### ISSUE TITLE
CSI Driver plugin attach method should return device path

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/kubernetes#70852]
**What happened**:
In-tree CSI driver [returns attachment ID](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L123) for `Attach` method (similarly for `WaitForAttach` method)

**What you expected to happen**:
It should return device path per [volume interface definition](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L123) 

**Anything else we need to know?**:
This affects CSI migration where in-tree driver is migrated to CSI while using old PV spec, `volumeAttached` field on node will be shown as:
```
  volumesAttached:
  - devicePath: csi-b7a72fc7d19e2b8f44332833e726788c8afe1be897e6faaabd92cedc47a84cff
    name: kubernetes.io/aws-ebs/vol-0eedee73dff51ca75
```
**Environment**:
- Kubernetes version (use `kubectl version`): tested on leakingtapan:kubelet-migration-aws branch

/kind bug

**Comment by leakingtapan** [comment]
Investigated the issue. This is because `VolumeAttachmentStatus` doesn't contain any information related to device path. It only has `AttachmentMetadata` which might contain device path (in the case of EBS CSI driver, I use `devicePath` key for it) if the driver choose to report it otherwise this information will be missing. Is this intentional?

**Comment by davidz627** [comment]
Discussed with @leakingtapan and @saad-ali offline.

We will not be "fixing" this behavior. 
That being said we are removing the dependency that CSI has on the `devicePath` field: https://github.com/kubernetes/kubernetes/pull/71095 and plan to deprecate the field (removal in 1.15).

With CSI drivers `devicePath` should be passed through the `volume_context` with any other context required to pass between Create and Publish's.

With these two changes we will slowly phase out reliance on the `devicePath` node annotation completely. 

/close

**Comment by saad-ali** [comment]
> With CSI drivers devicePath should be passed through the volume_context with any other context required to pass between Create and Publish's.

Clarification it should be passed as `publish_context` from `ControllerPublishVolumeResponse` to both `NodeStageVolumeRequest` and `NodePublishVolumeRequest`.
