### ISSUE TITLE
[flake] kops-aws CI job is flaking

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#70867]
**Which jobs are failing**:
The `kops-aws` job is flaking heavily on both 1.13 and master.

**Which test(s) are failing**:

**Since when has it been failing**:
Started flaking Nov 1st, 2018.

**Testgrid link**:
- [1.13](https://testgrid.k8s.io/sig-release-1.13-blocking#kops-aws-1.13) (57 fails in 165 runs in the past week)
- [master](https://testgrid.k8s.io/sig-release-master-blocking#kops-aws-master) (97 flakes in 302 runs in the past week)

/kind flake

**Comment by mariantalla** [comment]
Prioritizing as `critical-urgent` because of:
- proximity to code slush/freeze
- it's flaking on and off for a while
- it's in a blocking test suite

/priority critical-urgent

**Comment by AishSundar** [comment]
Seems like #10116 workaround helped the job. The Kops job is passing in both master and 1.13. Close this issue now.

/close
