### ISSUE TITLE
Windows e2e test image redis: "/bin/bash /run.sh" not found

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#70879]
CI tests for windows in GCE: https://testgrid.k8s.io/google-windows#windows-prototype
The tests use the repo-list: https://raw.githubusercontent.com/e2e-win/e2e-win-prow-deployment/master/repo-list.txt

Quite a few kubectl and deployment tests consistently fail because `/bin/bash run.sh`cannot be found in the windows redis test image.
```
Nov  9 16:53:18.651: INFO: At 2018-11-09 16:48:18 +0000 UTC - event for redis-master: {replication-controller } SuccessfulCreate: Created pod: redis-master-5mw24
Nov  9 16:53:18.651: INFO: At 2018-11-09 16:48:18 +0000 UTC - event for redis-master-5mw24: {default-scheduler } Scheduled: Successfully assigned e2e-tests-kubectl-vz2wk/redis-master-5mw24 to e2e-86-be9ce-minion-windows-group-mvxb
Nov  9 16:53:18.651: INFO: At 2018-11-09 16:50:48 +0000 UTC - event for redis-master-5mw24: {kubelet e2e-86-be9ce-minion-windows-group-mvxb} Pulling: pulling image "e2eteam/redis:1.0"
Nov  9 16:53:18.651: INFO: At 2018-11-09 16:51:48 +0000 UTC - event for redis-master-5mw24: {kubelet e2e-86-be9ce-minion-windows-group-mvxb} Pulled: Successfully pulled image "e2eteam/redis:1.0"
Nov  9 16:53:18.651: INFO: At 2018-11-09 16:51:57 +0000 UTC - event for redis-master-5mw24: {kubelet e2e-86-be9ce-minion-windows-group-mvxb} Created: Created container
Nov  9 16:53:18.651: INFO: At 2018-11-09 16:52:34 +0000 UTC - event for redis-master-5mw24: {kubelet e2e-86-be9ce-minion-windows-group-mvxb} Failed: Error: failed to start container "redis-master": Error response from daemon: container redis-master encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"/bin/bash /run.sh","WorkingDirectory":"C:\\redis","Environment":{"KUBERNETES_PORT":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP":"tcp://10.0.0.1:443","KUBERNETES_PORT_443_TCP_ADDR":"10.0.0.1","KUBERNETES_PORT_443_TCP_PORT":"443","KUBERNETES_PORT_443_TCP_PROTO":"tcp","KUBERNETES_SERVICE_HOST":"10.0.0.1","KUBERNETES_SERVICE_PORT":"443","KUBERNETES_SERVICE_PORT_HTTPS":"443"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```

@kubernetes/sig-windows-bugs 
@PatrickLang @adelina-t 

Is this expected or is there any wrong with our setup (e.g., a missing patch)? Thanks!

**Comment by PatrickLang** [comment]
Dockerfile is at https://github.com/e2e-win/k8s_images/tree/master/redis

**Comment by michmike** [comment]
@yujuhong the easiest way to check is to simply deploy the redis image locally and see if bash is in it

**Comment by PatrickLang** [comment]
@yujuhong can you share the specific case(s) that are failing?

**Comment by michmike** [comment]
i installed/deployed the redis image that @PatrickLang referenced above and there is no bash installed in it.

**Comment by yujuhong** [comment]
> @yujuhong can you share the specific case(s) that are failing? I want to see if they changed since this should have been passing during v1.11 or 1.12

@PatrickLang , am I pulling the wrong image?

I got the same error when trying to run the container using Docker on a Windows VM.
```
PS>  docker run -d e2eteam/redis:1.0
3ee107a32e3c47c7f61e5361bbf20b8b2eac52d18db6048edca8fc413e5357b0
C:\Program Files\Docker\docker.exe: Error response from daemon: container 3ee107a32e3c47c7f61e5361bbf20b8b2eac52d18db6048edca8fc413e5357b0 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"/bin/bash /run.sh","WorkingDirectory":"C:\\redis","CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
```

**Comment by michmike** [comment]
@yujuhong  that's what i got as well. i tried exactly what you did. i wonder if the test case was updated. can you share the context of the test case in terms of why it needs to run the bash command?

**Comment by yujuhong** [comment]
> @yujuhong that's what i got as well. i tried exactly what you did. i wonder if the test case was updated. can you share the context of the test case in terms of why it needs to run the bash command?

A couple of Deployment and kubectl tests using this image all failed, e.g., "Kubectl logs should be able to retrieve and filter logs"

@michmike I don't think the test itself was the problem. They didn't override the entrypoint in the container image. The redis image itself couldn't start up because it was looking for `/bin/bash`

**Comment by michmike** [comment]
@yujuhong in my case, the redis image started just fine. there was not issue in the image starting up and serving content. the /bash command is extra i believe and not needed by the image itself.
somewhere in the test is a command to execute something inside the container using bash ...can you please see what that is and paste it in this thread?

**Comment by yujuhong** [comment]
@michmike but in my case, I couldn't even run the container using docker directly (as pasted in my previous https://github.com/kubernetes/kubernetes/issues/70879#issuecomment-437502707). The container wouldn't come up at all.

I used `e2eteam/redis:1.0`. Was this the one you tested?

**Comment by michmike** [comment]
@yujuhong i used the dockerfile from https://github.com/e2e-win/k8s_images/tree/master/redis that Patrick sent and i created my own image. everything was successful and i was able to run...of course no bash was present.
![image](https://user-images.githubusercontent.com/6655749/48293967-30f56680-e447-11e8-9437-a0d05111093e.png)
![image](https://user-images.githubusercontent.com/6655749/48294017-75810200-e447-11e8-85b1-2b322e22f84d.png)

**Comment by yujuhong** [comment]
> @yujuhong i used the dockerfile from https://github.com/e2e-win/k8s_images/tree/master/redis that Patrick sent and i created my own image.

That's the difference. I am using the `e2eteam` repository from https://github.com/e2e-win/e2e-win-prow-deployment
I believe this hosts images used to run tests on Azure. 
@PatrickLang is this still the case, or is the recommendation for us to build and maintain our own image repositories?

**Comment by PatrickLang** [comment]
/assign @bclau 
cc @adelina-t

**Comment by adelina-t** [comment]
cc @bclau

**Comment by adelina-t** [comment]
@yujuhong The images in the e2eteam repository are built from the docker files that @PatrickLang indicated. We're checking to see if there is any change we pushed a broken image by mistake on one of the builds.

**Comment by bclau** [comment]
Hi. Can you specify which test does this? Because There's also no /run.sh included, so there might also be some other issues than the image itself.

The e2eteam/redis:1.0 [1] image is based on the kubernetes one [2], but with a Windows approach. As you can see in [2], there's no run.sh added.

[1] https://github.com/e2e-win/k8s_images/tree/master/redis
[2] https://github.com/kubernetes/kubernetes/blob/master/test/images/redis

**Comment by yujuhong** [comment]
@bclau the problem seems to have been resolved after the repush. The error no longer appears in our CI test. Thank you!
