### ISSUE TITLE
[sig-scheduling] ResourceQuota should create a ResourceQuota and capture the life of a configMap

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#70871]
**Which jobs are failing**:
[sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel)

**Which test(s) are failing**:
[sig-scheduling] ResourceQuota should create a ResourceQuota and capture the life of a configMap

**Since when has it been failing**:
November 8th, 2018

**Testgrid link**:
- [testgrid](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel)
- [Example failure](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/5524)

/kind failing-test

**Comment by mariantalla** [comment]
Hey, assigning `critical-urgent` priority to this one as we're close to code freeze and it's in a blocking test suite.

/priority critical-urgent

**Comment by bsalamat** [comment]
/assign @WanLinghao
Could you please take a look. The only recent change in this test is made by you.

**Comment by bsalamat** [comment]
cc/ @derekwaynecarr 

I still don't understand why resource quota tests are among of the scheduler tests.

**Comment by AishSundar** [comment]
@WanLinghao this job is continuously failing. any updates on this?

**Comment by WanLinghao** [comment]
@AishSundar sorry for the delay，I am working on it

**Comment by AishSundar** [comment]
@WanLinghao as @bsalamat mentioned [your commit](https://github.com/kubernetes/kubernetes/commit/efac533f9269ca1687d084a7360f87f7b4ace1fc) seems to be the last thing that touched the test and it started failing post that (NOv 7th).  For starters can we try reverting your PR and see if that helps?

**Comment by AishSundar** [comment]
This test seems to be passing in the latest runs based on a new test-infra commit. Lets watch for a couple more runs before closing this issue out.

**Comment by AishSundar** [comment]
this passed for 4 runs now.  @mariantalla plz close this as you see fit. Thanks

**Comment by mariantalla** [comment]
Closing as the job is passing consistently.

/close
