### ISSUE TITLE
Downgrade cluster tests are failing with connection refused errors

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#70873]
**Which jobs are failing**:
[sig-release-master-upgrade#gce-master-new-downgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-master-new-downgrade-cluster)

**Which test(s) are failing**:
- [UpgradeTest](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1077)
- [[sig-cluster-lifecycle] Downgrade [Feature:Downgrade] cluster downgrade should maintain a functioning cluster [Feature:ClusterDowngrade]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1077)
- [[sig-apps] replicaset-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1077)
- [hpa-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1077)

**Since when has it been failing**:
November 8th, 2018

**Reason for failure**:
They all fail with:
```
Get https://<REDACTED>/apis/apps/v1/namespaces/e2e-tests-sig-apps-replicaset-upgrade-fhrmc/replicasets/rs: dial tcp <REDACTED>:443: connect: connection refused
not to have occurred
```

/kind failing-test

**Comment by AishSundar** [comment]
/assign @justinsb @roberthbailey @zmerlynn 

This seems like a new issue that started manifested in this morning's run, Its concerning since downgrade jobs were stable before then. @justinsb would you plz be able to investigate and triage as priority? Thanks !

**Comment by justinsb** [comment]
I suspect this is another blip when the apiserver is restarting because of the overly aggressive health check (https://github.com/kubernetes/kubernetes/issues/70305), but haven't been able to find the log to prove it yet

**Comment by AishSundar** [comment]
True to what @justinsb pointed out, this seems to be a transient issue, the job is passing. Will close this issue now and reopen if need be.

/close
