### ISSUE TITLE
APIserver returns status code 500 instead of 400 when passed an incorrect pod create request

### ISSUE THREAD

**Issue by madhuri-rai07** [kubernetes/kubernetes#7087]
$ kubectl create -f pod.yaml
F0421 01:01:26.609520   26289 create.go:83] unable to load "wron_pod.yaml": error unmarshaling JSON: json: cannot unmarshal string into Go value of type v1beta3.PodSpec
```
$ cat pod.yaml
apiVersion: v1beta3
kind: Pod
metadata:
  name: error
  labels:
    test: value
spec: test
containers:
  - name: nginx
    image: dockerfile/nginx
```

**Comment by roberthbailey** [comment]
What version of kubectl are you using (you can run `kubectl version -c`)? v1beta3 wasn't fully supported until the 0.15.0 release. Prior to that you needed to manually enable a pre-release version with a command line flag, and we explicitly didn't guarantee compatibility between kubectl and the apiserver as the api was in development.

**Comment by nikhiljindal** [comment]
The string "test" in front of "spec" seems incorrect.
Removing that might fix the problem.

**Comment by madhuri-rai07** [comment]
$ kubectl version -c
Client Version: version.Info{Major:"0", Minor:"11+", GitVersion:"v0.11.0-323-g754a2a8305c8", GitCommit:"754a2a8305c812121c3845d8293efdd819b6a704", GitTreeState:"clean"}

I have tested the same with client API and same error occurred resulting in 500 status. 

@nikhiljindal I know the input is incorrect but that should not result in 500 status. It worked well with correct input.

**Comment by madhuri-rai07** [comment]
I have enabled v1beta3 by following https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook/v1beta3

**Comment by nikhiljindal** [comment]
ok Thanks for clarifying @madhuri-rai07.
The bug then is that the response status code should be 400 and not 500 when the input yaml is invalid.

**Comment by madhuri-rai07** [comment]
Yes.
Thanks Nikhil.

**Comment by bgrant0607** [comment]
Specifically, the server should return 422 (StatusUnprocessableEntity), via NewInvalid:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/errors/errors.go#L162

However, this error is being generated by the client, not by the server. kubectl currently decodes API objects, which it shouldn't but that's another issue #3955.

**Comment by lavalamp** [comment]
Wait, this is from April. Please reopen if still an issue.

**Comment by nikhiljindal** [comment]
I just retried it.
```kubectl create -f wrong_pod.yaml``` returns:
```yaml: line 7: mapping values are not allowed in this context``` which is a client generated error (We can definitely improve the error message)

```curl -X POST -d @/tmp/wrong_pod.json http://localhost:8080/api/v1/namespaces/default/pods``` returns 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Pod): couldn't get version/kind; json parse error: invalid character 't' after object key:value pair",
  "reason": "BadRequest",
  "code": 400
}
```
