### ISSUE TITLE
Is it possible to update the pod spec like priority class Name ?

### ISSUE THREAD

**Issue by ravishankarsrrav** [kubernetes/kubernetes#70906]
`/priorityClassName` `/Container` `/spec`

**Comment by shubheksha** [comment]
Hi, the GitHub issue tracker isn't the best place to ask for support regarding the operation of Kubernetes. Please try one of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) listed instead.

**Comment by liggitt** [comment]
only very limited portions of pod specs are mutable (image, adding tolerations, and shortening the activeDeadlineSeconds)

/close
