### ISSUE TITLE
[Failing Test] gce-new-master-upgrade-master job timing out in Release master-upgrade dashboard

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#70912]
**Which jobs are failing**:
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master

**Which test(s) are failing**:
The job has been [Timing out](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1874)

**Since when has it been failing**:
11/7.  [Changelist with possible culprit](https://github.com/kubernetes/kubernetes/compare/5bfe2967a...12be2444c?)

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master

**Reason for failure**:
Kubetest timed out

/kind failing-test
/sig cluster-lifecycle
/assign @justinsb 
/cc @roberthbailey @jberkus @mariantalla @mortent 
/priority critical-urgent
/milestone v1.13

@justinsb can you please take a look and help triage ^^

**Comment by justinsb** [comment]
@AishSundar  when you said "changelist with possible culprit" - was there one you had in mind, or that's just the list?

**Comment by AishSundar** [comment]
@justinsb I didnt have any specific CL in mind and yes the list is long (we should have caught this issue earlier). We cut our Beta and 1.13 branch  on 11/7 (5pm pST) and that's why you see the switch from 1.11 to 1.12. Coincidentally the job started timing out from the run post the branch switch. Briefly glancing at the logs it looks like the actual upgrade passed fine. but i see a lot of connection timeouts ```--connect-timeout 1 http://35.239.122.153:30252/hostName``` and ```Waiting for GCE PD "bootstrap-e2e-3189e20e-e511-11e8-9ab1-0a580a3c6c84" to detach from node "bootstrap-e2e-minion-group-nb5n".``` which caused the entire job to hit 15h timeout limit.

**Comment by AishSundar** [comment]
FWIW here's an healthy run log to compare with https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1869?log#log

**Comment by jberkus** [comment]
Hey, a bunch of other tests have been timing out too, looks like the same issue:

* https://k8s-testgrid.appspot.com/sig-release-1.13-all#gce-1.12-1.13-upgrade-cluster
* https://k8s-testgrid.appspot.com/sig-release-1.13-all#gce-1.12-1.13-upgrade-cluster-new
* https://k8s-testgrid.appspot.com/sig-release-1.13-all#gce-1.12-1.13-upgrade-master
* https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-1.12-1.13-upgrade-cluster
* https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-1.12-1.13-upgrade-cluster-new

Not all of them started on 11/7 (a few were failing before that) but 3 of the above did.

**Comment by AishSundar** [comment]
ahh those jobs are in the 1.13-all dashboard.. good catch @jberkus. So basically any upgrade (master or cluster) from 1.12 to 1.13 seems to timeout. The symptoms are the same, the upgrade itself seems to have happened fine ([from gubenator logs](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster/756)) but the jobs timeouts at 15hr

**Comment by AishSundar** [comment]
/cc @jbartosik @MaciekPytel 

@justinsb @jbartosik considering the tests started timing out from 11/7, I was looking at the changes that went in on 11/7 and I found the following 2 PRs

* CP of HPA test fixes onto 1.12 branch - [PR#0739](https://github.com/kubernetes/kubernetes/pull/70739)
* Overflow issue on renewal - [PR#70768](https://github.com/kubernetes/kubernetes/pull/70768)

I am thinking it must be related to the HPA cherrypick, since the [HPAtests are not running anymore](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master) on the gce-upgrade job after the CP

Hope this helps in narrowing down a bit?

**Comment by AishSundar** [comment]
Also I see all the upgrade tests actually passing on the runs. its timing out post that on some test.. So I am assuming Upgrade itself isnt broken.. @justinsb please confirm if this is right.

**Comment by AishSundar** [comment]
Post [PR#10134](https://github.com/kubernetes/test-infra/pull/10134) splitting the [gce-new-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master) into [parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel) and [non-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master) runs, the new parallel job passed - https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel. So as suspected, upgrade functionality is fine!

Waiting on the new run of the non-parallel job to see whats causing the timeout.

**Comment by jbartosik** [comment]
I took a look and tests are going overtime. Before they took about 13h to run, now they timeout after 15h. This may be caused by fixing HPA tests. Those tests have 3 phases: scale 1, stabilization wait, scale 2. Before they flaked during stabilization phase. If they pass it now they will take longer (remaining stabilization + time for the second scale).

**Comment by AishSundar** [comment]
The latest runs are now passing. I see thw HPA tests pass too

https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master

@jberkus @justinsb

**Comment by jberkus** [comment]
I'll close this as soon as we address porting the fix to the 1.13-uprade tests.

**Comment by AishSundar** [comment]
Yes we will need to apply the same resolution to  1.13 jobs as noted https://github.com/kubernetes/test-infra/pull/10134#issuecomment-438087120

**Comment by AishSundar** [comment]
#10145 merged ! So ww should hopefully see 1.13 upgrade jobs cleanup as well in next few runs

**Comment by AishSundar** [comment]
Annnd, i see the new parallel jobs passing in 1.13 https://k8s-testgrid.appspot.com/sig-release-1.13-all#gce-1.12-1.13-upgrade-cluster-parallel

Lets wait for the non-parallel ones to pass in the next run before we close this.

**Comment by jberkus** [comment]
There are still upgrade tests failing/timing out, but it's for different reasons.  Closing this issue.

/close
