### ISSUE TITLE
Kubelet node status based on CRD Installation

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#70911]
As we move to using CRD's more we have use cases for not letting the Kubelet be schedulable until certain CRD's have been installed or certain initialization actions have been performed with them. It would be nice to have a generic feature that hooks into Kubelet Node Status Ready Condition that can check whether certain CRD's are installed or not and post an error (and make Kubelet NotReady) if those CRD's are not available.

This becomes more important as many core (required for functionality) new Kubernetes API's are being made into CRDs. Without the CRD installed some core functionality will not work so we need a mechanism to ensure that the CRDs exist.

Functionality has a dependency on: #70910

/cc @saad-ali 
/sig node
/sig api-machinery

/kind feature

**Comment by saad-ali** [comment]
CC @gnufied

**Comment by saad-ali** [comment]
Proposed logic:
```
// During CSI Plugin init on kubelet
if (“CSIPersistentVolume” feature gate exists) && (kubelet not running in "headless" mode) {
  if (feature gate for any CSI CRD is on) {
    if (CSI CRD NOT installed) {
      // Make node unschedulable with an event indicating that either required CRD must be installed (via addon) or “CSIPersistentVolume” must be disabled via feature gate.
    }
  }
} else {
  // Do not init CSI
  // glog.Warninf("CSI is disabled")
  // Continue normally
}
```

**Comment by lavalamp** [comment]
Please tolerate failures and make actionable events (or other status notifications) rather than impose requirements on the startup process. This makes the system much more reliable and failure tolerant, and teaches users how the system works while letting them fix their own problems.

**Comment by gnufied** [comment]
May be we should resort to warning users with an event on node object in 1.13 before making node NotReady in 1.14.  We document the add-on/requirement in release notes, so as cluster installation tools have a chance to catch up before it becomes mandatory.

**Comment by davidz627** [comment]
Discussed with @mbohlool @saad-ali @gnufied online (feel free to correct + add info if i'm misrepresenting here):

1.13:
    -CSINodeInfo CRD goes Beta, any features depending on CSINodeInfo have soft failure or default to "old" behavior if the CRD is not installed.

1.14
    -CSINodeInfo CRD goes GA, Kubelet is NotReady if CRD is not installed - there will have to be documentation for cluster up (admin action) to install the CRD.

**Comment by saad-ali** [comment]
For context: 

We definitely want to handle the non-existance of CRDs as gracefully as possible. But at v1.15, we want to enable migration of in-tree volume plugins to CSI, and at some point afterwards the in-tree plugin code will be deprecated (deleted). Migration will depend on these CRDs. We don't want to surprises users who do not install the CRD suddenly with the deletion of the in-tree plugin code. So we want to signal the CRD requirement as early as possible.

Plan of action

* For v1.13, CSI will work without CSI CRDs and the specific CSI features that depend on the CRDs will fail if the CRDs don't exist (these features include topology, pod workload info, skip attach).
* For v1.14 CSI will require the CSI CRDs to be installed -- exactly how we do this needs to be decided (e.g. kubelet put in NotReady during initialization until CRDs exist?) we can decide then.

xref  https://github.com/kubernetes/enhancements/issues/615

**Comment by lavalamp** [comment]
Don't forget that nodes may lag the control plane by 2 releases. Are the versions you give control plane or node versions?

**Comment by davidz627** [comment]
> Don't forget that nodes may lag the control plane by 2 releases. Are the versions you give control plane or node versions?

node versions.
Requiring CRDs to be installed in 1.14 allows master components to start depending on the CRD existence at 1.16 IIUC.

**Comment by xmudrii** [comment]
Hello,

I'm a bug triage shadow and I'd like to remind that code freeze is starting tomorrow (Thursday) PST EOD. :snowflake: :mountain_snow: Is this issue going to be fixed in the upcoming days?

**Comment by davidz627** [comment]
No longer necessary for Storage work. I can leave the issue open as I think there may be a more general use case. But this is definitely not a `v1.14` issue anymore. Lets say
/remove-lifecycle stale
/priority important-longterm
