### ISSUE TITLE
[sig-apps] "DaemonRestart [Disruptive] Kubelet should not restart containers across restart " fails in Release master-upgrade dashboard

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#70913]
**Which jobs are failing**:
[gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new) in Release upgrade dashboard

**Which test(s) are failing**:
[[sig-apps] DaemonRestart [Disruptive] Kubelet should not restart containers across restart](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1789)

**Since when has it been failing**:
Since 11/9. [Delta Changelist](https://github.com/kubernetes/kubernetes/compare/941010e53...fb1fd1cce?)

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new

**Reason for failure**:
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:154
Nov 10 12:34:44.673: All nodes should be ready after test, Not ready nodes: ", bootstrap-e2e-minion-group-g61s"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:402

/kind failing-test
/sig apps
/priority critical-urgent
/milestone v1.13
/assign @kow3ns 
/cc @jberkus @mariantalla @mortent 

@kow3ns this test is continuously failing in release blocking upgrade tests since 11/9. Cn you please take a look as priority and help triage. Code freeze is approaching on 11/16 and its critical to get this addressed before then. Thanks.

**Comment by AishSundar** [comment]
@kubernetes/sig-apps-bugs

**Comment by AishSundar** [comment]
With Code freeze coming up this Friday 11/16,  this is a blocker for Beta.1 due to cut this Friday as well.

**Comment by mortent** [comment]
This seems to have passed the last five runs, but I will take a look at it first thing tomorrow.

**Comment by jberkus** [comment]
This has been passing for two days, I'm going to call it resolved.

/close
