### ISSUE TITLE
Consider replacing k8s.io/apimachinery/pkg/util/diff with github.com/google/go-cmp/cmp

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#70925]
`k8s.io/apimachinery/pkg/util/diff` is a test only package. `cmp` package has a superset of functionality and better error ourput. We do a lot of manual iterations like
 
https://godoc.org/github.com/google/go-cmp/cmp

Various tests can be simplified e.g.:

https://github.com/kubernetes/kubernetes/blob/8307fb2fb3ddd48cd8447e54978166f0c1123583/pkg/controller/certificates/rootcacertpublisher/publisher_test.go#L186-L201

to:

```go
if !cmp.Equal(expect, actions) {
    t.Errorf("unexpected actions:\n%s", cmp.Diff(expect, actions))
}
```
/kind cleanup

**Comment by RaviTezu** [comment]
Hi @dims,
I would like to take this up.

**Comment by dims** [comment]
@RaviTezu go for it

**Comment by mikedanese** [comment]
@RaviTezu the PR is already out. See #70929

**Comment by shivakrishna9** [comment]
Is this issue still open?

**Comment by mikedanese** [comment]
We are waiting for code freeze to be over before merging the fix.
