### ISSUE TITLE
Creating pod without volume configurations (Secret or configMap), with non-optional, the pod creation returns timeout exception after 5 minutes.

### ISSUE THREAD

**Issue by pontiyaraja** [kubernetes/kubernetes#70937]
**@kubernetes/sig-storage-feature-requests**

**What happened:**

From the reference of PR _https://github.com/kubernetes/kubernetes/pull/70299_
While adding new e2e test cases for secret and configMap

Creating pod without volume configurations (Secret or configMap), by setting optional value as false, the pod creation returns timeout exception after 5 minutes, because of failing to mount volume for pod. 

If it's slow, you're basically waiting for the kubelet to bounce vs. failing on admission to sanity check the deps in the manifest.  

_Originally posted by @timothysc in https://github.com/kubernetes/kubernetes/pull/70299_

**Comment by liggitt** [comment]
Can you clarify the scenario? Is this creating a pod with a non-optional secret or configmap volume, where the actual secret or config map does not exist?

**Comment by pontiyaraja** [comment]
@liggitt yes, that's the exact scenario.
