### ISSUE TITLE
kubectl cannot execute port forward

### ISSUE THREAD

**Issue by junsionzhang** [kubernetes/kubernetes#70938]
kubectl  port-forward   tiller-deploy-65fcff7ff6-7kjbb  -n kube-system 44134
error: error upgrading connection: unable to upgrade connection: Unauthorized

does anyone have advice to solve it? thanks a lot
/sig testing

**Comment by prksu** [comment]
please following issue template. at least specify your environment. it will help contributors to reproduce your issue.
