### ISSUE TITLE
API server should handle duplicate '/' in URL 

### ISSUE THREAD

**Issue by glbyers** [kubernetes/kubernetes#70942]
**What happened**:
In k8s 1.12.2, requests to API server for //version result in 404, whilst /version responds as expected.

**What you expected to happen**:
Duplicate URL path separators should be squashed. ie. //version and /version are equivalent. Same for other paths (//metrics, //healthz, etc.)

**How to reproduce it (as minimally and precisely as possible)**:
```curl http://127.0.0.1:8080//version``` gives 404 and a list of supported paths.

**Anything else we need to know?**:
k8s 1.12.2

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
n/a

- OS (e.g. from /etc/os-release):
```CentOS Linux release 7.5.1804 (Core)```

- Kernel (e.g. `uname -a`):
```Linux master-54c86b5a30c7.node.dev.consul 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

- Install tools:
ansible

- Others:

@kubernetes/sig-api-machinery-bugs

/kind bug

**Comment by liggitt** [comment]
is there a good reason to tolerate incorrect paths like that?

**Comment by glbyers** [comment]
It seems to be a widely held convention that // is equivalent to / in a path. This is certainly true wrt Unix/Linux filesystem hierarchy and holds with web servers like Apache and Nginx. 

As far as reasoning goes, consider that a client may take a configurable/user defined API server URL (let's call it k8s_api_url) which may or may not have been defined with a trailing slash. Sanitisation issues aside, the following should work regardless of whether the user had defined k8s_api_url with or without a trailing slash.

```'/'.join([k8s_api_url, 'version'])```
  
Which would work just fine had the use defined k8s_api_url as "http://127.0.0.1", but not as "http://127.0.0.1/".

**Comment by roycaihw** [comment]
Agree that invalid url like this should be handled on client side. Fix for tolerating host url with trailing slash in python client has been merged.
