### ISSUE TITLE
Clients using kubeconfigs that load certificates from disk should reload credentials on rotation

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#70958]
This will happen more and more now and we need to not break clients that use the node credential.

/kind bug
/sig auth

@kubernetes/sig-auth-bugs

**Comment by mourya007** [comment]
@mikedanese  Is this bug still exist ?

**Comment by mikedanese** [comment]
Yes, it's still not handled.

**Comment by mourya007** [comment]
@mikedanese Could you specify how can i help in this issue ?

**Comment by awly** [comment]
I started working on a PR but didn't have time to finish it off yet.
This is tricky, because we technically support passing cert as a file and key as a blob (or vice versa) in `kubeconfig`.

Anyway, I'll work on it some more, unless @mourya007 you'd like to give it a go
