### ISSUE TITLE
Changing node-cidr-mask-size confuse range allocator; leads to PodCIDR overlapping

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#70957]
When having an existing cluster integrating with a cloud-provider and having under-sized nodes, changing max-pods and ultimately the `node-cidr-mask-size` leads the `RangeAllocatorType` to allocate overlapping using the newly constructed `CidrSet`

FYI @lledru @kubernetes/sig-cloud-provider 

/assign
/kind bug
/sig network
/sig cloud-provider

**Comment by thockin** [comment]
In general the node's PodCIDR field is not mutable.

Can you provide more details on what you are doing that leads up to this?  Help us to reproduce it..

**Comment by yastij** [comment]
@thockin - when you start a cluster with a node-cidr-mask-size=27, then try to expand it to 24, delete a node and restart the kubelet, you’ll see that this leads the range_allocator (especially the cidr_set) to allocate an overlapping cidr since it has no idea about having heterogeneous cidr sizes.

This usually happens when you want to add more pods per node (or more ips available per node)

**Comment by thockin** [comment]
The long-story-short on this is that it is not supported.

We could make the CIDR range allocator smarter here, but this is a feature-request more than a bug.

**Comment by yastij** [comment]
@thockin - I can start a KEP with some usecases
