### ISSUE TITLE
1.13 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by marpaia** [kubernetes/kubernetes#70955]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.13 Release Notes. If you know of issues or API changes that are going out in 1.13, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @marpaia 

/sig release
/milestone v1.13

**Comment by AishSundar** [comment]
@saad-ali @msau42 This is an umbrella issue to gather list of known issues and workaound in 1.13. Can you please add the note and workaround for https://github.com/kubernetes/kubernetes/pull/70716 (promoting GCE RePD support to GA in Kubernetes) discussed in the email thread offline. Thanks

**Comment by AishSundar** [comment]
1 more item to followup for release notes and/or known issue - https://github.com/kubernetes/kubernetes/pull/71020#pullrequestreview-175296511

**Comment by msau42** [comment]
cc @verult for documenting known repd naming issue

**Comment by AishSundar** [comment]
As mentioned in #71020 's release notes section, CSI is intentionally not backwards compatible between 1.12 and 1.13. xref: https://github.com/kubernetes/kubernetes/issues/65246#issuecomment-439710126

**Comment by liggitt** [comment]
CSI compatibility issue above was resolved in beta.1

**Comment by AishSundar** [comment]
One more known issue related to CSI raciness - https://github.com/kubernetes/kubernetes/pull/71440#issuecomment-442258737

**Comment by saad-ali** [comment]
Also, flex volume resize issue: https://github.com/kubernetes/kubernetes/issues/71470

**Comment by AishSundar** [comment]
Also CSI driver registartion latency - https://github.com/kubernetes/kubernetes/issues/71383#issuecomment-442161755

@saad-ali ^^

**Comment by saad-ali** [comment]
> Also CSI driver registartion latency - #71383 (comment)

This issue is an caused by an external sidecar container (driver-registrar). Once it is fixed on the external sidecar, the issue will not exist with 1.13.0. So it does not make sense to capture it in Kubernetes release notes.

Instead the release notes for the external-container should capture this (I'll take care of that).

**Comment by saad-ali** [comment]
> One more known issue related to CSI raciness - #71440 (comment)

This is not actually a raciness issue. Regardless, the actual issue from 71440 is already captured in the release notes under `if kubelet plugin registration for a driver fails, kubelet will not retry...`

**Comment by marpaia** [comment]
So, thanks to @saad-ali, CSI raciness is represented in the notes and CSI driver registration latency does not require a known issue note.

In working with @gnufied, he came up with this note, which I've added to the known issues section of the doc:

> In come cases, a PVC may have erroneous Resizing condition even after volume has been successfully expanded. Users may choose to delete the condition, but it is not required.

**Comment by saad-ali** [comment]
> In come cases, a PVC may have erroneous Resizing condition even after volume has been successfully expanded. Users may choose to delete the condition, but it is not required.

LGTM

**Comment by marpaia** [comment]
All known issues up until this point are represented in the PR for the "final" release notes doc here: https://github.com/kubernetes/sig-release/pull/386
