### ISSUE TITLE
Calico 无法正常启动

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#70976]
Readiness probe failed: Get http://172.16.5.118:9099/readiness: dial tcp 172.16.5.118:9099: connect: connection refused

使用caclio 官网的配置文件 version 3.1.3 
netstat -lntp | grep 9099  
9099 端口并没有监听起来

**Comment by vsxen** [comment]
用什么安装的？calico 具体日志？怎么重现？

请不要发这些没有任何有用信息的issue    提问前请按照issue模板  
尽量翻译为英文https://translate.google.com/

I can not find any useful information, close it first.

/close

**Comment by gitplyx** [comment]
kubectl logs calico-kube-controllers-6f6d7d7c94-mkj4r -n kube-system 
2018-11-13 14:05:19.934 [INFO][1] main.go 69: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"policy,profile,workloadendpoint,node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:""} 2018-11-13 14:05:29.939 [FATAL][1] main.go 81: Failed to start error=failed to build Calico client: context deadline exceeded


 kubectl describe pod calico-kube-controllers-6f6d7d7c94-mkj4r -n kube-system
Normal Pulled 53m (x53 over 5h) kubelet, 172.16.5.118 Container image "docker.runsdata.com/calico/kube-controllers:v3.1.3" already present on machine 
Warning BackOff 3m (x1301 over 5h) kubelet, 172.16.5.118 Back-off restarting failed container

安装方式 k8s 使用 caclio 官网 caclio.yaml 部署
Calico Version v3.1.3 # https://docs.projectcalico.org/v3.1/releases#v3.1.3 # 
This manifest includes the following component versions: 
# calico/node:v3.1.3 # calico/cni:v3.1.3 # calico/kube-controllers:v3.1.3
 # This ConfigMap is used to configure a self-hosted Calico installation. 
kind: ConfigMap 
apiVersion: v1 
metadata: name: calico-config 
namespace: kube-system data: 
# Configure this with the location of your etcd cluster. 
etcd_endpoints: https://172.16.5.117:2379,https://172.16.5.118:2379,https://172.16.5.119:2379
 # Configure the Calico backend to use. calico_backend: "bird" 
# The CNI network configuration to install on each node.
 cni_network_config: |- 
{ "name": "k8s-pod-network", "cniVersion": "0.3.0", 
"plugins": 
[ { "type": "calico", 
"etcd_endpoints": "__ETCD_ENDPOINTS__", 
"etcd_key_file": "__ETCD_KEY_FILE__", 
"etcd_cert_file": "__ETCD_CERT_FILE__",
 "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__", 
"log_level": "info", "mtu": 1500,
 "ipam": { "type": "calico-ipam" }, 
"policy": { "type": "k8s" }, 
"kubernetes": { "kubeconfig": "__KUBECONFIG_FILEPATH__" } },
 { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} } ] } 
# If you're using TLS enabled etcd uncomment the following. 
# You must also populate the Secret below with these files. 
etcd_ca: "/calico-secrets/etcd-ca" 
etcd_cert: "/calico-secrets/etcd-cert" 
etcd_key: "/calico-secrets/etcd-key" --- 
# The following contains k8s Secrets for use with a TLS enabled etcd cluster. 
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/ 
apiVersion: v1
 kind: Secret 
type: Opaque 
metadata: name: calico-etcd-secrets 
namespace: kube-system data: # Populate the following files with etcd TLS configuration if desired, but leave blank if # not using TLS for etcd. # This self-hosted install expects three files with the following names. The values 
# should be base64 encoded strings of the entire contents of each file. 
etcd-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNFNDSmZicTVBV2N4VUlTckcvT1JnRUYwcjBteG9jZHNBVWVNbUdJZi9MZ0srRTlPClVuWDhhWkh3bk53VjFZTTVkVTZQUGI3QjZ4c0h0V1VZTTBaZDlhNXZubWI1eS9MTnZoOElVNlpkMDRVM3VneG0KVzJtY3FzeDJuSGh2YWJWR3o5bFJ2LzNJOUhHM1VxRlhiNjgva05MTEkrRlhPUElTSXpmM0JobVFyaTg4dGN6Rwp6K0dxRXo1QWRqcW41RVMyYUVRMThob1pIUUdPZXpYSllYU0pyVHRnL2MvSjF1ekhrMCs2S3NWZnVvVWF5THB2Clo0TzBkUFgzWmQ0OHh6ODdlWitSOFNhTi9iNzhHK1J3TEptNTRNeGNjOGNiMWo0VU54VzFLTkpPQmFWbTdnY2sKVzVlUXZZdG9HU2t1d1VtUm9DUmpDUWJJNjdvaDNVK0liQVA1YlFJREFRQUJBb0lCQUh4d3djOVA0V2ZYSkxrLwpQRjRNK3NhTVovVmtwTjJxSUJkczkxaGNGUlphblNXNG9MQ1FLMkFublhyM1pOSks0UDNvMk9EbWlzWnNnSXhTClAxaEljek9Vb25wS3JaV0F0eDE2aGQzSFBtSG5aM0JkM2s1MVNIWlk0cytHK3Y3Umh6enBBWGxBelUzaGRkWWsKL1BIdFN4UEFrUzFhS0I2QUlHcDdTdjZDTHlrNFJjTEU4ZllwUUJ0bmgyUFdRYnUwTFZxei9MOTlIOVV3cVNrbQpPMVFvdEhFelgyczRkTEhISFFrb1hsM2VXSk9yM010dldKQUZHWTRaQStxUGZKNGw0QnJuQ0hDOFVuaWFyS1NHCktKdStWdjlVNWR4bHlkN1QvTjVZK0FUaXBSbXFKU2RmM0hoRDRoNFNiWVN0akludVp6VjVzQ2gvK2hqT3lmUVgKa3VmWVVZRUNnWUVBOUd5ZUFHeVVsalZ3c0pobXo5c0c1YlVZQ1ZVWW9kS2NtRC9abnpoT1dtdTdmb2JRNm5uSQp1dy9rd0lCbm9DYmI2aHUyU29aNG85ditSZU8zUW11Z01jd2Mra2Fha0hCWE04a3VuaWhYWFoxMGcvZEdtVndWClh4UVdZVHFNUzYwQTdRNWxjVHhpZHp0L3VPWGJYT1htTVI0dTg5R1VETERTd3pPUzNsU0d0VkVDZ1lFQTY4bjIKVG5VV0tzV3Qvd3VKcVFPbExoMjNLcnk4ZjlNMEFEMWZDMmRMUFFYRjBCS3RTMm1xR1czd2JWVVVaSEdqY3RxVQo0cHlSbm1QeTQwMi8zYVFtbmw3cmUxU0daakN5R2d4eWJJSzBkSEtpY3F4eC9pQjBhS0UxN0ViWDZNcHNKZmRsCm9pa3JSaTh0VnREYlRUUWp6NE5TeGs1TkZGVXZrb3AyZjZySHExMENnWUVBNklYMEFaOUo4Mk8vWXFCNUhqL1YKWGUxYmduVkx5NVphbHBRWGFWcmRYek9oMklwVWNOdU9WRGFZZlhFcUk3Y1QrckNHU0h1SWhRbWg2Y2JwN2V3SgpKNVp2OHIvOEJuQjQ1TEQ5QWtTS2FHcUVENDdMd05WVEYzSTZvQ0JjbXhsb0NoeHA4TUZyUXRaOWVONWlRd3dLCllxdStLd0V6Z0tjdXViaDBmY0dYclNFQ2dZRUF5RGJCR0JQaUU4V3hubXpNb3FCK3hTN2tWcnpXanUvbkt3RHgKMEx3UUxpdlZzWDM2ZXB1cG5WZzJISkJ1OVc5dEs5eWhLZDlxNHdUWnZOdExQVWZpcHYzUWxQUEwvNy8vcTVEQQpKSlhENTFGajBWM09tY3d6TEprZk1aZGlSTUNGbnFONVFINFd5Y3pMZ2ZsdERoeGxBQkx4MllPcGZjZHIwdElTCkZ3d0w2ZDBDZ1lBT3AzbHBuaWFEVDRDS3ZiaFdOODgwSHhFMTE0cDNzZWRGMmRmaDJjaVgvbnFGOGowZS90RUQKR3hLR2pyaGk2UnJLUndTSy9rNTVtbjNUWmkxUjAzZVM2OVVseEdtekR4Y2QrdlFsbGhUakFwUGpVTkxaWHpLbApzVk5WN0d0ZHRDT3R6Y1RabXpBQXNOaEhLVXRLaEZhN1pwRGtlOFRjcXE1OU5VNnp6YVdrOFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo= 
etcd-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUlsZ2E3TmhId2x4TUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014RXpBUkJnTlYKQkFNTUNtdDFZbVZ5Ym1WMFpYTXhEREFLQmdOVkJBb01BMnM0Y3pBZUZ3MHhPREE0TWpRd05qTXhOVFZhRncwMApOakF4TURrd05qTXhOVFZhTUI0eERUQUxCZ05WQkFNTUJHVjBZMlF4RFRBTEJnTlZCQW9NQkdWMFkyUXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGhJSWw5dXJrQlp6RlFoS3NiODVHQVFYU3YKU2JHaHgyd0JSNHlZWWgvOHVBcjRUMDVTZGZ4cGtmQ2MzQlhWZ3psMVRvODl2c0hyR3dlMVpSZ3pSbDMxcm0rZQpadm5MOHMyK0h3aFRwbDNUaFRlNkRHWmJhWnlxekhhY2VHOXB0VWJQMlZHLy9jajBjYmRTb1ZkdnJ6K1Ewc3NqCjRWYzQ4aElqTi9jR0daQ3VMenkxek1iUDRhb1RQa0IyT3Fma1JMWm9SRFh5R2hrZEFZNTdOY2xoZEltdE8yRDkKejhuVzdNZVRUN29xeFYrNmhSckl1bTluZzdSMDlmZGwzanpIUHp0NW41SHhKbzM5dnZ3YjVIQXNtYm5nekZ4egp4eHZXUGhRM0ZiVW8wazRGcFdidUJ5UmJsNUM5aTJnWktTN0JTWkdnSkdNSkJzanJ1aUhkVDRoc0EvbHRBZ01CCkFBR2pQVEE3TUFrR0ExVWRFd1FDTUFBd0N3WURWUjBQQkFRREFnWGdNQ0VHQTFVZEVRUWFNQmlIQkg4QUFBR0gKQkFvQUFJMkhCQW9BQUk2SEJBb0FBSTh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUZ4RVRMYUlRT0hTVXVCVgpTYndKN1U1VXVINEVnem8vYUF4VUdpa1hRVEQrNmptNFo1SkU4WjQvdC9vRC9Ub3ZZbzZLNmJ0NHhrUDhUUXJ1CjQ1WEJBNDlwaGN5UHE3Q0ZyQkJqQ0laNHpqUDdRRDVVdERoWHhCcjhod1ZMaVNVZExoRmZza0M4ZWd1dTlkQmMKWXlGYXV2RjZJVzRBZ0p6TlVtT2Y4K3V3U2tyZUIrbnJpZXViSVVsVHRqQzVrbjE5VFRnWXJ1YUdScXlTaFBRVwpWaGV1ck83V3JLV1dzZ2pSendOYUN0V2FSMmNGdjB5UEd4dUpBSlF5SGUzeS9qTWVLbXE5K0UyWmdraStQWmI0CjUzWlNjbzZ1SVMwZlJhakwzdC9vQm5hdEs2YkYwU0JDRVdHWDBJVWFab1VMb25CTS92a3Z4SDNEYWNYWDNVYTIKYXZiREk4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= 
etcd-ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lKQVBHeGJmbE5hZ3QxTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014RXpBUkJnTlYKQkFNTUNtdDFZbVZ5Ym1WMFpYTXhEREFLQmdOVkJBb01BMnM0Y3pBZUZ3MHhPREE0TWpRd05qTXhOVFZhRncwMApOakF4TURrd05qTXhOVFZhTUNNeEV6QVJCZ05WQkFNTUNtdDFZbVZ5Ym1WMFpYTXhEREFLQmdOVkJBb01BMnM0CmN6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUw5RGpjbGhHbFRJaXlMMExOckoKQlh5NkhVUHJjS2VvVDF6b0Zzc05ucC9VSDF3blprUGNpeDVrOGhGaXhjeHBZYTZVemFCaG84TnJFd1dOZFBFagpvQ1o0amtHZTd6VFVrQTdPVXFUUi9va0F3Wnh3S0U3dXNHc0xLcGx0aG5LUkNmMGI4dU9Uemk0R0xhVytVY0Q3ClhNQVVrS3VKdnRFTU9wTWNsWHVDTERkREZJS0NlOTJvWFFQL21vR2JvMlNPVHJpTEozUm9QT3pSWUJlcGZQNzcKVnJNSnhMRjVNUUlyS0gzV0RGallBV2I2MHI4VXliMXc5SVBjclEvWnh5NTk4SmpLUUhxSXRZZ2tIakx5ZDFraQpneVdGZzVCNmU5NnhGOFF1SWtrQW1jMzZvMjBraVJ2MHNqSVc1emhDM3FaM3N1U0JTNkVQSURPTWNpdXFaRnFFCi82c0NBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGTUdhek50QzdodXZ3NDl0WGlabE1UR3NFbGpHTUI4R0ExVWQKSXdRWU1CYUFGTUdhek50QzdodXZ3NDl0WGlabE1UR3NFbGpHTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUQvNGFEbVl2ZkYwWURudGJqRE5nZlRNZjVVcEduVkI2WkJmazM4TzlWMFFocEpRCjM2di9zT01oS3hIU3BvRjNjdkxVQUVzdGsxczFaUnJiajJaVy9WRFNHVkl0Nlg2MWVMeDhJN21WQkxnUHlsV3YKZkQ4R1VVczBzc0RWUnJDR3laeTM0eWcvbTlGVUxjVlNuRzIzdFhhd1g2b0hqVU0rTkdDY3lWNlgrd2YrRGd5MwpOUGIxZStWbVpVRjhkaEUvZSs3MzNTWDVvbDFIOWJXUW5DY09ZMXBmc0JCK1BxdlFxZm92U0RNVEZ0aHFqMUNjCjZRQTIwcDZvNk00elVRRnA1SWFRVFdXMVdhd0YzWTNHVjJFL2ptU2Jwa0Nod3NwTFZuL1ZrYklhdkt1MUxpKzYKZWJyeFlVWnhnSk9zOUZ1ODAyeEg3aGxaaS9XV1ZINHF2Y0hRaFJBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== ---
 # This manifest installs the calico/node container, as well 
# as the Calico CNI plugins and network config on
 # each master and worker node in a Kubernetes cluster. 
kind: DaemonSet 
apiVersion: extensions/v1beta1
 metadata: 
name: calico-node 
namespace: kube-system 
labels: k8s-app: 
calico-node 
spec: selector: 
matchLabels: k8s-app: 
calico-node updateStrategy: 
type: RollingUpdate
 rollingUpdate: maxUnavailable: 1
 template: 
metadata: labels: 
k8s-app: calico-node 
annotations: scheduler.alpha.kubernetes.io/critical-pod: '' spec: hostNetwork: true tolerations:
 # Make sure calico/node gets scheduled on all nodes. - effect: NoSchedule operator: Exists
 # Mark the pod as a critical add-on for rescheduling. 
- key: CriticalAddonsOnly operator: Exists - effect: NoExecute operator: Exists serviceAccountName: calico-node # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods. terminationGracePeriodSeconds: 0 containers: # Runs calico/node container on each Kubernetes node. This # container programs network policy and routes on each # host. - name: calico-node image: docker.runsdata.com/calico/node:v3.1.3 # imagePullPolicy: IfNotPresent env: - name: IP_AUTODETECTION_METHOD value: interface=ens33 # The location of the Calico etcd cluster. - name: ETCD_ENDPOINTS valueFrom: configMapKeyRef: name: calico-config key: etcd_endpoints # Choose the backend to use. - name: CALICO_NETWORKING_BACKEND valueFrom: configMapKeyRef: name: calico-config key: calico_backend # Cluster type to identify the deployment type - name: CLUSTER_TYPE value: "k8s,bgp" # Disable file logging so `kubectl logs` works. - name: CALICO_DISABLE_FILE_LOGGING value: "true" # Set noderef for node controller. - name: CALICO_K8S_NODE_REF valueFrom: fieldRef: fieldPath: spec.nodeName # Set Felix endpoint to host default action to ACCEPT. - name: FELIX_DEFAULTENDPOINTTOHOSTACTION value: "ACCEPT" # The default IPv4 pool to create on startup if none exists. Pod IPs will be # chosen from this range. Changing this value after installation will have # no effect. This should fall within `--cluster-cidr`. - name: CALICO_IPV4POOL_CIDR value: "10.1.0.0/16" - name: CALICO_IPV4POOL_IPIP value: "Always" # Disable IPv6 on Kubernetes. - name: FELIX_IPV6SUPPORT value: "false" # Set Felix logging to "info" - name: FELIX_LOGSEVERITYSCREEN value: "info" # Set MTU for tunnel device used if ipip is enabled - name: FELIX_IPINIPMTU value: "1440" # Location of the CA certificate for etcd. - name: ETCD_CA_CERT_FILE valueFrom: configMapKeyRef: name: calico-config key: etcd_ca # Location of the client key for etcd. - name: ETCD_KEY_FILE valueFrom: configMapKeyRef: name: calico-config key: etcd_key # Location of the client certificate for etcd. - name: ETCD_CERT_FILE valueFrom: configMapKeyRef: name: calico-config key: etcd_cert # Auto-detect the BGP IP address. - name: IP value: "autodetect" - name: FELIX_HEALTHENABLED value: "true" securityContext: privileged: true resources: requests: cpu: 250m livenessProbe: httpGet: path: /liveness port: 9099 periodSeconds: 10 initialDelaySeconds: 10 failureThreshold: 6 readinessProbe: httpGet: path: /readiness port: 9099 periodSeconds: 10 volumeMounts: - mountPath: /lib/modules name: lib-modules readOnly: true - mountPath: /var/run/calico name: var-run-calico readOnly: false - mountPath: /var/lib/calico name: var-lib-calico readOnly: false - mountPath: /calico-secrets name: etcd-certs # This container installs the Calico CNI binaries # and CNI network config file on each node. - name: install-cni image: docker.runsdata.com/calico/cni:v3.1.3 imagePullPolicy: IfNotPresent command: ["/install-cni.sh"] env: # Name of the CNI config file to create. - name: CNI_CONF_NAME value: "10-calico.conflist" # The location of the Calico etcd cluster. - name: ETCD_ENDPOINTS valueFrom: configMapKeyRef: name: calico-config key: etcd_endpoints # The CNI network config to install on each node. - name: CNI_NETWORK_CONFIG valueFrom: configMapKeyRef: name: calico-config key: cni_network_config volumeMounts: - mountPath: /host/opt/cni/bin name: cni-bin-dir - mountPath: /host/etc/cni/net.d name: cni-net-dir - mountPath: /calico-secrets name: etcd-certs volumes: # Used by calico/node. - name: lib-modules hostPath: path: /lib/modules - name: var-run-calico hostPath: path: /var/run/calico - name: var-lib-calico hostPath: path: /var/lib/calico # Used to install CNI. - name: cni-bin-dir hostPath: path: /opt/cni/bin - name: cni-net-dir hostPath: path: /etc/cni/net.d # Mount in the etcd TLS secrets with mode 400. # See https://kubernetes.io/docs/concepts/configuration/secret/ - name: etcd-certs secret: secretName: calico-etcd-secrets defaultMode: 0400 imagePullSecrets: - name: registrykey --- # This manifest deploys the Calico Kubernetes controllers. # See https://github.com/projectcalico/kube-controllers apiVersion: extensions/v1beta1 kind: Deployment metadata: name: calico-kube-controllers namespace: kube-system labels: k8s-app: calico-kube-controllers annotations: scheduler.alpha.kubernetes.io/critical-pod: '' spec: # The controllers can only have a single active instance. replicas: 1 strategy: type: Recreate template: metadata: name: calico-kube-controllers namespace: kube-system labels: k8s-app: calico-kube-controllers spec: # The controllers must run in the host network namespace so that # it isn't governed by policy that would prevent it from working. hostNetwork: true tolerations: # Mark the pod as a critical add-on for rescheduling. - key: CriticalAddonsOnly operator: Exists - key: node-role.kubernetes.io/master effect: NoSchedule serviceAccountName: calico-kube-controllers containers: - name: calico-kube-controllers image: docker.runsdata.com/calico/kube-controllers:v3.1.3 imagePullPolicy: IfNotPresent env: # The location of the Calico etcd cluster. - name: ETCD_ENDPOINTS valueFrom: configMapKeyRef: name: calico-config key: etcd_endpoints # Location of the CA certificate for etcd. - name: ETCD_CA_CERT_FILE valueFrom: configMapKeyRef: name: calico-config key: etcd_ca # Location of the client key for etcd. - name: ETCD_KEY_FILE valueFrom: configMapKeyRef: name: calico-config key: etcd_key # Location of the client certificate for etcd. - name: ETCD_CERT_FILE valueFrom: configMapKeyRef: name: calico-config key: etcd_cert # Choose which controllers to run. - name: ENABLED_CONTROLLERS value: policy,profile,workloadendpoint,node volumeMounts: # Mount in the etcd TLS secrets. - mountPath: /calico-secrets name: etcd-certs volumes: # Mount in the etcd TLS secrets with mode 400. # See https://kubernetes.io/docs/concepts/configuration/secret/ - name: etcd-certs secret: secretName: calico-etcd-secrets defaultMode: 0400 imagePullSecrets: - name: registrykey

发送自 Windows 10 版邮件应用

发件人: k8s-ci-robot
发送时间: 2018年11月13日 21:51
主题: Re: [kubernetes/kubernetes] Calico 无法正常启动 (#70976)

@vsxen: You can't close an active issue/PR unless you authored it or you are a collaborator.
In response to this:
用什么安装的？calico 具体日志？怎么重现？
请不要发这些没有任何有用信息的issue 提问前请按照issue模板
尽量翻译为英文https://translate.google.com/
I can not find any useful information, close it first.
/close
Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository.

**Comment by vsxen** [comment]
看起来是 Kubeconfig的问题
the reason may be kubeconfig file？

https://github.com/projectcalico/kube-controllers/blob/release-v3.1/main.go#L79
