### ISSUE TITLE
kubernetes 1.12.2 failed to load Kubelet config file /var/lib/kubelet/config.yaml

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#70984]
**What happened**:
missing /var/lib/kubelet/config.yaml
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 18.10
- Kernel (e.g. `uname -a`):
- Install tools: Docker 18.9.0
- Others:
`failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory

Error syncing pod f0ab0f74-e6f2-11e8-8410-482ae31e6a94 ("nginx-ingress-microk8s-controller-c2pgz_default(f0ab0f74-e6f2-11e8-8410-482ae31e6a94)"), skipping: failed to "StartContainer" for "nginx-ingress-microk8s" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=nginx-ingress-microk8s pod=nginx-ingress-microk8s-controller-c2pgz_default(f0ab0f74-e6f2-11e8-8410-482ae31e6a94)"`

/kind bug

**Comment by neolit123** [comment]
please try our support channels like stackoverflow instead:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

also please provide detailed instructions on how you create the cluster.
thanks.

/close

**Comment by bilalcaliskan** [comment]
https://kubernetes.io/docs/setup/independent/kubelet-integration/
