### ISSUE TITLE
scheduler fails to schedule pods with antiAffinity

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubernetes#70996]
**What happened**: Pod failing to be scheduled due to antiAffinity. There's 3 pods, 2 currently scheduled. There's a free AZ (prior to doing a deployment rollout 3 pods had been scheduled successfully within the same antiAffinity rules)

On restarting the scheduler, the pod is scheduled correctly.

**What you expected to happen**: The pod to be scheduled

**How to reproduce it (as minimally and precisely as possible)**: Unsure. happens intermittently

**Anything else we need to know?**:

```
$ k describe pod kube-apiserver-7cdc45f85d-q7ts7 | tail -n 4
  Type     Reason              Age                From               Message
  ----     ------              ----               ----               -------
  Normal   PodDoestFitAnyNode  1m                 rescheduler        Critical pod kube-system_kube-apiserver-7cdc45f85d-q7ts7 doesn't fit on any node.
  Warning  FailedScheduling    11s (x16 over 2m)  default-scheduler  0/60 nodes are available: 2 Insufficient cpu, 5 Insufficient memory, 60 ExistingPodsAntiAffinityRulesNotMatch, 60 MatchInterPodAffinity.


$ k get pod -o yaml kube-apiserver-7cdc45f85d-q7ts7 | grep -A 10 affin
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: appId
            operator: In
            values:
            - kube-apiserver
        topologyKey: failure-domain.beta.kubernetes.io/zone
  containers:

$ k get pod -a -l appId=kube-apiserver
NAME                              READY     STATUS    RESTARTS   AGE
kube-apiserver-7cdc45f85d-b99hp   1/1       Running   0          4m
kube-apiserver-7cdc45f85d-bx7rr   1/1       Running   0          27m
kube-apiserver-7cdc45f85d-q7ts7   0/1       Pending   0          3m


Scheduler logs contain no references to this pod, will be trying to reproduce at a higher debug level
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:19:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:11:51Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: openstack
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by mikebryant** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by Huang-Wei** [comment]
I'm not sure if we still support 1.9. @k82cn @bsalamat can comment.

Considering that there are certain amount of performance improvement on Pod{Anti}Affinity since 1.9, esp. in 1.12, I would recommend to upgrade the whole cluster to 1.12 - if it's an option for you.

**Comment by bsalamat** [comment]
We no longer support 1.9, but from the error logs, it appears that the scheduler didn't find any nodes that could run your pod: `0/60 nodes are available: 2 Insufficient cpu, 5 Insufficient memory, 60 ExistingPodsAntiAffinityRulesNotMatch, 60 MatchInterPodAffinity.`
Are you sure that your cluster spans multiple zones?

**Comment by mikebryant** [comment]
Yes, absolutely. If the scheduler is restarted it then immediately schedules those pods, spreading them across all 3 zones.

Can appreciate 1.9 isn't supported though, we're attempting to upgrade further but it's currently blocked by internal factors.

I can reopen this if we can reproduce with a later version

**Comment by absolutarin** [comment]
@mikebryant sorry for checking in after a year. Did you run into similar issues again? What is your k8s cluster version?
