### ISSUE TITLE
IPVS: rs delete failed after scaledown

### ISSUE THREAD

**Issue by annProg** [kubernetes/kubernetes#70997]
**What happened**:
After a HPA scaledown, Failed to delete rs, this is the logs:
```
E1113 18:48:44.010713    9987 graceful_termination.go:89] Try delete rs "169.169.218.191:80/TCP/172.20.42.128:80" err: Failed to delete rs "169.169.218.191:80/TCP/172.20.42.128:80", can't find the real server
E1113 18:49:44.011275    9987 graceful_termination.go:89] Try delete rs "169.169.218.191:80/TCP/172.20.42.128:80" err: Failed to delete rs "169.169.218.191:80/TCP/172.20.42.128:80", can't find the real server
E1113 18:49:44.011584    9987 graceful_termination.go:89] Try delete rs "169.169.218.191:80/TCP/172.20.31.175:80" err: Failed to delete rs "169.169.218.191:80/TCP/172.20.31.175:80", can't find the real server
```

**What you expected to happen**:
delete rs successfully after scaledown

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
It seems that only on node the vip is using will failed to delete rs. other node delete rs successfully.

node that vip was not using:
```
TCP  169.169.218.191:80 rr
  -> 172.20.2.81:80               Masq    1      0          0         
  -> 172.20.10.73:80              Masq    1      0          0         
  -> 172.20.31.175:80             Masq    1      0          0         
  -> 172.20.37.54:80              Masq    1      0          0         
  -> 172.20.38.80:80              Masq    1      0          0         
  -> 172.20.41.86:80              Masq    1      0          0         
  -> 172.20.49.11:80              Masq    1      0          0         
  -> 172.20.60.11:80              Masq    1      0          0         
  -> 172.20.61.16:80              Masq    1      0          0
```

node with using vip
```
TCP  169.169.218.191:80 rr
  -> 172.20.2.81:80               Masq    1      0          1515      
  -> 172.20.10.73:80              Masq    1      0          1523      
  -> 172.20.16.74:80              Masq    1      0          709       
  -> 172.20.21.86:80              Masq    1      0          694       
  -> 172.20.31.175:80             Masq    1      0          1521      
  -> 172.20.37.54:80              Masq    1      0          1536      
  -> 172.20.38.80:80              Masq    1      1          1519      
  -> 172.20.39.111:80             Masq    1      0          693       
  -> 172.20.40.85:80              Masq    1      0          706       
  -> 172.20.41.86:80              Masq    1      0          1517      
  -> 172.20.42.129:80             Masq    1      0          686       
  -> 172.20.44.101:80             Masq    1      0          690       
  -> 172.20.49.11:80              Masq    1      1          1540      
  -> 172.20.57.14:80              Masq    1      0          693       
  -> 172.20.59.9:80               Masq    1      0          703       
  -> 172.20.60.11:80              Masq    1      1          1507 
```
**Environment**: 
- Kubernetes version (use `kubectl version`):  1.12.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 7.2
- Kernel (e.g. `uname -a`): 3.10
- Install tools: binary
- Others:

/kind bug

**Comment by annProg** [comment]
@kubernetes/sig-network-bugs

**Comment by annProg** [comment]
Found only few node did not update rs, may need more test

**Comment by m1093782566** [comment]
@annProg 

I am curious to learn if you have resolved this issue? Does IPVS proxier still have the problem?

**Comment by towolf** [comment]
@m1093782566 I reported similar issues in another bug recently. And I got the same messages in the log:

https://github.com/kubernetes/kubernetes/issues/70493#issuecomment-434791855

**Comment by brahmovacha** [comment]
I am also facing the same issue with following scenario:

1. When HPA gets scaled out/ down
2. When we delete any deployment running on k8s cluster

Everytime, we have to restart the kube-proxy in order to align all nodes and master.

My cluster comprises of:
1 master and 2 nodes and we running kube-proxy with ipvs mode.

Any suggestion on how to monitor/watch this ipvs issue automatically till this issue gets resolved would be appreciated

**Comment by annProg** [comment]
@brahmaroutu please see #71071 , this issue had been solved
