### ISSUE TITLE
Re-organize certificate and key helper libraries

### ISSUE THREAD

**Issue by awly** [kubernetes/kubernetes#71004]
The libraries with helper funcs in client-go and kubeadm are very dis-organized and have a lot of overlap. There's also many very specialized funcs that are not reusable.

List of current libraries:
- https://godoc.org/k8s.io/client-go/util/cert
- https://godoc.org/k8s.io/client-go/util/cert/triple
- https://godoc.org/k8s.io/client-go/util/certificate
- https://godoc.org/k8s.io/client-go/util/certificate/csr
- https://godoc.org/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap
- https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil

Propose the following organization:
- k8s.io/client-go/util/x509util - certificate helpers used by k8s clients
- k8s.io/client-go/util/keyutil - key(pair) helpers used by k8s clients
- k8s.io/kubernetes/pkg/util/x509util - internal-only certificate and CSR helpers used by control plane and native tools
- k8s.io/kubernetes/pkg/util/keyutil - internal-only key(pair) helpers used by control plane and native tools
- kubeadm and kubelet (like csr.RequestNodeCertificate) specialized code will live under their respective source trees

I'll work on incrementally moving towards that organization

/kind bug

**Comment by awly** [comment]
/sig auth
/assign awly
CC @mikedanese @liggitt

**Comment by neolit123** [comment]
cc @luxas

**Comment by mourya007** [comment]
@awly @mikedanese  What  we need to in this library https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil

**Comment by awly** [comment]
@mourya007 https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil has some overlap with the other libraries. It is also kubeadm-specific but has several dependencies in client-go that nobody else uses.

I want to pull anything in client-go that only kubeadm uses into pkiutil.
If stuff in client-go isn't obviously useful to a k8s client (managing a PKI is not, for example) it should land somewhere in k8s.io/kubernetes/pkg or /cmd.

**Comment by mourya007** [comment]
@awly  Can you give me one example for what exactly we need to do in this library https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil ?

**Comment by awly** [comment]
@mourya007 for example move these kubeadm-only functions into `pkiutil`:
- https://godoc.org/k8s.io/client-go/util/cert#EncodeCertPEM
- https://godoc.org/k8s.io/client-go/util/cert#EncodePrivateKeyPEM
- https://godoc.org/k8s.io/client-go/util/cert#EncodePublicKeyPEM
- https://godoc.org/k8s.io/client-go/util/cert#NewPrivateKey
- https://godoc.org/k8s.io/client-go/util/cert#NewSignedCert

**Comment by mikedanese** [comment]
Is this fixed?
