### ISSUE TITLE
DiskUsage measurement doesn't ignore sub-mounts

### ISSUE THREAD

**Issue by ehmm** [kubernetes/kubernetes#71012]
I'm using K8S 1.10 and have a specific use case where I'm trying to use an emptyDir to share mounts between two containers in a pod.
I'm using the MountPropagation feature successfully, but while debugging another issue I noticed that the node was running a very long running du command.
Looking into the source I noted:
https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/volume/util/fs/fs.go

Which runs du on any emptyDir, do measure disk usage. I recommend that in this case we should add the -x flag that will skip any mounted directories as they do not count against the file usage and would make these scans a lot faster.

I could of course add a simple pull request for this but first wanted to see if this was known and on purpose.

To reproduce bind mount/loop mount/device mount any large/slow directory into an emptyDir volume and watch as the du process slogs away

**Environment**:
- Kubernetes 1.10
- GKE

/kind bug

**Comment by ehmm** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
I think it makes sense to ignore submounts.

**Comment by jingxu97** [comment]
@ehmm, do you still want to submit a PR to fix this? Thanks!
