### ISSUE TITLE
'kubeadm init --dry-run --feature-gates=DynamicKubeletConfig=true' doesn't work together

### ISSUE THREAD

**Issue by iggy** [kubernetes/kubernetes#71019]
**What happened**:

`--dry-run` and  `--feature-gates=DynamicKubeletConfig=true` don't work together

```
# kubeadm init --apiserver-advertise-address 10.138.136.208 --pod-network-cidr 172.16.0.0/12 --ignore-preflight-errors=all --feature-gates=CoreDNS=true --feature-gates=DynamicKubeletConfig=true --dry-run
[init] using Kubernetes version: v1.12.2
...
[kubelet] WARNING: The Dynamic Kubelet Config feature is beta, but off by default. It hasn't been well-tested yet at this stage, use with caution.
[dryrun] Would perform action GET on resource "configmaps" in API group "core/v1"
[dryrun] Resource name: "kubelet-config-1.12"
error enabling dynamic kubelet configuration: couldn't get the kubelet configuration ConfigMap: configmaps "kubelet-config-1.12" not found
```

**What you expected to happen**:

I know this is a very new and not well-tested feature, but just reporting in case it's a corner case nobody has tested yet.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  - `kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
  - `DigitalOcean` not that it matters, I haven't gotten very far into installing
- OS (e.g. from /etc/os-release):
  - `Ubuntu 18.04 (bionic)
- Kernel (e.g. `uname -a`):
  - `Linux ubuntu001 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
  - `N/A`
- Others:

/kind bug

**Comment by neolit123** [comment]
we have removed the feature gate from kubeadm 1.13 and it has moved under `kubeadm alpha kubelet` this feature is now not part of the standard init workflow. there are a number of problems with the DKC feature, one of which is related to privileges.

in terms of mixing:
`--dry-run and --feature-gates=DynamicKubeletConfig=true`
it's unlikely that we can backport a fix for that in 1.12 as this is not a critical bug fix.

thanks.
/close
