### ISSUE TITLE
Update golang.org/x/net/http2 vendored files

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#71016]
It is too late to do this in 1.13, so when 1.14 opens up, we should update `golang.org/x/net/http2`

Please see https://github.com/kubernetes/kubernetes/pull/70971

**Comment by wenjiaswe** [comment]
@PrasadG193 Thanks! I will be happy to review once it's done.

**Comment by PrasadG193** [comment]
@dims @wenjiaswe @cheftako AFAIU We need to update this dependency in all the repos under https://github.com/kubernetes/kubernetes/tree/master/vendor/k8s.io. Should we create a PR against each repo? I guess these tests will not pass until we merge changes in vendored repos.

**Comment by wenjiaswe** [comment]
@PrasadG193  Sorry for the delay! I was busy with KubeCon and just caught up with this. Actually, what you need to do is to update files in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io in this PR, instead of vendors. cc @dims for confirmation. (same reply as in the PR)

**Comment by dims** [comment]
@wenjiaswe 's suggestion is correct!
