### ISSUE TITLE
kubectl patch servicemonitor fails with UnsupportedMediaType

### ISSUE THREAD

**Issue by andig** [kubernetes/kubernetes#71024]
**What happened**:

Trying to patch a `servicemonitor` after deploying `prometheus-operator`, I'm unable to patch the monitor:

    Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json

**What you expected to happen**:

Monitor patched via `kubectl` similar to how deployments can be patched.

**How to reproduce it (as minimally and precisely as possible)**:

    kubectl patch servicemonitor prometheus-prometheus-oper-kubelet --patch "$(cat kubelet-cadvisor-patch.yaml)"

with this patchfile:

    # workaround for https://github.com/Azure/AKS/issues/680
    spec:
      endpoints:
      - honorLabels: true
        interval: 30s
        port: http-metrics
      - honorLabels: true
        interval: 30s
        path: /metrics/cadvisor
        port: http-metrics
      jobLabel: k8s-app
      namespaceSelector:
        matchNames:
        - kube-system
      selector:
        matchLabels:
          k8s-app: kubelet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

	Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
	Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure
- Kernel (e.g. `uname -a`):

	Darwin AndiMacPro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

/kind bug

**Comment by yue9944882** [comment]
/triage support

> Partially update a node using a strategic merge patch. Specify the patch as JSON.
>		kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'

thats not the correct patch format. we need standard json patch format w/ that command. i'd suggest u to use apply or edit command

Additionally, iiuc, `servicemonitor` is a custom resource and the strategy merge patch is not supported for custom resource for now.

**Comment by andig** [comment]
> Additionally, iiuc, servicemonitor is a custom resource and the strategy merge patch is not supported for custom resource for now.

Thank you, I wasn't aware of that. If there's any tracking issue I'd be happy to subscribe to that as its quite useful.

> thats not the correct patch format. we need standard json patch format w/ that command. i'd suggest u to use apply or edit command

Thats confusing- I can successfully do a `kubectl patch deployment` with yaml?

**Comment by yue9944882** [comment]
> If there's any tracking issue I'd be happy to subscribe to that as its quite useful.

@andig patch support for custom resource will be done via server-side-apply in future releases. it's tracked via a KEP iirc. @apelisse 

> I can successfully do a kubectl patch deployment with yaml?

not sure about that. but this seems not the documented usage.

**Comment by apelisse** [comment]
@andig Can you try: `kubectl patch servicemonitor prometheus-prometheus-oper-kubelet --patch "$(cat kubelet-cadvisor-patch.yaml)" --type=merge`? The default type is strategic which is indeed unsupported for CRs

**Comment by andig** [comment]
Great:

	❯ kubectl patch servicemonitor prometheus-prometheus-oper-kubelet --patch "$(cat prometheus/kubelet-cadvisor-patch.yaml)" --type=merge
	servicemonitor.monitoring.coreos.com/prometheus-prometheus-oper-kubelet patched

I now understand what a "json" merge patch is and why that is what need be done for CRDs. Much appreciated!

**Comment by apelisse** [comment]
Yeah, be careful because there is [JSon patch](https://tools.ietf.org/html/rfc6902) and [JSon merge patch](https://tools.ietf.org/html/rfc7386) :-)

**Comment by discordianfish** [comment]
The error is quite misleading though, would be great if that could be fixed.

**Comment by lentzi90** [comment]
> Looking at the patch above, there is no API version, group, and kind in the yaml. The top level of the yaml is "spec" which I suspect is NOT valid.

@bswartz the kind and name is given as part of the command and the API version and group is defaulted based on this. The patch command will thus identify the relevant resource with this information and merge in the patch given. So it is indeed valid. :slightly_smiling_face:

**Comment by bswartz** [comment]
> > Looking at the patch above, there is no API version, group, and kind in the yaml. The top level of the yaml is "spec" which I suspect is NOT valid.
> 
> @bswartz the kind and name is given as part of the command and the API version and group is defaulted based on this. The patch command will thus identify the relevant resource with this information and merge in the patch given. So it is indeed valid. slightly_smiling_face

Thanks, I didn't know this. What caused the error in this case then?
