### ISSUE TITLE
kubectl --namespace flag should support multiple values

### ISSUE THREAD

**Issue by princerachit** [kubernetes/kubernetes#71032]
the `--namespace` flag only supports one value.
```bash
kubectl xxx xxx --namespace=<oneval>
```
where `<oneval>` is the namespace name.
It should be possible to pass multiple comma separated values in this argument, something like:
```bash
kubectl get po --namespace=ns1,ns2,ns3
```

**Comment by liggitt** [comment]
previously proposed and discussed in https://github.com/kubernetes/kubernetes/issues/52326

making the --namespace flag behave inconsistently across multiple commands is not desired.

making the current single value plural would fundamentally change most operations, and greatly increase the complexity of propagating success/error status through the command structure.

/close
