### ISSUE TITLE
Meteor and Mongo example

### ISSUE THREAD

**Issue by chees** [kubernetes/kubernetes#7103]
We made an example of how to run Meteor together with MongoDB on GKE:
https://github.com/Q42/meteor-gke

@jeffmendoza asked us if this can be merged into the official Kubernetes repo.
We're fine with that, so I made the example a little more generic and less dependent on GKE:
https://github.com/chees/kubernetes/tree/master/examples/meteor

I'd like to submit a pull request for that which Jeff can then work on some more. According to the guidelines I need an issue for it first, so here it is.
I also just submitted the CLA form.

Let me know if I can create the PR.

**Comment by jeffmendoza** [comment]
Hi all. Yes, I'll be expanding this into a more in-depth tutorial.

**Comment by fabioy** [comment]
Please create the PR. The reviewer(s) will evaluate as to whether it'll be accepted, of course.  Note that in some cases, the advice is that a blog post may be more appropriate for examples.

Thank you.

**Comment by jeffmendoza** [comment]
This can be closed
