### ISSUE TITLE
Clean new install on CentOS7x kubelet fails to start with error: kubelet: error: failed to run Kubelet: invalid kubeconfig

### ISSUE THREAD

**Issue by iammrchetan** [kubernetes/kubernetes#71034]
@kubernetes/sig-contributor-experience-bugs

**What happened**: kubelet is not running; so can't run kubeadm init. Pulling config image fail.
[root@kekecentest04 run]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-11-14 13:55:59 EAT; 2s ago
     Docs: https://kubernetes.io/docs/
  Process: 29502 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255)
 Main PID: 29502 (code=exited, status=255)

Nov 14 13:55:59 kekecentest04 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Nov 14 13:55:59 kekecentest04 systemd[1]: Unit kubelet.service entered failed state.
Nov 14 13:55:59 kekecentest04 systemd[1]: kubelet.service failed.

**What you expected to happen**:
kubelet should be running, in active state. But it's in activating/failed state.
Hence kubeadm init should run successfully.
kubeadm init --apiserver-advertise-address=172.23.19.51 --pod-network-cidr=10.244.0.0/16

**How to reproduce it (as minimally and precisely as possible)**:
Installed k8s on fresh centos 7.4. Followed below document
https://www.howtoforge.com/tutorial/centos-kubernetes-docker-cluster/
[root@kekecentest04 system]# rpm -aq | grep -i kube
kubelet-1.12.2-0.x86_64
kubeadm-1.12.2-0.x86_64
kubernetes-cni-0.6.0-0.x86_64
kubectl-1.12.2-0.x86_64

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
[root@kekecentest05 tmp]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
RAM: 4GB, disk 40 GB, cpus: 2
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):
Linux kekecentest05 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
yum
- Others:
**==== docker version ==== installed using tarball**
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**==== output of  journalctl _SYSTEMD_UNIT=kubelet.service ====**
Nov 14 10:25:53 kekecentest05 kubelet[13018]: F1114 10:25:53.426389   13018 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed

**==== output while tried creating config.yaml from solution someone suggested ====**
kubeadm upgrade node config --kubelet-version v1.12.2
couldn't create a Kubernetes client from file "/etc/kubernetes/kubelet.conf": failed to load admin kubeconfig [open /etc/kubernetes/kubelet.conf: no such file or directory]

/kind bug

**Comment by twillert** [comment]
@iammrchetan I have the same issue with a fresh CentOS 7.6 installation. Did you manage to find out the cause of this?
