### ISSUE TITLE
Unable to --force apply using kubectl 1.10/1.11

### ISSUE THREAD

**Issue by alewitt** [kubernetes/kubernetes#71042]
**What happened**: 
When trying to update a roleRef in a clusterrolebinding, i tried running `kubectl apply--force -f myFile.yaml`. Kubectl came back with `invalid`

**What you expected to happen**:
When using `--force`, kubectl should delete and recreate the resource if it runs into an immutable resource

**How to reproduce it (as minimally and precisely as possible)**:
create a clusterRoleBinding, then try to `kubectl apply --force` change the roleRef

**Anything else we need to know?**:
Only happening on kubectl 1.10 and 1.11. Both 1.9 and 1.12 are working as expected.

**Environment**:
- Kubernetes version (use `kubectl version`): Server (1.10.8+IKS) Client (1.10.10 and 1.11.4)
- Cloud provider or hardware configuration: IBM
- OS (e.g. from /etc/os-release): Mac
- Kernel (e.g. `uname -a`): Darwin Kernel Version 18.0.0
- Install tools: curl
- Others:

/kind bug

**Comment by alewitt** [comment]
@kubernetes/sig-CLI-bugs

**Comment by liggitt** [comment]
Behavior changed in https://github.com/kubernetes/kubernetes/pull/58991

The behavior you are expecting was actually (somewhat legitimately) reported as a bug in https://github.com/kubernetes/kubernetes/issues/58984

There's currently no way for the CLI to know if an invalid error returned from the server is because you are trying to change an immutable field (like roleRef on a binding), or because the object you are applying has a field value that is never allowed. Deleteting/recreating could make sense in the first case. Deleting and failing to recreate is not desired in the second case.

**Comment by dixudx** [comment]
Prior to v1.10, the CLI would try to delete and recreate without any limitations if forced. And v1.10 added a check on conflict error when forced.  v1.12 started to add another check on invalid errors.

> There's currently no way for the CLI to know if an invalid error returned from the server is because you are trying to change an immutable field (like roleRef on a binding), or because the object you are applying has a field value that is never allowed. Deleteting/recreating could make sense in the first case. Deleting and failing to recreate is probably not desired in the second case.

@liggitt Agree. I will suggest we should return more specific errors from apiserver. For the second case, we should return `BadRequest` to indicate that. WDYT?

**Comment by liggitt** [comment]
> For the second case, we should return BadRequest to indicate that. WDYT?

I don't think that is an appropriate response, given the definition of the 400 http status code. 422 still seems correct for both, they are simply different causes

**Comment by alewitt** [comment]
> There's currently no way for the CLI to know if an invalid error returned from the server is because you are trying to change an immutable field (like roleRef on a binding), or because the object you are applying has a field value that is never allowed. Deleteting/recreating could make sense in the first case. Deleting and failing to recreate is probably not desired in the second case.

i would agree deleting and failing to recreate is not desired and having the system be smart enough to keep the old resource running in this case would be *nice*. But ultimately it is the user's responsibility to know what they are doing when using something like `--force`. Breaking the main use case, an immutable field change, to account for user error is not a great solution.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/66602 should be picked to release-1.11 for compatibility
