### ISSUE TITLE
Extract common label/annotation reset functions while setting status into a common utility

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#71056]
This came up as a follow up to https://github.com/kubernetes/kubernetes/pull/69929

Also rather than opening 5 different issues - we are going to use this github issue to track all follow up items mentioned here - https://github.com/kubernetes/kubernetes/pull/69929#issuecomment-438897594

**Comment by jsafrane** [comment]
* [extract utility method to reset objectmeta fields for status update](https://github.com/kubernetes/kubernetes/pull/69929#discussion_r233295428): PR #71211

**Comment by jsafrane** [comment]
* and the rest is fixed in #71217
