### ISSUE TITLE
CSINodeInfo lister not syncing existing objects

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#71052]
**What happened**: The CSINodeInfo lister here:
https://github.com/kubernetes/kubernetes/blob/12402742041386b82c89b1c64cb855bdc1691928/staging/src/k8s.io/csi-api/pkg/client/informers/externalversions/csi/v1alpha1/csinodeinfo.go#L38
is used in the external-attacher to get NodeID. If `CSINodeInfo` already exists before external-attacher is started, the object corresponding to the target node is missing for at least a few minutes.
https://github.com/kubernetes-csi/external-attacher/blob/9da8c6d20d58750ee33d61d0faf0946641f50770/pkg/controller/csi_handler.go#L500

The node lister inside the external-attacher, which is initialized the same way as the CSINodeInfo lister, syncs existing objects just fine. Calling the API directly works.
Lister initialization:
https://github.com/kubernetes-csi/external-attacher/blob/9da8c6d20d58750ee33d61d0faf0946641f50770/cmd/csi-attacher/main.go#L150

I suspect it's a bug in listers and informers associated with CRDs.

Caused one of the test failures in #70760; other possibly related discussion around the use of CRD informers in CSI: #68261

Once this bug is fixed, https://github.com/kubernetes-csi/external-attacher/pull/90 needs to be reverted

/sig storage
/sig api-machinery
/cc @msau42 @saad-ali @davidz627 @jsafrane @lavalamp 
/priority important-soon

/kind bug

**Comment by AishSundar** [comment]
@verult I assume you are planning to get this fixed in time for Code freeze (11/16)? I am adding the 1.13 milestone to this issue. Let me know otherwise.

/milestone v1.13

**Comment by verult** [comment]
@AishSundar this is likely not getting fixed completely for 1.13, but we already have a mitigation in place to avoid the problem temporarily.

**Comment by AishSundar** [comment]
Thanks @verult considering code freeze is tomorrow and we have a workaround, I am moving this to 1.14

/milestone v1.14

**Comment by msau42** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by spiffxp** [comment]
/milestone clear
/remove-priority important-soon
/priority important-longterm
Having seen no movement on this issue for a while, I'm going to assume it's not committed to for this milestone.  Please add this back to the v1.14 milestone if you intend to work on this.

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/78029
