### ISSUE TITLE
pods will not  migrate when a  Node is unreachable.

### ISSUE THREAD

**Issue by yanghaichao12** [kubernetes/kubernetes#71057]
if ‘prestop’  hook is set and ‘TerminationGracePeriodSeconds’ are not null，assuming a node is unreachable，i wonder how a pod in this node can be deleted gracefully and migrant to other healthy nodes？ i check some doc and get this:
‘’‘
Kubernetes (versions 1.5 or newer) will not delete Pods just because a Node is unreachable. The Pods running on an unreachable Node enter the ‘Terminating’ or ‘Unknown’ state after atimeout. Pods may also enter these states when the user attempts graceful deletion of a Pod on an unreachable Node. 
’‘’
so， how should i do？

/triage support

**Comment by wgliang** [comment]
In fact, the scheduler does not directly manage the state of the pod. How to deal with the pods on an unreachable Node, I am not very clear about the behavior of the current pod controller, but I think this should be related to the controller.
/area nodecontroller
