### ISSUE TITLE
Flaking Test: 100 nodes: [sig-scalability] Load capacity [Feature:Performance] should be able to handle 30 pods per node ReplicationController with 0 secrets, 0 configmaps and 0 daemons

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71060]
**Which jobs are failing**:  gce-cos-master-scalability-100

**Which test(s) are failing**:  [sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using ReplicationController with 0 secrets, 0 configmaps, 0 token projections, and 0 daemons

**Since when has it been failing**: Pretty much forever

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

**Reason for failure**:

Appears to somehow be related to scheduler CPU:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19700

```
Container kube-scheduler-e2e-big-master/kube-scheduler is using 0.410578205/0.4 CPU
not to have occurred
```

**Anything else we need to know**:

What's interesting about this flake is that it occurs about once in 10 runs.  And it doesn't occur at all in 1.13:

https://testgrid.k8s.io/sig-release-1.13-blocking#gci-gce-scalability-1.13

This is possibly related to issue  #70708, but since that issue was for a different test and linked to the golang upgrade, opening a new issue to track the current visible flake.

/kind flake
/sig scalability
/priority important-longterm

cc:
@mariantalla @AishSundar @wojtek-t @mortent

**Comment by wojtek-t** [comment]
Given that we migrated to the ClusterLoader framework in the menatime, I'm closing this one.
