### ISSUE TITLE
The return of [sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator fails on "pull-kubernetes-e2e-gce" and "ci-kubernetes-e2e-gci-gce"

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71065]
**Which jobs are failing**: gke-1.12-1.13-downgrade-cluster-parallel

**Which test(s) are failing**: [sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator fails on "pull-kubernetes-e2e-gce" and "ci-kubernetes-e2e-gci-gce"

**Since when has it been failing**: 11/14

**Testgrid link**: https://testgrid.k8s.io/sig-release-1.13-all#gke-1.13-1.12-downgrade-cluster-parallel

**Reason for failure**:

This appears to be the same problem as the otherwise resolved Issue #63622.  Apparently this one test job wasn't updated to stop trying to use a 1.7 API server.
@
**Anything else we need to know**:

/kind failing-test
/priority important-longterm
/sig testing
/sig api-machinery
/sig gcp

@liggitt @spiffxp @rramkumar1

**Comment by jberkus** [comment]
This is not a blocker for 1.13

**Comment by liggitt** [comment]
that test no longer exists in master or the release-1.13 branch. that means any failure lives in 1.12 test code. should https://github.com/kubernetes/kubernetes/pull/68300 be backported to the release-1.12 branch? that seems odd.

**Comment by jberkus** [comment]
We did it for all the other upgrade/downgrade jobs, I don't see why not.

**Comment by spiffxp** [comment]
I won't say no to someone backporting the fix, but it's not going to be me, and it's not signal I'm going to be paying attention to
