### ISSUE TITLE
I am getting a issue with running kubernetes  version with issue--Unable to connect to the server: dial tcp [::1]:8080:

### ISSUE THREAD

**Issue by Sankara11Varma** [kubernetes/kubernetes#71062]
I am getting one error message while accessing Kubectl version.please help to understand and resolve the issue.

Kubectl application we posted in the system 32 folder from there, we are calling through power shell admin mode.While calling kubectl version, i am getting below error message.

Error Message:Unable to connect to the server: dial tcp [::1]:8080:

Below are the details provided.

Server : Microsoft Windows Server 2016 Datacenter
Version	10.0.14393 Build 14393
System Type	x64-based PC
Docker version : 17.06.2-ee-17
Docker API version: 1.30
Kubernetes-cli v1.12.1

Please help me on this,Is there need to change any firewall settings for this?.I was tried to change Environment variable as suggested by other members, but didn't able get proper output yet.

**Comment by Sankara11Varma** [comment]
Hi All,

Below are the details provided further please help me on this.

Server : Windows server  -OS Name	Microsoft Windows Server 2016 Datacenter
Version	10.0.14393 Build 14393
System Type	x64-based PC
Docker version :   17.06.2-ee-17
API version:  1.30

Kubectl application we posted in the system 32 folder from there, we are calling through power shell admin mode.While calling kubectl version, i am getting above error message.

**Comment by liggitt** [comment]
Kubectl is trying to connect to localhost:8080, which is the default when it does not have a kubeconfig file available with specific connection parameters

Ensure you have a valid kubeconfig file at ~/.kube/config or have a KUBECONFIG envvar set pointing to a file with valid connection configuration

/close
