### ISSUE TITLE
Nodes hangs when cpu manager policy set to static with soft lockup - CPU stuck for 22s after scheduling multiple pods

### ISSUE THREAD

**Issue by f84anton** [kubernetes/kubernetes#71073]
**What happened**:
Nodes hangs: watchdog: BUG: soft lockup - CPU# stuck for 22s! 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
kubelet options: 
--cgroup-driver=cgroupfs 
--cgroups-per-qos=True
--enforce-node-allocatable=pods
--kube-reserved cpu=200m,memory=512M
--eviction-hard=memory.available<100Mi,nodefs.available<200Mi,imagefs.available<200Mi  
--eviction-soft-grace-period=memory.available=30s,nodefs.available=30s,imagefs.available=30s  
--eviction-soft=memory.available<300Mi,nodefs.available<1Gi,imagefs.available<1Gi  
--eviction-minimum-reclaim=memory.available=100Mi,nodefs.available=1Gi,imagefs.available=1Gi  
--eviction-pressure-transition-period=2m  
--system-reserved=memory=1.5Gi  
--kube-reserved=cpu=300m,memory=150Mi  
--system-reserved=cpu=300m,memory=500Mi 
--cpu-manager-policy=static 

Have some pods with Guaranteed QoS Class with integer CPU requests on node.
Significantly scale up anything with Burstable QoS Class, from 1 to 100 for example;
In 15 minutes node will hangs.

**Anything else we need to know?**:
Can't reproduce when cpu manager policy is set to none.

Errors in logs: cpu manager can't update cpuset.cpus for kube-proxy, multiple errors:
```
kubelet[13571]: E1115 08:37:11.883044   13571 cpu_manager.go:183] [cpumanager] AddContainer error: rpc error: code = Unknown desc = failed to update container "67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860": Error response from daemon: Cannot update container 67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860: docker-runc did not terminate sucessfully: failed to write 0-1,3-31,33,35-63 to cpuset.cpus: write /sys/fs/cgroup/cpuset/kubepods/burstable/pod18427c267c777fabebdf16ef334cda4d/67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860/cpuset.cpus: device or resource busy

kubelet[13571]: E1115 08:37:11.883061   13571 cpu_manager.go:250] [cpumanager] reconcileState: failed to add container (pod: kube-proxy-k8s1, container: kube-proxy, container id: 67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860, error: rpc error: code = Unknown desc = failed to update container "67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860": Error response from daemon: Cannot update container 67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860: docker-runc did not terminate sucessfully: failed to write 0-1,3-31,33,35-63 to cpuset.cpus: write /sys/fs/cgroup/cpuset/kubepods/burstable/pod18427c267c777fabebdf16ef334cda4d/67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860/cpuset.cpus: device or resource busy

dockerd[9041]: time="2018-11-15T08:32:42.457354702+03:00" level=error msg="Handler for POST /v1.38/containers/67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860/update returned error: Cannot update container 67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860: docker-runc did not terminate sucessfully: failed to write 0-1,3-31,33,35-63 to cpuset.cpus: write /sys/fs/cgroup/cpuset/kubepods/burstable/pod18427c267c777fabebdf16ef334cda4d/67bb6b01cc23f4e4cfaea940b488a1b2190c0984934f15fb923e4473dfab7860/cpuset.cpus: device or resource busy\n: unknown
```

[log errors and describe pod for kube-proxy](https://github.com/kubernetes/kubernetes/files/2585212/cpu_manager.txt)

[dmesg_soft_lockup.txt](https://github.com/kubernetes/kubernetes/files/2585305/dmesg_soft_lockup.txt)

**Environment**:
- Kubernetes version (use `kubectl version`): 
```Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}```
- Cloud provider or hardware configuration: Dell PowerEdge™ R640 DX292 2 x Intel® Xeon® Gold 6130 16-Core (Skylake-SP) incl. Hyper-Threading Technology 754GB RAM.
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): 
```Linux k8s5 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```
```Linux k8s5 4.19.2-041902-generic #201811132032 SMP Tue Nov 13 20:34:19 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```
- Install tools: kubespray
- Others:
```
# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

/kind bug

**Comment by f84anton** [comment]
@kubernetes/sig-node-bugs

**Comment by bradbeam** [comment]
We're seeing a similar issue as well on 1.11.7. We thought it may be a kernel issue initially, but havent seen any difference going from 4.15.0-42-generic to 4.15.0-45-generic [Ubuntu 18.04.1 LTS]. 

The kube-proxy errors seem to be discussed a bit in https://github.com/kubernetes/kubernetes/issues/66614
