### ISSUE TITLE
Conflicting scale up events on pods scheduled with secondary scheduler

### ISSUE THREAD

**Issue by consideRatio** [kubernetes/kubernetes#71070]
**What happened**:
I got different and conflicting events from cluster-autoscaler when using a custom configuration on a secondary kube-scheduler running in another namespace than the default one. The cluster-autoscaler shows an event coupled with the pod that it triggered a scale up no matter what, but with the custom scheduler, I got a bunch of additional events (`Normal   NotTriggerScaleUp       6m (x25 over 11m)   cluster-autoscaler`) that contradicted the initial event.

**With default scheduler**:
```
  Type     Reason                  Age                 From                                      Message
  ----     ------                  ----                ----                                      -------
  Normal   TriggeredScaleUp        26m                 cluster-autoscaler                        pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/ds-platform/zones/europe-west1-b/instanceGroups/gke-floss-gpu-k80-4f5b3c32-grp 0->1 (max: 2)}]
  Warning  FailedScheduling        22m (x72 over 27m)  default-scheduler                         0/2 nodes are available: 2 Insufficient nvidia.com/gpu, 2 node(s) didn't match node selector.
  Normal   SuccessfulAttachVolume  17m                 attachdetach-controller                   AttachVolume.Attach succeeded for volume "pvc-49f6b719-db61-11e8-b653-42010a840127"
```

**With custom scheduler**:
```
  Type     Reason                  Age                 From                                      Message
  ----     ------                  ----                ----                                      -------
  Normal   TriggeredScaleUp        11m                 cluster-autoscaler                        pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/ds-platform/zones/europe-west1-b/instanceGroups/gke-floss-gpu-k80-4f5b3c32-grp 1->2 (max: 2)}]
  Warning  FailedScheduling        7m (x105 over 12m)  jupyterhub-user-scheduler                 0/3 nodes are available: 1 Insufficient nvidia.com/gpu, 2 node(s) didn't match node selector.
  Normal   NotTriggerScaleUp       6m (x25 over 11m)   cluster-autoscaler                        pod didn't trigger scale-up (it wouldn't fit if a new node is added)
  Normal   SuccessfulAttachVolume  2m                  attachdetach-controller                   AttachVolume.Attach succeeded for volume "pvc-47a6a5f8-cbde-11e8-b369-42010a840222"
```

**What you expected to happen**:
I expect to not see `Normal   NotTriggerScaleUp       6m (x25 over 11m)   cluster-autoscaler` after seeing the event about the pod triggering scale up, when using a custom scheduler as well as if using the default scheduler.

**How to reproduce it (as minimally and precisely as possible)**:
I'm sorry, but as this is quite a complicated system to reproduce involving a lot, I will not spend time reproducing this down
1. Install the jupyterhub helm chart, see https://z2jh.jupyter.org
2. Enable the custom scheduler with
```yaml
# config.yaml --- values passed to the helm chart
scheduling:
  userScheduler:
    enabled: true
```

**Anything else we need to know?**:
I'm running on a managed k8s cluster on GKE, version 1.11.2-gke.18 on the master and on the node-pool scaling up. The custom scheduler is a custom configured kube-scheduler of version 1.11.2.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2-gke.18 
- Cloud provider or hardware configuration: Google Cloud
- OS (e.g. from /etc/os-release): container optimized os
- Kernel (e.g. `uname -a`):
- Install tools: gcloud
- Others:

/kind bug

**Comment by MaciekPytel** [comment]
Cluster autoscaler only works with default scheduler, any form of custom scheduling is not supported.

The reason for this is CA works by importing kubernetes scheduler code, running it internally and expecting that the result will be exactly what scheduler will do. Anything that changes the behavior of scheduler predicate functions breaks CA.

**Comment by MaciekPytel** [comment]
A side note: https://github.com/kubernetes/autoscaler is probably a better for opening issues related to CA, it's easy for an issue to drown in main k/k repo.

**Comment by consideRatio** [comment]
Thanks for the quick insight @MaciekPytel !

Opened the following issue: https://github.com/kubernetes/autoscaler/issues/1406
