### ISSUE TITLE
Update master to etcd 3.3.x

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#71083]
**What happened**: 
@timothysc noticed that when checking etcd versions, it doesn’t look like to be properly updated in master. client is 3.3 but the images don’t appear to be updated. docker pull k8s.gcr.io/etcd-amd64:3.3.10 - doesn’t exist. 

**What you expected to happen**:
For the 1.13 cycle we need to pickup etcd 3.3 which following changelog - https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3310-2018-10-10

/assign @jpbetz 
/cc @timothysc 
/kind cleanup
/priority critical-urgent
/milestone v1.13

**Comment by timothysc** [comment]
During the 1.12 cycle we made a compromise to upgrade etcd to 3.2.latest at the time, but agreed to upgrade to 3.3.10 in the 1.13 cycle.  Currently, we have a 1/2 upgraded master branch where the client is 3.3.10 but none of the images have been pushed and /cluster and kubeadm are not updated. 

/cc @wojtek-t @gyuho

**Comment by timothysc** [comment]
The changelog for 3.3.10 contains a number of important fixes imo : https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3310-2018-10-10

**Comment by AishSundar** [comment]
Code freeze for 1.13 is tomorrow 11/16. It will be great to get this updated before that to watch CI signal for Beta.1

**Comment by gyuho** [comment]
Regarding release image,

https://github.com/etcd-io/etcd/releases/tag/v3.3.10 was released but etcd upstream uses different registry:

- https://console.cloud.google.com/gcr/images/etcd-development/GLOBAL/etcd
- https://quay.io/repository/coreos/etcd?tag=latest&tab=tags

I do not have access to `k8s.gcr.io`.

**Comment by lavalamp** [comment]
I'm not sure that we intended to update the installed etcd version?

**Comment by lavalamp** [comment]
Can someone point me at an issue saying we intended to upgrade the etcd server version?

**Comment by gyuho** [comment]
Yeah, @jpbetz only upgraded client here https://github.com/kubernetes/kubernetes/pull/69322.

3.3 upgrade issue was created here https://github.com/kubernetes/kubernetes/issues/61326, but nobody upgraded etcd server, it seems.

**Comment by lavalamp** [comment]
Thanks.

At this point in the release I don't think it is a good idea to change the default etcd version as typically that needs to soak in the performance tests for a while. Also it's a data migration, which needs some vetting.

Still investigating but that's my initial impression.

**Comment by gyuho** [comment]
In feature-wise, v3.2 (latest) and v3.3 client use the same balancer and gRPC version.

Agree, in general we need more performance testing (which me and @jpbetz are planning to improve next year). v3.3 disabled freelist sync in backend storage to address database size issue https://github.com/etcd-io/etcd/issues/8009 which should not affect the compatibility, but we should give more time for testing.

Keeping v3.2 server would be the safest option, and v3.3 client would be 100% compatible.

/cc @wojtek-t @shyamjvs

**Comment by lavalamp** [comment]
I think we should either file a new issue to track this or edit the description of this issue. Specifically:
1. It's 100% OK for etcd client and server to not be at the same version.
2. We'll plan to update to etcd 3.3.x for 1.14 and not 1.13 since this needs to come at the beginning of a release.

**Comment by lavalamp** [comment]
Actually let's dedup to https://github.com/kubernetes/kubernetes/issues/61326.
