### ISSUE TITLE
ValidatingWebhookConfiguration/MutatingWebhookConfiguration using URL requires match including port for client authentication

### ISSUE THREAD

**Issue by chunyenlin** [kubernetes/kubernetes#71087]
**What happened**:
When configure Admission Webhook to use (external) url, if client authentication is enabled & configured, ValidatingWebhook requests to external AdmissionWebhook server fails because of client authentication.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure /etc/kubernetes/manifests/kube-apiserver.yaml 
    Add --admission-control-config-file={path of admissionControlConfig.yaml} & make sure admissionControlConfig.yaml & admissionKubeConfig.yaml(contains client BASE64-encoded cert/key) can be accessed from kube-apiserver
2. Deploy AdmissionWebhook in-cluster service
3. Configure ValidatingWebhookConfiguration/MutatingWebhookConfiguration with the in-cluster AdmissionWebhook service ( using 'service' under clientConfig )
4. Now deploy some other pods. It works well. Observation on the in-cluster AdmissionWebhook REST server shows it's mutual authentication(both server & client authentication)
5. Set up an external AdmissionWebhook server (ex. https://admission.mytest13579.com:443). It loads the same clientRootCA.pem as the in-cluster AdmissionWebhook  server.
6. Set up a custom web client(in Go) and make sure it could send simulated ValidatingWebhook request to the external AdmissionWebhook server with mutual authentication
(now we are sure the client&server authentication for the external AdmissionWebhook server functions well)
7. Re-configure ValidatingWebhookConfiguration/MutatingWebhookConfiguration to use 'url' under clientConfig (cabundle is changed to the one for the external AdmissionWebhook web server as well)
8. In admissionKubeConfig.yaml, change users.name to 'admission.mytest13579.com'
9. Restart kube-apiserver
    Make sure  admission.mytest13579.com can be resolved correctly in kube-spiserver
10. Now deploy some other pods. It fails.
      => Kubectl shows logs like: 
      Error from server (InternalError): error when creating "mytest.yaml": Internal error occurred: failed calling admission webhook "admission.mytest13579.com": Post https://admission.mytest13579.com:443/validate?timeout=30s: remote error: tls: bad certificate
      => External AdmissionWebhook server shows
      http: TLS handshake error from 10.1.107.1:40682: tls: client didn't provide a certificate

If I configure kube-apiserver to not using --admission-control-config-file, ValidatingWebhook request to external AdmissionWebhook server works fine with only server authentication.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: 
local vSphere environment
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
- Kernel (e.g. `uname -a`): 
Linux wlin-k8master 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
The issue is the appended port. When using URL-configured webhooks, if the port is specified in 
the URL, it is required to also be in the kubeconfig file user names. For example, to provide client credentials to a webhook configured with `https://admission.mytest13579.com:443`, specify `name: admission.mytest13579.com:443`

https://github.com/kubernetes/kubernetes/pull/82252 will add logic to search for credential matches without the port if no matches with the port are specified, but in the meantime, you can configure a kubeconfig file with the port included.

**Comment by liggitt** [comment]
/priority important-soon

to fix resolution to be consistent for webhook GA
