### ISSUE TITLE
nsswitch.conf adding

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#71082]
**What would you like to be added**:
I would like kubernetes to add in an nsswitch.conf file if it is missing in the container. It should contain:
hosts: files dns myhostname

**Why is this needed**:
golang/glibc has an undesirable behavior that can lead to security issues, if nsswitch.conf is missing from the container. it can cause resolving in odd ways, such as 'localhost' being resolved to a remote host.

This is a common issue with statically linked go binaries and minimal distribututions such as scratch, busybox, alpine, etc.

golang has thus for not been willing to change the default behavior on their end. Since it is a common problem on the kubernetes side, I recommend we put in this guard rail to protect against a common problem.

/kind feature

**Comment by kfox1111** [comment]
Other k8s issues are trying to one off work around this problem, but I think its bigger then that. Lets solve it all at once. Some related issues:
https://github.com/kubernetes/kubernetes/issues/48124
https://github.com/kubernetes/kubernetes/issues/69195
https://github.com/kubernetes/kubernetes/issues/70249

golang's issue:
https://github.com/golang/go/issues/22846

some tangential stuff.
Alpine's issue:
https://github.com/gliderlabs/docker-alpine/issues/367
https://github.com/gliderlabs/docker-alpine/issues/367

**Comment by freehan** [comment]
Probably not a kubernetes problem. The user should build nsswitch.conf in the image. Or the base image should have it.

**Comment by kfox1111** [comment]
its not obvious to users that they need to do that. :(
