### ISSUE TITLE
Ability to get accessible namespaces based on RBAC

### ISSUE THREAD

**Issue by mwringe** [kubernetes/kubernetes#71097]
Originally created the issue in kubernetes/community and asked to open the issue here instead.

The old issue is available here: https://github.com/kubernetes/community/issues/2942

**What would you like to be added**:

The ability to be able to get a list of namespaces that a current user has access to based on their RBAC permissions. This is manly for being able to give users a list of namespaces within a UI.

There is currently no mechanism to be able to do this. Multiple feature requests have been opened but they have been closed (see https://github.com/kubernetes/kubernetes/issues/48537, https://github.com/kubernetes/kubernetes/issues/58262, https://github.com/kubernetes/kubernetes/issues/61958)

The argument for not wanting this feature was brought up: "I still don't think a special acl-filtered list-only API belongs in core kubernetes" (@liggitt https://github.com/kubernetes/community/issues/2942#issuecomment-439085611)

But we already do something very similar in Kubernetes with SelfSubjectRulesReview. This will return a list of all actions a user can perform within a specified namespace based on their permissions. Its a bit confusing to understand why the SelfSubjectRulesReview is allowed  but something to return a list of namespaces that a user has access to is not.

Some of the arguments in the past seem to also be about how an acl-filtered list wouldn't work with the ability to watch on changes. But we don't need watch capabilities. SelfSubjectRulesReview is post based and doesn't support watch. SelfSubjectRulesReview even mentions that its meant more for UI purposes and is not to be used for more authentication purposes (which is also the usecase we are looking at).

If SelfSubjectAccessReview would be updated to work across all namespaces and not just a single namespace, then this might also work for our usecase. But this is likely to be overkill for what we want from it. Being able to narrow down the permission being requested might work out better (eg return all namespaces where the current user can create pods). But ideally, just knowing if you can access the namespace would be enough for our usecase.

Or there might be some other way of handling things here which could give us the results we are looking for.

**Why is this needed**:

There is a problem where any console or other tools can be granted permissions in certain namespaces using k8s RBAC, but there is no way for it to get that list of namespaces back out. 

For instance, we have the Kiali project which provides a UI console for monitoring Istio service meshes. 

Right now we grant Kiali cluster wide permissions which allows it to read all the namespaces and provide a drop down option for users to select which namespace they want to view.

We have a need to be able to restrict the Kiali permissions to only specified namespaces. This is a better security policy for users so that they don't need to give cluster wide permissions when they don't need it. Its also going to be important if we have multiple Istio control planes and Kiali instances in the same k8s cluster (where each istio/kiali instance covers different namespaces).

Its easy to grant Kiali a role to a particular namespaces and use that to control access to resources within that namespace. But there doesn't appear to be a way to get a list of namespaces that the Kiali serviceaccount has access to.

This means we need to manually store the list of namespaces we have granted to the Kiali service account somewhere and have Kiali read this separate list. Which is prone to error and difficult to keep in sync. This extra effort doesn't really make sense since the system should store this information and retrieve this for us.

All of this works great in OpenShift using 'projects' and we are looking to be able to add the same functionality when using k8s (yes, we are aware of https://github.com/openshift/kube-projects but is a demo only project that appears to be dead and doesn't seem to work anymore)

/kind feature

**Comment by liggitt** [comment]
> we already do something very similar in Kubernetes with SelfSubjectRulesReview. This will return a list of all actions a user can perform within a specified namespace based on their permissions. Its a bit confusing to understand why the SelfSubjectRulesReview is allowed but something to return a list of namespaces that a user has access to is not

SelfSubjectRulesReview is not authoritative, is not supported by all authorizers, and is explicitly not to be used for making external authorization decisions:

https://github.com/kubernetes/kubernetes/blob/7c4d097faf6202fdbfefab962306a3ea50269488/staging/src/k8s.io/api/authorization/v1/types.go#L195-L200

The referenced requests (#48537, #58262) were asking for partial resource lists, which (because they are actually exposing resource info) must be authoritative, and to comply with standard list API behavior, should include a resourceVersion
