### ISSUE TITLE
VolumeScheduling unit tests assume the feature gate is off

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#71091]
**What happened**: Tests pass/fail depending on what tests run before them. If VolumeScheduling is on, StorageClasses must have a VolumeBindingMode field. If it is off, it can be nil.

**What you expected to happen**: Test pass/fail determinstically 

**How to reproduce it (as minimally and precisely as possible)**: ref: https://github.com/kubernetes/kubernetes/pull/65829

**Anything else we need to know?**: They should use SetFeatureGateDuringTest instead. Consider allowing VolumeBindingMode to be nil. (Same issue as VolumeMode).

/kind bug

**Comment by msau42** [comment]
@lichuqiang could you help look at this?
