### ISSUE TITLE
tests must use SetFeatureGateDuringTest instead of DefaultFeatureGate.Set

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#71108]
while reviewing tests in #65829, we realized some unit tests originally set up to test behavior when an alpha gate was enabled, were leaking changes to feature gates out of their packages by attempting to reset them to the old, default, disabled values.

there is a test utility that allows setting a gate to a value and automatically reverting to the original value when the test is complete:

```
defer utilfeaturetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.<FeatureName>, true|false)()
```

https://github.com/kubernetes/kubernetes/pull/71100 added tests to ensure the packages that were leaving gates changed from their default were fixed

Once that merges, we should:
* Convert remaining instances of `DefaultFeatureGate.Set` and `DefaultFeatureGate.SetFromMap` in unit tests to `SetFeatureGateDuringTest`
* Add a verification script to ensure no new uses are added in test files and that packages that set features also run the verification test to ensure gates are unmodified on package completion
* update development/community docs to describe the right way to test feature gates

To locate offending files:
```
grep -l --include *_test.go -R 'DefaultFeatureGate.Set' .
```

To find files calling SetFeatureGateDuringTest and not deferring calling the resulting function:
```
grep  --include *_test.go -R 'SetFeatureGateDuringTest' . | grep -v defer
grep  --include *_test.go -R 'SetFeatureGateDuringTest' . | grep -v ")()"
```

/kind bug
/kind cleanup

**Comment by liggitt** [comment]
cc @msau42

**Comment by msau42** [comment]
Another followup item is to update community development docs
