### ISSUE TITLE
avoid useless calculates in CalculateInterPodAffinityPriority func

### ISSUE THREAD

**Issue by q6413260** [kubernetes/kubernetes#71112]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/11553677/48598964-9514af00-e9a0-11e8-979d-0482d430b61f.png)

**Why is this needed**:
in CalculateInterPodAffinityPriority func，I think we don’t need to calculate all nodes。
we only need to calculate the filteredNodes to avoid useless calculate？

/kind feature

**Comment by q6413260** [comment]
sig/scheduling

**Comment by msau42** [comment]
Please open a PR and sig scheduling can help review

**Comment by q6413260** [comment]
@msau42 I just opened a RP, but the below image says
![image](https://user-images.githubusercontent.com/11553677/48629854-b5228d80-e9f5-11e8-886b-ea49794477c2.png)

could you tell me what does it mean ?

**Comment by msau42** [comment]
It means that we are in code slush for the 1.13 release, so only planned or critical changes are allowed.  I would rebase your PR against the master branch and once we are out of 1.13 code freeze, then we can start merging changes for the next release

**Comment by q6413260** [comment]
@msau42 I know，tks

**Comment by Huang-Wei** [comment]
@q6413260 please check https://github.com/kubernetes/kubernetes/pull/71133#pullrequestreview-177043137

**Comment by Huang-Wei** [comment]
/close

as this issue is as design.
