### ISSUE TITLE
how to connect local docker containers to local Kubernetes cluster

### ISSUE THREAD

**Issue by Leo-gred** [kubernetes/kubernetes#71129]
i have Kubernetes local cluster. on one of Node, i have added docker containers /(using docker-compose.yaml file.)
if i run "docker ps" i can see all my RUN containers, but i can't add it to the dashuboard in Kubernetes, please help.
@kubernetes/sig-contributor-experience-<group-suffix>

**Comment by zegl** [comment]
@Leo-gred This is not supported. Only pods and containers managed by Kubernetes/kubelet will be visible on the dashboard (and other Kubernetes tools).

You can use ["static pods"](https://kubernetes.io/docs/tasks/administer-cluster/static-pod/) in a similar way as you're using docker-compose to schedule the containers locally, and to make the pods accessible by Kubernetes tools.

**Comment by neolit123** [comment]
/triage support
/sig node
/close


for further questions please try our support channels like stackoverflow:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example
