### ISSUE TITLE
Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-amd64-l2xjb": Error response from daemon: network host not found

### ISSUE THREAD

**Issue by gprashanthkumar** [kubernetes/kubernetes#71130]
**What happened**:
Pod won't start. In logs its giving an following error messages:

Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-amd64-l2xjb": Error response from daemon: network host not found

MountVolume.SetUp failed for volume "xtables-lock" : open /run/xtables.lock: The system cannot find the path specified.

when we look in "Logs from kube-flannel"  we see the message
Get https://172.27.108.241:10250/containerLogs/kube-system/kube-flannel-ds-amd64-l2xjb/kube-flannel?tailLines=5000&timestamps=true: dial tcp 172.27.108.241:10250: i/o timeout

**What you expected to happen**:
Pod sandboxes created with no error  messages.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We are attempting to have a window node with Linux (Ubuntu master node) and flannel network

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Hardware configuation
- OS (e.g. from /etc/os-release):
Kernel Version:
10.0.17134.407
OS Image:
Windows 10 Pro
Container Runtime Version:
docker://18.6.1
Kubelet Version:
v1.12.2
Kube-Proxy Version:
v1.12.2
Operating system:
windows
Architecture:
amd64 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by gprashanthkumar** [comment]
@kubernetes/sig-windows

**Comment by daschott** [comment]
Hi @gprashanthkumar can you use Windows Server and follow these instructions: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows ?

**Comment by daschott** [comment]
DaemonSets like kube-flannel-ds should not be scheduled on Windows as they're not supported. Windows runs flannel as a host-agent process instead today.

**Comment by skandabhatt** [comment]
/remove-lifecycle rotten

What's the solution for this issue ?.

**Comment by nguyenkhanhthien** [comment]
I ran into the same problem. Someone has solution please share with me. thanks. 
![image](https://user-images.githubusercontent.com/23173987/108583759-89c64000-736e-11eb-8590-07b2a3958602.png)
