### ISSUE TITLE
Kubelet sometimes stop restarting static pods

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes/kubernetes#71134]
Kubernetes 1.9.11

Hi, i've moved our installation to static pods:
  * etcd
  * kube-apiserver
  * kube-controller-manager
  * kube-scheduler

Issue:
Sometimes kubelet silently stop restarting static pods,
and will continue restarting them again if i do:
  systemctl restart kubelet
  docker rm -f <failed pod>

In theory that happens in two different cases:
  * After pods has been crashing 10-20x times in one sequence
   Example: while bootstrap empty cluster kube-apiserver can't connect to etcd,
   crash several times and stop restarting -> without api server cluster can't be provisioned).
  * If kubelet can't connect to API server - can't change mirror pod status
    Example: All kube-apiservers pod template has been rewritten by update and has been stopped in same time 

Thanks for any suggestions!

**Comment by andor44** [comment]
I believe we're seeing the same issue, except with evictions. We're running the master components as static pods, too. In our case it's not that they crash but they sometimes get evicted due to disk pressure, and they don't get started back up.

**Comment by surajssd** [comment]
@andor44 @Nefelim4ag can you specify definite steps to reproduce the error?

**Comment by andor44** [comment]
1. Have a static pod on your kubelet with `restartPolicy: Always`
2. Bring the static pod to a state where it has to be restarted (e.g. main container crashing, getting evicted due to disk pressure, etc.)
3. Observe that the pod stays down

The situation is relatively easy to reproduce with disk pressure eviction. Note that it seems that the kubelet doesn't stop restarting it every time, it seems somewhat random when it stops restarting the pod. On a tangential note: why are static pods _ever_ evicted?

**Comment by surajssd** [comment]
Created a yaml file and put it in `/etc/kubernetes/manifests` on one of worker nodes named `w0`.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web
  name: web
spec:
  containers:
  - image: nginx
    name: web
  dnsPolicy: ClusterFirst
  restartPolicy: Always
```

The pod has been created with name `web-w0`:

```console
[root@c0 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                         READY   STATUS    RESTARTS   AGE   IP                NODE   NOMINATED NODE   READINESS GATES
default       web-w0                       1/1     Running   0          45s   10.38.0.3         w0     <none>           <none>
kube-system   coredns-86c58d9df4-k7xx6     1/1     Running   0          89m   10.40.0.1         w1     <none>           <none>
kube-system   coredns-86c58d9df4-ps7s2     1/1     Running   0          89m   10.40.0.2         w1     <none>           <none>
...
kube-system   weave-net-lc6h5              2/2     Running   0          89m   192.168.121.215   w1     <none>           <none>
kube-system   weave-net-rrflz              2/2     Running   0          38m   192.168.121.79    w0     <none>           <none>
```

On the worker node `w0` again tried creating an aritifical disk pressure:

```console
[root@w0 ~]# df -H
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/vda1        43G  2.2G   38G   6% /
...
```

Almost 38G is free, so create a huge file of that size!

```console
[root@w0 ~]# dd if=/dev/zero of=file.txt count=38912 bs=1048576


dd: error writing 'file.txt': No space left on device
37985+0 records in
37984+0 records out
39829123072 bytes (40 GB, 37 GiB) copied, 321.271 s, 124 MB/s
```

Now if you look at the pods on `w0` they have been evicted, even the static pod `web-w0` has been evicted.

```console
[root@c0 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                         READY   STATUS    RESTARTS   AGE   IP                NODE   NOMINATED NODE   READINESS GATES
default       web-w0                       0/1     Evicted   0          10m   <none>            w0     <none>           <none>
kube-system   coredns-86c58d9df4-k7xx6     1/1     Running   0          99m   10.40.0.1         w1     <none>           <none>
kube-system   coredns-86c58d9df4-ps7s2     1/1     Running   0          99m   10.40.0.2         w1     <none>           <none>
...
kube-system   weave-net-8dfcb              0/2     Evicted   0          2s    <none>            w0     <none>           <none>
kube-system   weave-net-bmlbs              2/2     Running   0          99m   192.168.121.72    c0     <none>           <none>
kube-system   weave-net-lc6h5              2/2     Running   0          99m   192.168.121.215   w1     <none>           <none>
```

Creating space on the worker node to bring things to normal

```console
[root@w0 ~]# rm file.txt 
rm: remove regular file 'file.txt'? y
```

Now if you see for the pods on the `w0` worker node that were evicted are back now except for the static pod:

```console
[root@c0 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                         READY   STATUS    RESTARTS   AGE    IP                NODE   NOMINATED NODE   READINESS GATES
default       web-w0                       0/1     Evicted   0          22m    <none>            w0     <none>           <none>
kube-system   coredns-86c58d9df4-k7xx6     1/1     Running   0          111m   10.40.0.1         w1     <none>           <none>
kube-system   coredns-86c58d9df4-ps7s2     1/1     Running   0          111m   10.40.0.2         w1     <none>           <none>
...
kube-system   kube-proxy-6p2lt             1/1     Running   0          110m   192.168.121.215   w1     <none>           <none>
kube-system   kube-proxy-jz89h             1/1     Running   0          11m    192.168.121.79    w0     <none>           <none>
kube-system   weave-net-kn2f2              2/2     Running   0          79s    192.168.121.79    w0     <none>           <none>
kube-system   weave-net-lc6h5              2/2     Running   0          110m   192.168.121.215   w1     <none>           <none>
```

Now restarting the kubelet on `w0`

```console
[root@w0 ~]# systemctl restart kubelet
```

Checking the pods again:

```console
[root@c0 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                         READY   STATUS    RESTARTS   AGE     IP                NODE   NOMINATED NODE   READINESS GATES
default       web-w0                       1/1     Running   0          24m     10.38.0.4         w0     <none>           <none>
kube-system   coredns-86c58d9df4-k7xx6     1/1     Running   0          113m    10.40.0.1         w1     <none>           <none>
...
```

And you can see that the static pod is running fine.


So yes I can confirm that this is an issue, atleast when tried with the cluster that was setup using kubeadm.

**Comment by hprateek43** [comment]
@Nefelim4ag Is this up for grabs?

**Comment by Nefelim4ag** [comment]
@hprateek43, i'm not sure that i fully understand.

But you can grab that issue, if you wish.

**Comment by hprateek43** [comment]
@Nefelim4ag This issue points to an old k8s release. Any idea if it is patched in recent releases or is still open?

**Comment by Nefelim4ag** [comment]
@hprateek43, i think that not fixed in recent releases, i.e. more over, only recently K8s fixed static pod eviction with pod priority =)

I think currently #76598 more related to problem.
