### ISSUE TITLE
kube-controller-manager hung control loop sometime

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes/kubernetes#71139]
Kubernetes 1.9.11
etcd 3.3.9

/sig scheduling
- - -
Problem kube-controller-manager randomly stop sync loops, i.e. does not move forward on state of resources. Example:
Updated deployment does not create new RS to replace old, deleted old RS, will be recreated with old info.

If needed cluster looks like:
5 x etcd nodes <-> 5 x etcd grpc-proxy <-> 5 x kube-apiserver <-> envoy http2/grpc balancer <-> kube-controller-manager

Restart of kube-controller master helps fix the problem.
Looks like problem hidden in kube-controller/kube-apiserver watch-cache:
```
Operation cannot be fulfilled on daemonsets.extensions "rbd-remounter": StorageError: invalid object, Code: 4, Key: /registry/daemonsets/kube-system/rbd-remounter, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 8a457414-52c8-11e8-8495-6c92bf0b2bc5, UID in object meta: 03192501-e9be-11e8-ab08-a4bf0103966a
```

If i look in etcd i see  UID 03192501-e9be-11e8-ab08-a4bf0103966a
So i think etcd works Ok.

(that happens randomly on different clusters, but i can reproduce it manually).
 
In general to reproduce i use 2 different files with DS/Deployment, only different in limit/request,
to make kube-controller update something.

apply when one by one, not waiting while previous update will finished.
then delete resource while it updating, and apply/create again.

Log snipets:
[logs.log](https://github.com/kubernetes/kubernetes/files/2590221/logs.log)

Thanks for any suggestions.

**Comment by Nefelim4ag** [comment]
I think that can be related: 
#41760

**Comment by Nefelim4ag** [comment]
With etcd 3.3.10, i get new type of  return about (from kubectl) error (i think that really funny):
```
root@K8S-BE01:~# kubectl -n kube-system delete daemonset rbd-remounter
Error from server (Conflict): Operation cannot be fulfilled on daemonsets.extensions "rbd-remounter": StorageError: invalid object, Code: 4, Key: /registry/daemonsets/kube-system/rbd-remounter, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: d1363be6-eb6c-11e8-8922-a4bf0102da29, UID in object meta: 0eb91c8a-eb69-11e8-8922-a4bf0102da29
```

**Comment by Nefelim4ag** [comment]
Also test https://github.com/etcd-io/etcd/pull/10019
Doesn't help.

```
I1119 01:33:31.370815 1655446 round_trippers.go:437] GET http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 200 OK in 2 milliseconds
I1119 01:33:31.568634 1655446 request.go:480] Throttling request took 197.229626ms, request: PUT:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:31.569927 1655446 round_trippers.go:437] PUT http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 409 Conflict in 1 milliseconds
I1119 01:33:31.768626 1655446 request.go:480] Throttling request took 189.628162ms, request: GET:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:31.771139 1655446 round_trippers.go:437] GET http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 200 OK in 2 milliseconds
I1119 01:33:31.968649 1655446 request.go:480] Throttling request took 196.940572ms, request: PUT:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:31.970215 1655446 round_trippers.go:437] PUT http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 409 Conflict in 1 milliseconds
I1119 01:33:32.168607 1655446 request.go:480] Throttling request took 189.605481ms, request: GET:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:32.171074 1655446 round_trippers.go:437] GET http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 200 OK in 2 milliseconds
I1119 01:33:32.368625 1655446 request.go:480] Throttling request took 196.97191ms, request: PUT:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:32.370013 1655446 round_trippers.go:437] PUT http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 409 Conflict in 1 milliseconds
I1119 01:33:32.568667 1655446 request.go:480] Throttling request took 189.689334ms, request: GET:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:32.571069 1655446 round_trippers.go:437] GET http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 200 OK in 2 milliseconds
I1119 01:33:32.768684 1655446 request.go:480] Throttling request took 197.009472ms, request: PUT:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:32.769887 1655446 round_trippers.go:437] PUT http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 409 Conflict in 1 milliseconds
I1119 01:33:32.968617 1655446 request.go:480] Throttling request took 198.536237ms, request: GET:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:32.971677 1655446 round_trippers.go:437] GET http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 200 OK in 2 milliseconds
I1119 01:33:33.168613 1655446 request.go:480] Throttling request took 196.333506ms, request: PUT:http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0
I1119 01:33:33.170029 1655446 round_trippers.go:437] PUT http://localhost:8080/apis/extensions/v1beta1/namespaces/infra/deployments/elasticsearch-0 409 Conflict in 1 milliseconds
```

**Comment by Nefelim4ag** [comment]
That's look like that:
API server cache some info,
then return wrong cached version, and when client try modify object (i.e. send it back to server).
Server check it with etcd version of object and refuse change...

Why API server don't update self cache?

**Comment by Nefelim4ag** [comment]
Rebuild K8s 1.9.11 with etcd 3.1.20 doesn't help.

**Comment by Nefelim4ag** [comment]
Another error what can happen (i use daemonset for tests):
```
      nodeSelector:
        ac446052-eceb-11e8-90b5-a4bf0102da29: ac4460ad-eceb-11e8-90b5-a4bf0102da29
```

Most funny part about that, is what i just not use nodeSelector at all in that DS.
That part added by some race condition when K8s Api/Controller services try modify objects.

**Comment by Nefelim4ag** [comment]
Rebuild k8s 1.9.11 on etcd 3.2.25 - currently in test.

**Comment by k82cn** [comment]
BTW, we did not support 1.9 right now :) It's better to try new version of k8s.

**Comment by Nefelim4ag** [comment]
@k82cn, yep, i know what it too old.
But in any way, before update we need understood where problem happens and fix that problem.
Because when we move to next version, we can only hope what we don't hit any other problems.
And as you can know, debug several random bugs not so easy, because they can affect each other.

Also before move to next version we must port our patches and at least test what all stuff will work correctly - that also will take some time.

Currently updating in tree version of etcd to 3.2.25, looks like fix in our case. Because kube-controller/scheduler stop miss cluster events (i think what just api server stop miss them).

But update etcd to 3.3.10, 3.3.10+ with server/client side watch fixes does not throw away UID mismatch errors if object has been replaced (i.e. delete -> recreate).
That's looks like some type of lag before kube-* services will notice what object has disappeared.

Thanks.

**Comment by Nefelim4ag** [comment]
I will close issue if 3.2.25 really fix problem (Within a week).

**Comment by k82cn** [comment]
> I will close issue if 3.2.25 really fix problem (Within a week).

Sure, please help to verify; that's really helpful info for other. Thanks.

**Comment by Nefelim4ag** [comment]
Looks like fix.
Thanks!

**Comment by edwardstudy** [comment]
Hi, @k82cn. I reproduced this issue on v1.10.12.

I just ran a loop of my integration test and the test sometimes failed with below message when client was updating a secret or configMap:

```
Could not update 'example1': Operation cannot be fulfilled on secrets "example1": StorageError: invalid object, Code: 4, Key: /registry/secrets/test1551059812/example1, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: ee3cd7d6-38a0-11e9-b9e7-9eaa955ab0b9, UID in object meta:
2019-02-25T09:59:35.220+0800	ERROR	extendedstatefulset-reconciler	Could not remove OwnerReferences pointing to ExtendedStatefulSet 'owned-ref-testess-wjjpj': Operation cannot be fulfilled on secrets "example1": StorageError: invalid object, Code: 4, Key: /registry/secrets/test1551059812/example1, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: ee3cd7d6-38a0-11e9-b9e7-9eaa955ab0b9, UID in object meta:
```

**Comment by GounGG** [comment]
use 3.31 of etcd, this problem still exists.

kubernetes: 1.16.3
scheduler log:
```bash
E0914 07:19:33.433325       1 scheduler.go:658] error binding pod: pods "xxxx" not found
E0914 07:19:33.437133       1 scheduler.go:333] Error updating the condition of the pod xxxxxx: Operation cannot be fulfilled on pods "xxxxxx": StorageError: invalid object, Code: 4, Key: /registry/pods/xxxxxx, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: b28d2d8d-8066-436f-b814-3a826b4e2df0, UID in object meta:
```
