### ISSUE TITLE
Changing CRD validation causes existing WATCH requests to silently hang

### ISSUE THREAD

**Issue by drigz** [kubernetes/kubernetes#71138]
**What happened**:

If you establish a WATCH request on a list of CRs, then edit the CRD's `validation` object, you will stop getting MODIFIED events on the WATCH request. The WATCH request doesn't fail or report an error, but will not return more MODIFIED events until the request is restarted.

This causes problems for custom controllers, which become unresponsive until their requests expire.

**What you expected to happen**:

Either the request should end (so it can be restarted safely) or it should continue to return MODIFIED events.

**How to reproduce it (as minimally and precisely as possible)**:

I've attached [repro.sh.txt](https://github.com/kubernetes/kubernetes/files/2590209/repro.sh.txt). It does the following:

- Create CRD and an initial CR.
- Start a proxy, wait for it to come up, then start a watch request.
- Change the CR. (This change to the CR results in a MODIFIED event)
- Change the `validation` section of the CRD.
- Make another change to the CR. (This change to the CR doesn't result in an event).

I've tested this against GKE masters on 1.9, 1.10 and 1.11, as well as a kubeadm 1.12.2 cluster. The output looks like:

```
customresourcedefinition.apiextensions.k8s.io/testcrs.example.com created
testcr.example.com/my-test-cr created
Starting to serve on 127.0.0.1:8303
{"type":"ADDED","object":{"apiVersion":"example.com/v1","kind":"TestCR","metadata":{"creationTimestamp":"2018-11-16T17:08:48Z","generation":1,"name":"my-test-cr","namespace":"default","resourceVersion":"471","selfLink":"/apis/example.com/v1/namespaces/default/testcrs/my-test-cr","uid":"4845b766-e9c2-11e8-a427-02423c385d1a"},"spec":{"a":"asdf"}}}
testcr.example.com/my-test-cr replaced
{"type":"MODIFIED","object":{"apiVersion":"example.com/v1","kind":"TestCR","metadata":{"creationTimestamp":"2018-11-16T17:08:48Z","generation":1,"name":"my-test-cr","namespace":"default","resourceVersion":"474","selfLink":"/apis/example.com/v1/namespaces/default/testcrs/my-test-cr","uid":"4845b766-e9c2-11e8-a427-02423c385d1a"},"spec":{"a":"This change to the CR results in a MODIFIED event."}}}
The first modification has been made.
customresourcedefinition.apiextensions.k8s.io/testcrs.example.com replaced
testcr.example.com/my-test-cr replaced
The second modification has been made.
testcr.example.com "my-test-cr" deleted
customresourcedefinition.apiextensions.k8s.io "testcrs.example.com" deleted
curl: (18) transfer closed with outstanding read data remaining
```

Note that you only see MODIFIED once despite the CR being changed twice.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2-gke.18, 1.12.2
- Cloud provider or hardware configuration: GKE, kubeadm on amd64
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-36-generic #39~16.04.1-Ubuntu SMP

/kind bug

**Comment by drigz** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by yue9944882** [comment]
i suppose it's related w/ #68508

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/78029
