### ISSUE TITLE
RFC 952/1123 allows uppercase characters, but IsDNS1123Subdomain does not

### ISSUE THREAD

**Issue by astrieanna** [kubernetes/kubernetes#71140]
**What happened**:
[`IsDNS1123Subdomain`](https://github.com/kubernetes/kubernetes/blob/f3b98a08b05257fbc3c19b52ced70ea67c546b1e/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L135) and [`IsDNS1123Label`](https://github.com/kubernetes/kubernetes/blob/f3b98a08b05257fbc3c19b52ced70ea67c546b1e/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L116) do not allow uppercase letters.

I ran into this when trying to start kubelet on a node with an all-caps hostname. The node can't register when its node name defaults to the hostname and the hostname includes capital letters.

**What you expected to happen**: 
They should allow uppercase letters.
[RFC 952](https://tools.ietf.org/html/rfc952) says "No distinction is made between upper and lower case." 
[RFC 1123](https://tools.ietf.org/html/rfc1123#page-13) doesn't change that (just allows the first character to be a number). 

/kind bug

**Comment by liggitt** [comment]
we can change the documentation, but changing the validation rules isn't possible to do compatibly at this point

/kind documentation

**Comment by astrieanna** [comment]
@liggitt could you explain more exactly what would be incompatible?

**Comment by thockin** [comment]
Why do we need to change it?  Case-insensitivity is a great way to write lots of subtle bugs.  We didn't do it on purpose.

We could normalize such fields to lower-case, but in general we do not modify user-input like that, so it would be a big deal.

**Comment by liggitt** [comment]
Agree. We should not change the validation rule. We can change the documentation to clarify it must be dns conformant and lowercase

**Comment by thockin** [comment]
And for the record, normalizing names would cause churn on things like `kubectl apply` that we really don't want, I think.

**Comment by freehan** [comment]
no fix yet. closing

**Comment by c3d** [comment]
> And for the record, normalizing names would cause churn on things like `kubectl apply` that we really don't want, I think.

All of Internet goes through that "churn" for what it is worth, because RFC1123, through RFC952, actually mandates it. There is no room for "we don't want to do it for performance reasons" in "No distinction is made between upper and lower case".

It's OK to use your own validation rules. Just don't quote RFC1123 in them, if you can't follow it.

**Comment by maxlillo** [comment]
This is actually quite annoying for automations where you need the hostname the you don't normalize it because of this misimplemented fucntionality

**Comment by semik** [comment]
Please can you remove RFC 1123 from error message? I just run into `ingress.networking.k8s.io \"test\" is invalid: [spec.rules[0].host: Invalid value: \"TEST-HOSTNAME.LOCAL\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: \"TEST-HOSTNAME.LOCAL\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

That error message is misleading. Hostnames are case insensitive. If you have to limit case, do it, but make your own excuse. Do not blame 36 year old standard!

```
      The syntax of a legal Internet host name was specified in RFC-952
      [DNS:4].  One aspect of host name syntax is hereby changed: the
      restriction on the first character is relaxed to allow either a
      letter or a digit.  Host software MUST support this more liberal
      syntax.
```

RFC 952 says:
```
   ASSUMPTIONS

   1. A "name" (Net, Host, Gateway, or Domain name) is a text string up
   to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
   sign (-), and period (.).  Note that periods are only allowed when
   they serve to delimit components of "domain style names". (See
   [RFC-921](https://www.rfc-editor.org/rfc/rfc921), "Domain Name System Implementation Schedule", for
   background).  No blank or space characters are permitted as part of a
   name. No distinction is made between upper and lower case.  The first
   character must be an alpha character.
```

**Comment by thockin** [comment]
It says "a lowercase RFC 1123 subdomain ..."

Anyway, I am hoping to make validation errors better in the next few releases, so this will likely be covered.
