### ISSUE TITLE
Published CRD openapi does not inform kubectl explain or validation

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#71142]
**What happened**:

https://github.com/kubernetes/kubernetes/pull/67205 started publishing crd openapi schemas.

**What you expected to happen**:

`kubectl explain` and `kubectl create` would make use of the schema information

**How to reproduce it (as minimally and precisely as possible)**:

1. create a CRD with a schema: `kubectl create -f staging/src/k8s.io/csi-api/pkg/crd/manifests/csinodeinfo.yaml`
2. try to explain the resource: `kubectl explain csinodeinfo`
3. try to create the resource with invalid fields: `echo '{"kind":"CSINodeInfo","apiVersion":"csi.storage.k8s.io/v1alpha1","metadata":{"name":"foo"},"spec":{"foo":true}}'   | kubectl create -f -`

Kubectl does not successfully discover the schema info

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign sttts roycaihw

/kind bug

**Comment by liggitt** [comment]
a way to add the GVK to the published schema was noted in https://github.com/kubernetes/kubernetes/pull/67205#issuecomment-439496573, but that does not resolve the issues with explain or kubectl validation.

**Comment by roycaihw** [comment]
I think we find the root cause: https://github.com/kubernetes/kubernetes/pull/67205#issuecomment-439524844. Working on a fix

**Comment by nikopen** [comment]
-tracking comment-

this will be closed soon as #71192 merges

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, will #71192 be merged in the next week?

**Comment by roycaihw** [comment]
@soggiest Yes we are actively finalizing the review. Hopefully we will get it tagged & merged soon

**Comment by sttts** [comment]
#71192 merged 🎉
