### ISSUE TITLE
Published CRD openapi schema takes ~60 seconds to appear, increased test time significantly

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#71143]
**What happened**:

#67205 started publishing crd openapi schemas.

**What you expected to happen**:

Schema information to appear quickly when a new CRD is created, and for the integration test added that tests this to complete quickly.

**How to reproduce it (as minimally and precisely as possible)**:

1. create a CRD with a schema: `kubectl create -f staging/src/k8s.io/csi-api/pkg/crd/manifests/csinodeinfo.yaml`
2. wait for the schema to appear: `kubectl get --raw /openapi/v2 | grep '"csi.storage.k8s.io.v1alpha1.CSINodeInfo":'`

It takes ~60 seconds for the schema to appear.

The `TestCRDOpenAPI()` integration test added that does this increased the runtime of the test/integration/master package from 333s (average of five runs on master prior to merge) to 460s (average of five runs against the PR). The other ~25 tests in that package take a total of ~5.5 minutes, and this one test added an additional 2 minutes. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign sttts roycaihw

/kind bug

**Comment by roycaihw** [comment]
The bottleneck is the controller re-queuing each successfully-updated item with [one-minute delay](https://github.com/kubernetes/kubernetes/blob/d0c3cd182cffb3e722b14322fd1ca854a8bf62b0/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go#L34). I'm checking if we can tweak that at least for e2e/integration tests.

**Comment by liggitt** [comment]
that seems indicative of a real problem we'd want to fix in how the create CRD -> register API service -> publish schema flow works, not just something to artificially shorten in the tests

**Comment by roycaihw** [comment]
Openapi schema is aggregated/served on apiextensions-apiserver's handler immediately after CRD is created. It's fine from the aspect of viewing k8s.io/apiextensions-apiserver as an individual product. 

The current work flow is kube-aggregator syncs openapi spec from apiextensions-apiserver every minute. This is also true for aggregated APIServices. Changes in openapi spec of aggregated APIServices may take at most one minute to get reflected on kuybe-apiserver. 

One alternative is we could aggregate CRD schema to kube-apiserver directly (I tried this previously). But this leaks CRD-related code to k/k.

**Comment by sttts** [comment]
If I remember right, the merging algorithms was pretty heavy, runtime around or above a second. I question that this algorithmic problem is that complex. Would like to see somebody to look over that algorithm to get it into the 100ms area. Then we can call it much more often or even on demand if a CRD is changed (with a throttling of once per second max or so).

**Comment by roycaihw** [comment]
@sttts We have two merging algorithms (two spec aggregators):

 - in apiextensions-apiserver, a CRD spec aggregator works with crd_discovery_controller, and aggregates CRD spec on demand when a CRD is changed 
   - (this is newly added in the publish PR)
 - in kube-aggregator, an in-tree spec aggregator works with [controller](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go), and aggregates spec from APIService every minute.

The merging algorithm for CRD spec aggregator is much faster compared to the in-tree one (~80x gain; in 100ms area with 100ish CRDs), because we simply adds spec up instead of checking path conflicts. More details in: https://github.com/kubernetes/kubernetes/pull/67205#discussion_r211789219

**Comment by roycaihw** [comment]
I tried to put together a summary about potential solutions. Haven't been satisfied with any of them. I'd appreciate it if you could take a look and leave any comments/suggestions: 

https://docs.google.com/document/d/13lBj8Stdwku8BgL0fbT__4Iw97NRh77loJ_MoZuCGwQ/edit#

**Comment by spiffxp** [comment]
Any update on this? I'm led to believe https://github.com/kubernetes/kubernetes/pull/71192 is intended to fix this

**Comment by liggitt** [comment]
That is fixing this issue. This is not actually a bug in master, the original PR was backed out. https://github.com/kubernetes/kubernetes/pull/71192 will reintroduce CRD openapi publishing but in a way that resolves this issue as well

**Comment by soggiest** [comment]
Hello!
mountain_snow code freeze mountain_snow is coming in 3 days. Will this be implemented in the next few days?

**Comment by nikopen** [comment]
#71192  has been merged, is this good for closing? @liggitt @roycaihw

**Comment by liggitt** [comment]
yes

/close
