### ISSUE TITLE
private Registry does not work with Deployment Ressource

### ISSUE THREAD

**Issue by StefanSchubert** [kubernetes/kubernetes#71154]
Please reopen ticket #57801 - I believe the problem reoccured in v1.12
@area/kubelet-api

**What happened**:

kind Deployment does not care about private registry.

**What you expected to happen**:

Following the official guide to setup a private docker registry works with deployments, too.

**How to reproduce it (as minimally and precisely as possible)**:

Follow https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry
to configure a private registry. publish an image to your private registry and try to use is within a yaml kind: Deployment. Result: Image can't be pulled.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
client v1.12 (git 1.12.0)
server v1.12 (git 1.12.2)
 
- Cloud provider or hardware configuration:
onPremise
- OS (e.g. from /etc/os-release):
centos7
- Install tools:
kubeadm

/kind bug

**Comment by gluehbirnenkopf** [comment]
I just tested assigning the serviceaccount with a pull secret and automounting this within the deployment.
Anybody can confirm that automountserviceaccounttoken=true still works?

For me not.

**Comment by StefanSchubert** [comment]
Hi @gluehbirnenkopf,

thanks for confirmation. I hadn't in mind that the secret could be coupled by the service account.
So I tried the following, stripped the imagePullSecret from my deployment.yaml and patched the default service account with the imagePullSecret. After that the container/pod could be build by taking the image from the private registry.

So finally it works out for me, though is it a good idea to have a tight coupling between service-account and private registry? I would prefer to have the possibility to use the setting directly within the deployment yaml, where the image is specified and the image is the one which is coupled to the registry.

**Comment by markvincentcaro** [comment]
@StefanSchubert How did you set your secret as the default service account's image pull secret?

**Comment by liggitt** [comment]
> I would prefer to have the possibility to use the setting directly within the deployment yaml, where the image is specified and the image is the one which is coupled to the registry.

You can specify imagePullSecrets directly in the deployment spec or in the service account, whichever you prefer. Ones specified on the deployment take precedence:

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/serviceaccount/admission.go#L191

**Comment by liggitt** [comment]
> Anybody can confirm that automountserviceaccounttoken=true still works? I thought at least this would be a workaround, but seems not.

That is related to mounting API credentials into the pod. It is unrelated to image pull secrets

**Comment by liggitt** [comment]
Can you provide:

1. The deployment manifest you used that attempted to set an image pull secret (as retrieved from the API server with `kubectl get deployment <name> -o yaml`
2. An example pod created from that deployment (as retrieved from the API server with `kubectl get pod <name> -o yaml`)
3. The command used to create the referenced secret (with confidential parameters redacted), and the kubectl version used to create it

**Comment by bsakweson** [comment]
Did this ever gotten resolved? I just ran into the same issue. I have my secret actually specified in the the container. I just want to add that I followed this [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) to the T. Here is my pod info using -o yaml options:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"private-reg","namespace":"default"},"spec":{"containers":[{"image":"registry.domain.com/kong:1.0.3-oidc","name":"kong"}],"imagePullSecrets":[{"name":"regcred"}]}}
  creationTimestamp: "2019-02-25T11:52:41Z"
  name: private-reg
  namespace: default
  resourceVersion: "1578048"
  selfLink: /api/v1/namespaces/default/pods/private-reg
  uid: db28c3b3-38f3-11e9-b648-74d435bc2121
spec:
  containers:
  - image: registry.domain.com/kong:1.0.3-oidc
    imagePullPolicy: IfNotPresent
    name: kong
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-mrfsk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: node4
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-mrfsk
    secret:
      defaultMode: 420
      secretName: default-token-mrfsk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-02-25T11:52:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-02-25T14:33:12Z"
    message: 'containers with unready status: [kong]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-02-25T14:33:12Z"
    message: 'containers with unready status: [kong]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-02-25T11:52:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://760c04d309e4d070b52dfb4ef46e0ff7792e416ed7f8418babe3081112712957
    image: registry.domain.com/kong:1.0.3-oidc
    imageID: docker-pullable://registry.domain.com/kong@sha256:fdf84abbb57c7debaf160995f2cc6fb65cbdc35b5138d48c74ebcacd50b4e563
    lastState:
      terminated:
        containerID: docker://760c04d309e4d070b52dfb4ef46e0ff7792e416ed7f8418babe3081112712957
        exitCode: 1
        finishedAt: "2019-02-25T14:33:11Z"
        reason: Error
        startedAt: "2019-02-25T14:33:10Z"
    name: kong
    ready: false
    restartCount: 33
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=kong pod=private-reg_default(db28c3b3-38f3-11e9-b648-74d435bc2121)
        reason: CrashLoopBackOff
  hostIP: xxx.xxx.x.xx
  phase: Running
  podIP: xxx.xxx.x.xx
  qosClass: BestEffort
  startTime: "2019-02-25T11:52:41Z"
```

**Comment by bsakweson** [comment]
It turns out that there are barely any search results out there that talks about ways to resolve this issue. In my case the issue with the url. The official tutorial mention in my posts above completely missed that also. The solution was to make sure that the url has the v2 part attached to it. In other words, it should be like this `registry.mydomain.com/v2` that is if your registry is version 2. I believe the document just says `registry.mydomain.com`.

**Comment by diadara** [comment]
Can confirm that specifying the second part of the registry in the regestry credentials solves this issue for 1.12  as @bsakweson suggests.
