### ISSUE TITLE
[Failing Test] [k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#71153]
**Which jobs are failing**: https://k8s-testgrid.appspot.com/sig-release-1.13-all#soak-gci-gce-1.13

**Which test(s) are failing**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/481

Error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet_perf.go:263
Nov 15 15:34:31.439: Memory usage exceeding limits:
 node bootstrap-e2e-minion-group-vzfd:
 container "runtime": expected RSS memory (MB) < 367001600; got 368508928
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet_perf.go:155
```

**Since when has it been failing**: Started failing 11/13/2018

**Testgrid link**: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/481

/kind failing-test
/priority critical-urgent
/sig node
/milestone v1.13
/cc @dchen1107 @derekwaynecarr

**Comment by AishSundar** [comment]
/cc @dims @mkumatag @jingxu97 @dchen1107 @jberkus 

@dims and @dchen1107 we are seeing this specific Kubelet test fail 90% on the 1.13 branch. I didnt see any recent change to the test itself, but want to get the failure checkout. Can one of you please triage and assign to the right owner? I am setting the priority as critical-urgent until its triaged otherwise. Thanks

**Comment by AishSundar** [comment]
/assign @dchen1107 

@dchen1107 this is now failing consistently on 1.13. Can you plz help triage as priority?

**Comment by dchen1107** [comment]
This shouldn't become the release blocker. 

```
 node bootstrap-e2e-minion-group-vzfd:
 container "runtime": expected RSS memory (MB) < 367001600; got 368508928
```

Just indicates that after several days soaking test, at one of node, docker's memory usage exceeds the certain threshold. The same test failed with soaking test in previous releases too.

**Comment by jberkus** [comment]
This test just failed on both serial and soak today.

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-serial/1668
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/500

Might be random, but it does seem (per Triage as well) that failures are getting more frequent.

**Comment by jberkus** [comment]
Changing to flake

/kind flake
/remove-kind failing-test

**Comment by jberkus** [comment]
This is flaking pretty badly in the soak test:

https://k8s-testgrid.appspot.com/sig-release-1.13-all#soak-gci-gce-1.13

@dchen1107 can we get someone to look into this, and either fix the memory leak or change the parameters of the test?  Just saying "It flakes sometimes" doesn't really work for testing.

**Comment by jberkus** [comment]
Another burst of failures on this test and the related "0 pods per node" test this week.
