### ISSUE TITLE
Support OIDC token validation (introspection) in the API server

### ISSUE THREAD

**Issue by hb3b** [kubernetes/kubernetes#71151]
**What would you like to be added**:
An OIDC option (optional) in the API server for validating OIDC tokens against a token introspection endpoint.

**Why is this needed**:
Administrators are unable to prevent Kubernetes from accepting signed ID tokens that have been revoked by an OIDC provider.

/kind feature
/sig auth

**Comment by hb3b** [comment]
Any thoughts? @kubernetes/sig-auth-feature-requests

**Comment by mecampbellsoup** [comment]
> Kubernetes OIDC usage closely resembles the implicit flows with response_type=id_token. In this flow, the OIDC client (i.e. Kubernetes API server) doesn't directly contact the OIDC provider. In fact it can't, because it never receives an access token. Because the client never interacts with the OIDC provider, this flow does not lend itself to long lived ID tokens. If you want to do extra validation, you can always use the webhook authenticator:
> 
> [kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication)

This is a very lucid and reasonable response.

Question: in what scenarios do you see benefits of implementing a full-fledged OIDC server (i.e. Identity Provider) over just a normal "webhook token" auth server that issues/processes opaque tokens?
