### ISSUE TITLE
go get -u github.com/kubernetes/kubernetes/cmd/kubelet

### ISSUE THREAD

**Issue by tanweernoor** [kubernetes/kubernetes#71168]
below should work... 
go get -u github.com/kubernetes/kubernetes/cmd/kubelet

install works fine but service fails due to below issue...

kubelet version
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x757bb80, 0x493c4f4, 0xf, 0x4d01320, 0x4abd600)
/usr/lib64/go/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0x757bb80, 0x493c4f4, 0xf, 0x4abd600)
/usr/lib64/go/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0x493c4f4, 0xf, 0x4abd600)
/usr/lib64/go/src/net/http/server.go:2380 +0x4b
k8s.io/kubernetes/vendor/golang.org/x/net/trace.init.0()

**Comment by neolit123** [comment]
/sig release
/triage support

shouldn't you be doing this instead:
```
go get -u k8s.io/kubernetes/cmd/kubelet
```

**Comment by tanweernoor** [comment]
sig/cli
kind/bug

**Comment by tanweernoor** [comment]
thanks for the comment, however, i am putting "go get -u github.com/kubernetes/kubernetes/cmd/kubelet" in the spec file

**Comment by dims** [comment]
@tanweernoor - yea, don't do that :) follow what @neolit123 mentioned

**Comment by dims** [comment]
@vharsh we just recently got it working. So please do file a PR against that document if you get some time.
