### ISSUE TITLE
CSI: Take advantage of `csi_secret` in CSI 1.0

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#71186]
**What happened**:
CSI 1.0 decorates sensitive fields with `csi_secret`. Let's take advantage of this feature to programmatically ensure no sensitive CSI fields are ever logged by kubernetes components (kubelet).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by sbezverk** [comment]
@pohly I have not heard about that being `a bad style` in fact, kubernetes-incubator and kubernetes csi do import right from kubernetes repo packages:
```
kubernetes-incubator sbezverk$ grep -r "k8s.io/kubernetes/pkg" ./ | grep -v vendor | grep -v staging | wc -l
      54
kubernetes-csi sbezverk$ grep -r "k8s.io/kubernetes/pkg" ./ | grep -v vendor | grep -v staging | wc -l
      24
```

**Comment by pohly** [comment]
Serguei Bezverkhi <notifications@github.com> writes:
> @pohly I have not heard about that being `a bad style`

It was one of the first things that were pointed out when I explained
that I wanted to make "test/e2e/framework" reusable for developers
outside of Kubernetes.

> in fact, kubernetes-incubator and kubernetes csi do import right from
> kubernetes repo packages:

That it's done doesn't mean that it should be done this way.

**Comment by liggitt** [comment]
> @pohly @saad-ali we could add sanitizing code in kubernetes repo in `pkg/volume/csi/csi_util.go` and then it can be imported by external csi components

If the code is intended for reuse outside of kubernetes/kubernetes, it should live in one of the staging repos.

**Comment by pohly** [comment]
Jordan Liggitt <notifications@github.com> writes:

>> @liggitt the idea was to have the same func to be used in kubelet as well as in external csi components.
>
> that's fine. the kubelet can use code in the staging repos.

@liggitt and just to be clear, the external CSI components shouldn't use
k8s.io/kubernetes whereas pulling from the mirrored staging repos
(like k8s.io/utils) is fine, right?

**Comment by sbezverk** [comment]
@liggitt @pohly since it is CSI specific func, how about `k8s.io/csi/utils` ?

**Comment by saad-ali** [comment]
> @liggitt and just to be clear, the external CSI components shouldn't use
> k8s.io/kubernetes whereas pulling from the mirrored staging repos
> (like k8s.io/utils) is fine, right?

External components can not depend on `github.com/kubernetes/kubernetes`. If there is external code that has a common library, that common library should live in it's own external repo that can be imported by all consumers.

If the library is also required by code living in `github.com/kubernetes/kubernetes` we can put it in staging where it will get mirrored to a external repo like `github.com/kubernetes/csi-api`. In this case the `kubernetes/kubernetes` code will depend on the internal staging version of the library. All external code will depend on the mirrored external repo.

In this case, it does appear that we don't log anywhere in k/k, so there is no immediate need for this library. Either of these approaches (putting it in an external repo, or putting it in staging and having it mirrored to an external repo) would be fine. For the sake of simplicity, we may want just put it in a new external repo `github.com/kubernetes-csi/csi-utils` for now?

**Comment by sbezverk** [comment]
@saad-ali works for me, thanks for detailed explanation..

**Comment by saad-ali** [comment]
@sbezverk Either you or @pohly, feel free to create an issue on https://github.com/kubernetes/org/issues. And I can approve it.

Let's call the new repo: `github.com/kubernetes-csi/csi-lib-utils`?

**Comment by sbezverk** [comment]
@saad-ali here you go: https://github.com/kubernetes/org/issues/268

**Comment by saad-ali** [comment]
`kubernetes/kubernetes` doesn't log CSI grpcs. The external components that do are being updated to use https://github.com/kubernetes-csi/csi-lib-utils/tree/master/protosanitizer
