### ISSUE TITLE
[Failing Test] TestAdoption in Integration-master job blocking merges

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#71189]
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master seems to be failing in master branch alone

**Which test(s) are failing**:
[k8s.io/kubernetes/test/integration/replicationcontroller.TestAdoption](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-integration-master/6740)

**Since when has it been failing**:
Since 11/18

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master 

**Anything else we need to know**:
The integration job on 1.13 branch seems to be fine. This is now failing in presubmits, blocking merges in 

https://github.com/kubernetes/kubernetes/pull/71187

/kind failing-test
/sig testing
/priority critical-urgent
/milestone v1.13

/assign @cblecker @BenTheElder

**Comment by liggitt** [comment]
failure is 
``` 
--- FAIL: TestAdoption (3.63s)
    replicationcontroller_test.go:434: Failed to create replication controllers: 0-length response
```

**Comment by neolit123** [comment]
i've been seeing this flake the past week.
