### ISSUE TITLE
`kubectl auth reconcile` auto-creates namespaces

### ISSUE THREAD

**Issue by jessesuen** [kubernetes/kubernetes#71185]
**What happened**:

I noticed some surprising behavior of `kubectl auth reconcile`, which I'm not sure is intentional, but is very unexpected, in that `kubectl auth reconcile` will auto-create namespaces if it doesn't exist. This behavior does not seem to be documented anywhere.

For example, if I run:
```
kubectl auth reconcile --namespace my-namespace -f /tmp/my-role.yaml
```
against the following Role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
rules:
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - list
```

Then the namespace `my-namespace` gets created. This is confirmed when enabling logs in kubectl:

```
I1118 03:11:38.222982   89185 round_trippers.go:405] GET https://REDACTED/apis/rbac.authorization.k8s.io/v1/namespaces/my-namespace/roles/my-role 404 Not Found in 32 milliseconds
I1118 03:11:38.261152   89185 round_trippers.go:405] POST https://REDACTED/api/v1/namespaces 201 Created in 37 milliseconds
I1118 03:11:38.304245   89185 round_trippers.go:405] POST https://REDACTED/apis/rbac.authorization.k8s.io/v1/namespaces/my-namespace/roles 201 Created in 40 milliseconds
role.rbac.authorization.k8s.io/my-role reconciled
```

**What you expected to happen**:

`kubectl auth reconcile` is described in the CLI description as "preferred to 'apply' for RBAC resources so that proper rule coverage checks are done."

However, this cannot be used as a drop-in replacement for apply as it requires additional privileges on the client, and the behavior is not symmetrical when the namespaces do not exist. I would expect the command to fail if the namespace does not exist.

In the case of `kubectl apply` you simply get NotFound
```
$ kubectl apply -f /tmp/my-role.yaml --namespace non-existant-ns
Error from server (NotFound): error when creating "/tmp/bg.yaml": namespaces "non-existant-ns" not found
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version --client -o yaml
clientVersion:
  buildDate: 2018-09-28T15:20:58Z
  compiler: gc
  gitCommit: 0ed33881dc4355495f623c6f22e7dd0b7632b7c0
  gitTreeState: clean
  gitVersion: v1.12.0
  goVersion: go1.11
  major: "1"
  minor: "12"
  platform: darwin/amd64
```

/sig cli
/sig auth

/kind bug

**Comment by WanLinghao** [comment]
@deads2k  It seems that this is a intended feature

**Comment by enj** [comment]
The code that backs `auth reconcile` is used on the server side as well.  Hence the namespace creation was added in #48480.  I made it best effort in #70351 which will land in 1.13.

**Comment by jessesuen** [comment]
Changing it to best effort doesn't actually help our specific situation because the deployment tool we are building (Argo CD), relies on running the kubectl CLI to perform deployments, and has root access. 

After changing the command from:
```
kubectl apply -f some-rbac-role.yaml --namespace some-namespace
```
to:
```
kubectl auth reconcile -f some-rbac-role.yaml --namespace some-namespace
```

Suddenly we were creating namespaces in some situations when we didn't expect it to be created, where we could rely on an error coming back from `apply` about the missing namespace. Since Argo CD runs as root, best effort doesn't help.

The simple workaround on our end is to just preface it with a `get ns`:
```
kubectl get ns some-namespace && kubectl auth reconcile -f some-rbac-role.yaml --namespace some-namespace
```

But I would suggest documenting this behavior at least.

**Comment by liggitt** [comment]
It is intentional. +1 for documenting.

**Comment by liggitt** [comment]
/assign
opened #71397
