### ISSUE TITLE
container-lifecycle-hooks do not execute on image update 

### ISSUE THREAD

**Issue by joshshn** [kubernetes/kubernetes#71191]
**What would you like to be added**:

Kubernetes 1.12 provides container-lifecycle-hooks: PostStart and PreStop. PreStop hook is called when a container is terminated. However when updating the image of a container via the command
'kubectl set image pod pod-name pod=imagename:v2' does not invoke the PreStop hook for cleaning up of pod data.

**Why is this needed**:
Any cleanup in the pods required before updating the image can be executed.

/kind feature

**Comment by QuinnBast** [comment]
/reopen

This is still an issue. PostStart does not run after a container gets updated in-place using `kubectl edit` or `kubectl set image` etc.
