### ISSUE TITLE
Transient 404 for custom resource after etcd restart

### ISSUE THREAD

**Issue by drigz** [kubernetes/kubernetes#71218]
**What happened**:

I got a 404 Not Found error from the apiserver for a custom resource that exists. The 404 error only persisted for one request, after which 200s were returned as normal.

I originally observed this on GKE at the end of a control plane upgrade, but have also reproduced this using https://github.com/kubernetes-sigs/kind and sending SIGTERM to etcd.

**What you expected to happen**:

apiserver shouldn't return 404 for existing resources.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install [kind](https://github.com/kubernetes-sigs/kind#installation-and-usage) and create a cluster.
1. Start a proxy for test requests:
    ```
    KUBECONFIG=$(kind get kubeconfig-path) kubectl proxy &>dev/null &
    ```
1. Start sending test requests to etcd:
    ```
    while true; do
        curl -m 1 -s -D- http://localhost:8005/apis/example.com/v1/namespaces/default/testcrs/my-test-cr
    done | grep ^HTTP | uniq -c
    ```
1. Periodically kill etcd:
    ```
    while true; do
        sudo kill $(ps ax | grep "etcd[ ]--ad" | awk '{print $1}')
        sleep 2m
    done
    ```

Because of the pod restart backoff, it may take some time to reproduce the issue: I ran for about half an hour and saw the following:

```
  16006 HTTP/1.1 200 OK
    618 HTTP/1.1 502 Bad Gateway
      1 HTTP/1.1 404 Not Found
    911 HTTP/1.1 200 OK
   4213 HTTP/1.1 502 Bad Gateway
  17700 HTTP/1.1 200 OK
   6136 HTTP/1.1 502 Bad Gateway
      3 HTTP/1.1 404 Not Found
  50668 HTTP/1.1 200 OK
    997 HTTP/1.1 502 Bad Gateway
      1 HTTP/1.1 404 Not Found
  11817 HTTP/1.1 200 OK
   5023 HTTP/1.1 502 Bad Gateway
      1 HTTP/1.1 404 Not Found
   6367 HTTP/1.1 200 OK
  22570 HTTP/1.1 502 Bad Gateway
```

Note the few `404 Not Found` errors occurring after the `502 Bad Gateway` errors that indicate the unavailability of etcd.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: v1.12.2 (also observed on GKE with versions 1.10.9 and 1.11.2)
- Cloud provider or hardware configuration: kubeadm amd64
- OS (e.g. from /etc/os-release): Debian Buster-like
- Kernel (e.g. `uname -a`): 4.18.10
- Install tools:
- Others:

/kind bug

**Comment by drigz** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
this is related to server restart, not to etcd being down. I can recreate simply by restarting the apiserver while making hotloop requests to the custom resource endpoint.

the custom resource handler should return a 503 response to requests that are sent to it before it has filled its cache with active CRDs
