### ISSUE TITLE
"Fixes" needs to be urgently removed from the PR template

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71224]
It's our policy that contributors NOT use the phrasing "Fixes #99999" in PR requests, as that causes associated issues to auto-close by github.  In fact, test-infra is planning a feature that will block this text.  However, the Fixes line is present in the default PR template for k/k and possibly other repos.

The urgency here is that contributors using "Fixes" is causing problems for the 1.13 Release Team, since issues are being auto-closed that are not, in fact, fixed, and we lose track of them.

Line from PR template:

```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
```

/sig contributor-experience
/priority important-soon
/milestone 1.13

cc
@cblecker @castrojo @spiffxp @AishSundar

**Comment by AishSundar** [comment]
This is definitely something we want fixed for /kind flake and failing-test. Even in case of bug fixes, I think it should be upto the issue reporter to verify and close the issue vs the bot doing it. I assume this might be an issue even with feature issues since most features have multiple PRs to address them.

AFAICT, the only exception might be /kind cleanup (?)

**Comment by nikhita** [comment]
>  In fact, test-infra is planning a feature that will block this text.

Just to be clear, the test-infra feature will _not_ block this text in the PR body. It will only block this text in the commit message.

**Comment by cblecker** [comment]
How urgent is this? This line has been in the template since August 2016 (over two years).
https://github.com/kubernetes/kubernetes/commit/2a008b947a875deaf7d696c79debbd090ba6c5fb

**Comment by jberkus** [comment]
@cblecker for some reason, on this release we're getting a *lot* of test-fail PRs that are flagged "Fixes", which is causing the issues to auto-close even when the test is still failing.  It's making it challenging to do CI Signal.

**Comment by nikopen** [comment]
Opened this: https://github.com/kubernetes/kubernetes/pull/71278

**Comment by liggitt** [comment]
Hmmm… I didn't understand this to mean we were forbidding use of it. Having to manually close every fixed issue is error prone and unnecessary work

**Comment by justaugustus** [comment]
> > It's our policy that contributors NOT use the phrasing "Fixes #99999" in PR requests, as that causes associated issues to auto-close by github.
> 
> Where was this policy proposed and agreed on?

I believe the consensus was that we didn't want magic keywords in the commit message, because it leads to a lot of noise, but AFAIK no one has said it those keywords shouldn't be included in PR / Issue descriptions. More discussion here: https://github.com/kubernetes/test-infra/issues/9360

**Comment by liggitt** [comment]
> I believe the consensus was that we didn't want magic keywords in the commit message, because it leads to a lot of noise, but AFAIK no one has said it those keywords shouldn't be included in PR / Issue descriptions

That's what I recall as well. Being in the commit message auto-closes and tags issues every time the commit is pulled into a fork or other repo. 

Using the PR description to auto-close an issue on merge is useful and desired in many cases. If there are specific types of issues we don't want people to do that on, a comment in the template seems reasonable.

**Comment by liggitt** [comment]
not release-blocking, will leave open to track improvements to wording in the PR template
