### ISSUE TITLE
export of "(cluster)roles/rolebindings" not supported

### ISSUE THREAD

**Issue by gladiatr72** [kubernetes/kubernetes#71226]
---

With the following descriptions, please pretend there are duplicate figures for role/clusterrole/rolebinding/clusterrolebinding

---

**What would you like to be added**:

For... reasons, you can export a namespace's entire rack of _roles_ and _rolebindings_ but not individuals.

```

kubectl get role -n namespace name-of-role --export -o yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
```
instead of

```

kubectl get role -n namespace name-of-role --export -o yaml

Error from server (BadRequest): export of "rolebindings" is not supported

```

**Why is this needed**:

This is an arbitrary limitation of GA features.  RBAC adoption should be encouraged.  Proper use of RBAC already adds a _very understandable_ amount of complexity to RBAC adoption--the API should not make this adoption more challenging than necessary.

`kubectl get role -n namespace --export -o yaml` already provides an _items_ collection without complaint.  

/kind feature

**Comment by gladiatr72** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
/close

this is a duplicate of https://github.com/kubernetes/kubernetes/issues/47228

export is not supported on RBAC resources currently. the fact that `kubectl get` accepts the --export parameter for a list objects without complaint is a bug (https://github.com/kubernetes/kubernetes/issues/49497), which was closed with this comment:

> this issue is noted in the original "implement export" issue in https://github.com/kubernetes/kubernetes/issues/24855#issuecomment-329889844 which is still open... this very much seems like a partially designed feature that we need to finish designing before changing behavior further

export is not uniformly supported, nor is it clear that it will be. see comments in https://github.com/kubernetes/kubernetes/issues/24855#issuecomment-365407438

Use `kubectl get ... -o yaml` to obtain the yaml for an individual API object.
