### ISSUE TITLE
Update local PV tests to use the new storage test framework

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71237]
**What would you like to be added**:
We've been refactoring the storage e2e tests to be plugin-agnostic.  We should migrate as many local PV tests to use it as much as possible, and maybe even consider converting local PV test cases to be plugin-agnostic if it makes sense.

There are still major changes going on in this area right now though.  We should wait until https://github.com/kubernetes/kubernetes/pull/70862 and https://github.com/kubernetes/kubernetes/pull/70992 have merged.

@kubernetes/sig-storage-feature-requests 

/kind feature

**Comment by msau42** [comment]
cc @cofyc @NickrenREN, would one of you be interested in working on this?

**Comment by msau42** [comment]
As a first step, we can add local PV to the TestDriver interface here: https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/storage/drivers/in_tree.go.

By doing this, we automatically get a bunch of test cases running against local PV.

**Comment by cofyc** [comment]
## Current contexts of "PersistentVolumes-local"

### Volume type agnostic

`KUBERNETES_PROVIDER="local" ./hack/ginkgo-e2e.sh  --ginkgo.focus='PersistentVolumes-local' --ginkgo.dryRun | grep 'sig-storage' | grep 'Volume type' -v | sort | uniq`

[sig-storage] PersistentVolumes-local  Local volume that cannot be mounted [Slow] 
[sig-storage] PersistentVolumes-local  Pod with node different from PV's NodeAffinity 
[sig-storage] PersistentVolumes-local  StatefulSet with pod affinity [Slow] 
[sig-storage] PersistentVolumes-local  Stress with local volumes [Serial]

### Volume type

#### List of volume types

`KUBERNETES_PROVIDER="local" ./hack/ginkgo-e2e.sh  --ginkgo.focus='PersistentVolumes-local' --ginkgo.dryRun | grep 'sig-storage' | grep 'Volume type' | grep -o -P 'Volume type: [^\]]+' | sort | uniq`

Volume type: block
Volume type: blockfswithformat
Volume type: blockfswithoutformat
Volume type: dir
Volume type: dir-bindmounted
Volume type: dir-link
Volume type: dir-link-bindmounted
Volume type: gce-localssd-scsi-fs
Volume type: tmpfs

#### Contexts

`KUBERNETES_PROVIDER="local" ./hack/ginkgo-e2e.sh  --ginkgo.focus='PersistentVolumes-local' --ginkgo.dryRun | grep 'sig-storage' | grep 'Volume type' | sed -r 's/Volume\stype:\s[a-z-]+/Volume type: {fs}/' | sort | uniq`

[sig-storage] PersistentVolumes-local  [Volume type: {fs}] One pod requesting one prebound PVC 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] Set fsGroup for local volume 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] Two pods mounting a local volume at the same time 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] Two pods mounting a local volume one after the other 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] [Serial] One pod requesting one prebound PVC 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] [Serial] Set fsGroup for local volume 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] [Serial] Two pods mounting a local volume at the same time 
[sig-storage] PersistentVolumes-local  [Volume type: {fs}] [Serial] Two pods mounting a local volume one after the other

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by msau42** [comment]
The remaining items are cleanup items are not urgent for 1.14
/milestone clear
