### ISSUE TITLE
Critical pod is still being evicted in 1.13

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#71234]
**What happened**:

In 1.13, critical pod (with annotation `scheduler.alpha.kubernetes.io/critical-pod: ""`, or with priorityClass "system-cluster-critical") are being evicted if the node becomes NotReady or Unreachable.

**What you expected to happen**:

Critical pod should be applied with corresponding toleration without tolerationSeconds, hence unable to be evicted.

**How to reproduce it (as minimally and precisely as possible)**:

- prepare a 1.13 cluster with 2+ nodes, and enable `ExperimentalCriticalPodAnnotation` featuregate
- create a sample pod in kube-system, with criticalPod annotation:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
```

- on the worker node where the pod lands, manually block network connectivity to apiserver

```console
$ k get po -n kube-system -o wide | grep pause
pause-7bbd88b47d-7qzns                  1/1     Running   0          9m1s   10.244.2.3   kube-node-1
$ k get no | grep node-1
kube-node-1   Ready                      <none>   15m   v1.14.0-alpha.0.503+8848740f6d0f8

# Block network from kube-node-1 to master

$ k get no | grep node-1
kube-node-1   NotReady                   <none>   16m   v1.14.0-alpha.0.503+8848740f6d0f84
$ k get po -n kube-system -o wide | grep pause
pause-7bbd88b47d-7qzns                  1/1     Running   0          12m   10.244.2.3   kube-node-1
$ k get po pause-7bbd88b47d-7qzns -o yaml -n kube-system | grep -i toleration -A3
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

# After 300 seconds

$ k get po -n kube-system -o wide | grep pause
pause-7bbd88b47d-7qzns                  1/1     Terminating   0          17m   10.244.2.3   kube-node-1   <none>           <none>
pause-7bbd88b47d-9fdp9                  0/1     Pending       0          36s   <none>       <none>        <none>           <none>
```

**Anything else we need to know?**:

Note that critical pod can refer to a pod (1) with annotation `scheduler.alpha.kubernetes.io/critical-pod: ""` or (2) with priorityClass "system-cluster-critical"). So this issue also happen in 1.12 and 1.11.

**Environment**:
- Kubernetes version (use `kubectl version`): master branch (v1.13.0-beta)
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm-dind-cluster
- Others:

/kind bug
/sig scheduling

**Comment by Huang-Wei** [comment]
cc/ @k82cn @ravisantoshgudimetla

**Comment by k82cn** [comment]
evicted after `tolerationSeconds: 300` or evicted immediately?

**Comment by Huang-Wei** [comment]
@k82cn They're evicted after 300 seconds, just like normal pods.

**Comment by k82cn** [comment]
emm... If so, I think that should be fine :) `critical-pod` is cluster level system pod; if the node is not-ready or unreachable, we'd better re-schedule it to other nodes to make service ready; otherwise, we're not sure whether the 'critical' is healthy :)

**Comment by k82cn** [comment]
we need to make sure the `critical-pod` will evict others to run :)

**Comment by Huang-Wei** [comment]
> if the node is not-ready or unreachable, we'd better re-schedule it to other nodes to make service ready

This is reasonable :)

/cc @ravisantoshgudimetla any particular case you have in mind is more an issue?

> we need to make sure the `critical-pod` will evict others to run :)

I think it's covered well by preemption logic.

**Comment by Huang-Wei** [comment]
@ravisantoshgudimetla right now **daemonset pods** are applied with no-execute tolerations without tolerationSeconds, say they will be kept on the node even the node is not-ready/unreachable.

And after that, it will be handled by admission - which applied "tolerationSeconds=300" to **every** pod - unless they already carry tolerations, e.g. like daemonset pod.

So your suggestion of "apply `NoExecute` toleration without tolerationSeconds to any critical pod which has `system-node-critical` priority" makes sense to me. Because for `system-node-critical`, as its name implies, it should be kept onto the node no matter if the node becomes not-ready or unreachable. @bsalamat @k82cn thoughts?

And for `system-cluster-critical` pods, in eviction's (not preemption) perspective, they are treated the same as regular pods.

**Comment by ravisantoshgudimetla** [comment]
@Huang-Wei - That is right, one use-case I could think of having `system-node-critical` components when the control plane components are created as static pods. If that node is applied a `NoExecute` taint, we should let control plane components still run on it, if they have `system-node-critical` priorityClass.

**Comment by liggitt** [comment]
> If that node is applied a NoExecute taint, we should let control plane components still run on it, if they have system-node-critical priorityClass.

That seems to be confusing two things. Toleration of unready conditions (or other node taints) is orthogonal to priority relative to other pods. I would not expect criticality to affect how a pod's tolerations work.

A critical component can indicate it tolerates all unready conditions (with a wildcard toleration), and that it should have priority over other pods (with a critical annotation or priorityclass setting).

**Comment by ravisantoshgudimetla** [comment]
>  Toleration of unready conditions (or other node taints) is orthogonal to priority relative to other pods. I would not expect criticality to affect how a pod's tolerations work.

- IIUC, the point you are trying to make is separation of concerns where priority is something that is relative to pods and has nothing to do with criticality. I agree with your point but we are adding implicit tolerations to critical DS pods for example `NotReady` toleration. While the context may be different there, I believe if we are adding tolerations we should do the same for other pods unless there is a good reason for it.

 https://github.com/kubernetes/kubernetes/blob/1e50c5711346e882a54e833a9931af9678af7a82/pkg/controller/daemon/daemon_controller.go#L1423

- While an explicit mention of NoExecute tolerations may be good, I think, when we enable `TaintNodesByConditions` and `TaintBasedEvictions` as part of upgrade and if control-plane components don't have explicit NoExecute toleration(which is a possibility), there is a very good chance that they would get evicted making the upgrade difficult.

- Finally, critical pods are separated into `system-cluster-critical` components and `system-node-critical` pods, here we don't want `system-node-critical` pods to be evicted by scheduler or other component. Previously, we never had the notion of 'cluster-critical` and `node-critical`, and it would have made sense in the previous scenario as it is ok to evict critical pods and they could run on other node. Also, if the pod spec has both toleration to all taints and priorityClass `system-node-critical` it may defeat the purpose of having `system-node-critical` as we explicitly mentioned in the documentation that we don't want any pod with this priorityClass to be evicted.

**Comment by liggitt** [comment]
> While the context may be different there, I believe if we are adding tolerations we should do the same for other pods unless there is a good reason for it.

Auto-adding tolerations limits the power of the API by equating priority with tolerations

**Comment by ravisantoshgudimetla** [comment]
I think here is the place- 

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/util/daemonset_util.go#L52-#L61

> Auto-adding tolerations limits the power of the API by equating priority with tolerations

I am not denying that - Just that special priority classes should be given meaningful tolerations or at  least be removed which can have conflicting effects with other features.

**Comment by liggitt** [comment]
> I think here is the place-
>
> https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/util/daemonset_util.go#L52-#L61

I think that was done to maintain compatibility with pre-scheduler daemonset behavior, not as a model of what we want the interaction between priority and tolerations to be

**Comment by ravisantoshgudimetla** [comment]
You mean this was DS controller was doing this right from the start or was it created after scheduler started scheduling DS pods? I think it's the former and if that is the case, we have been doing it from a long time.

**Comment by liggitt** [comment]
Tolerations affect how the scheduler assigns pods to nodes. Originally, the daemonset controller assigned pods to nodes, bypassing the scheduler. When making the switch to use the scheduler, it had to start adding tolerations to preserve existing assignment behavior

**Comment by k82cn** [comment]
> When making the switch to use the scheduler, it had to start adding tolerations to preserve existing assignment behavior

Yes, we add tolerations to keep backward compatibility of DeamonSetController :)

> Toleration of unready conditions (or other node taints) is orthogonal to priority relative to other pods. I would not expect criticality to affect how a pod's tolerations work.

+1, toleration and priority are two different features; it's better to let user to decide how them work together if we do not have real use case right now.

**Comment by ravisantoshgudimetla** [comment]
> When making the switch to use the scheduler, it had to start adding tolerations to preserve existing assignment 

I think tolerations are added to DS pod when we started using taints & tolerations in 1.6. PR - https://github.com/kubernetes/kubernetes/pull/41896, after that, we wanted to have backward compatibility when scheduler started scheduling DS pods, so we had to continue this. But even back in 1.6 the rationale behind DS pods adding those tolerations is same as now. We could have added a NoExecute` toleration to DS pod instead of adding it in the codepath.

Regarding `system-node-critical` priorityClass, I am fine with it having explicit toleration but I believe, it doesn't guarantee continuous running of pod with tolerations in pod spec which conflicts with its design, unless I understood it wrong.

**Comment by bsalamat** [comment]
+1 to @liggitt's [points](https://github.com/kubernetes/kubernetes/issues/71234#issuecomment-441384973).
Priority and toleration are two separate things and one should not imply the other. A high-priority pod should not have automatic toleration for NoExecute taint. An obvious example is the case that one runs a small number of critical pods in a cluster. She wants these pods to preempt others when the cluster is full, but she also wants them to run on healthy nodes and be responsive. An automatic "NoExecute" toleration would remove the possibility of having them run on healthy nodes.

The case of DS controller applying toleration is a bit different. DaemonSet pods generally have association with nodes where they run. They run on "all nodes" of the cluster or they run on a subset of nodes specified by a node selector. In the latter case, they run on "all nodes" with particular labels. So, it makes sense for them to "stick" to their corresponding nodes and not go any where else. That's why we have toleration for DS pods.
The same concept does not apply to other non-DS pods.

**Comment by ravisantoshgudimetla** [comment]
Thanks for explanation @liggitt @k82cn @bsalamat. As I told earlier, I am fine with `system-node-critical` pod having explicit `NoExecute` taint but we need to document that `system-node-critical` could be evicted but not preempted. I will created a docs PR for it.

Thanks @Huang-Wei for creating the issue. I will close this now.

/close
