### ISSUE TITLE
Customized Pod ipPool failed to work

### ISSUE THREAD

**Issue by leoowu** [kubernetes/kubernetes#71249]
**What happened**:
I create my k8s cluster with kubeadm command "kubeadm init --pod-network-cidr=10.51.0.0/16 --kubernetes-version=v1.12.2 --apiserver-advertise-address=192.168.190.102 --service-cidr=10.96.0.0/16  --token-ttl=0  -v=9 ", and the 'CALICO_IPV4POOL_CIDR' from Calico was '10.51.0.0/16'

![image](https://user-images.githubusercontent.com/6262327/48754956-9874a700-ecce-11e8-9996-02eb83133ff3.png)
![image](https://user-images.githubusercontent.com/6262327/48754985-b4784880-ecce-11e8-960e-d1314d32c59a.png)

but  the customized Pod ipPool failed to work, still the default value "192.168.0.0/16"
![image](https://user-images.githubusercontent.com/6262327/48755007-c6f28200-ecce-11e8-93a0-aa440c148d06.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1) kubeadm init --pod-network-cidr=10.51.0.0/16 --kubernetes-version=v1.12.2 --apiserver-advertise-address=192.168.190.102 --service-cidr=10.96.0.0/16  --token-ttl=0  -v=9
2) kubectl apply -f  \
https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/rbac.yaml
 kubectl apply -f \
https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/etcd.yaml
wget https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/calico.yaml
change the 'CALICO_IPV4POOL_CIDR' value from 192.168.0.0/16 to your customized ipPool
kubectl apply -f calico.yaml

and then u can create a new POD or just check the ipPool value via calicoctl like bellow:
ETCD_ENDPOINTS=http://localhost:6666 calicoctl get ipPool -o wide
 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
vm
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux master01 4.17.2-1.el7.elrepo.x86_64 #1 SMP Sat Jun 16 11:18:11 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm v1.12.2
- Others:

/kind bug

**Comment by neolit123** [comment]
`--pod-network-cidr=10.51.0.0/16`
this can be problematic if something on the host has already taken address in the same CIDR.

please try the WeaveNet CNI plugin instead from here:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

this same page has:
>Also, beware, that your Pod network must not overlap with any of the host networks as this can cause issues. If you find a collision between your network plugin’s preferred Pod network and some of your host networks, you should think of a suitable CIDR replacement and use that during kubeadm init with --pod-network-cidr and as a replacement in your network plugin’s YAML.

if it works with WaeveNet, then you can either report the problem to Calico or close the issue if you get it working with a good CIDR.

/priority awaiting-more-evidence
