### ISSUE TITLE
[failing test] upgrade/downgrade tests failing with GKE errors

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#71268]
**Which jobs are failing**:
In [sig-release-1.13-all](https://k8s-testgrid.appspot.com/sig-release-1.13-all):
- [gke-cos-1.13-default](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-cos-1.13-default)
- [gke-cos-1.13-reboot](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-cos-1.13-reboot)
- [gke-cos-1.13-serial](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-cos-1.13-serial)
- [gke-cos-1.13-slow](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-cos-1.13-slow)
- [gke-cos-1.13-ingress](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-cos-1.13-ingress)
- [gke-1.13-1.12-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-1.13-1.12-downgrade-cluster)
- [gke-1.13-1.12-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-1.13-1.12-downgrade-cluster-parallel)
- [gke-1.13-1.12-gci-kubectl-skew](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-1.13-1.12-gci-kubectl-skew)
- [gke-1.13-1.12-gci-kubectl-skew-serial](https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-1.13-1.12-gci-kubectl-skew-serial)

**Which test(s) are failing**:
`Up` is timing out; [run 4422](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-beta-stable1-downgrade-cluster-parallel/4422) is the first failure.

**Since when has it been failing**:
2018-11-19

**Reason for failure**:
This could be a gcp networking flake / problem:
```
W1120 04:14:50.686] ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
``` 

**Related**
[Issue #70133](https://github.com/kubernetes/kubernetes/issues/70133)

/kind failing-test

**Comment by mariantalla** [comment]
Assigning `critical-urgent` priority as this can blur CI signal and we're very close to the release date.

/priority critical-urgent

**Comment by jberkus** [comment]
Adding a sig, and dropping the priority level because GKE tests are non-blockers.

/sig gcp
/priority important-soon
/remove-priority critical-urgent

**Comment by mariantalla** [comment]
Some fresh failures (`connection refused`) started overnight:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-stable1-beta-upgrade-cluster-new/896
