### ISSUE TITLE
nf_conntrack: table full, dropping packet

### ISSUE THREAD

**Issue by annProg** [kubernetes/kubernetes#71261]
**What happened**:
- dmesg -T show lots of `nf_conntrack: table full, dropping packet`
```
[Tue Nov 20 22:30:22 2018] nf_conntrack: table full, dropping packet
[Tue Nov 20 22:30:27 2018] nf_conntrack: table full, dropping packet
[Tue Nov 20 22:30:27 2018] nf_conntrack: table full, dropping packet
[Tue Nov 20 22:30:27 2018] nf_conntrack: table full, dropping packet
```

This issue may break pod http health check,  pod will restart frequently. Such as `ingress-nginx-controller`， will be unavailable， all request will failed.

**What you expected to happen**:
no errors in dmesg 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I  tune `net.netfilter.nf_conntrack_max`  to `1048576` , then problem fixed. 
So , I think kube-proxy may should increase the value
```
I1120 15:18:19.757786   26448 conntrack.go:52] Setting nf_conntrack_max to 786432
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.2
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): CentOS 7.2
- Kernel (e.g. `uname -a`): 3.10
- Install tools: binary
- Others:

/kind bug

**Comment by annProg** [comment]
@kubernetes/sig-network-bugs

**Comment by m1093782566** [comment]
@annProg 

I assume you can tune this parameter via `--conntrack-max-per-core`, xref: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L164

Given the default value `786432` in your case, I assume your host has 24 CPU cores? Default value of max-contrack-per-core is 32*1024.

**Comment by annProg** [comment]
> @annProg
> 
> I assume you can tune this parameter via `--conntrack-max-per-core`, xref: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L164
> 
> Given the default value `786432` in your case, I assume your host has 24 CPU cores? Default value of max-contrack-per-core is `32*1024`.

Thanks! I will tune the parameter

**Comment by Lion-Wei** [comment]
@annProg And if you are using config file, `--conntrack-max-per-core` flag will not work, you need add the following param in your config file. : )
```yaml
conntrack:
  maxPerCore: 60000
```

**Comment by annProg** [comment]
@Lion-Wei Thanks! it works

**Comment by annProg** [comment]
For ingress-nginx node with lvs vip, the most thorough solution might be to set notrack for lvs vip.

run the script on `ingress-nginx` node
```bash
#!/bin/bash
vip=`ip addr show lo |grep "/32" |awk '{print $2}' |cut -f1 -d'/'`
 
[ "$vip"x == ""x ] && echo "no vip" && exit 1
 
iptables -vnL -t raw |grep "$vip" |grep "dpt:443" &>/dev/null || iptables -t raw -A PREROUTING -d $vip -p tcp --dport 443 -j NOTRACK
iptables -vnL -t raw |grep "$vip" |grep "dpt:80" &>/dev/null || iptables -t raw -A PREROUTING -d $vip -p tcp --dport 80 -j NOTRACK
iptables -vnL -t raw |grep "$vip" |grep "spt:443" &>/dev/null || iptables -t raw -A OUTPUT -s $vip -p tcp --sport 443 -j NOTRACK
iptables -vnL -t raw |grep "$vip" |grep "spt:80" &>/dev/null || iptables -t raw -A OUTPUT -s $vip -p tcp --sport 80 -j NOTRACK
 
iptables -vnL -t raw |grep $vip
```

after notrack:

<img width="334" alt="nf_conntrack" src="https://user-images.githubusercontent.com/4145852/48845893-a878ad80-edd8-11e8-89ab-915f9419299a.png">
