### ISSUE TITLE
Update 1.10 to 1.11  kubelet node is forbidden to patch status

### ISSUE THREAD

**Issue by peradel** [kubernetes/kubernetes#71271]
Pod's are unable to communicate.

```Nov 20 14:12:30 test-node-09 kubelet-wrapper[1556]: W1120 14:12:30.493541    1556 status_manager.go:498] Failed to update status for pod "kube-apiserver-test-node-09_kube-system(944906ec-ecc6-11e8-ae4e-0cc47afc2098)": failed to patch status "[...omitted patch data ...]": pods "kube-apiserver-test-node-09" is forbidden: User "system:node:test-node-09" cannot patch pods/status in the namespace "kube-system"```

**What happened**: patch to pods/status is denied.

**What you expected to happen**: patch operation succeeds

**How to reproduce it (as minimally and precisely as possible)**: start updating kubelet 1.10 to 1.11.3 without using kubeadm. 

* Change hyperkube image from `k8s.gcr.io/hyperkube:v1.10.5` to  `k8s.gcr.io/hyperkube:v1.11.3`
* restart one node

**Anything else we need to know?**: The symptoms seem the same as in bug #52711 but we already use `--authorization-mode=Node,RBAC` successfully in the running cluster.

The logs of node-problemdetector on that node contained the following
 ```Error from server: Get https://test-node-09:10250/containerLogs/kube-system/node-problem-detector-btfth/node-problem-detector: x509: certificate signed by unknown authority```

Connecting on that node with `openssl s_client -connect test-node-09:10250` will present  a certificate chain rooted in a self signed certificate generated on that node
 ```Certificate chain
 0 s:/CN=test-node-09@1542720938
   i:/CN=test-node-09-ca@1542720937
 1 s:/CN=test-node-09-ca@1542720937
   i:/CN=test-node-09-ca@1542720937```
This is different from the ca certificate set throughout  the rest of our cluster.

**Environment**:
- Kubernetes version (use `kubectl version`):1.10.5 (running)
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1855.5.0
- Kernel (e.g. `uname -a`): 4.14.74-coreos
- Install tools:
- Others: no kubeadm!

<!-- DO NOT EDIT BELOW THIS LINE -->
/kind bug

**Comment by liggitt** [comment]
That permission was added in https://github.com/liggitt/kubernetes/commit/9fe2c536249d7ec3010d71d6b610f35754e478b6#diff-eee450e334a11e0b683ce965f584c3c4, in 1.11+, and your apiserver is currently 1.10.5.

Upgrade your kube-apiserver to be at least as new as your kubelet. Running a kubelet newer than the apiserver is not supported.

/close

**Comment by cypherfox** [comment]
IMO it would be usefull to have this information placed in the Changelog (of referenced from there). The only upgrade manual we could find was using kubeadm, which we don't use.

Or is the use of kubeadm required for cluster operations?

**Comment by liggitt** [comment]
Kubeadm is definitely not required. Keeping the kubelet at a supported level relative to the apiserver is required. There is actually a documentation pull request in progress (https://github.com/kubernetes/website/pull/11060) to make the version requirements and upgrade order clearer.

**Comment by peradel** [comment]
Our Cluster is now running on version 1.11.4. But we still have the problem with the certificates as described above. The logs of any pod contain
`Error from server: Get https://test-node-09:10250/containerLogs/kube-system/kube-proxy-kptxm/kube-proxy: x509: certificate signed by unknown authority`
