### ISSUE TITLE
pkg/util/wait PollUntil() can leak goroutines

### ISSUE THREAD

**Issue by shomron** [kubernetes/kubernetes#71277]
Related to #14995, there remains a leak in `wait.PollUntil()` which does not ensure the channel it passes to `WaitFor` is closed. This causes goroutines to leak under common scenarios, such as when calling `cache.WaitForCacheSync()`.

/cc @ncdc 

**What happened**:
Each call to `wait.PollUntil` leaks an active goroutine (in this case spawned by `wait.poller()` via `wait.WaitFor()`. The goroutine will not end until the `stopCh` passed to `PollUntil` is closed - however this requirement can and should be handled internally. Often callers will pass a context with a longer lifespan.

**What you expected to happen**:
`wait.PollUntil` should ensure that the polling goroutine is ended after its condition is met. This can be accomplished by creating a new channel with a child cancellation relationship to the original, and passing that on instead. This child channel can be closed once `WaitFor` returns.

**How to reproduce it (as minimally and precisely as possible)**:
The minimal reproduction would be to call `wait.PollUntil` with a true condition, and not close the passed `stopCh`. However, a more complete reproduction involving a `ShareInformer` can be seen [here](https://github.com/shomron/poll-leak/blob/master/main.go).

**Anything else we need to know?**:
This leak was discovered in practice and caused a steady leak of memory and cpu in a project I work on.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Google GKE
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others: n/a

/kind bug

**Comment by ncdc** [comment]
fyi @liggitt @smarterclayton @deads2k @sttts 

Oren has 2 options to fix this. He'll be pasting sample code shortly and we can decide which approach we prefer.

**Comment by smarterclayton** [comment]
I would prefer using contexts - we actually should in the long term have context variants of all waits, so it’s the right direction to start using them more here

**Comment by dims** [comment]
+1 to option 1
