### ISSUE TITLE
Improve handling of some YAML-related issues in kubectl edit

### ISSUE THREAD

**Issue by jpetazzo** [kubernetes/kubernetes#71279]
**What would you like to be added**:

When editing a resource with `kubectl edit`, invalid changes *usually*
take the user back to the editor, with an explanation why their change
was rejected.

For instance, if I do:
- `kubectl edit service kubernetes`
- and add `hello` on the first line
- save and quit
... I'm taken back to the editor, with a helpful message: (broken down to multiple lines here for readability)
```yaml
# services "kubernetes" was not valid:
# * : Invalid value: "The edited file failed validation":
# [yaml: line 1: mapping values are not allowed in this context,
# [invalid character 'h'     looking for beginning of value,
# invalid character 'h' looking for beginning of value]]
```

However, if I do:
- `kubectl edit service kubernetes`
- add `version: 42` in the labels section
- save and quit
... I'm taken back to the shell, with a message saying:
```
error: services "kubernetes" could not be patched: cannot convert int64 to string
You can run `kubectl replace -f /tmp/kubectl-edit-j62k7.yaml` to try this update again.
```

This one could be improved by:
- taking me back to the editor
- and/or indicating (like for the previous error) the line at which the error happened

Furthermore, if I do:
- `kubectl edit service kubernetes`
- add `enabled: yes` in the labels section
- save and quit
... I'm taken back to the shell, with a message saying:
```
error: services "kubernetes" could not be patched: unrecognized type: string
```

(As you might guess, that one happens because YAML parsers interpret `yes` as a boolean value,
and boolean values aren't valid labels.)

This one could be improved by at least indicating (like for the int64 case) that this is related to boolean
interpretation.

**Why is this needed**:

To prevent head-scratching from people who are going to use any kind of yes/no label in selectors and labels.

Ideally, a consistent behavior (taking people back to the editor no matter what) would be fantastic,
but at least nudging them in the right direction would be a huge improvement!

**Related issues**

#42217 is similar. It dates from 1.6 but there was no particular follow-up. I don't know
if it's because it was deemed unimportant after all, or if it fell through the cracks.

/kind feature

**Comment by dims** [comment]
@jpetazzo i've reopened the issue you mentioned

**Comment by PhillipAmend** [comment]
@chaosaffe @ainmosni

I'm getting on this!
