### ISSUE TITLE
GetReference should require a meta.Interface

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#7127]
As part of this PR:

https://github.com/GoogleCloudPlatform/kubernetes/pull/7093

It was noted that GetReference should have more information injected in order to build a reference without a hard-coded scheme.

GetReference needs to be modified to allow downstream consumption that runs with alternate Scheme.  This impacts the ability to create Events around extended Kinds.

**Comment by bgrant0607** [comment]
Related: #1490

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
