### ISSUE TITLE
CoreDNS cache out-of-date results

### ISSUE THREAD

**Issue by wavezhang** [kubernetes/kubernetes#71308]
**What happened**:
Cluster DNS keep returning NXDOMAIN when svc/pod is recreated.

**What you expected to happen**:
Cluster DNS return cluster ip/pod id after svc/pod is running.

**How to reproduce it (as minimally and precisely as possible)**:
1. Keep on connect to svc/pod using domain
2. Recreate svc/pod or pod
3. You will see service keeps unavailable until cache timeout 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux test 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
 See [same Issue and solution on coredns](https://github.com/coredns/coredns/issues/2327)

/kind bug
/sig network

**Comment by chrisohaver** [comment]
This is due to caching, and works as designed.  The question was cross-posted to coredns/coredns#2327. 

A workaround was proposed/verified there and the issue closed.

**Comment by chrisohaver** [comment]
> So, will this solution merged into default coredns config for k8s?

IMO, we cannot, due to the complications of reverse lookups I described in coredns/coredns#2327.
To handle reverse lookups correctly in that solution, you'd need to know the Pod and Service CIDRs, which are not trivial to determine at install time (Pod CIDR specifically is difficult to determine).

**Comment by wavezhang** [comment]
can we get Pod CIDR ```kubeadm-config``` configmap?

**Comment by chrisohaver** [comment]
> can we get Pod CIDR kubeadm-config configmap?

No, it completely dependent on the network add on used.  It is available in the kubeadm configmap for flannel, but not all others.
