### ISSUE TITLE
[sig-auth] ServiceAccounts should mount an API token into pods failing in Alpha clusters

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#71329]
https://k8s-testgrid.appspot.com/sig-gcp-master#gci-gke-alpha-enabled-default

/sig auth
/kind failing-test

**Comment by jberkus** [comment]
Adding a priority to this:

/priority important-soon

Please raise the priority if you consider this a release blocker.  Given the test job, it normally wouldn't be.

**Comment by mikedanese** [comment]
It's a test issue. I'm hoping to fix this before 1.11 but I don't consider it a release blocker.
