### ISSUE TITLE
Deprecate old plugin watcher dir

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#71335]
**What happened**:
CSI https://github.com/kubernetes/kubernetes/pull/71314 re-introduced support for the deprecated volume plugin socket dir to allow for enough time for older plugins to be upgraded. But eventually, maybe in two releases (v1.15) we should deprecate the old directory.

CC @liggitt 

/sig storage

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
added to 1.13 release notes as deprecated and targeting removal in 1.15
