### ISSUE TITLE
kubectl logs failed with error: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by cxj110** [kubernetes/kubernetes#71343]
**What happened**:
```sh
[root@master kubernetes]# kubectl logs -f user-mgmt-n5hl8
Error from server: Get https://172.16.36.238:10250/containerLogs/default/user-mgmt-n5hl8/user-mgmt?follow=true: net/http: TLS handshake timeout
[root@master kubernetes]# 
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use the kubeadm to build a single master cluster, then launch some pods.

then try to print the logs from the minion node with "kubectl logs -f".

**Anything else we need to know?**:
it seems that the the kubectl logs is using IP address rather than hostname to do the request, but the TSL certificate seems only for hostname.
In my remember, the "kubectl logs" should to use the hostname rather than IP address right?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.2
- Cloud provider or hardware configuration: Huawei Cloud.
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core) 
- Kernel (e.g. `uname -a`): Linux master 4.19.2-1.el7.elrepo.x86_64 #1 SMP Tue Nov 13 16:18:09 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm
- Others:

/kind bug
@kubernetes/sig-Node-bugs, @kubernetes/sig-Network-bugs

**Comment by liggitt** [comment]
a cert mismatch would not timeout the TLS handshake, it would fail with an error about invalid SANs. does the apiserver have network visibility to the node?

/area kubeadm
/remove-sig cli
/sig cluster-lifecycle

**Comment by liggitt** [comment]
> other cmds can be executed normally, such as: "kubectl get nodes, kubectl create -f xxx.yaml, kubectl delete pod xxxx, kubectl delete service xxxx".

none of those commands require the apiserver to contact the kubelet, only kubectl logs does (and kubectl exec/attach/portforward, etc)

**Comment by neolit123** [comment]
@cxj110 
have you applied the rest of the steps like copying your KUBECONFIG file and installing a pod network plugin after kubeadm init finishes?

also does this work:
`kubectl get nodes`
?

if yes to both, please share you kubeadm configuration file or the command line you use to start kubeadm init.

**Comment by cxj110** [comment]
@neolit123 
kubectl get nodes is good. Only kubectl logs ... failed.

I will try to upgrade to the latest version and check again, close this issue timebing.

thank you for your help.

**Comment by amit4aws** [comment]
@cxj110  were you ever able to resolve the issue?. Any idea why I am seeing this issue?

**Comment by rijabiken-edge** [comment]
To resolve this issue, you can allow access from all IPs from port 10250 in your security group (firewall) config. Not sure why this fixes it as this port is supposedly only been used by the "KUBELET API" but yeah, it fixes it

**Comment by rijabiken** [comment]
To resolve this issue, you can allow access from all IPs from port 10250 in your security group (firewall) config. Not sure why this fixes it as this port is supposedly only been used by the "KUBELET API" but yeah, it fixes it
