### ISSUE TITLE
Use default spec.configSource on Node register when DynamicKubeletConfig activated

### ISSUE THREAD

**Issue by MrD2** [kubernetes/kubernetes#71359]
Starting from Kubernetes 1.11 DynamicKubeletConfig is activated by default, so this should always be present.

**What happened**:
When setting up a dynamic kubelet configuration the user is required to manually edit the node configurations (using kubectl edit node NODE_#) so that the node knows where to get it's corresponding kubelet configuration ConfigMap. 
For the kubelet to actively seek for a dynamic configuration the parameter '--dynamic-config-dir' has to be passed on the respective kubelet service creation arguments. Note that if this arguments are not passed the kubelet ends up by settling with the local/default configurations setup defined by arguments and/or configFile.

This parameter on the kubelet should be enough to activate or not the dynamic kubelet setup.

**What you expected to happen**:
The Master should attach default values on the spec.configSource parameters when responding to a Node Register request (when DynamicKubeletConfig activated - kubernetes > 1.11). This way the only operation needed to be done on the master is to create/replace the degault ConfigMap.

This can be done because the minion kubelet uses last known working configuration if the kubelet ConfigMap is not found or the key is wrong, as well as this ConfigMap is only searched if the kubelet has the corresponding argument

**How to reproduce it (as minimally and precisely as possible)**:
* Minion Nodes operations
Replace kubelet_configuration
```bash
### This is the kubelet definition
# kubernetes kubelet (minion) config
# The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS="--address=0.0.0.0"
# The port for the info server to serve on
# KUBELET_PORT="--port=10250"
# You may leave this blank to use the actual hostname
KUBELET_HOSTNAME=""
# Edit the kubelet.kubeconfig to have correct cluster server address
KUBELET_KUBECONFIG=/etc/kubernetes/kubelet.kubeconfig
# Add your own!
KUBELET_ARGS="$(/etc/kubernetes/get_require_kubeconfig.sh)  --kubeconfig /etc/kubernetes/kubelet-config.yaml --hostname-override=kube-fycutlofs4bl-minion-0 --dynamic-config-dir=/var/lib/kubelet/dynamic  --cloud-provider=openstack --cloud-config=/etc/kubernetes/kube_openstack_config --pod-infra-container-image=gcr.io/google_containers/pause:3.0 --client-ca-file=/etc/kubernetes/certs/ca.crt --tls-cert-file=/etc/kubernetes/certs/kubelet.crt --tls-private-key-file=/etc/kubernetes/certs/kubelet.key"
```
* kubelet-config has the minimal/default kubelet configuration parameters. In this case it only knows how to contact the kube-api service and validate both the service and itself
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/certs/ca.crt
    server: https://10.0.0.6:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:kube-fycutlofs4bl-minion-0
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: system:node:kube-fycutlofs4bl-minion-0
  user:
    as-user-extra: {}
    client-certificate: /etc/kubernetes/certs/kubelet.crt
    client-key: /etc/kubernetes/certs/kubelet.key
```
* Master operation (for replacing default ConfigMap or if it does not exist)
Create the kubelet dynamic configuration ConfigMap
```bash
KUBELET_CONFIG_CONFIGMAP="${KUBE_MANIFESTS_PATH}/kubelet_config_configmap.yaml"
cat > ${KUBELET_CONFIG_CONFIGMAP} <<EOF
kind: ConfigMap
apiVersion: v1
data:
  kubelet: |
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    address: ${KUBE_NODE_IP}
    cgroupsPerQOS: true
    cgroupDriver: ${CGROUP_DRIVER}
    readOnlyPort: 0
    authentication:
      x509:
        clientCAFile: ${CERT_DIR}/ca.crt
      webhook:
        enabled: true
      anonymous:
        enabled: false
    authorization:
      mode: Webhook
    tlsCertFile: ${CERT_DIR}/kubelet.crt
    tlsPrivateKeyFile: ${CERT_DIR}/kubelet.key
    clusterDomain: ${DNS_CLUSTER_DOMAIN}
    clusterDNS:
      - ${DNS_SERVICE_IP}
    featureGates:
      CSIPersistentVolume: true
      MountPropagation: true
metadata:
  name: kubelet
  namespace: kube-system
EOF
```
* Restart the minion services:
```bash
systemctl restart kubelet.service && journalctl -f -u kubelet.service
```

By now, the dynamic configuration should work, but it does not. To trigger the minions to update we have to manually patch each node with the spec.configSource object. For example using:
```bash
kubectl -n kube-system patch node NODE_# -p '{"spec":{"configSource":{"configMap":{"name":"kubelet","namespace": "kube-system","kubeletConfigKey":"kubelet"}}}}'
```

**Anything else we need to know?**:

**Environment**:
`
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: OpenStack
- OS (e.g. from /etc/os-release): Fedora 27 (Atomic Host)
- Kernel (e.g. `uname -a`): Linux kube-fork-2puyljuevin5-master-0.novalocal 4.14.18-300.fc27.x86_64 #1 SMP Thu Feb 8 01:35:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Automated (Openstack-Magnum)
- Others:

/kind bug
/sig node
/sig openstack
/sig cluster-ops

**Comment by liggitt** [comment]
> To trigger the minions to update we have to manually patch each node with the spec.configSource object.

That is working as intended. Opting nodes into a particular configuration should be an explicit action. The apiserver should not assume dynamic node configuration is homogenous across all nodes.

/close

**Comment by MrD2** [comment]
Ok, it is working as intended, but i think it has a missing feature.
/kind feature

When i open this ticket i was expecting more of a discussion. Your right, it can be done automatically external to the apiserver and kubelet processes but i feel it is a bit sloppy.

But if we wanted a starting point to use homogeneous dynamic configuration we could just flag it when calling kube-api process, so when the node registers it sends the configSource object. For this homogeneous configuration the setup would be much less complex. finner grained configurations could be made using tags that would be reported by the node itself

/open
