### ISSUE TITLE
How to add env variables and current working directory for pod exec 

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [kubernetes/kubernetes#71350]
Docker provides for exec api ability to set up current working directory and environment variables. It would be nice to have such features in the Kubernetes api too: https://docs.docker.com/engine/api/v1.37/#tag/Exec

**What would you like to be added**:
Add for Pod exec api parameters: current working directory (WorkingDir) and environment variables (Env).

**Why is this needed**:
It  is very  useful for reuse the same command to different places (and containers), automate exec commands, and set up working directory for terminal. There are a lot of cases when useful predefine env variables for command, to override some default value inside container or define some value, but don't apply it inside container with help config map.

**Comment by WanLinghao** [comment]
I think you can achieve what you want via:
https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/apis/core/types.go#L1952
https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/apis/core/types.go#L1964

**Comment by AndrienkoAleksandr** [comment]
@WanLinghao I want to have ability from client application which uses Kubernetes go-client launch exec with predefined env variables and current working dir. How `kubernetes/pkg/apis/core/types.go` could help in this case?

**Comment by ehashman** [comment]
@AndrienkoAleksandr a solution was provided in https://github.com/kubernetes/kubernetes/issues/71350#issuecomment-441920054

Specifically, you can set the `workingDir` and `env` parameters in your container specification: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#container-v1-core https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

You can ask for additional help on our [forums](https://discuss.kubernetes.io/).

/kind support
/remove-kind feature
/close
