### ISSUE TITLE
Is there any way to keep job pods for some time when backofflimit reached

### ISSUE THREAD

**Issue by bitzhuxb** [kubernetes/kubernetes#71364]
@kubernetes/sig-cluster-lifecycle-feature-requests

When backofflimit is reached, the job will delete the related pod. If the pod is deleted, we can't use the follow commands to see details:
`kubectl logs podname
`
`kubectl get pod podname -o yaml
`

The following is the events of the backofflimit jobs:
`  Normal   SuccessfulCreate      16h                job-controller  Created pod: tj-13644-zhutest0030-1122172613-tqlw9`
  `Normal   SuccessfulDelete      16h                job-controller  Deleted pod: tj-13644-zhutest0030-1122172613-tqlw9`
  `Warning  BackoffLimitExceeded  16h (x2 over 16h)  job-controller  Job has reached the specified backoff limit`

**Comment by cwdsuzhou** [comment]
Maybe, you can configure the `grace-period` of pod.

**Comment by bitzhuxb** [comment]
> Maybe, you can configure the `grace-period` of pod.

By setting the restartpolicy to 'Never' fixed my problem. Thanks anyway
