### ISSUE TITLE
can't visit by this dns format  like "http://servicename.namespace:port"

### ISSUE THREAD

**Issue by DevilMayCrySamsara** [kubernetes/kubernetes#71375]
**What happened**:
i hava a service,i can access by this dns like "http://servicename.namespace.svc:port",but i can't visit by this dns format  like "http://servicename.namespace:port",i don't know why
![image](https://user-images.githubusercontent.com/20835804/48936326-8cdee580-ef45-11e8-9314-2b4405a804aa.png)

**What you expected to happen**:

I can access it either way

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.11.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708
- Kernel (e.g. `uname -a`):3.10.0-693.2.2.el7.x86_64
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
it looks like the request is reaching the backing pod correctly (you are getting a http response), and the service is responding with an http error. is the backing pod configured to accept requests via both of those hostnames?

/sig network

**Comment by DevilMayCrySamsara** [comment]
This is due to a bug in my project  ,thanks，spring-boot-gradle-plugin ：2.0.3.RELEASE ,
There will be no problem when I upgrade the version to 2.0.4.release
