### ISSUE TITLE
CSI: registration process fails

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/kubernetes#71378]
**What happened**:

The CSI driver registrar container fails to start with the following message:

```
I1123 12:42:02.529686       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error uninstalling CSI driver from CSINodeInfo object error updating CSINodeInfo: timed out waiting for the condition; caused by: [csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found, csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found, csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found, csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found],}
E1123 12:42:02.529792       1 main.go:123] Registration process failed with error: plugin registration failed with err: error uninstalling CSI driver from CSINodeInfo object error updating CSINodeInfo: timed out waiting for the condition; caused by: [csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found, csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found, csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found, csinodeinfos.csi.storage.k8s.io "ip-172-18-0-74.ec2.internal" not found], restarting registration container.
```
The commit that introduced this issue seems to be aa8244beb50b66d4de0f18aad2867aa7091eaf30.

**What you expected to happen**:

The CSI driver registrar container should start correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Just deploy the registrar sidecar container.

/kind bug
/assign @saad-ali

**Comment by bertinatto** [comment]
I noticed that the error doesn't happen if I use the registrar image with label `v1.0-canary`. It only happens with `v1.0.0`.

Do we want to keep backward compatibility with the `v1.0.0` image?

**Comment by bertinatto** [comment]
CC @msau42

**Comment by liggitt** [comment]
the 1.0.0 image had a bug in it where it reported the wrong version. see https://github.com/kubernetes/kubernetes/pull/71314#discussion_r235583955

**Comment by saad-ali** [comment]
Yes, what @liggitt said. Please use 1.0.1 driver-registrar sidecar container. If you still have issues with that version please reopen this issue.
