### ISSUE TITLE
Kubelet trying to contact api server on localhost:8080

### ISSUE THREAD

**Issue by geosword** [kubernetes/kubernetes#71381]
**What happened**:
Pod which references a ceph Persistent volume claim, fails to start. It stays in "ContainerCreating" status

**What you expected to happen**:
The pod to become "Running" with the ceph storage attached in /mnt/rbd 

**How to reproduce it (as minimally and precisely as possible)**:
Run through:
http://docs.ceph.com/docs/mimic/start/kube-helm/
The smoke test near the end, creates a pod with ceph storage attached.

**Anything else we need to know?**:
I've found evidence the problem is with kubelet not ceph itself.
To put some more flesh on the bone. The pod creation *succeeds* when the pods are scheduled to run on either of our two master servers. If its scheduled to run on a worker, this error is shown in the logs of the workers kubelet:
```
MountVolume.WaitForAttach failed for volume : fail to check rbd image status with: (exit status 1), rbd output: The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
If I check listening ports on the masters, sure enough, localhost:8080 is listening. (I've now prevented that from happening with the apiserver parameter --insecure-port=0, and now predictably, its doesnt matter where the pod is scheduled, the above error results.

After getting the api listening on localhost:8080 again (in addition to its usual 443), for a bit of hacky work around, I decided to try setting up an ssh tunnel between a worker and a master, so that the worker would indeed have the api available over localhost:8080. After scheduling the pod on that worker, the result was still a non running pod, but with a slightly different error:

```
2018-11-23 14:43:57.651747500 E1123 14:43:57.651702   12892 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/rbd/rbd:kubernetes-dynamic-pvc-c904f171-ee4e-11e8-b069-0a58ac100419\"" failed. No retries permitted until 2018-11-23 14:45:59.651656311 +0000 GMT m=+5164.902266188 (durationBeforeRetry 2m2s). Error: "MountVolume.WaitForAttach failed for volume \"pvc-c8e57354-ee4e-11e8-bda3-caef73f3b003\" (UniqueName: \"kubernetes.io/rbd/rbd:kubernetes-dynamic-pvc-c904f171-ee4e-11e8-b069-0a58ac100419\") pod \"pvcpodtest\" (UID: \"5a44c761-ef2c-11e8-b6f6-caef73f3b003\") : fail to check rbd image status with: (exit status 1), rbd output: (Unable to connect to the server: EOF\n)"
```
BTW I did first verify the tunnel was working, by hitting http://localhost:8080 on the worker with curl.

Whilst it hasn't fixed the problem (the pod remains in ContainerCreating status) it has affected the outcome, which is what makes me think the kubelet is at fault, and not ceph. I have a issue logged with ceph too: https://github.com/helm/charts/issues/9509 , mainly because grepping the kubelet logs shows that kubelet only tries to connect to localhost:8080 when a ceph volume is involved in the pod.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare metal
- OS (e.g. from /etc/os-release):
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux bddcbpkbn6 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
```
- Install tools:
```
None. Guided by https://github.com/kelseyhightower/kubernetes-the-hard-way
```
- Others:

/kind bug

**Comment by liggitt** [comment]
@kubernetes/sig-storage-bugs how does ceph know how to contact the apiserver?

**Comment by mlmhl** [comment]
@geosword How do you make sure this `http://localhost:8080` is the address of apiserver? This information is printed by `rbd` command, so I think this `http://localhost:8080` is the address of ceph mon. You should check your PV object.

**Comment by geosword** [comment]
@liggitt. A good point, The process detailed at http://docs.ceph.com/docs/mimic/start/kube-helm/ does not mention supplying an api address to ceph, which tells me it doesn't need to know, presumably because it assumes the "kubernetes" service is present and working.

I dont have a response from "Ceph" yet regarding the issue I logged there. Hopefully I will get something later today.

@mlmhl. 

>How do you make sure this http://localhost:8080 is the address of apiserver?

In the case of a worker node, I set up an SSH tunnel to localhost:8080 on the (a) master.
In the case of the master nodes, --insecure-bind-address / --insecure-port are set to localhost:8080 by default.

>This information is printed by rbd command 

I'd be interested in seeing what the full command is. 

> http://localhost:8080 is the address of ceph mon. You should check your PV object.

I can see nothing in http://docs.ceph.com/docs/mimic/rados/configuration/network-config-ref/ suggesting ceph listens on port 8080.

"By default, daemons bind to ports within the 6800:7300 range. You may configure this range at your discretion. Before configuring your IP tables, check the default iptables configuration."

**Comment by geosword** [comment]
I figured it out. I had to upgrade my ceph-common tool set. It works on all nodes, and without the api listening on localhost:8080
