### ISSUE TITLE
Failing Test: ci-kubernetes-soak-gci-gce-beta fails to load

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71401]
**Which jobs are failing**: ci-kubernetes-soak-gci-gce-beta

**Which test(s) are failing**: all of them, the test fails to start

**Since when has it been failing**: Nov. 21

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-1.13-all#soak-gci-gce-1.13

**Reason for failure**:

The test is apparently failing to even start:

```
failed loading kubeconfig: error during gsutil cp gs://kubernetes-e2e-soak-configs/ci-kubernetes-soak-gci-gce-beta/kube-config /workspace/.kube/config: exit status 1
```

**Anything else we need to know**:

There's two unresolved test-fail issues on that job currently being worked on, so we need that job running to see if they're fixed for release.

/kind failing-test
/sig testing
/priority critical-urgent

attn:
@amwat @RahulMahale @AishSundar 

/assign @cjwagner

**Comment by AishSundar** [comment]
@krzyzacy is there anything more we need to do here to restart the soak job?

**Comment by krzyzacy** [comment]
@AishSundar the latest run (https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/498) is currently running, let's wait for that to finish.

**Comment by krzyzacy** [comment]
/shrug

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/488 took 19h50m to finish... timeout is 20h... let's give the job a bit more room...

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/500 finished (finally!)

/close
