### ISSUE TITLE
Master-upgrade tests experiencing gce flakes

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#71418]
**Which jobs are failing**:
- [gce-master-new-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster)

**Which test(s) are failing**:

| Job | Test | Reason for failure |
| - | - | - |
| [gce-master-new-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster) | [[sig-apps] replicaset-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1107#cluster-downgrade-sig-apps-replicaset-upgrade) | `dial tcp 35.184.185.29:443: connect: connection refused`
| [gce-master-new-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster) | [[sig-cluster-lifecycle] Downgrade [Feature:Downgrade] cluster downgrade should maintain a functioning cluster [Feature:ClusterDowngrade]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1107#sig-cluster-lifecycle-downgrade-featuredowngrade-cluster-downgrade-should-maintain-a-functioning-cluster-featureclusterdowngrade) | `dial tcp 35.184.185.29:443: connect: connection refused`
| [gce-master-new-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster) | [hpa-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1107#cluster-downgrade-hpa-upgrade) | `TLS handshake timeout`

**Since when has it been failing**:
2018-11-25

**Anything else we need to know**:
Related: [#71268](https://github.com/kubernetes/kubernetes/issues/71268)

/kind flake
/sig gcp

**Comment by mariantalla** [comment]
Assigning `important-soon` until we get a couple more runs and see how persistent the issue is.
Might move to `important-longterm` if it's a one-off.
This is a non-release-blocking suite.

/priority important-soon

**Comment by jberkus** [comment]
Tracking in milestone.  These tests are release-informing, if not release-blocking, and if they all flake at once it's going to lag the release.

/milestone v1.13
