### ISSUE TITLE
Volume detach while mount e2e is flaking

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#71425]
The newly introduced e2e which checks for detach while mount is in progress is flaking:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/32313

/sig storage
/assign

**Comment by nikopen** [comment]
tracked under https://github.com/kubernetes/kubernetes/issues/71426 

/close
