### ISSUE TITLE
Failing Test: [sig-storage] Detaching volumes should not work when mount is in progress

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71426]
**Which jobs are failing**: gce-cos-master-default, several others

**Which test(s) are failing**: Failing Test: [sig-storage] Detaching volumes should not work when mount is in progress

**Since when has it been failing**: 11/23

**Testgrid link**:  https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default

**Reason for failure**:

See Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Detaching%20volumes%20should%20not%20work%20when%20mount%20is%20in%20progress

This test started failing the cos-master-default test this morning.  However, according to Triage it's been fialing across our e2e test suite in various places since 11/23.  There's two kinds of failures, a timeout, and a "filesystem should be read-only". 

**Anything else we need to know**:

This is a blocker for release.

/kind failing-test
/sig storage
/priority critical-urgent
/milestone v1.13

attn:
@saad-ali 
@childsb 
@AishSundar

**Comment by gnufied** [comment]
Looking into it.

**Comment by AishSundar** [comment]
/reopen

Reopening until we can get some clean CI signal.

FWIW spoke to @saad-ali to confirm this is a pure test setup issue and there is a possibility that this might not be fixed fully.

**Comment by saad-ali** [comment]
This test looks like it's been green since the fix merged.

**Comment by AishSundar** [comment]
@jberkus are you ok closing this as per recent runs?
