### ISSUE TITLE
Pod garbage collector threshold behavior

### ISSUE THREAD

**Issue by libesz** [kubernetes/kubernetes#71421]
**What happened**: After taken into use the `--terminated-pod-gc-threshold` parameter of controller-manager, there are still terminated Pods left in the system.

**What you expected to happen**: I would expect the garbage collector to clean up all the terminated Pods when their amount exceeds the threshold.

**How to reproduce it (as minimally and precisely as possible)**: Set the `--terminated-pod-gc-threshold` to a small value (i.e. 1) to the controller-manager and create more terminated pods with a state according to [this check](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/controller/podgc/gc_controller.go#L102) to trigger Pod GC in the scheduler. When the GC successfully completes, the configured amount of Pods are left in the system. This means you cannot configure the controller to clean up completely.

**Anything else we need to know?**: According to the GC [code](https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/controller/podgc/gc_controller.go#L119), this might be intentional, though I cannot get the point. The current behavior seems to allow the terminated Pod amount fluctuate above and under the threshold, instead of clean up completely when threshold is met. Other GCs (`gcOrphaned`, `gcUnscheduledTerminating`) cleans up completely, though.
Related to #63483.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): RHEL 7.x
- Kernel (e.g. `uname -a`): 4.4
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
> According to the GC code, this might be intentional, though I cannot get the point. 

Once a terminated pod is cleaned up, its logs are no longer accessible. Setting this threshold allows the cluster administrator to decide how many pods to leave in place for post-termination log access.

**Comment by libesz** [comment]
I see. Thanks. We might indicate this behavior and the reason for that in the docs if the controller-manager.
