### ISSUE TITLE
Create/Update of custom resources returns wrong error code for bad requests, 500 instead of 4XX

### ISSUE THREAD

**Issue by sambdavidson** [kubernetes/kubernetes#71435]
**What happened**:
POST or PUT to a custom resource with a JSON body missing "kind" results in a 500 error:
```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Object 'Kind' is missing in 'object has no kind field '",
    "code": 500
}
```
A missing "apiVersion" also results in a 500 error:
```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Internal error occurred: Object 'apiVersion' is missing in 'object has no apiVersion field'",
    "reason": "InternalError",
    "details": {
        "causes": [
            {
                "message": "Object 'apiVersion' is missing in 'object has no apiVersion field'"
            }
        ]
    },
    "code": 500
}
```
Then with both "kind" and "apiVersion" defined we get the normal 4XX return codes.

**What you expected to happen**:
All bad inputs for create and update requests should be 4XX return codes.
E.g. Creating a `Role` with body of `{}` results in the 422 error:
```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Role.rbac.authorization.k8s.io \"\" is invalid: metadata.name: Required value: name or generateName is required",
    "reason": "Invalid",
    "details": {
        "group": "rbac.authorization.k8s.io",
        "kind": "Role",
        "causes": [
            {
                "reason": "FieldValueRequired",
                "message": "Required value: name or generateName is required",
                "field": "metadata.name"
            }
        ]
    },
    "code": 422
}
```

**How to reproduce it**:
Create a CRD or use a cluster that already has a one prepared (GKE 1.11.0+ clusters have the CRD `cloud.google.com/v1beta1` `backendconfigs` installed which you could test against). HTTP `POST` to that custom resource with a JSON body of `{}`.

E.g. 
```sh
curl -d '{}' -H "Content-Type: application/json" -X POST http://CLUSTER/apis/cloud.google.com/v1beta1/namespaces/default/backendconfigs
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

/sig api-machinery

/kind bug

**Comment by zhouhaibing089** [comment]
I guess it is raised athttps://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L148, which is checked in `rest.BeforeCreate`.

**Comment by nikhita** [comment]
> Kubernetes version (use kubectl version): 1.11.2

This is fixed on master, but I can reproduce it on 1.11.

Posting a custom resource with a JSON body of `{}`:

on master:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "CronTab in version \"v1\" cannot be handled as a CronTab: unmarshalerDecoder: Object 'Kind' is missing in '{}', error found in #2 byte of ...|{}|..., bigger context ...|{}|...",
  "reason": "BadRequest",
  "code": 400
}
```

on 1.11:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Object 'Kind' is missing in 'object has no kind field '",
  "code": 500
}
```

**Comment by yue9944882** [comment]
[https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/staging/src/k8s.io/apiextensions-apiserver/pkg/crdserverscheme/unstructured.go#L50](https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/staging/src/k8s.io/apiextensions-apiserver/pkg/crdserverscheme/unstructured.go#L50)

we are transforming all non-status error into 500 status error, a quick fix by #71500

**Comment by yue9944882** [comment]
@nikhita instead of fixed, it's rather been shadowed by #70087

[https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go#L80-L85](https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go#L80-L85)

**Comment by ubhide** [comment]
I get the same response when trying to update the custom resource's 'status' sub-resource. On k8s v1.11.4

**Comment by liggitt** [comment]
submitting the specified object on master returns a 400 badrequest, as desired

/close
