### ISSUE TITLE
vSphere conformance tests are flaky

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#71430]
**Which jobs are failing**:
- [sig-release-master-blocking#Conformance - vSphere-cloud-provider](https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20vSphere-cloud-provider) -- failed and not run since 2018-11-20
- [sig-release-master-blocking#Conformance - vSphere](https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20vSphere) -- failures over 2018-11-24/25

**Which test(s) are failing**:
In [Conformance - vSphere-cloud-provider](https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20vSphere-cloud-provider)
- [BeforeSuite](https://gubernator.k8s.io/build/k8s-conformance-cloud-provider-vsphere/head/ci/latest/1542736883#beforesuite)
```
dial tcp: lookup k8s.vmware.ci on 10.32.0.10:53: server misbehaving
```

In [Conformance - vSphere](https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20vSphere)
- [[sig-apps] ReplicationController should adopt matching pods on creation [Conformance]](https://gubernator.k8s.io/build/k8s-conformance-vsphere/head/ci/latest/1543191038#sig-apps-replicationcontroller-should-adopt-matching-pods-on-creation-conformance)
```
Expected error:
    <*errors.errorString | 0xc00009f870>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

- [[sig-storage] Subpath Atomic writer volumes should support subpaths with projected pod [Conformance]](https://gubernator.k8s.io/build/k8s-conformance-vsphere/head/ci/latest/1543104575#sig-storage-subpath-atomic-writer-volumes-should-support-subpaths-with-projected-pod-conformance) --> *latest run succeeded, will keep an eye on it*
```
Expected error:
    <*errors.errorString | 0xc000fb9990>: {
        s: "expected pod \"pod-subpath-test-projected-kr98\" success: Gave up after waiting 5m0s for pod \"pod-subpath-test-projected-kr98\" to be \"success or failure\"",
    }
    expected pod "pod-subpath-test-projected-kr98" success: Gave up after waiting 5m0s for pod "pod-subpath-test-projected-kr98" to be "success or failure"
not to have occurred
```

/kind failing-test
/sig vmware

**Comment by mariantalla** [comment]
Assigning `priority/important-soon` as conformance tests for specific providers are non-blocking.

/priority important-soon

**Comment by mariantalla** [comment]
`Conformance - vSphere` is now cleared out, but the `BeforeSuite` in `Conformance - vSphere-cloud-provider` has still not run since [run 1542736883](https://gubernator.k8s.io/build/k8s-conformance-cloud-provider-vsphere/head/ci/latest/1542736883).

**Comment by dims** [comment]
@mariantalla is this still a problem? please close it if this is not needed

**Comment by mariantalla** [comment]
It seems this specific issue isn't 🤔 vsphere conformance tests are still failing/flaking in master-informing (they've moved there since this issue was opened), but with different errors.Example runs:
* [Conformance - vSphere-cloud-provider](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cloud-provider-vsphere-conformance-latest/1118002720343592960)
* [Conformance - vSphere](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-vsphere-conformance-latest/1118365459343740932)

Closing this one.
/close
