### ISSUE TITLE
XFS volumes should be mountable failing in COS tests [Should not be running at all]

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#71436]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-cos2-k8sbeta-default
 ci-kubernetes-e2e-gke-cos1-k8sbeta-default 

**Which test(s) are failing**:
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (xfs)] volumes should be mountable

**Since when has it been failing**:
Forever

**Testgrid link**:
https://testgrid.k8s.io/cos-cos2-k8sbeta#gce-cos2-k8sbeta-default

**Reason for failure**:
Test should be skipped on COS images
We have some skipping logic but it seems to not be triggered properly

/kind failing-test
/sig storage

**Comment by jberkus** [comment]
Is this a separate issue from the known storage tests issues?

**Comment by davidz627** [comment]
/remove-lifecycle stale
tests are still failing

**Comment by tpepper** [comment]
#78459 only landed in master for 1.16.  To see if this fixes things more we'd need to cherry pick it back to 1.15 at least since that is now "k8sbeta".  Across the life of this issue "k8sbeta" was  earlier releases, places to which the patch has also not been cherry picked.

**Comment by davidz627** [comment]
dashboard no longer exists. I think all newer versions of kubernetes have the fix
/close
