### ISSUE TITLE
XFS volumes should be mountable tests failing on Ubuntu

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#71437]
Example failure: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-ubuntu2-k8sbeta-default/3021#sig-storage-in-tree-volumes-driver-gcepd-testpattern-pre-provisioned-pv-xfs-volumes-should-be-mountable

**Which jobs are failing**:
ci-kubernetes-e2e-gke-ubuntu2-k8sbeta-default 
ci-kubernetes-e2e-gke-ubuntu1-k8sbeta-default

**Which test(s) are failing**:
 [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (xfs)] volumes should be mountable

**Since when has it been failing**:
Flaking for a while

**Testgrid link**:
https://testgrid.k8s.io/canonical-ubuntu2-k8sbeta#gke-ubuntu2-k8sbeta-default

**Reason for failure**:
UNKNOWN

**Anything else we need to know**:

/kind failing-test
/sig storage
/assign

**Comment by davidz627** [comment]
these tests are no longer running in Ubuntu by design

**Comment by davidz627** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/74095

**Comment by chardch** [comment]
Hey @davidz627 It looks like these tests are being run in Ubuntu still. https://testgrid.k8s.io/canonical-ubuntu2-k8sstable1#gce-ubuntu2-k8sstable1-serial

To confirm, these xfs tests shouldn't be running for Ubuntu?

**Comment by davidz627** [comment]
XFS tests *should* be running on Ubuntu. I don't remember the history of this Issue but I think it was probably referring to something different
