### ISSUE TITLE
CSI plugin registration can be slow

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71433]
**What happened**:
From https://github.com/kubernetes/kubernetes/issues/71383#issuecomment-441796126, it took around a minute for the CSI plugin to register. It would be good to understand why it took so long and if it's normal/expected.

> Timeline of events:
> 
> Test pod started getting processed by kubelet:
> ```
> I1126 15:27:34.537403    1446 config.go:414] Receiving a new pod "pod-subpath-test-csi-hostpath-dynamicpv-mgnk_e2e-tests-csi-volumes-92vsl(cc5409be-f18f-11e8-9a1b-42010a800002)"
> ```
> 
> It took a minute after the test pod was created for the csi driver to finish registering and mount to succeed, and then subpath event to trigger:
> ```
> I1126 15:28:32.392198    1446 csi_plugin.go:116] kubernetes.io/csi: Trying to validate a new CSI Driver with name: csi-hostpath-e2e-tests-csi-volumes-92vsl endpoint: /var/lib/kubelet/plugins/csi-hostpath-e2e-tests-csi-volumes-92vsl/csi.sock versions: 1.0.0, foundInDeprecatedDir: false
> I1126 15:28:32.392254    1446 csi_plugin.go:137] kubernetes.io/csi: Register new plugin with name: csi-hostpath-e2e-tests-csi-volumes-92vsl at endpoint: /var/lib/kubelet/plugins/csi-hostpath-e2e-tests-csi-volumes-92vsl/csi.sock
> 
> I1126 15:28:32.433217    1446 operation_generator.go:567] MountVolume.SetUp succeeded for volume "pvc-c9e516f1-f18f-11e8-9a1b-42010a800002" (UniqueName: "kubernetes.io/csi/csi-hostpath-e2e-tests-csi-volumes-92vsl^cbfcc214-f18f-11e8-9505-42010a800005") pod "pod-subpath-test-csi-hostpath-dynamicpv-mgnk" (UID: "cc5409be-f18f-11e8-9a1b-42010a800002")
> I1126 15:28:32.465509    1446 volume_manager.go:383] All volumes are attached and mounted for pod "pod-subpath-test-csi-hostpath-dynamicpv-mgnk_e2e-tests-csi-volumes-92vsl(cc5409be-f18f-11e8-9a1b-42010a800002)"
> I1126 15:28:34.082064    1446 server.go:459] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-csi-volumes-92vsl", Name:"pod-subpath-test-csi-hostpath-dynamicpv-mgnk", UID:"cc5409be-f18f-11e8-9a1b-42010a800002", APIVersion:"v1", ResourceVersion:"47363", FieldPath:"spec.containers{test-container-subpath-csi-hostpath-dynamicpv-mgnk}"}): type: 'Warning' reason: 'Failed' Error: failed to prepare subPath for volumeMount "test-volume" of container "test-container-subpath-csi-hostpath-dynamicpv-mgnk"
> ```
> 
> So #71428 should address the issue.  I was initially confused because the test logs didn't show the subpath event for some reason

@kubernetes/sig-storage-bugs 

/kind bug

**Comment by AishSundar** [comment]
@msau42 @saad-ali is this a blocker for 1.13? do we have a baseline of how long its expected to take for the registration?

**Comment by saad-ali** [comment]
I took a look at this.

Looks like the external `driver-registrar` sidecar causes the delay (see [log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new-parallel/400/artifacts/_sig-storage_CSI_Volumes_Driver_csi-hostpath_Testpattern_Dynamic_PV_default_fs_subPath_should_fail_if_subpath_directory_is_outside_the_volume_Slow_/csi-hostpathplugin-xwdfw-driver-registrar.log)):

```
==== start of log for container csi-hostpathplugin-xwdfw/driver-registrar ====
I1126 15:27:32.384912       1 main.go:138] Version: v1.0.1-0-g78b5c12
I1126 15:27:32.385026       1 main.go:145] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1126 15:27:32.385041       1 connection.go:68] Connecting to /csi/csi.sock
I1126 15:27:32.386221       1 connection.go:95] Still trying, connection is CONNECTING
I1126 15:27:32.394550       1 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
I1126 15:27:33.386937       1 connection.go:95] Still trying, connection is CONNECTING
I1126 15:28:32.385355       1 connection.go:88] Connection timed out
I1126 15:28:32.385709       1 main.go:153] Calling CSI driver to discover driver name.
I1126 15:28:32.385753       1 connection.go:136] GRPC call: /csi.v1.Identity/GetPluginInfo
I1126 15:28:32.385766       1 connection.go:137] GRPC request: 
I1126 15:28:32.387729       1 connection.go:139] GRPC response: name:"csi-hostpath-e2e-tests-csi-volumes-92vsl" vendor_version:"v1.0.0-0-gdf8026fe" 
...
```

So, `driver-registrar` failed to connect to CSI driver, and took a minute to fail.

Here are the logs from the host path CSI driver side (see [link](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new-parallel/400/artifacts/_sig-storage_CSI_Volumes_Driver_csi-hostpath_Testpattern_Dynamic_PV_default_fs_subPath_should_fail_if_subpath_directory_is_outside_the_volume_Slow_/csi-hostpathplugin-xwdfw-hostpath.log)):

```
==== start of log for container csi-hostpathplugin-xwdfw/hostpath ====
I1126 15:27:32.956647       1 hostpath.go:102] Driver: csi-hostpath-e2e-tests-csi-volumes-92vsl 
I1126 15:27:32.956727       1 hostpath.go:103] Version: v1.0.0-0-gdf8026fe
I1126 15:27:32.956738       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I1126 15:27:32.956746       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I1126 15:27:32.956753       1 driver.go:81] Enabling controller service capability: LIST_SNAPSHOTS
I1126 15:27:32.956760       1 driver.go:93] Enabling volume access mode: SINGLE_NODE_WRITER
I1126 15:27:32.957106       1 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I1126 15:27:33.493049       1 utils.go:96] GRPC call: /csi.v1.Identity/Probe
I1126 15:27:33.493070       1 utils.go:97] GRPC request: 
I1126 15:27:33.493100       1 utils.go:102] GRPC response: 
I1126 15:27:33.494000       1 utils.go:96] GRPC call: /csi.v1.Identity/GetPluginInfo
I1126 15:27:33.494020       1 utils.go:97] GRPC request: 
I1126 15:27:33.494059       1 identityserver-default.go:32] Using default GetPluginInfo
I1126 15:27:33.494073       1 utils.go:102] GRPC response: name:"csi-hostpath-e2e-tests-csi-volumes-92vsl" vendor_version:"v1.0.0-0-gdf8026fe" 
....
```

So it looks like the `driver-registrar` tries to open a connection

```
I1126 15:27:32.385041       1 connection.go:68] Connecting to /csi/csi.sock
```

a split second before the CSI hostpath driver starts listening:

```
I1126 15:27:32.957106       1 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
```

And the `driver-registrar` takes a minute to fail/recover from that.

Based on this, the issue does not seem to be due to any code in `kubernetes/kubernetes`. And is not a blocker for 1.13.

I will open an issue on the driver-registrar to track if this delay can be reduced.

**Comment by saad-ali** [comment]
Opened https://github.com/kubernetes-csi/driver-registrar/issues/76. Closing this.

**Comment by dims** [comment]
@saad-ali @msau42 

Can we try the grpc options used in other spots?

Looks like the current options for the connect are here:
https://github.com/kubernetes-csi/driver-registrar/blob/master/pkg/connection/connection.go#L69-L73

cadvisor for example has `WithBlock` and `WithTimeout`
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/google/cadvisor/container/containerd/client.go#L71-L76

**Comment by saad-ali** [comment]
@dims will do!
