### ISSUE TITLE
how Kubernetes work.?

### ISSUE THREAD

**Issue by babalsurer** [kubernetes/kubernetes#71446]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by nikopen** [comment]
Feel free to refer to the documentation: https://kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational

/close
