### ISSUE TITLE
ResourceQuota objects not refreshing anymore (while admission controller still working)

### ISSUE THREAD

**Issue by nikopen** [kubernetes/kubernetes#71450]
**What happened**

ResourceQuotas are configured in every namespace of a busy production cluster. At some point the following happened:

- "status:used" got inflated / was more than the sum of Requests in namespaces
- "status:hard" refused to get updated via applying new manifests - "spec:hard" was normally updated but "status:hard" was stuck.
- attempted deleting and recreating the ResourceQuota, and "status" remained empty {}.

Still, the main functionality of refusing to schedule new pods that exceeded current status:hard was still working.

**Remediation:**

killed controller-manager, as soon as another pod took the master lease and controllers started working, the issue got resolved.

My best guess is that there's some kind of deadlock in the ResourceQuota controller or in controller-manager in general.

**Environment**:
- k8s 1.10.9
- Cloud provider: VSphere on-premise
- OS: Ubuntu 16.04
- Kernel:  4.4.0-135

/kind bug
/sig apps api-machinery scheduling
(not sure what's the exact SIG for this)

**Comment by nikopen** [comment]
Possibly related issues:

https://github.com/kubernetes/kubernetes/issues/67761
https://github.com/kubernetes/kubernetes/issues/60037

**Comment by liggitt** [comment]
Do you have controller manager logs from the affected period?

**Comment by nikopen** [comment]
it was down for about 16 hours, and the conman logs are super verbose/spammy, about 300k per day... trying to filter out the junk and find something relevant.

grepping for "quota" only greps the "exceeded quota" messages of the admission controller not allowing new pods to be scheduled

**Comment by nikopen** [comment]
Can't fully verify the exact time when resourcequota froze, but this sequence of log lines are very near to it:

about 20+ lines of this:
```
E1126 14:43:52.091365       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=1043203, ErrCode=NO_ERROR, debug=""
```

then this failing for every existing API:
```
E1126 14:43:52.101571       1 reflector.go:322] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to watch *v1beta1.ValidatingWebhookConfiguration: Get https://10.12.35.140:6443/apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations?resourceVersion=488618546&timeoutSeconds=439&watch=true: dial tcp 10.12.35.140:6443: getsockopt: connection refused
E1126 14:43:52.101676       1 reflector.go:322] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to watch *v1alpha1.PriorityClass: Get https://10.12.35.140:6443/apis/scheduling.k8s.io/v1alpha1/priorityclasses?resourceVersion=488618528&timeoutSeconds=416&watch=true: dial tcp 10.12.35.140:6443: getsockopt: connection refused

E1126 14:43:52.104459       1 reflector.go:322] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to watch *v1.NetworkPolicy: Get https://10.12.35.140:6443/apis/networking.k8s.io/v1/networkpolicies?resourceVersion=488618518&timeoutSeconds=381&watch=true: dial tcp 10.12.35.140:6443: getsockopt: connection refused
```
etc.

```
E1126 14:43:52.260971       1 cronjob_controller.go:118] can't list Jobs: Get https://10.12.35.140:6443/apis/batch/v1/jobs: dial tcp 10.12.35.140:6443: getsockopt: connection refused
```

```
E1126 14:43:53.106662       1 reflector.go:205] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:125: Failed to list <nil>: Get https://10.12.35.140:6443/apis/extensions/v1beta1/networkpolicies?limit=500&resourceVersion=0: dial tcp 10.12.35.140:6443: getsockopt: connection refused
```

Failed to watch resourcequota:
```
E1126 14:43:52.104596       1 reflector.go:322] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to watch *v1.ResourceQuota: Get https://10.12.35.140:6443/api/v1/resourcequotas?resourceVersion=504569223&timeoutSeconds=392&watch=true: dial tcp 10.12.35.140:6443: getsockopt: connection refused
```

leader election failure:
```
E1126 14:43:53.188641       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://10.12.35.140:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 10.12.35.140:6443: getsockopt: connection refused
```

```
serviceaccounts failing:
E1126 14:44:00.749690       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1alpha1.PriorityClass: priorityclasses.scheduling.k8s.io is forbidden: User "system:kube-controller-manager" cannot list priorityclasses.scheduling.k8s.io at the cluster scope
E1126 14:44:00.749786       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:kube-controller-manager" cannot list validatingwebhookconfigurations.admissionregistration.k8s.io at the cluster scope
```
etc for all APIs again

```
E1126 14:44:00.877901       1 reflector.go:205] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:125: Failed to list <nil>: servicemonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:kube-system:generic-garbage-collector" cannot list servicemonitors.monitoring.coreos.com at the cluster scope
E1126 14:44:00.880207       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.PodSecurityPolicy: podsecuritypolicies.policy is forbidden: User "system:kube-controller-manager" cannot list podsecuritypolicies.policy at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:kube-controller-manager" not found, clusterrole.rbac.authorization.k8s.io "view" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "olympus:podsecuritypolicy:restricted" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found]
```

waiting for caches:
```
I1126 14:44:00.895058       1 controller_utils.go:1019] Waiting for caches to sync for resource quota controller
```

@liggitt

**Comment by nikopen** [comment]
after these events, the only thing not working was essentially the ResourceQuota controller, everything else looked fine

**Comment by liggitt** [comment]
do you have API server logs for a few seconds before and after `14:44:00.895058`? it looks like something significant happened with the apiserver, first being unavailable, then returning errors about default RBAC roles not being found. was the API server restarted as well when the issue was resolved, or just the controller manager?

a potential deadlock was fixed in the GC controller in 1.11 around resync racing with available resources changing in https://github.com/kubernetes/kubernetes/pull/64235

it looks like that deadlock can still occur in resource quota in https://github.com/kubernetes/kubernetes/blob/2fd10764c848e580a78c94b7cc4359f5c9e8083c/pkg/controller/resourcequota/resource_quota_controller.go#L435-L442 if a resource type (like a CRD) is removed between when `newResources` is computed and when `controller.WaitForCacheSync` is called (`WaitForCacheSync` will hang forever trying to sync the now-nonexistent resources)

**Comment by nikopen** [comment]
There are 5 apiserver replicas, and it seems that at 14:40:02 they started restarting on a rolling update fashion - they're mirror pods so it wasn't triggered by a deployment, and not sure what triggered that, but there's loglines on shutting down and bringing up each apiserver very quickly (so no node restarts), then proceeding on the next one.

14:44 is during bringing up the 4th apiserver which lived in the same node with the leader-elected controller-manager at the time.

apiserver logs:
14:43:57 'started 10 admission controllers successfully'
14:44:00.065 'serving securely'

then waiting for caches to sync, and 'quota admission added evaluator for (resource) over the next 20 minutes
```
I1126 14:56:59.798267       7 controller.go:537] quota admission added evaluator for: {apps daemonsets}\n
```

Other than that APIserver logs don't have anything of interest printed

It's likely the above deadlock was hit. I'll continue having a look tomorrow, gotta go

**Comment by yliaog** [comment]
@nikopen do you know if there are resource types removed during that time period? as @liggitt pointed out that the deadlock could happen when a resource type (like a CRD) is removed between when newResources is computed and when controller.WaitForCacheSync is called. I think it is good to confirm that is what happened in your case.

**Comment by nikopen** [comment]
@yliaog where would that information be? Audit logs? 

not sure if there's enough retention for the logs to still exist, but @JHK @boosty may be able to help you on this

**Comment by yliaog** [comment]
Yes, audit log should be able to tell if it still exists.

**Comment by JHK** [comment]
Sorry, we don't have the audit logs anymore for this time period.
