### ISSUE TITLE
Support ordinal index for normal (stateless) pod

### ISSUE THREAD

**Issue by dream83619** [kubernetes/kubernetes#71458]
**What would you like to be added**:
Support ordinal index for normal (stateless) pod.

**Why is this needed**:
When we use docker swarm, there is a {{ .Task.Slot }}, which we use in a lot of scenario. (e.g. set spring cloud stream's instance index and identity application instance for logging). But kubernetes only support this feature for stateful-set. It will be very helpful to support this feature for stateless pod either.

@kubernetes/sig-contributor-experience-feature-requests

/kind feature
/sig contributor-experience

**Comment by nikhita** [comment]
/remove-sig contributor-experience

I guess this should be (?)
/sig apps

**Comment by mhyousefi** [comment]
Ok, so what is the alternative to `Docker Swarm`'s `{{ .Task.Slot }}` in, let's say, K8S `Deployment` or `ReplicaSet`??

**Comment by mhyousefi** [comment]
It turns out you can expose pod info to containers with envs using the `Downward API` as explained in [this link](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/).
