### ISSUE TITLE
ingress host name

### ISSUE THREAD

**Issue by vengam** [kubernetes/kubernetes#71459]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
below is my ingress file
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: fund-processor
spec:
  rules:
  - host: fundprocessor.ksd.ntrs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fund-processor
          servicePort: 80

when iam hitting the url https://fundprocessor.ksd.ntrs.com , getting error 502 and when i change the host in ingress to  fundprocessor-dev.ksd.ntrs.com and redeploy it is working. before it is working with url  fundprocessor.ksd.ntrs.com but it is not working now and when i change to new host  fundprocessor-dev.ksd.ntrs.com then it is working. what is the exact issue can you explain.

/kind bug

**Comment by yue9944882** [comment]
@vengam plz move this issue to the repo of ur ingress controller instead. it's beyond the scope of kubernetes main repo.

/close
