### ISSUE TITLE
Dynamic audit webhook versioning

### ISSUE THREAD

**Issue by pbarker** [kubernetes/kubernetes#71464]
**What would you like to be added**:
Currently dynamic audit configuration only allows for audit events to be sent in a pinned version https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/audit/dynamic/dynamic.go#L104. This should ideally be configurable.

/kind feature

**Comment by maniSbindra** [comment]
Hi @pbarker @tallclair I would like to work on the issue if no one else is.

Thanks.

**Comment by pbarker** [comment]
That would be awesome @maniSbindra. I haven't started on that piece, but feel free to ping me on slack if you have any questions

**Comment by mourya007** [comment]
@pbarker @tallclair I would like to work on this issue.

**Comment by mourya007** [comment]
@pbarker @maniSbindra  Are you still working on this ? Can I start working on it if nobody has started till now?

**Comment by ethereal-sandeep** [comment]
@pbarker I would like to work on it, if no one working on it.

**Comment by mourya007** [comment]
@maniSbindra  Thanks, I am starting working on this now.

**Comment by mourya007** [comment]
@pbarker Can you provide any reference for how to start on this feature ?

**Comment by pbarker** [comment]
@mourya007 I opened a PR for the API change as that will take awhile to get through https://github.com/kubernetes/kubernetes/pull/73547

**Comment by pbarker** [comment]
@mourya007 also see https://github.com/kubernetes/kubernetes/pull/73547#issuecomment-459109958 we may want to hold out to see the outcome of the admission work

**Comment by liggitt** [comment]
> @mourya007 also see [#73547 (comment)](https://github.com/kubernetes/kubernetes/pull/73547#issuecomment-459109958) we may want to hold out to see the outcome of the admission work

see https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md#admissionreview-v1 for the accepted proposal. Shaping the work in progress for the audit webhook like that would be a reasonable next step

**Comment by mourya007** [comment]
> > @mourya007 also see [#73547 (comment)](https://github.com/kubernetes/kubernetes/pull/73547#issuecomment-459109958) we may want to hold out to see the outcome of the admission work
> 
> see https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/00xx-admission-webhooks-to-ga.md#admissionreview-v1 for the accepted proposal. Shaping the work in progress for the audit webhook like that would be a reasonable next step

I think @pbarker updated the webhook struct with the specified comment. So, what should be the next step.
