### ISSUE TITLE
Support PVC Expansion Through StatefulSet volumeClaimTemplates

### ISSUE THREAD

**Issue by SidakM** [kubernetes/kubernetes#71477]
**What would you like to be added**:
Support and allow for users to increase the storage requests in the volumeClaimTemplates inside of a statefulset. The increased storage requests should propagate to all PVCs associated with the modified volumeClaimTemplates.

**Why is this needed**:
Since 1.11 persistent volume expansion is in beta which allows for a PVC's resource storage request to be increased. However, it is not possible to modify a volumeClaimTemplate in a statefulset to achieve the same effect in all associated PVCs.

Quickly wrote something for this last week: https://github.com/kubernetes/kubernetes/pull/71384

Proposal: https://github.com/kubernetes/enhancements/pull/660
Feature tracking issue: https://github.com/kubernetes/enhancements/issues/661

/kind feature

**Comment by SidakM** [comment]
@kubernetes/sig-apps-pr-reviews https://github.com/kubernetes/kubernetes/pull/71384

**Comment by SidakM** [comment]
@kubernetes/sig-apps-pr-reviews https://github.com/kubernetes/kubernetes/pull/71384 can I get  some 👀 on this PR it's been a while...

**Comment by mlushpenko** [comment]
I thought I had problems with helm, good the solution is in progress already.
