### ISSUE TITLE
Flaky test: Image pull failed with "readlink /var/lib/docker/overlay2: invalid argument"

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71473]
**What happened**:
Test logs show that there were issues pulling container images:

```
Nov 26 09:49:10.193: INFO: At 2018-11-26 09:44:10 +0000 UTC - event for csi-hostpath-provisioner-0: {kubelet test-34cf3ed1e3-minion-group-qzrz} InspectFailed: Failed to inspect image "gcr.io/gke-release/csi-provisioner:v0.4.1-gke.0": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
Nov 26 09:49:10.193: INFO: At 2018-11-26 09:44:10 +0000 UTC - event for csi-hostpath-provisioner-0: {kubelet test-34cf3ed1e3-minion-group-qzrz} Failed: Error: ImageInspectError
```

@kubernetes/sig-storage-bugs 

/kind bug

**Comment by msau42** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-serial/1493#sig-storage-csi-volumes-driver-csi-hostpath-v0-testpattern-dynamic-pv-default-fs-subpath-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow

**Comment by msau42** [comment]
I spoke with node team, and they said the "readlink /var/lib/docker/overlay2: invalid argument" error is a known, un-rootcaused docker issue that may occur if the node unexpectedly crashes: https://github.com/moby/moby/issues/35747

**Comment by msau42** [comment]
cc @kubernetes/sig-node-bugs

**Comment by msau42** [comment]
Since this is a long standing docker problem, I don't think this should be release blocking

**Comment by msau42** [comment]
@jiayingz and I worked out the timeline of events:
1. a different hostpath csi test was running at 07:07, which uses the csi driver container images.
```
 I1126 07:07:43.322] [0m[sig-storage] CSI Volumes[0m [90m[Driver: csi-hostpath-v0][0m [0m[Testpattern: Dynamic PV (default fs)] subPath[0m 
I1126 07:07:43.322]   [1mshould unmount if pod is force deleted while kubelet is down [Disruptive][Slow][0m
```
The test brought up the driver, decided to skip the test, and started bringing down the driver, but doesn't wait for it to fully brought down?

2. Afterwards, a reboot test ran
```
I1126 07:08:08.229] [0m[sig-cluster-lifecycle] Restart [Disruptive][0m 
I1126 07:08:08.229]   [1mshould restart all nodes and ensure all nodes and pods recover[0m
```

3.  While the reboot was happening, the hostpath container images were still being pulled.  This probably triggered moby/moby#35747

4. When the next CSI Hostpath test ran, it failed to pull the images
```
Nov 26 09:49:10.193: INFO: At 2018-11-26 09:44:10 +0000 UTC - event for csi-hostpath-provisioner-0: {kubelet test-34cf3ed1e3-minion-group-qzrz} InspectFailed: Failed to inspect image "gcr.io/gke-release/csi-provisioner:v0.4.1-gke.0": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
Nov 26 09:49:10.193: INFO: At 2018-11-26 09:44:10 +0000 UTC - event for csi-hostpath-provisioner-0: {kubelet test-34cf3ed1e3-minion-group-qzrz} Failed: Error: ImageInspectError
```

**Comment by msau42** [comment]
We can probably improve the storage tests to not bring up the driver if we're going to skip it.  I believe https://github.com/kubernetes/kubernetes/pull/70992 might address some of this.

**Comment by alejandrox1** [comment]
This is showing up again [ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1303](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1303)
/remove-lifecycle stale

**Comment by msau42** [comment]
@alejandrox1 the test case is the same, but I don't think the symptom is the same.  The most recent failure is probably more related to https://github.com/kubernetes/kubernetes/issues/72500
