### ISSUE TITLE
Failling Test: [sig-storage] Flexvolume expansion tests are flaky

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#71470]
This is a child issue of https://github.com/kubernetes/kubernetes/issues/71434

For example - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/21996

/sig storage

@aniket-s-kulkarni will you be able to look into this?

**Comment by AishSundar** [comment]
/milestone v1.13
/kind failing-test
/priority critical-urgent

I am addind this to 1.13 milestone as critical-urgent until investigated and triaged otherwise. The Code freeze deadline for the fix is EOD tomorrow, 11/28

/cc @msau42 @jberkus @mariantalla @mortent

**Comment by gnufied** [comment]
@aniket-s-kulkarni if you read kubelet logs, it may contain clues about why status condition failed to update. I do agree that if `pvc.Status.Capacity` had correct value then condition should be removed too but apparently something happened.

**Comment by gnufied** [comment]
I think the root cause of this issue is - same PVC is being considered twice for resizing while fs resizing was pending on the node.  The flow is like this:

1.  User edits the PVC and requests more size (this add pvc resize progress condition)
2. flexvolume plugin controller side resize is instant and hence it returns success immediately and pv size is updated and PVC gets fs resize condition.
3. On node, kubelet resizes the volume and removes the condition.
4. Now while we wait for resize on the node, same PVC is being considerd again for resizing by the expand-controller loop, because pvc.status.capacity < pvc.spec.capacity .  The actual operation generator code actually will reject the second resize request - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L1266 because it considers PV size but what we are seeing is, resize-in-progress condition is being at least added twice.

Here is how we know that volume was considered twice for resize:

```
1126 13:08:09.979859       1 volume_resize_map.go:115] Adding pvc e2e-tests-mounted-flexvolume-expand-6c7wp/pvc-k7lj2 with Size 6Gi/2Gi for resizing
I1126 13:08:12.090042       1 volume_resize_map.go:115] Adding pvc e2e-tests-mounted-flexvolume-expand-6c7wp/pvc-k7lj2 with Size 6Gi/2Gi for resizing
```

This flake was not introduced by flexvolume change afaict and existed before. I think timing issue with flex is just triggering it. All resize operation are idempotent and expand controller anyways rejects the resize request by comparing PV size and hence it should not be too bad. In worst case, this WILL cause a condition to be added to the PVC unnecessarily (and that is what is happening here).

I will make a fix for this. But IMO - this should not be release blocker.

**Comment by saad-ali** [comment]
Thanks for digging in to this @gnufied.

Based on https://github.com/kubernetes/kubernetes/issues/71434#issuecomment-442252599 we will move this to v1.14 and document it as a known issue for Flex resize.

/milestone v1.14

**Comment by AishSundar** [comment]
@gnufied @saad-ali is there any perceived user effect  if an extra condition gets added to the PVC ? is it just ignored?

**Comment by jberkus** [comment]
Fix tags:

/kind flake
/remove-kind failing-test

**Comment by gnufied** [comment]
The condition exists as a messaging to the user about stage of volume resizing, but there aren't any actions taken based on that. So - user will not have any usage issues with PVC or anything, guess just the messaging will be kinda confusing.  Also - the issue itself is kinda rare. For example, this test flaked only twice between 11/13 and 11/27, so most users will most likely not run into this.

**Comment by AishSundar** [comment]
Thanks @gnufied this is now moved to 1.14

**Comment by spiffxp** [comment]
/remove-lifecycle stale
This is still failing (it's unclear to me whether it's a flake or a continuous failure from this display) https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Flexvolume

**Comment by gnufied** [comment]
Yeah,  there is a fix for this available actually - https://github.com/kubernetes/kubernetes/pull/71611 . I need to sync with @jsafrane and see how we can merge the PR.

**Comment by nikopen** [comment]
Hey @gnufied , in terms of v1.14 release, how close is the fix for this / what's the current status?

**Comment by gnufied** [comment]
We missed fixing this in v1.14. We are working on a fix that will land in 1.15.

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-longterm
More representative of how it's actually being treated

**Comment by gnufied** [comment]
This should be fixed now..

/close
