### ISSUE TITLE
Flake in Kubectl port forwarding

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71472]
**Which jobs are failing**: gce-new-master-upgrade-parallel, and other tests (see triage link below)

**Which test(s) are failing**: 

* [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects a client request should support a client that connects, sends DATA, and disconnects
* [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects

**Since when has it been failing**:  As long as we have history

**Testgrid link**: 

recent example: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel

**Reason for failure**:

Looks like IPv6 failures: 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/portforward.go:496
Nov 27 10:34:17.006: Failed to parse kubectl port-forward output: Forwarding from [::1]:39785 -> 80

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/portforward.go:182
```
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/portforward.go:490
Nov 27 16:38:38.223: Failed to parse kubectl port-forward output: Forwarding from [::1]:40777 -> 80

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/portforward.go:182
```

So this may or may not be related to #70248

Looks like this particular test has been flaky across our suite of test jobs, for as long as we have history:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-11-27&test=With%20a%20server%20listening%20on%20localhost

... so I'm suspecting that the test was mis-designed with a built-in race condition or some similar problem.  Please investigate and clean it up, thanks!

**Anything else we need to know**:

This is not a blocker for 1.13

/kind flake
/sig cli
/priority important-soon
attn:
@AishSundar 
@kubernetes/sig-cli-test-failures
@soltysh @adohe

**Comment by jberkus** [comment]
This flake is being addressed here: https://github.com/kubernetes/kubectl/issues/558

**Comment by m1kola** [comment]
Closing this issue. See https://github.com/kubernetes/kubectl/issues/558#issuecomment-450673237 for a bit more details.

/close
