### ISSUE TITLE
Flaky test: container start fails with "linux runtime spec devices: lstat /dev/sdc: no such file or directory"

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71478]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-slow

**Which test(s) are failing**:
[sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support creating multiple subpath from same volumes

**Since when has it been failing**:
Flaked once on 11/23

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/21942

**Reason for failure**:
Container failed to start with:
```
Nov 24 06:28:00.091: INFO: At 2018-11-24 06:27:57 +0000 UTC - event for pod-subpath-test-emptydir-5bs6: {kubelet bootstrap-e2e-minion-group-82h4} Failed: Error: failed to start container "test-container-volume-emptydir-5bs6": Error response from daemon: linux runtime spec devices: lstat /dev/sdc: no such file or directory
```

I'm unsure where /dev/sdc is coming from.  Usually emptydir volumes share the root disk at /dev/sda.

**Anything else we need to know**:

@kubernetes/sig-node-bugs 

/kind failing-test

**Comment by jberkus** [comment]
fixing tags:

/kind flake
/remove-kind failing-test

/priority important-soon

**Comment by wongma7** [comment]
The pod is privileged so it has something to do with devices on the host moving around while the container is starting.

for e.g. https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-kube-dns/1912#sig-storage-in-tree-volumes-driver-nfs-testpattern-pre-provisioned-pv-default-fs-subpath-should-support-existing-directory

/dev/sdh gets detached around the time the pod is starting.

I0124 21:35:25.367655    1454 operation_generator.go:517] MountVolume.WaitForAttach succeeded for volume "pvc-e8e455d6-201f-11e9-b9fb-42010a800002" (UniqueName: "kubernetes.io/gce-pd/e2e-1912-9415e-dynamic-pvc-e8e455d6-201f-11e9-b9fb-42010a800002") pod "pod-subpath-test-gcepd-dynamicpv-w6j5" (UID: "eb51c1bd-201f-11e9-b9fb-42010a800002") DevicePath "/dev/disk/by-id/google-e2e-1912-9415e-dynamic-pvc-e8e455d6-201f-11e9-b9fb-42010a800002"
I0124 21:35:25.391775    1454 mount_linux.go:454] `fsck` error fsck from util-linux 2.28.2
fsck.ext2: Bad magic number in super-block while trying to open /dev/sdh

I0124 21:35:48.420752       1 reconciler.go:229] attacherDetacher.DetachVolume started for volume "pvc-e8e455d6-201f-11e9-b9fb-42010a800002" (UniqueName: "kubernetes.io/gce-pd/e2e-1912-9415e-dynamic-pvc-e8e455d6-201f-11e9-b9fb-42010a800002") on node "e2e-1912-9415e-minion-group-vjpf" 

INFO: At 2019-01-24 21:36:00 +0000 UTC - event for pod-subpath-test-nfs-preprovisionedpv-g7nr: {kubelet e2e-1912-9415e-minion-group-vjpf} Failed: Error: failed to start container "test-container-subpath-nfs-preprovisionedpv-g7nr": Error response from daemon: linux runtime spec devices: lstat /dev/sdh: no such file or directory

I0124 21:36:07.671188       1 operation_generator.go:430] DetachVolume.Detach succeeded for volume "pvc-e8e455d6-201f-11e9-b9fb-42010a800002" (UniqueName: "kubernetes.io/gce-pd/e2e-1912-9415e-dynamic-pvc-e8e455d6-201f-11e9-b9fb-42010a800002") on node "e2e-1912-9415e-minion-group-vjpf" 

Unsure how to work around this, it is probably the container runtime's job to tolerate this

**Comment by gnufied** [comment]
@wongma7 Did ADC just detach the volume while fsck/mount was in progress?

**Comment by wongma7** [comment]
@gnufied no, I omitted bunch of lines. Just wanted to show that google-e2e-1912-9415e-dynamic-pvc-e8e455d6-201f-11e9-b9fb-42010a800002 is /dev/sdh and it got detached in between 35:48 and 36:07, pod failed at 36:00

**Comment by msau42** [comment]
It's strange that it's showing an error message for a device that is unrelated to the container.  The error message makes it sound like the runtime is listing all the devices on the host

**Comment by wongma7** [comment]
It looks like docker is doing that (if container is privileged) https://github.com/moby/moby/blob/62d80835abe3f7bc54c70f5e7bad638eaf3596be/daemon/oci_linux.go#L87

**Comment by msau42** [comment]
Ahh, I guess if the container's privileged, it's making all the host devices available to the container too.  Which doesn't work that well in Kubernetes as devices fluctuate.

I'm surprised though that a retry won't work eventually
