### ISSUE TITLE
ci-cri-containerd-e2e-ubuntu-gce many tests fail with: failed to create containerd task

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71476]
**Which jobs are failing**:
ci-cri-containerd-e2e-ubuntu-gce

**Which test(s) are failing**:
Many failed in this run

**Since when has it been failing**:
This run failed on 10/25

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-cri-containerd-e2e-ubuntu-gce/8226#sig-storage-in-tree-volumes-driver-gcepd-testpattern-inline-volume-default-fs-volumes-should-be-mountable

**Reason for failure**:
Containers failed to start with:
Oct 26 05:18:47.930: INFO: At 2018-10-26 05:18:24 +0000 UTC - event for volume-injector-zz89: {kubelet bootstrap-e2e-minion-group-gb8z} Failed: Error: failed to create containerd task: OCI runtime create failed: container_linux.go:336: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"cgroup\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v1.linux/k8s.io/volume-injector/rootfs\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /run/containerd/io.containerd.runtime.v1.linux/k8s.io/6cfb2144321818493ad276acafb2d082b3233afd19b5f6c0558f268a8a7215cb/rootfs/sys/fs/pod8534b75c-d8de-11e8-b7cf-42010a800002/volume-injector: no such file or directory\\\"\"": unknown

**Anything else we need to know**:

@kubernetes/sig-node-bugs 

/kind failing-test

**Comment by msau42** [comment]
cc @yujuhong @Random-Liu

**Comment by Random-Liu** [comment]
runc should never check `stat /run/containerd/io.containerd.runtime.v1.linux/k8s.io/6cfb2144321818493ad276acafb2d082b3233afd19b5f6c0558f268a8a7215cb/rootfs/sys/fs/pod8534b75c-d8de-11e8-b7cf-42010a800002/volume-injector`, which of course does not exist. It should be `.../rootfs/sys/fs/cgroups/cpu/pod....` etc.

We only know that the error is thrown out by this line https://github.com/opencontainers/runc/blob/master/libcontainer/rootfs_linux.go#L58, but we don't know why runc tries to mount to that destination.

And please note that the error happens to different containers in different tests in that run, and all the failures happen on the same node "bootstrap-e2e-minion-group-gb8z".

I'd like to believe that something is wrong on the node, e.g. misconfigured mounts, unexpected symlinks confused runc on the node.
