### ISSUE TITLE
Make the ELB name conform to cloud providers rules

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#7148]
Cloud providers have various rules regarding the naming of a load balancer. Here are links to the rules of GCE (https://cloud.google.com/compute/docs/load-balancing/network/target-pools) and AWS(http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLoadBalancer.html).

Currently we have made sure the names returned by GetLoadBalancerName will satisfy the rules of GCE and AWS. In the future, we need to make this function more flexible so that different naming rules can be forced.

Related: #7145 #6812

**Comment by justinsb** [comment]
I think we can close this?  At least on AWS, we now create the ELB with a name derived from the service UUID, so we can guarantee we meet the rules, whatever name the user chooses.

I think this is the pattern other clouds use/should use also.  Closing, but feel free to reopen if not...
