### ISSUE TITLE
Unschedulable pods may block head of the scheduling queue

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#71486]
**What happened**:
In large clusters, events that trigger rescheduling of the unschedulable pods are frequent. For example, in a cluster with 1000 nodes, node updates, which are often just heartbeats, may happen at an average rate of 100/s. These events trigger rescheduling of unschedulable pods. The scheduler moves unschedulable pods to its active scheduling queue when such events are observed. There are two particularly problematic scenarios:
1. There are high-priority unschedulable pods and preemption does not help make them schedulable. For example, they may have node affinity that cannot be satisfied, or they may have pod affinity to other pods that do not exist. Such high priority pods may go to the head of the active scheduling queue and block everything behind them.
2. There are many pending pods with the same priority, but a number of them are unschedulable. When these unschedulable pods are moved to the active queue, they are expected to go behind other pods in the queue, but since our queue sorts pods by priority and these pods have the same priority, their order is unspecified. The Pop() algorithm of the heap swaps the head of the queue with the tail, effectively causing the heap to act similar to a LIFO. So, pods which are tried recently, go to the head with a high probability and are retried. This starves pods behind them in the queue.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig scheduling
/assign

**Comment by bsalamat** [comment]
@hex108 Yes, we basically need a [back-off mechanism for the scheduling queue](https://github.com/kubernetes/kubernetes/pull/57057). Another approach is to [differentiate between node heartbeats vs. actual node updates](https://github.com/kubernetes/kubernetes/issues/70316). We will pursue both of these approaches.

**Comment by xiaoxubeii** [comment]
@bsalamat @hex108 Agree. On the one hand we need to reduce the frequency of unnecessary rescheduling, on the other hand we need to optimize the sorting algorithm. And the #70366 would help to reduce the frequency. But I think "differentiate between node heartbeats vs. actual node updates" is a better approach.

**Comment by Abhik1998** [comment]
Yes its a better approach indeed but what if we use the recursion there

**Comment by bsalamat** [comment]
@xiaoxubeii We should have all three changes to address all known scenarios efficiently. The three changes are:
1. #57057 back off mechanism
2. #71488 fair sorting of pods in the scheduling queue
3. #71551 smarter processing of node updates

Node updates are not the only trigger for the scheduler to retry unschedulable pods. The scheduler also retries when running pods terminate, among a couple of other events. So, without having backoff mechanism a high priority unschedulable pod could still block head of the queue in clusters with high churn, for example, in clusters where many pods terminate frequently.
Back off mechanism by itself addresses the issue in all scenarios, but the other two changes make the scheduling queue smarter and more efficient.

**Comment by xiaoxubeii** [comment]
@bsalamat The three prs above are quite comprehensive : ).

**Comment by bsalamat** [comment]
All of the above items are done already.
