### ISSUE TITLE
Don't need to update the deletionTimestamp if the pod is already in deleting phase

### ISSUE THREAD

**Issue by yuki90** [kubernetes/kubernetes#71494]
Currently if one pod is stuck in deleting status and we delete the pod again, the deletionTimestamp will be updated to the latest timestamp.

It is better to keep the deletionTimestamp as when the first delete action taken. Then we can use it to trace how long the pod is stuck in deleting phase.

/sig api-machinery

**Comment by yue9944882** [comment]
[https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L114](https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L114)

iiuc the deletion timestamp wont be updated unless you requests w/ a shorter grace period. how you reproduce that?

**Comment by liggitt** [comment]
correct, the deletiontimestamp is only modified for an existing object when the grace period is shortened

/close
