### ISSUE TITLE
@kubernetes/sig-Testing-test-failures,proposals: Worker node in "NotReady" state on master node in Kubernetes.

### ISSUE THREAD

**Issue by rossawan** [kubernetes/kubernetes#71498]
We have 1 master and 1 worker node.
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
--------------------------------------------
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2",
---------------------------------------------------------------------------------
Docker Version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64
 Experimental: false

------------------------------------------------------------------------------ 
Below are logs from Master and Worker.

Master node logs: 
Nov 27 12:32:19 testing kubelet[24591]: W1127 12:32:19.208696   24591 cni.go:293] CNI failed to retrieve network namespace path: cannot find network namespace for the t
Nov 27 12:32:19 testing kubelet[24591]: W1127 12:32:19.206761   24591 pod_container_deletor.go:75] Container "9370575f67db6a3fa95a73eed2eae0387290c4623bdc9b5dad55122298
Nov 27 12:32:19 testing kubelet[24591]: W1127 12:32:19.172445   24591 docker_sandbox.go:375] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the s
Nov 27 12:32:19 testing kubelet[24591]: W1127 12:32:19.161208   24591 cni.go:293] CNI failed to retrieve network namespace path: cannot find network namespace for the t
Nov 27 12:32:19 testing kubelet[24591]: W1127 12:32:19.144750   24591 pod_container_deletor.go:75] Container "f46e7aa98b5ccc0cf5e72720f35518493afe5d3cb73795618f165f39a4
Nov 27 12:32:19 testing kubelet[24591]: W1127 12:32:19.117088   24591 docker_sandbox.go:375] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the s
Nov 27 12:32:19 testing kubelet[24591]: E1127 12:32:19.102436   24591 pod_workers.go:186] Error syncing pod 383946b0-f211-11e8-9b47-026e4269e78c ("coredns-576cbf47c7-tk
Nov 27 12:32:19 testing kubelet[24591]: E1127 12:32:19.102214   24591 kuberuntime_manager.go:657] createPodSandbox for pod "coredns-576cbf47c7-tkhpw_kube-system(383946b
Nov 27 12:32:19 testing kubelet[24591]: E1127 12:32:19.102199   24591 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "coredns-576cbf47c7-tkhpw_kube-system(383946b0
Nov 27 12:32:19 testing kubelet[24591]: E1127 12:32:19.102137   24591 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc =
Nov 27 12:32:07 testing kubelet[24591]: 2018-11-27 12:32:07.843 [INFO][13943] k8s.go 794: pod info &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:

Worker Logs:
Nov 28 06:17:40 testingnew kubelet[21666]: E1128 06:17:40.112560   21666 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc
Nov 28 06:17:36 testingnew kubelet[21666]: E1128 06:17:36.463498   21666 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNo
Nov 28 06:17:36 testingnew kubelet[21666]: W1128 06:17:36.462567   21666 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 28 06:17:35 testingnew kubelet[21666]: E1128 06:17:35.109166   21666 pod_workers.go:186] Error syncing pod 33057587-f215-11e8-bac5-026e4269e78c ("kube-flannel-ds-am
Nov 28 06:17:35 testingnew kubelet[21666]: E1128 06:17:35.109079   21666 kuberuntime_manager.go:657] createPodSandbox for pod "kube-flannel-ds-amd64-d59kx_kube-system(3
Nov 28 06:17:35 testingnew kubelet[21666]: E1128 06:17:35.109057   21666 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "kube-flannel-ds-amd64-d59kx_kube-system(33
Nov 28 06:17:35 testingnew kubelet[21666]: E1128 06:17:35.108986   21666 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc
Nov 28 06:17:31 testingnew kubelet[21666]: E1128 06:17:31.460570   21666 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNo
Nov 28 06:17:31 testingnew kubelet[21666]: W1128 06:17:31.459770   21666 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 28 06:17:28 testingnew kubelet[21666]: E1128 06:17:28.108928   21666 pod_workers.go:186] Error syncing pod 33051f2a-f215-11e8-bac5-026e4269e78c ("kube-proxy-dxqvj_k
Nov 28 06:17:28 testingnew kubelet[21666]: E1128 06:17:28.108872   21666 kuberuntime_manager.go:657] createPodSandbox for pod "kube-proxy-dxqvj_kube-system(33051f2a-f21
Nov 28 06:17:28 testingnew kubelet[21666]: E1128 06:17:28.108850   21666 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "kube-proxy-dxqvj_kube-system(33051f2a-f215
Nov 28 06:17:28 testingnew kubelet[21666]: E1128 06:17:28.108797   21666 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc

**Comment by rossawan** [comment]
> @rossawan: There are no sig labels on this issue. Please add a sig label by either:
> 
> 1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
>    e.g., `@kubernetes/sig-contributor-experience-<group-suffix>` to notify the contributor experience sig, OR
> 2. specifying the label manually: `/sig <group-name>`
>    e.g., `/sig scalability` to apply the `sig/scalability` label
> 
> Note: Method 1 will trigger an email to the group. See the [group list](https://git.k8s.io/community/sig-list.md).
> The `<group-suffix>` in method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

Sig-label done. Please help me on this issue. Thanks.

**Comment by Shnatsel** [comment]
The SIG labels should be done in message body, not in the title. It should probably be made more clear. I'll do it now: @kubernetes/sig-testing-test-failures

@rossawan is the issue still relevant?
