### ISSUE TITLE
vsphere cloud provider dynamic volume provisioning fails with message "No VM found"

### ISSUE THREAD

**Issue by SWBSanjeewa** [kubernetes/kubernetes#71502]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig sig-vmware

**What happened**:
when try to create pvc using dynamic volume provisioning using storageclass, the status of the pvc is pending forever and below is the kubectl describe pvc output looks like

Events:
  Type       Reason              Age               From                         Message
  Warning    ProvisioningFailed  9s (x3 over 26s)  persistentvolume-controller  Failed to provision volume with StorageClass "thin-disk": No VM found

**What you expected to happen**:
PVC is successfully created and bound

**How to reproduce it (as minimally and precisely as possible)**:
Start kubernetes as vsphere cloud provider, create storage class for vsphere cloud provider and create PVC for storageclass

**Anything else we need to know?**:
When investigate the issue and the kubernetes source a workaround was worked.
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere_util.go
func GetNodeUUID(node *v1.Node) (string, error) 

the method is suppose to return node UUID
if(kubeletVersion < v1.9.4) {
     return node.Status.NodeInfo.SystemUUID
}else{
     return "vsphere://"+node.Spec.ProviderID
}
so since we have kubernetes version v1.12.2 UUID will get get from node.Spec.ProviderID

kubectl get no ubuntu-rnd-02 -o json
{
    "apiVersion": "v1",
    "kind": "Node",
    "spec": {
        "podCIDR": "10.244.2.0/24"
    },
    "status": {
        "nodeInfo": {
            "systemUUID": "421F1857-47B2-C797-312D-C2B5D67059D5",
			"kubeletVersion": "v1.12.2",
        }
    }
}

Since we have kubernetes version v1.12.2 it should get node UUID from node.Spec.ProviderID but when try to get node details using kubectl get node -o yaml there is no value for node.Spec.ProviderID

By editing kubernetes node resource and adding node.Spec.ProviderID manually and after restarting kube-controller-manager, PVC was created successfully and status was changed to Bounded

apiVersion: v1
kind: Node
spec:
  providerID: vsphere://421FEB34-F754-4D5D-DD3F-672B8B30322F

**Environment**:
- Kubernetes version 1.12
- Cloud provider or hardware configuration: vsphere cloud provider
- OS (Ubuntu 18.04.1):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig sig-vmware

**Comment by dkirrane** [comment]
Seeing the same issue on kubeadm 1.12.3 cluster
`persistentvolume-controller  Failed to provision volume with StorageClass "thin-disk": No VM found`

**Comment by umair-akram** [comment]
Kind of different problem we were upgrading from 1.10.12 to 1.11.6. In our case the PVC is success fully formed and bounded but when one of the pods is scheduled and control plane wants to mount this pvc it fails with No VM found.

**Comment by Torrent007** [comment]
Any update on it? I have this issue too :(

**Comment by Shnatsel** [comment]
Since this seems to be something related to VSphere specifically, you should also try contacting VMware support about it.

**Comment by dansou901** [comment]
Same here, this is still an issue for me

**Comment by derWeihnachtsmann** [comment]
also got this issue. My cluster-yaml looks like the following:

> cloud_provider: 
>   name: "vsphere"
>   vsphereCloudProvider: 
>     ..disk: 
>       ....scsicontrollertype: "pvscsi"
>     ..global: 
>       ....datacenter: "My-Datacenter"
>       ....insecure-flag: true
>       ....port: "443"
>       ....server: "10.10.1.100"
>       ....soap-roundtrip-count: 0
>       ....user: "administrator@vsphere.local"
>       ....working-dir: "Rancher-VM-DIR"
>     ..virtual_center: 
>       ....10.10.1.100: 
>         ....soap-roundtrip-count: 0
>         ....user: "administrator@vsphere.local"
>     ..workspace: 
>       ....datacenter: "My-Datacenter"
>       ....default-datastore: "RAID10_DC5_02_01"
>       ....folder: "Rancher-VM-DIR"
>       ....server: "10.10.1.100"

My StorageClass:
![grafik](https://user-images.githubusercontent.com/16196578/60338934-8e72ff00-99a7-11e9-8695-e703044aedd8.png)

My Workload-Configuration:
![grafik](https://user-images.githubusercontent.com/16196578/60339056-f1fd2c80-99a7-11e9-918d-1608c4f9efa7.png)

![grafik](https://user-images.githubusercontent.com/16196578/60339081-06d9c000-99a8-11e9-8e27-793056123081.png)

PVC-Info:

\> kubectl get pvc
NAME          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
testclaim     Pending                                      sc-mskgj       18s
volumeclaim   Pending                                      sc-mskgj       56m
\> kubectl describe pvc testclaim
Name:          testclaim
Namespace:     default
StorageClass:  sc-mskgj
Status:        Pending
Volume:        
Labels:        cattle.io/creator=norman
Annotations:   field.cattle.io/creatorId: user-rn7vj
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason              Age                From                         Message
  \----       ------              ----               ----                         -------
  Warning    ProvisioningFailed  11s (x2 over 26s)  persistentvolume-controller  Failed to provision volume with StorageClass "sc-mskgj": No VM found
Mounted By:  testworkload-5d6959d97c-ln48x`

**Comment by qwrobins** [comment]
I'm having this issue as well. Is there a work around?

**Comment by petertsu** [comment]
I'm having this issue as well. Is there a work around?

**Comment by derWeihnachtsmann** [comment]
I solved this by editing the Cluster yaml again and again in RancherUI. It now looks like this and is confirmed to WORK:

> cloud_provider: 
>   ..name: "vsphere"
>   ..vsphereCloudProvider: 
>     ....disk: 
>       ......scsicontrollertype: "pvscsi"
>     ....global: 
>       ......datacenter: "Datacenter01"
>       ......insecure-flag: true
>       ......port: "443"
>       ......server: "10.10.1.200"
>       ......soap-roundtrip-count: 0
>       ......user: "administrator@vsphere.local"
>       ......working-dir: "KubernetesVMs"
>     ....virtual_center: 
>       ......10.10.1.200: 
>         ......soap-roundtrip-count: 0
>     ....workspace: 
>       ......datacenter: "Datacenter01"
>       ......default-datastore: "RAID10_DC5_02_01"
>       ......folder: "KubernetesVMs"
>       ......server: "10.10.1.200"

I assume I missed some lines at the workspace-part..

I use vcenter 6.0 / ESXI 6.0.0 13635687

Maybe this helps someone.

**Comment by SWBSanjeewa** [comment]
This issue was encounter when you add cloud provider to vsphere for an already configured cluster with worker nodes. You should first create kubernetes  master with vsphere cloud provider and add worker nodes after that with vsphere cloud provider, node resource will be created with correct node.Spec.ProviderID starting with vsphere://<UUID> as expected

**Comment by SandeepPissay** [comment]
/close

Closing this as there is no issue in the code, but its a deployment issue.
