### ISSUE TITLE
kubeadm init fail 90% of the time on aarch64 (rock64) due to TLS timeouts

### ISSUE THREAD

**Issue by Xnyle** [kubernetes/kubernetes#71505]
**What happened**:

When running kubeadmin (versions tested 11.5 to 12.3) init on a vanilla debian aarch64 the process times out/fails most of the times.

Why: I guess because kube-apiserver is hammerd with requests the whole time by kube-scheduler and kube-controller-manager pods. kube-apiserver sits at 100% cpu the whole time and the querying pods get TLS connection timeouts while the etcd pod is also complaining about "took too long (904.738249ms) to execute".

I'm not sure, if etcd is the problem though , cause kube-apiserver is @100% cpu while etcd is more or less idle.

The matter gets even worse, if I put etcds datair away from the sd card to an external USB3 SSD even if random writes are normally much faster to that disk.

kube-apiserver eventually fails with 100s of "TLS handshake error from 192.168.X.X:5XXXX" and gets restarted.

If i'm lucky the second kube-apiserver is then finally able to process requests and init succeeds. Most of the time it fails though.

**What you expected to happen**:

kubeadm init should give pods room to breathe during initialization on toy clusters. Actually I wouldn't even call a rock64 a toy, it's a pretty beefy SBC and k8s should init without problems on it.

As there are many similar bug reports around and the problem seems to pop up again @ every new major version I'd also expect that ARM bare metal clusters don't get neglected so much during testing.

**How to reproduce it (as minimally and precisely as possible)**:

kubeadm init --pod-network-cidr 10.244.0.0/16 #on aarch64

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.12.3
- OS (e.g. from /etc/os-release): debian stretch ayufaran
- Kernel (e.g. `uname -a`): 4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1

/sig api-machinery

/kind bug

**Comment by neolit123** [comment]
> kubeadm init should give pods room to breathe during initialization on toy clusters. Actually I wouldn't even call a rock64 a toy, it's a pretty beefy SBC and k8s should init without problems on it.

this isn't really a kubeadm problem.
k8s is vastly untested on arches other than AMD64, although we did receive reports about successful mixed-arch clusters from the CNCF.
at one point for ARM we were suspecting a race condition in the kubelet instead of a "room to breathe" scenario.

please try kubeadm + kubelet + control-plane 1.13 and get back to this with a report of what you see.

also have a look at this (liveness probe problem for RPI):
https://github.com/kubernetes/kubeadm/issues/413#issuecomment-438695903

^ using this solution in 1.13 you can also experiment with tweaks in the manifest files in terms of pod resource limits.
thanks.

/priority awaiting-more-evidence

**Comment by geoffgarside** [comment]
From what I’ve seen in the past most of the ARM64 issues stem from the poor RSA crypto in Golang 1.10 and earlier, it should be improved in 1.11 but k8s and importantly etcd need to be built with 1.11 for those RSA improvements to be seen. I’ve not looked into this for a while now so I’m not up to date on what version of Golang is being used at the moment for each of these.

**Comment by geoffgarside** [comment]
Looks like etcd 3.4 requires Golang 1.11+ based on the CHANGELOG, so they might work. Does kubeadm still default to 3.2.x? 3.2 appears to use Golang 1.8, 3.3 uses Golang 1.9.

**Comment by dims** [comment]
@geoffgarside yes kubeadm from 1.13 will use etcd `3.2.24`. In 1.14, it will be switched to 3.3 (follow along in https://github.com/kubernetes/kubernetes/issues/61326)

**Comment by neolit123** [comment]
etcd 3.2.24 is built using 1.8.7:
https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/Makefile#L55

**Comment by Xnyle** [comment]
Will try 1.13 and report back when it's available as deb package, as I currently only have limited time for that toy cluster project.

**Comment by timothysc** [comment]
Closing this issue.  

If you are still having an issue in 1.13, please feel free to reopen an issue here: https://github.com/kubernetes/kubeadm
