### ISSUE TITLE
Flake: sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: gcePD [Serial] should provision storage

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71519]
**Which jobs are failing**: Various upgrade and downgrade jobs

**Which test(s) are failing**: [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: gcePD [Serial] should provision storage

**Since when has it been failing**: 

it's been a flake as long as we have history (to September), although it became more frequent around 10/3: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-10-15&test=CSI%20Volumes%20CSI%20plugin%20test%20using%20CSI%20driver%3A%20gcePD

**Testgrid link**:  

Most recent: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster

But it's occurred across a whole suite of jobs

**Reason for failure**:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1109

Looks like the GCE storage is simply not provisioning: 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:112
Expected error:
    <*errors.errorString | 0xc42238e560>: {
        s: "Gave up after waiting 15m0s for pod \"pvc-volume-tester-ccrzq\" to be \"success or failure\"",
    }
    Gave up after waiting 15m0s for pod "pvc-volume-tester-ccrzq" to be "success or failure"
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:1256
			
```

... which suggests that this is a problem with GCE and not with storage, but I'm going to tag everyone here just in case.

**Anything else we need to know**:

Right now, this is not a blocker for 1.13, but if it happens as frequently as it did this morning it could be.

/kind flake
/priority important-soon
/sig storage
/sig gcp
/sig testing
attn:
@AishSundar @spiffxp @msau42 @saad-ali @kubernetes/sig-gcp-bugs

**Comment by msau42** [comment]
Looking at the linked failure, the pod failed to come up because of:
```
Nov 26 18:46:46.607: INFO: At 2018-11-26 18:31:33 +0000 UTC - event for pvc-volume-tester-nmxd2: {kubelet bootstrap-e2e-minion-group-8t0n} FailedMount: MountVolume.WaitForAttach failed for volume "pvc-6b608a39-f1a9-11e8-81df-42010a800002" : volume us-central1-f/pvc-6b608a39-f1a9-11e8-81df-42010a800002 has GET error for volume attachment : resource name may not be empty
```

This error should have been fixed by https://github.com/kubernetes/kubernetes/pull/71095, which merged 11/16.

This particular test job is downgrading the cluster to 1.12, which will have this bug.  We could look into backporting #71095 if necessary.

**Comment by msau42** [comment]
I see the test in the upgrade suite stopped failing after 11/21, which runs against 1.14 nodes.

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2636
I took a look at the last failure and saw:
```
Nov 22 00:56:28.077: INFO: At 2018-11-22 00:41:15 +0000 UTC - event for pvc-volume-tester-j5b75: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-48de939c-edef-11e8-9f70-42010a800002" : node "bootstrap-e2e-minion-group-d8pp" has no NodeID annotation
```

I think this was the same issue as described in https://github.com/kubernetes/kubernetes/issues/70760#issuecomment-438863272, but the date of the fix doesn't seem to line up with when the tests stopped failing.

**Comment by msau42** [comment]
Oh actually, I think the upgrade suite was failing until 11/21, because of the backwards compatibility issues that were fixed in https://github.com/kubernetes/kubernetes/pull/71314

**Comment by spiffxp** [comment]
/area deflake

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-12-31&pr=1&text=not%20in%20phase%20Bound%20

This seems to be occurring much less frequently than it did, I would be willing to call it closed, I leave to you two to decide if there's more to be done
