### ISSUE TITLE
Allow CSI Drivers that support BOTH 0.x and 1.x to use old plugin dir

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#71517]
**What happened**:
CSI allows 0.x drivers only in the deprecated kubelet plugin dir.
CSI allows 1.x drivers only in the new kubelet plugin dir.

If a driver implements both 0.x and 1.x (which is unlikely since the side car containers do not support this), kubelet requires the driver live in new kubelet plugin dir.

So CSI drivers that implement both 0.x and 1.x if they want a seamless transition between k8s 1.12 to 1.13 would need to deploy in both old and new dir.

**What you expected to happen**:

@liggitt argues that this is adding churn for CSI authors. He recommends allowing any driver that implements 0.x (even if it implements 1.x) to use either new or old (not just new).

/milestone v1.13

If release team approves, PR is small and I can get prepare it pretty quickly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
discussed in the burndown meeting, please go ahead and prepare the PR

**Comment by AishSundar** [comment]
@dougm @cjwagner we need to wait for a fix for this before lifting code freeze
