### ISSUE TITLE
kubectl create support cronjob

### ISSUE THREAD

**Issue by welemon** [kubernetes/kubernetes#71511]
**What would you like to be added**:
```
kubectl create cronjob ...
or 
kubectl create job --schedule="* * * * *" ...
```
**Why is this needed**:
Because of https://github.com/kubernetes/kubernetes/pull/68132
`kubectl run` is not recommended to create cronjob (with `--schedule` flags) anymore.
But there is no imperative command available for `kubectl create` to create cronjob.

/sig CLI

/kind feature

**Comment by Pingan2017** [comment]
i wanna work on this. give me several days
