### ISSUE TITLE
Failing Test: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should be able to switch between HTTPS and HTTP2 modes

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71521]
**Which jobs are failing**: gce-cos-1.13-ingress

**Which test(s) are failing**:  [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should be able to switch between HTTPS and HTTP2 modes

**Since when has it been failing**: 11/27, around 9am

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-1.13-blocking#gce-cos-1.13-ingress

**Reason for failure**:

Timeout

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:425
Failed to get request_version=2 or request_scheme=https, response body: 
Expected error:
    <*errors.errorString | 0xc0000cf860>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:1101
```

**Anything else we need to know**:

This is a blocker for 1.13

/kind failing-test
/priority critical-urgent
/sig network
/sig gcp
attn:
@kubernetes/sig-network-bugs @kubernetes/sig-gcp-bugs 
@AishSundar @MrHohn @caseydavenport @thockin

**Comment by jberkus** [comment]
According to triage, this is a fairly new flake, so it's more likely than not representative of 1.13-related breakage.  https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20be%20able%20to%20switch%20between%20HTTPS%20and%20HTTP2%20modes

**Comment by MrHohn** [comment]
cc @agau4779

**Comment by dims** [comment]
@jberkus looks like the same flake shows up in older versions too. right?

https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-cos-1.11-ingress
https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-ingress

1.10 does not have the same test ...

**Comment by MrHohn** [comment]
Given that, seems likely caused by a recent change on GCE side. Not sure what changed yet.

**Comment by jberkus** [comment]
Oooh, well spotted.  I'd guess a problem with GCE's support of HTTP2.  Let's see if we can raise someone on the GCE side.

**Comment by AishSundar** [comment]
/cc @agau4779 

Adding Ashley who is trying to repro the issue locally.

**Comment by MrHohn** [comment]
We reproduced the issue locally and seems like there are some issues on the GCE side --- we confirmed all k8s components are acting properly but the test backend is observeing inconsistent HTTP version on in-coming requests. We've raised an internal issue for this.

This shouldn't block the release though given it is on GCE side.

**Comment by liggitt** [comment]
the job has now had 16 green runs in a row. can it be closed?

**Comment by AishSundar** [comment]
yes they rolled out a fixed on GCE end yesterday :) Closing now, @jberkus please reopen if it recurs.

/close
