### ISSUE TITLE
Storage XFS volumes should be mountable test does not verify actual formatted filesystem

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#71528]
This test does not verify what filesystem was actually formatted on the device. If we just always format `ext4` (would be a bug), all these "volumes should be mountable" tests will pass no matter what filesystem we pass in even if it is not supported.

/sig storage
/kind bug

/cc @msau42

**Comment by msau42** [comment]
cc @mkimuram I think you opened a similar issue?

**Comment by mkimuram** [comment]
@msau42 @davidz627 

I think https://github.com/kubernetes/kubernetes/pull/70823 should address this issue.

**Comment by mkimuram** [comment]
Also, to avoid a situation like need to skip specific filesystem for specific environment as explained in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/192 , csi gce driver will need to add skip like  https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/drivers/in_tree.go#L1135 .

**Comment by davidz627** [comment]
closing due to duplicate of https://github.com/kubernetes/kubernetes/issues/70822
