### ISSUE TITLE
Single source for DEBs and RPMs

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#71530]
We have duplicate code in k/release and k/k for deb(s) and rpm(s). 

The code in k/release is built using:
```
./jenkins.sh --kube-version 1.12.0 --distros xenial` (debs)
./docker-build.sh` (rpms)
```

The code in k/k is built using:
```
bazel build //build/debs 
bazel build //build/rpms
```

Note that the code in k/release can sign the debs and rpms, while the one in k/k doesn't (AFAICT). 

Since k/k is versioned and k/release is not, we need to drop the code in k/release and stick to the one in k/k. More specifically we need to change our release process to build the stuff from k/k and push them to where ever we publish artifacts. So there's a lot more digging to be done

Related issue : https://github.com/kubernetes/release/issues/631

/sig release

cc @tpepper @calebamiles @justaugustus

**Comment by timothysc** [comment]
closing in favor of #71677
