### ISSUE TITLE
GCE PD CSI "should work after update" test failing

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#71536]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4399

**Which jobs are failing**:
sig-release-master-blocking

**Which test(s) are failing**:
[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] should work after update

**Since when has it been failing**:
Since the test was introduced

**Testgrid link**:
[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] should work after update

**Reason for failure**:
Looks like the secret the driver requires is not being added to the cluster.

/kind failing-test
/sig storage
/cc @msau42 
/assign

**Comment by msau42** [comment]
oops i opened https://github.com/kubernetes/kubernetes/issues/71534 too
