### ISSUE TITLE
Flake: [sig-scheduling] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#71541]
**Which jobs are failing**: soak-gce-gci-1.13, others

**Which test(s) are failing**: [sig-scheduling] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]

**Since when has it been failing**:

Rougly forever.  #63768 shows how this test was flaking back during the 1.11 cycle.  There's been no sudden increase in frequency, but a test that flakes roughly 1.5 times per hour needs looking into, and probably tweaking.

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-release-1.13-all#soak-gci-gce-1.13
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/500

**Reason for failure**:

Most of the time, these flakes are timeouts.  However, sometimes they have other causes; see Triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-10-15&test=validates%20MaxPods%20limit%20number%20of%20pods%20that%20are%20allowed%20to%20run

**Anything else we need to know**:

This is part of a general effort to clean up our CI signal by eliminating longstanding, frequent flakes.

/kind flake
/priority important-longterm
/sig scheduling
attn:
@kubernetes/sig-scheduling-bugs 
@k82cn

**Comment by alenkacz** [comment]
There are several different failures in this test, I was in particular looking at 
`Error waiting for 312 pods to be running - probably a timeout` which usually boils down to something like this
`event for maxp-309: {default-scheduler } FailedScheduling: 0/4 nodes are available: 1 node(s) were unschedulable, 3 Insufficient pods.`

My hunch is that we are trying to schedule more than we should.

This is how we compute how many pods to schedule https://github.com/kubernetes/kubernetes/blob/b8ba75bcd9d3be31e4b53105b2cc67538c9c2d1b/test/e2e/scheduling/predicates.go#L116 which just takes max capacity and substracts whatever this returns https://github.com/kubernetes/kubernetes/blob/eaf89cfbb483f99411141f70c294e8a014e49cec/test/e2e/framework/util.go#L3110

My guess would be that the computation is not completely correct. My idea would be to add more logging into `WaitForStableCluster` to be able to figure out more. Does that sound reasonable to you or would you take another approach? 

cc. @bsalamat

**Comment by alenkacz** [comment]
These are all the non-test containers running there at the time the test fails (because there's no extra space to schedule the last successful pod)

```
Jun 19 04:00:25.604: INFO: 	Container fluentd-gcp ready: true, restart count 0
Jun 19 04:00:25.604: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 0
Jun 19 04:00:25.605: INFO: 	Container metadata-proxy ready: true, restart count 0
Jun 19 04:00:25.605: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 0
Jun 19 04:00:25.605: INFO: 	Container kube-proxy ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container metrics-server ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container metrics-server-nanny ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container coredns ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container kube-proxy ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container metadata-proxy ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 0
Jun 19 04:00:25.986: INFO: 	Container kubernetes-dashboard ready: true, restart count 0
Jun 19 04:00:25.987: INFO: 	Container fluentd-gcp ready: true, restart count 0
Jun 19 04:00:25.987: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container autoscaler ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container coredns ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container metadata-proxy ready: true, restart count 1
Jun 19 04:00:26.545: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 1
Jun 19 04:00:26.545: INFO: 	Container fluentd-gcp-scaler ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container kube-proxy ready: true, restart count 1
Jun 19 04:00:26.545: INFO: 	Container event-exporter ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container fluentd-gcp ready: true, restart count 1
Jun 19 04:00:26.545: INFO: 	Container prometheus-to-sd-exporter ready: true, restart count 1
Jun 19 04:00:26.545: INFO: 	Container heapster ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container heapster-nanny ready: true, restart count 0
Jun 19 04:00:26.545: INFO: 	Container default-http-backend ready: true, restart count 0
```

**Comment by alenkacz** [comment]
I went over all the pods that were on the node before the test started and then after and diff-ed all the pods that are not started by the test "grep -v maxp-" and did not found any pod that would start in the middle of test and was not present in the beginning :/ 

but there were 18 pods in the beginning, 330 is the full capacity so we should have started 312 to fully saturate, while we were trying to start 313. (maybe some pod restarted right when we were starting the test?)

I am looking at this latest case https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1141089953766182913 but there's many like this one

**Comment by alenkacz** [comment]
Can we possibly be missing some pods here? https://github.com/kubernetes/kubernetes/blob/ec02afb46edba4f673173811491498c709de990a/test/e2e/framework/pod/resource.go#L683 pods with no node assigned that are not unschedulable?

**Comment by alenkacz** [comment]
This just got much worse in the last weeks, I tried looking into PRs along the time and hit into this https://github.com/kubernetes/kubernetes/pull/83365 could someone please verify it that could have made things worse?

@ahg-g @Huang-Wei @notpad 

I'll also try to look tomorrow since I investigated this while ago :)

**Comment by Huang-Wei** [comment]
Another flake: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83578/pull-kubernetes-integration/1190306355727044611/

**Comment by alenkacz** [comment]
Anyone can help here? It's constantly red for several days, it's not even flaking anymore in our release dashboards

https://testgrid.k8s.io/sig-release-1.17-informing#gce-cos-k8sbeta-serial

/priority important-soon
