### ISSUE TITLE
Kubernetes HPA returning incorrect API version

### ISSUE THREAD

**Issue by therealgambo** [kubernetes/kubernetes#71556]
**What happened**:

When applying a HPA `autoscaling/v2beta1` manifest, kubernetes accepts the manifest and returns the `autoscaling/v1` version when querying the manifest.

**What you expected to happen**:
Manifest to maintain `autoscaling/v2beta1` api version

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl create -f hpa-demo.yaml`
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hpa-demo-master
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
```

`kubectl get hpa -o yaml hpa-demo`
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2018-11-29T10:53:31Z","reason":"ReadyForNewScale","message":"the
      last scale time was sufficiently old as to warrant a new scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2018-11-29T10:53:31Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from memory resource
      utilization (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2018-11-29T10:53:31Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"memory","currentAverageUtilization":38,"currentAverageValue":"4018176"}},{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":20,"currentAverageValue":"1m"}}]'
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageUtilization":80}}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"hpa-demo","namespace":"staging0"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"},{"resource":{"name":"memory","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"extensions/v1beta1","kind":"Deployment","name":"hpa-demo-master"}}}
  creationTimestamp: 2018-11-29T10:52:01Z
  name: hpa-demo
  namespace: staging0
  resourceVersion: "718045"
  selfLink: /apis/autoscaling/v1/namespaces/staging0/horizontalpodautoscalers/hpa-demo
  uid: cd513382-f3c4-11e8-9fa7-02bf9ef29fa4
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hpa-demo-master
  targetCPUUtilizationPercentage: 80
status:
  currentCPUUtilizationPercentage: 20
  currentReplicas: 1
  desiredReplicas: 1
```

As you can see from the above, the manifest is accepted by kubernetes on creation, when retrieving the mainfest it's returned in v1 format.

If we explicitly define the apiversion, we get the correct response.
`kubectl get hpa.v2beta1.autoscaling -o yaml hpa-demo`
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"hpa-demo","namespace":"staging0"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"},{"resource":{"name":"memory","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"extensions/v1beta1","kind":"Deployment","name":"hpa-demo-master"}}}
  creationTimestamp: 2018-11-29T10:52:01Z
  name: hpa-demo
  namespace: staging0
  resourceVersion: "718045"
  selfLink: /apis/autoscaling/v2beta1/namespaces/staging0/horizontalpodautoscalers/hpa-demo
  uid: cd513382-f3c4-11e8-9fa7-02bf9ef29fa4
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hpa-demo-master
status:
  conditions:
  - lastTransitionTime: 2018-11-29T10:53:31Z
    message: the last scale time was sufficiently old as to warrant a new scale
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: 2018-11-29T10:53:31Z
    message: the HPA was able to successfully calculate a replica count from memory
      resource utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: 2018-11-29T10:53:31Z
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - resource:
      currentAverageUtilization: 38
      currentAverageValue: "4018176"
      name: memory
    type: Resource
  - resource:
      currentAverageUtilization: 20
      currentAverageValue: 1m
      name: cpu
    type: Resource
  currentReplicas: 1
  desiredReplicas: 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.10", GitCommit:"be1a908c6aa47e0ae1b1dc861a1de6ccfe963aa2", GitTreeState:"clean", BuildDate:"2018-11-13T11:33:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): `Container Linux by CoreOS 1520.9.0 (Ladybug)   4.13.16-coreos-r1   docker://1.12.6`
- Kernel (e.g. `uname -a`):a
- Install tools:
- Others:

/kind bug

**Comment by MaciekPytel** [comment]
This is working as intended. v1 is the default version of HPA so that's what you get if you don't request a specific version. You can get autoscaling/v2beta1 representation of your HPA by running `kubectl get hpa.v2beta1.autoscaling -o yaml hpa-demo`

A bit of explanaition: Internally all HPA objects are stored in the same way, regardless which version of API you used to create them. When you get HPA Kubernetes API server converts this internal representation to the version you requested.

**Comment by therealgambo** [comment]
Is there a way to make `hpa.v2beta1.autoscaling` the default output in my cluster, for cluster operators this is confusing as they aren't seeing the true configuration.

**Comment by liupeng0518** [comment]
emmm...
I have the same question, but the memory is unknown, k8s has no error.
```
[root@k8s-m1 hpa]# kubectl get hpa
NAME         REFERENCE               TARGETS                   MINPODS   MAXPODS   REPLICAS   AGE
php-apache   Deployment/php-apache   <unknown>/100Mi, 0%/50%   1         10        1          52m

```

**Comment by srsrin** [comment]
Piggybacking off of the realgambo, is there anyway to make the beta version the default? Because when deployed the hpa through helm, helm doesn't allow the use of beta versions so reverts back to v1 when we would like to be using v2beta2 @MaciekPytel 

thanks.

**Comment by MaciekPytel** [comment]
I don't know - @kubernetes/sig-api-machinery-misc can you help with the question above?

**Comment by liggitt** [comment]
> Is there a way to make hpa.v2beta1.autoscaling the default output in my cluster, for cluster operators this is confusing as they aren't seeing the true configuration.

no, the API group and version ordering is pinned in the API server.

note that this only affects how kubectl decides to resolve ambiguous get requests... if you want a specific version, include that in the kubectl get request.

**Comment by farrukh90** [comment]
This is still an issue. can we reopen it?

**Comment by liggitt** [comment]
This is working as designed. `v1` is preferred when no version is specified in a kubectl get command. You can get the autoscaling/v2beta1 representation of your HPA by running `kubectl get hpa.v2beta1.autoscaling -o yaml hpa-demo`

**Comment by wmcnamee-tunein** [comment]
why not get the representation of the object itself? you cannot have multiple objects of the same name and different versions

**Comment by lavalamp** [comment]
> why not get the representation of the object itself? you cannot have multiple objects of the same name and different versions

The server can convert all objects to any version of their resource it understands, so I don't understand.

If we change this for all of you who want v2betaX to be the default, then we will have a bunch of people wanting v1 to be the default again :)

There has to be some default. Please make your scripts / api calls explicitly request the version you want.

**Comment by ghostsquad** [comment]
I'm not saying the default, I'm saying the version that was applied

**Comment by ghostsquad** [comment]
Maybe I'm just a bit confused about what the correct way to interact with, or get versioned resources and get the _accurate_ representation of that resource. Again, coming back to `v1` vs `v2beta2` of an HPA. There's no `metrics` array in the HPA spec in v1. So, if I default to getting the v1 representation, it's essentially "empty". I need some way to determine the actual version as it exists in etcd.

At first, I thought well, I could `get` and look at `kubectl.kubernetes.io/last-applied-configuration` annotation, but I'm not sure if that annotation would reliably exist. It would also require 2 gets each time.

If it's safe to say that older versions of APIs can always be accurately converted to newer versions, then the I think you could always target the newer version. But then the issue is that older versions get deprecated, and again, it doesn't matter how I `get` them, it only matters how they are actually stored in etcd, so I could run into an issue where they are stored as on old version, and when I upgrade k8s those resources stop working.

**Comment by lavalamp** [comment]
No, that's not how versions work in kubernetes. The data has to be represented *somehow* in all versions, or the server can't round-trip between them without losing something. In your case, you must always ask for v2beta2 and fall back to v1 if the server doesn't understand your request.

The version stored in etcd is not a detail that clients are able to figure out* from behavior.

[*] although we do now expose it for the storage migrator, it's purposely not obvious, to help people like yourself not take a dependency on it that you'll regret later :)

**Comment by ghostsquad** [comment]
would it be safe then to ask for a new feature of kubectl, such that via `~/.kube/config` I can specify what I would like the "default" apiVersion to be for each resource when I run `kubectl get hpa` and it's ambiguous? If so, I can file a new issue and link these.

**Comment by lavalamp** [comment]
We'd strongly prefer that scripts specify the exact version they want-- @liggitt demonstrated the syntax above.

**Comment by ghostsquad** [comment]
> No, that's not how versions work in kubernetes. The data has to be represented somehow in all versions, or the server can't round-trip between them without losing something. In your case, you must always ask for v2beta2 and fall back to v1 if the server doesn't understand your request.

When I see deprecation warnings, such as those in v1.16, how should I proceed to identify which resources are old and going to be deprecated?

> Ingress resources will no longer be served from extensions/v1beta1 in v1.20. Migrate use to the networking.k8s.io/v1beta1 API, available since v1.14. Existing persisted data can be retrieved via the networking.k8s.io/v1beta1 API.

Or is this saying that nothing actually has to be done to older versions, but that this deprecation warning is only for clients that use the API and have expectations of the structure of the data based on the apiVersion?

**Comment by lavalamp** [comment]
> Or is this saying that nothing actually has to be done to older versions, but that this deprecation warning is only for clients that use the API and have expectations of the structure of the data based on the apiVersion?

Kubernetes does the right thing with the data. Users have to do the right thing with their clients (i.e., upgrade them to use new versions).

**Comment by ghostsquad** [comment]
Thank you

**Comment by ryanjwh** [comment]
Keep in mind, this doesn't just affect scripts. There are a wealth of tools for k8s management, CI/CD, etc out there and this can break them as well - and users of k8s don't necessarily have control over modifying the tool (at least, easily) to work with the newer API. IE:
* Spinnaker
* Rancher

Now, if we have Spinnaker deploying an HPA, and we use a new feature in HPA that requires v2beta, and Spinnaker depends on kubectl to function, then it potentially runs into errors trying to manage hpa resources because kubectl (by extension of the k8s cluster) is passing it back bad data if it tries to get current state for any reason.

**Comment by lavalamp** [comment]
> ... Spinnaker depends on kubectl to function, then it potentially runs into errors trying to manage hpa resources because kubectl (by extension of the k8s cluster) is passing it back bad data if it tries to get current state for any reason.

Tools should always use a specific version, then this won't happen. Please file a bug with the relevant tools.

Note that it's totally fine for you to interact with an object in one version, and a tool to interact with the object in a different version. That is totally fine unless the API author isn't passing our round trip test.
