### ISSUE TITLE
kube-proxy/IPVS: arp_ignore and arp_announce break some CNI plugins

### ISSUE THREAD

**Issue by lbernail** [kubernetes/kubernetes#71555]
**What happened**:
After PR: #70530, we noticed communications issue in our pods.
We use the Lyft CNI plugin (https://github.com/lyft/cni-ipvlan-vpc-k8s) which relies on two interfaces in pod:
* an IPVLAN interface connecting to the AWS VPC which has a VPC IP
* an Unnumbered point-to-point interface (veth) connecting to the host and that does not have an IP (it "borrows" the one from the IPVLAN interface)

On the host side, there is a veth interface which also doesn't have an IP (it borrows one from the main interface).

With the latest versions of kube-proxy communication between host and pods break

**What you expected to happen**:
Communication still works

**How to reproduce it (as minimally and precisely as possible)**:
* Use the Lyft CNI plugin
* Deploy kube-proxy `v1.13.0-beta.2`
* Try to ping the host from a pod (or a pod from the host)

**Anything else we need to know?**:
The new sysctls create 2 issues:
* containers started after kube-proxy inherit net.ipv4.conf.all.arp_ignore=1 so they will not answer ARP queries on the veth interface
* the veth on the host side also does not have an IP so it will no answer ARP queries from the pods

I know that our setup is pretty uncommon but assuming that the veth on the host side will have an IP seems dangerous. Some discussions on the PTP plugin for instance suggest not using IP for the host interface: containernetworking/plugins#137

Possible fixes:
* create a flag to enable ARP filtering (I think to avoid breaking existing setups, we should disable it by default but I'm fine with enabling it by default as long as we document the solution)
* use arptables to filter ARP queries for clusterIPs (`arptables -A INPUT -d <clusterIP> -j DROP`): a bit more work because we need to do it for all clusterIPs (there may be a more efficient way to do it but I could not make it work by filtering on the kube-ipvs interface) and this requires the arptables binary. We could test for the existence of the binary and log a warning if it is missing (similar to behavior with conntrack)

**Environment**:
- Kubernetes version (use `kubectl version`): kube-proxy `v1.13.0-alpha.3`
- OS (e.g. from /etc/os-release): `Ubuntu 18.04.1 LTS`
- Kernel (e.g. `uname -a`): `Linux ip-10-128-212-113 4.15.0-1023-aws #23-Ubuntu SMP Mon Sep 24 16:31:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

/area ipvs
/sig network
/kind bug

/assign @m1093782566 
ping @kvaps

**Comment by kvaps** [comment]
I can say only that solution with arptables working fine with MetalLB.

**Comment by m1093782566** [comment]
Oh, really? Glad you confirm that.

**Comment by lbernail** [comment]
It doesn't look like arptables works with ipset

**Comment by kvaps** [comment]
Unfortunately arptables doesn't support ipsets, but `nft` do. (not fully implemented)

Eg:
```
nft add chain arp filter input   { type filter hook input   priority 0 \; }
nft add set arp filter k8s_services { type ipv4_addr\;}
nft add arp element k8s_services { 1.2.3.4 }
nft add arp element k8s_services { 1.2.3.5, 1.2.3.6 }
```
But current implementation is not allowing to use it for arp rules for now:
```
nft add rule arp filter input arp plen 4 @nh,96,32 @k8s_services counter drop
```
Will answer:
```
Error: datatype mismatch, expected integer, expression has type IPv4 address
add rule arp filter input arp operation request arp plen 4 @nh,96,32 @k8s_services counter drop
                                                           ~~~~~~~~~ ^^^^^^^^^^^^^
```
I guess because there is still no type specified for `@nh,96,32`

BTW: nft does not allow to create set of integer components:
https://www.spinics.net/lists/netfilter-devel/msg36817.html

But there is a way for specify multiple IPs for one rule, eg:

```
nft add rule arp filter input arp plen 4 @nh,96,32 {16909060, 16909061, 16909062} counter drop
```
Where `16909060, 16909061, 16909062` is IPv4 addresses in decimal format

**Comment by lbernail** [comment]
Another option would be to use the `service-cluster-ip-range` and filter all queries but this flag is not in kube-proxy today

**Comment by kvaps** [comment]
Bad idea, it will handle `clusterIPs` but not `externalIPs` - which can be really differ

**Comment by kvaps** [comment]
@lbernail can you explain more detail why Lyft CNI can not assign IPs to the right interfaces for avoid this kind of issues?

**Comment by lbernail** [comment]
> Bad idea, it will handle clusterIPs but not externalIPs - which can be really differ

Yes you are right. bad idea

> can you explain more detail why Lyft CNI can not assign IPs to the right interfaces for avoid this kind of issues?

It could definitely add IPs to these interfaces but it's not the choice that was made. More details here: https://eng.lyft.com/announcing-cni-ipvlan-vpc-k8s-ipvlan-overlay-free-kubernetes-networking-in-aws-95191201476e ("Unnumbered point-to-point interface"). I could probably PR a fix there.

I'm a bit worried that some other CNI plugins could break here though

**Comment by ymmt2005** [comment]
Just FYI, we have another CNI plugin that is affected by this.
https://github.com/cybozu-go/coil/issues/37

**Comment by ymmt2005** [comment]
We addressed the issue by assigning a link-local address 169.254.1.1/32
to the host-side veth in https://github.com/cybozu-go/coil/pull/36 .

So this issue is not critical at least for our case.

**Comment by kvaps** [comment]
> Unfortunately `arptables` doesn't support ipsets, but new `nftables` do. (not fully implemented yet)
> 
> Eg we can create ipset for arp:
> 
> ```
> nft add chain arp filter input   { type filter hook input   priority 0 \; }
> nft add set arp filter k8s_services { type ipv4_addr\;}
> nft add arp element k8s_services { 1.2.3.4 }
> nft add arp element k8s_services { 1.2.3.5, 1.2.3.6 }
> ```
> 
> But current implementation is not allowing to use it for arp rules for now:
> 
> ```
> nft add rule arp filter input arp plen 4 @nh,96,32 @k8s_services counter drop
> ```
> 
> Will return:
> 
> ```
> Error: datatype mismatch, expected integer, expression has type IPv4 address
> add rule arp filter input arp operation request arp plen 4 @nh,96,32 @k8s_services counter drop
>                                                            ~~~~~~~~~ ^^^^^^^^^^^^^
> ```
> 
> I guess because there is still no type specified for `@nh,96,32` (destination ip) and `@nh,64,32` (source ip)
> 
> BTW: nft does not allow to create set of integer components:
> https://www.spinics.net/lists/netfilter-devel/msg36817.html
> 
> But there is a way for specify multiple IPs in one rule, eg:
> 
> ```
> nft add rule arp filter input arp plen 4 @nh,96,32 {16909060, 16909061, 16909062} counter drop
> ```
> 
> Where `16909060, 16909061, 16909062` is IPv4 addresses in decimal format
> 
> More info here:
> https://serverfault.com/a/942166/205043

Good news everyone, new nft supports setting ip address for arp filters :

https://bugzilla.netfilter.org/show_bug.cgi?id=1307#c2
