### ISSUE TITLE
etcd&apiserver down under 2-master(HA) configuration

### ISSUE THREAD

**Issue by linanster** [kubernetes/kubernetes#71557]
Hi all,
  I try to set up 2-master(HA) k8s,  the 2 master nodes get Ready, However, "etcd" and "kube-apiserver" on master2(node2) down. Need your help and appreciate your advice.

-----
info:
node1(master):10.249.244.51
node2:(master):10.249.244.52
keepalived vip: 10.249.244.59

[root@node1 ~]# kubectl -s https://10.249.244.51:6443  get pod -n kube-system -o wide    
NAME                            READY   STATUS             RESTARTS   AGE   IP              NODE    NOMINATED NODE
coredns-576cbf47c7-6w88q        1/1     Running            0          27m   10.244.0.2      node1   <none>
coredns-576cbf47c7-vp2ch        1/1     Running            0          27m   10.244.0.3      node1   <none>
etcd-node1                      1/1     Running            0          26m   10.249.244.51   node1   <none>
etcd-node2                      0/1     CrashLoopBackOff   5          13m   10.249.244.52   node2   <none>
kube-apiserver-node1            1/1     Running            0          26m   10.249.244.51   node1   <none>
kube-apiserver-node2            0/1     CrashLoopBackOff   4          13m   10.249.244.52   node2   <none>
kube-controller-manager-node1   1/1     Running            0          26m   10.249.244.51   node1   <none>
kube-controller-manager-node2   1/1     Running            0          13m   10.249.244.52   node2   <none>
kube-flannel-ds-amd64-6bfvj     1/1     Running            0          13m   10.249.244.52   node2   <none>
kube-flannel-ds-amd64-l87zk     1/1     Running            0          24m   10.249.244.51   node1   <none>
kube-proxy-pr887                1/1     Running            0          13m   10.249.244.52   node2   <none>
kube-proxy-qrvk9                1/1     Running            0          27m   10.249.244.51   node1   <none>
kube-scheduler-node1            1/1     Running            0          26m   10.249.244.51   node1   <none>
kube-scheduler-node2            1/1     Running            0          13m   10.249.244.52   node2   <none>
[root@node1 ~]# 
[root@node1 ~]# 
[root@node1 ~]# 
[root@node1 ~]# 
[root@node1 ~]# kubectl -s https://10.249.244.51:6443  logs kube-apiserver-node2 -n kube-system
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
[root@node1 ~]# 
[root@node1 ~]# 
[root@node1 ~]# kubectl -s https://10.249.244.51:6443  logs etcd-node2 -n kube-system              
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)

**Comment by linanster** [comment]
[root@node1 ~]# kubectl -s https://10.249.244.51:6443  get node -n kube-system
NAME    STATUS   ROLES    AGE   VERSION
node1   Ready    master   27m   v1.12.2
node2   Ready    master   12m   v1.12.2

**Comment by linanster** [comment]
resolved myself

**Comment by RUONES** [comment]
> 
> 
> resolved myself

@linanster how did you resolve, just curious?

**Comment by rgarcia89** [comment]
I would be also curious to hear how you resolved the issue as I am seeing the same in my 3 master mode cluster right now. 
@linanster
