### ISSUE TITLE
Node being deleted when network outage encountered

### ISSUE THREAD

**Issue by Michael-Baylis** [kubernetes/kubernetes#71562]
**What happened**:
Occasionally when there is a network hiccup, a node is deleted from the k8s configuration.  When the network recovers, the kubelet service is stuck with 
kubelet_node_status.go:377] Error updating node status, will retry: error getting node "cicsk8s8": nodes "cicsk8s8" not found
and from that point the node is unavailable
When I restart kubelet, it recreates the node and sometimes it is deleted again almost immediately.  I will attach an example kubelet log

**What you expected to happen**:
The node not to be delete and the kubelet service to recover to normal operations after the network is back.

**How to reproduce it (as minimally and precisely as possible)**:
I am unable to to reproduce, happens rarely and inconsistently

**Anything else we need to know?**:
Using Flannel as our network and using the Openstack cloudprovider on some of the nodes,  but not the ones experiencing this problem.
We have 2 nodes running under VMWare,  3 on s390x and 3 under OpenStack.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.2
- Cloud provider or hardware configuration: We have 2 nodes running under VMWare,  3 on s390x and 3 under OpenStack.
Using Flannel as our network and using the Openstack cloudprovider on some of the nodes,  but not the ones experiencing this problem.
- OS (e.g. from /etc/os-release): Various, but the s390x versions experiencing this problem ar Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`): 4.4.0-130-generic
- Install tools: Kubeadm 1.12.2
- Others:

/kind bug

**Comment by Michael-Baylis** [comment]
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.636414   47535 server.go:1013] Started kubelet
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: E1129 13:27:49.641529   47535 kubelet.go:1287] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.653403   47535 server.go:133] Starting to listen on 0.0.0.0:10250
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.662652   47535 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.662910   47535 status_manager.go:152] Starting to sync pod status with apiserver
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.662924   47535 kubelet.go:1804] Starting kubelet main sync loop.
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.662972   47535 kubelet.go:1821] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.663365   47535 volume_manager.go:248] Starting Kubelet Volume Manager
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.682051   47535 desired_state_of_world_populator.go:130] Desired state populator starts to run
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.690898   47535 server.go:318] Adding debug handlers to kubelet server.
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.763129   47535 kubelet.go:1821] skipping pod synchronization - [container runtime is down]
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.763635   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: E1129 13:27:49.763637   47535 kubelet.go:2236] node "cicsk8s8" not found
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:49.847129   47535 kubelet_node_status.go:70] Attempting to register node cicsk8s8
Nov 29 13:27:49 cicsk8s8.hursley.ibm.com kubelet[47535]: E1129 13:27:49.900672   47535 kubelet.go:2236] node "cicsk8s8" not found
Nov 29 13:27:51 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:50.991143   47535 kubelet.go:1821] skipping pod synchronization - [container runtime is down]
Nov 29 13:27:51 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:50.991183   47535 kuberuntime_manager.go:910] updating runtime config through cri with podcidr 10.244.10.0/24
Nov 29 13:27:51 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:50.993979   47535 kubelet_node_status.go:73] Successfully registered node cicsk8s8
Nov 29 13:27:51 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:50.994481   47535 docker_service.go:345] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:10.244.10.0/24,},}
Nov 29 13:27:51 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:51.122234   47535 kubelet_network.go:75] Setting Pod CIDR:  -> 10.244.10.0/24
Nov 29 13:27:51 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:51.719540   47535 kubelet.go:1821] skipping pod synchronization - [container runtime is down]
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.427097   47535 cpu_manager.go:155] [cpumanager] starting with none policy
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.427633   47535 cpu_manager.go:156] [cpumanager] reconciling every 10s
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.429008   47535 policy_none.go:42] [cpumanager] none policy: Start
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671539   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "flannel-cfg" (UniqueName: "kubernetes.io/configmap/91338e19-f3da-11e8-8b04-00505694cd85-flannel-cfg") pod "kube-flannel-ds-s390x-7x4wk" (UID: "91338e19-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671574   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "flannel-token-bxnsq" (UniqueName: "kubernetes.io/secret/91338e19-f3da-11e8-8b04-00505694cd85-flannel-token-bxnsq") pod "kube-flannel-ds-s390x-7x4wk" (UID: "91338e19-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671593   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy" (UniqueName: "kubernetes.io/configmap/9132c950-f3da-11e8-8b04-00505694cd85-kube-proxy") pod "kube-proxy-s390x-9z59z" (UID: "9132c950-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671615   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/9132c950-f3da-11e8-8b04-00505694cd85-xtables-lock") pod "kube-proxy-s390x-9z59z" (UID: "9132c950-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671635   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/9132c950-f3da-11e8-8b04-00505694cd85-lib-modules") pod "kube-proxy-s390x-9z59z" (UID: "9132c950-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671654   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy-token-2652w" (UniqueName: "kubernetes.io/secret/9132c950-f3da-11e8-8b04-00505694cd85-kube-proxy-token-2652w") pod "kube-proxy-s390x-9z59z" (UID: "9132c950-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671672   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "run" (UniqueName: "kubernetes.io/host-path/91338e19-f3da-11e8-8b04-00505694cd85-run") pod "kube-flannel-ds-s390x-7x4wk" (UID: "91338e19-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671688   47535 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "cni" (UniqueName: "kubernetes.io/host-path/91338e19-f3da-11e8-8b04-00505694cd85-cni") pod "kube-flannel-ds-s390x-7x4wk" (UID: "91338e19-f3da-11e8-8b04-00505694cd85")
Nov 29 13:27:52 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:52.671695   47535 reconciler.go:154] Reconciler: start to sync state
Nov 29 13:27:55 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:55.414992   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:55 cicsk8s8.hursley.ibm.com kubelet[47535]: W1129 13:27:55.443669   47535 pod_container_deletor.go:75] Container "5872266cc119bf17b0f667ceebf6bd6e83e39d381baf235629ae40d70d7f7b47" not found in pod's containers
Nov 29 13:27:55 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:55.844730   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:55 cicsk8s8.hursley.ibm.com kubelet[47535]: W1129 13:27:55.884798   47535 pod_container_deletor.go:75] Container "6db95ff6bc221adbc109fb40b1699121b7b4b93bd003e005d0d693c2f506dad9" not found in pod's containers
Nov 29 13:27:56 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:56.852715   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:56 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:56.853028   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:56 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:56.861388   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:57 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:57.902143   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:57 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:57.902513   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:27:58 cicsk8s8.hursley.ibm.com kubelet[47535]: I1129 13:27:58.907693   47535 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
Nov 29 13:28:01 cicsk8s8.hursley.ibm.com kubelet[47535]: E1129 13:28:01.151594   47535 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "cicsk8s8": nodes "cicsk8s8" not found

**Comment by Michael-Baylis** [comment]
the above shows cicsk8s8 not being found,     being registered and then not being found again.
The second restart kept the cicsk8s8 registered.

**Comment by Michael-Baylis** [comment]
so the question is,  what would be deleting the node?  so I could go and look at those logs to determine why

**Comment by changyaowei** [comment]
![image](https://user-images.githubusercontent.com/12136478/49241558-1fe6b680-f443-11e8-8f0d-48555ee5c270.png)
![image](https://user-images.githubusercontent.com/12136478/49241810-ecf0f280-f443-11e8-9820-a06ffae0b7af.png)

When you restart kubelet, two goroutine works. In `syncNodeStatus func`  try to register node, in `fastStatusUpdateOnce` loop, it try to get node info,  before register done, it will always error `node "cicsk8s8" not found` , so it looks like `cicsk8s8 not being found, being registered and then not being found again`

**Comment by Michael-Baylis** [comment]
Thats what I am seeing.  If I do a "watch kubectl get nodes",  I see the node appear briefly and then disappear again,  never to return unless I bouce kubelet again

**Comment by Michael-Baylis** [comment]
Didn't have this problem in v1.10,    only since I jumped to v1.12.2

**Comment by changyaowei** [comment]
In v1.10. not have fastStatusUpdateOnce func

**Comment by Michael-Baylis** [comment]
I am not sure what you are saying?  How does this relate to the fact the node is being deleted?

**Comment by thockin** [comment]
Nodes will be deleted after (I think) 5 minutes if they don't heartbeat.  I also believe it's a known problem that Kubelet does not re-register without being restarted.  If you reboot the node it should be OK?

**Comment by liggitt** [comment]
Kubelet reregister issue is https://github.com/kubernetes/kubernetes/issues/71398

**Comment by Michael-Baylis** [comment]
@thockin Reboot the whole node is the only way to get this to work.
@liggitt That issue does seem to tie in with what I am seeing.  I will continue with that one.

**Comment by Michael-Baylis** [comment]
Then again.
Is it possible to prevent the auto deletion of the Node after 5 mins of no heartbeat?  Just mark the node as not-ready?   We have a fairly static environment,  so nodes that have lost network connectivity will come back eventually.

**Comment by liggitt** [comment]
the only place I see Node objects deleted is when the cloud provider reports the node no longer exists:

https://github.com/kubernetes/kubernetes/blob/d6385cdb610ae513a9814867ba545de1d9428a3d/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L781-L793

https://github.com/kubernetes/kubernetes/blob/d6385cdb610ae513a9814867ba545de1d9428a3d/pkg/controller/cloud/node_controller.go#L280-L302

**Comment by Michael-Baylis** [comment]
Ah, that may be the problem then.    our s390x are native nodes.   I do have 3 nodes on openstack so I can make use of dynamic volume provisioning.

So if the heartbeat is lost and the cloudprovider reports that the node does not exist,  which they never did,  the node is deleted.

Would that be accurate?

**Comment by Michael-Baylis** [comment]
@thockin I came to same conclusion,  build my own version with that section commented out.  Just need to work out how to :-)
Thinking of raising another issue focusing on the incorrect "cloud" assumption, but have to figure out how to word it.
Thank you @thockin and @liggitt for your assistance.
