### ISSUE TITLE
CRI log format needs to define maximum file name length better.

### ISSUE THREAD

**Issue by HackToHell** [kubernetes/kubernetes#71567]
I recently ran into an issue with Fluentd being unable to buffer logs from kubernetes because the length was more than the OS maximum. https://github.com/fluent/fluentd/issues/2195

This might be a problem even in the newer CRI log format as kubernetes names can by upto 253 chars and the CNI defines a log line as 

``` /var/log/pods/<podUID>/<containerName>_<instance#>.log ```

Where both the `containerName` and `instance` can be more than 253 and can hit the OS limit of 255.

Additionally I am not sure of the maximum sizes for containerName and instance. (Related https://github.com/kubernetes/community/issues/814 ). But I am assuming it's 253 from https://kubernetes.io/docs/concepts/overview/working-with-objects/names/.

**Comment by cblecker** [comment]
@kubernetes/sig-node-bugs
