### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed - Invalid Kubernetes API v1 endpoint

### ISSUE THREAD

**Issue by aleks-mariusz** [kubernetes/kubernetes#71571]
**What happened**:

Following #49570 i am having a similar issues, running kubernetes v1.12.3 with the fluentd-addon, with it trying to get kubernetes metadata from the cluster's API-server IP.  I am using fluentd v1.3.0 (latest at the time of this), and latest kubernetes.

and my org has a CA that i have the pub-key deployed on all my master/minion nodes, as well as had it signed the cert that the cluster uses when i bootstrapped the cluster. 

when the fluentd pods start up, they exit with this error:
```
2018-11-29 18:18:45 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint https://10.12.12.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed"
```
which would suggest the certs are not "lining up".  

**What you expected to happen**:
Well, this situation doesn't seem to make sense since poking around _inside the pod_ i see the TLS cert being returned when connecting to the API server IP: 

<details>
<summary>the s_client-provided cert information of the API server within the pod</summary>

```
root@bash-5465db66d7-btqm5:~# openssl s_client -connect 10.12.12.1:443 2>&1 </dev/null | openssl x509 -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4324063523466593868 (0x3c0228dd5e73464c)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = UK, L = London, O = company Ltd, OU = infrastructure, CN = k8s-lab.company.corp, emailAddress = infrastructure@company.com
        Validity
            Not Before: Nov 29 17:10:41 2018 GMT
            Not After : Nov 29 17:57:34 2019 GMT
        Subject: CN = kube-apiserver
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:be:1a:8d:76:8b:de:11:82:a7:ac:39:e2:3c:a1:
[...snip...]
                    27:fb
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Authority Key Identifier:
                keyid:A3:0C:E3:05:47:D5:13:5B:0F:77:3F:26:B8:9C:67:7D:4C:7D:66:4A

            X509v3 Subject Alternative Name:
                DNS:k8lab2bs, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.k8s-lab.company.corp, DNS:api-k8s-lab, DNS:api-k8s-lab, IP Address:10.12.12.1, IP Address:10.12.100.132
    Signature Algorithm: sha256WithRSAEncryption
         5b:29:a7:8c:be:3c:28:83:c6:2a:f8:18:ce:b3:ad:ad:96:0d:

    Signature Algorithm: sha256WithRSAEncryption
         5b:29:a7:8c:be:3c:28:83:c6:2a:f8:18:ce:b3:ad:ad:96:0d:
[...snip...]
         b0:2c:d0:78
```
</details>

And comparing it to the /run/secrets/kubernetes.io/serviceaccount/ca.crt:

<details>
<summary>x509 info from the service-account provided ca.crt</summary>

```
root@bash-5465db66d7-btqm5:~# openssl x509 -text -noout -in /run/secrets/kubernetes.io/serviceaccount/ca.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            4c:00:00:00:c8:7c:5f:b5:24:b7:54:8a:8e:00:00:00:00:00:c8
    Signature Algorithm: sha512WithRSAEncryption
        Issuer: DC = corp, DC = company, CN = company-CORP-CA1
        Validity
            Not Before: Nov 29 17:10:41 2018 GMT
            Not After : Nov 29 17:20:41 2020 GMT
        Subject: C = UK, L = London, O = company Ltd, OU = infrastructure, CN = k8s-lab.company.corp, emailAddress = infrastructure@company.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:9a:80:70:92:a2:d8:37:cb:98:a1:1f:b1:48:1e:
[...snip...]
                    40:71
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
            1.3.6.1.4.1.311.20.2:
                .
.S.u.b.C.A
            X509v3 Subject Key Identifier:
                A3:0C:E3:05:47:D5:13:5B:0F:77:3F:26:B8:9C:67:7D:4C:7D:66:4A
            X509v3 Authority Key Identifier:
                keyid:86:B5:4E:2B:BD:34:AE:52:0B:42:13:D6:EA:D4:58:00:F5:49:AE:3A

            X509v3 CRL Distribution Points:

                Full Name:
                  URI:ldap:///CN=company-CORP-CA1,CN=SEC1BS,CN=CDP,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=company,DC=corp?certificateRevocationList?base?objectClass=cRLDistributionPoint

            Authority Information Access:
                CA Issuers - URI:ldap:///CN=company-CORP-CA1,CN=AIA,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=company,DC=corp?cACertificate?base?objectClass=certificationAuthority

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha512WithRSAEncryption
         0b:e0:5f:14:c0:19:94:0b:97:e4:4c:f6:2c:5a:3c:81:7a:f1:
[...snip...]
```

</details>

So the API server's ISSUER line: 

```
        Issuer: C = UK, L = London, O = company Ltd, OU = infrastructure, CN = k8s-lab.company.corp, emailAddress = infrastructure@company.com
```

actually **matches** the CA provided: 

```
        Subject: C = UK, L = London, O = company Ltd, OU = infrastructure, CN = k8s-lab.company.corp, emailAddress = infrastructure@company.com
```

(i also tried to specify _ca_file_ pointing to /run/secrets/kubernetes.io/serviceaccount/ca.crt, but only if i set _ssl_verify_ to false will the pods start up :-(

It's strange that when i used to build the cluster where it generated self-signed certificates there were no such issues, when trying to do PKi *properly*, i run into errors :-/

**How to reproduce it (as minimally and precisely as possible)**:
provide yoru own ca.crt and ca.key in /etc/kubernetes/pki before running kubeadm init on the cluster

**Anything else we need to know?**:
followed the HA using kubeadm directions on kubernetes's docs site

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.3
- Cloud provider or hardware configuration: linux kvm "baremetal"
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 3.10.0-862.9.1.el7.x86_64
- Install tools: kubeadm

/kind bug

**Comment by heidemn** [comment]
@aleks-mariusz We had a similar problem, with the example [fluentd-daemonset-elasticsearch-rbac.yaml](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch-rbac.yaml) from the **fluentd-kubernetes-daemonset** repo.
Maybe it helps in your case.

The example DaemonSet YAML worked out of the box, but after transforming it to Terraform code, it no longer worked.
The problem was that the token for the fluentd ServiceAccount was not mounted into the Pods.

Using the Terraform Kubernetes provider, `kubernetes_service_account.automount_service_account_token` was `false` by default.
Using kubectl, the same property was `true` by default.

Setting this property to `true` solved the problem.
