### ISSUE TITLE
Better documentation on k8s-etcd version compatibility

### ISSUE THREAD

**Issue by wenjiaswe** [kubernetes/kubernetes#71572]
**What happened**:
We need to a better documentation about the version compatibility between k8s and etcd. I did a quick search and didn't find anything other than historic upgrading issues and PRs, and notes spreading in CHANGELOGs. 

**What you expected to happen**:
Have a clear doc/table on  version compatibility between k8s and etcd

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

/cc @jpbetz @jingyih @gyuho 
/assign @wenjiaswe 
/sig api-machinery

**Comment by liggitt** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/45506, which got autoclosed and had more context

see also https://github.com/kubernetes/website/pull/11060
