### ISSUE TITLE
Pod using subpath with nfs is stuck in terminating

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71584]
**What happened**:
NFS server got restarted and caused the nfs mounts to be stale.  Pod deletion hung with:
```
Error: "error cleaning subPath mounts for volume \"nfs-content\": error reading /var/lib/kubelet/pods/redacted/volume-subpaths/nfs-content/redacted: lstat /var/lib/kubelet/pods/redacted/volume-subpaths/nfs-content/redacted/2: stale NFS file handle"
```

**What you expected to happen**:
I think the [subpath directory traversing](https://github.com/kubernetes/kubernetes/blob/v1.9.7/pkg/util/mount/mount_linux.go#L780) needs to check for a [stale mount](https://github.com/kubernetes/kubernetes/blob/v1.9.7/pkg/volume/util/util.go#L184)

**How to reproduce it (as minimally and precisely as possible)**:
I have not been able to repro the stale nfs mount.  These are the steps I tried:
1. start a nfs-server using https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
2. create a pod using subpath with nfs. write data into the subpath.
3. restart the nfs-server pod
4. Write more data into the subpath
5. delete pod

In my test, the nfs mount is able to recover from the nfs server restarting.  Maybe my next attempt to repro should bring the nfs server down for longer.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
cc @jsafrane

**Comment by jsafrane** [comment]
> I think the subpath directory traversing needs to check for a stale mount

+1, however, I don't like leaking NFS into other parts of Kubernetes.
