### ISSUE TITLE
Azure provider triggers VMSS manual upgrade which restarts all instances at the same time

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#71594]
**What happened**:

We have a v1.10.6 cluster hosted in Azure (deployed with https://github.com/Azure/acs-engine) using `VMSS`  for agent pool and we decided to change the VM Size of the VMSS instances for cost efficiency. The plan was:

 - Change the VMSS VM Size
 - Double the number of instances (the new instances being created with the new VM Size)
 - Drain the old instances
 - Upgrade the old instances to the new VM Size
 - Scale down to the original number of nodes

What actually appened:

 - We changed the VMSS VM Size
 - We doubled the number of instances
 - Kubernetes Azure cloudprovider triggered a `manualupgrade` of the VMSS leading to upgrading all the nodes not matching the new VM Size
 - All services hosted were down due to all the "old nodes" being stopped at the same time for Upgrade

Here the Azure audit log showing that the Service Principal used by the kubernetes cluster Azure provider triggered the manual upgrade:
```json
{
    "authorization": {
        "action": "Microsoft.Compute/virtualMachineScaleSets/manualupgrade/action",
        "scope": "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/k8s4-EUW-dev-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s4-euw-dev-agent-vmss"
    },
    "caller": "<SOME_ID>",
    "channels": "Operation",
    "claims": {
        "aud": "https://management.core.windows.net/",
        "iss": "https://sts.windows.net/<AZURE_TENANT_ID>/",
        "iat": "1543571495",
        "nbf": "1543571495",
        "exp": "1543575395",
        "aio": "42RgYPg3Vf3czm1PjRPl7kz8ZFs/EwA=",
        "appid": "<K8S_AZURE_SERVICE_PRINCIPAL>",
        "appidacr": "1",
        "http://schemas.microsoft.com/identity/claims/identityprovider": "https://sts.windows.net/<AZURE_TENANT_ID>/",
        "http://schemas.microsoft.com/identity/claims/objectidentifier": "<SOME_ID>",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "<SOME_ID>",
        "http://schemas.microsoft.com/identity/claims/tenantid": "<AZURE_TENANT_ID>",
        "uti": "dOjT0Ob3B0OV9ckOFFXjAQ",
        "ver": "1.0"
    },
    "correlationId": "c0ec14e9-0d68-4eed-ab97-6043a2dc50fd",
    "description": "",
    "eventDataId": "00263b46-028d-498b-9264-ba94e20c1b84",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2018-11-30T10:09:31.1754255Z",
    "id": "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/k8s4-EUW-dev-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s4-euw-dev-agent-vmss/events/00263b46-028d-498b-9264-ba94e20c1b84/ticks/636791693711754255",
    "level": "Informational",
    "operationId": "c0ec14e9-0d68-4eed-ab97-6043a2dc50fd",
    "operationName": {
        "value": "Microsoft.Compute/virtualMachineScaleSets/manualupgrade/action",
        "localizedValue": "Manual Upgrade Virtual Machine Scale Set"
    },
    "resourceGroupName": "k8s4-EUW-dev-RG",
    "resourceProviderName": {
        "value": "Microsoft.Compute",
        "localizedValue": "Microsoft.Compute"
    },
    "resourceType": {
        "value": "Microsoft.Compute/virtualMachineScaleSets",
        "localizedValue": "Microsoft.Compute/virtualMachineScaleSets"
    },
    "resourceId": "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/k8s4-EUW-dev-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s4-euw-dev-agent-vmss",
    "status": {
        "value": "Accepted",
        "localizedValue": "Accepted"
    },
    "subStatus": {
        "value": "Accepted",
        "localizedValue": "Accepted (HTTP Status Code: 202)"
    },
    "submissionTimestamp": "2018-11-30T10:09:50.1545164Z",
    "subscriptionId": "<AZURE_SUBSCRIPTION_ID>",
    "properties": {
        "statusCode": "Accepted",
        "serviceRequestId": "03abebf2-7aaf-4195-8e21-fb9c2f48a861"
    },
    "relatedEvents": []
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.6
- Cloud provider or hardware configuration: Azure

/kind bug

**Comment by feiskyer** [comment]
This is a known issue because VMSS API doesn't support configurations for each instance. Hence, Azure cloud provider would do manualupgrade for all instances whenever VMSS model is updated.

@sylr For safety, I suggest you do the manualupgrade step by step for all instances if you have changed the VMSS model.

**Comment by sylr** [comment]
@feiskyer How would I do that ? Once I change the VMSS Size I have just a few minutes before the Azure provider triggers the `manualupgrade` on all "old" instances.

**Comment by feiskyer** [comment]
> Once I change the VMSS Size I have just a few minutes before the Azure provider triggers the manualupgrade on all "old" instances.

oops, didn't notice this is a really active cluster. cloud provider would update all vmss instances whenever there're service or backend changes. Could you add other vmss node pools in the same cluster? In that way, each vmss could be upgraded separately.

**Comment by sylr** [comment]
> Could you add other vmss node pools in the same cluster? In that way, each vmss could be upgraded separately.

What make syou think they won't be also upgraded all at once ?

**Comment by sylr** [comment]
@feiskyer Can you pass this issue internally to the VMSS team at @Azure ?

**Comment by feiskyer** [comment]
@sylr there're plans of supporting LB backends updates for each instance. that should be rollout next year.

**Comment by calvix** [comment]
This seems like really bad design if I want to have full control over I should be able to do that and having separate VMSS for each worker sounds awful.

On AWS its handled properly, where a cloud provider is not meddling with whenever it should or not update the ASG so I wonder why its different on Azure.

Is there a way how to disable this behavior? VMSS already have a way of defining the `updatePolicy` so why its necessary have same logic in azure cloud provider?

**Comment by feiskyer** [comment]
The operation is required for updating LoadBalancer backends, or else, kubernetes service with type LoadBalancer won't work.

We're pending on VMSS new APIs to allow only updating the networkProfile in such cases.

**Comment by mo-saeed** [comment]
@feiskyer Do you have any updates here ?

**Comment by feiskyer** [comment]
The ETA of new VMSS APIs is mid April, and this issue would be fixed after that's available.

**Comment by mo-saeed** [comment]
@feiskyer I installed k8s version 1.13.6 with aks-engine and VMSS worker nodes, when I created a new service of Type loadbalancer, loadbalancer successfully created and VMSS's instances joined the backend-pool but all VMSS instances shown with "No Latest Model", tried to upgrade them manually, it works but after re-joining the LB backend pool they are again "No Latest Model", my question is this normal behaviour and if not do you have any idea what could be the issue here. _this only happens with k8s 1.13.6_

**Comment by feiskyer** [comment]
@mo-saeed yep, this is normal since only the instance is updated instead of vmss.
