### ISSUE TITLE
docs/authorization.md contains incorrect indenting

### ISSUE THREAD

**Issue by hatchan** [kubernetes/kubernetes#7159]
`docs/authorization.md` contains incorrect indenting for the "Policy File Format" properties, which causes the markdown render it as a paragraph instead of a list.

Also the property `namespace` should be `ns` according to the example.

**Comment by mikebrow** [comment]
#dibs

**Comment by mikebrow** [comment]
@hatchan Which example says to use ns as the property name?

**Comment by hatchan** [comment]
@mikebrow I'm guessing this has been resolved since reporting this issue

**Comment by mikebrow** [comment]
kk thx... was about to look at the blame hist.  Cheers.

**Comment by erictune** [comment]
File in question live here now:
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/authorization.md
and it looks fine.
