### ISSUE TITLE
client-go/testing: inconsistent behavior around evictions

### ISSUE THREAD

**Issue by bouk** [kubernetes/kubernetes#71598]
**What happened**:

I'm trying to test Eviction functionality in my program, but running into some inconsistencies around how Evictions are handled in the fake SimpleClient in the client-go testing functionality. Most notably, `client.PolicyV1beta1().Evictions(namespace).Evict` creates a different `Action` from `client.CoreV1().Pods(namespace).Evict`, and both are missing information.

`client.PolicyV1beta1().Evictions(namespace).Evict` issues a `GetAction` with `Verb` set to `Post` (seems to be the only Fake that has this mismatch) on the `eviction` subresource of `pods`. It is missing all the extra information in the eviction, i.e. the `DeleteOptions`.

`client.CoreV1().Pods(namespace).Evict` issues a `CreateAction` on the `eviction` subresource of the `pods` resource. This is wrong, because `evictions` aren't created, they're only posted and handled immediately. The Action is missing a Namespace.

**What you expected to happen**:

I want to be able to add my own reactor to the SimpleClient to handle this special case. I propose we change both cases to a `GenericAction` with `Value` set to the `policy.Eviction`. This will ensure it's not handled by the current SimpleClient ObjectReaction, and makes it so users can implement whatever they want themselves.

I'd be happy to make a PR with these changes.

**How to reproduce it (as minimally and precisely as possible)**:

```
package main

import (
	"fmt"

	policy "k8s.io/api/policy/v1beta1"
	meta "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func main() {
	client := fake.NewSimpleClientset()
	client.CoreV1().Pods("default").Evict(&policy.Eviction{
		ObjectMeta: meta.ObjectMeta{
			Name: "pod-1",
		},
	})
	client.PolicyV1beta1().Evictions("default").Evict(&policy.Eviction{
		ObjectMeta: meta.ObjectMeta{
			Name: "pod-2",
		},
	})

	for _, action := range client.Actions() {
		fmt.Printf("%T%+v\n", action, action)
	}
}
```

Output:

```
testing.CreateActionImpl{ActionImpl:{Namespace: Verb:create Resource:/v1, Resource=pods Subresource:eviction} Name: Object:&Eviction{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:pod-1,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},DeleteOptions:nil,}}
testing.GetActionImpl{ActionImpl:{Namespace:default Verb:post Resource:/v1, Resource=pods Subresource:eviction} Name:pod-2}
```

**Environment**:
git revision of `k8s.io/client-go`: `8abb21031259350aad0799bb42ba213ee8bb3399`

/kind bug

**Comment by liggitt** [comment]
> `client.CoreV1().Pods(namespace).Evict` issues a `CreateAction` on the `eviction` subresource of the `pods` resource. This is wrong, because `evictions` aren't created, they're only posted and handled immediately.

POST requests *are* create requests. It doesn't matter if the object is persisted or not.

**Comment by mbohlool** [comment]
cc @caesarxuchao
