### ISSUE TITLE
Probe httpHeaders "Host" is lost after redirect

### ISSUE THREAD

**Issue by johnraz** [kubernetes/kubernetes#71592]
Hello there,

I did search around and didn't find a report for this already, I hope it's  not a dupe.

**What happened**:
In an HTTP probe definition (readyness or liveness), the custom host header is not set properly after a redirect occurs.

**What you expected to happen**:
Seeing that #18233 states that redirects are weird but allowed, I would expect the custom headers to be maintained after the redirect occurs.

**How to reproduce it (as minimally and precisely as possible)**:
Setup an HTTP service that expects a specific Host header to be used (using Django here) and would return a 400 if the Host doesn't match (for a more detail view at how Django deals with this [read along](https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts)).

Then setup a probe like:

```
livenessProbe:
    httpGet:
        path: /admin/
        port: http
        httpHeaders:
            - name: Host
              value: the-expected-host.tld
```

You should now see in your logs that the first call to the service succeeded with a 301 (or 3XX) which means the Host header was set properly, but that the call to the redirected url will fail with a 400 which means the Host header was not set anymore and makes the probe raise an error.

**Anything else we need to know?**:
In the above test, setting the "path" to the redirected url works and the probe is green.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: intel NUC
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): Linux nuc 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Minikube
- Others:

/kind bug

**Comment by thockin** [comment]
We are calling Go's HTTP client here - is it possible that this is "normal" behavior for Go?  I don't know...

**Comment by johnraz** [comment]
@thockin Seems like an old bug indeed: https://github.com/golang/go/issues/22233 - not sure where to go from there...

**Comment by dims** [comment]
@johnraz want to try attempting a patch using [CheckRedirect](https://golang.org/pkg/net/http/)? code that @thockin mentioned is in https://github.com/kubernetes/kubernetes/tree/master/pkg/probe/http

**Comment by johnraz** [comment]
@dims I can definitely try to submit a PR with that change! Thanks for pointing in the right direction 👍

**Comment by ahg-g** [comment]
I just tested this on GKE and also have a unit test confirming that this is not an issue anymore, I guess HTTP go client has been fixed.

**Comment by johnraz** [comment]
Awesome! looks like losing track of my commitment here was a good investment 😃 thx for the feedback !

**Comment by thockin** [comment]
Awesome.  Looking forward to more tests :)
