### ISSUE TITLE
Kube-Controller-Manager serves insecurely on IPv6 ([::]:<PORT>) (v1.12.0)

### ISSUE THREAD

**Issue by m-no-2017** [kubernetes/kubernetes#71600]
**What happened**: kube-controller-manager starts but listens insecurely on IPv6, even if --secure-port and --bind-address is set

**What you expected to happen**: kube-controller-manager just listens securely when settings are provided

**How to reproduce it (as minimally and precisely as possible)**:
Start a cluster on v1.12.0 and set the systemd as follows:
<pre><code>  --bind-address=127.0.0.1 \
  --kubeconfig=/REDACTED/controller-manager.kubeconfig \
  --cluster-cidr=your-pod-cidr \
  --cluster-name=clustername \
  --cluster-signing-cert-file=/REDACTED/ca.crt \
  --cluster-signing-key-file=/REDACTED/ca.key \
  --controllers=*,bootstrapsigner,tokencleaner \
  --leader-elect=true \
  --profiling=false \
  --root-ca-file=/REDACTED/ca.crt \
  --service-account-private-key-file=/REDACTED/sa.key \
  --service-cluster-ip-range=your-svc-cidr \
  --use-service-account-credentials=true \
  --secure-port=10259 \
  --v=2</code></pre>

**Anything else we need to know?**:
- --kubeconfig is deprecated but the binary does not start without it
- --authorization-kubeconfig is documented where? (I cannot find it in the docs, maybe my fault)
- the cluster bootstraps correctly and network (weave) + dns (coredns) is working
- scheduling of pods work
- csr of nodes get approved and issued

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.0
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release): Ubuntu 18.04.01 LTS
- Kernel (e.g. `uname -a`): 4.15.0-34-generic
- Install tools: self-made (Kelseys Hard-Way guide)
- Others:

/area controller-manager
/sig cluster-lifecycle

**Comment by liggitt** [comment]
you must set `--port=0` to disable insecure serving. unfortunately, the help text telling you this is hidden because the flag is marked as deprecated. opened https://github.com/kubernetes/kubernetes/pull/71601 to fix this and will pick to 1.13.x / 1.12.x
