### ISSUE TITLE
Kubectl - Introduce "custom-columns" variant to add additional columns to output

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#71612]
Currently, `kubectl get` supports `--custom-columns` as one of its output format flags. The behavior of this flag allows a user to specify a comma-delimited list of `COLUMN_NAME` mapped to a jsonpath value: `COLUMN:.metadata.name`.

The problem with the current behavior is that only the columns that are specified are shown in the final output printed to the screen. In the example above, only the following information would be presented to the user:

```
$ kubectl get pod my-pod --custom-columns=COLUMN_NAME=.metadata.name
COLUMN_NAME
my-pod
```

This behavior can be enhanced by introducing a new variant of the `--custom-columns` flag that would *add* the user-provided column-values to the normal human-readable output of the command:

```
$ kubectl get pod my-pod --extra-columns=CUSTOM_COLUMN=.metadata.name
NAME     READY     STATUS    RESTARTS   AGE   CUSTOM_COLUMN
my-pod   1/1       Running   0          28s   my-pod
```

/kind feature

cc @smarterclayton @soltysh @seans3 

/sig cli

**Comment by smarterclayton** [comment]
I think this would be a lot like `-L`.  I would want it to be easy to add ("I like what you have, but I want this one more column").  I would probably lean more towards a syntax like:

```
... -C RV=.metadata.resourceVersion
```

It's ok to force me to use `-C` multiple times

**Comment by mattmelgard** [comment]
I don't know if this is something that's been considered already but you also might be able to just integrate this into the custom-columns flag by doing something like `--custom-columns=default,CUSTOM_COLUMN=.metadata.name` where `default` refers to the set of default columns that are provided.

**Comment by smarterclayton** [comment]
As we deal more with CRDs it's likely we'll hit this more often, which
potentially justifies a shorter / friendlier variant (just like -L).  It is
definitely an option to use the form you mention, although we'd have to be
careful about explaining it, and its discoverability would be low.  I would
guess most users just want to add a column, they don't want to define a
custom set, but that's something we should validate.

**Comment by mattmelgard** [comment]
@smarterclayton, sounds good to me. Would it be okay if I assigned this to myself then? I'm newer to contributing but I think this might be something I could handle.

**Comment by soltysh** [comment]
@mattmelgard I'm also leaning towards what Clayton proposes, since that's better UX. Be warned this functionality has to work with server-side printing mechanism, since that's the new default and might cause you some problems. It would be nice if you could show up on one of our sig-cli calls (next one Jan 16th) and give a short description of the proposed feature. Since this is a new feature it will need to be properly tracked for a 1.14 release. If in doubt feel free to ping me on slack.
/assign @mattmelgard

**Comment by soltysh** [comment]
@mattmelgard it looks like I can't assign that to you, so I'll assign this to myself for now and so that I can easily track this :smile: 
/assign @soltysh

**Comment by mattmelgard** [comment]
@soltysh sounds good and thanks for the update! Sorry for the issue assignment trouble, I totally forgot that you have to be a collaborator/member for that.

I'll make sure to drop by the next SIG meeting and follow up with you on Slack if I have any hangups.

**Comment by sushobhan78** [comment]
When I issue "kubectl get pods --all-namespaces -o wide", I see the following columns being listed - namespace,name,ready,status,restarts,age,ip,node,NOMINATED NODE,READINESS GATES

How do I use "-o custom-columns" to list all the columns except the last two columns?

**Comment by Jancis** [comment]
`-o custom-columns=:.metadata.namespace,:.metadata.name,:.metadata.ready, ...`

**Comment by ean5533** [comment]
Any chance of this getting picked back up? I'm another use case for "I just want to add one additional custom column, not replace the whole output".

**Comment by its-dave** [comment]
I'd also like to see this issue re-opened, as currently there's no way (that I can tell) to have the `AGE` column and a custom column appear in the same output

**Comment by oguzyildiz1991** [comment]
@ean5533 @its-dave would they get any notifications if the replies got many upvotes after the issue was closed? I wonder if we should create a new issue instead

**Comment by howardjohn** [comment]
Strong +1 to adding this - its non trivial to compute the pod "ready" column as well

**Comment by howardjohn** [comment]
I've opened a PR for this: https://github.com/kubernetes/kubernetes/pull/102819
