### ISSUE TITLE
kubelet panic: concurrent map write

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#71614]
**What happened**: kubelet paniced due to a concurrent map write

**What you expected to happen**: kubelet should not panic

**How to reproduce it (as minimally and precisely as possible)**: I'm seeing this running hack/ci/e2e.sh in https://sigs.k8s.io/kind

**Anything else we need to know?**: Logs are here: 

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel/4622

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel/4622/artifacts/logs/kind-1-control-plane/kubelet.log

**Environment**: `kind` cluster (kubernetes running in a docker container)
- Kubernetes version (use `kubectl version`):  `v1.14.0-alpha.0.752+3156df3e806cb8`
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): Ubuntu (in a container)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

/kind bug

**Comment by BenTheElder** [comment]
the panic alone is here: https://gist.github.com/BenTheElder/f02da3f5473e32aa7fc3cb83db1a10fe

**Comment by BenTheElder** [comment]
looks like one of the writes is here:
https://github.com/kubernetes/kubernetes/blob/3156df3e806cb8bf468845b37eec939dee52a1d8/pkg/kubelet/remote/remote_runtime.go#L240

I don't see a mutex or anything being held. not sure where the other write was yet..

**Comment by mtaufen** [comment]
That delete looks like it merged yesterday: https://github.com/kubernetes/kubernetes/pull/66308
