### ISSUE TITLE
The header on the conformance document should show proper release information.

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#71627]
**What happened**:
The Conformance Document currently has a static header that is displayed from a file. The release information in the header should reflect proper release number so that the document reflect the current state.

**What you expected to happen**:
Should show proper current release information

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/kind bug

**Comment by brahmaroutu** [comment]
#70626 in reaction to @spiffxp comments 
  cf_header.md is still hardcoded to mention v1.9 at the top, could we parameterize this?

**Comment by imkin** [comment]
This seems to have been addressed at https://github.com/kubernetes/kubernetes/pull/70626 
Should we just close this?

**Comment by spiffxp** [comment]
No, #70626 specifically did _not_ address this issue, this should stay open.  See https://github.com/kubernetes/kubernetes/pull/70626#issuecomment-490144809
