### ISSUE TITLE
Let kublet / kubeadm handle downloading images / configure insecure repositories, not docker

### ISSUE THREAD

**Issue by Xnyle** [kubernetes/kubernetes#71639]
**What would you like to be added**:

Let kublet handle downloading images, not the runtime (currently docker).
Extend the deployment/image config so that image is an url where http:// means: yes, i want to download it from an insecure repo.

**Why is this needed**:

Im failing to understand, why in order to use my own (dev,insecure) image registry, i have to configure docker on every node to know about it / accept it.

From my point of view, I'd like to configure everything via kubeadm/helm/yaml files. And this includes where image come from.
I also would like to configure if I want a particular "insecure" image on a deployment basis, not globally in some obscure docker way.
I don't want to care about how docker or later rkt is actually doing things.

Kubelet should configure docker for me after i told k8s what i want to do via yaml files.

Furthermore as far as I understand it right now, the current way, that docker manages downloading the images, it cannot download them from a non exposed cluster ip?

/sig architecture

/kind feature

**Comment by liggitt** [comment]
That would break the boundary between the kubelet and the container runtime. The kubelet should not be configuring implementation details of container runtimes, only interacting with them via the container runtime interface API. 

If you wanted to configure docker in a particular way on all your nodes (like adding an accepted insecure registry address or CIDR, or adding in trust roots to the docker CA dir, you may be able to do so by running a privileged daemonset pod across all nodes, but in-tree code in the kubelet to reconfigure particular container runtimes is a non-goal. 

/close
