### ISSUE TITLE
Issues with k8s networkpolicy and metrics-server

### ISSUE THREAD

**Issue by olivejing** [kubernetes/kubernetes#71649]
Hi, 

Kubernetes v1.11.2
calico: v3.1.3
metrics-server: v0.2.1
For k8s cluster, there are three control nodes: control-01, control-02, and control-03. metrics-server pod runs on control-02.
For k8s cluster, there are three control nodes: control-01, control-02, and control-03. metrics-server pod runs on control-02.
```
[root@paas7-control-02 ~]# kubectl get pod -n kube-system -o wide | grep metrics
metrics-server-5cdb5f7dc6-bjqjh            2/2       Running   0          11d       192.168.235.202   paas7-control-02   <none>
```
networkpolicy config:
```
[root@paas7-control-02 ~]# kubectl get networkpolicy -n kube-system kubernetes-services -o yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: 2018-11-18T18:35:00Z
  generation: 1
  name: kubernetes-services
  namespace: kube-system
  resourceVersion: "8512"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/networkpolicies/kubernetes-services
  uid: a836b5c8-eb60-11e8-84ed-fa163e53f369
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network-policy: kube-system
    - namespaceSelector:
        matchLabels:
          network-policy: paas
  podSelector: {}
  policyTypes:
  - Ingress
```
when i run kubectl command on control-01/control-03, it printed 504 timeout, example:
kubectl get node -v 9:
```
I1130 09:20:55.200467   20224 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.11.2 (linux/amd64) kubernetes/bb9ffb1" 'https://172.16.1.8:8443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I1130 09:21:25.204066   20224 round_trippers.go:405] GET https://172.16.1.8:8443/apis/metrics.k8s.io/v1beta1?timeout=32s 504 Gateway Timeout in 30003 milliseconds
```
kubectl top node -v 9:
```
I1130 09:22:40.529049   30928 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.11.2 (linux/amd64) kubernetes/bb9ffb1" 'https://172.16.1.8:8443/apis/metrics.k8s.io/v1beta1/nodes'
I1130 09:23:10.530977   30928 round_trippers.go:405] GET https://172.16.1.8:8443/apis/metrics.k8s.io/v1beta1/nodes 504 Gateway Timeout in 30001 milliseconds
I1130 09:23:10.531583   30928 round_trippers.go:411] Response Headers:
I1130 09:23:10.531591   30928 round_trippers.go:414]     Date: Fri, 30 Nov 2018 09:23:10 GMT
I1130 09:23:10.531597   30928 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I1130 09:23:10.531601   30928 round_trippers.go:414]     Content-Length: 135
I1130 09:23:10.531640   30928 request.go:897] Response Body: {"metadata":{},"status":"Failure","message":"Timeout: request did not complete within 30s","reason":"Timeout","details":{},"code":504}
I1130 09:23:10.531900   30928 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server was unable to return a response in the time allotted, but may still be processing the request (get nodes.metrics.k8s.io)",
  "reason": "Timeout",
  "details": {
    "group": "metrics.k8s.io",
    "kind": "nodes",
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Timeout: request did not complete within 30s\",\"reason\":\"Timeout\",\"details\":{},\"code\":504}"
      }
    ]
  },
  "code": 504
}]
```
when i run kubectl command on control-02 which runs metrics-server pod, sometimes it runs well, sometimes run failed with 503 error:
kubectl top node -v 9:
```
I1130 09:25:17.482210   28925 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.11.2 (linux/amd64) kubernetes/bb9ffb1" 'https://172.16.1.12:8443/apis/metrics.k8s.io/v1beta1/nodes'
I1130 09:25:17.482908   28925 round_trippers.go:405] GET https://172.16.1.12:8443/apis/metrics.k8s.io/v1beta1/nodes 503 Service Unavailable in 0 milliseconds
I1130 09:25:17.482928   28925 round_trippers.go:411] Response Headers:
I1130 09:25:17.482953   28925 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I1130 09:25:17.482966   28925 round_trippers.go:414]     X-Content-Type-Options: nosniff
I1130 09:25:17.482974   28925 round_trippers.go:414]     Content-Length: 20
I1130 09:25:17.482981   28925 round_trippers.go:414]     Date: Fri, 30 Nov 2018 09:25:17 GMT
I1130 09:25:17.482998   28925 request.go:897] Response Body: service unavailable
I1130 09:25:17.483187   28925 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server is currently unable to handle the request (get nodes.metrics.k8s.io)",
  "reason": "ServiceUnavailable",
  "details": {
    "group": "metrics.k8s.io",
    "kind": "nodes",
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "service unavailable"
      }
    ]
  },
  "code": 503
}]
```
After adding ipblock in networkpolicy, it worked well, but then deleted ipblock in networkpolicy, it still works. 
```
   - ipBlock:
        cidr: 172.16.1.0/24
```
why it reponsed 504 and 503 error code when using the networkpolicy without above ipblock?
when i deleted ipblock in networkpolicy, the kubectl still works. the networkpolicy does not become effective until pod restart.

/sig cli
/sig network
/triage support

**Comment by thockin** [comment]
@caseydavenport

**Comment by thockin** [comment]
Does it allow traffic from pods on the node, or just the node itself?

**Comment by caseydavenport** [comment]
It allows traffic from the node itself. But host networked pods are currently indistinguishable from the host itself.

**Comment by thockin** [comment]
Do we know that this is the case here?  @olivejing isthat what's happening?

**Comment by olivejing** [comment]
what is conntrack entry time? how long does it keeps? I did test, and it seems like that the conntrack entry did not timeout.
After deleting ipblock in networkpolicy and waiting for 24 hours, the networkpolicy still does not block the traffic from node-01/03 to metrics-server(runs on node-02) except restarting metris-server.

**Comment by tellxp** [comment]
sometimes, when i use kubectl top node
```bash
kubectl top node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
```
Error was promoted. 
Continue to execute kubectl top node, I'll get status.

**Comment by menardorama** [comment]
Hi did you solved your issue ?
I am getting the same behaviour, don't know what to do

**Comment by tellxp** [comment]
@menardorama 
I got this error because of using proxy when initializing kubernetes master.
```shell
vi /etc/kubernetes/manifest/kube-apiserver.yaml
```
after deleting proxy env, everything is fine.

**Comment by caseydavenport** [comment]
> Do we know that this is the case here?

We don't _know_ that's the case here. 

> After deleting ipblock in networkpolicy and waiting for 24 hours, the networkpolicy still does not block the traffic from node-01/03 to metrics-server(runs on node-02) except restarting metris-server.

I think this would be a signal that it is likely something else going on.

> when i run kubectl command on control-02 which runs metrics-server pod, sometimes it runs well, sometimes run failed with 503 error:

To summarize where we are now, this sounds like you're always able to access the metrics server from `control-02`, but not from `control-01` or `control-03` unless the policy is modified to allow from the IPs of those nodes, which is expected. 

However, we're expecting that removing that IPBlock which allows `control-01` and `control-03` should revert us to the original state, where those nodes cannot access the metrics-server.

Restarting the metrics server fixes it, which makes me suspicious of connection tracking, but I guess the thing to check would be whether Calico has updated the iptables on `control-02` or not after deleting that ipBlock. Could you compare the output of `iptables-save` with and without the ipBlock? And then again after restarting the metrics server?
