### ISSUE TITLE
Scheduler's predicates should be matched against kubelet

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#71662]
**What would you like to be added**:
Make `GeneralPredicates` a MUST have predicate for scheduler.

**Why is this needed**:
Admin could configure scheduler's predicates. Take a extremely special case for example, we just configures `PodFitsHostPorts` predicates as following:

```
$ cat scheduler-policy.yaml
{
  "kind" : "Policy",
  "apiVersion" : "v1",
  "predicates" : [
      {"name" : "PodFitsHostPorts"}
    ],
   "priorities" : [
	{"name" : "MostRequestedPriority", "weight" : 100}
    ]
}
```
Suppose there are two kubelet nodes with same allocatable resource(kubelet A has 1 cpu and 500Mi left for allocating, kubelet B has 5 cpu and 2048Mi left for allocating), then user creates a deployment whose pod resource request is 3 cpu 1024Mi.  

According to the configure policy, scheduler will schedule the pod to kubelet A which does not have sufficient resource actually, because it just uses predicate `PodFitsHostPorts`. And kubelet will use `pkg/kubelet/lifecycle/predicates#Admit`(which calls `GeneralPredicates`) to admit, then rejects it because there is no sufficient resource.

The controller finds the pod rejected by kubelet, and creates a new pod, scheduler will schedule it to kubelet A again according to its policy. And kubelet A will reject it again.

The root cause is that scheduler use predicates configured by admin, and kubelet uses 
stable predicates, e.g. `GeneralPredicates`, they might not be matched.

As discussed in https://github.com/kubernetes/kubernetes/issues/67874, should we make GeneralPredicates as MUST in scheduler policy?

/kind feature

**Comment by hex108** [comment]
/sig scheduling
/assign @hex108 
cc @resouer

**Comment by wgliang** [comment]
Very good proposal and question.
IMO, GeneralPredicates should be the default predicates outside of the scheduler policy.

**Comment by k82cn** [comment]
Regarding to PR, please try `RegisterMandatoryFitPredicate`; I'm ok to enhance that.
