### ISSUE TITLE
Kubernetes apiserver cors-allowed-origins misconfiguration

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#71669]
## Summary
A list of allowed origins can be supplied to the Kubernetes apiserver at runtime to support Cross-Origin Resource Sharing (CORS). Documentation states that this list "can be a regular expression to support subdomain matching"; however, every item in the list is treated as a regular expression in the CORS request handling middleware. Further, documentation and test cases do not contain examples of safe regular expressions.

Because of this, if a user provides a valid origin, such as "https://www.example.com", it would be possible for an invalid origin to bypass the intended control, using an origin such as "https://www.example.com.evil.com". For the user to protect themselves from this issue, they would need to supply a valid regular expression that contains the meta-characters needed to mark the end of the provided origin (i.e. "$").

The impact of this issue would be dependent on the authentication mechanisms in use. For example, cookie or basic authentication would allow an attacker to submit requests and read responses within the context of the application consumer; however, the use of a JWT or something similar would likely not have an impact, as these authentication mechanisms could not be abused without an attacker knowing the user's credentials. Some far-fetched scenarios could include the use of easy-to-guess credentials and an application and domain that is on a network location that an attacker could not contact directly.

This should be resolved to prevent any future issues in the Kubernetes ecosystem.

## Mitigation
A proper solution should protect users from themselves. There are a couple of routes that could be taken to resolve this issue.
* [ ] Adjust documentation to reflect that all items are treated as a regular expression, and that items not containing and matching end meta-character could result in security issues. Additionally, adjust test cases and documentation to show secure examples.
* [ ] Append a matching end meta-character to each item supplied from the user.
* [ ] Attempt to identify when a regular expression is provided and only treat those as regular expressions.

## Credit
This issue was identified by Tom Steele of Atredis Partners.

## References
* https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
* https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/staging/src/k8s.io/apiserver/pkg/server/filters/cors.go

/kind bug
/area security
/sig api-machinery

**Comment by mbohlool** [comment]
@cheftako @liggitt
