### ISSUE TITLE
kubelet - How to avoid pod to be evicted in node pressure？，I'm a little confused？

### ISSUE THREAD

**Issue by gosoon** [kubernetes/kubernetes#71661]
Kubernetes v1.8.1

I've already tested when kubelet use ‘----eviction-hard=’  flag，notice that there's only a key here and no value，then only tested node disk is full（/ and /home used is 100%，this is equivalent to
nodefs.available=100%）pod not eviction, and i do not see pressure status use `kubectl describe node xxx` ，but I'm still wondering if this is standard practice, and it looks really weird。

/kind feature

**Comment by gosoon** [comment]
@vishh 
![image](https://user-images.githubusercontent.com/31582214/49575447-aa687200-f97d-11e8-9ad6-587bb50ce3f1.png)

kubernetes/cmd/kubelet/app/server.go

Sorry to bother you，I would like to ask if the comment here means that  ‘----eviction-hard=’ flag can be used  in kubelet config?

**Comment by vishh** [comment]
Yes, the flag should work. cc @dashpole

**Comment by gosoon** [comment]
OK，thanks.

**Comment by B8kingS0ga** [comment]
for version 1.11.3, if I didn't use that flag, it will have some default value when running? I didn't find any clue about that default hard eviction default value
