### ISSUE TITLE
prevent unhealthy pod from deployment

### ISSUE THREAD

**Issue by sarkistlt** [kubernetes/kubernetes#71689]
I was trying to find some alternative for docker-swarm rollback command, which allow you to specify rollback strategy in deployment file. In k8s ideally it should use`readinessProbe`, and if didn't pass`failureThreshold` it should rollback, before starting deployment of the next pod (to avoid downtime).

Currently in my deployment script I'm using hook `kubectl rollout status deployment $DEPLOYMENT_NAME || kubectl rollout undo deployment $DEPLOYMENT_NAME`, which works, but it's not ideal because first rollout command will trigger error way after unhealthy pod will be deployed and healthy one will be destroyed which will cause downtime.

Ideally it shouldn't even kill current pod before new one will pass readinessProbe

**Comment by faraazkhan** [comment]
Have you tried setting `spec.rollingUpdate.maxUnavailable: 0%` in your deployment, this will force all new pods to come up and be ready before old pods are retired. If new pods are unhealthy, the rollout will fail and you can undo the deployment.

**Comment by sarkistlt** [comment]
@faraazkhan yes I think this is what I'm looking for, thanks!
