### ISSUE TITLE
PR template is slightly unclear

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#71685]
**What happened**: The PR template is a little unclear to new contributors.

EG:
```md
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
```

If I understand what "uncomment" is, and leave it on it's own line I get:
```
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
 /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
```
which has two problems:
- I probably left the space after the `>` (so the bot regex won't match)
- I probably didn't put a newline before the uncommented line, which is necessary for it to not just continue to be a comment block:

---

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
 /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

--- 

vs

---

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

---

Another issue is in this bit:
```
**Does this PR introduce a user-facing change?**:
<!--  
If no, just write "NONE".
If yes, a release note is required:
Enter your extended release note in the block below. If the PR requires additional action from users switching to the new release, include the string "action required".
2. 
-->
```release-note

```

We should probably make this something like a literal:
```release-note
NONE
```

If you're not an experienced contributor, it's not very clear where you should write "NONE" and what kind of quoting you should use, etc.

**What you expected to happen**: I hope for the PR template to be a little more obvious and easy to use

**How to reproduce it (as minimally and precisely as possible)**: create a new PR 🙃 

**Anything else we need to know?**:

/sig contributor-experience

cc @cblecker @nikhita 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by paralika** [comment]
I would like to work on this issue.

**Comment by cben** [comment]
#72606 was an improment but many of the original observations still stand.
Here's what I found looking at 75 latest PRs (~67 human-written ones if you discount 8 "Automated cherry pick"):

### Few people uncomment & retain the rest

The instruction to "uncomment only one /kind line" seems to suggest keeping all the other options present with `> ` prefix, but few people do that!  I found just 7, of which:

- 2 PRs retained that whole section of the template, not picking a kind at all.  1 of these still got kind label magically set by the bot (possibly from linked issue?)

  I confirmed (tip: ⋯ -> Quote reply lets you see the markdown source) these were NOT people that removed `>` but forgot newline, getting bitten by markdown "lazy continuation" rule — they retained `>` on all lines.

- 3 PRs uncommented 1 line.
- 2 PRs uncommented multiple lines, resulting in multile kind/... labels! Example:

  > **What type of PR is this?**
  > 
  > > Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
  > > /kind api-change
  > > /kind bug
  > 
  > /kind cleanup
  > /kind deprecation
  > 
  > > /kind design
  > > /kind documentation
  > > /kind failing-test
  > 
  > /kind feature
  > 
  > > /kind flake

  I don't know if you'll want to encourage "Uncomment one or more", or want to keep it a "hidden feature" for experienced users?
  However, from the (secondary) angle "template teaches people how the project/infrastructure works", the "only one" wording is slightly misleading — it obscures the fact /kind just sets a label, similar to /area, /sig etc. (and from what I saw, multiple areas or SIGs are common?)

### Most people delete the irrelevant lines, leaving only something like:

> **What type of PR is this?**
> 
> /kind bug

One hypothesis is people feel leaving the rest is noise that detracts from writing & reading the description?  
Weak evidence that's not the _only_ motivation: a few (didn't count, I'd say ~3) retained the instructions line, which is clearly noise, e.g.:

> **What type of PR is this?**
> 
> > Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> 
> /kind cleanup
> 

Another hypothesis: people are not sure what "uncomment" means precisely / don't trust it / discover the markdown lazy-continuation problem themselves.  Removing the ones you want is intuitively more robust.
I don't think we can measure this, but see below.

### Some people delete the options they don't want, but retain the `> `

Found 3 of these, these are actual failures of the process!
*~5% of people took the effort to choose a kind but didn't understand the instructions :crying_cat_face:*

#92178 (bot assigned kind/cleanup anyway, not sure how)

> **What type of PR is this?**
> 
> > Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> > /kind cleanup
> 

#92082 (needs-kind)

> **What type of PR is this?**
> 
> > /kind cleanup
> 

#92132 (needs-kind)

> **What type of PR is this?**
> 
> > Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> > /kind bug
> > /kind documentation
>

**Comment by cben** [comment]
### Suggestions

It seems delete-all-irrelevant mechanic is better than "uncomment" mechanic.  It avoids markdown pitfall, the end result has less noise, and most people choose it anyway.

What if the template had them without `> ` prefixes?
This would prevent mistakes of the last kind, where `>` prevented bot from seeing contributor's choice!

`````markdown
**What type of PR is this?**
> Please leave only relevant line(s), delete the rest:

/kind api-change
/kind bug
/kind cleanup
/kind design
/kind documentation
/kind failing-test
/kind feature
/kind flake
`````

A downside is that when somebody is lazy / misses this step, they'll create PRs with ALL kind/ labels :worried: 

Is the bot smart about /commands inside fenced blocks?  Or HTML comments?  If yes, could use them as a signal that you made a conscious choice:

`````markdown
**What type of PR is this?**
<!--
Copy the relevant line(s) outside this comment block:

/kind api-change
/kind bug
/kind cleanup
/kind design
/kind documentation
/kind failing-test
/kind feature
/kind flake
-->
`````

#### Checklist?

I've also seen projects that use checklists in templates:
`````markdown
**What type of PR is this?**
> Change `- [ ]` to `- [x]` in the desired line(s):

- [ ] /kind api-change
- [ ] /kind bug
- [ ] /kind cleanup
- [ ] /kind design
- [ ] /kind documentation
- [ ] /kind failing-test
- [ ] /kind feature
- [ ] /kind flake
`````
downsides:
- Would require bot support to understand it.
- It's slightly worse on the "template teaches people how the project/infrastructure works" angle — you won't learn from that these are regular /commands you can just write wherever.
- Misses on benefits of "delete" mechanic.  People will likely delete anyway, with same mild confusion about two-ways-to-do-it.

#### Delete + uncomment?
`````markdown
**What type of PR is this?**
> Remove leading `>` from relevant `/kind` line(s), delete the other lines:
>
>/kind api-change
>/kind bug
>/kind cleanup
>/kind design
>/kind documentation
>/kind failing-test
>/kind feature
>/kind flake
`````

Well, this was too many words to suggest such small tweak :laughing:, but:

1. Explains exactly what to do, rather than vague "uncomment".  Not sure if this will reduce mistakes of the last kind.
2. Removed space between `>/kind` avoids risk of leaving space mentioned in OP, without having to explain it.
3. Encourages removing the rest => less worries, no markdown pitfall.

**Comment by cben** [comment]
OK, that answers the question about bot & fenced blocks :grin: ^^^^^

/remove-kind api-change
/remove-kind cleanup
/remove-kind documentation
/remove-kind failing-test
/remove-kind feature
