### ISSUE TITLE
Should fix typos like limitting

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#71683]
**What happened**:
There are some files and comments using `limitting` and `limitted`, but these words are typos. 

**What you expected to happen**:
Should rename them with `limiting` and `limited`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master branch
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig cli

**Comment by yue9944882** [comment]
no need for a dedicated issue for typos, just take it please

/close
