### ISSUE TITLE
Can write IP Address in ingress's host

### ISSUE THREAD

**Issue by weilai201** [kubernetes/kubernetes#71695]
I depoy my ingress-nginx controller use 'hostNetwork: true'.
When I do not configure the 'host' in my ingress.yaml file. Now, I can visit my app use the host ip (such as 'http://192.168.56.201/app/index.html') where the ingress-nginx-controller pod deployed. 
But i found the 'session affinity' cannot take effect. So I read the source code of ingress-nginx. I found it use the http request header 'Host'  to choose the peer. In ingree-nginx , if you cannot configure 'host', the server_name is '\_'. So when you use IP to visit your app, the request header of Host is your IP address. The ip is not equal '\_'. So I think the 'session affinity' cannot take effect.

Should the host can configure IP Address in ingress? 

My kubernetes version is : 1.11.4
Ingress nginx version is : 0.21.0

/sig ingress-controller

**Comment by Shnatsel** [comment]
As far as I understand, this is a feature request for ingress-nginx. If so, it should be filed on this repository instead: https://github.com/kubernetes/ingress-nginx

If I am mistaken and you're proposing a change in the core Kubernetes, please elaborate further on what exactly is the problem and also comment `/sig network` to get it assigned to the appropriate Kubernetes special interest group.

**Comment by thockin** [comment]
I don't think you want to do this because a single Ingress controller can host several Ingresses.

Either way, this should be filed against ingress-nginx
