### ISSUE TITLE
k8s api not available during nodepool with autoscaling add/remove node

### ISSUE THREAD

**Issue by unludo** [kubernetes/kubernetes#71693]
**What happened**:

Each time a node is added to a nodepool, the cluster enters upgrading status. During this time, the kubernetes api is not available, even for k8s system itself.
For example: k8s.io/dns/pkg/dns/dns.go:192: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused
This means that the GKE console can't show the worloads.
Any call to the k8s api fails.
This lasts for more than one minute depending on the load 

**What you expected to happen**:
No k8s api downtime

**How to reproduce it (as minimally and precisely as possible)**:

1/ create a cluster - wait for its availability
2/ create a nodepool inside with autoscaling on
3/ create a pod with node selector corresponding to this nodepool

result is node creating, cluster shows as "upgrading" and all the errors.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3-gke.18
- Cloud provider or hardware configuration: GKE. 
- OS (e.g. from /etc/os-release): Nodepools are with machine type ubuntu whereas cluster is in google Cos
- Kernel (e.g. `uname -a`):
- Install tools: ansible, using gcloud command
- Others:

/kind bug

**Comment by unludo** [comment]
@kubernetes/sig-api-machinery-bugs
@kubernetes/sig-autoscaling-bugs
@kubernetes/sig-gcp-bugs

**Comment by lavalamp** [comment]
Please file a support request: https://cloud.google.com/kubernetes-engine/docs/support

It's not clear from this report what has gone wrong, but I suspect it is not a kube-apiserver problem. Support can help you more.

(It is possible the support request will eventually be routed to me or my team but then we will have the necessary context to diagnose.)
