### ISSUE TITLE
Failed to start ContainerManager failed to get rootfs info: unable to find data in memory cache

### ISSUE THREAD

**Issue by xuxiaosen** [kubernetes/kubernetes#71704]
Hi all:
  I have used systemctl to start kubelet(version 1.12.3, 1.11.1 were both tested), but it never start successful.

systemctl -xeu kubelet log shows:
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.466504   46672 container.go:507] Failed to update stats for container "/system.slice/systemd-udev-trigger.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/systemd-udev-trigger.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.466799   46672 container.go:507] Failed to update stats for container "/docker": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/docker/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.466845   46672 container.go:507] Failed to update stats for container "/system.slice/ipmi.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/ipmi.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.467017   46672 container.go:507] Failed to update stats for container "/system.slice/rhel-dmesg.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/rhel-dmesg.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.467098   46672 container.go:507] Failed to update stats for container "/system.slice/khotfix.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/khotfix.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.467454   46672 container.go:507] Failed to update stats for container "/system.slice/sshd-keygen.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/sshd-keygen.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.468227   46672 container.go:507] Failed to update stats for container "/system.slice/lvm2-lvmetad.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/lvm2-lvmetad.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: W1203 21:33:42.468574   46672 container.go:507] Failed to update stats for container "/system.slice/systemd-remount-fs.service": failure - /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/systemd-remount-fs.service/cpuacct.stat is expected to have 4 fields, continuing to push stats
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: E1203 21:33:42.517783   46672 kubelet.go:2236] node "g88d03421.na61" not found
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: I1203 21:33:42.557574   46672 kubelet_node_status.go:279] Controller attach/detach is disabled for this node; Kubelet will attach and detach volumes
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: I1203 21:33:42.559132   46672 cpu_manager.go:155] [cpumanager] starting with none policy
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: I1203 21:33:42.559141   46672 cpu_manager.go:156] [cpumanager] reconciling every 10s
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: I1203 21:33:42.559150   46672 policy_none.go:42] [cpumanager] none policy: Start
Dec 03 21:33:42 g88d03421.na61 kubelet[46672]: F1203 21:33:42.559165   46672 kubelet.go:1359] Failed to start ContainerManager failed to get rootfs info: unable to find data in memory cache

running command:
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --enable-controller-attach-detach=false --fail-swap-on=false

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.3, v1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):3.10.0
- Install tools:
- Others:

/kind bug

**Comment by WanLinghao** [comment]
Can you print the dir the log warning about.
For example 
ls -al  /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/systemd-udev-trigger.service/cpuacct.stat

**Comment by xuxiaosen** [comment]
> Can you give more info about the dirs the log refers
> For example
> ls -al /sys/fs/cgroup/cpuset,cpu,cpuacct/system.slice/systemd-udev-trigger.service/cpuacct.stat

ls -al  /sys/fs/cgroup/cpu/system.slice/systemd-udev-trigger.service/cpuacct.stat
-r--r--r-- 1 root root 0 Dec  4 12:15 /sys/fs/cgroup/cpu/system.slice/systemd-udev-trigger.service/cpuacct.stat

cat /sys/fs/cgroup/cpu/system.slice/systemd-udev-trigger.service/cpuacct.stat
user 0
system 0


ls -al /sys/fs/cgroup/cpuset/system.slice/systemd-udev-trigger.service/cpuacct.stat
-r--r--r-- 1 root root 0 Sep  8 03:23 /sys/fs/cgroup/cpuset/system.slice/systemd-udev-trigger.service/cpuacct.stat

cat /sys/fs/cgroup/cpuset/system.slice/systemd-udev-trigger.service/cpuacct.stat
user 0
system 0

ls -al /sys/fs/cgroup/cpuacct/system.slice/systemd-udev-trigger.service/cpuacct.stat
-r--r--r-- 1 root root 0 Sep  8 03:23 /sys/fs/cgroup/cpuacct/system.slice/systemd-udev-trigger.service/cpuacct.stat

cat /sys/fs/cgroup/cpuacct/system.slice/systemd-udev-trigger.service/cpuacct.stat
user 0
system 0

**Comment by Shnatsel** [comment]
@kubernetes/sig-node-bugs

**Comment by piaoyu** [comment]
the same problem 
Kubernetes version (use kubectl version): v1.12.0，v1.12.4
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): centos7
Kernel (e.g. uname -a):3.10.0-327

**Comment by yangqk** [comment]
@xuxiaosen  
Have you solved this issue?

**Comment by wstian** [comment]
same error message in kubelet log
```
Failed to start ContainerManager failed to get rootfs info: unable to find data in memory cache
```

we solve it by downgrading the linux kernel, a customized internal kernel based on 3.0.x

**Comment by thinkin** [comment]
Have solve?

**Comment by ninehills** [comment]
workaround: 

KUBELET_ARGS add
--feature-gates=\"LocalStorageCapacityIsolation=false\"

**Comment by wangxf1987** [comment]
steps:
systemctl daemon-reexec
systemctl restart docker
systemctl restart kubelet

it's may be the containerd-shim not exit, you can run
```shell
ps aux | grep docker
```
