### ISSUE TITLE
Still some flaky volume binding integration tests

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#71716]
**Which jobs are failing**:
pull-kubernetes-integration

**Which test(s) are failing**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestVolumeBinding

The flake rate is much better than before, but there are still some occasional flakes.

/kind failing-test

**Comment by msau42** [comment]
cc @cofyc do you have time to investigate?

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by cofyc** [comment]
Example: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72303/pull-kubernetes-integration/39182/#k8siokubernetestestintegrationscheduler-testvolumebindingstresswithschedulerresync

**Comment by cofyc** [comment]
/close

No failures in volume binding for 15 days. Reopen or create new issue when there are new failures.

Testgrid snapshot on 2018-01-22 for test `TestVolumeBinding|TestPVAffinityConflict|TestVolumeProvision|TestRescheduleProvisioning`:

![snapshot](https://user-images.githubusercontent.com/91730/51513051-c350b800-1e43-11e9-987e-fa7f0b204424.png)
