### ISSUE TITLE
NewFilteredDynamicSharedInformerFactory ignores namespace parameter

### ISSUE THREAD

**Issue by shomron** [kubernetes/kubernetes#71714]
**What happened**:

The `NewFilteredDynamicSharedInformerFactory` constructor takes a `namespace` argument which is meant to populate a member and be passed along to new informers constructed in `ForResource`. However, `namespace` is ignored and the `namespace` member is initialized to `metav1.NamespaceAll` instead.

**What you expected to happen**:

I exepected `NewFilteredDynamicSharedInformerFactory` to capture the `namespace` argument in `dynamicSharedInformerFactory.namespace`, and subsequently pass it on to `NewFilteredDynamicInformer` calls in `ForResource`. 

**How to reproduce it (as minimally and precisely as possible)**:

Construct a `FilteredDynamicSharedInformerFactory` scoped to a specific namespace. Create an informer using `ForResource` and perform a `List`. Results will span namespaces.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.13.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by wwitzel3** [comment]
Waiting for an approved on the tests for the fix here: https://github.com/kubernetes/kubernetes/pull/76776

**Comment by tedyu** [comment]
commit 2ed3272a5e428690c066a7c09e5c6a2fad3d74b6
Author: Michael FIG <michael@liveblockauctions.com>
Date:   Wed May 15 11:48:17 2019 -0600

    Honour NewFilteredDynamicSharedInformerFactory namespace argument

**Comment by tedyu** [comment]
@caesarxuchao 
If you're not working on this, can I work on it ?
