### ISSUE TITLE
e2e storage testsuites: avoid timeout in "volumeMode should fail in binding dynamic provisioned PV to PVC"

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#71748]
**What would you like to be added**:

Here's how the test is written at the moment:
https://github.com/kubernetes/kubernetes/blob/e689d515f77cda51898045d626ec4070e3328194/test/e2e/storage/testsuites/volumemode.go#L329-L330

During a normal test run, this `framework.WaitForPersistentVolumeClaimPhase` will run for five minutes and then time out. The timeout error then is considered a test success.

Instead, the test should wait for the expected error condition and fail if that isn't reached within the timeout period.

**Why is this needed**:

Faster test execution, more precise testing (no false positives when the operation fails for some other reason).

/kind feature

/sig storage
/cc @mkimuram

**Comment by mkimuram** [comment]
@pohly 

Thank you for pointing it out.

I think that this will be achieved by the similar way to https://github.com/kubernetes/kubernetes/pull/71428, it checks that proper events happen instead of waiting for not success. 

However, because events are not reliable, https://github.com/kubernetes/kubernetes/issues/71570 will change it to waiting for not success.

Are there any good ideas to check proper failure instead of waiting not fail or relying on events?

/cc @msau42 @cofyc @saad-ali

**Comment by msau42** [comment]
For PVC errors, I'm not sure if there's a great way.  For the Pod subpath error, the error is propagated to Pod conditions.  But PVC does not have a similar field.

**Comment by pohly** [comment]
Michelle Au <notifications@github.com> writes:
> For PVC errors, I'm not sure if there's a great way.  For the Pod
> subpath error, the error is propagated to Pod conditions.  But PVC
> does not have a similar field.

They get posted as status, but I agree, this might not be easy to wait for.

**Comment by msau42** [comment]
I mean that today PVC.status.conditions are only used by the resizing controller.  So we would have to consider if it makes sense to report binding errors in the PVC conditions as well.

**Comment by pohly** [comment]
/remove-lifecycle stale

Still relevant. I think the tests was recently marked as `[SLOW]` to prevent running it in pre-merge checks, but when running all tests it still causes delays.

**Comment by mkimuram** [comment]
Reopening this issue, for it can be improved.
/reopen
