### ISSUE TITLE
kube-scheduler is missing permissions for delegated authentication

### ISSUE THREAD

**Issue by mrIncompetent** [kubernetes/kubernetes#71752]
**What happened**:
The kube-scheduler crashes with v1.13 as it is missing the required permissions for delegated authentication:
```
W1205 10:35:37.728989       1 authentication.go:248] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

kube-scheduler runs in a different kubernetes cluster.

v1.12 does not have the `--authentication-kubeconfig` flag - and it does not try to load the ConfigMap kube-system/extension-apiserver-authentication

v1.13 without `--authentication-kubeconfig` uses the in-cluster client - pointing to the wrong cluster & fails loading the ConfigMap kube-system/extension-apiserver-authentication

v1.13 with `--authentication-kubeconfig` uses the provided kubeconfig, but still fails loading the ConfigMap kube-system/extension-apiserver-authentication as the user `system:kube-scheduler` does not have the required permission to read it.

**What you expected to happen**:
1. The kube-scheduler has the correct permission by default to handle delegated authentication
2. The kube-scheduler handles this case gracefully by not serving on the secure port. See https://github.com/kubernetes/kubernetes/pull/71743#issuecomment-444561450

**How to reproduce it (as minimally and precisely as possible)**:
Start a v1.13.0 kube-scheduler (Not inside the cluster) with the following flags:
```
--kubeconfig /etc/kubernetes/kubeconfig/kubeconfig
--authentication-kubeconfig /etc/kubernetes/kubeconfig/kubeconfig
```

**Anything else we need to know?**:
The environment:
kube-scheduler runs in a different kubernetes cluster.

Introduced in #69663
This is a tracking issue triggered by: https://github.com/kubernetes/kubernetes/pull/71743

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.0

/kind bug

**Comment by luxas** [comment]
Shouldn't we create the bootstrap RBAC rules by default for the scheduler and kcm wrt this now @liggitt @sttts?

**Comment by alvaroaleman** [comment]
> Shouldn't we create the bootstrap RBAC rules by default for the scheduler and kcm wrt this now @liggitt @sttts?

Ping on that one. How is tolerating the missing permissions a fix for this?

**Comment by liggitt** [comment]
> How is tolerating the missing permissions a fix for this?

tolerating missing permissions preserves pre-1.13 behavior. adding the permissions by default is in progress in https://github.com/kubernetes/kubernetes/pull/72491
