### ISSUE TITLE
Kubernetes trying to attach non-available volume

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/kubernetes#71750]
**What happened**:

Kubernetes tries to attach EBS volumes while their status is still `creating`:

```
Events:
  Type     Reason                  Age                From                                  Message
  ----     ------                  ----               ----                                  -------
  Warning  FailedScheduling        19s (x6 over 28s)  default-scheduler                     pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               19s                default-scheduler                     Successfully assigned default/app to ip-172-18-0-74.ec2.internal
  Warning  FailedAttachVolume      15s (x4 over 19s)  attachdetach-controller               AttachVolume.Attach failed for volume "pvc-320dced4-eefa-11e8-a19d-0e7ca462e948" : "Error attaching EBS volume \"vol-01cce92492ab6d0b0\"" to instance "i-0fcdf055a3d119b1b" since volume is in "creating" state
  Normal   SuccessfulAttachVolume  7s                 attachdetach-controller               AttachVolume.Attach succeeded for volume "pvc-320dced4-eefa-11e8-a19d-0e7ca462e948"
  Normal   Pulling                 1s                 kubelet, ip-172-18-0-74.ec2.internal  pulling image "centos"
```
I believe this started to happen after #67812, when volumes and their tags started to be created in the same request. Before that, tags would be set through another call (i.e., `c.tagging.createTags`), which retries if the volume isn't `available`.

**What you expected to happen**:

Kubernetes should try to attach the volume only when it's available. In order to do that, `aws.CreateDisk()` should make sure the volume is `available` when it returns.

**How to reproduce it (as minimally and precisely as possible)**:

Just create a dynamically provisioned EBS volume.

/kind bug
/sig storage
/sig aws

**Comment by bertinatto** [comment]
CC @jsafrane @gnufied

**Comment by gnufied** [comment]
What is the downside of this? IIRC - even when we tagged separately, we used to have few cases where by the time attachment was attempted, volume was not available.  May be tagging while creating the volume makes it worse but someone has to wait for volume to become available - either attach call or create volume call itself.

**Comment by gnufied** [comment]
In worse case this causes first attach to fail - but controller will retry anyway.

**Comment by jsafrane** [comment]
I think it re-introduces https://github.com/kubernetes/kubernetes/issues/62171

**Comment by gnufied** [comment]
No - looking at events attached to the pod, it looks like volume eventually got attached. I think #62171 is unrelated.

**Comment by jsafrane** [comment]
It is related. If you create volume with invalid keys, AWS returns you a volume and in this case Kubernetes will create a PV for it. But then the volume silently disappears. The only way how to detect that is to wait for the volume to either get Available or disappear.

**Comment by gnufied** [comment]
@jsafrane we are still waiting for volume to become available if volume has kms key - https://github.com/jsafrane/kubernetes/blob/7bbe309d8d64adf72b13ced258f1e97567dd945d/pkg/cloudprovider/providers/aws/aws.go#L2229

**Comment by leakingtapan** [comment]
+1 on this issue. I have seen this quite often on my v1.12 cluster too. So this is an issue even before #67812

**Comment by jsafrane** [comment]
>@jsafrane we are still waiting for volume to become available if volume has kms key - https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2225

Oh, sorry for the noise.

**Comment by leakingtapan** [comment]
EBS CSI driver is already [waiting after volume creation](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L291) regardless of whether kms key is used or not. Any objections to do the same for in-tree?

**Comment by jsafrane** [comment]
I like it.
