### ISSUE TITLE
kubectl help can't display underscore properly

### ISSUE THREAD

**Issue by flf2ko** [kubernetes/kubernetes#71769]
**What happened**:
kubectl help description can't display underscore properly.

Example 1:
`kubectl diff -h`

```
Diff configurations specified by filename or stdin between the current online configuration, and the configuration as it
would be if applied.

Output is always YAML.

KUBECTL EXTERNAL DIFF environment variable can be used to select your own diff command. By default, the "diff" command
available in your path will be run with "-u" (unicode) and "-N" (treat new files as empty) options.
```
The environment variable `KUBECTL_EXTERNAL_DIFF` displayed but missing underscore.

Example 2:
`kubectl apply edit-last-applied -h`

```
Edit the latest last-applied-configuration annotations of resources from the default editor.

The edit-last-applied command allows you to directly edit any API resource you can retrieve via the command line tools.
It will open the editor defined by your KUBE _EDITOR, or EDITOR environment variables, or fall back to 'vi' for Linux or
'notepad' for Windows. You can edit multiple objects, although changes are applied one at a time. The command accepts
filenames as well as command line arguments, although the files you point to must be previously saved versions of
resources.
```

The environment variable `KUBE_EDITOR` with an additional space before underscore.

**What you expected to happen**:

Display underscore properly without missing or additional space.

**How to reproduce it (as minimally and precisely as possible)**:

Use kubectl and run following example:

`kubectl diff -h`
`kubectl apply edit-last-applied -h`
`kubectl config rename-context -h`

**Anything else we need to know?**:

The description are correctly in code base, but display with wrong message format.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/diff/diff.go#L54
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply/apply_edit_last_applied.go#L33

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

and also linux version kubectl

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by tanshanshan** [comment]
I found the same problem 
`kubectl config unset --help`
```
Unsets an individual value in a kubeconfig file

PROPERTY _NAME is a dot delimited name where each token represents either an
attribute name or a map key.  Map keys may not contain dots.
```

PROPERTY _NAME the same as above you paste

in https://github.com/kubernetes/kubernetes/blob/71cf45f35ca7baa3fdc44ebe4992b71ab1741277/pkg/kubectl/cmd/config/unset.go#L42

**Comment by surajnarwade** [comment]
@juanvallejo , I would like to take this up :smile:

**Comment by surajnarwade** [comment]
oops, it's already there: https://github.com/kubernetes/kubernetes/pull/72137
