### ISSUE TITLE
Headless service dns entries not created if service name contains hyphen

### ISSUE THREAD

**Issue by llamahunter** [kubernetes/kubernetes#71775]
**What happened**:
Created a headless service so that DNS names would be created for my stateful set pods.  The service name contained a hyphen '-' character 

**What you expected to happen**:
DNS entries of the form <pod-name>.<service-name>.<namespace>.<cluster-suffix> would be created by kube-dns.  However, they are not if the service name contains a hyphen.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the instructions on creating a StatefulSet here
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#creating-a-statefulset
but use 'nginx-foo' for the metadata.name of the Service instead of 'nginx'

**Anything else we need to know?**:
https://tools.ietf.org/html/rfc952 says domain names can have hyphens.  It's reasonably widely used on the internet.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.3
- Cloud provider or hardware configuration:
EKS
- OS (e.g. from /etc/os-release):
whatever AWS EKS ami uses
- Kernel (e.g. `uname -a`):
see above
- Install tools:
EKS
- Others:

/kind bug

**Comment by llamahunter** [comment]
Hmm... it's very strange that this doesn't work, since the end to end example here *appears* to test this case.  

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns.go

Yet, as with the simple example above using nginx, it can demonstrably be shown not to work.

**Comment by llamahunter** [comment]
Ugh... nevermind.  I think I found the secret incantation while reading the endpoint reconciliation code.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L447
Not only does the pod need to have a hostname, but it needs to refer to the service name via the Pod.Spec.Subdomain, which is set via the StatefulSet.Spec.ServiceName field.

**Comment by ksemaev** [comment]
@llamahunter can you please explain these 2 things:
1) Why pods behind headless services without hyphen, and no hostname and subdomain specified still accessible by name?
2) What to do it I have 2 separate headless services connected to one pod (deploy/statefulset etc)?
