### ISSUE TITLE
Pod CIDR

### ISSUE THREAD

**Issue by boocup** [kubernetes/kubernetes#71794]
I am trying to modify the Pod CIDR used by nodes. I have uncommented the "podCIDR:" in cluster.yaml, but the Pod CIDR shown in the node page of the dashboard doesn't reflect my change. Is there more that needs to be done? BTW- I am trying to get more IPs available so I can have more pods per node.

**Comment by liggitt** [comment]
podCIDR is an immutable field. to modify it, the Node object must be deleted and recreated. this typically also means existing pods must be drained from the Node

/close

**Comment by boocup** [comment]
right. I have done Kube-aws destroy. then after modifying the field in cluster.yml ran kube-aws up. Should I expect the change to be reflected? Apologies if I am missing something.

**Comment by liggitt** [comment]
ah, that would be better asked in https://github.com/kubernetes-incubator/kube-aws
