### ISSUE TITLE
SelfSubjectAccessReview result is incorrect

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#71791]
**What happened**:
```
cluster/kubectl.sh create clusterrole --verb="*" psp --resource=psp
cluster/kubectl.sh create rolebinding psp --clusterrole=psp --serviceaccount=default:default
```
result: use below
~~➜  kubernetes git:(master) ✗ cluster/kubectl.sh auth can-i use psp --as=system:serviceaccount:default:default -v 8
{"namespace":"default","verb":"use","group":"extensions","resource":"podsecuritypolicies"}},"status":{"allowed":true,"reason":"RBAC: allowed by RoleBinding \"psp/default\" of ClusterRole \"cluster-admin\" to ServiceAccount \"default/default\""}}
yes~~

```
➜  kubernetes git:(master) ✗ cluster/kubectl.sh get psp --as=system:serviceaccount:default:default
Error from server (Forbidden): podsecuritypolicies.extensions is forbidden: User "system:serviceaccount:default:default" cannot list resource "podsecuritypolicies" in API group "extensions" at the cluster scope
```
SelfSubjectAccessReview only matches rules. If the request is sent directly to apiserver , apiserver will get the attribute from request, there is no problem like this. but if other places use the SelfSubjectAccessReview API to verify permission, there may be hidden security issues. Now the client must ensure that the attribute passed by itself is correct.

/sig auth

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
can you clarify your full setup, and what the unexpected behavior is?

there appear to be other rolebindings to the service account in question (specifically, `cluster-admin` was bound to the service account within that namespace according to the message `allowed by RoleBinding "psp/default" of ClusterRole "cluster-admin" to ServiceAccount "default/default"`) that were not shown in the recreation steps

**Comment by zjj2wry** [comment]
```
➜  kubernetes git:(master) ✗ cluster/kubectl.sh create clusterrole --verb="*" psp --resource=psp
clusterrole.rbac.authorization.k8s.io/psp created
➜  kubernetes git:(master) ✗ cluster/kubectl.sh create rolebinding psp --clusterrole=psp --serviceaccount=default:default
rolebinding.rbac.authorization.k8s.io/psp created
➜  kubernetes git:(master) ✗ cluster/kubectl.sh auth can-i use psp --as=system:serviceaccount:default:default -v 8
I1206 22:48:07.053115    4287 loader.go:359] Config loaded from file /var/run/kubernetes/admin.kubeconfig
I1206 22:48:07.058739    4287 loader.go:359] Config loaded from file /var/run/kubernetes/admin.kubeconfig
I1206 22:48:07.061816    4287 loader.go:359] Config loaded from file /var/run/kubernetes/admin.kubeconfig
I1206 22:48:07.062929    4287 request.go:942] Request Body: {"kind":"SelfSubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"namespace":"default","verb":"use","group":"extensions","resource":"podsecuritypolicies"}},"status":{"allowed":false}}
I1206 22:48:07.063012    4287 round_trippers.go:383] POST https://localhost:6443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews
I1206 22:48:07.063127    4287 round_trippers.go:390] Request Headers:
I1206 22:48:07.063143    4287 round_trippers.go:393]     Impersonate-User: system:serviceaccount:default:default
I1206 22:48:07.063152    4287 round_trippers.go:393]     User-Agent: kubectl/v1.14.0 (darwin/amd64) kubernetes/a17742b
I1206 22:48:07.063158    4287 round_trippers.go:393]     Accept: application/json, */*
I1206 22:48:07.063164    4287 round_trippers.go:393]     Content-Type: application/json
I1206 22:48:07.078241    4287 round_trippers.go:408] Response Status: 201 Created in 15 milliseconds
I1206 22:48:07.078282    4287 round_trippers.go:411] Response Headers:
I1206 22:48:07.078295    4287 round_trippers.go:414]     Content-Type: application/json
I1206 22:48:07.078306    4287 round_trippers.go:414]     Content-Length: 376
I1206 22:48:07.078316    4287 round_trippers.go:414]     Date: Thu, 06 Dec 2018 14:48:07 GMT
I1206 22:48:07.078371    4287 request.go:942] Response Body: {"kind":"SelfSubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"namespace":"default","verb":"use","group":"extensions","resource":"podsecuritypolicies"}},"status":{"allowed":true,"reason":"RBAC: allowed by RoleBinding \"psp/default\" of ClusterRole \"psp\" to ServiceAccount \"default/default\""}}
yes
```

**Comment by liggitt** [comment]
> if we want show correct result need client ensure attributes is correct?

yes, the attributes provided to the subjectaccessreview must be correct in order for the result to be correct

> check psp we can not pass namespace field when call selfreview

namespace can always be provided to [self]subjectaccessreview requests, the authorization check for the verb/resource/scope is generic. when checking if a PSP can be used, the namespace of the pod being checked is provided so that permission to use a PSP can be scoped to a single namespace if desired

**Comment by liggitt** [comment]
selfsubjectaccessreview using the attributes in the provided review to match authorization rules is working as intended

/close
