### ISSUE TITLE
winkernel kube-proxy assumes nodename and hostname are the same

### ISSUE THREAD

**Issue by astrieanna** [kubernetes/kubernetes#71799]
**What happened**: When using the vsphere cloud provider and a hostname override, kube-proxy does not recognize local endpoints correctly.

**What you expected to happen**: kube-proxy should use the same logic as kubelet to determine nodename. The nodename does not need to be the same as the hostname override.

**How to reproduce it (as minimally and precisely as possible)**:
(1) Run a cluster on vsphere with a windows node, with the vsphere cloud provider
(2) Start kube-proxy with a hostname override that does not match the os' hostname, and see kube-proxy mark local pods' HNSEndpoints as remote.

**Anything else we need to know?**:
kube-proxy behaves as if the endpoints are remote because the nodename of the endpoints does not match the hostname-override passed into kube-proxy.

This is the line where proxier compares a nodename in an endpoint to the hostname:
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/winkernel/proxier.go#L896

The hostname used by proxier above is determined by kube-proxy here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server_windows.go#L75

This will use the hostname-override if provided, and the os' hostname otherwise. This hostname is used to create the proxier, a healthz check, and the NodeRef in the ProxyServer struct. I believe that the other two uses actually want a hostname (an IP or something DNS-routeable).

kubelet determines the nodename:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L536

I think kube-proxy should use the same cloud-provider function to determine the nodename, since the important thing about this value is it matched what kubelet is using when registering the node.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11/1.12
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release): 1803

/kind bug

**Comment by astrieanna** [comment]
This also applies to other proxiers (the ones on linux):
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/endpoints.go#L221

**Comment by dineshgovindasamy** [comment]
@astrieanna We use the same logic as other Proxies. I think we should table this discussion in the SIG Network meeting if we want to change this to all proxies.

**Comment by astrieanna** [comment]
@dineshgovindasamy good point. I'm closing this issue in favor of one that is focused on kube-proxy as a whole, since this is not just windows. https://github.com/kubernetes/kubernetes/issues/71851
