### ISSUE TITLE
Sweep for calls to delete that result in orphaning dependents

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#71807]
**What happened**:

Several resources default to orphaning dependents for backwards compatibility:
* daemonsets in extensions/v1beta1, apps/v1beta2
* deployments in extensions/v1beta1, apps/v1beta1, apps/v1beta2
* replicasets in extensions/v1beta1, apps/v1beta2
* statefulsets in apps/v1beta1, apps/v1beta2
* jobs in batch/v1
* cronjobs in batch/v1beta1, batch/v2alpha1
* replicationcontrollers in v1

Calls made via client-go to delete these resource via these versions which do not specify a deletion propagation policy default to orphaning dependents. For controller-deleted resources, this is almost always not what we want.

A specific example of this was https://github.com/kubernetes/kubernetes/issues/71772 that deleted jobs and accidentally orphaned pods.

We should sweep controller calls that delete the resources/versions listed above without specifying a deletion propagation policy and decide what policy is expected. In general, I would expect controllers to use background deletion propagation.

/kind bug

**Comment by liggitt** [comment]
cc @kubernetes/sig-apps-misc

**Comment by adohe** [comment]
cc @adohe

**Comment by liggitt** [comment]
a lot of controllers got switched to use apps/v1 in 1.14, so there are now no controllers calling Delete on the indicated versions

/close
