### ISSUE TITLE
[scheduler] improve logging for successful binding

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71819]
**What would you like to be added**:
We should add a log line (at V1 or V2) each time the scheduler successfully creates a binding. The log should include,
- pod namespace/name
- target node
- number of nodes evaluated
- number of feasible nodes found

**Why is this needed**:
If the scheduler thinks everything is going well, almost nothing gets logged about scheduling decisions. Adding this log will help us debug issues where, for example, the scheduler cache is out of sync with a node's state, and the node repeatedly rejects pods that we bind to it.

/sig scheduling

/kind feature

**Comment by misterikkit** [comment]
/help
/good-first-issue

To anyone who wants to help with this, please make sure that sig-scheduling approves of this enhancement first.
/cc @bsalamat @k82cn

**Comment by wgliang** [comment]
I can take this if sig-scheduling approves of this enhancement.
/assign
/remove-help

**Comment by wgliang** [comment]
@k82cn @bsalamat 
What‘s your opinions？I will submit PR if you think this is ok.

**Comment by bsalamat** [comment]
@wgliang I agree that we need the log records.
