### ISSUE TITLE
api timeouts when using token authentication

### ISSUE THREAD

**Issue by jmcmeek** [kubernetes/kubernetes#71811]
**What happened**:
One of our customers has a workload that makes a lot of api calls using serviceaccount tokens.  They have seen periods of increasingly slow responses eventually leading to many requests failing due to a 1 minute timeout in the apiserver. Requests using other authentication mechanisms (certificate, OIDC tokens) at the same time see no slowdown or timeouts.

**What you expected to happen**:
API calls using serviceaccount tokens should have similar performance as other calls.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
At apiserver verbosity (-v)=4, we saw log entries like:
```
GET:https://127.0.0.1:2040/api/v1/namespace
s/81b54524bfa349828fae6a546b5808bc/serviceaccounts/compose
I1205 23:11:19.509645       1 request.go:530] Throttling request took 3.049260372s, request: GET:https://127.0.0.1:2040/api/v1/namespace
s/be7e995326144ec9a6a65c21c79e04fa/secrets/compose-token-z225g
I1205 23:11:19.529665       1 request.go:530] Throttling request took 3.040583457s, request: GET:https://127.0.0.1:2040/api/v1/namespaces/kube-system/secrets/kube-dns-token-kl8s6
```
The log sample those are from spanned 5m 45 sec, and contains 5698 of those Throttling entries.
They appear to be coming from a go-client in the apiserver calling back into the apiserver.

Further investigation suggested this was due to rate limiting within the go-client used by the tokenauthenticator to validate the tokens - check that the service account and secret associated with the token still exist.

We saw throttling times over 1 minute.  At 30 seconds, the total time to perform just the serviceaccount and secret lookup would be sufficient to cause the request to timeout.

We didn't find any way to change the rate limiting configuration, but we did find the `--service-account-lookup` apiserver option.  After setting that to false, API calls were consistently fast.  So it seems that token validation is the culprit and we can circumvent it at the risk of allowing clients to use tokens that have since been deleted.

Some thoughts suggested here:
- Provide a knob to control this throttling
- Disable throttling in the go-client used by token authentication
- We think there is a cache mechanism with a 10 minute TTL.  We can't tell from our logs how often there is a cache miss and why (not in the cache, expired...), but the TTL might be replaced by watches that could invalidate entries as SAs and secrets are deleted.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.5
- Cloud provider or hardware configuration: IBM Kubernetes Service
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): Linux REDACTED 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by jmcmeek** [comment]
@kubernetes/sig-auth-bugs

**Comment by liggitt** [comment]
added informer lookup in https://github.com/kubernetes/kubernetes/pull/71816

**Comment by jmcmeek** [comment]
@liggit Is this going to be cherry-picked to any other releases?

**Comment by liggitt** [comment]
> @liggit Is this going to be cherry-picked to any other releases?

no, backports are limited to fixing security issues, critical bugs, and regressions. scale/performance improvements that are not addressing regressions are not backported.

**Comment by jmcmeek** [comment]
@liggitt We just got 1.14.0. alpha running in IKS.  Your change appears to work great.  A test that used to take 26 minutes due to throttling ran in 10 seconds.  Thanks!

**Comment by liggitt** [comment]
> @liggitt We just got 1.14.0. alpha running in IKS. Your change appears to work great. A test that used to take 26 minutes due to throttling ran in 10 seconds.

fantastic
