### ISSUE TITLE
frontend ip lost while service still exsting on azure

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#71838]
This happened for the second time, I've seen some frontend ip configuration for internal loadbalancer being cleaned up while we did not delete the corresponding service.

- audit logs do not show anything interesting
- controller-manager (`--v=4`) did not show anything interesting
- Azure activity log shows the following:

```
IP configuration /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Network/loadBalancers/<loadbalancer_name>/frontendIPConfigurations/<ip_config_id> is using the private IP address <ip_adress> which is being cleaned up and was allocated to resource /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Network/loadBalancers/<loadbalancer_name>.
```

/priority critical-urgent
/kind bug
/sig azure

cc @feiskyer

**Comment by feiskyer** [comment]
@yastij What logs have you got from kube-controller-manager when this is happening? And which version of kubernetes are you running?

**Comment by feiskyer** [comment]
@yastij I'm closing the issue since it's not active for a long time. Feel free to reopen it if you still have problems.

/close
