### ISSUE TITLE
kubectl makes GET request despite  --watch-only=true being set

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#71845]
**What happened**:

`kubectl get <resource> <name> --watch-only`  makes GET request for a resource despite what documentation says

**What you expected to happen**:

Only WATCH request is made

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl  --v=6 get sa default --watch-only
I1207 13:34:18.650646    9886 round_trippers.go:405] GET https://apiserver/api/v1/namespaces/default/serviceaccounts/default 200 OK in 81 milliseconds
I1207 13:34:18.662141    9886 round_trippers.go:405] GET https://apiserver/api/v1/namespaces/default/serviceaccounts?fieldSelector=metadata.name%3Ddefault&resourceVersion=0&watch=true 200 OK in 10 milliseconds
```

notice there is a first GET,  which fetches object, if I understand `--watch-only` description correctly it shouldn't be there.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

/area kubectl
/sig cli

**Comment by redbaron** [comment]
does it need to make that GET request? I know it is pretty unrealistic, but there can be an RBAC role with watch only verb

**Comment by liggitt** [comment]
yes, otherwise it doesn't know when it is done getting the initial set of ADDED events for existing items

**Comment by redbaron** [comment]
But subsequent watch request is `resourceVersion=0` , doesn't it mean "send me all events since you received this request" ?

**Comment by liggitt** [comment]
> But subsequent watch request is `resourceVersion=0` , doesn't it mean "send me all events since you received this request" ?

In the list case, we use the rv from the list as our watch starting point. in the single-version case, we use `0` and skip printing the first event.
