### ISSUE TITLE
Differentiate between authenticated & non-authenticated images

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#71850]
Currently kubernetes allows for an image pulled using a secret to be referenced without a secret by other pods.  The AlwaysPullImages admission controller fixes that, but at the expense of always pulling the image, creating a hard dependency on the registry being available.

Can we discuss a solution that allows for kubernetes to differentiate between public and private images?  Or that can cache a map from the credential to the image used?  (I guess it is conceivable, although likely  a terrible idea, that some registry might use credentials to serve different image labels to different users)

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/18787 ?

**Comment by justinsb** [comment]
Thanks @liggitt - quite right. I hope you had to look the PR number up ;-)
