### ISSUE TITLE
[scheduler cleanup phase 2]: Move users of `factory.NewConfigFactory` to `scheduler.New`

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71859]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

Our existing, multi-step constructor `NewConfigFactory` is being replaced by the simpler `New` function. (See https://github.com/kubernetes/kubernetes/pull/69057) This issue covers migrating all users to the new function.

Today, all callers appear to be in either `cmd/kube-scheduler` or `test/integration`.

When the migration is complete, we should also be able to,

- remove `NewSchedulerConfig` from `cmd/kube-scheduler/app`
- remove `scheduler.NewFromConfigurator`
- rename `scheduler.NewFromConfig` to `scheduler.newFromConfig`

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by misterikkit** [comment]
Looks like the PR missed some calls to `NewConfigFactory` in the `test/integration` area.
/reopen

**Comment by wgliang** [comment]
@misterikkit I will do it.

**Comment by vllry** [comment]
Whoops
/hold cancel
/lifecycle frozen

**Comment by draveness** [comment]
Have talked to @wgliang, I'll take it over and start working on this.

/unassign @wgliang 
/assign

**Comment by alculquicondor** [comment]
@draveness what's the pending work on this?

**Comment by draveness** [comment]
> @draveness what's the pending work on this?

I'm working on #80697

**Comment by ahg-g** [comment]
@ahmad-diaa can you please post an update on what PRs are pending, and what other instances of ```factory.NewConfigFactory``` that still needs to be removed before we declare this issue closed?

**Comment by ahmad-diaa** [comment]
Currently pending PRS: #80697, #81911, #82040
#81911 is blocked by #81911

remaining calls:
- https://github.com/kubernetes/kubernetes/blob/c58767b1e2981bd7826b4336de0c2756fa975339/pkg/scheduler/api/compatibility/compatibility_test.go#L1232
- `scheduler.New` won't be able to remove this now (dependent on https://github.com/kubernetes/kubernetes/issues/72547)
- calls in `factory_test.go` (won't be removed now as well).

**Comment by ahg-g** [comment]
We should also remove the dependency in autoscaler: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/predicates.go#L129

**Comment by ahmad-diaa** [comment]
> We should also remove the dependency in autoscaler: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/predicates.go#L129

I missed this one, will send a PR for it.

Is there a way to look for `factory.NewConfigFactory` calls  in all repos to avoid missing calls in other repos like this one?

**Comment by ahg-g** [comment]
> > We should also remove the dependency in autoscaler: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/predicates.go#L129
> 
> I missed this one, will send a PR for it.
> 
> Is there a way to look for `factory.NewConfigFactory` calls in all repos to avoid missing calls in other repos like this one?

unfortunately not, but this should be the only one and we need to work on a better interface with the autoscaler.

**Comment by ahmad-diaa** [comment]
@ahg-g https://github.com/kubernetes/autoscaler/blob/6c5a504681bc688d838f1b58006cbe0c93e13bfc/cluster-autoscaler/simulator/predicates.go#L195 seems like a blocker to getting rid of the configurator.

**Comment by ahmad-diaa** [comment]
> @ahg-g https://github.com/kubernetes/autoscaler/blob/6c5a504681bc688d838f1b58006cbe0c93e13bfc/cluster-autoscaler/simulator/predicates.go#L195 seems like a blocker to getting rid of the configurator.

@alculquicondor I could think of two options for now:
- exporting `getPredicateMetaDataProucer()` https://github.com/kubernetes/kubernetes/blob/e5f276a1ab226f3590634a240a6a82aa9fefcb49/pkg/scheduler/factory/plugins.go#L506
- postponing this until we migrate the factory package to the scheduler

WDYT?

**Comment by alculquicondor** [comment]
@maciekpytel Is there a reason why the autoscaler can't use `predicates.GetPredicateMetadata` directly?

That appears to be the only value that's written to `factory.predicateMetadataProducer`.

**Comment by ahg-g** [comment]
This is done as well.

/close
