### ISSUE TITLE
[scheduler cleanup phase 2]: Move priority types from `pkg/scheduler/algorithm` to `pkg/scheduler/algorithm/priorities`

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71865]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

The priority types in `pkg/scheduler/algorithm` (`PriorityConfig`, `PriorityMetadata`, etc.) should be moved to the package that implements these types, `pkg/scheduler/algorithm/priorities`. This is a relatively minor change, but having all the priority stuff in one package will make it easier to refactor in future cleanup.

Note: `pkg/scheduler/algorithm` may not import `pkg/scheduler/algorithm/priorities` as that would cause an import loop.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by sonasingh46** [comment]
I would like to work on this issue.

**Comment by sonasingh46** [comment]
I will take it.
