### ISSUE TITLE
[scheduler cleanup phase 2]: Rename `pkg/scheduler/cache` to `pkg/scheduler/nodeinfo`

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71862]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

Nearly all of the "cache" functionality has been moved from this package into `pkg/scheduler/internal/cache`. What remains is `NodeInfo` and its related functionality.

Note: This package is imported in a handful of places outside of `pkg/scheduler`.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by yuexiao-wang** [comment]
I will work on it

**Comment by wgliang** [comment]
Cool, thanks for you help @yuexiao-wang 
/remove-help

**Comment by yuexiao-wang** [comment]
@wgliang thanks
