### ISSUE TITLE
[scheduler cleanup phase 2]: Move compatibility_test.go to `pkg/scheduler/api`

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71867]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

The tests in `pkg/scheduler/algorithmprovider/defaults/compatibility_test.go` ensure backwards compatibility with the types in `pkg/scheduler/api`. It makes more sense for these tests to live in that package.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by yuexiao-wang** [comment]
I would like to take it and thanks

**Comment by huynq0911** [comment]
Hi! I am contributer and I would like to take it.

**Comment by yuexiao-wang** [comment]
OK, @huynq0911 go head

**Comment by huynq0911** [comment]
@yuexiao-wang thanks!

**Comment by liztio** [comment]
/lifecycle active

for @huynq0911

**Comment by misterikkit** [comment]
@yuexiao-wang Thanks for taking care of this one! :smiley:

**Comment by yuexiao-wang** [comment]
You are wellcome
