### ISSUE TITLE
[scheduler cleanup phase 2]: Move predicate and priority registration into their own packages

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71866]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

The package `pkg/scheduler/algorithmprovider/defaults` contains `init()` code that makes several calls into `factory.RegisterFitPredicate` and similar functions. The code that registers all predicates should be moved into `pkg/scheduler/algorithm/predicates` along with the call to `factory.RegisterPredicateMetadataProducerFactory`. The above also applies to priorities, whose code belongs in `pkg/scheduler/algorithm/priorities`.

When this is done, the only `init()` code in the `defaults` package should be to `factory.RegisterAlgorithmProvider`.

Note: Algorithm providers are just sets of strings, so the `defaults` package doesn’t need to have any side effects beyond registering the two algorithm providers.

Other Note: I think `ApplyFeatureGates()` should be refactored away as part of https://github.com/kubernetes/kubernetes/issues/68957.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by bhavin192** [comment]
I would like to work on this.

**Comment by farmer-hutao** [comment]
I want to have a try, thanks!

**Comment by misterikkit** [comment]
Sorry for the delayed reply.

@bhavin192, are you able to work on this? If not, @farmer-hutao could take it.

**Comment by misterikkit** [comment]
Sounds good. You've probably already seen https://github.com/kubernetes/community/blob/master/contributors/guide/README.md

**Comment by bhavin192** [comment]
Hey @misterikkit I'm trying to figure out things for this
When we say: move the calls to `factory.RegisterFitPredicate()` from defaults package to predicates package, should I create a function similar to `defaultPredicates()` https://github.com/kubernetes/kubernetes/blob/b278f84786b4819f2dd484f6c994f08d0536cc96/pkg/scheduler/algorithmprovider/defaults/defaults.go#L106 in predicates package, and call that from defaults' `init()`  ?

**Comment by misterikkit** [comment]
@bhavin192 Part of the problem with the existing code is that it's combining two unrelated things. Calls to `RegisterAnything` are modifying global state in the `factory` package, while `defaultPredicates()` is just supposed to return a set of strings.

Taking another look at defaults.go, we see that some predicates get registered here: https://github.com/kubernetes/kubernetes/blob/1d59ab05fa0d5ee2838a2047e51e54bc6196bfec/pkg/scheduler/algorithmprovider/defaults/defaults.go#L49

But other predicates are registered at and below this line:
https://github.com/kubernetes/kubernetes/blob/1d59ab05fa0d5ee2838a2047e51e54bc6196bfec/pkg/scheduler/algorithmprovider/defaults/defaults.go#L64


I think it would be more appropriate to have an `init()` in the predicates package that registers every predicate (and similar for priorities). Then the defaults package just maintains a list of those strings that represent the default set of predicates/priorities.

**Comment by misterikkit** [comment]
Hi @bhavin192, let me know if my previous comment made sense. If you feel stuck on this issue, I want to fix that.

**Comment by bhavin192** [comment]
Hey @misterikkit yes, I got the point, thank you for the explanation, will let you know if I feel stuck.

**Comment by bhavin192** [comment]
While importing `pkg/scheduler/factory` in `pkg/scheduler/algorithm/predicates` I'm getting circular dependency error, 

```console
import cycle not allowed
package k8s.io/kubernetes/cmd/kube-scheduler
	imports k8s.io/kubernetes/cmd/kube-scheduler/app
	imports k8s.io/kubernetes/cmd/kube-scheduler/app/options
	imports k8s.io/kubernetes/pkg/scheduler/factory
	imports k8s.io/kubernetes/pkg/scheduler/algorithm/predicates
	imports k8s.io/kubernetes/pkg/scheduler/factory
```

**Comment by misterikkit** [comment]
@bhavin192 Argh, you are right. This keeps happening to us as I try to move things around; I should have expected it. I can see a few different alternatives.

1. find a different destination for the registration code.
2. move the registration code into `factory` package
3. keep registration code in `default` package, but split up the code that does registering with the code that specifies lists of strings for `AlgorithmProvider`s. And remove the return value from  `factory.RegisterFitPredicate` and similar functions. 

My preference is number 3. What do you think?

**Comment by bhavin192** [comment]
@misterikkit Number 3 sounds better to me too.
