### ISSUE TITLE
[scheduler cleanup phase 2]: Flatten Top Level Scheduler Struct

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71860]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

Currently, the type [`scheduler.Scheduler`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go) is a struct with one field. (`factory.Config`) It is misleading for all of the scheduler’s config *and state* to be stored in a type called "config".

Instead, we can merge these two types, keeping only `scheduler.Scheduler`. Any function returning a Config will return a Scheduler instead. Integration tests will need to be fixed to accommodate this change.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by ahmad-diaa** [comment]
@misterikkit Can I give it a try?

**Comment by misterikkit** [comment]
@ahmad-diaa sure. Reach out here or on slack if you run into trouble.

**Comment by misterikkit** [comment]
/assign @ahmad-diaa 
/remove-help
(don't worry if assignee field doesn't update)

**Comment by misterikkit** [comment]
@ahmad-diaa pinged me about the import loop caused by this change.

> Removing the `factory.Config` and using `scheduler.Scheduler` instead would introduce a circular dependency where `factory.go` imports `.../pkg/scheduler` and `scheduler.go` imports `…/pkg/scheduler/factory`.  

My goal with this issue is that the `scheduler.Scheduler` type has a bunch of members (cache, queue, etc.) rather than the one "config" member. If we can find another way to accomplish that, let's discuss.

**Comment by xiaozhouX** [comment]
I would like to try it togather, as we have discussed in slack.

**Comment by vllry** [comment]
Are there any current blockers for this issue?
