### ISSUE TITLE
[scheduler cleanup phase 2]: Rename `pkg/scheduler/util` to `pkg/scheduler/internal/podinfo`

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#71863]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

If you contributed in phase 1, please give others a chance before claiming this issue. You can also help out by reviewing the phase 2 PRs.

This package contains only functions related to pods. Having “util” as a name is generally discouraged, since it doesn’t tell readers anything about what is in that package. This change will also mirror the change to create `pkg/scheduler/nodeinfo` which will have a bunch of node-related types and functions.

`GetPodPriority` from this package is used by `pkg/kubelet/eviction`. In order to make our package internal, we should do one of the following. (1 is my preference)

1. Copy the function into kubelet and remove the dependency
2. Move the function into a different area like `apimachinery` or `client-go`
3. Make the funcion an official part of the scheduler’s public go libraries

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by mysunshine92** [comment]
I will work on it

**Comment by shinytang6** [comment]
Hey @misterikkit @mysunshine92 , what's the status of this issue? Can l take this up as a beginning contribution to k8s?

**Comment by hprateek43** [comment]
@misterikkit I am picking up this issue. I almost have a patch ready and will be opening a PR shortly.

**Comment by misterikkit** [comment]
/remove-lifecycle rotten
The PR for this is nearly merged.

**Comment by alculquicondor** [comment]
I understand that no one is working on this now?

**Comment by hprateek43** [comment]
> I understand that no one is working on this now?

I have the PR almost merged.

**Comment by alculquicondor** [comment]
@hprateek43 wasn't there more work pending than just that PR?

/reopen

**Comment by hprateek43** [comment]
@alculquicondor I am working on structuring the other PRs corresponding to this

**Comment by alculquicondor** [comment]
Thanks @hprateek43. Just remember to not put the word "Fixes" in your PR description unless it's the last PR.

**Comment by alculquicondor** [comment]
/reopen

Please @hprateek43, remember to not use the word "Fixes" in your PRs if they are not the last one.

**Comment by alculquicondor** [comment]
Hi @hprateek43, could you please do a survey of the remaining structs and functions in the util package and their usages?

From there, we can decide what is the best location for each of them.

**Comment by hprateek43** [comment]
@alculquicondor I will review the scheduler today and identify redundant components. Will open a cleanup PR

**Comment by hprateek43** [comment]
@alculquicondor I reviewed the scheduler and think we can safely move `error_channel.go` and its test cases into an internal package. I just made this change on a local branch and seems to work. Will open a issue for it and send the PR for merge.

**Comment by hprateek43** [comment]
@alculquicondor I am opening a new issue around channels that links to this one, the PR will fix that instead of this umbrella issue

**Comment by haosdent** [comment]
@ahg-g do we still need this?
