### ISSUE TITLE
 net/http: HTTP/1.x transport connection broken: malformed HTTP response

### ISSUE THREAD

**Issue by xuekew** [kubernetes/kubernetes#71878]
**What happened**:
[root@master ~]# kubectl logs my-web
Error from server: Get http://node1:10250/containerLogs/default/my-web/nginx: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.12.0-rc.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos 7.4
- Kernel (e.g. `uname -a`):3.10.0-514.26.2.el7.x86_64
- Install tools:Binary system
- Others:

/kind bug

**Comment by liggitt** [comment]
you are contacting a https url using http

/close

**Comment by xuekew** [comment]
my config

**Comment by xuekew** [comment]
root/kubernetes/server/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,DefaultSt
rageClass,ResourceQuota,NodeRestriction \
  --insecure-bind-address=0.0.0.0 \
  --kubelet-https=false \
  --service-cluster-ip-range=10.68.0.0/16 \
  --service-node-port-range=20000-40000 \
  --etcd-servers=http://etcd:2379 \
  --enable-swagger-ui=true \
  --allow-privileged=true \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/lib/audit.log \
  --event-ttl=1h \
  --v=2

**Comment by liggitt** [comment]
You should drop --kubelet-https=false from your invocation. That is causing the apiserver to try to reach the kubelet using http, but the kubelet is serving over https.

**Comment by ChanderG** [comment]
I faced the same error. In my case, the cause was a missing "imagePullSecrets" section in the pod config.
