### ISSUE TITLE
gluster endpoints are disappearing

### ISSUE THREAD

**Issue by sa9226** [kubernetes/kubernetes#71871]
In our env. we are using heketi/gluster dynamic provisioning for persistent volumes.
Our cluster is used by many application teams in dev as well as production.  We are noticing endpoints related pvc are disappearing once in while. It's not impacting all endpoints only few once in a while. Once the endpoint is missing if pod any chance restart having trouble mounting the pvc and failing. Any help and pointers are appreciated. Thank you.

Here is the example of service object and corresponding endpoint. 

**What happened**: Glusterfs pvc endpoints are disappearing randomly

**What you expected to happen**: It shouldn't delete endpoint

**How to reproduce it (as minimally and precisely as possible)**: It's happening very randomly and not able to reproduce

**Anything else we need to know?**:  As per my debugging from logs, it's happening after helm  delete and install .  This reinstall doesn't include PVC delete request. Application comes fine and endpoint exist that moment.  after couple of days, noticed api server is sending multiple DELETE requests to DELETE PVC.  

Here is sample for Servie, endpoint and PVC

kubectl -n com-att-app-dev describe svc glusterfs-dynamic-mariadb-pvc

Name:              glusterfs-dynamic-mariadb-pvc
Namespace:         com-att-app-dev
Labels:            gluster.kubernetes.io/provisioned-for-pvc=mariadb-pvc
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.233.38.133
Port:              <unset>  1/TCP
TargetPort:        1/TCP
Endpoints:         xxx.xxx.xxx.xxx:1 + 17 more...
Session Affinity:  None

 kubectl  describe endpoints glusterfs-dynamic-mariadb-pvc
Name:         glusterfs-dynamic-mariadb-pvc
Namespace:    com-att-app-dev
Labels:       gluster.kubernetes.io/provisioned-for-pvc=mariadb-pvc
Annotations:  <none>
Subsets:
  Addresses:          11.11.11.11
  NotReadyAddresses:  <none>
  Ports:
    Name     Port  Protocol
    ----     ----  --------
    <unset>  1     TCP

Events:  <none>

 kubectl -n com-att-app-dev describe pvc mariadb-pvc
Name:          mariadb-pvc
Namespace:     com-att-app-dev
StorageClass:  gluster-heketi-no-replica
Status:        Bound
Volume:        pvc-1056b286-d246-11e8-9a84-02b76f316b40
Labels:        app=app-mariadb
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-class=gluster-heketi-no-replica
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Finalizers:    []
Capacity:      6G
Access Modes:  RWX
Events:        <none>

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: openstack
- OS (e.g. from /etc/os-release): Ubuntu 16.04 
- Kernel (e.g. `uname -a`): Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:

/kind bug

**Comment by sa9226** [comment]
@kubernetes/cluster-lifecycle-bugs

**Comment by liggitt** [comment]
That sounds suspiciously like 
https://github.com/kubernetes/kubernetes/pull/58547 which was fixed in 1.9.3

**Comment by humblec** [comment]
@sa9226 it could be affer effect of the bug which @liggitt mentioned, if that version didnt resolve this issue, I would suggest an upgrade of your cluster to `1.13`. It should resolve this issue for sure.

**Comment by sa9226** [comment]
Thank you both. We are in process of upgrading our cluster and will post the status if I see this issue again.

**Comment by megastallman** [comment]
> @sa9226 it could be affer effect of the bug which @liggitt mentioned, if that version didnt resolve this issue, I would suggest an upgrade of your cluster to `1.13`. It should resolve this issue for sure.

I'm an RKE user.
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`
Having absolutely the same bug.

**Comment by rafalkasa** [comment]
To persist the Gluster endpoints, you also need to create a service.
```
apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster 
spec:
  ports:
  - port: 1
```
Save the service definition to a file, for example `gluster-service.yaml,` then create the endpoints object

**Comment by blurpy** [comment]
It is not necessary to create a service manually, or endpoints. This is handled by the dynamic provisioning support. Except that sometimes a bug deletes the endpoints.

**Comment by humblec** [comment]
yeah, we dont need any manual actions about `service` or `endpoint` for GlusterFS PVCs. Its automatically taken care the driver code itself.  Also the endpoint issue which is referred earlier has been already resolved, so you should not be seeing this issue any more ! if you still face the issue please revert.
