### ISSUE TITLE
Replace references of gcr.io with generic name

### ISSUE THREAD

**Issue by mnaser** [kubernetes/kubernetes#71888]
**What happened**:
It seems that by default, all references to images point towards `gcr.io` for things like `pause` containers.  In addition, it seems that the official Docker images are released there as well.

**What you expected to happen**:
Ideally, using a non-vendor specific name.  Perhaps, something like `k8s.cncf.io` or a similar foundation-level path which brings Kubernetes towards decreasing vendor-specific references (it could just be a CNAME that continues to host at GCR, don't break what's not fixed!)

**How to reproduce it (as minimally and precisely as possible)**:
Pretty straightforward. :)

**Anything else we need to know?**:
NA

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by dims** [comment]
it was worse before ... https://groups.google.com/forum/#!topic/kubernetes-dev/ytjk_rNrTa0 :) we now use `k8s.gcr.io/pause`which is slightly better. when we get things going with the wg-k8s-infra working group to move assets to CNCF, we can take next steps - https://github.com/kubernetes/k8s.io/issues/158
