### ISSUE TITLE
Pod be scheduled in untainted master with lower priority.

### ISSUE THREAD

**Issue by aixeshunter** [kubernetes/kubernetes#71905]
**What would you like to be added**:
Pod be scheduled in untainted master with lower priority.

**Why is this needed**:
I have a cluster with 3 masters and 3 nodes, the masters are untained and pods can be scheduled in them.

But I want the pod runs in nodes preferentially if their resources are enough only. Because the masters are very significant but resource in cluster is limited, so that they are untained.

Is there a `AlgorithmProvider` achieve it?

**Comment by krmayankk** [comment]
its not clear what you want. It seems you prefer to run on nodes in some condition while on master on other conditions. Does node affinity and anti affinity help with your case  https://kubernetes.io/docs/concepts/configuration/assign-pod-node/  ?

**Comment by aixeshunter** [comment]
> its not clear what you want. It seems you prefer to run on nodes in some condition while on master on other conditions. Does node affinity and anti affinity help with your case https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ ?

Hi, thanks your answer.
But I prefer to run on nodes if the resource(CPU, memory) is enough only, if not, the pod runs on master.

In general， my goal is to let the pods run as much as possible on the node instead of the master.

**Comment by aixeshunter** [comment]
Maybe `kubectl taint nodes master1  node-role.kubernetes.io/master=:PreferNoSchedule` can be worked?

**Comment by aixeshunter** [comment]
> Maybe `kubectl taint nodes master1 node-role.kubernetes.io/master=:PreferNoSchedule` can be worked?

Yeah, it is worked for me !!!
