### ISSUE TITLE
K8s dashboard edit always shows JSON editor even when Actions for object show view/edit YAML

### ISSUE THREAD

**Issue by shailesh91** [kubernetes/kubernetes#71927]
@kubernetes/sig-ui

**What happened**:
Whenever I try to view or edit a deployment or any other k8s Object in Kubernetes Dashboard, I always see a JSON Editor/Viewer even when the Actions drop-down nav on the far right of a record show View/Edit YAML.

**What you expected to happen**:
I was expecting to see a YAML Viewer/Editor when selecting Action for K8s Object (for Example a Stateful Set Deployment)

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/3657525/49769946-1c4efd00-fc97-11e8-854e-efb235ab6625.png)
![image](https://user-images.githubusercontent.com/3657525/49770099-c62e8980-fc97-11e8-8eda-20ffae987182.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.7", GitCommit:"572a070abf31a08a8f0d104220da467ea1e3d5f2", GitTreeState:"clean", BuildDate:"2018-11-14T05:26:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
GKE
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux ip-172-31-28-47 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
thanks for the bug report. please open it against https://github.com/kubernetes/dashboard/issues

/close
