### ISSUE TITLE
CRD deletion may fail if webhook conversion is not available

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#71925]
In case of conversion webhook failure, a list may not be possible on CRs but CRD deletion code tries to list and delete all CRs which may fail preventing CRD to be deleted.

A workaround is to set conversion to None for that CRD and delete it.

The fix would be to return a storage interface with None converter for CRD deleter to use.

**Comment by liggitt** [comment]
I don't think we can/should shortcircuit the conversion...

* if the customresource has a finalizer, it should be honored, which means persisting the object back to storage with a deletionTimestamp, which means successfully converting it to/from whatever version is in etcd to the current storageVersion
* watchers need to receive delete events, in the version they are watching, which means successfully converting from whatever is in etcd to the version they are watching

**Comment by liggitt** [comment]
I think this is actually working as designed (need to make sure the deletion recovers or can proceed once the webhooks is available again)

**Comment by yue9944882** [comment]
fallback to non-converter sounds fine. 

if we've decided to destroy a CRD, do we really have to hold until its webhook fixed? besides, the deleter required only the namespace/name of the listed CRs, it doesn't matter if the converion webhook fails to convert its content.

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/issues/71925#issuecomment-446118200 for reasons deletion needs the webhook working

**Comment by yue9944882** [comment]
> if the customresource has a finalizer, it should be honored

yes, but the finalizer exists in the object meta which doesn't require a converion. iiuc, the finailzers would still be honored we switched non-converter.

> watchers need to receive delete events, in the version they are watching, which means successfully converting from whatever is in etcd to the version they are watching

not sure about this one. from a user's perspective, why are we keeping the watchers (a controller or admission webhook whatever) running before we actually delete that CRD. 🤔

**Comment by liggitt** [comment]
Because we're about to delete the objects they are watching and we must inform them of that

**Comment by liggitt** [comment]
I do think we want tests to make sure behavior in this case is as expected, but I don't think using the no-op convertor is correct.

I'd expect deletion to fail when conversion is unavailable, and the CRD finalizer to retry until success

**Comment by mbohlool** [comment]
So to be clear, you are talking about the finalizers on the CRs not CRD. right?

I see your point and I agree that we should not do this in our code. The workaround is always there for the users that really need to delete the CRD with a failing webhook. @yue9944882, @sttts do you agree with just documenting workaround somewhere and close this?

**Comment by yue9944882** [comment]
@liggitt 's point is definitely making sense. i'm just wondering if such a strict CRD deletion will lead users to complain about that. sounds much better if we could clearly document that behavior.

**Comment by mbohlool** [comment]
I think we should add a section to documentation on "Failure modes".

**Comment by liggitt** [comment]
documentation and tests ensuring the behavior in that failure case works as expected sounds good to me

**Comment by liggitt** [comment]
included in https://github.com/kubernetes/website/pull/15982
