### ISSUE TITLE
add a new predicate: max replicas limit per node

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#71930]
**What would you like to be added**:
add a new predicate: max replicas limit per node 

**Why is this needed**:
I want to add a new predicate that supports this scene:
when we deploy a statefulset, we need control the replicas number of statefulset. Considered that the network, memory, disk IO are limited. we could appoint the number of replicas to deploy in one node. Anti-affinity could not help us control the accurate number clearly.

/kind feature

**Comment by zhangxiaoyu-zidif** [comment]
https://github.com/kubernetes/kubernetes/pull/71913#issuecomment-446061296

**Comment by wanghaoran1988** [comment]
@zhangxiaoyu-zidif Does this cover your issue ?https://github.com/kubernetes/kubernetes/issues/40358

**Comment by zhangxiaoyu-zidif** [comment]
@wanghaoran1988  thanks, that case is similar to mine. we can summary those needs, and make this feature convincing.

**Comment by zhangxiaoyu-zidif** [comment]
To summarize that:
case 1:
pre-planed env: we need to control the replicas per node to avoid too many pod scheduled to one node. In fact as to one node, its disk IO resource, disk quota, network bandwidth, and other resource are limited, so the accurate limited replicas number is needed.

case 2:
ClusterAutoscaler env: In CA when a replicaset/deployment is created and its pods cannot schedule due to lack of capacity new nodes are added. If the nodes used in the clusters are big enough it may happen that all replicas end up on a single node which is probably not the user wanted when creating pods with multiple replicas. If the user specifies hard pod anti-affinity it will get as many nodes as replicas which may lead to poor node utilization. copied from https://github.com/kubernetes/kubernetes/issues/40358#issue-202812972

case 3:
stability, the other use case is to ensure that not all pods go to a single rack as the rack may die at some time causing a big outage. On the other hand we don't want to have only ONE pod in a rack as there might not be enough racks.

case 3: the test env, disk IO(resource) insulation.  similar to case 1. copied from: https://github.com/kubernetes/kubernetes/issues/40358#issuecomment-274806926

**Comment by zhangxiaoyu-zidif** [comment]
@bsalamat @resouer  @k82cn 
if we have some plan to implement this feature, I could do some help.

**Comment by wgliang** [comment]
@zhangxiaoyu-zidif 
Thanks, the scene you described does exist, and I agree that we should cover this case. But I think we should consider this case from two dimensions, resource limitation and business limitation.

For the first case you mentioned, from the resource limitation, I think it is more biased towards resource planning. Even dIsk IO should consider whether it can calculate the remaining resources just like the number of CPU. We can consider how to measure this resource and filter it by predicate, but not directly calculate the current number of Pods.

In terms of business limitation, we want to limit the number of Pods on a single Node. We can enhance the current anti-affinity function or priority to calculate the number of Pods of the same type, so as to select a better node.

In general, if we solve the problem of resource limitation well, then the problem of business limitation may be less, unless we consider disaster tolerance. . .

**Comment by wgliang** [comment]
And are we still considering a wider range of Pod number limit, such as tor or zone?

**Comment by zhangxiaoyu-zidif** [comment]
>  Even dIsk IO should consider whether it can calculate the remaining resources just like the number of CPU. 

No, CPU resource is totally different from IO, bandwidth resource, resource isolation is rather urgent.

> We can enhance the current anti-affinity function or priority to calculate the number of Pods of the same type, so as to select a better node.

how could we calculate the number dynamically?  If we could not, accurate and static replicas number is preferred.

**Comment by xiaoxubeii** [comment]
IMO the anti-affinity is a better way to implement the hard constraints.

**Comment by zhangxiaoyu-zidif** [comment]
@xiaoxubeii 
Some app replicas have strong demands on some node resource. Maybe one replicas or two will occupies most of one kind resource, so spreading them is very necessary. anti-affinity only drains other replicas and remains one in this node, but sometimes we could deploy two replicas on this node. So setting one accurate number for the replicas is useful.

**Comment by Huang-Wei** [comment]
@zhangxiaoyu-zidif does PodAntiAffinity with topologyKey `kubernetes.io/hostname` resolve your issue?

**Comment by zhangxiaoyu-zidif** [comment]
yes， "kubernetes.io/hostname" could help. Should we add some more specified label for extend information. maybe we want to spread this replicas according data center, or even server rack and so on.

**Comment by xiaoxubeii** [comment]
There are some known labels in: https://github.com/kubernetes/kubernetes/blob/a6ba2ebf85d8673f78220c089aba1290437de2be/pkg/kubelet/apis/well_known_labels.go#L26-L28

**Comment by zhangxiaoyu-zidif** [comment]
@xiaoxubeii  yes, there some existed label, but we need more and even specifies some customized labels.

**Comment by evanmcclure** [comment]
/remove-lifecycle rotten

Having a replicaCount per node is still needed.

**Comment by evanmcclure** [comment]
Maybe a replicaCount anti-affinity?
