### ISSUE TITLE
tests: MaxContainerBackOff tests are flaky when using Windows nodes

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#71949]
**Which jobs are failing**:

N/A

**Which test(s) are failing**:

    [k8s.io] Pods  should cap back-off at MaxContainerBackOff [Slow][NodeConformance]
    [k8s.io] Pods  should have their auto-restart back-off timer reset on image update [Slow][NodeConformance]

**Since when has it been failing**:

Unknown. Tests are flaky when using Windows nodes.

**Testgrid link**:

N/A

**Reason for failure**:

When using Windows nodes, the mentioned tests might fail randomly due to the fact that Windows Kubelet might fail to report the new Pod Status before its execution finishes, causing the Pod Status to remain in ``CrashLoopBackOff`` state, which causes the tests to fail, since they're expecting the Pod to enter a ``Running`` State.

This could be solved by increasing the Pod's sleep period from 5 second to 10 seconds, allowing sufficient time for Kubelet to report the new ``Running`` state, or, instead of waiting for the ``Running`` state to occur, the tests should wait for the ``RestartCount`` to increase.

**Anything else we need to know**:

/sig windows

/kind failing-test

**Comment by adelina-t** [comment]
@fejta Can we please reopen this issue? It seems to get closed automatically because it gets referenced in some PRs that merge ( mainly Windows testing job related ), but the underlying issue is still under investigation.

**Comment by fejta** [comment]
Please use `/reopen` to reopen the issue. 

Please see the description of https://github.com/kubernetes/test-infra/pull/11230 and note that GitHub highlights the word res-lve next to this issue number. 

That caused GitHub to close this issue when you merged that PR (that's GitHub automation, not something out tooling does or can control). 

When a PR is related to an issue we tend to say "ref #11230". Please avoided using words like fix, resolve, etc around PR numbers.
