### ISSUE TITLE
Emit events when Daemonset fails to schedule pod due to hostport clash

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/kubernetes#71951]
**What would you like to be added**:
An event to be emitted when a daemonset pod fails to be place on a node due to a hostport clash
**Why is this needed**:
When deploying a daemonset it can be quite difficult to work out why it's not scheduling any pods when you have a hostport clash as it does not emit any events. 

It seems in the code this was purposefully prevented, it assumed hostport clashes were intentional due to the lack of hard pod anti-affinity, as this is now a feature I think it would be useful to have the event emitted for easier debugging. 

code here: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L1365 

I'm quite happy to raise a PR to change this.

/sig apps

/kind feature

**Comment by Joseph-Irving** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by wgliang** [comment]
That's a good point.
@k82cn @bsalamat

**Comment by k82cn** [comment]
which k8s version do you use? If enabled `Schedule daemonset pods by scheduler`, we should get such kind of events :)

**Comment by Joseph-Irving** [comment]
@k82cn ah I saw this on 1.11. I forgot the scheduler took over daemonset pod scheduling in 1.12 so I assumed that code I linked to was still being used. 

So yes with 1.12+ you get an event on the pod itself as it gets stuck in pending, as opposed to the event being on the Daemonset.
