### ISSUE TITLE
Keep indentations for kubectl -w command

### ISSUE THREAD

**Issue by tomasnorre** [kubernetes/kubernetes#71986]
**What would you like to be added**:

It would be great to keep indentations on `-w` e.g. kubectl get pods -w 

**Why is this needed**:

This would help getting a better overview when using the watch option. 

/kind feature

**Comment by vllry** [comment]
@tomasnorre I think you might be looking for https://github.com/kubernetes/kubectl

**Comment by tomasnorre** [comment]
Sorry my bad, you are right.
