### ISSUE TITLE
user without token have grant access

### ISSUE THREAD

**Issue by zyriuse75** [kubernetes/kubernetes#71995]
To connect to kubernetes I have to enter my token once connected I can do everything. 
I just realized that if I **click on skip**  instead of  enter my token on the kubernetes connection interface I am **connected** and I can do everything too :( .

I don't really know where to look to fix the problem. From what I've read, I have to look at kube-system and RBAC.
[screenshot ](https://ufile.io/mqid2)

sig/authentication

/triage support

**Comment by liggitt** [comment]
thanks for the report. this is tracked in https://github.com/kubernetes/dashboard/issues/2672 and being fixed in https://github.com/kubernetes/dashboard/pull/3400

/close
