### ISSUE TITLE
Azure node providerID for VMSS instances has inconsistent case

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#71994]
**What happened**:

```
sylvain@ubuntu-1604-dev:~/gopath/src/k8s.io/autoscaler/cluster-autoscaler[azure-zones]$ kubectl --context=k8s1-euw-sandbox --namespace=kube-system get nodes -o json | jq .items[].spec.providerID
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/K8S1-EUW-SANDBOX-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s1-euw-sandbox-agentzone3-vmss/virtualMachines/68"
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s1-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachines/k8s1-euw-sandbox-master-0"
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s1-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachines/k8s1-euw-sandbox-master-1"
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s1-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachines/k8s1-euw-sandbox-master-2"
```

**What you expected to happen**:

I expected the porviderID of my `virtualMachineScaleSets` instance to have the resourceGroups part in the same case as the `virtualMachines`, i.e.: `K8S1-EUW-SANDBOX-RG` -> `k8s1-EUW-sandbox-RG`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This inconsistency breaks the cluster-autoscaler.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.2
- Cloud provider or hardware configuration: Azure

/kind bug

**Comment by feiskyer** [comment]
This is actually the issues of VMSS API. I have reported the issues to the team.

**Comment by justaugustus** [comment]
@feiskyer -- Can we have this opened as an issue in Azure repo, so we can cross-reference?

**Comment by feiskyer** [comment]
@justaugustus The issues are because of VMSS internal. It'll be fixed soon (probably May) and I'll update status then.
