### ISSUE TITLE
kubelet not respects dnsconfig returned by cni

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#72019]
**What happened**:

kubelet didn't respect dns config returned by cni, it only uses what was specified by --cluster-dns or dns detected from host.

Was is by design?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by freehan** [comment]
WAI closing.
