### ISSUE TITLE
Error determining if node ip-172-31-22-208.us-west-2.compute.internal shutdown in cloud: Invalid format for AWS instance ()

### ISSUE THREAD

**Issue by iyacontrol** [kubernetes/kubernetes#72018]
**What happened**:
i meet `Error determining if node ip-172-xx-xx-208.us-west-2.compute.internal shutdown in cloud: Invalid format for AWS instance ()`  when i use cloud-provider=aws.  

**What you expected to happen**:  run well

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
1: iam policy 
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}`

2 : kubectl get node -o yaml

> apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2018-12-13T08:23:55Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: ip-172-xx-xx-208.us-west-2.compute.internal
    node-role.kubernetes.io/master: ""
  name: ip-172-xx-xx-208.us-west-2.compute.internal
  resourceVersion: "4241"
  selfLink: /api/v1/nodes/ip-172-xx-xx-208.us-west-2.compute.internal
  uid: 6e66b6cd-feb0-11e8-98ae-024eb1d0666e
spec:
  podCIDR: 192.168.0.0/24

**Environment**:
- Kubernetes version (use `kubectl version`): k8s1.13.0
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): Amazon Linux 
- Kernel (e.g. `uname -a`): Linux version 4.14.70-72.55.amzn2.x86_64
- Install tools: kubeadm
- Others:

/kind bug
/sig aws

**Comment by iyacontrol** [comment]
it looks like the cloud-provider=aws of kubelet didn't work.

**Comment by dcvtruong** [comment]
Hi, I'm seeing similar error on azure cloud-provider.

'''
E1003 18:04:29.450442       1 node_lifecycle_controller.go:803] Error determining if node ...-master-01 shutdown in cloud: failed to get power status for node "...-MASTER-01"
'''
