### ISSUE TITLE
gci-gce-scalability is flaky after migration to ClusterLoader

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#72016]
https://testgrid.k8s.io/sig-scalability-gce#gci-gce-scalability

ResourceConstraints is the biggest contributor.

**Comment by krzysied** [comment]
I looks like currently there were 4 causes of flakes:
- apiserver cpu constraint
 It increased slightly. I don't think it's a serious issue. I'm going to increase it's value (still lower then original test value).
- scheduler cpu constraint
I suspect is connected to resent scheduler changes. Parallelism inside scheduler was increased - more cpu should be used. Constraint should be adjusted.
- controller manager cpu constraint
There is already issue open for this. https://github.com/kubernetes/perf-tests/issues/326
- pod startup time
For a moment startup time increased from 4s to 16s. It looks like a real flake - it happened once. If it happens again I will investigate this case.

**Comment by krzysied** [comment]
Another flake I found is about incorrect json file. IIUC the real problem is with assumption that we have at least 100 nodes. When cluster is created with 99 nodes, the test calculates improperly.
https://github.com/kubernetes/test-infra/pull/10448 - add explicit node number to fix config calculations.

**Comment by jberkus** [comment]
Is this the reason for this error, or is that a new problem?

```
:0
[measurement call TestMetrics - TestMetrics error: [resource constraints: 1 constraints violated]]
:0
```

**Comment by wojtek-t** [comment]
@jberkus - yes. I already asked @krzysied offline to bump those limits - in the original PR I was also claiming they are too strict, and apparently I was right...

**Comment by krzysied** [comment]
@wojtek-t @jberkus There were some changes in clusterloader. Those changes resulted with increased  lb-controller cpu usage.
PR https://github.com/kubernetes/perf-tests/pull/352 will bump up resource constraint.

**Comment by jberkus** [comment]
I feel like we need somewhere to track these resource usage increases -- and for that matter, discuss them.

**Comment by wojtek-t** [comment]
@jberkus - we switched the way we run tests and there appeared that there were some differences. WSo we understand them and that was expected.

**Comment by wojtek-t** [comment]
@krzysied - resource usage measurement is still flaky; please adjust

**Comment by krzysied** [comment]
@wojtek-t I looked through the latest flakes. All resource related flakes are because of apiserver and controller manager cpu constraints. https://github.com/kubernetes/perf-tests/pull/363 will bump up these constraints.

**Comment by wojtek-t** [comment]
It seems to be pretty healthy now.
