### ISSUE TITLE
Hyperkube sigterm not working for kube-proxy, kube-controller-manager, kube-scheduler

### ISSUE THREAD

**Issue by flarno11** [kubernetes/kubernetes#72029]
**What happened**:
The signal SIGTERM has no effect for `hyperkube kube-proxy`, `hyperkube kube-controller-manager`, `hyperkube kube-scheduler`.

**What you expected to happen**:
Same behavior for all the components, sending SIGTERM once shuts down the components correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Start `hyperkube kube-proxy`, press Ctrl-C, doesn't work, press Ctrl-C again kills the process. Start `hyperkube kubelet`, press Ctrl-C stops the process immediately.

**Anything else we need to know?**:
For `hyperkube kubelet`, `hyperkube kube-apiserver` it seems to work fine. Sending the signal twice works as well, probably with panic.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.4, 1.12.3
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Redhat 7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: Manual, Systemd
- Others:

/kind bug

**Comment by mritd** [comment]
1.13.4 have the same problem

**Environment:**

- Kubernetes version (use kubectl version): 1.13.4
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Ubuntu 18
- Kernel (e.g. uname -a): 4.15.0-46-generic
- Install tools: Manual, Systemd
- Others:
