### ISSUE TITLE
pod status is “ExitCode：0” in kubectl get pod

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#72020]
**What happened**:
![image](https://user-images.githubusercontent.com/5154334/49929540-b31cf300-fefd-11e8-89c6-8af0e3eab14f.png)

**What you expected to happen**:
express the status correctly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by Pingan2017** [comment]
It seems to mean your containers exited with code 0
https://github.com/kubernetes/kubernetes/blob/83f115ec799ae5fad11dc5920c36354fb6653e96/pkg/printers/internalversion/printers.go#L640-L645

**Comment by liggitt** [comment]
this is working as intended, to indicate more information about the termination reason than just Terminated

/close

**Comment by zhangxiaoyu-zidif** [comment]
so could we add the container name in this status to make it more clear.
