### ISSUE TITLE
gce-cos-1.11-serial and node-kubelet-1.11 blocking tests failure

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#72036]
**Which jobs are failing**: 

https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-cos-1.11-serial
https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#node-kubelet-1.11

**Which test(s) are failing**:
* [sig-storage] PersistentVolumes-local Stress with local volume provisioner [Serial] should use be able to process many pods and reuse local volumesChanges
* [k8s.io] Variable Expansion should allow substituting values in a volume subpath [Feature:VolumeSubpathEnvExpansion][NodeAlphaFeature:VolumeSubpathEnvExpansion] [cos-stable2]
* [k8s.io] Variable Expansion should allow substituting values in a volume subpath [Feature:VolumeSubpathEnvExpansion][NodeAlphaFeature:VolumeSubpathEnvExpansion] [ubuntu]
* [k8s.io] Variable Expansion should allow substituting values in a volume subpath [Feature:VolumeSubpathEnvExpansion][NodeAlphaFeature:VolumeSubpathEnvExpansion] [cos-stable1]
* [k8s.io] Variable Expansion should allow substituting values in a volume subpath [Feature:VolumeSubpathEnvExpansion][NodeAlphaFeature:VolumeSubpathEnvExpansion] [coreos-alpha]

This is blocking the release of 1.11.6

/kind failing-test
/priority critical
/sig storage
/sig node

**Comment by foxish** [comment]
cc @msau42 @Random-Liu @krzyzacy

**Comment by msau42** [comment]
VariableExpansion tests are an alpha feature and should not be run in this suite

**Comment by liggitt** [comment]
Feature:VolumeSubpathEnvExpansion is an alpha feature which is disabled by default. why is it being included in a non-alpha run?

**Comment by foxish** [comment]
I see, perhaps it's missing the regex in the suite definition - I'll take a look. @msau42 the serial test failure in https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-cos-1.11-serial still looks legitimate.

**Comment by foxish** [comment]
Appears to have triggered after https://github.com/kubernetes/kubernetes/pull/71933

**Comment by foxish** [comment]
Reverted #71933 and that fixed the cos-serial test issue.
Removing the alpha feature test needs a sig-node approver - https://github.com/kubernetes/test-infra/pull/10436

@yujuhong PTAL

**Comment by foxish** [comment]
Fixed, 1.11.6 has been released.
