### ISSUE TITLE
Scheduler preemption: take pod's StartTime into account when select potentialVictims

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#72039]
**What would you like to be added**:
When selecting victims on node in `selectVictimsOnNode`(https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L982), take pod's `StartTime` into account. When two pod's Priority is equal, preempt pod whose `StartTime` is later first. 

**Why is this needed**:
 If a pod's `StartTime` has been running for a longer time, it might finish earlier, or it might have done more things. It might make more sense to preempt them later, e.g. a user submitted a job A at time 9:00 am,  then he submitted a job B at time 10:00 am, he might expect that scheduler preempts pods for job B first.

/kind feature

**Comment by hex108** [comment]
/sig scheduling
/assign @hex108 
cc @bsalamat

**Comment by bsalamat** [comment]
PR #74974 implements this feature. We are currently in code freeze for 1.14. The feature will be in 1.15.

**Comment by hex108** [comment]
Thanks @bsalamat for it. It is similar with a little difference, the PR #74974 aims to select a node, and this issue aims to pick a pod whose StartTime is latter after the node has been selected.

**Comment by hex108** [comment]
@bsalamat I just sent a PR for it. PTAL :)
