### ISSUE TITLE
Add GetFullContainerName to ContainerRuntime API

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#7204]
This is required for cAdvisor and monitoring to map cgroup stats to Pod and container. We don't need this in the future version once we have pod_level resource management. But today we don't have it. 

cc/ @vmarmol @yifan-gu

**Comment by xiangpengzhao** [comment]
@dchen1107 is this issue valid? If not (seems likely), we can close it :)

**Comment by vbmade2000** [comment]
@dchen1107 Do we still need it ?
