### ISSUE TITLE
Failed to unmount nfs when connection was lost

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#72048]
**What happened**:

__NFS Background__: Most operations on nfs mountpoint will hang if the connection to nfs server is lost.

When tearing down pod kubelet tries to unmount all volumes pod have mounted. There are some operations kubelet would done like stat/unmount mntpoint etc. At that moment, the  stat/unmount codes would hang forever if connection to nfs server is lost, though it may recover when the connection is reconnected.

**What you expected to happen**:

No matter what happened to NFS server, kubelet tears down pods along with their nfs volumes successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. setup a nfs service
2. create a pod with above nfs volume mounted
3. teardown nfs service
4. destroy pod

kubelet will hang at step 4 and output message related to unmount volume

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by sikhlaqu** [comment]
@linxiulei 
**What is the current workaround for this issue ?**

We have a customer complaining about this,  when his firewall goes down, all his NFS storage hangs and they dont recover even after the Firewall is restored/back and when he deletes his Application PODs, they always remain in "terminating state" (kube 1.12 + containerd runtime). POD describe shows _"Killing container with id containerd://mobilitx:Need to kill Pod ..."_

---solution we tried---
            A **"--force"**  delete POD doesn't remove the actual running container. Hence the only solution, we see is **NODE reboot**. But when many Nodes are impacted, its not desirable.  **Is there any alternative ?**

**During your test, are those terminating POD disappeared, when NFS connectivity was back ?** but Our case, its not back.

Will this fix solve the above issue ? and what is the timeline and release  for this fix rollout ?

**Comment by zrss** [comment]
thx for pointing this out. i confirm that hang will happen when nfs server down or there is a network problem

and i have another question that how the nfs client handle the *crash* of the nfs server, specially, after a long down time, can it still be auto-recover ?

**Comment by linxiulei** [comment]
I guess it’s a linux blkio subsystem flaw that most of io issue would cause hang. I have gave a short period of downtime testing though, the nfs client auto recovered

**Comment by zrss** [comment]
ok, i find this out, it seems it will always retry in default mode

![image](https://user-images.githubusercontent.com/8072378/52548425-92dbb880-2e08-11e9-8763-fa9642a05f5d.png)

thanks anyway

**Comment by h0jeZvgoxFepBQ2C** [comment]
So the only solution is to reboot the node or kubelet? We are getting hit by this very often and it really makes problems for our system...
