### ISSUE TITLE
Figure out a way to run e2e tests against Rocket

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#7205]
Rocket folks already have e2e run on AWS. We need to have similar setup to run on GCE. cc/ @yifan-gu Please cc this one to Brian (I dont have his github account)

**Comment by bakins** [comment]
Slight clarification: we are currently working on full e2e test runs on CoreOS with Docker on AWS. Close to completing this.  Should be straightforward to replicate this on GCE.

The goal is to run e2e tests on CoreOS on multiple cloud providers using both rkt and docker.

**Comment by roberthbailey** [comment]
It would be great to get the e2e test runs automated and the results collected into a common dashboard. See #6605. @justinsb

**Comment by bakins** [comment]
The extremely early CoreOS additions for e2e: https://github.com/bakins/kubernetes/tree/coreos/cluster/coreos-aws

No where near ready to open a PR.  Tests do not pass as some tests check for the "aws" provider and include/exclude tests based on that.  I know a few people are thinking about "hierarchal" providers and how to integrate with the tests.

**Comment by pmorie** [comment]
It's possible there will be some E2E tests (ie, the one specifically for docker entrypoint control) that don't apply to rocket.  We will need some way to differentiate them.

**Comment by dchen1107** [comment]
cc/ @yifan-gu @jonboulle

We should categorize existing tests into 3 categories:
* Test should pass with rkt and it does
* Test should pass with rkt, but not yet
* Test is not applicable for rkt

Then later we can add forth one including tests specifically for rkt too.

**Comment by yifan-gu** [comment]
@dchen1107 sgtm. I am going to take the work.

**Comment by pmorie** [comment]
Awesome @yifan-gu

**Comment by mikedanese** [comment]
I agree that this is stale.

**Comment by mikedanese** [comment]
Coreos is running e2e on rkt.

**Comment by yifan-gu** [comment]
:tada: :tada: :tada: @euank
