### ISSUE TITLE
Almost useless error message.

### ISSUE THREAD

**Issue by steigr** [kubernetes/kubernetes#72058]
**What would you like to be added**:
Add the new path `/var/lib/kubelet/plugins_registry` and maybe the old to the error message.

**Why is this needed**:
The error-message is normally not in context e.g. container/pod log output, thus lacking documentation and references.

/kind feature

**Comment by Shnatsel** [comment]
Could you clarify what error message you are referring to and provide steps to reproduce it? I'm afraid this report is not actionable as-is.
