### ISSUE TITLE
suggestion for pod qos

### ISSUE THREAD

**Issue by yanghaichao12** [kubernetes/kubernetes#72075]
**What would you like to be added**:
    now pod qos is defined according to 'resources requests  and 'limits'  in container specification. if a pod has more than one container, we must write it many times. like that:
`    "spec": {
        "replicas": 2,
        "selector": {
            "name": "ubuntu-test-pod"
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "name": "ubuntu-test-pod"
                }
            },
            "spec": {
                "containers": [
                    {
                        "command": [
                            "sleep",
                            "86400"
                        ],
                        "image": "ubuntu:v1",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "ubuntu-test",
                        **_"resources": {
                            "limites": {
                                "cpu": "500m"
                            }_**
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File"
                    },
                    {
                        "command": [
                            "sleep",
                            "7200"
                        ],
                        "image": "ubuntu:v1",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "ubuntu-cgroup",
                        **_"resources": {
                            "limites": {
                                "cpu": "600m"
                            }_**
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File"
                    }
                ],
`

**Why is this needed**:
          can we just specify one time for one pod? and all PIDs of pod are put in one cgroup?

/kind feature

**Comment by ipuustin** [comment]
Already the QoS classes work in a somewhat more complex way. The docs say that for a `guaranteed` pod, **every** container in a pod must have matching memory and CPU resource requests and limits. However, for a `burstable` pod, **at least one** container must have a memory or CPU request.
