### ISSUE TITLE
Make PodFilter as part of public API

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#72078]
**What would you like to be added**:

Make `scheduleinternalcache.PodFilter` as public.

**Why is this needed**:

`algorithm.PodLister` is public, so we should not dependent on an internal interface. The case is that https://github.com/kubernetes-sigs/kube-batch can not use `predicates.NewPodAffinityPredicate` with a customized `PodLister` :(

/sig scheduling

xref https://github.com/kubernetes/kubernetes/issues/68951

/kind feature

**Comment by denkensk** [comment]
I want to take it.

**Comment by denkensk** [comment]
@k82cn  I wonder if there is something wrong with my understanding? I find Scheduleinternalcache.PodFilter is already public.  
```
// PodFilter is a function to filter a pod. If pod passed return true else return false.
type PodFilter func(*v1.Pod) bool
```
Can you give me more information about this issue？Thank you so much~
/remove-help

**Comment by k82cn** [comment]
> I find Scheduleinternalcache.PodFilter is already public.

It's in `internal` package

**Comment by denkensk** [comment]
> > I find Scheduleinternalcache.PodFilter is already public.
> 
> It's in `internal` package
Thank you, I see.  Can I solve this problem by moving PodFilter from package Scheduleinternalcache to 
package algorithm？
@k82cn

**Comment by k82cn** [comment]
just move PodFilter should be enough, and avoid recycle dependent.
