### ISSUE TITLE
How to expose Kube-dns as type: LoadBancer

### ISSUE THREAD

**Issue by devops083** [kubernetes/kubernetes#72086]
Hello,

I am implemeting ISTIO-mesh expansion in kubernetes (AWS)
as part of this I need to expose Kube-dns service.

so I tried to created a kube-dns service with type: LoadBalancer but an unable to get external IP its in pending state.

apiVersion: v1
kind: Service
metadata:
  name: dns-ilb
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  type: LoadBalancer
  ports:
  - port: 53
    protocol: UDP
  selector:
    k8s-app: kube-dns

kubectl get svc -n kube-system
NAME                                 TYPE               CLUSTER-IP      EXTERNAL-IP   PORT(S)            AGE
dns-ilb                            LoadBalancer      xx.xx.xx.xx         <pending>     53:30749/UDP    28m
kube-dns                         ClusterIP            xx.xx.xx.xx         <none>          53/UDP,53/TCP   1h

so why dont we expose kube-dns with type: LoadBalancer????

**Comment by Shnatsel** [comment]
Hello!

As a rule of thumb, questions regarding configuration should go to StackOverflow where they get a lot more visibility, and thus get resolved much faster. [Click here](https://stackoverflow.com/questions/ask) to ask a question on StackOverflow. Please tag it "kubernetes", "istio" and "amazon-web-services".

/triage support
/meow space

**Comment by thockin** [comment]
There's not enough info here to help.

In general, `type: LoadBalancer` costs money, so we do not enable it by default.  That said, nothing stops YOU from doing it.  I can't speak to whether it works on AWS or not, but Kubernetes should allow it.  What errors are you getting?

Also, yes, this would be better at StackOverflow.
