### ISSUE TITLE
E2E storage: dynamically determine test volume size

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#72080]
**What would you like to be added**:

`test/e2e/storage/testsuites` creates volumes dynamically. Initially, the size of those volumes was hard-coded in the test, which prevented using the tests with storage backends that couldn't support that hard-coded size.

https://github.com/kubernetes/kubernetes/pull/70862 introduces a mechanism where the driver for the storage backend can set the size.

But this still has the problem that the size chosen by the driver might not work for some tests. A better solution would be to let the driver and each test specify a size range, then when setting up the volume for a specific test, the actual size gets chosen by looking at the intersection.

**Why is this needed**:

Some tests might fail when the chosen size is too small or too large? Mostly a theoretic issue at this point, it hasn't happened in practice yet.

/kind feature

**Comment by srmocher** [comment]
Can this be assigned to me. I can start working on this with the provided context.

**Comment by srmocher** [comment]
I'm relatively new to the code base so apologies if I'm wrong about my assumptions.
If I understand correctly, we'd like to avoid harcoding exact volume sizes in tests like [this](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/provisioning.go#L154) and use size ranges for both the test and driver for the backend and then use the value which works for both(intersection)?

**Comment by mkimuram** [comment]
@srmocher 

Thank you very much for working on this!

> If I understand correctly, we'd like to avoid hardcoding exact volume sizes in tests like this and use size ranges for both the test and driver for the backend and then use the value which works for both(intersection)?

Correct.

For detailed background, please check comments to ```GetClaimSize()``` on "e2e/storage: drivers determine the claim size" commit in below link.
https://github.com/kubernetes/kubernetes/pull/70862/commits 

Also, if there are any questions, please feel free to ask me.

**Comment by srmocher** [comment]
@mkimuram I've tried to put together something resembling the proposed solution here https://github.com/kubernetes/kubernetes/pull/72275 to address this issue. I don't have full context on some things like setting the ranges/driver and per test - happy to get feedback and improve it.
