### ISSUE TITLE
The kubectl cluster-info dump does not work with  --namespace flag

### ISSUE THREAD

**Issue by mszostok** [kubernetes/kubernetes#72088]
**What happened**:
The `kubectl cluster-info dump` does not work properly when **--namespace** flag is specified.

If you specify the **--namespaces** flag to dump given namespace then only the list of Nodes are dump. Other information about Services, Pods etc. are not available.

The problem was introduced by [this](https://github.com/kubernetes/kubernetes/commit/b7d4f159652ad4cc55f6cc666e3f2bf67c451890#diff-d04e8f9e706881e9fd22051b093cb758L149) changed.

**What you expected to happen**:
When `kubectl cluster-info dump --namespaces=<namespace_list>` command is executed then all information is dump.

**How to reproduce it (as minimally and precisely as possible)**:

Execute command `kubectl cluster-info dump --namespaces=<namespace_list>`.

**Anything else we need to know?**:

`-`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
_unrelated_
- OS (e.g. from /etc/os-release):
_unrelated_
- Kernel (e.g. `uname -a`):
_unrelated_
- Install tools:
_unrelated_
- Others:

/kind bug

**Comment by juanvallejo** [comment]
bot didn't seem to pick up /assign. Let's try again

/assign pandyamarut

**Comment by mszostok** [comment]
@juanvallejo FYI: please take in mind that PR for fixing this issue was already created 39 days ago. PR fixes kubectl cluster-info dump command and adds test coverage to never regress. It needs to be only reviewed. I posted that information twice on slack cli channel :)

**Comment by mszostok** [comment]
still valid

**Comment by wallrj** [comment]
Still not fixed. The fix in https://github.com/kubernetes/kubernetes/pull/72090 was never merged.

/reopen

**Comment by soltysh** [comment]
@mszostok still interested in fixing it? If so pls open a PR and ping me on slack

**Comment by janekmichalik** [comment]
anyone? Still does not work.

**Comment by eddiezane** [comment]
This appears to be fixed by https://github.com/kubernetes/kubernetes/pull/91890

/close
