### ISSUE TITLE
Add Verb match support for ABAC

### ISSUE THREAD

**Issue by lovejoy** [kubernetes/kubernetes#72097]
**What would you like to be added**:
verb  list match for abac
**Why is this needed**:
Like ReadOnly feature ,we need a CreateOnly feature to limit the delete request   ,and this can be describe as a verb list, And I found  https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/abac/abac.go#L175
there still a todo here.May be we should implement this?

/kind feature

**Comment by lovejoy** [comment]
@liggitt

**Comment by liggitt** [comment]
Since the stabilization of the RBAC authorizer, new features are not being added to the ABAC authorizer. We can remove that TODO.

**Comment by lovejoy** [comment]
@liggitt  Actually I want to limit user can only WriteOnly to resources of some namespaces with same prefix( the user may create many same prefix namespaces). And this can't be solved by  RBAC as it 's designed for exists and known namespace.And I think  it's easier to be implement in ABAC https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/abac/abac.go#L212 just change this line to support same prefix namespaces and add verb match for abac
Any advice  for this ?

**Comment by liggitt** [comment]
Authorizers do not have access to the name of the object being created (since it is not present in the API call URL). A [webhook admission plugin](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) could be used to limit creation requests to specific namespaces and resources.
