### ISSUE TITLE
Kube-Proxy use ipvs proxy-mode blocks ipv6 nodePorts when running in ipv4 mode

### ISSUE THREAD

**Issue by hegnee** [kubernetes/kubernetes#72098]
**What happened**:

I created a nodeport service `nginx-app-svc`
```
# kubectl get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes      ClusterIP   10.68.0.1       <none>        443/TCP        3d
nginx-app-svc   NodePort    10.68.191.131   <none>        80:39334/TCP   3d
```
use netstat get info: 
```
# netstat -nltpu| grep 39334
tcp6      21      0 :::39334                :::*                    LISTEN      9392/kube-proxy 
```

I have a ipv6 address eth0: `fb80::301f:6df2:9df6:81b2/64`
 use curl to access 
`curl -g http://[fb80::301f:6df2:9df6:81b2]:39334`
it's blocking

**What you expected to happen**:
I can use ipv6 address to access  `nginx-app-svc ` 
**How to reproduce it (as minimally and precisely as possible)**:
kube-proxy config:
```
[Unit]
Description=Kubernetes Kube-Proxy Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=network.target

[Service]
WorkingDirectory=/var/lib/kube-proxy
ExecStart=/opt/kubernetes/bin/kube-proxy \
  --bind-address=:: \
  --hostname-override=csdpaas5 \
  --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig \
  --logtostderr=true \
  --proxy-mode=ipvs  \
  -v=5
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```
**Anything else we need to know?**:
CNI: calico v3.3.1
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`Bare`
- OS (e.g. from /etc/os-release):
`CentOS Linux release 7.3.1611 (Core) `
- Kernel (e.g. `uname -a`):
`Linux csdpaas5 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
None
- Others:

/kind bug

**Comment by Shnatsel** [comment]
Dual-stack support in k8s is very limited right now, see #62822.

Also, in my experience nginx is incredibly capricious when it comes to IPv6, and will require tuning its configs in very specific and arcane ways to work. I would start by SSHing into the container and checking if nginx can serve pages over IPv6 inside the container, without Kubernetes in the way.

**Comment by Shnatsel** [comment]
@kubernetes/sig-network is this a duplicate of #62822 or not?

**Comment by thockin** [comment]
@m1093782566

**Comment by thockin** [comment]
While we actually do open the port in kube-proxy (which is why netstat sees it at all), we use iptables rules to handle traffic, and those are single-family only.  No dual-stack yet.
