### ISSUE TITLE
kubectl exec does not support resource/name format

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#72104]
Unfortunately, not even `pod/pod-name` is supported which makes using `kubectl exec` in scripts very annoying.

@kubernetes/sig-cli-feature-requests

**Comment by prksu** [comment]
kubectl exec is only for pod, I don't think adding a resource/name format is necessary.

**Comment by masatomo** [comment]
:+1: `kubectl port-forward` now supports resource/name to select a pod. https://github.com/kubernetes/kubernetes/pull/59705

that would be great if `kubectl exec` supports it as well.

**Comment by soltysh** [comment]
@prksu go for it
