### ISSUE TITLE
Kubelet reporting out of disk space while log shows ample space available

### ISSUE THREAD

**Issue by bb-acarrera** [kubernetes/kubernetes#72108]
**What happened**:
Worker node reported OutOfDisk Space status when it appears plenty of space was available.

Below is the `kubectl describe node` showing the transition time was Sat, 15 Dec 2018 14:44:01
```
OutOfDisk        False   Mon, 17 Dec 2018 09:11:24 -0500   Sat, 15 Dec 2018 14:44:01 -0500   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Mon, 17 Dec 2018 09:11:24 -0500   Sat, 15 Dec 2018 14:44:01 -0500   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 17 Dec 2018 09:11:24 -0500   Sat, 15 Dec 2018 14:44:01 -0500   KubeletHasNoDiskPressure     kubelet has no disk pressure
```

Reviewing the Kubelet logs on that host it appears to be reporting ample amount of space at that time:

```
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458336   10267 helpers.go:840] eviction manager: observations: signal=nodefs.inodesFree, available: 104784331, capacity: 104856384, time: 2018-12-15 14:44:01.443961533 -0500 EST m=+1035337.335369630
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458385   10267 helpers.go:840] eviction manager: observations: signal=imagefs.available, available: 235237284Ki, capacity: 309504832Ki, time: 2018-12-15 14:44:01.443961533 -0500 EST m=+1035337.335369630
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458394   10267 helpers.go:840] eviction manager: observations: signal=imagefs.inodesFree, available: 19659524, capacity: 19200Ki, time: 2018-12-15 14:44:01.443961533 -0500 EST m=+1035337.335369630
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458400   10267 helpers.go:840] eviction manager: observations: signal=pid.available, available: 64914, capacity: 64Ki, time: 2018-12-15 14:44:01.457710222 -0500 EST m=+1035337.349118244
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458407   10267 helpers.go:840] eviction manager: observations: signal=memory.available, available: 41292464Ki, capacity: 49295348Ki, time: 2018-12-15 14:44:01.443961533 -0500 EST m=+1035337.335369630
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458415   10267 helpers.go:840] eviction manager: observations: signal=allocatableMemory.available, available: 46779628Ki, capacity: 49295348Ki, time: 2018-12-15 14:44:01.458210542 -0500 EST m=+1035337.349618568
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458424   10267 helpers.go:840] eviction manager: observations: signal=nodefs.available, available: 85200416Ki, capacity: 104846172Ki, time: 2018-12-15 14:44:01.443961533 -0500 EST m=+1035337.335369630
Dec 15 14:44:01 ip-1-70-237-11.dob1.bcpc.bloomberg.com kubelet[10267]: I1215 14:44:01.458472   10267 eviction_manager.go:336] eviction manager: no resources are starved
```
**What you expected to happen**:

Provide in the Kubelet logs a more detailed description of what is out of disk space at the time of setting the status.  Additionally the information should also appear as an event in `kubectl describe node`.  Given the above logs it would appear this is a false alarm, but without further logging it's hard to say that conclusively.

**How to reproduce it (as minimally and precisely as possible)**:

Unclear, this appears to happen randomly on our k8s cluster.

**Anything else we need to know?**:
We do not see evictions from this message.  
**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.5
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): RHEL 7.3
- Kernel (e.g. `uname -a`):  3.10.0-514.6.1.el7.x86_64
- Install tools:
- Others:

/kind bug

**Comment by Shnatsel** [comment]
Could you clarify where exactly do you see the OutOfDisk Space status reported?

**Comment by bb-acarrera** [comment]
We have a custom (closed source) task that queries that monitors the state of the nodes and alerts on changes in status.

**Comment by Shnatsel** [comment]
Could you specify how the closed-source task gets that information? Does it query some API, or run df, or something else?

Both kubectl output and kubelet logs report that there is disk space available, which appears to be correct. We'd need to understand what exactly reports that disk space is not available to debug this.

**Comment by bb-acarrera** [comment]
The task queries the node status from the api server.  It specifically looks at the transition time for the different statuses to determine if something has changed.
