### ISSUE TITLE
Kubelet doesn't reattempt RBD mount

### ISSUE THREAD

**Issue by andor44** [kubernetes/kubernetes#72107]
**What happened**:
We have a pod (created by a CronJob) that wants to mount an RBD-backed volume. Occasionally, the pod is stuck in `ContainerCreating` status with the following message:

```
Warning  FailedMount  4s (x2435 over 3d20h)  kubelet, <nodename>  Unable to mount volumes for pod "<podname>(<pod UID>)": timeout expired waiting for volumes to attach or mount for pod "<namespace>"/"<podname>". list of unmounted volumes=[<rbd volume>]. list of unattached volumes=[<rbd volume> <default service account token>]
```

As you can see this pod has been stuck in such a state for almost 4 days. The RBD volume is **definitely** not in use at the moment by another pod, but it was in use **in the past**. We've noticed that more often than not the RBD image was mounted on the same node the last time the job ran, but this is not always the case.

When we do an `$ rbd status <image name>` we can see that the image is being watched by the node it should be mounted by but it is **not** mapped on that node (or anywhere else).

We do not see _any_ messages related to RBD in the kubelet's logs. It's as if the kubelet isn't even reattempting to map/mount the image. Restarting the kubelet will solve the problem immediately, the volume is mapped straight away and the pod starts fine.

**What you expected to happen**:
To always mount the RBD volume, or reattempt if necessary, without having to manually restart the kubelet to get it to mount it.

**How to reproduce it (as minimally and precisely as possible)**:
I don't have a good repro case unfortunately. The fact that pod/mount "turnover" is high because these are pods created by a cronjob seems to be a factor, but I don't have factual evidence to support this hypothesis.

**Anything else we need to know?**:
The ceph credentials used by k8s have the auth capabilities properly set:

```
client.REDACTED
	key: REDACTED
	caps: [mon] profile rbd
	caps: [osd] profile rbd pool=<poolname>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.11
- Cloud provider or hardware configuration: Bare metal/self-hosted VMs
- OS (e.g. from /etc/os-release): CoreOS stable
- Kernel (e.g. `uname -a`): `4.14.81-coreos`
- Install tools: Our own ansible scripts
- Others: `ceph version 12.2.8 (luminous)`, latest external-storage RBD provisioner

/kind bug
/sig storage
/sig node

**Comment by andor44** [comment]
This is still an issue on at least 1.11.7 (with updated CoreOS stable, 1967.6.0)

**Comment by andor44** [comment]
/remove-lifecycle stale
Still an issue

**Comment by fmors** [comment]
This is also an issue on K8s v1.12.8.

I have a CronJob that creates a job that makes a dump of a mongo database into an EFS. The first jobs started by this CronJob and their corresponding pods work fine, but after a few jobs it starts to give the same mount errors:

Unable to mount volumes for pod "<pod name>": timeout expired waiting for volumes to attach or mount for pod "<pod>". list of unmounted volumes=[backup-efs]. list of unattached volumes=[<volume name>].

Is there a fix already available for this? Or a workaround?
