### ISSUE TITLE
kube-apiserver 1.12.3 running as a container in Docker connects to ipv6 localhost (and fails)

### ISSUE THREAD

**Issue by mhulscher** [kubernetes/kubernetes#72109]
**What happened**:
I start the kube-apiserver docker image. When it tries to connect to itself on localhost it fails with an error. This happens regardless of whether IPv6 is enabled or disabled in either or bothe linux kernel and the docker daemon. This does not happen in Kubernetes =<1.11

```F1217 14:46:29.285877       1 controller.go:148] Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://localhost:6443/api/v1/services: dial tcp [::1]:6443: connect: cannot assign requested address```

**What you expected to happen**:

kube-apiserver to start

**How to reproduce it (as minimally and precisely as possible)**:

```$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:16:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:16:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker run --rm -d --name etcd quay.io/coreos/etcd:v3.3 /usr/local/bin/etcd --advertise-client-urls=http://0.0.0.0:2379 --listen-client-urls=http://0.0.0.0:2379

$ docker run -ti --link etcd gcr.io/google-containers/kube-apiserver:v1.12.3 /usr/local/bin/kube-apiserver --etcd-servers=http://etcd:2379
...
F1217 14:57:30.143527       1 controller.go:148] Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://localhost:6443/api/v1/services: dial tcp [::1]:6443: connect: cannot assign requested address
```

**Anything else we need to know?**:

Also tried combinations of `--bind-address=0.0.0.0` and `--advertise-address=127.0.0.1` on the `kube-apiserver`

Seems to work on docker-for-windows 18.09.0.

I am unsure how to proceed. Any tips or suggestions would be greatly appreciated.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.12.3`
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): `container-linux 1911.4.0`
- Kernel (e.g. `uname -a`): `4.14.81-coreos`
- Install tools:
- Others:

/kind bug

**Comment by mhulscher** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by thockin** [comment]
@leblancd 

@kubernetes/sig-network-bugs

**Comment by fedebongio** [comment]
/remove-sig api-machinery 
(waiting for networking to triage)

**Comment by cmluciano** [comment]
@mhulscher Can you add a bit more information about your setup so that I can try to replicate? Are you launching containers with docker run and are you using flannel for your CNI?

**Comment by thockin** [comment]
I can not reproduce this at all with Docker 18.09.4

Can you help us to narrow it down?  Do your docker runs have IPv6 addresses assigned?

`docker run -ti gcr.io/google-containers/kube-apiserver:v1.12.3 ip addr`
