### ISSUE TITLE
Bump kubernetes-cni plugins version

### ISSUE THREAD

**Issue by rmb938** [kubernetes/kubernetes#72103]
**What would you like to be added**:

Bump the kubernetes-cni packages to version 0.7.4 of the CNI plugins

**Why is this needed**:

I require these options from the portmap plugin https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap

```
conditionsV4, conditionsV6 - array of strings. A list of arbitrary iptables matches to add to the per-container rule. This may be useful if you wish to exclude specific IPs from port-mapping
```

These options were released in v0.7.0-rc1

/kind feature

I can override the binaries manually for now however anytime kubernetes-cni update it will override my changes so I rather have the kubernetes-cni packages updated.

**Comment by rmb938** [comment]
@kubernetes/sig-release-feature-requests

Not sure if that is the correct sig, couldn't find one that specifically manages the dep and rpm packages

**Comment by Shnatsel** [comment]
Could you clarify what repository/repositories you're using? This would help determine the proper point of contact.

**Comment by rmb938** [comment]
The `kubernetes-cni` rpm available in this repository https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

I am also assuming updating the debian version at the same time would be preferred
