### ISSUE TITLE
Race condition in preemption logic of the scheduler when setting nominatedNodeName 

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#72124]
**What happened**:
Setting nominatedNodeName has an inherent race:
1. The scheduler tries a pod and finds it unschedulable.
1. The preemption logic tries and finds a node to schedule the pod (with or without preempting any other pod).
1. The scheduler sends a pod update to update nominatedNodeName of the pod.
    The scheduler has NOT received the pod update for setting "nominatedNodeName" yet.
1. The scheduler tries another pod and finds the same node schedulable. So, it binds the second pod.
1. The nominated Pod has the nominatedNodeName set, but the resources on the node are already taken by another pod, so the nominated pod is no longer schedulable on that node.

The race that I described above can cause an issue:
1. There is a pod which has nominatedNodeName, but is affected by the above race.
1. A smaller pod with the same priority is scheduled on the same node (due to the above race condition).
1. There is enough room on the node for other small pods, but since there exists a nominated pod for the node, other smaller pods won't be scheduled there. The nominated pod cannot be scheduled there either, because the available resources are partially taken by the other smaller pod and there are not enough resources for the nominated pod.

**What you expected to happen**:

The race condition in setting nominatedNodeName must be eliminated. We should use a similar approach to "assume" to update the scheduler cache with nominated pods early and not wait for pod status updates.

/kind bug

/sig scheduling
/assign

**Comment by Huang-Wei** [comment]
I’m even thinking of it more aggressively: if it’s possible to only keep NominatedNode status in memory.

**Comment by bsalamat** [comment]
@Huang-Wei It cannot be kept only inside scheduler's memory. It could, if we didn't care about multi-scheduler support. Since we want to inform other schedulers that there is a pod waiting for the resources, we must mark the nomination in the object.

**Comment by Huang-Wei** [comment]
> It could, if we didn't care about multi-scheduler support.

👍
