### ISSUE TITLE
Race condition between setting node taints and scheduling

### ISSUE THREAD

**Issue by krzysztof-jastrzebski** [kubernetes/kubernetes#72129]
**What happened**:
Pod was scheduled on newly created node with condition Ready equal to false.
**What you expected to happen**:
Pod shouldn't be scheduled until Ready condition is true.
**How to reproduce it (as minimally and precisely as possible)**:
Run cluster with Cluster Autoscaler enabled. Add pod which needs to scale up cluster.
Watch nodes and pods objects when new node is added. 
**Anything else we need to know?**:
Scheduler is not using conditions anymore but it uses taints instead (like node.kubernetes.io/not-ready) which are not added when Kubelet registers node for the  first time:
https://github.com/kubernetes/kubernetes/blob/2b96a6074243cf39293fc294b20d3b8c97d3daca/pkg/kubelet/kubelet_node_status.go#L211
After some time taints are added but pod can be already scheduled. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.3-gke.1
- Cloud provider or hardware configuration: GKE

/kind bug

**Comment by yujuhong** [comment]
/sig node
/sig scheduling
@bsalamat @k82cn

**Comment by aermakov-zalando** [comment]
We've just tried to enable `TaintNodesByCondition`/`ScheduleDaemonSetPods` in our clusters (AWS, our own tooling to manage them) and it's not the only issue:
 * Even if the race condition is fixed, most Kubernetes configurations including GKE inject a `NoExecute` toleration for `.../node-ready` and `.../node-unreachable` with a 5 minute window to reduce the number of disruptions. Unfortunately, this also means that scheduler is free to schedule newly created pods on nodes that are not yet ready or have gone down a few minutes ago, which is pretty stupid.
 * The autoscaler itself doesn't treat these conditions in a special way, from what I understand by looking at the source code. This means that if the tolerations are not there, it'll spin up a new node, determine that the pods can't run on it because of taints and happily create a new node instead of waiting for the node to be ready.

**Comment by losipiuk** [comment]
Thanks for reporting that @aermakov-zalando. I created https://github.com/kubernetes/autoscaler/issues/1515 to track work needed in CA.

**Comment by k82cn** [comment]
> Scheduler is not using conditions anymore but it uses taints instead (like node.kubernetes.io/not-ready) which are not added when Kubelet registers node for the first time

Yes, for now, node controller taints nodes based on nodes' condition, there's a race condition between kubelet, node controller and scheduler. We need to let kubelet map condition to taints when startup; and for restart case, we need to also give a white list for node restriction admission.

> Unfortunately, this also means that scheduler is free to schedule newly created pods on nodes that are not yet ready or have gone down a few minutes ago, which is pretty stupid.

`NoExecute` does not mean `NoSchedule`; if only tolerate `NoExecute`, it still can not be scheduled. `NoExecute` with time window simulates termination gracefully.

**Comment by yujuhong** [comment]
@k82cn the feature is already beta and enabled by default, but kubelet does not apply appropriate taint to prevent the race conditions...

Another thing is that this still does not handle version skews with older kubelets.

**Comment by bsalamat** [comment]
I agree with @yujuhong. I feel we should disable the feature given the severity of the race condition and re-enable it later when the issue is addressed.

**Comment by aermakov-zalando** [comment]
@k82cn 

> `NoExecute` does not mean `NoSchedule`; if only tolerate `NoExecute`, it still can not be scheduled. `NoExecute` with time window simulates termination gracefully.

That might've been the intention, but that's not what we observed in practice (at least on 1.11.5, maybe it's fixed in 1.12). Even after the node was properly tainted, the scheduler kept scheduling stuff there. I've just tried doing the same thing and I can clearly see the pod getting scheduled:

```
$ kubectl describe node ip-10-149-65-133.eu-central-1.compute.internal | grep Taints
Taints:             foo=bar:NoExecute
```

```
$ kubectl get deploy nginx-test-abc -o yaml
…
spec:  …
  template: …
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-149-65-133.eu-central-1.compute.internal
      tolerations:
      - effect: NoExecute
        key: foo
        operator: Exists
        tolerationSeconds: 300

```

```
$ kubectl delete pod -l run=nginx-test-abc
pod "nginx-test-abc-6df8bfc7f4-bmrq5" deleted
```

```
$ kubectl get pod -l run=nginx-test-abc -o wide
NAME                              READY     STATUS    RESTARTS   AGE       IP          NODE
nginx-test-abc-6df8bfc7f4-rb4mj   1/1       Running   0          27s       10.2.2.11   ip-10-149-65-133.eu-central-1.compute.internal
```

**Comment by k82cn** [comment]
Also agree to disable this feature by default, let's re-enable it when race condition and version skews are handled :)

**Comment by krzysztof-jastrzebski** [comment]
@k82cn
Is it working as @aermakov-zalando  described in previous comment?

**Comment by k82cn** [comment]
> Taints:             foo=bar:NoExecute

It should be `foo=bar:NoSchedule` if you don-t want to schedule pod.

**Comment by aermakov-zalando** [comment]
Yes, but `not-ready` is a `NoExecute` taint. Doesn't `NoExecute` imply `NoSchedule` as well?

**Comment by Huang-Wei** [comment]
@aermakov-zalando they're different. `NoExecute` impacts existing pods on the tainted node:

- if existing pod doesn't corresponding toleration, it will be applied with a toleration with 300 tolerationsSeconds (by admission controller) , and gets evicted afterwards
- if existing pod does have corresponding toleration, admission controller will bypass, and the existing pod will behave based on its own toleration - either evicted after `tolerationSeconds`, or, being kept as is (no `tolerationSeconds` was set)

**Comment by aermakov-zalando** [comment]
@Huang-Wei Yes, I understand that `NoExecute` also evicts. Would you mind explaining how it *should* work with regards to the scheduler? Is the scheduler allowed to schedule a pod on a node that has a `NoExecute` taint (I assume not)? Is it allowed to schedule a pod on a node if it has a `NoExecute` toleration?

**Comment by k82cn** [comment]
> Doesn't NoExecute imply NoSchedule as well?

No

> but …/not-ready is a NoExecute taint.

We also taint node with `NoSchedule` when it's not ready by https://github.com/kubernetes/kubernetes/pull/63471 and https://github.com/kubernetes/kubernetes/pull/67734

**Comment by Huang-Wei** [comment]
> Is the scheduler allowed to schedule a pod on a node that has a NoExecute taint (I assume not)?

No, unless the pod has the mapped NoExecute toleration.

> Is it allowed to do it if the pod has a NoExecute toleration for the taint?

Yes.

> new nodes are tainted with …/not-ready:NoExecute, which should evict existing pods and forbid scheduling new ones (I'm assuming NoExecute implies NoSchedule, because otherwise the pod could be immediately rescheduled back),

`NoExecute` controls eviction behaviors, while `NoSchedule` controls scheduling behaviors. I would't say "NoExecute implies NoSchedule" b/c whether a pod can be scheduled onto tainted node is judged by a simple rule: whether the incoming pod tolerates all taints on target node.

For example, if target node has "foo=bar:NoExecute" taint, and an incoming pod has toleration defined as "{effect: NoExecute, key:foo: operator:Exists}", then the incoming pod can be scheduled.
But if target node has 2 taints: e.g. "foo=bar:NoExecute" and "foo=bar:NoSchedule", and incoming pod has only one toleration "{effect: NoExecute, key:foo: operator:Exists}", then it will fail to be scheduled.

**Comment by Huang-Wei** [comment]
@aermakov-zalando A taint is a 3-tuple {key,value,effect}, we can't make (implicit) assumption that two taints with the same key has implicit semantics like NoExecute implies NoSchedule or whatever.

BTW: you can use one general toleration to tolerate two taints without specifying the effect:

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: pause
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
  tolerations:
  - key: foo
    operator: Exists
```

**Comment by szuecs** [comment]
@Huang-Wei our use case is mainly on node bootstrap and we want to be sure that NoExecute and NoSchedule is active from the startup, otherwise you create race conditions that can lead to production outages. What do you recommend to achieve this?

**Comment by Huang-Wei** [comment]
@szuecs yeap, that's exactly the issue needs to be solved, and is the theme of this issue - my explanation above was to keep irrelevant symptoms apart from the racing issue.

**Comment by szuecs** [comment]
@Huang-Wei is this scheduled for the next minor release or is it a bigger thing that need to be in the quarterly update schedule?
For us it has a big impact.

**Comment by Huang-Wei** [comment]
@szuecs we'll try to fix it asap, but we can't give an ETA due to this holiday.

> is this scheduled for the next minor release

Yes, when it's ready in `master` branch, we will also get it back ported to each releases, so that it will be available in next minor version.

**Comment by Huang-Wei** [comment]
@k82cn @bsalamat @yujuhong raised a PR #72315 to hold off adding NotReady node to scheduler cache, PTAL.

**Comment by szuecs** [comment]
@k82cn  I guess this is fine as flags to the apiserver and controller manager and scheduler:
         - --feature-gates=TaintBasedEvictions=true,TaintNodesByCondition=false,ScheduleDaemonSetPods=false

**Comment by aermakov-zalando** [comment]
@Huang-Wei Yes, I understand how it's currently implemented. I was just trying to argue that although it's simple from the implementation perspective, actually using taints & tolerations correctly is a lot harder than necessary with some gotchas. Even built-in Kubernetes commands don't actually work correctly. However, this is probably out of scope of the issue and unlikely to be changed due to BC reasons.

**Comment by resouer** [comment]
Let's move the discussion from https://github.com/kubernetes/kubernetes/pull/72315#issuecomment-451032040 to here.

The approach I'm proposing is: we can have an Admission to taint nodes when they are created, and then use Node Controller to un-taint nodes based on condition update.

Open for discussion to see if there're edge cases and will draft a design to follow up here.

**Comment by k82cn** [comment]
> we can have an Admission to taint nodes when they are created, 

How to handle k8s upgrade? The new version of kubelet will update instead of create Node.

Another option is introduce something similar to taint in `Node.Status` refer to (https://github.com/kubernetes/kubernetes/pull/72315#issuecomment-451035556 ). For now, taint is in `node.spec`.

**Comment by answer1991** [comment]
@krzysztof-jastrzebski 

The simplest way to solve your problem is starting kubelet with options --register-with-taints=node.kubernetes.io/not-ready:=NoSchedule. 

we can consider to add default value node.kubernetes.io/not-ready:=NoSchedule to option *--register-with-taints*.

**Comment by bsalamat** [comment]
Today I was informed of another issue with scheduling CNI daemons when TaintNodesByCondition is disabled. This is general problem with scheduling daemon pods on nodes which are not fully operational yet.
DaemonSet pods have blanket toleration for various node condition taints to ensure that daemons are scheduled on nodes even when the nodes are not fully operational. Disabling TaintNodesByCondition, enables node condition check in the scheduler. The node condition checker does not process tolerations and when a node is not ready, network is unavailable, etc. the scheduler won't schedule pods on the node.
So, disabling TaintNodesByCondition does not seem to be a good option. Instead, we must find a way to fix the issue ASAP.

The solution proposed by @answer1991 sounds good, but it requires kubelet upgrade/restart. I don't know if there is any better way at this point. We should all work together closely to address this issue quickly.

**Comment by bsalamat** [comment]
We had a meeting at Google to brainstorm possible solutions. @liggitt suggested adding the logic to the API server admission to taint new nodes with "not ready" when TaintNodesByCondition is enabled. This seems to be the best solution that covers both new clusters and existing clusters upgraded to 1.12+. This solution works with version skew and older kubelets.

**Comment by yastij** [comment]
Just to make sure, we’re building this as a mutating webhook right ?

**Comment by krmayankk** [comment]
This seems related https://github.com/kubernetes/kubernetes/issues/67057
