### ISSUE TITLE
Set percentage of nodes scored in each cycle dynamically based on the cluster size

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#72125]
**What would you like to be added**:
Kubernetes scheduler has [a config option](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/types.go#L83) that specifies what percentage of the cluster nodes should be scored in each scheduling cycle. The scheduler stops scanning more nodes once that many nodes are found feasible for running the pod under consideration.
The default value of this config option is 50 (for 50%). We should let the scheduler determine this value based on the size of the cluster when this config option is not provided.
I'd propose this formula for finding the percentage: `50 - cluster size / 125`. This is a linear formula that gives us 50 when the cluster size is 100 nodes and 10 for a 5000 node cluster.
The scheduler already has a lower bound of 50 nodes per scheduling cycle. As a part of this change, we should also add a 5% lower bound for the formula (If the result of the formula is below 5, we should return 5).

**Why is this needed**:
To improve scheduler performance in large clusters. 

/kind feature
/sig scheduling

**Comment by wgliang** [comment]
@xiaoxubeii  Thanks
