### ISSUE TITLE
HPA controller hang while getting metrics

### ISSUE THREAD

**Issue by jmcmeek** [kubernetes/kubernetes#72130]
**What happened**: HPA stopped updating deployments.  controller-manager log entries from horizontal.go simply stop.  A goroutine dump shows HPA controller hung for 5655 minutes in GetResourceMetrics (will attach stack in comment).  After killing controller-manager, HPA processing resumed.

**What you expected to happen**:  HPA controller should not hang and should resume processing when it can get metrics properly.

**How to reproduce it (as minimally and precisely as possible)**:  None.

**Anything else we need to know?**: I didn't see any obvious sign of problems in heapster.  Maybe there was some networking issue. But the HPA controller shouldn't hang. I took a quick look at the code in the stack - trying to guess if this might have been fixed since 1.10 or work differently with metrics-server. There was nothing obvious to me.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.11
- Cloud provider or hardware configuration: IBM Cloud Kubernetes Service 
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): 4.4.0-89-generic
- Install tools:
- Others:

/kind bug

**Comment by jmcmeek** [comment]
The goroutine dump showed this call stack:
```
goroutine 33173 [select, 5655 minutes]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).RoundTrip(0xc420b70820, 0xc465a73400, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:879 +0x85f
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc422c26280, 0xc465a73400, 0xc4420f3b00, 0xc48fb4b740, 0x70000000040cb00, 0xffffffffffffffff)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:351 +0x159
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).RoundTrip(0xc422c26280, 0xc465a73400, 0x77c201, 0xc4420f3b98, 0xc48fb4b970)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:313 +0x3a
k8s.io/kubernetes/vendor/golang.org/x/net/http2.noDialH2RoundTripper.RoundTrip(0xc422c26280, 0xc465a73400, 0xc45ac28300, 0x5, 0xc4223f03e8)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/configure_transport.go:75 +0x39
net/http.(*Transport).RoundTrip(0xc420010780, 0xc465a73400, 0xd, 0xc424af2f00, 0x4f8)
	/usr/local/go/src/net/http/transport.go:371 +0xd47
k8s.io/kubernetes/vendor/k8s.io/client-go/transport.(*bearerAuthRoundTripper).RoundTrip(0xc42155ea20, 0xc465a73400, 0xa, 0xc424ea8100, 0x73)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/round_trippers.go:285 +0x186
k8s.io/kubernetes/vendor/k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc42155ea40, 0xc465a73200, 0xc42155ea40, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/round_trippers.go:163 +0x10c
net/http.send(0xc465a73100, 0xb3b6520, 0xc42155ea40, 0x0, 0x0, 0x0, 0xc45c8bc570, 0xc4420f3760, 0xc48fb4bc18, 0x1)
	/usr/local/go/src/net/http/client.go:249 +0x1a9
net/http.(*Client).send(0xc424d73bc0, 0xc465a73100, 0x0, 0x0, 0x0, 0xc45c8bc570, 0x0, 0x1, 0x5c)
	/usr/local/go/src/net/http/client.go:173 +0xfd
net/http.(*Client).Do(0xc424d73bc0, 0xc465a73100, 0x0, 0xfb, 0x0)
	/usr/local/go/src/net/http/client.go:602 +0x28d
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request(0xc439763980, 0xc48fb4bf08, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:664 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).DoRaw(0xc439763980, 0x4e10537, 0x4, 0x4e17e5a, 0x8, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:750 +0x95
k8s.io/kubernetes/pkg/controller/podautoscaler/metrics.(*HeapsterMetricsClient).GetResourceMetric(0xc424f4a870, 0x4e0f6f9, 0x3, 0xc4797d90d0, 0xd, 0xb3feac0, 0xc448edef00, 0x5c, 0x5c, 0xc48fb4c520, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/metrics/legacy_metrics_client.go:70 +0x276
k8s.io/kubernetes/pkg/controller/podautoscaler.(*ReplicaCalculator).GetResourceReplicas(0xc4257a22d0, 0x1400000002, 0x4e0f6f9, 0x3, 0xc4797d90d0, 0xd, 0xb3feac0, 0xc448edef00, 0x4e16573, 0x7, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/replica_calculator.go:57 +0xf6
k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).computeReplicasForMetrics(0xc4250d9280, 0xc4662636c0, 0xc45755e3c0, 0xc443a77230, 0x1, 0x1, 0x11, 0x4f3472d, 0x3d, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:286 +0x166b
k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).reconcileAutoscaler(0xc4250d9280, 0xc46abe3380, 0x0, 0xc46abe3380)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:445 +0x179c
k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).reconcileKey(0xc4250d9280, 0xc443f5ebc0, 0x37, 0x41a27a0, 0xc46464da40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:371 +0x1bd
k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).processNextWorkItem(0xc4250d9280, 0xc4221e0200)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:182 +0xd2
k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).worker(0xc4250d9280)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:170 +0x2b
k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).(k8s.io/kubernetes/pkg/controller/podautoscaler.worker)-fm()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:136 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4252b0fa0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4252b0fa0, 0x3b9aca00, 0x0, 0xc425159f01, 0xc420cc83c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4252b0fa0, 0x3b9aca00, 0xc420cc83c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/pkg/controller/podautoscaler.(*HorizontalController).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go:136 +0x1dc
```

**Comment by jmcmeek** [comment]
@kubernetes-autoscaling-bugs

**Comment by Shnatsel** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by bskiba** [comment]
Hi there, starting from 1.11 fetching metrics for HPA for Heapster is deprecated in favour of the Metrics API (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis), one of the reasons for that being that the metrics were fetched in this not-very-Kubernetes way.  This is the default behaviour starting from 1.9. What is the reason for using the legacy client in your set up?

As a side note, I think we are not doing patches to 1.10 any more, so there is low probability of the legacy client getting fixed.

**Comment by jmcmeek** [comment]
We've been using heapster as the sole metrics provider because the Kubernetes dashboard does not yet support metrics-server (https://github.com/kubernetes/dashboard/issues/2986).

I recognize that a 1.10 patch is doubtful, but a look at code (that I am not familiar with) suggested this problem could exist in later releases and also with metrics-server.  I've seen the problem a handful of times; this was the first time we had more useful debug info than "hpa stopped working".

**Comment by bskiba** [comment]
> We've been using heapster as the sole metrics provider because the Kubernetes dashboard does not yet support metrics-server (kubernetes/dashboard#2986).
Understandable, I hope dashboard is migrated soon.

I must say I haven't seen this happening with metrics server (but to be fair, haven't seen this with Heapster either). I guess it will be hard to fix without being able to reproduce.

**Comment by jmcmeek** [comment]
From the heapster side...  I don't know why it hung.  In one instance we could see that heapster has been restarted near the time of the hang. Perhaps there was a window where heapster socket was open, but not yet able to process requests, but regardless there appear to be ways in which this call can hang.  I thought this might be a matter of making sure the client performing the DoRaw() call near https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/legacy_metrics_client.go#L71 (and had appropriate timeouts to ensure that DoRaw() would eventually fail.

And a nit - I believe use of heapster for HPA is deprecated in 1.12, not 1.11.  But it is on the way out.

From metrics-server side...  I don't know if there is an issue.  Most of our customers are using heapster.  That will change over time, but as of now, the only times I hahttps://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/rest_metrics_client.go#L66ve seen this have been with heapster.  metrics server does have to get similar metrics - https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/rest_metrics_client.go#L66 and near line 113.  I imagine that a call to metrics-server could hang in the same way, but I gather this call goes through the apiserver rather than directly to metrics-server so the behavior could be different.
