### ISSUE TITLE
RuntimeClass unrecognized in v1.13.0

### ISSUE THREAD

**Issue by guptaNswati** [kubernetes/kubernetes#72132]
Trying to use RuntimeClass feature in v1.13.0 but I am getting `unrecognized feature-gate key: RuntimeClass`

What I did:
`kubeadm init --feature-gates=RuntimeClass=true`

Also when I do 
`kubeadm init --help` it doesn’t show feature-gates options. Is that expected?

**Environment**:
- Kubernetes version: v1.13.0
- Docker Version: 18.09.0
- OS: Ubuntu 18.04
- Kernel: 4.15.0-42-generic

/kind bug

**Comment by dims** [comment]
@guptaNswati kubeadm's `feature-gates` are not the same as those from the control plane binaries. you should probably do the kubeadm install first and then tweak the cluster using tips in https://kubernetes.io/docs/concepts/containers/runtime-class/

/close
