### ISSUE TITLE
Flexvolume volume resizing doesn't work

### ISSUE THREAD

**Issue by sun7927** [kubernetes/kubernetes#72131]
/sig storage

**what happened**
Setup a one-node Kubernetes 1.13 cluster and installed with a plugin with volume provisioner and flexvolume for an external block storage. It worked correctly and successfully to create a PVC and a Pod using it. However, it went in a problem when expanding the PVC, that the flexvolume plugin didn't get ```expandfs``` call.

**what is expected to happen**
When expand a PVC, the status goes into ```FileSystemResizePending```. And then, re-create (delete and then create again) the POD which is using the PVC, the flexvolume should get the ```expandfs``` call.

Environment:
**Kubernetes Cluster**
One node cluster, installed 1.13 version by kubeadm;

**flexvolume plugin**
1. storageclass
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  creationTimestamp: 2018-12-04T22:54:36Z
  labels:
    kubernetes.io/cluster-service: "true"
  name: mystorage
  resourceVersion: "2659"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/mystorage
  uid: 9296d77b-f817-11e8-9140-aa00c780d2c6
parameters:
  backend: block
provisioner: mystorage-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
2. flexvolume plugin
Implemented the following APIs for volume resizing:
```
expandvolume
expandfs
```
In addition, the flexvolume is installed on the host, and working correctly for volume mount/unmount/attach/detach.

**The PVC/Pod info**
``` PVC:
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # Referenced in pod.yaml for the volume spec
  name: mypvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mystorage
```
```Pod:
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
  - name: my-vol
    persistentVolumeClaim:
        claimName: mypvc-claim
  containers:
  - name: nginx
    image: nginx
    # Configure a mount for the volume We define above
    volumeMounts:
    - name: my-vol
      mountPath: /data
    ports:
    - containerPort: 80
```

After creating PVC and Pod successfully, resized the volume like:
```kubectl edit pvc mypvc-claim```, changed the ```resources.requests.storage``` from ```5G``` to ```8G```
And then, the PVC status is changed
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ab17a17f-0240-11e9-9c96-0a580af40023","leaseDurationSeconds":15,"acquireTime":"2018-12-17T21:18:15Z","renewTime":"2018-12-17T21:18:46Z","leaderTransitions":0}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mypvc-claim","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"pure"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: mystorage-provisioner
  creationTimestamp: 2018-12-17T21:18:15Z
  finalizers:
  - kubernetes.io/pvc-protection
  name: mypvc-claim
  namespace: default
  resourceVersion: "1364972"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/mypvc-claim
  uid: 449d925b-0241-11e9-86ba-aa00c780d2c6
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 8Gi
  storageClassName: mystorage
  volumeMode: Filesystem
  volumeName: pvc-449d925b-0241-11e9-86ba-aa00c780d2c6
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-12-17T22:06:37Z
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
  phase: Bound
```
And also, found a log from kube-controller-manager as below:
```
Dec 17 22:08:36 k8s-test-87bffe1e03-0 sha256:d82530ead066dbed965b7705b8989ffc41705b59a5592b68046da2bbf2f6cabe/k8s_kube-controller-manager_kube-controller-manager-k8s-test-87bffe1e03-0_kube-system_3e2cdea54768295fafbc91dab55ef6a1_3/1246867818db[24919]: W1217 22:08:36.795359       1 plugins.go:842] FindExpandablePluginBySpec(pvc-449d925b-0241-11e9-86ba-aa00c780d2c6) -> returning noopExpandableVolumePluginInstance
```

And then, deleted the pod which also called flexvolume plugin to unmount/detach the PVC/volume successfully. And later, created another pod which called flexvolume plugin to attach/mount the PVC successfully.
However, it didn't send out expandfs call the flexvolume plugin for resizing filesystem.

/kind bug

**Comment by gnufied** [comment]
@mlmhl it appears that the online resizing code depends on plugin being attachable. I don't see this specififed in spec - https://github.com/kubernetes/community/blob/6bf5bf4481c485216bf06f511b87609a1974b2b1/contributors/design-proposals/storage/online-grow-volume-size.md

Error:

```
Dec 17 23:10:23 k8s-test-87bffe1e03-0 kubelet[23379]: E1217 23:10:23.626593   23379 reconciler.go:268] operationExecutor.ExpandVolumeFSWithoutUnmounting failed for volume "pvc-449d925b-0241-11e9-86ba-aa00c780d2c6" (UniqueName: "flexvolume-pure/flex/6447b523-0242-11e9-86ba-aa00c780d2c6-pvc-449d925b-0241-11e9-86ba-aa00c780d2c6") pod "nginx" (UID: "6447b523-0242-11e9-86ba-aa00c780d2c6") : VolumeFSResize.FindAttachablePluginBySpec failed for volume "pvc-449d925b-0241-11e9-86ba-aa00c780d2c6" (UniqueName: "flexvolume-pure/flex/6447b523-0242-11e9-86ba-aa00c780d2c6-pvc-449d925b-0241-11e9-86ba-aa00c780d2c6") pod "nginx" (UID: "6447b523-0242-11e9-86ba-aa00c780d2c6") : AttachableVolumePlugin is nil
```

**Comment by gnufied** [comment]
Second problem is - Flexvolume resizing implementation interacts badly with plugins that don't implement attach/detach. Volume resizing expects a plugin to have `DeviceMounter` interace but in case of flex this is not well defined and hence code ends up using `AttachDetach` interace which is not implemented and hence looks like `expandfs` call is not being made.

**Comment by mlmhl** [comment]
In the previous version we depend on plugin being attachable because we need to get the device mount path through `Attacher.GetDeviceMountPath` method.

After we refactoring the volume plugin interfaces, `GetDeviceMountPath` is extracted into an independent `DeviceMountableVolumePlugin` interface. Of cause we can change to use `DeviceMountableVolumePlugin`, but it seems still not work for flexvolume as it may not implement `DeviceMountableVolumePlugin`.

What's more, current flexvolume resize process needs to know both device path and device mount path, can we get these information from an un-device-mountble flexvolume?

**Comment by sun7927** [comment]
does it make sense to query pod for the device mountpath instead of making a call to the plugin?

**Comment by sun7927** [comment]
@gnufied is there any timeline to fix this issue, and how to fix?

**Comment by gnufied** [comment]
I am looking into fixing this for 1.14. 

/assign

**Comment by gnufied** [comment]
I think we can't rely on devicePath being present always anyways. The CSI specs too require just the deviceMountPath not devicePath. I am considering refactoring the code so as resizing can work without depending on attach interface.

**Comment by gnufied** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/74863 which fixes this. If deviceMountPath is not available the resizing will fall back to `volumeMounter.GetPath()` which should be implemented by all plugins.

**Comment by gnufied** [comment]
closing this. It should be fixed in latest release.
