### ISSUE TITLE
Error: deployments/scale.extensions <name-of-extension> not found

### ISSUE THREAD

**Issue by srsrin** [kubernetes/kubernetes#72134]
sig/autoscaling

**What happened**:
We are attempting to use horizontal pod autoscaling in our cluster. The cluster autoscaler yaml is already deployed to our cluster but not through helm. However the HorizontalPodAutoscaler yamls are in our charts folder and are deployed through helm. But we are getting the error: "deployments/scale.extensions <name-of-extension> not found when pushing the release into the cluster. 

**What you expected to happen**:
The HPA yamls reference the deployments that are expected to occur in the cluster but each deployment cant find the extension itself. 
**How to reproduce it (as minimally and precisely as possible)**:
Have a cluster. Deploy the hpa yamls using helm but deploy the cluster autoscaler using the command '''kubectl create -f <modified-cluster-autoscaler.yaml>'''
**Anything else we need to know?**:
I'm also using the azure-k8s-adapter to keep track of external metrics and wonder if that is messing up the hpa stuff. 
**Environment**:
- Kubernetes version (use `kubectl version`): 1.8+
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
Can this be reproduced on 1.10 or above?

**Comment by liggitt** [comment]
Also, do you have the HPA object definition?

**Comment by srsrin** [comment]
i just checked, my version of kubernetes is 1.10
`{{- $root := . }}
{{- range .Values.hpa}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .targetRefName }}
  minReplicas: 1
  maxReplicas: {{ .maxReplicas }}
  metrics: 
    - type: External
      external:
        metricName: {{ .metricName }}
        targetValue: 1
---
{{- end }}`

**Comment by liggitt** [comment]
and does the targetRefName deployment exist?

**Comment by srsrin** [comment]
yes there are three deployments and they should all link to the autoscaler. Instead, the autoscaler doesn't connect to those three deployments so deployments get pushed to the cluster. For context, i have a deployment.yaml that generates the three deployments along with the hpa.yaml

**Comment by liggitt** [comment]
can you provide a representative HPA and Deployment object as retrieved from the apiserver with `kubectl get hpa ... -o yaml` and `kubectl get deployment ... -o yaml`, and the exact text of the error you are seeing?

**Comment by oceaneLonneux** [comment]
@srsrin  What was the solution for your problem?
