### ISSUE TITLE
Convert existing PVs to use volume topology

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#72139]
**What would you like to be added**:
Existing PVs using zone/region labels should be updated to use PV.NodeAffinity. 

**Why is this needed**:
 Then we can deprecate and eventually remove the VolumeZone scheduling predicate.

/kind feature

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by msau42** [comment]
@kubernetes/sig-api-machinery-misc is anyone aware of past precedent of backfilling new fields for existing API objects?

**Comment by msau42** [comment]
Would this be something that API defaulting can handle?  It's a little strange because the conversion logic would trigger off of certain hardcoded labels.

**Comment by liggitt** [comment]
> @kubernetes/sig-api-machinery-misc is anyone aware of past precedent of backfilling new fields for existing API objects?

the precedents I'm aware of didn't end well. defaulting fields based on other fields interacts poorly with updates (see selector defaulting in extensions/v1beta1 workload objects - https://github.com/kubernetes/kubernetes/issues/34292)

**Comment by andrewsykim** [comment]
/assign 

Working on this as part of https://github.com/kubernetes/enhancements/issues/837.

**Comment by msau42** [comment]
I think this can be addressed through CSI migration.  It can translate existing zone labels on PVs to PV.NodeAffinity.  

We can deprecate the VolumeZone predicate once we send out the migration deprecation notice for all cloud plugins, and then remove it entirely once migration is GA and cannot be disabled.

/assign @davidz627 @ddebroy @leakingtapan

**Comment by msau42** [comment]
This also implies the volumebinding predicate needs to call the translation library

**Comment by ddebroy** [comment]
@msau42 I was wondering if it make sense to perform the Zone Labels => NodeAffinity translations in `volumeutil` as part of the call to `volumeutil.CheckNodeAffinity` (which gets invoked by the VolumeBinding predicate) and thus pave the path for deprecation/removal of the VolumeZone predicate. Performing the translation at the point it is needed may be safer from a cluster downgrade perspective.

I am not sure if CSI translation library is the ideal place for Zone Labels => NodeAffinity translation as CSI translation cares more about translating both to CSI topologies. In the CSI translation library, when translating a CSI PV to in-tree, we can make sure that we always populate NodeAffinity and never the labels.

**Comment by msau42** [comment]
What downgrade scenario are you thinking will break if we do the translation in the migration library?  The main reason why I think translation lib may be a good place is because the zone labels are a provider-specific thing (ie, GCE PD has special syntax to handle repd, Azure requires both region + zone labels), whereas `CheckNodeAffinity` is provider-agnostic and supposed to handle arbitrary labels. I think translating to CSI topologies is fine.

**Comment by davidz627** [comment]
I agree with @ddebroy that we probably shouldn't conflate this effort with CSI Migration. There may be the possibility for some code reuse or some common helper functions but I don't think this should take resources or be tracked under the CSI Migration effort. Right now the translation library does not handle the PV labels individually, you get the full PV translated (including PV labels if the specific plugin requires translation of them) and I would caution against exporting a PV label translating function inside the "CSI Translation Library".

**Comment by ddebroy** [comment]
@msau42 I was thinking of the effect of downgrades from the perspective of persisting actual changes to the PV API objects but thinking more, it should not be an issue since no one is going to downgrade down to an old enough version of k8s when the predicates to consider NodeAffinity was not enabled by default. So please ignore that concern about downgrade.

**Comment by ddebroy** [comment]
I was thinking of `CheckNodeAffinity` calling a generic `TranslatePVLabelsToNodeAffinity` which can follow a pattern similar to CSI translation: look at the PV source and dispatch to a registered translation function (from the appropriate provider) that declares supports for the given PV source.

**Comment by msau42** [comment]
I was not proposing adding a translate labels-only method.   Using the same existing translation methods, I want to take a given in-tree PV and translate it to a CSI PV.  And the CSI PV should have PV.NodeAffinity filled in with the appropriate CSI topology labels.  This all happens in-memory in the scheduler predicate. Nothing gets persisted to the API object.

**Comment by ddebroy** [comment]
Clarified on slack and now it does make sense. 

1. `TranslateCSIPVToInTree` should set `NodeAffinity` always (not directly related to this but helps with the general direction)
2. `TranslateInTreePVToCSI` will set `NodeAffinity` with topology upon detecting zone labels on the PV (mainly for pre-provisioned scenarios).

With the above two in place, scheduling predicates should be able to use the above to pave a path to deprecate label oriented predicates.

**Comment by davidz627** [comment]
Discussed with @ddebroy, we should add tests that guarantee this behavior

**Comment by msau42** [comment]
Also one more question to figure out: What happens when a new in-tree PV is dynamically provisioned? Does use in-tree topology labels/NodeAffinity, or the csi ones?

**Comment by davidz627** [comment]
I believe it will use the CSI ones, @ddebroy to confirm.
Is that ok?

**Comment by msau42** [comment]
Yes, if it uses CSI labels in PV.NodeAffinity, then there will be nothing that needs translation (although we should also test and make sure translation works if the labels/keys are already translated)
