### ISSUE TITLE
dig will stop and return empty when dnsmasq replied "REFUSED" with the dig tool builded in the e2e test

### ISSUE THREAD

**Issue by qmyuan2018** [kubernetes/kubernetes#72149]
**What happened**:
dig will be stoped and return empty when dnsmasq replied "REFUSED"
**What you expected to happen**:
dig success finially when handling replies from dnsmasq
**How to reproduce it (as minimally and precisely as possible)**:
1. start the kubernetes conformance test with the test case "should provide DNS for cluster  ".
2. login the dns test container k8s_jessie-querier_dns-test and use dig command.
**Anything else we need to know?**:
1. e2e test version: v1.12.1
2. dig version in the e2e test: DiG 9.9.5-9+deb8u15-Debian
   dig result:
   dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A
   

3. dig version installed manually on host: DiG 9.9.4-RedHat-9.9.4-61.el7_5.1
    dig result:
    dig  +tcp +noall +answer +search kubernetes.default.svc.cluster.local A
    kubernetes.default.svc.cluster.local. 5 IN A 10.254.0.1

**Environment**:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

/kind bug

**Comment by Shnatsel** [comment]
@kubernetes/sig-testing-bugs

**Comment by johnbelamaric** [comment]
I am not able to reproduce this in the latest 1.12 e2e tests. If you can consistently reproduce it please reopen.
