### ISSUE TITLE
kube-proxy cannot use ipvs mode on Linux 4.19

### ISSUE THREAD

**Issue by gouki777** [kubernetes/kubernetes#72146]
**What happened**:
Kubernetes v1.11.x v1.12.x do not used ipvs mode on linux 4.19
**What you expected to happen**:
Kubernetes v1.11.x v1.12.x used ipvs mode on linux 4.19
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/issues/70304
I know,ipvs mode on linux 4.19 fixed in kubernetes 1.13.0,but v1.11 and v1.12 donot  fixed.
v1.11 and v1.12 ,I want to know when to fixed it. thanks

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.x and v1.12.x
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Centos 7.5 x 64
- Kernel (e.g. `uname -a`):  4.19.6-1.el7.elrepo.x86_64
- Install tools:
- Others:

/kind bug

**Comment by Shnatsel** [comment]
The good news is that don't have to wait for someone else to do it - you can propose cherry-picking the fix yourself! 

Here's the process to do that:

1. Find original pull request that fixed the issue
1. Run the cherry-picking script with that PR's number: https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh - this will create pull requests cherry-picking the fix
1. Request a regular LGTM review (requesting it from whoever LGTM'd the original pull request usually works best)
1. Request a review from the patch release manager for the series you're interested in. You can look up the relevant contacts for 1.12 [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.12/release_team.md) and for 1.11 [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release_team.md).

That's it!

**Comment by m1093782566** [comment]
xref #75241, #75242

/close
