### ISSUE TITLE
Update docs to indicate that API values of []byte are always base64-encoded

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#72158]
**What would you like to be added**:
Extend the docs the clarify that various places there the API expects `[]byte` that this is base64 encoded

**Why is this needed**:
I was looking at the 1.13 API docs for the conversion webhook and it said

```
`caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used.
```

It's not obvious to me that this value should be base64 of the pem encoded contents

/kind feature

**Comment by dprotaso** [comment]
Going to label api-machinery as I think explicit annotation on certain fields is important

/sig api-machinery

**Comment by liggitt** [comment]
sweeping existing []byte fields and ensuring mention of base-64 encoding in json/yaml contexts would be good

**Comment by nzoueidi** [comment]
I would like to give it a chance and work on it!

**Comment by nzoueidi** [comment]
I would like to take it! As this my first issue I would like to get some help. Thanks

**Comment by liggitt** [comment]
it would involve:
* sweeping API types defined in types.go files
* locating fields of type []byte
* ensuring the field documentation includes a description that the json/yaml serialization is base64-encoded
* run `make update` to regenerate the relevant documentation and commit the results

**Comment by loqutus** [comment]
i'm in queue for taking it:)

**Comment by cosmin-ionita** [comment]
Any status on this issue? I'd also like to take it / work on it

**Comment by loqutus** [comment]
i updated comments to api types, but make update haven't changed docs. Probably they are in some other place, but i can't find it:)

**Comment by m-happy** [comment]
I'm a newbie and would love to contribute. Any help would be appreciated.

**Comment by vaibhavk** [comment]
Hi, if the issue is still unresolved and no one is working on it, I would like to work it

**Comment by entro-pi** [comment]
Is this issue still available?

I'm an Outreachy Applicant and would like to help with this! It'd give me a chance to get used to the setup/configuration of a PR here as well.

**Comment by nitishb** [comment]
Can I take this up?

**Comment by nitishb** [comment]
I am assigning this to myself. If there is a conflict, please update.
/assign @nitishb

**Comment by dprotaso** [comment]
another PR is still open
/remove-lifecycle rotten

**Comment by devarshigoswami** [comment]
If this issue hasn't been resolved, can I take it up??
