### ISSUE TITLE
Conformance Document does not properly pick up comment section.

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#72166]
**What happened**:
When the comment section associated with the conformance test is separated with more that four spaces/tabs etc then the comment is ignored.

**What you expected to happen**:
Comment associated with the conformance test should be used instead of ginkgo comments.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Received output (due to extra tabs)**

## [blackbox test when starting a container that exits should run with the expected status](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/common/runtime.go#L45)

**Expected output:**
## [Container Runtime, Restart Policy, Pod Phases](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/common/runtime.go#L45)

Release : v1.13
If the restart policy is set to ‘Always’, Pod MUST be restarted when terminated, If restart policy is ‘OnFailure’, Pod MUST be started only if it is terminated with non-zero exit code. If the restart policy is ‘Never’, Pod MUST never be restarted. All these three test cases MUST verify the restart counts accordingly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13

/kind bug

**Comment by Shnatsel** [comment]
/area conformance
/sig architecture

@brahmaroutu thanks for the report and the fix!
