### ISSUE TITLE
Enhancement: StatefulSet ConfigMapTemplate

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/kubernetes#72162]
**What would you like to be added**:

A feature to StatefulSet that would allow different configmaps to be mounted into each pod in the statefulset.    I imagine it would work similarly to volumeClaimTemplate, but instead of creating PVC's, it would just reference configmaps following the pattern.  For example, if the statefulset creates a pod named `foo-1`, there should be a way to tell that pod to mount config files from the configmap `config-for-foo-1`.

**Why is this needed**:

It's quite typical that a multi-pod stateful app would have slightly different configuration for each pod.   Other mechanisms for achieving this are inelegent.

Others would find a use for such a feature: https://stackoverflow.com/questions/48384602/how-to-add-a-configmap-to-a-specific-pod-in-a-statefulset

/kind feature

**Comment by Shnatsel** [comment]
@kubernetes/sig-storage-feature-requests
