### ISSUE TITLE
SSL cert for docs.k8s.io is invalid which leads to broken links in documentation

### ISSUE THREAD

**Issue by bfarayev** [kubernetes/kubernetes#72183]
**What happened**:
Documentation links in Changelog pages are broken because of expired or invalid SSL certs for *https://docs.k8s.io/*

**What you expected to happen**:
Link can be changed to *https://kubernetes.io/docs/* to avoid extra redirect and not depend on *.k8s.io certificates

**How to reproduce it (as minimally and precisely as possible)**:
Click on *Documentation* link in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#v1116

/kind bug

**Comment by mattjmcnaughton** [comment]
@kubernetes/sig-docs-maintainers is this something y'all have an interest in being done? If so, I'd be happy to do it, but just wanted to get a green light first.
