### ISSUE TITLE
Ability to update persistent volumes size in StatefulSet

### ISSUE THREAD

**Issue by tsmgeek** [kubernetes/kubernetes#72198]
Now that v1.11 support volume resizing I thought that this should be followed all the way up though to StatefulSets templates which unfortunately it does not seem to be.
This makes it quite harder than it needs to be to update a statefulset.

`The StatefulSet "elasticsearch-data" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.`

There is a feature request to allow adding/removing pvc from statefulset as well #65870

**Environment**:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

EKS - 1.11.5

/kind bug

**Comment by Shnatsel** [comment]
This seems to be a feature request. I'm going to label it as such, please correct me if I'm wrong.

/remove-kind bug
/kind feature
@kuberneres/sig-storage-feature-requests
@kuberneres/sig-cluster-lifecycle-feature-requests

**Comment by Shnatsel** [comment]
Reiterating mentions so that the bot hopefully picks them up

@kubernetes/sig-storage-feature-requests

@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by msau42** [comment]
cc @gnufied

**Comment by gnufied** [comment]
There is some discussion underway here - https://github.com/kubernetes/kubernetes/pull/71384 . But I think we are going to need a proper KEP.

**Comment by msau42** [comment]
Feature is being tracked through https://github.com/kubernetes/enhancements/issues/661
/close
