### ISSUE TITLE
kubectl rollout status should support multiple resources

### ISSUE THREAD

**Issue by pjo256** [kubernetes/kubernetes#72216]
**What happened**:
```
deployments/
     a.yml
     b.yml
```

`kubectl rollout status -R -f deployments` fails with `error: rollout status is only supported on individual resources and resource collections - 2 resources were found`.

**What you expected to happen**:

The [docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-status-em-) suggest that `-R` should work for multiple resources in a directory when running `rollout status`. 

`status` should've been applied to all resources under `deployments` following https://github.com/kubernetes/kubernetes/issues/20435. `status` was omitted in https://github.com/kubernetes/kubernetes/pull/25110 and I wasn't able to find a discussion regarding this omission in other issues.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl rollout status -R -f deployments`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.7
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by RMcD** [comment]
/reopen
/remove-lifecycle rotten

I agree with the assessment that this is a bug the `kubectl rollout history`, `kubectl rollout pause`, and `kubectl rollout resume` all work with spec files with multiple resources in them. `kubectl rollout status` does not. All of the commands would additionally benefit from only operating on supported resource types for rollout (Deployment, DaemonSet) from the spec file, but that's really a sperate enhancement.

Client kubectl 1.16.6
Server EKS 1.14.9

How Status Behaves:
`> kubectl rollout status -f .\ClusterService\core-dns.yaml -n kube-system
error: rollout status is only supported on individual resources and resource collections - 6 resources were found`

How Pause Behaves:
`> kubectl rollout pause -f .\ClusterService\core-dns.yaml -n kube-system
deployment.apps/coredns paused
error: serviceaccounts "coredns" pausing is not supported
error: clusterroles.rbac.authorization.k8s.io "system:coredns" pausing is not supported
error: clusterrolebindings.rbac.authorization.k8s.io "system:coredns" pausing is not supported
error: configmaps "coredns" pausing is not supported
error: services "kube-dns" pausing is not supported`

How Resume Behaves:
`> kubectl rollout resume -f .\dc-infra-k8s-infrastructure\ClusterService\core-dns.yaml -n kube-system
deployment.apps/coredns resumed
error: serviceaccounts "coredns" resuming is not supported
error: clusterroles.rbac.authorization.k8s.io "system:coredns" resuming is not supported
error: clusterrolebindings.rbac.authorization.k8s.io "system:coredns" resuming is not supported
error: configmaps "coredns" resuming is not supported
error: services "kube-dns" resuming is not supported`

How History Behaves:

```
> kubectl rollout history -f .\dc-infra-k8s-infrastructure\ClusterService\core-dns.yaml -n kube-system
deployment.apps/coredns
REVISION  CHANGE-CAUSE
1         <none>

error retrieving history for "ServiceAccount", no visitor method exists for { ServiceAccount}
error retrieving history for "ClusterRole.rbac.authorization.k8s.io", no visitor method exists for {rbac.authorization.k8s.io ClusterRole}
error retrieving history for "ClusterRoleBinding.rbac.authorization.k8s.io", no visitor method exists for {rbac.authorization.k8s.io ClusterRoleBinding}
error retrieving history for "ConfigMap", no visitor method exists for { ConfigMap}
error retrieving history for "Service", no visitor method exists for { Service}
```

**Comment by RMcD** [comment]
@pjo256 Could you reopen this?
If not I guess I'll file a new issue.

**Comment by docwhat** [comment]
What is needed to move this forward?

**Comment by docwhat** [comment]
/remove-lifecycle stale

poke poke

**Comment by CatalinMustata** [comment]
Any updates on this?
