### ISSUE TITLE
gce-cos-master-serial core dumping

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#72224]
**Which jobs are failing**: gce-cos-master-serial

**Which test(s) are failing**: the whole job is core dumping

**Since when has it been failing**:  Dec. 18th

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:

Core dump from ginko:

```
error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true (interrupted): signal: aborted (core dumped)
```

**Anything else we need to know**:

/kind failing-test
/sig testing
/sig release
/priority important-soon

attn:
@tpepper @BenTheElder @maria @spiffxp

**Comment by BenTheElder** [comment]
so the test-infra change that I would suspect if it was us merged here: https://github.com/kubernetes/test-infra/commit/74a6b442efb506394917e0629d9aae1b97114c15

**Comment by BenTheElder** [comment]
1:41 PM PST on the 18th for that

**Comment by jberkus** [comment]
Timing works ...

**Comment by BenTheElder** [comment]
Will look into this more tomorrow. This sort of thing should NOT have been a problem, but our tests tend to wind up coupled to the environment 😕

**Comment by BenTheElder** [comment]
this also went in during that time: https://github.com/kubernetes/kubernetes/compare/1d59ab05f...12be140dc, it seems suspicious that an image change would take us from "the job works and takes just over 6 hours" to "the job hangs somewhere near the end and terminates after 8+ hours"
cc @andrewsykim

**Comment by andrewsykim** [comment]
https://github.com/kubernetes/kubernetes/pull/70344 was a pretty big change so please let me know if there's anything I can do to help here. I couldn't find anything related to it digging into the logs but maybe I was looking at the wrong place.

**Comment by BenTheElder** [comment]
Thanks @andrewsykim, I'm in the same boat. Comparing the logs between the previous and very broken run I'm seeing the timeout + large panic at the end but not clear what the underlying issue is yet.

**Comment by andrewsykim** [comment]
I couldn't find the panic, can you copy/paste the panic trace here?

**Comment by BenTheElder** [comment]
It's really big, end of this log, just from the timeout I think. https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4473
