### ISSUE TITLE
Pod stuck on Terminating after node lost

### ISSUE THREAD

**Issue by dantingl** [kubernetes/kubernetes#72226]
**What happened**:
One pod is running on a worker node. After the node poweroff, the pod was stuck on 'Terminating' status. From pod metadata, its status is still 'Running'.

**What you expected to happen**:
The pod status should change to 'NodeLost'.

**How to reproduce it (as minimally and precisely as possible)**:
1. apply pod1 in node1
2. poweroff node1
3. after several minutes, pod1 gets stuck on 'Terminating'

**Anything else we need to know?**:
It works as expected in k8s 1.11. But in k8s 1.13 we had this issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
 cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
uname -a
Linux prme-hs2-nsbu2-dhcp-001-223 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by Huang-Wei** [comment]
> What you expected to happen:
The pod status should change to 'NodeLost'.

I checked in 1.11, `pod.phase` is `Running`, it's just `pod.reason` is `NodeLost`.

I suppose the "pod status" you mean is the `STATUS` column displayed in kubectl?

**Comment by dantingl** [comment]
> I suppose the "pod status" you mean is the `STATUS` column displayed in kubectl?

Yes, I mean the pod.reason should be NodeLost.
But in k8s1.13, the pod is still Running without NodeLost reason.

**Comment by Huang-Wei** [comment]
@dantingl it's b/c in 1.13 `TaintBasedEvictions` are enabled by default:

https://github.com/kubernetes/kubernetes/blob/456ffa0453563e0d2116d864f6b997abd3ccd27b/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L430-L439

I can get it fixed, but not sure it's worth doing that. As setting reason to "NodeLost" is an extra operation to APIserver - in addition to "deleting a pod".

So I'm wondering if it really concerns your business, or you're just curious.

cc/ @k82cn

**Comment by dantingl** [comment]
> I can get it fixed, but not sure it's worth doing that. As setting reason to "NodeLost" is an extra operation to APIserver - in addition to "deleting a pod".
> 
> So I'm wondering if it really concerns your business, or you're just curious.

It needs to be changed to "NodeLost", otherwise how could user know if the pod is going to be deleted. 'Terminating' is not in status from API.

**Comment by Huang-Wei** [comment]
If you want to check if a pod is being deleted, the most reliable way to check its `metadata.deletionTimestamp` - check whether it's non-nil.

**Comment by dantingl** [comment]
Do you mean metadata.deletionTimestamp and NodeLost are added in pod spec at the same time?
I want to find a time when pod is already got deleted. Based on my understanding even deletionTimestamp is marked, pod may be still running there.

**Comment by Huang-Wei** [comment]
> Based on my understanding even deletionTimestamp is marked, pod may be still running there.

deletionTimestamp means a pod is marked for deletion. But for the "node unreachable" case, API server can't get heartbeat from kubelet, so it's just "marked" for deletion, and when `tolerationSeconds` passed, a new pod will be created to replace the "zombie" pod. And the "zombie" pod info will only be cleaned up when kubelet is connected to APIserver after connectivity issue is resolved.

**Comment by Huang-Wei** [comment]
yes, it may be.

**Comment by dantingl** [comment]
Thanks for your explaination. I'm fine whether this will be addressed or not. Thanks!

**Comment by Huang-Wei** [comment]
My preference is to keep current logic as is - for a node which loses connection to API server, in 1.11 it needs 2*len(pods) calls to APIserver (set status.reason to NodeLost and then delete pods). And in 1.13 it just goes deleting the pods which causes less pressure to APIserver.

**Comment by xiaoxubeii** [comment]
I am curious how Kubernetes delete pods when taints offline nodes. I can not find relative codes.

**Comment by srinathkotu** [comment]
I am still facing this issues on v1.13.3. Is there anything else i need to configure to have  "TaintBasedEvictions" feature working properly?
Below are the tolerations and taints that i see on my node(powered off) and pod(stuck on terminating):

`kubectl get pod nginx-deployment-8abcf4969df-gik89 -o yaml | grep -A4 tolerations`
 
 ```tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
```

`kubectl get nodes ip-10-10-10-100.ec2.internal -o yaml | grep -A12 taints`

  ```taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2019-01-27T14:48:08Z"
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/shutdown
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2019-01-27T14:48:13Z"
```

**Comment by srinathkotu** [comment]
@Huang-Wei could you elaborate when you say 
>it just goes deleting the pods
do you mean that the pods should get deleted automatically after the tolerationseconds time is reached?

**Comment by Huang-Wei** [comment]
@srinathkotu Expected symptom on "lost node" is that the pod running on that node would be showing as "Terminating" after `terminationSeconds`, and then a replacement pod will be created, and scheduled onto other available nodes if possible.

> do you mean that the pods should get deleted automatically after the tolerationseconds time is reached?

Yes, but it only modifies the "deletionTimestamp" of that pod, and needs another kubelet's signal to delete the API metadata (stored in etcd) totally. Unfortunately in the "node lost" case, the network is lost, so the API object can't be deleted, so it still shows as "Terminating".

However, this "terminating" pod doesn't count as a valid replica of the workload. Say you have a 2-replica app prior to node lost, and then node lost after "terminationSeconds", you will see 2 pods running, and 1 pod terminating. Only when the lost node gets back, it will reconcile to remove the API info of the terminating pod.

**Comment by srinathkotu** [comment]
@Huang-Wei Thank you for making is very clear.

Now my next crazy question: Is there any way(like a cronjob that can be run?) to remove these 'zombie/hanging' pods?

**Comment by Huang-Wei** [comment]
Theoretically yes, using a crontab or sth alike. I know that "terminating" pods looks untidy...

On the other hand, a long-time "terminating" pod can be read as a signal indicating the cluster met some glitch. So prior to getting them cleaned up, maybe it's worth hopping in and examining what's going on.

**Comment by srinathkotu** [comment]
@Huang-Wei  So i am facing this scenario when the node running pods of a statefulset goes down, the pods go into a 'terminating' state **but** new pods don't get created on the remaining nodes. However when the node running pods of a deployment goes down, the pods go into a 'terminating' state **and** new pods get created for them just like you had mentioned in your previous comment.

The statefulset pods don't get recreated until they are `force deleted`. 

This to me seems like an issue in either the rescheduling of the pods.

**Comment by Huang-Wei** [comment]
@srinathkotu you mean after "terminationSeconds", new replacement pod is still **not** created (a new pod stays in pending status doesn't count as "not created")? If it's the case, it's _likely_ an issue in statefulset.

I'd suggest to open an issue including detailed cluster info, like k8s version, statefulset spec, etc. So that folks in sig-apps can give an authoritative answer on this. (label the issue with `/sig apps`)

**Comment by peterrosell** [comment]
> Only when the lost node gets back, it will reconcile to remove the API info of the terminating pod.

I guess this behavior will leave terminating pods forever if the node never gets back. When running preemptive VMs that come and go I can imagine that there can be a lot of terminating pods hanging around.

I also got the same problem as @srinathkotu with statefulset. added some info about that in #74689.

**Comment by sukhong** [comment]
We are facing the same issue on Kubernetes 1.15.3

**Comment by sukhong** [comment]
Does this issue share the same root cause with this issue: https://github.com/kubernetes/kubernetes/issues/80968?

**Comment by sukhong** [comment]
In fact, this issue is actually even worse, because there is no way to detect this zombie pods unless you manually run the command.

**Comment by sukhong** [comment]
The problem is that even after nodes become available again, "terminating" pods to not become "ready" again, but they stay terminating forever...

**Comment by vanyans** [comment]
I also ran into this issue today. Running Kuberentes 1.15.
The kube node that failed was hosting helm repository so I ended up with 2 pods:

kube-system   pod/helm-repository-7bdc8cbd77-jf5fq                      1/1     Terminating       
kube-system   pod/helm-repository-7bdc8cbd77-nxtc2                      1/1     Running   

Helm wasn't reachable until the Terminating pod was forcefully killed.

Seems there is more to this issue then just having pods in terminating state forever.

Can/will anything be done about this issue?

Thanks

**Comment by ubhide** [comment]
I also ran into this issue. Running kubernetes 1.15.4

**Comment by jmolmo** [comment]
I also ran this issue.

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
 Needed to manually force Pod termination.

**Comment by prabhu87** [comment]
Any solution for this?

Am running v1.15.3 cluster, after node lost the pods are stuck at terminating state.

Can we make a health check in the pod,before the controller change the node status to NOTReady state, the pods which are running in the lost node, should recreate in available nodes.

**Comment by prabhu87** [comment]
I too faced the same issue and found solution, its worked for me,

Am running v1.15.3 cluster, after node lost the pods are stuck at terminating state.

Added below taint to terminate the pod in 2s when the node state changed to NotReady/unreachable.

tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 2s
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 2s
change terminationGracePeriodSeconds to 0secs.

Above all are pod specs.

**Comment by ubhide** [comment]
Continued to experience this on a 1.16 cluster as well

**Comment by msshroff** [comment]
Facing same issue on 1.16.1 cluster 
/remove-lifecycle rotten

**Comment by yogeshdass** [comment]
Delete the node from the cluster and it will remove the pods that are in terminating state on that dead node

**Comment by yanchenko-igor** [comment]
https://github.com/kubernetes/kubernetes/pull/91907 this PR solves this issue.

**Comment by daicang** [comment]
We have encountered this in 1.17.0. After node lost, pods on that node stuck in "Terminating". Here statefulset and deployment have different behaviour:

statefulset: stuck pod would not be removed, and new pod would not be created to replace

deployment: stuck pod would not be removed, but a new pod is created by deployment controller on another node

As said in https://github.com/kubernetes/kubernetes/issues/72226#issuecomment-467974050, this is expected, since connection with kubelet is broken, pod can't be removed. 

btw, change `tolerationSeconds` or remove toleration don't work in our env, I guess this is because pods run into terminating *after* `tolerationSeconds`

**Comment by yanchenko-igor** [comment]
My fix was rejected as it changes the default kubernetes behavior, but I created a KEP, if anyone interested to fix this issue please review and discuss it https://github.com/kubernetes/enhancements/pull/1863

**Comment by JinlongWukong** [comment]
if these zombies pods have pod affinity terms,  the new creating pods will always be pending, how to solve this problem?

**Comment by nerzhul** [comment]
it seems we encounter the same issue on some of our staging issue which are in 1.19.7 :(

**Comment by javsalgar** [comment]
We got this incident with one of our chart users as well: https://github.com/bitnami/charts/issues/5867

**Comment by imriss** [comment]
@nerzhul and @javsalgar, It seems that it is more related to an AMI release than the k8s release. I had the same issue with an AMI version for k8s 1.19, and it was resolved after I upgraded the AMI version to v20210414 (based on this comment https://github.com/awslabs/amazon-eks-ami/issues/195#issuecomment-821195669 here https://github.com/awslabs/amazon-eks-ami/issues/195).

**Comment by john1337** [comment]
still face the same problem in 1.22.12

**Comment by pokiz** [comment]
I am also experiencing this in v1.30.4 during node disconnection tests.
We completely lost the monitoring/alerting stack part running on this node with a StefulSet.

**Comment by XtremeOwnageDotCom** [comment]
![image](https://github.com/user-attachments/assets/8886a37b-7002-4164-8378-f4a48c325520)

Might as well bring this issue into 2025... for 1.31

**Comment by XtremeOwnageDotCom** [comment]
> kubectl get pods --all-namespaces --field-selector spec.nodeName=rke-worker-2 | awk '{print $1, $2}' | tail -n +2 | while read namespace pod; do
>     kubectl delete pod "$pod" --namespace "$namespace" --grace-period=0 --force
> done

I love when its been years later.... I run into this issue on a different cluster... had forgotten all about this.

And then, manage to solve the issue myself, with my own comment years later.
