### ISSUE TITLE
Kubernetes dashboard is not coming up

### ISSUE THREAD

**Issue by tathagatkhanorkar** [kubernetes/kubernetes#72238]
**What happened**:
Kubernetes dashboard is not coming up.
I have a kubernetes cluster and a node

> 1

 $kubectl get pods --all-namespaces

 NAMESPACE     NAME                                 READY     STATUS    RESTARTS   AGE
kube-system   coredns-86c58d9df4-lrrmx             1/1       Running   0          2h
kube-system   coredns-86c58d9df4-zf2sz             1/1       Running   0          2h
kube-system   etcd-k8s-master                      1/1       Running   0          2h
kube-system   kube-apiserver-k8s-master            1/1       Running   0          2h
kube-system   kube-controller-manager-k8s-master   1/1       Running   0          2h
kube-system   kube-flannel-ds-amd64-tlmcq          1/1       Running   0          2h
kube-system   kube-flannel-ds-amd64-vlhsw          1/1       Running   0          2h
kube-system   kube-proxy-jnvw7                     1/1       Running   0          2h
kube-system   kube-proxy-zqfqr                     1/1       Running   0          2h
kube-system   kube-scheduler-k8s-master            1/1       Running   0          2h

$kubectl get nodes
NAME         STATUS    ROLES     AGE       VERSION
k8s-master   Ready     master    2h        v1.13.1
k8s-node     Ready     <none>    2h        v1.13.1

these are my kubernetes pods and deployments.

and following are those deployments and pods in which kubernetes dashboard gets up.

> 2

$kubectl get pods --all-namespaces
NAMESPACE     NAME                                  READY     STATUS    RESTARTS   AGE
default       demonode-7f6d877fbb-gzvp7             1/1       Running   0          8d
default       icagent-rgtx5                         0/0       Running   0          44d
kube-system   heapster-apiserver-84b844ffcf-jchmm   1/1       Running   0          44d
kube-system   kube-dns-64f844c854-cvf8l             0/3       Pending   0          44d
kube-system   kube-dns-64f844c854-vq9hh             3/3       Running   6          44d

$kubectl get nodes
NAME           STATUS    ROLES     AGE       VERSION
192.168.0.15   Ready     <none>    44d       v1.9.2-CCE2.0.7-B003

this cluster I am connected with is of opentelekom Cloud service Cloud Container Engine

**What you expected to happen**:
I want to create my own cluster using my master and node configuration, but i am not able to find these pods yaml to deploy them on my first cluster and node pair.

**Anything else we need to know?**:
Using 1st pair of kubernetes cluster made by me.

>  gulp serve

> [15:59:24] Failed to load external module @babel/register
> [15:59:24] Requiring external module babel-register
> [15:59:29] Using gulpfile ~/go/src/github.com/kubernetes/dashboard/gulpfile.babel.js
> [15:59:29] Starting 'clean-packaged-backend-source'...
> [15:59:29] Starting 'kill-backend'...
> [15:59:29] Finished 'kill-backend' after 364 μs
> [15:59:29] Starting 'locales-for-backend:dev'...
> [15:59:29] Starting 'scripts'...
> [15:59:30] Starting 'styles'...
> [15:59:30] Starting 'buildExistingI18nCache'...
> [15:59:31] Finished 'buildExistingI18nCache' after 852 ms
> [15:59:31] Starting 'angular-templates'...
> [15:59:31] Finished 'locales-for-backend:dev' after 1.55 s
> [15:59:31] Finished 'clean-packaged-backend-source' after 1.75 s
> [15:59:31] Starting 'package-backend-source'...
> [15:59:47] Finished 'scripts' after 18 s
> [15:59:49] Finished 'styles' after 19 s
> [15:59:49] Starting 'index'...
> [15:59:50] Finished 'index' after 501 ms
> [15:59:50] Finished 'angular-templates' after 20 s
> [15:59:50] Starting 'watch'...
> [15:59:52] Finished 'watch' after 1.65 s
> [15:59:52] Finished 'package-backend-source' after 21 s
> [15:59:52] Starting 'link-vendor'...
> [15:59:52] Finished 'link-vendor' after 518 μs
> [15:59:52] Starting 'package-backend'...
> [15:59:52] Finished 'package-backend' after 34 μs
> [15:59:52] Starting 'backend'...
> [16:00:10] Finished 'backend' after 18 s
> [16:00:10] Starting 'spawn-backend'...
> [16:00:10] Finished 'spawn-backend' after 19 ms
> [16:00:10] Starting 'serve'...
> [HPM] Proxy created: /api  ->  http://localhost:9091
> [16:00:10] Finished 'serve' after 145 ms
> 2018/12/20 16:00:10 Starting overwatch
> 2018/12/20 16:00:10 Using kubeconfig file: /root/.kube/config
> 2018/12/20 16:00:10 Skipping in-cluster config
> 2018/12/20 16:00:10 Using random key for csrf signing
> 2018/12/20 16:00:10 No request provided. Skipping authorization
> 2018/12/20 16:00:10 Successful initial request to the apiserver, version: v1.13.1
> 2018/12/20 16:00:10 Generating JWE encryption key
> 2018/12/20 16:00:10 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
> 2018/12/20 16:00:10 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
> 2018/12/20 16:00:11 Initializing JWE encryption key from synchronized object
> 2018/12/20 16:00:11 Creating in-cluster Heapster client
> [BS] [BrowserSync SPA] Running...
> [Browsersync] Access URLs:
> 2018/12/20 16:00:11 Serving insecurely on HTTP port: 9091
> 
> External: http://192.168.1.169:9090/
>  Local: http://localhost:9090/ 
> UI: http://localhost:3001
>  UI External: http://192.168.1.169:3001
> [Browsersync] Serving files from: /root/go/src/github.com/kubernetes/dashboard/dist/amd64
> [Browsersync] Serving files from: /root/go/src/github.com/kubernetes/dashboard/src/app
> 2018/12/20 16:00:11 Metric client health check failed: the server could not find the requested resource (get services heapster). Retr ying in 30 seconds. 

Using 2nd configuration of kubernetes cluster

>  gulp serve

> [16:11:55] Failed to load external module @babel/register
> [16:11:55] Requiring external module babel-register
> [16:11:59] Using gulpfile ~/go/src/github.com/kubernetes/dashboard/gulpfile.babel.js
> [16:11:59] Starting 'clean-packaged-backend-source'...
> [16:11:59] Starting 'kill-backend'...
> [16:11:59] Finished 'kill-backend' after 206 μs
> [16:11:59] Starting 'locales-for-backend:dev'...
> [16:11:59] Starting 'scripts'...
> [16:12:00] Starting 'styles'...
> [16:12:00] Starting 'buildExistingI18nCache'...
> [16:12:01] Finished 'buildExistingI18nCache' after 1.21 s
> [16:12:01] Starting 'angular-templates'...
> [16:12:02] Finished 'locales-for-backend:dev' after 2.1 s
> [16:12:02] Finished 'clean-packaged-backend-source' after 2.24 s
> [16:12:02] Starting 'package-backend-source'...
> [16:12:19] Finished 'scripts' after 19 s
> [16:12:21] Finished 'styles' after 21 s
> [16:12:21] Starting 'index'...
> [16:12:21] Finished 'index' after 240 ms
> [16:12:21] Finished 'angular-templates' after 20 s
> [16:12:21] Starting 'watch'...
> [16:12:23] Finished 'watch' after 1.55 s
> [16:12:23] Finished 'package-backend-source' after 21 s
> [16:12:23] Starting 'link-vendor'...
> [16:12:23] Finished 'link-vendor' after 5.09 ms
> [16:12:23] Starting 'package-backend'...
> [16:12:23] Finished 'package-backend' after 39 μs
> [16:12:23] Starting 'backend'...
> [16:12:25] Finished 'backend' after 1.57 s
> [16:12:25] Starting 'spawn-backend'...
> [16:12:25] Finished 'spawn-backend' after 15 ms
> [16:12:25] Starting 'serve'...
> [HPM] Proxy created: /api  ->  http://localhost:9091
> [16:12:25] Finished 'serve' after 87 ms
> 2018/12/20 16:12:25 Starting overwatch
> 2018/12/20 16:12:25 Using kubeconfig file: /root/.kube/config
> 2018/12/20 16:12:25 Skipping in-cluster config
> 2018/12/20 16:12:25 Using random key for csrf signing
> 2018/12/20 16:12:25 No request provided. Skipping authorization
> [BS] [BrowserSync SPA] Running...
> [Browsersync] Access URLs:
>        Local: http://localhost:9090/
>     External: http://192.168.1.169:9090/
>           UI: http://localhost:3001
>  UI External: http://192.168.1.169:3001
> [Browsersync] Serving files from: /root/go/src/github.com/kubernetes/dashboard/dist/amd64
> [Browsersync] Serving files from: /root/go/src/github.com/kubernetes/dashboard/src/app
> 2018/12/20 16:12:26 Successful initial request to the apiserver, version: v1.9.2-CCE2.0.7-B002-15-g1c2ee6c37ba9f1
> 2018/12/20 16:12:26 Generating JWE encryption key
> 2018/12/20 16:12:26 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
> 2018/12/20 16:12:26 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
> 2018/12/20 16:12:27 Initializing JWE encryption key from synchronized object
> 2018/12/20 16:12:27 Creating in-cluster Heapster client
> 2018/12/20 16:12:27 Serving insecurely on HTTP port: 9091
> 2018/12/20 16:12:27 Successful request to heapster

> $ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

> lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz
Stepping:              7
CPU MHz:               2194.711
BogoMIPS:              4389.42
Hypervisor vendor:     Microsoft
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              10240K

I want some guidance over how to make a usable kubernetes cluster pair to keep my dashboard up.
If anymore details are needed feel free to ask for it... 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
dashboard issues are tracked in https://github.com/kubernetes/dashboard

please re-file this there, thanks.

/close
