### ISSUE TITLE
Kubernetes Rolling Update not obeying 'maxUnavailable' replicas when redeployed in autoscaled conditions

### ISSUE THREAD

**Issue by bholagabbar-mt** [kubernetes/kubernetes#72231]
**What happened**:

Our apps are configured with the following `strategy` in the Deployment - 

      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate

The Horizonatal Pod Autoscaler is configured as so 
```
      spec:
        maxReplicas: 10
        minReplicas: 2
```
When our application was redeployed, instead of running a rolling update, it instantly terminated 8 of our pods and dropped the number of pods to 2 which is the min number of replicas available. This happened in a fraction of a second as you can see here

![](https://i.stack.imgur.com/V7AVN.png)

**What you expected to happen**:

As maxUnavailable is 25%, shouldn't only about 2-3 pods go down at max ? Why did so many pods crash at once ? It seems as though rolling update is useless if it works this way.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Output of `kubectl get hpa`
![](https://i.stack.imgur.com/ehlyV.png)

StackOverflow Question - https://stackoverflow.com/questions/53851948/kubernetes-rolling-update-not-obeying-maxunavailable-replicas-when-redeployed

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: AWS with Kops
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by Shnatsel** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by bskiba** [comment]
What is your HPA's scale target, Deployment or Replication Controller?  (See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#autoscaling-during-rolling-update)

**Comment by bholagabbar-mt** [comment]
@bskiba I believe Replication Controllers were deprecated ? We are using deployments..Will the output of `kubectl describe hpa <hpa_name> ` help ? I have attached it

Name:                                                          myapp
Namespace:                                                prod-singapore
Labels:                                                  
                                                          owner=dev
Annotations:                                              <none>
CreationTimestamp:                                        Fri, 21 Dec 2018 13:06:09 +0530
Reference:                                                Deployment/myapp
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  69% (1131220992) / 70%
  resource cpu on pods  (as a percentage of request):     23% (52m) / 70%
Min replicas:                                             2
Max replicas:                                             10
Deployment pods:                                          2 current / 2 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from memory resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>

**Comment by bskiba** [comment]
Thanks! It seems this should be working with HPA then.

HPA only modifies the desired number of replicas for the deployment, so it seems if there are issues, they should be in the rolling update implementation. Mentioning sig-apps to advise.
@kubernetes/sig-apps-bugs

**Comment by kow3ns** [comment]
/close
Available means that the Pods have been Ready for at least minReadySeconds. Replicas refers to the total number of replicas which is 8. If you're readiness check failed for some reason that could explain the discrepancy, but the Pods were not terminated by a RollingUpdate.

**Comment by pc-rshetty** [comment]
We faced this exact same issue today on eks 1.15

**Comment by kamalrajv** [comment]
I had similar issue where the new deployment will bring the pods down to 1 and then scale it up to the autoscaler values set.  i had below config in the deployment spec
replicas: 1 

Instead of having it defaulted to 1, i had it replaced with minReplicas value of the hpa, then i saw that it maintained that min value when new replicaset is taking action on bringing up the new image. 
Although when your pods have scaled beyond the Replicas count specified and you do a deployment it brings down the pods to the min value and both replicaset are in action until the count is matched with the load and also the new one taking the place of old one. 

hope this helps

**Comment by jeffro94** [comment]
I had this same issue as well.

> Instead of having it defaulted to 1, i had it replaced with minReplicas value of the hpa, then i saw that it maintained that min value when new replicaset is taking action on bringing up the new image.

Instead of this, you can just exclude the `replicas` value entirely from the deployment yaml. This is described at: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling
