### ISSUE TITLE
Namespaces "Terminating" forever, even after the APIService blocking termination is gone

### ISSUE THREAD

**Issue by Shnatsel** [kubernetes/kubernetes#72244]
**What happened**: In presence of an unresponsive APIService namespaces will not be deleted, but will be stuck in "Terminating" state forever. Deleting the unresponsive APIService will make deletion of newly created namespaces succeed, but namespaces already in "Terminating" state will be stuck forever. 

**What you expected to happen**:
1. After deleting the unresponsive API namespaces should be deleted instead of remaining stuck in "Terminating" state.
1. There should be log messages along the lines of "namespace X could not be deleted because finalizer Y failed" on namespace deletion failure. This is not normal state for the cluster and that fact should be logged.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/adapter-beta.yaml
Add one more API, this one will be unresponsive:
```yaml
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    name: custom-metrics-stackdriver-adapter
    namespace: custom-metrics
  version: v1beta1
```
Run the following in shell:
```bash
kubectl apply -f sd-adapter.yml
kubectl create ns my-test
kubectl delete ns my-test
```
Now you can observe the namespace being stuck in "Terminating" state:
```
me@desktop:~$ kubectl get namespaces
NAME             STATUS        AGE
custom-metrics   Active        10m
default          Active        22h
kube-public      Active        22h
kube-system      Active        22h
my               Active        1h
my-test          Terminating   7m
```
Deleting the unresponsive API should let the namespace successfully terminate, but doesn't:
```
me@desktop:~$ kubectl get --raw '/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.external.metrics.k8s.io' | jq . > tmp.json
me@desktop:~$ kubectl delete -f tmp.json
apiservice.apiregistration.k8s.io "v1beta1.external.metrics.k8s.io" deleted
me@desktop:~$ kubectl get ns
NAME             STATUS        AGE
custom-metrics   Active        15m
default          Active        22h
kube-public      Active        22h
kube-system      Active        22h
my               Active        1h
my-test          Terminating   12m
me@desktop:~$ 
me@desktop:~$ kubectl get ns
NAME             STATUS        AGE
custom-metrics   Active        17m
default          Active        22h
kube-public      Active        22h
kube-system      Active        22h
my               Active        1h
my-test          Terminating   13m
```
Looks like it will never succeed without removing finalizer, but newly created namespaces will be deleted:
```
me@desktop:~$ kubectl create ns my-new
namespace/my-new created
me@desktop:~$ kubectl delete ns my-new
namespace "my-new" deleted
me@desktop:~$ kubectl get ns
NAME             STATUS        AGE
custom-metrics   Active        17m
default          Active        22h
kube-public      Active        22h
kube-system      Active        22h
my               Active        1h
my-test          Terminating   14m
```

**Anything else we need to know?**: This looks similar to #66735, but I also have exact reproduction steps. 

I have tried to trace execution of the namespace deletion to pinpoint what exactly goes wrong, but my plan was foiled because [the relevant code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/deletion/namespaced_resources_deleter.go) has very little debug logging.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.11-gke.1, 1.11.5-gke.4
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): GKE host

/kind bug
@kubernetes/sig-api-machinery-bugs
@derekwaynecarr
@smarterclayton

**Comment by smarterclayton** [comment]
It would have been better if namespaces had status and the namespace deletion controller wrote that message into namespace status

**Comment by logicalhan** [comment]
@sergeyevstifeev, I can't seem to reproduce your result. These are the steps I have taken to reproduce your issue, given a fresh build/deploy of kubernetes on v1.11.5. 

```
wget https://gist.githubusercontent.com/logicalhan/cc707e8ec84ec84ca36df690d8fce80b/raw/58194777f6a01c334ab7e8a879166ba512d43f53/issue-72244.yaml
kubectl apply -f issue-72244.yaml
kubectl create ns ns-test
kubectl delete ns ns-test
```

At this point, I can observe the namespace which is stuck in the terminating state. At this point, if I run the following two commands:

```
kubectl get --raw '/apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.external.metrics.k8s.io' >> tmp.json
kubectl delete -f tmp.json
```

I can observe via `watch kubectl get ns` in another terminal, that after a certain amount of time, that the namespace is deleted. Is there something here that I am missing?
