### ISSUE TITLE
set --insecure-port to 0 breaks kube-addon-manager

### ISSUE THREAD

**Issue by sandeep-kotha** [kubernetes/kubernetes#72240]
/triage support

Kubernetes Version: 1.12.1
kube-addon-manager: k8s.gcr.io/kube-addon-manager-amd64:v8.7
kube-apiserver: k8s.gcr.io/hyperkube-amd64:v1.12.1

- Lock down Insecure port on API server set --insecure-port to 0

- Kubectl logs kube-addon-manager  -n kube-system. You see an error 
The connection to the server localhost:8080 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==

**Root Cause:** Kubectl is communication over default port 8080
**Solution**: put config in .kube (It works)
**Problem:** I ended up creating my own image. Currently is there any way or work in progress to support kube-addon-manager to use kube config to communicate with API server ?

**Comment by sandeep-kotha** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by sandeep-kotha** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by sandeep-kotha** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by liggitt** [comment]
running in a pod or mounting in credentials to the default location or setting KUBECONFIG both work for configuring the add-on manager to authenticate to the apiserver

/close
