### ISSUE TITLE
deployments/rollback not passed to validation

### ISSUE THREAD

**Issue by jhrv** [kubernetes/kubernetes#72256]
**What happened**:
I'm unable to configure the api-server through a `ValidatingWebhookConfiguration` to pass admission requests to my `ValidatingAdmissionWebhook` for the `deployments/rollback` resource. 

I'm adding the following rule to the `ValidatingWebhookConfiguration`
```
  - apiGroups:
    - extensions
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - deployments/rollback
```

When performing rollbacks, I'm not seeing any calls to the admission webhook.

**What you expected to happen**:

To receive validation requests when performing rollbacks.

**How to reproduce it (as minimally and precisely as possible)**:
Create a ValidatingAdmissionWebhook and perform a rollback request.

**Anything else we need to know?**:
Mentioned this on the #sig-api-machinery channel on Slack, and @liggitt suggested the error was that the `createValidation`-object never is used: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/apps/deployment/storage/storage.go#L163-L183

**Environment**:
- Kubernetes version (use `kubectl version`):
1.12.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Container Linux by CoreOS 1911.5.0 (Rhyolite)   4.14.84-coreos   docker://18.6.1
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by hzxuzhonghu** [comment]
Good point, should call `createValidation`.
