### ISSUE TITLE
Publish Test Results from Master Branch of Cri-o To http://prow.k8s.io 

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#72253]
In  order to promote [RunAsGroup](https://github.com/kubernetes/enhancements/issues/213) to beta, we want to make sure we have coverage for cri-o in CI.

Currently CRI-o is publishing tests results for every  PR to k/k  http://prow.k8s.io . We want to make sure only master branch tests results for CRI-O are being published to k/k for accuracy.

**Comment by krmayankk** [comment]
Any update on this @runcom ?

**Comment by krmayankk** [comment]
Any update @runcom  ?

**Comment by krmayankk** [comment]
@runcom  can you update if you are working on this ?
cc @tallclair

**Comment by krmayankk** [comment]
@runcom  any update on this. Is this something you are working on ?

**Comment by liggitt** [comment]
it looks like this aged out... has this been done?

**Comment by BenTheElder** [comment]
> Currently CRI-o is publishing tests results for every PR to k/k http://prow.k8s.io . We want to make sure only master branch tests results for CRI-O are being published to k/k for accuracy.

Where exactly, which tests? What job? I'm not aware of any cri-o tests in prow.k8s.io ...

**Comment by krmayankk** [comment]
- Verified that RunAsGroup tests are running for containerd in k/k as per logs [here](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94641/pull-kubernetes-e2e-gce-ubuntu-containerd/1304635954148937729/#1:build-log.txt%3A55564) 
- I see some backporting here for RunAsGroup in cri-o https://github.com/cri-o/cri-o/pull/4115
- 
@kolyshkin i see some flags  set but cannot find where RunAsGroup tests are running 
```
grep -r RunAsGroup *
integration/build/kubernetes.yml:      export FEATURE_GATES="AllAlpha=false,RunAsGroup=true"
```
but dont know how to verify if RunAsGroup tests are running. i looked at 
- https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4169/test_pull_request_crio_integration_crun_fedora/12316/
- https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4169/test_pull_request_crio_integration_crun_fedora_cgroupv2/3497/
- https://prow.ci.openshift.org/view/gcs/origin-federated-results/pr-logs/pull/cri-o_cri-o/4169/test_pull_request_crio_integration_rhel/20889/
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/4169/pull-ci-cri-o-cri-o-release-1.19-e2e-aws/1302919257016766464
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/4169/pull-ci-cri-o-cri-o-release-1.19-images/1302919257872404480

@tallclair  what else do we need to do ? Do we need to add tests  in k/k that verify RunAsGroup tests are passing for cri-o as well or we rely on tests in the cri-o repo ?

**Comment by krmayankk** [comment]
@tallclair  ping ?

**Comment by tallclair** [comment]
> Do we need to add tests in k/k that verify RunAsGroup tests are passing for cri-o as well or we rely on tests in the cri-o repo ?

The best way to handle this might be to add it to the CRI validation suite: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/validation.md

I'm not sure how those are tracked with respect to containerd and cri-o though.

**Comment by krmayankk** [comment]
@kubernetes/sig-node-pr-reviews can someone advice on the question of how to ensure RunAsGroup tests are present in cri-o validation suite @feiskyer  @saschagrunert  @jterry75 ?

**Comment by krmayankk** [comment]
I see https://github.com/kubernetes-sigs/cri-tools/blob/16911795a3c33833fa0ec83dac1ade3172f6989e/pkg/validate/security_context_linux.go#L357 has a RunAsGroup test, does this mean it is present in CRI validation suite and is somehow ensuring that all Runtimes must pass this test ? Where are this results logged ?

**Comment by krmayankk** [comment]
> @kubernetes/sig-node-pr-reviews can someone advice on the question of how to ensure RunAsGroup tests are present in cri-o validation suite @feiskyer @saschagrunert @jterry75 ?

pinging again @feiskyer @saschagrunert @jterry75

**Comment by saschagrunert** [comment]
> I see https://github.com/kubernetes-sigs/cri-tools/blob/16911795a3c33833fa0ec83dac1ade3172f6989e/pkg/validate/security_context_linux.go#L357 has a RunAsGroup test, does this mean it is present in CRI validation suite and is somehow ensuring that all Runtimes must pass this test ? Where are this results logged ?

We run CRI-O and containerd tests in cri-tools directly. CRI-O (and probably containerd too) run critest in their own repository again. I think this is not a Kubernetes issue we're speaking about here. I'm wondering which kind of tests are missing from critest. If you see some, can you please transfer this issue to cri-tools and close this one?

**Comment by krmayankk** [comment]
@saschagrunert i dont think tests are missing in cri-tools or the respective repos of cri-o or containerd. I pointed to tests in [here](https://github.com/kubernetes-sigs/cri-tools/blob/16911795a3c33833fa0ec83dac1ade3172f6989e/pkg/validate/security_context_linux.go#L357) which are related to RunAsGroup .  You mentioned both CRI-O and containerd are tested in cri-tools. Can you confirm if RunAsGroup is tested for both CRI-O and containerd ? How can i confirm that ?

I am trying to answer @tallclair question above

> The best way to handle this might be to add it to the CRI validation suite: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/validation.md

?
I'm not sure how those are tracked with respect to containerd and cri-o though.

**Comment by saschagrunert** [comment]
> @saschagrunert i dont think tests are missing in cri-tools or the respective repos of cri-o or containerd. I pointed to tests in [here](https://github.com/kubernetes-sigs/cri-tools/blob/16911795a3c33833fa0ec83dac1ade3172f6989e/pkg/validate/security_context_linux.go#L357) which are related to RunAsGroup . You mentioned both CRI-O and containerd are tested in cri-tools. Can you confirm if RunAsGroup is tested for both CRI-O and containerd ? How can i confirm that ?

Yes, we run every critest test for containerd and CRI-O in the cri-tools repository as GitHub action:
- https://github.com/kubernetes-sigs/cri-tools/actions?query=workflow%3A%22critest+containerd%22
- https://github.com/kubernetes-sigs/cri-tools/actions?query=workflow%3A%22critest+CRI-O%22

**Comment by krmayankk** [comment]
> > @saschagrunert i dont think tests are missing in cri-tools or the respective repos of cri-o or containerd. I pointed to tests in [here](https://github.com/kubernetes-sigs/cri-tools/blob/16911795a3c33833fa0ec83dac1ade3172f6989e/pkg/validate/security_context_linux.go#L357) which are related to RunAsGroup . You mentioned both CRI-O and containerd are tested in cri-tools. Can you confirm if RunAsGroup is tested for both CRI-O and containerd ? How can i confirm that ?
> 
> Yes, we run every critest test for containerd and CRI-O in the cri-tools repository as GitHub action:
> 
> * https://github.com/kubernetes-sigs/cri-tools/actions?query=workflow%3A%22critest+containerd%22
> * https://github.com/kubernetes-sigs/cri-tools/actions?query=workflow%3A%22critest+CRI-O%22

@tallclair @liggitt  is that enough or do we need to somehow bring these results back to k/k CI ?

**Comment by BenTheElder** [comment]
Validating a Kubernetes feature does not involve running it on every existing implementation of pluggable mechanisms / extension points. We are not for example going to run all CNI implementations
Sometime we need to run one concrete implementation in order to get a functioning cluster, but it's always about testing _the kubernetes parts_. 
prow.k8s.io is eliminating any lingering projects that are not part of upstream k8s (basically legacy from being Google provided), wg-k8s-infra does not host external projects.
**Testgrid** despite the domain alias is still Google and does.

**Comment by krmayankk** [comment]
> Validating a Kubernetes feature does not involve running it on every existing implementation of pluggable mechanisms / extension points. We are not for example going to run all CNI implementations
> Sometime we need to run one concrete implementation in order to get a functioning cluster, but it's always about testing _the kubernetes parts_.
> prow.k8s.io is eliminating any lingering projects that are not part of upstream k8s (basically legacy from being Google provided), wg-k8s-infra does not host external projects.
> **Testgrid** despite the domain alias is still Google and does.

Sounds good, then i think there is no action needed here. I will check the integration tests for RunAsGroup and make sure enough coverage is there and we should be goo. I will wait for any comments from @tallclair

**Comment by krmayankk** [comment]
@tallclair i have verified with help from @saschagrunert that cri-tools has RunAsGroup test coverage for both containerd and CRI-O and we dont need to publish these results to k/k. So i believe this issue can be closed as no op. Also i have verified that test coverage exists and no further tests are need wrt RunAsGroup. Can you confirm we can close this issue ?

**Comment by ehashman** [comment]
/close

@tallclair please reopen if you think this has not been addressed.
