### ISSUE TITLE
1.13.1 kube-proxy ipvs don't work when pod ip is changed

### ISSUE THREAD

**Issue by xiaosuhan** [kubernetes/kubernetes#72270]
**What happened**:

In k8s 1.13.1 version。When a Pod is changed, the kube-proxy log(info) show that the LVS rs IP is changed. but using 'ipvsadm -Ln', it's unccorrectly.    it's only Part of the node will have the situation
sometimes.
the bad node in  kube-proxy log(info)   don't have    `graceful_termination.go:160] Trying to delete rs 
  xxxxxx `  and   `graceful_termination.go:173] Deleting rs  xxxxx` 

**What you expected to happen**:

The nodeport  on the corresponding node is inaccessible

**How to reproduce it (as minimally and precisely as possible)**:

in 1.13.1 version，and  then update one deployment . use `ipvsadm -Ln` check nodeport

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `1.13.1`):
- Cloud provider or hardware configuration:
- OS (CentOS Linux):
- Kernel (3.10.0-514.el7.x86_64 ):
- Install tools: ipvsadm-1.27-7.el7.x86_64
- Others:

/kind bug
 
![kube-proxy](https://user-images.githubusercontent.com/28727045/50418351-e9476480-0865-11e9-81ca-e04353b2c6c3.png)

**Comment by xuezm01** [comment]
I have the same problem，Is there a solution that can be solved?

**Comment by 2PacIsAlive** [comment]
might be related to https://github.com/kubernetes/kubernetes/issues/71071, if so v1.13.2 has the fix

**Comment by lbernail** [comment]
Yes there is definitely a problem with `v1.13.1`
If the issue persists with `v1.13.2` let us know

**Comment by thockin** [comment]
One better - if this still exists, please reopen

**Comment by shimron** [comment]
having the same problem in v1.13.8, logs:

`I1021 08:29:22.907423 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.86.120:6666
I1021 08:29:22.907428 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.86.81:6666
I1021 08:29:22.907596 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.86.81:6666
I1021 08:29:22.907615 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.86.81:6666
I1021 08:29:22.907621 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.80.10:6666
I1021 08:29:22.907774 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.80.10:6666
I1021 08:29:22.907787 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.80.10:6666
I1021 08:29:22.907792 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.90.157:6666
I1021 08:29:22.908107 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.90.157:6666
I1021 08:29:22.908162 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.90.157:6666
I1021 08:29:22.908183 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.92.228:6666
I1021 08:29:22.908505 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.92.228:6666
I1021 08:29:22.908541 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.92.228:6666
I1021 08:29:22.908551 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.115.122:6666
I1021 08:29:22.908677 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.115.122:6666
I1021 08:29:22.908696 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.115.122:6666
I1021 08:29:22.908703 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.93.178:6666
I1021 08:29:22.908808 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.93.178:6666
I1021 08:29:22.909155 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.93.178:6666
I1021 08:29:22.909180 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.82.7:6666
I1021 08:29:22.909294 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.82.7:6666
I1021 08:29:22.909331 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.82.7:6666
I1021 08:29:22.909357 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.102.33:6666
I1021 08:29:22.909501 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.102.33:6666
I1021 08:29:22.910176 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.102.33:6666
I1021 08:29:22.910185 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.86.77:6666
I1021 08:29:22.910297 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.86.77:6666
I1021 08:29:22.910311 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.86.77:6666
I1021 08:29:22.910316 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.90.152:6666
I1021 08:29:22.910401 1 graceful_termination.go:172] Not deleting, RS 11.233.32.84:6666/TCP/11.233.90.152:6666: 0 ActiveConn, 1 InactiveConn
I1021 08:29:22.910409 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.106.75:6666
I1021 08:29:22.910523 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.106.75:6666
I1021 08:29:22.910544 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.106.75:6666
I1021 08:29:22.910550 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.115.102:6666
I1021 08:29:22.910640 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.115.102:6666
I1021 08:29:22.910656 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.115.102:6666
I1021 08:29:22.910660 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.115.67:6666
I1021 08:29:22.910746 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.115.67:6666
I1021 08:29:22.910759 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.115.67:6666
I1021 08:29:22.910763 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.67.117:6666
I1021 08:29:22.910849 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.67.117:6666
I1021 08:29:22.910862 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.67.117:6666
I1021 08:29:22.910867 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.74.117:6666
I1021 08:29:22.910944 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.74.117:6666
I1021 08:29:22.910955 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.74.117:6666
I1021 08:29:22.910959 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.109.51:6666
I1021 08:29:22.911058 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.109.51:6666
I1021 08:29:22.911078 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.109.51:6666
I1021 08:29:22.911088 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.98.62:6666
I1021 08:29:22.911180 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.98.62:6666
I1021 08:29:22.911195 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.98.62:6666
I1021 08:29:22.911200 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.93.132:6666
I1021 08:29:22.911270 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.93.132:6666
I1021 08:29:22.911285 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.93.132:6666
I1021 08:30:22.911437 1 graceful_termination.go:161] Trying to delete rs: 11.233.32.84:6666/TCP/11.233.90.152:6666
I1021 08:30:22.911622 1 graceful_termination.go:175] Deleting rs: 11.233.32.84:6666/TCP/11.233.90.152:6666
I1021 08:30:22.911645 1 graceful_termination.go:94] lw: remote out of the list: 11.233.32.84:6666/TCP/11.233.90.152:6666`

**Comment by lbernail** [comment]
The logs don't indicate a problem, this is expected with graceful termination
What symptoms are you seeing?

**Comment by shimron** [comment]
When updating a deployment, requests to the pods through the service ip are timeout on some nodes. After restart the kube-proxy on those nodes, the timeout disappeared. At the same time, there are many logs in kube-proxy pod like above.
