### ISSUE TITLE
Can we deprecate '--image-gc-high-threshold' and 'image-gc-low-threshold'

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#72272]
**What would you like to be added**:
deprecate '--image-gc-high-threshold' and 'image-gc-low-threshold' and using eviction instead
since now we have two policy (two entrance) of image garbage collection. maybe it's time to deprecate one of them and remove it in future.
https://github.com/kubernetes/kubernetes/blob/d257ee9bfdd8e32138d6c906ec94411b8e1d62fd/pkg/kubelet/kubelet.go#L1301-L1306
**Why is this needed**:

/kind feature
/kind cleanup
/sig node

**Comment by liggitt** [comment]
image GC is not the same thing as eviction, right? I'm not sure I understand what the replacement for image GC would be

**Comment by Pingan2017** [comment]
@liggitt  image GC is not the same thing as eviction. Eviction can call image GC.
in k8s, there are two ways to GC images:
1. the first way: when the disk usage reachs the image-gc-high-threshold, the GarbageCollect will clean up iamges to fee spaces.
https://github.com/kubernetes/kubernetes/blob/d476af7c199df9b5b1d42bc85e24aa167934a2ef/pkg/kubelet/images/image_gc_manager.go#L297-L304

2. the other way is : when the imagefs.available < 15% OR nodefs.available < 10, the eviction will call imageGC to remove images.
https://github.com/kubernetes/kubernetes/blob/d476af7c199df9b5b1d42bc85e24aa167934a2ef/pkg/kubelet/eviction/helpers.go#L1019-L1032

in my opinion, we just only keep the second way and deprecate the first one.

**Comment by Pingan2017** [comment]
ping @kubernetes/sig-node-feature-requests
