### ISSUE TITLE
Cinder volumes not being detached during instance failure

### ISSUE THREAD

**Issue by Mohamedji** [kubernetes/kubernetes#72273]
**What happened**: When a node failure occurs and new pod is scheduled but get stuck in ContinerCreating Status

**What you expected to happen**: Cinder Volume should have been detached from node and attached to new node where pod is scheduled

**How to reproduce it (as minimally and precisely as possible)**:  
Steps : 
1.Deploy mysql deployment with pv
kubectl apply -f https://k8s.io/examples/application/wordpress/mysql-deployment.yaml

2.Check where pod is running
kubectl get pods -o wide

3.Shutdown node where pod is running
init 0

4. Wait for pod to get scheduled on new node
kubectl get pods -o wide

![image](https://user-images.githubusercontent.com/6219755/50335430-5048de80-0531-11e9-8230-3043b6fe7cc9.png)

5. Retrieve more details of pod
kubectl describe pod wordpress-mysql-7d4fc77fdc-8nvc5

![image](https://user-images.githubusercontent.com/6219755/50335500-838b6d80-0531-11e9-8a8d-a16d1a3fa07f.png)

**Anything else we need to know?**:  

Even rook with ceph rbd gives same error 

![image](https://user-images.githubusercontent.com/6219755/50335609-d6652500-0531-11e9-89b4-d9c9082bff2a.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 
4CPU & 8 GB RAM

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux ktest1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm v1.13.1

- Others:

@kubernetes/sig-openstack @kubernetes/sig-storage @kubernetes/sig-cluster-lifecycle

/kind bug

**Comment by Mohamedji** [comment]
@kubernetes/sig-openstack @kubernetes/sig-storage @kubernetes/sig-cluster-lifecycle

**Comment by Mohamedji** [comment]
@zetaab Any fix for this.

**Comment by zetaab** [comment]
@Mohamedji this is known issue, there are quite many other issues from this same issue https://github.com/kubernetes/kubernetes/issues/65392 https://github.com/kubernetes/kubernetes/issues/53059
