### ISSUE TITLE
Add Lazy Evaluation of Resource Quotas Limits

### ISSUE THREAD

**Issue by kelaban** [kubernetes/kubernetes#72278]
Moving a thread from sig-scheduling slack to here.

**What would you like to be added**:

Some Resource Quota limits should be evaluated lazily in the scheduler instead of eagerly during pod submission. For example, if a namespace RQ limits a user to 1 CPU, that user should be able to submit N number of 1 CPU Pods and they should execute one at a time.  With current implementation any requests beyond the initial 1 CPU Pod will be immediately rejected (i.e. eager evaluation of the quota).

Limits on CPU, RAM, and extended resources such as GPU are examples of quotas which should have a "soft" limit which is evaluated lazily and enforced by the scheduler

Limits on number of items (such as number of Pods/ConfigMaps/etc.) are example of quotas which should probably be evaluated eagerly

**Why is this needed**:

From an end users perspective; if I submit a Pod and the cluster is saturated or my Pod is unschedualable for any other reason my request is accepted and held in the queue for scheduling. However, if my namespace is saturated due to RQs or my request is unscheduable because my request is larger than my quota, my request is rejected immediately. These behaviors are inconsistent for the end user.

In the run-to-completion world, this is a common issue. People do not use Pods, as in the example but they use Jobs or some other type of controller to manage their Pods. Because of the inconsistent behavior each of these controller implementations need to be _Quota Aware_  in order to handler the latter part of my example above. 

/kind feature

**Comment by everpeace** [comment]
As kelaban wrote, I'm also interested in introducing `ResourceQuota.spec.soft` from a viewpoint of enduers. 

However, I believe that kubernetes is extensible enough to solve this issue.  I think the issue can be solved mostly by implementing [scheduler extender](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md).

FYI: I implemented [everpeace/kube-throttler](https://github.com/everpeace/kube-throttler/blob/master/example/throttle.yaml). This provicdes an CRD which is similar to "soft" resource quota.

For example,  if below CRD is defined,

```
kind: Throttle
metadata:
  namespace: ns1
  name: throttle1
spec:
  selector:
    someKey: someValue
  threshold:
     cpu: 2
```

Then, it can prohibit to schedule any pods (just keep pods `Pending` state) when it detects `requests.cpu` of running pods with label `someKey=someValue` reaches `2`.

Users can see  below event when throttle is active (i.e. your request exceeds "soft" quota):

```
$ kubectl describe pod throttled-pod
...
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  14s (x9 over 1m)  my-scheduler       pod is unschedulable due to throttles[active]=(default,throttle1)
```

So, I think we would focus to discuss why kubernetes supports this feature officially.

**Comment by Huang-Wei** [comment]
/reopen

I think it's a valid requirement. Let's see if we can get a KEP solving this.

**Comment by alculquicondor** [comment]
There is incubation work going on

- https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/9-capacity-scheduling
- https://docs.google.com/document/d/1ViujTXLP1XX3WKYUTk6u5LTdJ1sX-tVIw9_t9_mLpIc/edit#
