### ISSUE TITLE
Include CRI Test Coverage in k/k CI

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#72287]
As part of promoting [RunAsGroup](https://github.com/kubernetes/enhancements/issues/213) feature  to beta, there were several questions that came up. This issue serves to capture those questions and initiate a discussion to eventually get answers or solutions to those.

Questions
- Are CRI tests included in k/k CI  for at least Containerd and CRI-O ?
- If not , should we depend on CI test results published from those external repos to http://prow.k8s.io/ or should we just include those tests inline in this repo  so that its easier to debug ?
- What should be included in CRI tests in the CI ? Is crictl testsuite enough or more is needed ?
- Should dockershim be removed or continue to exist ?
- Should failure of CRI tests be release blocking ?

**Comment by krmayankk** [comment]
@jberkus  @BenTheElder @runcom @liggitt  @tallclair @Random-Liu

**Comment by liggitt** [comment]
it looks like this aged out... has this been done?
