### ISSUE TITLE
dev-build-and-push.sh is broken

### ISSUE THREAD

**Issue by b1zzu** [kubernetes/kubernetes#72297]
Hi,

the `hack/dev-build-and-push.sh` script is broken because the `cluster/kube-push.sh` script has been removed from in this pull request: https://github.com/kubernetes/kubernetes/pull/58247 .

Is `dev-build-and-push.sh` deprecated too, shall we remove it?

/kind bug

**Comment by b1zzu** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by dims** [comment]
@stewart-yu hope it's ok since it's been a while, i pushed a small change. if you still want to work this, let me know and i'll drop the PR

**Comment by stewart-yu** [comment]
@dims :+1: 
you can go head
