### ISSUE TITLE
oom_score_adj for guarenteed containers

### ISSUE THREAD

**Issue by clkao** [kubernetes/kubernetes#72294]
**What would you like to be added**:

Increase the default [guaranteedOOMScoreAdj](https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/kubelet/qos/policy.go#L33), and/or make it adjustable.

**Why is this needed**:

Currently `guaranteedOOMScoreAdj` is the same as `PodInfraOOMAdj` (-998).  When OOM is triggered by a guaranteed pod, the `pause` container is consistently killed first, followed by init process (`tini` in this case) of the actual container.  This seems to be consistent with the manifestation of [node notready/flappy PLEG](https://github.com/kubernetes/kubernetes/issues/45419) on our system (v1.11.5 with docker 17.03.2-ce).

As killing the `pause` process restarts the infra container, subsequent killing of the `tini` process might cause some weird lockup in docker. This is suspected as the kubelet message is: `PLEG not healthy Warning ContainerGCFailed`

We should at least increase `guaranteedOOMScoreAdj` to -997 so processes in the non-infra container, which are likely the ones causing OOM, get killed first.  It appears this was the behaviour before #32926 (infra = -999 and guaranteed = -998), but infra became -998 whilst docker was ensured to be -999.

If we further increase `guaranteedOOMScoreAdj`, it will take the actual process memory usage into account and OOM triggers can be reduced for the same pod, as the right process gets killed.  The [current logic](https://github.com/kubernetes/kubernetes/blame/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/kubelet/qos/policy.go#L62) ensures burstables >= guaranteed in the case of node-wide OOM. Actually the (currently incorrect) inline comment `A guaranteed pod using 100% of memory can have an OOM score of 10` indicates `guaranteedOOMScoreAdj` should be -990.  With the value if a process uses > 90% memory within the guaranteed pod, it can be correctly identified and killed.

What do people think that the reasonable default should be? and should this be made adjustable as kubelet config, or as pod option?

/sig node

/kind feature

**Comment by jiaxuanzhou** [comment]
#71269 is a similar pr to this issue, but it is better to make it an option of kubelet
