### ISSUE TITLE
Is there a way to seperate NodeExternalIP and NodeInternalIP on vsphere cloud?

### ISSUE THREAD

**Issue by clivez** [kubernetes/kubernetes#72308]
**What happened**:
All nodes in the cluster have two IPs, one from a internal network and the other from a public network, for example:
```
[root@monster-manager-1 ~]# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.2.122  netmask 255.255.255.0  broadcast 172.16.2.255
        inet6 4001:172:214::122  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::250:56ff:fead:d18  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:ad:0d:18  txqueuelen 1000  (Ethernet)
        RX packets 69401548  bytes 25885430203 (24.1 GiB)
        RX errors 0  dropped 19  overruns 0  frame 0
        TX packets 57719464  bytes 34119309070 (31.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@monster-manager-1 ~]# ifconfig eth1
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.42.242.193  netmask 255.255.254.0  broadcast 10.42.243.255
        inet6 fe80::250:56ff:fead:a2ec  prefixlen 64  scopeid 0x20<link>
        inet6 2a00:8a00:6000:6104:10:42:242:193  prefixlen 64  scopeid 0x0<global>
        ether 00:50:56:ad:a2:ec  txqueuelen 1000  (Ethernet)
        RX packets 1007959  bytes 1418865547 (1.3 GiB)
        RX errors 0  dropped 19  overruns 0  frame 0
        TX packets 110806  bytes 6573121 (6.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
And we use `--node-ip=172.16.2.122` when start kubelet.
When describe the node, I got one ExternalIP and two InternalIPs in the Addresses field.
```
Addresses:
  ExternalIP:  172.16.2.122
  InternalIP:  172.16.2.122
  InternalIP:  10.42.242.193
  Hostname:    monster-manager-1
```
**What you expected to happen**:
It will be very appreciated if there could be a way to identify which IP is internal and which is actually external
```
Addresses:
  InternalIP:  172.16.2.122
  ExternalIP:  10.42.242.193
  Hostname:    monster-manager-1
```

**How to reproduce it (as minimally and precisely as possible)**:
From the code 
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L655-L663
I see vsphere will report an IP as both internal and external, is it possible to identify whether an IP is actually internal or external?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
vsphere
- OS (e.g. from /etc/os-release):
Red Hat Enterprise Linux Server 7.5 (Maipo)
- Kernel (e.g. `uname -a`):
3.10.0-862.11.6.el7.x86_64
- Install tools:
- Others:

/kind bug

**Comment by clivez** [comment]
Hello, is there anyone that has any idea?

**Comment by clivez** [comment]
Helloooooooo?

**Comment by clivez** [comment]
Will anybody help?

**Comment by rsolus** [comment]
This issue is really problematic in my project. Is there anyone who can help to solve it?
