### ISSUE TITLE
kubetest --up create cluster failed

### ISSUE THREAD

**Issue by taragu** [kubernetes/kubernetes#72301]
**What happened**:
I was trying to create a local cluster with `kubetest --up`, but got an error:
```
[guw@ibm.com@mbp ~/go/src/k8s.io/kubernetes (readonly-test-validate-readonly-io)]$ kubetest --up
2018/12/22 16:01:37 process.go:153: Running: ./hack/e2e-internal/e2e-down.sh
.....
.....
2018/12/22 16:01:59 process.go:153: Running: ./hack/e2e-internal/e2e-up.sh
Project: tara-test-dec-19
Network Project: tara-test-dec-19
Zone: us-central1-b
... Starting cluster in us-central1-b using provider gce
... calling verify-prereqs
... calling verify-kube-binaries
... calling verify-release-tars
... calling kube-up
Project: tara-test-dec-19
Network Project: tara-test-dec-19
Zone: us-central1-b
BucketNotFoundException: 404 gs://kubernetes-staging-9e568f11b7 bucket does not exist.
Creating gs://kubernetes-staging-9e568f11b7
Creating gs://kubernetes-staging-9e568f11b7/...
+++ Staging server tars to Google Storage: gs://kubernetes-staging-9e568f11b7/e2e-test-guw@ibm.com-devel
+++ kubernetes-server-linux-amd64.tar.gz uploaded (sha1 = 02c0bea82ac271a972c1fe5f593b89f32bfccd81)
+++ kubernetes-manifests.tar.gz uploaded (sha1 = 069de1b397ad823b861472bcbf4dc1f4343903ea)
INSTANCE_GROUPS=
NODE_NAMES=
Looking for already existing resources
Creating new auto network: e2e-test-guw@ibm.com
ERROR: (gcloud.compute.networks.create) Could not fetch resource:
 - Invalid value for field 'resource.name': 'e2e-test-guw@ibm.com'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'

2018/12/22 16:07:24 process.go:155: Step './hack/e2e-internal/e2e-up.sh' finished in 5m25.185997102s
2018/12/22 16:07:24 main.go:313: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 1
```

The important part is `Invalid value for field 'resource.name': 'e2e-test-guw@ibm.com'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'`. This error occurs because my mac account name is "guw@ibm.com" which doesn't match the regex, and this user name is being used in the resource name without any checks (see `cluster/gce/config-test.sh` line 107 and 111 https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L107 ). 

**What you expected to happen**:
kubetest --up can create resource with a name that matches the regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'. It should check if `${USER}` matches the regex and uses it in the resource name only if it does. 

**How to reproduce it (as minimally and precisely as possible)**:
Update your mac's account name to "xxx@xxx.com". 
![2018-12-22_20-18-03](https://user-images.githubusercontent.com/6353048/50379980-4a81f480-0628-11e9-96c8-d8a2b7efa082.png)

Install kubetest with `go get -u k8s.io/test-infra/kubetest`, and run `kubetest --build` and `kubetest --up`.

**Anything else we need to know?**: a temporary workaround is to update line [107](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L107) to `NETWORK=${KUBE_GCE_NETWORK:-e2e-test-xxx}` and line [111](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L111) to `INSTANCE_PREFIX="${KUBE_GCE_INSTANCE_PREFIX:-e2e-test-xxx}"` and the cluster can be created successfully. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.0.963+1f58c78f0821d4", GitCommit:"1f58c78f0821d4a0834fb7c646c61234444c8ce2", GitTreeState:"clean", BuildDate:"2018-12-21T21:53:05Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: gcp
- OS (e.g. from /etc/os-release): macos 10.14.1
- Kernel (e.g. `uname -a`): 
`Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`
- Install tools: 
- Others: 

/kind bug

**Comment by liggitt** [comment]
Can you set the network to a valid value by setting KUBE_GCE_NETWORK directly prior to invoking the script?

**Comment by taragu** [comment]
@liggitt just tried setting KUBE_GCE_NETWORK and KUBE_GCE_INSTANCE_PREFIX and it worked. Thanks!

**Comment by liggitt** [comment]
Great. That would be the recommendation for using this script in your environment. 

/close
