### ISSUE TITLE
cpu manager should add a flag to disable cpu exclusive feature

### ISSUE THREAD

**Issue by tangle329** [kubernetes/kubernetes#72313]
**What would you like to be added**:
Add a flag to kubelet to enable/disable cpu exclusive feature.
**Why is this needed**:
We want bond  pod1  to some core, for example core 1,2,3,4. and set its cpushare to 1024.  The same time  we also want pod2 be  configured with cpushare=1.   This way if cpu exclusive is disabled, pod2 can use some cpu usage of pod1 when pod1 is in idle status, and pod1 can get back almost all cpu usage when it's busy。 As a result,  we can improve our cpu utilizition

/kind feature

@kubernetes/sig-node-feature-requests

**Comment by Shnatsel** [comment]
Reiterating mention to trigger notification: @kubernetes/sig-node-feature-requests

**Comment by ConnorDoyle** [comment]
@tangle329 just to clarify, are you referring to use of the `cpuset.cpu_exclusive` flag? If so, the CPU manager does not currently use this. Exclusivity is achieved by gradually migrating containers off of "exclusive" allocations.

The rest of what you described is pretty similar to the behavior given a burstable pod and a best-effort pod on the same node. The BE pod gets minimal shares (2) and the Bu pod gets shares according to the CPU resource request. What doesn't happen currently is to constrain the Bu pod to a subset of the available cores. May I ask more about the use case? There are lots of important and real scenarios that require more flexible behavior than the static policy can provide right now. The challenge has been to corral all of them and come out with a clear picture of what an alternative policy should do. There have been proposals ranging from 1) a "sufficiently smart" built-in dynamic policy 2) exposing a declarative configuration to set up "pools" which may or may not overlap, and which may or may not be overcommitted 3) creating a full new plugin interface similar to device plugins or the CRI.
