### ISSUE TITLE
Better way to share common utilities between PV controller and Volume Binder

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#72329]
**What would you like to be added**:

**Why is this needed**:

Address this:
https://github.com/kubernetes/kubernetes/blob/197fc67693c2391dcbc652fc185ba85b5ef82a8e/pkg/controller/volume/persistentvolume/scheduler_binder.go#L121-L125

/kind feature

## Proposal

- [x] ctrl.kubeClient -> binder.kubeClient
- [x] ctrl.classLister -> binder.classLister
- [x] ctrl.isDelayBindingMode(claim) -> persistentvolume.IsDelayBindingMode(claim, classLister)
- [x] ctrl.getBindVolumeToClaim(pv, pvc) -> persistentvolume.GetBindVolumeToClaim(pv, pvc)
  - [x] persistentvolume.isVolumeBoundToClaim -> persistentvolume.IsVolumeBoundToClaim
- [x] ctrl.updateBindVolumeToClaim(pv, pvc, false) is removed

**Comment by cofyc** [comment]
/sig storage
cc @msau42
I'll take a look at this.

**Comment by msau42** [comment]
This may also be slightly related: https://github.com/kubernetes/kubernetes/issues/56098
