### ISSUE TITLE
Add PodTemplate hash/uuid into Pod

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#72322]
**What would you like to be added**:

Most of Pods are created by controller/operator who knows the `PodTemplate`;  if this info is included in Pod, scheduler can do the scheduling cache based on it.

**Why is this needed**:

It'll save lots of scheduling effort, e.g. if failed to schedule a Pod, the other pods that created from the same pod template can not be scheduled :)

/kind feature

**Comment by liggitt** [comment]
I'm confused what this is proposing. Pods created that way already have an ownerReference pointing to the parent object, and the submitted pod.spec already contains the info from the pod. What specific information are you wanting to make available to the scheduler that is not currently available?

**Comment by k82cn** [comment]
BTW, it should be an optimization instead of restriction :)

**Comment by liggitt** [comment]
Hashes of podspecs have been extremely problematic across releases over the years. I'm not eager to add more of them. 

Only one ownerReference can have controller=true, if I recall correctly.

**Comment by k82cn** [comment]
wow, happy new year !!

It's used by scheduler's equaliance cache as optimization: if two pod has same hash/uuid of pod spec, they can share predicates failure result. 

> Only one ownerReference can have controller=true

Yes; take TFJob as demonstration, both ps pod and worker pod has only one controlled ownerReference , and their the ownerReference are the same one; but scheduler can not share predicates failure result, as their pod template maybe different.

**Comment by mlmhl** [comment]
+1. There are quite a few customized controllers use different templates to create pod.

> Hashes of podspecs have been extremely problematic across releases over the years.

IIUC, the main problem of pod spec hash is that it can't keep the same if we add new fields. However, I think this problem has little impact on the scheduler equaliance cache optimization: If the hash value changes, it will only cause a cache miss, and what scheduler needs do is to recalculate the predicate result and then put it into the cache with the new hash key.

BTW, do we have any in progress work to find a more appropriate way to compare pod specs?

**Comment by smarterclayton** [comment]
I’m not in favor of including pod template onto pod - that massive duplication that is completely unnecessary except for one optimization in scheduler.

The scheduler is already the arbiter of fit - I find it hard to believe you can’t make equivalence work without pod spec.  Can you describe why it’s so hard or what info is absent?

**Comment by k82cn** [comment]
> that massive duplication

oh ... update title to `Add PodTemplate hash/uuid into Pod`; not the whole `PodTemplate` :)

> The scheduler is already the arbiter of fit - I find it hard to believe you can’t make equivalence work without pod spec. Can you describe why it’s so hard or what info is absent?

To make equivalence work, we need to do deep equal of pod sepc which is so heavy; if there's a uuid/hash of pod template in pod's annotation, scheduler can use it instead of deep equal. Maybe something (e.g. annotation) looks like `k8s.io/pod-template-hash = group/kind/api_version/ns/name/res_version`
