### ISSUE TITLE
Use fake client real watch mechanism in PV controller tests

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#72327]
**What would you like to be added**:

**Why is this needed**:

Fake clients support pushing events now.

With this, testing code will more like really code and we don't need mock informers behavior anymore.

xref: https://github.com/kubernetes/kubernetes/pull/57504
xref: https://github.com/kubernetes/kubernetes/issues/54075

~~I'm going to support concurrent control and incremental resource version in client-go fake client.~~
~~xref: https://github.com/kubernetes/kubernetes/pull/72353~~ (rejected, see comments in PR)

/kind feature

**Comment by cofyc** [comment]
/kind cleanup
I think we can move on to using real watch mechanism now. I'm going to use it in #72045.

**Comment by cofyc** [comment]
cc @msau42 @jsafrane

**Comment by fatsheep9146** [comment]
Since I just fixed the local storage provisioner's test case with fake.ClientSet, I think I can help with this, if none of you have spare time to do this. May I?
/cc @cofyc @msau42 @jsafrane

**Comment by cofyc** [comment]
Thanks! But my proposal to support concurrent control and incremental resource version in client-go general ObjectTracker is rejected (xref: https://github.com/kubernetes/kubernetes/pull/72353). We still need `volumeReactor` for our testing.

But one thing we can do is to use real watch mechanism instead of interacting with internal structs (e.g. cache). But I suggest we do it case by case.

/close
