### ISSUE TITLE
Change existing metrics to conform metrics guidelines

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#72333]
**What would you like to be added**:

This issue is used to track the progress of changing existing metrics to conform metrics guidelines:

- [x] docker metrics (https://github.com/kubernetes/kubernetes/pull/72323)
- [x] scheduler metrics (https://github.com/kubernetes/kubernetes/pull/72332)
- [x] proxy metrics (https://github.com/kubernetes/kubernetes/pull/72334)
- [x] workqueue metrics (https://github.com/kubernetes/kubernetes/pull/71300)
- [x] mark deprecated in related workqueue metrics (https://github.com/kubernetes/kubernetes/pull/72679)
- [x] kubelet metrics (https://github.com/kubernetes/kubernetes/pull/72470)
- [x]  apiserver metrics (https://github.com/kubernetes/kubernetes/pull/72336)
- [x] fix admission metrics in true units (https://github.com/kubernetes/kubernetes/pull/72343)
- [x] Rename cadvisor metric labels to match instrumentation guidelines (https://github.com/kubernetes/kubernetes/pull/69099)

**Why is this needed**:

/kind feature
/sig instrumentation

**Comment by brancz** [comment]
Could you add https://github.com/kubernetes/kubernetes/pull/69099 to this tracking?

Other than that I believe this covers it.

**Comment by danielqsj** [comment]
@brancz sure, added.
