### ISSUE TITLE
CSI - Delete volumeattachment and volume failed when the associated node is not found.

### ISSUE THREAD

**Issue by jackhaibo** [kubernetes/kubernetes#72335]
**What happened**:
I mapped a volume to the node name is `ubuntu-node5` via kubernetes-csi plugin. Later I added this node to other clusters and forgot to unmap this volume from `ubuntu-node5`, causing the volumeattachment and volume cannot be deleted, even adding  `--grace-period=0 --force` parameters in the delete command.

Using the describe command to show volumeattachment details are as follows:
```
root@ubuntu-master:/home# kubectl describe volumeattachment csi-ec16a73670ecf3d64e137653e852e34516ed89768d8e791e634fbe4d57497b5e

Name:         csi-ec16a73670ecf3d64e137653e852e34516ed89768d8e791e634fbe4d57497b5e
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1beta1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:             2018-12-22T12:31:24Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2018-12-26T07:05:24Z
  Finalizers:
    external-attacher/csi-djplugin
  Resource Version:  727742
  Self Link:         /apis/storage.k8s.io/v1beta1/volumeattachments/csi-ec16a73670ecf3d64e137653e852e34516ed89768d8e791e634fbe4d57497b5e
  UID:               7ebd70df-05e5-11e9-8869-9017acae5907
Spec:
  Attacher:   csi-djplugin
  Node Name:  ubuntu-node5
  Source:
    Persistent Volume Name:  pvc-38df24f0-05e3-11e9-8869-9017acae5907
Status:
  Attach Error:
    Message:  PersistentVolume "pvc-38df24f0-05e3-11e9-8869-9017acae5907" is marked for deletion
    Time:     2018-12-24T15:53:09Z
  Attached:   false
  Detach Error:
    Message:  node "ubuntu-node5" not found
    Time:     2018-12-26T07:06:02Z
Events:       <none>
```
Using the get command to show node details are as follows:
```
root@ubuntu-master:/home# kubectl get node
NAME            STATUS    ROLES     AGE       VERSION
ubuntu-master   Ready     master    4d        v1.10.3
ubuntu-node1    Ready     <none>    4d        v1.10.3
ubuntu-node2    Ready     <none>    4d        v1.10.3
```
**What you expected to happen**:
I hope that in this case, the volumeattachment can be forcibly deleted, so that it does not affect other tasks of csi plugin, Or determine whether there is a volumeattachment associated with the node before deleting the node.

**How to reproduce it (as minimally and precisely as possible)**:
1. Map a volume to a node.
2. Delete this node.
3. Delete the volume and associated volumeattachment

**Anything else we need to know?**:
When I create a new node and name it `ubuntu-node5`, add it to the kubernetes cluster, this volumeattachment and volume are all automatically deleted.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.3
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux ubuntu-master 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: csi plugin [https://github.com/opensds/nbp/tree/master/csi]
- Others:

/kind bug
/sig node 
/sig volumeattachment

**Comment by brissenden** [comment]
I have the same issue. The only difference is that the node crashed and left all the volume attachment that can't be removed. As author already mentioned, it affects also `csi-cinder-controllerplugin` plugin.

**Comment by b0b0haha** [comment]
Is this issue has been solved?
