### ISSUE TITLE
 Investigate callers of IsLikelyNotMountPoint

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#72347]
**What happened**:
IsLikelyNotMountPoint() doesn't detect bind mounts of directories on the same fs as /var/lib/kubelet.  Local PVs that are directories on the rootfs are most problematic.  Similar CSI plugins that expose rootfs directories are also problematic. 

[This commit](https://github.com/msau42/kubernetes/commit/559fdd5229eb550054df57d1854d58dc4cd7c506) identifies some functions that are technically incorrect because they use IsLikelyNotMountPoint() instead of IsNotMountPoint().  However, IsNotMountPoint() is expensive since it has to scan all mount points on the host, so instead of changing the callers to use IsNotMountPoint(), we found other ways to fix the problem.

We should investigate all other uses of IsLikelyNotMountPoint() to see if these cases are handled.

@kubernetes/sig-storage-bugs 

/kind bug

**Comment by msau42** [comment]
Here's another place where IsLikelyNotMountPoint() needs to change: https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_mounter.go#L387

**Comment by gnufied** [comment]
hmm, it has been documented that `IsLikelyNotMountPoint` does not ALWAYS return correct information, esp. about bind mounts - https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L241

I guess the intent was to use it for volume types that expose a new devices and not to use it for detecting mount points which are basically bind mounts of local directories onto rootfs itself.   For local storage it is a problem if admin ended up adding rootfs device to local-storage pool. 

For many use cases it is possibly to flip the switch via https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L131

**Comment by gnufied** [comment]
If we do want to check mount table each time we want to really verify if a directory is a mount point then we should investigate poll based interface @cofyc implemented awhile back for polling the mount table. That may be cheaper than querying mount table all the time.

**Comment by msau42** [comment]
Yes, we should investigate all calls to IsLikelyNotMountPoint() that's in the general volume manager code (not plugin-specific), as well as CSI logic.  We have to evaluate the performance implications since IsNotMountPoint is more expensive.

The other thing I've been thinking, is to evaluate in each case if we even need to check if something is a mount point?  If you try to `os.Remove` a mount point or directory with content, it will fail.

**Comment by msau42** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/72257

**Comment by cofyc** [comment]
List of calls of `IsLikelyNotMountPoint` outside of `pkg/volumes`:

```
$ grep '\.IsLikelyNotMountPoint(' pkg/ -R 2>/dev/null | grep -v '^pkg\/volume'
pkg/util/mount/mount_windows_test.go:		result, err := mounter.IsLikelyNotMountPoint(filePath)
pkg/util/mount/mount.go:	notMnt, notMntErr := mounter.IsLikelyNotMountPoint(file)
pkg/util/mount/exec_mount.go:	return m.wrappedMounter.IsLikelyNotMountPoint(file)
pkg/util/mount/safe_format_and_mount_test.go:			isNotMountPoint, err := fakeMounter.IsLikelyNotMountPoint(dest)
pkg/util/mount/mount_helper.go:			notMnt, err = mounter.IsLikelyNotMountPoint(mountPath)
pkg/util/mount/mount_helper.go:	notMnt, mntErr := mounter.IsLikelyNotMountPoint(mountPath)
pkg/util/removeall/removeall.go:	isNotMount, err := mounter.IsLikelyNotMountPoint(path)
pkg/kubelet/kubelet_getters.go:		isNotMount, err := kl.mounter.IsLikelyNotMountPoint(volumePath)
```

- [x] pkg/util/removeall/removeall.go, RemoveAllOneFilesystem
  - safe, although maybe unnecessary
-  [ ] pkg/kubelet/kubelet_getters.go, Kubelet.getMountedVolumePathListFromDisk
  - my proposal see https://github.com/kubernetes/kubernetes/issues/72346#issuecomment-466347067
- [ ] pkg/util/mount/mount_helper.go, doCleanupMountPoint
  - TODO (will update)
- [x] pkg/util/mount/safe_format_and_mount_test.go
  - safe, test files
- [x] pkg/util/mount/exec_mount.go
  - safe
- [x] pkg/util/mount/mount.go, isNotMountPoint
  - safe, Mounter.IsNotMountPoint implementation
- [x] pkg/util/mount/mount_windows_test.go
  - safe, test files

List of calls of `IsLikelyNotMountPoint` under `pkg/volume/csi`:

```
$ grep '\.IsLikelyNotMountPoint(' pkg/volume/csi/ -R 2>/dev/null 
pkg/volume/csi/csi_mounter.go:	notMnt, err := mounter.IsLikelyNotMountPoint(dir)
```

- [ ] pkg/volume/csi/csi_mounter.go, isDirMounted
  - TODO (guess we should use IsNotMountPoint for safety because `dir` passed to SetUpAt may be a directory on host, e.g. `csi-hostpath`)

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by msau42** [comment]
Thanks for the thorough investigation @cofyc!

For Local PV, only https://github.com/kubernetes/kubernetes/issues/72346#issuecomment-466347067 is relevant, and it's for extreme corner cases. Given that, I think it can be addressed after GA.

All the issues pointed out are also issues for CSI volumes in general that utilize the local filesystem instead of a separate device. We should continue to investigate fixes for CSI, although it is not urgent for 1.14 either. This may become more important for inline ephemeral volumes.

Based on that, I'm going to remove the 1.14 milestone from this issue.
/milestone clear

**Comment by jsafrane** [comment]
@cofyc are you still looking at this issue? The code may be quite different now.

**Comment by cofyc** [comment]
> @cofyc are you still looking at this issue? The code may be quite different now.

sorry, I'm not working on this anymore. it's very old issue, we need rethink it based on the new code.

/unassign

**Comment by xing-yang** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.27.0-alpha.2/staging/src/k8s.io/mount-utils/mount_linux.go#L409

**Comment by xing-yang** [comment]
Close it for now.  Please re-open if this is still an issue.
