### ISSUE TITLE
Why cache and queue must be internal in Kubernetes scheduler

### ISSUE THREAD

**Issue by xiaoxubeii** [kubernetes/kubernetes#72355]
/triage support

I am now working on an open source project related to Kubernetes scheduler. It is actually a Kubernetes schedule simulator and helps to tune scheduling performance, validate schedule algorithms and so on. But I found schedule cache and queue is in kubernetes/pkg/scheduler/internal, and I had to copy the codes instead of referencing directly because my simulator is out-of-tree. My question is why schedule cache and queue must be internal and is there a need to implement pluggable out-of-tree schedulers in the future?

Any help would be very important. Thanks.

**Comment by Huang-Wei** [comment]
@xiaoxubeii it's due to recent code refactoring. The motivation was that we think those implementations (queue/cache) are only needed by kube scheduler.

cc/ @misterikkit

**Comment by wgliang** [comment]
This is a good question, I remember that our expectation is that we can share the cache to multiple schedulers instead of requiring multiple copies of the cache. @bsalamat

**Comment by xiaoxubeii** [comment]
We can share the cache to achieve shared state although there are some problems such as consistency, head-of-blocking and so on.

**Comment by xiaoxubeii** [comment]
OK, I am glad to do that.

**Comment by misterikkit** [comment]
> is there a need to implement pluggable out-of-tree schedulers in the future?

Yes, if I understand you correctly. The scheduler framework effort should meet these needs. https://github.com/kubernetes/enhancements/issues/624


> why schedule cache and queue must be internal

These components were moved to `internal` specifically because we didn't intend them to be consumed as APIs, and we don't want the cost of maintaining them like public APIs. 


> there are always some codes or interfaces referencing either internalqueue.SchedulingQueue or schedulerinternalcache.Cache

These are valid points. we *do* intend for constructing a scheduler to remain as a golang API, so requiring internal types is not suitable. Are you able to use `scheduler.New` instead of `core.NewGenericScheduler`? The `core` package is another component that is not intended to be directly imported by outside packages.

On another note, I think the use case of having a simulator is a great one. I would like us to maintain useful golang APIs for projects such as this. If you feel that you need to interact directly with `cache`, `queue`, or `core`, then I would like to discuss those requirements and see if we can move you onto better APIs.

**Comment by xiaoxubeii** [comment]
> is there a need to implement pluggable out-of-tree schedulers in the future?
> 
> Yes, if I understand you correctly. The scheduler framework effort should meet these needs. kubernetes/enhancements#624

Yes, the scheduler framework would achieve this requirement.

> Are you able to use scheduler.New instead of core.NewGenericScheduler? The core package is another component that is not intended to be directly imported by outside packages.

OK, I will try to construct the scheduler on a higher API and prevent from referencing internal package.
But actually accessing directly schedule cache and queue would be helpful for me to tune and test Kubernetes schedule.

**Comment by misterikkit** [comment]
> But actually accessing directly schedule cache and queue would be helpful for me to tune and test Kubernetes schedule.

I'd like to understand more about why you want/need direct access to these components. You mention that you are running simulations and tuning scheduler performance. Does that mean you are scheduling fake pods and measuring the timing? What parameters are you changing for performance? Is your system running offline, or modifying live clusters?  :thinking:

**Comment by xiaoxubeii** [comment]
> Does that mean you are scheduling fake pods and measuring the timing?

Almost. My schedule simulator can use both fake pods and schedule snapshot to simulate the actual Kubernetes scheduling. And I need to collect the metrics and want to watch the whole process. I don't want it is a black-box for me.

> What parameters are you changing for performance? 

I am trying to find the potential performance issues of Kubernetes default scheduler. And I also implemented some schedulers that meet our requirements. The above situations are both my needs.

> Is your system running offline, or modifying live clusters? 

My simulator is running offline using fake pods, nodes or schedule snapshot.

**Comment by resouer** [comment]
> And I need to collect the metrics and want to watch the whole process. I don't want it is a black-box for me

For all these requirements it's totally fine to fork & hack kube-scheduler in your simulation env, no?

For cluster capacity planning only, it's should be not hard to build from external: https://github.com/kubernetes-incubator/cluster-capacity (seems deprecated but still a concrete example)
