### ISSUE TITLE
why not create cgroup dir(/sys/fs/cgroup/cpuset/system.slice.. etc)  in kubelet starts

### ISSUE THREAD

**Issue by ztewyk** [kubernetes/kubernetes#72359]
in pkg/kubelet/cm/node_container_manager.go

in func enforceExistingCgroup,it just check wheteher  kubelet group dir exist. why not create kubelet cgroup dir if  not exist in func enforceExistingCgroup?

**Comment by 2rs2ts** [comment]
Did you find an answer to this?
