### ISSUE TITLE
Follow up #70277, the close of the "done" channel should terminate WaitFor

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#72357]
Users of the `WaitFor` function would expect the close of the "done" channel should terminate the [WaitFor](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L385). We should change the function to align to users' expectation.

We should document what the `done` channel does.

This is a behavior change, to be cautious, we should add a release note claiming breaking change.

/kind bug

**Comment by caesarxuchao** [comment]
/sig api-machinery

cc @kdada. Feel free to assign to yourself if you have time. Otherwise I'll attempt a fix tomorrow ;)

**Comment by kdada** [comment]
@caesarxuchao I'll fix it. 

/assign @kdada
