### ISSUE TITLE
ci-benchmark-scheduler-master not working correctly

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#72363]
**Which jobs are failing**:
ci-benchmark-scheduler-master

**Which test(s) are failing**:

**Since when has it been failing**:
12/19/2018 ~19:49
**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler

**Reason for failure**:
"go-junit-report not found"

**Anything else we need to know**:
IIUC the problem is not with actual test case, but results post processing. The .stdout file should be converted using go-junit-report, which fails.

/kind failing-test

**Comment by krzysied** [comment]
The last good run was [7772](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-master/7772/build-log.txt). [7773](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-master/7773/build-log.txt) is bad.

Kubernetes changes https://github.com/kubernetes/kubernetes/compare/7ce7a80cd...28b965a8c between those two runs.

**Comment by krzysied** [comment]
@cblecker  I saw that there were some changes made by you during that time. Can you verify whether they can be related to this issue, please?

I will try to check if there was no changes on test-infra side.

**Comment by krzysied** [comment]
Changes in test-infra: https://github.com/kubernetes/test-infra/compare/899fabec7...d758ce889 . I don't see there anything related to ci-benchmark-scheduler-master.

**Comment by Shnatsel** [comment]
@kubernetes/sig-scalability-test-failures

**Comment by cblecker** [comment]
Had a look at this. Job seems to be green, but isn't exporting junit results. Thing is, I don't know if it ever has. If you look at the [artifacts for 7772](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-benchmark-scheduler-master/7772/) (the mentioned last green run), there isn't any junit results there either.

cc @wojtek-t @kubernetes/sig-testing

**Comment by krzysied** [comment]
> If you look at the artifacts for 7772 (the mentioned last green run), there isn't any junit results there either

Good observation. I though the results where generated to `.stdout` file, parsed it and then removed it. From 7773 there is new file https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-master/7773/artifacts/junit_5a6df720540c20d95d530d3fd6885511223d5d20_20181220-035149.stdout. Previously its content could be found in build-log.txt.

Maybe previously [this line](https://github.com/kubernetes/kubernetes/blob/2a1560061e743a09731a485e632810393fda8628/hack/make-rules/test.sh#L258) cause function to return. I this were true, I assume [this line](https://github.com/kubernetes/kubernetes/blob/2a1560061e743a09731a485e632810393fda8628/hack/make-rules/test.sh#L207) also behaved differently. For example due to `KUBE_JUNIT_REPORT_DIR` having different value?

**Comment by krzysied** [comment]
Currently scheduler benchmark is constantly failing since run 8021 (01/10/2019). There is a `panic: runtime error: invalid memory address or nil pointer dereference` log in `.out` file.

The changes between first broken and last "good" test: https://github.com/kubernetes/kubernetes/compare/bd5a4ccfc3d3e0cfa1a9099180526c2237aabec8...2c8b571d573d434687316c606fb5e20e63008345
Example of the log: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-master/8021/artifacts/junit_5a6df720540c20d95d530d3fd6885511223d5d20_20190109-235832.stdout

The [ci job](https://github.com/kubernetes/test-infra/blob/ad72cd23fbbba55d9de9b232f6fdc3ab89c672ce/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L554) we run is using k8s.io/kubernetes//test/integration/scheduler_perf.

cc @bsalamat @kubernetes/sig-scheduling-test-failures

**Comment by k82cn** [comment]
@wgliang , would you help to check that?

**Comment by wgliang** [comment]
@krzysied This issue had beed fixed. U can checkout it #72967

**Comment by wgliang** [comment]
This issue has been fixed. Any questions, please feel free to reopen it. I will close it.
/close

**Comment by krzysied** [comment]
@wgliang  OK. Thanks!
