### ISSUE TITLE
Starting K8s master takes too long

### ISSUE THREAD

**Issue by quangtamle** [kubernetes/kubernetes#72374]
Hello everyone,

I start the k8s master but it takes too much time. 
How can I fix this ??? because I saw no error.
![too long](https://user-images.githubusercontent.com/43220759/50488562-66f4a700-0a03-11e9-9384-301f7e6b35ca.png)

Thank you in advances

/sig node
/sig cluster ops

**Comment by neolit123** [comment]
you might have better success asking on stackoverflow.

**Comment by neolit123** [comment]
please try our support channels instead:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close
