### ISSUE TITLE
Cleanup mounter IsNotMountPoint

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#72387]
**What happened**:
There's [mount.Interface.IsNotMountPoint](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/util/mount/mount.go#L60), and [mount.IsNotMountPoint](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/util/mount/mount.go#L253).

The former is used by local and nfs volume plugins, while the latter is used by [UnmountMountPoint](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/util/util.go#L140:6), which is also used by local and nfs volume plugins.

**What you expected to happen**:
Can we consolidate these? This is really confusing and could easily be the source of bugs.

/kind cleanup

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
cc @cofyc

**Comment by cofyc** [comment]
/assign
I'd like to clean up code.
