### ISSUE TITLE
Service NodePort not working

### ISSUE THREAD

**Issue by fyuan1316** [kubernetes/kubernetes#72392]
**What happened**:
![image](https://user-images.githubusercontent.com/42265657/50506539-66681900-0ab4-11e9-9746-5e71c05bc4ad.png)

the port 8000 of sample-service(10.107.175.103)  seems not working.
i checked endpoint "endpoints/xxxx-sample-service " is ok!
then access sample-service by nodeport(32322) is ok too.
![image](https://user-images.githubusercontent.com/42265657/50507181-5271e680-0ab7-11e9-8263-634bfd897503.png)

After restarting the kube-proxy pods, I tested it again by following the above steps, but the result is the same.

**What you expected to happen**:
i hope the nodeport can be accessed normally.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 16.04.1 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux master 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by fntlnz** [comment]
@fyuan1316  Type `NodePort` is meant to be used to expose expose your port in the underlying network of the host node so your test with netcat should work for `10.110.205.95` that is a `ClusterIP` while you should use the Node's ip address for the one with `NodePort`


Read more at: https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

**Comment by fyuan1316** [comment]
@fntlnz thanks for your quick reply.
In another namespace of my cluster, I tested it for another service. There are some differences in the results, which makes me confused.
![image](https://user-images.githubusercontent.com/42265657/50539254-52a5db00-0bb8-11e9-808a-4e85e19d7fc7.png)
![image](https://user-images.githubusercontent.com/42265657/50539269-7ec15c00-0bb8-11e9-844b-3905db82e452.png)

| tests-group | test-command in pod | port | result |desc|
| --- | --- | --- | --- | --- |
| test1-1 | nc -vz 10.107.175.103 8000 | service port| hang | pod's namespace== svc's namespace |
| test1-2 | nc -vz 10.107.175.103 32322 | node port| ok | pod's namespace== svc's namespace |
| test2-1 | nc -vz 10.97.235.189 8877 | service port| ok | pod's namespace!= svc's namespace |
| test2-2 | nc -vz 10.97.235.189 31646 | node port| ok | pod's namespace!= svc's namespace  |

I have previously understood that in the pod i could access the service (nodeport mode) in several ways:
1. curl node-ip port 
2. curl service-ip port 
3. curl service-ip nodeport
if there is a misunderstanding, please correct me thank you.

**Comment by fntlnz** [comment]
@fyuan1316 The way it is designed is:

- When you expose NodePort you are binding your port to the node port, so you access the service using the port on the node ip and you cannot access the service using the service's ip
- When you expose using ClusterIP you can access the service using the service's ip.

If you want to achieve both (node port and cluster ip)  what you do is that you create two services pointing to the same resources.

**Comment by phanisowjanyavutukuri** [comment]
I have deployed a sample nginx application and created the kubernetes service with nodeport then with the private ip of the machine am able to curl but am unable to curl with the public ip
Could any one please help me in this
Thanks in advance

**Comment by vllry** [comment]
@phanisowjanyavutukuri would you mind filing a separate issue, if you still have a problem? That sounds like it may be an unrelated firewall issue. Kubernetes does not normally distinguish private vs public IP interfaces.

/close

**Comment by muditmn** [comment]
i got the same issue.....if you want to reslove download the client bundle from Docker EE UCP by going into my profile section. Then shift this bundle on your UCP linux node then source the env.sh file.
Command:- source env.sh script
