### ISSUE TITLE
kubernetes reliability/reactivity on node failure not work properly

### ISSUE THREAD

**Issue by Unrealnew** [kubernetes/kubernetes#72395]
When a node fails by default the **normal** behavior looks like:

- Kubelet updates it status to apiserver periodically, as specified by **--node-status-update-frequency**. The default value is 10s.
- Kubernetes controller manager checks the statuses of Kubelets every **–-node-monitor-period**. The default value is 5s.
- In case the status is updated within **--node-monitor-grace-period** of time, Kubernetes controller manager considers healthy status of Kubelet. The default value is 40s.
- After --node-monitor-grace-period it will consider node unhealthy. It will remove its pods based on **--pod-eviction-timeout** The default value is 5m0s

I have tried with **-–node-status-update-frequency (kubelet daemon as KUBELET_EXTRA_ARGS)** set to 4s (10s is default). **--node-monitor-period to 2s** (5s is default). **--node-monitor-grace-period to 20s** (40s is default). **--pod-eviction-timeout set to 30s** (5m is default).  The last three configurations have been made on the kube-controller-manager (/etc/kubernetes/manifests/kube-controller-manager.yaml)

**What happened**:
Pods will be evicted in 5m as if no configuration had been provided.

**What you expected to happen**:
In such scenario, pods will be evicted in about 50s because the node will be considered as down after 20s, and --pod-eviction-timeout occurs after 30s more.

**How to reproduce it (as minimally and precisely as possible)**:
Create a right configuration, for example:
-–node-status-update-frequency to 4s (kubelet)
--node-monitor-period to 2s 
--node-monitor-grace-period to 20s
--pod-eviction-timeout set to 30s 

Run pod (on worker node) than brutally shutdown the node with the pod running.
Wait, and after about 5min (no 50s) the pod is restarted on another worker.

**Anything else we need to know?**:
Exactly the same configuration, stack software and hw, test procedure, but with k8s v1.12.4 works very well...!! Pods will be evicted in about 50s.

With both k8s v1.12.4 and v1.13.1 the controller-manager containers have been checked (with docker command) and have always shown the correct configuration provided:
--node-monitor-period to 2s
--node-monitor-grace-period to 20s
--pod-eviction-timeout set to 30s 
 
**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.1
- Cloud provider or hardware configuration: On-premises installation
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`): Linux 3.10.0-957.1.3.el7.x86_64
- Install tools: None
- Others: Multi master (3 node) configuration with internal etcd and 3 worker node and an external load balancer. 

/kind bug

**Comment by Shnatsel** [comment]
@kubernetes/sig-node-bugs

**Comment by wenxuwan** [comment]
I have the same problem with v1.13.1.

**Comment by wenxuwan** [comment]
If there have another thread to follow this problem ???

**Comment by danielloczi** [comment]
I have the same problem with v1.13.2.

**Comment by yld2019** [comment]
I have the same problem with v1.13.3.

```
NAME    STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
node-0   Ready    master   8d    v1.13.3   192.168.0.17   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://1.13.1
node-1   Ready    <none>   8d    v1.13.3   192.168.0.5    <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://1.13.1
```

**Comment by danielloczi** [comment]
Is there any news regarding this bug? 
In some time critical setup in production it causes serious issues, and as far as I know there is still no solution or workaround. 
Any idea how to make pods re-started as fast as possible after node failure?

I already configured liveness probes, but unfortunately it doesn't help as it seems to me that the failed kube-system pods checks the result of the liveness probe instead of the healthy ones. That is another thing I don't understand why healthy kube-system doesn't see a failed livenessprobe and start new pod instances?

**Comment by Unrealnew** [comment]
I "simply" believe that in the transition between 1.12 and 1.13 they introduced a bug in dealing with the monitor-period ooptions. It would be useful to know a roadmap for solving this important problem!

UP!

**Comment by yld2019** [comment]
When node is considered failed, the related pod is still considered healthy. 
**What happened**:
`kubectl get node
NAME    STATUS     ROLES    AGE   VERSION
yld-0   Ready      master   17d   v1.13.3
yld-1   NotReady   <none>   17d   v1.13.3
kubectl get po -w
NAME                    READY   STATUS    RESTARTS   AGE
curl-649649b6c7-gcc4k   1/1     Running   0          10m
`
**What you expected to happen**:
`NAME                    READY   STATUS    RESTARTS   AGE
curl-649649b6c7-gcc4k   0/1     Running   0          10m`

**Comment by alexling92** [comment]
I have the same problem too. The --pod-eviction-timeout function does not seem to be working at all. Is this a bug?

**Comment by danielloczi** [comment]
FYI: the bug not related to multi-master environment, I able to reproduce it on one master, two worker nodes setup also. See: #74651

**Comment by Unrealnew** [comment]
The pod-eviction-timeout took effects after set the TaintBasedEvictions to false (- --feature-gates=TaintBasedEvictions=false on kubectl conf) because de fault value now is true since 1.13.
Here we can find all new features and default value linked to a specific version. 

- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#
 
So i think that the new feature TaintBasedEvictions has broken the legacy functionality of pod eviction.
But I still have a problem with TaintBasedEvictions. Infact my new kubelet extra args configuration is:

- --feature gates="TaintBasedEvictions=true,TaintNodesByCondition=true,NodeLease=true"

I have this Deployment:

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30

All seams to work well but I realized that the state of my nodes is constantly oscillating.
Infact on all node (3 master 2 worker) in kubectl logs (journalctl -u kubelet -f) I have this error:

mar 01 12:01:36 master-servers-2 kubelet[25763]: E0301 12:01:36.252570   25763 controller.go:115] failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "master-servers-2" is forbidden: **User "system:node:master-servers-2" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": disabled by feature gate NodeLease**

Permission issue?!

**Comment by w564791** [comment]
I have the same problem with v1.13.4

**Comment by w564791** [comment]
I have the same problem with v1.13.4,The --pod-eviction-timeout function does not seem to be working at all  ,I set the following parameter `--node-monitor-period=1s  --node-monitor-grace-period=10s  --pod-eviction-timeout=40s` , But the pod is always rescheduled after 5 minutes of the node down

**Comment by white-cloud** [comment]
@Unrealnew  hello , 
may i know please how did you set up -–node-status-update-frequency to 4s (kubelet) in kubelet , because i can find no config file for the kubelet ??

Thank you .

**Comment by venkatalolla** [comment]
@Unrealnew Hi,

I have the same problem with v1.14.0, the worker nodes are unstable they keep switching back and forth between `Ready` and `NotReady` state and the see the following error 
``failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "worker-1" is forbidden: User "system:node:worker-1" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node``

Also, I do have a kube-node-lease namespace, but it has no resources.

I tried creating a clusterrolebinding for the User "system:node:worker-1" in "coordination.k8s.io "API groups. Nothing worked :( 

Finally,
I removed the `TaintNodesByCondition` and `NodeRestriction` arguments from `--enable-admission-plugins=` in the **/etc/systemd/system/kube-apiserver.service** on all **3 master nodes** and restared the kube-apiserver and kube-controller-manager and I never saw the above error on the worker nodes and on master nodes `kubectl get nodes`  shows that worker nodes are always in `Ready`.

Following is the  **/etc/systemd/system/kube-apiserver.service** that I used in my cluster,
```
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-apiserver \
  --advertise-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/audit.log \
  --authorization-mode=RBAC,AlwaysAllow \
  --bind-address=0.0.0.0 \
  --client-ca-file=/var/lib/kubernetes/ca.pem \
  --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,Priority,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota \
  --enable-swagger-ui=true \
  --etcd-cafile=/var/lib/kubernetes/ca.pem \
  --etcd-certfile=/var/lib/kubernetes/kubernetes.pem \
  --etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem \
  --etcd-servers={% for host in groups['master'] -%}https://{{ hostvars[host].ansible_eth0.ipv4.address }}:2379{%- if not loop.last %},{%- endif %}{%- endfor %} \
  --event-ttl=1h \
  --experimental-encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml \
  --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem \
  --kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem \
  --kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem \
  --kubelet-https=true \
  --runtime-config=api/all \
  --service-account-key-file=/var/lib/kubernetes/service-account.pem \
  --service-cluster-ip-range={{ service_cluster_ip_range }} \
  --service-node-port-range=30000-32767 \
  --tls-cert-file=/var/lib/kubernetes/kubernetes.pem \
  --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem \
  --v=5
Restart=on-failure
RestartSec=5
Type=notify

[Install]
WantedBy=multi-user.target
```

Is there any permanent fix for by enabling the TaintNodesByCondition and NodeRestriction?

Any help appreciated! Thank you.

**Comment by ranjujohn** [comment]
Regarding the pod-eviction-timeout issue, I was also facing the same issue with k8s 1.15.0 and then read about the change as mentioned below.

"In version 1.13, the TaintBasedEvictions feature is promoted to beta and enabled by default, hence the taints are automatically added by the NodeController (or kubelet) and the normal logic for evicting pods from nodes based on the Ready NodeCondition is disabled"

I got it working by setting the flags as below(https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) 

--default-not-ready-toleration-seconds=30
--default-unreachable-toleration-seconds=30

**Comment by puthi** [comment]
@venkatalolla,
I'm running into the same problem here, running kubernetes 1.14.3
I think your configuration works because you set --authorization-mode=RBAC,**AlwaysAllow**, the AlwaysAllow, allow everything as long as the authentication pass. For production environment i think it might not be a good idea, a better approach to your problem maybe to create the ClusterRole as a workaround here(https://github.com/kubernetes-sigs/kubespray/blob/master/roles/kubernetes-apps/cluster_roles/templates/node-crb.yml.j2) and allow the node to do auto update. 

But i wonder if there is anyways to configure Kubernetes natively so that it just work out of the box without extra ClusterRole. I tried to read and understand the official document here (https://kubernetes-io-vnext-staging.netlify.com/docs/reference/access-authn-authz/node/), but i cannot really understand what to do with "system:nodes" group and "system:node:<nodename>", even though i generate kubelet authentication certificates with "Subject: O=system:nodes, CN=system:node:<nodename>", it still doesn't work properly unless i added extra ClusterRole.

**Comment by RocMe** [comment]
> The pod-eviction-timeout took effects after set the TaintBasedEvictions to false (- --feature-gates=TaintBasedEvictions=false on kubectl conf) because de fault value now is true since 1.13.
> Here we can find all new features and default value linked to a specific version.
> 
> * https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#
> 
> So i think that the new feature TaintBasedEvictions has broken the legacy functionality of pod eviction.
> But I still have a problem with TaintBasedEvictions. Infact my new kubelet extra args configuration is:
> 
> * --feature gates="TaintBasedEvictions=true,TaintNodesByCondition=true,NodeLease=true"
> 
> I have this Deployment:
> 
> ```
> apiVersion: apps/v1 
> kind: Deployment
> metadata:
>   name: nginx-deployment
> spec:
>   selector:
>     matchLabels:
>       app: nginx
>   replicas: 1
>   template:
>     metadata:
>       labels:
>         app: nginx
>     spec:
>       containers:
>       - name: nginx
>         image: nginx:1.7.9
>         ports:
>         - containerPort: 80
>       tolerations:
>       - key: "node.kubernetes.io/not-ready"
>         operator: "Exists"
>         effect: "NoExecute"
>         tolerationSeconds: 30
>       - key: "node.kubernetes.io/unreachable"
>         operator: "Exists"
>         effect: "NoExecute"
>         tolerationSeconds: 30
> ```
> 
> All seams to work well but I realized that the state of my nodes is constantly oscillating.
> 
> ```
> NAME               STATUS     ROLES    AGE    VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
> master-servers-1   Ready      master   115m   v1.13.3   192.168.56.110   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.2
> master-servers-2   Ready      master   113m   v1.13.3   192.168.56.111   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.2
> master-servers-3   NotReady   master   113m   v1.13.3   192.168.56.112   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.2
> worker-servers-1   Ready      worker   112m   v1.13.3   192.168.56.113   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.2
> worker-servers-2   Ready      worker   112m   v1.13.3   192.168.56.114   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.2
> ```
> 
> Infact on all node (3 master 2 worker, installed by **kubeadmin**) in kubectl logs (journalctl -u kubelet -f) I have this error:
> 
> mar 01 12:01:36 master-servers-2 kubelet[25763]: E0301 12:01:36.252570 25763 controller.go:115] failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "master-servers-2" is forbidden: **User "system:node:master-servers-2" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": disabled by feature gate NodeLease**
> 
> Permission issue?!
> 
> Also the documentation states that: "When node lease feature is enabled, each node has an associated Lease object in **kube-node-lease** namespace that is renewed by the node periodically, and both NodeStatus and node lease are treated as heartbeats from the node."
> 
> But I have not kube-node-lease namepsace. :-(

hi I face a problem like this"disabled by feature gate NodeLease".How did you solve it ?

**Comment by SCLogo** [comment]
/reopen
Is that possible it happens with less resources. Our node had 7 pods. 
is that possible it happens because of missing reservations for kubernetes and for nodes?
