### ISSUE TITLE
kubelet log api should at least return one byte when  follow set to true

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes/kubernetes#72397]
**What would you like to be added**:
I want kubelet to reponse with a "START of TEXT" byte before sending real logs.

**Why is this needed**:
When live-streaming pod logs by setting 'follow' to True, the python client (requests/urllib3) needs at least one byte from server to return a response object . When there is no log yield yet, python client would hang in the thread waiting for a response, this make writing a async client very hard. (If put the client in a coprocessing environment, it would block other task.)

/kind feature

**Comment by Shnatsel** [comment]
@kubernetes/sig-api-machinery-proposals

**Comment by liggitt** [comment]
writing spurious data into the log stream is a non goal. ensuring headers are written and flushed back to the client is reasonable, and is done here: 

https://github.com/kubernetes/kubernetes/blob/2cc92a09fd27cca93048e751f232268df552cc79/pkg/kubelet/server/server.go#L564

https://github.com/kubernetes/kubernetes/blob/2cc92a09fd27cca93048e751f232268df552cc79/pkg/kubelet/kubelet_pods.go#L1187-L1192

/close

**Comment by zq-david-wang** [comment]
@liggitt  What about adding a "preamble" option to logs api? The option indicates that logs api should write back a preamble (if set) before sending back logs.
something like this:
# kubectl get --raw '/api/v1/namespaces/ingress-nginx/pods/default-http-backend-68f657df97-j2ncr/log?follow=True&preamble=>>>>>'
>>>>>

This way, no worrying about breaking existing apis, also those clients that needs at least 1 byte to proceed could manage it all by itself, as following python example:
```
log = apiV1.read_namespaced_pod_log(
    name="default-http-backend-68f657df97-j2ncr",
    namespace="ingress-nginx",
    _preload_content=False,
    follow=True,
    preamble="<<<",
)
```

I am writing a PR for this. Need your opinion on it

**Comment by liggitt** [comment]
The client should be fixed to stream content correctly, I don't think an API change to work around this would be a good idea.

**Comment by zq-david-wang** [comment]
@liggitt thanks for the response.
If there could be a fix from client side, it would be great. I have check with client code for a while, but so solve yet, hope community would have better idea for a client fix and I have opened an issue for this in kubernete-python project. But it really seems easier to make api changes and a "preamble" may serve other  purpose as well.

Any way, I would like to keep both options open and make PR for server code changes just for reference

**Comment by zq-david-wang** [comment]
I tried with docker-client's log interface, it would return a HTTPResponse object without blocking even there is not log to read. Base on this, there should be a solution for kubernete-python project.

**Comment by liggitt** [comment]
Yes. Reading response headers only, then returning a reader object to stream the body is a normal feature for http clients.

**Comment by tomplus** [comment]
@liggitt I've tried to check it from python client perspective but I've noticed that headers are not returned by apiserver even if I use kubectl or curl.

Steps to reproduce:

1. Start busybox, it sleeps only and doesn't log

```
$ kubectl run debug --image=busybox --restart=Never --command sleep 300
```

2. Get logs from kubect

```
$ kubectl logs busybox -v9
...
...
I0104 14:27:42.570027    8301 round_trippers.go:436] GET http://localhost:8080/api/v1/namespaces/default/pods/busybox 200 OK in 3 milliseconds
I0104 14:27:42.570051    8301 round_trippers.go:442] Response Headers:
I0104 14:27:42.570070    8301 round_trippers.go:445]     Content-Type: application/json
I0104 14:27:42.570076    8301 round_trippers.go:445]     Date: Fri, 04 Jan 2019 14:27:42 GMT
I0104 14:27:42.570218    8301 request.go:873] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"busybox","namespace":"default","selfLink":"/api/v1/namespaces/tprus/pods/busybox","uid":"d154ca2
[cut]
I0104 14:27:42.574258    8301 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.10 (linux/amd64) kubernetes/0985707" http://localhost:8080/api/v1/namespaces/default/pods/busybox/log?follow=true

... hang, without headers ...
```

3. dump from tpcflow confirms that headers hasn't been sent

```
127.000.000.001.42110-127.000.000.001.08080: GET /api/v1/namespaces/default/pods/busybox/log?follow=true HTTP/1.1
Host: localhost:8080
User-Agent: kubectl/v1.9.10 (linux/amd64) kubernetes/0985707
Accept: application/json, */*
Accept-Encoding: gzip

... hang ... no headers
```

Did I miss something? Thanks.

**Comment by liggitt** [comment]
it looks like the apiserver wrote headers, but did not flush them.

#72575 makes the headers be returned immediately

**Comment by tomplus** [comment]
Thank you for your quick response.
