### ISSUE TITLE
Expand imagePullSecrets to include TLS client authentication

### ISSUE THREAD

**Issue by bernard-wagner** [kubernetes/kubernetes#72394]
**What would you like to be added**:

Allow specifying the x509 certificate and private key to be used by the runtime client as part of `imagePullSecrets`. Kubelet should be able to use the secrets when connecting to the registry endpoint. 

**Why is this needed**:

Private registries often require certificate based client authentication. Although the docker client will attempt to use the certificate and key if present in `/etc/docker/certs.d/{hostname}`, it does not provide the same flexibility as `imagePullSecrets`. 

Issuing and distributing the certificates to unmanaged or autoscaling clusters is not always straight forward. Current workarounds include the creation of `DaemonSets` to copy the certificates on to each node. This approach can cause issues with versioning and also results in the secrets being exposed at rest.

https://godoc.org/github.com/docker/docker/client#WithTLSClientConfig

/kind feature
/sig node

**Comment by liggitt** [comment]
I didn't think docker allowed per-pull TLS options (CA trust roots, for example, must be globally configured). Do client x509 credentials have the same restrictions?
