### ISSUE TITLE
NodeTree.Next() in scheduler is really expensive

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#72408]
I was running some experiments to see what throughput we can get if scheduler wouldn't have all those fancy predicates and priorities.
So what I did is I removed all but "podFitsResources" predicates and all priorities.

What surprised me was that in 5k-node clusters, the throughput I got was ~140pods/s and it was purely limited by scheduler (for simple pods).

So I looked into the profiles and observed, that:
"NodeTree.Next()"
is consuming pretty much the same amount of time as computing those predicates:

[profile001.pdf](https://github.com/kubernetes/kubernetes/files/2715044/profile001.pdf)

It is coming from here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L431

I think this is a significant waste of resources:
- we are pretty much interating over cachedNodeInfoMap (just in a different order)
- we are accessing that cachedNodeInfoMap anyway below:
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L435

Additionally, given that we need locking in that Next() function, this is unnecessary serializing some of the operations and introducing lock contention (especially for those simple predicates for which computing is really is fast).

I think that it is overcomplicated, given how rarely set of nodes changes.
We probably should consider the following:
- keep references to nodes in a simple slice (that gives us constant time access to n-th element)
- access to that list can be locked with read-mutex (so reduce lock-contention)
- only when set of available nodes changes, rebuild that structure (using that fancy logic to rounrobin over zones, etc.)

@kubernetes/sig-scheduling-bugs @kubernetes/sig-scalability-bugs 

/assign @bsalamat

@bsalamat - can you triage this?

**Comment by wojtek-t** [comment]
Actually, I started thinking (similarly to arguments above), why cachedNodeInfoMap:
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L132
actually has to be a map?

Maybe this actually can be a slice:
- we can insert delete an argument to sorted slice in O(lg n) in golang
- do we need a constant time access both ways (from cache to cachedNodeInfoMap and vice versa)?

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/72481 is roughly what I had in mind.
We need to verify the impact and fix tests, but it should be roughly it.

**Comment by bsalamat** [comment]
@wojtek-t Given the outcome of the PR you sent, do you think we should keep this open?

**Comment by wojtek-t** [comment]
Let's keep that open, but I will reassign it to me. I will get back to it once I have a bit of time.
