### ISSUE TITLE
Please clarify --kubeconfig and --config in https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

### ISSUE THREAD

**Issue by justicezyx** [kubernetes/kubernetes#72412]
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ states to use --config with a config file following KubeletConfiguration schema, but the texts did not clarify its relationship with --kubeconfig.

Possible solutions:
- Please consider expand the texts, or link to another page with more details.
- If these cannot be done immediately, I suggest to leave a TODO to ask readers to follow a certain known typical practice, in order to prevent random chasing.
- Something else is more reasonable. Please advise.

Future work
- As K8s' popularity grows, the amount of newcomers are significantly growing, please make sure the documentations are written with a clear targeted audience to avoid writing documents that are not meaningful for expert, but also at the same time is lacking too many details to be useful for novices.

PS:
- The reporter is new to k8s, and has no knowledge to implement the possible solutions.

**Comment by liggitt** [comment]
thanks for the request, please open doc issues against https://github.com/kubernetes/website/issues/ so they can be routed to the correct team

/close
