### ISSUE TITLE
Feature request: Ability to mark a replication controller inactive

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#7242]
If you model deployments of an application as a sequence of replication controllers, often you want to keep the last set of replication controllers around for historical rollback of deployments.

For example, RC[n].replicas=5, RC[n-1].replicas=0, RC[n-2].replicas=0, etc.

If I want to rollback to n-2, ideally, you would size RC[n].replicas=0 and size up RC[n-2].replicas.  The issue is that when you keep a number of legacy controllers laying around in a namespace, they each consume resources resolving the replica size is actually 0 as desired.

Ideally, I would have a way to mark a replication controller as inert, and if inert, the replication controller loop would just skip to the next replication controller and avoid the etcd lookup.

/cc @ironcladlou

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by bgrant0607** [comment]
We're keeping around replicas=0 RCs for Deployment now. The main benefit of the proposal is performance IIUC.

**Comment by bgrant0607** [comment]
cc @kargakis @janetkuo @mqliang

**Comment by bgrant0607** [comment]
cc @kubernetes/deployment

**Comment by kargakis** [comment]
Worth noting that the sync loop relist interval for all the workload controllers has been extended to a random value between 12h and 24h.

**Comment by kargakis** [comment]
Also, the resource handlers are avoiding update events when the resource version is the same. Essentially we are not syncing controllers when there are no events on them. I think this is not an issue anymore.
