### ISSUE TITLE
Getting crash error #kubectl get pods --all-namespaces

### ISSUE THREAD

**Issue by KiranKhadatkar** [kubernetes/kubernetes#72439]
NAMESPACE     NAME                                                       READY   STATUS              RESTARTS   AGE
default       nginx-deployment-5c689d88bb-5r966                          0/1     ContainerCreating   0          51m
default       nginx-deployment-5c689d88bb-wb9jq                          0/1     ContainerCreating   0          51m
kube-system   coredns-576cbf47c7-gqzq7                                   0/1     ContainerCreating   0          4h18m
kube-system   coredns-576cbf47c7-z7pc6                                   1/1     Running             0          4h18m
kube-system   etcd-kirankhadatkar1c.mylabserver.com                      1/1     Running             0          4h17m
kube-system   kube-apiserver-kirankhadatkar1c.mylabserver.com            1/1     Running             0          4h17m
kube-system   kube-controller-manager-kirankhadatkar1c.mylabserver.com   1/1     Running             0          4h17m
kube-system   kube-flannel-ds-amd64-c8w9v                                0/1     CrashLoopBackOff    53         4h10m
kube-system   kube-flannel-ds-amd64-drxcj                                0/1     CrashLoopBackOff    53         4h10m
kube-system   kube-flannel-ds-amd64-pvtwz                                0/1     CrashLoopBackOff    53         4h10m
kube-system   kube-proxy-7npbc                                           1/1     Running             0          4h14m
kube-system   kube-proxy-fbnjr                                           1/1     Running             0          4h18m
kube-system   kube-proxy-gxgtc                                           1/1     Running             0          4h14m
kube-system   kube-scheduler-kirankhadatkar1c.mylabserver.com            1/1     Running             0          4h17m

**Comment by liggitt** [comment]
That means the kubelet cannot start those pods. Try viewing events (`kubectl get events --all-namespaces`) to see more info about why

/close
