### ISSUE TITLE
`hyperkube kubectl` panics on ARM architecture (v1.13.0+)

### ISSUE THREAD

**Issue by ljfranklin** [kubernetes/kubernetes#72447]
**What happened**:

Attempted to run `hyperkube kubectl get pods` but it panics on ARM architecture (Raspberry Pi 3 B+):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76eda68c]
goroutine 1 [running]:
runtime: unexpected return pc for runtime.sigpanic called from 0x76eda68c
```

Interestingly the `kubectl` binary from the same archive works as expected. Only the `hyperkube` binary seems to have the issue.

Full panic output:

[panic.log](https://github.com/kubernetes/kubernetes/files/2717705/panic.log)

**What you expected to happen**:

`kubectl` commands succeed without panicking.

**How to reproduce it (as minimally and precisely as possible)**:

- Downloaded `hyperkube` v1.13.1 (arm architecture) from [here](https://dl.k8s.io/v1.13.1/kubernetes-server-linux-arm.tar.gz)
- Extract archive into current directory
- Run a `kubectl` command via `hyperkube` binary: `./kubernetes/server/bin/hyperkube kubectl get pods`
- See that command panics

**Anything else we need to know?**:

Works on v1.12.4, but v1.13.0 and v1.13.1 fail.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/arm"}
```
- Cloud provider or hardware configuration: Raspberry Pi 3 B+ (ARM architecture)
- OS (e.g. from /etc/os-release): Raspbian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): `Linux node1 4.14.70-hypriotos-v7+ #1 SMP Fri Nov 9 04:39:17 UTC 2018 armv7l GNU/Linux`
- Install tools:
- Others:

/kind bug

**Comment by ljfranklin** [comment]
@kubernetes/sig-cli-bug

**Comment by liggitt** [comment]
do the other hyperkube commands exhibit the same crash? if kubectl works standalone, it is likely the source of the crash is another init block from another of the commands bundled into hyperkube. attempting the other standalone commands might help barrow down the problematic one
