### ISSUE TITLE
Kubernetes API docs section index autoscroll only goes down as far as `CONFIG AND STORAGE APIS > Volume Attachment v1beta1 storage.k8s.io` 

### ISSUE THREAD

**Issue by tjimsk** [kubernetes/kubernetes#72459]
To reproduce:

1. Go to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/
2. Click on any section index item below `CONFIG AND STORAGE APIS > VolumeAttachment v1beta1 storage.k8s.io` (for example, `CLUSTER APIS > Namespace v1 core`)
3. The focus goes to `CLUSTER APIS` click on `Namespace v1 core`.  The index view automatically scrolls to and focuses on `CONFIG AND STORAGE APIS > VolumeAttachment v1beta1 storage.k8s.io > Read Operations > Watch List`

For step 2, any section index before will trigger the expected autoscroll result (for example, click on `WORKLOADS APIS > ReplicaSet v1 apps`).

**Comment by liggitt** [comment]
Thanks for the report. Please open this against https://github.com/kubernetes/website/issues so the right team can address it

/close
