### ISSUE TITLE
Error loading CNI config file /etc/cni/net.d/10-flannel.conf: no 'type'; perhaps this is a .conflist

### ISSUE THREAD

**Issue by orestisf** [kubernetes/kubernetes#72468]
**What happened**:
I've (successfully) set up a k8s cluster in an environment using one master and two workers and am using flannel for networking

The network appears to be functioning (at least I can deploy a basic nginx container) but in journaclt I see repeatedly (~every 5 seconds) the following log:

`Ιαν 01 03:43:48 MASTER-HOSTNAME kubelet[28784]: W0101 03:43:48.321342   28784 cni.go:161] Error loading CNI config file /etc/cni/net.d/10-flannel.conf: no 'type'; perhaps this is a .conflist`

The contents of my `10-flannel.conf` file:
```
cat /etc/cni/net.d/10-flannel.conf
{
  "name": "cbr0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}

```

**How to reproduce it (as minimally and precisely as possible)**:
I deployed flannel by issuing:

`kubectl -n kube-system apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml` [following the recommendation here](https://github.com/kubernetes/kubernetes/issues/48798#issuecomment-427454190) for [known issue 1044](https://github.com/coreos/flannel/issues/1044).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
`Linux MASTER-HOSTNAME 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

/kind bug

**Comment by keiransteele** [comment]
I encountered this exact error. What I did was rename .conf to .conflist and the node immediately went to a ready status. Don't know if this might break anything else but will find out soon.

**Comment by orestisf** [comment]
@keiransteele that's what I ended up doing too, and I haven't noticed anything broken for about at least a week or so.

**Comment by g0lg0th7** [comment]
I have the same issue

**Comment by bini0209** [comment]
I have also same error after restart my master node
