### ISSUE TITLE
kubelet with cri-o goes crazy on CPU/RAM

### ISSUE THREAD

**Issue by mcluseau** [kubernetes/kubernetes#72467]
**What happened**:

In correlation to https://github.com/kubernetes-sigs/cri-o/issues/1927#issuecomment-450588927, when the kubelet get invalid responses from the CRI engine (CRI-O):

```
manager.go:1147] Failed to create existing container: /kubepods/burstable/podda7e2a57-0b9b-11e9-a7a6-0cc47abaca30/crio-e85b43dd2af0a65ae90bcdd6957e0705268c953f3ec5c506d3d096d34eae48c6: invalid character 'c' looking for beginning of value
```

then the kubelet is also seen at very high CPU and memory usage:

```
top - 07:09:52 up 2 days, 22:42,  1 user,  load average: 2774.61, 2601.04, 2421.94
Tasks: 2390 total,   3 running, 1785 sleeping,   0 stopped, 602 zombie
%Cpu(s): 30.4 us, 55.9 sy,  0.1 ni,  9.3 id,  2.3 wa,  0.9 hi,  1.2 si,  0.0 st
MiB Mem : 257891.8 total,   1100.9 free, 237627.1 used,  19163.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  16922.2 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 437442 root      20   0  142.8g  62.1g  13588 S  2714  24.6   5055:02 kubelet
```

**What you expected to happen**:

A better handling of that situation, so the kubelet can stay responsive and do its others tasks. This bug report is not about fixing the cri-o issue.

**How to reproduce it (as minimally and precisely as possible)**:

Hard to say, it happens often on our cluster, with pretty big nodes (40 CPUs + 256GB memory), but it looks more or less random.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: 40 CPUs and 256GB RAM nodes
- OS (e.g. from /etc/os-release): Gentoo
- Kernel (e.g. `uname -a`): 4.19.12
- Install tools: custom (currently working on open-sourcing them)
- Others: under OpenRC, not systemd.

/kind bug

**Comment by mcluseau** [comment]
Example 1m load average:
![image](https://user-images.githubusercontent.com/3868856/50579851-e9b2b180-0e9c-11e9-8676-ede4ebea30e3.png)

**Comment by mcluseau** [comment]
log analysis shows the correlation is not causality. Here are the log sources lines that occur only during error periods, with example:

```
source line                    | Example output
container.go:409               | Failed to create summary reader for "/kubepods/burstable/pod82[...]30/crio-conmon-78[...]48": none of the resources are being tracked.
kubelet.go:1680                | Unable to mount volumes for pod "[...]": timeout expired waiting for volumes to attach or mount for pod "[...]". list of unmounted volumes=[data]. list of unattached volumes=[data config default-token-2wb8w]; skipping pod
log.go:172                     | http: TLS handshake error from 127.0.0.1:37292: EOF
nestedpendingoperations.go:267 | Operation for "\"kubernetes.io/rbd/volumes:[...]\"" failed. No retries permitted until 2019-01-01 [...] (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"[...]\" (UniqueName: \"kubernetes.io/rbd/volumes:[...]\") pod \"[...]\" (UID: \"[...]\") "
operation_generator.go:683     | UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/[...]-default-token-sqnbq" (OuterVolumeSpecName: "default-token-sqnbq") pod "82[...]30" (UID: "82[...]30"). InnerVolumeSpecName "default-token-sqnbq". PluginName "kubernetes.io/secret", VolumeGidValue ""
reconciler.go:181              | operationExecutor.UnmountVolume started for volume "default-token-sqnbq" (UniqueName: "kubernetes.io/secret/82[...]30-default-token-sqnbq") pod "82[...]30" (UID: "82[...]30")
reconciler.go:301              | reconciler.go:301] Volume detached for volume "default-token-sqnbq" (UniqueName:
 "kubernetes.io/secret/82[...]30-default-token-sqnbq") on node "xxx" DevicePath ""
```

If volume errors are not significant, only the error about creating the summary reader is left.

**Comment by mcluseau** [comment]
with more verbosity I think I have something more likely: thousands of `housekeeping took x` with x mostly around 1s (but going up to 10 from what I've seen). I have and average of 875 per second on my sampling. Here's an extract:
```
I0103 22:00:00.025245 1034313 container.go:529] [/kubepods/burstable/pod0f...30/crio-c7...bd] Housekeeping took 2.728330441s
I0103 22:00:00.027711 1034313 container.go:529] [/kubepods/burstable/podd4...30/crio-conmon-e8...d7] Housekeeping took 1.071674334s
I0103 22:00:00.033341 1034313 container.go:529] [/kubepods/burstable/podda...30/crio-conmon-9d...bb] Housekeeping took 1.979761423s
I0103 22:00:00.042124 1034313 container.go:529] [/kubepods/burstable/podd5...30/crio-conmon-24...79] Housekeeping took 2.736489286s
I0103 22:00:00.046191 1034313 container.go:529] [/kubepods/burstable/podda...30/crio-conmon-80...91] Housekeeping took 3.09225748s
I0103 22:00:00.046574 1034313 container.go:529] [/kubepods/burstable/podd9...30/crio-conmon-dc...e7] Housekeeping took 1.090519502s
I0103 22:00:00.047031 1034313 container.go:529] [/kubepods/burstable/podd4...30/crio-conmon-88...0c] Housekeeping took 3.397979933s
```

Also, FWIW, I said I'm using linux 4.19.12, that's because I observed a lot of kernel time and needed https://marc.info/?l=linux-kernel&m=152163868401389&w=2 to optimize it. With the use of RCU in this optimization, now I have this perf top report:

```
   PerfTop:  124396 irqs/sec  kernel:86.1%  exact: 100.0% [4000Hz cycles:ppp],  (all, 40 CPUs)
----------------------------------------------------------------------------------------------------------

    68.48%  [kernel]          [k] osq_lock
     1.62%  [kernel]          [k] native_queued_spin_lock_slowpath
     1.21%  [kernel]          [k] __mutex_lock.isra.5
     0.71%  [kernel]          [k] mutex_unlock
     0.71%  [kernel]          [k] mutex_spin_on_owner
     0.66%  [kernel]          [k] __mutex_unlock_slowpath.isra.18
     0.56%  [kernel]          [k] mutex_lock
     0.54%  libjvm.so         [.] 0x00000000004dfca0
```

**Comment by mcluseau** [comment]
Possibly linked to https://github.com/kubernetes/kubernetes/pull/72105

**Comment by memorais** [comment]
> Possibly linked to #72105
Hi @mcluseau I detected the same behavior on my environment. In my case it started to happen after a migration from 1.13.3 to 1.14.3. Do you figured out whats happening and possible workarounds?

I'm thinking to back with Docker instead of CRI-O... :(

**Comment by mcluseau** [comment]
Hi @memorais, we switched back to containerd for now. I don't know when we'll have time to test again. Since you observe that behavior, I think this bug should be reopened.
/reopen

**Comment by memorais** [comment]
> Hi @memorais, we switched back to containerd for now. I don't know when we'll have time to test again. Since you observe that behavior, I think this bug should be reopened.
> /reopen

Thanks for your quick response. So containerd seems to be an effective solution, I'll give a try since this seems a quite severe bug IMHO. Fortunately I did not migrate this to production, just happening in my test and dev environment.

**Comment by mcluseau** [comment]
Yes, containerd is nice too, we have 10 production clusters and 12 non-production clusters, both metal and virtualized, working well.

**Comment by memorais** [comment]
I just changed to containerd instead of cri-o and the problem stopped happening.
