### ISSUE TITLE
Missing/inconsistent merge patch strategy for ServiceAccount imagePullSecrets 

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes/kubernetes#72475]
The `imagePullSecrets` array on `ServiceAccounts` does not specify a patch strategy of 'merge', so when you try to 'stategic' or 'merge' patch in a new Secret name, any existing Secret names all get removed/replaced. It seems like a merge patch strategy would be appropriate for this array, and indeed the `imagePullSecrets` array for `Pods` already specifies a merge patch strategy. This seems like an oversight or bug that the `imagePullSecrets` array on `ServiceAccounts` is not handled in a consistent and appropriate manner. This is also not consistent with the `secrets` array in `ServiceAccounts` which does merge patch strategy.

**What happened**:

When you try to 'stategic' or 'merge' patch to add a new `Secret` name in the `imagePullSecrets` list on a `ServiceAccount`, and existing `Secret` name(s) get removed/replaced.

**What you expected to happen**:

I expected the `imagePullSecrets` array on `ServiceAccounts` to use a merge patch strategy consistent with `imagePullSecrets` array on `Pods` (which does specify and use a merge patch strategy), and to add the new `Secret` name to the `imagePullSecrets` array.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl patch serviceaccount default --type strategic --patch '{"imagePullSecrets":[{"name":"test1"}]}'
kubectl patch serviceaccount default --type strategic --patch '{"imagePullSecrets":[{"name":"test2"}]}'
kubectl get serviceaccount default -o yaml
````
Note that 'test2' has replaced 'test1', rather than being merged into the `imagePullSecrets` list.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
- name: test2
secrets:
-name: default-token-abcde
```
**Anything else we need to know?**:

`imagePullSecrets` in a `PodSpec` is configured and behaves as expected, merging new secret names into the list.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#podspec-v1-core
```
imagePullSecrets
LocalObjectReference array
patch strategy: merge
patch merge key: name
```

In contrast `imagePullSecrets` in a `ServiceAccount` is missing this behavior/specification

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#serviceaccount-v1-core
```
imagePullSecrets
LocalObjectReference array
```

Yet the `secrets` array in a `ServiceAccount` does have a merge strategy.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#serviceaccount-v1-core
```
secrets
ObjectReference array
patch strategy: merge
patch merge key: name
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): GCE COS
- Kernel (e.g. `uname -a`): GCE COS (Linux 4.14.65+ #1 SMP Thu Oct 25 10:42:50 PDT 2018 x86_64) GNU/Linux
- Install tools: GCE
- Others: N/A

/kind bug

**Comment by tossmilestone** [comment]
@whereisaaron because there is no `patchStrategy` tag on `imagePullSecrects`, I could create a PR to fix the issue.

**Comment by liggitt** [comment]
unfortunately, changing the merge patch strategy is not backwards compatible with existing API usage. you can use a json patch to append items to the list

**Comment by whereisaaron** [comment]
Thanks @liggitt I did look test a json patch, and it works to add, but you can't test if the item is in the array/list already, so I think their is no atomic json patch to do this?

Isn't any existing API usage expecting this, a direct result of working around this problem? 

Even so, when this is fixed, it isn't a problem if people patch in the same Secret name, since a merge patch won't lead to a duplicate, as before the fix.

Is the breaking issue a (more obscure?) situation where people patch in secret Name 'd' into a ServiceAccount, and they are rely on existing Secret names 'a', 'b', and 'c' to be deleted? And with this problem fixed, they would end up with 'a', 'b', 'c', 'd'? That wouldn't prevent any pulls, unless maybe 'a' and 'd' were different credentials for the same registry?

OK, I understand this can't be fixed in a patch release if it might break assumptions like above people are relying on. Does that means we have to target a PR to a minor release like 1.14.x or 1.15.x?

**Comment by liggitt** [comment]
> Does that means we have to target a PR to a minor release like 1.14.x or 1.15.x?

API breakage is not acceptable even on minor versions. Changes in behavior like that would require an API revision (e.g. `v2`) which is not planned in the near term

**Comment by whereisaaron** [comment]
Oh dear, we are stuck with this for a while then @liggitt! 😅
Thanks for your efforts @tossmilestone 👏 ❤️

**Comment by answer1991** [comment]
@liggitt 

Have we had any specifications about how to set the new field tag to prevent the similar issue happen again?

**Comment by PriyankPa** [comment]
Came here following a similar trail or issues as OP. Will this be taken up in v2?
