### ISSUE TITLE
kube-proxy componentConfig ergonomics

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#72480]
**What would you like to be added**:

With a push to migrate all components  to componentConfig it is important not to make existing use-cases worse.. More specifically, following uses should remain possible and be easy to use:

 1. `--hostname-override` should remain "legal" cli switch as it makes no sense to put it into supposedly common config
 2. configuration fetch/reload (probably common to all componentConfig users, not just kube-proxy):
      a. if used via ConfigMap , kube-proxy should be detecting updates to file. when using command line, change to args causes pod restarts and all settings are applied, that is not what happened with componentConfig file.
      b. visibility of change propagation is much lower with componentConfig: with CLI rolling pod restarts shows explicitly which instances applied new config and which one did not.
      c. change safety: should there be a config change which causes kube-proxy to crash, ALL instances of kube-proxy are going down, instead of just one when using rolling update and CLI

All items in 2. can be mitigated by embedding full config as environment variable and then writing to a file in entrypoint with `/bin/sh -c 'printenv CONFIG > config.yaml && exec kube-proxy --config config.yaml'` but that is ugly and somewhat defeats the point of componentConfig

/sig cluster-lifecycle

/kind feature

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by mtaufen** [comment]
Regarding (1) yes :)
Regarding (2) you should be able to do a rolling update of a deployment or daemonset that switches it to a new configmap reference, rather than updating a configmap in place. It's best to treat configmaps as immutable. `kubectl create configmap` has the `--append-hash` option to help with unique naming.

**Comment by redbaron** [comment]
Regarding (2), it is not about how to workaround, it is about Kubernetes
team offering like for like replacement for previous practices.


Before it was enough to have bunch of yaml files and apply them and
everything would sort itself out. Unless kube-proxy is changed to reread
configmap, I can't do it anymore, I am now forced to drop to bash to do
immutable configmap and retemplating, that is what I call "make my life
worse"

**Comment by mtaufen** [comment]
I think dealing with immutable configmaps is one of the use-cases that kustomize is designed to help with. You're right that it's not necessarily as easy as "just applying" once the name needs to change, so this is something that ought to be solved, either in kustomize or elsewhere.

/cc @monopole

**Comment by redbaron** [comment]
/remove-lifecycle stale

Sent from ProtonMail mobile

-------- Original Message --------
