### ISSUE TITLE
kubectl port-forwarding has a hardcoded concept that assumes target pod/container to be listening on 127.0.0.1

### ISSUE THREAD

**Issue by sokoow** [kubernetes/kubernetes#72488]
**What happened**:
Seems like kubectl port-forwarding has a hardcoded concept that assumes target pod/container to be listening on 127.0.0.1. We've ran into some trouble for containers that appear listen on IP of the pod only. Yeah I know, it's enough to just change listen address of app in the pod to 0.0.0.0 and it should resolve it - try that with legacy apps and slower code cycle changes apps. 

**What you expected to happen**:
Can some flag/switch be considered to be added to kubectl port-forwarding invocation that will change target listening IP addr for pods pls ?

**How to reproduce it (as minimally and precisely as possible)**:
Run a pod that listens at non 127.0.0.1, try to redirect it with kubectl port-forwarding

**Anything else we need to know?**:

**Environment**:
True for pretty much any setup 

/kind bug
/sig-cli

**Comment by liggitt** [comment]
/remove-sig cli
/sig node

the actual communication with the container is done by the kubelet via the container runtime interface (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/streaming/server.go#L380-L382)
