### ISSUE TITLE
1.12 kubelet upgraded to 1.13 leaves stale OutOfDisk condition

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#72485]
**What happened**:

https://github.com/kubernetes/kubernetes/pull/70111 removed reporting of the OutOfDisk condition in the kubelet.

A 1.12 kubelet upgraded to a 1.13 kubelet leaves the previously reported OutOfDisk condition in place, and it eventually gets switched to Unknown status.

**What you expected to happen**:

If this condition is no longer reported, it should be removed by the kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run a 1.12 kubelet, let it report OutOfDisk condition status.
2. Upgrade to 1.13
3. Note the condition is no longer updated
4. After a while, the node controller flips the status to Unknown

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig node

**Comment by resouer** [comment]
/assign

We happened to have a fix handy, if no one is working on it.

**Comment by zhangxiaoyu-zidif** [comment]
after upgrade kubelet should ignore this condition .

**Comment by dixudx** [comment]
> or change it to 'DiskPressure'

@zhangxiaoyu-zidif Better not. What if both condition `DiskPressure` and `OutOfDisk` exist?

**Comment by Pingan2017** [comment]
@liggitt  #67037 should be picked to 1.13 also, I think.

**Comment by erikh** [comment]
1.13.2 doesn't have this patch; would it be possible to make it for 1.13.3?

**Comment by ghouscht** [comment]
Unfortunately this was not mentioned in the release notes (or I missed it), got hit by this too.
1.13.2 is affected too, would be good for me to see this getting fixed in 1.13.3
