### ISSUE TITLE
During e2e kube-up, existing disks, firewall-rules and addresses cause failure.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#7248]
If an e2e run is terminated by ctrl-c, closing laptop, etc, then resources may exist in a partial state.
This seems to happen to me a lot.

Some examples:

ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
 - The resource 'projects/causal-jigsaw-637/global/firewalls/e2e-test-etune-master-https' already exists

ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/causal-jigsaw-637/regions/us-central1/addresses/e2e-test-etune-master-ip' already exists

**Comment by quinton-hoole** [comment]
Thanks for filing. We could probably improve this, but not for v1.0.
Until improved, avoid interrupting e2e tests, and/or manually delete the cruft that they leave behind when interrupted.

**Comment by erictune** [comment]
Sometimes waiting for the test cleanup by itself can hang for an hour or more.    So, not pressing ctrl-c is a poor option.

**Comment by quinton-hoole** [comment]
Oh dear.  Jenkins e2e tests run to completion in about 20 min.  Are you seeing longer than that?
But yes, agreed, if you're trying to run all of the e2e tests, but decide to terminate part way through, then manual cleanup is probably the best approach (a few minutes of clicking around in the gcloud UI, or I wrote a little bash script to do it for me).  If you're finding it significantly more arduous than I'm describing, then perhaps we should invest some time in fixing it up.
