### ISSUE TITLE
kube-apiserver etcd object count metrics do not allow us to infer the total number of objects in etcd

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#72492]
Currently we only log out the etcd object counts for resources which we know about. Noteably, we do not output the object counts for dynamic resources (i.e. CRDs). This can be problematic when troubleshooting a cluster. We should be able to export (as metrics) both the total number of objects in etcd at a given time as well as the sum total of the CRD objects in existence at a given time. 

/kind bug

**Comment by sttts** [comment]
How is this related to https://github.com/kubernetes/kubernetes/pull/65983 ? What else is needed?

**Comment by logicalhan** [comment]
@sttts, ah good to know, was looking at an older cluster which did not have these metrics. I'll close the ticket.
