### ISSUE TITLE
Regression in volume provisioning with shared datastore on vSphere

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#72497]
It appears that vSphere used to support dynamic volume provisioning even if datastore being used isn't shared with all VMs in the cluster (somewhere in 1.7/1.8). But in 1.9 - we changed this behavior and now volume provisioning does not work at all if any of datastore being used is not shared between all VMs of the cluster.

Shouldn't this be considered a breaking change?

cc @divyenpatel @SandeepPissay

**Comment by krejkrejkrej** [comment]
Hello. I represent one bank affected by this change. In Openshift 3.7 we've successfully used a combination of node Labels+NodeSelectors and PersistentVolumeClaims+StorageClasses to place pods and volumes, respectively, on their intended compute/storage tier. The compute/storage tiers are isolated from each other. 

Now, in Openshift 3.10 provisioning new PVC's does not work, however already existing PVC's can be used. Feel free to reach out to me for more details.

**Comment by SandeepPissay** [comment]
@gnufied This code is added on purpose. This is done to prevent situations where the kube-scheduler cannot schedule pods on nodes that do not have access to the datastore. To prevent this, the current vSphere Cloud Provider validates that the datastore is shared across all Kubernetes nodes before creating the persistent volume.

@subramanian-neelakantan is working on a PR that supports zones in vSphere cloud provider where we will check for shared datastores only within the zone. Here's the first PR for that feature support - https://github.com/subramanian-neelakantan/kubernetes/pull/1

**Comment by gnufied** [comment]
@SandeepPissay But there exists at least couple of workarounds that a customer could use to ensure that pods get only scheduled on nodes where volume can attach itself. 

We have same problem in AWS and GCE as well. But we chose not to break dynamic provisioning as it exists. I know it is not ideal but it seems like least painful way of ensuring backward compatibility.

**Comment by gnufied** [comment]
xref - https://github.com/kubernetes/kubernetes/pull/55845

**Comment by subramanian-neelakantan** [comment]
This situation could get better once vSphere Cloud Provider adds support for "zones". This is being worked upon here 
https://github.com/kubernetes/kubernetes/issues/67703. With this support, the requirement for a shared datastore is limited to only node VMs of the same zone. The vSphere admin would have the ability to partition nodes into zones based on the ESX hosts and datastore topology boundaries in vSphere.

I would like to hear if there are customer use cases where this would still not help. That would help us prioritize this issue.
