### ISSUE TITLE
kubectl vs kubeclt (command-line tool)

### ISSUE THREAD

**Issue by dolanmiu** [kubernetes/kubernetes#72490]
I can't find anything on google about this, but everywhere in the documentation, `kubectl` is referred to as the "Kubernetes **C**ommand-**L**ine **T**ool"

```
https://kubernetes.io/docs/tasks/tools/install-kubectl/
```

So, naturally, should it not be `kubeclt` rather than `kubectl`? As CLT stands for **C**ommand-**L**ine **T**ool.

/sig-cli

**Comment by Shnatsel** [comment]
This probably makes sense, but the tool is far too widespread to rename it now.

**Comment by liggitt** [comment]
it is an abbreviation of "control", along the lines of etcdctl, systemctl, journalctl, ...

/close
