### ISSUE TITLE
Vsphere cloud provider - Error syncing pod timeout expired

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes#72509]
**What happened**:
Time to time i am getting FailedSync error message timeout expired waiting for volumes to attach/mount for pod while running create pod command. The pod stuck on creation process long time.
**What you expected to happen**:
pod created and running 

**How to reproduce it (as minimally and precisely as possible)**:
This is sporadic problem and difficult to reproduce. It could happen once in 10s restarts.  
kubectl create po test.yaml 
**Anything else we need to know?**:
We are experiencing with this problem with kubernetes 1.6  version and vmware 6.0 version.
**Environment**:
- Kubernetes version (use `kubectl version`):
 kubernetes 1.6
- Cloud provider or hardware configuration:
   vsphere cloud provider
- OS (e.g. from /etc/os-release):
ubuntu 14.04
- Kernel (e.g. `uname -a`):
Linux ws-lnx01 4.4.0-97-generic #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
govc
- Others:
Looks like this is a bug.

/kind bug

**Comment by Shnatsel** [comment]
@kubernetes/sig-vmware-bugs

**Comment by g1001p** [comment]
This problem happening if pod is trying mounting vmdk disk

**Comment by figo** [comment]
@g1001p  do you have any kubelet logs?  also have a some questions around your description.
1) is pod eventually able to create successfully? (since you are saying it is taking long time) 
if yes, how much delay you got?  < 1m? ~10m? or longer?

2) how to reproduce this issue exactly?
is it restarting the kubelet?  (you mentioned: `It could happen once in 10s restarts`)

**Comment by g1001p** [comment]
1. is pod eventually able to create successfully? (since you are saying it
is taking long time)
   if yes, how much delay you got? < 1m? ~10m? or longer?

 There are a combination of it - sometimes pod was creating in less than
minute, sometimes in less than 10 minutes,  sometimes longer than 10
minutes and sometimes it was stuck even days on the creation state .
 There is dissimilar duration of the delay.

2.  how to reproduce this issue exactly?
     is it restarting the kubelet? (you mentioned: It could happen once in
10s restarts)
 It is not simple reproduce this problem
 Sometimes this issue could happening while restarting entire kubernetes
cluster which include restarting kubelet.
 Sometimes if just delete and create pod with mount of vmdk disk.
