### ISSUE TITLE
pods with nodeAffinity went to MatchNodeSelector state after node reboots

### ISSUE THREAD

**Issue by xinma** [kubernetes/kubernetes#72502]
pods with `nodeAffinity` went to `MatchNodeSelector` state.

**What happened**:

After a power maintenance (or decent amount of nodes reboot together in short period of time), lots of pods went into `MatchNodeSelector` state hence not coming up.
Even after cluster later went to a stable state and all nodes became ready/up-to-date. these `MatchNodeSelector` (failed to be admitted) pods never came up again as kubelet put them into same bucket as terminated pods.
some of the pods we had were not backed by a deployment or rc. so I had to either delete and recreate these pods, or force update pod state (with `PUT` against pod status field).

> more details after my troubleshooting. 

first. all failed pods had the following affinity in spec.
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain
            operator: In
            values:
            - Rack1
```
it requires node object to have label `failure-domain=Rack1`, which we applied to node object via apiserver.

kubelet logs from node, after reboot.
```
-- Reboot --
Dec 04 08:14:39 nodeXXX systemd[1]: Started Kubernetes Kubelet Server.
Dec 04 08:14:56 nodeXXX kubelet[8615]: I1004 08:14:56.527919    8615 kubelet_node_status.go:82] Attempting to register node nodeXXX

Dec 04 08:14:59 nodeXXX kubelet[8615]: I1004 08:14:59.603526    8615 kubelet.go:1871] SyncLoop (ADD, "api"): "xxxxx, podXXX(podUUID), xxxxx"
Dec 04 08:14:59 nodeXXX kubelet[8615]: I1004 08:14:59.675924    8615 predicate.go:120] Predicate failed on Pod: podXXX(podUUID), for reason: Predicate MatchNodeSelector failed

Dec 04 08:15:05 nodeXXX kubelet[8615]: E1004 08:15:05.541717    8615 kubelet_node_status.go:106] Unable to register node "nodeXXX" with API server: the server has received too many requests and has asked us to try again later (post nodes)
```
kubelet attempted to register and update Node object since `Dec 04 08:14:56` 
before it got a retry return from apiserver (last log above `Dec 04 08:15:05`). It already entered sync loop and rejected the pod that referred to not-yet-sync'd labels from node object (with the `initialNode`). 

a quick going-thru in code.
`Run()` of kubelet.go would try to `syncNodeStatus` which would hit `kl.registerWithAPIServer` from `kubelet_node_status.go`.
in parallel, kubelet entered syncloop, got all pods on the node, and tried to bring them up with `HandlePodAdditions` from which it checked and tried to admit these pods. in pod admit, it would hit `getNodeAnyWayFunc` first and eventually hit `getNodeAnyWay` in `kubelet_getters.go`, since `GetNodeInfo` at this moment would fail, it would fail back to get a `initialNode` without all extra labels. thus pod referring these labels would fail to be admitted, kubelet would `kl.rejectPod` which put that pod into terminated phase.

**What you expected to happen**:
Pods with `nodeAffinity` or any node label selecting should be able to come up eventually, after node object is fully sync’d.
In this case, pods would enter a somehow un-recoverable state. even after node object is fully sync’d.

**How to reproduce it (as minimally and precisely as possible)**:
This is more of a scalability issue. we have thousand-nodes clusters, and when we reboot or restart kubelet on ~500 of them all together, apiserver started to reject connection and then we saw behaviors like this.
in terms of ways to reproduce.
1. in a cluster label some nodes with label a=b. `kubectl label node a=b`.
2. create pods with `nodeAffinity` (`matchExpressions`. key `a` In values `b`)
3. (in our case) reboot all nodes at once. (or other ways to simulate apiserver delays). 
the way we saw it was - when we reboot ~500 nodes at once. most of the pods with nodeAffinity
 in the rebooted nodes would enter `MatchNodeSelector` state.

**Anything else we need to know?**:
n/a

**Environment**:
- Kubernetes version: 1.10 (and i think same issue still exists in latest version.)
- Cloud provider or hardware configuration: private cloud and k8s cluster with all BMs.
- OS (e.g. from /etc/os-release): CentOS atomic 7.5 
- Kernel (e.g. `uname -a`): 4.15
- Install tools:
- Others:

/kind bug
/sig node

**Comment by xinma** [comment]
IMHO.

major issue is here. in `Run()` of `kubelet.go`:

https://github.com/kubernetes/kubernetes/blob/816dfab180e1a0739a7928c0eff45067801aaa12/pkg/kubelet/kubelet.go#L1406-L1438

[L1408](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1408) started a go routine to `syncNodeStatus`.
however it if takes long enough. in [L1438](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1438) it already enters syncloop and starts to get podconfig from configchannel and handle pod ADDs and admits.

One proposal is to wait on `kl.registrationCompleted == true` before the start of watching apiserver aka `NewSourceApiserver` when kubelet does `makePodSourceConfig`

**Comment by mlmhl** [comment]
How do you determine that this problem is due to node registration failure? The node objects won't be deleted in apiserver/etcd during node rebooting, so I guess the reason is that the node info cache hasn't been synced when `GetNodeInfo` is invoked by the admit process. In other words, [this line](https://github.com/kubernetes/kubernetes/blob/816dfab180e1a0739a7928c0eff45067801aaa12/pkg/kubelet/kubelet_getters.go#L232) returns a not found error and then fall back to use `initalNode`.

BTW, what type of app do you use, or you just use pod directly?

**Comment by salanki** [comment]
We just had this happen, anyone has any clarity?

**Comment by lyind** [comment]
This issue still seems to persists in K8s 1.20.2 and is really annoying:

After node reboot (first pod is replacement launched after the old pod couldn't restart due to the issue):
```
...
rook-ceph            rook-ceph-osd-25-967d79b58-4zhkk                                  1/1     Running        0          19m
rook-ceph            rook-ceph-osd-25-967d79b58-c5pkp                                  0/1     NodeAffinity   0          16d
...
```

Could we please reopen it or is there any known workaround I may have missed?

**Comment by kqsantacruz** [comment]
FWIW, I'm also experiencing this issue using preemtible nodes in GKE, in my case running  1.18.16-gke.302, which I believe should contain the cherry-picked fix.
