### ISSUE TITLE
ServiceAccountName not removed with Kubectl apply

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/kubernetes#72519]
**What happened**:
If you have a deployment with `serviceAccountName` set if you remove the field and apply the new config the `serviceAccountName` remains set to what it previously was.
**What you expected to happen**:
The `serviceAccountName` to be removed from the deployment spec.
**How to reproduce it (as minimally and precisely as possible)**:
Apply a deployment with a service account set e.g
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: busybox
          command:
            - sleep
            - "600"
    serviceAccountName: "foo"
```
Then apply the same manifest with it removed.
kubectl apply -f test.yaml
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: busybox
          command:
            - sleep
            - "600"
```

`kubect get deploy test -o yaml`
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"test","namespace":"kube-system"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"test"}},"template":{"metadata":{"labels":{"app":"test"}},"spec":{"containers":[{"command":["sleep","600"],"image":"busybox","name":"test"}]}}}}
  creationTimestamp: "2019-01-03T14:10:52Z"
  generation: 5
  name: test
  namespace: kube-system
  resourceVersion: "214767939"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/test
  uid: 6131e4f9-0f61-11e9-85ae-025efa9cc9c4
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - command:
        - sleep
        - "600"
        image: busybox
        imagePullPolicy: Always
        name: test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: foo
      serviceAccountName: foo
      terminationGracePeriodSeconds: 30
```
The service account is still set.

I do get `deployment.apps/test configured` when applying the change which implies it notices the change but does not seem to act on it.
**Anything else we need to know?**:
This also works with a CronJob, so does not seem specific to Deployments
**Environment**:
- Kubernetes version (use `kubectl version`):
v1.11.5 (have reproduced on minikube v1.13.0)
cli: v1.13.1
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1800.6.0
VERSION_ID=1800.6.0
BUILD_ID=2018-08-04-0323
PRETTY_NAME="Container Linux by CoreOS 1800.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`): 
```
Linux ip-172-23-12-198.eu-west-1.compute.internal 4.14.59-coreos-r2 #1 SMP Sat Aug 4 02:49:25 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
- Others:

/kind bug

**Comment by liggitt** [comment]
serviceAccountName is defaulted from serviceAccount for backwards compatibility. It is not possible to leave one field unset.

/close

**Comment by roy-work** [comment]
This bug bit me today. As I stated on the linked #82525, I consider `kubectl apply` to be an operation that sets the current state of an object, not patches it. Having properties like this that survive the apply is incredibly surprising.

> It is not possible to leave one field unset.

The `kubectl apply` in the original bug report doesn't set either field. (It doesn't explicitly `null` them out, which I think is what you're getting at, but I don't think that should be required during a `kubectl apply`.)

**Comment by Stono** [comment]
Also bitten by this.  In helm we use just “serviceAccountName” in our spec.   We don’t set “serviceAccount”

therefore when we remove serviceAccountName we would be expecting it to be removed, not left around.

reading this, we could work around it by setting serviceAccount as well, but it feels counter intuitive to need to set the value of a field that is otherwise auto generated for us.

**Comment by fluxx-sleblanc** [comment]
I just hit an issue where using `kubectl apply` to set both:
```
      serviceAccountName: null
      serviceAccount: null
```
did *NOT* unset either value. 

However, using `kubectl edit` to make the change directly to the deployment manifest worked. 

It seems that it no longer works to explicitly set both fields to empty with `kubectl apply`.

**Comment by tobinus** [comment]
I encountered this bug today. As an alternative to clearing both `serviceAccountName` and `serviceAccount`, it is possible to explicitly set `serviceAccountName` to `default`, which is [what Kubernetes does internally](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) either way:

> Every Kubernetes namespace contains at least one ServiceAccount: the default ServiceAccount for that namespace, named `default`. If you do not specify a ServiceAccount when you create a Pod, Kubernetes automatically assigns the ServiceAccount named `default` in that namespace.
> 
> (…)
> 
> In the output, you see a field `spec.serviceAccountName`. Kubernetes automatically sets that value if you don't specify it when you create a Pod.

I prefer this workaround, since it means I only need to set `serviceAccountName`, and can avoid using the deprecated `serviceAccount` field.

I guess this means we should add `serviceAccountName: default` to any manifests that have a PodTemplate, have not set `serviceAccountName` already, and are applied using `kubectl apply`, `helm` or similar, so that it is possible to roll back any change to `serviceAccountName` down the road.
