### ISSUE TITLE
How to incrementally roll out update node when using Dynamic Kubelet Configuration

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#72510]
@mtaufen 
kubectl version:v1.12.2
kube-api version:v1.12.2
kubelet version:v1.12.2
I follow the guide [https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/](url) to configure Dynamic Kubelet Configuration. It seems that if I want to incrementally roll out update all nodes maybe follow these orders as below:
1. create a new configmap and save it to the Kubernetes control plane
2. `kubectl edit no ${node}` to make node point to the new ConfigMap one by one
3. waiting for kubelet auto restart 

My question is:
1. If I have a huge cluster(likely 1000 nodes), I should use the above method to update those nodes one by one by myself?
2. It seems that there're some options didn't exist in [KubeletConfiguration type](https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/kubelet/apis/kubeletconfig/v1beta1/types.go), such as `--network-plugin=cni` ` --allowed-unsafe-sysctls=net.*,kernel.shm*,kernel.msg*,kernel.sem,fs.mqueue.*` and so on. So I need configure those options in command line by myself?

/sig node

**Comment by mtaufen** [comment]
1. Correct. Create the ConfigMap with your config in it and then update the reference on each Node one-by-one. This allows you to do a rolling update.
2. Also correct. Several options haven't been migrated to the KubeletConfiguration type yet (work is in progress). To set these, you currently need to have control over the configuration of the Kubelet's command line.

**Comment by workhardcc** [comment]
> 1. Correct. Create the ConfigMap with your config in it and then update the reference on each Node one-by-one. This allows you to do a rolling update.
> 2. Also correct. Several options haven't been migrated to the KubeletConfiguration type yet (work is in progress). To set these, you currently need to have control over the configuration of the Kubelet's command line.

Thanks for your reply!
