### ISSUE TITLE
In-cluster namespace isn't overridden by kubeconfig if the context is specified via kubectl --context flag.

### ISSUE THREAD

**Issue by deiwin** [kubernetes/kubernetes#72524]
**What happened**:
In-cluster namespace isn't overridden by kubeconfig if the context is specified via kubectl `--context` flag. When using `kubectl config use-context`, the override works as expected.

**What you expected to happen**:
If I specify `namespace: default` for a `test` context in kubeconfig, then I expect `kubectl --context=test` to use `default` as the default namespace, regardless of whatever's in `/var/run/secrets/kubernetes.io/serviceaccount/namespace`.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl run -i -t --rm test --image=lachlanevenson/k8s-kubectl:v1.10.5 --restart=Never -n kube-system --command -- sh                                                                                                           [18:21:39]
If you don't see a command prompt, try pressing enter.
~ # kubectl version --client
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
~ #
~ # # By default the in-cluster namespace is used as expected
~ # kubectl get pods --v=99 2>&1 | grep "Using in-cluster namespace"
I0103 16:23:03.535870       8 merged_client_builder.go:160] Using in-cluster namespace
~ # kubectl config set-context test --namespace=default
Context "test" created.
~ #
~ # # I would expect this not to use in-cluster namespace, but it does
~ # kubectl get pods --context=test --v=99 2>&1 | grep "Using in-cluster namespace"
I0103 16:24:09.477277      51 merged_client_builder.go:160] Using in-cluster namespace
~ #
~ # # This workaround allows not using the in-cluster namespace
~ # kubectl config use-context test
Switched to context "test".
~ # kubectl get pods --v=99 2>&1 | grep "Using in-cluster namespace" 
~ #
```

**Anything else we need to know?**:
#44570 supposedly fixed this issue, but not for the case where the context is specified via a command line flag (`--context`).

This is because this line
https://github.com/kubernetes/kubernetes/blob/32ac1c9073b132b8ba18aa830f46b77dcceb0723/staging/src/k8s.io/client-go/tools/clientcmd/merged_client_builder.go#L154
checks for `raw.Contexts[raw.CurrentContext]`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.5 (details above)
- Cloud provider or hardware configuration: -
- OS (e.g. from /etc/os-release): -
- Kernel (e.g. `uname -a`): -
- Install tools: -
- Others: -

/kind bug

**Comment by deiwin** [comment]
@kubernetes/sig-cli

**Comment by Shnatsel** [comment]
@kubernetes/sig-cli-bugs
