### ISSUE TITLE
etcd / grpc-go version mismatch

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#72538]
according to etcd documentation, it says - `clientv3-grpc1.7: Official client implementation, with grpc-go v1.7.x, which is used in latest etcd v3.2 and v3.3.`, so we should be only using grpc-go 1.7.x 

since 1.7.5 is the latest in 1.7.x series, we should stick to that until we switch to etcd 3.4 (which will need/use grpc-go 1.14.x)

However in https://github.com/kubernetes/kubernetes/pull/71020, we ended up switching to gRPC to 1.13.0 which seems to be a potential culprit for issues being documented in https://github.com/kubernetes/kubernetes/issues/71696

Note that this is not a simple revert of the grpc-go version as the csi.pb.go (added in https://github.com/kubernetes/kubernetes/pull/71020/commits/c63476d0c4d8ec0d28360c505a25c5525b9cbbe7#diff-94325e976a8ceaffad911d49a184c626) must be re-generated with the correct version of protoc which will work with 1.7.5 of grpc-go 

/assign @saad-ali

**Comment by dims** [comment]
we are also seeing the problem in 1.13 branch, so any action taken here has to be applied to 1.13 as well.

/sig release

**Comment by dims** [comment]
cc @jpbetz @liggitt @wojtek-t

**Comment by liggitt** [comment]
notably, the grpc bump for CSI landed ~4 hours before the first sighting of the 0-length response failure - https://github.com/kubernetes/kubernetes/issues/71696#issuecomment-450187362

**Comment by dims** [comment]
Same with the merge commit for 1.13 landed and the CI jobs on that branch started showing issues as well.

**Comment by wojtek-t** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/71696

**Comment by saad-ali** [comment]
I will look in to regenerating the CSI client with an older version of gRPC as a temporary workaround. 

What are the timelines for moving to `etcd 3.4`?

**Comment by dims** [comment]
we should still give the folks who take care of etcd that we are using different grpc versions than what they may be expecting us to use (cc @xiang90 @jpbetz)

**Comment by dims** [comment]
/close

seems like we have been doing ok with the versions we picked. So let's close this out
