### ISSUE TITLE
[scheduler cleanup phase 🐼]: Move cache debugger setup into a helper function

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#72543]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

Currently, the `cache/debugger` feature is set up at the end of `NewConfigFactory()` in `pkg/scheduler/factory/factory.go`. This setup should be moved into its own helper function, preferably in the `cache/debugger` package.

/sig scheduling

/kind cleanup

/help

**Comment by mjaow** [comment]
I'd like to take this one
