### ISSUE TITLE
[scheduler cleanup phase 🐼]: Change `getBinderFunc` from method to function

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#72544]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

The `getBinderFunc` method of `configFactory` does not need to be a method. It should be converted into a plain func that takes a client (`kubernetes.Interface`) and slice of `SchedulerExtender`. (code is in `pkg/scheduler/factory/factory.go`)

/sig scheduling

/kind cleanup

/help

**Comment by xiaoanyunfei** [comment]
I'd like to take this one

**Comment by misterikkit** [comment]
fixed by #72615
