### ISSUE TITLE
[scheduler cleanup phase 🐼]: Change `MakeDefaultErrorFunc` from method to function

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#72545]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.

Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

The `MakeDefaultErrorFunc` method of `configFactory` contains a lot of error handling logic, but that logic does not belong in the `configFactory` type. It should be converted into a regular func that takes all the args it needs instead of `configFactory`.

(code is in `pkg/scheduler/factory/factory.go`)

/sig scheduling

/kind cleanup

/help

**Comment by xiaoanyunfei** [comment]
I'd like to take this one
