### ISSUE TITLE
Cleanup volume/util.UnmountMountPoint callers

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#72550]
**What would you like to be added**:
After https://github.com/kubernetes/kubernetes/pull/71804 merges, the callers of the functions noted [here](https://github.com/kubernetes/kubernetes/pull/71804/files#diff-c3acf7a7fec401d0a3cb4998088ee1e5R130) should be updated to use the mount pkg directly, and the functions under pkg/volume/util removed.

/kind cleanup

**Comment by msau42** [comment]
/help
@kubernetes/sig-storage-bugs

**Comment by danielqsj** [comment]
@msau42 I'd like to take this task.
/assign
