### ISSUE TITLE
The Pod set Restart Policy always but the kubelet always create a new container, not restart the old exited container

### ISSUE THREAD

**Issue by xqqcoder** [kubernetes/kubernetes#72557]
/triage support

**Comment by mjaow** [comment]
i've tried. You have to recreate pause container after it exited. And there must be a way to update relation from app container to pause container

**Comment by xqqcoder** [comment]
> i've tried. You have to recreate pause container after it exited. And there must be a way to update relation from app container to pause container. But docker donnot support it
> 
> At Last,I have to hack docker to make it work

yes, you re right , i read the kubelet code ,the restart policy just push the failed pod to create queue to recreate the pod, i want to use pod for vm, maybe hack the kubelet to restart the docker container will solve my problem

**Comment by xqqcoder** [comment]
> is it the new pause container are created for back-off delay? the old container will eventually been restarted.
> 
> ```
> Exited Containers that are restarted by the kubelet are restarted with an exponential back-off delay (10s, 20s, 40s …) capped at five minutes, and is reset after ten minutes of successful execution
> ```

this just recreate the pod's container , i want the restart policy to restart the docker container not recreate new

**Comment by xqqcoder** [comment]
i have another problem is that i want the kubelet restart the exit container when the machine restart  or docker restart , this must hack the kubelet ?
