### ISSUE TITLE
Specify the pod of the statefulset to update

### ISSUE THREAD

**Issue by huweihuang** [kubernetes/kubernetes#72555]
**What would you like to be added**:

Now the Phased Roll Outs of the statefulset can only be updated one-way based on a pod number, ie partition. For example, partition is equal to 2, and pods greater than or equal to 2 can be updated, but pods whose partition is less than a certain value cannot be specified for update, and a pod update cannot be specified.

**Why is this needed**:

example:
I use statefulset to create a redis master-slave cluster with 5 instances. Set the pod with sequence number 2 as the master instance. If I want to perform operations to add memory to the instance, I need to expand the memory from the slave instance first, then switch the master instance. Finally, expand the memory of the original master instance.
The operation is as follows, I need to first expand the memory of the pod with the sequence number 0, 1, 3, 4, perform the operation of switching the master instance, and finally expand the memory of the pod with the sequence number 2. But now the statefulset's partition parameter can only expand the memory of 3, 4, and finally expand the memory of 0, 1, 2, but can not expand the memory of the pod less than 2, and finally expand the memory of 2.

```
pod-0    slave
pod-1    slave
pod-2    master   #Last updated, need to have a pause control before updating
pod-3    slave
pod-4    slave
```

/kind feature

**Comment by huweihuang** [comment]
@kubernetes/sig-scalability-feature-requests

**Comment by kow3ns** [comment]
We are unlikely to implement this feature in StatefulSet controller as the semantics conflict in a backward incompatible way. Also, the use case isn't general enough. We'd encourage the contribution of a community operator for Redis that orchestrates that workload specifically. Take a look at [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) if you'd like to make such a contribution.

/close
