### ISSUE TITLE
Execute command on node

### ISSUE THREAD

**Issue by omarwaleed** [kubernetes/kubernetes#72570]
**What would you like to be added**:
Ability to run command on node either directly using the kubectl command or as a configuration before scheduling a deployment/pod
**Why is this needed**:
some container like elasticsearch fail during scheduling the first time on a node because the default value for max virtual memory is below the minimum required by elastic search to run. The only solution is to run a command on the host to increase the size of the virtual memory and whenever a new node is added, the host machine has to be accessed and that command is executed before that node can schedule successfully any elastic search pods.
Plus it saves time going through ssh-ing into each node to check on something

/kind feature

**Comment by liggitt** [comment]
this can be accomplished a few different ways:
* running a daemonset on all nodes
* running a single pod targeted at a specific node
* adding a privileged initContainer to the pod that has this requirement that ensures the system is prepared for the primary container

/close

**Comment by TheOnlyWei** [comment]
@liggitt Is there a demonstration somewhere of how to achieve this? I am trying to find ways to restart services on each node. AFAIK, a container that is part of a daemonset does not have access to services of its host node.
