### ISSUE TITLE
Specify remote host for kubectl port-forward 

### ISSUE THREAD

**Issue by alexpirine** [kubernetes/kubernetes#72597]
**What would you like to be added**:

According to [the documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#port-forward), with port-forward we can specify:

```
$ port-forward TYPE/NAME --address [localhost] LOCAL_PORT:REMOTE_PORT
```

- a local port to listen on (`LOCAL_PORT` argument)
- a remote port to forward data to (`REMOTE_PORT` argument)
- a local IP address to listen on (`--address` flag)

But, the remote IP is always set to `127.0.0.1`. We can only redirect requests to the loopback interface of the pod.

This feature request suggests the possibility of specifying a remote host for port forwarding, in a similar fashion to `ssh -L LOCAL_PORT:REMOTE_HOST:REMOTE_PORT`.

This would redirect all requests to `LOCAL_PORT` to `REMOTE_HOST:REMOTE_PORT`, `REMOTE_HOST` being accessible only from the pod.

The port-forward command usage would change as follows:

```
$ port-forward TYPE/NAME [options] [LOCAL_PORT:[REMOTE_HOST:]]REMOTE_PORT [...[LOCAL_PORT_N[REMOTE_HOST_N:]:]REMOTE_PORT_N]
```

This is a backwards-compatible change.

Examples:

Listen on port 127.0.0.1:8888 locally, forwarding to 127.0.0.1:5000 in the pod

```
kubectl port-forward pod/mypod 8888:5000
```

Listen on port 127.0.0.1:8888 locally, forwarding to 1.1.1.1:5000 in the pod

```
kubectl port-forward pod/mypod 8888:1.1.1.1:5000
```

Listen on port 8888 on all addresses locally, forwarding to 2.2.2.2:5000 in the pod

```
kubectl port-forward --address 0.0.0.0 pod/mypod 8888:2.2.2.2:5000
```

**Why is this needed**:

This is very useful for debugging and providing network access to resources available from sidecar containers with some network-related functionality, such as VPN tunnels.

My own use case is an OpenVPN tunnel managed by a container, it would be very handy to proxy some requests from my development machine to the VPN (`tun0`) interface of the pod.

**Comment by alexpirine** [comment]
@kubernetes/sig-network-feature-requests

**Comment by alexpirine** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by rocketraman** [comment]
Another use case for this is when the process in the remote pod does not accept connections on the loopback interface, but only on the pod's IP:

```
tcp        0      0 10.5.3.65:9200          0.0.0.0:*               LISTEN      -
tcp        0      0 10.5.3.65:9300          0.0.0.0:*               LISTEN      -
```

In this case, a port forward does not work as it tries to connect unsuccessfully to the loopback.

**Comment by pieterdd** [comment]
`/remove-lifecycle stale`

In my case, it'd be a valuable feature because it'd let my local machine connect to an Amazon RDS database that is normally only reachable within my Kubernetes cluster. This is helpful when diagnosing issues on production when no safer/easier options are available.

**Comment by alicederyn** [comment]
If you want to forward a non-k8s-managed port and have permission to stand up a new pod, you can run the [alpine/socat] image and port-forward to that:

    kubectl run --restart=Never --image=alpine/socat TEMP_POD_NAME -- -d -d tcp-listen:PORT,fork,reuseaddr tcp-connect:HOSTNAME:PORT
    kubectl wait --for=condition=Ready pod/TEMP_POD_NAME
    kubectl port-forward pod/TEMP_POD_NAME LOCAL_PORT:PORT

Don't forget to bring the pod down once you're done.

    kubectl delete pod/TEMP_POD_NAME --grace-period 1 --wait=false

[alpine/socat]: https://hub.docker.com/r/alpine/socat/

**Comment by rustamxp** [comment]
up

**Comment by nilsonsfj** [comment]
This would be really useful for me right now. Hope the referenced MR ever goes through...

**Comment by foobarbecue** [comment]
Me too.

**Comment by erenbz** [comment]
feature is certainly needed, just has spent 6 hours debugging pod networking ending up realizing the port was just bound to interface ip addr so socat fails. maybe additional improvement would be not defaulting to 127.0.0.1 but iterating through binding list and getting first instance of port x.

**Comment by jkenefick** [comment]
This feature is not just a nice to have, it's a need to have

**Comment by velickym** [comment]
+1 feels kindda essential

**Comment by abdennour** [comment]
My use case is the following: 
- fighting against silos to make it work
- accessing api-server (192.168.x.x) is thru simple tunnel :  `ssh -N -L 6443:localhost:6443 `192.168.x.x`
- check api-server hostname from kubeconfig, and force it to resolve to localhost thru my local /etc/hosts.

Now all kubectl requests works like a charm.
But when it comes to `kubectl port-forward`, it does not work even with `--address 0.0.0.0`

- kubernetes client version: 1.17.4 
- kubernetes server version: 1.17.3

My question: Does my issue will be solved when this issue is being solved ?

**Comment by nilsonsfj** [comment]
Still need the feature.

**Comment by velickym** [comment]
Still needed.

**Comment by gitizenme** [comment]
Still needed

**Comment by A-Kamaee** [comment]
Still needed

**Comment by amitainz** [comment]
I'd like this feature too.

**Comment by knight42** [comment]
I would like to work on it.
/assign

**Comment by knight42** [comment]
hmm I think this might arise some security concerns, i.e. accidentally expose sensitive service to the outside world without any authentication. I would only continue to work on this if @kubernetes/sig-cli-maintainers confirm that this is a feature that we really want.

/unassign

**Comment by nilsonsfj** [comment]
> hmm I think this might arise some security concerns, i.e. accidentally expose sensitive service to the outside world without any authentication. I would only continue to work on this if @kubernetes/sig-cli-maintainers confirm that this is a feature that we really want.
> 
> /unassign

I find it interesting how a seemingly standard SSH feature available everywhere can spark so much uncertainty and controversy and basically be put off for almost 2 years now.

**Comment by tleish** [comment]
Based on the excellent tip from @alicederyn, I created the following local to remote port forward script through kubernetes and then auto deletes the temp pod when you are finished with the script:

```bash
#!/usr/bin/env bash

set -e

TEMP_POD_NAME=mysql-jump-server
LOCAL_PORT=3307
REMOTE_HOST=prod.abc123.region-1.rds.amazonaws.com
REMOTE_PORT=3306

function cleanup {
  echo "" 
  kubectl delete pod/$TEMP_POD_NAME --grace-period 1 --wait=false
}
trap cleanup EXIT

kubectl run --restart=Never --image=alpine/socat $TEMP_POD_NAME -- -d -d tcp-listen:$REMOTE_PORT,fork,reuseaddr tcp-connect:$REMOTE_HOST:$REMOTE_PORT
kubectl wait --for=condition=Ready pod/$TEMP_POD_NAME
kubectl port-forward pod/$TEMP_POD_NAME $LOCAL_PORT:$REMOTE_PORT
```

**Comment by Type1J** [comment]
I need this feature. I'm using the script from @tleish and @alicederyn for now, but adding this to `port-forward` would be much better.

**Comment by kunaals** [comment]
Still needed

**Comment by mlsorensen** [comment]
This would really be nice. Not all use cases bind to localhost in the pod.

As a workaround - the socat script above can also be added as a sidecar to the pod, in cases where the pod/destination IP is known or you are willing to discover it via a sidecar startup script.

**Comment by MatteoGioioso** [comment]
Any update? The socat workaround does not work for me

**Comment by Type1J** [comment]
I'm not sure if this is going to happen. If somebody made a pull request, would it be accepted?

**Comment by daniel-kun** [comment]
I also have the use case to access a database that is only accessible from the remote network.

Additionally, there is the use case to access third party APIs that use whitelisted source IP addresses, which often are only the outgoing IP addresses of the cluster. With the port-forwarding to arbitrary external hosts or IP addresses you could access those IPs from your local development machine (for troubleshooting, tests, ...).

Arguably this is of course not the core functionality of Kubernetes, but it would be pretty handy nevertheless.

For the time being, I'm using the socat-approach posted by @alicederyn (thanks Alice, btw.!)

**Comment by knight42** [comment]
Hi all! I have created a kubectl plugin [krelay](https://github.com/knight42/krelay) which is able to forward data to a specific IP or hostname. 

Although it might not fully meet the requirement described in the issue, if all you want is to forward traffic to external hosts or IP addresses that are only accessible within the cluster as described by @daniel-kun, please feel free to try it out, I think it will solve your problem. I am looking forward to your feedback!

**Comment by henrik242** [comment]
@knight42 Works perfectly! E.g. `kubectl relay host/some-pod-accessible-host 4321` forwards `some-pod-accessible-host:4321` to `localhost:4321`.

**Comment by alexpirine** [comment]
> /reopen

/reopen
