### ISSUE TITLE
can not telnet access other pods and internet

### ISSUE THREAD

**Issue by 344654931** [kubernetes/kubernetes#72609]
### access internet in busybox

    `/ # ping kubernetes.io
    PING kubernetes.io (45.54.44.102): 56 data bytes
    64 bytes from 45.54.44.102: seq=0 ttl=46 time=40.603 ms
    64 bytes from 45.54.44.102: seq=1 ttl=46 time=40.439 ms

    / # wget http://kubernetes.io
    Connecting to kubernetes.io (45.54.44.102:80)
    wget: server returned error: HTTP/1.1 404 Not Found
    `

### access pod in busybox

    `
    / # ping 10.244.1.134
    PING 10.244.1.134 (10.244.1.134): 56 data bytes
    64 bytes from 10.244.1.134: seq=0 ttl=64 time=0.211 ms
    64 bytes from 10.244.1.134: seq=1 ttl=64 time=0.049 ms

    / # wget http://10.244.1.134:8080/wx/token?code=123
    Connecting to 10.244.1.134:8080 (10.244.1.134:8080)
    wget: server returned error: HTTP/1.1 404 Not Found
    `

### can access internet in host server
`   [root@cloud-node2 ~]# wget http://kubernetes.io
    --2019-01-06 09:38:44--  http://kubernetes.io/
    Resolving kubernetes.io (kubernetes.io)... 45.54.44.102
    Connecting to kubernetes.io (kubernetes.io)|45.54.44.102|:80... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://kubernetes.io/ [following]
    --2019-01-06 09:38:44--  https://kubernetes.io/
    Connecting to kubernetes.io (kubernetes.io)|45.54.44.102|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 21959 (21K) [text/html]
    Saving to: ‘index.html.1’`
  

### can access pod in host server

    `[root@cloud-node2 ~]# wget http://10.244.1.134:8080/wx/token?code=123
    --2019-01-06 09:06:43--  http://10.244.1.134:8080/wx/token?code=123
    Connecting to 10.244.1.134:8080... connected.
    HTTP request sent, awaiting response... 500 
    2019-01-06 09:06:43 ERROR 500: (no description)`

**Comment by 344654931** [comment]
@wojtek-t

**Comment by thockin** [comment]
Are you using Istio?

This is not a systemic problem, it's a setup problem.  Github is for bugs - If this persists, please take it to slack, discuss, or stackoverflow and include details about your cloud env, network driver, and setup tools.
