### ISSUE TITLE
Kubernetes pulling docker local image in local registry faild

### ISSUE THREAD

**Issue by xdk-rachel** [kubernetes/kubernetes#72611]
Hi everyone,
I am tring to pull docker images from my local registry.
First I use `docker run -d -p 5000:5000 --restart=always --name registry registry:2` to creat a local registry.
And then I taged my image `docker tag myimage localhost:5000/myimage` and push my image `docker push localhost:5000/myimage`
But when I created it in kubernetes I got 
Failed to pull image "localhost:5000/k8sros/mqtt-kube-operator:0.1.0": rpc error: code = Unknown desc = Error response from daemon: Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: getsockopt: connection refused

Then I followed https://blog.hasura.io/sharing-a-local-registry-for-minikube-37c7240d0615 and created kube-registry by `kubectl create -f kube-registry.yaml`
but when I run `kubectl port-forward --namespace kube-system $(kubectl get po -n kube-system | grep kube-registry-v0 | \
awk '{print $1;}') 5000:5000` I got Unable to listen on port 5000: All listeners failed to create with the following errors: Unable to create listener: Error listen tcp4 127.0.0.1:5000: bind: address already in use, Unable to create listener: Error listen tcp6 [::1]:5000: bind: address already in use
error: Unable to listen on any of the requested ports: [{5000 5000}]
 Anyone has any ideas?
Thank you first 
Rachel

**Comment by figo** [comment]
if you are using minikube, then you don't have to push to registry at all, try follow this one:
https://stackoverflow.com/questions/42564058/how-to-use-local-docker-images-with-minikube

or looks like you are getting routing problem, you can quickly  run `docker pull localhost:5000/myimage` to verify instead of going through k8s.

**Comment by xdk-rachel** [comment]
> if you are using minikube, then you don't have to push to registry at all, try follow this one:
> https://stackoverflow.com/questions/42564058/how-to-use-local-docker-images-with-minikube
> 
> or looks like you are getting routing problem, you can quickly run `docker pull localhost:5000/myimage` to verify instead of going through k8s.

But I am using kubernetes cluster locally not minikube

**Comment by surajssd** [comment]
@xdk-rachel how have you setup your kubernetes cluster?

**Comment by tanshanshan** [comment]
1 . config docker use config 
"insecure-registries": ["0.0.0.0/0"],
2.  the error message is 
> bind: address already in use, 

you should kill the process which use 5000 port in this node.

**Comment by zioalex** [comment]
@xdk-rachel  please check the network. Could be that from Kubernetes you cannot reach the local registry. May be you need to forward the packet.
One simple test would be just to start a container with a public image and try to reach the port 5000 from inside.

**Comment by kostampl** [comment]
I get exactly the same error. However, if I follow the process proposed [here](https://blog.hasura.io/sharing-a-local-registry-for-minikube-37c7240d0615 ) on a Mac, it works. Could it be a OS issue? Was anyone able to solve it?
