### ISSUE TITLE
error: starting container process caused "exec: \"/opt/mqtt-kube-operator\": permission denied"

### ISSUE THREAD

**Issue by xdk-rachel** [kubernetes/kubernetes#72612]
Hi everyone,
I am trying run docker image in mu kubernetes cluster.
I created a dockerfile like this 

FROM alpine:latest
ARG CONTAINER_BINARY
COPY ./$CONTAINER_BINARY /opt/mqtt-kube-operator
WORKDIR /opt
RUN chmod +x /opt/mqtt-kube-operator
ENTRYPOINT ["/opt/mqtt-kube-operator"]

But when I run this docker image in kubernetes I got this error 
container_linux.go:265: starting container process caused "exec: \"/opt/mqtt-kube-operator\": permission denied"

Anyone has any ideas?
Thank you first
Rachel

**Comment by surajssd** [comment]
@xdk-rachel does this work fine with just docker by doing `docker run <image name>` ?
