### ISSUE TITLE
deepcopy.go:126] Failed loading boilerplate: open 

### ISSUE THREAD

**Issue by liu-xuewen** [kubernetes/kubernetes#72610]
**What happened**:

root@ubuntu:/home/liu/go/src/k8s.io/kubernetes# make
F0105 19:27:35.214411    2387 deepcopy.go:126] Failed loading boilerplate: open /home/liu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
Makefile.generated_files:152: recipe for target 'gen_deepcopy' failed
make[1]: *** [gen_deepcopy] Error 1
Makefile:523: recipe for target 'generated_files' failed
make: *** [generated_files] Error 2
root@ubuntu:/home/liu/go/src/k8s.io/kubernetes# export
declare -x CLUTTER_IM_MODULE="xim"
declare -x COMPIZ_CONFIG_PROFILE="ubuntu"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-pYsWW0IanJ"
declare -x DEFAULTS_PATH="/usr/share/gconf/ubuntu.default.path"

**What you expected to happen**:
make sucess
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by figo** [comment]
have you set your 'GOPATH' and 'GOROOT'?

**Comment by chenpfeisoo** [comment]
I met it, too
