### ISSUE TITLE
kubernetes Loadbalancer type service with AWS ,External ip is showing pending 

### ISSUE THREAD

**Issue by RajaSureshAditya** [kubernetes/kubernetes#72623]
HI Team ,
Need some help in understanding the issue ,

kubectl version:

output:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

i have created a replicaset and service for it with type LoadBalancer

kubectl get svc 

kubernetes        ClusterIP      10.96.0.1        <none>        443/TCP          24h
wildfly-service   LoadBalancer   10.108.206.206   <pending>     8080:30640/TCP   74m

i was unable to understand to whats going wrong with my service please help me with this ,i am actually block with this issue .

and my kubernetes master ec2 is having aws role to access the elasticloadbalancing

**Comment by Shnatsel** [comment]
@kubernetes/sig-aws-misc
