### ISSUE TITLE
Maintain the code for node conformance checks outside of kubeadm

### ISSUE THREAD

**Issue by rojkov** [kubernetes/kubernetes#72630]
**What would you like to be added**:

Move the code under https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/util/system to a separate package/repo.

**Why is this needed**:

The code is used by both kubeadm and test-e2e-node, but some part of the code, i.e. node checks customized with a spec file, is used in test-e2e-node only. Yet kubeadm owns it. Perhaps it makes sense to maintain the code as a separate package that kubeadm and test-e2e-node depend on, but don't own as suggested in https://github.com/kubernetes/kubernetes/pull/72455#discussion_r244972153.

@neolit123 @resouer 
/cc @kubernetes/sig-testing
/cc @kubernetes/sig-cluster-lifecycle

**Comment by rojkov** [comment]
@kubernetes/sig-testing-proposals @kubernetes/sig-cluster-lifecycle-proposals

**Comment by neolit123** [comment]
/assign @luxas @timothysc 
for comments.

**Comment by dims** [comment]
@rojkov @neolit123 wanna move it to https://github.com/kubernetes/utils ?

**Comment by neolit123** [comment]
i would leave the location decision to the assigned.
utils SGTM.

**Comment by neolit123** [comment]
/remove-lifecycle stale
we discussed this recently in the testing commons meeting, but we didn't pick a good location.
also we need to see if the docker validator can stop importing docker packages.

**Comment by neolit123** [comment]
/lifecycle frozen
xref: https://github.com/kubernetes/kubeadm/issues/1638
^ we have ongoing work here, but we need to poke sig-node for approval.

**Comment by BenTheElder** [comment]
@neolit123 was this resolved, I seem to remember it was but I wasn't involved there.

**Comment by neolit123** [comment]
yes, it was resolved.
/close
