### ISSUE TITLE
low performance to schedule pod via scheduler extender

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#72634]
**What would you like to be added**:
Improve scheduler perormence when using scheduler extender

**Why is this needed**:
We customize our cluster's schedule policy by an extender, As our cluster growe bigger and bigger, the scheduler's throughput becomes the bottleneck. when cluster's node number bigger than 1000, it seems that schedule throughput less then 10pod/s, I have made some plots to illustrate this.

![image](https://user-images.githubusercontent.com/11574918/50760172-fde21e80-12a1-11e9-88dd-2709a689c624.png)
Pic 1: cluster of 100 nodes

![image](https://user-images.githubusercontent.com/11574918/50760198-0fc3c180-12a2-11e9-8b66-a746771dea66.png)
Pic 2: cluster of 500 nodes

![image](https://user-images.githubusercontent.com/11574918/50760214-1baf8380-12a2-11e9-829e-71994855273e.png)
Pic 3: clusrer of 1000 nodes

plus: making this plot by scan pod's field: metadata.createionTimestap, status.conditions["PodScheduled"].lastTransitionTime and status.conditions["Ready"].lastTransitionTime, maybe those timestamps not accurate enough, but can indicate something roughly.

I try to figure out why it's so slow and find it mainly caused by HTTP transmission(JSON format) between extender, Both scheduler and extender need lots of time to Marshal/Unmarshal JSON as showed in flame graph blew:
![image](https://user-images.githubusercontent.com/11574918/50760785-a775df80-12a3-11e9-913b-284cffa6c930.png)
Pic 4:  flame graph of kube-scheduler when 1000 nodes

As well as my extender programer has this problem:
![image](https://user-images.githubusercontent.com/11574918/50761238-d476c200-12a4-11e9-9eb7-a364b2800193.png)
Pic 5:  flame graph of my extender process when 1000 nodes

My extender's schedule policy takes a tiny time in Predicate step from the picture above.  The payload of HTTP body is 2.24M per requst when 1000 nodes, so the JSON encode/decode could be an expensive action.

Some guys has mentioned this problem before(#60697, #59980), Is there any effort have we mad? or some workarounds?  or some advise I can work for?

**Comment by gaorong** [comment]
I have tried `json-iterator` and many other packages without the use of reflection such as easyjson, but all of them are helpless. 

Cloud you please tell me where can I track the process/schedule of refactoring?

**Comment by wgliang** [comment]
@gaorong 
FYI:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduling-framework.md
https://github.com/kubernetes/kubernetes/issues/68951

**Comment by gaorong** [comment]
> can you import default scheduler, and register your algorithm?

Yes, It seems to be the only choice before ready of the framework.

**Comment by k82cn** [comment]
> Yes, It seems to be the only choice before ready of the framework.

As golang did not support dynamic lab, you may also do this for performance with framework; for the "import default scheduler" , I means taking default scheduler as third-party package by godep/dep; instead of modifying it directly :)

**Comment by gaorong** [comment]
@k82cn Thanks for reminding, I'll have a try.

**Comment by misterikkit** [comment]
> import default scheduler, and register your algorithm

This use case is being targeted by the scheduling framework design, where you can add `k8s.io/kubernetes/pkg/scheduler` to your `vendor` folder and add your own plugins. I don't have a good time estimate on that aspect yet.
