### ISSUE TITLE
Docs: Add legend to the PV Access Modes table

### ISSUE THREAD

**Issue by gazoo4** [kubernetes/kubernetes#72640]
**What would you like to be added**:
I'd like to ask to add a legend to the [table](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) listing the supported storage drivers and access modes.
**Why is this needed**:
It's not clear how to read the current legend (e.g. supported/not-supported, recommended/not-recommended,...?). Came to the surface while having a dispute in the team how this table should be understood.

**Comment by gazoo4** [comment]
@kubernetes/sig-docs-feature-requests

**Comment by liggitt** [comment]
thanks for the report, please open docs issues against https://github.com/kubernetes/website/issues so they can be routed to the right team

/close
