### ISSUE TITLE
Kubernetes OSS oncall should be "paged" when CI build or e2e tests break

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#7264]
This needs to happen during the common merge window (7:00 am Monday to 5:00 pm (17:00h) Friday, Pacific Time).

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/collab.md

It is much easier to locate the merged PR causing the breakage if it is tracked down very soon after the merge.

**Comment by roberthbailey** [comment]
A failed run for GCE is already advertised to the IRC channel, which should be monitored by the oncall. Maybe we can figure out a way for Jenkins to send an email or chat message that gets routed properly as well?

**Comment by ihmccreery** [comment]
@krousey Based on your experience, I believe this is done.  Closing; reopen if not.
