### ISSUE TITLE
Flaky Test "In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support non-existent path"

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#72661]
**Which jobs are failing**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=In-tree%5CsVolumes%5Cs%5C%5BDriver%3A%5Csnfs%5C%5D%5Cs%5C%5BTestpattern%3A%5CsDynamic%5CsPV%5Cs%5C(default%5Csfs%5C)%5C%5D%5CssubPath%5Csshould%5Cssupport%5Csnon-existent%5Cspath

**Which test(s) are failing**:
In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support non-existent path 1m14s

**Since when has it been failing**:
Unknown

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/33667

**Reason for failure**:
Unknown

/sig storage
/assign

**Comment by davidz627** [comment]
Error looks like: 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:210
Expected error:
    <*errors.errorString | 0xc00173f080>: {
        s: "expected \"content of file \\\"/test-volume/volumes-1310/test-file\\\": mount-tester new file\" in container output: Expected\n    <string>: content of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retryingcontent of file \"/test-volume/volumes-1310/test-file\": \n    Unexpected content. Expected: mount-tester new file\n    . Retrying\n    \nto contain substring\n    <string>: content of file \"/test-volume/volumes-1310/test-file\": mount-tester new file",
    }
    expected "content of file \"/test-volume/volumes-1310/test-file\": mount-tester new file" in container output: Expected
        <string>: content of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retryingcontent of file "/test-volume/volumes-1310/test-file": 
        Unexpected content. Expected: mount-tester new file
        . Retrying
        
    to contain substring
        <string>: content of file "/test-volume/volumes-1310/test-file": mount-tester new file
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2426
```

**Comment by davidz627** [comment]
Observing interesting behavior. Some key takeaways:
This error seems to only crop up on NFS tests and it happens on more than one NFS test:
Only NFS for a certain test: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=subPath%5Csshould%5Cssupport%5Csnon-existent%5Cspath#ee5b59bbddd57729881f
A different test but for NFS: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/33440
this seems to imply that this failure has something to do with NFS specific behavior.

With further investigation into the actual binary that is being run in the test we can see that the "write container" is opening, writing, then closing a file (successfully), then immediately opening, reading, closing, and verifying the file contents (successfully) <- implied from no failure logs. So from the "write container"'s perspective all seems well.

However, as we see the failure messages from the "read container" which is a separate container acting as a separate NFS client. It seems that the "read container" is able to open the file (the file exists) and yet reads no data from the file. This is a strange state since the "write container" creates and writes the file in a fairly atomic manner (using `ioutil.WriteFile`) and even validates the file by reading it back right afterwards without error (using `ioutil.ReadFile`).

The current theory is that there is some sort of sync/flush slowness or issue with NFS. 

I do not have enough domain knowledge to rule out anything since im not sure how data/metadata flushes work with NFS (whether it is possible metadata [file existing] can be flushed while data [file contents] are not for such a significant period of time [20 seconds]).

Based on some reading done on section 5.9 of http://nfs.sourceforge.net/nfs-howto/ar01s05.html, next steps are to attempt to reproduce the error, and if I am able to, then to run the containers again but opening the file with `O_SYNC` to see if that fixes the issue. Seems like NFS is by default async and that may explain this issue?

/cc @msau42 @gnufied

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by jsafrane** [comment]
NFS man page says that close() should be enough to flush data to the server:

       The  NFS client treats the sync mount option differently than some other file systems (refer to mount(8) for a description of the generic sync and async mount options).  If neither sync nor async is specified (or if the async option is specified), the NFS client delays sending application writes to the
       server until any of these events occur:

              Memory pressure forces reclamation of system memory resources.

              An application flushes file data explicitly with sync(2), msync(2), or fsync(3).

              An application closes a file with close(2).

              The file is locked/unlocked via fcntl(2).

I don't know how it could be possible that a file is not available on another NFS client.

Perhaps we could schedule reader pod to the same node as the writer to work around the problem?

**Comment by msau42** [comment]
Reader and writer containers are in the same pod

**Comment by davidz627** [comment]
As another data point: I have now run the test by itself on a personal e2e cluster 1810 times without a single flake.

**Comment by wongma7** [comment]
https://github.com/kubernetes/kubernetes/pull/73318 should mitigate this as it forces the read container to start after write container. In short, this is an nfs-ganesha bug when read/write happens at the same time. (I opened https://github.com/kubernetes/kubernetes/pull/73318 for another issue, writer container starting 10s after reader container, but it should help here anyway).

Note how it's only the dynamic tests failing, i.e. nfs provisioner with nfs-ganesha backend. What's happening is something like: in container 1 (writer), ioutil.WriteFile creates the empty file, container 2 (reader) Opens the file, container 1 Writes "mount-tester new file" but container 2 has it Open and its contents is "" so ??? and ultimately the file ends up on server-side as "" instead of "mount-tester new file." Something is wonky with nfs-ganesha's caching or locking or whatever.

I can reproduce on an nfs ganesha mount quite easily with this script, about 1/10 runs the writer will read back the file `content of file "/nfsganeshamount/asdf_9": ""` right after it was supposed to have written "mount-tester new file" with no error

```
for x in (seq 9)
  go run $HOME/go/src/k8s.io/kubernetes/test/images/mounttest/mt.go --file_content_in_loop=/nfsganeshamount/asdf_$x --retry_time=20 & go run $HOME/go/src/k8s.io/kubernetes/test/images/mounttest/mt.go --new_file_0644=/nfsganeshamount/asdf_$x 
  sleep 1
end
```

I am not sure why it is hard to reproduce on a personal e2e cluster.

I'll try to resolve it with ganesha upstream. Anyway, it is not a requirement that we use nfs-provisioner+nfs-ganesha for dynamic nfs e2e tests, I'm sure something based on the better-tested kernel nfs could be hacked together also, have had that on my TODO for a while.

**Comment by msau42** [comment]
great find! Is it possible to change our nfs provisioning tests to use nfs-client instead?

**Comment by wongma7** [comment]
Probably, another option is to mount ganesha shares with `-o nfsvers=3`.

**Comment by wongma7** [comment]
https://github.com/kubernetes/kubernetes/issues/73535 to track that created

**Comment by spiffxp** [comment]
/remove-kind failing-test
/kind flake
because it's a flake and not a continuously failing test
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by spiffxp** [comment]
This specific test case is still flaking: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=%5C%5BDriver%3A%20nfs%5C%5D.*subPath%20should%20support%20non-existent%20path

Given the lack of progress on https://github.com/kubernetes/kubernetes/issues/73535 is there anything else being done to address this?

**Comment by spiffxp** [comment]
Pretty much anything related to subPath is flaking (or otherwise failing): https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=subPath

I suspect there need to be other issues opened for this, still triaging.

/priority important-soon
I will be escalating to priority/critical-urgent if this is related to the flakes that are causing [release-master-blocking/gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default) to be nearly continuously red

**Comment by msau42** [comment]
This issue is specific tracking failures to nfs plugin.

I would open different issues if the plugin is different.

**Comment by alejandrox1** [comment]
Please correct me if I'm wrong but this issue doesn't seem related to a failure in the sig-release dashboards. I'll remove it from the CI signal project

**Comment by davidz627** [comment]
/remove-lifecycle stale
I believe this is still not resolved

**Comment by spiffxp** [comment]
/milestone clear
I don't think this is specific to v1.14
