### ISSUE TITLE
configmap volume should delete the "ready" file of the internal emptydir volume on mount failure

### ISSUE THREAD

**Issue by jmf0526** [kubernetes/kubernetes#72675]
**What happened**:
There is a node in my cluster whose disk is full on root partition, I cleared the disk and then rebooted the node to recover it. After the reboot, the kube-proxy on that node got stuck in "ContainerCreating" status and never changes, and all other pods can't run properly since the kubeproxy is not runing.

**What you expected to happen**:
Kubeproxy on that node can run normally after the disk clean and reboot

**How to reproduce it (as minimally and precisely as possible)**:
1. make the disk full on root partition
-  in my env, leave roughly 100k space on root partition would make this issue more reproducible

- this issue is kind of tricky, to reproduce it, one need to populate the disk repeatedly since some disk space would be cleared because of pod eviction

-  the kube-proxy got deleted and created repeatedly because of pod eviction and daemon-set mechanism, it would stuck in ContainerCreating status if the disk space is not enough for creating volume contents of kube-proxy configMap volume, the first pod error event is like:
_MountVolume.Setup failed for volume "kube-proxy":.....no space left on device_

- After it got stuck, the following  pod error event woud repeat over and over, kube-proxy is trying to mount configMap volume but always fail
_MountVolume.Setup failed for volume "kube-proxy": stat /var/lib/kubelet/pods/{pod_id}/volumes/kubernetes.io~configmap/kube-proxy no such file or directory_

2.clear the disk and reboot
- the reboot is neccesary to reproduce the issue, without the reboot the pod eviction would kick in to delete kube-proxy pod

3. now the kube-proxy woud stuck in ContainerCreating Status forever, restart kubelet has no effects on that, kube-proxy pod need to be mannully deleted to get recover
- kube-proxy pod can't mount  configMap volume, the following error keeps repeating
_MountVolume.Setup failed for volume "kube-proxy": stat /var/lib/kubelet/pods/{pod_id}/volumes/kubernetes.io~configmap/kube-proxy no such file or directory_

**Anything else we need to know?**:
After digging into this issue for a quite long time, i think the reason for this issue is:

The configMap volume uses emptyDir internally to create the volume directory, after the directory is created, configMap volume failed to populate it with configMap content because the disk is full, then configMap volume calls emptyDir.tearDown() to clear the temp directory.

The problem is that emptyDir uses a "ready" file under /var/lib/kubelet/pods/{podId}/plugin/..  to determine whether the directory is created or not, if the ready file is present, then it wouldn't create the directory. The tearDown method only remove the directory, it doen't remove the ready file, so after the first out of disk error, the diretory creation always get skipped, hence no such file or directory error repeat over and over.

**Environment**:
- Kubernetes version (use `kubectl version`):
v.1.11.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
cent os 7
- Kernel (e.g. `uname -a`):
- Install tools:
kubeadm
- Others:

**Comment by jmf0526** [comment]
@kubernetes/sig-storage-bugs

**Comment by ejschoen** [comment]
If it's any help, I just encountered this issue in kubelet v1.13.2 under Debian Stretch 9.5, after a restart.  I was not out of disk space.  Deleting the ready files from /var/lib/kubelet/pods/{podId}/plugins/kubernetes.io~empty-dir/wrapped_kube*/ helped.

**Comment by hickeng** [comment]
/reopen

hit this just now with the same conditions as originally described, but without a reboot.
```
kubelet[8359]: I0804 13:56:50.365133    8359 server.go:417] Version: v1.18.2-4+96f96f938adda3
```

**Comment by dmellstrom** [comment]
> If it's any help, I just encountered this issue in kubelet v1.13.2 under Debian Stretch 9.5, after a restart. I was not out of disk space. Deleting the ready files from /var/lib/kubelet/pods/{podId}/plugins/kubernetes.io~empty-dir/wrapped_kube*/ helped.

Thanks @ejschoen ! this helped me get my cluster running after all pods were evicted and clearing space alone didn't fix the issue.
