### ISSUE TITLE
Centos: network plugin is not ready: cni config uninitialized

### ISSUE THREAD

**Issue by amekawy-eu** [kubernetes/kubernetes#72680]
Hello,
I am trying to setup cluster on Centos 7 with Kube v1.13.1.
I followed the documentation: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ and created a funnel network.
But the master is stay in not ready state
[root@master ~]# kubectl get nodes
NAME     STATUS     ROLES    AGE   VERSION
master   NotReady   master   72m   v1.13.1

The master also report
Jan 08 10:02:07 master kubelet[12184]: E0108 10:02:07.831271   12184 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

[root@master ~]# ifconfig -a
cni0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.142.0.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::383f:a1ff:fed1:73e0  prefixlen 64  scopeid 0x20<link>
        ether 0a:58:0a:8e:00:01  txqueuelen 1000  (Ethernet)
        RX packets 1290  bytes 85028 (83.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1689  bytes 502340 (490.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:da:26:25:ba  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
        inet 10.142.0.4  netmask 255.255.255.255  broadcast 10.142.0.4
        inet6 fe80::4001:aff:fe8e:4  prefixlen 64  scopeid 0x20<link>
        ether 42:01:0a:8e:00:04  txqueuelen 1000  (Ethernet)
        RX packets 11001  bytes 21558520 (20.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 1
        TX packets 6257  bytes 782458 (764.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1410
        inet 10.142.0.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::3cdc:78ff:febc:56a6  prefixlen 64  scopeid 0x20<link>
        ether 3e:dc:78:bc:56:a6  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 8 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 695856  bytes 201748834 (192.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 695856  bytes 201748834 (192.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@master ~]#

[root@master ~]# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.142.0.1      0.0.0.0         UG        0 0          0 eth0
10.142.0.0      0.0.0.0         255.255.255.0   U         0 0          0 cni0
10.142.0.1      0.0.0.0         255.255.255.255 UH        0 0          0 eth0
10.142.0.4      0.0.0.0         255.255.255.255 UH        0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
[root@master ~]#

Joining other node fails with:
[discovery] Failed to request cluster info, will try again: [Get https://10.142.0.4:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.142.0.4:6443: i/o timeout]

the worker node can not reach even the master through normal ping anymore.
[root@node01 ~]# ping master
PING master (10.142.0.4) 56(84) bytes of data.

**Comment by amekawy-eu** [comment]
area/kubeadm  sig/network

**Comment by amekawy-eu** [comment]
/area/kubeadm /sig/network

**Comment by amekawy-eu** [comment]
@kubernetes/sig-network-bugs

**Comment by amekawy-eu** [comment]
thanks a lot for your help, i got it worked that after doing " kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml" 
I needed to restart the master node, then all works fine 👍

**Comment by noyessie** [comment]
I face the same errors and it seens that It seens that `systemd` have a problems. I'm not remember my last `systemd` version. But update it solve the problems for me.

**Comment by fanglijun** [comment]
Update systemd from `30.el7_3.9` to `67.el7_7.4` solved this.  Thanks @noyessie !

**Comment by asitha23** [comment]
Apparently With the latest Kubernetes version (v1.24) to work, you need to run the following command

```
containerd config default > /etc/containerd/config.toml
systemctl restart containerd
```
