### ISSUE TITLE
Occasional Error: read EHOSTUNREACH at TCP.onStreamRead

### ISSUE THREAD

**Issue by xiaozhongliu** [kubernetes/kubernetes#72681]
**What happened**:
Our apps rely on some GRPC services. Occasionally the following error occurs and breaks our logic.
Our apps were published in prod env recently, we've checked apps' metrics that there was neither traffic pressure nor restart whenever the error occurs.
```
{ Error: read EHOSTUNREACH
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'EHOSTUNREACH', code: 'EHOSTUNREACH', syscall: 'read' }
```

**What you expected to happen**:
Apps work normally and no EHOSTUNREACH errors.

**How to reproduce it (as minimally and precisely as possible)**:
This error occurs occasionally, no stable reproduction method... If you need any specific stuff please tell me, thanks.

**Anything else we need to know?**:
Call chain: bff api pod => kube-proxy => grpc service pod

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Alicloud
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
- Kernel (e.g. `uname -a`):
Linux iZbp11zjwu3eul74z7h4skZ 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Cloud managed
- Others: None

**Comment by danwinship** [comment]
Are the pods backing the service dying and being restarted? (eg, check the `RESTARTS` column in `kubectl get pods`. Or else are you repeatedly changing the Deployment they're part of or something like that?). Someone trying to connect to a service IP might get `EHOSTUNREACH` if the service has no pods backing it.
