### ISSUE TITLE
Add flag to show all resources referencing the current object

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubernetes#72683]
**What would you like to be added**:

A generic way to query all resources that reference the current resource via owner references.
So for example a command like `kubectl get foo/bar --references` will print all resources that reference `foo/bar`.  

**Why is this needed**:

This capability will allow better debugging for GC issues, when one resource is stucked in deletion state because it depends on other resource to be deleted. It would also help to visualize the graph that garbage collection is using and list resources that will be automatically deleted (secrets, config maps, etc...).

/sig cli

**Comment by liggitt** [comment]
for debugging GC, the graph export added to the controller manager might be a better avenue (https://github.com/kubernetes/kubernetes/pull/66623)

**Comment by liggitt** [comment]
> So for example a command like `kubectl get foo/bar --references` will print all resources that reference `foo/bar`.

this would involve discovering and listing all of every object at or below the object's scope (all resources in the same namespace for namespaced targets, all cluster-scoped and namespaced resources for cluster-scoped targets)
