### ISSUE TITLE
Refactor kube-apiserver flags into constants

### ISSUE THREAD

**Issue by Zyqsempai** [kubernetes/kubernetes#72702]
**What would you like to be added**:
Refactor all flags in kube-apiserver package into constants
example: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/options/options.go#L128
The issue is a continue of work related to those issues:
https://github.com/kubernetes/kubeadm/issues/1336
https://github.com/kubernetes/kubeadm/issues/1333

Open questions:
We have few Todo's in this package, like https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/options/options.go#L132 or https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/options/options.go#L175 can we resolve them?
We have a lot of hardcodes here https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/aggregator.go#L242 should we do something to them?

/kind cleanup
/priority important-longterm
/help-wanted

**Comment by liggitt** [comment]
/close

a package gathering command line flag names adds complexity and indirection to the code, with little benefit
