### ISSUE TITLE
Metrics-server failed to start when created with cluster/addons/metrics-server

### ISSUE THREAD

**Issue by Rajat-0** [kubernetes/kubernetes#72713]
Metrics-server failed to start with " CrashLoopBackOff " status when created with cluster/addons/metrics-server. 
It creates 2 containers (metrics-server metrics-server-nanny) in a pod. Metrics-server is working fine but Metrics-server-nanny is failing.

Container logs:-
`ERROR: logging before flag.Parse: I1230 22:30:08.280033       1 pod_nanny.go:65] Invoked by [/pod_nanny --config-dir=/etc/config --cpu={{ base_metrics_server_cpu }} --extra-cpu=0.5m --memory={{ base_metrics_server_memory }} --extra-memory={{ metrics_server_memory_per_node }}Mi --threshold=5 --deployment=metrics-server-v0.3.1 --container=metrics-server --poll-period=300000 --estimator=exponential --minClusterSize={{ metrics_server_min_cluster_size }}]
invalid argument "{{ metrics_server_min_cluster_size }}" for "--minClusterSize" flag: strconv.ParseUint: parsing "{{ metrics_server_min_cluster_size }}": invalid syntax
Usage of /pod_nanny:
      --config-dir string      Path of configuration containing base resource requirements. (default "MISSING")
      --container string       The name of the container to watch. This defaults to the nanny itself. (default "pod-nanny")
      --cpu string             The base CPU resource requirement.
      --deployment string      The name of the deployment being monitored. This is required.
      --estimator string       The estimator to use. Currently supported: linear, exponential (default "linear")
      --extra-cpu string       The amount of CPU to add per node.
      --extra-memory string    The amount of memory to add per node.
      --extra-storage string   The amount of storage to add per node. (default "0Gi")
      --memory string          The base memory resource requirement.
      --minClusterSize uint    The smallest number of nodes resources will be scaled to. Must be > 1. This flag is used only when an exponential estimator is used. (default 16)
      --namespace string       The namespace of the ward. This defaults to the nanny pod's own namespace. (default "kube-system")
      --pod string             The name of the pod to watch. This defaults to the nanny's own pod. (default "metrics-server-v0.3.1-8646846686-cwrxx")
      --poll-period int        The time, in milliseconds, to poll the dependent container. (default 10000)
      --storage string         The base storage resource requirement. (default "MISSING")
      --threshold int          A number between 0-100. The dependent's resources are rewritten when they deviate from expected by more than threshold.`

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.2
- OS (e.g. from /etc/os-release): xenial/ubuntu16.04
- Kernel (e.g. `uname -a`):  4.4.0-141-generic
- Install tools:  hack/local-up-cluster.sh
- Others: None

**Comment by danielqsj** [comment]
@Rajat-0 Have you checked this parameter `{{ metrics_server_min_cluster_size }}` ?

**Comment by xxlest** [comment]
@Rajat-0 i got same issue, have you fixed it?

**Comment by Rajat-0** [comment]
@xxlest No, I didn't tried it yet. I have deployed metrics server with [kubenetes-incubator/metric server](https://github.com/kubernetes-incubator/metrics-server/) on kube-adm and using **addons enable metrics-server** command.

**Comment by xxlest** [comment]
> @xxlest No, I didn't tried it yet. I have deployed metrics server with [kubenetes-incubator/metric server](https://github.com/kubernetes-incubator/metrics-server/) on kube-adm and using **addons enable metrics-server** command.

same with me, i used 1.8+ version to try and didn't meet this issue. finally i use  prometheus  operator to get  health index

**Comment by walwong** [comment]
same as me, I set the - --minClusterSize={{ metrics_server_min_cluster_size }}
to - --minClusterSize=16, it throw another error as above:
panic: cannot parse '{{ base_metrics_server_cpu }}': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
any comments?

**Comment by walwong** [comment]
> same as me, I set the - --minClusterSize={{ metrics_server_min_cluster_size }}
> to - --minClusterSize=16, it throw another error as above:
> ERROR: logging before flag.Parse: I0321 09:04:40.800213 1 pod_nanny.go:81] Watching namespace: kube-system, pod: metrics-server-v0.3.1-68dccbd4fc-6fsrg, container: metrics-server.
> ERROR: logging before flag.Parse: I0321 09:04:40.800238 1 pod_nanny.go:82] storage: MISSING, extra_storage: 0Gi
> ERROR: logging before flag.Parse: I0321 09:04:40.809049 1 pod_nanny.go:109] cpu: {{ base_metrics_server_cpu }}, extra_cpu: 0.5m, memory: {{ base_metrics_server_memory }}, extra_memory: {{ metrics_server_memory_per_node }}Mi
> panic: cannot parse '{{ base_metrics_server_cpu }}': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]_[-+]?[0-9]_)$'
> 
> any comments?

solved, change the configuration in the  metrics-server-deployment.yaml file "- --cpu={{ base_metrics_server_cpu }} to - --cpu=4"  #your cpu quantity
then two container in pod are running well .
