### ISSUE TITLE
Have kubelet export metric containing its own name

### ISSUE THREAD

**Issue by tomwilkie** [kubernetes/kubernetes#72715]
**What would you like to be added**:

It would be useful if the kubelet exported a metric that contained its own name as a label, for instance:

`kubelet_node_name{job="kubelet", instance="10.135.73.142:10250", name="10.135.73.142"}`.

This name should be consistent with the output of `kubectl get nodes`.

**Why is this needed**:

This would allow us to join the kubelet metrics against metrics exported by kube-state-metrics.

An example of this can be seen in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/135.  We've arranged in our cluster for the `instance` labels to be set to the node's name, but this is controlled by Prometheus and depends on your scrape & relabelling config.  As such, in general we can't rely on this to be the case - for instance, with the prometheus-operator the `instance` label is a IP:Port combo.

/cc @metalmatze @brancz

**Comment by tomwilkie** [comment]
@kubernetes/sig-instrumentation

**Comment by brancz** [comment]
This metric as it is right now doesn’t conform to the instrumentation guidelines, so yes we should changes this as part of the metrics overhaul targeted for 1.14.

**Comment by danielqsj** [comment]
@brancz you mean to add a label `node` in kubelet metrics ?
