### ISSUE TITLE
pull-kubernetes-local-e2e-containerized is failing

### ISSUE THREAD

**Issue by cadeniyi** [kubernetes/kubernetes#72726]
pull-kubernetes-local-e2e-containerized is failing and has been failing consistently since 2018-12-18

Looks like something happened between build 1648 and 1649 and the cluster is not coming up.

https://testgrid.k8s.io/conformance-all#local-up-cluster-containerized,%20master%20(dev)

**Comment by dims** [comment]
Hopefully when the following merges, it will be better

https://github.com/kubernetes/test-infra/pull/10488
https://github.com/kubernetes/test-infra/pull/10664

**Comment by dims** [comment]
@danielqsj looks like that test fails in other jobs too, lets watch it for a couple of more days to see what frequency it fails: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=should%20run%20and%20stop%20complex%20daemon

**Comment by danielqsj** [comment]
@dims sure, thanks.

**Comment by therc** [comment]
It failed five out of five times for me on https://github.com/kubernetes/kubernetes/pull/72993 yesterday

**Comment by dims** [comment]
@therc if you notice, it's not a mandatory job, which means even if this job fails fails, the PR itself is merge-able. Looks like the daemonset test is very problematic. will have to look

**Comment by dims** [comment]
https://github.com/kubernetes/test-infra/pull/10810 will ensure that all the ci/pull local-e2e jobs use the same cpu/mem so they stop timing out, then we can check if daemonset test issue happens in both local-e2e-containerized and local-e2e or just one of them.

**Comment by dims** [comment]
Logged a specific bug in https://github.com/kubernetes/kubernetes/issues/73073

**Comment by dims** [comment]
@danielqsj thanks! filed https://github.com/kubernetes/test-infra/pull/10859 for that

**Comment by dims** [comment]
one remaining issue is logged here : https://github.com/kubernetes/kubernetes/issues/73073

/close
