### ISSUE TITLE
Incorrect message in kubeadm init logs

### ISSUE THREAD

**Issue by Sagar2366** [kubernetes/kubernetes#72723]
On executing kubeadm init command 
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

in [wait-control-plane] it is showing 4m0s and in [kubelet-check] it is showing 40s passed

**Comment by paralika** [comment]
sig/cluster-lifecycle

**Comment by neolit123** [comment]
thanks for the report but this is not a bug.

there is an initial timeout for the kubelet that is much shorter than 4m0s and it's 40s.
once this passes there is still a chance that the control plane can boot up.

think of this like `kubelet-check` is a "phase" of the whole `wait-control-plane` process.

/close
