### ISSUE TITLE
[Windows] Running state skipped if the container fails fast after back off

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#72722]
**What happened**:

/sig windows
/sig testing

When using Windows Server 2019 as compute nodes, with ``azure-vnet-cni-v1.0.16-rc2`` or ``v1.0.15``, some tests are consistently failing

Affected tests:

    [k8s.io] Pods  should cap back-off at MaxContainerBackOff [Slow][NodeConformance]
    [k8s.io] Pods  should have their auto-restart back-off timer reset on image update [Slow][NodeConformance]

The tests are expecting the container to enter a ``Running`` state before entering the ``Terminated`` state (their command includes a non-existent command (``/bin/sh -c sleep 5 /crash/missing``), so the containers are expected to fail), but the Containers always transition from ``Waiting (Reason:CrashLoopBackOff)`` to ``Terminated (Reason:Completed)``.

But when using ``azure-vnet-cni-v1.0.14``, the tests no longer consistently fail; they randomly pass or fail, but when increasing the sleep period from 5 to 10 seconds as proposed by the PR https://github.com/kubernetes/kubernetes/pull/71950, the tests will consistently pass.

NOTE: this issue does not occur when using ``l2bridge`` flannel on Windows, even when the sleep period is 5 seconds.

Related issue: #71949

**What you expected to happen**:

The Container status should be updated faster, so the ``Running`` state is not omitted if the Container fails fast. The tests should then be able to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Have a deployment as described above and run the mentioned tests. Alternatively, spawn this pod and watch its Container status and its transitions ( https://paste.ubuntu.com/p/nfH7v7MZ7m/ ). After the back-off period expires, the container should enter a ``Running`` state, but it doesn't.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): "v1.13.1"
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Windows Server 2019 compute nodes, azure-vnet-cni-v1.0.16-rc2
- Kernel (e.g. `uname -a`):
- Install tools: aks-engine-v0.28.1
- Others:

**Comment by adelina-t** [comment]
cc: @PatrickLang

**Comment by PatrickLang** [comment]
Azure-CNI 1.0.16 caused some latency starting pods due to a lock contention, and 1.0.17 seems better. I still need to write tests to debug this further

**Comment by PatrickLang** [comment]
I'm gathering investigation details here https://gist.github.com/PatrickLang/b49f85e91dcf990f92e90f30e245b330

**Comment by xmudrii** [comment]
Hello,

I'm a bug triage shadow and I'd like to remind that code freeze is coming in 3 days (Friday, 8th March). :snowflake: :mountain_snow: Is it still planned for this issue to be fixed for 1.14?

**Comment by bclau** [comment]
Yes. It is addressed by: https://github.com/kubernetes/kubernetes/pull/71950

**Comment by bclau** [comment]
The PR https://github.com/kubernetes/kubernetes/pull/71950 merged, so this should be ok now.
