### ISSUE TITLE
not obvious (or possible) how to use an editor with spaces in the command

### ISSUE THREAD

**Issue by jtnord** [kubernetes/kubernetes#72734]
I was trying to use a different editor than notepad on windows to be used by `kubectl edit foobar` by setting the `EDITOR` environment variable.

Doing this was non trivial and the following did not work all resulting in different errors.

**What happened**:

```
win-box > set EDITOR="c:\Program Files\notepad2\Notepad2.exe"
win-box > kubectl edit foo/bar
'\"c:\Program Files\notepad2\Notepad2.exe\"' is not recognized as an internal or external command,
operable program or batch file.
error: there was a problem with the editor "cmd /C \"c:\\Program Files\\notepad2\\Notepad2.exe\" "

win-box > set EDITOR=c:\Program Files\notepad2\Notepad2.exe
win-box > kubectl edit foo/bar
'c:\Program' is not recognized as an internal or external command,
operable program or batch file.
error: there was a problem with the editor "cmd /C c:\\Program Files\\notepad2\\Notepad2.exe "

win-box > set EDITOR=c:\Program^ Files\notepad2\Notepad2.exe
win-box > kubectl edit foo/bar
'c:\Program' is not recognized as an internal or external command,
operable program or batch file.
error: there was a problem with the editor "cmd /C c:\\Program Files\\notepad2\\Notepad2.exe "
```

**What you expected to happen**:

I should be able to use normal windows paths, either by quoting them, or not.

the workaround is to use a short filename `set EDITOR=c:\progra~1\notepad2\notepad2.exe` however short paths are optional and may not always be created.  ([reference](https://support.microsoft.com/en-gb/help/121007/how-to-disable-8-3-file-name-creation-on-ntfs-partitions))

**How to reproduce it (as minimally and precisely as possible)**:

try and set an editor on windows where there is a space in the name of the command.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.10.3
- Cloud provider or hardware configuration:
N/A this is client side issue
- OS (e.g. from /etc/os-release):
windows 10 1803 
- Kernel (e.g. `uname -a`):
:-)
- Install tools:
- Others:

**Comment by mycall** [comment]
In case anyone wants an answer, it needs two things:
1. Put Notepad2.exe (or code.exe) into system PATH environment variable
2. set EDITOR=notepad2 -w
   (or EDITOR=code -w)

**Comment by oldium** [comment]
Currently there is no way how to pass path with spaces on Windows cmd.exe with `EDITOR` or `KUBE_EDITOR` environment variables. Pull Request #112104 addresses this issue. With the fix, you would be able to specify the following:

```cmd
set KUBE_EDITOR="C:\Program Files\Notepad++\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
```

and when `C:\Program Files\Notepad++` is in your `PATH`, you could do as well:

```cmd
set KUBE_EDITOR="notepad++.exe" -multiInst -notabbar -nosession -noPlugin
```

or (this is current workaround for the problem)

```cmd
set KUBE_EDITOR=notepad++.exe -multiInst -notabbar -nosession -noPlugin
```
