### ISSUE TITLE
Resource Quota test with uninitialized pod fails

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#72742]
**Which jobs are failing**:

Unknown.

**Which test(s) are failing**:

    [Feature:Initializers] should create a ResourceQuota and capture the life of an uninitialized pod.

**Since when has it been failing**:

Unknown.

**Testgrid link**:

Unknown

**Reason for failure**:

``INFO: expect err to be timeout error, got Pod "too-large-pod" is invalid: metadata.initializers.pending[0].name: Invalid value: "unhandled": should be a domain with at least three segments separated by dots``

Even after that particular issue is fixed, the test continues to fail at the step when creating a Pod with an Initializer which exceeds the Resource Quota:

``INFO: expect err to be timeout error, got pods "too-large-pod" is forbidden: exceeded quota: t
est-quota, requested: cpu=1100m, used: cpu=0, limited: cpu=1``

Additionally, in my case, the 30 seconds wait for the Resource Quota to be updated is not always enough, which causes the test to sometimes timeout.

**Anything else we need to know**:

/sig testing

**Comment by krmayankk** [comment]
@bclau  which test is failing ? is this from PR or a UT or integration ?

**Comment by bclau** [comment]
@krmayankk The test is mentioned in the description: ``[Feature:Initializers] should create a ResourceQuota and capture the life of an uninitialized pod.``, which is an e2e test.

**Comment by bsalamat** [comment]
Also, resource quota tests are very flaky in our upgrade tests:
https://k8s-testgrid.appspot.com/sig-release-1.12-all#gke-gci-1.11-gci-1.12-upgrade-master

cc/ @vikaschoudhary16

**Comment by bsalamat** [comment]
Some of the tests also fail in other setups, such as:
https://k8s-testgrid.appspot.com/sig-release-1.12-all#gke-cos-1.12-default
https://k8s-testgrid.appspot.com/sig-release-1.13-all#gke-cos-1.13-default

In all the failures, logs similar to the ones below are seen:

```
STEP: Building a namespace api object, basename resourcequota
STEP: Waiting for a default service account to be provisioned in namespace
[It] should create a ResourceQuota and capture the life of a configMap.
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/resource_quota.go:367
STEP: Creating a ResourceQuota
STEP: Ensuring resource quota status is calculated
Jan 10 22:28:28.246: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:29.851: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:31.851: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:33.854: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:35.863: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:38.008: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:39.933: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:41.940: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:43.856: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:45.892: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:47.850: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:49.851: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:51.850: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:53.966: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:55.851: INFO: resource resourcequotas, expected 1, actual 2
Jan 10 22:28:55.891: INFO: resource resourcequotas, expected 1, actual 2
[AfterEach] [sig-scheduling] ResourceQuota
```

It looks like there are changes in new versions of the clusters that breaks the assumptions of the tests.

**Comment by bclau** [comment]
It seems the test was removed by https://github.com/kubernetes/kubernetes/commit/17aa60686ebe5fd04b4fe6f442dc36a8d70b6730 for some reason.

**Comment by yliaog** [comment]
metadata.initializers is alpha, and is decided to be deprecated, and removed.

**Comment by liggitt** [comment]
the alpha initializers feature has been removed

/close
