### ISSUE TITLE
initOpCache is not skipping undeletable resource in namespaced_resources_deleter

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#72758]
**What happened**:
In initOpCache:

```
                        if !verbs.Has("delete") {
                                klog.V(6).Infof("Skipping resource %v because it cannot be deleted.", gvr)
                        }
```
The execution doesn't continue with the next resource in the for loop which starts on line 182.

**What you expected to happen**:

The resource should be skipped but it seems the resource is handled as if the verb check doesn't exist.

**How to reproduce it (as minimally and precisely as possible)**:

Found the issue during code inspection.

**Anything else we need to know?**:

None

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@kubernetes/sig-contributor-experience-bugs

**Comment by idealhack** [comment]
Thanks for reporting this!

You can link to the code block like this: https://github.com/kubernetes/kubernetes/blob/bd5a4ccfc3d3e0cfa1a9099180526c2237aabec8/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L186-L188

By looking at the `OWNERS` file, we'd better let sig-api-machinery know about this.

/sig api-machinery
@kubernetes/sig-api-machinery-bugs

**Comment by tedyu** [comment]
ping @derekwaynecarr @smarterclayton

**Comment by smarterclayton** [comment]
The code is confusing since it looks like it's adding things to the list, but it's really just priming a cache.  The real check is:

```
	deletableResources := discovery.FilteredBy(discovery.SupportsAllVerbs{Verbs: []string{"delete"}}, resources)
```

in deleteAllContent
