### ISSUE TITLE
Document/cleanup the kubernetes.io/cluster-service='true' label

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubernetes#72757]
The `kubernetes.io/cluster-service: "true"` label is sprinkled across over 100 yaml files in the kubernetes repo (according to github search). However, I could not find any documentation around the effect of this label.

After searching the code base, it seems that:
1. The label was being used by the addon manager in the past, but it has since been deprecated.
2. The `kubectl cluster-info` command seems to be the only place where this label is used in the code. It is used to display the addresses of the services that contain this label.

Would it make sense to document this label, and also cleanup the instances of this label that exist on manifests that are not `kind: Service`?

/kind cleanup
/kind docs

**Comment by neolit123** [comment]
/remove-kind feature
/kind documentation
/sig cluster-lifecycle

> The kubernetes.io/cluster-service: "true" label is sprinkled across over 100 yaml files in the kubernetes repo (according to github search). However, I could not find any documentation around the effect of this label.

previously the addons had documentation about the label:
https://github.com/kubernetes/kubernetes/blob/05ce0506f87f727fbadf0fc753a7af7c6675038a/cluster/addons/README.md

but it was removed as the label is deprecated..

> Would it make sense to document this label, and also cleanup the instances of this label that exist on manifests that are not kind: Service?

since it's deprecated i don't think we should document it, but yes the YAMLs need a cleanup.

cc @MrHohn

**Comment by MrHohn** [comment]
> The kubectl cluster-info command seems to be the only place where this label is used in the code. It is used to display the addresses of the services that contain this label.

This is also what I found about this label. @kubernetes/sig-cli-maintainers is this label documented somewhere with `kubectl`?

**Comment by war-turtle** [comment]
@alexbrand @neolit123  @MrHohn 
I think this issue should be marked with help-wanted and good-first-issue

**Comment by spiffxp** [comment]
>The `kubectl cluster-info` command seems to be the only place where this label is used in the code. It is used to display the addresses of the services that contain this label.

OK so why are we removing this label if there is a command that uses it?  Is the command deprecated?  If not, how will this command accomplish the same level of functionality today?

**Comment by neolit123** [comment]
the code in kubectl is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/clusterinfo/clusterinfo.go#L94

this label was deprecated, therefor it seems appropriate to start removing the label from manifests, and eventually the related parts of the `kubectl cluster-info` command too.

but we are hitting some deprecation policy question marks here related to the command and @kubernetes/sig-cli-maintainers should decide on the way forward.

**Comment by ialidzhikov** [comment]
As far I see `kubectl cluster-info` uses `kubernetes.io/cluster-service` for only `kind: Services`.
Why all of the related PRs for removing of the label from non `kind: Service` manifests are on hold?

**Comment by ialidzhikov** [comment]
We should reopen this one as it was closed by one of the PR that cleaned some addons. Still there are more addons to be cleaned up and maybe we still need the documentation on kubectl side for the `kubectl cluster-info`usage of `kubernetes.io/cluster-service`. 
@kubernetes/sig-cli-maintainers , wdyt?

**Comment by bowei** [comment]
We remove the usage of this label from the addon manager first, then after that proves to be successful, remove the label.
Removing the label while keeping the addon code feels like the wrong order.

**Comment by ialidzhikov** [comment]
> We should remove the usage of this label from the addon manager first, then after that proves to be successful, remove the label.
> Removing the label while keeping the addon code feels like the wrong order.

Hmm, I don't see it as hard requirement. Since more than 2 years (more than 8 k/k minor releases) the kube-addon-manager supports both `kubernetes.io/cluster-service: "true"` and `addonmanager.kubernetes.io/mode: Reconcile/EnsureExists`. I believe that the master branch should always point to the latest and should not contain any deprecated things. Users running really legacy version of kube-addon-manager can always checkout older tags in git/github for appropriate addon manifests. In this way we will prevent new users to get manifests with the deprecated label.
@bowei WDYT?

**Comment by neolit123** [comment]
this still seems viable; cluster-lifecycle no longer maintains the addons YAMLs.
also PRs are welcome.

/remove-lifecycle rotten
/remove-sig cluster-lifecycle

**Comment by frittentheke** [comment]
> /assign

I suppose this should not go stale then?

**Comment by frittentheke** [comment]
> /assign

@cheftako  

I suppose this should not go stale then?
