### ISSUE TITLE
Report CPU usageNanoCores for pods/containers in summary API on Windows

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#72788]
Related: #62047

On Windows, kubelet reports only the cumulative`usageCoreNanoSeconds` for cpu usage.
```
    "containers": [                                                                                                             
     {                                                                                                                          
      "name": "foo",                                                                                                         
      "startTime": "2019-01-09T23:26:05Z",                                                                                      
      "cpu": {                                                                                                                  
       "time": "2019-01-10T01:02:31Z",                                                                                          
       "usageCoreNanoSeconds": 25156250000                                                                                      
      },
```

On Linux, kubelet reports both `usageCoreNanoSeconds` and the instantaneous `usageNanoCores`.
```
    "containers": [
     {
      "name": "foo",
      "startTime": "2019-01-09T23:18:42Z",
      "cpu": {
       "time": "2019-01-10T01:08:29Z",
       "usageNanoCores": 2825438,
       "usageCoreNanoSeconds": 19549406996
      },
```

Although In the future, most components/monitoring pipelines will switch to using the cumulative metrics, a few features still depend on the instantaneous `usageNanoCores` metrics today. Examples are: `kubectl top`, HPA/VPA. Kubelet should report this metrics on Windows to support the existing features.

/cc @dashpole, who explained to me what features depend on the cpu metrics.
/cc @kubernetes/sig-windows-feature-requests @PatrickLang @feiskyer 
/cc @pjh @mtaufen

**Comment by PatrickLang** [comment]
@feiskyer - is this something that's clear enough in the CRI layer that you can implement it, or do we need to fix that first?

**Comment by PatrickLang** [comment]
@yujuhong do you have any notes or a doc you can point to that better describes what features depend on which metrics? It would be good for us to share and see if anything other than `kubectl top` is broken

**Comment by dashpole** [comment]
The horizontal and vertical pod autoscalers also depend on the [resource metrics api](https://github.com/kubernetes/metrics#resource-metrics-api)

**Comment by yujuhong** [comment]
Documentation on metrics API and metrics server (i.e., the aggregator): https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/

The metrics-server pod keeps spewing errors like this:
```
unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:e2e-test-yjhong-minion-windows-group-7gg8...
```
Running `kubectl top pod`:
```console
# Against a Linux pod
$ kubectl top pod ubuntu
NAME      CPU(cores)   MEMORY(bytes)   
ubuntu    0m           0Mi    

# Against a Windows pod
$ kubectl top pod foo-server
Error from server (NotFound): podmetrics.metrics.k8s.io "default/foo-server" not found
```
I haven't verified whether pod autoscaling works in my cluster, but I assume they won't since metrics server seems to discard the metrics from the windows pods.

> @feiskyer - is this something that's clear enough in the CRI layer that you can implement it, or do we need to fix that first?

I believe the implementation is in kubelet (for the docker integration), so this should not need CRI changes.

**Comment by jamesjmurtagh** [comment]
I think this is generally an issue for non-Docker CRIs. The kubelet source code suggests that these metrics will be gathered from the CRI (if the CRI is not Docker). The struct that kubelet expects returned from the ContainerStats RPC does not include usageNanoCores.

Does this mean that, until this is resolved, custom CRIs are unable to satisfactorily report metrics to the 'metrics-server'?

**Comment by PatrickLang** [comment]
@feiskyer - are you able to work on this?

**Comment by dashpole** [comment]
@jamesjmurtagh that is a good point.  For CRI runtimes, the kubelet should calculate the average over 10s to produce this metric.

**Comment by yujuhong** [comment]
> @jamesjmurtagh that is a good point. For CRI runtimes, the kubelet should calculate the average over 10s to produce this metric.

Good point. We designed CRI around core metrics API, but some CRI runtimes have integrated with cadvisor directly to fill the gap while we wait for core metrics API.
I think it's reasonable for kubelet to do this on behalf of all CRI runtimes. I spoke to @dashpole offline, and this would probably require no more than 2-day of work. 

If sig-windows (e.g., @feiskyer) can pick this up, that'd be great. @dashpole has agreed to review the changes (thanks!)
If not, we should clear document that this is not supported in Windows GA for 1.14.

**Comment by michmike** [comment]
thanks for the update. we will wait to hear back from @feiskyer

**Comment by feiskyer** [comment]
Currently, `usageCoreNanoSeconds` is got from docker's stats API on Windows. From docker stats API [here](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/docker/docker/api/types/stats.go#L23), only `TotalUsage` is available, hence `usageNanoCores` is not set on Windows:

https://github.com/kubernetes/kubernetes/blob/8b98e802eddb9f478ff7d991a2f72f60c165388a/vendor/github.com/docker/docker/api/types/stats.go#L18-L40

@PatrickLang @michmike Do you know any way to get `usageNanoCores` for Windows containers?

**Comment by jamesjmurtagh** [comment]
> @PatrickLang @michmike Do you know any way to get instantaneous `usageNanoCores` for Windows containers?

@feiskyer  I think this is broader than just a Windows issue. Officially supported tools such as the kubernetes metrics-server expect the `usageNanoCores` field, but custom CRIs that conform to the interfaces defined in the `kubelet/apis/cri/runtime` package are not given the liberty to return this value.

#72803

**Comment by yujuhong** [comment]
@dashpole suggested previously to cache the stats temporarily and compute the stats using the diff. David, could you chime in on how this could be done?

> @feiskyer I think this is broader than just a Windows issue. Officially supported tools such as the kubernetes metrics-server expect the `usageNanoCores` field, but custom CRIs that conform to the interfaces defined in the `kubelet/apis/cri/runtime` package are not given the liberty to return this value.

Yes, this was mentioned in the previous comments too. There are plans to transition those components off this field, but it's WIP. We are looking for a workaround in kubelet for now.

**Comment by michmike** [comment]
my biggest worry is that if we say this impacts the horizonal POD autoscaler, how is that passing in our end2end and conformance tests?

**Comment by yujuhong** [comment]
> my biggest worry is that if we say this impacts the horizonal POD autoscaler, how is that passing in our end2end and conformance tests?

Do you test HPA? It's not part of conformance, and I doubt this is included in windows testing.

**Comment by dashpole** [comment]
As to how this could be done, in [pkg/kugelet/stats/cri_stats_provider.go:ListPodStats()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/stats/cri_stats_provider.go#L78) and 
 [ListPodCPUAndMemoryStats()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/stats/cri_stats_provider.go#L178) we could just add a `map[string]*runtimeapi.CpuUsage` in the `criStatsProvider` struct, which we assign the previous CpuUsage metric for each container.  Then, when we need to calculate the rate, we pass the previous CpuUsage along with the current one to `makeContainerStats`, and calculate a rate based on the timestamp and values.

**Comment by alankm** [comment]
> As to how this could be done, in pkg/kugelet/stats/cri_stats_provider.go:ListPodStats() and
ListPodCPUAndMemoryStats() we could just add a map[string]*runtimeapi.CpuUsage in the criStatsProvider struct

I've done some tinkering on this myself and I originally thought that it would be as simple as that. It gets much more complicated when you have to work in between the existing cAdvisor-based logic. I assume the intent is to cut it out entirely eventually, but the information passed through the CRI doesn't even come close to being so comprehensive. 

So far I've found that this approach fixes the problem for the "/stats/summary" api, but not necessarily for the other apis. In particular, "/stats/container" seems to be completely based on cAdvisor, being completely unimpacted by the changes we made to those two functions. Some monitoring tools and metrics scrapers rely on the "/stats/container" api for their metrics, which means it is insufficient to update one api without doing the other.

**Comment by dashpole** [comment]
> the information passed through the CRI doesn't even come close to being so comprehensive.

We don't need to fill in everything in the summary API, just "usageNanoCores".

> So far I've found that this approach fixes the problem for the "/stats/summary" api, but not necessarily for the other apis. In particular, "/stats/container" seems to be completely based on cAdvisor, being unimpacted by the changes we made to those two functions. Some monitoring tools and metrics scrapers rely on the "/stats/container" api for their metrics, which means it is insufficient to update one api without doing the other.

The "/stats/summary" api is the one used by the metrics server, which is why we care about it in this case.  The "/stats/container" isn't something we need to implement to support this.

**Comment by michmike** [comment]
> > my biggest worry is that if we say this impacts the horizonal POD autoscaler, how is that passing in our end2end and conformance tests?
> 
> Do you test HPA? It's not part of conformance, and I doubt this is included in windows testing.

we added a couple of tickets to validate if HPA works. My guess is that it works for memory and not for CPU metrics because of this issue. 

If this is complicated to fix, i wonder if waiting for the CRI containerD changes in windows would be the best option for supporting this.

**Comment by feiskyer** [comment]
Sorry the for late response. HPA is actually working for Windows containers. e.g. in my cluster (v1.12.5), cpu-based HPA is working as expected:

```sh
$ kubectl describe hpa
Name:                                                  iis
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 01 Feb 2019 16:40:51 +0800
Reference:                                             Deployment/iis
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (0) / 50%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       5 current / 5 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:
  Type    Reason             Age    From                       Message
  ----    ------             ----   ----                       -------
  Normal  SuccessfulRescale  8m42s  horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  8m27s  horizontal-pod-autoscaler  New size: 5; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  6m42s  horizontal-pod-autoscaler  New size: 7; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  57s    horizontal-pod-autoscaler  New size: 5; reason: All metrics below target
```

@yujuhong Which version of kubernetes are you referring for HPA issues?

**Comment by dashpole** [comment]
@feiskyer are you running heapster, or the metrics server to serve HPA?  Heapster uses the cumulative metric, but the metrics-server uses the 10 average rate metric.

**Comment by feiskyer** [comment]
See #73659 .
