### ISSUE TITLE
Allow custom DNS and IP SANs for kubelet TLS bootstrapping CSR

### ISSUE THREAD

**Issue by zacharya** [kubernetes/kubernetes#72790]
**What would you like to be added**: It would be nice for kubelet to be able to accept custom DNS and IP SANs in `bootstrap-kubeconfig` for use when generating the CSR for TLS bootstrapping

**Why is this needed**: Currently the metrics server has to be run in insecure mode if you're using TLS bootstrapping

**Comment by zacharya** [comment]
It looks like currently, the bootstrap process just ignores the DNS and IP SAN parameters in client-go:
https://github.com/kubernetes/client-go/blob/bfc2f811739f7d4171a4e0af9f7833c6ff197fbb/util/cert/csr.go#L30-L38
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/certificate/bootstrap/bootstrap.go#L323

A possible approach might be adding options to the bootstrap kubeconfig:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L58

I'm happy to submit a PR if the enhancement is approved and the approach is agreed upon.

**Comment by liggitt** [comment]
If you want control over the hostnames for your kubelet, you can:
1. run with --cloud-provider=external and TLS cert rotation enabled
2. set the hostname or IP or DNS addresses on the Node API object

When run with external cloud provider, the kubelet will request serving certs for whatever addresses are set into its Node object's status

**Comment by zacharya** [comment]
Ok, thanks for the follow up.  This seems to be an issue brought about by our specific setup and not by the bootstrapping process itself.
