### ISSUE TITLE
Add CPU threshold for eviction

### ISSUE THREAD

**Issue by ping035627** [kubernetes/kubernetes#72799]
**What would you like to be added**:
I want to add CPU threshold for eviction.

**Why is this needed**:
I don't know why there is no CPU threshold in eviction threshold, I think we should add CPU threshold for eviction.

**Comment by ping035627** [comment]
@derekwaynecarr @vishh @dchen1107

**Comment by vishh** [comment]
xref #42910
Why do you need CPU usage based evictions?

**Comment by ping035627** [comment]
Sometimes cpu is too high, I think we should evict some pod to ensure the node normal.
