### ISSUE TITLE
Kubelet stats summary missing usageNanoCores

### ISSUE THREAD

**Issue by jamesjmurtagh** [kubernetes/kubernetes#72803]
It seems that the [metrics-server](https://github.com/kubernetes-incubator/metrics-server) expects to find 'usageNanoCores' included in the CPU metrics data for containers, returned by the CRI remote procedure call, "ListContainerStats". By kubelet's definitions, ListContainerStats returns an object that does not include this field.

As a result, I'm having difficulties satisfying the requirements of the metrics-server with my own CRI. Should the provided and expected data be consistent across these two projects? 
[Related issue.](https://github.com/kubernetes-incubator/metrics-server/issues/172)

**Comment by jamesjmurtagh** [comment]
@kubernetes/sig-instrumentation-proposals

**Comment by dmolik** [comment]
I believe this is still an issue. Here is the link back kubernetes-incubator/metrics-server#172
@mrunalp
I'll dig into this some more in the next 24 hours or so

**Comment by dmolik** [comment]
so the pod reports the nanoCores, but they are still missing at the container level

**Comment by jamesjmurtagh** [comment]
> so the pod reports the nanoCores, but they are still missing at the container level

Yep, that's what I'm seeing (when using a CRI other than Docker).

**Comment by PatrickLang** [comment]
/sig node

Adding node since this involves CRI changes

**Comment by jamesjmurtagh** [comment]
/reopen

What's the status on this? I haven't seen any indicators that this has been addressed.
Sorry if I've misused the 'reopen' command.
