### ISSUE TITLE
why cgroup not created during kubelet start

### ISSUE THREAD

**Issue by ztewyk** [kubernetes/kubernetes#72808]
cgroup created during container start:
in kubernetes/pkg/kubelet/cm/container_manager_linux.go
func (cm *containerManagerImpl) createNodeAllocatableCgroups() error {
	cgroupConfig := &CgroupConfig{
		Name: cm.cgroupRoot,
		// The default limits for cpu shares can be very low which can lead to CPU starvation for pods.
		ResourceParameters: getCgroupConfig(cm.capacity),
	}
	if cm.cgroupManager.Exists(cgroupConfig.Name) {
		return nil
	}
	if err := cm.cgroupManager.Create(cgroupConfig); err != nil {
		glog.Errorf("Failed to create %q cgroup", cm.cgroupRoot)
		return err
	}
	return nil
}

so why cgroup not created during kubelet start?

**Comment by mjaow** [comment]
is there any logs?
