### ISSUE TITLE
when SessionAffinityConfig is different, enqueueService in update Service handler

### ISSUE THREAD

**Issue by hanxiaoshuai** [kubernetes/kubernetes#72810]
**What would you like to be added**:
https://github.com/kubernetes/kubernetes/pull/72809
**Why is this needed**:
when SessionAffinityConfig is different, enqueueService in update Service handler

**Comment by kow3ns** [comment]
/remove-sig apps
/sig network
This is a network related issue and PR. Your PR has appropriate reviewers already.
