### ISSUE TITLE
How to wait for all completed when use kubectl apply -f xxx.yaml?

### ISSUE THREAD

**Issue by veezhang** [kubernetes/kubernetes#72817]
How to wait for all completed when use kubectl apply -f xxx.yaml?
Not check it use kubectl get one by one.

**Comment by liggitt** [comment]
what do you mean by completed? apply returns when all objects have been submitted to the server

**Comment by veezhang** [comment]
all objects have been submitted to the server, and the server have processed.
such as, the pod status has been Running.

**Comment by cofyc** [comment]
one way is to use `kubectl get -f <resource.yaml> --watch` to watch changes after applying successfully

**Comment by Shnatsel** [comment]
You're looking for `kubectl wait`

Here's the documentation: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait

**Comment by grahamoptibrium** [comment]
Let me further this issue by explaining a use-case I'm currently fighting with.

I have a CRD and a resource of Kind: MyCRD in a common yaml/directory.

When I run `kubectl apply -f both.yaml`; the request to create the CRD is sent, and the request to create the resource is also sent; but before the CRD has actually been created, leading to a 'no such kind' failure.

**Comment by arianvp** [comment]
Workaround for this is to always apply CRDs in separate transactions and wait for their readiness:

```
kubectl apply -f crd.yaml
kubectl wait --for condition="established" crd --all
kubectl apply -f my-resources-depending-on-crd.yaml
```

**Comment by infa-amohanda** [comment]
> Workaround for this is to always apply CRDs in separate transactions and wait for their readiness:
> 
> ```
> kubectl apply -f crd.yaml
> kubectl wait --for condition="established" crd -f crd.yaml
> kubectl apply -f my-resources-depending-on-crd.yaml
> ```

For me without using the crd worked.
kubectl wait --for condition="established" -f crd.yaml

**Comment by Rishit-dagli** [comment]
I usually use:

```sh
while ! kubectl apply -f example.yaml; do echo "Retrying to apply resources"; sleep 10; done
```
