### ISSUE TITLE
Topology Manager Tracking Issue

### ISSUE THREAD

**Issue by lmdaly** [kubernetes/kubernetes#72828]
This issue is to track the feature implementation of the Topology Manager as outlined in this proposal document.

https://github.com/kubernetes/community/pull/1680/files

**What would you like to be added**:
Topology Manager component in Kubelet which collects hints from other Kubelet components in order to create a best fit Socket alignment.

**Goals are**:
- Arbitrate preferred socket affinity for containers based on input from
  CPU manager and Device Manager.
- Provide an internal interface and pattern to integrate additional
  topology-aware Kubelet components.

**Why is this needed**:
Multiple components in the Kubelet make decisions about system
topology-related assignments, but do not co-ordinate to make aligned decisions.

**Kubernetes Enhancements Issue**
https://github.com/kubernetes/enhancements/issues/693
 
**Related implementation PRs**

**Merged/Closed:**
~~https://github.com/kubernetes/kubernetes/pull/72913~~
~~https://github.com/kubernetes/kubernetes/pull/72885~~
~~https://github.com/kubernetes/kubernetes/pull/73580~~
~~https://github.com/kubernetes/kubernetes/pull/73589~~
~~https://github.com/kubernetes/kubernetes/pull/74411~~
~~https://github.com/kubernetes/kubernetes/pull/79343~~
~~https://github.com/kubernetes/kubernetes/pull/80294~~
~~https://github.com/kubernetes/kubernetes/pull/74345~~
     - Closed as superseded by https://github.com/kubernetes/kubernetes/pull/80570
~~https://github.com/kubernetes/kubernetes/pull/74357~~
~~https://github.com/kubernetes/kubernetes/pull/80301~~
~~https://github.com/kubernetes/kubernetes/pull/73920~~
~~https://github.com/kubernetes/kubernetes/pull/74423~~
~~https://github.com/kubernetes/kubernetes/pull/80569~~
~~https://github.com/kubernetes/kubernetes/pull/80570~~
~~https://github.com/kubernetes/kubernetes/pull/82020~~
     - closed, merged into #80570 
~~https://github.com/kubernetes/kubernetes/pull/81951~~
~~https://github.com/kubernetes/kubernetes/pull/81722~~

**Bug Fixes**
~~https://github.com/kubernetes/kubernetes/pull/82104~~

**Additional 1.16 PRs (Not release blocking):**
https://github.com/kubernetes/kubernetes/pull/81793
https://github.com/kubernetes/kubernetes/pull/81586
~~https://github.com/kubernetes/kubernetes/pull/82099~~
~~https://github.com/kubernetes/kubernetes/pull/81787~~

**Documentation PRs**
https://github.com/kubernetes/enhancements/pull/1222
~~https://github.com/kubernetes/website/pull/15716~~

**Comment by lmdaly** [comment]
@ConnorDoyle @balajismaniam @nolancon

**Comment by cbf123** [comment]
I'm not sure where the right place would be to bring this up, so please let me know if there's a better place.  The current proposal/implementation allows for a k8s node to be configured for "best-effort" or "strict" affinity matching and it applies to every pod landing on that node.  Since edge clusters can be quite small, it may not be feasible to dedicate entire nodes for one or the other.  As an alternative, I'd like to propose  that we allow specifying "best-effort" or "strict" affinity at the pod level.  Most of the code would remain unchanged, we'd just look at a pod label instead of a configuration option when deciding whether or not to allow pods that cannot be strictly affined to land on a given node.

**Comment by ConnorDoyle** [comment]
Hi @cbf123 

> applies to every pod landing on that node

Slight correction: applies to every Guaranteed QoS pod on the node. You can have non-aligned non-Guaranteed pods co-resident with aligned Guaranteed pods on a node with strict policy enabled.

Does that help for your use case? We can discuss the change you suggested in further detail for 1.17 / beta but it’s late in the release cycle to start a new design that touches the pod API. There are a lot more stakeholders and approvals required for API changes like that.

**Comment by cbf123** [comment]
Right, it would only be every Guaranteed QoS pod.  That helps, but it means that on a node with "strict" affinity there's no way to represent "This pod needs guaranteed CPU and memory but also needs access to a scarce PCI device even if it means cross-NUMA traffic".

In OpenStack they went so far as to make it possible to specify "best-effort/strict" for each requested PCI device.

**Comment by Pothulapati** [comment]
Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th, which means that there should be a PR ready (and merged) until then.

Do we still target this for 1.16? If not please re-tag the issue to the planned milestone.

**Comment by lmdaly** [comment]
> Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th, which means that there should be a PR ready (and merged) until then.
> 
> Do we still target this for 1.16? If not please re-tag the issue to the planned milestone.

@Pothulapati I've been keeping the topology level issue comment up to date. This is still tagged for 1.16, the PRs that need to be merged are: 
https://github.com/kubernetes/kubernetes/pull/80570
https://github.com/kubernetes/kubernetes/pull/81793
https://github.com/kubernetes/kubernetes/pull/81722

**Comment by xmudrii** [comment]
@lmdaly Any update on this? It seems like all release-critical PRs are merged. Do we want to move it to the 1.17 milestone?

**Comment by lmdaly** [comment]
@xmudrii All the PRs have been merged so the milestone is 1.16. I was planning to close the issue when the 1.16 release was out, or what is the standard practice?

**Comment by xmudrii** [comment]
@lmdaly I think that sounds okay. :+1:

**Comment by liggitt** [comment]
closing it or moving it out of the milestone once 1.16-targeted work is completed is helpful for reporting

**Comment by lmdaly** [comment]
1.16 PRs merged and documentation PR merged.
Closing issue.

**Comment by jfbai** [comment]
https://github.com/kubernetes/kubernetes/pull/78516 as well
