### ISSUE TITLE
Setting is-default-class=false does not persist on Azure's "default" storageclass

### ISSUE THREAD

**Issue by ryanlovett** [kubernetes/kubernetes#72841]
**What happened**:
I patched the "default" storageclass so that `storageclass.kubernetes.io/is-default-class` was set to false. After waiting from 3-10s, it reverts back to true. This also happens if I additionally set managed-premium to be the default storageclass.

**What you expected to happen**:
The "default" storageclass will not reacquire is-default-class=true.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
kubectl get sc -w
```

**Anything else we need to know?**:
This is with AKS, a managed kubernetes service, so I cannot [edit configuration on the master node](https://github.com/kubernetes/kubernetes/issues/53428#issuecomment-337488764).
**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.x and 1.11.5
- Cloud provider or hardware configuration: Azure

**Comment by ryanlovett** [comment]
@kubernetes/sig-azure-bugs

**Comment by andyzhangx** [comment]
@ryanlovett  it's duplicated to https://github.com/Azure/AKS/issues/550, and it's an AKS specif issue not related to azure cloud provider here. See my comments there:
https://github.com/Azure/AKS/issues/550#issuecomment-407040786

**Comment by ryanlovett** [comment]
Thanks @andyzhangx.
