### ISSUE TITLE
Create customresourcedefinition, Error: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "virtualservices.networking.istio.io": the object has been modified; please apply your changes to the latest version and try again  

### ISSUE THREAD

**Issue by SFHfeihong** [kubernetes/kubernetes#72876]
k8s version: v1.9.3
When I create customresourcedefinition, There is error like Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "virtualservices.networking.istio.io": the object has been modified; please apply your changes to the latest version and try again .

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.networking.istio.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: istio-pilot
spec:
  group: networking.istio.io
  names:
    kind: VirtualService
    listKind: VirtualServiceList
    plural: virtualservices
    singular: virtualservice
    categories:
    - istio-io
    - networking-istio-io
  scope: Namespaced
  version: v1alpha3

So what is the reason of it?

**Comment by liggitt** [comment]
a few questions:
* where are you seeing the error, in the apiserver log or in the output of the kubectl command?
* what kubectl command are you using to create the object?
* are you running HA apiservers?

**Comment by SFHfeihong** [comment]
The log is shown by apiserver. I run k8s in HA apiservers. The command I used is "kubectl apply -f "+file.

**Comment by liggitt** [comment]
API servers attempt to update CRD status to indicate whether the names were available. In an HA apiserver setup, the API servers race to do so, and all but the first lose the race with a resource conflict error. That is not unexpected. Opened #72919 to avoid logging normal API responses in that scenario.

**Comment by SFHfeihong** [comment]
Thanks ! But I want to know whether the CRD has been set successfully in HA apiservers ? I use the command " kubectl get crd virtualservices.networking.istio.io  -o yaml" and get the following results.
 
![image](https://user-images.githubusercontent.com/27404167/51221112-0e198e00-1973-11e9-88f9-c872739e3ba4.png)

I see its status is true. But when i create a virtualservices, it returns error.

Error from server (Timeout): error when creating "cms-api-virtualservice.yaml": Timeout: request did not complete within allowed duration
![image](https://user-images.githubusercontent.com/27404167/51221271-ce06db00-1973-11e9-8101-9e2516f7c3b4.png)

So i want to know how to solve this error.

**Comment by SFHfeihong** [comment]
@mbohlool Excuse me. Do you have some greate ideas to solve this issue??

**Comment by mbohlool** [comment]
@SFHfeihong There is a PR for this sent by @liggitt #72919

**Comment by mbohlool** [comment]
I see your request is timed-out not failed. In HA, I expect the request to fail in the first seconds of the CRD creation, but after that it should go through. I need more logs during this timeout or a consistent way to reproduce it.
