### ISSUE TITLE
kubeadm: specify a service account for pre-pulling images with right pod security policy

### ISSUE THREAD

**Issue by luisyonaldo** [kubernetes/kubernetes#72880]
**What would you like to be added**:
Use a different service account than `default` for the pre-pull images pods.

Right now, `kubeadm` will create a `DamonSet` to pre-pull images which uses the `default` service account in `kube-system` namespace.

We are using pod security policies in our cluster so we need to allow the `default` sa in `kube-system` ns to use the `privileged` psp. This is due to our default psp blocking `root` user and forcing users to specify which user they want to run.

**Why is this needed**:
At the moment we need to apply a psp that allows to run pod with an unspecified user (`privileged` psp in our case) to the `default` service account. Which in not good in my opinion, because any pod deployed in `kube-system` ns using the `default` sa will have access to this policy.

Note: this is also fixed if `kubeadm` specify an user in the `securityContext` of the pod. Since, as far as I can see, there is no need for any `privileged` access, is just that our default psp forces you to not use `root` user and specify which user you want to use.

**Comment by luisyonaldo** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by neolit123** [comment]
hi, please open the same issue in the k/kubeadm repo.
thank you

/close
