### ISSUE TITLE
kubeadm upgrade plan advised to upgrade etcd to older version

### ISSUE THREAD

**Issue by jorhett** [kubernetes/kubernetes#72892]
**What happened**:

`kubeadm upgrade plan` gave instructions to "upgrade" to a lower version.

```
# kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.13.1
[upgrade/versions] kubeadm version: v1.13.2
[upgrade/versions] Latest stable version: v1.13.2
[upgrade/versions] Latest version in the v1.13 series: v1.13.2

External components that should be upgraded manually before you upgrade the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT   AVAILABLE
Etcd        3.3.10    3.2.24
```

**What you expected to happen**:

AFAICT 3.3.10 is a valid version of etcd to use. If anything, I would expect that it would recommend a new minor version greater than the existing version.

**How to reproduce it (as minimally and precisely as possible)**:

Install etcd 3.3.10, run `kubeadm upgrade plan`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.1 (except kubeadm 1.13.2 in prep for upgrade)
- OS (e.g. from /etc/os-release): CentOS 7.6
- Kernel (e.g. `uname -a`): Linux TSDSSPLDS602.rsc.humad.com 3.10.0-862.3.3.el7.x86_64 #1 SMP Thu Jun 14 16:17:02 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

/sig cluster-lifecycle

**Comment by phenixblue** [comment]
Reading through the kubeadm code [here](https://github.com/kubernetes/kubernetes/blob/7d8554643e2e05fda714f30fc71f34ce05514b68/cmd/kubeadm/app/constants/constants.go#L389) it looks like there is a specific version (`<major>:<minor>`) for each Kubernetes version from 1.10 to 1.14.

Etcd version 3.2.24 is listed as the supported version for 1.13, regardless of the kubernetes minor version.

**Comment by neolit123** [comment]
please open the same issue in the k/kubeadm repository.
thank you.

/close
