### ISSUE TITLE
Does Windows service control integration properly support stopping a service

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#72900]
**What happened**:
I configured Kubelet to run as a service on Windows, with a setting to restart on failure (`sc.exe failure kubelet reset= 0 actions= restart/10000`). I noticed that it restarts even when I explicitly stop the service with `sc.exe stop kubelet`, even though the `failureflag` documentation states the following (I left it at `0`, the default):
```
Changes the failure actions flag setting of a service. If this setting is 0 (default), the Service Control Manager
(SCM) enables configured failure actions on the service only if the service process terminates with the service in
a state other than SERVICE_STOPPED. If this setting is 1, the SCM enables configured failure actions on the service if the service enters the SERVICE_STOPPED state with a Win32 exit code other than 0 in addition to the service process termination as above. This setting is ignored if the service does not have any failure actions configured.
```

**What you expected to happen**:
I expected the Kubelet to only restart when killed unexpectedly, per above docs.

**Anything else we need to know?**:
I think the problem might be due to this part of our service control integration, but I'm not really sure: https://github.com/kubernetes/kubernetes/blob/master/pkg/windows/service/service.go#L85
It looks like we send `svc.Stopped` and then `os.Exit(0)`, but the official golang example sends `svc.StopPending` and just returns without exiting. (https://github.com/golang/sys/blob/master/windows/svc/example/service.go#L57). Is this difference meaningful?

- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Windows

/cc @PatrickLang @kubernetes/sig-windows-bugs 
/sig node
/sig windows

**Comment by yujuhong** [comment]
The same should apply to kube-proxy as well.

**Comment by michmike** [comment]
@alinbalutoiu  i believe you implemented  this functionality. can you please take a look?
cc: @aserdean
