### ISSUE TITLE
Failed logs during Kubernetes pvc/pv binding

### ISSUE THREAD

**Issue by olivejing** [kubernetes/kubernetes#72905]
**What happened**:
I used storageclass to create volume, during pvc and pv binding, failed logs were reported. It happens every time when creating pvc/pv, so there are too many failed logs in my cluster.
failed logs:
```
E1218 07:57:01.256167       1 pv_protection_controller.go:116] PV pvc-781a999f-029a-11e9-bdc2-fa163ef4d7a2 failed with : Operation cannot be fulfilled on persistentvolumes "pvc-781a999f-029a-11e9-bdc2-fa163ef4d7a2": the object has been modified; please apply your changes to the latest version and try again
E1218 07:57:31.230257       1 pv_protection_controller.go:116] PV pvc-8c5a675f-029a-11e9-bdc2-fa163ef4d7a2 failed with : Operation cannot be fulfilled on persistentvolumes "pvc-8c5a675f-029a-11e9-bdc2-fa163ef4d7a2": the object has been modified; please apply your changes to the latest version and try again
E1218 09:11:40.652570       1 pv_protection_controller.go:116] PV pvc-ee11e6c7-02a4-11e9-9a7d-fa163ef2d3bd failed with : Operation cannot be fulfilled on persistentvolumes "pvc-ee11e6c7-02a4-11e9-9a7d-fa163ef2d3bd": the object has been modified; please apply your changes to the latest version and try again
```
I opened kube-controller log level to 5 and got follow logs:
```
I0108 02:20:54.327308       1 pv_protection_controller.go:203] Got event on PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3
I0108 02:20:54.327443       1 pv_controller_base.go:535] storeObjectUpdate updating volume "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3" with version 1008493
I0108 02:20:54.327505       1 pv_controller.go:824] volume "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3" entered phase "Bound"
I0108 02:20:54.327548       1 pv_controller.go:931] updating PersistentVolumeClaim[default/pvc-test]: binding to "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3"
I0108 02:20:54.327648       1 pv_controller.go:963] volume "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3" bound to claim "default/pvc-test"
I0108 02:20:54.332311       1 pv_protection_controller.go:166] Error adding protection finalizer to PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3: Operation cannot be fulfilled on persistentvolumes "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3": the object has been modified; please apply your changes to the latest version and try again
I0108 02:20:54.332519       1 pv_protection_controller.go:126] Finished processing PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3 (13.40545ms)
E0108 02:20:54.332648       1 pv_protection_controller.go:116] PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3 failed with : Operation cannot be fulfilled on persistentvolumes "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3": the object has been modified; please apply your changes to the latest version and try again
I0108 02:20:54.332971       1 pv_controller.go:974] updating PersistentVolumeClaim[default/pvc-test]: bound to "pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3"
I0108 02:20:54.333386       1 pv_protection_controller.go:123] Processing PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3
......
I0108 02:20:54.340808       1 pv_controller.go:645] synchronizing PersistentVolume[pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3]: all is bound
I0108 02:20:54.340830       1 pv_controller.go:803] updating PersistentVolume[pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3]: set phase Bound
I0108 02:20:54.340854       1 pv_controller.go:806] updating PersistentVolume[pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3]: phase Bound already set
I0108 02:20:54.340876       1 pv_protection_controller.go:203] Got event on PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3
I0108 02:20:54.341004       1 pv_protection_controller.go:169] Added protection finalizer to PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3
I0108 02:20:54.341053       1 pv_protection_controller.go:126] Finished processing PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3 (7.543352ms)
I0108 02:20:54.341076       1 pv_protection_controller.go:123] Processing PV pvc-0205077c-12ec-11e9-8d34-fa163ea8fbb3
```
**What you expected to happen**:
why it reported "Error adding protection finalizer to PV" at first time?
why it reported failed logs?
Error/failed logs during successful operations should not occur.
**How to reproduce it (as minimally and precisely as possible)**:
It happens every time when i use k8s pvc/pv
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2 and v1.12.3

/sig Storage

**Comment by alex-roman** [comment]
Having the same issue but the volume isn't attached to any node in my case. 
```
goroutinemap.go:150] Operation for "provision-default/mongodb[ce7a639e-27f2-11e9-984c-0a3e952976c6]" failed. No retries permitted until 2019-02-03 20:32:21.627148934 +0000 UTC m=+380.338622509 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumeclaims \"mongodb\": the object has been modified; please apply your changes to the latest version and try again"
```

pv_controller tries to bound pvc, succeed, updates the claim and since the volume is actually detached pv_controller does the same thing next loop.
I don't see any other related errors except the one posted above.

**Comment by olivejing** [comment]
> 
> 
> Having the same issue but the volume isn't attached to any node in my case.
> 
> ```
> goroutinemap.go:150] Operation for "provision-default/mongodb[ce7a639e-27f2-11e9-984c-0a3e952976c6]" failed. No retries permitted until 2019-02-03 20:32:21.627148934 +0000 UTC m=+380.338622509 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumeclaims \"mongodb\": the object has been modified; please apply your changes to the latest version and try again"
> ```
> 
> pv_controller tries to bound pvc, succeed, updates the claim and since the volume is actually detached pv_controller does the same thing next loop.
> I don't see any other related errors except the one posted above.

I run command: kubectl create -f pvc-test.yaml：
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-az-nova
```
the error happens every time:
`E0222 02:04:35.053949       1 goroutinemap.go:150] Operation for "provision-default/pvc-test[33608eb7-3646-11e9-946e-fa163e255ba2]" failed. No retries permitted until 2019-02-22 02:04:35.539965143 +0000 UTC m=+236459.134894572 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumeclaims \"pvc-test\": the object has been modified; please apply your changes to the latest version and try again"`

**Comment by jwsomis** [comment]
I am experiencing this as well without the volume attachment.

**Comment by ionutbiru** [comment]
I have the same issue using cinder storage class. the volume is created but never attached. Did you guys found a fix for this?

storage class: https://kubernetes.io/docs/concepts/storage/storage-classes/#openstack-cinder
mysql deployment: https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
kubectl get sc,pv,pvc,pod --all-namespaces: https://paste.xinu.at/UNp/

latest log and nothing after it: 

> pv_protection_controller.go:116] PV pvc-48fed935-5b61-11e9-9901-fa163e5ebeae failed with : Operation cannot be fulfilled on persistentvolumes "pvc-48fed935-5b61-11e9-9901-fa163e5ebea> the object has been modified; please apply your changes to the latest version and try again

**Comment by olivejing** [comment]
I am using k8s v1.13.4 now, the issue still exist:
E0411 02:17:53.404234       1 pv_protection_controller.go:116] PV pvc-fd256216-5bff-11e9-a069-fa163ec82c85 failed with : Operation cannot be fulfilled on persistentvolumes "pvc-fd256216-5bff-11e9-a069-fa163ec82c85": the object has been modified; please apply your changes to the latest version and try again

**Comment by naumvd95** [comment]
absolutely similar problem !
k8s `v1.13.5`
cinder SC
```Operation for "provision-openstack/mysql-data-mariadb-server-0[6ddbcc2a-65ed-11e9-b23f-fa163e56065a]" failed. No retries permitted until 2019-04-23 17:30:04.187120038 +0000 UTC m=+19037.170658427 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumeclaims \"mysql-data-mariadb-server-0\": the object has been modified; please apply your changes to the latest version and try again"```

**Comment by ionutbiru** [comment]
for me it works if i create the template with the following labels:

--labels kube_tag=v1.13.4,cloud_provider_tag=1.13.1,kube_version=v1.13.4

**Comment by krmayankk** [comment]
@ionutbiru  where did you add those labels ? Are they documented ?

**Comment by ranjujohn** [comment]
I get similar error when i tested K8s **1.14.3** with vsphere cloud provider. Any work around for this?

goroutinemap.go:150] Operation for "provision-default/test-claim[ee798e76-8dd4-11e9-9e8b-005056858582]" failed. No retries permitted until 2019-06-13 12:15:29.021689773 +0000 UTC m=+151.946011736 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumeclaims "test-claim": the object has been modified; please apply your changes to the latest version and try again"

**Comment by svjakrm** [comment]
I have the same issue, k8s 1.14.3 vSphere 6.5
`E0626 10:26:44.588883       1 pvc_protection_controller.go:138] PVC default/pvcsc-vsan failed with : Operation cannot be fulfilled on persistentvolumeclaims "pvcsc-vsan": the object has been modified; please apply your changes to the latest version and try again`
Any workarounds available?

**Comment by arturoera** [comment]
same issue, 
```E0930 20:25:37.219900       1 pvc_protection_controller.go:138] PVC default/my-volume failed with : Operation cannot be fulfilled on persistentvolumeclaims "my-volume": the object has been modified; please apply your changes to the latest version and try again```
k8s 1.14.6 hosted in GCE (not GKE). 
After the pvc is in pending status for a while, eventually it bounds, the delay its just ranging from 2 to 6 hours.

**Comment by timyinshi** [comment]
my cluster has the same error,i know the reason,when pvc create rbd image,have no right result,the rbd create process is hung,so the pvc's resourceversion is not right.i think when resovle the problem of rbd can not work,the pvc ’resourceversion is right.
 kubectl exec kube-controller-manager-mgt01 -nkube-system -it sh
sh-4.4# ps -ef                                                                                                                                                                                                   
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  5 11:38 ?        00:00:25 /hyperkube controller-manager --bind-address=10.68.11.4 --kubeconfig=/etc/kubernetes/kube-controller-manager-kubeconfig.yaml --leader-elect=true --service-account
root        73     1  0 11:39 ?        00:00:00 rbd create kubernetes-dynamic-pvc-490fdc2f-fc9c-11e9-bda9-52540052e775 --size 10240 --pool k8s-rbd --id admin -m 10.68.12.101:6789,10.68.12.102:6789,10.68.12.103:
