### ISSUE TITLE
Flake: TestImageLocality in pull/ci kubernetes-integration jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#72903]
**Which jobs are failing**: pull/ci kubernetes-integration jobs

**Which test(s) are failing**: TestImageLocality

**Since when has it been failing**: 
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestImageLocality

**Testgrid link**: 

**Reason for failure**:

**Anything else we need to know**:

**Comment by dims** [comment]
http://storage.googleapis.com/k8s-metrics/flakes-latest.json says 

```
  "pr:pull-kubernetes-integration": {
    "consistency": 0.833,
    "flakes": 91,
    "flakiest": {
      "k8s.io/kubernetes/test/integration/scheduler TestPreemptionRaces": 23,
      "k8s.io/kubernetes/test/integration/apiserver Test202StatusCode": 15,
      "k8s.io/kubernetes/test/integration/scheduler TestImageLocality": 10
    }
  },
```

**Comment by resouer** [comment]
/assign

We need to handle this, cc @silveryfu

**Comment by silveryfu** [comment]
Thanks @dims and @resouer, please check https://github.com/kubernetes/kubernetes/pull/73091.
