### ISSUE TITLE
build/run.sh hangs on stopping rsync container 

### ISSUE THREAD

**Issue by rus4** [kubernetes/kubernetes#72915]
:~/work_directory/kubernetes$ build/run.sh make
+++ [0115 13:03:42] Verifying Prerequisites....
+++ [0115 13:03:44] Building Docker image kube-build:build-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container kube-rsync-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container kube-build-data-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container friendly_franklin
+++ [0115 13:03:58] Keeping container k8s_etcd_etcd-minikube_kube-system_d4778d4ccda87460ba6302905901c7e2_1583
+++ [0115 13:03:58] Keeping container k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_f1cde7e7052dc59a12e93941d40462e7_1583
+++ [0115 13:03:58] Keeping container wizardly_bell
+++ [0115 13:03:58] Keeping container determined_bardeen
+++ [0115 13:03:58] Keeping container relaxed_goldberg
+++ [0115 13:03:58] Keeping container k8s_kube-addon-manager_kube-addon-manager-minikube_kube-system_8b52f08746ac78d32737b5f7fdffec52_0
+++ [0115 13:03:58] Keeping container k8s_kube-scheduler_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-addon-manager-minikube_kube-system_8b52f08746ac78d32737b5f7fdffec52_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-controller-manager-minikube_kube-system_f1cde7e7052dc59a12e93941d40462e7_0
+++ [0115 13:03:58] Keeping container k8s_POD_etcd-minikube_kube-system_d4778d4ccda87460ba6302905901c7e2_0
+++ [0115 13:03:58] Keeping container kube-rsync-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container kube-build-data-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container friendly_franklin
+++ [0115 13:03:58] Keeping container k8s_etcd_etcd-minikube_kube-system_d4778d4ccda87460ba6302905901c7e2_1583
+++ [0115 13:03:58] Keeping container k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_f1cde7e7052dc59a12e93941d40462e7_1583
+++ [0115 13:03:58] Keeping container wizardly_bell
+++ [0115 13:03:58] Keeping container determined_bardeen
+++ [0115 13:03:58] Keeping container relaxed_goldberg
+++ [0115 13:03:58] Keeping container k8s_kube-addon-manager_kube-addon-manager-minikube_kube-system_8b52f08746ac78d32737b5f7fdffec52_0
+++ [0115 13:03:58] Keeping container k8s_kube-scheduler_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-addon-manager-minikube_kube-system_8b52f08746ac78d32737b5f7fdffec52_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-controller-manager-minikube_kube-system_f1cde7e7052dc59a12e93941d40462e7_0
+++ [0115 13:03:58] Keeping container k8s_POD_etcd-minikube_kube-system_d4778d4ccda87460ba6302905901c7e2_0
+++ [0115 13:03:58] Keeping container kube-rsync-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container kube-build-data-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Keeping container friendly_franklin
+++ [0115 13:03:58] Keeping container k8s_etcd_etcd-minikube_kube-system_d4778d4ccda87460ba6302905901c7e2_1583
+++ [0115 13:03:58] Keeping container k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_f1cde7e7052dc59a12e93941d40462e7_1583
+++ [0115 13:03:58] Keeping container wizardly_bell
+++ [0115 13:03:58] Keeping container determined_bardeen
+++ [0115 13:03:58] Keeping container relaxed_goldberg
+++ [0115 13:03:58] Keeping container k8s_kube-addon-manager_kube-addon-manager-minikube_kube-system_8b52f08746ac78d32737b5f7fdffec52_0
+++ [0115 13:03:58] Keeping container k8s_kube-scheduler_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-addon-manager-minikube_kube-system_8b52f08746ac78d32737b5f7fdffec52_0
+++ [0115 13:03:58] Keeping container k8s_POD_kube-controller-manager-minikube_kube-system_f1cde7e7052dc59a12e93941d40462e7_0
+++ [0115 13:03:58] Keeping container k8s_POD_etcd-minikube_kube-system_d4778d4ccda87460ba6302905901c7e2_0
+++ [0115 13:03:58] Keeping image kube-build:build-ca5af74d58-5-v1.11.4-1
+++ [0115 13:03:58] Syncing sources to container
+++ [0115 13:03:58] Stopping any currently running rsyncd container

**Comment by rus4** [comment]
$ docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                    PORTS                       NAMES
2734ab8deb4a        b27d08bd7ae4                      "/rsyncd.sh"             2 hours ago         Up 2 hours                127.0.0.1:32768->8730/tcp   kube-rsync-ca5af74d58-5-v1.11.4-1

**Comment by rus4** [comment]
Is there something going on with rsyncd ? 
```
s# docker history b27d08bd7ae4
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
b27d08bd7ae4        2 hours ago         /bin/sh -c chmod a+rx /rsyncd.sh                2.3kB
a22562ae2777        2 hours ago         /bin/sh -c #(nop) ADD file:4741f7d5fafbdd1b6…   2.3kB
6610014a9f06        2 hours ago         /bin/sh -c chmod a+r /rsyncd.password           32B
85c602b20cbd        2 hours ago         /bin/sh -c #(nop) ADD file:b64df02c642ee1b01…   32B
82a540160068        2 hours ago         /bin/sh -c chmod a+r /etc/localtime             3.69kB
3e8cceae0244        2 hours ago         /bin/sh -c #(nop) ADD file:b67bade5bd7fa7f81…   3.69kB
67b0f9f03a3d        2 hours ago         /bin/sh -c chmod -R a+rwx $GOPATH               35.6MB
328446ad8419        2 hours ago         /bin/sh -c git config --system user.email "n…   55B
9c3a6cdd0f1d        2 hours ago         /bin/sh -c #(nop)  ENV KUBE_GIT_VERSION_FILE…   0B
79ed4f19b7e6        2 hours ago         /bin/sh -c #(nop)  ENV KUBE_OUTPUT_SUBPATH=_…   0B
```

**Comment by rus4** [comment]
```
# docker logs 2734ab8deb4a
2019/01/15 11:27:22 [1] rsyncd version 3.1.2 starting, listening on port 8730
2019/01/15 11:27:22 [17] params.c:Parameter() - Ignoring badly formed line in config file: 172.17.0.1
2019/01/15 11:27:22 [17] params.c:Parameter() - Ignoring badly formed line in config file: 192.168.122.1
2019/01/15 11:27:22 [17] params.c:Parameter() - Ignoring badly formed line in config file: 192.168.99.1
2019/01/15 11:27:22 [17] connect from UNDETERMINED (172.17.0.1)
2019/01/15 11:27:22 [17] module-list request from UNDETERMINED (172.17.0.1)
2019/01/15 11:27:22 [18] params.c:Parameter() - Ignoring badly formed line in config file: 172.17.0.1
2019/01/15 11:27:22 [18] params.c:Parameter() - Ignoring badly formed line in config file: 192.168.122.1
2019/01/15 11:27:22 [18] params.c:Parameter() - Ignoring badly formed line in config file: 192.168.99.1
2019/01/15 11:27:22 [18] connect from UNDETERMINED (172.17.0.1)
2019/01/15 11:27:22 [18] rsync to k8s/ from k8s@UNDETERMINED (172.17.0.1)
2019/01/15 11:27:22 [18] receiving file list
2019/01/15 11:27:24 [18] sent 367717 bytes  received 188584128 bytes  total size 187195614
```

**Comment by truongnh1992** [comment]
Could I handle this issue?

**Comment by ethereal-sandeep** [comment]
@rus4 It would be great if i could get to work on this.

**Comment by rus4** [comment]
yes please i need all the help i can get , i am also looking at the alternative way of building that uses docker containers using make quick-release this seems to get further but also gets to a point where it stalls with the process going to nil memory utilisation so both approaches seem problematic for me.

**Comment by vivekbagade** [comment]
Any update on this?

**Comment by yuxiangqian** [comment]
On ubuntu:
Not a solution but I got around following [this link](https://stackoverflow.com/questions/49104733/docker-on-ubuntu-16-04-error-when-killing-container) to manually stop any running "rsyncd". You might end up failing to stop them with error like: "container_linux.go:393: signaling init process caused "permission denied"
running: sudo aa-remove-unknown should allow you to stop it thereafter. Good luck

**Comment by fenglixa** [comment]
Cann't reproduce this issue, but checked the code, pls actions as below, and append result here, if you encounter again:

```
$ docker ps -a |grep -i kube-rsync
Get the KUBE_RSYNC_CONTAINER_NAME from the result of above CLI.
$ docker kill ${KUBE_RSYNC_CONTAINER_NAME}
$ docker wait ${KUBE_RSYNC_CONTAINER_NAME}
$ docker version
```

Thanks
BR
-Francis

**Comment by GDegrove** [comment]
Hey @rus4 do you still need/want any help on this issue?

**Comment by ameena3** [comment]
Hey @rus4 , 
Do you still need any help here . Please find the latest code below for stopping the Rsyncd containers  :-
`# Pedantically kill, wait-on and remove a container. The -f -v options
# to rm don't actually seem to get the job done, so force kill the
# container, wait to ensure it's stopped, then try the remove. This is
# a workaround for bug https://github.com/docker/docker/issues/3968.
function kube::build::destroy_container() {
  "${DOCKER[@]}" kill "$1" >/dev/null 2>&1 || true
  if [[ $("${DOCKER[@]}" version --format '{{.Server.Version}}') = 17.06.0* ]]; then
    # Workaround https://github.com/moby/moby/issues/33948.
    # TODO: remove when 17.06.0 is not relevant anymore
    DOCKER_API_VERSION=v1.29 "${DOCKER[@]}" wait "$1" >/dev/null 2>&1 || true
  else
    "${DOCKER[@]}" wait "$1" >/dev/null 2>&1 || true
  fi
  "${DOCKER[@]}" rm -f -v "$1" >/dev/null 2>&1 || true
}`

Step 1:- Give kill signal 
Step 2:- Wait for the container to stop 
Step 3:- Force remove the container
 This should potentially fix the issue 
Try the steps from @fenglixa  they should help with identifying the issue

**Comment by AnitaNayak** [comment]
I wanted to take this up. @rus4. Please let me know.
