### ISSUE TITLE
Scheduler leaves pod stuck in pending after worker node reload

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#72925]
**What happened**:

Kubernetes scheduler may leave a single pod stuck in pending state after a worker node is reloaded/reinstalled. This problem appears to have been introduced in Kubernetes v1.12.4 and v1.13.1.  We have not been able to recreate the problem in our testing on earlier releases.  The key to the failure is that the worker being reloaded/reinstalled must be the only scheduling option available. The pending pod is eventually scheduled if a new scheduler leader is elected or the node status changes. This appears to be a timing bug since the problem does not always occur.

**What you expected to happen**:

No pods are stuck in pending state.

**How to reproduce it (as minimally and precisely as possible)**:

Start with a single node cluster running a handful of pods.  Cordon, drain and then reload/reinstall the node.  Since this is a timing bug, it may take several iterations to recreate the problem.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4, 1.13.1 and 1.13.2
- Cloud provider or hardware configuration: VMs running in VirtualBox
- OS (e.g. from /etc/os-release): `Ubuntu 18.04.1 LTS`
- Kernel (e.g. `uname -a`): `Linux carrier0-master-1 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Custom ansible scripts
- Others: N/A

**Comment by rtheis** [comment]
Events from the pending pod:

```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  36m (x17 over 42m)  default-scheduler  0/1 nodes are available: 1 node(s) were unschedulable.
  Warning  FailedScheduling  35m (x2 over 36m)   default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
```

Events from the node:

```
Events:
  Type     Reason                   Age                From                       Message
  ----     ------                   ----               ----                       -------
  Normal   NodeNotSchedulable       42m                kubelet, 10.200.202.22     Node 10.200.202.22 status is now: NodeNotSchedulable
  Normal   Starting                 36m                kubelet, 10.200.202.22     Starting kubelet.
  Warning  InvalidDiskCapacity      36m                kubelet, 10.200.202.22     invalid capacity 0 on image filesystem
  Normal   NodeAllocatableEnforced  36m                kubelet, 10.200.202.22     Updated Node Allocatable limit across pods
  Normal   NodeHasSufficientDisk    36m (x6 over 36m)  kubelet, 10.200.202.22     Node 10.200.202.22 status is now: NodeHasSufficientDisk
  Normal   NodeHasSufficientMemory  36m (x6 over 36m)  kubelet, 10.200.202.22     Node 10.200.202.22 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    36m (x5 over 36m)  kubelet, 10.200.202.22     Node 10.200.202.22 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     36m (x5 over 36m)  kubelet, 10.200.202.22     Node 10.200.202.22 status is now: NodeHasSufficientPID
  Normal   Starting                 36m                kube-proxy, 10.200.202.22  Starting kube-proxy.
```

**Comment by Huang-Wei** [comment]
@rtheis does "reload/reinstall" mean `Node` info is still kept in etcd? or `kubectl delete node <node name>` (or equivalent steps) is executed to remove that node entirely?

And I assume the "reloaded" node keeps the same spec and IP/node name with previous one?

**Comment by rtheis** [comment]
@Huang-Wei the `Node` info is still kept in etcd.  And the node keeps the same spec, IP and name as it had before.  The reload does the following:

1. Cordon and drain the node
2. Destroy the VM
3. Provision the VM again with the same spec
4. Uncordon the node

**Comment by k82cn** [comment]
>  1 node(s) had taints that the pod didn't tolerate.

What's the taint/toleration accordingly?

**Comment by rtheis** [comment]
@k82cn there were no taints added to the node during this process.  The pods are part of a deployment with only basic tolerations provided by Kubernetes.  Deleting the pod will get it scheduled even though the taints and tolerations are unchanged.  Simply restarting the scheduler leader will get the pod scheduled as well.

**Comment by k82cn** [comment]
>  there were no taints added to the node during this process.

Can you share `kubectl get node node_name -o yaml` and `kubectl get pod pod_name -o yaml` ?

**Comment by Huang-Wei** [comment]
The symptom (esp. "a single pod stuck in pending state") is quite similar as issue #72122. I think why this occurs since v1.12.4 is related the PR #71551 - which was delivered to master branch, and backported to v1.12.4, and it appears to reveal higher chance of racing.

cc/ @bsalamat 

Basically we have 2 solutions to fix this:

1. find the real root cause of the racing condition and give fix (I haven't got luck to reproduce this yet)
1. given that we have a solution (#72558) to alleviate this kind of problem, @rtheis could you try to run your test on a) master branch or b) v1.12.4 with #72558 cherrypicked to see if the issue is resolved? and does this fits your business need? (in other words, the single pod may be pending for 30 seconds at most)

**Comment by rtheis** [comment]
@k82cn I'll recreate and provide you the details.  However, the pod that is stuck pending is different every time.

**Comment by rtheis** [comment]
@Huang-Wei Thanks, I'll work on the recreate and test of the cherrypick.  That PR certainly seems promising.

**Comment by rtheis** [comment]
Node YAML after recreate:

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2019-01-18T15:23:12Z"
  labels:
    arch: amd64
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    ibm-cloud.kubernetes.io/ha-worker: "true"
    ibm-cloud.kubernetes.io/worker-version: 1.13.2_1501
    kubernetes.io/hostname: 10.200.200.6
    privateVLAN: "2"
    publicVLAN: "1"
  name: 10.200.200.6
  resourceVersion: "4035"
  selfLink: /api/v1/nodes/10.200.200.6
  uid: f7cdb88d-1b34-11e9-8faa-faa05f368167
spec:
  providerID: ibm://///cruiser1/cruiser1-worker-1
status:
  addresses:
  - address: 10.200.200.6
    type: InternalIP
  - address: 192.168.10.6
    type: ExternalIP
  - address: 10.200.200.6
    type: Hostname
  allocatable:
    cpu: 1920m
    ephemeral-storage: "49945295219"
    hugepages-2Mi: "0"
    memory: 1734944Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 51341792Ki
    hugepages-2Mi: "0"
    memory: 2041120Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2019-01-18T17:52:41Z"
    lastTransitionTime: "2019-01-18T16:42:50Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2019-01-18T17:52:41Z"
    lastTransitionTime: "2019-01-18T16:42:50Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2019-01-18T17:52:41Z"
    lastTransitionTime: "2019-01-18T16:42:50Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2019-01-18T17:52:41Z"
    lastTransitionTime: "2019-01-18T16:43:31Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2019-01-18T15:23:12Z"
    lastTransitionTime: "2019-01-18T16:37:15Z"
    message: Kubelet never posted node status.
    reason: NodeStatusNeverUpdated
    status: Unknown
    type: OutOfDisk
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - registry.ng.bluemix.net/armada-master/kubernetes-dashboard-amd64@sha256:d6b4e5d77c1cdcb54cd5697a9fe164bc08581a7020d6463986fe1366d36060e8
    - registry.ng.bluemix.net/armada-master/kubernetes-dashboard-amd64:v1.10.1
    sizeBytes: 44743415
  - names:
    - registry.ng.bluemix.net/armada-master/cni@sha256:77d335561bf44d09dfdd2ad2f4f3711210abead20d70a94a38f2598ef88d95e0
    - registry.ng.bluemix.net/armada-master/cni:v3.3.1
    sizeBytes: 23846173
  - names:
    - registry.ng.bluemix.net/armada-master/node@sha256:028231a4d707b17928504b6364ab6000989496921963d153fead69d9b8334ca8
    - registry.ng.bluemix.net/armada-master/node:v3.3.1
    sizeBytes: 20223791
  - names:
    - registry.ng.bluemix.net/armada-master/kube-controllers@sha256:5d3686a7dc06b54eeca901bb4a65dbda16bb93f8ad0b0f4091108d30301fa126
    - registry.ng.bluemix.net/armada-master/kube-controllers:v3.3.1
    sizeBytes: 14566696
  - names:
    - registry.ng.bluemix.net/armada-master/coredns@sha256:dbd3e8bf23bc25fc5df4f78b01ae3df2b6e580a594d37b9037ed5190c272c887
    - registry.ng.bluemix.net/armada-master/coredns:1.2.6
    sizeBytes: 12031018
  - names:
    - registry.ng.bluemix.net/armada-master/metrics-server-amd64@sha256:ad4a7150389426eedbd2bc81ba8067dc4807b7f47697310a8fe917f34475f83e
    - registry.ng.bluemix.net/armada-master/metrics-server-amd64:v0.3.1
    sizeBytes: 10908506
  - names:
    - registry.ng.bluemix.net/armada-master/addon-resizer@sha256:737c634a95f04bffbcd8d3a833745cc26d4d42e8a759ca75b8b8b407ef40b780
    - registry.ng.bluemix.net/armada-master/addon-resizer:1.8.4
    sizeBytes: 9498066
  - names:
    - registry.ng.bluemix.net/armada-master/cluster-proportional-autoscaler-amd64@sha256:aac2f92c5bf5de7c2bc43fcc63e9fedf93ba2c3434940679f4f202ebb524aa3a
    - registry.ng.bluemix.net/armada-master/cluster-proportional-autoscaler-amd64:1.3.0
    sizeBytes: 8991532
  - names:
    - registry.ng.bluemix.net/armada-master/keepalived-watcher@sha256:9c4c08cd99bca900ad0e691d0a66e45422ec9661893ae3783d16520685305d5a
    - registry.ng.bluemix.net/armada-master/keepalived-watcher:132
    sizeBytes: 8884677
  - names:
    - registry.ng.bluemix.net/armada-master/haproxy@sha256:826bef8f95f894b96047c8405f188c0743d8c9a85a092552605b5490f401ff43
    - registry.ng.bluemix.net/armada-master/haproxy:1.8.12-alpine
    sizeBytes: 8838911
  - names:
    - registry.ng.bluemix.net/armada-master/pause@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610
    - registry.ng.bluemix.net/armada-master/pause:3.1
    sizeBytes: 315499
  nodeInfo:
    architecture: amd64
    bootID: b406fc21-92df-4221-b810-cac349fedadf
    containerRuntimeVersion: containerd://1.1.5
    kernelVersion: 4.15.0-42-generic
    kubeProxyVersion: v1.13.2+IKS
    kubeletVersion: v1.13.2+IKS
    machineID: f65d2cc488a243b78927223be3693fd7
    operatingSystem: linux
    osImage: Ubuntu 18.04.1 LTS
    systemUUID: FF62B567-22DC-4DF3-9890-BF87D56ADEB7
```

**Comment by rtheis** [comment]
Pod YAML after recreate:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: ibm-privileged-psp
  creationTimestamp: "2019-01-18T16:35:45Z"
  generateName: vpn-899ff4679-
  labels:
    app: vpn
    kubernetes-dashboard-policy: allow
    pod-template-hash: 899ff4679
  name: vpn-899ff4679-x44xz
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: vpn-899ff4679
    uid: 84f50cc2-1b33-11e9-8faa-faa05f368167
  resourceVersion: "2650"
  selfLink: /api/v1/namespaces/kube-system/pods/vpn-899ff4679-x44xz
  uid: 1ae534ca-1b3f-11e9-8faa-faa05f368167
spec:
  containers:
  - env:
    - name: K8S_CERT_DIR
      value: /etc/kubernetes/cert
    image: registry.ng.bluemix.net/armada-master/vpn-client:2.4.6-r3-IKS-8
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - ping -w 3 192.168.255.1
      failureThreshold: 5
      initialDelaySeconds: 120
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 30
    name: vpn
    resources:
      requests:
        cpu: 5m
        memory: 5Mi
    securityContext:
      privileged: true
      procMount: Default
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/cert
      name: vpn-config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7pwjx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: bluemix-default-secret
  - name: bluemix-default-secret-regional
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: vpn-config
    name: vpn-config
  - name: default-token-7pwjx
    secret:
      defaultMode: 420
      secretName: default-token-7pwjx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-01-18T16:35:46Z"
    message: '0/1 nodes are available: 1 node(s) had taints that the pod didn''t tolerate.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

**Comment by rtheis** [comment]
@Huang-Wei the cherrypick doesn't look trivial for 1.12 or 1.13.  Give me some time to setup an environment to test on 1.14.  Unless you have another way?

**Comment by Huang-Wei** [comment]
@rtheis Yeap, it's not a trivial task to rebuild the source code. Let me know if you need any help.

> Give me some time to setup an environment to test on 1.14.

I suppose you're going to try on latest 1.14 tag? e.g. v1.14.0-alpha.1?

> Unless you have another way?

Right now I'm working on the 1st solution I mentioned in https://github.com/kubernetes/kubernetes/issues/72925#issuecomment-455444197. The challenge is I can't reproduce this in my local dev env (I'm running on source code branch of v1.12.4) yet, so my current plan is to retry reproducing your issue to make my solution more convincing. If still no luck, I will send out the PR for reviewing early next week.

**Comment by Huang-Wei** [comment]
And @rtheis, let me confirm with your statement:

> Kubernetes scheduler may leave a single pod stuck in pending state after a worker node is reloaded/reinstalled.

When the issue occurs, **everytime** there is only one single pod stuck in pending state, right?

**Comment by Huang-Wei** [comment]
Still don't have luck in reproducing the issue. But I've prepared a PR #73078 and put detailed analysis there. Any comments are welcome.

**Comment by rtheis** [comment]
@Huang-Wei No, the problem does not occur every time.  It can take as many as 7 retries before reproducing it.

**Comment by Huang-Wei** [comment]
@rtheis Sry, I should have made it more clear - I wanted to confirm that among all the times the issue is reproducible, is that everytime there is only one single pod in pending state?

**Comment by rtheis** [comment]
@Huang-Wei correct, every time that I've reproduced the problem there has been only one pod in pending state.

**Comment by Huang-Wei** [comment]
@rtheis Thanks. To some extent, it's consistent with the deduction in my PR.

**Comment by rtheis** [comment]
@Huang-Wei is it possible to have the necessary fixes cherry-picked to at least 1.12 and 1.13?  That would make it easier for me to build and test?

**Comment by Huang-Wei** [comment]
Yeap, cherrypick PRs (#73206 onto 1.13, #73207 onto 1.12) were created and will be reviewed/approved soon.

**Comment by rtheis** [comment]
@Huang-Wei Thank you for the cherrypick PRs.  I rebuilt 1.13 with the cherrypick PR and still saw the problem on 2 of 10 recreate attempts.  Without the fix, I saw a similar failure rate.

**Comment by Huang-Wei** [comment]
@rtheis the fix is only ready in master right now. Did you rebuild 1.13 by manually running “git cherrypick <this commit id>” on release-1.13? Or directly built from latest src code of release-1.13?

**Comment by rtheis** [comment]
@Huang-Wei I manually rebuilt 1.13.2 with https://github.com/kubernetes/kubernetes/pull/73206/.

**Comment by Huang-Wei** [comment]
/reopen

@rtheis I will take another look.

**Comment by Huang-Wei** [comment]
@rtheis I've verified #73309 is able to fix your issue thoroughly. And cherrypick PRs have been raised (1.12 #73567, 1.13 #73568).

**Comment by rtheis** [comment]
@Huang-Wei Thank you.

**Comment by bsalamat** [comment]
Thanks, @Huang-Wei and @rtheis!
K8s 13.3 already has another change (#72558) that should alleviate the problem significantly. K8s 13.4 will have the definitive fix.
Given that the root-cause is fixed, we can close this issue.
