### ISSUE TITLE
KubeletConfiguration does not support flex volume plugin directory

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#72926]
It looks like `KubeletConfiguration` type does not have a field for `VolumePluginDir` which is a valid kubelet option. Was there any particular reason to not bring this field over?

/sig node
/sig storage

cc @sjenning

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/61650?

one decision was whether to expose all the individual directory flags in config, or use fixed relative paths off the kubelet's root dir

@derekwaynecarr

**Comment by gnufied** [comment]
closing in favour of #61650 

/close
