### ISSUE TITLE
Promote node os/arch label to stable

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#72929]
**What would you like to be added**:
kubelet self labels the node with OS/arch, etc. The labeling was added backed in 1.3. It's time to promote the labels.
```
LabelOS   = "beta.kubernetes.io/os"
LabelArch = "beta.kubernetes.io/arch"
```

**Why is this needed**:
This feature has already been used in multiple places to help schedule pods onto the right nodes.

For the transition, kubelet will need to label itself with both the beta and the GA label to handle the master-node version skew for a few releases.

/cc @kubernetes/sig-node-feature-requests @dchen1107 @derekwaynecarr @liggitt @luxas  
/cc @PatrickLang @pjh @mtaufen

**Comment by mtaufen** [comment]
I support this.

**Comment by PatrickLang** [comment]
+1

**Comment by bgrant0607** [comment]
Has documentation been updated? Are the possible/expected label values documented? I don't even see a golang documentation page containing the values.

Are there upgrade and version-skew tests? Annotation changes in the past have caused compatibility breakage. I wouldn't expect label key changes to be any less error prone.

Speaking of breakage, do we need a test to verify that golang changes don't break us by changing the values?

**Comment by bgrant0607** [comment]
cc @liggitt

**Comment by liggitt** [comment]
Just saw this, thanks. 

The values are reported by kubelet as part of the kubelet's reconcile loop, so we have a single writer, so reporting both the old and new annotation keys doesn't seem concerning. 

I agree documentation needs to be updated, and note the release at which the new keys started getting reported. 

Changing the go constant values is the most concerning part of this and should probably be reverted. I'd recommend choosing new constant names (LabelOSStable or something) to avoid silently changing the behavior of every component that references the existing constants in ways that aren't safe for clusters with 1.13 or older kubelets. 

For extra credit, the node controller could add/update the stable labels on nodes to match the beta labels reported by legacy nodes until 1.16 when the oldest kubelets in the cluster would be known to report the new labels as well.

**Comment by yujuhong** [comment]
> Has documentation been updated? Are the possible/expected label values documented? I don't even see a golang documentation page containing the values.
> I agree documentation needs to be updated, and note the release at which the new keys started getting reported.

Not yet. I will send a PR to update documentation in https://github.com/kubernetes/website, in particular, https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

> Are there upgrade and version-skew tests? Annotation changes in the past have caused compatibility breakage. I wouldn't expect label key changes to be any less error prone.

> Changing the go constant values is the most concerning part of this and should probably be reverted. I'd recommend choosing new constant names (LabelOSStable or something) to avoid silently changing the behavior of every component that references the existing constants in ways that aren't safe for clusters with 1.13 or older kubelets.

FWIW, `LabelOS` and `LabelArch` are not used anywhere in the kubernetes repository. But fair enough, there might be outside components relying on those. I'll send a PR to revert & fix this behavior. 

> The values are reported by kubelet as part of the kubelet's reconcile loop, so we have a single writer for the existing labels, so reporting both the old and new label keys doesn't seem concerning in a normal case. The only case I can think of that would cause trouble is if a kubelet was upgraded, reported the new label, then a node with the same name with a different os/arch and back level kubelet was run, and would not maintain the new label. That seems far fetched to me.

> For extra credit, the node controller could add/update the stable labels on nodes to match the beta labels reported by legacy nodes until 1.16 when the oldest kubelets in the cluster would be known to report the new labels as well.

I'm not sure how likely this would happen (and likely may cause other issues), but I can do that if this is required.

**Comment by liggitt** [comment]
> > For extra credit, the node controller could add/update the stable labels on nodes to match the beta labels reported by legacy nodes until 1.16 when the oldest kubelets in the cluster would be known to report the new labels as well.
> 
> I'm not sure how likely this would happen (and likely may cause other issues), but I can do that if this is required.

If we don't do that, no one without intimate knowledge of the target cluster of their manifest can start using the new labels until ~1.16.

**Comment by bgrant0607** [comment]
To expand on @liggitt's comment, since supported node/control-plane version skew is 2 releases, in general the new node labels couldn't be depended upon until 2 releases after introduction.

**Comment by yujuhong** [comment]
> To expand on @liggitt's comment, since supported node/control-plane version skew is 2 releases, in general the new node labels couldn't be depended upon until 2 releases after introduction.

That's why kubelet reports both at the same time. This is a general problem for any new node label.

I will send a PR to add the labels in the node controller, so that folks can start relying the newer labels if they wish.
