### ISSUE TITLE
OpenStack cloud controller manager pod restart many times

### ISSUE THREAD

**Issue by openstacker** [kubernetes/kubernetes#72949]
**What happened**:
The pod of openstack cloud controller manager restarted many times. See below for the frequency. 
kube-system             openstack-cloud-controller-manager-bkw5n          1/1       Running   5         19d
kube-system             openstack-cloud-controller-manager-bkw5n          1/1       Running   13         25d
kube-system             openstack-cloud-controller-manager-bkw5n          1/1       Running   20         27d

**What you expected to happen**:
No restart.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not quite sure if it's can be reproduced with a kubeadm created cluster. My one is created by Magnum and recently we just support cloud controller manager, so could be related to the config.

**Anything else we need to know?**:
I can see below error with "logs --previous":
`I0115 01:57:11.394341       1 serving.go:318] Generated self-signed cert in-memory
W0115 01:57:12.458180       1 authentication.go:282] Cluster doesn't provide requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0115 01:57:12.460922       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0115 01:57:12.468085       1 controllermanager.go:107] Version: v0.0.0-master+$Format:%h$
W0115 01:57:12.468132       1 plugins.go:118] WARNING: openstack built-in cloud provider is now deprecated. Please use 'external' cloud provider for openstack: https://github.com/kubernetes/cloud-provider-openstack
I0115 01:57:13.050895       1 secure_serving.go:116] Serving securely on 127.0.0.1:10258
I0115 01:57:13.051495       1 leaderelection.go:187] attempting to acquire leader lease  kube-system/cloud-controller-manager...
E0115 01:58:30.260429       1 leaderelection.go:252] error retrieving resource lock kube-system/cloud-controller-manager: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints cloud-controller-manager)
I0115 01:59:08.204674       1 leaderelection.go:196] successfully acquired lease kube-system/cloud-controller-manager
I0115 01:59:08.205232       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"cloud-controller-manager", UID:"acfa9fc2-03b3-11e9-8fba-fa163e505144", APIVersion:"v1", ResourceVersion:"4088585", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' k8s-2-gl3nfz724udw-master-0.novalocal_e04ffcb3-1868-11e9-aded-fa163e505144 became leader
I0115 01:59:30.213848       1 leaderelection.go:231] failed to renew lease kube-system/cloud-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
F0115 01:59:30.308015       1 controllermanager.go:190] leaderelection lost
`

**Environment**:

- Kubernetes version (use `kubectl version`):
v1.11.2

- Cloud provider or hardware configuration:
OpenStack

- OS (e.g. from /etc/os-release):
Fedora Atomic 27

- Kernel (e.g. `uname -a`):

- Install tools:
OpenStack Magnum
- Others:

**Comment by openstacker** [comment]
@dims Any comments will be appreciated. Cheers.

**Comment by virtuman** [comment]
having exact same issue on baremetal k8s with just 3 nodes. first observed on v1.12.1, since then, upgraded to 1.12.3, issue persists. we use kubespray for cluster management and CentOS as the host OS.
