### ISSUE TITLE
Flaky test in TestBindAPIUpdate

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#72954]
**Which jobs are failing**:

pull-kubernetes-bazel-test

**Which test(s) are failing**:

https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72953/pull-kubernetes-bazel-test/72686/

**Since when has it been failing**:

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by liggitt** [comment]
the test failure seems related to the PR that is being tested

no other flakes have been observed: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestBindAPIUpdate

**Comment by cofyc** [comment]
I've run it against latest master locally and it may fail.

**Comment by dims** [comment]
@cofyc @liggitt - i can recreate it with `-race` https://paste.fedoraproject.org/paste/XT1OW8CqbdFJSOLbx-h2eA/raw

**Comment by Shnatsel** [comment]
@kubernetes/sig-testing
