### ISSUE TITLE
kubectl: enable nodeSelector updates from the command line

### ISSUE THREAD

**Issue by kmerker** [kubernetes/kubernetes#7296]
We saw in the flocker demo this command:

master$ kubectl get rc redis-master -o yaml | sed 's/spinning/ssd/' | kubectl update -f -

Should be able to do this with a kubectl command, not spitting out yaml, sed, and reading it back in.

**Comment by roberthbailey** [comment]
There's already a kubectl command to update labels on objects within the system, but not one to update the label selector of a replication controller.

**Comment by bgrant0607** [comment]
Would be a `kubectl set` command. #21648

**Comment by asalkeld** [comment]
I can pick this one up (doing it as a part of some create sub commands).

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by davidopp** [comment]
nodeSelector is kinda deprecated, should be using node affinity instead.

**Comment by kargakis** [comment]
I guess we will still need those `set` subcommands for setting/unsetting {pod,node} affinity from podspec-y things

**Comment by adohe** [comment]
yes, we did need this. Assign it to me and will open a PR asap.

**Comment by davidopp** [comment]
Of course keep in mind that updating the ReplicaSet won't have any effect on pods that are already running.

**Comment by kargakis** [comment]
Only ReplicaSets have this limitation.

On Sun, Apr 30, 2017 at 8:10 PM, David Oppenheimer <notifications@github.com

**Comment by adohe** [comment]
Thus I will document this to make it more clear.
