### ISSUE TITLE
kubeadm init  warning  Operating System: Kylin 4.0.2(arm64)   

### ISSUE THREAD

**Issue by guocaifeng** [kubernetes/kubernetes#72968]
How to solve this problem?

This is error info:   

Jan 16 21:52:49 greatwall-os dockerd[1670]: time="2019-01-16T21:52:49.798808940+08:00" level=warning msg="Seccomp is not enabled in your kernel, running container without default profile."
Jan 16 21:52:49 greatwall-os kubelet[22767]: E0116 21:52:49.815876   22767 kubelet.go:2266] node "greatwall-os" not found
Jan 16 21:52:49 greatwall-os kubelet[22767]: I0116 21:52:49.857805   22767 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Jan 16 21:52:49 greatwall-os kubelet[22767]: I0116 21:52:49.857861   22767 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Jan 16 21:52:49 greatwall-os kubelet[22767]: W0116 21:52:49.861684   22767 pod_container_deletor.go:75] Container "40daa00a9bac6e96de51523fa6524b4d1a565413f996e5d2928f7fd11a1085e2" not found in pod's containers
Jan 16 21:52:49 greatwall-os kubelet[22767]: E0116 21:52:49.916061   22767 kubelet.go:2266] node "greatwall-os" not found
Jan 16 21:52:49 greatwall-os kubelet[22767]: E0116 21:52:49.934935   22767 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.2.57.12:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.2.57.12:6443: connect: connection refused
Jan 16 21:52:49 greatwall-os dockerd[1670]: time="2019-01-16T21:52:49.943028560+08:00" level=warning msg="Seccomp is not enabled in your kernel, running container without default profile."
Jan 16 21:52:49 greatwall-os kubelet[22767]: E0116 21:52:49.952701   22767 event.go:212] Unable to write event: 'Patch https://10.2.57.12:6443/api/v1/namespaces/default/events/greatwall-os.157a57f9e02a3598: dial tcp 10.2.57.12:6443: connect: connection refused' (may retry after sleeping)
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.016269   22767 kubelet.go:2266] node "greatwall-os" not found
Jan 16 21:52:50 greatwall-os dockerd[1670]: time="2019-01-16T21:52:50.070356120+08:00" level=warning msg="Seccomp is not enabled in your kernel, running container without default profile."
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.123838   22767 kubelet.go:2266] node "greatwall-os" not found
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.154315   22767 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.2.57.12:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dgreatwall-os&limit=500&resourceVersion=0: dial tcp 10.2.57.12:6443: connect: connection refused
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.224030   22767 kubelet.go:2266] node "greatwall-os" not found
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.287464   22767 pod_workers.go:190] Error syncing pod 44b569a35761491825f4e7253fbf0543 ("kube-scheduler-greatwall-os_kube-system(44b569a35761491825f4e7253fbf0543)"), skipping: failed to "StartContainer" for "kube-scheduler" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-scheduler pod=kube-scheduler-greatwall-os_kube-system(44b569a35761491825f4e7253fbf0543)"
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.331677   22767 kubelet.go:2266] node "greatwall-os" not found
Jan 16 21:52:50 greatwall-os kubelet[22767]: W0116 21:52:50.367427   22767 docker_container.go:216] Cannot create symbolic link because container log file doesn't exist!
Jan 16 21:52:50 greatwall-os kubelet[22767]: E0116 21:52:50.367891   22767 remote_runtime.go:213] StartContainer "dd2253af6819c36fd4d8fdaa5d327054c2377a60da1d99bbf49e900313829559" from runtime service failed: rpc error: code = Unknown desc = failed to start container "dd2253af6819c36fd4d8fdaa5d327054c2377a60da1d99bbf49e900313829559": Error response from daemon: cannot join network of a non running container: 391e66aa5aac573fccb257d444ef876396a1876c60367b4856096ed53825703f

**Comment by neolit123** [comment]
hello, you can try out support channels and/or google for this:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

`Operating System: Kylin 4.0.2(arm64)`
we don't have test coverage for this OS and developers that use it.

/close
