### ISSUE TITLE
Several klog flags are not recognized by kube-proxy

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#72975]
**What happened**:
When trying to configure `kube-proxy` with the `--log-file` option, I got `error: unknown flag: --log_file`. I then tried every flag registered in `klog.InitFlags`, and noticed that several flags are not recognized:

| Flag Name | Recognized |
| --- | --- |
| "log_dir" | no |
| "log_file" | no |
| "logtostderr" | yes |
| "alsologtostderr" | yes |
| "v" | yes |
| "skip_headers" | no |
| "stderrthreshold" | yes |
| "vmodule" | yes |
| "log_backtrace_at" | no |

```
$ kube-proxy --version
Kubernetes v1.14.0-alpha.0.1225+4ef06e518d788b
```

**What you expected to happen**:
Expected the flag to be recognized.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kube-proxy --log_file=foo
```

- Kubernetes version (use `kubectl version`): v1.14.0-alpha.0.1225+4ef06e518d788b
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Happens on both Linux and Windows (for at least `--log_file`, the other flags I just tested on Linux).

/assign @dims

**Comment by dims** [comment]
@mtaufen looks like the `_`(s) get turned into `-`

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ _output/local/go/bin/kube-proxy --help 2>&1 | grep -e log-file -e log-dir -e skip-headers -e log-backtrace
      --log-backtrace-at traceLocation               when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                               If non-empty, write log files in this directory
      --log-file string                              If non-empty, use this log file
      --skip-headers                                 If true, avoid header prefixes in the log messages
dims@bigbox:~/go/src/k8s.io/kubernetes$ _output/local/go/bin/kube-proxy --version
Kubernetes v1.14.0-alpha.1.47+fdfd88588596c5
```

**Comment by mtaufen** [comment]
Shouldn't the normalize func correct for this?

**Comment by mtaufen** [comment]
For instance, I can pass the flag with an underscore or a hyphen on Kubelet.

**Comment by thockin** [comment]
I think component-base will help with this?

@luxas

**Comment by luxas** [comment]
> I think component-base will help with this?

Yes, definitely
