### ISSUE TITLE
gce-scale-performance regressed on pod-startup-time

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#72976]
gce-scale-performance regressed on pod-startup-time (there is very high flakiness now).

@mm4tt will provide more details on that tomorrow, 

This happened somewhere between runs 283 and 288 (there is strong hypothesis that between 283 and 284, but I'm not 100% convinced)

**Comment by wojtek-t** [comment]
I actually think that there might have been more regressions in the meantime

Looking into perf-dash, the interested graphs to look into are:
- latency of "patch node status"
- density request count of "pod status PUT"
- latency of "pods delete"
- latency of "get pods in namespace"

I think the first step would be to understand the difference in number of "pod status PUT".

But I tend to think now that there might have been even 3 separate regressions in that period (one between 283 and 284, another betweeen 285 and 288 and one more between 292 and 293).

@kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment]
@shyamjvs

**Comment by mm4tt** [comment]
I believe that the issue boils down to periods of slowness in the api server. Some examples and logs below:

Run: **294**
Pod: **density-latency-pod-3779-qvspw**
e2e startup latency: **9.885406939s**

Logs:
```
I0111 19:04:51.415414       1 event.go:221] Event(v1.ObjectReference{Kind:"ReplicationController", Namespace:"density-30-30-1899", Name:"density-latency-pod-3779", UID:"c3a81379-15d3-11e9-b622-42010a280002", APIVersion:"v1", ResourceVersion:"28387322", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: density-latency-pod-3779-qvspw                                                      
I0111 19:04:51.731571    1721 kubelet.go:1882] SyncLoop (ADD, "api"): "density-latency-pod-3779-qvspw_density-30-30-1899(c599fdcd-15d3-11e9-b622-42010a280002)"                                             
I0111 19:04:51.734906       1 scheduler.go:569] pod density-30-30-1899/density-latency-pod-3779-qvspw is bound successfully on node gce-scale-cluster-minion-group-4-0nfl, 500 nodes evaluated, 500 nodes were found feasible                                                                                                                                                                                           
I0111 19:04:51.806981    1721 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-db6pt" (UniqueName: "kubernetes.io/secret/c599fdcd-15d3-11e9-b622-42010$280002-default-token-db6pt") pod "density-latency-pod-3779-qvspw" (UID: "c599fdcd-15d3-11e9-b622-42010a280002")
I0111 19:04:51.908391    1721 reconciler.go:252] operationExecutor.MountVolume started for volume "default-token-db6pt" (UniqueName: "kubernetes.io/secret/c599fdcd-15d3-11e9-b622-42010a280002-default-tok$n-db6pt") pod "density-latency-pod-3779-qvspw" (UID: "c599fdcd-15d3-11e9-b622-42010a280002")
I0111 19:04:52.772208    1721 operation_generator.go:571] MountVolume.SetUp succeeded for volume "default-token-db6pt" (UniqueName: "kubernetes.io/secret/c599fdcd-15d3-11e9-b622-42010a280002-default-toke$-db6pt") pod "density-latency-pod-3779-qvspw" (UID: "c599fdcd-15d3-11e9-b622-42010a280002")
I0111 19:04:52.972279    1721 kuberuntime_manager.go:409] No sandbox for pod "density-latency-pod-3779-qvspw_density-30-30-1899(c599fdcd-15d3-11e9-b622-42010a280002)" can be found. Need to start a new on$
I0111 19:04:53.732152    1721 kubelet.go:1927] SyncLoop (PLEG): "density-latency-pod-3779-qvspw_density-30-30-1899(c599fdcd-15d3-11e9-b622-42010a280002)", event: &pleg.PodLifecycleEvent{ID:"c599fdcd-15d3$11e9-b622-42010a280002", Type:"ContainerStarted", Data:"f74c3d9a35a5a01d707e0535346b814b1c2979b2988346730a5511b4caae2053"}
I0111 19:04:54.753184    1721 kubelet.go:1927] SyncLoop (PLEG): "density-latency-pod-3779-qvspw_density-30-30-1899(c599fdcd-15d3-11e9-b622-42010a280002)", event: &pleg.PodLifecycleEvent{ID:"c599fdcd-15d3$11e9-b622-42010a280002", Type:"ContainerStarted", Data:"16dcee9beaa7180b6398ee4d7728946d9d334468ee2bc129e5b7c8373f60a37b"}
I0111 19:04:59.313316       1 wrap.go:47] GET /api/v1/namespaces/density-30-30-1899/pods/density-latency-pod-3779-qvspw: (4.271693365s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.227.107.23$:58182]
I0111 19:05:00.028802       1 wrap.go:47] PATCH /api/v1/namespaces/density-30-30-1899/pods/density-latency-pod-3779-qvspw/status: (456.940573ms) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.2$7.107.231:58182]
```
Interesting lines are the three last ones.  At 19:04:54.753184 the second container was started and then kublet wants to report pod as started in the api server. In order to do so it issues GET and then PATCH, but the GET takes over 4s. 

Below are **api server logs** around that time, as you can see all operations have latency ~4s.
```
I0111 19:04:59.313057       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-rjnq?resourceVersion=0&timeout=10s: (4.265717848s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.190.134.239:45514]
I0111 19:04:59.313068       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-71dz?resourceVersion=0&timeout=10s: (4.264493738s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.231.69.55:46996]
I0111 19:04:59.313082       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-wgxn?resourceVersion=0&timeout=10s: (4.252180741s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.196.248.226:58798]
I0111 19:04:59.313091       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-4-0jvv?resourceVersion=0&timeout=10s: (4.250959954s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.243.147.176:38096]
I0111 19:04:59.313210       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-3-jmw9?resourceVersion=0&timeout=10s: (4.250904594s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.185.61.246:46186]
I0111 19:04:59.313249       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-b5p6?resourceVersion=0&timeout=10s: (4.246893158s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.237.71.210:48402]
I0111 19:04:59.313261       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-2jw0?resourceVersion=0&timeout=10s: (4.245968574s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.237.210.15:57562]
I0111 19:04:59.313273       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-2-9sjh?resourceVersion=0&timeout=10s: (4.240693196s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.243.208.241:49992]
I0111 19:04:59.313297       1 wrap.go:47] PATCH /api/v1/nodes/gce-scale-cluster-minion-group-3-wh6b/status: (4.330334645s) 200 [node-problem-detector/v0.5.0-49-gfb81368 104.196.115.188:38076]
I0111 19:04:59.313307       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-2-lfg0?resourceVersion=0&timeout=10s: (4.230141708s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 104.196.44.232:45520]
I0111 19:04:59.313316       1 wrap.go:47] GET /api/v1/namespaces/density-30-30-1899/pods/density-latency-pod-3779-qvspw: (4.271693365s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.227.107.231:58182]
I0111 19:04:59.313324       1 wrap.go:47] PATCH /api/v1/nodes/gce-scale-cluster-minion-group-3-j6vg/status: (4.328273898s) 200 [node-problem-detector/v0.5.0-49-gfb81368 35.196.61.213:42242]
I0111 19:04:59.313345       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-41pk?resourceVersion=0&timeout=10s: (4.230734541s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.237.253.140:47538]
I0111 19:04:59.313359       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-4m8w?resourceVersion=0&timeout=10s: (4.221886431s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 104.196.101.96:40762]
I0111 19:04:59.313371       1 wrap.go:47] GET /api/v1/namespaces/density-30-34-5877/secrets?fieldSelector=metadata.name%3Ddefault-token-c76k2&resourceVersion=25988339&timeout=9m20s&timeoutSeconds=560&watch=true: (9m20.00258561s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.196.65.147:35272]
I0111 19:04:59.313388       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-95sx?resourceVersion=0&timeout=10s: (4.262390757s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.243.220.138:54984]
I0111 19:04:59.313399       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-2-t3ch?resourceVersion=0&timeout=10s: (4.218209351s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.196.194.94:39628]
I0111 19:04:59.313411       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-4-51z2?resourceVersion=0&timeout=10s: (4.217717853s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.243.191.34:52676]
I0111 19:04:59.313447       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-2-hc8q?resourceVersion=0&timeout=10s: (4.220031264s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 104.196.145.73:51906]
I0111 19:04:59.313458       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-ljxs?resourceVersion=0&timeout=10s: (4.217537806s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 104.196.109.99:39378]
I0111 19:04:59.313481       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-4-nt6n?resourceVersion=0&timeout=10s: (4.217413696s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/40de2ee 35.227.94.95:51710]
```

I checked few other pods with worst e2e latency in run 294 and all of them were more or less the same (pod was started in a timely manner, but it took super long to report it to the api server).

I also checked other runs and similar situation happens in all of the recent failures. E.g. run **296** (the most recent one), pod: **density-latency-pod-1325-dcjbg**

Logs:
```                                                                                        
I0116 19:05:12.330341       1 event.go:221] Event(v1.ObjectReference{Kind:"ReplicationController", Namespace:"density-30-26-9983", Name:"density-latency-pod-1325", UID:"a44592e1-19c1-11e9-91d2-42010a280002", APIVersion:"v1", ResourceVersion:"28531284", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: density-latency-pod-1325-dcjbg                                                      
I0116 19:05:12.364761    1746 kubelet.go:1882] SyncLoop (ADD, "api"): "density-latency-pod-1325-dcjbg_density-30-26-9983(a6474538-19c1-11e9-91d2-42010a280002)"
I0116 19:05:12.367698       1 scheduler.go:569] pod density-30-26-9983/density-latency-pod-1325-dcjbg is bound successfully on node gce-scale-cluster-minion-group-hxwz, 500 nodes evaluated, 500 nodes wer$ found feasible
I0116 19:05:12.524617    1746 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-775bk" (UniqueName: "kubernetes.io/secret/a6474538-19c1-11e9-91d2-42010$280002-default-token-775bk") pod "density-latency-pod-1325-dcjbg" (UID: "a6474538-19c1-11e9-91d2-42010a280002")
I0116 19:05:12.625582    1746 reconciler.go:252] operationExecutor.MountVolume started for volume "default-token-775bk" (UniqueName: "kubernetes.io/secret/a6474538-19c1-11e9-91d2-42010a280002-default-tok$n-775bk") pod "density-latency-pod-1325-dcjbg" (UID: "a6474538-19c1-11e9-91d2-42010a280002")
I0116 19:05:12.647422    1746 operation_generator.go:571] MountVolume.SetUp succeeded for volume "default-token-775bk" (UniqueName: "kubernetes.io/secret/a6474538-19c1-11e9-91d2-42010a280002-default-toke$-775bk") pod "density-latency-pod-1325-dcjbg" (UID: "a6474538-19c1-11e9-91d2-42010a280002")
I0116 19:05:12.682428    1746 kuberuntime_manager.go:409] No sandbox for pod "density-latency-pod-1325-dcjbg_density-30-26-9983(a6474538-19c1-11e9-91d2-42010a280002)" can be found. Need to start a new on$
I0116 19:05:13.367038    1746 kubelet.go:1927] SyncLoop (PLEG): "density-latency-pod-1325-dcjbg_density-30-26-9983(a6474538-19c1-11e9-91d2-42010a280002)", event: &pleg.PodLifecycleEvent{ID:"a6474538-19c1$11e9-91d2-42010a280002", Type:"ContainerStarted", Data:"cb0289084e5f7216281dc8ff29d5e648f3e5e76a8e00c87a0dd7f17771add754"}
I0116 19:05:14.384838    1746 kubelet.go:1927] SyncLoop (PLEG): "density-latency-pod-1325-dcjbg_density-30-26-9983(a6474538-19c1-11e9-91d2-42010a280002)", event: &pleg.PodLifecycleEvent{ID:"a6474538-19c1$11e9-91d2-42010a280002", Type:"ContainerStarted", Data:"ce22c77248b69a3a4f4692eccc21875baa23c3c2d00d8875f7d0dc2876d9dd5c"}
I0116 19:05:18.804653       1 wrap.go:47] GET /api/v1/namespaces/density-30-26-9983/pods/density-latency-pod-1325-dcjbg: (4.140722625s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/06e1af7 35.243.227.89$46388]
I0116 19:05:20.328053       1 wrap.go:47] PATCH /api/v1/namespaces/density-30-26-9983/pods/density-latency-pod-1325-dcjbg/status: (1.074063434s) 200 [kubelet/v1.14.0 (linux/amd64) kubernetes/06e1af7 35.2$3.227.89:46388]
```
Get pod also took over 4s. 

Focusing back on run 294, we checked the [etcd logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/294/artifacts/gce-scale-cluster-master/etcd.log) around the time the api server slowness occurred, but nothing interesting was found there. 
What's more in the api server we log the trace information if an etcd operation takes too long. In case of Get we log trace if an operation takes longer than 500ms (see [here](https://github.com/kubernetes/kubernetes/blob/3ed107ff0e23c0ca434865b1a3608be21b11601f/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L52)), but no trace was found in the apiserver log for any of the slow operations. It means that we can exclude etcd as a culprit here. The slowness seems to be coming from the api server itself. I'll examine the pprof files we collect for the api-server to see if there is anything interesting there.

**Comment by wojtek-t** [comment]
Re above:

1, The logs from apiserver are interesting. The GET requests there have "resourceVersion=0:, which means they are served from cache - they are not even hitting etcd.
So (even if there are problems in etcd), they are not the only ones.

2. pprof aren't very useful for debuggin - they are giving more "generic picture". So it's not surprising they aren't helpful here.

3. @mm4tt - couple things we need to understand are:
- at the time of slowness, were there more requests hitting apiserver than usually?
- were we maybe serving some "large list" requests (a number of components relisting whole state?)

In general, from the graphs that I was looking yesterday at, it seems that number of some requests (PUT pod status) were visibly increased  that is something we also need to understand where they are coming from

**Comment by mm4tt** [comment]
I'm working on a script to analyze api-server log to answer the questions from 3. Will post the results here once I have them.

**Comment by mborsz** [comment]
We tried to debug this with @mm4tt 

pod_startup graph shows that the increase of latency happened between 284 and 285.
![wzslj1kwk8l](https://user-images.githubusercontent.com/2559168/51323904-b27dfc00-1a69-11e9-9202-e1a46f403037.png)

This perfectly correlates with
![7oxcjwennt0](https://user-images.githubusercontent.com/2559168/51323982-dc372300-1a69-11e9-8813-cc8431b5cd0e.png)

Between 284 and 285 we have a couple of changes: 
https://github.com/kubernetes/kubernetes/compare/c3e60b6e1...d257ee9bf
https://github.com/kubernetes/kubernetes/commit/6515c4e09b37c530df38f55e1f02912398c5bff1 seems to be responsible for increased scheduling throughput.

My understanding is that increased scheduling throughput somehow affects the apiserver latency.

We also see tons of changes in request counts (e.g. PUT pod status @wojtek-t mentioned), but none of them happened between 284 and 285 (they are 290+ usually), so I wouldn't focus on them for now.

**Comment by wojtek-t** [comment]
Yes - that commit bumped scheduler throughput.

However - I'm not convinced why this would cause such behavior.
In the phase of "scheduling latency pods", we are creating them once per 200ms, so scheduler throughput doesn't matter - we were able to immediately schedule them no matter what the scheduler was. And before creating the first latency pod, we wait for all saturation pods to be successfully started.

So while I could believe that that change may result in higher latencies of api calls (i.e. higher load of apiserver) during different phases of the test, during the phase of "latency pods", it shouldn't matter.

**Comment by mm4tt** [comment]
We think we've found a plausible explanation. 

Looking at the apiserver latency/num_requests graphs below we realized that the slowness period occurs directly after the log rotate.

### Run 254
![254](https://user-images.githubusercontent.com/2604887/51385965-19122100-1b21-11e9-8d4e-4130e03cd362.png)

### Run 256
![256](https://user-images.githubusercontent.com/2604887/51385971-1d3e3e80-1b21-11e9-94f6-cafa8236939f.png)

A crucial observation here is that we enabled apiserver-audit logs starting from run 284 (more or less when the regression started). Audit logs are as big as apiserver logs, which in the end puts much bigger strain on the log-rotate. Each log-rotate run needs to process now over a dozen GBs of logs, which may block master's disk and as a result slow down the api server (assuming that api server has some disk blocking operations, e.g. audit logging may be blocking - we weren't able to rule that out). Master's disk in a 5K node test cluster is currently a non-ssd 100GB disk, which doesn't guarantee a high throughput. 

We'll test the above hypothesis by running tests with different the log-rotate frequency (change from 1h to 5m) and upgrading master's disk.

Will post the results here as soon as we have them.

**Comment by shyamjvs** [comment]
Out of curiosity - hasn't audit-logging and log-rotation been there for a while already in our tests? This one seems like recent regression.

**Comment by wojtek-t** [comment]
It should have been, but it wasn't: https://github.com/kubernetes/test-infra/pull/10479

**Comment by mm4tt** [comment]
The log-rotate change seems to be fixing the pod run-to-watch latency.
![run_to_watch](https://user-images.githubusercontent.com/2604887/51477978-54fbef00-1d8a-11e9-9ed9-3b11e8a999eb.png)

Unfortunately, the 99th percentile of the e2e pod startup latency is still above the limit. As @wojtek-t said, probably there is another regression involved here.

**Comment by mm4tt** [comment]
As per our understanding, the other regression is this one - https://github.com/kubernetes/kubernetes/issues/73176

**Comment by mm4tt** [comment]
The issue seems to be fixed now. Last two run of the gce scale performance have passed.
The 99th percentile of the pod startup latency went down to ~4s:
![pjde8vor5jy](https://user-images.githubusercontent.com/2604887/51896195-301c0300-23ac-11e9-8094-43c6d3c4399f.png)

The PRs that contributed to the fix are:
  * https://github.com/kubernetes/kubernetes/pull/72062
  * https://github.com/kubernetes/test-infra/pull/10822
  * https://github.com/kubernetes/test-infra/pull/10823
  * https://github.com/kubernetes/test-infra/pull/10899

**Comment by wojtek-t** [comment]
@mm4tt - can you remove the "temporary todo" comments, given that we want to leave the bigger disks for audit logs?

**Comment by mm4tt** [comment]
Sure, I'm working on that. Will send a PR shortly.
