### ISSUE TITLE
Allow volume limits to be configured via openstack.conf

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#72988]
We merged https://github.com/kubernetes/kubernetes/pull/72980 to allow configurable volume limits for Cinder. But @dims proposed adding such a limit to openstack.conf as well, among other things this will enable us to support node specific limits more easily - https://github.com/kubernetes/kubernetes/issues/69280 

/sig openstack
/sig storage
/sig scheduling

**Comment by gnufied** [comment]
cc @ravisantoshgudimetla

**Comment by hogepodge** [comment]
What would be the extent of the modification? It must not break current compatibility, and the in-tree provider is scheduled for removal this year. I'm ok with it as long as existing users aren't broken by it.

**Comment by gnufied** [comment]
@hogepodge it should be a change into openstack.conf which would add a new configurable field. It would be backward compatible but would allow admins to configure different limits on a node if they must.

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release.  Please `/milestone clear` if I am incorrect
