### ISSUE TITLE
Using subPath with hostPath results in wrong mounting

### ISSUE THREAD

**Issue by mikkeloscar** [kubernetes/kubernetes#72991]
**What happened**: We are running [kubelet from a rkt container on Container
Linux](https://github.com/zalando-incubator/kubernetes-on-aws/blob/a1eb8393e378aed8923b08822c32a50fa4d09bce/cluster/node-pools/worker-default/userdata.clc.yaml#L130-L193) (ignore the v1.11.6 kubelet version, this was also tested on `v1.13.2`), and when creating a pod which specifies a `subPath` for mounting a `hostPath` then the resulting mount is not at the `hostPath` location but rather inside the rkt container rootfs of the kubelet container.

1. create a pod with volume mount (see manifest below) and exec into it:

```bash
$ kubectl exec -it test-subpath-hostpath bash
# create file at mountpoint
> touch /data/my_unique_file
```

2. login to node via ssh and locate the file created. We would expect it to be
   under `/data/disk0/my-app/my_unique_file`:

```bash
# login to node via ssh
> find / -name "my_unique_file"
/var/lib/rkt/pods/run/8e87b57e-1cde-4a0c-8fa1-a2c7fc2029fd/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/pods/ed0c591b-19d6-11e9-8d20-02978c36acf4/volume-subpaths/data/nginx/0/my_unique_file
/var/lib/rkt/pods/run/8e87b57e-1cde-4a0c-8fa1-a2c7fc2029fd/stage1/rootfs/opt/stage2/hyperkube/rootfs/data/disk0/my-app/my_unique_file
/var/lib/kubelet/pods/ed0c591b-19d6-11e9-8d20-02978c36acf4/volume-subpaths/data/nginx/0/my_unique_file
```

In our setup `/data/disk0` is on a dedicated SSD with 300GB space, so it
doesn't make sense to put the data on the 50GB root disk where the rkt overlay
is located:

```bash
> df -h
...
/dev/nvme1n1     275G   65M  260G   1% /data/disk0
overlay           47G  2.9G   42G   7% /var/lib/rkt/pods/run/8e87b57e-1cde-4a0c-8fa1-a2c7fc2029fd/stage1/rootfs/opt/stage2/hyperkube/rootfs
...
```

If we create the same pod, but without `subPath` then we would expect the file
to be under `/data/disk0/my_unique_file`, which is also the case:

```bash
$ kubectl exec -it test-subpath-hostpath bash
# create file at mountpoint
> touch /data/my_unique_file
```

From the node point of view:

```bash
# login to node via ssh
> find / -name "my_unique_file"
/data/disk0/my_unique_file
```

**What you expected to happen**: I expected the mount to be under the real
`hostPath` of the node. This works fine when **NOT** using `subPath`.

**How to reproduce it (as minimally and precisely as possible)**:

By creating the following pod in a cluster with nodes with a hostPath:
`/data/disk0`:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-subpath-hostpath
  labels:
    app: test-subpath-hostpath
spec:
  containers:
  - name: nginx
    image: k8s.gcr.io/nginx-slim:0.8
    volumeMounts:
    - name: data
      mountPath: /data
      subPath: my-app # when removing this, it works!
  volumes:
  - hostPath:
      path: /data/disk0
      type: Directory
    name: data
```

Creating the same pod without the `subPath` specified works as expected.

**Anything else we need to know?**:

I mention that we are running `kubelet` as a rkt container because I saw
similar issues (#61456) and think that might be quite relevant to this bug.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.13.2`
- Cloud provider or hardware configuration: https://github.com/zalando-incubator/kubernetes-on-aws
- OS (e.g. from /etc/os-release):
  ```
  $ cat /etc/os-release
  NAME="Container Linux by CoreOS"
  ID=coreos
  VERSION=1800.7.0
  VERSION_ID=1800.7.0
  BUILD_ID=2018-08-15-2254
  PRETTY_NAME="Container Linux by CoreOS 1800.7.0 (Rhyolite)"
  ANSI_COLOR="38;5;75"
  HOME_URL="https://coreos.com/"
  BUG_REPORT_URL="https://issues.coreos.com"
  COREOS_BOARD="amd64-usr"
  ```
- Kernel (e.g. `uname -a`): `Linux ip-10-149-64-119.eu-central-1.compute.internal 4.14.63-coreos #1 SMP Wed Aug 15 22:26:16 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`
- Install tools: https://github.com/zalando-incubator/kubernetes-on-aws
- Others:

**Comment by JishanXing** [comment]
Hi，

I followed your step but cannot reproduce this issue, please confirm whether there is anything I missed.
1) the pod
apiVersion: v1
kind: Pod
metadata:
  name: test-subpath-hostpath
  labels:
    app: test-subpath-hostpath
spec:
  containers:
  - name: nginx
    image: **ubuntu**
    **command:
        - sleep
        - "3600"**
    volumeMounts:
    - name: data
      mountPath: /data
      subPath: my-app # when removing this, it works!
  volumes:
  - hostPath:
      path: /data/disk0
      type: Directory
    name: data

2)
kubectl exec -it test-subpath-hostpath bash
root@test-subpath-hostpath:/# touch /data/my_unique_file

3) Go to my node,
 ls /data/disk0/my-app/my_unique_file
/data/disk0/my-app/my_unique_file

Thanks

**Comment by JishanXing** [comment]
Hi，

I followed your step but cannot reproduce this issue, please confirm whether there is anything I missed.
1) the pod
<pre><code>
apiVersion: v1
kind: Pod
metadata:
  name: test-subpath-hostpath
  labels:
    app: test-subpath-hostpath
spec:
  containers:
  - name: nginx
    image: ubuntu
    command:
        - sleep
        - "3600"
    volumeMounts:
    - name: data
      mountPath: /data
      subPath: my-app # when removing this, it works!
  volumes:
  - hostPath:
      path: /data/disk0
      type: Directory
    name: data
</code></pre>

2)
kubectl exec -it test-subpath-hostpath bash
root@test-subpath-hostpath:/# touch /data/my_unique_file

3) Go to my node,
 ls /data/disk0/my-app/my_unique_file
/data/disk0/my-app/my_unique_file

Thanks

**Comment by JishanXing** [comment]
My version

 kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp", GitCommit:"90febef3a98de5efb2e1248525e24a57e01ad386", GitTreeState:"c
lean", BuildDate:"2018-09-04T08:03:44Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean
", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mikkeloscar** [comment]
Your test looks correct, but how is `kubelet` running in your setup? I suspect it's related to us running it in a rkt container which makes `subPath` do the wrong thing.

**Comment by JishanXing** [comment]
I am running kubectl locally but not in container, maybe that's the key difference.

**Comment by omadawn** [comment]
We are experiencing the same issue. 

We are running the kubelet in rkt

I've seen this issue in 1.11.6 and 1.10.11

# 1.10 cluster version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

# 1.11 cluster version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by outception** [comment]
It results in creating an overlay automatically, not using the volume special by hostPath.

**Comment by OJFord** [comment]
/remove-lifecycle rotten

Thank you for opening this issue, I've been bitten by this too, and who knows how much longer it would have taken me to try without `subPath`!

```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

I'm not using rkt.

I don't know what's being mounted when I have `subPath` specified, the permissions look as expected, but the directory's empty - perhaps it's creating it because it thinks it doesn't exist? (Which is default `hostPath` behaviour.)

If I remove `subPath`, there the files are, just under the previously specified sub path instead of directly on the mount point.

**Comment by OJFord** [comment]
Actually, it's weirder - the `subPath` _is_ mounted at the correct location, and files in the sub path root are correctly shared.

However, a _directory_ within that `subPath`, when written to in the container, goes to:
```
/var/lib/kubelet/pods/<uuid>/volume-subpaths/<volname>/<containername>/0/<dirname>/<fname>
```
and not the mounted `hostPath`.

**Comment by outception** [comment]
not every version fo k8s have this bug:

v1.13.4 √ (Ubuntu)
v1.14.1 × (DigitalOcean)
v1.15.0 √ (Minikube)

**Comment by OJFord** [comment]
@outception Does your 'x' mean 'does not have issue'? Because my reproduction _was_ 1.14.1.

**Comment by mikkeloscar** [comment]
Just FYI: we don't see this issue after we switched from Container Linux and running kubelet via rkt to now running kubelet as a systemd service in ubuntu.
