### ISSUE TITLE
External metric name does not work with uppercase letters

### ISSUE THREAD

**Issue by dturn** [kubernetes/kubernetes#72996]
**What happened**:
HPA external metric names with uppercase letters do not work.

**What you expected to happen**:

I expect that metric names with upper case letters will work.

**How to reproduce it (as minimally and precisely as possible)**:

Make sure that the metric is available: 
```
> kubectl --context tierstaging-central get --raw  "/apis/external.metrics.k8s.io/v1beta1/namespaces/hpa-staging/Hpa.staging.request_time.median" | jq .                                               

{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/hpa-staging/Hpa.staging.request_time.median"
  },
  "items": [
    {
      "metricName": "Hpa.staging.request_time.median",
      "metricLabels": {
        "cluster-name": "tierstaging-central"
      },
      "timestamp": "2019-01-04T22:30:01Z",
      "value": "11"
    }
  ]
}
```

Deploy an app with a minimal HPA:

```
 > cat hpa.yml
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  metrics:
  - type: External
    external:
      metricName: Hpa.staging.request_time.median
      metricSelector:
        matchLabels:
          cluster-name: tierstaging-central
      targetAverageValue: 13
```

It fails where the relevant part of the error is `no metrics returned from external metrics API`

```
> kubectl --context tierstaging-central -n hpa-staging get hpa web-hpa -o yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2018-12-07T21:06:19Z","reason":"SucceededGetScale","message":"the
      HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2018-12-07T21:06:19Z","reason":"FailedGetExternalMetric","message":"the
      HPA was unable to compute the replica count: unable to get external metric hpa-staging/Hpa.staging.request_time.median/\u0026LabelSelector{MatchLabels:map[string]string{cluster-name:
      tierstaging-central,},MatchExpressions:[],}: no metrics returned from external
      metrics API"}]'
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"External","external":{"metricName":"Hpa.staging.request_time.median","metricSelector":{"matchLabels":{"cluster-name":"tierstaging-central"}},"targetAverageValue":"13"}}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"web-hpa","namespace":"hpa-staging"},"spec":{"maxReplicas":4,"metrics":[{"external":{"metricName":"Hpa.staging.request_time.median","metricSelector":{"matchLabels":{"cluster-name":"tierstaging-central"}},"targetAverageValue":13},"type":"External"}],"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"web"}}}
  creationTimestamp: "2018-12-07T21:06:04Z"
  name: web-hpa
  namespace: hpa-staging
  resourceVersion: "244467318"
  selfLink: /apis/autoscaling/v1/namespaces/hpa-staging/horizontalpodautoscalers/web-hpa
  uid: e8b6b960-fa63-11e8-af04-42010a800041
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
status:
  currentReplicas: 2
  desiredReplicas: 0
```

This comes from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/metrics/pkg/client/external_metrics/client.go#L83 and
https://github.com/kubernetes/client-go/blob/e6b0ffda95bb53fab6259ebc653a0bbd3e826d9d/rest/request.go#L428

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
k version --context tierstaging-central       
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:51:55Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.4", GitCommit:"0c81dc1e8c26fa2c47e50072dc7f98923cb2109c", GitTreeState:"clean", BuildDate:"2018-12-07T00:22:06Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: gke

**Comment by CharlyF** [comment]
@MaciekPytel, interesting - I am having the same issue but with `:` in labels.
Do you think the community would be interested in extending the regex to support `/` and `:` ?

With regards to your solution, have you considered using the annotations of the HPA to specify values that would otherwise not be supported ?

**Comment by MaciekPytel** [comment]
It's similar issue with labels - since the whole mechanism is based on Kubernetes label selector it must obey rules defined for those: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set.

I don't expect anyone will agree to change how Kubernetes labels work just for HPA, so the only way to get different characters would be to use a different mechanism for metric labels. 
We considered just using a key-value map of labels, but that has the problem of how do you do a more complex query? Using label selectors gives us the `matchExpressions` syntax.

In both cases (labels and metric names) the problem is not passing it to HPA. It's how HPA could pass it to metrics adapter. Technically it is requesting a resource from aggregated api server and that request must be compatible with how Kubernetes works internally.

**Comment by dturn** [comment]
Thanks everyone for the discussion. I think we're all on the same page and can close this issue. Feel free to re-open if anyone disagrees.
