### ISSUE TITLE
kubectl v1.13.2 is not available at the Google cloud storage

### ISSUE THREAD

**Issue by it-praktyk** [kubernetes/kubernetes#72990]
**What happened**:
When I try to download the newest kubectl tool using the command described in the documentation https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl error is returned 

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl</Details></Error>%  
```
It looks like the file is not correctly stored at the Google cloud.

**What you expected to happen**:
The binary kubectl file will be retrieved.

**How to reproduce it (as minimally and precisely as possible)**:
Use the command
```
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
```
The sub-part related to the retrieve the version returns: 'v1.13.2'

**Anything else we need to know?**:
If something was changed in releasing of the kubectl tool the documentation of 
- Kubernetes: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl
- Minikube: https://github.com/kubernetes/minikube
has to be updated.

**Comment by it-praktyk** [comment]
The issue is still unresolved.

**Comment by it-praktyk** [comment]
I've found that issue is related to the [Zsh shell](https://www.zsh.org/).

By pasting the command 
```
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
```
the braces are escaped and the command in the terminal looks like
```
curl -LO https://storage.googleapis.com/kubernetes-release/release/$\(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt\)/bin/linux/amd64/kubectl
```

**Comment by bCom5** [comment]
For those that don't notice, it is a \ after $ and a \ after .txt
