### ISSUE TITLE
Bad default config file for arch linux installations

### ISSUE THREAD

**Issue by BDague** [kubernetes/kubernetes#73006]
**What happened**:
-Kubelet wouldn't start. 
-I looked through the logs, found a strange "command not found error", followed by the name of the config file (/etc/kubernetes/kubeconfig)
Here's the offending line:
KUBELET_KUBECONFIG=/etc/kubernetes/kubelet.kubeconfig

**What you expected to happen**:
The line should look like this:
KUBELET_KUBECONFIG="--bootstrap-kubeconfig /etc/kubernetes/kubelet.kubeconfig"

**How to reproduce it (as minimally and precisely as possible)**:
Install kubernetes on an Arch Linux system, I got this error on a fresh install.
**Anything else we need to know?**:
Basically, the default config file is trying to pass in a raw filename as an argument.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", 
GitTreeState:"archive", 
BuildDate:"2019-01-17T04:56:36Z", 
GoVersion:"go1.11.4", 
Compiler:"gc", 
Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
None (Local Desktop)
- OS (e.g. from /etc/os-release):
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

- Kernel (e.g. `uname -a`):
Linux SUPERCX1 4.19.15-1-lts #1 SMP Sun Jan 13 13:53:52 CET 2019 x86_64 GNU/Linux 
- Install tools:
pacaur package manager
- Others:

/sig bug

**Comment by neolit123** [comment]
hello, where are you downloading the kubelet package from?
do you have a link for the actual package?

please mind that if it's not from the official kubernetes repository we cannot support this bug report:
https://packages.cloud.google.com

/sig release
/sig cluster-lifecycle
/priority awaiting-more-evidence
