### ISSUE TITLE
Not getzone for vsphere cloud provider if users don't want to get zone/region

### ISSUE THREAD

**Issue by celiawa** [kubernetes/kubernetes#73002]
#

**What would you like to be added**:
Hope that if user doesn't need to get zone for vSphere Cloud provider,  it won't trigger  the list attached tags action.

That is if users don't provider [Labels] field, the it will not try to query the zones. 

[Global] 
       ...
[WorkSpace]
       ...
[Network]
       ...
[Labels]
       zone = "k8s-io-zone"
       region = "k8s-io-region"

If users don't provide [Labels] field, then the behavior will be the same as the old version.

**Why is this needed**:
In our environment, we didn't provider [Labels] field in the vsphere.conf, and we don't need to get zones or regions for the nodes.  kubelet service failed to start because our vcenter account has no privilege to access REST API https://10.42.40.10:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags. 
In the the REST API page mentioned that " To invoke this operation, you need the read privilege on the input object.".   But mostly our account has no such permission. 

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/cis/tagging/tag_association.list_attached_tags-operation.html

Jan 16 08:07:27 bcmtmonster-manager-1 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jan 16 08:07:27 bcmtmonster-manager-1 kubelet[9308]: F0116 08:07:27.918962    9308 kubelet.go:1354] Kubelet failed to get node info: failed to get zone from cloud provider: POST https://10.42.40.10:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 403 Forbidden
Jan 16 08:07:27 bcmtmonster-manager-1 kubelet[9308]: E0116 08:07:27.918935    9308 vsphere.go:1405] Get zone for node bcmtmonster-manager-1: POST https://10.42.40.10:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 403 Forbidden
Jan 16 08:07:27 bcmtmonster-manager-1 kubelet[9308]: E0116 08:07:27.918563    9308 vsphere.go:1358] Cannot list attached tags. Get zone for node bcmtmonster-manager-1: POST https://10.42.40.10:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 403 Forbidden

**Comment by celiawa** [comment]
@jiatongw  Hi, I saw you submitted this PR https://github.com/kubernetes/kubernetes/pull/66795. Could you please help to look at my issue request. Thanks.

**Comment by jiatongw** [comment]
@celiawa Hi, thanks for the issue.  Do you have a valid vCenter license?

**Comment by pkqsun** [comment]
@jiatongw, we use a trial version of vcenter. Does is matter for this feature?

**Comment by jiatongw** [comment]
@pkqsun Just curious, I didn't aware of this kind of problem before. I can submit a PR, but I am not the owners. Let me contact them first.

**Comment by jiatongw** [comment]
@pkqsun Hi, could you refer to this issue #73307 ? The discussions may be a help

**Comment by subramanian-neelakantan** [comment]
@celiawa with this PR https://github.com/kubernetes/kubernetes/pull/72687, VCP will attempt to fetch zone information only if the vsphere.conf has the _[Labels]_ entry. Could you confirm this works for you and close this issue?

**Comment by celiawa** [comment]
Thanks @jiatongw, @subramanian-neelakantan.
