### ISSUE TITLE
DNS requires trailing '.' to resolve hosts outside of local network

### ISSUE THREAD

**Issue by Falconx1000** [kubernetes/kubernetes#73004]
I have a Kubernetes cluster setup using rancher 2.0 to provision the cluster on bare-metal nodes. DNS lookups inside the cluster work fine as well as lookups for hosts on the local network. All lookups are done in a test pod running on the cluster. 

bash-4.4# nslookup kubernetes #Kubernetes DNS test
Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   kubernetes.default.svc.cluster.local
Address: 10.43.0.1

bash-4.4# nslookup mysql-mysql.mysql #Test to another namespace
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   mysql-mysql.mysql.svc.cluster.local
Address: 10.43.158.48

bash-4.4# nslookup deepsea #Test to local server not connected to kubernetes cluster
Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   deepsea.falconindustries.ca
Address: 10.0.0.139

bash-4.4# nslookup www.google.ca #Test to host on the internet does not work
Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   www.google.ca.falconindustries.ca
Address: XXX.XXX.XXX.XXX
Name:   www.google.ca.falconindustries.ca
Address: *IPV6 PUBLIC ADDRESS*

bash-4.4# nslookup www.google.ca**.** #Test to same host works when trailing '.' is added
Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   www.google.ca
Address: 172.217.1.163
Name:   www.google.ca
Address: 2607:f8b0:400b:809::2003

All servers can lookup google.ca without the trailing '.' This is only required for kubernetes pods.
/sig DNS

**Comment by fntlnz** [comment]
@Falconx1000 can you give us more info about your setup?
Please look at the [bug-report issue template](https://github.com/kubernetes/kubernetes/issues/new?labels=kind%2Fbug&template=bug-report.md) and add here the information required in it to help us understand and reproduce your problem.

**Comment by Falconx1000** [comment]
**How to reproduce it (as minimally and precisely as possible)**:
Deploy Kubernetes 1.11.5 with Rancher 2.1.4 on to 4 nodes. deployed nicolaka/netshoot docker container for network testing. DNS lookups inside the cluster work fine as well as lookups for hosts on the local network.
**What happened**:
nslookup outside of LAN attempts to add search domain if tailing period is not added to the lookup
**What you expected to happen**:
nslookup would find ip address for www.google.ca
**Anything else we need to know?**:
Mistakenly written without the rest of the template. Host servers have no issues looking up hots on the internet. Hosts receive dhcp address from pfsense firewall which also provides dns resolver.
**Environment**: 
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: 4 bare-metal nodes 
- OS (e.g. from /etc/os-release):
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
- Kernel (e.g. `uname -a`): Linux ceph-osd0 4.12.14-lp150.12.28-default #1 SMP Mon Dec 3 16:46:15 UTC 2018 (b91289f) x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Ceph Nautilus and salt minions are deployed on the same nodes. nodes are running infiniband for ceph backend networking
- Others:

**Comment by Falconx1000** [comment]
Looking more into name resolving this appears to be the same issue as #64924
