### ISSUE TITLE
RollingUpdate for daemonset got stuck due to one of the daemonset pods being in unknown state

### ISSUE THREAD

**Issue by sagarkrsd** [kubernetes/kubernetes#73011]
**What happened**:
RollingUpdate for daemonset got stuck due to one of the daemonset pods being in unknown state

**What you expected to happen**:

We expected the rolling update to select a pod which is not in **unknown** state or atleast if it selects a pod with **unknown** state then it should have some default timeout so that it can select one of the other pods for update.
However, when we deleted the pod with **unknown** state using **kubectl delete pod <pod_name> -n <namespace> --grace-period=0 --force**, the scheduler again scheduled the pod to the same node, it got deleted and came up with pending state while rolling update was still stuck there trying to update the same pod first, We expected the rolling update to try to update one of the other pods.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The node has a taint :
```
taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: 2019-01-14T17:24:02Z

```
The daemonset had this default toleration:
```
tolerations:
- operator: "Exists"
  effect: "NoSchedule"

```
When we removed this toleration from the daemonset, the scheduler stopped scheduling the pods to that node and then everything worked fine.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.4
- Cloud provider or hardware configuration: Baremetal cluster
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kow3ns** [comment]
you can control the amount of disruption you want to tolerate and the maximum number of bin setting maxUnavailable https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#performing-a-rolling-update. If you don't want the DaemonSet to tolerate a taint you should, as you did, remove the toleration for the taint. This seems to work as intended 
/close
