### ISSUE TITLE
Expose metrics for CSI

### ISSUE THREAD

**Issue by metalmatze** [kubernetes/kubernetes#73019]
**What would you like to be added**:
In previous versions of Kubernetes there have been the `kubelet_volume_*` metrics. 
With the introduction of CSI these metrics are no longer populated and I currently don't see any metrics that can replace these from the CSI side.

**Why is this needed**:
We want to alert on different CSI related metrics similar to `kubelet_volume_stats_capacity_bytes` and `kubelet_volume_stats_available_bytes` just to name a few.

/sig storage
/sig instrumentation
/cc @gnufied @brancz

**Comment by metalmatze** [comment]
If someone from sig storage could let us know how to move forward with this, I would be happy to work on fixing the current situation.

**Comment by gnufied** [comment]
@metalmatze you should start looking into replacing `MetricsNil` interface over here - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L69 with a real one. Obviously, this will require making real CSI RPC call for actually fetching the metrics.

**Comment by humblec** [comment]
> @metalmatze you should start looking into replacing `MetricsNil` interface over here - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L69 with a real one. 
>
For general use case, if we populate the mounter metrics interface for intree CSI driver, it should populate the metrics via existing PV metric controller, Isnt it ?

**Comment by humblec** [comment]
>@metalmatze you should start looking into replacing MetricsNil interface over here - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L69 with a real one. Obviously, this will require making real CSI RPC call for actually fetching the metrics.
>
@gnufied yeah, we have to fill metricsprovider interface to get something useful. however, I wondering  about the need of CSI rpc call here or trying to understand the requirement. That said, I believe, by rpc call you are referring to make use of `NodeGetVolumeStats` service. But, the question I have here is, once the (intree) csi driver issued nodepublish call to third party CSI driver, we actually have the mount in the kubelet for fs type volume mode. So, isnt it good enough to just execute `volume.NewMetricsStatFS` to get the stats ? Please feel free to fill in if I am missing something here :)

**Comment by gnufied** [comment]
@humblec `NewMetricsStatFS` always uses statfs based call for collecting metrics which depending on volume type may not be a good idea. statfs based call works best for block storage file systems and does not work particularly well for shared file systems or volume types where disk space is shared with the host.  

Using CSI RPC call ensures we always get right metrics.

**Comment by anmolsachan** [comment]
Referencing the dependent issues : https://github.com/openshift/console/issues/1258 , https://github.com/rook/rook/issues/1659

**Comment by anmolsachan** [comment]
Referencing related PR : https://github.com/kubernetes/kubernetes/pull/76188

**Comment by msau42** [comment]
This has been addressed by #76188
/close
