### ISSUE TITLE
kubectl explain shows wrong/old apiVersion

### ISSUE THREAD

**Issue by erkules** [kubernetes/kubernetes#73062]
~~~
root@erkan0:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
root@erkan0:~# kubectl explain deploy | head -n 2
KIND:     Deployment
VERSION:  extensions/v1beta1

~~~

**What happened**:

The version shown in `kubectl explain deploy` shows extensions/v1beta1 instead of apps/v1

**What you expected to happen**:

I'm expecting apps/v1

**How to reproduce it (as minimally and precisely as possible)**:

As shown above

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):

~~~
 kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

~~~

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
 cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

Linux erkan0 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm

- Others:

**Comment by YoubingLi** [comment]
It depends on api-version

===  kubectl api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

>>>> kubectl explain deployment --api-version='extensions/v1beta1' | head -n 8
KIND:     Deployment
VERSION:  extensions/v1beta1

DESCRIPTION:
     DEPRECATED - This group version of Deployment is deprecated by
     apps/v1beta2/Deployment. See the release notes for more information.
     Deployment enables declarative updates for Pods and ReplicaSets.

>>>  kubectl explain deployment --api-version='apps/v1' | head -n 8
KIND:     Deployment
VERSION:  apps/v1

DESCRIPTION:
     Deployment enables declarative updates for Pods and ReplicaSets.

FIELDS:
   apiVersion   <string>

If api-version is not specified in command line, it is treated as "extensions/v1beta1"

**Comment by YoubingLi** [comment]
There is typo in the preivous comment

     If api-version is not specified in command line, it is treated as "extensions/v1beta1"
To
    If api-version is not specified in the command line, the command just reutrns the first matching one

There are four versions regarding to Deployment in my cluster such as 

      extensions/v1beta1, Kind=Deployment
      apps/v1, Kind=Deployment
      apps/v1beta2, Kind=Deployment
      apps/v1beta1, Kind=Deployment

where does it mention that "Deployment" uses "apps/v1" as the default version?
If it is not mentioned in any place, it should not be a bug.

**Comment by erkules** [comment]
Wouldn't you expect not to get any apiversion but the newest?

**Comment by YoubingLi** [comment]
@erkules 

This is a general interface for all resources.

The format of api-version is "GROUP/VERSION", and there is not a good approach to compare version between different groups.

For example, "extension" and "apps" for deployment.

**Comment by liggitt** [comment]
kubectl defaults to fetching extensions/v1beta1 when an ambiguous request is made for compatibility reasons

if you want deployments from the apps API group, do `kubectl explain deployment.apps`

/close

**Comment by Rodalli** [comment]
> if you want deployments from the apps API group, do `kubectl explain deployment.apps`
> 
> /close

Just so no one else gets confused by this like I did...

`kubectl explain deployment.apps` will generate an error, because there is no field called 'apps' in the deployment resource.

I honestly don't know what the proper `kubectl explain` command would be to get the description for the apps/v1 deployment resource, or if this distinction is even possible via `kubectl explain`. It would be cool if it was!

**Comment by liggitt** [comment]
> I honestly don't know what the proper kubectl explain command would be to get the description for the apps/v1 deployment resource, or if this distinction is even possible via kubectl explain

kubectl explain takes an `--api-version` flag, so `kubectl explain deployments --api-version=apps/v1`

**Comment by kidlj** [comment]
For ingresses, you can show its yaml with different apiversions like:

```
[lijian@kidlj ~]$ kubectl get ingress echo-demo-v1-legacy-ingress -o yaml | head -2
apiVersion: extensions/v1beta1
kind: Ingress

[lijian@kidlj ~]$ kubectl get ingress.networking echo-demo-v1-legacy-ingress -o yaml | head -2
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
```
