### ISSUE TITLE
kubectl expose --overrides : what field are missing ?

### ISSUE THREAD

**Issue by ErwanMAS** [kubernetes/kubernetes#73077]
Hey Guys ,
I try to use the option *--override* with *kubectl expose* .
First i did this and it work :
```
kubectl run test-nginx-metadata --image=nginx --replicas=2 --port=80 --expose --service-overrides='{ "metadata": { "annotations": { "zone-context": "home" } } } '
```
Now i want to add another *service* with *kubectl expose*
and this command does not work
```
kubectl expose deployment test-nginx-metadata  --port=1000 --target-port=80 --type=NodePort --name=test-nginx-metadata-srv-2 --overrides='{ "apiVersion": "v1" , "kind": "Service" , "metadata": { "annotations": { "zone-context": "work" } } } '
```
I have this error
```
error: no kind "Service" is registered for the internal version of group "" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```
If i remove *--overrides* the command work .

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
````

**Comment by YoubingLi** [comment]
expose tries to convert version from "v1" to "__internal" which is not registered.
This is the reason that the function doesn't works.

== "pkg/kubectl/cmd/expose/expose.go"
316                 if inline := cmdutil.GetFlagString(cmd, "overrides"); len(inline) > 0 {
317                         object, err = cmdutil.Merge(scheme.Codecs.LegacyCodec(scheme.Scheme.PrioritizedVersionsAllGroups()...), object, inline)
318                         if err != nil {
319                                 return err
320                         }
321                 }

=== staging/src/k8s.io/apimachinery/pkg/runtime/serializer/codec_factory.go

156 // LegacyCodec encodes output to a given API versions, and decodes output into the internal form from
157 // any recognized source. The returned codec will always encode output to JSON. If a type is not
158 // found in the list of versions an error will be returned.
159 //
160 // This method is deprecated - clients and servers should negotiate a serializer by mime-type and
161 // invoke CodecForVersions. Callers that need only to read data should use UniversalDecoder().
162 //
163 // TODO: make this call exist only in pkg/api, and initialize it with the set of default versions.
164 //   All other callers will be forced to request a Codec directly.
165 func (f CodecFactory) LegacyCodec(version ...schema.GroupVersion) runtime.Codec {
166         return versioning.NewDefaultingCodecForScheme(f.scheme, f.legacySerializer, f.universal, schema.GroupVersions(version), runtime.**InternalGroupVersioner**)
167 }

**Comment by YoubingLi** [comment]
kubectl help expose

Expose a resource as a new Kubernetes service.

 Possible resources include (case insensitive):

 pod (po), service (svc), replicationcontroller (rc), deployment (deploy), replicaset (rs)

In order to control the scope, I only register them as un-versioned type in the fix.
