### ISSUE TITLE
Fix kms ebs provisioning e2e to not use events

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#73081]
As identified here by @wongma7  - https://github.com/kubernetes/kubernetes/issues/71570#issuecomment-452308387 

We need to fix this e2e so as it does not uses events.

/sig storage

cc @jsafrane @msau42

**Comment by cofyc** [comment]
/close
Closing via https://github.com/kubernetes/kubernetes/pull/73139.
