### ISSUE TITLE
Remove node OS/arch beta labels in kubernetes 1.18

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#73084]
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190130-node-os-arch-labels.md
ref: #72929

The OS/arch labels are going to be promoted to GA in v1.14. Kubelet will continue reporting both the beta and the GA labels until v1.18.
The beta labels below should be removed in v1.18.
```
"beta.kubernetes.io/os"
"beta.kubernetes.io/arch"
```
/cc @kubernetes/sig-node-bugs

**Comment by bgrant0607** [comment]
Please ensure this deprecation is announced with 1.14, in release notes and in the feature documentation

**Comment by vbmade2000** [comment]
@yujuhong Can I work on this ?

**Comment by markyjackson-taulia** [comment]
@yujuhong Is this issue ok to close? All associated work look completed

**Comment by jtslear** [comment]
Hello @yujuhong 
Bug Triage team here for the 1.18 release. Is there anything else required for this issue?  I see that https://github.com/kubernetes/kubernetes/pull/76415 was closed without a merge and suspect we still need to complete some work.  This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18?

cc @dchen1107 and @liggitt as KEP approvers.

**Comment by yosshy** [comment]
We have some codes to be modified:
```
user@k8sdev:~/go/src/k8s.io/kubernetes$ git checkout v1.18.0
Note: checking out 'v1.18.0'.
(snip)
HEAD is now at 9e991415386 Release commit for Kubernetes v1.18.0

user@k8sdev:~/go/src/k8s.io/kubernetes$ grep -r beta.kubernetes.io/os * | grep -v CHANGELOG
cluster/addons/ip-masq-agent/ip-masq-agent.yaml:        beta.kubernetes.io/os: linux
pkg/kubelet/apis/well_known_labels.go:  LabelOS = "beta.kubernetes.io/os"
plugin/pkg/admission/noderestriction/admission_test.go: node.Labels["beta.kubernetes.io/os"] = value
test/e2e/windows/cpu_limits.go:                                 "beta.kubernetes.io/os": "windows",

user@k8sdev:~/go/src/k8s.io/kubernetes$ grep -r beta.kubernetes.io/arch * | grep -v CHANGELOG
pkg/kubelet/apis/well_known_labels.go:  LabelArch = "beta.kubernetes.io/arch"
plugin/pkg/admission/noderestriction/admission_test.go: node.Labels["beta.kubernetes.io/arch"] = value
test/e2e_node/testing-manifests/sriovdp-ds.yaml:        beta.kubernetes.io/arch: amd64
```
