### ISSUE TITLE
Deleting a namespace containing a custom resource with finalizer results in repeated updates to deletionTimestamp

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes/kubernetes#73098]
**What happened**:
1. Create a custom resource defintion
2. Create a namespace
3. Create a custom resource in the namespace with a finalizer attached
4. Delete the namespace
5. The custom resource in the namespace will get its deletionTimestamp field updated about every 8 seconds.

**What you expected to happen**:

The resource would have the deletionTimestamp set once then not be updated again.  This becomes a hassle if a controller needs to perform an operation that takes longer than the update period as it will need to perform a read-modify-write with retry loop when removing the finalizer.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
#!/bin/bash

set -euo pipefail

echo "+++ Creating my-namespace, Custom Resource Definition 'test', and Custom
Resource 'my-test in my-namespace."
kubectl create ns my-namespace
kubectl apply -f - <<EOF
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.test.k8s.io
spec:
  group: test.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: tests
    singular: test
    kind: Test
EOF
kubectl apply -f - <<EOF
apiVersion: test.k8s.io/v1
kind: Test
metadata:
  name: my-test
  namespace: my-namespace
  finalizers:
  - foo
EOF

echo "+++ Setting up watch on my-test, my-namespace"

pids=()
kubectl get -w ns my-namespace -oyaml &
pids+=($!)
kubectl get -w -n my-namespace test my-test -oyaml &
pids+=($!)
cleanup() {
  echo "+++ Attempting to finalize my-test"
  kubectl apply -f - <<EOF
apiVersion: test.k8s.io/v1
kind: Test
metadata:
  name: my-test
  namespace: my-namespace
EOF

  echo "+++ Killing watches"
  kill "${pids[@]}"
}
trap cleanup SIGINT SIGTERM EXIT


echo "+++ Deleting my-namespace, my-test will continue to have deletionTimestamp
updated about every 8 seconds."
kubectl delete ns my-namespace

wait "${pids[@]}"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
GKE 1.11

**Comment by liggitt** [comment]
/area custom-resources

deletionTimestamps should not update even if subsequent deletion requests are made

**Comment by danielqsj** [comment]
@liggitt  as this description: https://github.com/kubernetes/kubernetes/blob/dc3edee5f5f732df7c6b50e073c35bd20912ac6a/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L912

if object has pending finalizers, the deletionTimestamps should be updated.
Do we need to change this logic ?

**Comment by liggitt** [comment]
deletionTimestamp is supposed to be immutable:

https://github.com/kubernetes/kubernetes/blob/dc3edee5f5f732df7c6b50e073c35bd20912ac6a/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L274

storage modifying that timestamp is unexpected, at least to me

**Comment by liggitt** [comment]
we should at least ensure that this documentation is honored:

> // Once the deletionTimestamp is set, this value may not be unset or be set further into the
> // future, although it may be shortened or the resource may be deleted prior to this time.

**Comment by liggitt** [comment]
> we should at least ensure that this documentation is honored

opened https://github.com/kubernetes/kubernetes/pull/73138 to do that
