### ISSUE TITLE
The test "Simple pod should support inline execution and attach" is inherently racy.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#73099]
The test case "executing a command with run and attach without stdin" is inherently racy.

The test runs`kubectl run run-test --image=docker.io/library/busybox:1.29 --restart=OnFailure --attach=true --stdin -- sh -c cat && echo 'stdin closed'`, and expected to see `stdin closed` in the output.

The case when the test passes:
* case 1:
  * Kubernetes creates and starts the container without stdin;
  * The container exits before attach runs;
  * kubectl falls back to get container log, which contains `stdin closed`. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run/run.go#L527
* case 2:
  * Kubernetes creates and starts the container without stdin;
  * kubectl attach before "stdin closed" is printed;
  * kubectl attach contains `stdin closed`.

The case when the test fails:
  * Kubernetes creates and starts the container without stdin;
  * The container prints "stdin closed", but hasn't exited yet;
  * kubectl attach contains nothing.

One example failure: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/7057

Related issue: https://github.com/kubernetes/kubernetes/issues/24070

Can we modify this test not to check the output? Or use `kubectl log` to check output instead?

/cc @kubernetes/sig-node-bugs @kubernetes/sig-cli-bugs

**Comment by selfmanagingresource** [comment]
Uploaded https://github.com/kubernetes/kubernetes/pull/73682 to try to address

**Comment by justinsb** [comment]
/reopen

This test is still inherently racy, even after  #73682

**Comment by justinsb** [comment]
Fix in #79235 (I hope!)

**Comment by justinsb** [comment]
Moving into the current milestone as it was not fixed in 1.14

**Comment by ttousai** [comment]
Hello! I'm a bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. Code freeze is starting on August 29th (about 3 days from now), which means that this PR must merged by then.

Do we still target this issue to be fixed for 1.16?

**Comment by justinsb** [comment]
Thanks @ttousai .  PR is available and awaiting review!

**Comment by xmudrii** [comment]
@justinsb What is the PR in question? Is it targeting 1.16 or 1.17?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/79235

**Comment by aojea** [comment]
@BenTheElder is right, it seems to be present in kind jobs now only

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=Kubectl%20client%20Simple%20pod%20should%20support%20inline%20execution%20and%20attach

**Comment by aojea** [comment]
/assign

let's see if we start to recover a bit of stability :smile: 

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-e2e-kind&test=Kubectl%20client%20Simple%20pod%20should%20support%20inline%20execution%20and%20attach

**Comment by aojea** [comment]
The rate of failures decreased a lot since last changes

Checking the logs of the failures it seems that the problem is that the pod has not finished before checking the output, as Lantao described

> Kubernetes creates and starts the container without stdin;
> The container prints "stdin closed", but hasn't exited yet;
> kubectl attach contains nothing.

The test fails

```
May 15 06:02:03.923: INFO: Running '/home/prow/go/src/k8s.io/kubernetes/bazel-bin/cmd/kubectl/linux_amd64_pure_stripped/kubectl --server=https://127.0.0.1:46599 --kubeconfig=/root/.kube/kind-test-config --namespace=kubectl-1361 run run-test-2 --image=docker.io/library/busybox:1.29 --restart=OnFailure --attach=true --leave-stdin-open=true -- sh -c cat && echo 'stdin closed''
May 15 06:02:13.219: INFO: stderr: "If you don't see a command prompt, try pressing enter.\n"
May 15 06:02:13.219: INFO: stdout: ""
May 15 06:02:13.219: FAIL: Expected
    <string>: 
to contain substring
    <string>: stdin closed
```

Collecting events from namespace 

```
May 15 06:02:16.523: INFO: POD         NODE         PHASE    GRACE  CONDITIONS
May 15 06:02:16.523: INFO: run-test-2  kind-worker  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-15 06:02:04 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-05-15 06:02:12 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-05-15 06:02:12 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-15 06:02:04 +0000 UTC  }]
```

The framework logs the pods the kubelet thinks is on the node

```
May 15 06:02:18.189: INFO: run-test-2 started at 2020-05-15 06:02:04 +0000 UTC (0+1 container statuses recorded)
May 15 06:02:18.189: INFO: 	Container run-test-2 ready: true, restart count 0
```

**Comment by BenTheElder** [comment]
note that it's still racy, but it's hopefully somewhat mitigated.

**Comment by hasheddan** [comment]
@aojea any updates here?

**Comment by aojea** [comment]
> @aojea any updates here?

nope, totally agree with the description, is racy by design, couldn't find any way or trick  to avoid the randomness

**Comment by BenTheElder** [comment]
Specific sub-tests were fixed previously, but this one sub-case:
> Executing a command with run and attach without stdin

That one we can't use the "Wait for stdin input to signal we're attached" hack, so it's just racy.

We could remove that case maybe. I'm not sure who I'd want to weigh in on that, probably someone more active in node / CLI.

**Comment by BenTheElder** [comment]
not super common atm but still happening. discussing
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=%3Cstring%3E%3A%20stdin%20closed&test=Kubectl%20client%20Simple%20pod%20should%20support%20inline%20execution%20and%20attach

**Comment by aojea** [comment]
/unassign
@aledbf has a fix for this https://github.com/kubernetes/kubernetes/pull/93961
