### ISSUE TITLE
Refactor kubectl to decouple command framework from business logic

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#7311]
Too much kubectl business logic resides in pkg/kubectl/cmd. I'd like essentially all of kubectl to be callable as a library, and functionality like run-container and rolling-update should be configurable declaratively, as well. 

Some of the logic (stop #1535, resize #1629, rolling-update #1743) belongs on the server side, too, but that's a separate issue.

An example that's close:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/run.go
No mention of cobra, no flags, no reading files/URLs/etc. 

Additional changes I'd like to run.go include accepting its config as an object and/or json (rather than the simple array), and moved to a more generic client directory/package. For generators specifically, we need some sort of plugin mechanism and/or should just make them into simple services (#5280).

Examples that don't obey this principle:
- updateWithPatch: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/update.go#L122
- RunRollingUpdate: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/rollingupdate.go#L67

Additionally, for declarative updates (#1702), it needs to be possible to specify the update policy in json, accompanying the objects to be updated.

At a glance, pkg/client/clientcmd looks like it respects the separation that we should strive for.

Related: Clients shouldn't be using the internal rep. #3955 #4874 -- only apiserver and kubelet should be using it. Even our controllers should only be using the latest stable API version.

Internally our command-line tool grew more and more functionality, and it became very hard to tease apart. Applications were linking in essentially the whole tool (flags and all) just to use specific bits of it, such as to take a list of objects and send them to the API. 

Of course, these principles should be documented somewhere. (Related, but not identical to #6797)

@smarterclayton @lavalamp @ghodss @jlowdermilk @deads2k @ironcladlou @brendandburns @thockin @erictune

**Comment by ghodss** [comment]
Would one possible approach be to migrate a lot of the logic from kubectl into self-sufficient modules in something like pkg/client/tools?

**Comment by bgrant0607** [comment]
@ghodss That's along the lines of what I was thinking, yes.

**Comment by smarterclayton** [comment]
The commands should take interfaces directly for their type specific behavior (Reaper, etc) when specific code is required per type.  Those interfaces should be provided by the factory to the cobra initializers, but the Run behavior should take generic options.  

An example from Openshift: https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/request_project.go - flag and argument handling is distinct from execution.

**Comment by bgrant0607** [comment]
See also #12143 re. functionality that should move server-side.

**Comment by AdoHe** [comment]
@pwittrock what's the status of this issue now?

**Comment by pwittrock** [comment]
@AdoHe I believe the status of this issue is unassigned, but something I would like to get done.  The end goal of this would be to be able to call kubectl commands from a go program as a library.  Some things that we need to address would be:
- Using flags to directly pass arguments to the commands
- Writing response directly to stdout instead of returning them in a data structure

  Are you interested in picking it up?

**Comment by AdoHe** [comment]
@pwittrock yes, I think this would be a direction of kubectl, would like to make this happen.

**Comment by bryk** [comment]
FYI: Dashboard UI currently uses some kubectl code as subprograms in its backend codebase. Mostly for YAML/JSON processing. It is painful process because we have to hack around flags, structs and files.

**Comment by AdoHe** [comment]
@bryk I guess you mean something like [this](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/replicationcontroller/replicationcontrollerdeploy.go#L306) in dashboard, how would you expect this to be that can  make this process not that painful, what about a kubectl wrapper service sidecar?

**Comment by bryk** [comment]
@AdoHe I'd still prefer calling kubectl Go code as a library directly from Dashboard UI backend. Think about error handling, concurrency, parsing, client request pool initialization, etc. It is just easier and more maintainable when you do this in the code.

**Comment by smarterclayton** [comment]
@jwforres how do you feel about this?  I'm thinking new-app and a few
specific flows.  How might you use this in Openshift console?

**Comment by AdoHe** [comment]
@bryk ok, get it.

**Comment by deads2k** [comment]
> @jwforres how do you feel about this?  I'm thinking new-app and a few
> specific flows.  How might you use this in Openshift console?

I thought this issue was about creating composeable  command objects for clean re-use (our complete, validate, run methods) and https://github.com/kubernetes/kubernetes/issues/12143 was about moving the client-side logic server-side.

**Comment by bgrant0607** [comment]
We are probably also going to want to split generic API functionality from Kubernetes-specific API resource types, as we try to make the API machinery more generic and reusable.

**Comment by ardaguclu** [comment]
I think, we have run a long way to achieve this decoupling and it is time to close this issue. If there is any, we can track the work in a new issue.

/close
