### ISSUE TITLE
How do I modify the rbd_default_order parameter

### ISSUE THREAD

**Issue by wqcheng** [kubernetes/kubernetes#73127]
I use ceph RBD as the storage of k8s, but the default size of the created RBD is 4M. In fact, the rbd_default_order=21 specified in the configuration file of my ceph does not work. I do not seem to have seen relevant instructions. @k8s-merge-robot

**Comment by wqcheng** [comment]
k8s/volumes

**Comment by drakonstein** [comment]
The answer is that you can't modify any settings like that.  As per the command [2] executed for RBD creation, other than the size of the RBD, nothing is customizable.  It also disables any features that KRBD cannot handle even though RBD-NBD is now a supported option that can use the newer features.  I submitted this [1] 7 months ago, but it never received any comments or interest.

[1] https://github.com/kubernetes/kubernetes/issues/66029

[2] https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-master/actions/create-rbd-pv#L147-L148
