### ISSUE TITLE
kubectl auth can-i Error when using --as-group

### ISSUE THREAD

**Issue by ckcd** [kubernetes/kubernetes#73123]
**What happened**:

I gives user: `testname` a `role` and `rolebinding`, and test it using `kubectl auth can-i`, but it failed when use `--as xx --as-group xx`  :

```
$ kubectl auth can-i -n myns get pods --as=testname --as-group=whatever
Error from server (Forbidden): selfsubjectaccessreviews.authorization.k8s.io is forbidden: User "ckauth" cannot create selfsubjectaccessreviews.authorization.k8s.io at the cluster scop
```

and it's fine when only use `--as=xx`
```
$ kubectl auth can-i -n myns get pods --as=testname
yes
```

and it's fine when get pods without `auth can-i`
```
$ kubectl -n myns get pods --as=testname --as-group=whatever
NAME            READY     STATUS    RESTARTS   AGE
pod-1           1/1         Running        0            41d
...
```

and for the problem in the begining, to workaround it, I must create a `clusterrole` and a `clusterrolebinding` of resource `selfsubjectaccessreviews ` for the user or the group.

```
// create a clusterrole with resource: selfsubjectaccessreviews
$ kubectl create clusterrole ...

// create a clusterrolebindind with this clusterrole for the user or group
$ kubectl create clusterrolebinding ...

$ kubectl auth can-i -n myns get pods --as=testname --as-group=whatever
yes
```

**What you expected to happen**:

whatever the group is, the ans should be OK because the `testname` has correct `rolebinding`,

and we should NOT need to create the clusterrolebinding for `selfsubjectaccessreviews` because the k8s has `system:basic-user` clusterrole which gives permission to all users to create `selfsubjectaccessreviews`.

```
$ kubectl get clusterrolebinding system:basic-user -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2018-04-25T07:22:59Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:basic-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:basic-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
```

the test using `get pods` without `auth can-i` also prove my opinion.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.7
- Cloud provider or hardware configuration: no
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): 4.4.0-62-generic
- Install tools:
- Others:

**Comment by liggitt** [comment]
Be sure to include all relevant groups with multiple `--as-group` params. you typically need to include `--as-group=system:authenticated` in order to have permission to run a selfsubjectaccessreview check.

/close

**Comment by chrissound** [comment]
How would I determine all relevant groups @liggitt ?

**Comment by liggitt** [comment]
> How would I determine all relevant groups @liggitt ?

Because group membership is provided by the authenticators configured for your cluster, the mapping from a username to a set of groups is external to kubernetes and dependent on your configured providers.
