### ISSUE TITLE
Ignore empty fields in HashContainer

### ISSUE THREAD

**Issue by yingnanzhang666** [kubernetes/kubernetes#73120]
**What would you like to be added**:
Change the HashContainer, ignore empty fields when compute the hash value of this container.

**Why is this needed**:
When upgrading k8s cluster, if there are new fields in container spec in new k8s version, all the existing container will be restart. For production environment, restarting all the containers will impact data plane, it should be avoid if possible.

**Comment by xichengliudui** [comment]
@yingnanzhang666  What version and system are you using?

**Comment by yingnanzhang666** [comment]
@xichengliudui we have upgraded our clusters to kubernetes 1.12. os is centos 7.
