### ISSUE TITLE
Failing test (timeout): [sig-auth] Metadata Concealment should run a check-metadata-concealment job to completion

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#73133]
**Which jobs are failing**:
- [sig-release-master-upgrade#gce-new-master-upgrade-master-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel)

**Which test(s) are failing**:
- [[sig-auth] Metadata Concealment should run a check-metadata-concealment job to completion 15m9s](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/821#sig-auth-metadata-concealment-should-run-a-check-metadata-concealment-job-to-completion)

**Since when has it been failing**:
At least since 2019-01-08

**Testgrid link**:
- [gubernator](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/821#sig-auth-metadata-concealment-should-run-a-check-metadata-concealment-job-to-completion) 

**Reason for failure**:
Timeout

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/metadata_concealment.go:33
Expected error:
    <*errors.errorString | 0xc4200d96b0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/metadata_concealment.go:62
```

**Comment by dekkagaijin** [comment]
The GCE metadata concealment image was updated in 1.14: https://github.com/kubernetes/kubernetes/pull/71094

The old test image (1.1.1) used in the upgrade test is expected to fail with the new image

**Comment by mourya007** [comment]
How can we reproduce this issue?

**Comment by dekkagaijin** [comment]
You can swap the metadata-proxy image with:

```shell
kubectl set image ds/metadata-proxy-v0.1 metadata-proxy=k8s.gcr.io/metadata-proxy:v0.1.11 --namespace=kube-system
```

GKE will trample any changes to the daemonset, but this should work with any other GCE cluster.

Compatibility:
* `k8s.gcr.io/metadata-proxy:v0.1.11`: `gcr.io/kubernetes-e2e-test-images/metadata-concealment:1.2`
* `k8s.gcr.io/metadata-proxy:v0.1.10`: `gcr.io/kubernetes-e2e-test-images/metadata-concealment:1.1.1`

**Comment by liggitt** [comment]
> You can swap the metadata-proxy image

We don't want to change the cluster configuration inside the tests.

It looks like to fix this, we need to update the release-1.12 (and maybe release-1.13) branches to run the 1.2 metadata-concealment test image if the cluster version is 1.14+

@kubernetes/sig-testing is making forward-looking changes to tests two releases old like this expected?

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/73964 and https://github.com/kubernetes/kubernetes/pull/73965 to make these two e2e tests conditional in the release branches

**Comment by liggitt** [comment]
latest run passed: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/1107

/close
