### ISSUE TITLE
Failing test in master-upgrade: Invalid `ds1` selector

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#73136]
**Which jobs are failing**:
**In [sig-release-master-upgrade](https://testgrid.k8s.io/sig-release-master-upgrade):**
- [gce-new-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master)
- [gce-new-master-upgrade-master-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel)
- [gce-new-master-upgrade-cluster-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel)
- [gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster)
- [gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)
- [gce-new-master-upgrade-cluster-new-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel)

**Which test(s) are failing**:
- `[sig-apps] daemonset-upgrade`
- `[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]`

**Since when has it been failing**:
At least 2019-01-07

**Testgrid link**:
- [[sig-apps] daemonset-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/2112#master-upgrade-sig-apps-daemonset-upgrade)
- [[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/2112#sig-cluster-lifecycle-upgrade-featureupgrade-master-upgrade-should-maintain-a-functioning-cluster-featuremasterupgrade)

**Reason for failure**:
```
unable to create test DaemonSet : DaemonSet.apps "ds1" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"ds-name":"ds1"}: `selector` does not match template `labels`
```

/sig apps
/sig cluster-lifecycle

**Comment by neolit123** [comment]
cc @kubernetes/sig-gcp-bugs
