### ISSUE TITLE
Failing test in master-upgrade: [sig-network] Networking should provide unchanging, static URL paths for kubernetes api services

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#73134]
**Which jobs are failing**:
- [sig-release-master-upgrade#gce-new-master-upgrade-master-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel)

**Which test(s) are failing**:
- [[sig-network] Networking should provide unchanging, static URL paths for kubernetes api services](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/760#sig-network-networking-should-provide-unchanging-static-url-paths-for-kubernetes-api-services)

**Since when has it been failing**:
2019-01-15 (build [760](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/760#sig-network-networking-should-provide-unchanging-static-url-paths-for-kubernetes-api-services))

**Testgrid link**:
- [gubernator, build 760](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/760#sig-network-networking-should-provide-unchanging-static-url-paths-for-kubernetes-api-services)

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:61
Jan 16 07:18:03.008: Failed: the server could not find the requested resource
```

**Anything else we need to know**:
- The commit combination for the test's first failure is [k/k:51dd616cd](https://github.com/kubernetes/kubernetes/commit/51dd616cd) and [k/test-infra:2d1053361](https://github.com/kubernetes/test-infra/commit/2d1053361). However a few builds prior to #760 have passed with the same combination, and the test has been consistently passing before then in general. Has anything changed outside these repos that could affect the test? Config/setup etc?

/sig network

**Comment by liggitt** [comment]
the failing path is "STEP: testing: /swaggerapi"

That URL is for swagger 1.2 schema docs, which were removed in master https://github.com/kubernetes/kubernetes/pull/72924

That test was updated in master in that PR as well. The failure indicates a test from a previous branch is running against master and needs to be updated.

**Comment by liggitt** [comment]
do we know what branch the failing test is running from? release-1.12? release-1.13?

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/73964 and https://github.com/kubernetes/kubernetes/pull/73965 to make these two e2e tests conditional in the release branches

**Comment by liggitt** [comment]
latest run passed: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master-parallel/1107

/close
