### ISSUE TITLE
Adding an already deleted node port to service shows already acquired error

### ISSUE THREAD

**Issue by safrmich** [kubernetes/kubernetes#73140]
This is a copy of https://github.com/kubernetes/kubernetes/issues/32987 which is closed but not resolved as people (including myself) are still facing the issue. I've got this issue with Kubernetes version 1.11.2.

**Comment by neolit123** [comment]
/sig cli
?

**Comment by safrmich** [comment]
Hello neolit123,

Please refer to ticket https://github.com/kubernetes/kubernetes/issues/32987 for the description of the problem. The ticket is closed even though the issue hasn't been resolved and still appears. The latest occurrence is with Kubernetes version 1.11.2.

Thank you,
Michal

**Comment by jinsalex** [comment]
Hi I am also experiencing the same. any update on the issue or any command that can be used to check whether the node is available?

**Comment by michalpiasecki1** [comment]
having same issue

**Comment by chirangaalwis** [comment]
Experiencing the same issue with AWS EKS.

The Kubernetes version is as follows:
`Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by attila123** [comment]
I ran into this problem with Kubernetes v1.11.3 (running on CoreOS (Container Linux)).
This was on a dev machine. I had an existing Service definition (NodePort). I tried to add more sections under "ports:" for this Service definition yaml, then I got the error that I had to name them all (I don't have the exact output). Then I deleted the second section under "ports:", so it only had one protocol+port+targetPort+nodePort section under "ports:" as before.
Then I tried to apply the file again, and got:
```
$ kubectl apply -f fluent-bit-node-port.yaml
The Service "fluent-bit-node-port" is invalid: spec.ports[0].nodePort: Invalid value: 30180: provided port is already allocated
```
Meanwhile I ssh-d to the host and run `netstat -tlnp` but nothing is listening on this port.
I tried to even poweroff this dev machine and start again. No luck. As one can expect, Kubernetes DB got somehow inconsistent, so why would a reboot help.

**Comment by zhtangsh** [comment]
Just came into same issue with v1.11.2. In my case, node port got released after sleep 60 seconds.

**Comment by staticdev** [comment]
I have this issue on the new v1.14.0 =/

**Comment by kiranyedavalli** [comment]
I am facing this issue as well in v1.14.2

**Comment by MarouaniALA** [comment]
having same issue any updates?

**Comment by MarouaniALA** [comment]
I deleted the svc every thing goes alright ;)

**Comment by ruszki** [comment]
I delete a service from a Pod just before `helm upgrade` applies its manifest, which create a new service with the same NodePort. The pod is a Helm hook. In this case, this randomly happens. Strangely, if I check services with `kubectl get services` after deletion but before helm would apply its manifest, it works every time without exception.

**Comment by ruszki** [comment]
I delete a service from a pod via REST API just before `helm upgrade` applies its manifest, which create a new service with the same NodePort. The pod is a Helm hook. In this case, this randomly happens. Strangely, if I check services with `kubectl get services` after deletion but before helm would apply its manifest, it works every time without exception. It also works with about 3 minutes sleep between the deletion and recreation.

**Comment by attlee-wang** [comment]
This issues is not resolved and I've got this issue with Kubernetes version 1.12.4，pleace re-open @fejta.

**Comment by HimanshuPanwar004** [comment]
Waited for long to let kubernetes refresh it but issue still persist.
Alternative:
1) Create a fresh service by delete the service associated by running "kubectl delete svc <service-name>". service name can listed with command "kubectl get services -o wide".
2) Change the port number in your services yaml config file.

**Comment by zoltan-fedor** [comment]
I have the same issue in 1.17.

I have 3 different environments each with 2 services. I needed to recreate the services - which meant dropping them and recreating them immediately. Out of the 6, 5 went fine and 1 started to complain about "provided port is already allocated".

That port was used by that service 2 seconds before, so when I have deleted the service the port should have freed up. I have verified, the service was gone, but the port did not become available. Again, it has worked 5 out of 6 times, but the 6th kept saying the port is used.

In the end I gave up and switched the yaml config to use a different port. Very mysterious.

**Comment by Kvistian** [comment]
In my case I had experimented with a namespace that were tied to a service using a specific port and even though the service weren't running the port was unavailable when I tried running it.
The port became available first when I deleted the namespace.

**Comment by wagfeliz** [comment]
I confirm that its still happening, on AWS EKS 1.21.

**Comment by bspa10** [comment]
Same issue for me on AWS EKS with 1.23

**Comment by DanielMcAssey** [comment]
Hitting this with 1.26

**Comment by aojea** [comment]
have you checked if there are no other service with that nodeport already acquired?

**Comment by DanielMcAssey** [comment]
Yeah 100%, I've checked the services, ive done a dump and I have checked the API server logs, cant see reference to it. Its a multi-master AWS EKS cluster.

If it matters, its a UDP port, spec below
```
spec:
  ports:
    - protocol: UDP
      port: 30301
      targetPort: 30301
      nodePort: 30301
  selector:
    statefulset.kubernetes.io/pod-name: shard-0-app-0
  type: NodePort
  externalTrafficPolicy: Local
```

**Comment by aojea** [comment]
I mean, any other service in the cluster can "steal" that port 30301, it is assigned randomly.

You should check for all the services, not just that one

**Comment by DanielMcAssey** [comment]
Sorry, what I meant was I checked all services across all namespaces (Its not a massive cluster, about ~40 services)

**Comment by aojea** [comment]
do you mean that apiserver keeps thinking that port is already allocated despite there is no service using it?

There is a loop on the apiserver that fixes that, it runs every 1 min IIRC 🤔

**Comment by aojea** [comment]
just do `kubectl describe service --all-namespaces | grep -i nodeport | grep 30301`

**Comment by DanielMcAssey** [comment]
Nothing found :(

**Comment by aojea** [comment]
run the apply to that service with -v7 and paste the output

**Comment by DanielMcAssey** [comment]
Well, ignore me. Its now working, there must have been a service with that port. Thanks for helping me debug!

**Comment by aojea** [comment]
no worries, I remember one similar bugs some years ago, but it was a very rare race condition and it had to happen to fast, one request to delete to one apiserver and the other to create to other one ... but nevertheless, the apiservers will detect it and clean that leakage after a few minutes

**Comment by kornesh** [comment]
Can confirm, just rerunning it after a few minutes works

**Comment by agates4** [comment]
Bit of a faster command to find the suspect:
`kubectl get svc --all-namespaces -o=jsonpath='{range .items[*]}{.metadata.namespace}{"\t"}{.metadata.name}{"\t"}{range.spec.ports[*]}{.nodePort}{"\n"}{end}{"\n"}{end}' | grep "\t30031"`
