### ISSUE TITLE
PV and PVClaim storage restrictions not working as expected

### ISSUE THREAD

**Issue by djcloudy** [kubernetes/kubernetes#73146]
**What happened**:

Pod is exceeding the limits placed in the PV and PVC parameters:

`apiVersion: v1
kind: Service
metadata:
  name: my-redis
  labels:
    run: my-redis
spec:
  type: NodePort
  ports:
  - port: 6379
    protocol: TCP
    name: redis-port
  selector:
    run: my-redis
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-redis-storage
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: server1.xxxxxxxx.com
    path: /export/data/redis
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-redis-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
    persistentvolumeclaims: "1"
    requests.storage: "5Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis
spec:
  selector:
    matchLabels:
      run: my-redis
  replicas: 1
  template:
    metadata:
      labels:
        run: my-redis
    spec:
      containers:
      - name: redis-pv
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: task-pv-redis-storage
          mountPath: /data
      volumes:
      - name: task-pv-redis-storage
        persistentVolumeClaim:
         claimName: task-pv-redis-claim
        #emptyDir: {}`

**What you expected to happen**:

The pod should not be able to write in excess of the defined storage limits

**How to reproduce it (as minimally and precisely as possible)**:

kubectl -f apply redis.yaml

`kubectl get pvc
NAME                  STATUS   VOLUME                  CAPACITY   ACCESS MODES   STORAGECLASS   AGE
task-pv-redis-claim   Bound    task-pv-redis-storage   5Mi        RWO            manual         2m58s`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

4.4.0-131-generic

- Install tools:
- Others:

**Comment by liggitt** [comment]
the limits in the PV are not enforced by kubernetes, those are informational and expected to be enforced by the underlying storage implementation

/close
