### ISSUE TITLE
Cluster IP will lost connection when restart kube-proxy in version 1.12.5

### ISSUE THREAD

**Issue by annProg** [kubernetes/kubernetes#73154]
**What happened**:
After upgrading to kube-proxy `1.12.5`, the ClusterIP will be disconnected when restarting kube-proxy. When a service uses ClusterIP to connect to other services, it will be affected. As shown in the figure, during the kube-proxy restart, the response time is obviously slower.
![image](https://user-images.githubusercontent.com/4145852/51508755-a317fd80-1e31-11e9-9995-febec4cfba0b.png)

When back to kube-proxy `1.11.4`, no this problem. this is the log, attention the time, kube-proxy restart at `10:27:09`, see the picture above, response time at the time is normal.
```
Log file created at: 2019/01/22 10:27:09
Running on machine: k8s-node-pushd
Binary: Built with gc go1.10.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0122 10:27:09.971242   14444 flags.go:27] FLAG: --alsologtostderr="true"
I0122 10:27:09.971512   14444 flags.go:27] FLAG: --bind-address="0.0.0.0"
I0122 10:27:09.971521   14444 flags.go:27] FLAG: --cleanup="false"
I0122 10:27:09.971528   14444 flags.go:27] FLAG: --cleanup-iptables="false"
I0122 10:27:09.971532   14444 flags.go:27] FLAG: --cleanup-ipvs="true"
I0122 10:27:09.971536   14444 flags.go:27] FLAG: --cluster-cidr=""
```

### Another scene
when use kube-proxy `1.12.5` , ClusterIP of `coredns` will also be disconnected, name resolve will failed
![image](https://user-images.githubusercontent.com/4145852/51509117-00f91500-1e33-11e9-8721-68fd275d237d.png)

**What you expected to happen**:
ClusterIP won't lost connection when kube-proxy restart

**How to reproduce it (as minimally and precisely as possible)**:
Use kube-proxy `1.12.5`

**Anything else we need to know?**:
Add flag  `--cleanup-ipvs=false` ,  same result
```
Log file created at: 2019/01/22 11:15:24
Running on machine: k8s-node-pushd
Binary: Built with gc go1.10.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0122 11:15:24.262837   27865 flags.go:33] FLAG: --alsologtostderr="true"
I0122 11:15:24.263066   27865 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0122 11:15:24.263075   27865 flags.go:33] FLAG: --cleanup="false"
I0122 11:15:24.263081   27865 flags.go:33] FLAG: --cleanup-iptables="false"
I0122 11:15:24.263085   27865 flags.go:33] FLAG: --cleanup-ipvs="false"
I0122 11:15:24.263089   27865 flags.go:33] FLAG: --cluster-cidr=""
```

![image](https://user-images.githubusercontent.com/4145852/51510351-b62dcc00-1e37-11e9-803d-8cd915320c9b.png)

**Environment**:
- Kubernetes version (use `kubectl version`):  1.12.5
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):  CentOS 7
- Kernel (e.g. `uname -a`):  3.10
- Install tools:  manual
- Others:

**Comment by annProg** [comment]
@kubernetes/sig-network-bugs
/area ipvs

**Comment by annProg** [comment]
## Test different version

| version | result |
| ---- | ---- |
| 1.11.4 | OK |
| 1.11.5 | Problem |
| 1.12.0 | OK |
| 1.12.1 | OK |
| 1.12.2 | Problem |
| 1.12.5 | Problem |

perhaps it was introduced by graceful termination   
@Lion-Wei @m1093782566 @lbernail

**Comment by lbernail** [comment]
I'll have a look this week (probably not today)
It could be caused by the VS being cleaned up on startup (not likely) or the clusterIP being unbound and rebound

**Comment by annProg** [comment]
Is there any progress on this issue? @lbernail

**Comment by lbernail** [comment]
@annProg I've started looking into this
Just to understand well: you notice an increased latency for new connections to a clusterIP during the restart phase?
Things a fine during the deletion fine ? (and while kube-proxy is not running?)

**Comment by lbernail** [comment]
It seems you mean that for a short while the clusterIP is not even working (given what you mentioned on coredns). Is this correct?

**Comment by annProg** [comment]
> It seems you mean that for a short while the clusterIP is not even working (given what you mentioned on coredns). Is this correct?

Yes, seems ipvs rule will be recreated when restart kube-proxy

**Comment by lbernail** [comment]
I think I have reproduced this (using wrk2 and deleting the kube-proxy process while it's running)

I wonder if it is related to this part of the code that is run at start-up: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/graceful_termination.go#L207-L221

It will delete all RS that have no connections and set the weight of the other to 0, which means we won't be able to establish connections until syncProxyRules runs
I don't know the reason for doing this at initialization. @Lion-Wei / @m1093782566 you probably have more context.

I can still create a build to validate this hypothesis

**Comment by lbernail** [comment]
@annProg : I tested my idea (not deleting RS at start-up) and initial tests looks promising:
- max latency does not change during a restart of the kube-proxy process (in my very simple wrk test)
- VS and RS reconciliation still work fine without the deletion (very limited testing there: I deleted a service and scaled down a deployment backing another while kube-proxy was not running and at restart everything was immediately resynced)

Here is the diff against the `release-1.12` branch: https://github.com/kubernetes/kubernetes/compare/release-1.12...DataDog:lbernail/graceful-restart?expand=1

If you can try on a test cluster, I have a public test image here: `lbernail/hyperkube-amd64:v1.12.7-beta.1`

Again, I don't know the reason for deleting all RS at start-up in the first place, so be careful (and let me know of you notice anything weird).

**Comment by annProg** [comment]
@lbernail I had compiled kube-proxy use the new code in `lbernail/graceful-restart`, and tested with `dig`, 
```
for id in `seq 1 300`;do echo -n "$id: "; dig @169.169.0.2 google.com +short +time=1 +tries=1;done
```

When restart kube-proxy, all DNS queries have succeeded while original kube-proxy will have some failed query.

**Comment by lbernail** [comment]
@annProg this looks really promising
I'm creating a PR. If there is any doubt on the impacts we can discuss there

**Comment by PaulFurtado** [comment]
Turns out the iptable proxier has similar issues (for different reasons): https://github.com/kubernetes/kubernetes/issues/75360
