### ISSUE TITLE
kube-proxy in ipv6-only cluster binding to both ipv4 and ipv6 address

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/kubernetes#73158]
**What happened**:
 I have an ipv6-only cluster, and in that cluster I have a NodePort service. After the NodePort service is added kube-proxy binds to the NodePort on the system, but in doing so it is binding to both ipv4 and ipv6 addresses, which we can see here:

```
root@k8s-test-node1:~# sudo netstat -tanl | grep 31802
tcp6       0      0 :::31802                :::*                    LISTEN     
root@k8s-test-node1:~# ss -anp | grep 31802
tcp    LISTEN     0      128      :::31802                :::*                   users:(("kube-proxy",pid=8924,fd=6))
root@k8s-test-node1:~# nc -4 -lk 31802
nc: Address already in use
```
I then set the `net.ipv6.bindv6only` sysctl to 1, recreated the cluster and the same thing happened. And to clarify when sending packets through on ipv4 (since it is listening) the service doesn't function, presumably because `iptables` (ipv4 version) has no kube-proxy rules

**What you expected to happen**:
I expected the ipv6-only kube-proxy to bind to only ipv6 addresses. With it doing this double bind it causes a few problems (1) iptables is only managed for v4 or v6, not both. (2) this exposes more ports than I'd like -- since this is supposed to be an ipv6 only cluster.

IMO it would be reasonable if either (1) ipv4 binds worked meaning I could send traffic on ipv4 and/or ipv6 and it would forward to the service or (2) ipv6 only bind

**How to reproduce it (as minimally and precisely as possible)**:
Create an ipv6-only cluster with any NodePort service and then attempt to `nc -l` on the same port on the node.

**Anything else we need to know?**:
**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.2
- Cloud provider or hardware configuration: digitalocean
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): `Linux k8s-test-node1 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Others:

**Comment by jacksontj** [comment]
@kubernetes/sig-network-bugs

**Comment by jacksontj** [comment]
I've created a [simple workaround](https://github.com/kubernetes/kubernetes/compare/master...jacksontj:issue_73158?expand=1) which simply changes the `OpenLocalPort` method to be specific about what ip version it binds to. This seems like a reasonable change fix to the problem short of adding dual-stack support. We could add a separate CLI flag to control this behavior, but IMO its previous behavior was misleading as it was binding a socket that it wasn't actually managing traffic for.

**Comment by uablrek** [comment]
Almost duplicate of https://github.com/kubernetes/kubernetes/issues/72098 (ipv6/4 switched)

**Comment by jacksontj** [comment]
@uablrek yes seems like the inverse of my issue. The fix/workaround I have implemented should fix both cases (as it makes the bind specific).

**Comment by cmluciano** [comment]
related: https://github.com/kubernetes/kubernetes/issues/73157

**Comment by cmluciano** [comment]
@jacksontj Can you confirm if this issue is related to the PR suggested in https://github.com/kubernetes/kubernetes/issues/73157#issuecomment-574116053

**Comment by aojea** [comment]
/close
fixed by https://github.com/kubernetes/kubernetes/pull/87699
