### ISSUE TITLE
kube-proxy in ipv6 cluster with ipv4 "external-ip" for a service

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/kubernetes#73157]
**What happened**:
I have an ipv6-only cluster, and in that cluster one of the cloud provider systems created a LoadBalancer with an `EXTERNAL-IP` set to an ipv4 address. When this happened kube-proxy continually fails with errors such as:

```
E0122 06:42:12.851974       1 proxier.go:1335] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.6.0: host/network `<REDACTED_EXTERNAL_IP>' not found
Error occurred at line: 50
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

```

From the error here it seems that kube-proxy is blindly assuming all IPs that it gets for services etc. are ipv6, in this case it is ipv4 which is causing iptables to fail.

**What you expected to happen**:
I expected kube-proxy to not add the errant rule. Long-term once [dual-stack support ](https://github.com/kubernetes/enhancements/issues/563) is added this should be a moot point, but as of today since ipv6 only clusters are "supported" my expectation is that a single incorrect IP in a service shouldn't stop all kube-proxy rules from functioning.

**How to reproduce it (as minimally and precisely as possible)**:
Create an ipv6-only cluster and add a service with an External-IP which is ipv4

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.2
- Cloud provider or hardware configuration: digitalocean
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): `Linux k8s-test-master 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Others:

**Comment by jacksontj** [comment]
@kubernetes/sig-network-bugs

**Comment by jacksontj** [comment]
I've created a [simple workaround](https://github.com/kubernetes/kubernetes/compare/master...jacksontj:issue_73157?expand=1) which simply skips the mismatched IP addresses. This skips the rule and allows kube-proxy to manage the rest of the iptables entries. If this approach is acceptable I'd be more than happy to clean that up and submit a PR.

**Comment by cmluciano** [comment]
> Yes, logging an error and then ignoring the IP is the correct approach for now. I believe we want to enforce the "service IP and endpoint IP must be the same address family" rule for all proxy implementations, not just iptables, so maybe the check (or at least the helper function that performs the check) should go at a higher level

It's strange that this happens since we do have [some logic in the higher-level service.go](https://github.com/kubernetes/kubernetes/blob/059d6057ddb660ff9ba1e93b885ba03fd359213d/pkg/proxy/service.go#L130) function. 

@jacksontj Do you see any log messages in the following format "%s in %s has incorrect IP version" .

I'm still digging through to see how we attempt to filter these from the list.

**Comment by cmluciano** [comment]
> I'm still digging through to see how we attempt to filter these from the list.

I misinterpreted the function as LogandOmit but it's really LogAndEmit, and this simply logs doesn't actually remove them from the list. For clusterIP changes we [actually return nil  ](https://github.com/kubernetes/kubernetes/blob/059d6057ddb660ff9ba1e93b885ba03fd359213d/pkg/proxy/service.go#L262-L269).

**Comment by cmluciano** [comment]
cc @khenidak I think you mentioned that this may be an issue on the cloud-provider side. Can you provide any feedback on if this is something that we should just punt until the forthcoming dualstack GA?

**Comment by jacksontj** [comment]
This should have nothing to do with the cloud providers? The issue here is that in an ipv6 cluster you can still sometimes have some ipv4 addresses for things (e.g. LoadBalancers -- as a very concrete example DigitalOcean doesn't do ipv6 load balancers) and then kube-proxy attempts to use those ipv4 addresses in ip6tables which breaks the entire chain generation. So as it stands today it takes a single ipv4 address to completely break kube-proxy.

I have continued to maintain a workaround (current for 1.15 -> https://github.com/kubernetes/kubernetes/compare/release-1.15...jacksontj:release-1.15_ipv6) which simply filters out any ips that don't match the operating version. I imagine if kube-proxy is smart enough to see that its ipv4 vs ipv6 and use both iptables and ip6tables this issue would clear up -- which presumably would be required for dualstack ipv6 (depending on the kube-proxy plans for it).

**Comment by jacksontj** [comment]
/reopen
/remove-lifecycle rotten

This is still an unresolved issue

**Comment by aojea** [comment]
@jacksontj I've tried to reproduce it locally but I couldn't hit the error, at least with master and 1.17

There are the steps I'm following:

1. Create an [IPv6 cluster with KIND](https://kind.sigs.k8s.io/docs/user/quick-start/#ipv6-clusters)
2. Create a deployment:
`kubectl apply -f https://k8s.io/examples/service/access/hello-application.yaml`
3. Expose it using a load balancer:
`kubectl expose deployment hello-world --type=LoadBalancer`
4. Because KIND doesn't provide a LB we [can simulate it patching the service](https://github.com/kubernetes-sigs/kind/issues/702#issuecomment-573426736)
`kubectl patch service hello-world -p '{"spec": {"type": "LoadBalancer", "externalIPs":["172.31.71.218"]}}'`
5. or using kubectl directly:
`kubectl expose deployment hello-world --name=testipv4 --type=LoadBalancer --external-ip=6.6.6.6`

We can check that the services have external IPv4 addresses:
```
kubectl get service
NAME              TYPE           CLUSTER-IP         EXTERNAL-IP     PORT(S)          AGE
example-service   NodePort       fd00:10:96::3237   <none>          8080:32677/TCP   27m
hello-world       LoadBalancer   fd00:10:96::98a5   172.31.71.218   8080:32284/TCP   20m
kubernetes        ClusterIP      fd00:10:96::1      <none>          443/TCP          37m
testipv4          LoadBalancer   fd00:10:96::4236   6.6.6.6         8080:30164/TCP   6s
```

And that the kube-proxy logs the IP family mismatch but does not error
```
kubectl -n kube-system logs kube-proxy-762s5
I0112 15:10:19.216558       1 server_others.go:78] IPv6 bind address (::), assume IPv6 operation
W0112 15:10:19.470342       1 server_others.go:323] Unknown proxy mode "", assuming iptables proxy
I0112 15:10:19.475838       1 node.go:135] Successfully retrieved node IP: 2001:db8:1::242:ac11:3
I0112 15:10:19.475862       1 server_others.go:145] Using iptables Proxier.
I0112 15:10:19.476082       1 server.go:571] Version: v1.17.0
I0112 15:10:19.476468       1 conntrack.go:52] Setting nf_conntrack_max to 262144
I0112 15:10:19.476571       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0112 15:10:19.476621       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0112 15:10:19.476771       1 config.go:131] Starting endpoints config controller
I0112 15:10:19.476797       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
I0112 15:10:19.476862       1 config.go:313] Starting service config controller
I0112 15:10:19.476889       1 shared_informer.go:197] Waiting for caches to sync for service config
I0112 15:10:19.577074       1 shared_informer.go:204] Caches are synced for endpoints config
I0112 15:10:19.577152       1 shared_informer.go:204] Caches are synced for service config
E0112 15:32:27.438725       1 utils.go:221] 172.31.71.218 in externalIPs has incorrect IP version (service default/hello-world).
E0112 15:40:19.480049       1 utils.go:221] 172.31.71.218 in externalIPs has incorrect IP version (service default/hello-world).
E0112 15:40:19.480075       1 utils.go:221] 172.31.71.218 in externalIPs has incorrect IP version (service default/hello-world).
E0112 15:46:48.019851       1 utils.go:221] 6.6.6.6 in externalIPs has incorrect IP version (service default/testipv4).
```

can you verify if this is happening to you with 1.17?

**Comment by aojea** [comment]
@jacksontj I've sent a PR #87117 to fix the problem and it works for me locally,
will be great if you can confirm it works for you too :smile:

**Comment by jacksontj** [comment]
That patch looks like it should work, here is the one I'm running for comparison -- https://github.com/kubernetes/kubernetes/compare/release-1.15...jacksontj:release-1.15_ipv6

**Comment by uablrek** [comment]
Easier test;

* In any cluster ipv4/ipv6-only or dual-stack
* Use https://github.com/Nordix/assign-lb-ip to set an LB address of the *wrong* family

`assign-lb-ip` does no check of family. At least earlier there were tests for `externalIPs` but *not* for `loadBalancerIP`. My guess was that is was assumed that cloud-providers never does something wrong :smile:
