### ISSUE TITLE
nodeselector docu - behavior mismatch

### ISSUE THREAD

**Issue by nrobert13** [kubernetes/kubernetes#73166]
**What happened**:
using nodeselector in a daemonset 
```
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
```
having the label on the master node, runs fine.
Changing label during runtime to 
`node-role.kubernetes.io/master: ""`
will cause the pod on the respective master to be terminated, although the docu says:
`The “IgnoredDuringExecution” part of the names means that, similar to how nodeSelector works, if labels on a node change at runtime such that the affinity rules on a pod are no longer met, the pod will still continue to run on the node.`
https://v1-12.docs.kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
**What you expected to happen**:
the pod to still continue to run, as specified in the docu
**How to reproduce it (as minimally and precisely as possible)**:
1. make sure label `node-role.kubernetes.io/master: "true"` is on the nodes
2. create daemonset with:
```
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
```
3. change label on one node:
` kubectl label node master01 --overwrite node-role.kubernetes.io/master=`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vmware
- OS (e.g. from /etc/os-release):
`CentOS Linux release 7.4.1708 (Core)`
- Kernel (e.g. `uname -a`): 
`Linux master01 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubespray

- Others:

**Comment by liggitt** [comment]
That documentation describes the behavior of individual pods, but not necessarily of controllers built on top of those pods. DaemonSets use the node selector in their spec to find the nodes on which their pods should run, and actively ensure they have pods running only on those nodes.

**Comment by nrobert13** [comment]
I see, my question was more related to the part why the pod is getting terminated on the node where during runtime the label was changed. Are these special controller behaviors documented somewhere? didn't manage to find this specific one, that daemonsets handle nodeselector differently from pods.

**Comment by liggitt** [comment]
> Are these special controller behaviors documented somewhere? didn't manage to find this specific one, that daemonsets handle nodeselector differently from pods.

it's in the DaemonSet API documentation (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#daemonsetspec-v1-apps):

> template: An object that describes the pod that will be created. The DaemonSet will create exactly one copy of this pod on every node that matches the template's node selector (or on every node if no node selector is specified).

**Comment by nrobert13** [comment]
Thanks, but I still don't see where is it stated that daemonsets respects the nodeselector in a different way than pods do it, that a running pod is getting terminated if the nodeselector doesn't match anymore, unlike in pod description where it states, `The “IgnoredDuringExecution” part of the names means that, similar to how nodeSelector works, if labels on a node change at runtime such that the affinity rules on a pod are no longer met, the pod will still continue to run on the node.`

So in pod definition the pod will not be terminated if the label changes during runtime, but in daemonsets it will be.

**Comment by liggitt** [comment]
DaemonSets maintain pods as nodes are added/removed, or as node labels are updated to make them match/not-match the DaemonSet nodeSelector
