### ISSUE TITLE
kubelet's httpProbe  follow redirects

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#73172]
**What happened**:

httpProbe follows redirect

**What you expected to happen**:

301/302 code makes check successfull as per documentation

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

/sig node

**Comment by iamakulov** [comment]
See also https://github.com/kubernetes/kubernetes/issues/47893

**Comment by gertvdijk** [comment]
@redbaron 
I'm confused with this issue. As it currently states, you're reporting that it's an _issue_ that it does follow redirects, but #47893 reports that it doesn't. Was it a typo or are you seeing something different?

Also you request/expect to have a 301/302 to be successful, but that implies it does not have to follow any redirect and that it should report a successful probe even if following the redirect would have resulted in a failure?

**Comment by iamakulov** [comment]
> Could you provide a link to that?

I’d reply instead of @redbaron here:

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.
> — https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by gertvdijk** [comment]
> > Could you provide a link to that?
> 
> I’d reply instead of @redbaron here:
> 
> > Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.
> > — https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

Yeah, that's what I found too, so his expectation

> 301/302 code makes check successfull as per documentation

is not based on documentation, hence my question where he got that information from.

**Comment by thockin** [comment]
There's some confusion.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ says:

     Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

https://github.com/kubernetes/kubernetes/issues/18233 was a bug about not following redirects, and https://github.com/anfernee/kubernetes/commit/3c6fd0ed470ba6734b9886fd57e61730d9a6c31e added tests for redirects.

`pkg/probe/http/http.go` says `res.StatusCode >= http.StatusOK && res.StatusCode < http.StatusBadRequest` means success.  Note that it looks like we just accept the code, but really the Go HTTP lib appears to follow redirects internally.

When we discussed redirects (https://github.com/kubernetes/kubernetes/issues/18233) we generally agreed that  local redirects seem OK, but non-local was unclear.  This limitation appears never to have been implemented.

So I figure the only way to know for sure is to test it.  I wrote this program:

```
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/good", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("good")
		fmt.Fprintf(w, "GOOD")
	})
	http.HandleFunc("/redirect-to-good", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("redirect-to-good")
		http.Redirect(w, r, "/good", http.StatusFound)
	})
	http.HandleFunc("/redirect-to-bad", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("redirect-to-bad")
		http.Redirect(w, r, "/bad", http.StatusFound)
	})
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

I built it (static) and pushed it as thockin/http-redirect-test - feel free to play along.

```
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: NAME
spec:
  containers:
  - name: test
    image: thockin/http-redirect-test
    readinessProbe:
      httpGet:
        path: PROBE
        port: 8080

$ cat pod.yaml | sed -e 's/NAME/test-good/' -e 's|PROBE|/good|' | k -n http apply -f -
pod/test-good created

$ cat pod.yaml | sed -e 's/NAME/test-redir-good/' -e 's|PROBE|/redirect-to-good|' | k -n http apply -f -
pod/test-redir-good created

$ cat pod.yaml | sed -e 's/NAME/test-redir-bad/' -e 's|PROBE|/redirect-to-bad|' | k -n http apply -f -
pod/test-redir-bad created
```

Now let's see...

```
$ k -n http get pods
NAME              READY     STATUS    RESTARTS   AGE
test-good         1/1       Running   0          106s
test-redir-bad    0/1       Running   0          69s
test-redir-good   1/1       Running   0          90s
```

Let's look for evidence:

```
$ k -n http logs test-good
2019/03/13 16:24:00 good
2019/03/13 16:24:10 good

$ k -n http logs test-redir-good
2019/03/13 16:24:14 redirect-to-good
2019/03/13 16:24:14 good
2019/03/13 16:24:24 redirect-to-good
2019/03/13 16:24:24 good

$ k -n http logs test-redir-bad
2019/03/13 16:24:29 redirect-to-bad
2019/03/13 16:24:39 redirect-to-bad
```

So it *is* following redirects.  Now the question is whether we should
    a) accept 301/302 as success (as per docs) and not redirect at all
    b) fix docs and limit redirects to local only (probably breaking someone)
    c) fix docs and follow redirects wherever they lead (current behavior)

I think a) is silly and c) is of dubious value and possible risk.  I am not sure how to easily do (b) but anything is possible.

**Comment by gertvdijk** [comment]
Cool, great work to work all that out! :+1: 

What's the version of Kubernetes that you've used to test it?

* Option **a** may not be very silly - command line `curl` without `--location` option also returns success without following a redirect. :man_shrugging:  
* Option **b** could be implemented by only allowing a Location response header if they are either relative _or_ absolute _and_ share the very same scheme+domain/ip/port. Is that hard in the current code base? (I haven't checked, not so comfortable in Go.)
* Option **c** does sound like a risk indeed. I don't like my kubelets following possible unintentional external resources. Nor does it seem useful - you only want to probe the actual pod, right? Perhaps breaking the behaviour for some people with option b isn't that bad as it would probably only indicate faulty configurations...

Perhaps add another option... Make it configurable. E.g. introduce a flag in `httpGet`, as sibling to `path` and `port`: `followRedirects` as boolean, and only follow "internal" redirects.

**Comment by thockin** [comment]
I tested against HEAD from a few weeks ago.

I am loathe to make new options, but it may be all we can do.  I am not
sure it belongs in the pod itself, though.  Maybe it is an externally
enforced policy?

**Comment by tallclair** [comment]
> Option b could be implemented by only allowing a Location response header if they are either relative or absolute and share the very same scheme+domain/ip/port. Is that hard in the current code base? (I haven't checked, not so comfortable in Go.) 

I think changing scheme & port should be allowed, as long as the host is unchanged. This is what we do for `ValidatProxyRedirects`: https://github.com/kubernetes/kubernetes/blob/118e33dfcd8bf052f34d9a922145ab5f97e6a354/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L409

**Comment by tallclair** [comment]
After some offline discussions, our proposal is:
1. If the redirect is relative, or to the same hostname (different port is OK), it should be followed.
2. If the redirect is to a different hostname, then it should be treated as a success (the documented behavior). However, we will also generate an event in this case to ease debugging.

**Comment by bradleybluebean** [comment]
@tallclair, I would suggest not following redirects for a couple reasons:

- Accepting 301/302 as success and stopping there can provide a lightweight way to test the liveness of 3rd party software where you can't control the endpoints available

- From what I can tell, with redirects enabled, the probe does not ultimately succeed until it gets a non-redirected success status. This means each request counts toward the timeoutSeconds. With just one redirect and a default timeoutSeconds of 1, if a pod is under load and each request, though successful, takes 501 milliseconds to return, the probe with fail and kubernetes will end up killing the pod. To me, and I imagine others, this behaviour is non-obvious since any single, non-redirected request is well below the 1 second threshold.

**Comment by thockin** [comment]
In general I would argue that redirecting from a health probe is a bad
idea.  I sort of wish we never supported it at all.  For the 0.001% of
people who legit need it, I think this compromise is plausible.

**Comment by redbaron** [comment]
If redirects are always local (which is good), what following them gives
us? Whatever redirect destination is it can be set in a probe directly.

**Comment by jacksontj** [comment]
@thockin any thoughts on adding an option to allow the caller to enable/disable redirect following? Just ran into this and it is a bit odd to me that it follows redirects by default (definitely seems to break the principle of least surprise)
