### ISSUE TITLE
externalTrafficPolicy: Local makes Azure LoadBalancer stop working 

### ISSUE THREAD

**Issue by huydinhle** [kubernetes/kubernetes#73188]
**What happened**:
- Change one of LoadBalancer Service in Azure from externalTrafficPolicy: Cluster to externalTrafficPolicy: Local make any request that sends to this Loadbalancer to be timeout completely 
- Switch it back to Cluster will have the loadbalancer working fine and receive traffic again

**What you expected to happen**:
LoadBalancer should still receive traffic just fine

**How to reproduce it (as minimally and precisely as possible)**:
1) Spin up a Kubernetes cluster with Azure to be the cloud provider
2) Create a Kubernetes service with type Loadbalancer
3) configure `externalTrafficPolicy` to be Local
4) try to use curl to send request to this loadbalancer
5) Receive timeout 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.7
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-1025-azure
- Install tools: acs-engine 
- Others:

**Comment by Sennahoi** [comment]
I just had the same problem. I installed two nginx-ingress controllers with that policy and found out that the load balancer forwards traffic to the same ports, i.e.

IP1:80 -> 80 
IP1:442 -> 443
AND
IP2:80 -> 80 
IP2: 443 -> 443

In my opinion, this doesn't make sense. Two services can't use the same node port. So, my guess is:

For each external port, only one service can use this policy.

**Comment by feiskyer** [comment]
I believe the issue has already been fixed.  @huydinhle @Sennahoi Please open a new issue if you still have the issues.

/close
