### ISSUE TITLE
failed to create kubelet: unknown service runtime.v1alpha2.RuntimeService

### ISSUE THREAD

**Issue by ping035627** [kubernetes/kubernetes#73189]
I0123 09:17:30.849536   18641 flags.go:33] FLAG: --container-runtime="remote"
I0123 09:17:30.849540   18641 flags.go:33] FLAG: --container-runtime-endpoint="unix:///var/run/docker/containerd/docker-containerd.sock"

E0123 09:17:30.895631   18641 remote_runtime.go:72] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
E0123 09:17:30.895892   18641 kuberuntime_manager.go:184] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
F0123 09:17:30.895924   18641 server.go:261] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

**Comment by changyaowei** [comment]
@ping035627  Kubernetes version and containerd version need provided

**Comment by ping035627** [comment]
k8s1.13.0 and containerd in docker18.06.

**Comment by changyaowei** [comment]
> k8s1.13.0 and containerd in docker18.06.

docker 18.06 ? Do you mean docker or containerd ?

**Comment by changyaowei** [comment]
I found the latest moby  version is 17.05*,  and  can we use moby's containerd  as runtime  ?

**Comment by ping035627** [comment]
But I'm just testing whether docker's containerd can be used as runtime for k8s.

**Comment by zouyee** [comment]
https://github.com/containerd/cri

**Comment by webwurst** [comment]
I am seeing this error with these components when running `crictl ps` or `kubelet`:

| component | --version |
| ------------- | ------------- |
| containerd | containerd github.com/containerd/containerd v1.2.5 bb71b10fd8f58240ca47fbb579b9d1028eea7c84 |
| crictl | crictl version v1.13.0 |
| kubelet | Kubernetes v1.13.4 |

At the moment I feel a bit lost about which versions should be compatible. But I'll keep digging.

**Comment by dims** [comment]
Run `mkdir -p /etc/containerd && containerd config default > /etc/containerd/config.toml` and then restart `containerd` ( fyi, i just made this change in kind - https://github.com/kubernetes-sigs/kind/pull/425/files )

Then you can run the `crictl` like so:
https://github.com/kubernetes-sigs/kind/pull/425#issuecomment-479168589

**Comment by vteratipally** [comment]
came across the same error with 1.5.0 containerd and docker version 20.3
`failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
`

**Comment by zouyee** [comment]
https://github.com/kubernetes/kubernetes/issues/73189#issuecomment-479278959
