### ISSUE TITLE
Kubernetes can's convert LinuxMemory.swap value from a unint64 into a int64 according to ociSpec

### ISSUE THREAD

**Issue by zhiminghufighting** [kubernetes/kubernetes#73200]
**What happened**:

There is an stable error when k8s master to create pod in k8s node from customers now. Could you please see the logs and check if there are some methods to debug kata when there is some errors?
And please see my comments included in the logs:
===============================================================================Env config====================================================================================================================
	OS	K8s 	Docker 	Kata 	With the same yaml and image	Based on	Result based on Kata container	Result based on Runc
K8s master	Centos 3.10.0.862	Kubectl 1.5	1.13.1	1.3&1.4.2$1.5.0.rc	Centos/nginx	ESXi  VM	Failed as below	Success 
K8s slave	Centos 3.10.0.862	Kubelet 1.5.2	1.13.1	1.3&1.4.2$1.5.0.rc	Centos/nginx	ESXi  VM/ a real machine	Failed as below	Success

===============================================================================log start=====================================================================================================================
Jan 16 11:58:46 localhost.localdomain dockerd[28191]: time="2019-01-16T11:58:46.943257758-05:00" level=debug msg="{Action=start, ID=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c, LoginUID=4294967295, PID=1297, Config={Hostname=nginx-rc-2s3fd, User=1001, AttachStdin=false, AttachStdout=false, AttachStderr=false, Tty=false, OpenStdin=false, StdinOnce=false, Env=[KUBERNETES_PORT=tcp://10.254.0.1:443 KUBERNETES_PORT_443_TCP=tcp://10.254.0.1:443 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_PORT_443_TCP_ADDR=10.254.0.1 KUBERNETES_SERVICE_HOST=10.254.0.1 KUBERNETES_SERVICE_PORT=443 KUBERNETES_SERVICE_PORT_HTTPS=443 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=oci], ArgsEscaped=true, Image=10.239.160.130:5000/pod-infrastructure, Entrypoint=[/pod], NetworkDisabled=false, Labels=map[distribution-scope:public io.k8s.display-name:OpenShift Container Platform Pod Infrastructure version:v3.5.5.26 io.openshift.tags:openshift,pod summary:Provides the latest release of Red Hat Enterprise Linux 7 in a fully featured and supported base image. vendor:Red Hat, Inc. io.kubernetes.pod.name:nginx-rc-2s3fd io.kubernetes.pod.uid:bd4265d8-1967-11e9-a8be-005056a6632d architecture:x86_64 io.kubernetes.container.name:POD io.kubernetes.container.ports:[{\"containerPort\":80,\"protocol\":\"TCP\"}] io.kubernetes.container.restartCount:0 io.kubernetes.container.terminationMessagePath: release:2 vcs-ref:2c2469f84a76b8ee1bf88f00018cbe754422c56d vcs-type:git io.kubernetes.container.hash:72cfffe1 io.kubernetes.pod.namespace:default description:The Red Hat Enterprise Linux Base image is designed to be a fully supported foundation for your containerized applications.  This base image provides your operations and application teams with the packages, language runtimes and tools necessary to run, maintain, and troubleshoot all of your applications. This image is maintained by Red Hat and updated regularly. It is designed and engineered to be the base layer for all of your containerized applications, middleware and utilites. When used as the source for all of your containers, only one copy will ever be downloaded and cached in your production environment. Use this image just like you would a regular Red Hat Enterprise Linux distribution. Tools like yum, gzip, and bash are provided by default. For further information on how this image was built look at the /root/anacanda-ks.cfg file. com.redhat.component:openshift-enterprise-pod-docker name:openshift3/ose-pod authoritative-source-url:registry.access.redhat.com io.kubernetes.pod.terminationGracePeriod:30 build-date:2017-06-14T20:09:23.618982 com.redhat.build-host:rcm-img-docker02.build.eng.bos.redhat.com io.k8s.description:This is a component of OpenShift Container Platform and holds on to the shared Linux namespaces within a Pod.]}, HostConfig={LogConfig={Type:json-file Config:map[]}, NetworkMode=default, PortBindings=map[], AutoRemove=false, DNS=[10.248.2.5 10.239.2
7.228 172.17.6.9], DNSSearch=[sh.intel.com], OomScoreAdj=-998, Privileged=false, PublishAllPorts=false, ReadonlyRootfs=false, SecurityOpt=[seccomp=unconfined], ShmSize=67108864, Runtime=ka
ta-runtime, Resources={CPUShares:2 Memory:0 NanoCPUs:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CPURealtimePeriod:0 CPURealtimeRuntime:0 CpusetCpus: CpusetMems: Devices:[] DiskQuota:0 KernelMemory:0 MemoryReservation:0 MemorySwap:-1 MemorySwappiness:0xc420e8f690 OomKillDisable:0xc420e8f698 PidsLimit:0 Ulimits:[] CPUCount:0 CPUPercent:0 IOMaximumIOps:0 IOMaximumBandwidth:0}}}"
Jan 16 11:58:47 localhost.localdomain kata-runtime[11593]: time="2019-01-16T11:58:47.129116417-05:00" level=info msg="loaded configuration" arch=amd64 command=create file=/usr/share/defaul
ts/kata-containers/configuration.toml format=TOML name=kata-runtime pid=11593 source=runtime
Jan 16 11:58:47 localhost.localdomain kata-runtime[11593]: time="2019-01-16T11:58:47.129339636-05:00" level=info arch=amd64 arguments="\"create --bundle /var/run/docker/libcontainerd/c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c --console  --pid-file /run/docker/libcontainerd/containerd/c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c/init
/pid c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c\"" command=create commit=258eae0 name=kata-runtime pid=11593 source=runtime version=1.3.1
Jan 16 11:58:47 localhost.localdomain kata-runtime[11593]: time="2019-01-16T11:58:47.129468271-05:00" level=debug msg="converting /run/docker/libcontainerd/c3ccb74e61d7ca6704e702705ce56953
2ea97445154d2f04c7feff263ddb797c/config.json" arch=amd64 command=create container=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c name=kata-runtime pid=11593 source=virtcontainers subsystem=oci
Jan 16 11:58:47 localhost.localdomain kata-runtime[11593]: time="2019-01-16T11:58:47.130047942-05:00" level=error msg="json: cannot unmarshal number 18446744073709551615 into Go struct fie  
ld LinuxMemory.swap of type int64" arch=amd64 command=create container=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c name=kata-runtime pid=11593 source=runtime
Jan 16 11:58:47 localhost.localdomain kata-runtime[11600]: time="2019-01-16T11:58:47.134145136-05:00" level=info msg="loaded configuration" arch=amd64 command=delete file=/usr/share/defaul
ts/kata-containers/configuration.toml format=TOML name=kata-runtime pid=11600 source=runtime
Jan 16 11:58:47 localhost.localdomain kata-runtime[11600]: time="2019-01-16T11:58:47.134267994-05:00" level=info arch=amd64 arguments="\"delete c3ccb74e61d7ca6704e702705ce569532ea97445154d
2f04c7feff263ddb797c\"" command=delete commit=258eae0 name=kata-runtime pid=11600 source=runtime version=1.3.1
Jan 16 11:58:47 localhost.localdomain kata-runtime[11600]: time="2019-01-16T11:58:47.134337653-05:00" level=error msg="Container ID (c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff2
63ddb797c) does not exist" arch=amd64 command=delete container=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c name=kata-runtime pid=11600 source=runtime
Jan 16 11:58:47 localhost.localdomain kata-runtime[11608]: time="2019-01-16T11:58:47.156750155-05:00" level=info msg="loaded configuration" arch=amd64 command=delete file=/usr/share/defaul
ts/kata-containers/configuration.toml format=TOML name=kata-runtime pid=11608 source=runtime
Jan 16 11:58:47 localhost.localdomain kata-runtime[11608]: time="2019-01-16T11:58:47.156882974-05:00" level=info arch=amd64 arguments="\"delete c3ccb74e61d7ca6704e702705ce569532ea97445154d
2f04c7feff263ddb797c\"" command=delete commit=258eae0 name=kata-runtime pid=11608 source=runtime version=1.3.1
Jan 16 11:58:47 localhost.localdomain kata-runtime[11608]: time="2019-01-16T11:58:47.156935604-05:00" level=error msg="Container ID (c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff2
63ddb797c) does not exist" arch=amd64 command=delete container=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c name=kata-runtime pid=11608 source=runtime

=======================================================================log end====================================================================================

**What you expected to happen**:
Kat container can be launched correctly by kubernetes when i run "kubectl create -f nginx.yaml" in master node

**How to reproduce it (as minimally and precisely as possible)**:
See the environment: 
	OS	K8s 	Docker 	Kata 	With the same yaml and image	Based on	Result based on Kata container	Result based on Runc
K8s master	Centos 3.10.0.862	Kubectl 1.5	1.13.1	1.3&1.4.2$1.5.0.rc	Centos/nginx	ESXi  VM	Failed as below	Success 
K8s slave	Centos 3.10.0.862	Kubelet 1.5.2	1.13.1	1.3&1.4.2$1.5.0.rc	Centos/nginx	ESXi  VM/ a real machine	Failed as below	Success

cmd :
in master nodes:
install docker 1.13.1 + kubelet-master 1.5.0 + etcd  
kubectl create -f nginx.yaml
in slave nodes:
install docker 1.13.1 + kubelet-slave 1.5.2 + kata container 1.3/or 1.4/ or 1.5.2

**Anything else we need to know?**:

please notify this error log:

Jan 16 11:58:47 localhost.localdomain kata-runtime[11593]: time="2019-01-16T11:58:47.130047942-05:00" level=error msg="json: cannot unmarshal number 18446744073709551615 into Go struct fie  
ld LinuxMemory.swap of type int64" arch=amd64 command=create container=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c name=kata-runtime pid=11593 source=runtime

i didn't configure any memory related info in yaml.
k8s should use the default value '-1' to configure LinuxMemory.swap and convert it as an uint64 18446744073709551615. 
Actually, you can check ocispec related with LinuxMemory.swap is an int64. 
So the value exceed the range of int64 and kata container will raise this error when kata container unmarshal this the config.json file. It is a right action for kata. But it is an error action for k8s to convert a "-1" into uint64 and write it into container config.json.
https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#memory 
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@zhiminghufighting this is possibly interaction between containerd and katacontainers runtime. Please raise it with kata folks - https://github.com/kata-containers/runtime

/close

**Comment by zhiminghufighting** [comment]
@dims, i am responsible for kata PRC local support and i use docker to launch kata container and it works.

**Comment by zhiminghufighting** [comment]
@dims  kata container raise the error when it unmarshal the config.json and  when it is launched by kubectl from master node. It is a right action for kata to check the value range for int64 type LinuxMemory.swap, when the value 18446744073709551615 exceed the range of int64 and kata raise the error.
             kata container will works well when it is launched by docker-containerd.
             if the error is caused by conatinerd and kata runtime, it will always raise the error whatever it is launched by k8s or docker.

Thanks for your quick response and please recheck this issue again.

**Comment by zhiminghufighting** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by grahamwhaley** [comment]
To add some more info - I believe @jodh-intel also re-created using `runc`, so we don't believe this is a kata specific issue (just the kata-runtime picked it up first in our testing).

**Comment by dims** [comment]
@zhiminghufighting @grahamwhaley where exactly in kubernetes do we create this `config.json`? what does the json contain? (can you paste a full example?) since i have not been able to figure out what exactly you are mentioning.

**Comment by zhiminghufighting** [comment]
@dims you can see the swap value is 18446744073709551615, actually it is an int64 value in ocispec.
kata will check the config.json according to ocispec and raise the error when it found the range of 
memory sway value is exceed int64 range.


here:
"memory":{"swap":18446744073709551615,"swappiness":18446744073709551615},


kata runtime report the error:
Jan 16 11:58:47 localhost.localdomain kata-runtime[11593]: time="2019-01-16T11:58:47.130047942-05:00" level=error msg="json: cannot unmarshal number 18446744073709551615 into Go struct fie
ld LinuxMemory.swap of type int64" arch=amd64 command=create container=c3ccb74e61d7ca6704e702705ce569532ea97445154d2f04c7feff263ddb797c name=kata-runtime pid=11593 source=runtime

@jodh-intel @grahamwhaley  thanks for your inputs and perspective for this issue.
The default value of this swap may be "-1" even user don't specify the value in yaml file. K8s uses the default value "-1" assign to swap and don't convert it from an uint64 to int 64.

**Comment by zhiminghufighting** [comment]
@dims thanks for your direction and hints. i will track the value assignment of swap to "-1" and the procedure to generate the config.json.
