### ISSUE TITLE
Support configurable ProjectedVolumeToken rotation period on kubelet

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#73221]
**What would you like to be added**:

A kubelet configuration parameter for modifying the rotation period on ProjectedVolumeTokens. 

**Why is this needed**:

The current default is hardcoded to begin rotation attempts [after 80% of the token's lifetime or 24 hours](https://github.com/kubernetes/kubernetes/blob/v1.14.0-alpha.1/pkg/kubelet/token/token_manager.go#L141-L160), whichever is occurs first. This is a safe default for a 24 hour period, but shorter periods might necessitate more frequent rotation. The API server requires a [minimum token lifetime of 10 minutes](https://github.com/kubernetes/kubernetes/blob/v1.14.0-alpha.1/pkg/apis/authentication/validation/validation.go#L29-L41), so perhaps kubelet could accept a range of 20% to 80% of the token's lifetime. The 20/80 numbers are arbitrary, but it would be nice to allow this to be configurable

/sig auth
/sig node
/kind enhancement

See kubernetes/enhancements#542

**Comment by mourya007** [comment]
@liggitt @mikedanese @micahhausler I would like to work on this issue or some help in this issue.

**Comment by mikedanese** [comment]
What would be a more suitable % for shorter TTLs?

**Comment by mikedanese** [comment]
I'm not sure what that means in this context. Can you give some detail? The current heuristic was a first pass. I'd like to understand the scenarios in which it breaks down. Per [5 and 6](https://github.com/kubernetes/community/blob/master/contributors/devel/component-config-conventions.md#part-1-dont-make-it-configuration), I'm wondering if we can improve the heuristic before punting to configuration.
