### ISSUE TITLE
Azure Load Balancer public IP lookup by name

### ISSUE THREAD

**Issue by doubleyewdee** [kubernetes/kubernetes#73235]
**What would you like to be added**:
Add an annotation to allow lookup of loadBalancerIP by specifying a named Azure resource instead of an explicit IP address. This can pair with the existing 'azure-load-balancer-resource-group' annotation (perhaps call it 'azure-load-balancer-public-ip-resource' or similar).

**Why is this needed**:
During provisioning of k8s clusters on Azure we request IP addresses with specific tags from an Azure IP allocation service. As a result we do not know at cluster setup time what address we will receive, but we do know what the name of the resource is as we control this. While possible to look up the IP during YAML generation it feels more appropriate to extend this functionality within k8s itself.

In https://github.com/kubernetes/kubernetes/blob/b6c8ef298ebfceb66422c416f55ab6076b7ff65d/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L213 it appears an attempt is made to do a reverse lookup from IP address to resource anyway so this would just save time/effort.

@kubernetes/sig-azure-feature-requests

**Comment by doubleyewdee** [comment]
adding @kubernetes/sig-azure

**Comment by doubleyewdee** [comment]
Yes, today we actually do go and look up the IP address after we get one. That said, we already know group+resource name from our Azure deployment specification and it seems counterintuitive to provide resource group name and IP address and then have the k8s code go do a reverse lookup from IP to the LB it applies to.

**Comment by feiskyer** [comment]
The IP is part of service spec, so it's required to make the full service spec work. To support specifying public IP name, a new annotation may be added in service spec.

I wonder what's the use cases of this?

@khenidak What do you think about this?

**Comment by paulgmiller** [comment]
I don't think external ip addesress a required field (if it's omitted then a new public ip is created). The annotation would be a way to use name rather than address. This would us not have to dynamically populate the external ip address just prior to deploy.

**Comment by doubleyewdee** [comment]
Use case is for folks who know what they've called their public IP resource but don't know what IP is assigned. It's a low-pri item. Will bump this and see if I can get to making a patch for a new annotation. If it goes stale again I will close and admit defeat. :)

**Comment by feiskyer** [comment]
@doubleyewdee thanks, feel free to open a PR for it.

**Comment by feiskyer** [comment]
@nilo19 would work on this feature

/assign @nilo19

**Comment by paulgmiller** [comment]
Need any help?
