### ISSUE TITLE
Unprivileged device plugins fails to start grpc server

### ISSUE THREAD

**Issue by vikaschoudhary16** [kubernetes/kubernetes#73240]
**What happened**:
If the device plugin is an unprivileged container and selinux is enabled, it fails to start grpc server.

```
Jan 23 15:31:28 localhost journal[23606]: pluginSocksDir:  /var/lib/kubelet/device-plugins 
Jan 23 15:31:28 localhost audit[9297]: AVC avc:  denied  { write } for  pid=9297 comm="sampledeviceplu" name="device-plugins" dev="dm-2" ino=4990510 scontext=system_u:system_r:container_t:s0:c18,c144 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0 
Jan 23 15:31:28 localhost journal[23606]: Start error:  listen unix /var/lib/kubelet/device-plugins/dp.1548237688: bind: permission denied
```

**What you expected to happen**:
Unprivileged device plugins also able to work

**How to reproduce it (as minimally and precisely as possible)**:
0. Enable selinux
1. Deploy a k8s cluster
2. Deploy a device plugin daemonset without `privileged: true` and plugin sock dir as "/var/lib/kubelet/device-plugins/"

Plugin will not be able to register

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vikaschoudhary16** [comment]
/remove-lifecycle stale
This issue is not fixed yet

**Comment by paulhodson** [comment]
Device plugins in general are too dependent on `privileged: true` in my opinion. I encountered the same problem, and have addressed it for now by creating a `pluginusers` group on the node and all relevant containers and having a `node-prep` container which does:
```
chmod g+w /var/lib/kubelet/device-plugins/ /var/lib/kubelet/device-plugins/kubelet.sock
chgrp pluginusers /var/lib/kubelet/device-plugins/ /var/lib/kubelet/device-plugins/kubelet.sock
```
It goes without saying that the `device-plugins` folder is mapped from node to container.

I am hopeful that the security model will be tightened up.

**Comment by vikaschoudhary16** [comment]
@paulhodson was not https://github.com/kubernetes/kubernetes/pull/73241 helpful?

**Comment by paulhodson** [comment]
@vikaschoudhary16 I hadn't come across that, thank you. I'll check it out

**Comment by paulhodson** [comment]
@vikaschoudhary16 Looks like everything was fine in SELinux land. My issue was that I don't run containers with `root` if I don't have to. `kubelet.sock` permissions are `root:root` by default.
