### ISSUE TITLE
Confusing "Please use 'external' cloud provider for openstack" warning when already using external

### ISSUE THREAD

**Issue by mogaika** [kubernetes/kubernetes#73245]
/kind bug

What happened:
Log says:
W0119 22:23:10.778211 10831 plugins.go:118] WARNING: openstack built-in cloud provider is now deprecated. Please use 'external' cloud provider for openstack: https://github.com/kubernetes/cloud-provider-openstack
what can make administrators confused and think that cloud provider is misconfigured

Anything else we need to know?:
cmd that we are using:
/usr/bin/openstack-cloud-controller-manager --cloud-provider=openstack --cloud-config /etc/kubernetes/cloud-config --cluster-name=kubernetes --kubeconfig /etc/kubernetes/controller-manager.kubeconfig --leader-elect=true --v=4

Originally this issue was created in cloud-provider-openstack repo (https://github.com/kubernetes/cloud-provider-openstack/issues/445), but I recreated it here because it must be fixed in kubernetes repo and affects all cloud providers

**Comment by hello2mao** [comment]
hi @mogaika by setting **--cloud-provider=openstack**, you are use in-tree cloudprovider and this is deprecated.

If you want to use external cloudprovider, you should set **--cloud-provider=external** and start [openstack ccm](https://github.com/kubernetes/cloud-provider-openstack).

More info: https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider

**Comment by mogaika** [comment]
> hi @mogaika by setting **--cloud-provider=openstack**, you are use in-tree cloudprovider and this is deprecated.
@hello2mao as you can see --cloud-provider=openstack provided to openstack-cloud-controller-manager binary. Our kubernetes uses external cloud-provider-openstack for sure because we use features that not available in in-tree cloud provider.
Please check original issue https://github.com/kubernetes/cloud-provider-openstack/issues/445

**Comment by ramineni** [comment]
@mogaika is right, this happens on using external provider also.  ExternalCMServer calls InitCloudProvider here  https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/controllermanager.go#L113 , but there is no way to check if it is called from external or internal provider here https://github.com/kubernetes/cloud-provider/blob/master/plugins.go#L98 which is causing the issue. we can't use cloud provider 'external' when calling from external provider as then we wont be able to get the cloud provider object in that case ( https://github.com/kubernetes/cloud-provider/blob/master/plugins.go#L133 will not be called) . we should be able to distinguish if it is called from external / internal provider, that should fix the issue.
