### ISSUE TITLE
When a pod resource limits are specified, but resource requests are not, why do we set default requests to limits

### ISSUE THREAD

**Issue by hanxiaoshuai** [kubernetes/kubernetes#73242]
When a pod resource limits are specified, but resource requests are not, why do we set default requests to limits

https://github.com/kubernetes/kubernetes/blob/b9631a881f327b58ff52654cbb448927226bf05a/pkg/apis/core/v1/defaults.go#L132-L148

**Comment by henrywangx** [comment]
@hanxiaoshuai Hi，xiaoshuai.
We also feel confused about this. Because we think the default requests should be 0.
