### ISSUE TITLE
Taint-to-string method generates string that taint parser considers invalid 

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes/kubernetes#73249]
**What happened**: The [`ToString` receiver on the `v1.Taint` type generates the string](https://github.com/kubernetes/kubernetes/blob/33b20f2/pkg/apis/core/taint.go#L33) "key:effect" when the `Value` of the taint is the empty string.

Because the generated string has no `=` character, when it is passed to the `parseTaint` method in `pkg/util/taints`, the method returns an error.

I discovered this issue by defining a taint in a kubeadm configuration file. kubeadm converted the taint to a string, then passed the string to kubelet using the `--register-with-taints` flag, and kubelet threw an error.

**What you expected to happen**:
I expect the `ToString` receiver on the `v1.Taint` type to only generate strings that are accepted by the `parseTaint` method in `pkg/util/taints`. Conversely, I expect the `parseTaint` method to accept any string generated by the `ToString` receiver on the `v1.Taint` type.

**How to reproduce it (as minimally and precisely as possible)**:
The following program demonstrates the issue. I compiled it using the `release-1.13` branch. It initializes a `Taint` struct with the `Value` field left as an empty string. It then converts the struct to a string. Finally, it calls `utils.NewTaintsVar`, just as kubelet does [here](https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubelet/app/options/options.go#L406). Subsequently, [a call to `Set` ](https://github.com/kubernetes/kubernetes/blob/5fdad5c/pkg/util/taints/taints.go#L85) returns an error that originates in the `parseTaint` method.
```
package main

import (
	"fmt"

	"k8s.io/api/core/v1"
	"k8s.io/kubernetes/pkg/apis/core"
	utiltaints "k8s.io/kubernetes/pkg/util/taints"
)

func main() {
	t := v1.Taint{
		Key:    "node-role.kubernetes.io/master",
		Effect: v1.TaintEffectNoSchedule,
	}
	s := t.ToString()
	ptr := []core.Taint{}
	tv := utiltaints.NewTaintsVar(&ptr)
	if err := tv.Set(s); err != nil {
		fmt.Println(err)
	}
}

```
Output:
```
invalid taint spec: node-role.kubernetes.io/master:NoSchedule
```

**Comment by jayunit100** [comment]
cc @ravisantoshgudimetla

**Comment by dlipovetsky** [comment]
Some information I'm gathering to help figure out this right fix:

1. According to the [v1.13 API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#taint-v1-core), the Value is required.
2. The `ToString` receiver was introduced here: https://github.com/kubernetes/kubernetes/pull/32378
3. The original `ParseTaint` method was introduced here:  https://github.com/kubernetes/kubernetes/pull/31647. I noticed that, in this PR, there are a few uses of a taint that has no value, but whose string representation still has the `=` character: `node.alpha.kubernetes.io/ismaster=:NoSchedule`.

If the string representation without the `=` character is invalid, then the `ToString` receiver needs to be fixed. Otherwise, the parsing should be fixed.

**Comment by ravisantoshgudimetla** [comment]
@dlipovetsky - Thanks for creating the issue

My understanding is that taints and tolerations need to have `node.alpha.kubernetes.io/ismaster=:NoSchedule` format as they are similar to labels which have `key, value`, so `ToString` need to be fixed here.

/cc @k82cn 

/sig scheduling

**Comment by dlipovetsky** [comment]
@ravisantoshgudimetla Thanks for your input.

I've thought about how fixing `ToString` might impact existing clusters. There should be no impact, assuming all components on existing clusters already reject the invalid string representation that can be generated by `ToString`. This assumption is true if all components use the same parsing mechanism as kubelet does.

**Comment by ravisantoshgudimetla** [comment]
@dlipovetsky - No problem. 

Yes, I thought about backward compatibility too. If we fix on the api side(which we shouldn't IMHO), it may cause breakage to api. Since `ToString` is not externally exposed and not part of api, it should be fixed in that function. 

Do you want to send PR to address it?

**Comment by dlipovetsky** [comment]
@ravisantoshgudimetla 

Yes, I'd like to send a PR. I'll get started on it.

**Comment by dlipovetsky** [comment]
I suspect are instances of incorrect string representations of Taints in the Kubernetes docs. If I find them, I'll file a separate PR on k/website.

**Comment by jayunit100** [comment]
@derekwaynecarr  @aveshagarwal  @ravisantoshgudimetla  ~ can one of you help us push this taints patch through ?  would like to possibly add some more related patches in the near future as well.

**Comment by stuart-warren** [comment]
I got around this with older version of kubeadm:

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "someapiserver.acme.com:443"
    token: "sometoken"
    unsafeSkipCAVerification: true
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  taints:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
    value: '""' # notice the excessive quoting
```

outputs `--register-with-taints=node-role.kubernetes.io/master="":NoSchedule` in `/var/lib/kubelet/kubeadm-flags.env`
