### ISSUE TITLE
New scheduler priority for real load average and free memory

### ISSUE THREAD

**Issue by kabakaev** [kubernetes/kubernetes#73269]
**What would you like to be added**:
Kubelet should update node's status.loadavg and status.freeMemory on each heartbeat.
`loadavg` should be a map taken from /proc/loadavg.
`freeMemory` should be calculated as `free + buffers + cache` from /proc/meminfo, see `man 1 free`.

Scheduler should be extended with two more PriorityMaps: `loadAverage` and `freeMemory`.

**Why is this needed**:

Every kubernetes newby sooner or later gets frustrated with the fact that pods are _not_ distributed over cluster according to real-time node utilization.

Instead, _all_ containers spec must be extended with _static_ requests.memory and requests.cpu in order to improve pod scheduling decisions and prevent a "noizy neighbour" problem. What a hacky and tedious task, especially thinking of how far from reality all those requests values may be!

As of now, kube-scheduler decides on which node a new pod should be started based on [priorities](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/algorithm/priorities). The `kube-scheduler --policy-config-file` argument points to a json config listing weights of those priorityMaps.

Unfortunately, none of those priorityMaps have anything to do with real CPU and memory usage. Disk latency is not considered either. All scheduling decisions are based on static node info and the previous schedulings.

In reality, node resources may be well below of what is written by kubelet into `status.allocatable`, such as in case of kernel memory leak or some system daemon going crazy.

Also, a k8s user may write too small `requests.cpu` and `requests.memory` pod specs or not write them at all.

Any of those issues may lead to kernel OOM and extremely high `load average`. But scheduler will never know about such bad condition of a node unless kubelet sends heartbeats.  [Descheduler](https://github.com/kubernetes-incubator/descheduler) would not help wither, as it depends on good kube-scheduler knowledge.

Use of `loadavg` value for scheduling priority may be good enough to avoid scheduling on a node running out of free CPU, memory or disk throughput.

Adding a second scheduler priority based on amount of actual "free+cached" memory will improve scheduling decisions further.

**Comment by kabakaev** [comment]
@kubernetes/sig-node-feature-requests
@kubernetes/sig-scheduling-feature-requests

**Comment by wgliang** [comment]
#18620 #18438 This may be duplicate PR.

**Comment by yastij** [comment]
@kabakaev - heartbeats are reported through the Lease API now, which is independent from node status. Making the kubelet update the node status on a high frequency can cause issues at etcd level cc @wojtek-t @derekwaynecarr

**Comment by kabakaev** [comment]
@yastij , HDYT maybe such usecase may be solved better using a [custom scheduler](https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/)? I never saw it in action though.

**Comment by xiaoxubeii** [comment]
@kabakaev I agree with @yastij. Frequent updates like status.loadavg and status.freeMemory will significantly increase the pressure on kube-apiserver and etcd. One feasible approach which I made is to implement a custom scheduler and use metrics collected by a custom resource monitor.

**Comment by kabakaev** [comment]
@xiaoxubeii , what do you mean by `which I made`? Do you have any working example of a custom scheduler?

**Comment by hex108** [comment]
> @kabakaev - heartbeats are reported through the Lease API now, which is independent from node status. Making the kubelet update the node status on a high frequency can cause issues at etcd level cc @wojtek-t @derekwaynecarr

If so, could we make it(whether report the cpu/memory load information) an option for users?  I think it is really a useful feature.

**Comment by rodolfo-albuquerque** [comment]
Any updates or workarounds on this issue?

**Comment by yanivpaz** [comment]
hitting this issue as well . 
what is the recommended solution ? 
I saw https://github.com/meeramurali/Custom-Kubernetes-Scheduler

**Comment by grepthat** [comment]
It seems like the [vertical-pod-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) might be a solution to this problem?

**Comment by warmchang** [comment]
@kabakaev @unixfox The "Real Load Aware Scheduling" plugin may help you:

- KEP: https://github.com/kubernetes-sigs/scheduler-plugins/tree/6b7e77af527d8db82afb5060e5474ed524bdc0d6/kep/61-Trimaran-real-load-aware-scheduling

- PR: https://github.com/kubernetes-sigs/scheduler-plugins/pull/115
