### ISSUE TITLE
Add support for StandardSSD_LRS on Azure as SC/PV

### ISSUE THREAD

**Issue by LW81** [kubernetes/kubernetes#73260]
**What would you like to be added**:

Since last summer azure offers a Disk Type called StandardSSD.

See https://azure.microsoft.com/en-us/blog/preview-standard-ssd-disks-for-azure-virtual-machine-workloads/

These disks are cost-effective storage option optimized for workloads that need consistent performance at lower IOPS levels

As of today i can't define this type of disks in a Storage Class for Kubernetes.

**Why is this needed**:

StandardSSD offer a predictable performance at a good price point and should therefore be usable with in Kubernetes.

@kubernetes/sig-azure
/sig azure

**Comment by andyzhangx** [comment]
new managed disk types [`StandardSSD_LRS`](https://aka.ms/StandardSSDBlog), `UltraSSD_LRS` are available from `v1.13.0`

all possible `skuname` values are `Standard_LRS`, `StandardSSD_LRS`, `Premium_LRS`, `UltraSSD_LRS`

**Comment by andyzhangx** [comment]
here is the eample: https://github.com/andyzhangx/demo/blob/master/pv/storageclass-azuredisk-managed.yaml
let me know if you have any further question.
/close
