### ISSUE TITLE
--cpu-cfs-quota-period should not have effect if feature gate CPUCFSQuotaPeriod is not enabled

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes/kubernetes#73264]
**What happened**:
When run kubelet with "--cpu-cfs-quota-period 1000ms"  and without --feature-gates=CustomCPUCFSQuotaPeriod=true, kubelet would set cgroup cpu.cfs_period_us to 1000000, but make calculation based on a default value of 100000, this means if a pod has a limit of 100m, it would have a quota of 10000,  causing its limit set to 10m actually.

**What you expected to happen**:
If the cfs gate is not enabled, the "--cpu-cfs-quota-period" option should not take effect at all.

**How to reproduce it (as minimally and precisely as possible)**:
Start kubelet with "--cpu-cfs-quota-period 1000ms", and run a pod with limit set to some value, then the pod's runtime limit, which is only 10%.

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/9ce03717a90f9482436b85b512ee482374c57880/pkg/kubelet/cm/helpers_linux.go#L61-L63
The code above reset the period to default when calculating quota, but the runtime period is not reset.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
cc @dashpole @szuecs

**Comment by szuecs** [comment]
@zq-david-wang I think the problem is https://github.com/kubernetes/kubernetes/pull/63437/files#diff-5b0d60893b6218cfff53f6dc8b8488d2L68, I will prepare a fix for it

@Thanks @dims for the notification.
