### ISSUE TITLE
Discussion on admission plugin ordering

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#73291]
As part of Admission Webhook GA, we need to decide on admission plugin ordering for both standard plugins and webhooks.

The ordering problem comes out of issues like [this one](https://github.com/kubernetes/kubernetes/issues/64333)

**Problem**: Plugins can have different ideas about some fields of the object hence side effect of one plugin is affecting other plugins and the ordering may result in different results. Some plugins have validation phase at the end of the order which will fail if any other plugin changes the field they care about.

The best suggestion right now is: In the case where a mutating admission plugin makes structural additions (e.g. adding a new container), we could rerun the mutating phase to give all plugins visibility to the new substruct, and the opportunity to enforce/default/reject fields on that substruct. 

@sttts @liggitt @caesarxuchao @lavalamp @deads2k

**Comment by liggitt** [comment]
implemented in https://github.com/kubernetes/kubernetes/pull/78080
