### ISSUE TITLE
kubelet failed to start because it failed to get zone from vsphere cloud provider

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#73307]
**What happened**:

Enabled vSphere cloud provider in Kubernetes v1.12.4 cluster. But found kubelet failed to start due error to get zone from vSphere cloud provider.

```
Jan 25 07:58:25 bws-01y-20190121-mst01 hyperkube[31519]: E0125 07:58:25.351818   31519 vsphere.go:1358] Cannot list attached tags. Get zone for node bws-01y-20190121-mst01: POST https://cicd-vc1.rtp.x.x.x:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 403 Forbidden
Jan 25 07:58:25 bws-01y-20190121-mst01 hyperkube[31519]: E0125 07:58:25.361085   31519 vsphere.go:1405] Get zone for node bws-01y-20190121-mst01: POST https://cicd-vc1.rtp.x.x.x:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 403 Forbidden
Jan 25 07:58:25 bws-01y-20190121-mst01 hyperkube[31519]: F0125 07:58:25.361109   31519 kubelet.go:1354] Kubelet failed to get node info: failed to get zone from cloud provider: POST https://cicd-vc1.rtp.x.x.x:443/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags: 403 Forbidden
```

```
# cat /etc/systemd/system/kubelet.service
...
  --cloud-provider=vsphere \
  --cloud-config=/etc/cfc/conf/vsphere_cloud_conf \

# cat /etc/cfc/conf/vsphere_cloud_conf
[Global]
   user=username
   password=passw0rd
   server=cicd-vc1.x.x.x.x
   port=443
   insecure-flag=1
   datacenter=wlot01
   datastore=DS01
   working-dir=bws-01y
[Disk]
   scsicontrollertype=pvscsi
```

While the same conf works for **Kubernetes v1.11.5**.

**What you expected to happen**:

Kubelet should start successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Just build a Kubernetes v1.12.4 cluster with vSphere cloud provider enabled.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.4 
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0-87-generic
- Install tools: 
- Others:

**Comment by liqlin2015** [comment]
Checked the code https://github.com/kubernetes/kubernetes/blob/v1.12.4/pkg/cloudprovider/providers/vsphere/vsphere.go#L1345. Is it possible that the rest API client was not generated correctly or the session was expired for some reason?

**Comment by liqlin2015** [comment]
cc @dougm . Do you have any idea about the error? Compared with Kubernetes v.1.11.x, does additional privilege required for zone tags?

**Comment by subramanian-neelakantan** [comment]
This looks like a privilege issue for the kubelet's VC user that is connecting to vCenter to list the tags associated with host/cluster/datacenter. Can you verify whether this VC user has the necessary permissions setup as described in https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html? Can this user list the tags associated with a host and a cluster and a datacenter?

There is no easy way to disable zone support in vsphere cloud provider. So, you would have to get the VC user permissions fixed for the kubelet to become active again.

**Comment by liqlin2015** [comment]
Thanks @subramanian-neelakantan . I will check again the permission again listing tags associated with host/cluster/datacenter.

**Comment by liqlin2015** [comment]
@subramanian-neelakantan Do you know is there any doc talking about the permission difference in each Kubernetes release? For example, additional tag permission is required for Kubernetes > v1.12.x.

**Comment by subramanian-neelakantan** [comment]
Hi @liqlin2015, to the best of my knowledge the permissions required for the VC user has not changed across VCP releases. The required permissions have been documented in the above link 
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html. Please point out any deficiencies in this link and we can update it.

**Comment by asalmoqbel** [comment]
I am having the same issue after upgrading from v1.10.2 to v1.13.2 using Kubespray .. the cloud provider is vsphere here is the logs for the failed master:
```
vsphere.go:1404] Get zone for node xxxxxxxx: NoPermission
kubelet_node_status.go:68] Unable to construct v1.Node object for kubelet: failed to get zone from cloud provider: NoPermission
vsphere.go:1404] Get zone for node xxxxxxxx: NoPermission
kubelet.go:1379] Kubelet failed to get node info: failed to get zone from cloud provider: NoPermission

```

please let me know if you need me to provide any extra information

**Comment by asalmoqbel** [comment]
Hi @subramanian-neelakantan , regarding the permissions we didn't change the permissions but after upgrade it stopped working .. please see my comment above, appreciate your help.

**Comment by liqlin2015** [comment]
@subramanian-neelakantan We have the privilege required for dynamic persistent volume provisioning with storage policy based volume placement. Can tell which privilege is needed for querying tags associated with DataCenter, Cluster and hosts objects?

**Comment by jiatongw** [comment]
@liqlin2015 Hi, did you provide `[Labels]` in `vcp.conf` file? Or you just leave it empty?

**Comment by asalmoqbel** [comment]
@jiatongw in my case we didn't put this section ( [Labels] ) at all, the we tried to put this section empty and same results.

**Comment by subramanian-neelakantan** [comment]
The VC user configured in your vsphere.conf file needs to have System.Read privilege on the datacenter, cluster and hosts on which the k8s nodes are running in vCenter. A good way to verify whether the privileges are configured correctly would be to invoke the Get-TagAssignment powercli or invoke the QueryAttachedInventoryServiceTags() API from the VC MOB https://<vc_ip>/invsvc/mob1. These techniques are documented in VMware docs as well as in other blogs. Hope this helps.

**Comment by liqlin2015** [comment]
@subramanian-neelakantan We have the privilege required for dynamic persistent volume provisioning with storage policy based volume placement. Can tell which privilege is needed for querying tags associated with DataCenter, Cluster and hosts objects?

**Comment by luckyfengyong** [comment]
@subramanian-neelakantan Thanks for the info. It seems the permission of System.Read privilege on hosts is missed from VMware doc of https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html#minimal-set-of-vsphere-rolesprivileges-required-for-static-only-persistent-volume-provisioning. 

Can you help to confirm whether the above link could be used as pre-requirement of vSphere Cloud Provider for k8s 1.12.x?

**Comment by subramanian-neelakantan** [comment]
Hi @luckyfengyong, The "Read-only (pre-existing default role)" shown in this document includes the System.Read privilege. So things should work as expected if you provide the k8s VC user this "Read-only" role on the Datacenter/Cluster/Hosts on which k8s VMs are placed. Hope that helps and clarifies. If this resolves your problem, kindly close this issue.

**Comment by luckyfengyong** [comment]
Thanks @subramanian-neelakantan. We are now testing the minimum requirement. Once the test is done, we will close the ticket.

**Comment by monica-wei** [comment]
Hi @subramanian-neelakantan,  in my case we don't provide `[Labels]` in vsphere configuration file and we don't have storage policy either.

so we set the the Minimal roles/privileges for vsphere according to https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html#minimal-set-of-vsphere-rolesprivileges-required-for-dynamic-volume-provisioning-without-storage-policy-based-volume-placement

But there's get zone error of kubelet. Could you help to confirm which privileges is missing for get zone function in the guide? Thanks in advance.

**Comment by subramanian-neelakantan** [comment]
Hi @monica-wei, have you made sure that the k8s user logging in to vCenter has been provided the "Read-only" role on the datacenter, cluster and hosts on which k8s VMs are running? To do this:
1. log in to vCenter as a administrator user
2. Select Datacenter, go to Permissions tab
3. Click on add permission button, select k8s user, and select "Read-only" role
4. Click ok.

This should now provide the necessary System.Read privilege for the k8s user on the Datacenter. Repeat it on Cluster and Hosts as well where the k8s VMs are running. Now the tagging APIs during kubelet startup should be successful, and hence kubelet should startup successfully. Hope that helps.

**Comment by monica-wei** [comment]
Hi @subramanian-neelakantan thanks for your quick response.

I **granted the "Read-only" role on the vCenter, datacenter and set "propagate to children" to No** according to Minimal set of vSphere roles/privileges required for dynamic volume provisioning **without storage policy** based volume placement

![image](https://user-images.githubusercontent.com/47728900/52939460-33991d80-339f-11e9-8b8d-ba5ba877b9da.png)

So based on your description, I should repeat it on Cluster and Hosts as well. 
And set "propagate to children" to No, right?

Could you or someone else help to update the guide https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html.

Best Wishes!

**Comment by subramanian-neelakantan** [comment]
@monica-wei, Ah I see that this instruction is given only for the Datacenter (with propagate to children set to no). I will see how to update this documentation.

Meanwhile, could you confirm here whether repeating the permission setting for Cluster and Hosts solves this issue for you? It might help others coming here for the same issue.

**Comment by monica-wei** [comment]
Hi @subramanian-neelakantan , I tested in our lab, kubelet is running after adding "Read-only" role on the vCenter, datacenter, Cluster and Hosts where VMs are running. And the "propagate to children" set to no.

**Comment by subramanian-neelakantan** [comment]
Hi @monica-wei, thanks for confirming. Really appreciate you reporting the documentation issue in 
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html.

**Comment by luckyfengyong** [comment]
@subramanian-neelakantan Our test is done based on comments of https://github.com/kubernetes/kubernetes/issues/73307#issuecomment-460523632. 

Please feel free to close it.
