### ISSUE TITLE
vSphere volumes do not have zone labels auto applied

### ISSUE THREAD

**Issue by subramanian-neelakantan** [kubernetes/kubernetes#73301]
**What happened**:
With zones marked using tags in vCenter and using VCP, the k8s nodes show the zone information correctly in its labels, but a volume does not have the zone labels applied. A node's zone information works correctly due to PR https://github.com/kubernetes/kubernetes/pull/66795.

```
$:~> kubectl get nodes --show-labels
NAME                 STATUS                     AGE       VERSION                                     LABELS
kubernetes2-master   Ready,SchedulingDisabled   6d        v1.14.0-alpha.0.1570+ccf84273118a1f-dirty   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=region_1,failure-domain.beta.kubernetes.io/zone=zone_1,kubernetes.io/hostname=kubernetes2-master
kubernetes2-node1    Ready                      6d        v1.14.0-alpha.0.1570+ccf84273118a1f-dirty   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=region_1,failure-domain.beta.kubernetes.io/zone=zone_1,kubernetes.io/hostname=kubernetes2-node1
```

However, a newly created volume does not show any zone labels today.

```
$:~> kubectl get pv --show-labels
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM          STORAGECLASS   REASON    AGE       LABELS
pvc-aab193fe-1fc8-11e9-a263-005056929afb   1Mi        RWO           Delete          Bound     default/pvc1   sc1                      17h       None
```

**What you expected to happen**:

A newly created volume should be automatically applied with the well-known zone labels.

```
$:~> kubectl get pv --show-labels
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM          STORAGECLASS   REASON    AGE       LABELS
pvc-aab193fe-1fc8-11e9-a263-005056929afb   1Mi        RWO           Delete          Bound     default/pvc1   sc1                      17h       failure-domain.beta.kubernetes.io/region=region_1,failure-domain.beta.kubernetes.io/zone=zone_1
```

This is important since the scheduler places the pod on a node of the same zone based on the Volume's zone information.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup zones in vCenter by tagging an ESX host, cluster or datacenter with the tag name of your choice and tag category, say "zoneCategory" and "regionCategory".
2. Update the /etc/kubernetes/vsphere.conf file in each k8s node to include the following and restart kubelet.
```
[Labels]
    zone = "zoneCategory"
    region = "regionCategory"
```
3. Create a PV and look at the auto-applied labels on it as shown above. The zone information is missing.

**Anything else we need to know?**:
The partially addresses https://github.com/kubernetes/kubernetes/issues/67703

**Environment**:
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: vSphere

**Comment by liqlin2015** [comment]
@subramanian-neelakantan I have an issue https://github.com/kubernetes/kubernetes/issues/73307 to get zone from vsphere cloud provider with Kubernetes v1.12.4. Is there any limitation for zone support?
How about I disable the zone label?

**Comment by subramanian-neelakantan** [comment]
@liqlin2015 I have responded in issue #73307.
