### ISSUE TITLE
Endpoints API Object could not support large number of endpoints

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#73324]
**What happened**:

When a service select many backend pods (e.g. 10k), the corresponding Endpoints object becomes big (>1MB in proto). 

On Kube-proxy, the API watcher will start dropping the endpoints object and will not program iptables for the service. https://github.com/kubernetes/kubernetes/issues/57073
```
k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: watch of *core.Endpoints ended with: very short watch: 
k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Unexpected watch close - watch lasted less than a second and no items received
```

On master, if the object is too big. It can result in write failure to etcd. 
```
Error syncing endpoints for service "xxxxx/xxxxxxxxx": etcdserver: request is too large
```

**What you expected to happen**:

It should just work.

**Proposed Short Term Fix**:

1. Add support in Endpoint controller to truncate the endpoint object to the size supported(configured). With this approach, while all endpoints are not reflected, traffic disruption can be avoided by avoiding stale IP tables state on nodes.   
2. Add events when endpoint object size is approaching limits and when it exceeds limit - resulting in truncation. (Ideally also generate events where we would drop the message)

**Environment**: OSS K8s
- Kubernetes version (use `kubectl version`): 1.11

**Comment by nikopen** [comment]
Hi @freehan , is another PR needed to close this?
Code Freeze is in effect from next Friday.

**Comment by liggitt** [comment]
given this is not a regression, it doesn't seem release blocking

**Comment by spiffxp** [comment]
/milestone clear
v1.14 release lead here, at this late stage in the release cycle, this doesn't seem like it's destined for this release.

Please come talk to us in #sig-release if you feel this was done in error

**Comment by alejandrox1** [comment]
This is being tackled in https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/0752-endpointslices
so removing the rotten label to (to distinguish this from issues which are labeled as rotten and do need some work done)
/remove-lifecycle rotten
