### ISSUE TITLE
HTTP Error: statusCode=404 No such image: gcr.io/google_containers/pause:0.8.0

### ISSUE THREAD

**Issue by wgq91here** [kubernetes/kubernetes#7332]
I installed kubernete 0.14 a week age. Today I update kebernete to 0.15, and pods couldn't up. It was always PENDING.

I checked message and found "HTTP Error: statusCode=404 No such image: gcr.io/google_containers/pause:0.8.0"

<pre>
Apr 26 09:05:57 localhost docker: No such image: gcr.io/google_containers/pause:0.8.0
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=info msg="-job image_inspect(gcr.io/google_containers/pause:0.8.0) = ERR (1)"
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: gcr.io/google_containers/pause:0.8.0"
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=error msg="HTTP Error: statusCode=404 No such image: gcr.io/google_containers/pause:0.8.0"
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=info msg="POST /images/create?fromImage=gcr.io%2Fgoogle_containers%2Fpause&tag=0.8.0"
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=info msg="+job pull(gcr.io/google_containers/pause, 0.8.0)"
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=info msg="+job resolve_repository(gcr.io/google_containers/pause)"
Apr 26 09:05:57 localhost docker: time="2015-04-26T09:05:57+08:00" level=info msg="GET /containers/json"
</pre>

I already jump out of GFW. Why?

**Comment by wgq91here** [comment]
<code>
[root@localhost ~]# ping gcr.io
PING gcr.io (74.125.204.82) 56(84) bytes of data.
64 bytes from 74.125.204.82: icmp_seq=1 ttl=46 time=78.6 ms
64 bytes from 74.125.204.82: icmp_seq=2 ttl=46 time=78.3 ms
^C
--- gcr.io ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 78.312/78.462/78.612/0.150 ms
[root@localhost ~]# docker pull gcr.io/google_containers/pause
FATA[0020] Error response from daemon: v1 ping attempt failed with error: Get http://gcr.io/v1/_ping: dial tcp: i/o timeout 
[root@localhost ~]# 
</code>

**Comment by mattmoor** [comment]
Can you curl https://gcr.io/v1/_ping from the machine?

Where is this running?  What version of Docker?

**Comment by wgq91here** [comment]
<pre>
[root@localhost ~]# curl https://gcr.io/v1/_ping
true
</pre>
OK. It is RUNNING.

**Comment by satnam6502** [comment]
Sorry @zmerlynn i should have just cc-ed you rather than assigning to you.

**Comment by Telmo** [comment]
Why is kubernetes trying to download an image from a registry out in the internet. When trying to test in network that have no access to the internet the testing completely breaks down and it makes it so kubernetes can't be deployed to not internet facing hosts.

**Comment by roberthbailey** [comment]
The default behavior is to download the pause container from gcr.io. This can be overridden by passing a command line flag to the kubelet on startup.

**Comment by tobegit3hub** [comment]
The `gcr` and `pause` image are blocked by Chinese gov, you know. How can I skip this when I try to deploy the pod or rc?

**Comment by roberthbailey** [comment]
You can build your own pause image and put it into a registry that you can access. Then when you start the kubelet, pass `pod-infra-container-image` and point it at your own pause image (the flag is defined [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/app/server.go#L196)).

**Comment by tobegit3hub** [comment]
Hi @roberthbailey . Please put it in docker hub and we all appreciate about it.

**Comment by roberthbailey** [comment]
There's already a pause container there: https://registry.hub.docker.com/u/kubernetes/pause/ (but I thought docker hub was also inaccessible, hence my suggestion to build your own version).

**Comment by tobegit3hub** [comment]
Great! Docker hub is accessible and it would be better to get the image from docker hub by default. Anyway, thanks for your work.

**Comment by mattmoor** [comment]
@tobegit3hub 
I am curious how DockerHub is visible and GCR is not...?

**Comment by tobegit3hub** [comment]
It's the gov issue and we're gonna judge it. Most google services are blocked in China. Currently Docker services just work but I will NOT make sure it works later, you know :cold_sweat:

**Comment by resouer** [comment]
@roberthbailey Is it possible to sync contents in gcr.io to hub.docker.com somehow? If Google feels tricky to do so, we'd like to do it. Just provide us a method to achieve that. :smile:

**Comment by roberthbailey** [comment]
I'm not sure, but @mattmoor might know.

**Comment by tobegit3hub** [comment]
Now we solve the problem by running these two commands. And not so bad.

```
docker pull docker.io/kubernetes/pause
docker tag docker.io/kubernetes/pause gcr.io/google_containers/pause:0.8.0
```

**Comment by roberthbailey** [comment]
Based on the last update (over 2 months ago) this issue is resolved.

**Comment by xuedihualu** [comment]
@tobegit3hub 
do not start the container from the image(docker tag docker.io/kubernetes/pause gcr.io/google_containers/pause:0.8.0)???

**Comment by xuedihualu** [comment]
I have the new problem  API error (500): No command specified

**Comment by Rev1408** [comment]
on a Minikube there is no kubelet, how do we pass this option pod-infra-container-image
