### ISSUE TITLE
Need ExternalName test for mixed-OS clusters

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73328]
There aren't any tests that cover ExternalPort services from Windows pods today. Here's an example manual case that can best explain what needs to be automated.

1. Start a Windows pod on a Windows node
2. `kubectl create -f …` this yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: searchengine
spec:
  type: ExternalName
  externalName: www.google.com
```

3. `kubectl exec <podname> curl.exe searchengine`

```
azureuser@k8s-master-30163644-0:~$ kubectl exec iis-2019-c5d48d8c-cqw7x curl.exe searchengine
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
100  1561  100  1561    0     0   1561      0  0:00:01 --:--:--  0:00:01 33212
```
This shows that DNS is working for the ExternalName service entry. The actual HTTP request fails (by design) because curl is putting the service name in the header which is rejected by the http server itself. 

/sig windows
/good-first-issue

**Comment by prisar** [comment]
@PatrickLang Can explain why you think http server is rejecting service name in header?

**Comment by PatrickLang** [comment]
curl was using the URL given to set the hostname in the HTTP request.

To illustrate what this does - here's another way to get the same result. Ask www.google.com to give you the page for www.bing.com. It can't serve that content so it returns a 404.

```
curl.exe -H 'Host: www.bing.com' http://www.google.com
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
```

Therefore, if I had run `curl.exe -H 'www.google.com' searchengine` that would have succeeded.

**Comment by bclau** [comment]
We could use the test ``[sig-network] DNS should provide DNS for ExternalName services`` for this. This test does:

- creates an initial ExternalName to foo.example.com and validates the DNS resolution.
- renames the ExternalName to bar.example.com and validates the new DNS resolution.
- changes the Service Type to ClusterIP and validates the new DNS resolution.

**Comment by keremgocen** [comment]
Is anyone working on this? I'd like to jump on it

**Comment by PatrickLang** [comment]
sure, go for it. 
/assign @keremgocen

**Comment by mgdevstack** [comment]
@keremgocen  What kind of modifications are required to run [this](https://github.com/kubernetes/kubernetes/issues/73328#issuecomment-460689175) e2e in [Windows]. 
TestName: 
`[sig-network] DNS should provide DNS for ExternalName services`

I'm in process to promote DNS based e2e from `e2e/network/dns.go` into Conformance suite.

**Comment by bclau** [comment]
HI @mgdevstack. I am also looking into that test, as it is a bit flaky on Windows. My recommendation would be to increase the retry period / number of retries for the dig command.

**Comment by mgdevstack** [comment]
Thanks for pointing its Flaky behavior on Windows. I'm in process to setup k8s cluster in Windows env and then troubleshoot.

**Comment by PatrickLang** [comment]
Ok, looks like the right things are happening. #74964 is approved. Once https://github.com/kubernetes/kubernetes/pull/74983 merges it should show up in testgrid for Windows too.

/remove-good-first-issue
