### ISSUE TITLE
Restart POD if container dies

### ISSUE THREAD

**Issue by psaini79** [kubernetes/kubernetes#73338]
Is there a way or parameter to set in yaml files to forcefully restart the pod if a container restarts in a pod?

At this moment, if container dies, it restarts but it left some previous state. For my application  requirement I have few IP aliases on eth0 network card. If container dies the IP aliases remain in a pod and other applications assumes that application node is still active and part of the cluster.

**Environment**:
- kubeadm-1.11.3-2.0.2.el7.x86_64
- Machine : Baremetal machine 
-  OS : Oracle Linux Server release 7.5
- Kernel (e.g. `uname -a`): 4.1.12-112.16.4.el7uek.x86_64
- Install tools:
- Others:

**Comment by psaini79** [comment]
sig /Architecture

**Comment by neolit123** [comment]
/remove-sig architecture

hello, it's best to ask support questions in your support channels like stackoverflow.
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

this is probably the answer you are looking for:
https://stackoverflow.com/a/46127779

/close
