### ISSUE TITLE
kubernete v1.13 kubelet not running

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#73340]
I use the kubernetes v1.13 source code and make it then deploy the cluster,I found the kubelet not running
is there any para set to kubelet?thanks!

[root@host-101-101-101-127 kubernetes]# systemctl status kubelet.service 
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 六 2019-01-26 15:06:55 CST; 2s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 73289 ExecStart=/usr/bin/kubelet $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBELET_API_SERVER $KUBELET_ADDRESS $KUBELET_PORT $KUBELET_HOSTNAME $KUBE_ALLOW_PRIV $KUBELET_ARGS (code=exited, status=255)
  Process: 73286 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/hugetlb/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73283 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/devices/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73280 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/perf_event/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73277 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/cpuset/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73274 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/memory/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73271 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/freezer/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73268 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/net_cls,net_prio/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73265 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/systemd/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73262 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/cpu,cpuacct/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73259 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/blkio/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73256 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/pids/kubelet.service (code=exited, status=0/SUCCESS)
  Process: 73253 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/pids/system.slice (code=exited, status=0/SUCCESS)
  Process: 73250 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/hugetlb/system.slice (code=exited, status=0/SUCCESS)
  Process: 73247 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/freezer/system.slice (code=exited, status=0/SUCCESS)
  Process: 73244 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/net_cls,net_prio/system.slice (code=exited, status=0/SUCCESS)
  Process: 73241 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/perf_event/system.slice (code=exited, status=0/SUCCESS)
  Process: 73239 ExecStartPre=/bin/mkdir -p /sys/fs/cgroup/cpuset/system.slice (code=exited, status=0/SUCCESS)
 Main PID: 73289 (code=exited, status=255)

1月 26 15:06:55 host-101-101-101-127 systemd[1]: Unit kubelet.service entered failed state.
1月 26 15:06:55 host-101-101-101-127 systemd[1]: kubelet.service failed.

the kubelet log is :
F0126 15:16:11.062083   84730 server.go:199] unrecognized feature gate: Accelerators
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0xc00000e001, 0xc00095e000, 0x804, 0x2710)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:828 +0xd4
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x6fb3860, 0xc000000003, 0xc0007b0210, 0x6d52fcf, 0x9, 0xc7, 0x0)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:782 +0x18e
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printDepth(0x6fb3860, 0x3, 0x1, 0xc000823c20, 0x1, 0x1)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:669 +0x129
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).print(0x6fb3860, 0x3, 0xc000823c20, 0x1, 0x1)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:660 +0x5a
k8s.io/kubernetes/vendor/k8s.io/klog.Fatal(0xc000823c20, 0x1, 0x1)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1187 +0x53
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000794000, 0xc00004c100, 0xe, 0xe)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:199 +0x943
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000794000, 0xc00004c100, 0xe, 0xe, 0xc000794000, 0xc00004c100)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2cc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000794000, 0xc00077e7b0, 0x41446e8, 0xc0006dff28)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000794000, 0x41444a8, 0x6fb3420)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:43 +0xc1

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x6fb3860)
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:941 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
        /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:403 +0x69

**Comment by shubheksha** [comment]
Hi @jianglingxia, the GitHub issue tracker isn't the best place to ask for support regarding the operation of Kubernetes. Please try one of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) listed instead.

**Comment by neolit123** [comment]
+1
/close
