### ISSUE TITLE
why is my pod always at init status?

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#73347]
ceph-mds-cdcf54647-c4n5f               0/1     Init:0/2    0          105s
ceph-mds-cdcf54647-wvvcc               0/1     Init:0/2    0          147m

why is my pod always at init status?

[root@node1 ~]# kubectl describe pod ceph-mds-cdcf54647-c4n5f -n ceph
Name:               ceph-mds-cdcf54647-c4n5f
Namespace:          ceph
Priority:           0
PriorityClassName:  <none>
Node:               node4/172.20.164.160
Start Time:         Sat, 26 Jan 2019 20:20:12 +0800
Labels:             application=ceph
                    component=mds
                    pod-template-hash=cdcf54647
                    release_group=ceph-client
Annotations:        configmap-bin-hash: 3c1a68f5e409af99db7275a4eb58e92318c6cd12d8a52a27ba71b526cf125e47
                    configmap-etc-client-hash: 5b386d0e973c856a3caf424651c8b5e31e7aad3fd90eb8dbfbf25a784291c51c
Status:             Pending
IP:                 10.233.74.71
Controlled By:      ReplicaSet/ceph-mds-cdcf54647
Init Containers:
  init:
    Container ID:  docker://e198d0b15c0923043c494c7fa935c1e01c1ff35ef19f060d022c56a8517f316e
    Image:         quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    Image ID:      docker-pullable://quay.io/stackanetes/kubernetes-entrypoint@sha256:32b1b657ee4bcc9cc7a1529e31d8e1a06376172373ee020f97f3e78168fde4b6
    Port:          <none>
    Host Port:     <none>
    Command:
      kubernetes-entrypoint
    State:          Running
      Started:      Sat, 26 Jan 2019 20:20:14 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      POD_NAME:              ceph-mds-cdcf54647-c4n5f (v1:metadata.name)
      NAMESPACE:             ceph (v1:metadata.namespace)
      INTERFACE_NAME:        eth0
      PATH:                  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
      DEPENDENCY_SERVICE:    ceph:ceph-mon
      DEPENDENCY_JOBS:       ceph-storage-keys-generator,ceph-mds-keyring-generator,ceph-rbd-pool
      DEPENDENCY_DAEMONSET:  
      DEPENDENCY_CONTAINER:  
      DEPENDENCY_POD_JSON:   
      COMMAND:               echo done
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ceph-mds-token-h5tw7 (ro)
  ceph-init-dirs:
    Container ID:  
    Image:         docker.io/ceph/daemon:master-0b3eb04-mimic-centos-7-x86_64
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /tmp/init-dirs.sh
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      CLUSTER:  ceph
    Mounts:
      /run from pod-run (rw)
      /tmp/init-dirs.sh from ceph-client-bin (ro)
      /var/lib/ceph from pod-var-lib-ceph (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ceph-mds-token-h5tw7 (ro)
Containers:
  ceph-mds:
    Container ID:  
    Image:         docker.io/ceph/daemon:master-0b3eb04-mimic-centos-7-x86_64
    Image ID:      
    Port:          6800/TCP
    Host Port:     0/TCP
    Command:
      /tmp/mds-start.sh
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       tcp-socket :6800 delay=60s timeout=5s period=10s #success=1 #failure=3
    Readiness:      tcp-socket :6800 delay=0s timeout=5s period=10s #success=1 #failure=3
    Environment:
      CLUSTER:        ceph
      CEPHFS_CREATE:  1
      NAMESPACE:      ceph (v1:metadata.namespace)
      MON_PORT:       6789
    Mounts:
      /etc/ceph/ceph.client.admin.keyring from ceph-client-admin-keyring (ro)
      /etc/ceph/ceph.conf.template from ceph-client-etc (ro)
      /run from pod-run (rw)
      /tmp/mds-start.sh from ceph-client-bin (ro)
      /tmp/utils-checkDNS.sh from ceph-client-bin (ro)
      /var/lib/ceph from pod-var-lib-ceph (rw)
      /var/lib/ceph/bootstrap-mds/ceph.keyring from ceph-bootstrap-mds-keyring (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ceph-mds-token-h5tw7 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ceph-client-etc:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ceph-client-etc
    Optional:  false
  ceph-client-bin:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ceph-client-bin
    Optional:  false
  pod-var-lib-ceph:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  pod-run:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  ceph-client-admin-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ceph-client-admin-keyring
    Optional:    false
  ceph-bootstrap-mds-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ceph-bootstrap-mds-keyring
    Optional:    false
  ceph-mds-token-h5tw7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ceph-mds-token-h5tw7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  ceph-mds=enabled
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  65s   default-scheduler  Successfully assigned ceph/ceph-mds-cdcf54647-c4n5f to node4
  Normal  Pulled     63s   kubelet, node4     Container image "quay.io/stackanetes/kubernetes-entrypoint:v0.3.1" already present on machine
  Normal  Created    63s   kubelet, node4     Created container
  Normal  Started    63s   kubelet, node4     Started container

**Comment by 13567436138** [comment]
i see

**Comment by njxiaohan** [comment]
@13567436138 I met the same problem,how did you fix it ?

**Comment by spuny** [comment]
Yea, please let us know how did you fixed this problem.

Thanks
