### ISSUE TITLE
Proposal: Replace Service with ReverseProxy

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#73352]
## Problem
The name Service doesn’t really describe what a k8s Service does or is and frequently causes naming conflicts in higher level abstractions. 

## Proposal
Rename or replace the Service resource with a similar resource named ReverseProxy. 

## Reasoning
ReverseProxy better describes the current functionality and intent behind the Service resource and is more consistent with existing infrastructure terminology, which will make it easier to learn/teach/communicate. Creating a new resource will also allow re-thinking the abstraction to make it more flexible (e.g. make KubeProxy just one of several optional backend/controller types. 

The reason I propose replacement over just renaming is to aid rollout of a new resource type without immediately breaking reverse compatibility. ReverseProxy can be added to replace Service the same way ReplicaSet replaced ReplicationController. 

## Alternatives Considered
Services are currently being used to configure L4 & L7 load balancers (a type of reverse proxy) both internal and external to K8s. But a reverse proxy in front of a single pod isn’t balancing load, it’s just acting as a static ingress IP for a pod that may be replaced over time. So **LoadBalancer** is too specific a name. 

The reason not to call it a **StaticIP** is because in most IaaS, the static IPs can be reserved and attached/detached to only a single resource (e.g. a VM), not a set of resources. Usually a static IP would be attached to a load balancer or reverse proxy which would itself handle the fan out.

/cc @kubernetes/sig-architecture-proposals

**Comment by neolit123** [comment]
/sig architecture

you might get a better response about your proposal if you you send a message to the sig-architecture mailing list:
https://github.com/kubernetes/community/tree/master/sig-architecture

**Comment by karlkfi** [comment]
The bot said pinging the group would send the mailing list an email. Should I send an email in addition?

**Comment by bgrant0607** [comment]
Thanks for the suggestion.

We'll consider it if/when we make major changes to Service.

I made note of it here:
https://docs.google.com/presentation/d/16c8i5ptRcsubBE_uRymGTklgOcvmAeAuRxSsSIWKGeM/edit#slide=id.g4741dd49cd_1_138

cc @thockin

**Comment by bgrant0607** [comment]
For posterity: https://github.com/knative/serving/issues/412#issuecomment-475322374
