### ISSUE TITLE
Kubelet serving CSR not auto-approved

### ISSUE THREAD

**Issue by jnummelin** [kubernetes/kubernetes#73356]
**What happened**:

I enabled `serverTLSBootstrap: true` on kubelet and expected the serving certificates CSR to be auto-approved by controller manager as per docs here: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#approval

Discussing with @mauilion on Slack revealed that `csrapproving` controller does NOT approve serving CSR's at all.

So it needs to be explicitly mentioned in the docs that the auto-approval works only for client certs. Otherwise there will be other chasing the rabbit deep down for hours like I did. :)

Is there any reason why the serving CSR is not approved automatically?

**What you expected to happen**:

Based on the docs I expected the serving CSR to be automatically approved.

**How to reproduce it (as minimally and precisely as possible)**:

Enable `serverTLSBootstrap: true` on kubelet and watch the CSR staying in `Pending` state.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration: Any env
- OS (e.g. from /etc/os-release): Centos 7.4&7.5, Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools: Tested with Kontena Pharos, kubeadm
- Others:

**Comment by NicolasT** [comment]
See the note in the documentation you linked to:

> Note: The CSR approving controllers implemented in core Kubernetes do not approve node serving certificates for security reasons. To use RotateKubeletServerCertificate operators need to run a custom approving controller, or manually approve the serving certificate requests.

Which refers to https://github.com/kubernetes/community/pull/1982

**Comment by jnummelin** [comment]
@NicolasT Thanks for pointing that out, it was too well hidden from me under rotation part of the docs. I swear I had read through that page like 23 times.

Should this be closed since it works as-designed, or kept open for the discussion to maybe enable auto-approval for serving certs too.

**Comment by liggitt** [comment]
This is working as designed. There is no information in the API to determine whether a particular address belongs to a node. 

/close

**Comment by jtackaberry** [comment]
> Thanks for pointing that out, it was too well hidden from me under rotation part of the docs. I swear I had read through that page like 23 times.

Don't feel bad -- I fell down this same rabbit hole this week, and probably wasted even more time than you, and even read that bit in the documentation but so much material online (most of it Chinese :)) suggested the selfnodeserver was indeed a thing.  And so I had convinced myself that I was simply missing an RBAC incantation.

It wasn't until actually seeing 7665f15 that I realized I was chasing my own tail.

**Comment by clementnuss** [comment]
if someone arriving on this issue is looking for a way to auto-approve kubelet-serving CSR, you might want to check this controller I recently wrote to achieve that goal.
unlike existing approvers, this one implements a series of validation to prevent attackers from forging certificates
https://github.com/postfinance/kubelet-csr-approver
