### ISSUE TITLE
Update CONTRIBUTING.md to include slightly more detail

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#7335]
Some questions I had:

* If a PR comes in from an outside contributor, is the standard procedure for one maintainer to look at it, or two? Is there something that determines this?
* What does the LGTM GitHub label mean? When is/isn't it used?

**Comment by ghodss** [comment]
* How do those one or two maintainers relate to the Assignee? Is the Assignee of an outside PR expected to merge, or to mark LGTM and someone else merges?

**Comment by jellonek** [comment]
Hmmm... Quite old issue with few questions - could be this closed/resolved in near future?

**Comment by bgrant0607** [comment]
@jellonek We will document this as part of our work on contributor workflow.

cc @apelisse @grodrigues3
