### ISSUE TITLE
Replace kubernetes/pkg/util/net/sets with code in k8s.io/utils/net/

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#73361]
At some point, the code in https://github.com/kubernetes/kubernetes/tree/master/pkg/util/net/ (net.go and ipnet.go) was moved to https://github.com/kubernetes/utils/tree/master/net

However we have not started using the code in the kubernetes/utils library. We should switch over to the vendored library and delete the duplicate code in the main repo.

**Comment by vjdhama** [comment]
@dims I would like to work on this.

**Comment by ashishranjan738** [comment]
I also work on this issue
