### ISSUE TITLE
kube-proxy: ipv4/ipv6 mix crashes: KUBE-MARK-DROP':No such file or directory

### ISSUE THREAD

**Issue by LittleFox94** [kubernetes/kubernetes#73360]
Hi there,

I'm not entirely sure if this is a bug or a funny configuration fault. Since that exact configuration worked before, I'm still reporting it.

**What happened**:

Having mixed IPv4 and IPv6 addresses for pods prevented `kube-proxy` (in `iptables` mode) from creating iptables rules. Logged was an error from iptables-save: `Couldn't load target 'KUBE-MARK-DROP':No such file or directory`.

Since there weren't a lot iptables rules written before the crashing command, network was completely down on that node.

This problem only affected a single node of my 4 node cluster (3 controllers which are also workers, one additional worker). Affected node was a controller node.

**What you expected to happen**:

Create iptables rules as the cluster did before I started with the upgrades.

**How to reproduce it (as minimally and precisely as possible)**:

I started today with upgrading my cluster from 1.10.11 to 1.13.2 (installing every latest patch version for every minor in order). This problem started shortly after rolling out 1.12.5 after a node had an unrelated problem and had to be restarted. I think that reboot only uncovered the bug and the other nodes would also be affected after a reboot (or `kube-proxy --cleanup`).

I had a funny-but-working config. My containers all have IPv4 addresses, but kubelet was configured to use the IPv6 address of the node (`--node-ip`, `--address`). This resulted in Pods created by a DaemonSet having IPv6 addresses.

That exact configuration worked on 1.10.11 and broke somewhere newer. The versions installed today before seeing the bug were 1.10.12, 1.11.7 and 1.12.5. 

Fixing the kubelet config to use the IPv4 node address in the flags given above, restarting all kubelets and kube-proxies and then deleting all pods created by DaemonSets fixed the issue.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): stated above
- Cloud provider or hardware configuration: virtual machines, different specs
- OS (e.g. from /etc/os-release): Debian Stretch (current stable)
- Kernel (e.g. `uname -a`): 4.9.0-8-amd64 (debian stretch kernel)
- Install tools: custom playbooks for Ansible, can be provided with history regarding this bug
- Others: no CNI plugin but static routes

**Comment by LittleFox94** [comment]
@kubernetes/sig-network-bugs

**Comment by danwinship** [comment]
> I had a funny-but-working config. My containers all have IPv4 addresses, but kubelet was configured to use the IPv6 address of the node

No, that's not a working config. You can currently use either *only* IPv4 addresses, or *only* IPv6 addresses. It shouldn't let you bring up the cluster the way you did, but there's not enough sanity-checking, so instead of giving you a proper error early on, it's crashing in a confusing way later.

**Comment by LittleFox94** [comment]
OK then :)

I just wanted to report it because it worked in a prior version. If I understand you correctly, it only worked by accident?

(you may close this issue)

**Comment by 11janci** [comment]
Just to clarify: AFAIK the pods' IPs are created based on the podCIDR config parameter (that comes from the master) and not the host's IP. Also, containers share the pod's IP. So if your containers got an IPv4 address, it came from the podCIDR param from master.
So to fix the insufficient sanity checking, there needs to be a comparison of IP versions of podCIDR vs the host's IP, am I correct?

**Comment by danwinship** [comment]
/remove-lifecycle stale
I'll check the corresponding PR...

**Comment by khayamgondal** [comment]
@danwinship @fejta-bot @LittleFox94 is it still open? I can take it.

**Comment by vegemitecheesetoast** [comment]
@thockin can I take this? This will be my first contribution, I think it's a good starter.

**Comment by vegemitecheesetoast** [comment]
I found another issue to start - feel free to give to someone else

**Comment by conwaychriscosmo** [comment]
Is this still a bug that needs to be fixed?

**Comment by zhan849** [comment]
@conwaychriscosmo we just hit it in 1.14.5, we might want to re-open

**Comment by JokerDevops** [comment]
I encountered the same error in version 1.13.6.
```
Oct 21 15:31:14 node49 kube-proxy: E1021 15:31:14.145695    7041 proxier.go:1204] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.4.21: Couldn't load target `KUBE-MARK-DROP':No such file or directory
Oct 21 15:31:14 node49 kube-proxy: Error occurred at line: 14
Oct 21 15:31:14 node49 kube-proxy: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```
This looks like an iptables-restore usage error, is it a code problem? Error calling method?

**Comment by aojea** [comment]
/close
This should be fixed by these PRs that ensure that the KUBE-MARK-DROP rule exists:
https://github.com/kubernetes/kubernetes/pull/84422
https://github.com/kubernetes/kubernetes/pull/82214
