### ISSUE TITLE
Fuzzer should be aware of API defaults

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#7337]
Currently the fuzzer does not apply the defaulting functions, which means that any defaulted fields need to be specially fuzzed to avoid a diff when an object is round-tripped.  The fuzzer should apply the defaulting functions and we should take out the custom fuzzing handlers that exist solely to fuzz default fields.

**Comment by lavalamp** [comment]
We desperately need to split the fuzzer into a round-trip test and a does-this-crash-the-decoder test. This issue is only applicable to the former.
