### ISSUE TITLE
Finish hooking up run_as_username on Windows

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73387]
https://github.com/kubernetes/kubernetes/pull/64009 added run_as_username to the container runtime interface, but did not hook it up in the Kubernetes `v1.Container.SecurityContext.runAsUser` field. That's still an int, which won't work on Windows.

**Anything else we need to know?**:
#69905 is tracking testing for this

/milestone v1.14
/sig windows
/sig architecture

**Comment by liggitt** [comment]
> I don't think we can convert existing fields from int to IntOrString, as was implied by [kubernetes/enhancements#732](https://github.com/kubernetes/enhancements/pull/732). That would break any client with compiled-in types that then encountered a string in that field.

correct, we cannot change the primitive type of an already released field

**Comment by jsturtevant** [comment]
I've started to tackle this.  Are there considerations (versioning,back compatibility, etc) of adding a new field to `v1.Container.SecurityContext`?  

Does a new field name of `v1.Container.SecurityContext.runAsUserName` work? Or should it be something like `v1.Container.SecurityContext.windows.runAsUser`?

**Comment by jsturtevant** [comment]
I opened a PR to try it out.  I modeled it after [SELinuxOptions in the SecurityContext.]( https://github.com/kubernetes/kubernetes/blob/85f1205efa89008e6e94a92d66a9dd691cb59825/staging/src/k8s.io/api/core/v1/types.go#L2951)

**Comment by nikopen** [comment]
/milestone v1.15

@PatrickLang the kanban board is great!

**Comment by liggitt** [comment]
work on an ongoing feature, recategorization

**Comment by mikedanese** [comment]
cc @tallclair per RuntimeClass.
