### ISSUE TITLE
Mysterious authorization failure to `GET /` in aggregated apiservers

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#73389]
**What happened**:
I tested the sample-apiserver again, and looked in the log of the wardle apiserver (which was running `-v=5`).  I found nearly regular repeats (with a period of 30 seconds) of couplets like the following.

```
I0128 06:37:06.730494       1 authorization.go:73] Forbidden: "/", Reason: ""
I0128 06:37:06.732291       1 wrap.go:47] GET /: (12.89124ms) 403 [Go-http-client/2.0 10.0.2.15:33206]
```

The client IP:port match the main kube apiserver.

I can not find corresponding entries in the main kube apiserver's log, not even when I turn it up to `-v=8`.

**What you expected to happen**:

I expected no authorization failures.  I expected more information when there _is_ a failure.  I expected a more informative UserAgent string.  I expected relevant debug logging in the main apiserver.

**How to reproduce it (as minimally and precisely as possible)**:
`go get k8s.io/sample-apiserver`
`cd` to sample-apiserver
`export DOCKER_PREFIX=$your_dockerhub_username`
Run the following script to build:
```
#!/bin/bash

GOOS=linux GOARCH=amd64 go build
cp sample-apiserver artifacts/simple-image/kube-sample-apiserver
IMGREF=${DOCKER_PREFIX:-$LOGNAME}/kube-sample-apiserver:$(git rev-parse HEAD)
docker build -t $IMGREF ./artifacts/simple-image
docker push $IMGREF
```
Edit the image ref in the `rc.yaml` to match, and add `-v=5` to the apiserver's command line.
`kubectl apply -f artifacts/example`
Look in the wardle server's log for the complaints like those cited above.

**Anything else we need to know?**:
This problem is not new.  I have been seeing it in code derived from the sample apiserver *years* ago.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): Buildroot 2018.05
- Kernel (e.g. `uname -a`): Linux minikube 4.15.0 #1 SMP Fri Jan 18 22:39:33 UTC 2019 x86_64 GNU/Linux
- Install tools: minikube
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
this is likely the availability check:

https://github.com/kubernetes/kubernetes/blob/a4f2590bd8400ca43e2cf09882f493611a3ce289/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go#L238-L250

**Comment by MikeSpreitzer** [comment]
@liggitt : if I understand this code correctly, the wardle server always fails the availability check.  Does that mean the availability check is wrong, or the wardle server, or ...?  And, does this have anything to do with https://github.com/kubernetes/sample-apiserver/issues/12 ?

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/79895 to only check the discovery endpoint the server is required to serve

/close
