### ISSUE TITLE
Replace kubernetes/pkg/util/strings with k8s.io/utils/tree/master/strings

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#73385]
At some point, the code in https://github.com/kubernetes/kubernetes/tree/master/pkg/util/strings/ was moved to https://github.com/kubernetes/utils/tree/master/strings

However we have not started using the code in the kubernetes/utils library. We should switch over to the vendored library and delete the duplicate code in the main repo.

**Comment by danielqsj** [comment]
Fixed by #73455 
/close
