### ISSUE TITLE
Kubernetes does not expose metrics for PVCs with storageclass Ceph-fs

### ISSUE THREAD

**Issue by tiwalter** [kubernetes/kubernetes#73395]
**What happened**:
I get no metrics for the PVC, if i use PVCs with storageclass Ceph-fs. If i use storageclass Ceph-rbd, it works and e.g the metric **kubelet_volume_stats_capacity_bytes** shows metrics for this PVC.

**What you expected to happen**:
Kubernetes exposes metrics for PVCs with storageclass Ceph-fs (e.g. via metric name **kubelet_volume_stats_capacity_bytes**)

**How to reproduce it (as minimally and precisely as possible)**: 
- Create a PVC with storageclass Ceph-fs
- Deploy Prometheus and scrape Kubernetes metrics
- Look up the metric **kubelet_volume_stats_capacity_bytes** 

**Anything else we need to know?**:
- Prometheus v2.6.1 is used for monitoring Kubernetes

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4
- OS (e.g. from /etc/os-release):  Ubuntu 18.04.1 LTS (Bionic Beaver)
- Others: Prometheus v2.6.1 for monitoring

**Comment by jason-gideon** [comment]
I have the same issue. Is there any solution? please help me

**Comment by Lin-qu** [comment]
Hi @tiwalter I have the save issue, May I know how does it work?

**Comment by tiwalter** [comment]
Hi @Lin-qu sorry for the late reply. Unfortunately, i missed the notification. Is your issue still persistent?
