### ISSUE TITLE
Need headless service tests on Windows

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73416]
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

There isn't a test for this running on Windows nodes today. We need to create one that:
- Creates a headless service with multiple instances
- Creates another pod in the same namespace and check that DNS resolution returns A records for those pod IPs

/milestone v1.14
/sig windows

**Comment by bclau** [comment]
The test ``[sig-network] DNS should provide DNS for services  [Conformance]`` already tests this, This is the .yaml generated and used by the test: [1]. As you can see, the test creates a headless service (according to the documentation, it is ``dns-test-service``, which has the ClusterIP set to None), and checks the DNS resolution A record through TCP and UDP using dig.

[1] https://paste.ubuntu.com/p/TyKQcNryj8/

**Comment by PatrickLang** [comment]
I just moved it into the in progress column. @pengfeihu is looking at this

**Comment by xmudrii** [comment]
Hello,

I'm a bug triage shadow and I'd like to remind that code freeze is coming in 2 days (Thursday). :snowflake: :mountain_snow: Is it still planned for this issue to be fixed in 1.14?

**Comment by PatrickLang** [comment]
Thanks  @bclau for calling that out. The last few runs have passed that successfully. Here's an example.

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows/39

/close
