### ISSUE TITLE
Potential misjudgment in nodeAddressesChangeDetected of node_controller

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#73410]
**What happened**:
I was reading nodeAddressesChangeDetected of pkg/controller/cloud/node_controller.go .
```
        for i := range addressSet1 {
                addressMap1[addressSet1[i].Type] = addressSet1[i].Address
                addressMap2[addressSet2[i].Type] = addressSet2[i].Address
```
Suppose for the same type, addresses in addressSet1 are bb, followed by aa.
Addresses in addressSet2 are cc followed by aa.
The comparison in the next for loop would detect no change which is not true.

**What you expected to happen**:
We should distinguish the above difference in address values.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@kubernetes/sig-cloude-provider
/sig cloude-provider

**Comment by surajssd** [comment]
@tedyu can you provide steps to re-create this on real kubernetes cluster?

**Comment by tedyu** [comment]
As I stated above, this potential issue was found during code reading.
I haven't seen this in real cluster yet.
