### ISSUE TITLE
Tracking Issue - Conformance Coverage for Etcd

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#73424]
**What would you like to be added**:
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Why is this needed**:
Identify tests the tests general and pluggable behavior for persistence wrt etcd.

/area conformance

**Comment by brahmaroutu** [comment]
as indicated by @timothysc
There have been multiple proposals and even a PR to replace Etcd with other storage systems, and we've upgraded Etcd across major versions (from 2 to 3), so Apiserver behaviors that are dependent on Etcd (optimistic concurrency, watch, Event TTL) should be covered. SIG API Machinery should help with that. They did add some watch tests already.

**Comment by timothysc** [comment]
Coverage for this should be tested via the api-server to test key storage behaviors such as 
- Watch Behaviors 
- Storage Layer issues 

/assign @timothysc
