### ISSUE TITLE
Tracking Issue - Conformance Coverage for HostAliases

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#73426]
**What would you like to be added**:
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Why is this needed**:
Conformance coverage on HostAliases require more tests to be added.

/area conformance

**Comment by timothysc** [comment]
move to close, because we're going todo a field check on PodSpec.
