### ISSUE TITLE
Tracking Issue - Conformance Coverage for Scheduler

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#73422]
**What would you like to be added**:
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Why is this needed**:
This is to track conformance coverage to the scheduler functionality

area/conformance

**Comment by brahmaroutu** [comment]
area/conformance

**Comment by timothysc** [comment]
We're going to close this one in favor of podspec work.
