### ISSUE TITLE
Tracking Issue - Conformance Coverage for Kube-proxy

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#73423]
**What would you like to be added**:
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Why is this needed**:
This Issue is to improve conformance coverage for Kube-Proxy 

/area conformance

**Comment by timothysc** [comment]
closing, conformance shouldn't even know that kube-proxy exists.
