### ISSUE TITLE
Tracking Issue - Conformance Coverage for Shared Container Namespaces

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#73430]
**What would you like to be added**:
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Why is this needed**:
This is to improve conformance test coverage for Container Namespaces

/area conformance

**Comment by pontiyaraja** [comment]
@brahmaroutu is it Share Process Namespace between Containers in a Pod ?

**Comment by pontiyaraja** [comment]
> I think we should start with 'shareProcessNamespace' but there are 'HostIPC' and 'HostPID' if they make any sense.
> As per docs we need test cases for (https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/)
> 
> 1. Container without PID 1
> 2. Containers can see process from a shared container in a Pod
> 3. Containers sharing file system
> 
> @timothysc @tallclair Can you please let us know tests/scenarios that make sense to write e2e and promote to conformance?

@brahmaroutu the above test cases are covered in [security_context.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/security_context_test.go), few test cases are features and [shared process namespace between the containers](https://github.com/kubernetes/kubernetes/blob/5ab509b54bafe0f4faed00a1efe2d14b16856619/test/e2e_node/security_context_test.go#L74) test case marked as `[Alpha]`. But in v1.13 its beta.

**Comment by brahmaroutu** [comment]
@pontiyaraja security context tests should be for testing selinux and seccomp capabilities I believe.

**Comment by mgdevstack** [comment]
@pontiyaraja, Is there any other actionable item here.
e.g 
1) if PodShareProcessNamespace is promoted to beta in #66507, why don't we update e2e to use beta resources and tag them as [Beta]. Once it is GA in 1.15 release, we can think for Conformance Promotion.

**Comment by timothysc** [comment]
closing in preference to https://github.com/kubernetes/kubernetes/issues/76345
