### ISSUE TITLE
Fetch fluentd td agent securely

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#7345]
`toolbelt.treasuredata.com` doesn't serve over SSL but is used as the source of the fluentd td agent for ubuntu (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile#L24). We should find a source for the agent that can be fetched securely when building the fluentd elastic search docker image.

**Comment by roberthbailey** [comment]
Split off of #128.

**Comment by satnam6502** [comment]
Can we have a milestone for this? If v1.0 I shall look into it -- if post then we can deal with this later.

**Comment by satnam6502** [comment]
An alternative would be to use the Cloud Logging  td-agent and then add in the plug-in for Elasticsearch and then adjust the config appropriately. @a-robinson @mr-salty

**Comment by a-robinson** [comment]
Using the cloud logging td-agent SGTM. Easier to share it than to have two different versions of fluentd.

**Comment by satnam6502** [comment]
I would propose making this a post 1.0 requirement? Given that our current node level logging setup works I am rather reluctant to futz t around with it now.

**Comment by roberthbailey** [comment]
Fixed by #12942.
