### ISSUE TITLE
The names of the two child nodes are the same, resulting in confusion.

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/kubernetes#73453]
**What happened**:
When you have two children with exactly the same hostname, something unexpected happens when you execute the kubeadm join command

**What you expected to happen**:
kubectl get nodes returns the correct information

**How to reproduce it (as minimally and precisely as possible)**:
kubeadm init --kubernetes-version=v1.12.2/kubeadm init --kubernetes-version=v1.13.2
Perform a kubeadm join on two nodes with the same hostname

**Anything else we need to know?**:
I tried two versions, v1.12.0/v1.13.0, both of which were confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0/v1.13.0
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu18.04
- Kernel (e.g. `uname -a`): Linux ubuntutest 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by neolit123** [comment]
nodes with the same name are not supported.
https://kubernetes.io/docs/setup/independent/install-kubeadm/
> Unique hostname, MAC address, and product_uuid for every node. See here for more details.

/close

**Comment by xichengliudui** [comment]
@neolit123  I'm sorry to trouble you

**Comment by neolit123** [comment]
no problem at all! @xichengliudui
