### ISSUE TITLE
Need container lifecycle event tests

### ISSUE THREAD

**Issue by michmike** [kubernetes/kubernetes#73451]
We need to add Windows-specific tests to cover container lifecycle events

Test cases needed for postStart
Test cases needed for preStop

These need to run on Windows containers to test that functionality on windows

/sig windows
/milestone v1.14

**Comment by benmoss** [comment]
There are already two tests that cover this being run by the acs-engine tests: 

- [k8s.io] [sig-node] PreStop should call prestop when killing a pod [Conformance]
- [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly [NodeConformance] [Conformance]

/close
