### ISSUE TITLE
Support for building Windows container images

### ISSUE THREAD

**Issue by benmoss** [kubernetes/kubernetes#73475]
Following up with a Slack conversation between @spiffxp @ixdy and @yujuhong [here](https://kubernetes.slack.com/archives/C09QZ4DQB/p1548721080968800).

**What would you like to be added**:

The Windows versions of the test images should be available from the same repository as the Linux ones. For testing support for Windows we've so far been pushing alternate images to a [separate registry](https://hub.docker.com/u/e2eteam) and maintaining the Dockerfiles in a [separate repo](https://github.com/kubernetes-sigs/windows-testing).

Since the `image-util.sh` script already supports multi-arch manifests it should be relatively straightforward there, but the main difficulty will be reconciling the changes that have been made to the Dockerfiles and their source files themselves.

**Why is this needed**:

It will remove the need to supply an alternate image registry when running the test suites. It's also valuable for maintaining the veracity of the images as we look ahead to certifying Windows clusters.

**Comment by PatrickLang** [comment]
@benmoss 

Is this the process you had in mind?

1. Build and push to an existing registry for Windows-only images (work item: https://github.com/kubernetes-sigs/windows-testing/issues/3 )
2. Update `image-util.sh` to reference these and include them in the same multi-arch manifest when the Linux images are updated

**Comment by PatrickLang** [comment]
cc @adelina-t

**Comment by PatrickLang** [comment]
If we want to handle multiple Windows versions, then Docker EE-basic 18.09 is required. We're using that on Azure, but need to check on GCE.

**Comment by neolit123** [comment]
cc

**Comment by pjh** [comment]
> If we want to handle multiple Windows versions, then Docker EE-basic 18.09 is required. We're using that on Azure, but need to check on GCE.

This is fine for us, we're using Docker 18.09 by default for Windows containers on GCE.
