### ISSUE TITLE
Fetch coreos_production_qemu_image.img.bz2 securely

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#7347]
`alpha.release.core-os.net` doesn't have a valid SSL certificate (it looks like it's a GCS bucket since https://www.ssllabs.com/ssltest/analyze.html?d=alpha.release.core-os.net says that I should be using a `*.storage.googleapis.com` domain name). We should find a source for the image that can be fetch securely.

**Comment by roberthbailey** [comment]
Split off of #128. 

/cc @lhuard1A since I can't assign this to you directly.

**Comment by justinsb** [comment]
@sdminonne you made a (meaningful) change in libvirt_coreos a few months ago.  Does `cluster/libvirt-coreos/` still work?  Any idea on a better source?

**Comment by sdminonne** [comment]
@justinsb `cluster/libvirt-coreos` works (at least for my needs) . I use it everyday for dev and I'd like to keep it working. I was not aware of this issue. Having a look and let you know.

**Comment by sdminonne** [comment]
@roberthbailey I had a look at https://www.ssllabs.com/ssltest/analyze.html?d=alpha.release.core-os.net but I found no reference to `...googleapis...` maybe something changed since this issue is quite old. Could you check again and eventually share more details on the issue? Thanks in advance

**Comment by roberthbailey** [comment]
Back in mid-2015 I was looking for places where we were fetching resources dynamically during cluster creation and trying to make sure that the fetches were done over SSL (to prevent a malicious actor from being able to inject code into new clusters) -- see https://github.com/kubernetes/kubernetes/issues/128. 

The idea was to try and switch https://github.com/kubernetes/kubernetes/blob/master/cluster/libvirt-coreos/util.sh#L155 from `http://${COREOS_CHANNEL:-alpha}.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2` to `https://${COREOS_CHANNEL:-alpha}.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2`. 

If I run the wget command directly, it appears to work fine over SSL (and is actually way faster for me -- the http endpoint said it would take >3 hrs to download and the https endpoint took 12s).

**Comment by roberthbailey** [comment]
I've created https://github.com/kubernetes/kubernetes/pull/34646 to switch it to https
