### ISSUE TITLE
Node goes down with KubeletHasSufficientPID and pod is not rescheduled to other available nodes?

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#73470]
**What happened**:
I have a cluster deployed to AWS EKS with 3 to 4 nodes. One of the node goes down for no reason with KubeletHasSufficientPID and the StatefulSet pod replicas is violated in a sense that it does not reschedule pod in other available nodes. I change the podManagementPolicy to Parallel but it doesn't help. Any advice and insight is apprecated.
**What you expected to happen**:
StatefulSet replicas is hornoured and reschedule new pod to other available nodes.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shyamjvs** [comment]
This behaviour is intentional. See this comment ([xref](https://github.com/kubernetes/kubernetes/issues/54368#issuecomment-339378164) for more details):

```
This is by design. When a node goes "down", the master does not know whether it was a safe down (deliberate shutdown) or a network partition. If the master said "ok, the pod is deleted" then the pod could actually be running somewhere on the cluster, thus violating the guarantees of stateful sets only having one pod.

In your case, if you intend the node to be deleted, you must delete the node object. That will cause the master to understand that you wish the node to be gone, and delete the pods.
```

/close
