### ISSUE TITLE
Need Horizontal POD autoscaling tests

### ISSUE THREAD

**Issue by michmike** [kubernetes/kubernetes#73489]
We need to add Windows-specific tests to cover Horizontal POD autoscaling

Test cases needed for all types of metrics that autoscaling can cover (CPU, Memory, etc)

These need to run on Windows containers to test that functionality on windows

/sig windows
/milestone v1.14

**Comment by benmoss** [comment]
I started investigating whether we could get [these tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/horizontal_pod_autoscaling.go) to run, but ran into two issues:
- First, the version of the `resource-consumer` image in the e2eteam account is only tagged 1.3, and the test calls for 1.4. I retagged it and pushed it based on the code in the windows-testing repo
- The tests also depend on an image we haven't ported yet, `resource-consumer/controller:1.0`. I'll try to see how hard porting that is tomorrow.

**Comment by michmike** [comment]
thanks Ben!

**Comment by bclau** [comment]
@benmoss I think the bigger issue would be that we can't push repo_name/resource-consumer/controller:1.0 on dockerhub alongside the other images we ported, as it doesn't allow you to push images with slashes in them.

**Comment by benmoss** [comment]
relevant: https://github.com/kubernetes/kubernetes/pull/73659

**Comment by michmike** [comment]
> @benmoss I think the bigger issue would be that we can't push repo_name/resource-consumer/controller:1.0 on dockerhub alongside the other images we ported, as it doesn't allow you to push images with slashes in them.

can we push the images somewhere else that is supported? how can i help if there is red tape to doing this?

**Comment by benmoss** [comment]
We can push them to GCR or ACR for now. I'm sure I can get permission to host these under a Pivotal-sponsored account, or I'm sure MS folks can get permission from there.

**Comment by bclau** [comment]
I'm wondering if the kubernetes folks would agree to rename the image from ``resource-consumer/controller`` to ``resource-consumer-controller``. That would solve the issue. I don't really know why or what advantages were for naming the image ``resource-consumer/controller``.

**Comment by michmike** [comment]
@bclau  can you please add this image to your request for https://github.com/kubernetes/kubernetes/issues/74134 and ask that this image is pushed under gcr.io/google-samples or gcr.io/google-containers?

**Comment by timmycarr** [comment]
Hello,

I'm a bug triage shadow and I'd like to remind that code freeze is coming in 3 days (Friday, 8th March). Is it still planned for this issue to be fixed for 1.14?

**Comment by bclau** [comment]
Just an FYI, the image ``resouce-consumer/controller`` has officially been renamed to ``resource-consumer-controller``. This image has also been pushed to the ``e2eteam`` registry. We can proceed on this issue.

https://github.com/kubernetes/kubernetes/pull/75115

**Comment by benmoss** [comment]
The horizontal pod autoscaler tests from https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/horizontal_pod_autoscaling.go now pass against my cluster! We can add them to our various e2e runs and then mark this as closed

**Comment by michmike** [comment]
great news @benmoss and @bclau 
Claudio, would you be able to include these tests to our e2e runs? thanks!

**Comment by PatrickLang** [comment]
/milestone v1.16
we probably need another job to isolate slower-running tests like these. Successful runs are currently ~4.5 hrs, runs with some failures may take up to 7 due to retries.

**Comment by Pothulapati** [comment]
Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16? If not please re-tag the issue to the planned milestone.

**Comment by bclau** [comment]
The horizontal pod autoscaling tests has been included in https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master

**Comment by ttousai** [comment]
Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on Nov. 18. Is this issue still intended for 1.17?

**Comment by benmoss** [comment]
I'd say this is done now.

/close
