### ISSUE TITLE
Don't update the Pod object after each scheduling attempt by adding a timestamp to the scheduling queue

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#73485]
We recently added [a PR to put a timestamp on a Pod object](https://github.com/kubernetes/kubernetes/pull/72619) every time it is attempted by the scheduler. This change improves scheduler's fairness and gives pods that have been tried oldest a higher precedence over other pods with the same priority. However, this change could increase the number of pod updates and could raise the load of the API server in some scenarios. This is particularly problematic in clusters with a lot of unschedulable pods that remain unschedulable for a long time and getting attempted many times.
In fact, we don't need to keep this timestamp in the API object. This is needed only for the scheduler to keep track of the time that a pod is attempted. In other words, this timestamp can be kept in the scheduler's internal state only. We should add a timestamp to every pod in the scheduling queue. The timestamp will be the time that the pod is added to the queue. The scheduler should use this timestamp for sorting pods with the same priority. By doing this we will not update the API object after every scheduling attempt.

/kind bug
/sig scheduling

**Comment by denkensk** [comment]
I can help to do this. ^_^

**Comment by bsalamat** [comment]
/assign denkensk

Thank you!

**Comment by bsalamat** [comment]
@denkensk I cannot officially assign it to you since you are not a member yet, but I consider it assigned to you. You can start working on it.
