### ISSUE TITLE
Fetch debian packages securely

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#7348]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L295-L296 made me look at the `/etc/apt/sources.list` file and I noticed there and in our startup script that we are fetching all of our debian packages from http://gce_debian_mirror.storage.googleapis.com rather than https://gce_debian_mirror.storage.googleapis.com and http://security.debian.org rather than https://security.debian.org.

**Comment by roberthbailey** [comment]
Split off of #128.

**Comment by roberthbailey** [comment]
For GCE, we bake all of the packages we need into the container vm (and don't actually fetch them dynamically any longer).

**Comment by zmerlynn** [comment]
This is still a tiny issue if someone adds a new dep and we don't notice it. I keep meaning to spend an hour or two to write the package-differ test, but haven't gotten around to it.

**Comment by justinsb** [comment]
Not sure what was in the offending lines all those years ago @roberthbailey, but aren't debian packages signed?  http should be safe, and it sounds like we aren't fetching them anyway.  OK to close?

**Comment by zmerlynn** [comment]
SGTM
