### ISSUE TITLE
CRI: Include pod name and namespace in the CRI pod log directory

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#73503]
This has been previously discussed https://github.com/kubernetes/kubernetes/issues/58638#issuecomment-385126031, but we haven't got time to get to this.

Given that CRI runtimes (containerd, cri-o) are used by more and more people, it is better to make this CRI change earlier than later.

/cc @kubernetes/sig-node-feature-requests

**Comment by Random-Liu** [comment]
The proposed pod log directory path is `/var/log/pods/{POD_NAMESPACE}_{POD_NAME}_{POD_UID}`. The order makes it easier to do `ls /var/log/pods/{POD_NAMESPACE}*` or `ls /var/log/pods/{POD_NAMESPACE}_{POD_NAME}*`.

The biggest thing we should pay attention to for log path changing is backward compatibility. Although we never officially support in-place upgrade, we should still avoid breaking it.

We have the [`LogPath`](https://github.com/kubernetes/kubernetes/blob/4fec22b3e4da6034948fd684f60637171cb55561/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L899) field in `ContainerStatus`, and in many cases we can leverage that to avoid the backward compatibility issue. And we've been doing that already for [kubectl logs](https://github.com/kubernetes/kubernetes/blob/4fec22b3e4da6034948fd684f60637171cb55561/pkg/kubelet/kuberuntime/kuberuntime_container.go#L746) and [kubelet log manager](https://github.com/kubernetes/kubernetes/blob/4fec22b3e4da6034948fd684f60637171cb55561/pkg/kubelet/logs/container_log_manager.go#L199).

We should change some other places, such as the [`TerminationMessage`](https://github.com/kubernetes/kubernetes/blob/4fec22b3e4da6034948fd684f60637171cb55561/pkg/kubelet/kuberuntime/kuberuntime_container.go#L416).

However, this is not enough, because 1) sometimes we try to avoid `ContainerStatus` call for performance, e.g. [container log stats](https://github.com/kubernetes/kubernetes/blob/4fec22b3e4da6034948fd684f60637171cb55561/pkg/kubelet/stats/cri_stats_provider.go#L472); 2) sometimes we do need the pod log directory, e.g. when creating a container in an old pod sandbox started before upgrade.

One option is to introduce a `LogDirectory` field in `PodSandboxStatus`, but this will only work with new runtimes which support it, we can't start relying on it immediately.

Another option is to add some annotation from Kubelet side. We can add a `io.kubernetes.pod.cri.log.schema=1.14` annotation, and only start using the new pod directory path if the pod has `io.kubernetes.pod.cri.log.schema==1.14`, or else fall back to legacy log path.

Once 1.13 is deprecated, we can remove all the backward compatibility logic. In this way, we can easily update the pod/container log path in the future without breaking backward compatibility.

**Comment by xmudrii** [comment]
(tracking update - in progress #74441)

**Comment by xmudrii** [comment]
@Random-Liu Now that #74441 is merged should this issue be closed?

**Comment by Random-Liu** [comment]
Yeah, let's close this.
