### ISSUE TITLE
Push the zookeeper-installer 1.3 image to gcr.io

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#73507]
This PR https://github.com/kubernetes/kubernetes/pull/73194 solves execution issue in `gcr.io/kubernetes-e2e-test-images/pets/zookeeper-installer`.

Please help to push new image (version 1.3) to gcr.io.
Dockerfile is [here](https://github.com/danielqsj/kubernetes/blob/master/test/images/pets/zookeeper-installer/Dockerfile), Makefile is [here](https://github.com/danielqsj/kubernetes/blob/master/test/images/pets/zookeeper-installer/Makefile).

/cc @dims
/cc @thockin

/sig release
/sig testing

**Comment by danielqsj** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/73383

**Comment by johscheuer** [comment]
Any news when the image will be published?

**Comment by danielqsj** [comment]
hi @kubernetes/sig-testing , could someone help push a new image (version 1.3) to gcr.io?

**Comment by mkumatag** [comment]
@ixdy ^^^

**Comment by johscheuer** [comment]
I also noticed that the Redis image was missing `bash` as well I added a PR that fixes that: https://github.com/kubernetes/kubernetes/pull/74648

**Comment by listx** [comment]
Sorry about the long silence; I'll get on this later today.

**Comment by listx** [comment]
@ixdy I don't have access to push to gcr.io/kubernetes-e2e-test-images. Can you or someone give me access?

**Comment by listx** [comment]
Done. See https://pantheon.corp.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL/pets?gcrImageListsize=30

**Comment by danielqsj** [comment]
@listx @ixdy Thanks so much.
