### ISSUE TITLE
k8s 1.13.2, Unable to apply config file into kube-scheduler pod

### ISSUE THREAD

**Issue by tanksoga** [kubernetes/kubernetes#73505]
**What happened**:
I had k8s 1.13.2 cluster create (1 master + 2 work node), after deploy my containers, I found all pods is deployed to same work node. I google for a while and I found this article Scheduler Performance Tuning taking about new parameter "percentageOfNodesToScore" after 1.12 and default is set to 50. I want to change to 100

**What you expected to happen**:
I made a scheduler_extra.conf with following content
```
$ cat /etc/kubernetes/scheduler_extra.conf
apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
algorithmSource:
   provider: DefaultProvider
percentageOfNodesToScore: 100
```
And modify /etc/kubernetes/manifests/kube-scheduler.yaml as follow
```
.............
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --config=/etc/kubernetes/scheduler_extra.conf <<--- I add this line
    - --leader-elect=true
....................
....................
volumeMounts: <-- I change the following lines>
    - mountPath: /etc/kubernetes/
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/
      type: Directory
    name: kubeconfig
...............
```
However, after kube-scheduler pod be restart ( by kubelet automatically ), I go into kube-scheduler pod but /etc/kubernetes/scheduler_extra.conf didn't be mounted into pod so that after I issue kube-scheduler --write-config-to=temp.conf and cat temp.conf, percentageOfNodesToScore still are the defaulted value "50", not the value "100" I input in scheduler_extra.conf.

I use docker ps command to show the kube-scheduler pod startup command and found scheduler_extra.conf didn't be used 

```
$docker ps --format "{{.Names}} {{.Command}} {{.Status}}" --no-trunc | grep kube-scheduler
k8s_kube-scheduler_kube-scheduler-paymentkubermaster_kube-system_a7914e6386c7369adde3dcf67c27fed6_3 "kube-scheduler --address=127.0.0.1 --kubeconfig=/etc/kubernetes/scheduler.conf --leader-elect=true" Up 1 second
```

In the order word, it seems the --config parameter didn't be taken by kube-scheduler pod when it start up.

**How to reproduce it (as minimally and precisely as possible)**:
Use above description can be reproduced easily

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: VMs on our VMWare vShpere 6.5
- OS (e.g. from /etc/os-release):  Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Kernel (e.g. `uname -a`):  Linux paymentkubermaster 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm -init
- Others: ```
I use kubeadm -init to install container version k8s
$ docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
weaveworks/weave-npc                 2.5.1               789b7f496034        7 days ago          49.6MB
weaveworks/weave-kube                2.5.1               1f394ae9e226        7 days ago          148MB
k8s.gcr.io/kube-apiserver            v1.13.2             177db4b8e93a        2 weeks ago         181MB
k8s.gcr.io/kube-proxy                v1.13.2             01cfa56edcfc        2 weeks ago         80.3MB
k8s.gcr.io/kube-controller-manager   v1.13.2             b9027a78d94c        2 weeks ago         146MB
k8s.gcr.io/kube-scheduler            v1.13.2             3193be46e0b3        2 weeks ago         79.6MB
k8s.gcr.io/coredns                   1.2.6               f59dcacceff4        2 months ago        40MB
k8s.gcr.io/etcd                      3.2.24              3cab8e1b9802        4 months ago        220MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        13 months ago       742kB
```

/sig scheduling

**Comment by wgliang** [comment]
@tanksoga 
Looks like an issue of kubeadm. 
/area kubeadm

**Comment by tanksoga** [comment]
> 
> 
> @tanksoga
> Looks like an issue of kubeadm.
> /area kubeadm

I think it is

**Comment by neolit123** [comment]
> Looks like an issue of kubeadm.

i don't think so.
the user is applying custom modifications to the scheduler pod, and the pod at this point is managed by the kubelet.

if you find a kubeadm specific problem please file the issue in the kubernetes/kubeadm repo.
there is no way to pass percentageOfNodesToScore from kubeadm, but you can pass volumes.
read here about extra volumes: https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

/remove-area kubeadm

**Comment by tongchao199** [comment]
> **What happened**:
> I had k8s 1.13.2 cluster create (1 master + 2 work node), after deploy my containers, I found all pods is deployed to same work node. I google for a while and I found this article Scheduler Performance Tuning taking about new parameter "percentageOfNodesToScore" after 1.12 and default is set to 50. I want to change to 100
> 
> **What you expected to happen**:
> I made a scheduler_extra.conf with following content
> 
> ```
> $ cat /etc/kubernetes/scheduler_extra.conf
> apiVersion: kubescheduler.config.k8s.io/v1alpha1
> kind: KubeSchedulerConfiguration
> algorithmSource:
>    provider: DefaultProvider
> percentageOfNodesToScore: 100
> ```
> And modify /etc/kubernetes/manifests/kube-scheduler.yaml as follow
> 
> ```
> .............
> spec:
>   containers:
>   - command:
>     - kube-scheduler
>     - --address=127.0.0.1
>     - --kubeconfig=/etc/kubernetes/scheduler.conf
>     - --config=/etc/kubernetes/scheduler_extra.conf <<--- I add this line
>     - --leader-elect=true
> ....................
> ....................
> volumeMounts: <-- I change the following lines>
>     - mountPath: /etc/kubernetes/
>       name: kubeconfig
>       readOnly: true
>   hostNetwork: true
>   priorityClassName: system-cluster-critical
>   volumes:
>   - hostPath:
>       path: /etc/kubernetes/
>       type: Directory
>     name: kubeconfig
> ...............
> ```
> However, after kube-scheduler pod be restart ( by kubelet automatically ), I go into kube-scheduler pod but /etc/kubernetes/scheduler_extra.conf didn't be mounted into pod so that after I issue kube-scheduler --write-config-to=temp.conf and cat temp.conf, percentageOfNodesToScore still are the defaulted value "50", not the value "100" I input in scheduler_extra.conf.
> 
> I use docker ps command to show the kube-scheduler pod startup command and found scheduler_extra.conf didn't be used
> 
> ```
> $docker ps --format "{{.Names}} {{.Command}} {{.Status}}" --no-trunc | grep kube-scheduler
> k8s_kube-scheduler_kube-scheduler-paymentkubermaster_kube-system_a7914e6386c7369adde3dcf67c27fed6_3 "kube-scheduler --address=127.0.0.1 --kubeconfig=/etc/kubernetes/scheduler.conf --leader-elect=true" Up 1 second
> ```
> In the order word, it seems the --config parameter didn't be taken by kube-scheduler pod when it start up.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> Use above description can be reproduced easily
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`):
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
> 
> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
> ```
> * Cloud provider or hardware configuration: VMs on our VMWare vShpere 6.5
> * OS (e.g. from /etc/os-release):  Red Hat Enterprise Linux Server release 7.6 (Maipo)
> * Kernel (e.g. `uname -a`):  Linux paymentkubermaster 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> * Install tools: kubeadm -init
> * Others: ```
>   I use kubeadm -init to install container version k8s
>   $ docker images
>   REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
>   weaveworks/weave-npc                 2.5.1               789b7f496034        7 days ago          49.6MB
>   weaveworks/weave-kube                2.5.1               1f394ae9e226        7 days ago          148MB
>   k8s.gcr.io/kube-apiserver            v1.13.2             177db4b8e93a        2 weeks ago         181MB
>   k8s.gcr.io/kube-proxy                v1.13.2             01cfa56edcfc        2 weeks ago         80.3MB
>   k8s.gcr.io/kube-controller-manager   v1.13.2             b9027a78d94c        2 weeks ago         146MB
>   k8s.gcr.io/kube-scheduler            v1.13.2             3193be46e0b3        2 weeks ago         79.6MB
>   k8s.gcr.io/coredns                   1.2.6               f59dcacceff4        2 months ago        40MB
>   k8s.gcr.io/etcd                      3.2.24              3cab8e1b9802        4 months ago        220MB
>   k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        13 months ago       742kB
> 
> ```
> 
> /sig scheduling
> ```

kube-scheduler is [staic pods](https://kubernetes.io/docs/tasks/administer-cluster/static-pod/)，you should ensure where is kubelet --pod-manifest-path flag config。

 If your Kubernetes default scheduler is deployed as static pod, don't edit the yaml file inside /etc/kubernetes/manifest. You need to edit the yaml file outside the /etc/kubernetes/manifest directory.

And systemctl restart kubelet，recreate kube-scheduler

**Comment by Huang-Wei** [comment]
@tanksoga Firstly `percentageOfNodesToScore` is only effective in a large cluster (worker nodes number > 50 if I recall correctly).

Secondly, `--config` has been the official way to pass in scheduler parameters since 1.11.

But the tip here is: if you want to stick with "deprecated" flags, you're fine; but if you want to use `--config`, try to move all "deprecated" flags into the Config yaml. In terms of your case, you can:

1. (optional) remove `--kubeconfig` - which is a deprecated flag
2. provide a Config yaml to `--config`
    ```yaml
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    percentageOfNodesToScore: 100
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf
    ```

**Comment by Huang-Wei** [comment]
cc/ @bsalamat @misterikkit I saw a couple of issues asking for scheduler configuration as we marked a lot of flags as deprecated, but we don't document usage of `KubeSchedulerConfiguration` well.

In addition to documentation, do you think we should add some exceptions for deprecated flags, for example `--kubeconfig`, so that they can mix in if the field is not provided in `KubeSchedulerConfiguration` (via `--config`)?

https://github.com/kubernetes/kubernetes/blob/559b11410ee51998316e3e80d864886d88314607/cmd/kube-scheduler/app/options/options.go#L161-L173

Current exceptions on deprecated flags are `--address` and `--port`:

https://github.com/kubernetes/kubernetes/blob/559b11410ee51998316e3e80d864886d88314607/cmd/kube-scheduler/app/options/options.go#L173-L187
