### ISSUE TITLE
How to set the cpu, memory size of K8s master node?

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#73502]
For example, if 50 nodes K8s cluster, using 3 master nodes, how large is the cpu, memory of master node? if 200 node K8s cluster, using 7 master nodes, master node cpu, memory is appropriate?

/sig node
@Dawn Chen

**Comment by D-PENG** [comment]
The configuration of master node has little relationship with the cluster size, so the master node can not do pod scheduling.
