### ISSUE TITLE
unassigned HOST

### ISSUE THREAD

**Issue by wgq91here** [kubernetes/kubernetes#7350]
<pre>
[root@localhost ~]# kubectl get pods
POD                              IP            CONTAINER(S)    IMAGE(S)        HOST                              LABELS                          STATUS    CREATED
apache-master-controller-8zyrs   172.17.0.5    apache-master   fedora/apache   master-6-122-vhost/192.168.99.1   app=apache,name=apache-master   Running   14 minutes
apache-master-controller-pmno3   172.17.0.5    apache-master   fedora/apache   c1-6-123-vhost/192.168.99.2       app=apache,name=apache-master   Running   14 minutes
nginx-master-controller-9rn68                  nginx-master    nginx:1.7.12    <\<b>unassigned</b>\>                      app=nginx,name=nginx-master     Pending   4 minutes
nginx-master-controller-nu9dk    172.17.0.14   nginx-master    nginx:1.7.12    c2-6-124-vhost/192.168.99.3       app=nginx,name=nginx-master     Running   4 minutes
[root@localhost ~]# kubectl get minions
NAME                 LABELS    STATUS
c1-6-123-vhost       <none>    Ready
c2-6-124-vhost       <none>    Ready
master-6-122-vhost   <none>    Ready
</pre>

what is meaning?

**Comment by wgq91here** [comment]
Sorry. May be i wrong. Contains used same port.

**Comment by wgq91here** [comment]
<pre>
[root@localhost ~]# kubectl get pods,service,rc
POD                              IP           CONTAINER(S)    IMAGE(S)        HOST                              LABELS                          STATUS    CREATED
apache-master-controller-nqdqv   172.17.0.6   apache-master   fedora/apache   c1-6-123-vhost/192.168.99.2       app=apache,name=apache-master   Running   5 hours
apache-master-controller-t2h4b   172.17.0.6   apache-master   fedora/apache   master-6-122-vhost/192.168.99.1   app=apache,name=apache-master   Running   5 hours
nginx-master-controller-mt3ie    172.17.0.3   nginx-master    nginx:1.7.12    c2-6-124-vhost/192.168.99.3       app=nginx,name=nginx-master     Running   17 minutes
nginx-master-controller-yf3fc    172.17.0.9   nginx-master    nginx:1.7.12    master-6-122-vhost/192.168.99.1   app=nginx,name=nginx-master     Running   17 minutes
NAME            LABELS                                    SELECTOR     IP             PORT(S)
apache-apps     <none>                                    app=apache   10.254.0.179   8099/TCP
kubernetes      component=apiserver,provider=kubernetes   <none>       10.254.0.2     443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes   <none>       10.254.0.1     80/TCP
nginx-apps      <none>                                    app=nginx    10.254.0.99    8098/TCP
CONTROLLER                 CONTAINER(S)    IMAGE(S)        SELECTOR             REPLICAS
apache-master-controller   apache-master   fedora/apache   name=apache-master   2
nginx-master-controller    nginx-master    nginx:1.7.12    name=nginx-master    2
</pre>

Visit http://xxx/api/v1beta3/proxy/namespaces/default/services/apache-apps/ is right, but http://xxx:8091/api/v1beta3/proxy/namespaces/default/services/nginx-apps/ , it shows me 

<pre>
Error: 'dial tcp 172.17.0.3:80: no route to host'
Trying to reach: 'http://172.17.0.3:80/'
</pre>

**Comment by a-robinson** [comment]
Can you talk to the pod directly on http://172.17.0.3:80?

If not, can you give more detail about where the cluster is running and how you set it up? Kubernetes networking can vary quite a bit in different environments.

**Comment by wgq91here** [comment]
I tried to add bridge by brctl.

And docker -b=dockerkb0 (use brctl created it)

It is ..
<pre>
Error: 'dial tcp 172.17.0.1:80: i/o timeout'
Trying to reach: 'http://172.17.0.1:80/'
</pre>

Detail config is too much.

**Comment by wgq91here** [comment]
<pre>
[root@localhost ~]# kubectl get minions
NAME             LABELS    STATUS
c1-6-123-vhost   <none>    Ready
c2-6-124-vhost   <none>    Ready
[root@localhost ~]# ip route
default via 10.168.6.254 dev ens32  proto static  metric 1024 
10.168.6.0/24 dev ens32  proto kernel  scope link  src 10.168.6.122 
172.17.0.0/16 dev ens33  proto kernel  scope link  src 172.17.42.1 
192.168.99.0/24 dev ens32  proto kernel  scope link  src 192.168.99.1

[root@localhost ~]# kubectl get pods,services
POD                              IP           CONTAINER(S)    IMAGE(S)        HOST                          LABELS                          STATUS    CREATED
apache-master-controller-biqyb   172.17.0.1   apache-master   fedora/apache   c2-6-124-vhost/192.168.99.3   app=apache,name=apache-master   Running   23 minutes
apache-master-controller-x6uve   172.17.0.2   apache-master   fedora/apache   c1-6-123-vhost/192.168.99.2   app=apache,name=apache-master   Running   23 minutes
</pre>

On c1-6-123-vhost, curl 172.17.0.2 , it is fine. Show me `Apache`.
But on master, ping 172.17.0.2,show me `timeout`.

**Comment by goltermann** [comment]
We’re going through support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
