### ISSUE TITLE
namespaces "default" is forbidden

### ISSUE THREAD

**Issue by gejiwei** [kubernetes/kubernetes#73510]
**I deployed the k8s cluster with two nodes, installed the helm tool and rook-ceph, and reported the following errors when installing sitewhere**

Error: release sitewhere failed: namespaces "default" is forbidden: User "system:" in API group "" in the namespace "default"
![image](https://user-images.githubusercontent.com/39801390/51960878-c24c0600-2495-11e9-8e11-afb6b99a755f.png)
![image](https://user-images.githubusercontent.com/39801390/51960880-c5df8d00-2495-11e9-88e8-a52bb8336aa2.png)

What is this mistake, please? Thank you.

**Comment by liggitt** [comment]
typically that means you need to grant permissions to the user making the API calls. Can you provide the full error message you are seeing?
