### ISSUE TITLE
Reading apiserver latency metric doesn't works in tests

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#73519]
**What happened**:
Apiserver latency metric summary displays zeros instead on actual values.

**What you expected to happen**:
Summary should displays actual values.

**How to reproduce it (as minimally and precisely as possible)**:
Running performance test.

**Comment by krzysied** [comment]
This issue was introduce in https://github.com/kubernetes/kubernetes/commit/24643fd1163857a507e40f4bceb303c5b44d2d8f . There is problem with reading "apiserver_request_latency_seconds_summary". This metric doesn't exist.

**Comment by krzysied** [comment]
- [ ] Reverting metric to deprecated one (apiserver_request_latencies_summary).
Old metric is still available, This will allow performance tests to work properly.
This is important due to k8s SLI being based on this metric.
- [ ] Implement new version of reading metric and verifying SLI.

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by krzysied** [comment]
@spiffxp The current status of this issue is that this is somehow fixed - it's working, the tests are passing, however metric we are using is mark as deprecated. We are introducing changes to testing framework (clusterlaoder2) so it will be using different metric.
IMHO, It's not a problem (or blocker) for 1.14.

**Comment by wojtek-t** [comment]
@spiffxp - it's not 1.14 - it's not breaking nor blocking anything.

**Comment by wojtek-t** [comment]
We promissed to finish that in 1.16 to allow removing that metric.
So we should prioritize finishing that.

/assign @krzysied 
/assign @oxddr

**Comment by wojtek-t** [comment]
@mm4tt - FYI

**Comment by mm4tt** [comment]
This happens as a part of https://github.com/kubernetes/perf-tests/issues/498

**Comment by mm4tt** [comment]
I think this got fixed via https://github.com/kubernetes/perf-tests/pull/915
/close

**Comment by mm4tt** [comment]
/title Perf-tests shouldn't use deprecated apiserver_request_latency_seconds_summary metric

**Comment by mm4tt** [comment]
/retitle Perf-tests shouldn't use deprecated apiserver_request_latency_seconds_summary metric
