### ISSUE TITLE
encryption provider "aescbc" is vulnerable to a padding oracle attack and should be deprecated

### ISSUE THREAD

**Issue by xformerfhs** [kubernetes/kubernetes#73514]
While working with Kubernetes v1.13.2 and examining the way encrypted secrets are stored in etcd I noticed that the recommended encryption provider “aescbc” is susceptible to a [padding oracle attack](https://en.wikipedia.org/wiki/Padding_oracle_attack "padding oracle attack"). While the attack is not really feasible and there are probably attacks that are much easier to execute it is nonetheless a security vulnerability and I think it would be a good idea not to recommend an encryption method that has this vulnerability, so others will not perceive it as recommended by Kubernetes.

   The encryption provider “aescbc” uses the AES encryption algorithm in [CBC](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#CBC "CBC") mode with [PKCS#7](https://tools.ietf.org/html/rfc2315 "PKCS#7") padding to store the encrypted data. Because it does not use an integrity check this combination is susceptible to a padding oracle attack. A padding oracle makes it possible to retrieve the clear text of the encrypted data without knowing the key and without even knowing the encryption algorithm. It takes advantage of the fact that the attacker is able to control the encrypted data and that the encrypted data are used in CBC mode to prepare the next cipher block for decryption. It only works when the software that manages the data replies with an “invalid padding” error when the padding is wrong and no error when the padding is correct. This is the way how Kubernetes’ provider works.

   The source file ``aes.go`` contains the following lines of code in the function ``(t *cbc) TransformFromStorage``:

```go
for i := 0; i < paddingSize; i++ { 
   if result[size+i] != c { 
      return nil, false, errInvalidPKCS7Padding 
   } 
}
```
   I.e, there is an error message that distinguishes a padding error from other errors.

   An attacker could now do the following:

1. Find out where the data resides in etcd’s database. This is easy as the data is prefixed by the string ``k8s:enc:aescbc``. This, in turn is prefixed by the length of the following data, which has the following format: ``k8s:enc:aescbc:v1:[keyName]:[InitializationVector:8Bytes][EncryptedData]``.
2. The attacker now shuts down the API server, changes the last byte of the next-to-last block of  ``[EncryptedData]`` to ``[LastByteOfNext-to-lastBlock] XOR [GuessedClearByteOfLastByteOfLastBlock] XOR  0x01``.
3. Then he starts the API server, waits until the secret is accessed and watches the log file for the padding error message.
4. If there is a padding error message the guess was wrong and he starts step 2 again with the next guessed clear byte
5. If there was no padding error message the guessed clear byte was correct and step 2 is started again this time with the guessed next to last byte of the last block and so on working backwards to the first byte of the block and then the same through the other blocks.

   An attacker would have to repeat this procedure on the average ([PasswordLength] + 12 + 4) * 128 times. For an 8 character secret that yields 3.072 times on the average and 6.144 times at the maximum. Stopping and starting the API server several thousand times in a row is quite cumbersome and probably sure to attract attention, so this is not quite a feasible attack. Also, if the attacker is able to manipulate the bytes of etcd’s database he will probably also be able to read the encryption configuration data with the keys directly. But, nonetheless it is a possible attack.

   The main reason why I want to bring this to your attention is that Kubernetes is a role model for other programmers and if you use this vulnerable encryption method, others will follow. So, in order to strengthen security as a whole I would be glad if you would deprecate the use of “aescbc” and instead use one of the following alternatives:

* Use ``secretbox`` or ``aesgcm``. They are much more secure than ``aescbc`` and not susceptible to a padding oracle attack
* Add integrity checking to ``aescbc`` by adding a [HMAC](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code "HMAC") in [encrypt-then-MAC-mode](https://en.wikipedia.org/wiki/Encrypt-then-MAC#Encrypt-and-MAC_(E&M) "encrypt-then-MAC") to ``aescbc`` so that there will never be a padding error as the manipulation of bytes would then generate an error before padding is checked.
* Use [Arbitrary Tail Byte padding](https://eprint.iacr.org/2003/098.pdf "Arbitrary Tail Byte padding") or no padding at all with a length prefix.
* Use AES in counter mode and not CBC.

I.e. use any other combination than CBC and PKCS#7 padding, as this combination is really badly insecure.

As I said, this attack is not really feasible and there are much easier ways to compromise the server when one has already access to etcd's storage. I just think that Kubernetes should not endorse an algorithm combination that is essentially broken.

**Comment by smarterclayton** [comment]
This was considered during the design - I believe the end argument was:

If you can perform this attack (change disk contents) you’re root on the master which means you can, for instance, change etcd to run your pod as root on every node in the cluster, create a role that gives you cluster admin and the right to view every secret, or tell the kubelet to load any PV in your account that you have access to.

So it’s definitely an attack, it’s just equivalent to a more serious attack.

Aesgcm was eliminated as a default recommendation because of vector reuse (we should never recommend it for high write rare clusters).  I’ll have to look at the KEP again because discussed the other options as well.

**Comment by smarterclayton** [comment]
I recall us discussing and eliminating counter mode because of something.  Secret box was reasonably new at the time and there was a concern about endorsing it.

I’d probably prefer to fix the padding issue given the relative history of aes cbc

**Comment by xformerfhs** [comment]
I think it would be a good idea to always use integrity checks when using encryption. There have been a lot of attacks recently that manipulate the ciphertext. All of these attacks can no longer be performed when there is integrity checking in place. "secretbox" has integrity checking, "aesgcm" has and I think "aescbc" should be modified to use a HMAC in encrypt-then-MAC mode. Really, never use encryption without a MAC.

**Comment by immutableT** [comment]
CBC mode is also [hard coded](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go#L312) for use by Envelope Encryption, where a new DEK is generated per secret - making the collision attacks against an IV not relevant.

Changing default to GCM is a good choice for Envelope Encryption (even for reasons outside the scope of the padding oracle attack).  However, this raises the question of how to perform upgrades. The difficulty stems from the fact that there is no metadata on the encrypted record, so we would not know what encryption algorithm was used to perform re-wrapping. I think we would need to address this issue first. I have some ideas around this, I will create a separate issue.

**Comment by smarterclayton** [comment]
Default to GCM isn’t feasible unless we address IV reuse.

**Comment by xformerfhs** [comment]
See [Kubernetes Security Audit](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf), finding ID TOB-K8S-029 and appendix H.
