### ISSUE TITLE
Unmount device failure in kubelet when there is IO error

### ISSUE THREAD

**Issue by shilpamayanna** [kubernetes/kubernetes#73513]
**What happened**:
Unmount volume fails in kubelet when volume with XFS filesystem is shutdown due to IO error. This causes pod to be stuck in Terminating state forever.

**What you expected to happen**:
Unmount volume should succeed

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with  ISCSI/network mounted volume and disconnect/de-provision ISCSI target.
Delete pod

**Anything else we need to know?**:
XFS shuts down the filesystem due to I/O errors. Kubelet issues "stat" call to check if the mount point exists. Stat calls fail with EIO and Kubelet never unmounts the volume.
Issue was fixed with #67097. 
Fix for #68759 has introduced this issue again.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.3
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Centos 7.4
- Kernel (e.g. `uname -a`): 
Linux appserv40 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Manual
- Others:

**Comment by shilpamayanna** [comment]
@davidz627 Fix for #68759 has exposed the kubelet unmount issue again. GetMountRefs is invoking stat call to check if the path exists. This call would fail with I/O error when XFS shutdown.

**Comment by davidz627** [comment]
Hi @shilpamayanna, I understand the error and can submit a patch to fix this. However, I'm not really sure how to reproduce it for testing. Do you have some minimal steps to repro the error?

**Comment by shilpamayanna** [comment]
@davidz627 , I tried the experiment with remote volume. This could be reproduced with iSCSI volume.
