### ISSUE TITLE
send pod OOM events 

### ISSUE THREAD

**Issue by knightXun** [kubernetes/kubernetes#73515]
kubelet has oomwatcher which watch oom events from docker. I notice such oom has container names.For kubernetes, every pod has its special format name: for example `k8s_fluentd-kafka_fluentd-gqnrc_kube-system_2841dd35-22d8-11e9-b0af-0cc47a70d098_0` contains namespace , 'k8s' , podname, containername. So we can add a pod oom event in oomwatcher.
this is A little change, and it will bring very helpful information.
If need any help, I can send a pr for this.

**Comment by gaorong** [comment]
I'd like to work for this.
/assign

**Comment by gaorong** [comment]
related issue: #69676

**Comment by gaorong** [comment]
After diving into this issue, I found it's more complicated than I expected, someone had a try on this, see [this PR](https://github.com/kubernetes/kubernetes/pull/45682), there may be such a scenario which a big cluster has many always failed container and try to restart,  then there will be many spam event messages, this will be a serious problem, we should take more time to reconsider this problem and stop our step on this until someday we have a more perfect solution, even though I want this feature very much.
