### ISSUE TITLE
Creating selectors is expensive in EndpointsController

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#73527]
When profiling scalability tests at large scale, it appears that the function ``` SelectorFromValidatedSet``` can consume even 10% of cpu.
In the profiles it's coming purely from the GetPodServices in EndpointsController.

The reason for that is for every single call of GetPodServices:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L170
for every single service in that namespace we build the selector from scratch:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/listers/core/v1/service_expansion.go#L49

Even though a single such operation is not very expensive, the amount of that is resulting in significant percentage of overall cpu usage.

Longer-term solution is to do exactly what was done e.g. for ReplicaSet:
https://github.com/kubernetes/api/blob/master/apps/v1/types.go#L723
 - use appropriate type for the selector once we create v2 Service API.

That would mean that store-in-memory services would have the selector already created, so it would eliminate that completely.

I'm wondering if there is something we can do here more short-term.

@kubernetes/sig-network-misc @freehan 
@kubernetes/sig-scalability-misc

**Comment by freehan** [comment]
IIUC, It sounds like a simple short-term fix can be adding an in-memory cache of selector per service. That would avoid recreating the selector every time. This would be a good PR for new contributor.

**Comment by wojtek-t** [comment]
> IIUC, It sounds like a simple short-term fix can be adding an in-memory cache of selector per service. That would avoid recreating the selector every time.

Yeah probably. Though it obviously complicates the code, so my main goal was to ensure that the new API will not have this problem.

**Comment by yashbhutwala** [comment]
@freehan @wojtek-t I would like to work on this!  As a first time contributor, I would appreciate some help.

**Comment by wojtek-t** [comment]
@yashbhutwala - nice to meet you.
From my comment above it may not be clear, but I'm not 100% convinced that it's a good first task.

But to describe in more details:
- on every add/update/delete Pod action, endpointsController is calling getPodMemberships which call GetPodServices:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/listers/core/v1/service_expansion.go#L36
- this internally creates a selector: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L871
- that building a selector (allocations + sorting mostly) is becoming expensive if called that frequently 

What @freehan is suggesting that, we may want to cache "service->selector" mapping inside endpoints controller and use that instead of recomputing that every single time.

I'm a bit worried that it may complicate the code, but I think I may be too pesimistic here. So it's probably worth trying.

So what you would need to do is:
- add this mapping service->selector in endpoints controller
- add logic that is keeping this mapping up-to-date
- instead of using GetPodServices(), we will be "listing all services from that namespace" and then filtering that ourservles
Shouldn't be that much work...

**Comment by yashbhutwala** [comment]
Thanks @wojtek-t for laying out an outline for me!  I'll shoot my best shot, and put up a PR, perhaps you can guide it along

**Comment by shinytang6** [comment]
Hey @yashbhutwala , what's the status of this issue? Still work on that?

**Comment by yashbhutwala** [comment]
@shinytang6 @wojtek-t @freehan I made a PR here: https://github.com/kubernetes/kubernetes/pull/75965.  Review/feedback/suggestions appreciated! :)

**Comment by tedyu** [comment]
@wojtek-t 
SelectorFromValidatedSet calls sort. However, the goal for creating the selector is for calling selector.Matches where the sorting can be skipped.
```
		selector := labels.Set(service.Spec.Selector).AsSelectorPreValidated()
```
How about passing a flag to AsSelectorPreValidated() which skips the sorting step ?

**Comment by wojtek-t** [comment]
> How about passing a flag to AsSelectorPreValidated() which skips the sorting step ?

AsSelectorPreValidated() is already a bit of a hack by iself (I know I'm the one who added it). And I'm bit reluctant of making it even more strange looking...

**Comment by tedyu** [comment]
Can SelectorFromValidatedSet skip calling sort ?
I would think that the selectors have equal weight.

**Comment by wojtek-t** [comment]
> Can SelectorFromValidatedSet skip calling sort ?

It can't - it would e.g. break the assumption that you can compare them.
Or will be printed randomly when you print them.
The potential drawbacks are larger than the gain from it (i.e. majority of selectors are fairly small and memory allocations/gc connected to building selector are usually more expensive the this sort).

**Comment by gongguan** [comment]
> * instead of using GetPodServices(), we will be "listing all services from that namespace" and then filtering that ourservles

@wojtek-t seems selector-cache solution has to rewrite GetPodServices function, is it feasible to change so many code?

**Comment by wojtek-t** [comment]
Not necessary - see https://github.com/kubernetes/kubernetes/issues/73527

**Comment by tedyu** [comment]
@wojtek-t 
Did you mean a different issue number ?
The above issue number is for this issue.

**Comment by wojtek-t** [comment]
I meant https://github.com/kubernetes/kubernetes/pull/75965

**Comment by gongguan** [comment]
> I meant #75965

ok, seems no need for me to implement the selector-cache

**Comment by sarajmunjal** [comment]
@wojtek-t I'd like to work on this as a first issue if you don't mind. Should we iterate on #75965 or try afresh?

**Comment by gongguan** [comment]
@wojtek-t  One concern about service selector cache: what if service's selector updated?
By the way, does the same problem exist in endpointslice controller?

**Comment by gongguan** [comment]
@wojtek-t Excuse me, one concern about the service selector: should cache updated while service selector changed?

**Comment by wojtek-t** [comment]
> @wojtek-t Excuse me, I have one concern about the service selector: should cache updated while service selector changed?

yes
