### ISSUE TITLE
Pods sit in ContainerCreating for a long time in presence of a large number of ServiceAccount imagePullSecrets

### ISSUE THREAD

**Issue by alanjcastonguay** [kubernetes/kubernetes#73541]
**What happened**:

On AKS, I edited the "default" ServiceAccount in 11 namespaces to add `imagePullSecrets[]`, and erroneously listed the same `type=kubernetes.io/dockerconfigjson` secret 545 times. That bug was a provisioner trying to workaround #72475 but not being idempotent. My fault.

I observed in this state that Pods in those namespaces took 4-60 minutes to start, most of that time spent in ContainerCreating state.

```
registry-b7bc48969-fgbxk            1/1       Running             0          8m        10.244.4.241   aks-nodepool1-22789428-9    <none>
registry-b7bc48969-jlhr4            0/1       ContainerCreating   0          8m        <none>         aks-nodepool1-22789428-8    <none>
```

The Pod above did eventually start Running. `kubectl -n tenant-demo describe pod registry-b7bc48969-jlhr4` shows a 13 minute gap in time. From docker's perspective, the container was created at the same time the pod lifecycle Created/Started events appear.

```
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  47m   default-scheduler                  Successfully assigned tenant-demo/registry-b7bc48969-jlhr4 to aks-nodepool1-22789428-8
  Normal  Pulling    34m   kubelet, aks-nodepool1-22789428-8  pulling image "registry:release-master-2019-01-28.725"
  Normal  Pulled     34m   kubelet, aks-nodepool1-22789428-8  Successfully pulled image "registry:release-master-2019-01-28.725"
  Normal  Created    34m   kubelet, aks-nodepool1-22789428-8  Created container
  Normal  Started    34m   kubelet, aks-nodepool1-22789428-8  Started container
```
```
sudo docker ps | grep registry-b7bc48969-jlhr4
2fcb593a088c        registry   "node src --log json"    33 minutes ago      Up 33 minutes                           k8s_registry_registry-b7bc48969-jlhr4_tenant-demo_146d9319-2324-11e9-940e-0af3429e1259_0
20a889c1ac76        k8s.gcr.io/pause-amd64:3.1              "/pause"                 34 minutes ago      Up 34 minutes                           k8s_POD_registry-b7bc48969-jlhr4_tenant-demo_146d9319-2324-11e9-940e-0af3429e1259_0
```

kubelet logs from the node also reflected that 13 minute gap; there's a period where no events were produced mentioning this pod.

```
Jan 28 17:42:28 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:42:28.124844   28057 kubelet.go:1837] SyncLoop (ADD, "api"): "registry-b7bc48969-jlhr4_tenant-demo(146d9319-2324-11e9-940e-0af3429e1259)"
Jan 28 17:42:28 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:42:28.196941   28057 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-wnq2m" (UniqueName: "kubernetes.io/secret/146d9319-2324-11e9-940e-0af3429e1259-default-token-wnq2m") pod "registry-b7bc48969-jlhr4" (UID: "146d9319-2324-11e9-940e-0af3429e1259")
Jan 28 17:42:28 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:42:28.297238   28057 reconciler.go:252] operationExecutor.MountVolume started for volume "default-token-wnq2m" (UniqueName: "kubernetes.io/secret/146d9319-2324-11e9-940e-0af3429e1259-default-token-wnq2m") pod "registry-b7bc48969-jlhr4" (UID: "146d9319-2324-11e9-940e-0af3429e1259")
Jan 28 17:42:29 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:42:29.355810   28057 operation_generator.go:558] MountVolume.SetUp succeeded for volume "default-token-wnq2m" (UniqueName: "kubernetes.io/secret/146d9319-2324-11e9-940e-0af3429e1259-default-token-wnq2m") pod "registry-b7bc48969-jlhr4" (UID: "146d9319-2324-11e9-940e-0af3429e1259")
-13-minutes-
Jan 28 17:55:28 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:55:28.147031   28057 kuberuntime_manager.go:385] No sandbox for pod "registry-b7bc48969-jlhr4_tenant-demo(146d9319-2324-11e9-940e-0af3429e1259)" can be found. Need to start a new one
Jan 28 17:55:28 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:55:28.839349   28057 kubelet.go:1882] SyncLoop (PLEG): "registry-b7bc48969-jlhr4_tenant-demo(146d9319-2324-11e9-940e-0af3429e1259)", event: &pleg.PodLifecycleEvent{ID:"146d9319-2324-11e9-940e-0af3429e1259", Type:"ContainerDied", Data:"20a889c1ac764e1fb1b220f896cdca2d16ed2fedfd2775a258798900ca618c86"}
Jan 28 17:55:29 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:55:29.853715   28057 kubelet.go:1882] SyncLoop (PLEG): "registry-b7bc48969-jlhr4_tenant-demo(146d9319-2324-11e9-940e-0af3429e1259)", event: &pleg.PodLifecycleEvent{ID:"146d9319-2324-11e9-940e-0af3429e1259", Type:"ContainerStarted", Data:"20a889c1ac764e1fb1b220f896cdca2d16ed2fedfd2775a258798900ca618c86"}
Jan 28 17:55:30 aks-nodepool1-22789428-8 kubelet[28057]: I0128 17:55:30.872748   28057 kubelet.go:1882] SyncLoop (PLEG): "registry-b7bc48969-jlhr4_tenant-demo(146d9319-2324-11e9-940e-0af3429e1259)", event: &pleg.PodLifecycleEvent{ID:"146d9319-2324-11e9-940e-0af3429e1259", Type:"ContainerStarted", Data:"2fcb593a088c43c2ee6e8d1e6759265da281f41c60033f7957c6787c14c7bed5"}
```

This delay was observed for pods with ~1GB images on the private registry (ACR) in that secret, and for  ~4MB alpine images from the public docker registry. I don't think image size or authentication mattered here. There did not appear to be any memory/cpu/disk pressure on the nodes.

**What you expected to happen**:

The quantity of an ServiceAccount's imagePullSecrets listed to have no (or less) impact on the start time of a pod.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a new AKS 1-node cluster with v1.11.5 on Standard DS2 v2 (2 vcpus, 7 GB memory), standard networking, RBAC on. No ACR required.

https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-sh does the following:

* Create a secret `kubectl create secret docker-registry acr-auth --docker-server example.azurecr.io --docker-username example --docker-password test --docker-email me@example.com`
* Patch the service account `kubectl patch sa default -p '{"imagePullSecrets":[{"name": "acr-auth"}]}' --type=merge`
* Launch a pod `time kubectl run -it --rm --image=alpine:3.6 --quiet=true --restart=Never alpine36 -- echo up` - observe <10s startup (note the image should cache)
* Append to the service account 600 times `kubectl patch sa default --type='json' -p='[{"op": "add", "path": "/imagePullSecrets/-", "value": {"name": "acr-auth"}}]' > /dev/null`
* Launch a pod `time kubectl run -it --rm --image=alpine:3.6 --quiet=true --restart=Never alpine36 -- echo up` - observe ~128s startup.

Observe a linear relationship between the number of secrets listed and the number of seconds it takes to launch _one_ alpine:3.6 pod. See https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-csv graphed: ![reproduction.png](https://user-images.githubusercontent.com/1447600/52006969-6ab09900-249b-11e9-8578-e8d33b8fd7f2.png).

But when I first experienced the symptoms I had ~100 pods launching at around the same time. They appeared to slowly drain, with a wide range (4-60 minutes) of delays. When many pods were started (and in ContainerCreating) at the same time, I _think_ their delays were cumulative; where one pod took ~4 minutes to start Running, the next was blocked and then took ~8 minutes, the next ~12 minutes, etc. It's possible there's a single-threaded task happening here, but I haven't found it.

https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-multipod-sh does the following:

* Create a secret `kubectl create secret docker-registry acr-auth --docker-server example.azurecr.io --docker-username example --docker-password test --docker-email me@example.com`
* Patch the service account with `kubectl patch sa default -p '{"imagePullSecrets":[{"name": "acr-auth"}]}' --type=merge`
* Append to the service account 29 times with `kubectl patch sa default --type='json' -p='[{"op": "add", "path": "/imagePullSecrets/-", "value": {"name": "acr-auth"}}]' > /dev/null`
* For N 1..20, measure duration:
    * Launch N pods `kubectl run -it --rm --image=alpine:3.6 --quiet=true --restart=Never alpine36 -- echo up` - observe <10s startup (note the image should cache)
    * Wait for all N pods to finish starting

I observe a linear relationship, all pods take approximately 10*QtyPods seconds to start in the presence of 30 imagePullSecrets. See https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-multipod-csv graphed ![reproduction-multipod.png](https://user-images.githubusercontent.com/1447600/52006970-6ab09900-249b-11e9-8f67-44f60840c48e.png).

The pods remain in ContainerCreating for most of the elapsed time, and then move to Running and Completed within a few seconds of each other.

```
NAME          READY     STATUS              RESTARTS   AGE       IP            NODE                       NOMINATED NODE
alpine36-1    0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-10   0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-11   0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-2    0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-3    0/1       Completed           0          2m        10.244.0.13   aks-agentpool-28810660-0   <none>
alpine36-4    0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-6    0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-7    0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
alpine36-9    0/1       ContainerCreating   0          2m        <none>        aks-agentpool-28810660-0   <none>
```

It appears in all cases I observed a pod to take approximately (0.3 * len(imagePullSecrets) * concurrentlyStartingPods) seconds to start.

I wonder whether (but have not proven that) there is a namespace-crossing effect here, where some many-imagePullSecrets x many-pods-creating in namespace A can cause some victim pod in namespace B to wait.

**Anything else we need to know?**:

I tried unsuccessfully to reproduce on KinD with v1.12.3-435f92c71.

@jackfrancis [noted on slack](https://kubernetes.slack.com/archives/C5HJXTT9Q/p1548797386652400) that "If you’ve identified a causal relationship there, it definitely *seems* like something foundational to the way Pod bootstrapping is implemented regardless of cloudprovider."

I don't know whether this is really a bug or working as intended. My naive guess is that `kubernetes/plugin/pkg/admission/serviceaccount/admission.go`'s `Admit()` is effectively single-threaded & slow (under some set of circumstances).

The workaround for this is pretty trivial: Don't do that. I figure it's useful to document in an issue anyway, even if that just gets closed wontfix, just in case it helps someone else.

**Environment**:
- Kubernetes version (use `kubectl version`):
    * Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
    * Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AKS 1-node cluster with v1.11.5 on Standard DS2 v2 (2 vcpus, 7 GB memory), standard networking, RBAC on, standard networking
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alanjcastonguay** [comment]
I can't attach the shellscripts or csv files here, so I put them at https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec

**Comment by alanjcastonguay** [comment]
Starting with @kubernetes/sig-azure-bugs, since I haven't reproduced this outside AKS.

**Comment by alanjcastonguay** [comment]
A tiny run of the same shell scripts (far fewer samples, still looks linear) against DockerForMac Version 2.0.0.2 (30215) running k8s v1.10.11 637c7e2885 at 
https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-multipod-dockerformac-csv and 
https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-dockerformac-csv.

**Comment by alanjcastonguay** [comment]
The original symptom was with AKS version 1.11.5. I ran the reproduction against AKS with version 1.11.6 (linear) and 1.12.4 (flat).

**Comment by alanjcastonguay** [comment]
A reproduction attempt on AKS 1.12.4 yielded  a flat deploy time - it's about 3 seconds (with some outliers) regardless of the number of imagePullSecrets listed. [Data](https://gist.github.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec#file-reproduction-1-12-4-csv) graphed:

![reproduction-1.12.4.png](https://gist.githubusercontent.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec/raw/339858b42bcf61dbd6f812349c5d13feb68e4032/reproduction-1.12.4.png).

**Comment by alanjcastonguay** [comment]
A reproduction attempt on AKS 1.11.6 yielded a linear deploy time, same as 1.11.5. [Data](https://gist.githubusercontent.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec/raw/1396b55134fd74a982d89770c049ed983b30bb4d/reproduction-1.11.6.csv) graphed:

![reproduction-1.11.6.png](https://gist.githubusercontent.com/alanjcastonguay/ac890649c5b484062dedf98ae1f186ec/raw/1396b55134fd74a982d89770c049ed983b30bb4d/reproduction-1.11.6.png).

So the behaviour changed between 1.11.6 and 1.12.4

**Comment by alanjcastonguay** [comment]
Those AKS clusters were deployed with commands like:

```
az aks create --no-ssh-key --kubernetes-version 1.11.5 --name 1-11-5-reproduction --resource-group 73541 --network-plugin kubenet --tags purpose=reproduction --node-count 1
az aks create --no-ssh-key --kubernetes-version 1.11.6 --name 1-11-6-reproduction --resource-group 73541 --network-plugin kubenet --tags purpose=reproduction --node-count 1
az aks create --no-ssh-key --kubernetes-version 1.12.4 --name 1-12-4-reproduction --resource-group 73541 --network-plugin kubenet --tags purpose=reproduction --node-count 1
```

**Comment by jveski** [comment]
AKS nodes have `node.alpha.kubernetes.io/ttl: 0`, so on 1.11.x clusters (prior to #64752) secrets referenced by pods aren't cached. You can verify this by bumping up the kubelet log level — for every pull secret you'll see a GET request for the associated secret when the pod is created.

Possibly this isn't showing up on other cloud providers because they set a non-0 TTL?

**Comment by alanjcastonguay** [comment]
@jveski thanks for the insight! That's a very reasonable explanation for the situation. Even an extremely short (<10s) cache would eliminate the impact of duplicates. On that basis this can be closed.
