### ISSUE TITLE
Secrets metadata should include updatedTimestamp

### ISSUE THREAD

**Issue by richgerrard** [kubernetes/kubernetes#73548]
**What would you like to be added**: 
Currently (v1.13) the metadata for secrets only includes creationTimestamp:
`kubectl get secret mysecret -o yaml`
returns:
`apiVersion: v1
data:
  config.yaml: YXBpVXJsOiAiaHR0cHM6Ly9teS5hcGkuY29tL2FwaS92MSIKdXNlcm5hbWU6IHt7dXNlcm5hbWV9fQpwYXNzd29yZDoge3twYXNzd29yZH19
kind: Secret
metadata:
  creationTimestamp: 2018-11-15T20:40:59Z
  name: mysecret
  namespace: default
  resourceVersion: "7225"
  selfLink: /api/v1/namespaces/default/secrets/mysecret
  uid: c280ad2e-e916-11e8-98f2-025000000001
type: Opaque`
(as per: [Secrets docs](https://kubernetes.io/docs/concepts/configuration/secret/) )
It would be delicious if this metadata also included a field for "updatedTimestamp" to track if changes were made to a secret since its inception.

**Why is this needed**: 
It would be great if we could use the `get secret` call to return an updatedTimestamp status to see if a change was made to a secret recently.  We have some keys, for example, that rotate regularly and need to be updated in `secrets`.  If one is missed due to human error, we need to decode each secret and compare manually to see if one was missed.  This is a little labour-intensive, and an updatedTimestamp would help narrow the scope of our task.

**Comment by richgerrard** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by Zyqsempai** [comment]
I can take this one if we will get approve.

**Comment by roycaihw** [comment]
cc @liggitt

**Comment by liggitt** [comment]
Fields added to metadata would affect all objects, not just secrets.

While this could be useful, it needs careful thought to avoid causing every write (even ones that change no data) to result in a write to etcd. The naive implementation (set the field to `time.Now()` in PrepareForCreate() and PrepareForUpdate()) would cause this issue.

Writes to etcd intentionally no-op if the bytes being written are identical to the ones already in etcd. We should not change that behavior (it would increase etcd writes in existing configurations, possibly significantly).

Given the scope (all objects) and the nuance of the implications, this needs to start as a proposal in the kubernetes/enhancements repo (template [here](https://github.com/kubernetes/enhancements/blob/master/keps/0000-kep-template.md)).

**Comment by hairyhenderson** [comment]
> While this could be useful, it needs careful thought to avoid causing every write (even ones that change no data) to result in a write to etcd

The main requirement here is to track changes, so writes that change no data should not cause the `updatedTimestamp` to change.
