### ISSUE TITLE
ResourceRequest Limits does not work as described

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#7355]
The API v3 says that:
```
// ResourceRequirements describes the compute resource requirements.
type ResourceRequirements struct {
	// Limits describes the maximum amount of compute resources required.
	Limits ResourceList `json:"limits,omitempty" description:"Maximum amount of compute resources allowed"`
	// Requests describes the minimum amount of compute resources required.
	Requests ResourceList `json:"requests,omitempty" description:"Minimum amount of resources requested"`
}
```

But in our scheduler implementation we use:
```
func getResourceRequest(pod *api.Pod) resourceRequest {
	result := resourceRequest{}
	for ix := range pod.Spec.Containers {
		limits := pod.Spec.Containers[ix].Resources.Limits
		result.memory += limits.Memory().Value()
		result.milliCPU += limits.Cpu().MilliValue()
	}
	return result
}
```

This means that in practice we use Limits as an amount used by the Scheduler to see if Pod fits the Node (i.e. we use it as ```Request``` should be), and we don't use ```Requests``` in any meaningful way.

For obvious reasons this is confusing, and we should fix that by either removing ```Requests``` from API and changing the comment, or fix current usages. I'm in favor of removing, even though I see that in future we may wan't to introduce this split again.

@ggarson @bgrant0607 @davidopp @thockin

**Comment by derekwaynecarr** [comment]
If limits are specified, they need to always take precedence over ```Requests```.  I think ```Requests``` right now is only used for persistent volume storage sizes.

**Comment by thockin** [comment]
I agree that the comment is worded badly, but the description makes more
sense to me.  In the PersistentVolume discussion, I argued this same point
- Limit was the wrong field to start with.   I can not find the notes on
the discussion, but maybe Brian's bear-trap memory will bring it back to
light.

**Comment by markturansky** [comment]
Here's one bit of that conversation: https://github.com/GoogleCloudPlatform/kubernetes/pull/4055#discussion_r25713050

**Comment by markturansky** [comment]
A more recent one:  https://github.com/GoogleCloudPlatform/kubernetes/pull/5105#discussion_r25985655

It can be difficult to piece together an entire conversation on github.

**Comment by thockin** [comment]
So my comments there were about Request.  I think Request is correct.

**Comment by lavalamp** [comment]
I don't think this is a 1.0 blocker.

**Comment by derekwaynecarr** [comment]
I think the problem right now is we have no way of enforcing ```Requests``` in the Kubelet right now via the Docker resource controls since it only allows for hard limits.

In the near term, we could look to do the following:

1. Validate that container.resources.requests is <= container.resources.limits for each specified key
2. Scheduler should merge container.resources.requests with container.resources.limits (where limits takes precedence) to build the getResourceRequest to perform node placement
3.  Kubelet ignores container.resources.requests until we have pod level cgroup support

**Comment by bgrant0607** [comment]
The comments/descriptions reflect what we want to have implemented. Requests has not been implemented, except for storage.

The scheduler should use Requests.

Kubelet doesn't need to enforce Requests.

Requests < Limits implies a lower QoS (#147).

See the explanation in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md

cc @vishh

**Comment by bgrant0607** [comment]
We should document how we translate cpu limit to shares. The swagger isn't really the right place. Probably we need a more user-focused version of resources.md.

**Comment by gmarek** [comment]
Because we provide an abstraction of a higher level than Docker and our users don't really need to understand Docker way of handling resources (i.e. what kind of guarantees they can/cannot expect), I believe that we should explain this as well. The same holds for other container engines.

**Comment by gmarek** [comment]
@bgrant0607 is this fixed by current QoS implementation?

**Comment by bgrant0607** [comment]
Yes.
