### ISSUE TITLE
--vmodule used in scalability tests is adding significant concention

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#73575]
After we moved logging all requests in apiserver to V(3) level:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L146

We have added the:
--vmodule=httplog=3
to config of all scalability tests, because debugging scalability tests is pretty much impossible without having those logs.

However, apparently this is adding a huge lock contention on that, because if vmodule is non-empty, we enter a non-trivial code-path in the glog for every single glog call:
https://github.com/golang/glog/blob/master/glog.go#L999

I did some experiments, and switching --v=3 for apiserver (instead of --v=2 + vmodule) doesn't introduce the significiant change - the difference in amount of produced logs is about 10% (a bit less).

So given that we don't do that in production anyway, what we should do is to:
- set --v=3 for apiserver in our scalability tests (to have all the logs we need)
- get rid of those vmodule settings

@kubernetes/sig-scalability-bugs

**Comment by mm4tt** [comment]
Something went wrong here.
The vmodule flag change worked as expected, but setting --v=3 in apiserver didn't.
Here are the api-server args from the recent run of the gce scale perormance 
![api-server-args](https://user-images.githubusercontent.com/2604887/52262664-5ce09500-292d-11e9-8674-4b7e2be8e519.png)
The vmodule is not set, but the log level is set to v2. As the result we currently don't have the http logs.

I'm investigating why log verbosity is not overridden in api server.

**Comment by mm4tt** [comment]
Env variables seem to be set correctly in the build file:
![7vg9cptdh59](https://user-images.githubusercontent.com/2604887/52263270-fa889400-292e-11e9-8a0b-b8b5a61b26f3.png)

**Comment by mm4tt** [comment]
https://github.com/kubernetes/kubernetes/pull/73735 seems to be fixing the issue - 
![4vn4qtcwwew](https://user-images.githubusercontent.com/2604887/52267856-67555b80-293a-11e9-9dd6-a86866dfe69e.png)
