### ISSUE TITLE
deployment's image always rollback to specify tag

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes/kubernetes#73574]
**What happened**: when edit deployment's image, it will auto rollback to specify tag  
if you set image to "abcd:v1", it will be "abcd:v3.1.10-dev" after few seconds 
if you set image to "xyz:v2", it will be "xyz:v3.1.10-dev" after few seconds
and  
```
kubectl rollout history deployment mydep
```
output like this:  
```
13   kubectl set image deployment/mydep mydep=abcd:v3.1.10-dev --namespace=mynamespace --record=true
14   kubectl set image deployment/mydep mydep=xyz:v3.1.10-dev --namespace=mynamespace --record=true
... 
```
but i never run these commands, but just edit deployment's image in dashboard, edit one time, rollout history output will add one line, which image name equal to my edit but tag always be "v3.1.10-dev".

**What you expected to happen**: 
do not set image automatically please!!

**How to reproduce it (as minimally and precisely as possible)**: 
i have no idea because just one deployment wrong.

**Anything else we need to know?**:  etcd cluster timeout sometimes. but other deployments works well.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
CentOS Linux release 7.4.1708 (Core)
```
- Kernel (e.g. `uname -a`):
```
Linux k8s20 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

/sig bug

**Comment by neolit123** [comment]
hello, k8s version 1.9 is outside of the support skew, thus even if there is a bug we cannot fix it.
please try at least k8s 1.12 and re-open this issue if the problem is still present.

thank you.
/close
