### ISSUE TITLE
Containers deleted while pod still having finalizers set

### ISSUE THREAD

**Issue by calind** [kubernetes/kubernetes#73584]
**What happened**:
Pod enters `Terminating` state and containers get deleted even if finalizers still exist on pod.

**What you expected to happen**:
Pods should stay in `Running` state and containers should stay up while finalizers still exist on pod.

**How to reproduce it (as minimally and precisely as possible)**:
```console
$ kubectl apply -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: finalizer-pod
  finalizers:
    - test.example.com/my-finalizer
spec:
  containers:
  - name: nginx
    image: nginx
EOF
$ kubectl delete pod finalizer-pod --timeout 1s
pod "finalizer-pod" deleted
$ kubectl get pod
NAME            READY     STATUS        RESTARTS   AGE
finalizer-pod   0/1       Terminating   0          74s
```

**Anything else we need to know?**:
We need this in order to do gracefull failovers when pods get deleted. We cannot use container lifecycle hooks because we need to coordinate the failover across containers and pods. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"10ecc6db83fd47a93eb0940e2e4434f2b0a5c3ec", GitTreeState:"clean", BuildDate:"2018-08-15T21:23:47Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Docker for Mac`
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Docker Desktop"
```
- Kernel (e.g. `uname -a`):
```
Linux e10fa4332909 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
```

**Comment by afirth** [comment]
I think this is working as designed, because the finalizer is on the pod, not the container, so it does not block GC of the container, even with foreground deletion. You mention that preStop is not an option for you? [finalizer design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/garbage-collection.md#new-components). I'm unclear if it's possible to put a finalizer on the container directly, however I don't think that will solve your problem either.

**Comment by calind** [comment]
My expectation was that `kubelet` waits for finalizers to be removed before starts terminating containers. Otherwise I really don't see the value in having finalizer on an pod with 0 containers.

Design docs don't state a clear behavior for this case.

**Comment by afirth** [comment]
I believe that 1) finalizers are run async, and only block the _hard_ delete of the object they are on (parent/pod), and 2) they will never block the deletion of a resource which has ownerRefs to this object (child/container).
Even if they were on the container, the finalizer begins executing as soon as it's marked for deletion. I don't know of anything that blocks removing the endpoint from the service, maybe someone else can chime in.

**Comment by liggitt** [comment]
This is working as designed. Finalizers block deletion of the pod API object, not termination of the containers. You can use graceperiodseconds and prestophooks to give your containers time to shut down gracefully on termination.
