### ISSUE TITLE
vsphere cloud provider fails reading accessible datastores and won't create volumes

### ISSUE THREAD

**Issue by brokenjacobs** [kubernetes/kubernetes#73597]
/kind bug
/sig cloud-provider
/sig vmware
@kubernetes/sig-vmware-bugs

**What happened**:
Trying to set up the vsphere cloud provider on a new kubernetes cluster, I am unable to get the provider to create pv's. It doesn't even attempt to do so.

**What you expected to happen**:
A pv would be created when deploying a statefulset, instead the pvc stays pending and never creates.

**How to reproduce it (as minimally and precisely as possible)**:
kubeadm deploy a new cluster with the vsphere provider against vcenter 6.5.0.13000 with version 1.13.2 or 1.12.5 of kubernetes, using centos 7.6.1810 vms. Pass cloud-provider flags to kubeadm so providerID shows in the node details (otherwise you run into issue [65933](https://github.com/kubernetes/kubernetes/issues/65933)

**Anything else we need to know?**:
Relevant kube-controller-manager -v=0 output:
```I0131 16:39:00.338886       1 vsphere_volume_util.go:140] VSANStorageProfileData in vsphere volume ""
I0131 16:39:00.338894       1 vsphere.go:1133] Starting to create a vSphere volume with volumeOptions: &{CapacityKB:5242880 Tags:map[kubernetes.io/created-for/pvc/namespace:default kubernetes.io/created-for/pvc/name:data-minio-0 kubernetes.io/created-for/pv/name:pvc-b42968e0-2576-11e9-aadf-005056884d81] Name:kubernetes-dynamic-pvc-b42968e0-2576-11e9-aadf-005056884d81 DiskFormat:thin Datastore: VSANStorageProfileData: StoragePolicyName: StoragePolicyID: SCSIControllerType:}
I0131 16:39:00.339814       1 graph_builder.go:578] GraphBuilder process object: events.k8s.io/v1beta1/Event, namespace default, name minio-0.157efc4ec21f319c, uid b42b426e-2576-11e9-aadf-005056884d81, event type update
I0131 16:39:00.343229       1 nodemanager.go:424] Renewing NodeInfo &{dataCenter:0xc000206340 vm:0xc00044f210 vcServer:den-resvc-1.*** vmUUID:42084a1c-41a2-965b-b3aa-482b24027dca} for node "den-k8smaster1-1.***"
I0131 16:39:00.344266       1 nodemanager.go:312] Updated NodeInfo {0xc002f22078 0xc0038e06f0 den-resvc-1.*** 42084a1c-41a2-965b-b3aa-482b24027dca} for node "den-k8smaster1-1.***".
I0131 16:39:00.344280       1 nodemanager.go:424] Renewing NodeInfo &{dataCenter:0xc0000d2758 vm:0xc000247aa0 vcServer:den-resvc-1.*** vmUUID:42086533-599f-e8b3-b146-5efa4d43998f} for node "den-k8sworker1-1.***"
I0131 16:39:00.345316       1 nodemanager.go:312] Updated NodeInfo {0xc00000c4e0 0xc003dec940 den-resvc-1.*** 42086533-599f-e8b3-b146-5efa4d43998f} for node "den-k8sworker1-1.***".
I0131 16:39:00.345337       1 vsphere_util.go:132] Getting accessible datastores for node den-k8smaster1-1.***
E0131 16:39:00.348871       1 virtualmachine.go:229] Failed to get Datastore managed objects from datastore objects. dsObjList: [], properties: [info], err: object references is empty
I0131 16:39:00.348885       1 vsphere_util.go:110] error "object references is empty" getting accessible datastores for node &{NodeName:den-k8smaster1-1.*** vm:0xc0038e06f0 VMUUID:42084a1c-41a2-965b-b3aa-482b24027dca}
E0131 16:39:00.348895       1 vsphere.go:1185] Failed to get shared datastore: object references is empty
I0131 16:39:00.348904       1 vsphere.go:1237] The canonical volume path for the newly created vSphere volume is ""
I0131 16:39:00.348919       1 pv_controller.go:1511] failed to provision volume for claim "default/data-minio-0" with StorageClass "miniosc": object references is empty
E0131 16:39:00.348952       1 goroutinemap.go:150] Operation for "provision-default/data-minio-0[b42968e0-2576-11e9-aadf-005056884d81]" failed. No retries permitted until 2019-01-31 16:39:01.34893902 +0000 UTC m=+61.721747776 (durationBeforeRetry 1s). Error: "object references is empty"
I0131 16:39:00.348989       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"data-minio-0", UID:"b42968e0-2576-11e9-aadf-005056884d81", APIVersion:"v1", ResourceVersion:"3335", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "miniosc": object references is empty
```
**Environment**:
vmware vsphere environment, fibre channel backed storage no vsan, no storage profiles
3 vcenters, 1 separate platform services controller
all k8s vm's are in the same vcenter, with the same storage attached

- Kubernetes version (use `kubectl version`):
-bash-4.2$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
vsphere cloud provider
vmware vcenter 6.5.0.13000
vmware esxi 6.5.0, 10175896 
```
[Global]
        user = "k8s-vsphere-service@***"
        password = "*******"
        server = "den-resvc-1.ci.neoninternal.org"
        port = "443"
        insecure-flag = "1"
        datacenter = "***-Denver-Resource"
        datastore = "vol-k8s-1"
        working-dir = "folder-K8S"
[Disk]
        scsicontrollertype = pvscsi
```
- OS (e.g. from /etc/os-release):
centos 7.6.1810
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
I have also tested with Kubernetes 1.12.5 and gotten the same results.

**Comment by brokenjacobs** [comment]
Ok well this ended up being my issue. I figured out that somehow the volume I was using wasn't attached to three of my cluster nodes, which just happened to be the nodes running the kubernetes vm's. Rescan storage, everything works. Closing ticket. This was driving me nuts.

**Comment by tirelibirefe** [comment]
> Ok well this ended up being my issue. I figured out that somehow the volume I was using wasn't attached to three of my cluster nodes, which just happened to be the nodes running the kubernetes vm's. Rescan storage, everything works. Closing ticket. This was driving me nuts.

Hello Brokenjacobs;
Were you able to figure it out? If yes, how did you fix the problem? I have been working on the same problem for a while.

**Comment by brokenjacobs** [comment]
I ended up just resetting things. Never did get it to reattach.

**Comment by belissner** [comment]
Hello, we also had this issue and a Rescan storage on VMware cluster where the K8s nodes reside has solved the issue.
