### ISSUE TITLE
Pod scheduled in NetworkNotReady node stucks ContainerCreating

### ISSUE THREAD

**Issue by micafer** [kubernetes/kubernetes#73590]
**What happened**:

We have deloped a tool to manage an elastic kubernetes cluster.
We send pods to the cluster and, if there are no free resources, new nodes are automatically added to the cluster.
When the nodes are added to the cluster (using kubeadm join) pods are assigned to the new node but in many cases the pods stuck in "ContainerCreating" state showing this info:

```
  Type     Reason                  Age                 From                      Message
  ----     ------                  ----                ----                      -------
  Warning  FailedScheduling        13m (x11 over 17m)  default-scheduler         0/2 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling        11m                 default-scheduler         0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 Insufficient cpu, 2 Insufficient memory.
  Normal   Scheduled               11m                 default-scheduler         Successfully assigned fn/plants-3ca92873-19f6-4393-af75-c0db54bfdde4-j779l to wn3.localdomain
  Warning  NetworkNotReady         10m (x8 over 11m)   kubelet, wn3.localdomain  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized]
  Warning  FailedCreatePodSandBox  10m                 kubelet, wn3.localdomain  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "59bf34f4a3803e50f29d709acf629e734a7793daa36400035ecc46d8b63c2268" network for pod "plants-3ca92873-19f6-4393-af75-c0db54bfdde4-j779l": NetworkPlugin cni failed to set up pod "plants-3ca92873-19f6-4393-af75-c0db54bfdde4-j779l_fn" network: open /run/flannel/subnet.env: no such file or directory
```

**What you expected to happen**:

Pods successfully launched and running.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster and launch a set of pods that required more resources than the actual available resources.
They remain in pending state. Then add a new node to the cluster to execute these pods.

**Anything else we need to know?**:

It seems that the scheduler assigns the pods to the node before it has the network ready (is our case using the flannel network).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
KVM VMs with 2 CPUs and 4 GB of RAM.
- OS (e.g. from /etc/os-release):
Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`):
```
Linux kubeserver.localdomain 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: 
kubeadm

**Comment by tanshanshan** [comment]
from the error msg` network is not ready`, you should check your  whether flannel network plugin is ok.
check your flannel pod firstly.

**Comment by changyaowei** [comment]
https://github.com/kubernetes/kubernetes/issues/72129

**Comment by changyaowei** [comment]
When a node add, before it change to unready, schedule a pod to the node

**Comment by micafer** [comment]
> #72129

Yes this is exactly my issue.

**Comment by micafer** [comment]
Last release 1.13.3 apply the PR #73097 and fixes my issue.
