### ISSUE TITLE
E2E storage: test snapshot semantics

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#73625]
**What would you like to be added**:

https://github.com/kubernetes/kubernetes/pull/69036 adds a test that snapshots can be created and used. It would be good to actually verify that the snapshotting properly handles data (https://github.com/kubernetes/kubernetes/pull/69036/files#r252769254):

1. Write some data
1. Take a snapshot
1. Write more data
1. Create a new volume from snapshot
1. Validate data is the old data

**Why is this needed**:

To ensure that snapshotting really works.

/sig storage
/cc @msau42 @xing-yang @wackxu

**Comment by xing-yang** [comment]
Hi @AndiLi99, there's an PR opened for this a while ago: https://github.com/kubernetes/kubernetes/pull/79015.  It needs an update.  Can you help review that one?  Thanks.

**Comment by AndiLi99** [comment]
Hi @xing-yang, that pr is a bit outdated and I don't think I have any further comments to add besides needing to rebase and deal with merge conflicts.
