### ISSUE TITLE
Break dependency between k8s.io/kubernetes/pkg/credentialprovider/aws and k8s.io/kubernetes/pkg/cloudprovider/providers/aws

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#73643]
Please see:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/regions.go#L81

This is making it hard to move the code to staging/ as part of external cloud provider enablement.

**Comment by dims** [comment]
@mcrute will you be able to help with this?

**Comment by mcrute** [comment]
@dims funny you should ask, there's been a PR open (#70675) for about 3 months that just needs some input from @liggitt and @justinsb that fixes just this. :smile:

**Comment by andrewsykim** [comment]
/close 

This was done in https://github.com/kubernetes/kubernetes/pull/75587
