### ISSUE TITLE
Delete: needs more preconditions

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#73648]
Today you can use UID as a precondition for delete; this allows you to avoid deleting an object that has been replaced with an object of the same name.

As reported by @fasaxc on slack, there's also a need to ensure a delete fails if an unobserved change happens to an object. This could be implemented as either an RV or a Generation precondition.

Scenario:

1) A observes object foo and sends a delete request.
2) B observes object foo and modifies it in a way that would have prevented its deletion.
3) A's delete request happens to arrive afterwards; the object is deleted and B's change is lost.

/sig api-machinery

**Comment by ajatprabha** [comment]
@lavalamp I'd like to work on this issue.

**Comment by lavalamp** [comment]
@ajatprabha Go for it!

**Comment by krmayankk** [comment]
Are we saying that , if I get an object, store its resourceVersion and then issue a delete on the resourceVersion for that object , even though the object has been modified and hence its resourceVersion changed, the delete still succeeds ?

**Comment by ajatprabha** [comment]
@krmayankk I think there is no RV based precondition check on delete. Only UID based check is there.
https://github.com/kubernetes/kubernetes/blob/0c2613c71a87f850190a8c1084d4de1e18336c07/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L79-L82
I'm a little confused when you say `issue a delete on resourceVersion for that object`. Do you mean like delete the object with old stored RV? In that case, I think currently the delete succeeds as I can't find a check.

**Comment by ajatprabha** [comment]
@lavalamp I'm looking at #22965 to see which places need precondition checks. Will a simple `Preconditions.ResourceVersion` check suffice to solve the issue here? Also, how will a Generation precondition work if it is to be used?

**Comment by lavalamp** [comment]
RV precondition: only delete the object if its current RV equals the specified one.

Generation precondition: only delete the object if its current metadata.Generation equals the specified one.

Either one works, the generation one is more tolerant of random status updates. There's possibly room in the world for both.

@deads2k might have an opinion?

If we're going to have more than 2 or three of these things we probably need to make a general mechanism :/ But I think people can use RV or Generation preconditions to stand in for an arbitrary check, so if anything deserves a top level precondition, it'd be those.

**Comment by lavalamp** [comment]
Thanks, @ajatprabha!

**Comment by krmayankk** [comment]
This is good to know, I thought the RV based update/delete worked and would always result in conflict if RV changed. I wonder where do these kinds of changes get documented . May be worth an entry in the api conventions doc?
