### ISSUE TITLE
PVC supplied secrets for volume authentication

### ISSUE THREAD

**Issue by venkatsc** [kubernetes/kubernetes#73641]
**What would you like to be added**:

PVC supplied secrets for volume authentication for both statically and dynamically provisioned volumes  (currently for CSI's NodeStage and NodePublish related API calls. Possibly, later can be extended to the ControllerPublish and Provisioning related API calls).

Assumptions:
1. Every storage user has their own credentials to access the storage
2. K8S deployment follows the [suggested usage model for storage resources](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#introduction) 

To achieve this, we propose a slight modification to the existing approach 

Administrator:

1. Creates `StorageClass` with storage provider and other parameters except `csi.storage.k8s.io/node-stage-secret-name`, `csi.storage.k8s.io/node-stage-secret-namespace`, `csi.storage.k8s.io/node-publish-secret-name` and  `csi.storage.k8s.io/node-publish-secret-namespace`. This can be used by users for all volume calls by supplying their own secrets through PVC.
2.  Dynamic volumes (through `external-provisioner`) creates PV without appending these secrets into the `PV.Spec.csi` and leaves those to be resolved from bound PVC during mount time.
3. For static volumes, Administrator creates the PV without `PV.Spec.csi.nodePublishSecretRef` and `PV.Spec.csi.nodeStageSecretRef` leaving those to be resolved from the bound PVC.

Normal User:

1. From PVC, sends the fixed keys that are already formalized for CSI calls `csi.storage.k8s.io/node-publish-secret-name/namespace` instead of templated keys
2. Before initiating `NodeStageVolume/NodeUnstageVolume/NodePublishVolume/NodeUnpublishVolume` from CSI component in K8S, get the binding PVC from `PV.Spec.claimRef`, if the accessed `claimRef` has secrets supplied with above keys use these for respective calls.
3. If the binding PVC does not provide any secrets, fail the mount. 

**Why is this needed**:
To authenticate users with vendor side authentication mechanisms such as authentication tokens before giving access to the volume.

Without Per PVC secrets, users can only use the volume with administrator provided secrets and storage vendor cannot distinguish between different users to authenticate.

Currently, CSI supports per PVC secrets for `NodeStageVolume`, `NodeUnstageVolume`, `NodePublishVolume` and `NodeUnpublishVolume` calls through [templating](https://kubernetes-csi.github.io/docs/Usage.html#csi-provisioner-parameters) parameters in storage class. However, it only works for dynamic provisioning as the secrets from PVC are added to the PV only once during the volume [provisioning](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L866) in the `external-provisioner`. It creates the following issues,

1. A dynamically provisioned volume with CSI cannot be used by more than one user even after clean up as secrets of the user are stuck onto the PV. The administrator can remove the secrets but does not know whose secrets should be attached there for the next use. 
2. Statically provisioned volumes cannot use "per PVC secrets" as there will not be any interaction with the provisioner. In this case, secrets supplied in PVC are ignored. This not only makes the "per PVC secrets" useless but creates the confusion as "per PVC secrets" behave differently in different flows.

The below flow explains some of the issues in details, 
1. User A creates PVC passing secrets through annotations. This creates dynamic volume in storage and its PV (with the secrets supplied in the PVC) in K8S.
2. User deletes the PVC after use, which moves the PV to the `Released` state. Administrator cleans the volume and makes it available for re-use. At this point, the administrator does not know which user is going to use the PV, so it is not possible for the administrator to associate any valid secrets to the PV except their own secrets.
3. Some other user B tries to bind this PV by supplying secrets through PVC, CSI does not use the secrets given in PVC as there is no involvement of `external-provisioner` at this point. 

/sig storage
/cc @msau42

**Comment by msau42** [comment]
For manual provisioning, do you already know which PVC the PV is intended for?

**Comment by venkatsc** [comment]
Hi @msau42 
We are a storage provider, it is unpredictable how PVC and PVs are going to be used at the customer deployments.

I followed the [recommended deployment approach](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#introduction)
1. Administrator manages the PV
2. User manages the PVC

So the binding is in the direction of PVC to PV.
Our expectation is that the administrator creates the PVs and user request the PVs through PVCs.
