### ISSUE TITLE
client-go build error

### ISSUE THREAD

**Issue by lijiansgit** [kubernetes/kubernetes#73654]
**What happened**:
i run go build command 
../../../k8s.io/kubernetes/pkg/features/kube_features.go:495:23: cannot us
e "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceValidation (
type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/util/feat
ure".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature in map k
ey
../../../k8s.io/kubernetes/pkg/features/kube_features.go:496:23: cannot us
e "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceSubresources
 (type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/util/fe
ature".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature in map
 key
../../../k8s.io/kubernetes/pkg/features/kube_features.go:497:23: cannot us
e "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceWebhookConve
rsion (type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/ut
il/feature".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature i
n map key

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Ubuntu 18.04.1 LTS \n \l
go version go1.11.1 linux/amd64
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
code:
package main

import (
	"time"

	"github.com/pkg/errors"
	"k8s.io/api/core/v1"

	log "github.com/lijiansgit/go/libs/log4go"
	appsv1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	cltappsv1 "k8s.io/client-go/kubernetes/typed/apps/v1"
	cltcorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
	deploymentutil "k8s.io/kubernetes/pkg/controller/deployment/util"
)

	replicaSets, _, _, err := deploymentutil.GetAllReplicaSets(config.deployment, r.appsClt)
	if err != nil {
		panic(err)
	}

**Comment by roycaihw** [comment]
please take a look at: https://github.com/kubernetes/client-go#dependency-management

as @liggitt suggested, you are having some similar problem, and you need to apply one of the solutions mentioned above

https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dependency-management-for-the-serious-or-reluctant-user could help if you use godeps/glide/dep as your dependency management tool
