### ISSUE TITLE
use NVIDIA_VISIBLE_DEVICES to share GPU in Kubernetes

### ISSUE THREAD

**Issue by shajc0504** [kubernetes/kubernetes#73660]
NVIDIA_VISIBLE_DEVICES : controls which GPUs will be accessible inside the container. By default, all GPUs are accessible to the container.
Can kubernetes use NVIDIA_VISIBLE_DEVICES to implement GPU sharing?

**Comment by neolit123** [comment]
/close

please discuss this topic in the https://github.com/NVIDIA/k8s-device-plugin/ tracker.
also this seems related to https://github.com/kubernetes/kubernetes/issues/52757

thanks.
