### ISSUE TITLE
Inefficient sharding in staging/src/k8s.io/apimachinery/pkg/util/cache/cache.go

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#73671]
**What happened**:
When indices are skewed in terms of number of items per shard, there would be shard(s) with more frequent evictions compared to less populated shard(s).

**What you expected to happen**:
We can use maxSize / shardsCount as target capacity per shard. Shard(s) with fewer items than target capacity should allow shard(s) with more items than target capacity to borrow against unused quota.

If usage in low occupancy shard(s) increases, we can evict random key from shard with above target capacity items.

This way, overall, we make efficient use of cache with maxSize items.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by roycaihw** [comment]
cc @wenjiaswe
