### ISSUE TITLE
Add support for blacklist in PodTolerationRestriction Admission Controller 

### ISSUE THREAD

**Issue by rnsv** [kubernetes/kubernetes#73675]
**What would you like to be added**:
Need an ability to provide blacklisted tolerations in PodTolerationRestriction Admission Controller 
**Why is this needed**:
The current implementation only supports whitelist and default tolerations.  This feature is useful In cases where the administrator of the cluster wants to taint certain nodes to be used exclusively for cluster administration (e.g pods running in kube-system).   This feature will provide the ability to prevent pods running on other non-system namespaces from tolerating these taints

**Comment by rnsv** [comment]
/area/admission-control
/sig/api-machinery

**Comment by rnsv** [comment]
/area/admisson-control

**Comment by xiaoxubeii** [comment]
I don't get your point. Can you make an use case?

**Comment by rnsv** [comment]
Here is an example of my cluster configuration for this usecase

Two nodes (node1, node2)
Taints on node1 -> t1, t2
Taint on node2 -> t2

Two namespaces (ns1, ns2)
pods on ns1 -> pod1 -> tolerates taints t1 and t2
pods on ns2 -> pod2 -> tolerates taint t2

If I want to prevent pod2 on ns2 from tolerating t1, I can add a whitelist for taints with t2 (in ns2)

Later, I decide to add a new node (node3) with taints t2 and t3

If I have to allow pod2 to tolerate t3, I have to update my whitelist to include t3. The new whitelist on ns2 will become t2 and t3

This is a great feature if I want to manage everything with whitelisted tolerations.

In large clusters with multiple namespaces and taints, there are situations where you just want to prevent certain pods from tolerating few taints.  In those situations, it will be easier for cluster admin to specify blacklisted tolerations.

In the above example if I had to implement using blacklist tolerations, I would just add t1 to ns2's blacklist.
