### ISSUE TITLE
Several sig-storage tests failing in master-upgrade

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#73696]
**Which jobs are failing**:
In [master-upgrade](https://testgrid.k8s.io/sig-release-master-upgrade):
- [gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)
- [gce-new-master-upgrade-cluster-new-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel)

**Which test(s) are failing**:
- `[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (ext3)] volumes should be mountableChanges`
- `[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] provisioning should provision storage with defaultsChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should be able to unmount after the subpath directory is deletedChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should fail if non-existent subpath is outside the volume [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath directory is outside the volume [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath file is outside the volume [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support creating multiple subpath from same volumes [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directories when readOnly specified in the volumeSourceChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing directoryChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support existing single fileChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support file as subpathChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support non-existent pathChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMountChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly file specified in the volumeMountChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support restarting containers using directory as subpath [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should support restarting containers using file as subpath [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should verify container cannot write to subpath readonly volumesChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] volumeIO should write files of various sizes, verify size, validate content [Slow]Changes`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] volumes should allow exec of files on the volumeChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] volumes should be mountableChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (ext3)] volumes should allow exec of files on the volumeChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (ext4)] volumes should allow exec of files on the volumeChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (ext4)] volumes should be mountableChanges`
- `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (filesystem volmode)] volumeMode should create sc, pod, pv, and pvc, read/write to the pv, and delete all created resources`

**Since when has it been failing**:
January 31st, 2019

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new-parallel/1176

**Reason for failure**:
Seem to be different versions of timeouts:
```
PersistentVolumeClaims [pvc-9447w] not all in phase Bound within 5m0s
```

```
timed out waiting for the condition
```

```
Gave up after waiting 5m0s for pod "pod-subpath-test-pd-csi-storage-gke-io-dynamicpv-rwlf" to be "success or failure"
```

```
Gave up after waiting 5m0s for pod \"csi-injector-22rh\" to be \"success or failure\""
```

**Anything else we need to know**:
- Coincides with the test-infra commit 1c0a3d856 ([diff since last passing commit](https://github.com/kubernetes/test-infra/compare/e62114bdc...1c0a3d856))
- Some sig-cluster-lifecycle tests started failing at the same time (https://github.com/kubernetes/kubernetes/issues/73705)

cc @mortent @kacole2 @alejandrox1 @smourapina

/kind failing-test
/sig testing
/sig storage

**Comment by mariantalla** [comment]
Editing this to cover only sig-storage related failed tests, https://github.com/kubernetes/kubernetes/issues/73705 covers sig-cluster-lifecycle ones that started at the same time.

**Comment by msau42** [comment]
/assign @david

In the serial job, it's mostly CSI volume tests that are failing, but in the parallel job there are some in tree failures too.

In the past, the NodeLease tests have left the cluster in a bad state so that is something to investigate

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by davidz627** [comment]
prelim investigation: looks like most of the errors are of the form
`event for csi-gce-pd-node-tt9wp: {kubelet bootstrap-e2e-minion-group-tfxr} FailedMount: MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory`
which suggests the Node DaemonSet of the driver is not coming up because the `plugins_registry` directory does not exist. This directory exists on k8s `1.13+`.

The test `gce-new-master-upgrade-cluster-new` should first upgrade the cluster (i.e. master and nodes) and then run the new test suite with new kubectl.

This leads me to believe that the cluster is not being upgraded properly before the tests are being run which seems to be confirmed by the upgrade test failure:
```
[sig-cluster-lifecycle] Upgrade [Feature:Upgrade]
I0201 07:49:19.777] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/framework.go:22
I0201 07:49:19.777]   cluster upgrade
I0201 07:49:19.777]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/cluster_upgrade.go:142
I0201 07:49:19.777]     should maintain a functioning cluster [Feature:ClusterUpgrade] [It]

I0201 07:49:19.778]     Expected error:
I0201 07:49:19.778]         <*errors.errorString | 0xc00151c050>: {
I0201 07:49:19.779]             s: "error running /workspace/kubernetes_skew/cluster/gce/upgrade.sh [-N v1.14.0-alpha.2.152+1b741f4c77aa97]; got error exit status 127, stdout \"== Pre-Upgrade Node OS and Kubelet Versions ==\\nname: \\\"bootstrap-e2e-master\\\", osImage: \\\"Container-Optimized OS from Google\\\", kubeletVersion: \\\"v1.14.0-alpha.2.152+1b741f4c77aa97\\\"\\nname: \\\"bootstrap-e2e-minion-group-0l2g\\\", osImage: \\\"Container-Optimized OS from Google\\\", kubeletVersion: \\\"v1.12.6-beta.0.18+8ddfd4bc3159d5\\\"\\nname: \\\"bootstrap-e2e-minion-group-n8rn\\\", osImage: \\\"Container-Optimized OS from Google\\\", kubeletVersion: \\\"v1.12.6-beta.0.18+8ddfd4bc3159d5\\\"\\nname: \\\"bootstrap-e2e-minion-group-tfxr\\\", osImage: \\\"Container-Optimized OS from Google\\\", kubeletVersion: \\\"v1.12.6-beta.0.18+8ddfd4bc3159d5\\\"\\nFound subnet for region us-west1 in network bootstrap-e2e: bootstrap-e2e\\n== Ensuring that new Node base OS image matched the existing Node base OS image\\n\", stderr \"Project: k8s-jkns-gke-slow-1-4\\nNetwork Project: k8s-jkns-gke-slow-1-4\\nZone: us-west1-b\\nINSTANCE_GROUPS=bootstrap-e2e-minion-group\\nNODE_NAMES=bootstrap-e2e-minion-group-0l2g bootstrap-e2e-minion-group-n8rn bootstrap-e2e-minion-group-tfxr\\n== Preparing node upgrade (to v1.14.0-alpha.2.152+1b741f4c77aa97). ==\\nWarning: Permanently added 'compute.3483888700310310388' (RSA) to the list of known hosts.\\r\\n/workspace/kubernetes_skew/cluster/gce/upgrade.sh: line 216: set-node-image: command not found\\n\"",
I0201 07:49:19.779]         }
I0201 07:49:19.780]         error running /workspace/kubernetes_skew/cluster/gce/upgrade.sh [-N v1.14.0-alpha.2.152+1b741f4c77aa97]; got error exit status 127, stdout "== Pre-Upgrade Node OS and Kubelet Versions ==\nname: \"bootstrap-e2e-master\", osImage: \"Container-Optimized OS from Google\", kubeletVersion: \"v1.14.0-alpha.2.152+1b741f4c77aa97\"\nname: \"bootstrap-e2e-minion-group-0l2g\", osImage: \"Container-Optimized OS from Google\", kubeletVersion: \"v1.12.6-beta.0.18+8ddfd4bc3159d5\"\nname: \"bootstrap-e2e-minion-group-n8rn\", osImage: \"Container-Optimized OS from Google\", kubeletVersion: \"v1.12.6-beta.0.18+8ddfd4bc3159d5\"\nname: \"bootstrap-e2e-minion-group-tfxr\", osImage: \"Container-Optimized OS from Google\", kubeletVersion: \"v1.12.6-beta.0.18+8ddfd4bc3159d5\"\nFound subnet for region us-west1 in network bootstrap-e2e: bootstrap-e2e\n== Ensuring that new Node base OS image matched the existing Node base OS image\n", stderr "Project: k8s-jkns-gke-slow-1-4\nNetwork Project: k8s-jkns-gke-slow-1-4\nZone: us-west1-b\nINSTANCE_GROUPS=bootstrap-e2e-minion-group\nNODE_NAMES=bootstrap-e2e-minion-group-0l2g bootstrap-e2e-minion-group-n8rn bootstrap-e2e-minion-group-tfxr\n== Preparing node upgrade (to v1.14.0-alpha.2.152+1b741f4c77aa97). ==\nWarning: Permanently added 'compute.3483888700310310388' (RSA) to the list of known hosts.\r\n/workspace/kubernetes_skew/cluster/gce/upgrade.sh: line 216: set-node-image: command not found\n"
I0201 07:49:19.780]     not to have occurred
```

Version being stuck in `1.12` also confirmed in this Node info dump at the end of a failing test:
```
Node Info: &Node{....,KubeletVersion:v1.12.6-beta.0.18+8ddfd4bc3159d5,...}
```

/cc @kubernetes/sig-cluster-lifecycle 
/assign @justinsb 
for triage (sorry I'm not sure who owns the cluster upgrade tests)

**Comment by justinsb** [comment]
> ...workspace/kubernetes_skew/cluster/gce/upgrade.sh: line 216: set-node-image: command not found\\n\""...

 think set-node-image was renamed to set-linux-node-image in f0f78299348afcf770d4e8d89dcea82f80811b28 .  I'll try sending a PR to fix

**Comment by justinsb** [comment]
PR to rename those functions in #73822 - hopefully a fix!

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by msau42** [comment]
I think this is resolved. I don't see these test cases failing in the upgrade suites.
/close
