### ISSUE TITLE
[sig-cluster-lifecycle] cluster upgrade tests failing

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#73705]
**Which jobs are failing**:
on `sig-master-upgrade`:

[https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster&width=80)

**Which test(s) are failing**:
* `UpgradeTest`
* `[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]`
* `[sig-cluster-lifecycle] cluster-upgrade`

**Since when has it been failing**:
Failing since 2019-02-01

**Testgrid link**:
[https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2768](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2768)

**Reason for failure**:
```
got error exit status 127, stdout \"== Pre-Upgrade Node OS and Kubelet Versions ==\\nname: \\\"bootstrap-e2e-master\\\"...
```

**Anything else we need to know**:
Coincides with k/k commit 8ddfd4bc3 and k/test-infra 0ed3e3400.
[Diff since last passing k/k commit](https://github.com/kubernetes/kubernetes/compare/fae2376b6...8ddfd4bc3?).

cc @mortent @kacole2 @mariantalla  @smourapina

/kind failing-test
/sig testing
/sig cluster-lifecycle

**Comment by mariantalla** [comment]
Might be related, as it started failing at the same time: https://github.com/kubernetes/kubernetes/issues/73696

**Comment by justinsb** [comment]
PR to rename those functions in #73822 - hopefully a fix!

**Comment by alejandrox1** [comment]
@justinsb could you please take another look? #73822 didnt seem to clear these failing tests.

**Comment by justinsb** [comment]
@alejandrox1 I think we need to wait for build 2794

**Comment by justinsb** [comment]
Looks like this is now in much better shape - we've had some totally green runs!

Still some flakiness around some sig-network session-affinity tests, but likely unrelated to this issue (?)

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by alejandrox1** [comment]
These specific test failures have cleared up.
/close
