### ISSUE TITLE
pull-kubernetes-e2e-kubeadm-gce is broken

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#73722]
Error is as follows:
```
W0130 00:54:46.481] 2019/01/30 00:54:46 main.go:315: Something went wrong: failed to acquire k8s binaries: error during make -C /go/src/k8s.io/kubernetes bazel-release: exit status 2
```

Please see:
- https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kubeadm-gce
- https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kubeadm-gce&graph-metrics=test-duration-minutes

Looks like this started when we switched over the kubeadm jobs from sig-testing to sig-cluster-lifecycle
https://github.com/kubernetes/test-infra/compare/b0f8f2cfb...ee2861173

**Comment by dims** [comment]
/assign @krzyzacy

cc @neolit123 @timothysc

**Comment by krzyzacy** [comment]
yes still working on it - trying to move it off run_after_success since that's deprecated from Prow

**Comment by neolit123** [comment]
we are not even watching this as signal that much to be honest.
kubeadm-gce-master is the real signal (periodic).

@krzyzacy 
a difference that i see between the kubeadm-gce-master (periodic) job and this one is that the periodic has some debug output for creating the kubernetes-anywhere folder:
```
I0204 22:12:43.452] Initialized empty Git repository in /workspace/k8s.io/kubernetes-anywhere/.git/
I0204 22:12:43.453] process 75 exited with code 0 after 0.0m
I0204 22:12:43.453] Call:  git config --local user.name 'K8S Bootstrap'
I0204 22:12:43.460] process 76 exited with code 0 after 0.0m
I0204 22:12:43.460] Call:  git config --local user.email k8s_bootstrap@localhost
I0204 22:12:43.465] process 77 exited with code 0 after 0.0m
I0204 22:12:43.466] Call:  git fetch --quiet --tags https://github.com/kubernetes/kubernetes-anywhere kubeadm-e2e
```

while i cannot see the same in the logs for the pre-submit.

**Comment by krzyzacy** [comment]
sorry I'm behind on everything.. the presubmit uses podutils, so the clone log lives in places like https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/70896/pull-kubernetes-e2e-kubeadm-gce/17105/clone-log.txt

I need to bump the image and docker was gone on my mac and I ssh was messed up so I never got a chance... on it now

**Comment by krzyzacy** [comment]
@neolit123 it at least passed the build stage now - maybe you can tell me what's the actual problem? ref: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73651/pull-kubernetes-e2e-kubeadm-gce/17130

**Comment by neolit123** [comment]
all the recent runs (that are not build problems) suggest failing to fetch a kubeconfig from the GCE master.
i don't have enough information to figure out why is that happening; kubeadm-gce-master is OK in that regard.

i'm hoping that we can just remove this job this week!

**Comment by krzyzacy** [comment]
> i'm hoping that we can just remove this job this week!

🎶 in my 👂 ;-) 🤞

**Comment by dims** [comment]
💯

**Comment by neolit123** [comment]
i got permission from SIG-CL chairs to remove this.
TODO today.
