### ISSUE TITLE
PR did get /lgtm comment but not the corresponding label

### ISSUE THREAD

**Issue by casusbelli** [kubernetes/kubernetes#73736]
PR #68925 did get a /lgtm comment but not the corresponding lgtm label I'd expect. Is this a bug or is there some other requirement to be met that I'm not aware of?

**Comment by nikhita** [comment]
@casusbelli Looks like a dropped webhook (we have noticed this with GitHub sometimes).

I have added the lgtm, so it should get merged soon. :)

/close

**Comment by nikhita** [comment]
Also note that the tests will be run again once more before merging, so it might take some time.

**Comment by casusbelli** [comment]
thnx!
