### ISSUE TITLE
Cleanup IBMCloud Kubemark scripts

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kubernetes#73743]
**What would you like to be added**:
Refactor the [IBMCloud kubemark bash scripts](https://github.com/kubernetes/kubernetes/tree/master/test/kubemark/iks)

**Why is this needed**:
* The CLI tool (`bx`) used by the script [test/kubemark/iks/util.sh](https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/iks/util.sh) has been [deprecated as of May 2018](https://cloud.ibm.com/docs/cli/reference/ibmcloud/bx_cli.html#ibmcloud_cli) and replaced by `ibmcloud`.
* Other aspects such as the removal of personal image names should be addressed.

/cc @spzala
/kind cleanup
/sig ibmcloud

**Comment by Huang-Wei** [comment]
FYI: I happened to replace `bx` with `ibmcloud` in #76909.

**Comment by spzala** [comment]
@Huang-Wei thanks!

**Comment by mrbobbytables** [comment]
Thank you! 👍

**Comment by mrbobbytables** [comment]
As #76909 has been merged. I think this is safe to close :) 
If not, please reopen.
Thanks @Huang-Wei @spzala !

/close

**Comment by spzala** [comment]
> As #76909 has been merged. I think this is safe to close :)
> If not, please reopen.
> Thanks @Huang-Wei @spzala !
> 
> /close

@mrbobbytables sounds good, thank you again for bringing this issue to the sig attention!
