### ISSUE TITLE
Creating new object using kubectl --server-side apply fails

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/kubernetes#73759]
**What happened**:

When running `kubectl --server-side apply -f obj.yaml` the apiserver returns an error:
```
Error from server (NotFound): services "foo" not found
```
with obj.yaml being:
```
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  selector:
    app: foo
  ports:
  - port: 80
    targetPort: http
```

**What you expected to happen**:

The object being created if not found.

**How to reproduce it (as minimally and precisely as possible)**:

- get etcd up `third_party/etcd/etcd`
- get apiserver up `mkdir -p /tmp/certs && hack/update-bazel.sh  && bazel run  //cmd/kube-apiserver:kube-apiserver -- --port=8090 --etcd-servers="http://localhost:2379" --cert-dir="/tmp/certs" --admission-control=MutatingAdmissionWebhook,ValidatingAdmissionWebhook,AlwaysAdmit --feature-gates ServerSideApply=true`
- run kubectl apply `kubectl --server-side apply -f obj.yaml` (built from master as well)

**Anything else we need to know?**:
Everything built directly from master

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kwiesmueller** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by jennybuckley** [comment]
I think this is caused by https://github.com/kubernetes/kubernetes/issues/65925

**Comment by kwiesmueller** [comment]
Okay, thanks for looking into it @jennybuckley .
Anything I can do here?
