### ISSUE TITLE
1.11 ~ "kubectl get"  help mesaage is not listing all object types

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#73767]
Maybe this is b/c CSI was beta in v1.11 ? But it still seems like it might be a bug of not showing all objects in the help message.

**What happened**:

`kubectl get` didn't list `volumeattachment` as an object suggestion

**What you expected to happen**:

`kubectl get` should show all valid `get` targets, including beta objects, like `volumeattachment`.

**How to reproduce it (as minimally and precisely as possible)**:

Type `kubectl get` on a 1.11 + cluster.    You won't see CSI.  

**Anything else we need to know?**:

**Environment**:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
`get` no longer enumerates all resources, but suggests using `kubectl api-resources` to list all resources available on the local server

/close
