### ISSUE TITLE
Make security rules default to no access instead of 0.0.0.0/0

### ISSUE THREAD

**Issue by aaronmell** [kubernetes/kubernetes#73764]
**What would you like to be added**:
I would like to see the elb ingress for AWS changed to default to not allowing any inbound requests if it is misconfigured vs allowing all inbound requests.

**Why is this needed**:
A misconfiguration can leave you exposed without realizing it.

**Comment by d-nishi** [comment]
/assign @M00nF1sh 
/kind/feature

**Comment by M00nF1sh** [comment]
Hi,
Default secure is indeed a best practice. However, it will make our behavior inconsistent with other cloud providers.
I think it's worth a discussing in sig-aws, and sig-network for what's the desired semantic for vanilla LoadBalancer Service without configuration.
