### ISSUE TITLE
kube-proxy iptables rules mess

### ISSUE THREAD

**Issue by mylocaldevstack** [kubernetes/kubernetes#73762]
**What happened**:
I have 10 services deployed on my cluster, currently lets focus on 2 of them (call them A and B for convenience) with 2 replicas per each service.
When i'm sending http request directly from pod A.1->B.externalIP i get randomly http 200 or http 404.
When i did some digging today i found that there are messed up rules in iptables (some of them redirects to wrong service IP - lets call it C which gives me 404 obviously)
When i scale down replicas to 1 instance everything works fine, the error occurs when replicas > 1.

**What you expected to happen**:
I wanted to get proper response from service B.

**How to reproduce it (as minimally and precisely as possible)**:
install cluster using kubespray 2.8.0 with weave net, deploy metallb, configure metallb.
Deploy few restful microservices.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
  - azure vms
  - 4vcpu 8gb ram
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
`Linux node1 4.15.0-1031-azure #32~16.04.1-Ubuntu SMP Wed Oct 31 19:20:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
  - kubespray v 2.8.0 
- Others:
  - metallb 0.7.3
  - weave cni plugin

**Comment by mylocaldevstack** [comment]
1. @kubernetes/sig-network-bugs

**Comment by mylocaldevstack** [comment]
Okay, lets add a bit more data to process:

---
A is deployed on node 3 and node4 
```
ansible@node1:~$ kubectl get pods -l app=A -o wide
NAME                                       READY     STATUS    RESTARTS   AGE       IP            NODE      NOMINATED NODE
A-deployment-5ff875d444-cdrwx   1/1       Running   0          1d        10.64.13.76   node3     <none>
A-deployment-5ff875d444-jjttz   1/1       Running   0          1d        10.64.13.12   node4     <none>
```

service definition:
```
ansible@node1:~$ kubectl get svc -l app=A -o wide
NAME           TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE       SELECTOR
A   LoadBalancer   10.64.14.29   10.64.11.2    80:32094/TCP   1d        app=A,version=v0.0.209-182760-dev
```
---
B is deployed on node4 and node5
```
ansible@node1:~$ kubectl get pods -l app=B -o wide
NAME                                      READY     STATUS    RESTARTS   AGE       IP             NODE      NOMINATED NODE
B-deployment-765446c4c5-2mcr9   1/1       Running   0          3h        10.64.13.143   node5     <none>
B-deployment-765446c4c5-v9w9c   1/1       Running   0          3h        10.64.13.14    node4     <none>
```

service definition:

```
ansible@node1:~$ kubectl get svc -l app=B -o wide
NAME          TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE       SELECTOR
B   LoadBalancer   10.64.14.88   10.64.11.8    80:31762/TCP   3h        app=B,version=0.0.66-SNAPSHOT
```
---
C is deployed on node3 node4 and node5:
```
ansible@node1:~$ kubectl get pods -l app=C -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP             NODE      NOMINATED NODE
C-deployment-cf44758dd-4nzw7   1/1       Running   0          3h        10.64.13.80    node3     <none>
C-deployment-cf44758dd-5zzgh   1/1       Running   0          3h        10.64.13.11    node4     <none>
C-deployment-cf44758dd-7d4mr   1/1       Running   0          3h        10.64.13.79    node3     <none>
C-deployment-cf44758dd-8j9bc   1/1       Running   0          3h        10.64.13.78    node3     <none>
C-deployment-cf44758dd-8xlbz   1/1       Running   0          3h        10.64.13.13    node4     <none>
C-deployment-cf44758dd-hs6l9   1/1       Running   0          3h        10.64.13.7     node4     <none>
C-deployment-cf44758dd-jxlct   1/1       Running   0          3h        10.64.13.10    node4     <none>
C-deployment-cf44758dd-mghbd   1/1       Running   0          3h        10.64.13.137   node5     <none>
C-deployment-cf44758dd-mzpfk   1/1       Running   0          3h        10.64.13.77    node3     <none>
C-deployment-cf44758dd-r8xtj   1/1       Running   0          3h        10.64.13.140   node5     <none>
C-deployment-cf44758dd-wm6pd   1/1       Running   0          3h        10.64.13.141   node5     <none>
C-deployment-cf44758dd-zcvl7   1/1       Running   0          3h        10.64.13.142   node5     <none>
```

service definiton:
```
ansible@node1:~$ kubectl get svc -l app=C -o wide
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE       SELECTOR
C       LoadBalancer   10.64.14.143   10.64.11.9    80:31885/TCP   3h        app=C,version=0.0.22-SNAPSHOT
```

**Comment by mylocaldevstack** [comment]
When i do `curl` from pod `A-deployment-5ff875d444-cdrwx` to `10.64.11.8` sometimes we get our request pushed to `10.64.13.7` (`C-deployment-cf44758dd-hs6l9`)

We did some digging in `iptables -L -t nat` and found that there's a rule:

```
KUBE-MARK-MASQ  all  --  10.64.13.7           anywhere             /* default/B:http */
DNAT       tcp  --  anywhere             anywhere             /* default/B:http */ tcp to:10.64.13.7:80
```

Which obviously shows that there is some kind of mess in these rules as shown above.
For your convenience i've prepared all dumps in repository: https://github.com/mylocaldevstack/kube-proxy-iptables-issue 

feel free to investigate further because most probably i've missed something.

Anyways - I'm a bit surprised that there are rules that messes the ip addressing and redirects traffic for wrong ip.

**Comment by squeed** [comment]
what is the result of `kubectl get endpoints`?

**Comment by danwinship** [comment]
`iptables -L` doesn't provide the information in a very useful way. Can you give the output of `iptables-save` instead?

**Comment by mylocaldevstack** [comment]
I’m afraid i can’t do that because we couldn’t wait a week with with cluster that doesn’t work properly and we had to redeploy the cluster from scratch with 1.12.3. So far so good.

**Comment by danwinship** [comment]
OK, given that, there's not much chance of debugging this at this point. If someone else runs into this problem they can file a new bug.
/close
