### ISSUE TITLE
Enhancing the Downward API to expose the external IP

### ISSUE THREAD

**Issue by leuvataral** [kubernetes/kubernetes#73760]
**What would you like to be added**:
Allow setting the `type` of IP we want when we use Downward API to get the node IP.

Would look something like this:
```
- name: NODE_EXTERNAL_IP
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
      type: ExternalIP
``` 

**Why is this needed**:

This is useful when the node has different InternalIP and ExternalIP assigned and we specifically need the External IP.

This can eliminate hacks like using `curl https://ipinfo.io/ip` inside the container.

**Comment by leuvataral** [comment]
That sounds like a good option. I believe we should be able to select ExternalIP, even if InternalIP is assigned instead of preferring the internal IP. Makes things a lot easier.

**Comment by liggitt** [comment]
> I believe we should be able to select ExternalIP, even if InternalIP is assigned instead of preferring the internal IP. Makes things a lot easier.

Note that not all nodes report internal IP or external IP

**Comment by leuvataral** [comment]
Would it be ideal to set the preference? Meaning if we use `status.hostIPExternal` , External IP of the node is preferred over Internal IP?

**Comment by squeed** [comment]
For dual-stack purposes, selecing the "first" IP of any type is ultimately bound to be limiting. Do we have any precedent in the downwards API for returning multiple values.?

**Comment by leuvataral** [comment]
I agree it is very limiting. Especially when using a cloud kubernetes cluster where the InternalIP of the node is different than ExternalIP.
ExternalIP is externally accessible but InternalIP is not.

**Comment by EronWright** [comment]
This is looking like the main tracking issue for enhancing the Downward API to expose the external IP.   May I suggest a revised issue title to reflect that?

**Comment by leuvataral** [comment]
Yes, please go ahead. Thanks.

**Comment by danwinship** [comment]
> For dual-stack purposes, selecing the "first" IP of any type is ultimately bound to be limiting. Do we have any precedent in the downwards API for returning multiple values?

Yeah, it might be best to just expose all of `node.Status.Addresses`, serialized as JSON? Then if someone really needs to know the second IPv6 ExternalIP, they can find that.

But it's also goofy to add a redundant `PodStatus.Addresses` just so people can access it via the downward API, so maybe another possibility would be to let people do something like:

```
- name: NODE_ADDRESSES
  valueFrom:
    fieldRef:
      kind: Node
      fieldPath: status.addresses
```

where `kind` would default to `Pod` for backward compatibility, but this would then let kubelet expose certain data from other objects in some cases.

**Comment by MarcPow** [comment]
Is there any reason that exposure of the external-ip via the downward API is contra-indicated?  Or is it just a matter of someone putting in the PR?

**Comment by thockin** [comment]
@leuvataral @MarcPow and everyone

This is not a case of not wanting the feature or not wanting to solve the problem.  The reason this is stalled is that is complicated.

Pulling a downwardAPI value from the node is (I think) without precedent and has some real implications.  First the API gets more complex (especially if we expose anything but the whole field).  Second, there are security implications - I don't want to put kubelet in a spot where we can trick it into escalating your privileges.  What criteria governs whether a given pod is allowed to see this information or not?

There's a relatively simpler answer to this whole class of problems: run a sidecar which watches the node in question, extracts and formats the information you want, and writes it to a file in an emptyDir volume for your app to read. 

So my inclination is to close this and encourage the above.  Can someone tell me why that is not good enough?  I'm open to good debate :)

**Comment by ddurham2** [comment]
@thockin, the problem I'm seeing with sidecar (actually trying just an initContainer myself) is that your whole pod then has to run with a service account with kube API access, even though only the sidecar/initContainer should be able to query the node information.  Am I missing something?

**Comment by abonander** [comment]
> There's a relatively simpler answer to this whole class of problems: run a sidecar which watches the node in question, extracts and formats the information you want, and writes it to a file in an emptyDir volume for your app to read.

This also belies a ton of complexity and headache.

It doesn't look like there's an official OCI image for `kubectl`, so are you supposed to just try to find a third-party one you can trust? Or try to build your own with all the fun that entails, like somehow ensuring that it stays up to date?

Or are you also recommending that we construct the API requests ourselves with whatever tooling we're comfortable with? 

Either way, that doesn't sound very simple to me.

**Comment by thockin** [comment]
registry.k8s.io/kubernetes/kubectl:v1.28.0-alpha.1

**Comment by abonander** [comment]
It looks like the image literally just contains `kubectl` itself so... how am I meant to write a file to an `emptyDir` volume without something like shell redirections? `kubectl` doesn't look to have any flag to write its output to a file.

I can still think of a couple of ways to make that work, like:

* Running `kubectl proxy` as a sidecar and then querying the API either from _another_ sidecar or in the command for the main container
* Copying the `kubectl` binary to a volume and executing it from the volume in another sidecar or the main container

Neither is exactly what I'd call "simple," though of the two I'd probably choose the second option because I only need to get the node's public IP during startup, but at that point I might as well just build the `kubectl` binary into the image in the first place.

**Comment by thockin** [comment]
You're right.  It's not awesome.  I'll see what folks think about making something more utilitarian.
