### ISSUE TITLE
"Dynamic Provisioning" e2e test failed on local cluster

### ISSUE THREAD

**Issue by k-toyoda-pi** [kubernetes/kubernetes#73771]
**What happened**:
The following e2e test failed on my local cluster.
- DynamicProvisioner [Slow] [It] should provision storage with different parameters

```
- Failure [6.240 seconds]
[sig-storage] Dynamic Provisioning
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:22
  DynamicProvisioner [Slow]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:259
    should provision storage with different parameters [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:260

    Expected
        <int>: 0
    not to equal
        <int>: 0

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:1189
```
**What you expected to happen**:
My k8s node has no zone lables.
```
$ cluster/kubectl.sh describe node
Name:               127.0.0.1
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=127.0.0.1
                    kubernetes.io/os=linux
```
The test tries to get zone labels by getRandomClusterZone() at first.
It fails because of getting no zone labels.

I think that it's better to skip than fail if a k8s node does not have zone labels.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.2.359+0fdb65efa0d6c7-dirty", GitCommit:"0fdb65efa0d6c7d9ca81f6e218e97824909dc4c3", GitTreeState:"dirty", BuildDate:"2019-02-06T01:08:26Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.2.359+0fdb65efa0d6c7-dirty", GitCommit:"0fdb65efa0d6c7d9ca81f6e218e97824909dc4c3", GitTreeState:"dirty", BuildDate:"2019-02-06T01:08:26Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: local cluster using local-up-cluster.sh
- OS (e.g. from /etc/os-release): ubuntu 18.04.1
- Kernel (e.g. `uname -a`): 4.15.0-43-generic
- Install tools: 
- Others:

**Comment by oomichi** [comment]
These test depends on cloud providers as gce/gke, aws, openstack, vsphere and azure.
In addition, the other test("should create persistent volume in the zone specified in allowedTopologies of storageclass") which calls getRandomClusterZone() checks the cloud providers previously.
So this issue happens on local, then we need to add the similar check on the test before calling getRandomClusterZone().
