### ISSUE TITLE
CSI block: Why is NodePublishVolume called in SetUpDevice?

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#73773]
**What happened**:
I'm doing a retroactive review of the CSI block implementation and I have a few questions:

Why are there 4 different paths that point to the same block device?  I see:
    * [global map path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L55)
    * [staging target path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L63)
    * [publish target path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L70)
    * [pod path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L77)

This seems like an unnecessary amount of redirection. Ideally, global map path == staging target path, and publish target path == pod path.  

Along the same lines, I see that publish target path is not a per pod path and `NodeStageVolume` and `NodePublishVolume` are called in the same SetUpDevice() function. This kind of makes the `NodePublish` call useless because it's just bind mounting the volume to another global location, which is what `NodeStage` already provides. This is also different from filesystem semantics, where NodeStage/Unstage is serialized per volume, and NodePublish/Unpublish is serialized per pod.

**What you expected to happen**:
Can we simplify this and try to align with how the filesystem semantics work?  The more intermediate steps we have, the more likely one of them is going to fail. Also each additional mount consumes kernel resources, and will make operations that need to list all mounts slower.

@kubernetes/sig-storage-bugs 
/assign @mkimuram @vladimirvivien @bswartz

**Comment by mkimuram** [comment]
@msau42

Thank you for your review and filing this issue to improve CSI block implementation.

I agree the idea of reducing the complexity by directly mapping the device to the right place in CSI driver.

- For "publish target path == pod path", this could be achieved by:

1. Make [```makeBlockVolumes```](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L113) accept other than symlink,
2. Make [```MapBlockVolume```](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L900) properly handle a case that ```devicePath``` and ```podVolumeMapPath``` are the same, or just skip creating symlink.
    (In CSI, ```devicePath``` is set to ```publishPath```, so this will allow csi driver directly map ```podVolumeMapPath``` to ```publishPath```.)
3. Make "publish target path == pod path"

Also, through this change, we'd better consider replacing symlink to bind mount for idempotency.

- For "global map path == staging target path":
  ```staging_target_path``` in CSI v1.0 spec is defined as  just a directory that SP can use for any purposes, not the device. (https://github.com/container-storage-interface/spec/pull/335/commits/6620cb6ab68f8e0a91bbda82c60e2da3d59e5af5#diff-308dbd5d943fd4b49fc73f1092c253abR983 .) So, we will need to investigate more on whether just doing similar change to 2 and 3 above is good or not. Does anyone already has any knowledge on this?

**Comment by msau42** [comment]
I think it would be great if we can investigate replacing the loopback device mechanism with bind mounts for the normal in-tree Kubernetes block implementation.  I think it would simplify the code a lot and we wouldn't need this global map to do refcnting.  cc @wongma7

**Comment by wongma7** [comment]
only did some brief testing but doesn't seem like bind mounting will can prevent a device from being detached like associating a loop device can

original rationale, for discussion later: https://github.com/kubernetes/kubernetes/blob/31c6a2ba355687363ee694611148b7c67a0ae8d4/pkg/volume/util/operationexecutor/operation_generator.go#L904

**Comment by msau42** [comment]
It's not for preventing detach, but to make sure the device name (/dev/sdb) does not get reused while it is still being used by a container.

**Comment by leakingtapan** [comment]
> only did some brief testing but doesn't seem like bind mounting will can prevent a device from being detached like associating a loop device can

How did you test the case that volume got silently replaced?

**Comment by wongma7** [comment]
isn't that the same thing? If the container is using /dev/sdb, the only way /dev/sdb can get reused is if it gets detached and something gets attached in its place. (my understanding is based on the comment in the code there ^)

**Comment by wongma7** [comment]
@leakingtapan I tried losetup locally, not really meant to be an exhaustive or accurate test, just trying to understand potential issue
``` 
losetup /dev/loop6 /tmp/file1
mount --bind /dev/loop6 /tmp/bindmountfile
cat /tmp/bindmountfile # contents of file1
losetup -d /dev/loop6
cat /tmp/bindmountfile # empty
losetup /dev/loop6 /tmp/file2
cat /tmp/bindmountfile # contents of file2
```

from perspective of whoever had /dev/loop6 bindmounted contents has silently changed

**Comment by msau42** [comment]
Ah thanks for detailing the steps. I had thought that the bind mount would still keep the reference to the original device but that does not seem to be the case.

**Comment by mkimuram** [comment]
@wongma7 

Isn't the intention of ```AttachFileDevice``` something like below?
With below test, I see that /dev/loop6, or device, isn't deleted,
until /dev/loop7, or descriptor lock, is deleted.
(We should ideally test this with actual devices for supported drivers, not /dev/loop6.)

```
# losetup /dev/loop6 /tmp/file1
# mount --bind /dev/loop6 /tmp/bindmountfile
# losetup /dev/loop7 /tmp/bindmountfile
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE          DIO
/dev/loop6         0      0         0  0 /tmp/file1           0
/dev/loop7         0      0         0  0 /tmp/bindmountfile   0
# losetup -d /dev/loop6 
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE          DIO
/dev/loop6         0      0         1  0 /tmp/file1           0
/dev/loop7         0      0         0  0 /tmp/bindmountfile   0
# losetup -d /dev/loop7
# losetup 
```

**Comment by msau42** [comment]
Yes, I was asking if it's possible to remove that loopback "lock" and just use a bindmount to protect against this scenario.  But it doesn't seem possible.

**Comment by msau42** [comment]
@bswartz @mkimuram @wongma7 and I discussed this in more detail today.  Summary:

* Let's move the publish call back to MapDevice so that it is called per pod and not per volume.  This is to be consistent with how NodePublish/Stage calls work for filesystem volumes. This may also require adding UnmapDevice to the BlockVolume interface
* We may need to clarify in the CSI spec the semantics around multi access on a single node.
* We are unable to simplify the number of paths for now.  `globalMapPath` and `podPath` are needed for Kubernetes to refcnt the number of pods using the device to gate the unstage call.  The path returned by `nodeStageVolume` is not actually a device, it's a directory where a plugin keeps information about the device.
* It's a little odd that the Kubernetes refcnting mechanism is exposed into the plugin. Maybe that can be cleaned up later.

**Comment by gnufied** [comment]
> Let's move the publish call back to MapDevice so that it is called per pod and not per volume. This is to be consistent with how NodePublish/Stage calls work for filesystem volumes. This may also require adding UnmapDevice to the BlockVolume interface

I tend to agree but this also means that `SetupDevice` call will do `NodeStage` and also create pod volume symlink (which is currently done in `MapDevice`). This would also mean that `MapDevice` will do `NodePublish` and create volume level symlink. If we take this route - CSI will be an exception and all the other plugins will create both pod and volume links in `MapDevice` call. I am not sure I like that. 

Currently `SetupDevice` is a no-op for most in-tree volume types. We could change the code to create pod global symlinks and keep consistent behaviour across plugins (including CSI).

**Comment by humblec** [comment]
@mkimuram it looks like https://github.com/kubernetes/kubernetes/pull/74026 was an attempt to seperate stage and publish calls for block volume which is very much required. Any particular reason to not getting this PR into completion ?

**Comment by mkimuram** [comment]
@humblec 

I re-opened it and rebased the commit. Let's continue discussion there.

@gnufied 

> Currently SetupDevice is a no-op for most in-tree volume types. We could change the code to create > pod global symlinks and keep consistent behaviour across plugins (including CSI).

#74026 is only for CSI. Let's work on this for each driver in another PR. 
(I hope that that PR covers common part of the codes for other drivers.)

**Comment by humblec** [comment]
> @humblec
> 
> I re-opened it and rebased the commit. Let's continue discussion there.


Thats awesome !! thanks @mkimuram ..

> 
> @gnufied
> 
> > Currently SetupDevice is a no-op for most in-tree volume types. We could change the code to create > pod global symlinks and keep consistent behaviour across plugins (including CSI).
> 
> #74026 is only for CSI. Let's work on this for each driver in another PR.
> (I hope that that PR covers common part of the codes for other drivers.)

Yeah, sounds good to me.

**Comment by davidz627** [comment]
Some more context based on my investigation of an issue.
https://github.com/kubernetes/kubernetes/pull/79784#issuecomment-537254635

Please look when fixing block volume issues - there are some significant issues (some may be the same already brought up in this thread)

**Comment by wongma7** [comment]
globalMapPath is used for ref-counting block volumes. It was intended to be equivalent to / modeled fater filesystem volumes' deviceMountPath. (Whoever wrote it left this: https://github.com/kubernetes/kubernetes/blob/14e5adfc85119b0fca6bed1dabfca8bc94d9f923/pkg/volume/util/operationexecutor/operation_generator.go#L1041)

Block volumes
devicePath->globalMapPath->path under pod uid dir

Filesystem
devicePath->deviceMountPath->path under pod uid dir

**Comment by msau42** [comment]
I think the CSI implementation further complicates this by adding 2 more paths to the mix.

**Comment by davidz627** [comment]
> Block volumes
> devicePath->globalMapPath->path under pod uid dir

AFAIK CSI Block Volumes is currently:
devicePath->globalMapPath
devicePath->podVolumeMapPath
devicePath->nodeStagePath->nodePublishPath
where `globalMapPath != nodeStagePath && podVolumeMapPath != nodePublishPath`

**Comment by wongma7** [comment]
Let's get it all sorted out in https://github.com/kubernetes/kubernetes/pull/74026.

My bad, globalMapPath needs to be renamed and refactored since nothing is actually "mapped" to or from there. It should be made super obvious that its only purpose is to store information about what pods are using a given volume. There should be no overlap between it and the other paths. It should not be an argument to MapDevice because in practice every plugin simply calls util.MapBlockVolume on it.

This is a TODO for me, after we merge https://github.com/kubernetes/kubernetes/pull/74026.
