### ISSUE TITLE
I can not install applications in k8s

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#73777]
I found this info on every node。and when i remove the  node.kubernetes.io/network-unavailable:NoSchedule taint。soon k8s will generate another the same taint。
what‘s going on，anyone help？
Taints:             node.kubernetes.io/network-unavailable:NoSchedule
Unschedulable:      false
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   True    Wed, 06 Feb 2019 14:24:05 +0800   Wed, 06 Feb 2019 14:24:05 +0800   NoRouteCreated               RouteController failed to create a route

**Comment by MrHohn** [comment]
Basically the RouteController failed to create a route for node, hence a `network-unavailable:NoSchedule` taint got added to the node.

You would want to investigate why the RouteController failed --- that investigation might be specific to what environment you are running on.

**Comment by andrewsykim** [comment]
@13567436138 can you provide more context on your cluster? What cloud provider is your cluster configured to use?

**Comment by 13567436138** [comment]
https://github.com/AliyunContainerService/alicloud-controller-manager
this one

**Comment by andrewsykim** [comment]
This seems like a configuration issue with your cluster and the cloud provider, I think you'll be able to get more help if you open an issue here https://github.com/kubernetes/cloud-provider-alibaba-cloud. Hope that helps, feel free to reopen this issue otherwise!
