### ISSUE TITLE
Missing Test cases

### ISSUE THREAD

**Issue by mourya007** [kubernetes/kubernetes#73776]
There are some functions in validation.go for which tests are missing.

FSGroup https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/policy/validation/validation.go#L268

SupplimentalGroup
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/policy/validation/validation.go#L287

RunAsGroup
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/policy/validation/validation.go#L236

**Comment by mourya007** [comment]
/sig auth
@liggitt @mikedanese 

I have a PR ready for this. I can push it as per the discussion.

**Comment by liggitt** [comment]
> I have a PR ready for this. I can push it as per the discussion.

sounds good, go ahead

**Comment by liggitt** [comment]
it's fine to add a test case for that. I'll go ahead and close this issue... we don't need an issue to track that.

/close
