### ISSUE TITLE
Docs for StatefulSet DNS unclear

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/kubernetes#73808]
I created a stateful set locally and was unable to resolve the DNS names for the pods in the statefulset (https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id). Then through much googling I found that you *must* define a service otherwise the DNS names aren't resolvable.

This line I think was supposed to tell me this:
```
A StatefulSet can use a Headless Service to control the domain of its Pods
```

But how I read that is that I *can* create a headless service if I want to change the domain name. My expectation was that without a headless service the DNS names would still resolve, which turned out to not be the case.

So if the service is supposed to be required (which at least in my testing and some other issues I've seen) then the docs should specifically call out that it is required.

**Comment by jacksontj** [comment]
@kubernetes/sig-docs-bugs

**Comment by mattjmcnaughton** [comment]
Hi @jacksontj !

Under the [limitations](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) section, it says "StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this service."

Thoughts on if reminding the user of that limitation in the "Stable Network Id" Section would help avoid the confusion you experienced?

I'll put out a pr with this small change and the community can decide if its helpful :)

**Comment by jacksontj** [comment]
> Under the [limitations](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) section, it says "StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this service."

I hadn't even seen that! That would definitely have saved a bunch of time

> Thoughts on if reminding the user of that limitation in the "Stable Network Id" Section would help avoid the confusion you experienced?

I definitely think it would. That first mention is basically at the top and this is much further down (page 2 vs page 6).

**Comment by mattjmcnaughton** [comment]
Ok cool! Hopefully my pr will help :)

**Comment by mattjmcnaughton** [comment]
A documentation fix has been merged up in https://github.com/kubernetes/website/pull/12564, so I think we can close this issue.

**Comment by jacksontj** [comment]
I see the change merged in that PR, but I don't see it updated on the website. Whats the release cadence for the docs website?

**Comment by jacksontj** [comment]
Agreed, thanks for getting that change in!
