### ISSUE TITLE
Debug symbols are being obfuscated irrespective of extra GOGCFLAGS set 

### ISSUE THREAD

**Issue by icanhazbroccoli** [kubernetes/kubernetes#73814]
**What happened**:
While building a kube-apiserver component from the sources using make, I noticed the output binary is still stripped, even though I put in the suggested GC flags.
The command I'm running is:
```bash
$ make all WHAT=cmd/kube-apiserver GOGCFLAGS="-N -l"
```

```bash
$ file _output/bin/kube-apiserver
_output/bin/kube-apiserver: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

The motivation is to get a debug version of a component which is recognisable by delve/gdb.

**What you expected to happen**:
I expected to get a non-stripped binary.

**How to reproduce it (as minimally and precisely as possible)**:

Run make and inspect the `file` command output:
```bash
$ make all WHAT=cmd/kube-apiserver GOGCFLAGS="-N -l"
$ file _output/bin/kube-apiserver
```

**Anything else we need to know?**:

I discovered this file: hack/lib/golang.sh, where debug obfuscation and inlining are hardcoded to on:
```bash
goldflags="${GOLDFLAGS:-} -s -w $(kube::version::ldflags)"
gogcflags="${GOGCFLAGS:-} -trimpath=${KUBE_ROOT}"
```
LD flags -s -w and GC flag -trimpath are producing an optimised inlined binary.

Applying this dummy workaround solved my problem: https://gist.github.com/icanhazbroccoli/e98a353284b723815131eb6804fbb33e

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD@fcb0d60d4c8
- Cloud provider or hardware configuration: microk8s
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`): Linux 3.10.0-862.14.4.el7.x86_64
- Install tools:
- Others:

**Comment by neolit123** [comment]
cc @dims @cblecker 
as per: https://github.com/kubernetes/kubernetes/commit/d9cfd77149bc84fe755b68794528e7d7cb114d1a

**Comment by dims** [comment]
@neolit123 @icanhazbroccoli please see https://github.com/kubernetes/kubernetes/pull/70276

**Comment by cblecker** [comment]
This should be fixed if you use the options: `GOGCFLAGS="-N -l" GOLDFLAGS=""`.

We're going to use https://github.com/kubernetes/kubernetes/issues/77527 to track getting the docs updated.

/close

**Comment by liangwang1985** [comment]
vi  hack/lib/golang.sh
change form:  goldflags="${GOLDFLAGS:-}  -s -w $(kube::version::ldflags)”
to:  goldflags="${GOLDFLAGS:-}  $(kube::version::ldflags)”
then build with flag : make  GOGCFLAGS="-N -l”
after this gdb is ok!

**Comment by dims** [comment]
@liangwang1985 please see https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile#L81-L85
