### ISSUE TITLE
Proxy protocol With AWS ELB is not working

### ISSUE THREAD

**Issue by itskarthikholla** [kubernetes/kubernetes#73810]
**What happened**:
Proxy Protocol is enabled on AWS ELB using **service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"**  on EKS Cluster but Client IP is not preserved by proxy protocol

**What you expected to happen**:
Client IP should be preserved by Proxy Protocol. 

**How to reproduce it (as minimally and precisely as possible)**:

1. On EKS create a deployment. ( Basically my app uses port 4334)
2. Create a classic LoadBalancer with Proxy protocol enabled using **service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"** for container port 4334 and load balancer listener port 4334.
3. Try to connect to app using Loadbalancer listener 4334.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release):AMI 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
LoadBalancer config
"LoadBalancerDescriptions": [
    {
        "Subnets": [
            "subnet-1",
            "subnet-2",
            "subnet-2"
        ],
        "CanonicalHostedZoneNameID": "******",
        "CanonicalHostedZoneName": "*************",
        "ListenerDescriptions": [
            {
                "Listener": {
                    "InstancePort": 31431,
                    "LoadBalancerPort": 4334,
                    "Protocol": "TCP",
                    "InstanceProtocol": "TCP"
                },
                "PolicyNames": []
            }
        ],
        "HealthCheck": {
            "HealthyThreshold": 2,
            "Interval": 10,
            "Target": "TCP:31499",
            "Timeout": 5,
            "UnhealthyThreshold": 6
        },
        "VPCId": "vpc-***********",
        "BackendServerDescriptions": [
            {
                "InstancePort": 31431,
                "PolicyNames": [
                    "k8s-proxyprotocol-enabled"
                ]
            }
        ],
        "Instances": [
            {
                "InstanceId": "i-085ece5ecf"
            },
            {
                "InstanceId": "i-0b4741cf"
            },
            {
                "InstanceId": "i-03aea99"
            }
        ],
        "DNSName": "***************************",
        "SecurityGroups": [
            "sg-********"
        ],
        "Policies": {
            "LBCookieStickinessPolicies": [],
            "AppCookieStickinessPolicies": [],
            "OtherPolicies": [
                "k8s-proxyprotocol-enabled"
            ]
        },
        "LoadBalancerName": "a1df476de2aa011e9aabe0af927e6700",
        "CreatedTime": "2019-02-07T06:18:01.020Z",
        "AvailabilityZones": [
            "us-east-1a",
            "us-east-1b",
            "us-east-1c"
        ],
        "Scheme": "internet-facing",
        "SourceSecurityGroup": {
            "OwnerAlias": "abcd",
            "GroupName": "k8s-elb-abcd"
        }
    }
]

**Comment by itskarthikholla** [comment]
@kubernetes/sig-aws-bugs

**Comment by itskarthikholla** [comment]
>

**Comment by itskarthikholla** [comment]
I have one more doubt , as part of load balancer creation we got a policy '**k8s-proxyprotocol-enabled**'. It is applied only on  **BackendServerDescriptions** . In ***ListenerDescriptions** for LoadBalancer port is this policy should be applied? Correct me if I am wrong.  I tried to apply the same on ***ListenerDescriptions**  using aws-cli it was failing with the below error message.  


aws elb **set-load-balancer-policies-of-listener** --load-balancer-name name --load-balancer-port 4334 --policy-names **k8s-proxyprotocol-enabled** --region us-east-1


**An error occurred (InvalidConfigurationRequest) when calling the SetLoadBalancerPoliciesOfListener operation: k8s-proxyprotocol-enabled cannot be enabled**

**Comment by jverce** [comment]
Hello @itskarthikholla,

Can you provide information about your testing method? I wasn't able to reproduce your error.

Here's how I tested myself:

1. Resources file (`lb-echo.yml`):
```yaml
apiVersion: v1
kind: Service
metadata:
  name: source-ip-app
  labels:
    app: source-ip-app
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: source-ip-app
```
2. Commands to spin up the container and load balancer:
```bash
$ kubectl run source-ip-app --image=k8s.gcr.io/echoserver:1.4
deployment.apps/source-ip-app created
$ kubectl apply -f lb-echo.yml
```
3. Check out logs in container (note: stuff like `A.A.A.A` are actually IP addresses):
```bash
$ kubectl attach pod/source-ip-app-5ddb496674-2rrf4
172.31.31.129 - - [27/Feb/2019:20:05:43 +0000] "PROXY TCP4 A.A.A.A B.B.B.B 21662 80" 400 173 "-" "-"
172.31.37.110 - - [27/Feb/2019:20:05:44 +0000] "PROXY TCP4 A.A.A.A E.E.E.E 8725 80" 400 173 "-" "-"
172.31.31.129 - - [27/Feb/2019:20:05:45 +0000] "PROXY TCP4 C.C.C.C B.B.B.B 25095 80" 400 173 "-" "-"
172.31.9.219 - - [27/Feb/2019:20:05:46 +0000] "PROXY TCP4 A.A.A.A D.D.D.D 1617 80" 400 173 "-" "-"
172.31.31.129 - - [27/Feb/2019:20:05:47 +0000] "PROXY TCP4 A.A.A.A B.B.B.B 27755 80" 400 173 "-" "-"
172.31.37.110 - - [27/Feb/2019:20:05:48 +0000] "PROXY TCP4 A.A.A.A E.E.E.E 31477 80" 400 173 "-" "-"
```
4. Removing line `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"` resources file causes the following change in the logs:
```
172.31.31.129 - - [27/Feb/2019:20:05:54 +0000] "GET / HTTP/1.1" 200 505 "-" "curl/7.47.0"
172.31.37.110 - - [27/Feb/2019:20:05:55 +0000] "GET / HTTP/1.1" 200 505 "-" "curl/7.47.0"
172.31.9.219 - - [27/Feb/2019:20:05:56 +0000] "GET / HTTP/1.1" 200 504 "-" "curl/7.47.0"
172.31.31.129 - - [27/Feb/2019:20:05:57 +0000] "GET / HTTP/1.1" 200 505 "-" "curl/7.47.0"
172.31.37.110 - - [27/Feb/2019:20:05:59 +0000] "GET / HTTP/1.1" 200 505 "-" "curl/7.47.0"
172.31.9.219 - - [27/Feb/2019:20:06:00 +0000] "GET / HTTP/1.1" 200 504 "-" "curl/7.47.0"
```

**Comment by jverce** [comment]
BTW my ELB description looks very similar to yours:
```json
{
    "LoadBalancerDescriptions": [
        {
            "LoadBalancerName": "xyz",
            "DNSName": "xyz-123.us-west-2.elb.amazonaws.com",
            "CanonicalHostedZoneName": "xyz-123.us-west-2.elb.amazonaws.com",
            "CanonicalHostedZoneNameID": "abc",
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "Protocol": "TCP",
                        "LoadBalancerPort": 80,
                        "InstanceProtocol": "TCP",
                        "InstancePort": 30427
                    },
                    "PolicyNames": []
                }
            ],
            "Policies": {
                "AppCookieStickinessPolicies": [],
                "LBCookieStickinessPolicies": [],
                "OtherPolicies": [
                    "k8s-proxyprotocol-enabled"
                ]
            },
            "BackendServerDescriptions": [
                {
                    "InstancePort": 30427,
                    "PolicyNames": [
                        "k8s-proxyprotocol-enabled"
                    ]
                }
            ],
            "AvailabilityZones": [
                "us-west-2a",
                "us-west-2b",
                "us-west-2c"
            ],
            "Subnets": [
                "subnet-1",
                "subnet-2",
                "subnet-3"
            ],
            "VPCId": "vpc-62b80c1b",
            "Instances": [
                {
                    "InstanceId": "i-1"
                },
                {
                    "InstanceId": "i-2"
                },
                {
                    "InstanceId": "i-3"
                }
            ],
            "HealthCheck": {
                "Target": "TCP:30427",
                "Interval": 10,
                "Timeout": 5,
                "UnhealthyThreshold": 6,
                "HealthyThreshold": 2
            },
            "SourceSecurityGroup": {
                "OwnerAlias": "456",
                "GroupName": "k8s-elb-xyz"
            },
            "SecurityGroups": [
                "sg-1"
            ],
            "CreatedTime": "2019-02-16T01:59:27.230Z",
            "Scheme": "internet-facing"
        }
    ]
}
```

**Comment by d-nishi** [comment]
/close as @itskarthikholla did not respond.

Please refer to this issue and reopen if you face the same issue.

**Comment by a-shink** [comment]
@jverce Try to add annotation for NLB type balancer. Modified lb-echo.yml:
`
apiVersion: v1
kind: Service
metadata:
  name: source-ip-app
  labels:
    app: source-ip-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: source-ip-app
`

**Comment by jeremykerr-sp** [comment]
> @jverce Try to add annotation for NLB type balancer. Modified lb-echo.yml:
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   name: source-ip-app
>   labels:
>     app: source-ip-app
>   annotations:
>     service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
>     service.beta.kubernetes.io/aws-load-balancer-type: nlb
> spec:
>   type: LoadBalancer
>   ports:
>   - port: 80
>     targetPort: 8080
>     protocol: TCP
>   selector:
>     run: source-ip-app
> ```
> 
> Then I see mixed logs:
> 10.0.1.154 - - [19/Jul/2019:09:09:05 +0000] "PROXY TCP4 10.0.6.216 10.0.6.216 35882 31869" 400 173 "-" "-"
> 10.0.1.179 - - [19/Jul/2019:09:09:05 +0000] "PROXY TCP4 10.0.6.216 10.0.6.216 57406 31869" 400 173 "-" "-"
> 10.0.1.210 - - [19/Jul/2019:09:18:03 +0000] "GET / HTTP/1.1" 200 886 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
> 10.0.1.210 - - [19/Jul/2019:09:18:04 +0000] "GET /favicon.ico HTTP/1.1" 200 896 "http://a853b3619aa0511e99e410acc42fcbf1-9d21f867aaee8570.elb.us-east-2.amazonaws.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
> 
> Looks like Proxy does not works from NLB?

I'm seeing the same issue

**Comment by nigeisel** [comment]
I still have the same issue. Are there any updates on this?
