### ISSUE TITLE
kops configuration fails due to invalid credentials

### ISSUE THREAD

**Issue by code-sleuth** [kubernetes/kubernetes#73815]
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-cli-master#aws

**Which test(s) are failing**:
Up

**Since when has it been failing**:
02/02/19 09:07

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-cli-master#aws

**Reason for failure**:
Invalid aws credentials

**Anything else we need to know**:
/kind failing-test

**Comment by zetaab** [comment]
this is duplicate https://github.com/kubernetes/kubernetes/issues/73444#issuecomment-461381067
