### ISSUE TITLE
kubectl wait outputs NotFound error when condition is delete 

### ISSUE THREAD

**Issue by amente** [kubernetes/kubernetes#73832]
**What happened**:
When running the command:

 `kubectl wait deployment/tiller-deploy --for=delete` 

 It waits until the condition is met, and then outputs:

Error from server (NotFound): deployments.extensions "tiller-deploy" not found

**What you expected to happen**:

Since this is a successful case for 'delete' condition. It should output something like:

`deployment.extensions/tiller-deploy delete condition met`

**How to reproduce it (as minimally and precisely as possible)**:
Run the wait command with `--for=delete` after a resource has been deleted

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Zyqsempai** [comment]
So let me get it right, you are trying to put wait condition on already deleted resource?

**Comment by amente** [comment]
@Zyqsempai yes. I run the command 

`kubectl delete deployment tiller-deploy`

Then, I want to wait until the deployment is deleted, using 

`kubectl wait deployment/tiller-deploy --for=delete`

I assume waiting on a deleted resource is a condition that `kubectl wait <resource> --for=delete` supports. But the issue here, the error output when the condition is met wasn't something I was expecting. This seems to me a special case that should be handled in the fix for:  https://github.com/kubernetes/kubernetes/issues/66456

**Comment by Zyqsempai** [comment]
Got it, i will take a look.
