### ISSUE TITLE
Allow use of encrypted secrets

### ISSUE THREAD

**Issue by nhooyr** [kubernetes/kubernetes#73838]
See #28538

> If secret contents could be encrypted/decrypted by an encryption provider plugin (e.g., KMS on AWS) running in the kube master or in kubelets (though the kubelet option may require more complex IAM setup), then it would be acceptable to check in secret manifests into source control.

Helm supports this via https://github.com/futuresimple/helm-secrets

**Comment by nhooyr** [comment]
I have no idea what a sig label is.

**Comment by nhooyr** [comment]
I guess the solution here is to just use helm if you want this feature?

**Comment by mourya007** [comment]
@immutableT Are you working on this issue ?

**Comment by immutableT** [comment]
Yes, I will be submitting a proposal (hopefully next week).

**Comment by mourya007** [comment]
> Yes, I will be submitting a proposal (hopefully next week).

Thanks for the reply, Let me know If I can give helpful hand on this.

**Comment by mourya007** [comment]
> Yes, I will be submitting a proposal (hopefully next week).

Hi, Still working on it ?

**Comment by immutableT** [comment]
Yes, still working on this.
