### ISSUE TITLE
Moving from master slave architechture to peer-peer

### ISSUE THREAD

**Issue by vikashiscoder** [kubernetes/kubernetes#73841]
As the load of the controller increases it will not scale in a master slave setup of the clusters.
In case of peer to peer all nodes can respond as masters increasing the scaling capacity.

**Comment by neolit123** [comment]
please provide more detail about the feature you request.

/kind feature
/sig architecture

**Comment by vikashgupta01** [comment]
The master is the unified endpoint for the cluster. Single "source of truth" for the entire cluster. As load increases the capacity of master is exhausted. Also might lead to single point of failure.

Suggesting movement to peer 2 peer architecture.
When moving to peer to peer architecture, there is more scaling and no single point of failure. No single node or process is master. All can serve the requests based on their availability. More advantages can be added with implementation of gossip protocol in turn increasing the maintainability of nodes.

**Comment by vikashiscoder** [comment]
The master is the unified endpoint for the cluster. Single "source of truth" for the entire cluster. As load increases the capacity of master is exhausted. Also might lead to single point of failure.

When moving to peer to peer architecture, there is more scaling and no single point of failure. No single node or process is master. All can serve the requests based on their availability. More advantages can be added with implementation of gossip protocol in turn increasing the maintainability of nodes.

**Comment by bgrant0607** [comment]
@vikashiscoder Thanks for the suggestion, but you are essentially requesting a full system redesign, which is not feasible. The peer-to-peer architecture was considered and we decided against it, for a number of reasons. If you have specific scalability challenges, please file more specific issues with the details.
