### ISSUE TITLE
Node status should include allocated resources info through the API

### ISSUE THREAD

**Issue by jobevers** [kubernetes/kubernetes#73856]
I can't re-open #27404 and it looks like it closed without any resolution. This seems like useful data to have available.

**Comment by ogirardot** [comment]
+1

**Comment by cgagnaire** [comment]
Hi,
We would definitly like to have the "allocated pods and resources" informations in the  `/api/v1/nodes/<node>/status` endpoint as it is the main informations missing, with the _Unschedulable_ boolean, compared to the `kubectl describe nodes`.
Information we can also find in the dashboard : 
![image](https://user-images.githubusercontent.com/23257354/53258609-58f29800-36cd-11e9-897d-8b0be02b6143.png)
Thanks you!

**Comment by ramkrisharies** [comment]
Hai,
I need to get the node allocated Resource Details using API
can anyone help me with this
Thanks in Advance
Ram

**Comment by SGrondin** [comment]
I didn't want to parse "describe" output or make one call per pod, so I wrote something in awk. I hope it's useful, enjoy!
```awk
kubectl get pods --no-headers --all-namespaces \
  -o=custom-columns="NODE:.spec.nodeName,POD:.metadata.name,NAMESPACE:.metadata.namespace,CPUREQ:.spec.containers[*].resources.requests.cpu" \
| awk '
  $4 != "<none>" {
    split($4, requests, ",")
    for (i in requests) {
      if (substr(requests[i], length(requests[i])) != "m") {
        print "Error processing\n" $0
        exit 1
      } else {
        acc[$1] += substr(requests[i], 0, length(requests[i]) - 1)
      }
    }
  }
  END {
    for (i in acc) {
      print i "\t" acc[i]
    }
  }
'
```
Output:
```
my-node-aaaa	2894
my-node-bbbb	3271
my-node-cccc	3339
my-node-dddd	2851
my-node-eeee	3081
```
Comparison with `kubectl describe node my-node-aaaa`:
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                   Requests         Limits
  --------                   --------         ------
  cpu                        2894m (73%)      1066m (27%)
  memory                     3882560Ki (30%)  9248320Ki (72%)
```

**Comment by so0k** [comment]
@SGrondin  - thank you for sharing, any suggestion on how to get the percentage of total allocatable by having it collated with 

```
k get no -o=custom-columns="NODE:.metadata.name,ALLOCATABLE:.status.allocatable.cpu"
```

**Comment by prasadjjoshi** [comment]
I created this script which parses 'kubectl describe nodes' & output the CPU/memory stats in a json since I needed it badly. This script can also be used with other automation code.
https://github.com/prasadjjoshi/k8-utils
Feel free to use it.
