### ISSUE TITLE
[Failing test] Kubeadm fails to dump cluster logs

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#73855]
**Which jobs are failing**:
* [sig-release-master-blocking#kubeadm-gce-stable-on-master](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-stable-on-master)
* [sig-release-master-blocking#kubeadm-gce-master](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-master)

**Which test(s) are failing**:
* [DumpClusterLogs](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-stable-on-master/5472)

**Since when has it been failing**:
Around 18:55, 2/5. The failures seem to coincide with changes on test-infra , see [diff](https://github.com/kubernetes/test-infra/compare/3575681ec...335caa0b1).

**Testgrid link**:
* [https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-stable-on-master](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-stable-on-master) 

**Reason for failure**:
```
subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', 
'--deployment=kubernetes-anywhere', '--provider=skeleton', '--cluster=e2e-5472-4a39f', '--gcp-network=e2e-5472-4a39f', '--extract=release/stable', '--gcp-zone=us-west1-b', 
'--kubernetes-anywhere-kubelet-version=stable', '--kubernetes-anywhere-kubernetes-version=stable', '--test_args=--ginkgo.focus=\\[Conformance\\]|\\[Feature:BootstrapTokens\\]|\\[Feature:NodeAuthorizer\\] --minStartupPods=8', 
'--timeout=300m', '--kubernetes-anywhere-path=/workspace/k8s.io/kubernetes-anywhere', '--kubernetes-anywhere-phase2-provider=kubeadm', 
'--kubernetes-anywhere-cluster=e2e-5472-4a39f', '--kubernetes-anywhere-kubeadm-version=gs://kubernetes-release-dev/ci/v1.14.0-alpha.2.365+0dfbbc290cce9d-bazel/bin/linux/amd64/')' returned non-zero exit status 1
```

cc @mortent @kacole2 @mariantalla @smourapina

/kind failing-test
/sig cluster-lifecycle

**Comment by neolit123** [comment]
> Kubeadm fails to dump cluster logs

this part is partially fixed now:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master

except other problems remain.

/assign
/area kubeadm

**Comment by neolit123** [comment]
the dump cluster logs part is green.
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-stable-on-master
is red because it needs a test-infra update (kubekins). possibly open a separate issue and assign me.

/close

**Comment by mariantalla** [comment]
@neolit123 The logs dump is still failing [on the sig-release dashboard](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-stable-on-master), is a separate bump necessary for that one?

**Comment by neolit123** [comment]
yes, the `kubeadm-gce-stable-on-master` issue is a separate one.
i will now ping sig-testing to update a certain "tool" and hopefully this will be fixed too.

**Comment by neolit123** [comment]
@mariantalla `kubeadm-gce-stable-on-master` went green.
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-stable-on-master
