### ISSUE TITLE
\x00 or \0 from GetZoneKey is in controller prometheus endpoint.

### ISSUE THREAD

**Issue by Ramyak** [kubernetes/kubernetes#73867]
**What happened**:
Controller's prometheus endpoint has \0.
```
node_collector_evictions_number{zone="us-east-1:^@:us-east-1a"} 1
node_collector_evictions_number{zone="us-east-1:^@:us-east-1b"} 3
node_collector_evictions_number{zone="us-east-1:^@:us-east-1e"} 4
# HELP node_collector_unhealthy_nodes_in_zone Gauge measuring number of not Ready Nodes per zones.
# TYPE node_collector_unhealthy_nodes_in_zone gauge
node_collector_unhealthy_nodes_in_zone{zone="us-east-1:^@:us-east-1a"} 0
node_collector_unhealthy_nodes_in_zone{zone="us-east-1:^@:us-east-1b"} 0
node_collector_unhealthy_nodes_in_zone{zone="us-east-1:^@:us-east-1e"} 0
# HELP node_collector_zone_health Gauge measuring percentage of healthy nodes per zone.
# TYPE node_collector_zone_health gauge
node_collector_zone_health{zone="us-east-1:^@:us-east-1a"} 100
node_collector_zone_health{zone="us-east-1:^@:us-east-1b"} 100
node_collector_zone_health{zone="us-east-1:^@:us-east-1e"} 100
# HELP node_collector_zone_size Gauge measuring number of registered Nodes per zones.
# TYPE node_collector_zone_size gauge
node_collector_zone_size{zone="us-east-1:^@:us-east-1a"} 383
node_collector_zone_size{zone="us-east-1:^@:us-east-1b"} 383
node_collector_zone_size{zone="us-east-1:^@:us-east-1e"} 381
```
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
That is not conformant to prometheus's allowed characters.

**What you expected to happen**:
Would be good.
`node_collector_zone_size{zone="us-east-1::us-east-1e"} 381`

**How to reproduce it (as minimally and precisely as possible)**:
curl controller's prometheus endpoint like `http://localhost:10252/metrics`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Head, `v1.10.8`

/sig cluster-lifecycle

**Comment by kow3ns** [comment]
https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/controller/nodelifecycle/metrics.go

Node metrics aren't sig apps. I think cluster lifecycle is probably the right place

**Comment by tbe** [comment]
This issue is still present today.
