### ISSUE TITLE
unable to wget example yaml files from https://kubernetes.io/docs/home/

### ISSUE THREAD

**Issue by RaviSaraswathi** [kubernetes/kubernetes#73873]
**What happened**:

- Go to https://kubernetes.io/docs/home/
- Click on any of the example yaml file link in website, it shows black in browser
-  can't download the example yaml files from website using wget as the link is not showing in browser. 

example: The page https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/ has a yaml file pods/resource/memory-request-limit.yaml. I am not able to download this using wget. It was working few days earlier!  copied to clipboard is working. 

**What you expected to happen**:
wget of any yaml file from website document directory should work. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RaviSaraswathi** [comment]
<img width="1587" alt="screen shot 2019-02-09 at 3 50 36 am" src="https://user-images.githubusercontent.com/33672117/52518770-079ecf00-2c1e-11e9-9c90-499b419ffe87.png">

**Comment by neolit123** [comment]
please open this ticket in kubernetes/website
thanks.

/close
