### ISSUE TITLE
delete apiserver pod ,cluster is down

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#73875]
I delete one apiserver pod and then It become like below.
```
NAME                                      READY   STATUS     RESTARTS   AGE
calico-kube-controllers-64cd888cd-86tn8   1/1     Running    0          69m
calico-node-759c8                         1/1     Running    0          69m
calico-node-7xqs5                         1/1     Running    0          69m
calico-node-gmkv8                         1/1     NodeLost   0          69m
calico-node-m4trm                         1/1     Running    0          69m
coredns-788d98cc7b-679z6                  1/1     Running    0          8m32s
coredns-788d98cc7b-fw495                  1/1     Running    0          68m
coredns-788d98cc7b-lmngh                  1/1     Unknown    0          68m
dns-autoscaler-66b95c57d9-ftpns           1/1     Unknown    0          68m
dns-autoscaler-66b95c57d9-whmwm           1/1     Running    0          8m32s
kube-apiserver-node1                      1/1     Unknown    0          71m
kube-apiserver-node2                      1/1     Running    0          71m
kube-controller-manager-node1             1/1     Unknown    0          71m
kube-controller-manager-node2             1/1     Running    1          71m
kube-proxy-9h478                          1/1     Running    0          69m
kube-proxy-bdqbw                          1/1     Running    0          69m
kube-proxy-nl2dl                          1/1     NodeLost   0          69m
kube-proxy-svfhf                          1/1     Running    0          69m
kube-scheduler-node1                      1/1     Unknown    0          71m
kube-scheduler-node2                      1/1     Running    1          71m
kubernetes-dashboard-5db4d9f45f-fglj5     1/1     Running    0          68m
local-volume-provisioner-4cmwt            1/1     Running    0          69m
local-volume-provisioner-4fbqs            1/1     Running    0          69m
local-volume-provisioner-qlfhr            1/1     Running    0          69m
local-volume-provisioner-vd5rb            1/1     NodeLost   0          69m
metrics-server-694898c9bc-26htl           2/2     Unknown    0          67m
metrics-server-694898c9bc-pgfwq           2/2     Running    0          8m32s
nginx-proxy-node3                         1/1     Running    0          71m
nginx-proxy-node4                         1/1     Running    0          71m
tiller-deploy-bf6884cdb-qr8pc             1/1     Running    0          68m


```

**Comment by 13567436138** [comment]
how to recover from this

**Comment by neolit123** [comment]
please reopen this ticket once you fill the issue template correctly:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/ISSUE_TEMPLATE/bug-report.md

thanks!
/close

**Comment by maicohjf** [comment]
> I delete one apiserver pod and then It become like below.
> 
> ```
> NAME                                      READY   STATUS     RESTARTS   AGE
> calico-kube-controllers-64cd888cd-86tn8   1/1     Running    0          69m
> calico-node-759c8                         1/1     Running    0          69m
> calico-node-7xqs5                         1/1     Running    0          69m
> calico-node-gmkv8                         1/1     NodeLost   0          69m
> calico-node-m4trm                         1/1     Running    0          69m
> coredns-788d98cc7b-679z6                  1/1     Running    0          8m32s
> coredns-788d98cc7b-fw495                  1/1     Running    0          68m
> coredns-788d98cc7b-lmngh                  1/1     Unknown    0          68m
> dns-autoscaler-66b95c57d9-ftpns           1/1     Unknown    0          68m
> dns-autoscaler-66b95c57d9-whmwm           1/1     Running    0          8m32s
> kube-apiserver-node1                      1/1     Unknown    0          71m
> kube-apiserver-node2                      1/1     Running    0          71m
> kube-controller-manager-node1             1/1     Unknown    0          71m
> kube-controller-manager-node2             1/1     Running    1          71m
> kube-proxy-9h478                          1/1     Running    0          69m
> kube-proxy-bdqbw                          1/1     Running    0          69m
> kube-proxy-nl2dl                          1/1     NodeLost   0          69m
> kube-proxy-svfhf                          1/1     Running    0          69m
> kube-scheduler-node1                      1/1     Unknown    0          71m
> kube-scheduler-node2                      1/1     Running    1          71m
> kubernetes-dashboard-5db4d9f45f-fglj5     1/1     Running    0          68m
> local-volume-provisioner-4cmwt            1/1     Running    0          69m
> local-volume-provisioner-4fbqs            1/1     Running    0          69m
> local-volume-provisioner-qlfhr            1/1     Running    0          69m
> local-volume-provisioner-vd5rb            1/1     NodeLost   0          69m
> metrics-server-694898c9bc-26htl           2/2     Unknown    0          67m
> metrics-server-694898c9bc-pgfwq           2/2     Running    0          8m32s
> nginx-proxy-node3                         1/1     Running    0          71m
> nginx-proxy-node4                         1/1     Running    0          71m
> tiller-deploy-bf6884cdb-qr8pc             1/1     Running    0          68m
> ```

21. 
Configure the kubelet systemd managed service, on the node labelled with name=wk8s-node-1,
to launch a Pod containing a single container of image nginx named myservice automatically. Any
spec files required should be placed in the /etc/kubernetes/manifests directory on the node.
Hints:
 You can ssh to the failed node using $ ssh wk8s-node-1
 You can assume elevated privileges on the node with the following command $ sudo -i

😂
1. 登陆到节点上
找到kubelet 的目录
/etc/kubenetes/manifests/
创建下面的yaml ，并保存在这个目录
apiVersion: v1
kind: Pod
metadata:
    name: myeservice
spec:
    containers:
    - name: myservice
       image: nginx
2. vi /etc/systemctl/system/kubelet.service
在/usr/bin/kubelete 下面第一行加入
--pod-manifest-path=/etc/kubenetes/manifests/
保存
systemctl daemon-reload
systemctl restart kubelet
docker ps | grep myservice
