### ISSUE TITLE
kubectl is getting server timeout

### ISSUE THREAD

**Issue by recrk** [kubernetes/kubernetes#73878]
I installed first ectd, kubeapiserver and kubelet using systemd service. The services are running fine and listening to all required ports.

When I run kubectl cluster-info , I get below output Kubernetes master is running at http://localhost:8080

When I run kubectl get componentstatuses, then I get below output etcd-0 Healthy {"health": "true"}

But running kubectl get nodes , I get below error Error from server (ServerTimeout): the server cannot complete the requested operation at this time, try again later (get nodes)

Can anybody help me out on this.

**Comment by tanshanshan** [comment]
maybe you can use` journalctl -fu` to get kube-apiserver and kubelet logs , wheather exists error log .
or user  `curl `to access apiserver
and paste kubernetes version info
