### ISSUE TITLE
[Failing Test] master-blocking:kubeadm-gce-master Test

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#73880]
**Which jobs are failing**:
* [master-blocking#kubeadm-gce-master](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-master)

**Which test(s) are failing**:
* [Test](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/1798)

**Since when has it been failing**:
Failing since 2/4 at 14:11. [k/k diff](https://github.com/kubernetes/kubernetes/compare/9d6ebf6c7...732cb1001) and  [k/-test-infra diff](https://github.com/kubernetes/test-infra/compare/2e7dfc3b7...6402bf485).

**Testgrid link**:
* [https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-master](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-master)

**Reason for failure**:
```
W0204 22:23:12.081] 2019/02/04 22:23:12 main.go:297: Something went wrong: encountered 1 errors: [error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true: exit status 1]
W0204 22:23:12.085] Traceback (most recent call last):
W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 764, in <module>
W0204 22:23:12.086]     main(parse_args())
W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 615, in main
W0204 22:23:12.086]     mode.start(runner_args)
W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W0204 22:23:12.086]     check_env(env, self.command, *args)
W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0204 22:23:12.087]     subprocess.check_call(cmd, env=env)
W0204 22:23:12.087]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0204 22:23:12.087]     raise CalledProcessError(retcode, cmd)
W0204 22:23:12.087] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--deployment=kubernetes-anywhere', '--provider=skeleton', '--cluster=e2e-1798-1ad8f', '--gcp-network=e2e-1798-1ad8f', '--extract=ci/latest-bazel', '--gcp-zone=us-west1-b', '--kubernetes-anywhere-kubelet-ci-version=latest-bazel', '--kubernetes-anywhere-kubernetes-version=ci-cross/latest', '--test_args=--ginkgo.focus=\\[Conformance\\]|\\[Feature:BootstrapTokens\\]|\\[Feature:NodeAuthorizer\\] --minStartupPods=8', '--timeout=300m', '--kubernetes-anywhere-path=/workspace/k8s.io/kubernetes-anywhere', '--kubernetes-anywhere-phase2-provider=kubeadm', '--kubernetes-anywhere-cluster=e2e-1798-1ad8f', '--kubernetes-anywhere-kubeadm-version=gs://kubernetes-release-dev/ci/v1.14.0-alpha.2.287+732cb10019c50e-bazel/bin/linux/amd64/')' returned non-zero exit status 1
E0204 22:23:12.100] Command failed
I0204 22:23:12.101] process 328 exited with code 1 after 10.4m
E0204 22:23:12.101] FAIL: ci-kubernetes-e2e-kubeadm-gce-master
```

cc @mortent @kacole2 @mariantalla @smourapina

/kind failing-test
/sig cluster-lifecycle

**Comment by neolit123** [comment]
this is fixed:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master
/close

**Comment by maicohjf** [comment]
> **Which jobs are failing**:
> 
> * [master-blocking#kubeadm-gce-master](https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-master)
> 
> **Which test(s) are failing**:
> 
> * [Test](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/1798)
> 
> **Since when has it been failing**:
> Failing since 2/4 at 14:11. [k/k diff](https://github.com/kubernetes/kubernetes/compare/9d6ebf6c7...732cb1001) and [k/-test-infra diff](https://github.com/kubernetes/test-infra/compare/2e7dfc3b7...6402bf485).
> 
> **Testgrid link**:
> 
> * https://testgrid.k8s.io/sig-release-master-blocking#kubeadm-gce-master
> 
> **Reason for failure**:
> 
> ```
> W0204 22:23:12.081] 2019/02/04 22:23:12 main.go:297: Something went wrong: encountered 1 errors: [error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true: exit status 1]
> W0204 22:23:12.085] Traceback (most recent call last):
> W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 764, in <module>
> W0204 22:23:12.086]     main(parse_args())
> W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 615, in main
> W0204 22:23:12.086]     mode.start(runner_args)
> W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
> W0204 22:23:12.086]     check_env(env, self.command, *args)
> W0204 22:23:12.086]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
> W0204 22:23:12.087]     subprocess.check_call(cmd, env=env)
> W0204 22:23:12.087]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
> W0204 22:23:12.087]     raise CalledProcessError(retcode, cmd)
> W0204 22:23:12.087] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--deployment=kubernetes-anywhere', '--provider=skeleton', '--cluster=e2e-1798-1ad8f', '--gcp-network=e2e-1798-1ad8f', '--extract=ci/latest-bazel', '--gcp-zone=us-west1-b', '--kubernetes-anywhere-kubelet-ci-version=latest-bazel', '--kubernetes-anywhere-kubernetes-version=ci-cross/latest', '--test_args=--ginkgo.focus=\\[Conformance\\]|\\[Feature:BootstrapTokens\\]|\\[Feature:NodeAuthorizer\\] --minStartupPods=8', '--timeout=300m', '--kubernetes-anywhere-path=/workspace/k8s.io/kubernetes-anywhere', '--kubernetes-anywhere-phase2-provider=kubeadm', '--kubernetes-anywhere-cluster=e2e-1798-1ad8f', '--kubernetes-anywhere-kubeadm-version=gs://kubernetes-release-dev/ci/v1.14.0-alpha.2.287+732cb10019c50e-bazel/bin/linux/amd64/')' returned non-zero exit status 1
> E0204 22:23:12.100] Command failed
> I0204 22:23:12.101] process 328 exited with code 1 after 10.4m
> E0204 22:23:12.101] FAIL: ci-kubernetes-e2e-kubeadm-gce-master
> ```
> cc @mortent @kacole2 @mariantalla @smourapina
> 
> /kind failing-test
> /sig cluster-lifecycle

😊
23.
Given a partially-functioning Kubenetes cluster, identify symptoms of failure on the cluster.
Determine the node, the failing service and take actions to bring up the failed service and restore
the health of the cluster. Ensure that any changes are made permanently.
The worker node in this cluster is labelled with name=bk8s-node-0
Hints:
 You can ssh to the relevant nodes using $ ssh $(NODE) where $(NODE) is one of
bk8s-master-0 or bk8s-node-0
 You can assume elevated privileges on any node in the cluster with the following command
$ sudo -i


是kube-manager-controller 没有启动启动就做完了
kubectl get cs
能看到controller manager 没有启动
登陆到master 上
systemctl start kube-manager-controller.service
# 到机器上的/etc/systemd/system 确认一下是不是这么写的
新情况：kuber.service 的manifest 路径写错了

🤣
24. 
Creae a persistent volume with name app-config of capacity 1Gi and access mode
ReadWriteOnce. The type of volume is hostPath and its location is /srv/app-config

apiVersion: v1
kind: PersistentVolume
metadata:
    name: app-config
spec:
    capacity:
       storage: 1Gi
    accessModes:
       - ReadWriteOnce
    hostPath:
       path: /srv/app-config
