### ISSUE TITLE
AWS node/instance security group - misuse of cluster tag

### ISSUE THREAD

**Issue by Benjamin-Dobell** [kubernetes/kubernetes#73906]
**What happened**:

Load balancer -> instance inbound security rules not configured on instances.

```
W0211 00:02:32.503572       1 aws.go:3627] Error opening ingress rules for the load balancer to the instances: "Multiple tagged security groups found for instance i-0ba118132440e527f; ensure only the k8s security group is tagged; the tagged groups were sg-0a47f194362fa26a4(nodes.staging.kops.snaploader.com) sg-04b52fd571603668f(ftp.nodes.staging.kops.snaploader.com) "
E0211 00:02:32.503805       1 service_controller.go:219] error processing service ingress-nginx/ingress-nginx (will retry): failed to ensure load balancer for service ingress-nginx/ingress-nginx: Multiple tagged security groups found for instance i-0ba118132440e527f; ensure only the k8s security group is tagged; the tagged groups were sg-0a47f194362fa26a4(nodes.staging.kops.snaploader.com) sg-04b52fd571603668f(ftp.nodes.staging.kops.snaploader.com)
```

**What you expected to happen**:

The instances to have their security rules configured correctly.

**How to reproduce it (as minimally and precisely as possible)**:

On AWS backed k8s cluster:

1. Create an additional security group for your instances and tag it as owned by the cluster. key=`kubernetes.io/cluster/<CLUSTER_NAME`, value=`owned`.

2. Define an ingress resource with an AWS ELB load balancer (the specifics are not important).

**Anything else we need to know?**:

The semantics for cluster tag, and its value, in particular "owned" are well defined:

```
    // ResourceLifecycleOwned is the value we use when tagging resources to indicate
    // that the resource is considered owned and managed by the cluster,
    // and in particular that the lifecycle is tied to the lifecycle of the cluster.
    ResourceLifecycleOwned = "owned"
```

i.e. we need to tag our resources such that k8s knows to clean them up when our cluster is destroyed.

However, the cloud provider is reusing the cluster tag for an unrelated purpose i.e. Determining the _primary_ security group of an instance:

https://github.com/kubernetes/kubernetes/blob/a7966022d78bce63fa8212ea2519c99f49c2570e/pkg/cloudprovider/providers/aws/aws.go#L3850

Presumably, this is a not what the tag was intended for; it appears to be semantically inaccurate to use it in this fashion. It has the unintended side-effect that we can't have k8s automatically clean up multiple security groups (that are attached to instances).

Tags are cheap; the k8s AWS provider integration should be using an additional tag to identify the _primary_ security group. This can be implemented in a backwards compatible fashion i.e. Look for the new semantically accurate "primary" tag; if it doesn't exist fall back to using the semantically inaccurate "owned" tag. 

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

AWS

- OS (e.g. from /etc/os-release):

Debian GNU/Linux 9 (stretch)

- Kernel (e.g. `uname -a`):

Linux ip-172-20-60-92 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

- Install tools:

Kops 1.11.0

**Comment by Benjamin-Dobell** [comment]
@kubernetes/sig-aws-cloud-provider-aws

**Comment by Benjamin-Dobell** [comment]
@kubernetes/sig-aws-cloud-provider-aws-bugs

**Comment by Benjamin-Dobell** [comment]
@kubernetes/sig-cloud-provider-aws-bugs

**Comment by Benjamin-Dobell** [comment]
@kubernetes/sig-aws-bugs

... _One of these days I'll work out how to tag sigs 😉_

**Comment by zetaab** [comment]
this is kops issue not k8s? so this is reported in wrong repo?

**Comment by Benjamin-Dobell** [comment]
@zetaab I've linked to the problematic code within this repository in my OP. Once the AWS cloud provider is updated to be aware of a new tag that signifies which security group is the "primary" security group, then Kops will need to be updated.

So the issue within this repository needs to be resolved first. Then I will open an issue against Kops to support the new tag. EKS will likely want to follow suit.

**Comment by Benjamin-Dobell** [comment]
Hmm, I see there's a separate AWS cloud provider repository.

I'll open the issue against it as well. Presumably the changes would need to be merged (pkg updated) here as well. So I'll leave this issue open.

**Comment by Benjamin-Dobell** [comment]
I've updated this issue to indicate that it's the "cluster tag" (`kubernetes.io/cluster/<CLUSTER_NAME>`) that's having its semantics mistreated - technically it need not be "owned" (it could be shared).

It's worth noting that the legacy cluster tag `KubernetesCluster` must also not be present.

https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/cloudprovider/providers/aws/tags.go#L133

I'd be happy to submit a PR to resolve this issue, but seems as I'm talking about introducing an additional tag I suspect there ought to be a discussion around this.

_P.S. I'll be providing updates in this repo until informed otherwise, as the other AWS cloud provider repository seems to simply be a mirror i.e. This is the correct place for this issue.

**Comment by paxatasadey** [comment]
Thanks & after adding the tag into the node security group, we found the issue as resolved. Now the cleanup (SG along with the ingress rule deletion) is happening automatically with kubectl delete -f <something.yaml>. The tag to be updated as:
Key="kubernetes.io/cluster/<Cluster Name>", Value="shared"

**Comment by Pratima** [comment]
Very much a pressing issue for us as well. It will be an issue for anyone using the [Terraform AWS EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks) since it tags the SGs by default. The cloud provider is mis-using these tags to create NLB rules and search for SGs then it needs to be fixed. Could this issue be expedited?

**Comment by montanaflynn** [comment]
I'm hitting this running on AWS EKS with a cluster created using https://github.com/weaveworks/eksctl

**Comment by mr-karan** [comment]
What's the current solution?

**Comment by paxatasadey** [comment]
Can you please share the details likebwhat you are trying and the error you
are getting?

**Comment by alexanderaucobo** [comment]
Updated to EKS-14 and now i have the same Problem.

**Comment by nemo83** [comment]
```➜  eks-playground git:(master) ✗ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.10.1"}```

```Kubernetes version
1.14
Platform version
eks.3```

And I have the same issue. Any workaround / Solution?

Thanks

**Comment by Belonias** [comment]
@nemo83 Did you find any workaround ? Today suddenly I encountered the same error

**Comment by nemo83** [comment]
> @nemo83 Did you find any workaround ? Today suddenly I encountered the same error

what are you using to create/manage the EKS cluster?

**Comment by Belonias** [comment]
@nemo83 eksctl 0.10.1 -_- ok thank you very much

**Comment by alexanderaucobo** [comment]
You need to update your ingress controller on eks 14.
Like: kubectl -n kube-system set image deployment/alb-ingress-controller server=docker.io/amazon/aws-alb-ingress-controller:v1.1.3

**Comment by Belonias** [comment]
@nemo83 your solution to downgrade eksctl worked perfect.
@alexanderaucobo I couldn't try your solution because after I downgrade and upgraded again eksctl couldn't even create a cluster

**Comment by boddumanohar** [comment]
I also see the same issue. I am also not able to create a new Service of type loadbalancer. I see this error 
```
LAST SEEN   TYPE      REASON                       OBJECT                         MESSAGE
11m         Normal    EnsuringLoadBalancer         service/elasticsearch-secure   Ensuring load balancer
22m         Warning   CreatingLoadBalancerFailed   service/elasticsearch-secure   Error creating load balancer (will retry): failed to ensure load balancer for service api-metrics/elasticsearch-secure: Multiple untagged security groups found for instance i-XXXX; ensure the k8s security group is tagged
```

**Comment by boddumanohar** [comment]
what is the tag that this `tag` that kubernetes is looking for?

**Comment by paxatasadey** [comment]
> what is the tag that this `tag` that kubernetes is looking for?

The tag to be updated for the node security group as
Key="kubernetes.io/cluster/", Value="shared"

**Comment by boddumanohar** [comment]
@paxatasadey  I've updated the node security group to the value said above, but I still get the same message in events.

**Comment by boddumanohar** [comment]
I've created the cluster using kubespray and the kubernetes version is 1.14.

**Comment by paxatasadey** [comment]
@boddumanohar .. I got your point. Actually the K8s version 1.14 only support single untagged SG per instnace. But it seems you have multiple untagged SGs per instance. Please remove the unnecessary ones or tagged those if possible. The aws.go is as bellow:
	if len(untagged) > 0 {
		// For back-compat, we will allow a single untagged SG
		if len(untagged) != 1 {
			return nil, fmt.Errorf("Multiple untagged security groups found for instance %s; ensure the k8s security group is tagged", instanceID)
		}
		return untagged[0], nil
	}

For more details you can check the full code :: https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/aws/aws.go

**Comment by dardanos** [comment]
I'm running into this issue, and after a few hours reading this issue and others, I can't figure out what's wrong. I'm going to try to give as much information as possible. Any advice is 🏅 at this moment.


**Environment**:
- Kubernetes version: 1.16
- Install tools: kops

**What happened**:
LoadBalancer is `<pending>`.
Cluster events shows:

```
Error syncing load balancer: failed to ensure load balancer: 
Multiple tagged security groups found, for instance, i-XXX; ensure only the k8s security group is tagged; the tagged groups were sg-YYY(api-elb.CLUSTER_NAME) sg-ZZZ(masters.CLUSTER_NAME) sg-OOO(nodes.CLUSTER_NAME)
```

**Some bullet points:**

* I only have one security group associated with `I-XXX`, which is `sg-OOO(nodes.CLUSTER_NAME)`. I found that `I-XXX` is an EC2 instance, so no idea why it's being mentioned in the error message.
* Each security group in the error above has the following tags
    ```
    Name              | nodes.CLUSTER_NAME.local
    KubernetesCluster | CLUSTER_NAME
    kubernetes.io/cluster/CLUSTER_NAME | owned
    ```
* Tags and security groups are created automatically, so I didn't change anything yet.
* Error is coming from [aws.go#L3930](https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/aws/aws.go#L3930) (Thanks @paxatasadey)
* Open questions:
   - Why doesn't the error mention the security group created automatically? is it because it is not associated with the instance  `I-XXX`
   - How can I point the LoadBalancer to use that security group and fix this issue? 😇 


<details>
 <summary>YAML for the Service definition</summary>

```yml
apiVersion: v1
kind: Service
metadata:
  name: in1-ambassador
  namespace: ambassador
  labels:
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/part-of: in1
    helm.sh/chart: ambassador-6.2.0
    app.kubernetes.io/instance: in1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ambassador-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN-CERTIFICATE>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/instance: in1
```
</details>

**Comment by saibaldey** [comment]
@dardanos Can you please recreate the K8s cluster once again? But before that make sure you have cleaned up everything (all SGs, Nodes, ELBs etc ) related to the K8s cluster.
The possible reasons could be some failure attempt might have created those dangling SGs.

**Comment by dardanos** [comment]
Thanks, @saibaldey, I ended up recreating the cluster, and everything started to work without problems. I'm sure it was something I did that left the cluster in an inconsistent state.

**Comment by b0nete** [comment]
I fix this problem removing "kubernetes.io/cluster/<CLUSTER_NAME>" tag in one of the security groups.
