### ISSUE TITLE
my pod cant even ping google.com

### ISSUE THREAD

**Issue by phanisowjanyavutukuri** [kubernetes/kubernetes#73957]

**Comment by phanisowjanyavutukuri** [comment]
I have followed the kubernetes-hard way to setup the cluster except the network part 
I have installed weave net cni after that my container cant even ping google.com 
but it can ping 8.8.8.8

**Comment by figo** [comment]
/close

@phanisowjanyavutukuri i am closing the issue now, this is probably a DNS setting problem,  you probably can ping 10.128.242.90 which is one of the google.com server ip.
feel free to open new issue if you can pin down issue to sig-network area.

**Comment by cedricve** [comment]
same issue, using docker desktop
