### ISSUE TITLE
Lock contention in watchcache

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#73958]
When running 5k-node clusters with high enough churn (visibly bumping churn of load test) it's possible to observe that watchcache start accumulating lag.
The problem seems to be related mostly to lock contention.

I'm treating this as an umbrella bug for now, will be pasting more information here and linking PRs with improvements to it.

**Comment by wojtek-t** [comment]
The first most obvious thing is that dispatchEvent() method is holding the lock for its whole time when it is running:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L652
However, add() methods it is calling are blocking. We obviously don't want to keep a lock while waiting for something else. Fix is coming.

**Comment by hormes** [comment]
I suggest splitting the add() to nonblockingAdd() and add() methods, then dispatch events in nonblocking way firstly to make faster watchers not be blocked by slower ones.

The pipeline of updates: store updates ->  incoming buffer of cacher -> input buffer of cacheWatcher. But the incoming buffer size of cacher is 100, which is smaller than the input buffer size of cacheWatcher (1000). When one of the watcher is blocking, we can't dispatch events to it, and the incoming buffer will be filled quickly, I suggest increasing the incoming buffer size.

**Comment by hormes** [comment]
CC @xiang90 @resouer

**Comment by wojtek-t** [comment]
> I suggest splitting the add() to nonblockingAdd() and add(), then dispatch events in nonblocking way firstly to make faster watchers not be blocked by slower ones.

This won't solve the problem of lock contention - this will help only for individual event (the next event (at least in the current design) is blocked in adding the previous one for all watchers).

>  I suggest increasing the incoming buffer size.

We may consider that, but in my experiments when I bumped it by 10x it doesn't make any difference.

**Comment by hormes** [comment]
I am willing to submit a PR for that later in this week

**Comment by wojtek-t** [comment]
BTW - watch bookmarks that we're working on are also huge part of it.

There are 3 more things that come to my mind that we can improve:
- indexing for lists (at least theoretically, we may have the same index for watchcache store that we have as a trigger function in cacher)
- try to reduce critical section of watchcache::processEvent (maybe onEvent doesn't need to be called under lock, given that there is at most one processEvent in-flight) 
- try to improve GetAllEventsSinceThreadUnsafe - this is potentially allocating a lot of memory and copying a bunch of pointers, maybe we can be smarter here

But at least second point may be affected by watch bookmarks, so we should do watch bookmarks first to not collide between those two.

**Comment by wojtek-t** [comment]
Re second point - I think we can solve it even with bookmarks - see this comment: https://github.com/kubernetes/kubernetes/pull/75474/files#r273511670

**Comment by tedyu** [comment]
Clicking on the above link doesn't seem to how a particular comment - maybe the comment was marked resolved ?

**Comment by wojtek-t** [comment]
Maybe I don't know. But anyway https://github.com/kubernetes/kubernetes/pull/76702 is what I had on my mind works with the current implementation of bookmarks, but didn't work with the initial one.

**Comment by hormes** [comment]
> try to improve GetAllEventsSinceThreadUnsafe - this is potentially allocating a lot of memory and copying a bunch of pointers, maybe we can be smarter here

As we used a cyclic buffer here, we have to copy them to prevent being modified. After thinking about it, a linked block list may help to solve the problem.

**Comment by ricky1993** [comment]
Etcd move blocking watcher to victims, use a loop to send batch event to victims.
Can we move blocking watchers to victims like etcd? And we can make blocking watcher not to block dispatch events.
https://github.com/etcd-io/etcd/blob/e56e8471ec1870df699fde0bcf8d3e5bee5221be/mvcc/watchable_store.go#L91

**Comment by wojtek-t** [comment]
Based on this comment https://github.com/kubernetes/kubernetes/issues/73958#issuecomment-479522798

1) is done [i.e. we have support for indexes already]
2) is done: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L328
3) is not yet done

Though I will open a dedicated issue for that describing some idea how we can do that.
