### ISSUE TITLE
kubectl cp output: 'time stamp 2019-02-12 12:17:06 is 0.103301902 s in the future'

### ISSUE THREAD

**Issue by pk044** [kubernetes/kubernetes#73956]
**What happened**:
Copying a folder `/var/lib/pgsql/data` to a pod, e.g. postgresql-16-1-m7wjw results in the following error:
time stamp 2019-02-12 12:17:06 is 0.103301902 s in the future
**What you expected to happen**:

Successful file upload to a given pod.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl cp var/lib/pgsql/data/ myproject/postgresql-69-1-h7tln:/var/lib/pgsql/`

**Anything else we need to know?**:

perhaps this might come useful https://www.chrisnewland.com/tar-time-stamp-is-in-the-future-146

**Environment**:
```
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-02-08T23:07:29Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
VERSION_CODENAME=""
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

- Kernel (e.g. `uname -a`): 

`Linux localhost.localdomain 4.19.16-200.fc28.x86_64 #1 SMP Thu Jan 17 00:16:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by clanesf** [comment]
Ran into this as well. That and it's annoying that `kubectl cp` cannot be used to create a directory structure when copying files into a container.
