### ISSUE TITLE
Fine grained specification of CPU affinity

### ISSUE THREAD

**Issue by ahadas** [kubernetes/kubernetes#73954]
**What would you like to be added**:
Enhance CPU placement (that is currently done by CPU manager when using the static policy) to take into account CPU affinity rules between subgroups of CPUs that are assigned to a pod.

**Why is this needed**:
Seems that CPU manager with the static policy generally assumes that the closer the CPUs of a container are the better it is. However, when the container emulates a multi-socket/multi-core system, we can leverage the knowledge of the emulated topology to achieve better CPU placement.

For instance, let's say we have a node with:
1 CPU-socket with 2 CPU-cores and 2 logical-CPUs per CPU-core.
And let's say we run a container that emulates a virtual machine with the following topology:
1 CPU socket, with 2 CPU-cores and 1 logical-CPU per CPU-core.
The container requires 2 CPUs and therefore CPU manager may return 2 logical-CPUs within the same CPU-core, if such CPUs exist. But a better placement (in terms of VM performance, although it may come at the expense of running fewer workloads on the node) would be 2 logical-CPUs within different CPU-cores, when no other container runs on the node.
Had we had the ability to specify something like: "Listen, the container requires 2 CPUs but there's no requirement to have them tied up together within the same CPU-core", CPU manager could have allocated those CPUs from different CPU-cores to provide them with more CPU time.

I tried to list the affinity rules that come to my mind:
1. When a subgroup of CPUs resides within the same socket in the emulated topology, we want them to reside within the same socket on the node (to minimize cross-socket interaction).
2. When subgroups of CPUs reside within different sockets in the emulated topology, we prefer them to reside within different sockets on the node (unless there's a good argument for placing them within the same socket).
3. When a subgroup of CPUs resides within the same core in the emulated topology, we prefer them to reside within the same core on the node (unless there's a good argument for placing them within different cores).
4. When subgroups of CPUs reside within different cores in the emulated topology, we prefer them to reside within different cores on the node (unless there's a good argument for placing them within the same core).

Some initial thoughts:
* In KubeVirt, we have the emulated topology as part of the spec. We can convert it to some affinity pattern that will be processed by CPU Manager/Topology Manager.
* In this case, the logic for CPU placement within CPU Manager could be generalized to consider the affinity pattern that results from the emulated topology.

**Comment by ahadas** [comment]
@jeremyeder

**Comment by jeremyeder** [comment]
Hi @ahadas - I sent some emails connecting dots on these.  You're on them.

**Comment by ahadas** [comment]
ping
