### ISSUE TITLE
kube-proxy fails to update master IPvS vip entries during master node recycle

### ISSUE THREAD

**Issue by naemono** [kubernetes/kubernetes#73960]
**What happened**:
We regularly cycle out master nodes in our clusters for various reasons, such as security updates, version upgrades, etc.  After upgrade to 1.13.1, we are noticing that various nodes within the cluster begin to fail to be able to communicate with any master node and we've traced the issue back to ipvs having far too many master nodes within the VIP.  (we have max of 3x master nodes at any time)

From an example node
```
$ sudo ipvsadm -l -n | grep -A5 172.17.0.1:443
TCP  172.17.0.1:443 rr persistent 10800
  -> 10.0.134.254:6443            Masq    0      0          4
  -> 10.0.137.45:6443             Masq    1      0          0
  -> 10.0.144.81:6443             Masq    0      0          11
  -> 10.0.153.246:6443            Masq    1      0          0
  -> 10.0.163.20:6443             Masq    1      0          0
```

During this time, these were the 3x master nodes within the cluster:
```
m5.xlarge  	10.0.163.20	us-east-1c	running	33 minutes ago	devclus0-k8s-master
m5.xlarge  	10.0.137.45	us-east-1a	running	40 minutes ago	devclus0-k8s-master
m5.xlarge  	10.0.153.246	us-east-1b	running	25 minutes ago	devclus0-k8s-master
```

When this happens we see traffic like this in the logs

```
E0212 03:10:00.478864 1 reflector.go:205] our_app/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Pod: Get https://172.17.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 172.17.0.1:443: connect: no route to host
```

The only way we've found to recover within a reasonable time frame (1 hour or so), is to login to each node and execute a removal of the ghost entry(ies) from ipvs
`sudo ipvsadm -d -t 172.17.0.1:443 -r 10.0.144.81:6443:6443`

The automated procedure we follow to cycle the master nodes out is as follows

1. delete first node from k8s cluster via client.go `kubeClient.CoreV1().Nodes().Delete()`
2. terminate the instance within ec2 autoscale group
3. wait for new instance to come online, and be healthy within ec2, and the ec2 target group
4. wait for it to be seen as healthy within k8s `condition.Reason == "KubeletReady" && condition.Type == corev1.NodeReady`
5. repeat with next node until all 3x are cycled

**What you expected to happen**:
I would expect that the ipvs vip would be updated with the correct entries for the master nodes.

**How to reproduce it (as minimally and precisely as possible)**:
3x node masters in ec2 using autoscale group with another non-master node, and cycle out the master nodes in order using above procedure

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1"`
- Cloud provider or hardware configuration:
aws ec2
masters are `m5.xlarge`
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ip-10-0-163-20 4.4.0-1074-aws #84-Ubuntu SMP Thu Dec 6 08:57:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
client-go version
```
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"
```

**Comment by prameshj** [comment]
@m1093782566 Can you take a look?

**Comment by uablrek** [comment]
Note that the non-existing targets in ipvs has Weight=0 meaning that they should not get any new connections. (just a comment/observation)

**Comment by naemono** [comment]
This issue is just killing us.  When this occurs, everything within our clusters just begins mass failing... 

```
ubuntu@ip-10-0-169-164:~$ sudo ipvsadm -l -n | head
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
```
```
ubuntu@ip-10-0-169-164:~$ sudo ipvsadm -l -n | grep -A5 172.17.0.1:443
TCP  172.17.0.1:443 rr persistent 10800
  -> 10.0.135.125:6443            Masq    1      1          0
  -> 10.0.156.149:6443            Masq    1      0          0
  -> 10.0.156.169:6443            Masq    0      1          9
  -> 10.0.169.214:6443            Masq    0      0          462
  -> 10.0.175.12:6443             Masq    1      1          0
```

**Comment by ephur** [comment]
This issue is related to the graceful termination handling. I'm not able to determine why, but when the remote instance is terminated (say `  -> 10.0.169.214:6443            Masq    0      0          462`) the connections are never being disconnected. This is causing the graceful termination to never remove the real server. Since the real server is not removed, the connections remain. In this instance, disabling graceful termination would resolve the issue (but there does not appear to be a way to do this). I work with @naemono and thus far we're unable to determine why the connections never terminate even though the remote instance completely goes away. Presumably they will remain for 5 days until the established connections finally timeout from the conntrack table.

**Comment by naemono** [comment]
We are suspecting this may be the fix for this issue:
https://github.com/kubernetes/kubernetes/pull/71834

We are testing and will update this issue

**Comment by naemono** [comment]
It appears #71834 did fix our issue.  Closing.

**Comment by maicohjf** [comment]
> **What happened**:
> We regularly cycle out master nodes in our clusters for various reasons, such as security updates, version upgrades, etc. After upgrade to 1.13.1, we are noticing that various nodes within the cluster begin to fail to be able to communicate with any master node and we've traced the issue back to ipvs having far too many master nodes within the VIP. (we have max of 3x master nodes at any time)
> 
> From an example node
> 
> ```
> $ sudo ipvsadm -l -n | grep -A5 172.17.0.1:443
> TCP  172.17.0.1:443 rr persistent 10800
>   -> 10.0.134.254:6443            Masq    0      0          4
>   -> 10.0.137.45:6443             Masq    1      0          0
>   -> 10.0.144.81:6443             Masq    0      0          11
>   -> 10.0.153.246:6443            Masq    1      0          0
>   -> 10.0.163.20:6443             Masq    1      0          0
> ```
> During this time, these were the 3x master nodes within the cluster:
> 
> ```
> m5.xlarge  	10.0.163.20	us-east-1c	running	33 minutes ago	devclus0-k8s-master
> m5.xlarge  	10.0.137.45	us-east-1a	running	40 minutes ago	devclus0-k8s-master
> m5.xlarge  	10.0.153.246	us-east-1b	running	25 minutes ago	devclus0-k8s-master
> ```
> When this happens we see traffic like this in the logs
> 
> ```
> E0212 03:10:00.478864 1 reflector.go:205] our_app/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Pod: Get https://172.17.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 172.17.0.1:443: connect: no route to host
> ```
> The only way we've found to recover within a reasonable time frame (1 hour or so), is to login to each node and execute a removal of the ghost entry(ies) from ipvs
> `sudo ipvsadm -d -t 172.17.0.1:443 -r 10.0.144.81:6443:6443`
> 
> The automated procedure we follow to cycle the master nodes out is as follows
> 
> 1. delete first node from k8s cluster via client.go `kubeClient.CoreV1().Nodes().Delete()`
> 2. terminate the instance within ec2 autoscale group
> 3. wait for new instance to come online, and be healthy within ec2, and the ec2 target group
> 4. wait for it to be seen as healthy within k8s `condition.Reason == "KubeletReady" && condition.Type == corev1.NodeReady`
> 5. repeat with next node until all 3x are cycled
> 
> **What you expected to happen**:
> I would expect that the ipvs vip would be updated with the correct entries for the master nodes.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 3x node masters in ec2 using autoscale group with another non-master node, and cycle out the master nodes in order using above procedure
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`):
>   `Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1"`
> * Cloud provider or hardware configuration:
>   aws ec2
>   masters are `m5.xlarge`
> * OS (e.g. from /etc/os-release):
> 
> ```
> $ cat /etc/os-release
> NAME="Ubuntu"
> VERSION="16.04.5 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.5 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial
> ```
> * Kernel (e.g. `uname -a`):
> 
> ```
> $ uname -a
> Linux ip-10-0-163-20 4.4.0-1074-aws #84-Ubuntu SMP Thu Dec 6 08:57:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> ```
> * Install tools:
> * Others:
>   client-go version
> 
> ```
> [[override]]
>   name = "k8s.io/client-go"
>   version = "kubernetes-1.10.0"
> ```

20. S
A Kubernetes worker node, labelled with name=wk8s-node-0 is in state NotReady . Investigate
why this is the case, and perform any appropriate steps to bring the node to a Ready state,
ensuring that any changes are made permanent.
Hints:
 You can ssh to the failed node using $ ssh wk8s-node-0
 You can assume elevated privileges on the node with the following command $ sudo -i

😉

是kubelet 没有启动
kubectl get node
查看一个node 是notReady
ssh 上去
systemctl status kubelet
发现没有启动
systemctl start kubelet
systemctl enable kubelet
