### ISSUE TITLE
Vagrant: Support bearer tokens and client certs

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#7397]
This requires removing the nginx server that sits in front of the kube-apiserver and having the apiserver bound to port 443.

See #4007.

**Comment by roberthbailey** [comment]
@derekwaynecarr I'm pretty sure you finished this long ago, so marking as fixed. Feel free to add a link to the PR if you want to dig it up.

**Comment by derekwaynecarr** [comment]
Yes, nginx is no longer on Vagrant.  Thanks for closing.
