### ISSUE TITLE
unable to reach istio sidecar with 443

### ISSUE THREAD

**Issue by daparthi001** [kubernetes/kubernetes#73971]
cat /etc/systemd/system/kube-apiserver.service
[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota \
  --advertise-address=serverip \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/k8s-audit/audit.log \
  --audit-policy-file=/etc/kubernetes/audit-policy.yaml \
  --authorization-mode=Node,RBAC \
  --client-ca-file=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem \
  --secure-port=443 \
  --enable-swagger-ui=true \
  --etcd-cafile=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem \
  --etcd-certfile=/etc/kubernetes/kube-master.pem \
  --etcd-keyfile=/etc/kubernetes/kube-master-key.pem \
  --etcd-servers=https://url:2379 \
  --experimental-encryption-provider-config=/etc/kubernetes/etcd-encryption-config.yaml \
  --feature-gates=SupportPodPidsLimit=true \
  --kubelet-certificate-authority=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem \
  --kubelet-client-certificate=/etc/kubernetes/kube-master.pem \
  --kubelet-client-key=/etc/kubernetes/kube-master-key.pem \
  --runtime-config=api/all,settings.k8s.io/v1alpha1=true \
  --service-account-key-file=/etc/kubernetes/kube-master-sa.pem \
  --service-cluster-ip-range=192.168.0.0/16 \
  --service-node-port-range=1-60000 \
  --tls-ca-file=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem \
  --tls-cert-file=/etc/kubernetes/kube-master.pem \
  --tls-private-key-file=/etc/kubernetes/kube-master-key.pem
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

Feb 12 14:55:17  systemd[1]: Stopped Kubernetes API Server.
Feb 12 14:55:17  systemd[1]: Started Kubernetes API Server.
Feb 12 14:55:17  kube-apiserver[15538]: I0212 14:55:17.743124   15538 feature_gate.go:190] feature gates: map[SupportPodPidsLimit:true]
Feb 12 14:55:17  kube-apiserver[15538]: Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-pl
Feb 12 14:55:17  kube-apiserver[15538]: Flag --tls-ca-file has been deprecated, This flag has no effect.
Feb 12 14:55:17  kube-apiserver[15538]: I0212 14:55:17.745454   15538 server.go:135] Version: v1.10.11
Feb 12 14:55:17  kube-apiserver[15538]: I0212 14:55:17.745503   15538 server.go:724] external host was not specified, using serverip
Feb 12 14:55:18  kube-apiserver[15538]: I0212 14:55:18.289539   15538 plugins.go:149] Loaded 9 admission controller(s) successfully in the fol
Feb 12 14:55:18  kube-apiserver[15538]: I0212 14:55:18.290459   15538 plugins.go:149] Loaded 9 admission controller(s) successfully in the fol
Feb 12 14:55:18  kube-apiserver[15538]: I0212 14:55:18.312644   15538 master.go:228] Using reconciler: master-count
Feb 12 14:55:19  kube-apiserver[15538]: W0212 14:55:19.191406   15538 genericapiserver.go:342] Skipping API batch/v2alpha1 because it has no r
Feb 12 14:55:19  kube-apiserver[15538]: W0212 14:55:19.200291   15538 genericapiserver.go:342] Skipping API rbac.authorization.k8s.io/v1alpha1
Feb 12 14:55:19  kube-apiserver[15538]: W0212 14:55:19.201793   15538 genericapiserver.go:342] Skipping API storage.k8s.io/v1alpha1 because it
Feb 12 14:55:19  kube-apiserver[15538]: W0212 14:55:19.212009   15538 genericapiserver.go:342] Skipping API admissionregistration.k8s.io/v1alp
Feb 12 14:55:19  kube-apiserver[15538]: [restful] 2019/02/12 14:55:19 log.go:33: [restful/swagger] listing is available at https://
Feb 12 14:55:19  kube-apiserver[15538]: [restful] 2019/02/12 14:55:19 log.go:33: [restful/swagger] https://serverip:443/swaggerui/ is mapp
Feb 12 14:55:20  kube-apiserver[15538]: [restful] 2019/02/12 14:55:20 log.go:33: [restful/swagger] listing is available at https://
Feb 12 14:55:20  kube-apiserver[15538]: [restful] 2019/02/12 14:55:20 log.go:33: [restful/swagger] https://serverip:443/swaggerui/ is mapp
Feb 12 14:55:20  kube-apiserver[15538]: I0212 14:55:20.849173   15538 plugins.go:149] Loaded 9 admission controller(s) successfully in the fol
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.356552   15538 insecure_handler.go:121] Serving insecurely on 127.0.0.1:8080
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.357668   15538 serve.go:116] Serving securely on [::]:443
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.357718   15538 controller.go:84] Starting OpenAPI AggregationController
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.362588   15538 apiservice_controller.go:90] Starting APIServiceRegistrationController
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.362605   15538 cache.go:32] Waiting for caches to sync for APIServiceRegistrationContro
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.362629   15538 available_controller.go:262] Starting AvailableConditionController
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.362635   15538 cache.go:32] Waiting for caches to sync for AvailableConditionController
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.363225   15538 crd_finalizer.go:242] Starting CRDFinalizer
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.419654   15538 <autogenerated>:1] http: TLS handshake error from workernode:55012: EO
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.422264   15538 customresource_discovery_controller.go:174] Starting DiscoveryController
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.422301   15538 naming_controller.go:276] Starting NamingConditionController
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.423106   15538 <autogenerated>:1] http: TLS handshake error from workernode:56024: EO
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.424266   15538 crdregistration_controller.go:110] Starting crd-autoregister controller
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.424281   15538 controller_utils.go:1019] Waiting for caches to sync for crd-autoregiste
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.426546   15538 <autogenerated>:1] http: TLS handshake error from workernode:21410: EO
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.429940   15538 <autogenerated>:1] http: TLS handshake error from workernode:48199: EO
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.433362   15538 <autogenerated>:1] http: TLS handshake error from workernode:11425: EO
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.436788   15538 <autogenerated>:1] http: TLS handshake error from workernode:43552: EO
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.575582   15538 controller_utils.go:1026] Caches are synced for crd-autoregister control
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.576080   15538 cache.go:39] Caches are synced for APIServiceRegistrationController cont
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.587635   15538 autoregister_controller.go:136] Starting autoregister controller
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.587649   15538 cache.go:32] Waiting for caches to sync for autoregister controller
Feb 12 14:55:24  kube-apiserver[15538]: W0212 14:55:24.611398   15538 controller.go:242] Resetting master service "kubernetes" to &core.Servic
Feb 12 14:55:24  kube-apiserver[15538]: W0212 14:55:24.624191   15538 mastercount.go:135] Resetting endpoints for master service "kubernetes"
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.625084   15538 controller.go:537] quota admission added evaluator for: { endpoints}
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.662775   15538 cache.go:39] Caches are synced for AvailableConditionController controll
Feb 12 14:55:24  kube-apiserver[15538]: I0212 14:55:24.687809   15538 cache.go:39] Caches are synced for autoregister controller

**Comment by liggitt** [comment]
closing for lack of information

/close
