### ISSUE TITLE
PreStop process is not completed when within termination grace period

### ISSUE THREAD

**Issue by globervinodhn** [kubernetes/kubernetes#73993]
Once a DELETE API call is made to the running pod, the pod is terminated as soon as the main command finishes executing. As a result, the preStop hook does complete gracefully when the execution time is well within the termination grace period.

**What happened**:
Quoting the comment (https://github.com/kubernetes/kubernetes/issues/55807#issuecomment-459723439) from #55807,

**When** `t(ContainerProcess) < t(PreStopProcess) < t(TerminationGracePeriod)`
**Outcome:** Once container started, Pod DELETE API is requested after 16s leading to immediate preStop handler invocation. ASAP container process finishes, container is terminated without completing preStop process.
**Effective log summary scenario 2:-**

```
11:42:20.230742 ContainerProcess Started
11:42:23.940196667 ContainerProcess Creates file
11:42:36.721807 Delete API Call
11:42:36.721980 kuberuntime SIGTERM issued(Killing container)
11:42:36.787709378 PreStopProcess Started (From 'mark' file stat)
11:42:38.791633370 PreStopProcess Write to file (lastOperation. from 'mark' file stat)
11:43:13.846303794 ContainerProcess Running (lastOperation, writing to file, from 'message' file stat)
11:43:14.697992 ContainerDied (ProcessFinished/Terminated)
11:43:14.711791 runtime service fails to make RPC call on unavailable/terminated container
11:43:14.697992 Kubelet starts cleaning up resources and ensures all associated resources are removed
11:43:26.857793 DELETE API request is made again (Internal kubelet request invocation leading "pod not found" response)
```
**What you expected to happen**:
The preStop hook should be allowed to complete when the duration is within the termination grace period. It is expected that the pod should not be moved to the terminated state until and unless preStop completes or termination grace period limit is reached, whichever is earlier.

**How to reproduce it (as minimally and precisely as possible)**:
containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
     postStart:
        exec:
          command: ["/bin/sh", "-c", "touch /lifecycle/message"]
     preStop:
        exec:
           command: ["/bin/bash", "-c", "touch /lifecycle/mark && sleep 80 && echo hi > /lifecycle/mark"]
    command: ["/bin/sh", "-c", "sleep 50 && echo terminating > /lifecycle/message"]
    volumeMounts:
    - name: test-dir
      mountPath: /lifecycle
  terminationGracePeriodSeconds: 120
  restartPolicy: Never
  volumes:
  - name: test-dir
    hostPath:
     path: /home/vagrant/test
     type: Directory

**Anything else we need to know?**:
As per the analysis, it is observed that once the main command execution is completed, the pod goes into a terminated state, ensuring no time for preStop to complete. After a DELETE API call is issues, SIGTERM call and preStop hook execution are started simultaneously. Once the main command is completed, the preStop is killed abruptly and the pod is moved to terminate state. An attempt to capture and trap the SIGTERM was made, however to no avail as the behavior still remains the same.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): x86_64 GNU/Linux
- Install tools: 
- Others:

**Comment by mgdevstack** [comment]
As per https://github.com/kubernetes/kubernetes/issues/55807#issuecomment-463502568, [step-4](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace) of termination lifecycle is justifying above Scenario-2 expressing preStop runs as non-blocking wrt. to below quotes.

> It’s important to note that this happens in parallel to the preStop hook and the SIGTERM signal. **Kubernetes does not wait for the preStop hook to finish**.

> If your app finishes shutting down and exits before the terminationGracePeriod is done, Kubernetes moves to the next step immediately.

@mikedanese, If we say, preStop MUST run as blocking process then **what actual behavior of system should be expected?** (Blocking from ContainerState to be in terminated, regardless of main ContainerProcess state, once preStop is handled/started, preStop MUST run for completion leading to successful exit 0 ?)
There are `n` factors causing preStop to exit with statusCode `x` in event of either systemSignals( SIGTERM) or application level errors. **Should we not expect Blocking behavior of preStop due to such scenarios?** Addressing Blocking behavior of preStop is the only ambiguity remaining here.

**Comment by mikedanese** [comment]
> MUST run as blocking process then **what actual behavior of system should be expected?**

Within the grace period? It should not receive a sigterm. Maybe this is a bug. Can you show me the e2e test code?

**Comment by mgdevstack** [comment]
Yes, within the grace period.
>Can you show me the e2e test code?
#73780

**Comment by mgdevstack** [comment]
/close
as per
1. https://github.com/kubernetes/kubernetes/pull/73780#discussion_r257449857 
2. Detailed doc is available at https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
