### ISSUE TITLE
kubectl get pod: No resources found

### ISSUE THREAD

**Issue by ryianyang** [kubernetes/kubernetes#74005]
**What happened**:
I create deployment by a simple centos pod, the deployment can create succeed,but kubectl get pod: No resources found
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
the deployment,configmap, svc,sa etc. all can create successful and Etcd cluster is health, master 's service (apiserver,scheduler,controller-manager) are running ok

I search many solution from git or other k8s forum can help me to fix it , i hope somebody can solve it ,thx

**Environment**:
my k8s cluster version is v1.9.3

**Comment by trungnvfet** [comment]
I think you should try with --all-namespaces and/or -n <name_of_namespaces> in the kubectl command.

**Comment by ryianyang** [comment]
> I think you should try with --all-namespaces and/or -n <name_of_namespaces> in the kubectl command.

I have some operator experience on k8s , I don't make this kind of low_level mistakes. think you for your reply.

**Comment by ryianyang** [comment]
now, the  controller-manager service always  interval of a few seconds to restart

**Comment by ryianyang** [comment]
57319   47858 core.go:73] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
63368   47858 controllermanager.go:486] Error starting "node"
63399   47858 controllermanager.go:155] error starting controllers: failed to mark cidr as occupied: cidr 172.17.0.0/24 is out the range of cluster cidr 172.19.0.0/16

**Comment by ryianyang** [comment]
kube-controller-manager.service 

[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/bin/kube-controller-manager \
--address=127.0.0.1 \
--master=http://127.0.0.1:8080 \
--allocate-node-cidrs=true \
--service-cluster-ip-range=172.18.0.0/16 \
--cluster-cidr=172.19.0.0/16 \
--cluster-name=kubernetes \
--root-ca-file=/etc/kubernetes/pki/ca.pem \
--cluster-signing-cert-file=/etc/kubernetes/pki/ca.pem \
--cluster-signing-key-file=/etc/kubernetes/pki/ca-key.pem \
--service-account-private-key-file=/etc/kubernetes/pki/apiserver-key.pem \
--kubeconfig=/etc/kubernetes/controller-manager.conf \
--use-service-account-credentials=true \
--node-monitor-grace-period=40s \
--node-monitor-period=5s \
--pod-eviction-timeout=2m0s \
--allocate-node-cidrs=true \
--experimental-cluster-signing-duration=87600h \
--leader-elect=true --logtostderr=false --log-dir=/var/log/kubernetes \
--v=2
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
