### ISSUE TITLE
Can't start pods in Windows Server 2019

### ISSUE THREAD

**Issue by jwlogemann** [kubernetes/kubernetes#74019]
**What happened**:

Trying to start a container on a windows node results in an error "The container operating system does not match the host operating system."

**What you expected to happen**:

Pod should start

**How to reproduce it (as minimally and precisely as possible)**:
Try to deploy an application based on nanoserver:1809 to a node running windows server 2019 (also 1809) 

**Anything else we need to know?**:
I can run the image I'm trying to deploy directly on the node (using docker run ...) and it works fine, so the problem is not in the image, but in the interaction between Kubernetes and Windows.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.1
- Cloud provider or hardware configuration: Kubernetes is running on windows 2019 on bare metal
- OS (e.g. from /etc/os-release): Windows Server 2019
- Kernel (e.g. `uname -a`): 10.0.17763.316
- Install tools:
- Others: Docker EE 18.09.2

There's a similar issue here: https://github.com/kubernetes/kubernetes/issues/69901 but it refers to a windows update which apparently fixes this. That update has been applied (and all others as well) but the problem persists

**Comment by neolit123** [comment]
/sig windows

you can try sending a message to the SIG windows mailing list to notify about this problem:
https://github.com/kubernetes/community/tree/master/sig-windows

**Comment by jwlogemann** [comment]
> /sig windows
> 
> you can try sending a message to the SIG windows mailing list to notify about this problem:
> 
> actually you need to match your container OS and host OS.
> try that. unmatched versions are not supported!
> 
> https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#windows-server-containers
> 
> /close

Hi, 
I'm trying to run server 1809 on server 1809, which is a supported configuration. Also I can run the container by hand on the server, which indicates tis is not a docker or container issue, but a Kubernetes issue. Please reopen
