### ISSUE TITLE
Expose kube-proxy metrics on 0.0.0.0

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#74011]
**What would you like to be added**:
We'd like to change the Kube Proxy MetricsBindAddress default from 127.0.0.1 to 0.0.0.0. 

**Why is this needed**:
Currently the kube-proxy metrics are exposed by default on 127.0.0.1 interface. It makes it impossible to export kube proxy metrics to prometheus server via prometheus operator.
I've sent https://github.com/kubernetes/test-infra/pull/11281 to change the bind address in tests, but we believe that changing the default might be actually a better idea.

Other components (e.g. [kube-scheduler](https://github.com/kubernetes/kubernetes/blob/a7966022d78bce63fa8212ea2519c99f49c2570e/pkg/scheduler/apis/config/v1alpha1/defaults.go#L78)) use 0.0.0.0 as the default metrics bind address.

<br />
I'm happy to send a PR to do that, but would like to get your opinion first.

**Comment by mm4tt** [comment]
/assign @freehan 
@wojtek-t

**Comment by squeed** [comment]
+1 - one of those things I was so surprised I had to configure.

**Comment by wojtek-t** [comment]
@kubernetes/sig-network-feature-requests 

@bowei @thockin - thoughts? Is there any reason (other than historical) that it isn't exposed?

**Comment by mm4tt** [comment]
Friendly ping.

@bowei @thockin Did you have a chance to take a look?

**Comment by bowei** [comment]
I don't of any reason why it was not

CC: @freehan @MrHohn

**Comment by freehan** [comment]
I do not recall any particular reason. Maybe just because the kube-proxy metrics were rarely collected.

**Comment by MrHohn** [comment]
FYI there was a bug when configuring kube-proxy metrics bind: https://github.com/kubernetes/kubernetes/issues/53754. It was recently fixed, but cherrypicks haven't been merged:
- https://github.com/kubernetes/kubernetes/pull/72865
- https://github.com/kubernetes/kubernetes/pull/72866
- https://github.com/kubernetes/kubernetes/pull/72867

**Comment by whypro** [comment]
It was fixed by https://github.com/kubernetes/kubernetes/pull/72682

**Comment by mm4tt** [comment]
We've run into the bug you mentioned when we started overriding metrics-bind-address in tests. The kube-proxy was crashlooping in old releases due to a different flag format, see https://github.com/kubernetes/kubernetes/issues/74123

Given that people are becoming more interested in collecting kube-proxy metrics, e.g. Network Programming SLI or https://github.com/kubernetes/kubernetes/pull/74027, I think it's reasonable to expose them by default. Will send a PR shortly.

**Comment by thehackercat** [comment]
+1

**Comment by mindw** [comment]
Would [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) be a solution as well?

**Comment by aojea** [comment]
@bgvladedivac the endpoint is configurable 

> 
> --metrics-bind-address 0.0.0.0     Default: 127.0.0.1:10249
> --
>   | The IP address for the metrics server to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces)

xref: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

**Comment by bgvladedivac** [comment]
@aojea  thanks a lot :) I found out that in the prom-operator documentation, it's just not an easy catch.

**Comment by bowei** [comment]
/close 

I'm going to close this for now. Current best practice is to use the flag to configure, but not change the defaults.

**Comment by cprivite** [comment]
@bowei There is no linked PR that says we should use the flag instead. There was a linked PR that said there were some previous bugs that would have led to preferring the default to be disabled. As those bugs are disabled and literally everyone and their mother wants this exposed by default now, can we reopen this and get it enabled by default?

**Comment by bowei** [comment]
Copying link to comment from Jordan as to why this is not open by default: 

https://github.com/kubernetes/kubernetes/pull/74300#issuecomment-510906208
