### ISSUE TITLE
Rolling update rename should delete first then re-create

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#7402]
#7279 adds code that creates 2 replication controllers at the same time governing 2 sets of pods. That violates user and client expectations, and contradicts long-standing validation plans (#2210). It should delete first, then create.

**Comment by brendandburns** [comment]
I'm fine with this being an issue, but I'd summarize a little differently, since I think we should refine #2210 to allow overlap as long as the size is the same.  But regardless, when that validation is added, we should figure out what we want to do.

**Comment by bgrant0607** [comment]
Create then delete violates user and client assumptions as well as our own prior validation checks, and is incompatible with the general delete then re-create strategy that we're going to support for updating otherwise non-updatable fields, such as the object name.

**Comment by bgrant0607** [comment]
We may need to fix this sooner rather than later if the RC controller is using a map to keep track of RCs corresponding to pods.

cc @lavalamp @bprashanth

**Comment by lavalamp** [comment]
As it stands, @bprashanth's PR will (randomly) ignore all but one overlapping controller.

**Comment by bprashanth** [comment]
My rewrite will assume that the overlap case is unsupported. I have plans to add a new field to the status and set it to dormant when there's an overlap, and wake up the dormant controller when there isn't, but that will be in a follow up pr.

**Comment by bgrant0607** [comment]
controllerRef should make this change unnecessary.

cc @gmarek

**Comment by bgrant0607** [comment]
DaemonSet updates have a similar issue, which may be harder to resolve.
