### ISSUE TITLE
Can't find 'docker' in PATH when build v1.13.3

### ISSUE THREAD

**Issue by wubigo** [kubernetes/kubernetes#74046]
@kubernetes/sig-release

**What happened**:
bigo@bigo-vm1:~/go/src/k8s.io/kubernetes$ ./build/run.sh make quick-release
+++ [0214 09:29:44] Verifying Prerequisites....

PATH=/home/bigo/bin:/home/bigo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bigo/go/bin:/usr/lib/go-1.11/bin/ 

+++ [0214 09:29:46] Building Docker image kube-build:build-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:04] Keeping container kube-build-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:04] Keeping container kube-build-data-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:04] Keeping container etcd_curl
+++ [0214 09:30:04] Keeping container heuristic_allen
+++ [0214 09:30:05] Keeping container kube-build-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:05] Keeping container kube-build-data-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:05] Keeping container etcd_curl
+++ [0214 09:30:05] Keeping container heuristic_allen
+++ [0214 09:30:05] Keeping container kube-build-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:05] Keeping container kube-build-data-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:05] Keeping container etcd_curl
+++ [0214 09:30:05] Keeping container heuristic_allen
+++ [0214 09:30:06] Keeping image kube-build:build-7310fcc638-5-v1.11.5-1
+++ [0214 09:30:06] Syncing sources to container
+++ [0214 09:30:06] Stopping any currently running rsyncd container
+++ [0214 09:30:07] Starting rsyncd container
+++ [0214 09:30:15] Running rsync
+++ [0214 09:30:18] Stopping any currently running rsyncd container
+++ [0214 09:30:22] Output from this container will be rsynced out upon completion. Set KUBE_RUN_COPY_OUTPUT=n to disable.
+++ [0214 09:30:22] Running build command...
+++ [0214 09:30:28] Verifying Prerequisites....

!!! [0214 09:30:28] Can't find 'docker' in PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin whoami=, please fix and retry.

!!! [0214 09:30:28] See https://docs.docker.com/installation/#installation for installation instructions.
!!! Error in build/release.sh:34
  Error in build/release.sh:34. 'return 1' exited with status 1
Call stack:
  1: build/release.sh:34 main(...)
Exiting with status 1
Makefile:427: recipe for target 'quick-release' failed
make: *** [quick-release] Error 1
!!! [0214 09:30:30] Call tree:
!!! [0214 09:30:30]  1: ./build/../build/common.sh:518 kube::build::run_build_command_ex(...)
!!! [0214 09:30:30]  2: ./build/run.sh:39 kube::build::run_build_command(...)
!!! Error in ./build/../build/common.sh:593
  Error in ./build/../build/common.sh:593. '((i<4-1))' exited with status 2
Call stack:
  1: ./build/../build/common.sh:593 kube::build::run_build_command_ex(...)
  2: ./build/../build/common.sh:518 kube::build::run_build_command(...)
  3: ./build/run.sh:39 main(...)
Exiting with status 1

**What you expected to happen**:
build  binary into _output
**How to reproduce it (as minimally and precisely as possible)**:
git clone -b v1.13.3 https://github.com/kubernetes/kubernetes.git  $GOPATH/src/k8s.io/
cd $GOPATH/src/k8s.io/

add following line 
echo "Docker_path=$(which docker)"   (++) 
to line 264 to build/common.sh

./build/run.sh make quick-release

**Anything else we need to know?**:

 i have a working build environment for v1.11.7.   
after checkout v1.13.3 and according to [external-dependencies](https://github.com/kubernetes/kubernetes/blob/v1.13.3/CHANGELOG-1.13.md#external-dependencies)
golang  has updated from 1.10 to golang1.11

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux bigo-vm1 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
go version go1.11.5 linux/amd64

**Comment by SataQiu** [comment]
In my opinion, you can run `make quick-release` instead of `./build/run.sh make quick-release`.
```
$ git clone https://github.com/kubernetes/kubernetes
$ cd kubernetes
$ make quick-release
```

**Comment by wubigo** [comment]
@SataQiu make quick-release works
