### ISSUE TITLE
Volume resize tests are failing in multizone and alpha environment

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#74049]
Alpha environment tests are failing - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/6876

The root cause of the tests failing in alpha environment appears to be:

```
Feb 14 01:16:24.068: INFO: At 2019-02-14 01:11:31 +0000 UTC - event for deployment-535e408a-2ff5-11e9-9340-52a97e11b2fc-bd8c54665-llwhg: {kubelet bootstrap-e2e-minion-group-1cn1} FailedMount: MountVolume.resizeFileSystem update PVC status failed for volume "pvc-4f7dab2d-2ff5-11e9-95c5-42010a8a0002" : PatchPVCStatus.Failed to patch PVC "pvc-rqfkj" with persistentvolumeclaims "pvc-rqfkj" is forbidden: node "bootstrap-e2e-minion-group-1cn1" is not allowed to update fields other than status.capacity and status.conditions: 
object.ObjectMeta.ManagedFields[0].Fields.Map[f:metadata].Map[f:finalizers].Map[.].Map:
```

So basically kubelet is not allowed to update PVC. Which is weird. Need to investigate further.

Also for multizone environment - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/28052

This line looks weird from e2e:

```
FailedScheduling: 0/10 nodes are available: 1 node(s) had volume node affinity conflict, 1 node(s) were unschedulable, 8 node(s) didn't match node selector.
```

So the deployment is straight up not getting started.

/sig storage
/assign

**Comment by msau42** [comment]
For multizone failure it looks like the pod has a node selector that conflicts with the zone where the PV was provisioned

**Comment by gnufied** [comment]
I think failures on alpha cluster is related to generated api code:

```
object.ObjectMeta.ManagedFields[6]:
  a: <nil>
  b: v1.ManagedFieldsEntry{Manager:"kubelet", Operation:"Update", APIVersion:"v1", Ti...
```

Obviously none of the PVC patch code sets this stuff and yet is showing up in object diff. I am wondering why. cc @liggitt

**Comment by gnufied** [comment]
It looks like we may have to reset `ManagedField` field before comparing PVCs for admitting them as well.

**Comment by apelisse** [comment]
Yeah, server side apply has added an alpha feature to live apiserver that
allows to track ownership of fields. This is what you see in the
managedFields field. It’s automatically added when objects are modified. If
you want to compare your object against a staticly compiled expected
object, you should be emptying /setting it to nil.

**Comment by liggitt** [comment]
> If you want to compare your object against a staticly compiled expected object, you should be emptying/setting the managedField to nil.

this is the code in question:

https://github.com/kubernetes/kubernetes/blob/2b9c9154b52bdac914bf3ab37c8d349d926e6e16/plugin/pkg/admission/noderestriction/admission.go#L301-L310

Thing is, we don't actually want the kubelet taking ownership of any fields other than the one it changed. If we nil out the managed field for the comparison, that allows the kubelet to mess with managedFields in any way it wants to

**Comment by gnufied** [comment]
@apelisse can you pick this up to fix failure in alpha clusters? Reading @liggitt's last comment - it doesn't seem like a storage issue.

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by apelisse** [comment]
We don't have a good way to do what @liggitt is suggesting now, so I suspect we will have to default to ignore this field specifically when comparing (by setting it to null on both sides), at least for now.

**Comment by msau42** [comment]
@apelisse will you be able to submit a PR to fix this?

**Comment by alejandrox1** [comment]
As per https://kubernetes.slack.com/archives/C09QZFCE5/p1551884623064400
/remove-sig storage
/sig api-machinery

**Comment by apelisse** [comment]
@msau42 Sure, I'll try to send a pr this morning
