### ISSUE TITLE
HPA : GKE | HPA is not scaling pods even though the memory utilization hits the threshold value

### ISSUE THREAD

**Issue by cbharathnoor** [kubernetes/kubernetes#74056]
We have a GKE cluster (1.11) and implemented HPA based on memory utilization for pods. During our testing activity, we have observed, at times, HPA is not scaling pods even though the target value is met. We have also noticed that, HPA events is not giving us any response data ( either scaling or downscaling related info). Please find the reference screenshot mentioned below,

<img width="1439" alt="screen shot 2019-02-14 at 11 06 33 am" src="https://user-images.githubusercontent.com/45029099/52766588-a3c93b80-304d-11e9-9909-102c7df1c13b.png">

**What you expected to happen**:  Based on the defined threshold value, HPA should scale pods as soon as the resource utilization is equal to or greater than target value.

**How to reproduce it (as minimally and precisely as possible)**: Create a GKE cluster (1.11.6), deploy  pods and HPA respectively.

**Environment**: GKE
- Kubernetes version (use `kubectl version`): BLRLA00119:components cbharathnoor$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:40:58Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GKE

- Note : We are running a JAVA spring application as a docker container inside a pod.

Request you to guide us in resolving this issue. Also, let us know, if we can debug HPA implementation.

Thanks.

**Comment by hello2mao** [comment]
@cbharathnoor hi, the HPA will skip scaling if the ratio is sufficiently close to 1.0 (within a globally-configurable tolerance, from the --horizontal-pod-autoscaler-tolerance flag, which defaults to 0.1).

In your case, the ratio is 96/90=1.07 which is close to 1.0.

**Comment by cbharathnoor** [comment]
@hello2mao thanks for the details, HPA behavior looks fine.
