### ISSUE TITLE
Can't start pods in Windows Server 2019

### ISSUE THREAD

**Issue by jwlogemann** [kubernetes/kubernetes#74066]
**What happened**:
Trying to start a container on a windows node results in an error "The container operating system does not match the host operating system."

**What you expected to happen**:
Pod should start

**How to reproduce it (as minimally and precisely as possible)**:
Try to deploy an application based on nanoserver:1809 to a node running windows server 2019 (also 1809). Please note that 1809 and 1809 are matching versions, and this is a config supported by Microsoft.

**Anything else we need to know?**:
I can run the image I'm trying to deploy directly on the node (using docker run ...) and it works fine, so the problem is not in the image, but in the interaction between Kubernetes and Windows.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.1
- Cloud provider or hardware configuration:   Kubernetes is running on windows 2019 on bare metal
- OS (e.g. from /etc/os-release):  Windows Server 2019
- Kernel (e.g. `uname -a`):   10.0.17763.316
- Install tools:
- Others:  Docker EE 18.09.2

There's a similar issue here: #69901 but it refers to a windows update which apparently fixes this. That update has been applied (and all others as well) but the problem persists

I posted #74019 yesterday, but it was closed by someone who didn't read or understand the bug.

**Comment by neolit123** [comment]
thank you for the further explanation that was missing in your previous ticket:

this is odd and should not happen:
> Try to deploy an application based on nanoserver:1809 to a node running windows server 2019 (also 1809). Please note that 1809 and 1809 are matching versions, and this is a config supported by Microsoft.

as it is guaranteed by:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility#windows-server-containers

@kubernetes/sig-windows-bugs

**Comment by PatrickLang** [comment]
can you run `docker images` and post output? I think you need to check the `pause` image. If you didn't build it manually, then starting pods will fail.

**Comment by jwlogemann** [comment]
I will check this on monday, I don't have access to the server today.

**Comment by jwlogemann** [comment]
> can you run `docker images` and post output? I think you need to check the `pause` image. If you didn't build it manually, then starting pods will fail.

Output on the windows node:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> docker images
REPOSITORY                              TAG                                      IMAGE ID            CREATED             SIZE
registry.XXX.nl/dbxjml/dotnet-example   windows                                  5566e72ef5d8        2 days ago          503MB
microsoft/dotnet                        2.2-aspnetcore-runtime-nanoserver-1809   fbd2e2ad00ea        2 days ago          498MB
kubeletwin/pause                        latest                                   df50757e7311        2 days ago          1.17GB
hello-world                             latest                                   7dddd19ddc59        6 weeks ago         333MB
hello-world                             nanoserver                               7dddd19ddc59        6 weeks ago         333MB
mcr.microsoft.com/windows/nanoserver    latest                                   4c872414bf9d        4 months ago        1.17GB

Output on the linux control plane (in case you need it):
[root@CPS-NPO-RM01 ~]# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.13.1             fdb321fd30a0        2 months ago        80.2MB
k8s.gcr.io/kube-controller-manager   v1.13.1             26e6f1db2a52        2 months ago        146MB
k8s.gcr.io/kube-scheduler            v1.13.1             ab81d7360408        2 months ago        79.6MB
k8s.gcr.io/kube-apiserver            v1.13.1             40a63db91ef8        2 months ago        181MB
k8s.gcr.io/coredns                   1.2.6               f59dcacceff4        3 months ago        40MB
k8s.gcr.io/etcd                      3.2.24              3cab8e1b9802        4 months ago        220MB
hello-world                          latest              4ab4c602aa5e        5 months ago        1.84kB
quay.io/coreos/flannel               v0.10.0-amd64       f0fad859c909        12 months ago       44.6MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        14 months ago       742kB
quay.io/coreos/flannel               v0.9.1-amd64        2b736d06ca4c        15 months ago       51.3MB

**Comment by neolit123** [comment]
this this pause image:
https://hub.docker.com/r/e2eteam/pause/tags

this is the one that runs in Windows e2e tests at the moment.
also yikes. 1-2GB for a pod infra container.

**Comment by PatrickLang** [comment]
Also be sure to check the pause container option to the kubelet. It should match the image you have `kubeletwin/pause latest df50757e7311 2 days ago 1.17GB`

Some of the Azure deployment scripts build one called `kubletwin/pause` instead

**Comment by bclau** [comment]
@neolit123 That is not the same as the ``kubeletwin/pause`` image. The ``e2eteam/pause`` image is the Windows E2E testing equivalent of this image: https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L128, and it is based on the windows/servercore:ltsc2019 image. The full image may seem 2GB in size, but since all the images we use are based on that and because of how docker and its layering system works, only a small layer is actually downloaded, the one on top of the windows/servercore image.

For example, if I remove the ``e2eteam/pause:3.1`` image from my system (``docker rmi e2eteam/pause:3.1``) and pull it again (``docker pull e2eteam/pause:3.1``), only ~2 MB of data is actually being downloaded, and the whole operation takes less than 1-2 seconds.

**Comment by neolit123** [comment]
> The full image may seem 2GB in size, but since all the images we use are based on the servercore image and because of how docker and its layering system works, only a small layer is actually downloaded, the one on top of the windows/servercore image.

that is true. layers would reduce the download to the diff in that image.
we might have to add a reminder for that to Windows users.

> @neolit123 That is not the same as the `kubeletwin/pause` image. The `e2eteam/pause` image is the Windows E2E testing equivalent of this image: https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L128, and it is based on the windows/servercore:ltsc2019 image. The full image may seem 2GB in size, but since all the images we use are based on the servercore image and because of how docker and its layering system works, only a small layer is actually downloaded, the one on top of the windows/servercore image.

i still don't have the whole picture about the used images, so please excuse me.

if say the user wants to run nanoserver image based workloads, would they be able to download a nanoserver based pause image too?

**Comment by jwlogemann** [comment]
Hi,
The suggestion of checking the kubeletwin/pause was the right one. The image bundled with Kubernetes is based on build 14393 (server 2016), so it doesn't work on server 2019.

The fix was to build a new Pause image. I used this as the Dockerfile:
`FROM mcr.microsoft.com/windows/nanoserver:1809
CMD cmd /c ping -t localhost`

And then I tagged it as 'kubeletwin/pause'

Perhaps this should be added to the documentation somewhere? I used the Microsoft documentation at: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows

**Comment by bclau** [comment]
> 
> 
> Hi,
> The suggestion of checking the kubeletwin/pause was the right one. The image bundled with Kubernetes is based on build 14393 (server 2016), so it doesn't work on server 2019.
> 
> The fix was to build a new Pause image. I used this as the Dockerfile:
> `FROM mcr.microsoft.com/windows/nanoserver:1809 CMD cmd /c ping -t localhost`
> 
> And then I tagged it as 'kubeletwin/pause'
> 

Indeed, I remember having this issue some ago too. My first instinct was to check the desired Pod's container image, not the kubeletwin/pause image. IMO, the failure reason in this scenario is not obvious enough and could be something that we could improve upon.

> Perhaps this should be added to the documentation somewhere? I used the Microsoft documentation at: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows

Hmm, maybe. The documentation you linked only tells you that you should pull the ``mcr.microsoft.com/windows/nanoserver:1809`` image and tag it as ``microsoft/nanoserver:latest``, so that that image be used by the flannel's repo start script (https://github.com/Microsoft/SDN/tree/master/Kubernetes/flannel/l2bridge)  to create the ``kubeletwin/pause`` image.

**Comment by bclau** [comment]
So, @jwlogemann, if this no longer is an issue, can you close this issue, please?

**Comment by michmike** [comment]
> Hi,
> The suggestion of checking the kubeletwin/pause was the right one. The image bundled with Kubernetes is based on build 14393 (server 2016), so it doesn't work on server 2019.
> 
> The fix was to build a new Pause image. I used this as the Dockerfile:
> `FROM mcr.microsoft.com/windows/nanoserver:1809 CMD cmd /c ping -t localhost`
> 
> And then I tagged it as 'kubeletwin/pause'
> 
> Perhaps this should be added to the documentation somewhere? I used the Microsoft documentation at: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows

we will include this in the GA docs for windows containers on K8s. i had already added a note on this. thank you and sorry for the trouble. i will close this ticket now.
