### ISSUE TITLE
Fluentd 1.2.2 - Argument Error, error="log does not exist"

### ISSUE THREAD

**Issue by cbharathnoor** [kubernetes/kubernetes#74071]
**What happened**:
We are facing "Argument Error, error="log does not exist" when we deploy EFK stack on GoogleKubernetesEngine (GKE) cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create a GKE cluster (1.11.6), deploy EFK stack on GKE cluster.

**Fluentd logs reference**:
`2019-02-14 04:38:14 +0000 [warn]: dump an error event: error_class=ArgumentError error="log does not exist" location=nil tag="node-problem-detector" time=2019-02-14 04:34:27.057416000 +0000 record={"_BOOT_ID"=>"d60c283cd4434b6691a4204e2ab72155", "_MACHINE_ID"=>"e8650c4a44677a9d1e4f6cb4894c7868", "PRIORITY"=>"6", "SYSLOG_FACILITY"=>"3", "_UID"=>"0", "_GID"=>"0", "_SYSTEMD_SLICE"=>"system.slice", "_CAP_EFFECTIVE"=>"3fffffffff", "_TRANSPORT"=>"stdout", "_HOSTNAME"=>"gke-cbha03-default-pool-a6b8eec7-ljr7", "_PID"=>"1293", "SYSLOG_IDENTIFIER"=>"node-problem-detector", "_COMM"=>"node-problem-de", "_EXE"=>"/home/kubernetes/bin/node-problem-detector", "_CMDLINE"=>"/home/kubernetes/bin/node-problem-detector --v=2 --logtostderr --system-log-monitors=/home/kubernetes/node-problem-detector/config/kernel-monitor.json,/home/kubernetes/node-problem-detector/config/docker-monitor.json --custom-plugin-monitors=/home/kubernetes/node-problem-detector/config/kernel-monitor-counter.json,/home/kubernetes/node-problem-detector/config/systemd-monitor-counter.json,/home/kubernetes/node-problem-detector/config/docker-monitor-counter.json --apiserver-override=https://35.237.48.55?inClusterConfig=false&auth=/var/lib/node-problem-detector/kubeconfig --port=20256", "_SYSTEMD_CGROUP"=>"/system.slice/node-problem-detector.service", "_SYSTEMD_UNIT"=>"node-problem-detector.service", "_SYSTEMD_INVOCATION_ID"=>"c6356af3aad6422086f7a2ce40ceab7d", "MESSAGE"=>"I0214 04:34:27.057133    1293 custom_plugin_monitor.go:98] New status generated: &{Source:systemd-monitor Events:[] Conditions:[{Type:FrequentKubeletRestart Status:False Transition:2019-02-13 18:04:29.389561164 +0000 UTC m=+303.488904121 Reason:FrequentKubeletRestart Message:} {Type:FrequentDockerRestart Status:False Transition:2019-02-13 18:04:31.177353737 +0000 UTC m=+305.276696694 Reason:FrequentDockerRestart Message:} {Type:FrequentContainerdRestart Status:False Transition:2019-02-13 18:04:32.831006019 +0000 UTC m=+306.930348976 Reason:FrequentContainerdRestart Message:}]}"}`

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:40:58Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider: Gcloud

- ES: 6.3.0

- Gem file reference:
`source 'https://rubygems.org'`
`gem 'fluentd', '<=1.2.2'`
`gem 'activesupport', '~>5.2.0'`
`gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.1.2'`
`gem 'fluent-plugin-elasticsearch', '~>2.10.5'`
`gem 'fluent-plugin-systemd', '~>1.0.1'`
`gem 'fluent-plugin-detect-exceptions', '~>0.0.11'`
`gem 'fluent-plugin-prometheus', '~>1.0.1'`
`gem 'fluent-plugin-multi-format-parser', '~>1.0.0'`
`gem 'oj', '~>3.6.2'`
`gem 'fluent-plugin-grok-parser', '~>2.1.2'`
`gem 'fluent-plugin-amqp', '0.12.0' `

Request you to help us in resolving this issue.

Thanks.

**Comment by gregbacchus** [comment]
I had this problem too, and after a lot of head scratching and reinstalling of fluentd, I discovered that the problem is actually with elasticsearch. 

What leads to to believe this is that, after doing everything that I could think of in fluentd, I eventually deleted my current index in elasticsearch, and everything started working again.

**Comment by jerbob92** [comment]
@gregbacchus I think that was what fixed it for me too.

**Comment by dminca** [comment]
This error is thrown when no logs where pushing for quite some time & there's a gap.

You need to open Kibana and look for the last date you got metrics, then delete all the indexes up until that date, it'll start working afterwards.

**Comment by cbharathnoor** [comment]
@dminca got it, thanks for the info.

**Comment by ashleshmandke** [comment]
> I had this problem too, and after a lot of head scratching and reinstalling of fluentd, I discovered that the problem is actually with elasticsearch.
> 
> What leads to to believe this is that, after doing everything that I could think of in fluentd, I eventually deleted my current index in elasticsearch, and everything started working again.

Hey,

I am getting below error seems to same:-
[warn]: #0 dump an error event: error_class=ArgumentError error="message does not exist"
I also cleared my current index and executed the fluentd script but its still rejecting records and giving out "[warn]: #0 dump an error event: error_class=ArgumentError error="message does not exist"" error.

Seems it is a issue with elasticsearch. Please help ;)

**Comment by linbingdouzhe** [comment]
issue here

**Comment by akshayubale1** [comment]
same here please help me as well what can be the issue with elasticsearch

**Comment by akshayubale1** [comment]
> same here please help me as well what can be the issue with elasticsearch



> I had this problem too, and after a lot of head scratching and reinstalling of fluentd, I discovered that the problem is actually with elasticsearch.
> 
> What leads to to believe this is that, after doing everything that I could think of in fluentd, I eventually deleted my current index in elasticsearch, and everything started working again.

same here please help me as well what can be the issue with elasticsearch

**Comment by maxisam** [comment]
well, i disable remove_key_name_field and problem solved. It doesn't work if I remove elasticsearch indice
