### ISSUE TITLE
The HorizontalPodAutoscalerUpscaleForbiddenWindow option is still present

### ISSUE THREAD

**Issue by Kanshiroron** [kubernetes/kubernetes#74097]
Hello,

Looking at the code (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/apis/config/v1alpha1/defaults.go#L161), I noticed that the HorizontalPodAutoscalerUpscaleForbiddenWindow option is still present but doesn't seem to be used (it is indeed absent from the documentation).

**Comment by hello2mao** [comment]
@Kanshiroron It is marked deprecated in this PR: https://github.com/kubernetes/kubernetes/pull/66615. And as it says this flag is currently no-op and will be deleted.

**Comment by Kanshiroron** [comment]
:+1:
