### ISSUE TITLE
kubelet on windows consuming 100% cpu running multiple powershell process with`Get-NetAdapterStatistics` 

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#74101]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD (commit: 08d05227303b8f0b7d9c203c7d942788df1cbc97)
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Windows 1803, Windows 1809
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

High cpu usage on the Windows nodes:
```
PS C:\> Get-Counter '\Process(*)\% Processor Time' | Select-Object -ExpandProperty countersamples| Select-Object -Property instancename, cookedvalue,path| ? {$.instanceName -notmatch "^(idle|_total|system)$"} | Sort-Object -Property cookedvalue -Descending| Select-Object -First 25| ft InstanceName,@{L='CPU';E={($.Cookedvalue/100/$env:NUMBER_OF_PROCESSORS).toString('P')}} -AutoSize

InstanceName CPU
------------ ---
powershell   71.15%
powershell   13.07%
powershell   5.08%
powershell   4.36%
msmpeng      2.90%
powershell   2.90%
services     0.73%
kubelet      0.00%
```

Multiple processes running `Get-NetAdapterStatistics`
```
PS C:\> Get-WmiObject Win32_Process | Select-Object CommandLine | Select-String powershell

@{CommandLine=powershell}
@{CommandLine=powershell /c " Get-NetAdapterStatistics | ConvertTo-Json"}
@{CommandLine=powershell /c " Get-NetAdapterStatistics | ConvertTo-Json"}
@{CommandLine=powershell /c " Get-NetAdapterStatistics | ConvertTo-Json"}
@{CommandLine=powershell /c " Get-NetAdapterStatistics | ConvertTo-Json"}
```
I can reproduce this reliably when creating windows 1803 or 1809 nodes in GCE. 

PR #70121 added support for network stats on Windows by calling `powershell /c Get-NetAdapterStatistics | ConvertTo-Json`. 
This function will be called every time kubelet gets queried for stats (`/stats/summary`, `/metrics`). Monitoring agents usually call periodically (e.g., 10s, 60s), etc. Kubelet itself also queries this to perform important functions such as eviction. I patched kubelet to disable the network stats on Windows, and was able to verify that the patch fixed the issue.

I'm not sure why `Get-NetAdapterStatistics` can be so slow and consuming so much CPU. @PatrickLang, @adelina-t have you seen this when testing on Azure. I assume the CI test job is using the latest kubelet binary with network stats.

Regardless, we'd need to cache the information since users can easily overload kubelets/nodes by querying the stats. /cc @feiskyer 

/cc @kubernetes/sig-windows-bugs 
/cc @pjh @jingxu97 @mtaufen 
/cc @dashpole

**Comment by yujuhong** [comment]
I believe this is the reason why the GCE Windows test job has been timing out. https://testgrid.k8s.io/google-windows#windows-gce

**Comment by yujuhong** [comment]
> I believe this is the reason why the GCE Windows test job has been timing out. https://testgrid.k8s.io/google-windows#windows-gce

@feiskyer I'm leaning towards reverting the PR since this blocks our CI testing completely, and the fix is not trivial.

**Comment by feiskyer** [comment]
OK, let's revert the PR and find better solutions later.

/assign

**Comment by michmike** [comment]
@feiskyer  can you please propose an alternative fix for 1.14?
thank you!
cc: @PatrickLang

**Comment by feiskyer** [comment]
Yep, of course. Need to figoure out how to fetch the data more efficiently first.

**Comment by michmike** [comment]
You may want to check if bypassing PowerShell and going directly to WMI where the data is stored is more efficient (This can be done in addition to caching to help alleviate the stress on the node).

wmic /namespace:\\root\StandardCimv2 path MSFT_NetAdapterStatisticsSettingData  get name, receivedbytes, sentbytes

**Comment by PatrickLang** [comment]
+1 - I didn't know which class name was needed. One of the libraries like this may help https://github.com/masterzen/winrm

**Comment by PatrickLang** [comment]
My other thought was that it may be possible to keep a powershell session open, and pipe new commands to it. I think the jit at the beginning is the most expensive part. using the Windows Performance Recorder would be able to determine how much time was spent in each call on the stack.

**Comment by michmike** [comment]
> My other thought was that it may be possible to keep a powershell session open, and pipe new commands to it. I think the jit at the beginning is the most expensive part. using the Windows Performance Recorder would be able to determine how much time was spent in each call on the stack.

if we go native WMI/WinRM will likely be much faster. even faster is likely the windows perf counters
https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-performance-counters
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.performancecounter?view=netframework-4.7.2 (not sure if these are available in any form for GO)

**Comment by PatrickLang** [comment]
here's some code that uses perf counters https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/winstats/perfcounters.go

the same package may work for this but I haven't confirmed what the counter names are

**Comment by feiskyer** [comment]
Thanks for everyone's inputs, the perf counter way looks better.

**Comment by michmike** [comment]
that's awesome to hear Pengfei! Will you have a PR ready for this soon?

**Comment by feiskyer** [comment]
Filed https://github.com/kubernetes/kubernetes/pull/74788 to fix the issue.

**Comment by PatrickLang** [comment]
PR still in review/test
