### ISSUE TITLE
Make `ImageLocalityPriority` easy to use by others

### ISSUE THREAD

**Issue by thandayuthapani** [kubernetes/kubernetes#74132]
**What would you like to be added**:
 Publish `priorityMetadata` from `pkg/scheduler/algorithm/priorities/metadata.go`.  So that it can be accessed outside `priorities` package.

**Why is this needed**:
In `ImageLocalityPriority` Function, only `priorityMetadata.totalNumNodes` is required, so if it is possible to create object of `priorityMetadata` and populate only `totalNumNodes`, it is better.  Rather than collecting data like ServiceLister, ControllerLister, ReplicaSetLister, StatefulSetLister to create a `PriorityMetadataFactory` then to create `priorityMetadata` object from that.

**Comment by huynq0911** [comment]
> **What would you like to be added**:
> Publish `priorityMetadata` from `pkg/scheduler/algorithm/priorities/metadata.go`. So that it can be accessed outside `priorities` package.

I was a little bit confused. As far as I see that almost `priorityMetadata` usages are inside  `priorities` package (`image_locality.go` also). So, can you give me an example of accessing `priorityMetadata` outside  `priorities` package?

**Comment by k82cn** [comment]
xref https://github.com/kubernetes-sigs/kube-batch/pull/587

As we want to reuse `ImageLocalityPriority` outside default scheduler.

**Comment by huynq0911** [comment]
@k82cn, @thandayuthapani : I see.  Can I take this?

**Comment by k82cn** [comment]
> I see. Can I take this?

sure; I'm also thinking how to simplify priorityMetadata's factory functions. Please also share your idea here :)

**Comment by huynq0911** [comment]
@k82cn: Hmm, can you share the implementation idea of `ImageLocalityPriority` function in PR [587](https://github.com/kubernetes-sigs/kube-batch/pull/587/)? 
Is it same as `ImageLocalityPriorityMap` function in [/scheduler/algorithm/priorities/image_locality.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/image_locality.go) ?

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by k82cn** [comment]
> Hmm, can you share the implementation idea of `ImageLocalityPriority` function in PR [587](https://github.com/kubernetes-sigs/kube-batch/pull/587/)?

I want to import and use `ImageLocalityPriorityMap` directly from upstream.

**Comment by bsalamat** [comment]
@k82cn I generally do not recommend using internal data structures/functions of the scheduler in other components as a library. This applies to other similar code that is not part of the scheduler API. We cannot guarantee backward compatibility of such internal structures as we develop the scheduler.

**Comment by k82cn** [comment]
> do not recommend using internal data structures/functions of the scheduler

Agree; comparing to make `priorityMetadata` public, prefer to enhance `NewPriorityMetadataFactory` to accept nil listers to return `priorityMetadata`.

**Comment by bsalamat** [comment]
@k82cn metadata is an internal structure of the scheduler. This means that we may change or even remove it without any announcement. I believe the scheduling framework can solve some of these problems that you are facing now, but in the absence of it we should consider alternatives. One option is to expose some of the scheduler functions externally, as you suggested. Another is to copy part of it in your own repo. Copying is not a great option, but as temporary solution may work better than the former option. It does not expose internal functions of the scheduler and your component will not break with changes to the scheduler. This temporary solution will be replaced by a better implementation when the scheduling framework is ready.

cc/ @misterikkit who had to deal with a few of such imports of non-public scheduler code in other modules when he was working on refactoring the scheduler code.

**Comment by misterikkit** [comment]
I have attempted to fix our PredicateMetadata and PriorityMetadata a few times, and those branches have ended in frustration. To quote @robpike, "[A little copying is better than a little dependency.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s)"

However, I can think of at least one other alternative. You could refactor the priority function into its core behavior that only takes an int, and a wrapper that takes priorityMetadata.

WDYT?

**Comment by resouer** [comment]
> This temporary solution will be replaced by a better implementation when the scheduling framework is ready.

I agree in current stage, temporary workaround like copy-paste can be acceptable (as long as its impact is reasonable). 

Actually, as scheduling framework effort is actively on-going and we highly want users to adopt it in the future, we may want to hold most  "frameworking or resue" ideas/proposals for default scheduler unless it's scheduling framework related or critical. Less distraction is good for this phase.

**Comment by k82cn** [comment]
> I believe the scheduling framework can solve some of these problems that you are facing now

em... I'm also thinking how to enhance the framework; as we discussed in scheduling framework design doc, we may consider how to support "batch" workload, e.g. proportion sharing between job/podgroup, preemption based on other factor instead of priority, and so on. 

Not sure whether you went thouth kube-batch's code; in kube-batch, there're several plugin callback here (by registering func instead of interface implementation):

- Validate: check whether job is ready for scheduling, e.g. enough task for Gang-scheduling
- QueueOrder: help to sort queues, suggest which queue should be handled firstly
- JobOrder: help to sort jobs (PodGroup), suggest which job should be handled firstly within a queue
- TaskOrder: help to sort tasks, suggest which task should be handled firstly within a job (e.g. master vs. worker)
- Preemptable: check whether Pod can evict other Pod between jobs, e.g. priority, sharing
- Reclaimable: similar to Preemptable, but consider betwene queues.
- Predicate/Priortize: similar to default scheduler

For now, we import predicates/priorities from default scheduler for that.

All those plugin are combined together by actions: allocate, reclaim, preempt, backfill; and all those actions are configurable and plugable.

> "A little copying is better than a little dependency."

We already import other priority/predicates, this is only one of them; so dependency is easier :)

> Another is to copy part of it in your own repo. 

A little worried about License and bug fix ...

**Comment by misterikkit** [comment]
kubelet and cluster autoscaler expect to make use of our predicates, and supporting this is meant to be part of the framework effort. I think priorities should get the same treatment. My hope is that with the framework, we will change the predicate & priority APIs from the mess we have today to something that is developer-friendly.

**Comment by k82cn** [comment]
> we will change the predicate & priority APIs from the mess we have today to something that is developer-friendly.

Yes, both using it outside and developing plugin for it.
