### ISSUE TITLE
Failing LivenessProbe of a NFS Pod makes Kubelet "NotReady"

### ISSUE THREAD

**Issue by Mynom** [kubernetes/kubernetes#74135]
**What happened**:

When a Pod with NFS is killed because of a failed liveness probe, the node goes into `NotReady` state.

**What you expected to happen**:

When a pod with NFS is killed because of a failed liveness probe, the node itself should stay operational.

**How to reproduce it**:

Test Setup:

* Create a StatefulSet with a NFS backed PVC and a LivenessProbe (the NFS is not used for anything)
* Kill the connectivity to the NFS server on the Node (with iptables)
* Make the Liveness probe fail
* Kubelet tries to kill the pod (as it should)
* Pod remains in state running for some time
* Kubelet reports RPC errors after some minutes
* After some minutes Kubelet reports PLEG errors
* The node goes to `NotReady`
* After some minutes node goes to ready
* And then loops between `Ready`/`NotReady` every few minutes.
* Pods cannot start or terminate on this node

**Further info**:

Here are the PLEG errors:

```
kubelet.go:1821] skipping pod synchronization - [PLEG is not healthy: pleg was last seen active 3m3.917895079s ago; threshold is 3m0s]

setters.go:518] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2019-02-14 11:57:49.94166251 +0100 CET m=+511.567299413 LastTransitionTime:2019-02-14 11:57:49.94166251 +0100 CET m=+511.567299413 Reason:KubeletNotReady Message:PLEG is not healthy: pleg was last seen active 3m5.962978199s ago; threshold is 3m0s}
```

If we do a `docker ps -a` we see that the container is in status "created"
When we try a `docker inspect <container>`, the process hangs until NFS is restored.
In case that the NFS server should be gone forever we would need to restart the node.

What we tried without success:

* Use different NFS mount options
  * Mount NFS with “hard” option
  * Mount NFS with “soft” option

If the NFS is mounted soft and we do a `umount -l`, the nodes goes into `NotReady` only once, and recovers after that.

Tried to install a new docker / containerd version

* Install docker-0.0.0-20190211170408-013c963.tgz
* Install containerd-1.2.3.linux-amd64.tar.gz

We also found other issues which mention similar problems. (https://github.com/docker/for-linux/issues/397)

The following Scenario works as expected:

* As above, but without a failing LivenessProbe
* Kill the connectivity to the nfs server on the host (with iptables)
* Delete the Pod or scale the StatefulSet down to 0
* Pod remains in "Terminating" until nfs connectivity is restored.
* The Node and all other pods on the node are OK

Why does this behave differently than when the kubelet is killing the pod because of a failed LivenessProbe?

How to debug it further?

**Environment**:

Bare Metal Kubernetes Cluster:
* OS: CentOS 7.6
* Kubernetes Version: 1.12.3
* Kernel: 4.20.7
* Docker Version 18.09.2

**Comment by Mynom** [comment]
We also tested NFSv4, but it behaves the same way as v3.

**Comment by Mynom** [comment]
We also tested setting `runtimeRequestTimeout` to lower values, but it only helps to some degree. If there are to many pods which need killing and have nfs, we see the same pleg not healthy error.

**Comment by Mynom** [comment]
We "fixed" the problem, by swapping docker with containerd.

**Comment by naoufallaaziz** [comment]
Hello, we are facing the same issue, we are able to reproduce the problem like it is described above: we add an iptable rule to drop packets to the nfs server, than we set false livenessprobe to force the pod to the terminating state. as a result, the node goes to notready state with PLEG error in the node description. We are looking for any fixes or workarrounds, but we are not willing to change docker by containerd as it is suggested above. Thank you
