### ISSUE TITLE
Deprecate "containerized kubelet"

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#74148]
There was a previous attempt : https://github.com/kubernetes/kubernetes/issues/43708

We have open issues that is not being worked on:
- https://github.com/kubernetes/kubernetes/issues/74144
- https://github.com/kubernetes/kubernetes/issues/73073

I think it's time to delete the CI jobs and start the deprecation cycle.

/sig node
/assign @derekwaynecarr

**Comment by dchen1107** [comment]
We discussed this at today's SIG Node meeting. SIG Node agreed to deprecate "containerized kubelet" with the following action items:

* The project was initiated for self-host cluster by SIG cluster lifecycle. We should communicate with them first to understand the potential dependencies. 
* There were some demand from the community for this feature in the past, but we don't know who are using this in their production. We should announce this deprecation at Kubernetes Community weekly meeting and send email to kubernetes-dev@.

**Comment by dims** [comment]
will do thanks @dchen1107

**Comment by dims** [comment]
cc @timothysc @luxas @roberthbailey @kubernetes/sig-cluster-lifecycle 

cc @saad-ali @childsb @kubernetes/sig-storage-misc

**Comment by andrewrynhard** [comment]
@dims Does this deprecate `hyperkube` based `kubelet` in any way. I have a project that depends on this and I think it is a real use case for a container based `kubelet`.

https://github.com/autonomy/talos

**Comment by dims** [comment]
@andrewrynhard it doesn't. the main thing to go would be this flag, if you are not using it, you are good.

[1] https://github.com/kubernetes/kubernetes/pull/74267/commits/bcf6d39b3a8d3c260b69f83c29e9c37fca74025f

**Comment by calvix** [comment]
What is the reason behind this decision? We are heavily using containerized `kubelet` in production running on CoreOS

Would that mean that we no longer can run kubelet in container?

**Comment by dims** [comment]
@calvix 

- Do you use the flag as shown here? https://github.com/kubernetes/kubernetes/pull/74176/files#diff-ed3df710e9af7cd30a185896a60897d9L814
- Do you have `--volume` mounts as shown just below the line pointed above

If so, you have about a 3 releases per our deprecation policies to switch over to some other way of running kubelet. RedHat/CoreOS folks who initially championed this approach have given up on it, there are no test suites, no owners. sig-storage is having a hard time trying to keep things working.

So please ping the CoreOS folks to research for an alternative for the future.

Note that `kind` still runs kubelet in a container, it just does not use the flag or volume mounts as shown above.

**Comment by tnozicka** [comment]
Is it necessary to remove/deprecate the feature or just disable the flaky CI check? I find that feature and running in kubelet helpful. Briefly looking at the implementation there is at least unit test suit.

**Comment by dims** [comment]
@tnozicka that's the tip of the ice berg, there's a lot more things that can be simplified when we drop this feature, example see https://github.com/kubernetes/kubernetes/pull/68513

Another example of what we had to go through is here - https://github.com/kubernetes/kubernetes/pull/63143

There is no appetite to continue taking on this burden.

I'll let @derekwaynecarr @jsafrane @saad-ali and others chime in on the undue cost of keeping this alive.

**Comment by timothysc** [comment]
fwiw I don't think we should deprecate the entire use case b/c it's highly valuable for testing.  I'm not certain why this matters for the kubelet, b/c it really shouldn't unless it's a design flaw.

**Comment by dims** [comment]
@saad-ali @msau42 @jsafrane @derekwaynecarr can you please chime in with the ongoing cost of supporting this feature? how much effort is to keep it going?

**Comment by calvix** [comment]
>  Do you use the flag as shown here? https://github.com/kubernetes/kubernetes/pull/74176/files#diff-ed3df710e9af7cd30a185896a60897d9L814

Yes

> * Do you have `--volume` mounts as shown just below the line pointed above

we use this list fo volume:
https://github.com/giantswarm/k8scloudconfig/blob/master/v_4_1_0/master_template.go#L221-L247

This seems to work pretty nice for us and we don't have any volume issues so far.

**Comment by jsafrane** [comment]
> I'll let @derekwaynecarr @jsafrane @saad-ali and others chime in on the undue cost of keeping this alive.

Maintenance of containerized kubelet is increasingly painful. Kubelet / its storage code must know about all mounts on the host, resolve symlinks on the host, execute various helpers on the host and similar stuff, which is especially hard when it does not actually run on the host but is a weird container. See https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/nsenter_mount.go and https://github.com/kubernetes/utils/blob/master/nsenter/nsenter.go for all the hacks we use. They are brittle and tend to break in very unexpected way.

It's also largely undocumented and various ways how to run kubelet in a container are cargo-culted around. See above, `-v /usr/lib64/libxfs.so.0:/usr/lib/libxfs.so.0`, really? No offense, I know why it's there, but whole containerized kubelet is hack on top of hack on top of hack.

**Comment by msau42** [comment]
Not only is the code complex, but it is also not tested, so we have had to rely on manual testing when making bug fixes, and we don't know about regressions until after the release when users report issues. sig-storage has tried for 6+ months to find an owner that can dedicate resources to support and maintain this environment, but nobody has stepped up.

**Comment by saad-ali** [comment]
+1 to what @msau42 asnd @jsafrane said. Either we should deprecate the feature, or find an owners who can commit to fixing issues and adding much needed tests. We tried to find an owner in SIG storage during Q2 2018 but no one stepped up.

**Comment by anguslees** [comment]
Just because I like causing trouble, another alternative is to run `kubelet` executable from a container (or systemd portable unit, etc), but unify the kubelet's rootfs view with that of the host.  Specifically: do the equivalent of #54935, but for `kubelet`.
Then you would run from docker with `-v /:/rootfs:rshared` (or equivalent), and early in `main()` chroot() to /rootfs.  This loads the executable from the docker image, but all later filesystem operations are done from a pov equivalent to the host root fs.

I think this keeps the kubelet lifecycle management benefits of running it from a container _and_ allows the storage folks to just do regular filesystem operations, like there was nothing clever going on.

**Comment by derekwaynecarr** [comment]
The function needs ownership from both SIG Node and SIG Storage.

There were attempts early in the project to remove containerized kubelet support, but Red Hat offered contributors to maintain this model in both SIGs for ~11 releases of Kubernetes.  Kubernetes was much smaller 11 releases ago and our shared project experience was limited.  It's one thing for a feature to work initially, and another thing to reason about the impact of alternative deployment models when dealing with CVE responses or just doing normal maintainer review of incoming PRs or feature function.  That lived experience is informing our future choices at Red Hat to focus on just deploying kubelet as systemd unit (like many other Kubernetes service providers), but if there are others in the community that want to keep the function alive and maintain it we need owners to volunteer and commit to fix issues and add much needed tests.

If not, it seems the responsible thing for the community is to clearly deprecate it.

**Comment by stealthybox** [comment]
> Just because I like causing trouble, another alternative is to run `kubelet` executable from a container (or systemd portable unit, etc), but unify the kubelet's rootfs view with that of the host. Specifically: do the equivalent of #54935, but for `kubelet`.
> Then you would run from docker with `-v /:/rootfs:rshared` (or equivalent), and early in `main()` chroot() to /rootfs. This loads the executable from the docker image, but all later filesystem operations are done from a pov equivalent to the host root fs.
> 
> I think this keeps the kubelet lifecycle management benefits of running the kubelet binary from a container _and_ allows the storage folks to just do regular filesystem operations, like there was nothing clever going on.

I like this suggestion to simplify the mechanism while retaining the packaging and runtime benefits of the container image.

@andrewrynhard, I'm curious what we're doing in talos if we're not using the `--containerized` flag and how what we're doing solves the use-case of running kubelet inside a container.

**Comment by andrewrynhard** [comment]
I kind of like the idea of mounting `/` to `/rootfs` as well. Although, one of the benefits we see in mounting only the needed host paths is that it is less of the host filesystem exposed in case of a security vulnerability. On the other hand we currently mount everything we _think_ we need: https://github.com/autonomy/talos/blob/master/internal/app/init/pkg/system/services/kubelet.go#L86-L96
and that could change in any release. The above solution would allow us to never worry about that again really. @stealthybox We don't use the `--containerized` flag, and I can't say I have seen any of the mentioned issues in our setup. We pass Sonobuoy conformance tests as well. So I can't say I would know exactly what we are doing to solve these problems since I personally have ran into them. I have had rook run just fine as well.
