### ISSUE TITLE
use the csi with cinder storage the driver pod always restart 

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#74162]
**What happened**:
in the k8sv1.14 version,i try the csi-cinder-plugin yaml in web,but the pod always restart!
like this :
default   csi-nodeplugin-cinderplugin-hblqv   2/2   Running   8     16m
default   csi-nodeplugin-cinderplugin-hblqv   1/2   Error   8     16m
kube-system   csi-attacher-cinderplugin-0   1/2   Error   7     18m
default   csi-nodeplugin-cinderplugin-hblqv   1/2   CrashLoopBackOff   8     16m

first i set the kube-apiserver controller-manager schedule kubelet with the --feature-gates=CSIDriverRegistry=true,CSINodeInfo=true then restart the service 

second i create the rbac and statefulset and ds use the yaml with the web:

**What you expected to happen**:
i want all pod running
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
[root@hpa-vm:~/info/logs/k8s]$ kubectl get nodes
NAME           STATUS   ROLES    AGE   VERSION
10.62.1.2   Ready    <none>   68d   v1.14.0-alpha.0.943+0111db216612f7-dirty

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
can you give me some advise? I step by step by the web method but not running,thanks

**Comment by j-griffith** [comment]
@jianglingxia Have you looked at the logs for the PODs to see if it tells you why it's restarting?  I'm assuming you deployed Kubernetes using the externa OpenStack Provider?  You're not trying to do standalone Cinder are you?  Maybe if you provide some more details on how to reproduce that would help, in the meantime I'll see if I can get an environment deployed and check the latest plugin.

**Comment by jianglingxia** [comment]
https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/cinder-csi-plugin
and i reply you in the slack 
thanks

**Comment by adisky** [comment]
Closing the issue, as per discussion on slack, cinder-csi-plugin v0.2.0 used with 1.0.0 sidecars, which is incompatible, upgrading cinder-csi-plugin to 1.0.0 solved the issue
/close
