### ISSUE TITLE
Kubelet: unable to valid path to counter. Error code is c0000bb8

### ISSUE THREAD

**Issue by radiy** [kubernetes/kubernetes#74173]
**What happened**:

I`m trying to setup node on window server 2019, but kubelet fails with error "F0217 17:36:06.467149    3200 server.go:262] failed to run Kubelet: unable to valid path to counter. Error code is c0000bb8"

**What you expected to happen**:

kubelet runs successfully

**How to reproduce it (as minimally and precisely as possible)**:

* install windows server 2019 with ru_RU locale
* run kubelet

**Anything else we need to know?**:

Problem appearances on any non English windows os.
It`s caused by hard-coded performance counter names in
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/winstats/perfcounters.go
PdhValidatePath expects localized counter name.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.3
- Cloud provider or hardware configuration:
n/a
- OS (e.g. from /etc/os-release):
windows server 2019
- Kernel (e.g. `uname -a`):
n/a
- Install tools:
n/a
- Others:
n/a

**Comment by kevdrz** [comment]
Same problem with German Windows.
We even tried replacing the english counters with the german equivalents - no success.

**Comment by ydder007** [comment]
Hey, this is still an issue in version 1.15.0. Will this ever be fixed? Are there any workarounds available?

**Comment by radiy** [comment]
Hi @ydder007, to fix error you need to comment out lines 53-56 in perfcounters.go and rebuild.
I have tested it on 1.13 and after commenting out that lines everything works.

**Comment by Vacant0mens** [comment]
opened an issue [here](https://github.com/JeffAshton/win_pdh/issues/2) the same day as my comment above:

**Comment by wawa0210** [comment]
> opened an issue [here](https://github.com/JeffAshton/win_pdh/issues/2) the same day as my comment above.
> Note: I was using the English version.

I have reproduced this problem in the French environment, but the English environment is normal, has your windows installed other languages? I looked at the example of npd on Microsoft's official website and found that it may be a problem with kubernetes. I am following up with the community.

The microsoft offical example is : https://docs.microsoft.com/en-us/windows/win32/perfctrs/determining-whether-a-counter-is-located-on-a-machine

They dont call  this function `PdhValidatePath `

**Comment by AbelHu** [comment]
@benmoss It seems like that removing `PdhValidatePath` does not fix this issue. `PdhAddEnglishCounter` also returns the same error `Error code is c0000bb8`

https://github.com/kubernetes/kubernetes/blob/v1.18.2/pkg/kubelet/winstats/perfcounters.go#L57-L60

Error logs in 1.18.2:
```
I0725 01:04:33.597201  285124 controller.go:101] kubelet config controller: starting controller
I0725 01:04:33.638287  285124 controller.go:267] kubelet config controller: ensuring filesystem is set up correctly
I0725 01:04:33.639240  285124 fsstore.go:59] kubelet config controller: initializing config checkpoints directory "C:\\var\\lib\\kubelet\\store"
I0725 01:04:33.639240  285124 server.go:417] Version: v1.18.2
W0725 01:04:33.640194  285124 plugins.go:115] WARNING: azure built-in cloud provider is now deprecated. The Azure provider is deprecated and will be removed in a future release
F0725 01:04:33.844801  285124 server.go:274] failed to run Kubelet: unable to add process counter. Error code is c0000bb8
mkdir : An item with the specified name C:\k\volumeplugins already exists.
At C:\k\kubeletstart.ps1:36 char:1
+ mkdir $global:VolumePluginDir
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\k\volumeplugins:String) [New-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand
```

**Comment by benmoss** [comment]
@AbelHu very interesting, can you please open a new issue and investigate our options if you can?

**Comment by wawa0210** [comment]
I remember the last time I modified it and passed the test on the French and Russian Windows operating systems, can you describe your environment information in detail?
