### ISSUE TITLE
Move HumanReadablePrinter to cli-runtime

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes/kubernetes#74179]
**What would you like to be added**:
The cli-runtime repo (`kubernetes/staging/src/k8s.io/cli-runtime`) provides generic printing functionality for plugin authors. However, the `HumanReadablePrinter` from package `k8s.io/kubernetes/pkg/printers` is not included. This printer should also be available in the cli-runtime repo, so that plugins can use it.

**Why is this needed**:
Printing a resource in a standard way ensures a uniform experience in the k8s ecosystem. Given that plugins should also adhere to common standards as far as possible, this printer should be made available to plugin authors by moving it to cli-runtime.

@kubernetes/sig-cli-feature-requests

**Comment by juanvallejo** [comment]
Currently, there are server-side dependencies on `pkg/printers/humanreadable.go`, however we could consider copying that file to cli-runtime to aid with [server-side printing](https://kubernetes.io/docs/reference/kubectl/overview/#server-side-columns) on third-party clients / plugins. cc @soltysh for his opinion on this.

@corneliusweig note that if the above does happen, it would _not_ mean that third-party clients get human-readable behavior for any types from `k8s.io/api`, unless we also copy all of the handlers from https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go and make them work with types from `k8s.io/api` as well. Currently they only work with "internal" types, and introduce core repo dependencies

**Comment by corneliusweig** [comment]
@juanvallejo Thanks for clarifying this! I think if third-party clients can use the server-side printing tools to get the standard look&feel, this is exactly what I am looking for.

**Comment by soltysh** [comment]
See the linked issue for now.

**Comment by grzesuav** [comment]
hi, what is status of this issue ? Is something blocking before implementation (dependencies) ?
