### ISSUE TITLE
Command line completion for kubectl plugins

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes/kubernetes#74178]
**What would you like to be added**:
1. When I type `$ kubectl `<kbd>Tab</kbd><kbd>Tab</kbd> I would like to see kubectl plugins in the list of suggested subcommands. For example, if I have installed `kubectl_sniff`, subcommand completions should suggest `sniff`.
2. If the plugin itself also supports command-line completion, `$ kubectl plugin --`<kbd>Tab</kbd><kbd>Tab</kbd> should show suggestions from the plugin command completion.

**Why is this needed**:
Plugins fill in niches in the kubectl workflow, so that they are used rather seldomly. This means that plugin users need to memorize plugin names and their options over long times without using them. Therefore, plugin usefulness would be greatly enhanced by suggesting plugin sub-commands and their options.

**Comment by corneliusweig** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by SataQiu** [comment]
In fact, `kubectl` already supports command completion.
You can run `kubectl completion -h` for more information about it.

If you are using bash shell，just run `source <(kubectl completion bash)`, and then it will work!

**Comment by corneliusweig** [comment]
Hi @SataQiu , but I'm not talking about command completion in general. I'm talking about command completion for `kubectl` plugins. For example, the new plugin system allows to call a plugin with at location `/usr/bin/kubectl_my_plugin` as `kubectl my-plugin`. It would be nice to get `my-plugin` suggested, when typing `kubectl `<kbd>Tab</kbd>.
Further, if plugin names are completed, so should be options for those plugins -- provided the plugin offers some form of command completion.

**Comment by superbrothers** [comment]
I try to implement completion for kubectl plugins!

**Comment by marckhouzam** [comment]
@superbrothers Were you able to make progress on this?  I have a working patch for the completion of the plugin name (part #1 of this issue).  I can make a PR for it if it can help.

**Comment by corneliusweig** [comment]
@marckhouzam This is a great first step! I do think however, that the real value is auto-completion for the plugin options. I can roughly remember what plugins I have, but _not_ what options they offer. That's the real value here, I think.
This will probably need a contract for how plugins make completion available (e.g. by following the kubectl standard of `my-plugin completion bash/zsh`). WDYT?

**Comment by marckhouzam** [comment]
@corneliusweig I've been thinking about how to do the plugin options completion.  Based on the patch I have now, I believe what will be needed is to be able to ask the plugin what the possible completions can be (based on the user-specified parameters).  

So the plugin won't need to generate a bash or zsh completion script (which is difficult for the author of the plugin) but just output possible completions. This also has the benefit of being independent of which shell is used.

One way is to do as you mention and have the plugin support `myplugin completion` as a way to ask the plugin what the completions would be.  Although it won't behave in the same fashion as `kubectl completion <shell>` (as it won't generate a completion script, and is shell-independent), I like that option because it simply requires a plugin author to provide a different script called `kubectl-myplugin-completion` which the bash completion logic can call.  

Another way would be to ask the plugin itself to support a flag such as `--complete` which would return the possible completions.  I don't like this because if the plugin doesn't support this flag, we'd be calling it and who knows what it would do in that unexpected case.  The use of `kubectl-myplugin-completion` makes it easy to check of presence or absence of completion support.

So I suggest that the contract with plugins be that a plugin that supports completion would provide two scripts
```
kubectl-<plugin>
kubectl-<plugin>-completion
```
and that the bash completion script call `kubectl-<plugin>-completion` to get the list of completions.

Any thoughts?

**Comment by superbrothers** [comment]
Hi guys,

I've already implemented completion for plugins (subcommands only, doesn't include options) as https://github.com/superbrothers/kubernetes/tree/completion-plugins. However it needs to be refactored more.

You can try completion for plugins with the following steps:

First, prepare the repository, and build a kubectl.

```
$ pwd
/home/dev/src/k8s.io/kubernetes
$ git remote add superbrothers git://github.com/superbrothers/kubernetes.git
$ git fetch superbrothers
$ git checkout -b completion-plugins superbrothers/completion-plugins
$ make kubectl
```

Install kubectl-hello plugin for completion testing.

```
$ mkdir -p ~/bin/
$ cat <<'EOL' > ~/bin/kubectl-hello
#!/bin/sh

echo hello
EOL
$ chmod +x kubectl-hello
$ export PATH="$HOME/bin:$PATH"
$ _output/bin/kubectl hello
hello
```

Load the kubectl completion code.

```
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
$ source <(_output/kubectl completion bash)
```

You can see completion for some plugins.

```
`$ kubectl <tab><tab>
annotate                        cordon                          get                             replace
api-resources                   cp                              hello                           rollout
api-versions                    create                          krew                            run
apply                           delete                          kustomize                       scale
attach                          describe                        label                           set
auth                            diff                            logs                            taint
autoscale                       drain                           open-svc                        top
certificate                     edit                            options                         uncordon
cluster-info                    exec                            patch                           version
completion                      exec-as                         plugin                          view-serviceaccount-kubeconfig
config                          explain                         port-forward                    wait
convert                         expose                          proxy 
```

**Comment by marckhouzam** [comment]
Cool! You've used the same technique I did.  However, may I suggest re-using the code from the plugin package instead of copying it?

https://github.com/VilledeMontreal/kubernetes/commit/6f500099a8ee05b42d4cc8f2f33f7148fb75fd4a

**Comment by corneliusweig** [comment]
@marckhouzam Well, you are absolutely right in saying that we can't just call a plugin with some flag to produce the completion script, because who knows what will happen. Therefore, option completion for plugins has to go the route via an external completion script, like
```
kubectl-myplugin
kubectl-myplugin-completion.bash
kubectl-myplugin-completion.zsh
```

However, I'm pretty sure that those completion files need to be bash/zsh scripts, because they need to process contextual information. For example, say I have a plugin with sub-commands
```
kubectl myplugin subcommandA --option-for-a
kubectl myplugin subcommandB --option-for-b
kubectl myplugin <tab><tab> # should show subcommandA & subcommandB
kubectl myplugin subcommandA <tab><tab> # should show --option-for-a
```
As you say, this will have to be maintained by the plugin authors.

@marckhouzam  Can you take a typical cobra command completion script as basis and work out how kubectl-plugin-completion and this external script need to work together? You could even try to have kubectl as its own plugin, like `kubectl-kubectl` and `kubectl-kubectl-completion.bash` or so :grinning:

**Comment by marckhouzam** [comment]
@corneliusweig kubectl already has some dynamic completion code to allow to complete pod names for example, which actually calls kubectl itself.  I think I can use the same technique for plugin parameter completion.  So here's an example of what I'm thinking:

```
> cat kubectl-plugin
#/bin/bash
if [[ "$1" = "--uppercase" ]]; then
   echo HELLO
else
   echo hello
fi

>cat kubectl-plugin-completion
#/bin/bash
OPTION="--uppercase"
if [[ ${OPTION#$1} != ${OPTION}  ]]; then
   echo ${OPTION}
fi
```
Then  when the user types `kubectl plugin --u<TAB>` the kubectl completion script will call `kubectl plugin completion --u`.  This call will return `--uppercase` which will be given to the shell by the kubectl completion script.  I haven't actually tested this example, so I could be wrong.

I'll try implementing it to see if I'missing something.

**Comment by superbrothers** [comment]
@marckhouzam Thank you for supporting me ;) I adds you as co-author to commit when I send a PR.

**Comment by marckhouzam** [comment]
@superbrothers Thanks

**Comment by marckhouzam** [comment]
I've been working on auto-completion for the Helm project and I have a proposal with a PR that fully supports auto-completion for Helm plugins.  I believe the fundamental aspects of the solution would apply just as well to kubectl.  Some adaptation would be needed to adjust to how kubectl supports plugins, but I think it wouldn't be very hard.

https://github.com/helm/helm/issues/7043
https://github.com/helm/helm/pull/7078

**Comment by elsesiy** [comment]
Is there an ETA on this? If I see it correctly, this currently preventing plugin authors to implement completions as the generated completion suggestions are based off the root command `kubectl` and not the subcommand aka plugin. I've been trying all day to make this work but failed and that's when I stumbled over this issue..

**Comment by ahmetb** [comment]
Several major issues I see here are:

- We don't want files like `completion.yaml` as proposed in previous comment. We had a plugin.yaml requirement prior to kubectl 1.12 and it didn't look great at all. The simplicity of plugins is valuable to us. (Also, unlike Helm plugins, kubectl plugins don't live at a particular directory, or follow a directory structure.)

- Plugin completions most likely would be integrated into `kubectl completion [bash|zsh]` commands, which a lot of people put in their ~/.bashrc or ~/.zshrc file. We need to keep this command fast.

So what if the `kubectl completion` command called a special command on each plugin, _in parallel_, to inquire if it has completion available (e.g.` $PLUGIN get-completion [bash|zsh]`), with a short deadline, and cached the successful results (maybe keyed with on plugin binary’s stat data, or checksum). That way, `kubectl complete` cmd could also provide data about plugins, while periodically refreshing the cached completion scripts.

**Comment by elsesiy** [comment]
Shall not be stale 👍

**Comment by colceagus** [comment]
any updates on this one ? is it complete/done?

**Comment by elsesiy** [comment]
@colceagus No update, still open..

**Comment by marckhouzam** [comment]
It would be nice if some plugin developers try out the solution proposed in https://github.com/kubernetes/kubernetes/pull/105867 and provide feedback.

@corneliusweig since `get-all` uses Cobra, the solution is very easy.  Here is how to try it out:
First build kubectl with the PR
```
cat <<EOF > kubectl_complete-get_all
#!/usr/bin/env sh

# It is important to quote the \$@ variable since the last parameter
# could be empty, which indicates that the prefix to complete is empty.
kubectl get-all __complete "\$@"
EOF
chmod +x kubectl_complete-get_all
```
put this new `kubectl_complete-get_all` on $PATH.

And now test using the newly built `kubectl` (I build mine at `/tmp/kubectl`).
```
$ /tmp/kubectl get<TAB>
get             -- Display one or many resources
get-all

$ /tmp/kubectl get-all <TAB>
completion  -- generate the autocompletion script for the specified shell
help        -- Help about any command
version     -- Print the version information
```
For completion of flags (which I realize is the real value for the `get-all` plugin), kubectl needs to first move to Cobra 1.3.

**Comment by marckhouzam** [comment]
@ahmetb I would be interested in your opinion on the proposed solution.  It will not work out-of-the-box with Krew, but I haven't found a way to do better with respect to Krew.

> What if the kubectl completion command called a special command on each plugin, in parallel, to inquire if it has completion available (e.g. $PLUGIN get-completion [bash|zsh])

You had mentioned this previously, and although it would be a nice solution, I am concerned it would cause problems to any plugin that ignores all arguments and runs no matter what.  With such a plugin, calling a `get-completion` command would trigger the plugin to run and possibly perform undesired actions when completions are requested.

**Comment by ahmetb** [comment]
@marckhouzam I'm sorry about slow responses. Finally had time to read it and parse these. You're right we shouldn't randomly call a plugin binary without knowing it supports completion.

From #105867:

> This PR does two things:
> 1- includes plugin names during kubectl shell completion

kubectl already has a mechanism to find all plugins on $PATH, so I agree that at minimum, kubectl<kbd>Tab</kbd> can and should show plugins installed on the system (even if the plugins themselves don't support shell completion)

> 2- allows a plugin to provide completions through an executable script named kubectl_complete-<pluginName> present on $PATH

I think this is a good model. Just like how kubectl scans $PATH for `kubectl-*`, it can scan `kubectl_complete-*` to see if a plugin supports completion. (It's important to define if that binary takes additional positional args or --options) 

To make the (2) a reality, I support adding an additional field to the Krew plugin manifest. The shape of that would be up for a discussion (I imagine it might be (a) a separate binary that comes in the plugin archive, or (b) allow linking to the plugin binary itself and the plugin reads argv[0] and prints completion, which can be done with (a) anyway).

I think it's doable. I'm not very familiar with how shell completion works in practice, when it's called, how lazy can it be loaded, what are performance implications etc, but if you'd like to drive this effort, I think we can discuss a design on Krew side as well. Please bring this up in a SIG CLI meeting to see what the folks think about your proposal.

**Comment by marckhouzam** [comment]
@ahmetb brilliant! Thanks for taking the time to think about this.  Your suggestion to adapt krew sounds great to me.

I will continue with the PR on kubectl's side and if it gets accepted we can look at krew.

**Comment by marckhouzam** [comment]
> It's important to define if that binary takes additional positional args or --options

The `kubectl_complete-<plugin>` as proposed in #105867 accepts the exact same arguments as the standard `kubectl-<plugin>` executable.  The new completion executable will examine those arguments and will determine what the shell completion choices following them should be.

**Comment by ahmetb** [comment]
@marckhouzam do you have an insight into whether a plugin developer would develop and ship a separate executable for the completion, or would they simply link the main plugin executable and see if the argv[0] is the kubectl_complete-*? I assume the answer largely also depends on whether the plugin was authored in Go or bash (basically the only two languages I've ever seen a plugin submission in out of 150+).

**Comment by marckhouzam** [comment]
@ahmetb I think plugins will choose to ship a separate executable.  I feel it keeps the two aspects nicely separate (the plugin functionality and the shell completion functionality).  Also, it is very easy for a separate executable to call back the main plugin if the developer wishes to do so, so I find that solution the most flexible.  For example, for plugins using the Cobra library, the `kubectl_complete-myplugin` script would call back the executable like this:
```
#!/bin/sh
kubectl myplugin __complete "$@"
```

BTW, I have looked into the 179 plugins in the krew index and I found that 50% (yes, half!) of them used Cobra (some of them indirectly by calling back `kubectl`).  This means that shell completion should be very easy to implement for all these plugins.

**Comment by subhamkrai** [comment]
@ahmetb @marckhouzam I'm interested in this support and thanks for adding this feature. One question: in which version this is planned to be released? Looking forward to this.
