### ISSUE TITLE
Catch PodExceedsFreeCPU or PodExceedsFreeMemory events in Java Client API

### ISSUE THREAD

**Issue by IvanMijailovic** [kubernetes/kubernetes#74214]
Hi All, 
Is there any way to catch PodExceedsFreeCPU or PodExceedsFreeMemory events in Java Client API code?
On the other hand, make Java Client code aware of these failed events.

Thanks in advance!

**Comment by errordeveloper** [comment]
I think you should report this in Java client repository, not here.

**Comment by IvanMijailovic** [comment]
Thanks @errordeveloper, the question is raised on their side hence issue closed.
