### ISSUE TITLE
Non-existent image referenced in imageutil

### ISSUE THREAD

**Issue by maxbischoff** [kubernetes/kubernetes#74215]
**What happened**:

I extracted the images from https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go to mirror them in a closed environment and got an error for `CudaVectorAdd2` resepctive gcr.io/kubernetes-e2e-test-images/cuda-vector-add:2.0: 
`Error response from daemon: manifest for gcr.io/kubernetes-e2e-test-images/cuda-vector-add:2.0 not found`
The var `CudaVectorAdd2` also does not seem to be referenced in any test.

**What you expected to happen**:

The image should either be pullable or the variable be removed.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ docker image pull gcr.io/kubernetes-e2e-test-images/cuda-vector-add:2.0
Error response from daemon: manifest for gcr.io/kubernetes-e2e-test-images/cuda-vector-add:2.0 not found
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maxbischoff** [comment]
@kubernetes/sig-testing-bugs

**Comment by anarchistHH1983** [comment]
I signed it
