### ISSUE TITLE
windows: considerations about the pause image

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#74218]
1. determine a good default location for the pause image on Windows
should we host in in GCR as the default location for users?

2. image contents
- we most likely need to make it schema2 with support for all OS versions that we want to target.
- ideally needs to be as small as possible.
  - if users will target nanoserver on worker nodes the image should be nanoserver based too.
  - if the users are already using a full Windows Server image we might want to have a separate image for that.
  - this possibly means different images.

with regards to deployer tools like kubeadm in the future, we might have to think about how to approach 
the problem tag wise. e.g. separate repos for nanoserver or full Windows Server based images.

xref https://github.com/kubernetes/kubernetes/issues/74134

/sig windows
/kind feature
/assign @bclau @neolit123 
cc @michmike

**Comment by michmike** [comment]
My goal should be if microsoft can create the pause image and push it to mcr.microsoft.com. then we cna do a manifest push on gcr.io for tests to consume it.
/assign @craiglpeters

**Comment by michmike** [comment]
@craiglpeters already worked with msft to publish this image at mcr.microsoft.com/k8s/core/pause:1.0.0
can we close this issue now?

cc: @neolit123

**Comment by neolit123** [comment]
@michmike 

just tried the image and it runs fine on my 1809.
also i'm seeing the image is a schema v2, nano server based.

so yes, i think we can close.
thanks for the update!

/close

**Comment by michmike** [comment]
perfect thanks @neolit123

**Comment by benmoss** [comment]
@neolit123 is this something we should be defaulting in kubelet? https://github.com/kubernetes/kubernetes/blob/aa5fda22f23c3bb0a1b5c2853171b7fbd11900b8/cmd/kubelet/app/options/container_runtime.go#L28-L32

**Comment by neolit123** [comment]
i would say, yes.
these are the defaults for the kubelet `--pod-infra-container-image` flag.

**Comment by michmike** [comment]
in our instuctions, we are telling folks to use it like this as well.
```
# Register kubelet.exe
# Microsoft releases the pause infrastructure container at mcr.microsoft.com/k8s/core/pause:1.0.0
# For more info search for "pause" in the "Guide for adding Windows Nodes in Kubernetes"
nssm install kubelet C:\k\kubelet.exe
nssm set kubelet AppParameters --hostname-override=<hostname> --v=6 --pod-infra-container-image=mcr.microsoft.com/k8s/core/pause:1.0.0 --resolv-conf="" --allow-privileged=true --enable-debugging-handlers --cluster-dns=<DNS-service-IP> --cluster-domain=cluster.local --kubeconfig=c:\k\config --hairpin-mode=promiscuous-bridge --image-pull-progress-deadline=20m --cgroups-per-qos=false  --log-dir=<log directory> --logtostderr=false --enforce-node-allocatable="" --network-plugin=cni --cni-bin-dir=c:\k\cni --cni-conf-dir=c:\k\cni\config
nssm set kubelet AppDirectory C:\k
nssm start kubelet```

**Comment by benmoss** [comment]
Is there a reason we're hosting this on mcr.microsoft.com? We're talking about adding to the pause image in #75479 for enabling port forwarding, but we (the k8s community) doesn't have access to the Dockerfile or to push new versions of it right now.

**Comment by neolit123** [comment]
@benmoss apparently the layers of the original images are licensed in such a way that we cannot host them in another registry. we can only create manifests that reference them.

**Comment by astrieanna** [comment]
@neolit123 That's true of all windows images because you can't host the nanoserver/servercore base images. My impression is that this pause image is nanoserver + a default executable, which would mean that the very minimal additional layer (setting a default executable) could be hosted anywhere, right?

**Comment by neolit123** [comment]
yes, the additional layer can be hosted in a community maintained location.

**Comment by yujuhong** [comment]
> yes, the additional layer can be hosted in a community maintained location.

+1 the source code for the pause image should be hosted in a kubernetes repository, and the images can be pushed to registries the community maintains.

**Comment by yujuhong** [comment]
> @neolit123 is this something we should be defaulting in kubelet?

Caveat: this flag only works for dockershim (and the discussion to decouple dockershim from kubelet is ongoing in sig-node)  Other CRI runtimes get to decide what type of PodSandbox and pause image they'd like to use.

**Comment by benmoss** [comment]
xref #75618

**Comment by jwlogemann** [comment]
I've opened a related feature request here: https://github.com/kubernetes/kubernetes/issues/80032

It's a request to select the correct  pause image based on the windows kernel version. Currently k8s fails to run pods by default if you run it on Server 1903, since the pause image is build for 1809
