### ISSUE TITLE
securityContext runAsGroup leads to diff on kubectl apply

### ISSUE THREAD

**Issue by sepich** [kubernetes/kubernetes#74211]
**What happened**:
Applying the same yaml leads to `configured` instead of `unchanged`
```
$ cat test.yml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    securityContext:
      runAsGroup: 65534
      runAsUser: 65534

$ kubectl apply -f test.yml
pod/myapp-pod configured

$ kubectl apply -f test.yml
pod/myapp-pod configured

$ kubectl get pod/myapp-pod -oyaml | grep last-applied-configuration -A1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"myapp-pod","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","echo Hello Kubernetes! \u0026\u0026 sleep 3600"],"image":"busybox","name":"myapp-container","securityContext":{"runAsGroup":65534,"runAsUser":65534}}]}}
```
Removing `runAsGroup` fixes it:
```
$ cat test.yml | grep -v runAsGroup | kubectl apply -f -
pod/myapp-pod unchanged
```

**What you expected to happen**:
When there is no diff with `kubectl.kubernetes.io/last-applied-configuration` there should be no `configured` response?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
on-premise
- OS (e.g. from /etc/os-release):
Debian 9
- Kernel (e.g. `uname -a`):
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by liggitt** [comment]
That is attempting to set a field that is not currently enabled by default in the api. Client-side, kubectl sees that it wants to set the field and that it is not set server side

/close
