### ISSUE TITLE
Flaky in-tree local volume plugin tests

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#74229]
**Which jobs are failing**:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/34994

**Which test(s) are failing**:

[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (default fs)] volumes should be mountable

**Since when has it been failing**:

**Testgrid link**:

https://testgrid.k8s.io/sig-storage-kubernetes#gce

**Reason for failure**:

Volume of previous pod is not unmounted before the second pod is trying to mount its volume.

**Anything else we need to know**:

**Comment by cofyc** [comment]
The problem is when client is deleting first pod, it is deleted immediately.

```
I0219 00:28:14.843692       1 wrap.go:47] DELETE /api/v1/namespaces/volumes-8868/pods/in-tree-injector-rms5: (93.019997ms) 200 [e2e.test/v1.14.0 (linux/amd64) kubernetes/197941a -- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (default fs)] volumes should be mountable 35.232.4.199:49772]
I0219 00:28:14.854369       1 graph_populator.go:167] deletePod volumes-8868/in-tree-injector-rms5 for node bootstrap-e2e-minion-group-j6dk
```

This is because when pod status phase is `Succeeded`, [pod object is deleted immediately](https://github.com/kubernetes/kubernetes/blob/cbcc2b26fe214282290b2d8c9dabfbf2226fdeb6/pkg/registry/core/pod/strategy.go#L135-L138). But pod is set to `Succeeded` before its volumes are unmounted and detached.

`in-tree-injector` pod object may be deleted from apiserver before its volumes are unmounted, so it may have conflicts in setting fsGroup for second pod `in-tree-client.

If we want to wait for the pod to be deleted by kubelet instead of apiserver, we need to make it a long-running pod.

cc @msau42

**Comment by msau42** [comment]
cc @dashpole is this expected? I thought kubelet is supposed to delete the pod object only after the volumes are unmounted. This also impacts the StorageProtection feature, which assumes that if the Pod object is deleted, then the volume has been unmounted. For a storage backend like nfs, it may result in unmount hanging. cc @kubernetes/sig-storage-bugs  

@cofyc to fix the flakiness, the simplest thing may be to make the two pods use the same fsgroup.  I don't see a strong use case for two pods using different fsgroups.

**Comment by dashpole** [comment]
> I thought kubelet is supposed to delete the pod object only after the volumes are unmounted.

That is only during graceful deletion.  If a pod is Succeeded, do we begin unmounting volumes?  Or do we wait until the deletion timestamp is set?  Would it be good enough to start unmounting when the pod is failed/succeeded?  If we want to be 100% sure this isn't a problem, we would need to always do graceful deletion, even when the pod is failed/succeeded.

**Comment by msau42** [comment]
Yes, we do start unmounting when pod is [succeeded or failed](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/util/util.go#L372).

The API is setting grace period to 0 in the case of pod success or failed. Maybe that needs to be removed if we want to use Pod deletion as a signal that volumes are unmounted.

**Comment by cofyc** [comment]
To always do graceful deletion even when the pod is failed/succeeded is simple, then we can assume that normally when pod objects are deleted (except forcefully), volumes are already unmounted by kubelet. But [this feature is added long ago](https://github.com/kubernetes/kubernetes/pull/15900), and it helps to improve performance in deleting jobs in batch.

For this flaky test only, what I need is to make sure volumes are unmounted before the second pod is going to mount them, but local volumes are not reported in `VolumesInUse` or other fields of node status, I can't make sure of this by checking node status either.

Possible workarounds:

- make the first a long-running pod (too hacky)
- wait for a while before starting the second pod (short period may be flaky too, long period increases test time)

I'm going to use same fsGroup for both pods until we have a reliable way to detect volumes are unmounted or not.
