### ISSUE TITLE
Unable to decode an event from the watch stream: stream error: stream ID 3; INTERNAL_ERROR

### ISSUE THREAD

**Issue by vvkkhjt** [kubernetes/kubernetes#74237]
here is my question:https://stackoverflow.com/questions/54760830/unable-to-decode-an-event-from-the-watch-stream-stream-error-stream-id-3-inte

**Comment by jingyih** [comment]
@vvkkhjt Are you running on Azure? This issue looks similar to a known issue #69147.

**Comment by vvkkhjt** [comment]
@jingyih No,its on Qcloud.

**Comment by zw0610** [comment]
@vvkkhjt Hi, do you mind sharing with us the solution you found to fix this issue?

**Comment by vvkkhjt** [comment]
> @vvkkhjt Hi, do you mind sharing with us the solution you found to fix this issue?

https://github.com/vvkkhjt/k-collection/blob/20d458d049f724ca3d895d9f688ce60933803381/kapp/v1/v1.go#L224

**Comment by zw0610** [comment]
> > @vvkkhjt Hi, do you mind sharing with us the solution you found to fix this issue?
> 
> https://github.com/vvkkhjt/k-collection/blob/20d458d049f724ca3d895d9f688ce60933803381/kapp/v1/v1.go#L224

Thanks a lot!
