### ISSUE TITLE
multi `container` query param in kubectl request

### ISSUE THREAD

**Issue by xrmzju** [kubernetes/kubernetes#74231]
**What happened**:
when use `kubectl exec` command, we found multi `container` query param in the request, 
```shell
...exec?command=sh&container=container-0&container=container-0&stdin=true&stdout=true&tty=true'
```
  because we set the `container` param twice in  `kubernetes/pkg/kubectl/cmd/exec/exec.go`  
```go
		req := restClient.Post().
			Resource("pods").
			Name(pod.Name).
			Namespace(pod.Namespace).
			SubResource("exec").
			Param("container", containerName)
		req.VersionedParams(&corev1.PodExecOptions{
			Container: containerName,
			Command:   p.Command,
			Stdin:     p.Stdin,
			Stdout:    p.Out != nil,
			Stderr:    p.ErrOut != nil,
			TTY:       t.Raw,
		}, scheme.ParameterCodec)
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use `kubectl exec` command and set the log level to `8`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tossmilestone** [comment]
@xrmzju It seems a duplicate 'container' param are set, thanks for your report. I will fix it later.
