### ISSUE TITLE
Add way to specify kubeadm's --ignore-preflight-errors in InitConfiguration and JoinConfiguration

### ISSUE THREAD

**Issue by marccarre** [kubernetes/kubernetes#74246]
**What would you like to be added**:

A single way to configure all of `kubeadm`'s behaviour.
In particular, given `ignorePreflightErrors` and `externalcfg` are currently disjoint:
https://github.com/kubernetes/kubernetes/blob/a887ae8344adf9739c1d156a718c05fdf95b73ab/cmd/kubeadm/app/cmd/init.go#L104-L106
https://github.com/kubernetes/kubernetes/blob/a887ae8344adf9739c1d156a718c05fdf95b73ab/cmd/kubeadm/app/cmd/join.go#L132-L133
I would like a way to specify the set of strings corresponding to `--ignore-preflight-errors`'s value as an "array" in (at least) `InitConfiguration` and `JoinConfiguration`.

**Why is this needed**:

This would simplify programmatic usage of `kubeadm`: one configuration file to generate, and then pass to `kubeadm`.

**Potential way forward**:

1. Keep `--ignore-preflight-errors` for backward-compatibility (for now).
2. Add the following field to both `InitConfiguration` and `JoinConfiguration`:

    ```go
    IgnorePreflightErrors []string `json:"ignorePreflightErrors,omitempty"`
    ```

3. Take the union of both sets, validate it (as currently done), and use this going in the rest of the program.

**Misc.**:

Happy to make the change myself, once I get a "go" (or at least, no "no-go") from someone more knowledgeable. (Maybe @luxas? 🙂 )

**Comment by neolit123** [comment]
could you please move this to the k/kubeadm repository?
kubeadm tracks it's issues there.

thank you.

**Comment by marccarre** [comment]
Looks like I cannot "[move](https://help.github.com/en/articles/transferring-an-issue-to-another-repository)" it per-se, but I cloned it here: kubernetes/kubeadm/issues/1460

**Comment by neolit123** [comment]
that's what i meant, sorry.
/close
