### ISSUE TITLE
There are too many pdb update operations even if no changes take place

### ISSUE THREAD

**Issue by snowplayfire** [kubernetes/kubernetes#74240]
**What happened**:

There are too many pdb update operations compared with other resources.
![image](https://user-images.githubusercontent.com/11936090/52943840-fd609b80-33a8-11e9-880a-308e7de12638.png)
That is, there are many "Put" operations for pdb periodically in kube-apiserver log.
```
I0212 20:35:05.923317   10957 wrap.go:42] PUT /apis/policy/v1beta1/namespaces/<namespace>/poddisruptionbudgets/<name>/status: (2.618059ms) 200 
...
```

In my view, the amount of pdb operations  is connected with disruption controller's resyncPeriod and pdb's quantity in cluster. 

For example:

disruption-controlle's default resyncPeriod is 30s,  and there are 100 pdbs in cluster.

We can find that the update operation times per minute is  about  200.

The data is reasonable, explanation is as follows: 

According to disruption-controlle's design, there is one  resync every 30s.  One resync means to call updatePdbStatus function for every pdb, so there are 200 times updatePdbStatus.  

Function updatePdbStatus  judges whether the pdb is changed. If changed, call  apiserver to update the pdb' status.

```
func (dc *DisruptionController) updatePdbStatus(pdb *policy.PodDisruptionBudget, currentHealthy, desiredHealthy, expectedCount int32, disruptedPods map[string]metav1.Time) error {
...
if pdb.Status.CurrentHealthy == currentHealthy &&
		pdb.Status.DesiredHealthy == desiredHealthy &&
		pdb.Status.ExpectedPods == expectedCount &&
		pdb.Status.PodDisruptionsAllowed == disruptionsAllowed &&
		reflect.DeepEqual(pdb.Status.DisruptedPods, disruptedPods) &&
		pdb.Status.ObservedGeneration == pdb.Generation {
		return nil
	}
...
}
```
When no eviction happens,  disruptedPods is empty.  In this situation,  disruptedPods is an empty map, but pdb.Status.DisruptedPods is nil, empty map is not equal to nil.
So reflect.DeepEqual(pdb.Status.DisruptedPods, disruptedPods) returns false.

The pdb is thought to has be changed,  then apiserver is called to update the pdb' status.  In fact, there is no change for the pdb when disruptedPods is an empty map and pdb.Status.DisruptedPods is nil.

**What you expected to happen**:
There shouldn't be so many pdb update operations. That is, when pdb has no change,  apiserver shouldn't be called to update its status.

**How to reproduce it (as minimally and precisely as possible)**:
Create some pdbs in cluster,  you will see many "Put" operations for pdb periodically in kube-apiserver log.

**Anything else we need to know?**:

**Environment**:
kubernetes v1.13.2

**Fix suggestions**:
The bug is caused by the mixed usage of empty and  nil for disruptedPods,  the type of which is map[string]metav1.Time. There are two fix suggestions for it:

1. Choose one of empty map and  nil for disruptedPods, use it consistently and refuse to mix empty map and  nil. For example,  when disruptedPods is empty or nil, save it as an empty map in etcd.  Then every client gets pdb from etcd, the pdb.Status.DisruptedPods is an empty map.  

1. After get pdb for etcd,  assign an empty map to it if pdb.Status.DisruptedPods  is nil. 

Maybe the mixed usage of  empty and nil for map is a common problem in k8s design, not just for disruptedPods. I will propose a work around solution for the problem.

If the solution has any problem, please let me know and I can modify the code.

**Comment by kow3ns** [comment]
/assign @mortent 

Morten can you PTAL and the open PR. I reviewed as well.

**Comment by YueHonghui** [comment]
ref https://github.com/kubernetes/kubernetes/issues/43218
