### ISSUE TITLE
ds shows  wrong pod status by kubectl

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#74253]
**What happened**:
when i exec `kubectl get ds` it shoud wrong message:
```shell
$kubectl  get ds    
NAME     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                       AGE
csi-ds   0         0         0       0            0           xxx=000   77m
```

but in fact it has replicas.

when describe this ds

```shell
kubectl describe ds csi-ds
...
Name:           csi-ds
Selector:       daemonset=pv-provisioner
Node-Selector:  xxx=000
Labels:         k8s-app=hostpath-driver
Annotations:    ...
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  109 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
...

```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centOS 7.4
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yowenter** [comment]
I'll try to reproduce it and try to figure it out.

**Comment by yowenter** [comment]
@zhangxiaoyu-zidif  Hi, could you paste the output of `kubectl get ds csi-ds -o yaml` ? 
I guess there may be some mistakes with the selector.

**Comment by zhangxiaoyu-zidif** [comment]
@yowenter  you mean that something wrong with my node selector?

**Comment by zhangxiaoyu-zidif** [comment]
OK, I recheck it, now it is correct now:
```shell
$kubectl  get ds
NAME     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                       AGE
csi-ds   109       109       109     109          109         xxx=000   23h
```

**Comment by zhangxiaoyu-zidif** [comment]
maybe the sync needs some time, but it delays too much... I am not sure when it turns correct...

**Comment by yowenter** [comment]
The daemonset is an higher layer abstraction of pod. The ds controller use shared Informer to sync pod status. So maybe it will be a little slow.
