### ISSUE TITLE
Master-blocking failing tests: verify.godeps and verify.staging-godeps

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74261]
**Which jobs are failing**:
* [master-blocking/verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)

**Which test(s) are failing**:

| Job | Test | Reason for failure |
|---|---|---|
| [verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master) | [verify.godeps](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26819) | `Your vendored results are different: diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto /tmp/gopath.fjRjH3/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto`
| [verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master) | [verify.staging-godeps](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26819) | `Unexpected dirty working directory`

**Since when has it been failing**:
2019-02-19, [build 26960](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26960), [k/k 42b7bb1c1](https://github.com/kubernetes/kubernetes/commit/42b7bb1c1)

**Anything else we need to know**:
Related: https://github.com/kubernetes/kubernetes/issues/73999
I wonder if there's an opportunity for automation/testing before end to end tests there 🤔

/kind failing-test
/priority important-soon
/sig api-machinery

cc @smourapina @alejandrox1 @mortent @kacole2

**Comment by mariantalla** [comment]
Thanks! 💥

**Comment by spiffxp** [comment]
/reopen
We're running into this again, slightly different error message

**Comment by spiffxp** [comment]
Last good: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/27209
First failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/27210

Leads me to https://github.com/kubernetes/kubernetes/compare/b1d4d4067...8770e0cd3

**Comment by spiffxp** [comment]
Paging @dims @nikhita @scottrigby any idea how this could be related to https://github.com/kubernetes/kubernetes/pull/74664 ? That's the only PR showing up in that commit range

**Comment by spiffxp** [comment]
This looks like another occurrence of the same failure, and is making me question whether we're actually kicking a can down the road vs. fixing whatever is causing these to happen
```
Your vendored results are different:
diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go /tmp/gopath.UfEUr6/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
--- vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go	2019-03-04 21:58:23.139775316 +0000
+++ /tmp/gopath.UfEUr6/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto /tmp/gopath.UfEUr6/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto 2019-03-04 22:00:54.000000000 +0000
# ...
--- vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto	2019-03-04 21:58:22.465714719 +0000
+++ /tmp/gopath.UfEUr6/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto	2019-03-04 22:00:54.000000000 +0000
# ...
```

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority critical-urgent
this is on release-blocking

**Comment by spiffxp** [comment]
/close
OK, it was poor form for me to re-open and re-purpose this issue, I opened ok I opened https://github.com/kubernetes/kubernetes/issues/74921 instead
