### ISSUE TITLE
Support Downward API for HostAliases

### ISSUE THREAD

**Issue by rickypai** [kubernetes/kubernetes#74265]
### What would you like to be added

Currently, HostAliases provide a way to inject entries into `/etc/hosts` files inside Pods.

While this is useful for previously-known static IPs, there are times when one would want to alias the IPs of dynamic resources like the Node IP or the Pod's own IP.

### Why is this needed

It's often useful for the Pod to know the IP of the host in order to access per-node resources like DaemonSet Pods or processes not controlled by Kubernetes. These processes are often responsible for shared concerns like stats or log aggregation.

For example, Datadog, a popular monitoring service, recommends users to host the `datadog-agent` daemonset using hostPort then using [downward API](https://www.datadoghq.com/blog/monitor-kubernetes-docker/#pass-the-node-s-ip-address-to-your-app) to communicate with the daemonset pods.

Supporting downward API for HostAlias would enable this pattern for applications that expect configuration through pre-determined hosts.

The usecase for Pod's own IP is less strong since one can just use `localhost` or pod name as the downward API which would alias to the Pod IP.

### Tentative Implementation

1. Modify `HostAlias` API to support `ResourceFieldSelector` in addition to `IP`
2. Add validations to ensure only either `ResourceFieldSelector` or `IP` is used at one point
3. Add validations to ensure only `status.hostIP` and `status.podIP` are valid values in  `ResourceFieldSelector`s
4. Modify kubelet `hostsEntriesFromHostAliases` to support downward dynamic IPs from the downward APIs https://github.com/kubernetes/kubernetes/blob/f52713515b8d526feed0f9111b3f075aaf463001/pkg/kubelet/kubelet_pods.go#L351-L364

I can complete this work should the idea be approved and there will be review support.

### Alternatives

This can also be achieved through topology-aware service routing. However, existing proposals all seem to have stalled (https://github.com/kubernetes/kubernetes/issues/28610, https://github.com/kubernetes/enhancements/issues/274)

https://github.com/kubernetes/enhancements/issues/536 seems the most promising as it supports different topology and node-locality. That said, `HostAlias` still supports a niche when the `Service` abstraction is not available, either due to static Pods used during cluster bootstrapping, or talking to processes that may not be Kubernetes managed :(

@yujuhong @thockin 

/sig node /sig network

**Comment by bjhaid** [comment]
> Supporting downward API for HostAlias would enable this pattern for applications that expect configuration through pre-determined hosts.

Does the below capabilities provided by the downward API[1] not address this:

```
spec.nodeName - the node’s name
status.hostIP - the node’s IP
```

we use datadog at my job and we inject `status.hostIP` into all pods.

1. https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

**Comment by rickypai** [comment]
@bjhaid not all applications support the configuration injection methods provided by the existing downward API. That's why `HostAlias` exists in the first place.

**Comment by aantono** [comment]
@bjhaid How exactly do you do such injection?

**Comment by bjhaid** [comment]
Downward API env vars

**Comment by rickypai** [comment]
@thockin @bowei the 1.15 development cycle just started. If you think the proposal is reasonable, I can own the implementation. Thanks a lot!

**Comment by reidab** [comment]
I've run across a similar issue running [Consul](https://www.consul.io/docs/platform/k8s/run.html) — the official helm charts for it recommend running a daemonset and injecting the IP using the downward API. This works great until TLS is enabled on the consul nodes and a client wants to enforce host checking on the certificate. The suggested path there is to generate the cert with a Subject Alternative Name, but I need to be able to inject the host's IP as an alias for that to work.

**Comment by JacobHenner** [comment]
This would be useful for me too (specifically, being able to reference status.podIP as the IP for a hostalias, and spec.nodeName as a component of the hostname). 

In my situation, sendmail expects the hostname of the container to resolve to an IP present in /etc/hosts. That /etc/hosts entry is expected to contain both the short hostname, and the fqdn. Since k8s does not supply such an fqdn in /etc/hosts, sendmail is unable to resolve the fqdn. [This leads to delays](https://salsa.debian.org/debian/sendmail/blob/master/sendmail/daemon.c#L3295).

If I could reference these variables directly, I could add something like:
```yaml
- ip: "${status.podIP}"
hostnames:
  - "${spec.nodeName}.localdomain"
```

**Comment by bowei** [comment]
Could these use cases be met by a sidecar or init container? Is the issue the fact that `/etc/resolv.conf` is owned by kubelet so its hard to mutate.
I see the value, but adding this particular downward API seems to be a one off. For instance, we would probably never refer to fields in the pod other than `status.{host,node}Name`? Do we have use cases outside of those fields?

**Comment by rickypai** [comment]
@bowei thanks a lot for giving the time to review this. The issue with init container/sidecar remains the same, which is that kubelet is responsible for the content of `/etc/resolv.conf` and `/etc/hosts`. While users can make modifications to those files, the modifications are lost on each container restart when kubelet re-mounts the volume.

This was the impetus for `HostAliases` in the first place: to provide a way to configure kubelet to inject additional entries into the `/etc/hosts` file: https://github.com/kubernetes/kubernetes/issues/43632

And this proposal is to slightly expand the capability of `HostAliases` to allow referencing dynamic variables like pod ip and host ip available through downward API. I hope this sounds reasonable.

**Comment by JacobHenner** [comment]
> Do we have use cases outside of those fields

podIP and nodeIP would both be useful. In my situation, podIP and nodeName would be necessary to accommodate sendmail's (misguided) assumptions about /etc/hosts, while maintaining /etc/hosts through the required HostAliases setting.

**Comment by rickypai** [comment]
@bowei could you take a look at this again and let me know what you think? I'd like to make sure this makes the various deadlines for 1.16. Let me know if it needs like a KEP or something.

**Comment by Pablo-CC** [comment]
This would be useful for me too, I am deploying the (https://docs.gitlab.com/charts/)[Gitlab Helm chart] and different component access some services via an Ingress controller which checks the host name for redirection. So, it will be useful if I could add several names (all the ingresses in `kubectl get ing`) under the same IP

**Comment by rickypai** [comment]
@bowei I still think this is useful and am willing to work on this if you think the idea is reasonable. Otherwise, we can just close this. We ended up using another workaround for this internally, but having this be supported by the API would be useful.

**Comment by timduhenchanter** [comment]
Can this be reconsidered?  It is valuable for the use cases presented by @rickypai

**Comment by yanghesong** [comment]
#107079 also has similar needs, if the idea is reasonable, I am willing to implement this function.
