### ISSUE TITLE
Support custom taints during e2e tests

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#74282]
**What would you like to be added**:
Support for users with clusters that have `NoSchedule` taints on specific nodes other than master nodes so that they can still run e2e tests.

**Why is this needed**:
It is a reoccurring problem that Sonobuoy users report problems with e2e tests failing to run on their clusters because of a setup which included custom taints.

 - Having looked briefly into the code it seems like plumbing a custom, allowed NoSchedule taint would be pretty extensive, is that correct?
 - Is the idea of _only_ supporting the master NoSchedule taint something that is deliberate/documented somewhere that I have not found it?
 - Is there a recommended workaround? If we assume their taints on the nodes are not flexible, the only option they would have would be to configure the test context to set `TestContext.AllowedNotReadyNodes=(number of non-master, unschedable nodes)`, is that correct? Is there a reason they shouldn't try and do that?

/sig testing

**Comment by johnSchnake** [comment]
So the relevant points of code are during the SyncrhonizedBeforeSuite section here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L103

and then in the wait logic here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2728-L2759

Most of the other uses of `LabelNodeRoleMaster` seem to be test setup, so extending the logic shouldn't be a problem, its just that those tests will be using the default control plane label.

I think we could accomplish this ticket if we were to replace the logic of "check for LabelNodeRoleMaster" and instead had a test context variable which had slice/map of labels which will be regarded as control plane nodes in which being unschedulable is OK.

The only complication is that this snippet outside of the test framework uses it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L588-L600

I'm not too familiar with that section but it isn't heavily used and it seems like it is just trying to find schedulable nodes. Would need to find the appropriate fashion to get this list of values ("control plane node labels" to it).

Am I missing the ball or does that seem accurate?

**Comment by timothysc** [comment]
I think plumbing through the test context makes sense, but you'd need to make certain all pods that are started are using the framework properly, which being honest (I don't know if they all are).

**Comment by neolit123** [comment]
it's unlikely that we can get the logic here to accommodate for all cases: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2750
e.g. a CP node can have a PreferNoSchedule taint.

so instead of having an algorithm that is universal, we should think of ways to let the user pick the nodes via a taint mask (e.g. "!NoSchedulable") or node mask (e.g. "*worker-node"). we also need to look at how/where this should be added. the CLI is already overloaded with flags. while the config is hard to deal with from test-infra jobs.

**Comment by johnSchnake** [comment]
@neolit123 You're just saying that you think a mask/filter will be even more flexible than a discrete list?  If I'm understanding you correctly then I agree, that does make sense. Either way we're just talking about getting the user to specify some value that will allow this `WaitForAllNodesSchedulable` to tolerate more/different unschedulable nodes, right?

As for where to put it, thats a fair point and I'll defer if people feel strongly. My 2cents is that because people are usually scripting around the tests and not running ginkgo (and all the flags) by hand each time, flag bloat isn't that big of a problem. I lack some historical knowledge on the flag/config file that might be relevant though.

**Comment by neolit123** [comment]
> You're just saying that you think a mask/filter will be even more flexible than a discrete list? If I'm understanding you correctly then I agree, that does make sense. Either way we're just talking about getting the user to specify some value that will allow this WaitForAllNodesSchedulable to tolerate more/different unschedulable nodes, right?

yes to both questions.

> As for where to put it, thats a fair point and I'll defer if people feel strongly. My 2cents is that because people are usually scripting around the tests and not running ginkgo (and all the flags) by hand each time, flag bloat isn't that big of a problem. I lack some historical knowledge on the flag/config file that might be relevant though.

depends on what we end up as an implementation. e.g. a full blown node list (no wildcards) on the command line for a big cluster is not ideal.

**Comment by johnSchnake** [comment]
Sorry if I was ambiguous; I wasn't ever suggesting a list of actual nodes (e.g. by names/ips or anything) but was suggesting a list of labels: currently the logic is effectively
 - Dont worry about schedulability if its labeled with (exactly) master

And I was just suggesting a custom label list so you'd say:
 - Dont worry about schedulability if it is labeled with (any of) [custom list]

The mask idea is fine too since it would just be a superset of this functionality:
 - Dont worry about schedulability if any of its labels matches (any of) [label regexp or something]

I'll put together something and see if there are any hiccups along the way.

**Comment by stevesloka** [comment]
Maybe a design doc would help discussions?

**Comment by neolit123** [comment]
> Maybe a design doc would help discussions?

sounds good. we can start with a google doc with public access linked from the OP of this ticket.

**Comment by johnSchnake** [comment]
Here is a doc for clarification and discussion:
https://docs.google.com/document/d/1iI9QdjPtL767ZjMB3WUxhEEd9mGO4aPtxXr7QOkztnE/edit#

**Comment by johnSchnake** [comment]
Convergence of effort; found that @liggitt was working on nearly the same thing here https://github.com/kubernetes/kubernetes/pull/76654 as I was working on my PR. It uses label selectors rather than my approach which was going to be using regexp or globbing. His is very idiomatic and still accomplishes the same goal.

If you know of a case where this wouldn't satisfy our need, please speak up, otherwise I'm going to endorse that approach.

**Comment by johnSchnake** [comment]
Talking with @liggitt about his approach and others discussed on/around his ticket, the intent has shifted slightly.

Rather than expand the special case handling to include other master-ish labels, there was a desire to get away from waiting for these types of labels at all and instead just check against a set of _known_ system taints which mark that the node isn't ready or the network isn't yet available.

The PR I linked to above had been put on the back burner and so I picked it up to try and get this in for 1.15. PR will be put up momentarily. See it for more details.

**Comment by xmudrii** [comment]
@johnSchnake Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by xmudrii** [comment]
@johnSchnake Any update on this?
