### ISSUE TITLE
[kubeadm] `kubeadm reset` ask for confirmation

### ISSUE THREAD

**Issue by jackielii** [kubernetes/kubernetes#74296]
**What would you like to be added**:
`kubeadm reset` should ask for confirmation to prevent accidental reset

**Why is this needed**:
Without the confirmation, the command can be easily executed by mistake

**Comment by xichengliudui** [comment]
K8s will ask your permission and then reset the cluster.
```
[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]:
```

**Comment by jackielii** [comment]
Might be my mistake, I just did a `kubeadm reset` on the master node and it proceeded without asking. And I regret to say it was a production server

**Comment by xichengliudui** [comment]
if you have no problem, please close this pr. thanks
