### ISSUE TITLE
kubelet v1.13.2 cannot patch node status occasionally

### ISSUE THREAD

**Issue by KielChan** [kubernetes/kubernetes#74302]
**What happened**:

After upgrade kubernetes from v1.9.11 to v1.13.2 in  place, some of node cannot patch its node status to kube-apiserver. Even kubelet cannot watch configMap because it `use of closed network connection`.

**What you expected to happen**:

kubelet can patch its status successfully

**How to reproduce it (as minimally and precisely as possible)**:

Not sure. At least 250 pods on the node, or upgrade kubelet from v1.9.11 to v1.13.2 in place?

**Anything else we need to know?**:

The problem occurs in k8s upgrades, almost 60 nodes upgrade successfully, but some of them report watch closed, and two of them cannot patch node status, and node not ready after 40s.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.2-2", GitCommit:"9b1517e9763225a100794a58d893c94e101c2c23", GitTreeState:"clean", BuildDate:"2019-02-13T09:58:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.2-2", GitCommit:"9b1517e9763225a100794a58d893c94e101c2c23", GitTreeState:"clean", BuildDate:"2019-02-13T09:56:10Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux vms70321 4.10.13-1.el7.elrepo.x86_64 #1 SMP Thu Apr 27 12:06:06 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

I cannot decrypt ssl file with tcpdump because DHE algorithm, also I cannot analysis tcp process with wireshark because client reset it after 10s(default), and nothing can be observed.
After rollbacking kubelet to v1.9.11, node become `Ready`

LOG:
```bash
I0218 20:50:07.250032   25079 request.go:942] Request Body: {"status":{"$setElementOrder/conditions":[{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"},{"type":"PIDPressure"}],"conditions":[{"lastHeartbeatTime":"2019-02-18T12:50:07Z","type":"MemoryPressure"},{"lastHeartbeatTime":"2019-02-18T12:50:07Z","type":"DiskPressure"},{"lastHeartbeatTime":"2019-02-18T12:50:07Z","type":"Ready"},{"lastHeartbeatTime":"2019-02-18T12:50:07Z","type":"PIDPressure"}]}}
I0218 20:50:07.250102   25079 round_trippers.go:416] PATCH https://master:6443/api/v1/nodes/node01/status?timeout=10s
I0218 20:50:07.250110   25079 round_trippers.go:423] Request Headers:
I0218 20:50:07.250116   25079 round_trippers.go:426]     User-Agent: kubelet/v1.13.2 (linux/amd64) kubernetes/9b1517e
I0218 20:50:07.250121   25079 round_trippers.go:426]     Accept: application/vnd.kubernetes.protobuf, */*
I0218 20:50:07.250126   25079 round_trippers.go:426]     Content-Type: application/strategic-merge-patch+json

I0218 20:50:17.309986   25079 round_trippers.go:441] Response Status:  in 10059 milliseconds
I0218 20:50:17.310004   25079 round_trippers.go:444] Response Headers:

E0218 20:50:17.516226   25079 kubelet_node_status.go:380] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"Ready\"},{\"type\":\"PIDPressure\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2019-02-18T12:50:07Z\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2019-02-18T12:50:07Z\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2019-02-18T12:50:07Z\",\"type\":\"Ready\"},{\"lastHeartbeatTime\":\"2019-02-18T12:50:07Z\",\"type\":\"PIDPressure\"}]}}" for node "svr3304hw2288": Patch https:// master:6443/api/v1/nodes/
node01/status?timeout=10s: context deadline exceeded
```
and

```bash
I0218 16:15:58.838129   42589 streamwatcher.go:107] Unable to decode an event from the watch stream: read tcp node01:56934->master:6443: use of closed network connection
I0218 16:15:58.838158   42589 reflector.go:357] object-"redis"/"envs-ttdarchmsgredis42-728336": Watch close - *v1.ConfigMap total 0 items received
I0218 16:15:58.838268   42589 round_trippers.go:416] GET https://master:6443/api/v1/namespaces/redis/configmaps?fieldSelector=metadata.name%3Denvs-ttdarchmsgredis42-728336&resourceVersion=171296292&timeout=6m9s&timeoutSeconds=369&watch=true
I0218 16:15:58.838275   42589 round_trippers.go:423] Request Headers:
I0218 16:15:58.838280   42589 round_trippers.go:426]     Accept: application/vnd.kubernetes.protobuf, */*
I0218 16:15:58.838285   42589 round_trippers.go:426]     User-Agent: kubelet/v1.13.2 (linux/amd64) kubernetes/9b1517e
I0218 16:15:58.838464   42589 streamwatcher.go:107] Unable to decode an event from the watch stream: read tcp node01:56934->master:6443: use of closed network connection
```

**Comment by KielChan** [comment]
maybe error happened in https, because I have test kubelet patch node status with insecure-address and insecure-port, it never failed

**Comment by lavalamp** [comment]
I'm not sure that it's related, but skipping versions is not supported or tested; at least not on the control plane, I'm not sure about nodes but the most you could skip while still being in the supported matrix is 1. It's actually pretty risky skipping versions.

If you roll forward one version at a time you'll at least have a much better idea of which version introduces the problem.

About this specific problem, I would check your certs / tokens.

Maybe read this over and double check your settings? https://kubernetes.io/docs/reference/access-authn-authz/node/

**Comment by KielChan** [comment]
Finnally, I have found why kubelet cannot patch its node status sometimes, ’cos more than 250 resources stay on the node, kubelet cannot watch more than 250 streams with kube-apiserver at the same time. So, I just adjust kube-apiserver `--http2-max-streams-per-connection` to `1000` to relieve the pain.

**Comment by lavalamp** [comment]
Nice find, thanks for letting us know the cause.

**Comment by YueHonghui** [comment]
@lavalamp 
We have decrypted the stream between kubelet and kube-apiserver. Also we have dumped the goroutine stacktrace and pprof trace of kubelet and kube-apiserver. Maybe these are useful to you. I will reference goroutine stacktrace blocked by condition wait of kubelet below.

[cwgid1.backtrace.zip](https://github.com/kubernetes/kubernetes/files/2908780/cwgid1.backtrace.zip)

**Comment by lavalamp** [comment]
Thanks!

**Comment by farrukh90** [comment]
> Finally, I have found why kubelet cannot patch its node status sometimes, ’cos more than 250 resources stay on the node, kubelet cannot watch more than 250 streams with kube-apiserver at the same time. So, I just adjust kube-apiserver `--http2-max-streams-per-connection` to `1000` to relieve the pain.

How did you do that? I mean how did you edit it?

**Comment by LeoLiuYan** [comment]
> > Finally, I have found why kubelet cannot patch its node status sometimes, ’cos more than 250 resources stay on the node, kubelet cannot watch more than 250 streams with kube-apiserver at the same time. So, I just adjust kube-apiserver `--http2-max-streams-per-connection` to `1000` to relieve the pain.
> 
> How did you do that? I mean how did you edit it?

Why the 250 streams is the upper limit?

**Comment by KielChan** [comment]
concurrent stream in client and server is same, 'cos http2 headers coordination. In Apiserver it's default value is 250, and in kubelet client is 1000, so just adjust apiserver's configuration `--http2-max-streams-per-connection` in v1.13.2

**Comment by caiconkhicon** [comment]
> concurrent stream in client and server is same, 'cos http2 headers coordination. In Apiserver it's default value is 250, and in kubelet client is 1000, so just adjust apiserver's configuration `--http2-max-streams-per-connection` in v1.13.2

How do you find the current streams in the connection? I mean the actual value, not the setting, so I can I find if it is my issue or not.

**Comment by KielChan** [comment]
@caiconkhicon 

Emmm... The master branch means `v1.13.2`, codes show as follow:

```
https://github.com/kubernetes/kubernetes/blob/master/vendor/golang.org/x/net/http2/transport.go#L770-L944

and internal function `awaitOpenSlotForRequest`

https://github.com/kubernetes/kubernetes/blob/master/vendor/golang.org/x/net/http2/transport.go#L948-L983
```
