### ISSUE TITLE
Minor resource leak/cleanup in subpath and other tests

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#74317]
While reading some of the e2es, I found following code to be suspect:

```
	cleanup := func() {
		if l.pod != nil {
			By("Deleting pod")
			err := framework.DeletePodWithWait(f, f.ClientSet, l.pod)
			Expect(err).ToNot(HaveOccurred(), "while deleting pod")
			l.pod = nil
		}

		if l.resource != nil {
			l.resource.cleanupResource()
			l.resource = nil
		}

		if l.testCleanup != nil {
			l.testCleanup()
			l.testCleanup = nil
		}
	}
```

This would mean that - if deleting a pod fails then rest of the cleanup code won't get executed. Which may be problematic for next test execution. 

/sig storage

cc @msau42

**Comment by msau42** [comment]
cc @pohly

**Comment by pohly** [comment]
I noticed that too. It has been a general pattern in several of the `AfterEach` functions. It's not limited to pod deletion either, `l.resource.cleanupResource()` and `l.testCleanup()` also probably have asserts.

I was pondering what to do about this. A better approach would be to distinguish between test setup (must use asserts) and tear down (no asserts, log errors). But even that is problematic: what if teardown partly fails? Who cleans up?

One can also argue that teardown should *not* continue after a failure. For example, if deleting a PVC fails, then the CSI driver handling it should not be removed, or the PVC will be stuck forever.

In the end there's no big difference between "clean up aborted" and "clean up failed and continued": some garbage gets left behind in both cases, and most likely the solution is the same in both cases - just bring up a new test cluster.

Regarding "may be problematic for next test execution": maybe, but well-written tests are able to run in parallel and thus must be (by definition) independent of test setup or teardown in other tests, so this is only an issue in tests that must run sequentially. I'm aware that the gcepd tests currently fall into that area, though.

**Comment by msau42** [comment]
The underlying disks represented by PVS do not get cleaned up by deleting the cluster immediately because cluster teardown immediately shuts down the controllers that are supposed to handle cleanup.

How about waiting to error at the very end of the cleanup function?  In the past we have had real issues with pod teardown that would have been easily caught by this.

**Comment by pohly** [comment]
What do you meant with "waiting to error"?

Do you want `framework.DeletePodWithWait()`, `l.resource.cleanupResource()` and `l.testCleanup()` to run even if one of them fails or panics (i.e. has an assertion failure)?

**Comment by msau42** [comment]
Correct although thinking about that more it would be hard to enforce. Methods called inside may also have assertion failures.

Is it reasonable to try to cleanup as much as we can, but in some failure cases there may need to be manual intervention?

**Comment by pohly** [comment]
We can wrap each call in a func which has a defer and catches exceptions there, so it can be enforced in a generic way.

I'm just not sure how much it will really help when, for example, deleting the pod which currently uses a volume fails.

**Comment by gnufied** [comment]
Can we not audit other cleanup functions being called from teardown and make sure they return error and not assert themselves?  What I ended up doing was - use `utilserrors.NewAggregate()` and gather all the errors and then assert at the end of teardown routine.

**Comment by pohly** [comment]
Sure, that also can be done. Now we just need a volunteer...

**Comment by pohly** [comment]
Just for reference, previously in 1.13 the code looked like this:
https://github.com/kubernetes/kubernetes/blob/96043d91a17435b1294e8427edf4c0eca8d25d0c/test/e2e/storage/testsuites/subpath.go#L185-L196

The driver cleanup then followed in:
https://github.com/kubernetes/kubernetes/blob/96043d91a17435b1294e8427edf4c0eca8d25d0c/test/e2e/storage/csi_volumes.go#L138-L141
