### ISSUE TITLE
deleting a finalizing resource should not fail

### ISSUE THREAD

**Issue by phillipao** [kubernetes/kubernetes#74334]
**What would you like to be added**:
This sequence fails:
$ kubectl delete ns foo --wait=false
$ kubectl delete ns foo --wait=true
Error from server (Conflict): Operation cannot be fulfilled on namespaces "foo": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.

I'd like for it to succeed.

**Why is this needed**: In my application, the first delete takes place several layers deep, on another server even. I can't do it synchronously. The second delete is in some test cleanup code.

I can work around the error by first checking whether the namespace is present and active before deleting. But it feels like that shouldn't be necessary, since deleting is an idempotent operation.

**Comment by yue9944882** [comment]
https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-448633260

deleting namespace should be done via request subresource

/remove-kind feature
/kind support

**Comment by phillipao** [comment]
Sorry, it's difficult to understand your response. Can you elaborate, please?

The comment you link to says to PUT something to the namespace's finalize subresource. I don't know what a "request subresource" is.

I can't find any documentation for the finalize subresource, but I suspect it's deleting finalizers because of a stuck delete. That's not the issue I'm talking about.

Also, I know how to check that whether the namespace is in terminating state before deleting, so I'm not looking for workarounds. I'm making a feature request.

**Comment by apelisse** [comment]
Hi @phillipao, 

If I understand properly, you're looking for a way to "re-attach" to the waiting deletion of the namespace, rather than get an error. So that you can wait until the previous deletion command finishes?

**Comment by phillipao** [comment]
exactly, yeah

**Comment by apelisse** [comment]
That sounds like a feature :-)

**Comment by phillipao** [comment]
To put another way, this sequence seems wrong:

`kubectl delete ns my-ns --ignore-not-found # succeeds`
`kubectl delete ns my-ns --ignore-not-found # fails, because terminating`
`kubectl delete ns my-ns --ignore-not-found # succeeds, because not found`

**Comment by apelisse** [comment]
I completely understand, and I agree. Not sure it can be done.

**Comment by apelisse** [comment]
Some of the logic to implement this might be on the client.

/remove-kind support
/kind feature
/sig cli

**Comment by yue9944882** [comment]
@phillipao Sry for misreading. I was referencing another unrelated issue.

/kind feature

> "re-attach" to the waiting deletion of the namespace

That conflict error is designed to prevent un-pre-conditioned deletion upon namespaces. And re-attaching deletion (if that's what you mean) should only be valid if it's a pre-conditioned deletion which also requires you to get the resource. It doesn't come easier than checking namespace's status I suppose. @adohe I'm also curious why there's no conditioned deletion support in kubectl?
