### ISSUE TITLE
simplify e2e.go

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#74353]
**What would you like to be added**:

#66649 and its PR #68483 made it possible to use test/e2e/framework outside of Kubernetes. But projects doing that (like https://github.com/intel/pmem-CSI/blob/d4bd9086d742701ba5b5fe10d413a2ed79a8fad4/test/e2e/e2e.go or https://github.com/intel/oim/blob/799b79eb01b4471a715f3f12b4c199a7c055c8ef/test/e2e/e2e.go) still need to copy a significant chunk of code. It would be better to move more of that code into the test/e2e/framework itself where it then can be reused.

One thing that has to be kept in mind is that the set of dependencies of the framework should not be increased by this.

**Why is this needed**:

Simplifies the writing of a custom E2E test suite.

**Comment by vinicyusmacedo** [comment]
@pohly I would like to work on this issue.

**Comment by pohly** [comment]
> I would like to work on this issue.

Thanks for the offer. Let's see whether I can assign it to you...

/assign @vinicyusmacedo 

If you want to discuss it further, feel free to reach out to the folks currently maintaining the E2E framework (the testing-commons sub-project of SIG-testing, see https://github.com/kubernetes/community/tree/master/sig-testing#subprojects). I'm less active there at the moment.
