### ISSUE TITLE
Health check by CSI driver

### ISSUE THREAD

**Issue by sarjeet2013** [kubernetes/kubernetes#74359]
**What would you like to be added**:

CSI driver should provide a way to inform CO about a bad health of an attach/mount and let CO reattach/remount request to the CSI driver again. There is no existing RPC for CSI that has support for it.

**Why is this needed**:

In some cases, the intermittent failure from the storage backend can remove the attached volume or fail the mount to the backend storage, and will linger the pod volume to an unknown state. The CSI driver should take appropriate action in this case, and if possible, It should inform CO to reattch/remount the volume operation again.

**Comment by msau42** [comment]
This feeds into an overall volume health feature. It would be beneficial to have a higher level overview of the problem space and user stories, especially considering the failure conditions of many of the CSI drivers out there.  I think we can break this out into multiple parts:

* How to surface unhealthy volumes?
* What kind of reactions would we want Kubernetes or external controllers to be able to take?

Some related proposals in this area:
https://github.com/kubernetes/community/pull/1484
https://github.com/kubernetes/enhancements/pull/766

**Comment by msau42** [comment]
cc @xing-yang @jingxu97 @NickrenREN

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by NickrenREN** [comment]
@sarjeet2013 , new KEP is here: https://github.com/kubernetes/enhancements/pull/1077
Comments are welcome, thanks

**Comment by sarjeet2013** [comment]
@NickrenREN Thanks for the link. I haven't gotten chance to review it yet, but what's the current status of KEP?

**Comment by xing-yang** [comment]
@sarjeet2013 We have not got much review comments since last update.  Your review is welcome.

**Comment by NickrenREN** [comment]
@sarjeet2013 sorry, we have not get much time to push the feature forward recently. Will do it soon, comments are welcome.

**Comment by xing-yang** [comment]
/remove-lifecycle stale

KEP is review in progress.  We are trying to get it in 1.18.

**Comment by xing-yang** [comment]
KEP was merged in 1.18.
CSI spec change was merged too: https://github.com/container-storage-interface/spec/pull/415
Implementation in kubernetes-csi is WIP.
