### ISSUE TITLE
Extract cloud provider specific credentialproviders

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#74379]
Splitting this out from the conversations in https://github.com/kubernetes/kubernetes/pull/70675, we are trying to remove cloud specific code into pluggable things, we should do the same with the credential providers too

/area cloudprovider

**Comment by andrewsykim** [comment]
Tracking issue for SIG Cloud Provider milestones https://github.com/kubernetes/cloud-provider/issues/13.

Hoping to have an alpha working version of this for v1.15

**Comment by ttousai** [comment]
Hello @dims ! I'm a bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. Code freeze is starting on August 29th (about 2 days from now).
Do we still target this issue to be fixed for 1.16?

**Comment by jonjohnsonjr** [comment]
FWIW these being in-tree is currently breaking a bunch of folks due to https://github.com/kubernetes/kubernetes/issues/81878

**Comment by kikisdeliveryservice** [comment]
hi @andrewsykim @cheftako @dims 

Bug Triage Release Team checking in. Code freeze for the 1.17 release is on November 18. Is this still intended for 1.17? Thanks!

**Comment by smourapina** [comment]
Hello @dims, @andrewsykim! 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18? Thanks in advance!

**Comment by cheftako** [comment]
Hi @smourapina, SIG Cloud-Provider is aiming for an alpha implementation in 1.18.

**Comment by cheftako** [comment]
https://github.com/kubernetes/enhancements/pull/1406

**Comment by markyjackson-taulia** [comment]
@dims @cheftako 
Are we staffed and still on-track for v1.18 release? Code freeze is slated for 3/5

**Comment by cheftako** [comment]
@nckturner ?

**Comment by markyjackson-taulia** [comment]
@nckturner,
Will this make it into v1.18?

![](https://apptimize.com/wp-content/uploads/2015/11/Code-Freeze.png)

**Comment by nckturner** [comment]
@markyjackson-taulia still planning on having this in by 1.18

**Comment by markyjackson-taulia** [comment]
> @markyjackson-taulia still planning on having this in by 1.18

@nckturner can you let me know what this is depends on? I would like to track that as we get closer to code freeze

**Comment by markyjackson-taulia** [comment]
@nckturner Circling back on this. Can you provide the details on what this depends on so I can ensure those items are tracked as we move closer to the 3/5 code freeze?

cc @dims  @cheftako

**Comment by markyjackson-taulia** [comment]
@nckturner do you think this is going to make the v1.18 code freeze date? 3/5 is rapidly approaching. If you don’t think so, let me know so I can move this in to the next milestone

**Comment by markyjackson-taulia** [comment]
@nckturner do you think this is going to make the v1.18 code freeze date? 3/5 is rapidly approaching. If you don’t think so, let me know so I can move this in to the next milestone

**Comment by markyjackson-taulia** [comment]
I had a chat today with @nckturner and he is optimistic this will land in 1.18. I will follow up again on Wednesday

**Comment by markyjackson-taulia** [comment]
@nickchase we are 24 hours out from code freeze. Can I get a temperature on this?

**Comment by markyjackson-taulia** [comment]
I will wait till mid day pst. If there is no exception I will move to the next version milestone

**Comment by nckturner** [comment]
@markyjackson-taulia just posted PR, let's see if there is possibility for it to land. https://github.com/kubernetes/kubernetes/pull/88813

**Comment by markyjackson-taulia** [comment]
Seems there is still work inflight and code freeze is here. I will move to v1.19

**Comment by markyjackson-taulia** [comment]
Filed for an exception:
https://github.com/kubernetes/enhancements/issues/1599
https://groups.google.com/forum/#!msg/kubernetes-release-team/dB6ZBZIzJG4/2nA9_qdgAwAJ

**Comment by markyjackson-taulia** [comment]
The exception was denied and therefore moving to v1.19
see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-release-team/dB6ZBZIzJG4/vhV1U9UyAAAJ for details

**Comment by dims** [comment]
tracked here https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/541-external-credential-providers

**Comment by enj** [comment]
> tracked here https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/541-external-credential-providers

`541` is for the `client-go` exec credential provider.  https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20191004-out-of-tree-credential-providers.md is the KEP for the cloud provider work.

**Comment by droslean** [comment]
@enj Since the code freeze is approaching, shall we move this to 1.20?

**Comment by enj** [comment]
@droslean I do not know the current status of this work (I am not on sig-cloud-provider).

**Comment by droslean** [comment]
@enj Thanks for the feedback. @dims WDYT?

**Comment by dims** [comment]
+1 to move it @droslean 

/milestone v1.20

**Comment by mkorbi** [comment]
Heyho @dims wanted to check how it is going?
As the issue is tagged for 1.20, is it still planned for this release?

**Comment by dims** [comment]
@mkorbi probably not. clearing the milestone
