### ISSUE TITLE
Pod object can be deleted before volumes have unmounted

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74372]
**What happened**:
As discovered in https://github.com/kubernetes/kubernetes/issues/74229, if a pod is is not long-running and ends in a success or failed state, when that Pod object is deleted, it [immediately deletes](https://github.com/kubernetes/kubernetes/blob/cbcc2b26fe214282290b2d8c9dabfbf2226fdeb6/pkg/registry/core/pod/strategy.go#L135-L138) the Pod object instead of waiting for volumes to be unmounted.

This scenario breaks the storage protection feature for volume types that do not have deletion protection built-in, such as nfs.

One way we may be able to fix this issue is to only set grace period to 0 if the Pod does not use a PVC volume source.

@kubernetes/sig-storage-bugs 

cc @cofyc

**Comment by liggitt** [comment]
> This scenario breaks the storage protection feature for volume types that do not have deletion protection built-in, such as nfs.

can you give more details about how this is broken?

**Comment by msau42** [comment]
The storage protection feature is supposed to prevent PVCs from being deleted until after Pods are done using them.  It does this by waiting for the Pod object to be completely deleted, which normally is how [kubelet signals](https://github.com/kubernetes/kubernetes/blob/62f5fd4c6c96ed33fb67aca8740ae660548f21df/pkg/kubelet/kubelet_pods.go#L900) that the volume has been unmounted.

In this case, when a pod is not long-running,
1. Pod is in success/terminated state in kubelet. Volume is still mounted.
2. Pod gets deleted by user. api server sets termination grace period to 0 and doesn't wait for kubelet to delete the Pod object.
2. PVC Protection controller sees that the Pod object is gone, removes finalizer from PVC.
3. PVC object is removed.
4. PV controller sees PVC is gone, triggers PV deletion.  Volume gets deleted from backend
5. Kubelet sees Pod deletion, starts volume cleanup process.
6. Volume manager tries to unmount the volume, but it ends up hanging forever because it's gone from the backend.
