### ISSUE TITLE
Need cross-OS test for service connectivity

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#74377]
Create a hybrid OS test that will have two services, one in linux and one in windows that talk to each other over flannel (Claudiu indicated this had some issues in his testing and we need to verify this)

We should create the test in such a way that can work with all supported CNIs

/sig windows

**Comment by michmike** [comment]
This is complete, right? @vyta

**Comment by vyta** [comment]
> This is complete, right? @vyta

@michmike  Yes, complete with PR #74550

**Comment by michmike** [comment]
/close 
PR is complete
