### ISSUE TITLE
`externalTrafficPolicy: Local` doesn't work well with nodeport for internal traffic

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#74383]
**What happened**:

Sending traffic from a pod (`hostNetwork: false`) to the nodeport (`externalTrafficPolicy: Local`) on another node is not working properly.

Below illustrate what happens:
![nodeport bug with only local](https://user-images.githubusercontent.com/8681801/53214479-a1dd1a80-3601-11e9-835a-4e353d7be67c.png)

To describe it in words:
- We have client podA running on nodeA, server podC running on nodeC.
- Client podA sends request to the nodePort on nodeB.
- On node B, the request gets DNAT to the actual backend podC, but doesn't get SNAT.
- Request reaches the server podC, and the response goes directly back to the client podA. It can't go through because the connection path is asymmetrical.

This seems to affect kube-proxy iptables mode but not sure about the others.

This can probably be fixed (if it's worth it) by adding iptable rules to SNAT the request that goes through nodePort chain, like what happens on nodePort service that uses `externalTrafficPolicy: Cluster`. Though the source IP will not be preserverd anymore.

**What you expected to happen**:
Pod should be able to send traffic to a nodeport service that uses local externalTrafficPolicy.

**How to reproduce it (as minimally and precisely as possible)**:
Created a similar setup as described above.

**Anything else we need to know?**:
cc @freehan @bowei @thockin 
@kubernetes/sig-network-bugs 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.0.1370+bfa587631168ae-dirty", GitCommit:"bfa587631168ae53b21fc5215c8e00a0a36e2e75", GitTreeState:"dirty", BuildDate:"2019-01-03T21:44:05Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by MrHohn** [comment]
Given that this (`externalTrafficPolicy: Local` with nodeport) is broken in a somewhat fundamental way and there is no clear plan for fixing it at the moment, let's punt this out of 1.14 for now.

/milestone clear

**Comment by thockin** [comment]
ping to @MrHohn

**Comment by MrHohn** [comment]
Removing triage/unresolved as this is a real issue that we should fix, or at least provide clarification on the expected behavior.
/remove-triage unresolved

**Comment by MrHohn** [comment]
This may need a similar fix as https://github.com/kubernetes/kubernetes/issues/74383 --- we should probably route local nodeport traffic to service chain and don't worry about the source IP preservation.

cc @andrewsykim

**Comment by andrewsykim** [comment]
@MrHohn PR I opened the initial PR for that here https://github.com/kubernetes/kubernetes/pull/77523 PTAL and let me know what you think. I think not worrying about source IP preservation and going to service chain makes sense to me

**Comment by MrHohn** [comment]
@andrewsykim Thanks! I was meant to ref your PR but pasted the wrong one :/

**Comment by andrewsykim** [comment]
Ah, that makes sense. Thanks!

**Comment by andrewsykim** [comment]
Let me know if you want me to adapt that PR to also account for node ports

**Comment by MrHohn** [comment]
> Let me know if you want me to adapt that PR to also account for node ports, otherwise I'll keep the PR to only account for LB IPs

Thanks Andrew, since your PR is tackling a more critical use case, feel free to focus on that and we can pick this up in the second pass.

**Comment by andrewsykim** [comment]
> This can probably be fixed (if it's worth it) by adding iptable rules to SNAT the request that goes through nodePort chain, like what happens on nodePort service that uses externalTrafficPolicy: Cluster. Though the source IP will not be preserverd anymore.

Similar to https://github.com/kubernetes/kubernetes/pull/77523, if we know the source is internal to the cluster (by checking cluster CIDR or --src-type=LOCAL) this seems reasonable to me as long as we're not changing source IP preservation rules from external traffic.

**Comment by MrHohn** [comment]
I can pick this up in the next release.
/remove-lifecycle rotten

**Comment by coryrjohnson** [comment]
Any update on if this might get fixed for NodePort services?

**Comment by andrewsykim** [comment]
@MrHohn are you still working on a fix for this? Happy to take this one

**Comment by MrHohn** [comment]
@andrewsykim Nope I'm not on this one at the moment, feel free to take it and thanks!

**Comment by aojea** [comment]
is this still happening?

**Comment by uablrek** [comment]
> is this still happening?

No. Tested on v1.23.3

/close

**Comment by uablrek** [comment]
Sorry, war a bit fast on that one. Missed that the addressed node MUST NOT have a local endpoint.
/reopen

**Comment by uablrek** [comment]
The problem still remains, but it is an unsupported case according to the "destination" model described in https://github.com/kubernetes/kubernetes/issues/108526. Even though the source is internal (a pod) traffic to the nodePort should be treated as "external" and as such it MUST NOT be routed to a node without a local endpoint for `externalTrafficPolicy: Local`.

I leave this issue open, but it should be closed if/when a consensus has been reached about the "destination" model.

**Comment by thockin** [comment]
Discussed in sig-net, this is WAI.  For ETP=Local, don't use node-ports on nodes that don't have backends.
