### ISSUE TITLE
translations/kubectl/... can't edit

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/kubernetes#74387]
**What happened**:
https://github.com/kubernetes/kubernetes/issues/74339

But when I found the path to the file I was trying to fix, I saw the last line:
```
// Code generated by go-bindata.
// sources:
// translations/OWNERS
// translations/extract.py
// translations/kubectl/OWNERS
// translations/kubectl/de_DE/LC_MESSAGES/k8s.mo
// translations/kubectl/de_DE/LC_MESSAGES/k8s.po
// translations/kubectl/default/LC_MESSAGES/k8s.mo
// translations/kubectl/default/LC_MESSAGES/k8s.po
// translations/kubectl/en_US/LC_MESSAGES/k8s.mo
// translations/kubectl/en_US/LC_MESSAGES/k8s.po
// translations/kubectl/fr_FR/LC_MESSAGES/k8s.mo
// translations/kubectl/fr_FR/LC_MESSAGES/k8s.po
// translations/kubectl/it_IT/LC_MESSAGES/k8s.mo
// translations/kubectl/it_IT/LC_MESSAGES/k8s.po
// translations/kubectl/ja_JP/LC_MESSAGES/k8s.mo
// translations/kubectl/ja_JP/LC_MESSAGES/k8s.po
// translations/kubectl/ko_KR/LC_MESSAGES/k8s.mo
// translations/kubectl/ko_KR/LC_MESSAGES/k8s.po
// translations/kubectl/template.pot
// translations/kubectl/zh_CN/LC_MESSAGES/k8s.mo
// translations/kubectl/zh_CN/LC_MESSAGES/k8s.po
// translations/kubectl/zh_TW/LC_MESSAGES/k8s.mo
// translations/kubectl/zh_TW/LC_MESSAGES/k8s.po
// translations/test/default/LC_MESSAGES/k8s.mo
// translations/test/default/LC_MESSAGES/k8s.po
// translations/test/en_US/LC_MESSAGES/k8s.mo
// translations/test/en_US/LC_MESSAGES/k8s.po
// DO NOT EDIT!
```

**What you expected to happen**:
fix https://github.com/kubernetes/kubernetes/issues/74339

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ceshihao** [comment]
I think it means you should modify corresponding files in translations instead of generated bindata.go

**Comment by xichengliudui** [comment]
Here's how I understand it: 
none of the files above the `// DO NOT EDIT!` can be edited. It's not that I want to edit the bindata.go file.
did I misunderstand?

**Comment by mattjmcnaughton** [comment]
I agree with @ceshihao that the comment is saying that you should not edit `pkg/kubectl/generated/bindata.go` and instead update the `translation/*` files.
