### ISSUE TITLE
Kubernetes worker node error on kube proxy and calico node

### ISSUE THREAD

**Issue by jshakk** [kubernetes/kubernetes#74382]
**What happened**: Installed kubernetes and docker in master and worker node successfully. However  getting the below error when tried to get the pods
kube-system   calico-node-mz9sc                                    0/1     PodInitializing
kube-system   kube-proxy-cz7cv                                     0/1     ContainerCreating

**What you expected to happen**:
Expected to successfully scale the replica. Since the worker node had issue, scaling happened in master node itself.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Here is the error:
kubectl describe pod calico-node-mz9sc --namespace=kube-system
Containers:
  calico-node:
    Container ID:
    Image:          calico/node:v3.5.1
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:275: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd1c5d1fd_35ee_11e9_928f_fa163ee640f0.slice/docker-d3c72950f35c9f94b00612c8ec05be9cdcd0f849eb5614f23036a68d6a864a82.scope: cannot allocate memory\"": unknown

kubectl describe pod kube-proxy-cz7cv --namespace=kube-system

      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:275: applying cgroup configuration for process caused \"mkdir /sys/fs/cgroup/memory/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod8847595c_3606_11e9_8f91_fa163ee640f0.slice/docker-ff25265a3889389f3ba614635f3fdd3b5a9ab8b288a9b0854e1e1426dc379a32.scope: cannot allocate memory\"": unknown

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): RHEL7 VM
- Kernel (e.g. `uname -a`):Linux **-*.**.******.com 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by xichengliudui** [comment]
I suggest you execute:
`apt update -y`
or
`systemctl daemon-reload && systemctl restart docker`
or all trying to execute

**Comment by jshakk** [comment]
> I suggest you execute:
> `apt update -y`
> or
> `systemctl daemon-reload && systemctl restart docker`
> or all trying to execute

Thank you, I did that and calico and kube-proxy went to pending state indefintely.
kube-system   calico-node-7kqhn                                    0/1     Pending
kube-system   kube-proxy-rl78q                                     0/1     Pending

when i described the pod, i got the below.
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  50m   default-scheduler  Successfully assigned kube-system/calico-node-7kqhn to ******.com

**Comment by nareshku** [comment]
I have noticed the same error.

Kubernetes version: 1.12.3
Docker Version: 17.03.2-ce
OS: RHEL 7, kernel 3.10.0-957.5.1.el7.x86_64
```
cat /sys/fs/cgroup/memory/memory.usage_in_bytes
5456760832 
# less than the limit 11083304960
```

from docker logs:
```
Mar  5 19:51:54 ip-10-98-210-248 dockerd: time="2019-03-05T19:51:54.032938184Z" level=error msg="Handler for POST /v1.27/containers/cf578a12e9a50f01ad1e727fced6b2326a1b11e0505e5976829aeae5934c7b68/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"mkdir /sys/fs/cgroup/memory/kubepods/burstable/pod0548afef-3558-11e9-a349-0676ba249136/cf578a12e9a50f01ad1e727fced6b2326a1b11e0505e5976829aeae5934c7b68: cannot allocate memory\\\"\"\n"
```

**Comment by nareshku** [comment]
I was not able to reproduce this issue with `docker version: 18.06.3`.

**Comment by TestAcct42** [comment]
Just adding my 2cents. 
I tried the systemctl daemon-reload && systemctl restart docker
That did not work for me. I had to reboot the box.  After rebooting, docker seemed to behave itself. I am not sure why it was acting that way. I am running updated version, but still suspect it's a possible kernal bug. 

Apologies for reopening, but I wanted to add my findings, as I was having this issue with one of my  nodes. 

Thanks!

**Comment by ryan4yin** [comment]
same problem, seems like the same issue: https://github.com/docker/for-linux/issues/841

**Comment by hellolittlewei** [comment]
我也出现了这个问题
unable to ensure pod container exists: failed to create container for [kubepods burstable pod0bd6fb3b-b5c6-41c6-a846-0c7843b27ee7] : mkdir /sys/fs/cgroup/memory/kubepods/burstable/pod0bd6fb3b-b5c6-41c6-a846-0c7843b27ee7: cannot allocate memory

**Comment by hellolittlewei** [comment]
> 我也出现了这个问题
> unable to ensure pod container exists: failed to create container for [kubepods burstable pod0bd6fb3b-b5c6-41c6-a846-0c7843b27ee7] : mkdir /sys/fs/cgroup/memory/kubepods/burstable/pod0bd6fb3b-b5c6-41c6-a846-0c7843b27ee7: cannot allocate memory

我运行nginx-ingress-controller

**Comment by wentfar** [comment]
unable to ensure pod container exists: failed to create container for [kubepods besteffort ] : mkdir /sys/fs/cgroup/memory/kubepods/besteffort/ : no space left on device

我也出现这个问题。。。
