### ISSUE TITLE
Controller will be hung for a while after restarting 

### ISSUE THREAD

**Issue by ricky1993** [kubernetes/kubernetes#74397]
**What happened**:
Our cluster has about 50k replicaset. Every time we restart controller, it will be hung for 15 minutes.
Replicaset controller's queue is full, and cannot handle the new sync request.
![image](https://user-images.githubusercontent.com/10073361/53225513-3c496680-36b3-11e9-81f0-0a11c6e4b629.png)

 
**What you expected to happen**:
After leader restarting, the standby should be the new leader and handle the new sync request rapidly.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.11
- Cloud provider or hardware configuration:
40Core, 192G memory
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
> * 1.10.11

@ricky1993 thanks for the report but 1.10 is outside of the support skew. please update!

/close

**Comment by ricky1993** [comment]
@neolit123 after updated, the problem is still exist at 1.12 version.
/reopen

**Comment by ricky1993** [comment]
Can we list & watch the object at stand-by controller? Once it get the lease, it can work faster?
@wojtek-t @lavalamp

**Comment by liggitt** [comment]
> Can we list & watch the object at stand-by controller? Once it get the lease, it can work faster?

It's quite expensive to maintain warm caches for an idle controller.

**Comment by liggitt** [comment]
Also, without the controller loops running draining the workqueues, they would grow indefinitely even if items were added/deleted

**Comment by wojtek-t** [comment]
+1 for what Jordan said - we would have to process all of them in a dry-run mode or sth. And what if then the master falls over our component and we already processed an item that master failed to process?

This will introduce a number of problems that don't exist now and would require a bunch of very careful thought-through.

**Comment by ricky1993** [comment]
I totally understand what you concern about. It is a really complicated work.
Another solution in my mind is using a independent init queue to process init event? We can add a option to switch it.
The problem is how to seperate the init events and we would add a worker for each controller to consume the init queue. But I think it may be more safe.
What do you think of that?

**Comment by wojtek-t** [comment]
Is this what you're talking about: https://github.com/kubernetes/kubernetes/pull/73203 roughly (as an infrastructure change we would like to use)?
I started looking into that some time ago, but didn't have time to push that forward. But I would have to think more whether it would really help for this case...

**Comment by ricky1993** [comment]
I have a quick through for the pr. I think it can partially fit this case.
Another problem is that can we process init events and watch events at the same time with two queues? 
I am not sure is there any risk. Maybe sync the same deployment in two threads at the same time?

**Comment by liggitt** [comment]
interleaving the init add events with later update/delete events is not desirable.

> I am not sure is there any risk. Maybe sync the same deployment in two threads at the same time?

that is exactly the risk, as well as processing add/update/delete events out of order

**Comment by wojtek-t** [comment]
out-of-order would be my main fear...

**Comment by liggitt** [comment]
The processing of the initial list is a fundamental part of the controller design, and is what makes it safe to restart a controller, or recover from a controller crash

/remove-kind bug
/close
