### ISSUE TITLE
`kubectl --namespace apply --prune` should prune within the namespace only

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubernetes#74414]
**What would you like to be added**:
Actually, the parameter `--prune` depends to all namespaces in the cluster. Filtering is only possible with labels. When running `kubectl --namespace NAMESPACE --prune -f ` the `prune` should only depend on the objects defined in `NAMESPACE`.

**Why is this needed**:
A typical use-case is having one repository and namespace per project. When working with declarative objects it should be possible to remove objects and get them pruned like having them described in the respository.
This would also help when renaming objects within the repository - which actually needs a manual `kubectl delete` on the host for the old objects.

This even could be a better solution for the problem described in https://github.com/kubernetes/kubernetes/issues/57916

**Comment by rdxmb** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by roycaihw** [comment]
cc @apelisse

**Comment by Liujingfang1** [comment]
We have been aware of the issues in prune and we want to improve it. 
Recently we opened a [KEP](https://github.com/kubernetes/enhancements/pull/810) for improving pruning in `kubectl apply`. With the proposed solution, the problem from current `--prune` will be fixed.

**Comment by mcary** [comment]
I just deleted a bunch of things in another team's namespace (:blush:).  I'd would love to have this feature.

**Comment by VojtechVitek** [comment]
Is there any workaround for this? I want to prune resources within a single namespace only.

**Comment by apelisse** [comment]
We're still working on improving prune, the current mechanism is broken enough that we don't recommend people us it.

**Comment by apelisse** [comment]
Also look like it's been fixed recently.

**Comment by yhack** [comment]
Can someone confirm if this is implemented? I tried using this feature with kubectl 1.18.2, which has https://github.com/kubernetes/kubernetes/pull/83084, yet as with previous versions kubectl it returned an error about pruning a nonNamespaced object of kind Namespace.

**Comment by njam** [comment]
>  it returned an error about pruning a nonNamespaced object of kind Namespace.

I assume the problem is that "Namespace" is a non-namespaced resource, and therefore is not filtered by namespace, so gets deleted by "prune".

As a workaround it's possible to manually pass a `--prune-whitelist` (whitelist of resources allowed to be deleted), and _not_ include "Namespace" in it:
```
kubectl apply --namespace=NAMESPACE -f test.yaml --prune --all --dry-run=server \
  --prune-whitelist=core/v1/ConfigMap \
  --prune-whitelist=core/v1/Endpoints \
  --prune-whitelist=core/v1/PersistentVolumeClaim \
  --prune-whitelist=core/v1/PersistentVolume \
  --prune-whitelist=core/v1/Pod \
  --prune-whitelist=core/v1/ReplicationController \
  --prune-whitelist=core/v1/Secret \
  --prune-whitelist=core/v1/Service \
  --prune-whitelist=batch/v1/Job \
  --prune-whitelist=batch/v1beta1/CronJob \
  --prune-whitelist=extensions/v1beta1/Ingress \
  --prune-whitelist=apps/v1/DaemonSet \
  --prune-whitelist=apps/v1/Deployment \
  --prune-whitelist=apps/v1/ReplicaSet \
  --prune-whitelist=apps/v1/StatefulSet
```
The list of resources is taken from [here](https://github.com/kubernetes/kubectl/blob/release-1.18/pkg/cmd/apply/prune.go#L176).

**Comment by foriequal0** [comment]
@njam I think wrapping this loop with `if !o.EnforceNamespace { ... }` would fix it.
https://github.com/kubernetes/kubectl/blob/release-1.18/pkg/cmd/apply/prune.go#L86-L90
