### ISSUE TITLE
[Failing Test] master-blocking:gce-cos-master-default diffResources

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#74417]
**Which jobs are failing**:
* [master-blocking#gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
* [master-upgrade#gce-new-master-upgrade-cluster-new-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel)

**Which test(s) are failing**:
* `master-blocking#gce-cos-master-default - diffResources`
  * [gubernator](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35102)
  * [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35102)
* `master-upgrade#gce-new-master-upgrade-new-cluster-new-parallel - diffResource`
  * [gubernator](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new-parallel/1464)

**Since when has it been failing**:
Started failing on 2/20. Failure coincides most closely with changes on [k/k, see diff](https://github.com/kubernetes/kubernetes/compare/f99728e6f...82b7a8a5e).
[k/test-infra diff](https://github.com/kubernetes/test-infra/compare/4546a6010...ef0e29b93)

**Testgrid link**:
* [https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
* [https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel)

**Reason for failure**:
Gubernator highlights to this failure:
```
W0222 13:50:26.482] 2019/02/22 13:50:26 main.go:307: Something went wrong: encountered 1 errors: [Error: 2 leaked resources
W0222 13:50:26.483] +NAME                                                            ZONE        SIZE_GB  TYPE         STATUS
W0222 13:50:26.483] +bootstrap-e2e-dynamic-pvc-6596a87d-36a4-11e9-8e3c-42010a8a0002  us-west1-b  5        pd-standard  READY]
W0222 13:50:26.488] Traceback (most recent call last):
W0222 13:50:26.489]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 764, in <module>
W0222 13:50:26.489]     main(parse_args())
W0222 13:50:26.489]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 615, in main
W0222 13:50:26.489]     mode.start(runner_args)
W0222 13:50:26.489]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W0222 13:50:26.490]     check_env(env, self.command, *args)
W0222 13:50:26.490]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0222 13:50:26.490]     subprocess.check_call(cmd, env=env)
W0222 13:50:26.490]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0222 13:50:26.490]     raise CalledProcessError(retcode, cmd)
W0222 13:50:26.491] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-master-image=gci', '--gcp-node-image=gci', '--gcp-nodes=4', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--publish=gs://kubernetes-release-dev/ci/latest-green.txt', '--test_args=--ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=50m')' returned non-zero exit status 1
E0222 13:50:26.508] Command failed
```

cc @mortent @kacole2 @mariantalla @smourapina

/kind failing-test
/priority important-soon
/sig storage

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by msau42** [comment]
I think this is the same issue: https://github.com/kubernetes/kubernetes/issues/74380

**Comment by mariantalla** [comment]
Prioritizing this to `critical-urgent` because it's been failing for a while, and across different dashboards.

/priority critical-urgent
/remove-priority important-soon

**Comment by alejandrox1** [comment]
Per @msau42's comment, https://github.com/kubernetes/kubernetes/issues/74380 was a solution for this one as well.
/close
