### ISSUE TITLE
1.14 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by onyiny-ang** [kubernetes/kubernetes#74425]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.14 Release Notes. If you know of issues or API changes that are going out in 1.14, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @dstrebel @jeefy @onyiny-ang @alenkacz

/sig release
/milestone v1.14

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release.  Please `/milestone clear` if I am incorrect

**Comment by fturib** [comment]
@chrisohaver : can you add here a comment about the known issue https://github.com/coredns/coredns/issues/2629 ? Thanks!

**Comment by chrisohaver** [comment]
There is a known [issue](coredns/coredns#2629) in CoreDNS 1.3.1, wherein if the Kubernetes API shuts down while CoreDNS is connected, CoreDNS will crash. The issue is [fixed](coredns/coredns#2529) in CoreDNS 1.4.0.

Let me know if more detail is needed.

**Comment by fturib** [comment]
workaround for this issue would be to use another version of CoreDNS : 1.3.0, or 1.4.0. 
Another possible solution is to mount an EmptyDir volume to /tmp.

**Comment by BenTheElder** [comment]
FYI a working CoreDNS issue link is at https://github.com/coredns/coredns/issues/2629 and fix link at https://github.com/coredns/coredns/pull/2529

**Comment by clkao** [comment]
kubelet might fail to restart if an existing flexvolume mounted pvc contains large number of directories, or is full. #75019

**Comment by BenTheElder** [comment]
@justaugustus is there something we should be doing here?

**Comment by onyiny-ang** [comment]
@BenTheElder @justaugustus These are created to catch known issues prior to the release so that they can be included in the release notes. The only reason I haven't closed this is because I am not sure whether or not it is useful for users to keep the issue open once the release has been cut--since other "known issues" may arise. If not, I'm happy to close this as well as the issue for 1.15.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/close
I looked back at other "known issues" issues going back to 1.9 and they never stayed open long enough to hit rotten.  Most were usually open / active for roughly a month, which I suspect lines up with when a patch release or two had been cut.  I think we can call this done.

**Comment by BenTheElder** [comment]
Makes sense! Thanks 😅
