### ISSUE TITLE
pull-kubernetes-cross flaking

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#74437]
Flake is of the form
```
I0222 21:07:23.771] +++ [0222 21:07:23] Building conformance image for arch: ppc64le
W0222 21:08:00.916] Cannot overwrite digest sha256:92857d647abe8d9c7b4d7160cd5699112afc12fde369082a8ed00688b17928a9
W0222 21:08:00.919] make[1]: *** [build] Error 1
```

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-cross shows nothing for it, presumably because the failures aren't wrapped in a junit.xml file that's parsed by kubernetes/test-infra/kettle

The job itself seems to be failing more often recently, but how many of these failures are due to this flake? https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-cross

- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/74153/pull-kubernetes-cross/9895 - #74153 (this PR is by far hitting it the most, could just be the one that's getting the most updates)
- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73819/pull-kubernetes-cross/9905 - #73819 
- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73930/pull-kubernetes-cross/9901 - #73930 
- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73555/pull-kubernetes-cross/9900 - #73555 
- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72939/pull-kubernetes-cross/9888 - #72939 
- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/71192/pull-kubernetes-cross/9868 - #71192 
- https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73983/pull-kubernetes-cross/9823 - #73983

/priority important-soon
/kind flake
/sig testing
/milestone v1.14

**Comment by spiffxp** [comment]
```
bentheelder [2:04 PM]
it's a flake
w/ docker

ixdy [2:04 PM]
I think because we are doing multiple builds at once
maybe

bentheelder [2:05 PM]
it crops up sometimes and then goes away for a long time, last time I dug I found some stuff about concurrent image pulls (incidentally kubernetes serializes these by default IIRC)
it's pretty rare usually, we've had it not happen for like more than a month
last time I dug into this it was actually painful to prove that it was just a flake because it goes so long between failures
I think we upgraded docker since I last saw it, but we're still on something a bit old (18.06.x in most places)
```

**Comment by ixdy** [comment]
to clarify, by "multiple builds at once" I mean "multiple `docker build`s at once".

**Comment by spiffxp** [comment]
/priority important-longterm
given that this doesn't run against every PR, in the context of v1.14 burndown this seems less important than flakes that impact jobs that run against every PR

**Comment by ibrasho** [comment]
Since code freeze is this Thursday and this is part of the 1.14 milestone, are there any plans to resolve it soon?

**Comment by BenTheElder** [comment]
pull-kubernetes-cross is now at consistency 1, all metrics look extremely healthy for the moment. failures in the history look legitimate.

We've made a number of changes that may have impacted this including upgrading docker, switching the build machines to PD-SSD instead of standard PD, and improving the build scripts slightly..

I think we can safely close this for now

/remove-lifecycle rotten
/close
