### ISSUE TITLE
Support dumping logs with log exporter for GCE windows nodes

### ISSUE THREAD

**Issue by pjh** [kubernetes/kubernetes#74439]
**What would you like to be added**:
Windows support in the logexporter daemonset (`cluster/log-dump/logexporter-daemonset.yaml`).

**Why is this needed**:
In https://github.com/kubernetes/kubernetes/pull/73442 we introduced support for Windows nodes in clusters on GCE. In https://github.com/kubernetes/kubernetes/pull/74438 I'm adding support for fetching logs from Windows nodes in GCE test clusters. For parity with Linux nodes the logexporter daemonset should be ported to work on Windows too.

**Comment by pjh** [comment]
/assign yujuhong

Since I can't assign issues to myself yet...

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release.  Please `/milestone clear` if I am incorrect

**Comment by yujuhong** [comment]
/milestone clear

This doesn't have to be in 1.14.

/assign @pjh

**Comment by pjh** [comment]
cc @yanglu1031
