### ISSUE TITLE
pull-kubernetes-integration flaking test test-cmd run_kubectl_run_tests

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#74431]
**Which jobs are failing**:
pull-kubernetes-integration

**Which test(s) are failing**:
test-cmd run_kubectl_run_tests

**Since when has it been failing**:
According to triage, the first failure was 2019-02-21 12:00 UTC

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

**Reason for failure**:
Unknown

**Anything else we need to know**:

This may be a flake? I can't tell yet.  The testgrid link is not a continuous failure, but it could be that not enough PR's have whatever change is causing the failure

Triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pr%3Apull-kubernetes-integration#1f13e06e89eca50e1cd8

It looks like it may be happening in CI as well https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Comment by spiffxp** [comment]
/remove-kind failing-test
/kind flake
I can't see it consistently happening in CI, so it must be a flake?

**Comment by spiffxp** [comment]
What I got when running locally...
```
job.batch "pi" deleted
Waiting for Get pods {{range.items}}{{.metadata.name}}:{{end}} : expected: , got: pi-dgspr:

run.sh:39: FAIL!
Get pods {{range.items}}{{.metadata.name}}:{{end}}
  Expected:
  Got:      pi-dgspr:

51 /Users/spiffxp/w/go/src/k8s.io/kubernetes/hack/lib/test.sh

!!! [0222 16:19:40] Call tree:
!!! [0222 16:19:40]  1: /Users/spiffxp/w/go/src/k8s.io/kubernetes/test/cmd/../../test/cmd/run.sh:39 kube::test::get_object_assert(...)
!!! [0222 16:19:40]  2: /Users/spiffxp/w/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:47 run_kubectl_run_tests(...)
!!! [0222 16:19:40]  3: /Users/spiffxp/w/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0222 16:19:40]  4: /Users/spiffxp/w/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:134 juLog(...)
!!! [0222 16:19:40]  5: /Users/spiffxp/w/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:465 record_command(...)
!!! [0222 16:19:40]  6: hack/make-rules/test-cmd.sh:109 runTests(...)
+++ exit code: 1
+++ error: 1
Error when running run_kubectl_run_tests
```

**Comment by spiffxp** [comment]
And I see the same thing in the build-log.txt for https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/74440/pull-kubernetes-integration/45980
```
I0222 23:56:51.553] (B[mjob.batch "pi" deleted
I0222 23:56:51.647] Waiting for Get pods {{range.items}}{{.metadata.name}}:{{end}} : expected: , got: pi-b7fp6:
I0222 23:56:51.648] [1m[31m
I0222 23:56:51.652] run.sh:39: FAIL!
I0222 23:56:51.653] Get pods {{range.items}}{{.metadata.name}}:{{end}}
I0222 23:56:51.653]   Expected: 
I0222 23:56:51.653]   Got:      pi-b7fp6:
I0222 23:56:51.653] (B[m[31m
I0222 23:56:51.654] 51 /go/src/k8s.io/kubernetes/hack/lib/test.sh
I0222 23:56:51.654] (B[m
I0222 23:56:51.692] +++ exit code: 1
I0222 23:56:51.697] +++ error: 1
I0222 23:56:51.747] Error when running run_kubectl_run_tests
```

**Comment by spiffxp** [comment]
Trying to track down the first occurrence.  I think there was an XML parsing error that was obscuring this that was fixed recently.  Backtracking through pull-kubernetes-integration failures and visually inspecting them.

https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/74440/pull-kubernetes-integration/45980 - run_kubectl_run_tests - 2019-02-22 15:45 PST

https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/45688/ - run_kubectl_run_tests - 2019-02-21 01:13 PST

https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73555/pull-kubernetes-integration/45612/ - run_kubectl_run_tests - 2019-02-20 16:50 PST

... and then I don't see this particular test failing during 02-19 or 02-18

**Comment by spiffxp** [comment]
So going by that, let's cast a net in commits that landed just prior to the earliest PR failure, and N hours prior
```
spiffxp@spiffxp-macbookpro:kubernetes (master %)$ git log --merges
# ...
commit 3baab4dc356f46335e72e88e7754b93898acff2c
Merge: 61b676aae1 6355186c3e
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Wed Feb 20 16:40:02 2019 -0800
# ...
commit ad403f8e2054d0dcd322e287af17cc3d69b38bf3
Merge: b96342ab92 713925bf3e
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Feb 19 23:20:41 2019 -0800
```

https://github.com/kubernetes/kubernetes/compare/ad403f8e2054d0dcd322e287af17cc3d69b38bf3...3baab4dc356f46335e72e88e7754b93898acff2c

**Comment by spiffxp** [comment]
Suspects
- https://github.com/kubernetes/kubernetes/pull/73201 - only because it touches test/cmd/core.sh
- https://github.com/kubernetes/kubernetes/pull/73866 - enables server side apply <-- this is my guess 
- https://github.com/kubernetes/kubernetes/pull/73959 - reduce lock contention in watchcache

**Comment by apelisse** [comment]
the test might be racy in the first place, maybe enabling the feature changes the time profile of the test.

**Comment by spiffxp** [comment]
Welp, now that I have what I think is a local repro loop for this, and I'm bisecting, it's looking like the whole commit range I suspected is fine 🙄

Looking closer, this particular test case is overly optimistic, it deletes a job and immediately gets pods expecting there to be none.  

I'd still like to nail down what timing change surface this before I go change the `get_object_assert` to a `wait_object_assert` or using a different set of flags for the `kubectl delete` call

**Comment by spiffxp** [comment]
Well, for some reason https://github.com/kubernetes/kubernetes/pull/74057 seems to be when the flakes started showing up

**Comment by apelisse** [comment]
I realize that the flake is hard to reproduce especially since it's hard to run specific tests in `test-cmd`. You can comment a lot of the tests by playing with some of these shell scripts so that they mostly just run the test you want to run. if you do so, you might be able to run 10/20 times the test in a row at this PR and before. I'm curious what the difference would be in term of flake rate.

**Comment by spiffxp** [comment]
Yeah that's what I've been doing.  It's https://github.com/kubernetes/kubernetes/pull/74057 and specifically looks to be 8c28d3f63c360d43d00c80091c6aac7f19afc259.  Which has nothing directly to do with pods, so I guess it's just a matter of this slowing the apiserver down just enough to start tripping a poorly written test.

**Comment by spiffxp** [comment]
FYI @liggitt  for the above.  My plan for now is just to rewrite the test so it's more forgiving.  But I wanted to confirm that it's expected / known that apiserver performance changed a bit as a result of this.

**Comment by liggitt** [comment]
> I wanted to confirm that it's expected / known that apiserver performance changed a bit as a result of this.

What metric are you seeing suffer with that commit? There should be no impact.

**Comment by apelisse** [comment]
A racy test goes from flaking 0% of the time to flaking 10-20% of the time

**Comment by spiffxp** [comment]
[This particular naive test case](https://github.com/kubernetes/kubernetes/blob/master/test/cmd/run.sh#L36-L39) flakes:
```
# Clean up
kubectl delete jobs pi "${kube_flags[@]}"
# Post-condition: no pods exist.
kube::test::get_object_assert pods "{{range.items}}{{$id_field}}:{{end}}" ''
```

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=integration#1f13e06e89eca50e1cd8

It should probably use `wait_object_assert` instead.  The thing is, I can't get it to flake before.

I hacked up test/cmd/legacy-script.sh to run just this, and none of the other test cases
```
for run in {1..100} do
    record_command run_kubectl_run_tests
done
```

**Comment by liggitt** [comment]
> It should probably use wait_object_assert instead.

It definitely should.

> The thing is, I can't get it to flake before.

I'll take a look at job->pod deletion propagation time before/after that commit, but there's nothing I can think of in that path a new networking API group would impact.
