### ISSUE TITLE
"make test-cmd WHAT=kubeadm" performs additional tests

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#74464]
this PR removed the script `./hack/make-rules/test-kubeadm-cmd.sh` which can be used to run the `cmd/kubeadm/test` integration tests.

https://github.com/kubernetes/kubernetes/pull/72939

the following command is claimed to be a replacement:
```
make test-cmd WHAT=kubeadm
```

but instead it runs unrelated tests too.

expecting the above command to only show the following output (run only kubeadm tests):
```
+++ [0223 22:28:56] Building go targets for linux/amd64:
    cmd/kubeadm
found packages rand (cgo1.go) and rand2 (cgo2.go) in /home/lubo-it/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/bazel-kubernetes/external/go_sdk/doc/progs
Running tests for APIVersion: v1,admissionregistration.k8s.io/v1beta1,admission.k8s.io/v1beta1,apps/v1,apps/v1beta1,apps/v1beta2,auditregistration.k8s.io/v1alpha1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,autoscaling/v2beta2,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1,coordination.k8s.io/v1beta1,coordination.k8s.io/v1,extensions/v1beta1,events.k8s.io/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,networking.k8s.io/v1beta1,policy/v1beta1,rbac.authorization.k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,scheduling.k8s.io/v1beta1,scheduling.k8s.io/v1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,storage.k8s.io/v1alpha1,
+++ [0223 22:29:16] Running tests without code coverage
ok  	k8s.io/kubernetes/cmd/kubeadm/test/cmd	29.694s
```

/assign @runyontr @spiffxp @cblecker 
@kubernetes/sig-cluster-lifecycle

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release.  Please `/milestone clear` if I am incorrect

**Comment by ibrasho** [comment]
Hey!

Gentle reminder that code freeze is this Thursday.

Since this is part of the 1.14 milestone, is it going to be resolved soon?

**Comment by neolit123** [comment]
hopefully in the next couple of days.

PR is here:
https://github.com/kubernetes/kubernetes/pull/74807
