### ISSUE TITLE
failed to create kubelet: only support unix socket endpoint

### ISSUE THREAD

**Issue by tiptop-labs** [kubernetes/kubernetes#74463]
**What happened**:

registered custom CRI by starting kubelet with extra options: `--container-runtime-endpoint=tcp://localhost:2000 --image-service-endpoint=tcp://localhost:2000 --container-runtime=remote` according to documentation [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md); kubelet did not start; error message in journalctl was: "failed to create kubelet: only support unix socket endpoint"

**What you expected to happen**:

 kubelet should have started because `kubelet --help` says for both `--container-runtime-endpoint` and `--image-service-endpoint`: "currently unix socket and tcp endpoints are supported on Linux"; custom CRI was listening on port 2000

**How to reproduce it (as minimally and precisely as possible)**:

e.g. add systemd fragment /etc/systemd/system/kubelet.service.d/20-cri.conf:
```
[Service]
ExecStart=
ExecStart=/usr/bin/kubelet --container-runtime-endpoint=tcp://localhost:2000 --image-service-endpoint=tcp://localhost:2000 --container-runtime=remote $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```

**Anything else we need to know?**:

current `pkg/kubelet/util/util_unix.go` does indeed forbid `protocol != unixProtocol`; so perhaps text for `kubelet --help` (in current `cmd/kubelet/app/options/options.go`) should be changed to "currently unix sockets are supported on Linux" (i.e. does not support tcp endpoints) to fix

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.3
- OS: Debian 9
- Install tools: kubeadm

@kubernetes/sig-node-bugs

**Comment by tiptop-labs** [comment]
I've added now @kubernetes/sig-node-bugs to the original text.

**Comment by feiskyer** [comment]
Thanks of reporting the issue, would file a PR to fix this.
