### ISSUE TITLE
[Failing Test] master-blocking: kubeadm-gce-master

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#74474]
@kargakis @lubinsz 

i have a suspicion that this PR broke a sig-apps test:
https://github.com/kubernetes/kubernetes/pull/74293
diff: https://github.com/kubernetes/kubernetes/compare/d6de0454e...b96378c05

**Which jobs are failing**:
kubeadm-gce-master
(release blocking)

**Which test(s) are failing**:
 [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]Changes

**Since when has it been failing**:
02-22

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master

**Reason for failure**:
```
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance] 1m30s
go run hack/e2e.go -v --test --test_args='--ginkgo.focus=\[sig\-apps\]\sDaemon\sset\s\[Serial\]\sshould\srollback\swithout\sunnecessary\srestarts\s\[Conformance\]$'
test/e2e/framework/framework.go:704
Expected
    <int>: 3
to equal
    <int>: 0
test/e2e/apps/daemon_set.go:418
```

/kind failing-test
/priority important-soon
/sig cluster-lifecycle
/sig apps

@kubernetes/sig-cluster-lifecycle 
cc @alejandrox1 @mariantalla

**Comment by kargakis** [comment]
Looks like framework.TestContext.CloudConfig.NumNodes is not set appropriately in the kubeadm test?

**Comment by neolit123** [comment]
i guess we need to set NUM_NODES explicitly for this deployer to work now with master.

by default, the value is bound to `--gcp-nodes` here:
https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L601-L603

the env variable NUM_NODES needs to be updated based on this value:
https://github.com/kubernetes/test-infra/blob/master/kubetest/anywhere.go#L60
(default 4)

> W0224 17:49:16.366]   Error in ./hack/ginkgo-e2e.sh:143. '"${ginkgo}"  ....<snip>"--num-nodes=${NUM_NODES}"} 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/2035/build-log.txt

what i don't understand is where the value of 3 is coming from. the number of worker nodes in that job is 4.

will send a PR for test infra regardless.

**Comment by kargakis** [comment]
> what i don't understand is where the value of 3 is coming from. the number of worker nodes in that job is 4.

There should be 3 old pods running since the new pod is unhealthy and the update is stuck at N-1 healthy

**Comment by BenTheElder** [comment]
> Looks like framework.TestContext.CloudConfig.NumNodes is not set appropriately in the kubeadm test?

IMO this probably needs to be auto-detected by the framework.

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by neolit123** [comment]
^ sent another attempt at fixing this:
https://github.com/kubernetes/test-infra/pull/11505

**Comment by alejandrox1** [comment]
Closing this, the test cleared out.
/close
