### ISSUE TITLE
Add kubectl `alias` command to allow reusing of complex commands

### ISSUE THREAD

**Issue by geymed** [kubernetes/kubernetes#74475]
**What would you like to be added**:
I would like to have the ability to create aliases for kubectl commands (similar to `git config --global alias...`)

**Why is this needed**:
This will boost the productivity of the tool and will allow performing frequent operations that requires a lot of typing faster.

/sig cli

**Comment by weeperscreepers** [comment]
Any reason regular old shell aliases don't work ?
If your k8s stuff is dockerized it seems like that would be really easy
