### ISSUE TITLE
Kubernetes service port stops listening when the "/var/log" directory is full".

### ISSUE THREAD

**Issue by vladwa** [kubernetes/kubernetes#74496]
Kubernetes service port stops listening when the "/var/log" directory is full".

Reproduce step:
1. Fill the /var/log directory. 

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5+coreos.0", GitCommit:"0d082e389e1f4311dc5d225eb77f9688c50d340a", GitTreeState:"clean", BuildDate:"2018-03-21T21:10:44Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5+coreos.0", GitCommit:"0d082e389e1f4311dc5d225eb77f9688c50d340a", GitTreeState:"clean", BuildDate:"2018-03-21T21:10:44Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider : AWS 

OS : 16.04.3 LTS (Xenial Xerus)

uname -a
Linux p-cshdp-kube-01.juniper.net 4.4.0-1072-aws #82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yowenter** [comment]
Let me work on it :-)

**Comment by Coderhypo** [comment]
provide some logs about kube-proxy? /sig network

**Comment by vladwa** [comment]
I dont see any logs roll over as /var/log directory is completely full. Once i clear the logs i need to restart kubelet service.

**Comment by yowenter** [comment]
So you mean when the /var/log is full, the kubelet will exit?
