### ISSUE TITLE
Ability to use LimitRanges without default values

### ISSUE THREAD

**Issue by yuripastushenko** [kubernetes/kubernetes#74507]
**What would you like to be added**:
Ability to use LimitRange without default values.
So the next type of pods will be rejected:
1) Pods with container specification without of limits and requests;
2) Pods with container specification limits and requests that don't fit in LimitRange min and max resources values.  

**Why is this needed**:
We provide k8s as service for our users inside the company.
We tell users to specify the requests and limits for containers in pods.
But some of them can simply forget about this.
We want to enforce them to do this.
We would like to reject all pods without explicit setting of its requests and limits in some namespaces.
For solving this problem we use ResourceQuota, that partially help us.
But we don't want to limit them in resources by namespace.
On the other hand - there is an instrument named "LimitRange", that gives the ability to set the min and max resources limits by namespace.  
But here we also have a problem - when setting LimitRange without default values - the default values are generated automatically from specified max limits, and for our clients it is not obvious that the requests and limits are set for their pods, when they don't specify any resources at all.
Its a kind of magic for them. And in some cases, they ask us - "Why does my containers was oom killed? I didn't specify any memory limits..."

**Comment by yuripastushenko** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yuripastushenko** [comment]
Hello!
@yliaog - can you comment this feature?

**Comment by yliaog** [comment]
If I understand it correctly, you would like to "reject all pods without explicit setting of its requests and limits in some namespaces", "But we don't want to limit them in resources by namespace."

In that case, you can create resource quota with *arbitrarily large* limits, that would satisfy both of your requirements listed above. You don't really need to use LimitRange.

**Comment by yuripastushenko** [comment]
This is not the only one behaviour that i want to have. I also want to
restrict users from creating pods with too large cpu requests.
For example:
maximum cpu requests per pod: 5 cpu.

пт, 1 марта 2019 г., 21:42 Yu Liao notifications@github.com:

**Comment by yuripastushenko** [comment]
My case is:
 I want to restrict users from creating pods with requests larger than 5
cpu, and also limit the namespace with 10 cpu requests.
And I dont want to set a default value for cpu requests because:
1) The user, that creates the pod better know what cpu requests should be
set.
2) If I will set the defaults - there will be cases, when  users will
forget to set the requests, and the default requests will be applied, and
in most cases those requests will be wrong...

пт, 1 марта 2019 г., 21:42 Yu Liao notifications@github.com:

**Comment by yuripastushenko** [comment]
@yliaog - cant you please comment my case?

**Comment by yliaog** [comment]
do you have to specify limits for container (in addition to pod)? If you just need to specify limits for pod, i think no default will be set automatically.

For example:
====================
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "200m" 
        memory: "6Mi"
===================
kubectl describe limits
Name:       resource-limits
Namespace:  default
Type        Resource  Min   Max  Default Request  Default Limit  Max Limit/Request Ratio
----        --------  ---   ---  ---------------  -------------  -----------------------
Pod         memory    6Mi   1Gi  -                -              -
Pod         cpu       200m  2    -                -              -
==================================================
with the above limits in place, the following pod cannot be created.
kubectl create -f pod.yml 
Error from server (Forbidden): error when creating "pod.yml": pods "busybox-sleep" is forbidden: [minimum cpu usage per Pod is 200m.  No request is specified., minimum memory usage per Pod is 6Mi.  No request is specified., maximum cpu usage per Pod is 2.  No limit is specified., maximum memory usage per Pod is 1Gi.  No limit is specified.]
=====================
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
=====================




However, if you have to specify container limits, then default will be set (default is the max).
cat limits.yml 
===========================
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "200m" 
        memory: "6Mi"
    -
      type: "Container"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "100m" 
        memory: "4Mi" 
=====================================================
kubectl describe limits
================================================
Name:       resource-limits
Namespace:  default
Type        Resource  Min   Max  Default Request  Default Limit  Max Limit/Request Ratio
----        --------  ---   ---  ---------------  -------------  -----------------------
Pod         cpu       200m  2    -                -              -
Pod         memory    6Mi   1Gi  -                -              -
Container   cpu       100m  2    2                2              -
Container   memory    4Mi   1Gi  1Gi              1Gi            -

**Comment by yuripastushenko** [comment]
Wow great!
Thank you a lot!
It is interesting that I didn't find anything about this ability (specifying LimitRange for pod) in documentation.
In documentation is described only case with LimitRanges on container.
But today i found an issue opened on k8s documentation that was stalled.
https://github.com/kubernetes/website/issues/9585

**Comment by yuripastushenko** [comment]
@yliaog I appreciate your help with this issue.
And if we already started this discussion, just to be clear, we have the behaviour:
```
LimitRanges with type "Container" have the behaviour:
If default resources are not specified - the defaults are the max.
```

I want to understand, what is the reason of setting default requests and limits in containers when specified max section in LimitRange on containers?

It seems that LimitRanges on Pods have different behaviour compared to LimitRanges on Containers.

What problems this behaviour solve?

Why k8s automatically creates the default requests and limits on container, when creating LimitRange with type "Container" and max section is specified?

And why k8s does not allow administrators to choose the behavior of such LimitRanges _(if i will specify defaults - they will be applied, if not - the pod with container that dont have specified resources - will be rejected)_?

Is there any architectural manifest or document where is described why LimitRanges on Containers **MUST** act using described behaviour _(from beginning if this comment)_?

**Comment by yliaog** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/admission_control_limit_range.md

is the design proposal for the LimitRange feature, it has the use cases, design considerations. Hopefully that could help answer your question.
