### ISSUE TITLE
Missing user mapping option for Quobyte storage based volumes

### ISSUE THREAD

**Issue by casusbelli** [kubernetes/kubernetes#74519]
**What happened**:
Containers cannot access Quobyte volumes provided via a Quobyte mount run by the Quobyte plugins mount command due to permission denied issues. Even if user mappings are provided these are ignored by the Quobyte client due to a missing mount flag.

**What you expected to happen**:
Access should work with the provided user mapping.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run Quobyte volumes without providing an externally managed plugin mount, thus allowing the Quobyte plugin to run the mount command.
2. Create Quobyte based StorageClass, PVC and pod desc.
3. Run the pod

**Anything else we need to know?**:
1. I'm preparing a pull request with a fix
2. Workaround is to run an externally managed mount for the plugin, e.g. via a systemd unit or a k8s daemonset. Ensure that mount activates the allow-usermapping-in-volumename option. In this case the plugin uses the existing mount.

**Environment**:
not relevant.
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig storage

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by gianarb** [comment]
Hello @casusbelli ,

I'm a bug triage shadow and I'd like to remind that code freeze is coming in 2 days (Friday, 8th March). :snowflake:  Is it still planned for this issue to be fixed for 1.14?

**Comment by casusbelli** [comment]
@gianarb I'm happy to merge this asap, ideas on how to bring this forward?
