### ISSUE TITLE
Minor issue  while running "make check" The below Error for  configure helper shell script at line 1872 

### ISSUE THREAD

**Issue by kishorebhat-p** [kubernetes/kubernetes#74515]
**Which jobs are failing**:TestEncryptionProviderFlag 

**Which test(s) are failing**:TestEncryptionProviderFlag 

**Since when has it been failing**:NA

**Testgrid link**:NA

**Reason for failure**:  Issue is presence of "-n" option at line 1872 in 
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh

configure_helper_test.go:133: Start kubernetes api-server
            ./configure-helper.sh: line 1872: local: -n: invalid option
            local: usage: local [option] name[=value] ...
        configure_helper_test.go:134: Failed to run configure-helper.sh: exit status 2

**Anything else we need to know**:

**Comment by nikopen** [comment]
/remove-kind failing-test
/close

Please open a "Bug Report" - 'failing tests' are for upstream-CI.
