### ISSUE TITLE
Minor issue  while running "make test" , The below error is seen where the configuration to run kube-apiserver is not correct

### ISSUE THREAD

**Issue by kishorebhat-p** [kubernetes/kubernetes#74516]
**Which jobs are failing**:TestEncryptionProviderFlag 

**Which test(s) are failing**:TestEncryptionProviderFlag 

**Since when has it been failing**:NA

**Testgrid link**:NA

**Reason for failure**:
Probably need to add encryption-provider-config in configure-helper.sh at line 1617 
params+=" --encryption-provider-config=${ENCRYPTION_PROVIDER_CONFIG_PATH}"

Error seen 

+++ [0131 14:52:16] Running tests without code coverage
--- FAIL: TestEncryptionProviderFlag (0.54s)
    --- FAIL: TestEncryptionProviderFlag/ENCRYPTION_PROVIDER_CONFIG_is_set (0.28s)
        configure_helper_test.go:136: Start kubernetes api-server
        apiserver_manifest_test.go:140: Got "exec /usr/local/bin/kube-apiserver --v=2  --cloud-config=/etc/gce.conf --address=127.0.0.1 --allow-privileged=true --cloud-provider=gce --client-ca-file=/foo/bar --etcd-servers=http://127.0.0.1:2379 --etcd-servers-overrides=/events#http://127.0.0.1:4002 --secure-port=443 --tls-cert-file=/foo/bar --tls-private-key-file=/foo/bar --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --enable-aggregator-routing=true --token-auth-file=/etc/srv/kubernetes/known_tokens.csv --service-account-issuer=https://foo.bar.baz --service-account-api-audiences=https://foo.bar.baz --service-account-signing-key-file=/foo/bar/baz.key --authorization-mode=Node,RBAC --allow-privileged=true 1>>/var/log/kube-apiserver.log 2>&1",
             want flags to contain "--encryption-provider-config=/tmp/configure-helper-test134522332/encryption-provider-config.yaml"
FAIL
FAIL    k8s.io/kubernetes/cluster/gce/cos       1.391s
--- FAIL: TestEncryptionProviderFlag (0.50s)
    --- FAIL: TestEncryptionProviderFlag/ENCRYPTION_PROVIDER_CONFIG_is_set (0.28s)
        configure_helper_test.go:136: Start kubernetes api-server
        apiserver_manifest_test.go:140: Got "exec /usr/local/bin/kube-apiserver --v=2  --cloud-config=/etc/gce.conf --address=127.0.0.1 --allow-privileged=true --cloud-provider=gce --client-ca-file=/foo/bar --etcd-servers=http://127.0.0.1:2379 --etcd-servers-overrides=/events#http://127.0.0.1:4002 --secure-port=443 --tls-cert-file=/foo/bar --tls-private-key-file=/foo/bar --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --enable-aggregator-routing=true --token-auth-file=/etc/srv/kubernetes/known_tokens.csv --service-account-issuer=https://foo.bar.baz --service-account-api-audiences=https://foo.bar.baz --service-account-signing-key-file=/foo/bar/baz.key --authorization-mode=Node,RBAC --allow-privileged=true 1>>/var/log/kube-apiserver.log 2>&1",
             want flags to contain "--encryption-provider-config=/tmp/configure-helper-test602044424/encryption-provider-config.yaml"
FAIL
FAIL    k8s.io/kubernetes/cluster/gce/custom    1.327s
--- FAIL: TestEncryptionProviderFlag (0.51s)
    --- FAIL: TestEncryptionProviderFlag/ENCRYPTION_PROVIDER_CONFIG_is_set (0.29s)
        configure_helper_test.go:136: Start kubernetes api-server
        apiserver_manifest_test.go:140: Got "exec /usr/local/bin/kube-apiserver --v=2  --cloud-config=/etc/gce.conf --address=127.0.0.1 --allow-privileged=true --cloud-provider=gce --client-ca-file=/foo/bar --etcd-servers=http://127.0.0.1:2379 --etcd-servers-overrides=/events#http://127.0.0.1:4002 --secure-port=443 --tls-cert-file=/foo/bar --tls-private-key-file=/foo/bar --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --enable-aggregator-routing=true --token-auth-file=/etc/srv/kubernetes/known_tokens.csv --service-account-issuer=https://foo.bar.baz --service-account-api-audiences=https://foo.bar.baz --service-account-signing-key-file=/foo/bar/baz.key --authorization-mode=Node,RBAC --allow-privileged=true 1>>/var/log/kube-apiserver.log 2>&1",
             want flags to contain "--encryption-provider-config=/tmp/configure-helper-test397202268/encryption-provider-config.yaml"
FAIL
FAIL    k8s.io/kubernetes/cluster/gce/gci       1.353s
--- FAIL: TestEncryptionProviderFlag (0.52s)
    --- FAIL: TestEncryptionProviderFlag/ENCRYPTION_PROVIDER_CONFIG_is_set (0.29s)
        configure_helper_test.go:136: Start kubernetes api-server
        apiserver_manifest_test.go:140: Got "exec /usr/local/bin/kube-apiserver --v=2  --cloud-config=/etc/gce.conf --address=127.0.0.1 --allow-privileged=true --cloud-provider=gce --client-ca-file=/foo/bar --etcd-servers=http://127.0.0.1:2379 --etcd-servers-overrides=/events#http://127.0.0.1:4002 --secure-port=443 --tls-cert-file=/foo/bar --tls-private-key-file=/foo/bar --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --enable-aggregator-routing=true --token-auth-file=/etc/srv/kubernetes/known_tokens.csv --service-account-issuer=https://foo.bar.baz --service-account-api-audiences=https://foo.bar.baz --service-account-signing-key-file=/foo/bar/baz.key --authorization-mode=Node,RBAC --allow-privileged=true 1>>/var/log/kube-apiserver.log 2>&1",
             want flags to contain "--encryption-provider-config=/tmp/configure-helper-test420478490/encryption-provider-config.yaml"

**Anything else we need to know**:
NA

**Comment by nikopen** [comment]
/remove-kind failing-test
/close

Please open a "Bug Report" - 'failing tests' are for upstream-CI.
