### ISSUE TITLE
AWS LB only creates in one availability zone

### ISSUE THREAD

**Issue by 1hanymhajna** [kubernetes/kubernetes#74527]
My issue is related to this issue #28586,
I see the same behavior in eks as well,

* All the subnets have the same tag that equal to the cluster name with shared value
* Added service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true" as annotations

But when i look to the AZ that added to the load balancer, it just add the one that have access to outside ( the other two AZ have subnets without connection to gateway (internal subnets)

When i added them manually it working fine

To make the things clear:
I have 3 subnets, everyone in different AZ
subnet 1
subnet 2
subnet 3

subnet 1 and 2 can go out to the worldwide (via internet gateway) using NAT that connected to subnet3

All of them with the same tags with value 'shared' value

**Comment by spender0** [comment]
same issue

**Comment by jralph** [comment]
Any news on this issue?

**Comment by gree-gorey** [comment]
I don't think that's Kubernetes related.
  
I was able to resolve this problem by creating public-facing subnets within AZ that has instances in private subnet with NAT gateway.
  
So, instead of having this layout:
```
AZ-a: instance-1 --- subnet-1 (private) -x- LB
AZ-b: instance-2 ---- subnet-2 (public) --- LB
AZ-c: instance-3 ---- subnet-3 (public) --- LB
```
You should do change it to this:
```
AZ-a: instance-1 --- subnet-1 (private) --- subnet-4 (public) --- LB
AZ-b: instance-2 ---- subnet-2 (public) ------------------------- LB
AZ-c: instance-3 ---- subnet-3 (public) ------------------------- LB
```
Here is the relevant AWS documentation:
https://aws.amazon.com/premiumsupport/knowledge-center/public-load-balancer-private-ec2/

**Comment by debu99** [comment]
any update?

**Comment by 1hanymhajna** [comment]
Our solution was to create two subnets in every AZ, one is private, and one is public with Nat gateway then it worked as expected
