### ISSUE TITLE
CSI migration check should handle invalid volume spec

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74553]
**What happened**:
Followup to https://github.com/kubernetes/kubernetes/pull/74493#discussion_r260069044: `useCSIPlugin` should be feature gated, and also needs to handle nil volume spec.

@kubernetes/sig-storage-bugs

**Comment by davidz627** [comment]
PR to do a feature gate check immediately. Handling nil volume spec needs to be investigated and designed in Migration for reconstruction code design

**Comment by tedyu** [comment]
useCSIPlugin already has this check:
```
	if !utilfeature.DefaultFeatureGate.Enabled(features.CSIMigration) {
		return false
```
Is there anything else which needs to be done for this issue ?

**Comment by davidz627** [comment]
/remove-lifecycle rotten
need to verify
