### ISSUE TITLE
Hostname setting in v1.PodSpec does not work for StatefulSets

### ISSUE THREAD

**Issue by anikammsft** [kubernetes/kubernetes#74564]
Upon creating a StatefulSet by setting the hostname field in the PodSpec section of the StatefulSet, the pod hostname does not change from what Kubernetes would otherwise set. When setting hostnames on Deployments and Replicasets, Kubernetes acts on this setting, but this behavior is different on StatefulSets.

To reproduce this, you can take the sample spec from [the StatefulSet documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) and add the following entry in spec->template->spec:
 hostname: myapp

I have attached the spec below that contains this setting.
[ss-test.yaml.txt](https://github.com/kubernetes/kubernetes/files/2903647/ss-test.yaml.txt)

Upon deploying this StatefulSet, you will find that the generated pods have hostnames web-0, web-1 and web-2 as they would be without the hostname setting. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration: kubeadm
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): 4.4.0-141-generic

@kubernetes/sig-api-machinery-bugs

**Comment by Joseph-Irving** [comment]
This is intentional, in https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_utils.go
```go
func initIdentity(set *apps.StatefulSet, pod *v1.Pod) {
	updateIdentity(set, pod)
	// Set these immutable fields only on initial Pod creation, not updates.
	pod.Spec.Hostname = pod.Name
	pod.Spec.Subdomain = set.Spec.ServiceName
}
```
It overrides the hostname field to be the pod name.

This makes sense as in statefulsets each pod should have a unique hostname.

**Comment by anikammsft** [comment]
Thanks for your quick response!
In that case, is it possible to add an enhancement that can take the user provided hostname value and append the same numeric extension to it as it does with the StatefulSet name to create pod names?

e.g.
If user provided the following:
hostname: myapp

Could we generate pod names such as myapp-0, myapp-1, etc. in case of StatefulSets?

**Comment by Joseph-Irving** [comment]
Is there a reason you can't just call your statefulset, `myapp`? If you have a very compelling and common user story for this it makes it easier to justify change.

It would definitely break from convention to have the pod names not match the name of the statefulset as all other pods created by another resource (e.g job, replicaset) follow the pattern of `resource-name-identifier`.

**Comment by anikammsft** [comment]
The issue in our product is that we want to join the pods to an Active Directory (AD) domain and running an AD service, unfortunately, requires that the hostname be only up to 15 characters. Since this is a very stringent requirement, we need to keep our statefulset names quite short to allow for a big count of pods. This ends up taking out information encoded in those names. We could essentially move that information into labels, however, they are not immutable. Moreover, there are ways that a customer of our product can deploy apps that can have long pod names and we would have to go a special route to cap the naming for them ending up in bad user experience. A lot of these problems would be significantly easier to manage if the hostname override is allowed for statefulsets.

**Comment by Joseph-Irving** [comment]
Right, I understand the issue but it currently seems quite specific to your setup. Also you would still need to ensure that your customers don't set hostname to be longer than 15 characters, so you'd be moving the problem elsewhere. 

If you want to progress this it's probably worth opening a feature request issue, describe the issue more generically and see if there are other use cases in the community that this would enable. You might also want to mention it in the sig-apps slack channel or add it the sig-apps agenda so that they can discuss it.

**Comment by anikammsft** [comment]
Thank you, Joseph! I have filed [feature request 74696](https://github.com/kubernetes/kubernetes/issues/74696).
