### ISSUE TITLE
ServiceAccount Token is mounted as rw------

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#74565]
Hi,

I try to update my cluster to v1.13.3 and I face issue with **ServiceAccount tokens**.

**What happened**:
The token is mounted as `rw- --- --- `

**What you expected to happen**:
It should be mounted as` rw-r-- r--` to allow other user than root to use the token (helm-tiller/ nginx-ingress..) 

I'm don't find any ressource that speak about this change or how to modify this configuration.

All my internal components (tiller, nginx, dashboard...) crash now. 

Thanks ! 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.3
- Cloud provider or hardware configuration: BareMetal
- OS (e.g: `cat /etc/os-release`): Debian 9
- Install tools: Saltstack / managed with Systemd

**Comment by WanLinghao** [comment]
Do you mean inside container or outside container?

**Comment by neolit123** [comment]
/sig auth
(?)

**Comment by valentin2105** [comment]
@WanLinghao  Yes, I mean inside the container, in /run/secret/kubernetes.io/token

**Comment by WanLinghao** [comment]
@valentin2105 I didn't find v1.13.3 branch.

**Comment by valentin2105** [comment]
@WanLinghao  The ls -alh need to be made on ../data/token , because here it's just a symlink.

**Comment by mikedanese** [comment]
Do you have alpha features enabled?

**Comment by valentin2105** [comment]
Hi @mikedanese , 

Thanks I think it's my issue because I use `AllAlpha=true` on my api-server. 
What's the way to disable only **TokenRequestProjection** ? 
Thank you.

**Comment by mikedanese** [comment]
`AllAlpha=true,TokenRequestProjection=false`, or you can fix the issue :). TokenRequestProjection is a lot better than the old token volumes. The permission lockdown is intended to improve security, but we bundled a bunch of other security improvements in that feature as well. All improvements and breaking changes are recorded in #70679.

I'd love to get feedback on what made this difficult for you to adopt so we can figure out how to advance this feature with minimal impact to users. What made you notice the permission change? Are you running containers as non-root users? You can use fsGroup and supplemental groups to correct file permission issues. There are some examples of this here: https://github.com/kubernetes/kubernetes/commit/8bcb178da38fe728c760541902c2d453930a9416#diff-7f3dae733c7b50bebdc8ecd4bf2550fe

**Comment by valentin2105** [comment]
Thanks for pointing me the right way to inquire the non-root user which will use the token.
It was my issue, Helm's tiller / CoreDNS or Nginx-Ingress run at non-root user (nobody) and was not able to use the Account token. 

So by adding : 

```
      securityContext:
        supplementalGroups: [ 65534 ]
        fsGroup: 65534
```

To my deployment, it should fix my issue ? 

I will try that. Thank you so much.

**Comment by mikedanese** [comment]
@valentin2105 Sorry for the slow response. Clients need to re-read the token periodically from disk. k8s.io/client-go has already been updated to do this since version 10.0.0 (kubernetes version 1.13). Can you point me towards the failing helm chart?

**Comment by valentin2105** [comment]
Thanks, I think I need to use latest release of my deployments apps (helm / nginx-ingress / coreDNS).
