### ISSUE TITLE
CSI translation library should export an interface instead of functions

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#74594]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/csi-translation-lib/translate.go exports number of functions. It's hard to unit test anything that calls the library. It would be much easier if the library exported interface(s) so individual unit tests could mock it out or add its own translation func into the global variable.

/sig storage 

@davidz627 @ddebroy

**Comment by davidz627** [comment]
fair point. We considered it at first but it seemed kind of weird to have to initialize an object for using the translation library every time we wanted to use it. I see the value in it being mocked out though.

**Comment by davidz627** [comment]
/remove-lifecycle stale
woudl still be a nice change

**Comment by davidz627** [comment]
I think actually this is an anti-pattern in golang:
https://github.com/golang/go/wiki/CodeReviewComments#interfaces
https://twitter.com/davecheney/status/942593128355192832?lang=en
https://medium.com/@cep21/preemptive-interface-anti-pattern-in-go-54c18ac0668a

/close
please re-open if this is incorrect
