### ISSUE TITLE
add more logging in azure disk attach/detach

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#74598]
**What happened**:
add more logging in azure disk attach/detach

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

**Comment by tpepper** [comment]
The issue message here doesn't say why a change was desired.  The PR "Original logging is not clear when dealing with managed disk, since diskName is empty".  That's more informative.
