### ISSUE TITLE
Unable to create a PVC because it says spec.dataSource is now required

### ISSUE THREAD

**Issue by Sher-Chowdhury** [kubernetes/kubernetes#74597]
**What happened**:
I'm trying to apply the following:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: pvc-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
```

However i get the following error message:

```bash
$ kubectl apply -f configs/pvc-example/pvc-obj-def.yml 
error: error validating "configs/pvc-example/pvc-obj-def.yml": error 
validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required; 
if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:

It should have successfully create the pvc object. However one thing I discovered that it does work successfuully if I comment out the 'apiVersion' line and then reattempt the apply:

```bash
$ kubectl apply -f configs/pvc-example/pvc-obj-def.yml 
persistentvolumeclaim "pvc-db" created
$ kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc-db    Bound     pvc-d7004148-39c7-11e9-8b76-080027635baa   1Gi        RWO           standard       5s
```

**How to reproduce it (as minimally and precisely as possible)**:
I'm working with a minikube provisioned kubecluster on my macbook. 

```bash
$ minikube version
minikube version: v0.34.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

I'm using the version of Virtualbox version 6.0.4.

**Comment by Joseph-Irving** [comment]
I can reproduce this with kubectl version `1.6.2` and kubernetes version `1.13.3`. However this issue is not present with a later version kubectl version such as `1.13.3`.

Kubectl is only guaranteed to work with kubernetes clusters that are +/- 1 minor version. So I recommend updating your kubectl.

**Comment by Sher-Chowdhury** [comment]
Hi @Joseph-Irving 

Thanks for looking into this. I'm pretty sure I hav the latest version of kubectl, but I did try upgrading just to be sure:

```bash 
$ brew upgrade kubernetes-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

Error: kubernetes-cli 1.13.3 already installed
$ 
```

I'm quite new to Kubernetes, but I think you might have the versions the wrong way round. My Kubernetes version is 1.6.2 and my kubectl version is 1.13.3 (as mentioned in my ticket above).

**Comment by Joseph-Irving** [comment]
the output you showed in your issue:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
shows server as `1.13.3` and client (aka kubectl) as `1.6.2`

Just because brew says kubernetes-cli is installed doesn't mean that's what's in your path, you can try `which kubectl` to help determine which binary you're using.

**Comment by Sher-Chowdhury** [comment]
My apologies, you were correct in the first instance. I got the version numbers mixed up. 

Ok I managed to fix it now. To help others, here's what I did to fix it, first I uninstalled kubectl via the homebrew approach:

```bash 
$ brew remove kubernetes-cli
```

Then tracked down the old kubectl binary and renamed it:

```bash
$ which kubectl
/usr/local/bin/kubectl
$ mv /usr/local/bin/kubectl /usr/local/bin/old-version-kubectl
```

Then reinstalled kubectl again:

```bash
$ brew install kubernetes-cli
```

The versions are now the latest:

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

I tried creating the pvc again and it worked. Many thanks @Joseph-Irving for pointing me in the right direction.
