### ISSUE TITLE
"request too large" results with 5xx error in 1.10 cluster

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#74600]
I was browsing through some master logs investigating 5xx errors and found that:

"logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"etcdserver: request is too large\",\"code\":500}\n""

in and 1.10 cluster. Too large requests shouldn't result in 5xx error codes.

I don't know if this was fixed in a newer release, so I'd like to ask someone to triage.

@kubernetes/sig-api-machinery-bugs @lavalamp @liggitt @smarterclayton

**Comment by yowenter** [comment]
which API you've requested? and any api server log s ?

**Comment by gmarek** [comment]
For custom resource, but it shouldn't matter - the error comes from the etcd, which doesn't care about APIs (if we didn't start to leak more details in the store abstraction when I wasn't looking).

**Comment by oomichi** [comment]
Does this mean the API request contain large values on metadata and apiserver outputs it directly without input validation?
If so, https://github.com/kubernetes/kubernetes/issues/74620 seems helpful for this issue.

**Comment by roycaihw** [comment]
I think it's fixed by https://github.com/kubernetes/kubernetes/issues/74600 and cherry-picked to 1.11+. My understanding is apiserver returns 413 StatusRequestEntityTooLarge on large requests

cc @caesarxuchao to confirm

**Comment by liggitt** [comment]
> I think it's fixed by #73805 and cherry-picked to 1.11+. My understanding is apiserver returns 413 StatusRequestEntityTooLarge on large requests

the limits added in that PR are larger than the typical etcd document limits, so I wouldn't expect it to prevent all etcd errors

**Comment by roycaihw** [comment]
@liggitt you're right. I forgot that limit (100MB) is way larger than the etcd limit we use

related issue: https://github.com/kubernetes/kubernetes/issues/47668#issuecomment-397029553
related WIP PR: https://github.com/kubernetes/kubernetes/pull/67317

when etcd / gRPC error message occur, apiserver should handle and return a constant error message (413)

**Comment by gmarek** [comment]
To be fair - etcd returning 5xx for 'too large request' is also wrong.

**Comment by roycaihw** [comment]
cc @jpbetz

**Comment by akhil-rane** [comment]
I feel response code here should be 400 - Bad request instead of 500.
