### ISSUE TITLE
Provide full list of options for "reason" when consuming Kubernetes events

### ISSUE THREAD

**Issue by tomkerkhove** [kubernetes/kubernetes#74607]
**What would you like to be added**: Provide full list of options for "reason" when consuming Kubernetes events

**Why is this needed**: This would allow consumers to provide more accurate consumption of these events. Nowadays there is not a straight-forward approach of processing them, as far as I know.

Bonus points if we can generate and use those lists in our clients like [https://github.com/kubernetes-client/csharp](https://github.com/kubernetes-client/csharp)

If this is documented somewhere, please do tell me!

**Comment by tomkerkhove** [comment]
Not sure which sig is most suitable for this, instrumentation will do I guess - @kubernetes/sig-instrumentation-misc

/cc @brendanburns 	as we were talking about this earlier.

**Comment by brancz** [comment]
Events can be produced by any component, including add on components, so I don't think we can have a true set of possible values.

**Comment by tomkerkhove** [comment]
That's what I was afraid of - Probably not even a Kubernetes-only list as well?

**Comment by brancz** [comment]
You could search through the kubernetes code base, but as far as I know there is no 1 list of values anywhere, they're just defined where used.

**Comment by tomkerkhove** [comment]
Forgot to circle back to this, sorry for that!

However, I think it would be great if we could have a central location which defines all events and when they occur. Now it's hard as a consumer to know what event represents what.

/cc @brendandburns
