### ISSUE TITLE
[Failing Test] [sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path tests failing

### ISSUE THREAD

**Issue by kacole2** [kubernetes/kubernetes#74626]
**Which jobs are failing**:
- [sig-release-1.14-all/gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default)

**Which test(s) are failing**:
- [[sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path 29s](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-default/9490#sig-scheduling-preemptionexecutionpath-runs-replicasets-to-verify-preemption-running-path)

**Since when has it been failing**:
- since 2019-02-25 @ 4:15
- [Compared Commit Changes](https://github.com/kubernetes/kubernetes/compare/506e8dc9e...39dac9a88)

**Testgrid link**:
- [sig-release-1.14-all/gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default)

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:401
Expected
    <bool>: false
to equal
    <bool>: true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:431
```

**Anything else we need to know**:

/kind failing-test
/priority important-soon
/sig scheduling
/milestone 1.14

**Comment by Huang-Wei** [comment]
I will take a look.

/assign

**Comment by Huang-Wei** [comment]
@kacole2 is it possible to simulate a `gke-cos` env? The e2e test only failed on `gke-cos` (even `gck-cos` is good), and the error occurs when trying to create a PriorityClass API object.

If it's infeasible, I suppose the only way to debug is to put a temp PR printing more info and wait for `gke-cos` test suite to pick up, and then check the logs?

**Comment by alejandrox1** [comment]
This seems to also present in [sig-release-1.14-all#gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default).

**Comment by Huang-Wei** [comment]
update: waiting for https://github.com/kubernetes/kubernetes/commits/release-1.14 to pick up PR #74744 so as to expose more clues.

**Comment by Huang-Wei** [comment]
The errors shows it can't create a regular v1 PriorityClass:

```
Mar  1 17:13:36.107: INFO: Failed to create priority 'p1/1': the server could not find the requested resource
Mar  1 17:13:36.107: INFO: Reason: NotFound. Msg: the server could not find the requested resource
```

And even can't list PriorityClass:

```
Mar  1 17:13:55.869: INFO: Unable to list priorities: the server could not find the requested resource
```

It looks like a HTTP 404 error when fetch/create v1 PriorityClass.

@liggitt @bsalamat any clues? (this occurs only in [gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default))

**Comment by bsalamat** [comment]
/assign

@Huang-Wei Thanks for investigating it. Looks like we need to enable the API on the GKE side. I will do that.

**Comment by Huang-Wei** [comment]
Oh, I thought the API enabling is by default (at least for v1). So you mean there is a sort of "whitelist" configured in GKE to specify which particular APIs are enabled?

**Comment by bsalamat** [comment]
Not that we have any blacklisted API that I know, but API versions must be explicitly enabled.

**Comment by Huang-Wei** [comment]
Got it. Thanks for the explanation.

**Comment by bsalamat** [comment]
GKE changes are merged. Let's wait for the next run of the test.

**Comment by Huang-Wei** [comment]
Latest 3 runnings are green.

**Comment by liggitt** [comment]
great

/close
