### ISSUE TITLE
Obtain cloud controller status via `kubectl get cs`

### ISSUE THREAD

**Issue by m3ngyang** [kubernetes/kubernetes#74643]
**What would you like to be added**:
Users can obtain cloud controller status via `kubectl get cs`, for example,
```
# kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
cloud-controller     Healthy   ok
etcd-0               Healthy   {"health": "true"}
etcd-1               Healthy   {"health": "true"}
etcd-2               Healthy   {"health": "true"}

# kubectl get cs cloud-controller -o json
{
    "apiVersion": "v1",
    "conditions": [
        {
            "message": "ok",
            "status": "True",
            "type": "Healthy"
        }
    ],
    "kind": "ComponentStatus",
    "metadata": {
        "creationTimestamp": null,
        "name": "cloud-controller",
        "selfLink": "/api/v1/componentstatuses/cloud-controller"
    }
}
```

**Why is this needed**:
For kubernetes deployed in cloud, `cloud controller` is a key master-like component, as important as `controller-manager`. It status may be included and printed via `kubectl get cs`. 
Currently, `component status` only detects health of `controller-manager` and `scheduler` besides `etcd`s, supposing they are deployed on the same node. Another problem is that how to design an elegant way to detect health of `cloud controller` because it can be deployed in different ways by cloud providers.

https://github.com/kubernetes/kubernetes/blob/38a325250fbefa8785740d00358978eefa160dde/pkg/registry/core/rest/storage_core.go#L255-L258

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/pull/82247#discussion_r322381376 and https://github.com/kubernetes/enhancements/issues/553#issuecomment-529591505 for why this behavior does not belong in the kube-apiserver
