### ISSUE TITLE
[Failing test] Before Suites failing for ci-kubernetes-node-kubelet-beta in 1.14-blocking

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74658]
**Which jobs are failing**:
ci-kubernetes-node-kubelet-beta in [sig-release-1.14-blocking#node-kubelet-1.14](https://testgrid.k8s.io/sig-release-1.14-blocking#node-kubelet-1.14) dashboard

**Which test(s) are failing**:
All `BeforeSuite()`s.

**Since when has it been failing**:
2019-02-19 (when it was created)

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.14-blocking#node-kubelet-1.14

**Reason for failure**:
Error hints at an issue with the setup order:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:142
Node 1 disappeared before completing BeforeSuite
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:142
```

/kind failing-test
/sig node
(based on the name of the testgrid view and the test job, please reassign if I got this wrong)
/priority important-soon
/milestone v1.14

cc @kubernetes/sig-node-test-failures 
cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by dashpole** [comment]
From https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-beta/10143/artifacts/tmp-node-e2e-602b6e6f-ubuntu-gke-1604-xenial-v20170420-1-system.log

Feb 27 17:14:44 tmp-node-e2e-602b6e6f-ubuntu-gke-1604-xenial-v20170420-1 kubelet[2764]: F0227 17:14:44.837923    2764 server.go:266] failed to run Kubelet: failed to create kubelet: docker API version is older than 1.26.0

`ubuntu-gke-1604-xenial-v20170420-1` is a really old image.  I wonder where it is being configured...

**Comment by dashpole** [comment]
`--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config-1-14.yaml`

Points to https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config-1-14.yaml#L6

Maybe we should bump that to `ubuntu-gke-1804-d1703-0-v20181113`, which is used in the main and serial configs.

**Comment by dashpole** [comment]
/reopen

whoops, lets wait for a green run

**Comment by dashpole** [comment]
runs are green now!
/close

**Comment by alejandrox1** [comment]
/reopen

BeforeSuite* jobs haven't completely clear out, need more time to run and see

**Comment by dashpole** [comment]
@alejandrox1 can you point me at the failing BeforeSuite?  The one referenced in the issue description has been green for ~20 runs in a row now...

/assign

**Comment by alejandrox1** [comment]
I'm sorry @dashpole, I checked it out in testgrid last night and it didn't show any green runs for me. SO issue on my end.
Thank you for following up on this!
/close
