### ISSUE TITLE
kubelet fails to start: plugin watcher fail to traverse pvc under plugin dir

### ISSUE THREAD

**Issue by clkao** [kubernetes/kubernetes#74669]
**What happened**:

When kubelet restarts while a full rook-ceph pvc is mounted by running pods, it fails with:

```
failed to start Plugin Watcher. err: failed to traverse deprecated plugin socket path "/var/lib/kubelet/plugins", err: failed to watch /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-XXX/dirYY/dirZZ/, err: no space left on device
```
**What you expected to happen**:

kubelet restarts successfully and reconstructs pod and pvc mount states

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Followup to 
https://github.com/kubernetes/kubernetes/pull/70494#issuecomment-455701906, https://github.com/kubernetes/kubernetes/issues/69015 is related, addressing the watcher events.  The initial `traversePluginDir` from `pluginWatcher.Start()` is causing this issue.

Note that the plugin path is deprecated for probing CSI plugin registration: https://github.com/kubernetes/kubernetes/issues/71335

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`): 4.15.0-32
- Install tools: rke

**Comment by clkao** [comment]
Looking at https://github.com/kubernetes/kubernetes/blob/7b24399fb5f3fd7b3894f33c3f4948694f642f70/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L193

it seems fsWatcher.Add is called for every directory found recursively by `fs.Walk`, which is why https://github.com/rook/rook/issues/2568 suggested increasing `fs.inotify.max_user_watches`, given the whole pvc is mounted under plugin dir in this case.

@saad-ali, do we expected outdated CSI registration sockets to exist deeper than `/var/lib/kubelet/plugins/pluginname/some-csi.sock`? if not, we can perhaps just avoid fsWatcher.Add given some depth.

I am only vaguely aware of the old csi-ceph, which is of the following structure:
```
/var/lib/kubelet/plugins/csi-cephfsplugin/
/var/lib/kubelet/plugins/csi-cephfsplugin/csi.sock
/var/lib/kubelet/plugins/csi-cephfsplugin/controller
/var/lib/kubelet/plugins/csi-cephfsplugin/controller/volumes
/var/lib/kubelet/plugins/csi-cephfsplugin/controller/volumes/vol-XXX
/var/lib/kubelet/plugins/csi-cephfsplugin/controller/volume-cache
/var/lib/kubelet/plugins/csi-cephfsplugin/node
```

**Comment by liggitt** [comment]
was https://github.com/kubernetes/kubernetes/pull/72221/files supposed to address this on 1.12?

**Comment by clkao** [comment]
@liggitt I think #72221 is only skipping the blacklisted dir, which is (kubernetes.io/). it does not address the issue where non-CSI flexvolume plugin mounts backing filesystems under the plugin dir, causing excessive traversal + watch calls.

**Comment by clkao** [comment]
this might also be related to #70324, if there are ~8k directories in the plugin dir, kubelet will watch them and can run out of inotify watcher when adding things under /sys/fs/cgroup

**Comment by clkao** [comment]
Not that since the code path is wrapped with the KubeletPluginsWatcher feature gate, disabling it should theoretically fix this issue, if you don't need csi probing. However the documentation is unclear if the feature gate is required for csi and device plugins to register, or is used for watching newly installed plugins while kubelet is running.
