### ISSUE TITLE
[Flaky test] Reboot tests are flaky in master-blocking

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74661]
**Which jobs are failing**:
`ci-kubernetes-e2e-gci-gce-reboot` in [sig-release-master-blocking#gce-cos-master-reboot](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot)

**Which test(s) are flaking**:
* `[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on`
* `[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by triggering kernel panic and ensure they function upon restart`
* `[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart`
* `[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards`
* `[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards`
* `[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering clean reboot and ensure they function upon restart`

**Since when has it been flaking**:
For about 20% of the time over the last 2 weeks.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot

**Reason for failure**:
Various versions of timeouts, for example (taken from separate runs), either:
```
Feb 27 11:16:21.126: Test failed; at least one node failed to reboot in the time given.
```
 or
```
I0227 11:16:21.187] Feb 27 11:16:21.175: INFO: event for fluentd-gcp-scaler-85cdd7d7c5-z29nw: {kubelet err-e2e-minion-group-g6dp} FailedMount: MountVolume.SetUp failed for volume "fluentd-gcp-scaler-token-hqrcg" : couldn't propagate object cache: timed out waiting for the condition
```

/sig cluster-lifecycle
/kind flake
/priority important-soon

cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by alejandrox1** [comment]
This doesn't seem to be an issue anymore :)
/close
