### ISSUE TITLE
Request for clarification: how are services scheduled onto nodes?

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kubernetes#74670]
I apologize in advance if this is already documented (but I looked and couldn't find anything).

I'm dealing with a case where a LoadBalancer service gets scheduled onto a host that is about to be terminated. Ideally I'd be able to use a node selector to limit this to hosts that I know will not be terminated (before the service itself will be deleted).

**Comment by mkornacker** [comment]
@kubernetes/sig-scheduling-misc

**Comment by Huang-Wei** [comment]
`Service` only describes a mapping with target pods, using `spec.selector`. So pods are scheduled instead of service. And when you delete a service, the pods are not impacted at all.

I guess you're trying to ask how an application (e.g. Deployment, StatefulSet) is scheduled?

**Comment by mkornacker** [comment]
I have a StatefulSet (containing one pod) that is scheduled onto specific
nodes using a node selector and taints/tolerations. The contained pod is
the target for the service, and I'm seeing these warnings when running
'kubectl describe svc ...'. The EC2 instances mentioned in these warnings
should not be running the target pod (taints/tolerations should prevent
that), so I'm wondering how those EC2 instances crept in.

  Warning  CreatingLoadBalancerFailed  40m   service-controller  Error
creating load balancer (will retry): failed to ensure load balancer for
service .../...: InvalidInstance: EC2 instance i-017bcxxx is not in running
state.
           status code: 400, request id: 89143a07-...
  Warning  CreatingLoadBalancerFailed  38m  service-controller  Error
creating load balancer (will retry): failed to ensure load balancer for
service .../...: InvalidInstance: EC2 instance i-008exxx is not in running
state.
           status code: 400, request id: cfdad194-...

**Comment by Huang-Wei** [comment]
Oh this error is more related with sig-aws, I will let them comment.

BTW: from the description, it looks like EC2 loadbalancer needs your target instances to be running. If instances are not running, it's pointless to set forwarding/NAT rules to a black hole.

/remove sig-scheduling
/sig aws

**Comment by mkornacker** [comment]
I understand that the target instance needs to be running, but the
terminated instance shouldn't have been a scheduling target for the
pod to which the service is attached (due to taints/tolerations).

Is there some way to track why this particular instance was chosen?

**Comment by Huang-Wei** [comment]
Nope. The (aws) cloudprovider manages how a LoadBalancer is created and implemented.

**Comment by mkornacker** [comment]
I was assuming that the error message
" Warning  CreatingLoadBalancerFailed  40m   service-controller  Error
creating load balancer (will retry): failed to ensure load balancer for
service .../...: InvalidInstance: EC2 instance i-017bcxxx is not in running
state"
came from a Kubernetes scheduling component.

Are you saying that the placement of this load balancer on a particular EC2
instance was determined by AWS, not Kubernetes?

**Comment by Huang-Wei** [comment]
> Are you saying that the placement of this load balancer on a particular EC2 instance was determined by AWS, not Kubernetes?

Yes.
