### ISSUE TITLE
Replace Get-GcePdName module in windows with native support using Get-Disk to return user-friendly GCE PD name

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#74674]
**What would you like to be added**:
In current gce pd attacher code, we use a workaround with Get-GcePdName module to retrieve Pd name and its disk number. After native support of using Get-Disk is available, we should replace it.
**Why is this needed**:

**Comment by yujuhong** [comment]
/assign @pjh 
Peter, assigning this to you since this is blocked by the fix in GCE.

**Comment by andyzhangx** [comment]
what's `Get-Disk` command? any details?

**Comment by PatrickLang** [comment]
@jingxu97 @pjh can you clarify what you mean by "After native support of using Get-Disk is available, we should replace it." ? Is there specific SCSI Inquiry page 83 data that's missing?

**Comment by yujuhong** [comment]
@PatrickLang this is not meant for 1.14, and does not require an OS change. This issue is tracking a GCE bug.

Right now, if you attach multiple disks to a node, the output of `Get-Disk` does not have any information that could let user identify which disk corresponds to which PD. We are waiting for the GCE to fix this properly so that we don't have to jump through hoops to identify the disks.

**Comment by PatrickLang** [comment]
I'm assuming this means setting a WWN or serial number that's also reflected in a GCE API?

Note: WWN is in UniqueId. It's not always there on ATA devices so Windows will make one up. iSCSI, SAS or FC will almost always have that unique identifier.

```
get-disk | fl


UniqueId           : 500A07150372F0DE
Number             : 0
Path               : \\?\scsi#disk&ven_&prod_m4-ct128m4ssd3#4&e937c7&0&050000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}
Manufacturer       :
Model              : M4-CT128M4SSD3
SerialNumber       : 0000000013140372F0DE
Size               : 119.24 GB
AllocatedSize      : 128035676160
LogicalSectorSize  : 512
PhysicalSectorSize : 512
NumberOfPartitions : 4
PartitionStyle     : GPT
IsReadOnly         : False
IsSystem           : True
IsBoot             : True
```

**Comment by PatrickLang** [comment]
/milestone clear
Definitely not in 1.15 since it's past code freeze

**Comment by benmoss** [comment]
@pjh any hope of this for 1.16? It's unfortunate for kubelet to be relying on a non-standard Powershell module

**Comment by pjh** [comment]
@benmoss yeah, I agree it's unfortunate to use the non-standard Powershell module. Removing that workaround requires a GCE platform change that we're working on but we won't be prepared to remove this dependency in the K8s 1.16 timeframe.

In the meantime, is there a place where it would be helpful to document this dependency? I expect you found this by trying to use a GCE PD with a Windows pod and getting an error...

**Comment by benmoss** [comment]
I don't think so, I know I didn't look at any docs before trying to get it to work.

**Comment by ddebroy** [comment]
Long term, this should be taken care of by: [1] the CSI migration effort which paves the path for removal of in-tree plugin code and directing references to in-tree plugins to their CSI counterparts and  [2] enablement of CSI plugins in Windows using a "CSI-proxy" which will incorporate support for querying SCSI Page 83 IDs.
