### ISSUE TITLE
kube-proxy: have a URL that exposes iptables/ipvs/etc config

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#74677]
**What would you like to be added**:

Debugging services often devolves into SSHing to nodes and running iptables or ipset or ipvs commands.  We should have a URL that shows the last written state of these things and maybe a rate-limited way of dynamically reading them.

**Why is this needed**:

Debugging is hard.

**Comment by rikatz** [comment]
Suggestion: Can't we make this a metric of kube-proxy inside prometheus? 

Something like 

``ipvs-entry{serviceip="W.X.Y.Z", endpoints="ip1,ip2,ip3"} COUNT-OF-ENTRIES`` 

for each entry? 

On the other hand, this might be a problem in Services containing a lot of endpoints, generating a really big set of metrics, and don't know if this is the best way to do this

**Comment by uablrek** [comment]
Both iptables and ipvs proxiers generates input to "iptables-restore". It might be sufficient to store these for later retrieval?

The latest succesful and the latest failed (if any).

**Comment by rikatz** [comment]
Lars is doing some old issue digging o/

I think the biggest issue with that is the size of the file. Tim's idea of putting some rate limiting is nice, also I think some authentication would be great as firewall rules tend to be 'confidential'.

The thing is: what happens when you've Calico and IPVS, Calico generating 50k rules and IPVS with 4k of services? ipvsadm-save returns a 1Mb file (that's ok) and iptables-save returns a 7mb file. If this is 'ok', I'm on with the idea of generating this debug endpoint :)

**Comment by uablrek** [comment]
If you want the entire iptables-save I would agree, but I meant the input to iptables-restore that kube-proxy generates in it's sync.

You can see it in the logs as a loong string with lots of "\"\n\"" which makes it hard to read and a ref to an error on "line 63".

That data only contains kube-proxy things. But it can of course be big anyway, but would be requested "on demand" from kube-proxy so normally no bandwith problem.

**Comment by rikatz** [comment]
My point here is, for debugging reasons it would be great to have what kube-proxy generated and what really is installed / configured in the host.

So you can take the smaller and the big picture (and also see what kube-proxy proposed to be applied has really been applied in the host) but hey, great :D let's dig into that.

@thockin as this was your idea originally, what's the approach you've been thinking?

Thanks :)

**Comment by uablrek** [comment]
@danwinship Maybe this proposal should be revisited for proxy-mode=nftables? It is much simpler, but _really_ large configs may still be a problem.

**Comment by uablrek** [comment]
(or close it)

**Comment by aojea** [comment]
I can see how this can have a lot of security concerns , @thockin is this really something you want to keep open?

I don't feel this is much of an issue these days, doing a `kubectl get --raw /` vs `kubectl exec -it ..` is not  much diffferent
