### ISSUE TITLE
Roll ingress controller / API from Beta to version 1

### ISSUE THREAD

**Issue by tburow** [kubernetes/kubernetes#74679]
**What would you like to be added**:
I would like the Ingress controller API version moved out of beta.  This is a community issue that impacts other supporting opensource projects.  

**Why is this needed**:
Opensource community projects such as terraform Kubernetes provider will not add features that support a beta interface.   ref issue: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/14

This is an old ongoing problem that seems to be a simple fix to roll the interface version out of beta.

@kubernetes/sig-contributor-experience-feature-requests

**Comment by LondonAppDev** [comment]
Love kubernetes and thanks for all the work you do. 

Commenting because this issue has been a major limitation for me for deploying to GCP using Terraform.

**Comment by rmacian** [comment]
Same here, I would like to use Terraform to deploy my apps

**Comment by tburow** [comment]
bump

**Comment by tburow** [comment]
@kubernetes/sig-contributor-experience-feature-requests

**Comment by idealhack** [comment]
@kubernetes/sig-network-feature-requests 

/sig network
/remove-sig contributor-experience

**Comment by vllry** [comment]
This will be happening in the not-distant future, but I'm not personally aware of a timeline. We don't want to rush the change in status, as there are still legitimately many uncertainties about the future of Ingress, and making it prematurely GA would vastly complicate future work.

**Comment by vllry** [comment]
I couldn't quickly find more info tracking this, would appreciate some added

/help-wanted

**Comment by tburow** [comment]
I think much of the concern is around this is part of the functional base for k8s and has been for sometime, and relied upon by many.  I guess im not in the loop on future changes for ingress.  From my understanding its been in this state for years now however because its still listed as beta its causing downstream integration issues.  Seems like regardless of the future state, rolling the current version to GA would be a welcome change.

**Comment by idealhack** [comment]
I see sig-network has aware of this issue, so that's good.

Meanwhile, I'm afraid this does not meet the [requirements](https://git.k8s.io/community/contributors/guide/help-wanted.md) of `help wanted` from contributors.

/remove-help

**Comment by tburow** [comment]
@bowei  Might you have an update on this or possible ETA?
Thanks

**Comment by bowei** [comment]
This will be a KEP in 1.15.

**Comment by bowei** [comment]
Either continuing on this KEP or a follow on: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md

**Comment by rikatz** [comment]
@bowei we can close this, as Ingress v1 is already available right?

I'll close, can re-open if necessary

/close
