### ISSUE TITLE
kube-dns as a standalone DNS product

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#7469]
SkyDNS supports arbitrary backends.  If we implement that interface in terms of kubernetes, we don't need etcd or skydns binaries running.

**Comment by smarterclayton** [comment]
Summary of current design discussion:

* DNS can be backed by code https://github.com/openshift/origin/blob/d3282b30203b559d804dcb29fe1209a8b13cf449/pkg/dns/serviceresolver.go#L63
* DNS is important to the operation of a container, so if the DNS server is down some containers can't start
* When running a docker registry on the cluster, the nodes would need to resolve the DNS entry for the registry service for SSL to properly function
* Having a local cache on each node for DNS is desirable
* The service proxy is already caching all of the information (or most) needed to offer DNS
* Therefore, the service proxy should serve DNS locally based on its map of services to endpoints

Potential design points not addressed:

* Today, every kube-proxy sees all services and endpoints
  * In some clusters, this may cause issues - if we decide to prevent some nodes from seeing all services, DNS resolution would have to be done at multiple levels

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (31/30 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:58101 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZEhaZ-0020Xr-0r
	for robin@eikaas.no; Mon, 13 Jul 2015 19:32:25 +0200
Date: Mon, 13 Jul 2015 10:32:21 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1436808741;
	bh=uIxIj5pHXe14jQsHJgE30Xqqlm2afos8Nau9ANGxiwY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=am3Lib/6hBJdkJX0G9h8C207aIZ0KwvJAyOzAA7FvUiwvw92OJTJMH0LF0wpA1pLe
	 ixo3X2gFnB7NWSMVAuGExqQLRdnsC+dYziOEMMtibLl0z3KuJ8zUC/QZjKpwmgLr7a
	 t3Gm6qp6hK5ljJo3eDkyCzLe8ZohyDZ0hhYe3tZo=

**Comment by thockin** [comment]
Done!

**Comment by bboreham** [comment]
Was there a PR or commit that closed this?

**Comment by thockin** [comment]
yes - kube-dns was rewritten for 1.3 as a standalone bin using skydns as a
lib.  We're still open to other implementations of course, we just ran with
the devil we knew. :)
