### ISSUE TITLE
Enable hostname override setting in v1.PodSpec to work with StatefulSets

### ISSUE THREAD

**Issue by anikammsft** [kubernetes/kubernetes#74696]
This is being filed as a follow up to [bug report 74564](https://github.com/kubernetes/kubernetes/issues/74564). 

Kubernetes v1.PodSpec currently allows users to specify a hostname setting. This setting takes effect on ReplicaSets and Deployments, however, it does not work on StatefulSets. 

Users can have special needs on hostnames that cannot be accommodated in the names of StatefulSets. 
One example is when running Active Directory domain joined services in Kubernetes pods. AD requires that the hostnames be only up to 15 characters long which creates a stringent requirement since Kubernetes also appends long identifiers when generating the pod names from the parent StatefulSet/Deployment/ReplicaSet.

Additionally, when the hostname setting takes effect on ReplicaSets and Deployments, it gets applied to all the pods thereby limiting the addressability to individual pods using the hostname. The request with this is to provide an ability to distinguish the pods.

**What would you like to be added**:
1. Ability to set hostnames on StatefulSet pods
2. Ability to distinguish hostnames across multiple pods from the same StatefulSet/Deployment/ReplicaSet/DaemonSet.

**Why is this needed**:
Needed when users have special requirements on hostnames that certain technologies such as Active Directory can enforce.

@kubernetes/sig-apps-feature-requests

**Comment by Joseph-Irving** [comment]
@kubernetes/sig-apps-feature-requests
