### ISSUE TITLE
Current trace logs are not readable

### ISSUE THREAD

**Issue by snowplayfire** [kubernetes/kubernetes#74707]
**What would you like to be added**:
I found an unfriendly problem of current trace package. The phenomenon is stepDuration and stepMsg are not consistent. Maybe it is by-design or it is a bug.

The path of the trace package is "/vendor/k8s.io/apiserver/pkg/util/trace".

I will take `kube-scheduler` for example to describe the problem. When the scheduler is scheduling a pod, we can find its corresponding trace message in kube-scheduler log as follows.
```
Trace[63718591]: [963.946µs] [963.946µs] Computing predicates
Trace[63718591]: [31.535934ms] [30.571988ms] Prioritizing
Trace[63718591]: [145.960023ms] [114.424089ms] Selecting host
Trace[63718591]: [145.993901ms] [33.878µs] END
```
Corresponding code in trace.go
```
buffer.WriteString(fmt.Sprintf("Trace[%d]: [%v] [%v] %v\n", tracenum, step.stepTime.Sub(t.startTime), stepDuration, step.msg))

```
According to the code and common sense, we can explain the trace. Take line 2 as example:
```
Trace[63718591]: [31.535934ms] [30.571988ms] Prioritizing
```
"63718591" is tracenum;

"31.535934ms" is the duration from the begining to completed current step "Prioritizing";

"30.571988ms" is the duration of current step "Prioritizing";

"Prioritizing" is current step's name.

That is,  one step "Prioritizing" costs 30.571988ms, and the step "Prioritizing" including all front steps cost 31.535934ms, all front steps cost (31.535934-30.571988) ms.

In fact, the above explanation is wrong. The duration doesn't belongs to the current step, but the last step.

The right explanation:

"30.571988ms" is the duration of step "Computing predicates";

"31.535934ms" is the duration from the begining to completed step "Computing predicates".

We can see the trace log is not readable. A Readable trace should be like:
```
Trace[63718591]: [963.946µs] [963.946µs] Initializating
Trace[63718591]: [31.535934ms] [30.571988ms] Computing predicates
Trace[63718591]: [145.960023ms] [114.424089ms] Prioritizing
Trace[63718591]: [145.993901ms] [33.878µs] Selecting host
```
I don't know it is by-design or it is a bug.  If it is by-design, who can tell me the purpose？If it is not by-design, I can propose a PR to make it more readable.

**Why is this needed**:

Log should be readable, but the stepDuration and stepMsg are not consistent in trace log, which cause the difficulty of reading it and using it in monitoring system.

**Comment by wenjiaswe** [comment]
@snowplayfire I am not familiar with the scheduling source code, like the example you gave, would you mind explaining how do you know which duration is from which step to start? 
cc scheduling expert @bsalamat  as well.

**Comment by snowplayfire** [comment]
The focus of the problem is a package named "trace" in source code. The function of the package is to record every step's duration which can be used to analyze situation. The package "trace" is used in some places of the source code more than scheduler. 
The path of the package is "/vendor/k8s.io/apiserver/pkg/util/trace".  Maybe you can read the source code of the package, you can catch the problem easily.

I take scheduler for example to explain the problem, just because scheduler uses the trace package and I found the problem when I used the trace log to monitor scheduler.  I  was misled by the trace. In fact, the problem is nothing to do with scheduling.
```
func (g *genericScheduler) Schedule(pod *v1.Pod, nodeLister algorithm.NodeLister) (string, error) {
	trace := utiltrace.New(fmt.Sprintf("Scheduling %s/%s", pod.Namespace, pod.Name))
	defer trace.LogIfLong(100 * time.Millisecond)

	if err := podPassesBasicChecks(pod, g.pvcLister); err != nil {
		return "", err
	}

	nodes, err := nodeLister.List()
	if err != nil {
		return "", err
	}
	if len(nodes) == 0 {
		return "", ErrNoNodesAvailable
	}

	err = g.snapshot()
	if err != nil {
		return "", err
	}

	trace.Step("Computing predicates")
	startPredicateEvalTime := time.Now()
	filteredNodes, failedPredicateMap, err := g.findNodesThatFit(pod, nodes)
	if err != nil {
		return "", err
	}
        ...
```
1. utiltrace.New(): new a trace
2. trace.Step("stepMsg"): record every step's name and last step's end time. 
3. trace.LogIfLong(): calculate duration and write trace message into log

If you read the code of "trace.Step" and "trace.LogIfLong", you can find how I know which duration is from which step to start.  

Do you think I explained it clearly?

**Comment by wenjiaswe** [comment]
Thanks for the explanation. 

I read the trace code in /vendor/k8s.io/utils/trace/trace.go for [New()](https://github.com/kubernetes/kubernetes/blob/8d69dc630ba66d05ad95146583a7482ed1eb3f82/vendor/k8s.io/utils/trace/trace.go#L42), [trace.Step("stepMsg")](https://github.com/kubernetes/kubernetes/blob/8d69dc630ba66d05ad95146583a7482ed1eb3f82/vendor/k8s.io/utils/trace/trace.go#L47), [trace.LogIfLong()](https://github.com/kubernetes/kubernetes/blob/8d69dc630ba66d05ad95146583a7482ed1eb3f82/vendor/k8s.io/utils/trace/trace.go#L85). I think the current behavior is correct according to the source code. "New" news a trace, "Step" prints out the step name and time, for this particular example you gave, they are "[Computing predicates](https://github.com/kubernetes/kubernetes/blob/a352b74bcca9de2acd1600e47ea7f122ac8c1fe1/pkg/scheduler/core/generic_scheduler.go#L182)", "[Prioritizing](https://github.com/kubernetes/kubernetes/blob/a352b74bcca9de2acd1600e47ea7f122ac8c1fe1/pkg/scheduler/core/generic_scheduler.go#L201)", "[Selecting host](https://github.com/kubernetes/kubernetes/blob/a352b74bcca9de2acd1600e47ea7f122ac8c1fe1/pkg/scheduler/core/generic_scheduler.go#L224)", then at the end of "LogIfLong", it prints ["END"](https://github.com/kubernetes/kubernetes/blob/8d69dc630ba66d05ad95146583a7482ed1eb3f82/vendor/k8s.io/utils/trace/trace.go#L78). The time given in trace.Step is the time when trace.Step is called, which in this case is when each step starts, so if you want to get the duration of Computing predicates, you use the time given in the next step (31.535934ms) minus the time given when computing predicates starts (963.946µs).

Please notice the time in traceStep is just the current time: https://github.com/kubernetes/kubernetes/blob/8d69dc630ba66d05ad95146583a7482ed1eb3f82/vendor/k8s.io/utils/trace/trace.go#L52. It's really how trace is used in each component that matters. 

It looks like what you want is to print out one more line when a new trace is created at New()? I don't think that would give more information than the duration of initializing a trace. 

Please let me know if I understood wrong. Thanks!

**Comment by snowplayfire** [comment]
What you understood is exact.

But I think what is printed out is misplaced.  If I want to know the duration of a step,  I can get it from the following line, rather than the current line. That is,  step name and duration are not relevant in every line.

What I want is not to print out one more line, I want to adjust the misplaced logs printed out to make step name and duration in every line relevant. 

Replace
```
Trace[63718591]: [963.946µs] [963.946µs] Computing predicates
```
with
```
Trace[63718591]: [31.535934ms] [30.571988ms] Computing predicates
```
The way to print out is in trace.LogIfLong(). We can do something in trace.LogIfLong() to adjust the misplaced logs printed out.

After I adjust the way to print out, the first line should have a step name. I take "Initializating" here just like the original "END".

**Comment by snowplayfire** [comment]
@wenjiaswe Some other people also find the problem and fix it.  I will close the issue.

https://github.com/kubernetes/kubernetes/pull/78280

https://github.com/kubernetes/kubernetes/pull/78275
