### ISSUE TITLE
get priorityclasses.scheduling.k8s.io system-node-critical

### ISSUE THREAD

**Issue by anan-lee** [kubernetes/kubernetes#74729]
**What happened**:
Kube-apiserver kept rebooting when I set up a new cluster.

**What you expected to happen**:
the Fatal log:
Feb 28 22:49:48  kube-apiserver: F0228 22:49:48.523563    9384 hooks.go:188] PostStartHook "scheduling/bootstrap-system-priority-classes" failed: unable to add default system priority classes: the server was unable to return a response in the time allotted, but may still be processing the request (get priorityclasses.scheduling.k8s.io system-node-critical)

**How to reproduce it (as minimally and precisely as possible)**:

more log:

Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.539904    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.540060    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.540323    9384 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Namespace: the server was unable to return a response in the time allotted, but may still be processing the request (get namespaces)
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.540821    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Feb 28 22:49:47  kube-apiserver: I0228 22:49:47.541196    9384 trace.go:76] Trace[130408725]: "List /api/v1/namespaces" (started: 2019-02-28 22:48:47.538451932 +0800 CST m=+29.798105233) (total time: 1m0.002685474s):
Feb 28 22:49:47  kube-apiserver: Trace[130408725]: [1m0.002685474s] [1m0.002592975s] END
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.541333    9384 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1beta1.ValidatingWebhookConfiguration: the server was unable to return a response in the time allotted, but may still be processing the request (get validatingwebhookconfigurations.admissionregistration.k8s.io)
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.542263    9384 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.543404    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.546173    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.546374    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.546681    9384 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.546811    9384 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Pod: the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.546846    9384 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:117: Failed to list *apiextensions.CustomResourceDefinition: the server was unable to return a response in the time allotted, but may still be processing the request (get customresourcedefinitions.apiextensions.k8s.io)
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.548887    9384 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.549801    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.549895    9384 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.550223    9384 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.550542    9384 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *core.LimitRange: the server was unable to return a response in the time allotted, but may still be processing the request (get limitranges)
Feb 28 22:49:47  kube-apiserver: I0228 22:49:47.551228    9384 trace.go:76] Trace[999017112]: "List /api/v1/serviceaccounts" (started: 2019-02-28 22:48:47.539624267 +0800 CST m=+29.799277595) (total time: 1m0.011563767s):
Feb 28 22:49:47  kube-apiserver: Trace[999017112]: [1m0.011563767s] [1m0.011477601s] END
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.552363    9384 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout
Feb 28 22:49:47  kube-apiserver: E0228 22:49:47.555084    9384 writers.go:149] apiserver was unable to write a JSON response: http: Handler timeout

arg:
KUBE_API_ARGS=" --request-timeout 1m --authorization-mode=Node,RBAC  --runtime-config=rbac.authorization.k8s.io/v1beta1  --kubelet-https=true  --token-auth-file=/etc/kubernetes/token.csv  --service-node-port-range=30000-32767  --tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem  --tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem  --client-ca-file=/etc/kubernetes/ssl/ca.pem  --service-account-key-file=/etc/kubernetes/ssl/ca.pem  --storage-backend=etcd3  --etcd-cafile=/etc/etcd/ssl/ca.pem  --etcd-certfile=/etc/etcd/ssl/etcd.pem  --etcd-keyfile=/etc/etcd/ssl/etcd-key.pem  --enable-swagger-ui=true  --audit-log-maxage=30  --audit-log-maxbackup=3  --audit-log-maxsize=100  --audit-log-path=/var/log/k8s-audit.log  --event-ttl=1h"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
8core 8g
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux  3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by mucahitkurt** [comment]
How is this issue related with sig storage?

**Comment by liggitt** [comment]
startup errors related to everything attempting to contact etcd indicates an error between your kube-apiserver and your etcd server

/close
