### ISSUE TITLE
kube-conformance should support dryRun option

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#74727]
**What would you like to be added**:
The kube-conformance image should support setting the dryRun option just like focus/skip. 

**Why is this needed**:
This is a very commonly requested feature in Sonobuoy since users often are setting up/experimenting with runs and want to check what a certain regexp will hit without actually running it.

Change will be here: 
https://github.com/kubernetes/kubernetes/blob/9c5cf3ccf77225fd38772a5a9162d6dc7f818d20/cluster/images/conformance/run_e2e.sh#L42-L51

/sig testing

**Comment by dims** [comment]
+1 !!
