### ISSUE TITLE
[Flaky test] Advanced Audit tests are flaky in 1.14-blocking

### ISSUE THREAD

**Issue by smourapina** [kubernetes/kubernetes#74745]
**Which jobs are flaking**:
https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default

**Which test(s) are flaking**:
- `[sig-auth] Advanced Audit [DisabledForLargeClusters] should audit API calls to create, get, update, patch, delete, list, watch secrets.`
- `[sig-auth] Advanced Audit [DisabledForLargeClusters] should audit API calls to create, get, update, patch, delete, list, watch configmaps.`

**Reasons for flaking**:
Seem to be mostly timeouts, for example: [9538](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/9538), [9543](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/9543), [9544](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/9544).

**Since when has it been flaking**:
Since 2/20.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default

**Anything else we need to know**:
Latest failure logs can be found in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/9544.

cc @mortent @kacole2 @mariantalla @alejandrox1

/kind flaky-test
/priority important-soon
/sig auth

**Comment by liggitt** [comment]
from slack conversation with @pbarker:

> @pbarker 
> In hunting around, it seems the most common case is that the events are in one of the rotated logs and can be found by running `CheckAuditLines` https://github.com/kubernetes/kubernetes/blob/master/test/utils/audit.go#L53 manually.
This makes me wonder if they may be getting rotated, and I noticed https://github.com/kubernetes/kubernetes/commit/0713f29c289a339fef06647c10fa65d59a169a8d#diff-ff266e54aabe0e2f74de4f944db65edb merged that same day, I'm still testing to see if that impacts the audit logs.

cc @jpbetz

**Comment by pbarker** [comment]
If we wanted to test that theory we could temporarily change those file rotation settings back to what they were and see if that fixes the problem.

**Comment by jpbetz** [comment]
@liggitt @pbarker The intent of the change was to check if log rotation was needed more often but still keep the rotation policy the same (new day starts, log file size > 100MB). I'm certainly okay with reverting the change to see if it fixes the bug, but if it does, I'm concerned that it still might flake if the test run crosses hour boundries.

**Comment by jpbetz** [comment]
Created https://github.com/kubernetes/kubernetes/pull/74911 to revert then log rotation change.

**Comment by pbarker** [comment]
thank you @jpbetz, we'll see if that fixes it, if so we brainstorm on how to fix it more permanently

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/74915 merged ~18 hours ago

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Advanced%20Audit

I'm not yet seeing a clear difference, and suspect we have more work to do here

**Comment by spiffxp** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=e2e-gce&test=Advanced%20Audit - maybe more relevant since it filters out kops jobs that aren't on release-blocking

The main cluster is our good friend `timed out waiting for condition`
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/audit.go:66
after 5m0s failed to observe audit events
Expected error:
    <*errors.errorString | 0xc0002caa60>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/audit.go:745
```

**Comment by pbarker** [comment]
that one looks a lot better, still curious why its failing at all, I'll dig in a bit more

**Comment by tallclair** [comment]
Once DynamicAudit goes to beta, we should be able to eliminate the reliance on the log files by using a webhook to verify the audit stream instead. Thanks for investigating @pbarker !

**Comment by soggiest** [comment]
We in code freeze for 1.14. If this issue is blocking the 1.14 release can we please get an update on whether this issue will be closed in the next week? If this issue is not blocking 1.14 can we move it to 1.15?

@pbarker

**Comment by alejandrox1** [comment]
Seems like #74915 did resolve this issue.
The failed tests in this issue have cleared out.
/close

**Comment by spiffxp** [comment]
If we focus on gci-gce jobs it looks like it's become _less_ flaky but hasn't gone away entirely

https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=e2e-gci-gce&test=Advanced%20Audit
<img width="1104" alt="Screen Shot 2019-03-16 at 11 38 02 AM" src="https://user-images.githubusercontent.com/49258/54479950-0abe4980-47e0-11e9-8831-50d34e177cb4.png">

Definitely not happy as far as kops is concerned

https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=kops&test=Advanced%20Audit
<img width="1098" alt="Screen Shot 2019-03-16 at 11 40 49 AM" src="https://user-images.githubusercontent.com/49258/54479988-5d980100-47e0-11e9-9acd-89a283978243.png">

**Comment by liggitt** [comment]
the methodology the test is using is inherently flaky in the face of server-side log rotation

spoke with @tallclair about this, and I think we should do the following:
* now: mark the existing e2e tests as `[flaky]` while we resolve issues
* short-term: take detailed specific-request-to-specific-audit-event tests and make sure we have integration tests covering that 
* medium-term: change e2e tests to general "audit for resource X is enabled" and make them much more robust by moving away from trying observe an audit event for a *particular* request, and unmark them flaky
* long-term: change e2e tests to use dynamic audit and point at a test-specific audit sink

**Comment by liggitt** [comment]
marking flaky in https://github.com/kubernetes/kubernetes/pull/75447

**Comment by tallclair** [comment]
Thanks @liggitt 

Follow up tasks captured by https://github.com/kubernetes/kubernetes/issues/75563
