### ISSUE TITLE
wait for containers cleanup before delete pod too slow

### ISSUE THREAD

**Issue by ddongchen** [kubernetes/kubernetes#74779]
**What would you like to be added**:
   We try to delete all pods, which containing at least two containers, at the same time, we found pods are deleted too slow, then we checked the log and found there are two blocks:

(1)  pod is deleted before all its' containers are deleted, which from https://github.com/kubernetes/kubernetes/pull/50350. I know if the pod is evicted, it should release all resources. while if the pod is deleted normally, is it safe to delete pod when just all containers are exited?  We can have a check when deleting pod, if is evicted, pod should wait for all containers are deleted, if not, just wait for all containers are exited.
    Related codes: 
         pkg/kubelet/kubelet_pods.go:  PodResourcesAreReclaimed()

(2) when container exited, kubelet will put the pod into channel to delete containers. while there is just one worker to remove container one by one from channel. if there are multi containers, or one container waste too much time, others pods will be affected. We can add more workers to handle the channel.
   Related codes: 
             pkg/kubelet/pod_container_deletor.go:
                      newPodContainerDeletor()
                      deleteContainersInPod()

**Why is this needed**:
     pod deleting time is also important for Kubernetes request, we can firstly have a talk to check if it is reasonable for the above two points, if its ok, I can upload patches for this. Thanks~

**Comment by Manouchehri** [comment]
@ddongchen Did you ever manage to improve the speed of pod deletion?

**Comment by ddongchen** [comment]
> @ddongchen Did you ever manage to improve the speed of pod deletion?
 I found no one cares about that, so I didn't do anything
