### ISSUE TITLE
Migrate command line flags from a mix of _ and - to just -

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#7478]
Continuing on from #7281...

I don't think we should keep this as a steady state - we should migrate to just `-`'s and first deprecate then remove flags with `_` by 1.0.

Even if we don't disable `_` flags by 1.0, we should make sure deprecation warnings are issued.

**Comment by ghodss** [comment]
Closed by #8026.

**Comment by ghodss** [comment]
Actually, now that #8026 is implemented, we should decide if we want to actually disable _ separators by 1.0, or wait until a later release (like 2.0).

**Comment by thockin** [comment]
is it so bad to just leave it?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by eparis** [comment]
I say we just close this. We no longer have any `_` in the kube code. We automatically convert `_` to `-` if we get the flag from some other codebase.

We have checkers to make sure we don't add any more `_`. I think we've done everything there is to do here...
