### ISSUE TITLE
Kubelet failing to start on Azure stack

### ISSUE THREAD

**Issue by rjaini** [kubernetes/kubernetes#74785]
What happened:
Currently starting Kubectl failing on Azure Stack.
What you expected to happen:
Kubectl should start on Azure Stack environment.

How to reproduce it (as minimally and precisely as possible):
Try to deploy Kubernets on Azure Stack environment..

Anything else we need to know?:
Environment:
Kubernetes version (use kubectl version): master
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Others:
/sig azure
/assign

**Comment by andyzhangx** [comment]
is it `kubelet`? `kubectl` is a tool ...

**Comment by rjaini** [comment]
my bad its kubelet. I update the title.

**Comment by andyzhangx** [comment]
@rjaini then could you provide the kubelet log? I am not sure kubelet on Azure stack is running as a container or process, you could get the logs by:
https://github.com/andyzhangx/demo/tree/master/debug#q-how-to-get-k8s-kubelet-logs-on-linux-agent
And how do you deploy k8s on azure stack?

**Comment by rjaini** [comment]
[kubelet.log](https://github.com/kubernetes/kubernetes/files/2929054/kubelet.log)
