### ISSUE TITLE
help html 404 not found

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubernetes#74801]
Many code use this [url](https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/v1/definitions.html) in help content like:
```
$ kubectl help patch
Update field(s) of a resource using strategic merge patch, a JSON merge patch, or a JSON patch. 

JSON and YAML formats are accepted. 

Please refer to the models in
https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/v1/definitions.html
to find if a field is mutable.

```

But i click and find that 404, i use:
```
$ kubelet --version
Kubernetes v1.10.12
```

I also look into master branch, still same url. Need to update i think.

**Comment by daixiang0** [comment]
@WanLinghao is there any doc about `kubelet patch` that describe which changes can be done to specify resource?
After test, now i know `kubelet patch` only can change little to `pod` resource.

**Comment by WanLinghao** [comment]
@liggitt  Do you have any idea?

**Comment by liggitt** [comment]
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/ ?

**Comment by daixiang0** [comment]
@liggitt thanks, but i want to know the limit about `kubectl patch`, now only i can do is test then i can get that.

**Comment by liggitt** [comment]
`kubectl explain <type>[.path.to.field]` can display schema info about particular resources or fields

**Comment by liggitt** [comment]
for example, `kubectl explain pod.spec`

**Comment by daixiang0** [comment]
I can see some detail, while still can not find the limit about `kubectl patch` to particular resources or fields.

**Comment by daixiang0** [comment]
@liggitt any input?

**Comment by liggitt** [comment]
information about immutability of fields is not consistently published today

**Comment by daixiang0** [comment]
@liggitt hi, i add a comment as #75316, may be helpful for confused users like me.

**Comment by daixiang0** [comment]
@liggitt any update?
