### ISSUE TITLE
Add VolumeName field selector to PVC 

### ISSUE THREAD

**Issue by mohnishkodnani** [kubernetes/kubernetes#74817]
**What would you like to be added**:
I would like to add a field selector for the .Spec.VolumeName for a PVC.

**Why is this needed**:
I have a usecase where I need to query for all PVC for a particular host. 
PVC has no direct link to the host in the Spec. The way I am doing this right now, is to get a list of Persistent Volume (PV) running on a particular host exposed by the label kubernetes.io/hostname. 
Once, i have this list. I query and get all PVC for a particular namespace, which is huge in our case. 
Then I filter out individually based on whether that PVC has the volumeName set to the PV I am interested in. 
This will allow me to make my query more efficient and get results directly rather than filtering out at the client side.

**Comment by mohnishkodnani** [comment]
@kubernetes/sig-cli-feature-requests
@kubernetes/sig-storage-feature-requests

**Comment by krmayankk** [comment]
@mohnishkodnani the bigger questions is why do you need this feature. Why do you want to list PVC on a given host. Do you think this feature will be generally usefull to a wide variety of users. In Container orchestration world, generally per host thinking should be avoided.

**Comment by mohnishkodnani** [comment]
Our use case is very latency sensitive, and so we are planning to use
local-ssd disks on the hosts.
Now, we have our application as StatefulSet. In the stateful set we create
Volume Claim Templates with local disk. Now, every pod that belongs to the
STS creates a PVC on the host using local disk.
To get data to these nodes that they are going to serve, we have a
daemonset ( the reason we have this and not as a side car, is because the
teams maintaining this application to get data is different and we dont
want to club the lifecycles of development and also if we have it as a side
car and update the sidecar, which might require a restart of the pod, that
restart is very expensive, becuase it takes a long time for the applicaiton
to come up with the GB's of data it needs to load. )
So, our approach is to have this data downloading application run as
daemonset. Now, we created a mutating webhook, which is called for every
pod of the daemonset.
Since, its daemonset it knows the Node Name ( disabled the daemonset
scheduler feature ). It then queries all the PV's that belong to the node
and then wants to get the PVC's that belong to those PV's. This is where
there is a problem.We have to get all PVC's ( could be 1000's) and then
filter them on application side by looking at the volume Name. If we could
have a field selector for PVC's we could do this at the server side.

**Comment by mohnishkodnani** [comment]
To add to the above, once we find the PVC, we use a mutating webhook to add the volume to the daemonset pod. This way the StatefulSet and the daemonset pod running on the same node can share the disk. 
@krmayankk ☝️

**Comment by mohnishkodnani** [comment]
cc @krmayankk One more, because we are using the combination of STS and local disk as PVC, when a node goes down, we have to do cleanup ourselves so that the pod can be re-scheduled on another host, otherwise the STS will always try to schedule to the node with the PVC name in the volume claim template. To do the clean up as well, it seems i write a node controller, and detect node down condition, now i have to find the PVC on that node and delete those. This will also help in that use case. 
Please let me know how we can discuss this further.

**Comment by msau42** [comment]
PV has a claimref field that tells you the PVC it is bound to

**Comment by mohnishkodnani** [comment]
We have to find the PVC, so in this case we dont know the PVC, hence we
dont know what claimref we have to check.
Scenario is this:
You have a hostname and you have to find all PVC's for that host.
The reasoning to do this is highlighted in the comments above.
So, in our workflows we have to go from HostName -> PV -> PVC List and
filter by volume Name.
Instead if fieldSelector volumeName was searchable then, we could avoid
getting the list of all PVC's and filter on client side.

**Comment by msau42** [comment]
I mean once you list all the PVs on that host, then for each of those PVs, you can check PV.Spec.ClaimRef to get the PVC

**Comment by gregswift** [comment]
I do agree that you can totally get to what you need using existing commands, however I have to agree with OP that this is a useful and reasonable feature.

our usecase:

We use local disks as well.  Our alerting system reports on disks in high usage.  The filesystem for such a disk tends to be: 

  /var/data/kubelet/pods/${UUID}/volumes/kubernetes.io~local-volume/${PV_NAME}

So the steps for us to identify the associated pod for this PV are:

  kubectl describe pvc $(kubectl get pvc | awk '/6bf14f63-8af4-4aa6-8038-2b95ab40460f-10.4.2.211/ {print $1}')

But we have over 400 PVCs, so we are having to get basic information about all of them with that before rather than just doing something like:

  kubectl describe pvc --field-selector="spec.volumeName=6bf14f63-8af4-4aa6-8038-2b95ab40460f-10.4.2.211"

**Comment by msau42** [comment]
Sorry for the delay, this totally fell off my radar.  

Given a PV, you can look `PV.Spec.ClaimRef` to get the exact PVC it is bound to.  There's no need to list PVCs and filter by volumeName.

**Comment by gregswift** [comment]
thanks.. i have forgotten about this too and think we may have come to a similar conclusion :man_shrugging:
