### ISSUE TITLE
CSI node ID annotation not removed from node when CSI driver is uninstalled

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#74812]
I am not sure if this is just my environment but looks like nodeID annotation is not being removed correctly when a driver is uninstalled.

```
annotations": {                                     
            "csi.volume.kubernetes.io/nodeid": "{\"csi-mock-csi-mock-volumes-2615\":\"csi-mock-csi-mock-volumes-2615\",\"csi-mock-csi-mock-volumes-3625\":\"csi-mock-csi-mock-volumes-3625\",\"csi-mock-csi-mock-volumes-4712\":\"csi-mock-csi-mock-volumes-4712\",\"csi-mock-csi-mock-volum
es-5083\":\"csi-mock-csi-mock-volumes-5083\",\"csi-mock-csi-mock-volumes-5754\":\"csi-mock-csi-mock-volumes-5754\",\"csi-mock-csi-mock-volumes-7389\":\"csi-mock-csi-mock-volumes-7389\",\"csi-mock-csi-mock-volumes-8506\":\"csi-mock-csi-mock-volumes-8506\",\"csi-mock-csi-mock-volumes-9
106\":\"csi-mock-csi-mock-volumes-9106\",\"csi-mock-csi-mock-volumes-9467\":\"csi-mock-csi-mock-volumes-9467\",\"csi-mock-csi-mock-volumes-9884\":\"csi-mock-csi-mock-volumes-9884\"}",
```

^ is result of me running e2e's bunch of times. Surely, eventually they should be removed right?

cc @verult  @msau42 

/sig storage

**Comment by verult** [comment]
Is the socket removed on driver uninstall?

**Comment by mucahitkurt** [comment]
When I check [the code](https://github.com/kubernetes/kubernetes/blob/39073f0b9f642ed658cbe7a81f980394089f0a6f/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L152) it seems to me when uninstalling CSI driver is completed, removing nodeID from node annotations should also be completed. There are [related test codes](https://github.com/kubernetes/kubernetes/blob/39073f0b9f642ed658cbe7a81f980394089f0a6f/pkg/volume/csi/nodeinfomanager/nodeinfomanager_test.go#L562) for this scenario.

**Comment by trickkiste** [comment]
same problem with 
https://github.com/robin-rpr/csi-sshfs
https://github.com/chr-fritz/csi-sshfs
