### ISSUE TITLE
StatefulSetSpec.volumeClaimTemplates doesn't have a merge key

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#74819]
cc @kow3ns 
cc @janetkuo 
cc @kubernetes/sig-apps-bugs 

StatefulSetSpec.volumeClaimTemplates does not have a merge strategy or key, so it is always replaced.  See PodSpec.volumes for what this should look like

- [podspec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#podspec-v1-core)
- [statefulsetspec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#statefulsetspec-v1-apps)

**Comment by krmayankk** [comment]
i thought the bigger problem is statefulsets doesnt support updates of volumeClaimTemplates. So would it make sense to support merge/patch ?

**Comment by adrian-gierakowski** [comment]
@krmayankk it does make sense to properly support strategic merge patch operation on the volumeClaimTemplates in order to allow using patches to generate configs for different enviroments using kustomiztion.yaml

**Comment by adrian-gierakowski** [comment]
can we please reopen this?

**Comment by rocketraman** [comment]
@pwittrock reopen? Just ran into this issue while trying to use kustomize.

**Comment by rocketraman** [comment]
> i thought the bigger problem is statefulsets doesnt support updates of volumeClaimTemplates. So would it make sense to support merge/patch ?

If this is the reason why merge/patch won't be supported for volume claim templates, then perhaps https://github.com/kubernetes-sigs/kustomize/issues/819 needs to be re-opened instead.

**Comment by kragniz** [comment]
I personally think this still makes sense in the context of applying a patch to generate resources, even if that patch would be rejected by the apiserver

/reopen

**Comment by adrian-gierakowski** [comment]
This is still important to me. Lack of merge key makes it difficult to user strategic merge patch to kustomize volumeClaimTemplates for different environments

**Comment by adrian-gierakowski** [comment]
Not rotten
