### ISSUE TITLE
godep restore script fails silently when jq command is missing

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#74838]
**What happened**:
```
hack/run-in-gopath.sh hack/godep-restore.sh
+++ [0301 15:57:42] Restoring kubernetes godeps
+++ [0301 15:57:42] Dependencies appear to be current - skipping download
```
Except the dependencies are definitely not current. This appears to happen when jq is missing on my machine.

**What you expected to happen**:
I expected the command to loudly report that jq is missing. 

**How to reproduce it (as minimally and precisely as possible)**:
Ensure that jq is not installed, then run this inside k/k:
```
hack/run-in-gopath.sh hack/godep-restore.sh
```

/assign @thockin

**Comment by thockin** [comment]
Specifically, godep-restore sends stderr to /dev/null.

I tried to fix that but the error code is not propagating up the way I expected it to, and I ran out of time to debug today.

**Comment by liggitt** [comment]
cc @sttts

**Comment by liggitt** [comment]
godep restore is gone. long live godep.

the replacement explicitly requires jq as one of the first steps in the script 

/clsoe

**Comment by thockin** [comment]
The bug was lurking DESPITE the `require-jq` but since the rewrite it doesn't seem to trigger any more..
