### ISSUE TITLE
"Connection reset by peer" due to invalid conntrack packets

### ISSUE THREAD

**Issue by anfernee** [kubernetes/kubernetes#74839]
**What happened**: Network services with heavy load will cause "connection reset" from time to time. Especially those with big payloads. When packets with sequence number out-of-window arrived k8s node, conntrack marked them as INVALID. kube-proxy will ignore them, without rewriting DNAT. The packet goes back the the original pod, who doesn't recognize the packet because of the wrong source ip, end up RSTing the connection. 

**What you expected to happen**: connection not reset

**How to reproduce it (as minimally and precisely as possible)**: 
@tcarmet wrote this just to reproduce the issue: https://github.com/tcarmet/k8s-connection-reset
Basically run it in a cluster, and after a while you will be able to see "Connection reset by peer" on both server and client pods. 

**Anything else we need to know?**:
Related issue: 
https://github.com/docker/libnetwork/issues/1090

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.7
- Cloud provider or hardware configuration: gke (should be general to all provider)
- OS (e.g: `cat /etc/os-release`): 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`): Linux gke-cluster-1-11-default-pool-161c67fc-6nzv 4.14.89+ #1 SMP Wed Jan 9 13:35:00 PST 2019 x86_64 GNU/Linux

**Comment by anfernee** [comment]
I created a small app to reproduce this issue: https://github.com/anfernee/k8s-issue-74839

**Comment by zuzzas** [comment]
I've been hitting this exact problem for packets between a Pod and the outside world.
So the DROP rule has to go into the INPUT chain. Is it the job of a CNI driver or the kube-proxy?

**Comment by kaitoy** [comment]
[The fix for this issue](https://github.com/kubernetes/kubernetes/pull/74840) was put to iptables mode but not to [ipvs mode](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1817), right?

Isn't ipvs mode affected by this issue, too?

**Comment by wenlxie** [comment]
> kube-proxy will ignore them, without rewriting DNAT. 

Can anyone point me  out how netfilter ignore this STATE invalid packet?

I checked the code in netfilter for function  iptable_nat_do_chain, but didn't find the code that handles the STATE=invalid packet.  
Thanks for help.

@anfernee

**Comment by anfernee** [comment]
Invalid is connection tracking state. My understanding is: If for some reason conntrack doesn't think it's the packet is "tracked" it could be grouped into "invalid" state. The problem is once it happens, [the connection will be reset](https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/#what-caused-the-connection-reset).

**Comment by anfernee** [comment]
> [The fix for this issue](https://github.com/kubernetes/kubernetes/pull/74840) was put to iptables mode but not to [ipvs mode](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1817), right?
> 
> Isn't ipvs mode affected by this issue, too?

ipvs should be fine. do you see similar issue in ipvs?

**Comment by wanggaolin** [comment]
I also encountered this problem. Have you solved it

**Comment by chenlein** [comment]
> ipvs should be fine. do you see similar issue in ipvs?

@anfernee  #112441 is this a similar issue for ipvs?

**Comment by anfernee** [comment]
> I also encountered this problem. Have you solved it

The error is a very general networking issue, which could be caused by many different reasons. This specific cause can be reproduced by the https://github.com/anfernee/k8s-issue-74839 



> > ipvs should be fine. do you see similar issue in ipvs?
> 
> Yongkun Anfernee Gui #112441 is this a similar issue for ipvs?

It looks like you got an answer already there :)
