### ISSUE TITLE
Conformance image / e2e considerations

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#74853]
A) `--num-nodes` seems to be required by some tests. we need to decide if jobs need to pass `--num-nodes` explicitly or let the e2e framework detect how many worker nodes a cluster has.
the conformance image has no notion of `--num-nodes` yet.
https://github.com/kubernetes/kubernetes/issues/74474

B) the conformance image runs `[Serial]` tests even in parallel mode:
https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh#L52-L55
if "y" is set in the YAML for `E2E_PARALLEL`
if we assume that `[Serial]` tests should not run in parallel mode, this means we need to pass `--skip=\\[Serial\\]` from the runner.
https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh#L44

C) should we switch the conformance image to `E2E_PROVIDER=skeleton`? currently it's `local`.
we need to check if this breaks anything.

discussion:
https://kubernetes.slack.com/archives/C78F00H99/p1551550250048900

/area test
/kind design
/kind bug
/assign @dims @BenTheElder @neolit123

**Comment by neolit123** [comment]
PRs - disable Parallel mode for conformance image (and test):
https://github.com/kubernetes/test-infra/pull/11588
https://github.com/kubernetes/kubernetes/pull/74851

**Comment by neolit123** [comment]
@kargakis @BenTheElder 

RE: https://github.com/kubernetes/kubernetes/pull/74293
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/daemon_set.go#L383

the introduction of ``framework.TestContext.CloudConfig.NumNodes`` in this test broke not only the kubeadm tests but also the conformance image and sonobuoy.

previously they did not require `--num-nodes` and we are now forced to detect the number of nodes outside of the e2e testing framework. possibly this test was the first conformance test that uses `NumNodes` as a aggressive failure condition.

there are two options here:
A) adapt all prow jobs, conformance image and sonobuoy, etc to explicitly pass `--num-nodes`. this ensures that future test will rely on the number of values the user provides and expects. we already starting going this route by providing mechanics for detecting schedulable nodes, per-solution.

B) auto-detect "ready", schedulable  nodes as a start number before, say a daemon set test runs and compare outcomes. this way a test will run on whatever number of nodes are currently available.

cc @timothysc @dims @spiffxp @pohly

**Comment by dims** [comment]
Line https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/daemon_set.go#L385 should be a explicit failure, not a `framework.Logf`

**Comment by dims** [comment]
@neolit123 i like option B!

**Comment by dims** [comment]
related to https://github.com/heptio/kube-conformance/pull/33

**Comment by BenTheElder** [comment]
Note that this test was NOT new, the other bug is ignoring skipped conformance tests. Ideally that shouldn't be possible.

**Comment by timothysc** [comment]
@dims I'm reluctant to make a sweeping change for 1.14 other then a band aide inside of test-infra. 

Ideally I'd like to assign this issue to the test-commons group to solve in 1.15.  
Thoughts?

**Comment by johnSchnake** [comment]
Agree that (A) (passing num-nodes explicitly) isnt a good option since it breaks other users who dont know about it in the first place and that this is well within the capabilities of the framework.

So for option (B) during startup of the framework we need to grab the nodes and count the number that are schedulable and not tainted as master nodes, correct? Save that into a TestContext variable and then reference it elsewhere as needed? Is the plan to reuse the existing `framework.TestContext.CloudConfig.NumNodes` value? I'm not at this time familiar with that value and whether it is needed in some other capacity and shouldn't be auto-set.

w.r.t. 1.14 vs 1.15; I don't have too strong a preference. I do generally prefer to let things bake a little longer inside of a release but t seems like if just the node count solves the problem its a small, scoped change that could make it in.

**Comment by timothysc** [comment]
From slack:  If num-nodes is not specified query on startup and over-ride the test context variable. 

@johnSchnake @stevesloka

**Comment by neolit123** [comment]
@johnSchnake 

> So for option (B) during startup of the framework we need to grab the nodes and count the number that are schedulable and not tainted as master nodes, correct?

a control plane node can be tainted as "master", but still allow workloads.
search for `effect:NoSchedulable` on all nodes, and exclude those that have it from the count.

> Is the plan to reuse the existing framework.TestContext.CloudConfig.NumNode

this is fed the `--num-nodes` flag, which is -1 by default.
if the user didn't add a value my suggestion is to just update `framework.TestContext.CloudConfig.NumNodes` with the detected count. also possibly add notes about that in the flag description.

> I'm not at this time familiar with that value and whether it is needed in some other capacity and shouldn't be auto-set.

future tests might decide to use this again (we already have some) and it will break if the user doesn't pass a valid number from the CLI flag. the "auto-detect if -1" logic seems reasonable and backwards compatible. how well our detection will work in complicated taint / toleration scenarios is another question.

> w.r.t. 1.14 vs 1.15; I don't have too strong a preference. I do generally prefer to let things bake a little longer inside of a release but it seems like if just the node count solves the problem its a small, scoped change that could make it in.

"Code Thaw" starts on the 19th of march. if we merge a change in master before that the change will also be picked by 1.14. if we patch this later the change has to be cherry picked for 1.14.
