### ISSUE TITLE
Way to see last node reboot/restart?

### ISSUE THREAD

**Issue by jmreicha** [kubernetes/kubernetes#74862]
**What would you like to be added**:

Currently there isn't a good way to check to see when a node was last rebooted/restarted (at least as far as I can tell) without having to log in to the server.

**Why is this needed**:

This is obviously useful for telling how long a server has been up and for quickly determining when a system was last patched, or not patched, which can be useful for debugging host level issues without having to log in to the server to check this.

Kubectl already retrieves other system related information such as OS and kernel versions and when the node was created and the amount of resources a machine has.

**Comment by WanLinghao** [comment]
I think we need this for each components(kube-master, kubelet, scheduler..)

**Comment by jmreicha** [comment]
Still interested in this, just haven't had a chance to look at implementing yet.
