### ISSUE TITLE
"docker ps" no containers in this node, but "kubectl get po" has running pods 

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#74878]
**What happened**:
`docker ps`  no running pod
`docker ps -a` can find containers have stopped
`kubectl get pod -o wide` can find this node have pods are running
I restart kubelet and the status became ok
I didn't notice any PLEG log in kubelet.log 
Maybe I think the kubelet cache is dirty because of some errors
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I cannot reproduce it , but I meet this problem twice half a year.
I want to know, have you ever had the same problem?
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ben-turner** [comment]
@Nebulazhang did you figure this out? I'm seeing the same thing on my cluster.
