### ISSUE TITLE
Unable to do full docker build of K8S on Macos [ Requires 8 GB docker vm memory size]

### ISSUE THREAD

**Issue by vyvekaggarwal** [kubernetes/kubernetes#74876]
**What happened**:

I am unable to do a full docker build of K8s on my macos machine

**What you expected to happen**: It is failing as follows:

No changes in generated bindata file: pkg/kubectl/generated/bindata.go
Go version: go version go1.12 linux/amd64
+++ [0303 21:30:50] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
Env for linux/amd64: GOOS=linux GOARCH=amd64 GOROOT=/usr/local/go CGO_ENABLED= CC=
Coverage is disabled.
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
!!! [0303 21:32:26] Call tree:
!!! [0303 21:32:26]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:614 kube::golang::build_some_binaries(...)
!!! [0303 21:32:26]  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:758 kube::golang::build_binaries_for_platform(...)
!!! [0303 21:32:26]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:582
  Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:582. '((i<5-1))' exited with status 1

**How to reproduce it (as minimally and precisely as possible)**:
build/run.sh make 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
 uname -a
Darwin Viveks-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
- Install tools:

Viveks-MacBook-Pro:kubernetes vivekagg$ docker --version
Docker version 18.09.2, build 6247962

- Others:

Any help to get this resolved will be appreciated.

**Comment by vyvekaggarwal** [comment]
Please note this happening even after I increased the RAM memory for docker VM to 4.5 GB

**Comment by vyvekaggarwal** [comment]
I had to increase the docker VM size to 8GB to get the build passing.

**Comment by vyvekaggarwal** [comment]
What is the minimum set of directories recommended to build to get started on contributing?

**Comment by guineveresaenger** [comment]
I am experiencing this issue as well.. upped my memory to 8GiB and nothing.

**Comment by rflorenc** [comment]
Same here. I was only able to `make quick-release` after giving docker 8Gib.
