### ISSUE TITLE
kubectl port-forward not working for websockets connection

### ISSUE THREAD

**Issue by ewnavilae** [kubernetes/kubernetes#74884]
**What happened**:
Can't remote debug NodeJS application running inside pod when using kubectl port-forward.

When starting a container with a nodeJS application and the --inspect=0.0.0.0:9229 flag, after port-forwarding with kubectl, Chrome DevTools acts as if there is no debug endpoint available and telnet acts as though nothing is listening on that port on the pod.

**What you expected to happen**:

Chrome DevTools should be able to perform remote debugging on this endpoint.
When connecting via telnet, if random text is sent, the expected output is as follows:

```
Escape character is '^]'.
asd
HTTP/1.0 400 Bad Request
Content-Type: text/html; charset=UTF-8

WebSockets request was expected
Connection closed by foreign host.
```

This shows there is a node process debugger listening on that port, instead, telnet behaves the same as if kubectl port-forward was executed on any other port without anything bound:

```
Escape character is '^]'.
Connection closed by foreign host.

```
**How to reproduce it (as minimally and precisely as possible)**:

First run
`kubectl run -it --rm --image=node --command node-inspect --generator=run-pod/v1 -- node --inspect=0.0.0.0:9229`

Then run
`kubectl port-forward node-inspect 9229`

At this point, if you run `telnet localhost 9229`, the connection is immediately closed.

**Anything else we need to know?**:

If the command is executed via an ssh tunnel like
`ssh -L 9229:$(kubectl get pods node -o json | grep podIP | awk '{print $2}' | cut -d '"' -f2):9229 root@k8master`
Then the debugging works perfectly.

IP tables has been used to open all ports.
The networking plugin is flannel.
Port-forwarding works normally for other HTTP services running on the cluster.

**Environment**:

- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:
`Local vSphere cluster`

- OS (e.g: `cat /etc/os-release`):
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

- Kernel (e.g. `uname -a`): 
`Linux k8master 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux`

- Install tools:
`kubeadm`

Can anyone reproduce this behaviour? If it works fine, could it be a simpler networking issue unrelated to kubernetes?

**Comment by ewnavilae** [comment]
Additionally, I have created a service and an ingress as further attempts to expose the debug feature on port 9229:

`kubectl expose pod node-inspect --port 9229`

Using the .yaml file:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-inspect
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: node-inspect.app.regra.pt
      http:
        paths:
          - path: /
            backend:
              serviceName: node-inspect
              servicePort: 9229 
```

When accessing the configured URI (node-inspect.app.regra.pt), I am met with the expected error message:

`WebSockets request was expected`

Yet adding the host and port (now 80, because of the ingress) to the list of DevTools connections yelded no results.no results.

**Comment by rmnoon** [comment]
Also running into this issue (specifically with a remote node debugger).  Thanks!

**Comment by dbalabka** [comment]
@rmnoon, @ewnavilae have you found a solution?

**Comment by rudolfbyker** [comment]
I see the exact same issue. Thanks for the SSH workaround :)

**Comment by mchandler-plato** [comment]
This is not a kubectl issue but a chrome (and/or nodejs) issue If you add `127.0.0.1:9229` to chrome://inspect under `Discover network targets` it works just fine.

Looking at wireshark trace it seems chrome tries to make the `localhost:9229/json/list` request to discover the nodejs inspect settings over ipv6 and fails but the exact same request works just fine over ipv4
