### ISSUE TITLE
[Failing test] [k8s.io] [sig-node] Kubelet regular resource usage tracking and clear up pods on node kubelet tests failing

### ISSUE THREAD

**Issue by smourapina** [kubernetes/kubernetes#74897]
**Which jobs are failing**:

Job	| Testgrid Link	| First failed build
--- | --- | ---
gke-cos-1.14-default | https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default | 9334
gke-cos-1.14-default | https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default | 9334
soak-gci-gce-1.14 | https://testgrid.k8s.io/sig-release-1.14-all#soak-gci-gce-1.14 | 641

**Which test(s) are failing**:
- `[k8s.io] NodeLease when the NodeLease feature is enabled the kubelet should create and update a lease in the kube-node-lease namespace`
- `[k8s.io] NodeLease when the NodeLease feature is enabled the kubelet should report node status infrequently`
- `[k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node`

**Since when has it been failing**:
2019-02-19

**Reason for failure**:
- Some timeouts (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-default/9335):
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/node_lease.go:84
Timed out after 300.000s.
```
- Memory usage exceeding limits (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/641)
```
node bootstrap-e2e-minion-group-ssr8:
 container "runtime": expected RSS memory (MB) < 367001600; got 370081792
```

/sig node
/kind failing-test
/priority critical-urgent
/milestone v1.14

cc @mariantalla @alejandrox1 @kacole2 @mortent

**Comment by alejandrox1** [comment]
since release-all jobs are non-blocking
/remove-priority critical-urgent
/priority important-soon

**Comment by alejandrox1** [comment]
All but `[k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node` in [sig-release-1.14-all#soak-gci-gce-1.14](https://testgrid.k8s.io/sig-release-1.14-all#soak-gci-gce-1.14) have cleared out.

The aforementioned tests in [sig-release-1.14-all#gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default) have been deleted.

**Comment by soggiest** [comment]
Hello! We are in code freeze for 1.14. It looks like this issue is not blocking 1.14. Can we move it to 1.15?

**Comment by alejandrox1** [comment]
@soggiest it isn't release blocking but we are keeping it within the v1.14 milestone as it is in the [sig-release-1.14-all](https://testgrid.k8s.io/sig-release-1.14-all) dashboard.

**Comment by ibrasho** [comment]
Hey @alejandrox1! Is anyone currently working on this? Just to make sure it's moving along :grin:

**Comment by alejandrox1** [comment]
Hi @ibrasho, usually, if there is no one assigned to an issue then there is no one is working on it.

**Comment by dchen1107** [comment]
This is not a release blocker.

**Comment by soggiest** [comment]
Since this is not a release blocker I'm going to remove the 1.14 milestone. 
/milestone clear

**Comment by mariantalla** [comment]
@dchen1107 Makes sense. As it's still release informing - are you concerned about the memory usage exceeding the limits expected by the test?

**Comment by alejandrox1** [comment]
Closing this as it doesn't seem to be a problem anymore.
/close
