### ISSUE TITLE
More Unit Tests for OpenStack Provider

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#74894]
**What would you like to be added**:
As per @GeetikaBatra comment here https://github.com/kubernetes/community/issues/2770#issuecomment-468992056, can we benefit from more unit tests on the OpenStack provider? If yes, @dims can you provide some guidance on what areas of the provider can benefit the most from this? 

Thanks @GeetikaBatra for offering to help!

**Comment by jaybatra26** [comment]
Thanks @andrewsykim for pointing me out in the right direction. 
@dims I would sincerely appreciate if you can help me kickstart it. Would [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack) be deprecated in future?

**Comment by GeetikaBatra** [comment]
Thanks @andrewsykim for pointing me in the right direction. 

@dims would [this](https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers/openstack) be deprecated in long run? I would sincerely appreciate if you can help me kickstart this.

**Comment by dims** [comment]
@GeetikaBatra yes, please add more tests in the kubernetes/cloud-provider-openstack repository. We need stop making any changes in the kubernetes/kubernetes repository as it will be dropped soon. yes it was already deprecated.

We could add more unit tests as well as more functional (and eventually e2e tests) in the kubernetes/cloud-provider-openstack repository. ( cc @adisky @hogepodge @mrhillsman )

**Comment by andrewsykim** [comment]
Seems like we should re-open this issue in kubernetes/cloud-provider-openstack then! 

/close
