### ISSUE TITLE
[Failing test] diffResources in master-upgrade

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74890]
**Which jobs are failing**:
* `ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new`
* `ci-kubernetes-e2e-gce-new-master-upgrade-cluster`

**Which test(s) are failing**:
`diffResources`

**Since when has it been failing**:
2019-03-01

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster
* https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new

**Reason for failure**:
```
Error: 12 leaked resources
+NAME                                                            ZONE        SIZE_GB  TYPE         STATUS
+bootstrap-e2e-78e337f9-3d2f-11e9-a656-2acb4231a6ed              us-west1-b  2        pd-standard  READY
+bootstrap-e2e-dynamic-pvc-796bbc5d-3d2f-11e9-9e04-42010a8a0002  us-west1-b  1        pd-standard  READY
+bootstrap-e2e-dynamic-pvc-85e2b93a-3d2f-11e9-9e04-42010a8a0002  us-west1-b  1        pd-standard  READY
+bootstrap-e2e-dynamic-pvc-97d1f1dd-3d2f-11e9-9e04-42010a8a0002  us-west1-b  1        pd-standard  READY
```

**Anything else we need to know**:
Might be related: https://github.com/kubernetes/kubernetes/issues/74417 (a recent diffResources test failure) and https://github.com/kubernetes/kubernetes/issues/74887 (started failing at the same jobs, at the same time).

/sig storage
/sig testing
/kind failing-test
/priority critical-urgent
/milestone v1.14

cc @smourapina @alejandrox1 @kacole2 @mortent 
cc @kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
In https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2826/build-log.txt, I see that the first thing the test does is upgrade the cluster, and that failed:
```
I0305 04:24:27.797] fatal error: sync: inconsistent mutex state
I0305 04:24:27.887] Test Suite Failed
W0305 04:24:27.988] !!! Error in ./hack/ginkgo-e2e.sh:143
W0305 04:24:27.989]   Error in ./hack/ginkgo-e2e.sh:143. '"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- "${auth_config[@]:+${auth_config[@]}}" --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" --host="${KUBE_MASTER_URL}" --provider="${KUBERNETES_PROVIDER}" --gce-project="${PROJECT:-}" --gce-zone="${ZONE:-}" --gce-region="${REGION:-}" --gce-multizone="${MULTIZONE:-false}" --gke-cluster="${CLUSTER_NAME:-}" --kube-master="${KUBE_MASTER:-}" --cluster-tag="${CLUSTER_ID:-}" --cloud-config-file="${CLOUD_CONFIG:-}" --repo-root="${KUBE_ROOT}" --node-instance-group="${NODE_INSTANCE_GROUP:-}" --prefix="${KUBE_GCE_INSTANCE_PREFIX:-e2e}" --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" --node-tag="${NODE_TAG:-}" --master-tag="${MASTER_TAG:-}" --cluster-monitoring-mode="${KUBE_ENABLE_CLUSTER_MONITORING:-standalone}" --prometheus-monitoring="${KUBE_ENABLE_PROMETHEUS_MONITORING:-false}" --dns-domain="${KUBE_DNS_DOMAIN:-cluster.local}" --ginkgo.slowSpecThreshold="${GINKGO_SLOW_SPEC_THRESHOLD:-300}" ${KUBE_CONTAINER_RUNTIME:+"--container-runtime=${KUBE_CONTAINER_RUNTIME}"} ${MASTER_OS_DISTRIBUTION:+"--master-os-distro=${MASTER_OS_DISTRIBUTION}"} ${NODE_OS_DISTRIBUTION:+"--node-os-distro=${NODE_OS_DISTRIBUTION}"} ${NUM_NODES:+"--num-nodes=${NUM_NODES}"} ${E2E_REPORT_DIR:+"--report-dir=${E2E_REPORT_DIR}"} ${E2E_REPORT_PREFIX:+"--report-prefix=${E2E_REPORT_PREFIX}"} "${@:-}"' exited with status 1
```

I think the aborted upgrade test is what caused the resources to leak.  For example, here's one leaked resource:
```
+bootstrap-e2e-dynamic-pvc-8b28e181-3efb-11e9-ad32-42010a8a0002  us-west1-b  1        pd-standard  READY
```

In the job, it is used by a pod that's part of the upgrade test:
```
I0305 14:00:17.224541       1 pv_controller.go:512] synchronizing PersistentVolume[pvc-8b28e181-3efb-11e9-ad32-42010a8a0002]: phase: Bound, bound to: "sig-apps-statefulset-upgrade-7984/datadir-ss-0 (uid: 8b28e181-3efb-11e9-ad32-42010a8a0002)", boundByController: true
```

**Comment by msau42** [comment]
@kubernetes/sig-cluster-lifecycle to triage the failing upgrade test.

/remove-sig storage

**Comment by timothysc** [comment]
I didn't dig too deep but these are googles tests not communities.  

/assign @justinsb 

@spiffxp - given that Robert used to triage the inbound, who is the google owner for /cluster?

**Comment by timothysc** [comment]
fwiw it looks like there are some @kubernetes/sig-network-misc failures too.

**Comment by timothysc** [comment]
For reference ours (SCL-community) are green - https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master

**Comment by MrHohn** [comment]
> fwiw it looks like there are some @kubernetes/sig-network-misc failures too.

Ref https://github.com/kubernetes/kubernetes/issues/74887#issuecomment-469923944, the firewall test failure is also caused by UpgradeTest unexpected hitting error and exiting in the middle, as described on https://github.com/kubernetes/kubernetes/issues/74890#issuecomment-469819930.

**Comment by kacole2** [comment]
This is also flaking on [sig-release-master-upgrade#gce-new-master-upgrade-master-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master-parallel) @mariantalla

**Comment by neolit123** [comment]
> I0305 04:24:27.797] fatal error: sync: inconsistent mutex state

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/lifecycle/cluster_upgrade.go#L435-L455

i would try this to see what happens with primitives only vs the go routine mutex wakeup problem:
```
...
readyLock := int32(0)
ready := func() {
	if atomic.LoadInt32(&readyLock) == 0 {
		defer atomic.StoreInt32(&readyLock, 1)
		sem.Ready()
	}
}
...
```

**Comment by justinsb** [comment]
@neolit123  great find!  I'm trying to figure out why that is panic-ing - do you have any links for the "go routine mutex wakeup problem" you referenced?

**Comment by neolit123** [comment]
@justinsb 

i tried looking for where the error string is coming from and ended up here:
https://github.com/golang/go/blob/release-branch.go1.12/src/sync/mutex.go#L143

also:
https://github.com/golang/go/blob/release-branch.go1.12/src/sync/mutex.go#L42

so a routine was woken, it attempts to acquire a lock, but it fails and the mutex enters starvation mode.
the FIFO waiters are supposed to set the `mutexLocked` bit after wakeup, bit this goroutine has reached a  undefined state where the mutex is both starving and the lock is not set.

the cause for the "throw" might as well be process resource exhaustion, but i don't know why that may happen. on a quick look the upgrade framework doesn't seem to be doing anything wrong, but this needs debugging. 

my proposal with the primitives above was to completely bypass the go mutex fairness and observe if the behavior changes with the bare instrinsics.

i wonder if the 1.12 update changed something here or if this was flaking with 1.11 too.

**Comment by justinsb** [comment]
Great analysis @neolit123 ... I agree that something is weird, and I agree that it seems like the 1.12 update is probably not unrelated.  Re-creating sync.Once without a mutex is a bit tricky, but your suggestion looks right (though it probably should use sync.CompareAndSwapUint32).  I can send a PR, unless you want to?

**Comment by neolit123** [comment]
i really don't have a setup to debug this failure properly. :\
any chance we can get the attention of krousey on this, as he is the author of the upgrade framework logic?

**Comment by justinsb** [comment]
I did ping @krousey and (I think) he concurs.  Your analysis was much deeper than what I did @neolit123 :-)  I was thinking it was something to do with copying the mutex somehow.

What I propose we do is that we get a compare-and-swap in there (I'll send a PR) and then we get the attention of the go team as it feels like a 1.12 regression if it does fix it.

I haven't been able to reproduce the problem in isolation.

**Comment by justinsb** [comment]
CAS idea is in #75305.  I don't have a better idea than trying it and seeing if it works...

**Comment by liggitt** [comment]
> i wonder if the 1.12 update changed something here or if this was flaking with 1.11 too.

fyi, the only change in the sync package between go 1.11 and 1.12 was in sync.Map:

```diff
$ git diff upstream/release-branch.go1.11 upstream/release-branch.go1.12 -- src/sync
diff --git a/src/sync/atomic/doc.go b/src/sync/atomic/doc.go
index 7c007d7a15..108b76b804 100644
--- a/src/sync/atomic/doc.go
+++ b/src/sync/atomic/doc.go
@@ -47,7 +47,8 @@ import (
 //
 // On non-Linux ARM, the 64-bit functions use instructions unavailable before the ARMv6k core.
 //
-// On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit
+// On ARM, x86-32, and 32-bit MIPS,
+// it is the caller's responsibility to arrange for 64-bit
 // alignment of 64-bit words accessed atomically. The first word in a
 // variable or in an allocated struct, array, or slice can be relied upon to be
 // 64-bit aligned.
diff --git a/src/sync/map.go b/src/sync/map.go
index c4a0dc4194..c6aa308856 100644
--- a/src/sync/map.go
+++ b/src/sync/map.go
@@ -167,18 +167,14 @@ func (m *Map) Store(key, value interface{}) {
 // If the entry is expunged, tryStore returns false and leaves the entry
 // unchanged.
 func (e *entry) tryStore(i *interface{}) bool {
-       p := atomic.LoadPointer(&e.p)
-       if p == expunged {
-               return false
-       }
        for {
-               if atomic.CompareAndSwapPointer(&e.p, p, unsafe.Pointer(i)) {
-                       return true
-               }
-               p = atomic.LoadPointer(&e.p)
+               p := atomic.LoadPointer(&e.p)
                if p == expunged {
                        return false
                }
+               if atomic.CompareAndSwapPointer(&e.p, p, unsafe.Pointer(i)) {
+                       return true
+               }
        }
 }
 
diff --git a/src/sync/runtime.go b/src/sync/runtime.go
index be16bcc8f7..b6b9e480a4 100644
--- a/src/sync/runtime.go
+++ b/src/sync/runtime.go
@@ -54,7 +54,7 @@ func init() {
 }
 
 // Active spinning runtime support.
-// runtime_canSpin returns true is spinning makes sense at the moment.
+// runtime_canSpin reports whether spinning makes sense at the moment.
 func runtime_canSpin(i int) bool
 
 // runtime_doSpin does active spinning.
```

**Comment by neolit123** [comment]
as per https://github.com/golang/go/commit/91fd14b82493e592730a3e459ef6610195b854c2 something else to try (which is actually the better test solution here) is to declare the symbol of the deferred function.

pseudo:
```
func readyTest(once sunc.Once, sem *chaosmonkey.Semaphore) {
	once.Do(func() {
		sem.Ready()
	})
}

func (cma *chaosMonkeyAdapter) Test(sem *chaosmonkey.Semaphore) {
	start := time.Now()
	var once sync.Once
	...
	defer readyTest(once, sem)
	...
	readyTest(once, sem)
	...
}
```

**Comment by liggitt** [comment]
we'll need a go1.12.1 for that... we shouldn't try to sweep use of sync.Once to adjust to the go1.12 bug... there are too many uses inside vendor

**Comment by neolit123** [comment]
i completely agree.
i'm just proposing random fixes to isolate the golang bug.
(though, at this point we are not even sure if we are actually encountering the exact same bug)

will request from on-call to retrigger one of the jobs before we jump into reverting.
but it seems reverting is the plan for now...

**Comment by tpepper** [comment]
Do we have a list of golang project issues/prs/commits we're looking at here?  Like do we have concrete reason to believe some specific relevant things would be in a 1.12.1 (hopefully soon)?

**Comment by neolit123** [comment]
> Like do we have concrete reason to believe some specific relevant things would be in a 1.12.1 (hopefully soon)?

all is speculation as per debugging mutexes on a super slow e2e test job.

**Comment by neolit123** [comment]
i don't know when 1.12.1 is coming out but i see some a number of open tickets here:
https://github.com/golang/go/milestone/92

**Comment by dims** [comment]
@rsc @bradfitz @Sajmani Looks like we have to move to upcoming golang 1.12.1 to pick up [1] or go back to 1.11.5 (lot of things to switch back!). Can you please advise when 1.12.1 may be available?

[1] https://github.com/golang/go/commit/91fd14b82493e592730a3e459ef6610195b854c2

**Comment by bradfitz** [comment]
I've started a discussion with the release team. Hopefully soon. It's been long enough since the Go 1.12(.0) release and we have a few things on or ready for the Go 1.12 branch. We'll keep you updated.

/cc @andybon @dmitshur @bcmills @ianlancetaylor

**Comment by justinsb** [comment]
Great find on the (likely) underlying issue @dims.  And I think you're right @neolit123 that even the workaround will not work, because it'll (probably) hit the same bug.  I suspect it might not panic so it might actually end up working "accidentally" - we'll see.

But - regardless - feels like we have a root-cause.  We can try your workaround @neolit123 if we think it'll help get us test signal again faster than switching go releases.

**Comment by spiffxp** [comment]
@bradfitz to give some context, we are currently scheduled to lift our code freeze by Tuesday March 19th, and stop accepting changes by Thursday March 21st (https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#timeline)

I'm willing to push out code freeze for a day or two for this, but if we can't try go1.12.1 by the 19th my gut says we need to revert.  Would really make our lives easier if it was this week.

**Comment by neolit123** [comment]
the last two runs with this patch: https://github.com/kubernetes/kubernetes/pull/75305
don't have the mutex failure it seems:
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster
see ..42, 43.

but 1.12.1 is still ideal, as noted here: https://github.com/kubernetes/kubernetes/issues/74890#issuecomment-472500878

**Comment by bradfitz** [comment]
We're aiming for a Go 1.12.1 soon: tonight at earliest, but likely tomorrow. Or worst case Friday if there are surprises.

**Comment by dims** [comment]
@bradfitz you all rock!

**Comment by justinsb** [comment]
Looks like the hackaround in #75305 did "work" in that UpgradeTest is no longer panic-ing and we are getting test signal again.  The locking is probably incorrect now and probably is still hitting the same bug and we just aren't panicing, but we have test signal! 

Results look not-terrible - some flakes on ESIPP and storage, but not on the same test in the (very small) sample so far.  And kudos to whoever had the good idea to trigger multiple parallels runs of this test so we got more results faster!

I believe this does suggest that we were hitting the deferred closure GC issue.

**Comment by neolit123** [comment]
> Results look not-terrible

indeed, and the diffResources test passes now.

> I believe this does suggest that we were hitting the deferred closure GC issue.

yes, once we revert our hack patch after a 1.12.1 bump we will be sure.

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/kubernetes/issues/75372, I want us to be ready with next steps.  Who wants to take the lead on pushing it forward?  I took a guess at the required steps in the description, please comment if I got anything wrong

I feel like we should also have an issue open to plan out what a rollback to go 1.11.5 would look like _just in case_, because I'd like to understand how much time needs to be budgeted for that, and work back to a decision point

**Comment by bradfitz** [comment]
Go 1.12.1 is out: https://golang.org/dl/

(And a Go 1.11.x update.)

**Comment by dims** [comment]
Thanks @bradfitz !

**Comment by mariantalla** [comment]
https://github.com/kubernetes/kubernetes/issues/75372 is expected to resolve this issue.

**Comment by Sajmani** [comment]
Thanks for the quick work, all.

**Comment by spiffxp** [comment]
It's looking like we've addressed this, will wait and see what further runs over the weekend bring in
ref: https://github.com/kubernetes/kubernetes/issues/75372#issuecomment-473498951
ref: https://github.com/kubernetes/kubernetes/issues/75372#issuecomment-473570787

**Comment by spiffxp** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gce.*upgrade&test=diffResources

Here we can see occurrences of `diffResources` for `/gce.*upgrade/` jobs increased after March 1st when golang 1.12 was introduced
![Screen Shot 2019-03-18 at 1 32 52 PM](https://user-images.githubusercontent.com/49258/54561647-5a3c7b00-4982-11e9-92b1-e8844c8e2018.png)

Here we can see the occurrences drop off sharply after our workaround was introduced, and stay low once the workaround was removed and golang 1.12.1 introduced
![Screen Shot 2019-03-18 at 1 32 35 PM](https://user-images.githubusercontent.com/49258/54561653-5dd00200-4982-11e9-86d5-b1719d74c486.png)

Calling this resolved
