### ISSUE TITLE
[Failing test] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74893]
**Which jobs are failing**:

| Job | Testgrid Link | First failed build | 
---|---|---|
| `ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster`| https://testgrid.k8s.io/sig-release-1.14-all#gce-1.13-1.14-upgrade-cluster | [1182](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster/1182) | Feb 19 | test infra 93b67c55b|
|`ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-parallel`|https://testgrid.k8s.io/sig-release-1.14-all#gce-1.13-1.14-upgrade-cluster-parallel | [1151](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-parallel/1151) |
| ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new | https://testgrid.k8s.io/sig-release-1.14-all#gce-1.13-1.14-upgrade-cluster-new | [1081](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new/1081) |
| `ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new-parallel` | https://testgrid.k8s.io/sig-release-1.14-all#gce-1.13-1.14-upgrade-cluster-new-parallel | [1145](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new-parallel/1145) | 
| `ci-kubernetes-e2e-gke-stable1-beta-upgrade-cluster-new` | https://testgrid.k8s.io/sig-release-1.14-all#gke-1.13-1.14-upgrade-cluster-new | [1127](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-stable1-beta-upgrade-cluster-new/1127)

**Which test(s) are failing**:
`[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]`

**Since when has it been failing**:
2019-02-19

**Reason for failure**:
Seems to be related to the removal of the apparmor pod:
```
Expected error:
    <*errors.StatusError | 0xc000648750>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
            Status: "Failure",
            Message: "pods \"test-apparmor-j8mln\" not found",
            Reason: "NotFound",
            Details: {
                Name: "test-apparmor-j8mln",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    pods "test-apparmor-j8mln" not found
```

/sig cluster-lifecycle
/kind failing-test
/priority critical-urgent
/milestone v1.14

cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
release-all jobs aren't release-blocking, I would prefer we save the red priority for those

**Comment by soggiest** [comment]
Hello! We are in code freeze for 1.14. If these issues are not release blocking can we move this issue to 1.15?

**Comment by alejandrox1** [comment]
@soggiest we are tracking this in milestone v1.14 because the aforementioned tests are part of https://testgrid.k8s.io/sig-release-1.14-all#gce-1.13-1.14-upgrade-cluster

**Comment by mariantalla** [comment]
@justinsb Is this something you could help with?

**Comment by timothysc** [comment]
/assign @justinsb  
/cc @kubernetes/sig-gcp-bugs  

These tests should probably change ownership to GCP now-a-days b/c the sig does not maintain them and they are only owned by google.

**Comment by mariantalla** [comment]
/remove-priority critical-urgent
(sorry, it was because I edited the original description of the issue)

**Comment by alejandrox1** [comment]
It appears these issues are still ongoing

**Comment by alejandrox1** [comment]
It appears these issues are still ongoing
/remove-milestone v1.14
/milestone v1.15

**Comment by soggiest** [comment]
This hasn't been worked looked at in about a month, I'm moving to 1.16
/milestone v1.16

**Comment by Verolop** [comment]
Are there any updates or follow up actions for this issue?

**Comment by alejandrox1** [comment]
Info in this issue is a bit stale as there have been a ton of changes.
Work related to the ci jobs mentioned in this issue can be tracked in https://github.com/kubernetes/kubernetes/issues/78995

/close
