### ISSUE TITLE
"kubectl logs --selector" ignores "--tail=-1"

### ISSUE THREAD

**Issue by adkerr** [kubernetes/kubernetes#74900]
**What happened**:

When attempting to get all log lines using `kubectl logs -l app=my.app --tail=-1` only 10 lines of logs are returned

**What you expected to happen**:

All log lines should be returned

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl logs -l app=my.app --tail=-1`

**Anything else we need to know?**:

This was introduced in ea7065d47187356f442ed2722c59833b8c4bf067 in an attempt to fix another issue where selectors would ignore tail values !=-1. I think the problem here is the logic cannot tell if the `-1` was set explicitly by the command line or is simply the initial default value.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.3
- Cloud provider or hardware configuration: Kubeadm
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by liucimin** [comment]
Maybe is not a bug.
See the kubectl help.

 --tail=-1: Lines of recent log file to display. Defaults to -1 with no selector, showing all log lines otherwise
10, if a selector is provided.

I think i mean  a selector is provided the --tail should not use -1 ?

**Comment by JishanXing** [comment]
> Maybe is not a bug.
> See the kubectl help.
> 
> --tail=-1: Lines of recent log file to display. Defaults to -1 with no selector, showing all log lines otherwise
> 10, if a selector is provided.
> 
> I think i mean a selector is provided the --tail should not use -1 ?

Thanks for you reply.

There are some background in below tickets, --tail=-1 is one of the option. Please check.

https://github.com/kubernetes/kubernetes/issues/51027
https://github.com/kubernetes/kubernetes/issues/35335

**Comment by adkerr** [comment]
@liucimin The help indicates that the _default_ is 10 if the selector is used. But if someone explicitly
asks for -1 it should still work, at least in my opinion.

**Comment by mikespokefire** [comment]
Encountering similar behaviour to this myself. Is there any chance whatever fixes get applied can also be applied to the `1.12.x` branch? Since that also has strange behaviour around logs with label selectors and setting `--tail`. See https://github.com/kubernetes/kubernetes/blob/v1.12.6/pkg/kubectl/cmd/logs.go#L180-L184

**Comment by JishanXing** [comment]
This ticket has two issues:
1) It's said "TailLines must be greater than or equal to 0", however we can specify -1.
kubectl logs -l app=test --tail=-3
error: TailLines must be greater than or equal to 0

kubectl logs -l app=test --tail=-1
12462: Wed Apr 10 06:51:34 UTC 2019
12463: Wed Apr 10 06:51:35 UTC 2019
12464: Wed Apr 10 06:51:36 UTC 2019
12465: Wed Apr 10 06:51:37 UTC 2019
12466: Wed Apr 10 06:51:38 UTC 2019
12467: Wed Apr 10 06:51:39 UTC 2019
12468: Wed Apr 10 06:51:40 UTC 2019
12469: Wed Apr 10 06:51:41 UTC 2019
12470: Wed Apr 10 06:51:42 UTC 2019
12471: Wed Apr 10 06:51:43 UTC 2019

2) --tail=-1 is the legacy usage which show all lines, here just return 10 lines.
kubectl logs -l app=test --tail=-1

The behavior after fix:

Tail value   Show lines
------------------------
Default      All lines
-1           All lines
<-1          error: TailLines must be greater than or equal to -1
=0           No logs, always used with -f
>0           Show N lines

Test cases:
./kubectl logs -l app=test --tail=-3
./kubectl logs -l app=test --tail=-1
./kubectl logs -l app=test --tail=2
./kubectl logs -l app=test --tail=0

**Comment by wdoekes** [comment]
Interesting. I think this also causes `--since-time` to fail:
```
$ kubectl -n NS --timestamps --tail=100000 POD-79c6f59559-slrst \
    --since-time='2019-04-25T10:22:26+02:00' | sort -n | head -n1 | sed -e 's/].*/]/g'
2019-04-25T08:22:23.547400000Z [pid: 13|app: 0|req: 135/325]
```
^-- expected record
```
$ kubectl -n NS logs --timestamps --selector=app=APPNAME \
    --since-time='2019-04-25T10:22:26+02:00' | sort -n | head -n1 | sed -e 's/].*/]/g'
2019-04-25T08:44:34.048756000Z [pid: 12|app: 0|req: 137/1153]
```
^-- some later record (there are only 2 pods running, so `--max-log-requests` is not relevant)
```
$ kubectl -n NS logs --timestamps --tail=10000 --selector=app=APPNAME \
    --since-time='2019-04-25T10:22:26+02:00' | sort -n | head -n1 | sed -e 's/].*/]/g'
2019-04-25T08:22:23.547400000Z [pid: 13|app: 0|req: 135/325]
```
^-- adding `--tail=N` makes it work

**Comment by wdoekes** [comment]
A bit strange that it finds records a few seconds older as well.. but that's not a big concern, and not relevant for this issue.
```
$ kubectl -n NS logs --timestamps POD-79c6f59559-p5mg5 \
    --since-time='2019-04-25T10:15:00+02:00' | sort -n | head -n2 | sed -e 's/].*/]/g'
2019-04-25T08:14:59.911926000Z [pid: 13|app: 0|req: 25/83]
2019-04-25T08:15:00.058213000Z [pid: 14|app: 0|req: 45/84]  <-- first record from 10:15+
```
vs.
```
# docker logs k8s_web_POD-79c6f59559-p5mg5_NS_e427eade-6731-11e9-a87b-002590e425d2_0 \
    --timestamps --since='2019-04-25T10:15:00+02:00' 2>&1 | sort -n | head -n2 | sed -e 's/].*/]/g'
2019-04-25T08:15:00.058213000Z [pid: 14|app: 0|req: 45/84]  <-- first record from 10:15+
2019-04-25T08:15:00.205318000Z [pid: 13|app: 0|req: 26/85]
```
Although that only happens when the `--tail` workaround is used:
```
$ kubectl -n ossoio-core logs --timestamps POD-79c6f59559-p5mg5 \
    --since-time='2019-04-25T10:15:00+02:00' | sort -n | head -n2 | sed -e 's/].*/]/g'
2019-04-25T08:15:00.058213000Z [pid: 14|app: 0|req: 45/84]  <-- first record from 10:15+
2019-04-25T08:15:00.205318000Z [pid: 13|app: 0|req: 26/85]
```
:thinking:
