### ISSUE TITLE
hostAliases do not work on deployments

### ISSUE THREAD

**Issue by mapdegree** [kubernetes/kubernetes#74901]
@kubernetes/sig-feature-requests
/sig feature-requests

We need to set the hostAliases on the deployment and deamonset in the latest version of Kubernetes.

Current documentarion support only pod manifest amendments and would appreciate extending this functionality to other deployment types. 

https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

Could you please consider this functionality in 1.14?

Regards, 
Dejan

@kubernetes/sig-feature-requests

/sig feature-requests

**Comment by mapdegree** [comment]
@kubernetes/sig-feature-requests

**Comment by bowei** [comment]
/kind feature

@mapdegree can you give a snippet as to what you are missing from Deployment and Daemonset. I thought the Pod teamplte will have the same type as the actual PodSpec.

**Comment by mitpwd** [comment]
Hi @bowei , 
here is an example error message I receive on a Deployment (kubectl apply -f deployment.yml).
I am using K8S 1.11.8 and kubectl 1.11.8.

`
$ kubectl apply -f reshifter-app.yaml
error: error validating "reshifter-app.yaml": error validating data: ValidationError(Deployment.spec): unknown field "hostAliases" in io.k8s.api.extensions.v1beta1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
`

Here is an example manifest (yml) for the deployment:

`
apiVersion:       extensions/v1beta1
kind:             Deployment
metadata:
  name:           reshifter
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
  - ip: "10.1.2.3"
    hostnames:
    - "foo.remote"
    - "bar.remote"
  replicas:       1
  template:
    metadata:
      labels:
        app:      reshifter
    spec:
      containers:
      - name:     reshifter-app
        image:    quay.io/mhausenblas/reshifter:0.3.21
        ports:
        - containerPort: 8080
`

**Comment by bowei** [comment]
Don't you need to put the hostAliases in the `template:` section of the Deployment?

**Comment by mitpwd** [comment]
Yes, that solved the problem. 

Would it make sense to add an example to the existing documentation for a Deployment? 

It would help new users of Kubernetes. I am happy to raise a PR.

Thank you!

**Comment by bowei** [comment]
`hostAliases` is a field in the Pod spec, and there are no spec fields from pod in the top-level for Deployment, so I'm hesitant to add docs for this (it's a schema error...) that could apply to any field.

/close

**Comment by AAber** [comment]
> Don't you need to put the hostAliases in the `template:` section of the Deployment?

Thanks for the tip helped me add the hostAliases, sample:

  template:
    metadata:
      labels:
        app: gwsc
    spec:
      hostAliases:
      - ip: "10.9.1.8"
        hostnames:
        - "redis-1c"
      - ip: "10.9.1.1"
        hostnames:
        - "redis-1b"

**Comment by AAber** [comment]
bowei - Thanks for the tip!!!
 Helped me add hostAliases to my deployment, sample:
```
  template:
    metadata:
      labels:
        app: gateway
    spec:
      hostAliases:
      - ip: "10.9.1.8"
        hostnames:
        - "redis-1c"
      - ip: "10.9.1.15"
        hostnames:
        - "redis-1b"
```
