### ISSUE TITLE
Investigate CheckVolumeExistence corner cases

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74914]
**What happened**:
Followup from https://github.com/kubernetes/kubernetes/pull/74653, a number of corner cases were identified as possibility being problematic:

* Reconstruction of attachable plugins when mount point is corrupted/stale
* Reconstruction of attachable plugins when mount point only partially cleaned up (mount is deleted but the directory still exists), or attachable plugin doesn't use mounts
* Reconstruction of raw block when device naming changes on a reboot. cc @wongma7 
* Is this going to be a problem for inline ephemeral volumes because reconstruction gets attachable plugin by name. cc @vladimirvivien 

cc @jingxu97 @chakri-nelluri

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by wongma7** [comment]
> Reconstruction of raw block when device naming changes on a reboot

The best we can do is check if the symlink is broken. This would be equivalent to checking if the mount point is corrupted/stale. However, if the symlink is broken and it is passed as a device to the container runtime the pod should fail to start anyway. But it shouldn't hurt to check so I will work on a patch to modify that `Check` function to check if the symlink is broken

Note I am unsure in what scenarios device names could change in the first place (without admin doing something to the node on purpose). e.g. most plugins like gcepd have unique persistent names like /dev/disk/by-id/*. aws ebs doesn't but its per-instance block device mappings are persistent.

**Comment by msau42** [comment]
What I'm more worried about is if on a reboot the symlink still exists but the device name has changed.  Cloud may not have this issue but I'm not familiar other volume types like iscsi or fc to know for sure. cc @mkimuram @bswartz

**Comment by msau42** [comment]
/lifecycle frozen
cc @jsafrane

**Comment by jsafrane** [comment]
> * Reconstruction of raw block when device naming changes on a reboot. cc @wongma7

Checked with in-tree iSCSI, all devices are removed after reboot and volumes are cleaned up. Did not check with CSI (no iSCSI there) nor in-tree Fibre Channel (no HW).

**Comment by jsafrane** [comment]
Tried with in-tree GCE PD, Azure and AWS.

* On AWS, it's Kubernetes who assigns device names for block devices. Block devices are not reordered on reboot.
* On GCE and Azure, block devices can be reordered, however, kubelet cleans just the symlinks in /var/lib/kubelet for deleted pods and thus it does not really matter if a device was renamed, only a potentially wrong or broken symlink is removed. Or, in case the pod still exists after reboot, kubelet goes through full mount cycle, incl. `WaitForAttach()` that finds the right device and fixes the symlinks.

* Reading Cinder code, its WaitForAttach finds the right device from udev.
* Reading Ceph RBD, its WaitForAttach finds the right device from /sys.
* Reading vSphere, its volumes are identified by /dev/disk/by-id/UUID of the volume.

So I would consider in-tree & reboot & potential reordering of devices as tested.

TODO: check one or two CSI drivers.

**Comment by jsafrane** [comment]
Checked with CSI GCE PD and AWS, both survive reboot just fine. See https://github.com/kubernetes/enhancements/issues/565#issuecomment-584590923

**Comment by jsafrane** [comment]
I think this issue has been dealt with, feel free to reopen if I missed anything.

/close
