### ISSUE TITLE
[test failed] "regular resource usage tracking resource tracking for 100 pods per node" for containerd

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#74917]
**Which jobs are failing**: sig-node-containerd/e2e-gci-serial

**Which test(s) are failing**: regular resource usage tracking resource tracking for 100 pods per node

**Since when has it been failing**: 2/28/2019

**Testgrid link**: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-serial/1884

**Reason for failure**: I think this is related to golang update to 1.12.

**Anything else we need to know**:

@mikebrow @yujuhong @kubernetes/sig-node-bugs

**Comment by Random-Liu** [comment]
It's a known issue that containerd has a per-container containerd-shim process. For each containerd-shim process, we need to pay for the go runtime memory overhead.

We updated to golang 1.12 in https://github.com/kubernetes/test-infra/commit/20b1c5787afa443300611ff63c65fcf79d874a31 and https://github.com/kubernetes/kubernetes/commit/f1d2fee2596bad3f50fbcf6ebf7cff295142699a.

And it seems that golang 1.12 has a even larger runtime size.

With containerd 1.3, we should be able to address this with per-pod containerd-shim https://github.com/containerd/containerd/pull/3004.

But before that, we need to either downgrade golang version for containerd to 1.11, or bump up the memory limit in the etst.

**Comment by mariantalla** [comment]
btw the same test is failing in the e2e upgrade tests[1], but with a different error message. Will open a new issue and link here.

[1] e.g. [build 2827](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2827) in [sig-release-master-upgrade#gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster)

cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by alejandrox1** [comment]
The test mentioned in this issue is still failing:
`[k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node`
see https://testgrid.k8s.io/sig-node-containerd#e2e-gci-serial

/cc @kubernetes/sig-node-test-failures 
/milestone v1.16
/priority important-soon
/remove lifecycle-rotten

**Comment by scottilee** [comment]
https://testgrid.k8s.io/sig-node-containerd#e2e-gci-serial is still failing and has been for a long time. Could someone look into this and provide an update?

/cc @dchen1107 @derekwaynecarr

**Comment by jimangel** [comment]
Friendly ping again on this issue! 👋 

/cc @kubernetes/sig-node-test-failures
/cc @dchen1107 @derekwaynecarr

**Comment by soggiest** [comment]
Any updates on this issue? 

/cc @kubernetes/sig-node-test-failures
/cc @dchen1107 @derekwaynecarr @Random-Liu

**Comment by dims** [comment]
@soggiest the test in question was demoted as part of  #81535 so we don't need to worry about it any more

- https://github.com/kubernetes/kubernetes/commit/79cff6cd1072f28d67730fe4ee50a173086b061e#diff-69f4e58c57b1efcc89f88e6e67005f39

**Comment by alejandrox1** [comment]
Thank you @dims for tracking that one down!
/close
