### ISSUE TITLE
the pvc can not be created

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/kubernetes#74929]
/kind bug

/sig storage
@Saad Ali

**What happened**:
My kubernetes cluster has a default storageclass, and when I use pvc to select an existing pv, this pvc will use the default storageclass to create the pv, instead of using the pv, I specified, which is a bug.

**What you expected to happen**:
You should use an existing pv to create a pvc, instead of using storageclass

**How to reproduce it (as minimally and precisely as possible)**:
Set storageclass as default:
  storageclass.beta.kubernetes.io/is-default-class: "true" 
use existing pv:
  selector:
    matchLabels:
      name: cks-core-repos-pv

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.1
- OS (e.g: `cat /etc/os-release`):ubuntu 16.04

**Comment by mlmhl** [comment]
What's the `StorageClassName` of your PV? The PV controller only binds PVC and PV which have same `StorageClassName`.

**Comment by shigy123456** [comment]
This problem has been resolved by simply shutting down the defaultstorageclass controller with the following configuration：
- --disable-admission-plugins=DefaultStorageClass

@mlmhl  Thank you for your attention.
