### ISSUE TITLE
release-master-blocking/verify-master is failing

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#74921]
**Which jobs are failing**:
* [master-blocking/verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)

**Which test(s) are failing**:
verify.godeps
```
Your vendored results are different:
diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go /tmp/gopath.UfEUr6/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
--- vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go	2019-03-04 21:58:23.139775316 +0000
+++ /tmp/gopath.UfEUr6/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go	2019-03-04 22:00:54.000000000 +0000
# ...
```
verify.staging-godeps
```
Unexpected dirty working directory:

  diff --git a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go b/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  index ef2dfe16aa..90bae839e1 100644
  --- a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  +++ b/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
# ...
```

**Since when has it been failing**:
Last good: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/27209
First bad: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/27210
Lastest bad: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/27213

**Anything else we need to know**:
I initially repurposed https://github.com/kubernetes/kubernetes/issues/74261 for this, but have no changed my mind

I initially thought this was due to the suspect commit range between the last good/first bad: https://github.com/kubernetes/kubernetes/compare/b1d4d4067...8770e0cd3 which caught https://github.com/kubernetes/kubernetes/pull/74664

Now suspect this is due to https://github.com/kubernetes/kubernetes/issues/74903 which allowed https://github.com/kubernetes/kubernetes/pull/74804 to break master

/milestone v1.14
/kind failing-test
/priority critical-urgent
/sig api-machinery

/cc @mariantalla @smourapina @alejandrox1 @mortent @kacole2 

/assign @dims @liggitt @sttts

**Comment by spiffxp** [comment]
Hoping https://github.com/kubernetes/kubernetes/pull/74902 fixes this

**Comment by liggitt** [comment]
job is green again

/close
