### ISSUE TITLE
Scheduler TestPreemptionRaces is flaky

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#74931]
**Which jobs are failing**:
[Presubmit tests](https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration)

**Which test(s) are failing**:
kubernetes/test/integration/scheduler.TestPreemptionRaces

**Since when has it been failing**:
Not exactly known. The flake rate is not high. That's probably why it has not received attention.

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

**Reason for failure**:
Logs are currently unaccessible. Test grid returns an error when clicking on the failed instances.

**Anything else we need to know**:

/sig scheduling
/label help-wanted

**Comment by denkensk** [comment]
@bsalamat  Let me try to fix it.
/assign @denkensk 
/remove-help

**Comment by denkensk** [comment]
Logs in 47435.
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/47435

**Comment by spiffxp** [comment]
This is currently the flakiest test for the flakiest PR job for kubernetes/kubernetes http://velodrome.k8s.io/dashboard/db/bigquery-metrics?panelId=7&fullscreen&orgId=1

**Comment by Huang-Wei** [comment]
I will try to work out a PR if @denkensk is not working on it.

**Comment by denkensk** [comment]
Sure, you can take over it if you want. @Huang-Wei  And It is strange about the flake in `TestPreemptionRaces`.   I ran about 3,000 times on a local machine, but never failed. :joy:   I also can help you to do someting ~

**Comment by Huang-Wei** [comment]
@denkensk Indeed, flaky tests are usually difficult to repro and debug..

A heads-up: I seem to have found the root cause. I'm working on a solution and will raise a PR after thorough testing.

**Comment by liggitt** [comment]
this is still flaking (e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78131/pull-kubernetes-integration/1130565823501438978/)

**Comment by Huang-Wei** [comment]
I will take another look.

**Comment by Huang-Wei** [comment]
There are two additional flakes since the one @liggitt reported on May 20:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1132075182698008578
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1131842499699019779

It's no longer that flaky [than before](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?panelId=7&fullscreen&orgId=1), but the PR I gave earlier proved not to be a thorough solution but mitigation.

I may not be able to continue looking into it in the next couple of weeks. Anyone is in interested, feel free to take it.

**Comment by alejandrox1** [comment]
Last failure was 4 days ago. will continue observing and see if it clears out
/milestone v1.16

**Comment by alejandrox1** [comment]
Been observing this one for a bit and it seems like its getting better https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-integration
Other than some failures a couple days ago it has been stable.
Will keep an eye for a couple more days to make sure.

**Comment by alejandrox1** [comment]
Seems to have stabilized.
/close
