### ISSUE TITLE
Refactor nodeinfomanager tests

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#74930]
**What happened**:
It's difficult to read because the validation is checking every field individually.  It would be simpler if we just passed in an expected CSINode object and compared it to what we get.

Also as a consequence, it's not able to test that we didn't modify existing/unrelated drivers.

@kubernetes/sig-storage-misc 
/kind cleanup

**Comment by mucahitkurt** [comment]
Hey @msau42 , I want to work on this issue.
