### ISSUE TITLE
Kubernetes Pods do not have internet access

### ISSUE THREAD

**Issue by prabhurs123** [kubernetes/kubernetes#74955]
Hi all,

Am setting up a kubernetes cluster with 1 master 2 nodes in locally. Everything is working fine except pods does not have access to internet/local network access, Below are my kubernetes details,

Could you please help me to resolve this issue,
---------------------------------------------------------------------------------------------
below the pods details,

```
[- [root@k8smaster ~]# kubectl get pods --all-namespaces 
- NAMESPACE     NAME                                             READY   STATUS    RESTARTS   AGE
- default       nh-dashboard-d77596b76-8rtcm                     1/1     Running   0          53m
- kube-system   coredns-86c58d9df4-ckb6d                         1/1     Running   2          4m47s
- kube-system   coredns-86c58d9df4-q4pvw                         1/1     Running   2          4m47s
- kube-system   etcd-k8smaster.nanoheal.com                      1/1     Running   0          115m
- kube-system   kube-apiserver-k8smaster.nanoheal.com            1/1     Running   0          115m
- kube-system   kube-controller-manager-k8smaster.nanoheal.com   1/1     Running   0          115m
- kube-system   kube-flannel-ds-amd64-44t4d                      1/1     Running   0          108m
- kube-system   kube-flannel-ds-amd64-5r6xd                      1/1     Running   0          108m
- kube-system   kube-flannel-ds-amd64-rmjbc                      1/1     Running   0          108m
- kube-system   kube-proxy-gsfpd                                 1/1     Running   0          115m
- kube-system   kube-proxy-pd7mw                                 1/1     Running   0          115m
- kube-system   kube-proxy-znbfc                                 1/1     Running   0          116m
- kube-system   kube-scheduler-k8smaster.nanoheal.com            1/1     Running   0          115m](url)
```

----------------------------------------------
Below the k8s master resolv.conf output,
```
[root@k8smaster ~]# cat /etc/resolv.conf
# Generated by NetworkManager
search nanoheal.com
nameserver 103.8.44.5
```

----------------------------------------------
Below the pod resolv.conf output,
```
[root@nh-dashboard-d77596b76-8rtcm:~# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local nanoheal.com
options ndots:5
```

---------------------------------------------------
Below the response from inside the pod, 
```
root@nh-dashboard-d77596b76-8rtcm:/# curl  8.8.8.8
curl: (7) Failed to connect to 8.8.8.8 port 80: Connection timed out
```

---------------------------------------------------

below the srvices details,

```
[root@k8smaster ~]# kubectl get svc --all-namespaces 
NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             ClusterIP   10.96.0.1       <none>        443/TCP         121m
default       nh-dashboard-svc       NodePort    10.98.163.156   <none>        80:30001/TCP    107m
kube-system   kube-dns               ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   120m
kube-system   kubernetes-dashboard   NodePort    10.103.29.149   <none>        443:31187/TCP   90m
```
--------------------------------------------
Below logs from coredns pod,

[ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:35245->103.8.44.5:53: i/o timeout
 [ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:43704->8.8.8.8:53: i/o timeout
 [ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:36364->103.8.44.5:53: i/o timeout
 [ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:46141->103.8.44.5:53: i/o timeout
 [ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:50167->103.8.44.5:53: i/o timeout
 [ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:34083->8.8.8.8:53: i/o timeout
 [ERROR] plugin/errors: 2 5097456227146284065.2749918219024011569. HINFO: unreachable backend: read udp 192.168.1.5:36951->8.8.8.8:53: i/o timeout
E0305 12:13:40.508343       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:318: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0305 12:13:40.509435       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:313: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0305 12:13:40.510471       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout

--------------------------------
below is my coredns config,

```
`apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-05T10:12:19Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "10209"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 28f332b5-3f2f-11e9-9f9a-50af73624a9e
``
```

and coredns is restarting automatically.

Kubernetes version : 1.13.4
Docker version : 1.13.1
OS : CentOS Linux release 7.6.1810
Network : Flannel

Please help me to fix this issue, i have been troubling from past 2 days.

**Comment by xiak** [comment]
10.254.174.10  is my DNS server

1. On the node, run 
nc -vz 10.254.174.10 53
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 10.254.174.10:53.
Ncat: 0 bytes sent, 0 bytes received in 0.25 seconds

2. In the pod, run 
dnstools# nc -vz 10.254.174.10 53
nc: 10.254.174.10 (10.254.174.10:53): Operation timed out

3. Check coredns logs
kubectl logs coredns-86c58d9df4-blp7w -n kube-system
.:53
2019-03-03T23:38:32.684Z [INFO] CoreDNS-1.2.6
2019-03-03T23:38:32.684Z [INFO] linux/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
 [INFO] plugin/reload: Running configuration MD5 = f65c4821c8a9b7b5eb30fa4fbc167769
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:40129->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:37637->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:51373->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:47882->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:49362->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:37377->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:44923->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:53840->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:38645->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 7653725984537222903.4343203491411508124. HINFO: unreachable backend: read udp 10.254.137.66:46853->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 0.0.0.0.in-addr.arpa. PTR: unreachable backend: read udp 10.254.137.66:59750->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 0.0.0.0.in-addr.arpa. PTR: unreachable backend: read udp 10.254.137.66:44060->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 updates.jenkins.io. A: unreachable backend: read udp 10.254.137.66:49548->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 updates.jenkins.io. A: unreachable backend: read udp 10.254.137.66:36287->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 www.google.com. A: unreachable backend: read udp 10.254.137.66:48673->10.254.174.10:53: i/o timeout
 [ERROR] plugin/errors: 2 www.google.com. A: unreachable backend: read udp 10.254.137.66:43727->10.254.174.10:53: i/o timeout

**Comment by xiak** [comment]
@prabhurs123 I have resolved this issue by changing nameserver ip, because my nameserver ip was in the range of CALICO_IPV4POOL_CIDR

**Comment by xiak** [comment]
I checked on my node:

`cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.254.17.10
`
The nameserver ip is 10.254.174.10 which is in the range of pod CIDR, I changed it from 10.254.17.10 to 10.32.10.10, It's OK now
`cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.32.10.10
`

**Comment by prabhurs123** [comment]
Thanks xiak. I have tried but no luck. So i have setup fresh k8s cluster again in different machine and its worked without any issues.

**Comment by thockin** [comment]
@fturib
