### ISSUE TITLE
Pulling kubernetes components images from a private container registry

### ISSUE THREAD

**Issue by Mnbill** [kubernetes/kubernetes#74953]
Hello,

My kubernetes cluster can't reach internet for security reasons, and i am afraid that one of kubernetes components try to pull image from internet.

Is it  possible to push kubernetes components images to a private container registry and after configure kuberntes to pull this images from it ?

If yes what are the advantages and disadvantages of doing this ?

images examples: 
kube-apiserver, kube-scheduler, kube-controller-manager, etcd ..

i am using public container registry:
k8s.gcr.io 

My kubernetes v1.10.1 cluster was installed by kubeadm

/help
/help-wanted
@kubernetes/sig-contributor-experience-help-wanted

Thanks

**Comment by neolit123** [comment]
> Is it possible to push kubernetes components images to a private container registry and after configure kuberntes to pull this images from it ?

yes, just google "docker create private local registry".
you can also pre-pull the images as TAR files and use `docker load` to load them locally.

> My kubernetes v1.10.1 cluster was installed by kubeadm

1.10 is no longer supported, so better upgrade.
1.11 is going outside of the supported version when 1.14 is released - late march.

**Comment by Mnbill** [comment]
Thanks :)

i am using gitlab docker container registry.

in this case how to configure kubeadm to pull images from this private registry when i will upgrade my kubernetes cluster ?

**Comment by neolit123** [comment]
for kubadm 1.13.x try writing this to a file called `config.yaml`
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
imageRepository: "k8s.gcr.io" 
```
replace `k8s.gcr.io` with your registry URL.

then pass this config like so `kubeadm init ..... --config config.yaml`

**Comment by neolit123** [comment]
since this is already supported, i will close this issue.
but please feel free to reply if the above works for you.

/close
