### ISSUE TITLE
kubectl top <resource> is not working with heapster removed

### ISSUE THREAD

**Issue by marcstreeter** [kubernetes/kubernetes#74961]
**What happened**:
installed kubernetes 1.13.2
**What you expected to happen**:
`kubectl top <pod/node>` provides metrics
**How to reproduce it (as minimally and precisely as possible)**:
`kubectl top node`
or
`kubectl top pod`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: baremetal 
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux node1 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubespray
- Others:

**Comment by marcstreeter** [comment]
@kubernetes/sig-cli-bugs

**Comment by WanLinghao** [comment]
Is is designed to be this, `kubectl top` relies on the metrics api provided by heapster

**Comment by marcstreeter** [comment]
Since heapster was removed with `1.13`([source](https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md)), will `kubectl top` start referring to the [metrics server](https://github.com/kubernetes-incubator/metrics-server)?

**Comment by marcstreeter** [comment]
ok, never mind (I'm still combing through my email, I got the answer to this in [another thread](https://github.com/cloudability/metrics-agent/issues/19)). 

> it just now requires that you run either heapster or the metrics-server in your cluster
