### ISSUE TITLE
[Umbrella issue for tracking] gce-cos-<branch>-default is flaky

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74960]
**Which jobs are flaking**:
* `gce-cos-master-default` (a.k.a. `ci-kubernetes-e2e-gci-gce`)
* `gce-cos-1.14-default` (a.k.a. `ci-kubernetes-e2e-gce-cos-k8sbeta-default`)

**Which test(s) are failing**:
A variety of tests, owned by different SIGs (see more detailed issues per SIG below).
The jobs are release blocking; it's currently flaking about 80% and 85% of the time respectively, which makes it impossible to get CI signal from them in an automated way.

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default
* https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default

**More detailed breakdown**
_still being populated_
* ~https://github.com/kubernetes/kubernetes/issues/74968~ https://github.com/kubernetes/kubernetes/issues/74745
* https://github.com/kubernetes/kubernetes/issues/74978
* https://github.com/kubernetes/kubernetes/issues/74984

**Related**
* https://github.com/kubernetes/kubernetes/issues/71383

/area deflake

**Comment by spiffxp** [comment]
triage clusters for gce-cos-master-default: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce%24

**Comment by spiffxp** [comment]
triage clusters for gce-cos-master-1.14: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-cos-k8sbeta-default%24

(this may be more fruitful to look at from a flake perspective, because the underlying commit is only changing on a daily basis)

**Comment by spiffxp** [comment]
/priority critical-urgent
We're not going to be able to cut a release with this level of flakiness, since it's not clear that this is one underlying culprit, this needs some sustained attention

**Comment by alejandrox1** [comment]
Related issue:
* #74699 [Failing Test] node leases tests failing in release-1.14-all:gke-cos-1.14-default

**Comment by mariantalla** [comment]
Just to clarify on `/milestone`:
* for discovery purposes; makes sense, this work is very relevant to 1.14, and includes issue that are targetted for this release.
* for completion purposes; there's a good chance that this umbrella issue won't be "finished" by 1.14, and will likely be relevant to future releases. I think that's still ok - did you think the same @spiffxp ?

**Comment by mariantalla** [comment]
Update on flake-rate-over-the-last-week:
* 44% for master-default
* 62% for 1.14-default

**Comment by spiffxp** [comment]
@mariantalla our ability to cut a release when we want to is impacted by this issue, agree this should remain milestoned to v1.14 until we cut v1.14.0

**Comment by liggitt** [comment]
sweeping issues marked critical-urgent... the linked testgrid appears green. can this be closed?

**Comment by spiffxp** [comment]
/close
agree this no longer seems critical-urgent, flake rates are well under the rates mentioned in description, and lower than rates mentioned mar 14

for posterity, testgrid.k8s.io currently says:

>gce-cos-master-default: FLAKY
>257 of 170772 tests (0.2%) and 79 of 228 runs (34.6%) failed in the past 7 days

>gce-cos-k8sstable1-default: FLAKY
>165 of 64574 tests (0.3%) and 40 of 83 runs (48.2%) failed in the past 7 days
