### ISSUE TITLE
getCSISourceFromSpec uses api.XXX type

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#74973]
function `getCSISourceFromSpec` in csi_util.go should use v1 and not api.xxx types.

/sig storage

cc @vladimirvivien

**Comment by vladimirvivien** [comment]
@gnufied while the package identifier is `api` the package itself resolves to `v1` of core:

https://github.com/kubernetes/kubernetes/blob/a352b74bcca9de2acd1600e47ea7f122ac8c1fe1/pkg/volume/csi/csi_util.go#L26
