### ISSUE TITLE
[Flaky tests] [sig-storage] CSI volumes subpath tests for readonly volumes are flaking in gce-cos-master-default, gce-cos-1.14-default

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#74978]
**Which jobs are failing**:
_w/ testgrid links_
* [`gce-cos-master-default`](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default) (a.k.a. `ci-kubernetes-e2e-gci-gce`)
* [`gce-cos-1.14-default`](https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default) (a.k.a. `ci-kubernetes-e2e-gce-cos-k8sbeta-default`)

These jobs are release-blocking; at the moment of writing this, they're flaking ~70%-80% of the time (not solely because of these tests), making it really hard to extract CI signal and make release blocking decisions based on them.

**Which test(s) are failing**:
_The following numbers are estimated from ~ the last 2 weeks' worth of builds_

| test | # failures in `gce-cos-master-default` | % failures in `gce-cos-master-default` | # failures in `gce-cos-1.14-default` | % failures in `gce-cos-1.14-default` |
|---|---|---|---|---|
`[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should verify container cannot write to subpath readonly volumes` | 29 | 6.58% | 23 | 6.99%
`[sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should verify container cannot write to subpath readonly volumes` | 44 | 9.98% | 27 | 8.21%

* Though the individual test flake rates are low compared to that of the job they're part of, `[sig-storage] CSI Volumes .* subPath should verify container cannot write to subpath readonly volumes` tests:
  * flaked 15% of the time, contributing to about 22% of flakes in `ci-kubernetes-e2e-gci-gce`
  * flaked about 14% of the time, contributing to about 21% of flakes in `ci-kubernetes-e2e-gce-cos-k8sbeta-default`

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:375
while waiting for subpath failure
Expected error:
    <*errors.errorString | 0xc000ad1dc0>: {
        s: "subpath container unexpectedly became running",
    }
    subpath container unexpectedly became running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:714
```

**Main questions**
* What can be done to stabilize these tests?
* Is there a chance that flakes in these tests hint at any instability in the code they cover? Some examples could be race conditions, operations that need retries etc.

**Bonus question**
* How much of what's covered in these e2e tests is covered elsewhere (unit tests/presubmits etc.)? Hypothetically speaking, which (if any) tests could be _safely_ removed from these jobs without losing coverage?

**Anything else we need to know**:
* Part of https://github.com/kubernetes/kubernetes/issues/74960
* Triage links for up-to-date stats on flakiness of these tests
  * [master](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce%24&test=%20should%20verify%20container%20cannot%20write%20to%20subpath%20readonly%20volumes)
  * [1.14](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-cos-k8sbeta-default%24&test=%20should%20verify%20container%20cannot%20write%20to%20subpath%20readonly%20volumes)

cc @smourapina @alejandrox1 @kacole2 @mortent 

/kind flake
/sig storage
/priority important-soon
/area deflake

**Comment by msau42** [comment]
/assign
Taking a look here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35450
The container was able to successfully write even though the volume should have been set to read only.  I have not found any suspicious test issues so far.  Will add some more debugging and try to repro on my own cluster.

@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
I am able to repro the failure on my local cluster.  So far I have verified that we do pass readOnly = true to CRI:
```
Mar 06 00:35:36 e2e-test-msau-minion-group-dvrh kubelet[1639]: I0306 00:35:36.071233    1639 kubelet_pods.go:259] MSAU pod "pod-subpath-test-csi-hostpath-dynamicpv-jkpm_provisioning-3391(c123fab9-3fa7-11e9-997c-42010a800002)" container "test-container-subpath-csi-hostpath-dynamicpv-jkpm" mount "test-volume" readonly %!q(bool=true)
```

**Comment by msau42** [comment]
Ok after dumping out container logs, I see that the container actually failed writing due to readOnly:
```
Mar  5 17:35:18.473: INFO: MSAU pod "pod-subpath-test-csi-hostpath-dynamicpv-r6fw" container "test-container-subpath-csi-hostpath-dynamicpv-r6fw" logs:
error writing new file "/test-volume/provisioning-8451": open /test-volume/provisioning-8451: read-only file system
error from Stat("/test-volume/provisioning-8451"): stat /test-volume/provisioning-8451: no such file or directory

```

However, the Pod still container status still became Running

**Comment by msau42** [comment]
Ok the test assumption is wrong.  The container can be temporarily running before it fails.  Working on a test fix

**Comment by msau42** [comment]
#75011 out for review

**Comment by msau42** [comment]
PR has merged. Will monitor for flakiness

**Comment by msau42** [comment]
There have been no flakes on master since #75011 merged
/close

**Comment by msau42** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce%24&test=subPath%20should%20verify%20container%20cannot%20write%20to%20subpath%20readonly%20volumes

**Comment by spiffxp** [comment]
(from the triage link above)
<img width="1097" alt="Screen Shot 2019-03-16 at 11 15 07 AM" src="https://user-images.githubusercontent.com/49258/54479692-c5e4e380-47dc-11e9-9c11-0f63ae3925c7.png">
calling this resolved
