### ISSUE TITLE
kubernetes can be install on the CentOS6.X or no public network of local environment

### ISSUE THREAD

**Issue by chaubeau** [kubernetes/kubernetes#7497]
kubernetes can be install on the CentOS6.X or no public network of local environment？

**Comment by cjcullen** [comment]
Thanks for the issue.

Does [Getting Started on CoreOS](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos.md) answer any of your questions?

**Comment by erictune** [comment]
I think the question was about CentOS not CoreOS.

The only guide we have for CentOS is
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/centos/centos_manual_config.md

It does not appear to support real networking (only works on one node).
It does not say which CentOS version it uses.

@coolsvap added that guide, so maybe he can answer.

**Comment by roberthbailey** [comment]
I'm going to close this as obsolete since it hasn't been updated in over two years.
