### ISSUE TITLE
Test artifacts not always gathered from Windows nodes on GCE

### ISSUE THREAD

**Issue by pjh** [kubernetes/kubernetes#74992]
At the end of an e2e test run for Windows clusters on GCE (https://testgrid.k8s.io/sig-windows#gce-windows-master&width=20) we expect several log files to be gathered from the Windows nodes: `docker.log`, `kube-proxy.log`, `kubelet.log`, `serial-1.log`. However, sometimes only `serial-1.log` is being gathered.

Example of what we expect: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/224/artifacts/e2e-224-36623-windows-node-group-7l93/

Example of the problem: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/226/artifacts/e2e-226-36623-windows-node-group-595q/

For these two example runs I also see differences in the logs collected from the Linux master; I haven't checked other runs yet to see if this happens consistently when we see the problem with Windows nodes.

https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/224/artifacts/e2e-224-36623-master/
vs. 
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/226/artifacts/e2e-226-36623-master/

The logs collected from the Linux worker nodes are the same for both runs.

**Comment by pjh** [comment]
cc @yujuhong @mtaufen @jingxu97

**Comment by pjh** [comment]
This is not release-blocking for 1.14.

**Comment by yujuhong** [comment]
Only serial logs don't depend on SSH. Looks like we have problems scp'ing the logs.
```
scp: /var/log/startupscript.log*: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Permission denied (publickey,keyboard-interactive).
```

**Comment by pjh** [comment]
/remove-lifecycle stale

I believe this is still happening, unfortunately we haven't had time to investigate further.

cc @YangLu1031
