### ISSUE TITLE
Stats performance is slow on Windows

### ISSUE THREAD

**Issue by benmoss** [kubernetes/kubernetes#74991]
**What happened**:
When looking at the changes made in #74933 I did a quick benchmark of the `/stats/summary` endpoints on both Linux and Windows nodes. Not very scientific, but: 

Linux:
```
$ siege -r 50 -c10 10.74.41.135:10255/stats/summary
** SIEGE 4.0.4
** Preparing 10 concurrent users for battle.
The server is now under siege...
Transactions:                    500 hits
Availability:                 100.00 %
Elapsed time:                   5.88 secs
Data transferred:               7.68 MB
Response time:                  0.11 secs
Transaction rate:              85.03 trans/sec
Throughput:                     1.31 MB/sec
Concurrency:                    9.10
Successful transactions:         500
Failed transactions:               0
Longest transaction:            1.16
Shortest transaction:           0.09
```

Windows:
```
$ siege -r 50 -c10 10.74.41.136:10255/stats/summary
** SIEGE 4.0.4
** Preparing 10 concurrent users for battle.
The server is now under siege...
Transactions:                    500 hits
Availability:                 100.00 %
Elapsed time:                 100.14 secs
Data transferred:               1.36 MB
Response time:                  2.00 secs
Transaction rate:               4.99 trans/sec
Throughput:                     0.01 MB/sec
Concurrency:                   10.00
Successful transactions:         500
Failed transactions:               0
Longest transaction:            2.04
Shortest transaction:           1.25
```

**What you expected to happen**:
Roughly similar, especially since I believe the implementation is such that stats aren't calculated every time the endpoint is hit.

**Environment**:
- Kubernetes version (use `kubectl version`): 43616fc920c195a6f892397d4b9b3f53c7aae1fa
- Cloud provider or hardware configuration: vSphere
- Docker as CRI

**Comment by benmoss** [comment]
cc @yujuhong

**Comment by yujuhong** [comment]
This could become an issue for kubelet in the future, especially because kubelet doesn't have throttling AFAIK (and I'm don't think client-side has rate-limiting).
/cc @haiyanmeng, who's looking into kubelet server-side throttling

**Comment by haiyanmeng** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/75060 to track the effort of "Add monitoring and throttling into kubelet http server".

**Comment by tianyuansun** [comment]
any update ? maybe i can help to fix this issue

**Comment by michmike** [comment]
@tianyuansun we welcome any and all help in this area. you can sync with @benmoss offline and see if you can help us fix this.

**Comment by tianyuansun** [comment]
![image](https://user-images.githubusercontent.com/31433937/65812056-81f38200-e1f4-11e9-892b-d8c871549849.png)

OK @michmike . above is my test result, kubelet v1.13.4, windows vs linux. only two pods on each node, with many cpu and mem available.

**Comment by pjh** [comment]
cc @Random-Liu @yliaog 

@Random-Liu did some investigation here and I believe found that docker is the bottleneck here, and that with containerd the stats performance is much faster.

**Comment by marosset** [comment]
I tracked the down to this dockershim call to ContainerStats https://github.com/kubernetes/kubernetes/blob/15c3f1b119ff4b4073c86df05c819a9672b80d68/pkg/kubelet/dockershim/docker_stats_windows.go#L34 taking ~2 seconds per container on a system with low cpu utilization.

This gets called as part of ListContainerStats https://github.com/kubernetes/kubernetes/blob/15c3f1b119ff4b4073c86df05c819a9672b80d68/pkg/kubelet/dockershim/docker_stats.go#L35 every time /stats/summary or /metrics endpoints are hit.

There is a metric in the instrumented dockershim client to measure the latency of calls but it only measures latency for each individual ContainerStats call - it does not measure how long it takes to get stats for all containers 
https://github.com/kubernetes/kubernetes/blob/15c3f1b119ff4b4073c86df05c819a9672b80d68/pkg/kubelet/dockershim/libdocker/instrumented_client.go#L265-L272

I set up kube-promethues and after updating the scrape timeout (so I can actually collect metrics) i'm seeing this one call take several orders of magnitude more time vs other docker calls

![image](https://user-images.githubusercontent.com/18291632/73288658-3d7eef80-41b0-11ea-9e9c-e60355a7dc6c.png)
(metrics are measured in microseconds)

If we want to address this for docker I think we can probably introduce some in-memory caching in or around
https://github.com/kubernetes/kubernetes/blob/15c3f1b119ff4b4073c86df05c819a9672b80d68/pkg/kubelet/dockershim/docker_stats_windows.go#L28

**Comment by marosset** [comment]
I will check if we can get the same metrics quicker through hcsshim (and that we have enough information to do so where these calls are being made) and if there is a way to batch the ContainerStats call to the docker api.
Either one of these may bring latency down to an acceptable level without needing to introduce caching.

**Comment by marosset** [comment]
Delays in the ConstainerStats calls were investigated and more details can be found in this Moby Issue.
https://github.com/moby/moby/issues/40437

I tried replacing calls to the docker api to get container stats with calls to hcsshin and greatly sped up calls to /stats/summary.
Since it looks like the delay is fixed and backed into ConstainerStats call another option could be to parallelize the calls to ContainerStats.

I'm writing some e2e tests to validate whatever approach we decide to take to resolve this issue.

**Comment by cpuguy83** [comment]
I've opened https://github.com/moby/moby/pull/40478 to address this in moby.

Sadly I do not think we can make a backport for this change since it is an API change, but open to suggestions.

**Comment by cpuguy83** [comment]
And one more PR: https://github.com/moby/moby/pull/40481 which should be backport-able, which reduces stat collection time from ~1.8s to ~1s

**Comment by PatrickLang** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/87730

If you have another case where this is slow on 1.18, please open up a new issue and let us know which api calls are slowing down.

/close
