### ISSUE TITLE
investigate if Windows suffers from reduced precision in CRI timestamps

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#74999]
pre-1.14, when testing on Windows nodes, there were instances where we were seeing timestamps very close to each other in `pkg/kubelet/stats/cri_stats_provider.go` (`criStatsProvider`)

the zero or negative value case should now be resolved by:
https://github.com/kubernetes/kubernetes/pull/74933

but Windows does not have nanosecond precision timers - highest precision timestamp are microseconds. we should double check if this causes problems in the future.

also see discussions in:
https://github.com/kubernetes/kubernetes/pull/74676#discussion_r261464301
^ thread has some notes on how Windows timers work in Go.
https://github.com/kubernetes/kubernetes/pull/74676
https://github.com/kubernetes/kubernetes/issues/74667

/sig windows
cc @yujuhong @adelina-t @PatrickLang  

this is out of scope for the 1.14 release.
/kind design
/priority backlog

**Comment by yujuhong** [comment]
Thanks for filing the issue!

/cc @pjh @mtaufen FYI
