### ISSUE TITLE
Podgc: probably should sort by pod finished time instead of create time?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#75017]
**What happened**:
https://github.com/kubernetes/test-infra/issues/11594

**What you expected to happen**:
Pods that finished earliest will get gc'd, not the pod started earliest... (but seems there's no exposed finished timestamp?)

cc @mm4tt @cjwagner @stevekuznetsov @spiffxp @mikedanese

**Comment by mikedanese** [comment]
We should greatly increase the podgc controller threshold or just remove it now that we have BackoffLimit and the API server/etcd has had significant work done.

https://github.com/kubernetes/kubernetes/blob/9f85c5c4b56940f88cb854615efad4e9f0c66f20/staging/src/k8s.io/api/batch/v1/types.go#L88

cc @caesarxuchao @lavalamp
