### ISSUE TITLE
Create e2e test case coverage for admit pod by sorted order.

### ISSUE THREAD

**Issue by pontiyaraja** [kubernetes/kubernetes#75022]
**What happened**:
Create e2e test case coverage for admit pod by sorted order. 
from the PR #71786  the sorting is required to avoid failing of pod admit for the test cases of pod port conflict and pod memory exceed. 
creating this issue from the comment [discussion_r261439500](https://github.com/kubernetes/kubernetes/pull/71786#discussion_r261439500).
**What you expected to happen**: 
If the port conflicted pods are admitted without sorting, it should fail to match the expected pod phase.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by pontiyaraja** [comment]
facing some blocks, ref : [https://groups.google.com/forum/#!topic/kubernetes-sig-node/9e93aO0D2C8](https://groups.google.com/forum/#!topic/kubernetes-sig-node/9e93aO0D2C8)

**Comment by timothysc** [comment]
closing.
