### ISSUE TITLE
Failing e2e test: stateful upgrade should maintain a functioning cluster

### ISSUE THREAD

**Issue by schrodit** [kubernetes/kubernetes#75034]
**Which jobs are failing**:
N/A
**Which test(s) are failing**:
[sig-apps] [sig-apps] stateful Upgrade [Feature:StatefulUpgrade] [k8s.io] stateful upgrade should maintain a functioning cluster

[Test Source](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/upgrades/etcd.go#L83)

**Since when has it been failing**:
Tested for 2 months

**Testgrid link**:
Test is not executed in testgrid
**Reason for failure**:
Test failing because of missing etcd service. Probably because service is not deployed with the test server ([file](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/statefulset/etcd/tester.yaml)) as it is with other statefulset tests ([cassandra stateful test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/statefulset/cassandra/tester.yaml)).

In addition it seems that the used image `k8s.gcr.io/cassandra-e2e-test:0.1` does not exist.
**Anything else we need to know**:

**Comment by kow3ns** [comment]
/assign @mml 
Matt I believe you helped with these upgrade tests for StatefulSet during the initial implementation phase. Do you have the context on what happened here?

**Comment by mml** [comment]
I'm not sure why the images disappeared, but we did have a long conversation at the time about where the source code to the images should be stored.  I think mine is actually still in a git repo on my workstation.  :fearful: @maisem do you happen to have the one you wrote?

**Comment by schrodit** [comment]
@mml any update on this?
