### ISSUE TITLE
Kubernetes Windows Containers - WIndows 2016 Build Version

### ISSUE THREAD

**Issue by johnyandrapati** [kubernetes/kubernetes#75033]
/sig windows

**Comment by johnyandrapati** [comment]
Hi we have Windows 2016 build version 1607, but have all the latest patches and also service packages installed (which I believe will take it up to 1809).

Although the build version still says 1607, I wanted to find out, if this is good enough for us to progress with addingnwindows nodes inside an existing kubernetes cluster and that we will have no issues.

Or should we upgrade to Windows 2016 build versions 1709 or 1809 regardless?

**Comment by guhuajun** [comment]
If it s possible, use Windows Server 2019 instead.
