### ISSUE TITLE
Windows EmptyDir volumes are not created with 0777

### ISSUE THREAD

**Issue by benmoss** [kubernetes/kubernetes#75049]
**What happened**:
Running a Windows pod with an EmptyDir volume attached should allow a non-Administrator user to read, write, and execute files inside that directory. Instead, it appears that this currently only works if the host's filesystem has ACLs set on a parent directory that set these permissions on all subdirectories. Basically the equivalent of setting 0777 on all of `/var/lib/kubelet` or something like that.

**What you expected to happen**:
EmptyDir directories should be created with 0777 permissions, just like on Linux.

**How to reproduce it (as minimally and precisely as possible)**:
- On a Windows host where `BUILTIN\Users` do not have write permission over `/var/lib/kubelet/`, run this spec: https://gist.github.com/benmoss/cfea81267982d5d17c4c7ed2a58bf541
- See that the `touch /cache/foo` line does not emit `touch: /cache/foo: Permission denied` in the logs

/sig windows

**Comment by benmoss** [comment]
Relevant context:
- https://github.com/kubernetes/kubernetes/commit/5394aa979f195a7b480ca0f46d996f6fe05910e2 
- https://github.com/kubernetes-sigs/windows-testing/pull/35

**Comment by benmoss** [comment]
Seems like at least part of the problem is that `Mkdir` on Windows ignores the file mode, since Windows permissions are a bit different: https://github.com/golang/sys/blob/70f52985063808f21fd6dd197895cdb9729443a5/windows/syscall_windows.go#L433-L439

**Comment by yujuhong** [comment]
> Seems like at least part of the problem is that `Mkdir` on Windows ignores the file mode, since Windows permissions are a bit different: https://github.com/golang/sys/blob/70f52985063808f21fd6dd197895cdb9729443a5/windows/syscall_windows.go#L433-L439

:-(

Ref: code to set permission to 777 in emptydir https://github.com/kubernetes/kubernetes/blob/47063891dd782835170f500a83f37cc98c3c1013/pkg/volume/emptydir/empty_dir.go#L41

/cc @jingxu97, who ran into similar problems writing tests.

**Comment by benmoss** [comment]
Started looking at this today, it's more difficult than I imagined. What I mean by "are not created with 0777" is that on Linux `0777` means all users have read/write/execute access. The code in https://github.com/kubernetes/kubernetes/blob/f8024ab087b321190a3bdcd29e0d22ef7cbb4b45/pkg/volume/emptydir/empty_dir.go#L326-L361 is running on Windows and isn't erroring, but the problem is that Go's attempt to map Unix permissions to Windows ends up not really matching the intention of this code.

I don't know that there is a super straightforward way to translate something like 0777 to Windows, except maybe putting ACLs on the directory giving `BUILTIN\Users` the `windows.GENERIC_ALL` permission.

**Comment by yujuhong** [comment]
> I don't know that there is a super straightforward way to translate something like 0777 to Windows, except maybe putting ACLs on the directory giving `BUILTIN\Users` the `windows.GENERIC_ALL` permission.

This is what was done in the stackoverflow answer: https://stackoverflow.com/questions/33445727/how-to-control-file-access-in-windows

**Comment by jingxu97** [comment]
cc @andyzhangx 

Could we fix this issue this the package mentioned by @yujuhong? https://github.com/hectane/go-acl

**Comment by yujuhong** [comment]
@benmoss @PatrickLang do you know of a better way to handle this, or would we have to change the ACLs as the comments above suggest?

**Comment by benmoss** [comment]
I think we would have to use ACLs. I ultimately added these lines just to make these tests pass: https://github.com/cloudfoundry-incubator/kubo-release-windows/blob/0831c11effeafb16f56e347daa229adb10757eeb/jobs/kubelet-windows/templates/bin/kubelet_ctl.ps1.erb#L133-L138

**Comment by liyanhui1228** [comment]
Tried reproducing this by deploying that pod using the yaml file, and this seems like already been fixed in someway. We could mark this as fixed if it cannot be reproduced any more. cc @yujuhong 

```
Path Owner                       Access
---- -----                       ------
C:\  NT SERVICE\TrustedInstaller CREATOR OWNER Allow  268435456
                                NT AUTHORITY\SYSTEM Allow  FullControl
                                BUILTIN\Administrators Allow  FullControl
                                BUILTIN\Users Allow  AppendData
                                BUILTIN\Users Allow  CreateFiles
                                BUILTIN\Users Allow  ReadAndExecute, Synchronize
```

```
PS C:\busybox> get-acl /cache | format-table -wrap

Path  Owner                  Access
----  -----                  ------
cache BUILTIN\Administrators NT AUTHORITY\SYSTEM Allow  FullControl
                             BUILTIN\Administrators Allow  FullControl
                             BUILTIN\Users Allow  ReadAndExecute, Synchronize
                             BUILTIN\Users Allow  AppendData
                             BUILTIN\Users Allow  CreateFiles
                             CREATOR OWNER Allow  268435456
```

**Comment by yujuhong** [comment]
@benmoss could you still reproduce the issue?

**Comment by benmoss** [comment]
No, I'm not sure this is still an issue
/close
