### ISSUE TITLE
[Failing test] [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75045]
**Which jobs are failing**:
`ci-kubernetes-e2e-gce-master-new-downgrade-cluster` in [sig-release-master-upgrade#gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster)

**Which test(s) are failing**:
`[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down`

**Since when has it been failing**:
* 2019-03-04, since [build 1298](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/1298)
* [commit diff](https://github.com/kubernetes/kubernetes/compare/1f6ea0455...3b4a9e4e7
) since last successful run

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:317
Expected grep stdout to be empty (i.e. no mount found).
Expected
    <string>: /dev/sdb on /var/lib/kubelet/pods/9ad53159-3eb2-11e9-9e86-42010a8a0009/volumes/kubernetes.io~csi/pvc-95d18973-3eb2-11e9-9e86-42010a8a0009/mount type ext4 (rw,relatime,data=ordered)
    /dev/sdb on /var/lib/kubelet/pods/9ad53159-3eb2-11e9-9e86-42010a8a0009/volumes/kubernetes.io~csi/pvc-95d18973-3eb2-11e9-9e86-42010a8a0009/mount type ext4 (rw,relatime,data=ordered)
    /dev/sdb on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/9ad53159-3eb2-11e9-9e86-42010a8a0009/volumes/kubernetes.io~csi/pvc-95d18973-3eb2-11e9-9e86-42010a8a0009/mount type ext4 (rw,relatime,data=ordered)
    /dev/sdb on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/9ad53159-3eb2-11e9-9e86-42010a8a0009/volumes/kubernetes.io~csi/pvc-95d18973-3eb2-11e9-9e86-42010a8a0009/mount type ext4 (rw,relatime,data=ordered)
    
to be empty
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:255
```

**Anything else we need to know**:
* This test fails on this job about half of the time: ([triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-master-new-downgrade-cluster%24&test=pd.csi.storage.gke.io%5D#9ec7396aaa70fcc48a7a)), so this could be a flake. Assigning `important-soon` unless we learn otherwise.

/kind failing-test
/sig storage
/priority important-soon
/milestone v1.14

@kubernetes/sig-storage-test-failures 
cc @smourapina @alejandroEsc @kacole2 @mortent

**Comment by msau42** [comment]
This is probably the same issue as https://github.com/kubernetes/kubernetes/issues/72500. The same test case is flaking on regular master serial jobs

**Comment by mariantalla** [comment]
This is still flaking quite heavily, even after #72500 was closed. Could it be prioritized please @msau42 ?

**Comment by msau42** [comment]
@mariantalla I took a quick look at the logs, and it looks like upgrading the nodes to master failed, so the tests afterwards ran against 1.13, which does not have this fix.

I would focus efforts on triaging why the upgrade from 1.13 to 1.15 failed first.

**Comment by msau42** [comment]
This is probably similar to the failed cluster upgrade in https://github.com/kubernetes/kubernetes/issues/74890

**Comment by msau42** [comment]
/remove-sig storage
/sig cluster-lifecycle
cc @justinsb

**Comment by spiffxp** [comment]
I believe this to be unrelated to the go 1.12 issue that was preventing upgrades.  It doesn't immediately appear as though go 1.12.1 is helping here.  I also can't really tell whether the introduction of go 1.12 made things notably worse (after other causes of flakes were fixed)

At this point I'm sortof lumping all of the subpath flakes together in my head, but I'm not sure that's fair.

eg: the flakes for the top failure cluster for this particular are happening in non-upgrade jobs as well
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-03-16&job=gce&test=subPath%20should%20unmount%20if%20pod%20is%20force%20deleted%20while%20kubelet%20is%20down
<img width="1099" alt="Screen Shot 2019-03-16 at 1 20 54 PM" src="https://user-images.githubusercontent.com/49258/54481164-6e4f7380-47ee-11e9-8f9a-955224681d63.png">
<img width="618" alt="Screen Shot 2019-03-16 at 1 21 07 PM" src="https://user-images.githubusercontent.com/49258/54481170-74455480-47ee-11e9-9483-1509461f75f3.png">

**Comment by msau42** [comment]
The most recent flakes are on test jobs where the node versions are 1.13, where the fix has not been cherry picked yet.  All flakes on jobs that test against master should be fixed by now.

There are 3 different bugs open for this test case that are all open due to waiting for 1.13 cherrypick.  Can we consolidate them all?

**Comment by alejandrox1** [comment]
Tests have been reorganized. Will open a new issues if this test failure appears again.
/close
