### ISSUE TITLE
Finish cleaning up self-set node labels

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#75050]
xref https://github.com/kubernetes/kubernetes/pull/74424

In 1.16:
* change the metadata-proxy addon to use `cloud.google.com/metadata-proxy-ready`
* change the kube-proxy addon to use `node.kubernetes.io/kube-proxy-ds-ready`
* change the masq-agent addon to use `node.kubernetes.io/masq-agent-ds-ready`
* stop setting `beta.kubernetes.io/fluentd-ds-ready`, `beta.kubernetes.io/kube-proxy-ds-ready`, and `beta.kubernetes.io/masq-agent-ds-ready` in kube-up `--node-labels`

**Comment by paivagustavo** [comment]
Hey @liggitt, I'm trying to start to contribute to kubernetes and this seem to be an easy task. Can I help with this one?
