### ISSUE TITLE
Flaky test - Emptydir share volume tests failing

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#75068]
Looks like Emptydir shared volume tests are flaking:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35493 and

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/7362

/sig storage
/assign

**Comment by liggitt** [comment]
looks like the test has been flaky since it was introduced:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-02-21&test=pod%20should%20support%20shared%20volumes%20between%20containers

**Comment by gnufied** [comment]
yeah:

```
06 21:04:53.513] Mar  6 21:04:34.759: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.227.176.104 --kubeconfig=/workspace/.kube/config exec pod-sharedvolume-6b9b99a1-4053-11e9-8257-0e513abef885 -c busybox-main-container --namespace=emptydir-2553 -- cat /usr/share/volumeshare/shareddata.txt'
I0306 21:04:53.513] Mar  6 21:04:37.566: INFO: rc: 126
I0306 21:04:53.513] Mar  6 21:04:37.566: INFO: Unexpected error occurred: error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://35.227.176.104 --kubeconfig=/workspace/.kube/config exec pod-sharedvolume-6b9b99a1-4053-11e9-8257-0e513abef885 -c busybox-main-container --namespace=emptydir-2553 -- cat /usr/share/volumeshare/shareddata.txt] []  <nil> rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
I0306 21:04:53.513] 
I0306 21:04:53.513]  command terminated with exit code 126
I0306 21:04:53.513]  [] <nil> 0xc001503500 exit status 126 <nil> <nil> true [0xc001c287c0 0xc001c287d8 0xc001c287f0] [0xc001c287c0 0xc001c287d8 0xc001c287f0] [0xc001c287d0 0xc001c287e8] [0x998710 0x998710] 0xc0027554a0 <nil>}:
I0306 21:04:53.513] Command stdout:
I0306 21:04:53.514] rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
I0306 21:04:53.514] 
```

**Comment by liggitt** [comment]
it looks like the main container is only set up to stay alive for 10 seconds... that should be way longer (and set TerminationGracePeriodSeconds short so the pod dies as soon as it is asked to)

**Comment by gnufied** [comment]
yeah. I am thinking 1 minute should suffice for the test and then set TerminationGracePeriodSeconds to 10s or something.

**Comment by gnufied** [comment]
or we could busywait forever and just have the pod killed.

**Comment by liggitt** [comment]
wait forever and TerminationGracePeriodSeconds of 0 sounds good

**Comment by spiffxp** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gce&test=EmptyDir.*shared
<img width="1098" alt="Screen Shot 2019-03-16 at 11 29 20 AM" src="https://user-images.githubusercontent.com/49258/54479855-c8483d00-47de-11e9-9a78-193db7a25a93.png">

calling this done
