### ISSUE TITLE
Tests are not using architecture-specific image names

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#75076]
/sig testing
/kind bug

we stopped pushing the legacy amd64 workaround (ref https://github.com/kubernetes/kubernetes/pull/44910#discussion_r121637373 and https://github.com/kubernetes/kubernetes/pull/44910/commits/19ca6ca9f2cbb0056766e46a6a0c69c40d990287#diff-4e7d90a055e3d5d5176b4d72daa9a0d4L90), which means every new image in gcr comes with a `-${arch}` suffix: https://github.com/kubernetes/kubernetes/blob/9eebfe7a04e59668adf31bafbaa38db56527dda8/test/images/image-util.sh#L124-L126
however (at least some) [tests](https://github.com/kubernetes/kubernetes/blob/9eebfe7a04e59668adf31bafbaa38db56527dda8/test/utils/image/manifest.go#L193-L197) are still using image names with no `-${arch}` suffix, e.g. https://github.com/kubernetes/kubernetes/pull/74763:
```
I0301 17:55:49.396] E0301 17:54:57.361864   11948 webhook.go:350] >>>>> image being used: gcr.io/kubernetes-e2e-test-images/webhook:1.14v1
```
I ended up manually pushing the amd64 workaround to make change for e2e tests.

not sure the scope of tests affected. Can start with updating the [image retrieve method](https://github.com/kubernetes/kubernetes/blob/9eebfe7a04e59668adf31bafbaa38db56527dda8/test/utils/image/manifest.go#L254-L262) to use amd64 arch and making sure the arch-specific images have been pushed

**Comment by mkumatag** [comment]
As per https://github.com/kubernetes/kubernetes/pull/75078#issuecomment-470425059 this is not really needed.

/close
