### ISSUE TITLE
Implement test/soak as an e2e, just to prevent bitrot.

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#7507]
Separated from #3139

**Comment by davidopp** [comment]
@satnam6502 @roberthbailey @jayunit100

**Comment by piosz** [comment]
Assigning Satnam to this according to what @saad-ali wrote in mail.

**Comment by bprashanth** [comment]
Would be nice if this ran for days and monitored memory footprint to avoid issues like https://github.com/GoogleCloudPlatform/kubernetes/pull/9584

**Comment by satnam6502** [comment]
I plan to delete my manual soak tests because I expect nobody else will find them useful after I leave. After deletion I will close this issue.

**Comment by satnam6502** [comment]
Un-assigning myself since I am leaving Google and Kubernetes.
