### ISSUE TITLE
Enable node e2e tests on Windows

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#75085]
**What would you like to be added**:

Currently there is no node e2e tests for Windows. Since the Windows features in kubernetes are going to GA, it is important to set up the job on PRs, to prevent build failure and reggressions for Windows.

**Why is this needed**:

node e2e tests are essential for Windows containers. We should probably add it after GA (e.g. v1.15).

/sig windows
/assign @PatrickLang

**Comment by PatrickLang** [comment]
Just to clarify - we're running a subset of conformance today but not the whole node e2e maintained by SIG-Node. We can work on adding some of those as needed for v1.15 and later. Getting the summary API covered (see #74788) should be the first target.
