### ISSUE TITLE
Implement loadgenerator k8petstore e2e test

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#7508]
Output perf data to a local file that can be regression checked in any CI.

Separated from #3139

**Comment by jayunit100** [comment]
cc @timothysc here's what im working on now :)

**Comment by davidopp** [comment]
@satnam6502 @roberthbailey

**Comment by jayunit100** [comment]
PR is here, post 1.0 #8145 . I'm ok closing this issue, as the PR is enough
