### ISSUE TITLE
allow hpa with unlimited max replicas

### ISSUE THREAD

**Issue by rochaporto** [kubernetes/kubernetes#75113]
**What would you like to be added**:

Ability to deploy an horizontal pod auto scaler (hpa) with no upper limit for the max number of replicas.

**Why is this needed**:

We're relying on a HPA to scale backfill workloads on our clusters - these are set with very low priority and pre-emptable. They have requests/limits set and the hpa will try to keep them at 80% cpu usage, which results in always trying to fill clusters with enough replicas to stay close to max cpu usage.

We work around this by setting a (very) unreasonable high number of max replicas, but it feels like maxReplicas could be made optional (or -1 == unlimited) for some use cases.

**Comment by mattjmcnaughton** [comment]
@DirectXMan12 is this something you think would be useful/a good idea? If yes, I'm happy to do a pr :) 

/assign

**Comment by DirectXMan12** [comment]
It seems like it could be a potential foot-gun, but it's not super-unreasonable -- I think it's probably worth discussing in a meeting (or here) a bit more.

**Comment by mattjmcnaughton** [comment]
/unassign

@DirectXMan12 that makes a lot of sense, thanks for weighing in!

@rochaporto if this is still of interest to you, do you mind starting discussions with sig-autoscaling? I think that slack could be a good place.

Still happy to implement this if we decide we want it, but sounds like some discussion could be useful first :)

**Comment by rochaporto** [comment]
Sorry for the delay, thanks for the feedback.

Yes, this is something that would be useful for us. I'll start a discussion as suggested.

**Comment by rochaporto** [comment]
In case this helps, here's a summary of what we're trying to do:
https://techblog.web.cern.ch/techblog/post/priority-preemption-boinc-backfill/

I'll start the discussion next week.
