### ISSUE TITLE
k8s.gcr.io/kube-cross does not work under other architectures like arm64

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#75114]
There's something wrong with the [manifests for kube-cross](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-cross?gcrImageListsize=30) as the image we publish though it seems to have manifests does not work on other platforms like arm64
```
standard_init_linux.go:207: exec user process caused "exec format error"
```

Please see some environment information
```
openlab@node-0:~$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:45:34 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:00:18 2019
  OS/Arch:          linux/arm64
  Experimental:     false
openlab@node-0:~$ uname -a
Linux node-0.dims.openlab-pg0.utah.cloudlab.us 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:53 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
openlab@node-0:~$ docker pull k8s.gcr.io/kube-cross:v1.12.0-1
v1.12.0-1: Pulling from kube-cross
741437d97401: Pull complete
34d8874714d7: Pull complete
0a108aa26679: Pull complete
7f0334c36886: Pull complete
d35724ed4672: Pull complete
d0ea18b1198f: Pull complete
647e63f91386: Pull complete
2b8c6ef26d61: Pull complete
e4c484d78610: Pull complete
e9b4d7c90f68: Pull complete
96fe66b8cafb: Pull complete
cc5a03814b47: Pull complete
e1dc59942b8c: Pull complete
0c842fd38bf6: Pull complete
Digest: sha256:5beba1349458d62edb8b672f0c5a8af4eb3cec4d066015368bf722416bdbfc78
Status: Downloaded newer image for k8s.gcr.io/kube-cross:v1.12.0-1
openlab@node-0:~$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-cross   v1.12.0-1           bf7729bdb359        7 days ago          1.75GB
openlab@node-0:~$ docker run -it k8s.gcr.io/kube-cross:v1.12.0-1 bash
standard_init_linux.go:207: exec user process caused "exec format error"
```

**Comment by dims** [comment]
@mkumatag i think this will fail for ppc64le as well, can you please check and confirm?

/cc @ixdy

**Comment by ixdy** [comment]
right, kube-cross is only published for amd64, since historically contributors were only running cross-builds on amd64 hosts.

**Comment by rockylee3128** [comment]
Hi, dims, I met the same problem, do you fix it

**Comment by rockylee3128** [comment]
Hi, @dims , I met the same problem, do you fix it

**Comment by mkumatag** [comment]
@AnitaNayak

**Comment by justaugustus** [comment]
/assign @dims @AnitaNayak
/remove-lifecycle rotten
ref: https://github.com/kubernetes/kubernetes/pull/85355

**Comment by vennb** [comment]
I am attempting the same on s390x, same error

**Comment by lubinsz** [comment]
cc @zhlhahaha

**Comment by u2bo** [comment]
I met the same problem, do you fix it @dims

**Comment by dims** [comment]
@u2bo not yet. @justaugustus has the TODO in his list.

**Comment by sayanchowdhury** [comment]
Hi @dims @justaugustus 👋🏽 I'm from the Bug Triage Team! I don't see a lot of update on this issue in a while. The code freeze for 1.20 release is starting November 12th which is about 3 weeks from now. As the issue is tagged for 1.20, is it still planned for this release?

**Comment by dims** [comment]
@sayanchowdhury i'll defer to @justaugustus as he was trying to figure out who may be able to help.

**Comment by justaugustus** [comment]
I'm optimistic about being able to wire this up for 1.21.
/milestone v1.21

**Comment by hasheddan** [comment]
xref https://github.com/kubernetes/sig-release/issues/1337

**Comment by BenTheElder** [comment]
Is there a reason we build this for one platform at a time and then create a manifest instead of letting buildx handle the manifest?

https://github.com/kubernetes/release/blob/master/images/Makefile.common-image

**Comment by erismaster** [comment]
Hello! I am from the Bug Triage team! This issue has not been updated for a few weeks, so I'd like to check on the status. Code freeze is starting March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by BenTheElder** [comment]
@dims presumably this is fixed now?

**Comment by dims** [comment]
@BenTheElder yep.

/close
