### ISSUE TITLE
[Failing test] verify.godeps is failing in master-blocking and 1.14-blocking

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75125]
**Which jobs are failing**:
* `ci-kubernetes-verify-master`
* `ci-kubernetes-verify-beta`

**Which test(s) are failing**:
`verify.godeps`

**Since when has it been failing**:
2019-03-07, [build 27262](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/27262) in master, [build 4442](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4442) in 1.14

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#verify-master

/sig testing
/priority critical-urgent
/milestone v1.14

cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by mariantalla** [comment]
/remove-sig testing
/sig api-machinery

Related: https://github.com/kubernetes/kubernetes/issues/73999, https://github.com/kubernetes/kubernetes/issues/74261

**Comment by mariantalla** [comment]
cc @kubernetes/sig-api-machinery-test-failures 

It looks like this started failing right after this merge: https://github.com/kubernetes/kubernetes/pull/71192 (commit [0b48018a3](https://github.com/kubernetes/kubernetes/commit/0b48018a3))

**Comment by liggitt** [comment]
fix in https://github.com/kubernetes/kubernetes/pull/75184

**Comment by spiffxp** [comment]
/reopen
For CI Signal to verify that things look green once we got more job runs

**Comment by alejandrox1** [comment]
All green :tada: 
/close
