### ISSUE TITLE
Graceful pod upgrade during application upgrade

### ISSUE THREAD

**Issue by zhan849** [kubernetes/kubernetes#75136]
**What would you like to be added**:
Currently when we upgrade an app, we always kill and recreate the Pods, and in some scenarios this can be heavy-weighted. I.e. when we want to roll out a different version of sidecar, it's desired that we only restart that sidecar, while keep main container running (of course main container should handle sidecar temporarily not available).

To limit the scope of this enhancement request, we can start with graceful pod upgrade only when images change, as it provides some obvious benefits, especially for statefulsets.

**Why is this needed**
1. Makes it possible to separate dev/release cycles of different teams - usually for stateful systems, people from data infra teams develop the main container, while people in other infra teams develop all the sidecars, i.e security, traffic, logging, metrics, etc.
2. Reduce overhead, both cost and time of unnecessary container restarts, as usually container startup / warmup routines are expensive 

**What is needed**:

1. An option in `v1.RollingUpdateDeployment`, `v1.RollingUpdateDaemonSet`, and `v1.StatefulSetUpdateStrategy` about how Pods wants to be upgraded, i.e. `"Recreate"` or `"PatchIfPossible"`
2. Support such Pod upgrade behavior in corresponding controllers - we can start with StatefulSetController

We are able to experiment it out and contribute to this feature

**Comment by kow3ns** [comment]
Please offfer a [KEP](kubernetes/enhancements) for this proposal if you intend to implement it. You can add me as an approver along with @janetkuo.

**Comment by zhan849** [comment]
thanks @kow3ns ! The KEP link you provided does not work, and can you pls point me to a past KEP example as well?

**Comment by kow3ns** [comment]
https://github.com/kubernetes/enhancements

**Comment by zhan849** [comment]
/remove-lifecycle stale

Sry about the delay, Q2 has been crazy, will finalize the KEP by end of next week.
