### ISSUE TITLE
Windows nodes should not allow privileged containers

### ISSUE THREAD

**Issue by benmoss** [kubernetes/kubernetes#75132]
**What happened**:
Windows pods that have `privileged: true` will still run in Windows, but the `privileged` flag will be ignored. Privileged containers are not supported by Windows, and so some kind of error should occur.

**What you expected to happen**:
An error saying something like "Privileged containers are not supported by Windows"

**How to reproduce it (as minimally and precisely as possible)**:
Deploy this pod: https://gist.github.com/benmoss/bffc51601f8fcedf744ba89ddc23813d

**Anything else we need to know?**:
I considered having kubelet error if `--allow-privileged` is set to true, but it looks like this flag is deprecated and will become always true in the future, if I understand the plan correctly. Therefore it seems like the validation needs to happen on the Pod spec itself when it's being sent to a Windows node.

/sig windows

**Comment by saiyan86** [comment]
moby/moby#31740 addressed this. I think this is a valid request.

**Comment by saiyan86** [comment]
I will fix this issue.

**Comment by benmoss** [comment]
@saiyan86 sorry I forgot to link my PR, already sent one in for this and other security context fields

**Comment by saiyan86** [comment]
@benmoss Cool! Thanks for the heads up 👍
