### ISSUE TITLE
[Failing test] Up test failing in gke-cos-1.14-*

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#75145]
**Which jobs are failing**:
* [ci-kubernetes-e2e-gke-cos-k8sbeta-default](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-default/9702)
* [ci-kubernetes-e2e-gke-cos-k8sbeta-reboot](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-reboot/9068)
* [ci-kubernetes-e2e-gke-cos-k8sbeta-serial](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-serial/2119)
* [ci-kubernetes-e2e-gke-cos-k8sbeta-slow](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-slow/9686)
* [ci-kubernetes-e2e-gke-cos-k8sbeta-ingress](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-ingress/6846)

**Which test(s) are failing**:
`Up`

**Since when has it been failing**:
It has been consistently failing since 3/6, flaking a lot before that. Failure coincides with [kubernetes/kubernetes/compare/7f8d874db...d4fa3c164](https://github.com/kubernetes/kubernetes/compare/7f8d874db...d4fa3c164).

**Testgrid link**:
* [https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default)
* [https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-reboot](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-reboot)
* [https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-serial](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-serial)
* [https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-slow](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-slow)
*[https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-ingress](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-ingress)

**Reason for failure**:

```
W0307 19:22:38.596] 2019/03/07 19:22:38 process.go:153: Running: gcloud container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard --project=k8s-jkns-e2e-gci-gke-ci-flaky --zone=us-west1-b --machine-type=n1-standard-2 --image-type=gci --num-nodes=3 --network=test-ff924dde89 --cluster-version=1.14.0-beta.1.562+88812c559deec4 test-ff924dde89
W0307 19:22:39.884] WARNING: Starting in 1.12, new clusters will have basic authentication disabled by default. Basic authentication can be enabled (or disabled) manually using the `--[no-]enable-basic-auth` flag.
W0307 19:22:39.886] WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-certificate` flag.
W0307 19:22:39.887] WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
W0307 19:22:39.888] WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
W0307 19:22:39.889] This will disable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
W0307 19:22:39.892] WARNING: Starting in Kubernetes v1.10, new clusters will no longer get compute-rw and storage-ro scopes added to what is specified in --scopes (though the latter will remain included in the default --scopes). To use these scopes, add them explicitly to --scopes. To use the new behavior, set container/new_scopes_behavior property (gcloud config set container/new_scopes_behavior true).
W0307 19:22:42.789] Creating cluster test-ff924dde89 in us-west1-b...
W0307 19:39:45.711] .......................................................................................................................................................................................................done.
W0307 19:39:45.773] ERROR: (gcloud.container.clusters.create) Operation [<Operation
```
cc @mortent @kacole2 @mariantalla @smourapina

/kind flake
/kind failing-test
/priority important-soon
/milestone v1.14
/sig cluster-lifecycle

**Comment by alejandrox1** [comment]
sig gcp may be of help here
/sig gcp

**Comment by timothysc** [comment]
/assign @justinsb 

for routing from SCL side.  These are google owned tests.

**Comment by justinsb** [comment]
Looking into this now.  Any other googlers also doing so feel free to ping me :-)

**Comment by justinsb** [comment]
Looks like this bug is known with a fix in flight: https://github.com/kubernetes/kubernetes/pull/75129

cc @msau42 @davidz627

**Comment by mariantalla** [comment]
Thanks @msau42 !

Will keep an eye on this for >5 consistent passes, will reopen if there's a problem.

**Comment by msau42** [comment]
/reopen
Most gke jobs are able to create clusters now, however the serial jobs are still seeing failures

**Comment by msau42** [comment]
Nevermind, it's because the serial job with the fix is still running.  I've verified that the cluster creation succeeds in the latest job.
/close

**Comment by spiffxp** [comment]
/area platform/gke
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gke&test=Up%24
<img width="1106" alt="Screen Shot 2019-03-16 at 12 00 52 PM" src="https://user-images.githubusercontent.com/49258/54480231-2f67f080-47e3-11e9-9783-8532eecc3894.png">

Think we're done here
