### ISSUE TITLE
cherry pick fix for smb unmount issue on Windows 

### ISSUE THREAD

**Issue by michmike** [kubernetes/kubernetes#75154]
Cherry pick PR https://github.com/kubernetes/kubernetes/pull/75087 back to 1.11, 1.12, 1.13

Instructions at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

/sig windows

**Comment by andyzhangx** [comment]
it has been cherry picked to 
1.12.8, 1.13.6
