### ISSUE TITLE
deployment scaling replicaset itself without any update or container down

### ISSUE THREAD

**Issue by denglouping** [kubernetes/kubernetes#75162]
**What happened**:
I noticed that my pod's running time is very short (like hours), but I didn't found any errors, restarts or something like these, and I didn't update my deployment for days.

Found that deployment start scalingreplicaset itself

And a bunch of old replicasets

**What you expected to happen**:
I think the right status is that if nothing happened the pod will keep running status forever

**How to reproduce it (as minimally and precisely as possible)**:
It didn't happen to my tiller and dns pod, but the params of scheler are the same.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
V1.9.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig scalability

**Comment by oxddr** [comment]
Hi @denglouping , could you provide list of steps to reproduce the problem. Based on your description it's hard to tell what's the problem. 
Also, do you observe the same behavior with pods that just sleep indefinitely?

**Comment by denglouping** [comment]
Sorry It doesn't happen all the time, and also I noticed sometimes after I updated my deployment, got the running status of new pods, but the outdated replicaset was still there with the outdated pods.
