### ISSUE TITLE
Network internet test for pod fails on azure

### ISSUE THREAD

**Issue by schrodit** [kubernetes/kubernetes#75172]
**Which jobs are failing**:
N/A
**Which test(s) are failing**:
```
[sig-network] Networking should provide Internet connection for containers [Feature:Networking-IPv4]
```
**Since when has it been failing**:
Ever
**Reason for failure**:
Vm on Azure with no public IP assigned aren't able to perform a `ping` command to the internet.

**Anything else we need to know**:
```golang
It("should provide Internet connection for containers [Feature:Networking-IPv4]", func() {
	By("Running container which tries to ping 8.8.8.8")
	framework.ExpectNoError(
	framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4PingCommand, 30))
})
```
The test (see [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go#L48)) tries to test the internet connection for a pod by pinging 8.8.8.8. 
But azure does not provide ICMP support for VM without a public IP therefore this test cannot succeed.(see [Azure docs](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections))

A fix would be to change the test method to a tcp request instead of a ping request (the test already performs a http get to google.com in its BeforeSuite (see [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go#L38)))
```golang
BeforeEach(func() {
	// Assert basic external connectivity.
	// Since this is not really a test of kubernetes in any way, we
	// leave it as a pre-test assertion, rather than a Ginko test.
	By("Executing a successful http request from the external internet")
	resp, err := http.Get("http://google.com")
	if err != nil {
		framework.Failf("Unable to connect/talk to the internet: %v", err)
	}
	if resp.StatusCode != http.StatusOK {
		framework.Failf("Unexpected error code, expected 200, got, %v (%v)", resp.StatusCode, resp)
	}
})
```

**Comment by pacoxu** [comment]
you may refer to https://github.com/Azure/azure-container-networking/issues/128#issuecomment-448367076

**Comment by cmluciano** [comment]
cc @caseydavenport @dcbw @thockin 

WDYT about the proposal to change this from an ICMP call? 

We probably need input from sig-architecture as well since this as well 

/sig architecture

**Comment by Huang-Wei** [comment]
An alternative is to issue a TCP/UDP request to 8.8.8.8 on port 53.

**Comment by saiyan86** [comment]
@schrodit ICMP is dropped by Azure for security reasons. This is intended. Can use curl as a replacement. I will fix the corresponding test.

**Comment by thockin** [comment]
SGTM

**Comment by saiyan86** [comment]
@thockin Can you please review the related PR? I'll @you in the PR again. Thanks!
