### ISSUE TITLE
gci-gce-scalability flakes - get configmaps latency issue

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#75171]
**Which jobs are failing**:
gci-gce-scalability - this is 100 nodes test for gce. This test is flaking.
**Which test(s) are failing**:
Density test

**Since when has it been failing**:
First fail can be seen in run 23438

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/23438

**Reason for failure**:
99th percentile of GET configmaps call latency is greater than 1s.

**Anything else we need to know**:

**Comment by krzysied** [comment]
![configmaps](https://user-images.githubusercontent.com/25119199/54024584-7a0cbb80-4198-11e9-90a6-a8719a5b25ea.png)

It looks like the problem is related to the increased number of get configmaps call. When the get configmaps calls happen at the same time as saturation pods creation, their latencies significantly increase.

IIUC the increased number of get configmaps calls is due to https://github.com/kubernetes/kubernetes/pull/74755

**Comment by krzysied** [comment]
#74755 should be only a temporary change. I expect that get configmap latency issue should resolve on its own.

/assign
I will try to debug it and find the bottleneck anyway.

**Comment by wojtek-t** [comment]
This https://github.com/kubernetes/kubernetes/pull/74781 should hopefully get it back to where we were previously.

**Comment by krzysied** [comment]
![configmaps_normal](https://user-images.githubusercontent.com/25119199/54523138-168c4600-496f-11e9-8fc1-1b10b042755f.png)
I looks like it is fixed.
