### ISSUE TITLE
Failure to mount/remount Azure files

### ISSUE THREAD

**Issue by harshaperera532** [kubernetes/kubernetes#75180]
**What happened**:
I am using Windows containers (Server Core ltsc 2019). These all have volumes mounted to three different Azure file shares under a single storage account. Multiple instances of these containers run on each node. On deploying the containers I get the following errors. Sometimes this does manage to resolve itself. 

MountVolume.SetUp failed for volume "log-share" : Remove-SmbGlobalMapping failed: exit status 1, output: "Remove-SmbGlobalMapping : No MSFT_SmbGlobalMapping objects found with property 'RemotePath' equal to \r\n'\\\\storageaccounturl\\logs'. Verify the value of the property and retry.\r\nAt line:1 char:1\r\n+ Remove-SmbGlobalMapping -RemotePath $Env:smbremotepath -Force\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n + CategoryInfo : ObjectNotFound: (\\\\storageaccounturl\\logs:String) [Remove-SmbGlobalMapping], Ci \r\n mJobException\r\n + FullyQualifiedErrorId : CmdletizationQuery_NotFound_RemotePath,Remove-SmbGlobalMapping\r\n \r\n"

MountVolume.SetUp failed for volume "config-share" : New-SmbGlobalMapping failed: exit status 1, output: "New-SmbGlobalMapping : Generic failure \r\nAt line:1 char:190\r\n+ ... ser, $PWord;New-SmbGlobalMapping -RemotePath $Env:smbremotepath -Cred ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n + CategoryInfo : NotSpecified: (MSFT_SmbGlobalMapping:ROOT/Microsoft/...mbGlobalMapping) [New-SmbGlobalMa \r\n pping], CimException\r\n + FullyQualifiedErrorId : HRESULT 0x80041001,New-SmbGlobalMapping\r\n \r\n"

**What you expected to happen**:
For the volumes to be mounted. This all worked ok in k8s 1.12.1 using Windows 1803. I have now upgraded to 1.13.4 and Windows ltsc2019.

**How to reproduce it (as minimally and precisely as possible)**:
Use aks-engine to create a 1.13.4 cluster with Windows nodes
Create a storage account
Create multiple file shares under the account.
Add access credentials to the storage account as a secret on k8s
Create a windows container with folders that will be used to mount the Azure storage account file shares.
Deploy to k8s defining volume mounts and volumes in the container section of the deployment
e.g.
        volumeMounts:
        - name: folder1-share
          mountPath: "c:\\app\folder1"
        - name: folder2-share
          mountPath: "c:\\app\\folder2"
      volumes:
      - name: folder1-share
        azureFile:
          secretName: azure-file-share-cred
          shareName: share1
          readOnly: false        
      - name: folder2-share
        azureFile:
          secretName: azure-file-share-cred
          shareName: share2
          readOnly: true

**Anything else we need to know?**:
This maybe related to the fix for https://github.com/kubernetes/kubernetes/issues/73087

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows 2019 
- Kernel (e.g. `uname -a`): 10.0.17763.316
- Install tools: aks-engine 0.13.2
- Others:

**Comment by andyzhangx** [comment]
hi @harshaperera532 in your logs, the remotepath is `storageaccounturl\logs`, so `logs` is the share name? also, could you log on to that agent node, and provide kubelet.err.log, there are logs like `SMB Mapping(%s) already exists, now begin to remove and remount`
