### ISSUE TITLE
[Failing test] gce-cos-<branch>-ingress are timing out 

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75186]
**Which jobs are failing**:
* [`ci-kubernetes-e2e-gci-gce-ingress`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/20602)
* [`ci-kubernetes-e2e-gce-cos-k8sbeta-ingress`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/6339)

**Which test(s) are failing**:
The jobs are timing out, but just before that, the following tests failed:
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should be able to switch between HTTPS and HTTP2 modes`
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should update ingress while sync failures occur on other ingresses`
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] should create NEGs for all ports with the Ingress annotation, and NEGs for the standalone annotation otherwise` (in `gce-cos-master-ingress`)
* `[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should be able to switch between HTTPS and HTTP2 modes` (in `gce-cos-1.14-ingress`)

**Since when has it been failing**:
late 2019-03-07

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-ingress
* https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-ingress

**Reason for failure**:
Timeout related to the L7 controller:
```
error: L7 controller failed to delete all cloud resources on time. timed out waiting for the condition
```

/sig network
/priority critical-urgent (failing consistently in release blocking jobs, blocking other tests entirely from running)

cc @kubernetes/sig-network-test-failures 
cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by nikopen** [comment]
@kubernetes/sig-network-bugs

**Comment by mariantalla** [comment]
@kubernetes/sig-gcp-test-failures could this be a gcp issue?

**Comment by mariantalla** [comment]
also cc'ing the sig-network chairs; could you help to triage this please? 🙏🏻

@thockin @dcbw @caseydavenport

**Comment by MrHohn** [comment]
Seems like Ingress controller kept panicing during the test (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/6367/artifacts/test-6724261826-master/glbc.log):
```
I0311 14:12:41.510138       1 backends.go:249] Sync: backends [{ingress-5906/echoheaders/443 32165 443 HTTPS 8443 false <nil>}]
E0311 14:12:42.100687       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/k8s.io/ingress-gce/pkg/healthchecks/healthchecks.go:332
/go/src/k8s.io/ingress-gce/pkg/healthchecks/healthchecks.go:244
/go/src/k8s.io/ingress-gce/pkg/healthchecks/healthchecks.go:106
/go/src/k8s.io/ingress-gce/pkg/backends/backends.go:220
/go/src/k8s.io/ingress-gce/pkg/backends/backends.go:283
/go/src/k8s.io/ingress-gce/pkg/backends/backends.go:252
/go/src/k8s.io/ingress-gce/pkg/controller/cluster_manager.go:98
/go/src/k8s.io/ingress-gce/pkg/controller/controller.go:349
/go/src/k8s.io/ingress-gce/pkg/controller/controller.go:299
/go/src/k8s.io/ingress-gce/pkg/controller/controller.go:111
/go/src/k8s.io/ingress-gce/pkg/utils/taskqueue.go:84
/go/src/k8s.io/ingress-gce/pkg/utils/taskqueue.go:54
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/k8s.io/ingress-gce/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/k8s.io/ingress-gce/pkg/utils/taskqueue.go:54
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1674e63]
```

/cc @rramkumar1

**Comment by MrHohn** [comment]
Seems like @freehan has filed https://github.com/kubernetes/ingress-gce/issues/675.

**Comment by nikopen** [comment]
this https://github.com/kubernetes/ingress-gce/pull/678 will likely mitigate the CI failures

**Comment by cmluciano** [comment]
Assigning to freehan and kubernetes/ingress-gce#678 's reviewer

/assign @MrHohn @freehan

**Comment by cmluciano** [comment]
@nikopen Can we move this to "Under investigation" on the CI project board?

**Comment by nikopen** [comment]
@mariantalla ^^

**Comment by mariantalla** [comment]
Hey @cmluciano I noticed the `triage/unresolved` label - does that mean that it won't be resolved (as is documented [here](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md)) or that it hasn't been yet?

**Comment by cmluciano** [comment]
@mariantalla No this is a misunderstanding on my part with what this label meant. I thought it signified "open but unassigned" . 

/remove-label triage/unresolved

**Comment by nikopen** [comment]
/remove-triage unresolved

triage labels seem to be a bit old, they should be revamped

**Comment by mariantalla** [comment]
`should be able to switch between HTTPS and HTTP2 modes` and `diffResources` are still failing consistently, nearly all other `Loadbalancing: L7 GCE` are flaking frequently at the moment.

/reopen

**Comment by mariantalla** [comment]
master-blocking runs are clearing out, but 1.14-blocking seem to still include the http2 test ([run #6430](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/6430) is the first that includes https://github.com/kubernetes/kubernetes/pull/75411 in `v1.14`)

**Comment by MrHohn** [comment]
Took a quick look, turned out job "ci-kubernetes-e2e-gce-cos-k8sbeta-ingress" doesn't skip test with the `[Unreleased]` tag.

The job config is auto-generated: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/generated/generated.yaml

@krzyzacy or @yguo0905, how can we add flag `--ginkgo.skip=\[Unreleased\]` to that job?

**Comment by krzyzacy** [comment]
hummmmmmm when did that tag becomes a thing?!

**Comment by rramkumar1** [comment]
@MrHohn I think it is here 

https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml

**Comment by MrHohn** [comment]
Thanks both, let me send a PR to update that.

**Comment by krzyzacy** [comment]
Why not use the feature tag? Introduce a new tag that need to be skipped by default will presumably break everything :-)

**Comment by krzyzacy** [comment]
[feature:unreleased], instead of [unreleased]

**Comment by MrHohn** [comment]
@krzyzacy That sounds like a reasonable approach, but it means we will need to update most of the ingress tests & jobs (more on-going PRs).

Could we update that job to skip `Unreleased` for now and file an issue to cleanup the tag after code freeze? ( Or maybe https://github.com/kubernetes/ingress-gce/issues/667 will happen first:) )

**Comment by krzyzacy** [comment]
I have a feeling this unrelease tag is running in other jobs.. which branch has this tag?

**Comment by MrHohn** [comment]
@krzyzacy The unrelease tag always co-presents with `[Feature:Ingress]` tag. So as long as we patch those ingress jobs it should be fine. https://github.com/kubernetes/test-infra/pull/11820 is updating the remaining jobs:
- k8s-stable3
- k8s-stable2
- k8s-stable1
- k8s-beta

**Comment by rramkumar1** [comment]
+1 to MrHhn

We have the filter on every job config. Each individual test (e. has the unreleased tag based on what branch it needs to be tested on. So if none of the actual tests have "Unreleased" nothing gets skipped.

Ref: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/ingress.go#L431

**Comment by krzyzacy** [comment]
:+1:

**Comment by mariantalla** [comment]
> Took a quick look, turned out job "ci-kubernetes-e2e-gce-cos-k8sbeta-ingress" doesn't skip test with the [Unreleased] tag.

👍 that explains a lot of things 😅 
1.14-blocking is now starting to pass; with the https/http2 test removed:
![image](https://user-images.githubusercontent.com/5007973/54569484-f2fae700-49d2-11e9-8d8a-104ebc63a875.png)

**Comment by mariantalla** [comment]
All clear, closing.

/close
