### ISSUE TITLE
Intercepting the "pods/eviction" subresource via validating webhooks should work

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubernetes#75193]
**What would you like to be added**:

It would be great if I could intercept the "pods/eviction" call for actions with side effects. It is right now possible to register a webhook, but it has no effect.

**Why is this needed**:

Right now it is not possible for controllers to see if pods which they manage are evicted or not. Intercepting "pods/eviction" and performing acthions (e.g. a patch on a resource) is one way of finding that out. It is then possible to perform custom actions before the eviction is finally granted.

**Comment by rmohr** [comment]
@liggitt already created a PR which covers that: https://github.com/kubernetes/kubernetes/pull/72951.

**Comment by liggitt** [comment]
will be fixed in https://github.com/kubernetes/kubernetes/pull/76910
