### ISSUE TITLE
FC Plugin Support for Mount Options

### ISSUE THREAD

**Issue by ejweber** [kubernetes/kubernetes#75191]
**What would you like to be added**:

Currently many in-tree storage plugins, including the iSCSI plugin, support mount options. The FC plugin does not. I have poked around the code enough to know where the plugin reports that mount options are not supported, but it isn't clear to me WHY they aren't supported.

**Why is this needed**:

Mount options can drastically change the performance and data persistence characteristics of a filesystem. For example, "noatime" can reduce metadata operations on frequently read data or "sync" can ensure all writes go immediately down to a backing storage array. I am working on a deployment across an FC backed cluster for which the the containerized application benefits from specific mount options, and I would guess other users might find similar use cases.

It seems to me that if mount options are supportable on iSCSI, they should be equally supportable on FC, but I certainly recognize the possibility that I may be missing something. Otherwise, I'm guessing they simply haven't been a priority?

**Comment by ejweber** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by jsafrane** [comment]
Yeah, we just miss a volunteer that would implement this feature. It should be relatively easy and straightforward, following iscsi as an example.

**Comment by sathish-thangaraj** [comment]
@jsafrane I would like to work on it! As this my first issue I would like to get some help.

**Comment by jsafrane** [comment]
@sathish-thangaraj that's great!

I was going to write detailed info how to fix this, however, I found out that mount options *should* work, at least in Kubernetes 1.13, see this commit: https://github.com/kubernetes/kubernetes/commit/6eda6d1a06dba54c65c8a4073edd40046155bbe5

So there is a simple bug somewhere. Looking around the code, this code smells fishy:

https://github.com/kubernetes/kubernetes/blob/662b683de4c516b1e62cbe101522f27ae942bda9/pkg/volume/fc/fc.go#L140-L154

`If  "block volume feature is enabled" then ... set mountOptions: []string{}`. Can you check with "BlockVolume" feature turned off in kubelet, i.e. `kubelet --feature-gates=BlockVolume=false <...>`? Mount options should work there. And then it should be fairly easy to fix it in `newMounterInternal`.

**Comment by ejweber** [comment]
@jsafrane 
It definitely looks like there's an issue there. I don't think the kubelet ever made it that far in my initial testings, as mounting (with mountOptions listed in the PersistentVolume object) failed with the following message: 

> MountVolume.MountOptionSupport check failed for volume "volume-1" : Mount options are not supported for this volume type

I assume this is related to the following code:

https://github.com/kubernetes/kubernetes/blob/662b683de4c516b1e62cbe101522f27ae942bda9/pkg/volume/fc/fc.go#L97-L99

Is there a way to disable a check like this without rebuilding all of Kubernetes?

**Comment by jsafrane** [comment]
> I assume this is related to the following code:

Good catch!

> Is there a way to disable a check like this without rebuilding all of Kubernetes?

No. IMO it should  be enough to rebuild kubelet here and it's fast and easy: `make WHAT=cmd/kubelet` and find it somewhere in `_output/bin`.

**Comment by ejweber** [comment]
Thanks for the help so far @jsafrane.

I flipped the SupportsMountOption() bool to "true" and the BlockVolume feature gate to false. I was then able to mount an ext4 volume with the "noatime" and "nodiratime" option (confirmed on the worker node). However, I attempted to use the "nobarrier" option but the worker node mounted the volume without it. Finally, I attempted to use a completely made-up option ("hello"). The volume did not fail to mount (as is suggested in the Kubernetes documentation. Instead, it mounted without the "hello" options.

I am attempting to locate useful logs to try to understand why some mount options are ignored or why incorrect mount options aren't causing failures, but the kubelet logs haven't been helpful thus far. Unfortunately I don't currently have any easy access to any iSCSI equipment for comparison.

**Comment by keremgocen** [comment]
anyone working on this? @sathish-thangaraj

**Comment by jeffliu27** [comment]
@jsafrane is there anywhere that I could help on the issue?

**Comment by ejweber** [comment]
Apologies for the extreme delay in keeping up with this issue. I believe the issue with ignored mount options may be more generally related to the way the Linux mounter (/pkg/utils/mount/mount-linux.go) handles mount options, although I don't have enough experience with other volume plugins to speak authoritatively on the issue. I recommend we try to get the basic changes suggested above into the code, as my limited testing shows them to be effective for at least some mount options. I'd try to submit a pull request myself, but I don't want to take it from @rahulk29, as they've already put forth the work to get it started.

**Comment by ejweber** [comment]
To clarify my previous comment, during Attach, the FC volume plugin mounts an FC volume to a global path with no mount options. During Mount, the Linux mounter bind mounts (-o bind) and bind remounts (-o bind,remount) an FC volume to a Pod specific path with mount options. However, the bind remount action is only capable of applying a limited number of mount options (those not on the list are silently ignored). In order to expand our mount option capabilities, we would (I believe) need to use mount options in the Attach phase.

**Comment by eladm26** [comment]
First time contributor, taking this one
/assign

**Comment by ejweber** [comment]
@eladm26, you are, of course, welcome to work on this issue. However, I wanted to let you know that I made code changes back in November that (I believe) address my previous comments. I only received approval from my employer in the last couple of days to make the contributions, or I would have submitted them already. I plan to clean things up and get a PR in sometime this afternoon. 

I am also a first time contributor, so we'll see how it goes.
/assign

**Comment by eladm26** [comment]
No problem at all dude.
You take this one since you already made the changes.
