### ISSUE TITLE
[Flaky Test] [k8s.io] [sig-node] NodeProblemDetector should run without error

### ISSUE THREAD

**Issue by kacole2** [kubernetes/kubernetes#75195]
**Which jobs are failing**:
[sig-release-master-informing#gce-master-scale-correctness](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&width=20)

**Which test(s) are failing**:
`[k8s.io] [sig-node] NodeProblemDetector should run without error`

**Since when has it been failing**:
2019-03-07 @ 22:52

**Testgrid link**:
[sig-release-master-informing#gce-master-scale-correctness](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&width=20)

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:53
Expected error:
    <*errors.errorString | 0xc00c033840>: {
        s: "error getting SSH client to prow@34.73.217.178:22: 'dial tcp 34.73.217.178:22: connect: connection refused'",
    }
    error getting SSH client to prow@34.73.217.178:22: 'dial tcp 34.73.217.178:22: connect: connection refused'
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:97
```
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:53
Expected error:
    <*errors.errorString | 0xc00c033840>: {
        s: "error getting SSH client to prow@34.73.217.178:22: 'dial tcp 34.73.217.178:22: connect: connection refused'",
    }
    error getting SSH client to prow@34.73.217.178:22: 'dial tcp 34.73.217.178:22: connect: connection refused'
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:97
```

**Anything else we need to know**:
/milestone v1.14
/sig node
/kind flake
/priority important-soon

**Comment by soggiest** [comment]
@Random-Liu  We are in code freeze for 1.14. Will this be closed in the next week? Or, if it isn't release blocking can we move it to 1.15?

**Comment by dchen1107** [comment]
@wangzhen127 can you take a look at this issue too? Thanks!

**Comment by Random-Liu** [comment]
@kacole2 I don't see the test running in sig-release-master-informing#gce-master-scale-correctness.

Are you sure that is the correct job?

**Comment by wangzhen127** [comment]
I will take a look now.

**Comment by wangzhen127** [comment]
@kacole2, can you update the test grid link? I don't see the test, either. And FYI, this test is now disabled on large clusters. See https://github.com/kubernetes/kubernetes/pull/75177.

**Comment by spiffxp** [comment]
/close
Agree this is taken care of by #75177
