### ISSUE TITLE
Backoff timer is shared between different operations on a volume

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#75209]
This is similar to issue I filed awhile ago - https://github.com/kubernetes/kubernetes/issues/41307 which is basically, if `Attach` of a volume keeps failing for quite awhile then `Detach` also won't be attempted until `maxDurationBeforeRetry` (2 min 2s currently) if exponential backoff does reaches that threshold.

I think we should not let concurrent operation on a volume but when nature of operation changes on a volume, we should reset the exponential backoff. IMO - it does not make sense to start from where previous operation left off when the operations aren't the same.

I think that may solve/help with problem https://github.com/kubernetes/kubernetes/issues/47350#issuecomment-470802348

cc @kubernetes/sig-storage-misc @smarterclayton

**Comment by smarterclayton** [comment]
Definitely a latency / scalability issue with removing and reacting to dead pods / namespaces.
