### ISSUE TITLE
flake: NodeLease when the NodeLease feature is enabled the kubelet should report node status infrequently 

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#75205]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=node_lease.go

```
test/e2e/common/node_lease.go:84
Timed out after 300.977s.
Expected
    <*errors.errorString | 0xc00050f0c0>: {
        s: "node status report period is shorter than lease duration",
    }
to be nil
test/e2e/common/node_lease.go:118
```

/assign
/milestone v1.14

**Comment by mariantalla** [comment]
@kubernetes/sig-node-test-failures & cc @dchen1107 @derekwaynecarr 

Hey sig-node, could we have some help with this issue please?

It's currently flaking 8% of the time in [`ci-kubernetes-e2e-gci-gce`](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce%24&test=NodeLease%20when%20the%20NodeLease%20feature%20is%20enabled%20the%20kubelet%20should%20report%20node%20status%20infrequently) (which is release-blocking) and an average of ~15% of the time [across all jobs it's a part of](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=NodeLease%20when%20the%20NodeLease%20feature%20is%20enabled%20the%20kubelet%20should%20report%20node%20status%20infrequently).

/priority important-soon

**Comment by mariantalla** [comment]
(Edit: Removed comment to ask for help, noticed open PR later...

For context/help to measure change post #75206 merge:
This is currently failing about 8% of the time in `ci-kubernetes-e2e-gci-gce`, and an average of ~15% of the time across all jobs it's a part of)

**Comment by spiffxp** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=shorter%20than%20lease%20duration
<img width="1095" alt="Screen Shot 2019-03-16 at 11 47 05 AM" src="https://user-images.githubusercontent.com/49258/54480049-40affd80-47e1-11e9-9fd6-b379aa74ec97.png">

Think this is done
