### ISSUE TITLE
Scale statefulset with precision

### ISSUE THREAD

**Issue by preddys75** [kubernetes/kubernetes#75216]
**What would you like to be added**:  I would like to ability to scale down a stateful set and enter the pod I want to target to be removed from the statefulset as a result of this command. I would then like to add the name of the node when I request the statefulset to scale back up. 

**Why is this needed**: This will help greatly in applications with large statefulsets during maintenence. It will give the ability to put maintenence operations in a loop and apply them to locations of each pod without having to scale the whole set down to zero. Will help greatly with elastic search.

**Comment by kow3ns** [comment]
This is too far from the current design of statefulset. If you are interested in implementing this you can implement a custom controller using [kubebuilder](https://book.kubebuilder.io/). If you disagree and you want to offer a design for community discussion you can offer a [KEP](https://github.com/kubernetes/enhancements) in SIG Apps and present it to the community.
/close
