### ISSUE TITLE
CSI Inline - code enhancement post alpha

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#75220]
Code enhancements based on code review from @davidz627 from #74086 

* Consolidate functions which returns source from volume.Spec (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263187404)
* Standardize on volumeHandle for consistency (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263187629)
* Fix comment indicated [here](https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263188997)
* Review if-block logic suggested here (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263189491)
* Possibly add a new type to carry around common values as suggested in this thread here (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263190054)
* Add comment to clarify func that generates new volumeHandle (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263190387)
* Add comment to discourage removal of keys for json file (see https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263191420)
* Implement this change here (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263107572)
* Fix TODO comments ( https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263191876)
* Update comment as suggested here (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263192445)
* Revisit how logic is determining persistent vs ephemeral (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263192100)
* Fix this comment (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263188291)
* Revisit this change (https://github.com/kubernetes/kubernetes/pull/74086/commits/923ad369c8a65c8aac47b22457e7e18bbcc1f335#r263192582)

**Comment by davidz627** [comment]
more post-merge comments:
https://github.com/kubernetes/kubernetes/pull/74086#discussion_r264021318
https://github.com/kubernetes/kubernetes/pull/74086#discussion_r264015162

**Comment by vladimirvivien** [comment]
Thank you.

**Comment by vladimirvivien** [comment]
Thanks @kfox1111

**Comment by vladimirvivien** [comment]
I don't most (if not all) are needed any longer due to the massive progression of the codebase since this was open.  If I am wrong, please feel free to re-open.
