### ISSUE TITLE
CSI Inline - Update CSIDriver to indicate driver mode

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#75222]
Currently, the alpha implementation of CSI inline implicitly relies on the source from volume.Spec to determine ephemeral vs persistent as done here https://github.com/kubernetes/kubernetes/blob/9fd3d2718b1d77849b92cf287c2ae70dd65d5912/pkg/volume/csi/csi_plugin.go#L787 

This change modifies the storage CSIDriver object to carry that information as outline in the original  [KEP here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190122-csi-inline-volumes.mda).

https://github.com/kubernetes/kubernetes/blob/9fd3d2718b1d77849b92cf287c2ae70dd65d5912/pkg/apis/storage/types.go#L264

**Comment by pohly** [comment]
As discussed in https://github.com/kubernetes/kubernetes/issues/79624, it is useful to allow drivers to work in both modes. https://github.com/kubernetes/kubernetes/pull/79983 implements that.

What remains open is to check the CSIDriver.Mode: an additional sanity check that prevents a "normal" driver to be used inline or vice-versa is useful.

Or can we rely on CSI drivers failing gracefully when used the wrong way? Then CSIDriver.Mode can be removed.

**Comment by kfox1111** [comment]
I don't think we can rely on that. Ephemeral bypasses the normal csi workflow, starting potentially half way through it when used in ephemeral mode. The driver needs to be designed to handle that. In the other case, using it in a pv will have unexpected effects, as it can be shared between pods, but will get deleted once the first pod is deleted, causing a use after delete...

**Comment by pohly** [comment]
/close

This is implemented: https://github.com/kubernetes/kubernetes/blob/6348200c92dec8848e55552f3e8039b3da95bd91/staging/src/k8s.io/api/storage/v1beta1/types.go#L306-L319
