### ISSUE TITLE
kubectl wait should not return if resource not yet exist

### ISSUE THREAD

**Issue by inoam** [kubernetes/kubernetes#75227]
Hi! This is my first submitted issue so feel welcome to point me anywhere :)
Consider the following example:
I install my application (using helm but it does not matter).
As part of installation some pods are being created. Suppose pod A the was created directly by helm, is creating pod B, at some point.
I have a script that wishes to wait until pod B is ready/Running.
I wish to use kubectl wait.
The problem: in case pod B is not yet created when runnig kubectl wait, it returns immediately with error. 
I saw on issue https://github.com/kubernetes/kubernetes/issues/66456, that Shivang44 wrote:
"Or, if it can't find a resource, it outputs:
Error from server (NotFound): deployment.extensions "web" not found.
Which is expected and a useful output."
Well, I disagree. The way I see it, everything performed with wait could be performed with loop (yes there is probably better polling / event waiting on kubectl wait). In this case I can solve with a loop on my script, but it misses the point of using wait.
I believe the support shuold be in k8s side.

**Comment by MrD2** [comment]
This should be reviewed
