### ISSUE TITLE
Does Kubernetes plan to support orchestrating raw binaries like nomad?

### ISSUE THREAD

**Issue by kant111** [kubernetes/kubernetes#75235]
Does Kubernetes plan to support orchestrating raw binaries(like say executing python script without containerizing) like nomad although I understand they both are built for different purpose etc! I see that there are still some companies in the industry doesn't want to move towards using containers yet therefore my question.

**Comment by praseodym** [comment]
I think this topic is better discussed on the [Kubernetes forum](https://discuss.kubernetes.io/).
