### ISSUE TITLE
[Umbrella issue for tracking] ci-kubernetes-e2e-gce-new-master-upgrade-cluster is flaky in 1.14

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#75239]
**Which jobs are failing**:
* `ci-kubernetes-e2e-gce-new-master-upgrade-cluster` in [sig-release-master-upgrade#gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster)

**Which test(s) are failing**:
Some of the flaking tests are:
* `[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down`

**Related issues**
- #75045 

/sig release
/area deflake
/kind flake
/priority important-soon
/milestone v1.14

**Comment by krmayankk** [comment]
Hello! We are in code freeze for 1.14. If this issue is release blocking, can we get a review on this issue? If this issue is not release blocking can we move it to 1.15?

**Comment by krmayankk** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
This is probably the same issue as https://github.com/kubernetes/kubernetes/issues/72500.

**Comment by krmayankk** [comment]
https://github.com/kubernetes/kubernetes/pull/74652 adding the pr that is fixing #72500 and probably this

**Comment by nikopen** [comment]
@alejandrox1 #74652 has been merged, is this behaving better?
