### ISSUE TITLE
HPA scales over MaxReplicas and then wont scale down.

### ISSUE THREAD

**Issue by dmarkey** [kubernetes/kubernetes#75247]
**What happened**:
I was testing HPA with a custom metric, and the deployment gets scaled one over maxPods and will refuse to scale down. Also the metric is read as "Unknown" even though it is available via the custom metric API.

Scaling the deployment down manually rectifies the situation.

**What you expected to happen**:

That the deployment doesn't scale beyond the desired amount of pods and scales down properly.

**How to reproduce it (as minimally and precisely as possible)**:

My custom metric is kind of specific, but should be reproducible for any custom metric (I think)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.5-eks-6bad6d 
- Cloud provider or hardware configuration: nodes: v1.11.5
- OS (e.g: `cat /etc/os-release`):Amazon AMI for EKS(lates)
- Kernel (e.g. `uname -a`): Amazon AMI for EKS
- Install tools: Flux/GitOps
- Others:

There may have been an cluster autoscaler event triggered (i.e. pending pods needed a new node added), not sure if that matters.

HPA output in real time:

```
$kubectl get hpa -n uat -o wide -w 
NAME         REFERENCE           TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
test-hpa   Deployment/test   0/500m    3         15        4          150m
test-hpa   Deployment/test   2/500m   3     15    4     150m
test-hpa   Deployment/test   1/500m   3     15    4     151m
test-hpa   Deployment/test   3/500m   3     15    4     151m
test-hpa   Deployment/test   1666m/500m   3     15    9     152m
test-hpa   Deployment/test   1571m/500m   3     15    9     152m
test-hpa   Deployment/test   1285m/500m   3     15    9     153m
test-hpa   Deployment/test   1285m/500m   3     15    9     153m
test-hpa   Deployment/test   714m/500m   3     15    9     154m
test-hpa   Deployment/test   1285m/500m   3     15    9     154m
test-hpa   Deployment/test   1857m/500m   3     15    9     155m
test-hpa   Deployment/test   <unknown>/500m   3     15    16    155m
test-hpa   Deployment/test   <unknown>/500m   3     15    16    156m
test-hpa   Deployment/test  <unknown>/500m   3     15    16    156m
test-hpa   Deployment/test  <unknown>/500m   3     15    16    157m
test-hpa   Deployment/test   <unknown>/500m   3     15    16    157m

```

**Comment by dmarkey** [comment]
I think I have some more information that might help. At the time of the autoscaling, there was 2 ReplicaSets in flight due to a deployment that was not rolling out properly.. I think this confused the HPA

**Comment by SaltedEggIndomee** [comment]
@dmarkey I have the same error. From observations, the scaling DOWN gets stuck when the scaling UP don't finish successfully. Long after the metric have re-fallen back down well below the target. 

Could be due to faulty Pods schedule, Node down, application failure etc. All will lead to this bug. 

I'm using Kubernetes 1.12 on EKS btw
