### ISSUE TITLE
delete recycler pod  not found error

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#75259]
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Recycle failed: failed to delete recycler pod: pods "recycler-for-pv50zoo3" not found

**Comment by neolit123** [comment]
/sig storage

hi, if you don't get a response soon, consider upgrading because 1.11 is going out of support at the end of this month.
