### ISSUE TITLE
JMeter load tests on multi-node EKS is slower than single-node cluster

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#75250]
**Which jobs are failing**:

**Which test(s) are failing**:
jmeter-5.1
**Since when has it been failing**:

**Testgrid link**:

**Reason for failure**:
Load test reports show that repsonse time from applications running on multi-node full-blown EKS cluster is much much slower than that from the same application running on a single-node EC2 cluster.

**Anything else we need to know**:
I have a full-blown kubernetes deployed on AWS EKS with ALB Ingress, horizontal pod autoscaler and cluster autoscaler. At the time of running the load test, 5 nodes are running and `kubectl get hpa -w` shows that the application is only at 20%/75% TARGET.

JMeter configuration:

Ramp-Up time: 100 seconds
```
Users     EKS     EC2
500:     200ms    100ms
1000:   5500ms  100ms
```

**Comment by khteh** [comment]
Here are the figures with `curl`, `ntimes` and `percentile`:
```
$ ntimes 100 -- ./curl_responsetime.sh https://myapp,eks.com/startSession --compressed | percentile
50%:	0.067528
66%:	0.094281
75%:	0.107139
80%:	0.115962
90%:	0.139908
95%:	0.172744
98%:	0.200265
99%:	0.228161
100%:	0.244852
$ ntimes 100 -- ./curl_responsetime.sh https://myapp.ec2.com/startSession --compressed | percentile
50%:	0.061199
66%:	0.064142
75%:	0.065373
80%:	0.066425
90%:	0.068595
95%:	0.07036199999999999
98%:	0.078259
99%:	0.082118
100%:	0.26717
```

**Comment by vinsguru** [comment]
@khteh 
The JMeter test - is that something you could share?

**Comment by khteh** [comment]
Share what?

**Comment by vinsguru** [comment]
The jmeter .jmx

**Comment by khteh** [comment]
What do you want to do with it?

**Comment by khteh** [comment]
Appears to be a bottleneck with single-pod Elasticsearch. Performance is back to normal after upgrading Elasticsearch to a full-fledged cluster.
