### ISSUE TITLE
Add more metrics to the scheduler for the number of pods scheduled and pending

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#75267]
**What would you like to be added**:
Add more [scheduler metrics](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go) to count the number of pods scheduled and the number of pending pods in the scheduling queue.

**Why is this needed**:
These metrics are helpful to debug scheduler and find about its health. It also provides insight to users about their cluster status.

/sig scheduling

**Comment by Huang-Wei** [comment]
I will take it as I haven't got a chance to explore metrics related code.

/remove-help
/assign
