### ISSUE TITLE
Allow kubectl to use absolute path

### ISSUE THREAD

**Issue by MQasimSarfraz** [kubernetes/kubernetes#75268]
**What would you like to be added**:
Currently `kubectl` is looking for kubeconfig in user home directory (relative path) but It would be great if `kubectl` supports a global path (absolute path) e,g `/etc/kubernetes/kubeconfig.yaml`.

**Why is this needed**:
I have a kubernetes cluster that is being shared between multiple people. All of them have different Linux users but want to access the k8s clsuter with same kubernetes `admin` user or just say I am running `api-server` on custom port. If the given feature was available I can simply put the file at a shared path and everything works out of box. 

One possible solution is using `$KUBECONFIG` but if commands are not processed via [shell](https://docs.ansible.com/ansible/latest/modules/command_module.html) there is no clean way other than using `--kubeconfig` with every command. May be I am missing something but it would be great if we can have absolute path support.

**Comment by MQasimSarfraz** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by draveness** [comment]
Do you suggest that kubectl needs to find the config file in multiple paths by default?

**Comment by MQasimSarfraz** [comment]
Yes. We can decide if we want to merge both the configs are prioritize relative path (user's home directry) over absolute path to maintain compatibility with existing setups. Do you see any issues with it?

**Comment by liggitt** [comment]
you can override the path kubectl uses to locate its kubeconfig by setting the $KUBECONFIG environment variable. you can also specify multiple paths in the $KUBECONFIG envvar (separated by the path separator character, e.g. `:` on linux)

/close
