### ISSUE TITLE
Scheduler should spread pods among physical host

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#75274]
Scheduler has a spreading mechanism that is enabled by default and spreads pods of a collection (ReplicaSet, etc) among nodes of a Kubernetes cluster. This works reasonably well in cloud environments, but it is not enough in on-prem clusters. Most users run a virtualization layer (KVM, vSphere, etc) on their physical machines and the guest VMs running on these physical machines act as nodes of Kubernetes clusters. As a result, a few nodes (VMs) of a Kubernetes cluster may run on the same physical host. Today, Kubernetes is oblivious to the physical hosts and may schedule multiple pods of a service on K8s nodes that run on the same physical machine. If the physical machine goes down, the service may get disrupted.

**What would you like to be added**:
A mechanism to make Kubernetes aware of the physical hosts and add a feature to the scheduler to spread pods among physical hosts (as well as K8s nodes).

**Why is this needed**:
To improve reliability of services running on Kubernetes. This is specially important when users run Kubernetes on-prem.

- [ ] Define a [standard label](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/well_known_labels.go) for nodes to identify the physical host.
- [ ] Add a mechanism to query virtualization layer (vSphere, etc) to find about physical hosts and adds them as a label to Kubernetes nodes. This could be an admission webhook, for example, that talks to the hypervisor at the time of node creation and adds the label to the nodes. (This is just an idea. Various options should be explored and a proper design doc with pros and cons of the options is needed.)
- [ ] Add a priority (scoring) function to the scheduler that spreads pods among physical hosts if the labels exist. If the labels don't exist, or spreading among physical host is not possible, it spreads pods among K8s nodes.

/sig scheduling
/kind feature

**Comment by bsalamat** [comment]
There is a related effort (which looks abandoned) by vmware: https://github.com/vmware/vsphere-affinity-scheduling-plugin.
I haven't looked closely at the project, but there are probably many ideas there that we can use here. It seems that it uses an scheduler extender to achieve spreading. We don't want to build an extender for performance reasons, but the spreading algorithm is probably the same as what we need here.

**Comment by Huang-Wei** [comment]
It might need to involve sig-cloudprovider, so that right after provisioning, the bm/vm can be tagged properly.

**Comment by bsalamat** [comment]
> It might need to involve sig-cloudprovider, so that right after provisioning, the bm/vm can be tagged properly.

Good point. In fact, it may be useful to have the physical label for nodes running in "cloud" as well.

**Comment by denkensk** [comment]
Maybe I can try to work on it.
/assign
/remove-help

**Comment by vllry** [comment]
I probably can't take on a lot, but I'll volunteer to help.

**Comment by bsalamat** [comment]
@denkensk @vllry Thank you both! Please read this comment and let me know which part of this effort you would like to work on.

This project has two mostly independent part:
1. Build a priority function for the scheduler.
1. Build an admission webhook to call some API (vSphere, etc) to get physical host information and add the label to the nodes at the time of node creation. Admission webhook is one option. Another option is to add this logic to Kubelet. Kubelet could possibly read this information and add it to the node. Having this in Kubelet has the downside of a race condition between the scheduler scheduling some pods on the node and the kubelet adding the label to the node. We should investigate these options and write a document about pros and cons of possible options.

We will probably need various implementations of the labeling mechanism (item 2 above) for vSphere, and other virtualization software, but we can start with one.

**Comment by denkensk** [comment]
@bsalamat @vllry  let me take part 2.  And  I think I can work with vally to write a document  for the whole issue firstly.

**Comment by wgliang** [comment]
@denkensk This is great! It is also necessary, we are missing too much documentation for feature changes.

**Comment by k82cn** [comment]
node controller may be another option to update the "label"; and it's better to avoid duplicated request to the VM provider for every nodes.

Regarding the race condition, it's acceptable for priorities compared to predicates :).

**Comment by denkensk** [comment]
> node controller may be another option to update the "label"; and it's better to avoid duplicated request to the VM provider for every nodes.

+1

**Comment by vllry** [comment]
I can take 1. @denkensk do you have a KEP started?

**Comment by denkensk** [comment]
> I can take 1. @denkensk do you have a KEP started?

Yes I just started. I will share the KEP with you later.

**Comment by bsalamat** [comment]
> node controller may be another option to update the "label"; and it's better to avoid duplicated request to the VM provider for every nodes.
Regarding the race condition, it's acceptable for priorities compared to predicates :).

Node controller is indeed an option and I agree that the bar for priority functions is lower and the race condition may be accepted in most scenarios, but given that the scheduler could schedule hundreds of pods per second, it might schedule many replicas of a collection on a set of newly added nodes on the same physical host which don't have the labels yet. Given this, we should evaluate all the options and choose node controller if it reduces complexity significantly.

**Comment by krmayankk** [comment]
i am happy to review and implement parts of this if needed parts of this. Spreading of pods across physical hosts and vms is definitely high on my priority.

**Comment by k82cn** [comment]
>  we should evaluate all the options

+1

**Comment by vllry** [comment]
@denkensk what's the progress on getting a KEP draft up? I'm digging into the scheduler component, but there's a limit to what I can do without the details solidified.

**Comment by denkensk** [comment]
HI @vllry  My bandwidth has been full recently You can also take over the part 2 and have a KEP draft up. You can assign this issue to yourself.

**Comment by denkensk** [comment]
HI @krmayankk @vllry My bandwidth has been full recently You can free to take over the part 2 and have a KEP draft up. You can assign this issue to yourself.  /unassign

**Comment by misterikkit** [comment]
I have not yet started writing a KEP for this. @vllry @denkensk do either of you have a draft that we can work from, or should I start from scratch?

Meanwhile, I'm going to go re-read the current spreading implementation.

**Comment by misterikkit** [comment]
As I started researching this, I found an email thread happening in @kubernetes/sig-cloud-provider which potentially subsumes this effort. 

https://groups.google.com/forum/#!topic/kubernetes-sig-cloud-provider/32N59IYXogY

**Comment by embano1** [comment]
Related issue with design implications listed under "phase 2" in the issue: https://github.com/kubernetes/kubernetes/issues/64021

**Comment by misterikkit** [comment]
Created the KEP so we can make a decision and have it documented.

**Comment by alculquicondor** [comment]
I'm interested in picking up the definition of the standard label.

**Comment by ahg-g** [comment]
@alculquicondor we can't formally assign it to you since you are not a member of K8s yet, but we assume this is assigned to you.

**Comment by andrewsykim** [comment]
Please see discussion in https://groups.google.com/forum/#!topic/kubernetes-sig-cloud-provider/32N59IYXogY regarding standardized labels, I think we need to have more discussions for what to do there.

**Comment by alculquicondor** [comment]
This can be superseded by #80639
