### ISSUE TITLE
apiregistration status should list kinds of a group/version

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#75271]
**What would you like to be added**:
I want to be able to list all the kinds in my cluster using just `kubectl`.

Today, I can see all the groups and versions with `kubectl get apiversions`.
But I can't see what kinds are in that group.

(You can get this from swagger, but that requires using e.g. `curl`.)

The aggregation layer already sets the status for APIService kind.
It could set the list of kinds in that group as part of the status as well.

**Why is this needed**:

As a user: as I add more ttypes (e.g. operators) to my cluster, it is hard to keep track of what kinds I have available.

As someone concerned about kubectl code: I don't want kubectl to have to do this on the client side using swagger.

**Comment by mbohlool** [comment]
what about `kubectl api-resources`?

**Comment by erictune** [comment]
Whoa.  TIL.
