### ISSUE TITLE
Simplify CleanupMountPoint workflow by removing IsCorruptedMnt and IsNotMountPoint

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#75273]
By reviewing PR #75087 and the relevant code, we think the function in CleanupMountPoint could be much simplified. In current workflow it does

1. Check path exist or not, if not, return with error
2. Check path is considered corrupted mount point (here we are not very clear what errors should be considered as corrupted mount points in Linux and Windows). If not corrupted mount points, return with error
3. If path exist and is not corrupted mount point, check whether it is a mount point. If it is no longer a mount point, remove the dir.
4. If it is a mount point, or a corrupted mount point (as the checking result from 2), issue umount, returns error if there is one.
5. If umount has no error, check whether it is still a mount point, if it is not, remove dir.

I think the whole process can be much simplified by removing the corrupted or normal mount point checking before issuing umount
1. Check path exist or not, if not, return with error
2. Issue umount, (but should not return even if there is an error)
3.  check whether it is a mount point. If it is no longer a mount point, remove the dir. Otherwise, return error message

**Comment by jingxu97** [comment]
cc @msau42 @saad-ali

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
I think we can also simplify PathExists by always returning true if err is returned.  Right now it returns false if some non-corrupted err is returned, which I don't think is a safe assumption

**Comment by mucahitkurt** [comment]
Hi @jingxu97 ,@msau42, I would like to work on this issue. For the PathExists function, I think if the error type is NotExists then it'll continue to return false, am I right?

**Comment by tedyu** [comment]
If this is still relevant, I can spend some time on this.
