### ISSUE TITLE
Document kernel requirements

### ISSUE THREAD

**Issue by benmccann** [kubernetes/kubernetes#7528]
[From @thockin](https://github.com/GoogleCloudPlatform/kubernetes/issues/6910#issuecomment-97300278):

> @benmccann We don't have a stated policy on kernel compat. for now it's pretty much "whatever docker supports". We should solidify that.

 Here's what I found in [the Docker docs](http://docs.docker.com/installation/ubuntulinux/):

> Additionally, your kernel must be 3.10 at minimum. The latest 3.10 minor version or a newer maintained version are also acceptable. Kernels older than 3.10 lack some of the features required to run Docker containers. These older versions are known to have bugs which cause data loss and frequently panic under certain conditions.

Some of the networking stuff is substantially cleaner if we can assume kernel 3.6, which I would like.

CC @dchen1107 @rjnagal @ghodss @justinsb

**Comment by quinton-hoole** [comment]
Surely, pragmatically speaking, the answer is currently bounded by the kernel versions supported by Docker, i.e. >= 3.10.  We can't support Kubernetes on top of kernel version which are known to be unstable and unsupported w.r.t. Docker.  That also simplifies our networking, which ideally requires >=3.6.  Is there anything more to discuss here?

Of course we could theoretically consider supporting kernel versions earlier than 3.10 on containers other than Docker (e.g. Rocket), but unless there's pretty solid requirement for that, I'd say no.

**Comment by a-robinson** [comment]
+1 to @quinton-hoole

**Comment by sidharta-s** [comment]
Docker kernel requirements seem to vary by distro. For example, see : http://docs.docker.com/installation/centos/ . CentOS/RHEL 6 are still popular/widely deployed.

**Comment by justinsb** [comment]
Also, it might be that the sysctl that is only available on >=3.6 doesn't in fact solve all the problems I thought it would.  So we probably shouldn't let that influence the decision.  @thockin's understanding is much better here.

From @sidharta-s link, It looks like CentOS backported the kernel fixes that Docker needs to the 2.6 kernel that is part of CentOS 6.5.

**Comment by quinton-hoole** [comment]
Aah, my oversight in not reading the docker support docs properly.  The restriction to kernel >=3.10 only applies to Ubuntu.  For Centos RHEL the restriction is >= 2.6.32-431 .  I wonder how much of the stock kernel 3.6 and beyond has been back-ported to Centos/RHEL kernel 2.6.32-431?  Last I looked (which was quite a few years ago, admittedly), many of the Centos/RHEL 2.6.x kernels were that version in name only, but included large back-ported chunks of later stock kernels.  e.g. can anyone confirm whether or not the sysctl changes that justinsb@ mentions above and that are in the >=3.6 stock kernel have been back-ported to RHEL 2.6.32-431?

**Comment by thockin-cc** [comment]
Sadly, kernel support in this regard is not easily detected - how can we
detect a back port? And worse, we would like to be able to assume modern
tools (up tables binary, for example) but can't.

CentOS 6 FTW!

**Comment by quinton-hoole** [comment]
For detecting backports, I have in the past used runtime detection of kernel compile flags:

http://stackoverflow.com/questions/14376540/view-linux-kernel-config-options

In that case it worked pretty well, but we'd have to check how well we can detect what we're looking for in this case.

**Comment by BenTheElder** [comment]
We probably also need requirements for some packages/utilities like iptables? (3760).

In general there doesn't seem to be much documentation about requirements for running kubernetes, though the code seems to try to stay back-compatible when possible.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/277

**Comment by dankohn** [comment]
Could anyone please definitively state the minimum Linux kernel version that will definitely work with Kubernetes 1.9?

**Comment by timothysc** [comment]
EL7.4 - kernel(s) are the lower bound.

**Comment by dankohn** [comment]
@timothysc RHEL 7.4 uses the 3.10 kernel.

https://access.redhat.com/articles/3078#RHEL7
