### ISSUE TITLE
[Failing Test] gce-scale-performance failed due to high latency Endpoints POST request

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#75284]
**Which jobs are failing**: ci-kubernetes-e2e-gce-scale-performance

**Which test(s) are failing**: Density (testing/density/config.yaml)

**Since when has it been failing**: March 11th 2019

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance

**Reason for failure**:
```
:0
[measurement call APIResponsiveness - APIResponsiveness error: top latency metric: there should be no high-latency requests, but: [got: {Resource:endpoints Subresource: Verb:POST Scope:namespace Latency:{Perc50:2.252341s Perc90:2.252341s Perc99:2.252341s} Count:1}; expected perc99 <= 1s]]
:0
```

**Comment by mm4tt** [comment]
This is the call that made the test fail

```
I0311 08:23:48.406292       1 wrap.go:47] POST /api/v1/namespaces/kube-system/endpoints: (2.281780751s) 201 [operator/v0.0.0 (linux/amd64) kubernetes/$Format 35.237.232.213:57892]
```

It was issued by the Prometheus Operator. 

It looks like there was only one POST on endpoints resource made by the Prometheus Operator throughout whole run (not only this particular test).

**Comment by mm4tt** [comment]
It looks similar call happens in all tests with Prometheus stack enabled, the difference is that they happen outside of density/load test and the api call latency is not measured for them. 

E.g. run 328 (successful):

```
W0307 08:41:37.053] I0307 08:41:37.053528   12721 prometheus.go:116] Waiting for Prometheus stack to become healthy...
I0307 08:44:55.635313       1 wrap.go:47] POST /api/v1/namespaces/kube-system/endpoints: (4.68811093s) 201 [operator/v0.0.0 (linux/amd64) kubernetes/$Format 35.231.179.209:40374]
W0307 08:48:40.480] I0307 08:48:40.479958   12721 prometheus.go:59] Prometheus stack set up successfully
W0307 08:48:40.480] I0307 08:48:40.480002   12721 clusterloader.go:136] Running testing/density/config.yaml
```

Whereas in run 330 the api call was made after the test started

```
W0311 08:20:24.675] I0311 08:20:24.674849   12323 clusterloader.go:136] Running testing/density/config.yaml
I0311 08:23:48.406292       1 wrap.go:47] POST /api/v1/namespaces/kube-system/endpoints: (2.281780751s) 201 [operator/v0.0.0 (linux/amd64) kubernetes/$Format 35.237.232.213:57892]
```

**Comment by mm4tt** [comment]
Actually, looks like the prometheus stack wasn't created successfully in this test

```
W0311 08:20:09.804] I0311 08:20:09.804391   12323 prometheus.go:49] Setting up prometheus stack
W0311 08:20:24.674] E0311 08:20:24.674145   12323 clusterloader.go:191] Error while setting up prometheus stack: error while applying (/go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/prometheus-clusterRoleBinding.yaml): Post https://34.73.197.67/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout
W0311 08:20:24.675] I0311 08:20:24.674849   12323 clusterloader.go:136] Running testing/density/config.yaml
I0311 08:23:48.406292       1 wrap.go:47] POST /api/v1/namespaces/kube-system/endpoints: (2.281780751s) 201 [operator/v0.0.0 (linux/amd64) kubernetes/$Format 35.237.232.213:57892]
```

Because of that we logged warning and didn't wait for the stack to be healty, this is why the kubelet endpoints object was created during density test

**Comment by mm4tt** [comment]
To summarize, AIs coming from this issue:

1. Configure Prometheus Operator to not create kubelet Endpoints - we don't monitor kubelets in our scale tests so we don't need it. Alternative is to wait for the kubelet Endpoints object to be created in the `waitForPrometheusToBeHealthy`

2. Make sure we retry errors like `Post https://34.73.197.67/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: net/http: TLS handshake timeout` while setting up Prometheus

3. Given that we're going to use Prometheus to measure API Call Latency on other SLI, we  should fail the test if the Prometheus stack couldn't be set up.

**Comment by wojtek-t** [comment]
The only missing bit here is https://github.com/kubernetes/kubernetes/issues/75294 - so I'm closing in favor of that one
