### ISSUE TITLE
Extracting CRI API to a new staging repository

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#75293]
Looking at say some of the end users of the CRI API

CRI-O : https://github.com/kubernetes-sigs/cri-o/tree/master/vendor/k8s.io/kubernetes/pkg/kubelet
Kind : https://github.com/kubernetes-sigs/kind/tree/master/pkg/container/cri
cri-containerd : https://github.com/containerd/cri/tree/master/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2

Can we please use a staging/ repository and extract this out so folks don't have to vendor kubernetes/kubernetes directly?

**Comment by dims** [comment]
cc @runcom @vbatts @mrunalp @BenTheElder @derekwaynecarr

**Comment by dims** [comment]
kind of related to https://github.com/kubernetes/enhancements/pull/866

**Comment by dims** [comment]
@kubernetes/sig-node-feature-requests

**Comment by vbatts** [comment]
And Alibaba pouch

-------- Original Message --------

**Comment by dims** [comment]
https://github.com/alibaba/pouch/tree/master/cri/apis/v1alpha2 thanks @vbatts

**Comment by mikebrow** [comment]
hmm.. 

Might want to add this as a task within the kep we talked about the last couple weeks for removing dockershim from the kublet tree and moving to CRI from alpha to ga, as these are IMO interrelated activities.

**Comment by feiskyer** [comment]
Looks reasonable. We may need another KEP for CRI GA, as there're still some issues to solve, e.g. streaming APIs and version compatibility. Those issues are independent of any runtimes. @yujuhong

**Comment by dims** [comment]
@feiskyer +1 to KEP for GA. In this Issue, we should concentrate on just the mechanics of creating a new repo and publishing code from staging/ to this new repo.

**Comment by feiskyer** [comment]
@yujuhong Any ideas on this? we'd make this before extracting dockershim out. Let me draft a KEP for detailed discussion.

**Comment by yujuhong** [comment]
Sounds good to me. Let's put the requirements in a KEP as everyone suggested.

Are we skipping beta to GA? :-)

**Comment by mikebrow** [comment]
I would split CRI out first then GA, just in case we need breaking change for splitting docker shim out.. but oh heck yeah good to see these discussions happening for the CRI space.

**Comment by vbatts** [comment]
* is there criteria for the CRI version to become beta?
* is there a tag or specific channel to open CRI specific questions/requests? (i.e. RFC pause/unpause for RuntimeService; RFC load mechanism for ImageService)

**Comment by feiskyer** [comment]
I don't think we have the criteria yet, we should create the criteria first before moving to beta/GA.

> I would split CRI out first then GA, just in case we need breaking change for splitting docker shim out.. but oh heck yeah good to see these discussions happening for the CRI space.

@mikebrow you mean split CRI out as beta? Do you think CRI GA is required before splitting docker shim out?

**Comment by feiskyer** [comment]
> is there a tag or specific channel to open CRI specific questions/requests? (i.e. RFC pause/unpause for RuntimeService; RFC load mechanism for ImageService)

@vbatts sig-node is the place.

**Comment by mikebrow** [comment]
> @mikebrow you mean split CRI out as beta? 

No, I think it's ok to split out the CRI api now before it has been promoted from alpha2 to beta. I would think that is preferable.

> Do you think CRI GA is required before splitting docker shim out?

Not a requirement, just a suggestion.

**Comment by PatrickLang** [comment]
What about the content in https://github.com/kubernetes-sigs/cri-tools ? Should critest move into the same repo and it could be the unit test for the API?

**Comment by vbatts** [comment]
On 25/03/19 14:44 -0700, Patrick Lang wrote:
>   What about the content in
>   [1]https://github.com/kubernetes-sigs/cri-tools ? Should critest move
>   into the same repo and it could be the unit test for the API?

Having those things live together would make sense to me.

**Comment by dims** [comment]
@PatrickLang @vbatts unfortunately things we publish from staging/ cannot have other things in there. Since we will be publishing from `staging/src/k8s.io/cri` into kubernetes/cri repo, we cannot mix it with things from existing cri-tools as there are some assumptions in the publishing-bot at the moment. When we go GA and finally drop the staging/ stuff we can definitely pull cri-tools in.

**Comment by vbatts** [comment]
Makes enough sense. I'm just stating it as a good intention

**Comment by feiskyer** [comment]
agreed with dims. The staging part should be separated from others

**Comment by dims** [comment]
Folks, it's alive https://github.com/kubernetes/cri-api
