### ISSUE TITLE
k8s.io/apiextensions-apiserver misses the generated code

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#75338]
**What happened**:

I'm trying to vendor k8s.io/kubernetes/test/e2e, which due to (recently added ?) code in test/e2e/framework/crd_util.go depends on k8s.io/apiextensions-apiserver. The problem now is that the content of k8s.io/apiextensions-apiserver is incomplete:
apiextensions-apiserver/pkg/controller/openapi/builder.go calls generatedopenapi.GetOpenAPIDefinitions, but apiextensions-apiserver/pkg/generated/openapi/ doesn't contain the generated code.

**What you expected to happen**:

I expect k8s.io/apiextensions-apiserver to compile when fetching it with "go get" or vendoring it with tools like "dep".

**How to reproduce it (as minimally and precisely as possible)**:

```
$ go get k8s.io/apiextensions-apiserver
# k8s.io/apiextensions-apiserver/pkg/controller/openapi
../apiextensions-apiserver/pkg/controller/openapi/builder.go:327:16: undefined: "k8s.io/apiextensions-apiserver/pkg/generated/openapi".GetOpenAPIDefinitions
../apiextensions-apiserver/pkg/controller/openapi/builder.go:382:11: undefined: "k8s.io/apiextensions-apiserver/pkg/generated/openapi".GetOpenAPIDefinitions
```

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by roycaihw** [comment]
sent a fix in https://github.com/kubernetes/kubernetes/pull/75339
