### ISSUE TITLE
Include CSR-signing CA cert bundle in default service account token secret

### ISSUE THREAD

**Issue by leblancd** [kubernetes/kubernetes#75337]
**What would you like to be added**:
*Usually*, the cluster-signing CA certificate bundle that is used for signing CSRs (see [Manage TLS Certificates in a Cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)) is the same as the cluster's Root CA. This root CA is readily available by someone who needs to import the CA into their clients' trust chain, since it is included as data (in the "ca.crt" field) in the default service account's token secret (see [Trusting TLS in a Cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#trusting-tls-in-a-cluster)).

However, in some platforms (e.g. PKS), the cluster-signing CA cert bundle is configured to be a different than the root CA cert bundle. These CA cert bundles are configured on the Kubernetes controller manager with these startup configs (for cluster-signing and root CA respectively):
```
    --cluster-signing-cert-file
    --root-ca-file
```
So when `--cluster-signing-cert-file` is configured, there's no way to retrieve that CA bundle other than SSHing onto a master node and looking at that configuration. And cluster admins aren't going to want non-admin users poking around where the CA private key is stored.

I would like to see the cluster-signing (or "CSR-signing") CA bundle included in the default service-account token secret, along with the root CA (i.e. the "ca.crt" data field). 

**Why is this needed**:
Some platforms configure a *different* CSR-signing CA than the cluster's root CA. When configured this way, there's no way to retrieve the CSR-signing CA bundle other than SSHing onto a Kubernetes master node and looking where the `--cluster-signing-cert-file` is pointing... and typically this is going to be the same directory as where the CA private key is.

One workaround would be to have the cluster admin create a separate Kubernetes secret for the CSR-signing CA bundle, but there would have to be a well-documented name for this new Kubernetes secret.

**Comment by liggitt** [comment]
> I would like to see the cluster-signing (or "CSR-signing") CA bundle included in the default service-account token secret, along with the root CA (i.e. the "ca.crt" data field).

those two trust bundles are distinct, and should not be combined by the controller manager. if the cluster admin wishes to distribute the CSR signing roots that way, they can include the signing CA in the root-ca-file

/close

**Comment by leblancd** [comment]
@liggitt, 
My request probably wasn't clear enough. I'm not saying that the trust bundles should be combined, they definitely need to be kept distinct. I'm suggesting that a new field be added to the secret used for the default service-account token, e.g. something like the "cluster-signing-ca.crt" here, so that the cluster-signing CA can be retrieved:
```
diverdane@ubuntu:~$ kubectl get secret default-token-dpw4z -o yaml
apiVersion: v1
data:
  ca.crt: 
                < - - - Root CA redacted - - - >
  cluster-signing-ca.crt: 
                < - - - New field, cluster signing CA goes here - - - >
  namespace: ZGVmYXVsdA==
  token: 
                < - - - Token redacted - - - >
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
                < - - - Snipped - - - >
```

**Comment by leblancd** [comment]
@liggitt - Would it at least make sense to clarify the ["Trusting TLS in a Cluster"](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#trusting-tls-in-a-cluster) section for this case? This section talks about trusting the root CA, but this is the wrong CA to add whenever `--cluster-signing-cert-file` is configured.

**Comment by liggitt** [comment]
> I'm suggesting that a new field be added to the secret used for the default service-account token

the content of the service account token secret is oriented around communication with the kube-apiserver. it's not a generic mechanism for injecting arbitrary trust bundles into pods

The "trusting TLS in a cluster" should clarify that it is referring to communication with the kube-apiserver

It could make sense to populate a configmap containing a bundle of CSR-signing certs, but that would be distinct from the kube-apiserver CA
