### ISSUE TITLE
Improve PV/Claim binding

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#7534]
See #7438.
- use GuaranteedUpdate when saving the bind
- create BindingREST subresource similar to pod

**Comment by markturansky** [comment]
Half of this issue is obsolete.  All generic etcd registries use GuaranteedUpdate. 
https://trello.com/c/4PQjMIuF/191-spike-investigate-shrinking-or-expanding-persistent-volumes

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc is this still an issue?

**Comment by markturansky** [comment]
@kargakis I don't think so. Closing in favor of new PRs.
