### ISSUE TITLE
`kubectl top pod` does not show any utilization %

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#75350]
**What happened**:
`kubectl top pod` does not show any utilization %
**What you expected to happen**:
`kubectl top pod` shows utilization %
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
`kubectl top node` shows utilization % but not `kubectl top pod`
**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.4
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.10
- Kernel (e.g. `uname -a`): 4.18.0-16-generic
- Install tools: kubectl
- Others:

**Comment by shiywang** [comment]
I don't think it's a bug of cli

when you use `kubectl top pods` the `Available v1.ResourceList` from server seems missing.

```
(*metricsutil.ResourceMetricsInfo)(0xc0006c7980)({
 Name: (string) (len=37) "metrics-server-v0.2.1-fd596d746-gqjnx",
 Metrics: (v1.ResourceList) (len=2) {
  (v1.ResourceName) (len=3) cpu: (resource.Quantity) 1m,
  (v1.ResourceName) (len=6) memory: (resource.Quantity) 21096Ki
 },
 Available: (v1.ResourceList) {
 }
})
(v1.ResourceList) {
}
```

@DirectXMan12 @kubernetes/sig-cli-misc 
/sig sig-autoscaling-bugs

**Comment by DirectXMan12** [comment]
it's not an autoscaling or metrics bug -- I think this is purely in the SIG CLI realm -- that `Available` field doesn't come from the metrics API (plus, metrics is SIG Instrumentation)

**Comment by shiywang** [comment]
okay, I'll take a look

**Comment by shiywang** [comment]
@khteh @liggitt for Node they have stuff like [Node.Status.Allocatable](https://github.com/fabric8io/kansible/blob/master/vendor/k8s.io/kubernetes/docs/proposals/node-allocatable.md) which is the utilization for now. In Pod, maybe we can calculate by `spec.containers[].resources.requests/spec.containers[].resources.limits` ? or we just disable showing `utilization %` for pod temporarily if that's not useful for pod currently?

https://github.com/kubernetes/kubernetes/blob/d1e865ee341ba37469efed8c935e22e2b483eec2/pkg/kubectl/cmd/top/top_node.go#L212-L216

**Comment by shiywang** [comment]
also @kubernetes/sig-cli-feature-requests
