### ISSUE TITLE
[Flaky Test] gce-scale-correctness : [sig-network] Loadbalancing: L7 [Slow] Nginx should conform to Ingress spec

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#75361]
**Which jobs are failing**: ci-kubernetes-e2e-gce-scale-correctness

**Which test(s) are failing**:  [sig-network] Loadbalancing: L7 [Slow] Nginx should conform to Ingress spec

**Since when has it been failing**: It failed yesterday (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/221), passed today

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness

**Reason for failure**: Timed out

**Comment by mm4tt** [comment]
/sig scalability
/sig network

@kubernetes/sig-network-test-failures, could you triage?

**Comment by cmluciano** [comment]
Seeing this passing for the last three days. I believe this was a flake.
