### ISSUE TITLE
[Flaky test] [sig-apps] DaemonRestart [Disruptive] Kubelet should not restart containers across restart

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75373]
**Which jobs are failing**:
* `ci-kubernetes-e2e-gci-gce-serial` ([testgrid](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial)) ([triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial%24&test=Kubelet%20should%20not%20restart%20containers%20across%20restart))
* `ci-kubernetes-e2e-gce-cos-k8sbeta-serial` ([testgrid](https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-serial)) ([triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-cos-k8sbeta-serial%24&test=Kubelet%20should%20not%20restart%20containers%20across%20restart))

**Which test(s) are failing**:
`[sig-apps] DaemonRestart [Disruptive] Kubelet should not restart containers across restart`

**Reason for failure**:
A timeout while deleting the namespace:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:152
Mar 13 23:56:13.750: Couldn't delete ns: "daemonrestart-7581": namespace daemonrestart-7581 was not deleted with limit: timed out waiting for the condition, pods remaining: 1 (&errors.errorString{s:"namespace daemonrestart-7581 was not deleted with limit: timed out waiting for the condition, pods remaining: 1"})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:342
```

**Anything else we need to know**
* This test flakes about 10% of the time at the moment.

/sig apps
/remove-kind failing-test
/kind flake
/priority important-soon
/milestone v1.14

cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by mariantalla** [comment]
@kubernetes/sig-apps-test-failures

**Comment by spiffxp** [comment]
Looking back a week ago, it seems like at least one major cluster started happening around March 1st, so possibly related to go 1.12
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-03-09&test=DaemonRestart#24a9e90c86eb2ad855a0

This may be worth keeping an eye on now that go 1.12.1 has been introduced https://github.com/kubernetes/kubernetes/issues/74890

**Comment by mariantalla** [comment]
No failures since March 15th in master-blocking:
![image](https://user-images.githubusercontent.com/5007973/54533446-0d58a480-4982-11e9-83a0-3940332e3329.png)

or 1.14-blocking
![image](https://user-images.githubusercontent.com/5007973/54533479-2feabd80-4982-11e9-8270-2bf0ef7dc32a.png)

Let's keep an eye on it for a couple more days.

**Comment by alejandrox1** [comment]
this test failure hasn't shown up for a while 🎉 
/close
