### ISSUE TITLE
[Flaky test] NodeLease when the NodeLease feature is enabled the kubelet should report node status infrequently

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75370]
**Which jobs are failing**:
* `ci-kubernetes-e2e-gci-gce` ([testgrid](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=20)) ([build 35714](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35714))
* `ci-kubernetes-e2e-gce-cos-k8sbeta-default` (testgrid(https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default&width=20)) ([build 9864](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/9864))

**Which test(s) are failing**:
`NodeLease when the NodeLease feature is enabled the kubelet should report node status infrequently`

**Since when has it been failing**:

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-default&width=20

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/node_lease.go:83
Timed out after 300.000s.
Expected
    <*errors.errorString | 0xc00177a260>: {
        s: "node status heartbeat is unchanged for 14.708854559s, waiting for 1m20s",
    }
to be nil
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/node_lease.go:134
```

**Anything else we need to know**:
* https://github.com/kubernetes/kubernetes/issues/75205 cleared out flakiness in the same place (different error though)

/sig node
/remove-kind failing-test
/kind flake
/sig node
/milestone v1.14
/priority important-soon

cc @liggitt as you worked on https://github.com/kubernetes/kubernetes/issues/75205 and might have input
cc @smourapina @alejandrox1 @kacole2 @mortent

**Comment by mariantalla** [comment]
This test is currently flaking up to 5% of the time in these jobs.That's not terrible, but the jobs are among the flakiest, so stabilizing it would really help.

**Comment by liggitt** [comment]
deflake in #75374

**Comment by spiffxp** [comment]
I think we finally got it with #75374 

GCE: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gce&test=NodeLease
<img width="1086" alt="Screen Shot 2019-03-16 at 11 20 29 AM" src="https://user-images.githubusercontent.com/49258/54479751-85d23080-47dd-11e9-9efc-3fd64d5e8841.png">

**Comment by liggitt** [comment]
agreed, I was watching the same query
