### ISSUE TITLE
The max label value length is too low.

### ISSUE THREAD

**Issue by edgan** [kubernetes/kubernetes#75380]
I want to have a AWS instance with a fqdn like the name below, but the current label value limit seems arbitrarily low. I should be able to set a FQDN as a label. As I feel like I should be able to set a subdomain as a label. I am aware of the design URL below. But I see no reason why labels should be limited to hostnames, and not allow things like subdomains or fqdns.

I would understand the restriction more if it was a limit on the title/name of the key, like ` kubernetes.io/hostname`, but the limit on values doesn't make sense. If I took the hostname limit of 63, and the subdomain limit of 253, the total is 316, not 63.

A side effect is I am having to change the naming scheme to using a random custom eight character hash in place of the instance id to make sure the fqdn is unique.

Design URL:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#identifiers-and-names-in-kubernetes

FQDN:
kube-frodo-worker-01a346cae00e2fcda.inf.us-west-2.aws.parsablenet.org <-- 69 characters

Instance id:
i-01a346cae00e2fcda

HOSTNAME:
kube-frodo-worker-01a346cae00e2fcda <--- 35 characters

SUBDOMAIN:
inf.us-west-2.aws.parsablenet.org <--- 33 characters

kubectl get nodes output:
```
NAME                                                           STATUS   ROLES    AGE     VERSION
kube-frodo-master-01.inf.us-west-2.aws.parsablenet.org         Ready    master   2d22h   v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-master-02.inf.us-west-2.aws.parsablenet.org         Ready    <none>   2d22h   v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-master-03.inf.us-west-2.aws.parsablenet.org         Ready    <none>   2d22h   v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-worker-01.inf.us-west-2.aws.parsablenet.org         Ready    <none>   2d22h   v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-worker-02.inf.us-west-2.aws.parsablenet.org         Ready    <none>   2d22h   v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-worker-03.inf.us-west-2.aws.parsablenet.org         Ready    <none>   2d22h   v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-worker-bec22759.inf.us-west-2.aws.parsablenet.org   Ready    <none>   18h     v1.13.4-beta.0.57+ff2b76f1b5531b
kube-frodo-worker-f6cac2eb.inf.us-west-2.aws.parsablenet.org   Ready    <none>   18h     v1.13.4-beta.0.57+ff2b76f1b5531b
```

Sample from `kubectl get node kube-frodo-master-01.inf.us-west-2.aws.parsablenet.org -o yaml`:
```
    kubernetes.io/hostname: kube-frodo-master-01.inf.us-west-2.aws.parsablenet.org
  name: kube-frodo-master-01.inf.us-west-2.aws.parsablenet.org

```

**Comment by akumria** [comment]
This really feels like more of a low-level thing, rather than any specific to AWS.

I think the 'sig/aws' is undeserved here.

Although what is a "reasonable" value length limit? 1024? Why not 2048? Or why not 100?

It has to be arbitrary, but I agree that 63 is on the low-side of arbitrariness.

**Comment by erictune** [comment]
Is the problem that the node can't be register because it can't set the label?
Or does the node register, but you cannot select it?

**Comment by justinsb** [comment]
Now we've promoted `kubernetes.io/hostname` out of beta, I think we need to re-examine this and raise the limit to match typical hostnames.

cf https://github.com/kubernetes/kubernetes/issues/90686#issuecomment-629351287

**Comment by justinsb** [comment]
And @etune the problem is that the kubelet can't create the node, because it tries to create it with a hostname label that is too long.

**Comment by nickperry** [comment]
@akumria @edgan 

> Although what is a "reasonable" value length limit? 1024? Why not 2048? Or why not 100?
> 
> It has to be arbitrary, but I agree that 63 is on the low-side of arbitrariness.

I think the limit should be 253.

"Section 2.3.4. Size limits" of https://tools.ietf.org/html/rfc1035 defines the limit of a DNS name as 255 octets. This shakes out to 253 characters in standard ASCII representation.

Our company would really appreciate this limit being raised. We are getting real problems now caused by the current limit.

**Comment by nickperry** [comment]
My colleague pointed out that it's the RFC 5280 X509 Common Field limit of 64 characters that's the problem here. So whilst a node's DNS name could be up to 253 chars, it wouldn't be able to get a valid certificate.

**Comment by mieubrisse** [comment]
Wanted to add that we'd really, really appreciate the limit being raised as well - we're trying to store some metadata custom to our app on the label, and the 63 limit is low enough that we're tripping it

**Comment by sftim** [comment]
retrospectively
/sig architecture
