### ISSUE TITLE
should not remove SMB mapping if original mapping is correct on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#75396]
**What happened**:
Following code will remove the original SMB mapping on Windows in the second SMB mount action on the same SMB path:
https://github.com/kubernetes/kubernetes/blob/d5a3db003916b1d33b503ccd2e4897e094d8af77/pkg/util/mount/mount_windows.go#L87-L94

While if there are a few replicas mounting the same SMB file on the same node, the second smb mount would remove the original SMB mount temparalily which will make the original mount unavailable in a short period of time.

Here the question is how should we check whether original SMB Mapping is valid or not after `isSMBMappingExist` check. cc @PatrickLang 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows
/assign

**Comment by yujuhong** [comment]
Is there a test for SMB?

**Comment by andyzhangx** [comment]
> Is there a test for SMB?

@yujuhong no

**Comment by yujuhong** [comment]
The SMB code is in-tree and not feature gated at all. Is it possible to add a test?

**Comment by andyzhangx** [comment]
> The SMB code is in-tree and not feature gated at all. Is it possible to add a test?

@yujuhong It should be an e2e test since it requires setting up SMB server first, there is already smb e2e test on windows by running azure file PVC test since azure file is also a SMB service:
https://github.com/Azure/aks-engine/blob/master/test/e2e/kubernetes/workloads/iis-azurefile.yaml
While that test is not in upstream. Not sure whether there is a SMB service on aws or gce.
