### ISSUE TITLE
`kubectl get pv -n namespace` does not filter output by namespace

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#75395]
**What happened**:
`kubectl get pv -n namespace` does not filter output by namespace. Instead it returns pv in all namespaces.

**What you expected to happen**:
`kubectl get pv -n namespace` filter output by namespace. Returns pv from the provided namespace.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.4
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.10
- Kernel (e.g. `uname -a`): 4.18.0-16-generic
- Install tools:
- Others:

**Comment by danielqsj** [comment]
Low-level resources, such as nodes and persistentVolumes, are not in any namespace: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#not-all-objects-are-in-a-namespace
