### ISSUE TITLE
Tolerations are doubled when the same toleration key is set twice

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#75406]
**What happened**:

When creating a pod with the same toleration key (but different operators and values), the resulting pod will have double the number of tolerations expected.

For example, spawning the pod [1] will result in the pod having the following tolerations [2]:

    Tolerations:     node-role.kubernetes.io/master:NoSchedule
                     node-role.kubernetes.io/master=true:NoSchedule
                     node-role.kubernetes.io/master:NoSchedule
                     node-role.kubernetes.io/master=true:NoSchedule

The pod still spawns and runs as expected.

[1] https://paste.ubuntu.com/p/JJjbsdm2nM/
[2] https://paste.ubuntu.com/p/WYbgPnmrCx/

**What you expected to happen**:

The set of tolerations should be added only once, not twice.

**How to reproduce it (as minimally and precisely as possible)**:

    kubectl create -f tolerations.yaml  #  see [1]
    kubectl describe -n test-ns po/test-pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.0-alpha.1
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by wgliang** [comment]
It seems that it has nothing to do with the scheduler. We should start with the generation and display of the tolerations.

**Comment by danielqsj** [comment]
I cannot reproduce this in master branch. The describe output is
```
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node-role.kubernetes.io/master=true:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

**Comment by bclau** [comment]
It seems that it might have been caused by using an older kubectl client. Tried this again on a v1.13.1 (both client and server) and couldn't reproduce.
