### ISSUE TITLE
Remove kube-proxy's automatic clean up logic

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#75408]
**What would you like to be added**:
Remove any logic in kube-proxy that tries to automatically clean up proxy rules based on the proxy mode. Only attempt to clean up if `--cleanup` is set.

**Why is this needed**:
This is a continuation of a discussion from https://github.com/kubernetes/kubernetes/pull/75377. There's a lot of complexity that comes with switching the proxy mode on kube-proxy because it tries to delete proxy rules created from other proxy modes. This has a lot of side-effects and we should be encouraging users to reboot thier nodes along with switching proxy modes. One example of this can be found https://github.com/kubernetes/kubernetes/issues/75360.

**Comment by vllry** [comment]
I can take this on - does this issue have/need a KEP?

**Comment by andrewsykim** [comment]
I think not but will defer to @thockin @bowei

**Comment by thockin** [comment]
I think a micro-KEP is appropriate.

Specifically to talk about compatibility with regards to flags and to talk about docs (not sure which, but we have to write this down :)

**Comment by thockin** [comment]
also to talk about --cleanup (I think it should probably clean up its own mode, not the others)

**Comment by vllry** [comment]
/assign @vllry 

(Yay, I can do this now!)
