### ISSUE TITLE
k8s.io/component-base should not call klog.InitFlags

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#75403]
**What happened**:

When updating the dependencies of an E2E test suite that uses test/e2e/framework outside of Kubernetes, the test suite started to fail during startup with an error about `-log-dir` being defined twice.

That's because both the test suite and `k8s.component-base/logs` were calling `klog.InitFlags`. The later gets pulled in via `test/e2e/framework` -> `k8s.io/apiserver` -> `k8s.component-base`.

https://github.com/kubernetes/component-base/blob/4727f38490bc68c3ba5e308586e7b045e216b991/logs/logs.go#L34-L38

**What you expected to happen**:

A package should never call `klog.InitFlags`, or more generally, should never define its own command line flags.

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by yliaog** [comment]
agreed, and as the comment says, it is temporary. It should be fixed.

// TODO(thockin): This is temporary until we agree on log dirs and put those into each cmd.

**Comment by pohly** [comment]
Just for fun I looked at the history: that comment dates back all the way to 2014 (https://github.com/kubernetes/kubernetes/commit/a570b81220331b7182561643faf556fd4ce5cddb) and has been copied two times already since then, without getting fixed.

That's a long time for something "temporary" :grin: 

Please fix it now, it's time.

**Comment by deads2k** [comment]
This is biting me.  I'm trying to work on top of kube 1.13 and I cannot import k8s.io/apiserver/pkg/server and anything that uses glog like google/certificate-transparency, mesos, grpc-ecosystem, and others.

**Comment by deads2k** [comment]
@pohly fancy meeting you here.  This problem you're having here is the same kind of one I'm fighting downstream because of https://github.com/kubernetes/kubernetes/pull/69105

**Comment by pohly** [comment]
@deads2k yes, I see the irony :grin:. But here a global flag got added recently, so in that sense it is a regression. As I said in that PR, importing tests and the framework has always defined global flags, so I don't see that as a regression, only as a missing feature. But let's continue the discussion there.
