### ISSUE TITLE
failed to start sandbox container due to  CNI failed and containerd-shim not installed on system

### ISSUE THREAD

**Issue by caravansary83** [kubernetes/kubernetes#75417]
**What happened**: The pod was failed while deploying (stuck at ContainerCreating state).

**What you expected to happen**: The pods should be successfully deployed and work normally (this bug seems to be on and off for a few days). 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
![error](https://user-images.githubusercontent.com/6527224/54458755-04699800-4722-11e9-9e1f-902bd7052bbc.png)

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", GitCommit:"14ea65f53cdae4a5657cf38cfc8d7349b75b5512", GitTreeState:"clean", BuildDate:"2017-11-22T20:29:21Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", GitCommit:"14ea65f53cdae4a5657cf38cfc8d7349b75b5512", GitTreeState:"clean", BuildDate:"2017-11-22T20:19:06Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Digital Ocean 

- OS (e.g: `cat /etc/os-release`): Ubuntu

- Kernel (e.g. `uname -a`): Linux 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others: The testing code is at https://github.com/ANRGUSC/Jupiter/tree/verify_coded_pricing

/sig network

**Comment by fntlnz** [comment]
@caravansary83 this seems related to #43967 can you check if the discussion there applies to your configuration and confirm that ?

**Comment by neolit123** [comment]
hello,
> Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", 

sorry. but 1.6 is no longer in the support skew.
you need to upgrade to 1.12.

please re-open if you find the same problem with the new version.

/close
