### ISSUE TITLE
kubectl can't started the container but docker can

### ISSUE THREAD

**Issue by wubigo** [kubernetes/kubernetes#75433]
/sig Node

**What happened**:

docker start the container successfully but  kubectl report  "no such file or directory" error
```
kubectl run fluent -it --image=fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch --generator=run-pod/v1 --restart=Never
standard_init_linux.go:207: exec user process caused "no such file or directory"

docker run -it fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch

```

**What you expected to happen**:
kubectl start the container without report file not found error

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

docker inspect fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch

```

               
            "Cmd": [
                "/fluentd/entrypoint.sh"
            ],
            "ArgsEscaped": true,
            "Image": 
               "sha256:314a6f06d2c3e4755dbd46ae72d53e56c694b6f03d45548177c71f81d267d753",
            "Volumes": null,
            "WorkingDir": "/home/fluent",
            "Entrypoint": [
                "/bin/entrypoint.sh"
            ],

```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-16T15:29:34Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

Linux bigo-HP 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by liucimin** [comment]
Maybe your kubelet is not use docker as runtime。
But it use cri-o?
