### ISSUE TITLE
Prevent storage class deletion if there are PVC(PV) related - finalizer

### ISSUE THREAD

**Issue by shay-berman** [kubernetes/kubernetes#75448]
**What would you like to be added**:
Finalizer on the storage class that will prevent storage class deletion if there are PVCs from the subjected storage class.

**Why is this needed**:
Following the new CSI practice, where [CSI secrets](https://kubernetes-csi.github.io/docs/secrets-and-credentials.html) keys defined inside the storage class per CSI operations (controller create\delete\publish\unpublish, node stage\publish).
So the CSI plugin uses secrets coming from the storage class in every CSI operation - means the the storage class must be exist not only in the creation time of the PVC but also for the whole PVC live-cycle. 
Here are the secret keys in the storage class:
> csi.storage.k8s.io/provisioner-secret-name
> csi.storage.k8s.io/provisioner-secret-namespace
> csi.storage.k8s.io/controller-publish-secret-name
> csi.storage.k8s.io/controller-publish-secret-namespace
> csi.storage.k8s.io/node-stage-secret-name
> csi.storage.k8s.io/node-stage-secret-namespace
> csi.storage.k8s.io/node-publish-secret-name
> csi.storage.k8s.io/node-publish-secret-namespace

So if the k8s admin delete a storage class while the PVC is in use by a pod, then delete this pod will fail because CSI plugin will not have the secret to do unpublish\unstage (nor delete the PVC).

To ensure csi secrets coming from storage class, we must prevent (probably by adding storage class finalizer) storage class deletion if there are active PVCs(I think even if the PVC is not used by workload we should prevent the storage class deletion).

FYI @jingxu97 \ @xing-yang - this issue also relevant for the volumeSnapshotClass object (mentioned it in the snapshot design meeting at [18/March/2019](https://docs.google.com/document/d/1qdfvAj5O-tTAZzqJyz3B-yczLLxOiQd-XKpJmTEMazs/edit#) )

**Comment by jingxu97** [comment]
cc @saad-ali @msau42

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests 
cc @gnufied 

So the way that we deal with this issue today, is that we copy all secrets specified in the storageclass to the PV object.  So theoretically, all information needed should be in the PV object, and these controllers should not be looking at StorageClass for the secrets. Now, we don't have a field for storing snapshot secrets today (nor for resize).  @saad-ali, @liggitt and I discussed this and we concluded that the best option is to add snapshot secret ref and resize secret ref to the PV csi spec.

**Comment by gnufied** [comment]
Was the decision to copy snapshot and resizing secrets too to PV was mainly because we needed to persist secrets somewhere in-case SC is deleted or was there any other reason?

Isn't it cheaper to have a finalizer on SC than to create new fields in PV specs?

**Comment by liggitt** [comment]
storage class is used to inform PV creation and deletion. I wouldn't expect to require a storage class to exist to snapshot a PV

**Comment by xing-yang** [comment]
For snapshot, we have a VolumeSnapshotClass, similar to StorageClass for PV/PVC.  It gets copied to VolumeSnapshotContent and it is used when deleting a VolumeSnapshotContent.  This is similar to how StorageClass gets coped to PV and then used when deleting a PV (https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L656).

**Comment by shay-berman** [comment]
@msau42 \ @saad-ali
So according to your comment, the CSI secret keys are copied during the PVC provisioning into the PV object, which mean that PVC can function even if storage class was deleted.  

Follow up questions:
1. Are all the CSI secret keys copied into the PV object?
    According to the PV k8s [doc](https://kubernetes.io/docs/concepts/storage/volumes/#csi), only the controllerPublish, nodeStage and nodePublish secrets stored inside PV object. But what about provision secret(for deletion)?  if the csi plugin requires the csi.storage.k8s.io/provisioner-secret-name in order to delete the PVC, does it mean that the storage class must exist for deletion? (because the provision secret is not copied to the PV object)

2. I think we should update the documentation in the CSI k8s [doc](https://kubernetes-csi.github.io/docs/secrets-and-credentials.html) that changing the secret in the storage class is good only for newly create PVCs, BUT it will not impact existing PVs (that was issued from this storage class). So to complete the secret change the customer MUST update it also on all the existing PV objects.  Toughs?

3. Maybe adding a finalizer to storage class is better then copy secret references to PV object (as @gnufied mentioned). So the user experience for changing the secret reference will be simpler (just change in the storage class instead of go over all the created PVs).

**Comment by liggitt** [comment]
The PV API should remain coherent even in the absence of StorageClass. StorageClass drives creation and deletion of PV objects, but a storage class is not required to drive behavior of an existing PV.

**Comment by shay-berman** [comment]
@liggitt, please clarify - is it mandatory to have the storage class of a PV in order to delete the PV?  (it looks like the csi.storage.k8s.io/provisioner-secret-name is not copied to the PV object. Does it mean that delete PVC is depend on the storage class?)

**Comment by liggitt** [comment]
> is it mandatory to have the storage class of a PV in order to delete the PV? (it looks like the csi.storage.k8s.io/provisioner-secret-name is not copied to the PV object. Does it mean that delete PVC is depend on the storage class?)

A PV provisioned from a storageclass (with a spec.storageClass name set) depends on the storage class for deletion. PVs can be provisioned/deleted via other mechanisms (and not have a storageclass set), and those would not depend on a storageclass for deletion.

**Comment by shay-berman** [comment]
1. @liggitt, as you mentioned the PV deletion depends on the storage class of the PV (assuming the PV was dynamically provisioned). So do you think its better to add finalizer to the storage class that will check if there are no existing PV before delete the storage class?

2. @saad-ali, do you think we should improve the documentation and state that if there is a need to replace CSI secret key on the storage class, then the k8s admin need to update it on the storage class, but also on all the existing PV object that were already provisioned.

**Comment by liggitt** [comment]
> 1. @liggitt, as you mentioned the PV deletion depends on the storage class of the PV (assuming the PV was dynamically provisioned). So do you think its better to add finalizer to the storage class that will check if there are no existing PV before delete the storage class?

Given that updates to storageclass objects are forbidden, delete and recreate is the only tool a cluster admin has to change a parameter in a storageclass (if they `kubectl apply` a change today, I think that happens automatically, actually). I'm hesitant to break that by adding a finalizer, making what was intended to be a delete/recreate operation hang.

Deleting a storageclass does not cause data loss (like deleting a PV does), so I don't think the same rationale around adding finalizers on PVs applies here.

**Comment by liggitt** [comment]
I would not be in favor of adding this feature, but will defer to sig-storage

**Comment by shay-berman** [comment]
ok

Then I think we should specify in the https://kubernetes-csi.github.io/docs/secrets-and-credentials.html that PV depend on storage class. 
So k8s admin will be aware that he cannot delete PVC if its storage class is not exist (because all other operations can be done even if the storage class is not exist, except deleting PVC).

Thoughts?

**Comment by paullaffitte** [comment]
What if I create a pod using a pvc provisioned by a CSI plugin and then delete the related storage class? I tried it and it prevent the pod to be deleted, even if I recreate the storage class afterwards, and it seems that no error is yield. So the cluster admin cannot even know why it isn't working. IMHO this is a serious issue that should be handled, a finaliser seems to be a good option.
