### ISSUE TITLE
cannot use the vip to access the nodeport

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes/kubernetes#75443]
```
[root@k8s-m3 ~]# ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:d6:d2:99 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.9/24 brd 172.16.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.1.240/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
[root@k8s-m3 ~]# curl -I 172.16.1.9:30394
HTTP/1.1 200 OK
Server: nginx/1.15.9
Date: Mon, 18 Mar 2019 15:22:10 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 26 Feb 2019 14:13:39 GMT
Connection: keep-alive
ETag: "5c754993-264"
Accept-Ranges: bytes

[root@k8s-m3 ~]# curl -I 172.16.1.240:30394
^C
[root@k8s-m3 ~]# grep bind /etc/kubernetes/kube-proxy.conf 
bindAddress: 0.0.0.0
```

**Comment by zhangguanzhang** [comment]
version: v1.13.4   
docker: 18.06.03
os: centos 7.6
kernel: Linux k8s-m3 5.0.2-1.el7.elrepo.x86_64 #1 SMP Wed Mar 13 18:41:45 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dcbw** [comment]
@zhangguanzhang can you grab the output of 'iptables-save' on a problem node? Let's see what the iptables rules say about why traffic cannot redirect from the VIP to the nodeport. Thanks!

**Comment by zhangguanzhang** [comment]
```
[root@k8s-m3 ~]# iptables-save
# Generated by iptables-save v1.4.21 on Mon Mar 25 09:34:09 2019
*nat
:PREROUTING ACCEPT [45:2856]
:INPUT ACCEPT [45:2856]
:OUTPUT ACCEPT [78:4672]
:POSTROUTING ACCEPT [78:4672]
:DOCKER - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-LOAD-BALANCER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODE-PORT - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SERVICES - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
-A POSTROUTING -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.244.0.0/16 -d 10.244.3.0/24 -j RETURN
-A POSTROUTING ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-FIREWALL -j KUBE-MARK-DROP
-A KUBE-LOAD-BALANCER -j KUBE-MARK-MASQ
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-NODE-PORT -p tcp -m comment --comment "Kubernetes nodeport TCP port for masquerade purpose" -m set --match-set KUBE-NODE-PORT-TCP dst -j KUBE-MARK-MASQ
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-POSTROUTING -m comment --comment "Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose" -m set --match-set KUBE-LOOP-BACK dst,dst,src -j MASQUERADE
-A KUBE-SERVICES -m comment --comment "Kubernetes service cluster ip + port for masquerade purpose" -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ
-A KUBE-SERVICES -m addrtype --dst-type LOCAL -j KUBE-NODE-PORT
-A KUBE-SERVICES -m set --match-set KUBE-CLUSTER-IP dst,dst -j ACCEPT
COMMIT
# Completed on Mon Mar 25 09:34:09 2019
# Generated by iptables-save v1.4.21 on Mon Mar 25 09:34:09 2019
*filter
:INPUT ACCEPT [6021:1332238]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [5987:1459357]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
-A INPUT -j KUBE-FIREWALL
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -s 10.244.0.0/16 -j ACCEPT
-A FORWARD -d 10.244.0.0/16 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 10.244.0.0/16 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 10.244.0.0/16 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Mon Mar 25 09:34:09 2019
[root@k8s-m3 ~]# kubectl get po,svc -o wide
NAME                         READY   STATUS    RESTARTS   AGE    IP           NODE     NOMINATED NODE   READINESS GATES
pod/nginx-79c7d7f988-jbzsq   1/1     Running   0          113s   10.244.3.3   k8s-m3   <none>           <none>

NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE     SELECTOR
service/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        2d22h   <none>
service/nginx        NodePort    10.106.48.173   <none>        80:31481/TCP   5m10s   app=nginx
[root@k8s-m3 ~]# ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:4e:db:6a brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.7/24 brd 172.16.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.1.240/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe4e:db6a/64 scope link 
       valid_lft forever preferred_lft forever
[root@k8s-m3 ~]# curl 172.16.1.7:31481
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@k8s-m3 ~]# curl 172.16.1.240:31481
^C
[root@k8s-m3 ~]# 
```

**Comment by danwinship** [comment]
ah, looks like
/area ipvs

**Comment by dcbw** [comment]
@zhangguanzhang With IPVS the proxy binds to the dummy interface, not the physical node interface. It sets up IPVS routes for the physical interface's IP instead. Are you able to run `ipvsadm -L` to see what the proxy is adding to the kernel?

**Comment by zhangguanzhang** [comment]
[root@k8s-m3 ~]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.16.1.7:31481 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0         
TCP  10.96.0.1:443 rr
  -> 172.16.1.3:6443              Masq    1      0          0         
  -> 172.16.1.5:6443              Masq    1      0          0         
  -> 172.16.1.7:6443              Masq    1      1          0         
TCP  10.96.0.10:53 rr
  -> 10.244.0.2:53                Masq    1      0          0         
  -> 10.244.2.2:53                Masq    1      0          0         
TCP  10.96.0.10:9153 rr
  -> 10.244.0.2:9153              Masq    1      0          0         
  -> 10.244.2.2:9153              Masq    1      0          0         
TCP  10.96.175.60:443 rr
  -> 10.244.3.2:443               Masq    1      2          0         
TCP  10.106.48.173:80 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0         
TCP  10.244.3.0:31481 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0         
TCP  10.244.3.1:31481 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0         
TCP  127.0.0.1:31481 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0         
TCP  172.17.0.1:31481 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0         
UDP  10.96.0.10:53 rr
  -> 10.244.0.2:53                Masq    1      0          0         
  -> 10.244.2.2:53                Masq    1      0          0

**Comment by lbernail** [comment]
The nodeport should appear in this list with something like:
```
TCP  172.16.1.9:30394 rr
  -> 10.244.0.4:80                Masq    1      0          0         
  -> 10.244.3.3:80                Masq    1      0          0  
```

Did you run the ipvsadm command on the same host? (host IP seems to be `172.16.1.7` instead of `172.16.1.9`)

The nodeport seems to work OK for `31481`

**Comment by zhangguanzhang** [comment]
vip will move to another machine, the `172.16.1.240` is the vip, but cannot connect to the `vip:30394`

**Comment by dcbw** [comment]
@zhangguanzhang is this problem still occurring, and were you able to see the VIP in the output of `ipvsadm -ln` on a node that had the problem?

**Comment by zhangguanzhang** [comment]
My environment has changed, in simple terms:
kube-proxy bind 0.0.0.0, proxyMode is ipvs
```
interface's real ip:nodeport can access the nodeport
interface's vip:nodeport cannot access the nodeport
```

**Comment by vivisidea** [comment]
yep, I got exactly the same problem here.

> My environment has changed, in simple terms:
> kube-proxy bind 0.0.0.0, proxyMode is ipvs
> 
> ```
> interface's real ip:nodeport can access the nodeport
> interface's vip:nodeport cannot access the nodeport
> ```

**Comment by lbernail** [comment]
In IPVS node, a virtual service should be created for all `<nodeip>:<nodeport>`
Could you give us the output of `ip addr` and `ipvsadm -Ln`?

**Comment by zhangguanzhang** [comment]
the vip is 100.64.2.65
```
# ip a s service
11: service: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 74:85:c4:1b:bb:c8 brd ff:ff:ff:ff:ff:ff
    inet 100.64.2.64/24 brd 100.64.2.255 scope global service
       valid_lft forever preferred_lft forever
    inet 100.64.2.65/24 scope global secondary service
       valid_lft forever preferred_lft forever
```
ipvsadm -ln
```
# ipvsadm -ln | head
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  100.64.2.64:30322 rr
  -> 10.245.0.206:12046           Masq    1      0          0         
  -> 10.245.1.3:12046             Masq    1      0          0         
  -> 10.245.2.28:12046            Masq    1      0          0         
TCP  172.17.0.1:30322 rr
  -> 10.245.0.206:12046           Masq    1      0          0         
  -> 10.245.1.3:12046             Masq    1      0          0         
  -> 10.245.2.28:12046            Masq    1      0          0         
TCP  10.76.107.197:30322 rr
  -> 10.245.0.206:12046           Masq    1      0          1         
  -> 10.245.1.3:12046             Masq    1      0          1         
  -> 10.245.2.28:12046            Masq    1      0          1         
TCP  10.245.0.0:30322 rr
  -> 10.245.0.206:12046           Masq    1      0          0         
  -> 10.245.1.3:12046             Masq    1      0          0         
  -> 10.245.2.28:12046            Masq    1      0          0         
TCP  10.245.0.1:30322 rr
  -> 10.245.0.206:12046           Masq    1      0          0         
  -> 10.245.1.3:12046             Masq    1      0          0         
  -> 10.245.2.28:12046            Masq    1      0          0         
TCP  127.0.0.1:30322 rr
  -> 10.245.0.206:12046           Masq    1      0          0         
  -> 10.245.1.3:12046             Masq    1      0          0         
  -> 10.245.2.28:12046            Masq    1      0          0  
TCP  10.64.0.1:443 rr
  -> 100.64.2.62:6443             Masq    1      1          0         
  -> 100.64.2.63:6443             Masq    1      2          0         
  -> 100.64.2.64:6443             Masq    1      2          0         
TCP  10.64.0.10:9153 rr
  -> 10.245.1.226:9153            Masq    1      0          0         
  -> 10.245.2.195:9153            Masq    1      0          0              
TCP  10.64.0.10:53 rr
  -> 10.245.1.226:53              Masq    1      0          0         
  -> 10.245.2.195:53              Masq    1      0          0         
UDP  10.64.0.10:53 rr
  -> 10.245.1.226:53              Masq    1      0          358       
  -> 10.245.2.195:53              Masq    1      0          358 
```

**Comment by lbernail** [comment]
The second IP is not bound. It definitely should
I won't be able to have a look today but I'll try to reproduce

**Comment by AL-Cui** [comment]
> yep, I got exactly the same problem here.
> 
> > My environment has changed, in simple terms:
> > kube-proxy bind 0.0.0.0, proxyMode is ipvs
> > ```
> > interface's real ip:nodeport can access the nodeport
> > interface's vip:nodeport cannot access the nodeport
> > ```

hi,boy.
Have you solved it yet?

**Comment by zhangguanzhang** [comment]
no

**Comment by AL-Cui** [comment]
> no

很急呀，不知道是改kube-proxy配置还是ipvs的

**Comment by zhangguanzhang** [comment]
如果你想vip访问就切成iptables吧

**Comment by AL-Cui** [comment]
难道ipvs就没法解决吗？是否可以修改配置，把VIP地址也加进去

**Comment by AL-Cui** [comment]
> The second IP is not bound. It definitely should
> I won't be able to have a look today but I'll try to reproduce

why The second IP is not bound.Do you konw how to bound?thanks

**Comment by zhangguanzhang** [comment]
@lbernail have resolve is?

**Comment by chendotjs** [comment]
@zhangguanzhang 
Can you provide the minimal steps to reproduce, etc how the secondary IP is bound (though I dont' think it really matters ).
kube-proxy syncs the rules every 30s by default, so there may be a latency  for it to add new service when secondary IP is bound.

**Comment by zhangguanzhang** [comment]
just use keepalived to keep a vip in nodes

**Comment by zhangguanzhang** [comment]
@chendotjs 你可以`ip addr add $VIP/$MASK dev $interface`手动或者写网卡配置文件给node的机器网卡添加vip后另一个机器ping下看看能不能通，能通了再看为啥kube-proxy没有bind上

**Comment by liucimin** [comment]
Yes.We found this problem in our cluster too.
@dcbw 
Is the kube-proxy have options to use special ip for the ipvs virtual server?

**Comment by chenqiangzhishen** [comment]
this is caused by the vip worked in `secondary` interface.
**(wrong)**inet 172.16.1.240/24 scope global secondary eth0
**(correct)**inet 172.16.1.240/24 scope global eth0
so you should change vip mask to 32 not 24, like `172.16.1.240/32` to avoid in `secondary` or slave status.

**Comment by zhangguanzhang** [comment]
thanks @chenqiangzhishen 
`scope global secondary eth0` ---> `scope global eth0`, It will be ok

**Comment by zhangguanzhang** [comment]
You can also configure kube-proxy to solve
https://github.com/kubernetes/kube-proxy/blob/master/config/v1alpha1/types.go#L158

**Comment by AL-Cui** [comment]
> You can also configure kube-proxy to solve
> https://github.com/kubernetes/kube-proxy/blob/master/config/v1alpha1/types.go#L158

咋修改？158行本身就是一个切片，要改成啥才能让kube-proxy转发流量到keepalived增加的新IP

**Comment by zhangguanzhang** [comment]
切片对应的yaml就是数组，例如
key1:
  - value1
  - value2

**Comment by AL-Cui** [comment]
> 切片对应的yaml就是数组，例如
> 
> ```yaml
> key1:
>   - value1
>   - value2
> ```

你说的yaml文件是指哪个yaml文件？我的kube-proxy服务是用system service。还是不太懂应该在哪添加我的vip地址

**Comment by AL-Cui** [comment]
> 切片对应的yaml就是数组，例如
> 
> ```yaml
> key1:
>   - value1
>   - value2
> ```

可是--nodeport-address这个参数不配置的话，不是默认使用所有本地IP吗？

**Comment by zhangguanzhang** [comment]
我是写yaml配置的，如果命令行参数的话你的得写
```
--nodeport-address=172.23.5.0/24
```

**Comment by liucimin** [comment]
> this is caused by the vip worked in `secondary` interface.
> **wrong:** inet 172.16.1.240/24 scope global secondary eth0
> **correct:** inet 172.16.1.240/24 scope global eth0
> so you should change vip mask to 32 not 24, like `172.16.1.240/32` to avoid in `secondary` or slave status.

Thx，this fix my problem.
