### ISSUE TITLE
Trailing whitespace in configmaps causes formatting issue

### ISSUE THREAD

**Issue by aguilarm** [kubernetes/kubernetes#75446]
**What happened**:
- I create a new configmap, where there are no trailing whitespaces on lines, using `|` to make a multil-ine string in yaml.
ex:
```
value: |
  configmap value that should be pretty printed
  with a couple of extra lines
  of text in it.
```
- I edit my configmap with `kubectl edit` or output it as yaml with `kubectl get -oyaml` and the value is human readable or pretty.
- If I later edit that configmap to have a trailing whitespace on one of the lines, `kubectl edit` or `kubectl get -oyaml` outputs the value as a long string with newline characters (\n) instead of a pretty, human readable version.
ex:
```
value: "configmap value that should be pretty printed\nwith a couple of extra lines\nof text in it."
```

**What you expected to happen**:
I always see pretty printed values.

**How to reproduce it (as minimally and precisely as possible)**:
Add a trailing whitespace to configmap values using multi-line text.

**Anything else we need to know?**:
This is a more specific version of https://github.com/kubernetes/kubernetes/issues/36222 which is closed. @lleontop and @jimmythedog discovered repro path.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.11
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): macos 
- Kernel (e.g. `uname -a`): darwin 17.7.0

**Comment by liggitt** [comment]
pretty-printing in more circumstances would be an enhancement to the yaml marshaler. the data is preserved correctly, so the current state is not a bug

**Comment by liggitt** [comment]
trailing space prevents pretty printing here:

https://github.com/kubernetes/kubernetes/blob/52bb829b20ee6729c09215d1d9c8ab94358c8ca5/vendor/gopkg.in/yaml.v2/emitterc.go#L1105-L1107

sourced from here:

https://github.com/go-yaml/yaml/blob/v2/emitterc.go#L1105-L1107

supporting more of the varieties of yaml string wrapping could be opened as a feature request against that component

/close

**Comment by aguilarm** [comment]
@liggitt thanks for taking a look at this, that's closure enough for me!
