### ISSUE TITLE
Update existing scheduling framework extension points according to the latest design

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#75456]
**What would you like to be added**:
We [added the plugin interface and a couple of extension points](https://github.com/kubernetes/kubernetes/pull/70227) for the scheduling framework a few months ago. We improved the scheduling framework design later and made [the interface](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#plugin-api) better.
The implementation of the interface, the existing extension points, and plugin examples need to be updated to be aligned with the newly proposed interface.

/sig scheduling
/assign

**Comment by hex108** [comment]
@bsalamat Thanks for it! Do you have any plan to support out of tree scheduler plugin? If I understand it correctly, we need load these out of tree plugins when scheduler starts working.
