### ISSUE TITLE
Incompatibility between kubelet and kubeadm and kubectl on which label prefix to use

### ISSUE THREAD

**Issue by ozankabak** [kubernetes/kubernetes#75457]
**What happened**:

I am seeing the following warnings in `kubelet` logs:
```
Mar 18 22:41:05 ip-172-32-13-98 kubelet[1655]: W0318 22:41:05.009124    1655 options.go:265] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/master]
Mar 18 22:41:05 ip-172-32-13-98 kubelet[1655]: W0318 22:41:05.009610    1655 options.go:266] in 1.15, --node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type, kubernetes.io/os)
```

**What you expected to happen**:

The `kubelet` seems to think that that the label prefix `node-role.kubernetes.io` is not allowed, suggesting `node.kubernetes.io` instead. However, `kubeadm` uses the former prefix to label and taint control plane nodes. Furthermore, `kubectl` displays node labels based on the former prefix too. So there is an incompatibility between `kubelet` and the `kubeadm`/`kubectl` duo. Either the prefix `node-role.kubernetes.io` should be included the allowed prefixes list, or the `kubeadm`/`kubectl` behaviors should change.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a new cluster using `kubeadm`, check `kubelet` logs in the master node.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux ip-172-32-74-112 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
- Install tools: `kubeadm`
- Others:

**Comment by ozankabak** [comment]
@kubernetes/sig-cli-bugs @kubernetes/sig-node-bugs @kubernetes/sig-cluster-lifecycle-bugs

**Comment by danielqsj** [comment]
@liggitt How about this label prefix `node-role.kubernetes.io` which used across projects ?
Could you give some guideline about whether add it to allowed list or change it to `node.kubernetes.io` ?

I can work on this ticket with your guideline, thanks.
/assign

Ref: https://github.com/kubernetes/kubernetes/pull/68267

**Comment by liggitt** [comment]
> Either the prefix node-role.kubernetes.io should be included the allowed prefixes list, or the kubeadm/kubectl behaviors should change.

Or the node role labels should be added by the control plane initialization process, not self-added by the kubelet via --node-labels

**Comment by ozankabak** [comment]
@liggitt: Question about the third option: If `--node-labels` functionality is not there, how would one label their nodes at setup time (not after join) via `kubeadm`? Today, the most convenient way I know of is to use `node-labels` in `kubeletExtraArgs` when using `kubeadm`.

**Comment by liggitt** [comment]
> how would one label their nodes at setup time (not after join) via kubeadm?

I'll let someone more familiar with kubeadm answer that. You can still use --node-labels to self-assign labels (within specific prefixes designated for self-assignment, or with non-k8s labels), but self assignment is not appropriate for labels that let a node self-claim to be a master node.

**Comment by danielqsj** [comment]
Let kubeadm masters to answer this issue.
/cc @kubernetes/sig-cluster-lifecycle 
/unassign

**Comment by neolit123** [comment]
kubeadm labels your CP nodes with `node-role.kubernetes.io/master` using an API client, not by using the kubelet `--node-labels` flag. see: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/markcontrolplane/markcontrolplane.go#L57

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L266-L268
the incompatibility is technically on the kubelet side.

at this point, if we completely disallow or change this kubeadm label, there is the potential to break existing user infrastructure. also kubeadm is not the only user of this label.

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L66

AFAIK, kubernetes had a problem where there was no standardization of how a CP node should be labeled. every deployer was doing it's own labeling.

please, read the comments in this PR:
https://github.com/kubernetes/kubernetes/pull/39112/

**Comment by ozankabak** [comment]
Yes, there are indeed many places where the `node-role` prefix is used. It seems like a pragmatic solution could be to add this prefix to the allowed list (hence not breaking anyone), but disallowing certain label(s) when self-labeling so that one won't be able to arbitrarily label itself as a master node.

**Comment by davidmccormick** [comment]
Doesn't it make sense that `kubectl` should support a ROLE label having been set in one of the valid node domains, e.g. `node.kubernetes.io/role`="CustomerA"` so that customers can continue to define specialist node roles (except 'master') and not break current functionality?

```
NAME                                         STATUS   ROLES        AGE    VERSION
ip-10-29-11-143.us-west-2.compute.internal   Ready    nodepool-a   105m   v1.14.1
ip-10-29-12-157.us-west-2.compute.internal   Ready    master       112m   v1.14.1
ip-10-29-20-101.us-west-2.compute.internal   Ready    master       112m   v1.14.1
ip-10-29-21-209.us-west-2.compute.internal   Ready    nodepool-b   105m   v1.14.1
ip-10-29-30-121.us-west-2.compute.internal   Ready    nodepool-c   106m   v1.14.1
ip-10-29-31-1.us-west-2.compute.internal     Ready    master       112m   v1.14.1
```
If I transition to using node.kubernetes.io/role="xyz" I get a degraded kubectl experience: -

```
NAME                                         STATUS   ROLES    AGE     VERSION
ip-10-29-15-152.us-west-2.compute.internal   Ready    master   2d18h   v1.14.1
ip-10-29-21-204.us-west-2.compute.internal   Ready    master   2d18h   v1.14.1
ip-10-29-22-212.us-west-2.compute.internal   Ready    <none>   2d17h   v1.14.1
ip-10-29-26-56.us-west-2.compute.internal    Ready    master   2d17h   v1.14.1
ip-10-29-30-211.us-west-2.compute.internal   Ready    <none>   2d17h   v1.14.1
ip-10-29-9-185.us-west-2.compute.internal    Ready    <none>   2d17h   v1.14.1
```

**Comment by liggitt** [comment]
> Doesn't it make sense that `kubectl` should support a ROLE label having been set in one of the valid node domains, e.g. `node.kubernetes.io/role`="CustomerA"` so that customers can continue to define specialist node roles (except 'master') and not break current functionality?

node roles are a natural selector to use for targeting workloads. it is surprising for a node to be able to self-assign a role label and steer workloads to itself (the most obvious unexpected ability would be for a random node to assert it was a master node and steer privileged daemonset pods to itself)

**Comment by neolit123** [comment]
@davidmccormick 

> If I transition to using node.kubernetes.io/role="xyz" I get a degraded kubectl experience: -

```
kubectl label nodes <name> node-role.kubernetes.io/nodepool-a=
```
makes the regular `kubectl get no` show the role.

**Comment by davidmccormick** [comment]
> node roles are a natural selector to use for targeting workloads. it is surprising for a node to be able to self-assign a role label and steer workloads to itself (the most obvious unexpected ability would be for a random node to assert it was a master node and steer privileged daemonset pods to itself)

I appreciate that we should protect against bad actors, it's just a challenge for our distribution (kube-aws) that relies on setting node labels through Cloud-Formation->Userdata->cloud-config->--node-labels command line parameter.  I suppose we could have some sort of privileged process that is watching for nodes and then labeling them for us - is there an accepted standard approach to this?

**Comment by davidmccormick** [comment]
> > If I transition to using node.kubernetes.io/role="xyz" I get a degraded kubectl experience: -
> 
> ```
> kubectl label nodes <name> node-role.kubernetes.io/nodepool-a=
> ```
> 
> makes the regular `kubectl get no` show the role.

Yes if I used the node-role.kubernetes.io/xyz= label then it's ok - I just can't set that from the kubelet command-line going forwards by the looks of things?

**Comment by neolit123** [comment]
i agree that there is a disagreement with the kubelet and kubectl here.

ideally the operator should apply the node-role labels manually and not the nodes them self, but if you still want to indicate that nodes are workers on the node sides, you can apply a temporary label using `--node-labels` and then run a "process" on the operator side to catch new nodes with this temporary label, remove the temporary label and apply `node-role.kubernetes.io/...x`

**Comment by ozankabak** [comment]
There has to be an "official" straightforward way to assign node roles via the `kubeadm` config file. If `node-labels` is not going to support this use case, some other mechanism/key should. Assume that you have something like an auto-scaling group for "worker" nodes. The most natural thing to do would be to provision them with a `kubeadm` config file that assigns "worker" roles to these nodes at join time, without jumping any unnecessary hoops. IMO, a solution that first assigns a temporary taint and then labels the node later on in the provisioning process via `kubectl` looks like a temporary work-around, not a permanent idiom.

**Comment by neolit123** [comment]
the boostrap kubeconfig of a kubeadm worker node does not have the privileges to self-assign role labels for this node. due to security measures, it's unlikely this will change anytime soon.

if you trust your workers you can create a new kubeconfig file that can do this, but you still have to copy it to the workers.

**Comment by dghubble** [comment]
A variety of use cases with autoscaling groups, managed instance groups, or scale sets rely on the `node-role` ability to create sets of nodes labled beforehand for different purposes. It seems to me unlikely these cases will introduce an operator-style components that just-in-time labels nodes as they come and go. I'm not sure how the control plane initialization process could be enough - especially in preemptible worker clusters, nodes are added after control plane bringup, so it would need to be a longer running process.

I get what we're trying to achieve here security-wise (adversary takeover of kubelet, change role). But I suspect a great many folks, will find less than intended workarounds, that will ultimately undermine those efforts. They'll run a process with credentials kubelet lacks. Any solutions involving temporary labels or taints seem to miss the original point - if we're worried about an adversary changing the flag, that same adversary can change the temporary label / taint flag. 

 This is going to be interesting or I'm missing something. Hopefully the later.

**Comment by dghubble** [comment]
[#80238](https://github.com/kubernetes/kubernetes/pull/80238/files) clears up some of the background.

1) `node-role.kubernetes.io/master` had some (quite old) side effects altering a few controller behaviors (such as auto-tainting the master). Unless one had a reliance on one of those behaviors, this looks ok. Clayton added two new labels and also a `LegacyNodeRoleBehavior` gate in there if that's not the case.
2) For regular workloads' node selectors, one could switch to using any label allowed by the new Kubelet rules
3) `kubectl get nodes` I believe will always display ROLES `<none>` initially. The table is printed [here](https://github.com/kubernetes/kubectl/blob/release-1.16/pkg/describe/versioned/describe.go#L3033) calling [findNodeRoles](https://github.com/kubernetes/kubectl/blob/release-1.16/pkg/describe/versioned/describe.go#L4678). I don't think the [labels it checks](https://github.com/kubernetes/kubectl/blob/master/pkg/describe/interface.go#L31) for can be set via Kubelet flags.

Finally, I don't see more references to `node-roles` in kubeadm? Admittedly, I use tools other than kubeadm and don't really follow it, so maybe a user of the rc's could confirm kubeadm is fixed.

**Comment by neolit123** [comment]
> Finally, I don't see more references to node-roles in kubeadm?

deployers like kubeadm, kops and kubespray will continue relying on the `"node-role.kubernetes.io/master"` labels.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L206

**Comment by anguslees** [comment]
Just pointing out that another option for some folks is to _not_ use dedicated masters (ie: drop the node-role usage entirely, from both node-label and pod node selector).  I suspect anyone that prefers slightly more convenience over security and was going to be happy with nodes nominating themselves as masters or not (via the legacy use of kubelet command line flag to just set node-role=master directly) will also be happy with just having master pods mixed into the general pool of nodes.

Fwiw I heartily endorse this option for test clusters and lower-paranoia constrained bare-metal situations (like my home cluster for example).  Higher pod density, greater redundancy for control jobs, and only a single pool of nodes to manage instead of two.  Downside: less defence in depth between a potential container escape and your cluster signing keys.

**Comment by dharmab** [comment]
@anguslees the split master/worker is unfortunately a risky option when using instance-based authentication (e.g. AWS IAM, Azure Managed Identity). Without additional controls like kube2iam or aad-pod-identity- and carefully curated access controls on identity- that could allow worker Pods to gain the privileges of the controller-manager.

(IMO instance-based authentication is risky in general and should generally be avoided, but it _is_ a supported use case...)

**Comment by strigazi** [comment]
@ozankabak Have you found the commit that introduced this change? I can't find it anywhere. Nothing in the changelog either.

**Comment by strigazi** [comment]
k8s v1.14.6 works fine, when I pass `--node-labels=node-role.kubernetes.io/master=""` my master is labeled with this label exactly.

In k8s v1.14.7 `--node-labels=node-role.kubernetes.io/master=""` in kubelet is converted to `--node-labels="node.kubernetes.io/master="` according to kubelet logs and kubectl get node.

**Comment by seanturner83** [comment]
Sorry but if an attacker can change the flags on your kubelet don't you have bigger issues than them changing the node label?

**Comment by anguslees** [comment]
> Sorry but if an attacker can change the flags on your kubelet don't you have bigger issues than them changing the node label?

The goal is to stop sideways movement: a compromise of a single node (and kubelet) should not allow you to take over other nodes or other pods.  Arbitrarily changing the labels on your own node is/was one way you could cause new "interesting" pods (like k8s master pods) to be scheduled on you that might in turn expose more interesting privileges, secrets, etc.

**Comment by jafferaws** [comment]
I'm looking for a solution to this issue. I use Kube-aws  setup with ASG. The kubelet fails to start because of node-role.

Use Case:

 I want to keep the Same node label for Master and Worker nodes as I'm using in v1.15 .

When I tried to upgrade the cluster to V1.16 the  --node-labels is restricted to use  'node-role' 

If I keep the node role as "node-role.kubernetes.io/master" the kubelet fails to start after upgrade.. if I remove the label, 'kubectl get node' output shows <none> for the upgraded node.

**Comment by neolit123** [comment]
the picture around the node-role label limitations on the kubelet side were explained above. TL;DR:
- kubeadm is using an API client with privileged credentials to set node-roles. it would only do that on control-plane nodes using the common "master" label (to be channel to "control-plane" in the future).
- kubeadm has no plans to apply node-roles for other node types.
- high level tools / admins can do that as long as they have credentials.
- the kubelet will not allow you to self-set node roles which is by design.
- kubectl special casing the display for node-role labels is a topic for sig/cli

if you have arguments around the node-role limitations this is a topic for sig/node (kubelet) and sig/architecture (see [this](https://github.com/kubernetes/enhancements/blob/143c03f0af52c47eab48ec54144dab6bcc86c98d/keps/sig-architecture/2019-07-16-node-role-label-use.md))

/remove-sig cluster-lifecycle
/remove-area kubeadm

**Comment by moonek** [comment]
I also think `node-labels` in `kubeletExtraArgs` is a very useful feature from the perspective of Cluster API.
`node-role.kubernetes.io` label is very useful in that it is the default printcolumm of `kubectl get node`.

**Comment by neolit123** [comment]
in a recent k/kubeadm ticket we discussed that it's technically not possible (due to privileges) for kubeadm to allow applying joining nodes the `node-role` and other reserved *kubernetes.io labels:
https://github.com/kubernetes/kubeadm/issues/2509
it becomes the responsibility of the administrator or a higher-level tool, like a controller / operator.

**Comment by liggitt** [comment]
> in a recent k/kubeadm ticket we discussed that it's technically not possible (due to privileges) for kubeadm to allow applying joining nodes the `node-role` and other reserved *kubernetes.io labels:
> [kubernetes/kubeadm#2509](https://github.com/kubernetes/kubeadm/issues/2509)
> it becomes the responsibility of the administrator or a higher-level tool, like a controller / operator.

This is the solution to this issue. Nodes cannot self-assign roles.

/close

**Comment by liggitt** [comment]
This is not a bug.

Nodes are limited in the labels they can apply, and cannot self-apply a role label. Something other than the kubelet must apply that label if it is desired on a node.

**Comment by liggitt** [comment]
I don't see the issue... kubeadm applies that label to the control plane nodes successfully using the privileged setup user rather than asking the nodes to self-label their role (which they are not permitted to). This is the expected approach and is working properly.
