### ISSUE TITLE
Can't change kube-controller-manager cluster cidr

### ISSUE THREAD

**Issue by gouki777** [kubernetes/kubernetes#75461]
**What happened**:  

Node k8s-m1 has CIDR 10.244.2.0/24, occupying it in CIDR map  
controllermanager.go:496] Error starting "nodeipam"   
 controllermanager.go:206] error starting controllers: failed to mark cidr as occupied: cidr  
 10.244.2.0/24 is out the range o/16  

**What you expected to happen**:
my change kube-controller-manager.config --cluster-cidr 10.247.0.0/16.   
but , kube-controller-manager no good.  

how do change cluster CIDR ?     
If kube have cluster-cidr-cache?  
how to do clear k8s-cluster-cidr-cache.  
  

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.5
- OS (e.g: `cat /etc/os-release`): centOS 7.5
- Kernel (e.g. `uname -a`): 4.19.6-1.el7.elrepo.x86_64
- Others:
<pre>
my    kube-controller-manager.config
      - --address=127.0.0.1
      - --allocate-node-cidrs=true
      - --cluster-cidr=10.247.0.0/16      
     .........................................
</pre>
kube-controller-manager.log
<pre>
I0319 03:34:27.516159       1 controllermanager.go:508] Started "podgc"   
I0319 03:34:27.516222       1 gc_controller.go:76] Starting GC controller 
I0319 03:34:27.516229       1 controller_utils.go:1027] Waiting for caches to sync for GC controller I0319 03:34:27.666379       1 controllermanager.go:508] Started "deployment" 
I0319 03:34:27.666444       1 deployment_controller.go:152] Starting deployment controller 
I0319 03:34:27.666452       1 controller_utils.go:1027] Waiting for caches to sync for deployment controller 
I0319 03:34:27.811727       1 node_ipam_controller.go:99] Sending events to api server. 
I0319 03:34:37.820363       1 range_allocator.go:78] Sending events to api server. 
I0319 03:34:37.820470       1 range_allocator.go:99] No Service CIDR provided. Skipping filtering out service addresses. 
I0319 03:34:37.820478       1 range_allocator.go:108] Node k8s-m1 has CIDR 10.244.2.0/24, occupying it in CIDR map 
E0319 03:34:37.820498       1 controllermanager.go:496] Error starting "nodeipam" 
F0319 03:34:37.820505       1 controllermanager.go:206] error starting controllers: failed to mark cidr as occupied: cidr 10.244.2.0/24 is out the range o/16
</pre>

**Comment by thockin** [comment]
In general we don't support changing the cluster CIDR - you might be able to expand it into adjacent spaces, but it has to be contiguous and we don't have a way to change nodes assignments on the fly.  You might be able to make it work by deleting all of your nodes and then changing that flag everywhere.

We have ideas on how to fix this but it's not really even at the design stage yet.

**Comment by gouki777** [comment]
i know,thanks.
