### ISSUE TITLE
How can I connect to the port in pod in outside network(port-forward?)

### ISSUE THREAD

**Issue by qiaozhi58** [kubernetes/kubernetes#75467]
The Istio which is based on Kubernetes, its official document said:
We can access the Jaeger UI by the following action:
kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=jaeger -o jsonpath=’{.items[0].metadata.name}’) 16686:16686 &

Then can use http://localhost:16686.
But the localhost is a Linux machine, there haven’t a browser.
I must open the browser on a remote machine.
How can I do?
thanks.

**Comment by qiaozhi58** [comment]
@neolit123 thanks.

**Comment by vllry** [comment]
@qiaozhi58 you can run that kubectl command from any authenticated system, EG a desktop computer with a GUI.

**Comment by thockin** [comment]
@qiaozhi58 as @vllry points out, this can run from a desktop, as lomg as you have `kubectl` that can reach the cluster.
