### ISSUE TITLE
Plugin "DefaultProvider" needs to be registered in BenchmarkScheduling 

### ISSUE THREAD

**Issue by denkensk** [kubernetes/kubernetes#75465]
**What happened**:
```
I0319 14:46:36.910486   11721 factory.go:341] Creating scheduler from configuration: {{ } [] [] [] 0 false}
I0319 14:46:36.910523   11721 factory.go:350] Using predicates from algorithm provider 'DefaultProvider'
F0319 14:46:36.910536   11721 util.go:72] Error creating scheduler: plugin "DefaultProvider" has not been registered
exit status 255
FAIL    k8s.io/kubernetes/test/integration/scheduler_perf   3.777s
```

**How to reproduce it (as minimally and precisely as possible)**:
```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-run=xxx -bench=BenchmarkScheduling"
```

**Anything else we need to know?**:
Maybe this error is introduced in by one commit (I haven't yet found it).  And we need init DefaultProvider when we setup Scheduler in `scheduler_perf`.

/sig scheduling
/kind bug
/assign
/cc @bsalamat

**Comment by bsalamat** [comment]
This is an interesting issue! I also see it on my machine, but as you pointed out, there is no recent change that could possibly cause this. In fact, we were in code freeze and no PR got merged into the schedule code base in the past ~couple of weeks. I wonder if a change in our build tools are made recently that introduced this.
