### ISSUE TITLE
i < --ginkgo.focus=[Feature:Performance]: syntax error

### ISSUE THREAD

**Issue by leeivan** [kubernetes/kubernetes#75460]
/kubemark/run-e2e-tests.sh

Kubemark master name: kubernetes-kubemark-master
Project: microservice-e2e-benchmark
Network Project: microservice-e2e-benchmark
Zone: us-central1-b
Trying to find master named 'kubernetes-kubemark-master'
Looking for address 'kubernetes-kubemark-master-ip'
Using master: kubernetes-kubemark-master (external IP: 35.202.65.239)
**./test/kubemark/run-e2e-tests.sh: line 50: ((: i < --ginkgo.focus=[Feature:Performance]: syntax error: invalid arithmetic operator (error token is ".focus=[Feature:Performance]")**
Setting up for KUBERNETES_PROVIDER="kubemark".

**Comment by neolit123** [comment]
@kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment]
```
go run hack/e2e.go -v --test --test_args="--ginkgo.focus=\[Feature:Performance\]"
```

works fine - this seem to be a problem with escaping.
