### ISSUE TITLE
kubectl delete|get `all foo` should delete the aliased resources named 'foo'

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#7547]
resource.Builder should allow `all/foo` and `all foo` since both are unambiguous.  Not super high priority, but makes `delete all` annoying when you want to delete several things that are named the same.

**Comment by bgrant0607** [comment]
Which doesn't work now? all/foo?

Ref. #5278

**Comment by smarterclayton** [comment]
`osc delete all foo` does not work.  `osc delete all/foo` is currently considered invalid by the builder although we should probably do the expansion.

----- Original Message -----

**Comment by alexbrand** [comment]
Is this still a valid bug? I can't tell if using `all` is still desired functionality. I get the following error message:
```
~> kubectl delete all nginx
error: you must specify only one resource
```

**Comment by smarterclayton** [comment]
I think it's still desired functionality - this happens a lot with services, deployments, and volumes in many cases (they're all named the same).  It's just not high priority.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-bugs

**Comment by shiywang** [comment]
I will take a look

**Comment by shiywang** [comment]
hi @smarterclayton , I made a little change, but I don't think this is want we want

``` console
$ ./kubectl get all nginx-deployment
NAME                  DESIRED   CURRENT   READY     AGE
rc/nginx-deployment   1981      1980      0         1m
NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/nginx-deployment   3         3         3            0           2m
Error from server (NotFound): pods "nginx-deployment" not found
Error from server (NotFound): services "nginx-deployment" not found
Error from server (NotFound): horizontalpodautoscalers.autoscaling "nginx-deployment" not found
Error from server (NotFound): jobs.batch "nginx-deployment" not found
Error from server (NotFound): replicasets "nginx-deployment" not found
$ ./kubectl delete all nginx-deployment
replicationcontroller "nginx-deployment" deleted
deployment "nginx-deployment" deleted
Error from server (NotFound): pods "nginx-deployment" not found
Error from server (NotFound): services "nginx-deployment" not found
Error from server (NotFound): horizontalpodautoscalers.autoscaling "nginx-deployment" not found
Error from server (NotFound): jobs.batch "nginx-deployment" not found
Error from server (NotFound): replicasets "nginx-deployment" not found
```
Could we add a filter in server side ?

**Comment by liggitt** [comment]
Expanding an alias to multiple types and then converting it to an operation on specific named objects will definitely lead to error cases like https://github.com/kubernetes/kubernetes/issues/7547#issuecomment-289513573

I don't really think this is a very predictable/usable feature, and I don't think adding error filtering to try to compensate makes it better or more understandable.

**Comment by liggitt** [comment]
Closing because of the usability issues that would be caused by adding this
/close

**Comment by lmktfy** [comment]
Relevant to https://github.com/kubernetes/website/issues/56291
