### ISSUE TITLE
Persistence Volume Azure Virtual Machine Scale Sets mount failed

### ISSUE THREAD

**Issue by suker200** [kubernetes/kubernetes#75478]
**What happened**:
Controller Manager can't request to attach the Disk (PV) to Virtual Machine from VMSS

I0319 12:50:40.197498       1 event.go:221] Event(v1.ObjectReference{Kind:"Pod", Namespace:"u001", Name:"u001-cassandra-csb-0", UID:"900a6abd-4a45-11e9-a32f-000d3a6cc167", APIVersion:"v1", ResourceVersion:"2242297", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' AttachVolume.Attach failed for volume "pvc-f852fa33-43b5-11e9-b42a-000d3a6cc167" : Attach volume "kubernetes-dynamic-pvc-f852fa33-43b5-11e9-b42a-000d3a6cc167" to instance "/subscriptions/xxxx/resourceGroups/qus7uw2-xxxx/providers/Microsoft.Compute/virtualMachineScaleSets/xxxx-qus7uw2l-k8sworker-7/virtualMachines/1" failed with compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Operation Put on Virtual Machine Scale Set VM Instance 1 of virtual machine scale set xxxx-qus7uw2l-k8sworker-7  is not allowed because the VM instance is not provisioned yet."

**How to reproduce it (as minimally and precisely as possible)**:
It just happened after some days work correctly.

**Anything else we need to know?**:
The Virtual Machine Scale Set VM Instance 1 started correctly with cloud-config and cloud-provider=azure are set. (Verified from Azure console and kubectl get node and ProviderID  was set when node join to cluster by kube-controller-manager)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Cloud provider or hardware configuration:  Azure
- OS (e.g: `cat /etc/os-release`): Centos7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: self-deployment
- Others:

/sig azure

**Comment by andyzhangx** [comment]
@suker200 does the attach disk to that instance operation still failed? I think it will retry for attach disk operation.

**Comment by suker200** [comment]
@andyzhangx  the attach disk still be failed. The retry still fail with same error "the VM instance is not provisioned yet" . The node provisioned successfully and join to the cluster (from azure console and kubectl get node )

**Comment by andyzhangx** [comment]
@suker200 could you go to azure portal to check whether that vmss instance is in `Running` state? The error comes from azure vmss RP, I doubt there is sth wrong with the vmss instance state.

**Comment by suker200** [comment]
@andyzhangx  thank you for fastly answer, I can sure that the server is running state from Azure Portal without any error. I'm thinking about Azure VMSS Response because it just happened yesterday after 2 weeks ran fine. What can I do to debug this case?

**Comment by andyzhangx** [comment]
@suker200 get the details from the log activity of that vmss and then file a ticket

**Comment by suker200** [comment]
@andyzhangx  can you point me the code which controller uses to query the vmss node info for this checking ? I will reproduce the query to test it

**Comment by andyzhangx** [comment]
https://github.com/kubernetes/kubernetes/blob/c27b913fddd1a6c480c229191a087698aa92f0b1/pkg/cloudprovider/providers/azure/azure_controller_vmss.go#L90

I see your cluster is based on centos, have you ever attached a disk to a vmss instance by k8s successfully before? could you provide the controller manager logs?

**Comment by suker200** [comment]
@andyzhangx  the attached disk still work correctly (about 2weeks) until yesterday it just failed after the old node is replaced by a new node. 

Firstly I thought it maybe relate to Sensitive Naming of Resource Group, I try to create with lowercase and it still failed. Checking from Azure Portal, it is `running` state. 

[kube-controller.log](https://github.com/kubernetes/kubernetes/files/2989337/kube-controller.log)

**Comment by andyzhangx** [comment]
@suker200 there is one way worth to try:
```
az vmss update-instances -g <RESOURCE_GROUP_NAME> --name <VMSS_NAME> --instance-id <ID(number)>
```

The above command will reset vmss instance state, in the before I obeserved that sometimes vm is in broken state while it still shows healthy in azure portal, and the above command could fix that issue, anyway it's worth a try.

**Comment by suker200** [comment]
@andyzhangx  I tried your command, still not work, I use `az vmss disk attach` to attach manually but still failed. Create new vmss doesn't help.

**Comment by andyzhangx** [comment]
@suker200 then it's an azure vmss issue, not a k8s issue.

**Comment by huydinhle** [comment]
@suker200 @andyzhangx I ran into this issue as well, is there a way to fix this with vmss?

**Comment by andyzhangx** [comment]
@huydinhle could you provide the detailed error info and k8s version?

**Comment by huydinhle** [comment]
@andyzhangx 
Kube version"
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Error from describing the pod
```
Warning  FailedAttachVolume  4m51s                attachdetach-controller           Multi-Attach error for volume "pvc-8c275903-b31c-11e9-852e-000d3afd0303" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume  59s (x9 over 3m9s)   attachdetach-controller           AttachVolume.Attach failed for volume "pvc-8c275903-b31c-11e9-852e-000d3afd0303" : Attach volume "kubernetes-dynamic-pvc-8c275903-b31c-11e9-852e-000d3afd0303" to instance "/subscriptions/c193c6d7-0cc4-42dd-8af2-394a4780ac11/resourceGroups/stage-westus2-enabling-chimp/providers/Microsoft.Compute/virtualMachineScaleSets/stage-kubernetesworkers-westus2-enabling-chimp/virtualMachines/9" failed with compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Operation Put on Virtual Machine Scale Set VM Instance 9 of virtual machine scale set stage-kubernetesworkers-westus2-enabling-chimp  is not allowed because the VM instance is not provisioned yet```

**Comment by andyzhangx** [comment]
@huydinhle there is sth. wrong with the vmss instance:
```
Operation Put on Virtual Machine Scale Set VM Instance 9 of virtual machine scale set stage-kubernetesworkers-westus2-enabling-chimp  is not allowed because the VM instance is not provisioned yet
```

I think you need to file an azure ticket to vmss team, thanks.

**Comment by huydinhle** [comment]
@andyzhangx thank you

**Comment by andyzhangx** [comment]
@huydinhle problem solved? could you also loop me in the support ticket, my mail: xiazhang@microsoft.com, I would like to know the RCA also, thanks.
