### ISSUE TITLE
Simplify Kubelet Volume Reconstruction

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#75484]
**What would you like to be added**:

To simplify the reconstruction code we should either 1) add checkpointing logic to the volume manager so that the entire state of the volume manager is persisted across restarted or 2) with each volume mount, store enough information (maybe as a JSON file) to recreate the entire volume object during reconstruction.

**Why is this needed**:

Kubernetes Kubelet Volume Manager has logic to try and "reconstruct" volumes from mounts to handle the case where a kubelet is restarted and the pods are deleted but the mounts still exist on the host and are not cleaned up.

The way this logic works today is that it tries to recover volume information from the mount path. Obviously the mount path does not contain enough information, so the reconstruction logic has lots and lots of hacks to try to work with minimal information. 

One big work around for this is that reconstruction tries not to add discovered mounts to "actual state" (because it doesn't have enough information to do so). This results in weird edge cases like https://github.com/kubernetes/kubernetes/pull/75458

To simplify the reconstruction code we should do one of the two options proposed above.

Both proposals have challenges that need to be considered and will add complexity, but they will simplify the reconstruction logic (which has been a source of lots and lots of bugs) to just add any discovered mounts on startup to the "actual state" and the volume manager will take care of unmounting them cleanly. 

CSI already writes a file per mount with extra info, but the reconstruction logic has to work for existing in-tree plugins in addition to CSI.

CC @jingxu97 
/sig storage

**Comment by bertinatto** [comment]
/assign
I'll take a look at this.

**Comment by bertinatto** [comment]
I'm currently working on some other stuff with tighter deadlines, so I think I can't work on this in the next weeks.

I'll get to it as soon as I can, but If someone wants to take this, feel free to take it.

**Comment by tedyu** [comment]
It seems option #2, the JSON file, seems to be better.
