### ISSUE TITLE
Enable kubectl port forward/exec to set tcp keep alive

### ISSUE THREAD

**Issue by JunSun17** [kubernetes/kubernetes#75488]
**What would you like to be added**:
This is part of work that relates to https://github.com/kubernetes/kubernetes/issues/63727

Actually also need for other long time session from kubectl, for example:
kubectl rollout status

@kubernetes/sig-cli-feature-requests

**Why is this needed**:

**Comment by JunSun17** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by wouterhund** [comment]
Please also consider `kubectl logs`

**Comment by marcecaro** [comment]
I am behind some proxies that tier down idle connections, so I would love to have this keep alive for port forwards.

**Comment by wouterhund** [comment]
/remove-lifecycle stale

This is still a huge problem on Azure with the LoadBalancer's tcp timeout.

**Comment by oz123** [comment]
We have a similar issue with Openstack Octavia loadbalancers. It would be great to see this added.

**Comment by Tawmu** [comment]
/reopen
/remove-lifecycle rotten

Would love to see this.
