### ISSUE TITLE
Remove make-symlink parameter in hyperkube in 1.16

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#75491]
Follow up for the deprecation we did in 1.14:
https://github.com/kubernetes/kubernetes/pull/74975

**Comment by Pothulapati** [comment]
I am willing to take this, if it is available :)

**Comment by dims** [comment]
@Pothulapati go for it. All you need to do is remove `makeSymlinksFlag` and associated code - https://cs.k8s.io/?q=makeSymlinksFlag&i=nope&files=&repos=kubernetes/kubernetes

**Comment by sodre** [comment]
@dims, I ended up getting hit with the removal of the --make-symlinks flag. I looked at the threads linked to the original PR, but I did not find the actual reason behind the removal. Do you recall was the reason behind removing that capability?

**Comment by dims** [comment]
@sodre the original request was from https://github.com/kubernetes/kubernetes/issues/69896#issuecomment-430398309
