### ISSUE TITLE
incorrect container memory metrics

### ISSUE THREAD

**Issue by ethinx** [kubernetes/kubernetes#75503]
**What happened**:
Just upgrade cluster to `v1.13.4`. Memory relevant metrics seems incorrect. In Pod spec, set limit to about **4Gi**

```
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 500Mi
```

but the metrics `container_spec_memory_limit_bytes` query from cadvisor/promethues, result is about **8.56GB** . As a result, the OOM behavior is incorrect. Beside `container_spec_memory_limit_bytes` the `container_memory_working_set_bytes` or `container_memory_rss`  is greater then RSS showed on result of top command on the host.

On old cluster, version, e.g. `v1.7.10`, the metrics seems right, memory limit is "7Gi", and `container_spec_memory_limit_bytes` is about **7.5GB** . 

**What you expected to happen**:
The metrics reflect the real memory status.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure, k8s version is `v1.13.4`, docker version `18.09.2`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.13.4**
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS 7.2
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7
- Install tools:
- Others: **DockerCE 18.09.2**

**Comment by ethinx** [comment]
@kubernetes/sig-instrumentation-bugs

**Comment by ethinx** [comment]
check in kubectl describe <node>

```
  Namespace                  Name                                         CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                         ------------  ----------  ---------------  -------------  ---
  default                   xxxxx-64dd958598-n2rsc                       0 (0%)        0 (0%)      500Mi (0%)       4Gi (6%)       25m
```

differ to docker stats

```
CONTAINER ID        NAME                                                                               CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
421793d3288f        k8s_xxxxx_xxxxx-64dd958598-n2rsc_default_f342e7b9-4af7-11e9-8f72-fa163ef04a42_0   2.30%               1.925GiB / 4GiB     48.14%              0B / 0B             0B / 0B             329
```

**Comment by pshirshov** [comment]
Hey, why this issue is closed? We have exactly the same problem - RSS as seen from host machine is lot lower than as all the k8 metrics...

**Comment by shadycuz** [comment]
I see similar, opening a new issue.
