### ISSUE TITLE
GCE 100 scalability test flakes

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#75509]
**Which jobs are failing**:
gci-gce-scalability

**Which test(s) are failing**:
Density test

**Since when has it been failing**:
Run 23995

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gci-gce-scalability

**Reason for failure**:
Api server cpu usage is over 2.2cpu limit.

**Anything else we need to know**:

**Comment by krzysied** [comment]
Based on changes between run 23994 and 23995, it looks like the issue can be caused by the https://github.com/kubernetes/kubernetes/commit/6f9bf5fe98bcc3b436fea4d6dd345a1502d20778.

**Comment by krzysied** [comment]
/cc @wojtek-t 

As a short term fix, I will increased the cpu limit for density tests. This will prevent test from flaking.

I think it will be good to also verify if  cpu usage increased in gce 5000 test.

**Comment by krzysied** [comment]
@smarterclayton There is a problem with increased cpu usage. It looks https://github.com/kubernetes/kubernetes/commit/6f9bf5fe98bcc3b436fea4d6dd345a1502d20778 could be the reason for this. Is this PR expected to increase apiserver cpu usage?

**Comment by smarterclayton** [comment]
Investigating, I wouldn’t expect it to impact flows that the scalability test hits.  It’s possible that we increased the amount of code on watch paths which caused a small increase in cpu, but anything detectable is not expected.

**Comment by smarterclayton** [comment]
```
$ git co 6f9bf5fe98bcc3b436fea4d6dd345a1502d20778^
$ go test ./vendor/k8s.io/apiserver/pkg/endpoints/ -test.bench=BenchmarkWatchHTTP -test.run=XXX
goos: darwin
goarch: amd64
pkg: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints
BenchmarkWatchHTTP-12    	   50000	     37514 ns/op
PASS
ok  	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints	2.276s

$ git co 6f9bf5fe98bcc3b436fea4d6dd345a1502d20778
Previous HEAD position was d7103187a3 Merge pull request #75054 from leakingtapan/ebs-wait
HEAD is now at 6f9bf5fe98 Merge pull request #71548 from smarterclayton/watch_converted
$ go test ./vendor/k8s.io/apiserver/pkg/endpoints/ -test.bench=BenchmarkWatchHTTP -test.run=XXX
goos: darwin
goarch: amd64
pkg: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints
BenchmarkWatchHTTP-12    	   20000	     68271 ns/op
```

Yes, looks like we allocate 100 times, more, looking at (it may have a very quick fix).

**Comment by smarterclayton** [comment]
Found it, opening a PR to fix shortly.

**Comment by smarterclayton** [comment]
Also, highlighted that the normal Get path has been allocating more than it should

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/75570 fixes AND makes get.

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubernetes/issues/73884

**Comment by spiffxp** [comment]
/remove-kind failing-test
This test isn't continually failing, but has a flake rate.  Using kind/flake instead

**Comment by wojtek-t** [comment]
This is pretty stable since the fix was merged.
