### ISSUE TITLE
go-inotify leaks file descriptors

### ISSUE THREAD

**Issue by cpuguy83** [kubernetes/kubernetes#75526]
**What happened**:

There are a couple of places where github.com/sigma/go-inotify is being used.
Unfortunately this package can leak file descriptors since `inotify_init` is called without `IN_CLOEXEC`.

This package seems to be a fork from an old golang.org/x package (which was removed) and hasn't been updated at all except for the fork itself.
(ping @sigma, maybe you would take a patch for this?)

fsnotify is recommend here, however fsnotify does not support all of the inotify watch flags being used, plus it adds a bunch that we aren't really interested in. Since fsnotify is more of a cross-platform package, I'm not sure how feasible it is to include support for these.

**Comment by sigma** [comment]
`github.com/sigma/go-notify` was really meant as a pure clone of the part of `golang.org/x/exp` that was preventing us from upgrading that particular dependency.
If we want to have patches to this code base, I think the right thing to do would be to have a proper fork under the `kubernetes-sigs` organization ?

**Comment by bgrant0607** [comment]
How about
https://github.com/kubernetes/utils/tree/master/third_party/forked/golang

**Comment by sigma** [comment]
> How about
> https://github.com/kubernetes/utils/tree/master/third_party/forked/golang

I think it's not ideal because cadvisor needs to consume the same code?

**Comment by thockin** [comment]
Doing a bit of homework:

inotify is a "notify me when X happens" API.

fsnotify is a "notify me of all events" API.

It looks like Kubelet wants to know if someone opens a file (the lockfile).  fsnotify does not support the IN_OPEN flag at all.  It is unclear whether fsnotify wants to support that or not.  At least one issue was files on it, and closed with no merge.

**Comment by sigma** [comment]
@thockin it felt like a big dependency to add to cadvisor, but I just had a look and they already consume another package from it. So I guess I withdraw my concern :)

**Comment by cpuguy83** [comment]
fsnotify has had spotty support over the last couple of years just because of the primary maintainer being busy with other things.

**Comment by dims** [comment]
`DONE!`

/close

**Comment by cpuguy83** [comment]
Thanks!
