### ISSUE TITLE
kubectl get pods on non-existing namespaces does say anything that the namespace does not exist

### ISSUE THREAD

**Issue by mitpwd** [kubernetes/kubernetes#75537]
Command:
kubectl get pods -n non-existing-namespace

Actual response:
No resources found.

Expected message:
Namespace not found.

**What would you like to be added**:
Exception message to be capturing the issue of a non-existing namespace.
"Namespace not found."

**Why is this needed**:
Address issues when users mistype a namespace. Assumption is there are no pods and wrong decision can be taken.

**Comment by WanLinghao** [comment]
It is for security purpose, it prevents unauthorized user sniff the existence  of namespaces.

**Comment by jayunit100** [comment]
I'd like to suggest that we possibly report 

...  instead of `No resources found in x namespace`, I'd like it if we  reported:

- `No resources found`
- `No resources found in the "x" namespace` 

Both of these imply that the namespace x may or may not exist.

**Comment by fykaa** [comment]
this thing has caused so much confusion almost forever..... but I get it if its for security reasons
