### ISSUE TITLE
New pod stuck at PodInitializing and does not restart on rebooted node in K8s 1.13

### ISSUE THREAD

**Issue by snowmansora** [kubernetes/kubernetes#75542]
**What happened**:
Rebooted a K8s 1.13 node (it is also a master node).
A new pod is started on the rebooted node and stuck at PodInitializing.
kubectl describe pod shows:
```
  Warning  FailedCreatePodSandBox  16m   kubelet, k8s-node-002  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "12cea40a96a528322a0bb8d6a043677576af744d65ea79ad54746a9a215695ba" network for pod "etcd-5pmzptwrwd": NetworkPlugin cni failed to set up pod "etcd-5pmzptwrwd_cluster1" network: Multus: Err in tearing down failed plugins: Multus: error in invoke Conflist add - "cni0": error in getting result from AddNetworkList: open /run/flannel/subnet.env: no such file or directory
```
kubelet on the rebooted node keeps on printing:
```
Mar 21 10:44:50 k8s-node-002 kubelet: I0321 10:44:50.379122    1437 kuberuntime_manager.go:427] Sandbox for pod "etcd-5pmzptwrwd_cluster1(68eadeba-4bc3-11e9-bc95-1241756354f2)" has no IP address.  Need to start a new one
```
But it never start a new one, hence pod stuck at PodInitializing.

**What you expected to happen**:
Pod not to stuck at PodInitializing.

**How to reproduce it (as minimally and precisely as possible)**:
On a 3 nodes clusters (K8s 1.13), deploy etcd-operator with a etcd cluster of size 3.
Reboot a node, etcd-operator will create a new etcd pod on the rebooted node.
Newly created etcd pod stuck at PodInitializing, e.g.:
```
cluster1         etcd-5pmzptwrwd                                                   0/1     Init:0/1   0          28m     <none>           k8s-node-002   <none>           <none>
```

**Anything else we need to know?**:
When using K8s 1.12.5, we don't see such problem.
We tried both 1.13.0 and 1.13.4 and we see this problem quite frequently (not 100% but high chance).
Not sure it is related or not: We see a lot of FailedCreatePodSandBox events when describing the new pod on K8s 1.12.5. But we only see one FailedCreatePodSandBox event on K8s 1.13.
Also, if we delete the stuck pod, it can be created again successfully on the same node.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7.5
- Kernel (e.g. `uname -a`): 3.10.0-862.2.3.el7.x86_64
- Install tools:
- Others:

**Comment by snowmansora** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by k82cn** [comment]
@kubernetes/sig-node-bugs 

If Pod keep in "PodInitializing" phase, scheduler can not re-schedule it :)

**Comment by errogaht** [comment]
> @kubernetes/sig-node-bugs
> 
> If Pod keep in "PodInitializing" phase, scheduler can not re-schedule it :)

ok but in this case i have to manually delete pod in replica set.
and it makes k8s not autonomous system. i need to set up alerts to detect stuck pods in PodInitializing state and then manuall delete. Marketing materials said that k8s can automatically heal, but in this case it is not true
