### ISSUE TITLE
Unknown container runtime version

### ISSUE THREAD

**Issue by sashayakovtseva** [kubernetes/kubernetes#75549]
**What happened**:
I am running k8s cluster with Singularity container runtime via [Singularity-CRI](https://github.com/sylabs/singularity-cri). After configuring `kubectl` and running `kubectl get no` & `kubectl describe no <node-name>` I have the following:

```
.....
Container Runtime Version:  singularity://Unknown
....
```

even though in kubelet logs I can see the line with correct version:
```
I0321 11:40:41.949782     429 kuberuntime_manager.go:197] Container runtime singularity initialized, version: 3.1.0-35.ge15c551
```

**What you expected to happen**:

Expected to have

```
.....
Container Runtime Version:  singularity://3.1.0-35.ge15c551
....
```

in `kubectl describe no <node-name>` output.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce it you'll need to have [Singularity installed](https://www.sylabs.io/guides/3.0/user-guide/installation.html). After that the easiest way to check is to use Sykube as described [here](https://www.sylabs.io/guides/cri/1.0/user-guide/sykube.html).

**Anything else we need to know?**:

Source code where version is returned [here](https://github.com/sylabs/singularity-cri/blob/master/pkg/server/runtime/runtime.go#L178)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
Do you see `Get remote runtime version failed` in the logs?

**Comment by sashayakovtseva** [comment]
No, instead I have this in the beginning of kubelet logs:
```
I0321 16:06:43.331854     438 kuberuntime_manager.go:197] Container runtime singularity initialized, version: 3.1.0-35.ge15c551
, apiVersion: 3.1.0-35.ge15c551
W0321 16:06:43.332096     438 probe.go:270] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
I0321 16:06:43.334425     438 server.go:1013] Started kubelet
```

**Comment by sashayakovtseva** [comment]
Any updates on this issue?

**Comment by sashayakovtseva** [comment]
@dims Still having the same issue on 1.14. Any help or comments? I confirm kubelet logs have correct runtime version:
```
# journalctl  -u kubelet | grep "Container runtime"
Apr 19 07:59:26 node01 kubelet[2195]: I0419 07:59:26.311029    2195 kuberuntime_manager.go:210] Container runtime singularity initialized, version: 3.2.0-rc1.36.g52daadc
```

**Comment by dims** [comment]
@sashayakovtseva can you check if you are seeing any errors on the singularity CRI service logs? ( coming from this line https://github.com/sylabs/singularity-cri/blob/master/pkg/server/runtime/runtime.go#L183 )

**Comment by sashayakovtseva** [comment]
@dims No errors from Singularity-CRI side

**Comment by dims** [comment]
weird!!! thanks for confirming @sashayakovtseva i'll have to install the CRI to debug ... unless someone else want to try to do that before me.

**Comment by sashayakovtseva** [comment]
I tried to debug kubelet but it looks like during `kubectl describe no` it already receives this `Unknown` version from a different k8s component (is that API server? not sure which component responses to kubelet in that case). Searching k8s source code didn't help much. Hope that helps you and thank you for response!

**Comment by sashayakovtseva** [comment]
@dims Hello! Sorry for bothering, but maybe you have any updates on that?

**Comment by dims** [comment]
@sashayakovtseva nope, i have not looked at it since then. sorry.

**Comment by sashayakovtseva** [comment]
Found issue, cri respond with a new line at the end of the version, e.g. "v3.0.0\n", so kubelet was unable to parse it correctly.
