### ISSUE TITLE
Secrets should be read-only by root

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#7554]
Well designed applications run as non-root, so having secrets only readable by root would improve the levels of defense in depth.

**Comment by erictune** [comment]
Are you talking about the secrets files on the /tmpfs from the node's view?  I agree those should be readonly.  

Or are you talking about the mount of the secret volume seen inside the container?  Those I don't think need to be readonly by root be default.  There is usually only one application inside the container, and it needs to run as a user that can access the secret, so it can use it.

**Comment by aronchick** [comment]
It's the latter - I can see there being two types of secrets - one that needs accessing by the application running on the container, and one that may be useful in one-time setup. The one-time setup ones could be more sensitive and need hiding from non-root.

**Comment by erictune** [comment]
@pmorie you had mentioned settable secret file permissions.  Anything to add to this conversation?

**Comment by pmorie** [comment]
@erictune @aronchick I missed the tag into this issue.  We've gone around about settable permissions for secrets -- perhaps this is another data point we can use to inform that discussion.  @aronchick could you give an example of a secret that shouldn't be readable by non-root UIDs?

**Comment by aronchick** [comment]
@pmorie Sure - let's say I wanted to do something that required root access to the box / elevated access to my database as the container started (e.g. run a migration, check a mount, etc). I would not want this readable by the account that runs the web server on that container, but I would want it to be available on the container when it starts.
