### ISSUE TITLE
privileged containers not showing up as privileged at docker level

### ISSUE THREAD

**Issue by DevasiaThomas** [kubernetes/kubernetes#75559]
**What happened**:
Started a container under a pod using the below in the pod yml
```
spec:
   securityContext:
          privileged: true
```
I can perform privileged actions in the container and hence it is privileged. But when I query docker to check if it is privileged using the below, it returns false.

`docker inspect --format='{{.ID}} {{.HostConfig.Privileged}}' <containerID>`

**What you expected to happen**:
The docker inspect command should have returned that the container is privileged. 

**How to reproduce it (as minimally and precisely as possible)**:
Run any pod with the above security context and use the container ID of the containers that come up in the  shared docker inspect command.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client 1.13.4
Server 1.13.4

- OS (e.g: `cat /etc/os-release`):
RHEL 7.2

- Kernel (e.g. `uname -a`):
Linux 3.10.0-327.el7.x86_64 

- Docker version
  17.09.0-ce

**Comment by WanLinghao** [comment]
Test OK in my environment, check if you test the /pause container.

**Comment by DevasiaThomas** [comment]
@WanLinghao you want me to check if the /pause container is priviliged??

**Comment by WanLinghao** [comment]
No, you should check the job running container rather than /pause container. I just gave a little tip to you to make sure you didn't check the wrong container...

**Comment by DevasiaThomas** [comment]
@WanLinghao My utility isn't K8 or OSE aware. it works on the docker layer and filters out privileged containers using the above docker inspect and i'm seeing containers started up as part of pods using the spec:securityContext:privileged:true turning up as false in docker inspect.

**Comment by pswica** [comment]
Could this be due to selinux--can you run `getenforce`? If so, does the issue persist if you test by temporarily disabling selinux and trying again?

**Comment by DevasiaThomas** [comment]
@pswica Currently `sestatus` shows the below

```
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          disabled
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```
It says permissive, do you think I would need to disable it and try again?  I'm open to try it, but from what i can tell a hard disable requires a reboot. I have people working on this openshift env

**Comment by pswica** [comment]
Given that it's permissive (e.g. selinux just logs violations, it doesn't enforce them), I don't think it's an selinux issue. Is this affecting all privileged containers or only one in particular?

**Comment by DevasiaThomas** [comment]
Okay, A system restart just fixed the behavior I was seeing. And I can't seem to reproduce the issue anymore. I'm closing this, will reopen this if I see it again down the line.
