### ISSUE TITLE
Docs need to be updated for recent change to default Secret and ConfigMap strategy

### ISSUE THREAD

**Issue by ficcaglia** [kubernetes/kubernetes#75554]
**What happened**:
PR #74755 made the default TTL vs Watch, but docs in https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod still say:

> It can be either propagated via watch (default), ttl-based, or simply redirecting all requests to directly kube-apiserver. 

**What you expected to happen**:
The docs should reflect the default is ttl-based as such:

It can be either propagated via watch, ttl-based (default), or simply redirecting all requests to directly kube-apiserver.

**Comment by ficcaglia** [comment]
@kubernetes/sig-docs

**Comment by josiahbjorgaard** [comment]
Can I take this issue?

**Comment by wojtek-t** [comment]
Sorry missed that.
I opened: https://github.com/kubernetes/website/pull/15531 and https://github.com/kubernetes/website/pull/15532 for that.

**Comment by wojtek-t** [comment]
Both were merged. Closing.
