### ISSUE TITLE
Idle master constantly burns CPU/disk polling itself

### ISSUE THREAD

**Issue by Foritus** [kubernetes/kubernetes#75565]
**What happened**: Setting up a Kubernetes cluster using kubeadm (using this guide: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ ), the master constantly polls itself (observable via a -v=4 log from the kube-apiserver pod). This load seems to average 10-11 TPS against the api server and subsequently etcd. This places a lot of uneccessary stress on the CPU and IO subsystems. See [api-server.log](https://github.com/kubernetes/kubernetes/files/2994288/api-server.log) for a log of the observed behaviour.

**What you expected to happen**:
For Kubernetes to not burn lots of system resources on pointless busy work. My goal as a user is to run my workloads, not just to run kubernetes :)

**How to reproduce it (as minimally and precisely as possible)**:
Install a small cluster by following this guide: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
Overview of steps to set up master:

1. sudo apt update
2. sudo apt install apt-transport-https
3. curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
4. echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
5. sudo apt update
6. sudo apt install kubeadm kubelet kubectl
7. sudo kubeadm init --token-ttl=0
8. kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
9. Join some workers by following steps 1-6 and then running the join command output from step 7 on them.

Let the cluster fully initialise (takes a minute or two for all the CNI stuff to initialise).

Observe the master has high CPU usage despite doing very little.

If you set the api-server log verbosity to 4 (edit /etc/kubernetes/manifests/kube-apiserver.yaml and add - --v=4 to the arguments list), you will see logs that look a lot like these: [api-server.log](https://github.com/kubernetes/kubernetes/files/2994288/api-server.log)

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: On prem (at home). 3 virtual machines (1 master, 2 workers) and 3 raspberry pis (all workers).

- OS (e.g: `cat /etc/os-release`):  Ubuntu 18.04.2 LTS (Bionic Beaver)

- Kernel (e.g. `uname -a`): Linux kube-master-1 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: apt/dpkg, kubeadm

**Comment by neolit123** [comment]
> the master constantly polls itself (observable via a -v=4 log from the kube-apiserver pod).

/sig api-machinery

**Comment by lavalamp** [comment]
Thanks for the example log. How big is the machine you're running this on? How much CPU was apiserver using? RAM?

apiserver / controllers don't use disk for things other than logs, so setting -v=4 may actually be the cause of that.

The traffic in the log file appears to include a number of controllers doing dynamic discovery. It's not clear to me if that's more often than expected or not. @yliaog might know.

**Comment by Foritus** [comment]
The disk load appears to be entirely caused by etcd, presumably a second-order effect from the api server chatting to it a lot? Docker stats output: ![image](https://user-images.githubusercontent.com/601930/54958347-51811180-4f4d-11e9-8ce9-3f6132af73b8.png)

The master runs in a VM with 2 cores and 4GB of RAM. Kuberenetes is using about 700MB of that, the rest is free/disk cache. The host box is a 16 core Xeon with 64GB of ram. The underlying storage is a pair of NVME SSDs running ZFS in RAID 1.

**Comment by lavalamp** [comment]
The only thing there that seems potentially unusual is the amount of I/O that etcd has done, but if this system has been running for a long enough time, then that's to be expected. E.g., node status updates and events cause churn, more or less by design.

The informers I mentioned are all hitting endpoints that don't talk to etcd (just reading discovery apis).

If you want to figure out what exactly is in your etcd, take a look at: https://github.com/jpbetz/auger

Kubernetes hasn't really optimized for the "scale down case". So, yeah, the control plane overhead looks bad as a percentage of the cluster if we're talking about < 5 node clusters. You could maybe scale it down to half that CPU / RAM if you just have 2 nodes, at that point you'd be at or near the minimum system to run the control plane.

**Comment by Foritus** [comment]
Closing as "hungry by design" then :)

**Comment by lavalamp** [comment]
At least for the moment. Thanks for understanding :)

(I'm definitely open to changes which reduce resource usage in small clusters, btw--it's just not been a priority yet.)

**Comment by wuestkamp** [comment]
There are quite a few of issues about high CPU when using Kubernetes for local development:

https://github.com/docker/for-mac/issues/2601
https://github.com/docker/for-mac/issues/3065

Could these have something todo with this ticket?

**Comment by ranman** [comment]
As a follow up to @wuestkamp 's comments - the high CPU usage and constant work when running no containers makes local development very difficult and destroys battery life on laptops.

**Comment by HarryWeppner** [comment]
This is *the* major complaint from our users as well and hindering K8s adoption in a significant way.

**Comment by planetf1** [comment]
++ for issue above. I'm fortunate enough to have easy access to a cloud environment, but for getting people onboarded with the idea of using k8s - or using k8s to showcase what I work in, it's a real inhibitor

**Comment by jwatte** [comment]
People with MacBooks in the office complain about this too. People with windows/linux/vmware laptops seem to be doing better. Maybe they're just less concerned about battery life?
Some setting that makes things poll, say, once every 2 seconds instead of 10 times a second would be useful.

**Comment by tekumara** [comment]
I'm experiencing 50% CPU usage when Kubernetes on Docker Desktop Mac is idle, no running pods.

I'm using Docker 2.3.3.0 (46574) Edge with Kubernetes v1.18.3.

I've given the VM 4G RAM, 1GB swap. 

After a factory reset, *com.docker.hyperkit* on the host uses ~5% CPU .

When I enable Kubernetes, *com.docker.hyperkit* CPU jumps to 50%. 

Using *justincormack/nsenter1* to enter the the VM, I see CPU is idle but there's regular I/O:
```
$ iostat -d -c -z -m
Linux 4.19.76-linuxkit (docker-desktop) 	07/11/20 	_x86_64_	(6 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.50    0.00    1.71    0.08    0.00   96.71

Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
vda              18.05         0.00         1.16          3       1606
vda1             12.83         0.00         1.16          2       1606
sr0               1.86         0.14         0.00        194          0
sr1               0.01         0.00         0.00          0          0
sr2               1.40         0.10         0.00        143          0

```

I've enabled *Kubernetes -> Show system containers*. On the host I see the k8s API server is using the most CPU:
```
$ docker stats --format "table {{printf \"%.25s\" .Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}" --no-stream
NAME                        CPU %               MEM USAGE / LIMIT     NET I/O             BLOCK I/O
k8s_compose_compose-78f95   0.09%               8.324MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_vpnkit-controller_vpn   0.00%               15.78MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_compose_compose-api-6   0.20%               24.14MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_storage-provisioner_s   0.40%               7.383MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_POD_compose-78f95d4f8   0.00%               324KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_compose-api-6ffb8   0.00%               288KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_vpnkit-controller   0.00%               340KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_storage-provision   0.00%               296KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_coredns_coredns-5644d   0.61%               7.309MiB / 170MiB     0B / 0B             0B / 0B
k8s_coredns_coredns-5644d   0.59%               7.562MiB / 170MiB     0B / 0B             0B / 0B
k8s_kube-proxy_kube-proxy   0.06%               9.938MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_POD_coredns-5644d7b6d   0.00%               352KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_coredns-5644d7b6d   0.00%               320KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_kube-proxy-2kwlf_   0.00%               300KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_kube-controller-manag   2.50%               34.84MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_kube-apiserver_kube-a   6.88%               359.6MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_etcd_etcd-docker-desk   2.96%               27.32MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_kube-scheduler_kube-s   0.08%               11.62MiB / 3.848GiB   0B / 0B             0B / 0B
k8s_POD_kube-controller-m   0.00%               324KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_kube-apiserver-do   0.00%               324KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_etcd-docker-deskt   0.00%               308KiB / 3.848GiB     0B / 0B             0B / 0B
k8s_POD_kube-scheduler-do   0.00%               312KiB / 3.848GiB     0B / 0B             0B / 0B
```

**Comment by arifwn** [comment]
Anyone experiencing high idle cpu usage when running kubernetes on docker mac can try running k3s via [k3d](https://github.com/rancher/k3d) instead. It's practically cut the idle cpu usage by half, down from ~50% to ~25%. Still not ideal, but better than nothing.

**Comment by talj-us-ibm-com** [comment]
It is interesting that this issue is closed but there was/is not a resolution.

**Comment by talj-us-ibm-com** [comment]
"tune the lease flags on controller manager & scheduler"

Do you mean these parts of kubernetes:

https://v1-18.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
https://v1-18.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

If yes, which flags/settings?  I see 'lease' mentioned in terms of leader election.

**Comment by lavalamp** [comment]
Yeah, change the lease duration to like 120 seconds and the renew to like 110 seconds, for example, and see if that makes a difference.

**Comment by lavalamp** [comment]
Actually you could try setting just leader-elect to false.

There's probably many such things that can be reduced or disabled when you don't need the system to respond to faults quickly.

**Comment by devZer0** [comment]
https://github.com/ubuntu/microk8s/issues/2007

**Comment by devZer0** [comment]
https://github.com/ubuntu/microk8s/issues/1567

**Comment by mc0** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/89936 a while back and I believe it would help with the overall CPU usage (for projects like kind/minikube).

**Comment by fs30000** [comment]
> I filed #89936 a while back and I believe it would help with the overall CPU usage (for projects like kind/minikube).

mc0, got any more tips for lowering the cpu usage? This is insane.

**Comment by MichaelZuo** [comment]
Since it's been over 4 years, presumably the fix isn't simple. So is there a more feasible alternate method?

**Comment by Kazmirchuk** [comment]
+1! recommendations on how to make kube-apiserver consume less CPU in a development kubeadm setup would be much appreciated. With K8S 1.32.4 it fluctuates around 7-9% in htop, and combined with kubelet's 4-6% this is enough to keep my laptop's fans spinning rather loud.
