### ISSUE TITLE
Cleanup Advanced Audit testing

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#75563]
1. Most of the functionality covered by the advanced audit e2e tests should be migrated to the audit integration tests.
2. The e2e tests should reduce the coverage, and just test a few core cases. Those cases should be robust to failure (retry on failure).
3. ~~Once dynamic audit graduates to beta, the advanced audit tests should be migrated to dynamic audit to remove dependence on the static profile & log rotation.~~

/sig auth
/priority important-soon
/milestone v1.15
/assign @pbarker @x13n

**Comment by liggitt** [comment]
this cleanup is not release-blocking

/milestone v1.16

**Comment by ZhiFeng1993** [comment]
@tallclair  is this one still active?

**Comment by tallclair** [comment]
Yes, this still needs to be done.

**Comment by stlaz** [comment]
@tallclair The audit tests seem to have been removed in f5490cb5c8ca4d1dece6107f298be23fa0b33f22, should this issue be closed? The description at https://github.com/kubernetes/kubernetes/pull/94050#issue-468852281 suggests that it's already done.

**Comment by tallclair** [comment]
Yep, thanks.
