### ISSUE TITLE
Add-On manager should not be creating kube-system namespace

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#75567]
**What happened**:
Add-on manager uses kubectl apply to create the kube-system namespace at start-up. 
This is redundant because the kube-apiserver creates the namespace in NewBootstrapController. 
This is a problem because if someone uses apply to make changes to the kube-system namespace, the add-on manager will wipe out these changes. 

**What you expected to happen**:
Kube-APIServer has the sole responsibility of creating the kube-system namespace.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply a label to the kube-system namespace.
restart the add-on manager.
Note the labels have been removed.

**Anything else we need to know?**:
/sig api-machinery

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
[https://github.com/kubernetes/kubernetes/blob/c48ed1c5aca6e06b6a3d70d5f189216df3150379/cluster/addons/addon-manager/kube-addons.sh#L213-L214](https://github.com/kubernetes/kubernetes/blob/c48ed1c5aca6e06b6a3d70d5f189216df3150379/cluster/addons/addon-manager/kube-addons.sh#L213-L214)

the contention script wipes out namespace ^^

**Comment by yliaog** [comment]
i guess it is intentional to have the addon manager to ensure kube-system is not modified, it tries to avoid the case that some cluster admin accidentally delete kube-system that result in a non-functional cluster.

**Comment by cheftako** [comment]
The add-on manager will only perform the check when it restarts. The API Server will also perform this check when it restarts. I think we should only have 1 system responsible for this and I believe that system should be the API server.

**Comment by rightblank** [comment]
trying to have my first contribute here, so is it proper to have the kube-system existence checked before applying the yaml file to create the kube-system namespace once again?

**Comment by cheftako** [comment]
@rightblank The Kube API Server will check for the existence of the kube-system namespace and create it if absent. It does all of this using client-go requests. The Add-On manager is the only system creating the kube-system by applying (a private) yaml file. I believe the correct fix here is to remove the Add-On managers attempts to create the kube-system namespace entirely. This is especially important if a user writes a CI/CD controller to apply their desired state to the kube-system namespace. I would argue the CI/CD is correct but the add-on manager will randomly wipe out the users changes. The API Server on the other hand will not.

**Comment by rightblank** [comment]
@cheftako , thanks for your help, so i will remove that line and pull a request later

**Comment by hprateek43** [comment]
Trying to get my first PR here. Is the issue still open ?

**Comment by cheftako** [comment]
@hprateek43 The issue is still open. You may want to check on https://github.com/kubernetes/kubernetes/pull/75769 though as @rightblank was trying to fix the issue with that PR.

**Comment by hprateek43** [comment]
@cheftako I am planing to introduce a check for kube-system namespace in line 136 in start_addon function to explicitly skip the kube-system namespace creation. Will it be a good approach ? Or should I comment out the line 214 itself that will prevent the trigger of namespace creation?
