### ISSUE TITLE
"OR" suppport for fieldselector

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#75596]
I want to find events for a lot of different objects and not do lots of api requests, can we add some kind of "OR" support ?

`kubectl get events --field-selector 'involvedObject.name=(foo,bar)`

**Comment by grosser** [comment]
/sig api-machinery
@kubernetes/sig-api-machinery-feature-requests

**Comment by yliaog** [comment]
there is support for label-based selection in api server, but not field-based. adding field based selection is non-trivial, it could add significant extra resource requirements on api server.

a pattern in kubernetes is for clients to *watch* for certain resource, and do whatever custom filtering, logic on client side.

there is a prospoal for events redesign in case it's helpful.
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/events-redesign.md

**Comment by grosser** [comment]
thx!
watching is not really an option since my resources don't have much in common, so I'd have to watch all events :(

**Comment by grosser** [comment]
also events don't seem to have labels by default, so selecting by label does not work ?
... would be interesting if they had the labels of the resource that caused them

**Comment by lavalamp** [comment]
Yeah, at the moment the expectation is that the client watches all events and filters locally.

Plumbing labels through is interesting, but potentially a ton of work because every place that triggers an event would have to change.
