### ISSUE TITLE
e2e and mandatory command line flags

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#75590]
**What happened**:

https://github.com/kubernetes/kubernetes/pull/69105 moved flag definitions from a function in the E2E test framework (`RegisterCommonFlags`) into the init section of some test packages. That's okay for the Kubernetes E2E test suite where those flags traditionally have been part of the command line.

But now @deads2k pointed out (https://github.com/kubernetes/kubernetes/pull/69105#pullrequestreview-216944509) that in his usage of the tests, he was only using Viper for setting the test configuration and doesn't want the configuration options to show up in the command line.

**What you expected to happen**:

Adding to the global command line must be entirely controlled by the owner of the actual binary. Packages should never directly define flags.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13 and (currently) the 1.14 release candidate

**Comment by Dabbeeru** [comment]
Can you please help me for the below error


Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'                                                                          Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'                                                                          Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'                                                                          Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'
--





apiVersion: v1                                                                                                                                                               clusters:                                                                                                                                                                    - cluster:                                                                                                                                                                       server:                                                                                            certificate-authority-data: " RYRFRFNU1ETXlNakEzTWpBME9Gb1hEVEk1TURNeE9UQTNNakEwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUlOCmk4SlArbENjc2 xGWGI1K3E5VmpZWmgxU2ZYK05FY1dCaE5lNEVvVi8vQ3JTYWtPems2bU1qRGpmVnEwbXZNaDAKSmdnZkFMMG9SOFFhKzRGK3h2d2RpSzdGd0J5YzYyZ1ZPd1NlNWl3dnl2V3ZnT2tlaFMyWEhRNlk0RzQ2T3FpaQpuQXM1VWovZk x0WjVpNEVHci9ML09ibi9VTFlkSnZkYzBhbTZNdnZBdmRvYXIzQVpLZkdlN0paUXBOUHRGaS85CjEvSkhuOU51aUpodjB3S1BqeXVNcTJTV1l1aVNSU3lJU0lGNDRDY05XRGhuaEQyYnpsLzN1LytVcnZhUDVzOEcKVTFLZWxLUF ZGa1A3cnE3UERSU1RYU3E0QUdLT2krZXdXcFZQZ0Y2ZHhKR0dPdndSZS9PK0VldFhDQnVTcUtjaQpTeHBMcWYzWk5yUTdrelpuMzlrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU 1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHMUZuVDN5K1lITmJWYjR2NlFQWVdUdkpBQU0KdzlpTW5ZTk5OVkFWLy9ZVmpVeGdMYk1LU3FjY2QxVW1UY3laY0JUdVBXYTN5dnZDTGVNeVZzaTZiUjFWclZ0SgpHN2pNTF VSZ1RIMEp1eUE3WERmbjFiZnhzODM5VVFZa2RWcm13QmdyNVFqSlJTR1piTGg3ZlZmM1pnWUErUms0ClVXR2xjOXNyaDV2TGJuYkRiSGp2VW54TU9SMnNTK0EvTWR0SWFhd3NKTUJROEEvQmpCTDEzZzVmQjg2T3F2ZXQKeUhVM0 JSd05KYzdpQXYwSTYyaWNEZWdMZHJQZHZtVjc3bmJ5bzgzQnhWUGJxdjlXY1FnaXlRZ0lwdGpzUWhEcQpGTXE2ZnNPT1JESlVsbU1aV2VhVmhUVHJ4TDNvMVNLSFpRQnN6cEJCbHlUYytkeEVxalVuWDFVRWlyaz0KLS0tLS1FTk QgQ0VSVElGSUNBVEUtLS0tLQo=>"                                                                                                                                                   name: kubernetes                                                                                                                                                           contexts:                                                                                                                                                                    - context:                                                                                                                                                                       cluster: kubernetes                                                                                                                                                          user:                                                                                                                                                                      name: aws                                                                                                                                                                  current-context: aws                                                                                                                                                         kind: Config                                                                                                                                                                 preferences: {}                                                                                                                                                              users:kubernetes                                                                                                                                                             - name: aws                                                                                                                                                                    user:                                                                                                                                                                          exec:                                                                                                                                                                          apiVersion: client.authentication.k8s.io/v1alpha1                                                                                                                            command: heptio-authenticator-aws                                                                                                                                            args:                                                                                                                                                                          - "token"                                                                                                                                                                    - "-i"                                                                                                                                                                       - ""                                                                                                                                                                  # - "-r"                                                                                                                                                                     # - ""
--

**Comment by Dabbeeru** [comment]
can you please assist me

**Comment by pohly** [comment]
@Dabberru looks like a syntax error in your config. That is unrelated to this issue. Please take your question to place where users of Kubernetes can get help (https://kubernetes.io/community/ or your vendor).

**Comment by pohly** [comment]
@Dabbeeru please delete your comment.
