### ISSUE TITLE
Hi Am getting error in .kube confige file

### ISSUE THREAD

**Issue by Dabbeeru** [kubernetes/kubernetes#75592]
Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'                                                                          Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'                                                                          Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'                                                                          Error loading config file "/home/ec2-user/.kube/config": yaml: line 15: could not find expected ':'
--

apiVersion: v1
clusters:
- cluster:
    server: <https://8FC560AAF4318E027FE0060EAC397455.yl4.us-east-2.eks.amazonaws.com>
    certificate-authority-data: "<LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXlNakEzTWpBME9Gb1hEVEk1TURNeE9UQTNNakEwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUlOCmk4SlArbENjc2xGWGI1K3E5VmpZWmgxU2ZYK05FY1dCaE5lNEVvVi8vQ3JTYWtPems2bU1qRGpmVnEwbXZNaDAKSmdnZkFMMG9SOFFhKzRGK3h2d2RpSzdGd0J5YzYyZ1ZPd1NlNWl3dnl2V3ZnT2tlaFMyWEhRNlk0RzQ2T3FpaQpuQXM1VWovZkx0WjVpNEVHci9ML09ibi9VTFlkSnZkYzBhbTZNdnZBdmRvYXIzQVpLZkdlN0paUXBOUHRGaS85CjEvSkhuOU51aUpodjB3S1BqeXVNcTJTV1l1aVNSU3lJU0lGNDRDY05XRGhuaEQyYnpsLzN1LytVcnZhUDVzOEcKVTFLZWxLUFZGa1A3cnE3UERSU1RYU3E0QUdLT2krZXdXcFZQZ0Y2ZHhKR0dPdndSZS9PK0VldFhDQnVTcUtjaQpTeHBMcWYzWk5yUTdrelpuMzlrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHMUZuVDN5K1lITmJWYjR2NlFQWVdUdkpBQU0KdzlpTW5ZTk5OVkFWLy9ZVmpVeGdMYk1LU3FjY2QxVW1UY3laY0JUdVBXYTN5dnZDTGVNeVZzaTZiUjFWclZ0SgpHN2pNTFVSZ1RIMEp1eUE3WERmbjFiZnhzODM5VVFZa2RWcm13QmdyNVFqSlJTR1piTGg3ZlZmM1pnWUErUms0ClVXR2xjOXNyaDV2TGJuYkRiSGp2VW54TU9SMnNTK0EvTWR0SWFhd3NKTUJROEEvQmpCTDEzZzVmQjg2T3F2ZXQKeUhVM0JSd05KYzdpQXYwSTYyaWNEZWdMZHJQZHZtVjc3bmJ5bzgzQnhWUGJxdjlXY1FnaXlRZ0lwdGpzUWhEcQpGTXE2ZnNPT1JESlVsbU1aV2VhVmhUVHJ4TDNvMVNLSFpRQnN6cEJCbHlUYytkeEVxalVuWDFVRWlyaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=>"
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: dilleswari
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user: dilleswari
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "<laxmi>"
        # - "-r"
        # - ""

**Comment by Dabbeeru** [comment]
can you please guide me how to add sig in my console 


-bash: syntax error near unexpected token `newline'
--

**Comment by Dabbeeru** [comment]
which group name need to mention in sig

**Comment by Dabbeeru** [comment]
if it is possible please update and give me my yml script

**Comment by Dabbeeru** [comment]
> which group name need to mention in sig

**Comment by neolit123** [comment]
you might get better responses if you post the question on stackoverflow or reddit!
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/sig aws
/triage support

**Comment by pswica** [comment]
This is clearly an issue with .yaml formatting. It's hard to give advice without the actual yaml on hard. Try running it through something like: http://www.yamllint.com/

**Comment by Dabbeeru** [comment]
Hi 

This valid yamil as your link i was just checked but still am getting error

error: Error loading config file "/home/ec2-user/.kube/config-devopsage": v1.Config: Clusters: []v1.NamedCluster: v1.NamedCluster: Cluster: v1.Cluster: Server: CertificateA uthorityData: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...\|Qo=\u003e","server":\|..., bigger context ...\|kwyQT0KLS0tLS1FTkQgQ0VSVElGSUN BVEUtLS0tLQo=\u003e","server":"\u003chttps://5A380CC50A1BC26A906D23727\|...                                                                                                   [ec2-user@ip-172-31-36-2 .kube]$
--

**Comment by pswica** [comment]
It may be that your .yaml file has hidden characters in it. Was this .yaml file transferred between OSes? Try copying the files into a plain text editor and trying again.
