### ISSUE TITLE
Solve unnecessary ERROR log on pull-kubernetes-e2e-gce-100-performance job

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#75608]
**What happened**:

When digging failed test on pull-kubernetes-e2e-gce-100-performance job, we see the following ERROR log:
```
W0305 23:22:16.168] Specify --start=39923 in the next get-serial-port-output invocation to get only the new output starting from here.
W0305 23:22:27.408] scp: /var/log/cluster-autoscaler.log*: No such file or directory
W0305 23:22:27.484] scp: /var/log/fluentd.log*: No such file or directory
W0305 23:22:27.484] scp: /var/log/kubelet.cov*: No such file or directory
W0305 23:22:27.484] scp: /var/log/startupscript.log*: No such file or directory
W0305 23:22:27.629] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```
However that happened at the succeeded job also, so that is just ignored and not related to the failed job.
The above log seems just noise for digging issues, so it is better to solve it.

**What you expected to happen**:

We never see the above ERROR log and will be able to concentrate on actual issues.

**How to reproduce it (as minimally and precisely as possible)**:

We can see the above log on pull-kubernetes-e2e-gce-100-performance job.

**Environment**:
- Upstream CI

**Comment by mattjmcnaughton** [comment]
@oomichi thoughts on how to best solve this?

I have two thoughts. One option is that we could pipe stderr for the scp command to /dev/null. That would guarantee we never see issues arising from the scp command. However, I'm concerned it could swallow meaningful errors.

Another option is we could apply a filter to the files that we try and scp, so that we're only scp'ing files that actually exist.

Let me know which you prefer and I'd love to do a pr :)

**Comment by mattjmcnaughton** [comment]
For those interested, the relevant code is in `cluster/log-dump/log-dump.sh`. Particularly the `copy-logs-from-node` function.

**Comment by oomichi** [comment]
@mattjmcnaughton Thanks for your comment. TBH when I submitted this issue, I didn't see the actual code of `copy-logs-from-node`.
Ideally the script should copy necessary log files only and I feel the script needs to filter unnecessary log files out from the list as your 2nd idea.

**Comment by mattjmcnaughton** [comment]
Yeah, I think I agree with you that option #2 is best @oomichi :) I will try and find time to work on this!

/assign

**Comment by oomichi** [comment]
@mattjmcnaughton Thanks for doing that, I am looking forward to reviewing it :-)
