### ISSUE TITLE
GKE unable to connect

### ISSUE THREAD

**Issue by vasiliyb** [kubernetes/kubernetes#75606]
**What happened**:
```
ResponseError: code=400, message='zone' field cannot be used to access GKE regional clusters. Use 'name' or 'parent' fields instead.
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
GKE regional kubernetes cluster... unable to connect

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mattjmcnaughton** [comment]
@vasiliyb thanks for posting!

Can you please add steps to reproduce the issue and also what you expected to happen. I think that'll give us a good starting point for debugging.
