### ISSUE TITLE
Scheduler: affinity predicates read nodes from informer cache instead of scheduler cache

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#75617]
**What happened**:
I recently saw an issue in which the scheduler hit this log line many times: 
https://github.com/kubernetes/kubernetes/blob/6f482974b76db3f1e0f5d24605a9d1d38fad9a2b/pkg/scheduler/algorithm/predicates/predicates.go#L1276

After some digging, it turns out that PodAffinityChecker has a `PodLister` and `NodeInfo`. The `PodLister` points at the scheduler's cache instance, while the `NodeInfo` points at a light wrapper around a `corelisters.NodeLister`.

https://github.com/kubernetes/kubernetes/blob/6f482974b76db3f1e0f5d24605a9d1d38fad9a2b/pkg/scheduler/factory/factory.go#L1329

In the scheduler, we use the cache to provide a globally consistent view of the cluster, even if that view is slightly out of date. Data read from the core `NodeInfo` may not have been processed by the scheduler cache yet. Letting data "skip ahead" like this can cause stale info to get persisted in the scheduler cache, and other subtle bugs.

While the original problem is not likely caused by this issue, I think it needs to be cleaned up to avoid potential bugs down the line.

**What you expected to happen**:
Predicates should only read state from the scheduler's cache in order to maintain consistency.

**How to reproduce it (as minimally and precisely as possible)**:
This was observed in a cluster with high rate of pod creation and node creation/deletion.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.5
- Cloud provider or hardware configuration: GKE with preemptible nodes
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Huang-Wei** [comment]
We do have this kind of issues, and here is another one: https://github.com/kubernetes/kubernetes/issues/70450.

**Comment by mattjmcnaughton** [comment]
I'm not sure the urgency of this fix, but if its not super urgent, I would love to pick it up, if there's an eng more experienced with the scheduler who could give me some initial guidance :)

**Comment by draveness** [comment]
I dug into the source code, and find out `CachedNodeInfo` is used by the scheduler and kubelet. Maybe we could change the internal struct of `CachedNodeInfo`, but I do not know why it appears in kubelet which seems irrelevant to the scheduler.

**Comment by xiaoxubeii** [comment]
@draveness `CachedNodeInfo` is just a wrapper of corelisters.NodeLister. kubelet can get node info by it.

**Comment by xiaoxubeii** [comment]
I think the point is that the kubernetes scheduler was designed to support single instance at the beginning. Even with the addition of multiple scheduler support, the cache between each scheduler is isolated. So at this stage, we can accept this without a shared state solution. After all, the node information is not actively modified by the kubernetes scheduler.

**Comment by draveness** [comment]
@xiaoxubeii So is it necessary to ensure the consistency by using node lister instead of cache in the scheduler, or we do not need to fix this issue https://github.com/kubernetes/kubernetes/issues/70450 which seems like to caused by inconsistent cache.

**Comment by dadux** [comment]
We've recently hit this issue with the scheduler. 

It appears that our scheduler somehow gets out of sync with the nodes, and start scheduling pods on tainted nodes. 
The node's kubelet then (rightfully) refuse to admit the pod.  

Looking at the scheduler logs, they are flooded with the following : 
```
E0521 03:01:34.742135       1 predicates.go:1277] Node not found, ip-10-155-107-76.ec2.internal
E0521 03:01:34.742142       1 predicates.go:1277] Node not found, ip-10-155-107-76.ec2.internal
```

Similar scenario, this is a high churn cluster with thousands of pods scheduled per minute - and nodes being autoscaled. 

Can we try to get a fix ?

**Comment by draveness** [comment]
I'm glad to pick this up if we decide to fix this issue.

**Comment by awprice** [comment]
> I'm glad to pick this up if we decide to fix this issue.

It would be awesome if you could fix this issue for us, we are currently seeing 100's of pods incorrectly being scheduled onto nodes with taints.

**Comment by tedyu** [comment]
The code cited for logging "Node not found, %v" is now in :
pkg/scheduler/algorithm/priorities/interpod_affinity.go

**Comment by misterikkit** [comment]
Thanks for the interest on fixing this bug. Sorry I haven't had time to engage on this issue. Feel free to send PRs my way.

@dadux, I'm not 100% certain that this will fix the problem of pods getting scheduled to tainted nodes. How is the taint being applied to the node? Even if the scheduler is internally consistent, there could be a time between node creation and the taint being applied where we send pods to that node.
