### ISSUE TITLE
coredns not start up

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#75625]
coredns 无法启动报错

Name:           coredns-8449ddb7b4-mzwgq
Namespace:      kube-system
Node:           192.168.174.132/192.168.174.132
Start Time:     Sat, 23 Mar 2019 18:09:28 +0800
Labels:         k8s-app=kube-dns
                pod-template-hash=8449ddb7b4
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/coredns-8449ddb7b4
Containers:
  coredns:
    Container ID:  
    Image:         coredns/coredns:1.1.3
    Image ID:      
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:    <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-7crsh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-7crsh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-7crsh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
Events:
  Type     Reason                  Age                  From                      Message
  ----     ------                  ----                 ----                      -------
  Normal   Scheduled               35m                  default-scheduler         Successfully assigned kube-system/coredns-8449ddb7b4-mzwgq to 192.168.174.132
  Warning  FailedCreatePodSandBox  35m                  kubelet, 192.168.174.132  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "f81ac70174bcb6ad3994a15d0c74d36b092aa74195c4f7d94e031aa81058b933" network for pod "coredns-8449ddb7b4-mzwgq": NetworkPlugin cni failed to set up pod "coredns-8449ddb7b4-mzwgq_kube-system" network: could not initialize etcdv3 client: tls: found a certificate rather than a key in the PEM for the private key, failed to clean up sandbox container "f81ac70174bcb6ad3994a15d0c74d36b092aa74195c4f7d94e031aa81058b933" network for pod "coredns-8449ddb7b4-mzwgq": NetworkPlugin cni failed to teardown pod "coredns-8449ddb7b4-mzwgq_kube-system" network: could not initialize etcdv3 client: tls: found a certificate rather than a key in the PEM for the private key]
  Normal   SandboxChanged          48s (x164 over 35m)  kubelet, 192.168.174.132  Pod sandbox changed, it will be killed and re-created.

**Comment by gitplyx** [comment]
cni.go:330] Error deleting network: could not initialize etcdv3 client: tls: found a certificate rather than a key in the PEM for the private key

**Comment by mattjmcnaughton** [comment]
Thanks for reporting @gitplyx :)

Could you please feel out the bug report issue template? I think that'll provide some important data to start the investigation.

==== TEMPLATE ======




**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by chrisohaver** [comment]
Please also wrap log output with triple backticks when pasting them into an issue, to retain monospaced whitespacing and make them easier to read. e.g. 

~~~
```
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  2s (x6 over 11s)  default-scheduler  0/4 nodes are available: 4 Insufficient cpu.

```
~~~

which is significantly easier to read than...

Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  2s (x6 over 11s)  default-scheduler  0/4 nodes are available: 4 Insufficient cpu.
