### ISSUE TITLE
genericScheduler#findNodesThatFit should return from parallel work early if there is any error

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#75635]
**What would you like to be added**:
In genericScheduler#findNodesThatFit, workqueue.ParallelizeUntil evaluates all checkNode.
Afterwards, if there is any err, the func would return.

We can add variant of ParallelizeUntil which takes errs (an error map - map[string]int).
```
                                select {
                                case <-stop:
                                        return
                                default:
                                        doWorkPiece(piece)
                                }
```
We can add a new case above where once errs map is non-empty, return early.

**Why is this needed**:
This addition would allow node evaluation to finish sooner if there is any error.

**Comment by tedyu** [comment]
@kubernetes/sig-scheduling

**Comment by mattjmcnaughton** [comment]
I'd love to take a stab at implementing this if its open for claiming :)

**Comment by mattjmcnaughton** [comment]
/unassign

Unfortunately I've been sick for the last week and haven't gotten a chance to work on this :( Opening it up for anyone else who may want to work on it.

**Comment by draveness** [comment]
@mattjmcnaughton, Hope you'll get better soon. And if nobody claims this, I'd like to work on it.

**Comment by draveness** [comment]
quoted from @Huang-Wei 

> actually the behavior that gathers all scheduling failures and return is intentional. And that info can be displayed when running `k describe pod <pending pod>`.

**Comment by Huang-Wei** [comment]
@tedyu would you mind closing this close as the behavior is intentional?

**Comment by tedyu** [comment]
@Huang-Wei
Since collecting all the errors may take some time, how about adding an option which allows quick return if there is at least one error ?

Normally the pods would encounter similar issues where seeing the first error would help find the cause.

**Comment by Huang-Wei** [comment]
@tedyu it's sort of a tradeoff between UX and performance. If we can prove that performance gets a boost in practice, sure we should do it. Otherwise, I'd prefer to leave it as is.

**Comment by draveness** [comment]
/close

Feel free to reopen it if you have any further questions.
