### ISSUE TITLE
why my dashboard display like this?

### ISSUE THREAD

**Issue by fengdage1** [kubernetes/kubernetes#75644]
<img src="https://i.loli.net/2019/03/24/5c978774093e7.png"/>

**Comment by neolit123** [comment]
/sig ui
please provide kubernetes/dashboard version, browser and OS version.
thanks.

**Comment by mrbobbytables** [comment]
@fengdage1 If you could, please post your [issue in the kubernetes/dashboard project](https://github.com/kubernetes/dashboard/issues/new/choose). The dashboard is not managed under the main kubernetes repo.

Thanks!

/close
