### ISSUE TITLE
ci-kuberentes-verify and pull-kubernetes-verify are failing in master, 1.13, 1.14

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#75653]
**Which jobs are failing**:
`ci-kubernetes-verify-beta`

**Which test(s) are failing**:
`verify.godeps` [kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4647](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/4647)

**Since when has it been failing**:
Test has been failing since 3/24, at 9:19

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.14-blocking#verify-1.14

**Reason for failure**:
Error during `hack/verify-godeps.sh`:
```
Your Godeps.json is different:
--- Godeps/Godeps.json	2019-03-25 02:24:42.529814436 +0000
+++ /tmp/gopath.tmXTzL/src/k8s.io/kubernetes/Godeps/Godeps.json	2019-03-25 03:08:44.614866981 +0000
@@ -1758,12 +1758,12 @@
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonpointer",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonreference",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "8483a886a90412cd6858df4ea3483dce9c8e35a3"
 		},
 		{
Godeps Verify failed.
If you're seeing this locally, run the below command to fix your Godeps.json:
patch -p0 < godepdiff.patch
(The above output can be saved as godepdiff.patch if you're not running this locally)
(The patch file should also be exported as a build artifact if run through CI)
Copying patch to artifacts..
Leaving /tmp/gopath.tmXTzL for you to examine or copy. Please delete it manually when finished. (rm -rf /tmp/gopath.tmXTzL)
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-godeps.sh	825s
```
Due to release v0.19.0 of
[go-openapi/jsonpointer/releases](https://github.com/go-openapi/jsonpointer/releases)
and [go-openapi/jsonreference/releases](https://github.com/go-openapi/jsonreference/releases)
the morning of 3/23.

/milestone v1.14
/kind failing-test
/priority critical-urgent

/cc @smourapina @mariantalla @kacole2 @mortent @spiffxp @nikopen

**Comment by alejandrox1** [comment]
Adding sig-testing until someone claims it
/sig testing

**Comment by alejandrox1** [comment]
The Godeps.json file specifies both a version and a SHA commit.
For [go-openapi/jsonpointer/releases](https://github.com/go-openapi/jsonpointer/releases) the hash `ef5f0afec364d3b9396b7b77b43dbe26bf1f8004` is the same for releases v0.17.0 through v0.19.0.

The same goes for [go-openapi/jsonreference/releases](https://github.com/go-openapi/jsonreference/releases). The hash `8483a886a90412cd6858df4ea3483dce9c8e35a3` has been the same for releases v0.17.0 through v0.19.0.

For both of these packages, the change from v0.18.0 (whats in Godeps.json) to v0.19.0 seems to be the addition of a go.sum and go.mod files.

**Comment by alejandrox1** [comment]
I think this is the presubmit job that corresponds to #75656 https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-godeps/4043
So just waiting to see if it works (runtime about an hour)

**Comment by alejandrox1** [comment]
Forgot to mention that this also needs to be fixed in master

**Comment by mariantalla** [comment]
Thanks for monitoring it so closely and for preparing the fixes @alejandrox1 💥 

I think https://github.com/kubernetes/kubernetes/pull/75659 and a cherry-pick to the `v1.14` branch make sense. I'd rather hold onto merging them until after we've released later today (🤞), especially for 1.14. My reasoning is that we've seen the tests stable with v0.18 of both dependencies for quite a while. The changes seem small, but I guess we'd still want to let the CI run for a while if we update any dependencies.

Because the job is very quick, I feel we can still decide to go for it later today if we decide otherwise; I'll hold back for now and let's speak at today's release meeting.

**Comment by mariantalla** [comment]
Hm, looking at it a bit more, there's no real change between the 2 releases:
https://github.com/go-openapi/jsonpointer/compare/v0.19.0...v0.18.0
https://github.com/go-openapi/jsonreference/compare/v0.19.0...v0.18.0

<img width="308" alt="Screen Shot 2019-03-25 at 10 37 11" src="https://user-images.githubusercontent.com/5007973/54913108-f9fd8a00-4ee9-11e9-8a66-0cb9e42cd93a.png">

A [new version](https://github.com/go-swagger/go-swagger/releases/tag/v0.19.0) of https://github.com/go-swagger/go-swagger seems to have triggered the new releases, but none of the 2 dependencies seem to vendor it (directly or indirectly).

I'm happy with that going in, at least for `master`. Let's still chat in a few hours about how to proceed.

**Comment by liggitt** [comment]
godeps adds comments that correspond to the latest tag for the referenced sha. that means a new tag on the same sha broke our CI verification, so we need to update the generated Godep file. there are no code or content changes associated with the bump, so the contents of `vendor` will not change.

**Comment by spiffxp** [comment]
This is affecting all PR's against master as well: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-godeps

**Comment by spiffxp** [comment]
Repurposing this as umbrella issue for the godeps issue since it's affecting multiple branches
