### ISSUE TITLE
Lots of error logs are observed on host system /var/log/message

### ISSUE THREAD

**Issue by wxyongcn** [kubernetes/kubernetes#75663]
in /pkg/kubelet/cm/cpumanager/cpu_manager.go

func (m *manager) reconcileState() (success []reconciledContainer, failure []reconciledContainer) {
	success = []reconciledContainer{}
	failure = []reconciledContainer{}

	activeContainers := make(map[string]*v1.Pod)

	for _, pod := range m.activePods() {
		allContainers := pod.Spec.InitContainers
		allContainers = append(allContainers, pod.Spec.Containers...)
		for _, container := range allContainers {
			status, ok := m.podStatusProvider.GetPodStatus(pod.UID)
			if !ok {
				**klog.Warningf("[cpumanager] reconcileState: skipping pod; status not found (pod: %s, container: %s)", pod.Name, container.Name)**
				failure = append(failure, reconciledContainer{pod.Name, container.Name, ""})

so it will print the msg of init container about every 20 seconds like below:

Mar 25 20:05:21 xiaoyowa-master-01 kubelet: W0325 20:05:21.566304   27779 cpu_manager.go:232] [cpumanager] reconcileState: skipping container; ID not found in status (pod: etcd-0, container: wait-for-etcd-discovery, error: unable to find ID for container with name wait-for-etcd-discovery in pod status (it may not be running))
Mar 25 20:05:44 xiaoyowa-master-01 kubelet: W0325 20:05:44.914337   27779 cpu_manager.go:232] [cpumanager] reconcileState: skipping container; ID not found in status (pod: etcd-0, container: wait-for-etcd-discovery, error: unable to find ID for container with name wait-for-etcd-discovery in pod status (it may not be running))
Mar 25 20:06:08 xiaoyowa-master-01 kubelet: W0325 20:06:08.796797   27779 cpu_manager.go:232] [cpumanager] reconcileState: skipping container; ID not found in status (pod: etcd-0, container: wait-for-etcd-discovery, error: unable to find ID for container with name wait-for-etcd-discovery in pod status (it may not be running))
Mar 25 20:06:29 xiaoyowa-master-01 kubelet: W0325 20:06:29.469104   27779 cpu_manager.go:232] [cpumanager] reconcileState: skipping container; ID not found in status (pod: etcd-0, container: wait-for-etcd-discovery, error: unable to find ID for container with name wait-for-etcd-discovery in pod status (it may not be running))

It will cause the message file size very large. Is it expected? Any idea how to solve this issue?

**Comment by mattjmcnaughton** [comment]
Thanks for your question @wxyongcn. 

I'm curious about the frequency with which you're seeing this log message. I.e. are you still seeing it when you expect that your container has finished initialization? Or is it taking a very long time for your container to initialize?

Regardless, if you are concerned about the size of `/var/log/message`, I think I'd recommend applying some form of log rotation to `/var/log/message`.

Additionally, if more help exploring would be helpful, would you mind filling out the bug reporting template? I think it'll provide some useful information to start the investigation.

===== Template =====




**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wxyongcn** [comment]
Thanks for your question @wxyongcn.

I'm curious about the frequency with which you're seeing this log message. I.e. are you still seeing it when you expect that your container has finished initialization? Or is it taking a very long time for your container to initialize?
xiaoyowa: yes, I am still seeing it when I expect that the the container has finished initialization.

Regardless, if you are concerned about the size of /var/log/message, I think I'd recommend applying some form of log rotation to /var/log/message.
xiaoyowa: yes, we have already rotated the log once a week. 
[root@xiaoyowa-master-01 log]# ls -lt | grep messages
-rw-------   1 root   root     89840622 Mar 25 19:55 messages
-rw-------   1 root   root    482420291 Mar 24 03:21 messages-20190324
-rw-------   1 root   root    367371352 Mar 17 03:13 messages-20190317
-rw-------   1 root   root    484562537 Mar 10 03:25 messages-20190310
-rw-------   1 root   root   1102564989 Mar  3 03:16 messages-20190303

you can see the file size is very large.

Additionally, if more help exploring would be helpful, would you mind filling out the bug reporting template? I think it'll provide some useful information to start the investigation.

===== Template =====

What happened:
Lots of init container error logs are observed on host system /var/log/message

What you expected to happen:
I think we don't need print the initialization container repeatedly.

How to reproduce it (as minimally and precisely as possible):
no special trigger.

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version):
[root@xiaoyowa-master-01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider or hardware configuration:
VM created on UCS

OS (e.g: cat /etc/os-release):
[root@xiaoyowa-master-01 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Kernel (e.g. uname -a):
[root@xiaoyowa-master-01 ~]# uname -a
Linux xiaoyowa-master-01 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Install tools:
Others:

**Comment by mattjmcnaughton** [comment]
Thanks for the additional info @wxyongcn !

From your bug report, I'm seeing that you're using an non-supported version of kubernetes (1.10.11). ```Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}```

Only the last three minor releases of Kubernetes are supported. Would you mind upgrading to a supported version and seeing if the issue persists?

If the log space continues to be a problem while you find time to do the k8s upgrade, perhaps you could increase the log rotation frequency from weekly to daily?

**Comment by wxyongcn** [comment]
Thanks. OK, we will try to upgrade the k8s version firstly. let's see if it makes any difference then.

**Comment by SleepyBrett** [comment]
Warnings of this form:
```
Apr 29 21:52:01 ip-172-16-198-138 kubelet-wrapper[1567]: W0429 21:52:01.425891    1567 cpu_manager.go:232] [cpumanager] reconcileState: skipping container; ID not found in status (pod: kube-flannel-bqm92, container: install-cni, error: unable to find ID for container with name install-cni in pod status (it may not be running))
```

occur forever whenever a pod has an init containers. Once the init-container exits the kubelet will forever try to interrogate the runtime for information on this container. (Verified on kubernetes 1.11.13)

Seems like once the container exits status 0 you should stop trying to interrogate it.

**Comment by zigmund** [comment]
Same here. With `cpuManagerPolicy: static` for every init-container kubelet will write `cpu_manager.go:236] [cpumanager] reconcileState: skipping container; ID not found in status (pod: foo..., container: bar, error: unable to find ID for container with name sysctl in pod status (it may not be running))` every `cpuManagerReconcilePeriod`

**Comment by artazar** [comment]
Issue is still present.
After enabling 'static' mode of cpumanager, /var/log/messages contains numerous errors.

`Nov  6 02:54:28 d003xknw000 kubelet: W1106 02:54:28.744870   24654 cpu_manager.go:238] [cpumanager] reconcileState: skipping container; ID not found in status (pod: mongo-rs-mongodb-replicaset-0, container: copy-config, error: unable to find ID for container with name copy-config in pod status (it may not be running))
Nov  6 02:54:28 d003xknw000 kubelet: W1106 02:54:28.744895   24654 cpu_manager.go:238] [cpumanager] reconcileState: skipping container; ID not found in status (pod: mongo-rs-mongodb-replicaset-0, container: install, error: unable to find ID for container with name install in pod status (it may not be running))
Nov  6 02:54:28 d003xknw000 kubelet: W1106 02:54:28.744903   24654 cpu_manager.go:238] [cpumanager] reconcileState: skipping container; ID not found in status (pod: mongo-rs-mongodb-replicaset-0, container: bootstrap, error: unable to find ID for container with name bootstrap in pod status (it may not be running))`

k8s version:
`Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by guanzydev** [comment]
The same problem：
`kubelet: W1128 17:30:04.046048   17585 cpu_manager.go:236] [cpumanager] reconcileState: skipping container; ID not found in status (pod: elasticsearch-logging-0, container: elasticsearch-logging-init, error: unable to find ID for container with name elasticsearch-logging-init in pod status (it may not be running))
 `
elasticsearch-logging-init is an init container and at exit status, but a large of log in message.

**Comment by zhanghuidinah** [comment]
The same problem：

```
[cpumanager] reconcileState: skipping container; ID not found in status (pod
```

**Comment by zigmund** [comment]
Same here. With `cpuManagerPolicy: static` for every init-container every ~15 sec log written:
```
Jan 31 08:51:12 kube-n1 kubelet[1452]: W0131 08:51:12.147171    1452 cpu_manager.go:238] [cpumanager] reconcileState: skipping container; ID not found in status (pod: foo-85fdc787d4-85mz6, container: bar, error: unable to find ID for container with name bar in pod status (it may not be running))
```

/reopen
/remove-lifecycle rotten

**Comment by AManMustHaveACode** [comment]
find same error with cilium 
/reopen
