### ISSUE TITLE
[Bug] make WHAT="targets1 target2 ... " fails.

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#75669]
**What happened**:

Trying to build tests with command:

`make WHAT="./test/e2e/e2e.test ./vendor/github.com/onsi/ginkgo/ginkgo"`

fails with error:

```
+++ [0325 16:04:54] Building go targets for darwin/amd64:
    ./test/e2e/e2e.test
    ./vendor/github.com/onsi/ginkgo/ginkgo
can't load package: package k8s.io/kubernetes: no Go files in /Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
!!! [0325 16:04:55] Call tree:
!!! [0325 16:04:55]  1: /Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes/hack/lib/golang.sh:629 kube::golang::build_some_binaries(...)
!!! [0325 16:04:55]  2: /Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes/hack/lib/golang.sh:764 kube::golang::build_binaries_for_platform(...)
!!! [0325 16:04:55]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
```

**Anything else we need to know?**:

Debugging the issue, I've noticed that the `go install ` command in `kube::golang::build_some_binaries(...)` gets called with an extra `' '`:

`go install -gcflags ' -trimpath=/Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes' -asmflags -trimpath=/Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes -ldflags ' -s -w -X '\''k8s.io/kubernetes/pkg/version.buildDate=2019-03-25T14:08:55Z'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.buildDate=2019-03-25T14:08:55Z'\'' -X '\''k8s.io/kubernetes/pkg/version.gitCommit=231e372d0cb16ffba8c8d6b04530dbb033ed23a2'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitCommit=231e372d0cb16ffba8c8d6b04530dbb033ed23a2'\'' -X '\''k8s.io/kubernetes/pkg/version.gitTreeState=dirty'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitTreeState=dirty'\'' -X '\''k8s.io/kubernetes/pkg/version.gitVersion=v1.14.0-alpha.2.2362+231e372d0cb16f-dirty'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitVersion=v1.14.0-alpha.2.2362+231e372d0cb16f-dirty'\'' -X '\''k8s.io/kubernetes/pkg/version.gitMajor=1'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitMajor=1'\'' -X '\''k8s.io/kubernetes/pkg/version.gitMinor=14+'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitMinor=14+'\''' '' k8s.io/kubernetes/./vendor/github.com/onsi/ginkgo/ginkgo`

This is because here: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L721 , binaries should be declared as array.

**Environment**:
- Kubernetes version: master 
- OS (e.g: `cat /etc/os-release`): Darwin

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/close
fixed by https://github.com/kubernetes/kubernetes/pull/75668
