### ISSUE TITLE
[Flaky test] Volume metrics should create prometheus metrics for volume provisioning and attach/detach

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#75666]
**Which jobs are flaking**:
`ci-kubernetes-e2e-gce-cos-k8sbeta-serial` ([testgrid](https://testgrid.k8s.io/sig-release-1.14-blocking#gce-cos-1.14-serial)) ([triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-cos-k8sbeta-serial%24&test=Volume%20metrics%20should%20create%20prometheus%20metrics%20for%20volume%20provisioning%20and%20attach%2Fdetach))

**Which test(s) are flaking**:
`Volume metrics should create prometheus metrics for volume provisioning and attach/detach`

**Reason for failure**:
Timeout:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:74
Timeout error fetching storage c-m metrics : timed out waiting for the condition
Unexpected error:
    <*errors.errorString | 0xc0002b93f0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:463
```

**Anything else we need to know**:
* This test flaking about 10% of the time in this job.

/sig storage
/kind flake
/priority important-soon

cc @kubernetes/sig-storage-test-failures 
@alejandrox1 @smourapina @kacole2 @mortent @spiffxp

**Comment by msau42** [comment]
I noticed one issue with the test is that it's not filtering metrics by plugin name.  So it will just count the last plugin's metric.  I'm not sure if the metrics collected are in any sorted order or not.  If not, then when you have a suite that runs multiple plugins, then you might be pulling from the wrong metric.

**Comment by alenkacz** [comment]
still very prevalent in sig-release dashboards https://testgrid.k8s.io/sig-release-1.17-informing#gce-cos-k8sbeta-serial

**Comment by gnufied** [comment]
I have pushed https://github.com/kubernetes/kubernetes/pull/85619 which should hopefully fix this.

**Comment by gnufied** [comment]
Also PR against 1.17 branch - https://github.com/kubernetes/kubernetes/pull/85649
