### ISSUE TITLE
Can not set watch cache size specifically for Custom Resource

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#75677]
**What would you like to be added**:

We should be able to configure watch cache size for an API group specifically defined by CRD.

**Why is this needed**:

Watch cache size should be a tunable variable for custom resource. A lower value may break the watch when there are  a bunch of instances and a lot of updates. That's how `too old resource version` arises generally.

1. A list call may take few seconds to complete.
1. The oldest resource version in APIServer may be newer than the one client get.
1. Client failed to watch since the resource version is already too old.

It usually helps if we can increase the watch-cache-size for that resource, but today we can not set one value for that custom resource group specifically.

https://github.com/kubernetes/kubernetes/blob/5732630bf28a3f6d9408bdecddab919eea5a29cc/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L730-L743

All it honors is the default watch cache size.

**Comment by zhouhaibing089** [comment]
cc @sttts

**Comment by jpbetz** [comment]
Yes, it should be fine to support CRD types via the `--watch-cache-sizes` kube apiserver flag. [Watch bookmarks](https://github.com/wojtek-t/enhancements/blob/5e63ab7becfd330064a1baf371f4b3e62dac38a7/keps/sig-api-machinery/20190206-watch-bookmark.md) should help with `too old resource version` issues, but having full CRD support with the `--watch-cache-sizes` flag seems like a good thing.

**Comment by zhouhaibing089** [comment]
Thanks. CRD is kinda dynamic, so maybe another approach is setting its watch cache size in CRD spec(is this possible)? I do not know which way is better honestly.

**Comment by jpbetz** [comment]
@zhouhaibing089 Good point. And since the watch cache is fairly implementation specific to the apiserver, and it's feasible it could one day be replaced with something else, not sure where it's configuration should belong for dynamic things like CRDs. Might require reviewing the alternatives and proposing an approach.

**Comment by lxlxok** [comment]
Hi @jpbetz, I found this issue together with @zhouhaibing089 . Can I take this task and send a PR. Thx

**Comment by jpbetz** [comment]
@lxlxok All yours! Recommend commenting on this issue once you've decided on a proposed approach to get early feedback.

**Comment by lxlxok** [comment]
Hi @jpbetz  I have wrapped up a solution to make param(--watch-cache-sizes) of apiserver also be effective for custom resource.  Would you mind to take a look at my PR #75804 😄. Thanks.

**Comment by zhouhaibing089** [comment]
Sorry that I didn't pay enough attention to the latest updates. This issue is no longer valid considering that watch cache size is already dynamic.

Ref:

* https://github.com/kubernetes/kubernetes/issues/90058
