### ISSUE TITLE
Cronjob: include lastSuccessfulTime in the status

### ISSUE THREAD

**Issue by aermakov-zalando** [kubernetes/kubernetes#75674]
**What would you like to be added**:

Cronjob `status` should include the last time when a job was successfully completed.

**Why is this needed**:

Currently, a Cronjob's `status` only includes the last time when a job was scheduled. This makes monitoring cronjobs much more complicated, because instead of simply comparing `status.lastSuccessfulTime` to the current timestamp, the monitoring system now has to hunt for the last job related to the cronjob and persist the state somewhere.

**Comment by aermakov-zalando** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by KitFreddura** [comment]
I'd be interesting in picking this up if the apps team thinks this is a good ticket - it seems like it's fairly beginner friendly.

**Comment by draveness** [comment]
Hi @kitfre, how is this going on? I could take it over if you don't have the time for this issue. :)

**Comment by kitfre** [comment]
Yes @draveness please do! I meant to update that I actually wasn't able to pick this up, but it slipped my mind 😨

**Comment by draveness** [comment]
Hi @kubernetes/sig-apps-feature-requests, do you have any thoughts on this feature?

**Comment by aermakov-zalando** [comment]
@kubernetes/sig-apps-feature-requests Any updates?

**Comment by barney-s** [comment]
Trying to understand the usage of lastSuccessfulTime. 

In a normally working case, 
 lastSuccessfulTime > lastScheduledTime => last job completed 
 lastSuccessfulTime < lastScheduledTime => last job completed, but a newer one is running

Is that the expectation ?

**Comment by aermakov-zalando** [comment]
We wanted to use it in monitoring (e.g. fire an alert if `lastSuccessfulTime` is more than X ago). `lastSuccessfulTime < lastScheduledTime` could also mean that the job has been failing for some time, so I don't know what would you get out of that.

**Comment by soltysh** [comment]
```
   lastScheduleTime	<string>
     Information when was the last time the job was successfully scheduled.
```
that's exactly what is being asked here.
/close

**Comment by aermakov-zalando** [comment]
@soltysh "successfully scheduled" != "successfully completed", and most of the users care more about the latter.

**Comment by soltysh** [comment]
This is described in https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/19-Graduate-CronJob-to-Stable and being actively implemented in https://github.com/kubernetes/kubernetes/pull/98965
/close

**Comment by aermakov-zalando** [comment]
It doesn't look like it was actually implemented, though. Searching for `lastSuccessfulTime` only shows API changes, there don't seem to be any changes to the CronJob controller logic. Or am I missing something?
