### ISSUE TITLE
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed

### ISSUE THREAD

**Issue by davejrt** [kubernetes/kubernetes#75683]
**What happened**:

Installing kubelet package on ubuntu 16.04 fails due to dependency issue with kubernetes-cni 

**What you expected to happen**:

To be able to install kubelet and have any upstream dependencies managed

**How to reproduce it (as minimally and precisely as possible)**:

```
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet=1.13.3-00
```
```
root@node-01:~# apt-get install kubelet=1.13.3-00
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
1.13.3
- OS (e.g: `cat /etc/os-release`):
{
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.5 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}

**Comment by bfurey** [comment]
Also seeing this with K8s 1.11.6

When deploying K8s 1.11.6, we get an error: Requires: kubernetes-cni = 0.6.0
 - we are required to lock down on K8s 1.11.6 and thus cannot move to K8s 1.11.9

```
/usr/bin/yum --noplugins install -y kubelet-1.11.6* kubeadm-1.11.6* kubectl-1.11.6* --disableexcludes=kubernetes

Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.11.6-0 will be installed
--> Processing Dependency: kubernetes-cni >= 0.6.0 for package: kubeadm-1.11.6-0.x86_64

---> Package kubectl.x86_64 0:1.11.6-0 will be installed
---> Package kubelet.x86_64 0:1.11.6-0 will be installed
--> Processing Dependency: kubernetes-cni = 0.6.0 for package: kubelet-1.11.6-0.x86_64
--> Running transaction check
---> Package kubelet.x86_64 0:1.11.6-0 will be installed
--> Processing Dependency: kubernetes-cni = 0.6.0 for package: kubelet-1.11.6-0.x86_64
---> Package kubernetes-cni.x86_64 0:0.7.5-0 will be installed

--> Finished Dependency Resolution
Error: Package: kubelet-1.11.6-0.x86_64 (kubernetes)
           Requires: kubernetes-cni = 0.6.0
           Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
               kubernetes-cni = 0.3.0.1-0.07a8a2
           Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-0
           Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-1
           Available: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
               kubernetes-cni = 0.6.0-0
           Installing: kubernetes-cni-0.7.5-0.x86_64 (kubernetes)
               kubernetes-cni = 0.7.5-0
 You could try using --skip-broken to work around the problem
```

**Comment by lingxiankong** [comment]
i am encountering the same issue for installing kubernetes 1.13.2

**Comment by adodge** [comment]
I was able to run this on Ubuntu 18.10 to set up a new node for a cluster running kubernetes 1.13.4:

```
sudo apt-get install kubeadm=1.13.4-00 kubelet=1.13.4-00 kubectl=1.13.4-00 kubernetes-cni=0.6.0-00
```

**Comment by swysth5665** [comment]
@chavafg Your amendment is correct.

@adodge yes,or first Run command apt install kubernetes-cni=0.6.0-00

**Comment by davidkarlsen** [comment]
I have this as well, and if I allow the cni to be upgraded stuff fails to start:
```
Mar 26 10:02:00 main kubelet[12634]: E0326 10:02:00.748638   12634 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:node:main.lan.davidkarlsen.com" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
```

**Comment by neolit123** [comment]
`apt-get install` works fine for me.

see here for yum:
https://github.com/kubernetes/kubernetes/issues/75701#issuecomment-476595925

what are the workarounds?

**Comment by brysonshepherd** [comment]
I have noticed that kubelet and kubeadm 1.12.6 now have this issue with wanting cni 0.6.0 . But kubelet and kubeadm 1.12.7 actually want cni 0.7.5. and will fail with cni 0.6.0.

**Comment by neolit123** [comment]
try pinning the version to 0.7.5 using: kubernetes-cni=0.7.5-00

**Comment by empath** [comment]
As people are fixing this -- keep in mind that there appears to be an embargoed CVE on kubernetes-cni=0.6.0, so be wary of pinning your start up scripts to that version permanently.

**Comment by neolit123** [comment]
it's highly recommended to upgrade to the latest PATCH version of the 1.x release you are using.
it should be using the 0.7.5 CNI that has the security bug fix and the installation should work.

as far as why this install problem is happening, the suspicion ATM is that `=0.6.0` version pinning in the old packages does work and it still tries to pull the latest kubernetes-cni 0.7.5-00 from the same repo.
an additional speculation is that this is happening because the MAJOR of CNI is `0` still - i.e. this would not have happened if CNI was `1.x.y`.

if we have to fix this using `>=` we need to update all old packages (and there are a lot).

**Comment by pavdmyt** [comment]
Having the same issue with `v1.12.2`:

```bash
$ apt install "kubeadm=1.12.2*" "kubelet=1.12.2*" "kubectl=1.12.2*"
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '1.12.2-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubeadm'
Selected version '1.12.2-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubelet'
Selected version '1.12.2-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubectl'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.7.5-00 is to be installed
E: Unable to correct problems, you have held broken packages.
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by sflxn** [comment]
This seems to be a recurring issue.  If you search kubeadm kubernetes-cni=0.6.0-00, this issue has come up in the past.  I can confirm that I tried every version of k8s from 1.11.0, and they all have this issue.

@neolit123 What do you suggest we do?  I can also confirm that pinning kubernetes-cni works but as stated here, there is a CVE on it so I don't really want to do that.  We're trying to tag our cluster api provider this week, but I need a solution.  Should i go ahead and pin to 0.6.0-00?

**Comment by neolit123** [comment]
@sflxn given we are trying to deal with package manager semantics i'd suggest to try to pin to 0.7.5 (somehow). in terms of the actual fix we want, SIG Release are currently discussing the option to push revisioned packages e.g. `kubelet.... -1` for *all* the old versions which will hopefully solve the problem.

we have multiple problems and multiple KEPs related to packages and SIG Release really want to let the users know that the k8s packages are only "best effort" at this point and not well maintained.

**Comment by sflxn** [comment]
@neolit123 Where can I get 0.7.5?  There isn't even a 0.7.5 release on the project's repo.  Ubuntu doesn't have this package either.

**Comment by neolit123** [comment]
it's in the kubernetes apt/yum repositories:
https://packages.cloud.google.com/

e.g.
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages
```
Package: kubernetes-cni
Version: 0.7.5-00
```

**Comment by sflxn** [comment]
Using kubernetes-cni 0.7.5 works if you're pulling down k8s 1.14.  For previous versions, it appears you need to still pin the package to 0.6.0.

**Comment by neolit123** [comment]
alternatively you can install the previous version of the packages and then install 0.7.5 over the existing 0.6.0.

**Comment by underyx** [comment]
For anyone looking for a workaround, I upgraded a 1.13.4 cluster to 1.13.5 successfully by upgrading kubeadm with `dpkg` like this:

```
sudo dpkg --ignore-depends=kubernetes-cni -i kubeadm_1.13.5-00_amd64_3a8177f070bce398f62a14a7ddbe81d064b378c085d7e2c4391571dfb87c259a.deb
```

I downloaded the `.deb` package from https://mirror.one.com/kubernetes/pool/.

This leaves `apt` in a confused state until everything else is upgraded with

```
sudo apt-get install kubelet=1.13.5-00 kubectl=1.13.5-00 kubernetes-cni=0.7.5-00
```

**Comment by rohantmp** [comment]
1.13.5 will use kubernetes-cni 0.7.5 without complaining.

**Comment by geerlingguy** [comment]
Confirmed that bumping to 1.13.5 (or later) fixes this.

**Comment by davejrt** [comment]
Closing as installing 1.13.5 addresses this issue
