### ISSUE TITLE
More CSI migration design items

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#75698]
**What would you like to be added**:
We need to design the following things:
* Migrating ROX volumes (both inline and PV-based).  This is further complicated by https://github.com/kubernetes/kubernetes/issues/70505, where the in-tree behavior is different from CSI behavior.
* Migrating PV labeling admission controllers for manually created PVs.  We want to eventually remove these admission controllers. cc @andrewsykim 

@kubernetes/sig-storage-feature-requests 
/assign @davidz627 @ddebroy @leakingtapan

**Comment by andrewsykim** [comment]
> Migrating PV labeling admission controllers for manually created PVs. We want to eventually remove these admission controllers. cc @andrewsykim

Was it decided that we no longer want to support zone/region labels for PVs? If so we can just remove the labelling behavior since the admission controller has already been deprecated for so long. That would also simplify https://github.com/kubernetes/enhancements/pull/839 since we don't have to rename the label going forward.

**Comment by msau42** [comment]
I think we still need to discuss if we want to continue to support the use case for labeling PVs with the correct topology when users manually create them.  While it's not an API change, it is a behavioral change that could impact user's workflows.

**Comment by andrewsykim** [comment]
Sounds good. What's the best way to continue this discussion with all the necessary stakeholders? SIG call or mailing list?

**Comment by jsafrane** [comment]
Beta labales like this are part of Kubernetes API and we must support them until core/v2.

https://github.com/kubernetes/kubernetes/blob/7dfcacd1cfcbdfe74b28f2473fb107e9a47ec905/staging/src/k8s.io/api/core/v1/well_known_labels.go#L21-L22

We can (and should) remove the admission plugin, but we should support the label in scheduler in case someone creates a PV manually.

**Comment by andrewsykim** [comment]
FYI this is a continuation from a discussion here https://github.com/kubernetes/enhancements/pull/839#issuecomment-468372562 

I'm okay with supporting the labels in the scheduler logic but not automatically labelling via admission controller. Thoughts @msau42 @saad-ali?

**Comment by davidz627** [comment]
> Migrating ROX volumes (both inline and PV-based). This is further complicated by #70505, where the in-tree behavior is different from CSI behavior.
I believe this was resolved by https://github.com/kubernetes/kubernetes/pull/77837

**Comment by msau42** [comment]
/remove-lifecycle stale
@davidz627 is the ROX migration issue resolved?

Regarding PV labeling admission controllers, we now have logic in the scheduler to migrate PVs that have beta zone labels -> CSI topology. If users today manually create CSI PVs, we can require that they fill in the appropriate PV.NodeAffinity.

But after CSI migration is on and admission controllers are removed, do we want to continue supporting auto-population of topology in-tree PVs? If so, then we may need to look into per-plugin admission webhooks?

**Comment by davidz627** [comment]
Remind me what was the issue specifically? Read only volumes work through migration to CSI now - they will be correctly attached/mounted as read only thru CSI when specified on the in-tree objects. I believe the multi-attach validation is checked from the access modes which are set correctly to `ROX` in migration when requested.

**Comment by msau42** [comment]
yeah rox is what you described.

Regarding admission webhook to auto-populate PV topology, this needs to be decided on a per-plugin basis, and not something that we can provide in k/k.  So I think we can close this.

/close
