### ISSUE TITLE
apiserver doesn't auto-recover from `kubectl delete --all apiservice`

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#75704]
**What happened**:

Deleting apiserver objects deletes all built in api registrations, and they do not come back until apiserver is restarted. (See report on twitter: https://twitter.com/philpearl/status/1109049228490350597)

**What you expected to happen**:

I expect that admin credentials are required to do this; if that's not true, it should be. (I haven't had time to check.)

I expect that either 
1. it should not be possible to delete the built in registrations, or
2. that a controller should recreate them if they vanish, or 
3. e.g. apiserver stops reporting healthy if they vanish, so that kubelet will restart it.

3 is maybe the easiest thing to implement.

**How to reproduce it (as minimally and precisely as possible)**:

`$ kubectl delete --all apiservice`

Don't do it on a cluster you care about.

**Comment by liggitt** [comment]
> I expect that admin credentials are required to do this; if that's not true, it should be. (I haven't had time to check.)

They absolutely are required. 

> 3 is maybe the easiest thing to implement.

Whatever we do must avoid dueling api servers in HA clusters (the current reason built-in APIService objects don't auto-recreate)

**Comment by mml** [comment]
No. 3 is probably easiest to backport as well, which is a really nice property.

**Comment by lavalamp** [comment]
These things are keyed on the name, I'm not sure why apiservers would dual in a destructive way? It doesn't seem hard to make the client behave correctly in that condition, am I missing something?

**Comment by liggitt** [comment]
naive autorecreating would mean stopping serving an API group on upgrade (like we plan to do in 1.18 with extensions/v1beta1) wouldn't work with HA API servers (as the new one came up and deleted the extensions/v1beta1 APIService that was no longer served, another still-running API server would recreate it and leave it orphaned and incorrect when it finally got shut down

**Comment by shawon100** [comment]
I accidentally deleted the apiservice and restored it by applying the api-server yml in bare metal kubernetes cluster 
`sudo kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml`

**Comment by Swaps76** [comment]
how did you get the api-server yml ?
