### ISSUE TITLE
kube-controller-manager in CrashLoopBackOff

### ISSUE THREAD

**Issue by sohel2020** [kubernetes/kubernetes#75726]
**What happened**:
Kube-controller-manager is in CrashLoopBackOff. It's not starting up because of listen tcp 0.0.0.0:10252: bind: address already in use

**What you expected to happen**:
kube-controller-manager will restart and will start without any problem 

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure How to reproduce it.

**Anything else we need to know?**:
core@ip-10-125-98-238 ~ $ docker ps -a | grep kube-controller-manager
daa19ab18578        gcr.io/google_containers/hyperkube                   "/bin/sh -c '/hyperk…"   44 seconds ago       Exited (255) 43 seconds ago                              k8s_kube-controller-manager_kube-controller-manager-ip-10-125-98-238.ec2.internal_default_a4c10e5c991dd390f83a067ba4b17bfa_232
3a14b0be21a8        gcr.io/google_containers/pause-amd64:3.0             "/pause"                 17 hours ago         Up 17 hours                                              k8s_POD_kube-controller-manager-ip-10-125-98-238.ec2.internal_default_a4c10e5c991dd390f83a067ba4b17bfa_0

core@ip-10-125-98-238 ~ $ ps -aux | grep controller
root      1637  0.0  0.0   4340   200 ?        Ss   Mar22   0:00 /bin/sh -c /hyperkube controller-manager --master=http://127.0.0.1:8080  --address=0.0.0.0 --cloud-provider=aws --cloud-config=/etc/cloud.conf --attach-detach-reconcile-sync-period 60s --v 4 --node-monitor-grace-period=300s --leader-elect=true --horizontal-pod-autoscaler-upscale-delay=2m0s --horizontal-pod-autoscaler-downscale-delay=4m0s --horizontal-pod-autoscaler-use-rest-clients=true --service_account_private_key_file=/etc/kubernetes/ssl/apiserver-key.pem --root-ca-file=/etc/kubernetes/ssl/ca.pem
root      1667  0.4  0.5 679976 172168 ?       Sl   Mar22  21:05 /hyperkube controller-manager --master=http://127.0.0.1:8080 --address=0.0.0.0 --cloud-provider=aws --cloud-config=/etc/cloud.conf --attach-detach-reconcile-sync-period 60s --v 4 --node-monitor-grace-period=300s --leader-elect=true --horizontal-pod-autoscaler-upscale-delay=2m0s --horizontal-pod-autoscaler-downscale-delay=4m0s --horizontal-pod-autoscaler-use-rest-clients=true --service_account_private_key_file=/etc/kubernetes/ssl/apiserver-key.pem --root-ca-file=/etc/kubernetes/ssl/ca.pem
core     18429  0.0  0.0   6848   988 pts/0    S+   10:29   0:00 grep --colour=auto controller

core@ip-10-125-98-238 ~ $ docker logs -f daa19ab18578
I0326 10:29:03.272549       8 controllermanager.go:109] Version: v1.8.15
I0326 10:29:03.273440       8 leaderelection.go:174] attempting to acquire leader lease...
F0326 10:29:03.273583       8 controllermanager.go:221] listen tcp 0.0.0.0:10252: bind: address already in use

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.15", GitCommit:"c2bd642c70b3629223ea3b7db566a267a1e2d0df", GitTreeState:"clean", BuildDate:"2018-07-11T17:59:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.15", GitCommit:"c2bd642c70b3629223ea3b7db566a267a1e2d0df", GitTreeState:"clean", BuildDate:"2018-07-11T17:52:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2023.4.0
VERSION_ID=2023.4.0
BUILD_ID=2019-02-26-0032
PRETTY_NAME="Container Linux by CoreOS 2023.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
- Kernel (e.g. `uname -a`): Linux ip-10-125-98-238.ec2.internal 4.19.23-coreos-r1 #1 SMP Mon Feb 25 23:40:01 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux

**Comment by liggitt** [comment]
that means something else (possibly another instance of `kube-controller-manager`?) is listening on that port. you need to determine what that other process is and stop it to free the port.

/close

**Comment by sohel2020** [comment]
> that means something else (possibly another instance of `kube-controller-manager`?) is listening on that port. you need to determine what that other process is and stop it to free the port.
> 
> /close
@liggitt
There is no other kube-controller-manager running on that node. when kube-controller-manager died it's not closing the pod.

**Comment by liggitt** [comment]
your ps output shows two processes:

$ ps -aux | grep controller
root 1637 0.0 0.0 4340 200 ? Ss Mar22 0:00 /bin/sh -c /hyperkube controller-manager ...
root 1667 0.4 0.5 679976 172168 ? Sl Mar22 21:05 /hyperkube controller-manager ...

**Comment by sohel2020** [comment]
> what does netstat show is bound to the port?
Yes

**Comment by ejmarten** [comment]
If you have `kubectl proxy` running, kill it.

**Comment by Harold2017** [comment]
i found this issue on aws **micro** ec2 instance, but never happened on higher level instance (small/medium/large...), i don't know whether the limited PC config is the reason...

**Comment by kow3ns** [comment]
This is a v 1.8 of Kubernetes (we only support two minor releases back). Do we know if this happens at more recent versions?
