### ISSUE TITLE
Add performance data gathering to density test suite

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#7572]
Grab the metrics and debug data, as well as the pod statuses, for density tests

**Comment by timothysc** [comment]
@fgrzadkowski, @vishh - 1st step plan to output data to feed into Prometheus from e2e tests.

**Comment by timothysc** [comment]
So after setting up prometheus and grocking, I think we can modify this slightly to easily feed in.

**Comment by timothysc** [comment]
Eventually we'll have to figure out how we want to integrate e2e with Prometheus, but that can be a separate PR. 

/cc @jayunit100

**Comment by rrati** [comment]
Closed via #7573

**Comment by timothysc** [comment]
@filbranden @roberthbailey @dchen1107 Fix From #8695 ^
