### ISSUE TITLE
E2E Proposal: To check memory limitation of the container

### ISSUE THREAD

**Issue by globervinodhn** [kubernetes/kubernetes#75756]
**What would you like to be added**: A new E2E test for validating the memory limitations of the container. This test needs to verify the resource quota allocation for the pod. The configuration should consist of memory limit and memory request parameters and should ensure that the pod is not started when the local command exceeds the memory limitations.

**Why is this needed**: 
This E2E is needed so as to verify the expected behaviour of pod allocation with respect to resource quota allocation.

--------------------------------------------------------------------------------------------------------------------------------
**Sample Configuration:**
apiVersion: v1
kind: Pod
metadata:
  name: memory-req-limit-exceed
spec:
  containers:
  - name: memory-demo
    image: polinux/stress
    resources:
      requests:
        memory: "10Mi"
      limits:
        memory: "11Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "2100M", "--vm-hang", "1"]
  restartPolicy: Never
--------------------------------------------------------------------------------------------------------------------------------
In the above scenario, the pod creation fails and ends with status 'OOMKILLED' as the local command requires memory allocation which exceeds the memory limitations specified as per the configuration.

/sig scheduling

@brahmaroutu @mgdevstack

**Comment by mgdevstack** [comment]
This seems an important functional behavior. Few things to catch here -
- As it is checking `OOMKILLED` status. Try to get this status reference from core libraries.
- Does the mentioned image is in k8s repo?

**Comment by mgdevstack** [comment]
Reference From https://github.com/kubernetes/kubernetes/issues/77973
>1. Name: Pod, memory resource, exceeds limit
e2e: Pod should be failed when memory utilisation exceeds it’s limit
Description: Create a pod with memory resource (request: 500Kb, limit: 1000Kb). Container keep requesting increasing memory gradually till 1200Kb. Container MUST be killed and Pod MUST fail.
