### ISSUE TITLE
High CPU on kubelet k8s v1.14.0

### ISSUE THREAD

**Issue by amentis** [kubernetes/kubernetes#75767]
**What happened**:
After the cluster was upgraded from v1.13.2 to v1.14.0 kubelet's CPU usage raised to around 40%.
**What you expected to happen**:
Not to use so much CPU, v1.13.2 didn't use as much

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade a HA cluster from v1.13.2 to v1.14.0

**Anything else we need to know?**:
Interestingly, on our non-HA cluster (one master-tainted, three workers, bare metal, same network, AMD cpus, but nearly the same hardware) the kubelets take around %19 at most.

**Environment**:
Ubuntu LTS 18.04LTS on all machines
Provisioner: kubeadm
etcd hosted inside the cluster
all nodes are in the same local network
Three masters with master taint removed
One worker
All machines are 64GB RAM Intel Xeon CPU E5-2650 v3 @ 2.30GHz 20 cores
Between 110 and 118 pods per machine

**Comment by danielqsj** [comment]
can you give some kubelet logs ?

**Comment by amentis** [comment]
> can you give some kubelet logs ?

It turned out, that pods cannot be started due to the registry credentials secret being out of date. I will fix that and check whether the CPU usage changes.

**Comment by amentis** [comment]
It was not related. All pods are running successfully. Other than these pull secret problems, the last logs were from January, and this cluster was upgraded yesterday.

**Comment by bitenca84** [comment]
I have the same problem after update kube to 1.13.3 from 1.14.3. I check that kubelet was using a lot of memory and cpu. When the node is reboot that issue are fixed temporally.

**Comment by MaxWinterstein** [comment]
Any news on this?
