### ISSUE TITLE
Rename MutatingWebhookConfiguration/namespaceSelector

### ISSUE THREAD

**Issue by cyrilledec** [kubernetes/kubernetes#75766]
**What would you like to be added**:
Rename `namespaceSelector` in MutatingWebhookConfiguration object

**Why is this needed**:
To make it more clear for users we should specify that this selector is looking at label of namespace and not namespace metadata.
The name should be something like : `namespaceLabelSelector`

**Comment by yue9944882** [comment]
renaming the field loses backward-compatibility for the object

**Comment by liggitt** [comment]
`___Selector` is used in multiple contexts, including networkpolicy (`namespaceSelector`, `podSelector`), and pods (`nodeSelector`), and the field documentation is clear.

/close
