### ISSUE TITLE
kube-apiserver.log entries delayed up to 10 seconds

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#75770]
**What happened**:
In gce scalability tests we are constantly seeing log entries that are delayed comparing to the neighbor ones, e.g. in:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/336/artifacts/gce-scale-cluster-master/kube-apiserver.log-20190319-1552993204.gz

I see:

```
I0319 08:17:08.220703       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-3-zf8w?resourceVersion=0&timeout=10s: (1.735366ms) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 104.196.145.73:47324]
I0319 08:17:08.220720       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-3-qfjf?resourceVersion=0&timeout=10s: (1.142807ms) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 35.237.171.145:35528]
I0319 08:17:08.220784       1 wrap.go:47] GET /apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/gce-scale-cluster-minion-group-4-2ptw?timeout=10s: (14.401021ms) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 35.243.200.2
54:40090]
I0319 08:16:59.574734       1 wrap.go:47] GET /api/v1/namespaces/kube-system/secrets?fieldSelector=metadata.name%3Dfluentd-gcp-token-zqmnv&resourceVersion=633&timeout=6m27s&timeoutSeconds=387&watch=true: (6m27.88470144s) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 35.231.107.59:43210]
I0319 08:17:08.222097       1 wrap.go:47] PUT /apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/gce-scale-cluster-minion-group-4-18f6?timeout=10s: (15.500236ms) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 35.237.46.169:44426]
I0319 08:17:08.222364       1 wrap.go:47] GET /api/v1/nodes/gce-scale-cluster-minion-group-3-jz31?timeout=10s: (23.784165ms) 200 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 35.243.242.131:42308]
I0319 08:17:07.507861       1 wrap.go:47] GET /apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/gce-scale-cluster-minion-group-1-nr2m?timeout=10s: (292.007991ms) 429 [kubelet/v1.15.0 (linux/amd64) kubernetes/1d441c1 35.231.156.141:50734]
```

In this case, 'I0319 08:16:59.574734' entry is reported after 08:17:08.220784 so it must be delayed at least ~9 seconds.

This is the worst case in that file (I checked only that one), but we are constantly seeing delays up to 0.5-1s when apiserver's load is high.

**What you expected to happen**:
To see logs ~sorted.

**How to reproduce it (as minimally and precisely as possible)**:
Just run gce 5000 nodes.

**Anything else we need to know?**:

I think this is specific to scale tests where we increase verbosity to include "access logs". Otherwise number of logs shouldn't be that high.

I think this is caused by the way we are pushing logs to the file: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests/kube-apiserver.manifest#L30

We are asking klog to write to stderr (which is unbuffered) and then forward stderr to file.
Writing to the buffer first should give some better performance.

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: gce
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @wojtek-t

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

We may consider having a corresponding bug in klog repo.
@dims - thoughts?

**Comment by dims** [comment]
@mborsz it makes sense, since it's hard for anyone else to try `5000 nodes`, can the scalability team please come up with a patch against klog that works? (file an issue/pr etc in that repo too!).

Thanks,
Dims
