### ISSUE TITLE
Generify  validateController  in utils.go

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#7577]
the `validateController` method in utils.go is supposed to be generic, but it really is coupled
- to apiv3 and also 
- to using kubectl for checking things rather than the more robust direct REST API calls 

lets make it more general

**Comment by oomichi** [comment]
Now we cannot find the corresponding code like

 $ grep validateController `find . -name utils.go`
 $

So can we close this issue now?
