### ISSUE TITLE
upgrade release-1.13 to go 1.11.6

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#75780]
> go1.11.6 (released 2019/03/14) includes fixes to cgo, the compiler, linker, runtime, go command, and the crypto/x509, encoding/json, net, and net/url packages. See the Go 1.11.6 milestone on our issue tracker for details.

release-1.13 is [still using go 1.11.5](https://github.com/kubernetes/kubernetes/blob/release-1.13/build/build-image/cross/Dockerfile#L18) and should be upgraded

/sig release

**Comment by liggitt** [comment]
cc @kubernetes/sig-release

**Comment by imkin** [comment]
I can take a look. 

/assign

**Comment by imkin** [comment]
The latest version is 1.11.10
@liggit should we should jump to that?
https://golang.org/doc/devel/release.html#go1.11

**Comment by imkin** [comment]
Go 1.11.10 has this windows security fix. 
https://github.com/golang/go/issues/30642

What is this upgrade solving?
What is our patch policy to upgrade dependecies like this? 
- Do we need to prove clear impact on the project for such dependency upgrades? 

https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/patch-release-manager

**Comment by neolit123** [comment]
> Go 1.11.10 has this windows security fix.
golang/go#30642

this CVE is DLL injection if system libraries such as an altered winmm.dll are placed in the path of a go compiled binary such as the kubelet, that is because by default Windows search the `.\` path for bundled library overrides.

![kubelet-dep-walker](https://user-images.githubusercontent.com/331852/57386728-9e4b3f80-71bd-11e9-9835-1bcfc9eae932.png)

the linked patch-set in `.10` addresses the problem by applying a couple of guard mechanics.

cc @PatrickLang 
/sig windows

**Comment by liggitt** [comment]
latest go 1.11.x is probably a good idea

**Comment by imkin** [comment]
The scope of this issue changes with discussions on https://github.com/kubernetes/kubernetes/issues/73286

If we are updated k8s release-1.12 to golang 1.12, we should also update 1.13

@liggitt @tpepper @feiskyer comments?

**Comment by feiskyer** [comment]
release-1.12 is still using Go 1.10.8, upgrading to 1.12 may introduce performance regressions and other issues. Unless we have good ways to validate the performance, I suggest we only upgrade Go to latest patch releases.

**Comment by imkin** [comment]
@feiskyer that is good to know.
@feiskyer @tpepper In practice how have we decided to update the go version in the past. What level justification is required? Should a SIG prove that this is worth the update or a blanket it-fixes-these-two-security-issues/bugs and it-impacts-these-two-kube-binaries/libs is sufficient?

This also effects kubectl I believe.

@kubernetes/sig-cli-misc

**Comment by warmchang** [comment]
Should update all active Kubernetes release branches to latest Go release (go1.12.7 now)?

https://github.com/kubernetes/kubernetes/issues/79912#issuecomment-510935321
https://github.com/kubernetes/kubernetes/issues/73286

**Comment by BenTheElder** [comment]
@warmchang we don't necessarily update past releases beyond go patch versions because of the potential for regressions in scalability etc. That policy needs discussion. @kubernetes/release-engineering

**Comment by warmchang** [comment]
@liggitt The release-1.13 needs to move to go1.11.13

Ref: https://github.com/kubernetes/kubernetes/issues/79912

**Comment by liggitt** [comment]
Issues to track specific go bumps aren't generally useful. go1.11.13 is the desired version now and is in progress
