### ISSUE TITLE
Getting started with Kubernetes: "kubectl get nodes" command shows errors

### ISSUE THREAD

**Issue by kcao3** [kubernetes/kubernetes#7581]
Hello,

I am very new to Kubernetes and would like to get some experience with this technology. Following the getting-started tutorials: 
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides, 
I picked the simplest setup example: Running kubernetes locally via Docker obtained from this website: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md as my starting point. The goal is to set up and run a simple single Kubernetes node cluster using Docker.
I was able to follow the three steps in this tutorial and at the the end, I believe I have a running Kubernetes cluster. The "docker ps" command output  shows that I have three containers running on my machine:
[centos@ip-172-31-49-223 kubernetes]$ sudo docker ps
CONTAINER ID        IMAGE                                        COMMAND                CREATED             STATUS              PORTS               NAMES
93c4836aa4f9        gcr.io/google_containers/hyperkube:v0.14.2   "/hyperkube proxy --   57 minutes ago      Up 57 minutes                           grave_hypatia
29e9b8469e7e        gcr.io/google_containers/hyperkube:v0.14.2   "/hyperkube kubelet    58 minutes ago      Up 58 minutes                           prickly_kowalevski
069d05ea9370        kubernetes/etcd:2.0.5.1                      "/usr/local/bin/etcd   59 minutes ago      Up 59 minutes                           desperate_poincare

However, in the "Test it out" section, when I run the command "kubectl get nodes" to list the nodes in my cluster, I got this exact error:

F0430 19:10:42.257549   27414 get.go:158] Get http://localhost:8080/api/v1beta1/nodes: dial tcp 127.0.0.1:8080: connection refused

rather than the following as shown in the tutorial:

NAME        LABELS    STATUS
127.0.0.1   <none>    Ready

I am not quite sure what causes the issue. From the error above, I notice that the version for is api is v1beta1, which could be an older (deprecated) version of the api. Does anyone have any idea how to resolve the issue?

Thank you very much for your time and support.

Best regards,

**Comment by cjcullen** [comment]
I just tried this out and ran into the same issue. V1beta1 is old, but still works. When I do a docker inspect on my apiserver container, I see that it does not have any PortBindings.

Maybe someone who knows more about this (like @brendandburns) can help us out.

**Comment by jlowdermilk** [comment]
@kcao3, that guide looks out of date. [This](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/locally.md) is the guide that we direct new users to from http://kubernetes.io/gettingstarted/, which should work better for you.

**Comment by sivi** [comment]
release v.1.0.3 has the very same problem, as well as master at the moment

**Comment by linzichang** [comment]
Maybe it due to failed to download the pause image. You may have a check.

**Comment by sivi** [comment]
I cannot recall properly now, yet it seems to me that the reason was one thing, so obvious for seasoned users, and entirely occluded for new: 

**docker software runs as service which has to be started:** *$ sudo systemctl start docker*

The getting-started-guides do not mention that!!! It would save quite a bit of frustrations if it were mentioned.

**Comment by lavalamp** [comment]
Hopefully obsolete now, please reopen if not.

**Comment by anmolnagpal** [comment]
I tried to setup Kubernetes using (https://www.cloudgear.net/blog/2015/5-minutes-kubernetes-setup/). But when i try to run getting below error.

F0131 14:14:04.770583   18807 get.go:70] Client error: Get http://localhost:8080/api/v1beta1/pods?namespace=default: dial tcp 127.0.0.1:8080: connection refused

Also when i checked the logs on api container getting this error.


E0131 10:13:06.441264       1 reflector.go:136] Failed to list *api.ServiceAccount: Get http://127.0.0.1:8080/api/v1/serviceaccounts?fieldSelector=metadata.name%3Ddefault: dial tcp 127.0.0.1:8080: connection refused

**Comment by companycy** [comment]
I follow guide from http://kubernetes.io/docs/getting-started-guides/docker/, and same issue still exists for release 1.1.2.

**Comment by saintx** [comment]
I followed the guide at https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html#start-the-machine and got the same issue.

**Comment by malachib** [comment]
Same (poor) results here also.

**Comment by shu-frank-csdn** [comment]
I also hit this issues, @kcao3 have you fixed it ? I struggle for three hours.
