### ISSUE TITLE
Failed to run Kubelet: unable to parse docker host `127.0.0.1:2376`

### ISSUE THREAD

**Issue by abizake** [kubernetes/kubernetes#75811]
**What happened**:

-  Running docker (18.06.02) behind TLS 

- KUBELET_EXTRA_ARGS=--docker 127.0.0.1:2376 --docker-tls --docker-tls-ca ./ca.pem --docker-tls-cert ./cert.pem --docker-tls-key ./key.pem

-  docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=127.0.0.1:2376 version
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:46:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:48:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false

This gives error : - failed to run Kubelet: unable to parse docker host `127.0.0.1:2376`
 
**What you expected to happen**:
kubelet should start using docker API server behind TLS .

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.3
- Cloud provider or hardware configuration: On Prem (Self VMs)
- OS (e.g: `cat /etc/os-release`):CentOS Linux 7 (Core) (7.4)
- Kernel (e.g. `uname -a`): 3.10.0-957.5.1.el7.x86_64
- Install tools: kubeadm
- Others:

**Comment by liupeng0518** [comment]
--docker tcp://127.0.0.1:2376
