### ISSUE TITLE
Add a scheduler priority function based on node load average

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#75825]
**What would you like to be added**:
In clusters, we find there are some nodes with low load average, and these nodes' most resource are allocated to pods. It might be caused by:

* Pod's request is much bigger than what it needs actually.
* Pod's resource usage has peaks and valleys periodically or irregularly.
* ...

To balance nodes' load, we could add a scheduler priority function based on kubelet node load average(we could add cpu load first), and prefer to schedule pods to those load average is low according to its weight set by administrator.

To implement this feature, we need 2 steps:
* Report node load average through kubelet heart-beat.
* Add scheduler priority function for it.

/sig scheduling
/sig node
/assign

**Comment by hex108** [comment]
It could also be implemented as a plugin for new scheduler framework.

**Comment by xiaoxubeii** [comment]
It duplicates with #73269. There are some concerns about high frequency requests and loads at api-server & etcd level.

**Comment by hex108** [comment]
@xiaoxubeii Thanks for it!
