### ISSUE TITLE
Simple Job Queue

### ISSUE THREAD

**Issue by schmitch** [kubernetes/kubernetes#75821]
**What would you like to be added**:
a simple Job Queue that is based on K8s Jobs

**Why is this needed**:
currently, most of the time, people just need jobs that are queued. of course this can be built by introducing complicated systems like, rabbitmq or kafka, however most of the time (consider IoT) this is too much, people just need something like a "Queue" where they can put QueuedJobs than run with a parallelism of 1 or 2, which can have all the goodies that k8s jobs have (like activeDeadlineSeconds, restartPolicy, whatever).

In a simple fashion this could be as simple as having a QueuedJob, which is like job, but just has a selector label that groups "QueuedJobs" together, so that the kubernetes scheduler will at most start X amount of a Job.

**Comment by danielqsj** [comment]
Do you mean a batch job whose `parallelism == 1` ? Ref: https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/usage/tutorial.md#3-create-a-job

**Comment by schmitch** [comment]
exactly. didn't new there is a sig already. sorry for the inconvenience

**Comment by schmitch** [comment]
Well after looking, I dobut that it works as a simple, queue or am I wrong?

I mean I have jobs comming into my cluster every x minute, I want to run at least 1 or 2 or raise the number dynamically as I scale up workers. But I never want to run more than X, so it's more like maxMember not minMember but I still want all jobs to run, but besides the pod group every job will be completed, so new jobs will be created, which have a activeDeadlineSeconds or restartPolicy. a simple queue for IoT.

**Comment by brentpearson** [comment]
I want a job queue that accepts a job and adds it to the queue. Each job has a spec for the amount of CPU and memory it requires to run. When resources are available to run the job at the front of the queue, it is run. 

Is there anything like this available? If not, I could create the queue part, but I need a way of determining the amount of free resources available in the K8s cluster, and/or whether or not a job is currently supportable by the K8s cluster.
