### ISSUE TITLE
New home for pkg/kubelet/server/streaming

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#75828]
During the CRI-API staging/ work, pkg/kubelet/server/streaming came up as another possibility for a new home as it is being used by many CRI implementations.

- https://github.com/kubernetes/kubernetes/pull/75531#discussion_r269260936
- https://github.com/kubernetes/kubernetes/issues/75293#issuecomment-472259254

So where do we move the code from `pkg/kubelet/server/streaming`? i think i can isolate streaming/remotecommand/portforward, so next thing is to find a home for it.  choices are
- just throw that into cri-api (staging)
- new staging/ directory say cri-runtime (under kubernetes org)
- new repository under kubernetes-sigs/ named cri-runtime with history preserved

Are there other options? Do we really need to do this?

/cc @vbatts @feiskyer @derekwaynecarr @yujuhong 
/sig node

**Comment by dims** [comment]
cc @mikebrow

**Comment by dims** [comment]
There's some discussion on slack at https://kubernetes.slack.com/archives/C0BP8PW9G/p1553777162006400

- this code is something that has been stable, so we do not need to put it through staging/
- many folks already are using cri by default without issue, so we can just create a new repository under `kubernetes-sigs/` github org
- choice of names was either `cri-helpers` or `cri-runtime`
- since we already have a cli-runtime repo which has a set of helpers for implementers, we could use that same pattern. Naming is hard!

Will wait for more feedback

**Comment by mikebrow** [comment]
Prefer cri-helpers over cri-runtime.

If looking for other names kubelet-services or kubelet-streaming would seem to be appropriate repo names. Kubelet-services if you think we'd eventually put more in there - otherwise kubelet-streaming would be a sufficiently descriptive name since `/streaming`, `/remotecommand`, and `/portforward` are libraries for streaming connections to between kubelet and a kubelet container runtime implementing the cri.

**Comment by feiskyer** [comment]
Also prefer cri-helpers for me. Since kubelet server also uses this library, could we create the repository under kubernetes org instead of kubernetes-sigs? I think kubelet doesn't depend on any repositories under kubernetes-sigs today.

**Comment by dims** [comment]
@feiskyer other binaries in k/k do depend on kubernetes-sigs/ so it should be ok. we put cri-api in kubernetes because it's being published from staging/

**Comment by yujuhong** [comment]
> * just throw that into cri-api (staging)

I think we should reconsider this to avoid maintaining/vendoring yet another repository, or at least until we're sure that they should be moved out.

@Random-Liu what do you think?

**Comment by liggitt** [comment]
> > * just throw that into cri-api (staging)
> 
> I think we should reconsider this to avoid maintaining/vendoring yet another repository, or at least until we're sure that they should be moved out.
> 
> @Random-Liu what do you think?

adding streaming server libraries to the api package greatly increases the dependency tree (k8s.io/api, k8s.io/apimachinery, and all their transitive dependencies)

an impl module like `k8s.io/cri-server` makes more sense to me. We've done the same thing for kubernetes types (k8s.io/api is distinct from client and server implementations)
