### ISSUE TITLE
AWS provider is missing tests for ELBv2

### ISSUE THREAD

**Issue by raulcd** [kubernetes/kubernetes#75829]
**What would you like to be added**:
Hi,
while taking a look on issue https://github.com/kubernetes/kubernetes/issues/63959 with PR https://github.com/kubernetes/kubernetes/pull/69263 I was trying to help add tests for the new functionality and I've realised that test coverage is pretty low on the aws module. On the `aws_test.go` file there are no tests for `ELBv2` for example so we cannot test the new functionality for NLB without adding a first round of coverage for it.
Current coverage:
```
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go (29.2%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_fakes.go (59.3%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_instancegroups.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_loadbalancer.go (12.9%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_metrics.go (50.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_routes.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_utils.go (41.7%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/device_allocator.go (72.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/instances.go (89.5%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/log_handler.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/regions.go (100.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/retry_handler.go (46.3%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/sets_ippermissions.go (0.0%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/tags.go (58.6%)
k8s.io/kubernetes/pkg/cloudprovider/providers/aws/volumes.go (12.1%)
```
I plan to work on increasing test coverage for the aws provider.

**Why is this needed**:

New functionality might break existing functionality without realising as the test coverage is a little low.

**Comment by newtondev** [comment]
Mind if I assist with improving the test coverage?

**Comment by raulcd** [comment]
Sure, thanks. I've started but I haven't been able to follow up, I've been busier than expected. I'll be looking and try to review if you are able to work on it.

**Comment by newtondev** [comment]
Hi @raulcd, hope you are well. Have you made any progress with these tests? I have been working on a few. Going to be adding more soon.

**Comment by raulcd** [comment]
I haven't, once you have them you can create a PR and I can review them.
