### ISSUE TITLE
kubelet 'metrics/probes' endpoint uses a gauge instead of counters

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#75839]
Currently the kubelet exports liveness/readiness probe metric information at an [endpoint 'metrics/probes'](https://github.com/kubernetes/kubernetes/blob/5c2fe63591acab508e1ff5771c3aa70268852318/pkg/kubelet/server/server.go#L79). 

The metric data looks like this:

```
# HELP prober_probe_result The result of a liveness or readiness probe for a container.
# TYPE prober_probe_result gauge
prober_probe_result{container="etcd-container",container_name="etcd-container",namespace="kube-system",pod="etcd-server-events-kubernetes-master",pod_name="etcd-server-events-kubernetes-master",pod_uid="",probe_type="Liveness"} 0
prober_probe_result{container="etcd-container",container_name="etcd-container",namespace="kube-system",pod="etcd-server-kubernetes-master",pod_name="etcd-server-kubernetes-master",pod_uid="",probe_type="Liveness"} 0
prober_probe_result{container="fluentd-gcp",container_name="fluentd-gcp",namespace="kube-system",pod="fluentd-gcp-v3.2.0-g7ftb",pod_name="fluentd-gcp-v3.2.0-g7ftb",pod_uid="",probe_type="Liveness"} 0
prober_probe_result{container="kube-apiserver",container_name="kube-apiserver",namespace="kube-system",pod="kube-apiserver-kubernetes-master",pod_name="kube-apiserver-kubernetes-master",pod_uid="",probe_type="Liveness"} 0
prober_probe_result{container="kube-apiserver",container_name="kube-apiserver",namespace="kube-system",pod="kube-apiserver-kubernetes-master",pod_name="kube-apiserver-kubernetes-master",pod_uid="",probe_type="Readiness"} 0
prober_probe_result{container="kube-controller-manager",container_name="kube-controller-manager",namespace="kube-system",pod="kube-controller-manager-kubernetes-master",pod_name="kube-controller-manager-kubernetes-master",pod_uid="",probe_type="Liveness"} 0
prober_probe_result{container="kube-scheduler",container_name="kube-scheduler",namespace="kube-system",pod="kube-scheduler-kubernetes-master",pod_name="kube-scheduler-kubernetes-master",pod_uid="",probe_type="Liveness"} 0
prober_probe_result{container="l7-lb-controller",container_name="l7-lb-controller",namespace="kube-system",pod="l7-lb-controller-v1.2.3-kubernetes-master",pod_name="l7-lb-controller-v1.2.3-kubernetes-master",pod_uid="",probe_type="Liveness"} 0
```

This is incredibly useful metric information, however, it would be better if these metrics were counters rather than gauges. Currently a success probe is registered as a '0' value and a failure is registered as a '1' value. However, depending on your prometheus scrape interval, you can lose bits of information. It would be better if we emitted these metrics as counters.

/sig instrumentation node

**Comment by danielqsj** [comment]
Perhaps a new counters metrics to record the the number of failure is a better option.
Because the gauge metrics is easy to watch and alert.
I can do it if @brancz agree with it.
/assign

**Comment by logicalhan** [comment]
> ...the gauge metrics is easy to watch and alert.

This is a good point. However, if we really did want to use it for this purpose, it would be better if the gauge metric reported '0' for success or else the current running count of failures for a given prober endpoint. With the current implementation, we are needlessly dropping some bits. 

It may be useful to have both. One can provide a more real time signal for alerting but the other gives you better historical data on master component probe results.

**Comment by logicalhan** [comment]
@hulkholden, do you have a preference on gauge vs counter here?

**Comment by hulkholden** [comment]
For our purposes a counter makes much more sense, because we want to use it to figure out the proportion of time something was healthy (e.g. for calculating availability SLOs). It also means we can have a much higher fidelity measurement - e.g. we could ramp up the healthchecks to every 5s but only scrape the results every minute.

> Because the gauge metrics is easy to watch and alert.

Can you point at some examples of people doing this, so I can better understand how these metrics are being used? It seems like using point-in-time samples of health is going to result in noisy alerts, unless you do more work elsewhere to aggregate ("alert if this metric was >0 for X minutes" - which then runs the risk of missing samples, as @logicalhan mentioned)

**Comment by danielqsj** [comment]
@hulkholden if the metrics value is 0 or 1, we can simple set prometheus rule as `metrics > 0 for x minutes` just like you mentioned.

**Comment by logicalhan** [comment]
Yes, I agree that the alert rule would be simple but it also feels prone to be noisy (as @hulkholden mentioned). A failed probe is not necessarily alert-worthy, since the kubelet defers action until the [failureThreshold is reached](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes); by default, the kubelet doesn't do anything until we have 3 consecutive failures.

**Comment by danielqsj** [comment]
> but it also feels prone to be noisy

Yep, so with `for X minutes` in alert rule, it will not fire alert noisily.

/cc @brancz

**Comment by brancz** [comment]
All the facts have already been stated, I'm in favor of removing the gauges and add counters (I don't see a state that we can't interpolate from the counter that the gauge displays today, yet the counter is more reliable in alerting aspects as mentioned).

**Comment by danielqsj** [comment]
@brancz sure.
As a counter, how to represent successful probe?
If the probe is successful, no action is taken, otherwise plus 1 to this metrics ?

**Comment by brancz** [comment]
I'm thinking something along the lines of:

```
prober_probes_total{result="successful",container="etcd-container",container_name="etcd-container",namespace="kube-system",pod="etcd-server-events-kubernetes-master",pod_name="etcd-server-events-kubernetes-master",pod_uid="",probe_type="Liveness"} 5
prober_probes_total{result="failed",container="etcd-container",container_name="etcd-container",namespace="kube-system",pod="etcd-server-events-kubernetes-master",pod_name="etcd-server-events-kubernetes-master",pod_uid="",probe_type="Liveness"} 25
```

**Comment by logicalhan** [comment]
> I'm thinking something along the lines of:
> 
> ```
> prober_probes_total{result="successful",container="etcd-container",container_name="etcd-container",namespace="kube-system",pod="etcd-server-events-kubernetes-master",pod_name="etcd-server-events-kubernetes-master",pod_uid="",probe_type="Liveness"} 5
> prober_probes_total{result="failed",container="etcd-container",container_name="etcd-container",namespace="kube-system",pod="etcd-server-events-kubernetes-master",pod_name="etcd-server-events-kubernetes-master",pod_uid="",probe_type="Liveness"} 25
> ```

Yeah, I was thinking along the same lines (i.e. using the result of the probe as a label).

**Comment by brancz** [comment]
Also now that we're talking about this and inspired by the metrics overhaul of 1.14, we should probably standardize these label values across Kubernetes. I'll add it to the next agenda.

**Comment by jaysonwor** [comment]
A little off topic but wondering if someone could help guide me on how to access this endpoint? I've tried both k8s 1.13 and 1.14 and cannot access metrics/probes (i can only hit /metrics) via the api server http endpoint. Is it exposed somewhere else, or is it a flag I have to enable?

**Comment by munsayac13** [comment]
> A little off topic but wondering if someone could help guide me on how to access this endpoint? I've tried both k8s 1.13 and 1.14 and cannot access metrics/probes (i can only hit /metrics) via the api server http endpoint. Is it exposed somewhere else, or is it a flag I have to enable?

I had this issue for few days. What you should do is in your prometheus.yaml config you have to add "metrics_path: /metrics/cadvisor" as shown below:

`  prometheus.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus-rules/cpu-usage.rules
      - /etc/prometheus-rules/instance-availability.rules
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        metrics_path: /metrics/cadvisor
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:10255'
            target_label: __address__
`
This will scrape out all container metrics that you would like to see.

**Comment by logicalhan** [comment]
> A little off topic but wondering if someone could help guide me on how to access this endpoint? I've tried both k8s 1.13 and 1.14 and cannot access metrics/probes (i can only hit /metrics) via the api server http endpoint. Is it exposed somewhere else, or is it a flag I have to enable?

This isn't an apiserver metric, it's actually a kubelet metric, so it's exposed on a different port. Are you using 8080? I think it should be 10255 or something like that.

**Comment by jaysonwor** [comment]
@ munsayac13  thanks for the suggestion. This is what I ended up doing to solve this:
* update the kubelet servicemonitor (e.g kubectl edit servicemonitor kubelet)
* added this:
- bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    path: /metrics/probes
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

**Comment by kolorful** [comment]
Hi folks,

I wonder if we could add the old gauge metrics back for backward compatibility sake. We just realized this change breaks some of our components that relies on the old metrics during our migrate to v1.15.x.

**Comment by brancz** [comment]
We don’t have stability guarantees on these metrics (or any for that matter). I don’t think we’ll be reintroducing these, but we’re introducing a metrics stability framework for these things to not happen again or have the same deprecation process as kubernetes APIs in the future. Sorry for the inconvenience!

**Comment by kolorful** [comment]
@brancz that is understandable. A quick follow up question about the new metrics: Does the counter number mean how many successful/failed probes happened during this "prometheus scrape interval", or does the number monotonically increase since the creation of the container?
