### ISSUE TITLE
[Kubernetes 1.14.0] Watch on aggregated API resource hangs until first event

### ISSUE THREAD

**Issue by simonferquel** [kubernetes/kubernetes#75837]
**What happened**:

Prior to 1.14, when you created a watch on a resource coming from an aggregated API, you would instantly obtain the `watch.Interface` object, and could stop it when you want.

Since 1.14, when you do the same, the `request.Watch()` method returns when the server sends its first event. Resources directly hosted by the central API-server (core resources, crds, etc.) are not touched by this issue.

When you use higher level APIs like informers, situations like this can make your code hang, as attempts to stop the informer seem ignored (the informer cancellation logic only works once the underlying watch.Interface has been retrieved), and your code hang.

This is hitting https://github.com/docker/cli, and a workaround has been found here: https://github.com/docker/cli/pull/1784. However this change of behavior means that current versions of the CLI can hang when deploying Kubernetes workloads.

**What you expected to happen**:

As with resources hosted by the central API server, the watch.Interface object should be instantly returned

**How to reproduce it (as minimally and precisely as possible)**:

I'll try to setup an automated test case for that with compose-on-kubernetes.
In the mean-time:
- deploy a kube 1.14 cluster with kind / minikube / ...
- deploy compose-on-kubernetes on it (see https://github.com/docker/compose-on-kubernetes/blob/master/docs/install-on-minikube.md)
- download the latest official docker cli release and try to deploy a simple compose file to kubernetes using `docker stack deploy -c compose-file.yml my-stack --orchestrator=kubernetes`

**Anything else we need to know?**:

After digging a little with a debugging http proxy, I saw that the big difference seem to be that:
- prior to 1.14, when such a watch is issued, the response headers are immediately sent to the client
- with 1.14, on central-API resources, it does not change
- with 1.14, on aggregated API resources, the reponse headers are sent with the first event

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T23:47:43Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Using Kind, also happen with internal Docker Desktop builds
- OS (e.g: `cat /etc/os-release`):
Both Kind, and Linuxkit
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fedebongio** [comment]
cc @mbohlool @liggitt

**Comment by liggitt** [comment]
a fix similar to https://github.com/kubernetes/kubernetes/pull/72575 might be required, where headers are flushed after write

**Comment by liggitt** [comment]
looks like watch is flushed here:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/watch.go#L211-L215

**Comment by simonferquel** [comment]
@liggitt please note that the problem manifests itself only for aggregated APIs. My guess is that there is something in the proxy created by kube-aggregator that does not propagate the flush down to the client.

**Comment by liggitt** [comment]
Not seeing issues there, it explicitly flushes on an interval as well: https://github.com/kubernetes/kubernetes/blob/91f40aec8ad5b992d8057b4fab0fa287ee6bdee9/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L232

Also, that code hasn't changed since 1.13

Will try to reproduce locally

**Comment by liggitt** [comment]
Actually, looks like to golang reverse proxy reworked flushing in go1.12: https://github.com/golang/go/commit/5440bfc2ea8c0a4c78d5161605659c07ea10e37a#diff-d863507a61be206d112f6e00e6d812a2

the flushing now takes effect on each body write, but I don't see anything forcing a flush after headers are written 

I'll take the issue upstream

/assign

**Comment by liggitt** [comment]
reported upstream as https://github.com/golang/go/issues/31125

**Comment by simonferquel** [comment]
Really good catch!

**Comment by liggitt** [comment]
workaround added in https://github.com/kubernetes/kubernetes/pull/75887 until we pick up a fix from golang

**Comment by liggitt** [comment]
picked to 1.14.1 in #76046
