### ISSUE TITLE
kubelet stopped posting node status, seems to be hung

### ISSUE THREAD

**Issue by zoramthanga** [kubernetes/kubernetes#75846]
**What happened**:
Pods are not getting created, user requests to create pods seem to just hang forever. We've had to restart kubernetes to get out of the situation. When in this state the only way to kill kubelet is kill -9.

# kubectl describe nodes
Name:               xxxxxxx
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                   beta.kubernetes.io/os=linux
                   kubernetes.io/hostname=a.b.c.d
                   node-role.kubernetes.io/master=
                   stateful=true
Annotations:        alpha.kubernetes.io/provided-node-ip=xxxxx
                   node.alpha.kubernetes.io/ttl=0
                   volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Wed, 20 Feb 2019 11:46:37 +0000
Conditions:
 Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                     Message
 ----             ------    -----------------                 ------------------                ------                     -------
 OutOfDisk        False     Thu, 21 Feb 2019 15:52:21 +0000   Wed, 20 Feb 2019 11:46:33 +0000   KubeletHasSufficientDisk   kubelet has sufficient disk space available
 MemoryPressure   Unknown   Thu, 21 Feb 2019 15:52:21 +0000   Thu, 21 Feb 2019 15:53:02 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
 DiskPressure     Unknown   Thu, 21 Feb 2019 15:52:21 +0000   Thu, 21 Feb 2019 15:53:02 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
 Ready            Unknown   Thu, 21 Feb 2019 15:52:21 +0000   Thu, 21 Feb 2019 15:53:02 +0000   NodeStatusUnknown          Kubelet stopped posting node status. 

**What you expected to happen**:

Users should be able to create new pods and run their workloads.

**How to reproduce it (as minimally and precisely as possible)**:

We do not have specific ways to reproduce it. The problem always shows within one day of running user workloads.

**Anything else we need to know?**:

We collected kubelet goroutine traces, 5 traces collected 3 seconds apart for experts to take a look at and see if something jumps out. May be a deadlock, as the system resource utilization is very low. This has been happening since February and we have looked at it from all kinds of angles; we would really love to have someone take a look and see if it might be a k8s bug.

**Environment**:
- Kubernetes version (use `kubectl version`):

$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.12", GitCommit:"5d26aba6949f188fde1af4875661e038f538f2c6", GitTreeState:"clean", BuildDate:"2018-04-23T23:17:12Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.12", GitCommit:"5d26aba6949f188fde1af4875661e038f538f2c6", GitTreeState:"clean", BuildDate:"2018-04-23T23:09:30Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Baremetal server running on premises.

- OS (e.g: `cat /etc/os-release`):
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
- Kernel (e.g. `uname -a`):
$ uname -r
3.10.0-957.5.1.el7.x86_64
- Install tools:
- Others:

Attaching the goroutine traces of kubelet when the cluster is in state. I will be happy to provide any other additional information that may be required.

[kubelet-goroutine-traces.tar.gz](https://github.com/kubernetes/kubernetes/files/3020194/kubelet-goroutine-traces.tar.gz)

**Comment by liggitt** [comment]
This was fixed in https://github.com/kubernetes/kubernetes/pull/63492 and picked to 1.8.14

FYI, the currently supported versions of Kubernetes are 1.12.x, 1.13.x, and 1.14.x

/close

**Comment by zoramthanga** [comment]
Thanks @liggitt !

**Comment by skandabhatt** [comment]
I'm having the same issue. Is the issue resolved ?. If yes, can anyone provide step by step instructions on resolving the issue?
