### ISSUE TITLE
`kubectl explain` should include the possible values of `crd.status.conditions.type`

### ISSUE THREAD

**Issue by astrieanna** [kubernetes/kubernetes#75842]
**What would you like to be added**:
A comment in `kubectl explain crd.status.conditions` that includes the possible values of `type`.

```
$ kubectl explain crd.status.conditions
KIND:     CustomResourceDefinition
VERSION:  apiextensions.k8s.io/v1beta1
RESOURCE: conditions <[]Object>
DESCRIPTION:
   ....
FIELDS:
  ....
   type	<string> -required-
     Type is the type of the condition. Can be Established, NamesAccepted, or Terminated.
```

I got the possible values from [CustomResourceDefinitionConditionType](https://github.com/kubernetes/kubernetes/blob/e318642946daab9e0330757a3556a1913bb3fc5c/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L270-L280).

The `kubectl explain crd.status.contitions.type` should contain the further explanation available in the linked code that explains what each condition type means.

**Why is this needed**:
Currently the output of `kubectl explain crd.status.conditions` is incomplete:
```
$ kubectl explain crd.status.conditions
KIND:     CustomResourceDefinition
VERSION:  apiextensions.k8s.io/v1beta1

RESOURCE: conditions <[]Object>

DESCRIPTION:
     Conditions indicate state for particular aspects of a
     CustomResourceDefinition

     CustomResourceDefinitionCondition contains details for the current
     condition of this pod.

FIELDS:
   lastTransitionTime	<string>
     Last time the condition transitioned from one status to another.

   message	<string>
     Human-readable message indicating details about last transition.

   reason	<string>
     Unique, one-word, CamelCase reason for the condition's last transition.

   status	<string> -required-
     Status is the status of the condition. Can be True, False, Unknown.

   type	<string> -required-
     Type is the type of the condition.
```
```
$ kubectl explain crd.status.conditions.type
KIND:     CustomResourceDefinition
VERSION:  apiextensions.k8s.io/v1beta1

FIELD:    type <string>

DESCRIPTION:
     Type is the type of the condition.
```

It is important to include the values of `status.conditions.type` because that's the value used to [wait on statuses](https://github.com/kubernetes/kubernetes/issues/66439). It is not user-friendly to require users to guess the possible string values for condition or require them to read the code to deduce what the possible values are.

**Comment by farmer-hutao** [comment]
Please let me do it~

**Comment by danielqsj** [comment]
@farmer-hutao oops, I just notice your message. I already submitted a PR for this.

**Comment by farmer-hutao** [comment]
It's ok~
