### ISSUE TITLE
How to configure a role to query only slave nod

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/kubernetes#75854]
/kind bug

/sig node
@Dawn Chen

**What happened**:
When I configure clusterrole, I can only choose to query all nodes, I want to query only salve nodes, How to configure an implementation to query only slave nodes？

my configuration:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list

Kubectl execution result：
kubectl get node
master1   Ready    master,monitor,node   63d   v1.12.1
master2   Ready    master,monitor,node   63d   v1.12.1
master3   Ready    master,monitor,node   63d   v1.12.1
slave1    Ready    node                  63d   v1.12.1
slave2    Ready    node                  63d   v1.12.1
slave3    Ready    node                  63d   v1.12.1

**What you expected to happen**:
When I execute the kubectl command, I just want to get the slave node.How to realize this?

**How to reproduce it (as minimally and precisely as possible)**:
Run the following command:
kubectl get node

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.1
- OS (e.g: `cat /etc/os-release`):ubuntu16.04

**Comment by YoubingLi** [comment]
ROLES column has been added in the output of "kubectl get node"

 kubectl get node
NAME      STATUS   **ROLES**    AGE    VERSION
ib22b06   Ready    <none>   192d   v1.11.3
ib22b08   Ready    master   193d   v1.11.3

**Comment by YoubingLi** [comment]
Following command could get master node

>>>  kubectl get nodes -l "node-role.kubernetes.io/master"

NAME      STATUS   ROLES    AGE    VERSION
ib22b08   Ready    master   193d   v1.11.3

>>>>   kubectl get nodes --show-labels

NAME      STATUS   ROLES    AGE    VERSION   LABELS
ib22b06   Ready    <none>   192d   v1.11.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=ib22b06
ib22b08   Ready    master   193d   v1.11.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=ib22b08,node-role.kubernetes.io/master=

>>>>  kubectl get nodes --show-labels | grep -v node-role.kubernetes.io/master

NAME      STATUS   ROLES    AGE    VERSION   LABELS
ib22b06   Ready    <none>   192d   v1.11.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=ib22b06

There is not a direct command to get slave nodes.

/closed

**Comment by shigy123456** [comment]
Thank you. I know you i can query slave nodes through label, but when you access apiserver through kubectl, can you access only slave nodes through role control?

**Comment by YoubingLi** [comment]
@shigy123456 

     The answer is "NO".

     BTW, a node Role is just a label.

**Comment by liggitt** [comment]
No, labels are not included in attributes available to the authorization layer. Only immutable attributes like API group, resource type, name, and namespace are able to be used for authorization

**Comment by shigy123456** [comment]
@liggitt  How to configure pod to operate on only one namespace ?

**Comment by liggitt** [comment]
Permissions can be granted in a single namespace with a RoleBinding in that namespace. The API calls to only look up objects within that namespace (as opposed to looking up objects across all namespaces) would have to be supported by the application

**Comment by shigy123456** [comment]
@liggitt ok,thanks
