### ISSUE TITLE
Kubelet: Sanitize user-provided input for runtimes

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#7585]
This is specifically for the rkt runtime. Today we accept a bunch of user-generated fields and concatenate them into a string to execute. We should be wary of what this input is as ensure that we escape it correctly.

This is more an an FYI and a note to do an audit, nothing critical at this time.

/cc @yifan-gu @dchen1107 @jonboulle

**Comment by jonboulle** [comment]
Sgtm. In the appc spec we try to be restrictive about this in many places
using the ac name type.
Am 30.04.2015 13:17 schrieb "Victor Marmol" <notifications@github.com>:

**Comment by spzala** [comment]
@vmarmol hi, just a gentle touch base since it's been two years of this issue was last discussed. Do we still want to keep it open or can we please close it? Thanks!
