### ISSUE TITLE
k8s 应用程序写日志导致容器内存使用率越来越高

### ISSUE THREAD

**Issue by liuhaibo0303** [kubernetes/kubernetes#75870]
**What would you like to be added**:
我的环境：
kubernetes v13
promethues v2.4.3
granfana 5.2.4

我遇到的问题：
容器以hostpath方式挂载了宿主机的一个目录，容器内部的应用程序写日志到这个挂载的目录，运行了一段时间以后，我在grafana的监控页面发现容器占用的内存越来越多，但是进入容器以后发现应用程序占用的内存是正常的，查询了一些资料以后发现容器使用的cahce内存会被当做实际使用的内存，所以，当我删除一部分日志文件以后，监控显示容器的占用的内存就会降下来。
我想问下，如果grafana显示的内存=容器实际使用的内存+容器使用的cache内存，那么我在k8s的deployment中定义的容器内存最大限制岂不是随着时间的推移，越来越接近，最终会达到这个最大限制而导致我们的pod被kill掉

**Why is this needed**:
容器的监控数据和deployment里面的最大内存限制是否可以按照容器的实际占用内存来

**Comment by WanLinghao** [comment]
First of all, please use English instead of Chinese.
The cache memory container using is still memory, I am not sure we should change this.
I guess the problem is you mount some vfs to the container like tmpfs. You should not do this.
/close

**Comment by Vicyangkang** [comment]
> **What would you like to be added**:
> 我的环境：
> kubernetes v13
> promethues v2.4.3
> granfana 5.2.4
> 
> 我遇到的问题：
> 容器以hostpath方式挂载了宿主机的一个目录，容器内部的应用程序写日志到这个挂载的目录，运行了一段时间以后，我在grafana的监控页面发现容器占用的内存越来越多，但是进入容器以后发现应用程序占用的内存是正常的，查询了一些资料以后发现容器使用的cahce内存会被当做实际使用的内存，所以，当我删除一部分日志文件以后，监控显示容器的占用的内存就会降下来。
> 我想问下，如果grafana显示的内存=容器实际使用的内存+容器使用的cache内存，那么我在k8s的deployment中定义的容器内存最大限制岂不是随着时间的推移，越来越接近，最终会达到这个最大限制而导致我们的pod被kill掉
> 
> **Why is this needed**:
> 容器的监控数据和deployment里面的最大内存限制是否可以按照容器的实际占用内存来

我也遇到这个问题，最后是怎么解决的呢

**Comment by 573009114** [comment]
> > **您想添加什么**：
> > 我的环境：
> > kubernetes v13 
> > promethues v2.4.3 
> > granfana 5.2.4
> > 我遇到的问题：
> > 容器以hostpath方式挂载了宿主机的一个目录，容器内部的应用程序写日志到这个挂载的目录，运行了一段时间以后，我在grafana的监控页面发现容器占用的内存越来越多，但是进入容器以后发现应用程序占用的内存是正常的，查询了一些资料以后发现容器使用的cahce内存会被当做实际使用的内存，所以，当我删除一部分日志文件以后，监控显示容器的占用的内存就会降下来。
> > 我想问下，如果grafana显示的内存=容器实际使用的内存+容器使用的高速缓冲存储器内存，那么我在K8S的部署中定义的容器内存最大限制岂不是随着时间的推移，越来越接近，最终会达到这个最大限制而导致我们的吊舱被杀灭掉
> > **为什么需要这样**：
> > 容器的监控数据和部署里面的最大内存限制是否可以按照容器的实际占用内存来
> 
> 我也遇到这个问题，最后是怎么解决的呢

我也遇到了。怎么解决呢？

**Comment by xiaowuwu163** [comment]
我也遇到了这个问题，请问你解决了吗，能否提供一下方案，谢谢。

**Comment by paleyoupa** [comment]
一样的问题，pod跑久了，日志的空间全算到container_memory_usage_bytes里面了，几十个G

**Comment by liuhaibo0303** [comment]
没有解决，只能定期删除日志。。。。这样grafana显示的内存大小才会降下来

**Comment by ppulse** [comment]
> 没有解决，只能定期删除日志。。。。这样grafana显示的内存大小才会降下来

We solve this problem by update linux kernel version to 4.15

**Comment by jinxuan-LY** [comment]
java + logback 日志框架也遇到相同的问题，减小归档数量缓解了这个问题。

**Comment by yourihua** [comment]
这个问题依然没有解决么
