### ISSUE TITLE
one gpu card allocated to two pods

### ISSUE THREAD

**Issue by leopoldxx** [kubernetes/kubernetes#75880]
**What happened**:
we observed that, on some nodes, the gpu card has been allocated to two pods. 
```json
# cat kubelet_internal_checkpoint  | python -m json.tool
{
    "Checksum": 3364951114,
    "Data": {
        "PodDeviceEntries": [
            {
                "AllocResp": "CkIKFk5WSURJQV9WSVNJQkxFX0RFVklDRVMSKEdQVS1hZDYzYzY4NC01NTkzLTExMWEtY2JiMS1jMTQ1MWViY2QwYWE=",
                "ContainerName": "notebook",
                "DeviceIDs": [
                    "GPU-ad63c684-5593-111a-cbb1-c1451ebcd0aa"
                ],
                "PodUID": "9a422c32-4fc2-11e9-bb64-505dac4c3a38",
                "ResourceName": "nvidia.com/gpu"
            },
            {
                "AllocResp": "CkIKFk5WSURJQV9WSVNJQkxFX0RFVklDRVMSKEdQVS03MmNiZjcyMy05ZjcwLTdkNDktYTZiYi02MjZmY2IzZjhjMzA=",
                "ContainerName": "notebook",
                "DeviceIDs": [
                    "GPU-72cbf723-9f70-7d49-a6bb-626fcb3f8c30"
                ],
                "PodUID": "368e63c4-2d97-11e9-8954-505dac4a7d28",
                "ResourceName": "nvidia.com/gpu"
            },
            {
                "AllocResp": "CkIKFk5WSURJQV9WSVNJQkxFX0RFVklDRVMSKEdQVS03ODU5YWNiMi03NGE2LTFlZTEtNjkyMS03MWJjN2RhYzQ3NDc=",
                "ContainerName": "notebook",
                "DeviceIDs": [
                    "GPU-7859acb2-74a6-1ee1-6921-71bc7dac4747"
                ],
                "PodUID": "6aa6a123-38ae-11e9-a279-505dac4a78ba",
                "ResourceName": "nvidia.com/gpu"
            },
            {
                "AllocResp": "CkIKFk5WSURJQV9WSVNJQkxFX0RFVklDRVMSKEdQVS0zOWMxY2VlZC04NTg0LThmMzAtNjIzZC0wMGUwNDEyY2FlOGY=",
                "ContainerName": "notebook",
                "DeviceIDs": [
                    "GPU-39c1ceed-8584-8f30-623d-00e0412cae8f"
                ],
                "PodUID": "9a8fe92f-4f74-11e9-bb64-505dac4c3a38",
                "ResourceName": "nvidia.com/gpu"
            }
        ],
        "RegisteredDevices": {
            "nvidia.com/gpu": [
                "GPU-ad63c684-5593-111a-cbb1-c1451ebcd0aa",
                "GPU-72cbf723-9f70-7d49-a6bb-626fcb3f8c30",
                "GPU-7859acb2-74a6-1ee1-6921-71bc7dac4747",
                "GPU-39c1ceed-8584-8f30-623d-00e0412cae8f"
            ]
        }
    }
}

```
```txt
# for cid in `docker ps | grep '9a422c32-4fc2-11e9-bb64-505dac4c3a38\|368e63c4-2d97-11e9-8954-505dac4a7d28\|6aa6a123-38ae-11e9-a279-505dac4a78ba\|9a8fe92f-4f74-11e9-bb64-505dac4c3a38' | grep -v pause | awk '{print $1}'`; do echo $cid; docker  exec   $cid sh -c 'env | grep -i gpu ; export LC_ALL=en_US.UTF-8; ls -al /dev/nvidia*'; done
574f84a549c8
NVIDIA_VISIBLE_DEVICES=GPU-ad63c684-5593-111a-cbb1-c1451ebcd0aa
crw-rw-rw- 1 root root 195,   3 Nov 30 19:25 /dev/nvidia3
c109104a6d52
NVIDIA_VISIBLE_DEVICES=GPU-39c1ceed-8584-8f30-623d-00e0412cae8f
crw-rw-rw- 1 root root 195,   2 Nov 30 19:25 /dev/nvidia2
3056850687db
NVIDIA_VISIBLE_DEVICES=GPU-ad63c684-5593-111a-cbb1-c1451ebcd0aa
crw-rw-rw- 1 root root 195,   3 Nov 30 19:25 /dev/nvidia3
a7b6795e788c
NVIDIA_VISIBLE_DEVICES=GPU-39c1ceed-8584-8f30-623d-00e0412cae8f
crw-rw-rw- 1 root root 195,   2 Nov 30 19:25 /dev/nvidia2
```
` /dev/nvidia2` and  `/dev/nvidia3` are mounted into two pods separately. 

i investigate the code and  do some tests, find that the situation was caused by an upgrade from 1.10.5 to 1.11.6。

kubelet 1.10.5 and kubelet 1.11.6 have different device-plugin checkpoint struct, kubelet 1.11.6 can't parse infomation from the checkpoint file created by kubelet 1.10.5.  so the device allocated info stored in checkpoint file will be lost after the upgrade.

after restart the kubelet process,  the pod, which has already been running on the node and needs gpu devices, will do admits. when it is handled by predicateAdmitHandler, `pluginResourceUpdateFunc` will allocate new gpu devices for the pod because kubelet knows nothing about the previous allocated info.

then create a new pod with gpu, the pod maybe get a gpu id which is new in kubelet 1.11 but already allocated to an old pod in kubelet 1.10.

i think the device-plugin manager's `readCheckpoint()` function should know how to parse  previous version struct and load checkpoint info correctlly.

/sig Resource Management

**What you expected to happen**:
every pod has a distinct gpu card.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

kubernets upgrade from 1.10.5 to 1.11.6

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

**Comment by ogre0403** [comment]
@leopoldxx 
Do you have idea to fix this problem ? 

I think the current solution is remove all running pod on the node, then let kubelet 1.11 know all GPU information. New allocated pod can be assigned correct GPU. 

We upgrade our bare metal cluster from 1.10.10 to 1.11.10 last week. Today we notice that if  nodes that have pod scheduled by old and new version, GPU on this node might be allocated to different pod.
