### ISSUE TITLE
Windows docs claim MountPropagationHostToContainer is supported, but internals suggest otherwise

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#75906]
**What happened**:

Windows documentation [here](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/windows/intro-windows-in-kubernetes.md) claims:

>V1.VolumeMount.mountPropagation - only MountPropagationHostToContainer is available. 

However, the internals suggest otherwise; `runtimeapi.MountPropagation_PROPAGATION_PRIVATE` is always returned on Windows:
https://github.com/kubernetes/kubernetes/blob/484043a6d15973e20e35405a3acab862bc75ad5f/pkg/kubelet/kubelet_pods.go#L272-L292

Either the docs should be corrected, or the Kubelet should be updated, or we should have a comment on why this does in fact enable MountPropagationHostToContainer on Windows.

/cc @PatrickLang @yujuhong @pjh 
/sig windows

**Comment by jingxu97** [comment]
I think the doc is not accurate. The kubernetes.io doc https://kubernetes.io/docs/setup/windows/ claims the same thing. 

For MountPropagationHostToContainer option, we can test it whether it is working or not.

**Comment by michmike** [comment]
i created two PRs to address the documentation gap. we will also test this and get back to this thread.

**Comment by mtaufen** [comment]
For 1.15 we may need to update Kubelet code to allow HostToContainer. @PatrickLang
