### ISSUE TITLE
Kubeadm: Allow overriding KubeletRunDirectory

### ISSUE THREAD

**Issue by ygalblum** [kubernetes/kubernetes#75902]
**What would you like to be added**:
Currently, the user can change kubelet's run-time directory by setting "root-dir" in the kubeletExtraArgs field of nodeRegistration object. While this flag does alter kubelet's behavior, kubeadm still writes the configuration files for kubelet under /var/lib/kubelet.

So, kubeadm should have its own parameter for the kubelet run-time directory to which it will write the configuration files. It can also pass the value of this parameter (if provided) to kubelet instead of using the kubeletExtraArgs map.

**Why is this needed**:
I'm running K8S on a VM with two volumes - a limited boot volume and a configurable (to be much larger) data volume. So, I'm trying to move run-time data from the boot volume to the data volume. I've already set docker and kubelet to use the data volume, and I would like to have kubeadm do the same 

@kubernetes/sig-cluster-lifecycle-feature-requests
/sig cluster-lifecycle

**Comment by neolit123** [comment]
please re-open the ticket in kubernetes/kubeadm 
thanks.

/close
