### ISSUE TITLE
GKE: NFS PV's don't recover NFS reconnect: Stale file handle

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#75918]
**What happened**:
Following the restart of an NFS server, pods with PersistentVolumes mounting the NFS shares get stuck with a `Stale file handle`

This can be observed on the node:

```
gke-delivery-platform-vds-20190308-b80738e3-stqk ~ # ls /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/49f22ce7-52f1-11e9-a541-42010aa40179/volumes/kubernetes.io~nfs/vds-solr-backups
ls: cannot access '/home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/49f22ce7-52f1-11e9-a541-42010aa40179/volumes/kubernetes.io~nfs/vds-solr-backups': Stale file handle
```

In dmesg you can see:
```
[184074.486065] nfs: server nfs.vds-solr.svc.cluster.local not responding, timed out
[184077.109838] nfs: server nfs.vds-solr.svc.cluster.local not responding, timed out
[184081.319496] NFS: server nfs.vds-solr.svc.cluster.local error: fileid changed
                fsid 0:86: expected fileid 0xe13cc, got 0xe13a9
[184081.332603] NFS: server nfs.vds-solr.svc.cluster.local error: fileid changed
                fsid 0:86: expected fileid 0xe13cc, got 0xe13a9
[184081.345804] NFS: server nfs.vds-solr.svc.cluster.local error: fileid changed
                fsid 0:86: expected fileid 0xe13cc, got 0xe13a9
```

Restating the pod, causing an umount and mount resolves the issue.

PV Template:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vds-solr-backups
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  mountOptions:
  - soft
  - nfsvers=4.1
  - timeo=50
  - retry=5
  - actimeo=5
  - noatime
  - nodiratime
  - rsize=32768
  - wsize=32768
  - intr
  nfs:
    path: /
    server: nfs.vds-solr.svc.cluster.local
  persistentVolumeReclaimPolicy: Delete
```

The export definition on the server is:
```
/exports *(rw,fsid=0,insecure,no_root_squash)
```

**What you expected to happen**:
When the NFS server restarts, the nfs client should reconnect, not leaving NFS mounts in a broken state.

**How to reproduce it (as minimally and precisely as possible)**:

 - Run an NFS server pod
 - Create a PV referencing it
 - Use that PV on another pod
 - Restart the NFS server pod
 - Observe the broken mount on the other pod

**Environment**:
- GKE v1.12.6-gke.7

**Comment by Stono** [comment]
@kubernetes/sig-storage-bugs

**Comment by Stono** [comment]
Also tested on `v1.12.5-gke.10` - same issue

**Comment by Stono** [comment]
Hello, 
I have gotten further debugging this issue.

For context, we use a simple `nfs` pod which shares an `emptyDir` volume for the purposes of some ephemeral shared scratch storage between a bunch of other applications.  If the nfs server restarts, we don't care about the contents of the share.

When you delete the pod, obviously the emptyDir is effectively a new "emptyDir", but on another node.  

I believe this is where the `StaleFileHandler` is coming from, as the directory that the old clients had mounted, has now gone.

I tested this by switching to a GCEPersistentDisk for the `/exports` folder on the NFS server, and restarted the POD and **did not** see `StaleFileHandler`.

So fundamentally:  Don't run an NFS server on docker which shares an emptyDir or any other ephemeral storage.

I would expect the remount to refresh the content from a clients perspective though, especially as the server sets `fsid=0`, but this is perhaps more of an nfs client issue?  I'm not sure.

**Comment by verult** [comment]
/

**Comment by prinf** [comment]
Having the same on 1.12.6-gke.10

**Comment by psycho-ir** [comment]
any update on this bug?

**Comment by msau42** [comment]
@psycho-ir are you seeing the issue with a pd-backed nfs server?

Backing an nfs share with an ephemeral data store that can change is not recommended.

**Comment by psycho-ir** [comment]
@msau42 Yes I used persistent disks and could reproduce it again.
Actually the same thing is happening out of GKE in on premise k8s cluster.

**Comment by msau42** [comment]
Can you give some more details of your nfs server, client pods and repro steps?

**Comment by psycho-ir** [comment]
I just tried another [nfs-server docker image](https://hub.docker.com/r/itsthenetwork/nfs-server-alpine/).

and now my client reconnects on restarts.
sorry to bother, looks like the docker image I was using hadn't been configure properly!

**Comment by msau42** [comment]
Thanks for the update. Closing this issue for now
/close
