### ISSUE TITLE
Container build interface

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#75919]
Hey 👋, if you think this is totally out of scope of Kubernetes feel free to close this one.

**What would you like to be added:**
The idea is to have a container build interface similar to the container runtime interface. Different container build tools could implement it to provide native OCI compliant container build support within Kubernetes, handled directly by the Kubelet. The image build process could be implemented as a new Kubernetes resource and needs to be stored in a registry on success.

**Why is this needed:**
Building images within Kubernetes is a real world use case but implies security related concerns. Having an consistent API would make a lots of custom solutions obsolete and improve the overall security.

**Comment by liggitt** [comment]
This was discussed at length in https://github.com/kubernetes/kubernetes/issues/1806#issuecomment-381787549 and closed as out of scope. 

It looks like there was an effort to do something along these lines at https://github.com/containerbuilding/cbi

/close
