### ISSUE TITLE
kubectl get csr No resources found.

### ISSUE THREAD

**Issue by Kal-spj** [kubernetes/kubernetes#75925]
When I manually deployed k8s, after master and node were both completed, kubectl got CSR, showing "No resources found." this problem has troubled me for a long time, I hope to get help!!!

**Comment by liggitt** [comment]
if there are no active csrtificate signing requests, then that message will be returned

/close

**Comment by hemkvo** [comment]
failed to run Kubelet: cannot create certificate signing

**Comment by hemkvo** [comment]
failed to run Kubelet: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "10001" cannot create resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope

**Comment by zhongwandong** [comment]
I have same one
