### ISSUE TITLE
Failed to setup cluster via local-up-cluster.sh

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#75929]
**What happened**:

Failed to setup cluster via `local-up-cluster.sh` in master branch.

```
use 'kubectl --kubeconfig=/var/run/kubernetes/admin-kube-aggregator.kubeconfig' to use the aggregated API server
hack/local-up-cluster.sh: line 633: node_cidr_args[@]: unbound variable
Cleaning up...
hack/local-up-cluster.sh: line 339: wait_for: No record of process 9141
...
2019/03/31 19:46:32 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
/go/src/k8s.io/kubernetes/hack/lib/util.sh: line 562:  8653 Terminated              etcd --advertise-client-urls "${KUBE_INTEGRATION_ETCD_URL}" --data-dir "${ETCD_DIR}" --listen-client-urls "${KUBE_INTEGRATION_ETCD_URL}" --debug 2> "${ETCD_LOGFILE}" > /dev/null
The connection to the server localhost:6443 was refused - did you specify the right host or port?
Kube-dns addon successfully deployed.
hack/local-up-cluster.sh: line 782: cni_conf_dir_args[@]: unbound variable
Cleaning up...
```

Perhaps related with https://github.com/kubernetes/kubernetes/pull/75662.

@s-ito-ts @dims 

**What you expected to happen**:

Run `local-up-cluster.sh` without error.

**How to reproduce it (as minimally and precisely as possible)**:

./hack/local-up-cluster.sh

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by WanLinghao** [comment]
Same error happens in my environment

**Comment by s-ito-ts** [comment]
@danielqsj 
Could you tell us more about error conditions?
  - What option did you specify to local-up-cluster.sh?
  - What version of bash do you use?

**Comment by danielqsj** [comment]
@s-ito-ts  
1. no other options, just `hack/local-up-cluster.sh`
2. bash version: `GNU bash, version 4.3.48(1)-release-(x86_64-pc-linux-gnu)`

**Comment by danielqsj** [comment]
@s-ito-ts which env were you testing in your PR ?
Have you tested it in Linux environment ?

**Comment by s-ito-ts** [comment]
@danielqsj

I tested in the following environment.

GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Ubuntu 18.04

**Comment by mrunalp** [comment]
We are seeing this issue on RHEL 7.

$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by mrunalp** [comment]
I have opened https://github.com/kubernetes/kubernetes/pull/75994 as a possible fix.
