### ISSUE TITLE
kube-api container keep restarting with leader node failure

### ISSUE THREAD

**Issue by pavel75** [kubernetes/kubernetes#75937]
**What happened**:
When leader node is down in 3 node HA cluster, kube-api host continue restating in loop in other 2 master node. 

Kube-controll-manager showed following error. 

error retrieving resource lock kube-system/kube-controller-manager: endpoints \"kube-controller-manager\" is forbidden: User \"system:kube-controller-manager\" cannot get resource \"endpoints\" in API group \"\" in the namespace \"kube-system\"\n","stream":"stderr","time":"2019-04-01T03:26:58.992389187Z"}
**What you expected to happen**:
with single master node failure cluster should function normal

# kubectl describe clusterrole system:kube-controller-manager
Name:         system:kube-controller-manager
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
PolicyRule:
  Resources                           Non-Resource URLs  Resource Names  Verbs
  ---------                           -----------------  --------------  -----
  secrets                             []                 []              [create delete get update]
  endpoints                           []                 []              [create get update]
  serviceaccounts                     []                 []              [create get update]
  events                              []                 []              [create patch update]
  tokenreviews.authentication.k8s.io  []                 []              [create]
  configmaps                          []                 []              [get]
  namespaces                          []                 []              [get]
  *.*                                 []                 []              [list watch]

**How to reproduce it (as minimally and precisely as possible)**:
https://kubernetes.io/docs/setup/independent/ha-topology/#stacked-etcd-topology

**Anything else we need to know?**:
Pod Security policy implemented in cluster

**Environment**:
- Kubernetes version (use `kubectl version`):
# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
On-prem VM

- OS (e.g: `cat /etc/os-release`):
RHEL 7
- Kernel (e.g. `uname -a`):
3.10.0-514.26.2.el7.x86_64

- Install tools:
Kubeadm 

- Others:

**Comment by neolit123** [comment]
please re-open the same ticket in kubernetes/kubeadm.
also please include information about your load balancer.

/area kubeadm
/close
