### ISSUE TITLE
Test coverage for pod quality of service

### ISSUE THREAD

**Issue by pontiyaraja** [kubernetes/kubernetes#75935]
**What happened**:
There is no complete test coverage for the Resource quality of service. There is only one test case is there for Guaranteed QoSClass. There is few important things to cover the test case, 
Please refer the QOS [proposal doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md)

**What you expected to happen**:
Test cases to cover : 
- Excess CPU resources will be distributed based on the amount of CPU requested. For example, suppose container A requests for 600 milli CPUs, and container B requests for 300 milli CPUs. Suppose that both containers are trying to use as much CPU as they can. Then the extra 100 milli CPUs will be distributed to A and B in a 2:1 ratio (implementation discussed in later sections)
- Pods will be throttled if they exceed their limit. If limit is unspecified, then the pods can use excess CPU when available
- Pods will get the amount of memory they request, if they exceed their memory request, they could be killed (if some other pod needs memory), but if pods consume less memory than requested, they will not be killed (except in cases where system tasks or daemons need more memory)
- When Pods use more memory than their limit, a process that is using the most amount of memory, inside one of the pod's containers, will be killed by the kernel
- Test case for Burstable and BestEffort

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@vishh @AnanyaKumar @kubernetes/sig-testing

**Comment by pontiyaraja** [comment]
@kubernetes/sig-testing

**Comment by cblecker** [comment]
/remove-sig testing
/sig node

Specific test coverage is the responsibility of the sig.

**Comment by mattjmcnaughton** [comment]
Thanks for thinking proactively about test coverage :)

At a high level, I'd love to chat about what types of tests (unit, integration, e2e...) are appropriate for each of these, re my comment here: https://github.com/kubernetes/kubernetes/pull/76129#pullrequestreview-223548067.

**Comment by pontiyaraja** [comment]
@mattjmcnaughton please refer my comment https://github.com/kubernetes/kubernetes/pull/76129#issuecomment-480556675

**Comment by mgdevstack** [comment]
**I feel that main intention of this issue to cover/verify QoS** (_Description has been added for wider range of resource utilisation as an umbrella issue_). 

Kubernetes provides different levels of Quality of Service to pods depending on what they request. Here we should verify that, when different `resource.request` and `resource.limit` are specified to the containers of the pod, does appropriate level of QoS ( Guaranteed, Burstable, and Best-Effort) assigned to `PodStatus.qosClass`?

Scenario could be:-  (Only QoS related e2e should be tracked here, no `container.resource` or `Limitrange` specific, they should fall under their area more precisely)
**Name**: Pod, QoS, when resources specified 
**e2e**: Pod should assign effective QoS in podStatus when resource request and limits are specified.
**Description:** Create a pod with 2 containers with specified resources-
1. podStatus MUST have `Guaranteed` Qos : If limits and optionally requests (not equal to 0) are set for all resources across all containers and they are equal
2. podStatus MUST have `Burstable` Qos : if requests and optionally limits are set (not equal to 0) for one or more resources across one or more containers, and they are not equal
3.  podStatus MUST have `Best-Effort` Qos : If requests and limits are not set for all of the resources, across all containers

**Comment by mgdevstack** [comment]
@pontiyaraja, 
1. This is dup of #76128, (for `qosClass`)
2. Based on your Issue description, #77973 can have detailed discussion about `podSpec.resource` API coverage and related PR's can be tracked there.

I would suggest to close this issue because of above two reasons.

**Comment by spiffxp** [comment]
@mattjmcnaughton I agree in principle with erring on the side of unit tests for more comprehensive code coverage.  However we only use e2e tests when it comes to certifying a kubernetes cluster as conformant. So the question becomes which test cases exactly would we expect all kubernetes clusters to support.  I think @mgdevstack's suggestion above is reasonable, WDYT?

**Comment by mattjmcnaughton** [comment]
@spiffxp you make a good point about conformance tests - so I agree :)

**Comment by timothysc** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/76345
