### ISSUE TITLE
fsType parameter is ignored in AWS StorageClass

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#75941]
**What happened**:
In Kubernetes 1.12 and 1.13, AWS StorageClass parameters are parsed as case-sensitive (`fstype`) and [our example](https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs) with `fsType` does not work:

https://github.com/kubernetes/kubernetes/blob/b08e9b0b4de65d5173c94f6ec3831081a9bdcbca/pkg/volume/aws_ebs/aws_util.go#L120-L122

In 1.11 and older it was working OK (case-insensitive). In 1.14 it was fixed as side-product of storage e2e test refactoring, https://github.com/kubernetes/kubernetes/pull/70823

https://github.com/kubernetes/kubernetes/blob/997d5182d0508d29612223fad9e2d10d3de73877/pkg/volume/awsebs/aws_util.go#L125-L129

**Comment by leakingtapan** [comment]
Thx @jsafrane for putting the fix. 

Could you cc me next time whenever there is any changes happening on the in-tree EBS plugin? Keeping feature compatibility between in-tree plugin and CSI is challenging before k/k ebs e2e test is reused for EBS CSI driver

**Comment by jsafrane** [comment]
It has been fixed in all supported branches
/close
