### ISSUE TITLE
tokenCleaner Informer is slowing down apiserver

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#75945]
**Why is this needed**:

Lately we enabled `tokenCleaner` in controller-manager and found this.

![image](https://user-images.githubusercontent.com/5449021/55313690-fd20e900-549a-11e9-982f-4a75cafb771c.png)

`Secrets` are pulled frequently and the response payload of each request is about 10MB. Actually current informer for `tokencleaner` will list all secrets in all namespaces. This should be avoided I think, since we only care about `kube-system` namespace.

And with more secrets are created in other namespaces, this will definitely affect the performances of apiserver.

/sig apps

**Comment by liggitt** [comment]
do you have evidence that these two controllers specifically are responsible for the spikes seen?

**Comment by lavalamp** [comment]
I agree with @liggitt. I would expect this to just make it worse, as now it will poll all and additionally kube-system.

A better avenue to investigate might be to figure out why it is polling and not watching.
