### ISSUE TITLE
http: proxy error: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by aliridha1510** [kubernetes/kubernetes#75955]
C:\Users\username\Desktop\kub>kubectl.exe  proxy 
Starting to serve on 127.0.0.1:8001 
I0401 13:20:30.461961    5940 log.go:172] http: proxy error: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it

$ kubectl.exe config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

**Comment by neolit123** [comment]
please provide more details about your setup:
k8s version
windows version

/triage support
/remove-kind bug
/sig windows

**Comment by aliridha1510** [comment]
$ kubectl.exe version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

Windows 10 Entreprise
64-Bit

**Comment by aliridha1510** [comment]
it is missing folder called . kube and config file  and then runs

**Comment by nezoic** [comment]
> it is missing folder called . kube and config file and then runs

I'm not sure what this means. Do you need a .kube folder created in the same location you're running kubectl in, along with the config file?
