### ISSUE TITLE
pvc_protection_controller queries local cache instead of apiserver(s)

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#75980]
**What happened**:
After studying https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/postpone-pvc-deletion-if-used-in-a-pod.md I thought of an optimization and checked the current implementation to see if it is there.  Instead I found that the current implementation makes a critical mistake: it only checks the local cache and never the live apiserver(s) (see https://github.com/kubernetes/kubernetes/blob/255a73ffc64d1c4e0f9a378ebf8d0005edfe6962/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L212).  Following is a scenario in which the current implememtation allows the removal of a PVC while it is in use by a Pod.  Start in a state where the PVC exists, has the finalizer, and is bound.  Next a Pod API object is created.  Then the Pod is scheduled and the relevant kubelet is notified and begins work on that Pod.  That kubelet queries an apiserver, which queries the etcd cluster holding PVC objects (which may or may not be the same as the etcd cluster holding Pod objects), and finds out that the PVC exists and is not being deleted.  The kubelet finishes creating and starting the Pod.  Then some client requests deletion of the PVC.  Its DeletionTimestamp is set.  Then the pvc_protection_controller is notified about this change to the PVC.  Note that I did _not_ say that the pvc_protection_controller has by now been notified about the creation or scheduling of the Pod.  This is possible, because we have no guarantee about ordering of notifications about different Kinds of objects.  The pvc_protection_controller queries its Pod informer's local cache of Pod information and does not find the new Pod.  The pvc_protection_controller then removes the Finalizer from the PVC, and soon the PVC API object is removed.

**What you expected to happen**:
I expected to see that https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/pvcprotection/pvc_protection_controller.go follows the community design doc or includes an optimization to avoid the apiserver check if the local cache shows usage of the PVC.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
Yes, that happens before the start point of the scenario I outlined.

**Comment by MikeSpreitzer** [comment]
Updated the original description to explicitly say that the PVC has the finalizer at the start of the scenario.

**Comment by MikeSpreitzer** [comment]
Nobody is assigned to this issue.  How does that get changed?

**Comment by jsafrane** [comment]
> Nobody is assigned to this issue. How does that get changed?

If you're project member, you can assign it to yourself by creating comment with `/assign`. But nothing prevents you from creating PR without this issue assigned to you ;-).

**Comment by matte21** [comment]
I'm the author of the duplicate issue #76703, and I'd like to work on this. It would be my first contribution, there might be some friction associated with that.

**Comment by MikeSpreitzer** [comment]
No friction, it is perfectly normal for someone who raises an issue to submit a PR to fix it.
