### ISSUE TITLE
Kubectl plugin not working on Windows

### ISSUE THREAD

**Issue by Myslik** [kubernetes/kubernetes#75981]
**What happened**: Running `kubectl hello` results in `not supported by windows`

**What you expected to happen**: `kubectl-hello.bat` from PATH gets executed

**How to reproduce it (as minimally and precisely as possible)**: Add `kubetl-hello.bat` somewhere to PATH

```
ECHO Hello!
```

**Anything else we need to know?**:
Could it be related to this? https://github.com/golang/go/issues/30662

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows 10 (Build 17763.379)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Myslik** [comment]
Can I somehow help with this?

**Comment by annkara** [comment]
@Myslik Seeing [this pull request](https://github.com/kubernetes/kubernetes/commit/dd9ae9a1d2ab5654c62d83371bd1f53965bff1e6#diff-f23cc6c004fbd8a713f8465465142ab8), I think this issue will be solved at the next release.

**Comment by Myslik** [comment]
@annkara It seems so. #76227
