### ISSUE TITLE
watch closed before UntilWithoutRetry timeout failures

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#76001]
**What happened**: failures like:
```
test/e2e/framework/framework.go:149
Unexpected error:
    <*errors.errorString | 0xc000308d80>: {
        s: "watch closed before UntilWithoutRetry timeout",
    }
    watch closed before UntilWithoutRetry timeout
occurred
test/e2e/framework/framework.go:220
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance/1112855802516869120

https://testgrid.k8s.io/conformance-kind#kind,%20master%20(dev)

**What you expected to happen**: not this! it looks like a race / flake

**How to reproduce it (as minimally and precisely as possible)**: run the e2e tests

**Anything else we need to know?**: https://github.com/kubernetes/kubernetes/pull/75835 seems suspect

/cc @liggitt 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by BenTheElder** [comment]
/sig api-machinery
(I think?)

**Comment by liggitt** [comment]
https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance is still red after revert

**Comment by liggitt** [comment]
though the "watch closed" test failures are gone now

**Comment by liggitt** [comment]
now the errors are encode panics in daemonset e2e tests:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance/1113046932642598917

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/75616 seems related

**Comment by liggitt** [comment]
fix is in https://github.com/kubernetes/kubernetes/pull/76025

**Comment by liggitt** [comment]
closing this issue as the "watch closed" issue is resolved

/close
