### ISSUE TITLE
Start running Probes in scalability tests

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#76012]
Probes are supposed to be simple jobs running inside kubernetes cluster measuring SLIs that could not be measured through other means.

An example of a SLI that could be measured via Probe is the [In Cluster Network Latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/network_latency.md) SLI.

**Comment by mm4tt** [comment]
/assign @oxddr 

@oxddr will be taking over this effort.

**Comment by oxddr** [comment]
This was done by https://github.com/kubernetes/perf-tests/issues/612 (only cleanup left) and https://github.com/kubernetes/perf-tests/issues/597.

/close
