### ISSUE TITLE
[Feature] kubectl top pods /nodes - add network traffic

### ISSUE THREAD

**Issue by mmack** [kubernetes/kubernetes#76011]
**What would you like to be added**:
It would be outstanding to see the network traffic for pods / nodes when doing a `kubectl top pods` or `kubectl top nodes`.

```
~ kubectl top pods                     
NAME                                        CPU(cores)   MEMORY(bytes)   Network In(per sec)   Network Out(per sec)
alertmanager-infra-alertmanager-0           2m           31Mi            560Kb                 10Kb
alertmanager-infra-alertmanager-1           2m           30Mi            1.2Mb                 550Kb
default-http-backend-6fd4978fb-62rn6        1m           13Mi            80Kb                  60Kb
grafana-5f9d5d8d56-nq5rw                    6m           302Mi           15.1Mb                10.8Kb
```

Something like
**Why is this needed**:
Better visibility of what's going on in your cluster.

@kubernetes/sig-cli-feature-requests

**Comment by mmack** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
is that a standard metric available from the metrics server?

cc @kubernetes/sig-instrumentation-feature-requests

**Comment by brancz** [comment]
> is that a standard metric available from the metrics server?

It is not. I believe there is a similar request for disk I/O metrics I believe.
