### ISSUE TITLE
kubectl wait  add ability to show tail logs while waiting to a pod

### ISSUE THREAD

**Issue by dorsany** [kubernetes/kubernetes#76024]
**What would you like to be added**:
add the ability to show tail logs while waiting to a pod
 
something like:
```
kubectl wait --for=condition=Ready --selector=app=mongodb --timeout=300s pods --logs
```

**Why is this needed**:
Today instead of develop 3 commands:
loop:
1) get pod status
2) get logs of the pod
3) if complete or failed exit loop otherwise wait

I'm using the ```kubectl wait``` that solved for me section **1** and **2**

please add the ability ```--logs```

**Comment by gokultp** [comment]
@dorsany  do you mean verbose, if so -vv will be more idiomatic.

**Comment by sftim** [comment]
I think this'd be better served by a plugin, and not by core kubectl functionality.

**Comment by rayjlinden** [comment]
Really, why?  Seems a rather basic desire....  Why have it in a plug in?
