### ISSUE TITLE
Block PV may be mounted if kubelet feature gate disabled

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#76044]
@msau42 you may remember you had a concern that if we made BlockVolume default in 1.13 there could be issues with version skewed clusters where kubelets with the feature gate still off could format block volumes if a pod was started/restarted, potentially deleting data that was there. (see https://github.com/kubernetes/kubernetes/pull/65829#issuecomment-432378975). I concluded it wasn't possible but I'm convinced now that's wrong.

It's true that kubelet won't mount `volumeDevices` volumes into the pod, which is what the downgrade test I added checked, but the issue is:
- If the feature gate is off kubelet will add everything in spec.volumes to desired state of world* regardless of whether it is in volumeDevices/volumeMounts/neither. This means it will call MountVolume on a block volume! https://github.com/kubernetes/kubernetes/blob/b1829dff0b2d001ef3c70dffc844ad4cc852b1c1/pkg/volume/util/operationexecutor/operation_executor.go#L726

Only if the feature gate is on will kubelet check spec.volumes against volumeMounts/volumeDevices. It will add every volume in spec.volumes desired state of world* unless either a) it is a BlockVolume and present in volumeMounts or b) it is a Filesystem volume and present in volumeDevices, i.e. there is a mismatch. So it will still mount/map things even if there is no respective volumeMount/volumeDevice but it will error if there is a mismatch.

TODO:
- Update the downgrade test to not only check that nothing is mounted in the pod but also that nothing is mounted to the node at all, i.e. to the pod volume directory under /var/lib/kubelet (how to do that is TBD)

- Whether the feature gate is on/off, don't add volumes desired state of world* that are not in any volumeDevices/volumeMounts at all. So if the feature gate is off, kubelet won't add any block volumes in volume.spec because it won't check volumeDevices and the block volume won't be present in volumeMounts. This is what I thought happened. It should happen anyway because what's the point of mounting a volume if it is not going to be consumed by the pod?

~- Add a safeguard to MountVolume even if feature gate is off. I've heard feature gate off is supposed to mean 'don't run any code related to the feature' but I think an exception to read the VolumeMode field would be okay here?~ not reliable, pod may not have field at all

The fix should be cherry-picked to 1.11 & 1.12

**Comment by wongma7** [comment]
are there any tests run against version skewed clusters?

**Comment by wongma7** [comment]
An additional option to not adding volumes that aren't in volumeMounts/volumeDevices to desired state of world is to fail starting the pod if volumeDevices is non-empty and the feature gate is disabled. I decided not to do that in the original PR though, the downgrade tests assumes the pod can still run with the volume at volumeDevices MIA, the assumption being that the application can fail its own way. Plus this check would require a kubelet w/ feature gate off to check a feature gate on API which again raises the question if we should be doing that.

**Comment by msau42** [comment]
There are upgrade tests that only upgrade the master and not the nodes.

Not adding volumes that aren't in volumeMounts/Devices sounds good to me.  I'm not sure if we could actually fail starting the pod because when we read the Pod object from the apiserver, I believe it should nil the values.

**Comment by msau42** [comment]
Hm but I don't see 1.12 upgrade tests in the sig-release dashboard

**Comment by wongma7** [comment]
OK I see, not adding volumes to desired state of world will be enough. It will be more difficult to reason about if the field is empty in which cases etc., better to not rely on that.

I don't think the existing downgrade test is running so as part of this issue I'm going to have to figure that out. Here is the 1.13->1.12 test where I would like my test to run but it doesn't show up. https://testgrid.k8s.io/sig-cluster-lifecycle-upgrade-skew#gce-1.13-1.12-downgrade-cluster. Here is the 1.12->1.13 test where it is skipped https://testgrid.k8s.io/sig-cluster-lifecycle-upgrade-skew#gce-1.12-1.13-upgrade-cluster. :/

I found this issue in openshift ci where master is 1.13 but kubelet 1.12 and logs showed a volume was mounted even though it cannot have been present in volumeMounts.  https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/6398#openshift-tests-sig-storage-in-tree-volumes-driver-aws-testpattern-dynamic-pv-block-volmode-volumemode-should-create-sc-pod-pv-and-pvc-readwrite-to-the-pv-and-delete-all-created-resources-suiteopenshiftconformanceparallel-suitek8s. It's not 100% proof that this issue is happening but we can infer well enough. Anyway I'll confirm as I work on this.

**Comment by wongma7** [comment]
There's a few other places outside kubelet mount/unmount that can assume spec.Volumes means the pod actually uses the volume. They can do it safely so I'm going to ignore them. e.g.

attach detach will attach all volumes in spec.volumes
scheduler uses spec.volumes to ensure pods using the same gce pd etc. are on the same node.
