### ISSUE TITLE
Kubelet: Refactor/improve runtime-Kubelet dependency

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#7606]
While getting the Runtime abstraction we've cut some corners and are left with a bit of a mess when it comes to the dependencies of the runtime in the kubelet. We should set aside some time to smooth out the dependency graph for this.

/cc @yujuhong @dchen1107 @yifan-gu

**Comment by gmarek** [comment]
@vmarmol @yifan-gu - can you give any update on this?

**Comment by yujuhong** [comment]
@gmarek, as far as I know @yifan-gu has been working on finishing the rkt package, while I have been working on kubelet's performance issues.  (FYI, @vmarmol went back to the borglet team)

If you have any specific issue about dependencies, feel free to post it here so that we can help.

**Comment by gmarek** [comment]
IIRC there was supposed to be some description of what refactoring @yifan-gu is planning.

**Comment by yujuhong** [comment]
I'm going to close this issue. The dependency between kubelet packages remains a problem, but a 4-digit issue really doesn't help.
