### ISSUE TITLE
Kubelet: Document container Runtime abstraction

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#7607]
Document the container runtime abstraction and expectation for future implementers of the interface.

/cc @yujuhong @yifan-gu @dchen1107

**Comment by yujuhong** [comment]
The abstraction may go through some more cleanup soon. We probably won't document it until the cleanup is mostly done.

**Comment by yujuhong** [comment]
This is obsolete. We switched to CRI (which also needs more documentation), but the abstraction in this issue is unlikely be used for any new integration.
