### ISSUE TITLE
restructure LICENSES file generation

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#76093]
This is a follow-up to https://github.com/kubernetes/kubernetes/pull/74877

Prior to https://github.com/kubernetes/kubernetes/pull/74877, Godeps/LICENSES included a copy of a dependency's LICENSE file for every package of the dependency we referenced.

https://github.com/kubernetes/kubernetes/pull/74877 switched to aggregating licenses at the module level. This is better in most ways, but means we don't have a fast way to check the licence for a particular vendored package (we have to manually drop the last path segment until we find the module root and the associated LICENSE file).

Some options:
* `vendor/modules.txt` lists the packages included from each module we depend on; we could munge that into the aggregated LICENSES file, so we have a package listing along with each included license
* thoughts from @thockin: "What I want to have is a directory tree of copies of licenses, with nmetadata about fingerprint (this pattern-matches as apache2) and per-pkg xrefs, so for any pkg I can trivially see what the license text is and what the category is, and diffs are useful"

/sig release
/cc @cblecker 
fyi @thockin

**Comment by JishanXing** [comment]
@liggitt 

Hi liggitt,

I did a PR for this issue, here are my proposal

This fix will generate the LICENSE file for each package under vender/ and put them to Godeps/ALL_LICENSES/ (In #76092, seems need move this dir to vender/ALL_LICENSES? I will move this folder to vendor in this ticket after your 1st round review)

The LICENSE file name format is "bitbucket.org:bertimus9:systemstat", use colon to separate the package:subpackage.

So the output for Godeps/ALL_LICENSES is below:
src/k8s.io/kubernetes/Godeps/ALL_LICENSES]> ls
bitbucket.org:bertimus9:systemstat github.com:marstr:guid
cloud.google.com:go github.com:mattn:go-shellwords
github.com:armon:circbuf github.com:mattn:go-sqlite3
github.com:asaskevich:govalidator github.com:matttproud:golang_protobuf_extensions
github.com:aws:aws-sdk-go github.com:mesos:mesos-go
github.com:Azure:azure-sdk-for-go github.com:mholt:caddy
......

Regards,
Jishan

**Comment by liggitt** [comment]
I'll defer to @cblecker / @thockin on the proposal
