### ISSUE TITLE
`make verify WHAT=bogus` succeeds

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#76094]
Found while working on https://github.com/kubernetes/kubernetes/pull/74877

As part of switching from godep to go modules, I renamed the verify-godeps.sh script to verify-vendor.sh

CI was green, so I assumed all was well, until I realized that CI was [actually calling](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/godeps.yaml#L18-L31) `make verify WHAT=godeps`, and `make verify` passes if the WHAT target cannot be located.

`make verify` should fail if an unknown target is specified, or jobs that think they are testing things could have typos or be testing nonexistent verify scripts.

/sig testing

**Comment by liggitt** [comment]
cc @kubernetes/sig-testing

**Comment by BenTheElder** [comment]
Took a quick look, this looks moderately painful to do without restructuring the whole script...

**Comment by YoubingLi** [comment]
I will work on it.

Both expected list and verified list are known in this case.
The code logic should be added to check the difference between expected and verified list.

**Comment by YoubingLi** [comment]
#76253

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/76253

/close
