### ISSUE TITLE
Cannot list the logs in one of the API pods

### ISSUE THREAD

**Issue by Ashraf-Hassan** [kubernetes/kubernetes#76147]
**What happened**: 
When I run:
# kubectl logs kube-apiserver-master01
I am getting:
failed to open log file "/var/log/pods/6db22ad086cc13a18bf0bd00eeaf6e05/kube-apiserver/0.log": open /var/log/pods/6db22ad086cc13a18bf0bd00eeaf6e05/kube-apiserver/0.log: no such file or directory

**What you expected to happen**:
To list the logs

**How to reproduce it (as minimally and precisely as possible)**:
I have 3 master on CentOS 7 VM behind HA Proxy.
I am able to display the logs for the of the APIs pods from the other 2 masters.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
1- The Cluster consists or VMs (3 masters, 2 infra, and 4 workers) on KVM.
2- The VMs are CentOS 7 based

- OS (e.g: `cat /etc/os-release`):

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

Linux master01 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

Kubeadm

- Others:
@kubernetes/sig-api-machinery

**Comment by Coderhypo** [comment]
the  logs in /var/log/pods is a soft link from /var/lib/docker/containers
can you run `ls -al` ，get the path in /var/lib/docker/containers，and check the log file?

**Comment by Ashraf-Hassan** [comment]
I cannot find any directory there with the name of :  6db22ad086cc13a18bf0bd00eeaf6e05
What should I do?
# ls -al /var/lib/docker/containers/
total 100
drwx------. 25 root root 4096 Apr  4 17:07 .
drwx--x--x. 15 root root 4096 Mar 12 13:26 ..
drwx------.  4 root root 4096 Mar 22 20:28 1dbefe80f7880285a02e28e9f1c8703bb65c8e8cc2c7742e442c4169ee50bd52
drwx------.  4 root root 4096 Mar 12 13:58 2d6e884a65127fefccb0f9d5839cd3f8195c39a850f88deb0c46ce5f5685aeaa
drwx------.  4 root root 4096 Mar 27 15:26 452b2426529ffd7e42188671ae325d7685fcd47131c11a219bdf2adf6f13e7f1
drwx------.  4 root root 4096 Mar 12 16:55 4b370aab7f063181756a8435ca90659b30bed60682d6820159a3d42ba1877732
drwx------.  4 root root 4096 Mar 12 13:57 71074df1f2366d877b0db6da4823075a5e8db42be9b4e27550a4fa60ca423e56
drwx------.  4 root root 4096 Mar 15 14:29 75dc3e816f8c89af97ab85f32c25d01574e28c373e06385cecc68218f556df03
drwx------.  4 root root 4096 Mar 12 13:51 85a27deacc29aeba7f2cd0f9277df8e08bc61e9a4e6d0a496b67e846d850b962
drwx------.  4 root root 4096 Mar 12 13:58 8c6681c66692e1fb1a46e29573a3ebecee6fda85e9d4b365855263f5352b0603
drwx------.  4 root root 4096 Mar 27 16:25 90a3e2fb609c79271e57ee1fada078a5639dc7afb07bdc30733ff10b59ac4fe3
drwx------.  4 root root 4096 Mar 12 13:58 aceb2a669dcc5df4ddc2199c25c4e2c9d0ab8c0f7918174f679c468b41c087e8
drwx------.  4 root root 4096 Mar 12 17:00 ae22c54346102bcd35d564789ae40ee4ee0eb62155507aba09e18a3aa4057c78
drwx------.  4 root root 4096 Mar 15 14:29 b3d0092a90807ebdabe9986f4de0bfca217adfe8ebb55586ba2e65344fb60c22
drwx------.  4 root root 4096 Mar 12 13:58 c342bc82ab5df5f089f2f5d2ac02c51217dbc3e68cab085b3ff91cbf1886e0c1
drwx------.  4 root root 4096 Mar 27 15:26 c52284048e2994f46d554a3ba1af32f94e0ffa9573e0c08409b0b72e3aba082f
drwx------.  4 root root 4096 Mar 12 13:57 c6089ec48573490daa405dae5a7366b20ad8effbbbc69ec727d6b03cf056506d
drwx------.  4 root root 4096 Mar 27 16:25 c87dafbb3789ad3ee4f923de2a9109bbe70202ad84c9fa0ea30aa71a890a93b2
drwx------.  4 root root 4096 Mar 12 13:51 cec3f31cdf6b7efdd81d9c80d30973ffc5cacbcba41964d1a6b8be9b4fbf21e2
drwx------.  4 root root 4096 Mar 12 16:55 d06f32cd00e324293a889868a9ed1fc142f7bba97a7bde3d279cdd9375af3021
drwx------.  4 root root 4096 Mar 12 13:50 d81b9331d06f77dc1dede528a840315426878506f805043e47e0c2b41d4f684e
drwx------.  4 root root 4096 Mar 12 13:50 e4dcff950b4c868c93e6be1ab11bef3c7f95e3dea28ad4ba5daa73dce81e343c
drwx------.  4 root root 4096 Mar 12 17:00 ed203bfdc6b9fe45077a23258a456f3801151735605f6e72ab4d27da9d414d07
drwx------.  4 root root 4096 Mar 22 20:28 f088625f45df64f61dda7d821647cce19b0190637c4fb80eb19fb53300eee21a
drwx------.  4 root root 4096 Mar 12 13:58 f9c857e546f27fc97913ea973effac6642513f164087d38cfcd8e95955ae8f34

**Comment by Coderhypo** [comment]
can you run `ls -al /var/log/pods`, and find 6db22ad086cc13a18bf0bd00eeaf6e05?
I guess this linked a container log file that deleted by docker, but need to verify
