### ISSUE TITLE
World Writable emptydir directories

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#76158]
So this PR - https://github.com/kubernetes/kubernetes/pull/9384 added `777` as default mode for EmptyDirs so as it can be used by non-root containers, but this was before `fsGroup` and other things. 

Is this still relevant? I was thinking it might be okay to move this to `770` but recently added `RunAsGroup` feature for containers may not play nicely with it if user has specified different GID for each container - https://github.com/kubernetes/community/pull/756 . Can we recommend users who use different GID for each container to specify a `fsGroup` rather than relying on configmap/emptydir to have 777 permission?

The problem with having world-writable directories laying around in local file-system is bunch of auditing tools already flag this up and make k8s unsuitable for such deployments.

**Comment by gnufied** [comment]
/sig storage

cc @thockin @msau42 @pmorie

**Comment by msau42** [comment]
@kubernetes/sig-auth-misc

**Comment by tallclair** [comment]
What is the motivation for this NOT being `777`? The parent directory should be restricted to root, so I'm not sure how an uncontained process would access this. For security sensitive applications, they can still write files as `600` or whatever they need.

I'm not sure that restricting access to this actually increases security much, but it does hurt useability...

**Comment by gnufied** [comment]
I think current motivation is - world writable directories are simply being flagged by linux security scanners (https://secscan.acron.pl/centos7/1/1/21). I agree that, parent directories are still restricted to root and hence a uncontained user can not access the world-writable directory.

**Comment by thockin** [comment]
Changing to require fsGroup would be a breaking change.  It would need a lengthy transition period

**Comment by abemarji** [comment]
Any chance to change the Permissions to enable Linux Sticky bit on the Directory ?   So chmod +1777 instead of 777?  enabling the sticky bit would address of of the concerns raised by the various linux security scanners.
