### ISSUE TITLE
Drop reverse proxy workaround once upgraded to go1.12.2

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#76154]
The workaround in https://github.com/kubernetes/kubernetes/pull/75887 should be removed (but the test kept to prevent regressions) once we upgrade to go 1.12.2 and pick up https://github.com/golang/go/commit/ec06e9ba4578d26fdb9c521d4042e3f9f7f42435

/assign

**Comment by cheftako** [comment]
Thanks Liggitt

**Comment by liggitt** [comment]
removed in https://github.com/kubernetes/kubernetes/pull/77222
