### ISSUE TITLE
bootstrap kubernetes from private registry

### ISSUE THREAD

**Issue by sshuvaev** [kubernetes/kubernetes#76155]
**What happened**:
Can't pull images from private registry

**What you expected to happen**:
Kubernetes pull images from private registry

**How to reproduce it (as minimally and precisely as possible)**:
1. kubeadm config images pull 
2. upload images to private registry
3. bootstrap kubernetes from private registry
4. init calico
5. join node
6. kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
    --type=kubernetes.io/dockerconfigjson
pulling image "registry/images/pause:3.1": Error response from daemon: Get https://registry/v2/images/pause/manifests/3.1: denied: access forbidden

**Anything else we need to know?**:
gitlab registry
docker pull = ok
imagepullsecrets not work when added to sa (kube-proxy for example)
trying kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> - nothing change
imagepullsecrets not work when added to daemonset

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
- Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm init --config

**Comment by neolit123** [comment]
/remove-kind bug
/triage support
/sig cluster-lifecycle
/sig cli

for kubeadm you need to use:
`imageRepository: ...."
under ClusterConfiguration:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

the kubelet needs a flag:
`--pod-infra-container-image ....`
from kubeadm it can be set using this:

```
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
```
https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

i cannot comment much about:
```
pulling image "registry/images/pause:3.1": Error response from daemon: Get https://registry/v2/images/pause/manifests/3.1: denied: access forbidden
```
you need to check if kubectl has the correct rights.

for the record, we do have successful stories of users using private registries.

**Comment by brentpearson** [comment]
> for kubeadm you need to use:
> `imageRepository: ...."
> under ClusterConfiguration:
> https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1
> 
> the kubelet needs a flag:
> `--pod-infra-container-image ....`
> from kubeadm it can be set using this:
> ```
> # KUBELET_EXTRA_ARGS should be sourced from this file.
> EnvironmentFile=-/etc/default/kubelet
> ```

Can you elaborate on these? Specific instructions for how to do this would be awesome. 

Is there a simple flag to add with the "kubeadm init" command that sets the imageRepository setting? I haven't read everything in that link closely, but it looks to be all about using one or more config files, in which case I'm worried that if I have to come up with all those config file contents, I'm going to be changing some setting from the default or whatever I'm using now, just to change the imageRepository setting.

So the kubelet needs a "--pod-infra-container-image" flag, and you say it can be set in what I assume is /etc/systemd/system/kubelet.service.d/10-kubeadm.conf. But then I just see EnvironmentFile=-/etc/default/kubelet. So are you trying to say that we need to add --pod-infra-container-image to /etc/default/kubelet? Couldn't it just be added by changing
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
to 
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --pod-infra-container-image" 
?

**Comment by neolit123** [comment]
> Can you elaborate on these? Specific instructions for how to do this would be awesome.

try the `--image-repository=<your-registry>` flag with `kubeadm init` and let me know if it works for you.
i forgot that we have this in 1.14.

with regards to `--pod-infra-container-image`, after using the above flag with `kubeadm init/join` have a look at `/var/lib/kubelet/kubeadm-flags.env` to verify the value for `--pod-infra-container-image` is good.

in case the above does not work for the pod-infra-container:

the file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` is a unit file and as per the systemd specs it should not be touched, but you still can do so.

instead, the proper way is to add the flag in `/etc/default/kubelet` like so:
```
# /etc/default/kubelet
KUBELET_EXTRA_ARGS=--pod-infra-container-image=<your-registry>/pause:3.1
```

**Comment by sshuvaev** [comment]
@neolit123 
This is does not fix my issue.
kube-proxy can't start before calico-node.
Calico-node in pending status becouse of can not pull image
Node status also notready becouse of cni not ready.
In my serviceaccount and daemonset I point calico to my private registry. 
Kubelet throw:
Apr 15 15:15:35 k8s-n2-test.test kubelet[13267]: I0415 15:15:35.359271   13267 docker_service.go:253] Docker cri networking managed by cni
Apr 15 15:15:35 k8s-n2-test.test kubelet[13267]: W0415 15:15:35.359331   13267 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d

kubectl get **ds calico-node** -n kube-system -o yaml:
        imagePullSecrets:
        - name: private-registry
    12d

kubectl get **sa calico-node** -n kube-system -o yaml
apiVersion: v1
imagePullSecrets:
- name: private-registry

First node with manual pulled images of calico-cni and calico-node started.

**Comment by neolit123** [comment]
i did not talk about CNI plugins in my post above.
you might have to modify the CNI plugin manifests to point to your private registry.
...or just prepull the CNI images.

**Comment by sshuvaev** [comment]
I'm did so on first node and all worked fine.
So, there is no way to pull cni image on a new node?

**Comment by neolit123** [comment]
> you might have to modify the CNI plugin manifests to point to your private registry.

also the worker nodes need to have access to the registry.

**Comment by sshuvaev** [comment]
My nodes have access to registry:
[k8s-n2-test /]# docker login private.registry
Authenticating with existing credentials...
Login Succeeded
Kubelet runnin as follow:
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=private.registry/devops/images/pause:3.1

kubectl describe po calico-node-hq4nd -n kube-system:
Warning  FailedCreatePodSandBox  103s (x184 over 41m)  kubelet, k8s-n2-test Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "private.registry/devops/images/pause:3.1": Error response from daemon: Get https://private.registry/v2/devops/images/pause/manifests/3.1: denied: access forbidden

kubectl describe po kube-proxy-2hnh5 -n kube-system:
 Warning  FailedCreatePodSandBox  3m46s (x186 over 43m)  kubelet, k8s-n2-test Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "private.registry/devops/images/pause:3.1": Error response from daemon: Get https://private.registry/v2/devops/images/pause/manifests/3.1: denied: access forbidden

my conclusing: imagepullsecrets does not working on new kubernetes node

**Comment by cdivitotawela** [comment]
> My nodes have access to registry:
> [k8s-n2-test /]# docker login private.registry
> Authenticating with existing credentials...
> Login Succeeded
> Kubelet runnin as follow:
> /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=private.registry/devops/images/pause:3.1
> 
> kubectl describe po calico-node-hq4nd -n kube-system:
> Warning FailedCreatePodSandBox 103s (x184 over 41m) kubelet, k8s-n2-test Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "private.registry/devops/images/pause:3.1": Error response from daemon: Get https://private.registry/v2/devops/images/pause/manifests/3.1: denied: access forbidden
> 
> kubectl describe po kube-proxy-2hnh5 -n kube-system:
> Warning FailedCreatePodSandBox 3m46s (x186 over 43m) kubelet, k8s-n2-test Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "private.registry/devops/images/pause:3.1": Error response from daemon: Get https://private.registry/v2/devops/images/pause/manifests/3.1: denied: access forbidden
> 
> my conclusing: **imagepullsecrets does not working on new kubernetes node**
> 
> P.S.: can't wait too long for assistance. make a manual pull:
> docker pull private.registry/devops/images/pause:3.1
> 3.1: Pulling from devops/images/pause
> 7675586df687: Pull complete
> 
> wait a minute and got result from kubectl get po -n kube-system:
> calico-node-hq4nd 1/1 Running
> kube-proxy-2hnh5 1/1 Running
> 
> P.P.S: run a few pods with the same imagepullsecrets and as a result node can pull image from registry:
> kubectl get po -n msdp -o wide
> originator 1/1 Running 0 22s k8s-n2-test
> processing 1/1 Running 0 15s k8s-n1-test

I have the same issue. @sshuvaev did you find a solution. 
When we run docker login it create credentials for the user and store at ~/.docker/config.json and this is not applicable when kubelet pull images. I have noticed permission denied error docker logs as well. 

I believe there should be a way to pass the docker registry auth details in kubelet so that those can be passed to docker.

**Comment by dims** [comment]
@cdivitotawela Chaminda, is this problem ONLY for the pause image? (do the other images load ok?)

**Comment by neolit123** [comment]
it is already possible to configure the kubelet with the docker auth.
see here https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

but make sure you have the credentials before the kubelet started (or simply restart the kubelet):
https://github.com/kubernetes/kubernetes/issues/69637
