### ISSUE TITLE
[sig-storage] Slow running tests in the test suite 

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#76170]
@Katharine created a spread sheet of the slowest running tests for the pull-kubernetes-gce job.
cc @liggitt 

discussion on slack:
https://kubernetes.slack.com/archives/C09QZ4DQB/p1554413286170600

spreadsheet:
https://docs.google.com/spreadsheets/d/1XXXBQtqARIfgY9HaAJvf0dJ83kydq14mQijAsH9tWYQ/edit?usp=sharing

pie chart of test durations from SIGs:
![pull-kubernetes-e2e-gce-test-durations](https://user-images.githubusercontent.com/331852/55592649-bd2f5f80-5741-11e9-859c-86a29ad2b1b6.png)

it seems appropriate to evaluate the state of the tests and reduce these runtimes.
possibly move tests to periodic by marking them as [Slow].

@kubernetes/sig-storage-bugs 
/assign @saad-ali @childsb 
/kind design
/area test
(?)

**Comment by msau42** [comment]
Are pull jobs the right place to be calculating the time?  Or should be be counting in CI instead?

**Comment by liggitt** [comment]
pull is the one timing out, so probably?

**Comment by msau42** [comment]
Looking at some of the top slowness::

subPath should fail for new directories when readOnly specified in the volumeSource: This test case is no longer defined in master
HostPathType: This test case has not been checked in yet and is trying to be added in a PR
PersistentVolumes-local  StatefulSet with pod affinity should use volumes spread across nodes when pod has anti-affinity: This test is already marked as slow in master

**Comment by msau42** [comment]
Created https://github.com/kubernetes/kubernetes/pull/76174. This should address most of the top slow storage tests
