### ISSUE TITLE
Remove FIFO scheduling queue from the scheduler codebase

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#76172]
After the introduction of Pod Priority and Preemption, we added a new scheduling queue which is Priority aware and has various features to provide fairness and to ensure that a high priority unschedulable pod does not block the head of the queue. This new queue has been enabled by default since Kubernetes 1.11 and is tested extensively in production and non-production scenarios. Given the maturity of the new queue, we can now remove [the old FIFO scheduling queue](https://github.com/kubernetes/kubernetes/blob/1c105e1629c7ab88623c97f1186609cbf27768f9/pkg/scheduler/internal/queue/scheduling_queue.go#L103) and [the old pod backoff mechanism](https://github.com/kubernetes/kubernetes/blob/1c105e1629c7ab88623c97f1186609cbf27768f9/pkg/scheduler/factory/factory.go#L681) from the scheduler code base.

/kind cleanup
/sig scheduling

**Comment by xiuqiaoli** [comment]
@bsalamat  Bobby, I can work on this task as a start point.

**Comment by bsalamat** [comment]
@xiuqiaoli Sure. I cannot assign to you officially since you are not a member yet, but it is assigned you.

**Comment by shinytang6** [comment]
hey @xiuqiaoli, can l ask what's the status of this? Can I try it?

**Comment by xiuqiaoli** [comment]
@shinytang6 Hi, I am working on it and will create PR later today.

**Comment by shinytang6** [comment]
@xiuqiaoli okay fine!
