### ISSUE TITLE
nslookup kubernetes fails from ambassador pod

### ISSUE THREAD

**Issue by sonyjop** [kubernetes/kubernetes#76186]

**Comment by sonyjop** [comment]
Kubernetes 1.14.0 and CNI is flannel with kubedns.
When I configured ambassador and the routers were not working. it always shown "no healthy upstream". Further analysis indicates that there is no access from ambassador pod to DNS 10.96.0.10 and nslookup kubernetes just fails. I tried nc 10.96.0.10 53 from the busybox pod and that too failed.

**Comment by vsxen** [comment]
check kube-proxy log & iptables rules in the node.
