### ISSUE TITLE
Cloud-controller-manager won't build for out-of-tree external providers

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#76205]
**What happened**:

panic: failed to find flag in global flagset (flag): cloud-provider-gce-lb-src-cidrs

goroutine 1 [running]:
k8s.io/component-base/cli/globalflag.Register(0xc0000ba900, 0x17df195, 0x1f)
	/home/neil/Go/pkg/mod/k8s.io/component-base@v0.0.0-20190405092941-79a63e28c077/cli/globalflag/globalflags.go:66 +0x1a9
k8s.io/kubernetes/cmd/cloud-controller-manager/app.NewCloudControllerManagerCommand(0xc00008e150)
	/home/neil/Go/pkg/mod/k8s.io/kubernetes@v1.14.0/cmd/cloud-controller-manager/app/controllermanager.go:91 +0x438
main.main()
	/home/neil/Dev/brightbox-cloud-controller-manager/main.go:39 +0x90

**What you expected to happen**:

The controller should run and stop with a '--cloud-provider cannot be empty' message

**How to reproduce it (as minimally and precisely as possible)**:

Follow the out of tree instructions here https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/

Comment out the _ "k8s.io/kubernetes/pkg/cloudprovider/providers" import line and build the cloud-controller-manager

**Anything else we need to know?**:

This worked fine prior to 1.14.0 

**Environment**:
- Kubernetes version (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`):
Linux bionic-vm 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linu
- Install tools:
kubeadm
- Others:

**Comment by magicsong** [comment]
any updates?

**Comment by timoreimann** [comment]
@andrewsykim we chatted about this the other day on Slack.

**Comment by timoreimann** [comment]
The GCE flag seems to be registered [here](https://github.com/kubernetes/kubernetes/blob/v1.14.1/cmd/cloud-controller-manager/app/controllermanager.go#L91), with the panic eventually occurring [here](https://github.com/kubernetes/component-base/blob/kubernetes-1.14.1/cli/globalflag/globalflags.go#L66).

**Comment by timoreimann** [comment]
Given some pointers on how to resolve the issue best, I'm happy to take a stab at a PR.

**Comment by timoreimann** [comment]
A workaround for external cloud providers seems to be to add a bogus version of the parameter before the call to [app.NewCloudControllerManagerCommand()](https://github.com/kubernetes/kubernetes/blob/v1.14.1/cmd/cloud-controller-manager/controller-manager.go#L41), like this:

```go
flag.CommandLine.String("cloud-provider-gce-lb-src-cidrs", "", "NOT USED (workaround for https://github.com/kubernetes/kubernetes/issues/76205)")
```

**Comment by dims** [comment]
@timoreimann would it be better to do something like this in master? (and get it back ported to 1.14 branch?)

```
diff --git a/cmd/cloud-controller-manager/app/controllermanager.go b/cmd/cloud-controller-manager/app/controllermanager.go
index 26710bbb928f..77e56c13e25b 100644
--- a/cmd/cloud-controller-manager/app/controllermanager.go
+++ b/cmd/cloud-controller-manager/app/controllermanager.go
@@ -18,6 +18,7 @@ package app
 
 import (
 	"context"
+	"flag"
 	"fmt"
 	"net/http"
 	"os"
@@ -86,9 +87,11 @@ the cloud specific control loops shipped with Kubernetes.`,
 	namedFlagSets := s.Flags(KnownControllers(), ControllersDisabledByDefault.List())
 	verflag.AddFlags(namedFlagSets.FlagSet("global"))
 	globalflag.AddGlobalFlags(namedFlagSets.FlagSet("global"), cmd.Name())
-	// hoist this flag from the global flagset to preserve the commandline until
-	// the gce cloudprovider is removed.
-	globalflag.Register(namedFlagSets.FlagSet("generic"), "cloud-provider-gce-lb-src-cidrs")
+	if f := flag.CommandLine.Lookup("cloud-provider-gce-lb-src-cidrs"); f != nil {
+		// hoist this flag from the global flagset to preserve the commandline until
+		// the gce cloudprovider is removed.
+		globalflag.Register(namedFlagSets.FlagSet("generic"), "cloud-provider-gce-lb-src-cidrs")
+	}
 	for _, f := range namedFlagSets.FlagSets {
 		fs.AddFlagSet(f)
 	}

```

**Comment by timoreimann** [comment]
@dims I think that should work, yeah. What I am wondering though is whether this is the way we want to go with long-term. It feels odd to me to have a specific GCE-only parameter be part of the generic bootstrapping process which we then need to handle in a special way.

If it's about getting a fix out ASAP (and think about a possibly better design later), I'm all on-board with your patch. :+1:

**Comment by dims** [comment]
@timoreimann the right thing to do is to get the sig-gcp folks to refactor that flag properly (and/or) remove the gce provider entirely (as a out of tree provider over time).

**Comment by dims** [comment]
@timoreimann let's stop the bleeding where external providers have to make unnecessary changes like you mentioned (fake flag). can you please file a PR with the patch i proposed?

**Comment by timoreimann** [comment]
@dims will do, thanks!

**Comment by andrewsykim** [comment]
Thanks for reporting this issue @NeilW and thanks for following-up @timoreimann! 

Agreed with everything @dims said. I can't recall why that flag was added in there in the first place, I think it was required to get the reference CCM implementation working with GCE. Apologies that it broke other implementations. The proposed changes makes sense to me as well. We have some work coming up (likely in the next release cycle) to make `cmd/cloud-controller-manager` more easily consumable as an external library which may involve moving `cloud-controller-manager` into it's own repo. Let me know if anyone is interested in picking this up!

**Comment by timoreimann** [comment]
Submitted a fix at https://github.com/kubernetes/kubernetes/pull/76627.

**Comment by timoreimann** [comment]
@andrewsykim in general, I'd be interested in helping on the move of `cloud-controller-manager`. However, I likely won't have many cycles available until post-KubeCon EU. If the effort is low-priority and/or can wait until end of May / June though, I'd be happy to help.

**Comment by andrewsykim** [comment]
@timoreimann I don't think we'll get to this until the v1.16 release cycle so I will loop you in then :)

**Comment by timoreimann** [comment]
@andrewsykim oh please do then, that's a convenient timeline for me. 🙂

**Comment by andrewsykim** [comment]
Sounds great @timoreimann! Here's the backlog tracking issue https://github.com/kubernetes/cloud-provider/issues/29
