### ISSUE TITLE
[sig-auth] question about IsRBACEnabled in the e2e testing framework

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#76207]
in the e2e testing framework we have an auth utility function IsRBACEnabled:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/authorizer_util.go#L137

in the testing commons meeting today @timothysc proposed that we might want to refactor this utility.

**a question** related to this code and the e2e testing framework is - should we fail immediately when the framework starts and the cluster has no RBAC, instead of having this utility called in many locations?

/sig auth
/sig testing
/kind design
/area e2e-test-framework

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubernetes/issues/76207

**Comment by liggitt** [comment]
some places use it to conditionally run tests that depend on being able to dynamically modify authorization rules

> should we fail immediately when the framework starts and the cluster has no RBAC

no, RBAC is not a required feature

**Comment by timothysc** [comment]
Thx @liggitt ! 

k, then we should just refactor what is there per our conversation this morning.

**Comment by neolit123** [comment]
ok, i will close this Q ticket as we have another for tracking the util rework.
