### ISSUE TITLE
[sig-apimachinery] removal of an aggregated client from the e2e test framework

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#76204]
please mind that this is more of a question/proposal.

in the e2e testing framework we import an aggregated clientset from here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L49

the only consumer of this client is this conformance test:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/aggregator.go#L80

> Should be able to support the 1.10 Sample API Server using the current Aggregator

the k8s testing commons group discussed if this client should be removed from the framework, possibly moved inside this test only.

PR in flight (needs changes):
https://github.com/kubernetes/kubernetes/pull/75989/files

questions:
- is this test up to date and maintained?
- any objections to creating the client in the test instead of the framework?

/sig testing
/sig api-machinery
/area e2e-test-framework

**Comment by timothysc** [comment]
@kubernetes/sig-api-machinery-test-failures  

For feedback on this ^

**Comment by sttts** [comment]
@timothysc I think moving the client construction to the test is fine. This is a very special purpose client anyway. I would avoid adding plumbing to the framework if it is only used in this one test.

**Comment by neolit123** [comment]
the related PR merged.
