### ISSUE TITLE
Enhance klog to split up the log files when it grows to 1.8GiB

### ISSUE THREAD

**Issue by yuwenma** [kubernetes/kubernetes#76210]
**What happened**:
klog supports "log-file" flag to specify the log file path. However, this log file doesn't support chunks. That's to say, when the size of the log file reaches 1.8GiB, the older logs are truncated. See details in [PR76190](https://github.com/kubernetes/kubernetes/pull/76190).     
 
**What you expected to happen**:
We want to keep all the log messages. If the log file goes too large, we expect to chunk the log file and compress the 1.8GB older logs in file kube-apiserver.log,gz.<with TIMESTAMP>.   

**How to reproduce it (as minimally and precisely as possible)**:

Cherry pick reverted [PR/75624](https://github.com/kubernetes/kubernetes/pull/75624) to your master, and build/release a new gcp version;
Create a cluster from the custom version,and when the log size (kube-controller-manager, kube-apiserver, kube-scheduler) reaches 1.8GiB. The older log messages will be truncated.  
**Anything else we need to know?**:
This issue needs to be fixed at least 1 month before v1.15. Since it blocks some v1.15 release features (like rebasing images from debian/alpine to distroless heavily depends on the klog feature).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14, v1.15
- Cloud provider or hardware configuration: GCP 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yuwenma** [comment]
@kubernetes/sig-release
@kubernetes/sig-scalability

**Comment by dims** [comment]
@yuwenma wanna create a mirror issue in https://github.com/kubernetes/klog ?

**Comment by tallclair** [comment]
Do we want to build logrotation into klog, or continue to rely on logrotate? If the former, maybe look into https://godoc.org/gopkg.in/natefinch/lumberjack.v2. If the latter, then klog needs to somehow recognize that the rotation has happened, and reopen the new file (any idea how this works in bash?).
