### ISSUE TITLE
Return total size of all matched data sets in LIST APIs responses

### ISSUE THREAD

**Issue by josh1707** [kubernetes/kubernetes#76247]
**What would you like to be added**:
Return total size of all matched data sets when I call the API with "limit" and "continue".

**Why is this needed**
1. To count the total pages for pagination.
2. I should query all data to get the total size without the "total size" property.

**Comment by josh1707** [comment]
@kubernetes/sig-api-machinery

**Comment by caesarxuchao** [comment]
See https://github.com/kubernetes/kubernetes/pull/75993
