### ISSUE TITLE
cross-build broken again?...? ...build constraints exclude all Go files...

### ISSUE THREAD

**Issue by Apokleos** [kubernetes/kubernetes#76259]
cross-build broken Again in k8s-v1.14.0 ? I am not sure. but I am suffering it!

**What happened**:
When I try to compile k8s-v1.14.0's cmd/kubelet module, I got the ERROR, and the ERROR is same to #58106, the bug  fixed some time ago, Why it comes up again! I don't know why! 
Error as below:
......
+++ [0408 16:50:40] Building go targets for linux/amd64:
    cmd/kubelet
vendor/github.com/google/cadvisor/accelerators/nvidia.go:29:2: build constraints exclude all Go files in /home/GoWorks/src/k8s.io/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/mindprince/gonvml
!!! [0408 16:50:42] Call tree:
!!! [0408 16:50:42]  1: /home/GoWorks/src/k8s.io/kubernetes/kubernetes/hack/lib/golang.sh:630 kube::golang::build_some_binaries(...)
!!! [0408 16:50:42]  2: /home/GoWorks/src/k8s.io/kubernetes/kubernetes/hack/lib/golang.sh:765 kube::golang::build_binaries_for_platform(...)
!!! [0408 16:50:42]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0408 16:50:42] Call tree:
!!! [0408 16:50:42]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0408 16:50:42] Call tree:
!!! [0408 16:50:42]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [all] Error 1

**What you expected to happen**:
I want to know why and how to fix it!!!
**How to reproduce it (as minimally and precisely as possible)**:
comile kubelet module step:
[root@foo kubernetes]# KUBE_BUILD_PLATFORMS=linux/amd64 make all WHAT=cmd/kubelet GOFLAGS=-v GOGCFLAGS="-N -l"

**Environment**:
kubernetes source code: v1.14.0
[root@foo kubernetes]# uname -msr
Linux 3.10.0-862.11.6.el7.x86_64 x86_64
[root@foo kubernetes]# go version
go version go1.12.2 linux/amd64
[root@foo kubernetes]# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/GoWorks"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build524368587=/tmp/go-build -gno-record-gcc-switches"
[root@foo kubernetes]#

**Comment by Apokleos** [comment]
(1) First Try:
When I use go1.11.3, it will be produce another error, and it gives me messages about go version required  go1.12.1 or greater as below:
[root@foo kubernetes]# KUBE_BUILD_PLATFORMS=linux/amd64 make all WHAT=cmd/kubelet GOFLAGS=-v GOGCFLAGS="-N -l"

Detected go version: go version go1.11.3 linux/amd64.
Kubernetes requires go1.12.1 or greater.
Please install go1.12.1 or later.

!!! [0409 15:21:42] Call tree:
!!! [0409 15:21:42]  1: hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.11.3 linux/amd64.
Kubernetes requires go1.12.1 or greater.
Please install go1.12.1 or later.

!!! [0409 15:21:42] Call tree:
!!! [0409 15:21:42]  1: /home/GoWorks/src/k8s.io/kubernetes/hack/lib/golang.sh:689 kube::golang::setup_env(...)
!!! [0409 15:21:42]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0409 15:21:42] Call tree:
!!! [0409 15:21:42]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
(2) Second Try
According to the error messages, I upgrade golang to go1.12.2. But  it will be failed with the error as below:
......
# k8s.io/kubernetes/cmd/kubelet
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-036607853/000008.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

!!! [0408 15:26:30] Call tree:
!!! [0408 15:26:30]  1: /home/GoWorks/src/k8s.io/kubernetes/hack/lib/golang.sh:624 kube::golang::build_some_binaries(...)
!!! [0408 15:26:30]  2: /home/GoWorks/src/k8s.io/kubernetes/hack/lib/golang.sh:758 kube::golang::build_binaries_for_platform(...)
!!! [0408 15:26:30]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0408 15:26:30] Call tree:
!!! [0408 15:26:30]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0408 15:26:30] Call tree:
!!! [0408 15:26:30]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [all] Error 1

(3) Third Try
I try to use go1.12.1.
When go v1.12.1 used and CGO_ENABLED="1" set,  the kubelet module will be compiled successfully!!! 
[root@foo kubernetes]# go version
go version go1.12.1 linux/amd64
[root@foo kubernetes]# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/GoWorks"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build439812382=/tmp/go-build -gno-record-gcc-switches"

So, I think,  "Kubernetes requires go1.12.1 or greater" is misleading. It does not work when I use go1.12.2.

I hope it will help you,buddy!!!

**Comment by liggitt** [comment]
```
/usr/bin/ld: /tmp/go-link-036607853/000008.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
```
that's a go error resolved in go1.12.3: https://github.com/golang/go/issues/31293

**Comment by liggitt** [comment]
it sounds like using go1.12.1 works (and I'd expect using go1.12.3 would work as well, given the go error was resolved in that version)

/close

**Comment by Apokleos** [comment]
@liggitt  
Yeah, I think,go1.12.2 and go1.12.3 both have the same bug.
I have tested compiling kubelet with go1.12.3.
It's a pity that go1.12.3 encounters the same problem as go1.12.2 does in my work. 
Now, only go1.12.1 works well!

**Comment by jomach** [comment]
I'm trying to compile cadvisor and I'm getting the same error...

```
jorge@Jorge-MacBook ~/Downloads/cadvisor                                                                                                                           [7:36:19]
> $ make build                                                                                                                                     
>> building assets
>> building binaries
>> building cadvisor
../../go/src/github.com/google/cadvisor/container/common/inotify_watcher.go:20:2: build constraints exclude all Go files in /Users/jorge/go/src/github.com/google/cadvisor/vendor/k8s.io/utils/inotify
make: *** [build] Error 1
```

**Comment by dims** [comment]
@jomach here you are building just cadvisor, not kubernetes, can you please open an issue there?

**Comment by Anutrix** [comment]
Got 
```
+++ Running case: verify.no-vendor-cycles
+++ working dir: /Users/nzaheerahmed/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-no-vendor-cycles.sh"
package github.com/google/cadvisor/manager
	imports github.com/google/cadvisor/resctrl: build constraints exclude all Go files in /Users/nzaheerahmed/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/resctrl
package github.com/opencontainers/runc/libcontainer/cgroups/systemd
	imports github.com/opencontainers/runc/libcontainer/cgroups/devices: build constraints exclude all Go files in /Users/nzaheerahmed/go/src/k8s.io/kubernetes/vendor/github.com/opencontainers/runc/libcontainer/cgroups/devices
+++ exit code: 1
+++ error: 1
FAILED   verify-no-vendor-cycles.sh	9s
```
on doing `make verify` on master branch.
Is this related?
