### ISSUE TITLE
Extend the criStatsProvider to collect more metrics

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes/kubernetes#76258]
**What would you like to be added**:
Supplement some metrics into cri stats, such as network info, maxUsage of Memory, CPU scheduling related metrics, etc.

We will extend the cri interface, and add the definitions of monitoring data. Then modify the criStatsProvider. 

**Why is this needed**:
With the development of security runtime, the metrics provided by cri stats currently are not enough for enterprise production. After the supplement, users will get the detail info about pods and containers.

Recently, we gradually start using kata and gvisor to run our applications. However we can not collect the metrics about containers and pods with a unified entrance in the kubelet level, such as network metrics, maxUsage of Memory, CPU scheduling related metrics, etc. Without these metrics, we can not monitor the pods and containers well. It will directly influence the service quality we provide on the Kubernetes.

So we want to provide a unified entrance to collect the runtime metrics. It is sure that we hope our solution is satisfied with community standard and overall tendency. 

Sincerely looking forward to some guidance from the Kubernetes community.

❌represents the missing metrics.
- CPU

- - CFS❌
  - Schedstat❌

- Memory

- - MaxUsage❌
   - Failcnt❌
   - RSS❌

- DiskIO❌

- - IoServiceBytes
  - IoServiced
  - IoQueued
  - Sectors
  - IoServiceTime
  - IoWaitTime
  - IoMerged
  - IoTime

- Network❌

- - RxBytes
  - RxPackets
  - RxErrors
  - RxDropped
  - TxBytes
  - TxPackets
  - TxErrors
  - TxDropped

**Comment by mattjmcnaughton** [comment]
@ZeroMagic thoughts on whether it would be appropriate to create a KEP for this work? https://github.com/kubernetes/enhancements

It seems large enough that that could be helpful :)

**Comment by WanLinghao** [comment]
@dashpole

**Comment by ZeroMagic** [comment]
@mattjmcnaughton Thanks. After a detailed discussion about this issue, we will decide if we need to create a KEP.

**Comment by allencloud** [comment]
> Would this break cAdvisor remove plan?

Thanks for your kind feedback. Actually I am wondering if we could get more details about the cAdvisor remove plan. Any link or somewhere. Searched on the issue list, while found no exactly matched one.  @mattjmcnaughton @dashpole

**Comment by WanLinghao** [comment]
@allencloud refer: https://github.com/kubernetes/kubernetes/issues/68522

**Comment by dashpole** [comment]
Thanks for looping me in.  One of the reasons we want to remove cAdvisor is because we don't think it is feasible, or wise to try and monitor every kind of container under the sun in cAdvisor.

We are then left with two ways we could get metrics without building in cAdvisor: Introduce CRI apis to carry the metrics and let the kubelet "re-expose" these metrics, or expose metrics directly from container runtimes.  I would advocate for the latter, as that removes the kubelet from the metrics serving path.  This removes a point of failure for metrics, simplifies the monitoring pipeline, and makes adding new metrics much simpler, as you don't need to get reviews from CRI maintainers.

**Comment by ZeroMagic** [comment]
@dashpole I have some questions about the latter way.
1. Which level of container runtimes do you mean, Containerd or KataContainers ?
2. How can kubelet get the metrics? Stats() API or commandl line?
3. When adding new metrics, we just need to modify container runtimes and kubelet. Is my understanding correct?

**Comment by dashpole** [comment]
1. Containerd/CRI-O
2. Why does the kubelet need the metrics?
3. I think it would be better if we just needed to modify the container runtime, and not the kubelet.

**Comment by ZeroMagic** [comment]
> 2. Why does the kubelet need the metrics?
In my understanding, `kubectl top` needs the metrics to show resource usage.

**Comment by stormgbs** [comment]
>  1. Containerd/CRI-O 

@dashpole Why only Containerd/CRI-O in the future? What about those cri compatible runtimes?

**Comment by dashpole** [comment]
> @dashpole Why only Containerd/CRI-O in the future? What about those cri compatible runtimes?

Apologies, any CRI compatible runtime can expose metrics, including Kata, etc.  I just listed those because I am familiar with them.

> In my understanding, kubectl top needs the metrics to show resource usage of pods.

resources required by kubectl top include CPU and memory usage metrics, which are already part of the CRI.
