### ISSUE TITLE
Limit Memory Emptydir size which mount on /dev/shm but df get the size always is half of machine

### ISSUE THREAD

**Issue by xqqcoder** [kubernetes/kubernetes#76263]
**What happened**:
i use the sizelimit to limit memory emptydir size, but the size i use "df" to get always is half of machine, i try to change the machine /dev/shm ,but it has no use

the machine:
Filesystem                                                                                                 Size  Used Avail Use% Mounted on
/dev/sda2                                                                                                   47G  6.6G   38G  15% /
devtmpfs                                                                                                   126G     0  126G   0% /dev
tmpfs                                                                                                      126G  516K  126G   1% /dev/shm

in container:
Filesystem                                                                                                 Size  Used Avail Use% Mounted on
tmpfs                                                                                                       64M     0   64M   0% /dev
tmpfs                                                                                                      126G     0  126G   0% /sys/fs/cgroup
tmpfs                                                                                                      126G     0  126G   0% /dev/shm
/dev/sda2                                                                                                   47G  6.6G   38G  15% /etc/hosts

some pod definition :
'empty_dir': {'medium': 'Memory',
                      'size_limit': '4Gi'},
'resources': {'limits': {'cpu': '32',
                       'memory': '64G',
                       'nvidia.com/gpu': '2'},
                       'requests': {'cpu': '32',
                       'memory': '64G',
                       'nvidia.com/gpu': '2'}},

**What you expected to happen**:
the sizelimit just limit usage , but what i can use should be all /dev/shm 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- OS (e.g: `cat /etc/os-release`): centos

**Comment by zffocussss** [comment]
same here.how to specify the size of tmpfs?
