### ISSUE TITLE
kube-proxy: Issue with IPv6 bind addresses for metrics and healthz.

### ISSUE THREAD

**Issue by josdotso** [kubernetes/kubernetes#76289]
**What happened**: Kube-Proxy does not apparently understand IPv6 addressing for HealthzBindAddress and MetricsBindAddress.

**What you expected to happen**: Kube-proxy to start without issue, binding as requested to IPv6.

**How to reproduce it (as minimally and precisely as possible)**: See below.

**Anything else we need to know?**: I'm using kubeadm to test and I removed the IPv4 addresses from all interfaces except `lo` (127.0.0.1).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): 18.04.1 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux vagrant 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 

```
ii  docker-ce                             5:18.09.4~3-0~ubuntu-bionic       amd64        Docker: the open-source application container engine
ii  docker-ce-cli                         5:18.09.4~3-0~ubuntu-bionic       amd64        Docker CLI: the open-source application container engine
```

Related: https://github.com/kubernetes/kubernetes/issues/62479#issuecomment-480992586

In an IPv6-only scenario of Kubernetes...

```
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:51:21Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "iptables"
healthzBindAddress: "::"
metricsBindAddress: "::1"
```
Results in:

```
[KubeProxyConfiguration.HealthzBindAddress: Invalid value: "::": must be IP:port, KubeProxyConfiguration.MetricsBindAddress: Invalid value: "::1": must be IP:port]
```

**Comment by MrHohn** [comment]
Thanks @josdotso, I remembered fixing this in https://github.com/kubernetes/kubernetes/pull/54191. I will take a stab to see why IPv6 address is not valid anymore.

/assign
/area ipv6
cc @leblancd @rpothier

**Comment by josdotso** [comment]
Thanks @MrHohn . Perhaps, the issue is that I'm using the config file way instead of the CLI args way? For that reason, perhaps this is an issue for kubeadm's validation of the config.

**Comment by JieJhih** [comment]
It seems like ``applyDeprecatedHealthzPortToConfig`` and ``applyDeprecatedMetricsPortToConfig`` dosen't return IPV6 format.
https://github.com/kubernetes/kubernetes/blob/1cca3f9d45a6aae62145b8630e36722bd316ef88/cmd/kube-proxy/app/server.go#L366-L392
https://github.com/kubernetes/kubernetes/blob/1cca3f9d45a6aae62145b8630e36722bd316ef88/pkg/proxy/apis/config/validation/validation.go#L196-L203

**Comment by MrHohn** [comment]
@JieJhih Thanks for the investigation. It true that the `applyDeprecatedXPortToConfig` func seems to not be ipv6 friendly. Though in @josdotso's case the CLI args are not involved at all, so might be a different issue.

**Comment by MrHohn** [comment]
@josdotso  After taking another look at the spec definition: https://github.com/kubernetes/kubernetes/blob/09f821ddb58dd59e89130f03b75a700061c117a8/pkg/proxy/apis/config/types.go#L111-L116
It seems like we are suppose to pass `HealthzBindAddress` and `MetricsBindAddress` in a `ip:port` fashion, instead of just IP. Can you try using this:
```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "iptables"
healthzBindAddress: "[::]:10256"
metricsBindAddress: "[::1]:10249"
```

**Comment by MrHohn** [comment]
I see, one issue is that the [`ApplyDefaults` func](https://github.com/kubernetes/kubernetes/blob/84b561033eea9a4dac5b04df4f387efa7a7e9940/cmd/kube-proxy/app/server.go#L468) seems to happen before we actually load from the given config file (in the [`Complete()` func](https://github.com/kubernetes/kubernetes/blob/84b561033eea9a4dac5b04df4f387efa7a7e9940/cmd/kube-proxy/app/server.go#L212-L230)). Hence the default ports (e.g. 10256, 10249) are not automatically appended in case they are not given.

Also, the `SetDefaults()` func is not compatible with IPv6 as well:
https://github.com/kubernetes/kubernetes/blob/37e6266ef4b203a3241bf140f36ff8ae29d2e1f7/pkg/proxy/apis/config/v1alpha1/defaults.go#L36-L49

Adding relevant folks to see if the ApplyDefaults order is intentional. @ncdc @xiangpengzhao

**Comment by ncdc** [comment]
We call `ApplyDefaults` in `NewProxyCommand` so the flag help text shows the default values when you run `--help`.

When the config file is loaded, the call to `UniversalDecoder().Decode()` applies defaults (i.e. it calls `SetDefaults_KubeProxyConfiguration`) if values are not present in the config file and there are applicable defaults.

I don't believe there is any issue with order of execution.

**Comment by ncdc** [comment]
I just tested `master` with a slight modification - I have it print out the resolved configuration after loading from `--config` and then it exits. I created a config file with the healthz and metrics bind addresses set to `0.0.0.0` and `127.0.0.1`, respectively. The values that were printed out had the ports appended (from the defaulting logic).

**Comment by MrHohn** [comment]
@ncdc Thanks! That clears my confusion --- so the issue is purely because `SetDefaults_KubeProxyConfiguration()` doesn't work with IPv6 address, but not the order of execution. We can address this with #76320.

**Comment by josdotso** [comment]
@MrHohn I recall trying it with port numbers too, and saw same issue. Shall I try again to be sure?

**Comment by MrHohn** [comment]
@josdotso Thanks, yeah would be great if you can try with that.

**Comment by josdotso** [comment]
@MrHohn The square brackets are the fix I guess:

With config...

```yaml
healthzBindAddress: ':::10256'
metricsBindAddress: '::1:10249'
```

the result is:

```
F0412 01:11:14.285591       1 server.go:466] failed validate: [KubeProxyConfiguration.HealthzBindAddress: Invalid value: ":::10256": must be IP:port, KubeProxyConfiguration.MetricsBindAddress: Invalid value: "::1:10249": must be IP:port]
```

But, with config...

```yaml
healthzBindAddress: '[::]:10256'
metricsBindAddress: '[::1]:10249'
```

the result looks good:

```
I0412 01:14:05.753308       1 server_others.go:78] IPv6 bind address (::), assume IPv6 operation
I0412 01:14:05.794495       1 server_others.go:148] Using iptables Proxier.
I0412 01:14:05.794746       1 server_others.go:178] Tearing down inactive rules.
E0412 01:14:05.831450       1 proxier.go:583] Error removing iptables rules in ipvs proxier: error deleting chain "KUBE-MARK-MASQ": exit status 1: ip6tables: Too many links.
I0412 01:14:06.066330       1 server.go:555] Version: v1.14.0
I0412 01:14:06.086339       1 config.go:102] Starting endpoints config controller
I0412 01:14:06.086534       1 controller_utils.go:1027] Waiting for caches to sync for endpoints config controller
I0412 01:14:06.086661       1 config.go:202] Starting service config controller
I0412 01:14:06.086768       1 controller_utils.go:1027] Waiting for caches to sync for service config controller
I0412 01:14:06.186892       1 controller_utils.go:1034] Caches are synced for endpoints config controller
I0412 01:14:06.186980       1 controller_utils.go:1034] Caches are synced for service config controller
```

I'm not sure yet what's up with the `proxier.go:583` error, but it seems unrelated.

Thanks! For some reason, I didn't try the IPv6 address with brackets + port number combination the other day.
