### ISSUE TITLE
Backwards incompatible client-go/testing across major versions makes it hard to use generated fakes for vendored CRD clients

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#76305]
test-infra uses:
* core kubernetes client code to manage things like pods
* a generated prow client to manage prowjob CRD resources
* a generated knative/build client to manage build CRD resources

We use the generated fake_build client for some of our unit testing. However, the signature for many of the methods in action.go in k8s.io/client-go/testing changed to include a PatchType method (added in https://github.com/kubernetes/kubernetes/pull/69330). 

This makes it unnecessarily hard for me to update the client-go version test-infra, as I either have to:
* Wait for CRD clients to upgrade client-go and regenerate their fakes
* Regenerate clients in vendored code
* Refactor my unit testing to avoid using generated fakes.

One solution here might be to start tagging our modules with major releases, which should allow the vendored knative/build to continue using the older version of client-go while the code under my control starts using the new version.

```
/usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/b0ebb806f871834291964fdb37490052/sandbox/linux-sandbox/31/execroot/io_k8s_test_infra/vendor/github.com/knative/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_build.go:131:44: not enough arguments in call to testing.NewPatchSubresourceAction
	have (schema.GroupVersionResource, string, string, []byte, []string...)
	want (schema.GroupVersionResource, string, string, types.PatchType, []byte, ...string)
/usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/b0ebb806f871834291964fdb37490052/sandbox/linux-sandbox/31/execroot/io_k8s_test_infra/vendor/github.com/knative/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_buildtemplate.go:119:44: not enough arguments in call to testing.NewPatchSubresourceAction
	have (schema.GroupVersionResource, string, string, []byte, []string...)
	want (schema.GroupVersionResource, string, string, types.PatchType, []byte, ...string)
/usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/b0ebb806f871834291964fdb37490052/sandbox/linux-sandbox/31/execroot/io_k8s_test_infra/vendor/github.com/knative/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_clusterbuildtemplate.go:112:48: not enough arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, []byte, []string...)
	want (schema.GroupVersionResource, string, types.PatchType, []byte, ...string)
```

FYI @sttts @lavalamp @caesarxuchao @liggitt 
@kubernetes/sig-api-machinery-bugs 

ref https://github.com/kubernetes/test-infra/issues/12107

**Comment by liggitt** [comment]
> One solution here might be to start tagging our modules with major releases, which should allow the vendored knative/build to continue using the older version of client-go while the code under my control starts using the new version.

We would have to go all the way to semantic import versioning for multiple versions to coexist in a build as you describe. Some of the implications of that are described at https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md#alternative-versioning-strategies

I am in favor of major version tagging the other k8s.io components to match client-go

/remove-kind bug
/kind feature

**Comment by fejta** [comment]
> especially if we are using the full power of the fakes to drive listers/informers/watchers.

Not convinced the trade-off is worth it here until kubernetes can prove it is a better citizen about following semver correctly.

If dependencies are cause maintenance/upgrade pain and we can remove them it is strongly in our interest to do so.

Faking object lists and object change notifications is not hard, and not worth getting stuck forever on a single version.
