### ISSUE TITLE
Unbounded valuesets for metric labels

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#76302]
Currently, we have a number of metrics in the kube-apiserver which will likely become problematic in the near-ish future. Specifically, metrics which currently have 'resource' as a label are unbounded. In large part, this is due to the emergence of CRDs, which has had the effect of unbounding the cardinality of resources (and sub-resources) served by the kube-apiserver. This dimension was previously bound to control-plane specific critical resources (e.g. pods, nodes, namespaces). 

The effect of this is that issues like #69540 will become increasingly likely since we cannot control the number of time-series generated by a given metric (these metrics effectively become memory leaks). While that issue was resolved (temporarily) by #69895, this is actually only a mitigation, since it does not solve the root of the problem (i.e. CRDs can cause unbounded metric growth). 

Since we still use resource/sub-resource in apiserver request metrics (e.g. apiserver_request_latencies, apiserver_response_sizes, apiserver_request_duration_seconds, apiserver_longrunning_gauge, apiserver_request_count), and since we are still adding actively adding labels to these metrics, it is likely only a matter of time before this becomes an issue again, since values for labels have a multiplicative effect on metric size.

/sig api-machinery instrumentation

**Comment by logicalhan** [comment]
/cc @smarterclayton @brancz (just as an FYI)

Also, the issue #69540 involved a single cluster. This impacts fleetwide aggregations for metrics like this and will also likely recur in single clusters (once it grows large enough and employs enough CRDs).

**Comment by smarterclayton** [comment]
Clients are already unbounded and much higher in practice.  Whatever solution we pick is going to have to do something about that too.

**Comment by logicalhan** [comment]
> Clients are already unbounded and much higher in practice. Whatever solution we pick is going to have to do something about that too.

Oh, yeah I hate those things. I was thinking we may want to do some pre-processing prior to emitting the client value in those metrics, so that doesn't bring in directory strings and version data and such. Thoughts? 

But yeah, I agree it would be generally desirable to have this dimension bounded as well.
