### ISSUE TITLE
Density test should surface node failures

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#7630]
I currently have an 80 node cluster with 3 un-sshable nodes, I didn't really do anything special, no idea why they're down. If I run density against this cluster, I'll get hit with failures because of (https://github.com/GoogleCloudPlatform/kubernetes/issues/7222). This is not easy to figure out after the test. 

More importantly if a node goes down after a pod has been scheduled, the test will fail without saying the node was down. Even more fun if the node comes back up by the time I get around to listing them, because I have no idea why the number of pods just went from 3000 to 2999.

@wojtek-t @rrati

**Comment by wojtek-t** [comment]
Thanks for reporting it - it's a really good point.

**Comment by wojtek-t** [comment]
cc @fgrzadkowski
