### ISSUE TITLE
winkernel proxy is deleting hnsendpoint while it's still referenced by another k8s service.

### ISSUE THREAD

**Issue by jxiewei** [kubernetes/kubernetes#76316]
**What happened**: We have two service(A & B) pointing to the same pod and different port, if we delete service A, service B becomes unaccessible from nodes other than the node pod is running at.

**What you expected to happen**: Deleting service A doesn't affect servicie B.

**How to reproduce it (as minimally and precisely as possible)**: Create two service pointing to the same pod and different port, check service accessibility from other nodes, then delete service A, check service B accessibility from other nodes.

**Anything else we need to know?**:  winkernel proxy refers hnsEndpoint from two endpointInfo structure if they points to same ip, both endpointInfo has refCount 1. If service A deleted, winkernel proxy will delete hnsEndpoint, causing another endpointInfo referring invalid  hnsEndpoint.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.12.4
- Cloud provider or hardware configuration:  aliyun
- OS (e.g: `cat /etc/os-release`): windows 1809
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by jxiewei** [comment]
@kubernetes/sig-windows-bugs

**Comment by ksubrmnn** [comment]
Can you include kube proxy logs from where it crashes? Does proxier crash?

I would expect the endpoint to be recreated even if it is deleted. Which is still not optimal but shouldn't cause crashes. I'm interested to see where the error is.

**Comment by daschott** [comment]
@jxiewei does this still repro in v1.14?

**Comment by jxiewei** [comment]
> Can you include kube proxy logs from where it crashes? Does proxier crash?
> 
> I would expect the endpoint to be recreated even if it is deleted. Which is still not optimal but shouldn't cause crashes. I'm interested to see where the error is.

proxier doesn't crash, service B becomes inaccessible, because underlying hns endpoint is gone.

**Comment by daschott** [comment]
@jxiewei what is the use-case for having 2 services point to the same pod?
Also, is service B accessible again after some time? Can you show the kube-proxy logs and endpoints (get-hnsendpoint) on the node where it is not accessible anymore?

**Comment by daschott** [comment]
Oh looks, like this is resolved already. Can we close this issue?

**Comment by ksubrmnn** [comment]
@daschott Can you follow up with Keith's team to take this up?

**Comment by ksubrmnn** [comment]
@daschott also that PR is closed and won't be opened again. There was another PR open for this, and I left feedback, but I don't think I heard back. That was some time ago.
