### ISSUE TITLE
kubeadm config file not support "apiServerCertSANs" filed?

### ISSUE THREAD

**Issue by ananclub** [kubernetes/kubernetes#76357]
when i use kubeadm to create k8s cluster,it report:

W0410 09:21:51.963920   26052 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta1", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "apiServerCertSANs"

config file content:

apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.14.0
controlPlaneEndpoint: 106.14.181.102:8443
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
- 192.168.11.190
- 192.168.11.191
- 192.168.11.192

**Comment by neolit123** [comment]
/close

please read details about the v1beta1 config here:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

there is no  field apiServerCertSANs in v1beta1.
to achieve that you need:
```
kind: ClusterConfiguration
...
apiServer:
  certSANs:
  - "10.100.1.1"
  ....
```
