### ISSUE TITLE
Let kubelet respect pod's finalizers

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#76360]
**What would you like to be added**:
If pod's finalizer list is not empty, kubelet should keep it running until its finalizer list is empty even its deletion timestamp is set.

**Why is this needed**:
If I understand it correctly,  finalizer works as a pre-delete hook. We create ingress for pods, and want to remove pod from ingress firstly before terminating it, then we could avoid request traffic are sent to pods that are not running. 

/sig node

**Comment by liggitt** [comment]
Finalizers control the *API object* lifecycle, not the lifecycle of the pod process. A pod that has had deletion requested is subject to it's process being terminated.

You can use the preStop lifecycle and/or terminationGracePeriodSeconds in combination with SIGTERM handling in your container process to control how long a pod remains running after deletion is requested to give your controller time to observe the deletionTimestamp and react prior to the container process being terminated.

/close
