### ISSUE TITLE
Failed deployment upgrade-  removing a serviceAccount from a deployment template does not get applied to kubernetes deployment object

### ISSUE THREAD

**Issue by randude** [kubernetes/kubernetes#76367]
**What happened**:
We used Helm to upgrade our deployment. It causes our 
You can view the thread here:
https://github.com/helm/helm/issues/5473

hickeyma verified this issue is not a helm but but a K8s patch command bug.

**What you expected to happen**:
I installed a deployment which was added a serviceAccountName. Then when I tried to install a version that doesnt use the serviceAccountName, the pod couldn't load.
What happened is that the serviceAccount was deleted as expected BUT the serviceAccountName was NOT removed from my deployment. So the pod couldnt load and my deployment was broken.
I had to manually edit the deployment and remove the serviceAccountName entry. This solved the issue.

**How to reproduce it (as minimally and precisely as possible)**:
Thanks hickeyma  from the helm team for writing this:
1. Install a chart which contains deployment which references a service account. Easiest to add service account resources in the chart.
2. Upgrade the release where the deployment no longer references the service account and the service account has been removed (for example, remove the service account resource from the chart before upgrade). Need to pass --recreate-pods with helm upgrade.
3. The pod should terminate and fail to restart.

**Anything else we need to know?**
This happens because the serviceAccountName field in the pod specification object is not handled by patch, and therefore it's not removed during an upgrade.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Helm:
Output of helm version:
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
- Others:
Cloud Provider/Platform (AKS, GKE, Minikube etc.):
On premise kubeadm -
kubeadm version -
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

@kubernetes/sig-architecture
/sig architecture
/sig cli

**Comment by liggitt** [comment]
This is unfortunate, but both fields are honored because of a name change around the 1.0 timeframe. the deprecated `serviceAccount` field can be removed if a new apiVersion of pods is introduced, but until then, clearing a service account on an existing object requires explicitly setting both `serviceAccount: ""` and `serviceAccountName: ""`

/close
