### ISSUE TITLE
Scalability tests should not consume public IPs for every node

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#76374]
Public IPs are expensive resources. Given that we're running scalability tests on 5k-node clusters, we are unnecessarily consuming 5k IPs which is a lot.

We should switch our tests so that nodes have only private IP addresses.

We are going to do that by configuring NAT so that nodes can talk to outside world (e.g. to download image from dockerhub). But that also requires changing some correctness tests which assume public IPs.

**Comment by mm4tt** [comment]
To summarize recent work:

1. Implementing setting up private gce clusters with nat, feature is gated via the `KUBE_GCE_PRIVATE_CLUSTER` env
2. CI test and dashboard with correctness tests on gce private cluster - https://k8s-testgrid.appspot.com/sig-scalability-experiments#gce-private-cluster-correctness
3. Currently 27 tests fail
4. WIP on fixing the tests - https://github.com/kubernetes/test-infra/pull/12252 should fix majority of them

**Comment by wojtek-t** [comment]
@mm4tt - is there anything missing to be done here?

**Comment by mm4tt** [comment]
No, we can close this one. It was done long time ago. Thanks for catching

/close
