### ISSUE TITLE
Certificates problems in kubeadm HA

### ISSUE THREAD

**Issue by felixPG** [kubernetes/kubernetes#76377]
**What happened**:

Hi All. Im facing a problem in HA k8s cluster bootstrapped by kubeadm. All work OK, but kubectl logs does not work. *net/http: TLS handshake timeout* .If I not wrong, kube-apiserver in *kubectl logs* forward the request *to the kubelet node where the pod are running*. Appear that kubelet certificate on that node are rejected, why???
If I make a curl from master to the node where the pod are running (same request that *kubectl logs*) the error is *Peer's certificate issuer has been marked as not trusted by the user.* .So, if in theory, *kubeadm copy all certificates to all nodes*, and *trust* this certificates, why the certificate was marked as untrusted? (editado) 

**What you expected to happen**:
kubectl logs work properly

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an HA kubernetes cluster with kubeadm
**Anything else we need to know?**:
k8s version 1.14

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.0

**Comment by neolit123** [comment]
>  All work OK, but kubectl logs does not work. net/http: TLS handshake timeout

i'm not seeing this particular problem in a local HA test setup.

but i do see a spam of:
```
I0410 21:40:51.463549       1 log.go:172] http: TLS handshake error from 172.17.0.5:51654: tls: client offered only unsupported versions: [300]
I0410 21:40:53.465046       1 log.go:172] http: TLS handshake error from 172.17.0.5:51678: tls: client offered only unsupported versions: [300]
I0410 21:40:55.467707       1 log.go:172] http: TLS handshake error from 172.17.0.5:51706: tls: client offered only unsupported versions: [300]
I0410 21:40:57.471854       1 log.go:172] http: TLS handshake error from 172.17.0.5:51736: tls: client offered only unsupported versions: [300]
I0410 21:40:59.471560       1 log.go:172] http: TLS handshake error from 172.17.0.5:51770: tls: client offered only unsupported versions: [300]
I0410 21:41:01.473058       1 log.go:172] http: TLS handshake error from 172.17.0.5:51796: tls: client offered only unsupported versions: [300]
I0410 21:41:03.474616       1 log.go:172] http: TLS handshake error from 172.17.0.5:51824: tls: client offered only unsupported versions: [300]
```

when calling:
```
kubectl logs <kube-api-server-pod> -n kube-system
```

@kubernetes/sig-cluster-lifecycle

**Comment by felixPG** [comment]
@neolit123 and what about *kubectl logs -f* .This will trigger the error.

**Comment by neolit123** [comment]
`-f` is just the flag to follow the log stream, i don't think this will cause a `net/http: TLS handshake timeout`.
