### ISSUE TITLE
Some removed containers in a pod stay in Running status, and pod cannot be deleted

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#76382]
**What happened**:
We met the scenario: we have two containers in a pod, one is in unhealthy status (container terminated), others running. Delete the pod and we saw that the the latter container always stay in "Running" status, as as result, the pod will always in "Terminating" status and cannot get deleted.

**What you expected to happen**:
Pod got deleted as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Here is an yaml with which you can reproduce the issue(The issue is not necessarily happen, but can be reproduced after trial several times)
```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
  namespace: test
spec:
  parallelism: 1
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "cat /non-exist-file"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cat /non-exist-file"]
      - name: d
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sleep infinity"]
      restartPolicy: Never
```
**Anything else we need to know?**:
Looking into the log, I can see message like this:
```
E0403 10:02:54.734120   32321 status_manager.go:340] Status update on pod world-002/job-wq-2-tt8cq aborted: terminated container c attempted illegal transition to non-terminated state
I0403 10:02:56.734554   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:03:06.734939   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:03:16.735480   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:03:26.733800   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:03:36.733862   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:03:46.735081   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:03:56.735565   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:04:00.733732   32321 kubelet.go:2439] SyncLoop (SYNC): 3 pods; test-04_cci-test(5d7b06c1-5128-11e9-b75a-80d4a5ae3e2b), cci-liufw2-56cdb645bb-hhttj_cci-test(986c7070-52ec-11e9-b75a-80d4a5ae3e2b), job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)
I0403 10:04:00.734078   32321 kubelet_pods.go:1569] Generating status for "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)"
E0403 10:04:00.734283   32321 status_manager.go:340] Status update on pod world-002/job-wq-2-tt8cq aborted: terminated container c attempted illegal transition to non-terminated state
I0403 10:04:06.735371   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:04:16.733922   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:04:26.735469   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:04:36.735530   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:04:46.734262   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:04:56.734059   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:05:06.735144   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:05:13.733733   32321 kubelet.go:2439] SyncLoop (SYNC): 2 pods; job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b), imc-bbbdc454d-p52dg_cci-auto-1553827123609(232945ab-51cc-11e9-b75a-80d4a5ae3e2b)
I0403 10:05:13.733841   32321 kubelet_pods.go:1569] Generating status for "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)"
E0403 10:05:13.733960   32321 status_manager.go:340] Status update on pod world-002/job-wq-2-tt8cq aborted: terminated container c attempted illegal transition to non-terminated state
I0403 10:05:16.734056   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:05:26.734980   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
I0403 10:05:36.734122   32321 kubelet_pods.go:1117] Pod "job-wq-2-tt8cq_world-002(e3fb6c57-55b3-11e9-b75a-80d4a5ae3e2b)" is terminated, but some containers are still running
```

And in the last recorded pod status of status_manager, container"d" is still of "Running" status, it looks like kubelet missed the event to update container "d" from "Running" to "terminated" status.

AFAIK, when kubelet got multi events for a same pod at the same time, some of them may got thrown away and not handled (first stored in `lastUndeliveredWorkUpdate` of podwork and later replaced by other events). 

So a wild guess here: the event triggered by PLEG to update container "d" from "Running" to "Terminted" happened to be thrown away here. and in later loops, underlying container has already been killed and removed, thus, containerstatus got from PLEG would be nil, we [treat the scenario as in need of restart and generate Waiting status](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L1540), that's why we saw message like `terminated container c attempted illegal transition to non-terminated state` in status manager log

log file:
[pod terminating log](https://github.com/kubernetes/kubernetes/files/3063738/pod.terminating.log)

/sig node
/kind bug
**Environment**:
- Kubernetes version (use `kubectl version`):
1.13
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lichuqiang** [comment]
@dashpole @sjenning I noticed you've addressed similar issues before (not exactly the same issue though), can you please help take a look?  thx :)

**Comment by lichuqiang** [comment]
Here I tried to tell the story more briefly:
Normally container status in the lifecycle of the pod above looks like this:
create pod (container "c" terminated, container "d" running) -->delete pod(container "c" terminated, container "d" terminated)-->pod API object got removed

But for some reason (I guess there were too many events of the pod at the time, the event triggered by PLEG to update container "d" from "Running" to "Terminted" happened to be thrown away), later, we cannot get status of the containers as they have been removed, thus, [kubelet would try to fulfill with Waitcreating status](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L1539), but [here in status manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L292), it does not allow container "c" to transit from "terminated" to "waiting"(as the pod is of "Never" restart policy).
As a result, the pod status would no longer get updated, and container "d" would stay in "Running" status, as a result, the pod API object can not be removed by kubelet.

**Comment by lichuqiang** [comment]
```
func ShouldContainerBeRestarted(container *v1.Container, pod *v1.Pod, podStatus *PodStatus, existingStatus *v1.ContainerStatus) bool {
	// Get latest container status.
	status := podStatus.FindContainerStatusByName(container.Name)
	// If the container was never started before, we should start it.
	// NOTE(random-liu): If all historical containers were GC'd, we'll also return true here.
	if status == nil {
		if existingStatus == nil || existingStatus.State.Terminated == nil {
			glog.V(5).Infof("Container %s in pod %s is of nil state, in need of restart, pod status: %v", container.Name, format.Pod(pod), podStatus)
			return true
		}
		if pod.Spec.RestartPolicy == v1.RestartPolicyNever ||
			existingStatus.State.Terminated.ExitCode == 0 && pod.Spec.RestartPolicy == v1.RestartPolicyOnFailure {
			// We'd not restart here if container already terminated and
			// 1. RestartPolicy is "Never".
			// 2. RestartPolicy is "OnFailure" but last ExitCode is 0.
			glog.V(5).Infof("Container %s in pod %s already terminated, no need to restart, last status: %v", container.Name, format.Pod(pod), existingStatus)
			return false
		}
		glog.V(5).Infof("Container %s in pod %s is of nil state, in need of restart, pod status: %v", container.Name, format.Pod(pod), podStatus)
		return true
	}
```

Here I update func `ShouldContainerBeRestarted` like this, following the rule in func `checkContainerStateTransition` of status manger, and for the pod above, it would not try to transit container "c" from "terminated" to "waiting", and when the event to update container "d" from "Running" to "Terminted" lost, it would looks like this:

create pod (container "c" terminated, container "d" running) -->delete pod(container "c" terminated, container "d" waiting)-->pod API object got removed

Thus, pod can be deleted anyway.

**Comment by tedyu** [comment]
Can you show existingStatus is obtained in the caller to ShouldContainerBeRestarted ?

**Comment by ypnuaa037** [comment]
Hi, Is there any progress on this issue? We had this problem too, if we delete controller-manager container by 'docker rm -f ' quickly after controller-manager starts, there is a small probability that it will happen (pod still running, but container removed). It seems PLEG missing the event of this container (event channel wasn't full)
