### ISSUE TITLE
Restrict pod scheduling to nodes by namespace

### ISSUE THREAD

**Issue by ev4ern** [kubernetes/kubernetes#76386]
Is there any way to restrict pod scheduling to nodes by namespace?
For example I have a set of nodes for production services and I don't want scheduler to create pods on them. Cause some pods in non production namespaces can  fails and it can affects production services.

**Comment by hex108** [comment]
@ev4ern You could try admission controller `PodNodeSelector` https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
