### ISSUE TITLE
Dependency Graph For Analysis

### ISSUE THREAD

**Issue by alok87** [kubernetes/kubernetes#76395]
## Objective
The task here is to visualise the kubernetes dependency graph. Use this visualisation to bring out insights in the optimisations that can be made.
- Get rid of unwanted dependencies by making surgical changes [for example](https://github.com/google/cadvisor/pull/2209)
- Find and update the dependencies which are [required](https://docs.google.com/document/d/1HtTI0rJEGP_MSf6eO87aCmx_tzpovPAAg7U2Zxwm8FE/edit#heading=h.ptf7bvotn64)
- Remove duplicates and merge dependencies if possible

## Top Level Dependency Graph
This is a top level dependency graphs. More dependency graphs per dependency will be released once we find which are the ones we need to be working on.

![Alt text](https://raw.github.com/alok87/svgs/master/k8s-dependencies.svg?sanitize=true)

## Analysis (Work in Progress)

**Comment by alok87** [comment]
/hold

cc @dims

**Comment by neolit123** [comment]
thanks for the graph!

/sig architecture
/kind design
/hold cancel

**Comment by neolit123** [comment]
looks like we still have dependencies on:
- github.com/golang/glog
- github.com/ghodss/yaml

decoupling from *sdk* is long term goal too.

**Comment by rajibmitra** [comment]
is this done ?

**Comment by alok87** [comment]
I think this was not used. Check in Code organization project. @dims can give more info.
