### ISSUE TITLE
When sandbox got recreated, related container were not killed explicitly

### ISSUE THREAD

**Issue by peter-wangxu** [kubernetes/kubernetes#76416]
**What happened**:
When sandbox container got recreated, whatever reason(server reboot, sandbox got killed), the related container in the pod should be killed explicitly, otherwise the cpu manager would leave the container in the /var/lib/kubelet/cpu_manager_state, causing cpu leak

**What you expected to happen**:

the expected behavior should be: the containers in the pod got killed and the lifecycle hooks are invoked in order to lease the cpu occupied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable cpu manager in kubelet
2. create a pod with guarantee QoS
3. reboot the server of the running pod
4. after server is up, check the `cid` of the terminated containers
5. checking the /var/lib/kubelet/cpu_manager_state, the entry of the `cid` was left there

here is the leak evidence：

```bash
root@ubuntu:~# docker kill  f0838c82f70b
f0838c82f70b
root@ubuntu:~# docker ps -a | grep my-pod-with-anovol
96041e11a37f        88dfbf70e51f                      "sleep 1000000"          54 seconds ago      Up 53 seconds                                         k8s_my-frontend_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_1
9fda0a2c4905        k8s.gcr.io/pause:3.1              "/pause"                 55 seconds ago      Up 54 seconds                                         k8s_POD_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_1
c105b5ecd642        88dfbf70e51f                      "sleep 1000000"          11 minutes ago      Exited (137) 55 seconds ago                           k8s_my-frontend_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_0
f0838c82f70b        k8s.gcr.io/pause:3.1              "/pause"                 11 minutes ago      Exited (137) About a minute ago                       k8s_POD_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_0
root@ubuntu:~# cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0","entries":{"96041e11a37f600c75accb303066110db02736e5f8daa1d7753c710448dfa1a5":"2","c105b5ecd642a05055563095f1240ae82f9344cca4bba63fa67aee164882bb51":"1"},"checksum":340621555
```
NOTE: `f0838c82f70b` is the sandbox of the pod

**Anything else we need to know?**:

**Environment**:
```
kubelet --version
Kubernetes v1.13.3
```

**Comment by dixudx** [comment]
cc @kubernetes/sig-node-bugs 
/sig node

**Comment by Pingan2017** [comment]
```
[root@hpa-vm:~]$ cat /var/lib/kubelet/cpu_manager_state 
{"policyName":"static","defaultCpuSet":"0,2-3","entries":{"733d5bfca5104046d143c20ab4c4ea9702efa3d2d48bb05a50ea2958ab505c75":"1"},"checksum":1486071111}[root@hpa-vm:~]$ 
[root@hpa-vm:~]$ 
[root@hpa-vm:~]$ docker stop efa30aac8a2b
efa30aac8a2b
[root@hpa-vm:~]$ 
[root@hpa-vm:~]$ cat /var/lib/kubelet/cpu_manager_state 
{"policyName":"static","defaultCpuSet":"0,2-3","entries":{"ff85a582359e627610e40ea6f65cb0ea3fccc34cdc03050456b921b66670d999":"1"},"checksum":2318522498}[root@hpa-vm:~]$ 
```
no err in my cluster.
[root@hpa-vm:~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.1067+eaa78b88ac25a6", GitCommit:"eaa78b88ac25a61bfb1aa81d118c5ffeda041b64", GitTreeState:"clean", BuildDate:"2019-03-15T08:03:30Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.1067+eaa78b88ac25a6", GitCommit:"eaa78b88ac25a61bfb1aa81d118c5ffeda041b64", GitTreeState:"clean", BuildDate:"2019-03-16T02:54:47Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}

maybe it has been fixed.

**Comment by peter-wangxu** [comment]
@Pingan2017 Can you please share your kubelet config? here is mine:
```
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --resolv-conf=/run/systemd/resolve/resolv.conf -v 8 --feature-gates=CSIDriverRegistry=true,CSINodeInfo=true,CPUManager=true --cpu-manager-policy=static --system-reserved=cpu=100m
```

**Comment by peter-wangxu** [comment]
> ```
> [root@hpa-vm:~]$ cat /var/lib/kubelet/cpu_manager_state 
> {"policyName":"static","defaultCpuSet":"0,2-3","entries":{"733d5bfca5104046d143c20ab4c4ea9702efa3d2d48bb05a50ea2958ab505c75":"1"},"checksum":1486071111}[root@hpa-vm:~]$ 
> [root@hpa-vm:~]$ 
> [root@hpa-vm:~]$ docker stop efa30aac8a2b
> efa30aac8a2b
> [root@hpa-vm:~]$ 
> [root@hpa-vm:~]$ cat /var/lib/kubelet/cpu_manager_state 
> {"policyName":"static","defaultCpuSet":"0,2-3","entries":{"ff85a582359e627610e40ea6f65cb0ea3fccc34cdc03050456b921b66670d999":"1"},"checksum":2318522498}[root@hpa-vm:~]$ 
> ```
> no err in my cluster.
> [root@hpa-vm:~]$ kubectl version
> Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.1067+eaa78b88ac25a6", GitCommit:"eaa78b88ac25a61bfb1aa81d118c5ffeda041b64", GitTreeState:"clean", BuildDate:"2019-03-15T08:03:30Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.1067+eaa78b88ac25a6", GitCommit:"eaa78b88ac25a61bfb1aa81d118c5ffeda041b64", GitTreeState:"clean", BuildDate:"2019-03-16T02:54:47Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
> 
> maybe it has been fixed.

I tried on newer version(1.14.1), a fix somehow mitigated the dead container in state file, while the state file clean(meaning killcontainer) happens after the new container creation, that mean if the host doesn't have enough cpu, the new container is not able to start up due to enough cpus.

My fix is trying to release the cpuset occupied by the dead container ASAP.
