### ISSUE TITLE
Need better error message for service proxy endpoints

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#7642]
If I try and visit a service with multiple ports via the proxy at the master and I don't specify a port I get an unhelpful error message e.g. `https://104.197.36.97/api/v1beta3/proxy/namespaces/default/services/elasticsearch-elasticsearch`

```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for \"elasticsearch-kibana\"",
  "code": 500
}
```

Well, this service does have two ports: `es` and `kibana`. Specifying the port works:
`https://104.197.36.97/api/v1beta3/proxy/namespaces/default/services/elasticsearch-kibana` gives

```
{
  "status" : 200,
  "name" : "Cardinal",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.5",
    "build_hash" : "2aaf797f2a571dcb779a3b61180afe8390ab61f9",
    "build_timestamp" : "2015-04-27T08:06:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

We should give a better error message.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
