### ISSUE TITLE
Volume mount fails with "cannot open directory" after some period of inactivity

### ISSUE THREAD

**Issue by ArtemAvramenko** [kubernetes/kubernetes#76436]
**What happened**:
I mount host folder and it works after applying. But after some period of time (one hour or more) or after host rebooting, the volume is gone:

    # cd /my-mount-path
    # ls
    ls: cannot open directory '.': No such file or directory

**What you expected to happen**:

The volume should be mounted even after reboot.

**How to reproduce it (as minimally and precisely as possible)**:

I specify voume mount in yaml:

        volumeMounts:
        - name: my-mount
          mountPath: /my-mount-path

and specify host path:

      volumes:
      - name: my-mount
        hostPath:
          path: /host_mnt/c/my-host-path

**Environment**:
- Kubernetes version: v1.10.11
- OS: Windows 10 Pro x64

**Comment by ArtemAvramenko** [comment]
@kubernetes/sig-windows-bugs

**Comment by ArtemAvramenko** [comment]
It seems that problem is hard to reproduce. I reset Kubernetes Cluster and the problem has gone, permanently I hope.

**Comment by andyzhangx** [comment]
@ArtemAvramenko is it due to `/host_mnt/c/my-host-path` has changed after reboot? so the symlink does not work?

**Comment by ArtemAvramenko** [comment]
@andyzhangx No, the С:\my-host-path folder is permanent and is on system drive physically.
