### ISSUE TITLE
Kubelet keeps creating identical rule on Deb Buster

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#76431]
**What happened**: Kubelet keeps creating identical rule:
```
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x8000/0x8000 /* kubernetes firewall for dropping marked packets */
...
# iptables -L -v -n | grep "kubernetes firewall for dropping marked packets" | wc -l
# Warning: iptables-legacy tables present, use iptables-legacy to see them
4190
```

**What you expected to happen**:
Have only one created

**How to reproduce it (as minimally and precisely as possible)**:
Run kubelet 1.12.7 on Debian Buster

**Anything else we need to know?**:
This issue does not seem to happen on Debian Stretch and kubelet 1.12.5

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.7
- Cloud provider or hardware configuration: on-prem
- OS (e.g: `cat /etc/os-release`): Debian Buster (updated today)
- Kernel (e.g. `uname -a`): 4.19 
- Install tools: manual
- Others:

I'll try taking a look at the source code, but I have no idea if there were any important changes to iptables (other than iptables-legacy).

Thanks,
Ashley

**Comment by CallMeFoxie** [comment]
tried
```
update-alternatives --config iptables
```
to switch from `/usr/sbin/iptables-nft` to `/usr/sbin/iptables-legacy` and it seems to be working for the past 10 minutes fine? I wonder if there is some compatibility issue.

Actually there maybe is, as that one rule was created under the new iptables yet the other rules are under the -legacy version).

**Comment by CallMeFoxie** [comment]
So it is a duplicity of #71305 ... should we track this here as this is kubelet and not kube-proxy or should we track it together?

**Comment by neolit123** [comment]
even if it's the same problem kube-proxy and kubelet are maintained by different groups.
so i'd say keep this open for now.

/sig node

**Comment by neolit123** [comment]
but actually....iptables problems fall under sig-network so just mention your issue in a comment in https://github.com/kubernetes/kubernetes/issues/71305

thanks
/close
