### ISSUE TITLE
PresistentVolumeClaims for batch/jobs

### ISSUE THREAD

**Issue by Thoro** [kubernetes/kubernetes#76435]
**What would you like to be added**:

Please add VolumeClaimTemplates to batch/jobs.

**Why is this needed**:

Currently the only way to dynamically provision new volumes is via the statefulset.

In my specific case, I have a zfs provisioner, that can create clones based of specified volumes. I would like to create a new clone for each job that runs based on the specified volume. The volume updates constantly, but should be frozen for the task.

**Comment by Thoro** [comment]
@kubernetes/sig-storage-feature-requests

I guess?

**Comment by jsafrane** [comment]
@kubernetes/sig-apps-feature-requests is the right forum.

From storage perspective, I think it should work, however, it looks a bit weird to me and very specific to one use case.

**Comment by draveness** [comment]
Is there any other use cases for this feature? I dug around the historical issues and didn't find any similar requests.

**Comment by jingxu97** [comment]
I am thinking whether it makes sense to have a separate API (maybe CRD) for VolumeClaimTemplates which can be referenced in different places. So user can use template reference instead of embedding it in different objects each time it is needed.

**Comment by Thoro** [comment]
Actually I really like that idea, maybe this would be the better approach.

Possibly there could also be a mutator / controller to control how the pvc are distributed on the pods (i.e. deployment with pvc templates), and how they are named. 

Currently the only way to have dynamic volumes is with a statefulset. But sometimes you want them in a daemonset or deployment

**Comment by draveness** [comment]
> I am thinking whether it makes sense to have a separate API (maybe CRD) for VolumeClaimTemplates which can be referenced in different places. So user can use template reference instead of embedding it in different objects each time it is needed.

That sounds like a good idea. The current `volumeClaimTemplates` has some issues, ex: it doesn't update the underlying PVC resources correctly https://github.com/kubernetes/kubernetes/pull/75051. It will be easier to manage the resources if we have a separate API and controller for that.

But do we need to use the `volumeClaimTemplates` in other resources except for StatefulSet? `volumeClaimTemplates` in the stateful set create PVCs and bind it to specific pod through sequence number. However, deployments and replica sets don't have such thing, the pods they created are transient and stateless, and when they were deleted, the corresponding controller would create new pods with a different name.

If the sig storage team thinks it's a useful feature and kubernetes needs to have this (not through CRD), I'm happy to open KEP and start working on that. :)

**Comment by kow3ns** [comment]
Have you considered implementing this as an extension. We might be willing to sponsor it as a SIG Apps subproject. Please consider submitting a KEP against SIG Apps.

**Comment by huide9** [comment]
looking for the dynamic provisioning function for batch/job. to enable `columeClaimTemplate` will be very helpful for each job to own a stable storage during the runtime. 
Consider at the runtime: each job may need to mount the nfs as source/destination for the predefined code/data. 

Can this issue be reopened?
