### ISSUE TITLE
Use Go's context package in place of CloseNotifier

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#76469]
**What would you like to be added**:
From server.go:
```
// Deprecated: the CloseNotifier interface predates Go's context package.
// New code should use Request.Context instead.
```
We should use context in place of:
```
	cn, ok := w.(http.CloseNotifier)
```
**Why is this needed**:
CloseNotifier is deprecated.

**Comment by danielqsj** [comment]
I'd like to have a try.
/assign

**Comment by neolit123** [comment]
/sig api-machinery
as per:
https://github.com/kubernetes/kubernetes/search?q=CloseNotifier&unscoped_q=CloseNotifier

**Comment by roycaihw** [comment]
cc @cheftako

**Comment by liggitt** [comment]
thanks for the PR, but I don't think we're ready to drop this yet, based on existing use by other components. See comment at https://github.com/kubernetes/kubernetes/pull/76648#discussion_r275795527

/close
