### ISSUE TITLE
Generate kubeconfig as well as tokens for service accounts

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#7647]
Mentioned in todays community meeting by @smarterclayton during @liggitt ServiceAccount demo.

Should something generate a kubeconfig file with the token in it, for each service account?
This would allow me to simplify the code in cluster/saltbase/salt/kube-addons/kube-addons.sh which creates secrets to just create service accounts.

Would this be the TokenController, or some new controller?

Would the kubeconfig go into a separate secret, or the same secret as the bare token?
- if same, then is ServiceAccountSecret still the right secret type?
- if different, is it annoying to have so many volumes?
- if same, limited control over location of each?

Given that there is now a "file format" for tokens, should we just extend the kubeconfig format to support a `tokenFilename` field?  If we did that, is there any need to put the kubeconfig in a secret, since it just references secrets?

What should be the canonical location where the automounter puts a kubeconfig file, so that clients don't have to specify a flag?

**Comment by roberthbailey** [comment]
One advantage of a kubeconfig file is that we can bundle more than just an access token. We could instead put client certs and we could put the root CA cert as well so that clients can verify the master when connecting to the secure endpoint.

**Comment by smarterclayton** [comment]
Yeah, we want to sign and distribute serving certs for tls components, but the kubecknfig doesn't quite satisfy.  But CA and clients and credentials should be our preferred vector.

But, and this is a big but, it's a pain for a normal program to extract values from that.  So I think targeting both (two values in the secret data) is valuable.

**Comment by roberthbailey** [comment]
I agree that for non-infrastructure components the data bundled inside a kubeconfig isn't really useful.

**Comment by smarterclayton** [comment]
It would be trivial to extend the secret generator to add two entries.  I think the power of this approach is that incremental addition.

**Comment by jimmidyson** [comment]
Having separate secret entries for token, CA cert, etc rather than a kubeconfig file would be easier to use without having to create kubeconfig parsers in multiple languages, etc.

**Comment by karlkfi** [comment]
Any chance of this happening? 
It's kind of annoying to have to generate a kubeconfig in pods that want to use kubectl.

**Comment by liggitt** [comment]
There are no plans to do this. kubectl can be used in a pod without needing to generate a kubeconfig file, and it automatically uses the service ip/port and serviceaccount token, and the current namespace
