### ISSUE TITLE
Kubelet has an exception log "couldn't propagate object cache: timed out waiting for the condition"

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/kubernetes#76480]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Log information: https://github.com/xichengliudui/public-repo/blob/master/logs.md

Ref: https://github.com/kubernetes/kubernetes/pull/75260

**Comment by xichengliudui** [comment]
here.

**Comment by liggitt** [comment]
Your logs indicate you are running 1.12.3. 

This was resolved in 1.12.7 in https://github.com/kubernetes/kubernetes/pull/74755

**Comment by xichengliudui** [comment]
YES, Thank you very much.
