### ISSUE TITLE
Remove privileged: true from pull-kubernetes-kubemark-e2e-gce-big

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#76484]
ref https://github.com/kubernetes/test-infra/issues/12172

Adding this back for now, but it is not clear why this job needs to run in an insecure container

@kubernetes/sig-scalability-bugs

**Comment by danielqsj** [comment]
hi @fejta , `pull-kubernetes-kubemark-e2e-gce-big` failed for a long time. Is this issue related ? 
 https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kubemark-e2e-gce-big

**Comment by cwdsuzhou** [comment]
> hi @fejta , `pull-kubernetes-kubemark-e2e-gce-big` failed for a long time. Is this issue related ?
> https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kubemark-e2e-gce-big

I have the  same issue
