### ISSUE TITLE
Kubernetes wildfly pod deployment fails to start

### ISSUE THREAD

**Issue by 1090223** [kubernetes/kubernetes#76493]
I have a kubernetes wildflypod and kubernetes postgres pod. I have specified env variables so that they can talk to each other but this is not working. But when I am linking these containers in docker it is working fine. What could be possibly wrong?

**Comment by neolit123** [comment]
/triage needs-information

please provide more details about your setup OS, kubernetes version, cluster setup, other conditions.
also it might be a better idea to ask on stackoverflow or reddit.

**Comment by 1090223** [comment]
OS is CentOS 7.5, Kubernetes major version:1 and minor:12 , cluster is setup on CentOS 7.5 servers. One is master  and other is worker node. Please tell a way by which i can troubleshoot this issue.

**Comment by 1090223** [comment]
@neolit123 Any suggestion from your side?

**Comment by neolit123** [comment]
i think you will get better feedback in community forums like stackoverflow or reddit.
i haven't seen much talks about wildfly in k8s, which leads me to believe that the k8s maintainers and people who monitor the issue tracker cannot answer your question.

i'm going to have to close this ticket, but feel free to try the above recommendation - e.g.:
https://stackoverflow.com/search?q=%5Bkubernetes%5D+wildfly

thanks
/close
