### ISSUE TITLE
Evaluate and eliminate use of google.golang.org/api/compute/v0.alpha because it's 20M

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#76504]
One of the top offenders that contribute to the size of our binaries is the v0.alpha API used in the GCE provider
```
20M    ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.alpha.a
```

Can we please check if the alpha features have already gotten promoted to beta? and if we really need the alpha features?

Steps to find sizes of built packages.
```
go build -a -v ./cmd/hyperkube 2>&1 | grep vendor | grep -v vendor/k8s.io > built.txt
cat built.txt | xargs -L 1 -I {} go build -o "{}.a" {}
find . -type f -name *.a -exec du -h {} \; | sort -h | grep -v vendor/k8s.io
```

**Comment by dims** [comment]
/sig gcp
cc @jagosan @cheftako @liggitt

**Comment by liggitt** [comment]
Looks like most of the use is network related. Would be good to evaluate if the APIs we're using have graduated to beta and we can stop calling the alpha APIs

fyi @bowei @MrHohn

**Comment by MrHohn** [comment]
It may be possible that the existing alpha APIs have graduated to beta or GA, though wouldn't this come back once we have another alpha API integrated in future?

**Comment by dims** [comment]
@MrHohn we should not be adding any more "new" stuff to in-tree cloud providers right? :)

cc @andrewsykim

**Comment by andrewsykim** [comment]
Yes, as per https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider#deprecation-notice we shouldn't anticipate cloud providers in-tree to add new features/integrations. Should only be incremental changes to fix bugs.

**Comment by MrHohn** [comment]
Right, thanks for the info. So it feels like the real fix here is https://github.com/kubernetes/enhancements/issues/668, after which we can remove all of `google.golang.org/api/compute` from k/k? Or is this causing immediate pain that we need to resolve sooner?

**Comment by andrewsykim** [comment]
If `google.golang.org/api/compute/v0.alpha` is needed for existing features in the GCE provider then I don't think it would be reasonable to remove it until the out-of-tree provider is supported like you mentioned. I think the ask here is if the `google.golang.org/api/compute/v0.alpha` dependency can be removed if we are importing v1 versions of the SDK. I haven't look through the GCE compute SDK in a while so not sure if the `v0.alpha` import is required or can be replaced with beta or v1 versions.

**Comment by andrewsykim** [comment]
cc @cheftako

**Comment by andrewsykim** [comment]
Seems like we create separate clients for alpha/beta versions of the client https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L104-L105 can we go through usage and see if it's feasible to remove?

**Comment by liggitt** [comment]
if it's a lot of work to tease out and remove, I'll settle for lumping it in with the rest of the "move out of tree" work, but it seemed worth checking, given it's the number 2 package in size

**Comment by andrewsykim** [comment]
> if it's a lot of work to tease out and remove, I'll settle for lumping it in with the rest of the "move out of tree" work, but it seemed worth checking, given it's the number 2 package in size

After doing a quick scan of the provider, it seems like it would be quite a bit of work to do this and would actually break compatibility if I'm not mistaken.

**Comment by MrHohn** [comment]
@andrewsykim Thanks for checking that. It may not break compatibility, though will require touching many places for switching this and need to make adjustment to the auto-generating wrapper we built sometimes before.. So need more testing to keep this safe.

Also did another check on the vendor --- it seems like `github.com/GoogleCloudPlatform/k8s-cloud-provider` itself also imports this Alpha API.  So making change to k/k might not be sufficient to eliminate this?
```
$ git grep -in "google.golang.org/api/compute/v0.alpha" vendor/
vendor/BUILD:448:        "//vendor/google.golang.org/api/compute/v0.alpha:all-srcs",
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/BUILD:23:        "//vendor/google.golang.org/api/compute/v0.alpha:go_default_library",
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go:34:   alpha "google.golang.org/api/compute/v0.alpha"
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/BUILD:16:        "//vendor/google.golang.org/api/compute/v0.alpha:go_default_library",
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go:22:     alpha "google.golang.org/api/compute/v0.alpha"
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/method.go:66:   case "google.golang.org/api/compute/v0.alpha":
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/BUILD:13:        "//vendor/google.golang.org/api/compute/v0.alpha:go_default_library",
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/mock.go:36:     alpha "google.golang.org/api/compute/v0.alpha"
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/op.go:25:    alpha "google.golang.org/api/compute/v0.alpha"
vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go:25:       alpha "google.golang.org/api/compute/v0.alpha"
...
```

**Comment by bowei** [comment]
Even though this is a big chunk of code, if we are support features calling the alpha API, then it has to stay in some form or another.
Until we build cloud specific libraries, as Go has no dynamic linking, I don't think we can do much about the code size.
What is the target binary size we are trying to go to and why?

**Comment by liggitt** [comment]
> if we are support features calling the alpha API, then it has to stay in some form or another

No disagreement, just thought it was worth seeing if they had graduated to the beta lib and we could drop use of the alpha package, given the size impact

**Comment by bowei** [comment]
Support for alpha features is an ongoing thing (they are always being added). Even if we remove them today, they will be required almost immediately tomorrow. It will cause unnecessary code churn at this point.

**Comment by dims** [comment]
@bowei aren't we supposed to move to external cloud providers and stop adding stuff in the in-tree one?

**Comment by bowei** [comment]
@dims -- yes that would be great, but isn't that effort not yet complete? (please correct me if I'm wrong)

**Comment by andrewsykim** [comment]
> @dims -- yes that would be great, but isn't that effort not yet complete? (please correct me if I'm wrong)

Yeah the effort is still on-going. The out-of-tree mechanism has been supported for a while but providers need to implement and drive adoption. Ideally if you want a new feature, add it out-of-tree and get users using the out-of-tree provider. IMO the more features we allow in-tree, the harder we make migration in the future. We realize this is a hard ask for users with existing clusters, we have a KEP open to address this for v1.15 https://github.com/kubernetes/enhancements/pull/979.

**Comment by dims** [comment]
Here's an experiment at removing the Alpha code from k/k https://github.com/kubernetes/kubernetes/pull/77014

as @MrHohn said (and i can confirm) we need to remove code from `github.com/GoogleCloudPlatform/k8s-cloud-provider` as well.
https://github.com/kubernetes/kubernetes/pull/77014#issuecomment-486246793

I think it's worth the effort to remove `v0.alpha` from both the repos. WDYT? ( cc @thockin @bgrant0607 )

**Comment by warmchang** [comment]
```
...
4.0M    ./k8s.io/kubernetes/vendor/github.com/vmware/govmomi/object.a
4.3M    ./k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/methods.a
6.3M    ./k8s.io/kubernetes/vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud.a
8.5M    ./k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-03-01/compute.a
14M     ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v1.a
15M     ./k8s.io/kubernetes/vendor/github.com/xanzy/go-cloudstack/cloudstack.a
16M     ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.beta.a
19M     ./k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-07-01/network.a
20M     ./k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/ec2.a
20M     ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.alpha.a
28M     ./k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/types.a
```

Check all the generated ".a" files (by size sort):

1. Large files are almost always related to cloud provider library.
2. Some package include diffrent version (alpha/beta/GA).
    - 14M     ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v1.a
    - 16M     ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.beta.a
    - 20M     ./k8s.io/kubernetes/vendor/google.golang.org/api/compute/v0.alpha.a
