### ISSUE TITLE
Have `NewWatcher` of plugin watcher return an interface instead of a struct

### ISSUE THREAD

**Issue by taragu** [kubernetes/kubernetes#76539]
**What would you like to be added**:
After PR #73891  is merged, refactor `pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go` so that `NewWatcher(...)` should return a Watcher interface instead of a struct.

**Why is this needed**:
This will make testing easier as fake implementation can be used easily.

FYI @saad-ali 
/assign @taragu

**Comment by tedyu** [comment]
@taragu 
Here is how the returned Watcher is used:
```
	// desiredStateOfWorldPopulator (the plugin watcher) runs an asynchronous
	// periodic loop to populate the desiredStateOfWorld.
	desiredStateOfWorldPopulator *pluginwatcher.Watcher
```
where desiredStateOfWorld is of particular importance.
If the Watcher interface you mentioned already exists, can you point me to it ?

Thanks

**Comment by taragu** [comment]
@tedyu the plugin watcher (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go#L35) is a struct instead of interface. We'd like to change this to an interface instead. Does this answer your question?
