### ISSUE TITLE
GKE support for node-pools with local SSD boot disk

### ISSUE THREAD

**Issue by Monnoroch** [kubernetes/kubernetes#76553]
**What would you like to be added**:

Support Local SSDs as boot disks in GCE/GKE.

**Why is this needed**:

Persistent disks do not make sense for preemptible nodes. These nodes regularly get deleted along with their persistent disks thus making these disks effectively non-persistent. Local SSDs fit this use case perfectly, as they are already not persistent and are faster and cheaper because of the lack of network overhead.

As a more far-fetched feature request, it would be nice to also support local HDDs for nodes that don't require low I/O latency and have local HDDs as a feature in general.

Related work: #36499 (the reason I'm posting the issue here).

**Comment by BenTheElder** [comment]
/area platform/gke
cc @msau42

**Comment by msau42** [comment]
Thanks for raising the issue. The GCE instance itself is limited to PD as a boot disk so we wouldn't be able to replace the boot disk. However it may be possible to use a local ssd as the kubelets root partition. This is on our backlog of feature requests.

In the meantime, does PD ssd as a boot disk give the performance you need?

/assign

**Comment by Monnoroch** [comment]
@msau42 thank you for your reply. My original issue is not quite about SSD vs HDD. It's about local vs persistent. My point here is that it doesn't even make sense to have **persistent** disks for **ephemeral** VMs.

**Comment by msau42** [comment]
There is a feature request open for this on the public GKE issue tracker: https://issuetracker.google.com/issues/35904742.

Closing this one out as this is outside of the k/k project.
/close
