### ISSUE TITLE
Infinite ImagePullBackOff CronJob results in resource leak

### ISSUE THREAD

**Issue by DarrienG** [kubernetes/kubernetes#76570]
**What happened**:
A CronJob without a ConcurrencyPolicy or history limit that uses an image that doesn't exist will slowly consume almost all cluster resources. In our cluster we started hitting the pod limit on all of our nodes, and began losing our ability to schedule new pods.

**What you expected to happen**:
Even without a ConcurrencyPolicy, CronJob should probably have the same behavior as most of the other pod schedulers. If I try to start a deployment with X replicas and I get ImagePullBackOff on one of the containers in a pod, the deployment won't keep trying to schedule more pods on different nodes until it consumes all cluster resources.

This is especially bad with CronJob, because unlike Deployment where an upper limit for horizontal scalability has to be set, CronJob with no history limit and ConcurrencyPolicy will slowly consume all resources on a cluster.

While this is up for debate, I would personally say when a scheduled Job has the ImagePullBackOff error, it shouldn't try to keep scheduling new pods. It should probably kill the pod trying to pull an image and make a new one, or wait for the pod to successfully pull the image.

Worst case scenario it will consume all cluster resources, best case scenario there is a thundering herd of CronJobs all rushing to completion when the image becomes available.

**How to reproduce it (as minimally and precisely as possible)**:
```yml
apiVersion: batch/v1beta1
kind: CronJob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: darrienglasser.com/busybox:does-not-exist
```
Deploy the above and wait. Your cluster will collapse over time.

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
On prem. A number of high powered nodes with Xeons. (256Gi+ memory and the latest Xeon Gold processors)

- OS (e.g: `cat /etc/os-release`):

```
core@k8s-node [23:36:33]~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.4.0
VERSION_ID=1911.4.0
BUILD_ID=2018-11-26-1924
PRETTY_NAME="Container Linux by CoreOS 1911.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):

```
Linux k8s-node 4.14.81-coreos #1 SMP Mon Nov 26 18:51:57 UTC 2018 x86_64 Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz GenuineIntel GNU/Linux
```

**Comment by DarrienG** [comment]
sig/scheduling

**Comment by DarrienG** [comment]
This hit us again yesterday on one of our clusters. We thought we cleaned up all the crons, bt it wasn't the case. It's such an easy and innocuous error to get.

**Comment by soltysh** [comment]
I think https://github.com/kubernetes/kubernetes/issues/76370 is related to the same problem.

**Comment by DarrienG** [comment]
/remove-lifecycle-stale

This is assigned. I'm surprised the bot decided to mark it as stale.

**Comment by DarrienG** [comment]
/remove-lifecycle stale

I don't work on Kubernetes anymore, but this is still an issue.

**Comment by alanorwick** [comment]
Hello! I'm a CS student at UT Austin. For a class project we're tackling some open source issues. I'm going to try to see if I can make progress on this. /assign

**Comment by ryanarifin134** [comment]
Hello! What are your thoughts on adding a field to the cronjob spec to limit the number of concurrent jobs spawned by the cronjob? For example, the spec could be `concurrentJobsAllowed` with a default of say, 100. This would provide a general failsafe to situations like this where you would not want one cronjob to accidentally spawn an unexpected number of jobs. One could use this field to specify to what degree of concurrency one cronjob should allow, thus preventing situations like this where users end up shooting themselves in the foot.

**Comment by DarrienG** [comment]
It isn't a bad idea, but brings up a few other questions:

* What happens to cronjobs that are spawned after the limit is exceeded?
* Does it count as a missed schedule if it is unable to be spawned?
* What happens if this parameter is set, but concurrencyPolicy is set to `forbid`?

Arguably something like this should have a default of infinity to not break previous workflows.

In theory a fix to this PR should work selectively with imagePullBackOff which will not break anybody else's workflow. I would argue a `concurrentJobsAllowed` parameter is targeting a problem orthogonal to this one, but am open to hearing other opinions.

**Comment by ryanarifin134** [comment]
1. If the limit is exceeded, we would prevent new jobs to be spawned by the cronjob.
2. Similar to if a job is prevented from being spawned if `ConcurrencyPolicy` is set to `Forbid`, a job would not be considered as a missed schedule if it is unable to be spawned.
3. The thought was to have this new spec field work in conjunction with the ConcurrencyPolicy. In other words, this field would only be valid if ConcurrencyPolicy is set to `Allow` (this check would have to be something we add).

We initially were thinking about selectively targeting pods with the `ImagePullBackOff` and `ErrImagePull` statuses, but how would you selectively deal with these statuses? Our first thought was to just delete them, but that would lead to a couple of issues. One is that that might delete pods that temporarily have this status and are not stuck in the infinite loop. The other is that deleting them automatically would remove visibility for developers to figure out what went wrong with their pod. We thought the `ConcurrentJobsAllowed` would provide a solution that avoided these problems. What are your thoughts on that?

**Comment by hermanbanken** [comment]
This hit us too. This being a new development cluster and not production, monitoring was not fully configured. Eventually we had 10.000 pods (which spinned up 100+ extra nodes) from one CronJob before we noticed.

**Comment by DarrienG** [comment]
@ryanarifin134 I guess I'm still a little iffy on `concurrentJobsAllowed` because I don't know if there's a use case for it.

Likewise: A default is required to be set to `concurrentJobsAllowed` for this bug to be fixed, which could break workflows that assume unbounded growth for a `concurrencyPolicy: Allow`

I'm still on board with if an ImagePullError happens either:

* Don't start another job

* Replace the old job with a new job

I'm a bit partial to the former, because if your cluster has reporting set up with say `kube-state-metrics`, it's really easy to see when a CronJob isn't scheduled after a set period of time.

I could see arguments for the latter though where there is a network blip and auto-recover would be preferred by replacing it by default.

Mind you - I do *not* work on Kubernetes anymore, so this is just my opinion. It might be worth asking a few folks who work full time on Kubernetes what they think.

**Comment by DarrienG** [comment]
/remove-lifecycle stale

But I also don't work in Kubernetes anymore, so I don't care very much.

**Comment by flokli** [comment]
This still seems to be an issue.

/remove-lifecycle rotten
/reopen

**Comment by rltvty** [comment]
This is still an issue. We had a cronJob with an invalid image, that spooled up 100 containers in our cluster.

**Comment by felschr** [comment]
Hitting this issue, too. It maxes out our nodes & causes any new/updated workload to be unschedulable.

**Comment by DarrienG** [comment]
Reopened!

**Comment by felschr** [comment]
It's still closed.

**Comment by DarrienG** [comment]
Ah apologies then. The GitHub app acts like you can reopen even if you can't. Looks like I don't have permissions then.

**Comment by felschr** [comment]
@DarrienG  can you try writing "/reopen" in here like @flokli tried before?
Looks like that should be possible for authors, and the bot would reopen it for you.

**Comment by ajendrex** [comment]
hello,

I think this problem is serious as it can consume the resources fast, depending on the cronjob frequency. Since it still has no direct solution; what would be the way around?

**Comment by SergeyKanzhelev** [comment]
cc: @alculquicondor 


> Since it still has no direct solution; what would be the way around?

A workaround as mentioned may be setting [`concurrencyPolicy`](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy) from `Allow` to `Replace` in order to ensure that whenever a new job it's scheduled it will delete the last job running. Would this work?

**Comment by alculquicondor** [comment]
Another workaround is to use `activeDeadlineSeconds` in the job Template as suggested here: https://github.com/kubernetes/kubernetes/issues/53331#issuecomment-358274195

@soltysh are you aware of any new KEPs that are looking into tackling this?

**Comment by DarrienG** [comment]
I haven't worked on K8s in years now, but I still get emails from it sometimes (thanks stale issue bot and other commenters). As the original filer I can tell you the issue is that this bug is very easy to hit. The problem being that the default configuration of a yaml file without extra parameters can easily take down a whole cluster. 

These two fields:
* `concurrencyPolicy`
* `activeDeadlineSeconds`

Will most certainly fix the problem, but especially when you are in an org where lots of folks are making new yaml files, modifying old ones, or have an unstable docker registry and old images disappear over time, you get issues like this.

We had a template for folks in the org to follow at Arista, but most folks did not use it. Baking in sane defaults is really important, otherwise it is very easy for folks to accidentally take down a K8s cluster, making the life of the cluster maintainers a mess.

At the very least a configuration parameter for the K8s cluster itself that could fix this would have been nice for me when  I worked on K8s. We want to actively remove footguns if we can.

At Meta we don't even use K8s nowadays though (well, more or less) and even so it is not my job to care about it, but this issue still gave me a lot of pain a few years ago and I would hate to see it close because there is a workaround.

Anyways I'll remove lifecycle stale for the last time to give members a chance to review, but it will probably be my last response here unless I have to (god willing) work on K8s again.

/remove-lifecycle stale

**Comment by alculquicondor** [comment]
Unfortunately, changing defaults is not backwards-compatible.

One option you have is to set these fields in your clusters via webhooks.

**Comment by DarrienG** [comment]
Ah that's a shame. I remember hoping originally spinning off endless jobs that do not have a valid image would be something that could be special cased whether or not those policies were set. It's unfortunate that's not the case.

I appreciate the heads up about webhooks, thanks

**Comment by flokli** [comment]
Changing defaults has been done in previous occasions as well. Things need to be deprecated/communicated properly, but it's not impossible (see [this example](https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0)

This GitHub issue has enough watchers / people affected, and it's causing real problems, which should be a strong argument for actually fixing it.

There's very few reports about how this would break existing workloads.

@alculquicondor what's the risk you see in adressing that footgun?

**Comment by benzvan** [comment]
I ran into a mildly related issue recently.
* A pod was in ImagePullBackOff due to a misconfigured image path
* We corrected the image path via a helm deploy
* the failed pod caused the updated cronjob to fail due to `concurrencyPolicy: forbid`

**Comment by alculquicondor** [comment]
Please see https://github.com/kubernetes/kubernetes/issues/76570#issuecomment-1230523060 and https://github.com/kubernetes/kubernetes/issues/76570#issuecomment-1330701444
