### ISSUE TITLE
metrics-server start failed. status is CrashLoopBackOff

### ISSUE THREAD

**Issue by chicago7** [kubernetes/kubernetes#76575]
**What happened**:
I0411 03:09:30.784560 1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0411 03:09:30.784637 1 heapster.go:72] Metrics Server version v0.2.1
I0411 03:09:30.784846 1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version
I0411 03:09:30.784862 1 configs.go:62] Using kubelet port 10255
I0411 03:09:30.785670 1 heapster.go:128] Starting with Metric Sink
I0411 03:09:31.372204 1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0411 03:09:31.904501 1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file

I try to use the below link that fix the issue, but didn't work 

https://github.com/Azure/acs-engine/issues/2421 
https://github.com/Azure/acs-engine/issues/2665
https://github.com/Azure/acs-engine/pull/2264

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
aks engine v0.34.0
k8s01.json
{
"apiVersion": "vlabs",
"location": "chinaeast2",
"properties": {
"orchestratorProfile": {
"orchestratorType": "Kubernetes",
"orchestratorVersion": "1.14.1",
"kubernetesConfig": {
"clusterSubnet": "10.244.0.0/16",
"networkPlugin": "kubenet",
"networkPolicy": "calico",
"enableRbac": false,
"addons": [
{
"name": "tiller",
"enabled": false
},
{
"name": "kubernetes-dashboard",
"enabled": false
},
{
"name": "blobfuse-flexvolume",
"enabled": false
},
{
"name": "keyvault-flexvolume",
"enabled": false
},
{
 "name": "rescheduler",
            "enabled": true
}
],
"apiServerConfig": {
"--enable-admission-plugins": "DenyEscalatingExec,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration"
}
}
},
"masterProfile": {
"count": 1,
"dnsPrefix": "test03",
"vmSize": "Standard_A2m_v2",
"firstConsecutiveStaticIP": "172.16.0.200",
"vnetSubnetId": "",
"storageProfile": "ManagedDisks"
},
"agentPoolProfiles": [
{
"availabilityProfile": "AvailabilitySet",
"name": "test02",
"count": 1,
"vmSize": "Standard_A2m_v2",
"vnetSubnetId": "",
"storageProfile": "ManagedDisks",
"osType": "Linux"
}
],
"linuxProfile": {
"adminUsername": "test02",
"ssh": {
"publicKeys": [
{
"keyData": ""
}
]
}
},
"servicePrincipalProfile": {
"clientId": "",
"secret": "*******"
}
}
}
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration: Azure China
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04-LTS
- Kernel (e.g. `uname -a`):4.15.0-1025-azure #26~16.04.1-Ubuntu SMP Tue Sep 25 11:09:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by Duchongming** [comment]
查看一下证书

**Comment by andyzhangx** [comment]
I tried by `aks engine v0.34.0` on chinaeast2, metric server works well:
```
kubectl logs metrics-server-74d64b844c-gnjzg -n kube-system
I0417 02:28:34.825300       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0417 02:28:34.825344       1 heapster.go:72] Metrics Server version v0.2.1
I0417 02:28:34.825561       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version
I0417 02:28:34.825576       1 configs.go:62] Using kubelet port 10255
I0417 02:28:34.826458       1 heapster.go:128] Starting with Metric Sink
I0417 02:28:35.079889       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0417 02:28:35.218543       1 heapster.go:101] Starting Heapster API server...
[restful] 2019/04/17 02:28:35 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
[restful] 2019/04/17 02:28:35 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
I0417 02:28:35.219484       1 serve.go:85] Serving securely on 0.0.0.0:443
```

@chicago7  the only difference is I set network plugin and policy as following:
```
    "networkPlugin": {
      "value": "azure"
    },
    "networkPolicy": {
      "value": ""
    },
```

I am not sure `calico` works on azure china now.

**Comment by chicago7** [comment]
@ andyzhangx thanks for your reply, i will try it

**Comment by chicago7** [comment]
@andyzhangx  i change the network plugin and policy value. but the issue still happened. 

NAME                                            READY     STATUS             RESTARTS   AGE
azure-cni-networkmonitor-2272p                  1/1       Running            0          3m
azure-cni-networkmonitor-4bt9n                  1/1       Running            0          3m
azure-ip-masq-agent-ftwzn                       1/1       Running            0          3m
azure-ip-masq-agent-kktnd                       1/1       Running            0          3m
coredns-5dc99c87cb-r8vw5                        1/1       Running            0          3m
kube-addon-manager-k8s-master-15989644-0        1/1       Running            0          2m
kube-apiserver-k8s-master-15989644-0            1/1       Running            0          2m
kube-controller-manager-k8s-master-15989644-0   1/1       Running            0          2m
kube-proxy-mtmws                                1/1       Running            0          3m
kube-proxy-nxxfr                                1/1       Running            0          3m
kube-scheduler-k8s-master-15989644-0            1/1       Running            0          2m
metrics-server-74d64b844c-l4tkc                 0/1       CrashLoopBackOff   4          3m
rescheduler-7b7b488f66-ffhr6                    1/1       Running            0          3m

I0417 09:36:34.973692       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0417 09:36:34.973761       1 heapster.go:72] Metrics Server version v0.2.1
I0417 09:36:34.973897       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version 
I0417 09:36:34.973905       1 configs.go:62] Using kubelet port 10255
I0417 09:36:34.974624       1 heapster.go:128] Starting with Metric Sink
I0417 09:36:35.949188       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0417 09:36:36.253041       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file

**Comment by AhmedMoAli** [comment]
Hello,

Any feedback about this ticket?

**Comment by chicago7** [comment]
@andyzhangx Could you help to fix the problem ? thanks

**Comment by andyzhangx** [comment]
@chicago7 I cannot repro on chinaeast2, is your config works on global Azure?

**Comment by chicago7** [comment]
@andyzhangx Thanks for your reply. Currently, The issue can repro on global azure and China Azure.

**Comment by andyzhangx** [comment]
@chicago7 can you paste your api-server config by: `cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep args`

My working cluster has following parameters
```
"--requestheader-client-ca-file=/etc/kubernetes/certs/proxy-ca.crt"
```
and that crt file is valid:
```
openssl x509 -in  /etc/kubernetes/certs/proxy-ca.crt -text
```

**Comment by chicago7** [comment]
@andyzhangx  output as following: 

root@k8s-master-15989644-0:/etc/kubernetes/manifests# cat ./kube-apiserver.yaml |grep args
      args: ["--advertise-address=172.16.0.200", "--allow-privileged=true", "--anonymous-auth=false", "--audit-log-maxage=30", "--audit-log-maxbackup=10", "--audit-log-maxsize=100", "--audit-log-path=/var/log/kubeaudit/audit.log", "--audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml", "--bind-address=0.0.0.0", "--client-ca-file=/etc/kubernetes/certs/ca.crt", "--cloud-config=/etc/kubernetes/azure.json", "--cloud-provider=azure", "--enable-admission-plugins=DenyEscalatingExec,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration", "--enable-bootstrap-token-auth=true", "--etcd-cafile=/etc/kubernetes/certs/ca.crt", "--etcd-certfile=/etc/kubernetes/certs/etcdclient.crt", "--etcd-keyfile=/etc/kubernetes/certs/etcdclient.key", "--etcd-servers=https://127.0.0.1:2379", "--insecure-port=8080", "--kubelet-client-certificate=/etc/kubernetes/certs/client.crt", "--kubelet-client-key=/etc/kubernetes/certs/client.key", "--profiling=false", "--secure-port=443", "--service-account-key-file=/etc/kubernetes/certs/apiserver.key", "--service-account-lookup=true", "--service-cluster-ip-range=10.0.0.0/16", "--storage-backend=etcd3", "--tls-cert-file=/etc/kubernetes/certs/apiserver.crt", "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", "--tls-private-key-file=/etc/kubernetes/certs/apiserver.key", "--v=4"]
root@k8s-master-15989644-0:/etc/kubernetes/manifests# cat ./kube-apiserver.yaml |grep request
root@k8s-master-15989644-0:/etc/kubernetes/manifests# 

and then , try to change enableAggregatedAPIs parameter from false to true in azuredeploy.json and azuredeploy.parameters.json. the issue still happened. execute the command[cat ./kube-apiserver.yaml |grep request], output is empty.

**Comment by andyzhangx** [comment]
@chicago7 You need to specify `enableAggregatedAPIs` as true in cluster definition file under `kubernetesConfig`, and then use aks-engine to regenerate the template, change `enableAggregatedAPIs` in generated templates won't work.
https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#kubernetesconfig

And if set `enableAggregatedAPIs` as true, api-server will have following parameter:
`--requestheader-client-ca-file=/etc/kubernetes/certs/proxy-ca.crt`

https://github.com/Azure/aks-engine/blob/05518ee90f77b5a8dc072f38d5a179e84f81db22/pkg/api/defaults-apiserver.go#L61-L62

**Comment by chicago7** [comment]
@andyzhangx  thanks for your reply, i will test it later.

**Comment by chicago7** [comment]
@andyzhangx  it works. thanks.   I set enableAggregatedAPIs and enableRbac as following:

"enableAggregatedAPIs": true,
"enableRbac": true,

**Comment by andyzhangx** [comment]
thanks for confirm
/close

**Comment by andyzhangx** [comment]
cc @jackfrancis it looks like `enableAggregatedAPIs` value is false in aks-engine 0.34.0, that would cause metrics-server crash.

**Comment by jackfrancis** [comment]
Definitely can't repro this issue, `enableAggregatedAPIs` has been default true for clusters >= k8s 1.9 for a long time. Validated on `v0.34.0`:

```
        "enableRbac": true,
        "enableAggregatedAPIs": true,
```

The above is from the resultant apimodel.json generated from a default api model input.

Additionally, we test basics metric-server operation with all E2E tests, so if it was consistently crashing we'd notice.

**Comment by chicago7** [comment]
@jackfrancis @andyzhangx thanks for your help and continuous follow-up the issue.  i can repro the issue in aks-engine 0.34.1/0.34.0/0.33.6 and k8s version is 1.14.1/1.14.0
