### ISSUE TITLE
API call latency regression

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#76579]
There is yet another regression for API-call latencies for 5k-node test:
https://testgrid.k8s.io/sig-scalability-gce#gce-scale-performance

The last 3 runs of load test failed there.

I didn't yet have time to look into it deeper, but (especially the last run) seems suspicious, due to this one:
```
Resource:nodes Subresource: Verb:POST Scope:cluster Latency:{Perc50:4.749ms Perc90:1.807403s Perc99:1.807403s} Count:16}
```

It seems some nodes were added during the test, which isn't expected.

@kubernetes/sig-scalability-bugs

**Comment by oxddr** [comment]
I'll have a look.

**Comment by wojtek-t** [comment]
I took a quick look into this one and looked into PRs merged between runs when it started failing:
https://github.com/kubernetes/kubernetes/compare/f873d2a05...aa7406460
But I didn't find anything really suspicious.

So I looked a a bit into graphs and my current hypothesis is that the regression actually happened before. This is based on looking into some graphs in perf-dash:

![Screenshot from 2019-04-16 14-26-57](https://user-images.githubusercontent.com/10743879/56209444-dc888f80-6053-11e9-8a09-9f04743dbf59.png)
![Screenshot from 2019-04-16 14-26-15](https://user-images.githubusercontent.com/10743879/56209448-df838000-6053-11e9-8ae3-ed2e62ca0a01.png)


Both tend to suggest that the regression happened one run before (and we were just lucky in the first attempt after regression).
Unfortunately, there was a whole in runs at this point, so there are 93 PR merged in that period:
https://github.com/kubernetes/kubernetes/compare/51db0fe21...f873d2a05
and I didn't yet have time to look into those...

**Comment by wojtek-t** [comment]
I took a look into those 93 PR merged in the period mentioned above. And there are exactly 6 that which impact I couldn't exclude immediately (though in most cases I highly doubt they may cause it):
[I highly doubt] https://github.com/kubernetes/kubernetes/pull/74877
[in theory probable] https://github.com/kubernetes/kubernetes/pull/75389
[I doubt, but...] https://github.com/kubernetes/kubernetes/pull/76065
[I doubt] https://github.com/kubernetes/kubernetes/pull/75967
[I doubt] https://github.com/kubernetes/kubernetes/pull/76211
[only if there would be many panics] https://github.com/kubernetes/kubernetes/pull/75853

**Comment by oxddr** [comment]
Last two runs have also failed density tests. 

Interestingly 5000 kubemark tests are passing just fine. I'll have a look at PR listed above and try to narrow down them down.

**Comment by oxddr** [comment]
At this point, we are still not sure, what is the last good commit. Assuming that the regression has happened before f873d2a0567057ebe8eaa19526513d4e265055e3 and we may get lucky so that load test doesn't fail, the last good run may go back up to f6c51d6e9923431a6a46597a837c0ff58c50dd80.

Next steps:
1) Re-run load test to check whether reverting commits from https://github.com/kubernetes/kubernetes/issues/76579#issuecomment-483982376 helps
2) Check the https://github.com/kubernetes/kubernetes/compare/f6c51d6e9...51db0fe21 range for other obvious culprits

**Comment by oxddr** [comment]
The first re-run wasn't successful - master become unreachable, causing test to crash. I am going to re-run it again.

**Comment by oxddr** [comment]
Reverting commits from https://github.com/kubernetes/kubernetes/issues/76579#issuecomment-483982376 didn't help and load test has failed. I'll have a look at earliest commits then.

**Comment by oxddr** [comment]
In the meantime I am re-running tests at 51db0fe21 to verify what was the last good run.

**Comment by oxddr** [comment]
Load tests had failed at 51db0fe. My current hypothesis is that the last green run was at f6c51d6e9. I am going to verify that now.

**Comment by oxddr** [comment]
I had problems with my machine and results from yesterdays run are lost. I am rerunning tests now. 

I am also having a look whether there are any traces of increased latency in smaller tests (ideally for 100 nodes cluster). Being able to run against smaller cluster will reduce feedback loop.

**Comment by wojtek-t** [comment]
I'm not convinced this is reflected in 100-node tests.

That said, I tried to looked around if I can find something else around that time that regressed.
And here is the graph for:
- LIST pods (scope=cluster) for kubemark-5000 from exactly that time:

![Screenshot from 2019-04-26 10-31-00](https://user-images.githubusercontent.com/10743879/56794578-b6f74500-680e-11e9-9fa1-c532c6a7373f.png)

The increase is really visible there.
The good news from that is:
- it's from density test, which is much faster
- it's from kubemark, which requires less resources to run
- this is from Apr 9th timerange, which is exactly when load test started failing

**Comment by wojtek-t** [comment]
BTW, assuming I'm correct above, there are only 15 commits in that range:
https://github.com/kubernetes/kubernetes/compare/2a05e1b7...99a52350

**Comment by wojtek-t** [comment]
Obviously, assuming that it's not test-infra change or sth like that...

**Comment by wojtek-t** [comment]
I checked test-infra and there weren't any changes for our jobs in this period (we enabled prometheus stack in the previous run, but the last good one already had that).

**Comment by oxddr** [comment]
I've checked your suggestion from the comment above and there is indeed correlation between increased latency in density tests on kubemark and failure on GCE 5000. 

I had a look at the commit range. There were two minor changes to scheduler (https://github.com/kubernetes/kubernetes/commit/db1ab237bf2c89a907902e9001910f1280572eda, https://github.com/kubernetes/kubernetes/commit/a93f803f8e400f1d42dc812bc51932ff3b31798a) and update of dependencies (https://github.com/kubernetes/kubernetes/commit/1cca3f9d45a6aae62145b8630e36722bd316ef88).

**Comment by dims** [comment]
@liggitt https://github.com/kubernetes/kubernetes/commit/1cca3f9d45a6aae62145b8630e36722bd316ef88 was one of yours ...

**Comment by oxddr** [comment]
FYI: I am going to run kubemark tests now with 1cca3f9 revert to check whether it's culprit.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/commit/1cca3f9d45a6aae62145b8630e36722bd316ef88 is the merge commit of a PR updating several dependencies (each in their own commit), and won't revert cleanly on master. If I had to pick a likely candidate, I would try reverting the golang.org/x/sys dependency to its previous version

**Comment by oxddr** [comment]
@liggitt I wasn't precise with my previous comment: I am running version Kuberntes as of 99a52350a43b8824db655779a7d34d8c8f761dfe with  1cca3f9 reverted. It reverted cleanly for me.

**Comment by liggitt** [comment]
I see. Looking through the list of updated dependencies in that PR, only the golang.org/x/sys and golang.org/x/text seem likely possibilities for having any performance implications.

If you wanted to try on master with the previous levels of those dependencies, you could do this:
```
hack/pin-dependency.sh golang.org/x/sys v0.0.0-20171031081856-95c657629925
hack/pin-dependency.sh golang.org/x/text v0.0.0-20170810154203-b19bf474d317
hack/update-vendor.sh
```

Note that the level of those dependencies we were previously on was ~18 months old and not in sync with go 1.12, so I'd be concerned about leaving those at those levels indefinitely.

**Comment by wojtek-t** [comment]
Thanks Jordan - although other PRs does seem to be suspicious, we should first try to prove that it's really this PR that caused regression. Once we know that for sure, we should find the exact commit and then think what do do with it.
I looked into description of golang.org/x/text, and it doesn't seem to be something that should visibly affect the tests.
What I'm wondering though, is that why it can't be golang.org/x/crypto - why did you exclude this one?

**Comment by liggitt** [comment]
> What I'm wondering though, is that why it can't be golang.org/x/crypto - why did you exclude this one?

because that bump only changed a single line:
```diff
 func parseOpenSSHPrivateKey(key []byte) (crypto.PrivateKey, error) {
-       magic := append([]byte("openssh-key-v1"), 0)
-       if !bytes.Equal(magic, key[0:len(magic)]) {
+       const magic = "openssh-key-v1\x00"
+       if len(key) < len(magic) || string(key[:len(magic)]) != magic {
                return nil, errors.New("ssh: invalid openssh private key format")
        }
```

**Comment by wojtek-t** [comment]
got it - thanks makes a lot of sense now

Unfortunately, I just realized, that the results when test run locally (those for kubemark-5000) will not really be comparable, because:
- there are only 3 LIST all pods request in this test (it's interesting how stable that is though...)
- those are done from test, so will be affected by network latency

@aoxn So the fact that those will be higher doesn't mean anything - you need to compare the results relatively to other when running your test locally...

**Comment by wojtek-t** [comment]
I did a number of experiments over the weekend.
I was experimenting with "kubemark-5000", looking into "LIST pods (scope-cluster)" APi call latencies based on https://github.com/kubernetes/kubernetes/issues/76579#issuecomment-486976106

As I also wrote above, I'm not entirely sure if it's a good thing to look, but it was easy to leave tests to run. Here are the results (below 50th, 90th and 99th percentile in microsecond):

- from commit 1cca3f9d45a6aae62145b8630e36722bd316ef88 (PR with Jordan`s update dependency):
```
297409, 542543, 542543   [a bit of outlier]
165483, 298405, 298405
172608, 297054, 297054
176362, 299967, 299967
```
- from commit b8b7ab39ec457b11caffbe0d31bd527cc8aa6f09 (the one before Jordan`s PR):
```
3691183, 4021243, 5058662  [this is strange outlier]
263, 224956, 224956
20565, 96741, 96741
139, 21546, 21546
```

The above seem to suggest that this is really the offending PR.

So I did a bit more:
- I reverted 4 commits: golang.org/x/sys, golang.org/x/crypto, golang.org/x/tools, golang.org/x/exp:
```
181832, 295141, 295141
179151, 293593, 293593
166846, 292647, 292647
```
[The results look really similar to the bad ones]

- On top of that, I also reverted: github.com/stretchr/objx, gonum.org/v1/gonum, golang.org/x/text
```
24333, 219550, 219550
199553, 854049, 854049
179570, 293148, 293148
25676, 181217, 181217
20889, 1850705, 1850705
177521, 293834, 293834
```

And i have troubles with interpreting these results - lower 50th percentile in 3/6 attempt may suggest it's here, but it still looks visibly worse than b8b7ab39ec457b11caffbe0d31bd527cc8aa6f09

But I will risk, and in the background will try to run tests with all golang.org deps reverted leving all others not-reverted (if the change is really in that second batch of reverted commits).

**Comment by dims** [comment]
that's a lot of work! ... thanks @wojtek-t

**Comment by oxddr** [comment]
For sake of completeness I've reverted changes to github.com/sirupsen/logrus, github.com/PuerkitoBio/urlesc, github.com/beorn7/perks, github.com/pborman/uuid and github.com/mailru/easyjson and run the same tests as @wojtek-t .

**Comment by wojtek-t** [comment]
This signal is really weak - I've run tests 3 times with all golang.org deps reverted and the results wer:
```
173654, 295800, 295800
29432, 170616, 170616
174514, 296277, 296277
```
which is quite similar to previous results with a bit more revert described above.

Given how clean the signal was, when run the previous PR, now my thinking is that it's neither of those 8 commits. But I will try to run tests from the "1 PR" before 1 or 2 more times to see if something didn't change in the meantime with the environment, and then we may try to revert something else (assuming we won't get something from @oxddr results)

**Comment by wojtek-t** [comment]
I'm less and less convinced that these are providing any useful signal. But given how easy is to run them, for completeness:
- 2 more runs from PR right before Jordan`s PR:
```
89, 185873, 185873
126, 228658, 228658
```
- 3 runs with last 13 commits of that PR reverted:
```
189035, 295875, 295875
20625, 175537, 175537
182414, 580602, 580602
```

**Comment by wojtek-t** [comment]
3 runs with 16 last commits reverted:
```
190541, 296125, 296125
179396, 296128, 296128
166440, 295622, 295622
```

3 runs with 18 last commits reverted:
```
138, 227467, 227467
103, 24336, 24336
138, 213127, 213127
```

3 runs with 17 last commits reverted:
```
110, 32490, 32490
150, 214017, 214017
173, 199257, 199257
```

I'm running tests with last 16 commits reverted one more time, but it seems that the problematic commit might be this one:
https://github.com/kubernetes/kubernetes/pull/76215/commits/a2ec981f67360f5dace19bd3afa3b120da170484
[which is prometheus library dependency]

**Comment by wojtek-t** [comment]
I did two more runs of it with last 16 commits reverted and the results were:
```
195173, 297218, 297218
27805, 222092, 222092
```

Just looking into repeatability of this, I'm leaning towards saying that it's the commit mentioned above.

Given that manual tests are a bit different than those automatic ones (e.g. the env where the test itself is running is workstation) I would suggest the following experiment:
- [temporary] revert that commit at head
- wait for GCE 5k-node tests to have 1 or 2 runs
- if that won't help re-revert it, if it helps, think what we can do to enable that commit

The cost of revert should be small (it's single dependency update), so it shouldn't cause any merge conflicts or sth like that.

@liggitt - thoughts?

**Comment by wojtek-t** [comment]
The revert has been temporarily merged - we will have the results tomorrow and re-revert if no impact.

However, in the meantime @krzysied found an interesting graph:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCount&Resource=nodes&Scope=cluster&Subresource=&Verb=POST
It seems that around that time nodes started failing.

I took a quick look into one random failure: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1123860268527390723/artifacts/gce-scale-cluster-minion-group-1-fkbv/ and it seems to be OOM on the machine.
So something we should also investigate - where does those OOMs coming from?

**Comment by wojtek-t** [comment]
![Screenshot from 2019-05-07 10-05-45](https://user-images.githubusercontent.com/10743879/57283632-e419e200-70af-11e9-9827-c06a07ab2c57.png)


@liggitt - we don't yet know if that's the only reason for regression, but apparently the revert I did helped for this particular metric ^^ And the impact is quite significant...

**Comment by krzysied** [comment]
Regarding OOM, it looks like this was caused by increased logging in kube-proxy. https://github.com/kubernetes/kubernetes/pull/77541 will revert the change to verify this assumption.

**Comment by liggitt** [comment]
> @liggitt - we don't yet know if that's the only reason for regression, but apparently the revert I did helped for this particular metric ^^ And the impact is quite significant...

if a few more runs demonstrate the lower stats are stable, I'd like to bump to https://github.com/beorn7/perks/commit/4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9 (which has the bugfix for off-by-one stats on unflushed data, but not the map-to-slice translation).

If the stats go back up with that change only, that means:
* we're trying to gather meaningful stats from small sample sizes
* the math.Ceil call while querying stats increased pod latency (unlikely) and/or we were collecting artificially low latencies before, benefiting from the off-by-one error

**Comment by liggitt** [comment]
the fact that the 50% bucket with https://github.com/beorn7/perks/commit/4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9 perfectly aligns with the 90% bucket without that fix strongly indicates we were benefiting from the off-by-one error

**Comment by wojtek-t** [comment]
Yeah - that sounds reasonable. Let's wait one more day and bump it (we should have next run in finished in couple hours and after the next one will be triggered, we can bump - so tomorrow or today evening PST maybe?)

**Comment by dcbw** [comment]
Why is increased kube-proxy logging causing an OOM in the first place? And why is it continuously failing to restore? If it's -4/lock contention, then there are already many fixes in-place (some kernel-side) to handle that. I'm very curious.

**Comment by liggitt** [comment]
> Let's wait one more day and bump it (we should have next run in finished in couple hours and after the next one will be triggered, we can bump - so tomorrow or today evening PST maybe?)

Can we bump the level to https://github.com/beorn7/perks/commit/4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9? I'd like to get rid of the pinned version asap since it means our staging components don't build identically for consumers.

**Comment by mm4tt** [comment]
@liggitt, given how the revert helped in case of kubemark-5000 I think it's reasonable to bump to [beorn7/perks@4c0e845](https://github.com/beorn7/perks/commit/4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9)

**Comment by dims** [comment]
@mm4tt @liggitt i've filed a PR for beorn7/perks@4c0e845

**Comment by mm4tt** [comment]
To summarize what happened this week. 

Kubemark 5000 looks better once  [Revert "github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973"](https://github.com/kubernetes/kubernetes/pull/77510) got in.
![3Wb5eK7ZnYu](https://user-images.githubusercontent.com/2604887/57531061-ec388280-7338-11e9-9d86-7a2ee8f03a0e.png)
The two bad runs are due to https://github.com/kubernetes/kubernetes/issues/77602

GCE 5000 doesn't look good:
 * Monday's run failed due to api call latency regression
 * Tuesday run failed to create cluster due to https://github.com/kubernetes/kubernetes/issues/77551
 * Wednesday / Thursday runs failed either due to some prow issues or https://github.com/kubernetes/kubernetes/issues/77551
 * Friday run is in progress, the density already finished and doesn't look good:
```
W0510 10:24:05.494] E0510 10:24:05.493973   12379 clusterloader.go:177] Test Finished
W0510 10:24:05.494] E0510 10:24:05.493977   12379 clusterloader.go:178]   Test: testing/density/config.yaml
W0510 10:24:05.495] E0510 10:24:05.493981   12379 clusterloader.go:179]   Status: Fail
W0510 10:24:05.497] E0510 10:24:05.493985   12379 clusterloader.go:181]   Errors: [measurement call APIResponsiveness - APIResponsiveness error: top latency metric: there should be no high-latency requests, but: [got: {Resource:replicationcontrollers Subresource: Verb:POST Scope:namespace Latency:{Perc50:30.713ms Perc90:1.243921s Perc99:22.218367s} Count:5159}; expected perc99 <= 1s got: {Resource:pods Subresource: Verb:LIST Scope:cluster Latency:{Perc50:2.864341s Perc90:8.169117s Perc99:11.06723s} Count:11869}; expected perc99 <= 10s got: {Resource:replicationcontrollers Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:312.152ms Perc90:2.269486s Perc99:3.717308s} Count:5050}; expected perc99 <= 1s got: {Resource:clusterrolebindings Subresource: Verb:POST Scope:cluster Latency:{Perc50:7.89ms Perc90:934.048ms Perc99:2.316961s} Count:126}; expected perc99 <= 1s got: {Resource:pods Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:32.244ms Perc90:628.303ms Perc99:2.200264s} Count:313114}; expected perc99 <= 1s got: {Resource:configmaps Subresource: Verb:POST Scope:namespace Latency:{Perc50:4.203ms Perc90:83.673ms Perc99:1.997746s} Count:504}; expected perc99 <= 1s got: {Resource:endpoints Subresource: Verb:GET Scope:namespace Latency:{Perc50:9.526ms Perc90:594.943ms Perc99:1.934924s} Count:6888}; expected perc99 <= 1s got: {Resource:configmaps Subresource: Verb:GET Scope:namespace Latency:{Perc50:7.087ms Perc90:700.61ms Perc99:1.878795s} Count:6789}; expected perc99 <= 1s got: {Resource:deployments Subresource:scale Verb:GET Scope:namespace Latency:{Perc50:4.213ms Perc90:644.656ms Perc99:1.799001s} Count:745}; expected perc99 <= 1s got: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:{Perc50:56.067ms Perc90:645.289ms Perc99:1.727933s} Count:1261507}; expected perc99 <= 1s got: {Resource:leases Subresource: Verb:GET Scope:namespace Latency:{Perc50:51.658ms Perc90:683.357ms Perc99:1.708248s} Count:3599443}; expected perc99 <= 1s got: {Resource:namespaces Subresource: Verb:GET Scope:cluster Latency:{Perc50:3.407ms Perc90:598.534ms Perc99:1.686868s} Count:1111}; expected perc99 <= 1s got: {Resource:endpoints Subresource: Verb:PUT Scope:namespace Latency:{Perc50:4.584ms Perc90:635.087ms Perc99:1.659155s} Count:6130}; expected perc99 <= 1s got: {Resource:configmaps Subresource: Verb:PUT Scope:namespace Latency:{Perc50:4.028ms Perc90:573.08ms Perc99:1.625079s} Count:3076}; expected perc99 <= 1s got: {Resource:services Subresource: Verb:GET Scope:namespace Latency:{Perc50:1.722ms Perc90:201.199ms Perc99:1.55345s} Count:1450}; expected perc99 <= 1s got: {Resource:leases Subresource: Verb:PUT Scope:namespace Latency:{Perc50:34.978ms Perc90:554.635ms Perc99:1.362447s} Count:3516994}; expected perc99 <= 1s got: {Resource:scalingpolicies Subresource: Verb:GET Scope:namespace Latency:{Perc50:38.579ms Perc90:694.336ms Perc99:1.227665s} Count:123}; expected perc99 <= 1s got: {Resource:pods Subresource:status Verb:PATCH Scope:namespace Latency:{Perc50:5.836ms Perc90:291.813ms Perc99:1.184748s} Count:831730}; expected perc99 <= 1s got: {Resource:daemonsets Subresource: Verb:GET Scope:namespace Latency:{Perc50:2.765ms Perc90:482.706ms Perc99:1.147335s} Count:748}; expected perc99 <= 1s got: {Resource:pods Subresource: Verb:GET Scope:namespace Latency:{Perc50:7.971ms Perc90:298.49ms Perc99:1.129257s} Count:1133482}; expected perc99 <= 1s got: {Resource:replicationcontrollers Subresource:status Verb:PUT Scope:namespace Latency:{Perc50:2.639ms Perc90:46.584ms Perc99:1.061413s} Count:16419}; expected perc99 <= 1s]]
```
 So, when it comes to gce-5000 reverting the github.com/beorn7/perks didn't really help.

As the regression is clearly visible in the density test, which takes ~2h (for comparison load test takes ~10h) I propose we temporarily disable load test and start running the density tests more often (we could easily fit a few runs per day) until we figure out what is going on.

**Comment by liggitt** [comment]
> Kubemark 5000 looks better once [Revert "github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973"](https://github.com/kubernetes/kubernetes/pull/77510) got in.

It looks better, but that is likely due to the revert restoring the bug that artificially reports lower latencies at small sample sizes. I expect https://github.com/kubernetes/kubernetes/pull/77735 (which fixes that reporting bug) will likely shift those reported latencies higher again. Note that it is not regressing actual latency, just making the reported latency more accurate at small sample sizes.

**Comment by wojtek-t** [comment]
> It looks better, but that is likely due to the revert restoring the bug that artificially reports lower latencies at small sample sizes. I expect #77735 (which fixes that reporting bug) will likely shift those reported latencies higher again. Note that it is not regressing actual latency, just making the reported latency more accurate at small sample sizes.

@liggitt - as you expected, the revert increased it again:
http://perf-dash.k8s.io/#/?jobname=kubemark-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness&Resource=pods&Scope=cluster&Subresource=&Verb=LIST

But that proves that this is not a cause of regression, but the real bug.
So we should probably get rid of the pin to that old version completely.

[Sorry for delay, I was OOO since Wednesday]

> Why is increased kube-proxy logging causing an OOM in the first place? And why is it continuously failing to restore? If it's -4/lock contention, then there are already many fixes in-place (some kernel-side) to handle that. I'm very curious.

@dcbw - it's probably because we are not setting limits for kube-proxy in any setup, thus it may eat the whole memory on the machine.
And it's NOT "continuously" failing to restore - just some attempts to restore are failing (though I don't have concrete numbers about the percentage).

**Comment by liggitt** [comment]
> So we should probably get rid of the pin to that old version completely.

agreed. opened https://github.com/kubernetes/kubernetes/pull/77809 to restore the version prometheus expects to use

**Comment by wojtek-t** [comment]
This is what we should focus on going forward probably:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadResponsiveness&Resource=pods&Scope=cluster&Subresource=&Verb=LIST

The latency of "LIST pods (scope=cluster)" latency was visibly increased. This may be related to the fact the the number of those calls were also increased. Understanding where are those coming from may help us understand the problem. @mborsz @mm4tt 
https://github.com/kubernetes/kubernetes/issues/77808#issuecomment-491945310 seems related

**Comment by mm4tt** [comment]
Reg. https://github.com/kubernetes/test-infra/pull/12686 and why we believe it may help with this regression (one of these regressions).

We've noticed an increase in memory used by coredns between runs 328 and 329
![0uQsPcCopoP](https://user-images.githubusercontent.com/2604887/57840523-153d9500-77c9-11e9-9d7d-1371710784d9.png)

This memory increases causes coredns to OOM (due to 170MB memory limit) which in turn has a negative impact on api latency (coredns gets restarted then lists all pods/endponts/etc.)
We've noticed that between runs 328 and 330 the cos version has changed on nodes (nodes only, because we overwrite it on master) in https://github.com/kubernetes/kubernetes/pull/75149

We run two tests. One on the exactly the same configuration as run 330 and another with reverted https://github.com/kubernetes/kubernetes/pull/75149.
Below are the graphs which shows that cos version upgrade is very likely related to the coredns memory increase

**330**
![ziNndcbdj7U](https://user-images.githubusercontent.com/2604887/57840841-af054200-77c9-11e9-9c24-09b7ab5837e7.png)

**330 with reverted https://github.com/kubernetes/kubernetes/pull/75149**
![wzEfFdaqanY](https://user-images.githubusercontent.com/2604887/57840883-c2181200-77c9-11e9-9aa9-b4db0de7ef07.png)

**Comment by wojtek-t** [comment]
I forked the CoreDNS problem to a separate issue: https://github.com/kubernetes/kubernetes/issues/78562

With that, this one can be closed.
