### ISSUE TITLE
kubectl: CrashLoopBackOff

### ISSUE THREAD

**Issue by chenliu1993** [kubernetes/kubernetes#76589]
I am new to kubernetes. I am running kubectl to pods:kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2 
but this status shows up:CrashLoopBackOff
![image](https://user-images.githubusercontent.com/13761170/56120036-ddf88000-5f9f-11e9-9608-e72210398a27.png)
And this is the kubectl describle pod podname shows:
![image](https://user-images.githubusercontent.com/13761170/56120109-10a27880-5fa0-11e9-8e48-5cea65cc815f.png)
What problem could this be? I am confused😂.
The OS is Centos 7.
Any help will be much appreciated.

**Comment by oxddr** [comment]
Hi @chenliu1993, it seems that your pod/container is crash looping. Can you check logs (```kubectl logs ${POD_NAME}```) for any obvious issues?

**Comment by WanLinghao** [comment]
You didn't specify command entry point for them.
Try `kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2 -- sleep 3000`
And then you can attach into container via:
kubectl exec -it  busybox-1-xxxxxx  -- /bin/ash

**Comment by WanLinghao** [comment]
Feel free if you want to reopen this
/close

**Comment by chenliu1993** [comment]
> Hi @chenliu1993, it seems that your pod/container is crash looping. Can you check logs (`kubectl logs ${POD_NAME}`) for any obvious issues?
No logs out from kubectl logs pos_name

**Comment by chenliu1993** [comment]
> kubectl exec -it busybox-1-xxxxxx -- /bin/ash

Thank you , issue solved!

**Comment by chenliu1993** [comment]
> You didn't specify command entry point for them.
> Try `kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2 -- sleep 3000`
> And then you can attach into container via:
> kubectl exec -it busybox-1-xxxxxx -- /bin/ash

Could you explain why after adding "-- sleep 3000" then it works? Why this command "sleep"?

**Comment by WanLinghao** [comment]
Each container needs a entry point, it would execute this entry point after boot. Here we assign it sleep so it would not exit. You may also try 
`kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2  -- /bin/ash`
Then you could observe that the container exit as soon as booting.  Since it boot the container, execute /bin/ash command, completed, exit.

**Comment by chenliu1993** [comment]
> Each container needs a entry point, it would execute this entry point after boot. Here we assign it sleep so it would not exit. You may also try
> `kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2 -- /bin/ash`
> Then you could observe that the container exit as soon as booting. Since it boot the container, execute /bin/ash command, completed, exit.

Got it! Thank you！

**Comment by chenliu1993** [comment]
> kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2 -- /bin/ash
Thank you!
But why it will exit as soon as booting? Why is it not openning a tty like "kubectl exec -it busybox-1-xxxxxx -- /bin/ash"

**Comment by chenliu1993** [comment]
> Each container needs a entry point, it would execute this entry point after boot. Here we assign it sleep so it would not exit. You may also try
> `kubectl run busybox-1 --image=docker.io/library/busybox:latest --replicas=2 -- /bin/ash`
> Then you could observe that the container exit as soon as booting. Since it boot the container, execute /bin/ash command, completed, exit.

Thank you!
But why it will exit as soon as booting? Why is it not openning a tty like "kubectl exec -it busybox-1-xxxxxx -- /bin/ash"
And why after "sleep 3000", the container will not show "Completed" status. Is it supposed to complete after 3000?
