### ISSUE TITLE
[Failing Test] listResources step failing 

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#76609]
**Jobs affected by failures**:
* `ci-kubernetes-e2e-gci-gce` 
* `ci-kubernetes-e2e-gce-device-plugin-gpu` 
* `ci-kubernetes-e2e-gci-gce-slow` 
* `ci-kubernetes-e2e-gci-gce-alpha-features`
* `ci-kubernetes-e2e-gci-gce-scalability`
* `ci-kubernetes-e2e-gci-gce-ingress`
* `ci-kubernetes-e2e-gci-gce-reboot`

**Which test(s) are failing**:
* In `ci-kubernetes-e2e-gci-gce` 
  * [`listResources After`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1117764911116587008)
* In `ci-kubernetes-e2e-gce-device-plugin-gpu`
  *  [`listResources After`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1117752328045203457)
* In `ci-kubernetes-e2e-gci-gce-slow`
  * [`listResources After`](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1117765161269071872)
* In `ci-kubernetes-e2e-gci-gce-alpha-features`
  * `listResources Before`
  * `listResources Down`
  * `diffResources`
* In `ci-kubernetes-e2e-gci-gce-scalability`
  * `listResources Down` failed 2 out of the 3 last runs.
  * `listResources After` failed 2 out of the 3 last runs, it is not currently failing.
  * `listResources Up` failed 2 out of the 3 last runs, it is not currently failing.
  * `listResources Before` failed 1 out of the 3 last runs, it is not currently failing.
* In `ci-kubernetes-e2e-gci-gce-ingress`
  * `listResource Up`
  * `listResource Down`
  * `listResources After`
* In `ci-kubernetes-e2e-gci-gce-reboot`
  * `listResources After`

**Since when has it been failing**:
* In `ci-kubernetes-e2e-gci-gce`
  * Failure appeared on 4/15 at 5:21 PDT 
  * kubernetes/kuberentes diff c09cfb717 117160a9e
  * test-infra diff 764cad593 126cb79be ***
* In `ci-kubernetes-e2e-gce-device-plugin-gpu`
  * Failure appeared on 4/15 at 4:31 PDT
  * kubernetes/kubernetes diff c09cfb717 117160a9e
  * test-infra on 126cb79be
* In `ci-kubernetes-e2e-gci-gce-slow`
  *  Failure appeared on 4/15 at 5:22 PDT
  * Kubernetes/kubernetes diff c09cfb717 117160a9e coincides with failure
  * test-infra 764cad593 126cb79be
* In `ci-kubernetes-e2e-gci-gce-alpha-features`
  * First failure happened on 4/15 at 3:08 PDT. 
  * Kubernetes/kubernetes diff c09cfb717 117160a9e 
  * test-infra diff 764cad593 126cb79be
* In `ci-kubernetes-e2e-gci-gce-scalability`
  * First failure happened on 4/15 at 3:58 PDT
  * kubernetes/kuberentes diff c09cfb717 117160a9e coincides with failure
  * test-infra diff 764cad593 126cb79b
* In `ci-kubernetes-e2e-gci-gce-ingress`
  * First failure occurred on 4/15 at 3:54 PDT
  * kubernetes/kubernetes diff 117160a9e 18533fe84 coincides with failure
  * test-infra on 126cb79be
* In `ci-kubernetes-e2e-gci-gce-reboot`
  * First failure occurred on 4/15 at 3:52 PDT
  * kubernetes/kubernetes diff 117160a9e 18533fe84 coincides . with failures
  * test-infra on 126cb79be

**Testgrid link**:
* `ci-kubernetes-e2e-gci-gce`: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default
* `ci-kubernetes-e2e-gce-device-plugin-gpu`: https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master
* `ci-kubernetes-e2e-gci-gce-slow`: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-slow
*  `ci-kubernetes-e2e-gci-gce-alpha-features`: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features
* `ci-kubernetes-e2e-gci-gce-scalability`: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100
* `ci-kubernetes-e2e-gci-gce-ingress`: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-ingress
* `ci-kubernetes-e2e-gci-gce-reboot`:  https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot

**Reason for failure**:
* `ci-kubernetes-e2e-gci-gce`. see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1117764911116587008)
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-jkns-e2e-kubeadm-gce-ci
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce
[ compute instance-templates ]

[ compute instance-groups ]

[ compute instances ]
```

* `ci-kubernetes-e2e-gce-device-plugin-gpu`, see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1117752328045203457)
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-jkns-e2e-gke-gpus
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]

[ compute instance-groups ]

[ compute instances ]
```
* In `ci-kubernetes-e2e-gci-gce-slow`, see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1117765161269071872)
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-jkns-clusterloader
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]

[ compute instance-groups ]

[ compute instances ]
```
* In `ci-kubernetes-e2e-gci-gce-alpha-features`, see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1117763400424755202)

**listResources Before**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-jkns-gce-ubuntu-1-6-slow
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]

[ compute instance-groups ]

[ compute instances ]
```
**listResources down**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-jkns-gce-ubuntu-1-6-slow
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]
NAME                                 MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
bootstrap-e2e-minion-template        n1-standard-2               2019-04-15T05:20:06.682-07:00
bootstrap-e2e-windows-node-template  n1-standard-2               2019-04-15T05:20:13.828-07:00

[ compute instance-groups ]
NAME                        LOCATION    SCOPE  NETWORK        MANAGED  INSTANCES
bootstrap-e2e-minion-group  us-west1-b  zone   bootstrap-e2e  Yes      3

[ compute instances ]
```
**diffResources**
```
Error: 34 leaked resources
+[ compute disks ]
+[ compute addresses ]
+[ compute routes ]
+NAME                            NETWORK  DEST_RANGE     NEXT_HOP                  PRIORITY
+default-route-106ddc8ac41d837d  default  10.152.0.0/20  default                   1000
+default-route-2a15fc785e01cac6  default  10.128.0.0/20  default                   1000
+default-route-4504d509cfe64019  default  10.142.0.0/20  default                   1000
+default-route-4c1ebb5261806daf  default  10.132.0.0/20  default                   1000
+default-route-506a3c1d08c0b7d4  default  10.164.0.0/20  default                   1000
+default-route-79d6a6d73ed16ada  default  10.154.0.0/20  default                   1000
+default-route-8ace5deb1bed0c36  default  10.166.0.0/20  default                   1000
+default-route-8b5408c1eb57a62a  default  10.160.0.0/20  default                   1000
+default-route-8b86be384612b907  default  10.170.0.0/20  default                   1000
+default-route-966264f4cfc0cbbd  default  10.150.0.0/20  default                   1000
+default-route-97b1c743fb2df7cb  default  10.148.0.0/20  default                   1000
+default-route-9822df6732ae40e4  default  10.138.0.0/20  default                   1000
+default-route-a2ceee605cb420af  default  10.168.0.0/20  default                   1000
+default-route-aab74676b8ef459e  default  10.172.0.0/20  default                   1000
+default-route-acba5fb3b4800be0  default  10.156.0.0/20  default                   1000
+default-route-ae554e1c43c59149  default  10.174.0.0/20  default                   1000
+default-route-b04cfab0bec3511f  default  10.158.0.0/20  default                   1000
+default-route-ba19f1b7b73d17be  default  10.162.0.0/20  default                   1000
+default-route-c07dc7e7ab4e5554  default  10.140.0.0/20  default                   1000
+default-route-cf7310f47a88d31b  default  0.0.0.0/0      default-internet-gateway  1000
+default-route-ed0ae002860a5a75  default  10.146.0.0/20  default                   1000
+[ compute firewall-rules ]
+NAME                    NETWORK  DIRECTION  PRIORITY  ALLOW                         DENY  DISABLED
+default-allow-icmp      default  INGRESS    65534     icmp                                False
+default-allow-internal  default  INGRESS    65534     tcp:0-65535,udp:0-65535,icmp        False
+default-allow-rdp       default  INGRESS    65534     tcp:3389                            False
+default-allow-ssh       default  INGRESS    65534     tcp:22                              False
+[ compute forwarding-rules ]
+[ compute target-pools ]
+[ logging sinks ]
```
* In `ci-kubernetes-e2e-gci-gce-scalability`, see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1117767929283219459)
**listResources Down**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-e2e-gce-scalability-1-2
Region: 
Zone: 
Instance prefix: e2e-big
Network: e2e-big
Provider: gce

[ compute instance-templates ]
NAME                           MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
e2e-big-minion-template        n1-standard-1               2019-04-15T05:40:16.696-07:00
e2e-big-windows-node-template  n1-standard-1               2019-04-15T05:40:23.610-07:00

[ compute instance-groups ]
NAME                  LOCATION    SCOPE  NETWORK  MANAGED  INSTANCES
e2e-big-minion-group  us-east1-b  zone   e2e-big  Yes      100

[ compute instances ]
```
* In `ci-kubernetes-e2e-gci-gce-ingress`, see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1117743014706417667)
**lisTresources Up**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-ingress-boskos-10
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]
NAME                                 MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
bootstrap-e2e-minion-template        n1-standard-2               2019-04-15T03:58:13.687-07:00
bootstrap-e2e-windows-node-template  n1-standard-2               2019-04-15T03:58:20.199-07:00

[ compute instance-groups ]
NAME                        LOCATION           SCOPE  NETWORK        MANAGED  INSTANCES
bootstrap-e2e-minion-group  asia-southeast1-a  zone   bootstrap-e2e  Yes      3

[ compute instances ]
```
**listResources Down**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-ingress-boskos-10
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]
NAME                                 MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
bootstrap-e2e-minion-template        n1-standard-2               2019-04-15T03:58:13.687-07:00
bootstrap-e2e-windows-node-template  n1-standard-2               2019-04-15T03:58:20.199-07:00

[ compute instance-groups ]
NAME                        LOCATION           SCOPE  NETWORK        MANAGED  INSTANCES
bootstrap-e2e-minion-group  asia-southeast1-a  zone   bootstrap-e2e  Yes      3

[ compute instances ]
```
**listResources After**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: k8s-ingress-boskos-10
Region: 
Zone: 
Instance prefix: bootstrap-e2e
Network: bootstrap-e2e
Provider: gce

[ compute instance-templates ]

[ compute instance-groups ]

[ compute instances ]
```
* In `ci-kubernetes-e2e-gci-gce-reboot`, see [spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1117774219334127617)
**listResources After**
```
Failed to list resources (error during ./cluster/gce/list-resources.sh: exit status 2):
Project: gce-gci-upg-1-4-1-3-ctl-skew
Region: 
Zone: 
Instance prefix: err-e2e
Network: err-e2e
Provider: gce

[ compute instance-templates ]

[ compute instance-groups ]

[ compute instances ]
```

**Anything else we need to know:**
Most of the test failures mentioned in this issue coincide with changes on kubernetes/kubernetes between [c09cfb7 117160a](https://github.com/kubernetes/kubernetes/compare/117160a...c09cfb7) and
[117160a 18533fe](https://github.com/kubernetes/kubernetes/compare/18533fe...117160a), however the latter occurred before the former and the failures can be observed in `ci-kubernetes-e2e-gci-gce-ingress`and `ci-kubernetes-e2e-gci-gce-reboot`.

**Update**: The failures seem to be clearing up in most of the tests. We should give a couple more hours to see if any further action needs to be taken.

/kind failing-test
/priority critical-urgent
/milestone v1.15
/sig cluster-lifecycle
/sig api-machinery
/sig testing

/cc @jimangel @smourapina @rarchk @alenkacz

**Comment by roycaihw** [comment]
/unassign
/sub

[`ci-kubernetes-e2e-gci-gce` history](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce) shows that the last occurrence of `listResources` failure happened at [7 hours ago](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1117776990951182338)

As the first comment suggested, I'll wait to see if further action needs to be taken from sig-api-machinery perspective

**Comment by roycaihw** [comment]
among the latest 20 runs of `ci-kubernetes-e2e-gci-gce` (between `2019-04-16 01:54:44 +0000 UTC` and `2019-04-16 16:25:53 +0000 UTC`) I see only one `listResource` [failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1118113197740527617)

```
listResources After
Failed to list resources (error during ./cluster/gce/list-resources.sh (interrupted): signal: aborted (core dumped)):
```

which is likely be triggered by timeout
```
```

**Comment by alejandrox1** [comment]
Thank you for looking into this @roycaihw 
Will be closing this since the failures haven't reoccurred in the last couple days.
/close
