### ISSUE TITLE
kubelet fails to start with custom docker root dir

### ISSUE THREAD

**Issue by jansmets** [kubernetes/kubernetes#76604]
Kubelet v1.14.1 fails to start when the Dcker Root dir is changed from the default.
```
# cat /etc/docker/daemon.json 
{
"data-root" : "/data/docker"
}
```
```
$ docker info
Docker Root Dir: /data/docker
```

I am running kubelet in a container that mounted volume `/data/docker:/data/docker:rw`
(also `/var/lib/kubelet` is mounted that way)
```
(reduced)
/usr/bin/docker run --rm --net host --pid host --privileged --volume /var/run:/var/run:rw --volume /data/docker:/data/docker:rw --volume /var/lib/kubelet:/var/lib/kubelet:shared -v /sys:/sys:ro  gcr.io/google-containers/hyperkube-amd64:v1.14.1     kubelet
```

```
F0415 12:57:40.074265   14895 kubelet.go:1359] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 37 in cached partitions map
```

When I also change the 'host side' `/var/lib/kubelet` to `/data/kubelet`,  kubelet starts.
```
/usr/bin/docker run --rm --net host --pid host --privileged --volume /var/run:/var/run:rw --volume /data/docker:/data/docker:rw --volume /data/kubelet:/var/lib/kubelet:shared  gcr.io/google-containers/hyperkube-amd64:v1.14.1     kubelet
```

When all the above is attempted with k8s `v1.13.5` it all works as expected.

Thank you

**Comment by YoubingLi** [comment]
@jansmets 

   Can you share more log about this issue?

**Comment by franclinsousa** [comment]
I create a link symbolic. It works!

**Comment by ruanafan** [comment]
@franclinsousa I have a same issue like this. 
I try to create a link symbolic like this:
> ln -s /home/../docker docker

But this does not work, could you please tell me how you fix this problem?
