### ISSUE TITLE
Reap/GC terminated pods

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#7660]
So that successful/failed pods don't accumulate forever.

**Comment by bgrant0607** [comment]
In the meantime, we should at least document that users need to do this.

**Comment by alex-mohr** [comment]
@lavalamp found failure modes of replication controllers where they spinloop creating pods that subsequently fail.  With nothing to reap those failed pods, they accumulate until etcd and apiserver get unhappy and the cluster is unusable.

Note that we need to bound the size of etcd's database, so a purely time-based GC interval may not be sufficient.

**Comment by bgrant0607** [comment]
The RC manager could do smarter GC, such as taking into account the failure reason. For instance, if there are no logs associated with the pods, there's no need to keep the pods in addition to the events. I'd also be in favor of backing off restarts. There was discussion about that in #2529.

**Comment by lavalamp** [comment]
Sure, RC manager could be smarter. But I think this problem is bigger than just RC (since we're going to add job and daemon controllers in the near future) and deserves a solution that is bigger than RC manager.

**Comment by lavalamp** [comment]
I want to add that from my vast sample size of 1, users in practice don't delete failed pods and instead just ignore them. Just having them in the `kubectl get pods` list isn't enough to cause users to go out and delete them. Users may not even realize they are supposed to do that.

At a minimum we should make get pods work with that by hiding these by default, and if any were present, print something like `... and N failed pods. Run "kubectl get pods --include-failed" to see failed pods, or run "kubectl delete pods --failed" to delete them.`

**Comment by a-robinson** [comment]
For what it's worth, I can definitely say that my instinct as a user would fall in line with @lavalamp's sample size of 1. I wouldn't delete failed pods, assuming the system would take care of them.

**Comment by nikhiljindal** [comment]
Discussed this with @lavalamp and an option is that the apiserver can set a ttl on the pod in etcd, when it gets an update setting the pod in failed state.
Lets see if I can make that work.

**Comment by bgrant0607** [comment]
Users don't delete pods: I agree, hence this issue.

Needs to be generalized for all controllers: I agree. Node controller could be a logical place. Eventually we'll need a general GC mechanism, such as to implement existence dependencies across objects.

Hiding dead pods: Docker convention is that `docker ps` shows live containers and `docker ps -a` includes dead containers. We could do something similar.

**Comment by abrutus** [comment]
+1 

There are no expectations documented anywhere for the end-user to manage failed pods, and leaving such a potentially critical operation (failing to do so [will lock the cluster](https://github.com/GoogleCloudPlatform/kubernetes/issues/11912#issuecomment-126053131)) to the end user is not a good idea.

**Comment by alex-mohr** [comment]
@nikhiljindal thanks for taking this on.  A ttl will likely help, but I'm not sure it's sufficient.  What TTL would have prevented the 130k pod issue?  Will that TTL prevent the next one?

Ultimately, etcd does not have infinite storage, so we need to ensure that we don't fill it with too many dead pods.  I'd propose we have an explicit cap on the number of them (even if via eventual consistency via a reaper run reasonably often).

**Comment by lavalamp** [comment]
@alex-mohr a 4 or 5 day TTL should have prevented this particular instance. We can do better, but that's a good start. I think a complete solution for this basically has to come along with the job controller (which will be able to make failed/succeeded pods at a much faster rate) and can probably be deferred until then, too.

**Comment by lavalamp** [comment]
@JanetKuo to look at `kubectl get pods` behavior for failed/succeeded pods.

**Comment by nikhiljindal** [comment]
Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/12055 to put a TTL of 4 days on terminated pods.

**Comment by derekwaynecarr** [comment]
I do like an option to hide failed/succeeded pods in kubectl to align with
docker ps -a

I do not like using TTL - especially if it is not configurable.  We run a
number of short lived pods in OpenShift even without Jobs yet.

**Comment by abrutus** [comment]
@derekwaynecarr are those openshift pods "failed"?

**Comment by derekwaynecarr** [comment]
I am sure we have build pods that exit with a non-zero exit status.  So
yes, some can be failed and some can be succeeded.

Actually from a kubectl perspective, not sure if I want two flags instead
of -a.  I think -a is fine if I can apply a status.phase selector to
distinguish.

**Comment by nikhiljindal** [comment]
Summarizing discussion spread across various issues and PRs (#11631, #12055 and #9165).

* We do not want to use TTL as it is not terribly efficient in etcd - it causes latency spikes under
write load and also ties us to etcd more strongly. (https://github.com/GoogleCloudPlatform/kubernetes/pull/12055#issuecomment-126718014)
* Instead, having a controller that garbage collects pods seems better.
* We anyways need it for deleting pods scheduled on deleted nodes. (NodeController cant keep track of pods it needs to delete after detecting a deleted node, if it crashes in between: https://github.com/GoogleCloudPlatform/kubernetes/issues/11631#issuecomment-128515613). We can extend the same controller to delete other pods that we want to delete.
* list of pods that we want this controller to delete:
- Pods scheduled on a deleted node.
- Pods that have been gracefully deleted. (Ideally, kubelet will delete the pod after gracefully killing the pod on node, except when it crashes in between)
- Terminated pods.
(https://github.com/GoogleCloudPlatform/kubernetes/pull/12055#issuecomment-126718014)

**Comment by nikhiljindal** [comment]
@smarterclayton What about pods corresponding to deleted RCs? And pods in deleted namespaces?
Should this controller delete them as well?

And should this controller be pod specific? For ex: should we reuse the same controller to delete RCs in deleted namespaces?

**Comment by smarterclayton** [comment]
On Aug 7, 2015, at 4:21 AM, Nikhil Jindal <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> What about pods
corresponding to deleted RCs?

That I think is not necessary yet, although in the future I could imagine
it happening.  It might be better to support graceful deletion of RCs via
the existing replication controller.

And pods in deleted namespaces?

Already handled by namespace controller

Should this controller delete them as well?

And should this controller be pod specific?

Possibly, although there is overlap for any resource which is bound to
another resource (services and load balancers).

For ex: should we reuse the same controller to delete RCs in deleted
namespaces?


I think the namespace controller handles that case sufficiently today.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/7660#issuecomment-128637839>
.

**Comment by bgrant0607** [comment]
If we're going to have a general-purpose GC component, which I agree would be useful, I'd like it eventually to handle existence dependencies of other objects, as described https://github.com/GoogleCloudPlatform/kubernetes/issues/1535#issuecomment-91413501

**Comment by nikhiljindal** [comment]
@smarterclayton Does https://github.com/GoogleCloudPlatform/kubernetes/pull/9165 take care of this controller or do you want me to send a proposal/PR for it?

**Comment by smarterclayton** [comment]
Going to be separate - I just stemmed the bleeding and ensured we retried
where appropriate (but permanent fails can still cause problems).

On Aug 11, 2015, at 4:57 PM, Nikhil Jindal <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> Does #9165
<https://github.com/GoogleCloudPlatform/kubernetes/pull/9165> take care of
this controller or do you want me to send a proposal/PR for it?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/7660#issuecomment-130071516>
.

**Comment by nikhiljindal** [comment]
ok. Will send a separate PR for it then. Thanks!

**Comment by nikhiljindal** [comment]
I dont think I will be able to get this done in time for 1.1 (working on a few other things).
Unassigning myself so that someone else can pick it up.

@lavalamp any suggestions on who can pick this?

**Comment by davidopp** [comment]
Yikes, I totally missed this.

Can someone summarize the absolute minimum we need to do to prevent the original problem? Many  ideas were suggested here, but would it be sufficient to just have node controller delete pods that meet any of the criteria that @nikhiljindal mentioned, namely
* Pods scheduled on a deleted node.
* Pods that have been gracefully deleted. (Ideally, kubelet will delete the pod after gracefully killing the pod on node, except when it crashes in between)
* Terminated pods. (#12055 (comment))

It seems the "hide dead pods" part can be punted to post-1.1?

@mikedanese @gmarek

**Comment by gmarek** [comment]
It doesn't seem natural to me for NodeController to be responsible for GC-ing Pods - it currently doesn't loop through them and I don't think it should. To be fair, I don't know if there's any component that does, so we might as well put it in the NodeController, but I believe that a separate controller might give a 'cleaner' architecture.

That being said, I think that the list @davidopp gave is valid. I know nothing about the Daemons and Jobs, so there might be some other cases when we end up with dangling pods.

**Comment by davidopp** [comment]
Yeah I think there were some suggestions to do a new generic "garbage collection" controller. I'm fine with that, just trying to figure out what we can do before the 1.1 deadline that doesn't require time travel. We could put it into node controller for now and move it out later, I guess (it's not an API change).

**Comment by gmarek** [comment]
I opened #14261 for it.

**Comment by smarterclayton** [comment]
There would be other loops on pods that are relevant (pods with an
activeDeadlineTimeout >>>> their value) so I would much prefer a pod
deletion controller for the core policy.

**Comment by alex-mohr** [comment]
The issue we saw in production was accumulating an unbounded and growing number of pods such that etcd and apiserver ran out of memory with 100+k pods.

I'd propose we use some flavor of that as an exit criteria: how well does the proposed strategy/implementation meet that goal?  Bonus points for fewer crossed fingers required.

**Comment by davidopp** [comment]
@mikedanese is going to work on this, as a new controller (with no coresponding API object). The intention is to get it in for 1.1 though obviously it will have to be a cherrypick.

**Comment by mikedanese** [comment]
Initial implementation in #14325

**Comment by mikedanese** [comment]
@alex-mohr this feature is available but not enabled. I recommend a failed pod limit of 12500 for GCE/GKE after testing responsiveness of the apiserver under this load. I can  submit a PR if we are happy with that number.

**Comment by alex-mohr** [comment]
@mikedanese Thanks for driving this.  12500 seems reasonable to me too, though I haven't been following details.  +1 to enabling by default in 1.1 if we're confident enough in it.

**Comment by davidopp** [comment]
Remaining items to do:
* Delete pods scheduled on a deleted node.
* Delete pods that have been gracefully deleted in the case where Kubelet died during the grace period

**Comment by smarterclayton** [comment]
I think the second bullet is covered if you aren't assuming the first
bullet.  The node controller will detect and terminate pods on nodes that
still exist.

**Comment by davidopp** [comment]
I think all the 1.1 bits are now finished (I just LGTMd #15183 which I believe was the last relevant PR), so we can remove the label. @mikedanese do you agree?

**Comment by davidopp** [comment]
There is more to do here, just not for 1.1

**Comment by mikedanese** [comment]
I'm reasigning this to you @davidopp. It's currently a p1 but I'm not working on it.

**Comment by bgrant0607** [comment]
@mikedanese @davidopp Can this be closed in favor of more specific issues?

**Comment by bgrant0607** [comment]
@mikedanese @davidopp Please file more specific issues for remaining work.

**Comment by kierenj** [comment]
I'm curious if there's anything to help me out with this.  I'm firmly in the beginner category for kubernetes, but after a few experiments my status graphs/stats are out of whack with hundreds of failed pods.  Is there any advice available on this / any follow-on issue I can subscribe to? Thanks.

**Comment by afirth** [comment]
https://github.com/micnncim/kubectl-reap was mentioned in another thread
