### ISSUE TITLE
pod status shows "CrashLoopBackOff" but pod phase shows "Running"

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubernetes#76619]
**What happened**:
Here is a pod called _test-worker-0_ which created by **stateful set**. I run some command contains **exit 0 ** in this pod, so that the status keeps `"CrashLoopBackOff"` when I run
`kubectl get pods test-worker-0` 

However, when I catch the phase field via `kubectl get pods test-worker-0 -o yaml`, it always shows as `“Running”`. The same issue happen via invoking kube-client python SDK `read_namespaced_pod_status` method

Is that a bug , or how can I catch the accurate status whenever this pod is in `"CrashLoopBackOff"` ?

**What you expected to happen**:
phase field should show correctly when pod is CrashLoopBackOff

**How to reproduce it (as minimally and precisely as possible)**:

1.  create a stateful set, which container.command just writes "exit 0"
2. pod will keep `"CrashLoopBackOff"` via `kubectl get pods test-worker-0` 
3. according to `kubectl get pods test-worker-0 -o yaml` or `read_namespaced_pod_status`, phase field keep showing as `“Running”`

**Anything else we need to know?**:

**Environment**: centos 7.5
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: on-premise
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`): Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by mysunshine92** [comment]
what is the pod's restartPolicy, if restartPolicy is Always，kubelet will always restart the pod，so the phase is Running。

**Comment by mysunshine92** [comment]
what is the pod's restartPolicy? if restartPolicy is Always，kubelet will always restart the pod，so the phase is Running.

**Comment by Cherishty** [comment]
Yes, and for stateful set pod will always restart if failed.
But I still wonder why the status in "phase" field does not match, and how can I handle "CrashLoopBackOff" message for the pod in stateful set?

**Comment by Joseph-Irving** [comment]
`CrashLoopBackOff` isn't actually a Pod Phase it's a container error state https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/sync_result.go#L28. It can be found in `containerStatuses[i].state.waiting.reason: "CrashLoopBackOff"`
E.g 
```yaml
status:
  containerStatuses:
  - containerID: foo
    image: image
    name: myContainer
    ready: false
    restartCount: 10
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=myContainer
        reason: CrashLoopBackOff
```
You can see the Pod phases here https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2160.

**Comment by GeorgeGuo2018** [comment]
> what is the pod's restartPolicy? if restartPolicy is Always，kubelet will always restart the pod，so the phase is Running.

Not exactly what you said. I had deployed a daemonset in my cluster with restart policy "always".  When one of the pod is pending, the 'pod.status.phase' changed to 'pending' using 'kubectl get pod xxx -n xxx -o yaml'.    I think, when the pod is not running correct for somereason like 'CrashLoopBackOff',  the kubectl command gives out the reason in the status field in stdout but  the actually 'pod.status.phase' remained, as 'CrashLoopBackOff' is actually not a pod phase.
you can try it out.
Actually i think it is better to determine a pod's status together with the judgement of 'pod.status.conditions' with type='Ready' and status='True' if such conditions exist.

**Comment by edmondo1984** [comment]
/remove-lifecycle rotten . One cannot rely on a kubernetes apply -f statefulset.yml exit code if this is not fixed and there are situations where it is highly desirable to be able to rollback if the pod never comes up

**Comment by aloisio31** [comment]
You can inspect the source code and check the function [printPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L734). And we can find the `STATUS` showed by `kubectl get pods` is defined by the variable `reason`.

**Comment by amolvgaikwad** [comment]
Hi All,

My Pod is going to crashloop when I add commands: ["sh","-c","echo Hi"]. 
Pod Staate  is completed, exit  code is 0. After 4 5 seconds it goes to crashloop. 

Does anyone faced the similar issues?
