### ISSUE TITLE
Fix: Use image util package to grab registry instead of static image path

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#76617]
Use image util package [[link](https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go)] to grab registry instead of using static image path to pull container images.

Reference: https://github.com/kubernetes/kubernetes/pull/75631#pullrequestreview-226247855

**Comment by mgdevstack** [comment]
Following references should be fixed.

1. https://github.com/kubernetes/kubernetes/blob/a9d4eddcd1515aac51a8b743cb0df002e7c92225/test/e2e/framework/ingress/ingress_utils.go#L931

2. https://github.com/kubernetes/kubernetes/blob/c1d2ac43ee26a83fd4045353937977c120b7246b/test/e2e/framework/pv_util.go#L807

3. https://github.com/kubernetes/kubernetes/blob/465e96535d578ae67d69b27183f01e3e1aac165e/test/e2e/network/kube_proxy.go#L244

4. https://github.com/kubernetes/kubernetes/blob/5993ec5a5a306de2b329ae7bfd182e8dddf3a8f3/test/e2e/storage/drivers/in_tree.go#L505

5. https://github.com/kubernetes/kubernetes/blob/5993ec5a5a306de2b329ae7bfd182e8dddf3a8f3/test/e2e/storage/drivers/in_tree.go#L530

6. https://github.com/kubernetes/kubernetes/blob/1addcf471519dde12667832980201785f6c2628a/test/e2e/storage/utils/utils.go#L356

7. https://github.com/kubernetes/kubernetes/blob/fc4cbf743ac899df1d96f520951c6b24dcaa8494/test/e2e/storage/volume_provisioning.go#L1161

8. https://github.com/kubernetes/kubernetes/blob/2321d1e9e8950cc94b3ef2368dfaacec61f1ba4f/test/e2e/storage/testsuites/ephemeral.go#L248

9. https://github.com/kubernetes/kubernetes/blob/eeb15a57fc8f2fd63e1aece9cb31cafa38097e21/test/e2e/apimachinery/table_conversion.go#L93

10. https://github.com/kubernetes/kubernetes/blob/c7f9dd0bafe2f3328148a85eed9c18322b9f308e/test/e2e/apimachinery/chunking.go#L64

11. https://github.com/kubernetes/kubernetes/blob/477304cdbdafed50826a3538c8a51fd91b89ad4e/test/e2e/framework/node/resource.go#L426

12. https://github.com/kubernetes/kubernetes/blob/a9d4eddcd1515aac51a8b743cb0df002e7c92225/test/e2e/framework/util.go#L1881

**Comment by mgdevstack** [comment]
13. https://github.com/kubernetes/kubernetes/blob/f5574bf62a051c4a41a3fff717cc0bad735827eb/test/e2e/windows/hybrid_network.go#L39

**Comment by johnSchnake** [comment]
I have no real problem with the ones that are making up image names like `foo` or `fake-not-scheduled`

I will take a look at the ones actually referring to real images and update them.
