### ISSUE TITLE
Provide pretty debug tooling for distroless-based images 

### ISSUE THREAD

**Issue by yuwenma** [kubernetes/kubernetes#76629]
**What would you like to be added**:
Provide a standard, easy to use debugging workflow for all contributors who work on a k8s container based on distroless 
**Why is this needed**:
Distroless doesn't contain shell. Thus, the widely used debugging approaches (e.g. entrypoint or kubectl exec) no longer work for distroless-based images. We'd like to come up with some tooling (or maybe a handbook) about how to debug on distroless-based containers. Hope this can help contributors be more efficient on triaging prod issues and developing new features.

**Comment by yuwenma** [comment]
@yujuhong Do you mind sharing more context about the debug container here?

**Comment by yujuhong** [comment]
@verb is working on debug containers and the plan is to have alpha with 1.15.

Tracking issue: https://github.com/kubernetes/enhancements/issues/277
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190212-ephemeral-containers.md

**Comment by kfox1111** [comment]
Until debug containers, I've been using this:
https://github.com/pnnl-miscscripts/miscscripts/tree/master/bin

**Comment by verb** [comment]
Since we've been working on this since before distroless containers were called distroless containers, our original feature request #27140 is probably difficult to discover. I've updated #27140 to refer to distroless explicitly and will close this as a duplicate.

Thanks for your feature request, we also think it's important. :+1:

/assign @verb
/close

**Comment by yuwenma** [comment]
> Since we've been working on this since before distroless containers were called distroless containers, our original feature request #27140 is probably difficult to discover. I've updated #27140 to refer to distroless explicitly and will close this as a duplicate.
> 
> Thanks for your feature request, we also think it's important. 👍
> 
> /assign Lee Verberne
> /close

Thanks Lee (and Yu-Ju)! I'll refer to #27140 for future conversations. This debugging tool is really important and helpful to rebasing distroless images.
