### ISSUE TITLE
Pod reflector getting delete events with nil object

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#76624]
**What happened**:

We are seeing nil objects on pod DELETE watch events in the reflector used by the pod cache of the apiserver. When this happens, the reflector is unable to process the delete event and does not remove the object from its cache. The error handling is [here](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L343). Note that the reflector does not re list in this scenario, so a malformed delete event will cause it to *never* remove the object from its cache.

The impact of this is pretty severe on our cluster, we have a very high pod churn rate (hundreds per minute). When this happens we end up with informer clients of the impacted apiserver believing (correctly from their standpoint) that hundreds of pods exist that no longer do. In particular this has had very negative effects on our scheduling, leading to starvation.

To investigate why the object on the event is nil, we deployed a fork of the apiserver that logs additional metadata about the error when it occurs
1. The resource revision the modification occurred at
2. The raw bytes of the previous value
3. The etcd key that was deleted

Using these logs, we saw that the raw bytes of the previous value was indeed nil, meaning that the etcd client indeed had the [prevValue](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/etcd3/event.go#L27) as nil, meaning that I believe the etcd client itself is returning the preKey with a nil value. Furthermore I confirmed that these delete events were extremely delayed and were showing us a delete that occurred at a resource version that was *smaller* than a resource version that had been *compacted*. This happens thousands of times when this issue repros, here is an example of the order of events for one pod
```
2019-04-12 17:56:19.496: log from fork: etcd: starting compacted rev (4488890661), endpoints ([https://eu-west-1a.etcd.k8s.local:2379 https://eu-west-1b.etcd.k8s.local:2379 https://eu-west-1c.etcd.k8s.local:2379])
2019-04-12 17:56:30.074 log from fork: name: storage/cacher.go:/pods: expected type *core.Pod, but watch event object had type <nil>, event object watch.Event{Type:"DELETED", Object:runtime.Object(nil), Key:"/registry/pods/ns1/pod1", Value:[]uint8(nil), PrevValue:[]uint8(nil), Rev:4488792739, IsDeleted:true, IsCreated:false, ReturnLocation:1}
```
Compaction occurs at rev 4488890661, then 11 seconds later we get an event about a delete that happened at rev 4488792739 (note that it's smaller than what was just compacted). This race is not always so tight, there is another pod that the delete event was received minutes after it was presumably compacted.

I believe then that the root cause of the problem is that the pod deletion events are being sent extremely delayed from etcd. I'm not sure why this is the case though.

**How to reproduce it (as minimally and precisely as possible)**:

We have repro'd this issue a half dozen times, each time the issue occurred on a single apiserver about 10 minutes after a kube controller manager leader change. Soon after the new kube controller manager leader grabs the lock, it causes the apiserver it's hitting to get into this bad state. Changing the kube controller manager does not always cause this issue to happen. When this issue happens, load does go extremely high (close to 1 normalized) on the host running the impacted apiserver, notably network traffic received from etcd goes up considerably.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.4
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ip-10-0-2-34 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- We are running kubernetes in HA (5 master hosts that have each have a kubecontroller manager performing leader election and an apiserver)
- etcd version: v3.2.16

**Comment by ryanmcnamara** [comment]
A couple thoughts have have on remediation
1. In the event that the reflector sees a nil event, should it restart its list watch process? It seems to me that it can no longer guarantee that it has received all events up to a resource version it has processed, which is particularly bad for delete events
2. Is it possible to spread the load of kube controller manager across all apiservers? I believe this is not possible because the controllers use a shared client which multiplexes all grpc requests over a single tcp connection. If this issue is load related, which seems likely given the repro, I believe this may mitigate.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/73845 was picked into v1.12.6 and might be relevant

**Comment by liggitt** [comment]
was this a HA etcd cluster?

**Comment by ryanmcnamara** [comment]
@liggitt yes it was, cluster size of 3, during the issue the load goes up on the etcd instances, but not concerningly so

**Comment by liggitt** [comment]
The nil prevObject from etcd is alarming, and needs investigation/correction, but there are a few things we can do in the meantime to make ourselves more resilient:

On the server side, when parsing events from etcd3, we should not see a delete event with a nil prevvalue, and if we do, [parseEvent()](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/event.go#L50-L55) should return an error, and the [event loop](https://github.com/kubernetes/kubernetes/blob/99e61466ab694b3652db2c063b9996a5d324a57a/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L212-L214) should end the watch with an error

When the informer is watching, if it encounters a watch event it cannot understand, or cannot access metadata, or cannot update the store, I think it should exit the watch loop with an error. All the cases where we call utilruntime.HandleError in this loop I *think* should probably change to return an error that triggers restarting the watch:

https://github.com/kubernetes/kubernetes/blob/440d0862687c96f9dda7c4e0d8c5a4da380e89bf/staging/src/k8s.io/client-go/tools/cache/reflector.go#L342-L372

**Comment by ryanmcnamara** [comment]
@liggitt the server side changes you're proposing make sense to me, if you'd like I can make the change (at least to error on nil event in the etcd watcher) and test it out in production today.

**Comment by liggitt** [comment]
getting a fix started/tested would be great. I'd like @jpbetz to ack that we should never see a delete event from etcd without a prevValue present

**Comment by ryanmcnamara** [comment]
@liggitt took an initial stab: https://github.com/kubernetes/kubernetes/pull/76675

Splitting up the changes to 
1. Return an error on delete event parse with nil prevKV
2. Treat all unexpected states in the reflector as errors

The pr addresses 1

**Comment by jpbetz** [comment]
> getting a fix started/tested would be great. I'd like @jpbetz to ack that we should never see a delete event from etcd without a prevValue present

Looks like prevKV not being returned if the previous KV was compacted [was intentional](https://github.com/etcd-io/etcd/blob/cca0d5c1bed134ac30e1354241f7655d2a118db4/etcdserver/etcdserverpb/rpc.proto#L695-L697):
```proto
// If prev_kv is set, created watcher gets the previous KV before the event happens.
// If the previous KV is already compacted, nothing will be returned.
bool prev_kv = 6;
```

But the behavior is surprising, so let's discuss it with the etcd devs: https://github.com/etcd-io/etcd/issues/10681

I agree with @liggitt that closing the current watch and then start a new watch would be a reasonable way to mitigate this.

**Comment by markyjackson-taulia** [comment]
@jpbetz @deads2k Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 18. Is this issue still intended for 1.17?

**Comment by tedyu** [comment]
How about the following change (w.r.t. https://github.com/kubernetes/kubernetes/issues/76624#issuecomment-483724336) ?
```
diff --git a/staging/src/k8s.io/client-go/tools/cache/reflector.go b/staging/src/k8s.io/client-go/tools/cache/reflector.go
index 62749ed7d3..8d7d73e0c2 100644
--- a/staging/src/k8s.io/client-go/tools/cache/reflector.go
+++ b/staging/src/k8s.io/client-go/tools/cache/reflector.go
@@ -365,20 +365,17 @@ loop:
                        }
                        if r.expectedType != nil {
                                if e, a := r.expectedType, reflect.TypeOf(event.Object); e != a {
-                                       utilruntime.HandleError(fmt.Errorf("%s: expected type %v, but watch event object had type %v", r.name, e, a))
-                                       continue
+                                       return fmt.Errorf("%s: expected type %v, but watch event object had type %v", r.name, e, a)
                                }
                        }
                        if r.expectedGVK != nil {
                                if e, a := *r.expectedGVK, event.Object.GetObjectKind().GroupVersionKind(); e != a {
-                                       utilruntime.HandleError(fmt.Errorf("%s: expected gvk %v, but watch event object had gvk %v", r.name, e, a))
-                                       continue
+                                       return fmt.Errorf("%s: expected gvk %v, but watch event object had gvk %v", r.name, e, a)
                                }
                        }
                        meta, err := meta.Accessor(event.Object)
                        if err != nil {
-                               utilruntime.HandleError(fmt.Errorf("%s: unable to understand watch event %#v", r.name, event))
-                               continue
+                               return fmt.Errorf("%s: unable to understand watch event %#v", r.name, event)
                        }
                        newResourceVersion := meta.GetResourceVersion()
                        switch event.Type {
```

**Comment by markyjackson-taulia** [comment]
@jpbetz @deads2k A kind reminder that code freeze for this release is on November 14. Is this issue still intended for 1.17?
--

**Comment by markyjackson-taulia** [comment]
@jpbetz @deads2k thoughts on moving this to v1.18 milestone? Code freeze is 11/14. A decision will need to be made by latest this coming Sunday 11/10

**Comment by markyjackson-taulia** [comment]
I have had no response after several tries, moving to milestone v1.18
 /milestone v1.18

**Comment by markyjackson-taulia** [comment]
I have had no response after several tries, moving to milestone v1.18

**Comment by liggitt** [comment]
The server-side fix in https://github.com/kubernetes/kubernetes/pull/76675 (to drop a watch if a delete event is received with a nil PrevKV) is available in all supported kube-apiserver versions (1.15.0+), closing this

/close
