### ISSUE TITLE
Deprecate kubelet cAdvisor-based endpoints

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#76660]
The cAdvisor port, which exposed the raw cAdvisor UI & API was removed in Kubernetes 1.12.

Now, we should also begin the deprecation process for the Kueblet API endpoints that are backed by the cAdvisor API. These are legacy endpoints, that expose undocumented APIs that don't conform to Kubernetes API standards. They no longer have any internal usage, as we moved core components to the summary API, and soon to the core metrics API. The cAdvisor APIs also tie us to cAdvisor internally, which we would eventually like to move to an implementation detail.

The endpoints I propose deprecating, and eventually removing are:
- `/spec`
- `/stats/*` _except_ `/stats/summary`
- `/metrics/cadvisor`

/milestone v1.15
/assign @tallclair @dashpole 
/sig node
/priority important-longterm

**Comment by tallclair** [comment]
Based on the [Kubernetes Deprecation Policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior), I think this needs to be rolled out over 1 year.

Proposal:

1. [v1.15] Add a flag: `--enable-cadvisor-endpoints`, default to true, mark as deprecated, document deprecation plan in flag description.
2. [v1.17] Default the flag to disabled.
3. [v1.19] Remove the flag and endpoints.

**Comment by dims** [comment]
@tallclair are we trying to do the same in this? https://github.com/kubernetes/kubernetes/issues/68522

**Comment by tallclair** [comment]
Ah, thanks for linking the two. This is a subset of the action items from that bug. I'll add it to the description.

**Comment by tallclair** [comment]
Although, the proposed timeline is different.... I'll sync up with @dashpole when he's back in office. Maybe this is a duplicate?

**Comment by tallclair** [comment]
Followed up with @dashpole, and we agreed on this timeline/proposal.

**Comment by tallclair** [comment]
David merged this proposal into https://github.com/kubernetes/kubernetes/issues/68522, so closing this as a duplicate.

**Comment by r-dilip** [comment]
where else can we get the node capacity locally without making an remote call to either the metrics server or the API Server. 
Previously, we were making a call to the /spec/ endpoint and parsing the CPU and Memory Capacity from the response, like below. 

root@omsagent-rs-6bcfff79fb-bt476:/opt/microsoft/omsagent/plugin# curl http://$NODE_IP:10255/spec/
{
  "num_cores": 2,
  "cpu_frequency_khz": 2394455,
  "memory_capacity": 7284559872,
  "hugepages": [
   {
    "page_size": 1048576,
    "num_pages": 0
   },


Is there an alternative to getting the same information without querying the API server or the metrics server once /spec/ endpoint is deprecated?

**Comment by tallclair** [comment]
Why is it a problem to get the information from the API server?
