### ISSUE TITLE
Move each file in test/e2e to it's own package

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#7666]
e2e tests are becoming a rats nest, all in one huge package.
Start by this trivial refactoring to prevent the situation from getting worse.

**Comment by ixdy** [comment]
Somewhat related to #16094. Is this still something we think we should pursue? @kubernetes/goog-testing @kubernetes/sig-testing

**Comment by kargakis** [comment]
I guess this should be a cross-sig effort. @kubernetes/sig-apps-misc we should start with our workload tests.

**Comment by wanghaoran1988** [comment]
I am working on the workload parts, pr: https://github.com/kubernetes/kubernetes/pull/46425

**Comment by spiffxp** [comment]
/close
I'm closing this in favor of #42670
