### ISSUE TITLE
Bogus kubeconfig prevents "kubectl version --client=true" returning client version

### ISSUE THREAD

**Issue by stuart-mclaren** [kubernetes/kubernetes#76661]
**What happened**:
A kubeconfig error prevented getting the client version

$ kubectl version --client=true
Error in configuration: 
* unable to read client-cert ...client.crt for minikube due to open .../client.crt: no such file or directory

**What you expected to happen**:
$ kubectl version --client=true
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-01-eks", GitCommit:"3560dff069d192fad3f14aa524cda6ecc73c309f", GitTreeState:"clean", BuildDate:"2019-03-27T04:30:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**How to reproduce it (as minimally and precisely as possible)**:
Edit kubeconfig to point to non-existant cert file

kubectl version --client=true

**Environment**:
- Kubernetes version (use `kubectl version`):

1.11.0 and later

**Comment by stuart-mclaren** [comment]
https://github.com/kubernetes/kubernetes/pull/76662

**Comment by neolit123** [comment]
i'm sorry but 1.10 and 1.11 are no longer supported.
please upgrade to 1.12 at the minimum.

if the problem persist re-open this ticket.
/sig cli
/close

**Comment by neolit123** [comment]
actually you have a PR for this in master.
/reopen

**Comment by kragniz** [comment]
Fixed in #76662
/close
