### ISSUE TITLE
[Failing Test] testing/load/config.yaml failing on master-informing

### ISSUE THREAD

**Issue by jimangel** [kubernetes/kubernetes#76670]
**Which jobs are failing**:

- `ci-kubernetes-e2e-gce-scale-performance`

**Which test(s) are failing**:

- `testing/load/config.yaml`

**Since when has it been failing**:

- Flaking since 02-21
- Failing since 04-10

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-performance

**Reason for failure**:

`[measurement call APIResponsiveness - APIResponsiveness error: top latency metric: there should be no high-latency requests, but: [got: {Resource:pods Subresource: Verb:LIST Scope:cluster Latency:{Perc50:239.829ms Perc90:7.420534s Perc99:14.532657s} Count:132}; expected perc99 <= 10s got: {Resource:serviceaccounts Subresource:token Verb:POST Scope:namespace Latency:{Perc50:4.129ms Perc90:18.398ms Perc99:1.55848s} Count:89}; expected perc99 <= 1s]]`

**Anything else we need to know**:

/sig testing
/kind failing-test
/kind flake
/priority important-soon
/milestone v1.15

/cc @alejandrox1 @smourapina @rarchk @alenkacz

**Comment by smourapina** [comment]
Commit that broke this test was [aa7406460](https://github.com/kubernetes/kubernetes/commit/aa7406460), corresponding to [PR #75217](https://github.com/kubernetes/kubernetes/pull/75217).
Assigning /sig api-machinery

**Comment by alejandrox1** [comment]
Assigning the api-machinery chairs to get some eyes on this:
/assign @lavalamp @deads2k

We need some help getting started on this.

**Comment by alejandrox1** [comment]
Been looking around and similar failures showed up on https://github.com/kubernetes/kubernetes/issues/75284

**Comment by wojtek-t** [comment]
This is a duplicate of couple other bugs for regressions we have:
https://github.com/kubernetes/kubernetes/issues/75833
https://github.com/kubernetes/kubernetes/issues/76579
https://github.com/kubernetes/kubernetes/issues/77127

**Comment by wojtek-t** [comment]
All of them are under investigation or in-resolution.

**Comment by alejandrox1** [comment]
Within ci-kubernetes-e2e-gce-scale-performance, the following test have been failing

* testing/load/config.yaml
* testing/density/config.yaml
* ClusterLoaderV2

At this time, testing/load/config.yaml stopped failing with the last run being succesful.
[Latest run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1129295897142759426).

**Comment by wojtek-t** [comment]
We're stably green for the last  week and a half since we fixed the regression. Closing.
