### ISSUE TITLE
Pod request objects generated from Job's don't have "metadata.name" field set during Admission Review

### ISSUE THREAD

**Issue by phenixblue** [kubernetes/kubernetes#76680]
**What happened**:

Pod request objects generated by a Job are sent to admission controllers without the `metadata.name` field being specified. 

**What you expected to happen**:

I see the `metadata.generateName` field, but would expect the name to have been generated prior to the object being submitted to the admission controller similar to how deployments seem to handle it.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy an admission controller that targets `Pod` objects for `Create` and `Update` actions. - [example](https://github.com/phenixblue/imageswap-webhook) 
- Create a Kubernetes job
- Watch for failures for the incoming pod request objects generated by the job (`kubectl logs` on the Webhook pod)

Failures are centered on defining a variable from the expected workload by referencing `request.object.metadata.name`

**Anything else we need to know?**:

If you use the example Webhook mentioned above, add `pprint(request_info)` above the variable definitions on line 18  in the `app/imageswap-webhook-deploy.py` file to print the entire request object as it comes into the webhook server

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.7
- Cloud provider or hardware configuration: PKS on VMware

**Comment by neolit123** [comment]
@kubernetes/cloud-provider-vsphere-maintainers 
/sig cloud-provider

**Comment by liggitt** [comment]
name generation happens as part of storage, in order to be able to retry if a conflict is detected.

the generated name is available to validating webhooks (which run after all modifications to the object are complete), but not to mutating webhooks

/close
