### ISSUE TITLE
Generated clients do not include limit and continue parameters for listing custom resources

### ISSUE THREAD

**Issue by moduspwnens** [kubernetes/kubernetes#76708]
The generated client methods for listing Kubernetes native resources include the "limit" and "continue" parameters, but the specs for listing custom resources do not.

See below docs for the Python and Java clients (e.g.) listing namespaced pods:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod
https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md#listNamespacedPod

And the same clients' docs for listing namespaced custom objects:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#list_namespaced_custom_object
https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CustomObjectsApi.md#listNamespacedCustomObject

This results in the client appearing to not support paginating results when listing custom resources, which is likely unintended because the API seems to support it just like it would for any other resource. My expectation is that the generated clients would support the "limit" and "continue" parameters for paging when listing custom resources.

I was unable to figure out if the cause is the result of something in this project's repo, or the kube-openapi project, or something else.

**Comment by Rstar1998** [comment]
@brendandburns any update on this ? 
Any support for paginated response of methods `list_namespaced_custom_object` ?
