### ISSUE TITLE
cgroup driver "systemd" does not work with custom CPU CFS quota period

### ISSUE THREAD

**Issue by ghouscht** [kubernetes/kubernetes#76704]
**What happened**:
I installed a cluster with kubeadm (1.14.1) and cgroup driver `systemd` with a custom cpu cfs quota period. Pods are unable to start with the following message:
```
Error: failed to start container "kube-flannel": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 5000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-pode7dac811_5d23_11e9_8ff8_005056935735.slice/docker-kube-flannel.scope/cpu.cfs_period_us: invalid argument\\\"\"": unknown
```
If I understand the [cgroup-drivers documentation](https://kubernetes.io/docs/setup/cri/#cgroup-drivers) correct, it's recommended to use the `systemd` driver on a systemd managed OS, but this currently blocks us to respect this recommendation. 

**Please note: `cgroupfs` driver is not affected of this particular problem. If we switch to use `cgroupfs` as driver everything works as expected.**

**What you expected to happen**:
Pods to start with a cfs quota period of 5ms set.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup docker on a systemd managed system with the following config in `/etc/docker/daemon.json`
```
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "bip": "10.127.1.1/24",
  "log-opts": {
    "max-size": "2g"
  },
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
```
(relevant part is the `exec-opts` setting)

2. Setup a k8s cluster with kubeadm with at least the following special config
```
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  CustomCPUCFSQuotaPeriod: true
cpuCFSQuotaPeriod: 5ms
```

3. Try to run a pod.

**Anything else we need to know?**:
`docker info` output:
```
Containers: 19
 Running: 16
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66GiB
Name: e1-k8s-mlsu105
ID: DUMM:WJD4:PCRQ:Z7QH:ZOO5:URCB:BWO4:K2BH:DB7D:7SFK:6CVU:5HYQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

`/var/lib/kubelet/kubeadm-flags.env`content:
```
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni 
```

related issue: https://github.com/kubernetes/kubernetes/issues/72878 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration: on-premises
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
- Kernel (e.g. `uname -a`):
```
Linux e1-k8s-mlsu105 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm 1.14.1
- Others: -

**Comment by yanghaichao12** [comment]
In addition to this, are there other pods with this problem? i'v tried just now and nothing is wrong:
`Containers: 11
 Running: 6
 Paused: 0
 Stopped: 5
Images: 10
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
`
`
root      7148     1  1 15:16 ?        00:00:13 /usr/bin/kubelet **--cgroup-driver=systemd** --v=0 --hostname-override=10.46.177.110 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.dynamicConfig --log-dir=/etc/kubernetes/logs --node-ip=10.46.177.110 --pod-infra-container-image=usee/pause-amd64:3.1 --network-plugin=cni --logtostderr=false --allow-privileged=true --minimum-image-ttl-duration=2m --maximum-dead-containers=50 --maximum-dead-containers-per-container=1 --minimum-container-ttl-duration=1m --node-status-update-frequency=20s
root      8213 23141  0 15:28 pts/8    00:00:00 grep --color=auto kubelet
`

**Comment by ghouscht** [comment]
Yes every pod which has resources configured fails. Forgot to mention, that you need to set limits and/or requests in your deployment to see the described behaviour. Pods with no limits/requests set are not affected (makes sense, as the kubelet does not need to write to the cgroup config files for those pods)

Example resources configuration for a deployment:
```yaml
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
```

**Comment by yanghaichao12** [comment]
below is my definition，it still work well. 
```json
"spec": {
        "containers": [
            {
                "command": [
                    "sleep",
                    "86400"
                ],
                "env": [
                    {
                        "name": "ENV_TEST_1",
                        "value": "env_test_1"
                    },
                    {
                        "name": "ENV_TEST_2",
                        "value": "env_test_22222"
                    }
                ],
                "image": "ubuntu:v1",
                "imagePullPolicy": "IfNotPresent",
                "name": "ubuntu-test",
                "ports": [
                    {
                        "containerPort": 22,
                        "protocol": "TCP"
                    }
                ],
                "resources": {
                    "limits": {
                        "cpu": "100m",
                        "memory": "50Mi"
                    },
                    "requests": {
                        "cpu": "100m",
                        "memory": "50Mi"
                    }
                },

```

I think this error is caused by docker, not kubelet. and you can try like this and see what happens：
```shell
docker run -d --name web41 --cpu-quota 25000 --cpu-period 100 --cpu-shares 30 training/webapp python app.py
```

**Comment by zq-david-wang** [comment]
Could be a systemd issue, you may try upgrading your systemd. I am running centos7 with systemd219, everything works fine.  (I think you can verify it by manually writing to some cpu.cfs_period_us under systemd managed cgroup directory, e.g. "echo 5000 > /sys/fs/cgroup/cpu,cpuacct/system.slice/system-getty.slice/cpu.cfs_period_us", if it yield "invalid argument", most likely your systemd does not initialize something properly.)

> # systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**Comment by ghouscht** [comment]
Plain docker without k8s seems to be ok:

```
# docker run -d --name dummy --cpu-quota 25000 --cpu-period 5000 --cpu-shares 30 rhel:7 sleep infinity
0020f3f02e8b896e1b485e321b706d5344d22a94fbb321ccc7cce417352b026a
```

Taking a look at the corresponding cgroup:
```
# cat /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-0020f3f02e8b896e1b485e321b706d5344d22a94fbb321ccc7cce417352b026a.scope/cpu.cfs_period_us
5000
```

systemd version:
```
# systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

Manually writing into a cgroup also works:
```
# echo 5000 > /sys/fs/cgroup/cpu,cpuacct/system.slice/system-getty.slice/cpu.cfs_period_us
# cat /sys/fs/cgroup/cpu,cpuacct/system.slice/system-getty.slice/cpu.cfs_period_us
5000
```

So seems like it's not a docker nor systemd problem (probably a combination of them but k8s definitely has an impact).

**Comment by zq-david-wang** [comment]
@ghouscht  could you try with container limit higher than 200m?  If you set cpu period to 5ms and limit to 100m,  the cpu quota  would be 5ms * (100m/1000m) = 0.5ms < 1ms, this would cause cgroup error when writing cpu quota.  
```
# echo 500 > /sys/fs/cgroup/cpu,cpuacct/system.slice/system-getty.slice/cpu.cfs_quota_us 
-bash: echo: write error: Invalid argument
```
And can  you make sure that you can run your pod with 100m limit and 5ms cpu period with cgroupfs? That dose not make sense

But considering that kubelet reporting error for writing cpu_period, not cpu_quota,  it would be some bug in kubelet:
According to linux kernel code, if current cgroup node's quota is larger than its parent node, it would yield "-EINVAL"
https://github.com/torvalds/linux/blob/8c2ffd9174779014c3fe1f96d9dc3641d9175f00/kernel/sched/core.c#L6781

This means that if kubelet did not setup quota/period for pod/container cgroup node in a proper sequence, it would have entered an invalid state where parent cgroup node have a cpu quota ratio smaller than child cgroup node.

Just speculating here, trying to read into kubelet code.....

**Comment by zq-david-wang** [comment]
I can reproduce it now.
Just set --cpu-cfs-quota-period to a value smaller than systemd default 100ms.

**Comment by zq-david-wang** [comment]
@szuecs

**Comment by ghouscht** [comment]
cgroupfs setup with the exact same configuration works: 
```
# docker info | grep Cgroup
Cgroup Driver: cgroupfs

# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=cgroupfs --network-plugin=cni
```

```
# k describe po kube-flannel-ds-amd64-pprnp
Name:               kube-flannel-ds-amd64-pprnp
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               e1-k8s-mlsu105/172.16.177.17
Start Time:         Wed, 24 Apr 2019 12:16:17 +0200
Labels:             app=flannel
                    controller-revision-hash=7454874746
                    pod-template-generation=1
                    tier=node
Annotations:        <none>
Status:             Running
IP:                 172.16.177.17
Controlled By:      DaemonSet/kube-flannel-ds-amd64
Init Containers:
  install-cni:
    Container ID:  docker://ed6c28e41ca52d2ef5a192d61724214414fd289aa59885d6211f6a0cb01ce58d
    Image:         quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64
    Image ID:      docker-pullable://quay-docker-remote.repo.pnet.ch/coreos/flannel@sha256:7806805c93b20a168d0bbbd25c6a213f00ac58a511c47e8fa6409543528a204e
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      -f
      /etc/kube-flannel/cni-conf.json
      /etc/cni/net.d/10-flannel.conflist
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 24 Apr 2019 12:16:24 +0200
      Finished:     Wed, 24 Apr 2019 12:16:24 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/cni/net.d from cni (rw)
      /etc/kube-flannel/ from flannel-cfg (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flannel-token-cnvdl (ro)
Containers:
  kube-flannel:
    Container ID:  docker://38f572dd43b4160afa7bddc7934cfcf56fe75ce077a7ac0b638407da50116521
    Image:         quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64
    Image ID:      docker-pullable://quay-docker-remote.repo.pnet.ch/coreos/flannel@sha256:7806805c93b20a168d0bbbd25c6a213f00ac58a511c47e8fa6409543528a204e
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/bin/flanneld
    Args:
      --ip-masq
      --kube-subnet-mgr
    State:          Running
      Started:      Wed, 24 Apr 2019 12:16:25 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_NAME:       kube-flannel-ds-amd64-pprnp (v1:metadata.name)
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /etc/kube-flannel/ from flannel-cfg (rw)
      /run/flannel from run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flannel-token-cnvdl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  run:
    Type:          HostPath (bare host directory volume)
    Path:          /run/flannel
    HostPathType:
  cni:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  flannel-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-flannel-cfg
    Optional:  false
  flannel-token-cnvdl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flannel-token-cnvdl
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  beta.kubernetes.io/arch=amd64
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type    Reason     Age    From                     Message
  ----    ------     ----   ----                     -------
  Normal  Scheduled  2m22s  default-scheduler        Successfully assigned kube-system/kube-flannel-ds-amd64-pprnp to e1-k8s-mlsu105
  Normal  Pulling    2m21s  kubelet, e1-k8s-mlsu105  Pulling image "quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64"
  Normal  Pulled     2m17s  kubelet, e1-k8s-mlsu105  Successfully pulled image "quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64"
  Normal  Created    2m16s  kubelet, e1-k8s-mlsu105  Created container install-cni
  Normal  Started    2m15s  kubelet, e1-k8s-mlsu105  Started container install-cni
  Normal  Pulled     2m15s  kubelet, e1-k8s-mlsu105  Container image "quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64" already present on machine
  Normal  Created    2m15s  kubelet, e1-k8s-mlsu105  Created container kube-flannel
  Normal  Started    2m14s  kubelet, e1-k8s-mlsu105  Started container kube-flannel
```

resulting cgroup configuration for this pod:
```
# cat /sys/fs/cgroup/cpu,cpuacct/kubepods/podffa9bc10-6679-11e9-b904-005056935735/cpu.cfs_quota_us
1000

# cat /sys/fs/cgroup/cpu,cpuacct/kubepods/podffa9bc10-6679-11e9-b904-005056935735/cpu.cfs_period_us
5000
```

**Comment by yanghaichao12** [comment]
@zq-david-wang i've set  --cpu-cfs-quota-period=50ms，every is okay，that's my configuration:

```shell
root@dev-lzx:/sys/fs/cgroup/cpu/kubepods.slice/kubepods-podad1bff00_667c_11e9_aa8d_fa163e87720d.slice# cat cpu.cfs_quota_us
100000
root@dev-lzx:/sys/fs/cgroup/cpu/kubepods.slice/kubepods-podad1bff00_667c_11e9_aa8d_fa163e87720d.slice# cat cpu.cfs_period_us
50000
root@dev-lzx:/sys/fs/cgroup/cpu/kubepods.slice/kubepods-podad1bff00_667c_11e9_aa8d_fa163e87720d.slice# ps -ef|grep kubelet
root     30702     1  1 18:30 ?        00:00:07 /usr/bin/kubelet --cgroup-driver=systemd --v=0 --hostname-override=10.46.177.110 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.dynamicConfig --log-dir=/etc/kubernetes/logs --node-ip=10.46.177.110 --pod-infra-container-image=usee/pause-amd64:3.1 --network-plugin=cni --logtostderr=false --allow-privileged=true --minimum-image-ttl-duration=2m --maximum-dead-containers=50 --maximum-dead-containers-per-container=1 --minimum-container-ttl-duration=1m --node-status-update-frequency=20s --cpu-cfs-quota-period=50ms


```


could you provide more information about how to reproduce it?

**Comment by ghouscht** [comment]
And back to systemd as cgroup driver with increased limits/requests (500m):

```
# k describe po kube-flannel-ds-amd64-6j2q6
...
    Limits:
      cpu:     500m
      memory:  50Mi
    Requests:
      cpu:     500m
      memory:  50Mi
    Environment:
      POD_NAME:       kube-flannel-ds-amd64-6j2q6 (v1:metadata.name)
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /etc/kube-flannel/ from flannel-cfg (rw)
      /run/flannel from run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from flannel-token-tfg9k (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  run:
    Type:          HostPath (bare host directory volume)
    Path:          /run/flannel
    HostPathType:
  cni:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  flannel-cfg:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-flannel-cfg
    Optional:  false
  flannel-token-tfg9k:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flannel-token-tfg9k
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  beta.kubernetes.io/arch=amd64
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                From                     Message
  ----     ------     ----               ----                     -------
  Normal   Scheduled  92s                default-scheduler        Successfully assigned kube-system/kube-flannel-ds-amd64-6j2q6 to e1-k8s-mlsu105
  Normal   Pulled     91s                kubelet, e1-k8s-mlsu105  Container image "quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64" already present on machine
  Normal   Created    91s                kubelet, e1-k8s-mlsu105  Created container install-cni
  Normal   Started    91s                kubelet, e1-k8s-mlsu105  Started container install-cni
  Warning  BackOff    15s (x6 over 89s)  kubelet, e1-k8s-mlsu105  Back-off restarting failed container
  Normal   Pulled     2s (x5 over 91s)   kubelet, e1-k8s-mlsu105  Container image "quay-docker-remote.repo.pnet.ch/coreos/flannel:v0.11.0-amd64" already present on machine
  Normal   Created    2s (x5 over 91s)   kubelet, e1-k8s-mlsu105  Created container kube-flannel
  Warning  Failed     2s (x5 over 91s)   kubelet, e1-k8s-mlsu105  Error: failed to start container "kube-flannel": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 5000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-pod7a652c85_667c_11e9_89c4_005056935735.slice/docker-kube-flannel.scope/cpu.cfs_period_us: invalid argument\\\"\"": unknown
```

**Comment by ghouscht** [comment]
@yanghaichao12 we've set the quota-period even lower to 5ms.

**Comment by zq-david-wang** [comment]
@yanghaichao12 you need to enable the feature gate for CFSQUOTAPeriod --feature-gates=CustomCPUCFSQuotaPeriod=true

**Comment by zq-david-wang** [comment]
> # cat /sys/fs/cgroup/cpu,cpuacct/kubepods/podffa9bc10-6679-11e9-b904-005056935735/cpu.cfs_quota_us
> 1000
> 
> # cat /sys/fs/cgroup/cpu,cpuacct/kubepods/podffa9bc10-6679-11e9-b904-005056935735/cpu.cfs_period_us
> 5000
> ```

@ghouscht it seems code for cgroupfs would round up value lower than 1ms to 1ms.  (a 5000 period with cpu limit set to 100m should have quota set to 500)

**Comment by zq-david-wang** [comment]
I think the issue is in runc,   trying to make code change and tests, should have a easy fix.

**Comment by yanghaichao12** [comment]
@ghouscht yes, 17.03.2-ce:
```shell
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:07:48 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

and my kernel :

```shell
root@dev-lzx:/sys/fs/cgroup/cpu/kubepods.slice/kubepods-podad1bff00_667c_11e9_aa8d_fa163e87720d.slice# uname -a
Linux dev-lzx 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yanghaichao12** [comment]
@ghouscht have you ever checked it in other docker version? and how about the result?

**Comment by yanghaichao12** [comment]
@zq-david-wang  my configuration have come into effect if you notice that：

```shell
cat cpu.cfs_period_us
50000
```
so, how can i reproduce the bug? or which versions of runc this error can occurs   in?

**Comment by zq-david-wang** [comment]
@yanghaichao12  sorry I did not read through carefully.
Could you check whether your docker is using systemd cgroup driver as well? what your `docker info` yields?

The problem with systemd is that when creating systemd cgroup, the period is always 100ms, and when update the quota/period, a period of value less than 100ms would cause kernel error because runc would set period first. And cgroupfs can directly set the period.

**Comment by zq-david-wang** [comment]
There is a easy way to reproduce this. (I was using ubuntu to make the test)
First make sure your docker use systemd cgroup griver.
Then set some limit to your systemd slice.
sudo bash -c "echo 800000 > /sys/fs/cgroup/cpu,cpuacct/system.slice/cpu.cfs_quota_us"

Then run a docker with period over 8 times less than default period value. (I am using 1000, which is 100 times less than 100000) 
$ docker run --cpu-quota 1000 --cpu-period 1000 --rm -it ubuntu bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 1000 to cpu.cfs_period_us: write /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-a0441892cd9c41e5f2ffb0c2493282e9fc04befb107a6fbcd1d71994230c28bc.scope/cpu.cfs_period_us: invalid argument\\\"\"": unknown.


When using systemd, a quota/period change would involve 2 steps, first create a systemd slice using systemd rules, and then runc would call a Set function to change the quota/period according. But under this situation, the order of setting quota and period matters.

**Comment by yanghaichao12** [comment]
@zq-david-wang as you see, my driver is systemd
```shell
root@dev-lzx:~# docker info|grep -i cgroup
WARNING: No swap limit support
Cgroup Driver: systemd

```
and my period is 50000(50ms）， it‘s less than 100ms
```shell
cat cpu.cfs_period_us
50000
```
but why i can't get it?  is there something i missed?

**Comment by zq-david-wang** [comment]
@yanghaichao12  could you try the procedure I mentioned above? If you have make manual changes to your cgroup parent node, better reset those back (or just reboot)

To make sure whether your docker is using systemd driver,  run a new container can check whether its cgroup tree has a systemd signature , something like *.scope

**Comment by yanghaichao12** [comment]
@zq-david-wang no， i never have made it manually. i just set   --cpu-cfs-quota-period less than 100ms and modify "resources" requested by pods. and i didn't use "docker run ....." 
 i guess systemd driver take effect:
```shell

root@dev-lzx:/sys/fs/cgroup/cpu/kubepods.slice/kubepods-podad1bff00_667c_11e9_aa8d_fa163e87720d.slice# ls -lt
drwxr-xr-x 2 root root 0 4月  25 18:35 docker-0dea40a4ec0f315c781b487ab07a805dd0a999297420206cb51513ac74338c03.scope
drwxr-xr-x 2 root root 0 4月  24 18:35 docker-ab9adc58978faf18c79259231993a91a872c541104979e2692159115db40d30e.scope

```

**Comment by zq-david-wang** [comment]
@yanghaichao12 
https://github.com/opencontainers/runc/commit/c44aec9b23f89ca40434fe5f86693870ef3bf9f9
This commit, "on Feb 24, 2017", using systemd to create and config cpu quota for child node,  it may not  be  in the runc binary with your docker-17.03 .
Before the commit, the initial value for quota/period is the same as cgroupfs.

THis maybe the reason why you could not reproduce it. Why not upgrade your docker.....

**Comment by yanghaichao12** [comment]
@zq-david-wang okey, i think that's the reason, thx a lot!

**Comment by derekwaynecarr** [comment]
note: systemd required changes to make this work, which is why the feature was still alpha.  upstream systemd added the field in july 2018.

see:
https://github.com/systemd/systemd/issues/9081
https://github.com/systemd/systemd/pull/9594

**Comment by ghouscht** [comment]
Going to close this, as it's not a k8s related issue.
Thx @derekwaynecarr for referencing the systemd issues.
