### ISSUE TITLE
Add redirects to godoc.org for k8s.io vanity URLs

### ISSUE THREAD

**Issue by thaJeztah** [kubernetes/kubernetes#76706]
**What would you like to be added**:

Visiting the vanity URLs used to import kubernetes Go packages (for example [`k8s.io/client-go`](https://kubernetes.io/client-go) will make me arrive at a 404 on the website:

<img width="459" alt="Screenshot 2019-04-17 at 14 37 00" src="https://user-images.githubusercontent.com/1804568/56288098-4cfbe300-611e-11e9-8035-f68cf01eb444.png">

It's common to redirect those URLs (when used without `?go-get=1`) to the corresponding godoc.org page (https://godoc.org/github.com/kubernetes/client-go)

**Why is this needed**:

When developing with the kubernetes libraries, developers may want to read the reference documentation, or locate the corresponding source-code on GitHub

**Comment by thaJeztah** [comment]
@kubernetes/sig-docs-feature-requests

**Comment by thaJeztah** [comment]
Hm, I should probably have opened this in https://github.com/kubernetes/website. I just spotted a redirects file there; https://github.com/kubernetes/website/blob/master/static/_redirects

**Comment by thaJeztah** [comment]
Opened a pull request in the website repository; https://github.com/kubernetes/website/pull/13861

**Comment by dims** [comment]
Thanks @thaJeztah !
