### ISSUE TITLE
go mod import of kubernetes modules, golang.org/x/text is referenced to a non-existent version

### ISSUE THREAD

**Issue by dionysius** [kubernetes/kubernetes#76700]
Hi, I'm coming from https://github.com/golang/go/issues/31487#issuecomment-484005323

Because this issue applies to probably all repos of kubernetes (seen here, in apimachinery, ...), I allow me to post here. For some reason, your `go.mod` file - currently in `master` - references `golang.org/x/text` with the tag `v0.3.1`, but there is no such tag there (see issue above for details)

**What happened**:
in my project
```
$ gotip mod tidy
go: finding golang.org/x/text/transform latest
go: finding golang.org/x/text/unicode/norm latest
go: finding golang.org/x/text/unicode latest
go: github.com/dionysius/go-issue-31487 imports
        github.com/spf13/viper imports
        github.com/spf13/afero imports
        golang.org/x/text/transform: package provided by golang.org/x/text at latest version v0.3.0 but not at required version v0.3.1-0.20181227161524-e6919f6577db
```
(see issue above about what gotip is)

**What you expected to happen**:
no error

**How to reproduce it (as minimally and precisely as possible)**:
use the example project in the issue stated above

**Anything else we need to know?**:
I found the issue commit was: https://github.com/kubernetes/kubernetes/commit/55d52fd5c35351c221f055ab08f3855ab5782b0d#diff-37aff102a57d3d7b797f152915a6dc16L442

Otherwise I think not, just request/ask. I'm kinda curious where the tag v0.3.1 is coming from

Update: I'm still curious where the tag v0.3.1 is coming from, but [I can let that work out by `go get -m golang.org/x/text@master` myself](https://github.com/golang/go/issues/31487#issuecomment-484020406). So maybe this issue is not a bug, but I now am more confused...

**Comment by dims** [comment]
cc @liggitt

**Comment by liggitt** [comment]
It's actually `v0.3.1-0` which is go's way or expressing "a commit after v0.3.1 that is not on a tag. 

See https://tip.golang.org/cmd/go/#hdr-Pseudo_versions

/close
