### ISSUE TITLE
PKI creation using now.UTC breaks after system clock drift corrections

### ISSUE THREAD

**Issue by mikeparker** [kubernetes/kubernetes#76714]
We're tracking a rare bug in Docker Desktop where users are getting the error message:
`the certificate is not valid yet` (see: https://github.com/docker/for-win/issues/2913)

This can be reproduced by manually changing your system clock forwards and backwards, but we believe it can also occur naturally when a system clock drifts forwards and a reboot or other sync corrects the system clock backwards again. 

We're using the code here to generate our kubernetes certificates:
https://github.com/kubernetes/client-go/blob/master/util/cert/cert.go#L65
which uses `time.Now` and `NotBefore : now.UTC()`

Some options:
a) Switch away from this utility function and write our own code to provide similar functionality
b) Open a PR here to provide flexibility in the NotBefore time, either setting the NotBefore time to a long time ago (e.g. 1970), providing an optional grace period
c) Open a PR here to change the default NotBefore time to use a hard coded grace period or set start time in the past

WDYT?

**Comment by mikeparker** [comment]
From previous thread, @liggitt said:
> it looks like https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L249-L256 does client-side validation, which is problematic for the clock drift reasons mentioned. it should not.
> 
> it is also reasonable to allow _some_ buffer in the NotBefore time (c.f. https://github.com/kubernetes/client-go/blob/master/util/cert/cert.go#L95)

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle
/sig api-machinery

**Comment by neolit123** [comment]
/lifecycle frozen

> but we believe it can also occur naturally when a system clock drifts forwards and a reboot or other sync corrects the system clock backwards again.

did you confirm that this can happen naturally?

> which uses time.Now and NotBefore : now.UTC()

i think the logic there is pretty sane and i doubt changes will be accepted to it, by the owners of client-go.

if you want to get feedback on this the forums for that are the SIG API machinery meeting or slack channel (#sig-api-machinery).

**Comment by mikeparker** [comment]
> did you confirm that this can happen naturally?

Yes, users are getting the bug simply with day to day usage, they aren't manually changing their computer clock.

> i think the logic there is pretty sane and i doubt changes will be accepted to it, by the owners of client-go.

I'm unsure whats sane about it. Not accepting our own certificate because we're setting a NotBefore time based on the current value of the system clock which is known to be unreliable and then rejecting the certificate we just created due to a minor clock adjustment, does not seem sane to me.

It's like giving yourself a password thats only valid from now (e.g. 10am) and then locking yourself out because you adjust your own clock to 9:59am. Just set the password to be valid from 9am. Or yesterday. Or a year ago. Or don't put a constraint on the start time as it's known to be in the past anyway, I don't understand the benefit about being so specific about the NotBefore time, it just invites race conditions.

**Comment by neolit123** [comment]
> It's like giving yourself a password thats only valid from now (e.g. 10am) and then locking yourself out because you adjust your own clock to 9:59am

i'm surprised there are systems that do that. possibly other bad things can happen next to certificates being rejected.

**Comment by liggitt** [comment]
padding NotBefore to backdate it a small amount (e.g. an hour) seems reasonable to me

**Comment by mikeparker** [comment]
> padding NotBefore to backdate it a small amount (e.g. an hour) seems reasonable to me

Sounds good to me too!

**Comment by neolit123** [comment]
digging into old issues.
@mikeparker would you be able to PR client-go with this change?

**Comment by neolit123** [comment]
sending a PR for kubeadm to relax the client side validation (warnings instead of errors)
PRs for the client-go side are welcome, unless already fixed.

/remove-lifecycle frozen

**Comment by neolit123** [comment]
the related kubeadm change:
https://github.com/kubernetes/kubernetes/pull/94504
is merging and it will be in 1.20, but we have no plans to backport it to older releases.

/remove-sig cluster-lifecycle
