### ISSUE TITLE
SubjectAccessReview endpoint should exist for providers other than GKE explicitly

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#76726]
**What would you like to be added**:
The function `WaitForNamedAuthorizationUpdate` in `test/e2e/framework/auth/helpers.go` should check for GKE and allow a missing SubjectAccessReview endpoint. If we get a 404 on another provider an error should still be returned.

GKE doesn't enable the SAR endpoint.  Without this endpoint, we cannot determine if the policy engine has adjusted as expected.  In this case, we currently wait one second and hope it's up to date without returning an error and that it has adjusted as expected.

**Why is this needed**:
A 404 on that endpoint is not expected behavior for any provider other than GKE so it doesn't make any sense to implicitly allow 404s and *hope* that everything is ok. If it is a special, allowable, condition for GKE we should make that explicit in the code.

The problem with doing it now is that checking the provider requires access to the TestContext which forces us to import the entire `test/e2e/framework` package. This goes against the goal of #76206 

At the same time, we don't want to cause every test/caller of this to have to (1) know that GKE acts differently in this situation and code that one special path. This may be the lesser of the evils though, but regardless of how it is accomplished, at some point, the code should be validating this flow.

Open to other solutions to this; maybe a specific test to test this code path (in which case this helper can be assumed to not be responsible for it?) Not sure if that is considered sufficient as it creates an awkward coupling between a helper function's assumptions and the existence of particular test.

**Comment by cjcullen** [comment]
I think that comment no longer applies, and we can just remove that GKE special case. IIRC, GKE didn't initially enable serving the authorization.k8s.io group, but it does now.

**Comment by johnSchnake** [comment]
OK; I will:
 - confirm GKE handling
 - paste link here for history
 - Put up PR removing the special case entirely
