### ISSUE TITLE
Setting the context to a namespace that doesn't exist should tell you that the namespace doesn't exist

### ISSUE THREAD

**Issue by janitha09** [kubernetes/kubernetes#76733]
**What would you like to be added**:

A warning or error letting the user know that they are attempting to switch to a namespace that doesn't exist

`kubectl config set-context --current --namespace=foo`

Prevent the namespace switch - stay where you are

**Why is this needed**:

User friendliness, prevent user from entering limbo space.

**Comment by liggitt** [comment]
All the `kubectl config ...` methods are intentionally local only, with no server contact required. `kubectl get ns <name>` can tell you if a namespace does not exist

**Comment by liggitt** [comment]
Changing the behavior to require server contact would be a breaking change. Adding a flag for a user to opt into the warning/error would not be significantly better than `kubectl get ns foo && kubectl config set-context --current --namespace=foo`

/close
