### ISSUE TITLE
kubelet does not report `usageNanoCores` for node on Windows

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#76740]
**What happened**:

`usageNanoCores` is not reported for `node` on Windows.
```
{ 
  "node": {
   "nodeName": "e2e-test-yjhong-windows-node-group-wv9b",
   "systemContainers": [
    {
     "name": "pods",
     "startTime": "2019-04-17T22:58:59Z",
     "cpu": {
      "time": null
     },
     "memory": {
      "time": null
     },
     "userDefinedMetrics": null
    }
   ],
   "startTime": "2019-04-17T22:24:57Z",
   "cpu": {
    "time": "2019-04-17T22:58:58Z",
    "usageCoreNanoSeconds": 55040000000
   },
   "memory": {
    "time": "2019-04-17T22:58:58Z",
    "availableBytes": 7619317760,
    "usageBytes": 1213886464,
    "workingSetBytes": 433328128,
    "rssBytes": 0,
    "pageFaults": 0,
    "majorPageFaults": 0
   },
...
```

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes v1.15.0-alpha.1.76+d48509bdf01ee1-
- Cloud provider or hardware configuration: GCE
- OS (e.g: `cat /etc/os-release`): Windows 1809
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @dashpole @feiskyer

**Comment by zhiweiv** [comment]
I reported same issue a few days ago, no feedback yet.
#75934

**Comment by feiskyer** [comment]
yep, only usageCoreNanoSeconds is reported for node CPU now. We should probably add a cache for usageCoreNanoSeconds and calculate usageNanoCores based on it.

**Comment by andyzhangx** [comment]
someone able to work on this? This is a blocking issue for upgrade to metrics server to v0.3.x if there is windows node
