### ISSUE TITLE
kubernetes v1.14.1 node.spec.podCIDR missing in worker nodes

### ISSUE THREAD

**Issue by dparalen** [kubernetes/kubernetes#76761]
Hi, 

I've noticed the `node.spec.podCIDR` was missing on my worker nodes, though the master node does provide both the key and value for the `node.spec.podCIDR` treat:
```
foo:daemonset milan$ kubectl get node empress --output json | jq .spec
{
  "podCIDR": "10.244.0.0/24",
  "taints": [
    {
      "effect": "NoSchedule",
      "key": "node-role.kubernetes.io/master"
    },
    {
      "effect": "NoSchedule",
      "key": "node.kubernetes.io/not-ready"
    }
  ]
}
foo:daemonset milan$ kubectl get node princess --output json | jq .spec
{
  "taints": [
    {
      "effect": "NoSchedule",
      "key": "node.kubernetes.io/not-ready"
    }
  ]
}
foo:daemonset milan$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
foo:daemonset milan$
```

As a consequence, e.g the [ kube-router ](https://www.kube-router.io/) (v0.2.5) worker daemon fails to start with an error like this:

```
foo:daemonset milan$ kubectl -n kube-system logs kube-router-arm64-sshw2
I0418 09:34:12.706389    9348 kube-router.go:207] Running /usr/local/bin/kube-router version v0.2.5, built on 2019-04-16T12:16:38+0200, go1.10.3
I0418 09:34:13.335132    9348 network_policy_controller.go:141] Starting network policy controller
I0418 09:34:13.349271    9348 network_routes_controller.go:979] Could not find annotaion `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 192.168.0.32 address.
I0418 09:34:13.350612    9348 network_routes_controller.go:320] `subnet` in CNI conf file is empty so populating `subnet` in CNI conf file with pod CIDR assigned to the node obtained from node spec.
F0418 09:34:13.368985    9348 network_routes_controller.go:327] Failed to get pod CIDR from node spec. kube-router relies on kube-controller-manager to allocate pod CIDR for the node or an annotation `kube-router.io/pod-cidr`. Error: node.Spec.PodCIDR not set for node: princess
```

IIRC this used to work just OK in kubernetes v1.13.z

**What happened**:
`node.spec.podCIDR` is missing on worker nodes

**What you expected to happen**:
having deployed kubernetes master node by `kubeadm init --pod-network-cidr=10.244.0.0/24 --token-ttl=0` I'd expect the worker node would have `node.spec.podCIDR` populated once it joined the cluster by `kubeadm join 192.168.0.17:6443 --token ip6wvr.w8m8u34zmpeee706 \
    --discovery-token-ca-cert-hash sha256:70228a58dd14c6609553dcc50b009e55a4fdb2fc6bcf87b5ee32da1504ed8cac` which wasn't the case.

**How to reproduce it (as minimally and precisely as possible)**:

-  master node: `kubeadm init --pod-network-cidr=10.244.0.0/24 --token-ttl=0`
- worker node: `kubeadm join 192.168.0.17:6443 --token ip6wvr.w8m8u34zmpeee706 \
    --discovery-token-ca-cert-hash `
- `kubectl get node princess --output json | jq .spec`
- also deploying kube-router fails with `F0418 09:34:13.368985    9348 network_routes_controller.go:327] Failed to get pod CIDR from node spec. kube-router relies on kube-controller-manager to allocate pod CIDR for the node or an annotation `kube-router.io/pod-cidr`. Error: node.Spec.PodCIDR not set for node: princess`

**Anything else we need to know?**:
master arch: amd64 worker arch 1x arm64 2x amd64 all worker nodes exhibit same issue although the master `node.spec.podCIDR` is present.

I used to run K8s v1.13.z without issues previously, tried deploying v1.14.1 couple of times with the same error. I ran `kubeadm reset -f` on all the nodes before updating to v1.14.1, cleaned `iptables` and `ipvsadm`, removed `/etc/kubernetes` completely on all the nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux princess 4.9.0-6-arm64-si #1 SMP Debian 4.9.82-1+deb9u3.softiron3 (2018-07-06) aarch64 GNU/Linux
- Install tools: kubeadm
- Others: manual deployment

/sig node

**Comment by mattjmcnaughton** [comment]
/assign @mattjmcnaughton 

I'd be happy to look into this :)

**Comment by bigkraig** [comment]
FWIW we are seeing this too, same versions

**Comment by mattjmcnaughton** [comment]
I'm still happy to look into this, but haven't had a ton of luck finding an immediate fix (still learning the code base :) ). If anyone else has a better idea of how to fix, please ping me and I'm happy for you to take over!

**Comment by dparalen** [comment]
@mattjmcnaughton take it easy, same noob here ;)

**Comment by andrewsykim** [comment]
```
kubeadm init --pod-network-cidr=10.244.0.0/24
```

I believe the default CIDR allocated per node is `/24` so assigning `/24` for the pod network is going to be problematic. Can you reproduce this if you use a larger pod subnet like `/16`?

**Comment by andrewsykim** [comment]
/close 

Closing this since I think it's just a matter of setting a higher pod network cidr. Feel free to re-open if you still see the issue after increasing the pod cidr

**Comment by dparalen** [comment]
@andrewsykim I've just confirmed all works when the pod network CIDR is 10.244.0.0/16. Is this limitation documented anywhere?
Thanks for help!

**Comment by andrewsykim** [comment]
If you allocate a `/24` for your entire pod network but you are allocating /24 for each node then the control plane will quickly run out of pod CIDRs (after 1 node). I'm not sure there's documentation for that exact edge case but generally you should allocate a large enough CIDR. Hope that helps :)

**Comment by dparalen** [comment]
@andrewsykim I see, that exactly matches what actually happens. There doesn't seem to be any [kubeadm CLI option](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#options) to change the node mask size; is `/24` a hard-coded constant in kubeadm?

IMO small device clusters (like mine vintage 4-node deployment) would be fine with just 64 pod IPs per node. On the other hand, more beefy machine based deployment might get underutilized  serving just 256 pod IPs per node...

**Comment by amayacitta** [comment]
Google can do it somehow using Flexible-pod-cidr, not sure if it's yet possible outside of GCP. I ran into the same issue above, took me ages to work it out. Now I've got /20 instead of /23 and can get more than 2 nodes working ;-)
