### ISSUE TITLE
Need ability to create "dummy" node for cluster backed by a cloud-provider

### ISSUE THREAD

**Issue by zbialik** [kubernetes/kubernetes#76766]
@kubernetes/sig-node-feature-requests
@kubernetes/sig-node-bugs
@kubernetes/sig-node-api-reviews
@kubernetes/sig-cloud-provider-feature-requests
@kubernetes/sig-cluster-lifecycle
@kubernetes/sig-api-machinery-feature-requests

/sig node
/sig cloud-provider
/sig cluster-lifecycle
/sig api-machinery

**What would you like to be added**:
Ability to create a "dummy" node using a yaml template and not have the kube-controller-manager automatically remove it when it sees that kubelet is not running.

Currently, I can create the "dummy" node and have it remain in the k8s cluster if and only if the cluster has Cloud Provider set to None: 

i.e. kubelet has argument `"--cloud-provider="`.

If I have `"--cloud-provider=aws"`, the k8s node gets automatically removed by the node-controller. This behavior is described in the docs:

["When running in a cloud environment, whenever a node is unhealthy, the node controller asks the cloud provider if the VM for that node is still available. If not, the node controller deletes the node from its list of nodes."](https://kubernetes.io/docs/concepts/architecture/nodes/#node-controller)

**Why is this needed**:
Need to create a "dummy" node to integrate F5/BIG-IP device with Kubernetes Cluster.

I am trying to use the [k8s-bigip-ctlr](https://github.com/F5Networks/k8s-bigip-ctlr) to autonomously update our BIG-IP device with routes to our backend pods. Specifically, we want to use the k8s-bigip-ctlr as an ingress-controller. The install docs for using the k8s-bigip-ctlr as an ingress-controller begin with creating a "dummy" node in the k8s cluster. Creating the "dummy" node allows flannel to add the BIG-IP device to the VXLAN. The install instructions are described and explained in the following docs: 

- [BIG-IP and flannel VXLAN Integration](https://clouddocs.f5.com/containers/v2/kubernetes/flannel-bigip-info.html)
- [Add BIG-IP device to flannel VXLAN](https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-bigip-k8s.html#use-bigip-k8s-flannel)

**Comment by liggitt** [comment]
@andrewsykim, wasn't there an existing issue for telling a cloud provider to ignore a node?

**Comment by andrewsykim** [comment]
@liggitt yeah we had some discussions for this in https://github.com/kubernetes/kubernetes/pull/73171. Not something that is high priority for the SIG right now but we would be open to KEPs to discuss this further :)
