### ISSUE TITLE
Prometheus related errors in build-log.txt

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#76760]
Not a failing test per-se, but I found following errors in build log:
```
W0417 08:18:35.533] E0417 08:18:35.532786   12335 api_responsiveness_prometheus.go:71] %!s(MISSING): prometheus framework is not provided!
W0417 10:09:53.486] E0417 10:09:53.486038   12335 api_responsiveness_prometheus.go:71] %!s(MISSING): prometheus framework is not provided!
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1118424348374339585

/assign @mm4tt
looks related to your current work.

**Comment by mm4tt** [comment]
/sig scalability

/assign @krzysied 
Krzysiek, it's the code you added recently, could you take a look?

**Comment by krzysied** [comment]
- https://github.com/kubernetes/perf-tests/pull/507 - fix for the missing argument.
- The api responsiveness prometheus measurement is enabled in all tests of the k8s head version. This measurement shouldn't cause the test to fails. The logic behind adding it was to compare its results with old api responsiveness measurement's.
- This measurement uses prometheus server. If there measurement is enabled and there is no proemethus server available, the error is logged.

**Comment by mm4tt** [comment]
Will be fixed by https://github.com/kubernetes/perf-tests/pull/507

/unassign
