### ISSUE TITLE
Use read lock in ServeHTTP

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#76783]
**What would you like to be added**:
Use read lock in ServeHTTP

**Why is this needed**:
Currently ServeHTTP (in healthcheck.go) takes the write lock:
```
	h.hcs.lock.Lock()
	svc, ok := h.hcs.services[h.name]
```
Since it only reads from h.hcs.services, holding read lock should suffice.

**Comment by tedyu** [comment]
cc @m1093782566

**Comment by tedyu** [comment]
ping @m1093782566

**Comment by m1093782566** [comment]
looks good to me. Thanks!

**Comment by tedyu** [comment]
@m1093782566 
Can you give /lgtm ?

**Comment by tedyu** [comment]
ping @m1093782566
