### ISSUE TITLE
Support log filters for Audit events

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#76794]
We are looking to use Audit sinks for a number of use-cases which requires us to know parts of the resource yaml. Using `Request` log level produces too much data. Rather we would like to provide a json filter (like you find in GraphQL) and receive only those fileds in the audit event. Does this sounds like a reasonable feauture request? If so, we would like to work it through the KEP etc.

I wrote a json filter library to handle a similar use-case. You can see the code and its example usage here: https://github.com/appscode/go/tree/master/encoding/json

**Comment by pbarker** [comment]
being worked on here https://github.com/kubernetes/kubernetes/pull/71230

**Comment by lavalamp** [comment]
There was a dynamic audit configuration API in the works that would probably serve this use case, but I'm not sure what the status is. hm I think this is the latest: https://github.com/kubernetes/enhancements/pull/1259
