### ISSUE TITLE
Support authentication in AuditSink client config

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#76813]
We are looking to send audit sink events to a external remote server. As things stand now, there is no way to provide Authorization header for these http requests. We would like to provide a token in the AuditSink via secret so that the sink server endpoint is authenticated.

https://github.com/kubernetes/api/blob/b8e4ab4b136a5ad597a48852189425fece12fdff/auditregistration/v1alpha1/types.go#L133

Is there any work around for this?

/area apiserver
/sig api-machinery
/sig auth

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/pull/73536 and https://github.com/kubernetes/enhancements/pull/658

/close
