### ISSUE TITLE
k8s dashboard style error

### ISSUE THREAD

**Issue by 0x2d3c** [kubernetes/kubernetes#76822]
Docker                           `17.03.2-ce`
Browser :                      `Chrome 73.0.3683.103 Linux`
Kubernetes:                `v1.14.0`
Dashboard:                 `k8s.gcr.io/kubernetes-dashboard-amd64     v1.10.1`

Screenshot:
![k8s-dashboard](https://user-images.githubusercontent.com/20468895/56423399-782d3080-62de-11e9-80c6-a5d541604c94.png)

**Comment by pigletfly** [comment]
This issue may be moved to https://github.com/kubernetes/dashboard

**Comment by 0x2d3c** [comment]
> This issue may be moved to https://github.com/kubernetes/dashboard

thanks
