### ISSUE TITLE
Ability to port-forward to a Service

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#7682]
Currently, `kubectl port-forward` can forward port to a pod.  It would be super useful to be able to forward to a service!

**Comment by thockin-cc** [comment]
This should be easy to do for "external" services one @justinsb lands his
work. Internal services are trickier, probably have to bounce through the
master..

**Comment by bgrant0607** [comment]
Closing in favor of #15180.
cc @thockin
