### ISSUE TITLE
[e2e] Add import restrictions file to the e2e testing framework

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#76832]
we need to add such a file under:
test/e2e/framework

see this file as an example:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/.import-restrictions

xref: https://github.com/kubernetes/kubernetes/issues/75601

/help
/good-first-issue
/area e2e-testing-framework
/sig testing
/kind cleanup

**Comment by johnSchnake** [comment]
What are the restrictions that we are trying to place in the e2e framework? In the example given it looks like the only thing blacklisted is provider-specific implementations or the internal client. I know one of the recent changes was ensuring we dont use the internal client, is that all we want to blacklist for now? Or also all specific provider implementations? Some other dep we want to prevent?

**Comment by Chrischuck** [comment]
I'd like to help on this issue, this would be my first issue so I'd need some help as well if that's OK.
