### ISSUE TITLE
[e2e] document e2e testing framework local testing for contributors

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#76833]
write documentation under test/e2e/framework or under the community repo on how to test your changes locally using kind/kubetest.

xref https://github.com/kubernetes/kubernetes/issues/75601

/assign
/kind documentation
/area e2e-test-framework

**Comment by neolit123** [comment]
@nzoueidi messaged me that they want to work on this issue.
/lifecycle active

**Comment by timothysc** [comment]
Closing in favor of issues in the other repos.
