### ISSUE TITLE
Allow scaleUpLimit parameter to be configurable

### ISSUE THREAD

**Issue by petrokashlikov** [kubernetes/kubernetes#76880]
**What would you like to be added**:
I would like scaleUpLimit parameter to be configurable to accommodate various scenarios

**Why is this needed**:
As per current motivation in code comments

```
// Do not upscale too much to prevent incorrect rapid increase of the number of master replicas caused by
// bogus CPU usage report from heapster/kubelet (like in issue #32304).

```
this parameter calculation formula was made up for above reasons. But right now HPA is used more widely, based not only on CPU metrics, but various custom metrics. Also cluster sizes are different and I understand that it may cause issues for example at very large scale, but if we want to scale some workload from 1 to 10 replicas, it wouldn't cause much issues. And by making this parameter configurable, cluster operator/administrator can decide if he want to take responsibility. 

Now about our specific practical use case, which require this parameter to be configurable. 

We use Kafka and nature of messaging stream is subject to spikes. We have HPA configured based on consumer lag. In regular situation we have one pod running as Kafka consumer and during spike in messaging we would like to scale it. As of now it is happening like this: 
Replicas are scaled from 1 to 4, then from 4 to 8 and then from 8 to 10 and we get this message in HPA events "the desired replica count is increasing faster than the maximum scale rate"

**Problem:** due to Kafka system design, each time when new consumers appear, Kafka is doing rebalancing to re-distribute load, so if we scale up gradually, it will do rebalancing few times and waste time on this. If we could configure this parameter and during spike allow to scale up to 10 replicas immediately, it will allow to do rebalancing only once and process data much quicker.

**Comment by petrokashlikov** [comment]
sig/autoscaling

**Comment by Rajat-0** [comment]
@petrokashlikov this might help you.
https://github.com/kubernetes/kubernetes/pull/74525
