### ISSUE TITLE
[Failing Test] [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]

### ISSUE THREAD

**Issue by smourapina** [kubernetes/kubernetes#76898]
**Which jobs are failing**:
`ci-kubernetes-e2e-gce-new-master-upgrade-cluster` - `master-upgrade/gce-new-master-upgrade-cluster`
`ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new` - `master-upgrade/gce-new-master-upgrade-cluster-new`

**Which test(s) are failing**:
`[sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]` 
- [ci-kubernetes-e2e-gce-new-master-upgrade-cluster #1117805679977959425](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/1117805679977959425)
- [ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new #1117872109163384835](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1117872109163384835)

**Since when has it been failing**:
Several failures in the past weeks.

**Testgrid links**:
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new

**Reason for failure**:
Timeouts, for example:
```
I0415 19:51:18.788] Apr 15 19:51:18.788: INFO: Running dig: [/usr/bin/dig +short abc.acme.local], stdout: ";; connection timed out; no servers could be reached", stderr: "", err: command terminated with exit code 9

I0415 19:51:41.928] Apr 15 19:51:41.928: INFO: Running dig: [/usr/bin/dig +short abc.acme.local], stdout: ";; connection timed out; no servers could be reached", stderr: "", err: command terminated with exit code 9
```

/milestone v1.15
/sig storage
/kind failing-test
/priority important-soon

/cc @alejandrox1 @jimangel @rarchk @alenkacz

**Comment by alejandrox1** [comment]
The test in this issue seemed to stop failing in https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new . This is good, it may mean that https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster just needs more runs to clear out.

**Comment by alejandrox1** [comment]
The test mentioned in this issue is now in:
* https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster
* https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-new

**Comment by alejandrox1** [comment]
The test mentioned in this issue has been removed from the job.
/close
