### ISSUE TITLE
[Failing Test] SkewTest failing in master-upgrade:gce-new-master-upgrade-cluster-new

### ISSUE THREAD

**Issue by smourapina** [kubernetes/kubernetes#76901]
**Which jobs are failing**:
[sig-release-master-upgrade#gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)

**Which test(s) are failing**:
[SkewTest](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1117872109163384835)

**Since when has it been failing**:
Since 4/15, but has shown considerable flakiness in the past few weeks.

**Testgrid link**:
[ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new #1117872109163384835](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1117872109163384835)

**Reason for failure**:
```
error during kubetest --test --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --report-dir=/workspace/_artifacts --disable-log-dump=true --report-prefix=skew --check-version-skew=false: exit status 1error during kubetest --test --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --report-dir=/workspace/_artifacts --disable-log-dump=true --report-prefix=skew --check-version-skew=false: exit status 1
```

/milestone v1.15
/sig storage
/kind failing-test
/kind flake
/priority important-soon

/cc @alejandrox1 @jimangel @rarchk @alenkacz

**Comment by alejandrox1** [comment]
Will close this issue. It seems like the skewtest failures are due to other tests failing. However, the other failures are not consistent enough to be consider as "flakes".
/close
