### ISSUE TITLE
Exclude docker cache proxy from CoreOS getting started guide

### ISSUE THREAD

**Issue by hobti01** [kubernetes/kubernetes#7693]
The CoreOS cloud-config seems to include an "add-on" of sorts: the [docker cache proxy](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml#L45).  It is run directly in docker.  The functionality of the cache proxy is not needed for Kubernetes, and only benefits downloaders of images from the docker public registry.  Could the extra configuration be removed from the CoreOS setup in favor of handling caching as a use case of https://github.com/GoogleCloudPlatform/kubernetes/issues/1319 ?

**Comment by roberthbailey** [comment]
Which CoreOS getting started guide are you referring to? Looking at https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides there are CoreOs instructions for Azure, AWS, GCE, Vagrant, Bare Metal, VMWare, and libvirt/KVM.

**Comment by hobti01** [comment]
AWS, GCE, Vagrant, VMWare all point to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos.md which links to guides for [Single Node Cluster](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_single_node_cluster.md) and
[Multi-node Cluster](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md) which each describe AWS, GCE, and VMWare configurations.  I'm referring to these multi-use guides which use the [master.yaml](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml) and [node.yaml](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/node.yaml) from the k8s repository.

There are several other guides on the coreos page that do not use these cloud-configs.

**Comment by roberthbailey** [comment]
@hobti01 - I've just been reading over those configs while reviewing #7667. 

We don't currently have a timeframe for when #1319 will be finished, so if folks are currently using the docker cache proxy it seems like we shouldn't remove it until a replacement is available. WDYT?

**Comment by antoineco** [comment]
The cache is not necessary but can speed up things a lot if you run a lot of nodes. The reason why it made it to the getting started guides is because Google folks use it in the "Supported" setups (in /cluster/...)

**Comment by hobti01** [comment]
We are using private registries, so do not realize a benefit.  The additional configuration seemed to be added as part of unrelated changes and I was simply looking to make the configuration minimal.  I'll remove from our configuration.

**Comment by antoineco** [comment]
I can take care of it if considered legitimate. I also believe the getting started setups should remain as generic as possible. People can easily adapt them to their needs if they want extra features.

@roberthbailey?

**Comment by roberthbailey** [comment]
I'm fine with removing it from the standard configuration as long as it's clear to users a) how to add it and b) when they should add it (it sounds like the answer is when they have a lot of nodes and are using a public registry).

**Comment by baldwinSPC** [comment]
I would +1 removing it from the standard CoreOS configs. I'm yanking it out in my own builds. I agree with everyone that this is an "add-on" that shouldn't be part of a minimal configuration.

**Comment by roberthbailey** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/10344.
