### ISSUE TITLE
do not evict a DaemonSet Pod

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#76930]
**What happened**:
a daemonset pod will be evicted by kubelet when met eviction signal. 
**What you expected to happen**:
do not evict a daemonset pod, since the Pod is immediately recreated and rescheduled back to the same node.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
/close

daemonset pods are not treated differently by virtue of being daemonset pods

see discussion in the linked PR
