### ISSUE TITLE
PluginWatcher:  if do not close watcher when timeout is expected?

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#76949]
**What happened**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L160

When timeout happens, we should not close watcher? Is this desired?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cwdsuzhou** [comment]
If this is not expected, I would like to send a PR

**Comment by cwdsuzhou** [comment]
@mattfarina could you help take a look at this issue

**Comment by mattjmcnaughton** [comment]
@cwdsuzhou are you suggesting that we should move the `w.fsWatcher.Close()` call at line 175 to a `defer w.fsWatcher.Close()` call at line 168? I think I'd agree with that - it does seem like the `w.fsWatcher` is going to leak if there's a timeout.

That being said, I'm not super familiar with this part of the code. Happy to review a pr if you create one :)

**Comment by cwdsuzhou** [comment]
> @cwdsuzhou are you suggesting that we should move the `w.fsWatcher.Close()` call at line 175 to a `defer w.fsWatcher.Close()` call at line 168? I think I'd agree with that - it does seem like the `w.fsWatcher` is going to leak if there's a timeout.
> 
> That being said, I'm not super familiar with this part of the code. Happy to review a pr if you create one :)

Yes , I think this may cause cause leak and I would like to send a PR later.
