### ISSUE TITLE
The OWNERS_ALIASES file cannot be parsed. YAML is invalid.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/kubernetes#76950]
The OWNERS_ALIASES file in this repo is currently being ignored because it cannot be parsed.
```
  error:  "error converting YAML to JSON: yaml: line 396: did not find expected key" 
  msg:  "Failed to unmarshal aliases from "/tmp/git119819704/OWNERS_ALIASES". Using empty alias map."   
```

I think the problem is that this PR introduced incorrect indentation: https://github.com/kubernetes/kubernetes/pull/76736/files 

/assign @saad-ali

**Comment by liggitt** [comment]
likely the mis-indented sig-storage-api-reviewers alias, being fixed in https://github.com/kubernetes/kubernetes/pull/76947/files
