### ISSUE TITLE
kubectl zsh completion misbehaves on path containing a directory

### ISSUE THREAD

**Issue by toadjaune** [kubernetes/kubernetes#76957]
**What happened**:

In the current working directory, I have a `dir` directory, containing a `plop.yml` file.
When typing the following :
```
$ kubectl apply -f di[TAB]
```
the command-line becomes : 
```
$ kubectl apply -f dir/ [CURSOR]
```
Please note the space after the trailing slash. This causes a second [TAB] press to start completing a subsequent argument, instead of completing among the files in `dir/`

**What you expected to happen**:

I expected the command-line to become : 
```
$ kubectl apply -f dir/[CURSOR]
```
And, if I press [TAB] a second time, to become : 
```
$ kubectl apply -f dir/plop.yml [CURSOR]
```
since this is the only file in the directory (or classic completion behavior if there were several files, etc)

**How to reproduce it (as minimally and precisely as possible)**:

The following was done on a vanilla Google Cloud VM instance, provisioned with a default debian 9 image.

```
# Whole procedure to be run as root

# Update the system
$ apt-get update && apt-get dist-upgrade -y
[…]

# Install zsh and kubectl
$ apt-get install -y zsh kubectl
[…]

# Switch to zsh
$ zsh

# Load completion system
$ autoload -Uz compinit
$ compinit
$ source <(kubectl completion zsh)

# Create the test files
$ mkdir dir
$ touch dir/plop.yml

# Then try to autocomplete with kubectl
$ kubectl apply -f di[TAB]
```

**Anything else we need to know?**:

This bug does not affect bash completion.
I also made sure that this was not due to a conflict with any other completion configuration : there is no `.zshrc`, and without the `compinit` command, the `source <(kubectl completion zsh)` fails, so I'm pretty confident there's no other configuration at all.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
(there's no server in this setup, but I don't think the server version would be relevant)
- Cloud provider or hardware configuration:
Google Cloud Platform, f1-micro (1 vCPU, 0,6 GB memory), Intel Haswell
- OS (e.g: `cat /etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux undisclosed-hostname 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
```
- Install tools: cf above procedure
- Others:
```
$ zsh --version
zsh 5.3.1 (x86_64-debian-linux-gnu)
```

**Comment by toadjaune** [comment]
@kubernetes/sig-cli-bugs

**Comment by YoubingLi** [comment]
zsh (5.0.2) doesn't have this kind of issue on RHEL 7.2
Did you try it on other OS with different zsh version?
I am not sure if it is the problem of zsh (5.3.1)

~# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

~# echo $0
zsh

~# zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)

~# ls dir/
a.ymal

~# kubectl apply -f dir/a.ymal

**Comment by toadjaune** [comment]
@YoubingLi you're right, I just try manually compiling zsh on my test system described above for both versions `5.0.2` and `5.3.1` (I did recompile `5.3.1` just to be sure a behaviour difference was not due to a side effect of my install method), and I confirm that the problem is present in `5.3.1` but not in `5.0.2`.

Thanks for this, I'll start bisecting this and reading changelogs when I have a moment.

**Comment by toadjaune** [comment]
It seems you were lucky, the behaviour difference apparently appeared somewhere between `5.0.2` and `5.0.3` !

All that the changelog says is :
```
Incompatibilities between 5.0.2 and 5.0.3
-----------------------------------------

The "zshaddhistory" hook mechanism documented in the zshmisc manual page
has been upgraded so that a hook returning status 2 causes a history
line to be saved on the internal history list but not written to the
history file.  Previously any non-zero status return would cause
the line not to be saved on the history at all.  It is recommended
to use status 1 for this (indeed most shell users would naturally do
so).
```
which seems totally unrelated to our issue.

I'll try to bisect it down to an exact commit.

**Comment by toadjaune** [comment]
Still trying to find time to work on this, my previous setup apparently contained errors leading to wrong conclusions.

**Comment by toadjaune** [comment]
Hi everybody !

I finally found some time to work on this, this time, I used Docker to be certain that I was bisecting properly, and that each compilation was independent from the previous ones.

Here's the resulting Dockerfile : 
```
FROM debian

# Install kubectl
RUN apt-get update \
 && apt-get install -y curl gpg \
 && curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
 && echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list \
 && apt-get update \
 && apt-get install -y kubectl

# Setup configuration loading
RUN echo "autoload -Uz compinit"            >> /root/.zshrc \
 && echo "compinit"                         >> /root/.zshrc \
 && echo "source <(kubectl completion zsh)" >> /root/.zshrc

# Install compilation dependencies
RUN apt-get install -y autoconf gcc libncurses-dev make yodl

# Copy the code in the container
COPY zsh /zsh
WORKDIR /zsh

# Compile zsh
# NB : --with-tcsetpgrp was added after checking that we have it when executing manuall ./configure
RUN ./Util/preconfig
RUN ./configure --disable-dynamic --with-tcsetpgrp
RUN make -j8
RUN make install

RUN zsh --version

CMD zsh --version && zsh
```

With this minimal setup, I tried compiling the following versions : 
* `master` (current)
* `5.3.1`
* `5.0.2`
* `5.0.0`

They are all affected by this bug, so this is likely not due to a change in zsh behaviour.

I don't have access to any RHEL machine to test, but I have the problem on my Fedora too.

kubectl version used for these tests : 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

I then tried the opposite test : installing zsh through the system packages, and try various versions of kubectl.
I went as far back as `1.8.0`, and the problem is still present, so likely not a kubectl regression either.

I'm not sure what to do next.
Maybe have other people test, and see if they can reproduce the issue on their systems or not ?

**Comment by toadjaune** [comment]
/remove-lifecycle stale
I'll have some time to take care of this, eventually.

**Comment by toadjaune** [comment]
I just checked again on my local machine (kubectl `v1.19.3`, zsh `5.8`), the problem is not present anymore.
