### ISSUE TITLE
ExperimentalHostUserNamespaceDefaulting feature flag is obsolete

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubernetes#76982]
**What happened**:
Enabled ExperimentalHostUserNamespaceDefaulting feature gate.
Looking through the code, once the transition to CRI was made, the flag no longer had any effect.
The original code was in https://github.com/kubernetes/kubernetes/blob/d0d78f478ce0fb9d5e121db3b7c6993b482af82c/pkg/kubelet/dockertools/docker_manager.go#L684

**What you expected to happen**:
Expected to see pods start with host networking on the host namespace.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable feature flag.
2. Set the following in `/etc/docker/daemon.json`:

``` json
{
  "userns-remap": "default"
}
```
3. Run kubeadm init
4. Tail `journalctl -fu kubelet`:

```
Apr 24 02:37:40 server kubelet[11601]: E0424 02:37:40.764670   11601 remote_runtime.go:109] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-scheduler-server": Error response from daemon: cannot share the host's network namespace when user namespaces are enabled
Apr 24 02:37:40 server kubelet[11601]: E0424 02:37:40.764769   11601 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-scheduler-server_kube-system(487d50e28512c6a58309dca4bcf716fd)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-scheduler-server": Error response from daemon: cannot share the host's network namespace when user namespaces are enabled
Apr 24 02:37:40 server kubelet[11601]: E0424 02:37:40.764832   11601 kuberuntime_manager.go:693] createPodSandbox for pod "kube-scheduler-server_kube-system(487d50e28512c6a58309dca4bcf716fd)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-scheduler-server": Error response from daemon: cannot share the host's network namespace when user namespaces are enabled
Apr 24 02:37:40 server kubelet[11601]: E0424 02:37:40.764956   11601 pod_workers.go:190] Error syncing pod 487d50e28512c6a58309dca4bcf716fd ("kube-scheduler-server_kube-system(487d50e28512c6a58309dca4bcf716fd)"), skipping: failed to "CreatePodSandbox" for "kube-scheduler-server_kube-system(487d50e28512c6a58309dca4bcf716fd)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-scheduler-server_kube-system(487d50e28512c6a58309dca4bcf716fd)\" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod \"kube-scheduler-server\": Error response from daemon: cannot share the host's network namespace when user namespaces are enabled"
```

**Anything else we need to know?**:
CIS Benchmark for Docker requires user namespace support at Level 2:
> Enable user namespace support in Docker daemon to utilize container user to host user 
> remapping. This recommendation is beneficial where containers you are using do not have an
> explicit container user defined in the container image. If container images that you are
> using have a pre-defined non-root user, this recommendation may be skipped since this
> feature is still in its infancy and might give you unpredictable issues and complexities.

Incorporating user namespace support in some sort (see also https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-usernamespace-remapping.md) would strongly enable the use of PSPs.

This feature flag should probably be deleted as it will need CRI changes to implement?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration: Non
- OS (e.g: `cat /etc/os-release`):
```
NAME=Fedora
VERSION="29 (Server Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
```
- Kernel (e.g. `uname -a`): `5.0.7-200.fc29.x86_64`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by sftim** [comment]
/reopen

Let's do that.
(also, thanks for the thorough initial report @randomvariable)

**Comment by sftim** [comment]
@ehashman would you also be willing to set an explicit priority on this one? I'd definitely like this to land for the v1.24 release because it's related to the removal of Docker Engine direct integration support (dockershim) from the kubelet.

**Comment by jan-skarupa** [comment]
/remove-lifecycle stale

Is there a final decision to remove the feature flag? If yes, I could look into it.
