### ISSUE TITLE
Can kubectl describe nodes add GPU resource summary?

### ISSUE THREAD

**Issue by blackpiglet** [kubernetes/kubernetes#76995]
**What would you like to be added**:
On kubernetes 1.10.9, "kubectl describe node" can get allocatable resources as following:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits    Memory Requests     Memory Limits
  ------------  ----------    ---------------     -------------
  30770m (54%)  54040m (96%)  118148925192 (58%)  201938112016 (99%)`
```

I am wondering whether it's feasible to add GPU resource in it too, or is there some other ways to get idle GPU numbers on the node? 

**Why is this needed**:
Because I am running a k8s cluster to admin GPU resources. I found there is no easy way to find out how many GPU are still not used by current pods. 
Idle GPU numbers can be gotten from each nodes nvidia-smi command result, but it seems not a good way to do it. So I am asking whether this can be done on k8s cli.

**Comment by sashayakovtseva** [comment]
For GPU you should use device plugin, there's one for NVIDIA+Docker here: https://github.com/NVIDIA/k8s-device-plugin

**Comment by blackpiglet** [comment]
> For GPU you should use device plugin, there's one for NVIDIA+Docker here: https://github.com/NVIDIA/k8s-device-plugin

Thanks. I understand that, but NVIDIA device plugin doesn't provide a direct way to get the used and unused GPU number. This is the suggested way to do that recommended by NVIDIA device plugin:
https://github.com/NVIDIA/k8s-device-plugin/issues/67

```
If you want to know how many GPUs are used in the cluster: List all pods running and add the nvidia.com/gpu.
If you want to know many GPUs are used on a node: List all pods running on that node and add the nvidia.com/gpu.
```

This is acceptable, but I think we can do better. By my understanding, k8s or NVIDIA device plugin already know how much resource are used to make scheduling happen, so show it in a k8s command should be possible.

**Comment by t-anil-kumar** [comment]
Not sure on version 1.10.9, but on my current installation having version 1.12.4, the following works
```
kubectl describe nodes  |  tr -d '\000' | sed -n -e '/^Name/,/Roles/p' -e '/^Capacity/,/Allocatable/p' -e '/^Allocated resources/,/Events/p'  | grep -e Name  -e  nvidia.com  | perl -pe 's/\n//'  |  perl -pe 's/Name:/\n/g' | sed 's/nvidia.com\/gpu:\?//g'  | sed '1s/^/Node Available(GPUs)  Used(GPUs)/' | sed 's/$/ 0 0 0/'  | awk '{print $1, $2, $3}'  | column -t
```
Sample Ouput:
```
# kubectl describe nodes  |  tr -d '\000' | sed -n -e '/^Name/,/Roles/p' -e '/^Capacity/,/Allocatable/p' -e '/^Allocated resources/,/Events/p'  | grep -e Name  -e  nvidia.com  | perl -pe 's/\n//'  |  perl -pe 's/Name:/\n/g' | sed 's/nvidia.com\/gpu:\?//g'  | sed '1s/^/Node Available(GPUs)  Used(GPUs)/' | sed 's/$/ 0 0 0/'  | awk '{print $1, $2, $3}'  | column -t
Node        Available(GPUs)  Used(GPUs)
10.3.50.102  4                0
10.3.50.171  4                3
10.3.50.97   4                1
```

**Comment by blackpiglet** [comment]
@t-anil-kumar 
Glad to hear. Thanks. That will do.

**Comment by saifrahmed** [comment]
For those noting this isn't possible, i'm a big confused:

When deploying pods requesting more GPUs than are available, the deployment will remain in pending state until the other deployment is gone. Specifically, a kubectl describe pod will note " Insufficient nvidia.com/gpu" suggesting that kubectl knows about GPU resources and availability.

```
Events:
  Type     Reason            Age              From               Message
  ----     ------            ----             ----               -------
  Warning  FailedScheduling  8s (x2 over 8s)  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu.

```

**Comment by hpasapp** [comment]
The incantation in @t-anil-kumar 's post above doesn't work for me. I only see total available GPUs, not how many GPUs are in use. Agree with @saifrahmed that presumably the information is available in k3s somehow, but seems unclear to me how to expose it from kubectl, or using kubernetes python client.

**Comment by anderson-kl-1** [comment]
A minor tweak to @t-anil-kumar 's shell command got it to work for me on zsh on MacOS.   Here's my alias. 

k8s_gpu='kubectl describe nodes | tr -d "\000" | sed -n -e "/^Name/,/Roles/p" -e "/^Capacity/,/Allocatable/p" -e "/^Allocated resources/,/Events/p"  | grep -e Name  -e  nvidia.com  | perl -pe "s/\n//"  |  perl -pe "s/Name:/\n/g" | sed "s/nvidia.com\/gpu://g" | sed "s/nvidia.com\/gpu//g" | sed "1s/^/Node Available(GPUs)  Used(GPUs)/" | sed "s/$/ 0 0 0/"  | awk '\''{print $1, $2, $3}'\''  | column -t'
