### ISSUE TITLE
how to validate client certificate, my application resolves for all digi cert client certificates

### ISSUE THREAD

**Issue by manojchandrabss** [kubernetes/kubernetes#76998]
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

 nginx-ingress-controller:
 Image:       quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0

we are using kubernetes and stable/nginx-ingress for our application. we are using 2 ways ssl authentication. everyone who have client key can authenticate our application. client.xyz.com.key should only work. but in our case, any digi cert client key is working for authentication. 

how can we tell nginx to check the cname of the client.key to validate before ssl termination. 

example:
application : www.xyz.com

only client.xyz.com.key can only access our application www.xyz.com.

Regards,
Manoj.

**Comment by liggitt** [comment]
questions about client auth via the nginx ingress can be directed to https://github.com/kubernetes/ingress-nginx

/close
