### ISSUE TITLE
Kube-Apiserver can not proxy admission-webhook and aggr-apiserver to Headless Service

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#77018]
**What happened**:

When I use Headless Service to declare my admission-webhook or aggr-apiserver, the Kube-Apiserver can not proxy the request if the Kube-Apiserver start flags has `--enable-aggregator-routing=false`, the error message is "cannot route to service with ClusterIP "None"".

What's more, in apiserver lib(staging/src/k8s.io/apiserver/pkg/util/proxy) test cases, if Kube-Apiserver start flags has `--enable-aggregator-routing=true`, Kube-Apiserver can not proxy the request and return errors too, but actually Kube-Apiserver  can proxy the request well.

**What you expected to happen**:

Enable Kube-Apiserver to proxy admission-webhook and aggr-apiserver to Headless Service.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start Kube-Apiserver with the flag `--enable-aggregator-routing=false`
2. Deploy an admission-webhook server and declare a Headless Service
3. Declare a MutatingWebhookConfiguration or ValidatingWebhookConfiguration ref the Headless Service
4. The Kube-Apiserver can not proxy the request to the Headless Service

**Anything else we need to know?**:

What's more, in apiserver lib(staging/src/k8s.io/apiserver/pkg/util/proxy) test cases, if Kube-Apiserver start flags has `--enable-aggregator-routing=true`, Kube-Apiserver can not proxy the request and return errors too, but actually Kube-Apiserver  can proxy the request well.

**Environment**:

The latest Kubernetes also has this issue

**Comment by dixudx** [comment]
@answer1991 `enable-aggregator-routing` only indicates what the service resolver will get, clusterIP or endpointIP.
For your case, i.e. headless service, no IPs will be found no matter `enable-aggregator-routing` is set to `true` or `false`.

**Comment by wu0407** [comment]
@liggitt  has  plant to support this feature
