### ISSUE TITLE
Remove dependency on ghodss/yaml

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#77024]
looks like we still pull in `github.com/ghodss/yaml` instead of `sigs.k8s.io/yaml`
```
sigs.k8s.io/kustomize/pkg/target/kusttarget.go:	"github.com/ghodss/yaml"
sigs.k8s.io/kustomize/pkg/resmap/resmap.go:	"github.com/ghodss/yaml"
github.com/coreos/etcd/embed/config.go:	"github.com/ghodss/yaml"
sigs.k8s.io/kustomize/pkg/patch/transformer/patchjson6902json.go:	"github.com/ghodss/yaml"
sigs.k8s.io/kustomize/pkg/transformers/config/factorycrd.go:	"github.com/ghodss/yaml"
sigs.k8s.io/kustomize/pkg/transformers/config/factory.go:	"github.com/ghodss/yaml"
```

Tasks:
- [x] [create PR in sigs.k8s.io/kustomize repo to replace the dependency](https://github.com/kubernetes-sigs/kustomize/pull/1014)
- [x] [create PR in github.com/coreos/etcd repo to replace the dependency](https://github.com/etcd-io/etcd/pull/10687)
- [ ] create PR in kubernetes/kubernetes to pull in updated items above

**Comment by dims** [comment]
@rohitsardesai83 can you please look into this?

**Comment by Pingan2017** [comment]
I'd like to take this if needed

**Comment by rohitsardesai83** [comment]
Yes dims I will start working on this

**Comment by rohitsardesai83** [comment]
@dims , I have raised a PR for the kustomize repo  : https://github.com/kubernetes-sigs/kustomize/pull/1014.

**Comment by rohitsardesai83** [comment]
@dims , opened a new PR against etcd repo : https://github.com/etcd-io/etcd/pull/10687

**Comment by rohitsardesai83** [comment]
@dims, https://github.com/etcd-io/etcd/pull/10687 is merged.

**Comment by rohitsardesai83** [comment]
@dims, https://github.com/etcd-io/etcd/pull/10718 is open against release-3.3 branch of etcd.

**Comment by vnktram** [comment]
Can I pick up the line item to pull the changes from `etcd` and `kustomize` into k8s?

**Comment by dims** [comment]
we'll need a etcd 3.3.14 looking at the list of changes since the last release [1]

[1] https://github.com/etcd-io/etcd/compare/v3.3.13...release-3.3

**Comment by dims** [comment]
etcd is now at 3.3.15, but kustomize is gonna be a bit of challenge, there's a new a 3.x (v3) with lots of changes, we could try 2.1.0 (still has some api changes)

**Comment by dims** [comment]
we are left with just kustomize here:
```
dims@dims-a01:~/go/src/k8s.io/kubernetes$ rg ghodss vendor/  | grep "\.go"
vendor/sigs.k8s.io/kustomize/pkg/target/kusttarget.go:	"github.com/ghodss/yaml"
vendor/sigs.k8s.io/kustomize/pkg/resmap/resmap.go:	"github.com/ghodss/yaml"
vendor/sigs.k8s.io/kustomize/pkg/patch/transformer/patchjson6902json.go:	"github.com/ghodss/yaml"
vendor/sigs.k8s.io/kustomize/pkg/transformers/config/factorycrd.go:	"github.com/ghodss/yaml"
vendor/sigs.k8s.io/kustomize/pkg/transformers/config/factory.go:	"github.com/ghodss/yaml"
```

**Comment by dims** [comment]
we will need progress in https://github.com/kubernetes/kubernetes/issues/82905 for this to wrap up.
