### ISSUE TITLE
Expose end to end latency volume operation metrics via CSI

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes/kubernetes#77030]
**What would you like to be added**:
Latency of volume operations like provisioning a volume has been evaluated as following:
1. for in-tree implementation, latency is recorded ONLY for one-retry loop which could be not accurate, i.e., when the first retry actually fails while the following attempt succeeded.
2. via CSI, as its async nature, i.e. [https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1404], the call for provisioning will return immediately and making the latency metrics recording at [https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1348](url) not accurate.

This issue has been brought up in [https://github.com/kubernetes/kubernetes/issues/75782](url), creating a separate issue to track the effort for enhance it in the current controller after discussion with @msau42 as itself seems to be big enough.

Within this enhancement, looking to have two stages:
1. provide accurate volume provisioning/deletion latency metrics for CSI workflow
2. discuss with sig/storage to see whether it is worth enhancing existing in-tree implementation

**Why is this needed**:
To provide more accurate volume operation latency metrics for provisioning/deletion for a better user experience.

**Comment by yuxiangqian** [comment]
@kubernetes/sig-storage-feature-requests
/assign
cc @gnufied @msau42 @saad-ali

**Comment by gnufied** [comment]
thanks for creating this. I have a WIP PR that partially implements this - https://github.com/kubernetes/kubernetes/pull/75384 . This PR only captures mount, unmount and attach operation timings.

**Comment by yuxiangqian** [comment]
@gnufied thanks for providing the reference implementation. I will be working on this enhancement along with @msau42 @saad-ali early next week and plan to merge into 1.15.

**Comment by yuxiangqian** [comment]
@msau42 @saad-ali @gnufied 
Document couple of implementation options here:
1. utilizing CreationTimestamp/DeletionTimestamp of each PVC metadata (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go) as the starting ts of the user operation.
   pro: accurate provisioning end to end latency
   con: does not really work for deletion because of existence of user defined graceful period, does not work for resizing
2. using starting ts captured by controller when a corresponding operation has been picked up, i.e., "syncClaim"
   pro: consistent implementation btw provisioning/deletion/resizing. Though metrics might not be 100%  accurate for creation (as the queuing time will not be captured), given the fact that queuing time is normally a very small portion of the whole process as well as the nature of the metrics in-accuracy nature, it should be sufficient. Meanwhile its feasible to measure queuing metrics separately in future enhancement if needed.
  con: a new local cache is needed in controller code, and its lifecycle has to be carefully managed. i.e., when to delete.

after discussion with @msau42, we have decided to take the 2nd approach for simplicity/consistency/feasibility.

Working on this item this week.
