### ISSUE TITLE
kubectl top should mention it requires setrics server not heapster due to deprecation

### ISSUE THREAD

**Issue by burdzwastaken** [kubernetes/kubernetes#77047]
**What happened**: 
kubectl top displays the following message when ran:
```
[] burdz@~: kubectl top
Display Resource (CPU/Memory/Storage) usage.

 The top command allows you to see the resource consumption for nodes or pods.

 This command requires Heapster to be correctly configured and working on the server.
```
**What you expected to happen**:
Output along the lines of:
```
 This command requires Metrics Server to be correctly configured and working on the server.
```
**How to reproduce it (as minimally and precisely as possible)**:
`kubectl top`
**Anything else we need to know?**:
offending line: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/top/top.go#L39
heapster deperecation: https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md#heapster-deprecation-timeline

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by burdzwastaken** [comment]
/remove-lifecycle stale
fixed in: https://github.com/kubernetes/kubernetes/pull/77049

**Comment by NeilW** [comment]
/remove-lifecycle stale
/sig cli

Can we fix this nit?

**Comment by burdzwastaken** [comment]
@NeilW I can rebase my PR to fix with the most recent Kubernetes master branch to then close out the this nit?
