### ISSUE TITLE
Pod scheduling is uneven

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/kubernetes#77052]
**What happened**:
Pod scheduling to each node is uneven.
I have nine pods and three nodes, a node is allocated five pods, the other node is only assigned one pod. as a result, some of the machine's resources will be fully occupied.some nodes have a lot of resources

**What you expected to happen**:
Let's say I have nine pods, we have node1, node2, node3 three nodes.
I want three pods running on each of my nodes, which is not a waste of resources.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Tip**:
```
I tried to use Node Affinity, but the result was not very good, or I used the wrong method, could you tell me the correct method?
```

**Comment by xiaoxubeii** [comment]
Please fill in the Environment:
```
Kubernetes version (use kubectl version):
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Network plugin and version (if this is a network-related bug):
Others:
```

**Comment by xichengliudui** [comment]
```
Kubernetes version (use kubectl version): 1.14.0  
Cloud provider or hardware configuration: 
OS (e.g: cat /etc/os-release): CentOS Linux 7 (Core)
Kernel (e.g. uname -a): 3.10.0-957.1.3.el7.x86_64 
Install tools: kubeadm
Network plugin and version (if this is a network-related bug): flannel, image: quay.io/coreos/flannel:v0.10.0-amd64
Others: NONE
```

**Comment by suigh** [comment]
@xichengliudui 
#77327 (API changes for KEP "Even Pods Spread) can help on this request.

**Comment by xichengliudui** [comment]
thanks.
