### ISSUE TITLE
flannel can't connect kube-apiserver

### ISSUE THREAD

**Issue by zkpingguo** [kubernetes/kubernetes#77061]
**What happened**:
flannel can't connect kube-apiserver,thus restart very often。

**What you expected to happen**:
flannel run normal.
**How to reproduce it (as minimally and precisely as possible)**:
master: kubeadm init  --pod-network-cidr=10.244.0.0/16
node：kubeadm join --token 3dp75u.icdqwe786yf7vc59 192.168.50.148:6443 --discovery-token-unsafe-skip-ca-verification
**Anything else we need to know?**:
Log as follows:
root@debian:~# docker logs faa668852544
I0425 07:14:37.721766       1 main.go:514] Determining IP address of default interface
I0425 07:14:37.724855       1 main.go:527] Using interface with name eth0 and address 192.168.50.19
I0425 07:14:37.815135       1 main.go:544] Defaulting external address to interface address (192.168.50.19)
E0425 07:15:07.825910       1 main.go:241] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-arm-bg9rn': Get https://10.96.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-arm-bg9rn: dial tcp 10.96.0.1:443: i/o timeout

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1
- Cloud provider or hardware configuration:no
- OS (e.g: `cat /etc/os-release`):no
- Kernel (e.g. `uname -a`):linux-4.9
- Install tools:
- Network plugin and version (if this is a network-related bug):flannel
- Others:no

**Comment by neolit123** [comment]
/sig network
/close
please contact the flannel maintainers for analysis of your problem, by creating a ticket in the flannel repo.
if they direct you that this is a k8s problem, re-open this ticket.
thanks.
