### ISSUE TITLE
Validate `kubernetes.io/hostname` label is same as metadata.name field of node object?

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#77067]
**What would you like to be added**:

Make sure `kubernetes.io/hostname` always equals to the node name. 

**Why is this needed**:

https://github.com/kubernetes/kubernetes/blob/78190f0758a6ccbe11051b33844a886e5c282342/pkg/kubelet/kubelet_node_status.go#L212-L229

However, `kubernetes.io/hostname` can be updated to any value later and some components will not work.

**Comment by mattjmcnaughton** [comment]
/assign @mattjmcnaughton 

@cofyc could you explain more about what components will not work if `kubernetes.io/hostname` is updated to any value later? Additionally, can you share more about how `kubernetes.io/hostname` could be updated later (i.e. are you referring to a k8s user manually changing the label)?

@neolit123 I'd love to tackle this - I'm curious if the correct place to fix this is in `pkg/apis/node/validation/validation.go` or in the `updateDefaultLabels` method in `pkg/kubelet/kubelet_node_status.go`?

**Comment by neolit123** [comment]
> could you explain more about what components will not work if kubernetes.io/hostname is updated to any value later? Additionally, can you share more about how kubernetes.io/hostname could be updated later (i.e. are you referring to a k8s user manually changing the label)?

i'd pose similar questions, is this a request to improve the error handling in case the label was changed manually or lock the label to prevent it being overwritten?

**Comment by cofyc** [comment]
> i'd pose similar questions, is this a request to improve the error handling in case the label was changed manually or lock the label to prevent it being overwritten?

lock the label. I guess there are no exceptions that hostname needs to be different from the node name.  If it has been changed by accident, users may encounter some strange problems, for example: 

- if `kubernetes.io/hostname` of node A is changed to B
- a user creates a pod with node affinity `kubernetes.io/hostname in (A)`
- the pod fails with `didn't match node selector` error and be pending forever, even if node A has enough resource

Some other mechanisms based on node labels have the same problem too.

> I'm curious if the correct place to fix this is in pkg/apis/node/validation/validation.go or in the updateDefaultLabels method in pkg/kubelet/kubelet_node_status.go?

I think it's better to enforce this in `validations.go`. To keep `hostname` label same as node name is like some other constraints we enforced on API types.

**Comment by mattjmcnaughton** [comment]
Ok, I've got a diff addressing this issue via a validation. Will create a pr shortly.

**Comment by zouyee** [comment]
/remove-lifecycle stale
any progress?

**Comment by mattjmcnaughton** [comment]
@zouyee I created a diff to address this issue - however, it hadn't seen any activity in months. I've tried pinging people, but if you want to also join in on that effort, I'm happy to reopen the diff.
