### ISSUE TITLE
I create a single master cluster with kubeadm, everything is fine but CoreDNS didn't work

### ISSUE THREAD

**Issue by genie2014** [kubernetes/kubernetes#77071]
I create a single master cluster with kubeadm, according to doc, I did it like this:

```
kubeadm init --pod-network-cidr=172.20.0.0/16
kubectl apply -f rbac-kdd.yaml
kubectl apply -f calico.yml
```

Now, everything is fine, all pods and services are running, but when I test CoreDNS, the problem is arise. I create a pod to test dns:

`kubectl exec busybox -- nslookup kubernetes`

It cannot resolve the kubernetes.

I think it maybe because the master IP is 10.0.197.143, and CoreDNS service's cluster-ip is 10.96.0.10. If I'm right, how can I change cluster-ip range?

**Comment by neolit123** [comment]
/area kubeadm
/priority awaiting-more-evidence

hi, what is your k8s version?
if you are running a k8s version before 1.12 it's not longer supported.
CoreDNS is the default DNS server in kubeadm since last year.

**Comment by genie2014** [comment]
> /area kubeadm
> /priority awaiting-more-evidence
> 
> hi, what is your k8s version?
> if you are running a k8s version before 1.12 it's not longer supported.
> CoreDNS is the default DNS server in kubeadm since last year.

k8s version is 1.14.0, DNS server is CoreDNS

**Comment by neolit123** [comment]
`kubeadm init` does have `--service-cidr` which maps to the api-server `--service-cluster-ip-range`.
