### ISSUE TITLE
Updating  cpu-manager-policy=static causes NVML unknown error 

### ISSUE THREAD

**Issue by henglianghe** [kubernetes/kubernetes#77073]
**What happened**: 

1. After setting the cpu-manager-policy=static of kubenets, the pod with gpu running nvidia-smi will report an error

   ```
   Failed to initialize NVML: Unknown Error
   ```

2. Setting the cpu-manager-policy=none for kubenets will not cause this error

3. Sometimes when the pod first runs, nvidia-smi will not give an error, and about 10 seconds later, running nvidia-smi will give an error

4. Check the reason for the error, find it is when reading /dev/nvidiactl Operation not permitted

   ```
   strace -v -a 100 -s 1000 nvidia-smi
   close(3)                                                                                           = 0
   open("/dev/nvidiactl", O_RDWR)                                                                     = -1 EPERM (Operation not permitted)
   open("/dev/nvidiactl", O_RDONLY)                                                                   = -1 EPERM (Operation not permitted)
   fstat(1, {st_dev=makedev(0, 704), st_ino=4, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=0, st_gid=5, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 1), st_atime=2019/04/23-17:35:28.678347231, st_mtime=2019/04/23-17:35:28.678347231, st_ctime=2019/04/23-17:33:09.682347235}) = 0
   write(1, "Failed to initialize NVML: Unknown Error\n", 41Failed to initialize NVML: Unknown Error
   )                                         = 41
   exit_group(255)                                                                                     = ?
   +++ exited with 255 +++
   ```

5. Update the cpu-manager-policy to none and static, and create two pods respectively as test-gpu(nvidia-smi can be run) and test-gpu-err (Running nvidia-smi reports an error).

   1. Check pods's /sys/fs/cgroup/devices/devices, found the difference between the list

   2. test-gpu(nvidia-smi can be run)

      ```
      root@super8:/sys/fs/cgroup/devices/kubepods/besteffort/pod52c61ec9-65b5-11e9-8cd2-0cc47aea540c/caca989a1f8d1a8c87f67c04d2d63347a98f52d745c44e77895b3ca4dfd9b18f# cat devices.list 
      c 1:5 rwm
      c 1:3 rwm
      c 1:9 rwm
      c 1:8 rwm
      c 5:0 rwm
      c 5:1 rwm
      c *:* m
      b *:* m
      c 1:7 rwm
      c 136:* rwm
      c 5:2 rwm
      c 10:200 rwm
      c 195:255 rw
      c 195:3 rw
      ```

   3. test-gpu-err (Running nvidia-smi reports an error)

      ```
      root@super8:/sys/fs/cgroup/devices/kubepods/besteffort/podbfa294b1-65aa-11e9-8cd2-0cc47aea540c/771eb2c6d41fe48160000ad481702d09bdda5bfe49d613f96273412e177b449d# cat devices.list 
      c 1:5 rwm
      c 1:3 rwm
      c 1:9 rwm
      c 1:8 rwm
      c 5:0 rwm
      c 5:1 rwm
      c *:* m
      b *:* m
      c 1:7 rwm
      c 136:* rwm
      c 5:2 rwm
      c 10:200 rwm
      ```

   4. 

6. so, After setting the cpu-manager-policy=static of kubenets,pod with gpu can run nvidia-smi command for a short time, But in a function that runs once in 10 seconds, /sys/fs/cgroup/devices/devices.list will be modified to lose read and write access to /dev/nvidiactl (and should have other files), and then cause nvidia-smi error

7.

**Comment by henglianghe** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/966

**Comment by vladwa** [comment]
The same issue is observed in kubernetes v1.14 version too.

**Comment by LiWeiJie** [comment]
The same issue is observed in kubernetes v1.15, v1.16 version too.

**Comment by zerosnake0** [comment]
/reopen
/remove-lifecycle rotten
same issue with v1.17 as well

**Comment by prcastro** [comment]
I'm still getting this error

**Comment by RenaudWasTaken** [comment]
@klueska fixed this in the latest (beta5) release

**Comment by klueska** [comment]
Note, this is a workaround more than a fix.

To use this workaround you will need to use the new daemonset spec `nvidia-device-plugin-compat-with-cpumanager.yml` instead of the default one.

This spec does two things different from the default one:
1) It adds a new argument to the plugin executable for `--pass-device-specs`
2) It launches the plugin as `--privileged`

If you don't want to use the `--privileged` flag, then things will still "work" in terms of allowing pods with GPUs to run, but you will see the plugin restart anytime a container with guaranteed CPUs from the CPUManager starts. If you are OK with this restart, then launching the daemonset as `--privileged` is not strictly necessary.
