### ISSUE TITLE
Audit plugin: log and webhook get different events 

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#77076]
**What happened**:

Log file  output

{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2019-04-25T11:07:48Z"},"level":"Request","timestamp":"2019-04-25T11:07:48Z","auditID":"a0e8d1ab-bed8-412e-9009-5747ca91f443","stage":"ResponseComplete","requestURI":"/api/v1/pods?fieldSelector=spec.nodeName%3D192.168.17.42\u0026limit=500\u0026resourceVersion=0","verb":"list","user":{"username":"system:node:192.168.17.42","groups":["system:nodes","system:authenticated"]},"sourceIPs":["192.168.17.42"],"objectRef":{"resource":"pods","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2019-04-25T11:07:48.383926Z","stageTimestamp":"2019-04-25T11:07:48.385811Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}

Our webhook Received

 {Event:{TypeMeta:{Kind: APIVersion:} Level:Request AuditID:a2051e27-585e-4172-a6bb-975ff9d784da Stage:ResponseComplete RequestURI:/api/v1/namespaces/kube-system/endpoints/cloud-controller-manager Verb:get User:{Username:kubernetes-admin UID: Groups:[system:masters system:authenticated] Extra:map[]} ImpersonatedUser:<nil> SourceIPs:[100.64.230.144] UserAgent: ObjectRef:0xc0002e0080 ResponseStatus:&Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,},Status:,Message:,Reason:,Details:nil,Code:200,} RequestObject:nil ResponseObject:nil RequestReceivedTimestamp:2019-04-25 19:25:28.728101 +0800 CST StageTimestamp:2019-04-25 19:25:28.730226 +0800 CST Annotations:map[authorization.k8s.io/decision:allow authorization.k8s.io/reason:]}}

We got different results. Some variables missed or is empty, like `UserAgent`, `Kind`, `APIVersion` are  usually empty. `timestamp` missed

**What you expected to happen**:

Get same data.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: k8s 1.11
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pbarker** [comment]
`kind` `apiversion` and `timestamp` could potentially be in how you are decoding it, not sure about `user_agent`. Could you share more of your code at getting to these results @cwdsuzhou, as well as the flags you have set on the API server and the audit policy you are using. Thanks

**Comment by cwdsuzhou** [comment]
@pbarker 

log config

--audit-log-maxbackup=10 \
--audit-log-maxsize=100 \
--audit-log-path=/var/log/kubernetes/kubernetes.audit \
--audit-log-maxage=7 \
--audit-policy-file=/etc/kubernetes/audit-policy.yml \


webhook config

--audit-webhook-mode=batch \
--audit-webhook-batch-max-size=40 \
--audit-webhook-config-file=/etc/kubernetes/audit-webhook.conf \
--audit-policy-file=/etc/kubernetes/audit-policy.yml \


in webhook, we used json decode.

**Comment by pbarker** [comment]
@cwdsuzhou I'm curious if you get the same results using the k8s decoder https://github.com/kubernetes/kubernetes/blob/master/test/images/audit-proxy/main.go#L42

**Comment by cwdsuzhou** [comment]
Thanks, I would have a try

**Comment by cwdsuzhou** [comment]
@pbarker  I found some `Kind、ApiVersion` I seems normal now. But `timeStamp` `CreationTimestmap` still missed

**Comment by cwdsuzhou** [comment]
I found lost UserAgent is  mainly due to different k8s version, in k8s 1.11 it is lost but in 1.13 it exists
