### ISSUE TITLE
rkt: rkt status can have 2 fields instead of 3

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#7708]
We expect the output of `rkt status` to have 3 fields (id, image, and status) whereas during `prepare` the images often have only 2 fields (id and status)

/cc @yifan-gu @jonboulle @dchen1107

**Comment by yifan-gu** [comment]
Do you mean `rkt list` actually? You are right, and I found for `prepare aborted` it can have 4 fields. 
The reason for using `rkt list` is because we don't have `rkt status` by that time, so now I think we can change to use `rkt status` so we only need the `uuid` field from `rkt list`.

**Comment by vmarmol** [comment]
In my work-arounds that's what I did :)
