### ISSUE TITLE
Break up and Refactor test/e2e/framework/util.go

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#77095]
**What would you like to be added**:
There are a lot of methods in `test/e2e/framework/util.go` that can be cleaned up or moved into it's own package for easier consumption/discovery. In https://github.com/kubernetes/kubernetes/issues/76206 there were some discussions for how to break up this file. The proposed package structure was:

**test/e2e/framework/**
   - [ ] kubectl/ (@MorrisLaw)
            - builder.go
            -  runner.go   
   - [x] log/ (@draveness)
            - logger.go 
   - [x] pod/ (@alejandrox1) 
            - wait.go
            - resource.go
   - [x] node/ (@jiatongw)
            - wait.go
            - resource.go
   - [ ] service/  (@draveness) 
            - resource.go
   - [x] endpoints/ (@draveness) 
            - resource.go
   - [x] resource/ (@alejandrox1) 
            - runtime.go
   - [ ] lifecycle/ (@jiatongw)
            - versions.go
            - state.go
            - restart
- [ ] wrappers.go (@MorrisLaw) 
- [ ] providers.go (@alejandrox1) 

I think each package & top level file can be it's own task. Pick a package above, go through each method in `test/e2e/framework/util.go` and move it to that package/file if it makes sense. The above is just a guideline, feel free to introduce new packages/files where it makes sense. 

**Why is this needed**:
This is a part of https://github.com/kubernetes/kubernetes/issues/76206 & https://github.com/kubernetes/kubernetes/issues/75601

**Comment by johnSchnake** [comment]
There are also ssh utilities that should probably move into their own package; I'll take that one as I think it is also a reasonable step in #69373 which is assigned to me (reducing reliance on ssh in tests). Step 1, figure out where it really bubbles up to, step 2, do something about it.

**Comment by draveness** [comment]
I'd like to take the files as below :)

```go
service/*
endpoints/*
resource/*
```

**Comment by alejandrox1** [comment]
I’d like to take kubectl/* and pod/* :)

**Comment by WanLinghao** [comment]
I would like to take kubectl and log

**Comment by WanLinghao** [comment]
Hi, all. When I try handle cluster thing, I found there are many functions containing k8s-component. Like 
```
CheckNodesReady
RestartControllerManager
WaitForApiserverUp
```
Should we combine node/ and cluster/, maybe something like:

- [ ] cluster/
      - kubelet.go
      - kube-proxy.go
      - controller-manager.go
      - api-server.go
What do you think?

**Comment by draveness** [comment]
> Hi, all. When I try handle cluster thing, I found there are many functions containing k8s-component. Like

Maybe we could leave these for now and see what we could do after the major part of this is done.

**Comment by andrewsykim** [comment]
> Should we combine node/ and cluster/, maybe something like:

`test/e2e/framework/nodes` should be for anything handling the node resource. So `CheckNodesReady` should go there if it gets and checks node objects from the apiserver. 

RestartControllerManager and WaitForApiserverUp should go into `test/e2e/framework/restart.go` or `test/e2e/framework/cluster/state.go` IMO. What do you think?

**Comment by andrewsykim** [comment]
@WanLinghao updated `test/e2e/framework/cluster` to `test/e2e/framework/lifecycle` as per @jiatongw's suggestion

**Comment by draveness** [comment]
Hi @SataQiu, how is the process of refactoring networking_util going on? 

I'm working on service related functions in utils.go https://github.com/kubernetes/kubernetes/pull/77155. Some of the functions have to import `framework` package because of some common functions like `Logf`. And networking_util.go is calling `WaitForServiceEndpointsNum` and `WaitForService` which means it could cause the import cycle problem. 

Do you have the time to work on the `networking_util`? If you do not have the time, I could take it over from here, many thanks. :)

**Comment by MorrisLaw** [comment]
I can work on wrappers and providers if they’re still available.

**Comment by johnSchnake** [comment]
@draveness I have a WIP for extracting the logging into its own package. It is a very heavily used set of functions though so I am running into a few issues. All solvable though I think.  I’ll let you know when that is done.

**Comment by MorrisLaw** [comment]
Should provider related things go into `test/e2e/framework/providers`? Or, is it actually intended for `provider` related methods to be broken into a `test/e2e/providers.go` file despite there already being a `test/e2e/framework/provider.go` file? @andrewsykim

**Comment by andrewsykim** [comment]
> Should provider related things go into test/e2e/framework/providers? Or, is it actually intended for provider related methods to be broken into a test/e2e/framework/providers.go file despite there already being a test/e2e/framework/provider.go file? @andrewsykim

I think everything in `test/e2e/framework/providers` should be the provider implementations and `test/e2e/framework/providers.go` should have methods like `ProviderIs`and variables like `ProvidersWithSSH` in it. We can consider moving that up to `test/e2e/framework/providers/provider.go` but a lot of other methods in `test/e2e/framework` depend on it so I think keeping it in the same package at least for now makes sense. What do you think?

**Comment by SataQiu** [comment]
> 
> 
> Hi @SataQiu, how is the process of refactoring networking_util going on?
> 
> I'm working on service related functions in utils.go #77155. Some of the functions have to import `framework` package since it calls some common functions like `Logf`. And `networking_util.go` is calling `WaitForServiceEndpointsNum` and `WaitForService` which means it could cause the import cycle problem.
> 
> Do you have the time to work on the `networking_util`? If you do not have the time, I could take it over from here, many thanks. :)

@draveness I have tried to solve this problem before, but it was suspended for some reason. If you have the time, feel free to take it over. Thanks a lot.

**Comment by andrewsykim** [comment]
@SataQiu that's why we're breaking up `test/e2e/framework/util.go` first. If we can move methods like `Logf` and `WaitForService` into their own packages we would avoid import cycles. Correct me if I'm wrong though, maybe there's another import cycle I'm not seeing

**Comment by WanLinghao** [comment]
I think we need move log functions and ssh functions to their own packages first to avoid cycle import.
They are widely referred in `test/e2e/framework package `.
I have create PR #77156  to solve this.

**Comment by WanLinghao** [comment]
oops, it seems it would import huge change both in test/e2e/framework and out test/e2e/framework...
I am not sure if we need this change now..

**Comment by draveness** [comment]
> oops, it seems it would import huge change both in test/e2e/framework and out test/e2e/framework...
> I am not sure if we need this change now..

We could duplicate the `Logf` and other functions in the target pkg and refactor piece by piece.

**Comment by draveness** [comment]
I open a pr  https://github.com/kubernetes/kubernetes/pull/77184 which adds a new logger package with duplicate `Logf` implementation. I think we could start from this. :)

**Comment by draveness** [comment]
Hi, @andrewsykim  I came up with a list of files which has the text of `framework.Logf` with the following cmd:

> There must more files calls `Logf` which imports framework pkg with an alias, but we could start from this.

```bash
$ ag  -l "framework.Logf" test/
```

+ [ ] test/e2e_node
+ [ ] test/e2e
+ [ ] test/e2e/ui
+ [ ] test/e2e/scheduling
+ [ ] test/e2e/framework/ingress
+ [ ] test/e2e/framework/providers
+ [ ] test/e2e/framework/deployment
+ [ ] test/e2e/framework/replicaset
+ [ ] test/e2e/framework/volume
+ [ ] test/e2e/auth
+ [ ] test/e2e/cloud
+ [ ] test/e2e/network
+ [ ] test/e2e/lifecycle
+ [ ] test/e2e/storage
+ [ ] test/e2e/storage/vsphere
+ [ ] test/e2e/storage/testsuites
+ [ ] test/e2e/instrumentation
+ [ ] test/e2e/common
+ [ ] test/e2e/scalability
+ [ ] test/e2e/upgrades
+ [ ] test/e2e/node
+ [ ] test/e2e/windows
+ [ ] test/e2e/autoscaling
+ [ ] test/e2e/kubectl
+ [ ] test/e2e/apps
+ [ ] test/e2e/apimachinery

We could work on this after https://github.com/kubernetes/kubernetes/pull/77184 get merged. And I could help with those files below:

```go
+ [ ] test/e2e_node
+ [ ] test/e2e
+ [ ] test/e2e/ui
+ [ ] test/e2e/scheduling
+ [ ] test/e2e/framework/ingress
+ [ ] test/e2e/framework/providers
+ [ ] test/e2e/framework/deployment
+ [ ] test/e2e/framework/replicaset
+ [ ] test/e2e/framework/volume
```

> And by the way, the endpoints pkg could mark as solved in the comments. :)

**Comment by andrewsykim** [comment]
@draveness awesome! Can you open another issue to track that work separately?

**Comment by andrewsykim** [comment]
@draveness, hope you don't mind I created the issue here https://github.com/kubernetes/kubernetes/issues/77359

**Comment by draveness** [comment]
> @draveness, hope you don't mind I created the issue here #77359

That's great. Thank you! 😆

**Comment by andrewsykim** [comment]
I unassigned people if there were no PRs open to allow other contributors to grab work

**Comment by MorrisLaw** [comment]
I can work on the kubectl package @andrewsykim

**Comment by alejandrox1** [comment]
I can work on pod @andrewsykim

**Comment by SataQiu** [comment]
How do you feel about moving `Skipf`, `SkipUnlessNodeCountIsAtLeast` ... into `log/skip.go` ?
Or just put them into `log/logger.go` ?  
These functions log the reasons for skipping some tests.
@andrewsykim

**Comment by alejandrox1** [comment]
updates:
* resource/runtime.go is done (I accidentally took it from @draveness) in #79150
* pods/* is largely done in  #77526 - there are some leftover functions waiting for kubectl-related functions to be refactored.

**Comment by jiatongw** [comment]
Update: 
First step of refactoring node package is node. Following up PRs are on the way 
@alejandrox1

**Comment by alejandrox1** [comment]
Hey all, i don't see anything in progress for providers.go.
yall mind if i take it?

**Comment by andrewsykim** [comment]
@alejandrox1 please do, assigned it to you

**Comment by josiahbjorgaard** [comment]
Since this issue is tagged for milestone v1.16, here is a gentle reminder that code freeze is starting in 9 days on August 29th. Is the issue still targeted for this release?

**Comment by alejandrox1** [comment]
Thank you @josiahbjorgaard 

Also, updates on this:
* services still has some more work to be done it seems https://github.com/kubernetes/kubernetes/issues/77197
* kubectl is in progress https://github.com/kubernetes/kubernetes/pull/77592 ()
* wrappers has yet to be done I believe
* providers  - i'll send a pr for this one this week. 

Will ping people in slack to see if there is any other things we need to do and to see what needs help :smiley:

**Comment by alejandrox1** [comment]
Checking back on things.
There is no more work to be done for moving provider-related code from the framework util.go file so that is essentially done.

**Comment by alejandrox1** [comment]
bumping to the next milestone for now but we need to reevaluate this issue.
/milestone v1.18

**Comment by jtslear** [comment]
Hello @MorrisLaw, @johnSchnake, and @andrewsykim 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18?

**Comment by MorrisLaw** [comment]
Not sure of the others, but I'm working on another PR to move the rest of `kubectl` related stuff out  to the `framework/kubectl` subpkg. Should have that out soon. Then that part will be done @jtslear

**Comment by jtslear** [comment]
@MorrisLaw how are we looking towards getting work completed prior to code freeze on the 5th of March.  And should we bring in anyone else to take a look at this issue?

**Comment by MorrisLaw** [comment]
Not sure I can have the rest of the `kubectl` stuff moved out before that date. Circular dependencies are making it tricky "/. Any help or pairing would be appreciated (: , otherwise I'll continue trying to work on it when I can (usually nights or weekends).

I also think we should remove the `wrappers` task out of this issue. Based on the following comment: https://github.com/kubernetes/kubernetes/pull/77160#pullrequestreview-253517801

I can't speak on the other tasks assigned to other ppl.

**Comment by MorrisLaw** [comment]
@jtslear ^

**Comment by andrewsykim** [comment]
Lowering the priority for this one. For v1.19 we want to prioritize https://github.com/kubernetes/kubernetes/issues/74352. Contributions still welcomed.

/priority backlog

**Comment by alejandrox1** [comment]
/milestone clear

Will cleanup this thing as well to better direct what has yet to be done

**Comment by oomichi** [comment]
Fixed a typo in the title

/retitle Break up and Refactor test/e2e/framework/util.go

**Comment by gavinfish** [comment]
It seems most node related work has been done. I will continue to follow up node related refactor. Share it here to avoid unnecessary conflicts.
