### ISSUE TITLE
Remove Rancher Credential Provider from upstream kubernetes

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#77098]
Rancher 1.6 is using it still. Current Rancher version is 2.2.x per @alena1108. So we could possibly remove it from upstream and let the rancher folks maintain it in their own tree.

We don't need to carry the extra weight as mentioned in https://github.com/kubernetes/kubernetes/issues/76506

Since this is useful only in the rancher environment, we don't really need the traditional deprecation period. Right @alena1108?

**Comment by alena1108** [comment]
fine with me @dims
