### ISSUE TITLE
rkt: Support ports with no names

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#7710]
rkt support assumes all ports have names while this is not always the case in Kubernetes. We should create default port names in these situations.

/cc @yifan-gu @jonboulle @dchen1107

**Comment by yifan-gu** [comment]
Yes. Maybe something like `protocol:port` such as `TCP:80` ?

**Comment by vmarmol** [comment]
SGTM

**Comment by thockin** [comment]
as long as you make sure it is unique in the pod, which means you actually
have to test it and add a suffix if needed

**Comment by yifan-gu** [comment]
@thockin OK, then prefix with the container name should be good IMO

**Comment by thockin** [comment]
I don't think we defend against exposing the same protocol-port twice in a
single container, so be defensive.

**Comment by yifan-gu** [comment]
@thockin Why we expose the same protocol-port twice? Is that something we could add to the validation of the pod spec?

**Comment by thockin** [comment]
Consider exposing two host ports for the same pod.  I know it is a stretch,
but we don't defend it now.  Should be relatively easy to validate, but the
error message infrastructure we have does not have an obvious function to
call to say that the combination of some fields is not valid.
