### ISSUE TITLE
cinder-csi-plugin GRPC  attach failed that DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#77104]
**What happened**:
i test in k8sv1.13 that use the cinder-csi-plugin, the pod running in the end but the pod log print that :GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded

the problem is that the csiTimeout is 15 second that the cinder can not attached within in 15 second so time out ?

Events:
  Type     Reason                  Age              From                      Message
  ----     ------                  ----             ----                      -------
  Normal   Scheduled               3m               default-scheduler         Successfully assigned default/csi-rc-nginx-ztsqv to 111.111.111.116
  Warning  FailedAttachVolume      3m               attachdetach-controller   AttachVolume.Attach failed for volume "pvc-20480633-6661-11e9-8227-3a8d7c0bb20e" : attachment timeout for volume 3a82ae36-744a-4051-b398-14a860e35b5e
  Warning  FailedAttachVolume      3m (x4 over 3m)  attachdetach-controller   AttachVolume.Attach failed for volume "pvc-20480633-6661-11e9-8227-3a8d7c0bb20e" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   SuccessfulAttachVolume  3m               attachdetach-controller   AttachVolume.Attach succeeded for volume "pvc-20480633-6661-11e9-8227-3a8d7c0bb20e"
  Normal   Pulled                  3m               kubelet, 111.111.111.116  Container image "gcr.io/google_containers/nginx:1.7.9" already present on machine
  Normal   Created                 3m               kubelet, 111.111.111.116  Created container
  Normal   Started                 3m               kubelet, 111.111.111.116  Started container

**What you expected to happen**:
the error log is normal?and can not print it ?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:v1.13
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rmb938** [comment]
I can duplicate a similar issue with my own csi plugin. For me it's when volumes are being unpublished. I can only duplicate it when draining a node that has multiple volumes attached. My csi has a limit on the number of operations it can do at once so the detach operations end up being queued and 15 seconds is not enough time for it to get through the queue.

Being able to configure the kubelet's csi timeout would fix this issue.

**Comment by jianglingxia** [comment]
thanks for your repliy, but I print the kubelet -h can not search the flag about the csi timeout ? what about you fix the issue ?

**Comment by hoyho** [comment]
You are right, the csiTimeout for kubelet is 15 second. As currently the csiTimeout is not configureable and is it hardcoded. So, If you want longer timeout, you may need to build Kubelet by yourself.

**Comment by jianglingxia** [comment]
thanks @hoyho

yes,now it is hardcoded can not configureable,

but i modify the csi_plugin.go of the const  csiTimeout      = 15 * time.Second  to 20s always can not fix it ! the logs print the  rpc error: code = DeadlineExceeded desc = context deadline exceeded by warning is normal? how can you fix the problem?thanks

**Comment by hoyho** [comment]
@jianglingxia 
I don't use cinder-csi-plugin so have no idea how long will this plugin need. Anyway, I think 20s is quietly no different with default 15s. How about set to 30s or 1m. I have a csi plugin and I change to default timeout up to 60s. It works fine. You may try it.

**Comment by jianglingxia** [comment]
ok,really thanks @hoyho

another feature that the https://kubernetes.io/docs/concepts/storage/storage-limits/#dynamic-volume-limits the max volume limit  per node the csi can support, I set the value in driver but maybe can not work,you familiar with it ?

**Comment by avorima** [comment]
@jianglingxia Hey, sorry I don't use cinder-csi-plugin as well but our csi plugin sometimes takes up to 45 seconds for attach. We fixed our timeout issues by setting the `--timeout` flag of the [external-attacher](https://github.com/kubernetes-csi/external-attacher#important-optional-arguments-that-are-highly-recommended-to-be-used). Maybe that helps
