### ISSUE TITLE
Volume deletion not triggered when CSI Migration is enabled

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#77102]
Using GCE PD in-tree volumes with feature flags `CSIMigration=true,CSIMigrationGCE=true` with csi external provisioner `v1.1.0` when pvc is deleted with `RetentionPolicy=delete` the `Delete` call is never triggered on the CSI Driver.

This causes the PD to be leaked and the PV to never go away.

Feature is `Alpha` so I think the impact of this is not high. However, a fix is required for `Beta`.

Discovered through testing with https://github.com/kubernetes/kubernetes/pull/77101 :+1: 

/assign @ddebroy 
/cc @msau42 @saad-ali @jsafrane @leakingtapan

**Comment by jsafrane** [comment]
@davidz627, do you have any details? Is the PV `Released` (=i.e. bug in external provisioner) or is it still `Bound`? Any finalizers on the PV? Any interesting logs in PV controller or external provisioner?

> This causes [...]  the PVC to never go away.

PVC must be deleted for PV reclaim policy to be executed. Is there any remaining finalizer on PVC? Or did you mean the **PV** never goes away?

**Comment by ddebroy** [comment]
I think in the `shoulddelete` [path](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/controller/controller.go#L1140), I missed adding checking for the `knownProvisioners` (besides just the `provisionerName`) for migration scenarios.

**Comment by ddebroy** [comment]
We were missing the translation step during deletion causing external provisioner to reject the Delete request due to absence of `volume.Spec.CSI`. Fixed in https://github.com/kubernetes-csi/external-provisioner/pull/273/files

**Comment by davidz627** [comment]
Resolved by https://github.com/kubernetes-csi/external-provisioner/pull/273
