### ISSUE TITLE
[Failing test] GCE-5000: pods startup latency > 5s

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#77126]
**Which jobs are failing**:
gce-scale-performance

**Which test(s) are failing**:
density test

**Since when has it been failing**:
Run 1120236390706057221. 2019-04-22 10:02 CEST

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gce-scale-performance

**Reason for failure**:
PodStartupLatency error: pod startup: too high latency 50th percentile: 5.589886258s.
The 99th percentile is expected to be below 5s.

**Anything else we need to know**:
This issue addresses a density test regression. However it focuses on regression from 1120236390706057221 run.
The regression introduced in previous runs is described in https://github.com/kubernetes/kubernetes/issues/77080

**Comment by krzysied** [comment]
![pod_startup_regression](https://user-images.githubusercontent.com/25119199/56803980-87ebce00-6824-11e9-9059-77c6f0481233.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityPodStartup&Metric=create_to_schedule

**Comment by krzysied** [comment]
![configmaps](https://user-images.githubusercontent.com/25119199/56804133-fd579e80-6824-11e9-934a-2399a5535520.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness&Resource=configmaps&Scope=namespace&Subresource=&Verb=GET

This regression has also visible impact on api calls latency.

**Comment by wojtek-t** [comment]
Hmm - for this one, actually the only suspicious commit seems to be upgrade to golang 1.12.4:
https://github.com/kubernetes/kubernetes/pull/76576

which seems unfortunate, given that we didn't yet fully solve regression of 1.12.0

@krzysied - can you please run tests at head by just reverting to go 1.12.1 ?

**Comment by wojtek-t** [comment]
i'm fairly sure (given that here all phases of pod startup increase) it's exactly the same as:
https://github.com/kubernetes/kubernetes/issues/77127
So we can probably look into those together:

So I looked into what changed in 1.12.4 golang (comparing to 1.12.1), and my strong suspicion is on:
https://github.com/golang/go/commit/ec06e9ba4578d26fdb9c521d4042e3f9f7f42435

@liggitt - thoughts?

@cblecker @dims - FYI

**Comment by wojtek-t** [comment]
@bradfitz

**Comment by wojtek-t** [comment]
FTR - the range of commits on k8s side when the regression happened: https://github.com/kubernetes/kubernetes/compare/3cbb20c69...75d45bdfc

**Comment by liggitt** [comment]
That fixed a regression in 1.12 to make it behave closer to 1.11.x. It only impacts proxied paths, so would not affect Pod API calls

**Comment by wojtek-t** [comment]
Thanks Jordan. Apparently I was also wrong with the cpu-usage - that increased 4 runs earlier.

**Comment by wojtek-t** [comment]
So I looked into that range again (the k/k) part and after eliminating all that has no chance to break (comments, unrelated scripts, etc), there are 5 PRs in this range:
[doubtful] https://github.com/kubernetes/kubernetes/pull/76546
[doubtful] https://github.com/kubernetes/kubernetes/pull/76819
[doubtful] https://github.com/kubernetes/kubernetes/pull/76796
[doubtful] https://github.com/kubernetes/kubernetes/pull/76333
[probable] https://github.com/kubernetes/kubernetes/pull/76576 [upgrade to go1.12.4]

I think there are two things that we need to check first:
- if reverting back to go1.12.1 helps
- if there were changes in test-infra, perf-tests or sth like that that may have affected this.

**Comment by wojtek-t** [comment]
Hmm - this is an interesting graph too:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=coredns%2Fcoredns&Resource=CPU

Not sure what that really means, but it seems to be related...

**Comment by krzysied** [comment]
![pod_startup_regression_2](https://user-images.githubusercontent.com/25119199/57217382-c3d81d80-6ff2-11e9-8a5e-845ff4e3794d.png)

Currently pod startup latency is below 5s. It looks like #77158 could have fixed the issue. However the PR (#74690) that was reverted was merged 4 runs before regression happened.

**Comment by krzysied** [comment]
It looks like the regression was caused by increasing time needed by node-controller to list all pods for each node. This is result of [GCE-5000: density tests are failing](https://github.com/kubernetes/kubernetes/issues/77080).

**Comment by krzysied** [comment]
Currently this regression is fixed. I'm closing the issue.
