### ISSUE TITLE
Kubernetes unable to delete Azure managed disks when PVCs are deleted

### ISSUE THREAD

**Issue by fatal-exception** [kubernetes/kubernetes#77121]
**What you did**: We replaced our 400GB PVCs with 250 GB PVCs by updating the definition of the `volumeClaimTemplates` in our statefulsets. We deleted the statefulsets, pvc and pv objects and then recreated them the statefulset with the new `volumeClaimTemplates` value of 250GB.

**What you expected to happen**: We expected new 250GB Persistent Volumes to be created, and the old 400GBs to have their PVs, PVCs and managed disks to all be deleted. What actually happened is that the old 400GB PVs and PVCs were deleted from Kube API, but the old 400GB managed disks were left in Azure, still attached to their VMSS instances - neither deleted nor detached.

Repeated logs like this were seen in kube-controller-manager logs:
```
E0415 08:42:43.881737       1 goroutinemap.go:150] Operation for "delete-pvc-fc3a2283-5c73-11e9-8b9e-000d3a43f2ad[ff7d6464-5c73-11e9-8b9e-000d3a43f2ad]" failed. No retries permitted until 2019-04-15 08:42:44.381710687 +0000 UTC m=+1182604.493725388 (durationBeforeRetry 500ms). Error: "Operation cannot be fulfilled on persistentvolumes \"pvc-fc3a2283-5c73-11e9-8b9e-000d3a43f2ad\": StorageError: invalid object, Code: 4, Key: /registry/persistentvolumes/pvc-fc3a2283-5c73-11e9-8b9e-000d3a43f2ad, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: ff7d6464-5c73-11e9-8b9e-000d3a43f2ad, UID in object meta: "
```

**How to reproduce it (as minimally and precisely as possible)**: Exact reproduction is difficult as it seems to rely on an error state (perhaps in Azure storage?). I will do some testing with volumeClaimTemplates of differing sizes, and report back if i manage to reproduce it

**Anything else we need to know?**: We have a lot of error messages all the time for delays in detaching disks in Azure. E.g. when an attach is attempted, we often see this error:
```
E0415 08:41:57.694104       1 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/azure-disk//subscriptions/55e4f991-0d11-459a-93b1-b7e8326a1fdb/resourceGroups/k8s-deploy-infradev-we/providers/Microsoft.Compute/disks/k8s-deploy-infradev-we-dynamic-pvc-fc44e7f2-5c73-11e9-8b9e-000d3a43f2ad\"" failed. No retries permitted until 2019-04-15 08:43:59.69405252 +0000 UTC m=+1182679.806067221 (durationBeforeRetry 2m2s). Error: "AttachVolume.Attach failed for volume \"pvc-fc44e7f2-5c73-11e9-8b9e-000d3a43f2ad\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/55e4f991-0d11-459a-93b1-b7e8326a1fdb/resourceGroups/k8s-deploy-infradev-we/providers/Microsoft.Compute/disks/k8s-deploy-infradev-we-dynamic-pvc-fc44e7f2-5c73-11e9-8b9e-000d3a43f2ad\") from node \"k8s-agentpool1-16412930-vmss00000e\" : Attach volume \"k8s-deploy-infradev-we-dynamic-pvc-fc44e7f2-5c73-11e9-8b9e-000d3a43f2ad\" to instance \"/subscriptions/55e4f991-0d11-459a-93b1-b7e8326a1fdb/resourceGroups/k8s-deploy-infradev-we/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool1-16412930-vmss/virtualMachines/14\" failed with compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"ConflictingUserInput\" Message=\"Disk '/subscriptions/55e4f991-0d11-459a-93b1-b7e8326a1fdb/resourceGroups/k8s-deploy-infradev-we/providers/Microsoft.Compute/disks/k8s-deploy-infradev-we-dynamic-pvc-fc44e7f2-5c73-11e9-8b9e-000d3a43f2ad' cannot be attached as the disk is already owned by VM '/subscriptions/55e4f991-0d11-459a-93b1-b7e8326a1fdb/resourceGroups/k8s-deploy-infradev-we/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool1-16412930-vmss/virtualMachines/k8s-agentpool1-16412930-vmss_0'.\""
--
```
This seems to indicate that the Azure disk detach is taking longer than Kubernetes expects

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure, aks-engine 0.33.0
- OS (e.g: `cat /etc/os-release`): 
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux k8s-agentpool1-16412930-vmss000000 4.15.0-1039-azure #43-Ubuntu SMP Fri Feb 15 17:43:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: aks-engine for all configuration. Some customisation on a custom base image (LDAP integration, hardening)
- Network plugin and version (if this is a network-related bug): Azure CNI
- Others:

**Comment by fatal-exception** [comment]
To recreate, I tried:
1. create minimal statefulset with a volumeClaimTemplate
2. wait for pods to start and pvcs, pvs to be created
3. try deleting statefulset
4. try deleting pvc

I confirmed that deleting statefulset led to the managed disk being moved to state ''unattached', and that deleting the pvc led to the managed disk being deleted in Azure - so i was not able to recreate the issue

**Comment by andyzhangx** [comment]
@fatal-exception what's the interval between you delete the old statefulset and create the new statefulset in the first repro? If there is detach failure, there should be logs in kube-controller-manager.

**Comment by fatal-exception** [comment]
@andyzhangx  I think just a few minutes between delete and create.

Weirdly, we don't se any errors for the detach, just the following repeated 4 times:
```
DetachVolume.Detach succeeded for volume "pvc-fc3a2283-5c73-11e9-8b9e-000d3a43f2ad" (UniqueName: "kubernetes.io/azure-disk//subscriptions/55e4f991-0d11-459a-93b1-b7e8326a1fdb/resourceGroups/k8s-deploy-infradev-we/providers/Microsoft.Compute/disks/k8s-deploy-infradev-we-dynamic-pvc-fc3a2283-5c73-11e9-8b9e-000d3a43f2ad") on node "k8s-agentpool1-16412930-vmss000003" 
```

Actually I think I found the problem. In between the disk detach, I also see errors talking to the Azure API:
```
E0412 09:57:51.763808       1 attacher.go:138] azureDisk - Error checking if volumes ([k8s-deploy-infradev-we-dynamic-pvc-fc3a2283-5c73-11e9-8b9e-000d3a43f2ad]) are attached to current node ("k8s-agentpool1-16412930-vmss000003"). err=compute.VirtualMachinesClient#List: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="" Message="An error has occurred."
```

It looks like Azure storage API was throwing errors at the time of the original detach. I guess the kube-controller-manager eventually gives up?

Thanks

**Comment by JohnCMcDonough** [comment]
We're seeing an identical error when deleting a PV.

To give a bit more information, our Azure Premium SSD storage class has a reclaim policy set to retain. We want to be able to delete PVCs without affecting the PVs. 

The expected behavior on our end, is that the PV is deleted, and in turn deletes the Cloud provider's provisioned resources. This assumption contradicts what the documentation says here: 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain

> 1. Delete the PersistentVolume. The associated storage asset in external infrastructure (such as an AWS EBS, GCE PD, Azure Disk, or Cinder volume) still exists after the PV is deleted.
> 2. Manually clean up the data on the associated storage asset accordingly.
> 3. Manually delete the associated storage asset, or if you want to reuse the same storage asset, create a new PersistentVolume with the storage asset definition.


However, I've found other documents describing the retain policies, and that documentation implies a different purpose for this flag: 
https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume


I've seen conflicting/confusing documentation on what the intended behavior of this is.
