### ISSUE TITLE
GCE-5000: apiserver - increased cpu usage

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#77127]
**Which jobs are failing**:
gce-scale-performance

**Which test(s) are failing**:
density test

**Since when has it been failing**:
Run 1117699728771911683. 2019-04-15 10:03 CEST

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gce-scale-performance

**Reason for failure**:
Increased cpu usage of apiserver

**Anything else we need to know**:
The test is not failing, however the cpu usage increased from 10 cores to 25 cores (90th percentile).

**Comment by krzysied** [comment]
![apiserver_cpu](https://user-images.githubusercontent.com/25119199/56804868-73f59b80-6827-11e9-9d5a-72a8e0e019a6.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=kube-apiserver-gce-scale-cluster-master%2Fkube-apiserver&Resource=CPU

**Comment by krzysied** [comment]
![etcd_cpu](https://user-images.githubusercontent.com/25119199/56804980-e1a1c780-6827-11e9-923e-67116ed0715e.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=etcd-server-gce-scale-cluster-master%2Fetcd-container&Resource=CPU

The etcd cpu usage is affected in the same way.

**Comment by wojtek-t** [comment]
Hmm - it's also worth mentioning that etcd cpu-usage also signiifcant increased:

http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=etcd-server-gce-scale-cluster-master%2Fetcd-container&Resource=CPU

That may indeed suggest that https://github.com/kubernetes/kubernetes/issues/77080 is the culprit, as this is the PR that was touching both etcd and kube-apiserver.

@wenjiaswe ^^

**Comment by wenjiaswe** [comment]
@krzysied I was just wondering how is the performance test GCE-5000 look like after the revert PR #77158? Thanks!

**Comment by krzysied** [comment]
![apiserver_cpu_2 png](https://user-images.githubusercontent.com/25119199/57215968-c3d61e80-6fee-11e9-9dbc-d72343a7f624.png)

There is not visible change in apiserver cpu usage.

However there is an impact on pod startup latency #77126

**Comment by krzysied** [comment]
@wenjiaswe It looks like #77158 had impact on gce 5000 performance, even though the cpu usage hasn't changed. I posted update in #77080.

**Comment by wenjiaswe** [comment]
Thanks @krzysied!

**Comment by wojtek-t** [comment]
@krzysied - is there something we still want to debug here?

**Comment by krzysied** [comment]
![cpu_apiserver_fixed](https://user-images.githubusercontent.com/25119199/58694233-d4ca4380-8392-11e9-9bdb-2d6d975f0552.png)

IMHO cpu usage is strictly related to density test regression. After fixing regression, the cpu usage was reduced.
I think we can close this issue.
