### ISSUE TITLE
Custom scheduler leaves pod in pending state 

### ISSUE THREAD

**Issue by Alisd96** [kubernetes/kubernetes#77131]
I have deploying a custom scheduler after following instructions step by step like mentioned in Kubernetes Docs

Here's [a link] (https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/)

Pods I specify should be scheduled using scheduler "my-scheduler" leaves in Pending state while "my-scheduler" pod is Running state..

Kubectl version : -Client: v1.14.1 -Server: v1.14.0

kubeadm version : v1.14.1

```
alisd@kubeMaster:~$ kubectl get pods -n kube-system
NAME                                 READY   STATUS    RESTARTS   AGE
calico-node-944jv                    2/2     Running   4          45h
coredns-fb8b8dccf-hzzwf              1/1     Running   2          45h
coredns-fb8b8dccf-zb228              1/1     Running   2          45h
etcd-kubemaster                      1/1     Running   3          45h
kube-apiserver-kubemaster            1/1     Running   3          45h
kube-controller-manager-kubemaster   1/1     Running   3          45h
kube-proxy-l6wrc                     1/1     Running   3          45h
kube-scheduler-kubemaster            1/1     Running   3          45h
my-scheduler-66cf896bfb-8j8sr        1/1     Running   2          45h
```

```
alisd@kubeMaster:~$ kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
annotation-second-scheduler   0/1     Pending   0          4s
```

```
alisd@kubeMaster:~$ kubectl describe pod annotation-second-scheduler
Name:               annotation-second-scheduler
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             name=multischeduler-example
Annotations:        <none>
Status:             Pending
IP:                 
Containers:
  pod-with-second-annotation-container:
    Image:        k8s.gcr.io/pause:2.0
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jclk7 (ro)
Volumes:
  default-token-jclk7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jclk7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

```
alisd@kubeMaster:~$ kubectl logs -f my-scheduler-66cf896bfb-8j8sr -n kube-system

E0426 14:44:01.742799       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E0426 14:44:02.743952       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
.....
```

**Comment by xiaoxubeii** [comment]
You can add some logs to trace scheduling process, such as in: https://github.com/kubernetes/kubernetes/blob/f01c1401a9802cf650382983161dd587705d7444/pkg/scheduler/core/generic_scheduler.go#L183

**Comment by Alisd96** [comment]
I've found a solution

Add these lines:

```
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - watch
  - list
  - get
```
to the end of the output of this command (this opens a file for you to edit):

`kubectl edit clusterrole system:kube-scheduler`

The pod using the scheduler that I deployed is now Running

```
alisd@kubeMaster:~$ kubectl get pods 
NAME                          READY   STATUS    RESTARTS   AGE
annotation-second-scheduler   1/1     Running   0          9m33s
```


`kubectl describe pod annotation-second-scheduler
`

 ```
Events:
      Type    Reason     Age   From                 Message
      ----    ------     ----  ----                 -------
      Normal  Scheduled  12m   my-scheduler         Successfully assigned default/annotation-second-scheduler to kubemaster
      Normal  Pulled     12m   kubelet, kubemaster  Container image "k8s.gcr.io/pause:2.0" already present on machine
      Normal  Created    12m   kubelet, kubemaster  Created container pod-with-second-annotation-container
      Normal  Started    12m   kubelet, kubemaster  Started container pod-with-second-annotation-container

```

**Comment by danikam** [comment]
I've run into the same issue, but the solution of adding lines at the end of the 

`kubectl edit clusterrole system:kube-scheduler`


output doesn't seem to work. 

kubectl version: -Client: v1.12.7 -Server: v1.12.7
kubeadm version: v1.12.7

**Comment by Alisd96** [comment]
> I've run into the same issue, but the solution of adding lines at the end of the
> 
> `kubectl edit clusterrole system:kube-scheduler`
> 
> output doesn't seem to work for me.
> 
> kubectl version: -Client: v1.12.7 -Server: v1.12.7
> kubeadm version: v1.12.7


I think this is not a problem related to Kubernetes because when you run the command `kubectl edit clusterrole system:kube-scheduler` the default text editor of the OS will be open in terminal

**Comment by danikam** [comment]
> > I've run into the same issue, but the solution of adding lines at the end of the
> > `kubectl edit clusterrole system:kube-scheduler`
> > output doesn't seem to work for me.
> > kubectl version: -Client: v1.12.7 -Server: v1.12.7
> > kubeadm version: v1.12.7
> 
> I think this is not a problem related to Kubernetes because when you run the command `kubectl edit clusterrole system:kube-scheduler` the default text editor of the OS will be open in terminal

Thank you for your reply! I think there's a misunderstanding though - adding the lines to the file works fine, it just doesn't have the effect of making the annotation-second-scheduler pod run. It may just be related to a mismatch between the k8s version (1.12.7) I'm using and the fact that the https://github.com/kubernetes/kubernetes is on the latest version. About to re-try after checking out release-1.12 in the https://github.com/kubernetes/kubernetes repo.

**Comment by danikam** [comment]
Seems to be working now after checking out release-1.12 in the https://github.com/kubernetes/kubernetes repo, except that setting --leader-elect=true causes the my-scheduler pod to hang on `attempting to acquire leader lease`:

~~~~
[root@node1 custom_scheduler]# kubectl logs my-scheduler-7bc786d8df-kjkk5 -n kube-system
W0716 15:00:55.666430       1 options.go:272] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.
I0716 15:00:55.669129       1 server.go:128] Version: v1.12.11-beta.0.1+5f799a487b70ae
W0716 15:00:55.669159       1 defaults.go:210] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W0716 15:00:55.669887       1 authorization.go:47] Authorization is disabled
W0716 15:00:55.669903       1 authentication.go:55] Authentication is disabled
I0716 15:00:55.669915       1 deprecated_insecure_serving.go:48] Serving healthz insecurely on [::]:10251
I0716 15:00:56.571065       1 controller_utils.go:1027] Waiting for caches to sync for scheduler controller
I0716 15:00:56.671188       1 controller_utils.go:1034] Caches are synced for scheduler controller
I0716 15:00:56.671240       1 leaderelection.go:205] attempting to acquire leader lease  kube-system/kube-scheduler...
~~~~

**Comment by user2394** [comment]
I am fairly new to Kubernetes. I am also stuck with the very same issue, can someone guide me how to troubleshoot this issues

Client Version: v1.13.5
Server Version: v1.13.8

**Comment by danikam** [comment]
> I am fairly new to Kubernetes. I am also stuck with the very same issue, can someone guide me how to troubleshoot this issues
> 
> Client Version: v1.13.5
> Server Version: v1.13.8

Just to clarify - the issue you're seeing is that kube-scheduler runs ok after checking out release-1.13, but hangs when you try setting --leader-elect=true?

**Comment by yuanlinios** [comment]
the solution also works for v1.15.3. But I do not quite understand why access to storageclasses is needed since the default scheduler works without it

**Comment by jqmichael** [comment]
If it's reproducible with k8s mainline, shouldn't the doc be updated? 

https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/#run-the-second-scheduler-in-the-cluster
