### ISSUE TITLE
Inconsistent message size in Kubelet

### ISSUE THREAD

**Issue by gyuho** [kubernetes/kubernetes#77138]
**What happened**:

```
remote_runtime.go:173] ListPodSandbox with filter nil from runtime service failed: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (8398577 vs. 8388608)
kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (8398577 vs. 8388608)
```

**What you expected to happen**:

`ListPodSandbox` should not fail because of it's response size.

**How to reproduce it (as minimally and precisely as possible)**:

N/A.

**Anything else we need to know?**:

Run batches through Argo workflow, but I don't think it's specific to the workloads.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: Amazon Linux 2
- OS (e.g: `cat /etc/os-release`):

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

- Kernel (e.g. `uname -a`): 

```
Linux ip-192-168-89-250.us-west-2.compute.internal 4.14.106-97.85.amzn2.x86_64 #1 SMP Fri Mar 15 17:07:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

<br>
<br>
My question is:

https://github.com/kubernetes/kubernetes/blob/62219e1f66d56fd663fd017e2f43e6dca6f41d59/pkg/kubelet/dockershim/remote/docker_server.go#L29-L31

limit is 8 MB.

https://github.com/kubernetes/kubernetes/blob/62219e1f66d56fd663fd017e2f43e6dca6f41d59/pkg/kubelet/remote/utils.go#L27-L29

limit is 16 MB.

1. What's the difference between `pkg/kubelet/dockershim/remote` and `pkg/kubelet/remote`? `pkg/kubelet/dockershim/remote` is for Docker, and `pkg/kubelet/remote` is for containerd? Can somebody help understand the difference?
2. Why does `pkg/kubelet/dockershim/remote` have difference limit than `pkg/kubelet/remote`? I think we should give them the same limits.

/cc @dims

**Comment by dims** [comment]
@gyuho +1 to make it the same. as reviewers mentioned, it's a temporary thing as the right way to fix it is to have some pagination which is not available currently

https://github.com/kubernetes/kubernetes/pull/63977#issuecomment-390064094

**Comment by mattjmcnaughton** [comment]
@dims Thanks for the guidance - putting out a pr to bump the size rn.
