### ISSUE TITLE
cleanup features.PodPriority

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#77152]
As PodPriority has been GA in 1.14, and we've removed FIFO implementation in scheduler.

I think it'd good to remove code related with "checking if features.PodPriority feature gate is enabled or not" - as that's always true now.

/sig scheduling
/kind cleanup

**Comment by draveness** [comment]
I could open a PR to clean it up if it' ok to do so. 😆

**Comment by draveness** [comment]
Kindly ping @bsalamat for suggestions on this.
