### ISSUE TITLE
Permission denied on hugetlb due to wrong filename

### ISSUE THREAD

**Issue by arnarg** [kubernetes/kubernetes#77169]
**What happened**:
When running `kubeadm init --pod-network-cidr=10.244.0.0/16` on OpenSUSE Kubic for aarch64 (board with amlogic s905w) kubelet spits out the following error and exits.
`kubelet.go:1359] Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to set config for supported subsystems : failed to write 4611686018427387904 to hugetlb.64kB.limit_in_bytes: open /sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64kB.limit_in_bytes: permission denied`

**What you expected to happen**:
For kubelet to not error and exit.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know if this is the same for all ARM boards or just amlogic.

**Anything else we need to know?**:
`/sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64KB.limit_in_bytes` exists but not `/sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64kB.limit_in_bytes` (notice capitalization of `KB`).

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.14.1`
- Cloud provider or hardware configuration: Amlogic s905w board with 2GiB RAM.
- OS (e.g: `cat /etc/os-release`):
```
NAME="openSUSE MicroOS"
# VERSION="20190415"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20190415"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20190415"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"
```
- Kernel (e.g. `uname -a`): `Linux kube-master01 5.0.7-1-default #1 SMP Sat Apr 6 14:47:49 UTC 2019 (8f18342) aarch64 aarch64 aarch64 GNU/Linux`
- Install tools: kubeadm

**Comment by arnarg** [comment]
@kubernetes/sig-architecture-bug

**Comment by tedyu** [comment]
What do you see for the following:
```
ls -l /sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64KB.limit_in_bytes
```
thanks

**Comment by arnarg** [comment]
```
> ls -l /sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64KB.limit_in_bytes
-rw-r--r-- 1 root root 0 Apr 12 18:45 /sys/fs/cgroup/hugetlb/kubepods/burstable/hugetlb.64KB.limit_in_bytes
```

**Comment by plutoid** [comment]
same issue on:
 Linux aml 5.0.2-aml-s905 #5.77 SMP PREEMPT Mon Apr 1 17:41:33 MSK 2019 aarch64 GNU/Linux

root@aml:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by arnarg** [comment]
@plutoid I actually managed to get past the error by changing the array you found and also one in runc iirc.

This one:
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go#L402

Seeing as we're both using kernel 5.0 it's possible that the kernel changed things and fixing this might not be trivial without breaking Kubernetes on older kernels. I might be way off though.

**Comment by jbhannah** [comment]
@arnarg I saw the same error with a 5.1.7 kernel on openSUSE Tumbleweed aarch64 on a Raspberry Pi 3B, and I think it was a change in the kernel — either [this one](https://github.com/torvalds/linux/commit/a21b0b78eaf770c6c3814dd59d213cd6aa47eecd#diff-748d3c2b4b2d359382721f781bb53b21) or [this one](https://github.com/torvalds/linux/commit/5480280d3f2d11d47f9be59d49b20a8d7d1b33e8#diff-748d3c2b4b2d359382721f781bb53b21).

**Comment by odinuge** [comment]
Hi @jbhannah! Yes, after some investigation I ended up with the two commits you referred to too! :smile: 

The fix in `runc` just got merged https://github.com/opencontainers/runc/pull/2065, so hopefully we can get the k8s fix https://github.com/kubernetes/kubernetes/pull/78495 into master as soon as possible! (Even more background info inside the PR: https://github.com/kubernetes/kubernetes/pull/78495)
