### ISSUE TITLE
dl.k8s.io Can't visit

### ISSUE THREAD

**Issue by zjning95** [kubernetes/kubernetes#77175]
http://dl.k8s.io Can't visit

**Comment by tedyu** [comment]
What error did you get ?
I can see xml where the beginning reads:
```
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
<Name>kubernetes-release</Name>
<Prefix/>
<Marker/>
<NextMarker>
archive/anago-v1.10.0-alpha.1/k8s.io/kubernetes/_output-v1.10.0-alpha.1/release-stage/full/kubernetes/cluster/gce/container-linux/configure-helper.sh
</NextMarker>
<IsTruncated>true</IsTruncated>
```

**Comment by zgfh** [comment]
it seem we hardcode a url in code https://github.com/kubernetes/kubernetes/blob/0f4b55bbf2149f6993006d4df4bae3378a56beab/cmd/kubeadm/app/util/version.go#L41
can we change it to a param or add a way to disable version check for offline install?

**Comment by neolit123** [comment]
> _output-v1.10.0-alpha.1

try using kubeadm 1.12 at least, but best to move to 1.14.
it has support for offline mode and will use the version of the client if not internet connection is available.

/remove-kind failing-test
/triage support
/close
