### ISSUE TITLE
kubelet debug interface 

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#77177]
**What would you like to be added**:
Does kubelet have http debug interface?

**Why is this needed**:
When kubelet or dockerd or node is notReady, we want to know the important cache in kubelet, like pod inof,  pod status, containers..etc. These info can help to locate bugs.
Maybe k8s can add an http interface to save this memory status in file without restarting kubelet.

**Comment by liggitt** [comment]
kubelet:10250/pods surfaces pods as the node sees them

**Comment by liggitt** [comment]
These are set up in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go

**Comment by Nebulazhang** [comment]
@liggitt Wow, thanks very much.
