### ISSUE TITLE
Directory traversal (or path traversal)?

### ISSUE THREAD

**Issue by warmchang** [kubernetes/kubernetes#77182]
**What happened**:

Initial submission is in k3s repo, but after verification and Darren's reminder, it also exists in kubernetes.

TL;DR https://github.com/rancher/k3s/issues/387

Accessing the "https://k8s-server:6443/logs/" reveals the details of the /var/log directory and the contents of all the files below.

**What you expected to happen**:
Kubernetes users cann't view all the files & directories in the /var/log path.

**How to reproduce it (as minimally and precisely as possible)**:
Step by step: https://github.com/rancher/k3s/issues/387#issuecomment-486640766

![20190418095100](https://user-images.githubusercontent.com/13084624/56626704-626c9200-6675-11e9-8abe-ae0950e242c9.png)
![image](https://user-images.githubusercontent.com/13084624/56733398-98536880-6792-11e9-99cd-806bc723b4b6.png)

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1
- Cloud provider or hardware configuration: VM on openstack
- OS (e.g: `cat /etc/os-release`): Fedora 29 (Cloud Edition)
- Kernel (e.g. `uname -a`): Linux william 5.0.9-200.fc29.x86_64 #1 SMP Mon Apr 22 00:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Manual
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by yue9944882** [comment]
isn't the path protected from RBAC?

**Comment by warmchang** [comment]
The program startup parameters:

> kube-apiserver --advertise-port=6445 --service-account-issuer=k3s --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --allow-privileged=true --advertise-address=127.0.0.1 --bind-address=127.0.0.1 --requestheader-username-headers=X-Remote-User --watch-cache=false --service-cluster-ip-range=10.43.0.0/16 --api-audiences=unknown --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --tls-cert-file=/var/lib/rancher/k3s/server/tls/localhost.crt --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --insecure-port=0 --secure-port=6444 --tls-private-key-file=/var/lib/rancher/k3s/server/tls/localhost.key --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/token-node.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/token-node.key --requestheader-allowed-names=kubernetes-proxy --authorization-mode=Node,RBAC --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key

> kube-scheduler --port=10251 --bind-address=127.0.0.1 --secure-port=0 --kubeconfig=/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --leader-elect=false

> kube-controller-manager --kubeconfig=/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --leader-elect=false --allocate-node-cidrs=true --bind-address=127.0.0.1 --secure-port=0 --cluster-cidr=10.42.0.0/16 --root-ca-file=/var/lib/rancher/k3s/server/tls/token-ca.crt --port=10252

> kubelet --allow-privileged=true --fail-swap-on=false --kubeconfig=/var/lib/rancher/k3s/agent/kubeconfig.yaml --root-dir=/var/lib/rancher/k3s/agent/kubelet --seccomp-profile-root=/var/lib/rancher/k3s/agent/kubelet/seccomp --serialize-image-pulls=false --hostname-override=minikube --anonymous-auth=false --eviction-hard=imagefs.available<5%,nodefs.available<5% --cgroup-driver=cgroupfs --authentication-token-webhook=true --cluster-domain=cluster.local --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --resolv-conf=/etc/resolv.conf --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --kubelet-cgroups=/systemd/user.slice/user-0.slice --healthz-bind-address=127.0.0.1 --read-only-port=0 --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --cert-dir=/var/lib/rancher/k3s/agent/kubelet/pki --cluster-dns=10.43.0.10 --runtime-cgroups=/systemd/user.slice/user-0.slice --cni-bin-dir=/var/lib/rancher/k3s/data/e249e3fc5ccf8ea07732c672f3062154b47357f5c85e1735339f087752a0f3ee/bin --container-runtime=remote --address=127.0.0.1 --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.pem

**Comment by liggitt** [comment]
The logs proxying can be turned off with `--enable-logs-handler=false`

That is supported by cluster installers like https://github.com/kubernetes/kubernetes/blob/1039feeab745d62661657565285c06373c42fec2/cluster/gce/gci/configure-helper.sh#L1737

Even when enabled, that handler is still subject to authorization. With what credentials are you accessing the secured port? Are they superuser credentials?

**Comment by liggitt** [comment]
Cannot reproduce on v1.14.1:

```sh
$ hack/local-up-cluster.sh &
$ curl -k https://localhost:6443/logs/

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/logs/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

With sufficiently powerful credentials (cluster-admin-level credentials), you can request the `/logs/` endpoint, but that is working as designed if the apiserver did not disable log access completely:

```sh
$ kubectl get --raw /logs/ --v=6
I0428 14:27:56.193477   21725 loader.go:359] Config loaded from file /Users/liggitt/go/src/k8s.io/kubernetes/_output/certs/admin.kubeconfig
I0428 14:27:56.204049   21725 round_trippers.go:438] GET https://localhost:6443/logs/ 200 OK in 9 milliseconds
<pre>
<a href="cups/">cups/</a>
<a href="daily.out">daily.out</a>
<a href="debug.log">debug.log</a>
...
```

**Comment by warmchang** [comment]
@liggitt Thank you for reply!

Yes, it can be turned off with --enable-logs-handler=false.

But IMO the superusers are only for cluster-admin-level.

Like a typical LAMP program, as the administrator of WordPress, I can handle all the data, configurations and logs of WordPress, but this does not mean that I have permission to view files and directories that do not belong to me on the colocation host.

Going one step further, can we consider disable log access (--enable-logs-handler=false) by default if it's a configuration problem, not a ~~vulnerability~~.

**Comment by liggitt** [comment]
> Going one step further, can we consider disable log access (--enable-logs-handler=false) by default

Individual deployments are free to change their defaults, and I'm in favor of defaulting to less exposed configurations. To change the kube-apiserver default, we would need to deprecate the current default and wait the requisite time period (https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli)

**Comment by warmchang** [comment]
Mentioned by https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf

```
17. Directory traversal of host logs running kube-apiserver and kubelet
Severity: Medium                                       Difficulty: Low
Type: Data Exposure                                    Finding ID: TOB-K8S-026
Target: kube-apiserver, kubelet

Description
The kube-apiserver runs within the Control Plane of a Kubernetes cluster, acting as the
central authority on cluster state. Part of its functionality is serving files from /var/log on
the /logs[/{logpath:*}] routes of the kube-apiserver. It can be accessed with an
authenticated client, and is enabled by default (Figure 3). These routes for the
kube-apiserver are defined within kubernetes/pkg/routes/logs.go (Figure 1), and are
mounted in k8s.io/kubernetes/pkg/master/master.go (Figure 2). However, this
configuration allows an attacker without host privileges to access protected host logs.
...
```

**Comment by blurpy** [comment]
Based on #77611 it looks like the apiserver will remove the /logs/ endpoint, but what about the kubelet? As the original rancher issue discusses, the kubelet is affected by the same issue.

**Comment by camilamacedo86** [comment]
What is the info that could be checked before it is disabled that will no longer be checked by default? (ihmo) Providing this context/list can help out those that need to see if they will or do not want to enable that in their cluster.

**Comment by liggitt** [comment]
Audit logs (https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/) can be used to determine if the endpoint was being used, if they are enabled for `nonResourceURLs` `/logs/*`
