### ISSUE TITLE
Can't make a ref to pod "{pod_name}", container {container_name}: selfLink was empty, can't make reference

### ISSUE THREAD

**Issue by leo1515416043** [kubernetes/kubernetes#77192]
**What happened**:
pod already gone，but such error occur in kubelet logs
```
kuberuntime_container.go:66] Can't make a ref to pod "rabbitmq-1_default(79f2adec-1fa6-11e9-92be-ac853da031fa)", container rabbitmq-k8s: selfLink was empty, can't make reference
```
**What you expected to happen**:
no such error
**How to reproduce it (as minimally and precisely as possible)**:
I don't know
**Anything else we need to know?**:
How to solve it?
**Environment**:
- Kubernetes version (use `kubectl version`):  
1.9.4 
- OS (e.g: `cat /etc/os-release`):  
Alibaba Group Enterprise Linux Server release 7.2 (Paladin)
- Kernel (e.g. `uname -a`): 
3.10.0-327.ali2010.rc7.alios7.x86_64

**Comment by liggitt** [comment]
Can this be reproduced on 1.12+? 1.9 is no longer supporter

**Comment by mgdevstack** [comment]
Observed this error in #77543.

Kubectl Version:
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.2.182+6a23a6278f48ef", GitCommit:"6a23a6278f48ef286b860159a9cab81d71e30640", GitTreeState:"clean", BuildDate:"2019-05-03T06:57:44Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.2.182+6a23a6278f48ef", GitCommit:"6a23a6278f48ef286b860159a9cab81d71e30640", GitTreeState:"clean", BuildDate:"2019-05-03T06:40:28Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
```

Kind Version:
```
0.3.0-alpha
```

Docker Version:
```
Docker version 18.09.2, build 6247962
```

**Comment by Swetad90** [comment]
I am facing the same issue

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

I am running a statefulset .When the pods get evicted, it is recreated on another working node. But the container on the older node is up & kubelet keeps complaining about not finding the link:

    Aug 30 20:29:36 staging-node-4 kubelet[2173]: I0830 20:29:36.358238    2173 kubelet_pods.go:1073] Killing unwanted pod "thanos-compactor-0"
    Aug 30 20:29:36 staging-node-4 kubelet[2173]: I0830 20:29:36.362581    2173 kuberuntime_container.go:559] Killing container "docker://b22287cd406c3fe9eff4ff2df1792c6f84b5b92d001359f05ea73f8788715609" with 30 second grace period
    Aug 30 20:29:36 staging-node-4 kubelet[2173]: E0830 20:29:36.363416    2173 kuberuntime_container.go:71] Can't make a ref to pod "thanos-compactor-0_thanos(23096418-c7b2-11e9-9be7-005056bc2883)", container thanos: selfLink was empty, can't make reference
    Aug 30 20:29:38 staging-node-4 kubelet[2173]: I0830 20:29:38.362191    2173 kubelet_pods.go:1073] Killing unwanted pod "thanos-compactor-0"
    Aug 30 20:29:38 staging-node-4 kubelet[2173]: I0830 20:29:38.366884    2173 kuberuntime_container.go:559] Killing container "docker://b22287cd406c3fe9eff4ff2df1792c6f84b5b92d001359f05ea73f8788715609" with 30 second grace period
    Aug 30 20:29:38 staging-node-4 kubelet[2173]: E0830 20:29:38.367901    2173 kuberuntime_container.go:71] Can't make a ref to pod "thanos-compactor-0_thanos(23096418-c7b2-11e9-9be7-005056bc2883)", container thanos: selfLink was empty, can't make reference

**Comment by narayanan** [comment]
@Swetad90 We are running into similar issue in out environment, did you find the root cause / any workarounds?

**Comment by amnk** [comment]
I am seeing the same on GKE with `v1.13.7-gke.24`

**Comment by benvaljean** [comment]
Seeing the same with v1.10.11 , looks like its been around for a while

**Comment by liys87x** [comment]
I am seeing the same
Version: Kubernetes v1.10.5, Docker 1.13.1
Temporary solution：restart docker && restart kubelet

**Comment by dooman87** [comment]
Getting the same problem on GKE 1.13.12-gke.25. The pods that it can't reference were deleted with `--grace-period=0 --force` because they were stuck in `TERMINATING` status forever (> 4 hours)

**Comment by xmapst** [comment]
@Swetad90  We are running into similar issue in out environment, did you find the root cause / any workarounds?

**Comment by yuripastushenko** [comment]
We have clusters on bare metal, version 1.12.1 with different workloads.
In the cluster where a lot of short living pods are creating we experienced the same error.
```
kuberuntime_container.go:67] Can't make a ref to pod "job-dind-d76dz_jenkins-slave(5b9eaff9-7983-11ea-bd18-509a4c9f27d0)", container docker-dind: selfLink was empty, can't make reference
```
In this cluster we also sometime have some pods stucked in Terminating state (described in https://github.com/kubernetes/kubernetes/issues/75065).
```
remote_runtime.go:282] ContainerStatus "%s" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: %s
generic.go:241] PLEG: Ignoring events for pod %podname/%namespace: rpc error: code = Unknown desc = Error: No such container: %container
```
Also sometime in this cluster we have errors with orphaned pods described here - https://github.com/kubernetes/kubernetes/issues/60987
```
kubelet_volumes.go:140] Orphaned pod "%s" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
```
Those errors are only on one cluster with described workload.
Have somebody any suggestions about this problem?

**Comment by dims** [comment]
1.12.x is no longer supported

/close
