### ISSUE TITLE
[Feature] Add namespaced node taint

### ISSUE THREAD

**Issue by jeffreystoke** [kubernetes/kubernetes#77202]
**What would you like to be added**:

Node taints in namespaced scope.

**Why is this needed**:

Since the `Kubernetes` brings us `virtual cluster` via the concept `namespace`, I think it's reasonable to support namespaced node taint to prevent workloads in some namespaces from being scheduled and executed in nodes with such taint(s) forcibly, and admits workloads from other namespaces without requirement of toleration(s).

Current node taint works in an optional way, users could easily get their workloads scheduled to those tainted nodes with tolerations, but this should not happen when these workloads are not acceptable (e.g. workloads from `testing` to `production`).

This feature will enable:

1. Multi-staging Kubernetes, we can use single `Kubernetes` cluster (or more specifically, single master group) for both `testing`, `staging` and `production` with hardware isolation in the form of namespaces (no more pains for multi-cluster Kubernetes to handle the upgrade)
2. Enforce the protection for dedicated nodes from unexpected misconfiguration in deployment script in the way of restricting the namespace.
3. Multi-tenant Kubernetes cluster sharing one master with multiple node group (see [my multi-tenancy doc for `arhat-dev/aranya`](https://github.com/arhat-dev/aranya/blob/master/docs/Multi-tenancy.md#10-prevent-user-bar-from-creating-pods-runing-in-cluster-nodes) for the example in edge device management)

This feature makes the `virtual cluster` finally the meaning of `namespace`.

**Comment by jayunit100** [comment]
Per conv in slack, this is an interesting idea and ive seen similar stuff done before, but there are other ways to do this, admission controllers to force pods to be mapped to hosts or taint controllers for namespaces, and so on.  I'd suppose bringing this up as a discussion item in sig-node or scheduling , and see how other people are solving the problem.

**Comment by mattjmcnaughton** [comment]
Thanks for the idea @jeffreystoke . I agree with @jayunit100 re circulating this around different sigs and seeing if there are other ways to solve this problem or if there is general interest in your proposed solution. If the later, please create a Kubernetes Enhancement Proposal (KEP) to track your work. See the [KEP](https://github.com/kubernetes/enhancements/) homepage for more information.

**Comment by jeffreystoke** [comment]
@jayunit100 @mattjmcnaughton thanks to your replies, I will repost this issue to these slack channel, and read more docs, seems I'm doing feature request not quite the Kubernetes way.

**Comment by jeffreystoke** [comment]
Thank you everyone, I am closing it since we have podnodeselector admission controller for this purpose, and seems kubernetes guys would like to stay with that design for now.
