### ISSUE TITLE
Having an option "if different" for imagePullPolicy

### ISSUE THREAD

**Issue by mleneveut** [kubernetes/kubernetes#77201]
**What would you like to be added**:
I could be usefull to have an option "IfDifferent" for imagePullPolicy.

**Why is this needed**:
When we need an image tag "latest" (for example the Dynatrace oneAgent is :latest and we need it to be always at the lastest version to get Dynatrace's updates) but don't want to re-pull always the same image.

The option "IfDifferent" would behave like "Always", but before pulling, it would check the hash of the image with the hash already present locally. If different, it pulls the image.

/sig node

**Comment by danielqsj** [comment]
How can we get the hash of image before pulling it ? I think it depends on the remote image registry.

**Comment by mleneveut** [comment]
Good point, not sure about that. Thought it could be like a metadata of the image, that we could ask about first before pulling the whole image. You know like when you download a file, you have the file and aside the SHA or MD5.

**Comment by liggitt** [comment]
that's what Always does... it pings the registry for the sha that corresponds to the tag, and if different, pulls it. pull always is very cheap if the sha hasn't changed

/close
