### ISSUE TITLE
Stateless services get stuck in ContainerCreating forever

### ISSUE THREAD

**Issue by DarrienG** [kubernetes/kubernetes#77216]
**What happened**:
A number of our crons are getting stuck in ContainerCreating. Most of them are stateless, or use a ConfigMap or a secret or two.

**What you expected to happen**:
For the container to run, or to be rescheduled on another node.

**How to reproduce it (as minimally and precisely as possible)**:
We're not certain how to reproduce this. It's sporadic and hits about half of our crons at a time. We have a few machines with different specs and it seems to happen more often on our lower specced machines.

**Anything else we need to know?**:
The crons are mostly stateless. The containers are usually pretty big (.5Gi) but have maybe one ConfigMap or Secret each which are always present.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
On prem
-> 384Gi mem/Xeon gold (a few)
-> 60Gi mem/Intel(R) Xeon E5620 (one)
-> 65Gmem/Intel(R) Xeon(R) CPU E5-2620 (more)
- OS (e.g: `cat /etc/os-release`):

```
k8s-node $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.4.0
VERSION_ID=1911.4.0
BUILD_ID=2018-11-26-1924
PRETTY_NAME="Container Linux by CoreOS 1911.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux k8s-node 4.14.81-coreos #1 SMP Mon Nov 26 18:51:57 UTC 2018 x86_64 Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz GenuineIntel GNU/Linux
```

- Install tools:
ansible

- Network plugin and version (if this is a network-related bug):
Flannel and CoreDNS (probably not the issue, but included anyway)

**Comment by DarrienG** [comment]
It's worth noting that when this happens, we kill all pods stuck in ContainerCreating, they get rescheduled, and immediately work after that (until they don't again).

We aren't even close to our pod limit either.

**Comment by DarrienG** [comment]
More info - it looks like this may be caused by Kubernetes somehow getting into a strange state where it isn't sure whether or not containers for the image exist.

In the case today, we had two crons scheduled to run on the same host. The first cron is stuck in ContainerCreating and not running at all. The second cron is stuck in ContainerCreating with an actual error:

```
  Warning  FailedCreatePodSandBox  24m (x2 over 24m)  kubelet, somenode  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "some-cron-1556632800-6cz4w": Error response from daemon: Conflict. The container name "/k8s_POD_some-cron-1556632800-6cz4w_default_43c54add-6b50-11e9-a750-002590c43358_0" is already in use by container "b0754a19ded267561e6939389f406cdbfed6e9d681cb9cc0b0ec4e740daf587b". You have to remove (or rename) that container to be able to reuse that name.
```

However, if you look at the kubelet logs, you'll get:
```
Apr 30 14:30:37 somenode kubelet-1.13.2[5802]: E0430 14:30:37.715675    5802 generic.go:277] PLEG: pod some-cron-1556634600-dzwlp/default failed reinspection: rpc error: code = Unknown desc = Error: No such container: ebc3f620bfd6ebb1e874240843f8d524d4a31e11732228589f3524fb3a0102d7
```

If I'm understanding this correctly, it looks like Kubernetes can't schedule a new container to start running because an old one already exists, but isn't sure whether or not the container exists on the node.

**Comment by DarrienG** [comment]
Going to add /sig apps as well. This probably isn't just in issue for crons, we just happen to hit it more with crons.

**Comment by DarrienG** [comment]
Just as an update - this continues to affect us. We have some crons that have been stuck for up to 11 days. To fix, we kill the pod and the pods create and work almost instantly.

**Comment by DarrienG** [comment]
This continues to hit with services stuck eternally in ContainerCreating. We've upgraded to the latest CoreOS and all

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.3.0
VERSION_ID=2079.3.0
BUILD_ID=2019-04-22-2119
PRETTY_NAME="Container Linux by CoreOS 2079.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

Killing the pod usually fixes it. Even if it reschedules on the same node. This time it did not. The only fix was restarting kubelet.

**Comment by discordianfish** [comment]
@DarrienG Do you see container creation timeouts for that pod in the events or kubelet logs? Is it possible that you have very high IO load on the affected nodes?

I had the same issue due to containers with heavy write load on the container filesystem. This load caused docker’s create_container api calls to timeout but eventually finish. Kubernetes appears to have assumed that the operation failed and tried to re-create the pod, leading to `Conflict. The name ... is already in use by container ...` from which it didn’t recover.

**Comment by DarrienG** [comment]
Luckily (?) enough, this actually happened again today. It was on one of our compute nodes where we're constantly spinning up Jenkins build slaves and running builds. It's reasonable to assume that may be the answer.

**Comment by edmorley** [comment]
Hi! Could this be due to the issue described in #79398? (I'm presuming since these are crons they may be using a restartPolicy of never too?)

**Comment by discordianfish** [comment]
There is a design issue with how timing out docker commands are handled. It looks like Kubernetes just retries them without verifying whether the call actually succeeded eventually.

**Comment by DarrienG** [comment]
We specifically set a restartPolicy of never on most of our crons if that helps.

**Comment by DarrienG** [comment]
/remove-lifecycle-stale

This still happens to us.

**Comment by DarrienG** [comment]
I'll get it right on the first time some day.

/remove-lifecycle stale

**Comment by DarrienG** [comment]
This hit us again today. We're still on Kubernetes version `1.13.2` has it been fixed in a later version?

**Comment by discordianfish** [comment]
@DarrienG So id you had high IO load and high docker api response times?

**Comment by DarrienG** [comment]
It's hard for us to pinpoint, but the answer is probably yes. It was during the high point of the workday.

I'll see if I can catch it the next time it happens and look at load then.

**Comment by DarrienG** [comment]
We had the same issue again, and are here to report back.

Unfortunately our metrics for disk pressure seem to be malfunctioning at the moment, but we were able to capture CPU usage and general load.

CPU usage (orange is iowait, almost all cores were spinning at 100%) :

<img width="199" alt="Screen Shot 2019-10-24 at 12 17 12 PM" src="https://user-images.githubusercontent.com/5041953/67505043-8165d400-f658-11e9-8ad2-9f729a2a2983.png">

And load (hovering around 85%):

<img width="225" alt="Screen Shot 2019-10-24 at 12 17 19 PM" src="https://user-images.githubusercontent.com/5041953/67505154-bd993480-f658-11e9-92c0-34434055c7a7.png">

The graphs are a little sketchy to read, but the answer is that there was high CPU usage and reasonably high load at the time this happened again.

**Comment by DarrienG** [comment]
FYI we caught this again and the load was high again when this happened. I might as well confirm suspicions and say that this is the case.

**Comment by discordianfish** [comment]
@DarrienG Yeah as I expected, the problem here is that calls to docker timeout while docker still tries to execute the operation and finally successed. Kubernetes doesn't know about it and retries, leading to this conflict.
I'm afraid there is no easy fix for this. You'd have to have some docker api semantics that guarantees if a call times out it will actually not executed. You best options are simply avoiding such high load (which is what we did by upgrading to faster disks) or try crio-o instead, which might help. But even if it doesn't help, it's more likely to get a proper solution than something Docker based.

**Comment by colindean** [comment]
We have been encountering this issue periodically for more than a year now. Only manually killing the pod resolves the issue. 

I will attempt to gather system load data next time it occurs. I speculate that our cluster is nearly always under high load.

**Comment by c-horn** [comment]
Some details from the situation @colindean is referencing.

We have encountered this on multiple versions of kubernetes, but most recently today:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Our cronjob is also stateless with only minor mounted secrets (keys), is configured `restartPolicy: Never` and `concurrencyPolicy: Forbid`, and runs every 30 minutes.

ContainerCreating locks seem to correlate roughly with scheduling cadence because our daily crons fail substantially less often.

The most puzzling part is the `Events: <None>` which doesn't even show a `Scheduled` event or a pull failure. In the past (maybe previous k8s versions?) we would get docker image pull errors.

**Comment by vaxinate** [comment]
I have a similar problem to @colindean , or one very similar to it on version 1.14. Has anyone seen this recently on newer versions?

**Comment by DenisPalnitsky** [comment]
/remove-lifecycle stale

We had same issue that symptoms are similar to what @discordianfish described
