### ISSUE TITLE
[Failing Test] bazel-test-master is failing

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#77213]
**Which jobs are failing**:
`ci-kubernetes-bazel-test`

**Which test(s) are failing**:
`//cmd/kubeadm/app/util:go_default_test` ([spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-test/1122855768916234241))

**Since when has it been failing**:
Failing 4/27.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //cmd/kubeadm/app/util:go_default_test
-----------------------------------------------------------------------------
--- FAIL: TestChroot (0.10s)
    chroot_test.go:62: subprocess output:
        === RUN   TestChroot
        --- FAIL: TestChroot (0.00s)
            chroot_test.go:48: Expected file "/go_default_test" to exist, but got stat /go_default_test: no such file or directory
        FAIL
    chroot_test.go:64: subprocess error: exit status 1
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
FAIL
```

/kind failing-test
/priority critical-urgent
/milestone v1.15
/sig cluster-lifecycle
/cc @jimangel @smourapina @rarchk @alenkacz

**Comment by dims** [comment]
cc @neolit123

**Comment by neolit123** [comment]
>  FAIL: TestChroot (0.00s)

testing locally

**Comment by neolit123** [comment]
PR sent:
https://github.com/kubernetes/kubernetes/pull/77218
feel free to LGTM.

**Comment by alejandrox1** [comment]
Thank you very much @neolit123 and @dims for jumping on this so quickly
