### ISSUE TITLE
verify godeps failing on 1.14

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#77238]
**Which jobs are failing**:
https://testgrid.k8s.io/sig-release-1.14-blocking#verify-1.14

**Which test(s) are failing**:
verify.godeps

**Since when has it been failing**:
04-29@08:54PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.14-blocking#verify-1.14

**Reason for failure**:
```
Your Godeps.json is different:
--- Godeps/Godeps.json	2019-04-29 19:55:05.529878553 +0000
+++ /tmp/gopath.bJqhuY/src/k8s.io/kubernetes/Godeps/Godeps.json	2019-04-29 20:37:34.963600168 +0000
@@ -1705,7 +1705,7 @@
 		},
 		{
 			"ImportPath": "github.com/evanphx/json-patch",
-			"Comment": "v4.1.0-19-g5858425f75500d",
+			"Comment": "v4.2.0",
 			"Rev": "5858425f75500d40c52783dce87d085a483ce135"
 		},
 		{
Godeps Verify failed.
```

**Anything else we need to know**:
~This is also blocking cherry-pick PRs against the 1.14 branch.~  It's not a required test, maybe it should be...

/assign @liggitt @cblecker

**Comment by mtaufen** [comment]
@liggitt informs me that when someone adds a new tag to an existing sha it confuses godeps

**Comment by liggitt** [comment]
Looks like github.com/evanphx/json-patch added a new tag to an existing sha, which confuses godeps. Updating the normalized godeps.json file is the only fix

**Comment by mtaufen** [comment]
I'll send a fix, thanks

**Comment by mtaufen** [comment]
Fixed.
