### ISSUE TITLE
External provisioner to manage static imported PV

### ISSUE THREAD

**Issue by peter-wangxu** [kubernetes/kubernetes#77250]
**What would you like to be added**:

Currently user can import a static CSI PV with a storage class(`persistentVolumeReclaimPolicy : Delete`), then create a pvc to bind this PV. when create a pod with above pvc, the external attacher(with csi plugin) can attach/detach the pv without any problem.

while due to the current design, deletion of PVC would trigger an event on the PV: 
```yaml
status:
  phase: Failed
  message: >-
    Error getting deleter volume plugin for volume "pv-delete-immediate-ssd-1b":
    no volume plugin matched
```

below is full yaml of PV:
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-delete-immediate-ssd-1b
  selfLink: /api/v1/persistentvolumes/pv-delete-immediate-ssd-1b
  uid: a1d3f99d-6afd-11e9-a38e-00163e000652
  resourceVersion: '110962311'
  creationTimestamp: '2019-04-30T04:08:38Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 20Gi
  csi:
    driver: antcloud-csi
    volumeHandle: svcins-pv-delete-immediate-ssd-1b
    fsType: ext4
    volumeAttributes: {storage_type: cloud_disk}
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: pvc-delete-immediate-ssd-1b
    uid: c6fb80d1-6afd-11e9-a38e-00163e000652
    apiVersion: v1
    resourceVersion: '110961455'
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-disk-delete-immediate-ssd-1b
status:
  phase: Failed
  message: >-
    Error getting deleter volume plugin for volume "pv-delete-immediate-ssd-1b":
    no volume plugin matched
```
**Why is this needed**:

By design, the `Delete` policy should delete the PV allow with the deletion of PVC, while static PV by admin cannot deleted in this way. otherwise the the PV will be left as `Failed` and with error message.

**Comment by peter-wangxu** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by msau42** [comment]
If you want to get csi provisioner to delete a precreated PV, you need to add "pv.kubernetes.io/provisioned-by: <csi driver name>" annotation to your PV.

See https://github.com/kubernetes-csi/external-provisioner/issues/202 for followup discussion

/close
