### ISSUE TITLE
Can't remove terminating persistent volumes (PV)

### ISSUE THREAD

**Issue by XzenTorXz** [kubernetes/kubernetes#77258]
**What happened**:

The pod and namespaces got removed, but sometimes the pv still remains in "Terminating" status even with `ReclaimPolicy` `Delete`.

![grafik](https://user-images.githubusercontent.com/3819224/56957908-f395aa00-6b48-11e9-930a-90606adeebd9.png)

```
Name:            pvc-3252ac79-674e-11e9-9651-5404a6f17789
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: rancher.io/longhorn
Finalizers:      [external-attacher/io-rancher-longhorn]
StorageClass:    longhorn1rep
Status:          Terminating (lasts <invalid>)
Claim:           sentry/sentry-data
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        10Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            io.rancher.longhorn
    VolumeHandle:      pvc-3252ac79-674e-11e9-9651-5404a6f17789
    ReadOnly:          false
    VolumeAttributes:      numberOfReplicas=1
                           staleReplicaTimeout=60
                           storage.kubernetes.io/csiProvisionerIdentity=1556113772288-8081-rancher.io/longhorn
Events:                <none>
```
I tried to delete it with `kubectl delete pv pvc-3252ac79-674e-11e9-9651-5404a6f17789 --force --grace-period=0` but it gets stuck and remains terminating.

**What you expected to happen**:

PV's should get removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
single node setup with rancher
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
`Linux node2 4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 09:00:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
rancher
- Network plugin and version (if this is a network-related bug):
- Others:
We use Longhorn as our Storageclass

**Comment by cwdsuzhou** [comment]
You could check if `VolumeAttachment` still exist using `Kubectl get volumeattachment`.
Besides,  you can check if the volume detached successfully in csi driver logs.

**Comment by XzenTorXz** [comment]
The `VolumeAttachment` still exists, so i guess i create a ticket by the csi provisioner project.

The only problem I see here is that I see no connection between the `VolumeAttachment`and the `PersistentVolume`. I only can check all the attachment and see if the `PVC `still exists.

**Comment by ravibagri5** [comment]
You can get rid of this issue by manually editing the pv and then removing the finalizers which looked something like this:

  - kubernetes.io/pv-protection```
examples removing for finalizers

kubectl patch pvc pvc_name -p '{"metadata":{"finalizers":null}}'
kubectl patch pv pv_name -p '{"metadata":{"finalizers":null}}'
kubectl patch pod pod_name -p '{"metadata":{"finalizers":null}}'

**Comment by Cherishty** [comment]
@ravibagri5  your suggestion does work! But I still wonder why the finalizer is  **always** blocking the deletion?

**Comment by ravibagri5** [comment]
@Cherishty  Because, in your case, the finalizer value is set to 'protect' which will block the deletion. You can read more about finalizers here :
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers

**Comment by Cherishty** [comment]
@ravibagri5  Yes I give much of thumbs for your answer under this issue. which does disturb me a lot.
I wonder can we remove this definition when creating the pv/pvc? 

I try `finalizers: ~` or `finalizers: NULL` under **metadata** section but it does not work

**Comment by palashgoel7** [comment]
Here's a one-liner to remove finalizers from all pv in the system

`kubectl get pv | tail -n+2 | awk '{print $1}'  | xargs -I{} kubectl patch pv {} -p '{"metadata":{"finalizers": null}}'`

**Comment by sryabkov** [comment]
When I tried running the above one-liner provided by @palashgoel7 (although on a different type of object), I got the following error
`Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json`

The solution was to add `--type='merge'`. The final command was
```
kubectl get pg | tail -n+2 | awk '{print $1}' | xargs -I{} kubectl patch pg {} --type='merge' -p '{"metadata":{"finalizers": null}}'
```
> notice the object type is `pg` (postgres.kubedb.com) not `pv`, not sure if this is important

**Comment by FritschAuctores** [comment]
/remove-lifecycle stale

The problem is still there

**Comment by FritschAuctores** [comment]
/remove-lifecycle rotten

The problem is still there.

**Comment by dbsanfte** [comment]
Having resources stuck in a Terminating state is dodgy and strange. Just saying.

**Comment by 41tair** [comment]
The problem is still in 1.18.0

**Comment by stephen304** [comment]
Had this issue just now deleting a pvc, it got stuck in terminating for a few hours even though the container it was bound to seemed to have deleted fine. Patching the pvc with the command above resulted in "not found", but patching the pv worked to get it to delete fully.

**Comment by writeClearly** [comment]
/remove-lifecycle rotten
Present with v1.23.1

**Comment by obvionaoe** [comment]
/reopen
this issue is still relevant in the newest versions of Kubernetes

**Comment by chefchanyu** [comment]
you need to deleting the resource in order. delete pod -> delete pvc -> delete pv
