### ISSUE TITLE
Kube-proxy goes in  non-operational mode after cleanup without reporting when cleanup job is done

### ISSUE THREAD

**Issue by DockToFuture** [kubernetes/kubernetes#77264]
**What happened**:
After removing auto-cleanup logic for non-current kube-proxy modes, kube-proxy has to be called manual with ```cleanup``` flag(see, https://github.com/kubernetes/kubernetes/pull/76109). After switching the proxy mode from ```iptables``` to ```ipvs```, kube-proxy gets called with the ```--cleanup``` flag and goes in a non-operational loop after https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L696. When a new svc is created it is non-functional until kube-proxy gets restarted without the ```--cleanup``` flag.   
  
**What you expected to happen**:
Kube-proxy should report when the cleanup job is done and exit in a clean way. Currently it is hanging in an infinite loop.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1

/cc @vllry @zanetworker @timuthy

**Comment by vllry** [comment]
There is a fix for this in #76399, when I get to the office I’ll look at backporting it.

/priority important-soon
/assign @vllry
/remove-triage unresolved

**Comment by vllry** [comment]
@DockToFuture  I'm going to close this issue as a duplicate of #76727. The fix is in master and I'm working on backporting it.
