### ISSUE TITLE
test/soak/cauldron uses Docker Hub to push/pull image

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#77273]
We've deleted all repos from Docker Hub and will be retiring the org/user (ref: https://github.com/kubernetes/k8s.io/issues/237)

Apparently the `kubernetes/cauldron` repo is referenced for docker push and pull in https://github.com/kubernetes/kubernetes/blob/master/test/soak/cauldron/Dockerfile

It's unclear to me whether we have broken anything, or if this is dead code.  I would use https://cs.k8s.io to find out if this is referenced anywhere (aside from sundry vendor dirs)

If dead code: remove it

If used: move to test/e2e/images and follow the same pattern there used to push to gcr.io

/sig testing
/area test
/wg k8s-infra
/priority important-soon

/help
/good-first-issue
I believe this is a pretty straightforward issue and am happy to review whatever PR's are made for it

**Comment by caohe** [comment]
Could I have a try? But I cannot find the `test/e2e/images` directory.
