### ISSUE TITLE
Joining multiple masters to an existing HA cluster concurrently fails

### ISSUE THREAD

**Issue by jeanluclariviere** [kubernetes/kubernetes#77283]
**What happened**:
When attempting to join 2 masters to a cluster concurrently, one succeeds and the other fails. The error we get is:  ` "error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: Get https://10.10.10.10:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config: EOF"`

In this case, I was using ansible. It wasn't until I introduced "serial: 1" to join them one at a time did the error stop. I should also add that this did not stop workers from joining the cluster and I could do many of these at a time.

**What you expected to happen**:
Both master nodes to join the cluster

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to join 2 masters simultaneously via a script / ansible / programatically.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration: bare-metal
- OS (e.g: `cat /etc/os-release`): RHEL 7
- Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/close
hello,
1.14 does not support this, so you have to slightly delay the joining of control-plane nodes.

for 1.15 we have this change:
https://github.com/kubernetes/kubernetes/pull/76821/commits/bc8bafd825816844b1a93af98b22b86a3f32a65e
that will enable support for concurrent join, but the change cannot be backported for 1.14.
thanks.
