### ISSUE TITLE
While creating statfulsets pod , getting this issue "Warning  FailedCreate  4s (x14 over 35s)  statefulset-controller  create Pod ztslenvoylb-0 in StatefulSet ztslenvoylb failed error: The POST operation against Pod could not be completed at this time, please try again."

### ISSUE THREAD

**Issue by arun0704** [kubernetes/kubernetes#77290]
**What happened**:
I wrote the k8s initializer for watching statefulsets resorces and modify annotation and update the statefulsets. when i deploy my statefulset pods getting this issue.
"Warning  FailedCreate  4s (x14 over 35s)  statefulset-controller  create Pod ztslenvoylb-0 in StatefulSet ztslenvoylb failed error: The POST operation against Pod could not be completed at this time, please try again."

**What you expected to happen**:
Statefulsets pod should get created.

**How to reproduce it (as minimally and precisely as possible)**:
Step1:- Run this example for statefulsets.
https://github.com/gyliu513/jay-work/tree/master/k8s/example/kube-initializer-tutorial

step2:- Do helm install <your statefulsets helm chart name>

**Anything else we need to know?**:
Earlier i thought its free available  RAM issue but cleared cache/buff, not resolved issue.

**Environment**:
This test i am doing in minikube environment
this is minikube version and k8s version.

minikube version: v0.35.0

- Kubernetes version (use `kubectl version`):
[root: /home/dangi.arun/golang/src/kubernetes-initializer-tutorial_statefulset]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
[root: /home/dangi.arun/golang/src/kubernetes-initializer-tutorial_statefulset]$ kubectl describe statefulset.apps/ztslenvoylb
Name:               ztslenvoylb
Namespace:          default
CreationTimestamp:  Tue, 30 Apr 2019 19:33:22 +0530
Selector:           app=ztslenvoylb-label,release=ztslenvoylbtest
Labels:             app=ztslenvoylb-label
                    chart=ztslenvoylb-0.4.8
                    heritage=Tiller
                    release=ztslenvoylbtest
Annotations:        initializer.kubernetes.io/envoy: true
Replicas:           824638366224 desired | 0 total
Update Strategy:    OnDelete
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       app=ztslenvoylb-label
                danmippool=10.96.180.106-10.96.180.107-10.96.180.108
                danmsubnetmask=26
                envoylbintializer=envoylb
                release=ztslenvoylbtest
                serviceType=ZTSLENVOYLB_SERVICE
                vnfName=ztslenvoylbtest
                vnfType=ZTSL
  Annotations:  danm.k8s.io/interfaces:
                  [
                      {
                          "network": "danmed1",
                          "ip": "0.9.9.9",
                          "proutes": {
                              "0.0.0.0/0": "10.96.180.65"
                          }
                      }
                  ]
                networks: [ { "name": "calico"}, { "name": "danm"} ]
  Containers:
   ztsenvoylb:
    Image:      corepaas-docker-local.bhisoj70.apac.nsn-net.net/envoyhotrestartimagewithtls:0.5.80
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /usr/bin/supervisord
      -c
      /etc/supervisord.conf
    Environment:
      secretuserzts:      <set to the key 'username' in secret 'zts1ztssecret'>  Optional: false
      secretpasswordzts:  <set to the key 'password' in secret 'zts1ztssecret'>  Optional: false
    Mounts:
      /certs from certs (rw)
      /etc/envoy from config (rw)
      /var/DebugTrace/envoylb from shared-data (rw)
   consulagent-container:
    Image:       corepaas-docker-local.bhisoj70.apac.nsn-net.net/consul:0.5.80
    Ports:       8500/TCP, 8400/TCP, 53/TCP, 8600/TCP, 8443/TCP, 8080/TCP, 8301/TCP, 8302/TCP, 8600/TCP, 8300/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/consul
    Args:
      agent
      -retry-join=$(NODE_SERVICE_NAME).$(NAMESPACE).$(SERVICE_DOMAIN_NAME)
      -retry-join=$(NODE_SERVICE_NAME).$(NAMESPACE).$(SERVICE_DOMAIN_NAME)
      -retry-join=$(NODE_SERVICE_NAME).$(NAMESPACE).$(SERVICE_DOMAIN_NAME)
      -client=$(CLIENT_BIND_IP)
      -data-dir=/tmp/consul
      -bind=$(MY_POD_IP)
      -enable-script-checks=true
      -datacenter=$(DATACENTER_VALUE)
      -domain=$(DOMAIN_NAME)
      -node=$(MY_POD_IP)
    Environment:
      MY_POD_IP:             (v1:status.podIP)
      NAMESPACE:             (v1:metadata.namespace)
      NODE_NAME:            ztslb
      NODE_SERVICE_NAME:    sdservice
      SERVICE_DOMAIN_NAME:  svc.cluster.local
      DOMAIN_NAME:          default.svc.cluster.local
      DATACENTER_VALUE:     dc1
      CLIENT_BIND_IP:       0.0.0.0
    Mounts:
      /tmp/consul from data (rw)
   fluent-bit:
    Image:      corepaas-docker-local.bhisoj70.apac.nsn-net.net/lfsclient:0.5.80
    Port:       <none>
    Host Port:  <none>
    Environment:
      TARGET_IP:     127.0.0.1
      TARGET_PORT:   8888
      traceLevel:    trace
      logRetention:  2
      logPath:       /opt/log
      VNFNAME:       ZTSLBSERVICE
      PODNAME:        (v1:metadata.name)
    Mounts:
      /fluent-bit/etc from config-volume (rw)
      /var/log from shared-data (rw)
   registrationcontainer:
    Image:      corepaas-docker-local.bhisoj70.apac.nsn-net.net/alpine-curl:0.5.80
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      consulreg.sh
    Environment:
      SERVICENAME:        ztslenvoylb-service
      SDSFQDN:            127.0.0.1
      ZTSNAME:            zts1
      ZTSCLUSTERLBEXTIP:  
    Mounts:               <none>
  Volumes:
   data:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
   certs:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      configmapenvoylbcpserver
    Optional:  false
   shared-data:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
   config-volume:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       fluent-bit-config-servicemesh
    Optional:   false
Volume Claims:  <none>
Events:
  Type     Reason        Age                From                    Message
  ----     ------        ----               ----                    -------
  Warning  FailedCreate  4s (x14 over 35s)  statefulset-controller  create Pod ztslenvoylb-0 in StatefulSet ztslenvoylb failed error: The POST operation against Pod could not be completed at this time, please try again. @kubernetes/sig-api-machinery-Daniel Smith

**Comment by wangzhuzhen** [comment]
Met the same. Only get InnerError when POST to create pod.  The reason in my case is that  there already have an pod with the same podname and podnamspace in etcd yet (but not created  by k8s, because when create the old pod the POST request get timeout error return, when timeout error happend, we checked  and make sure that the old pod was written in etcd).

**Comment by decipher27** [comment]
Delete the sts and then redeploying should fix it. Worked for me!
