### ISSUE TITLE
Allow filtering in watch API

### ISSUE THREAD

**Issue by mpashka** [kubernetes/kubernetes#77300]
**What would you like to be added**:
In kubernetes watch API I want possibility to get watch notification only when specific field in target object is changed. In other words I want possibility to filter watch notifications on API server.

**Why is this needed**:
In big kubernetes clusters kubernetes API can be bottleneck. Each time API receives request it goes to etcd, fetches data from it and provides response. And this operation requires significant amount of CPU resources. And taking node list operation can be 
important thing to provide kubernetes networking and other things - e.g. it is actively used in [kube-router](https://github.com/cloudnativelabs/kube-router) project.
Also in our case node list operation is used to determine our app instances weights for proper load balancing - we store node weight in kubernetes node annotation.
In our kubernetes cluster installation we observed significant API server performance degradation when API server requests reached 4k/minute.

In order to reduce API server load we started to use kubernetes watch API. But using kubernetes watch for node is not perfect because update is emitted each time node receives heartbeat and updates appropriate condition in it's state. So in our app we receive 20 node update watches per 
second while we need only information about node weight annotation update. So I'd like to propose to allow filtering watch responses. That will significantly reduce traffic between api server and endpoints and reduce api server load.

**Comment by mpashka** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
Node heartbeats are moved out to a node lease object for exactly this reason. See https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0009-node-heartbeat.md

**Comment by mpashka** [comment]
In that case I assume I can close this issue.
In addition to that but not related to kubernetes watch API
I suppose kubernetes API executes all requests in parallel.
That can be not efficient. E.g. if node list request takes 1 sec and we get 3 node list requests per second then requesting all 3 is inefficient. Instead after receiving some request API implementation can check if same request is already executed and if yes then it can give same response to all requests when latter is ready. In that case we won't get api server performance degradation if number of the same requests increases.
