### ISSUE TITLE
Windows vSphere node crashing from VmsNicPxyLWMUninitialize

### ISSUE THREAD

**Issue by benmoss** [kubernetes/kubernetes#77318]
I recently had a node crash on the [vSphere Windows test job](https://k8s-testgrid.appspot.com/sig-windows#cfcr-vsphere-windows-master). The crash dump file points to 
the symbol `VmsNicPxyLWMUninitialize` from `VmsProxyHNic.sys`.

- [WinDbg logs](https://gist.github.com/benmoss/97656a165d3c4c042c22432a3e98725e)
- [Crash dump file](https://storage.googleapis.com/pivotal-e2e-results/crash%20dumps/dump05012019.dmp.tgz)

Windows version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
WIN-BMTD0B... Update           KB4486553     WIN-BMTD0B0DLM7\bosh 4/23/2019 12:00:00 AM
WIN-BMTD0B... Update           KB4480056     WIN-BMTD0B0DLM7\bosh 4/23/2019 12:00:00 AM
WIN-BMTD0B... Security Update  KB4493510     NT AUTHORITY\SYSTEM  4/23/2019 12:00:00 AM
WIN-BMTD0B... Hotfix           KB900259      NT AUTHORITY\SYSTEM  4/23/2019 12:00:00 AM
WIN-BMTD0B... Security Update  KB4493509     NT AUTHORITY\SYSTEM  4/23/2019 12:00:00 AM
```

cc @PatrickLang  @daschott  @kubernetes/sig-windows-bugs @dineshgovindasamy 

/sig windows

**Comment by michmike** [comment]
cc: @dineshgovindasamy  as well

**Comment by benmoss** [comment]
looks like this has been resolved by a recent KB
/close
