### ISSUE TITLE
kubectl try-again pod OR delete pod without re-scheduling

### ISSUE THREAD

**Issue by stanislavkozlovski** [kubernetes/kubernetes#77316]
**What would you like to be added**:
I'd like to add a way to short-circuits the backoff loop time and restart a pod.

**Why is this needed**:
You could achieve the same thing with `kubectl delete pod` but the issue with that is that it can reschedule the pod on another host

/kind feature
/sig node

**Comment by mattjmcnaughton** [comment]
Thanks for sharing this idea @stanislavkozlovski !

Do you mind explaining more about your use case? I.e. do you want all pods to exhibit this short-circuit behavior or only certain groups of pods or only in one off instances?

If this moves forward, I'd imagine you'd want to create a [Kubernetes Enhancement Proposal (KEP)](https://github.com/kubernetes/enhancements). Another path to consider is whether this could be accomplished without any changes to the core of Kubernetes... off the top of my head, could you deploy a controller running on your cluster which watches for crashing pods, and immediately deletes and reschedules them on the same host?

**Comment by stanislavkozlovski** [comment]
> could you deploy a controller running on your cluster which watches for crashing pods, and immediately deletes and reschedules them on the same host?

I think this would work, thanks for the idea!

> use case

Essentially, I'd like a one-off command to trigger this behavior. That would be more convenient and flexible than having a controller which does it automatically. You may not always want the stickiness that the controller gives you
