### ISSUE TITLE
Garbage collect VolumeAttachment objects to trigger detach

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#77324]
**What happened**:

*Background:* The attach/detach controller create `VolumeAttachment` objects for CSI Volumes to indicate that a volume needs to be attached to a node. It deletes the object to indicate that the volume should be detached.

*Problem:* If the Attach/Detach controller crashes, and in the meantime the pod using that volume is deleted, when the AD controller restarts, it won't know that the volume was previously attached and should be cleaned up.

**What you expected to happen**:

*Proposal:* We should have the AD controller periodically list all `VolumeAttachment` objects and for any that are not accounted for, update its internal actual/desired state caches so that the volume is gracefully detached.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/sig storage

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cwdsuzhou** [comment]
@saad-ali could I take it?

**Comment by msau42** [comment]
/lifecycle frozen
/reopen
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/pull/96617 should address this
