### ISSUE TITLE
building on mac results in KUBE_SERVER_PLATFORMS[@]: unbound variable

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#77349]
This issue was moved from https://github.com/kubernetes-sigs/kind/issues/471

**What happened**: building kubernetes with make fails on mac after https://github.com/kubernetes/kubernetes/pull/76974

**What you expected to happen**: building should not fail

**How to reproduce it (as minimally and precisely as possible)**: build from a mac

**Anything else we need to know?**: mapfile is not available on macOS bash. we should have a version check at minimum if we're going to use unsupported features (some of the code already does this)

cc @mtaufen @dims

**Comment by mtaufen** [comment]
@thockin 

Ugh. Does the containerized build at least still work on Mac? 
Ideally we'd stick to that as the recommended approach, since we can at least guarantee a correct environment.

I guess this is really Apple's fault, for refusing to upgrade the bash version on Macs (so they can avoid GPL) - the default on most Macs is 3.2.57, which dates to 2007 according to this blog post: https://itnext.io/upgrading-bash-on-macos-7138bd1066ba. 

I don't personally think we should support something that old. None of our CI uses a bash that old. It's ripe for breakage. You can install a newer version of bash via homebrew.

**Comment by BenTheElder** [comment]
the containerized build does not because this code runs on the host.

> I don't personally think we should support something that old. None of our CI uses a bash that old. It's ripe for breakage. You can install a newer version of bash via homebrew.

we should put a version check then, so we get a more understandable error.

**Comment by BenTheElder** [comment]
Up until this point we have supported it by using `read` instead, macOS's old system bash is annoying, but errors from deep within our bash waste more time supporting confused developers 🤷‍♂

**Comment by BenTheElder** [comment]
IIRC even in CI you ran into a bash version problem in fact just yesterday (?)

we could add a snippet like this to the main build if we don't want to switch to `read`:
https://github.com/kubernetes/kubernetes/blob/ef830e2bcf7a23a0ae74e8d8b9e8811a83142f38/hack/update-vendor-licenses.sh#L136-L147

**Comment by tpepper** [comment]
I worry about requiring brew and can imagine some folks systems might be managed in a way that disallow this.  Still it's reaaaaally painful having to debug and trying to keep things running with the crufty OSX dev userspace.  Given there are multiple snippets of brew install suggestions, it would be better imho to put them in one common top level place (ie: `build/common.sh`)

**Comment by BenTheElder** [comment]
@tpepper fair, On systems with restricted `/usr` at least https://docs.brew.sh/Installation#untar-anywhere should work, if _that_ doesn't work i'd expect the setup is just too restrictive to build at all (?)

The check doesn't have to require homebrew per se either, even just "Sorry building on macOS is unsupported" is more helpful than:

```console
... snipped output ...
/Users/bentheelder/go/src/k8s.io/kubernetes/hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variablemake: *** [quick-release-images] Error 1
```

**Comment by cblecker** [comment]
Fix inbound: https://github.com/kubernetes/kubernetes/pull/77362
