### ISSUE TITLE
Use Logf in test/e2e/framework/log

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#77359]
**What would you like to be added**:
As part of https://github.com/kubernetes/kubernetes/issues/76206, we agreed that breaking up `Logf` into it's own package would be ideal. The main benefit is that we are breaking potential import cycles that occur from having `Logf` in `test/e2e/framework`.  We now need to go through all the e2e tests that use `framework.Logf` and replace it with `Logf` in `test/e2e/framework/log`. 

@draveness already added a new log package in https://github.com/kubernetes/kubernetes/pull/77184. And here https://github.com/kubernetes/kubernetes/issues/77095#issuecomment-487803247 he broke down what tests need to be updated to use the new logger package in `test/e2e/framework/log`. 

- [ ] test/e2e_node (@draveness)
- [ ] test/e2e (@draveness)
- [ ] test/e2e/ui (@draveness)
- [ ] test/e2e/scheduling (@draveness)
- [ ] test/e2e/framework/ingress (@draveness)
- [ ] test/e2e/framework/providers (@draveness)
- [ ] test/e2e/framework/deployment (@draveness)
- [ ] test/e2e/framework/replicaset (@draveness)
- [ ] test/e2e/framework/volume (@draveness)
- [ ] test/e2e/auth (@johnSchnake)
- [ ] test/e2e/cloud (@lledru)
- [ ] test/e2e/network (@johnSchnake)
- [ ] test/e2e/lifecycle (@jiatongw)
- [ ] test/e2e/storage (@johnSchnake)
- [ ] test/e2e/storage/vsphere (@johnSchnake)
- [ ] test/e2e/storage/testsuites (@johnSchnake)
- [ ] test/e2e/instrumentation (@figo)
- [ ] test/e2e/common (@johnSchnake)
- [ ] test/e2e/scalability (@johnSchnake)
- [ ] test/e2e/upgrades (@johnSchnake)
- [ ] test/e2e/node (@johnSchnake)
- [ ] test/e2e/windows (@johnSchnake)
- [ ] test/e2e/autoscaling (@johnSchnake)
- [ ] test/e2e/kubectl (@jiatongw)
- [ ] test/e2e/apps (@figo)
- [ ] test/e2e/apimachinery (@figo)

Please comment below on what packages you would like to refactor

**Why is this needed**:
This is part of https://github.com/kubernetes/kubernetes/issues/75601 to refactor / clean up the testing e2e framework.

**Comment by jiatongw** [comment]
I can take `test/e2e/lifecycle` and `test/e2e/kubectl`

**Comment by johnSchnake** [comment]
I'll start with 
```
test/e2e/auth
  test/e2e/cloud
  test/e2e/network
```

**Comment by lledru** [comment]
hi, i can start with test/e2e/storage

**Comment by andrewsykim** [comment]
@johnSchnake hope you don't mind, assigning `test/e2e/cloud` to @lledru

**Comment by johnSchnake** [comment]
Nope, no problem at all. I just grabbed a few randomly.

**Comment by johnSchnake** [comment]
Also, to be clear @andrewsykim , there isn't a need to do 1 PR/package right? The whole idea of this is to prevent it from being in one huge PR but if we put 2-3 packages in a PR you dont mind?

**Comment by andrewsykim** [comment]
> Also, to be clear @andrewsykim , there isn't a need to do 1 PR/package right? The whole idea of this is to prevent it from being in one huge PR but if we put 2-3 packages in a PR you dont mind?

Yes! That was my intention. 2-3 packages per PR sounds reasonable to me

**Comment by alejandrox1** [comment]
@andrewsykim @draveness any chance we could hold of on `test/e2e/framework/deployment` just for a little while? I'm currently working on it on #77373 and `Logf` appears all over the place.

**Comment by draveness** [comment]
> @andrewsykim @draveness any chance we could hold of on `test/e2e/framework/deployment` just for a little while? I'm currently working on it on #77373 and `Logf` appears all over the place.

OK, I would start work on this package after your PR gets merged. :)

**Comment by draveness** [comment]
Here is a reminder: don't forget to import `log` package with alias - `e2elog`.

**Comment by johnSchnake** [comment]
Taking
```
  test/e2e/storage
  test/e2e/storage/vsphere
  test/e2e/storage/testsuites
```

**Comment by johnSchnake** [comment]
Taking 3 more:
```
  test/e2e/common
  test/e2e/scalability
  test/e2e/upgrades
```

**Comment by johnSchnake** [comment]
Taking one more set today:
```
  test/e2e/node
  test/e2e/windows
  test/e2e/autoscaling
```

**Comment by figo** [comment]
will start with 
```
  test/e2e/apps
  test/e2e/apimachinery
  test/e2e/instrumentation
```

**Comment by draveness** [comment]
Hi @andrewsykim, we could close this issue since the `Logf` function was removed from the framework package.
