### ISSUE TITLE
Add Scheduling Framework Configuration

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#77365]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and extension points for "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.

An important piece of the framework is the [framework configuration](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#configuring-plugins). The configurations instructs which plugins should be initialized and called by the framework. It also provides configuration to each plugin.
We should add the framework configuration to our scheduler component config. Add the logic to parse the configuration and pass it to the scheduling framework when scheduler is initialized.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by JieJhih** [comment]
I would like to work on it. Can you assign it to me?

**Comment by draveness** [comment]
Maybe we could split it into different phases.

**Comment by draveness** [comment]
Sorry, I just found out the un-reserved phase was already taken in #77288, I'd like to work on other phases if they were not taken.

**Comment by bsalamat** [comment]
@JieJhih Yes, I can assume that it is assigned to you, but I cannot formally assign it to you since you are not a member of K8s yet.
Please be aware that code freeze for 1.15 is May 30th. Your PR must be merged by then. Please give at least two week for the review process. In other words, you have about 10 days to send the PR. Please confirm that you can prepare the PR on time.

**Comment by matthewejohnson711** [comment]
I dont even know
