### ISSUE TITLE
Add Permit extension point for the scheduling framework

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#77372]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and extension points for "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.
"[Premit](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#permit)" is an important extension point that enables building advanced scheduling features, such as gang scheduling (AKA co-scheduling in K8s world). 
As a part of this effort, a new interface for permit plugins should be added. The main function of the plugin should return a "[Status](https://github.com/kubernetes/kubernetes/blob/6a8a3682919652ae668c389ed2f60efb770eed03/pkg/scheduler/framework/v1alpha1/interface.go#L47)" and a timeout. We also need to build the record keeping for pods in "wait" state and add a clean-up mechanism for pods whose timeout has expired.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by Huang-Wei** [comment]
I'd like to take this :)

**Comment by Huang-Wei** [comment]
Per offline talk with Abdullah (@ahg-g) would like to give a try on it.

@ahg-g Go ahead to take this.

**Comment by bsalamat** [comment]
Thanks, @Huang-Wei!
@ahg-g, we assume this is assigned to you, although we cannot formally assign it to you since you are not a member of K8s yet.
Please be aware that code freeze for 1.15 is on May 30th. Your PR must be merged by then. Please give at least two week for the review process. In other words, you have about 10 days to send the PR. Please confirm that you can prepare the PR on time.

**Comment by ahg-g** [comment]
Thanks @Huang-Wei and @bsalamat I will make this my priority and try my best to send a PR this week.
