### ISSUE TITLE
Updating Deployment annotations creates massive repetitive revision-history annotation, causing Deployment controller failure

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/kubernetes#77387]
**What happened**:
We created a Deployment and continuously updated an annotation on it periodically for a week. Eventually, we noticed errors in the controller-manager logs due to the `deployment.kubernetes.io/revision-history` annotation growing too large.

Example annotations:
```python
 {
    'deployment.kubernetes.io/desired-replicas': '2',
    'deployment.kubernetes.io/max-replicas': '3',
    'deployment.kubernetes.io/revision': '41',
    'deployment.kubernetes.io/revision-history': '41,41,41,41,41,41,41,41,41,41,41,41,41,.............'
}
```
controller-manager error:
```
I0502 01:39:20.871854       6 deployment_controller.go:485] Error syncing deployment yarn-crm/crm-qa-nm: ReplicaSet.apps "crm-qa-nm-7bf7b57dff" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

**What you expected to happen**:
1. Updates that do not change the revision number should not be added to the revision history.
2. The revision history should be capped at a fixed number of elements, it should not be possible to have unbounded growth for Deployments that are frequently updated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Deployment
2. Repeatedly modify an annotation on it and note that the `deployment.kubernetes.io/revision-history` annotation gets the same number appended every time.

**Environment**:
- Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"archive", BuildDate:"2019-04-16T22:45:40Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by PaulFurtado** [comment]
/sig scalability

Not 100% sure where this one fits, I couldn't determine which group owns the Deployment/ReplicaSet controllers, but this is a scalability problem

**Comment by janetkuo** [comment]
> 1. Updates that do not change the revision number should not be added to the revision history.
> 1. The revision history should be capped at a fixed number of elements, it should not be possible to have unbounded growth for Deployments that are frequently updated.

Agree with these, and if the limit is hit, the beginning of the history can be removed.
