### ISSUE TITLE
AWS: volumes are not attached if they were detached shortly before

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#77389]
E2e tests occasionally flake on AWS. It happens randomly to all tests that create a pod with a volume, write something to the volume, delete the pod and create a new one that reads from the volume. For example:

```
[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Dynamic PV (default fs)] provisioning should provision storage with mount options
```

## High-level description
1. A/D controller detaches a volume from a node (= the old pod died)
2. Immediately after that (under 1s) it tries to attach the same volume to the same node (=the new pod is scheduled and coincidentally it uses the same node).

In most cases this works, however, few times per day it happens that the second attach (in Kubernetes terms, see below) does not succeed and the test times out.

## Details
AWS cloud provider in Kubernetes heavily uses DescribeInstances and DescribeVolumes to check that a volume has been attached or detached:

In step 1. above, Kubernetes issues `DetachVolume` AWS API call and polls `DescribeVolumes` until it reports that the volume has been detached.

In step 2. above, Kubernetes issues `DescribeInstances` AWS API call to check what devices are used on a node and then it tries to find a free device for the volume that should be attached.

In this bug, `DescribeInstances` in step 2 reports the volume as **detaching**, even that `DescribeVolumes` reported the volume as **detached** in step 1. There was no `AttachVolume` call in between!

Kubernetes does not expect that this could ever happen and does not try attach the volume (it's not reported as detached, so why bother, right?). This is the code that finds out that the volume is not detached ("detaching" != "detached"):

https://github.com/kubernetes/kubernetes/blob/7f95735597bd621ee357a568f6c8d5f1b23c98ea/pkg/cloudprovider/providers/aws/aws.go#L2129

And few lines below we skip `AttachVolume`:
https://github.com/kubernetes/kubernetes/blob/7f95735597bd621ee357a568f6c8d5f1b23c98ea/pkg/cloudprovider/providers/aws/aws.go#L2140-L2156

We (OpenShift) run **lot of** Kubernetes e2e tests on AWS. We run them in a single AWS project and I guess we hit some timing issues / races on AWS side. We hit also AWS API quota pretty hard, but it does not seem to be related to this bug, I mention it only to illustrate the amount of things that run in parallel and that AWS may not like that load.

**Environment**:
Kubernetes v1.13.4

/kind bug
/sig aws
/sig storage

**Comment by jsafrane** [comment]
Flow from AWS API perspective:

```
Around 19:20:00: DetachVolume()
19:20:00.791625: DescrvibeVolumes(vol-0a90988d68c4166b5) = "detaching"
19:20:01.982537: DescrvibeVolumes(vol-0a90988d68c4166b5) = "detaching"
19:20:03.874333: DescrvibeVolumes(vol-0a90988d68c4166b5) = "detaching"
19:20:07.184488: DescrvibeVolumes(vol-0a90988d68c4166b5) = empty Attachments, interpreted as "detached"
19:20:07.404850: DescribeInstances(i-02b72eba7c14c5434) = volume vol-0a90988d68c4166b5 looks detached:
[{
  DeviceName: "/dev/xvda",
  Ebs: {
    AttachTime: 2019-04-30 18:20:37 +0000 UTC,
    DeleteOnTermination: true,
    Status: "attached",
    VolumeId: "vol-0714b435a9b3d1682"
  }
} {
  DeviceName: "/dev/xvdcv",
  Ebs: {
    AttachTime: 2019-04-30 19:16:53 +0000 UTC,
    DeleteOnTermination: false,
    Status: "attached",
    VolumeId: "vol-01a18b18d5521bf8c"
  }
}]
```

So far so good.


`19:20:07.932111: DescribeInstances(i-02b72eba7c14c5434)` = volume vol-0a90988d68c4166b5 **is back detaching**:
```
[{
  DeviceName: "/dev/xvda",
  Ebs: {
    AttachTime: 2019-04-30 18:20:37 +0000 UTC,
    DeleteOnTermination: true,
    Status: "attached",
    VolumeId: "vol-0714b435a9b3d1682"
  }
} {
  DeviceName: "/dev/xvdcv",
  Ebs: {
    AttachTime: 2019-04-30 19:16:53 +0000 UTC,
    DeleteOnTermination: false,
    Status: "attached",
    VolumeId: "vol-01a18b18d5521bf8c"
  }
} {
  DeviceName: "/dev/xvdcp",
  Ebs: {
    AttachTime: 2019-04-30 19:17:00 +0000 UTC,
    DeleteOnTermination: false,
    Status: "detaching",                 <---- WRONG
    VolumeId: "vol-0a90988d68c4166b5"
  }
}]
```

All timing is related to a response received, processed and logged by Kubernetes, which may be different to time corresponding request was sent. Everything in this report happens in sequence, there is no pararellism for a single volume. (Other volumes may be and often are attached / detached in parallel to this flow).

**Comment by jsafrane** [comment]
@leakingtapan @d-nishi @micahhausler, this looks like a bug in AWS itself, `DescribeInstances` seem to return old data randomly. Can you please check AWS side of things?

And we probably need fix / workaround on Kubernetes side. How can we check that a volume has been 100% detached if `DescribeInstances` returns inconsistent data? We can check if a volume is `detaching` in `getMountDevice` and not report is as attached here:

https://github.com/kubernetes/kubernetes/blob/7f95735597bd621ee357a568f6c8d5f1b23c98ea/pkg/cloudprovider/providers/aws/aws.go#L1756

This will cause Kubernetes to re-use the same device name and call `AttachVolume`. How bulletproof is it going to be?

And most importantly, what other parts of Kubernetes depend on `Describe*` being consistent?

**Comment by leakingtapan** [comment]
I confirmed internally. This is expected behavior for `DescribeInstances` and `DescribeVolumes` since ec2 API follows a [eventual consistence model](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency) where resource mutation might be not reflected immediately. This could explain why `DescribeInstances` returns a volume in detaching state even after the previous `DescribeInstances` call returns without the volume (detached)

> And we probably need fix / workaround on Kubernetes side. How can we check that a volume has been 100% detached if `DescribeInstances` returns inconsistent data? We can check if a volume is `detaching` in `getMountDevice` and not report is as attached here:

I think this won't work in the case when the volume is actually stuck in detaching state, since attaching a stuck volume could simply make it worse.

Given that, how about, in `AttachDisk` call, we return error when notice the volume is still being returned from `DescribeInstances` and we reply on the AD controller retry to check the state next time, and hopefully the state converges.

**Comment by jsafrane** [comment]
> Given that, how about, in AttachDisk call, we return error when notice the volume is still being returned from DescribeInstances and we reply on the AD controller retry to check the state next time, and hopefully the state converges.

If `DescribeInstances` can return stale data, depending on it in `AttachDisk` (or anywhere else) probably won't help, because we may again get new or stale data "randomly".

We call `DescribeInstances` in `AttachDisk` today to get fresh list of used/free devices. Depending on timing, two cases happen:

* Sometimes it returns that the volume is detaching and I can see `Got assignment call for already-assigned volume` in logs. Handling `DescribeInstances` as you suggest would help here.

* Sometimes it returns that the volume is detached. We find a new device name and call AWS `AttachVolume` and start polling `DescribeVolmes` for finished attach. This `DescribeVolume` then returns that the volume is **detaching from the node with the old device name**. So we're actually attaching a volume that's being detached and you wrote that's a bad thing. In my logs, I can see that Kubernetes recovers from this error:
  * Volume plugin AttachVolume() fails with `Error attaching volume "aws://us-east-1a/vol-0380c554281eeed57" to node "ip-10-0-137-111.ec2.internal": disk attachment of "aws://us-east-1a/vol-0380c554281eeed57" to "ip-10-0-137-111.ec2.internal" failed: requested device "/dev/xvdbh" but found "/dev/xvdbo"`
  * A/D controller re-tries
  * AttachVolume() calls AttachDisk() that calls `DescribeInstances` to find a free device. `DescribeInstances` returns that the volume is actually being attached to the node (I can see `Got assignment call for already-assigned volume` in logs)
  * AttachDisk() polls `DescribeVolumes` until the volume is attached.
  * -> it works, but to me it feels like it's just an accident. Checking`DescribeInstances` can't help in this case.

So, is there another way how to check that a volume is really detached? Or should we promote the error flow described above to official fix and add bunch of comments around so we won't remove / tweak the flow in future? What bad can happen when we call AWS `AttachVolume` on a volume that's detaching? AWS at least once reported that the volume is detached, so the volume probably is not be stuck.

**Comment by leakingtapan** [comment]
>  So we're actually attaching a volume that's being detached and you wrote that's a bad thing

I think it is only bad if the volume was previously stuck. But feels acceptable for me if it is being detached and the previous `DescribeVolume` call in `DetachDisk` at least confirmed once.

> So, is there another way how to check that a volume is really detached?

Confirming internally. But I suspect there isn't any. 

> What bad can happen when we call AWS AttachVolume on a volume that's detaching?

As long as the volume is not stuck (unmounted properly), we should be able to attach a detaching volume especially when it is at least confirmed being detached once from `DescribeVolume` call in `DetachDisk`. Even if the first time it doesn't work, retry should help recover the situation. How do you think?

**Comment by bertinatto** [comment]
According [to the page](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency) @leakingtapan pointed, AWS recommends two actions to manage the eventual consistency model (k8s already does **1**, but AFAIK not **2**, except when there's an exponential backoff among `Describe*` calls:

1) Run the appropriate `Describe*` call before modifying a resource
2) Add wait time between subsequent commands, even if `Describe*` returns a green response (this does infer that `Describe*` might return stale data)

Currently, k8s assumes a state based on a single `Describe*` green response, e.g., `DescribeVolume` is called repeatedly with an exponential backoff until it returns a given volume state.

What if it required at least **two** positive responses instead? What are the chances that `Describe*` would return stale data twice? I'd assume that **two** calls returning a detached volume (with exponential backoff in between, which enforces point **2** above)  would be reliable enough.

The downside is that this would increase the API usage, which is already high.

**Comment by bertinatto** [comment]
@leakingtapan, do you know if the native AWS `wait*` calls may be more stale-data-proof?

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.WaitUntilVolumeInUse

**Comment by jsafrane** [comment]
Looking at `EC2.WaitUntilVolumeInUse` implementation, it tries with constant backoff of 15 seconds (which I consider pretty large) and it returns when the first `Describe*` returns that the volume is in use, so basically the same as what Kubernetes does.

**Comment by jsafrane** [comment]
From what I saw, sometimes it happens that `DescribeVolume` reports a volume as detached, subsequent `DescribeInstances` reports that the volume is not attached, `AttachVolume` succeeds and only after that `DescribeVolume` shows that the volume is `detaching` (from the old device name) instead of `attaching`.

So Kubernetes got at least two confirmations that the volume is detached. What would be the correct delay to wait for second (third, ...) confirmation that the volume is really detached? IMO it would hurt our performance a lot.

**Comment by leakingtapan** [comment]
> @leakingtapan, do you know if the native AWS `wait*` calls may be more stale-data-proof?
> 
> https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.WaitUntilVolumeInUse

The Wait* function simply calls DescribeXX under the hood and uses some hard coded timeout. So it's similar to what kubernetes does like @jsafrane said.
