### ISSUE TITLE
Kube-dns has been CrashLoopBackOff

### ISSUE THREAD

**Issue by codingandcoding** [kubernetes/kubernetes#77388]
**What happened**:
# kubectl  get pods -n kube-system -o wide
NAME                                      READY     STATUS             RESTARTS   AGE       IP                NODE
calico-etcd-jknbh                         1/1       Running            1          13h       192.168.56.101    k8s-node1
calico-kube-controllers-99bdf4cd4-vz5sb   1/1       Running            16         18h       192.168.56.101    k8s-node1
calico-node-cd94b                         2/2       Running            22         18h       192.168.56.101    k8s-node1
calico-node-mknvs                         2/2       Running            6          18h       192.168.56.102    k8s-node2
calico-node-ttsdv                         2/2       Running            6          18h       192.168.56.103    k8s-node3
etcd-k8s-node1                            1/1       Running            6          18h       192.168.56.101    k8s-node1
kube-apiserver-k8s-node1                  1/1       Running            6          18h       192.168.56.101    k8s-node1
kube-controller-manager-k8s-node1         1/1       Running            6          18h       192.168.56.101    k8s-node1
kube-dns-86f4d74b45-7cwg8                 2/3       CrashLoopBackOff   257        18h       192.168.169.135   k8s-node2
kube-proxy-585bv                          1/1       Running            6          18h       192.168.56.101    k8s-node1
kube-proxy-kxd2x                          1/1       Running            2          18h       192.168.56.103    k8s-node3
kube-proxy-x7bk6                          1/1       Running            2          18h       192.168.56.102    k8s-node2
kube-scheduler-k8s-node1                  1/1       Running            6          18h       192.168.56.101    k8s-node1
kubernetes-dashboard-7b9c7bc8c9-ggz8t     1/1       Running            54         14h       192.168.169.134   k8s-node2

# kubectl get nodes
NAME        STATUS    ROLES     AGE       VERSION
k8s-node1   Ready     master    18h       v1.10.0
k8s-node2   Ready     <none>    18h       v1.10.0
k8s-node3   Ready     <none>    18h       v1.10.0

# kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns
I0503 10:19:56.894593       1 dns.go:48] version: 1.14.8
I0503 10:19:56.895373       1 server.go:71] Using configuration read from directory: /kube-dns-config with period 10s
I0503 10:19:56.895410       1 server.go:119] FLAG: --alsologtostderr="false"
I0503 10:19:56.895416       1 server.go:119] FLAG: --config-dir="/kube-dns-config"
I0503 10:19:56.895420       1 server.go:119] FLAG: --config-map=""
I0503 10:19:56.895422       1 server.go:119] FLAG: --config-map-namespace="kube-system"
I0503 10:19:56.895424       1 server.go:119] FLAG: --config-period="10s"
I0503 10:19:56.895428       1 server.go:119] FLAG: --dns-bind-address="0.0.0.0"
I0503 10:19:56.895430       1 server.go:119] FLAG: --dns-port="10053"
I0503 10:19:56.895434       1 server.go:119] FLAG: --domain="cluster.local."
I0503 10:19:56.895437       1 server.go:119] FLAG: --federations=""
I0503 10:19:56.895441       1 server.go:119] FLAG: --healthz-port="8081"
I0503 10:19:56.895443       1 server.go:119] FLAG: --initial-sync-timeout="1m0s"
I0503 10:19:56.895445       1 server.go:119] FLAG: --kube-master-url=""
I0503 10:19:56.895448       1 server.go:119] FLAG: --kubecfg-file=""
I0503 10:19:56.895451       1 server.go:119] FLAG: --log-backtrace-at=":0"
I0503 10:19:56.895454       1 server.go:119] FLAG: --log-dir=""
I0503 10:19:56.895457       1 server.go:119] FLAG: --log-flush-frequency="5s"
I0503 10:19:56.895460       1 server.go:119] FLAG: --logtostderr="true"
I0503 10:19:56.895462       1 server.go:119] FLAG: --nameservers=""
I0503 10:19:56.895464       1 server.go:119] FLAG: --stderrthreshold="2"
I0503 10:19:56.895466       1 server.go:119] FLAG: --v="2"
I0503 10:19:56.895468       1 server.go:119] FLAG: --version="false"
I0503 10:19:56.895472       1 server.go:119] FLAG: --vmodule=""
I0503 10:19:56.895505       1 server.go:201] Starting SkyDNS server (0.0.0.0:10053)
I0503 10:19:56.895688       1 server.go:220] Skydns metrics enabled (/metrics:10055)
I0503 10:19:56.895697       1 dns.go:146] Starting endpointsController
I0503 10:19:56.895699       1 dns.go:149] Starting serviceController
I0503 10:19:56.896015       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0503 10:19:56.896022       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0503 10:19:57.396351       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:19:57.896028       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:19:58.396374       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:19:58.896274       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:19:59.396136       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:19:59.896163       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:00.396454       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:00.896169       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:01.395903       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:01.896255       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:02.396232       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:02.896320       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:03.395889       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:03.895898       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:04.396240       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:04.896247       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:05.396276       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:05.895979       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:06.396127       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:06.896252       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:07.396174       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:07.896312       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:08.396066       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:08.895973       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:09.396232       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:09.896116       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:10.395981       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:10.896159       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:11.396308       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:11.895839       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:12.396186       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:12.896174       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:13.396226       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:13.895989       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:14.396180       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:14.895939       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:15.395861       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:15.896141       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:16.396083       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:16.896122       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:17.396044       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:17.896238       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:18.396114       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:18.896093       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:19.396352       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:19.896057       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:20.395911       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:20.896279       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:21.396188       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:21.896224       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:22.396140       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:22.896277       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:23.396247       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:23.896044       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:24.396003       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:24.896488       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:25.396234       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:25.896036       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:26.396028       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:26.896159       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
E0503 10:20:26.897158       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0503 10:20:26.897494       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0503 10:20:27.396321       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0503 10:20:27.896060       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...

# kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c dnsmasq
I0503 10:22:20.863098       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0503 10:22:20.863246       1 nanny.go:94] Starting dnsmasq [-k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0503 10:22:21.266327       1 nanny.go:119] 
W0503 10:22:21.266346       1 nanny.go:120] Got EOF from stdout
I0503 10:22:21.266359       1 nanny.go:116] dnsmasq[9]: started, version 2.78 cachesize 1000
I0503 10:22:21.266367       1 nanny.go:116] dnsmasq[9]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0503 10:22:21.266370       1 nanny.go:116] dnsmasq[9]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0503 10:22:21.266372       1 nanny.go:116] dnsmasq[9]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0503 10:22:21.266374       1 nanny.go:116] dnsmasq[9]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0503 10:22:21.266377       1 nanny.go:116] dnsmasq[9]: reading /etc/resolv.conf
I0503 10:22:21.266379       1 nanny.go:116] dnsmasq[9]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0503 10:22:21.266381       1 nanny.go:116] dnsmasq[9]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0503 10:22:21.266383       1 nanny.go:116] dnsmasq[9]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0503 10:22:21.266386       1 nanny.go:116] dnsmasq[9]: using nameserver 30.14.129.245#53
I0503 10:22:21.266388       1 nanny.go:116] dnsmasq[9]: using nameserver 30.14.128.82#53
I0503 10:22:21.266390       1 nanny.go:116] dnsmasq[9]: using nameserver 10.65.0.201#53
I0503 10:22:21.266392       1 nanny.go:116] dnsmasq[9]: read /etc/hosts - 7 addresses

# kubectl logs -n kube-system kube-dns-86f4d74b45-7cwg8 -c sidecar
I0503 10:22:41.860848       1 main.go:51] Version v1.14.8
I0503 10:22:41.860996       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0503 10:22:41.861046       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
I0503 10:22:41.861136       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, you are running a unsupported version of k8s. the last supported version is 1.12, which will go out of scope when 1.15 is released.
```
k8s-node1 Ready master 18h v1.10.0
k8s-node2 Ready 18h v1.10.0
k8s-node3 Ready 18h v1.10.0
```

for 1.10 you can try searching for help on stackoverflow or our support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example
thanks

/close

**Comment by codingandcoding** [comment]
> hi, you are running a unsupported version of k8s. the last supported version is 1.12, which will go out of scope when 1.15 is released.
> 
> ```
> k8s-node1 Ready master 18h v1.10.0
> k8s-node2 Ready 18h v1.10.0
> k8s-node3 Ready 18h v1.10.0
> ```
> 
> for 1.10 you can try searching for help on stackoverflow or our support channels:
> https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example
> thanks
> 
> 
hi，my kubectl version is v1.10.0
# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
