### ISSUE TITLE
kubectl version cmd not working correctly

### ISSUE THREAD

**Issue by chaos234** [kubernetes/kubernetes#77428]
**What happened**: When I use `kubectl version` the output looks like the following: https://i.imgur.com/Td86Faj.png

**What you expected to happen**: It should normaly tell `Client Version: 1.14.1` or smth. similar.

**How to reproduce it (as minimally and precisely as possible)**: Unsure, when this happened. It seems that smth. is broken within kubectl, why evert.

**Anything else we need to know?**:

Nothing, what can help for now. Otherwise ask for it please :)

**Environment**:
- Kubernetes version (use `kubectl version`): Can be read out from the image above :)

- Cloud provider or hardware configuration: 4x8GB RAM, 2x3 TB (SWRAID 0, no swap), I7-2600

- OS (e.g: `cat /etc/os-release`): Debian 9 (stretch)
- Kernel (e.g. `uname -a`): 4.9.0-9-amd64 Debian 4.9.168-1 (2019-04-12)
- Install tools: What is meant by this?
- Network plugin and version (if this is a network-related bug): not needed
- Others:

**Comment by liggitt** [comment]
The output lists the full client version info, including build date, git version, etc

/close

**Comment by chaos234** [comment]
And why am I getting then the following error: https://i.imgur.com/1LptHOJ.png

/open

**Comment by liggitt** [comment]
kubectl shows the client version, and the server version it is configured to talk to

the server response was malformed, which means kubectl is configured to talk to a server that is not running kubernetes (it appears to be returning an html response)

**Comment by liggitt** [comment]
the issue was closed because this is a configuration error, not a bug in kubectl
