### ISSUE TITLE
API to provide the cluster host/ip for a Golang project when it in running inside of the cluster

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/kubernetes#77444]
**What would you like to be added**:

**API to provide the cluster host/ip for a Golang project when it in running inside of the cluster**

**What is my goal?**

* Via the `k8s.io/client-go` I would like to get the cluster HOST ( public hostname or IP ) from inside of the cluster
* By a [Golang operator project](https://github.com/operator-framework/operator-sdk), I'd like to be able to get the cluster host ( public hostname or IP ) and create an ingress object with this value in runtime.

**What means inside of the cluster? How I am checking it inside of the cluster?**
* By developing a Golang operator which is deployed and running on a Minishift/Kube cluster.

**NOTE:** The [rest.Config.host](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L57) will not have the same value from inside and outside of a cluster and I am just looking for a way to get the cluster Host(public hostname/IP/Master) from the API in the project.

> When running outside the cluster, kubectl cluster-info and other clients use the cluster.server value in your $KUBECONFIG. This typically uses a hostname or IP that is routable to the cluster API server from outside the cluster.

> When running inside the cluster, clients use the $KUBERNETES_SERVICE_HOST environment variable, which comes from the kubernetes.default.svc service. This host/IP is typically only routable inside the cluster.

Example:

```go
	cfg, _:= config.GetConfig()
	var hostname cfg.Host //HERE

         cfg, _:= rest.InClusterConfig()
	var hostname cfg.Host	//HERE
```

**Suggestion**

 Add a new attribute in [rest.Config](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L57) to provide this value. For example, masterHost = ""  

**Why is this needed**:

It shows a common need. IMHO a dev could need to know this info for many reasons. However, for me it was required for:

* Create an Ingress object with the host value because OCP will just create properly its Route object based in an Ingress if it has the HOST value.

**Comment by camilamacedo86** [comment]
@kubernetes/sig-api-machinery

**Comment by camilamacedo86** [comment]
@liggitt I updated the first comment in order to make it more clear. What evidence you are looking for? Has anything else that I could provide in order to help you with?

**Comment by liggitt** [comment]
the rest.Config is simply a config struct. If you populate it from a kubeconfig file, it contains the URL specified for the cluster in the kubeconfig file. If you populate it with InClusterConfig, it contains the value of KUBERNETES_SERVICE_HOST. I'm not sure I understand what you are asking for inside the cluster… you can provide a process inside the cluster an explicit kubeconfig, and it will behave identically to the process run outside the cluster. 

The only "API" for obtaining an address at which to speak to the apiserver is the KUBERNETES_SERVICE_HOST envvar. There may not be a public hostname or IP, or there could be more than one, so I'm not sure an API for that has a clear implementation. It also isn't clear what the desired interaction to ingress is.

**Comment by camilamacedo86** [comment]
Hi @liggitt,

Following some clarofications.

**What is the goal?**

* Via the `k8s.io/client-go` I would like to get the cluster HOST ( public hostname or IP ) from inside of the cluster
* By a Golang operator project, I'd like to be able to get the cluster host ( public hostname or IP ) and create an ingress resource with this value in runtime.

**What means inside of the cluster? How I am checking it inside of the cluster?**
* By developing a Golang operator which is deployed on a Minishift/Kube

NOTE: It is clear that the value of rest.Config.host will not be the same when the app is executed locally and when it is executed in the cluster. 

> When running outside the cluster, kubectl cluster-info and other clients use the cluster.server value in your $KUBECONFIG. This typically uses a host name or IP that is routable to the cluster API server from outside the cluster.

> When running inside the cluster, clients use the $KUBERNETES_SERVICE_HOST environment variable, which comes from the kubernetes.default.svc service. This host/IP is typically only routable inside the cluster.

Following an example of the code. 

```go
	cfg, _:= config.GetConfig()
	var hostname cfg.Host //HERE

         cfg, _:= rest.InClusterConfig()
	cfgHost := cfg.Host	//HERE
```

**Suggestions**
* add a new attribute in  [rest.Config](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L57) to provide this value
* change the logic which set up the value in the host attribute to ensure that it will have the cluster HOST (public hostname or IP ) always return.

**Comment by liggitt** [comment]
It sounds like you are wanting a way, from inside a pod, to know what address a user outside the cluster should use to speak to the apiserver. There are a few problems I see with that:
* that is not information the apiserver has today, so would require adding configuration to the apiserver
* it is not the case that there is always a single hostname or IP address extra-cluster users should use to speak to an API server (there might be zero, or there might be more than one)
* if there are more than one, it's not clear how to select the right one

Additionally, the motivation for configuring ingress objects with hosts pointed at the apiserver is not clear.

Given the difficulty in adding this configuration, in selecting appropriate value(s) for the apiserver, and in making use of those values correctly, my recommendation would be to configure your operator with knowledge of an external host it should use, rather than try to add this as API.

**Comment by deads2k** [comment]
> It sounds like you are wanting a way, from inside a pod, to know what address a user outside the cluster should use to speak to the apiserver. There are a few problems I see with that:
> 
> * that is not information the apiserver has today, so would require adding configuration to the apiserver
> * it is not the case that there is always a single hostname or IP address extra-cluster users should use to speak to an API server (there might be zero, or there might be more than one)
> * if there are more than one, it's not clear how to select the right one
> 
> Additionally, the motivation for configuring ingress objects with hosts pointed at the apiserver is not clear.
> 
> Given the difficulty in adding this configuration, in selecting appropriate value(s) for the apiserver, and in making use of those values correctly, my recommendation would be to configure your operator with knowledge of an external host it should use, rather than try to add this as API.

This has come up before and we attempted to solve it with discovery, but the results were not good.  A few years out and I've never seen the information from the discovery doc used and I know some distributions always hardcode the value or leave it out.

Deciding how particular agents should access the kube-apiserver is outside the scope for the kube-apiserver machinery today and is likely to remain that way for the reasons Jordan indicated.

/close

**Comment by camilamacedo86** [comment]
Hi @deads2k and @liggitt,

### Comments in line.

> * that is not information the apiserver has today, so would require adding configuration to the apiserver

Yes, it is not and because of this its a feature request :-)

> * it is not the case that there is always a single hostname or IP address extra-cluster users should use to speak to an API server (there might be zero, or there might be more than one)

Following the possible solutions:
* The attribute can be a []string in this way this value can be 0..N 
* Should be great if it could have the cluster hostname/master Virtual IP where the pod is deployed and running if it is a multi-cluster installation. 

> if there are more than one, it's not clear how to select the right one
* Should make sense return the value referent the cluster where the call is made. For example, From the pod, is not possible to get its mater and then get this value?

> Additionally, the motivation for configuring ingress objects with hosts pointed at the apiserver is not clear.

### Example to clarifies the limitations and reason for this 

* By using the [Operator framework](https://github.com/operator-framework) a dev is able to build the resources in runtime as follows. 
* Let's think in the scenario where the dev will implement a deployment and service objects and would like to add an ingress to expose this service. Following the Ingress implementation as an example.

```go
ing := &v1beta1.Ingress{
		TypeMeta: v1.TypeMeta{
			APIVersion: "extensions/v1beta1",
			Kind:       "Ingress",
		},
		ObjectMeta: v1.ObjectMeta{
			Name:      m.Name,
			Namespace: m.Namespace,
			Labels:    ls,
		},
		Spec: v1beta1.IngressSpec{
			Backend: &v1beta1.IngressBackend{
				ServiceName: m.Name,
				ServicePort: intstr.FromInt(int(m.Spec.Port)),
			},
			Rules: []v1beta1.IngressRule{
				{
					Host: //FIXME: Here is required to inform the clusterHostname in order to make it work well as expected
					IngressRuleValue: v1beta1.IngressRuleValue{
						HTTP: &v1beta1.HTTPIngressRuleValue{
							Paths: []v1beta1.HTTPIngressPath{
								{
									Backend: v1beta1.IngressBackend{
										ServiceName: m.Name,
										ServicePort: intstr.FromInt(int(m.Spec.Port)),
									},
									Path: "/",
								},
							},
						},
					},
				},
			},
		},
	}
```
**NOTE:** The HOST is optional according to the API, however, the service will not be expose as expected if this information be not informed here.

* The OCP to attend its user has the [v1.Route](https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html). 
* It has many facilities compared with the [Ingress](https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_ingress, however, it is not the point
* When an [Ingress](https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_ingress) is applied in an OCP cluster it will generate automatically a route for it in order to keep its compatibility but without informing the HOST this route will not be created with the required information in order to work properly.

### How much it is important?

* Without this feature implemented we are not able to automate the need to expose services by using the Operator Framework properly for applications which will be running in Kuberntes and/or Openshift 
* Without this implementation is hard dev operator projects which will work and support both (OCP and Kuberntes)
* Also, I can think in many reasons and needs that can be required to know the public host of the cluster where the resource is applied and running when we are developing operator projects in order to automate the installation/managing/packing and etc of applications in both. 

### How you can check this scenario?

* In a Minishift install a deployment with a node.js app
* Create its service and expose it with the route. You will check that you are able to access the NodeJS app by the URL generated. 
* Now create an ingress.yaml informing the host and apply it. You will see a route created based on the ingress and when you access the URL it works perfectly well.
* Remove the host information from the ingress and apply it then you will check that the route was created by the service was not expose as expected.

**Comment by liggitt** [comment]
The discovery client (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/discovery/discovery_client.go) can be used to interrogate the apiserver for the API groups and versions it is serving. Along with that info, the apiserver can optionally return a set of server addresses. See the serverAddressByClientCIDRs field here:

https://github.com/kubernetes/kubernetes/blob/5f91b68d094785721ea68ce596f01cd2f3c917c9/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L899-L951

Note that this is what David was referring to in his previous comment:

> This has come up before and we attempted to solve it with discovery, but the results were not good. A few years out and I've never seen the information from the discovery doc used and I know some distributions always hardcode the value or leave it out.

Given there is already a way for apiservers to provide the info you are asking for, and many do not, I don't anticipate adding another API for this purpose.

**Comment by camilamacedo86** [comment]
HI @liggitt,

Thank you for share this over the discovery client. If you check [here](https://github.com/aerogear/mobile-security-service-operator/pull/54) my first solution was to add this value hardcode and my idea was to automate it by shell scripts which will be called before the CRs be applied in the cluster.

However, I really would like to get this info by the client API inside of the cluster instead of the shell scripts and/or the "hardcode" solution. Note that my motivation here is; if OCP is able to know the public hostname inside of the cluster since when the route is created it gets and uses this info to generate the host why Kube could not provide it? 

Anyway, really thank your support and info provided. 

Cheers.
