### ISSUE TITLE
When the number of jobs exceeds 500, cronjob cannot schedule, bug of pager.List

### ISSUE THREAD

**Issue by chengxiangwang** [kubernetes/kubernetes#77465]
**What happened**:
    When the number of jobs exceeds 500, cronjob cannot schedule, bug of pager.List 
**What you expected to happen**:
    When the number of jobs exceeds 500, cronjobs are scheduled normally
**How to reproduce it (as minimally and precisely as possible)**:
    Create at least 501 jobs and one cronjob to see if cronjobs can be scheduled
**Anything else we need to know?**:
    internalversion.List convert to batchv1.JobList error
    The following is the error log：  
  
```
May 05 17:28:16 qa-cpu003.aibee.cn kube-controller-manager[40548]: E0505 17:28:16.100551   40548 cronjob_controller.go:117] expected type *batchv1.JobList, got type *internalversion.List
```
**Environment**:
- Kubernetes version (use `kubectl version`):
    v1.14
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
  
```
Linux qa-cpu001.aibee.cn 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
  ansible and kube binary
- Network plugin and version (if this is a network-related bug):
  calico
- Others:

**Comment by liucimin** [comment]
Would do you like to show  us the full error?

**Comment by chengxiangwang** [comment]
@liucimin Thanks, the error message is as follows：
```
May 05 17:28:16 qa-cpu003.aibee.cn kube-controller-manager[40548]: E0505 17:28:16.100551   40548 cronjob_controller.go:117] expected type *batchv1.JobList, got type *internalversion.List
```

**Comment by liggitt** [comment]
cc @smarterclayton @jpbetz 

Related to paging?

**Comment by liucimin** [comment]
@chengxiangwang
Thx for your reply.
 @liggitt 
Yes it is a bug in the  syncAll function.
I will try to fix it.
https://github.com/kubernetes/kubernetes/pull/77475

**Comment by jpbetz** [comment]
cc @jingyih 

As it stands, this API is error prone, but I'm not certain how to fix it.

The to `*batchv1.JobList` is not safe here. But it's not obvious since it works up to the page limit.

`pager.List` returns a `runtime.Object` which can be either the type returned by the `ListPageFunc` provided to `pager.New` (in this case `*batchv1.JobList`) if the result fits in a single page or `metainternalversion.List` (see the [`pager.List` implementation](https://github.com/kubernetes/kubernetes/blob/df3e59fedc89da34ba9eb75e12d03a9bf4def2dd/staging/src/k8s.io/client-go/tools/pager/pager.go#L76)) if it exceeds a single page in size and must be accumulated.

`meta.ListAccessor` can be safely used to access the returned list type. As a starter, we should document that.

**Comment by liucimin** [comment]
@jpbetz 
I have the same analyze about this bug.
I push a pr to fix this.
Would do like to review it?

```	
	js := make([]batchv1.Job, 0)
	err = meta.EachListItem(jlTmp, func(object runtime.Object) error {
		jobTmp, ok := object.(*batchv1.Job)
		if !ok {
			return fmt.Errorf("Object must be a batchv1.Job.")
		}
		js = append(js, *jobTmp)
		return nil
	})

I try to use meta.EachListItem to change the list into []batchv1.Job

**Comment by chengxiangwang** [comment]
@liucimin Thanks, I think querying the cronjob list in the syncAll function after querying the batch job list requires a similar transformation.

**Comment by jpbetz** [comment]
Right, all usages of pager.List need to be reviewed/fixed.

**Comment by jpbetz** [comment]
pager.ForEachItem is simpler

**Comment by jingyih** [comment]
cc @caesarxuchao

**Comment by smarterclayton** [comment]
I have an outstanding item to replace all List style cast access with an interface method that all lists are required to implement.  That would remove the use of meta.ListAccessor and ForEachItem with equivalents on the object, and we would return the list interface from List methods (e.g. runtime.ObjectList).

We can't know whether the PageFn returns consistent objects - I would probably say we could alter List to always return metainternalversion.List but that is not necessarily a free operation.

**Comment by smarterclayton** [comment]
Why is the cron job controller still making live calls to the apiserver?

**Comment by smarterclayton** [comment]
Don't use a pager....

**Comment by jpbetz** [comment]
> I have an outstanding item to replace all List style cast access with an interface method that all lists are required to implement.

+1

> We can't know whether the PageFn returns consistent objects - I would probably say we could alter List to always return metainternalversion.List but that is not necessarily a free operation.

I'm in favor of this over what we have today. It prevents the type of accident that happened in this PR.

**Comment by soltysh** [comment]
> Why is the cron job controller still making live calls to the apiserver?

There's a plan (https://github.com/kubernetes/enhancements/pull/978) to move it to GA and rewrite the controller not to use live calls anymore but rely on shared informers.

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/77475

/close
