### ISSUE TITLE
Kube-controller-manager exception log problem when scale operation

### ISSUE THREAD

**Issue by xhlim** [kubernetes/kubernetes#77474]
![image](https://user-images.githubusercontent.com/9361471/57204376-09dcb380-6fea-11e9-926b-b8425fd9edfd.png)
![image](https://user-images.githubusercontent.com/9361471/57204378-13661b80-6fea-11e9-9d08-89b4b58ef267.png)
An exception log occurs irregularly when the above command is executed.

**Comment by xhlim** [comment]
![image](https://user-images.githubusercontent.com/9361471/57204417-4b6d5e80-6fea-11e9-98e1-2cddf9b191b2.png)

**Comment by yanghaichao12** [comment]
i’ve test many times， but cannot reproduce it. what's the version of your k8 and etcd? 
In general, this kind of error only occurs when concurrency，
Did you also do other operations on the object at the same time?

**Comment by xhlim** [comment]
kubernetes version ：1.10.12
etcdctl version: 3.2.7
I have this problem when I reduce the number of instances to 0 and then expand to 2. Repeat operation

**Comment by yanghaichao12** [comment]
yes, i've done the same thing but with different version.  Did you also do other operations on the object at the same time?or some job is still running?

**Comment by xhlim** [comment]
![image](https://user-images.githubusercontent.com/9361471/57211832-491ffa00-7014-11e9-93ea-5af66d7b278d.png)
![image](https://user-images.githubusercontent.com/9361471/57211854-60f77e00-7014-11e9-9d7f-4b47319eff1f.png)
journalctl -fu kube-controller-manager | grep nginx
I checked it through the "journalctl -fu kube-controller-manager | grep nginx" and it was not manipulated by any other object during my execution.

**Comment by yanghaichao12** [comment]
@xhlim #50102 have fixed it.
