### ISSUE TITLE
Unique Id for cluster

### ISSUE THREAD

**Issue by yoavAqua** [kubernetes/kubernetes#77487]
Is there a way to find unique id for kubernetes cluster?
We are working with several environments and we couldn't find something to uniquely identify a cluster environment.

Our current workaround is to save all the node's on the cluster and use the node's machine id field to determine on which cluster you are.

**Comment by lavalamp** [comment]
There is not, but you're not the only one wanting something like this. Current best practice is to use the kube-system UID.

**Comment by lavalamp** [comment]
I am pretty sure there was a long email discussion on this on the SIG Architecture mailing list.

**Comment by yoavAqua** [comment]
@lavalampThanks for the reply :)
I'm sorry but what exactly is the "kube-system UID"? 
Also, do you have any thoughts about our workaround? is the machine_id field unique for a single node on all the kubernetes environments (clusters)? couldn't get it from the documentation.

**Comment by dims** [comment]
@yoavAqua i think it's this thread https://groups.google.com/d/msg/kubernetes-sig-architecture/mVGobfD4TpY/nkdbkX1iBwAJ
