### ISSUE TITLE
rotate-server-certificates keep applying for certificates

### ISSUE THREAD

**Issue by gouki777** [kubernetes/kubernetes#77489]
hi  
I have a problem for certificate-rotation, 
my rotate-server-certificates have been repeating the application certificate,I don't know what went wrong.

when i restart kubelet serivce.
 my rotate-server-certificates have been repeating the application certificate

i look certificate-rotation  
[https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation)    
```      
k8s version:v1.12.5   
Linux k8snode7 4.19.1-1.el7.elrepo.x86_64 


kube-controller-manager.config add
- --feature-gates=RotateKubeletServerCertificate=true
- --experimental-cluster-signing-duration=8670h

node kubelet.config  add
--rotate-server-certificates --rotate-certificates 

```
my kubelet-client-current.pem rotate-certificates normal running 
but kubelet-server-current.pem rotate-server-certificates have problem.

rotate-server-certificates phenomenon.
i read documentation
<pre>
# kubectl get csr
NAME        AGE   REQUESTOR                            CONDITION
csr-4g998   15s   system:node:k8snode6            Pending
# kubectl certificate approve csr-4g998
certificatesigningrequest.certificates.k8s.io/csr-4g998 approved
# kubectl get csr
NAME        AGE   REQUESTOR                            CONDITION
csr-4g998   48s   system:node:k8snode6            Approved,Issued
# kubectl get csr
NAME        AGE     REQUESTOR                            CONDITION
csr-4g998   18m     system:node:k8snode6        Approved,Issued
csr-lbrqx      51s   system:node:k8snode6            Pending
csr-rqkxn   10m     system:node:k8snode6             Pending

[root@k8snode6]# ll -h
-rw------- 1 root root 1.3K May  6 15:36 kubelet-client-2019-05-06-15-36-42.pem
-rw-r--r-- 1 root root 1.1K May  6 15:39 kubelet-client.crt
lrwxrwxrwx 1 root root   59 May  6 15:36 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2019-05-06-15-36-42.pem
-rw------- 1 root root  227 May  6 15:39 kubelet-client.key
-rw-r--r-- 1 root root 2.2K May  6 15:39 kubelet.crt
-rw------- 1 root root 1.7K May  6 15:39 kubelet.key
-rw------- 1 root root 1.4K May  6 14:59 kubelet-server-2019-05-06-14-59-47.pem
-rw------- 1 root root 1.4K May  6 15:37 kubelet-server-2019-05-06-15-37-17.pem
lrwxrwxrwx 1 root root   59 May  6 15:37 kubelet-server-current.pem -> /var/lib/kubelet/pki/kubelet-server-2019-05-06-15-37-17.pem

# openssl x509 -text -in kubelet-server-current.pem
Certificate:
        Issuer: C=TW, ST=Taipei, L=Taipei, O=Kubernetes, OU=Kubernetes-manual, CN=kubernetes
        Validity
            Not Before: May  6 07:32:00 2019 GMT
            Not After : May  5 07:32:00 2020 GMT
</pre>

**Comment by gouki777** [comment]
and when i restart kubelet serivce.   
my rotate-server-certificates have been repeating the application certificate
<pre>
[root@k8snode6]# systemctl restart kubelet.service

[root@k8s-m1 ]# kubectl get csr
NAME        AGE   REQUESTOR                            CONDITION
csr-fmqlf   36m   system:node:k8snode6           Approved,Issued
csr-rc47l   6s    system:node:k8snode6               Pending
</pre>

**Comment by sambdavidson** [comment]
Hey gouiki777, I have been looking into this issue for a bit with a colleague and we were wondering if you could produce some kubelet logs from us from your cluster/node experiencing this issue.

The control loop responsible for rotating certs is [here](https://github.com/kubernetes/client-go/blob/7b18d6600f6b0022e31c46b46875beffd85cc71a/util/certificate/certificate_manager.go#L252). We suspect either the _manager_ object isn't updating it's _cert_ property correctly or something isn't working with the [templateChanged](https://github.com/kubernetes/client-go/blob/7b18d6600f6b0022e31c46b46875beffd85cc71a/util/certificate/certificate_manager.go#L263) channel. 

Thankfully there are a ton of logs that can clear this up in that code I linked. Can you ensure your kubelet is running at **verbosity level 2 or greater**, reproduce the issue, and supply your kubelet logs as it is creates a bunch of duplicate CSRs?

The logs I am primarily interested in are:

- ["Waiting %v for next certificate..."](https://github.com/kubernetes/client-go/blob/7b18d6600f6b0022e31c46b46875beffd85cc71a/util/certificate/certificate_manager.go#L255)
- ["Certificate template changed..."](https://github.com/kubernetes/client-go/blob/7b18d6600f6b0022e31c46b46875beffd85cc71a/util/certificate/certificate_manager.go#L268)
- ["Certificate expiration is %v..."](https://github.com/kubernetes/client-go/blob/7b18d6600f6b0022e31c46b46875beffd85cc71a/util/certificate/certificate_manager.go#L489)

Among others.

Thanks!

**Comment by gouki777** [comment]
hi~ sambdavidson  
my kubelet.config
<pre>
Environment="KUBELET_ARGS=--rotate-certificates --rotate-server-certificates --cert-dir=/var/lib/kubelet/pki --logtostderr=true --v=3" 
</pre>
my certificates file
<pre>
# ll -h
total 12K
-rw------- 1 root root 1.3K May  7 18:34 kubelet-client-2019-05-07-18-34-04.pem
lrwxrwxrwx 1 root root   59 May  7 18:34 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2019-05-07-18-34-04.pem
-rw------- 1 root root 1.4K May  5 16:49 kubelet-server-2019-05-05-16-49-10.pem
-rw------- 1 root root 1.4K May  7 18:35 kubelet-server-2019-05-07-18-35-24.pem
lrwxrwxrwx 1 root root   59 May  7 18:35 kubelet-server-current.pem -> /var/lib/kubelet/pki/kubelet-server-2019-05-07-18-35-24.pem
</pre>
start kubelet and look log
<pre>
-- Logs begin at Mon 2019-05-13 23:04:14 CST. --
May 29 14:05:43 k8s11 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 29 14:06:21 k8s11 systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 29 14:06:21 k8s11 kubelet[25170]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 29 14:06:21 k8s11 kubelet[25170]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 29 14:06:21 k8s11 kubelet[25170]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 29 14:06:21 k8s11 kubelet[25170]: Flag --rotate-server-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.754925   25170 flags.go:33] FLAG: --address="0.0.0.0"
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.755779   25170 flags.go:33] FLAG: --rotate-certificates="true"
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.755784   25170 flags.go:33] FLAG: --rotate-server-certificates="true"
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.760180   25170 mount_linux.go:180] Detected OS with systemd
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.760218   25170 server.go:408] Version: v1.12.5
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.760278   25170 feature_gate.go:206] feature gates: &{map[]}
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.760344   25170 feature_gate.go:206] feature gates: &{map[]}
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.760409   25170 plugins.go:99] No cloud provider specified.
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.760422   25170 server.go:524] No cloud provider specified: "" from the config file: ""
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.781421   25170 bootstrap.go:57] Kubeconfig /etc/kubernetes/kubelet.conf exists and is valid, skipping bootstrap
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.782085   25170 certificate_store.go:131] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.782894   25170 server.go:585] Starting client certificate rotation.
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.782905   25170 certificate_manager.go:234] Certificate rotation is enabled.
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.783390   25170 certificate_manager.go:442] Certificate expiration is 2029-03-27 22:29:00 +0000 UTC, rotation deadline is 2027-02-06 00:09:42.932490872 +0000 UTC
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.783429   25170 certificate_manager.go:240] Waiting 67434h3m21.14907159s for next certificate rotation
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.783490   25170 manager.go:155] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/system.slice/kubelet.service"
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.952083   25170 server.go:460] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s11", UID:"k8s11", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Starting' Starting kubelet.
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.952221   25170 certificate_manager.go:442] Certificate expiration is 2029-03-27 22:30:00 +0000 UTC, rotation deadline is 2027-12-03 05:26:06.113787568 +0000 UTC
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.952239   25170 certificate_manager.go:240] Waiting 74639h19m44.161551335s for next certificate rotation
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.952274   25170 volume_manager.go:246] The desired_state_of_world populator starts
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.952279   25170 volume_manager.go:248] Starting Kubelet Volume Manager
May 29 14:06:21 k8s11 kubelet[25170]: I0529 14:06:21.955598   25170 desired_state_of_world_populator.go:130] Desired state populator starts to run
</pre>
kubelet run same time   have been repeating the application certificate ( 10 Minutes) and log...
<pre>
May 29 14:18:54 k8s11 kubelet[25170]: I0529 14:18:54.194795   25170 eviction_manager.go:317] eviction manager: no resources are starved
May 29 14:18:56 k8s11 kubelet[25170]: E0529 14:18:56.794752   25170 certificate_manager.go:378] Certificate request was not signed: timed out waiting for the condition
May 29 14:18:58 k8s11 kubelet[25170]: I0529 14:18:58.836331   25170 certificate_manager.go:336] Rotating certificates
May 29 14:19:00 k8s11 kubelet[25170]: I0529 14:19:00.872754   25170 server.go:799] GET /metrics: (18.888122ms) 200 [Prometheus/2.9.2 10.249.239.70:38386]
May 29 14:19:01 k8s11 kubelet[25170]: I0529 14:19:01.950895   25170 kubelet_pods.go:1327] Generating 
</pre>

**Comment by sambdavidson** [comment]
Great these logs are helpful! Sorry for the late reply. 

So a few observations that might mean we need to dig up additional logs. 

It is a little confusing because it appears that you already have a valid certificate(s) that won't rotate for `67434h3m21.14907159s` and `74639h19m44.161551335s`. There are no additional logs about a rotation attempt within that pasted section of logs.

The error you pasted in the second section which occurs ~12 minutes later:
```
May 29 14:18:56 k8s11 kubelet[25170]: E0529 14:18:56.794752   25170 certificate_manager.go:378] Certificate request was not signed: timed out waiting for the condition
```
Is printed [here](https://github.com/kubernetes/client-go/blob/e65ca70987a6941be583f205696e0b1b7da82002/util/certificate/certificate_manager.go#L414) and should occur after a _"Rotating certificates"_ logged [here](https://github.com/kubernetes/client-go/blob/e65ca70987a6941be583f205696e0b1b7da82002/util/certificate/certificate_manager.go#L381).  I am interested in when exactly that certificate rotation attempt began and if it lines up with the initialization logs above from around `14:06:21.783390`, 12 minutes earlier.

However, the error itself _"Certificate request was not signed: timed out waiting for the condition"_ might just mean something is wrong with whatever certificate signing automation you have in place. Take a look at the [Kubernetes docs on approving CSRs](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#approving-certificate-signing-requests). Perhaps you just have to manually approve the CSRs if no automation is in place (as I don't know your K8s infrastructure).

**Comment by alexeldeib** [comment]
@sambdavidson I am seeing something similar but kind of opposite. I think my issue may be more config/docs related, so I'll take it elsewhere if it proves to be unrelated. 

My kubelet is configured with `tlsCertFile` and `tlsKeyFile`. When I boot up the server, it creates CSRs and when I look in /var/lib/kubelet/pki I see one new Serving certificate and two new Client certificates. 

However, Kubelet doesn't start using the new certificates because it has a valid `tlsCertFile/tlsKeyFile` for Serving. If I remove those two pieces from my Kubelet config, all is well. 

Based on [this code](https://github.com/kubernetes/client-go/blob/177766529176f38606818ef97494cbc7e9445483/util/certificate/certificate_store.go#L57-L69) I assumed the new cert should be picked up pretty quickly. Is it not rotating in this case because the [valid cert doesn't expire for a while](https://github.com/kubernetes/client-go/blob/177766529176f38606818ef97494cbc7e9445483/util/certificate/certificate_manager.go#L238) still?

**Comment by mikedanese** [comment]
Multiple CSRs created in early kubelet boot is expected under some conditions. https://github.com/kubernetes/kubernetes/pull/77936

@alexeldeib sounds like a separate issue.

**Comment by gouki777** [comment]
I up kubenetes version 1.13.5+
my rotate-server-certificates have not repeating the application certificate.
The 1.13 version does not have this problem.
thanks.
