### ISSUE TITLE
"kubectl get nodes" taking too much time to return result

### ISSUE THREAD

**Issue by GarbageYard** [kubernetes/kubernetes#77494]
**What happened**: Executed command ```kubectl get nodes``` but it took more than a minute to return result

**What you expected to happen**: I expected to see the output almost instantly

**How to reproduce it (as minimally and precisely as possible)**: Install Kubernetes on CentOS VM with details as mentioned in Environment section below

**Anything else we need to know?**:
**Logs**
1) ```kubectl get nodes```
```
NAME           STATUS   ROLES                      AGE     VERSION
10.150.16.54   Ready    controlplane,etcd,worker   2d21h   v1.13.5
10.150.16.55   Ready    controlplane,etcd,worker   2d21h   v1.13.5
10.150.16.56   Ready    controlplane,etcd,worker   2d21h   v1.13.5
```

2. ```kubectl get pod -o wide -v=10```
Kindly refer attachment: [get_pod.log](https://github.com/kubernetes/kubernetes/files/3147129/get_pod.log)

**Environment**:
- Kubernetes version (use `kubectl version`): ```kubectl version```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: 3 VMs for Kubernetes node + 1 VM for running ```kubectl``` and RKE (Rancher Kubernetes Engine). All four machines have CentOS installed with the same version details as mentioned below.

- OS (e.g: `cat /etc/os-release`): ```cat /etc/*release```

```
CentOS Linux release 7.6.1810 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core)

```
- Kernel (e.g. `uname -a`): `Linux mybox 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools: ```docker version```

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
- Network plugin and version (if this is a network-related bug):
- Others: Similar delay is noticed when i run ```kubectl get service``` command

```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   109d

```

Any help will really be appreciated.

/sig cli

**Comment by tedyu** [comment]
Server is 1.13
Do you observe similar slowness if server runs 1.14 ?

Thanks

**Comment by GarbageYard** [comment]
I have installed it using Rancher Kubernetes Engine [Release v0.1.18](https://github.com/rancher/rke/releases/tag/v0.1.18). Post that, all others are release candidates. I can give it a try but is v1.13 having such issues?

**Comment by zq-david-wang** [comment]
> 'dial tcp 10.43.185.20:443: i/o timeout'

My guess is that your metrics server does not work well  and you need to check whether your metrics server is up.  It should be in kube-system namespace

**Comment by GarbageYard** [comment]
@zq-david-wang : Seems that must have been the issue. When i checked the container log for metric server, i found the following:

`[x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-requestheader-ca"), x509: certificate signed by unknown authority]`

I cleaned up the nodes and then tried setting up the cluster again. Now i am getting the following error:

```
# ./rke up --config ./rancher-cluster.yml
INFO[0305] [controlplane] Successfully started [kube-apiserver] container on host [10.150.16.55]
INFO[0305] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.150.16.55]
INFO[0305] [controlplane] Successfully started [kube-apiserver] container on host [10.150.16.56]
INFO[0305] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.150.16.56]
INFO[0305] [controlplane] Successfully started [kube-apiserver] container on host [10.150.16.54]
INFO[0305] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.150.16.54]

FATA[0514] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.150.16.55]: Get https://localhost:6443/healthz: EOF, log: I0507 07:05:51.188445       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.
```

If i check the port 6443 on 10.150.16.55, i see it's listening.

```
# netstat -ntpl | grep 6443
tcp6       0      0 :::6443                 :::*                    LISTEN      10311/kube-apiserve
```

I also noticed that `kube-apiserver` container is restarting continuously.

**Comment by GarbageYard** [comment]
I performed the [following steps](https://github.com/rancher/rancher/issues/20027#issuecomment-490014906) and after this, i noticed that `kubectl` command is running without any lag.
