### ISSUE TITLE
fluentd-gcp memory consumption has increased

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#77492]
It's causing flakiness of the pull-kubernetes-e2e-gce-100-performance, see https://github.com/kubernetes/kubernetes/issues/73884#issuecomment-489542295

It's also visible in the [perf-dash graph](http://perf-dash.k8s.io/#/?jobname=gce-100Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=fluentd-gcp%2Ffluentd-gcp&Resource=memory)  
![mKMPjAcrwZk](https://user-images.githubusercontent.com/2604887/57214946-cd11bc00-6feb-11e9-8c26-0b241b67354c.png)

We'll increase the memory constraint in https://github.com/kubernetes/perf-tests/pull/524 in order to deflake the presubmits, but we should figure out what caused the increase in the memory usage.

**Comment by mm4tt** [comment]
We can rule out fluentd-gcp upgrade, the version that we use (v.3.2.0) hasn't changed since 1.13

**Comment by mm4tt** [comment]
/assign @x13n 

@x13n, could you take a look and help us debug?

**Comment by x13n** [comment]
Since the version didn't change, my guess is that some component(s) started generating more logs. Did CPU usage increase as well?

**Comment by mm4tt** [comment]
I believe it slightly increased, but it's not as visible as the memory increase, see http://perf-dash.k8s.io/#/?jobname=gce-100Nodes&metriccategoryname=E2E&metricname=DensityResources&PodName=fluentd-gcp%2Ffluentd-gcp&Resource=CPU

**Comment by x13n** [comment]
Interesting. Can we rule out backend latency increase somehow? If the mean latency increased, the buffers utilization would follow. Unfortunately, fluentd doesn't expose request latency metrics today, only success/failures: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb

/cc @qingling128 @bmoyles0117

**Comment by tedyu** [comment]
Is it possible to perform some sort of bisecting to narrow the scope of search ?

Thanks

**Comment by qingling128** [comment]
Not sure if it's related, but we observed some memory consumption difference between k8s versions < 1.10 and versions >=1.10: https://github.com/fluent/fluentd/issues/2236#issue-391291898. Originally we thought it's triggered by log rotation change in k8s. But it's only a hypothesis that has not been proved.

**Comment by mm4tt** [comment]
Bisection would be possible, but may be hard due to high variance of the memory consumption (see the first graph). Also we don't really have manpower to do it, we're currently facing few other regressions that have priority over this one. 

Any other ideas how to debug this? Is fluentd-gcp exposing any prometheus metrics that might be useful to debug this? Can we compare some fluentd-gcp logs from a good run and bad run to see if there is anything that stands out?

**Comment by x13n** [comment]
I'm not sure eyeballing fluentd logs would expose memory problems.

fluentd_status_buffer_queue_length/fluentd_status_buffer_total_bytes metrics might be worth looking at, to confirm that the memory increase is indeed coming from the buffers.

**Comment by mm4tt** [comment]
I was wrong saying that the version of fluentd-gcp hasn't changed. 
It was bumped up from 1.6.0 to 1.6.8 in https://github.com/kubernetes/kubernetes/pull/77224. 
The timing correlates with the increase we see in the perf-dash, so it's the culprit most likely.

**Comment by mm4tt** [comment]
Sorry, this got deprioritized. The tests still flakes due to that, I think at this point the only reasonable action is to assume that the increase was caused by fluentd version upgrade and increase the constraints to add some headroom and deflake the test.

Will send a PR shortly.

**Comment by mm4tt** [comment]
Ref. https://github.com/kubernetes/kubernetes/issues/80212
