### ISSUE TITLE
support label selector in resource quota scopeSelector

### ISSUE THREAD

**Issue by qiwqwq** [kubernetes/kubernetes#77508]
**What would you like to be added**:
“A quota is matched and consumed only if scopeSelector in the quota spec selects the pod”
ScopeSelector it only support priorityClass, Is it possible to support label selector?
**Why is this needed**:
Different teams can be different namespace, but one team may be have many applications , quota management between different applications is troublesome。If scopeSelector support label selector, it will very useful.

**Comment by liggitt** [comment]
the scopes added so far have covered attributes of objects that incur different types of resource consumption (terminating pods, types of services, priority class levels, etc)

pod labels are fully under the control of the actor creating the pods, and can be freely changed without affecting the resources actually consumed by the pod, so they don't seem like a great control for quota to enforce on

**Comment by ScorpioCPH** [comment]
@liggitt Thanks for your explanation, but types of resource is not enough in some scenarios:
- We have one namespace for one user (tenant);
- They deploy some pods with different env labels, such as `app-env=staging` and `app-env=production`;
- They want to config different quota for the different env, as `quota-staging.hard=100 cores`, `quota-production=500 cores`;

So extend the scope selector to support label selector will be great.
And more, we have implement this in our internal branch, will be happy to contribute this code into upstream :)

/cc @resouer

**Comment by liggitt** [comment]
thanks for the feedback. I still don't think label selectors make sense as a quota scope, but am willing to hear thoughts from other quota maintainers

/sig api-machinery

**Comment by josephlewis42** [comment]
We have a similar use-case: we're using namespaces in K8s for tenant isolation. Each namespace can build containers from source and serve them (via Knative). 

We'd like to allow setting quotas over the whole namespace for cluster stability, but also on the containers running servers so they can't auto-scale up and prevent new build containers from being scheduled.

**Comment by josephlewis42** [comment]
@qiwqwq do you mind re-opening this issue unless it's resolved? That way we can keep the conversation going here and don't have to open a new one.

Thanks!

**Comment by tysonnorris** [comment]
We have similar need for this feature.

**Comment by imalandu** [comment]
@qiwqwq plz re-opening this issue~

**Comment by fabifrank** [comment]
Is there something meanwhile? We running into a similiar issue: We have different Namespaces and want to set resource quotas per namespace, thus priorityclasses dont make sense.

**Comment by zebambam** [comment]
I would also like to just add a label to a pod and have that count against that label's quote across all namespaces. This is because we're creating workers at the request of another application, and the labels are stamped by that application. Don't want to allow any single user to over-use our compute resources.

**Comment by stpabhi** [comment]
I would like to share my thoughts on this. we should be able to create multiple priorityclasses (per app/team/env) and use them in resourcequota scope selector for all the required namespaces. By using a mutating webhook set the appropriate priorityClassName based on pod labels, annotations, or even username/groups from AdmissionRequest.UserInfo. Once a pod is admitted pod labels could still be changed and quota controller doesn't have to worry about it. I haven't tried it and i think it's possible based on my understanding from documentation.

**Comment by Jamstah** [comment]
We have a situation where some of our pods require software licenses. We would like to label them and use a resourcequota to ensure we stay within our purchased limits.

So, +1 trip this being reopened!

**Comment by BaskiGIT** [comment]
Hi our use case is that in a single namespace there are some services with minimal requests/limits and some other databases with far higher requests/limits

While we can achieve this with restricting ResourceQuota with priorityClass it would be more convenient to do based on labels without having to introduce priorityClass

**Comment by tamirshkolnik** [comment]
We have similar need for this feature.

**Comment by sorushsaghari** [comment]
I need this too. i want to run spark on jupyter for data scientist. so they can change the resources needed for a job

**Comment by CHoldinghausen** [comment]
we need this as well - please reopen

**Comment by lmktfy** [comment]
One use case I had in mind was around limits on ephemeral storage. I wanted a way to express a policy similar to "you can have up to three Pods that request more than 10GiB each of `emptyDir` storage, or you can have up to 250 of them with up to 1.2TiB total, provided that they repel each other as a required scheduling constraint, and that none requests more than 8GiB individually".

Now that is a very specific ask! I don't think it's fair to put that kind of rule in core K8s.

Quota scoped by label could be a building block to achieve that. It would need to be carefully implemented so that changing the label fails if a scoped quota would be violated.

Not a small piece of work, and not especially important to me. But it is a real use case from a real enterprise.
