### ISSUE TITLE
tokencleaner not removing expired bootstrap tokens

### ISSUE THREAD

**Issue by jakubek** [kubernetes/kubernetes#77505]
**What happened**:
kube-controller-manager with enabled option --controllers=*,tokencleaner is not removing newly created tokens. It works only after kube-controller-manager restart or after editing secret with token.

**What you expected to happen**:
It should remove all expired tokens from kube-system namespace, without restarting or touching secrets.

**How to reproduce it (as minimally and precisely as possible)**:
* enable tokencleaner in kube-controller-manager
* start controller manager
* create bootstrap token, you can use script https://gist.github.com/jakubek/e510cb5a894c66b9df59098b28c75c74
* wait 5 minutes
* token is still there
* restart kube-controller-manager OR edit newly created token
* token should be gone after a while

**Anything else we need to know?**:
It could be related with #https://github.com/gardener/gardener/issues/264

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tedyu** [comment]
Do you see the following log ?
```
		if err != nil && !apierrors.IsConflict(err) && !apierrors.IsNotFound(err) {
			klog.V(3).Infof("Error deleting Secret: %v", err)
```
thanks

**Comment by jakubek** [comment]
@tedyu no errors at all
