### ISSUE TITLE
build failure: cli-runtime kustomize pkg wants to import deleted factory code

### ISSUE THREAD

**Issue by pothos** [kubernetes/kubernetes#77502]
This line https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/factory.go#L24 references deleted code.
See https://github.com/kubernetes/cli-runtime/issues/2

**Comment by pothos** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
make sure you are using a level of sigs.k8s.io/kustomize that matches the level of k8s.io/cli-runtime you are using 

you can find the referenced level in Godeps/Godeps.json (if using <= 1.14.x) or go.mod (on master if using > 1.14.x)

/close
