### ISSUE TITLE
Deprecate the `--enable-logs-handler` option for the apiserver

### ISSUE THREAD

**Issue by rohitsardesai83** [kubernetes/kubernetes#77515]
**What would you like to be added**:
Deprecate the flag which enables exposing logs of apiserver.

**Why is this needed**:
As per https://github.com/kubernetes/kubernetes/issues/77182#issuecomment-487439173, in order to disable accessing apiserver logs in the future, we need to deprecate the current default and wait for the requisite time period.

**Comment by lavalamp** [comment]
I'm in favor of deprecating this. It's potentially disruptive, I think an email blast to kubernetes-dev would be a good idea.

**Comment by rohitsardesai83** [comment]
> I'm in favor of deprecating this. It's potentially disruptive, I think an email blast to kubernetes-dev would be a good idea.

Thanks @lavalamp , I have  posted in kubernetes-dev mailing list.

**Comment by liggitt** [comment]
> As per [#77182 (comment)](https://github.com/kubernetes/kubernetes/issues/77182#issuecomment-487439173), in order to disable accessing apiserver logs in the future, we need to deprecate the current default and wait for the requisite time period.

I'm also in favor of removing this functionality from the apiserver. Since this is GA behavior, the deprecation period would be 12 months.

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle
