### ISSUE TITLE
Azure Public IPs not 

### ISSUE THREAD

**Issue by stoader** [kubernetes/kubernetes#77511]
**What happened**:
We deployed two Kubernetes clusters to the same Azure Resource Group. Created services of load balancer type on both clusters. One of the services never received a public IP. Upon investigation, we noticed that the first Kubernetes cluster deleted the Azure Public IP that was created for the service by the other cluster.

Apparently, all public IPs in the resource group are retrieved: https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L1350  then public IPs which don't match this criteria: https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L1357 are deleted.

This logic besides the name of the kubernetes service should also consider the K8s cluster where the public IP originated from to avoid stepping on each other's toes when multiple clusters share the same resource group.

**What you expected to happen**:
In case multiple clusters run in the same resource group a cluster should delete only resources created by itself.

**How to reproduce it (as minimally and precisely as possible)**:
Create two Kubernetes clusters (1.14) with different cluster names to the same resource group than create kubernetes services of load balancer type in each cluster. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.4
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by stoader** [comment]
@kubernetes/sig-azure-bugs

**Comment by feiskyer** [comment]
@stoader thanks for reporting the issue, this is the bug we should fix for sharing resource group.

/sig azure
/kind bug
/assign
