### ISSUE TITLE
No debug info when building Kubernetes source code with `make all GOGCFLAGS="-N -l"`

### ISSUE THREAD

**Issue by qianzhangxa** [kubernetes/kubernetes#77527]
**What happened**:
I ran `make all GOGCFLAGS="-N -l"` to build latest Kubernetes source code, and then I see the binaries are still stripped:
```
$ file _output/bin/kubelet 
_output/bin/kubelet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=715f57807e652488c5e086b82f5daf4063a74b04, stripped
```

And I can not use dlv to debug the binary:
```
$ dlv exec _output/bin/kubelet                          
could not launch process: could not open debug info
```

In Makefile, I see the following comments:
```
#   make all GOGCFLAGS="-N -l"
#     Note: Use the -N -l options to disable compiler optimizations an inlining.
#           Using these build options allows you to subsequently use source
#           debugging tools like delve.
```
But that seems not correct in my build.

**What you expected to happen**:
I expected Kubernetes binaries with debug info.

**How to reproduce it (as minimally and precisely as possible)**:
`make all GOGCFLAGS="-N -l"`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Latest Kubernetes source code.
- Cloud provider or hardware configuration: A virtual machine with 2 cores and 8GB RAM.
- OS (e.g: `cat /etc/os-release`): 18.04 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux workstation 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by YoubingLi** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh

kube::golang::build_binaries() {
  # Create a sub-shell so that we don't pollute the outer environment
  (
    # Check for `go` binary and set ${GOPATH}.
    kube::golang::setup_env
    V=2 kube::log::info "Go version: $(go version)"

    local host_platform
    host_platform=$(kube::golang::host_platform)

    local goflags goldflags goasmflags **gogcflags**
    # If GOLDFLAGS is unset, then set it to the a default of "-s -w".
    # Disable SC2153 for this, as it will throw a warning that the local
    # variable goldflags will exist, and it suggest changing it to this.
    # shellcheck disable=SC2153
    goldflags="${GOLDFLAGS=-s -w} $(kube::version::ldflags)"
    goasmflags="-trimpath=${KUBE_ROOT}"
    gogcflags="${GOGCFLAGS:-} -trimpath=${KUBE_ROOT}"    
           ~~~~~ It is a local variable 
           ~~~~~ It turns out the value is empty in kube::golang::build_binaries_for_platform


I will take this one and provide a PR.

/cc @YoubingLi

**Comment by YoubingLi** [comment]
It is the problem of "-ldflags -s -w" and I will provide a PR ASAP.


/cc @YoubingLi

**Comment by dims** [comment]
@YoubingLi @qianzhangxa please set `GOLDFLAGS` to an empty string and see if that helps

https://github.com/kubernetes/kubernetes/commit/7e01702a8827529b48f131ca287cf498391ff88b

**Comment by YoubingLi** [comment]
@dims
    Yes, this is my fix solution (Remove '-s -w' from goldflags).
    Meanwhile, I had verified that it works.

**Comment by qianzhangxa** [comment]
@dims Did you mean `make all GOGCFLAGS=""`? I tried it just now, but the result is same, the binaries are still stripped:
```
file _output/bin/kubelet  
_output/bin/kubelet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=cd40ab7314461bff741a76a44a51f12ba00d6e13, stripped
```

**Comment by Davidrjx** [comment]
in my case for kubernetes1.13.5, removing  '-s -w' from goldflags is enough.
