### ISSUE TITLE
Adding support for windows storage metric

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#77520]
**What would you like to be added**:
Adding support for measuring volume usage metrics in windows

**Why is this needed**:
Currently, for monitoring storage metric, we have two ways.
1. For local ephemeral storage (emptyDir, secret etc): it uses [metricsDu](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/metrics_du.go) which use "du" command to get the disk usage for the specified path.

2. For persistent disk: it uses [metricsStatFS](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/metrics_statfs.go) which uses "df" command to get the disk usage for each mount point.

We to need find the equivalent command/utility for windows to collect the usage metrics for different types of storage. In windows, 
1. du: we could download and install du utility https://docs.microsoft.com/en-us/sysinternals/downloads/du
2. df:  fsutil volume diskfree command can check disk usage of a disk

**Comment by jingxu97** [comment]
cc @yujuhong

**Comment by andyzhangx** [comment]
cc @VybavaRamadoss
