### ISSUE TITLE
build/release.sh (hack/lib/golang.sh) requires minimum bash v4.4

### ISSUE THREAD

**Issue by cjschaef** [kubernetes/kubernetes#77521]
**What happened**:  building Kubernetes release and it failed due to a variable not being set ([with `set -u` enabled](https://github.com/kubernetes/kubernetes/blob/caf9d94d697ce327e0c1c3dee71a1f06a6fc918e/build/release.sh#L25)). It appears a [recent commit](https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b) does not function as expected on `bash v4.3` (used Ubuntu 16). Additional details will be provided in comment below
```
kubernetes/hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variable
```

**What you expected to happen**: successful build of Kuberentes release or documented minimum supported OS releases (i.e., bash versions)

**How to reproduce it (as minimally and precisely as possible)**: using Ubuntu 16 (`bash v4.3`), run [build/release.sh] using `release-1.14`, `v1.15.0-alpha.2` or `master` (containing https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b or subsequent cherry pick)

**Anything else we need to know?**:  It appears the issue is with how `bash v4.3` and `bash v4.4` create `readonly` variables, where I believe `v4.3` does not create the variables with the expected scope (created using `local` scope versus `global` scope). This creates a minimum supported OS version when running `build/release.sh` from the best I can tell.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.15.0-alpha.2` [`release-1.14`](https://github.com/kubernetes/kubernetes/commit/ffa6160e087d699282daca15085f9cb968240b80)
- Cloud provider or hardware configuration:  N/A
- OS (e.g: `cat /etc/os-release`):
```
release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):  `Linux armada-lb-build 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:  `build/release.sh`
- Network plugin and version (if this is a network-related bug):  N/A
- Others:

/sig release

**Comment by cjschaef** [comment]
Some of the details I mentioned above, modified the `hack/lib/golang.sh` file to output some helpful information
- the diff of changes I made
https://pastebin.com/zrU28PRQ
- the results when running on Ubuntu 16 (bash 4.3)
https://pastebin.com/ph1648Ui
- the results when running on Ubuntu 16 (bash 4.3) without the `readonly` variable attribute (you can now see the variable is a `global` variable, not locally scoped to the function `kube::golang::setup_platforms`)
https://pastebin.com/yfhXmANC

And on Ubuntu 18 (bash 4.4) the variable is scoped `globally` with the `readonly` attribute as you would expect and `build/release.sh` runs as expected.

**Comment by nikhita** [comment]
I guess https://github.com/kubernetes/kubernetes/pull/77362 fixes this problem.

cc @cblecker

**Comment by cjschaef** [comment]
I don't think the `mapfile` is/was the only issue here. It was obviously `readonly` as I was testing with `KUBE_FASTBUILD=true`, so only `readonly` variables were being used and not scoped outside the function (in bash 4.3).
https://github.com/kubernetes/kubernetes/blob/eaafa5952f8073f51b13dbeafe406019995c8c0b/hack/lib/golang.sh#L204-L220

**Comment by adisky** [comment]
@cjschaef  we are also getting the same error on bash version 4.3
cc @h00130372 @mrhillsman

**Comment by adisky** [comment]
@cjschaef any update on this, are you fixing it??

**Comment by kiwik** [comment]
Same question with @adisky , this issue impact OpenLab cloud-provider-openstack E2E testing job.

**Comment by dims** [comment]
@kiwik @adisky can you please try this? https://github.com/kubernetes/kubernetes/pull/77867

**Comment by aojea** [comment]
@dims it works with your fix https://circleci.com/gh/aojea/kubernetes/53 ,

**Comment by cjschaef** [comment]
Sorry I missed this yesterday. I will try #77867 as well. Otherwise, my assumption was to revert the use of a function, as that creates the scoping problem we've been seeing with `readonly` variables in `bash 4.3`.

**Comment by dims** [comment]
@aojea i think that would be `make quick-release` not `make quick-release-images`

**Comment by dims** [comment]
Also both `make quick-release` not `make quick-release-images` should work now.

**Comment by cjschaef** [comment]
Looks like #77867 worked for me. Was able to run a `KUBE_FASTBUILD` using `bash 4.3` successfully.
```
GOPATH=/home/vagrant/go KUBE_GIT_VERSION=v1.15.0-alpha.3 KUBE_DOCKER_IMAGE_TAG=v1.15.0-alpha.3 KUBE_RELEASE_RUN_TESTS=n KUBE_FASTBUILD=true KUBE_VERBOSE=0 ./build/run.sh make hyperkube
...
Successfully built 09f441c067bb
Successfully tagged hyperkube-amd64:v1.15.0-alpha.3
```

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/76974
