### ISSUE TITLE
Unclear status of dynamic topology-aware volume provisioning with vSphere Cloud Provider

### ISSUE THREAD

**Issue by embano1** [kubernetes/kubernetes#77535]
**What happened**:

On several channels in SIG VMware (Slack, email) users were asking about the status of whether topology-aware volume scheduling (`volumeBindingMode: WaitForFirstConsumer`) with dynamic provisioning is supported with the in-tree vSphere Cloud Provider (VCP). However, according to the [official K8s docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode), this is not the case, leaving our users and vSphere community in an unclear state.

**What you expected to happen**:
Recently there were several fixes to the VCP and storage handling in different vSphere storage deployment topologies (see [this issue](https://github.com/kubernetes/kubernetes/issues/67703)), incl. volume creation method signatures to include the optional (and related) field `allowedTopologies` to satisfy the corresponding volume provisioning interface.

Since VCP [added](https://github.com/kubernetes/kubernetes/issues/64021) zones interface support in v1.12 and based on that additional fixes for dynamic volume provisioning across zones/topologies, our users and vSphere community expect topology-aware volume scheduling to work. 

We should document the expected behavior and support statement whether and under which circumstances (versions, in-tree/out-of-tree cloud provider, etc.) topology-aware volume scheduling is supported for vSphere.

/sig vmware

**Comment by subramanian-neelakantan** [comment]
VCP has zones support. A volume is always provisioned on a shared datastore in vSphere. Without zones, the Volume is placed on a globally shared datastore across all the k8s nodes (VMs). With the use of zones, the datastore needs to be a shared only among the k8s nodes (VMs) in that zone. A Volume is placed on a particular zone by using `allowedTopologies`.

`WaitForFirstConsumer` volume binding mode works as expected, in that the Volume is not created until a Pod that uses this PVC is created. At such time, the Volume is placed either on a globally shared datastore (when Zones is not used) or on datastore that is visible within the nodes of that Zone. Note that node local datastores are *not* used for placement of Volumes in vSphere using VCP. Still when using `WaitForFirstConsumer` the Volume placement is delayed so that the pod's Zone requirement can be met by the Volume. In other words, `WaitForFirstConsumer` when used along with `allowedTopologies` to specify the Zone allows you to delay and place the Volume in a shared datastore of that Zone.

**Comment by embano1** [comment]
Thank you @subramanian-neelakantan for your quick and detailed response! Before I close this issue, let me clarify my understanding two parts in your response:

> With the use of zones, the datastore needs to be a shared only among the k8s nodes (VMs) in that zone. A Volume is placed on a particular zone by using `allowedTopologies`

When you refer to zones, assuming you mean the `[labels]` section in vcp.conf to reflect the tags for zones/region? As per the volume creation (datastore selection) logic described by you, I wonder: is it really needed to specify `allowedTopologies` in the StorageClass then? Because the scheduler gets back with a Kubernetes node (VM) recommendation to the persistent volume controller, this would not be needed since we check the corresponding vSphere host for that VM and its associated datastores, right? Also, my understand is that `allowedTopologies` is only used with `WaitForFirstConsumer`. If a customer has not enabled this binding mode in a StorageClass, are we still evaluating `allowedTopologies` in our volume creation logic?

> At such time, the Volume is placed either on a globally shared datastore (when Zones is not used) or on datastore that is visible within the nodes of that Zone

As per my comment above, does this require `allowedTopologies` in the StorageClass? IIRC, the logic we have is `pod -> kubernetes node -> VM -> host -> tags -> find all hosts in that zone -> find all shared datastores`. So we would actually not be dependent on the `allowedTopologies` field in StorageClass.

> Note that node local datastores are not used for placement of Volumes in vSphere using VCP.

I am not understanding this sentence. What is a "node local datastore"? Or are you saying that only shared datastores are evaluated (i.e. intersect function for that particular zone tag), which totally makes sense.

> In other words, WaitForFirstConsumer when used along with allowedTopologies to specify the Zone allows you to delay and place the Volume in a shared datastore of that Zone.

Going back to my earlier comment. Are you saying that we must pass `allowedTopologies` in the StorageClass to make placement work as expected? This could lead to undesired effects for users if these things get out of sync or, even worse, an admin forgets to specify that in the StorageClass for a vSphere volume.

**Comment by frodenas** [comment]
@subramanian-neelakantan, besides @embano1 questions, which k8s version supports `WaitForFirstConsumer` volume binding mode? I've been testing it on a v1.13.5 cluster and even when the scheduler is adding the `volume.kubernetes.io/selected-node` label to the pvc, the VCP (with zones) is creating the pv on a datastore not accessible for that particular node.

**Comment by subramanian-neelakantan** [comment]
> When you refer to zones, assuming you mean the `[labels]` section in vcp.conf to reflect the tags for zones/region?

That's correct. The `[labels]` section in `vsphere.conf` file enables the Zones feature of VCP. Once the feature is enabled, specifying zone tags in `allowedTopologies` places the Volume in a datastore that is shared  among nodes (VMs) in that zone. Without `allowedTopologies` in the StorageClass, the Volume always ends up in a globally shared datastore among all nodes (VMs) in the k8s cluster.

> As per the volume creation (datastore selection) logic described by you, I wonder: is it really needed to specify `allowedTopologies` in the StorageClass then? Because the scheduler gets back with a Kubernetes node (VM) recommendation to the persistent volume controller, this would not be needed since we check the corresponding vSphere host for that VM and its associated datastores, right?

As of now when placing a Volume, VCP does not use the pod scheduler's `selectedNode`.  It only uses the zone information specified in `allowedTopologies` of the StorageClass if available. The reason I think ignoring the `selectedNode` is alright is that VCP always selects only a shared datastore to place the Volume and so is guaranteed visibility to the pod.

> Also, my understand is that `allowedTopologies` is only used with `WaitForFirstConsumer`. If a customer has not enabled this binding mode in a StorageClass, are we still evaluating `allowedTopologies` in our volume creation logic?

VCP evaluates and honours the `allowedTopologies` if specified in the StorageClass. This can be used with or without `WaitForFirstConsumer` as it is implemented today.

> As per my comment above, does this require `allowedTopologies` in the StorageClass? IIRC, the logic we have is `pod -> kubernetes node -> VM -> host -> tags -> find all hosts in that zone -> find all shared datastores`. So we would actually not be dependent on the `allowedTopologies` field in StorageClass.

`allowedTopologies` is always required when we want to restrict the Volume's visibility to only within a Zone. VCP does not infer the zone from the `selectedNode`.

> I am not understanding this sentence. What is a "node local datastore"? Or are you saying that only shared datastores are evaluated (i.e. intersect function for that particular zone tag), which totally makes sense.

That's correct. Only datastores that are shared among all k8s nodes of a zone are considered when trying to place a Volume in that zone. I realize my original statement can cause confusion and should be replaced with this statement instead.

> Going back to my earlier comment. Are you saying that we must pass `allowedTopologies` in the StorageClass to make placement work as expected? This could lead to undesired effects for users if these things get out of sync or, even worse, an admin forgets to specify that in the StorageClass for a vSphere volume.

The way VCP works today, `allowedTopologies` must be specified in StorageClass to place a Volume in a specific zone. This could be changed/improved if we find a need. Proposed behaviour could be - In the absence of `allowedTopologies` in StorageClass, but when `selectedNode` is present (ie. `WaitForFirstConsumer` is present) VCP could place the Volume in the same zone as the `selectedNode` thus ensuring correctness. Let me know if you agree to this proposal and find a need.

**Comment by subramanian-neelakantan** [comment]
> @subramanian-neelakantan, besides @embano1 questions, which k8s version supports `WaitForFirstConsumer` volume binding mode? I've been testing it on a v1.13.5 cluster and even when the scheduler is adding the `volume.kubernetes.io/selected-node` label to the pvc, the VCP (with zones) is creating the pv on a datastore not accessible for that particular node.

Hi Ferran @frodenas, as per current implementation of VCP, the zone has to be specified in `allowedTopologies` in SC for the volume to be placed in the correct zone. Let me know if this does not work for you.

**Comment by frodenas** [comment]
> > As per the volume creation (datastore selection) logic described by you, I wonder: is it really needed to specify `allowedTopologies` in the StorageClass then? Because the scheduler gets back with a Kubernetes node (VM) recommendation to the persistent volume controller, this would not be needed since we check the corresponding vSphere host for that VM and its associated datastores, right?
> 
> As of now when placing a Volume, VCP does not use the pod scheduler's `selectedNode`. It only uses the zone information specified in `allowedTopologies` of the StorageClass if available. The reason I think ignoring the `selectedNode` is alright is that VCP always selects only a shared datastore to place the Volume and so is guaranteed visibility to the pod.
> 

Are you assuming that `allowedTopologies` has a single zone? So if I have a StorageClass with 3 zones specified at the `allowedTopologies` and `volumeBindingMode` set to `WaitForFirstConsumer`, when I create a Stateful using a PVC with that StorageClass, I expect that kubernetes scheduler will pick a node based on my pod’s scheduling constraints, and then, the VCP should create the PV in a datastore accessible from this node. Are you saying that VCP does not use `selectedNode` so it may create the PV on a datastore not mounted on the node host?

> > @subramanian-neelakantan, besides @embano1 questions, which k8s version supports `WaitForFirstConsumer` volume binding mode? I've been testing it on a v1.13.5 cluster and even when the scheduler is adding the `volume.kubernetes.io/selected-node` label to the pvc, the VCP (with zones) is creating the pv on a datastore not accessible for that particular node.
> 
> Hi Ferran @frodenas, as per current implementation of VCP, the zone has to be specified in `allowedTopologies` in SC for the volume to be placed in the correct zone. Let me know if this does not work for you.

My SC had `allowedTopologies` (with 3 zones), and the volume was created on a datastore not accessible by the node where the scheduler placed my pod. I guess it's related to my previous comment. I can provide mode details about my topology if needed.

**Comment by rhockenbury** [comment]
> The way VCP works today, `allowedTopologies` must be specified in StorageClass to place a Volume in a specific zone. This could be changed/improved if we find a need. Proposed behaviour could be - In the absence of `allowedTopologies` in StorageClass, but when `selectedNode` is present (ie. `WaitForFirstConsumer` is present) VCP could place the Volume in the same zone as the `selectedNode` thus ensuring correctness. Let me know if you agree to this proposal and find a need.

The use case is that a storageClass would not be required per zone.  `allowedTopologies` currently only supports one zone value, which means multiple zones require multiple storageclasses.  The current implementation makes the user choose the zone (storageclass) when creating the PVC, when the desired behavior with `WaitForFirstConsumer` would be for the storage to follow the pod placement, regardless of zone.

**Comment by aegershman** [comment]
Witnessing same thing as https://github.com/kubernetes/kubernetes/issues/77535#issuecomment-496750131 and https://github.com/kubernetes/kubernetes/issues/77535#issuecomment-497843332

**Comment by embano1** [comment]
> `allowedTopologies` currently only supports one zone value
As per K8s API, `allowedTopologies` is of type array so that should not block you. We're working on fixing the in-tree VCP storage handling to have the user experience inline with that of the other cloud provider implementations fully supporting topology-aware volume scheduling.

**Comment by subramanian-neelakantan** [comment]
Please follow the fix to issues #78514 and #78841 for VCP supporting topology-aware scheduling.

**Comment by rhockenbury** [comment]
> > `allowedTopologies` currently only supports one zone value
> 
> As per K8s API, `allowedTopologies` is of type array so that should not block you. We're working on fixing the in-tree VCP storage handling to have the user experience inline with that of the other cloud provider implementations fully supporting topology-aware volume scheduling.

Right.  The issue is in how VCP uses `AllowedTopologies` when an array of zones is specified. #78841 looks like it addresses exactly that.

**Comment by xyloman** [comment]
Is there a resolution to this issue?
