### ISSUE TITLE
Client-go fake dynamic client forces initialization with an empty slice of objects

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#77547]
**What happened**:
When initializing client-go fake dynamic client, it requires an empty slice of objects or causes a panic:

```go
func () {
    fake.NewSimpleDynamicClient(runtime.NewScheme(), []runtime.Object{}...)
}
```

**What you expected to happen**:
The following not to panic

```go
func() {
    fake.NewSimpleDynamicClient(runtime.NewScheme())
}
```

**How to reproduce it (as minimally and precisely as possible)**:
Use the fake dynamic client in client-go without a list of initial objects (or nil)
```go
fake.NewSimpleDynamicClient(runtime.NewScheme(), []runtime.Object{}...)
```

**Comment by liggitt** [comment]
I cannot reproduce the issue:

```go
func TestConstruct(t*testing.T){
	scheme := runtime.NewScheme()
	client := NewSimpleDynamicClient(scheme)
	fmt.Println(client)
}
```

```
=== RUN   TestConstruct
&{{{{0 0} 0 0 0 0} [] [0xc0001c3620] [0xc0001be4a0] [] []} 0xc0001d45b0}
--- PASS: TestConstruct (0.00s)
PASS
ok  	k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/fake	0.194s
```

**Comment by liggitt** [comment]
the desired usage is working already. a few examples:

https://github.com/kubernetes/kubernetes/blob/7faeee22b109d644f9a0ed736447e8867cae728e/pkg/kubectl/cmd/apply/apply_test.go#L1305

https://github.com/kubernetes/kubernetes/blob/7faeee22b109d644f9a0ed736447e8867cae728e/pkg/kubectl/cmd/wait/wait_test.go#L108

/close
