### ISSUE TITLE
When restartPolicy is never and sandbox is exited,we should set pod phase is Failed

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#77544]
**What happened**:
For pod's restartPolicy is never, first time there is no sandbox for a pod, kubelet will create a new sandbox for this pod.but for same reason(maybe network is notReady, so it can not set up network for this sandbox, kubelet will stop this sandbox), the sangbox status is notReady, then the next time kubelet will not create a new  sandbox,but the pod's phase is pending

**What you expected to happen**:
When restartPolicy is never and sandbox is exited,we should set pod phase is Failed

**How to reproduce it (as minimally and precisely as possible)**:
stop the network, then create a pod whose restartPolicy is never.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mattjmcnaughton** [comment]
Thanks for opening discussion on this @mysunshine92 !

Could you start by adding clarification on what the current state is and adding an example to reproduce that current state?

Could you also share more about why you think this change would be a good idea? Thanks!

**Comment by mysunshine92** [comment]
> 
> 
> Thanks for opening discussion on this @mysunshine92 !
> 
> Could you start by adding clarification on what the current state is and adding an example to reproduce that current state?
> 
> Could you also share more about why you think this change would be a good idea? Thanks!

thanks for your comments. now that sandbox is exited, and kubelet will never create a new sandbox, if set the phase is pending, it will be confused.
