### ISSUE TITLE
Large tests (>500 nodes) fail on cluster set-up

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#77551]
**Which jobs are failing**: sig-scalability-gce/gce-scale-performance

**Which test(s) are failing**: Up

**Since when has it been failing**: since today

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance

**Reason for failure**: Set-up scripts report only 500 nodes to be up, even though we see in api-server more nodes that registered

**Comment by mm4tt** [comment]
Looks like the pagination (controlled via --chunk-size) was enabled in kubectl. The default is 500 rows, which explains the behavior we see in the failing tests.
I wasn't able to find the culprit CL, but found an easy fix. Will send a PR shortly

**Comment by liggitt** [comment]
> I wasn't able to find the culprit PR

broke in #75993, fixed in #77580 (with added tests)

**Comment by mm4tt** [comment]
Ah, thanks, I thought https://github.com/kubernetes/kubernetes/pull/75993 could related, but it wasn't really obvious to me that it was the real culprit.
Thanks for fixing, once https://github.com/kubernetes/kubernetes/pull/77580 gets merged we can revert https://github.com/kubernetes/kubernetes/pull/77552

**Comment by mm4tt** [comment]
FYI, the temporary workaround seems to be working, the gce-scale-performance is running and not failing anymore on cluster creation - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1126034395224870915
