### ISSUE TITLE
Add Post-bind extension point to the scheduling framework

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#77566]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and extension points for "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.

[Post-bind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#post-bind) plugins are informational and called after a pod is successfully bound. This is the end of a binding cycle, and can be used to clean up associated resources.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by wgliang** [comment]
I'd like to take this :)

**Comment by bsalamat** [comment]
Yours! Thanks, Leon!
