### ISSUE TITLE
hpa Unable to get memory metrics

### ISSUE THREAD

**Issue by zijiwork** [kubernetes/kubernetes#77575]
Hello, guys, I might need your help. I am unable to  get memory metrics when configuring metrics-server.

- Kubernetes 1.13.5
- metrics-server 0.3.1
- kernel
CentOS Linux release 7.6.1810 (Core)    4.4.176-1.el7.elrepo.x86_64 x86_64

```
kubectl  version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
[root@K8S-PROD-MASTER-A1 ~]# kubectl  top node 
kubec	tlNAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
10.211.18.11   66m          6%     377Mi           31%       
10.211.18.4    175m         17%    923Mi           82%       
10.211.18.5    152m         15%    953Mi           78%       
10.211.18.50   49m          4%     373Mi           62%       
10.211.18.6    153m         15%    970Mi           79%       
[root@K8S-PROD-MASTER-A1 ~]# kubectl top pod 
NAME                          CPU(cores)   MEMORY(bytes)   
curl-66959f6557-nwhsh         0m           1Mi             
nginx-5c7588df-xz686          0m           1Mi             
nginx-test-78bb4ff9cf-bdpv7   0m           2Mi
```

hpa I can't get memory metrics when I use targetAverageValue.    targetAverageUtilization Parameters can work properly
```
[root@K8S-PROD-MASTER-A1 metrics-server]# kubectl  get hpa 
NAME             REFERENCE               TARGETS                   MINPODS   MAXPODS   REPLICAS   AGE
nginx-test-hpa   Deployment/nginx-test   <unknown>/300Mi, 0%/80%   1         3         1          78m
```

```
[root@K8S-PROD-MASTER-A1 metrics-server]# kubectl  describe  hpa nginx-test-hpa  
Name:                                                  nginx-test-hpa
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           kubectl.kubernetes.io/last-applied-configuration:
                                                         {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"nginx-test-hpa","namespace":"def...
CreationTimestamp:                                     Wed, 08 May 2019 10:05:18 +0800
Reference:                                             Deployment/nginx-test
Metrics:                                               ( current / target )
  resource memory on pods:                             <unknown> / 300Mi
  resource cpu on pods  (as a percentage of request):  0% (0) / 80%
Min replicas:                                          1
Max replicas:                                          3
Deployment pods:                                       1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from memory resource
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedGetResourceMetric       68m                  horizontal-pod-autoscaler  unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  68m                  horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)
  Warning  FailedGetResourceMetric       9m20s (x7 over 43m)  horizontal-pod-autoscaler  unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  9m20s (x7 over 43m)  horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)
```

The kube-porxy component has the following error. Does this affect normal operation?
```
May  8 11:14:19 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:19.516354   19470 graceful_termination.go:174] Deleting rs: 10.99.203.203:443/TCP/10.99.67.2:443
May  8 11:14:19 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:19.517392   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:53/UDP/10.99.67.7:53
May  8 11:14:19 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:19.517491   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:53/UDP/10.99.67.7:53
May  8 11:14:41 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:41.916533   19470 graceful_termination.go:160] Trying to delete rs: 10.99.167.169:80/TCP/10.99.67.4:80
May  8 11:14:41 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:41.916614   19470 graceful_termination.go:174] Deleting rs: 10.99.167.169:80/TCP/10.99.67.4:80
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.510327   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:53/TCP/10.99.67.6:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.510384   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:53/TCP/10.99.67.6:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.510568   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:9153/TCP/10.99.67.6:9153
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.510669   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:9153/TCP/10.99.67.6:9153
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.510858   19470 graceful_termination.go:160] Trying to delete rs: 10.99.255.171:443/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.510894   19470 graceful_termination.go:174] Deleting rs: 10.99.255.171:443/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.511499   19470 graceful_termination.go:160] Trying to delete rs: 10.99.8.0:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.511535   19470 graceful_termination.go:174] Deleting rs: 10.99.8.0:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.511769   19470 graceful_termination.go:160] Trying to delete rs: 10.99.8.1:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.511805   19470 graceful_termination.go:174] Deleting rs: 10.99.8.1:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.511901   19470 graceful_termination.go:160] Trying to delete rs: 10.211.18.50:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.511933   19470 graceful_termination.go:174] Deleting rs: 10.211.18.50:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.512029   19470 graceful_termination.go:160] Trying to delete rs: 127.0.0.1:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.512058   19470 graceful_termination.go:174] Deleting rs: 127.0.0.1:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.512197   19470 graceful_termination.go:160] Trying to delete rs: 192.168.187.139:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.512232   19470 graceful_termination.go:174] Deleting rs: 192.168.187.139:32279/TCP/10.99.67.8:8443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.544407   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:53/UDP/10.99.67.6:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.544481   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:53/UDP/10.99.67.6:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.867829   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:53/TCP/10.99.67.7:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.868131   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:53/TCP/10.99.67.7:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.868533   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:9153/TCP/10.99.67.7:9153
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.872924   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:9153/TCP/10.99.67.7:9153
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.890052   19470 graceful_termination.go:160] Trying to delete rs: 10.99.203.203:443/TCP/10.99.67.2:443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.890701   19470 graceful_termination.go:174] Deleting rs: 10.99.203.203:443/TCP/10.99.67.2:443
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.896144   19470 graceful_termination.go:160] Trying to delete rs: 10.99.110.110:53/UDP/10.99.67.7:53
May  8 11:14:42 K8S-PROD-LB-A1 kube-proxy: I0508 11:14:42.896243   19470 graceful_termination.go:174] Deleting rs: 10.99.110.110:53/UDP/10.99.67.7:53

``` 
@kubernetes/sig-autoscaling

**Comment by zijiwork** [comment]
@kubernetes/sig-autoscaling

**Comment by ssslkj123** [comment]
I got the same problem with you ，and no ideal how to resolve it , 
`# kubectl  describe  hpa
Name:                                                  deployment-hpa-test
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           kubectl.kubernetes.io/last-applied-configuration:
                                                         {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"deployment-hpa-test","namespace"...
CreationTimestamp:                                     Wed, 19 Jun 2019 10:28:12 +0800
Reference:                                             Deployment/nginx-hpa
Metrics:                                               ( current / target )
  resource memory on pods:                             <unknown> / 10Mi
  resource cpu on pods  (as a percentage of request):  0% (0) / 30%
Min replicas:                                          1
Max replicas:                                          8
Deployment pods:                                       8 current / 8 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from memory resource
  ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       27m (x4 over 27m)  horizontal-pod-autoscaler  unable to get metrics for resource memory: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  27m (x4 over 27m)  horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
  Normal   SuccessfulRescale             25m                horizontal-pod-autoscaler  New size: 2; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             22m                horizontal-pod-autoscaler  New size: 3; reason: memory resource above target
  Normal   SuccessfulRescale             20m                horizontal-pod-autoscaler  New size: 5; reason: memory resource above target
  Normal   SuccessfulRescale             19m                horizontal-pod-autoscaler  New size: 6; reason: memory resource above target
  Normal   SuccessfulRescale             18m                horizontal-pod-autoscaler  New size: 7; reason: memory resource above target
  Normal   SuccessfulRescale             17m                horizontal-pod-autoscaler  New size: 8; reason: memory resource above target
  Warning  FailedGetResourceMetric       4m20s              horizontal-pod-autoscaler  unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  4m20s              horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)`

`kubectl  top nodes
NAME         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
10.65.2.19   150m         1%     5142Mi          40%       
10.65.2.20   93m          1%     8072Mi          63%       
10.65.2.21   64m          0%     2867Mi          22%       
10.65.2.22   55m          0%     5107Mi          9%        
10.65.2.23   111m         0%     5464Mi          10%       
10.65.2.24   48m          0%     8336Mi          16%       
10.65.2.25   42m          0%     4576Mi          8%        
10.65.2.26   75m          0%     6458Mi          12%       
10.65.2.27   54m          0%     5325Mi          10%       
10.65.2.4    1306m        2%     29115Mi         14%       
10.65.2.5    123m         0%     6238Mi          3%        
10.65.2.6    630m         1%     14738Mi         7%`

`kubectl  get hpa
NAME                  REFERENCE              TARGETS                  MINPODS   MAXPODS   REPLICAS   AGE
deployment-hpa-test   Deployment/nginx-hpa   <unknown>/10Mi, 0%/30%   1         8         8          47m`

BTW ,  I have already add following args  in the metrics-server

`
        command:
        - /metrics-server
        - --metric-resolution=15s
        - --kubelet-insecure-tls
        - --requestheader-allowed-names=metrics-server
        - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
        - --kubelet-insecure-tls
`
apiserver's args
`
  --requestheader-client-ca-file=/etc/kubernetes/pki/ca.pem \
  --requestheader-allowed-names="" \
  --requestheader-extra-headers-prefix="X-Remote-Extra-" \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --proxy-client-cert-file=/etc/kubernetes/pki/kube-metrics-server.pem \
  --proxy-client-key-file=/etc/kubernetes/pki/kube-metrics-server-key.pem \
`
controller's args
`
  --experimental-cluster-signing-duration 87600h10m0s \
  --use-service-account-credentials=true \
  --horizontal-pod-autoscaler-use-rest-clients=true \
  --v=2

`

**Comment by mathisub** [comment]
I have the same issue after upgrading the cluster to 1.13.5. 
NAME              REFERENCE                TARGETS                   MINPODS   MAXPODS   REPLICAS   AGE
hello-world-hpa   Deployment/hello-world   <unknown>/200Mi, 0%/10%   2         10        2          46h
I am using metrics-server 0.3.2.

**Comment by mathisub** [comment]
My issue was resolved by updating the hpa pod yaml with the correct syntax for v2beta2 version.
Example: 
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: mypod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mypod
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50

**Comment by mathisub** [comment]
didn't copy appropriately: pasting the metrics portion:  
metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50

**Comment by isurulucky** [comment]
Facing a similar issue with K8s server version 1.14.3. However in my case its the memory percentage that is not working. Providing the absolute value works:
```
$ kubectl describe hpa.v2beta1.autoscaling petbemem--controller-autoscalepolicy-hpa

Name:                                                     petbemem--controller-autoscalepolicy-hpa
Namespace:                                                default
Labels:                                                   app=petbemem--controller
                                                          mesh.cellery.io/cell=petbemem
                                                          mesh.cellery.io/service=petbemem--controller
Annotations:                                              <none>
CreationTimestamp:                                        Thu, 11 Jul 2019 17:48:50 +0530
Reference:                                                Deployment/petbemem--controller-deployment
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  <unknown> / 30%
Min replicas:                                             1
Max replicas:                                             3
Deployment pods:                                          1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for memory
Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedGetResourceMetric       34m (x4 over 34m)   horizontal-pod-autoscaler  unable to get metrics for resource memory: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  34m (x4 over 34m)   horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  32m (x8 over 33m)   horizontal-pod-autoscaler  failed to get memory utilization: missing request for memory
  Warning  FailedGetResourceMetric       4m (x115 over 33m)  horizontal-pod-autoscaler  missing request for memory
```

It says memory request is not found but its correctly set:

```
spec:
  containers:
    image: isurulucky/hpatest
    imagePullPolicy: Always
    name: hpatest
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 64Mi
```

**Comment by willzhang** [comment]
```
        args:
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
```

**Comment by mathisub** [comment]
In my case "kubectl top po" was working and HPA was unable to get the metrics data. The recycling of the metrics-server resolved the HPA authentication issue with k8s API server.

**Comment by eliteGoblin** [comment]
I encountered the same issue, I found that after I change raw value of memory to percentage, it works: 

```yaml
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: podinfo
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      # targetAverageValue: 200Mi  not work, changed to below
      targetAverageUtilization: 80
```

my cluster is setup by kops v1.13
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by francardoso93** [comment]
I had all resources properly set in all containers and kept struggling with this. The only solution I found was to downgrade from apiVersion: autoscaling/v2beta2 to apiVersion: autoscaling/v2beta1

**Comment by danksim** [comment]
> I had all resources properly set in all containers and kept struggling with this. The only solution I found was to downgrade from apiVersion: autoscaling/v2beta2 to apiVersion: autoscaling/v2beta1

I am having the same issue. The deployment/pod has cpu/memory requests/limits set properly. I would rather not downgrade since I am trying to upgrade kubernetes to v1.25. Weird.
