### ISSUE TITLE
Unexpectedly large results from kubelet_volume_stats_used_bytes

### ISSUE THREAD

**Issue by dwbrown2** [kubernetes/kubernetes#77570]
**What happened**:

We're trying to measure persistent volume utilization and Prometheus is currently reporting `kubelet_volume_stats_used_bytes` that is 20x+ the size of the corresponding persistent volume claim. It's happening in two persistent volumes that are both glusterfs -- they're not the only gluster volumes in this cluster, but they are the only ones that are PV+PVC volumes. The underlying glusterfs is large in both situations where this is occurring (as one can see in the `df -h` output) relative to the PVC. This issue is occurring on an AWS cluster. 

**What you expected to happen**:
Used bytes being less than or equal to the size of the persistent volume claim request.

**Environment**:
- Cloud provider or hardware configuration: AWS
- Install tools: kubeadm

**Comment by dwbrown2** [comment]
@kubernetes/sig-storage-bugs -- apologies if I'm reporting this in the wrong place.

**Comment by msau42** [comment]
/remove-lifecycle rotten
Is this still an issue? cc @humblec

**Comment by dwbrown2** [comment]
I unfortunately don't have access to a cluster w/ glusterfs right now so can't confirm at the moment.

**Comment by humblec** [comment]
@dwbrown2 the metrics for glusterfs was tested in a great extent and never heard such reports. So, wondering is this still an issue ? if not, we may close this and reopen or open an issue accordingly.

**Comment by dwbrown2** [comment]
Happy to close and reopen if I can repro again.

**Comment by shibumi** [comment]
Hi, I have the same issue just with NFS as storage provider. Any idea?
