### ISSUE TITLE
Token request: opt out of the token controller generated secrets

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#77599]
The controller manager will optionally use the `TokenRequest` API to provision tokens for controllers.  These SA based controllers no longer need secret based tokens.

Action items:

1. Determine how to opt out of the token controller generated secrets (generically)
1. Use the above generic functionality to make it so that the only tokens for the controller clients are ephemeral and short lived

/sig auth
/sig api-machinery

@kubernetes/sig-auth-feature-requests 

xref: #70679 #71275 #72179

/priority important-longterm

**Comment by WanLinghao** [comment]
Since patch #72179 would be contained in v1.15, does that mean we should start clean work after v1.15 released?
> Determine how to opt out of the token controller generated secrets (generically)

**Comment by liggitt** [comment]
Stopping auto-generating new secret-based tokens and removing existing unused secret-based tokens is being addressed in KEP 2799 (https://github.com/kubernetes/enhancements/pull/2800)

/close
