### ISSUE TITLE
[Flaking Tests] scheduler.TestUnreservePlugin flaking in ci-kubernetes-integration-master

### ISSUE THREAD

**Issue by jimangel** [kubernetes/kubernetes#77601]
**Which jobs are failing**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1126051507540594695

**Which test(s) are failing**:
scheduler.TestUnreservePlugin

**Since when has it been failing**:
Ran 9 times between 5/6 and 5/7, succeeding only once. Not present anywhere else.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Reason for failure**:
```
I0508 09:28:51.061633  108159 healthz.go:184] [+]ping ok
[+]log ok
[-]etcd failed: reason withheld
[+]poststarthook/generic-apiserver-start-informers ok
[-]poststarthook/bootstrap-controller failed: reason withheld
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld
[-]poststarthook/ca-registration failed: reason withheld
healthz check failed


logging error output: "[+]ping ok\n[+]log ok\n[-]etcd failed: reason withheld\n[+]poststarthook/generic-apiserver-start-informers ok\n[-]poststarthook/bootstrap-controller failed: reason withheld\n[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld\n[-]poststarthook/ca-registration failed: reason withheld\nhealthz check failed\n"
```

**Anything else we need to know**:

/sig scheduling
/sig testing
/priority important-soon
/kind flake
/milestone v1.15

CC: @alejandrox1 @smourapina @rarchk

**Comment by danielqsj** [comment]
@jimangel this test was reverted by https://github.com/kubernetes/kubernetes/pull/77577.
It will not block others now.

**Comment by jimangel** [comment]
Thanks @danielqsj !

/close

**Comment by alejandrox1** [comment]
Let's maintain this one open so we can keep an eye on it 👀 
/reopen

**Comment by alejandrox1** [comment]
This looks resolved.
/close
