### ISSUE TITLE
Token request: proactively remove unused secret based SA tokens

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#77600]
Once it is possible to opt out of secret based SA tokens, any preexisting secrets should be removed.

Action items:

1. Clean up legacy tokens for the controller service accounts after a release

/sig auth
/sig api-machinery

@kubernetes/sig-auth-feature-requests 

xref: #70679 #71275 #72179 #77599

/priority important-longterm

**Comment by WanLinghao** [comment]
Since patch #72179 would be contained in v1.15, does that mean we should start clean work after v1.15 released?

> Clean up legacy tokens for the controller service accounts after a release

**Comment by liggitt** [comment]
We can start considering how we'd enable a service account to indicate it didn't want secret tokens in 1.15, but yes, we would not have the controller-manager switch to using that until at least 1.16

**Comment by liggitt** [comment]
Stopping auto-generating new secret-based tokens and removing existing unused secret-based tokens is being addressed in KEP 2799 (https://github.com/kubernetes/enhancements/pull/2800)

/close
