### ISSUE TITLE
Kube Components no longer log to STDERR/STDOUT

### ISSUE THREAD

**Issue by rdodev** [kubernetes/kubernetes#77624]
**What happened**:

`kubectl log` for kubeapiserver, schedulers and controllermanager only show startup and "stale" data. 

**What you expected to happen**:
I expected to see all the logs as they are logged

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl log kube-apiserver-pod-name -n kube-system -f`

**Anything else we need to know?**:
Docs say since the move to klog, logs are no longer output to STDERR/STDOUT and are instead logged to /var/log/ [here]( https://kubernetes.io/docs/concepts/cluster-administration/logging/)

>  System components inside containers always write to the /var/log directory, bypassing the default logging mechanism

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
orduzr-a01:ui ruben$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-05-01T20:29:33Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): `Linux kubeconeu19-control-plane 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux`

**Comment by rdodev** [comment]
@dims

**Comment by rdodev** [comment]
Interesting: in a different cluster (same version/configuration) by setting `--v=5` in the manifest for each of those components does the trick, and `kubectl exec` into those containers show there are no files being written to `/var/log/` so ... perhaps it's the docs that are no longer accurate? :)

**Comment by vincepri** [comment]
Seems like this is a documentation issue, by default components using klog write to stderr. Does that sound right @dims?

**Comment by vincepri** [comment]
Is this still the case for 1.15? If not, we should probably close it

**Comment by rdodev** [comment]
@vincepri I thought we had agreed this was a doc issue, right? If so, if the docs have been fixed, then we can close this issue.
