### ISSUE TITLE
Measuring the period of downtime when upgrading kubeadm from version 1.13.0 to v1.14.0

### ISSUE THREAD

**Issue by truongnh1992** [kubernetes/kubernetes#77628]
Hi there, could anyone do me a favor, please.

I deployed a Single-Instance Stateful Application on K8S cluster version 1.13.0 (1 master node & 1 worker node)
https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

How can I measure the period of downtime when upgrading kubeadm from current version 1.13.0 to v1.14.0?

Thank you.

**Comment by neolit123** [comment]
hi,
it depends on how fast your node machines, how heavy your StatefulSet application is, but i wouldn't expect more than 1 minute of downtime for the setup you are describing.

to gather more responses on the subject try the k8s slack channel #kubeadm or ask on stack-overflow.

thanks.
/remove-sig contributor-experience
/sig cluster lifecycle
/close
