### ISSUE TITLE
explain deployment.spec.strategy.rollingUpdate.maxSurge and maxUnavailable wrong defaults

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#77641]
**What happened**:
`kubectl explain deployment.spec.strategy.rollingUpdate` explains that both `maxSurge` and `maxUnavailable` are `1` by default, while they are `25%` by default.

**What you expected to happen**:
It should be `25%`

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl explain deployment.spec.strategy.rollingUpdate`

**Anything else we need to know?**:

**Environment**: N/A
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
The defaults are different in different API versions. Those are the defaults for those fields in extensions/v1beta1. Use `--api-version=<group>/<version>` to see the docs for the version you are interested in

/close
