### ISSUE TITLE
Kubelet restarts Docker daemon frequently in AWS M5 instances

### ISSUE THREAD

**Issue by Bujail** [kubernetes/kubernetes#77654]
**What happened**:
Docker daemons are getting restarted frequently.

**What you expected to happen**:
Docker daemon need to be stable.

**How to reproduce it (as minimally and precisely as possible)**:
Cluster created using Kubeadm 1.14.1 in AWS with Instance type m5.xlarge

**Anything else we need to know?**:

Kubelet logs:

```
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.647547   16352 container.go:409] Failed to create summary reader for "/libcontainer_20433_systemd_test_default.slice": none of the resources are being tracked.
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.653567   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/libcontainer_20579_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/libcontainer_20579_systemd_test_default.slice: no such file or directory
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.653870   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_20579_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/libcontainer_20579_systemd_test_default.slice: no such file or directory
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.653898   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_20579_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_20579_systemd_test_default.slice: no such file or directory
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.656955   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/libcontainer_20596_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/libcontainer_20596_systemd_test_default.slice: no such file or directory
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.656989   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/libcontainer_20596_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/libcontainer_20596_systemd_test_default.slice: no such file or directory
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.657015   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/libcontainer_20596_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/libcontainer_20596_systemd_test_default.slice: no such file or directory
May  9 06:58:42 agent-e1-i-0ab8e91ed938021f3 kubelet: W0509 03:58:42.657039   16352 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_20596_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/libcontainer_20596_systemd_test_default.slice: no such file or directory

```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS 

- OS (e.g: `cat /etc/os-release`):

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

```
- Kernel (e.g. `uname -a`):
```
Linux agent-e1-i-0ab8e91ed938021f3 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
docker version
```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

cri-tools.x86_64           1.12.0-0            
kubeadm.x86_64             1.14.1-0           
kubectl.x86_64             1.14.1-0           
kubelet.x86_64             1.14.1-0            
kubernetes-cni.x86_64      0.7.5-0             

docker-ce.x86_64           3:18.09.5-3.el7     
docker-ce-cli.x86_64       1:18.09.5-3.el7

- Network plugin and version (if this is a network-related bug):

kubernetes-cni.x86_64      0.7.5-0
Overlay :  Weave Net 2.5.1

- Others:
I have converted the instances to m4.xlarge for testing, it was working perfectly

**Comment by mattjmcnaughton** [comment]
Hi @Bujail :) Hope we can help you make some progress on this issue.

Do you mind sharing more of the information that is causing you to believe that the Kubelet is responsible for restarting the Docker daemon? My understanding is that Kubelet doesn't actually mange the Docker daemon, it just expects it to be running.[1] My guess is that on Ubuntu 18.04, SystemD is managing the Docker daemon. 

1. The kubelet does, in many cases, run a shim over Docker, but that's separate from the actual docker daemon.

**Comment by Bujail** [comment]
Hi @mattjmcnaughton I came to that conclusion because of the kubelet logs. Docker daemon will restart just after reporting the 'systemd_test_default.slice: no such file or directory' error. This issue is more related to this [https://github.com/kubernetes/kubernetes/issues/76531](https://github.com/kubernetes/kubernetes/issues/76531)

**Comment by mattjmcnaughton** [comment]
@Bujail could you please post the Docker logs? I'm hopeful they'll help give us a better picture of what's going on.

This [documentation](https://docs.docker.com/config/daemon/) gives instructions on where they can be found on RHEL.

**Comment by Bujail** [comment]
Oops.. Sorry, My bad. The issue was not from the K8s end. There was a misconfiguration at puppet agent part. It was reinstalling docker daemon with another version every 20min(Package name was configured 18.09.5-3.el7 but puppet was trying to install 3:18.09.5-3.el7). But still I can see the   ```/libcontainer_6917_systemd_test_default.slice": none of the resources are being tracked``` and
```Error while processing event ("/sys/fs/cgroup/memory/libcontainer_14835_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory``` error in the logs. I think we can close this issue and track the slice related log flooding issue from here #76531 . Thanks @mattjmcnaughton

**Comment by mattjmcnaughton** [comment]
On Sat, May 11, 2019 at 09:27:22PM -0700, Bujail Swadiq K K wrote:
> Oops.. Sorry, My bad. The issue was not from the K8s end. There was a misconfiguration at puppet agent part. It was reinstalling docker daemon with another version every 20min(Package name was configured 18.09.5-3.el7 but puppet was trying to install 3:18.09.5-3.el7). But still I can see the   ```/libcontainer_6917_systemd_test_default.slice": none of the resources are being tracked``` and
> ```Error while processing event ("/sys/fs/cgroup/memory/libcontainer_14835_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory``` error in the logs. I think we can close this issue and track the slice related log flooding issue from here #76531 . Thanks @mattjmcnaughton 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/77654#issuecomment-491563574

Thanks for the update :)
