### ISSUE TITLE
Kubectl plugins: support global options

### ISSUE THREAD

**Issue by aermakov-zalando** [kubernetes/kubernetes#77666]
**What would you like to be added**:

If a `kubectl-foo` plugin binary exists, both `kubectl foo -n namespace` and `kubectl -n namespace foo` should work. Currently, only the first command would call the plugin binary, the second one would complain about a missing command.

**Why is this needed**:

Plugins should work correctly when using custom aliases that e.g. operate on a specific namespace.

**Comment by aermakov-zalando** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by aermakov-zalando** [comment]
No idea what would be the best way to handle it. The easiest way would be for `kubectl` to transform global options into command arguments, so the two commands would be equivalent.

**Comment by liggitt** [comment]
See https://github.com/juanvallejo/kubernetes/pull/9#discussion_r191944024 and https://github.com/juanvallejo/kubernetes/pull/9#issuecomment-393571640

cc @juanvallejo

**Comment by aermakov-zalando** [comment]
I'd argue that for global arguments the shape is already known, `kubectl options` even prints it out for you. This would allow aliases to work correctly with plugins so kubectl's UX isn't broken.

**Comment by Elgarni** [comment]
@liggitt @juanvallejo any thoughts on this? I'm thinking to open a PR to further discuss this with more details.

**Comment by liggitt** [comment]
I don't see anything to counter the points raised earlier. Opaque pass through of options to kubectl plugins is a fundamental part of the current design, and I'm not eager to trade that for ambiguous relocation of flags and associated arguments.

**Comment by Elgarni** [comment]
I see your point. Can't we though have both? Here is how I see the problem. 
```bash
kubectl [beforeOptions] plugin-command [afterOptions] 
```
The `beforeOptions` should be one of kubectl global options. Then the whole command should be perceived as follows:
```bash
kubectl plugin-command [afterOptions] [beforeOptions]
```
Moving forward with this implementation, I don't see any conflict with the [plugin design](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/0024-kubectl-plugins.md)

What do you think?

**Comment by liggitt** [comment]
Given the following plugins:
```
kubectl-foo
kubectl-foo-bar
```
and the invocation
```
kubectl foo --namespace x bar
```
which of the following should be invoked?
```
kubectl-foo --namespace x bar
kubectl-foo-bar --namespace x
```

Given that kubectl plugins are not required to handle all kubectl global options, and the ambiguity introduced by trying to relocate flags and associated values in the invocation, this doesn't seem like a good idea.

**Comment by Elgarni** [comment]
Let me clarify. The issue is not about handling global options _anywhere_, but rather handling only global options that come before the plugin command. 

In the implementation [here]():
```go
for idx := range cmdArgs {
		if strings.HasPrefix(cmdArgs[idx], "-") {
			break
		}
		remainingArgs = append(remainingArgs, strings.Replace(cmdArgs[idx], "-", "_", -1))
	}
```
The execution stops once it sees a dash. So a simple `kubectl -n somespace foo` will not work, while there is no reason why it should not work. 

is my concern clear to you?

**Comment by liggitt** [comment]
As described in https://github.com/juanvallejo/kubernetes/pull/9#discussion_r191944024 and https://github.com/juanvallejo/kubernetes/pull/9#discussion_r192124982, we don't have sufficient information to know if we should handle all flags and values as if they matched kubectl global flags, in order to relocate them after the plugin command

**Comment by Elgarni** [comment]
I am not sure exactly what you mean by sufficient information, can you elaborate a bit on that?

I see three scenarios:

&1:
```bash
kubectl --namespace somespace foo
```
This should work.

&2:
```bash
kubectl  foo --madeupflag madeupvalue
 ```
This should work too.

&3:
```bash
kubectl --madeupflag madeupvalue foo
 ```  
This should fail: `Error: unknown flag: --madeupflag`

are there other scenarios that could be confusing to decide on?

**Comment by liggitt** [comment]
> are there other scenarios that could be confusing to decide on?

yes, the one mentioned in https://github.com/kubernetes/kubernetes/issues/77666#issuecomment-577951716

**Comment by Elgarni** [comment]
Well, the current implementation combines non-flag args to form the list of plugin names to search. The enhancement I am thinking to add is, read the args from left to right. If a flag is known (.e.g a kubectl global option) then we know how to interpret it. Then we go to the next. If we encounter a flag that is not known, we can stop and raise a failure, since we don't know how it should be processed. 

I know this is not ideal, but it's an improvement over the current implementation, and does not break the current design.

**Comment by aermakov-zalando** [comment]
@liggitt The design results in pretty bad UX, though, with the plugins effectively unable to work like first-class commands.

In https://github.com/kubernetes/kubernetes/issues/77666#issuecomment-577951716, I think that `kubectl-foo-bar` is the only logical choice. Removing an argument shouldn't suddenly change the command that will be executed, and built-in `kubectl` commands support passing the namespace as the last argument.

I also don't understand the argument about requiring the plugins to support all `kubectl` arguments. If I run `kubectl plugin -n foo`, and the plugin doesn't support namespaces, the plugin will fail. Why should `kubectl -n foo plugin` silently work without any issues?

**Comment by liggitt** [comment]
> In [#77666 (comment)](https://github.com/kubernetes/kubernetes/issues/77666#issuecomment-577951716), I think that `kubectl-foo-bar` is the only logical choice. Removing an argument shouldn't suddenly change the command that will be executed...

That is exactly the problem. We don't know how `kubectl-foo` treats the `--namespace` flag, so we can't assume the token following `--namespace` on the command line should be consumed as part of consuming that flag.

**Comment by aermakov-zalando** [comment]
I still don't understand what problems do you see arising out of this. If I have `kubectl-foo` and `kubectl-foo-bar` on my $PATH, currently `kubectl foo -n test bar` invokes `kubectl-foo`, `kubectl foo bar -n test` invokes `kubectl-foo-bar`, and `kubectl -n test foo bar` **fails**. With my proposal, `kubectl -n test foo bar` will invoke `kubectl-foo-bar`, passing `-n test` to it, allowing it to work as a normal kubectl command. If it doesn't implement it, there might be some issues, but the same invocation flat out doesn't work right now, so how can this break anything?

**Comment by rnsv** [comment]
> Let me clarify. The issue is not about handling global options _anywhere_, but rather handling only global options that come before the plugin command.
> 
> In the implementation here:
> 
> ```go
> for idx := range cmdArgs {
> 		if strings.HasPrefix(cmdArgs[idx], "-") {
> 			break
> 		}
> 		remainingArgs = append(remainingArgs, strings.Replace(cmdArgs[idx], "-", "_", -1))
> 	}
> ```
> 
> The execution stops once it sees a dash. So a simple `kubectl -n somespace foo` will not work, while there is no reason why it should not work.
> 
> is my concern clear to you?

This is a valid ask.  Allowing kubectl global options to be passed down to plugin will help reuse those options.

**Comment by liggitt** [comment]
also discussed in https://github.com/kubernetes/kubectl/issues/884

**Comment by ahmetb** [comment]
> The easiest way would be for `kubectl` to transform global options into normal arguments

> Allowing kubectl global options to be passed down to plugin will help reuse those options in a consistent manner

It also will cause most plugins that exist today to fail. Majority of the plugins don't support global options from kubectl and potentially this behavior, but they do strict CLI options validation. So starting to pass new flags down to plugins is breaking behavior.

**Comment by aermakov-zalando** [comment]
Sorry! Misclicked.
