### ISSUE TITLE
Add mechanism to tell kubernetes that a node has gone down

### ISSUE THREAD

**Issue by bartwensley** [kubernetes/kubernetes#77660]
**What would you like to be added**:

I am interested in reducing the amount of time it takes for an endpoint to be removed from a service when a worker node goes down. I know that the --node-monitor-grace-period can be reduced from the default of 40s, but I'm more interested in a way to trigger this through the API.

For example, if an external entity knows that a node has rebooted, it would be useful to have a way to tell kubernetes that the node is not available. Kubernetes (the kube-controller-manager) could then trigger all the normal actions that are taken when the node status changes (e.g. marking the pods on the node as not ready and removing the pods endpoints from the associated services).

**Why is this needed**:

In the case where a worker node goes down (e.g. spontaneous reboot or power loss), it takes node-monitor-grace-period seconds for the endpoints for the pods on that node to be removed from their services. During that time period, any requests sent to pods on that node (through the service) will fail. If there was a way to tell kubernetes that the node was down, this period of failed requests could be reduced significantly.

**Comment by mattjmcnaughton** [comment]
Interesting idea - thanks for sharing @bartwensley !

I think this is an idea that, if it had the appropriate buy in, we'd definitely want to create a [Kubernetes Enhancement Proposal (KEP)](https://github.com/kubernetes/enhancements) for. I think responses to this issue (and potentially bringing it up in #sig-node on Slack or attending a sig-node meeting) will be a good guide of whether there's significant community interest, and I'm looking forward to hearing other's opinions.

In the shorter term, could you diminish the impact of a failed node on your services by configuring a stricter [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-tcp-liveness-probe)? I believe that would allow you to more quickly take a pod out of rotation when it stops responding to requests.

**Comment by bartwensley** [comment]
Thanks @mattjmcnaughton for the quick reply! The liveness probe won't help in my case (node rebooting or powered down) because the kubelet isn't there to do the liveness probe.

I will also bring this up on #sig-node, but would be nice to get feedback here as well so it is recorded for posterity.

**Comment by liggitt** [comment]
Actors other than the kubelet can patch node status if they are aware the node is not on. Can you describe why making use of the existing API is not sufficient?

**Comment by krmayankk** [comment]
> Actors other than the kubelet can patch node status if they are aware the node is not on. Can you describe why making use of the existing API is not sufficient?

@liggitt i think you mean `Actors other than the kubelet can patch pod status if they are aware the node is not on` , right ?

@bartwensley i think what Jordan is trying to say is that you could technically right something that would check if a node is down and using [readiness gates](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate), update the pod readiness gate to false. Although i agree this should just work out of the box without requiring extra work

**Comment by mattjmcnaughton** [comment]
On Thu, May 09, 2019 at 07:36:10AM -0700, Bart Wensley wrote:
> Thanks @mattjmcnaughton for the quick reply! The liveness probe won't help in my case (node rebooting or powered down) because the kubelet isn't there to do the liveness probe.
> 
> I will also bring this up on #sig-node, but would be nice to get feedback here as well so it is recorded for posterity.
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/77660#issuecomment-490930984

Ah yes, great point!

I am looking forward to the discussion on this :) and agree that @liggitt makes
an interesting point that'd be useful to explore further.

**Comment by bartwensley** [comment]
> Actors other than the kubelet can patch node status if they are aware the node is not on. Can you describe why making use of the existing API is not sufficient?

@liggitt Thanks for the suggestion. I had thought of patching the node status, but looking at the code that processes node status changes [1], I don't think that has any effect. The tryUpdateNodeHealth function will only update the observedReadyCondition if the gracePeriod has been exceeded - otherwise the currentReadyCondition and observedReadyCondition are the same and the caller (monitorNodeHealth) will not detect a change in the node status and will not take any action. The current code is only looking for cases where kubelet has not updated the node status - it isn't expecting an outside entity to change the status.

I could be wrong though - I'm new to this code. I was trying to test this out using kubectl to patch the node status, but that doesn't seem to work due to an open issue [2]. I will try this using the kubernetes API directly, but I'm wondering if the same limitation exists there?

If I'm right and tryUpdateNodeHealth doesn't currently process changes to the node status, would there be a willingness to update it to handle that case?

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L779
[2] https://github.com/kubernetes/kubernetes/issues/67455

**Comment by bartwensley** [comment]
@krmayankk - thanks for the suggestion, but the pod readiness gate feature isn't what I am looking for. It would require a spec update to every pod and then when a node went down, would require a status update for every pod on that node. Also, it looks to me like that feature relies on the kubelet, which is not running in the case of a node that is rebooting or has lost power.

**Comment by bartwensley** [comment]
@liggitt - I have used the kubernetes API to patch the node status, setting the Ready status to False. As I suspected, this does not have the expected behavior. The change in status causes the NoSchedule taint to be added to the node, but the pods are not marked as NotReady and remain on the node (which has been powered off in my case) indefinitely.

If there are no objections, I'll make the changes to support setting the node Ready status to False through the API and upload a patch for review.

**Comment by liggitt** [comment]
> If there are no objections, I'll make the changes to support setting the node Ready status to False through the API and upload a patch for review.

can you describe what changes you intend to make before opening  the PR? the APIs you require should already be available.

**Comment by bartwensley** [comment]
@liggit - Yes, the API to patch the node status is already there. The problem is in the node lifecycle controller [1]. The tryUpdateNodeHealth function only takes action if the gracePeriod has elapsed since the last update to the node status. The code is only looking for cases where kubelet has not updated the node status - it isn't expecting an outside entity to change the status. My plan is to update this code to also recognize that the node ready status has transitioned to false and do the same things that are currently done when the gracePeriod has elapsed.

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L779
