### ISSUE TITLE
Possible bug when decoding yaml/json into unstructured

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/kubernetes#77665]
## What happened:
During https://github.com/kubernetes/kubernetes/pull/75917 we discovered a failing test because of wrong int/float conversion on apply.

The problem got traced to how a json string gets decoded by sigs.k8s.io/yaml.
The string is:

```
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "test-svc"
  },
  "spec": {
    "ports": [
      {
        "port": 8080,
        "protocol": "UDP"
      }
    ]
  }
}
```

What we saw when unmarshalling this into unstructured was, that the results differ based on what unmarshaller we use and what we target in detail.

The different cases are:

### yaml/direct: sigs.k8s.io/yaml -> &unstructured.Unstructured{Object: map[string]interface{}{}}
```
u := &unstructured.Unstructured{Object: map[string]interface{}{}}
if err := yaml.Unmarshal(y, &u); err != nil {
	t.Fatal(err)
}
```
#### Result:
```
Port: 8080(int64)
```
### yaml/object: sigs.k8s.io/yaml -> &unstructured.Unstructured{Object: map[string]interface{}{}}**.Object**
```
u := &unstructured.Unstructured{Object: map[string]interface{}{}}
if err := yaml.Unmarshal(y, &u.Object); err != nil {
	t.Fatal(err)
}
```
#### Result:
```
Port: 8080(float64)
```

### json/direct: k8s.io/apimachinery/pkg/util/json -> &unstructured.Unstructured{Object: map[string]interface{}{}}
```
u := &unstructured.Unstructured{Object: map[string]interface{}{}}
if err := json.Unmarshal(y, &u); err != nil {
	t.Fatal(err)
}
```
#### Result:
```
Port: 8080(int64)
```

### json/object: k8s.io/apimachinery/pkg/util/json -> &unstructured.Unstructured{Object: map[string]interface{}{}}**.Object**
```
u := &unstructured.Unstructured{Object: map[string]interface{}{}}
if err := json.Unmarshal(y, &u.Object); err != nil {
	t.Fatal(err)
}
```
#### Result:
```
Port: 8080(int64)
```
### gojson/direct: encoding/json -> &unstructured.Unstructured{Object: map[string]interface{}{}}
```
u := &unstructured.Unstructured{Object: map[string]interface{}{}}
if err := gojson.Unmarshal(y, &u); err != nil {
	t.Fatal(err)
}
```
#### Result:
```
Port: 8080(int64)
```
### gojson/object: encoding/json -> &unstructured.Unstructured{Object: map[string]interface{}{}}**.Object**
```
u := &unstructured.Unstructured{Object: map[string]interface{}{}}
if err := gojson.Unmarshal(y, &u.Object); err != nil {
	t.Fatal(err)
}
```
#### Result:
```
Port: 8080(float64)
```

Additionally when setting the port in the json to 8080.0 (so float), all above approaches correctly convert to float64 except **yaml/direct: sigs.k8s.io/yaml -> &unstructured.Unstructured{Object: map[string]interface{}{}}** which does int64.

## What you expected to happen:
Consistency, documentation I guess. Took some time and luck to find this and I'm not even sure what this is or if it should be this way.

## How to reproduce it (as minimally and precisely as possible):
I created a gist with the test code I wrote while looking for this. Not beautiful but it shows the information above: https://gist.github.com/kwiesmueller/923e98898bd8d477bd1975f54d43b423
Just put the file at `staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/intfloat_test.go`
and run the Tests inside to see the output (in form of failures).
Sorry the test is tied around our fieldmanager code. I'll happily provide another example without involving our own logic, just was how the file evolved.

## Anything else we need to know?:
I created the ticket to move this discussion from our Slack channel.

/wg apply
/cc @apelisse @jennybuckley

**Comment by kwiesmueller** [comment]
One thing I found so far as well:
https://github.com/kubernetes/kubernetes/blob/95eb3a67020f6eabef08c3e9caf348149f469798/staging/src/k8s.io/apimachinery/pkg/util/json/json.go#L111
```
// convertNumber converts a json.Number to an int64 or float64, or returns an error
func convertNumber(n json.Number) (interface{}, error) {
	// Attempt to convert to an int64 first
	if i, err := n.Int64(); err == nil {
		return i, nil
	}
	// Return a float64 (default json.Decode() behavior)
	// An overflow will return an error
	return n.Float64()
}
```
used by k8s.io/apimachinery/pkg/util/json to fix the default gojson behavior. Thing is, sigs.k8s.io/yaml does not use this but the standard library.

**Comment by apelisse** [comment]
Why does it matter for us that it is a float or an int? Would something break if someone replaces `1` with `1.0`? I'm pretty sure it shouldn't.

**Comment by liggitt** [comment]
cc @sttts 

https://github.com/kubernetes-sigs/yaml/pull/14 might be relevant

**Comment by apelisse** [comment]
@kwiesmueller Haven't we fixed that one?

**Comment by kwiesmueller** [comment]
I think we solved the problem it caused but the exact thing in the description I don't know.

**Comment by apelisse** [comment]
Let's reopen if needed.
/close
