### ISSUE TITLE
Support service type as a field selector

### ISSUE THREAD

**Issue by rcorre** [kubernetes/kubernetes#77662]
**What would you like to be added**:

Allow `services` to be filtered by `spec.type`.

```
[rodencor@karminac ~]$ kubectl get svc --all-namespaces --field-selector=spec.type=LoadBalancer
Error from server (BadRequest): Unable to find "/v1, Resource=services" that match label selector "", field selector "spec.type=LoadBalancer": "spec.type" is not a known field selector: only "metadata.name", "metadata.namespace"
```

**Why is this needed**:

It is often important to differentiate between different kinds of services. For example, I'm trying to set up [resource count quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota) and want to count specifically how many LoadBalancers each namespace has (not just how many services in general).

**Comment by gigi-at-zymergen** [comment]
@rcorre This seems like a good idea to me, as we recently had to apply some updates to all nlbs created by the aws provider layer with annotations on services . I recognize we can work around with jq or grep on output, but would be nice for it to be supported as a field selector. Did you end up just solving this with jq?

**Comment by rcorre** [comment]
@gigi-at-zymergen it has been such a long time I don't remember :laughing: 
I'm guessing I filtered with `jq` or something similar.

**Comment by hixichen** [comment]
It seems a good idea to have type as field selector. 

not sure why this is closed.

**Comment by joemiao-exos** [comment]
We need this feature. It's especially useful when we try to collect and parse all the LoadBalancer info in a cluster.

**Comment by nonai** [comment]
+1

**Comment by TomaszKlosinski** [comment]
We're developing our own dashboard and we would like to see this feature implemented too.

**Comment by mans0954** [comment]
:+1:

**Comment by mkjpryor** [comment]
/remove-lifecycle rotten

I would also like to see this feature. For my use case, I need to be able to delete all the `LoadBalancer` services before deleting a cluster, because they correspond to load-balancers in the underlying cloud and the the cluster will not delete cleanly until they are gone.

**Comment by fedepaol** [comment]
This would help with loadbalancer implementations too, to save some resources (for example in metallb).

**Comment by boeboe** [comment]
This did the trick for me:

```console
  # Delete all service of type loadbalancer
  kubectl get svc -A \
    | grep "LoadBalancer" \
    | awk '{print "kubectl delete service " $2 " --namespace " $1}' \
    | while read kubectl_command ; do eval ${kubectl_command} ; done
```

**Comment by gecube** [comment]
@boeboe thanks for this bash almost one liner, but I also wonder why this feature could not be implemented by `kubectl` utility itself

**Comment by gecube** [comment]
@mkjpryor sounds that you need to implement a different process, because deleting LB from the cluster itself could be stuck. So anyway orphan LBs will exists and one will need to run a clean-up or some housekeeping process on some schedule basis.

**Comment by mkjpryor** [comment]
@gecube I did end up implementing a controller that deletes resources in the underlying cloud itself.

**Comment by aldesgroup** [comment]
This would indeed be nice to have

**Comment by wuleninja** [comment]
Still looking for a native way to filter the services by type

**Comment by wuleninja** [comment]
Ok, I've found this, to get the service of the right type, then its external IP: 

```
kubectl get services --all-namespaces -o jsonpath='{.items[?(@.spec.type=="LoadBalancer")].status.loadBalancer.ingress[0].ip}'
```

**Comment by aojea** [comment]
@bowei @cezarygerard @swetharepakula this can solve a lot of memory on the client side controllers that only need to watch LoadBalancer services

/close
