### ISSUE TITLE
When a Vmware node goes down, Kubernetes is unaware and PV isn't released

### ISSUE THREAD

**Issue by d4larso** [kubernetes/kubernetes#77678]
**What happened**:
If a Vmware node with a PV crashes, is shutdown or halted, Kubernetes is unaware and doesn't release the a pod's claim (PVC) on the PV.

**What you expected to happen**:
The PV should become "unattached" so the node and can be picked up for use by a Pod on another node.

**How to reproduce it (as minimally and precisely as possible)**:
Shutdown or halt a vmware VM and note that the associated PV can't be used by other nodes until the claim on the PV is deleted.

**Anything else we need to know?**:

**Environment**: vSphere Client version 6.7.0.30000
- Kubernetes version (use `kubectl version`): 1.13.5
- Cloud provider or hardware configuration: Vmware
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): Linux us03479-vsp1-m01 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): calico   v3.4.0
- Others:

**Comment by d4larso** [comment]
@kubernetes/sig-vmware-bugs

**Comment by dvonthenen** [comment]
Cross reference with:
https://github.com/kubernetes/kubernetes/issues/51835
