### ISSUE TITLE
Cache resource requests per Pod per resource name in getPodsToPreempt

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#77697]
**What would you like to be added**:
Cache resource requests per Pod per resource name (using a map) and pass it to calls of requirements.subtract() in getPodsToPreempt of preemption

**Why is this needed**:
In requirements.subtract(), we iterate over all containers of the Pod to calculate new quantity.
Such iteration is repeated at the scope of getPodsToPreempt.

Caching can reduce unnecessary repetition.

**Comment by mattjmcnaughton** [comment]
@tedyu did you intend to close your pr for this issue? Do you still think its something worthy of working on?

If not, mind closing the issue? Thanks!

**Comment by tedyu** [comment]
Planning to leave this open for a few days in case other people implement this caching.

**Comment by dashpole** [comment]
I'm not quite sure what the issue here is.  Are you seeing performance problems with kubelet preemption?  Is a large portion of the performance issue due to the calculation of pod resource requests?

**Comment by tedyu** [comment]
This enhancement was proposed when I saw repetitive calculation of resource requests in the code.

**Comment by mattjmcnaughton** [comment]
@tedyu mind closing this since we closed the pr? thank you!
