### ISSUE TITLE
initContainer metrics fail for cri-o runtime

### ISSUE THREAD

**Issue by villytiger** [kubernetes/kubernetes#77700]
**What happened**:
The metrics-server is unable to get metrics for pods with init containers.

**What you expected to happen**:
Metrics for pods with init containers show up.

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with an init container. Metrics are not gathered for that pod.

**Anything else we need to know?**:
Related to #74310. Must be fixed in v1.14.0, but for cri-o it isn't. A memory field is missing for terminated containers. I can't get any info for pods with init containers. I see the following data for an init container:
```json
     {
      "name": "frontend-init",
      "startTime": "2019-05-09T16:17:55Z",
      "cpu": {
       "time": "2019-05-09T18:54:57Z",
       "usageNanoCores": 0,
       "usageCoreNanoSeconds": 0
      },
      "rootfs": {
       "time": "2019-05-09T18:54:57Z",
       "availableBytes": 36474810368,
       "capacityBytes": 52586090496,
       "usedBytes": 3551232,
       "inodesFree": 25246479,
       "inodes": 25688064,
       "inodesUsed": 295
      },
      "logs": {
       "time": "2019-05-09T18:54:57Z",
       "availableBytes": 36474810368,
       "capacityBytes": 52586090496,
       "usedBytes": 4096,
       "inodesFree": 25246479,
       "inodes": 25688064,
       "inodesUsed": 441585
      },
      "userDefinedMetrics": null
     }
```

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.1
- Runtime:
cri-o 1.14.0

**Comment by vllry** [comment]
Just in case...

/sig node

**Comment by ashleykasim** [comment]
Seeing the same on k8s 1.14.4 and cri-o 1.14. Metrics-server v0.3.3 is skipping pods with exited init containers. 

Data returned from k8s stats/summary endpoint for a pod with an exited init container: 
```
"containers": [
...
    {
        "name": "iamwait",
        "startTime": "2019-07-31T22:55:36Z",
        "cpu": {
        "time": "2019-08-05T16:57:00Z",
        "usageNanoCores": 0,
        "usageCoreNanoSeconds": 0
        },
        "rootfs": {
        "time": "2019-08-05T16:57:00Z",
        "availableBytes": 442956890112,
        "capacityBytes": 459326619648,
        "usedBytes": 0,
        "inodesFree": 223987523,
        "inodes": 224390144,
        "inodesUsed": 3
        },
        "logs": {
        "time": "2019-08-05T16:57:00Z",
        "availableBytes": 3570970624,
        "capacityBytes": 7503589376,
        "usedBytes": 4096,
        "inodesFree": 3557157,
        "inodes": 3668976,
        "inodesUsed": 111819
        },
        "userDefinedMetrics": null
    },
...
]
```

I took a look and it looks like cri-o is correctly reporting a "0" value for exited containers. For the container in the above example, crictl returns this:

```# crictl stats --output=json
{
  "stats": [
    {
      ...
      "cpu": {
        "timestamp": "1564699000459692427",
        "usageCoreNanoSeconds": {
          "value": "0"
        }
      },
      "memory": {
        "timestamp": "1564699000459692427",
        "workingSetBytes": {
          "value": "0"
        }
      },
      ...
    }
  ]
}
```

**Comment by ashleykasim** [comment]
@villytiger did a little digging, https://github.com/kubernetes/kubernetes/issues/74310 would _not_ patch this for cri-o because kubernetes uses `cadvisor_stats_provider` rather than `cri_stats_provider` for cri-o. The reason for this is https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/helpers_linux.go#L42. This patch should fix it for us https://github.com/kubernetes/kubernetes/pull/73751.
