### ISSUE TITLE
Use framework.ExpectError() for e2e tests

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#77706]
**What happened**:

After fixing golint failures under `test/e2e` (now still in progress), we need to put `gomega` for each `Expect()` and `HaveOccurred()`.
Then common error checking code has become like:

`gomega.Expect(err).To(gomega.HaveOccurred())`

We can replace this code with `framework.ExpectError(err)` which is more readable and easy to be understood what the code does.

Now we have following e2e test directories which can be replaced:
- [x] test/e2e/apimachinery/ (https://github.com/kubernetes/kubernetes/pull/78279)
- [x] test/e2e/apps/ (https://github.com/kubernetes/kubernetes/pull/78279)
- [x] test/e2e/auth/ (https://github.com/kubernetes/kubernetes/pull/78279)
- [x] test/e2e/common/ (https://github.com/kubernetes/kubernetes/pull/78283)
- [ ] test/e2e/node/ (https://github.com/kubernetes/kubernetes/pull/78485)
- [ ] test/e2e/storage/ (https://github.com/kubernetes/kubernetes/pull/78485)
- [x] test/e2e/apps/deployment.go (https://github.com/kubernetes/kubernetes/pull/77709)
- [x] test/e2e/apps/cronjob.go (https://github.com/kubernetes/kubernetes/pull/77709)
- [x] test/e2e/apimachinery/resource_quota.go (https://github.com/kubernetes/kubernetes/pull/77709)
- [x] test/e2e/scheduling/limit_range.go (https://github.com/kubernetes/kubernetes/pull/77714)
- [x] test/e2e/kubectl/kubectl.go (https://github.com/kubernetes/kubernetes/pull/77709)
- [x] test/e2e/lifecycle/addon_update.go (https://github.com/kubernetes/kubernetes/pull/77709)
- [x] test/e2e/storage/volume_provisioning.go
- [x] test/e2e/storage/persistent_volumes-local.go
- [x] test/e2e/storage/volume_metrics.go  (https://github.com/kubernetes/kubernetes/pull/77718)
- [x] test/e2e/storage/testsuites/volumemode.go (https://github.com/kubernetes/kubernetes/pull/77718)
- [x] test/e2e/storage/vsphere/vsphere_zone_support.go
- [x] test/e2e/storage/vsphere/vsphere_volume_vsan_policy.go
- [x] test/e2e/storage/vsphere/vsphere_volume_datastore.go
- [x] test/e2e/storage/vsphere/vsphere_volume_fstype.go
- [x] test/e2e/node/kubelet.go (https://github.com/kubernetes/kubernetes/pull/77715)

**Comment by danielqsj** [comment]
/assign
PR will be submitted soon.

**Comment by danielqsj** [comment]
Fix the following in https://github.com/kubernetes/kubernetes/pull/77709
```
test/e2e/apimachinery/resource_quota.go
test/e2e/apps/cronjob.go
test/e2e/apps/deployment.go
test/e2e/kubectl/kubectl.go
test/e2e/lifecycle/addon_update.go
```

**Comment by danielqsj** [comment]
Fix `test/e2e/scheduling/limit_range.go` in #77714

**Comment by danielqsj** [comment]
Fix `test/e2e/node/kubelet.go` in https://github.com/kubernetes/kubernetes/pull/77715

**Comment by WanLinghao** [comment]
Hi, maybe I could take files beneath test/e2e/storage/vsphere/

**Comment by danielqsj** [comment]
@WanLinghao oops, I'm finished and prepare for PR.

**Comment by WanLinghao** [comment]
@danielqsj Thank you  That's OK

**Comment by danielqsj** [comment]
Fix the following in #77718
```
 test/e2e/storage/volume_provisioning.go
 test/e2e/storage/persistent_volumes-local.go
 test/e2e/storage/volume_metrics.go
 test/e2e/storage/testsuites/volumemode.go
 test/e2e/storage/vsphere/vsphere_zone_support.go
 test/e2e/storage/vsphere/vsphere_volume_vsan_policy.go
 test/e2e/storage/vsphere/vsphere_volume_datastore.go
 test/e2e/storage/vsphere/vsphere_volume_fstype.go
```

**Comment by danielqsj** [comment]
@oomichi All related PRs were merged. I think this ticket can be closed.
BTW, should we also replace `gomega.Expect(err).NotTo(gomega.HaveOccurred())` to `framework.ExpectNoError(err)` ?

**Comment by oomichi** [comment]
@danielqsj Thanks for your work. `framework.ExpectNoError(err)` thing is managed with https://github.com/kubernetes/kubernetes/issues/77103
We are almost finishing the work also :-)

**Comment by k-toyoda-pi** [comment]
I found `gomega.Expect(err).To(gomega.HaveOccurred())` in these files.
```
test/e2e/apimachinery/namespace.go
test/e2e/apimachinery/table_conversion.go
test/e2e/apimachinery/webhook.go
test/e2e/apps/job.go
test/e2e/auth/pod_security_policy.go
test/e2e/common/configmap.go
test/e2e/common/configmap_volume.go
test/e2e/common/expansion.go
test/e2e/common/privileged.go
test/e2e/common/projected_configmap.go
test/e2e/common/projected_secret.go
test/e2e/common/secrets.go
test/e2e/common/secrets_volume.go
test/e2e/node/mount_propagation.go
test/e2e/storage/csi_mock_volume.go
test/e2e/storage/utils/utils.go
test/e2e/storage/volume_expand.go
```
I'm working on :
```
test/e2e/apimachinery/namespace.go
test/e2e/apimachinery/table_conversion.go
test/e2e/apimachinery/webhook.go
test/e2e/apps/job.go
test/e2e/auth/pod_security_policy.go
```

**Comment by s-ito-ts** [comment]
I can work to the following item.

- test/e2e/common/configmap.go
- test/e2e/common/configmap_volume.go
- test/e2e/common/expansion.go
- test/e2e/common/privileged.go
- test/e2e/common/projected_configmap.go
- test/e2e/common/projected_secret.go
- test/e2e/common/secrets.go
- test/e2e/common/secrets_volume.go
