### ISSUE TITLE
Preserve container's working directory on kubectl exec

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#7770]
Hi there! I'm not familiar with Kubernetes' code base.
I traced the inner workings of `kubectl exec` to an [`ExecAction`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L552-L553), which is documented to be executed inside the container, and the working directory for the command  to be root ('/') in the container's filesystem.

This is, however, dissonant with how `docker exec` works:

```bash
$ docker ps | head -n 2
CONTAINER ID        IMAGE                                                                                                        COMMAND                CREATED             STATUS              PORTS               NAMES
555a2fd94619        172.30.17.221:5000/default/django-example:e0566c8be42b1611b11f47ed0c30706e4d3a72df79acd5e333e9976ed59795f3   "/usr/local/sti/run"   25 hours ago        Up 25 hours                             k8s_django-demo.597a8f9e_frontend-1-m7674_default_2eb052bb-f258-11e4-a47d-080027c5bfa9_765aba96      

$ openshift kubectl exec -p frontend-1-m7674 pwd                                             
/

$ docker exec 555a2fd94619 pwd                                                               
/opt/openshift/src
```

This behavior prevents us from running commands that use paths relative to the container's `WORKDIR`.

For instance, if we have a Django project inside a container, we'd like to use `kubectl exec` to run `python manage.py check` inside the container, but that's not possible unless we pass the full path to `manage.py`.

**Comment by dchen1107** [comment]
cc/ @vishh

**Comment by vishh** [comment]
The issue here is that we do not use `docker exec` and instead we run nsenter. I have been wanting to switch to using `docker exec` by default, but haven't gotten to it yet.

Related issue #6342

**Comment by rhcarvalho** [comment]
Thanks for the comments. @vishh would it be possible to change the working directory when using nsenter to match that of docker exec?

**Comment by vishh** [comment]
It is possible. There is also an open patch to add exec support to `nsinit`
(libcontainer) and use that instead.

**Comment by ncdc** [comment]
If we can get consensus, we'd like to move from `nsenter` to a custom executable that is similar to `nsinit` in that it does the equivalent to `docker exec` without requiring the daemon. Please see the comments starting here and going down: https://github.com/GoogleCloudPlatform/kubernetes/issues/6342#issuecomment-97549977

**Comment by rhcarvalho** [comment]
Seems that this has been fixed, at least with the default configuration that uses `docker exec`.

**Comment by lavalamp** [comment]
Please reopen if this is still an issue.
