### ISSUE TITLE
Add max-requests-inflight of event request

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#77723]
**What would you like to be added**:

We can use `--max-requests-inflight --max-mutating-requests-inflight` to control the number of the requests. But if too many request about event ,or we use `--etcd-servers-overrides` to override the event etcd and this etcd is too busy. Too many event  requests lead to other resource request may fail. For example , maybe 300 event requests are blocking and 100 pod requests can return normally but maybe other 200 pod requests are blocking because of too many requests.

**Why is this needed**:

Can we add different request limit for event and other resource?Just as `--max-event-requests-inflight` .
Because if api server has received too many requests, we should limit the event request or drop some, and need to ensure other resource request.

**Comment by yue9944882** [comment]
as for events, the admission controller `EventRateLimit` seems sufficient to resolve the issue. otoh, our guys' already been working on building a generic control-plane rate-limiting [WIP feature](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190228-priority-and-fairness.md), which can also help in a more flexible way in the future release.

**Comment by lavalamp** [comment]
I agree with @yue9944882; better fix is coming, for now use the EventRateLimit thingy.

**Comment by Nebulazhang** [comment]
@yue9944882 @lavalamp Thanks

**Comment by Nebulazhang** [comment]
@yue9944882 For `list` operation, I have some questions. when cluster has too many nodes and pods, just like `list pod`, it will put very large pressure for etcd. Does k8s have methods to limit for these heavy operations?

**Comment by yue9944882** [comment]
> Does k8s have methods to limit for these heavy operations?

firstly, there should be *too many* list calls in the cluster. try use the informer's cache as much as you can. for heavy list calls, we can do pagination. if the list pagination doesn't even help, there's a client-side rate limiting in client-go. sadly that rate limiting doesn't discriminate requests by verbs, but as the last resort we can build a dedicated client for lists.

**Comment by Nebulazhang** [comment]
> > Does k8s have methods to limit for these heavy operations?
> 
> firstly, there shouldn't be _too many_ list calls in the cluster. try use the informer's cache as much as you can. for heavy list calls, we can do pagination. if the list pagination doesn't even help, there's a client-side rate limiting in client-go. sadly that rate limiting doesn't discriminate requests by verbs, but as the last resort we can build a dedicated client for lists.

Thankyou

**Comment by jessehu** [comment]
Hi @yue9944882 @lavalamp, is the a default or recommended configuration for EventRateLimit?

The official doc https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#eventratelimit only provides this sample config:

> 
>  Below is a sample eventconfig.yaml for such a configuration:
> 
> apiVersion: eventratelimit.admission.k8s.io/v1alpha1
> kind: Configuration
> limits:
> - type: Namespace
>   qps: 50
>   burst: 100
>   cacheSize: 2000
> - type: User
>   qps: 10
>   burst: 50

**Comment by yue9944882** [comment]
> Hi @yue9944882 @lavalamp, is there a default or recommended configuration for EventRateLimit?

hi, i dont think there's a default limit configuration for this admission-controller (as far as i know)
