### ISSUE TITLE
kube-scheduler --policy-config-file flag is labeled DEPRECATED

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/kubernetes#77724]
I noticed that kube-scheduler --policy-config-file flag is labeled DEPRECATED since v1.11.
Without --policy-config-file flag, if I want to use shcheduler extender to add new scheduling rules, how should i do ?

**Comment by CermakM** [comment]
Really, what's the current way to extend the scheduler if this is deprecated? No luck so far figuring it out.
