### ISSUE TITLE
PLEG is not healthy

### ISSUE THREAD

**Issue by amoyx** [kubernetes/kubernetes#77728]
PLEG is not healthy: pleg was last seen active 3m3.928932625s ago; threshold is 3m0s
![image](https://user-images.githubusercontent.com/19795002/57512017-21df6a80-733d-11e9-9360-42feb9ec3a3f.png)
![image](https://user-images.githubusercontent.com/19795002/57512063-43d8ed00-733d-11e9-9854-04b68571fb2d.png)

**Comment by amoyx** [comment]
/sig node,   
I don't know whether it's Bug Report or Enhancement Request.

**Comment by neolit123** [comment]
please follow the issue template and provide more details about the problem.
/triage needs-more-information

**Comment by mysunshine92** [comment]
you can check if container runtime is not respone

**Comment by timyinshi** [comment]
I also encountered this problem. I found that docker could work normally. For example, when I inquired docker logs, information could be returned normally。
I think there is something wrong with the container of kube_proxy_pause, so I deleted a container of kube_proxy_pause. I found that my container was not started.
So I thought there might be a problem with kube_proxy_pod, so I removed kube_proxy_pod, but the pod didn't start automatically.
Finally I restarted kubelet and solved the problem.
I still don't understand why this problem occurred, do I have to restart kubelet after this problem occurred?
Error messages I encountered:
PLEG is not healthy: pleg was last seen active 3m40.438404083s ago; threshold is 3m0s

**Comment by Erically** [comment]
[PLEG is not healthy: pleg was last seen active 3m46.303313348s ago; threshold is 3m0s
delete deployment  --force --grace-period=0，then check if the container has been deleted

**Comment by yehaifeng** [comment]
I also have this issue.

My env:
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://paas-sh-01.99bill.com:443
openshift v3.11.0+0323629-61
kubernetes v1.11.0+d4cacc0

And it is not use by restart kubelet.
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832043  447731 kubelet_node_status.go:441] Recording NodeNotReady event message for node paas-node010024.99bill.com
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832028  447731 server.go:470] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"paas-node010024.99bill.com", UID:"paas-node010024.99bill.com", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientDisk' Node paas-node010024.99bill.com status is now: NodeHasSufficientDisk
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832053  447731 kubelet_node_status.go:835] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2019-11-06 18:08:10.832030177 +0800 CST m=+252.698806114 LastTransitionTime:2019-11-06 18:08:10.832030177 +0800 CST m=+252.698806114 Reason:KubeletNotReady Message:PLEG is not healthy: pleg was last seen active3m11.521744446s ago; threshold is 3m0s}
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832075  447731 kubelet_node_status.go:1077] Setting node status at position 7
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832075  447731 server.go:470] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"paas-node010024.99bill.com", UID:"paas-node010024.99bill.com", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientMemory' Node paas-node010024.99bill.com status is now: NodeHasSufficientMemory
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832108  447731 server.go:470] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"paas-node010024.99bill.com", UID:"paas-node010024.99bill.com", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasNoDiskPressure' Node paas-node010024.99bill.com status is now: NodeHasNoDiskPressure
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832173  447731 server.go:470] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"paas-node010024.99bill.com", UID:"paas-node010024.99bill.com", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node paas-node010024.99bill.com status is now: NodeNotReady
Nov 06 18:08:12 paas-node010024.99bill.com origin-node[447731]: I1106 18:08:10.832250  447731 kubelet_node_status.go:1077] Setting node status at position 8
