### ISSUE TITLE
Share one master node across multiple clusters

### ISSUE THREAD

**Issue by x8091** [kubernetes/kubernetes#77725]
We need to support multi-tenancy in k8s cluster. I found some articles mention about using namespace isolation for that, but it doesn't suit well in our case. Is there any other way to achieve this?

Actually, it's best for us if we can share one master node across multiple k8s clusters. Is it even possible? If yes, what we need to do?

**Comment by liggitt** [comment]
No, one apiserver only serves a single cluster. 
/close
