### ISSUE TITLE
EBS API polling when creating a volume

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/kubernetes#77741]
**What happened**:

When creating an EBS volume, we're currently waiting for the volume be in the correct state before proceeding:

https://github.com/kubernetes/kubernetes/blob/88ed776c6b447b1882a5fe99df0cfcaba1da4e72/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2398-L2421

However, we're using the interval defined in `encryptedCheckInterval` (e.g., 1 second), which was meant to be used for another reason and might be too soon for this specific case. Also, this might contribute to the API quota being exceeded.

CC @gnufied @leakingtapan 
/sig storage
/sig aws

**Comment by gnufied** [comment]
Yeah I think, this should be considered a regression. Many of our AWS clusters run on very thin margin of API quota and this would tip them over the edge.
