### ISSUE TITLE
Remount requires flag should be tracked inside desired state of world

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#77758]
While discussing https://github.com/kubernetes/enhancements/pull/737#discussion_r277895607, we came across a problem that is - the fact that a volume requires remount is tracked inside Actual State of World and not desired state of the world.

Resize required is also currently tracked inside ASOW. Resize required is being fixed - https://github.com/kubernetes/kubernetes/pull/77755 but remount required should be fixed separately.

/sig storage

cc @kubernetes/sig-storage-bugs

**Comment by jingxu97** [comment]
@gnufied is this still an issue?
