### ISSUE TITLE
DNS hostname "localhost" causes failing apiserver

### ISSUE THREAD

**Issue by kraney** [kubernetes/kubernetes#77764]
**What happened**:
This is on a cluster that I upgrade from 1.11.10 to 1.12.8. It's not clear whether the upgrade is related to the issue or not.

I am seeing apiserver repeatedly fail and be restarted, with this error:
```
Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://localhost:6443/api/v1/services: dial tcp 10.36.159.80:6443: connect: no route to host
```

I have managed a partial diagnosis of the problem. It seems that someone thought it would be cute to create a host by the name of "localhost._default full domain_".

Thus, when the apiserver creates a LoopbackClient targeting `https://localhost:6443/api/v1/services`, that is actually resulting in a DNS lookup of the FQDN "localhost._domain_", which resolves to a normal IP and not 127.0.0.1. This causes the client to fail with the error above.

**What you expected to happen**:
I would expect that either

a) The LoopbackClient functionality would generate an absolute hostname, like `https://localhost.:6443/` so that the default domain is not added before a lookup happens, or

b) `localhost` would not be queried via DNS at all in the first place.

**How to reproduce it (as minimally and precisely as possible)**:
I believe it can be reproduced by creating a DNS A record for "loopback" within the same domain as the default for your Kubernetes master node.

**Anything else we need to know?**:
I haven't yet found a root cause for why this lookup happens via DNS using automatically-extended FQDN rather than from /etc/hosts using the hostname as given. It's possible Kubernetes is not the root cause. However, using localhost directly on the system or within an independent Docker container does not show this behavior. I have not yet seen this behavior from anything outside of apiserver when localhost is used.

**Environment**:
- Kubernetes version (use `kubectl version`):
[kriraney@lannnsvc01 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:14:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
VMWare

- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

- Kernel (e.g. `uname -a`):
Linux xxxx 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
Weave

- Others:

**Comment by vllry** [comment]
I thiiink this is a sig-node issue?

/sig node

**Comment by mattjmcnaughton** [comment]
Hi @kraney !

Thanks for the detailed issue report!

A couple of questions to gather some more information:

1. From the `kubectl version` output in your error report, it looks like you're using `v1.11.12` on the server. But your post states you've upgrade to `1.12.8`. Do you mind just confirming that you actually are using `1.12.8`? If not, I think upgrading to `1.12.8` is a good first step, as `1.11` is no longer supported.
2. Can you share more about what you mean by ` It seems that someone thought it would be cute to create a host by the name of "localhost.default full domain".`? How did you discover the existence of this host?

Also, @vllry for my own understanding, could you share a little more about what causes this issue to belong to sig-node? It seems like the code paths discussed are part of the apiserver (which is fairly detached from sig-node in my understanding). _super_ possible I'm missing something though :)

**Comment by kraney** [comment]
> 1. From the `kubectl version` output in your error report, it looks like you're using `v1.11.12` on the server. But your post states you've upgrade to `1.12.8`. Do you mind just confirming that you actually are using `1.12.8`? If not, I think upgrading to `1.12.8` is a good first step, as `1.11` is no longer supported.

I may have not gotten to 1.12.8 properly at the time of the report; this bug appeared during the process of updating to 1.12.8 using kubeadm. Kubeadm reported the upgrade as successful, which is why I state 1.12.8. However, it seems as though this failure in apiserver was preventing the upgrade from truly finalizing.

I was able to workaround the issue by changing my default domain to one that didn't have a "localhost" in it. Since then, I proceeded to upgrade all the way to 1.14.1.


> 2. Can you share more about what you mean by ` It seems that someone thought it would be cute to create a host by the name of "localhost.default full domain".`? How did you discover the existence of this host?

What I mean is, either by editing DNS directly, or by booting a host named "localhost" via DHCP with it set to update DNS, someone created a DNS A record by the name of "localhost". Similar to "localhost.example.com", only with our real domain name. I'm not sure how the record came about, only that I found it when I went looking for it. I suspect it's the DHCP thing; someone set up a host, couldn't think of a hostname, and used "localhost", not realizing that it would get pushed into DNS. (But that's just speculation.)

I discovered this situation by tracking down the IP address reported in the error. It's a local address on our network. I scanned the host and recognized it as a real system at that IP. Then on a hunch I did an nslookup of "localhost", and voila I got back the problem IP as the response. This made the error message suddenly make sense, since it first mentions "https://localhost" and then complains about a surprising IP address.

Having "localhost" as a DNS record is probably not a normal situation, but on the other hand there's nothing that prevents it so it would be more robust to protect against it. Otherwise it might represent a sneaky way for someone to jump in the middle of comms they shouldn't be seeing.

**Comment by zq-david-wang** [comment]
"localhost" should be resolved by /etc/hosts and no DNS server query should be involved, unless you configured your system to make dns server query first. 
What's the content of /etc/hosts and /etc/nsswitch.conf, if any, used by your apiserver?

**Comment by kraney** [comment]
I know it *should* be, but for some reason it isn't. It does not seem to be related to actual config of the system, as mentioned "ping localhost" directly on the host and even as an exec within the apiserver container resolves localhost correctly. Only within the apiserver process it's behaving this way.

/etc/hosts looks like:
```
127.0.0.1		localhost localhost.localdomain localhost4 localhost4.localdomain4
127.0.0.1 		 localhost.default.domain.com
10.24.66.12		host01.default.domain.com host01
10.24.66.13		host02 host02.default.domain.com
```

As you can see, I added an entry (after the problem showed itself, while trying to diagnose it) giving the FQDN that is being resolved through DNS. This did not prevent the issue, for some reason apiserver is going to DNS first.

/etc/nsswitch.conf looks like:
```
passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by lavalamp** [comment]
@vllry @mattjmcnaughton This is api machinery, since it's only kube-apiserver with the issue.

/remove-sig node

**Comment by lavalamp** [comment]
Actually--is it just kube-apiserver or everything that uses client-go? Does your controller-manager happen to be connecting over localhost?

**Comment by lavalamp** [comment]
One theory is that it's related to the pure-go DNS resolver: https://golang.org/pkg/net/#hdr-Name_Resolution; there's an env var to toggle it.

**Comment by zq-david-wang** [comment]
@kraney Can you  clarify whether /etc/hosts and /etc/nsswitch.conf given above is used by your apiserver or just by your host? I assume your apiserver is running inside a container. But I am not sure.  If that is the case, you should check the file inside the container . If there is no nsswitch.conf inside the container, then what @lavalamp mentioned could be possible,  the binary did not check /etc/hosts. 
https://github.com/golang/go/issues/22846 Someone mentioned the issue when updating to 1.12

**Comment by kraney** [comment]
Apiserver is the only process where I've noticed this behavior. It's possible it occurred elsewhere and escaped my attention, if it was the sort of failure that would automatically recover. I think broadly speaking, the processes are not configured to talk over localhost however, this is a multi-node cluster. Apiserver is only using localhost because it's using the LoopbackClientConfig in this particular spot.

The pure-go DNS resolver seems like a very plausible possibility, since I'm not seeing this behavior more broadly.

I don't suppose apiserver does a chroot or a drop privileges, where it might somehow lose visibility of /etc/hosts?

Apiserver is running in a container, and the files I quoted are from inside that container.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/69195

**Comment by kraney** [comment]
@lavalamp I believe you have pinpointed it.

Looking in https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go, the function `nameList` will put the unadorned name last in the search order unless it has >= ndots in it. The default for ndots is 1, so "localhost" would not have enough and would end up at the last of the list.

Looks to me like a bug in go and k8s is an innocent victim.

I reported it over at the golang repo: https://github.com/golang/go/issues/32017

**Comment by kraney** [comment]
It seems from discussion on the ticket with go, that this may not be the problem. Apparently even glibc looks up the FQDN for localhost first when it goes to DNS.

Comparing the observed behavior with the expected, the real issue is that apiserver seems to be going to DNS first despite the fact that /etc/nsswitch.conf is configured for "files dns". I'll continue looking for a simple repro case or a smoking gun in the code.

**Comment by kraney** [comment]
Actually, I am not seeing this behavior in version 1.14.1
