### ISSUE TITLE
Support for MPTCP, Multipath in TCP protocol

### ISSUE THREAD

**Issue by fivefingers1** [kubernetes/kubernetes#77771]
IETF is working on a draft version for TCP which is an extension for Multipath Operation with Multiple Addresses "draft-ietf-mptcp-rfc6824bis-15"

Reference  
https://tools.ietf.org/html/draft-ietf-mptcp-rfc6824bis-15

Currently, I am aware that Kubernetes does not support multi-homing and list it as non-goal item.

Reference 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0015-20180614-SCTP-support.md

The question is if this draft version is approved are there any plans to support the same.
As I understand this will be encountering the same issues related to SCTP Multi-homing support.

**Comment by aojea** [comment]
I think that the important thing here is that it has to be supported in the Kernel and then in all the distros so it can be usable by kubernetes and AFAIK the one only implementation I'm aware of is still out of the kernel tree https://github.com/multipath-tcp/mptcp

Ref: https://tools.ietf.org/html/draft-ietf-mptcp-experience-07
