### ISSUE TITLE
Checksums/signatures for add-ons

### ISSUE THREAD

**Issue by nightwatchcyber** [kubernetes/kubernetes#77789]
**What would you like to be added**:
Some sort of digital signatures or checksums for add-ons to prevent malicious ones, similar to the way packaging works on Debian, etc.

**Why is this needed**:
To prevent packages being modified with malicious code

**Comment by neolit123** [comment]
technically if you are applying an addon from a manifest using kubectl, you can have the checksum validation on the manifest itself. so it's already possibly as a step on the operator side.

could you provide more details on what do you have in mind - i.e. implementation details about this feature?

/triage needs-information
/sig auth

**Comment by nightwatchcyber** [comment]
I am talking to a case where you doing are apply from URL, like here:
https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#install

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

I am not seeing a checksum in there

**Comment by mikedanese** [comment]
We recommend that you pull images by hashes if you care about this. Kubernetes also supports runtime enforcement:

https://kubernetes.io/blog/2017/11/securing-software-supply-chain-grafeas/

**Comment by nightwatchcyber** [comment]
I read through the post - it discusses checksums on the container images themselves. The YAML file has no checksum, so if a user does apply from URL, there is no protection and the attacker can modify the YAML file and force users to a container of their choice.

It also appears that many add-ons both recommend doing apply URL, and do not use the checksum approach.
