### ISSUE TITLE
Audit bash scripts for obvious silent failure ("or true") bugs 

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#7778]
#7650 refers

I think I can remember three of these sorts of '|| true' bugs recently. Is it perhaps worth doing an audit of our code base for them. Superficially there are a lot of instances of this:

$ find kubernetes -name "*.sh" | xargs grep '||\strue' | wc -l
122

**Comment by roberthbailey** [comment]
The recent bugs were where we were missing the `|| true` part on a command that would occasionally exit with a non-zero status. The common one I found was if you grep and it returns no results it won't have a zero exit status but we typically are checking the output against expected output anyway and don't want bash to abruptly exit. There are probably other commands that behave similarly, but starting with fixing all of the greps would be great.
