### ISSUE TITLE
PodSecurityContext RunAsNonRoot API description does not reflect implementation

### ISSUE THREAD

**Issue by praseodym** [kubernetes/kubernetes#77787]
The `PodSecurityContext` type has a field called `RunAsNonRoot` to indicate that a container must run as non-root user. The description for this field includes the sentence `If unset or false, no such validation will be performed.`, which would mean that setting the field to `false` or to `nil` (unset) have the same effect:

https://github.com/kubernetes/kubernetes/blob/04f59751ecc4206c8b078d3a29e303617d90a978/pkg/apis/core/types.go#L2759-L2767

However, the PodSecurityPolicy provider implementation handles the `nil` (unset) case differently, and thus does differentiate between unset or `false` values:

https://github.com/kubernetes/kubernetes/blob/ace60e8acb2c62e006884a654936d7e30a67824b/pkg/security/podsecuritypolicy/provider.go#L167-L173

The API type documentation should be updated to clarify this behaviour and reflect the actual PodSecurityPolicy implementation.

/sig node

**Comment by mattjmcnaughton** [comment]
Thanks for reporting this issue. 

I think that @kubernetes/sig-auth-bugs would be best able to assist with this.

/sig auth
/remove-sig node

**Comment by liggitt** [comment]
The pod documentation is correct. If the field is not set or is false, the enforcement is not performed by the kubelet. 

However, podsecuritypolicy with a runasuser strategy of mustrunasnonroot will force a pod that has not specified a runAsNonRoot setting or a runAsUser uid to runAsNonRoot: true

The documentation on the MustRunAsNonRoot strategy of podsecuritypolicy should clarify the mutation behavior of the PSP

/remove-kind bug
/kind documentation

**Comment by josiahbjorgaard** [comment]
Can I take this issue?

**Comment by neolit123** [comment]
@josiahbjorgaard 

> The documentation on the MustRunAsNonRoot strategy of podsecuritypolicy should clarify the mutation behavior of the PSP

^ this is something that can be changed.

**Comment by josiahbjorgaard** [comment]
@neolit123 @liggitt  Here's a proposed change to the documentation in [content/en/docs/concepts/policy/pod-security-policy.md](https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/policy/pod-security-policy.md):

```diff
  ### Users and groups
  **RunAsUser** - Controls which user ID the containers are run with.
  - *MustRunAs* - Requires at least one `range` to be specified. Uses the
  minimum value of the first range as the default. Validates against all ranges.
  - *MustRunAsNonRoot* - Requires that the pod be submitted with a non-zero
  `runAsUser` or have the `USER` directive defined (using a numeric UID) in the image.
+  Pods which have not specified a `runAsNonRoot` setting nor a `runAsUser` setting
+  will be mutated to set `runAsNonRoot` is true, thus requiring a defined `USER` directive. 
  No default provided. Setting `allowPrivilegeEscalation=false` is strongly 
  recommended with this strategy.
```

Is this sufficient to solve this issue? If so, should I submit a PR there?

**Comment by praseodym** [comment]
I'd change that to
> requiring a defined non-zero numeric `USER` directive in the container image.
to be a little more complete.

**Comment by josiahbjorgaard** [comment]
/assign
See PR for docs at https://github.com/kubernetes/website/pull/14820

**Comment by willthames** [comment]
This would have saved me some battling today! I couldn't work out why my pod wasn't selecting my run-as-root pod security policy and ignoring my restricted pod security policy - I didn't realise I had to explicitly set `runAsUser: 0` to get the correct PSP to match (I thought the restrictive PSP would reject the pod and then the run-as-root PSP would match, not that the restrictive PSP would mutate the PodSpec)
