### ISSUE TITLE
KUBE_SERVER_PLATFORMS[@]: unbound variable building images on CircleCI

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#77799]
**What happened**:

kubernetes images fail to build on CircleCI with the following error
```
circleci@default-a7f00417-d525-463d-96a5-779752c9ae63:~/go/src/k8s.io/kubernetes$ make quick-release-images
+ make quick-release-images
/home/circleci/go/src/k8s.io/kubernetes/hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variable
make: *** [quick-release-images] Error 1
```

**What you expected to happen**:

Being able to build kubernetes images on CircleCI

**How to reproduce it (as minimally and precisely as possible)**:

I have a [kubernetes fork](https://github.com/aojea/kubernetes/tree/circleci_master) with the circleCI configuration, also you can access [the job logs ](https://circleci.com/gh/aojea/kubernetes/50).

**Anything else we need to know?**:

I was narrowing down the problem to this specific commit https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b

Using that commit it fails
```
circleci@default-a7f00417-d525-463d-96a5-779752c9ae63:~/go/src/k8s.io/kubernetes$ git checkout dcee810a3f544cd0669c252945b29bfeedcd119b
+ git checkout dcee810a3f544cd0669c252945b29bfeedcd119b
Previous HEAD position was 06bc7e3e00... Merge pull request #76792 from dekkagaijin/insecure-port
HEAD is now at dcee810a3f... Restrict builds to officially supported platforms
circleci@default-a7f00417-d525-463d-96a5-779752c9ae63:~/go/src/k8s.io/kubernetes$ make quick-release-images
+ make quick-release-images
/home/circleci/go/src/k8s.io/kubernetes/hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variable
make: *** [quick-release-images] Error 1

```

and the previous commit doesn't 

```
circleci@default-a7f00417-d525-463d-96a5-779752c9ae63:~/go/src/k8s.io/kubernetes$ make quick-release-images
+ make quick-release-images
+++ [0513 08:25:56] Verifying Prerequisites....
+++ [0513 08:25:56] Building Docker image kube-build:build-b9d3b75eb3-5-v1.12.4-1
....
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment]
@mtaufen @thockin I'm pinging you because I know that you are doing some bash script cleaning.
I tried to understand what's the problem and fixing it but my bash skills are getting a bit rusty

**Comment by adisky** [comment]
@aojea Most Probably it is same as #77521, we are also facing CI failure due to recent merge.

**Comment by aojea** [comment]
indeed @adisky , thanks 
closing as duplicate
