### ISSUE TITLE
#1126965275330088960 of ci-kubernetes-e2e-gce-scale-performance has failed

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#77808]
The attempt https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1126965275330088960 has failed. I will write here when I find something.

/kind bug
/assign
/sig scalability

/cc @wojtek-t @mm4tt @krzysied

**Comment by mborsz** [comment]
Right before first restart of kube-apiserver I see in logs a series of POST replicationcontrollers:

```
I0511 01:46:25.813633       1 wrap.go:47] POST /api/v1/namespaces/test-pv8z4w-18/replicationcontrollers: (26.734612376s) 500
goroutine 537254266 [running]:
(...)
logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Internal error occurred: resource quota evaluates timeout\",\"reason\":\"InternalError\",\"details\":{\"causes\":[{\"message\":\"resource quota evaluates timeout\"}]},\"code\":500}\n"
 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.202.98.2:44068]
```

All of them fails with "resource quota evaluates timeout"

**Comment by wojtek-t** [comment]
@yliaog @jpbetz

**Comment by mborsz** [comment]
It's still not clear to me if 'resource quota evaluates timeout' is an effect of the problem or the cause of the problem.

I see that between 1:46 and 2:48 UTC we had tons of 429 responses.
![G3MX5fsD51V](https://user-images.githubusercontent.com/2559168/57627875-27d18780-7599-11e9-8d28-24e8a169a8ce.png)

**Comment by mborsz** [comment]
"resource quotas evaluates timeout" is a red herring here:

```
I0511 01:46:22.115914       1 wrap.go:47] POST /api/v1/namespaces/test-pv8z4w-18/replicationcontrollers: (5.739062711s) 500
goroutine 537309094 [running]:
(...)
logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Get https://[::1]:443/api/v1/namespaces/test-pv8z4w-18/resourcequotas: dial tcp [::1]:443: connect: connection refused\",\"code\":500}\n"
 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.202.98.2:44094]
```

so IIUC resource quota evaluator tries to fetch all resourcequotas in given namespace in order to validate whether they are matched. In case when kube-apiserver is ~unhealthy it's not able to list resourcequotas object in a timely manner and returns error.

**Comment by wojtek-t** [comment]
It should list the from internal cache, I think...

**Comment by krzysied** [comment]
I've observed the same issue in my manual gce 5000 density test run. At some point the controller manager and scheduler are losing leader election, causing them to restart. Then controller manger and scheduler (and other components)  spam apiserever with calls (initialization) causing 429s to show. As usual the log timestamps become messed up.
The apiserver didn't restart though.

**Comment by yliaog** [comment]
IIUC, 'resource quota evaluates timeout' is the result of api server being unhealthy (overloaded).

**Comment by wojtek-t** [comment]
> I've observed the same issue in my manual gce 5000 density test run. At some point the controller manager and scheduler are losing leader election, causing them to restart. Then

@krzysied  - that is a consequence not a root cause. We're looking for root cause.

> IIUC, 'resource quota evaluates timeout' is the result of api server being unhealthy (overloaded).

@yliaog - where is this timeout coming from? IIRC we're listing from local cache, and we are not creating any resource quotas at all in the cluster, so what may cause that?

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/blob/3d12466c0221549ffd0651668e078b53482bcad2/plugin/pkg/admission/resourcequota/controller.go#L621

it looks that evaluator cannot finish in time (10s)

**Comment by wojtek-t** [comment]
Hmm - I looked into the code.
This is what terrifies me a little bit:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/resource_access.go#L123

I think that this logic doesn't make sense (i.e. I don't really see a good reason for handling the case of "no quotas in the lister" differently from "some quotas in the lister" wrt detecting freshness of data - if there are some items in the cache they may also be terribly old in theory - the only use case is not-yet-initiallized cache, but that should be handled differently).
@liggitt - for thoughts

That said, I don't think that may be the reason of failure, because nothing has changed there in the last 2 months... So it more looks like a consequence, rather than cause to me.

**Comment by wojtek-t** [comment]
For this run - this is what was most probably the main issue:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCount&Resource=pods&Scope=cluster&Subresource=&Verb=LIST

We had 3 orders of magnitude more LIST pods calls. Where those were coming from?

**Comment by liggitt** [comment]
> I think that this logic doesn't make sense (i.e. I don't really see a good reason for handling the case of "no quotas in the lister" differently from "some quotas in the lister" wrt detecting freshness of data - if there are some items in the cache they may also be terribly old in theory - the only use case is not-yet-initiallized cache, but that should be handled differently).
@liggitt - for thoughts

a scenario where that code would have an impact is in a new namespace being initialized, where something auto-populates the new namespace with quota, then grants permissions to a namespaced user. not sure if that's what @deads2k added that to handle, or if he had something else in mind.

> That said, I don't think that may be the reason of failure, because nothing has changed there in the last 2 months... So it more looks like a consequence, rather than cause to me.

Yeah, that code has been present for 3 years, so I wouldn't expect that to be a cause.

**Comment by mborsz** [comment]
> For this run - this is what was most probably the main issue:
> http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCount&Resource=pods&Scope=cluster&Subresource=&Verb=LIST
> 
> We had 3 orders of magnitude more LIST pods calls. Where those were coming from?

I saw that already -- my interpretation was that they were generated by node-controller because nodes became NotReady, but I will take a closer look if this is a really the case.

**Comment by mborsz** [comment]
> > For this run - this is what was most probably the main issue:
> > http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCount&Resource=pods&Scope=cluster&Subresource=&Verb=LIST
> > We had 3 orders of magnitude more LIST pods calls. Where those were coming from?
> 
> I saw that already -- my interpretation was that they were generated by node-controller because nodes became NotReady, but I will take a closer look if this is a really the case.

kube-controller-manager is restarting every few minutes starting from 01:46:23 to 03:11:34 and then approximately once an hour.

**Comment by wojtek-t** [comment]
This has been fixed in the meantime. Closing.
