### ISSUE TITLE
Documentation needed to describe possible Event.Reason for project

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#7781]
I counted ~30 different events being thrown in the project from various components.

I think to benefit future code reviews, we should standardize on a common set of reasons, or at minimum, author a document that has a table of events, reasons, and why they are thrown in the system.

As a user of the system that wants to potentially write automation against the presence of certain events, it would be good to have a document to reference.

**Comment by mbforbes** [comment]
This is a great point. I have no idea whether this is "cluster" team, but putting there for now.

**Comment by vishh** [comment]
I will take up this issue.

**Comment by erictune** [comment]
We intentionally don't want to enumerate all possible reasons. We want
client code to handle new reasons and to actuate on levels not reasons/
edges

**Comment by vishh** [comment]
Closing as per https://github.com/kubernetes/kubernetes/issues/7781#issuecomment-99264457
