### ISSUE TITLE
exit with 137 code, and not limit resource

### ISSUE THREAD

**Issue by ajax-2** [kubernetes/kubernetes#77849]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
thanks for logging the issue. please re-open it once you provide more details about the tools and the OS you are using.

/close
