### ISSUE TITLE
All Pods on an unreachable node are marked NotReady upon the node turned Unknown 

### ISSUE THREAD

**Issue by chaudyg** [kubernetes/kubernetes#77864]
**What happened**:
We reached a corner case in our kubernetes cluster:
1. a network partition between kubelet and the apiserver. ALL our nodes unable to report to the apiserver (misconfiguration of the loadbalancer between kubelet and the apiserver).
2. As expected, after 40 seconds, all the nodes status turn to Unknown.
3. However, at the same time, all the pods on all the nodes were marked NotReady. Endpoints available dropped to zero for every service running in the cluster. 100% traffic suddenly failed at our ingress. 100% of DNS queries failed inside the cluster.
4. As expected, after 5 minutes, some of the pods started being evicted. However eviction stopped because this was a full cluster outage.

**What you expected to happen**:

One of the following two options:
1. Pods readiness should NOT be marked as NotReady when the Node condition turns Unknown. Pod should be marked unready only when they are actually being evicted from the cluster.

The documentation mentions the following corner case.
> The corner case is when all zones are completely unhealthy (i.e. there are no healthy nodes in the cluster). In such case, the node controller assumes that there’s some problem with master connectivity and stops all evictions until some connectivity is restored.
https://kubernetes.io/docs/concepts/architecture/nodes/

2. OR, the documentation should be updated to explain this behaviour.

**How to reproduce it (as minimally and precisely as possible)**:
* Stop kubelet on one of the node
* Wait 40 seconds
* Watch all the pods running on that node being marked an NotReady (and removed from the service endpoints)

**Anything else we need to know?**:
* Line of code: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L764-L769
* End2End test: https://github.com/kubernetes/kubernetes/blob/ee0038adaa9a316a26e435353f629ea4af4b46f1/test/e2e/apps/network_partition.go#L137

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11,1.12,1.13,1.14
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): NA
- Kernel (e.g. `uname -a`): NA
- Install tools: NA
- Network plugin and version (if this is a network-related bug): NA
- Others:

**Comment by chaudyg** [comment]
@kubernetes/sig-node-bugs
@kubernetes/sig-cluster-lifecycle

**Comment by mattjmcnaughton** [comment]
Thanks for your detailed error report @chaudyg :)

My guess is that, given the integration test, it is intentional that pods become `NotReady` when the node is marked `NotReady`.

I'm wondering, would that behavior have been acceptable if the documentation had been clearer? How could we update the documentation so there were less surprises?

**Comment by chaudyg** [comment]
Thx @mattjmcnaughton for your reply.

Is seems like an intentional behaviour. But I am failing to grasp the full rational behind it.

What I am convinced of is that having the apiserver unreachable for 40+ seconds should NOT result in a full cluster outage. 

They are 2 scenarios in this part of the code:
* The node turns NotReady. In this case I can understand why marking pods as NotReady quickly make sense. You know the underlying node in unhealthy, and we can infer pods won't perform as expected. I will recommend we document this behaviour.
* The node turns Unknown. In this case the controller cannot make an informed decision. The overall rational in the controller in an "unknown" scenario seems to be that the controller acts slowly and carefully. If first keeps the status quo by granting a 5m grace period to the node. Then it starts recreation some of the the pods slowly (eviction-rate flag) but only if some nodes are still healthy. If none of the nodes are available, it won't make any decision. I feel like the right approach. Removing all the endpoints feels like a ruched decision. I would recommend we don't mark the pod as NotReady in this use case.

**Comment by hjacobs** [comment]
@chaudyg thanks for looping me in, please submit the full postmortem on https://github.com/hjacobs/kubernetes-failure-stories when ready :clap:

**Comment by mattjmcnaughton** [comment]
> Thx @mattjmcnaughton for your reply.
> 
> Is seems like an intentional behaviour. But I am failing to grasp the full rational behind it.
> 
> What I am convinced of is that having the apiserver unreachable for 40+ seconds should NOT result in a full cluster outage.
> 
> They are 2 scenarios in this part of the code:
> 
> * The node turns NotReady. In this case I can understand why marking pods as NotReady quickly make sense. It knows the underlying node in unhealthy, and assumes the underlying pods won't perform as expected. I will recommend we document this behaviour.
> * The node turns Unknown. In this case the controller cannot make an informed decision. The overall rational in the controller in an "unknown" scenario seems to be that the controller acts slowly and carefully. If first keeps the status quo by granting a 5m grace period to the node. Then it starts recreating some of pods slowly (eviction-rate flag) but only if some nodes are still healthy. If none of the nodes are ready, it won't make any decision. It feels like a sensible approach. Removing all the endpoints feels like a ruched decision. I would recommend we don't mark the pod as NotReady in this case.

Thanks for the clarification @chaudyg :) 

To ensure I'm understanding, the second scenario you describe (i.e. "Unknown node status results in grace period than slow eviction provided other nodes are still healthy") is the way you believe it should work, not the way it actually works correct? From the code, it looks like the way it works is that all Pods are marked `NotReady` if the node is anything except healthy.

I certainly agree that your preferred behavior sounds reasonable in the use case you described. Thinking about other error scenarios or cluster use cases, can we think of any times that it wouldn't be reasonable? Are their controls we could expose to the cluster admin to make this type of behavior more flexible?

Really interested to hear the communities thoughts on this :)

**Comment by chaudyg** [comment]
> To ensure I'm understanding, the second scenario you describe (i.e. "Unknown node status results in grace period than slow eviction provided other nodes are still healthy") is the way you believe it should work, not the way it actually works correct?

Correct. It's the way I believe it should work. It's also what the documentation currently explains. All Pods are marked `NotReady ` is an undocumented feature.

> can we think of any times that it wouldn't be reasonable?
Maybe the following scenario?

Someone trips on the network cable or your node suddenly stops.
*  If you run in the cloud: this is a non problem. The cloud-provider will most likely detect this, and the could-provider-controller will remove the failing node from the kubernetes api. Then, all the pods on that node will marked as `terminating`.
* However, if you run on bare metal: After 40 seconds, the node will be marked as `Unknown`. But then pods running on that node will keep on receiving traffic until the the `--pod-eviction-timeout`  is reached (default to 5m). Then and only then those pods will be added to the eviction queue.

> Really interested to hear the communities thoughts on this :)

@freehan you wrote the code to [update pod status once node becomes NotReady](https://github.com/kubernetes/kubernetes/commit/01829432db07431689cfc0942a15e2dc58bf1fe6) . Would you be willing to share your opinion?

**Comment by derekwaynecarr** [comment]
keep in mind pods still have to follow graceful termination, and if those pods are backed by a workload controller like a stateful set, the pods will not just get created.  at this time, an administrator would have to force delete those pods (as the platform right now is not able to detect that the node is network partitioned or powered on yet, but work is in progress to enable this).

**Comment by chaudyg** [comment]
**Another example**
Just had another flavour of this incident. It lasted 4 minutes but was quite intense. 

- Two apiserver (out of 3) pods got stuck (still investigating the root cause, but it's irrelevant in the current context). 
![image](https://user-images.githubusercontent.com/7817963/59192650-16b96d80-8b7b-11e9-8bd2-2286f4a172ab.png)
- the controller-manager leader was still perfectly healthy.
- All the Kubelet connected to the failing apiservers failed to reports their status.
- After 40 seconds, the controller manager swap the status to those nodes to `UNKNOWN`
![image](https://user-images.githubusercontent.com/7817963/59192556-b9bdb780-8b7a-11e9-95da-e0d08139dd00.png)
- The controller manager also decided to mark all the pods on the affected nodes as `NotReady`. All traffic to those pods stopped.
![image](https://user-images.githubusercontent.com/7817963/59192821-a65f1c00-8b7b-11e9-9f95-5e011a28ce56.png)
- For example, a huge number of core dns pods become unavailable in the cluster
![image](https://user-images.githubusercontent.com/7817963/59192896-d4dcf700-8b7b-11e9-8632-b76bce8a6c27.png)
- Eventually, the failing apiserver pods go automatically restarted. Everything came back to normal.

----
**Followup**
Had a chat with @freehan and @saad-ali  at kubecon about this issue.

- The initial intention behind marking all the pods as `NotReady` was to prevent to prevent sending traffic to pods when a node suddenly crashes without getting removed from the list of nodes. In this scenario, this limits the downtime to 40 seconds  instead of the default 5 minutes (`--pod-eviction-timeout`)
- The drawback is that it makes the cluster very sensitive to connectivity issues between kubelets and the apiserver.
---

**How to progress this issue?**
I think both scenarios mentioned above make sense. Pods should be marked `NotReady` quickly enough to prevent sending traffic to failing node, but slowly enough to prevent a full cluster outage when there is connectivity issues with the apiserver. 

We should consider implementing some sort of `eviction-rate` to prevent marking all the pods `NotReady` too quickly?

I would be interested to get other people's opinion on this one!

**Comment by mattjmcnaughton** [comment]
@chaudyg thanks for the additional info!

I agree with you that we should look at exposing some form of parameter giving the cluster admin control over how quickly the pods are marked `NotReady`. We could set a sensible default (perhaps even what exists now).

Curious to hear from @derekwaynecarr when he gets a second :)

**Comment by chaudyg** [comment]
Any more thoughts? @derekwaynecarr would you have some time to take a look?
