### ISSUE TITLE
137 exit code, but my limit is not set

### ISSUE THREAD

**Issue by ajax-2** [kubernetes/kubernetes#77924]
# error
Hey, All friends, my pod is exit with code 137 when i connect mysql in this pod.

# error message
```
command terminated with non-zero exit code: Error executing in Docker Container: 137
```

# environment
* kubernetes: 1.14.1
* docker: 18.0.9
* mysql: 5.7
* install method: helm

# What
![image](https://user-images.githubusercontent.com/29370146/57617615-ccf95980-75b3-11e9-80eb-f55da4c09427.png)
This is my pod, it's running, enn~ very good!
So i use nextcloud in web, and external mysql is this pod. But pod don't work, and tell me the message!
![image](https://user-images.githubusercontent.com/29370146/57617738-1d70b700-75b4-11e9-8e11-f61599c47c9d.png)

# Hope
I wanna know Why it don't work, And i should do what to solve it. 

# note
In my logic machine, not vm, it work well!
And my pod resource is not set limit!

/sig podexit

**Comment by neolit123** [comment]
/triage support
/remove-kind bug

hi, you might get better responses on slack or stackoverflow.
but also there are already *a lot* of related issues:
https://github.com/kubernetes/kubernetes/search?q=137+exit+code&type=Issues

**Comment by zq-david-wang** [comment]
If your pod restarted,  "describe pod " should have useful information.

**Comment by ajax-2** [comment]
> If your pod restarted, "describe pod " should have useful information.

我看了下，启动后没有任何其他的日志，只显示健康检查失败，然后我把健康检查去掉了，还是出错

**Comment by ajax-2** [comment]
> /triage support
> /remove-kind bug
> 
> hi, you might get better responses on slack or stackoverflow.
> but also there are already _a lot_ of related issues:
> https://github.com/kubernetes/kubernetes/search?q=137+exit+code&type=Issues

Yeah, It's a good idea, Maybe i can get answer in stackoverflow! Thanks
