### ISSUE TITLE
Private StorageClass 

### ISSUE THREAD

**Issue by zhiteng** [kubernetes/kubernetes#77926]
@kubenetes/sig-storage

**What would you like to be added**:
In big enough k8s deployments, there are cases when certain StorageClasses were crafted for some particular use cases.  It's desired to limit to the exposure of such StorageClasses, in other words, making some StorageClasses private (only visible/usable for some users/groups/namespaces).  API to change who has access to StorageClasses is also needed to make this feature practical.

**Why is this needed**:
The fact that in our deployment of K8s, we have multiple storage devices, each might be configured differently in order to provide different classes of service, in terms of performance.  Such type of classes of service are mapped to StorageClasses perfectly.  However, except for certain generic SCes, most of such SCes are crafted for certain use cases, meaning they are not supposed to be consumed by general public.  We can only control the quota of there SCes so that most users won't be able to use them, but they can be seen from list SCes API and our support has constantly receive inquiry like what those SCes are for, and why they cannot use them.  As our service running longer and longer, more and more fine-tuned StorageClasses were added, we started to miss the private volume type API from OpenStack block storage (https://developer.openstack.org/api-ref/block-storage/v3/index.html#volume-types-types, https://developer.openstack.org/api-ref/block-storage/v3/index.html#volume-type-access-volumes).  We wonder if this is common desired feature and would love to see K8s to add support for private StorageClasses.  

Thanks.

**Comment by wenjun93** [comment]
@rootfs @jsafrane @jingxu97

**Comment by jsafrane** [comment]
> making some StorageClasses private (only visible/usable for some users/groups/namespaces)

StorageClasses visible/non-visible to users: use RBAC
StorageClasses usable/non-usable to namespaces: use quota, that works per namespace.

StorageClasses usable/non-usable to users: that's not possible, quota (per namespace) should be used instead.
