### ISSUE TITLE
Kubernetes client does not print any new events after watching

### ISSUE THREAD

**Issue by smartbit** [kubernetes/kubernetes#77929]
When running the following command on a GKE cluster with version 1.12.6-gke.10 we see the last events, but no new events are ever printed after that:

    kubectl get events -w

Even if we forcibly delete a pod in that same namespace, for example, nothing is printed. If we set up a watch client with Go in a pod in the cluster then it doesn't receive any events beyond the initial ones either.

**Comment by Overv** [comment]
Never mind this, we can only reproduce this on a specific cluster.
