### ISSUE TITLE
Flaky SchedulerPredicates e2e tests because of undeleted namespaces

### ISSUE THREAD

**Issue by OlegLoewen** [kubernetes/kubernetes#77928]
**Which test(s) are failing**:

- [sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching  [Conformance]
- [sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching  [Conformance]
- [sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run  [Conformance]

**Details**
I'm still facing this issue which causes flakiness:
```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:79
Expected error:
    <*errors.errorString | 0xc0011b21a0>: {
        s: "Namespace e2e-tests-container-probe-5dp7g is active",
    }
    Namespace e2e-tests-container-probe-5dp7g is active
not to have occurred
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:88
```
system-out output:
```
go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:147
STEP: Creating a kubernetes client
STEP: Building a namespace api object, basename sched-pred
STEP: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in e2e-tests-sched-pred-h67w2
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-scheduling] SchedulerPredicates [Serial]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:78
May 13 09:30:03.176: INFO: Waiting up to 1m0s for all (but 2) nodes to be ready
May 13 09:30:03.184: INFO: Waiting for terminating namespaces to be deleted...
May 13 09:30:03.186: INFO: Unexpected error occurred: Namespace e2e-tests-gc-5vwws is active
[AfterEach] [sig-scheduling] SchedulerPredicates [Serial]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:148
STEP: Collecting events from namespace "e2e-tests-sched-pred-h67w2".
STEP: Found 0 events.
```

I tested this testcases with different cloud providers (gce, aws, alicloud, openstack, azure) and have observed, that this issue is only happening for gce and alicloud clusters and only for k8s release < 1.14.0

**Comment by BenTheElder** [comment]
if it's only happening for older releases, perhaps a fix was added?

I do not own scheduling tests.
/unassign
cc @spiffxp for conformance
@kubernetes/sig-scheduling-misc

**Comment by professor** [comment]
When we were on `v1.13.5` we did not see this flake occur. Since upgrading to `v1.13.10`, we're seeing this flake frequently.
