### ISSUE TITLE
add kubeadm to the releases binary/pakages list

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubernetes#77921]
**What would you like to be added**:

Every k8s release most of the kube* binaries are build and loaded to github relases page. But for some reason, the kubeadm is not part of the list.
Can it be added?
(Alternativelly,  hyperkube build)
As for deb/rpm packages, I guess it's too complicated; for now binary would a good step ahead IMO.

**Why is this needed**:
For non final versions, we there is no reason us to build it manually, when all the other binaries are already build. IMO kubeadm, being part of the same project, should be released like any other artifact of this project.

**Comment by tianyuansun** [comment]
can i help fix this? @justaugustus

**Comment by timothysc** [comment]
+1 from me, but we may move to release kubeadm separately in the future. 
/cc @kubernetes/sig-cluster-lifecycle

**Comment by neolit123** [comment]
@ReSearchITEng 
> Every k8s release most of the kube* binaries are build and loaded to github relases page. But for some reason, the kubeadm is not part of the list.

looking at https://github.com/kubernetes/kubernetes/releases
https://github.com/kubernetes/kubernetes/releases/tag/v1.14.4
i don't see the GitHub releases having binary assets, maybe i'm missing a link?

however following these links, e.g.:
> Additional binary downloads are linked in the CHANGELOG-1.14.md.

leads to the page where one can download `kubernetes-node-OS-ARCH` that contains kubeadm.

**Comment by ReSearchITEng** [comment]
You are right, I did not notice the 3rd section:"node" (I must have checked under "client"). Sorry about that.

Now, that we are at this, would it be very complex to open a package manager repo for alpha&beta (yum/deb), the same way there is one for final releases?

**Comment by neolit123** [comment]
> You are right, I did not notice the 3rd section:"node" (I must have checked under "client"). Sorry about that.

"client" is the only package that is missing kubeadm.

> Now, that we are at this, would it be very complex to open a package manager repo for alpha&beta (yum/deb), the same way there is one for final releases?

this is a WIP by sig-release and the publishing process.
see this KEP (k8s proposal) about having pre-release packages:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190219-publishing-packages.md#user-stories

**Comment by neolit123** [comment]
but given kubeadm is already in the tars, we can close this issue.
/close
