### ISSUE TITLE
[Failing Tests] ClusterLoaderV2  failing in presubmits 

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#77938]
**Which jobs are failing**:
pull-kubernetes-e2e-gce-100-performance

**Which test(s) are failing**:
ClusterLoaderV2 

**Since when has it been failing**:
It has been consistently failing since 6:55 PDT today.

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-100-performance&width=90

**Reason for failure**:
[From spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-100-performance/1128678861077221376) the reason being listed is 
```
error during /go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --nodes=100 --provider=gce --report-dir=/workspace/_artifacts --testconfig=testing/density/config.yaml --testconfig=testing/load/config.yaml --testoverrides=./testing/density/100_nodes/override.yaml: exit status 1
```

Before this happens, this other thing happens:
```
F0515 15:51:08.325125 82020 clusterloader.go:233] Error while setting up prometheus stack: timed out waiting for the condition
```

/kind failing-test
/priority critical-urgent
/milestone v1.15
/cc @kubernetes/sig-scalability-test-failures 
/cc @jimangel @smourapina @rarchk @alenkacz

**Comment by oxddr** [comment]
Fixed in https://github.com/kubernetes/perf-tests/pull/529

/cc @mm4tt 
/close
