### ISSUE TITLE
Namespaces and CRD have inconsistent delete-on-update behavior than other built-in resources.

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#77944]
For most built-in resources, if the object deletion is blocked by finalizers, the Update request that removes the last pending finalizer causes the apiserver to delete the object.

The logic is enforced by the generic storage's `Update()` function, specifically, by the [shouldDeleteDuringUpdate](https://github.com/kubernetes/kubernetes/blob/4d3d153210c0788b8e188c467d31061470d8c042/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L394-L406) function. It checks if finalizers are deleted, and if the metadata.deletionGracefulPeriods was set to 0 (by the first Delete request).

[Namepaces](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/namespace/storage/storage.go#L125) and [CRD](https://github.com/kubernetes/kubernetes/blob/4d3d153210c0788b8e188c467d31061470d8c042/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go#L70)  storage overrides the generics storage's `Delete()` function. They don't set the `deletionGracefulPeriods`, so namespaces and CRDs do not have this delete-on-update behavior.

I can think of two alternative fixes.

1. Relaxing the `shouldDeleteDuringUpdate`
    * Let `shouldDeleteDuringUpdate` return true if (finalizers are removed by the update) && (deletionGracefulSeconds was set to 0 or was nil) && (deletionTimestamp was not nil). 
    * We would also need to override the namespace storage's Update() function, to let it additionally check the `namespace.spec.finalizers` in its `shouldDeleteDuringUpdate`.

2. Only fixing the behavior of CRDs. Let the `Delete()` function of the CRD storage sets CRD's deletionGracefulPeriod to 0 on first Delete. We'll leave namespaces alone, as its behavior has been like that for years.

cc @liggitt 
ref https://github.com/kubernetes/kubernetes/pull/76346#discussion_r284028314
/sig api-machinery

**Comment by liggitt** [comment]
> Let `shouldDeleteDuringUpdate` return true if (finalizers are removed by the update) && (deletionGracefulSeconds was set to 0 or was nil) && (deletionTimestamp was not nil).

That matches my expectations
