### ISSUE TITLE
Options in system resolv.conf ignored

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes/kubernetes#77967]
**What happened**:
Kubelet ignore options in /etc/resolv.conf for pods with default policy

**What you expected to happen**:
Kubelet must merge that options with default and insert in pod /etc/resolv.conf

**How to reproduce it (as minimally and precisely as possible)**:
Set any options in /etc/resolv.conf, restart kubelet/pod options will not be copied 

**Environment**:
- Kubernetes version (use `kubectl version`):
From at least 1.12+

/sig node

**Comment by mattjmcnaughton** [comment]
Thanks for starting discussion about this!

From reading the documentation, I'm wondering if the solution to this is giving your pods `dnsPolicy: Default`? Confusingly, that is not the same as not specifying a `dnsPolicy`... if you don't specify a `dnsPolicy`, k8s defaults to using `ClusterFirst`. `dnsPolicy: Default` will lead to /etc/resolv.conf being respected, while `dnsPolicy: ClusterFirst` (or `dnsPolicy` not specified) will not lead to `/etc/resolv.conf`.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

cc @namreg :)

**Comment by namreg** [comment]
@mattjmcnaughton Could you please clarify `dnsPolicy: ClusterFirst (or dnsPolicy not specified) will not lead to /etc/resolv.conf`? I don't specify `dnsPolicy` for pod, but custom resolv.conf (which given to the kubelet) is applied to pod's container resolv.conf. Also, as I can see in the code, if `dnsPolicy` is `ClusterFirst`, `dnsConfig.Searches` is merged with the custom resolv.conf (https://github.com/kubernetes/kubernetes/blob/732ea8d752fce56776745f0714bea88a2f9a244b/pkg/kubelet/network/dns/dns.go#L366, https://github.com/kubernetes/kubernetes/blob/732ea8d752fce56776745f0714bea88a2f9a244b/pkg/kubelet/network/dns/dns.go#L150)

If it's desired behavior do not have merged custom options, then, I think, we have little bit inconsistency :)

**Comment by mattjmcnaughton** [comment]
> @mattjmcnaughton Could you please clarify `dnsPolicy: ClusterFirst (or dnsPolicy not specified) will not lead to /etc/resolv.conf`? I don't specify `dnsPolicy` for pod, but custom resolv.conf (which given to the kubelet) is applied to pod's container resolv.conf. Also, as I can see in the code, if `dnsPolicy` is `ClusterFirst`, `dnsConfig.Searches` is merged with the custom resolv.conf (
> 
> https://github.com/kubernetes/kubernetes/blob/732ea8d752fce56776745f0714bea88a2f9a244b/pkg/kubelet/network/dns/dns.go#L366
> 
> ,
> https://github.com/kubernetes/kubernetes/blob/732ea8d752fce56776745f0714bea88a2f9a244b/pkg/kubelet/network/dns/dns.go#L150
> 
> )
> If it's desired behavior do not have merged custom options, then, I think, we have little bit inconsistency :)

Thanks for looking at this with me :)

I'm looking at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/dns/dns.go#L324 which seems to show that if the `dnsType` is `podDNSCluster`, then `dnsConfig.Options` will be set to `defaultDNSOptions`. My understanding is that `dnsType` will equal `podDNSCluster` if we do not specify a `dnsPolicy` for the pod.

In other words, I _think_ that the custom `resolv.conf` given to the Kubelet is only applied if `dnsType = podDNSHost`, which happens only if you set `dnsType = default` for your pod.

Very possible I'm wrong though :)
