### ISSUE TITLE
kubectl top pods: Metrics not available for pod

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/kubernetes#77971]
**What happened**:

`kubectl top pods --namespace backstage` outputs error:

```
W0516 16:25:09.356872   11172 top_pod.go:190] Metrics not available for pod backstage/container-name-678f95c84-qnqml, age: 1242h46m15.3568533s
error: Metrics not available for pod backstage/container-name-678f95c84-qnqml, age: 1242h46m15.3568533s
```

**Environment**:
- Kubernetes version : v1.7.6, 
- Cloud provider or hardware configuration: 1.11.8-gke.6

**Comment by neolit123** [comment]
> Kubernetes version : v1.7.6,

try updating to 1.11 at least. this version is no longer supported.

/sig cli
/remove-kind bug
/triage support

**Comment by hudsonrio** [comment]
Had a similar experience with 1.9, also using Google GKE. Simply running `gcloud components update` 
which upgraded me to `v1.12.7` resolved the issue.

**Comment by whitecolor** [comment]
I'm on window 10 WSL it seems it is the latest version available there (
![image](https://user-images.githubusercontent.com/736697/57889750-0a2d4800-784f-11e9-96f7-7a0037dc1627.png)

**Comment by whitecolor** [comment]
Yes updated to 1.14.  thanks)

**Comment by KeyaJohn** [comment]
hi,   my  k8s  version  is  1.13.2,   
Can't you do it?

**Comment by KeyaJohn** [comment]
hi, my k8s version is 1.13.2, no?
