### ISSUE TITLE
verify-symbols.sh is not able to verify symbols

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#77983]
**What happened**:

In recent pull-kubernetes-verify runs, I see:

```
+++ Running case: verify.symbols 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-symbols.sh"
+++ [0516 15:44:46] Building go targets for linux/amd64:
    cmd/hyperkube
nm: /home/prow/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/hyperkube: no symbols
```

**What you expected to happen**:

`verify-symbols.sh` was written to verify certain symbols do not appear in our builds, but it appears our builds (or, at least the hypercube build it uses) don't have symbols in them, so there is nothing for it to verify.

Since the hypercube build done by the script has a cost associated with it, we should only do it if we're going to get some benefit, and without any symbol tables in the binary, we're currently not.

**How to reproduce it (as minimally and precisely as possible)**:

`hack/verify-symbols.sh`

cc @sttts @thockin 

/sig testing

**Comment by liggitt** [comment]
fixed in #78018

/close
