### ISSUE TITLE
Pod Pending due to unbound persistent volume claims

### ISSUE THREAD

**Issue by cclark1974** [kubernetes/kubernetes#77993]
kubectl describe pods cdi-upload-flex-vnf-volume-claim
Name:               cdi-upload-flex-vnf-volume-claim
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=containerized-data-importer
                    cdi.kubevirt.io=cdi-upload-server
                    service=cdi-upload-flex-vnf-volume-claim
Annotations:        cdi.kubevirt.io/storage.createdByUploadController: yes
Status:             Pending
IP:                 
Controlled By:      PersistentVolumeClaim/flex-vnf-volume-claim
Containers:
  cdi-upload-server:
    Image:      kubevirt/cdi-uploadserver:v1.8.0
    Port:       <none>
    Host Port:  <none>
    Args:
      -v=1
    Readiness:  http-get http://:8080/healthz delay=2s timeout=1s period=5s #success=1 #failure=3
    Environment:
      TLS_KEY:            <set to the key 'tls.key' in secret 'cdi-upload-flex-vnf-volume-claim-server-tls'>  Optional: false
      TLS_CERT:           <set to the key 'tls.crt' in secret 'cdi-upload-flex-vnf-volume-claim-server-tls'>  Optional: false
      CLIENT_CERT:        <set to the key 'ca.crt' in secret 'cdi-upload-flex-vnf-volume-claim-server-tls'>   Optional: false
      UPLOAD_IMAGE_SIZE:  100Gi
    Mounts:
      /data from cdi-data-vol (rw)
      /scratch from cdi-scratch-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lb9gv (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  cdi-data-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  flex-vnf-volume-claim
    ReadOnly:   false
  cdi-scratch-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  flex-vnf-volume-claim-scratch
    ReadOnly:   false
  default-token-lb9gv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lb9gv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  4m16s (x87 over 129m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)

kubectl get pv
NAME                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                           STORAGECLASS   REASON   AGE
flex-vnf-volume           100Gi      RWX            Retain           Bound       default/flex-vnf-volume-claim   manual                  6h22m
flex-vnf-volume-scratch   100Gi      RWX            Retain           Available                                   manual                  165m

kubectl get pvc
NAME                            STATUS    VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
flex-vnf-volume-claim           Bound     flex-vnf-volume   100Gi      RWX            manual         6h17m
flex-vnf-volume-claim-scratch   Pending                                               manual         139m

kubectl describe pvc flex-vnf-volume-claim-scratch
Name:          flex-vnf-volume-claim-scratch
Namespace:     default
StorageClass:  manual
Status:        Pending
Volume:        
Labels:        app=containerized-data-importer
               cdi-controller=cdi-upload-flex-vnf-volume-claim
               cdi.kubevirt.io/storage.import.importPvcName=flex-vnf-volume-claim
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason              Age                    From                         Message
  ----       ------              ----                   ----                         -------
  Warning    ProvisioningFailed  3m34s (x68 over 139m)  persistentvolume-controller  storageclass.storage.k8s.io "manual" not found
Mounted By:  cdi-upload-flex-vnf-volume-claim

Previous PVC bound fine:
kubectl describe pvc flex-vnf-volume-claim
Name:          flex-vnf-volume-claim
Namespace:     default
StorageClass:  manual
Status:        Bound
Volume:        flex-vnf-volume
Labels:        <none>
Annotations:   cdi.kubevirt.io/storage.pod.phase: Pending
               cdi.kubevirt.io/storage.upload.target: 
               kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"flex-vnf-volume-claim","namespace":"default"},"spec...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Events:        <none>
Mounted By:    cdi-upload-flex-vnf-volume-claim

What is missing?

**Comment by cclark1974** [comment]
8s-master ~]$ kubectl apply -f /home/dell/flex-volume.yaml
persistentvolume/flex-vnf-volume created
k8s-master ~]$ kubectl apply -f /home/dell/flex-volume-scratch.yaml
persistentvolume/flex-vnf-volume-scratch created
k8s-master ~]$ kubectl get pv
NAME                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
flex-vnf-volume           100Gi      RWX            Retain           Available           manual                  9s
flex-vnf-volume-scratch   100Gi      RWX            Retain           Available           manual                  4s



k8s-master ~]$ kubectl apply -f /home/dell/flex-claim.yaml
persistentvolumeclaim/flex-vnf-volume-claim created
k8s-master ~]$ kubectl get pvc
NAME                    STATUS   VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
flex-vnf-volume-claim   Bound    flex-vnf-volume   100Gi      RWX            manual         3s
k8s-master ~]$ kubectl apply -f /home/dell/flex-claim-scratch.yaml
persistentvolumeclaim/flex-vnf-volume-claim-scratch created
k8s-master ~]$ kubectl get pvc
NAME                            STATUS    VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
flex-vnf-volume-claim           Bound     flex-vnf-volume   100Gi      RWX            manual         19s
flex-vnf-volume-claim-scratch   Pending                                               manual         2s

k8s-master ~]$ kubectl describe pvc flex-vnf-volume-claim-scratch
Name:          flex-vnf-volume-claim-scratch
Namespace:     default
StorageClass:  manual
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"flex-vnf-volume-claim-scratch","namespace":"default...
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason              Age               From                         Message
  ----       ------              ----              ----                         -------
  Warning    ProvisioningFailed  5s (x2 over 20s)  persistentvolume-controller  storageclass.storage.k8s.io "manual" not found
Mounted By:  <none>



Is there a limitation on NFS mounted volumes even if they are different mount points?
/PVS-volume-scratch type nfs4
/PVC-vol type nfs4

**Comment by tedyu** [comment]
storageclass.storage.k8s.io "manual" not found
