### ISSUE TITLE
Add PreFilter extension point of the scheduling framework

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#77998]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and a few extension points, such as "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.

[PreFilter](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-filter) plugins are used to pre-process info about the pod, or to check certain conditions that the cluster or the pod must meet. If a pre-filter plugin returns an error, the scheduling cycle is aborted.
These PreFilter plugins can perform operations such as building "Prediate Metadata" or performing basic checks on pods.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by ahg-g** [comment]
I will take on this one :)

**Comment by bsalamat** [comment]
@ahg-g Since you are not a member of the K8s community, we cannot officially assign the issue to you, but we consider it taken by you. Please send a PR when you can. There is no rush. This can be added in 1.16.
