### ISSUE TITLE
Add PostFilter extension point of the scheduling framework

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#78004]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and a few extension points, such as "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.

[PostFilter](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#post-filter) is an informational extension point. Plugins will be called with a list of nodes that passed the filtering phase. A plugin may use this data to update internal state or to generate logs/metrics.

This is needed for 1.16. A PR can be sent after 1.15 code freeze.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by tedyu** [comment]
Looking at Scheduler#scheduleOne and framework, I don't see filtering.

Should I look at some other class ?

Thanks

**Comment by bsalamat** [comment]
`ScheduleOne` eventually calls `genericScheduler` functions for filtering and scoring nodes. PostFilter plugins must be invoked by `genericScheduler`. Ideally, we should get rid of `genericScheduler` and replace it with the `Framework`, but that's a bigger refactoring which we will do later, after the Framework is built.

**Comment by draveness** [comment]
/assign

I could do the work after the Scheduling Framework is built.
