### ISSUE TITLE
Add Filter extension point of the scheduling framework

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#78001]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and a few extension points, such as "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.

[Filter](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#filter) plugins are used to filter out nodes that cannot run the Pod. For each node, the scheduler will call filter plugins in their configured order. If any filter plugin marks the node as infeasible, the remaining plugins will not be called for that node. Nodes may be evaluated concurrently.

Filter plugin interface should be designed so that all existing predicates functions can be converted to filter plugins.
**Please send your proposal for the interface of this extension point before sending a full PR and let us discuss and approve it first.**

This is needed for 1.16. A PR can be sent after 1.15 code freeze.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by YoubingLi** [comment]
I will work on it

**Comment by bsalamat** [comment]
@YoubingLi Thanks. I consider this assigned you.

**Comment by YoubingLi** [comment]
Following are my understanding about the current implementation

1. predicateMetadataProducer

    At the beginning, the producer would run preparation for current pod on each candidate host such as (anti-)affinity, pod resource request, port, etc.

2. FitPredicate

     Each built-in predicate uses following interface to evaluate each candidate host.
    meta is the result of Step 1 and each predicate uses it on-demand.

     func(pod *v1.Pod, 
              meta PredicateMetadata,
              nodeInfo *schedulernodeinfo.NodeInfo) (bool, []PredicateFailureReason, error)

3. Scheduler Extender
    
     Following interface is used to evaluate each candidate host for current pod.
 
     Filter(pod *v1.Pod,
              nodes []*v1.Node, 
             nodeNameToInfo map[string]*schedulernodeinfo.NodeInfo)
         (filteredNodes []*v1.Node, failedNodesMap schedulerapi.FailedNodesMap, err error)

**My proposal about Filter extension point is**

1. predicateMetadataProducer

    Don't use it any more. 
    I mean we can decouple his functionalities and let each plugin to handle it.
    Currently, just part of built-in predicates use it 

2. Plugin Interface

    type FilterPlugin interface {
	   Plugin
	   Filter(pc *PluginContext,
                    pod *v1.Pod,
                    nodeInfo *schedulernodeinfo.NodeInfo) *Status
    }

 3. Framework Interface

     // Record failure status for each non-candidate host 
     type FilterFailedMap map[string]*Status

     RunFilterPlugins(pc *PluginContext, pod *v1.Pod, []*v1.Node) ([] * v1.Node, FilterFailedMap, error)

**Question:**

   After the Filter extension is implemented, should we still keep current logic?

   I mean **findNodesThatFit** can be reused, but we should move them into pkg/scheduler/framework/v1alpha1 or use another way to re-use it.    

/cc @YoubingLi @bsalamat @Huang-Wei
