### ISSUE TITLE
Upgrade coredns to v1.4.0 or v1.5.0

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#78003]
**What would you like to be added**:
A newer version of coredns

**Why is this needed**:
Currently shipped v1.3.1 is affected by https://github.com/coredns/coredns/issues/2629 issue, which causes the cluster outage if API server goes away temporarily.

**Comment by JishanXing** [comment]
I will work on it.

**Comment by rajansandeep** [comment]
CoreDNS v1.5.0 has been planned to be included for k8s 1.15
/assign

**Comment by mattjmcnaughton** [comment]
> CoreDNS v1.5.0 has been planned to be included for k8s 1.15
> /assign

Total curiosity question :) Is there a guide somewhere that lists what 3rd party version upgrades we intend to perform in what k8s version? Or is it on a more adhoc basis?

**Comment by zerkms** [comment]
Given that it was reverted https://github.com/kubernetes/kubernetes/pull/78691 can we please reopen this issue to track the problem

**Comment by andscova** [comment]
Is there any plan to update CoreDNS to v1.5.0 for the next k8s version? Otherwise could you point me to a guide to update manually?

**Comment by chrisohaver** [comment]
> Is there any plan to update CoreDNS to v1.5.0 for the next k8s version?

Yes. Or whatever the latest stable version of coredns will be at the time.
