### ISSUE TITLE
Add Scoring extension point of the scheduling framework

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#78002]
**What would you like to be added**:
The [scheduling framework KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) is now implementable. We have [already added](https://github.com/kubernetes/kubernetes/pull/75848) plugin interfaces and a few extension points, such as "[reserve](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)" and "[prebind](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-bind)" plugins.

[Scoring](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#scoring) plugins are used to rank nodes that have passed the filtering phase. The scheduler will call each scoring plugin for each node. There will be a well defined range of integers representing the minimum and maximum scores. After the [normalize scoring](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#normalize-scoring) phase, the scheduler will combine node scores from all plugins according to the configured plugin weights.

Scoring plugin interface should be designed so that all existing priority functions can be converted to scoring plugins.
**Please send your proposal for the interface of this extension point before sending a full PR and let us discuss and approve it first.**

This is needed for 1.16. A PR can be sent after 1.15 code freeze.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by ahg-g** [comment]
I can do this one as well.

**Comment by bsalamat** [comment]
@ahg-g I consider this as assigned.

**Comment by draveness** [comment]
Hi @ahg-g, how is this going on? I could work on this if you don't have the time, thanks :)

**Comment by ahg-g** [comment]
Hi Drave, we have few PRs related to the framework that are not merged yet (because of kubecon, then the code freeze), and so there is no rush implementing this one, I will send a PR probably next week just before the code freeze ends.
