### ISSUE TITLE
LoadBalancer Service stuck on pending when EnableTcpReset is enabled on SLB

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#78011]
**What happened**:

LoadBalancer Service stuck on pending when EnableTcpReset is enabled on SLB:

```sh
 kubectl describe service nginx
Name:                     nginx
Namespace:                default
Labels:                   run=nginx
Annotations:              <none>
Selector:                 run=nginx
Type:                     LoadBalancer
IP:                       10.0.25.177
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32269/TCP
Endpoints:                10.244.0.27:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                  From                  Message
  ----     ------                      ----                 ----                  -------
  Warning  CreatingLoadBalancerFailed  3m13s (x6 over 13m)  service-controller    Error creating load balancer (will retry): failed to ensure load balancer for service default/nginx: timed out waiting for the condition
  Normal   EnsuringLoadBalancer        33s (x7 over 15m)    service-controller    Ensuring load balancer
  Warning  CreateOrUpdateLoadBalancer  1s (x40 over 15m)    azure-cloud-provider  Code="EnableTcpResetCannotBeSpecifiedForApiVersion" Message="Specified api-version 2017-09-01 does not meet the minimum required api-version 2018-07-01 for EnableTcpReset property." Details=[]
````

This is because the Azure network API version 2017-09-0 is too old. To fix it, the API verison should be upgraded to at least 2018-07-01.

**What you expected to happen**:

Azure cloud provider should set the LB rules successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The fix should be cherry picked to old stable versions. However, release-1.12 is using Azure SDK v19.2.0, which doesn't include network API version 2018-07-01. So cloud probably only cherry pick the fix to 1.13 and 1.14 branch.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig azure
/kind bug
/priority critical-urgent

**Comment by justaugustus** [comment]
ref: #78012
