### ISSUE TITLE
kubelet & kube-proxy logs flooded

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#78023]
**What happened**:

Looking through a node's kubelet's logs, we've observed that it's extremely difficult to look through it because of several error messages flooding it over and over: https://paste.ubuntu.com/p/mZHs9f34Ft/

**What you expected to happen**:

Error messages are important and they should not be ignored, but the same error messages should not fill the entire log files (the same error appears every 2 seconds). One idea would be to exponentially reduce the frequency for the **same** error, so it won't be logged every 2 seconds.

**How to reproduce it (as minimally and precisely as possible)**:

Have orphaned pods on a node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`): Windows Server 2019 (10.0.17763.379)
- Kernel (e.g. `uname -a`):
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by tedyu** [comment]
In Kubelet#cleanupOrphanedPodDirs, orphanVolumeErrors produced the errors shown in the snippet.

Can we cache the most recent orphanVolumeError across calls to Kubelet#cleanupOrphanedPodDirs ?
If the current error is the same as the most recent, we increment its counter.
When counter reaches 10, we log the error with count.

orphanRemovalErrors can be handled in the same way.

**Comment by mattjmcnaughton** [comment]
Thanks for reporting this @bclau :) 100 percent agree we want this logs to be usable and right now, they are difficult to use in their current state.

A couple of additional options to consider :)

1. (The simplest) is to increase `pkg/kubelet/kubelet.go#housekeepingPeriod` from 2 seconds to a larger value? Tbh, I'm not sure if this is safe to do, nor if it makes sense to let logging concerns drive this period.
2. (The quickest for you to implement) Try and not have any orphaned pods. Do you know how the orphaned pods are being created/why they are not being cleaned up? Regardless of the logging issue, that could be interesting to examine.
3. Log `housekeeping` errors in a separate go routine, which executes with a different period. This period could be every 10 secs, or even potentially use an exponential backoff.
4. Change the log level of these errors, so they are not seen when run with the default verbosity.

None of these options seems to be the perfect solution... but I'm curious if anyone of them catches your eye?

**Comment by derekwaynecarr** [comment]
/kind feature

The kubelet is a control loop, and its always trying to reconcile like many other kubernetes controllers.  We can look to see if the logging is proper at the right verbosity level, but maybe a better question is what issue was encountered that made you want to look at the kubelet logs?  Were you able to grep for that issue effectively in our logs?  Is there tooling we could provide as a SIG to improve the ability to find the right information in the log?  Depending on the administrator, it may actually help the user to see these logs to know there was a problem, or we should report a metric to monitor for the problem?

**Comment by yujuhong** [comment]
I think kubelet (and cadvisor ,etc) typically logs the same error repeatedly, and it's not easy to just "read" the log to determine if anything went wrong. Knowing the use case could definitely help us improve the situation, so +1 to @derekwaynecarr's comment above.



> 1. (The simplest) is to increase `pkg/kubelet/kubelet.go#housekeepingPeriod` from 2 seconds to a larger value? Tbh, I'm not sure if this is safe to do, nor if it makes sense to let logging concerns drive this period.

I'd suggest, in general, not to change the frequency of the control loop to lower the noise. 

> 2. (The quickest for you to implement) Try and not have any orphaned pods. Do you know how the orphaned pods are being created/why they are not being cleaned up? Regardless of the logging issue, that could be interesting to examine.

Yes, this can actually be a bug if volumes cannot be cleaned up. Did the message stop showing up eventually? If not, it may be worth investigating what blocked the cleanup.

> 3. Log `housekeeping` errors in a separate go routine, which executes with a different period. This period could be every 10 secs, or even potentially use an exponential backoff.

This seems like an overkill. I think there are easier ways to address this while reusing the same goroutine 

> 4. Change the log level of these errors, so they are not seen when run with the default verbosity.

I think this differs case by case. For this particular error, maybe we can lower the "logging" frequency by presenting aggregated result, but not sure about lowering the verbosity completely.

**Comment by bclau** [comment]
> 
> 
> A couple of additional options to consider :)
> 
>     2. (The quickest for you to implement) Try and not have any orphaned pods. Do you know how the orphaned pods are being created/why they are not being cleaned up? Regardless of the logging issue, that could be interesting to examine.

Don't really know, this happened while running some E2E tests. Don't know which one(s) caused that, and the logs were too big and numerous (log rotation) to analyze.

**Comment by bclau** [comment]
Update: This also happens with kube-proxy: https://paste.ubuntu.com/p/qbGKdgBDhc/

It will generate ~1GB of logs every few days while being idle / unused. That is a bit too much, IMO. I've had ~18GB (or more) of logs on a node after a few weeks.
