### ISSUE TITLE
mount: special device /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[workload_share_0  ] volumes/myDisk does not exist

### ISSUE THREAD

**Issue by saravanakumarrajendran** [kubernetes/kubernetes#78024]
Tried this option 
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/kubernetes-volumes.html
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/persistent-vols-claims.html

Volume creation

vmkfstools -c 2G /vmfs/volumes/workload_share_0/volumes/myDisk.vmdk

Tried directly creating pod to attach.

#vsphere-volume-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: test-vmdk
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-vmdk
      name: test-volume
  volumes:
  - name: test-volume
    # This VMDK volume must already exist.
    vsphereVolume:
      volumePath: "[datacenter/workload_share_0] volumes/myDisk.vmdk"
      fsType: ext4

Created the PV and attached pod, even getting the same error.

  Warning  FailedMount  22s  kubelet, k8worker001  MountVolume.SetUp failed for volume "pv0001" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/e30f2f05-7886-11e9-af52-0050568cada5/volumes/kubernetes.io~vsphere-volume/pv0001 --scope -- mount -o bind /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[workload_share_0  ] volumes/myDisk /var/lib/kubelet/pods/e30f2f05-7886-11e9-af52-0050568cada5/volumes/kubernetes.io~vsphere-volume/pv0001
Output: Running scope as unit run-26004.scope.
mount: special device /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[workload_share_0  ] volumes/myDisk does not exist

**Comment by divyenpatel** [comment]
@saravanakumarrajendran looks like you are missing `disk.EnableUUID` flag on your node VM. Can you please add this flag, and recreate the pod. 

you can add this flag on your node VM using govc or vcenter UI.

```
govc vm.change -e="disk.enableUUID=1" -vm='VM Path'
```

**Comment by divyenpatel** [comment]
@saravanakumarrajendran are you able to resolve this issue with enabling disk.enableUUID flag on the node VM. If yes, please mark this issue as resolved and close it.

**Comment by raulsh** [comment]
I have the exact same problem. I followed all of the recommendations, but nothing.

**Comment by tirelibirefe** [comment]
I have the same problem. My VMs are already flagged disk.EnableUUID=TRUE

**Comment by andyzhangx** [comment]
I have the same transient issue on Azure File(SMB) mount, as I could observe, it only happens in k8s v1.20 in a little possibility, not sure what's wrong(rerun the test usually works):
```
May  2 15:06:55.766: INFO: At 2021-05-02 14:51:38 +0000 UTC - event for azurefile-volume-tester-2tpth: {kubelet k8s-agentpool1-32450920-vmss000000} FailedMount: MountVolume.SetUp failed for volume "azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7" : rpc error: code = Internal desc = Could not mount "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/globalmount" at "/var/lib/kubelet/pods/ed800670-69de-4a1e-902c-e0ceeca4ec68/volumes/kubernetes.io~csi/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/globalmount /var/lib/kubelet/pods/ed800670-69de-4a1e-902c-e0ceeca4ec68/volumes/kubernetes.io~csi/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/mount
Output: mount: /var/lib/kubelet/pods/ed800670-69de-4a1e-902c-e0ceeca4ec68/volumes/kubernetes.io~csi/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/globalmount does not exist.
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azurefile-csi-driver/642/pull-azurefile-csi-driver-e2e-vmss/1388861197100519424/build-log.txt

**Comment by zhoudayongdennis** [comment]
@divyenpatel

i encountered the same issue on vsphere CPI 1.21 and CSI 2.3.1 with disk.EnableUUID=TRUE, do you have any further recommendation for more investigation?
