### ISSUE TITLE
Allow listing secrets without disclosing secret data

### ISSUE THREAD

**Issue by nelsonjr** [kubernetes/kubernetes#78056]
**What would you like to be added**:

Allow the ability to list resources without the ability to read its contents

**Why is this needed**:

For secrets, it is preferred to not let users see their contents with the naked eye. However, today is an all-or-nothing proposition: you either list the secrets *and has access to all their content*, or not see them at all.

This prevents users from asserting that the resources even exist.

*From Discussion With Security Team*

**What happened**

With a limited user, with cluster role `view` role, and associating with a cluster role that allows `("", "secrets", ["list"])`, the user is capable of extracting the secrets data.

**What you expected to happen**

Secrets are not exposed as `get` permissions is absent.

**How to reproduce it (as minimally and precisely as possible)**

1. Grant cluster role `view`
2. Create a cluster role that allows `secrets:list` and associate with the user
3. Run `kubectl get secrets` and confirm secrets can be listed
4. Run `kubectl get secret <some-secret>` and confirm access is denied
5. Run `kubectl get secrets -o yaml` and see all the secrets in plain text

**Environment**

Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Any
- Kernel (e.g. `uname -a`): Any

**Detailed log**
```
$ kubectl get secret
default-token-r5gjn   kubernetes.io/service-account-token   3      5d

$ kubectl get secret default-token-r5gjn
Error from server (Forbidden): secrets "default-token-r5gjn" is forbidden: User "system:serviceaccount:acct-bali-team:nelson-araujo" cannot get secrets in the namespace "bali-data-stg"

$ kubectl get secret default-token-r5gjn -o yaml
Error from server (Forbidden): secrets "default-token-r5gjn" is forbidden: User "system:serviceaccount:acct-bali-team:nelson-araujo" cannot get secrets in the namespace "bali-data-stg"

$ kubectl get secret -o yaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: <DATA>
    namespace: <DATA>
    token: <DATA>
  kind: Secret
  metadata:
    annotations:
      kubernetes.io/service-account.name: default
      kubernetes.io/service-account.uid: c863e592-7469-11e9-b0dc-02082368d9d6
    creationTimestamp: 2019-05-12T03:55:29Z
    name: default-token-r5gjn
    namespace: <DATA>
    resourceVersion: "1454"
    selfLink: /api/v1/namespaces/bali-data-stg/secrets/default-token-r5gjn
    uid: c865f8a0-7469-11e9-b0dc-02082368d9d6
  type: kubernetes.io/service-account-token
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by nelsonjr** [comment]
@kubernetes/sig-architecture

**Comment by liggitt** [comment]
> This prevents users from asserting that the resources even exist.

Can you describe use cases for this? Also, names themselves can be considered private information.

**Comment by nelsonjr** [comment]
@liggitt if the names are private then you simply do not grant list.

The use case here is where you have different applications in the same namespace, and you want your developers to be able to see the dashboard, but not access all secrets of all applications.

**Comment by liggitt** [comment]
> and you want your developers to be able to see the dashboard, but not access all secrets of all applications

A dashboard that tolerates not being able to list secrets seems like the best approach in that case. Given the narrowness of the use case, an entirely new access pattern and authorization attribute is unlikely.

**Comment by WeiBanjo** [comment]
We have same issue in our company. We are trying to limit developer to access/read all secrets in a namespace. But we want to give ability for develop to know the name of the secret.

**Comment by wmgroot** [comment]
We have the same desire at our company to allow developers to list the names of secrets for debugging and transparency, without being able to read the secret itself.

/remove-lifecycle stale

**Comment by liggitt** [comment]
Thanks for the feature request, but this is unlikely to make progress as an issue. A proposal that works through the design along with the implications of such a change can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps).

/close
