### ISSUE TITLE
Old ReplicaSet and Old pods are still alive with New ReplicaSet

### ISSUE THREAD

**Issue by petro404** [kubernetes/kubernetes#78070]
**What happened**:
I am creation new deployment and after few seconds update the pod template spec with new configuration and then Old ReplicaSet and Old pods are still alive with New ReplicaSet
the current behaviour is based on default deployment strategy rolling upgrade 

i would like to know if its normal behaviour of rolling upgrade so k8s will keep the old pod until the new pod will started successfully and then it will disable the old replicaset and delete the old pod

**What you expected to happen**:
New ReplicaSet is created with new pod and old replicaset should be removed with old pod

**How to reproduce it (as minimally and precisely as possible)**:
1-create new deployment resource
2-update the pod template sepc by adding new env variable

**Anything else we need to know?**:
/sig scalability
/sig API Machinery
/sig Architecture

**Environment**:
- Kubernetes version (use `kubectl version`):1.11
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Yes, that is a property of a rolling upgrade strategy

/close
