### ISSUE TITLE
[Failing tests] CustomResourceConversionWebhook and CustomResourcePublishOpenAPI failing in master-blocking

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#78087]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-alpha-features

**Which test(s) are failing**:
* [sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI]
works for multiple CRDs of same group but different versions
* [sig-api-machinery] CustomResourceConversionWebhook [Feature:CustomResourceWebhookConversion]
Should be able to convert a non homogeneous list of CRs
* [sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI]
works for CRD without validation schema`
* [sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI]
works for multiple CRDs of same group and version but different kinds
* [sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI]
updates the published spec when one versin gets renamed
* [sig-api-machinery] CustomResourceConversionWebhook [Feature:CustomResourceWebhookConversion]
Should be able to convert from CR v1 to CR v2
* [sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI]
works for multiple CRDs of different groups
* [sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI]
removes definition from spec when one versin gets changed to not be served

**Since when has it been failing**:
Failing since 5/16 [k/k diff](https://github.com/kubernetes/kubernetes/compare/dddb133c2...afd928b8b).
There were two PRs related to API machinery and tests that were merged during this period #77925 and #77927

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

**Reason for failure**:

The first failure seems to be this:

[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for multiple CRDs of same group but different versions
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go:187 
May 19 16:36:16.133: failed to wait for definition "io.k8s.crd-publish-openapi-test-multi-ver.v3.E2e-test-crd-publish-openapi-9283-crd" to be served with the right OpenAPI schema: 
failed to wait for OpenAPI spec validating condition: timed out waiting for the condition; lastMsg: spec.SwaggerProps.Definitions["io.k8s.crd-publish-openapi-test-multi-ver.v3.E2e-test-crd-publish-openapi-9283-crd"] not found 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go:194
```

/cc @kubernetes/sig-api-machinery-test-failures 
/priority critical-urgent
/kind failing test
/milestone v1.15
/cc @jimangel @smourapina @rarchk @alenkacz

**Comment by liggitt** [comment]
@sttts looks like there were some alpha gated tests that need adjusting after https://github.com/kubernetes/kubernetes/pull/77927

**Comment by sttts** [comment]
On it.

**Comment by roycaihw** [comment]
another PR touching CRD OpenAPI publishing was merged yesterday https://github.com/kubernetes/kubernetes/pull/77554 and we didn't run alpha presubmit test

@liggitt let me know if you think it's specific to CRD openapi publishing and I can look into it

**Comment by liggitt** [comment]
debugging now

**Comment by liggitt** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features is now green

/close
