### ISSUE TITLE
Create AWS IPv6 route cause "destinationCidrBlock is invalid" 

### ISSUE THREAD

**Issue by hangxie** [kubernetes/kubernetes#78089]
**What happened**: I run IPv6 for pod/service network on AWS with kubernetes+calico, kubernetes was unable to update route table with error message like:
```
E0519 18:55:27.800744       1 route_controller.go:199] Could not create route 8fa94910-7a67-11e9-8b00-0a8652be5e88 fd00:1234::300/120 for node ip-10-10-1-37.ec2.internal: error creating AWS route (fd00:1234::300/120): "InvalidParameterValue: Value (fd00:1234::300/120) for parameter destinationCidrBlock is invalid. This is not a valid CIDR block.\n\tstatus code: 400, request id: 24812989-6221-43aa-a8de-20bde0ee3672"
```
and route was never created.

I scanned code and found that that kubernetes uses DestinationCidrBlock to create new route but that's for IPv4 only, it should use DestinationIpv6CidrBlock parameter to create IPv6 routes.

**What you expected to happen**: new route created with IPv6 CIDR

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: No

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`AWS`
- OS (e.g: `cat /etc/os-release`):
`VERSION="18.04.2 LTS (Bionic Beaver)"`
- Kernel (e.g. `uname -a`):
`Linux kube-master-0 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
`kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:20:34Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`
- Network plugin and version (if this is a network-related bug):
```
calico
Client Version:    v3.7.2
Git commit:        a51fe915
Cluster Version:   v3.7.2
Cluster Type:      k8s,bgp
```
- Others:

**Comment by hangxie** [comment]
@kubernetes/sig-aws-bugs

**Comment by hangxie** [comment]
I ended up with disable cloud route so this is no longer an issue to me, but it will still be a problem to someone who wants to use the feature.

**Comment by aojea** [comment]
indeed this is going to fail with ipv6 routes

https://github.com/kubernetes/kubernetes/blob/103e926604de6f79161b78af3e792d0ed282bc06/staging/src/k8s.io/legacy-cloud-providers/aws/aws_routes.go#L212

@andrewsykim what's the policy with the legacy cloud providers? 
should new bugs being opened against the new out of tree cloud providers?
/cc @danwinship
