### ISSUE TITLE
Re-distribute pods over labeled nodes

### ISSUE THREAD

**Issue by Badranh** [kubernetes/kubernetes#78091]
**What happened**:
At first I had 3 replicas of X pod that run on labeled nodes and I had a cluster of 3 nodes( 1 master and 2 nodes) all of them were unlabeled, so I executed this command: 

` kubectl label node  {node1-name}  label=x`

then

` kubectl label node  {node2-name}  label=x`

after that I executed

`kubectl get pods -o wide`

and it looked that the 3 pods are running on {node1-name} and not distributed, I waited for 10 minutes and still the 3 pods running on one node only which is {node1-name}.

**What you expected to happen**:
Shouldn't they be re-distributed again like 2 pods on {node1-name} and 1 on {node2-name} for example?
**How to reproduce it (as minimally and precisely as possible)**:
1- create 2 nodes with a master node (AWS)
2- create a deployment using yml file that has 3 replicas of a labeled pod
3- label one of the nodes
4- label the second node

**Environment**:
- Kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS

- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

Linux ubuntu-xenial 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liggitt** [comment]
pod nodeSelectors are used to schedule pods to nodes. once scheduled and running, pod nodeSelectors do not cause eviction if the node labels change. 

/sig scheduling node
/remove-kind bug
/kind feature
