### ISSUE TITLE
Autodetect IP family for e2e testing

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#78099]
**What would you like to be added**:

Introduce a mechanism that allows ~~detecting~~ specifying the IP protocol version used in the e2e testing.

**Why is this needed**:

This is a followup on #70248, my understanding is that in order to discriminate between IPv4 or IPv6  we have to use the test labels and this adds complexity to the testing automation and doesn't allow to send this information to the context of the tests.

Having a mechanism to ~~detect~~ specify the IP protocol will simplify the testing for IPv4 and IPv6 and will allow reusing most of the code.

**Comment by aojea** [comment]
/sig testing
/cc @neolit123 @fabriziopandini @BenTheElder 
/assign @aojea 

Does this make sense?
If affirmative, what should be the best way to add this functionality? 
Checking the code I think that `e2e/framework/test_context.go` or `test/e2e/framework/framework.go` can provide this, don't know if checking some of the cluster config parameters, 🤔 ...

**Comment by neolit123** [comment]
the testing-commons group (sig-testing) maintains the framework, but ideally the decision on how to proceed in terms of adding ipv6 detection should come from sig-network.

possibly having this as agenda for a sig-network meeting is a good start, then discussing it in a testing-commons meeting.

/sig network
/area e2e-testing-framework

> Having a mechanism to detect the IP protocol will simplify the testing for IPv4 and IPv6 and will allow reusing most of the code.

the linked issue is a big one, so i don't have all the context here. but IMO existing tests should just work for ipv6 without the requirement for a new "IPV6" tag in test names.

dual-stack or protocol specific tests should have their descriptions contained the details properly.

we might want to add an utility function under:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/networking_utils.go
(there is a PR to move it BTW https://github.com/kubernetes/kubernetes/pull/77377/files)

then such an utility might be useful *only* to tests that need to detect the protocol.
one of the goals is to refactor the code in test_context / framework, so adding this logic there is less preferred.

**Comment by aojea** [comment]
@neolit123 I think that we can use an option to test_context to specify the cluster IP family the same way that exists one for the cloud provider

```
	// Provider identifies the infrastructure provider (gce, gke, aws)
	Provider string
```

**Comment by BenTheElder** [comment]
Being able to override and specify exactly what you want the test to beleive about your cluster is nice, but ideally it should generally work without specifying _more_ flags. Surely we can detect this?

**Comment by aojea** [comment]
I was thinking during some time about this,  detecting the IP family is very simple having IPv4 or IPv6 only clusters, but with the introduction of dual stack I´m afraid about the supportability and reliability of the autodetecting mechanisms in the long term. If you see the dual stack PRs there are still a lot of unknowns about the cluster behavior.
My point is, let´s have something first stable that works and is simple, and once dual stack is implemented, we can replace the flag with a function in the framework .

I guess that migrating from a flag variable to a function is straight forward, 

```
// LoopbackIP returns a loopback IP depending on the IP family of the cluster
func LoopbackIP() string {
	switch TestContext.IpFamily {
	case "ipv6":
		return "::1"
	default:
		return "127.0.0.1"	}
}
```

is just replacing `TestContext.IpFamily` by `e2enet.IpFamily`, what do you think?

**Comment by neolit123** [comment]
> is just replacing TestContext.IpFamily by e2enet.IpFamily, what do you think?

in https://github.com/kubernetes/kubernetes/pull/80398
`IpFamily` is added as part of the context.

do you mean adding `e2enet.IpFamily()` as a function which will auto-detecting the ip family.
less flags for the framework binary is preferred.

**Comment by aojea** [comment]
once we have this I will open a new issue to start cleaning up `[Feature:Networking-IPv6]` and `[Feature:Networking-IPv4]` , we no longer need to discriminate based on tags
