### ISSUE TITLE
[Failing test] GCE-5000: increased latency of replicationcontrollers list

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#78111]
**Which jobs are failing**:
gce-scale-performance
kubemark-5000

**Which test(s) are failing**:
Scalability density and load tests.

**Since when has it been failing**:
Run 1115887544400089089 2019-04-10 08:01:47 +0000 UTC.
Previous correct run 1115162902861451269 was on 2019-04-08.

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000

**Reason for failure**:
The test is no failing constantly. However the latency of listing replication controllers significantly increased.

**Anything else we need to know**:

**Comment by krzysied** [comment]
![rc_list_density](https://user-images.githubusercontent.com/25119199/58023128-4c84ac80-7b0f-11e9-8fe6-c4b210874863.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=DensityResponsiveness&Resource=replicationcontrollers&Scope=cluster&Subresource=&Verb=LIST

![rc_list_load](https://user-images.githubusercontent.com/25119199/58023135-55757e00-7b0f-11e9-914b-eafe9745b887.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadResponsiveness&Resource=replicationcontrollers&Scope=cluster&Subresource=&Verb=LIST

**Comment by krzysied** [comment]
This issue is also observable on kubemark-100-highDensity

![rc_list_kubemark](https://user-images.githubusercontent.com/25119199/58023296-c1f07d00-7b0f-11e9-8248-05ce08f0b0be.png)
http://perf-dash.k8s.io/#/?jobname=kubemark-100Nodes-highDensity&metriccategoryname=APIServer&metricname=DensityResponsiveness&Resource=replicationcontrollers&Scope=cluster&Subresource=&Verb=LIST

This test takes ~3h to be executed (which is same time as gce5000 desnity test), but requires only 104cpu to be run.

**Comment by krzysied** [comment]
I've compared logs from 08-04 and 10-04. In case of load test is seems that in both cases there where long (~5s) calls. It seems that for some reason apiserver metrics (or clusterloader) returns different values for similar metrics.

**Comment by krzysied** [comment]
Logs from kubemark100-highDensity:

08-04:
```
I0408 08:20:59.854502       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+saturation&limit=500&resourceVersion=0: (2.22079ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.101.108:39866]
I0408 08:21:01.193433       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+saturation: (1.717344ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.101.108:39844]
I0408 09:08:51.218693       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+latency&limit=500&resourceVersion=0: (601.147µs) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.101.108:39868]
I0408 09:10:51.589241       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+latency: (103.110304ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.101.108:39850]
I0408 09:12:56.846320       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+latency: (1.785482ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.101.108:39854]
I0408 09:13:06.483924       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+saturation: (1.619895ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.101.108:39844]
```
99th perc (perfdash): 1.476ms

10-04:
```
I0410 16:14:18.118570       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+saturation&limit=500&resourceVersion=0: (2.274331ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.38.228:47506]
I0410 16:14:19.493526       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+saturation: (1.52567ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.38.228:47486]
I0410 17:02:12.710609       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+latency&limit=500&resourceVersion=0: (701.975µs) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.38.228:47512]
I0410 17:04:13.178729       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+latency: (205.417366ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.38.228:47494]
I0410 17:06:18.440140       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+latency: (2.092425ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.38.228:47496]
I0410 17:06:27.097434       6 wrap.go:47] GET /api/v1/replicationcontrollers?labelSelector=group+%3D+saturation: (1.445484ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 35.188.38.228:47486]
```
99th perc: 204ms

It looks like there was some bug in metrics on apiserver, clusterloader or perfdash side. Current result seems correct.

**Comment by krzysied** [comment]
I looked through clusterloader and perfdash histories and I haven't spotted any changes related to this issue.

**Comment by wojtek-t** [comment]
This has merged on April 9th:
https://github.com/kubernetes/kubernetes/pull/76215

I'm almost sure this is what is described https://github.com/kubernetes/kubernetes/issues/76579#issuecomment-490079549 and below in that thread.
There was a bug in metrics reporting.

**Comment by krzysied** [comment]
You are right. The replicationcontrollers list graph has the same characteristic as one for pods list. This is the same case. I'm closing the bug.
