### ISSUE TITLE
Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.

### ISSUE THREAD

**Issue by boroda4436** [kubernetes/kubernetes#78126]
**What happened**:
Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.

**What you expected to happen**:
Expected to create a namespace and receive next msg on the UI: _Successfully created default namespace with name cbs-namespace_

**How to reproduce it (as minimally and precisely as possible)**:
1. Clone the project: https://github.com/boroda4436/kubernetes-demo.git
2. Add your Google Compute credentials key to resources/google_credentials.json and change your project name in application.properties
3. Run main app
4. Visit http://localhost:8080/ and click CREATE CLUSTER
5. After cluster will be deployed - click CREATE_NAMESPACE

Create namespace command will fail and you will see error message right in your browser:

### Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue May 21 11:58:46 EEST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Operation: [create] for kind: [Namespace] with name: [null] in namespace: [null] failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:321)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.lambda$createNew$0(BaseOperation.java:336)
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:26)
	at com.boroda.kubernetes.demo.controller.KubeClusterController.createBasicNamespace(KubeClusterController.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by boroda4436** [comment]
sig/GCP

**Comment by boroda4436** [comment]
@sig/GCP

**Comment by boroda4436** [comment]
@kubernetes/sig-gcp

**Comment by boroda4436** [comment]
@sig-gcp

**Comment by boroda4436** [comment]
@kubernetes/sig-gcp

**Comment by boroda4436** [comment]
@kubernetes/gcp

**Comment by boroda4436** [comment]
@kubernetes/sig-gcp-bugs

**Comment by tedyu** [comment]
Where can I find the logs containing the 'namespace: [null] failed' message ?

**Comment by boroda4436** [comment]
@tedyu thanks for reply! 
You can see this error message after step 5 right in the your browser

**Comment by boroda4436** [comment]
@tedyu Did you have a chance to reproduce the bug using steps above?

**Comment by tedyu** [comment]
Busy @dayjob

Hopefully would get to this later.

**Comment by boroda4436** [comment]
updated a demo project https://github.com/boroda4436/kubernetes-demo
Now you can specify cluster version.
Note that everything is ok with 1.11.8-gke.6, but at the same time demo is not working with 1.12.7-gke.10

**Comment by boroda4436** [comment]
**SOLVED:** It was required to refresh the Google OAuth2 token and pass to kubeclient. Works fine for all versions. 
**IMPLEMENTED** in this [commit](https://github.com/boroda4436/kubernetes-demo/commit/5d67baba0780d58d6bd3d0ce03bad73047112671)
