### ISSUE TITLE
[Failing tests] Multiple job failures on the BeforeSuite step while waiting for CoreDNS to be ready

### ISSUE THREAD

**Issue by smourapina** [kubernetes/kubernetes#78123]
**Which jobs are failing**:
Multiple jobs on `master-informing`.

**Which test(s) are failing**:
`Before Suite` on the following jobs:
- https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-stable-master
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master-parallel
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-parallel
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster
- https://testgrid.k8s.io/sig-release-master-informing#gce-master-new-downgrade-cluster
- https://testgrid.k8s.io/sig-release-master-informing#gce-master-new-downgrade-cluster-parallel
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-new
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-new-parallel

**Since when has it been failing**:
Since 5/17.

**Testgrid links**:
See above.

**Reason for failure**:
All the failures mentioned above seem to have to have the same root cause, namely failure while waiting for CoreDNS to be ready.
Example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1129638974428549121
```
May 18 07:09:00.075: Error waiting for all pods to be running and ready: 2 / 14 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                      NODE                   PHASE   GRACE CONDITIONS
coredns-65546fffc9-j9p6b kinder-upgrade-worker2 Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [coredns]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [coredns]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason: Message:}]
```

/sig testing
/priority critical-urgent
/kind failing test
/milestone v1.15
/cc @jimangel @alejandrox1 @rarchk @alenkacz

**Comment by chrisohaver** [comment]
Some of this (possible all of it) is due to #78030, which is dependent on #78033 being merged.

**Comment by neolit123** [comment]
Not the gce job tho. Only the kinder job. So the gce jobs are failing a problem outside of kubeadm/kinder

**Comment by neolit123** [comment]
/assign
(At kubecon this week)

**Comment by chrisohaver** [comment]
The gce failures appear to show the same behavior, but with _kube-up_ instead of kubeadm.  I.e. it appears that kube-up may also be retaining old configs when upgrading/downgrading.  If thats true, then we may need to integrate the migration tools into kube-up as well.

**Comment by rajansandeep** [comment]
I have opened https://github.com/kubernetes/kubernetes/pull/78302 which aims to fix all the failing tests except https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-stable-master, which will be fixed via https://github.com/kubernetes/kubernetes/pull/78033.

**Comment by smourapina** [comment]
Great job so far @chrisohaver, @rajansandeep and @neolit123! 

Would it be possible to ask for the open PRs to be merged and/or a solution found soon? We have these tests failing for quite some time and code freeze coming up in the next days. Thank you in advance for your efforts!

**Comment by neolit123** [comment]
@smourapina thanks for the heads up.
@rajansandeep let me know if you don't have the time for the https://github.com/kubernetes/kubernetes/pull/78033 refactor that i requested and i can try to take over there. the alternative is to rollback the coredns version which i assume is not ideal, due to a variety of fixes in the new version.

**Comment by alejandrox1** [comment]
@neolit123 is there any more work planned for this issue? I see that some of the kinder jobs are still failing https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-stable-master

**Comment by rajansandeep** [comment]
@alejandrox1 merging #78302 and #78033 will resolve and close this issue.

**Comment by alejandrox1** [comment]
Thank you for the update @rajansandeep ! 🎉

**Comment by alejandrox1** [comment]
updates: kinder tests were fixed via https://github.com/kubernetes/kubernetes/pull/78545

**Comment by neolit123** [comment]
/unassign
i was here for:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-stable-master

it's a bit flaky, but green - which is due to the tooling.

**Comment by soggiest** [comment]
Since #78302 and #78303 we're moved to 1.16, and we're waiting for #78851 to merge, can we move this issue to 1.16?

**Comment by alejandrox1** [comment]
@soggiest https://github.com/kubernetes/kubernetes/pull/78303 ? is that the right PR?

**Comment by soggiest** [comment]
Good catch, I meant #78033

**Comment by alejandrox1** [comment]
The GCE test failures were fixed by https://github.com/kubernetes/kubernetes/pull/78691 and https://github.com/kubernetes/kubernetes/pull/78920
/close
