### ISSUE TITLE
Docker failed to create container on windows nodes: Failed to unmarshall layerchain json - invalid character '\\x00' looking for beginning of value"

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#78139]
**What happened**:
Docker failed to create container on windows nodes with error message
```
Failed to unmarshall layerchain json - invalid character '\\x00' looking for beginning of value"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Not sure. This happened quite frequently in E2E tests.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: GCE
- OS (e.g: `cat /etc/os-release`): Windows 1809
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Search result suggested that the file may be corrupted. Once a node ran into this issue for a certain image, it'd no longer be able to create containers using that image.

On the same node, I've found error messages (from windows even log) below:
```
An error was detected on device \Device\Harddisk4\DR125 during a paging operation.
Disk 4 has the same disk identifiers as one or more disks connected to the system. Go to Microsoft's support website (http://support.microsoft.com) and search for KB2983588 to resolve the issue.
The disk signature of disk 4 is equal to the disk signature of disk 1.
```

I think the device in the error message corresponds to the container, and the error message can be related to the problem, but I'm not sure.

**Comment by tedyu** [comment]
Was there any other line from windows event log related to disk 1 / 4 ?

thanks

**Comment by yujuhong** [comment]
I didn't notice anything specific, but there were similar log messages for disk 1 & 8

**Comment by yujuhong** [comment]
Update: I found errors such as `An error was detected on device \Device\Harddisk6\DR28 during a paging operation.` in test runs that did not have the "layerchain" issue, so likely those are just red herrings.

**Comment by drnybble** [comment]
I am seeing the same error with Docker Swarm against 18.09.7

**Comment by mmusin** [comment]
The same issue i faced in AKS

**Comment by Lagicrus** [comment]
I am also having this issue

**Comment by michmike** [comment]
@Lagicrus can you please give us some additional details on your environment, versions of windows/k8s and any logs? thanks!

**Comment by michmike** [comment]
cc: @marosset

**Comment by marosset** [comment]
cc @immuzz

**Comment by Lagicrus** [comment]
> @Lagicrus can you please give us some additional details on your environment, versions of windows/k8s and any logs? thanks!


This issue "resolves" itself when I use WSL2 vs Windows ones (for people who want to try a different fix). Or at least that is what I assume as it tells me to switch to Linux when it breaks.

Sorry that I took a while to respond @michmike was busy with other projects and then it took about 20 minutes to go from "Building X" to actually doing one of the steps and henceforth failing.

Version for Docker 
![image](https://user-images.githubusercontent.com/24227350/83348488-15052e80-a325-11ea-9ec3-5199b0a8db75.png)
(Saves me having to type it out)

When I run `docker-compose -v` in PowerShell (in Windows Terminal) I get `docker-compose version 1.26.0-rc4, build d279b7a8`

Unsure what logs I can get you so I will wait for a response. 
In terms for where it breaks for me if it helps
![image](https://user-images.githubusercontent.com/24227350/83348527-64e3f580-a325-11ea-8624-bfe16dfe65a5.png)

**Comment by marosset** [comment]
@Lagicrus can you share what Windows version/patches you are using by running winver.exe and sharing the output?

Are you seeing this when using container base images other than python:3.7?

Can you start containers on the same machine manually and, does `docker logs <container id>`  contain more info?

**Comment by Lagicrus** [comment]
> @Lagicrus can you share what Windows version/patches you are using by running winver.exe and sharing the output?
> 
> Are you seeing this when using container base images other than python:3.7?
> 
> Can you start containers on the same machine manually and, does `docker logs <container id>` contain more info?

![image](https://user-images.githubusercontent.com/24227350/83560280-e4341d80-a50d-11ea-8e56-0f8c8bb9d6d3.png)

Currently, the only base image I use is python:3.7.
Which prebuilt image would you recommend me trying to build locally to test best?

Well, I can't get the logs of the container as when I do `docker ps` its blank 😕

**Comment by dazinator** [comment]
Hitting this on azure web app for windows containers, running a aspnet core 3.1 docker image.
