### ISSUE TITLE
Include windows binaries in cri-tools

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#78134]
Right now cri-tools only include tarballs for linux 
https://github.com/kubernetes/kubernetes/blob/c85c0e4780e428fdfb33debc31bc88f8095e5831/build/workspace.bzl#L29-L36

/cc @feiskyer @Random-Liu 
/cc @pjh

**Comment by ttousai** [comment]
Hello! I'm a bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. Code freeze is starting on August 29th (about 2 days from now), which means that this PR must merged by then.

Do we still target this issue to be fixed for 1.16?

**Comment by feiskyer** [comment]
@justaugustus anything we can do in release team?

**Comment by saschagrunert** [comment]
I'm working on this one now.
/assign
