### ISSUE TITLE
Pv cannot control the storage capacity. Is there any way to control it?

### ISSUE THREAD

**Issue by Mentality-is-better** [kubernetes/kubernetes#78149]
![image](https://user-images.githubusercontent.com/43332489/58076103-ee71cb00-7bdb-11e9-89e7-2a5840151b23.png)
[](url)

Set the pv size to 2Gi, but the actual storage can still be greater than 2Gi

![image](https://user-images.githubusercontent.com/43332489/58076176-28db6800-7bdc-11e9-822f-1f780aa53f71.png)

Hope everybody can help solve next

Thank you!

**Comment by Coderhypo** [comment]
Hi, guy,

I think `Gi != G`

https://stackoverflow.com/questions/50804915/kubernetes-size-definitions-whats-the-difference-of-gi-and-g

**Comment by Mentality-is-better** [comment]
![image](https://user-images.githubusercontent.com/43332489/58087314-ec673680-7bf2-11e9-8db7-9a4678e5eb48.png)

Thank you. The pv capacity can still be used after I tested according to what you said

![image](https://user-images.githubusercontent.com/43332489/58087477-34865900-7bf3-11e9-9408-6a44795a124c.png)

**Comment by Mentality-is-better** [comment]
@Coderhypo

**Comment by Mentality-is-better** [comment]
@danielqsj 
Can we solve this problem
thank you

**Comment by Mentality-is-better** [comment]
Can someone help out?

**Comment by hoyho** [comment]
> Can someone help out?

@Mentality-is-better 
From the screenshot you provided, you are using nfs (mount with nfsv4).
nfs volume don't have a quota setting or limitation on size. It was just a shared folder.
This should be a special case, Some storage backend do not support quota.

you may refer the CSI design
[https://github.com/container-storage-interface/spec/blob/c3707a60a2d4a0a684ba342c048534defb74853d/csi.proto#L416](https://github.com/container-storage-interface/spec/blob/c3707a60a2d4a0a684ba342c048534defb74853d/csi.proto#L416)
  
 >// Information about a specific volume.
message Volume {
  // The capacity of the volume in bytes. This field is OPTIONAL. If not
  // set (value of 0), it indicates that the capacity of the volume is
  // unknown (e.g., NFS share).
  // The value of this field MUST NOT be negative.
  int64 capacity_bytes = 1;

**Comment by Mentality-is-better** [comment]
@hoyho   thank you
