### ISSUE TITLE
Kubernetes apiserver tls handshake error after certificate added and bind address

### ISSUE THREAD

**Issue by thundertiger825** [kubernetes/kubernetes#78158]
Logs of kube-apiserver

Starting crd-autoregister controller
May 21 11:49:34 master kube-apiserver[1236]: I0521 11:49:34.874671    1236 controller_utils.go:1027] Waiting for caches to sync for crd-autoregister controller
May 21 11:49:34 master kube-apiserver[1236]: I0521 11:49:34.874794    1236 customresource_discovery_controller.go:199] Starting DiscoveryController
May 21 11:49:34 master kube-apiserver[1236]: I0521 11:49:34.874891    1236 naming_controller.go:284] Starting NamingConditionController
May 21 11:49:34 master kube-apiserver[1236]: I0521 11:49:34.874991    1236 establishing_controller.go:73] Starting EstablishingController
May 21 11:49:34 master kube-apiserver[1236]: I0521 11:49:34.876306    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57432: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.085722    1236 cache.go:39] Caches are synced for APIServiceRegistrationController controller
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.086151    1236 cache.go:39] Caches are synced for autoregister controller
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.086626    1236 controller_utils.go:1034] Caches are synced for crd-autoregister controller
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.316325    1236 cache.go:39] Caches are synced for AvailableConditionController controller
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.871978    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57462: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.872825    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57460: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.873319    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57464: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.878493    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57466: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.880452    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57468: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.881122    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57470: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.881863    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57472: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.884294    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57474: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.884529    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57476: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.885442    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57478: tls: first record does not look like a TLS handshake
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.902427    1236 storage_scheduling.go:91] created PriorityClass system-node-critical with value 2000001000
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.976969    1236 storage_scheduling.go:91] created PriorityClass system-cluster-critical with value 2000000000
May 21 11:49:35 master kube-apiserver[1236]: I0521 11:49:35.977241    1236 storage_scheduling.go:100] all system priority classes are created successfully or already exist.
May 21 11:49:36 master kube-apiserver[1236]: W0521 11:49:36.251900    1236 lease.go:226] Resetting endpoints for master service "kubernetes" to [10.91.32.169]
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.873827    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57480: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.876190    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57484: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.876958    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57482: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.879252    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57486: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.880935    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57488: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.883205    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57490: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.885651    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57492: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.886507    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57494: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.888103    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57498: tls: first record does not look like a TLS handshake
May 21 11:49:36 master kube-apiserver[1236]: I0521 11:49:36.889038    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57496: tls: first record does not look like a TLS handshake
May 21 11:49:37 master kube-apiserver[1236]: I0521 11:49:37.725242    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57500: tls: first record does not look like a TLS handshake
May 21 11:49:37 master kube-apiserver[1236]: I0521 11:49:37.875571    1236 log.go:172] http: TLS handshake error from 10.91.32.169:57502: tls: first record does not look like a TLS handshake

**Comment by thundertiger825** [comment]
configuration of apiserver file 


###
# kubernetes system config
#
# The following values are used to configure the kube-apiserver
#

# The address on the local server to listen to.
KUBE_API_ADDRESS="--bind-address=0.0.0.0"

# The port on the local server to listen on.
KUBE_API_PORT="--secure-port=6443"

# Port minions listen on
# KUBELET_PORT="--kubelet-port=10250"

# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers=http://127.0.0.1:2379,http://127.0.0.1:4001"

# Address range to use for services
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

# default admission control policies
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota,DefaultStorageClass"

# Add your own!
KUBE_API_ARGS="--service-account-key-file=/etc/kubernetes/serviceaccount.key --tls-cert-file=/etc/kubernetes/apiserver.crt --tls-private-key-file=/etc/kubernetes/apiserver.key --client-ca-file=/etc/kubernetes/ca.crt"

**Comment by liggitt** [comment]
That means a client is attempting to connect to the secured port with http protocol instead of https. Check the connection configuration files (kubeconfig files) to make sure https://… is used

/close
