### ISSUE TITLE
Can not change containerport with deployment

### ISSUE THREAD

**Issue by parkjunhyo** [kubernetes/kubernetes#78152]
Please give some of Idea 

My environments are like below
- Ubuntu 16.04
- kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

I want to create kubernetes container for "httpd:lastest". I tried 2 ways for this.
1)
kubectl run crenet-fronts-deployment --image=httpd:latest --port=8080 --replicas=3
kubectl expose deployment crenet-fronts-deployment --type=LoadBalancer --name=crenet-fronts-lb
2)
kubectl apply -f httpd-deployment.yaml
----- httpd-deployment.yaml -------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crenet-fronts-deployment
  labels:
    app: crenet-fronts-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: crenet-front
  template:
    metadata:
      labels:
        app: crenet-front
    spec:
      containers:
      - name: front-container
        image: httpd:latest
        ports:
        - containerPort: 8080

after then, I check the container network status on worker.
ip netns exec 927391647cb9 netstat -anput
------------------ result ------------------------------
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      18342/httpd

also I tried "kubectl describe deployments"
----------------------- I checked this result --------------------
Pod Template:
  Labels:  app=crenet-front
  Containers:
   front-container:
    Image:        httpd:latest
    Port:         8080/TCP

This is the issue. The real container works on "80" port, not "8080" which I want to.
Please let me know how to change this work correctly.

/sig network
/sig scheduling

**Comment by Coderhypo** [comment]
You may need to check httpd config file，and make sure its listen 80

**Comment by saiyan86** [comment]
You should redirect the traffic to port 80(assuming your pod is listening on port 80).

Please try below command instead.
```
kubectl run crenet-fronts-deployment --image=httpd:latest --port=8080 --target-port=80 --replicas=3
```

**Comment by parkjunhyo** [comment]
@Coderhypo 

Thanks. I changed httpd conf in /var/lib/docker/overlay2/something/usr/local/apache2/htdocs/httpd.conf

after then, I restart container "docker container restart". I checked the listen port and it was changed.

**Comment by parkjunhyo** [comment]
@saiyan86 

I solved above issue with above answer.
