### ISSUE TITLE
Unknown object type "nil" in Secret.data.redis-password

### ISSUE THREAD

**Issue by rkumar1609** [kubernetes/kubernetes#78167]
I have a tool which is now available to be deployed on Kubernetes.  A Know person made a document on getithub where he asked to run two power shell files.
https://github.com/tonikautto/qse-kubernetes-minikube

When I run first file 0-install-tools.ps1 it install tools like virtualbox, minikube, helm and kubernetes-cli.

When I run second file 1-Deploy-Minikube.ps1 it is getting failed on last step where it is executing:

helm install -n qliksense qlik/qliksense -f values.yaml

The person who has created the getithub doc on the same has run it successful but am not sure why it is failing at my windows10 machine.

Following error I am getting:
 error validating data: unknown object type "nil" in Secret.data.redis-password

Can you please help me to know why it is failing at my side or there is some problem with the version these powershell files are installing ? 

Hardware: 3 core and 8 GB RAM.

I am hoping a positive response from your team.

Thanks,
Rohit

**Comment by dblencowe** [comment]
Also seeing this issue after upgrading to the latest version of Helm. @rkumar1609 I think this might be a problem with Helm parsing Values than with k8s.

**Comment by rkumar1609** [comment]
Thanks for your response sir.
Can you please help me to fix it? I am new in kubernetes, I need help to fix it.

Thanks,
Rohit

**Comment by draveness** [comment]
Hi @rkumar1609, would you mind to close this issue since it is not a kubernetes problem? :)

**Comment by rkumar1609** [comment]
@draveness Can you please help me to know how to downgrade helm version is its issue of helm ?

I am writing down the steps how I installed it, can you please help me to install right version of helm

#Requires -RunAsAdministrator

# Install Chocolatey package manager
# Reference https://chocolatey.org/install
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Virtual box
choco install virtualbox --yes

# Minikube
choco install minikube --yes

# Kubectl
choco install kubernetes-cli --yes

# Helm
choco install kubernetes-helm --yes 


Thanks,
Rohit

**Comment by rkumar1609** [comment]
Dear Draveness,

I have downgraded HELM by command #choco install kubernetes-helm --version 2.13.1 --yes --force

but still same issue is occurring. I have received the message of successful downgrade of HELM but nothing help after it.

More details in below link

https://community.qlik.com/t5/Qlik-Sense-Multi-Cloud/Error-while-Installing-Qlik-Sense-in-Kubernetes/m-p/1589721#M102  

Can anyone help me how to fix this issue so I can move forward.

Thanks in advance,
Rohit

**Comment by draveness** [comment]
> Dear Draveness,
> 
> I have downgraded HELM by command #choco install kubernetes-helm --version 2.13.1 --yes --force
> 
> but still same issue is occurring. I have received the message of successful downgrade of HELM but nothing help after it.
> 
> More details in below link
> 
> https://community.qlik.com/t5/Qlik-Sense-Multi-Cloud/Error-while-Installing-Qlik-Sense-in-Kubernetes/m-p/1589721#M102
> 
> Can anyone help me how to fix this issue so I can move forward.
> 
> Thanks in advance,
> Rohit

It doesn't seem like a problem with kubernetes, and maybe you could find the support of qilk sense.

**Comment by rkumar1609** [comment]
Dear draveness

Qlik Sense people are saying it is from Kubernetes. 

Thanks,
Rohit

**Comment by rkumar1609** [comment]
Dear Draveness,

It could be the problem of HELM instead of Kubernetes, but not of Qlik for sure.

Thanks,
Rohit

**Comment by rkumar1609** [comment]
I had words with Qlik people they are saying its from HELM side
