### ISSUE TITLE
Stop ignoring SC1090 warnings in verify-shellscript.sh

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/kubernetes#78168]
Source directives tell shellcheck where to find shellscripts that are invoked dynamically using bash VARIABLEs in paths that cannot be determined at the time shellcheck is invoked.

Shellcheck directives are specially formatted script comments see [https://github.com/koalaman/shellcheck/wiki/Directive](https://github.com/koalaman/shellcheck/wiki/Directive)

The source directive is documented here [SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090)

**Comment by alisondy** [comment]
Make list in issue, so we can break the work up potentially

**Comment by RobertKielty** [comment]
So the part of list of other scripts that are now broken by no ignoring in ability to follow source are detailed here (from CI)

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78171/pull-kubernetes-verify/1131160750551732224
