### ISSUE TITLE
fail to get e2e test utils

### ISSUE THREAD

**Issue by hoyho** [kubernetes/kubernetes#78165]
**What happened**:
I'm following the instruction [e2e_test](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#building-kubernetes-and-running-the-tests)

`go get -u k8s.io/test-infra/kubetest`

```bash
[root@localhost kubernetes]#
[root@localhost kubernetes]# go get -u k8s.io/test-infra/kubetest
go: finding modernc.org/golex v1.0.0
go: finding modernc.org/mathutil v1.0.0
go: finding modernc.org/strutil v1.0.0
go: finding modernc.org/xc v1.0.0
go: finding modernc.org/cc v1.0.0
go: modernc.org/mathutil@v1.0.0: git fetch -f https://gitlab.com/cznic/mathutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/fb72eb2422fda47ac75ca695d44b06b82f3df3c5308e271486fca5e320879130: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/xc@v1.0.0: git fetch -f https://gitlab.com/cznic/xc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/29fc2f846f24ce3630fdd4abfc664927c4ad22f98a3589050facafa0991faada: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/strutil@v1.0.0: git fetch -f https://gitlab.com/cznic/strutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/golex@v1.0.0: git fetch -f https://gitlab.com/cznic/golex refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/9aae2d4c6ee72eb1c6b65f7a51a0482327c927783dea53d4058803094c9d8039: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/cc@v1.0.0: git fetch -f https://gitlab.com/cznic/cc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/3dac616a9d80602010c4792ef9c0e9d9812a1be8e70453e437e9792978075db6: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: error loading module requirements
[root@localhost kubernetes]# curl https://gitlab.com/cznic/golex
<!DOCTYPE html>
<html class="" lang="en">
<head prefix="og: http://ogp.me/ns#">
<meta charset="utf-8">
<link href="https://assets.gitlab-static.net" rel="dns-prefetch">
...
```

**What you expected to happen**:
get kubetest successful

**How to reproduce it (as minimally and precisely as possible)**:
1. prepare a new VM
2. git clone kubernetes
3. run `go get -u k8s.io/test-infra/kubetest` or  `go run hack/e2e.go  # from kubernetes/kubernetes`

**Anything else we need to know?**:
I thought it is caused by network? but running ` curl https://gitlab.com/cznic/golex` is fine
so I have no idea

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux vm44 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by hoyho** [comment]
area/test  
/area/test-infra

**Comment by YoubingLi** [comment]
@hoyho 

   You can manually clone each repository, then copy the content from .git directory to the destination place.

    I ever posted in kubernetes-dev channels.

**Comment by YoubingLi** [comment]
![image](https://user-images.githubusercontent.com/43125723/58685981-0e5d7780-83b0-11e9-86e4-fc4336e23e1a.png)

**Comment by hoyho** [comment]
> @hoyho
> 
> You can manually clone each repository, then copy the content from .git directory to the destination place.
> 
> ```
> I ever posted in kubernetes-dev channels.
> ```
@YoubingLi 
Can you post related chat history here.
Do you have a better solution? I solve it  by coping desired files from my previous development
for example:
```bash
# vm1 is a my previous virtual machine that have a configured environment
# vm2 is my new machine
ssh vm1
scp -r /root/go/pkg/mod/cache/vcs/9aae2d4c6ee72eb1c6b65f7a51a0482327c927783dea53d4058803094c9d8039  vm2:/root/go/pkg/mod/cache/vcs/
# continue to copy others ...

```

I hope there's some elegant way ..

**Comment by YoubingLi** [comment]
@hoyho

   I don't have a good solution.

  It is the problem of server that doesn't response "git fetch -f https://gitlab.com/cznic/mathutil".

  The following command works
       git fetch -f https://gitlab.com/cznic/mathutil.git

**Comment by YoubingLi** [comment]
@hoyho

   The issue is gone after I upgraded my git version to "2.22.0.rc2".

   You can try it.
