### ISSUE TITLE
How to find out whether a pod belongs to statefulset/deployment/replica-set

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubernetes#78181]
how can I use kubenetes client-sdk to figure out whether a **pod** belongs to **statefulset/deployment/replica-set**?

the same issue as [this](https://github.com/kubernetes/kubernetes/issues/32051), but that method does not work, also `kubectl describe pod` is not the same as` kubectl get pods`

What I can find is, for a pod belong to a high-level controller, it will have `metadata.generateName `and `metadata.ownerReferences`. Unfortunately, it is not supported via `Field Selectors`.

So how can I filter it out?

**Comment by zq-david-wang** [comment]
I would use selector(pod's label) to retrieve all relevant replica set(kind field from pod's owner reference), and then use owner reference to further narrow it down

**Comment by yue9944882** [comment]
https://github.com/kubernetes/kubernetes/blob/1c100619671dfaffe09f555a67bd9c43099f12ed/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L315-L319

the in-tree fields from `metadata.ownerReferences` will help

**Comment by Cherishty** [comment]
> https://github.com/kubernetes/kubernetes/blob/1c100619671dfaffe09f555a67bd9c43099f12ed/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L315-L319
> 
> the in-tree fields from `metadata.ownerReferences` will help

Yes, this is what I described in last post, but how can I filter it via **k8s pysdk**, or only have to list all pod and resolve it by myself?

**Comment by yue9944882** [comment]
> or only have to list all pod and resolve it by myself?

sadly, yes. the good news is that we can do pagination so that list chunks won't jam the traffic.

**Comment by YoubingLi** [comment]
Pod has UID attribute.

If the pod belongs to other object such as Job, Deployment, statefulset, the "controller-uid" is set in Pod's Labels.

You can check these 2 fields. 

   func getPodControlID(pod *corev1.Pod) string {

        if pod.Labels == nil {
                return string(pod.UID)
        } else {
                uuid, ok := pod.Labels["controller-uid"]
                if ok { 
                        return uuid
                } else {
                        return string(pod.UID)
                }
        }
}
