### ISSUE TITLE
build kubectl or other binaries from container

### ISSUE THREAD

**Issue by figo** [kubernetes/kubernetes#78195]
**What would you like to be added**:
add the capability of build binaries (e.x kubectl) from container for platforms like darwin/amd64, windows/amd64

**Why is this needed**:
the way we build darwin/windows kubectl today is to run following command:
```
make WHAT=cmd/kubectl KUBE_BUILD_PLATFORMS="darwin/amd64 windows/amd64"
```
it directly compiling from the host, make its hard to work consistently cross hosts.
instead, if we can compile from container, it will solve the portability problem.

/sig release

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/pull/78196#issuecomment-494704629
