### ISSUE TITLE
kube-scheduler's performance looks bad

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#78208]
**What happened**:
I have a 5000 node cluster, and 55000+ pods have already been running in this cluster. 25000 of them are managed by 1000 deployments. Then I did some test to know about the scheduler performance, I found that the qps was always 15+ pods/sec and scheduler only consume, at most, 2 of 32 cores. The qps will not increase when I do rolling update against more deployments, instead, there are lots of pods are pending.
Also, I observed there are lots of trace log while doing rolling update.
```
I0509 09:33:38.051328       1 trace.go:76] Trace[1260452793]: "Scheduling test-namespace/test-deploy-7d6f9d6f97-294mh" (started: 2019-05-09 09:33:37.921340778 +0000 UTC m=+100851.375269575) (total time: 129.959068ms):
Trace[1260452793]: [2.552365ms] [2.552365ms] Computing predicates
Trace[1260452793]: [46.367012ms] [43.814647ms] Prioritizing
Trace[1260452793]: [129.932795ms] [83.565783ms] Selecting host
Trace[1260452793]: [129.959068ms] [26.273µs] END
```
![image](https://user-images.githubusercontent.com/4256175/58158037-3102d880-7cac-11e9-88b4-cc3d6bcdd142.png)
![image](https://user-images.githubusercontent.com/4256175/58158076-47109900-7cac-11e9-848e-2604994d101c.png)

**What you expected to happen**:

1. scheduler should consume more cpus.
2. qps should be a large value. (I don't know, may be 100 pods/sec)

**How to reproduce it (as minimally and precisely as possible)**:
Doing rolling update concurrently.

**Anything else we need to know?**:
All pod have 3 labels.
**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.4
- Cloud provider or hardware configuration: 32 core & 128 gb memory & 5000 node cluster
- OS (e.g: `cat /etc/os-release`): v3.3.11
- Kernel (e.g. `uname -a`): 4.18.8-1.el7.elrepo.x86_64
- Install tools: kubeadm & ansible
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
In PrioritizeNodes:
```
	workqueue.ParallelizeUntil(context.TODO(), 16, len(nodes), func(index int) {
```
It seems the number of workers can be increased for higher parallelism.

**Comment by tedyu** [comment]
The additional traces from #78218 would give us more idea what to optimize.

**Comment by tedyu** [comment]
The following change would skip Reduce if Map hasn't run:
```
        for i := range priorityConfigs {
+               if priorityConfigs[i].Function != nil {
+                       continue
+               }
                if priorityConfigs[i].Reduce == nil {
                        continue
                }
```
generic_scheduler_test passes with the above.

**Comment by tedyu** [comment]
```
	if len(errs) != 0 {
		return schedulerapi.HostPriorityList{}, errors.NewAggregate(errs)
```
Currently all the errors are aggregated.
If we don't need all the errors, Function / Map / Reduce func can return early if errs becomes non-empty.

**Comment by misterikkit** [comment]
> Currently all the errors are aggregated.

Scheduler has a policy field `AlwaysCheckAllPredicates` specifically to control this.

**Comment by misterikkit** [comment]
@sevensees Thanks for raising this. In our CI, [we are able to hit 100 pods/s on a 5000 node cluster](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput).

I would like to understand how your setup differs from the test environment. Possibly there is some configuration that would get you higher performance, or some way we can make our test more realistic.

Some random questions:
- is the scheduler pod running with a CPU limit?
- are you using podAntiAffinity rules?
- have you set `PercentageOfNodesToScore` in your scheduler config?

**Comment by tedyu** [comment]
bq. Scheduler has a policy field AlwaysCheckAllPredicates
generic_scheduler_test has this check which is not dependent on test.alwaysCheckAllPredicates :
```
			if !reflect.DeepEqual(err, test.wErr) {
				t.Errorf("Unexpected error: %v, expected: %v", err, test.wErr)
			}
```
I want to get your opinion on how the above check should be formulated considering test.alwaysCheckAllPredicates

Thanks

**Comment by misterikkit** [comment]
> I want to get your opinion on how the above check should be formulated considering test.alwaysCheckAllPredicates

Because the test case also provides `test.wErr` the tests are capable of passing with or without `alwaysCheckAllPredicates` set. (They all seem to be passing.)

Taking a look at those tests, I don't think they are exercising that specific behavior very well. (There's plenty of room for increased test quality.)

Anyway, from the sample trace in this issue, it looks like node ranking is taking about twice as long as node filtering. We should probably look there first. If it's not confidential, I'd like to see a sample of pods from your cluster. I'm curious about the resource requests and affinity rules.

**Comment by hex108** [comment]
It seems that the step `Selecting host` took most part of the time(83.565783ms)?  So I think `PercentageOfNodesToScore` that @misterikkit suggests could help.

**Comment by tedyu** [comment]
Currently DefaultPercentageOfNodesToScore is set to 50.

I think for large cluster (> 1000 node), the default should be lowered (to 30% e.g.).

**Comment by Huang-Wei** [comment]
@sevensees Thanks for raising this issue. In addition to @misterikkit 's questions on how your cluster is setup, I do want to know:

1. What's the spec of your machines?
2. Which metrics you're using to measure the "pod scheduling time"?
3. How do you setup the workloads? Did you refer to https://github.com/kubernetes/perf-tests/tree/master/clusterloader2?

**Comment by sevensees** [comment]
@misterikkit @Huang-Wei Thank you guys for your attention. I applied the most of the default configuration except `--profiling=true` for debugging and `--leader-elect=true` for HA.

> Some random questions:
> 
> * is the scheduler pod running with a CPU limit?
> * are you using podAntiAffinity rules?
> * have you set `PercentageOfNodesToScore` in your scheduler config?

@misterikkit 

- No CPU limit, only `100m` CPU request assigned. The scheduler pod can consume CPU as much as it can.
- No. There is no podAntiAffinity in pod spec.
- No. I apply the default `PercentageOfNodesToScore`.

BTW, could you please share the configuration applied in the GCE test?

> @sevensees Thanks for raising this issue. In addition to @misterikkit 's questions on how your cluster is setup, I do want to know:
> 
> 1. What's the spec of your machines?
> 2. Which metrics you're using to measure the "pod scheduling time"?
> 3. How do you setup the workloads? Did you refer to https://github.com/kubernetes/perf-tests/tree/master/clusterloader2?

@Huang-Wei

1. 32 Cores & 128GB memory.
2. I deployed a [slo-monitor](https://github.com/kubernetes/perf-tests/tree/master/slo-monitor) in the cluster to monitor the pod scheduling time.
3. I setup workload by my own. I created 1000 deployments in a test namespace, and all these deployments have different replicas, the most one has 1000 replicas and the least one has 0 replicas. There are totally 25000+ pods in the test namespace. Besides, there are 30000+ system pods running in kube-system namespace. Then I do rolling update against these 1000 deployments concurrently.

**Comment by tedyu** [comment]
bq. Trace[1260452793]: [129.932795ms] [83.565783ms] Selecting host

It seems findMaxScores func took the majority of the time.

**Comment by ahg-g** [comment]
Do we have any logs indicating the number of iterations being made in findMaxScores for this trace?

There are two extreme cases that could make findMaxScores take such a long time: 1) if priorityList in findMaxScores is in reverse score order, then maxScoreIndexes will keep getting reset. 2) if all the nodes have similar score, then basically we are building and returning a large list every time.

I wonder if https://github.com/kubernetes/kubernetes/pull/78009 can help with this.

**Comment by misterikkit** [comment]
> It seems that the step `Selecting host` took most part of the time(83.565783ms)?

The log message is a little misleading. The trace step describes the amount of time since the last call to `Step()`. So we are actually logging the *beginning* of each step. I guess the more sensible thing to do would be to log at the *end* of each step. That would be a good cleanup PR.

**Comment by misterikkit** [comment]
> I wonder if #78009 can help with this.

That PR would save us a bunch of slice allocations in the worst case. (I don't know if the compiler is smart enough to reuse the slice memory when we reset it)

However, per my previous comment, I don't believe selecting the host is taking up 80ms. When we call `trace.Step()` the created step is considered to have a duration equal to `time.Now().Sub(lastStepTime)`.

**Comment by ahg-g** [comment]
> > It seems that the step `Selecting host` took most part of the time(83.565783ms)?
> 
> The log message is a little misleading. The trace step describes the amount of time since the last call to `Step()`. So we are actually logging the _beginning_ of each step. I guess the more sensible thing to do would be to log at the _end_ of each step. That would be a good cleanup PR.

Good catch! Here is the place where a step time is computed and reported: https://github.com/kubernetes/utils/blob/master/trace/trace.go#L70

**Comment by misterikkit** [comment]
https://github.com/kubernetes/utils/pull/93

**Comment by tedyu** [comment]
bq. smart enough to reuse the slice memory

The compiler is able to reuse the memory.

**Comment by hainesc** [comment]
> The compiler is able to reuse the memory.

I write a mocked scheduler and run selectHost(), It show the different addresses are used.

```go
package main
import (
	"fmt"
	"math/rand"
	"time"
	"strconv"
)

func main() {
	rand.Seed(time.Now().UnixNano())
	scheduler := &MockScheduler{}
	// 100 nodes here
	nodes := make([]PriorityHost, 100, 100)
	for i := 0; i < 100; i++ {
		nodes[i].Host = "node" + strconv.Itoa(i)
	}
	// Run five times
	for j := 0; j < 5; j++ {
		// every time, give a random score to each node.
		for i := 0; i < 100; i++ {
			nodes[i].Score = rand.Intn(20)
		}
		selected, err := scheduler.selectHost(nodes)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Printf("selected is %s\n", selected)
	}
}

type MockScheduler struct {
	lastNodeIndex uint64
}

type PriorityHost struct {
	Host string
	Score int
}

type PriorityList []PriorityHost

func (m *MockScheduler) selectHost(priorityList PriorityList) (string, error) {
	if len(priorityList) == 0 {
		return "", fmt.Errorf("empty list")
	} 
	maxScores := findMaxScores(priorityList)
	// Important!!! show the address of maxScores
	fmt.Printf("The address of maxScore is %p\n", &maxScores)
	ix := int(m.lastNodeIndex % uint64(len(maxScores)))
	m.lastNodeIndex++
	return priorityList[maxScores[ix]].Host, nil
}

func findMaxScores(priorityList PriorityList) []int {
	maxScoreIndexes := make([]int, 0, len(priorityList)/2)
	maxScore := priorityList[0].Score
	for i, hp := range priorityList {
		if hp.Score > maxScore {
			maxScore = hp.Score
			maxScoreIndexes = maxScoreIndexes[:0]
			maxScoreIndexes = append(maxScoreIndexes, i)
		} else if hp.Score == maxScore {
			maxScoreIndexes = append(maxScoreIndexes, i)
		}
	}
	return maxScoreIndexes
}
```

Environment: go version go1.12.1 darwin/amd64

**Comment by tedyu** [comment]
By 'reuse', I meant that space of the slice is reused:
```
package main

import (
	"fmt"
)

func main() {
	nodes := make([]int, 100, 100)
	nodes[0] = 3
	nodes[1] = 4
	fmt.Printf("%p\n", &nodes)
	nodes = nodes[:0]
	fmt.Printf("%p\n", &nodes)
	nodes = append(nodes, 5)
	fmt.Printf("%p", &nodes)
}
```
You can see the same address is printed.

**Comment by tedyu** [comment]
What @hainesc observed was due to this line:
```
	maxScoreIndexes := make([]int, 0, len(priorityList)/2)
```
The above is allocation, leading to different maxScore address.

**Comment by hainesc** [comment]
Sorry for I misunderstood that.

Yes, Inner the function `findMaxScores`, the slice is reused.

**Comment by sevensees** [comment]
> > It seems that the step `Selecting host` took most part of the time(83.565783ms)?
> 
> The log message is a little misleading. The trace step describes the amount of time since the last call to `Step()`. So we are actually logging the _beginning_ of each step. I guess the more sensible thing to do would be to log at the _end_ of each step. That would be a good cleanup PR.

So, It is the `Prioritizing` step that took most of the time.

**Comment by tedyu** [comment]
@sevensees 
How many extenders are used in your deployment ?

**Comment by sevensees** [comment]
> @sevensees
> How many extenders are used in your deployment ?

Sorry, what do you mean by `extenders`? Do you mean `replicas`? If so, The replicas are different for different deployments, and the most one has 1000 replicas.

**Comment by tedyu** [comment]
```
// SchedulerExtender is an interface for external processes to influence scheduling
// decisions made by Kubernetes. This is typically needed for resources not directly
// managed by Kubernetes.
type SchedulerExtender interface {
```

**Comment by sevensees** [comment]
> ```
> // SchedulerExtender is an interface for external processes to influence scheduling
> // decisions made by Kubernetes. This is typically needed for resources not directly
> // managed by Kubernetes.
> type SchedulerExtender interface {
> ```

I see, I did not apply any SchedulerExtender in deployment.

**Comment by warmchang** [comment]
Is 16 a magic number or an experience value?
https://github.com/kubernetes/kubernetes/blob/23eb2180c65472f5c25fdec551b594f0b2db427d/pkg/scheduler/algorithm/predicates/metadata.go#L488

**Comment by ahg-g** [comment]
/close

Lots of improvements made since then
