### ISSUE TITLE
kubectl cp fails on symlinks

### ISSUE THREAD

**Issue by phil9909** [kubernetes/kubernetes#78211]
**What happened**:
`kubectl cp` prints error message and exits when copying to symlinked folder when given as an absolute path.

**What you expected to happen**:
`kubectl cp` follows the symlink and stores the file(s) there.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
# create a dummy pod
kubectl run dummy --generator=run-pod/v1 --image=ubuntu --command -- sleep 99999

# create a working directory
mkdir tmp
cd tmp

# create a dummy file and copy to pod
touch some_file
kubectl cp -c dummy some_file default/dummy:some_file

# create an empty directory and a symlink
mkdir directory
ln -s directory link
```

```bash
# works:
kubectl cp -c dummy default/dummy:some_file directory/some_file
kubectl cp -c dummy default/dummy:some_file link/some_file
kubectl cp -c dummy default/dummy:some_file ${PWD}/directory/some_file

# does not work:
kubectl cp -c dummy default/dummy:some_file ${PWD}/link/some_file
```

Error message:
`warning: link "[...]/tmp/link/some_file" is pointing to "" which is outside target destination, skipping`

**Anything else we need to know?**:
- Works when using kubectl 1.14.1 and was introduced with 7962231a8074eca544701b875cb52dcc4429903c
- Can be patched like this:
 ```patch
diff --git a/pkg/kubectl/cmd/cp/cp.go b/pkg/kubectl/cmd/cp/cp.go
index 02612e0671..e4d839f12a 100644
--- a/pkg/kubectl/cmd/cp/cp.go
+++ b/pkg/kubectl/cmd/cp/cp.go
@@ -459,7 +459,7 @@ func (o *CopyOptions) untarAll(reader io.Reader, destDir, prefix string) error {
                }
                // For scrutiny we verify both the actual destination as well as we follow
                // all the links that might lead outside of the destination directory.
-               if !isDestRelative(destDir, destFileName) || !isDestRelative(destDir, filepath.Join(evaledPath, file)) {
+               if !isDestRelative(destDir, destFileName) || !isDestRelative(evaledPath, filepath.Join(evaledPath, file)) {
                        fmt.Fprintf(o.IOStreams.ErrOut, "warning: link %q is pointing to %q which is outside target destination, skipping\n", destFileName, header.Linkname)
                        continue
                }
 ```
which should be the correct behaviour, if I understood this correctly.

**Environment**:
- Kubernetes version (use `kubectl version`): ```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}```
- Cloud provider or hardware configuration:
Gardener Cluster on AWS
- OS (e.g: `cat /etc/os-release`):
`macOS 10.14.5`
- Kernel (e.g. `uname -a`):
`Darwin DGKX3HEDJ1GP 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64 i386 iMac18,3 Darwin`

**Comment by phil9909** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
/assign @soltysh 

it might be clearer to resolve any symlinks in the specified destination path as an initial step, and leave the untar traversal detection code as-is

**Comment by pswica** [comment]
I agree with @liggitt . I fixed this in my previous PR that fixes `kubectl cp` when copying directly to a directory.
