### ISSUE TITLE
ResourceQuotas stop refreshing

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes/kubernetes#78217]
**What happened**:
Quotas within a namespace stopped refreshing when pods were deleted or deployments scaled. ResourceQuotas within the namespace also couldn't be edited. 

**What you expected to happen**:
ResourceQuotas for a namespace are updated as pods are scaled or created.

**How to reproduce it (as minimally and precisely as possible)**:
Unable to reproduce exactly. It appears to have occurred during a restart of the kube-apiserver. The quotas weren't able to update until each kube-controller was restarted. 
**Anything else we need to know?**:
Appears related to https://github.com/kubernetes/kubernetes/issues/71450 which was closed. 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 4.20.7-1.el7.elrepo.x86_64 #1 SMP Wed Feb 6 13:17:46 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
#71450 was resolved in 1.15 in https://github.com/kubernetes/kubernetes/pull/74747

**Comment by liggitt** [comment]
without more reproducible steps, this will be difficult to address. do you have controller manager logs from the relevant period?

**Comment by liggitt** [comment]
for lack of additional information, closing as addressed by #74747
