### ISSUE TITLE
GET /api/v1/componentstatuses does not respect labelSelector

### ISSUE THREAD

**Issue by alewitt2** [kubernetes/kubernetes#78214]
**What happened**: tried to get listing of all componentstatuses using a labelSelector query selector. I am hitting the apiServer directly. GET /api/v1/componentstatuses

**What you expected to happen**: GET /api/v1/componentstatuses with labelSelector should limit responses to only componentstatuses with the specified label

**How to reproduce it (as minimally and precisely as possible)**: run GET /api/v1/componentstatuses with and without a labelSelector against the apiServer.

**Anything else we need to know?**: specifically my label selector is in the form `mylabel=myvalue`. and i can confirm everything works as expected when i hit GET /api/v1/pods

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: IBM
- OS (e.g: `cat /etc/os-release`): Mac
- Kernel (e.g. `uname -a`): Darwin Kernel Version 18.5.0
- Install tools: Using javascript npm request to talk to api server
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by alewitt2** [comment]
@kubernetes/sig-api-machinery-bug

**Comment by alewitt2** [comment]
i assume its because you cant add a label to componentstatus, but they still shouldnt return if i specify a labelSelector

**Comment by yue9944882** [comment]
that's indeed a bug i presume. but what use-case makes you label-querying componentstatus?

**Comment by alewitt2** [comment]
we have a bot to periodically run a query that finds all known endpoints on the ApiServer. Then for each of the found endpoints, find all resources with our label defined. sort of an inventory tracking system. https://github.com/razee-io/Watch-keeper

**Comment by alewitt2** [comment]
in a similar vein, the endpoint `/apis/metrics.k8s.io/v1beta1` doesnt seem to respect `fieldSelector: metadata.namespace==xyz` 

```{ name: 'pods',
          singularName: '',
          namespaced: true,
          kind: 'PodMetrics',
          verbs: [ 'get', 'list' ] }```

**Comment by 11janci** [comment]
I will take a look at this unless no objections

**Comment by yue9944882** [comment]
@11janci thank you, yours!

**Comment by 11janci** [comment]
@yue9944882 @royc added a PR for the ComponentStatus API, could you pls kindly take a look? I will look into the metrics API probably over the weekend. Thanks
