### ISSUE TITLE
kubetest failed ,density.go:554 report error

### ISSUE THREAD

**Issue by Yzerost** [kubernetes/kubernetes#78228]
**What happened**:
run kubetest with：
kubetest --test  --provider=local --test_args="--host=https://172.16.152.101:8443 --ginkgo.focus=\[Feature:Performance\]" >> logs/log.txt
,failed and report error below:

**May 22 19:35:35.302: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
May 22 19:35:35.421: INFO: namespace: e2e-tests-density-8b5nw, resource: bindings, ignored listing per whitelist
May 22 19:35:35.701: INFO: namespace e2e-tests-density-8b5nw deletion completed in 10.425428482s

• Failure in Spec Setup (BeforeEach) [16.530 seconds]
[sig-scalability] Density
/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scalability/framework.go:22
  [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons [BeforeEach]
  /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:554

  Expected error:
      <*errors.errorString | 0xc421cfbb40>: {
          s: "Unexpected response: \"\"",
      }
      Unexpected response: ""
  not to have occurred

  /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:470**
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSMay 22 19:35:35.704: INFO: Running AfterSuite actions on all node
May 22 19:35:35.704: INFO: Running AfterSuite actions on node 1

Summarizing 1 Failure:

[Fail] [sig-scalability] Density [BeforeEach] [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons
/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:470

Ran 2 of 998 Specs in 308.891 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 996 Skipped --- FAIL: TestE2E (308.95s)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (v1.11.0,installed in okd):
- Cloud provider or hardware configuration:
- OS (centos7):
- Kernel (e.g. Linux x86_64):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chiragrk** [comment]
I seem to hitting the exact same error:

minikube --vm-driver=none start  --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

kubetest --provider=local --test --test_args="--host=https://localhost:8443 --ginkgo.focus=\[Feature:Performance\]"

logs:
--------
W0618 08:44:07.163354   17440 metrics_grabber.go:79] Master node is not registered. Grabbing metrics from Scheduler, ControllerManager and ClusterAutoscaler is disabled.
Jun 18 08:44:07.179: INFO:
Latency metrics for node minikube
Jun 18 08:44:07.179: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "density-8532" for this suite. 
Jun 18 08:44:13.186: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
Jun 18 08:44:13.237: INFO: namespace density-8532 deletion completed in 6.05646383s

• Failure in Spec Setup (BeforeEach) [6.125 seconds]
[sig-scalability] Density
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/framework.go:22
  [Feature:Performance] should allow starting 30 pods per node using ReplicationController with 0 secrets, 0 configmaps, 0 token projections, and 0 daemons [BeforeEach]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:607

  Unexpected error:
      <*errors.errorString | 0xc0023a64e0>: {
          s: "Unexpected response: \"\"",
      }
      Unexpected response: ""
  occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/density.go:515
------------------------------


kubectl version 
-----------------
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
root@sc2-nsbu-cqe-dhcp-51-137:~# 


lsb_release -a
-------------------
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Is there anyway I can debug this further?
