### ISSUE TITLE
Move `GetPodPriority` into a common library

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#78220]
**What would you like to be added**:

The `GetPodPriority` function should be moved out of `pkg/scheduler` and into a common library where components can use it without importing scheduler code.

**Why is this needed**:

In #76990 we removed a dependency between kubelet and scheduler by copying a small helper function. We would prefer to have only one copy of this function, but it would need a home outside of `pkg/scheduler` and `pkg/kubelet`

This package seems like a reasonable place: `k8s.io/kubernetes/pkg/apis/scheduling`

```go
func getPodPriority(pod *v1.Pod) int32 {
	if pod.Spec.Priority != nil {
		return *pod.Spec.Priority
	}
	// When priority of a running pod is nil, it means it was created at a time
	// that there was no global default priority class and the priority class
	// name of the pod was empty. So, we resolve to the static default priority.
	return scheduling.DefaultPriorityWhenNoDefaultClassExists
}
```

/sig scheduling
/help
/good-first-issue

**Comment by dpandhi-git** [comment]
Can I take this?

**Comment by misterikkit** [comment]
@Deepika sounds good to me. (:

>

**Comment by dpandhi-git** [comment]
@misterikkit I am planning to add the function and its test in helpers.go/helpers_test.go from k8s.io/kubernetes/pkg/apis/scheduling. Let me know your thoughts?

**Comment by draveness** [comment]
Hi @dpandhi-git, are you still working on this issue, do you mind if I start to work on this one?

**Comment by tedyu** [comment]
I only found one copy in pkg/api/v1/pod/util.go

**Comment by ahg-g** [comment]
yeah, this has been addressed.

/close
