### ISSUE TITLE
ScaleClient should accept full group/version/resource

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#78231]
**What would you like to be added**:
Additional functions on the ScaleClient interface that accepts full group/version/resource instead of just group/resource.

**Why is this needed**:
The ScaleClient currently accept GroupResource and then uses an internal restmapper to look up the versions. In some situations we already have the full group/version/resource and it should be possible to use it directly and avoid extra lookups in the client.
Ref discussion in #76294 

/sig api-machinery

**Comment by yue9944882** [comment]
the point of accepting `GroupResource` here is to use the server-preferred version.
