### ISSUE TITLE
How is globalTimeout handled when draining a node

### ISSUE THREAD

**Issue by ggaurav10** [kubernetes/kubernetes#78236]
When draining a node, `evictPods()` is called. It is supposed to wait for duration `globalTimeout` for evicting all the pods.
https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/kubectl/cmd/drain.go#L534
If the each of the pods take different times to be evicted, then the timeout timer starts again from 0 because of `for`-ever loop.

**What you expected to happen**:
After `globalTimout` duration has passed, expected to see log message: `Drain did not complete within ...` regardless of pods taking time to evict.

**Comment by mattjmcnaughton** [comment]
/assign @mattjmcnaughton

Great  catch - putting out pr to fix rn.

**Comment by mattjmcnaughton** [comment]
Actually, this is already fixed in master. It looks like your link is to release 1.8. The most recent release is 1.14 :)

Here's the [pr which fixed it](https://github.com/kubernetes/kubernetes/pull/64378).


/unassign @mattjmcnaughton 

Mind closing this issue? Thanks :)

**Comment by ggaurav10** [comment]
Thanks :)
