### ISSUE TITLE
PreconfiguredRuntimeHandler e2e test fails in pull-kubernetes-e2e-containerd-gce CI job

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#78249]
Failure from a test PR - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/78221/pull-kubernetes-e2e-containerd-gce/1131363976186171392/build-log.txt

```
I0523 01:36:21.321] [91m[1mâ€¢ Failure [344.849 seconds][0m
I0523 01:36:21.321] [sig-node] RuntimeClass
I0523 01:36:21.321] [90mtest/e2e/common/runtimeclass.go:43[0m
I0523 01:36:21.321]   [91m[1mshould run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler] [It][0m
I0523 01:36:21.322]   [90mtest/e2e/common/runtimeclass.go:60[0m
I0523 01:36:21.322] 
I0523 01:36:21.322]   [91mUnexpected error:
I0523 01:36:21.322]       <*errors.errorString | 0xc001f92140>: {
I0523 01:36:21.322]           s: "Gave up after waiting 5m0s for pod \"test-runtimeclass-runtimeclass-5268-preconfigured-handler-gxvrf\" to be \"success or failure\"",
I0523 01:36:21.322]       }
I0523 01:36:21.322]       Gave up after waiting 5m0s for pod "test-runtimeclass-runtimeclass-5268-preconfigured-handler-gxvrf" to be "success or failure"
I0523 01:36:21.322]   occurred[0m
I0523 01:36:21.322] 
I0523 01:36:21.322]   test/e2e/common/runtimeclass.go:127```

**Comment by dims** [comment]
cc @Random-Liu 

Tim, Lantao,
Looks like we are not setting up a `test-handler` like we used to in this other CI job:
https://github.com/containerd/cri/blob/master/cluster/gce/configure.sh#L189-L198

and the test does not fail on docker based jobs as we [skip](https://github.com/kubernetes/kubernetes/blob/d15718cb1c48b0e6175c616e022ada923ff549d9/test/e2e/common/runtimeclass.go#L61-L62) it:
```
		// The built-in docker runtime does not support configuring runtime handlers.
		framework.SkipIfContainerRuntimeIs("docker")
```

So, what do we want to do here? choices are
- add `test-handler` in kube-up.sh
- detect preconfigured somehow and run or skip test using that instead of just skipping for docker
- skip `NodeFeature:*` for this job.

What is the best way to go ahead? 

Once we fix this, we can enable this job on all pre-submits (hurray!)

**Comment by tallclair** [comment]
Thanks for debugging it. My vote would be to add the test-handler, similar to what we do for the node test.

**Comment by BenTheElder** [comment]
I understand the logistics are a bit problematic here but I think it's weird that we just skip for docker and if you're not using docker we fail if you haven't set up a magical seemingly undocumented test-handler.

Every new cluster setup tool that is on CRI that we use to test is going to need to figure this out and add the magical handler, which is a bit unfortunate. I'm not sure what the best solution is though...
