### ISSUE TITLE
minikube start error with same IP of VM in VirtualBox.

### ISSUE THREAD

**Issue by umi0410** [kubernetes/kubernetes#78241]
**What would you like to be added**: 
This is a screencapture of the error message.
![error message](https://t1.daumcdn.net/cfile/tistory/99719A435CE60CF22B)
I think it will be better if the feedback for the error is modified in a more detailed way.
Like appending some lines like theses.
"Try opening virtualbox, click Global Tools - Host Network Manager, and check out if there are network adapters which use the same IP.
Then remove an adapter which has the same IP or change the IP not to be the same."

![error virtualbox](https://t1.daumcdn.net/cfile/tistory/997C323E5CE649961A)
This image is the case when the error occurs.

**Why is this needed**:
This is the screencapture of the error message but I, as a bigginer of Kubernetes and virtualbox, wasn't able to how I can handle the IP error.
I didn't know how to handle the network adapter of VMs from virtualbox and why they became to have the same IP. 

I think you are aware of why the error occurs ( because of the apapters that have the same IP )
but users are not familiar with what the host-only adapters and how to deal with them. So if you append some kind of detailed explanations for the error, it would be great Thank you.

**Comment by umi0410** [comment]
`/sig API Machinery`

**Comment by umi0410** [comment]
`/sig api-machinery`

**Comment by yue9944882** [comment]
sounds like a minikube issue, do you consider transferring the issue to [another repo](https://github.com/kubernetes/minikube)?
