### ISSUE TITLE
kubectl apply deployment doesn't update the existing one and creates a new one

### ISSUE THREAD

**Issue by yelhouti** [kubernetes/kubernetes#78253]
**What happened**:
kubectl apply deployment doesn't update the existing one and created a new one
**What you expected to happen**:
kubectl apply updated deployments the same way it does for services...
**How to reproduce it (as minimally and precisely as possible)**:
have deployment.yml file
kubectl apply -f deployment.yml
edit the file
kubectl apply -f deployment.yml

**Anything else we need to know?**:

**Environment**:
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Cloud provider or hardware configuration:
Bare Metal: (1 test server) Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz, 8 cores 32 Go of RAM
OS (e.g: cat /etc/os-release): Centos 7
Kernel (e.g. uname -a): 4.20.14-100.fc28.x86_64
Install tools: Kubespray

**Comment by yelhouti** [comment]
@kubernetes/sig-cli-bug

**Comment by liggitt** [comment]
does your deployment manifest specify a name or a generateName?

**Comment by yelhouti** [comment]
@liggitt thanks for your ansewer, it does specify a name:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myAppName
spec: ...
```

**Comment by liggitt** [comment]
by "create a new one", do you mean that it deletes and recreates the deployment with the same name? if so, that is required in order to change some aspects of a deployment (like the selector). can you provide more details about what you are changing? can you also include a trace log (add `--v=6`) to see what requests are being made and their return codes?

**Comment by yelhouti** [comment]
@liggitt well my phrasing was wrong, I apologize, what happens is that new pods is created when I edit and reapply the deployment, which now that i checked better is normal, this done to keep one instance running, and it removes it once the second one is ready, since had a resources problem, no one got ready and they both got stuck leading me to think that new ones where created and where going to stay there each time.
My bad, closing the issue.
