### ISSUE TITLE
Need healthchecks for "other" DNS containers

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#7825]
We now have a healthcheck for skydns, but not for etcd or kube2sky.

**Comment by thockin** [comment]
@ArtfulCoder please link this to your mondo PR's first comment so it auto-closes.

**Comment by thockin** [comment]
@girishkalele We should make sure out DNS pod has appropriate healthchecks for every container.

**Comment by girishkalele** [comment]
@thockin 

If I read the current setup correctly, we might have a small hole there in our DNS pod liveness check - dnsmasq might return the cached DNS entry to the sidecar healthz container and we fail to check if kubedns is alive.

Looked at the liveness and readiness probes on the skydns container specs.
The new skydns pod has the kubedns container liveness check serviced by this "sidecar?" healthz container.
The healthz container seems to doing an nslookup through the entire path from healthz -> dnsmasq -> kubedns. If dnsmasq caches the kubernetes.svc.default.xxx entry, we won't get a real healthcheck on the kubedns container.

**Comment by girishkalele** [comment]
DNS healthz container needs an additional DNS lookup to localhost port 10053 to verify kubedns is healthy.

**Comment by girishkalele** [comment]
Will close via https://github.com/kubernetes/kubernetes/pull/27652

**Comment by girishkalele** [comment]
Closed via #27652
