### ISSUE TITLE
Make kube api server understand XFCC header

### ISSUE THREAD

**Issue by holgero** [kubernetes/kubernetes#78252]
**What would you like to be added**:

kube api server should be able to understand the 'x-forwarded-client-certificate' header.

**Why is this needed**:

This would allow to run the kube api server behind an envoy proxy and to let that envoy proxy handle the TLS termination. The 'x-forwarded-client-certificate' can be set by envoy to pass on the information about the client certificate.

Would this be a welcome contribution?

**Comment by holgero** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by yue9944882** [comment]
https://tools.ietf.org/html/rfc6648

there's rfc proposing deprecating all `x-*` headers. we're not going the other way round, do we?

**Comment by holgero** [comment]
That rfc explicitly states that it “Makes no recommendation as to whether existing "X-" parameters ought to remain in use or be migrated to a format without the "X-"; this is a matter for the creators or maintainers of those parameters. "
So supporting an existing "X-" header doesn't violate that rfc.


Am 23. Mai 2019 18:44:25 MESZ schrieb Min Kim <notifications@github.com>:
>https://tools.ietf.org/html/rfc6648
>
>there's rfc proposing deprecating all `x-*` headers. we're not going
>the other way round, do we?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kubernetes/kubernetes/issues/78252#issuecomment-495295269

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by roycaihw** [comment]
cc @cheftako 
/sig auth

**Comment by holgero** [comment]
Did the last comment trigger a notification? Just to make it sure: 
@kubernetes/sig-auth-feature-requests

**Comment by mikedanese** [comment]
Why not just use the requestheader authenticator?

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy

**Comment by holgero** [comment]
This looks promising. What would it expect as value? The subject as it is specified in the certificate (something like "O=system:masters/CN=system:cluster-admin" ), or just the common name?

**Comment by holgero** [comment]
My guess is, the subject needs to be parsed by the proxy and assigned to username and groupname headers, right? The proxy I have in mind is an envoy proxy and as far as I know it cannot do that at the moment. That would mean I need to bridge this gap somewhere...
Not sure if it makes more sense to teach the proxy how to separate a subject line into group and user names. Or if it is a better idea to get the api server to understand the XFCC header.

**Comment by liggitt** [comment]
> This looks promising. What would it expect as value?

It expects the exact username and groups in the request headers, no interpretation/transformation is performed. All authentication logic is delegated to the auth proxy.

**Comment by mikedanese** [comment]
This subject is available to filters:

https://github.com/envoyproxy/envoy/blob/ff960238f966e906d26ef0c21c89d7b52b174b9c/include/envoy/ssl/connection.h#L56-L60

So a filter is responsible for parsing the distinguished name and converting it into appropriate headers. This is hopefully straightforward to do in a lua or wasm extension.

**Comment by liggitt** [comment]
I'm not eager to base server decisions on client certificates we have not actually verified private key possession of. Unless there are compelling reasons the request header authentication method the API server already is not sufficient, support for this feature will likely not be added.

**Comment by holgero** [comment]
@mikedanese Thanks for the hint, I think we will give that option using a filter a try.

**Comment by holgero** [comment]
@liggitt Sure, I understand. That feature would need to also include a reason for trusting that header.

**Comment by holgero** [comment]
@mikedanese 
> This subject is available to filters:
> 
> https://github.com/envoyproxy/envoy/blob/ff960238f966e906d26ef0c21c89d7b52b174b9c/include/envoy/ssl/connection.h#L56-L60
> 
> So a filter is responsible for parsing the distinguished name and converting it into appropriate headers. This is hopefully straightforward to do in a lua or wasm extension, or in a compiled in filter if you are so inclined.

Unfortunately it seems to be unavailable to lua filters, in the blue note box below https://www.envoyproxy.io/docs/envoy/v1.10.0/configuration/http_filters/lua_filter.html?highlight=lua#connection-object-api it states that the ssl connection object doesn't expose any API. And I wasn't able to get the peer info from the ssl object.

**Comment by liggitt** [comment]
> @liggitt Sure, I understand. That feature would need to also include a reason for trusting that header.

Re-parsing a client certificate (and potentially intermediate chain) on every request would also significantly impact request handling. That is intended to be done once at connection establishment.

**Comment by holgero** [comment]
> Unfortunately it seems to be unavailable to lua filters, in the blue note box below https://www.envoyproxy.io/docs/envoy/v1.10.0/configuration/http_filters/lua_filter.html?highlight=lua#connection-object-api it states that the ssl connection object doesn't expose any API.

I played around with lua filters a bit more and finally had success to get the subject value into the lua coding. So there seems to be a way to achieve what I need with a combination of configuring envoy to set the x-forwarded-client-cert request header and a lua filter.
This would mean that nothing needs to be done on kube api server side.

**Comment by mikedanese** [comment]
@holgero if you get this working and are feeling altruistic, please feel free to post the results here (e.g. lua extension code with friendly license). I'm sure others will run into the same thing, so it would be good to have somewhere to point them.

**Comment by holgero** [comment]
@mikedanese Sure, I will do that. There is also an issue open at envoyproxy/envoy about the need for a parsed subject as header: https://github.com/envoyproxy/envoy/issues/6601
