### ISSUE TITLE
pod:prometheus-k8s-0 is already Terminating

### ISSUE THREAD

**Issue by tanzhixu** [kubernetes/kubernetes#78274]
![image](https://user-images.githubusercontent.com/6026899/58296174-36276b00-7e05-11e9-9e8f-b0dc52bbb0d5.png)

**Comment by hainesc** [comment]
Hi, @tanzhixu
It is an error message that indicated volume not found, it could not find volume to mount, did you create it?
What is the document you followed to be here? You'd better seek help there.
