### ISSUE TITLE
Reduce memory footprint by removing unnecessary cloud provider plugins at runtime

### ISSUE THREAD

**Issue by frolickingferret445** [kubernetes/kubernetes#78271]
I am interested in reducing the memory footprint of kubernetes if possible.  From what I gather, by default, kubernetes runs with plugins for all cloud providers. I’ve looked into https://k3s.io/ and it mentions that it removes unnecessary in-tree cloud providers and storage drivers.  However, it doesn’t offer other important features, so I’d prefer to stick to my existing installation process (with perhaps a couple of additional steps).

Is there a way to do this? (preferably with kubeadm)

I discovered a daemonset called cloud-controller-manager (beta feature) which pulls out some of the cloud-specific tasks from kube-controller-manager.  

https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

However, it still has a cloud-provider command-line flag.  Does cloud-controller-manager reduce the memory footprint by only loading plugins for the necessary cloud provider?

I looked into using kubeadm to install cloud-controller-manager, but it seems that it isn’t yet supported, probably because it’s a beta feature.  All of the controller-manager flags are for kube-controller-manager:

https://kubernetes.io/docs/setup/independent/control-plane-flags/

It sounds like I could get this working with a few extra steps similar to this : 

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-controller-manager-with-kubeadm.md

Right?  

Any help would be appreciated, thanks.

@kubernetes/sig-cloud-provider-maintainers

**Comment by frolickingferret445** [comment]
@sig-cloud-provider

**Comment by frolickingferret445** [comment]
@kubernetes/sig-cloud-provider

**Comment by frolickingferret445** [comment]
@kubernetes/sig-cloud-provider-maintainers

**Comment by BenTheElder** [comment]
also interested in small memory footprints 🙃 
cc @cheftako re: cloud-controller-manager
cc @neolit123 re: kubeadm

**Comment by neolit123** [comment]
> I looked into using kubeadm to install cloud-controller-manager, but it seems that it isn’t yet supported, probably because it’s a beta feature. All of the controller-manager flags are for kube-controller-manager:

kubeadm is a node boostrapper. if kubernetes supports cloud-controller-manager as a DaemonSet then kubeadm supports it too.

except that we don't have a guide for that.

> All of the controller-manager flags are for kube-controller-manager:
https://kubernetes.io/docs/setup/independent/control-plane-flags/

you still have to use the kubeadm config to pass extraArgs to the control-plane components.

> It sounds like I could get this working with a few extra steps similar to this :
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-controller-manager-with-kubeadm.md

this guide runs the cloud-controller-manager as a static pod.

> Does cloud-controller-manager reduce the memory footprint by only loading plugins for the necessary cloud provider?

will leave the memory footprint questions to sig-cloud-provider. :)

**Comment by BenTheElder** [comment]
you can exclude _all_ of them at build time now, the CCM is the way forward though as all cloud providers are going out of tree

**Comment by dims** [comment]
tracked already https://github.com/kubernetes/enhancements/issues/88#issuecomment-450910270

/close
