### ISSUE TITLE
Certificate error when connecting to master after AWS cluster stop/start

### ISSUE THREAD

**Issue by madis** [kubernetes/kubernetes#7828]
I have set up a kubernetes cluster in AWS. After finishing work with it, I stop the instances. Next time when I start the instances up again, they get assigned new public IP-s. The ```.kube/config``` has IP-s from the first starting. I can update the IP-s in ```.kube/config``` but it results in certificate error ```Error: Get https://52.24.72.124/api/v1beta1/pods?namespace=default: x509: certificate is valid for 54.149.120.248, not 52.24.72.124``` when making requests against kubernetes api (e.g. ```./cluster/../cluster/aws/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl get pods --context=aws_kubernetes```). 

Is this expected behaviour and how to overcome it? I suppose generating the certificates for elastic IP, which wouldn't change between starting & stopping the cluster could help. But how to pass the elastic IP for kubernetes master to the *kube-up.sh* script?

**Comment by roberthbailey** [comment]
Can you reserve a fixed IP for your master instance? The start-up scripts generate the certificate based on the IP address of the master when it starts which is why you are seeing the old address in the SSL error.

**Comment by roberthbailey** [comment]
@justinsb

**Comment by madis** [comment]
Amazon calls the fixed IP-s Elastic IP-s. I can reserve one. Just not sure how to tell kubernetes to use it before generating the certificate.

**Comment by roberthbailey** [comment]
For GCE we do this (see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L509-L513). The AWS master creation is a bit different, but if you tweaked with the script [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/util.sh#L463-L476) you could probably manage to get this working.

**Comment by madis** [comment]
Thanks. I will tweak my aws util.sh and send a pull request so you can see if there's more interest in having this feature.

**Comment by manolitto** [comment]
You may (re)create a new certificate by doing this:

    ssh-add -K ~/.ssh/kube_aws_rsa
    ssh -A ubuntu@52.24.72.124
    cd /srv/salt/generate-cert
    sudo ./make-ca-cert.sh 52.24.72.124
    sudo reboot

Then you can download the certificate:

    ssh -A ubuntu@52.24.72.124 sudo cat /srv/kubernetes/kubecfg.crt > ~/.kube/$KUBE_CONTEXT/kubecfg.crt
    ssh -A ubuntu@52.24.72.124 sudo cat /srv/kubernetes/kubecfg.key > ~/.kube/$KUBE_CONTEXT/kubecfg.key
    ssh -A ubuntu@52.24.72.124 sudo cat /srv/kubernetes/ca.crt      > ~/.kube/$KUBE_CONTEXT/kubernetes.ca.crt

    chmod 400 ~/.kube/kubernetes/kubecfg.crt
    chmod 400 ~/.kube/kubernetes/kubecfg.key
    chmod 400 ~/.kube/kubernetes/kubernetes.ca.crt

Please note: if you are using v0.15.x or above you must add this certificate and the key to your kube config. See "kubectl config" for details or have a look into your ~/.kube/config file.

**Comment by madis** [comment]
I created a pull request that requests & assigns Elastic IP to cluster master instance. https://github.com/GoogleCloudPlatform/kubernetes/pull/7888

It allows stopping & starting cluster on AWS EC2 without certificate errors (because the master ip changed and certificate is for the old IP).  If this functionality fits the goals of the project, please send feedback, I'll fix if anything wrong :)

**Comment by justinsb** [comment]
Question for you @madis : are you stopping the instances using cluster/kube-down.sh, or by manually stopping them.  Separately from the elastic-ip issue, it sounds like there may be a problem here (I would expect kube-down should remove the no-longer-valid-configuration)

**Comment by madis** [comment]
I'm stopping the instances manually (i.e. without *cluster/kube-down.sh*) so they would not get destroyed and I can start them again next day. It's a cluster for playing around so I can save money by stopping it when not using.

**Comment by justinsb** [comment]
Thanks for clarifying @madis.   Seems like if we can find a workable solution for #7888 that'll be best.

**Comment by mikaelh** [comment]
@justinsb @madis The current feature in #7888 fails because the instance needs to be in running state to be able to assign an elastic ip. I made a pull request #13072 which run assign-elastic-ip after wait-for-instance-running has returned.

**Comment by stemau98** [comment]
@madis  can't help you with your problem but had a question about stopping the kubernetes cluster. 
How did you stop the instances? I have the problem that after I stopped them they started in emergency mode. I think something going wrong with ephemeral storge at second boot. Maybe you can help me?

**Comment by davidopp** [comment]
#7882 and #13072 have been merged, can we close this?

**Comment by justinsb** [comment]
I've opened #21159 to track the fact that instances (in particular the master) don't recover after a stop/start.  Everything else in this issue is fixed now I believe:  Instances should now recover after a reboot.  The master has a PD and an elastic IP, so clients can resume talking to it when it comes back.
