### ISSUE TITLE
RemainingItemCount is serialized in proto messages even when unset

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#78318]
**What happened**:
As part of [adding skew testing for serialized API responses](https://github.com/kubernetes/kubernetes/pull/78309), we discovered a diff in serialized proto responses when roundtripping data from 1.14:

```
    --- FAIL: TestRoundTripExternalTypes/.v1.Status (0.02s)
        --- FAIL: TestRoundTripExternalTypes/.v1.Status/fixtures-v1.14.0 (0.02s)
            fixtures.go:195: proto data differed from fixture
            fixtures.go:205: fixture vs reserialized:
                  strings.Join({
                  	... // 7 identical lines
                  	`    2: "8551505577692297499"`,
                  	`    3: ""`,
                + 	"    4: 0",
                  	"  }",
                  	"  2 {",
                  	... // 21 identical lines
                  }, "\n")
```

This is due to the RemainingItemCount field in ListMeta, which is always serialized in proto messages, because it is not a pointer.

**What you expected to happen**:
Proto messages do not include the optional field when unset.

**How to reproduce it (as minimally and precisely as possible)**:
* Check out https://github.com/kubernetes/kubernetes/pull/78309
* Run `go test ./vendor/k8s.io/api -run TestRoundTripExternalTypes//1.14` (tests round-tripping serialized API content for all types we shipped in 1.14)

This needs to be resolved before 1.15 ships.

/milestone v1.15
/kind bug
/sig api-machinery
/priority important-soon
/assign @caesarxuchao

**Comment by caesarxuchao** [comment]
What buggy behavior will an end user experience?

**Comment by liggitt** [comment]
> What buggy behavior will an end user experience?

the user would be unable to tell whether the server had returned a value for the field or not
