### ISSUE TITLE
Setting up a simple, single node kubernetes cluster using Docker

### ISSUE THREAD

**Issue by hesonglin006** [kubernetes/kubernetes#7831]
I followed the instrcution [https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md) to set up a simple, single node kubernetes cluster using Docker.When I use `kubectl get pods`,the problem is:  
` Client error: Get http://localhost:8080/api/v1beta1/pods?namespace=default: dial tcp 127.0.0.1:8080: connection refused`,What should I do?thanks for your response!

**Comment by viklas** [comment]
Hi - not sure what level of debugging you've managed so far.

It basically means the kubernetes 'api server' component hasn't started properly (no response on port 8080). If you SSH to your host and do a 'docker ps' you should see 5 containers (on 'master')...proxy, apiserver, scheduler, controller-manager and kubelet. If all 5 are running...good start. If any are missing...do a 'docker ps -a' to get the full list of running and stopped containers.

Now you want to do a 'docker logs xxx' (where xxx is the first few characters of the docker container ID you're interested in). In your case, the apiserver container. The output should give you some clues as to what is broken. If you need more logs, you have to option of hacking the pod manifest file called 'master.json' I think...set the logging to v=5, re-do everything from scratch, and you should catch the error.

There's a few possibilities about what is going wrong...start by grabbing the docker container logs.

**Comment by hesonglin006** [comment]
Thanks for your patient instruction，I'll try to solve the problem follow your guide,if there is still problem,I'll let you know,thx again @viklas

**Comment by brendandburns** [comment]
Is this using boot2docker? You may need to run ```boot2docker ssh -L 8080:localhost:8080```

**Comment by skuzye** [comment]
I got the same issue. I copied and pasted the commands in the guide.

**Comment by skuzye** [comment]
Seems like the docs are wrong, as per #7581

**Comment by goltermann** [comment]
Closing in favor of #7581
