### ISSUE TITLE
go-client credentials plugin can be retried on failures/errors

### ISSUE THREAD

**Issue by jamesgoodhouse** [kubernetes/kubernetes#78321]
**What happened**:
When writing a custom plugin application for use with kubectl for authentication (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins), any failures of the application result in 5 consecutive retries from `kubectl`.

**What you expected to happen**:
I expect that if my custom plugin application returns a non-zero status code, or otherwise panics, that kubectl will halt and not try to re-execute the plugin.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shell script with the following content:
```
#!/bin/sh
>&2 echo "error"
exit 1
```

Configure a user in your kubectl as follows:
```
- name: exec-auth-test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: <<PATH_TO_SHELL_SCRIPT>>
```

Run kubectl utilizing this user and see that "error" has been echoed out 5 times, regardless of the script returning a non-zero code. You can also run kubectl with `-v10` and see the multiple calls being made.

**Anything else we need to know?**:
This is important from a user experience perspective so that the application has some control over whether or not retries happen. In my specific case, I am triggering a user's web browser to open so that can finish authentication for a PKCE flow, resulting in a browser open 5 times in a row regardless of the fact the application has returned a non-zero status.

**Environment**:
- Kubernetes version (use `kubectl version`): `1.14`
- OS (e.g: `cat /etc/os-release`): MacOS using minikube
- Kernel (e.g. `uname -a`): `Darwin C02TW1DBHTD8 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`
- Install tools: minikube
- Network plugin and version (if this is a network-related bug): default minikube
- Others:

**Comment by jamesgoodhouse** [comment]
@kubernetes/sig-cli

**Comment by jamesgoodhouse** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
Reinvocation on error is not unexpected, and can happen for a variety of reasons (especially on idempotent get requests).

**Comment by awly** [comment]
IIUC retries are happening here https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L720-L808
We could add a special case to handle non-transient errors for GET requests.

But I don't think exit code is a good proxy for deciding about retries.
I'm working on a KEP for credential plugins now and plan to add `error` field to response object. That sounds like a good place to add `do_not_retry` field too.
