### ISSUE TITLE
 unable to create proxier: source-vip flag not set - Kubeproxy doesn't start on windows node

### ISSUE THREAD

**Issue by gkgth** [kubernetes/kubernetes#78338]
**What happened**:
Kubeproxy doesn't start on windows node 
**What you expected to happen**:
kubeproxy should start 
**How to reproduce it (as minimally and precisely as possible)**:
Kubernetes cluster v1.14.2 with Flannel in VXLAN mode , trying to attach a windows server 2019 as a node,  kubeproxy fails to start with the following error.

**Anything else we need to know?**:

```
Log file created at: 2019/05/25 05:30:53
Running on machine: WIN-5S8F8ERBA1G
Binary: Built with gc go1.12.5 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0525 05:30:53.023140    9052 server.go:475] unable to create proxier: source-vip flag not set
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0xc0000ae001, 0xc000448000, 0x942, 0x2710)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:828 +0xb8
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x29f46e0, 0xc000000003, 0xc000263420, 0x292aed8, 0x9, 0x1db, 0x0)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:782 +0x168
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printDepth(0x29f46e0, 0x3, 0x1, 0xc000719d18, 0x1, 0x1)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:669 +0x132
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).print(...)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:660
k8s.io/kubernetes/vendor/k8s.io/klog.Fatal(...)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1189
k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc00019b180, 0xc000472210, 0x0, 0xb)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:475 +0x275
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00019b180, 0xc0000b8010, 0xb, 0xf, 0xc00019b180, 0xc0000b8010)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2b5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00019b180, 0x192a708, 0x29f4380, 0x187d4fb)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2f3
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.14.2-beta.0.85+66049e3b21efe1/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/proxy.go:49 +0x10c

```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: VMWare
- OS (e.g: `cat /etc/os-release`):
Windows Node : Version 1809 17763.503
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Cherishty** [comment]
meet the same issue, any hints?

**Comment by Belogix** [comment]
@Cherishty - I think I have found the issue and have it working now. I am trying to create a temporary fix that I will share in a couple of hours.

**Comment by Belogix** [comment]
I am having issues pushing to my repo right now but basically I am using the Windows Services approach and in `register-svc.ps1` I changed lines 57 - 65 to this:

```powershell
elseif ($NetworkMode -eq "overlay")
{
    # Ensure that we have generated a Source VIP JSON file when using overlay networks
    if(!(Test-Path c:/k/sourceVip.json)) { GetSourceVip -ipAddress $ManagementIP -NetworkName 'vxlan0' }

    # Check that the required file was generated, if not the Kube-Proxy service will catastrophically fail to run but will seem to start.
    # The logs will be full of errors stating 'unable to create proxier: source-vip flag not set'.
    if(!(Test-Path c:/k/sourceVip.json))
    {
        Write-Error 'The .\SourceVip JSON file was not found - Fatal Error, aborting now!'
        Exit 999
    }
    $sourceVipJSON = Get-Content sourceVip.json | ConvertFrom-Json
    $sourceVip = $sourceVipJSON.ip4.ip.Split("/")[0]
    .\nssm.exe set $KubeProxySvc AppParameters --v=4 --proxy-mode=kernelspace --feature-gates="WinOverlay=true" --hostname-override=$Hostname --kubeconfig=c:\k\config --network-name=vxlan0 --source-vip=$sourceVip --enable-dsr=false --cluster-cidr=$ClusterCIDR --log-dir=$LogDir --logtostderr=false
}
```

If you are using the `start.ps1` script to run the components manually you need to check that lines 52 - 57 are being run correctly ( https://github.com/microsoft/SDN/blob/master/Kubernetes/flannel/start.ps1#L52-L55 ).

The main point is that the function `GetSourceVip` (from `helper1.psm1`) must be called before trying to run the kube-proxy. The `GetSourceVip` function should output two files (`sourceVip.json` and `sourceVipRequest.json`) by querying the HNS network. If that fails and those files are not generated then the current code just ignores that and carries on to run the kube-proxy with the `--source-vip` parameter blank. This will then mean the process starts but fails with the errors we are seeing. In my code snippet above you can see that I catch the failure and abort instead. When I get time I will see if I can put together a proper PR for this.

**Comment by gudipudipradeep** [comment]
Getting same issue any idea about this issue. kube-proxy service is not starting that i could not able connect with other components.

**Comment by maartenschalekamp** [comment]
@Belogix Thank you for the info.

I went to implement it rather after the register-svc.ps1 was executed. The vxvlan0 hns network will only be available after flannel created it as well, so running the GetSourceVip too early would cause invalid configurations generated in the sourceVip.json file.

I have added this just after my register-svc.ps1 command
```powershell
Write-Output "Set --source-vip in kube-proxy service config"
Stop-Service kube-proxy
# Flannel should setup the vxlan0 interface in hns
while ((Get-HnsNetwork | Where-Object { $_.Name -eq 'vxlan0' }).Name -ne 'vxlan0') { Write-Output "Waiting for hns network vxlan0"; Start-Sleep 5 }
if (Test-Path c:\k\sourceVip.json) { Remove-Item c:\k\sourceVip.json -Force -ErrorAction SilentlyContinue }
Import-Module C:\k\helper.psm1
GetSourceVip -ipAddress $privateip -NetworkName 'vxlan0'
$sourceVipJSON = Get-Content sourceVip.json | ConvertFrom-Json
$sourceVip = $sourceVipJSON.ip4.ip.Split("/")[0]
$kubeAppParams = (nssm get kube-proxy AppParameters) -replace '[^a-zA-Z0-9| |=|:|\\|/|\.|-]', '' -replace '--source-vip=', "--source-vip=$sourceVip"
Write-Output "Kube-Proxy Service Parameters: $kubeAppParams"
nssm.exe set kube-proxy AppParameters $kubeAppParams
Start-Service kube-proxy
```

The parameter `-ipAddress` from the function `GetSourceVip` not even used by it, so it can by anything.
For some reason the output for `(nssm get kube-proxy AppParameters)` have some character in between all the ascii values. So thats is why the regex in place to remove those at `(nssm get kube-proxy AppParameters)`

```powershell
PS C:\k> (nssm get kube-proxy AppParameters)
- - v = 4   - - p r o x y - m o d e = k e r n e l s p a c e   - - f e a t u r e - g a t e s = W i n O v e r l a y = t r u e   - - h o s t n a m e - o v e r r i d e = t u s - s v - k 8 - w i n - 0   - -  u b e c o n f i g = c : \ k \ c o n f i g   - - n e t w o r k - n a m e = v x l a n 0   - - s o u r c e - v i p = 1 0 . 2 4 4 . 3 . 2 7   - - e n a b l e - d s r = f a l s e   - - c l u s t e r - c i d  = 1 0 . 2 4 4 . 0 . 0 / 1 6   - - l o g - d i r = c : \ k \ l o g s   - - l o g t o s t d e r r = f a l s e
```
