### ISSUE TITLE
Volume resource counting to enforce scheduling constraints

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#7835]
From #3318:

>In the short term a pre creation hook can convert volume object characteristics (I am a persistent volume that is a GCE disk, therefore I require one unit of "storage" attach) and move that into the container resources as a summation, which the scheduler would look at as an arbitrary resource.  The binder can do this once we have finalization mechanisms

Above is from @smarterclayton.  Discussed something similar with @thockin and @bgrant0607 a while back.

I understand what we want to do, but lack the technical design to make it happen.

How does a pod/volume communicate what kind of "slot" is consumes?  Is this all contained in the scheduler (it is counting all resources consumed and placed)?  Where do the rules go (e.g, 16 GCE disks per node)?

Feedback is requested, please.

**Comment by smarterclayton** [comment]
The simplest thing I can imagine is a simple set of rules in an admission controller that might be configurable or based on some simple heuristics.  It walks incoming pods and converts their characteristics into another resource type.  This is something that would be an initializer hook once they exist.

**Comment by smarterclayton** [comment]
For instance, summate the number of GCE volumes in the pod and create a resource "mounted.persistentVolumes.count" = "1"

**Comment by smarterclayton** [comment]
We'd then probably need to add fit characteristic defaulting to the scheduler or the node somehow - max: "mounted.persistentVolumes.count" = 16

**Comment by markturansky** [comment]
I hate to be obtuse, but how does that translate into code?  where does "mounted.pV.count=1" go?  I don't quite grok *how* I would implement counting and where i would store rules.

**Comment by smarterclayton** [comment]
Into the resources field - essentially you're looking at the pod, doing a calculation, and then storing the result of the calculation as a "consumed" resource in the pod definition prior to the scheduler seeing it.

**Comment by markturansky** [comment]
What "resources field" do you refer to?  Where would this inspection go so that it's calculated before it gets to the scheduler?  Is the scheduler full of state now (knowing where it places pods, how many resources they're consuming across the cluster, etc) and I'm just adding another piece?

I kind of need to know specifically which code this is going to touch, because I am not familiar with the scheduler at this point.

**Comment by markturansky** [comment]
I discussed this with @abhgupta.  His advice was:

1. Add "volumes" to node.Status.Capacity when a node is added to the cluster.
  1. Clusters in GCE get "16" for "volumes" or similar key
  2. Clusters in AWS get "40" for "volumes" or similar key
  3. Clusters anywhere else get "0" for "volumes"
2. Add "volumes" to pod.Spec.Containers[i].Resources.Requests
  1. Inspect a pod's volumes and count its usages of GCE or AWB EBS volumes and add it to the "volumes" count
  2. Inspect a pod's PVClaim, fetch the corresponding PV, and count its usages of GCE or AWS EBS and add it to the "volumes" count.
3. Add "volumes" resource checking to scheduler predicates
  1. Similar to CPU/Memory, compare "volumes" available on a node to what is requested by a pod.
  2 Nice-to-have/future improvement: add to scheduler priorities to evenly distribute volumes across nodes

Clusters running in GCE/AWS will have their volume limits set to 16 and 40, respectively.  This number can be 0 everywhere else because pods requesting GCE/EBS volumes won't schedule correctly outside GCE/AWS.  Admission control will never tally a positive number of those volumes outside of those providers, so pods request 0 volumes and nodes have 0 volumes for constraints.

**Comment by bgrant0607** [comment]
See also #4910

We need some kind of plugin in apiserver to at least validate requests for each volume type. This code should also set defaults, including resource requirements.

We need some kind of plugin in kubelet to implement the volume type. This code should be able to publish capacity for such resource requirements.

I suggest using a different resource name for each volume type: GCEPersistentDiskVolumes, AWSElasticBlockStoreVolumes, etc.

cc @davidopp

**Comment by markturansky** [comment]
@bgrant0607 regarding validation, there is validation in the API but that doesn't tell a user they can't request an EBS volume when running in GCE.  What kind of plugins were you referring to that would validate each volume type?

Distinct resource names is a good idea.  I can use the constants from the volumes, either through duplication or the volume plugins can be exposed to the apiserver.  This would allow the validation mentioned above.    Also allows the distinct volume name "kubernetes.io/gce-pd", for example.

**Comment by jayunit100** [comment]
Cc @rootfs @swatt @childsb might need to update ceph and gluster if imdividual volume types if the volumes are responsible for self validation .

**Comment by bgrant0607** [comment]
@markturansky The necessary plugins don't exist yet. They are mentioned in #8190. We could extend the volume plugin API to add defaulting, conversion, and validation, but we eventually need a mechanism that's more general than just volumes.

**Comment by markturansky** [comment]
This issue can be closed when https://github.com/kubernetes/kubernetes/pull/19880 is merged (or this issue is a dupe of whatever issue 19880 is resolving)
