### ISSUE TITLE
Add Spanish i18n strings to kubectl

### ISSUE THREAD

**Issue by raelga** [kubernetes/kubernetes#78352]
**What would you like to be added**:

The Spanish i18n strings for `kubectl`.

**Why is this needed**:

To make `kubectl` more friendly to Spanish speakers.

/assign @raelga 
/sig cli
/kind feature

**Comment by raelga** [comment]
I'm already working on this issue. ⚙️

**Comment by mikefang426** [comment]
Is there anyone actually using Spanish kubectl in real life?

**Comment by raelga** [comment]
Not yes, cause is not implemented at this point, but may come handy.

**Comment by raelga** [comment]
It has been open for too long. If we find the resources to actually implement it, we will open a new one.

/close
