### ISSUE TITLE
After systemd-journal stop and start,kubelet will restart

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#78358]
After systemd-journal restart,kubelet will restart

I got this: https://github.com/moby/moby/pull/22460 . Docker ignore SIGPIPE events to fix it.
Does kubelet also need this fix?

/sig node

**Comment by mattjmcnaughton** [comment]
Hi @chenk008 - thanks for reporting this :)

Would you mind filing in the [Bug Report template](https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)? That'll give us some good initial information for starting our investigation.

**Comment by chenk008** [comment]
#38028

**Comment by chenk008** [comment]
How to reproduce it:
systemctl kill systemd-journald.service
After some minutes,the kubelet will restart
And strace log show:

> --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_TKILL, si_pid=32184, si_uid=0} ---
> +++ killed by SIGPIPE +++

**Comment by chenk008** [comment]
#https://github.com/kubernetes/kubernetes/issues/38028

**Comment by chenk008** [comment]
#https://github.com/kubernetes/kubernetes/issues/38028

**Comment by LeoLiuYan** [comment]
May kubelet should ignore SIGPIPE?
