### ISSUE TITLE
apiservers pki expired on the master and renew does not seem to take effect

### ISSUE THREAD

**Issue by desdic** [kubernetes/kubernetes#78382]
**What happened**:
apiservers cert expired and I ran kubeadm alpha cert renew all. The files seems to have updated (pki directory) but when restarting kubelet it still says its expired

**What you expected to happen**:
That it would have updated the pki so kubelet would start. But I would also expected that it updated itself like the other certs seems to do.

The documentation does not mention any other thing one need to run in order to have kubeadm alpha cert renew all work

**Environment**:
- Kubernetes version : v1.14.2
- Cloud provider or hardware configuration: local installation
- OS (e.g: `cat /etc/os-release`): 16.04.6 LTS 
- Kernel (e.g. `uname -a`): 4.4.0-145-generic

**Comment by neolit123** [comment]
please re-open this ticket in the kubernetes/kubeadm repository so that the maintainers can track it.

thanks
/area kubeadm
/close
