### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce-big pull-kubernetes-integration failed frequently

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#78401]
**Which jobs are failing**:

https://github.com/kubernetes/kubernetes/pull/78248

**Which test(s) are failing**:

pull-kubernetes-kubemark-e2e-gce-big
pull-kubernetes-integration 

**Since when has it been failing**:

2019-05-27 19:00:00  +8

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78248/pull-kubernetes-kubemark-e2e-gce-big/1133003298240991232/

**Reason for failure**:

`pull-kubernetes-kubemark-e2e-gce-big`  timeout
`pull-kubernetes-integration`  stress test failed 

**Anything else we need to know**:

**Comment by roycaihw** [comment]
/sig testing

pull-kubernetes-kubemark-e2e-gce-big failure might be related to: https://github.com/kubernetes/perf-tests/pull/538#discussion_r287891512. cc @mm4tt

**Comment by cwdsuzhou** [comment]
Thanks @roycaihw @mm4tt
