### ISSUE TITLE
Failed to admit critical pod due to "timeout waiting to kill pod" while handling admission failure

### ISSUE THREAD

**Issue by pracucci** [kubernetes/kubernetes#78405]
**What happened**:

Kops runs `kube-proxy` from a pod manifest stored on the node, having the `scheduler.alpha.kubernetes.io/critical-pod` annotation.

We've experienced the case where the cluster autoscaler turned on a new node and, once the node has been added to the cluster, application pods have been admitted before `kube-proxy`. Once it was the turn of `kube-proxy`, all system resources were utilized, so the pod has not been regularly admitted.

However, since it's a critical pod, the `kubelet` executed the `HandleAdmissionFailure`, which has tried to kill (`killPodNow`)  a pod whose container wasn't started yet (it was downloading the Docker image), which has caused `killPodNow` to timeout and return the error `"timeout waiting to kill pod"`.

The admission of `kube-proxy` failed with the following error:
```
Unexpected error while attempting to recover from admission failure: preemption: pod worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c) failed to evict timeout waiting to kill pod
```

The `kube-proxy` pod execution has not been retried, so we've got a node without `kube-proxy` running and its networking broken.

**What you expected to happen**:

The `kube-proxy` should be eventually admitted.

**Anything else we need to know?**:

A minimal log extraction for comprehension:

```
14:27:17.909755 kubelet.go:1833] SyncLoop (ADD, "api"): "worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c)"
14:27:27.318348 kubelet.go:1833] SyncLoop (ADD, "file"): "kube-proxy-ip-REDACTED.eu-west-1.compute.internal_kube-system(a1808f36adc75b3585b0951a00ac3102)"
14:27:42.456247 predicate.go:107] Failed to admit pod kube-proxy-ip-REDACTED.eu-west-1.compute.internal_kube-system(a1808f36adc75b3585b0951a00ac3102) - Unexpected error while attempting to recover from admission failure: preemption: pod worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c) failed to evict timeout waiting to kill pod
14:27:42.479469 kubelet.go:1878] SyncLoop (PLEG): "worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c)", event: &pleg.PodLifecycleEvent{ID:"829b7759-7c9d-11e9-ac16-06903246ae0c", Type:"ContainerStarted", Data:"6721ad58d43a97348b00dbca545df21da98242315bcd74740331964d828adb67"}
14:28:17.000000 kubelet.go:1878] SyncLoop (PLEG): "worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c)", event: &pleg.PodLifecycleEvent{ID:"829b7759-7c9d-11e9-ac16-06903246ae0c", Type:"ContainerStarted", Data:"4725d1fbeb24e46b13d3a19290b61929f4cb14cb4398ee455b3f1ffa8a7cbc17"}
```

From the "Failed to admit pod" log I have been able to trace back the core code involved:

- `HandleAdmissionFailure` (`pkg/kubelet/preemption.go`)
  Logs: "Failed to admit pod [POD] - [ERROR]"
  - `evictPodsToFreeRequests` (`pkg/kubelet/preemption.go`)
    Error message: "preemption: pod [POD] failed to evict [ERROR]"
    - `getPodsToPreempt` (`pkg/kubelet/preemption.go`)
    - `killPodFunc` -> `killPodNow` (`pkg/kubelet/pod_workers.go`)
      Error message: "timeout waiting to kill pod"

**Environment**:
- Kubernetes version: `1.11.7`
- Cloud provider: AWS
- OS: ubuntu 16.04.6 LTS (Xenial Xerus)
- Kernel: `Linux 4.4.0-1083-aws`
- Install tools: kops
- Network plugin and version: kubenet

**Comment by pracucci** [comment]
@kubernetes/sig-resource-management-bugs

**Comment by tedyu** [comment]
I think the following change may alleviate the situation you encountered:
```
diff --git a/pkg/kubelet/preemption/preemption.go b/pkg/kubelet/preemption/preemption.go
index f6e871376f..2a2d660bc9 100644
--- a/pkg/kubelet/preemption/preemption.go
+++ b/pkg/kubelet/preemption/preemption.go
@@ -21,6 +21,7 @@ import (
        "math"

        "k8s.io/api/core/v1"
+       utilerrors "k8s.io/apimachinery/pkg/util/errors"
        "k8s.io/client-go/tools/record"
        "k8s.io/klog"
        "k8s.io/kubernetes/pkg/api/v1/resource"
@@ -96,6 +97,7 @@ func (c *CriticalPodAdmissionHandler) evictPodsToFreeRequests(admitPod *v1.Pod,
                return fmt.Errorf("preemption: error finding a set of pods to preempt: %v", err)
        }
        klog.Infof("preemption: attempting to evict pods %v, in order to free up resources: %s", podsToPreempt, insufficientResources.toString())
+       errors := []error{}
        for _, pod := range podsToPreempt {
                status := v1.PodStatus{
                        Phase:   v1.PodFailed,
@@ -107,11 +109,12 @@ func (c *CriticalPodAdmissionHandler) evictPodsToFreeRequests(admitPod *v1.Pod,
                // this is a blocking call and should only return when the pod and its containers are killed.
                err := c.killPodFunc(pod, status, nil)
                if err != nil {
-                       return fmt.Errorf("preemption: pod %s failed to evict %v", format.Pod(pod), err)
+                       errors = append(errors, fmt.Errorf("preemption: pod %s failed to evict %v", format.Pod(pod), err))
+                       continue
                }
                klog.Infof("preemption: pod %s evicted successfully", format.Pod(pod))
        }
-       return nil
+       return utilerrors.NewAggregate(errors)
 }

 // getPodsToPreempt returns a list of pods that could be preempted to free requests >= requirements
```

**Comment by pracucci** [comment]
@tedyu Thanks for your reply. To my understanding, when the `getPodsToPreempt()` is called it will return the **minimum set** of pods required to free up resources, so even if only 1 pod eviction fails it's likely that at the end of the `evictPodsToFreeRequests()` the `kubelet` will not have enough resources anyway to admit the critical pod.

In your opinion / experience:

1. May be an option introducing retries in the `evictPodsToFreeRequests()` in case the eviction of 1 pod fails?
2. If yes, do you have any suggestion of a similar design adopted somewhere else in the `kubelet`?

**Comment by tedyu** [comment]
Looking at getPodsToPreempt, I am not sure it returns the minimum set of Pods.

For #1, retrying may not help much since the pod to be killed may not respond to the subsequent kill command.

**Comment by pracucci** [comment]
> Looking at getPodsToPreempt, I am not sure it returns the minimum set of Pods.

@tedyu Sorry to reiterate on this, but I double checked the code and - if I'm not missing anything - `getPodsToPreempt()` returns the minimum set of pods.

Let's look at `getPodsToPreempt()` logic:
1. Split pods by QOS class using `sortPodsByQOS()`
2. Ensure that the total sum of evictable pods resources is enough to satify the requirements (resources to evict for the critical pod)
3. Calculate the list of pods to evict, as the merge of there sublists:
   - `guarateedToEvict`: the minimum set of pods to evict assuming we've already evicted **all** `burstableToEvict` and *all** `bestEffortToEvict`
   - `burstableToEvict`: the minimum set of pods to evict assuming we've already evicted **all** `bestEffortToEvict` and the required `guarateedToEvict`
   - `bestEffortToEvict`: the minimum set of pods to evict to satify the requirements left
   
Am I missing anything?

A possible **different approach** to solve the issue is to refactor `getPodsToPreempt()` to return all input pods sorted by "should be evicted first". Then `evictPodsToFreeRequests()` iterates over the full sorted list of potential pods to evict until the requirements are not satisfied (skipping to subtract pod resources from requirements if a pod fails on `killPodFunc()`) and breaking the loop as soon as the requirements are satisfied. What's your take on this?

/cc @dashpole who originally implemented this

**Comment by tedyu** [comment]
w.r.t. approach outlined above, it makes sense.

**Comment by dashpole** [comment]
Whether this evicts the "minimum set" depends on how you define the "minimum set".  At the time this was implemented (k8s v1.5.0 IIRC), we didn't have PodPriority, so we used QoS to mirror the kubelet's eviction algorithm.  It should probably prioritize low-priority pods for eviction today given the recent changes to the eviction algorithm to incorporate PodPriority.  The current approach minimizes the eviction of guaranteed pods, and prioritizes evicting few larger pods over many smaller ones.

Since eviction marks the evicted pod as failed, it should suffice to just admit the pod regardless of what is returned by the evictPod function.  In future syncPod loops, the kubelet will retry the pod deletion steps that it was stuck on.  It would eliminate this class of bugs entirely, which was the purpose of the feature in the first place.

**Comment by tedyu** [comment]
@dashpole 
See if the following aligns with your suggestion:
```
diff --git a/pkg/kubelet/lifecycle/predicate.go b/pkg/kubelet/lifecycle/predicate.go
index 04eab48ffb..45525772bd 100644
--- a/pkg/kubelet/lifecycle/predicate.go
+++ b/pkg/kubelet/lifecycle/predicate.go
@@ -104,11 +104,7 @@ func (w *predicateAdmitHandler) Admit(attrs *PodAdmitAttributes) PodAdmitResult
                if err != nil {
                        message := fmt.Sprintf("Unexpected error while attempting to recover from admission failure: %v", err)
                        klog.Warningf("Failed to admit pod %v - %s", format.Pod(admitPod), message)
-                       return PodAdmitResult{
-                               Admit:   fit,
-                               Reason:  "UnexpectedAdmissionError",
-                               Message: message,
-                       }
+                       fit = true
                }
        }
        if !fit {
```

**Comment by dashpole** [comment]
Something like that, yeah.  I'm not sure the "Failed to admit pod" log warning is still required, but we can iron those things out during code review.

**Comment by pracucci** [comment]
> See if the following aligns with your suggestion:

@tedyu Doing like this it means we do always admit pods, while we should do it only for critical pods, correct?

**Comment by tedyu** [comment]
Please see this 
```
func (c *CriticalPodAdmissionHandler) HandleAdmissionFailure(admitPod *v1.Pod, failureReasons []predicates.PredicateFailureReason) (bool, []predicates.PredicateFailureReason, error) {
	if !kubetypes.IsCriticalPod(admitPod) {
		return false, failureReasons, nil
```
The change is for critical pod(s).
