### ISSUE TITLE
Delay from DiskPressure condition being reported from node

### ISSUE THREAD

**Issue by awprice** [kubernetes/kubernetes#78416]
**What happened**:

We've seen instances where a node will go into DiskPressure, but for some reason a pod is still scheduled to the node that is in DiskPressure. The kubelet will then not admit the pod to the node.

We've created a timeline of events when this occurs:

Time | Component | Event
------------ | ------------- | -------------
21/05/2019 22:09:01.904 | kubelet | Kubelet starts it’s eviction manager housekeeping run: `eviction manager: synchronize housekeeping`
21/05/2019 22:09:02.078 | kubelet | Kubelet observes the imagefs.available: `eviction manager: observations: signal=imagefs.available, available: 56694416Ki, capacity: 287191336Ki, time: 2019-05-21 22:09:01.906382227 +0000 UTC m=+28630.930520654`
21/05/2019 22:09:02.078 | kubelet | Kubelet determines that it has DiskPressure, adds DiskPressure=true to internal store `eviction manager: node conditions - observed: [DiskPressure]`
21/05/2019 22:09:11.269 | (external process) | Pod is created in cluster
21/05/2019 22:09:11.279 | scheduler | Scheduler binds the pod to the node
21/05/2019 22:09:11.280 | kubelet | Kubelet receives pod from it’s WATCH: `Receiving a new pod "94eaa0f8-f3ac-4bc2-b8a0-c28f935f3108_94eaa0f8-f3ac-4bc2-b8a0-c28f935f3108(0fcae484-7c15-11e9-8294-0a0671e4d05a)"`
21/05/2019 22:09:11.287| kubelet | Kubelet doesn’t admit the pod due to disk pressure: `Failed to admit pod 94eaa0f8-f3ac-4bc2-b8a0-c28f935f3108_94eaa0f8-f3ac-4bc2-b8a0-c28f935f3108(0fcae484-7c15-11e9-8294-0a0671e4d05a) - node has conditions: [DiskPressure]`
21/05/2019 22:09:11.288 | kubelet | Kubelet creates an event for the pod saying it has been rejected: `Event(v1.ObjectReference{Kind:"Pod", Namespace:"94eaa0f8-f3ac-4bc2-b8a0-c28f935f3108", Name:"94eaa0f8-f3ac-4bc2-b8a0-c28f935f3108", UID:"0fcae484-7c15-11e9-8294-0a0671e4d05a", APIVersion:"v1", ResourceVersion:"1618978777", FieldPath:""}): type: 'Warning' reason: 'Evicted' The node was low on resource: [DiskPressure].`
21/05/2019 22:09:11.672 | kubelet | Kubelet starts its general purpose house keeping run: `kubelet.go:1995] SyncLoop (housekeeping)`
21/05/2019 22:09:11.723 | kubelet | Kubelet creates a DiskPressure event for the node: `Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-155-109-139.ec2.internal", UID:"ip-10-155-109-139.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasDiskPressure' Node ip-10-155-109-139.ec2.internal status is now: NodeHasDiskPressure`
21/05/2019 22:09:11.731 | kubelet | Kubelet updates the status for the node to with DiskPressure = true
21/05/2019 22:09:11.748 | node controller-manager | Patches the node spec, adds DiskPressure taint

As you can see from the timeline of events, there is a significant delay from when the kubelet decides that the node is in DiskPressure and when the housekeeping run on the kubelet updates the status of the node on the API server. 

This delay means that pods can be scheduled onto the node that has DiskPressure as the scheduler isn't aware that the node is in DiskPressure as the DiskPressure taint has not been applied.

This delay is due to the eviction manager housekeeping run and the general kubelet housekeeping run having a delay between their runs, resulting in a brief period where a node is in DiskPressure but is fine according to the API server.

**What you expected to happen**:

The kubelet should ideally update the status of the node as soon as it determines it is in DiskPressure, which would prevent cases where pods are scheduled on nodes in DiskPressure. This could be done in the eviction manager, rather than the general housekeeping run.

**How to reproduce it (as minimally and precisely as possible)**:

1. Put node into DiskPressure by exhausting the disk of the node
2. Observe delay between the kubelet deciding it is in DiskPressure and the node status/taints being updated much later.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.4.0
VERSION_ID=2079.4.0
BUILD_ID=2019-05-15-0808
PRETTY_NAME="Container Linux by CoreOS 2079.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-8-2-89.us-west-2.compute.internal 4.19.43-coreos #1 SMP Wed May 15 07:18:39 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools: Terraform
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Can you attach the log which corresponds to the timeline above ?

Thanks

**Comment by awprice** [comment]
@tedyu Yes, we see the following log line: 
```
I0521 22:09:02.078285    2378 eviction_manager.go:291] eviction manager: node conditions - transition period not met: [DiskPressure]
```
This is straight after it has observed that there is DiskPressure.

**Comment by tedyu** [comment]
I assume the following was also logged:
```
		klog.V(3).Infof("eviction manager: no resources are starved")
```

**Comment by awprice** [comment]
@tedyu That log line isn't logged around 22:09:02. It is then logged at 22:13:19. We have our grace period set to 5m for DiskPressure, so I would imagine thats when it started freeing disk space.

**Comment by tedyu** [comment]
I assume you have looked at https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#hard-eviction-thresholds

It seems you can specify percentage higher than the default values listed above in:
```
--eviction-hard 
```
so that the response comes earlier.

**Comment by awprice** [comment]
@tedyu We have both hard and soft thresholds configured. I don't think it's an issue with thresholds we have defined. 

It's an issue of the time delay between when the kubelet decides it is DiskPressure and when it updates the status of the node on the Kubernetes API server. It's a side effect of having the loop where the node status is updated seperate to the eviction manager loop.

You could set the thresholds to any value and this would still occur.

**Comment by tedyu** [comment]
It seems you suggest once len(nodeConditions) > 0, we should update status on API server:
```
	// Patch the current status on the API server
	updatedNode, _, err := nodeutil.PatchNodeStatus(kl.heartbeatClient.CoreV1(), types.NodeName(kl.nodeName), originalNode, node)
```

**Comment by derekwaynecarr** [comment]
Historically, we update the node object at the normal housekeeping interval to both provide a heartbeat and update of present status.  The node heartbeat is in the process of transitioning into a separate NodeLease resource after which we could begin looking at different update intervals for the node object itself.  The 10s timeline shown above looks similar to the heartbeat interval.  In general, could you use ephemeral storage requests to improve scheduling for local storage?  Is your issue primarily around image garbage collection?  Is the imagefs the same as your rootfs?

**Comment by awprice** [comment]
> It seems you suggest once len(nodeConditions) > 0, we should update status on API server:
> 
> ```
> 	// Patch the current status on the API server
> 	updatedNode, _, err := nodeutil.PatchNodeStatus(kl.heartbeatClient.CoreV1(), types.NodeName(kl.nodeName), originalNode, node)
> ```

Yep that looks like it would probably do the job.

> Historically, we update the node object at the normal housekeeping interval to both provide a heartbeat and update of present status. The node heartbeat is in the process of transitioning into a separate NodeLease resource after which we could begin looking at different update intervals for the node object itself. The 10s timeline shown above looks similar to the heartbeat interval. In general, could you use ephemeral storage requests to improve scheduling for local storage? Is your issue primarily around image garbage collection? Is the imagefs the same as your rootfs?

How often does the allocatable ephemeral storage get updated on the API server? If there is a delay, I would imagine the same issue could happen - the pod gets scheduled onto the node with insufficient ephemeral storage, but the scheduler isn't aware that there was insufficient ephemeral storage as the heartbeat/housekeeping hadn't been run in time.

Our issue isn't around the image garbage collection itself - it works perfectly for us. It's the issue with the eventual consistency of the node condition being sent to the API server and the scheduler isn't aware of it. We constantly schedule a significant number of pods, so a 10 second delay is quite significant for us.

Our imagefs is the same as the rootfs.

**Comment by tedyu** [comment]
@derekwaynecarr 
```
into a separate NodeLease resource 
```
Is there PR for the above initiative ?

thanks

**Comment by awprice** [comment]
@derekwaynecarr Are you able to provide any update on this issue?
