### ISSUE TITLE
error during ./cluster/log-dump/log-dump.sh exit status 1

### ISSUE THREAD

**Issue by IamPrvn** [kubernetes/kubernetes#78432]
I get the following error while running conformance tests using kubetest.

error during ./cluster/log-dump/log-dump.sh /builds/atd/oci_k8s_conformance_tests/conformance/k8s_release_stable-1.13/generated/_artifacts: exit status 1

The test suite passed but the log collection step failed, quick look into code does suggest that skeleton types are not a part of node_ssh_supported_providers, so ideally log collection from master and workers should have skipped.
https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L41

Additional Info -
We do not use prow CI , we run the jobs (test) in our own environment and push the results to gcp bucket.
One more observation, not sure whether it's important.
When I used to run the same test on my mac dump-logs didn't cause any nuisance. See these results
https://prow.k8s.io/view/gcs/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.11/1557807885
The above issue arises when we run the test on linux (ubuntu OS) dockers containers. See the results for ubuntu
https://prow.k8s.io/view/gcs/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.11/1558512756

**Comment by IamPrvn** [comment]
After triaging it further I got to following conclusions ;
When you run kubetest with skeleton provider kubetest --provider skeleton --dump=<some_path>, KUBERNETES_PROVIDER is not set, and when DumpClusterLogs test case is run (because dump flag is passed) this unset variable causes the difference.
The code [[ "${master_ssh_supported_providers}" =~ "${KUBERNETES_PROVIDER}" ]] returns false in case of OSX while it returns true on linux. (https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L275)

A simple test to crosscheck is to run [[ "hello" =~ "" ]] and then check echo $? in bash on both osx and linux.
Since the above logic return true skeleton is supposed to be one of ssh_supported providers and thereby tries to fetch logs from master and nodes in which it fails.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/12741#issuecomment-496603567

**Comment by IamPrvn** [comment]
yes, did set `KUBERNETES_CONFORMANCE_TEST="y"`. And setting this variable causes KUBERNETES_PROVIDER to be set to "". Refer https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-util.sh#L27

**Comment by BenTheElder** [comment]
linux at work:
```console
$ [[ "hello" =~ "" ]]

$ echo $?
0

$ echo $BASH_VERSION
4.4.19(1)-release
```
what bash version are you using?

**Comment by BenTheElder** [comment]
> The above issue arises when we run the test on linux (ubuntu OS) dockers containers. See the results for ubuntu

FWIW prow testing is running in debian linux containers mainly, I've not seen this issue from anyone else yet and this code doesn't appear to have been touched recently.

`KUBERNETES_CONFORMANCE_TEST` should indeed set these to `""` and cause these legacy provider specific paths to not be traversed, or at least this is the intention.

related: you seem to be testing v1.1.3 but linking to code from master? are you actually testing using the code in the 1.13 branch? do you see this in other branches?

I'm not able to replicate this, regulalrly invoking these tests for [the kind project](https://kind.sigs.k8s.io/) from both linux and macOS w/o a provider. The (hacky) scripts are here: https://github.com/kubernetes-sigs/kind/blob/master/hack/ci/e2e.sh

**Comment by IamPrvn** [comment]
yes, this issue arises due to difference in bash version. For bash versions 4.2+ the regex check with empty string results in status code 0 while for bash version 3.2 the regex check results in status code 2 ( it implies that that the pattern given is syntactically incorrect and maybe empty regex match attempt was not done at all).
The linux distros ship with latest bash versions [4.2+] while osx mojave still ships with 3.2.57(1)-release. So when I ran with mac I luckily got correct behaviour (log-dump was avoided) despite the fact that regex check was not done at all. 
Now I  run conformance test using kubetest. where provider is `skeleton` , deployer defaults to `bash` and `KUBERNETES_CONFORMANCE_TEST` is set to y, on a ubuntu host with 4.2+ bash versions. 
`$GOPATH/bin/kubetest --check-version-skew=false --provider=skeleton --test --test_args=\"--ginkgo.focus=\[Conformance\] --ginkgo.skip=${{SKIP}}\" --extract=vx.y.z`
This fails as the below branch does not get traversed :
`  elif [[ ! "${master_ssh_supported_providers}" =~ "${KUBERNETES_PROVIDER}" ]]; then
    echo "Master SSH not supported for ${KUBERNETES_PROVIDER}"
    return`
I think we should rather check for this condtn :- 
`elif [[ ! ( -n "${KUBERNETES_PROVIDER}" && "${master_ssh_supported_providers}" =~ "${KUBERNETES_PROVIDER}" ) ]]`

> you seem to be testing v1.1.3 but linking to code from master?are you actually testing using the code in the 1.13 branch? do you see this in other branches?
I just pasted the link from master for reference purpose. I  pass the version with the `extract` flag, so kubetest should be checking out the right branches.  Yes I have tested against the latest patch versions of  1.14, 1.13, 1.12 , and all of them fail with the same error . The intended behaviour should have been logging "Master SSH not supported for " and exiting successfully.

**Comment by IamPrvn** [comment]
>I'm not able to replicate this, regulalrly invoking these tests for the kind project from both linux and macOS w/o a provider.
You are not using the `-- dump` flag , and hence the code base for collecting remote logs is not traversed in your case.
Secondly I am just new to kubetest, I am not able to find this flags --report-dir, --disable-log-dump in kubetest cli, I thought they are args for ./hack/ginkgo-e2e.sh and kubetest being a wrapper just exposes a subset of args.

**Comment by BenTheElder** [comment]
> You are not using the -- dump flag , and hence the code base for collecting remote logs is not traversed in your case.

Right, don't use the `--dump` flag with conformance testing? :upside_down_face:  We only use it with e2e testing in kubernetes CI with one of the legacy providers. That script I linked is running in many places to do conformance testing without one of those providers.

> Secondly I am just new to kubetest, I am not able to find this flags --report-dir, --disable-log-dump in kubetest cli, I thought they are args for ./hack/ginkgo-e2e.sh and kubetest being a wrapper over it just exposes a subset of args.

kubetest can pass arbitrary flags to ginkgo through `--test_args`.

You can see those flags being set here: https://github.com/kubernetes-sigs/kind/blob/f695fb5e4ac855dba760ddefa4735ae937e53904/hack/ci/e2e.sh#L158

IMHO this API is pretty bad but it is possible. FWIW there's some work being done on a kubetest2 with a new design but it will be a while.

**Comment by IamPrvn** [comment]
Thanks @BenTheElder . That did the job.

**Comment by BenTheElder** [comment]
Great!
