### ISSUE TITLE
kubectl port-forward doesn't properly recover from interrupted connection errors

### ISSUE THREAD

**Issue by dbolkensteyn** [kubernetes/kubernetes#78446]
**What happened**:
When I open a large number (in the 100s) of concurrent long-running HTTP requests against a port-forwarded pod that is running on GKE 1.13.6-gke.0 which I then interrupt/cancel, I observe timeout errors being reported by `kubectl port-forward pod/[pod_name] 8000:8000`. Eventually, the forwarded port becomes permanently unusable until I relaunch the command.

Types of messages that get logged by `kubectl port-forward`:
1. `Handling connection for 8000`
1. `E0528 16:12:42.255465   13724 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8000->127.0.0.1:62974: write tcp4 127.0.0.1:8000->127.0.0.1:62974: wsasend: An established connection was aborted by the software in your host machine.`
1. `E0528 16:13:12.495226   13724 portforward.go:293] error creating forwarding stream for port 8000 -> 8000: Timeout occured`
1. `E0528 16:13:53.891935   13724 portforward.go:271] error creating error stream for port 8000 -> 8000: Timeout occured`

After the port-forward becomes permanently unusable, I still see incoming requests logged as:
```
Handling connection for 8000
```

which then all fail about 30 seconds later with the following error, without the request being set to the pod:
```
E0528 16:38:06.245530    6668 portforward.go:271] error creating error stream for port 8000 -> 8000: Timeout occured
```

**What you expected to happen**:

1. Never have to relaunch `kubectl port-forward` because it is in a permanent failed state
1. All concurrent long-running HTTP requests to succeed (up to some reasonable amount of them of course)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an nginx pod serving a large 1GB static file:
    ```
    kubectl run -ti --rm --restart=Never --image=nginx nginx -- bash "-c" "dd if=/dev/zero of=/usr/share/nginx/html/large_file.bin count=1024 bs=1048576 && nginx -g 'daemon off;'"
    ```
1.  Port-forward it: `kubectl port-forward nginx 1234:80`
1. Run [Apache Bench](https://httpd.apache.org/docs/2.4/programs/ab.html) with 100 total requests, 100 concurrent ones and 1 second timeout, that you interrupt using Control+C (for some reason the timeout doesn't seem to be well enforced):
    ```
    ab -n 100 -c 100 -s 1 http://127.0.0.1:1234/large_file.bin
    ```
    Note that in my initial use-case, I managed to get this issue simply by quickly refreshing the URL in Google Chrome without any benchmarking tool.
1. If needed, re-run the same Apache Bench command until the port-forwarding fails to serve all incoming requests
1. Observe that now all requests to the nginx servers, even to http://127.0.0.1:1234/index.html are all failing. Additionally, nginx doesn't output those requests in its logs.
1. Relaunch the `kubectl port-forward nginx 1234:80` command, and the URL becomes available again showing that the pod was still healthy. 

**Anything else we need to know?**:

Possibility related issues & PRs:
- https://github.com/openshift/origin/issues/4287 - reports a similar bug
- https://github.com/kubernetes/kubernetes/issues/13673
- https://github.com/kubernetes/kubernetes/pull/12283

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:28:02Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.0", GitCommit:"14c9138d6fb5b57473e270fe8a2973300fbd6fd6", GitTreeState:"clean", BuildDate:"2019-05-08T16:22:55Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE 1.13.6-gke.0
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`): Windows
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dbolkensteyn** [comment]
I have just added precise instructions on how to reproduce. Please do let me know if anything else is needed.

**Comment by dbolkensteyn** [comment]
FYI, exposing the pod to the host through a `NodePort` service instead of a `port-forward` makes the pod's server reliably accessible:

```
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    run: nginx
```

**Comment by jerrylam** [comment]
any update on this? I have this issue everyday. I wonder if there is a workaround at least?

**Comment by cksassy** [comment]
Same error when port-forwarding to AWS EKS pod:

`E0806 17:04:44.805492   78962 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:3000->[::1]:61216: read: connection reset by peer`

kubectl version:

`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)`

**Comment by KotieSmit** [comment]
Does anybody have a solid workaround for this?

**Comment by 0xVox** [comment]
While this is no solution for the port-forward recovering properly, I did find it solved my use-case. 

When trying to tunnel to a mysql box we couldn't keep a connection alive for more than ~60 seconds, completely ruining the experience for anyone running long-running queries. 

By creating a new connection regularly we seemed to be able to keep the port-forward tunnel open.

- Start your port-forward command
- Write something that can ping the pod every 20 seconds on the target port, for our usecase we just have `mysqladmin ping -h 127.0.0.1` running in a loop 
- Run your intended long-running command alongside this ping script.

**Comment by pravinyo** [comment]
I am also facing similar issue 
$ k port-forward service/reverseproxy 8080:8080
error: timed out waiting for the condition

Here is my Kubecli details:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by reecebenson** [comment]
> I'm giving up on this

It's a shame as this issue is entirely present and _very_ frustrating. I've been battling it for a few days now...
/remove-lifecycle stale

**Comment by deltawi** [comment]
Any updates on this ? I have the same isssue when I try port-forwarding Airflow webserver 

`E0708 16:13:42.769394 51449 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:56960: write tcp6 [::1]:8080->[::1]:56960: write: broken pipe E0708 16:14:43.427643 51449 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured`

**Comment by moewill** [comment]
Not a true solution, but helps in the meantime

while true; do
<port-forward command>
done

**Comment by taisph** [comment]
This issue bubbles up to the `skaffold` tool as well. Running `skaffold dev --port-forward` will exhibit the same connection issues after a while.

**Comment by dbolkensteyn** [comment]
/remove-lifecycle stale

so let's remove the stale state

**Comment by pickfire** [comment]
I have this issue too but I use curl in one of the pods within kubernetes and curl the ip address of the pod directly as a workaround now.

**Comment by empinator** [comment]
0xVox's comment helped my to work around this issue

I wrote small bash script which I run after I start the port-forward in a second terminal. It initiates a new, brief connection every X seconds. This way the connection handling stays open if you have long running jobs like database dumps (mysql, mongo, etc.)

**Comment by pickfire** [comment]
I had to do ssh local forward and run the same command remotely, extra 10 characters or so, quite troublesome.

**Comment by mbsulliv** [comment]
> Does anybody have a solid workaround for this?

I tried @moewill's loop solution, but most of the time, kubectl wouldn't exit when the error occurred, leaving it stranded in a failed state until I manually hit CTRL+C (and the loop relaunched it).

To address the problem, I cloned the kubectl source and modified it to exit whenever an error occurs.  This appears to be a pretty good workaround for my use case since when the loop relaunches it, everything starts working again.  Maybe this workaround would help folks out until a proper fix is merged.  I'll try to put together a pull request.

**Comment by aojea** [comment]
duplicate of https://github.com/kubernetes/kubectl/issues/686

**Comment by Speedkore** [comment]
this is not fixed yet, come on, random problems are the worst

**Comment by philipcwhite** [comment]
I have this issue as well when connecting to GKE and port forwarding.  It works for some things but for slower queries it blows up.  When trying to pull data from Managed Prometheus into Grafana its a no go.  Once the pipe breaks it no longer works period.

**Comment by atinsinghal97** [comment]
I've been using this as a workaround: https://github.com/atinsinghal97/kubectl-port-forward-heaven

**Comment by philipcwhite** [comment]
Thanks @atinsinghal97.  This does seem to help.  For my particular issue I believe the fault is with Grafana (older builds have no issues) however this may be useful for testing that I'm doing sending OpenTelemetry data forward from my local machine.

**Comment by horihel** [comment]
retested with 1.22.9 - still a problem

please
/remove-lifecycle stale

**Comment by horihel** [comment]
Just FYI: Alternatives are becoming harder: our go-to alternative "kube-forwarder" is unmaintained for years and has problems talking to newer clusters.
port-forwarding is still a preferred way of accessing cluster-resources, as it doesn't require manipulation on any side (most alternative solutions at least need to manipulate DNS on the client).
If anyone finds a stable alternative implementation instead of kubectl's broken one, i'd be happy to know.

**Comment by dims** [comment]
cc @aojea @thockin  - Looks like a long standing issue :(

**Comment by robey** [comment]
/remove-lifecycle stale

this still happens with shocking regularity. i can't believe the authors are lucky enough to have it never happen to them.

**Comment by aojea** [comment]
This is a feature that is part of the apiserver and kubectl, proxying a local socket to a pod through a chain of proxies

https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls

I would not consider the port-forward mechanism something to use in production, Kubernetes networking already offer different mechanism to access the pods, 

https://kubernetes.io/docs/concepts/services-networking/

I'm curious about the use cases of `port-forward` and why people have such high expectations from it, if the people complaining is able to summarize the requirements and expectations, and the reasons to not use the kubernetes networking features, I can spend some time on proposing a better alternative or try to improve current feature

**Comment by horihel** [comment]
Here's (only) my case:
all of the usual networking options normally involve exposing the service to the internet.
- From the above comments, many people use a basic version of grafana, probably not configured for internet exposure (or sometimes company policy prevents it anyway). I used this example because grafana is exceptionally easy to break through port-forward (it breaks within minutes, requiring a restart of the forwarding).
- we use it mostly for developers who already have access to their namespaces for easy access to backend services that should also not be exposed to the internet. They already have their service account and RBAC set up. It's useful to be able to push or pull a database dump. It's much harder when your connection tunnel is unstable.

On the tools side, many tools (minikube for example) seem to rely on port-forward too.

On the dev-side (using minikube or other dev-cluster tools that don't provide a stable IP for your Nodeports/Loadbalancers) it's just very convenient to just know that you can use `localhost` with a known port in your scripts instead of looking up the IP every time (and maybe changing your hosts file).

port-forward is the only tunneling approach (that I know) that doesn't need elevation (or root on linux).

**Comment by horihel** [comment]
/remove-lifecycle rotten

i'm not too sure about this though as I was the only one that came up with a use case

**Comment by spacepluk** [comment]
I think the grafana issue is very common, or at least there's a lot of people talking about it if you google it.
FWIW I run into it daily and would like to see it fixed hehe

**Comment by robey** [comment]
My company uses it to access internal services that require auth to visit, like build servers. These sessions can last a long time, but are usually interrupted by the port forward crashing. The only way to notice is to see that the site has become unresponsive and go check the terminal for port forwarding timeouts and restart it.

If there was an alternate, more reliable way to handle authenticated port access, I could probably convince them to switch to it.

**Comment by NamelessVoice** [comment]
Here's a rather ugly hack/workaround Bash script to automatically restart the port forwarding when it crashes.

Change the value variable to the appropriate port forwarding command.

It will run port forwarding, then parse the output stderr for errors; if the errors contain "portforward.go" (which these kind of errors do), then it will restart; if the port forwarding exists for any other reason (such as the process being killed, or a legitimate error, then it will exit instead.

This could probably be written nicer, but it works for my purposes.

    value='kubectl port-forward svc/service-name 8001:80'
    while true; do
          echo "--> $value"
          $value 2>&1 >/dev/null |
          while IFS= read -r line
          do
                echo "### $line"
                if [[ "$line" == *"portforward.go"* ]]; then
                      echo "Retarting port forwarding $value"
                      exit 1
                else
                      exit 0
                fi
          done
          if [ $? -eq 0 ]; then
                break;
          fi
    done

**Comment by krichter722** [comment]
also related/similar: https://github.com/kubernetes/kubernetes/issues/19231

**Comment by doskhandoszhanov** [comment]
/remove-lifecycle stale
issue persists
