### ISSUE TITLE
Cannot run go tests in legacy-cloud-provider/gce

### ISSUE THREAD

**Issue by prameshj** [kubernetes/kubernetes#78456]
**What happened**:
Running "go test" inside staging/src/k8s.io/legacy-cloud-providers/gce throws error similar to this:

"code in directory src/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce expects import "k8s.io/legacy-cloud-providers/gce""

The same command works when invoked from vendor/k8s.io/legacy-cloud-providers/gce

**What you expected to happen**:
go test should work from either directory
**How to reproduce it (as minimally and precisely as possible)**:
 cd staging/src/k8s.io/legacy-cloud-providers/gce/ && go test

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by prameshj** [comment]
cc @MrHohn @cheftako

**Comment by MrHohn** [comment]
cc @BenTheElder :)

**Comment by BenTheElder** [comment]
I wouldn't expect that to work for _any_ of the staging repos if run from k8s.io/kubernetes/staging/... unless you fiddle with your gopath.

**Comment by MrHohn** [comment]
> I wouldn't expect that to work for any of the staging repos if run from k8s.io/kubernetes/staging/... unless you fiddle with your gopath.

It in fact works from inside of `staging/src/k8s.io/legacy-cloud-providers/aws` and hence we are baffled :)

**Comment by BenTheElder** [comment]
took a poke at this locally.

https://github.com/kubernetes/kubernetes/blob/3ccb63bb1b4d8a9e9a5e32bdd2750e44a6067ad4/staging/src/k8s.io/legacy-cloud-providers/gce/doc.go#L19

is why

**Comment by MrHohn** [comment]
Thanks Ben! Wasn't aware of this [import path checking](https://golang.org/pkg/cmd/go/#hdr-Import_path_checking) until now :)

**Comment by prameshj** [comment]
Thanks Ben! I learnt something :) 
Closing this issue since it is working as intended.
/close
