### ISSUE TITLE
Could not create route for hollow node in kubemark

### ISSUE THREAD

**Issue by nikhilsap** [kubernetes/kubernetes#78483]
**What happened**:
i tried using Kubemark in a pre-existing cluster. The framework runs properly without any issues. The hollow-pods created and registered as node. 
But when i do `kubectl describe node hollow-node`,i can see this error.

`Warning  FailedToCreateRoute  9s    route_controller  Could not create route f26a850b-81ee-11e9-a072-b2f06bc2a29d 100.96.99.0/24 for node hollow-node-4kc9s after 486.555595ms: instance not found`

we tried looking in to kubelet log, it shows 

`E0529 12:06:12.827327       5 desired_state_of_world_populator.go:309] Failed to add volume "kube-proxy-config" (specName: "kube-proxy-config") for pod "26febc5a-820a-11e9-a072-b2f06bc2a29d" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "kube-proxy-config" err=no volume plugin matched
E0529 12:06:12.827352       5 desired_state_of_world_populator.go:309] Failed to add volume "ssl-certs-hosts" (specName: "ssl-certs-hosts") for pod "26febc5a-820a-11e9-a072-b2f06bc2a29d" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "ssl-certs-hosts" err=no volume plugin matched
E0529 12:06:12.827366       5 desired_state_of_world_populator.go:309] Failed to add volume "systembussocket" (specName: "systembussocket") for pod "26febc5a-820a-11e9-a072-b2f06bc2a29d" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "systembussocket" err=no volume plugin matched
E0529 12:06:12.827386       5 desired_state_of_world_populator.go:309] Failed to add volume "kernel-modules" (specName: "kernel-modules") for pod "26febc5a-820a-11e9-a072-b2f06bc2a29d" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "kernel-modules" err=no volume plugin matched
I0529 12:06:12.8`

**What you expected to happen**:
The hollow-pod should properly registered as node and act as a node.

**How to reproduce it (as minimally and precisely as possible)**:
Use kubemark for pre-existing cluster.
**Anything else we need to know?**:
Internal-Ip for other node is `10.250.0.58`
**Environment**:
- Kubernetes version (use `kubectl version`):
v1.14.0
- Cloud provider or hardware configuration:
GCP

**Comment by snowplayfire** [comment]
I have recorded how to setup a kubemark cluster outside GCE as follows: https://github.com/snowplayfire/kubemark-outside-gce

Hope it is helpful for you.

**Comment by a85302543** [comment]
i have encounter this problem recently! any solution?
