### ISSUE TITLE
Split apiserver latency metrics on return code.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#78481]
We should split metrics exposed from apiserver on code as well. E.g. the fact that 99% of requests are responded very quickly is not that interesting if those 99% are 429s. I'm not quite sure we want to have buckets for each error code, or each error code class (2xx, 3xx, 4xx, 5xx). Ones that I'm interested in are 2xx.

If someone has opinions on bucketing (or thinks it's a terrible idea) let me know soon-ish, as I plan to send PR this or next week.

@kubernetes/sig-api-machinery-misc @wojtek-t @liggitt @lavalamp

**Comment by liggitt** [comment]
cc @logicalhan for cost of additional timeseries on this metric in particular

**Comment by gmarek** [comment]
Yeah - it's pretty heavy. We may need to figure out what do to with it in the long run. Sad reality is that it's currently the best way to judge load on apiserver:/ Having said that I'm more worried about the 'component' label, which IIUC can have unbounded cardinality. Here we can reasonably reduce blowup to 4x (I can't believe I wrote that:/).

**Comment by logicalhan** [comment]
What exactly are you thinking about doing here?

**Comment by logicalhan** [comment]
Component is actually one of two known values. Resource and subresource are unbounded (due to CRDs) and client is also an unbounded string.

**Comment by wojtek-t** [comment]
Note that in majority of metrics we already split by code:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go

> If someone has opinions on bucketing (or thinks it's a terrible idea) let me know soon-ish, as I plan to send PR this or next week.

We're enterring code-freeze tomorrow - so won't be merged soon...


Regarding overall idea, I agree it would be useful and we would need that for refining SLI/SLO (something that I talked about during my kubecon talk).
My personal intuition (though we need some real numbers probably) is that it should be fine, given all the metrics already have it.

**Comment by tedyu** [comment]
@gmarek 
Do you want to pick this up ?
