### ISSUE TITLE
Why "Simple Leader Election with Kubernetes and Docker" no longer exists in K8S source code?

### ISSUE THREAD

**Issue by nguyenuet** [kubernetes/kubernetes#78508]
We know that K8S used to have its own leader election:
https://github.com/kubernetes-retired/contrib/tree/master/election

I think it is very important. Some application can use the leader election in K8S for simple application instead of using Raft or Zookeeper.

But I do not know why this simple leader election no longer exists in K8S source code. 
Now, It has an example in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/examples/leader-election. But it is totally different from the target of the previous one.

Someone can help me? Is there any technical problem here.
If not, I think we should update this simple leader election code to the current source code

/sig Apps

**Comment by BenTheElder** [comment]
The entire contrib repo was out of date / poorly maintained, and was "retired". Note that many things are not in the main repo (this one) anymore as the project is very big, many are even in other organizations, in particular https://github.com/kubernetes-sigs


https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/examples/leader-election is probably the preferred example currently
