### ISSUE TITLE
hack/update-bazel doesn't add integration tags

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#78527]
**What happened**:
when running `hack/update-bazel.sh` integration tags were missing on `BUILD` files

**What you expected to happen**:
add the needed tags on test/integration `BUILD` files

**How to reproduce it (as minimally and precisely as possible)**:

add an integration test package under `test/integration`

cc @liggitt

**Comment by BenTheElder** [comment]
if we want to assume that all tests in a certain directory are integration tests this is very easy to automate, here's an example that we do now to mark `vendor/...` go tests and binaries as `manual`

https://github.com/kubernetes/kubernetes/blob/5267a3dc730ff606cb5b1d1a4ee05ef04ae7ed3b/hack/update-bazel.sh#L78

**Comment by BenTheElder** [comment]
Is the assumption that all tests in `test/integration/` should be tagged as integration?

I'd be happy to add this to the script, but would prefer to get https://github.com/kubernetes/kubernetes/pull/79287 in without conflicts first 😅
