### ISSUE TITLE
Improved test progress reporting

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#78535]
**What would you like to be added**:
I would like a method of seeing more clear data while tests are running, e.g.:
 - How many tests will be run, have been run, have passed, have failed, etc.
 - Name of the tests passed/failed/skipped

**Why is this needed**:
While a run is going we _only_ have the output from stdout to investigate. There is a LOT of noise in those logs which is great for debugging after the fact, but difficult to consume most of the time.
 - you can't tell how many tests have been run or get a sense of how much time is left
 - you cant easily get a list of all tests that have failed so far

**My proposal**
 - Adding a new, custom ginkgo reporter that will post the data to a given URL (passed via a flag)
 - if the URL isn't set, the reporter is a noop and doesn't waste time/resources

Use cases:
 - A user runs the tests dumps stdout to a file for debugging later, meanwhile they run a local server that will just echo the status updates it gets. At any point they look at the output they can get good data about what would be run, how far along it is, how successful it has been so far.
 - Using the conformance test image and Sonobuoy, the Sonobuoy worker can act as the server, taking those status updates and reporting them to the aggregator. This would allow Sonobuoy to present that information to users on demand or stream it depending on the context.

The work of adding this is pretty minimal and is clearly useful.  In the case of Sonobuoy; this has been the most requested feature for a long time showing that people in the community really do want to have a better high-level picture of the progress of these tests. I think emitting the data to an endpoint like this is a flexible implementation that can help any consumer of the tests (not just Sonobuoy).

**Comment by taojwmware** [comment]
One notification URL should work fine. Can you give me details on the data model for the status data to be published?

**Comment by johnSchnake** [comment]
That is one, slightly TBD area.

The reporter in the test framework has a bunch of data and I'm not sure what we exactly Sonobuoy may want from any given plugin (not just the e2e plugin). I don't want this implementation to be overly Sonobuoy specific or overly e2e specific.

Will update when something more clear is pinned down.

**Comment by johnSchnake** [comment]
Brought this up in the testing commons meeting and it was agreed that this approach seemed reasonable and that the customReporters seemed like the only way to generate this data.

In addition, it was requested that we find a way to also emit this (or some variation) into stdout/logs so that it is easier for a human to navigate those verbose logs.
