### ISSUE TITLE
The container running permission under Ubuntu system is always root

### ISSUE THREAD

**Issue by TimeBye** [kubernetes/kubernetes#78566]
**What happened**:
The container running permission under Ubuntu system is always root.
![image](https://user-images.githubusercontent.com/22651579/58691899-e83fd380-83bf-11e9-8605-3ec9980ad448.png)

**What you expected to happen**:
The container run permissions should be non-root.
![image](https://user-images.githubusercontent.com/22651579/58691810-a020b100-83bf-11e9-9a0d-b7ee28c3bbec.png)

**How to reproduce it (as minimally and precisely as possible)**:

OS: Ubuntu 16.04
docker-ce: 18.09.6
kubernetes: v1.14.2

run:
```
kubectl run sonarqube --image=sonarqube:7.6-community --rm -it --command bash
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.2
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 
- Install tools: kubeadm v1.14.2
- Network plugin and version (if this is a network-related bug): flannel
- Others:

**Comment by veeshall** [comment]
Could be related to #78308

**Comment by TimeBye** [comment]
I tried to switch to a lower version of Docker and it worked fine.
