### ISSUE TITLE
terminationMessagePolicy: FallbackToLogsOnError should be the default

### ISSUE THREAD

**Issue by DavidSimner** [kubernetes/kubernetes#78570]
**What would you like to be added**:
I would like the default for `terminationMessagePolicy` changed to `FallbackToLogsOnError`.

**Background**:
Quoting from the docs for `terminationMessagePolicy`:
> Indicate how the termination message should be populated. `File` will use the contents of `terminationMessagePath` to populate the container status message on both success and failure. `FallbackToLogsOnError` will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to `File`. Cannot be updated.

**Why is this needed**:
As a new user to k8s, I will generally have an application already, and that application will, most of the time, already log to stdout and/or stderr.

During the process of initially adopting k8s I'm inevitably going to make a mistake that causes my application (and therefore the container) to die.  When that happens, it would be great if my existing logging could be leveraged to explain to me why that happened.

Because I'm a new user, I won't have read the extensive documentation and learnt that if only I changed `terminationMessagePolicy` to look at stdout/stderr, or if only I changed my application to write to a file with a certain path, then I'd get to know why it failed.  But as a new user I won't have done any of those things, and it'd be nice if k8s showed me my existing stdout/stderr logging by default, so that I can easily know what is causing my application to die.

This will *not* be a breaking change, because existing users who are used to `File` and who are writing a file to `terminationMessagePath` (e.g. `/dev/termination-log`) will continue to get the contents of that file as the termination message.

Given that it makes life considerably easier for new users, and that it isn't a breaking change, I believe that the default `terminationMessagePolicy` should be changed to `FallbackToLogsOnError`

**Comment by DavidSimner** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by K3UL** [comment]
/reopen

What a horrible way to treat issues, to be honest

**Comment by minac** [comment]
@DavidSimner I believe this is a problem still for everyone. Is it still for you? 
If so could you please reopen the issue so that the right people (not bots) have a look at it.
Thank you for raising it in the first place, it's an obscure way to treat the final logs.
