### ISSUE TITLE
Two questions about flexvolume

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#78576]
I have two questions about flexvolume and hope to get your answers.
1.kubelet will periodically call the interface of flexvolume.How often is it called?
2.Why isn't the detach method I wrote for flexvolume called by kubelet?

**Comment by timyinshi** [comment]
@kubernetes/sig-storage

**Comment by BenTheElder** [comment]
/sig storage
you might have better luck checking with their slack channel or other venues, github notifications for this repo are pretty unmanageable.

**Comment by timyinshi** [comment]
@BenTheElder i got the answer,thanks.
