### ISSUE TITLE
All besteffort pods will be cleaned up if update allocatable memory limits of kubepods to a lower value

### ISSUE THREAD

**Issue by chestack** [kubernetes/kubernetes#78580]
**What would you like to be added**:
current_memory_usage_of_pods = cat /sys/fs/cgroup/memory/kubepods/memory.usage_in_bytes
current_memory_limit_of_pods = cat /sys/fs/cgroup/memory/kubepods/memory.limit_in_bytes

update kubelet configuration file to make new value of memory_limit_of_pods < current_memory_usage_of_pods
restart kubelet
All besteffort pods on this node will be cleaned up within about one minute

example as following:
```
[root@node-3 ~]# cat /sys/fs/cgroup/memory/kubepods/memory.usage_in_bytes
15894454272
[root@node-3 ~]# cat /sys/fs/cgroup/memory/kubepods/memory.limit_in_bytes
16232861696
[root@node-3 ~]# cat /etc/kubernetes/kubelet.env | grep -E "enforce|system-reserved"
--enforce-node-allocatable=pods  --cluster-dns=10.233.0.3 --cluster-domain=cluster.local --resolv-conf=/etc/resolv.conf --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml --system-reserved cpu=1024m,memory=18483Mi  --node-labels=node-role.kubernetes.io/master=true,node-role.kubernetes.io/node=true  --feature-gates=Initializers=False,PersistentLocalVolumes=False,ExpandPersistentVolumes=True,ReadOnlyAPIDataVolumes=False   --eviction-hard=memory.available<512Mi  --eviction-soft-grace-period=memory.available=90s  --eviction-max-pod-grace-period=120  --eviction-soft=memory.available<1024Mi "
[root@node-3 ~]# update configfile
-bash: update: command not found
[root@node-3 ~]#
[root@node-3 ~]# vim /etc/kubernetes/kubelet.env
[root@node-3 ~]# cat /etc/kubernetes/kubelet.env | grep -E "enforce|system-reserved"
--enforce-node-allocatable=pods  --cluster-dns=10.233.0.3 --cluster-domain=cluster.local --resolv-conf=/etc/resolv.conf --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml --system-reserved cpu=1024m,memory=20483Mi  --node-labels=node-role.kubernetes.io/master=true,node-role.kubernetes.io/node=true  --feature-gates=Initializers=False,PersistentLocalVolumes=False,ExpandPersistentVolumes=True,ReadOnlyAPIDataVolumes=False   --eviction-hard=memory.available<512Mi  --eviction-soft-grace-period=memory.available=90s  --eviction-max-pod-grace-period=120  --eviction-soft=memory.available<1024Mi "
[root@node-3 ~]#
```
current_memory_usage_of_pods = 15894454272 = **15158Mi**
current_memory_limit_of_pods = 16232861696 = **15480Mi**
--enforce-node-allocatable=pods is configured
update --system-reserved memory from **18483Mi to 20483Mi** to make new value of memory_limit_of_pods < current_memory_usage_of_pods

**Something  found**:
deep into the log,  I found the process is:

kl.updateRuntimeUp --> evictionManager.Start --> synchronize --> MemoryPressure
(allocatableMemory.available, available: -2085748Ki < 0)
kl.syncLoop --> HandlePodAdditions --> Admit --> reject --> SetPodStatus Failed

**Why is this needed**:

From the annotation[1] 

> "Pod Evictions are expected to bring down memory usage to below Node Allocatable limits"

I think this is not expected, not a good solution at least.

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/node_container_manager_linux.go#L83-L88

**Comment by chestack** [comment]
@vishh , you are the author of this commit “add support for node allocatable phase 2 to kubelet” which is related with this issue.
I will appreciate that you could take a look at this issue if you have time. Thanks

**Comment by mattjmcnaughton** [comment]
@chestack thanks for creating this issue - I'm having a little bit of difficulty understanding the change you're hoping for. Could you add a high level summary of the change you are asking for?

**Comment by chestack** [comment]
@mattjmcnaughton actually I am not sure if this is expected yet, so open this issue for discussion. 

IMO, set all besteffort pods status to Failed then to clean up is a big move for cluster. Maybe eviction process  is a better choice: rank pods --> evict one pod during each interval --> re-compute the node conditions
