### ISSUE TITLE
Conformance image should surface more (or any) flag options

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#78599]
**What would you like to be added**:
A way to set generic flags when calling the conformance test image.

**Why is this needed**:
Currently it just respects a handful of flags in an effort to be simple for callers. However, someone has reported a need to set one of the DNS flags https://github.com/heptio/sonobuoy/issues/733 and there isn't a real reason we don't surface _that_ flag. The problem is that there are so many other options, we'd have to add N env vars and keep it up to date as new flags get added.

Instead I think it might make sense to just add 2 more env vars: `GINKGO_FLAGS` and `E2E_FLAGS` which would all the user to set arbitrary values. Consider the previous env vars as easy-buttons and these as power-user functions. If set, we'd just append those to the ginkgo/e2e flags we invoke the tests with.

This would unblock any testing need related to flags.

/sig testing
/area conformance

**Comment by dims** [comment]
@johnSchnake i'd support this

**Comment by johnSchnake** [comment]
So my advanced use case for this is setting the `afterSuiteHook` flag which provides an arbitrary command to ginkgo to execute after the suite finishes.

The problem I think boils down to bash and the complications of it getting in the way and trying to interpret everything/escape things as it sees fit. I've found it impossible to set a reasonable command `echo foo` in a way through the env vars that gets used correctly from the env var.

In any case, having a single flag does make it potentially messy/complicated in these cases where you might need quotes or special characters. It makes it difficult if not impossible to properly pass things from your shell/CLI -> yaml -> env var -> CLI option via bash.

Generally when this sort of behavior is desired, a flag/option framework like cobra is used which allows you to correlate any env var to its flag version (e.g. E2E_DRYRUN -> -dryrun). I'm thinking that we may want to consider replacing the shell script with a small go app that we can better manipulate flags/control flow/etc. Even if we have to wire more up, it would be more natural to do so in something like Go than in a bash script IMO.

Another example of something that this (a go-runner) would help fix are things like: https://github.com/kubernetes/kubernetes/issues/78699 since we can better handle flow control in Go.

To be clear, I'm not suggesting we outright replace the bash script (where we would risk breaking the image effectively if the go runner wasn't quite right) but that we support both for a time and see how it works. If the go binary solves this problem and works correctly then we may be able to remove the bash script at some point, but for the time being we could just have the binary and it would represent a second possible entry point for the image.

Will have a think about this. It is a "small" task to create a few more options, but if done well it may be some of the last we have to do so I want to get it right.
