### ISSUE TITLE
Current conformance tests call non-GA APIs

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#78613]
**What happened**:

We have defined the requirements of conformance tests should call GA APIs only as `it tests only GA, non-optional features or APIs (e.g., no alpha or beta endpoints, no feature flags required, no deprecated features)` on https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements
However current conformance tests call non-GA APIs, they are not only Beta but also Alpha APIs.

The calling count of Alpha APIs is 25, the one of Beta APIs is 6818.

**What you expected to happen**:

Conformance tests call GA APIs only as the requirement.

**How to reproduce it (as minimally and precisely as possible)**:

The PR which enables API operation logs is https://github.com/kubernetes/kubernetes/pull/78606 and see `e2e.log` which contains non-GA API calls as https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/78606/pull-kubernetes-conformance-image-test/1134585482726871040/artifacts/

**Anything else we need to know?**:

How to check it:
```
$ wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/78606/pull-kubernetes-conformance-image-test/1134585482726871040/artifacts/e2e.log
$ egrep "(GET|POST|PUT|DELETE|HEAD) http" e2e.log | grep beta | wc -l
6818
$ egrep "(GET|POST|PUT|DELETE|HEAD) http" e2e.log | grep alpha | wc -l
25
```

**Comment by oomichi** [comment]
I think we need to remove Alpha API calls at least, the APIs are
```
$ egrep "(GET|POST|PUT|DELETE|HEAD) http" e2e.log | grep alpha | awk -F "] " '{print $2}'  | sed s/"https:\/\/10.96.0.1:443"//g | sort | uniq
DELETE /apis/apiregistration.k8s.io/v1beta1/apiservices/v1alpha1.wardle.k8s.io
DELETE /apis/wardle.k8s.io/v1alpha1/namespaces/aggregator-6186/flunders/dynamic-flunder-1262545286
DELETE /apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders/rest-flunder-106783861?timeout=32s
GET /apis/apiregistration.k8s.io/v1beta1/apiservices/v1alpha1.wardle.k8s.io
GET /apis/wardle.k8s.io/v1alpha1/namespaces/aggregator-6186/flunders
GET /apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders?timeout=32s
GET /apis/wardle.k8s.io/v1alpha1?timeout=32s
POST /apis/wardle.k8s.io/v1alpha1/namespaces/aggregator-6186/flunders
POST /apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders?timeout=32s
```

**Comment by liggitt** [comment]
we can rename them to v1 to avoid confusion if we want, but those are just test fixtures

**Comment by oomichi** [comment]
@liggitt Thanks, I see we need to filter out these Alpha APIs as non-problem.

The called Beta APIs are 50 and they are
```
$ egrep "(GET|POST|PUT|DELETE|HEAD) http" e2e.log | grep beta | awk -F "] " '{print $2}'  | sed s/"https:\/\/10.96.0.1:443"//g | sed s/"namespaces\/.*\/"/"namespaces\/.
.\/"/g | sort | uniq
DELETE /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/foo5njtqas.mygroup.example.com
DELETE /apis/apiregistration.k8s.io/v1beta1/apiservices/v1alpha1.wardle.k8s.io
DELETE /apis/mygroup.example.com/v1beta1/foo5njtqas/setup-instance
DELETE /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/wardler:aggregator-6186:auth-delegator
DELETE /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/wardler:aggregator-6186:sample-apiserver-reader
DELETE /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/sample-apiserver-reader
DELETE /apis/rbac.authorization.k8s.io/v1beta1/namespaces/../wardler-auth-reader
GET /apis/admissionregistration.k8s.io/v1beta1?timeout=32s
GET /apis/apiextensions.k8s.io/v1beta1?timeout=32s
GET /apis/apiregistration.k8s.io/v1beta1/apiservices/v1alpha1.wardle.k8s.io
GET /apis/apiregistration.k8s.io/v1beta1?timeout=32s
GET /apis/apps/v1beta1?timeout=32s
GET /apis/apps/v1beta2?timeout=32s
GET /apis/authentication.k8s.io/v1beta1?timeout=32s
GET /apis/authorization.k8s.io/v1beta1?timeout=32s
GET /apis/autoscaling/v2beta1?timeout=32s
GET /apis/autoscaling/v2beta2?timeout=32s
GET /apis/batch/v1beta1/namespaces/../cronjobs
GET /apis/batch/v1beta1?timeout=32s
GET /apis/certificates.k8s.io/v1beta1?timeout=32s
GET /apis/coordination.k8s.io/v1beta1?timeout=32s
GET /apis/events.k8s.io/v1beta1/namespaces/../events
GET /apis/events.k8s.io/v1beta1?timeout=32s
GET /apis/extensions/v1beta1/namespaces/../daemonsets
GET /apis/extensions/v1beta1/namespaces/../deployments
GET /apis/extensions/v1beta1/namespaces/../ingresses
GET /apis/extensions/v1beta1/namespaces/../networkpolicies
GET /apis/extensions/v1beta1/namespaces/../replicasets
GET /apis/extensions/v1beta1?timeout=32s
GET /apis/mygroup.example.com/v1beta1/foo5njtqas?resourceVersion=7896&watch=true
GET /apis/mygroup.example.com/v1beta1?timeout=32s
GET /apis/networking.k8s.io/v1beta1/namespaces/../ingresses
GET /apis/networking.k8s.io/v1beta1?timeout=32s
GET /apis/node.k8s.io/v1beta1?timeout=32s
GET /apis/policy/v1beta1/namespaces/../poddisruptionbudgets
GET /apis/policy/v1beta1/podsecuritypolicies
GET /apis/policy/v1beta1/podsecuritypolicies/e2e-test-privileged-psp
GET /apis/policy/v1beta1?timeout=32s
GET /apis/rbac.authorization.k8s.io/v1beta1/clusterroles
GET /apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
GET /apis/scheduling.k8s.io/v1beta1?timeout=32s
GET /apis/storage.k8s.io/v1beta1?timeout=32s
POST /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
POST /apis/apiregistration.k8s.io/v1beta1/apiservices
POST /apis/authorization.k8s.io/v1beta1/subjectaccessreviews
POST /apis/mygroup.example.com/v1beta1/foo5njtqas
POST /apis/policy/v1beta1/podsecuritypolicies
POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings
POST /apis/rbac.authorization.k8s.io/v1beta1/clusterroles
POST /apis/rbac.authorization.k8s.io/v1beta1/namespaces/../rolebindings
```

**Comment by oomichi** [comment]
CRD e2e test exists as conformance test like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/custom_resource_definition.go#L41

From liggitt's help on the slack:
```
CRDs are planned to go to v1 in 1.16, and planned to add to conformance as part of that
it's good to have that issue and something in place to make sure we don't accidentally add new uses of beta APIs in conformance
```

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/78614 switching the APIService, RBAC, and SubjectAccessReview uses to v1

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/70672 will merge in 1.16 and will stop serving the apps/v1beta1, apps/v1beta2, and most of the extensions/v1beta1 types by default

CRDs are planned to go to v1 in 1.16 and we will switch e2es to use v1 at that point (and likely enable more conformance tests around them)

**Comment by oomichi** [comment]
After @liggitt's patch was merged, I tried to get which APIs are touched on my local environment by the latest conformance test.
The following non-GA APIs are still touched:
```
$ egrep "(GET|POST|PUT|DELETE|HEAD) http" conformance.log | grep beta | awk -F "] " '{print $2}'  | sed s/"https:\/\/192.168.1.118:6443"//g | sed s/"namespaces\/.*\/"/"namespaces\/..\/"/g | sort | uniq
DELETE /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/foop9hnpas.mygroup.example.com
DELETE /apis/mygroup.example.com/v1beta1/foop9hnpas/setup-instance
GET /apis/admissionregistration.k8s.io/v1beta1?timeout=32s
GET /apis/apiextensions.k8s.io/v1beta1?timeout=32s
GET /apis/apiregistration.k8s.io/v1beta1?timeout=32s
GET /apis/apps/v1beta1?timeout=32s
GET /apis/apps/v1beta2?timeout=32s
GET /apis/authentication.k8s.io/v1beta1?timeout=32s
GET /apis/authorization.k8s.io/v1beta1?timeout=32s
GET /apis/autoscaling/v2beta1?timeout=32s
GET /apis/autoscaling/v2beta2?timeout=32s
GET /apis/batch/v1beta1/namespaces/../cronjobs
GET /apis/batch/v1beta1?timeout=32s
GET /apis/certificates.k8s.io/v1beta1?timeout=32s
GET /apis/coordination.k8s.io/v1beta1?timeout=32s
GET /apis/events.k8s.io/v1beta1/namespaces/../events
GET /apis/events.k8s.io/v1beta1?timeout=32s
GET /apis/extensions/v1beta1/namespaces/../daemonsets
GET /apis/extensions/v1beta1/namespaces/../deployments
GET /apis/extensions/v1beta1/namespaces/../ingresses
GET /apis/extensions/v1beta1/namespaces/../networkpolicies
GET /apis/extensions/v1beta1/namespaces/../replicasets
GET /apis/extensions/v1beta1?timeout=32s
GET /apis/mygroup.example.com/v1beta1/foop9hnpas?resourceVersion=27379&watch=true
GET /apis/mygroup.example.com/v1beta1?timeout=32s
GET /apis/networking.k8s.io/v1beta1/namespaces/../ingresses
GET /apis/networking.k8s.io/v1beta1?timeout=32s
GET /apis/node.k8s.io/v1beta1?timeout=32s
GET /apis/policy/v1beta1/namespaces/../poddisruptionbudgets
GET /apis/policy/v1beta1/podsecuritypolicies
GET /apis/policy/v1beta1?timeout=32s
GET /apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
GET /apis/scheduling.k8s.io/v1beta1?timeout=32s
GET /apis/storage.k8s.io/v1beta1?timeout=32s
POST /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
POST /apis/mygroup.example.com/v1beta1/foop9hnpas
```

**Comment by liggitt** [comment]
> After @liggitt's patch was merged, I tried to get which APIs are touched on my local environment by the latest conformance test.

Are you running the conformance test from master after https://github.com/kubernetes/kubernetes/pull/70672 merged? Many of the APIs you listed (apps/v1beta1, apps/v1beta2, extensions/v1beta1 daemonsets,deployments,networkpolicies,replicasets) are no longer served by default.

The quota and namespace controllers watch all resources, so the GET requests are not particularly concerning.

The mygroup.example.com API is a test fixture and should be disregarded (its version is arbitrary and could be renamed to v1 if we cared)

The only write to a non-v1 API I see there is the CRD API.

**Comment by oomichi** [comment]
@liggitt 
> Are you running the conformance test from master after #70672 merged?

Yeah, the commit of my local environment is https://github.com/kubernetes/kubernetes/commit/69a34f6a6f67de47cb9b72b6ac98e089d301beb3 which contains https://github.com/kubernetes/kubernetes/pull/70672

> Many of the APIs you listed (apps/v1beta1, apps/v1beta2, extensions/v1beta1 daemonsets,deployments,networkpolicies,replicasets) are no longer served by default.

Yes, right. I had the same question about that. I've checked all e2e code but I cannot find any places which calls beta APIs for them.
I am still investigating that, and the callers seem to be in AfterEach() which is one of test cleanup.
I'd like to dig it more with some actual test runs and will report the result soon.

@liggitt Thanks for your help anyways.

**Comment by liggitt** [comment]
these should now be cleaned up in master
```
DELETE /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/foop9hnpas.mygroup.example.com
POST /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
```

anything with `example.com` should be filtered out, e.g.:
```
DELETE /apis/mygroup.example.com/v1beta1/foop9hnpas/setup-instance
POST /apis/mygroup.example.com/v1beta1/foop9hnpas
```

**Comment by oomichi** [comment]
OK, now I've build e2e binary with the latest master (https://github.com/kubernetes/kubernetes/commit/bc1d8c6d61078269540f807248a455cba09e672c) and start running conformance test on my local environment.
It takes time, so I will report the result tomorrow.

**Comment by oomichi** [comment]
Conformance test of the latest master (https://github.com/kubernetes/kubernetes/commit/bc1d8c6d61078269540f807248a455cba09e672c) is touching the following beta APIs:
```
$ egrep "(GET|POST|PUT|DELETE|HEAD) http" conformance20190820.log | grep beta | awk -F "] " '{print $2}'  | sed s/"https:\/\/192.168.1.118:6443"//g | sed s/"namespaces\/.*\/"/"namespaces\/..\/"/g | sort | uniq
DELETE /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/foovmxm2as.mygroup.example.com
DELETE /apis/mygroup.example.com/v1beta1/foovmxm2as/setup-instance
GET /apis/admissionregistration.k8s.io/v1beta1?timeout=32s
GET /apis/apiextensions.k8s.io/v1beta1?timeout=32s
GET /apis/apiregistration.k8s.io/v1beta1?timeout=32s
GET /apis/apps/v1beta1?timeout=32s
GET /apis/apps/v1beta2?timeout=32s
GET /apis/authentication.k8s.io/v1beta1?timeout=32s
GET /apis/authorization.k8s.io/v1beta1?timeout=32s
GET /apis/autoscaling/v2beta1?timeout=32s
GET /apis/autoscaling/v2beta2?timeout=32s
GET /apis/batch/v1beta1/namespaces/../cronjobs
GET /apis/batch/v1beta1?timeout=32s
GET /apis/certificates.k8s.io/v1beta1?timeout=32s
GET /apis/coordination.k8s.io/v1beta1?timeout=32s
GET /apis/events.k8s.io/v1beta1/namespaces/../events
GET /apis/events.k8s.io/v1beta1?timeout=32s
GET /apis/extensions/v1beta1/namespaces/../daemonsets
GET /apis/extensions/v1beta1/namespaces/../deployments
GET /apis/extensions/v1beta1/namespaces/../ingresses
GET /apis/extensions/v1beta1/namespaces/../networkpolicies
GET /apis/extensions/v1beta1/namespaces/../replicasets
GET /apis/extensions/v1beta1?timeout=32s
GET /apis/metrics.k8s.io/v1beta1?timeout=32s
GET /apis/mygroup.example.com/v1beta1/foovmxm2as?resourceVersion=3089232&watch=true
GET /apis/mygroup.example.com/v1beta1?timeout=32s
GET /apis/networking.k8s.io/v1beta1/namespaces/../ingresses
GET /apis/networking.k8s.io/v1beta1?timeout=32s
GET /apis/node.k8s.io/v1beta1?timeout=32s
GET /apis/policy/v1beta1/namespaces/../poddisruptionbudgets
GET /apis/policy/v1beta1/podsecuritypolicies
GET /apis/policy/v1beta1?timeout=32s
GET /apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
GET /apis/scheduling.k8s.io/v1beta1?timeout=32s
GET /apis/storage.k8s.io/v1beta1?timeout=32s
POST /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
POST /apis/mygroup.example.com/v1beta1/foovmxm2as
```

**Comment by liggitt** [comment]
oops, the new tests added to complete CRD API surface coverage crossed wires with the v1 promotion PR and are still using v1beta1. will fix up and report back

**Comment by oomichi** [comment]
@liggitt OK, could you point the PR which fixes it up later so that I'd like to make sure my local repo contains the PR?

**Comment by liggitt** [comment]
> @liggitt OK, could you point the PR which fixes it up later so that I'd like to make sure my local repo contains the PR?

will be fixed in https://github.com/kubernetes/kubernetes/pull/81684

**Comment by liggitt** [comment]
The apiextensions.k8s.io/v1beta1 API calls are now removed from conformance tests

**Comment by liggitt** [comment]
The example.com API calls should be ignored, they are test data for testing example custom resources, not an actual API we ship

**Comment by liggitt** [comment]
opened kubernetes/enhancements#1332 with a proposal for an automated way to ensure no beta REST APIs or features are required to pass conformance

**Comment by oomichi** [comment]
@liggitt Thanks for doing that, +1

**Comment by oomichi** [comment]
https://github.com/kubernetes/enhancements/pull/1332 is done, so this issue becomes unnecessary today.

/close

**Comment by liggitt** [comment]
That is not done, the proposal has just been merged.

/reopen

**Comment by liggitt** [comment]
There is now a CI job configured to run conformance tests with only GA APIs and features (plus the beta certificates.k8s.io/v1beta1 API) - https://testgrid.k8s.io/conformance-kind#conformance-ga-only

That job ensures no new dependencies on beta APIs or features is introduced to conformance tests, and the certificates API is positioned to be promoted to GA in 1.19.

/close
