### ISSUE TITLE
"--kube-reserved-cgroup" kubelet option cannot find cgroup

### ISSUE THREAD

**Issue by xiongmaodada** [kubernetes/kubernetes#78629]
start kubelet with below config:
```
# root@k8s-node-prod-2:~# cat/etc/systemd/system/kubelet.service
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service
[Service]
WorkingDirectory=/var/lib/kubelet
ExecStart=/usr/local/bin/kubelet \
  --address=10.x.x.x \
  --hostname-override=10.x.x.x \
  --cluster-dns=10.x.x.x \
  --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --cert-dir=/etc/kubernetes/ssl \
  --cluster-domain=cluster.local. \
  --hairpin-mode promiscuous-bridge \
  --allow-privileged=true \
  --serialize-image-pulls=false \
  --logtostderr=true \
  --v=2 \
  --cgroup-driver=systemd \
  --cgroups-per-qos=true \
  --kube-reserved-cgroup=/podruntime.slice \
  --enforce-node-allocatable=pods,kube-reserved \
  --kube-reserved=cpu=500m,memory=500Mi,ephemeral-storage=10Gi 
  
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
```
podruntime.slice  with below config:
```
# root@k8s-node-prod-2:~# cat /lib/systemd/system/podruntime.slice
[Unit]
Description=Limited resources slice for Kubernetes services
Documentation=man:systemd.special(7)
DefaultDependencies=no
Before=slices.target
Requires=-.slice
After=-.slice
```
check the podruntime.slice  cgroup, get the following output:
```
#root@k8s-node-prod-2:~# systemctl status podruntime.slice
● podruntime.slice - Limited resources slice for Kubernetes services
   Loaded: loaded (/lib/systemd/system/podruntime.slice; static; vendor preset: enabled)
   Active: active since Sun 2019-06-02 11:29:57 CST; 42min ago
     Docs: man:systemd.special(7)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /podruntime.slice

Jun 02 11:29:57 k8s-node-prod-2 systemd[1]: Created slice Limited resources slice for Kubernetes services.
```
then, start kubelet.service, run `journalctl -u kubelet.service  -f`  as follows:
```
Jun 02 12:36:40 k8s-node-prod-2 kubelet[73505]: I0602 12:36:40.187096   73505 node_container_manager_linux.go:114] Enforcing kube reserved on cgroup "/podruntime.slice" with limits: map[cpu:{i:{value:500 scale:-3} d:{Dec:<nil>} s:500m Format:DecimalSI} ephemeral-storage:{i:{value:10737418240 scale:0} d:{Dec:<nil>} s:10Gi Format:BinarySI} memory:{i:{value:524288000 scale:0} d:{Dec:<nil>} s:500Mi Format:BinarySI}]
Jun 02 12:36:40 k8s-node-prod-2 kubelet[73505]: F0602 12:36:40.187428   73505 kubelet.go:1359] Failed to start ContainerManager Failed to enforce Kube Reserved Cgroup Limits on "/podruntime.slice": ["podruntime.slice"] cgroup does not exist
Jun 02 12:36:40 k8s-node-prod-2 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 02 12:36:40 k8s-node-prod-2 systemd[1]: kubelet.service: Unit entered failed state.
Jun 02 12:36:40 k8s-node-prod-2 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 02 12:36:45 k8s-node-prod-2 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
```
`["podruntime.slice"] cgroup does not exist`
why?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`):  SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by xiongmaodada** [comment]
@derekwaynecarr

**Comment by tedyu** [comment]
From cgroupManagerImpl#Exists :
```
	if len(missingPaths) > 0 {
		klog.V(4).Infof("The Cgroup %v has some missing paths: %v", name, missingPaths)
		return false
```
Can you turn on log V4 so that we can see the above log ?

thanks

**Comment by tedyu** [comment]
```
func (m *cgroupManagerImpl) Exists(name CgroupName) bool {
```
It seems if we change return value type to error, the caller would be able to incorporate error message from Exists func.

**Comment by mattjmcnaughton** [comment]
Thanks for sharing :) Hope we can help you debug!

Is the information here helpful?https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-allocatable.md#recommended-cgroups-setup

**Comment by xiongmaodada** [comment]
@tedyu @mattjmcnaughton  thanks for your rely. when I turn on log V4, logs as followed:
```
Jun 03 10:15:09 k8s-node-prod-2 kubelet[28082]: I0603 10:15:09.242375   28082 cgroup_manager_linux.go:276] The Cgroup [podruntime.slice] has some missing paths: [/sys/fs/cgroup/pids/podruntime.slice.slice /sys/fs/cgroup/cpu,cpuacct/podruntime.slice.slice /sys/fs/cgroup/cpu,cpuacct/podruntime.slice.slice /sys/fs/cgroup/memory/podruntime.slice.slice /sys/fs/cgroup/systemd/podruntime.slice.slice /sys/fs/cgroup/cpuset/podruntime.slice.slice]
```
Cgroup  path is not expected: `/sys/fs/cgroup/*/podruntime.slice`, so when I modify `--kube-reserved-cgroup=/podruntime`,  it‘s ok.

so， Is this normal?

**Comment by mattjmcnaughton** [comment]
Ah, it looks like its appending `.slice` automatically to the cgroup name. At the very least, I think the documentation could be clearer to indicate this will happen. An additional option could be adding the `.slice` suffix only if doesn't already exist.

**Comment by xiongmaodada** [comment]
@mattjmcnaughton thank you

**Comment by mattjmcnaughton** [comment]
@xiongmaodada no problem :) If this issue is resolved, would you mind closing it? Thanks!

**Comment by jaypipes** [comment]
@xiongmaodada @mattjmcnaughton It might be worth considering adding a little code somewhere that simply strips off the ".slice" from the cgroup name supplied in `--kubelet-reserved-cgroup` configuration option and just normalizing the input in the configuration package itself (possibly with a warning that prints out stating cgroup should not end in ".slice")

**Comment by mattjmcnaughton** [comment]
@jaypipes I think that's a great idea.

@xiongmaodada I will work on that, unless you want to :)

/assign

**Comment by xiongmaodada** [comment]
@mattjmcnaughton thank you！
