### ISSUE TITLE
cAdvisor container metric has the empty container_name field

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes/kubernetes#78636]
**What happened**:
I am trying to get the container CPU usage information in grafana, but getting emty diagrams. Grafana has the next dashboard request:
`sum by (container_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=\"$pod\"}[1m]))`
Here is the part of the cAdvisor output:
`container_cpu_usage_seconds_total{container_name="",cpu="total",id="/kubepods/burstable/pod6c90ee67-83c5-11e9-94aa-000d3a218149",image="",name="",namespace="default",pod_name="cassandra-1"} 23630.333620239`
As you can see, there is the empty container_name field.
**What you expected to happen**:
container_name="cassandra"
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Azure`
- OS (e.g: `cat /etc/os-release`): `CoreOS stable (2079.3.0)`
- Kernel (e.g. `uname -a`): `Linux tmp-plus1connect-k8s-master-0 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz GenuineIntel GNU/Linux`
- Install tools: `Terraform`
- Network plugin and version (if this is a network-related bug): `Azure-CNI`
- Others:

**Comment by IvanovOleg** [comment]
@kubernetes/sig-node-bug

**Comment by mattjmcnaughton** [comment]
Hi @IvanovOleg ! Thanks for sharing this issue :)

I think you'd actually have the most luck asking this on the [cadvisor](https://github.com/google/cadvisor) project.

Mind closing this issue and opening when there?

**Comment by IvanovOleg** [comment]
@mattjmcnaughton, I will create an issue there.
