### ISSUE TITLE
CreateStatefulPod will never got already exists errors

### ISSUE THREAD

**Issue by tjucoder** [kubernetes/kubernetes#78649]
```
func (spc *realStatefulPodControl) CreateStatefulPod(set *apps.StatefulSet, pod *v1.Pod) error {
	// Create the Pod's PVCs prior to creating the Pod
	if err := spc.createPersistentVolumeClaims(set, pod); err != nil {
		spc.recordPodEvent("create", set, pod, err)
		return err
	}
	// If we created the PVCs attempt to create the Pod
	_, err := spc.client.CoreV1().Pods(set.Namespace).Create(pod)
	// sink already exists errors
	if apierrors.IsAlreadyExists(err) {
		return err
	}
	spc.recordPodEvent("create", set, pod, err)
	return err
}
```

**What happened**: 
func CreateStatefulPod will never got a already exists errors
func CheckGeneratedNameError will trans 409 into 500
I got a create failed event, but my StatefulSet run well immediately
The events of my StatefulSet looks bad:
```
Reason:FailedCreate
Message:create Pod XXX in StatefulSet XXX failed error: The POST operation against Pod could not be completed at this time, please try again.
```

**What you expected to happen**:
I want sink already exists errors as the comment said in the code
I should not got the FailedCreate event when the Pod already exists

**How to reproduce it (as minimally and precisely as possible)**:
sync the same StatefulSet twice in a very short time
pod.Status.Phase is still empty during the second sync invoked

**Anything else we need to know?**:
After the create failed event, my StatefulSet run well
In fact there is no abnormality but the FailedCreate event
Will this code fix the bug?
```
if apierrors.IsAlreadyExists(err) || apierrors.IsServerTimeout(err) {
    return err
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):1.9, the latest version will happen too I think
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):SUSE12
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tjucoder** [comment]
sig/statefulset

**Comment by wangzhuzhen** [comment]
Met the same. Only get InnerError when POST to create pod.  The reason in my case is that  there already have an pod with the same podname and podnamspace in etcd yet (but not created  by k8s, because when create the old pod the POST request get timeout error return, when timeout error happend, we checked  and make sure that the old pod was written in etcd).
