### ISSUE TITLE
Cronjob `spec.schedule` can`t be change when `spec.schedule` value not `"` or `'`

### ISSUE THREAD

**Issue by fudali113** [kubernetes/kubernetes#78646]
**What happened**:
my cronJob yaml like:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  creationTimestamp: 2019-04-26T10:03:09Z
  labels:
    run: hello
  name: hello
  namespace: job
  resourceVersion: "64383604"
  selfLink: /apis/batch/v1beta1/namespaces/job/cronjobs/hello
  uid: 7e83dc18-680a-11e9-a3cf-00163e2e09c7
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: hello
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            imagePullPolicy: Always
            name: hello
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```
i want change `schedule` to `*/1 * * * *`

i just write new value when i must make schedule value is `"*/1 * * * *"` or `'*/1 * * * *'` ,
if value is `*/1 * * * *`, we can got a error message : 

```
# cronjobs "hello" was not valid:
# * : Invalid value: "The edited file failed validation": [yaml: line 43: did not find expected alphabetic or numeric character, [invalid character 'a' looking for beginning of value, invalid character 'a' looking for beginning of value]]
```

**What you expected to happen**:
`"`,`'` can`t influence logic

**How to reproduce it (as minimally and precisely as possible)**:
change `spec.schedule` value to not `"`, `'`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hainesc** [comment]
It is a matter of yaml, not kubernetes. BTW, what's wrong if there must be `"` or `'` ?

**Comment by fudali113** [comment]
> It is a matter of yaml, not kubernetes. BTW, what's wrong if there must be `"` or `'` ?

the wrong is write string in yaml not need  `"` or `'`, but there must need and not this description on the document.

**Comment by hainesc** [comment]
```go
package main

import (
        "fmt"
        "gopkg.in/yaml.v2"
)
 // replace field a by x yz, it will ok.
var data = `
a: */1 * * * * 
b:
  c: 2
  d: [3, 4]
`

type T struct {
        A string
        B struct {
                RenamedC int   `yaml:"c"`
                D        []int `yaml:",flow"`
        }
}

func main() {
        t := T{}
        err := yaml.Unmarshal([]byte(data), &t)
        if err != nil {
               fmt.Printf("error: %v", err)
        }
        fmt.Println(t)
}
```
Run this example which I get from https://github.com/go-yaml/yaml. It ends with an error. It will be OK if you replace `*/1 * * * *` by a simple string with blank such as `x yz`. If you think it is an bug, you can post an issue for go-yaml.

**Comment by fudali113** [comment]
i know this problem is not a bug via read [yaml alias document](https://yaml.org/spec/1.2/spec.html#alias//)

but i can't understand not error tips when this yaml first apply?  and i want write this to cronjob documents.

@hainesc

**Comment by hainesc** [comment]
Can you show me your raw yaml file that you applied to `kubectl`? And the output when you applied it.

**Comment by fudali113** [comment]
i am used `kubectl edit` change yaml config，error information in the first comment

> Can you show me your raw yaml file that you applied to `kubectl`? And the output when you applied it.

**Comment by hainesc** [comment]
> but i can't understand not error tips when this yaml first apply?

You must make sure when first applied, did the `schedule value` wrapped by `"` or `'`?
If it did, why do you edit it and remove the `'`?
