### ISSUE TITLE
Error proxying data from client to backend

### ISSUE THREAD

**Issue by Ankur7890** [kubernetes/kubernetes#78645]
Getting below exception in k8s api server logs.

Error proxying data from client to backend: Master -> Kubelet:10250 write: broken pipe

Can someone help me with the reason for the same.

**Comment by Ankur7890** [comment]
@kubernetes/Error-Proxying

**Comment by Himani-relan** [comment]
I am facing the same issue in kubeapi-server container logs.
Executing kubectl commands gives the below error:
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Could someone please tell the root cause ?

**Comment by oded-dd** [comment]
Our kube-apiserver are full with it:

```I0929 15:51:34.822292       1 log.go:172] http: TLS handshake error from 172.30.8.56:63562: tls: oversized record received with length 26990
E0929 15:53:05.622796       1 upgradeaware.go:357] Error proxying data from backend to client: tls: use of closed connection```

**Comment by Davidrjx** [comment]
https://github.com/kubernetes/kubernetes/issues/78645#issuecomment-536543651 i have same error line, is it affective?

**Comment by Bhuvan26** [comment]
We had also observed the same issue

E1204 10:53:48.215698 1 upgradeaware.go:338] Error proxying data from client to backend: read tcp 10.200.210.102:8443->10.200.210.103:39964: read: connection reset by peer
I1204 10:54:04.720577 1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1204 10:54:04.721860 1 controller.go:116] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Requeue.
E1204 10:54:08.218319 1 upgradeaware.go:338] Error proxying data from client to backend: read tcp 10.200.210.102:8443->10.200.210.103:40536: read: connection reset by peer

**Comment by lovexiongmao** [comment]
@Ankur7890 @oded-dd hello, have you solve the problem? i get the same issue. now

**Comment by khatrig** [comment]
Same issue here

**Comment by krishnakc1** [comment]
Hello, has anyone found what is causing it. I am seeing this error irregularly at our end.
Baremetal K8s - Version 1.14.3 - Installed using kubeadm Kubespray

1 upgradeaware.go:370] Error proxying data from client to backend: tls: use of closed connection
1 upgradeaware.go:370] Error proxying data from client to backend: write tcp 10...:por1:10..:por2 : write: connection reset by peer
upgradeaware.go:370] Error proxying data from client to backend: write tcp 10...:por1:10..:por2: write: broken pipe

**Comment by ksankeerth** [comment]
Hey,
Observed the same issue. 
```
Aug 12 06:00:22 kcp kubelet[629]: E0812 06:00:22.222747     629 upgradeaware.go:399] Error proxying data from client to backend: readfrom tcp 127.0.0.1:43306->127.0.0.1:41687: write tcp 127.0.0.1:43306->127.0.0.1:41687: write: broken pipe
Aug 12 06:09:27 kcp kubelet[629]: E0812 06:09:27.974883     629 upgradeaware.go:399] Error proxying data from client to backend: readfrom tcp 127.0.0.1:47832->127.0.0.1:41687: write tcp 127.0.0.1:47832->127.0.0.1:41687: write: broken pipe
```
I did some research and found that the API server can functions as proxy for any service/pods running in the cluster. 

Starting proxy :
`kubectl proxy `

API server can proxy Web socket connections too. For the Web-socket, there will connection Upgrade Request will be sent.  The request will go through in the following direction. If the backend (K8s service/pod) causes any issues in upgrading to Web socket connection, then these kind of error can be seen.

local machine(where we invoke request) => <API_SERVER_AS_PROXY _TO_pods/service> => <Actual_K8s_service/Pod>
