### ISSUE TITLE
Why Kube-dns could not find API server in kubernetes and automatically restarted at 12:00AM?

### ISSUE THREAD

**Issue by mahesh862086** [kubernetes/kubernetes#78654]
We have a cluster created in GKE. It was running fine but Kube-dns restarted automatically at 12:00AM along with few pods. There were 2 kube-dns pods in the namespace kube-system but only one got restarted with below errors. We also noticed that other pods were untouched.

`I0602 19:04:48.653590       1 dns.go:48] version: 1.14.13
I0602 19:04:48.655733       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
I0602 19:04:48.655805       1 server.go:121] FLAG: --alsologtostderr="false"
I0602 19:04:48.655831       1 server.go:121] FLAG: --config-dir="/kube-dns-config"
I0602 19:04:48.655840       1 server.go:121] FLAG: --config-map=""
I0602 19:04:48.655845       1 server.go:121] FLAG: --config-map-namespace="kube-system"
I0602 19:04:48.655851       1 server.go:121] FLAG: --config-period="10s"
I0602 19:04:48.655858       1 server.go:121] FLAG: --dns-bind-address="0.0.0.0"
I0602 19:04:48.655864       1 server.go:121] FLAG: --dns-port="10053"
I0602 19:04:48.655872       1 server.go:121] FLAG: --domain="cluster.local."
I0602 19:04:48.655881       1 server.go:121] FLAG: --federations=""
I0602 19:04:48.655888       1 server.go:121] FLAG: --healthz-port="8081"
I0602 19:04:48.655893       1 server.go:121] FLAG: --initial-sync-timeout="1m0s"
I0602 19:04:48.655899       1 server.go:121] FLAG: --kube-master-url=""
I0602 19:04:48.655905       1 server.go:121] FLAG: --kubecfg-file=""
I0602 19:04:48.655911       1 server.go:121] FLAG: --log-backtrace-at=":0"
I0602 19:04:48.655920       1 server.go:121] FLAG: --log-dir=""
I0602 19:04:48.655926       1 server.go:121] FLAG: --log-flush-frequency="5s"
I0602 19:04:48.655931       1 server.go:121] FLAG: --logtostderr="true"
I0602 19:04:48.655936       1 server.go:121] FLAG: --nameservers=""
I0602 19:04:48.655941       1 server.go:121] FLAG: --stderrthreshold="2"
I0602 19:04:48.655948       1 server.go:121] FLAG: --v="2"
I0602 19:04:48.655953       1 server.go:121] FLAG: --version="false"
I0602 19:04:48.655961       1 server.go:121] FLAG: --vmodule=""
I0602 19:04:48.656327       1 server.go:169] Starting SkyDNS server (0.0.0.0:10053)
I0602 19:04:48.656690       1 server.go:179] Skydns metrics enabled (/metrics:10055)
I0602 19:04:48.656707       1 dns.go:188] Starting endpointsController
I0602 19:04:48.656714       1 dns.go:191] Starting serviceController
I0602 19:04:48.656843       1 dns.go:184] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[]}
I0602 19:04:48.657299       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0602 19:04:48.657358       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0602 19:04:49.161278       1 dns.go:219] Waiting for [endpoints services] to be initialized from apiserver...

E0602 19:05:18.658618       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://10.57.220.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.57.220.1:443: i/o timeout
E0602 19:05:18.659416       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:192: Failed to list *v1.Service: Get https://10.57.220.1:443/api/v1/services?resourceVersion=0: dial tcp 10.57.220.1:443: i/o timeout
I0602 19:05:19.157105       1 dns.go:219] Waiting for [endpoints services] to be initialized from apiserver...
I0602 19:05:19.657129       1 dns.go:219] Waiting for [endpoints services] to be initialized from apiserver...

I0602 19:05:30.657099       1 dns.go:222] Initialized services and endpoints from apiserver
I0602 19:05:30.657134       1 server.go:137] Setting up Healthz Handler (/readiness)
I0602 19:05:30.657152       1 server.go:142] Setting up cache handler (/cache)
I0602 19:05:30.657178       1 server.go:128] Status HTTP port 8081
W0602 19:24:18.126042       1 reflector.go:323] k8s.io/dns/pkg/dns/dns.go:189: watch of *v1.Endpoints ended with: too old resource version: 4319887 (4320266)
W0602 21:34:03.553971       1 reflector.go:323] k8s.io/dns/pkg/dns/dns.go:192: watch of *v1.Service ended with: very short watch
W0602 21:34:03.553990       1 reflector.go:323] k8s.io/dns/pkg/dns/dns.go:189: watch of *v1.Endpoints ended with: very short watch
E0602 21:34:05.624226       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://10.57.220.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.57.220.1:443: connect: connection refused
E0602 21:34:09.741582       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://10.57.220.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.57.220.1:443: connect: connection refused
E0602 21:34:38.444373       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:192: Failed to list *v1.Service: Get https://10.57.220.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
E0602 21:34:40.883539       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://10.57.220.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
E0602 22:36:48.766809       1 reflector.go:304] k8s.io/dns/pkg/dns/dns.go:189: Failed to watch *v1.Endpoints: Get https://10.57.220.1:443/api/v1/endpoints?resourceVersion=4373005&timeoutSeconds=564&watch=true: read tcp 10.52.20.18:57528->10.57.220.1:443: read: connection timed out
E0602 22:36:48.766882       1 reflector.go:304] k8s.io/dns/pkg/dns/dns.go:192: Failed to watch *v1.Service: Get https://10.57.220.1:443/api/v1/services?resourceVersion=4358570&timeoutSeconds=408&watch=true: read tcp 10.52.20.18:57528->10.57.220.1:443: read: connection timed out
E0602 22:37:19.767672       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://10.57.220.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.57.220.1:443: i/o timeout
W0602 22:48:16.981444       1 reflector.go:323] k8s.io/dns/pkg/dns/dns.go:189: watch of *v1.Endpoints ended with: too old resource version: 4375762 (4375879)`

kube-pods information:

namespace = kube-system
kube-dns-6987857fdb-hr8tb                                        4/4     Running   0          11d
kube-dns-6987857fdb-ngg9d                                        4/4     Running   0          18h
kube-dns-autoscaler-bb58c6784-cxw77                              1/1     Running   0          18h

namespace=default
test-grpc-69d58fb6f5-lq6xt             3/3     Running   0          18h
test-grpc-text-78d7876994-n46sv        3/3     Running   3          7d2h
upload-76d9bb8fff-kdcm2                 1/1     Running   0          18h

We expected it would have stuck and manual restart required but it automatically restarted at 12:00AM along with other pods. How is this possible that auto recover of kube-dns in GKE?

**Comment by dims** [comment]
/close

please open a bug with your GKE support folks.
