### ISSUE TITLE
Failing test: [sig-storage] [Serial] Volume metrics should create metrics for total time taken in volume operations in P/V Controller

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#78651]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-storage] [Serial] Volume metrics should create metrics for total time taken in volume operations in P/V Controller

**Since when has it been failing**:
6/1

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial

**Reason for failure**:
Probably caused by
https://github.com/kubernetes/kubernetes/pull/78061

**Anything else we need to know**:

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures 
cc @xiangqian @gnufied

**Comment by msau42** [comment]
cc @yuxiangqian

**Comment by yuxiangqian** [comment]
this is possibly caused by renaming one label of the metric from "plugin_name" to "volume_plugin". Having a fix under testing now

**Comment by jimangel** [comment]
Thanks for opening this @msau42 let us know if we can help!

/priority important-soon
/milestone v1.15
/cc @alejandrox1 @smourapina @rarchk @alenkacz

**Comment by msau42** [comment]
@yuxiangqian is working on a fix

**Comment by yuxiangqian** [comment]
apologies for the late reply. fix PR is in for review
