### ISSUE TITLE
PV created too small for PVC when you use the non-i based units M,G, etc.

### ISSUE THREAD

**Issue by mleklund** [kubernetes/kubernetes#78669]
**What happened**:
When creating a PVC with storage set to 10M, PV is provisioned too small and cannot fulfill the request of the PVC.  When creating a PVC with storage set to 10Mi, PV is sufficiently provisioned.  I tested M/Mi as well as G/Gi and the issue happens with any of the tested non i units.

You can see a bit more discussion on the rook issue list here:

https://github.com/rook/rook/issues/3142

**What you expected to happen**:
I expect that k8s dynamic provisioner to be able to handle the UNIT/UNITi math.

**How to reproduce it (as minimally and precisely as possible)**:
Use a dynamic provisioner with non-i units in k8s 1.14+
**Anything else we need to know?**:

If this is intentional, I did not see a reference to it in the release notes.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.14.0 
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g: `cat /etc/os-release`): Container Linux by CoreOS stable (2079.4.0) 
- Kernel (e.g. `uname -a`): 4.19.43-coreos
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): flannel-cni
- Others:

**Comment by antoineco** [comment]
That's because the `M` and `Mi` notations are **not using the same system of unit** in Kubernetes.

`1M` = 10^6 (Decimal)
`1Mi` = 2^20 (Binary)

Units of storage are usually (if not always) expressed using the Binary SI, so in Kubernetes you can unfortunately not drop the "i".

https://en.m.wikipedia.org/wiki/Binary_prefix

/area documentation

**Comment by mleklund** [comment]
I am fully aware of the math differences.  And let's be honest when was the last time anyone came and asked for a 1 Tebibyte drive, no they ask you for a 1 Terabyte drive, they may wish for or want a Tebibyte, but it is not what they ask for.  Every drive manufacturer typically markets in Terabyte not Tebibytes as to most storage vendors. 

All that aside, If this is a change that has been made in 1.14 to only accept binary si units, then it needs to be documented.  PVC examples exist in the wild with non-binary si units that worked under 1.13 and do not under 1.14, and worst of all fail silently with PVC and PV sitting in the pending state. 

An example of this is a stateful set with the following volumeClaimTemplate:

``` volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ceph-replica"
      resources:
        requests:
          storage: 1G```

Creates a PV:

```
Name:            pvc-e1b1bd73-864a-11e9-8bb8-005056a51bbe
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: ceph.rook.io/block
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    ceph-replica
Status:          Pending
Claim:           default/www-web-0
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        953Mi
Node Affinity:   <none>
Message:
Source:
    Type:       FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:     ceph.rook.io/rook-ceph-system
    FSType:     xfs
    SecretRef:  nil
    ReadOnly:   false
    Options:    map[clusterNamespace:rook-ceph dataBlockPool: image:pvc-e1b1bd73-864a-11e9-8bb8-005056a51bbe pool:replicapool storageClass:ceph-replica]
Events:         <none>```

That cannot fill the PVC request, and the PVC is waiting for a PV large enough:

```
  Type       Reason                Age                   From                         Message
  ----       ------                ----                  ----                         -------
  Normal     ExternalProvisioning  74s (x3917 over 14h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator```

This same exact statefulset works under 1.13.  This is a breaking change.

**Comment by antoineco** [comment]
Thanks for clarifying :+1:  I did not initially understand the problem correctly, that's why my answer was off.

Any interesting log prefixed with `pv_controller.go` in your `kube-controller-manager`'s logs?

**Comment by mleklund** [comment]
Not that I saw, though I will go back and review.
