### ISSUE TITLE
kubectl ignores KUBECONFIG when writing cache

### ISSUE THREAD

**Issue by rmorrise** [kubernetes/kubernetes#78664]
**What happened**:

`kubectl` ignores the `%KUBECONFIG%` setting on Windows and tries to write the HTTP cache to a read-only file location. This seems to cause `kubectl` commands to run slowly (`kubectl get po` takes ~8 seconds for a single pod).

`%KUBECONFIG%` is set, but the setting is being ignored.

```
PS X:\> echo $Env:KUBECONFIG
C:\Users\rmorrise\.kube\config
PS X:\> kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6445
  name: docker-for-desktop-cluster
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
current-context: docker-for-desktop
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
PS X:\> kubectl get po --v=5
I0603 17:37:16.044761   20720 cached_discovery.go:133] failed to write cache to X:\.kube\cache\discovery\localhost_6445\servergroups.json due to mkdir X:\.kube\cache: Access is denied.
I0603 17:37:16.128124   20720 cached_discovery.go:86] failed to write cache to X:\.kube\cache\discovery\localhost_6445\v1\serverresources.json due to mkdir X:\.kube\cache: Access is denied.
I0603 17:37:16.223893   20720 cached_discovery.go:86] failed to write cache to X:\.kube\cache\discovery\localhost_6445\apiregistration.k8s.io\v1\serverresources.json due to mkdir X:\.kube\cache: Access is denied.
I0603 17:37:16.305915   20720 cached_discovery.go:86] failed to write cache to X:\.kube\cache\discovery\localhost_6445\apiregistration.k8s.io\v1beta1\serverresources.json due to mkdir X:\.kube\cache: Access is denied.
...
```

**What you expected to happen**:

All usages of `.kube` should be redirected to `C:\` drive as specified by `KUBECONFIG`.

**How to reproduce it (as minimally and precisely as possible)**:

1) Started on a windows PC with user profile stored in a network drive.
2) Install Docker Desktop and Kubernetes. Start the Kubernetes cluster. (Cluster context does not show up properly due to config mismatch.)
3) After Kubernetes is installed and the cluster is started, add environment variable `KUBECONFIG` to point to C:\ drive.
4) Exit docker desktop
5) Set windows folder permissions to prevent read/write in `.kube` on the network drive
6) Start up docker desktop
7) `kubectl get po --v=5`

**Anything else we need to know?**:

`USERPROFILE` is also set to `C:\Users\rmorrise\`

If `KUBECONFIG` is not set properly, `kubectl` will not work at all.
With `KUBECONFIG` set, kubectl works but is not able to cache data (causing slowness).

All tools that refer to `.kube` should use the exact same logic to find the correct path.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: lenovo thinkpad x64
- OS (e.g: `cat /etc/os-release`): Win 10 Enterprise
- Install tools: Docker Desktop windows

**Comment by liggitt** [comment]
The cache location is not controlled by kubeconfig.

**Comment by liggitt** [comment]
There are two caches kubectl uses, one for openapi schemas, controlled by `--cache-dir`, and one for discovery docs, which I don't think is configurable. 

Both should be configurable, but I'm not sure about deriving them from $KUBECONFIG

**Comment by rmorrise** [comment]
How can I set the cache location without specify a command-line argument on every single command?

**Comment by rmorrise** [comment]
Feature request - please set up a single environment variable to govern `.kube` location. Don't make me set two or more environment variables and/or command line options when I need to change the .kube path.

**Comment by The-Loeki** [comment]
/remove-lifecycle rotten

This issue persists, as the discovery path is hardcoded:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L216

I agree that $HOME/.kube should be one setting, like `KUBECTL_CACHE` or `KUBECTL_HOME` or whatever

**Comment by glensc** [comment]
@The-Loeki :

Don't link to branches!
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
- hit `y`
- and perhaps https://github.com/josephfrazier/octopermalinker

**Comment by blodone** [comment]
+1 it should be configurable. Using remote attached disks like ceph would destroy the usability of kubectl. Also it would be nice if an option like --no-cache would exist

**Comment by tedyu** [comment]
From staging/src/k8s.io/client-go/discovery/cached/disk/cached_discovery.go
```
// TODO(juanvallejo): the value of "--cache-dir" should be honored. Consolidate discoveryCacheDir with httpCacheDir
// so that server resources and http-cache data are stored in the same location, provided via config flags.
func NewCachedDiscoveryClientForConfig(config *restclient.Config, discoveryCacheDir, httpCacheDir string, ttl time.Duration) (*CachedDiscoveryClient, error) {
```
Is the unification mentioned above acceptable to everyone ?

**Comment by rmorrise** [comment]
@tedyu if I understood what you posted correctly, it looks like this would improve the behavior of the command line option. Would this be the first step to implement @The-Loeki 's suggestion to use KUBECTL_HOME? That would be awesome

**Comment by rmorrise** [comment]
Thinking of JAVA_HOME and similar, that's normally where the tool installation and bin is located, so KUBECTL_CACHE would probably make more sense

**Comment by jdef** [comment]
The OP mentions Windows. We've seen this degrade kubectl performance on linux machines too, where /home/xyz dirs are NFS mounts. Sure, it's possible to hack around the issue, but it's problematic especially for new k8s users who wonder why kubectl commands sometimes take so long to run.
