### ISSUE TITLE
TestWebhookReinvocationPolicy flakes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#78663]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestWebhookReinvocationPolicy

reinvocation_test.go:203: Internal error occurred: jsonpatch add operation does not apply: doc is missing path: "/metadata/labels/a"

/cc @jpbetz 
/sig api-machinery
/priority important-soon
/kind bug
/area admission-control

**Comment by jpbetz** [comment]
Investigating now. So far I haven't found a problem in the test code, so I'm investigating the reinvocation logic to see if this is a problem in admission control reinvocation.

**Comment by jpbetz** [comment]
I've reproduced and gotten the test to pass consistently. There are two problems (1) there is an error in WebhookAccessor.getUID() where the call returns name, not uid. (2) registering webhooks does not take effect immediately, which causes TestWebhookReinvocationPolicy to flake. Will send out a fix shortly.
