### ISSUE TITLE
progressDeadlineseconds not respected by the scale the deployment on container Image not exist 

### ISSUE THREAD

**Issue by wu0407** [kubernetes/kubernetes#78678]
**What happened**:
create deployment which the replica is  0,  and scale up the deployment.
if the image is not found in registry, the deployment not fail, stuck in "Waiting for deployment 
 rollout to finish".
**What you expected to happen**:
the deployment respect the progressDeadlineseconds and  rollout status is "deployment exceeded its progress deadline"
**How to reproduce it (as minimally and precisely as possible)**:
the deployment yaml
```
~$ cat test-nginx.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: test-network-nginx
  name: test-network-nginx-003
  namespace: default
spec:
  progressDeadlineSeconds: 60
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: test-network-nginx
      version: v3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test-network-nginx
        version: v3
    spec:
      containers:
      - image: nginx:v1.16   #this image not fond in registry
        imagePullPolicy: IfNotPresent
        name: test-network-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
kubectl apply -f  test-nginx.yaml
kubectl scale deploy test-network-nginx-003 --replicas=1 --timeout=10s
kubectl rollout status is stuck
```
~$ kubectl rollout status deploy  test-network-nginx-003        
Waiting for deployment "test-network-nginx-003" rollout to finish: 0 of 1 updated replicas are available...
```

**Anything else we need to know?**:
if the replica is 1 in test-nginx.yaml , then  kubectl apply -f  test-nginx.yaml respect progressDeadlineseconds.
```
~$ kubectl rollout status deploy  test-network-nginx-003 
Waiting for deployment "test-network-nginx-003" rollout to finish: 0 of 1 updated replicas are available...


error: deployment "test-network-nginx-003" exceeded its progress deadline
```
but use kubectl patch deploy test-network-nginx-003 -p '{"spec":{"replicas":1}}' also not repect progressDeadlineseconds.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
4.13.16-041316-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Joseph-Irving** [comment]
`progressDeadlineSeconds` is only respected when you're doing a deployment rollout, scaling a replicaset does not count as rollout, it's only when you create a new replicaset by changing something like the pod spec that a rollout occurs. 
So as far as I can tell it's expected behaviour for rollout status to not be honoured when scaling the replicaset. 

The fact it appears to be honoured when going from 1 to X in your case, is due to the fact that your initial deployment failed due to the non existent image, so when you scale the deployment it continues with a rollout as it never saw the `NewReplicaSetAvailable` event.

**Comment by wu0407** [comment]
I intend to  pause deployment in rolling up, current not solution to do it, so we do it with manually scale up
