### ISSUE TITLE
support all namespace to clusterRoleBings `subjects.namesapce` when kind is ServiceAccount

### ISSUE THREAD

**Issue by fudali113** [kubernetes/kubernetes#78677]
**What would you like to be added**:
if `subjects.namespace == ${all-namesapces symbol}` , this subject can match all namespace serviceAccount;

https://github.com/kubernetes/kubernetes/blob/9f85c5c4b56940f88cb854615efad4e9f0c66f20/pkg/registry/rbac/validation/rule.go#L290

https://github.com/kubernetes/apiserver/blob/268a6b65e7a9f82fdeb36723d74a53d5f3c5042a/pkg/authentication/serviceaccount/util.go#L41

**Why is this needed**:
we need add some role to all namespace serviceAccount, but i don't want to add all serviceAccount, i just want to add that role to some name serviceAccount; so i think need a all-namesapces symbol add to `subjects.namespace`.

**Comment by fudali113** [comment]
my case is:

i need through k8s service CRD to implement service discovery, so i need add some role (can access get pod, service, endpoints) to all namespaces default (or some) serviceAccount.

now, we add a namespace, need add a clusterRoleBind with this namespace, this is not easy and if i forget add bind will make error on my application。

**Comment by liggitt** [comment]
service accounts are given group memberships that let you grant permissions to all service accounts in a particular namespace (group name `system:serviceaccounts:<namespace>`), or all service accounts cluster-wide (`system:serviceaccounts`). See https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-binding-examples for these

Granting access to a service account with a particular name across namespaces is not intended to be supported. The service account with the name `foo` in namespace `a` has no relationship to the service account with the name `foo` in namespace `b`.

The recommendation is to create a clusterrole with the permissions you need, then when deploying to a particular namespace, create the deployment, serviceaccount, and rolebinding together.

/close
