### ISSUE TITLE
Grant admin user privileges in secure port mode kube-apiserver

### ISSUE THREAD

**Issue by tuananh170489** [kubernetes/kubernetes#78686]
I've disabled insecure port in kube-apiserver. After that, I initial admin user for k8s cluster using command
`kubectl config set-cluster $CLUSTER_NAME --certificate-authority=/etc/kubernetes/pki/ca.pem --embed-certs=true --server=https://X.X.X.X:6443 --kubeconfig=/etc/kubernetes/config/admin.kubeconfig`
Then, create RBAC for admin user privileges
`kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=admin --kubeconfig=/etc/kubernetes/config/admin.kubeconfig`
Of course, it's failed. If I run this command on insecure port mode without `--kubeconfig=/etc/kubernetes/config/admin.kubeconfig`, it will work.
So, how to create RBAC for admin user for new cluster with secure port mode?
Thanks!

**Comment by liggitt** [comment]
see the bootstrapping section of https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping, which describes the methods for getting an initial credential with API permissions

/close

**Comment by tuananh170489** [comment]
> see the bootstrapping section of https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping, which describes the methods for getting an initial credential with API permissions
> 
> /close

thank you so much!
