### ISSUE TITLE
gcr.io/fluentd-elasticsearch/fluentd not pullable

### ISSUE THREAD

**Issue by Morriz** [kubernetes/kubernetes#78684]
I don't know where to report this, but this endpoint is either nuked or behind auth suddenly:
```
# docker pull gcr.io/fluentd-elasticsearch/fluentd:v2.5.2
Error response from daemon: pull access denied for gcr.io/fluentd-elasticsearch/fluentd, repository does not exist or may require 'docker login'
```
I also did a `docker login gcr.io` which was succesfull but made no difference.

**Comment by Morriz** [comment]
@kubernetes/sig-testing-test-failures

**Comment by a8j8i8t8** [comment]
Yes, I'm also facing this issue.

**Comment by Morriz** [comment]
Is that repo maintained by google? Probably not. Otherwise I would expect it be found under `gcr.io/google-containers/fluentd-elasticsearch`, which has it's latest version at v2.4.0 as opposed to the version mentioned in the plugin (v2.5.2). Maybe that is an old repo and the new one is now down...

**Comment by nutellinoit** [comment]
Same problem here

**Comment by naseemkullah** [comment]
At the time of writing this the repo is public again but the most recent tag seems to be `v2.4.0`

**Comment by monotek** [comment]
@piosz  & @coffeepac 

seems the repo permissions were changed to private?

**Comment by monotek** [comment]
For the time being I've build the image again and pushed it to 
monotek/fluentd-elasticsearch:27

**Comment by Pigmalion** [comment]
Hi, I am using helm installation, and imagepullbackoff is my issue now as well .
How can I overcome this with the backup image? 
Thanks

**Comment by monotek** [comment]
just add the image & tag to the values file: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L2-L6

```
image:
  repository: registry.hub.docker.com/monotek/fluentd-elasticsearch
  tag: 27
```

**Comment by coffeepac** [comment]
Will get this sorted soon, apologies for the break.

**Comment by coffeepac** [comment]
the permissions problem has been resolved.  needed to enable the credit card.  

@Morriz can you please try pulling the image again and see what happens?  if the pull is successful can you close this ticket?

**Comment by naseemkullah** [comment]
Working now, thanks for the quick turnaround.

**Comment by xelalexv** [comment]
It's inaccessible again (ElasticSearch image as well):

```
$ docker pull gcr.io/fluentd-elasticsearch/fluentd:v2.5.2
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
$ docker pull gcr.io/fluentd_elasticsearch/elasticsearch:v6.6.1
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by monotek** [comment]
See: https://github.com/kubernetes/kubernetes/pull/79390

**Comment by vguaglione** [comment]
Where is this image on quay.io?  I've tried the following: 

docker pull quay.io/fluentd-elasticsearch/fluentd:v2.5.1
docker pull quay.io/fluentd-elasticsearch/fluentd:latest
docker pull quay.io/fluentd-elasticsearch/fluentd

and all three return the following error:

Error response from daemon: unauthorized: access to the requested resource is not authorized

**Comment by messiahUA** [comment]
@vguaglione it should be quay.io/fluentd_elasticsearch/fluentd

**Comment by vguaglione** [comment]
> @vguaglione it should be quay.io/fluentd_elasticsearch/fluentd

Thanks.  Is the v2.5.1 tag available?  If not, I imagine the latest is backward compatible with v2.5.1, yes?

**Comment by monotek** [comment]
https://quay.io/repository/fluentd_elasticsearch/fluentd?tab=tags

**Comment by vguaglione** [comment]
> https://quay.io/repository/fluentd_elasticsearch/fluentd?tab=tags
> 
> If you're afraid of the newer version use the v2.5.2 tag.

Thanks so much for the help.  I take it there are no substantial changes between 2.5.2 and 2.6?

**Comment by monotek** [comment]
you cna check the changes in the pr: https://github.com/kubernetes/kubernetes/pull/79014/files

**Comment by vguaglione** [comment]
> you can check the changes in this pr: #79014

Sounds good.  Thanks so much for the help, everyone!

**Comment by coffeepac** [comment]
closing this as fixed.  thanks for the patience and sorry for the troubles!

/close
