### ISSUE TITLE
Errors getting pid in conformance image script

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#78699]
**What happened**:
Ran the conformance image via Sonobuoy with the E2E_DRYRUN option set.
Results for the plugin were missing from the resulting tarball and the logs showed:
```
+ tee /tmp/results/e2e.log
/run_e2e.sh: line 65: wait: `6
15': not a pid or valid job spec
```

**What you expected to happen**:
No error, the plugin runs normally and reports results.

**How to reproduce it (as minimally and precisely as possible)**:
Not 100%, but it has been reported and I've seen the tarball. It is just racy
```
sonobuoy run --mode=quick --plugin e2e --plugin-env e2e.E2E_DRYRUN=true --wait
outfile=$(sonobuoy retrieve)
 mkdir ./results; tar xzf $outfile -C ./results
```
Check the logs to see if it includes `not a pid or valid job spec`. There may or may not be some results in `plugins/e2e/results` but in the cases reported to me there was just a 0 length file for e2e.log.

**Anything else we need to know?**:
The problem just seems to be that the `pgrep` command gets the right PID but then the command is finished before `wait` starts. This causes the script to exit badly and not properly report its results.

**Comment by thcdrt** [comment]
Same error from my side using the command "sonobuoy run".
Sonobuoy Version: v0.14.2

**Comment by johnSchnake** [comment]
@thcdrt Just to be clear, you saw that `pid` error when doing a normal `sonobuoy run` (which runs the whole conformance suite)? 

I'm the primary maintainer of Sonobuoy right now and that indeed seems odd if that's the case (since there would be no reason to have a race with the long-lived test run).  If you wouldn't mind, I'd be very interested in seeing the results tarball from that run (you can find me in the k8s slack (@jschnake).

As I mentioned in the issue regarding generic flag options (linked above), one way to help solve/mitigate this would be to have the image use a different runner than bash (presumably Go) so that we could more clearly and elegantly handle the timing/errors/etc.

**Comment by thcdrt** [comment]
@johnSchnake yes exactly, but when launching it again on the same cluster, I didn't have this error anymore. I'll send results to you on slack.

**Comment by johnSchnake** [comment]
Yea you're error message is maybe even more confusing:
```
/run_e2e.sh: line 65: wait: `': not a pid or valid job spec
```
It looks like `pgrep` couldn't find the running command. No indication that it failed, but it wasn't running hence the empty pid/valid job spec.

Looking at yours also made me realize that my message given in the description actually listed _2_ values (separated by newlines which is why I didnt notice it). So maybe pgrep was seeing the tee and the ginkgo command?

So it wasn't that it terminated so fast, but that this approach of `cmd | tee` then `wait $(pgrep)` just isn't very foolproof and has confusing error cases.

**Comment by johnSchnake** [comment]
@dims How would you feel about me creating an alternative to the `run.sh`? I wouldn't remove it (so no risk of irrevocably breaking the image) but adding a go binary here too that could run the tests and might be easier to analyze error paths and such. Even handling args/flags more elegantly if we expand it.

**Comment by dims** [comment]
go for it! @johnSchnake

**Comment by johnSchnake** [comment]
I am putting up the PR for the go runner, but fwiw I wanted to ping this ticket and mention that I have been getting this PID issue in Sonobuoy's CI system probably once a day.
