### ISSUE TITLE
1.15 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by onyiny-ang** [kubernetes/kubernetes#78698]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.15 Release Notes. If you know of issues or API changes that are going out in 1.15, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @jeefy @saschagrunert @alokpatra

/sig release
/milestone v1.15

**Comment by claurence** [comment]
linking to a semi-long slack thread around a known issue in klog: https://kubernetes.slack.com/archives/C09QZTRH7/p1560358363041600

**Comment by neolit123** [comment]
Concurrently joining control-plane nodes does not work as expected in kubeadm 1.15.0. The feature was planned to release with 1.15.0, but possibly a fix will come in a follow up patch release.

**Comment by onyiny-ang** [comment]
@claurence @liggitt How about:

Using --log-file is known to be problematic in 1.15. This presents as things being logged multiple times to the same file. The behaviour and details of this issue, as well as some preliminary attempts at fixing it are documented [here](https://github.com/kubernetes/kubernetes/issues/78734#issuecomment-501372131)

**Comment by liggitt** [comment]
> @claurence @liggitt How about:
> 
> Using --log-file is known to be problematic in 1.15. This presents as things being logged multiple times to the same file. The behaviour and details of this issue, as well as some preliminary attempts at fixing it are documented [here](https://github.com/kubernetes/kubernetes/issues/78734#issuecomment-501372131)

sgtm
