### ISSUE TITLE
Crio 1.14.1/2 (and other versions) cause kubelet to stack up rss memory and goroutines until system oom

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kubernetes#78694]
**What happened**:

cross posted: https://github.com/cri-o/cri-o/issues/2445

We run a mixed cluster of CRI-O and Docker nodes for testing and we've been seeing Kubelets go into runaway memory and goroutine usage on crio nodes only.

![image](https://user-images.githubusercontent.com/279521/58884238-d9de0a00-8694-11e9-9748-69a3019b5f33.png)

![image](https://user-images.githubusercontent.com/279521/58884386-288ba400-8695-11e9-8d86-68b2dcaa0624.png)

The increases are correlated with bunches of logs in this form coming off the kubelet in big blocks:

```
E0520 18:13:34.244009    1457 cri_stats_provider.go:576] Unable to fetch container log stats for path /var/log/pods/fomo_product-consumer-int-8d977bc86-vhgt4_5c8f0efe-7959-11e9-bc76-0639d7c4e89e/product-consumer-int: failed command 'du' ($ nice -n 19 du -s -B 1) on path /var/log/pods/fomo_product-consumer-int-8d977bc86-vhgt4_5c8f0efe-7959-11e9-bc76-0639d7c4e89e/product-consumer-int with error exit status 1
I see nothing unusual in the cri-o logs at all (default log-level).
```

We've recently added a memory cap to the kubelet slice (as before the memory would ballon until it oomed the machine causing general havock that seeming could result in the bug that is perhaps fixed in 1.14.2 around crio/system restarts causing problems with crio state on disk). Even with the memory cap when the kubelet restarts the memory usage often keeps at a rate similar to the rate from the last iteration until it is again killed.

![image](https://user-images.githubusercontent.com/279521/58885135-840a6180-8696-11e9-81ef-5bea3aea68e2.png)

This may be a cri-o or kubelet issue related to the cri stats path (conjecture) so I've created issues in both places.

**What you expected to happen**:

The kubelet memory and goroutine usage to remain sensible.

**How to reproduce it (as minimally and precisely as possible)**:

Unfortunately I do not yet have a set of easy steps to reproduce this problem, but it happens very frequently.

**Anything else we need to know?**:

Nope

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.4.0
VERSION_ID=2079.4.0
BUILD_ID=2019-05-15-0808
PRETTY_NAME="Container Linux by CoreOS 2079.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`): Linux ip-172-16-199-220 4.19.43-coreos #1 SMP Wed May 15 07:18:39 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
- Install tools: Custom
- Network plugin and version (if this is a network-related bug): 
- Others: Crio 1.14.1, 1.14.2 and several iterations of 1.11.x (against kube 1.11.x)

**Comment by SleepyBrett** [comment]
/sig node 
/sig instrumentation

?

**Comment by Random-Liu** [comment]
Can you find a bad node, send SIGABRT to kubelet, check kubelet log and paste the stacktrace here?

In that way, we can tell whether there is goroutine leakage in Kubelet.

**Comment by SleepyBrett** [comment]
Can do. The second image, btw, show go routines stacking up.

**Comment by SleepyBrett** [comment]
@Random-Liu Here is a gist: https://gist.github.com/SleepyBrett/c0400680a60c8cc7ddb3c38aee21ab3c

I did a quick analysis:

```
$ cat ~/kubelet_trace.log | grep goroutine -A 1 | grep -v goroutine | sed -E 's/Jun.*\]: (.*)\([a-zA-Z0-9,\. ]+\)$/\1/' | sort | uniq -c | sort
   1 Jun 05 21:54:50 ip-172-16-198-255 kubelet-wrapper[1479]: k8s.io/kubernetes/pkg/kubelet.newPodContainerDeletor.func1()
   1 Jun 05 21:54:50 ip-172-16-198-255 kubelet-wrapper[1479]: k8s.io/kubernetes/pkg/kubelet/status.(*manager).Start.func1()
   1 k8s.io/kubernetes/cmd/kubelet/app.run
   1 k8s.io/kubernetes/cmd/kubelet/app.watchForLockfileContention.func1
   1 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).podKiller
   1 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration
   1 k8s.io/kubernetes/pkg/kubelet.(*realOOMWatcher).Start.func1
   1 k8s.io/kubernetes/pkg/kubelet/config.(*sourceFile).doWatch
   1 k8s.io/kubernetes/pkg/kubelet/config.(*sourceFile).run.func1
   1 k8s.io/kubernetes/pkg/kubelet/images.(*serialImagePuller).processImagePullRequests
   1 k8s.io/kubernetes/pkg/kubelet/prober.(*manager).updateReadiness
   1 k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start.func1
   1 k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
   1 k8s.io/kubernetes/pkg/util/filesystem.(*fsnotifyWatcher).Run.func1
   1 k8s.io/kubernetes/vendor/github.com/coreos/go-systemd/dbus.(*Conn).dispatch.func1
   1 k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).globalHousekeeping
   1 k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).updateMachineInfo
   1 k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).watchForNewContainers.func1
   1 k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).watchForNewOoms.func1
   1 k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/watcher/raw.(*rawContainerWatcher).Start.func1
   1 k8s.io/kubernetes/vendor/github.com/google/cadvisor/utils/oomparser.(*OomParser).StreamOoms
   1 k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
   1 k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.NewDesc
   1 k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.checkMetricConsistency
   1 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop
   1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalHandler.func1
   1 k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon
   1 net.(*netFD).connect.func2
   1 net/http.(*Transport).getConn.func2.1
   1 net/http.(*http2serverConn).serve
   1 os/signal.signal_recv
   1 regexp.(*bitState).reset
   1 runtime.futex
   2 k8s.io/kubernetes/pkg/util/config.(*Mux).listen
   2 k8s.io/kubernetes/vendor/github.com/godbus/dbus.(*Conn).outWorker
   2 k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).transportMonitor
   2 k8s.io/kubernetes/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher
   2 k8s.io/kubernetes/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher
   2 k8s.io/kubernetes/vendor/google.golang.org/grpc/transport.(*controlBuffer).get
   2 k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*controller).Run.func1
   2 k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run
   2 k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1
   2 net/http.(*persistConn).writeLoop
   2 sync.runtime_Semacquire
   3 syscall.Syscall
   3 syscall.Syscall6
  21 internal/poll.runtime_pollWait
  66 k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop
  79 k8s.io/kubernetes/pkg/kubelet/prober.(*worker).run
  88 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
 149 k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2
 149 k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).watchHandler
 152 runtime.goparkunlock
1599 k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).housekeepingTick
2363 --
```

**Comment by SleepyBrett** [comment]
Still happening with kube 1.14.3 and crio 1.14.5.

**Comment by SleepyBrett** [comment]
We think this is probably related to an issue recently fixed in cri-o where cgroups were not properly being cleaned up. Is it possible that housekeeper routines are stacking because there are just thousands of orphaned cgroups. We're working on a soak test to confirm.

**Comment by tedyu** [comment]
@SleepyBrett 
Do you still experience the issue with crio 1.16.0 ?

Thanks

**Comment by mariusgrigoriu** [comment]
(Working with Brett) We haven't tried with 1.16, but I think this may have been caused by an issue in older builds of crio 1.14 where it didn't clean up cgroups, eventually leaving thousands of cgroups behind and giving cadvisor a lot of work. Probably safe to close.

**Comment by jieyu** [comment]
We observe a similar issue with containerd 1.2.5 as well (with k8s 1.15.5)
