### ISSUE TITLE
Scheduler should always delete from cache the pod<->node relation when the pod is deleted

### ISSUE THREAD

**Issue by dradoaica** [kubernetes/kubernetes#78730]
**What happened**:
All pods for statefulsets using a `podAntiAffinity` rule with `requiredDuringSchedulingIgnoredDuringExecution` stay pending with the following message:

```
0/9 nodes are available: 1 node(s) didn't match node selector, 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 7 node(s) had taints that the pod didn't tolerate. 
```

The node that didn't satisfy existing pods anti-affinity rules is empty (has only the system pods):

```
Non-terminated Pods:         (2 in total)
  kube-system                calico-node-lhc9p
  kube-system                kube-proxy-p5xrw
```

The `podAntiAffinity `:

```
      affinity:
       podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
           matchExpressions:
           - key: <custom-label>
             operator: In
             values: 
             - <value>
```

**What you expected to happen**:

Affinity rules to be respected and pods to be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:

Create no. of nodes + 2 pods via statefulsets with persisted volumes (in my case 10 pods), wait for all of them to get ready and then delete the statefulsets and the persisted volumes with `--grace-period=0 --force`. Recreate the pods

**Anything else we need to know?**:

It seems that after the delete step in the Kubernetes scheduler cache remains, for some nodes,  information about the last pod assigned to that node and any other pod that doesn't have affinity for that pod will not be deployed there (after the delete step the node is empty)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
````
- Cloud provider or hardware configuration:
VMs
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux ubuntu-master 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
/cc @kubernetes/sig-scheduling-bugs
/sig scheduling

**Comment by chendave** [comment]
@dradoaica Looks like the issue is not existed in v1.14.1 anymore,

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Steps I have tried, 
```
kubectl create -f https://raw.githubusercontent.com/chendave/initrepo/master/k8s/demo/statefulset/statefulsetAffinity.yaml
kubectl create -f https://raw.githubusercontent.com/chendave/initrepo/master/k8s/demo/statefulset/pvlist.yaml
```

Force delete the statefulset and the pv list
``` bash
kubectl delete -f https://raw.githubusercontent.com/chendave/initrepo/master/k8s/demo/statefulset/statefulsetAffinity.yaml --grace-period=0 --force
kubectl delete -f https://raw.githubusercontent.com/chendave/initrepo/master/k8s/demo/statefulset/pvlist.yaml --grace-period=o --force

kubectl delete pvc www-web-0 www-web-1  //delete PVC manully
````

Then re-create the `statefulset`, everything looks okay, cannot re-produce your issue in my side.

You might want to verify this on 1.14 as well?

**Comment by dradoaica** [comment]
seems to be from using `--grace-period=0 --force` on deleting
