### ISSUE TITLE
[Umbrella Issue] List of Stable API Endpoints Hit by Core Kubernetes Components

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78749]
Filtering through auditlog data [using APISnoop](https://apisnoop.cncf.io/?useragents=kube-.*&showUntested=true&showTested=true&showConformanceTested=false&zoomed=category-stable-core
) gets us a nice list of Stable API endpoints which are hit by Core Kubernetes components, and are _NOT_ covered by existing conformance tests. 

Grouping them by Kind:

- [kube-\*](#sec-1)
    - [ConfigMap](#sec-1-1)
    - [Namespace](#sec-1-3-2)
    - [Node](#sec-1-3-3)
    - [PersistentVolume](#sec-1-3-4)
    - [Endpoints](#sec-1-5-1)
    - [PersistentVolumeClaim](#sec-1-5-2)
    - [ResourceQuota](#sec-1-5-3)
    - [LimitRange](#sec-1-5-4)
    - [Secret](#sec-1-5-5)
    - [Service](#sec-1-5-6)
    - [Binding](#sec-1-5-7)
    - [Pod](#sec-1-5-8)
    - [Pod](#sec-1-5-11)
    - [ReplicationController](#sec-1-5-9)
    - [ServiceAccount](#sec-1-5-10)
    - [Scale](#sec-1-5-12)

# kube-\*<a id="sec-1"></a>

### ConfigMap<a id="sec-1-1"></a>

1. listCoreV1ConfigMapForAllNamespaces
	
2.  deleteCoreV1CollectionNamespacedConfigMap

### Namespace<a id="sec-1-3-2"></a>

1. replaceCoreV1NamespaceFinalize

2. listCoreV1Namespace [Tested]

### Node<a id="sec-1-3-3"></a>

1. patchCoreV1NodeStatus

2. patchCoreV1Node [Tested]

### PersistentVolume<a id="sec-1-3-4"></a>

1. patchCoreV1PersistentVolume

2. replaceCoreV1PersistentVolumeStatus

3. replaceCoreV1PersistentVolume

4. createCoreV1PersistentVolume [Tested]

5. deleteCoreV1PersistentVolume [Tested]

6. readCoreV1PersistentVolume [Tested]

### Endpoints<a id="sec-1-5-1"></a>

1. replaceCoreV1NamespacedEndpoints
 
2. listCoreV1EndpointsForAllNamespaces

3. deleteCoreV1CollectionNamespacedEndpoints

4. createCoreV1NamespacedEndpoints [Tested]

5. deleteCoreV1NamespacedEndpoints [Tested]

### PersistentVolumeClaim<a id="sec-1-5-2"></a>

1. patchCoreV1NamespacedPersistentVolumeClaimStatus

2. deleteCoreV1CollectionNamespacedPersistentVolumeClaim

3. replaceCoreV1NamespacedPersistentVolumeClaimStatus

4. listCoreV1PersistentVolumeClaimForAllNamespaces

5. replaceCoreV1NamespacedPersistentVolumeClaim [Tested]

6. createCoreV1NamespacedPersistentVolumeClaim [Tested]

7. readCoreV1NamespacedPersistentVolumeClaim

### ResourceQuota<a id="sec-1-5-3"></a>

1.  replaceCoreV1NamespacedResourceQuotaStatus     

2. deleteCoreV1CollectionNamespacedResourceQuota

3.  listCoreV1ResourceQuotaForAllNamespaces

### LimitRange<a id="sec-1-5-4"></a>

1. deleteCoreV1CollectionNamespacedLimitRange

2. listCoreV1LimitRangeForAllNamespaces

### Secret<a id="sec-1-5-5"></a>

1.  listCoreV1SecretForAllNamespaces

2.  deleteCoreV1CollectionNamespacedSecret

### Service<a id="sec-1-5-6"></a>

1.  listCoreV1ServiceForAllNamespaces

### Binding<a id="sec-1-5-7"></a>

1.  createCoreV1NamespacedPodBinding     :scheduler:

### Pod<a id="sec-1-5-8"></a>

1.  replaceCoreV1NamespacedPodStatus

2.  deleteCoreV1CollectionNamespacedPod

4. listCoreV1PodForAllNamespaces [Tested]

### PodTemplate<a id="sec-1-5-11"></a>

1.  deleteCoreV1CollectionNamespacedPodTemplate

2.  listCoreV1PodTemplateForAllNamespaces

### ReplicationController<a id="sec-1-5-9"></a>

1. patchCoreV1NamespacedReplicationController  

2. replaceCoreV1NamespacedReplicationControllerStatus

3. deleteCoreV1CollectionNamespacedReplicationController

4. listCoreV1ReplicationControllerForAllNamespaces 

### ServiceAccount<a id="sec-1-5-10"></a>

1.  listCoreV1ServiceAccountForAllNamespaces

2.  deleteCoreV1CollectionNamespacedServiceAccount

3. replaceCoreV1NamespacedServiceAccount [Tested]

### Scale<a id="sec-1-5-12"></a>

1.  replaceCoreV1NamespacedReplicationControllerScale [Tested]

2.  readCoreV1NamespacedReplicationControllerScale [Tested]

/area test
/area conformance

**Comment by hh** [comment]
@spiffxp should we punt this in favor of #76345 or something else

**Comment by spiffxp** [comment]
/priority important-longterm
I'd like to understand whether we've started work against this.  If so, let's update the description to show what's gotten promoted and what hasn't.  If not, I think we should punt this to backlog.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
Which of these remain uncovered by conformance tests?

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/assign @hh
Which of these remain uncovered by conformance tests?
