### ISSUE TITLE
Propose an admission controller "PodNodeAffinity" to replace admission controller "PodNodeSelector"

### ISSUE THREAD

**Issue by blepoutr** [kubernetes/kubernetes#78757]
If the Nodeselector is deprecated to be replaced by NodeAffinity (as per doc https://kubernetes.io/docs/concepts/configuration/assign-pod-node/), we should do the same for PodNodeselector admission controller (making it deprecated) and propose a new admission controller PodeNodeAffinity.

**Comment by blepoutr** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by blepoutr** [comment]
Based on #58198

**Comment by adampl** [comment]
@blepoutr please reopen.
