### ISSUE TITLE
statefulset should delete LocalPersistentVolume when node was deleted

### ISSUE THREAD

**Issue by smileusd** [kubernetes/kubernetes#78756]
**Why is this needed**:

If a statefulset use LocalPersistentVolume with pvc, when node deletion was happend, the pvc will not be delete, and the pod will stay pending to wait pvc was ready. If all the pvcs need to delete manually when node notready, it is very complicated. So any policies or solutions to auto delete pvc of local volume?

**Comment by smileusd** [comment]
@jsafrane  @msau42  PTAL

**Comment by msau42** [comment]
I believe @cofyc is working on a design for this

**Comment by cofyc** [comment]
yes, this is a general issue, but it's hard to have a general solution.

I plan to write a cloud controller to automate the recovery process in the cloud first. I've created a track issue in `sig-storage-local-static-provisioner` project: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/202
