### ISSUE TITLE
Why was a max length introduced for the CSI Node ID?

### ISSUE THREAD

**Issue by rgcostea** [kubernetes/kubernetes#78751]
**What happened**:
node-driver-registrar failed to register a node
**What you expected to happen**:
I expected the node to be registered
**How to reproduce it (as minimally and precisely as possible)**:
Register a node with a node ID exceeding 128 characters
**Anything else we need to know?**:
We overloaded the node ID to contain all of the details necessary to provide data access to the nodes from our storage array (e.g. {"name":"node1","uuid":"some_uuid","iqns":["iqn.1994-05.com.redhat:15d763458dd"],"networks":["172.10.0.0","172.20.16.0"]}).  We used this during ControllerVolumePublish to notify the SP of the node details.  This worked fine in 1.12 and 1.13.  Now that a new validation has been added to the length of the CSI node ID, we cannot register. 

**Environment**:
- Kubernetes version: 1.14.2

**Comment by rgcostea** [comment]
@kubernetes/sig-storage

**Comment by liggitt** [comment]
To be compliant with the CSI spec. See https://github.com/container-storage-interface/spec/blob/master/spec.md#size-limits

https://github.com/container-storage-interface/spec/pull/132
