### ISSUE TITLE
Documentation for --leader-elect-renew-deadline is incorrect

### ISSUE THREAD

**Issue by manderson23** [kubernetes/kubernetes#78759]
The documentation for `--leader-elect-renew-deadline` argument to kube-controller-manager states 

```This must be less than or equal to the lease duration```.

When I deploy kube-controller-manager with  `--leader-elect-renew-deadline` and  `--leader-elect-lease-duration` set to the same value I see a panic on startup
```
Flag --address has been deprecated, see --bind-address instead.
I0606 09:40:01.196052       1 serving.go:319] Generated self-signed cert in-memory
I0606 09:40:01.649334       1 controllermanager.go:155] Version: v1.14.1
I0606 09:40:01.649816       1 secure_serving.go:116] Serving securely on [::]:10257
I0606 09:40:01.650152       1 deprecated_insecure_serving.go:51] Serving insecurely on [::]:10252
panic: leaseDuration must be greater than renewDeadline
```

**Comment by manderson23** [comment]
@kubernetes/sig-docs

**Comment by sftim** [comment]
I think this is also
/sig api-machinery
