### ISSUE TITLE
Service load balancing with memory usage

### ISSUE THREAD

**Issue by Guo-astro** [kubernetes/kubernetes#78752]
**What would you like to be added**:
Presently,  the service cannot load balance according to pod memory usage. Is this by design 
or we can enhance it?
**Why is this needed**:
When an application with a large memory footprint, we want to avoid multi same requests routed to the same pod which will kill the pod. Any way to prevent that? Or we can monitor the memory usage of each pod and modify the load balancing algorithm

**Comment by Guo-astro** [comment]
@kubernetes/sig-architecture-feature-requests

**Comment by Guo-astro** [comment]
@kubernetes/sig-autoscaling-feature-requests

**Comment by vllry** [comment]
Perhaps post a KEP? Removing sig-arch until there is a cross-SIG plan.

/remove-sig architecture
