### ISSUE TITLE
goruntine leak if we use client-go in async timeout scene

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#78766]
**What happened**:

Recently we found that kube-apiserver will leak goruntine in large-scale scene with lots of 504 response code, and lots of logs like `Throttling request took %v, request: %s:%s`

**What you expected to happen**:

Fix the goruntine leak.

**How to reproduce it (as minimally and precisely as possible)**:

Set-up a large-scale Kubernetes cluster, or the following codes may help you how the goruntine leaks:

* The root cause of the problem is at [k8s.io/client-go/rest/request.go#L806](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L806):
```go
func (r *Request) Do() Result {
	r.tryThrottle()
 	
	...
}
```

* Reproduce it:
```go
var (
	leak int32 = 0
)

func getAsync(client rest.Interface) (interface{}, error) {
	ctx, cancelFn := context.WithTimeout(context.Background(), time.Second*5)
	defer cancelFn()

	resultCh := make(chan interface{}, 1)
	defer close(resultCh)

	go func() {
		atomic.AddInt32(&leak, 1)
		resultCh <- client.
			Get().Context(ctx).Timeout(time.Second * 5).
			Resource("pods").Namespace("default").Name("foo").
			Do()
		atomic.AddInt32(&leak, -1)
	}()

	select {
	case <-ctx.Done():
		return nil, fmt.Errorf("timeout")
	case result := <-resultCh:
		return result, nil
	}
}

func main() {
	// if you want to run this main function, please set master and kubeconfig value.
	config, err := clientcmd.BuildConfigFromFlags(master, kubeconfig)

	if nil != err {
		panic(err)
	}

	// set QPS to a very low value, reproduce large-scale scenes
	config.QPS = 0.000001
	config.Burst = 1

	if nil != err {
		panic(fmt.Errorf("failed to init client, err: %v", err))
	}

	c, err := kubernetes.NewForConfig(config)
	if nil != err {
		panic(fmt.Errorf("failed to init client, err: %v\n", err))
	}

	wait := sync.WaitGroup{}

	for i := 0; i < 1000; i++ {
		wait.Add(1)
		go func() {
			getAsync(c.RESTClient())
			wait.Done()
		}()
	}

	wait.Wait()

	fmt.Printf("goruntine leak num: %v", leak)
}

```

**Anything else we need to know?**:

Nothing yet.

**Environment**:

Never mind, the latest version of Kubernetes also has this issue.

**Comment by fedebongio** [comment]
cizixs@
/cc @jpbetz

**Comment by fedebongio** [comment]
@cizixs

**Comment by liggitt** [comment]
I don't think it's actually a leak, the goroutines do get released eventually

it looks like there's a context-aware ratelimiter method (`Wait`) we could investigate switching to (though it would need to be scale tested to make sure the more complex per-request logic didn't regress us)

**Comment by answer1991** [comment]
@liggitt 

> I don't think it's actually a leak, the goroutines do get released eventually

Yes, the goroutines will get released finally. But think about this:

The kube-apiserver accepts 1000 request in every second (QPS 1000), and QPS of client-go which kube-apiserver used to call apiextensions-apiserver and webhook-server only have 100. As we know, the kube-apiserver HTTP handler is wrapped with timeout filter just like my example codes above, then the backlog goroutines which hang at `r.tryThrottle()` will be more and more.

Your experimental commit is really cool, we really need context-aware ratelimiter method if we use ratelimiter in async sence.

**Comment by cizixs** [comment]
@liggitt It's not ideal to block on `tryThrottle()` method, as @answer1991 mentioned, this would cause APIServer experience higher and higher load, and unable to recover.

How about return `429 Too Many Requests` after given time(or even immediately), so burst requests won't cause APIServer too much load.

**Comment by adohe** [comment]
> kube-apiserver used to call apiextensions-apiserver

Finally kube-apiserver should not act as proxy to call aa server, redirect should be more acceptable.

**Comment by liggitt** [comment]
> Finally kube-apiserver should not act as proxy to call aa server, redirect should be more acceptable.

That requires all API clients to have visibility to all extension servers, and all extension servers to recognize all configured end-user authentication methods. Neither of those can be assumed today.

**Comment by lavalamp** [comment]
I consider #80465 the best defense against this issue.

**Comment by lavalamp** [comment]
The actual leak is fixed here: https://github.com/kubernetes/kubernetes/pull/83333
