### ISSUE TITLE
divide by zero in genericScheduler#findNodesThatFit

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#78776]
seen in TestNodePIDPressure in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78770/pull-kubernetes-integration/1136730984738197506/

```
panic: runtime error: integer divide by zero
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
/usr/local/go/src/runtime/panic.go:522 +0x1b5
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:520 +0xc97
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:207 +0x43b
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:284 +0x5d
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:461 +0x445
```

/milestone v1.15
/sig scheduling
/priority critical-urgent

including in the milestone to make sure this gets triaged before release

**Comment by liggitt** [comment]
added in https://github.com/kubernetes/kubernetes/commit/e660e84459b990239ed1a6f65627cd08617d21f6#diff-c237cdd9e4cb201118ca380732d7f361R519 in #77509

**Comment by dims** [comment]
cc @ahg-g

**Comment by ahg-g** [comment]
I think we should revert #77509, I created #78782.

**Comment by liggitt** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/78782
