### ISSUE TITLE
cronjob scheudle does not use master's timezone - instead it uses utc

### ISSUE THREAD

**Issue by shaozi** [kubernetes/kubernetes#78795]
**What happened**:
The master is at PDT (-7).

Verified local time on master:

```sh
timedatectl
                      Local time: Fri 2019-06-07 09:21:42 PDT
                  Universal time: Fri 2019-06-07 16:21:42 UTC
                        RTC time: Fri 2019-06-07 16:21:42
                       Time zone: America/Los_Angeles (PDT, -0700)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
```

Created a cronjob with schedule of `"0 12 * * 5"` to run on Friday noon.

```
kubectl describe cj manager-weekly-us
Name:                          manager-weekly-us
Namespace:                     default
Labels:                        environment=production
                               function=report
Annotations:                   <none>
Schedule:                      0 12 * * 5
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  824638405216
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  <none>
  Containers:
   manager-weekly-us:
    Image:      mantisphp7:0.8
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/sh
      -c
      /usr/bin/php  /var/www/html/mantis/reports/manager_report.php -i summary -m -t "us.field us.devops et carrier"
    Environment:  <none>
    Mounts:
      /mantis_file_upload from upload (rw)
      /scripts from scripts (rw)
      /var/www/html/mantis from www (rw)
  Volumes:
   www:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mantis-www
    ReadOnly:   false
   upload:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mantis-upload
    ReadOnly:   false
   scripts:
    Type:            PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:       mantis-scripts
    ReadOnly:        false
Last Schedule Time:  Fri, 07 Jun 2019 05:00:00 -0700
Active Jobs:         <none>
Events:              <none>
```

You can see it actually ran on 12 UTC, which is 5AM PDT.

**What you expected to happen**:

According to the document: 

> Note: All CronJob schedule: times are based on the timezone of the master where the job is initiated.

**How to reproduce it (as minimally and precisely as possible)**:

1. make sure your host is on some timezone not utc
2. create a cronjob with schedule `'0 12 * * *'` (or any hour that fit you)
3. observe when the cronjob runs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
self hosted
- OS (e.g: `cat /etc/os-release`):

```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):

`Linux smart-sjc-node1 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
kubeadm

- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
this is working as intended. adding timezone support to cronjobs was proposed in https://github.com/kubernetes/kubernetes/issues/47202 and ultimately decided against. see https://github.com/kubernetes/kubernetes/issues/47202#issuecomment-360820586

/close

**Comment by FishkinsDC** [comment]
@liggitt From what I see, that comment said they wouldn't add _per cronjob_ timezones, not that they won't respect the TZ of the master.

The k8s cronjobs docs say this:
> Note: All CronJob schedule: times are based on the timezone of the master where the job is initiated.

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by justgotthis** [comment]
Can we please re-open this bug? I did not see a solution to this. It was wrongfully closed referencing another issue. We are running into this bug as well currently so let me know if I need to open a new bug for this.

**Comment by kazusa-qooq** [comment]
i have same problem.

**Comment by justgotthis** [comment]
added ticket to track this as we are all still having issues:

https://github.com/kubernetes/kubernetes/issues/80577

**Comment by tracker1** [comment]
Silly question, why not set servers to UTC, and recognize the offset when setting these things?

**Comment by shaozi** [comment]
because when Daylight Saving kicks in or out, the offset will be changed. and you need to manually change your cronjob. (if you cronjob is scheduled, say, 9 AM everyday).

**Comment by spearsem** [comment]
Another bump to re-open. Many jobs can't be expressed in a fixed UTC time stamp format, but need to change as timezones change, such as with daylight savings.

**Comment by ramseydsilva** [comment]
This is indeed a bug. The name `Cronjob` itself is misleading since it does not follow the Cron specification. Most kubernetes users will assume Time Zone support comes out of the box. It is dissapointing that the core developers chose not to include this. This issue should affect > 90% of the users who don't operate on UTC time.

**Comment by mcobzarenco** [comment]
> This issue should affect > 90% of the users who don't operate on UTC time.
I arrived at this issue having the same issue, so I certainly agree, but at the same time I can also see why core devs would not want to maintenance burden -- timezones are a mess at the whims of governments (e.g. see Russia cancelling DST)

**Comment by KlavsKlavsen** [comment]
The docs clearly says that it follows the master's timezone - yet this issue documents that, even though his master is following PDT timezone - cronjob is following UTZ. So either fix documentation (and document what timezone it actually follows) or find bug?

**Comment by shaozi** [comment]
I did not see it mentioned here, so I copy and paste the link for a cronjob controller for Kubernetes with support for time zones:

https://github.com/hiddeco/cronjobber

I have been using it since

**Comment by balibebas** [comment]
> It is dissapointing that the core developers chose not to include this.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/19-Graduate-CronJob-to-Stable#support-timezone-for-cronjobs
