### ISSUE TITLE
CoreOS + Azure + Weave Getting Started Guide questions

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#7879]
I'm trying to discover the answers to some of these myself:

1. How do I connect my `kubectl` running locally on my machine, to the cluster that I've created with the CoreOS+Azure Getting Started Guide?

2. How does external routing work? At the end, there's only a single endpoint added and it's added to a specific minion. Does the proxy running on that single minion distribute load across all the minions? Is that really the recommended way of pointing the outside world at a Kubernetes install?

**Comment by mbforbes** [comment]
+cc @ahmetalpbalkan @kunchenguid

**Comment by colemickens** [comment]
For #1, the answer is to run a ssh tunnel to expose the master's 8080 locally. (I also noticed that just port fowarding 8080 to the Internet allowed at least the `/` path to be hit without auth. That seems scary to me -- I thought apiserver only listened for connections from localhost on the insecure port).

For #2, the answer seems to be that this can't really be done in Azure properly at the moment. The Azure load balancer requires that the combination of load balancer port and protocol be unique per machine endpoint. This means that I can't have two virtual IPs both directing port 80 traffic to the same set of machines, even if their internal ports are different.

I guess that the only option, at the moment, is to use the kubelet software balancing?

I don't know of the appropriate Azure folks to contact about this, or if I'm looking at things incorrectly.

**Comment by colemickens** [comment]
RE: Azure & IP-per-Service:

https://social.msdn.microsoft.com/Forums/azure/en-US/ad406b89-f497-44dd-9bd2-65ed26c02670/azure-load-balancer-cant-support-kubernetes?forum=WAVirtualMachinesVirtualNetwork

**Comment by errordeveloper** [comment]
> For #1, the answer is to run a ssh tunnel to expose the master's 8080 locally. (I also noticed that just port fowarding 8080 to the Internet allowed at least the / path to be hit without auth. That seems scary to me -- I thought apiserver only listened for connections from localhost on the insecure port).

Interesting... As you can see, I haven't configure the auth side of things, to avoid default passwords etc.

> For #2, the answer seems to be that this can't really be done in Azure properly at the moment. The Azure load balancer requires that the combination of load balancer port and protocol be unique per machine endpoint. This means that I can't have two virtual IPs both directing port 80 traffic to the same set of machines, even if their internal ports are different.

Well, this part needs a cloud provider implementation, which is currently missing for Azure. I think @jeffmendoza (or someone else at Microsoft) was looking into it...

**Comment by colemickens** [comment]
Sure, I don't expect the "createExternalLoadBalancer" to be respected yet, but as far as I can tell, the Azure networking features are limited such that it's not possible to setup the firewall rules manually even (such as the cloud provider impl would). It seems like Azure lacks the features necessary to properly enable Kubernetes in all scenarios.
