### ISSUE TITLE
Clean up all of our Dockerfiles

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#7881]
We should make them all FROM either scratch, busybox, or debian:jessie (or ubuntu:14.04 but it is bigger).  I am sad that there is not an ultra-small "just enough debian to run apt-get install" base.

**Comment by thockin** [comment]
it looks like debian:jessie is 50MB bigger than wheezy.  Sigh.

**Comment by mbforbes** [comment]
huge +1 for the "just enough debian to run apt-get install" base. This has confused me about Docker containers since I first attempted to understand them.

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by thockin** [comment]
@timstclair in case this wasn't in your inbox - up to you when to close it :)

**Comment by timstclair** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/40248
