### ISSUE TITLE
Add floating-point support to IntOrPercent

### ISSUE THREAD

**Issue by jasongwartz** [kubernetes/kubernetes#78822]
**What would you like to be added**:
Additional floating-point handling to `GetValueFromIntOrPercent()` https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L153, allowing users to pass `0.5` for the same behaviour as `"50%"`.

**Why is this needed**:
Some recent confusion arose with the PodDisruptionBudget documentation, where it was assumed that, for example, `0.5` can be passed to `minAvailable` which would represent 50%. This has been addressed with: https://github.com/kubernetes/website/issues/14682 and https://github.com/kubernetes/website/pull/14788

However, while writing the above PR for the docs, it occurred to me that this might be a common way users expect to interact with these kind of percentage-based APIs, and so the current behaviour (passing a percentage as a string) might seem like a bug.

**Comment by jasongwartz** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by tedyu** [comment]
If we enhance IntOrString, it seems the new type should support int, float and string.
```
type IntFloatOrString struct {
	Type   Type      `protobuf:"varint,1,opt,name=type,casttype=Type"`
	IntVal int32     `protobuf:"varint,2,opt,name=intVal"`
	StrVal string    `protobuf:"bytes,3,opt,name=strVal"`
	FloatVal float32 `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
}
```

**Comment by liggitt** [comment]
IntOrSteing is generally regarded as a mistake, I don't anticipate furthering the multi-schema aspect. It also would not possible to do that in a way that would not break backwards compatibility with old clients. 

Additionally, use of floating point numbers in API types is not recommended. See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types

/close
