### ISSUE TITLE
Promote LimitRange Tests to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78828]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the LimitRange kind:

[replaceCoreV1NamespacedLimitRange](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NamespacedLimitRange&showUntested=false&showConformanceTested=false&level=stable)

[deleteCoreV1NamespacedLimitRange](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-deleteCoreV1NamespacedLimitRange&showUntested=false&showConformanceTested=false&level=stable)

[createCoreV1NamespacedLimitRange](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-createCoreV1NamespacedLimitRange&showUntested=false&showConformanceTested=false&level=stable)

[readCoreV1NamespacedLimitRange](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-readCoreV1NamespacedLimitRange&showUntested=false&showConformanceTested=false&level=stable)

These are stable core endpoints, which have existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by hh** [comment]
Promoting this one test will increase Conformance Coverage by 4 endpoints.

```
[sig-scheduling] LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied.
```

**Comment by devaips** [comment]
PR #78921 was closed because the test [needs to be broken into multiple parts](https://github.com/kubernetes/kubernetes/pull/78921#discussion_r295536235), because it has too much going on. It was identified as a good candidate, and the discussion on refactoring it [is ongoing](https://github.com/kubernetes/kubernetes/pull/78921#issuecomment-506985021)
