### ISSUE TITLE
Field Selector not applied in fake clients List

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/kubernetes#78824]
**What would you like to be added**:
Currently, only Label selectors are applied in the `List` methods for the fake clients. 

Enhance the `List` methods to also apply Field selectors.

**Why is this needed**:
Prevent false positives in tests depending on field selector being applied.

For example: [this Events test](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/pod/events_test.go) in the Kubernetes Dashboard repository will succeed regardless of the name passed to it because it depends on [a function which depends on the field selector](https://github.com/kubernetes/dashboard/blob/e8e4fd43b3c6cfb75ab2cd9e2e1575f332724867/src/app/backend/resource/event/common.go#L41) which is not applied during the test.

**The criminal:**
[`ExtractFromListOptions`](https://github.com/kubernetes/kubernetes/blob/a363b153851326ece7f81f4c1ae0a1ab8700a209/staging/src/k8s.io/client-go/testing/actions.go#L295) returns `(labelSelector, fieldSelector, resourceVersion)`.

[The generator](https://github.com/kubernetes/kubernetes/blob/a363b153851326ece7f81f4c1ae0a1ab8700a209/staging/src/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go#L333) in `client-gen` only applies `labelSelector`, ignoring the rest.

Relevant snippet (lines `333` to `342`):
```go
label, _, _ := $.ExtractFromListOptions|raw$(opts)
if label == nil {
	label = $.Everything|raw$()
}
list := &$.type|raw$List{ListMeta: obj.(*$.type|raw$List).ListMeta}
for _, item := range obj.(*$.type|raw$List).Items {
	if label.Matches(labels.Set(item.Labels)) {
		list.Items = append(list.Items, item)
	}
}
```

**Todo:**
Extend above code section to also apply the fieldSelector.

**Related:**: https://github.com/kubernetes/kubernetes/pull/76735

/sig api-machinery

**Comment by eloyekunle** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Field selectors are applied serverside. The logic to extract object values to match field selectors is not available from within the fake client

**Comment by eloyekunle** [comment]
@liggitt Is it possible to simulate the logic in the fake client?

**Comment by liggitt** [comment]
You can add reactors to your instance of a fake client that return subsets of the list

**Comment by eloyekunle** [comment]
Thanks @liggitt. Closing now.
