### ISSUE TITLE
 Promote ConfigMap Tests to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78832]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the ConfigMap kind:

[patchCoreV1NamespacedConfigMap](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-patchCoreV1NamespacedConfigMap&showUntested=false&showConformanceTested=false)

This is a stable core endpoint which has existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by hh** [comment]
Promoting https://github.com/kubernetes/kubernetes/pull/79119 will increase Conformance Coverage by 1 endpoint.

```
[sig-api-machinery] AdmissionWebhook Should be able to deny pod and configmap creation
```

**Comment by BobyMCbobs** [comment]
PR [#79119](https://github.com/kubernetes/kubernetes/pull/79119) was closed because AdmissionWebHook is not yet GA.

/close

**Comment by BobyMCbobs** [comment]
This test uses a beta version of the API. According to the [Conformance Test Requirements](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements), this is prohibited.

The URL of the API which is test is hitting is [/apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#list-validatingwebhookconfiguration-v1beta1-admissionregistration-k8s-io).

**Comment by draveness** [comment]
/unassign

The original PR was superseded by @BobyMCbobs 's #80787
