### ISSUE TITLE
 Promote PersistentVolumeClaim Tests to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78830]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the PersistentVolumeClaim kind:

[createCoreV1NamespacedPersistentVolumeClaim](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-createCoreV1NamespacedPersistentVolumeClaim&showUntested=false&showConformanceTested=false)

[deleteCoreV1NamespacedPersistentVolumeClaim](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-deleteCoreV1NamespacedPersistentVolumeClaim&showUntested=false&showConformanceTested=false)

[readCoreV1NamespacedPersistentVolumeClaim](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-readCoreV1NamespacedPersistentVolumeClaim&showUntested=false&showConformanceTested=false)

[replaceCoreV1NamespacedPersistentVolumeClaim](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NamespacedPersistentVolumeClaim&showUntested=false&showConformanceTested=false)

These are stable core endpoints which have existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by hh** [comment]
We need to identify exactly which test is hitting *PVC endpoints.

**Comment by hh** [comment]
The tests that we could promote here would increase coverage by 4 endpoints.
However we need a test strategy for storage that works across all providers.
Basically tests that support the various ways providers supply PVCs.

```
[sig-storage] Volume expand should not allow expansion of pvcs without AllowVolumeExpansion property
[sig-storage] Volume expand Verify if offline PVC expansion works
[sig-storage] Volume expand should resize volume when PVC is edited while pod is using it
[sig-storage] Mounted volume expand Should verify mounted devices can be resized
[sig-storage] Volume expand should allow expansion of block volumes
```

**Comment by spiffxp** [comment]
Can we rewrite these to use local persistent volumes https://github.com/kubernetes/kubernetes/pull/79680#issuecomment-509159742

**Comment by draveness** [comment]
Sorry, I'm not quite familiar with the local persistent volumes

/unassign

**Comment by devaips** [comment]
PR closed due to need for an overall strategy for how to handle storage tests which in a provider agnostic way. https://github.com/kubernetes/kubernetes/pull/79680#issuecomment-509159742
