### ISSUE TITLE
Write Scale Tests for Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78834]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the Scale kind:

[replaceCoreV1NamespacedReplicationControllerScale](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NamespacedReplicationControllerScale&showUntested=false&showConformanceTested=false)

[readCoreV1NamespacedReplicationControllerScale](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-readCoreV1NamespacedReplicationControllerScale&showUntested=false&showConformanceTested=false)

These are stable core endpoints which are covered by an existing test, but the test does not directly exercise these endpoints. New tests should be written.

/area test
/area conformance
/sig testing

**Comment by zachmandeville** [comment]
Promoting #79112 would increase conformance coverage by two endpoints
``` 
[sig-network] Services should create endpoints for unready pods
```

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/79122#issuecomment-506766182 indicates the test in question can't be promoted as written

Also, in the context of this issue, I feel like that test is a poor example of something that _directly_ exercises the endpoints listed in the description.  Let's try to avoid promoting tests that incidentally hit these endpoints

**Comment by spiffxp** [comment]
/assign @devaips 
since you were also working on #79122 

My advice would be to:
- punt on rewriting the test that indirectly exercise these endpoints
- retitle this issue as Write Scale Tests for Conformance, move this to a different umbrella issue

**Comment by devaips** [comment]
I've updated the Title and Description. We could put this under umbrella ticket https://github.com/kubernetes/kubernetes/issues/78749

**Comment by BobyMCbobs** [comment]
[This test (#79087)](https://github.com/kubernetes/kubernetes/pull/79087) was closed because it is disruptive -- deletes Nodes, which is dangerous.

**Comment by BobyMCbobs** [comment]
[This test (#79122)](https://github.com/kubernetes/kubernetes/pull/79122) was closed because:
- It uses a deprecated annotation (`tolerate-unready-endpoints`)
- It uses preStop hook that sleeps, instead of using agnhost netexec
- It uses `wget`, which is Linux specific
