### ISSUE TITLE
Promote ResourceQuota Tests to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78831]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the ResourceQuota kind:

[deleteCoreV1NamespacedResourceQuota](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-deleteCoreV1NamespacedResourceQuota&showUntested=false&showConformanceTested=false&level=stable)

[replaceCoreV1NamespacedResourceQuota](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NamespacedResourceQuota&showUntested=false&showConformanceTested=false&level=stable)

These are stable core endpoints which have existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by devaips** [comment]
Relevant PR: https://github.com/kubernetes/kubernetes/pull/78331

**Comment by draveness** [comment]
the `createCoreV1NamespacedPersistentVolumeClaim` is supposed to included in https://github.com/kubernetes/kubernetes/issues/78830 imo.

**Comment by devaips** [comment]
> the `createCoreV1NamespacedPersistentVolumeClaim` is supposed to included in #78830 imo.

You're right, it was incorrect. I've changed it now. Thanks for noticing!

**Comment by hh** [comment]
The specific tests that if promoted would increase Conformance Coverage by 2 endpoints:
```
[sig-scheduling] LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied.
```

**Comment by hh** [comment]
Promoting https://github.com/kubernetes/kubernetes/pull/79120 will increase Conformance Coverage by 2 endpoints.
