### ISSUE TITLE
Promote ServiceAccount Tests to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78835]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the ServiceAccount kind:

[replaceCoreV1NamespacedServiceAccount](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NamespacedServiceAccount&showUntested=false&showConformanceTested=false)

This is a stable core endpoint which has existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by hh** [comment]
Promoting this test will increase Conformance Coverage by 1 endpoint.
```
[sig-auth] ServiceAccounts should ensure a single API token exists
```

**Comment by devaips** [comment]
Closed due to test [being deemed a non-viable](https://github.com/kubernetes/kubernetes/pull/79085#issuecomment-503270945) candidate for Conformance.
