### ISSUE TITLE
Promote Node Tests to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#78833]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the Node kind:

[replaceCoreV1NodeStatus](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NodeStatus&showUntested=false&showConformanceTested=false)

[replaceCoreV1Node](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1Node&showUntested=false&showConformanceTested=false)

[patchCoreV1Node](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-patchCoreV1Node&showUntested=false&showConformanceTested=false)

[readCoreV1Node](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-readCoreV1Node&showUntested=false&showConformanceTested=false)

These are stable core endpoints which have existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by devaips** [comment]
#79630 Was closed due to the test needing some superficial refactoring in order to be compatible with the Conformance framework.

**Comment by spiffxp** [comment]
I don't think #79679 should be promoted in the name of exercising these endpoints, it's too rube-goldbergian.  It may be a decent description of a Preemption behavior however, so awaiting feedback on that.

If there are no other tests that exercise these endpoints more directly, they'll need to be written.

**Comment by devaips** [comment]
The tests which we attempted to promote for this test need to be rewritten. The PR for the rewrite of 'Kubelet:Timed Pod Deletion' test is https://github.com/kubernetes/kubernetes/pull/80731
