### ISSUE TITLE
Kubernetes-master build failing with golang-master

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#78845]
Hi,

I am trying to build kubernetes-master with golang-master and I am getting this error:

```
# make all
+++ [0610 08:44:31] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd latest
go: finding k8s.io/kubernetes/vendor/k8s.io latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator latest
go: finding k8s.io/kubernetes/vendor latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen latest
can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: unknown import path "k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen": no matching versions for query "latest"
!!! [0610 08:44:56] Call tree:
!!! [0610 08:44:56]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:715 kube::golang::build_some_binaries(...)
!!! [0610 08:44:56]  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:854 kube::golang::build_binaries_for_platform(...)
!!! [0610 08:44:56]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0610 08:44:56] Call tree:
!!! [0610 08:44:56]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0610 08:44:56] Call tree:
!!! [0610 08:44:56]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile.generated_files:200: recipe for target '_output/bin/deepcopy-gen' failed
make[1]: *** [_output/bin/deepcopy-gen] Error 1
Makefile:557: recipe for target 'generated_files' failed
make: *** [generated_files] Error 2
```

Here is the golang version:

```
# go version
go version devel +323212b Sun Jun 9 16:23:11 2019 +0000 linux/amd64
```

Any tips on what could be the issue here? Or how to debug it? TIA.

CC: @mkumatag @liggitt

**Comment by liggitt** [comment]
the branch at https://github.com/liggitt/kubernetes/commits/go-1.13 allows `make all` to work using go1.13 (but not go1.12).

It fixes:
* Opting into vendor mode when using modules (required in go1.13)
* Switching away from ./vendor/foo builds to just build foo (this is what doesn't work in 1.12)
* Hacked up boilerplate locating code that was making assumptions about GOPATH that are no longer true in module builds

It does not resolve lots of assumptions in our code generation scripts about finding things via GOPATH, so `make update` doesn't regenerate properly yet

**Comment by BenTheElder** [comment]
@liggitt https://github.com/kubernetes-sigs/kind/blob/f03d85409082ae9b06410c716640005b555da722/hack/update/generated.sh has some hacks to use the code generators with a modules based repo without requiring the repo be in GOPATH, FWIW. might be useful :-)

**Comment by mkumatag** [comment]
> @liggitt https://github.com/kubernetes-sigs/kind/blob/f03d85409082ae9b06410c716640005b555da722/hack/update/generated.sh has some hacks to use the code generators with a modules based repo without requiring the repo be in GOPATH, FWIW. might be useful :-)

@bentheelder are you talking about following lines of code:

https://github.com/kubernetes-sigs/kind/blob/f03d85409082ae9b06410c716640005b555da722/hack/update/generated.sh#L24:L27

**Comment by BenTheElder** [comment]
@mkumatag the most relevant part would probably be https://github.com/kubernetes-sigs/kind/blob/f03d85409082ae9b06410c716640005b555da722/hack/update/generated.sh#L46-L54
```bash
# fake being in a gopath
FAKE_GOPATH="$(mktemp -d)"
trap 'rm -rf ${FAKE_GOPATH}' EXIT

FAKE_REPOPATH="${FAKE_GOPATH}/src/sigs.k8s.io/kind"
mkdir -p "$(dirname "${FAKE_REPOPATH}")" && ln -s "${REPO_ROOT}" "${FAKE_REPOPATH}"

export GOPATH="${FAKE_GOPATH}"
cd "${FAKE_REPOPATH}"
```

Faking it this way makes it a lot easier to deal with legacy tooling that expects the source to be in a particular GOPATH without actually needing it to be in one.

That script goes a bit further and also:
- installs the development-time only dependencies from their own go module (not the main project module, so the main project module doesn't need to depend on them or include them as transitive deps for consumers)
- enables running the generators in classic GOPATH/vendor mode while not checking vendor into the repo (xref: https://github.com/kubernetes/code-generator/issues/69)

We're probably not ready for those other aspects yet, but we might want to do them in the future.

**Comment by mm4tt** [comment]
@liggitt, I think it got broken again with https://go-review.googlesource.com/c/go/+/184098
Could you take a look when you have a moment?

**Comment by liggitt** [comment]
@mm4tt updated, though it looks like building takes *waaaaaay* longer with latest go devel... I'm sure some of our generation scripts are making go ast or list or build calls that were reasonable under gopath mode and are unreasonable in go modules mode

**Comment by BenTheElder** [comment]
@liggitt yes, the code generators are extremely slow under module mode https://github.com/kubernetes/code-generator/issues/69

**Comment by mm4tt** [comment]
Thanks @liggitt for taking a look and updating your branch. I tried it with the golang head, but either something doesn't work or it indeed takes waaaaay longer, and waaaay is additional few hours. 

I run:

```
make  clean quick-release

+++ [0705 11:46:20] Verifying Prerequisites....
+++ [0705 11:46:23] Removing _output directory          
+++ [0705 11:46:23] Verifying Prerequisites....
+++ [0705 11:46:24] Building Docker image kube-build:build-1c09373475-5-v1.13.x-20190705
+++ [0705 11:46:30] Creating data container kube-build-data-1c09373475-5-v1.13.x-20190705
+++ [0705 11:46:45] Syncing sources to container
+++ [0705 11:47:12] Running build command...                                               
go/build: importGo k8s.io/kubernetes: exit status 1                            
can't load package: package k8s.io/kubernetes: no Go files in /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes
                                 
                                                                                  
+++ [0705 11:47:15] Building go targets for linux/amd64:
    k8s.io/code-generator/cmd/deepcopy-gen
```

And I killed it after ~90min as it didn't seem to moving forward. Is it expected to take that long?

**Comment by liggitt** [comment]
it took O(hours) for me to run a build

**Comment by liggitt** [comment]
looks like `go mod tidy` in go1.13 might now require all transitively referenced packages in dependencies to resolve, even ones we don't actually depend on in our tree.

that means the [outdated k8s.io/client-go library](https://github.com/heketi/heketi/blob/v9.0.0/glide.yaml#L23-L24) the current version of the heketi dependency uses will not work properly

xref https://github.com/heketi/heketi/pull/1542

**Comment by liggitt** [comment]
umbrella issue for go1.13 in https://github.com/kubernetes/kubernetes/issues/82531

/close

**Comment by AmberLJC** [comment]
Can anyone summarize how to solve this. Still get the same error
THX

**Comment by liggitt** [comment]
The "opt out of module mode for builds" commit from https://github.com/kubernetes/kubernetes/pull/82809 is the simplest workaround for the moment. When go 1.13.2 is released and validated by sig-scalability, we will proceed with #82809 and complete the transition to building with 1.13.x
