### ISSUE TITLE
Enable setting up Kubemark master outside GCE.

### ISSUE THREAD

**Issue by cy-zheng** [kubernetes/kubernetes#78842]
**What would you like to be added**:
Enable setting up Kubemark master outside GCE.

**Why is this needed**:
Currently, kubemark master deployment scripts & config files is designed for GCE, and there are not enough information about deploying on bare metal machines. But kubemark is a brilliant performance test tool and we want to use it in company intranet.

**Comment by snowplayfire** [comment]
I have recorded how to setup a kubemark cluster outside GCE as follows: https://github.com/snowplayfire/kubemark-outside-gce

Hope it is helpful for you.

**Comment by dims** [comment]
@snowplayfire if you want to update the content here - https://github.com/kubernetes/community/tree/787bc4f78c9e2d23c614103ebc4d477b9a240258/contributors/devel/sig-scalability - that will be great as well!

**Comment by snowplayfire** [comment]
@dims  I have committed a PR as your suggestion, thank you!

**Comment by gaorong** [comment]
kubemark has supported on-premise cluster.

ref: https://github.com/kubernetes/kubernetes/pull/44394

**Comment by rthallisey** [comment]
I haven't tested with the pre-existing cluster scripts in quite a bit of time.  It's likely the scripts there are outdated and need updating.
