### ISSUE TITLE
kubectl cp with wildcards do not work

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/kubernetes#78854]
**What happened**:
Kubectl cp in 1.14.2 doesn't support wildcards, despite #72641 being merged.

From container to host (trying to copy `entrypoint,sh`):
```
$ kubectl cp consul-5d98b69458-w4tzm:/entry*.sh .
tar: Removing leading `/' from member names
tar: /entry*.sh: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

From host to container (where * expands to 2 local files at least):
```
$ kubectl cp * consul-5d98b69458-w4tzm:/
error: one of src or dest must be a remote file specification
```

**What you expected to happen**:
Kubectl can handle wildcards, and files are copied successfully.

**How to reproduce it (as minimally and precisely as possible)**
Try copy even a single file with wildcard from a pod:
```
$ kubectl cp <pod>:/entry*.sh .
```
or try to copy two or more files into a pod:
```
kubeclt cp * <pod>:/
```

**Anything else we need to know?**:
#72641 was merged without tests.

Also, passing unmatching filename wildcards to `kubectl cp` returns 0, while it should clearly be an error, ie. (without locally having file matching `foo*`):
```
$ kubectl cp foo* <pod>:/
$ echo $?
0
```
despite no files being copied.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on-prem VM
- OS (e.g: `cat /etc/os-release`): RHEL 7.6
- Kernel (e.g. `uname -a`): `Linux kubesingle 3.10.0-957.12.1.el7.x86_64 #1 SMP Wed Mar 20 11:34:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by tuminoid** [comment]
/sig cli
@dixudx

**Comment by dixudx** [comment]
> Kubectl cp in 1.14.2 doesn't support wildcards

@tuminoid Actually kubectl cp does support wildcards now.

> $ kubectl cp consul-5d98b69458-w4tzm:/entry*.sh .
tar: Removing leading `/' from member names
tar: /entry*.sh: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

Seems we are encountering an edge case. You can try to issue `tar cf - /entry*.sh > /dev/null` in the container manually. A same error will occur.

Anyway, current `kubectl cp` does not well handle such case. This is truly a bug of `kubectl cp`. Will send out a fix later.

**Comment by tuminoid** [comment]
Can you give working examples? I thought I was testing the simplest possible cases.

`kubectl cp --help` has no examples or mentions about supporting wildcards either.

**Comment by siosphere** [comment]
Trying to copy local to remote with wildcard on the local side does not work.

```
kubectl cp ./build/local/04eb0d8a255da29fa9f3d7c9979e4e068e6e4845/dist/* titan-v1-7d95b6f499-xv2cq:/assets/
error: one of src or dest must be a remote file specification
```
Even with providing extension
```
kubectl cp ./build/local/04eb0d8a255da29fa9f3d7c9979e4e068e6e4845/dist/*.js titan-v1-7d95b6f499-xv2cq:/assets/
error: one of src or dest must be a remote file specification
```

**Comment by tedyu** [comment]
Looks like the wildcard doesn't support source or destination being local.
See CopyOptions#Run

**Comment by tuminoid** [comment]
> Looks like the wildcard doesn't support source or destination being local.
> See CopyOptions#Run

That doesn't make any sense. Wildcard destination isn't a thing, and remote to remote is not supported at all. Also, where/what is CopyOptions#Run?

> Seems we are encountering an edge case. You can try to issue `tar cf - /entry*.sh > /dev/null` in the container manually. A same error will occur.

It succeeds, why wouldn't it? There is /entrypoint.sh in container, and tar will pack it up fine.

```
[root@consul-5d98b69458-w4tzm /]# tar cf - /entry*.sh > /dev/null
tar: Removing leading `/' from member names
```

**Comment by dixudx** [comment]
@tuminoid @siosphere I got a fix #78928. Please help verify. Thanks.

> $ kubectl cp * consul-5d98b69458-w4tzm:/
error: one of src or dest must be a remote file specification

I did manually test #72641. But I disabled the glob by `set -f` (this was set by .bashrc automatically). `*` gets expansion. So the command gets multiple arguments, more than expected 2.

> $ kubectl cp consul-5d98b69458-w4tzm:/entry*.sh .
tar: Removing leading `/' from member names
tar: /entry*.sh: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

The same reason. The files get expansion out for the container.

**Comment by tuminoid** [comment]
> > $ kubectl cp * consul-5d98b69458-w4tzm:/
> > error: one of src or dest must be a remote file specification
> 
> I did manually test #72641. But I disabled the glob by `set -f` (this was set by .bashrc automatically). `*` gets expansion. So the command gets multiple arguments, more than expected 2.

That was not in anyway obvious that it should get exactly two arguments. I'd even argue that kubectl should handle getting multiple sources gracefully, rather than force specific single-quote syntax to do expansion by itself.

> > $ kubectl cp consul-5d98b69458-w4tzm:/entry*.sh .
> > tar: Removing leading `/' from member names
> > tar: /entry*.sh: Cannot stat: No such file or directory
> > tar: Exiting with failure status due to previous errors
> 
> The same reason. The files get expansion out for the container.

In this case the entry*.sh is passed to kubectl for expansion as it doesn't match anything locally. It rather looks like kubectl treats it literally, instead of expanding it.

**Comment by dixudx** [comment]
> In this case the entry*.sh is passed to kubectl for expansion as it doesn't match anything locally. It rather looks like kubectl treats it literally, instead of expanding it.

@tuminoid In this case, the `entry*.sh` is passed to remote kubelet, where it will get expansion.

**Comment by tuminoid** [comment]
> > In this case the entry*.sh is passed to kubectl for expansion as it doesn't match anything locally. It rather looks like kubectl treats it literally, instead of expanding it.
> 
> @tuminoid In this case, the `entry*.sh` is passed to remote kubelet, where it will get expansion.

The point here is that it didn't get expanded in remote kubelet. Doing the manual tar in container works, but not via kubectl, so nobody expanded it, but rather treated it as literal.

**Comment by dixudx** [comment]
> tar: /entry*.sh: Cannot stat: No such file or directory
>  it didn't get expanded in remote kubelet.

It got expanded in the remote kubelet. The above error just proved that.
In the fix, I used another way to avoid getting expansion.

**Comment by wmorrone** [comment]
It is unclear to me from the above posts whether cp has been implement or not.  I have been testing with kubectl 1.15.0 and kubectl 1.14.1 and the results are the same, wildcards do not work as expected.  

Starting with a folder /tmp/scripts on the source machine that contained the following files:
- test2.py
- test2.xml
- test3.py
- test3.xml

I executed the following command,
   kubectl cp /tmp/scripts/*.* <pod>:/tmp/scripts/. 
My expected result was that all the files in /tmp/scripts on the source machine would be copied to the folder /tmp/scripts on the target pod .  However, the command failed returning the following message
   error: one of src or dest must be a remote file specification

If I change the script to the following
  kubectl cp /tmp/scripts/test3.x* nifi-0:/tmp/scripts/.
the file test3.xml is copied. 
So in one sense the wildcard is working in that I did not have to specify the entire xml extension.  But, this is not the result I was expecting.

If I have missed something in my interpretation of the use of wildcards please let me know.

Regards

**Comment by Heronalps** [comment]
This issue is not solved in the latest version of kubectl.
e.g.

kubectl cp IMG_03* /path/to/pod
error: one of src or dest must be a remote file specification

Please work on it if possible. Thank you!

**Comment by tuminoid** [comment]
/reopen

This is still valid.

**Comment by heyjared** [comment]
here's a workaround
find . | xargs -i{} kubectl cp {} namespace/pod:path

**Comment by dan-tw** [comment]
> I executed the following command, kubectl cp /tmp/scripts/_._ pod:/tmp/scripts/. My expected result was that all the files in /tmp/scripts on the source machine would be copied to the folder /tmp/scripts on the target pod . However, the command failed returning the following message error: one of src or dest must be a remote file specification

Might be a bit late but in case it saves someone else looking, this is because **you can't use absolute paths for your source**.

So what you needed to do was navigate to `/tmp/scripts` on your local host and then run the following command:

```
cd /tmp/scripts
kubectl cp . pod:/tmp/scripts/.
```

Then it will copy all files within the `/tmp/scripts` directory to `pod:/tmp/scripts/`
