### ISSUE TITLE
windows: kubectl port-forward does not work

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#78857]
**What happened**:

/sig windows

**What you expected to happen**:

``kubectl port-forward`` will generate the follow error when using Windows pods:

    curl http://127.0.0.1:40271
    Handling connection for 40271
    E0610 14:21:10.685551  124724 portforward.go:400] an error occurred forwarding 40271 -> 80: error forwarding port 80 to pod 40c9dc69b4d527427b72ebe4d8ea4a6a794fd7acc96c20373d0257439654f98f, uid : unable to do port forwarding: socat not found.
    curl: (52) Empty reply from server

This issue does not appear when using Linux pods.

**How to reproduce it (as minimally and precisely as possible)**:

Run the following commands:

    kubectl create -f pods/portforward.yaml  # https://paste.ubuntu.com/p/P8JQt7T8qk/
    kubectl port-forward -n services-4435 pod/nodeport-test-6t4rs 9999:80 &
    curl http://127.0.0.1:9999

The same scenario works when using Linux pods.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master (v1.16.0)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows Server Datacenter 10.0.17763.379
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): azure-vnet-cni, flannel
- Others:

**Comment by pswica** [comment]
The command actually tells you:

`Forward one or more local ports to a pod. This command requires the node to have 'socat' installed`

I would label this as:

/kind feature
/remove-kind bug

**Comment by zhiweiv** [comment]
There is a PR Implement port forwarding for windows https://github.com/kubernetes/kubernetes/pull/75479.

**Comment by yujuhong** [comment]
The PR has already been merged, pending moving the pause image to a repo owned by sig-windows (and maybe push an official pause image with this feature?)
/assign @benmoss

**Comment by benmoss** [comment]
https://asciinema.org/a/94FUya91IyRLnrhCrUBZo3zMk

it looks from the error like you're not actually running a kubelet with the changes in my PR. it would error with not finding `wincat`, not `socat`.

**Comment by bclau** [comment]
So, for the most part, port-forwarding tests work on windows now, with some interesting errors. The tests which are still failing:

    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on 0.0.0.0 [k8s.io] that expects a client request should support a client that connects, sends DATA, and disconnects
    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects
    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects a client request should support a client that connects, sends DATA, and disconnects
    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on 0.0.0.0 [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects

Half of them error out because the read data does not match the expectation. It expects to read something like ``xxxxxxxxxx``, but gets ``""`` instead. Looking through the pod logs, this can be seen:

    Accepted client connection
    Expected to write 10 bytes from client, but wrote 0 instead. err=write tcp [::1]:80->[::1]:49189: wsasend: An established connection was aborted by the software in your host machine.

Looking through kubelet and kube-proxy logs, there didn't seem to be any relevant information about this.

Basically, what the tests does, is this:

    kubectl create namespace ns1
    kubectl create -f port_fw1.yaml  # [1]
    kubectl port-forward -n ns1 pod/pfpod 9991:80 &
    echo "abc" | nc 127.0.0.1 9991
    kubectl logs -n ns1 pf/pod -c portforwardtester

The other half of the tests hang indefinetely. Basically, the connection never closes. What the tests do is this:

    kubectl create namespace ns2
    kubectl create -f port_fw2.yaml  # [1]
    kubectl port-forward -n ns2 pod/pfpod 9992:80 &
    nc 127.0.0.1 9992  # this will output a number of x characters, and will hang.
    kubectl logs -n ns2 pf/pod -c portforwardtester

Looking through the logs, the server lingers (making sure that all the data has been sent) before it closes the socket. I've added timestamps to the server's output:

    Accepted client connection
    Shutting down connection at 2019-07-15 17:12:38.7661425 +0000 GMT m=+516.300379001. Lingering...
    After Lingering... 2019-07-15 17:12:39.4661261 +0000 GMT m=+517.000363301
    Done at 2019-07-15 17:12:39.9686087 +0000 GMT m=+517.502868501

Any ideas about this?

[1] https://paste.ubuntu.com/p/DMYhZdvBK4/
[2] https://paste.ubuntu.com/p/bW4mpYKV8W/

**Comment by PatrickLang** [comment]
this bug could be in https://github.com/kubernetes-sigs/sig-windows-tools/tree/master/cmd/wincat

**Comment by PatrickLang** [comment]
@benmoss - are you looking at this? if not @kkmsft may be able to take it

**Comment by benmoss** [comment]
I'll take a look today, just got back from vacation

**Comment by benmoss** [comment]
@bclau my recollection is that it's related to https://github.com/golang/go/issues/28477#issuecomment-454530397.

**Comment by benmoss** [comment]
I tried using Go 1.13beta1 to rebuild agnhost, but it still is not working. It appears to get stuck on https://github.com/kubernetes/kubernetes/blob/e0ff9634d5b5a480595930236c87dec1327dbf13/test/e2e/kubectl/portforward.go#L231 and using tcpdump/wireshark I'm seeing that the Windows server never sends a `FIN` packet to close the connection. I'm not sure why, probably some fiddliness related to https://github.com/kubernetes/kubernetes/blob/e0ff9634d5b5a480595930236c87dec1327dbf13/test/images/agnhost/port-forward-tester/portforwardtester.go#L154-L160

**Comment by benmoss** [comment]
Further investigation seems to have discredited that idea, I think the problem might be in wincat. Will keep my murmurings to myself until I figure out a solution or give up :)
