### ISSUE TITLE
Unclear error when GCE PD disk attached as READ_ONLY and attempting to MountDevice !readOnly

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#78880]
When an unformatted disk is attached as `readOnly` through `PersistentVolume.spec.GCEPersistentVolumeSource.readOnly` if we then try to mount !readOnly with `Pod.spec.volumes.persistentVolumeClaim.readOnly=false`  we get the error:
```
MountVolume.MountDevice failed for volume "podpv" : exit status 1
```

We should return more error information than just "exit status 1"

/kind cleanup
/sig storage
/priority important-longterm
/cc @msau42 
xref: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/296

**Comment by msau42** [comment]
/close
this is fixed in the csi driver
