### ISSUE TITLE
Build container version error

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#78897]
/kind bug
/sig release

**What happened**:
I want to build a docker version of kubernetes, just do make quick-release?
When I do make quick-release, something goes wrong, can someone help me see what's going on?
make quick-release
+++ [0611 17:02:27] Verifying Prerequisites....
+++ [0611 17:02:27] Building Docker image kube-build:build-e597cac0f2-5-v1.12.1-2
+++ [0611 17:04:32] Creating data container kube-build-data-e597cac0f2-5-v1.12.1-2
+++ [0611 17:05:58] Syncing sources to container
!!! [0611 17:06:01] Could not get effective rsync port
!!! [0611 17:06:01] Call tree:
!!! [0611 17:06:01]  1: build/../build/common.sh:436 kube::build::sync_to_container(...)
!!! [0611 17:06:01]  2: build/release.sh:35 kube::build::build_image(...)
make: *** [Makefile:430: quick-release] Error 1

**What you expected to happen**:
i want to build container version k8s

**Environment**:
- OS (e.g: `cat /etc/os-release`):ubuntu 16.04.5
- Kernel (e.g. `uname -a`): 4.4.0-131
- Install tools:go 1.12.5

**Comment by timyinshi** [comment]
I found that the method kube::build::run_build_command_ex was not executed. Does anyone know why it could not be executed?
build/common.sh line 628
  kube::build::run_build_command_ex \
    "${KUBE_RSYNC_CONTAINER_NAME}" -p 127.0.0.1:"${KUBE_RSYNC_PORT}":"${KUBE_CONTAINER_RSYNC_PORT}" -d \
    -e ALLOW_HOST="$(${IPTOOL} | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')" \
    -- /rsyncd.sh >/dev/null

**Comment by timyinshi** [comment]
Hello, I'm building kubernetes using the make quick-release command to report an error, what's the reason?

+++ [0612 15:08:56] docker command:docker
    run
    --name=kube-rsync-e597cac0f2-5-v1.12.1-2
    --user=0:0
    --hostname=inserver-inspurclouddev-392-10
    --volumes-from
    kube-build-data-e597cac0f2-5-v1.12.1-2
    -p 8730:8730
    -d
    -e ALLOW_HOST=10.221.128.98
172.17.0.1
    --env
    KUBE_FASTBUILD=true
    --env
    KUBE_BUILDER_OS=linux-gnu
    --env
    KUBE_VERBOSE=8
    --env
    KUBE_BUILD_WITH_COVERAGE=
    --env
    GOFLAGS=
    --env
    GOLDFLAGS=
    --env
    GOGCFLAGS=
    --env
    SOURCE_DATE_EPOCH=
    --interactive
    --tty
    kube-build:build-e597cac0f2-5-v1.12.1-2
    /rsyncd.sh
docker: Invalid hostPort:  8730.
See 'docker run --help'.

Does anyone know why?

**Comment by justaugustus** [comment]
Is this still an issue?

/area release-eng
/priority important-soon
/milestone v1.16

**Comment by xmudrii** [comment]
@timyinshi Hello! I'm bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by RainbowMango** [comment]
If the issue still exists please @timyinshi feel free to re-open it.
/remove-help
/close

**Comment by RainbowMango** [comment]
Remove milestone to reduce unnecessary focus.
/milestone clear

**Comment by justaugustus** [comment]
Feel free to reopen this, if it's still an issue.
/close
