### ISSUE TITLE
Add HTTP headers to ACR

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#78893]
**What would you like to be added**:

Add HTTP header `X-Meta-Source-Client: azure/kubelet` to ACR credential provider.

**Why is this needed**:

Refer https://github.com/Azure/acr/blob/master/docs/http-headers.md. The HTTP headers could help to identify the source client of ACR requests.

/sig azure
/kind feature
/milestone v1.16

**Comment by xmudrii** [comment]
@feiskyer @justaugustus Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by feiskyer** [comment]
This would require a refactor of Azure clients implementation. Given code freezing is near, we're not able to get this done in v1.16.

/milestone v1.17

**Comment by smourapina** [comment]
@feiskyer @justaugustus Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 18. Is this issue still intended for 1.17?

**Comment by feiskyer** [comment]
@smourapina yep

**Comment by smourapina** [comment]
Friendly reminder that code freeze is rapidly approaching and will take place in November 14th. Is this issue still on track for 1.17? Otherwise we will need to move it to 1.18 milestone.

**Comment by feiskyer** [comment]
@smourapina yep, #84700 is working on this.

**Comment by feiskyer** [comment]
After digging into docker SDK, the http header customization is not supported: both authConfig and ImagePullOptions don't support customize http header refer https://github.com/kubernetes/kubernetes/blob/71a7be41e0518a7df549eb1fa7b51e7c647d985b/pkg/kubelet/dockershim/docker_image.go#L106-L109.

**Comment by cpuguy83** [comment]
HTTP headers are configured when creating the client.
You can set them afterwards but this is deprecated.

Here's the deprecated method: https://github.com/moby/moby/blob/3af8d484b132a492bd6f159e454560b7d7691fa9/client/client.go#L293-L297

The updated one is an function option passed when creating the client: https://github.com/moby/moby/blob/28d7dba41d0c0d9c7f0dafcc79d3c59f2b3f5dc3/client/options.go#L114-L120
