### ISSUE TITLE
Kubectl cp command over writes the running process executable without warning

### ISSUE THREAD

**Issue by VinodKumarGoku** [kubernetes/kubernetes#78892]
**What happened**: While performing kubectl cp of an executable from host to a container in pod. It copied successfully and modified all the permission of the existing file. The running process crashed.

**What you expected to happen**: kubectl cp should not perform direct copy of running executable files in usage from some other process. Instead it should report error for the same.

**How to reproduce it (as minimally and precisely as possible)**: 
1. Run an instance of a program i.e run a process in a container in a kubernetes pod. While the proocess is still running. Perform a kubectl cp of the executable from the host to the conatiner.
2. Check whether the process is still running.

**Anything else we need to know?**: usually cp command reports error when a copy is performed on a running executable file. It prevents direct copy.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): rhel 7.2
- Kernel (e.g. `uname -a`): Linux 5.0.2-1.el7.elrepo.x86_64
- Install tools: kubernetes cluster 
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by liggitt** [comment]
kubectl cp uses tar under the covers. I would be surprised if tar detected/handled that scenario the way you are requesting

**Comment by liggitt** [comment]
if the filesystem allows writing a file, cp should allow it as well. this is working as intended

/close
