### ISSUE TITLE
Applying DaemonSet configurations with `change-cause` annotations results in blank `CHANGE-CAUSE` descriptions reflected in rollout history

### ISSUE THREAD

**Issue by leeren** [kubernetes/kubernetes#78890]
**What happened**:
Manually adding `spec.template.metadata.annotations.kubernetes.io/change-cause` to a `kind:DaemonSet` manifest and subsequently applying the configuration changes failed to show the `CHANGE-CAUSE` description in the DaemonSet's rollout history.

Relevant contents of the `DaemonSet` configuration (**test.yaml**):

    …
    metadata:
      name: test
    spec:
      template:
        annotations:
          kubernetes.io/change-cause: "TEST"
    …

Despite applying the above `DaemonSet` configuration with a clearly-defined `kuberenetes.io/change-cause` annotation, the rollout history shows an empty `CHANGE-CAUSE` description for the new revision:

    $ kubectl apply -f test.yaml
    daemonset.apps/test configured

    $ kubectl rollout history daemonset/test
    REVISION  CHANGE-CAUSE
    1         <none>

**What you expected to happen**:
The expectation is that the configuration application successfully results in the `CHANGE-CAUSE` description being updated when running `kubectl rollout history`:

    $ kubectl apply -f test.yaml
    daemonset.apps/test configured

    $ kubectl rollout history daemonset/test
    REVISION  CHANGE-CAUSE
    1         TEST

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a minimal `kind:DaemonSet` manifest `test.yaml`
2. Make sure the following sections are added:
     - `spec.template.annotations` with`kubernetes.io/change-cause: "TEST"`
     - `metadata.name` with `test`.
3. Apply the configuration change via `kubectl apply -f test.yaml`
4. Check the `CHANGE-CAUSE` description by running `kubectl rollout history daemonset/test`

**Anything else we need to know?**:
When running the same above steps on manifests of `type:deployment`, the correct `CHANGE-CAUSE` description is output. This seems to be an issue specific to `DaemonSet` configurations, although other manifest types were not tested.

**Environment**:
- Kubernetes version (use `kubectl version`):

      Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:09:56Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
      Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: `GKE`
- OS (e.g: `cat /etc/os-release`): `Debian GNU/Linux`
- Kernel (e.g. `uname -a`): `4.19.20-1rodete1-amd64 #1 SMP Debian 4.19.20-1rodete1`

**Comment by rpeng** [comment]
We're running into this bug too, is it possible to get this prioritized?
