### ISSUE TITLE
[Flaky Tests] Flaky reboot tests

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#78901]
**Which jobs are failing**:
* ci-kubernetes-e2e-gci-gce-reboot
* ci-kubernetes-e2e-gce-cos-k8sbeta-reboot 

**Which test(s) are failing**:
There are multiple reboot tests failing, such as:
* [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on 
* [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards 
* [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart 
* [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering clean reboot and ensure they function upon restart 
* [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards 

**Since when has it been failing**:
These tests have been flaking for a while:
[triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-reboot&test=reboot).
There is a history of issues referencing them: https://github.com/kubernetes/kubernetes/issues/74661 , https://github.com/kubernetes/kubernetes/issues/14772 , https://github.com/kubernetes/kubernetes/issues/9062 , etc.

**Testgrid link**:
* https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-reboot
* https://testgrid.k8s.io/sig-release-1.15-blocking#gce-cos-k8sbeta-reboot

**Reason for failure**:
The common error message between all of the failures looks like this:
```
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on expand_less	7m24s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:111
Jun 11 10:29:36.739: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:169

[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards expand_less	5m13s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:125
Jun 11 10:34:47.931: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:169
 
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart expand_less	5m11s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:99
Jun 11 10:40:00.572: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:169
 
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering clean reboot and ensure they function upon restart expand_less	5m11s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:93
Jun 11 10:45:11.861: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:169
 
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards expand_less	5m12s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:117
Jun 11 10:50:22.772: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:169
```

/cc @kubernetes/sig-cluster-lifecycle 
/sig cluster-lifecycle
/kind flake
/priority important-soon
/milestone v1.15

/cc @jimangel @smourapina  @alenkacz

**Comment by neolit123** [comment]
/assign @justinsb 
Justin, PTAL if you can or delegate to someone with knowledge of the gce-cos* jobs.
thanks.

**Comment by scottilee** [comment]
Hey @justinsb I know you're super busy but any update on this? Or can this be delegated to someone else?

**Comment by scottilee** [comment]
@justinsb have you been able to take a look at this?

**Comment by alejandrox1** [comment]
This one is relevant to keep around just as a "it has always been happening" but the priority with these tests is very low. 
/lifecycle frozen

**Comment by soggiest** [comment]
@justinsb Have you had a chance to look at this?

**Comment by alejandrox1** [comment]
I want to take a look at these tests :eyes: 
/assign

**Comment by alenkacz** [comment]
/close

these jobs look green now
