### ISSUE TITLE
[Failing Test] DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver in master-blocking

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#78919]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-network] DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]

**Since when has it been failing**:
Failing since 6/10 at 16:58.
[k/k diff](https://github.com/kubernetes/kubernetes/compare/3a50c0069...d873167e8).
Decent chance that the failure is due to https://github.com/kubernetes/kubernetes/pull/78691

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_configmap.go:506
Jun 11 05:58:40.949: dig result did not match: []string{} after 2m0s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:103
```

/cc @kubernetes/sig-network-test-failures 
/priority critical-urgent
/kind failing-test
/milestone v1.15

/cc @jimangel @smourapina @alenkacz

**Comment by alejandrox1** [comment]
This is blocking the release 
/cc @claurence

**Comment by jimangel** [comment]
I noticed in the https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1138444096910659586/build-log.txt it thinks it's testing 1.16 alpha:

```
```

**Comment by rajansandeep** [comment]
https://github.com/kubernetes/kubernetes/pull/78920 should fix it.
Sorry for the mess-up!
