### ISSUE TITLE
kubelet.exe on Windows leaks process handles

### ISSUE THREAD

**Issue by mbergal** [kubernetes/kubernetes#78917]
/sig windows

Kubernetes version 1.14.3

Running  just one pod, the number of open process handles increases and reaches 17090 over few hours

![image](https://user-images.githubusercontent.com/167835/59300685-6a988500-8c55-11e9-9aaf-3b45d479d1f2.png)

**Comment by yujuhong** [comment]
You may have run into this issue: https://github.com/kubernetes/kubernetes/issues/78555
The PR to cherrypick the fix to 1.14 hasn't been merged yet. https://github.com/kubernetes/kubernetes/pull/78665

**Comment by mbergal** [comment]
Seems like it is in v1.15.0-rc.1, I will try that I think
