### ISSUE TITLE
ping my nameserver 10.96.0.10 fail

### ISSUE THREAD

**Issue by JK-97** [kubernetes/kubernetes#78926]
i use to this command deploy my k8s.
` kubeadm init --pod-network-cidr=10.244.0.0/16`
and i want to deploy kubeflow on k8s.
but my problem is : pod   in kubeflow namespeaces can not DNS，but can ping succes public network ip.
i use this comand to see the dns server:
`cat /etc/resolv.conf `
**nameserver 10.96.0.10
search kubeflow.svc.cluster.local svc.cluster.local cluster.local
options ndots:5**

but at mster nodes ,i ping 10.96.0.10 fail
i guess is the 10.96.0.10 DNS server down

**Comment by hainesc** [comment]
As 10.96.0.10 is a Cluster IP, It is not ping-able. You can use `telnet` or `curl`.

**Comment by aojea** [comment]
> As 10.96.0.10 is a Cluster IP, It is not ping-able. You can use `telnet` or `curl`.

/close

it was already answered
