### ISSUE TITLE
kuberenetes-pods

### ISSUE THREAD

**Issue by JainaHarshaVardan** [kubernetes/kubernetes#78927]
Hi all I create a Deployment file   Then applied file by using command "kubectl apply -f abc.yml" 
after deployed that one deployment  and one pod files are created.
when I'm trying to delete deployment file  deployment as well as pod files are deleted previously ...

but when I'm trying to delete deployment . deployment file only deleting.pod is not deleting..
if I'm trying to delete pod explicitly pod is recreating how can i overcome this problem..

**Comment by mysunshine92** [comment]
kubectl delete deploy <deployment-name> -n <namespace>
use above command, you can delete deploy.
