### ISSUE TITLE
How do I limit the number of pids that a single pod can start

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#78930]
/kind bug
/sig node
/sig apps

**What happened**:
I found a problem: a pod for the database postgres, because the daemon kept pulling up the service, took up a lot of pids until it ate up the pids on the node where the pod was, making the node unavailable
I wonder if there is any way to limit the number of pids that a single pod can start, and what needs to be done?

**What you expected to happen**:
I wonder if there is any way to limit the number of pids that a single pod can start, and what needs to be done?

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.1
- OS (e.g: `cat /etc/os-release`):ubuntu16.04.5
- Kernel (e.g. `uname -a`):4.4.0-116-generic

**Comment by Pingan2017** [comment]
start kubelet with `--pod-max-pids`

`      --pod-max-pids int                                                                                          Set the maximum number of processes per pod.  If -1, the kubelet defaults to the node allocatable pid capacity. (default -1) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)`

**Comment by timyinshi** [comment]
@Pingan2017 thanks.
another problem,what is the value of pod-max-pids,How much do I need to set?

**Comment by mattjmcnaughton** [comment]
You probably already saw this blog post (it was posted on slack), but linking here in case anyone looks at this issue in the future :) 

https://kubernetes.io/blog/2019/04/15/process-id-limiting-for-stability-improvements-in-kubernetes-1.14/

**Comment by timyinshi** [comment]
@mattjmcnaughton thanks,I would like to know what value of pod-max-pids needs to be appropriate?
