### ISSUE TITLE
Update top-level reviewers/approvers for k/k

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#78935]
@mborsz (SIG Scalability) started a [thread](https://groups.google.com/d/topic/kubernetes-sig-scale/6V60w-ABYCw/discussion) to inquire if we had a mechanism for revert-only approvers, which as far as I know isn't something that exists today.

I haven't seen policy on graduating into the top-level OWNERS file, but as stated in the SIG Scalability charter and mentioned by @mm4tt:
> We can rollback any merged PR if it has been identified as a cause of any performance/scalability SLOs regression (identified by the set of release blocking scalability/performance tests). The offending PR should only be merged again after proving to pass tests at scale.

So they should have this power.

Suggestion:
- Add to `OWNERS_ALIASES`:
  - `revert-approvers`
  - `sig-scalability-approvers`
  - `sig-scalability-reviewers`
- Add aforementioned groups to top-level reviewers and approvers stanzas

Additionally, I think we should also use the opportunity to [prune/update the current top-level reviewers/approvers](https://groups.google.com/d/topic/kubernetes-dev/B7fsNnR3Rxw/discussion).

I'm assigning the current top-level approvers to this for advice on policy, nominations for new reviewers/approvers, and suggestions on who to remove.

/assign @bgrant0607 @brendandburns @dchen1107 @jbeda @monopole @lavalamp @smarterclayton @thockin @wojtek-t @liggitt 
/cc @kubernetes/owners 

(As he expressed interest in assisting with reverts):
/cc @dims 

/sig architecture release
/committee steering
/kind cleanup
/milestone v1.16
/priority important-soon

**Comment by justaugustus** [comment]
Happy to coordinate making the OWNERS update, btw.

**Comment by smarterclayton** [comment]
Is there some documentation about getting approval for these reverts being difficult?

Has ContribEx considered handling this with a revert bot that would respect a different group?

**Comment by liggitt** [comment]
a revert bot solution sounds ideal

**Comment by smarterclayton** [comment]
I would expect it to be more generally useful / efficient to let any approver or reviewer of a PR ask a bot to create a pre-approved revert PR within a window.  That scales much better than human approvals anyway.

**Comment by thockin** [comment]
A bot sounds good to me - I don't know how we would enforce human "revert
only" permissions, since reverts aren't really reverts.  Maybe there's
git-fu I don't know here...

**Comment by dims** [comment]
So, i'd like to help with a few things:
- help with code organization related PRs that need top level approval 
- as part of dep-approvers, i can't really help with go.mod/go.sum changes currently as those files are in the root directory
- as i am on the east coast, i can help with reverts as well if needed.

thanks,
dims

**Comment by thockin** [comment]
I have no objections, but I am not sure how to express the bounds of this stuff in general.  There's certainly a lot of code organization, CHANGELOG, etc PRs that I'd be happy to not get.

**Comment by wojtek-t** [comment]
I just responded to the original email-thread. As i mentioned there, I think there are couple other things (some of them are great suggestions by others) that we may try first. Maybe those will be enough and we would be able to avoid both adding new approvers and having the revert bot.

**Comment by justaugustus** [comment]
Where did we land with this?

**Comment by wojtek-t** [comment]
We discussed this during the last SIG Arch and we decided that for now we can close it - we did couple mitigations on our side (moving jobs around etc.). We will reopen if it appears to be not enough (but I think it should be enough).
