### ISSUE TITLE
Delayed call to add network interface to the container

### ISSUE THREAD

**Issue by ashvindeodhar** [kubernetes/kubernetes#78947]
**What happened**:
In windows, when I create multiple pods simultaneously I see CNI ADD call to the workload container gets delayed. ( by as much as 2 mins with 10 simultaneous pod creation ).
Debugging this indicates that there is something in the kubelet waiting to set up stats before making the call to add network interface to the container.

**What you expected to happen**:
Don't expect this delay. 

**How to reproduce it (as minimally and precisely as possible)**:
Create multiple pods simultaneously. Enable logging in kubelet log. I set the logging level to --v=6. Verify the delay thru the kubelet log.
e.g. Following log lines from kubelet indicate the delay of ~2mins between the workload container getting created and it making the add call for network interface. This can be correlated further with the logs in Azure CNI ( azure-vnet.log )

Line 839:   I0611 23:23:57.612758    1980 fake_cpu_manager.go:40] [fake cpumanager] AddContainer (pod: test-dns, container: querier, container id: a4ad3177c68fe6b9daa9e116d44ef0680534163e17fa17aafd1e6eaafa0a0a86)  workload container
Line 1009: I0611 23:24:13.054237    1980 cri_stats_provider.go:206] Unable to find cadvisor stats for "a4ad3177c68fe6b9daa9e116d44ef0680534163e17fa17aafd1e6eaafa0a0a86"
Line 1214: I0611 23:24:53.873349    1980 cri_stats_provider.go:206] Unable to find cadvisor stats for "a4ad3177c68fe6b9daa9e116d44ef0680534163e17fa17aafd1e6eaafa0a0a86"
Line 1588: I0611 23:25:45.480688    1980 cri_stats_provider.go:206] Unable to find cadvisor stats for "a4ad3177c68fe6b9daa9e116d44ef0680534163e17fa17aafd1e6eaafa0a0a86"
Line 1726: I0611 23:25:50.330987    1980 generic.go:153] GenericPLEG: e6856f36-8c9f-11e9-8311-000d3a5e43d7/a4ad3177c68fe6b9daa9e116d44ef0680534163e17fa17aafd1e6eaafa0a0a86: non-existent -> running
Line 1730: I0611 23:25:50.337050    1980 cni.go:328] Adding test-ns4_test-dns/a4ad3177c68fe6b9daa9e116d44ef0680534163e17fa17aafd1e6eaafa0a0a86 to network azure-vnet/azure netns "container:de2e3c6badb829a5ee8252d3a223232163aa977c12516afb8b1e8c1aa527b6ac"

**Anything else we need to know?**:
This delay is dependent on the number of pods created simultaneously.
For 4 pods the worst case delay I see ~11-15 sec. For 10 pods, it's ~2mins.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Azure

- OS (e.g: `cat /etc/os-release`):
Windows

- Kernel (e.g. `uname -a`):
- Install tools:

- Network plugin and version (if this is a network-related bug):
Azure CNI v1.0.22

- Others:

**Comment by rhockenbury** [comment]
Related - https://github.com/kubernetes/kubernetes/issues/78479
