### ISSUE TITLE
Option to specify source NAT address for VIP traffic

### ISSUE THREAD

**Issue by maxstr** [kubernetes/kubernetes#78949]
**What would you like to be added**:
Right now, depending on the service type, kube-proxy will usually mark traffic to service VIPs to hit an iptables `MASQUERADE` rule for source NAT. I would like to be able to configure kube-proxy to use an iptables `SNAT` rule instead with a specified address. 

**Why is this needed**:
Similar to https://github.com/kubernetes/kubernetes/issues/78948, the use of `MASQUERADE` can cause issues because it overrides the use of route source hints. These route source hints are important on hosts with multiple addresses on an interface and in some host ECMP setups.

As with #78948 I can probably submit a PR for this if there's openness to the feature.

**Comment by maxstr** [comment]
I'll note our setup is similar to what was described in this issue: https://github.com/kubernetes/kubernetes/pull/75893

**Comment by rikatz** [comment]
@maxstr not sure how is this going, do you want to propose a PR for this? Maybe bring to sig network meeting? 

Thank you :)

**Comment by dylex** [comment]
I think I'm seeing an issue related to this where MASQUERADE is doing the wrong thing in a fairly simple setup with multiple networks:
https://discuss.kubernetes.io/t/multi-network-cluster-broken-without-masquerade-all/13671
`--masquerade-all` fixes it but I'm not sure that's the right fix.

**Comment by liruishan** [comment]
@maxstr ,I have found the real cause of this problem. If it is a local route, there will be errors in masquerade processing. It will select the first address from the address list as the source address. For example:

**There are three IP addresses on my host, which are:**
ens32 5.5.5.5
ens33 4.4.4.4
ens34 3.3.3.3
**If a route is a local route, like this:**
local  3.3.3.3  dev  lo   src  3.3.3.3
After masquerade, the source address of the packet sent to 3.3.3.3 will be replaced by 5.5.5.5

I look up  the source code of Linux kernel, masquerade is implemented in this way. I think masquerade is unreliable in this case, especially when we manually configure iptables rules, I think that kube-proxy should replace masquerade with SNAT.

PTAL,tks
