### ISSUE TITLE
e2e test setup fails on Ubuntu

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#78940]
**What happened**:
[A prow job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-storage/sig-storage-gce-config.yaml#L148) that uses Ubuntu image fails during Kubernetes installation:

```
W0610 03:04:45.124] 2019/06/10 03:04:45 process.go:155: Step '/workspace/get-kube.sh' finished in 14.697998994s
W0610 03:04:45.124] 2019/06/10 03:04:45 process.go:153: Running: ./hack/e2e-internal/e2e-down.sh
W0610 03:04:45.168] ./hack/e2e-internal/../../cluster/../cluster/gce/util.sh: line 29: /go/src/k8s.io/kubernetes/kubernetes/cluster/gce/ubuntu/node-helper.sh: No such file or directory
```

Full log: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/68108/pull-kubernetes-e2e-gce-iscsi/1137914995519000579/

Indeed, `cluster/gce/ubuntu/node-helper.sh` is not present on nodes. Only `gci` and `windows` subdirectories are present in `cluster/gce`. **I don't know what code removed (or did not package) `cluster/gce/custom` and `cluster/gce/ubuntu` symlinks, but they should be there.**

**What you expected to happen**:
Kubernetes is installed correctly and e2e tests start.

**How to reproduce it (as minimally and precisely as possible)**:
Run `/test pull-kubernetes-e2e-gce-iscsi` in a PR.

**Anything else we need to know?**:

* Prow job: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-storage/sig-storage-gce-config.yaml#L148. It seems to be the only one that uses Ubuntu image.

* This command works and installs Kubernetes correctly:
    ```
    KUBE_GCE_NODE_IMAGE=ubuntu-gke-1804-bionic-20180921 
    KUBE_GCE_NODE_PROJECT=ubuntu-os-gke-cloud KUBE_NODE_OS_DISTRIBUTION=ubuntu  
    cluster/kube-up.sh
    ```
    `cluster/gce/ubuntu/node-helper.sh` is present there. Dunno what the prow job does differently.

**Comment by jsafrane** [comment]
@kubernetes/sig-testing

**Comment by BenTheElder** [comment]
the nodes receive files staged via the release scripts and downloaded by the cluster/ scripts, I don't think sig testing will be the right group to fix this.

SIG node has some owners related to the various images that might have some idea how this is setup

**Comment by BenTheElder** [comment]
/sig release
this is _probably_ an issue in the release scripts

**Comment by justaugustus** [comment]
cc: @kubernetes/release-managers @kubernetes/release-engineering

**Comment by jsafrane** [comment]
@kubernetes/release-engineering PTAL, it looks like a stupid bug somewhere.

**Comment by cblecker** [comment]
Q: Did this *ever* run successfully?

**Comment by jsafrane** [comment]
> Q: Did this ever run successfully?

Most probably not, I haven't found a working e2e tests on Ubuntu. Still, `cluster/kube-up.sh` works well, there must be something slightly different in test setup scripts.

**Comment by jsafrane** [comment]
@kubernetes/release-engineering ping again?

Short recap:

* This works:
    ```
    KUBE_GCE_NODE_IMAGE=ubuntu-gke-1804-bionic-20180921 
    KUBE_GCE_NODE_PROJECT=ubuntu-os-gke-cloud KUBE_NODE_OS_DISTRIBUTION=ubuntu  
    cluster/kube-up.sh
    ```
    `cluster/gce/ubuntu/node-helper.sh` is there. (`cluster/gce/ubuntu` is symlink to `cluster/gce/gci`)

* This does not work:
    https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-storage/sig-storage-gce-config.yaml#L107

    Fails with: `./hack/e2e-internal/../../cluster/../cluster/gce/util.sh: line 29: /go/src/k8s.io/kubernetes/kubernetes/cluster/gce/ubuntu/node-helper.sh: No such file or directory`
    
    `cluster/gce/ubuntu` does not exist. The prow job must do something slightly different than kube-up.sh.

**Comment by cblecker** [comment]
@jsafrane The serial job is using GCI (COS): https://github.com/kubernetes/test-infra/blob/59cf84e0f73487cd0c9d2c83df2eaac6b85a2eb7/config/jobs/kubernetes/sig-storage/sig-storage-gce-config.yaml#L141

Is the non-serial job working? It uses ubuntu: https://github.com/kubernetes/test-infra/blob/59cf84e0f73487cd0c9d2c83df2eaac6b85a2eb7/config/jobs/kubernetes/sig-storage/sig-storage-gce-config.yaml#L179

If not, my guess from the last time I remember looking was checking the release bundle and ensuring it includes the ubuntu dir

**Comment by jsafrane** [comment]
> Is the non-serial job working?

No, same error.

> If not, my guess from the last time I remember looking was checking the release bundle and ensuring it includes the ubuntu dir

kubernetes.tar.gz created by `make quickrelease` contains `ubuntu``, released bundles (e.g. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#downloads-for-v1151) contains it too.  Otherwise `cluster/kube-up.sh` would not work with an Ubuntu image. 

So what does the prow job differently? Does something there prune the scripts? `ubuntu` is just a symlink to `gce`, does it make a difference?

**Comment by jsafrane** [comment]
Found it, `make bazel-release` creates kubernetes.tar.gz without any symlinks. It looks like bazel limitation. I filled #80461 to explicitly create the symlinks when tarball is created.

BTW, if `make bazel-release` and `make release` use different way to produce tarballs, who / when tests the ones created by `make release`?

**Comment by BenTheElder** [comment]
Most of CI is using make release or equivalent. Presumbit uses bazel.
