### ISSUE TITLE
Option to use ctmark instead of nfmark for marking/matching kube-proxy traffic

### ISSUE THREAD

**Issue by maxstr** [kubernetes/kubernetes#78948]
**What would you like to be added**:
Right now kube-proxy marks and matches traffic bound for service VIPs with nfmark (`iptables MARK`) rules. I would like to be able to mark and match VIP traffic using ctmark(`iptables CONNMARK`) rules instead.

**Why is this needed**:
One issue with using nfmarks is that they persist through packet encapsulation for tunnel devices. This means that for traffic to a VIP over a tunnel device (eg vxlan or ip in ip) both the encapsulated _and_ encapsulating packet will be marked for `MASQUERADE`. This `MASQUERADE` is an incorrect behavior on the outer packet, but is usually benign; the correct behavior would be for the encapsulating traffic to just use the route on the host with whatever source is set on that route. The  issue is that MASQUERADE overrides the use of route source hints which are used in some host ECMP setups or hosts where multiple addresses are assigned on a single interface.

If this is something there'd be openness to I can probably put together a PR for it.

**Comment by dcbw** [comment]
@maxstr are there downsides to connmark? eg is it possible to just switch to using connmark rather than nfmark?

**Comment by danwinship** [comment]
If we're switching to ct-based marking, we should use `connlabel`, not `connmark`; it's designed for having different people use different bits of, as opposed to `connmark`/`mark`, where in theory you're supposed to be using all the bits together to represent a single piece of data.

**Comment by maxstr** [comment]
Based on what I know I think either connmark or connlabel would be sensible defaults; I'm not aware of any downsides of using them over nfmark except for other users possibly already being reliant upon nfmarks for other purposes.

**Comment by danwinship** [comment]
The theoretical downside is that the mark/label would automatically be associated with all packets in the connection, not just the one that you marked. So if you were marking to indicate something specific to a single packet in a larger connection, then you couldn't switch from nfmark to ctmark. But that shouldn't be a problem for what kube-proxy is using marks for.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc

**Comment by dcbw** [comment]
Decision from SIG Network Call: @maxstr will do a PR for this and if it passes E2E testing it's probalby OK

**Comment by maxstr** [comment]
/remove-lifecycle stale

Still want to PR this, just looking to iron a few things out on my end
