### ISSUE TITLE
hack/local-up-cluster fails to bring up kubelet and a node

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#78950]
**What happened**:

kubelet terminated unexpectedly during hack/local-up-cluster
```
$ sudo PATH=$PATH hack/local-up-cluster.sh
...
Alternatively, you can write to the default kubeconfig:

  export KUBERNETES_PROVIDER=local

  cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/server-ca.crt
  cluster/kubectl.sh config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt
  cluster/kubectl.sh config set-context local --cluster=local --user=myself
  cluster/kubectl.sh config use-context local
  cluster/kubectl.sh
W0612 13:13:27]: kubelet terminated unexpectedly, see /tmp/kubelet.log
```
kubelet log
```
I0612 13:13:26.603449  174709 plugins.go:103] No cloud provider specified.
I0612 13:13:26.603467  174709 server.go:540] No cloud provider specified: "" from the config file: ""
F0612 13:13:26.605288  174709 server.go:272] failed to run Kubelet: failed to get the kubelet's cgroup: cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-484802.slice/session-c2.scope
```
as a result apiserver cannot find the node to schedule pods
```
$ kubectl get nodes
No resources found.
$ kubectl get po foo -oyaml
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-06-12T20:22:18Z"
    message: no nodes available to schedule pods
    reason: Unschedulable
    status: "False"
    type: PodScheduled
```
**What you expected to happen**:

kubelet runs successfully and hack/local-up-cluster creates a single node cluster

**How to reproduce it (as minimally and precisely as possible)**:

run hack/local-up-cluster from HEAD

**Anything else we need to know?**:

1. the additional cgroups check seemed to be introduced in https://github.com/kubernetes/kubernetes/commit/f8dff6bd5b700d624b802b747160576473c558d7; hack/local-up-cluster works when I check out the parent commit https://github.com/kubernetes/kubernetes/commit/21bec91e895a828ee8ed8d45a7d58279b8cae46f
```
$ kubectl get nodes
NAME        STATUS   ROLES    AGE    VERSION
127.0.0.1   Ready    <none>   2m3s   v1.15.0-alpha.3.179+21bec91e895a82-dirty
```

2. we have CI for hack/local-up-cluster and [it's green](https://k8s-testgrid.appspot.com/sig-testing-misc#ci-kubernetes-local-e2e), so I'm not sure if it's an error on my side. It would be greatly appreciated if someone could explain it to me

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node
cc @dashpole

**Comment by mattjmcnaughton** [comment]
Thanks for raising such a detailed issue!

cc @dashpole any thoughts here?

Confusingly, I think the kubelet has been assigned a different cgroup for memory and for cpu... however the fact that its using `user.slice` makes me think the user is relying on system defaults.

@roycaihw out of curiosity, have you made any mods to how your system assigns cgroups?

**Comment by dashpole** [comment]
It sounds like we might want to handle the error more gracefully.  If we can't get the kubelet's cgroup, we should fall back to collecting metrics from all cgroups.

**Comment by mattjmcnaughton** [comment]
@dashpole collecting metrics from all the cgroups on the system? Any concerns about how many cgroups there could be?

Also, @dashpole or @roycaihw any interest in implementing this fix (assuming we go with the fallback behavior)? If not, I can try.

**Comment by roycaihw** [comment]
thanks for looking into this! @mattjmcnaughton Sorry I'm not familiar with cgroups. I'm don't know any modification to my system assigns cgroups in particular

**Comment by dashpole** [comment]
I can put out a PR this week

**Comment by dashpole** [comment]
xref https://github.com/kubernetes/kubernetes/pull/79245

**Comment by mattjmcnaughton** [comment]
On Thu, Jun 20, 2019 at 04:21:34PM -0700, David Ashpole wrote:
> xref https://github.com/kubernetes/kubernetes/pull/79245
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/78950#issuecomment-504232883

Thanks!
