### ISSUE TITLE
Reschedule some pods when a new node is added into cluster

### ISSUE THREAD

**Issue by FengyunPan2** [kubernetes/kubernetes#78956]
**What would you like to be added**:
Move some pods which run on high-load node to the new node.

**Why is this needed**:
Currently I have three nodes, there are many pods running on them, their cpu usage are 60%~70% and their momery usage are 60%~70%.
\---
NodeA: ready  65%
NodeB: ready  65%
NodeC: ready  65%
\---
For unknown reasons, a node was down(ready->unready), its pods will be rebuilded. Then others' cpu usage and memory usage will become to 90%~100%, they are very busy. It is easy to get some OOM events.
\---
NodeA: ready    95%
NodeB: ready    95%
NodeC: unready  0%
\---
After a moment, the down node become ready(unready->ready),  but it has no pod. The result is: two nodes are very busy, a node is idle.
\---
NodeA: ready    95%
NodeB: ready    95%
NodeC: ready    0%
\---
\---
Can we add an enhancement to move some lower priority pods which run on high-load node to the new node?
\---

**Comment by FengyunPan2** [comment]
I have a idea:
Add the following parameter for eviction_manager,  if a new node is added into cluster or a unready node becomes ready, eviction_manager would trigger a pod eviction when node met  thresholds
/---
--eviction-pod-to-new-node：
A set of eviction thresholds (e.g. memory.available<2.5Gi) that if met and new node is added into cluster would trigger a pod eviction.
--eviction-pod-to-new-node-grace-period：
A set of eviction grace periods (e.g. memory.available=1m30s) that correspond to how long a eviction threshold must hold before triggering a pod eviction.
/---

**Comment by FengyunPan2** [comment]
My detailed steps:
step1: The eviction_manager watches the cluster nodes, if there are some nodes rrom unready to ready, go to step2; if there are some new nodes was added into cluster, go to step2; others...
step2:  determine the set of thresholds we need to drive eviction behavior, (i.e. cpu usage threshold
 and memory usage threshold are met), ifmet go to step3.
step3: Get the lower priority pods and do a sort by creationTimestamp\qosClass\status\restartCount\ priority.
step4: Filter pods again, about anti affinity, the replicas of pod's owner should large than 1, other limits...
step5: delete the pods, kube-scheduler would schedule them to new node.

**Comment by FengyunPan2** [comment]
\cc @dchen1107 
\cc @dashpole 
\cc @vishh 
Can you give me some suggestions? Thanks.

**Comment by FengyunPan2** [comment]
/cc @dchen1107 
/cc @dashpole 
/cc @vishh 
Can you give me some suggestions? Thanks.

**Comment by FengyunPan2** [comment]
BTW, it need add a parameter to enable\disable this enhancement.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes-incubator/descheduler

**Comment by FengyunPan2** [comment]
@liggitt Get it, thanks.
/close
