### ISSUE TITLE
es add-on: should we add memory limit?

### ISSUE THREAD

**Issue by zgfh** [kubernetes/kubernetes#78957]
**What happened**:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-statefulset.yaml#L75
no memory limit 
**What you expected to happen**:
limit memory

**Comment by zgfh** [comment]
ping @coffeepac  @monotek  @piosz

**Comment by coffeepac** [comment]
Are you having an issue about this?  As in, are hitting OOM issues or seeing pods evicted due to memory pressure?
