### ISSUE TITLE
Service Load balancer may not be cleaned up on type change

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#78954]
**What happened**:
Service Load balancer may not be cleaned up on type change if below sequence happen:
1. Service type changes from `LoadBalancer` to `ClusterIP`
2. Service controller restarts/crashes before it gets a chance to process the update from 1.
3. Service controller starts up again and sees the service doesn't want load balancer, hence skips it.
4. The load balancer resource sticks around even if it is no longer needed by the service.

Note that this is a different issue than https://github.com/kubernetes/kubernetes/issues/53451, as load balancer resource will still be cleaned up when the service object is deleted, just not when the type change happens.

**Anything else we need to know?**:
This is a corner case that is not covered by the initial service load balancer finalizer implementation (https://github.com/kubernetes/kubernetes/pull/78262).

This can probably be fixed in a trivial way --- make sure the `addFunc` handler takes in service with non-LoadBalancer type but has finalizer attached:
https://github.com/kubernetes/kubernetes/blob/aa3f81d657c1d4b7c789352af7179c08508adc3c/pkg/controller/service/service_controller.go#L140-L145

I will put more thoughts later.

cc @bowei @andrewsykim

**Comment by RainbowMango** [comment]
@MrHohn Can i reserve this issue in advance? :) I'd like to take this issue as my first issue.

**Comment by MrHohn** [comment]
@RainbowMango Sure thing, feel free to work on this and glad that you can help :)

**Comment by RainbowMango** [comment]
Any task i can do now?

**Comment by MrHohn** [comment]
> @MrHohn Do you mean attach finalizer for service that non-LoadBalancer type in AddFunc?

@RainbowMango No worries. I actually meant `addFunc` should include service with non-LoadBalancer type && with finalizer attached. As we only attach finalizer to a service only when we are creating a load balancer for it, a finalizer presents on the service (no matter what type it has) indicates there is a load balancer associated. Hence it makes sense that we should clean up the load balancer if the service no longer wants one, even if the service has not been deleted.

**Comment by MrHohn** [comment]
To clarify further, _"attach finalizer for service that non-LoadBalancer type in AddFunc"_ would not be what we want --- we shouldn't attach finalizer to service that we will not be creating load balancer for.

**Comment by RainbowMango** [comment]
@MrHohn 

After go through service controller part code, i guess you mean add a condition for `AddFunc` as follows:
```if ok && (wantsLoadBalancer(svc) || needsCleanup(svc) || (svc.Spec.Type != v1.ServiceTypeLoadBalancer && servicehelper.HasLBFinalizer(svc))) ```.

Am i right?

I'm not sure when service type changes if `AddFunc` can be involved. Can you clarify this ?

**Comment by MrHohn** [comment]
> After go through service controller part code, i guess you mean add a condition for AddFunc as follows:
if ok && (wantsLoadBalancer(svc) || needsCleanup(svc) || (svc.Spec.Type != v1.ServiceTypeLoadBalancer && servicehelper.HasLBFinalizer(svc))) .

Yea this was what I meant.

> I'm not sure when service type changes if AddFunc can be involved. Can you clarify this ?

On service type change, `UpdateFunc` will be involved instead of `AddFunc`. That part is already handled.

This issue is explicit for the case when controller fails to handle the type change update before it exiting (e.g. crashing, restart, etc.). Putting such detection to `AddFunc` is more off a remedy, it means the next time service controller starts up, it can re-syncs all existing services and find out it still need to cleanup load balancer for this service, even if it doesn't have load balancer type anymore.

**Comment by RainbowMango** [comment]
Thanks @MrHohn .

I have sent a PR assined to you. I think it should be checked in function `needsCleanup()`. It is the case that need to clean up whatever the reason is.
