### ISSUE TITLE
Kubectl exec -it [podname] bash throws error: Error from server: error dialing backend: No SSH tunnels currently open. 

### ISSUE THREAD

**Issue by limbuu** [kubernetes/kubernetes#78963]
I have been using kubernetes for more than a year. I recently ran into a problem i had never seen. I have stage and production cluster running in GKE. While i can access anything in stage cluster, i am having problem while using command : kubectl exec -it [podname] bash. It says  Error from server: error dialing backend: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-8ee7b20516c5b183b203"?. I waited couple of days hoping it was small glitch and would be solved by GKE, but i am still getting the problem. Anybody here please help me. I am using 1.11.8-gke.6 kubernetes version.

**Comment by KevinRiordan** [comment]
kubectl exec -it --namespace <namespace> <pod-name> -- /bin/bash

**Comment by limbuu** [comment]
No that doesn't work
