### ISSUE TITLE
kubernetes didn't work on arm64

### ISSUE THREAD

**Issue by rockylee3128** [kubernetes/kubernetes#78964]
![image](https://user-images.githubusercontent.com/35210314/59408186-035e0a80-8de6-11e9-9117-110af12241df.png)

**Comment by rockylee3128** [comment]
@luxas can you give me some advice?

**Comment by odinuge** [comment]
Hi @rockylee3128!

This is because the `kube-cross` image only supports `amd64`, and isn't a multi arch image.

The progress of adding support for other architectures in the `kube-cross` image can be tracked in this issue: https://github.com/kubernetes/kubernetes/issues/75114
