### ISSUE TITLE
Kubernetes node sysctl configuration 

### ISSUE THREAD

**Issue by mariojacobo** [kubernetes/kubernetes#78977]
**What happened**:

We have applied this workaround https://github.com/kubernetes/kubernetes/issues/70324#issuecomment-466107181 to increase the number of inotify watches. this is fine and working properly, I can "fs.inotify.max_user_watches" with the correct value from all pods in all namespaces. 

Now, we wanted to increase the following values as well, however the same workaround did not do the trick: 
net.core.netdev_max_backlog=4096 
net.core.somaxconn=4096 
net.ipv4.tcp_max_syn_backlog=4096 

Using the same DaemonSet as before did not do the trick. We specifically had to assign the DaemonSet to the kube-system namespace, however noticed that from within the container we were seeing the old values still. Eventually we found out that we had to recreate all of our PODs to include an init container that would change the values: 

initContainers:
         - command:
             - sh
             - -c
             - sysctl -w net.ipv4.tcp_max_syn_backlog=4096; sysctl -w net.core.somaxconn=4096; sysctl -w net.core.netdev_max_backlog=4096
           image: alpine:3.6
           imagePullPolicy: IfNotPresent
           name: sysctl
           resources: {}
           securityContext:
             privileged: true
             capabilities:
               add:
                 - NET_ADMIN
           volumeMounts:
             - name: modifysys
               mountPath: /sys

**What you expected to happen**:

To have the values reflected on the PODs as well, as docker and the host share the kernel. 
So, "fs.inotify.max_user_watches" cand be set in any Kubernetes namespace, and it's reflected  in the containers and nodes.  "net.core.somaxconn" needs to be set in the "kube-system" namespace and also as initcontainers in the POD yamls. Why the difference ? could it be due to safe vs unsafe sysctls 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Kube version: 1.12.6 
Provider: Azure AKS (unbuntu 16.04)
Kernel version: 4.15.0-1037-azure
Docker runtime: docker://3.0.4

**Comment by BenTheElder** [comment]
/sig node
/remove-sig scheduling

To set sysctls with a DaemonSet I believe you also need `hostPID: true` on the pod spec. The Kubernetes namespace should not matter.

**Comment by mariojacobo** [comment]
@BenTheElder - thanks, however as you can see in https://github.com/kubernetes/kubernetes/issues/70324#issuecomment-466107181 there is no need to add  hostPID:true, so I'm not if this applies. The documentation is quite lacking in this aspect, unless I'm looking in the wrong place.

**Comment by BenTheElder** [comment]
Re-read your original post.. all of your sysctls appear to be `net.*` which are namespaced, which is why putting it in an init container per pod. hostPID would set on the host but that's not what you want I think.

**Comment by BenTheElder** [comment]
You can set these via the security context, there's some pretty good docs for this here: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

hope that helps :-)

**Comment by mariojacobo** [comment]
thanks. that's the first thing I tried, which did not work unfortunately. I'll keep using the workaround
