### ISSUE TITLE
kube-scheduler plugin's strange code

### ISSUE THREAD

**Issue by likakuli** [kubernetes/kubernetes#78976]
**What happened**:
regist a preBind plugin will cause kube-scheduler panic
**What you expected to happen**:
do not panic
**How to reproduce it (as minimally and precisely as possible)**:
regist a preBind plugin
**Anything else we need to know?**:  

```
        pg := pluginsNeeded(plugins)
	if len(pg) == 0 {
		return f, nil
	}

	pluginConfig := pluginNameToConfig(args)
        // r is empty
	for name, factory := range r {
		// initialize only needed plugins
		if _, ok := pg[name]; !ok {
			continue
		}

		// find the config args of a plugin
		pc := pluginConfig[name]

		p, err := factory(pc, f)
		if err != nil {
			return nil, fmt.Errorf("error initializing plugin %v: %v", name, err)
		}
		f.plugins[name] = p
	}

        // f.plugins will always be empty, so error will be returned
	if plugins.Reserve != nil {
		for _, r := range plugins.Reserve.Enabled {
			if pg, ok := f.plugins[r.Name]; ok {
				p, ok := pg.(ReservePlugin)
				if !ok {
					return nil, fmt.Errorf("plugin %v does not extend reserve plugin", r.Name)
				}
				f.reservePlugins = append(f.reservePlugins, p)
			} else {
				return nil, fmt.Errorf("reserve plugin %v does not exist", r.Name)
			}
		}
	}
```

The comment for Enabled 
```
type PluginSet struct {
	// Enabled specifies plugins that should be enabled in addition to default plugins.
	// These are called after default plugins and in the same order specified here.
	Enabled []Plugin
	// Disabled specifies default plugins that should be disabled.
	// When all default plugins need to be disabled, an array containing only one "*" should be provided.
	Disabled []Plugin
}
```

Thus i am confused by the code and the comment

**Environment**:
- Kubernetes version (use `kubectl version`): 
v1.15.0-rc.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by likakuli** [comment]
sig/scheduling

**Comment by wgliang** [comment]
@likakuli Is there any panic context information or stack information?

**Comment by likakuli** [comment]
@wgliang here is the log
Log file created at: 2019/06/13 18:15:55
Running on machine: localhost
Binary: Built with gc go1.12.1 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0613 18:15:55.302272   86650 factory.go:261] error initializing the scheduling framework: prebind plugin foo does not exist
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0x3c59c01, 0x0, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:900 +0xe8
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x3c59c00, 0x3, 0xc0000c27e0, 0x3bc82d7, 0xa, 0x105, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:815 +0x254
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printf(0x3c59c00, 0x3, 0x2ab1d38, 0x2f, 0xc0007a4a78, 0x1, 0x1)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:727 +0x219
k8s.io/kubernetes/vendor/k8s.io/klog.Fatalf(0x2ab1d38, 0x2f, 0xc0007a4a78, 0x1, 0x1)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1309 +0x67
k8s.io/kubernetes/pkg/scheduler/factory.NewConfigFactory(0xc000502900, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/pkg/scheduler/factory/factory.go:261 +0x2af
k8s.io/kubernetes/pkg/scheduler.New(0x2d9d980, 0xc0001323c0, 0x2d36520, 0xc000310a20, 0x2d30160, 0xc0001da280, 0x2d365a0, 0xc000310a60, 0x2d36560, 0xc0004908a0, ...)
	/Users/didi/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:145 +0x571
k8s.io/kubernetes/cmd/kube-scheduler/app.Run(0xc000682128, 0xc0000a2240, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:164 +0xb83
k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand(0xc000642000, 0xc000686000, 0x0, 0x6, 0xc000093080, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:155 +0xa4d
k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand.func1(0xc000642000, 0xc000686000, 0x0, 0x6)
	/Users/didi/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:78 +0x7a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000642000, 0xc0000c2010, 0x6, 0x6, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0xe11
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000642000, 0xc000642000, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x677
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000642000, 0x0, 0x0)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x3b
main.main()
	/Users/didi/go/src/k8s.io/kubernetes/cmd/kube-scheduler/scheduler.go:47 +0xdf

goroutine 19 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x3c59c00)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1035 +0x73
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:404 +0x79

goroutine 47 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc0006810c0)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x79
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0x151

goroutine 25 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x26
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 82 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2b27358, 0x12a05f200, 0x0, 0x1, 0xc0000f6000)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:164 +0x1bb
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x2b27358, 0x12a05f200, 0xc0000f6000)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x2b27358, 0x12a05f200)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x80

goroutine 48 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001da440, 0x3b9aca00, 0x0, 0x1, 0xc0000f6000)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:164 +0x1bb
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0001da440, 0x3b9aca00, 0xc0000f6000)
	/Users/didi/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).run
	/Users/didi/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:624 +0xbb

The problem is obviously

**Comment by JieJhih** [comment]
@likakuli Can you provide any information about your registry? Something like: https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#plugin-registration

**Comment by likakuli** [comment]
@JieJhih I didn't implement a plugin. Only add a plugin to the KubeSchedulerConfiguration,

algorithmSource:
  provider: DefaultProvider
apiVersion: kubescheduler.config.k8s.io/v1alpha1
bindTimeoutSeconds: 600
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: ""
  qps: 50
disablePreemption: false
enableContentionProfiling: false
enableProfiling: false
failureDomains: kubernetes.io/hostname,failure-domain.beta.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region
hardPodAffinitySymmetricWeight: 1
healthzBindAddress: 0.0.0.0:10251
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 11s
  lockObjectName: kube-scheduler
  lockObjectNamespace: kube-system
  renewDeadline: 10s
  resourceLock: endpoints
  retryPeriod: 2s
metricsBindAddress: 0.0.0.0:10251
percentageOfNodesToScore: 50
schedulerName: default-scheduler
plugins:
  preBind:
    enabled:
    - name: foo
pluginConfig:
- name: foo
  args:
    flag: 1

**Comment by wgliang** [comment]
Although I am not sure, but I think it is your registry problem, just like @JieJhih  said, can you post the registry? Thanks

**Comment by wgliang** [comment]
@likakuli Maybe I understand your question. Indeed, if scheduler can't find the plugin you registered, it will panic directly. This is actually a composite expectation, because if it continues to execute you will not get the scheduling process and results you expect, so it is better to expose it in advance.

**Comment by likakuli** [comment]
@wgliang Thanks for your explain
