### ISSUE TITLE
Missing "protoc" when running API compatibility test

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#78980]
**What happened**:

API compatibility test depends on the presence of binary `protoc` in $PATH, but our presubmit ci job seems to be missing that: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/77327/pull-kubernetes-bazel-test/1139080812092723202/build-log.txt

```
compatibility.go:298: proto differs
compatibility.go:300: exec: "protoc": executable file not found in $PATH
compatibility.go:300: exec: "protoc": executable file not found in $PATH
```

https://github.com/kubernetes/kubernetes/blob/4f29960cb2058c4f556bf1e5ba49c9a29a501e70/staging/src/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go#L508

**What you expected to happen**:

1. Presubmit ci job should be self-contained to either install dependencies in the air, or have it pre-installed.
1. Furthermore, running `bazel test //staging/src/k8s.io/api:go_default_test` on a machine without `protoc` also fails. Dependencies should be transparent to users as well.

**How to reproduce it (as minimally and precisely as possible)**:

This issue can be triggered by a PR which contains API changes.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment]
A simple solution is to include `protoc` in:

https://github.com/kubernetes/test-infra/blob/bf4a71fd9ef14fc42473b719a5bd12f2b68b3b80/config/jobs/kubernetes/sig-testing/bazel-build-test.yaml#L19

But it doesn't help for users' running on a machine without `protoc`.

**Comment by liggitt** [comment]
The test does not depend on protoc. If the test fails, and protoc is present, it will dump more detailed info about the failure of protoc is available. By the time that message is logged, the test has already failed. 

/close

**Comment by liggitt** [comment]
Details about the test are added in a readme here: https://github.com/kubernetes/kubernetes/pull/78656

**Comment by Huang-Wei** [comment]
Thanks @liggitt. My local change (with API changes) passed with re-generated API compatibility data:

1. Run `UPDATE_COMPATIBILITY_FIXTURE_DATA=true go test ./vendor/k8s.io/api -run //HEAD &>/dev/null` (this generates lots of diff date under `staging/src/k8s.io/api/testdata/HEAD/`)
2. Then run `bazel test //staging/src/k8s.io/api:go_default_test` passed.

My question is should I (a) check-in the re-generated API data along with my PR, or (2) wait for #78656 to be merged?

**Comment by liggitt** [comment]
check in the regenerated data along with your PR

**Comment by Huang-Wei** [comment]
Got it. Thanks.
