### ISSUE TITLE
Corrupted filesystem when iSCSI is under load

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#78987]
`[sig-storage] In-tree Volumes [Driver: iscsi][Feature:Volumes] [Testpattern: Inline-volume (ext4)] volumes should be mountable` fails occasionally with iSCSI volumes.

I added `pull-kubernetes-e2e-gce-iscsi` job that runs e2e tests on iSCSI volumes on Ubuntu (because iscsiadm is installed there) and the aforementioned test flakes there.

The test does this:

1. It picks a node and runs all pods described below on this node.

2. It runs [iscsi-server pod](https://github.com/kubernetes/kubernetes/blob/85f2730d85c752d191057fec99c829566833442d/test/e2e/framework/volume/fixtures.go#L193). It's not a real server, it bind-mounts bunch of directories from the host and runs [a script that uses targetcli to add IQN to target that runs in Linux kernel](https://github.com/kubernetes/kubernetes/blob/master/test/images/volume/iscsi/run_iscsi_target.sh#L28).

3. It creates a PV for the new IQN.

4. It runs injector pod. The pod just does `echo Hello from iscsi from namespace volume-367 > index.html`.

5. It runs reader pod and check that index.html has expected content.

6. (it deletes the iscsi-server pod, which results into removal of IQN from the target)

The test fails, because the reader does not see content written by the injector. In addition, `dmesg` shows some scary errors:

```
Jun 13 14:57:22.861589 e2e-984c3e304e-decf4-minion-group-pdkf kernel: print_req_error: I/O error, dev sdc, sector 2
Jun 13 14:57:22.861741 e2e-984c3e304e-decf4-minion-group-pdkf kernel: Buffer I/O error on dev sdc, logical block 1, lost async page write
Jun 13 14:57:22.861770 e2e-984c3e304e-decf4-minion-group-pdkf kernel: Buffer I/O error on dev sdc, logical block 2, lost async page write
Jun 13 14:57:22.866031 e2e-984c3e304e-decf4-minion-group-pdkf kernel: print_req_error: I/O error, dev sdc, sector 518
Jun 13 14:57:22.866089 e2e-984c3e304e-decf4-minion-group-pdkf kernel: Buffer I/O error on dev sdc, logical block 259, lost async page write
Jun 13 14:57:22.866120 e2e-984c3e304e-decf4-minion-group-pdkf kernel: print_req_error: I/O error, dev sdc, sector 524
Jun 13 14:57:22.866160 e2e-984c3e304e-decf4-minion-group-pdkf kernel: Buffer I/O error on dev sdc, logical block 262, lost async page write
Jun 13 14:57:22.878890 e2e-984c3e304e-decf4-minion-group-pdkf kernel: print_req_error: I/O error, dev sdc, sector 0
Jun 13 14:57:22.899008 e2e-984c3e304e-decf4-minion-group-pdkf kernel: sd 2:0:0:0: [sdc] Synchronizing SCSI cache
```

I created PR #78941 that runs the test many times (30x by default). At least one of them always fails, see https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78941/pull-kubernetes-e2e-gce-iscsi/1139178958537887745/ 

What I checked:
* It works when tests are executed sequentially.
* It works when tests are executed in parallel with ~8 threads (e2e test uses IMO 30).
* **`blockdev --flushbufs /dev/sdXYZ` after unmount helps a bit**. The test then succeeds (or has at least higher success rate). But I still see scary errors in dmesg and fsck says that a volume was not cleanly unmounted. And unmount should flush the buffers too, right?
* Kubelet always unmounts, only after that it deletes the volume (`echo 1 > /sys/block/%s/device/delete`) and only after that it does `iscsadm ... --logout`.
* Sometimes I see timeouts from iscsiadm or even `encountered iSCSI database failure`, but it heals quickly (the whole cluster is under heavy load.)
* Tested with Ubuntu 18.04, Centos 7 and RHEL 8, all of them behave the same.
* So far I was not able to reproduce this with a shell script outside of Kubernetes.

Ideas:
* Could iscsi communication in kernel time out? The whole cluster is under really heavy load.
* Could targetcli somehow "damage" unrelated IQNs? There are many tests running in parallel, so a reconfiguration of the target happens quite often. All tests use the same IP (127.0.0.1) and port, each test uses its own IQN.

/sig storage

cc @bswartz @redbaron @j-griffith @rootfs @humblec  for iscsi expertise

**Comment by redbaron** [comment]
Interesting that failing test sees partial write. writer pod does echo with redirect and total write size is well below not only 4KB FS block size, but also 512 bytes sector size, so it must be super atomic, yet it is not :-/

-------- Original Message --------

**Comment by redbaron** [comment]
does it change if you create a single IQN, portal and multiple LUNs underneath? So there will be just a single login and a single logout by the kubelet for the whole test run.

**Comment by jsafrane** [comment]
I want the tests to be independent and race free. I don't want to maintain a state per node to know that the first test creates IQN, the last one removes it and keep a table of user / free LUNs.

**Comment by jsafrane** [comment]
I reproduced it partly outside of Kubernetes: adding a new IQN somehow disrupts the other IQNs. https://github.com/jsafrane/iscsi-reproducer

I can get `Buffer I/O error on dev sdc, logical block 123428, async page read` reliably, but no lost writes and filesystem corruption (FS is always clean).

**Comment by redbaron** [comment]
> I reproduced it partly outside of Kubernetes

Nice! IMHO it is worth reporting to https://www.mail-archive.com/open-iscsi@googlegroups.com/maillist.html
