### ISSUE TITLE
My cluster got very weird after `kubectl delete svc --all`

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#79004]
I read that this was a command that could be issued:

```bash
kubectl delete svc --all
```

what happens is that kubernetes service itself was deleted (and then seems to have restarted itself)

so this was the outcome of the above command:
https://stackoverflow.com/questions/56585220/cannot-tail-logs-of-pods-failed-create-pod-sandbox?noredirect=1#comment99758111_56585220

my cluster was pretty messed up after running the delete --all, I had to delete the entire cluster

**Comment by ORESoftware** [comment]
@kubernetes/sig-x

**Comment by yue9944882** [comment]
> kubectl delete svc --all

even tho kube-apiserver can recover from this by itself, but we still have to treat the "kubernetes.default" service nicely or it'll mess up many things

**Comment by ORESoftware** [comment]
here we go /remove-lifecycle stale
