### ISSUE TITLE
Pod ReadinessGate does not support strategic patch to add an item

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#79006]
**What happened**:

Pod's ReadinessGate is a slice, which must support strategic patch to add an item, but actually it is not.

**What you expected to happen**:

Pod ReadinessGate support strategic patch to add an item

**How to reproduce it (as minimally and precisely as possible)**:

A Pod named "pod1" has ReadinessGate ["bar"],  when we want to add a ReadinessGate "foo", we use `kubectl` to patch the Pod with the following command:
 ```
$ kubectl patch pod pod1 -p '{"spec":{"readinessGates":[{"conditionType":"foo"}]}}`'
```
After patch, the Pod has ReadinessGate ["foo"], but actually we want Pod 
 ReadinessGate has ["bar", "foo"].

The root cause source code is at [https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2984](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2984)

**Anything else we need to know?**:

Nothing yet

**Environment**:

The latest version of Kubernetes also has this issue

**Comment by yue9944882** [comment]
the field misses the patch key so SMP doesn't work. flip side of the coin, it breaks backward-compatiblity so the change is not acceptable. ref: https://github.com/kubernetes/kubernetes/issues/72475#issuecomment-450964421. in favor of server-side apply to address the issue.

**Comment by answer1991** [comment]
@yue9944882 got it, thanks for you reply.
