### ISSUE TITLE
fluentd-elasticsearch: add fluent-plugin-grok-parser

### ISSUE THREAD

**Issue by a-hat** [kubernetes/kubernetes#79024]
Would you consider to add the gem for [fluent-plugin-grok-parser](https://github.com/fluent/fluent-plugin-grok-parser)?

It could be helpful to parse the log output and extract additional fields

**Comment by ijunbin** [comment]
@a-hat 
do you fix out this?  i get the same problem when use grok
`ConfigError error="Unknown parser plugin 'grok'`
