### ISSUE TITLE
kubelet: Failed to find subsystem mount for required subsystem: pids

### ISSUE THREAD

**Issue by rafatio** [kubernetes/kubernetes#79046]
**What happened**:
We're updating the cluster from 1.12.1 to 1.14.3. When kubelet goes up for the first time, the following warnings related to cgroups pids controller appear:

`kubelet[4854]: W0612 qos_container_manager_linux.go:139] [ContainerManager] Failed to reserve QoS requests: failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to find subsystem mount for required subsystem: pids`

If we restart, kubelet returns fatal error with a similar motive:

`kubelet[1502]: F0614 19:19:17.066475    1502 kubelet.go:1359] Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup: failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to find subsystem mount for required subsystem: pids`

It makes sense since our kernel version doesn't support cgroups pids controller, then we disabled cgroups pids related feature gates: `SupportPodPidsLimit` and `SupportNodePidsLimit` expecting that kubelet would not require pids subsystems, but the behavior persisted.

Looking at [cgroup_manager_linux.go:329](https://github.com/kubernetes/kubernetes/blob/5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0/pkg/kubelet/cm/cgroup_manager_linux.go#L329), it looks like pids subsystem will always be required even with feature gates disabled. This change was introduced with `SupportNodePidsLimit` in 2597a1d97ef4d8f54b1ca661453e32794b756909.

**What you expected to happen**:
We expected that the cgroup pids subsystem to don't be required if feature gates related to pids are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
Try to start any kubelet in 1.14.x using a kernel older than 4.3.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
Oracle Linux Server release 7.6
- Kernel (e.g. `uname -a`):
Linux 4.1.12-124.26.12.el7uek.x86_64 #2 SMP Wed May 8 22:25:03 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
puppet

**Comment by mattjmcnaughton** [comment]
Thanks for looking into this!

Do you want to create a pr? We can then merge this into master and also cherry-pick it back into 1.14. Alternatively, if you don't have capacity for a pr I'm happy to take a stab.

**Comment by rafatio** [comment]
Just created:
#79073

**Comment by dashpole** [comment]
cc @RobertKrawitz

**Comment by balaji-panneerselvam** [comment]
Hi, We are facing this issue, with kubernetes v1.15.0, is this fixed?

**Comment by dims** [comment]
@balaji-panneerselvam - see the version information of when the commit landed in the commit itself:
https://github.com/kubernetes/kubernetes/pull/79073/commits/08c258add9b9b0be4597415f0add3d8fb627ec4b
