### ISSUE TITLE
build/run.sh failure due to fetch false preventing from being pulled

### ISSUE THREAD

**Issue by vorburger** [kubernetes/kubernetes#79048]
**What happened**:
I'm noob just trying [to follow the README](https://github.com/kubernetes/kubernetes#you-have-a-working-docker-environment) for the first time, but `build/run.sh` fails early on:

```
$ build/run.sh make kubectl
+++ [0614 23:18:26] Verifying Prerequisites....
+++ [0614 23:18:26] Building Docker image kube-build:build-8ef9608e83-5-v1.12.5-1
+++ Docker build command failed for kube-build:build-8ef9608e83-5-v1.12.5-1

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1: FROM k8s.gcr.io/kube-cross:v1.12.5-1
Error: error creating build container: no such image "containers-storage:[overlay@/home/vorburger/.local/share/containers/storage+/tmp/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]k8s.gcr.io/kube-cross:v1.12.5-1"

To retry manually, run:

docker build -t kube-build:build-8ef9608e83-5-v1.12.5-1 --pull=false /home/vorburger/Kubernetes/kubernetes/_output/images/kube-build:build-8ef9608e83-5-v1.12.5-1

!!! [0614 23:18:27] Call tree:
!!! [0614 23:18:27]  1: build/run.sh:31 kube::build::build_image(...)
!!! Error in build/../build/common.sh:427
  Error in build/../build/common.sh:427. 'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:427 kube::build::build_image(...)
  2: build/run.sh:31 main(...)
Exiting with status 1

```

**What you expected to happen**:
I guess i expected `build/run.sh` as advertised in the README? :smile: 

**How to reproduce it (as minimally and precisely as possible)**:
1. Fedora 30 Server
1. sudo dnf install podman-docker
1. docker rmi k8s.gcr.io/kube-cross
1. git clone https://github.com/kubernetes/kubernetes.git ; cd kubernetes
1. `build/run.sh make kubectl`

**Comment by vorburger** [comment]
The problem seems pretty obvious to me, unless I'm missing something:

How could `docker build` work with `--pull=false` for `FROM k8s.gcr.io/kube-cross:v1.12.5-1`, if you never pulled that image before?

I'll raise a PR proposing a fix...

**Comment by vorburger** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by BenTheElder** [comment]
> $ build/run.sh make kubectl

Where are we documenting this workflow? The usual workflow should probably be `make WHAT=cmd/kubectl` (or bazel...) 

In [the link](https://github.com/kubernetes/kubernetes#you-have-a-working-docker-environment) you provided above I see make?

**Comment by vorburger** [comment]
> Where are we documenting this workflow? The usual workflow should probably be `make WHAT=cmd/kubectl` 

found [here](https://github.com/kubernetes/kubernetes/blob/master/build/README.md#key-scripts)

> (or bazel...)

happy [to try Bazel](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/bazel.md)...

> In [the link](https://github.com/kubernetes/kubernetes#you-have-a-working-docker-environment) you provided above I see make?

that `make` ultimately seems to end up doing pretty much exactly the same:

```
$ make quick-release
+++ [0614 23:12:50] Verifying Prerequisites....
+++ [0614 23:12:51] Building Docker image kube-build:build-8ef9608e83-5-v1.12.5-1
+++ Docker build command failed for kube-build:build-8ef9608e83-5-v1.12.5-1

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1: FROM k8s.gcr.io/kube-cross:v1.12.5-1
Error: error creating build container: no such image "containers-storage:[overlay@/home/vorburger/.local/share/containers/storage+/tmp/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]k8s.gcr.io/kube-cross:v1.12.5-1"

To retry manually, run:

docker build -t kube-build:build-8ef9608e83-5-v1.12.5-1 --pull=false /home/vorburger/Kubernetes/kubernetes/_output/images/kube-build:build-8ef9608e83-5-v1.12.5-1

!!! [0614 23:12:51] Call tree:
!!! [0614 23:12:51]  1: build/release.sh:35 kube::build::build_image(...)
make: *** [Makefile:461: quick-release] Error 1
```

**Comment by cblecker** [comment]
Looks like it has to do with a difference in flag meanings between docker and podman. `docker build --pull=false` seems to be the equivalent of a `podman build --pull-always=false`. `podman build --pull=false` has a different meaning and functionality.

I would suggest opening up a bug report against libpod.. if they're going to provide an emulation layer, it should probably associate the right flags.

**Comment by vorburger** [comment]
> opening up a bug report against libpod..

https://github.com/containers/buildah/issues/1675

**Comment by BenTheElder** [comment]
> found here

thanks! @cblecker do you think those are really a good workflow? I would think the best workflow is to use the make / bazel targets :sweat_smile:

**Comment by cblecker** [comment]
Well, you *are* running make targets.. it just some are able to be run inside the containerized build system. Running a `make release` is basically a `build/run.sh make cross`. Totally a supported method. What we don't currently support is unique configurations for other build tools (like podman/buildah).

**Comment by vorburger** [comment]
#99025
