### ISSUE TITLE
bazel build: ERROR: WORKSPACE file can not be a symlink if incrementally updated directories feature is enabled.

### ISSUE THREAD

**Issue by vorburger** [kubernetes/kubernetes#79056]
**What happened**:
`bazel build` fails with:

    ERROR: WORKSPACE file can not be a symlink if incrementally updated directories feature is enabled.

**What you expected to happen**:
`bazel build` to work?

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/kubernetes/kubernetes.git ; cd kubernetes
bazel build //cmd/kubectl
(...)
bazel build //cmd/kubectl
ERROR: WORKSPACE file can not be a symlink if incrementally updated directories feature is enabled.
```

NB: Showing `bazel build` twice above is not a typo - it does work for me the very very first time, but subsequent attempts fail.

**Environment**:
```
$ bazel version
Build label: 0.26.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 11 17:32:07 2019 (1560274327)
Build timestamp: 1560274327
Build timestamp as int: 1560274327
```

Installed on Fedora 30 from https://docs.bazel.build/versions/master/install-redhat.html

**Comment by vorburger** [comment]
@kubernetes/sig-contributor-experience-bug

**Comment by vorburger** [comment]
> NB: Showing bazel build twice above is not a typo - it does work for me the very very first time, but subsequent attempts fail.

`bazel shutdown` actually works around this problem - but shouldn't be needed?

**Comment by nikhita** [comment]
I can reproduce this as well...same bazel version as issue body.

/cc @ixdy @fejta @BenTheElder

**Comment by jin** [comment]
Fix is to update to 0.26.1. This is https://github.com/bazelbuild/bazel/issues/8475

**Comment by BenTheElder** [comment]
I don't think we can do anything further here, do not use 0.26.0 😬 
https://github.com/bazelbuild/bazelisk provides a tool for using specific versions

**Comment by justaugustus** [comment]
/remove-sig release
/area release-eng
Ping @kubernetes/sig-testing.

**Comment by BenTheElder** [comment]
This was an upstream bug, long since fixed.
/close
