### ISSUE TITLE
How to change or update resource limits after scheduling?

### ISSUE THREAD

**Issue by hamiBU** [kubernetes/kubernetes#79065]
I would like to change/update resource limits after scheduling. What levels should I do? 
What parts of codes in go are necessary to be considered?

**Comment by liucimin** [comment]
Now the K8s not support this.
U can see the huawei paas repositiy.
It commit their finish.

**Comment by snowplayfire** [comment]
Maybe you can try to update `Cgroup` data to change/update resource limits.
