### ISSUE TITLE
Azure managed disk not mounting as pv

### ISSUE THREAD

**Issue by LiquoriChris** [kubernetes/kubernetes#79067]
**What happened**: Getting a MountVolume.Setup failure when configuring a pv with an Azure managed disk.

**What you expected to happen**: Volume should mount to share and be available.

**How to reproduce it (as minimally and precisely as possible)**: 

1. Create standard managed disk storage class.
2. Create deployment with a pvc and pv.

**Anything else we need to know?**: Currently using a standard HDD to test first. Using marketplace VMs in Azure. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.7
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): RHEL 7.6
- Kernel (e.g. `uname -a`): 3.10.0-957.21.2.el7.x86_64
- Install tools: kubeadm, kubelet, kubectl
- Network plugin and version (if this is a network-related bug):
- Others:
[podError.txt](https://github.com/kubernetes/kubernetes/files/3293055/podError.txt)

**Comment by LiquoriChris** [comment]
@kubernetes/sig-storage

**Comment by LiquoriChris** [comment]
@kubernetes/sig-storage

**Comment by andyzhangx** [comment]
I think it may be related to redhat os, the error says:
```
mount -o bind /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/<diskmount> /var/lib/kubelet/pods/<redacted>/kubernetes.io~azure-disk/<redacted>
```

Could you ssh to the node, and check whether `/var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/<diskmount>` exists and mounted correctly already?

I guess there is something wrong with the udev rule, could you also check whether there is a dir `/dev/disk/azure` on that node, you could find more debugging skills here:
https://github.com/andyzhangx/demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md#3-take-ubuntu-1604-as-an-example-it-has-attached-3-data-disks-below-is-the-debugging-info-need-to-collect

**Comment by andyzhangx** [comment]
BTW, how do you set up k8s cluster on redhat? @LiquoriChris
