### ISSUE TITLE
Promote Pod Test to Conformance

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#79115]
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the Pod kind:

[patchCoreV1NamespacedPodStatus](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-patchCoreV1NamespacedPodStatus&showUntested=false&showConformanceTested=false)

[listCoreV1PodForAllNamespaces](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-listCoreV1PodForAllNamespaces&showUntested=false&showConformanceTested=false)

These are stable core endpoints which have existing testing, potentially making for low-hanging fruit to upgrade to Conformance.

/area test
/area conformance
/sig testing

**Comment by hh** [comment]
This one seems like a likely candidate:
```
[k8s.io] Pods should support pod readiness gates [NodeFeature:PodReadinessGate]
```
It will add one new stable endpoint: patchCoreV1NamespacedPodStatus

**Comment by hh** [comment]
This test is disabled for large clusters... would that preclude it from conformance?
/cc @johnbelamaric 
```
[k8s.io] [sig-node] NodeProblemDetector [DisabledForLargeClusters] should run without error
```
It would add another endpoint: listCoreV1PodForAllNamespaces

**Comment by johnbelamaric** [comment]
Not according to the written policy. How is "large" defined?

**Comment by devaips** [comment]
The PR assigned to this issue has been closed and the test is being rewritten. Closing this issue.
