### ISSUE TITLE
Detach sequence key support, Ctrl + P

### ISSUE THREAD

**Issue by arbach** [kubernetes/kubernetes#79110]
ctrl+p is commonly used as up arrow, however same combination is the detach sequence for docker. This need to be configured in the coniguration file, or command line option --detach-key. 

Will be great if we can add same option to kubectl. 

@kubernetes/sig-cli-feature-requests

**Comment by arbach** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by bdowling** [comment]
Would be nice to see this fixed...

**Comment by oshadmon** [comment]
This looks like a duplicate of [71765](https://github.com/kubernetes/kubernetes/issues/71765) - given that the feature is still not there, would also appreciate reopening the issue. 

Thanks! 

`/reopen`
