### ISSUE TITLE
Slow Test analysis: "Pod should avoid nodes that have avoidPod annotation"

### ISSUE THREAD

**Issue by globervinodhn** [kubernetes/kubernetes#79126]
**What would you like to be added**:
The existing E2E test - "Pod should avoid nodes that have avoidPod annotation" - takes around 684 seconds i.e., 11 minutes to execute successfully. The tet is currently not marked SLOW as is expected to be.

**Why is this needed**:
Analysis to determine the reason for such slow execution of the test is a must to ensure that remedial solutions can be applied for the test to bring the execution to under 5 minutes and promote to conformance given it satisfies all the given criteria for conformance promotion.

Copied To: @mgdevstack  and @brahmaroutu

**Comment by globervinodhn** [comment]
remove /kind feature

**Comment by alenkacz** [comment]
I'll take a look at this one

**Comment by alenkacz** [comment]
@globervinodhn do you have example of the slow run? I went to testgrid, found the test in https://testgrid.k8s.io/sig-scheduling#gce-serial and all the executions I hit were under 2 minutes

**Comment by mgdevstack** [comment]
Yes this e2e execution time is always < 2min even in local `kind` cluster.
1. 
```
• [SLOW TEST:94.435 seconds]
[sig-scheduling] SchedulerPriorities [Serial]
test/e2e/scheduling/framework.go:23
  Pod should avoid nodes that have avoidPod annotation
  test/e2e/scheduling/priorities.go:152
------------------------------
Jun 19 14:56:00.960: INFO: Running AfterSuite actions on all nodes
Jun 19 14:56:00.960: INFO: Running AfterSuite actions on node 1

Ran 1 of 4408 Specs in 94.595 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 4407 Skipped
PASS
```
2. https://source.cloud.google.com/results/invocations/dd854d1c-2108-47bc-8976-c3639cba8fac/targets/test/tests;query=should%20avoid%20nodes%20that%20have%20avoidPod%20;failed=false

**Comment by globervinodhn** [comment]
> @globervinodhn do you have example of the slow run? I went to testgrid, found the test in https://testgrid.k8s.io/sig-scheduling#gce-serial and all the executions I hit were under 2 minutes

Both you and @mgdevstack are reporting sub 2 minutes time but it still takes 11 minutes for me!!! Must be some env issues at my end. However, I am attaching the console log. Do let me know if you find any issues in it,

[11_slow_avoid_pod_test2.txt](https://github.com/kubernetes/kubernetes/files/3319765/11_slow_avoid_pod_test2.txt)

**Comment by mgdevstack** [comment]
@globervinodhn, Could you verify once again. If issue is fixed, feel free to close this issue.

**Comment by globervinodhn** [comment]
> @globervinodhn, Could you verify once again. If issue is fixed, feel free to close this issue.

Weird as it might sound, due to some unknown reason I still experience slowness for this particular testcase
