### ISSUE TITLE
Ability to move/copy all namespaced objects

### ISSUE THREAD

**Issue by medmedchiheb** [kubernetes/kubernetes#79134]
**What would you like to be added**:

Always testing require some good functionality.
in kubernetes we have some good testing behavior.
but we could enhance it.

I'm suggesting to be able to move or copy all namespaced API objects from a namespace to another.

However, it's a powerful feature, since when you are going to test something but you won't modify actual state.

i suggest also, to be specified in `kubectl create namespace`
for example when creating a new namespace, all objects are copied from the base `ns` 
 
`kubectl create namespace testing --from-namespace=dev
`

**Why is this needed**:

testing feature for testing, by copy/move all objects from a namespace to another
you could let the base namespace as it's.

**Comment by almiche** [comment]
> by copy/move all objects from a namespace to another
you could let the base namespace as it's.

Hi there I don't really see what you mean here with this ? 

Why would you want to copy all the objects of a namespace for testing purposes? I can't see a scenario where someone would want to copy objects over to a new namespace since after having for example a deployment there's only so much you can modify until needing to just create a new deployment altogether. I'm curious to find out more 😄

**Comment by medmedchiheb** [comment]
@almiche   i'm referring to a full cluster state, this case is helpful especially when you're going to be prod.
imagine you have huge of objects and you want to move them. 
i see some people doing this by executing a script to copy or move objects. 
although, i'm suggest this to be part of kubernetes controllers rather than in client side.

**Comment by almiche** [comment]
> I'm referring to a full cluster state

I understand that but you mentioned above that this could be a testing feature what kind of testing ? 

> this case is helpful especially when you're going to be prod. 

I take it you would have you test and prod objects on the same cluster basically ? So when you're ready to deploy you create a new namespace copy over the entire cluster state and have that namespace be used as the prod instance ?

In any case this shouldn't be too difficult of a feature to add in, I just can't think of a really concrete scenario where I would use it. I would have multiple k8s clusters depending on the environment ie: testing, staging and prod. I wouldn't run my testing and prod instances of my system or app in the same k8s cluster and node pool.
