### ISSUE TITLE
kubernetes for edge computing case

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#79135]
**What happened**:
I expect to run a kubernetes with minimum resource for edge computing case. For example, run kubernetes on you phone, IoT device, switch, etc

**What you expected to happen**:
The edge case may not require much complex scheduling, admission control plugin, volume plugin. So we'd expect to 
- disable those component in the building stage to have a minimum hyperkube binary. 
- light-weighted data store instead of etcd. 
- Even HA support is not mandatory.  
- light-weighted container runtime, e.g., containerd, cri-o
- CNI network
- local storage, or CSI storage

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.2
- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: None
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liqlin2015** [comment]
/ kind feature

**Comment by rohitsardesai83** [comment]
Please check https://github.com/kubeedge/kubeedge/ .
Maybe it suffices some of your requirements.

**Comment by CindyXing** [comment]
To understand better, can you clarify below? These would be help to evaluate what can be done further. 

1. Where do you plan to run the control plane (k8s master components): at cloud or edge?
2. What exactly is the resource requirement at edge? You mentioned phone/iot device. Do you plan to treat them as a worker node in your k8s cluster? If so, what's the OS and resource requirement(memory, cpu, etc.)
3. What's the thought of CNI at the edge? How about CSI? What's the network and storage topology setting?

**Comment by liqlin2015** [comment]
@rohitsardesai83 We have tried k3s. It looks good to us. But from k8s community, what's the solution to support edge computing. You know k3s is from rancher, not official k8s community.

@CindyXing 
> 1. Where do you plan to run the control plane (k8s master components): at cloud or edge?

Run k8s control plane at edge device. 

> 2. What exactly is the resource requirement at edge? You mentioned phone/iot device. Do you plan to treat them as a worker node in your k8s cluster? If so, what's the OS and resource requirement(memory, cpu, etc.)

Memory resource requirement like the following:
- 512 MB ram for k8s master
- 75 MB ram for k8s worker
- 200 MB disk space

And OS should be some embedded,  Atomic OS.

> 3. What's the thought of CNI at the edge? How about CSI? What's the network and storage topology setting?

For CNI and CSI I mean we should run k8s cluster (both master and worker) on edge. There should be some CNI network like flannel and calico installed to help manage container network. 

For CSI I mean storage support for edge case. I don't have exact storage requirement yet. Currently local storage should be ok.

Of course, container runtime support. Should be containerd by default.

**Comment by ptone** [comment]
Rancher has said they are open and eager to contribute k3s/k3os to CNCF 

Are you looking for capability or just official status/blessing?

**Comment by liqlin2015** [comment]
Yea. We have learned k3s for a while.
Just want to know the (official) solution in k8s community. Looking forward Rancher contribute k3s to the community. But at the sametime there should not be two code repos.

**Comment by dims** [comment]
@liqlin2015 neither `kubedge` or `k3s` are not part of any official kubernetes github orgs. please do work with whichever solution that works for you. Both take different views on several matters, so it's up to your organization to pick a direction (or even support both!).
