### ISSUE TITLE
kubectl delete of a static pod results in multiple attempts to re-create the mirror pod before succeeding

### ISSUE THREAD

**Issue by RobertKrawitz** [kubernetes/kubernetes#79147]
**What happened**: `kubectl delete` of a static pod (really the mirror pod) results in multiple attempts to re-create the mirror pod before it finally succeeds (note that in some runs it goes into Running or Terminating state -- it just depends upon the exact timing of the `kubectl get pod`.
Note that in the below trace the pod name is elided from the `kubectl get pod` output.

Note that the actual static pod continues to run as normal.

```
pod "static-test-ip-10-0-133-116.ec2.internal" deleted
 1: Mon 17 Jun 2019 10:27:28 AM EDT    0/2   Pending   0     0s
 2: Mon 17 Jun 2019 10:27:29 AM EDT    0/2   Pending   0     1s
 3: Mon 17 Jun 2019 10:27:31 AM EDT    0/2   Pending   0     0s
 4: Mon 17 Jun 2019 10:27:32 AM EDT    0/2   Pending   0     0s
 5: Mon 17 Jun 2019 10:27:33 AM EDT    0/2   Pending   0     1s
 6: Mon 17 Jun 2019 10:27:35 AM EDT    0/2   Pending   0     0s
 7: Mon 17 Jun 2019 10:27:36 AM EDT    2/2   Running   0     0s
 8: Mon 17 Jun 2019 10:27:37 AM EDT    2/2   Running   0     1s
 9: Mon 17 Jun 2019 10:27:38 AM EDT    2/2   Running   0     3s
10: Mon 17 Jun 2019 10:27:40 AM EDT    2/2   Running   0     4s
11: Mon 17 Jun 2019 10:27:41 AM EDT    2/2   Running   0     5s
12: Mon 17 Jun 2019 10:27:42 AM EDT    2/2   Running   0     7s
13: Mon 17 Jun 2019 10:27:44 AM EDT    2/2   Running   0     8s
14: Mon 17 Jun 2019 10:27:45 AM EDT    2/2   Running   0     9s
15: Mon 17 Jun 2019 10:27:46 AM EDT    2/2   Running   0     11s
16: Mon 17 Jun 2019 10:27:48 AM EDT    2/2   Running   0     12s
```

**What you expected to happen**:
Mirror pod should start without additional state transitions

**How to reproduce it (as minimally and precisely as possible)**:
Create a static pod, `kubectl delete` it, and 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14/OpenShift 4.2 (master has the same code)
- Cloud provider or hardware configuration: AWS (not relevant)
- OS (e.g: `cat /etc/os-release`): Not relevant
- Kernel (e.g. `uname -a`): Not relevant
- Install tools: Not relevant
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by RobertKrawitz** [comment]
More details:

The bug appears to be a race condition between deleting the old mirror pod, the API server deleting its record of it, and creating a replacement that's not related to skew.  I suspect the reason I didn't see it bouncing back and forth in my earlier tests was simply that I wasn't running the oc get node frequently enough; if I run it continuously, I see it bounce.

The sequence is:

1) Somebody oc deletes the mirror pod.

2) The static pod code in kubelet.go (around line 1630) notices that the pod has been marked deleted (its deletion timestamp is not nil and it is a mirror pod), deletes it (in DeleteMirrorPod in mirror_client.go, via the apiserverClient), and creates a new one (again, via the apiserverClient).

3) The next time around, the static pod code may see either the old pod (that has been deleted) or the new one as the mirror pod.  If the old pod is the one that's seen, it sees that there's a deletion timestamp, so it deletes it again -- which, since pod deletion is by name (UID isn't involved) results in the new pod being deleted and yet another new pod being created.  If the new pod is the one that's seen, then we break out with the spin cycle complete.

Still TBD is why the mirror pod isn't getting replaced right away.  But here are traces of the relevant sequences:

Bad sequence:

```**1** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.346483  127422 kubelet.go:1629] Looking at mirror pod static-test-ip-10-0-133-116.ec2.internal_default(f5804497-912b-11e9-905d-0262cfb4eaaa) (2019-06-17 18:16:38 +0000 UTC)
**2** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: W0617 18:16:08.346527  127422 kubelet.go:1633] Deleting mirror pod static-test-ip-10-0-133-116.ec2.internal_default(f5804497-912b-11e9-905d-0262cfb4eaaa) because it is outdated (ts 2019-06-17 18:16:38 +0000 UTC ismirror true)
**3** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.346568  127422 mirror_client.go:90] Deleting a mirror pod "static-test-ip-10-0-133-116.ec2.internal_default"
**4** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.360095  127422 kubelet.go:1915] SyncLoop (DELETE, "api"): "static-test-ip-10-0-133-116.ec2.internal_default(f5804497-912b-11e9-905d-0262cfb4eaaa)"
**5** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.365757  127422 mirror_client.go:61] +++ CreateMirrorPod copying annocations to &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:static-test-ip-10-0-133-116.ec2.internal,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/static-test-ip-10-0-133-116.ec2.internal,UID:c16b436300c49a5823c0313268428fad,...
**6** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.367056  127422 kubelet.go:1909] SyncLoop (REMOVE, "api"): "static-test-ip-10-0-133-116.ec2.internal_default(f5804497-912b-11e9-905d-0262cfb4eaaa)"
**7** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.373583  127422 mirror_client.go:69]     +++ New pod &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:static-test-ip-10-0-133-116.ec2.internal,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/static-test-ip-10-0-133-116.ec2.internal,UID:fa7e0d17-912b-11e9-905d-0262cfb4eaaa,...
**8** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.375201  127422 kubelet.go:1899] SyncLoop (ADD, "api"): "static-test-ip-10-0-133-116.ec2.internal_default(fa7e0d17-912b-11e9-905d-0262cfb4eaaa)"
**9** Jun 17 18:16:08 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:08.591032  127422 kubelet.go:1629] Looking at mirror pod static-test-ip-10-0-133-116.ec2.internal_default(f5804497-912b-11e9-905d-0262cfb4eaaa) (2019-06-17 18:16:08 +0000 UTC)```

Good sequence:

```**11** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.606293  127422 kubelet.go:1629] Looking at mirror pod static-test-ip-10-0-133-116.ec2.internal_default(fd07cb10-912b-11e9-905d-0262cfb4eaaa) (2019-06-17 18:16:13 +0000 UTC)
**12** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: W0617 18:16:14.606315  127422 kubelet.go:1633] Deleting mirror pod static-test-ip-10-0-133-116.ec2.internal_default(fd07cb10-912b-11e9-905d-0262cfb4eaaa) because it is outdated (ts 2019-06-17 18:16:13 +0000 UTC ismirror true)
**13** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.606325  127422 mirror_client.go:90] Deleting a mirror pod "static-test-ip-10-0-133-116.ec2.internal_default"
**14** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.619916  127422 kubelet.go:1915] SyncLoop (DELETE, "api"): "static-test-ip-10-0-133-116.ec2.internal_default(fda04997-912b-11e9-905d-0262cfb4eaaa)"
**15** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.626095  127422 mirror_client.go:61] +++ CreateMirrorPod copying annocations to &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:static-test-ip-10-0-133-116.ec2.internal,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/static-test-ip-10-0-133-116.ec2.internal,UID:c16b436300c49a5823c0313268428fad,...
**16** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.628262  127422 kubelet.go:1909] SyncLoop (REMOVE, "api"): "static-test-ip-10-0-133-116.ec2.internal_default(fda04997-912b-11e9-905d-0262cfb4eaaa)"
**17** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.635995  127422 kubelet.go:1899] SyncLoop (ADD, "api"): "static-test-ip-10-0-133-116.ec2.internal_default(fe396356-912b-11e9-905d-0262cfb4eaaa)"
**18** Jun 17 18:16:14 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:14.636991  127422 mirror_client.go:69]     +++ New pod &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:static-test-ip-10-0-133-116.ec2.internal,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/static-test-ip-10-0-133-116.ec2.internal,UID:fe396356-912b-11e9-905d-0262cfb4eaaa...
**19** Jun 17 18:16:15 ip-10-0-133-116 hyperkube[127422]: I0617 18:16:15.608883  127422 kubelet.go:1629] Looking at mirror pod static-test-ip-10-0-133-116.ec2.internal_default(fe396356-912b-11e9-905d-0262cfb4eaaa) (<nil>)```

----

The messages at lines 7 and 18 were printed immediately after the call to apiServerClient...Create().  But the key is at lines 9 and 19.  At line 9, note that the UID (f58044...) is the UID of the old mirror pod, which has a deletion timestamp and therefore the mirror code deletes the pod -- but the pod that's actually in existence at the time is the new pod.  At line 19, however, note that the mirror pod is now the new one, which is not marked for deletion, and is therefore left alone.

The solution (I'll open a PR shortly) is to check both the pod name and the UID to make sure that we're in fact trying to delete the pod we think we want to delete.

**Comment by RobertKrawitz** [comment]
@smarterclayton @sjenning

**Comment by mattjmcnaughton** [comment]
Thanks for the detailed issue @RobertKrawitz :) Really awesome!

**Comment by brianloss** [comment]
I'm seeing this issue on an upgrade from v1.14.4 to v1.15.1 following the [kubeadm HA upgrade instructions](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/) on a CentOS 7 system. After installing the updated kubelet package and restarting kubelet per the instructions, the cluster went into a loop of continually restarting the etcd pod from one control plane node and the scheduler pod from another control plane node. This continued for approximately 10 minutes before the etcd pod finally stayed up. It was another 5 minutes before the scheduler pod finally ran.

I noticed v1.15.2 was released although the change log doesn't show this issue included. Was there a plan to back-port this fix to 1.15 and 1.14 (not to the same extent, but I have seen this behavior on a 1.14.4 cluster)? Since this behavior can happen to the apiserver pod, it has the potential to be very disruptive to a cluster.

**Comment by RobertKrawitz** [comment]
The actual etcd pod, or the mirror pod (which is more likely)?

I hadn't specifically planned on backporting it, but it shouldn't be a problem; this code has been stable.

**Comment by brianloss** [comment]
Ah, good point--the actual pod does appear to remain running. That makes it less important than I was initially thinking. However, it is a bit disconcerting for someone who happens to be looking at the state of the cluster (or for monitoring) to see the pod appear to be stuck in a restart loop. If it were just a few iterations, it might not matter too much. However, I'm seeing this happen for minutes at a time. For example, to verify that the real pod remained available I did a `kubectl delete pod` on the apiserver pod for one master, and `kubectl get pod` output showed it in the restart loop for 15 minutes before it settled down. IMO that's worth backporting if it's low risk.

**Comment by RobertKrawitz** [comment]
I opened a cherrypick against 1.15 for this.

**Comment by brianloss** [comment]
> I opened a cherrypick against 1.15 for this.

Appreciated. Thanks!
