### ISSUE TITLE
add "kubeadm stop" parameter (or any other cli) to stop entire cluster

### ISSUE THREAD

**Issue by tmc9031** [kubernetes/kubernetes#79141]
**What would you like to be added**:
Please add "kubeadm stop" parameter (or any other cli) to implement safely stop entire cluster for manitain some server node

**Why is this needed**:
Read all k8s document i can NOT find any method to stop cluster, and have to directly poweroff all server node
I am NOT sure that is safe for container running, i hope k8s can provided official poweroff method

**Comment by neolit123** [comment]
/triage support

depends on your setup, but if you have a load balancer in front of the API server you can temporary disable that without disrupting the k8s components. you can also temporary stop the api server, but that's less advisory.

kubernetes does not support such "stop" functionality, or "pause".
for more ideas you can also try stackoverflow -> kubernetes or the kubernetes slack #kubeadm channel.
thanks.
