### ISSUE TITLE
Connect lower level traces to surrounding request handling trace

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#79209]
**What would you like to be added**:

The kube-apiserver logs traces for operations that exceed a max latency using the `k8s.io/utils/trace` utility. This is done for request handling, etcd storage layer operations, watch cache operations and we just added it for webhook calls.

But when, for example, there is a create request that involves high latency admission webhook call, there are two separate traces logged: 

One for the create request being handled:

```
Trace[866828359]: "Create /api/v1/namespaces/default/pods" (started: 2019-03-11 08:20:14.448210695 +0000 UTC m=+579.430813234) (total time: 14.520559394s):
Trace[866828359]: [165.764543ms] [149.545551ms] Object stored in database
Trace[866828359]: [14.304157451s] [14.138392908s] Writing response
Trace[866828359]: [14.520559394s] [216.401943ms] END
```

An entirely independent one for the admission webhook call:

```
Trace[770033805]: "Call mutating webhook: configuration: mutating.stable.example.com, webhook: noop.stable.example.com, resource: {stable.example.com v1 foos}, subResource: , operation: DELETE, UID: fe7355d4-6c72-459c-9118-b7f43175dac1" (started: 2019-06-11 22:11:59.119388404 +0000 UTC m=+120.935456173) (total time: 12.76491ms):
Trace[770033805]: [12.754882ms] [12.754882ms] Request completed
```

Ideally, these would be connected together in some way. In the above example, the admission webhook call is part of the overall create request. I'm not tied to a specific output format, but it would be great to organize the trace logging to make this as obvious as possible, e.g.:

```
Trace[866828359]: "Create /api/v1/namespaces/default/pods" (started: 2019-03-11 08:20:14.448210695 +0000 UTC m=+579.430813234) (total time: 14.520559394s):
Trace[866828359]: Subtrace[770033805]: "Call mutating webhook: configuration: mutating.stable.example.com, webhook: noop.stable.example.com, resource: {stable.example.com v1 foos}, subResource: , operation: DELETE, UID: fe7355d4-6c72-459c-9118-b7f43175dac1" (started: 2019-06-11 22:11:59.119388404 +0000 UTC m=+120.935456173) (total time: 12.76491ms):
Trace[866828359]: Subtrace[770033805]: [12.754882ms] [12.754882ms] Request completed
Trace[866828359]: [165.764543ms] [149.545551ms] Object stored in database
Trace[866828359]: [14.304157451s] [14.138392908s] Writing response
Trace[866828359]: [14.520559394s] [216.401943ms] END
```

Currently, the trace library only provides a way to add steps to a trace, but I feel like hierarchy helps convey the relationships here.

**Why is this needed**:

Would make it much easier to drill down from  a trace message in the kube-apiserver to the component responsible for the high latency of a request.

/sig api-machinery
cc @cheftako @logicalhan

**Comment by roycaihw** [comment]
we could use context to carry the request-scoped trace object and replace the new allocated lower-level ones in https://github.com/kubernetes/kubernetes/pull/78610/files

/good-first-issue

**Comment by Creatone** [comment]
I intend to work with that issue.

**Comment by jeffliu27** [comment]
@roycaihw @jpbetz would love to help out as well!

**Comment by roycaihw** [comment]
The basic idea is that we have separate trace objects in our rest handlers (e.g. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L49) and in lower level webhook invocations (https://github.com/kubernetes/kubernetes/pull/78610/files). Those trace objects get logged separately as https://github.com/kubernetes/kubernetes/issues/79209#issue-458338942 describes. 

It makes more sense to combine those traces together into one log. I think passing the high level trace object to the lower levels through context and reusing it could solve it. We can even restrict to only pass `trace.Step` interface in the context to prevent accidentally invoke `trace.LogIfLong` at lower level

**Comment by vnktram** [comment]
@roycaihw I would like to help with this.

**Comment by jpbetz** [comment]
@jeffliu27 Were you still thinking of working on this? Sounds like @vnktram is also interested.

**Comment by roycaihw** [comment]
FYI https://github.com/kubernetes/kubernetes/pull/79376 is making webhooks context-aware, which makes it easier to [plumb high level trace from rest request handler](https://github.com/kubernetes/kubernetes/pull/79376/files#diff-7861f33474e4eb8d21cf1d33de5e4d4eR132) down to the [lower level webhook invocation](https://github.com/kubernetes/kubernetes/pull/78610/files#diff-e057ec5b2ec27b4ba1e1a3915f715262R61)

**Comment by answer1991** [comment]
> FYI #79376 is making webhooks context-aware, which makes it easier to [plumb high level trace from rest request handler](https://github.com/kubernetes/kubernetes/pull/79376/files#diff-7861f33474e4eb8d21cf1d33de5e4d4eR132) down to the [lower level webhook invocation](https://github.com/kubernetes/kubernetes/pull/78610/files#diff-e057ec5b2ec27b4ba1e1a3915f715262R61)

Good idea. We can add trace to context just like [RequestInfo and User](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go#L77).

**Comment by jeffliu27** [comment]
@jpbetz  yes, currently working on it

**Comment by caesarxuchao** [comment]
@jpbetz this is related to @YoyinZyc tracing work in etcd. She wants to work on this one as well!

**Comment by jpbetz** [comment]
Perfect.  Thanks @YoyonZyc.  Happy to chat about potential solutions

**Comment by tedyu** [comment]
@YoyinZyc
Was this the tracing work in etcd mentioned above ?
```
commit 340f0ac7974ba8cde802d5acae097f0ba0f9f6d1

    Add tracing to range request in etcd server.
```
Thanks

**Comment by YoyinZyc** [comment]
> @YoyinZyc
> Was this the tracing work in etcd mentioned above ?
> 
> ```
> commit 340f0ac7974ba8cde802d5acae097f0ba0f9f6d1
> 
>     Add tracing to range request in etcd server.
> ```
> 
> Thanks

Yes, it is. FYI, the PR is https://github.com/etcd-io/etcd/pull/11179
