### ISSUE TITLE
Invalid patch body can result internal-server error in the server

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#79210]
/kind bug
/sig api-machinery
/cc @jennybuckley @apelisse 

**What happened**:

patching (SMP) any object's annotation using invalid patch content will result in an (500) internal-server error. expecting a (400) bad-request error in this case.

patch body:
```json
{"metadata":{"annotations":{"foo":["bar"]}}}
```

received error:

```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unrecognized type: string","code":500}
```

the error is thrown from converter instead of the patcher, so it seems that patcher considers the body as valid then the converter complained.

**Anything else we need to know?**:

when my grandpa was 65 years old he started running one mile a day to keep fit. he's 70 now and we have no idea where he is.

**Comment by apelisse** [comment]
I just tried the same patch with "MergePatchType", and it also fails with 500.

**Comment by apelisse** [comment]
I can't make it fail with JSONPatchType, I get a 422

**Comment by apelisse** [comment]
```
Failed to patch object: the server rejected our request due to an error in our request (patch deployments deployment): {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server rejected our request due to an error in our request","reason":"Invalid","details":{},"code":422}
```

I suspect the error should read "the server rejected **y**our request due to an error in our request"
