### ISSUE TITLE
daemonset status not correct  num of status some filed

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#79211]
**What happened**:
in mysql cluster, it's has 33 node and every node running a pod of kube-proxy created by daemonset and all the pod of kube-proxy ds was running status. but when l describe the ds of kube-proxy, the status like this:
```
currentNumberScheduled: 4 
numberMisscheduled: 29 
desiredNumberScheduled: 4 
numberReady: 4  
updatedNumberScheduled: 4  
numberAvailable: 4  
```
what 's maening of the ds status filed？ l can‘t  find some doc or source code to know it. 
so l think those of myself like this: 
```
currentNumberScheduled: current daemoncontroller simulate schedule paas  and the pod not on the node in crrent time. (but when the controller manger restart, it's my less or zero)

numberMisscheduled: current daemoncontroller simulate schedule not paas. 

desiredNumberScheduled：only current daemoncontroller simulate schedule paas.

numberReady:  the pod status condition ready is true

updatedNumberScheduled:  current daemoncontroller simulate schedule paas  and the pod not on the node in crrent time.  the pod status condition available is true,the pod status condition ready is true , and the pod hash was update

numberAvailable:  the pod status condition available is true

```
please notic the all num was base on the current status of damon-controller.  when ths controller was down and restart, some num was not correct

the code of the status update owner by the daemonsetController like this:

```
func (dsc *DaemonSetsController) updateDaemonSetStatus(ds *apps.DaemonSet, hash string, updateObservedGen bool) error {
	klog.V(4).Infof("Updating daemon set status")
	nodeToDaemonPods, err := dsc.getNodesToDaemonPods(ds)
	if err != nil {
		return fmt.Errorf("couldn't get node to daemon pod mapping for daemon set %q: %v", ds.Name, err)
	}

	nodeList, err := dsc.nodeLister.List(labels.Everything())
	if err != nil {
		return fmt.Errorf("couldn't get list of nodes when updating daemon set %#v: %v", ds, err)
	}

	var desiredNumberScheduled, currentNumberScheduled, numberMisscheduled, numberReady, updatedNumberScheduled, numberAvailable int
	for _, node := range nodeList {
		wantToRun, _, _, err := dsc.nodeShouldRunDaemonPod(node, ds)
		if err != nil {
			return err
		}

		scheduled := len(nodeToDaemonPods[node.Name]) > 0

		if wantToRun {
			desiredNumberScheduled++
			if scheduled {
				currentNumberScheduled++
				// Sort the daemon pods by creation time, so that the oldest is first.
				daemonPods, _ := nodeToDaemonPods[node.Name]
				sort.Sort(podByCreationTimestampAndPhase(daemonPods))
				pod := daemonPods[0]
				if podutil.IsPodReady(pod) {
					numberReady++
					if podutil.IsPodAvailable(pod, ds.Spec.MinReadySeconds, metav1.Now()) {
						numberAvailable++
					}
				}
				// If the returned error is not nil we have a parse error.
				// The controller handles this via the hash.
				generation, err := util.GetTemplateGeneration(ds)
				if err != nil {
					generation = nil
				}
				if util.IsPodUpdated(pod, hash, generation) {
					updatedNumberScheduled++
				}
			}
		} else {
			if scheduled {
				numberMisscheduled++
			}
		}
	}
	numberUnavailable := desiredNumberScheduled - numberAvailable

	err = storeDaemonSetStatus(dsc.kubeClient.AppsV1().DaemonSets(ds.Namespace), ds, desiredNumberScheduled, currentNumberScheduled, numberMisscheduled, numberReady, updatedNumberScheduled, numberAvailable, numberUnavailable, updateObservedGen)
	if err != nil {
		return fmt.Errorf("error storing status for daemon set %#v: %v", ds, err)
	}

	return nil
}
```

1. first to simulate schedule the ds's pod to the node
2. second get the pod of  ds on the current node, if pod exist scheduled is true
3. if current schedule paas but the pod oready exist on the node, check the ready and avalible
4. step 3 not paas, but step 2 pass, numberMisscheduled++

l think the logic of the check ready and available is error.
 
**What you expected to happen**:
maybe the  currentNumberScheduled,numberMisscheduled,desiredNumberScheduled,updatedNumberScheduled  can do like this, but the numberReady,numberAvailable shouldn't do like this.

l think should consider the pod which exsit on the node.  the code like this:

```
func (dsc *DaemonSetsController) updateDaemonSetStatus(ds *apps.DaemonSet, hash string, updateObservedGen bool) error {
	klog.V(4).Infof("Updating daemon set status")
	nodeToDaemonPods, err := dsc.getNodesToDaemonPods(ds)
	if err != nil {
		return fmt.Errorf("couldn't get node to daemon pod mapping for daemon set %q: %v", ds.Name, err)
	}

	nodeList, err := dsc.nodeLister.List(labels.Everything())
	if err != nil {
		return fmt.Errorf("couldn't get list of nodes when updating daemon set %#v: %v", ds, err)
	}

	var desiredNumberScheduled, currentNumberScheduled, numberMisscheduled, numberReady, updatedNumberScheduled, numberAvailable int
	for _, node := range nodeList {
		wantToRun, _, _, err := dsc.nodeShouldRunDaemonPod(node, ds)
		if err != nil {
			return err
		}

		scheduled := len(nodeToDaemonPods[node.Name]) > 0

		if wantToRun {
			desiredNumberScheduled++
			if scheduled {
				currentNumberScheduled++

			}
		} else {
			if scheduled {
				numberMisscheduled++
			}
		}
		
		// Sort the daemon pods by creation time, so that the oldest is first.
		daemonPods, _ := nodeToDaemonPods[node.Name]
		sort.Sort(podByCreationTimestampAndPhase(daemonPods))
		pod := daemonPods[0]
		if podutil.IsPodReady(pod) {
			numberReady++
			if podutil.IsPodAvailable(pod, ds.Spec.MinReadySeconds, metav1.Now()) {
				numberAvailable++
			}
		}
		// If the returned error is not nil we have a parse error.
		// The controller handles this via the hash.
		generation, err := util.GetTemplateGeneration(ds)
		if err != nil {
			generation = nil
		}
		if util.IsPodUpdated(pod, hash, generation) {
			updatedNumberScheduled++
		}
	}
	numberUnavailable := desiredNumberScheduled - numberAvailable

	err = storeDaemonSetStatus(dsc.kubeClient.AppsV1().DaemonSets(ds.Namespace), ds, desiredNumberScheduled, currentNumberScheduled, numberMisscheduled, numberReady, updatedNumberScheduled, numberAvailable, numberUnavailable, updateObservedGen)
	if err != nil {
		return fmt.Errorf("error storing status for daemon set %#v: %v", ds, err)
	}

	return nil
}
```
**How to reproduce it (as minimally and precisely as possible)**:
create a ds in the cluster,  when the ds's all pod running, stop the controller-manager. 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
1.14.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux k8s-master 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
baniry
- Network plugin and version (if this is a network-related bug):
flannel:v0.11.0
- Others:

**Comment by huangjiasingle** [comment]
@sig API Machinery

**Comment by Joseph-Irving** [comment]
/sig apps
You can see the meaning of the status fields here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#daemonsetstatus-v1-apps

Misscheduled pods indicates that you have nodes running the daemonset pod that should not be, only 4 of your nodes appear to match the criteria to run the daemonset, hence having a `desiredNumberScheduled: 4`. This could be due to something like a mismatch of node selectors in the daemonset and labels on your nodes. potentially you have pods not managed by that ds running on your nodes that match the pod selector, e.g they're created manually or by another daemonset.

**Comment by huangjiasingle** [comment]
@Joseph-Irving  the doc of https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#daemonsetstatus-v1-apps couln't describe the those field clear.  
the all ds pod of kube-proxy total 33 was running normal. another 29 running pod no created manually or by another daemonset.    the ready and avilable num was not correct.
you can read the code of up.  the logic not correct.

**Comment by huangjiasingle** [comment]
@Joseph-Irving  if the controller manager is running alway and no restart. the logic is no problems. but if the controller manager was restart, the logic couldn't calculate the correct result of the ds status.

**Comment by tedyu** [comment]
Looks like we don't have a test where controller manager is restarted.
If such test is added, it would be easier to determine the code change.

**Comment by huangjiasingle** [comment]
@tedyu  that's right.

**Comment by huangjiasingle** [comment]
@deads2k @derekwaynecarr@ @mikedanese @janetkuo can you help me？
