### ISSUE TITLE
Field selector for CRD

### ISSUE THREAD

**Issue by sayarg** [kubernetes/kubernetes#79233]
**What would you like to be added**: Extend CRD API, add ability to specify fields to be used in a field selector query

**Why is this needed**: To filter large lists of CRD in both kubectl and http API. We are currently forced to copy fields and values from the CRD's spec and status to add labels, so that we can query with label selectors

**Comment by roycaihw** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/53459

currently CRD supports namespace and name as field selector labels

cc @liggitt @sttts

**Comment by yue9944882** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180415-crds-to-ga.md

>> Enable arbitrary CRD field selectors by supporting a whitelist of fields in CRD spec (https://github.com/kubernetes/kubernetes/issues/53459)

it's in the post-GA-task list

**Comment by sayarg** [comment]
thanks all for the details. i'll go ahead a close the issue and wait for post GA.
