### ISSUE TITLE
Update vendored dependencies to a released version instead of random SHA(s)

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#79234]
Algorithm:
- Look at go.mod, look for dependencies with [Pseudo-versions](https://golang.org/cmd/go/#hdr-Pseudo_versions)
- Look at the github repo of the dependencies, find a released tag closest to the SHA (but higher than the SHA)
- Look at the commits in the range and review with the [guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/godep.md#justifications-for-an-update) in mind
- NOTE that the version bump suggestions below are just that ("suggestions"), please try to find a closer or better match of release tags based on the guidelines above.

Here's the situation as of June 20, 2019 using [some scripts](https://gist.github.com/dims/c0857b86441442b15852a4c2355db130) to highlight possibilities
- [x] github.com/codedellemc/goscaleio ( filed https://github.com/kubernetes/kubernetes/pull/80321 )
- [ ] github.com/docker/libnetwork ( [from a9cd636e3789 to possibly v0.6.0-rc1 or newer](https://github.com/docker/libnetwork/compare/a9cd636e3789...v0.6.0-rc1) )
- [ ] github.com/gogo/protobuf ( [from 342cbe0a0415 to possibly v1.0.0 or newer](https://github.com/gogo/protobuf/compare/342cbe0a0415...v1.0.0) )
- [x] github.com/gophercloud/gophercloud( [from c818fa66e4c8 to possibly v0.2.0 or newer](https://github.com/gophercloud/gophercloud/compare/c818fa66e4c8...v0.2.0) )
- [x] github.com/heketi/heketi ( [from 558b29266ce0 to possibly v9.0.0 or newer](https://github.com/heketi/heketi/compare/558b29266ce0...v9.0.0) )
- [ ] github.com/libopenstorage/openstorage ( [from 093a0c388875 to possibly v8.0.0 or newer](https://github.com/libopenstorage/openstorage/compare/093a0c388875...v8.0.0) )
- [ ] github.com/opencontainers/runc ( [from f000fe11ece1 to possibly v0.1.1 or newer](https://github.com/opencontainers/runc/compare/f000fe11ece1...v0.1.1) )
- [ ] github.com/prometheus/common ( [from 4724e9255275 to possibly v0.6.0 or newer](https://github.com/prometheus/common/compare/4724e9255275...v0.6.0) )
- [x] github.com/seccomp/libseccomp-golang ( [from 1b506fc7c24e to possibly v0.9.1 or newer](https://github.com/seccomp/libseccomp-golang/compare/1b506fc7c24e...v0.9.1) )
- [ ] github.com/vishvananda/netlink ( [from b2de5d10e38e to possibly v1.0.0 or newer](https://github.com/vishvananda/netlink/compare/b2de5d10e38e...v1.0.0) )
- [ ] google.golang.org/api ( [from 583d854617af to possibly v0.6.0 or newer](https://google.golang.org/api/compare/583d854617af...v0.6.0) )
- [x] github.com/docker/distribution (filed https://github.com/kubernetes/kubernetes/pull/80721)

**Comment by mwmix** [comment]
@dims  I would like to work on this as my first issue. If I had some questions would you be available to help?

**Comment by dims** [comment]
@akutz could you peek at the github.com/codedellemc/goscaleio dependency?
@alok87 could you please see if you can take on the github.com/docker/libnetwork?
@liggitt i am totally afraid of the protobuf bump, could you please peek?
@ramineni could you please see if you can bump github.com/gophercloud/gophercloud?
@humblec can you please look at the github.com/heketi/heketi bump?
@RobertKrawitz did you last touch https://github.com/kubernetes/kubernetes/commits/master/pkg/volume/portworx? looks like the dependency is from there
@derekwaynecarr any idea who can help with github.com/opencontainers/runc and github.com/seccomp/libseccomp-golang?
@johnbelamaric do you see anything good with github.com/vishvananda/netlink?
@liggitt @cheftako who could help with google.golang.org/api?

**Comment by akutz** [comment]
Hi @dims,

While I [no longer have anything to do with GoScaleIO](https://gist.github.com/akutz/b291f5db2116bd644a5ab150b09b9066), I will still take a peak since you asked nicely :)

It appears the last release of GoScaleIO was [v0.1.0](https://github.com/thecodeteam/goscaleio/releases/tag/v0.1.0), on October 7th 2017. However, there have been [seven commits since then](https://github.com/thecodeteam/goscaleio/compare/v0.1.0...master).

FWIW, none of this fixes the Go module issue to which I referred the other day. I will be filing a separate issue to explain that. It's a systemic problem related to how k/k repos do not ever merge commits to which release tags point back to `master`.

**Comment by dims** [comment]
Ack @akutz thanks!

**Comment by RobertKrawitz** [comment]
@dims I did as part of #66928 (quotas for ephemeral storage).  This was because I needed to add an additional argument to the volume mounter code; I modified all of the volume types the same way.  Is something needed here?

**Comment by dims** [comment]
@mwmix pick one of the dependencies and see if you can make progress with a PR. We can use #k8s-code-organization to chat if you wish.

@RobertKrawitz Ack, no worries, that portworx code seems to drag in libopenstorage/openstorage, so was trying to see if anyone know that piece well enough to try to update the dependency version.

**Comment by odinuge** [comment]
Hi @dims,

**Comment by odinuge** [comment]
Hi @dims,

`github.com/seccomp/libseccomp-golang` & `github.com/opencontainers/runc` will be updated in https://github.com/kubernetes/kubernetes/pull/78495. `libseccomp-golang` will be pinned to `v0.9.1` (latest), while `runc` has to use the latest commit in order to get a required fix. Will bump `runc` to a released version as fast as they release a new version.

**Comment by dims** [comment]
@odinuge Ack, they (runc folks) don't seem to be very particular about tagging stuff. So we may have to request them to do so (looking at https://github.com/opencontainers/runc/tags). thanks for the update!

**Comment by dims** [comment]
@odinuge Don't forget we tried once before to update the libseccomp, so you will have to deal with issues mentioned here - https://github.com/kubernetes/kubernetes/pull/78187#pullrequestreview-250782154

**Comment by BenTheElder** [comment]
the libseccomp bit is not a good first issue due to the build changes, I'm working on fixing that one specifically. :crossed_fingers:

**Comment by draveness** [comment]
FYI: instructions for vendor related scripts: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md

**Comment by humblec** [comment]
@dims thanks, I am on it :)

**Comment by draveness** [comment]
I opened a PR to update  github.com/prometheus/common to v0.6.0 https://github.com/kubernetes/kubernetes/pull/79261

**Comment by mwmix** [comment]
@dims I will try my hand at the heketi dependency then. And I will drop any questions I may have in the chat you suggested. Ty!

**Comment by humblec** [comment]
> @dims I will try my hand at the heketi dependency then. And I will drop any questions I may have in the chat you suggested. Ty!

@mwmix as mentioned here https://github.com/kubernetes/kubernetes/issues/79234#issuecomment-504320005, I am on it :)

**Comment by BenTheElder** [comment]
Filed a PR for the libseccomp package https://github.com/kubernetes/kubernetes/pull/79287

**Comment by dims** [comment]
Some input from docker/moby folks https://github.com/moby/moby/issues/39632#issuecomment-516502726

**Comment by praseodym** [comment]
This issue seems to have PRs for all dependencies, so:
/remove-good-first-issue
/remove-help

**Comment by draveness** [comment]
/reopen

Close by mistake through #80321

**Comment by dims** [comment]
This has served its purpose. we are better off today than when we opened this issue. We just have to keep working it and open issues/pr(s) as needed
