### ISSUE TITLE
Refactor "create object, launch goroutines" logic all over

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#7923]
We have a number of different ways of doing this:

```
x := NewFoo()
x.Run()
```

```
x := NewFoo()
go x.runFoo()
```

```
fc := FooConfig{StartControllers: true}
x := NewFoo(&fc)
```

We should pick one and switch to it all over.  Relatively easy refactoring.

**Comment by lavalamp** [comment]
Whatever we choose, it should take a ```<-chan struct{}``` for shutdown instructions.

**Comment by thockin** [comment]
Mostly about consistency across code.  Style Guide style

**Comment by nikhita** [comment]
/remove-priority awaiting-more-evidence

I don't think `priority/awaiting-more-evidence` and `help wanted` labels should be on the same issue. :)

This issue looks like it's got sufficient evidence already.

**Comment by nikhita** [comment]
I'm going to add the good-first-issue label on this because this is refactoring code and the main issue body contains examples.

If you are interested in working on this, please feel free to pick any file where you find inconsistencies and start fixing it.

/good-first-issue

**Comment by minherz** [comment]
@thockin Is there any documented decision about which way is preferred?

**Comment by ash2k** [comment]
I've done a bit of refactoring in that area - please see #45454 (fix pr is #46094). I think the Go best practice is to delegate the decision of whether to start something in a goroutine or not to the caller. Or hide concurrency by exposing a synchronously looking API (i.e. a method that blocks until all the concurrent work has been done and all goroutines exited). I think such APIs are much easier to use - the caller has more control.

Please see my use case example in the issue I mentioned above.
Another example of the "lack of control" issue - I cannot use informer factory because it does not provide a way to block until all informers finish. So I use `informer.Run` (that blocks) to start informers and then track their lifecycles myself. I wanted to tackle this issue by refactoring the factory to expose a synchronous `Run` method that blocks until all informers stop. Haven't had time for it so far.

**Comment by thockin** [comment]
Agree that concurrency should be caller's problem.  We should, in general,
not have Run() functions that spawn their own goroutine and then return
without waiting for it.

**Comment by kenlavoie** [comment]
I'd like to take this as a first issue - CLA is in progress 

Anyone available to review before submitting a PR?

**Comment by jeffliu27** [comment]
Is there still help needed on this issue? I want to help as a first time contributor.

**Comment by Sanjary** [comment]
Hey folks, still need a hand? I'd love to help as a first time contributor.

**Comment by Tazminia** [comment]
Hello,

Is this still relevant ?

**Comment by thockin** [comment]
This is almost certainly still true, but finding them will be harder now.

I find > 700 "go something" calls in the codebase.  Maybe smarter analysis could find oddball cases?

```
find . -name \*.go | grep -v _test.go | grep -v vendor | xargs grep "go [a-zA-Z]" | grep -v "go func(" | less
```

**Comment by AnitaNayak** [comment]
Is this still relevant? I would like to help.

**Comment by hprateek43** [comment]
Can pick this up if still needed.

**Comment by Ajitesh13** [comment]
Hello, can I take this issue?

**Comment by gm7y8** [comment]
Hello, can I contribute to this?

**Comment by lavalamp** [comment]
All, this is (likely) a large change and can be done piece-meal. There's no need to ask for permission :) 

Also, if adding stop channels, I think it's best now to use a context instead of a raw `<-chan struct{}`.

**Comment by priyanka19-98** [comment]
Hello all, can I take up this issue if no one is assigned yet?

**Comment by bhakiyakalimuthu** [comment]
Hello, I'm a first time contributor.like to take up this one.

**Comment by clarkmcc** [comment]
@lavalamp it seems like there are a lot of cases where we would need the ability to stop but don't have access to a propagated context. The nice thing about the bare `<-chan struct{}` is that you can use it anywhere. Some of the lower level areas of the code base don't have access to a context. Thoughts?

**Comment by lavalamp** [comment]
Personally I'd probably make adaptors that convert `context` to `<-chan struct{}` or vice versa. Then it's easy to propagate whatever you have to whatever callees need, you can add this everywhere in a series of small PRs. Then in a second step you can convert places using `<-chan struct{}` to use `context` instead, and it's easy to fix callers by just removing an adaptor. Again in a series of smallish PRs.

The intermediate state probably involves an extra goroutine at each step, but a) context might do that anyway in some cases and b) it's a temporary state.

**Comment by vnev** [comment]
Hi, if no one is working on this I'd be willing to take it up

**Comment by Aut0R3V** [comment]
This looks interesting, I'd like to work on this. Can someone help me with the progress here?

**Comment by BLasan** [comment]
@thockin Still opened ?
