### ISSUE TITLE
Kubelet service wont start

### ISSUE THREAD

**Issue by afagund** [kubernetes/kubernetes#79244]
**What happened**:

I am following the official documentation below to set up a new Kubernetes cluster using kubeadm, however, I am not able to start kubelet on mu etcd nodes.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

**What you expected to happen**:

I expect to start kubelet as per steps in the official documentation.

**How to reproduce it (as minimally and precisely as possible)**:
Just follow exactly the steps from the documentation.

**Anything else we need to know?**:
This is what I am seeing in the logs.

Jun 20 19:38:14 etcd1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 20 19:38:14 etcd1 kubelet: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 20 19:38:14 etcd1 kubelet: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.

After creating a kubelet config file, I see a different error.

Config File:

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
staticPodPath: /etc/kubernetes/manifests
address: 127.0.0.1

Error:

Jun 20 19:26:22 etcd1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 20 19:26:23 etcd1 systemd: Started Kubernetes systemd probe.
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038340   15772 server.go:425] Version: v1.15.0
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038558   15772 plugins.go:103] No cloud provider specified.
Jun 20 19:26:23 etcd1 kubelet: W0620 19:26:23.038574   15772 server.go:564] standalone mode, no API client
Jun 20 19:26:23 etcd1 kubelet: F0620 19:26:23.038588   15772 server.go:273] failed to run Kubelet: no client provided, cannot use webhook authentication
Jun 20 19:26:23 etcd1 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 20 19:26:23 etcd1 systemd: Unit kubelet.service entered failed state.
Jun 20 19:26:23 etcd1 systemd: kubelet.service failed.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
 Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux etcd1.andrefagundes.org 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by afagund** [comment]
Also seeing in the logs 

Jun 20 19:43:12 etcd1 kubelet: F0620 19:43:12.031754   16803 server.go:156] unknown flag: --allow-privileged

**Comment by afagund** [comment]
@kubernetes/docs-bugs

**Comment by tedyu** [comment]
The deprecated Kubelet flag `--allow-privileged` has been removed. Remove any use of the flag from your kubelet scripts or manifests. ([#77820](https://github.com/kubernetes/kubernetes/pull/77820), [@dims](https://github.com/dims))

**Comment by afagund** [comment]
As I mentioned, I removed the flags and used the config file, however, I am seeing another error after that:

Jun 20 19:26:22 etcd1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 20 19:26:23 etcd1 systemd: Started Kubernetes systemd probe.
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038340 15772 server.go:425] Version: v1.15.0
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038558 15772 plugins.go:103] No cloud provider specified.
Jun 20 19:26:23 etcd1 kubelet: W0620 19:26:23.038574 15772 server.go:564] standalone mode, no API client
Jun 20 19:26:23 etcd1 kubelet: F0620 19:26:23.038588 15772 server.go:273] failed to run Kubelet: no client provided, cannot use webhook authentication
Jun 20 19:26:23 etcd1 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 20 19:26:23 etcd1 systemd: Unit kubelet.service entered failed state.
Jun 20 19:26:23 etcd1 systemd: kubelet.service failed.

**Comment by tedyu** [comment]
From BuildAuth :
```
	if client != nil && !reflect.ValueOf(client).IsNil() {
		tokenClient = client.AuthenticationV1beta1().TokenReviews()
```
It seems client was nil.
In turn:
```
	if kubeDeps.Auth == nil {
		auth, err := BuildAuth(nodeName, kubeDeps.KubeClient, s.KubeletConfiguration)
```
kubeDeps.KubeClient was nil.
This is because you were in standalone mode.

**Comment by tedyu** [comment]
I wonder if the auth should be dependent on whether standaloneMode is not true:
```
diff --git a/cmd/kubelet/app/server.go b/cmd/kubelet/app/server.go
index 139a8eacbb..e8338dd5db 100644
--- a/cmd/kubelet/app/server.go
+++ b/cmd/kubelet/app/server.go
@@ -612,7 +612,7 @@ func run(s *options.KubeletServer, kubeDeps *kubelet.Dependencies, stopCh <-chan
                }
        }

-       if kubeDeps.Auth == nil {
+       if kubeDeps.Auth == nil && !standaloneMode {
                auth, err := BuildAuth(nodeName, kubeDeps.KubeClient, s.KubeletConfiguration)
                if err != nil {
                        return err
```

**Comment by neolit123** [comment]
/remove-kind bug
cc @pytimer could you please take a look at this `setup-ha-etcd-with-kubeadm/` related issue.

**Comment by pytimer** [comment]
@neolit123 OK, sorry to reply late. I will look this issue.

**Comment by pytimer** [comment]
@afagund You follow the document https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster the first step , kubelet still not work? I have already update this document and testing kubelet, it show some flags has been deprecated, but kubelet running. If you use config file, the authorization mode default is webhook. 

Could you try delete config file and follow the setup ha etcd cluster first step to kubelet, and daemon reload and restart kubelet, if it not running, can you support all kubelet log?

**Comment by pytimer** [comment]
@afagund I follow the [setup-ha-etcd-with-kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) document to setup etcd, it works. 

I can't repeat your problem, could you tell me your detailed steps? I will according to your steps try to repeat your problem.
