### ISSUE TITLE
How to refer AWS ECR images in pod

### ISSUE THREAD

**Issue by scingiraj** [kubernetes/kubernetes#79269]
Hello all,

How can we refer images stored in AWS ECR  in the pods rather than pulling the images from dockerbub?
Scenario :  While creating the pod in a AWS Kubernetes cluster, we will create the pod.yaml as below-

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest

Here, we are referring the image nginx to be pulled from Dockerhub. If we want to refer the images which are stored in AWS ECR rather than pulling from docker, how can we do it ?

**Comment by justinsb** [comment]
https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry

> Simply use the full image name (e.g. ACCOUNT.dkr.ecr.REGION.amazonaws.com/imagename:tag) in the Pod definition.
