### ISSUE TITLE
pod cannot support fuse : sys_admin : apparmor:unconfined

### ISSUE THREAD

**Issue by ChenLong2014** [kubernetes/kubernetes#79265]
I use s3fs in the docker, so i try to avoid to use **--privileged**, finally I find the command which is useful to me. 

My docker image is from ubuntu.16.  

> docker run-it  --cap-add SYS_ADMIN  --device /dev/fuse --security-opt apparmor:unconfined

I try to find a YAML , in order to set the command : sys_admin ,fuse ,apparmor:unconfined. But I cannot. So is anyone can help me. how to put the command into the yaml.

apiVersion: v1
kind: Pod
metadata:
  annotations:
	container.apparmor.security.beta.kubernetes.io/notebook: unconfined 
    hub.jupyter.org/username: notebookuser
    kubernetes.io/availablezone: xxxxxxxx
  creationTimestamp: 2019-06-20T13:06:51Z
  labels:
    app: jupyterhub
    component: singleuser-server
    heritage: jupyterhub
  name: jupyter-notebookuser
  namespace: default
  resourceVersion: "4556332"
  selfLink: /api/v1/namespaces/default/pods/jupyter-notebookuser
  uid: 

spec:
  automountServiceAccountToken: false
  containers:
  - env:
    - name: LIMIT_SIZE
      value: "524288000"
    - name: LIMIT_NUMBERS
      value: "1024"
    - name: USER_ENABLE_EVS
      value: "false"
    - name: IS_PRIVILEGED_CONTAINER
      value: "false"
    - name: JUPYTER_ENABLE_OBS
      value: "false"
    - name: USER_STORAGE_CLASS
    - name: USER_STORAGE_CAPACITY
    - name: USER_STORAGE_MOUNT_PATH
    - name: USER_STORAGE_AVAILABLE_ZONE
    - name: NETWORK_TYPE
      value: internal
    - name: PROXY_COMMON
      value: http://www.internal
    image: xxxxxxxxx:xxxx/xxxxxxxxxxxx/s3fs-test:1
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: notebook
    ports:
    - containerPort: 8888
      name: notebook-port
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/fuse
      name: fuse
  volumes:
  - hostPath:
      path: /dev/fuse
      type: ""
    name: fuse
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-secret
  nodeName: 192.168.1.158
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
    runAsUser: 0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-06-20T13:06:51Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-06-20T13:06:54Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-06-20T13:06:51Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://24a837b4af34ff114b27af30de527ffa527ce
    image: xxxxxxxxx:xxxx/xxxxxxxxxxxx/s3fs-test:1
    imageID: docker-pullable://xxxxxxxxx:xxxx/xxxxxxxxxxxx/s3fs-test:1
    lastState: {}
    name: notebook
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-06-20T13:06:53Z
  hostIP: 192.168.1.158
  managementIP: 192.168.1.158
  phase: Running
  podIP: 172.16.0.103
  qosClass: BestEffort
  startTime: 2019-06-20T13:06:51Z

**Comment by ChenLong2014** [comment]
sorry about writing a long YAML.

**Comment by mattjmcnaughton** [comment]
I'll try and take a look at this tomorrow! In the meantime, here is the documentation around capabilities - anything helpful here: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container?

Also, can you please post the failure message you are seeing?

**Comment by ChenLong2014** [comment]
Thanks mattjmcnaughton !
my reference is following:
About docker
[](https://github.com/moby/moby/issues/16233)
[](https://github.com/moby/moby/issues/9448)
About K8S
[](https://stackoverflow.com/questions/51343504/cant-get-container-to-take-apparmor-profile-in-k8s)
[](https://github.com/kubernetes/kubernetes/issues/66216)

I don`t see the POD yaml to solve this problem. Or is there any thing I need to set the k8s?

The error message is :

_**fuse: failed to open /dev/fuse: Operation not permitted.**_
