### ISSUE TITLE
kubectl log/exec failed on container running on worker node

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#79268]
**What happened**:

1. Deploy k8s cluster with 2 machines: a master and a worker. After installation, confirmed everything worked as expected: I was able to kubectl exec into a pod on the worker node.
2. Uninstalled the worker node.
3. Provisioned another worker node with same hsotname, but different IP.
4. The new worker node joined the k8s cluster. Run `kubectl exec -it <pod name> bash` to check log of pod running the worker node. It failed
```
Error from server: error dialing backend: dial tcp 10.21.4.111:10250: connect: connection refused
```

Also get this error in kube-apiserver
```
status.go:64] apiserver received an error that is not an metav1.Status: \u0026errors.errorString{s:\"error dialing backend: dial tcp 10.21.4.111:10250: connect: connection refused\"}\n","stream":"stderr","time":"2019-06-19T20:47:57.317609306Z"
```

Well the node name was still resolved to the old IP. We can confirm from the host the hostname can be resolved to new IP.

Is there any hostname cache in golang?

**What you expected to happen**:

kubectl log/exec should work fine.

**How to reproduce it (as minimally and precisely as possible)**:

See above steps.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.5
- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.06
- Kernel (e.g. `uname -a`):
- Install tools: None
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by liqlin2015** [comment]
sig / node

**Comment by mattjmcnaughton** [comment]
Thanks for your error report here :)

Can you confirm that running `dig` on the hostname in question returns the new IP and not the old IP? I would be decently surprised if there was dns caching going on with k8s... I think its more likely that either your servers/machines, or your dns provider, is doing some caching. Getting the results of a `dig` when this is failing will help us understand it better :)

**Comment by liqlin2015** [comment]
We did not configure DNS to resolve the hostname. Just use the local `/etc/hosts`. And I can confirm `ping` will return the new IP. 
Would like to understand how kubernetes resolve the hostname of worker node?
Forget to mention restart of k8s service will resolve the problem.

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
do you see the same problem with 1.14?

https://github.com/kubernetes/kubernetes/blob/1973373be9b171b31c5b05601a9764c98f0640c9/pkg/registry/core/pod/strategy.go#L487
is where the nodename is resolved.

you mentioned restart k8s service will resolve the probelm, which k8s service you had restarted? could you provide more details?

**Comment by WanLinghao** [comment]
Unset the proxy environment setting and disable firewall, then try again

**Comment by liqlin2015** [comment]
@yliaog We restarted kubelet, kube-scheduler, kube-controller-manager, kube-apiserver.
I have not tried with k8s v1.14.x.

@WanLinghao There is no proxy setting. And why need to disable firewall? We did not enable firewall service.

**Comment by yliaog** [comment]
@liqlin2015 I think restarting kube-apiserver would suffice to fix it,  i.e. kubelet, kube-scheduler, kube-controller-manager do *not* need to be restarted. If this is indeed the case, it means the resolution is cached inside kube-apiserver. how long did you wait before restarting the apiserver? it could be that the cache has a long TTL.
