### ISSUE TITLE
sample-apiserver-deployment does not have minimum availability

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#79271]
**Which jobs are failing**:
When I run the e2e use case, I find an error. Who can help me explain why?

**Which test(s) are failing**:
<*errors.errorString | 0x40001db520>: {
          s: "error waiting for deployment \"sample-apiserver-deployment\" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:\"Available\", Status:\"False\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, Reason:\"MinimumReplicasUnavailable\", Message:\"Deployment does not have minimum availability.\"}, v1.DeploymentCondition{Type:\"Progressing\", Status:\"True\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, Reason:\"ReplicaSetUpdated\", Message:\"ReplicaSet \\\"sample-apiserver-deployment-65db6755fc\\\" is progressing.\"}}, CollisionCount:(*int32)(nil)}",
      }
      error waiting for deployment "sample-apiserver-deployment" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"False", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, Reason:"MinimumReplicasUnavailable", Message:"Deployment does not have minimum availability."}, v1.DeploymentCondition{Type:"Progressing", Status:"True", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63696702699, loc:(*time.Location)(0x81f0100)}}, Reason:"ReplicaSetUpdated", Message:"ReplicaSet \"sample-apiserver-deployment-65db6755fc\" is progressing."}}, CollisionCount:(*int32)(nil)}
  occurred

**Reason for failure**:
Reason:"MinimumReplicasUnavailable"

**Comment by timyinshi** [comment]
we have solve the problem.

**Comment by HasBert** [comment]
@timyinshi Can you provide more information how you solved this issue, please?

**Comment by timyinshi** [comment]
@HasBert  i have a docker proxy to get images from google.com,the error's mean didn't get the e2e images.
