### ISSUE TITLE
Port ranges for ELB SG or allow for main SG to be managed 

### ISSUE THREAD

**Issue by hibbert** [kubernetes/kubernetes#79279]
**What would you like to be added**:

One of either:-

* Allow a port range
* Allow SG to be created and managed outside of k8s and added in, some sort of annotation like service.beta.kubernetes.io/aws-load-balancer-extra-security-groups

**Why is this needed**:

You can end up running into security group rule limits, due to K8S managing the SG for the ELB and adding rules for each specific port

**Comment by justinsb** [comment]
k8s services themselves don't currently support port ranges (I believe), but I think the ask here is for using a single security group per ELB, regardless of the number of ports?

We talked about this in sig-aws, and @randomvariable suggested that you were asking that we combine contiguous port range to reduce the number of security group rules - is that correct?

**Comment by hibbert** [comment]
I think I've found what I wanted here - to allow the SG to be created and managed outside k8s - https://github.com/kubernetes/kubernetes/pull/62774. I didn't know about that at the time, I'm yet to test it.

**Comment by hibbert** [comment]
That doesn't work. Logged https://github.com/kubernetes/kubernetes/issues/79723 for this
