### ISSUE TITLE
[Failing test] GCE-5000: Replication controller having 409 code calls

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#79277]
**Which jobs are failing**:
gce-scale-performance

**Which test(s) are failing**:
Load test

**Since when has it been failing**:
2019-05-28 10:01 CEST (?)

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gce-scale-performance

**Reason for failure**:
It's not failing test. It's an unexpected behavior.

**Anything else we need to know**:
Could be connected with #79096 issue.

**Comment by krzysied** [comment]
![rc_409](https://user-images.githubusercontent.com/25119199/59929503-3c7b2800-9441-11e9-92a1-ec381eacbc1f.png)
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCountByClient&client=kube-controller-manager%2Fv1.16.0%20(linux%2Famd64)%20kubernetes%2Fsystem:serviceaccount:kube-system:replication-controller&code=409&component=apiserver&group=&resource=replicationcontrollers&scope=namespace&subresource=status&verb=PUT&version=v1

The number of 409 calls made by replication controller (manager) has significantly increased.

Cause 409 are resolved by getting current version of rc and updating rc status once again, the number of rc GETs also increased.
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCount&Resource=replicationcontrollers&Scope=namespace&Subresource=&Verb=GET

**Comment by krzysied** [comment]
Because this regression happened between run 1132919740835041284 and 1133282130554523650, it could be connected with #79096.

**Comment by krzysied** [comment]
Apiserver logs:
```
I0620 13:12:30.697232       1 wrap.go:47] PUT /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188/status: (3.655938ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]
I0620 13:12:30.698976       1 wrap.go:47] POST /api/v1/namespaces/test-q6ezwv-27/pods/small-rc-188-b7s6t/binding: (1.85194ms) 201 [kube-scheduler/v1.16.0 (linux/amd64) kubernetes/00e13db/scheduler [::1]:40908]
I0620 13:12:30.703243       1 wrap.go:47] PUT /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188/status: (1.130818ms) 409 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]
I0620 13:12:30.704853       1 wrap.go:47] GET /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188: (1.151205ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]
I0620 13:12:30.708042       1 wrap.go:47] PUT /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188/status: (2.404959ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]
I0620 13:12:30.710568       1 wrap.go:47] POST /api/v1/namespaces/test-q6ezwv-27/pods/small-rc-188-lj5z4/binding: (1.490963ms) 201 [kube-scheduler/v1.16.0 (linux/amd64) kubernetes/00e13db/scheduler [::1]:40908]
I0620 13:12:30.714590       1 wrap.go:47] PUT /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188/status: (1.977434ms) 409 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]
I0620 13:12:30.716165       1 wrap.go:47] GET /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188: (1.007339ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]
I0620 13:12:30.718558       1 wrap.go:47] PUT /api/v1/namespaces/test-q6ezwv-27/replicationcontrollers/small-rc-188/status: (1.556661ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/00e13db/system:serviceaccount:kube-system:replication-controller [::1]:40920]

```

**Comment by krzysied** [comment]
Another example of logs:
```
I0623 16:33:08.311664       1 wrap.go:47] GET /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48: (2.340523ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 104.132.162.78:42114]
I0623 16:33:08.435693       1 wrap.go:47] PATCH /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48: (2.045314ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 104.132.162.78:42114]
I0623 16:33:08.445386       1 wrap.go:47] PUT /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48/status: (1.829626ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/da31c50/system:serviceaccount:kube-system:replication-controller [::1]:36814]
I0623 16:33:08.452008       1 wrap.go:47] PUT /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48/status: (1.184788ms) 409 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/da31c50/system:serviceaccount:kube-system:replication-controller [::1]:36814]
I0623 16:33:08.453400       1 wrap.go:47] GET /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48: (842.814µs) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/da31c50/system:serviceaccount:kube-system:replication-controller [::1]:36814]
I0623 16:33:08.456359       1 wrap.go:47] PUT /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48/status: (2.265389ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/da31c50/system:serviceaccount:kube-system:replication-controller [::1]:36814]
I0623 16:33:12.913292       1 wrap.go:47] PUT /api/v1/namespaces/test-g58duf-48/replicationcontrollers/small-rc-48/status: (6.134788ms) 200 [kube-controller-manager/v1.16.0 (linux/amd64) kubernetes/da31c50/system:serviceaccount:kube-system:replication-controller [::1]:36814]
```
The two first lines are calls form cluster loader that change replicas from 5 to 6.

It looks like there is always two status updates calls. Maybe this 409 is cause by raced condition...
Replciation controller has [many workers](https://github.com/kubernetes/kubernetes/blob/3bd11af6a18d8ebaa3a0aeb2e66c2bb6f260b069/pkg/controller/replicaset/replica_set.go#L189). Assuming that there are two items with the same key in queue, they can be processed by two different workers. There is no lock before [getting rc](https://github.com/kubernetes/kubernetes/blob/3bd11af6a18d8ebaa3a0aeb2e66c2bb6f260b069/pkg/controller/replicaset/replica_set.go#L573) which can result in two [rc status updates](https://github.com/kubernetes/kubernetes/blob/3bd11af6a18d8ebaa3a0aeb2e66c2bb6f260b069/pkg/controller/replicaset/replica_set.go#L615) made at the same time for one rc.

**Comment by krzysied** [comment]
Assuming that race condition was always in replication controller code, it doesn't explained the reason for increased number of 409 calls. IMHO the update calls latency increased (milliseconds) or rc events are more grouped than they used to.

**Comment by alenkacz** [comment]
@krzysied is there anything we can do to prove that hypothesis or remove the flakiness?

**Comment by krzysied** [comment]
IMHO the best way is to remove the race condition and check if it fixes the problem. IIRC the controller has many workers and two of the them can handle requests for the some rc. We could use the same logic as in [taint manager](https://github.com/kubernetes/kubernetes/blob/5de41340ce3917ab948573f6358b10512a0333ce/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L191) so we ensure that all items related to one rc are processed by the same worker.

This can potentially remove the 409 calls, however it doesn't answer the question why the call characteristic changed...

**Comment by krzysied** [comment]
I created #80319 for the testing purpose. Let's see if it will reduce the number of 409 calls.

**Comment by krzysied** [comment]
Based on results from #80319 race condition is not a problem here... I haven't spotted any difference in number of the 409 calls :/
