### ISSUE TITLE
Return boolean to not scale instead of current scale.

### ISSUE THREAD

**Issue by josephburnett** [kubernetes/kubernetes#79275]
**What would you like to be added**:

The HPA replica calculator takes the current replica count as a function input.  If it determines no change to scale is needed, it returned the current replica count as a recommendation.

https://github.com/kubernetes/kubernetes/blob/737d74d12de86481b17d2f361edd70b26580b139/pkg/controller/podautoscaler/replica_calculator.go#L191-L194

I would prefer to return a boolean to indicate that no change is needed.

**Why is this needed**:

This is needed because it requires plumbing the current replica count (from spec) through many layers, just so the calculator can use it to punt on a scaling decision.  This leaves an opportunity to return the wrong value (e.g. replica count from status) which is the root cause of a runaway autoscaler bug: https://github.com/kubernetes/kubernetes/pull/79035.

**Comment by tedyu** [comment]
Something like this (handling of the boolean by the caller is to be plugged in) ?
```
diff --git a/pkg/controller/podautoscaler/replica_calculator.go b/pkg/controller/podautoscaler/replica_calculator.go
index d479a4edd8..ff5f2562b2 100644
--- a/pkg/controller/podautoscaler/replica_calculator.go
+++ b/pkg/controller/podautoscaler/replica_calculator.go
@@ -147,7 +147,7 @@ func (c *ReplicaCalculator) GetRawResourceReplicas(currentReplicas int32, target
                return 0, 0, time.Time{}, fmt.Errorf("unable to get metrics for resource %s: %v", resource, err)
        }

-       replicaCount, utilization, err = c.calcPlainMetricReplicas(metrics, currentReplicas, targetUtilization, namespace, selector, resource)
+       replicaCount, utilization, err, _ = c.calcPlainMetricReplicas(metrics, currentReplicas, targetUtilization, namespace, selector, resource)
        return replicaCount, utilization, timestamp, err
 }

@@ -160,27 +160,27 @@ func (c *ReplicaCalculator) GetMetricReplicas(currentReplicas int32, targetUtili
                return 0, 0, time.Time{}, fmt.Errorf("unable to get metric %s: %v", metricName, err)
        }

-       replicaCount, utilization, err = c.calcPlainMetricReplicas(metrics, currentReplicas, targetUtilization, namespace, selector, v1.ResourceName(""))
+       replicaCount, utilization, err, _ = c.calcPlainMetricReplicas(metrics, currentReplicas, targetUtilization, namespace, selector, v1.ResourceName(""))
        return replicaCount, utilization, timestamp, err
 }

 // calcPlainMetricReplicas calculates the desired replicas for plain (i.e. non-utilization percentage) metrics.
-func (c *ReplicaCalculator) calcPlainMetricReplicas(metrics metricsclient.PodMetricsInfo, currentReplicas int32, targetUtilization int64, namespace string, selector labels.Selector, resource v1.ResourceName) (replicaCount int32, utilization int64, err error) {
+func (c *ReplicaCalculator) calcPlainMetricReplicas(metrics metricsclient.PodMetricsInfo, currentReplicas int32, targetUtilization int64, namespace string, selector labels.Selector, resource v1.ResourceName) (replicaCount int32, utilization int64, err error, noChange bool) {

        podList, err := c.podLister.Pods(namespace).List(selector)
        if err != nil {
-               return 0, 0, fmt.Errorf("unable to get pods while calculating replica count: %v", err)
+               return 0, 0, fmt.Errorf("unable to get pods while calculating replica count: %v", err), true
        }

        if len(podList) == 0 {
-               return 0, 0, fmt.Errorf("no pods returned by selector while calculating replica count")
+               return 0, 0, fmt.Errorf("no pods returned by selector while calculating replica count"), true
        }

        readyPodCount, ignoredPods, missingPods := groupPods(podList, metrics, resource, c.cpuInitializationPeriod, c.delayOfInitialReadinessStatus)
        removeMetricsForPods(metrics, ignoredPods)

        if len(metrics) == 0 {
-               return 0, 0, fmt.Errorf("did not receive metrics for any ready pods")
+               return 0, 0, fmt.Errorf("did not receive metrics for any ready pods"), true
        }

        usageRatio, utilization := metricsclient.GetMetricUtilizationRatio(metrics, targetUtilization)
@@ -190,11 +190,11 @@ func (c *ReplicaCalculator) calcPlainMetricReplicas(metrics metricsclient.PodMet
        if !rebalanceIgnored && len(missingPods) == 0 {
                if math.Abs(1.0-usageRatio) <= c.tolerance {
                        // return the current replicas if the change would be too small
-                       return currentReplicas, utilization, nil
+                       return currentReplicas, utilization, nil, true
                }

                // if we don't have any unready or missing pods, we can calculate the new replica count now
-               return int32(math.Ceil(usageRatio * float64(readyPodCount))), utilization, nil
+               return int32(math.Ceil(usageRatio * float64(readyPodCount))), utilization, nil, false
        }

        if len(missingPods) > 0 {
@@ -224,12 +224,12 @@ func (c *ReplicaCalculator) calcPlainMetricReplicas(metrics metricsclient.PodMet
        if math.Abs(1.0-newUsageRatio) <= c.tolerance || (usageRatio < 1.0 && newUsageRatio > 1.0) || (usageRatio > 1.0 && newUsageRatio < 1.0) {
                // return the current replicas if the change would be too small,
                // or if the new usage ratio would cause a change in scale direction
-               return currentReplicas, utilization, nil
+               return currentReplicas, utilization, nil, true
        }

        // return the result, where the number of replicas considered is
        // however many replicas factored into our calculation
-       return int32(math.Ceil(newUsageRatio * float64(len(metrics)))), utilization, nil
+       return int32(math.Ceil(newUsageRatio * float64(len(metrics)))), utilization, nil, false
 }

 // GetObjectMetricReplicas calculates the desired replica count based on a target metric utilization (as a milli-value)
```

**Comment by tedyu** [comment]
It seems GetRawResourceReplicas and GetMetricReplicas pass the return values from calcPlainMetricReplicas to their callers.
The boolean return would need to be surfaced from these two func's as well.

**Comment by josephburnett** [comment]
@draveness if you plan to work on this, let's coordinate.  I have a more complete change for #79035 which uses types to keep spec replicas separate from status replicas.

**Comment by draveness** [comment]
> @draveness if you plan to work on this, let's coordinate. I have a more complete change for #79035 which uses types to keep spec replicas separate from status replicas.

I think that one would cover this issue. what do you think of closing this?

**Comment by josephburnett** [comment]
The HPA runaway bug was because we got spec and status replicas confused.  We returned status replicas to maintain the current scale, which causes when there are more Pods than we asked for (e.g. during a Deployment update).

We really should return a boolean instead of plumbing through the current scale.  I didn't want to include that in #79035 because it would make the change **much** larger.  I already pared it down quite a bit so it could be back ported.

I think we should still implement this boolean change to make the code easier to understand and safer.

**Comment by draveness** [comment]
> The HPA runaway bug was because we got spec and status replicas confused. We returned status replicas to maintain the current scale, which causes when there are more Pods than we asked for (e.g. during a Deployment update).
> 
> We really should return a boolean instead of plumbing through the current scale. I didn't want to include that in #79035 because it would make the change **much** larger. I already pared it down quite a bit so it could be back ported.
> 
> I think we should still implement this boolean change to make the code easier to understand and safer.

SGTM, I could send a PR later after yours get merged. What do you think?

**Comment by josephburnett** [comment]
If you have time to work on this issue, I recommend doing so right after #79035 merges.  I'll wait to submit my spec/status type change until after you fix this issue.  So please, go first.  :)

**Comment by draveness** [comment]
> If you have time to work on this issue, I recommend doing so right after #79035 merges. I'll wait to submit my spec/status type change until after you fix this issue. So please, go first. :)

Hi Joseph, you could take it over if you want, I don't want to block your work. 😁

**Comment by josephburnett** [comment]
You wouldn't be blocking my work.  I have many other things to do related to these problems.  Such as backporting #79035 to previous k8s versions.  Writing an E2E test to guard against this in the future.  And fixing another stuck HPA bug (https://github.com/kubernetes/kubernetes/issues/79158).  Your help would be welcome.  Go ahead!

**Comment by draveness** [comment]
Hi, I tried to populate the boolean value bottom-up, but the code does not look good and seems redundant. I don't feel like it is a good idea. Please feel free to take it over.

/unassign

**Comment by josephburnett** [comment]
Thanks @draveness for taking a look.  Can you show me the code?  Could be useful to see what not to do.

**Comment by draveness** [comment]
> Thanks @draveness for taking a look. Can you show me the code? Could be useful to see what not to do.

There are ~10 methods that need to update the return value and argument, and what it brings is less than the complexity and work we do for this IMO.
