### ISSUE TITLE
Some kubelet metrics use non-standard prometheus collectors unnecessarily

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#79286]
Some kubelet metrics use non-standard prometheus collectors unnecessarily. Specifically, we have [two metrics `running_pod_count` and `running_container_count`](https://github.com/kubernetes/kubernetes/blob/v1.15.2/pkg/kubelet/metrics/metrics.go#L430-L439) which can be simple gauges. Since we cannot migrate non-standard prometheus collectors using the internal metrics stability framework, we will need to convert these metrics into standard prometheus variants. 

/sig instrumentation
/assign @solodov

**Comment by logicalhan** [comment]
@dashpole recommends that we generate those metrics in the GenericPLEG during the relist. We can generate the data directly from the pods call there (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go#L211).

**Comment by irajdeep** [comment]
@logicalhan I would be interested to work on this issue if no one else is

**Comment by logicalhan** [comment]
Go for it!
