### ISSUE TITLE
Master service of type ExternalName doesn't set correct environment variables

### ISSUE THREAD

**Issue by mvladev** [kubernetes/kubernetes#79280]
**What happened**:

`kube-apiserver` is running with turned off master endpoint reconciler:

```
--endpoint-reconciler-type=none
```

The master (`default/kubernetes`) service is created manually with `type: ExternalName`:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
spec:
  clusterIP: ""
  type: ExternalName
  externalName: api.127.0.0.1.nip.io
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
```

A new Pod is created in some namespace and then environment variables are checked:

```console
$ kubectl create namespace baz

$ kubectl -n baz run busybox --restart=Never -it --image=alpine --generator="run-pod/v1" sh
If you don't see a command prompt, try pressing enter.
/ # env
HOSTNAME=busybox
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
````

**What you expected to happen**:

`KUBERNETES_SERVICE_PORT` and `KUBERNETES_SERVICE_HOST` environment variables to be set like so:

```console
/# env

KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://api.127.0.0.1.nip.io:443
HOSTNAME=busybox
SHLVL=1
HOME=/root
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=api.127.0.0.1.nip.io
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://api.127.0.0.1.nip.io443
KUBERNETES_SERVICE_HOST=api.127.0.0.1.nip.io
```

**How to reproduce it (as minimally and precisely as possible)**:

execute steps from above.

**Anything else we need to know?**:

Accessing the Master API via `kubernetes.default.svc.cluster.local` is successful. 
The annoying part is that controllers written with client-go are explicitly checking for those 2 [environment variables](https://github.com/kubernetes/kubernetes/blob/05b764dbe3e0f979f1d17293a13bafda688d5951/staging/src/k8s.io/client-go/rest/config.go#L404-L408) and refusing to start even if they are running `inCluster`.

This defect is caused by several checks in the Pod environment creation:
https://github.com/kubernetes/kubernetes/blob/9050c510e640f325d008792a517fe85808b34150/pkg/kubelet/kubelet_pods.go#L517-L520

The previous check should be moved after this
https://github.com/kubernetes/kubernetes/blob/9050c510e640f325d008792a517fe85808b34150/pkg/kubelet/kubelet_pods.go#L523-L530

And after all services are collected, environment variables are created and again services without `ClusterIP` are ignored:
https://github.com/kubernetes/kubernetes/blob/012b085ac870d359131f4251213bf2fff1d15aa0/pkg/kubelet/envvars/envvars.go#L29-L42

And finally `ClusterIP` is used to populate the `_HOST` env: 
https://github.com/kubernetes/kubernetes/blob/012b085ac870d359131f4251213bf2fff1d15aa0/pkg/kubelet/envvars/envvars.go#L44-L45

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

/sig node

**Comment by mattjmcnaughton** [comment]
@mvladev thanks for your detailed issue report!

It seems like you have a good idea of a potential fix. Do you have the capacity/interest for doing a quick [WIP] so we can take a look at some code?

**Comment by mvladev** [comment]
@mattjmcnaughton I've the fix ready, just need to adapt the fix. I'll probably fire a PR tomorrow

**Comment by mattjmcnaughton** [comment]
Wonderful - let some comments on your pr!
