### ISSUE TITLE
How can I find PodSpecs object?

### ISSUE THREAD

**Issue by hamiBU** [kubernetes/kubernetes#79281]
I'm trying to find PodSpecs struct object in [kubernetes GitHu](https://github.com/kubernetes/kubernetes)b. Where is its exact place?

**Comment by almiche** [comment]
Hi there I just took a quick look is this what you're looking for by chance ?
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2816

**Comment by liggitt** [comment]
Yes, that's the PodSpec definition

/close
