### ISSUE TITLE
`kubectl get crd` should show more info

### ISSUE THREAD

**Issue by dungdm93** [kubernetes/kubernetes#79299]
It would be nice if `kubectl get crd` show more useful information by default suck as `apiVersion`, `kind`, `scope` like:
![crd](https://user-images.githubusercontent.com/6848311/59966325-35d5d900-9545-11e9-8ccd-548aa78235e5.png)

My custom columns file: `crd.columns`
```
NAME            GROUP        VERSION        KIND              SCOPE        CREATED_AT
.metadata.name  .spec.group  .spec.version  .spec.names.kind  .spec.scope  .metadata.
```

```yaml
kubectl get crd -o custom-columns-file=crd.columns --sort-by=.spec.group
```
@kubernetes/sig-cli
/sig cli

**Comment by MartinKaburu** [comment]
cc @soltysh  @seans3 @mengqiy I would like to take this
