### ISSUE TITLE
TestBindPlugin is flaky

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#79297]
**Which jobs are failing**:

pull-kubernetes-integration

**Which test(s) are failing**:

TestBindPlugin

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79293/pull-kubernetes-integration/1142426772172705796/

**Reason for failure**:

```
framework_test.go:788: test #3: Expected the unreserve plugin to be called once, was called 34 times.
```

**Comment by draveness** [comment]
/kind flaky
/sig scheduling

cc/ @chenchun @bsalamat

**Comment by chenchun** [comment]
I'll take a look
