### ISSUE TITLE
Cleanup feature gates which should be removed in 1.16

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#79308]
The features flag below should be removed from the codebase.

- [x] 508:	HugePages https://github.com/kubernetes/kubernetes/pull/79307
- [x] 523:	VolumeScheduling https://github.com/kubernetes/kubernetes/pull/79307
- [ ] 524:	CSIPersistentVolume https://github.com/kubernetes/kubernetes/pull/79309
- [x] 527:	CustomPodDNS https://github.com/kubernetes/kubernetes/pull/79307
- [x] 550:	PodReadinessGates https://github.com/kubernetes/kubernetes/pull/79307
- [x] 552:	KubeletPluginsWatcher https://github.com/kubernetes/kubernetes/pull/79310

**Comment by draveness** [comment]
/assign
/priority important-soon
/sig release // not sure, feel free to remove this

**Comment by BenTheElder** [comment]
/retitle Cleanup feature gates which should be removed in 1.16
I saw this issue and thought we were removing the features themselves 😅

**Comment by draveness** [comment]
> /retitle Cleanup feature gates which should be removed in 1.16
> I saw this issue and thought we were removing the features themselves 😅

Sorry for that 🤣
