### ISSUE TITLE
Upgrade coredns to v1.4.0 or v1.5.0

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#79319]
Disclaimer: this was originally reported at https://github.com/kubernetes/kubernetes/issues/78003, yet it should be reopened, since the PR was reverted.

**What would you like to be added**:
A newer version of coredns

**Why is this needed**:
Currently shipped v1.3.1 is affected by https://github.com/coredns/coredns/issues/2629 issue, which causes the cluster outage if API server goes away temporarily.

**Comment by draveness** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/78033

**Comment by mattjmcnaughton** [comment]
Here's the reverted diff for context :) https://github.com/kubernetes/kubernetes/pull/78030

**Comment by aojea** [comment]
I think this can be closed, current CoreDNS version is 1.6.2 https://github.com/kubernetes/kubernetes/pull/82127

**Comment by zerkms** [comment]
Indeed, upgrading my cluster at the moment actually :-)
