### ISSUE TITLE
Kubelet: Support extended system info

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubernetes#79323]
**What would you like to be added**:

Kubelet can support add extend system info, such as ipmi information.

**Why is this needed**:

Now i want to add other system info in node information. But i found it only add labels or annotations to do it, is it have another way to do it or kubelet can support add extend system info?

**Comment by mattjmcnaughton** [comment]
Hi @pytimer :)

Thanks for your idea - could you maybe share a little more about what you mean by "supporting" extended system info? What does "support" mean in this context?

**Comment by pytimer** [comment]
I want to add custom system info when kubelet register the node, such as ipmi IP address and gateway, and I can use `kubectl describe nodes` to show this information easily,. Now I have to use labels and annotations to do it, it not very convenient and it make node have too many labels or annotations, so i think kubelet support add custom system info. 
I am not sure if I explain clearly.

**Comment by pacoxu** [comment]
> I want to add custom system info when kubelet register the node, such as ipmi IP address and gateway, and I can use `kubectl describe nodes` to show this information easily,. Now I have to use labels and annotations to do it, it not very convenient and it make node have too many labels or annotations, so i think kubelet support add custom system info.
> I am not sure if I explain clearly.

-  kubelet can update node info with ipmi info like BCM ip(xclarity ip in Lenovo).
-  controller-manager or standalone monitor system can get the server info from the BCM(the secret need to be provide in specified secret), so that the node can be drained once it is power off for some reason quickly.(No need to wait for 5minutes)
