### ISSUE TITLE
run k8s 1.14.3 version e2e test etcd failed on arm64

### ISSUE THREAD

**Issue by xieyanker** [kubernetes/kubernetes#79325]
I installed a k8s cluster, which version is 1.14.3 on arm64. 
Then I runned e2e test failed at `"Should be able to support the 1.10 Sample API Server using the current Aggregator"`.
I found it used etcd's image version `quay.io/coreos/etcd:v3.3.10`, I executed `docker run quay.io/coreos/etcd:v3.3.10`  manually, I got `standard_init_linux.go:185: exec user process caused "exec format error"`;
Then I pulled image version `quay.io/coreos/etcd:v3.3.10-arm64` , I executed `docker run quay.io/coreos/etcd:v3.3.10-arm64`, I got `2019-06-24 02:33:09.582058 E | etcdmain: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set.`;
Finally, I executed `docker run --env ETCD_UNSUPPORTED_ARCH=arm64 quay.io/coreos/etcd:v3.3.10-arm64`, it succeeded.
So, I think `quay.io/coreos/etcd:v3.3.10` image is not suppoted to arm64.

**Comment by BenTheElder** [comment]
cc @lubinsz

**Comment by xieyanker** [comment]
The latest version has resolved this issue, The image `quay.io/coreos/etcd:v3.3.10` has been replaced by `gcr.io/google-containers/etcd:3.3.10`. https://github.com/kubernetes/kubernetes/pull/76136/files, and I will close this issue.
