### ISSUE TITLE
StatefulSet may need specical method of generating pod name  

### ISSUE THREAD

**Issue by yuyulei** [kubernetes/kubernetes#79337]
**What happened**:
The problem was found in [issue#64023](https://github.com/kubernetes/kubernetes/issues/64023). 

There are three "invalid" questions: 
1. "invalid" label value: the value of label: "controller-revision-hash" exceeds length limition(63) 
2. "invliad" hostname: the field of pod: `.spec.hostname` exceeds length limition(63)
3. "invalid" label value: `statefulset.kubernetes.io/pod-name`(similar to 2)

### for Q1

I try DaemonSet, Because DaemoSet and StatefulSet are both using ControllerRevision. But their labels: "controller-revision-hash" are different:

```
// in StatefulSet pod's Labels:
"controller-revision-hash": "<statefulset_name>-<hash>"

// in DaemonSet pod's Labels:
"controller-revision-hash": "<hash>"
```
So DaemonSet has not above problem.

**Can we make statefulset pod's Label("controller-revision-hash") form "<statefulset_name>-hash" to "hash".** 

I think it also works if we do some adjusting code.

On the other hand, it is better to make the format of label: "controller-revision-hash" consistent. Today only statefulset and daemonset, maybe other resource using controllerrevisions later.

### for Q2

The root cause is statefulset pod's naming.
when DaemonSet creating pod, it will not set pod's name. So pod' name will generated from `GenerateName`. If DaemonSet's name is close to maxlength, like `abcedef-1-abcedef-2-abcedef-3-abcedef-4-abcedef-5-abcedefg-6-123`, the created pod's name will truncate first 58 bytes, so pod' name equals to:

```
"<truncted generate name>-hash"  
```
from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/names/generate.go#L51

But Statefulset creating pod, it will set pod's name[set pod name](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_utils.go#L258). The pod name will be `<statefulset name>-<ordinal>`, and can exceed 63 characters.

It produce some problems, like above:

```
spec.hostname: Invalid value: "abcedefg-1-abcedefg-2-abcedefg-3-abcedefg-4-abcedefg-5-abcedefg-6-0": must be no more than 63 characters
```
At this time, simple truncating does not work, Because statefulset pod' name end in "<ordinal>" not "hash". I think we may need a statefulset NameGenerator.

Given statefulset with name `abcedef-1-abcedef-2-abcedef-3-abcedef-4-abcedef-5-abcedef-6-0-123`(63 characters), My idea is to generate pod name by:
1. statefulset name prefix(55bytes)
2. statefulset name hash(6tytes)
3. ordinal

like  `abcedef-1-abcedef-2-abcedef-3-abcedef-4-abcedef-5-abcedef-6-abcdeqazwsx-0`

Does it work?

**What you expected to happen**:
If I can crate a statefulset, I hope the statefulset can create its pods. We may need special NameGenerator for StatefulSet.

**How to reproduce it (as minimally and precisely as possible)**:
Try to create statefulset with long name, like 63 characters.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux 4.18.8-1.el7.elrepo.x86_64 #1 SMP Sat Sep 15 10:10:09 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by yuyulei** [comment]
@kubernetes/sig-apps-bugs

**Comment by kow3ns** [comment]
For Q1, yes, that is something we can explore.
For Q2, no, there is too much in the ecosystem the depends on the current naming convention.
Do you want to open a PR to attempt to address Q1?

**Comment by yuyulei** [comment]
ok I try it

**Comment by czheng94** [comment]
Any update on this issue?
I have also been bothered by the same problem. Will be great if we can just apply what's described in Q1, and make the hash label values consistent for both daemonset and statefulset.

```
"controller-revision-hash": "<hash>"
```

**Comment by sparty02** [comment]
bump, we are still running into this issue
