### ISSUE TITLE
Kubectl logs should be able to retrieve and filter logs

### ISSUE THREAD

**Issue by huzy96** [kubernetes/kubernetes#79336]
When I used sonobuoy for Software conformance, the following failures occurred
```
• Failure [10.441 seconds]
[sig-cli] Kubectl client
/workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/framework.go:23
  [k8s.io] Kubectl logs
  /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:687
    should be able to retrieve and filter logs  [Conformance] [It]
    /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:692

    Expected
        <int>: 21
    to equal
        <int>: 1

    /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1232
```

Kubernetes version (use kubectl version): v1.14.3&v1.13.1
OS :CentOS Linux release 7.6.1810 (Core)
Kernel (e.g. uname -a):Linux node 3.10.0-957.21.3.el7.x86_64 
Install tools:kubeadm

This problem has been mentioned on [this page](https://github.com/kubernetes/kubernetes/issues/20224), but it has been solved.
Why did I encounter this problem?
Who can help me with this? I'm very grateful.

**Comment by GitHubxsy** [comment]
+1

**Comment by GitHubxsy** [comment]
set docker-daemon  log-driver=json-file

**Comment by huzy96** [comment]
Thank you very much for helping me solve this problem. @GitHubxsy
