### ISSUE TITLE
`vendor/modules.txt` is hot for conflicts and approval bottleneck

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#79347]
Any package change in a staging repository has to include its new packages in `vendor/modules.txt` which creates a bottleneck for conflicts and approval.

Can we split the file so that various parts can be owned by different groups of people?

/assign @liggitt

**Comment by liggitt** [comment]
> Can we split the file so that various parts can be owned by different groups of people?

the file is generated by `go mod vendor`, so no

**Comment by BenTheElder** [comment]
implementation here fur the curious 🙃 https://github.com/golang/go/blob/6f7542e4cb6914e8b8d888f16d440feeb8e631d2/src/cmd/go/internal/modcmd/vendor.go#L90

**Comment by apelisse** [comment]
@BenTheElder Do we have a way to relax approvals on this file?

**Comment by BenTheElder** [comment]
No :| https://github.com/kubernetes/test-infra/issues/7690

**Comment by nikhita** [comment]
> Do we have a way to relax approvals on this file?

That file doesn't need top-level approval though. `dep-approvers` should be able to approve that: https://github.com/kubernetes/kubernetes/blob/master/vendor/OWNERS

**Comment by BenTheElder** [comment]
@nikhita right, but in this case it's not actually a dependency change, it's a staging change, which otherwise has a different set of approvers?

**Comment by nikhita** [comment]
Ah ok, unfortunately this won't be solved by https://github.com/kubernetes/test-infra/issues/7690 though because that'll only allow to separate approvers for different files in a directory...and I don't think we can split `vendor/modules.txt`. :/

**Comment by BenTheElder** [comment]
we could expand the set of approvers just for that file that to be dep-approvers OR staging approvers, seeing as that file is autogenerated anyhow and actual vendor changes would include other files, but not without the test-infra fix.
