### ISSUE TITLE
vmware multiple nics

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#79340]
**What happened**:

When I enable the vmware cloud provider on my vmware based Kubernetes, I see multiple entries for addresses:
  - address: <IP1>
    type: ExternalIP
  - address: <IP1>
    type: InternalIP
  - address: <IP2>
    type: ExternalIP
  - address: <IP1>
    type: InternalIP
  - address: <NodeName>
    type: Hostname

<IP1> <IP2> <NodeName> changed to protect the innocent.

**What you expected to happen**:
There to only be one ExternalIP and InternalIP.

**How to reproduce it (as minimally and precisely as possible)**:
I launched a cluster with a frontend network, and a backend network with higher mtu for vxlan traffic. I enabled the vmware driver and multiple ExternalIP's and InternalIP's show up. With the driver disabled, it only has one of each.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
vmware

- OS (e.g: `cat /etc/os-release`):
 rhel 7.6

- Kernel (e.g. `uname -a`):
Linux ektm0 3.10.0-957.12.1.el7.x86_64 #1 SMP Wed Mar 20 11:34:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
canal

- Others:

**Comment by kfox1111** [comment]
@kubernetes/sig-node-bugs
@kubernetes/sig-vmware-bugs

**Comment by kfox1111** [comment]
@kubernetes/sig-node-bugs, @kubernetes/sig-vmware-bugs

**Comment by kfox1111** [comment]
so, it looks like there is a Network section in vsphere.conf. but it isn't applied, as kubelet doesn't have it anymore. (or the docs say not to use it).

Looks like its going through:
func getLocalIP() ([]v1.NodeAddress, error) in pkg/cloudprovider/providers/vsphere/vsphere.go
Which does just add all found vmware nics. No filtering.

**Comment by kfox1111** [comment]
Looks like even specifying the vsphere.conf, it will skip the public_network filter.

**Comment by kfox1111** [comment]
A workaround seems to be to change the mac address to not be a vmware mac address on the secondary nic. The vmware driver then filters it out, and all seems happy.

**Comment by mattjmcnaughton** [comment]
For now, I'm going to remove sig-node, as it most likely makes sense to begin the triage with sig-vmware. But please feel free to add sig-node back if that could be helpful.

/remove-sig node
