### ISSUE TITLE
flaky TestWebhookConverter tests

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#79358]
**Which jobs are failing**: `pull-kubernetes-integration`

**Which test(s) are failing**: `TestWebhookConverter.*` tests are very flaky (**the** most flaky presubmits currently) http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

**Since when has it been failing**:

**Testgrid link**: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestWebhook

**Reason for failure**:

**Anything else we need to know**: 
Examples: 
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79316/pull-kubernetes-integration/1143311633943105537/
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79317/pull-kubernetes-integration/1143352905730887683/

**Comment by BenTheElder** [comment]
cc @sttts @liggitt

**Comment by BenTheElder** [comment]
This is also https://github.com/kubernetes/kubernetes/issues/79177

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/78913

fix in progress in https://github.com/kubernetes/kubernetes/issues/78913

**Comment by BenTheElder** [comment]
thanks! will close out https://github.com/kubernetes/kubernetes/issues/79177 as well
