### ISSUE TITLE
Incorrect max length check on metadata.name

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kubernetes#79351]
**What happened**:
As far as I know metadata.name can be one or more DNS labels separated by dots (.) with the following constraints on max length: 1) each label has a max length of 63 characters 2) the maximum number of characters for the name (aka DNS subdomain) is 253 characters. 

I did a couple of tests using v1.15.0 and max length for label is not respected

**What you expected to happen**:
I was able to successfully create a pod with a name with a single label with 64 and 72 characters.
See pod-name-15.pdf for example of manifest YAML file.
kubectl responded as follows:
pod/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx64 created

The expected outcome is an error.

[pod-name-15.pdf](https://github.com/kubernetes/kubernetes/files/3322625/pod-name-15.pdf)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

@kubernetes/sig-cli
/sig cli

@kubernetes/sig-api-machinery
/sig api-machinery

**Comment by janetkuo** [comment]
> The Pod "xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxx75" is invalid: metadata.name: Invalid value: "xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxx75": a DNS-1123 subdomain must consist of lowercase alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(.a-z0-9?)*')

I think it's because "xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxxxx. xxxxxxxx75" contains space, which isn't allowed.

**Comment by stevebail** [comment]
Yes my bad. The first problem is still valid

**Comment by stevebail** [comment]
I have updated the problem description. Thanks Janet!

**Comment by janetkuo** [comment]
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names:
> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

DNS-1123 subdomain allows up to 253 char. 

63 char is the limit for DNS labels, e.g. for metadata.labels https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

**Comment by stevebail** [comment]
DNS labels are different from k8s labels.

Directly from k8s identifier spec:

1) When an object is created via an API, a Name string (a DNS_SUBDOMAIN) must be specified.
2) rfc1035/rfc1123 DNS subdomain (DNS_SUBDOMAIN) : One or more lowercase rfc1035/rfc1123 labels separated by '.' with a maximum length of 253 characters
3) rfc1035/rfc1123 DNS label (DNS_LABEL) : An alphanumeric (a-z, and 0-9) string, with a maximum length of 63 characters, with the '-' character allowed anywhere except the first or last character, suitable for use as a hostname or segment in a domain name

https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/design/identifiers.md

**Comment by BenTheElder** [comment]
> 1. When an object is created via an API, a Name string (a DNS_SUBDOMAIN) must be specified.

this is `metadata.name` (see the https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names link or https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#required-fields)

> 2. rfc1035/rfc1123 DNS subdomain (DNS_SUBDOMAIN) : One or more lowercase rfc1035/rfc1123 labels separated by '.' with a maximum length of 253 characters

So 253 characters are allowed (as @janetkuo said above).

---- 

> https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/design/identifiers.md 

The current link is https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md (linked to from the names docs)

**Comment by stevebail** [comment]
Let me try to clarify one last time.
Yes I understand that metadata.name is a DNS_Sudomain and it has a max length of 253 characters.
This is constraint #1.
No problem here. So far so good.

However, the DNS _Subdomain is also made of one or more DNS Labels and each DNS Label must have a max length of 63 characters. This is constraint #2.
This is the part that k8s is not following.

As far as I know both constraints must be followed.

Do you have a different interpretation? 
If so, then we should consider updating identifiers.md.

**Comment by BenTheElder** [comment]
Aha! Thank you very much for clarifying again, your point is much clearer 🙃 

I do not have a different interpretation but will defer to @janetkuo / api-machinery.
imho we should absolutely see this clarified or the check adjusted.

**Comment by liggitt** [comment]
this is a bug in IsDNS1123Subdomain, which uses a dns1123SubdomainFmt regex, which checks one or more dns1123LabelFmt regexes. dns1123LabelFmt limits allowed characters, but not length. It depended on the IsDNS1123Label() function separately checking length restrictions.

That said, at this point, we cannot tighten that validation, since there are existing persisted objects that could be made invalid. The best we can do is to document the error, and fix the bug for new API types.

**Comment by BenTheElder** [comment]
/kind documentation
ACK @liggitt, Let's get it documented then?

**Comment by amalts** [comment]
@BenTheElder @liggitt  I would like to take this as my first issue. Can i get some pointers to the documentation part?

**Comment by BenTheElder** [comment]
@amalts probably at least https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md (https://github.com/kubernetes/kubernetes/issues/79351#issuecomment-505278296) should be updated

**Comment by tedyu** [comment]
@amalts 
do you plan to work on this ?
