### ISSUE TITLE
TypedLocalObjectReference APIGroup should have omitempty

### ISSUE THREAD

**Issue by vincepri** [kubernetes/kubernetes#79354]
**What happened**:
[TypedLocalObjectReference](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4626-L4638) has `APIGroup` as a `*string` and marked as `+optional` without `omitempty` in the json tag directive. 

While using this type in Cluster API, instead of ObjectReference, omitting the APIGroup results in this error: `spec.infrastructureRef.apiGroup in body must be of type string: "null"`.

**What you expected to happen**:
The field in `TypedLocalObjectReference` can be made `omitempty`.

**How to reproduce it (as minimally and precisely as possible)**:
- Use a type with `TypedLocalObjectReference` 
- Use a go client to talk to the api-server to create a simple object without specifying APIGroup (which is optional)

**Anything else we need to know?**:

Request/Response to/from the api-server:
```
I0624 15:41:55.082575   88363 request.go:942] Request Body: {"kind":"Machine","apiVersion":"cluster.k8s.io/v1alpha2","metadata":{"name":"foo","namespace":"default","creationTimestamp":null},"spec":{"metadata":{},"bootstrap":{},"infrastructureRef":{"apiGroup":null,"kind":"","name":""}},"status":{}}

I0624 15:41:55.085642   88363 round_trippers.go:444] Response Headers:
I0624 15:41:55.085646   88363 round_trippers.go:447]     Date: Mon, 24 Jun 2019 22:41:55 GMT
I0624 15:41:55.085650   88363 round_trippers.go:447]     Content-Length: 1548
I0624 15:41:55.085654   88363 round_trippers.go:447]     Content-Type: application/json
I0624 15:41:55.085693   88363 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Machine.cluster.k8s.io \"foo\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"cluster.k8s.io/v1alpha2\", \"kind\":\"Machine\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-06-24T22:41:55Z\", \"generation\":1, \"name\":\"foo\", \"namespace\":\"default\", \"uid\":\"445dfcf4-96d1-11e9-bd3d-0c9d92c4bb46\"}, \"spec\":map[string]interface {}{\"bootstrap\":map[string]interface {}{}, \"infrastructureRef\":map[string]interface {}{\"apiGroup\":interface {}(nil), \"kind\":\"\", \"name\":\"\"}, \"metadata\":map[string]interface {}{}}}: validation failure list:\nspec.infrastructureRef.apiGroup in body must be of type string: \"null\"","reason":"Invalid","details":{"name":"foo","group":"cluster.k8s.io","kind":"Machine","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: map[string]interface {}{\"apiVersion\":\"cluster.k8s.io/v1alpha2\", \"kind\":\"Machine\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-06-24T22:41:55Z\", \"generation\":1, \"name\":\"foo\", \"namespace\":\"default\", \"uid\":\"445dfcf4-96d1-11e9-bd3d-0c9d92c4bb46\"}, \"spec\":map[string]interface {}{\"bootstrap\":map[string]interface {}{}, \"infrastructureRef\":map[string]interface {}{\"apiGroup\":interface {}(nil), \"kind\":\"\", \"name\":\"\"}, \"metadata\":map[string]interface {}{}}}: validation failure list:\nspec.infrastructureRef.apiGroup in body must be of type string: \"null\"","field":"[]"}]},"code":422}
```

**Comment by vincepri** [comment]
Nevermind, I re-read the description and it makes sense why it's not there now.

**Comment by 2uasimojo** [comment]
@vincepri Can you please explain it to me? The description makes it sound like I don't need to set it if I'm using a standard Kind. In my case, I'm using PersistentVolumeClaim, which is core/v1, and I'm still getting the error.

**Comment by navidnabavi** [comment]
I have this issue on PersistentVolumeClaim too. I must set it and somehow it does not act like an optional method.

**Comment by SamGerber** [comment]
Clicking through to the commits that mention this issue, it seems like the workaround they use is this:

`APIGroup: new(string),`

Worked for me.
