### ISSUE TITLE
Potential bugs on old cores: usage of sync/atomic.*64 functions

### ISSUE THREAD

**Issue by lzhfromustc** [kubernetes/kubernetes#79350]
**What happened**:
I noticed that atomic.LoadInt64 and atomic.CompareAndSwapInt64 are used in File: staging/src/k8s.io/apiserver/pkg/storage/util.go at Line: 81,85. There may be more in other files.

**What you expected to happen**:
These 64-bit functions in atomic can cause bugs on old cores.

**How to reproduce it (as minimally and precisely as possible)**:
Please see https://golang.org/pkg/sync/atomic/#pkg-note-BUG

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
> These 64-bit functions in atomic can cause bugs on old cores.
> Please see https://golang.org/pkg/sync/atomic/#pkg-note-BUG

I assume you're referring to this part from the link:

> On x86-32, the 64-bit functions use instructions unavailable before the Pentium MMX.

Pentium MMX is going to be > 20 years old ([wikipedia says](https://en.wikipedia.org/wiki/P5_(microarchitecture)) it was introduced in 1996), I'm not sure how succesful you'd be running Kubernetes on hardware from that era in general 🙃 

That doc does also note:
> On non-Linux ARM, the 64-bit functions use instructions unavailable before the ARMv6k core.

We don't support non-linux ARM currently.

> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

We should be fine there, it's the only word in the variable.

**Comment by lzhfromustc** [comment]
Thank you for your reply! I reported the usage of atomic64 because I saw grpc-go developers handled this as a bug and fixed it. Since it is fine for kubernetes, I am closing this issue.
