### ISSUE TITLE
Flexvolume to CSI migration

### ISSUE THREAD

**Issue by trevormeiss** [kubernetes/kubernetes#79355]
Is there any guidance for migrating flexvolume drivers to CSI?
We have an existing cluster with flex PVs. We would like to uninstall our flexvolume driver and install a new CSI driver. We would like the new CSI driver to use the same StorageClass as our old flex driver, and we would like the CSI driver to take over managing the existing PVCs.

Is there any work being done to make this migration non-disruptive?

**Comment by BenTheElder** [comment]
cc @davidz627

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by davidz627** [comment]
Hi @trevormeiss at this time unfortunately I don't believe anybody is working on this problem. Some designs have been proposed in the past: notably I believe @bswartz wanted to have a solution where you could create new CSI PV's in your system and do an "atomic pointer swap" of the PVC to the new PV. Although I believe there were quite a few unknowns to that approach and nobody is currently investing effort into it.

I am working on [solving a slightly different problem](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190129-csi-migration.md) of shimming the volume back-end for if you decide to stay with in-tree PV's.

Please sync up with @bswartz to ask if he has any updates on their proposal, and feel free to bring it up in the sig storage bi-weekly meeting as well.

**Comment by pure-yesmat** [comment]
Thanks @davidz627.
@bswartz can you share your current design/proposal/thoughts?

**Comment by pure-yesmat** [comment]
@davidz627 would you mind sharing the storage bi-weekly meeting details

**Comment by davidz627** [comment]
@pure-yesmat PTAL https://github.com/kubernetes/community/tree/master/sig-storage#meetings

**Comment by pure-yesmat** [comment]
Thanks, it seems the link is still to be updated?
https://docs.google.com/document/d/1FQx0BPlkkl1Bn0c9ocVBxYIKojpmrS1CFP5h0DI68AE/edit

**Comment by saad-ali** [comment]
@pure-yesmat Link for Storage SIG Meeting agenda: https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit

**Comment by bswartz** [comment]
@pure-yesmat My design involves a disruptive upgrade, in the sense that every pod attached to a volume would need to restart. In theory this should not be a big deal in a kubernetes cluster, but there are always users who do inadvisable things, so it's not something we take lightly. At a high level, the approach is to delete the old PV and create a new PV of the csi type, and to rebind the PVC, killing the pods at the right time.

It's theoretically possible to not even restart the pods, but such a solution would be very scary to try and support.

**Comment by dinathom** [comment]
@bswartz  We have tried the solution you propose but kubelet on the node may or maynot cleanup the paths for flexvolume depending on when kubelet was restarted.  Even if we are able to handle pod restarts, kubelet restarts is out of our control.  Do you have a proposal to handle unmounts/detach of flexvolumes because kubelet may/maynot call the flexvolume driver based on what its in-memory state is?

**Comment by bswartz** [comment]
I'm not sure what special things happen with flexvol plugins. I know that there are issues with cleanup when kubelet restarts. Under normal circumstances though, kubelet won't restart during a migration of this kind, and if it does restart, I think the behavior wouldn't differ much from a kubelet restart with no migration going on. Either the cleanup logic is reliable, or it's buggy, I don't see how migration makes it worse.

**Comment by pure-yesmat** [comment]
Hi @saad-ali and @bswartz,
Is there a programmatic way to restart a pod? Also how do we handle the case where the pod restart policy is never?

**Comment by msau42** [comment]
Yes, the programmatic way is to delete the Pod.  I think this is something that should not be handled automatically by the storage system. And it will have to be users that restart their pods when they are ready.

**Comment by pure-yesmat** [comment]
Thanks @msau42.

Deleting a pod does not work if it does not belong to a deployment or statefulset.

The summary I get from this is we cannot upgrade programmatically, we have to be ready to keep both drivers around forever. Asking users to delete all their pods for a driver upgrade seems overkill.

**Comment by msau42** [comment]
You don't need to keep them around forever. You can make policies such as the flex driver is being deprecated, and we'll stop supported it by Kubernetes version X.  Here's some steps to migrate your PVs to the CSI driver, etc
