### ISSUE TITLE
ConfigMap kubeadm:kubelet-config-1.15 does not exist

### ISSUE THREAD

**Issue by Michi03** [kubernetes/kubernetes#79363]
**What happened**:
I tried to connect a new node to a running kubernetes by use of `kubeadm token create`. 

**What you expected to happen**:
Generation of a ConfigMap named kubeadm:kubelet-config-1.15 which enables joining a new node.

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubeadm token create`

**Anything else we need to know?**:
The node I tried to join threw the following error message:
`error execution phase kubelet-start: configmaps "kubelet-config-1.15" is forbidden: User "system:bootstrap:dxouu8" cannot get resource "configmaps" in API group "" in the namespace "kube-system"`

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Bare Metal

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux tech4comp-Precision-5820-Tower 4.16.0-041600-generic #201804012230 SMP Sun Apr 1 22:31:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
apt

- Network plugin and version (if this is a network-related bug):
- Others:
`kubelet --version`
Kubernetes v1.15.0
`kubeadm version`
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Michi03** [comment]
I had added a node on version 1.14.3 for which a confimap still existed. Thus, downgrading to 1.14.3-00, running the join command and upgrading afterwards fixed the issue for me

**Comment by neolit123** [comment]
/close

if you have created a kubernetes cluster using `kubeadm init` with 1.14.x as the kubernetes version, it means you can only join kubelet binaries that match the 1.14 version (and fetch the `kubelet-config-1.14` ConfigMap), pre 1.15. this was confusing and arguably not valid.

in 1.15 the logic slightly improved, such as, that kubeadm fetches the version of the control plane from the cluster and then retrieves the config map for that exact version:
https://github.com/kubernetes/kubernetes/pull/78575

but there is still work to be done on this front:
https://github.com/kubernetes/kubeadm/issues/1582

thanks.
