### ISSUE TITLE
Unclear behavior when setting/updating already existing environment variables like PATH

### ISSUE THREAD

**Issue by cvanlabe** [kubernetes/kubernetes#79364]
**What happened**:
In a deployment manifest, one can set an environment variable like FOO, and the deployment will succeed. However, if you set one like PATH, you end up with a pod in RunContainerError status.

**What you expected to happen**:
I expect to find documentation you can not do this for existing environment variables, or I expect kubernetes to overwrite that environment variable inside the container. The use-case is that per deployment, I want to append a specific directory to the existing PATH inside the container, without having to modify the Dockerfile (and having to have multiple dockerfiles per deployment)

**How to reproduce it (as minimally and precisely as possible)**:
- Have a deployment yaml file with something like this:
```
...
containers:
  name: bla
  env:
    - name: PAAAATH
      value: "blabla"
...
```
- Apply it with `kubectl apply -f deployment.yaml`
- **This works**
- Have a deployment yaml file with something like this:
```
...
containers:
  name: bla
  env:
    - name: PATH
      value: "blabla"
...
```
- Apply it with `kubectl apply -f deployment.yaml`
- **This doesn't work**
- `kubectl get pods`
  ```
  NAME                       READY   STATUS              RESTARTS   AGE
  container-76c8df844-mw5jr    0/1     RunContainerError   0          2s
  ``` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: N/A - kvm VM
- OS (e.g: `cat /etc/os-release`): 

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`):

Linux candela-stg 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by cvanlabe** [comment]
@kubernetes/sig-bugs

**Comment by BenTheElder** [comment]
This is documented in the API docs but I'm not sure if it's documented elsewhere.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#container-v1-core

`env` says:
> List of environment variables to set in the container. Cannot be updated.

They're set.

_technically_ you can set PATH and still have a functioning container, you just need to be careful what you set it to. there's no merge functionality for environment values though

If you want to append to PATH without modifying the docker image, you can set this in the args, eg like https://stackoverflow.com/a/45106930

Kubernetes is overwriting the env in the same way `docker run -e FOO=bar ...` does.

**Comment by BenTheElder** [comment]
I think this would be
/sig node
since we're dealing with pods

**Comment by BenTheElder** [comment]
probably also
/kind documentation

github.com/kubernetes/website might be open to a PR or issue related to clarifying / adding a note about this. Im not sure where it would go though.

**Comment by cvanlabe** [comment]
@BenTheElder Thanks a lot for commenting. It would indeed be good if it can be more publicly available. 

I saw the stackoverflow document you mentioned, but I don't think that approach works. 
In your Dockerfile, you basically specify an ENTRYPOINT (the main executable), and the args from the deployment manifest get appended, not prepended. So the executable will not consider it as an environment variable.

ie: we'd get    
```
executable PATH=/path/to/bla
```
instead of
```
PATH=/path/to/bla executable
```

**Comment by mattjmcnaughton** [comment]
@cvanlabe @BenTheElder agree that a documentation update would be quite helpful here.

@cvanlabe would you mind linking some of the documentation you looked at when trying to solve this issue? We can give it a look and update the most appropriate page with this additional info that same environment variables intentionally can't be set.

**Comment by BenTheElder** [comment]
@cvanlabe you can just as easily prepend instead of append with "PATH=/foo:$PATH"
