### ISSUE TITLE
Nfs provisioner failed to mount in kubernetes v1.13.4 on google cloud

### ISSUE THREAD

**Issue by sudheshpn** [kubernetes/kubernetes#79373]
I have configured a nfs provisioner  for my kubernetes cluster on gcp plaform . status of pv,pvc, and nfs provisoner pod looks good. However when i try to  create a pod using the pvc in my pod defintion file i get the below exception.FYI  I am able to mount the nfs volume to my master node and slave node. Pls help

NFS provisoner status 

root@k8s-master:/etc/kubernetes/manifests# kubectl get pods 
NAME                                     READY   STATUS    RESTARTS   AGE
nfs-client-provisioner-548bb5fc4-fjm5n   1/1     Running   0          154m

pv,pvc's status set to bound

root@k8s-master:/etc/kubernetes/manifests# kubectl get pv,pvc --all-namespaces
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                STORAGECLASS          REASON   AGE
persistentvolume/pvc-98b69b70-9757-11e9-9001-42010a800004   2Gi        RWO            Delete           Bound    monitoring/prometheus-alertmanager   managed-nfs-storage            13m
persistentvolume/pvc-98b7216b-9757-11e9-9001-42010a800004   8Gi        RWO            Delete           Bound    monitoring/prometheus-server         managed-nfs-storage            13m
NAMESPACE    NAME                                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
monitoring   persistentvolumeclaim/prometheus-alertmanager   Bound    pvc-98b69b70-9757-11e9-9001-42010a800004   2Gi        RWO            managed-nfs-storage   13m
monitoring   persistentvolumeclaim/prometheus-server         Bound    pvc-98b7216b-9757-11e9-9001-42010a800004   8Gi        RWO            managed-nfs-storage   13m

Error message on my pod 

Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/98e6120d-9757-11e9-9001-42010a800004/volumes/kubernetes.io~nfs/pvc-98b69b70-9757-11e9-9001-42010a800004 --scope -- mount -t nfs 10.128.0.5:/m
onitoring/monitoring-prometheus-alertmanager-pvc-98b69b70-9757-11e9-9001-42010a800004 /var/lib/kubelet/pods/98e6120d-9757-11e9-9001-42010a800004/volumes/kubernetes.io~nfs/pvc-98b69b70-9757-11e9-9001-42010a800004
Output: Running scope as unit run-r11325b6f6c6e4ed49a7bb97a21319ede.scope.
mount.nfs: mounting 10.128.0.5:/monitoring/monitoring-prometheus-alertmanager-pvc-98b69b70-9757-11e9-9001-42010a800004 failed, reason given by server: No such file or directory
  Warning  FailedMount  41s (x4 over 7m26s)  kubelet, k8s-slave  Unable to mount volumes for pod "prometheus-alertmanager-786cfbc968-9nrz9_monitoring(98e6120d-9757-11e9-9001-42010a800004)": timeout expired waiting for volumes to
 attach or mount for pod "monitoring"/"prometheus-alertmanager-786cfbc968-9nrz9". list of unmounted volumes=[storage-volume]. list of unattached volumes=[config-volume storage-volume prometheus-alertmanager-token-lbzsq]

**Environment**: Cloud
- Kubernetes version (use `kubectl version`): v1.13.4
- Cloud provider or hardware configuration: Google Cloud
- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`): Linux k8s-master 4.15.0-1034-gcp #36~16.04.1-Ubuntu SMP Thu Jun 6 15:36:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:v1.13.4

**Comment by msau42** [comment]
Which nfs provisioner are you using?

This is the relevant error message:
mount.nfs: mounting 10.128.0.5:/monitoring/monitoring-prometheus-alertmanager-pvc-98b69b70-9757-11e9-9001-42010a800004 failed, reason given by server: No such file or directory

**Comment by sudheshpn** [comment]
The one below
https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client/deploy

**Comment by sudheshpn** [comment]
Do we need to set --cloud-provider gcp on kubelet?

**Comment by huisebug** [comment]
I also have the same question. Do I need to change the configuration of the kubelet service?

**Comment by huisebug** [comment]
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ce377816-cfc2-11e9-b56c-00163e02d405/volumes/kubernetes.io~nfs/pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405 --scope -- mount -t nfs ng-prometheus-k8s-db-prometheus-k8s-0-pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405 /var/lib/kubelet/pods/ce377816-cfc2-11e9-b56c-00163e02d405/volumes/kubernetes.io~nfs/pvc-c9eb5a05-cf7e-11e9-b56c-00163e02d405
Output: Running scope as unit run-12446.scope.
