### ISSUE TITLE
enhance to record accurate total end to end operation time for volume attach/detach/resizing

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes/kubernetes#79397]
**What would you like to be added**:
latency of volume attach/detach/resizing operations is currently evaluated at per-try basis and recorded into "storage_operation_duration_seconds" defined in [metrics.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/metrics.go). A recent fix (#78061) has been put in to record end to end latency for provisioning/deletion operations into "volume_operation_duration_seconds". This issue is created to track the fix for attach/detach/resizing operations

Another ongoing WIP here to fix end to end total operation time for mount/umount is here #75384

**Why is this needed**:
To provide more accurate volume operation latency metrics for detach/attach/resizing.

**Comment by yuxiangqian** [comment]
sig/storage

**Comment by yuxiangqian** [comment]
@msau42 @gnufied

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by gnufied** [comment]
Just to confirm.. is total mount and unmount timings out of scope for this issue?

**Comment by msau42** [comment]
I think we should consider node operations too. But we could track it as a separate issue if that's easier?

**Comment by yuxiangqian** [comment]
@msau42 @gnufied Can either of you assign the issue to me?
I am working on the enhancement and have been looking into the attach/detach and mount/unmount workflow, both sets of operations seems to end in: [OperationExecutor](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_executor.go), which eventually creates a corresponding Fun to be executed.
From this perspective, I am proposing to move [OperationStartTimeCache](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/metrics/metrics.go#L225) to [pkg/volume/util](https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/util) by adding a new file such that all storage operations could share the same implementation.

in this enhancement, I would do:
1. move the cache to volume/util
2. enhance end to end latency for attach/detach

mount/unmount will be enhanced in a separate one to avoid creating too big PRs
thoughts?

**Comment by msau42** [comment]
Sounds good to me! Thanks!

I think we can't assign you until you are a Kubernetes member. Can you apply for membership? https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by gnufied** [comment]
@yuxiangqian I think you can just assign this to yourself.  Just do a plain "/assign" in the comment here and it will work. I just found out.

**Comment by yuxiangqian** [comment]
thanks both. I think I can not assign it to myself, tried before. I will try to be a member firstly.
