### ISSUE TITLE
Automatically add system:authenticated when impersonating group

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#79395]
Is there a realistic scenario where a user would want to impersonate an arbitrary group but NOT also want system:authenticated? I think we should always add system:authenticated. Forgetting it results in some hard-to-debug behaviour with kubectl inexplicably failing every 10 mins.

Basically, I want to reopen this discussion: https://github.com/kubernetes/kubernetes/pull/44076#discussion_r110657420 .

/sig auth

**What happened**:
Tried to impersonate a group, did not know we needed to add system:authenticated, and inexplicably every 10 minutes our command would error until we did another kubectl command without impersonation:
```
$ kubectl get po --as=asdf --as-group=asdf
error: the server doesn't have a resource type "po"
$ kubectl get po
# Works
$ kubectl get po --as=asdf --as-group=asdf
# Works for 10 minutes
```

It turns out that every 10 minutes kubectl needs to repopulate its discovery cache and for that, the user needs to have permission to `get` /api (typically provided by system:discovery bound to system:authenticated). Since we didn't know we had to add --as-group=system:authenticated we had a hard time debugging. Found this comment https://github.com/kubernetes/kubernetes/issues/73123#issuecomment-456185028 much later.

**What you expected to happen**:
Can do `kubectl get po --as=asdf --as-group=asdf` as much as I want without seeing errors

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ kubectl get po --as=asdf --as-group=asdf`
# Works
$ rm -rf /Users/mattwon/.kube/cache/discovery
$ kubectl get po --as=asdf --as-group=asdf`
error: the server doesn't have a resource type "po"
```
**Anything else we need to know?**: If we decide we can't do this, at least I'd like to add mention of this "gotcha" here https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation

**Environment**:
kubernetes master

**Comment by enj** [comment]
We should update the docs so that the lack of any automatic groups impersonation is clear.

**Comment by anderseknert** [comment]
Just lost a few hours and hairs due to this, if it adds to the evidence. Agreed that a mention in the docs would likely have been good enough to avoid that though.

**Comment by bjethwan** [comment]
--as-group not working
 
k -n bipin  get pods
No resources found.

k -n bipin auth can-i --as-group=system:masters get pods
error: requesting groups or user-extra for xyz without impersonating a user

k -n bipin auth can-i --as-group=system:masters get pods
error: requesting groups or user-extra for xyz without impersonating a user

k -n bipin auth can-i --as-group=system:authenticated get pods
error: requesting groups or user-extra for xyz without impersonating a user

**Comment by anderseknert** [comment]
@bjethwan you always need to provide a user for impersonation as well, like `--as=johnrando --as-group=system:authenticated`

**Comment by rajatjindal** [comment]
Also spent few hours trying to debug this.

I am willing to submit the PR for this. I can see that we can go one of the following routes:

1. add message to command line argument to specify the need of 'system:authentocated' group OR
2. when impersonating group, automatically add 'system:authenticated' to the group list

I think the option 2 will be most user friendly (unless we think it will trigger some other different prob). 

kindly provide your feedback.

many thanks

**Comment by liggitt** [comment]
Changing the API behavior is probably not desirable, since it removed the ability to check permissions for a specific group (since you would never be sure if the answer was influenced by permissions granted to all authenticated users). A message indicating only the specified groups are being used if system:authenticated is not included seems useful

**Comment by wongma7** [comment]
I think this was fixed by https://github.com/kubernetes/kubernetes/pull/94204 ?
