### ISSUE TITLE
kubeadm v1.14.2 init failed to pull pause image when using cri and private registry  ( seems to pull 2 times ..)

### ISSUE THREAD

**Issue by boogie777** [kubernetes/kubernetes#79422]
**What happened**:

When trying to bootstrap a kube cluster v 1.14.2 the kubeadm process failed 
as the container pause is not retrieved.
Seems that even if the pause container is in our private registry during the setup,  the k8s.gcr.io pause container is being called ..wich failed do to internal firewall policy 

`image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 64.233.167.82:443: connect: connection refused
Jun 26 13:25:00 master01 kubelet: E0626 13:25:00.755513 87777 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-controller-manager-master01_kube-system(59e14f58e7932b5126761aec67097a02)" failed: rpc error: co
de = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gc
r.io/v2/pause/manifests/3.1: dial tcp 64.233.167.82:443: connect: connection refused`

**What you expected to happen**:

Expected a normal bootstrap and setup 
And only use of our private registry to use pause container

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`

- Cloud provider or hardware configuration:

bare metal 

`[root@master01~]` # cat /proc/cpuinfo  |grep processor -c
4
[root@master01 ~] # free -m
              total        used        free      shared  buff/cache   available
Mem:           7803         824        4169         432        2809        6138
Swap:             0           0           0
`
- OS (e.g: `cat /etc/os-release`):

 
`[root@master01 ~] # lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
`

- Kernel (e.g. `uname -a`):

`[root@master01 ~] # uname -a
Linux master01 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools:
- Network plugin and version (if this is a network-related bug):
`
[root@master01 ~] # rpm -qa |grep cni
kubernetes-cni-0.7.5-0.x86_64

containerd-1.2.7.linux-amd64.tar.gz
v1.0.0-rc8/runc.adm64
`

- Others:
private repository used : 
artifactory with docker-remote using k8s.gcr.io repo
Firewall dropping all netflow to the outside.

etcd-v3.3.13-linux-amd64.tar.gz

`
[root@master01~] # kubeadm config view
apiServer:
  certSANs:
  - vip-api
  - 10.121.255.8
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta1
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: 10.121.255.8:443
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  external:
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/etcd/client.crt
    endpoints:
    - https://10.121.255.21:2379
    keyFile: /etc/kubernetes/pki/etcd/client.key
imageRepository: artifact-docker/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.14.2
networking:
  dnsDomain: cluster.local
  podSubnet: 10.124.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
`
`
[root@master01 ~] # crictl -r unix:///run/containerd/containerd.sock -i unix:///run/containerd/containerd.sock images
IMAGE                                                                               TAG                 IMAGE ID            SIZE
artifact-docker/calico/cni                                  v3.7.2              98cc1111e3b96       47.9MB
artifact-docker/calico/kube-controllers                     v3.7.2              069f2f5046b2d       17.9MB
artifact-docker/calico/node                                 v3.7.2              fedbb67af68c3       66.6MB
artifact-docker/google_containers/coredns                   1.3.1               eb516548c180f       12.3MB
artifact-docker/google_containers/kube-apiserver            v1.14.2             5eeff402b6598       49.8MB
artifact-docker/google_containers/kube-controller-manager   v1.14.2             8be94bdae1399       47.6MB
artifact-docker/google_containers/kube-proxy                v1.14.2             5c24210246bb6       30MB
artifact-docker/google_containers/kube-scheduler            v1.14.2             ee18f350636d8       30MB
k8s.gcr.io/pause                                                                    3.1                 da86e6ba6ca19       317kB
artifact-docker/google_containers/pause                     3.1                 da86e6ba6ca19       317kB
`

--

@kubernetes/cluster-lifecycle/bugs
/sig cluster-lifecycle

**Comment by boogie777** [comment]
@kubernetes/sig-K8s Infra-bugs

**Comment by boogie777** [comment]
/kubernetes/test-infra

**Comment by neolit123** [comment]
/priority awaiting-more-evidence

if you have your `imageRepository: artifact-docker/google_containers` in the kubeadm config, the resulted pause image should be `artifact-docker/google_containers/pause:3.1`,

this value is then passed to the kubelet as `--pod-infra-container-image=artifact-docker/google_containers/pause:3.1`, but _only in the case of docker_ as this is a dockershim specific flag.
kubeadm does not support configuring the pod infra container for other container runtimes.

what are the contents of your `/var/lib/kubelet/kubeadm-flags.env` file after `kubeadm init/join`, but before `kubeadm reset`?

**Comment by BenTheElder** [comment]
for containerd you want these settings in the config file (default path `/etc/containerd/config.toml`)
```toml
# The "plugins.cri" table contains all of the server options.
[plugins.cri]
  # sandbox_image is the image used by sandbox container.
  sandbox_image = "artifact-docker/google_containers /pause:3.1"
```

see: https://github.com/containerd/cri/blob/master/docs/config.md

**Comment by boogie777** [comment]
Hello, @neolit123 and @BenTheElder 
thanks a lot for your quick anwers !

according the tips given to provide the path of the sandbox directly in containerd config ; the reset of the cluster with the firewall rule dropping access the the outside is a great success :D 

We now have only pause image pulled from our repo 
`
[root@zinfpaasmaster01bv ~] # crictl -r unix:///run/containerd/containerd.sock -i unix:///run/containerd/containerd.sock images 
IMAGE                                                                               TAG                 IMAGE ID            SIZE
artifact-docker-remote.meetic.ilius.net/calico/cni                                  v3.7.2              98cc1111e3b96       47.9MB
artifact-docker-remote.meetic.ilius.net/calico/node                                 v3.7.2              fedbb67af68c3       66.6MB
artifact-docker-remote.meetic.ilius.net/google_containers/coredns                   1.3.1               eb516548c180f       12.3MB
artifact-docker-remote.meetic.ilius.net/google_containers/kube-apiserver            v1.14.2             5eeff402b6598       49.8MB
artifact-docker-remote.meetic.ilius.net/google_containers/kube-controller-manager   v1.14.2             8be94bdae1399       47.6MB
artifact-docker-remote.meetic.ilius.net/google_containers/kube-proxy                v1.14.2             5c24210246bb6       30MB
artifact-docker-remote.meetic.ilius.net/google_containers/kube-scheduler            v1.14.2             ee18f350636d8       30MB
artifact-docker-remote.meetic.ilius.net/google_containers/pause                     3.1                 da86e6ba6ca19       317kB
[root@zinfpaasmaster01bv ~] # cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --pod-infra-container-image=artifact-docker-remote.meetic.ilius.net/google_containers/pause:3.1
`

Thanks a lot for your help !!

**Comment by neolit123** [comment]
thanks for the confirmation.
we should probably include docs for the other CR with respect to setting the "pause" image.
/close

**Comment by zgfh** [comment]
@neolit123 should we auto set "pause" image of containerd when have param of “--pod-infra-container-image”？ it will be more easy to install

**Comment by neolit123** [comment]
please comment on:
https://github.com/kubernetes/kubeadm/issues/2020

the flag also apparently controls garbage collection in the kubelet.
