### ISSUE TITLE
Move fluentd-elasticsearch out of k/k

### ISSUE THREAD

**Issue by coffeepac** [kubernetes/kubernetes#79432]
**What would you like to be added**:
currently the fluentd-elasticsearch cluster addon creates two docker images that are hosted in non-kubernetes controlled repositories and the code to create them is hosted in k/k.  either the code should be moved out of k/k or the images to should be controlled by the kubernetes org.

**Why is this needed**:
this type of ownership mismatch will lead to a bad user experience and possible security risks as and when the management for these artifacts get out of sync.

**Comment by monotek** [comment]
Not sure if we have enough time to wait for the feature to be generally available but I think githubs comming package registry would be a perfect fit.

https://github.blog/2019-05-10-introducing-github-package-registry/

**Comment by spiffxp** [comment]
We're still figuring out how to work with GitHub's registry (ref: https://github.com/kubernetes/org/issues/812) so I wouldn't recommend that as an immediate path forward

I would recommend pulling code out to a new repo in kuberentes-sigs (kuberentes/org issue + written decision from sig-inst to help you create that)

And follow https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io#creating-staging-repos to get a staging repo setup for this subproject

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/79390#issuecomment-506831535 some other locations to watch out per cs.k8s.io

**Comment by monotek** [comment]
not stale

**Comment by BenTheElder** [comment]
There is an established process for hosting images under the official kubernetes repository https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io

however, this sort of thing seems ripe for it's own subproject rather than having sources in kubernetes/kubernetes.

**Comment by SergeyKanzhelev** [comment]
@coffeepac are you using this image? I wonder if anybody is using it and whether we can simply delete it.

**Comment by monotek** [comment]
The image is also used in the fluentd-elasticsearch helm chart: 
https://github.com/kokuwaio/helm-charts/tree/main/charts/fluentd-elasticsearch

**Comment by coffeepac** [comment]
These images are seeing 40-80k 'actions' (as listed by quay, I'm not sure what that means) a day, we probably shouldn't delete them.

**Comment by cablespaghetti** [comment]
As a user of the Helm chart mentioned above, I agree we should move this out of the kubernetes repository for better ease of maintenance. I am happy to assist with the maintenance of the repository. However given @monotek seems to be the primary maintainer of this, can I suggest we move it to https://github.com/kokuwaio?

**Comment by monotek** [comment]
It depends if kubernetes project likes to provide the docker image and fluentd config in the future?
If so, we need to find a new repo under the kuberntes umbrella. 

I guess https://github.com/kubernetes-sigs would be the right place for the repo but as far as i understand the process i have to be an active member of kubernetes-sigs to create a repo there, but i'm not. 

If somebody else create it i would be happy to move everthin there via pr.

**Comment by coffeepac** [comment]
@monotek is correct, this repo should go be moved to k8s-sigs org.  There is a signup process for being added.  We should bring this up at the sig-instrumentation meeting to get some guidance if this should be a part of the sig-instrumentation repo or if we should find a different home.

part of this work should also include moving the images out of quay and behind wherever the k8s.io url points.

**Comment by coffeepac** [comment]
After the sig-inst meeting yesterday, Han has taken an action to create a new repo:  kuberenetes-sigs/addons.  I've agreed to move all the three sig-inst addons over.  (fluentd-elasticsearch, fluentd-gcp, metrics-server).  

after its moved we can start exploring moving the image out of quay.

**Comment by monotek** [comment]
Nice :)

**Comment by coffeepac** [comment]
it exists!  https://github.com/kubernetes-sigs/instrumentation-addons

**Comment by monotek** [comment]
Nice. I'll add a pr tomorrow...

**Comment by monotek** [comment]
added prs for adding fluentd-elasticsearch to kubernetes-sigs/instrumentation-addons and remove it from k/k in:
https://github.com/kubernetes-sigs/instrumentation-addons/pull/1
https://github.com/kubernetes/kubernetes/pull/101039

**Comment by SergeyKanzhelev** [comment]
/reopen

to track #101039 merge

**Comment by SergeyKanzhelev** [comment]
/reopen
/remove-lifecycle rotten

this still needs to happen
