### ISSUE TITLE
How to disable/remove StorageObjectInUseProtection when  declaring pv/pvc

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubernetes#79437]
**What happened**:
pv/pvc protection does make a lot of trouble and confusion and receive much of complaint, see
[#77258](https://github.com/kubernetes/kubernetes/issues/77258), [#69697](https://github.com/kubernetes/kubernetes/issues/69697). For much of case besides me, pv/pvc will always stuck in `Terminating ` status even **NO** pod is using it.

So I wonder how can I disable it, or how can I remove this part when declaring a pv/pvc? Some step I try:

1. As [Changelog 1.15](https://github.com/kubernetes/kubernetes/pull/74610) says, StorageObjectInUseProtection  is enable by default. However, checking the `kube-api.yaml` on my **1.14.2** cluster, I only find **MutatingAdmissionWebhook,ValidatingAdmissionWebhook,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,NodeRestriction**, NO `StorageObjectInUseProtection `is found so I can not disable it

2. When declaring a pv, I set `finalizers: NULL` under the metadata section of PV/PVC **explicitly** , but this does not work as the pv(c) still contains `Finalizers:      [kubernetes.io/pv-protection]` when descrbing

 
**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Cloud provider or hardware configuration: none
- OS (e.g: `cat /etc/os-release`): centos 7.6
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
See https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#how-do-i-turn-off-an-admission-controller for instructions on disabling default admission plugins. 

Note that disabling this admission plugin is strongly discouraged, since it allows API objects to be deleted while storage is still in use. 

/close
/remove-kind bug

**Comment by Cherishty** [comment]
@liggitt  Thanks you
While according to the [same page](https://microsoft.sharepoint.com/teams/ProjectCarina/_layouts/OneNote.aspx?id=%2Fteams%2FProjectCarina%2FShared%20Documents%2FCarina&wd=target%28CAP.one%7C89072344-4855-4B77-A8B4-E29BF40CF7E7%2FCluster%20proxy%7C9E2462D6-DD8E-4B45-A974-D4A58EF8DDC0%2F%29
onenote:https://microsoft.sharepoint.com/teams/ProjectCarina/Shared%20Documents/Carina/CAP.one#Cluster%20proxy&section-id={89072344-4855-4B77-A8B4-E29BF40CF7E7}&page-id={9E2462D6-DD8E-4B45-A974-D4A58EF8DDC0}&end), it also declare that 1.14 does **not** enable StorageObjectInUseProtection  by default, so how can pv(c)-protection is created **automatically**?

**Comment by liggitt** [comment]
The finalizer is also added by the pv-protection and pvc-protection controllers. You can disable that feature by passing --feature-gates=StorageObjectInUseProtection=false to the kube-controller-manager. Note that this is not recommended, and can result in data loss, and the feature will be unconditionally enabled in future releases.

**Comment by tedyu** [comment]
```
feature will be unconditionally enabled in future releases
```
Since data loss may be incurred, I wonder if the above statement needs modification.
Did you mean that the feature would be disabled ?

thanks

**Comment by liggitt** [comment]
> Since data loss may be incurred, I wonder if the above statement needs modification.
Did you mean that the feature would be disabled ?

No. The feature prevents data loss. It will be unconditionally enabled in a future release.

**Comment by Cherishty** [comment]
Thanks for your clarification @liggitt 

Yes, I do know the motivation of finalizer, but I believe much of users occur the issue (may be a bug?) that pv(c) stuck in "**terminating**" even **NO** pod is binding on it

**Comment by liggitt** [comment]
> I believe much of users occur the issue (may be a bug?) that pv(c) stuck in "terminating" even NO pod is binding on it

If the finalizer on the PVC isn't getting removed when all the pods are gone, that is a bug (or the controller manager that does the deletion isn't running).

**Comment by tedyu** [comment]
I wonder if the tests added below cover that @Cherishty described:

    Merge pull request #78410 from MrHohn/svc-finalizer-e2e

    [e2e] Add tests for service load balancer finalizer

**Comment by tedyu** [comment]
Looking at pvc_protection_controller, it seems the DeleteFunc was missing in the following case:
```
diff --git a/pkg/controller/volume/pvcprotection/pvc_protection_controller.go b/pkg/controller/volume/pvcprotection/pvc_protection_controller.go
index a79d538611..3cef1de3af 100644
--- a/pkg/controller/volume/pvcprotection/pvc_protection_controller.go
+++ b/pkg/controller/volume/pvcprotection/pvc_protection_controller.go
@@ -73,6 +73,9 @@ func NewPVCProtectionController(pvcInformer coreinformers.PersistentVolumeClaimI
                UpdateFunc: func(old, new interface{}) {
                        e.pvcAddedUpdated(new)
                },
+               DeleteFunc: func(obj interface{}) {
+                       e.podAddedDeletedUpdated(obj, true)
+               },
        })

        e.podLister = podInformer.Lister()
```
If I am correct, I can submit a PR.

thanks

**Comment by liggitt** [comment]
yes, pvcAddedUpdated should be changed to pvcAddedUpdatedDeleted, handle tombstone objects, and be called from the deletionhandler

**Comment by Cherishty** [comment]
Hi @liggitt,
Your guidance 
> The finalizer is also added by the pv-protection and pvc-protection controllers. You can disable that feature by passing --feature-gates=StorageObjectInUseProtection=false to the kube-controller-manager

does work! Thanks a lot.

A little question I found is, seems I can NOT find any document to claim this operation (even from [offiical doc](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)). 
And the only thing I can figure out is `kube-apiserver --disable-admission-plugins=StorageObjectInUseProtection` in [kube-apiserver](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#storageobjectinuseprotection), while it does **NOT** work. 

Is this a documentation or legacy issue?
