### ISSUE TITLE
[Feature:FSQuota] Ensure projects are reflected in /etc on kubelet startup

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#79440]
In some OS configurations, `/etc` is reset upon node reboots.  It is conventional to record projects being used in `/etc/projects` and `/etc/projid` to allow actors on the node to avoid project id collisions, so losing information in `/etc` could potentially allow project id collisions to occur.

Currently, [Quotas for Ephemeral Storage](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20180906-quotas-for-ephemeral-storage.md) will only use a project if it has no recorded usage (and thus hasn't been applied to a directory).  This means that the kubelet is guaranteed to never re-use projects it has placed on empty-dir volumes _even if the contents of /etc are wiped_.  However, if other actors on the node use project quotas and only check `/etc/projects` and `/etc/projid`, they may collide with the kubelet's projects if /etc is wiped.

To fix this corner case, the kubelet should record the projects it has applied to empty-dir volumes in  `/etc/projects` and `/etc/projid` after a restart.

cc @RobertKrawitz

**Comment by RobertKrawitz** [comment]
Quotas for ephemeral storage does add `/etc/projects` and `/etc/projid` records (and cleans them up on teardown).  I think the use case @dashpole is referring to has to do with `/etc` being wiped on reboot.

**Comment by dashpole** [comment]
Updated the issue description to clarify

**Comment by RobertKrawitz** [comment]
:+1:

**Comment by irajdeep** [comment]
@dashpole I can work on this if no one else if currently working on it

**Comment by dashpole** [comment]
@irajdeep I don't believe anyone is working on this.  Feel free to work on it.
