### ISSUE TITLE
`kubectl config set-context`  should not create a new context

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#79455]
I ran:

` $ kubectl config set-context eks1`

I got:

`Context "eks1" created.`

**What would you like to be added**:

I would like set-context to not create a context if it does not exist. 

**Why is this needed**:

It is confusing / poorly named api

**Comment by hpandeycodeit** [comment]
`set-context`      `Sets a context entry in kubeconfig`

As mentioned in the description, It creates an entry in kubeconfig. 

To set the current-context use `use-context`

` use-context:      Sets the current-context in a kubeconfig file`
