### ISSUE TITLE
kubectl version command error message is not proper

### ISSUE THREAD

**Issue by ramnar** [kubernetes/kubernetes#79454]
**What happened**:

**kubectl version --client=yes** command  is giving the following error message. Error message is repeated at the start and the end and also containing programming jargon

Error: invalid argument "yes" for "--client" flag: strconv.ParseBool: parsing "yes": invalid syntax

Examples:
   Print the client and server versions for the current context
  kubectl version

Options:
      --client=false: Client version only (no server required).
  -o, --output='': One of 'yaml' or 'json'.
      --short=false: Print just the version number.

Usage:
  kubectl version [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

invalid argument "yes" for "--client" flag: strconv.ParseBool: parsing "yes": invalid syntax

**What you expected to happen**:

The error message can be improved with one of the two variants

invalid argument "yes" for "--client" flag

Examples:
   Print the client and server versions for the current context
  kubectl version

Options:
      --client=false: Client version only (no server required).
  -o, --output='': One of 'yaml' or 'json'.
      --short=false: Print just the version number.

Usage:
  kubectl version [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

(or)

Invalid argument "yes" for "--client" flag

**How to reproduce it (as minimally and precisely as possible)**:

Run the command **kubectl version --client=yes**

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Amazon Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by odinuge** [comment]
Hi @ramnar! Thanks for posting this issue! It turns out that this duplicate output has been in kubectl, and all the other cli cmds, since `v1.9`. 😄 

This should be fixed by https://github.com/kubernetes/kubernetes/pull/79493, and hopefully we can cherry pick it back to at least `v1.15`.
