### ISSUE TITLE
change glog level without restart

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#79457]
Does k8s has interface to change glog level without restarting? Sometimes we need upgrade the glog level for debugging and if we restart it, maybe we cannot re-produce bugs.
**What would you like to be added**:
If not have , can k8s add the debug interface?
**Why is this needed**:
For debugging without restart

**Comment by mattjmcnaughton** [comment]
Hi @Nebulazhang !

Thanks for posting :)

I think this is a repo of https://github.com/kubernetes/kubernetes/issues/39758 - could I trouble you to close this issue, and instead offer a "plus one" on that issue? Thanks!

**Comment by liggitt** [comment]
a PUT to the `/debug/flags/v` endpoint allows this

```
curl -X PUT http://localhost:8080/debug/flags/v --data 1
successfully set klog.logging.verbosity to 1
```

/close

**Comment by Nebulazhang** [comment]
> a PUT to the `/debug/flags/v` endpoint allows this
> 
> ```
> curl -X PUT http://localhost:8080/debug/flags/v --data 1
> successfully set klog.logging.verbosity to 1
> ```
> 
> /close

Thanks ! It's helpful
