### ISSUE TITLE
Compile errors for some openapi tests in benchmark suite

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#79464]
I've just finished setting up a test suite with microbenchmarks.
It generally works, but there is a problem with some tests related to open-api that they don't compile, e.g.:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-microbenchmarks/1144171647465426947/artifacts/benchmark-log.txt

```
# k8s.io/kubernetes/pkg/generated/openapi [k8s.io/kubernetes/pkg/generated/openapi.test]
../kubernetes/pkg/generated/openapi/openapi_test.go:31:27: undefined: GetOpenAPIDefinitions
# k8s.io/kubernetes/pkg/master [k8s.io/kubernetes/pkg/master.test]
../kubernetes/pkg/master/master_openapi_test.go:47:77: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions
```

Can you please take a look so that we could make this suite green?

@kubernetes/sig-api-machinery-bugs @sttts
@fedebongio

**Comment by draveness** [comment]
I met this problem too

**Comment by draveness** [comment]
I met this problem during development several hours ago, but I solved it by rebasing the master branch, is this still exists? I just ran tests against the master, and passed the tests without this error:

```go
go test ./pkg/master/...
ok  	k8s.io/kubernetes/pkg/master	55.906s
ok  	k8s.io/kubernetes/pkg/master/controller/crdregistration	(cached)
?   	k8s.io/kubernetes/pkg/master/ports	[no test files]
ok  	k8s.io/kubernetes/pkg/master/reconcilers	(cached)
?   	k8s.io/kubernetes/pkg/master/storageversionhashdata	[no test files]
ok  	k8s.io/kubernetes/pkg/master/tunneler	(cached)
``

**Comment by wojtek-t** [comment]
Hmm - the test is running every 20 minutes, and fetching from head, so I think it's something different...

**Comment by draveness** [comment]
> Hmm - the test is running every 20 minutes, and fetching from head, so I think it's something different...

Where could we find the original code to run the test?

**Comment by sttts** [comment]
`kubernetes/pkg/generated` has generated code which we don't commit. Either skip the tests or generate before. Not sure how I can help here. This is pretty test environment dependent.

**Comment by wojtek-t** [comment]
Thanks Stefan - that explains a lot. I will look how to do that the easiest way then.

**Comment by liggitt** [comment]
see explanation in https://github.com/kubernetes/kubernetes/issues/79464#issuecomment-506403162

we need to run the openapi generation step before running the benchmark

**Comment by sttts** [comment]
Here is a copy of the generated file: https://gist.github.com/sttts/b31e7d2c3cf0ad51ca388f7ea25d6452

If the benchmarks don't care about proper OpenAPI specs, you could easily fake the required funcs with empty content.

**Comment by tedyu** [comment]
I generated the file locally:
```
-rw-r--r--  1 yute  staff  2120213 Jan 11 17:50 zz_generated.openapi.go
```
It is larger than the staging/src/k8s.io/apiextensions-apiserver/pkg/generated/openapi/zz_generated.openapi.go which is 148KB.

Is the size of this file the major reason for not checking into source repo ?

Thanks

**Comment by liggitt** [comment]
This does not seem actionable as long as we don't intend to commit the generated code.
