### ISSUE TITLE
env valueFrom another env var

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#79479]
**What would you like to be added**:

`spec.containers[n].env.valueFrom.environmentVariable`

**Why is this needed**:

In order to reduce application code involved with munging Kubernetes environment variables.

**Comment by liggitt** [comment]
You can reference other envvars using $(NAME) syntax. See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#envvar-v1-core
