### ISSUE TITLE
build flake:  pull-kubernetes-bazel-build fails with "UNAVAILABLE: 502:Bad Gateway"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#79485]
**Which jobs are failing**:
pull-kubernetes-bazel-build
pull-kubernetes-bazel-test

**Which test(s) are failing**:
N/A

**Since when has it been failing**:
Not sure.  Noticed it midday 27 June 2019.

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78808/pull-kubernetes-bazel-build/1144269794934001664
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78808/pull-kubernetes-bazel-test/1144269794934001665

**Reason for failure**:
Unknown

**Anything else we need to know**:
These tests recently passed on another commit, 1d5ffeac47cdd47d5c48118eb64cbe2ca5dd24bd (probably inaccessible now because a replacement was force-pushed), which had the same code.

**Comment by MikeSpreitzer** [comment]
A retest of the bazel build succeeded, so this is definitely a flake.

@kubernetes/sig-testing-pr-reviews : if you are not the best folks to tag on this, please update with a better tag.

**Comment by Katharine** [comment]
Looks like the RBE cluster briefly became unavailable? Infrastructure failure we can't do much about, probably.

**Comment by MikeSpreitzer** [comment]
I am not familiar with what the RBE cluster is.
I read https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md , and drew the implication that we do not want flakes and developers who get bitten by them should do something about it.  It looks like you are telling me that there is a category of flakes that we just have to tolerate.  Is there any guidance you can add to flaky-tests.md to help developers identify those?

**Comment by boddumanohar** [comment]
can someone please conform if they are still failing?

**Comment by BenTheElder** [comment]
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-build
it's not, the most recent failure is totally unrelated
/close
