### ISSUE TITLE
kubebuilder and controller-* libraries should follow k8s release cadence

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#79486]
Kubebuilder is becoming the common way to develop operators /controllers for Kubernetes. With the release of various new features of CRD, it seems that new annotations are added to kubebuilder instead of code-generator repo. But one issue with kubebuilder and its controller-runtime and controller-tools repos is that these are not released with the same cycle as Kubernetes. In recent times, these libraries have been updated months after the last Kubernetes release. This is not a criticism of the fine folks behind kubebuilder. As a developer of Kubernetes operators/controllers, we would like to see that these tools become part of the same release cadence as Kubernetes. This will us to experiment with the new features of CRDs and release own tools and products faster after a new release of Kubernetes.

**Comment by liggitt** [comment]
Thanks for the feedback. Please raise this issue against the relevant projects for discussion/visibility.

/close

**Comment by tamalsaha** [comment]
I have refiled https://github.com/kubernetes-sigs/kubebuilder/issues/827
