### ISSUE TITLE
hack/update-bazel produces warnings

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#79499]
**What happened**:
Got the following error while trying to run `hack/update-bazel.sh`:
```
gazelle: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp.go: error reading go file: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp.go: pkg-config not supported: #cgo pkg-config: libseccomp
gazelle: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go: error reading go file: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go: pkg-config not supported: #cgo pkg-config: libseccomp
``` 

**How to reproduce it (as minimally and precisely as possible)**:
Ran this on a fresh install of ubuntu 19.04, Go 1.12.6, and bazel 0.26.1.

**Anything else we need to know?**:
Seems like the change might have been due to the update in vendored deps from #78187 ( https://github.com/kubernetes/kubernetes/pull/78187#discussion_r294546736 ).
Although this script is run in CI where it is working so may be some set of recommende pkg versions would help prevent this problem?

**Environment**:
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 19.04
- Kernel (e.g. `uname -a`): 5.0.0-15-generic
- bazel: 0.26.1
- Go: 1.12.6

**Comment by alejandrox1** [comment]
Not sure who owns this...
/sig testing

**Comment by alejandrox1** [comment]
Seems like the errors are "warnings" and can be ignored?
https://github.com/bazelbuild/bazel-gazelle/pull/556#issuecomment-504587744

> Gazelle should just print a warning for pkg-config directives. From the code, it looks like the error is just passed to log.Printf. If it's failing and not generating anything, please open an issue.

@BenTheElder would you happen to have some recommendation for this? It seems that BUILD files are updated by update-bazel :woman_shrugging: 

Also, out of curiosity, how is this setup in the presubmits (why is it working there)?

**Comment by BenTheElder** [comment]
/sig release
this is not a failure
/retitle hack/update-bazel produces warnings

there was some discussion on the original PR about filtering them out but nothing conclusive
I'll file a PR to do that now..
/assign

**Comment by BenTheElder** [comment]
aside: this is actually form https://github.com/kubernetes/kubernetes/pull/79287 :-)

we're working around the lack of `pkg-config` support because we only need it for this package and on all known systems we compile on so far it only needs the one link flag as previously specified in the cgo config.

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/kubernetes/pull/79502

**Comment by hoyho** [comment]
> /sig release
> this is not a failure
> /retitle hack/update-bazel produces warnings
> 
> there was some discussion on the original PR about filtering them out but nothing conclusive
> I'll file a PR to do that now..
> /assign

Glad to see it. The output message is so misleading that I have spent hours on this issue 🙃🙃

**Comment by BenTheElder** [comment]
sorry about that 😅 the output does say "error" but it's actually considered a non-fatal warning in the upstream code and doesn't cause the script (or build) to fail.

**Comment by odinuge** [comment]
https://github.com/kubernetes/kubernetes/pull/79287 was merged before this discussion was resolved https://github.com/kubernetes/kubernetes/pull/79287#discussion_r296493509, so we kinda saw this coming. :/

Hopefully we can get the fix from @BenTheElder in #79502 merged as quick as possible 😄

**Comment by aojea** [comment]
/reopen

we have a new a new occurrence with libipmctl

```
hack/update-bazel.sh 
gazelle: /Users/aojea/work/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/machine/machine_libipmctl.go: error reading go file: /Users/aojea/work/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/machine/machine_libipmctl.go: pkg-config not supported: #cgo pkg-config: libipmctl
```

**Comment by tanjunchen** [comment]
I have the same question.
```
gazelle: /home/k8s-develop/goproject/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/machine/machine_libipmctl.go: error reading go file: /home/k8s-develop/goproject/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/machine/machine_libipmctl.go: pkg-config not supported: #cgo pkg-config: libipmctl
```
This output is a bit annoying.

```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```
Linux ubuntu 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by BenTheElder** [comment]
We can update the script to handle this issue and suppress the warning. The
previous PR is an example.
