### ISSUE TITLE
The kubernetes 1.15 kube-proxy report  "Unable to find HNS Network specified by cbr0"  on windows  node

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/kubernetes#79515]
**What happened**:

When i upgrade my kubernetes cluster windows node  to 1.15,the windows node kube-proxy cannot work properly.  My  windows deployment cannt access by Nodeip:Port on this node but it can access by  the same cluster other nodes with  Nodeip:Port 

When i rollback my windows node  to 1.14.1 .  the kube-proxy works good, everything is ok

The kube-proxy logs  Loop Report that.

```
E0628 16:57:08.673912    1180 hnsV2.go:36] Network Id  not found
E0628 16:57:08.673912    1180 proxier.go:564] Unable to find HNS Network specified by cbr0. Please check network name and CNI deployment
E0628 16:57:09.679372    1180 hnsV2.go:36] Network Id  not found
E0628 16:57:09.679372    1180 proxier.go:564] Unable to find HNS Network specified by cbr0. Please check network name and CNI deployment
```

* 1.15.0

![image](https://user-images.githubusercontent.com/7907809/60331135-8e362c00-99c6-11e9-9853-faaf9d781cb4.png)

At this version , i cannot access my application by current node ip and the port

![image](https://user-images.githubusercontent.com/7907809/60331564-832fcb80-99c7-11e9-948e-b574425d4d54.png)

---------

* 1.14.1
![image](https://user-images.githubusercontent.com/7907809/60331148-93937680-99c6-11e9-9ab7-c69adf56f243.png)

At this version , i can access my application by current node ip and the port

![image](https://user-images.githubusercontent.com/7907809/60331536-7317ec00-99c7-11e9-81c7-76d55f405777.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): windows server 2019 (10.0.17763.134)
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel host-gw
- Others:
@feiskyer @andyzhangx

**Comment by wawa0210** [comment]
@kubernetes/sig-windows

**Comment by dineshgovindasamy** [comment]
@ksubrmnn @madhanrm Can you take a look please?

**Comment by ksubrmnn** [comment]
Looking into this

**Comment by wawa0210** [comment]
I guess the error reported from the [hcsshim ](https://github.com/microsoft/hcsshim) by kube-proxy invoke 

When i rollback to kubernetes 1.14.3 ,every thing is ok

Any one can help me @ksubrmnn @madhanrm @dineshgovindasamy

**Comment by ksubrmnn** [comment]
@wawa0210 I’m looking at the logs you posted in slack now.

**Comment by ksubrmnn** [comment]
Can you try passing in the kube-proxy argument `--network-name=cbr0`

**Comment by wawa0210** [comment]
> Can you try passing in the kube-proxy argument `--network-name=cbr0`

I added the parameter '--network-name=cbr0' for kube-proxy , there's no change and report the error as the same as i posted

**Comment by wawa0210** [comment]
I found the reason for the issue ,
https://github.com/kubernetes/kubernetes/pull/80116

can you reivew that pr ? @ksubrmnn @dineshgovindasamy

**Comment by ksubrmnn** [comment]
/assign @ksubrmnn 

I'm talking to the owners of hcsshim now to see about another release
