### ISSUE TITLE
EKS 1.13 nodes can't communicate with ECR

### ISSUE THREAD

**Issue by sethpollack** [kubernetes/kubernetes#79535]
**What happened**:
Starting seeing this error on nodes after upgrading to nodes to 1.13:
```
aws_credentials.go:194] while requesting ECR authorization token RequestError: send request failed
caused by: Post https://api.ecr.us-east-1.amazonaws.com/:  dial tcp i/o timeout

remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-east-1.amazonaws.com/v2/eks/pause-amd64/manifests/3.1:  no basic auth credentials
```

**Anything else we need to know?**:
Nodes running 1.12 with EKS 1.13 were able to pull images and adding the VPC default security group to the worker launch configurations fixed the issue for the 1.13 nodes.

**Environment**:
- EKS 1.13

**Comment by BenTheElder** [comment]
You should probably file product support for EKS with AWS directly, generally speaking they don't appear to be super active here and this looks like an EKS issue rather than a Kubernetes issue.

**Comment by sethpollack** [comment]
It's related to an SDK change that went into 1.13 of EKS, and 1.14+ of upstream.
