### ISSUE TITLE
kubectl logs -f should wait when in state PodInitializing

### ISSUE THREAD

**Issue by eddieparker** [kubernetes/kubernetes#79547]
It's a minor gripe, but when I'm trying to find out why my pod fails, I tend to "kubectl logs -f [podname]".  A common problem is that it's still initializing and kubectl tells me to go away.

Given that I specified '-f', I'd rather it just hang out in that state and then start piping logs when it's ready, versus me having to manually poll for when it's out of that state.

**Comment by eddieparker** [comment]
/kind feature
@kubernetes/sig-cli-feature-requests

**Comment by draveness** [comment]
I think this is quite convenient if we have a flag to wait and follow the log of a pod like this:

```go
$ kubectl logs -f --wait [pod]
...
```

**Comment by tedyu** [comment]
I wonder if '--wait' is needed since '-f' is already present.
Meaning waiting in PodInitializing state should be the default.

**Comment by draveness** [comment]
> I wonder if '--wait' is needed since '-f' is already present.
> Meaning waiting in PodInitializing state should be the default.

It would be better we remain forward compatibility, and we don't what how the users dealt with `kubectl`. If we change the default behaviour which may break some users' shell script.

**Comment by eddieparker** [comment]
Just a suggestion, could you make something like '-F' act as "follow and wait" if you're worried about backwards compatibility?

That was you avoid longer command lines; although admittedly you do end up using one extra short arg.

**Comment by draveness** [comment]
/unassign

Please feel free to take this issue

**Comment by ajp-lqx** [comment]
Meanwhile, if anyone wants a one-liner to achieve this in a bash shell, you can wrap the call to `kubectl logs` in a while loop, e.g. `while [[ ! $(kubectl logs ...) ]]; then echo "waiting..."; sleep 2; done; kubectl logs ...`

This will keep waiting until the `kubectl logs ...` call returns a 0 exit code, and then run the same `kubectl logs ...` call one more time to send the output to the terminal.

**Comment by ajpauwels** [comment]
Meanwhile, if anyone wants a one-liner to achieve this in a bash shell, you can wrap the call to kubectl logs in a while loop, e.g. while [[ ! $(kubectl logs ...) ]]; then echo "waiting..."; sleep 2; done; kubectl logs ...

This will keep waiting until the kubectl logs ... call returns a 0 exit code, and then run the same kubectl logs ... call one more time to send the output to the terminal.

**Comment by yuzhiquan** [comment]
/remove-lifecycle stale
Any update?

**Comment by momon** [comment]
> Meanwhile, if anyone wants a one-liner to achieve this in a bash shell, you can wrap the call to `kubectl logs` in a while loop, e.g. `while [[ ! $(kubectl logs ...) ]]; then echo "waiting..."; sleep 2; done; kubectl logs ...`
> 
> This will keep waiting until the `kubectl logs ...` call returns a 0 exit code, and then run the same `kubectl logs ...` call one more time to send the output to the terminal.

This was very helpful for me.  I was doing a migration which involved issuing several pod revisions in tandem and monitoring them while waiting for them to initialize was a bit of a pain.  Using a simple variation of this command helped me automate my checks.  I am using it as such:

```
while [[ ! $(kubectl logs deployment/dpl-id-9n3k1 -c containername) ]]; do echo "waiting..."; sleep 2; done; kubectl logs deployment/dpl-id-9n3k1 -c containername -f
```

**Comment by Startouf** [comment]
This is still annoying that we do not have a --wait or -F flag as suggested above, I'm in favor of reopening

/reopen
/remove-lifecycle rotten

**Comment by pacoxu** [comment]
My workaround would be 

```
kubectl wait --for=condition=Ready=true pod/[podname] && kubectl logs -f [podname]
```

**Comment by cschlesselmann** [comment]
This is still annoying

/remove-lifecycle rotten

**Comment by kkroening** [comment]
Yeah that's some strange default behavior. When using `kubectl logs -l somekey=somevalue` for example, all it takes is _one_ pod to be in `PodInitializing` state to bring the entire command to its knees, even if there are other legitimate pods that match the label.
