### ISSUE TITLE
Private docker registry credentials

### ISSUE THREAD

**Issue by pamatteo** [kubernetes/kubernetes#7954]
Hi,

In my testing environment I'm currently using a private docker registry set up on my machine. Then I have a kubernetes master/minion on a vm in my cluster. Kubelet cannot pull from my private registry since authentication is required. I've tried to login with `docker login` and copying the `.dockercfg`  in both `/root` and `/var/lib/kubelet` directories. I restarted all the kubernetes components but it still seems that kubelet cannot find the credentials (I checked the kubelet logs). I set up the kubernetes master following the [docker-multinode getting started guide](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/docker-multinode). 

How can I solve the issue? Are then any workaround or hack that I can use?Or am I forced to remove the authentication from my private registry?

thanks!

**Comment by hobti01** [comment]
I think you are looking for what will result from  https://github.com/GoogleCloudPlatform/kubernetes/issues/499 We are also looking forward to a solution to this.

In the meantime, the presented work-around seems to be pulling manually on each node.

**Comment by erictune** [comment]
try copying the dockercfg to `/.dockercfg`.

**Comment by pamatteo** [comment]
I tried to copy `.dockercfg` in the root directoy but the `kubelet` still does not use any credential when pulling images. 
I looked at the logs of the `kubelet` and it seems that it uses as root directory `/var/lib/kubelet` so I guess it would look there for a possible `.dockercfg` file.

**Comment by madis** [comment]
The ```.dockercfg``` should be placed in ```$HOME/.dockercfg``` not in the root.

**Comment by pamatteo** [comment]
this is the case when you use `sudo docker` from command-line, kubelet looks in the kubelet home which may vary as said [here] (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md).

**Comment by pnovotnak** [comment]
Totally useless without private image support from a business perspective... Really need documentation too, because it's also relatively useless *with* the feature if it's not documented well.

**Comment by janroos** [comment]
Copying to /.dockercfg worked before. 
Now tried also /root, /home/coreos, /var/lib/kubelet, /var/lib/docker
Stopped working after I re-built my environment today with newest versions of everything.

Running manually works:
docker pull ...
sudo docker pull ...

kubelet's home directory seems to be /
sudo ls -ld /proc/909/cwd
lrwxrwxrwx 1 root root 0 May 19 14:20 /proc/909/cwd -> /

**Comment by analytik** [comment]
For people who still have a problem with this, try adding `https://` to your `.dockercfg`. I found this to work for me:
```{
	"hub.example.com:1024": {
		"auth": "asdf=",
		"email": "example@example.com"
	},
	"https://hub.example.com:1024": {
		"auth": "asdf=",
		"email": "example@example.com"
	}
}```
Without the https block, I was logged in from console (core user), but kubelet would throw auth errors (even when the `.dockercfg` file in its working directory, `/root/`, exists and is readable).

**Comment by jjw27** [comment]
I noticed "docker login" wraps this "auths" json tag around the output in /root/.docker/config.json 
When I copied it into  /.dockercfg  I had to remove it:

Did not work:
{
	"auths": {
                    "hub.example.com:1024": {
                     "auth": "asdf=",
                     "email": "example@example.com"
                      }
}


Worked:
{
       "hub.example.com:1024": {
        "auth": "asdf=",
        "email": "example@example.com"
 }

**Comment by danielwhatmuff** [comment]
On rhel 7, check the kubelet home directory in the kublet.service unit file and place the dockercfg in there, then restart kubelet. You need to remove the auths line and add https:// too.

**Comment by gajus** [comment]
Note that the current kubectl version (v1.4.6) does not support v2 API,

* https://github.com/kubernetes/kubernetes/blob/60a34fda0a5a22c715d33f851f761614069f93a1/pkg/kubectl/cmd/util/factory_client_access.go#L455

Therefore, this will not work:

```bash
kubectl create secret docker-registry dockerio --docker-server=http://127.0.0.1:5000/v2/ --docker-username=gajus --docker-password=gajus --docker-email=gajus@gajus.com
```

You need to explicitly specify that you are using v1, i.e.

```bash
kubectl create secret docker-registry dockerio --docker-server=http://127.0.0.1:5000/v1/ --docker-username=gajus --docker-password=gajus --docker-email=gajus@gajus.com
```

Sadly, the event log does not include any information to detect this:

```
2016-12-29 19:12:02 +0200 EET   2016-12-29 19:01:04 +0200 EET   7         gajus-com-1623401367-hdwvp   Pod          spec.initContainers{create-workdir-volume}   Normal    Pulling             {kubelet minikube}         pulling image "gajus/gajus.com:v1.0.0"
2016-12-29 19:12:05 +0200 EET   2016-12-29 19:01:06 +0200 EET   7         gajus-com-1623401367-hdwvp   Pod                                                       Warning   FailedSync          {kubelet minikube}         Error syncing pod, skipping: failed to "StartContainer" for "create-workdir-volume" with ErrImagePull: "Error: image gajus/gajus.com not found"

```

**Comment by gajus** [comment]
Ignore my comment. Something else is off.

**Comment by chokhareganesh** [comment]
This works with me
1) docker login on each node
2) generate secret `kubectl create secret docker-registry <secret-name> --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>`

OR
you can docker login on a single node, run `kubectl create secret` and send /root/.docker/config.json all minion 
[https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
[https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry)
