### ISSUE TITLE
Kubelet keeps failing 

### ISSUE THREAD

**Issue by blessedwithsins** [kubernetes/kubernetes#79556]
Hi Team,

I'm trying to install Kubernetes HA cluster on GCP using GCE. I'm not using GKE for this purpose and trying to use Kubeadm to do the same. However, on my nodes Kubelet keeps failing even after attempting several times.

Below is the error along with details:-

root@kube-master-1:/etc/systemd/system/kubelet.service.d# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider is GCP.

root@kube-master-1:/etc/systemd/system/kubelet.service.d# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@kube-master-1:/etc/systemd/system/kubelet.service.d# 

root@kube-master-1:/etc/systemd/system/kubelet.service.d# uname -a
Linux kube-master-1 4.15.0-1034-gcp #36-Ubuntu SMP Thu Jun 6 14:47:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@kube-master-1:/etc/systemd/system/kubelet.service.d#

root@kube-master-1:/etc/systemd/system/kubelet.service.d# docker info 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1034-gcp
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.607GiB
Name: kube-master-1
ID: QULN:TPJX:VRON:JG43:EFJO:JIQN:BGC2:KBVS:RNW5:XU4J:EAJS:25I2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@kube-master-1:/etc/systemd/system/kubelet.service.d# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:24:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
root@kube-master-1:/etc/systemd/system/kubelet.service.d#

Error logs fetched via Journalctl:-

-- Logs begin at Sat 2019-06-29 04:36:53 UTC, end at Sat 2019-06-29 05:50:31 UTC. --
Jun 29 04:45:45 kube-master-1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.733613    3660 server.go:407] Version: v1.13.5
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.734528    3660 plugins.go:103] No cloud provider specified.
Jun 29 04:45:46 kube-master-1 kubelet[3660]: W0629 04:45:46.740389    3660 server.go:552] standalone mode, no API client
Jun 29 04:45:46 kube-master-1 kubelet[3660]: W0629 04:45:46.762681    3660 server.go:464] No api server defined - no events will be sent to API server.
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.762708    3660 server.go:666] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.763077    3660 container_manager_linux.go:248] container manager verified user specified cgroup-root exists: []
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.763092    3660 container_manager_linux.go:253] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms}
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.764019    3660 container_manager_linux.go:272] Creating device plugin manager: true
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.764133    3660 state_mem.go:36] [cpumanager] initializing new in-memory state store
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.775100    3660 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Jun 29 04:45:46 kube-master-1 kubelet[3660]: I0629 04:45:46.778873    3660 client.go:104] Start docker client with request timeout=2m0s
Jun 29 04:45:46 kube-master-1 kubelet[3660]: E0629 04:45:46.782105    3660 kube_docker_client.go:91] failed to retrieve docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 29 04:45:46 kube-master-1 kubelet[3660]: W0629 04:45:46.782427    3660 kube_docker_client.go:92] Using empty version for docker client, this may sometimes cause compatibility issue.
Jun 29 04:45:46 kube-master-1 kubelet[3660]: F0629 04:45:46.782958    3660 server.go:261] failed to run Kubelet: failed to create kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 29 04:45:46 kube-master-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 29 04:45:46 kube-master-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 29 04:45:50 kube-master-1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 29 04:45:50 kube-master-1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 29 04:45:50 kube-master-1 kubelet[4537]: F0629 04:45:50.781562    4537 server.go:189] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jun 29 04:45:50 kube-master-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 29 04:45:50 kube-master-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 29 04:46:01 kube-master-1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 29 04:46:01 kube-master-1 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
Jun 29 04:46:01 kube-master-1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 29 04:46:01 kube-master-1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 29 04:46:01 kube-master-1 kubelet[4955]: F0629 04:46:01.121258    4955 server.go:189] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jun 29 04:46:01 kube-master-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 29 04:46:01 kube-master-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 29 04:46:11 kube-master-1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 29 04:46:11 kube-master-1 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2.
Jun 29 04:46:11 kube-master-1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 29 04:46:11 kube-master-1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 29 04:46:11 kube-master-1 kubelet[4983]: F0629 04:46:11.358802    4983 server.go:189] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jun 29 04:46:11 kube-master-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 29 04:46:11 kube-master-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 29 04:46:21 kube-master-1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 29 04:46:21 kube-master-1 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 3.
Jun 29 04:46:21 kube-master-1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 29 04:46:21 kube-master-1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 29 04:46:21 kube-master-1 kubelet[5013]: F0629 04:46:21.605749    5013 server.go:189] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jun 29 04:46:21 kube-master-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 29 04:46:21 kube-master-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 29 04:46:31 kube-master-1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 29 04:46:31 kube-master-1 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4.
Jun 29 04:46:31 kube-master-1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 29 04:46:31 kube-master-1 systemd[1]: Started kubelet: The Kubernetes Node Agent.

/sig GCP
/sig node
/Sig Architecture

**Comment by mattjmcnaughton** [comment]
Updating sigs to what I think will give the best chance of us getting helpful eyes on this :)

/remove-sig node
/sig cluster-lifecycle

**Comment by tedyu** [comment]
```
open /var/lib/kubelet/config.yaml: no such file or directory
```
@blessedwithsins 
Have you tried adding the above file ?

**Comment by neolit123** [comment]
`/var/lib/kubelet/config.yaml` is a file that `kubeadm init/join` generates

**Comment by robbierafay** [comment]
I am having similar issue . I am trying to run `kubeadm init` on a fresh Ubuntu 18 install on GCP with k8s 1.15.0 and docker version 18.09.5. For some reason the kubeadm install fails as kubelet  fails health check. kubelet process is running but is not listening on health check port 10248 and also none  of the static pods are getting started. 

Killing kubelet and  running it manually with increased verbosity shows that kubelet gets close to launching static pods but never does

[kubelet_logs_with_increased_verbosity.txt](https://github.com/kubernetes/kubernetes/files/3348616/kubelet_logs_with_increased_verbosity.txt)

**Comment by neolit123** [comment]
on a quick look i don't see any errors in the above log.

> --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice

^ did you set these?

please share your kubeadm configuration file or any flags you pass to `kubeadm`

**Comment by robbierafay** [comment]
Yes neolit123, used thise flags for kubelet. Was simply doing kubeadm init --pod-network-cidr=10.244.0.0/16 

Noticed this error in logs 

I0702 08:01:52.288620   20022 metadata.go:212] Failed to Get service accounts from gce metadata server: Get http://metadata.google.internal./computeMetadata/v1/instance/service-accounts/: dial tcp: lookup metadata.google.internal. on 127.0.0.1:53: no such host

Realized we were using consul as DNS server, changed that to use GCP native DNS server and kubeadm init worked fine.

**Comment by robbierafay** [comment]
I think I was hitting https://github.com/kubernetes/kubernetes/issues/30195

**Comment by blessedwithsins** [comment]
This issue doesn't happen If i switch to Ubuntu 16.04 Xenial LTS release. Happens only with using GCE with Ubuntu 18.04 Xenial LTS.

**Comment by blessedwithsins** [comment]
> on a quick look i don't see any errors in the above log.
> 
> > --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice
> 
> ^ did you set these?
> 
> please share your kubeadm configuration file or any flags you pass to `kubeadm`

This has already been set and I'm using systemd as cgroup driver which is advised.

**Comment by xzy256** [comment]
I occur same issue at Centos 7, kubeadm 1.15.1, when executing `kubeadm init --kubernetes-version=1.15.1 --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.145.67.213`. 
> [kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
