### ISSUE TITLE
Verify namespace deletion during e2e AfterSuite rather than AfterEach test

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#79564]
**What would you like to be added**:

Move per test namespace deletion from AfterEach test to AfterSuite.

**Why is this needed**:

We will be creation hundreds to thousands of new e2e tests.
We create a namespace for each one.
After the test, we need to delete them.
This currently extends each test by usually 20+ or more seconds.

**Comment by hh** [comment]
During the `BeforeEach`, when we create the namespace, is there an existing way to track the creation (to ensure/observe deletion later)?

`BeforeEach` => call to `f.CreateNamespace()`:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L215

Within `AfterEach` we call `deleteNS`

`AfterEach` => call to `deleteNS()`
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L309

This is where we could replace the `wait` with 'delete call succeeded'?

util => func `deleteNS()` definition *this is where we spend ~20+ seconds per test*
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L852-L911

The verification/observation could occur just before we start dumping reports and gathering metrics?

`SynchronizedAfterSuite()` => Run only on Gingko node 1
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L168-L172

**Comment by hh** [comment]
/area conformance
/area test

@kubernetes/cncf-conformance-wg

**Comment by smarterclayton** [comment]
The namespace serial tests call utility methods that wait for namespaces to be deleted.  If we change aftertest to not wait, we have to check those preconditions still hold.

The biggest impact of this change is that parallel tests will execute faster, increasing the load on the apiserver and controller manager, which may change performance tests or expose additional flakes in our tests.  It should be possible to see the impact just from a simple PR and soak out any issues there before we merge.

**Comment by hh** [comment]
@johnSchnake suggested an alternative verification/observation point within a custom reporter that shoots off necessary cleanup.

**Comment by hh** [comment]
@smarterclayton @johnSchnake should we go ahead and start on this or do either of you have an implementation started?

**Comment by johnSchnake** [comment]
I don't have an implementation started; 👍 to starting on it if you have the time.

**Comment by liggitt** [comment]
e2e deletion made asynchronous in https://github.com/kubernetes/kubernetes/pull/82439

/close
