### ISSUE TITLE
kubelet: Images with the same size on a node do not have a stable order

### ISSUE THREAD

**Issue by cezarsa** [kubernetes/kubernetes#79577]
**What happened**:

When two or more images on a given node have the same size, their order inside the `node.status.images` field set by the `kubelet` process is not deterministic.

This problem has the side effect of continually triggering controllers which assume this list to be always equal on node updates unless images are added or removed.

**What you expected to happen**:

The order of images should be stable even when two images have the same size, using the image ID as a second sort field would help this.

**How to reproduce it (as minimally and precisely as possible)**:

Choose a node and run:

```
docker commit $(docker create busybox) busybox2
```

Run a few times:

```
kubectl get node <chosen node> -o yaml | grep busybox
```

It should be possible to see `busybox` and `busybox2` images alternating on the output.

**Anything else we need to know?**:

Our particular use case make it really common for multiple images to have the same size on a given node. I came across this problem while debugging slow updates to DaemonSets and finding out that the kube-controller-manager was leaking memory until it eventually dies due to OOM:

<img width="800" alt="Screen Shot 2019-06-30 at 20 27 22" src="https://user-images.githubusercontent.com/11041/60403616-ebbcab00-9b75-11e9-87e6-887cf8e3cd09.png">

I was able to track this leak to a large number of watched elements in memory and by taking a look at the logs with increased verbosity I figured it was due to too many Node notifications being processed by the DaemonSet controller:

<img width="800" alt="Screen Shot 2019-06-30 at 20 36 23" src="https://user-images.githubusercontent.com/11041/60403704-41de1e00-9b77-11e9-8aee-5d22d2b3f4d5.png">

It's possible that other controllers in the wild that watch nodes and only ignore the conditions timestamps on updates to face the same problem.

I'll send a simple PR to fix this shortly.

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

But by taking a look at the code this problem also happens on master.

**Comment by mattjmcnaughton** [comment]
Nice debugging here :)
