### ISSUE TITLE
Draining a node with a pod that uses an AWS NLB does not deregister instances or close the nodeports on said node

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#79581]
**What happened**: Using a pod like the nginx-ing-cntlr with an AWS Network Load Balancer (NLB), and then draining the node its running on to force a migration to another node pool, does not reliably deregister the drained nodes from the NLB Target group. This causes the nodeport used by the NLB to remain open, and the drained node ends up continuing to funnel traffic for other pods cause of `externalTrafficPolicy: Cluster` being used. This leads to connection timeouts for clients, and downtime on migrations.

Switching to a Classic ELB, instead of an NLB, with connection draining enabled does work, and the instances that are drained are practically removed immediately from the instances targeted by the ELB, as expected. There seems to be some sort of issue with NLB's as this is not happening, or happening rarely (only saw it once in many tests but couldn't recreate it).

The node + LB [sync](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L643) set seems to be working as I see in the controller-mgr logs that the nodes are updated as I went from 11 nodes to 8, after attempting to drain + migrate a nodepool of 3 nodes with nginx-ing-cntlr all running on them:

```
I0630 22:08:34.548236 7 service_controller.go:639] Detected change in list of current cluster nodes. New node set: map[ip-172-16-153-92.us-east-2.compute.internal:
{}
ip-172-16-107-18.us-east-2.compute.internal:
{}
ip-172-16-131-114.us-east-2.compute.internal:
{}
ip-172-16-175-60.us-east-2.compute.internal:
{}
ip-172-16-100-188.us-east-2.compute.internal:
{}
ip-172-16-110-179.us-east-2.compute.internal:
{}
ip-172-16-173-181.us-east-2.compute.internal:
{}
ip-172-16-183-203.us-east-2.compute.internal:
{}
]

22:08:34
I0630 22:08:34.845543 7 service_controller.go:647] Successfully updated 6 out of 6 load balancers to direct traffic to the updated set of nodes
I0630 22:08:34.845543 7 service_controller.go:647] Successfully updated 6 out of 6 load balancers to direct traffic to the updated set of nodes
```

However, this update does not seem to be translating into deregistering instances from the NLB. And i've waited minutes & hours in case timeouts were playing a hand, but that didn't seem to help.

**What you expected to happen**: On node draining, with `externalTrafficPolicy: Cluster` being used, that the NLB would deregister the instances as expected.

**How to reproduce it (as minimally and precisely as possible)**: Launch a Deployment + NLB service on a node and drain it to force it over to another node pool. Watch the instances in the AWS NLB Target group never get out of "healthy" status or be drained + removed.

**Anything else we need to know?**:

**Environment**: AWS EKS
- Kubernetes version (use `kubectl version`): 1.12 & 1.13
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): AWS Linux 2
- Kernel (e.g. `uname -a`): 4.14.123-111.109.amzn2.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug): core-dns v1.2.6
- Others:

**Comment by metral** [comment]
Related:
- https://github.com/kubernetes/kubernetes/issues/65013#issuecomment-422214870
- https://github.com/kubernetes/kubernetes/issues/44997

**Comment by robisoh88** [comment]
cxv
