### ISSUE TITLE
container level TerminationGracePeriodSeconds

### ISSUE THREAD

**Issue by shimron** [kubernetes/kubernetes#79582]
**What would you like to be added**:
setup TerminationGracePeriodSeconds on container level
**Why is this needed**:
For some reason, pod may have two containers, container A can handle SIGTERM signal，but it may require seconds to half an hour to stop gracefully； container B wouldn't deal the SIGTERM（can be force killed）, so it can only be killed when the termination grace period reached.

In current k8s, we can only setup TerminationGracePeriodSeconds on pod level. In above case, I have to set TerminationGracePeriodSeconds to 1800s for container A，but sometimes container A only need 30s to stop gracefully. In this situation, the pod will stay in removing status for half an hour.  

If we can setup TerminationGracePeriodSeconds=30s for container B, and TerminationGracePeriodSeconds=1800s for container A. I think in some situation, the pod only needs 30s to be removed, not 1800s.

**Comment by RainbowMango** [comment]
IMO, it's not a common case.

> In current k8s, we can only setup TerminationGracePeriodSeconds on pod level. In above case, I have to set TerminationGracePeriodSeconds to 1800s for container A，but sometimes container A only need 30s to stop gracefully. In this situation, the pod will stay in removing status for half an hour.

I guess you ignored SIGTERM signal for container B, why do you do that? Why not just terminate in case of SIGTERM signal?

> container A can handle SIGTERM signal，but it may require seconds to half an hour to stop gracefully

It's unusual for a container to take so long time to stop.

**Comment by shimron** [comment]
@RainbowMango   Indeed, container B ignored SIGTERM while it was started with a bunch of shell scripts (bash -c) to do some init steps and share php scripts to container A.  

Container A is an nsq consumer  written in go which is used to execute php scripts based on the nsq message info.  For some reason, the execution of  php scripts may take a long time to complete, the maximum time could be half an hour. 

So, when container A receives SIGTERM, it's possible to need half an hour to stop gracefully in my case.
