### ISSUE TITLE
E2E Proposal: New E2E to ensure pods are scheduled to same nodes always

### ISSUE THREAD

**Issue by globervinodhn** [kubernetes/kubernetes#79590]
**What would you like to be added**: The new E2Es are needed to check that the pod satisfying the underlying conditions is scheduled to same nodes in each run.

**Why is this needed**: To validate pod scheduling based on node affinity/node Selector

**Plan for test yaml using Node Selector:**
1. Acquire a node from the cluster, say Node1
2. Taint Node1 with 'test-blue' with NoSchedule effect. Also, add nodeSelector label as 'node1:test-blue'
3. Acquire the second node from the cluster, say Node2
4. Ensure that the Node2 is removed of all taints and had no taints or any other restrictions.
5. Create 2 pods,
	- Pod1 with toleration for 'test-blue' and nodeSelector label as 'node1:test-blue'
	- Pod2 with no toleration
6. Schedule the pods,
	- Pod1 to be scheduled on Node1
	- Pod2 on Node2

Note: The same test should also be written using Node Affinity.

@mgdevstack

**Comment by alejandrox1** [comment]
This doesnt belong to sig testing. Let's relabel and look for this
/remove-lifecycle rotten
/remove-sig testing
/sig apps
/cc @kubernetes/sig-node-proposals 
/priority backlog
