### ISSUE TITLE
pull-kubernetes-e2e-aks-engine-azure consistently failing

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#79597]
**Which jobs are failing**:
pull-kubernetes-e2e-aks-engine-azure

**Which test(s) are failing**:
`Up`

**Since when has it been failing**:
[2019-05-10 05:20:51 +0000 UTC](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/77719/pull-kubernetes-e2e-aks-engine-azure/1126718651890667520) 

**Testgrid link**:
No Testgrid, but job history: https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure

**Reason for failure**:
```
error creating cluster: cannot deploy: cannot get the create deployment future response: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=30\\n[stdout]\\n\\n[stderr]\\nConnection to k8s.gcr.io 443 port [tcp/https] succeeded!\\nConnection to gcr.io 443 port [tcp/https] succeeded!\\nConnection to docker.io 443 port [tcp/https] succeeded!\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
```

**Anything else we need to know**:
ref: https://github.com/kubernetes/kubernetes/pull/79583#issuecomment-507224973

**Comment by justaugustus** [comment]
@kubernetes/sig-azure 
/assign @ritazh 
cc: @feiskyer @andyzhangx @khenidak 
/milestone v1.16
/priority important-soon

**Comment by feiskyer** [comment]
Related with https://github.com/Azure/aks-engine/pull/1548

**Comment by feiskyer** [comment]
Update: https://github.com/Azure/aks-engine/pull/1626 has been merged, but a new release with this change is not available yet. Pending on aks-engine's next release.

**Comment by CecileRobertMichon** [comment]
v1.16.0-alpha.1 is available in https://github.com/Azure/aks-engine/releases/tag/v0.39.0

**Comment by ritazh** [comment]
Will submit a PR after testing this in our own prow first.
