### ISSUE TITLE
Scheduler: affinity priority function lists nodes from the informer cache instead of scheduler cache

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#79629]
**What happened**:
#79076 modified the scheduler configuration such that NodeInfo is read from the scheduler cache. [NodeInfo is used in calculating pod affinity priority along with NodeLister](https://github.com/kubernetes/kubernetes/blob/38e8b8a9f65e66b779a0985e17868b036c1d601b/pkg/scheduler/algorithmprovider/defaults/register_priorities.go#L73). NodeLister is a light wrapper around a corelisters.NodeLister, which reads from the informer cache.

Listing nodes from one cache, while reading their info from another can potentially lead to issues similar to the ones described in #73956 

**What you expected to happen**:
Predicates and priority functions should read from the scheduler cache for consistency.

/kind bug
/sig scheduling
/help

**Comment by ahg-g** [comment]
@alculquicondor this is a good starter bug.

@draveness do you mind if Aldo works on this one?

**Comment by draveness** [comment]
Of course not, please take it. And I’m glad to provide help.

Regards,
Draven

**Comment by ahg-g** [comment]
Thanks Draven, @alculquicondor we will consider assigned to you.

**Comment by alculquicondor** [comment]
Ack, thanks
