### ISSUE TITLE
Allow to scheduler (extender) to update Pod Env: NVIDIA_VISIBLE_DEVICES 

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/kubernetes#79635]
**What would you like to be added**:
Allow to scheduler (extender) to update Pod Env: NVIDIA_VISIBLE_DEVICES.

**Why is this needed**:
Currently, it is too tedious and complicated to let scheduler extender or a standalone scheduler to pass GPU placement decision (e.g. Node: A, GpuIndex: 2,3) to nvidia-container-runtime.

This is because the device plugin Allocate() rpc, can only know the GPU placement decision from kubelet (not aware the decision from scheduler), and it does not even know which pod is currenly being Allocated. So, the device plugin cannot anyway to get GPU placement decision from scheduler.
Finally, many devs have to turn to implement a Custom Container Runtime Interface (CRI), which is too heavy, tedious and complicated.

A simple approach to solve it, is to let scheduler (extender) is able to directly update Pod Env: NVIDIA_VISIBLE_DEVICES, given that the Pod Env will override the env generated from the device plugin (i.e. the kubelet decision).

**However, currently, if a Pod object is created, its Env cannot be updated, even if the Pod has not bound to a Node. 
So, can we relax the validation?** 
Below is the Pod update validation error:
```
invalid: spec: Forbidden: pod updates may not change fields other than 
`spec.containers[*].image`, 
`spec.initContainers[*].image`, 
`spec.activeDeadlineSeconds` or 
`spec.tolerations` (only additions to existing tolerations)\n

```
Another simple apporach is to let scheduler (extender) to update Pod currently updated fields, such as annotation, but the annotation need to be able to be refered by Pod Env fieldRef. 
**However, currently, Pod Env fieldRef cannot be specified to an annotation of the Pod.
So, can we make an enhancement for this?**
Below is the Pod create validation error:
```
 'Pod "scheduler-test-gpu-anno" is invalid: spec.containers[0].env[0].valueFrom.fieldRef.fieldPath:
  Unsupported value: "metadata.annotations": supported values: "metadata.name", "metadata.namespace",
  "metadata.uid", "spec.nodeName", "spec.serviceAccountName", "status.hostIP", "status.podIP"'
```
_We currently plan to workaround this by set Pod Env configMapKeyRef, but this need to create a configMap per pod, and need to manage the life cycle of the configMap._

**Any comments for this?
And welcome for more simple apporaches or an eventual solution :)**

**Comment by liggitt** [comment]
you can use `metadata.annotations['annotationname']` as a `valueFrom.fieldRef.fieldPath`

**Comment by liggitt** [comment]
see https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

**Comment by yqwang-ms** [comment]
Thanks @liggitt , I do see you can use [this ](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api) to inject as a file, but I want to inject as Env NVIDIA_VISIBLE_DEVICES, and only in this way nvidia-container-runtime can pick it up.

For Env fieldRef seems different, please check current validation:
https://github.com/kubernetes/kubernetes/blob/6d8dd211111474f277ef8e390a3eeed2465fb9e0/pkg/apis/core/validation/validation.go#L2074

And the Volume fieldRef validation:
https://github.com/kubernetes/kubernetes/blob/6d8dd211111474f277ef8e390a3eeed2465fb9e0/pkg/apis/core/validation/validation.go#L951

**Comment by liggitt** [comment]
The expression I referenced works as an envvar as well. See https://github.com/kubernetes/kubernetes/blob/6d8dd211111474f277ef8e390a3eeed2465fb9e0/pkg/apis/core/validation/validation.go#L2141-L2153

There's an e2e test that makes use of it here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/expansion.go#L341-L347

**Comment by yqwang-ms** [comment]
Great!!! Thanks @liggitt

**Comment by yqwang-ms** [comment]
@liggitt BTW, can we allow scheduler (extender) to add Pod resource limit (such as cpu, memory) if they are not specified before and the pod is not bound, or support resource limit to refer the annotation?
