### ISSUE TITLE
Feature request: resource quota management for CSI inline volume 

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#79643]
**What would you like to be added**:

`CSI Inline volume` is a really valuable feature for users, but there is no resource quota management for it. 
A common scenario is:
- There is a storage class, which implemented by csi driver like `kubernetes.io.csi.local`,  there is also resource quota setting for this storageclass in user's namespaces.(https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota)
-  User can create a csi inline volume with the same csi driver `kubernetes.io.csi.local`. It will create the volume by the same driver, so if we don’t control the resource quota of  `CSI Inline volume`,  then it will make the  storage resource out of control.

**Why is this needed**:
The resource quota should be managed for `CSI Inline volume`, or we will lose the control of capacity.

Further more:
- If we need to do resource quota management for `CSI Inline Volume`, it should need to get the size of the volume, but there is no such field according to the design. What's the reason for this?

- We can make emptyDir to use CSI drivers volumes as well, so that emptyDir can have more mediums but not limited to root disk/memory/hugepage. User can  extend emptyDir mediums easily.

@msau42  @vladimirvivien  @xing-yang  @jsafrane  @gnufied   PTAL, thanks

**Comment by msau42** [comment]
cc @vladimirvivien @pohly @kfox1111

@kubernetes/sig-storage-feature-requests

**Comment by kfox1111** [comment]
Quota on ephemeral volumes can be complicated. Take for example, the image driver:
https://github.com/kubernetes-csi/csi-driver-image-populator
Since it uses container instances as a backing store, the usage could be 100% the image, or less depending on who else is using the image. Do you count any/all of of that, some or none? Just the changes the user wrote on top?

emptyDir also needs to stay separate from csi, as csi needs emptyDir to deploy drivers.

Not saying its a bad thing to figure out how quota should work, just that its much more complicated then it seems on the surface.

I'm still focused on getting a stable release of the base ephemeral support before diving into quota.

**Comment by wenlxie** [comment]
@msau42  @kfox1111  Thanks for reply

> Quota on ephemeral volumes can be complicated. Take for example, the image driver:
> https://github.com/kubernetes-csi/csi-driver-image-populator
> Since it uses container instances as a backing store, the usage could be 100% the image, or less depending on who else is using the image. Do you count any/all of of that, some or none? Just the changes the user wrote on top?

I do agree some kind of ephemeral volumes provided by some csi driver is hard to define the usage and set the quota, but the case I list is a bit different with this. 
More typical scenario is the csi ephemeral volumes use the same driver with storage class.  For storage class, user need to specific the request size of PVC, so it doesn't have the issue for how to  define the request size and usage.   

> 
> emptyDir also needs to stay separate from csi, as csi needs emptyDir to deploy drivers.
> 

I am not saying we need to remove emptyDir to CSI. 
I mean we can extend the emptyDir plugin to user CSI driver.  
For example:
 1.  I have a csi driver to provision local disk, the storage backend is from an LVM
 2.  I can create a PVC to request the storage
 3.  With `CSI inline volume` feature, I can deploy a pod to use local disk as ephemeral volumes
 4.  `emptyDIr` now have disk/memory/hugepage medium, how to extend it to use lvm or other kind of storage as the medium?  My idea is we can extend emptyDir to have another medium, for example `csi` ,  then it can call the csi driver to allocate and mount the volume. 
 5. With this, the same storage backend can be provided as: PVC, CSI inline volume and emptyDIr.
