### ISSUE TITLE
[Failing Test] Uses kubeadm/kinder to run kubeadm-e2e and e2e tests against a cluster created using kinder's skew-master-on-stable workflow

### ISSUE THREAD

**Issue by soggiest** [kubernetes/kubernetes#79669]
**Which jobs are failing**:
ci-kubernetes-e2e-kubeadm-kinder-master-on-stable

**Which test(s) are failing**:
task-09-reset
task-10-delete
task-01-add-kubernetes-versions

**Since when has it been failing**:
07/02/2019 

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master-on-stable

**Reason for failure**:
```
# task-06-e2e-kubeadm
kinder test e2e-kubeadm --test-flags=--report-dir=/logs/artifacts --report-prefix=e2e-kubeadm-after-upgrade --name=kinder-xony

 skipping because a predecessor task failed

# task-07-e2e
kinder test e2e --test-flags=--report-dir=/logs/artifacts --report-prefix=05-e2e --parallel --name=kinder-xony

 skipping because a predecessor task failed

# task-08-get-logs
kinder export logs --loglevel=debug --name=kinder-xony /logs/artifacts

time="15:46:47" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
Error: unknown cluster "kinder-xony"
 completed!

# task-09-reset
kinder do kubeadm-reset --name=kinder-xony

Error: a cluster with the name "kinder-xony" does not exists
 exit status 1

# task-10-delete
kinder delete cluster --name=kinder-xony

Error: unknown cluster "kinder-xony"
 exit status 1

Ran 5 of 11 tasks in 0.000 seconds
FAIL! -- 2 tasks Passed | 3 Failed | 6 Skipped

see junit-runner.xml and task logs files for more details

Error: failed executing the workflow
+ EXIT_VALUE=1
+ set +o xtrace
Cleaning up after docker in docker.
```

**Anything else we need to know**:
Looks related to #79668 

/cc @kubernetes/sig-cluster-lifecycle 
/milestone v1.16
/priority critical-urgent
/kind failing-test
/cc @Verolop @jimangel @soggiest @alenkacz

**Comment by neolit123** [comment]
see https://github.com/kubernetes/kubernetes/issues/79668#issuecomment-507757951

/assign
/sig testing

**Comment by neolit123** [comment]
after this merged the CI should stabilize:
https://github.com/kubernetes/release/pull/814
please check again tomorrow.

**Comment by soggiest** [comment]
Will do!

**Comment by justaugustus** [comment]
This was caused by changes to the build/release tooling, which have since been reverted (https://github.com/kubernetes/release/pull/814).

Here is the first green run of the tests since the k/release revert:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master-on-stable/1146477984689950724

Closing this out, but continued discussion on tooling/process improvement is happening here: https://github.com/kubernetes/release/issues/816
/close
/assign
/sig release
