### ISSUE TITLE
[Failing Test]  Nodes resize test failing in master-blocking

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#79662]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
* [sig-cluster-lifecycle] Nodes [Disruptive] Resize [Slow] should be able to add nodes
* [sig-cluster-lifecycle] Nodes [Disruptive] Resize [Slow] should be able to delete nodes 

**Since when has it been failing**:
These tests have been failing since 6/28
Failures coincide with the following changes: https://github.com/kubernetes/kubernetes/compare/967b23c72...665e76d97

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:
The failure messages look as follows:

[sig-cluster-lifecycle] Nodes [Disruptive] Resize [Slow] should be able to add nodes 
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:142
Unexpected error:
    <*errors.errorString | 0xc002efc270>: {
        s: "failed to wait for pods responding: timed out waiting for the condition",
    }
    failed to wait for pods responding: timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:152
```

[sig-cluster-lifecycle] Nodes [Disruptive] Resize [Slow] should be able to delete nodes 
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:112
Unexpected error:
    <*errors.errorString | 0xc0024c7650>: {
        s: "failed to wait for pods responding: timed out waiting for the condition",
    }
    failed to wait for pods responding: timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/resize_nodes.go:121
```

/cc @kubernetes/sig-cluster-lifecycle 
/milestone v1.16
/priority critical-urgent
/kind failing-test
/cc @Verolop @jimangel @soggiest @alenkacz

**Comment by alejandrox1** [comment]
For more context, the code for the failing tests is here 👀 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/lifecycle/resize_nodes.go

**Comment by justinsb** [comment]
I think agnhost needs to be passed `Args:  []string{"serve-hostname"},`, but https://github.com/kubernetes/kubernetes/pull/79238/files did not do so in test/e2e/common/util.go

/assign sig-testing

**Comment by alejandrox1** [comment]
Reopen to monitor job
/reopen

**Comment by alejandrox1** [comment]
Thank you @jeefy for working on the PR to solve this.
 #80615 indeed solved the issue reported here.
/close
