### ISSUE TITLE
Add e2e test(s) for volume scheduling limits

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#79660]
Right now, we have e2e test for [volume scheduling limits](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190408-volume-scheduling-limits.md) that executes only CSI mock driver with artificial limit of 2 volumes per node.

We need a test with real CSI driver(s).

Proposal:

* Allow individual test storage drivers to specify if they support CSI limits.
* Add a test that picks a random node and creates as many pods with a PV that the volume can handle (128 on GCE!).
* Check that the node can't handle any other volume.
* Make this test part of [CSI external test suite](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external).

* Add similar test(s) for in-tree volume plugins.
* Make sure the tests work with in-tree volume plugins migrated to CSI.

**Comment by alejandrox1** [comment]
This sounds important
/remove-lifecycle rotten
/lifecycle frozen

**Comment by davidz627** [comment]
To add to this I believe we should test that an in-tree plugin and its "replacement" CSI Driver share the same attach limits (both max and current usage)

**Comment by wongma7** [comment]
I see this  test has been added here: https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/e2e/storage/testsuites/volumelimits.go#L123

But I want to add a more basic/faster version of the test that simply checks if a driver has `CapVolumeLimits` then `attachable` has been set in CSINode, similar to https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/e2e/storage/volume_limits.go#L41

@jsafrane wdyt, would it be useful?

**Comment by jsafrane** [comment]
This is a really old issue :-D. I think the required test has been implemented, however, we do not run it in CI, because it takes too much time to provision 128 PDs that a GCP node can handle.

/unassign

> But I want to add a more basic/faster version of the test that simply checks if a driver has CapVolumeLimits then attachable has been set in CSINode

That sounds useful!

**Comment by wongma7** [comment]
/assign

opened #103074 to close this for good :)
