### ISSUE TITLE
kubectl help for commands with boolean options is misleading

### ISSUE THREAD

**Issue by ramnar** [kubernetes/kubernetes#79687]
**What happened**:
kubectl version --help has the following section.

Options:
  -c, --client=false: Client version only (no server required).
  -o, --output='': One of 'yaml' or 'json'.
      --short=false: Print just the version number.

**What you expected to happen**:
It should actually be 

Options:
  -c, **--client=true**: Client version only (no server required).
  -o, --output='': One of 'yaml' or 'json'.
      **--short=true**: Print just the version number.

It looks like --client=false will display only client version and --short=false will just print the version number. But that is not the case. This issue is there for all the kubectl help commands with boolean options. 

**How to reproduce it (as minimally and precisely as possible)**:
Run the command

kubectl version --help
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15
- Cloud provider or hardware configuration:AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ramnar** [comment]
@kubernetes/sig-cli
/sig cli

**Comment by tanshanshan** [comment]
--client default value is false if you use true ,it means  `Client version only (no server required)`.
--short default value is false , if you use true ,it means `Print just the version number.`
so ,I think it is right.

**Comment by ramnar** [comment]
> --client default value is false if you use true ,it means `Client version only (no server required)`.
> --short default value is false , if you use true ,it means `Print just the version number.`
> so ,I think it is right.

Hi,
**kubectl version --client** is returning the following. Looks like default value is true. Am i missing something

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}

**Comment by tanshanshan** [comment]
`kubectl version --client ` means you have set --client , the same as `kubectl version --client=true`
