### ISSUE TITLE
Invalid options for some kubectl commands should throw error

### ISSUE THREAD

**Issue by ramnar** [kubernetes/kubernetes#79688]
**What happened**:

**kubectl cluster-info dumpp** is not throwing any error as there is no such option as dumpp.Only option dump is available

Same is the case with the following command
**kubectl version i love kubernetes**

**What you expected to happen**:

Error should be displayed for both the above command

**How to reproduce it (as minimally and precisely as possible)**:

Run the following commands
kubectl cluster-info dumpp
kubectl version i love kubernetes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.15
- Cloud provider or hardware configuration:AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ramnar** [comment]
@kubernetes/sig-cli
/sig cli

**Comment by sukeesh** [comment]
@ramnar Please take a look at this PR #79863. Instead of throwing an error, executing the cmd and showing a warning would be the best thing to do IMO.
