### ISSUE TITLE
Use framework.ExpectEqual() for e2e tests

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#79686]
**What happened**:

After fixing golint failures under `test/e2e`, we need to put `gomega` for each `Expect()` and `Equal()`.
Then common error checking code has become like:

`gomega.Expect(foo).To(gomega.Equal(bar))`

We can replace this code with `framework.ExpectEqual(foo, bar)` which is more readable and easy to be understood what the code does.

Now we have following e2e test directories which can be replaced:
- [x] test/e2e/apimachinery (https://github.com/kubernetes/kubernetes/pull/79685)
- [x] test/e2e/apps (https://github.com/kubernetes/kubernetes/pull/79695)
- [x] test/e2e/auth (https://github.com/kubernetes/kubernetes/pull/79762)
- [x] test/e2e/autoscaling (https://github.com/kubernetes/kubernetes/pull/79765)
- [x] test/e2e/cloud (https://github.com/kubernetes/kubernetes/pull/79821)
- [x] test/e2e/common (https://github.com/kubernetes/kubernetes/pull/79769)
- [ ] test/e2e/framework (https://github.com/kubernetes/kubernetes/pull/79771)
- [x] test/e2e/kubectl (https://github.com/kubernetes/kubernetes/pull/79699)
- [x] test/e2e/lifecycle (https://github.com/kubernetes/kubernetes/pull/79860)
- [x] test/e2e/network (https://github.com/kubernetes/kubernetes/pull/79791)
- [x] test/e2e/node (https://github.com/kubernetes/kubernetes/pull/79792)
- [x] test/e2e/scalability (https://github.com/kubernetes/kubernetes/pull/79842)
- [x] test/e2e/scheduling (https://github.com/kubernetes/kubernetes/pull/79781)
- [x] test/e2e/servicecatalog (https://github.com/kubernetes/kubernetes/pull/79754)
- [x] test/e2e/storage (https://github.com/kubernetes/kubernetes/pull/79755)
- [x] test/e2e/upgrades (https://github.com/kubernetes/kubernetes/pull/79756)
- [x] test/e2e/windows (https://github.com/kubernetes/kubernetes/pull/79756)
- [x] test/e2e_node/apparmor_test.go (https://github.com/kubernetes/kubernetes/pull/80790)
- [x] test/e2e_node/container_log_rotation_test.go (https://github.com/kubernetes/kubernetes/pull/80790)
- [x] test/e2e_node/container_manager_test.go (https://github.com/kubernetes/kubernetes/pull/80790)
- [x] test/e2e_node/critical_pod_test.go (https://github.com/kubernetes/kubernetes/pull/80790)
- [x] test/e2e_node/device_plugin_test.go (https://github.com/kubernetes/kubernetes/pull/80790)
- [x] test/e2e_node/eviction_test.go (https://github.com/kubernetes/kubernetes/pull/80843)
- [x] test/e2e_node/gpu_device_plugin_test.go (https://github.com/kubernetes/kubernetes/pull/80843)
- [x] test/e2e_node/mirror_pod_test.go (https://github.com/kubernetes/kubernetes/pull/80843)
- [x] test/e2e_node/util.go (https://github.com/kubernetes/kubernetes/pull/80843)
- [x] test/e2e_kubeadm/dns_addon_test.go (https://github.com/kubernetes/kubernetes/pull/80795)
- [x] test/e2e_kubeadm/kubeadm_certs_test.go (https://github.com/kubernetes/kubernetes/pull/80795)
- [x] test/e2e_kubeadm/proxy_addon_test.go (https://github.com/kubernetes/kubernetes/pull/80795)

**Comment by k-toyoda-pi** [comment]
I will work test/e2e/kubectl.

**Comment by s-ito-ts** [comment]
I can work test/e2e/scheduling.

**Comment by frankjiao** [comment]
I will work /test/e2e/apps

**Comment by draveness** [comment]
I could work on these file

```go
 test/e2e/servicecatalog
  test/e2e/storage
  test/e2e/upgrades
  test/e2e/windows
```

**Comment by draveness** [comment]
I created #79754  #79755 and #79756 to cleanup gomega in these files, I could take more to work:

```go
 test/e2e/lifecycle
  test/e2e/network
  test/e2e/node
  test/e2e/scalability
```

**Comment by clarklee92** [comment]
I will work for the rest：
`test/e2e/auth`
`test/e2e/autoscaling`
`test/e2e/common`
`test/e2e/framework`

**Comment by draveness** [comment]
/reopen

Regards,
Draven

**Comment by k-toyoda-pi** [comment]
I will work on
```
test/e2e_node/apparmor_test.go
test/e2e_node/container_log_rotation_test.go
test/e2e_node/container_manager_test.go
test/e2e_node/critical_pod_test.go
test/e2e_node/device_plugin_test.go
```

**Comment by s-ito-ts** [comment]
I will work
```
test/e2e_kubeadm/dns_addon_test.go
test/e2e_kubeadm/kubeadm_certs_test.go
test/e2e_kubeadm/proxy_addon_test.go
```

**Comment by draveness** [comment]
I'll work on the rest

```go
 test/e2e_node/eviction_test.go
  test/e2e_node/gpu_device_plugin_test.go
  test/e2e_node/mirror_pod_test.go
  test/e2e_node/util.go
```

**Comment by oomichi** [comment]
@draveness @k-toyoda-pi @s-ito-ts Thanks for raising your hands. All items are fulfilled :-)
