### ISSUE TITLE
agnhost image build failed for ARM arch

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#79689]
**What happened**:

cd $GOPATH/src/k8s.io/kubernetes/test/images/agnhost

$ make
../image-util.sh bin webhook
../image-util.sh: line 145: GOARM: unbound variable
Makefile:23: recipe for target 'bin' failed
make: *** [bin] Error 1

**What you expected to happen**:

The binary or image should be built successfully.

**How to reproduce it (as minimally and precisely as possible)**:
see my desc above, type "make" will see the error message.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
I'm pretty sure this is supposed to be built via `make all WHAT=agnhost` from `test/images` which does default this environment variable.

https://github.com/kubernetes/kubernetes/blob/c8cee54240a0f36264b4de62423617dbc30b57aa/test/images/Makefile#L18

**Comment by chendave** [comment]
@BenTheElder , thanks for the information!
I think the harness of the shell scripts could bring us a little more, 
1.  GOARM should only been set when the ARCH is ARM
2.  Make a binary is possible where a Makefile is presented

**Comment by BenTheElder** [comment]
That seems reasonable, but we should probably avoid computing this in many places, currently the GOARM=${GOARM:-7} is going to always be 7 when building in the currently supported way. 

We should change that if we're going to compute it elsewhere.

cc-ing @cblecker @dims @spiffxp for test/images fun ...
