### ISSUE TITLE
COREDNS dns entry

### ISSUE THREAD

**Issue by Kilz78** [kubernetes/kubernetes#79715]
Hi, 

I saw a lot of topic regarding coreDNS but I do not found any simple topic that explain how to add a DNS entry. I have a kubernetes cluster with CoreDNS. On my old cluster I had just to add some entry in my /etc/hosts and all pods can resolve the entry that I set on my /etc/hosts.

I would like to deploy an application which I need to have some services, and one external storage. So I set up an external storage on the same network that my cluster kubernetes is it. But now I need to add a dns entry, that pods can resolve the ip address of my external storage to contact it. 

I need a really simple way to do it. 

kubeadm :
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

I am using CentOS 7, I have 3 Workers and 3 Masters in order to make a cluster. 

Please help me. 
Thanks you in advance.

**Comment by aojea** [comment]
Can you check this blog https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/?
I think that will solve your scenario
