### ISSUE TITLE
kubelet crashes in calcAndStoreStats when csi node does not support volume stats

### ISSUE THREAD

**Issue by jparklab** [kubernetes/kubernetes#79719]
**What happened**:

kubelet crashed due to nil pointer dereference inside calcAndStoreStats function in pkg/kubelet/server/stats/volume_stat_calculator.go

`Jul 03 06:50:42 kubelet[4440]: E0703 06:50:42.852792    4440 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 03 06:50:42 kubelet[4440]: goroutine 3224 [running]:
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3992120, 0x773bdd0)
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Jul 03 06:50:42 kubelet[4440]: panic(0x3992120, 0x773bdd0)
Jul 03 06:50:42 kubelet[4440]:         /usr/local/go/src/runtime/panic.go:522 +0x1b5 
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc00178ef00, 0xc000c96cc0, 0xe, 0xc0014b8880, 0x0, 0xc000c96cc0, 0xe, 0x0, 0x0, 0x0, ...)
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:141 +0x73
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc00178ef00)
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753 
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc001c02d10)
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Jul 03 06:50:42 kubelet[4440]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c02d10, 0xdf8475800, 0x3ff0000000000000, 0xc000f1dd01, 0xc0012c37a0)
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Jul 03 06:50:42 kubelet[4440]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Jul 03 06:50:42 kubelet[4440]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
`

I think this happens because GetMetrics function can return nil for both metric(https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_metrics.go#L65), and error, but calcAndStoreStats expects error to be not nil when metric is nil(https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/volume_stat_calculator.go#L108)

**What you expected to happen**:

Skip calculating stats for volumes that do not support volume stats.

**How to reproduce it (as minimally and precisely as possible)**:

Create a volume using a csi driver that does not support volume stats.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Server version 15.0
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`): 4.4.0-141-generic
- Install tools:kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
  Tested using synology-csi driver(https://github.com/jparklab/synology-csi)

**Comment by tedyu** [comment]
@jparklab 
Sounds like you have a PR ready.

Mind letting us know the PR number ?

Thanks

**Comment by jparklab** [comment]
I do not have a PR yet, but happy to make one. I'll add the PR number once I created it.

**Comment by jparklab** [comment]
@tedyu I created a PR and linked to this issue.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by humblec** [comment]
@jparklab Didnt this https://github.com/kubernetes/kubernetes/pull/78222/files solve this issue ?

**Comment by jparklab** [comment]
@humblec No, it does not fix the problem that metric itself is nil. Also, my pull request fixes the problem that csi_metrics returns nil value for error and the caller expects non nill value when csi driver does not support metrics.
