### ISSUE TITLE
Include controllers in command line completion of kubectl logs

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#79718]
**What would you like to be added**:
Command line completion of `kubectl logs` currently suggests only pod names, but it should also suggest the names of various controllers (which are also supported by `kubectl logs`). For example:
```
kubectl logs deploy/mydeployment
kubectl logs sts/mystatefulset
kubectl logs rs/myreplicaset
kubectl logs job/myjob
```

**Why is this needed**:
The current completion is incomplete.

**Comment by sroskelley** [comment]
@luksa may I suggest stern as a better alternative? 
https://github.com/wercker/stern/releases
