### ISSUE TITLE
User/Client certificate signing using the certificates.k8s.io API is unable to authenticate with k8s apiserver

### ISSUE THREAD

**Issue by Shuanglu** [kubernetes/kubernetes#79726]
**What happened**:
In AKS-engine cluster, I followed https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/ to generate a client certificate for a test human user.  However with the cert/key I got, I got 401 error when connect to k8s apiserver like "curl --cert <cert> --key <key> '<apiserver>/api/v1/namespaces/default/pods/shell-demo".
I used cfssl to directly generate the cert/key and it works well. Any difference between these two approaches?

**What you expected to happen**:
The cert/key generated by the csr api can be used to verify with k8s apiserver

**How to reproduce it (as minimally and precisely as possible)**:
1. build an AKS-engine cluster
2. follow https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/ to generate the request
3. follow https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/ to configure the user and then run 'kubectl get po --v=6' or use http API directly. it will return error 401

**Anything else we need to know?**:
Use cfssl to generate and it works well.
also found someone who seems is facing the similar issue https://gist.github.com/henning/2dda0b704426c66e78e355703a8dc177#gistcomment-2930352
**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`):"Ubuntu 16.04.6 LTS"
- Kernel (e.g. `uname -a`): 4.15.0-1049-azure
- Install tools: aks-engine
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by micahhausler** [comment]
/remove-sig aws

Looks like an Azure issue, not EKS.

@Shuanglu when you got the 401 with curl, what was the exact curl command you used? Also, what exact commands did you use to generate the CSR and create the CSR request for the kubernetes API?

**Comment by Shuanglu** [comment]
> /remove-sig aws
> 
> Looks like an Azure issue, not EKS.
> 
> @Shuanglu when you got the 401 with curl, what was the exact curl command you used? Also, what exact commands did you use to generate the CSR and create the CSR request for the kubernetes API?

1. what was the exact curl command you used?
curl -k -v -XGET --cert  testuser1.crt --key testuser1-key.pem  'https://192.169.0.4:6443/api/v1/namespaces/default/pods?limit=500'
2. what exact commands did you use to generate the CSR and create the CSR request for the kubernetes API?
cat <<EOF | cfssl genkey - | cfssljson -bare testuser1
{

  "CN": "testuser1",
  "key": {
    "algo": "ecdsa",
    "size": 256
  }
}
EOF

cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: testuser1
spec:
  request: $(cat testuser1.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

kubectl get csr testuser1 -o jsonpath='{.status.certificate}' \
    | base64 --decode > testuser1.crt

Is this a correct approach to generate a client certificate for a human user? i tested with cluster deployed via kubeadm and result is the same

**Comment by liggitt** [comment]
> server auth

that is not correct for a client certificate... that should be "client auth"
