### ISSUE TITLE
e2e tests for CIS compliance on kubeadm

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubernetes#79737]
Part of #683

/kind feature
/area security
/area testing
/milestone v1.16
/priority critical-urgent
/assign @yastij 

Given updated tests in #1648, produce an e2e suite for CIS compliance that vendors can re-use for compliance.

**Comment by timothysc** [comment]
@yastij - needs a KEP on this imo.

**Comment by yastij** [comment]
@timothysc - **if** this issue involves writing a test suite around security, that the community can vendor and re-use, we'll need to track it under k/k and poke sig-auth/testing, wdyt ?

**Comment by timothysc** [comment]
From chatting on steering it appears that there have been a longstanding series of complaints WRT CIS.  I'd ideally like to get some public facing docs and e2e suite that can be pointed at as the k8s-blessed set of tests.  

@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
@kubernetes/sig-node-feature-requests @kubernetes/sig-api-machinery-feature-requests as the other two components the bulk of the CIS recommendations are targeted at

**Comment by raesene** [comment]
@timothysc If there's specific items around the CIS benchmark that are sticking or problematic, we'd be happy to look at those as part of the process of maintaining/upgrading it.

The goal (or at least my goal, as one of the authors) is to produce a workable standard, not somethin that is impractical to implement.  Whilst obviously there'll be some items which only apply to specific environments, there shouldn't be anything in there, which is completely impractical/detrimental to the operation of a cluster.

**Comment by timothysc** [comment]
I'll defer to @randomvariable , as he has the complete list.

**Comment by randomvariable** [comment]
I've logged most of those in the workbench.

We mainly need to come up with new tests to target kubelet componentconfiguration for the published version of the documents now.

**Comment by raesene** [comment]
Awesome thanks :)

We'll try and come up with good modifications for the recommendations.  Any suggestions how the affected items could be worded, would be great.  with more complex configurations, it can be tricky to get a recommendation that covers all the options well.

**Comment by makoscafee** [comment]
@yastij Hello! I'm bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by xmudrii** [comment]
As this issue needs KEP, I'm going to remove it from the milestone until we don't have one.

/milestone clear
