### ISSUE TITLE
Add api to query which admission controller plugin are enabled

### ISSUE THREAD

**Issue by yu2003w** [kubernetes/kubernetes#79735]
**What would you like to be added**:
Added API to query which admission controller plugin are enabled.
**Why is this needed**:
We usually need to know which admission controller plugin are enabled at runtime.
For example, I want to deploy application which needs capability of CAP_NET_ADMIN. 
However, if PodSecurityPolicy is enabled, need to create proper PSP before deploying applications. It's necessary to have a mechanism to determine whether PodSecurityPolicy admission controller is enabled or not at runtime. If so, it's easily to decide to create PSP or not.

**Comment by liggitt** [comment]
This would be part of the component configuration effort. Once there is a versioned, serializable struct representing the apiserver configuration, it would likely be surfaced via a `/configz` endpoint.

**Comment by liggitt** [comment]
note that most API clients would likely not be authorized to call this API

**Comment by liggitt** [comment]
this is a duplicate of https://github.com/kubernetes/kubernetes/issues/54712

/close

**Comment by liggitt** [comment]
actually this is asking for the full admission chain, not specific webhook admission plugins

/reopen
