### ISSUE TITLE
VerifyAttachedVolumes is missing from CSI

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#79743]
**What would you like to be added**:
Support regular verify and bulk verify attach operations in CSI.

**Why is this needed**:
This is important for updating AD controller actual state when volumes may get attached out of band.  For example, a node deletion and recreation (with the same name) can cause volumes to be detached from the node. And AD actual state needs to be updated to retrigger an attach.

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by hantaowang** [comment]
To add more info for this issue, the AttachDetachController currently [checks](https://github.com/kubernetes/kubernetes/blob/932487c7440b05f634da52e82f853fe2aacd5009/pkg/volume/csi/csi_attacher.go#L237) the status of the VolumeAttachment resources to determine if a volume is attached, but those resources may not accurately reflect the actual state of the volumes. 

What should happen is that somehow AD controller needs to know if the volume becomes detached, like by something else updating the VA's status in a resync loop. Currently VA is updated by the external-attacher once it completes the attach RPC to the cluster wide driver. 

I'm not actually sure that CSI as it exists right now can support this. The closest functionality is the list volumes RPC, but there is no place in the [volume](https://github.com/container-storage-interface/spec/blob/master//lib/go/csi/csi.pb.go#L1525:6) struct returned that allows information on where it is attached to be stated. Another option is to try to reattach every volume on resync, but this results in a lot of unnecessary calls to the provider.

**Comment by davidz627** [comment]
https://github.com/kubernetes-csi/external-attacher/pull/184

**Comment by davidz627** [comment]
External attacher v2.1+ will now reconcile and repair incorrect attachments. The code for VerifyAttachedVolumes in the Kubernetes CSI Plugin can actually be removed since it is a no-op.
