### ISSUE TITLE
Add ready field to NodeSpec

### ISSUE THREAD

**Issue by avorima** [kubernetes/kubernetes#79744]
**What would you like to be added**:

A boolean field in the `NodeSpec` that is set to `true` when the node has the condition of type `NodeReady` set to `True`, and `false` otherwise.

**Why is this needed**:

Currently there's no way to create a simple watcher of ready nodes. Instead you just have to watch all nodes and filter out those that aren't ready. Just filtering nodes for `spec.unschedulable` will not yield the correct nodes, because operations like `kubectl cordon` mark a node as unschedulable, but its ready condition doesn't change. In our use-case we'd like to react to add and delete events for ready nodes. This is not possible with the current node spec + field selectors.

I'd be willing to tackle this task myself, I'd just like some input from the maintainers first.

**Comment by avorima** [comment]
Sorry, this is just a shot in the dark because I can't really make out what SIG is affected here but I think it's most likely just an API change
/sig api-machinery

**Comment by mattjmcnaughton** [comment]
Thanks for the idea @avorima !

Since this is an API change to a fairly fundamental type, I think we would most likely want to file a `KEP` for this. Please see https://github.com/kubernetes/enhancements for more info - and please let me know if you have any questions.

**Comment by avorima** [comment]
@mattjmcnaughton Ok, that'll be a first but I'll give it a shot. Should I file the KEP under sig-node?

**Comment by mattjmcnaughton** [comment]
I would think so! Maybe before writing the full sig, we can leave this issue open for a couple of days and see if anyone has thoughts. Additionally, I'd mention your idea in #sig-node on Slack and see if you garner any interest. And possibly even attend the sig-node weekly meeting and present it then :)
