### ISSUE TITLE
Share volumes between deployment and cron job

### ISSUE THREAD

**Issue by OJFord** [kubernetes/kubernetes#79746]
**What would you like to be added**:

Association between `JobSpec/PodTemplate/PodSpec` and a separate `PodSpec` in, for example, a deployment.

**Why is this needed**:

When you have a pod with a few containers sharing some volumes, and then say a `CronJob` that should also do something with these volumes, it feels clumsy to need to specify them twice, once for each controller's `PodSpec`. It also means that `emptyDir` can't be used in this case, since it wouldn't be the same one.

Perhaps this might look something like:
```yaml
volumesFrom:
  podRef:
    deployment: <name>
```

**Comment by OJFord** [comment]
Sorry bot.
/sig api-machinery

**Comment by kow3ns** [comment]
I don't think this is possible, and from a security perspective, I'm not sure its wise. Containers in a [Pod](https://kubernetes.io/docs/concepts/workloads/pods/pod/#what-is-a-pod) share the same network/storage. Allowing two containers from different Pods to cross the isolation boundary breaks the model of the API and isn't safely implementable in Kubelet. Moreover, the technical feasibility of implementation, in terms of DefaultShceduler, Kubelet, and API Server, is low. We are unlikely to implement this. If you think you can address these concerns feel free to offer a KEP to the enhancements repository.
