### ISSUE TITLE
Ceph CSI provisioner volume failed

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#79757]
**What happened**:
I  test in k8s v1.13.0 and deploy two ceph csi plugin then create pvc but can not dynamic create pv and volume

the pvc log is :
Events:
  Type       Reason                Age                   From                                                                                     Message
  ----       ------                ----                  ----                                                                                     -------
  Warning    ProvisioningFailed    5m28s                 cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-0_7bc9dd4a-9d2d-11e9-8e5e-fa163e4279c0  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = an error occurred while running (17) ceph [-m 178.178.178.189:1091,178.178.178.19:1091,178.178.178.188:1091 --id YWRtaW4= --key=***stripped*** -c /etc/ceph/ceph.conf fs get cephfs --format=json]: exit status 1: [errno 22] error connecting to the cluster

the csi plugin:
[root@node-8:/home/ubuntu/ceph-csi]$ kubectl get po
NAME                             READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-f9cs2           2/2     Running   0          23h
csi-cephfsplugin-provisioner-0   3/3     Running   0          25h

the pvc is 
[root@node-8:/home/ubuntu/ceph-csi]$ kubectl get pvc
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
csi-cephfs-pvc   Pending                                      csi-cephfs-sc   18h

i use the all yaml is :
https://github.com/ceph/ceph-csi/tree/master/examples/cephfs
https://github.com/ceph/ceph-csi/tree/master/deploy/cephfs/kubernetes
**What you expected to happen**:
I want the pv and volume can dynamic create 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Madhu-1** [comment]
@jianglingxia please make sure the monitor IP and port address are valid and reachable from provisioner pod, this will be a ceph-csi issue it's not related to kuberentes.

**Comment by jianglingxia** [comment]
really thanks for your reply,

and the monitor ip and port can reached ,i found that the secret yaml that the adminID and adminKey value can not base64, because exec the command :ceph [-m 178.178.178.189:1091,178.178.178.19:1091,178.178.178.188:1091 --id YWRtaW4= --key=***stripped*** -c /etc/ceph/ceph.conf fs get cephfs --format=json] the id and key then base64 again. i don't no why and i will issue the cephfs-csi

**Comment by Madhu-1** [comment]
@jianglingxia can you please create the same issue in ceph-csi repo we can discuss over there
