### ISSUE TITLE
Dir  automatically create would not be automatically removed when using csi raw block volume

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#79780]
**What happened**:

dir crated in /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices would not be automatically removed.

**What you expected to happen**:

when a pod delete the, the dir would be removed

**How to reproduce it (as minimally and precisely as possible)**:

create a pod using csi raw block volume and delete it

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/12230714/60653613-f4b2c280-9e7c-11e9-88ed-948f5e10692c.png)
 pod using pv-cb59bbc9-6195-49a0-b262-1adc9edeed1b actually has been deleted and the volume has been unmounted, but the dir still exists.

![image](https://user-images.githubusercontent.com/12230714/60658275-6a229100-9e85-11e9-97de-a79c26d58a87.png)

/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/{pv}/data still exists

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jsafrane** [comment]
I am afraid that the fix won't work for all volume plugins. I randomly checked where some volume plugins symlinks a device:

* iscsi: `/var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1`
* aws: `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/aws:/us-east-1d/vol-0e138b910f0fe4642`

So, iSCSI would be cleaned with this PR, but just as a coincidence, not as deliberate design. And AWS would still leave orphaned `aws:/`.

I am not convinced that this we don't have a plugin that **does not** use subdirectories.

I think a better approach is necessary. Perhaps `TearDownDevice` of every plugin should clean up everything that `SetUpDevice` created?

**Comment by cwdsuzhou** [comment]
> I am afraid that the fix won't work for all volume plugins. I randomly checked where some volume plugins symlinks a device:
> 
> * iscsi: `/var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface-default/127.0.0.1`
> * aws: `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/aws:/us-east-1d/vol-0e138b910f0fe4642`
> 
> So, iSCSI would be cleaned with this PR, but just as a coincidence, not as deliberate design. And AWS would still leave orphaned `aws:/`.
> 
> I am not convinced that this we don't have a plugin that **does not** use subdirectories.
> 
> I think a better approach is necessary. Perhaps `TearDownDevice` of every plugin should clean up everything that `SetUpDevice` created?

@jsafrane thanks for your advice, I would try to found a better approach

**Comment by msau42** [comment]
#79784 is being reverted because it broke CSI block volume cleanup

**Comment by msau42** [comment]
/remove-lifecycle rotten
@jsafrane is this still an issue?

**Comment by jsafrane** [comment]
I am adding CSI directories cleanup in #87978

**Comment by jsafrane** [comment]
This should be fixed by #87978
/close
