### ISSUE TITLE
LoadBalancer's healthcheck packet will be dropped in ipvs mode

### ISSUE THREAD

**Issue by imroc** [kubernetes/kubernetes#79783]
**What happened**:

Hi, I'm from the TKE team. In [TencentCloud TKE](https://intl.cloud.tencent.com/product/tke), LB health check packet source ip is LB's own ip (Service's ExternalIP)，and the LB will not do SNAT, when kube-proxy has ipvs enabled in 1.12，the the LoadBalancer's healthcheck packet to NodePort will be dropped by node, so the LB will think the node is unhealthy.  I tested 1.10 and found no such problem, and because the latest k8s version supported in TKE is 1.12, so I haven't tested k8s higher than 1.12. I didn't find any related issues, so I think the latest version should also have this problem.

I compared 1.10 and 1.12，1.12 will add the service's external ip to the `kube-ipvs0`:
``` bash
$ ip a show kube-ipvs0 | grep -A2 170.106.134.124
    inet 170.106.134.124/32 brd 170.106.134.124 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
```
- `170.106.134.124` is service's external ip (LB's ip)
- LB's ip was added to the dev `kube-ipvs0`

then kernel will add a local route in local table automatically:
``` bash
$ ip route show table local | grep 170.106.134.124
local 170.106.134.124 dev kube-ipvs0  proto kernel  scope host  src 170.106.134.124
```
and in 1.10, there is no LB's ip in dev `kube-ipvs0`, it is because of this difference that the packet cannot reach `cbr0` which source ip is LB's ip in 1.12,  I think it's related to an optimization: packets sent to service's external ip are routed directly to the pod via ipvs, which does not actually pass through the lb, check the ipvs rules in 1.12 we can found:
``` bash
ipvsadm -ln | grep -A1 170.106.134.124
TCP  170.106.134.124:80 rr
  -> 172.16.0.70:80               Masq    1      0          0
```

Check the [reference page](https://stupefied-goodall-e282f7.netlify.com/keps/sig-network/0011-ipvs-proxier/#supporting-loadbalancer-service) we can found kube-proxy will `Iterate LB’s ingress IPs, create an ipvs service whose address corresponding LB’s ingress IP`

You may ask how to prove the lb's healthcheck packet was dropped rather than redirected to the pod, I created a Service with type=LoadBalancer, and externalTrafficPolicy=Local, and the endpoint only have one pod, I captured the cbr0's packet on the node which has the service's pod, and there's no packet from lb has been captured, because the service's pod is only available at this node, if it is forwarded normally, it will must reach the `cbr0`.

If we delete the lb's local route in local table, then it will forward normally:
``` bash
ip route del table local local 170.106.134.124 dev kube-ipvs0  proto kernel  scope host  src 170.106.134.124
```
Or an infinite loop to execute this command to delete the ip in `kube-ipvs0`:
``` bash
$ ip addr del 170.106.134.124/32 dev kube-ipvs0
```

Is it possible that the incoming packet's source ip is found in the kernel's local table, it is considered to be the local ip, and then the kernel will drop the packet?

I guess why other cloud vendors didn't encounter this problem is because the source ip of lb's healthcheck packet is internal vip instead of lb's own ip

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-tke.4", GitCommit:"8433e31fd12cae66e59d634f4e7ab6cc13c93a4a", GitTreeState:"clean", BuildDate:"2019-06-25T05:19:07Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-tke.3", GitCommit:"ab6e1c10a35382c2ec70036e0e51c201eb3fc3f8", GitTreeState:"clean", BuildDate:"2019-06-18T12:12:29Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux VM-1-3-ubuntu 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by imroc** [comment]
cc @m1093782566

**Comment by imroc** [comment]
It’s a bit long, but I hope you can read it patiently.

**Comment by imroc** [comment]
After a deep dive into this problem，I found the root cause.

Let me to tell the long story. It's a bit too detailed, but it helps us understand the problem.

## A tiny IPVS design flaw
There are following two contradictory sentences in the [proposal](https://github.com/kubernetes/enhancements/blob/baca87088480254b26d0fdeb26303d7c51a20fbd/keps/sig-network/0011-ipvs-proxier.md#support-loadbalancer-service) of ipvs:

1. `IPVS proxier will NOT bind LB's ingress IP to the dummy interface`
2. `Iterate LB's ingress IPs, create an ipvs service whose address corresponding LB's ingress IP`

It means that LB ip will not be bounded to `kube-ipvs0`, but it will configure ipvs rules for LB ip, it's a bit contradictory, because if we do not bound the LB ip on the dummy interface(`kube-ipvs0`), kernel will not automatically create local route for the LB ip, so the packet sent to LB from container in cluster will be routed to the real LB instead of forward to pod directly by ipvs, then the ipvs rule for LB ip is useless (ipvs works on the input chain in netfilter, it requires all vips to be configured on the network interface in order for kernel to let packets go to input chain from prerouting chain which destnation ip is the vip, otherwise it will go to forward chain if ip is not in the local route).

I chatted with the author of ipvs proposal @m1093782566 who has confirmed that there is indeed such a problem in the design, and the implementation also has this problem at first, then https://github.com/kubernetes/kubernetes/pull/63066  this PR fixed that.

## How was this problem been discovered ?
It is because of this issue https://github.com/kubernetes/kubernetes/issues/59976 , some bare metal cluster uses MetalLB to create Service with LoadBalancer type, however, in some actual network environments, it is unreachable from pod to LB ip for some reason. The packet from pod to LB will not go through ipvs, cuz the LB ip is not configured to `kube-ipvs0`, so there is no local route for LB ip, resulting in the packets from pod to LB can not enter the input chain, enter the forward chain instead. https://github.com/kubernetes/kubernetes/pull/63066 this PR bind LB ip to `kube-ipvs0` solves the problem.

## The fix raises another problem
This fix did the right thing, but because of this change, it also raises another problem like this issue which is not usually found: Our LB will perform a health check on the nodeport, and the source ip of probe packet is LB its own ip, after https://github.com/kubernetes/kubernetes/pull/63066 this PR, the LB ip is configured on `kube-ipvs0`, and kernel create local route for LB ip automatically, when the probe packet from LB arrived on the nodeport, kernel found its source ip is a local ip, the packet will be ignored, cuz linux has a limitation: the source ip of any packet coming from a non-loopback interface cannot be the local ip. Therefore, the probe packet from LB will never reach the pod, and it will not be able to reply the packet to the LB, then LB will think that the nodeport is unhealthy.

## How to solve it ?

I tried to enable `accept_local`. The [accept_local](https://github.com/torvalds/linux/commit/8153a10c08f1312af563bb92532002e46d3f504a) parameter was introduced in linux kernel, allowing the source ip of the incoming packet to be the local ip: `sysctl -w net.ipv4.conf.all.accept_local=1`, but this only allows the incoming packet to be forwarded normally, and the reploy packet is still not reachable, cuz the destination ip of reply packet is LB ip, kernel found it is a local ip, then enters the input chain, and the ipvs kernel module checks the target ip:port, and found that there is no corresponding rs and does not process it (the destination port of reply packet is the source port of the probe packet, which is a random port, not in the ipvs load balancing list) , then the kernel will might tries to send the packet to the interface which configured the target ip, and it's `kube-ipvs0`, but this is a dummy interface with down state, so the packet will be ignored, and the reply packet for LB probe will never reach LB.

So we can't solve it by just modify the kernel param, the solution I am thinking of is to let kube-proxy support a parameter to control whether to bind LB ip to `kube-ipvs0`, does anyone has a better suggestion?

**Comment by imroc** [comment]
@lbernail I heard that you use ipvs a lot in the production environment, can you join this discussion? rolling back [this PR](https://github.com/kubernetes/kubernetes/pull/63066) can be a temporary solution, but we need a better long-term solution.

cc @Lion-Wei

**Comment by lbernail** [comment]
In several implementations load-balanced packets reach the nodes with the Load-balancer IP or External IP as target (it's the case with ILB on GCP and metalLB for instance). For IPVS to work in these cases, these IPs need to be considered local and that's why they are added to the dummy interface.

The problem you describe makes perfect sense. It would also impact AWS because packets are SNAT to the loadbalancer IP. However they don't set this `EXTERNAL-IP` in the status field but only the load-balancer name:
```  loadBalancer:
    ingress:
    - hostname: internal-xxxx.us-east-1.elb.amazonaws.com
```

I don't see an easy solution there. Would it be possible in the TKE controller to not set the ExternalIP and only set an hostname? That should solve your issue.
Otherwise the only solution I can see to address both use cases would be to add a flag to kube-proxy

@m1093782566 / @andrewsykim what do you think?

**Comment by imroc** [comment]
Let me summarize what candidate solutions I've come up with so far.

## Add A Flag to kube-proxy
Because the root cause of this problem is the LB's IP been bounded to `kube-ipvs0`, we can add a flag to `kube-proxy` to disable this behavior, but @m1093782566 worries that the kube-proxy will be overwhelmed by too many low-level flags, as far as I know, for instance, @lbernail added a low-level flag `--ipvs-strict-arp` to enable strict ARP in https://github.com/kubernetes/kubernetes/pull/75295, to avoid breaks some CNI plugins because of the change introduced in https://github.com/kubernetes/kubernetes/pull/70530

## Service Controller Write No ExternalIP
As @lbernail said, service-controller write no ExternalIP but only hostname in the status field of Service like AWS will solve the problem, but I think this approach can make people feel uncomfortable, we can't get the LB IP directly, and if we use dns to resolve LB's hostname to get IP, this depends on the implementation of the cloud vendor's LB, which requires add domain resolution for each LB IP automatically, which [TencentCloud](https://intl.cloud.tencent.com/) does not support for LAN LB. In addition, I think some app that manage kubernetes clusters may also rely on the IP in the service status field.

## Let LB Use Reserved IP as Source IP for Health Check
If use internal reserved IP rather than LB its own IP, it also can solve this problem, but this requires cross-team collaboration, and there may be some uncertainty, and the changes may have some other impact. More importantly, some cloud vendors or self-built LB will do snat, so if their LB IP is written in the status field of the service, the packet from normal client request will also never reach the pod. (btw, the reason why our LB can not do SNAT is that the interworking between LB and cloud VM in TencentCloud is achieved through a tunnel on the physical machine, so the reply packet will go through LB event if the destnation IP is not LB IP)


At present, I personally think that the best solution to the problem is the first one: Add a flag to kube-proxy to control whether bind LB IP to `kube-ipvs0`, cuz it's easy to implement and saves complicated and uncomfortable adaptation work for users.

**Comment by imroc** [comment]
We can add `--ipvs-exclude-external-ip` to kube-proxy which control whether to disable ipvs forwarding to the LoadBalancer's IP, I think it makes more sense, I'm going to submit a PR for this, what do you think? @m1093782566 @lbernail

**Comment by andrewsykim** [comment]
Wondering if we can fix this somehow with iptables, maybe masquerade only the health check node ports at PREROUTING? 

/remove-triage unresolved
(fix being discussed https://github.com/kubernetes/kubernetes/pull/79976)

**Comment by njuicsgz** [comment]
I wanted this PRI am looking forward this PR to avoid my problem. 
I used kube node ip as service's external ip with kube-proxy ipvs mode, so I got those node ips in kube-ipvs0. It makes problems as issue:
- 1. container1 can not access container2 with directly container ip, because the package from container1 -> flannel.1 -> eth0(container2's node) could not reach container2's node eth0 since container2's ip is just one service's external ip.
- 2. node1 could not access node2, if node2 is some service's external ip

when I used spring cloud/dubbo or other 3rd service discovery framwork, there is need to access container directly with it's ip. So 1 become a problem for me.

**Comment by andrewsykim** [comment]
FYI I'm going to raise this issue in the next SIG Network call

**Comment by Sh4d1** [comment]
@andrewsykim any news on this issue?

**Comment by andrewsykim** [comment]
@Sh4d1 sorry, this fell off my radar -- I'll try to follow-up on this soon. Thanks

**Comment by MatthiasLohr** [comment]
We ran into the same issue with MetalLB (Layer2 configuration). During debugging I found the issue with ipvs and so I came across this issue.

@imroc thank you very much for initiating this issue and providing a pull request - but unfortunately, discussion on that is discontinued. Is there any (other) idea around for solving that issue? How did you solve this for you so far?

**Comment by andrewsykim** [comment]
As far as I can tell, adding a flag to disable binding LB IPs is the only option without breaking compatibility for users. @lbernail @cmluciano thoughts?

**Comment by Sh4d1** [comment]
@andrewsykim what about https://github.com/kubernetes/enhancements/pull/1392 ? :thinking:

**Comment by andrewsykim** [comment]
If we're making changes at the API level that would work too :)

**Comment by uablrek** [comment]
Please see; https://github.com/kubernetes/kubernetes/issues/72236#issuecomment-614122808

**Comment by lbernail** [comment]
@andrewsykim I believe a flag for kube-proxy or an additional status field set by the cloud provider implementation are the simplest approaches (because I don't see scenarios where the behavior would change between services of type LoadBalancer in the same cluster)

@uablrek I'm not sure removing kube-ipvs0 would solve this here because we would have to add LoadBalancer IPs to the local route table anyway (otherwise we'll change the current documented datapath for pod to load-balancer IP)

**Comment by Sh4d1** [comment]
@lbernail the solution also solves some LoadBalancer bypass mechanism issues with LB that for instance encapsulate in proxy protocol (it's better described in the KEP 😅) and in this case I could see some scenarios when the user would want to enable/disable it by service

**Comment by andrewsykim** [comment]
> @andrewsykim I believe a flag for kube-proxy or an additional status field set by the cloud provider implementation are the simplest approaches (because I don't see scenarios where the behavior would change between services of type LoadBalancer in the same cluster)

In https://github.com/kubernetes/enhancements/pull/1392 I suggested adding a status field to enable/disable binding the LB IP. Let's move the discussion there.

**Comment by uablrek** [comment]
> because we would have to add LoadBalancer IPs to the local route table anyway

@lbernail True, but the point is that you can set the "src" address to something else than the clusterIp itself, e.g the node address.

**Comment by uablrek** [comment]
@andrewsykim 

> In kubernetes/enhancements#1392 I suggested adding a status field to enable/disable binding the LB IP. Let's move the discussion there.

Would removing bind-addresses not solve the problem *only* for those using an external LB that load balances to node-ports (most public clud providers), but would not the problem in this issue remain for others (all private-cloud users and some public clud providers)?

**Comment by andrewsykim** [comment]
> Would removing bind-addresses solve the problem only for those using an external LB that load balances to node-ports (most public clud providers), but would not the problem in this issue remain for others (all private-cloud users and some public clud providers)?

I think it depends what IPs you are advertising (clusterIP, externalIPs, loadbalancerIPs?). It will also depend on what the src address of the traffic is. For the public cloud LB case, this is only a problem when the source address is the LB's IP.

**Comment by marksmansj** [comment]
你好，看了您的“Kubernetes疑难杂症”的文章，想请教一个，tke kube-proxy用ipvs模式，svc用clb vip load balancer模式，clb 的vip不会绑定到ipvs0网卡上，那就数据包就不会进入input链，而进入forward链，但我看forward链只有ip_vs_icmp和ip_vs_reply两个hook，没有ip_vs_in的hook，那它是怎么实现dnat的呢？

**Comment by imroc** [comment]
> 你好，看了您的“Kubernetes疑难杂症”的文章，想请教一个，tke kube-proxy用ipvs模式，svc用clb vip load balancer模式，clb 的vip不会绑定到ipvs0网卡上，那就数据包就不会进入input链，而进入forward链，但我看forward链只有ip_vs_icmp和ip_vs_reply两个hook，没有ip_vs_in的hook，那它是怎么实现dnat的呢？

就没有 DNAT，直接访问到 CLB VIP 了 @marksmansj

**Comment by imroc** [comment]
参考 https://imroc.cc/tke/troubleshooting/faq/clb-loopback

**Comment by marksmansj** [comment]
> > 你好，看了您的“Kubernetes疑难杂症”的文章，想请教一个，tke kube-proxy用ipvs模式，svc用clb vip load balancer模式，clb 的vip不会绑定到ipvs0网卡上，那就数据包就不会进入input链，而进入forward链，但我看forward链只有ip_vs_icmp和ip_vs_reply两个hook，没有ip_vs_in的hook，那它是怎么实现dnat的呢？
> 
> 就没有 DNAT，直接访问到 CLB VIP 了 @marksmansj

Hello, as mentioned earlier, it is a scenario where PODs within a cluster access CLB VIP. May I ask if this is the data forwarding process I described below if it is an external client accessing CLB VIP (load balancer)?

1. External clients of the cluster access CLB VIP, and CLB forwards the request to the nodeport of the node IP. The request changes from the original client IP ->CLB VIP to client IP ->node IP (nodeport)

2. After receiving the packet, the node server discovers that the destination address is its own node IP, and  the packet enters the input chain to trigger IPVS to perform a DNAT request on the IP_vs_in hook buried in the input chain to the backend RS. After the packet passes through the input chain and then enters the post routing chain, it will also perform a SNAT to access RSs using the node IP (random port)

**Comment by trungng92** [comment]
An update to this:

https://kubernetes.io/blog/2023/12/18/kubernetes-1-29-feature-loadbalancer-ip-mode-alpha/

The feature "LoadBalancerIPMode" was introduced to fix this. It was added in 1.29, is in beta in 1.30, and is GA in 1.32+.
