### ISSUE TITLE
Block volume used as filesystem in a pod does not give clear error message

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#79794]
When a raw block PV is used as a filesystem one in a pod (i.e. in pod.spec.containers[x].volumeMounts), kubelet correctly won't start the pod, but it does not give user any information why.

In pod events I can't see anything useful:

```
Events:
  Type     Reason                  Age                    From                                                 Message
  ----     ------                  ----                   ----                                                 -------
  Normal   Scheduled               9m13s                  default-scheduler                                    Successfully assigned volumemode-206/security-context-d213f352-cd45-48ca-bb28-268a24ec75f8 to ip-10-0-160-149.us-east-2.compute.internal
  Warning  FailedAttachVolume      9m11s (x3 over 9m12s)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-6efadcf1-9e57-11e9-bf6d-0a9ea8760cec" : "Error attaching EBS volume \"vol-007031b5e356a6786\"" to instance "i-0daef3d471605cebf" since volume is in "creating" state
  Normal   SuccessfulAttachVolume  9m5s                   attachdetach-controller                              AttachVolume.Attach succeeded for volume "pvc-6efadcf1-9e57-11e9-bf6d-0a9ea8760cec"
  Warning  FailedMount             24s (x4 over 7m10s)    kubelet, ip-10-0-160-149.us-east-2.compute.internal  Unable to mount volumes for pod "security-context-d213f352-cd45-48ca-bb28-268a24ec75f8_volumemode-206(70902de5-9e57-11e9-bf6d-0a9ea8760cec)": timeout expired waiting for volumes to attach or mount for pod "volumemode-206"/"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8". list of unmounted volumes=[volume1]. list of unattached volumes=[volume1 default-token-h4xcm]
```

The pod is `ContainerCreating` forever. It should get `Failed` with a clear message.

In kubelet logs I can see:
```
desired_state_of_world_populator.go:296] Error processing volume "volume1" for pod "security-context-d213f352-cd45-48ca-bb28-268a24ec75f8_volumemode-206(70902de5-9e57-11e9-bf6d-0a9ea8760cec)": Volume "volume1" has volumeMode "Block", but is specified in volumeMounts for pod "volumemode-206"/"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8"
```

/sig storage
/kind bug
/priority important-soon

**Comment by jsafrane** [comment]
`Volume "volume1" has volumeMode "Block", but is specified in volumeMounts` comes from depths of Desired State of World Populator (DSWP):

https://github.com/kubernetes/kubernetes/blob/7cb5df672813326952171be6c9ab52d821b85c1a/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L529-L536

This code does not have access to event recorder and even if it had, it would be called too often and we would need some rate limiting of the events.

IMO, the best thing we could do is to mark the pod as Failed with a clear message that it's user fault and the pod can't be ever run. Is it a good idea to mark a pod as Failed from VolumeManager / DSWP?

Would it be better to mark the pod as such during admission into kubelet? Currently, kubelet does not even check if all PVCs used in the pod exist during pod admission. Should kubelet have a (soft) admission for checking of PVCs? Adding proper block / filesystem check there would be then trivial.

@gnufied @msau42 @jingxu97 @kubernetes/sig-node-bugs

**Comment by mattjmcnaughton** [comment]
/sig storage
/remove-sig node
I think this is most appropriately triaged via sig-storage, but please feel free to assign back to sig-node if y'all disagree.

**Comment by jsafrane** [comment]
@mattjmcnaughton, we (sig-storage) need some help here. This is outside of the area of kubelet we're familiar with. Of course we can handle the code if we know what is the best place to check if a PVC is used correctly in a pod.

**Comment by mattjmcnaughton** [comment]
Whoops, I didn't see that you were a part of `sig-storage` @jsafrane . My apologies :)

Readding sig-node :)

/sig node

**Comment by jsafrane** [comment]
I talked to @sjenning and there seem to be no easy way how to mark the pod as non-runnable. `Failed` is for pods that were running and exited, `ImagePullBackOff` (and similar) are for transient errors.

We agreed that an event would be the most appropriate.

**Comment by jsafrane** [comment]
Fix: https://github.com/kubernetes/kubernetes/pull/80369

Comments from sig-node staff is very welcome there!
