### ISSUE TITLE
Arbitrary image registry auth in CRI

### ISSUE THREAD

**Issue by sashayakovtseva** [kubernetes/kubernetes#79803]
Currently in order to pull from private registry one can use secrets (as described [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)). However it is tightly integrated with Docker and there is no other way to support different registries. This is especially weird as there is CRI that can has `PullImage` method. 

Is there any way to make kubelet pass `imagePullSecret` to CRI implementation without interpreting it as a Docker credentials? Of course that can be circumvented by configuring CRI itself, but I like approach with dynamic configuration with Secrets more.

**Comment by mattjmcnaughton** [comment]
Thanks for your question :)

From what I'm reading in https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry, it looks like there are a variety of different strategies possible for configuring access to an arbitrary image registry... however, I agree that the `ImagePullSecret` appears to map closely to Docker.

It may be worth discussing this in #sig-node on Slack, or even attending the weekly sig node meeting, and seeing if there is community interest in making `ImagePullSecret` more image repo agnostic. If there is, the next step would be filing a [KEP](https://github.com/kubernetes/enhancements). Happy to chat more about that process if we get to that point :)

**Comment by sashayakovtseva** [comment]
Hello @mattjmcnaughton and thank you for response!
I have already raised this question in slack `#sig-node` channel, but there was no response, so I raised this issue here 🙂

How can we put this topic to any upcoming sig node meeting? How can I take part there?  Or should I bring that topic once again in slack? 
As already said, `imagePullSecret` seems to be unaligned with CRI concept of arbitrary runtime and image service, so changing current implementation may be useful for any other runtimes that would like to integrate with k8s. I think this might be worth discussing with sig group, so please help with the process of attending the meeting with this topic or guide me anywhere else where this can be heard. 
Thank you!

**Comment by mattjmcnaughton** [comment]
cc'ing @derekwaynecarr @dchen1107, who are the leaders of sig-node.

https://github.com/kubernetes/community/tree/master/sig-node provides some context around the meeting times, agenda, etc...

**Comment by sashayakovtseva** [comment]
Hello @mattjmcnaughton, are there any updates so far?

**Comment by mattjmcnaughton** [comment]
Re cc'ing @dchen1107 and @derekwaynecarr - you could also try asking in #sig-node on the k8s slack :)

**Comment by derekwaynecarr** [comment]
@sashayakovtseva can you elaborate your specific concern a little better?  is there a particular registry you want to support? is there a CRI change you would like to see to enable that registry?  are you trying to support another transport or something?

**Comment by sashayakovtseva** [comment]
@derekwaynecarr Sure, I want to support [Sylabs cloud](cloud.sylabs.io/library) and enable private image pulls from there with `imagePullSecret`. Now there is docker specific flow in kubelet, so there is no way I can pass credentials for a registry except docker (or with same API). [Sylabs cloud](cloud.sylabs.io/library) for instance makes use of access tokens, but there in no way to pass it with secrets. 

What I think can be done here is moving secret/auth checks that are in kubelet now into CRI implementation and letting the implementation decide how to handle that credentials. Or introducing a new secret type like `kubernetes.io/pullconfig` that will not be interpreted by kubelet. 

K8s introduced CRI which has `ImageService`, so why forcing implementations to use docker when it comes to private images and `imagePullSecret`? I believe those checks should be removed from kubelet code to fully enable flexibility of k8s.

**Comment by sashayakovtseva** [comment]
@derekwaynecarr @mattjmcnaughton How can this issue appear in sig-node agenda?

**Comment by dchen1107** [comment]
@sashayakovtseva We are going to discuss this topic at today's SIG Node meeting.

**Comment by Random-Liu** [comment]
The use case makes sense to me.

> What I think can be done here is moving secret/auth checks that are in kubelet now into CRI implementation and letting the implementation decide how to handle that credentials. Or introducing a new secret type like kubernetes.io/pullconfig that will not be interpreted by kubelet.

I feel like moving secret/auth checks into the CRI implementation seems to be a too big change to me, because:
1) Docker type registries are still the most commonly used registry by Kubernetes users;
2) Copying the commonly used Docker keyring logic from Kubernetes to each container runtime e.g. containerd and cri-o makes it harder to maintain.

This is still doable, but a new secret type seems cleaner to me. The docker secret type is already "docker" something, which shouldn't be used in this new use case, a new secret type is required any way.

**Comment by sashayakovtseva** [comment]
This topic was not discussed on SIG-NODE, will it be discussed here? Should we prepare KEP? What are the next steps?

**Comment by dchen1107** [comment]
Too many proposals today at today's SIG Node, and sorry for missing this one. Yes, please carry on the discussion here. @Random-Liu

**Comment by Random-Liu** [comment]
@sashayakovtseva I think both the use case and high level idea make sense to me.

I think you may want to file a KEP to describe your use case and propose the new secret type + kubelet pass-through behavior.

The secret type name may need some discussion, other changes look relatively straightforward to me. :)

**Comment by sashayakovtseva** [comment]
KEP can be found in kubernetes/enhancements#1171

**Comment by dims** [comment]
@sashayakovtseva have you seen this? https://github.com/kubernetes/enhancements/pull/1137
