### ISSUE TITLE
Kubelet cpu manager should refresh cpuset if cpu topology changed

### ISSUE THREAD

**Issue by peter-wangxu** [kubernetes/kubernetes#79823]
**What happened**:
A node was previously installed with kubelet and use the static manager
as the node only contained 1 core, the /var/lib/kubelet/cpu_manager_state was initialized with
```json
{"policyName":"static","defaultCpuSet":"0","checksum":885245905}
```
later, the node was upgrade to 4 cores, and the file was not refreshed and the newly added cpus cannot be used by any workload anymore

**What you expected to happen**:
the kubelet should be aware of this cpu topology change ,and added the new cores to the manager state file.

**How to reproduce it (as minimally and precisely as possible)**:
install kubelet with cpu manage enabled. then upgrade the VM with more cores
the cpu manager state is not refreshed

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mattjmcnaughton** [comment]
In the short term, I believe you can fix this by deleting the `/var/lib/kubelet/cpu_manager_state` file and then restarting `kubelet`.

@ConnorDoyle , I'm seeing your name a lot on the cpu manager code. Can you comment on whether its intentional that `cpu_manager` doesn't pick up the new CPUs without manual intervention? Or is this a bug that we want to address?

**Comment by nagexiucai** [comment]
I had reviewed the logic, it seems that:

kubelet start -> cadvisor.MachineInfo -> plugapi.Device

But i can not find the point for updating `cpu manager state` by `machineinfo` periodically :(

**Comment by peter-wangxu** [comment]
> Thanks for raising this @peter-wangxu :)
> 
> In the short term, I believe you can fix this by deleting the `/var/lib/kubelet/cpu_manager_state` file and then restarting `kubelet`.
> 
> @ConnorDoyle , I'm seeing your name a lot on the cpu manager code. Can you comment on whether its intentional that `cpu_manager` doesn't pick up the new CPUs without manual intervention? Or is this a bug that we want to address?

@mattjmcnaughton yes, removal and restart fix it. shouldn't we provide a better way to heal this, it cause all workload running on the legacy cores without any attention.

Thanks
Peter

**Comment by mattjmcnaughton** [comment]
@peter-wangxu yup, I agree with you 100% that we most likely shouldn't need user intervention to fix this. Just want to get input from @ConnorDoyle on if there's anything we're missing, before starting work on addressing this.

**Comment by peter-wangxu** [comment]
Sure, if confirmed, I can also start work with this

**Comment by peter-wangxu** [comment]
@mattjmcnaughton @ConnorDoyle any update on this?

A similar problem occurred in our virtualized environment when shrink the VM spec by CPU.

if user shrinks the VM from 32 to 16 cores, the pods ocurrpy removed cores(17-31) will definitely failed to start as cpuset out of range.
