### ISSUE TITLE
VolumeManager frequently saves vol info if csi block mount failed.

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#79824]
**What happened**:

![image](https://user-images.githubusercontent.com/12230714/60708160-fee9c500-9f3f-11e9-917e-c2b47773e901.png)

volumeManager frequently saves vol info if csi block mount failed.

**What you expected to happen**:

Should not frequently save vol info. If it already exists, return.

**How to reproduce it (as minimally and precisely as possible)**:

This issue occurs when csi raw block mount failed because of resync.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): k8s 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node
/sig storage

**Comment by mattjmcnaughton** [comment]
/remove-sig node

Going to let sig-storage triage this. Happy for sig-node to be involved if we could be helpful :)
