### ISSUE TITLE
'kubctl create' to have 'pod' option

### ISSUE THREAD

**Issue by bergmeister** [kubernetes/kubernetes#79830]
**What would you like to be added**:

`kubectl create pod`

**Why is this needed**:

For exam purposes (CKAD) it is useful to be able to generate various templates and `kubectl create` offers various options that are useful together with the `--dry-run -o yaml` option. However, there is no template for creating a `pod`.

Currently the only way to generate a simple `pod` template is by using `kubectl run nginx --image=nginx --restart=Never`

**Comment by prksu** [comment]
Hi @bergmeister in the future `kubectl run` will only generate the simple `pod` see https://github.com/kubernetes/kubernetes/pull/68132 

i consider adding the `kubectl create pod` is not necessary here

**Comment by bergmeister** [comment]
I consider it to be useful for the Kubernetes exams that are tight in time where one cannot write much YAML from scratch and needs to use generators

**Comment by remyleone** [comment]
:+1: it is also useful for coherence. If a user uses "kubectl create" to create a given resource, it helps if  all base resources are available inside it.

**Comment by apelisse** [comment]
pod templates are generally much less useful than other types of resources. It's generally accepted that people wouldn't maintain pod yaml configurations but higher level abstractions to create these pods (deployment, statefulset, jobs).

Also, I think we're moving away from the general `kubectl create` pattern in general, so I don't think the sig would accept such a change, but I might be wrong so let's ping @kubernetes/sig-cli-maintainers to clarify.

**Comment by sftim** [comment]
> we're moving away from the general `kubectl create` pattern in general

If so, I'm keen to document an alternative.

**Comment by monotek** [comment]
What about:

```
kubectl run -it --rm --generator=run-pod/v1 pod --image=debian bash
```

**Comment by soltysh** [comment]
There's no plan to support `kubectl create pod`, `kubectl run pod` is what you can use. See also https://github.com/kubernetes/kubectl/issues/914 for reasons and the future of create commands.
/close
