### ISSUE TITLE
When cpuCFSQuotaPeriod is changed in kubelet, CPU limits are not enforced correctly

### ISSUE THREAD

**Issue by gjcarneiro** [kubernetes/kubernetes#79833]
**What happened**:

Containers are not being correctly CPU limited, after changing cpuCFSQuotaPeriod from the default 100ms to 10ms.

Even though I have cpu limit 500m in the container, I can run a program with an infinite loop, and see it consuming 100% of CPU.  In fact, the total CPU usage exceeds 100%, due to additional processes running.

**What you expected to happen**:

It should be limited to 50% of a CPU, as I set cpu limit to `500m`.  Changing cpuCFSQuotaPeriod should not modify the units of CPU limit, should be totally transparent.

**How to reproduce it (as minimally and precisely as possible)**:

```
# cat /etc/kubernetes/kubelet/config.yaml |grep CFS
cpuCFSQuota: true
cpuCFSQuotaPeriod: 10ms
```

Then create a pod with a container with CPU limits, in this example I have:

```
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
```

Inspecting the container, it seems the configuration sent to docker is wrong:

```
root@mer-32c2-pm:~# docker inspect a1281c6883c8|grep Cpu
            "CpuShares": 102,
            "NanoCpus": 0,
            "CpuPeriod": 10000,
            "CpuQuota": 50000,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,
```

If CpuQuota is 50k, and CpuPeriod is 10k, it sounds like the container is being limit to 5 CPU cores, instead of 0.5.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-46-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: docker 18.06.3-ce

**Comment by mattjmcnaughton** [comment]
I'm new to the world of CPU quotas... so apologies if what I'm saying doesn't make sense...

In reading https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt, I'm seeing the following:
> The bandwidth allowed for a group is specified using a quota and period. Within
each given "period" (microseconds), a group is allowed to consume only up to
"quota" microseconds of CPU time.  When the CPU bandwidth consumption of a
group exceeds this limit (for that period), the tasks belonging to its
hierarchy will be throttled and are not allowed to run again until the next
period.

Following this logic, doesn't it make sense that if we decrease the quota period, without changing the CPU limit, then the actual allowed CPU consumption will increase. Because the limit is enforced per quota period, and now the quota period is shorter?

**Comment by gjcarneiro** [comment]
That is the problem.  At kernel level you play with both `cfs_period_us` and `cfs_quota`, you control both to ensure the desired results.

In Kubernetes land, the sysadmin configures `cfs_period_us` system-wide (via the cpuCFSQuotaPeriod kubelet setting), and application developers control the "cpu limit".  If we set cpu limit = 0.5, that should be "half a CPU", always, regardless of how the sysadmin configured as cpuCFSQuotaPeriod.

Apparently, when computing cfs_quota for a container, kubelet does the calculations assuming the default value for cpuCFSQuotaPeriod (100ms), even when the value has been modified to something else.

**Comment by tedyu** [comment]
I assume kubefeatures.CPUCFSQuotaPeriod is enabled in @gjcarneiro 's case.

**Comment by liucimin** [comment]
/assgin
@gjcarneiro 
Would do you like to show us all the data in /etc/kubernetes/kubelet/config.yaml ?
I will trying to fix this by https://github.com/kubernetes/kubernetes/pull/79850

**Comment by gjcarneiro** [comment]
[config.yaml.txt](https://github.com/kubernetes/kubernetes/files/3364712/config.yaml.txt)

**Comment by gjcarneiro** [comment]
If helps, kubelet args:

```
KUBELET_ARGS=--v=2 "--alsologtostderr=true" "--cloud-config=" "--cloud-provider=" "--container-runtime=docker" "--enable-server=true" "--hostname-override=mer-32c2-pm.k3.gambit" "--kubeconfig=/etc/kubernetes/kubelet/kubeconfig" "--config=/etc/kubernetes/kubelet/config.yaml" "--node-ip=10.134.4.1" "--node-labels=datacenter=mer" "--non-masquerade-cidr=10.0.0.0/8" "--register-node=true" "--root-dir=/var/lib/kubelet"
```

**Comment by mattjmcnaughton** [comment]
On Fri, Jul 05, 2019 at 09:07:49AM -0700, Gustavo J. A. M. Carneiro wrote:
> That is the problem.  At kernel level you play with both `cfs_period_us` and `cfs_quota`, you control both to ensure the desired results.
> 
> In Kubernetes land, the sysadmin configures `cfs_period_us` system-wide (via the cpuCFSQuotaPeriod kubelet setting), and application developers control the "cpu limit".  If we set cpu limit = 0.5, that should be "half a CPU", always, regardless of how the sysadmin configured as cpuCFSQuotaPeriod.
> 
> Apparently, when computing cfs_quota for a container, kubelet does the calculations assuming the default value for cpuCFSQuotaPeriod (100ms), even when the value has been modified to something else.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/79833#issuecomment-508804706

Ah I gotcha - thank you for that explanation :)

**Comment by liucimin** [comment]
@gjcarneiro 
Report some thing about this issue.
I use my cluster(v1.14) to check this problem with your args.But the docker info is correct in my cluster.

```
docker inspect 40c1f05971f4 |grep -i cpu
            "CpuShares": 102,
            "NanoCpus": 0,
            "CpuPeriod": 10000,
            "CpuQuota": 5000,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,
```

```
cat /tmp/k8sconfig.yaml

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cpuCFSQuota: true
cpuCFSQuotaPeriod: 10ms

```

And then i check the code in 1.14，the clac is correct in the code.
```

	if m.cpuCFSQuota {
		// if cpuLimit.Amount is nil, then the appropriate default value is returned
		// to allow full usage of cpu resource.
		cpuPeriod := int64(quotaPeriod)
		if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.CPUCFSQuotaPeriod) {
			cpuPeriod = int64(m.cpuCFSQuotaPeriod.Duration / time.Microsecond)
		}
		cpuQuota := milliCPUToQuota(cpuLimit.MilliValue(), cpuPeriod)
		lc.Resources.CpuQuota = cpuQuota
		lc.Resources.CpuPeriod = cpuPeriod
	}
```

Then i check the code in 1.13.3, the code  also seem right ....
I will try to use 1.13.3 to check the runtime info.

**Comment by liucimin** [comment]
@gjcarneiro 

I check the code in 1.13. 

https://github.com/kubernetes/kubernetes/blob/e1be42a61576dcb85ea6b56de18fd627e4c55bfc/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L67-L75

There is seems the same with v1.14.
If u still meet the problem.Would u like to check your k8s version?Or try to upgrade your k8s then try again.

**Comment by gjcarneiro** [comment]
OK, I am glad to hear this is not a widespread bug.  But it still affects my case. I double checked, on another pod/container, which has cpu limit `500m`, but inspecting the running container I can see:

```
root@hex-32c1-pm:~# docker inspect bc2be1003d504902b62371f15a1774eedb9584e263e2d359f94d24ec903de416 |grep Cpu
            "CpuShares": 204,
            "NanoCpus": 0,
            "CpuPeriod": 10000,
            "CpuQuota": 50000,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,
``` 

Out of curiosity, what docker version do you have, @liucimin ?  I have `18.06.3-ce`.

**Comment by wuestkamp** [comment]
I have the same issue with 1.15.15: I set the `--cpu-cfs-quota-period=5ms --cpu-cfs-quota=true` but it doesn't have an effect on the actual docker containers?

```
:~/tmp# docker inspect ba84a633d40b | grep Cpu
            "CpuShares": 307,
            "NanoCpus": 0,
            "CpuPeriod": 100000,
            "CpuQuota": 30000,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,
```

**Comment by karan** [comment]
I've confirmed that the fix is to enable the `CustomCPUCFSQuotaPeriod` feature flag.

**Comment by gjcarneiro** [comment]
> I've confirmed that the fix is to enable the `CustomCPUCFSQuotaPeriod` feature flag.

OK, but then if the `CustomCPUCFSQuotaPeriod` is required to be enable (was not aware of it), then shouldn't the kubelet configuration `cpuCFSQuota: true` and `cpuCFSQuotaPeriod: 10ms` just be ignored (possibly with warning) if the feature flag is not enabled?

**Comment by karan** [comment]
In my tests, the kubelet did ignore `cpuCFSQuotaPeriod: 10ms` (didn't test `cpuCFSQuota: true`) albeit silently. We should at least warn in that case.
