### ISSUE TITLE
externalTrafficPolicy=Local no effects for the request made from the node LOCAL addresses.

### ISSUE THREAD

**Issue by adolli** [kubernetes/kubernetes#79865]
**What happened**:

**kube-proxy mode: iptables**. I have a Service object with `externalTrafficPolicy=Local`. When I make a request from the node such as the following command. The `externalTrafficPolicy=Local` seems to take no effects and the request was sent to the pod running in another node.

```bash
curl localhost:{nodePort}
curl 10.0.0.1:{nodePort}
# where 10.0.0.1 is my node IP.
```

I dived into the iptables rules and found 2 more rules added for the Service since version 1.15.0.  Commit locates here https://github.com/kubernetes/kubernetes/commit/b926fb9d2b161642f9cd524aaa06d7dda5d5aab6?w=1 . And I have also compared with the kube-proxy mode ipvs which does not have this issue.

**What you expected to happen**:

Sending the request to the node locally if `externalTrafficPolicy=Local` wherever the request was made from. 

Maybe I am not learning well the design. If so, would u please explain more about this feature?

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the service object mentioned before (also the pod if necessary).
1. Make a request through the service object's nodePort.
1. Monitor the log in the pod.

**Anything else we need to know?**:

My scenario is running several file servers as DaemonSet on different nodes replicatedly. Accessing it via an Ingress object as I need to access via an https way. The traffics are always heavy since many large files transfers. So I hope the traffic route only inside the node locally not proxy to another node randomly.

The traffic looks like  
```
             | inside one node                             |
External --> | Ingress --> Service --> Pod (of DaemonSet)  |
```

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:  common openstack-nova vm
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04.4
- Kernel (e.g. `uname -a`): 4.4
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by adolli** [comment]
@kubernetes/sig-network-bugs

**Comment by andrewsykim** [comment]
`externalTrafficPolicy=Local` should only apply for external traffic and shouldn't apply for any local addresses on the node? Service Topology _should_ fix this though https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0033-service-topology.md but that's a WIP. 

cc @m1093782566 @imroc
