### ISSUE TITLE
kubelet command line flags doesn't override that value in Kubelet’s config file

### ISSUE THREAD

**Issue by peter0086** [kubernetes/kubernetes#79876]
When I try to change the 'node status update frequency' via command line flags, I find an issue that when the value is larger than the one in config file, it will work. Otherwise, it won't.

This is an example:
I set the value below in config file.
**nodeStatusUpdateFrequency: 10s**
Then I add the flag in command line as
**kubelet --node-status-update-frequency=2s** 

**What happened**:
The node-status-update-frequency changes to '2s'
**What you expected to happen**:
The node-status-update-frequency stays at '10s'
**How to reproduce it (as minimally and precisely as possible)**:
Just as the example above, note that the command flag values need to be no lager than the one in config file.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.3
- Cloud provider or hardware configuration: OpenStack
- OS (e.g: `cat /etc/os-release`): Redhat 7
- Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

@kubernetes/sig-node-bugs
/sig node

**Comment by tedyu** [comment]
```
Specifies how often kubelet posts node status to master. Note: be cautious when changing the constant, it must work with nodeMonitorGracePeriod in nodecontroller
```
Do you know the value for nodeMonitorGracePeriod in your deployment ?

**Comment by peter0086** [comment]
> ```
> Specifies how often kubelet posts node status to master. Note: be cautious when changing the constant, it must work with nodeMonitorGracePeriod in nodecontroller
> ```
> 
> Do you know the value for nodeMonitorGracePeriod in your deployment ?

It 40s. Is the nodeMonitorGracePeriod must be smaller to node-status-update-frequency? 
My default node-status-update-frequency setting is 10s, which works well.
