### ISSUE TITLE
kubemark is using simplified auth setup

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#79883]
https://github.com/kubernetes/kubernetes/pull/78246 migrates the kubemark setup logic to kube-up-based, but also simplifies auth setup -- all components are using the same kubeconfig. This is a potential source of difference with gce setup where each component is using separate kubeconfig.

We should migrate all components to separate kubeconfigs.

**Comment by RainbowMango** [comment]
If still need help, please add tag back.

/remove-help
