### ISSUE TITLE
CSI block volume expects that devices are symlinks

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#79896]
I am testing CSI block volume reconstruction and it expects that devices "created" using `NodePublishVolume` are symlinks:

https://github.com/kubernetes/kubernetes/blob/be7da5052f40d8bcb7b6195ddae93f33b1faea28/pkg/volume/util/operationexecutor/operation_executor.go#L931-L939

Nothing in CSI spec requires the device to be a symlink.

>   // For volumes with an access type of block, the SP SHALL place the
  // block device at target_path.
  string target_path = 4;

"Place" is not specified anywhere and thus it can mean anything, for example `mknod()` or bind-mount. Ceph RBD uses bind-mounts.

I did not check the other CSI plugin code. It should not assume that a device is a symlink anywhere. Kubernetes should just check that a file of any type is present and use it.

@vladimirvivien @msau42 

Very similar issue is with mounts, volume reconstruction expects that every volume is a mount, which is again never required in CSI. For ephemeral volumes just a directory with few files should be enough.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
Unfortunately, we use symlinks to check if all pods that use a device are deleted so we can remove the global "symlink":

https://github.com/kubernetes/kubernetes/blob/be7da5052f40d8bcb7b6195ddae93f33b1faea28/pkg/volume/util/operationexecutor/operation_generator.go#L1305-L1312

Complex solution or even rework of whole block device reference counting is needed here.

**Comment by jsafrane** [comment]
I filled #79980 that's related to filesystem volumes, let's focus on block here.

**Comment by jsafrane** [comment]
> CSI block is strange and calls both stage and publish during setupdevice

Indeed. It's IMO against CSI spec, but I doubt anyone would complain.

With this commit, symlink counting looks working, at least the pod directory disappears after kubelet restart: https://github.com/kubernetes/kubernetes/pull/75071/commits/237a7eb412821860d701a67494903c7c24806d17.

/close
