### ISSUE TITLE
Add Normalize Scoring extension point of the scheduling framework

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#79901]
**What would you like to be added**:
The scheduling framework KEP is now implementable. We have already added plugin interfaces and a few extension points, such as "reserve" and "prebind" plugins.

[Normalize Scoring](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#normalize-scoring) plugins are used to modify scores before the scheduler computes a final ranking of Nodes. A plugin that registers for this extension point will be called with the scoring results from the same plugin.

This is needed for 1.16.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by congliu01** [comment]
Hi, I'd like to work on this one.

**Comment by ahg-g** [comment]
Thanks @congliu01 I can't reassign to you since you are not a member yet, but we will consider it yours. Note that you will have to wait until https://github.com/kubernetes/kubernetes/pull/79109 is merged since they depend on each other.

**Comment by congliu01** [comment]
Sounds good! Thanks!
