### ISSUE TITLE
[e2e] cleanup test/e2e/framework/kubelet_stats.go

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#79907]
Due to work refactoring `test/e2e/framework/metrics` in https://github.com/kubernetes/kubernetes/pull/79753 some objects and methods had to be duplicated from `test/e2e/framework/kubelet_stats.go` into `test/e2e/framework/metrics`.

We need to cleanup the duplicated code in `test/e2e/framework/kubelet_stats.go` and replace any calls made to duplicated methods/objects within the e2e framework with the proper methods/objects in `test/e2e/framework/metrics`.

/area e2e-test-framework
/sig testing
/kind cleanup
/assign

**Comment by alejandrox1** [comment]
/reopen
will pick this up

**Comment by tanjunchen** [comment]
@alejandrox1  test/e2e/framework/kubelet_stats.go is gone!
