### ISSUE TITLE
sig-cluster-lifecycle uses OWNERS aliases that 404

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#79904]
/assign @timothysc 
@kubernetes/sig-cluster-lifecycle 

https://github.com/kubernetes/kubernetes/pull/79874#issuecomment-509407586

Cannot find either of these aliases
```yaml
sig-cluster-lifecycle:
sig-cluster-lifecycle-maintainers:
```

ref https://github.com/kubernetes/test-infra/issues/13362

**Comment by neolit123** [comment]
thanks @fejta 

/sig cluster-lifecycle
@justinsb @timothysc 
let me know if want me to PR a fix, yet i don't know what action to take.
do you wish to keep these aliases?
