### ISSUE TITLE
Cleanup utility function in e2e service package

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#79913]
/sig testing
/priority important-longterm
cc/ @timothysc 

https://github.com/kubernetes/kubernetes/pull/77155 moved service_utils into a separated package. But there is a ton of cleanup work that should be done in those utility functions.

**Comment by Moriadry** [comment]
I would like to help with it:)

**Comment by draveness** [comment]
> I would like to help with it:)

#77155 has not been merged, please feel free to send PR after it gets merged.

**Comment by Moriadry** [comment]
> > I would like to help with it:)
> 
> #77155 has not been merged, please feel free to send PR after it gets merged.

Okay.

**Comment by draveness** [comment]
/help

@Moriadry  Please remove the help if you still want to do this.

**Comment by kireledan** [comment]
I'd love to help out with this cleanup.
