### ISSUE TITLE
Can I set providerid after kube init?

### ISSUE THREAD

**Issue by 17billion** [kubernetes/kubernetes#79915]
Can I set providerid after kube init?

Pvc is pending and I get the message "GetCloudProvider returned <nil>" as shown below.

```
Name:          prometheus-server
Namespace:     monitoring
StorageClass:  gp2
Status:        Pending
Volume:
Labels:        app=prometheus
               chart=prometheus-8.14.1
               component=server
               heritage=Tiller
               release=prometheus
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type       Reason              Age   From                         Message
  ----       ------              ----  ----                         -------
  Warning    ProvisioningFailed  10s   persistentvolume-controller  Failed to provision volume with StorageClass "gp2": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead
```
I did not set up the CloudProvider when inited kubeadm.
So, is there any way to set the providerid of the cluster already configured via kube init?
(Kubernetes v1.14.1)

**Comment by neolit123** [comment]
> So, is there any way to set the providerid of the cluster already configured via kube init?

configuring a cluster in such a way is not officially supported from kubeadm.
but most importantly there is no way to set a "CloudProvider" field kubeadm.

are you trying to use AWS as an external cloud provider?
are you passing `--cloud-provider=external` to the kubelet?

see this guide:
https://blog.scottlowe.org/2019/02/18/kubernetes-kubeadm-and-the-aws-cloud-provider/
