### ISSUE TITLE
Protected_test.go do not remove tempdir when test finished

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#79922]
**What happened**:

I run the unit tests for project.go, but I found it would not clean the tempdir it created.
![image](https://user-images.githubusercontent.com/12230714/60870299-2784fe00-a263-11e9-8da3-713a78e52634.png)

**What you expected to happen**:

automatically clean up when finishing unit tests.

**How to reproduce it (as minimally and precisely as possible)**:

go test $GOPATH/k8s.io/kubernetes/pkg/volume projected_test.go

**Anything else we need to know?**:

**Environment**: k8s 1.15
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by RainbowMango** [comment]
/assign @cwdsuzhou 

Assign the issue to you since you have fired a pull request.
