### ISSUE TITLE
The scheduler should get pod Info from schedule cache rather than PodLister

### ISSUE THREAD

**Issue by wybzju** [kubernetes/kubernetes#79930]
**What happened**:
https://github.com/kubernetes/kubernetes/blob/955198751cdbf10701607490937d35d0e3d57e50/pkg/scheduler/algorithm/predicates/predicates.go#L1351

why we don't just use the function nodeInfo.Pods() to get the pods' info?
The c.podLister.FilteredList function needs to traverse all pods，and it will increase lots of time. In our case, we need take about 2s to scheduler one pod.
`I0709 08:51:59.701469       1 trace.go:76] Trace[851004334]: "Scheduling default/test-preferred" (started: 2019-07-09 08:51:57.799755143 +0000 UTC m=+436710.026849716) (total time: 1.901686435s):`
However, by using  nodeInfo.Pods(), we can get the result directly and faster

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by wybzju** [comment]
@draveness can you tell me when will you start this issue?

**Comment by ahg-g** [comment]
@wybzju I wonder why are you hitting that code path? the metadata is supposed to be pre-calculated: https://github.com/kubernetes/kubernetes/blob/955198751cdbf10701607490937d35d0e3d57e50/pkg/scheduler/algorithm/predicates/predicates.go#L1346

**Comment by wybzju** [comment]
@ahg-g   I think maybe the version I use is too low. The version is 1.10.2

**Comment by draveness** [comment]
> @ahg-g I think maybe the version I use is too low. The version is 1.10.2

Do you mind to could close this issue since this is intentional according to @huang-wei's https://github.com/kubernetes/kubernetes/pull/80020#issuecomment-512117268 here?
