### ISSUE TITLE
Some problems about workqueue

### ISSUE THREAD

**Issue by yanghaichao12** [kubernetes/kubernetes#79934]
**What happened**:
When I use workqueue(https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/workqueue/queue.go) in the following order: Add(item)-->Done(item),I noticed that the  queue is getting bigger and bigger because of the section：
```go
	if q.dirty.has(item) {
		q.queue = append(q.queue, item)
		q.cond.Signal()
	}
```

**What you expected to happen**:
the queue can be  handled correctly and i want to know Why not judge if there is duplicate data in the slice 'queue'

**How to reproduce it (as minimally and precisely as possible)**:
calling Add(),Done(),Done(),Done(),....... and never calling Get()

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
> How to reproduce it (as minimally and precisely as possible):
> calling Add(),Done(),Done(),Done(),....... and never calling Get()

Get()/Done() calls *must* be paired 1:1. See examples for how to use the workqueue here: https://github.com/kubernetes/client-go/blob/master/examples/workqueue/main.go#L52-L60

/close
