### ISSUE TITLE
GKE IAM authorizer can authorize verb="*" checks, but not specific verbs

### ISSUE THREAD

**Issue by eshiroma** [kubernetes/kubernetes#79958]
**What happened**:
```
$ kubectl auth can-i '*' rolebindings
yes
$ kubectl auth can-i create '*'
yes
```

**What you expected to happen**:
The above should both return "no" because `kubectl auth can-i create rolebindings` returns "no" (as expected).

**How to reproduce it (as minimally and precisely as possible)**:
For user with permission to get but not create rolebindings (in all namespaces):
```
# Expected
$ kubectl auth can-i get rolebindings
yes
$ kubectl auth can-i create rolebindings
no - no RBAC policy matched
Required "container.roleBindings.create" permission.
# Unexpected
$ kubectl auth can-i "*" rolebindings
yes
$ kubectl auth can-i create '*'
yes
```

**Anything else we need to know?**:
Verbose version of what was expected vs. how to reproduce:
ResourceAttributes documentation is inconsistent with experiments for SelfSubjectAccessReview.

Documentation says that '"*" means all' for 'verb' and 'group' (and other fields). This implies AND behavior, but it seems like it may instead be treated as an OR which should be described as 'any' (which is problematic when an AND check is desired).

Source:
https://github.com/kubernetes/api/blob/master/authorization/v1/types.go#L94,L97
Generated API reference:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#resourceattributes-v1-authorization-k8s-io
(unchanged up through v1.15; test cluster had v1.12)

SelfSubjectAccessReview (`kubectl auth can-i`) was too permissive when "*" was used.

For a user that can only read and not write rolebindings, a specific check for "create" and "rolebindings" returned the expected result (no):

```
$ kubectl auth can-i get rolebindings
yes
$ kubectl auth can-i create rolebindings
no - no RBAC policy matched
Required "container.roleBindings.create" permission.
```

However, using `*` in place of the `create` verb yielded the unexpected "yes" (I expected `*` to be the AND of all can-i's for every verb). Similarly, using `*` in place of the rolebindings resource yielded the unexpected "yes" (I expected `*` to be the AND of all can-i's for `create` on every resource).

```
$ kubectl auth can-i "*" rolebindings
yes
$ kubectl auth can-i create '*'
yes
```

The same too-permissive behavior can be seen if "*" replaces either the verb or the API group in a manual curl SelfSubjectAccessReview. Request body was found with `kubectl auth can-i create rolebindings -v=500 2>&1 | grep "Request "`.

Matching the request and response from `kubectl auth can-i get rolebindings`
```
# ENDPOINT=<set from Kubernetes master address from `kubectl cluster-info`
$ TOKEN=$(gcloud auth print-access-token)
$ curl -k \
>     -X POST \
>     -d @- \
>     -H "Authorization: Bearer $TOKEN" \
>     -H 'Accept: application/json' \
>     -H 'Content-Type: application/json' \
>     https://$ENDPOINT/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
> {
>   "kind": "SelfSubjectAccessReview",
>   "apiVersion": "authorization.k8s.io/v1",
>   "spec": {
>     "resourceAttributes": {
>       "namespace": "default",
>       "group": "rbac.authorization.k8s.io",
>       "verb": "get",
>       "resource": "rolebindings"
>     }
>   }
> }
> EOF
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "default",
      "verb": "get",
      "group": "rbac.authorization.k8s.io",
      "resource": "rolebindings"
    }
  },
  "status": {
    "allowed": true
  }
}
```
Matching the request and response from `kubectl auth can-i create rolebindings`
```
$ curl -k \
>     -X POST \
>     -d @- \
>     -H "Authorization: Bearer $TOKEN" \
>     -H 'Accept: application/json' \
>     -H 'Content-Type: application/json' \
>     https://$ENDPOINT/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
> {
>   "kind": "SelfSubjectAccessReview",
>   "apiVersion": "authorization.k8s.io/v1",
>   "spec": {
>     "resourceAttributes": {
>       "namespace": "default",
>       "group": "rbac.authorization.k8s.io",
>       "verb": "create",
>       "resource": "rolebindings"
>     }
>   }
> }
> EOF
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "default",
      "verb": "create",
      "group": "rbac.authorization.k8s.io",
      "resource": "rolebindings"
    }
  },
  "status": {
    "allowed": false,
    "reason": "no RBAC policy matched\nRequired \"container.roleBindings.create\" permission."
  }
}
```
Matching the request and response from `kubectl auth can-i '*' rolebindings`
```
$ curl -k \
>     -X POST \
>     -d @- \
>     -H "Authorization: Bearer $TOKEN" \
>     -H 'Accept: application/json' \
>     -H 'Content-Type: application/json' \
>     https://$ENDPOINT/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
> {
>   "kind": "SelfSubjectAccessReview",
>   "apiVersion": "authorization.k8s.io/v1",
>   "spec": {
>     "resourceAttributes": {
>       "namespace": "default",
>       "group": "rbac.authorization.k8s.io",
>       "verb": "*",
>       "resource": "rolebindings"
>     }
>   }
> }
> EOF
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "default",
      "verb": "*",
      "group": "rbac.authorization.k8s.io",
      "resource": "rolebindings"
    }
  },
  "status": {
    "allowed": true
  }
}
```
Matching the request and response from `kubectl auth can-i create '*'`
```
$ curl -k \
>     -X POST \
>     -d @- \
>     -H "Authorization: Bearer $TOKEN" \
>     -H 'Accept: application/json' \
>     -H 'Content-Type: application/json' \
>     https://$ENDPOINT/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
> {
>   "kind": "SelfSubjectAccessReview",
>   "apiVersion": "authorization.k8s.io/v1",
>   "spec": {
>     "resourceAttributes": {
>       "namespace": "default",
>       "verb": "create",
>       "resource": "*"
>     }
>   }
> }
> EOF
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "default",
      "verb": "create",
      "resource": "*"
    }
  },
  "status": {
    "allowed": true
  }
}
```
Matching the request and response from `kubectl auth can-i create rolebindings`, replacing the group with '*'
```
$  curl -k \
>     -X POST \
>     -d @- \
>     -H "Authorization: Bearer $TOKEN" \
>     -H 'Accept: application/json' \
>     -H 'Content-Type: application/json' \
>     https://$ENDPOINT/apis/authorization.k8s.io/v1/selfsubjectaccessreviews <<'EOF'
> {
>   "kind": "SelfSubjectAccessReview",
>   "apiVersion": "authorization.k8s.io/v1",
>   "spec": {
>     "resourceAttributes": {
>       "namespace": "default",
>       "group": "*",
>       "verb": "create",
>       "resource": "rolebindings"
>     }
>   }
> }
> EOF
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "default",
      "verb": "create",
      "group": "*",
      "resource": "rolebindings"
    }
  },
  "status": {
    "allowed": true
```

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:27:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE (Google Cloud Platform)
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux cs-6000-devshell-vm-d33a2ba5-d0b7-4fb6-8958-a99b276e1cb8 4.14.111+ #1 SMP Sat Jun 22 23:33:41 PDT 2019 x86_64 GNU/Linux (using Cloud Shell)
- Install tools:
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by eshiroma** [comment]
@kubernetes/sig-auth-bug

**Comment by liggitt** [comment]
this looks to be specific to the GKE IAM-based authorizer's handling of the `*` verb

/cc @cjcullen @sambdavidson

**Comment by sambdavidson** [comment]
Hey Erika,

I was looking into this issue and I think I know what is going on.

Would your identity that you are using to call `kubectl auth can-i "*" rolebindings` happen to have the `container.thirdPartyObjects.update` permission? That would be case if your identity had a Google IAM role binding to a custom role with that permisson, _Kubernetes Engine Developer_, or _Kubernetes Engine Admin_. 

Attempting to repro with a GCP service account with 0 permissions I get:

```bash
kubectl auth can-i "*" rolebindings
no - Required "container.thirdPartyObjects.update" permission.
```

This is because within GKE's Authz IAM service we don't currently have support for wildcard stars. So what happens is we see the known resource `rolebindings` but we don't recognize the verb _string literal of an asterisk ("*")_  among known verbs "create", "delete", "get", "list", ... ect.

Because GKE doesn't recognize the "*" it just assumes you are talking about some unknown CRD or something so it falls back to a `container.thirdPartyObjects.update` permission.

But you have raised an interesting use case for why changing the functionality of "*" either externally in K8s or internally in GKE could be valuable. I will discuss it further within GKE auth folks.
