### ISSUE TITLE
which http code may lead to apiserver to create pod

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#79957]
when i  invoke apiserver to create a pod, it will return http code with 2xx,3xx,4xx,5xx.

1.  I know 2xx means pod will be created, and then I will check the pod status periodic. 
2. Is there other situation(maybe 4xx,5xx) which will lead to a pod to be created.I wanna filter impossible situation and reduce visiting to apiserver

I thought 5xx may lead to this result, maybe it cost apiserver too long to return, but pod is created.Am I right ? Or are there other situation?

**Comment by roycaihw** [comment]
cc @MikeSpreitzer

**Comment by liggitt** [comment]
possible places to document this:
https://kubernetes.io/docs/reference/using-api/api-concepts/

**Comment by roycaihw** [comment]
ref https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#success-codes

**Comment by roycaihw** [comment]
also error codes are missed in our openapi doc: https://github.com/kubernetes/kubernetes/issues/69014. I owe a PR for this one

**Comment by mjaow** [comment]
@roycaihw 
I thought 5xx may also lead to pod to be created(server timeout, but pod is created). But the doc didn't mention it.

**Comment by liggitt** [comment]
> 500 StatusInternalServerError
> 
> Indicates that the server can be reached and understood the request, but either an unexpected internal error occurred and the outcome of the call is unknown, or the server cannot complete the action in a reasonable time (this may be due to temporary server load or a transient communication issue with another server).

**Comment by mjaow** [comment]
thx.

**Comment by MikeSpreitzer** [comment]
@mjaow : I assume you closed this because https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#success-codes documents that the 500 status code means the action may or may not have completed.

I am betting that status code 504 also means the action may or may not have been done, but that doc does not spell this out.

**Comment by mjaow** [comment]
@MikeSpreitzer can doc spell this out.I think it may affect people's desicion in what to do after creating pod
