### ISSUE TITLE
Containers with "m" used as abbreviation in memory limits fail to start on Linux, and consume 1e+9 too much memory on Windows

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#79950]
## Background

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

  Limits and requests for memory are measured in bytes. You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki. For example, the following represent roughly the same value:

  `128974848, 129e6, 129M, 123Mi`

## Bug

If someone uses a lowercase letter, for example `m`, that has inconsistent behavior between Windows & Linux. `m` is a valid suffix for CPU but not memory.

> Note: `docker` command line options do support `m`, `b`, `k` and `g`. [docker resource constraints](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory)

On Linux, the `m` prefix is dropped if it's included as part of a memory resource. This resource allocation will create an allocation of 300 bytes, not 300 Megabytes or Mebibytes. That's too small and container startup will fail. See [full error logs](#full-error-logs) below.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test1
spec:
  containers:
  - name: nginx
    image: library/nginx
    resources:
      limits:
        cpu: 1
        memory: 800m
    ports:
      - containerPort: 80
  nodeSelector:
    "beta.kubernetes.io/os": linux
```

On Windows, the `m` prefix is treated the same as `M`. This resource allocation will be 300 Megabytes, and container startup will succeed.

```
apiVersion: v1
kind: Pod
metadata:
  name: iis-test2
spec:
  containers:
  - name: iis
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    resources:
      limits:
        cpu: 1
        memory: 800m
    ports:
      - containerPort: 80
  nodeSelector:
    "beta.kubernetes.io/os": windows
```

This would have the same effect on resources as `docker run --memory 800m -d mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019` on Windows.

## Proposed Fixes

There are a few different places this could be fixed. They're not mutually exclusive, so I'm asking SIG-Node and API reviewers to consider the impact of each.

Parsing cpu & memory limits separately is not feasible as the same string parser is shared for all resource types.

### Fix 1 - reject memory limits below a certain threshold in the admission controller

This would be the most consistent as the failure would happen immediately, and be consistent on both Windows & Linux. Let's start with a strawman proposal of 10Mi as the container minimum. Windows actually needs more like 200Mi, but I think 10Mi would be enough to catch the most egregious mistakes such as "10m".

Source Locations: 

https://github.com/kubernetes/kubernetes/blob/f47da8a75d13590322a4e1df502cf6629b2c36fa/plugin/pkg/admission/limitranger/admission.go#L213

### Fix 2 - reject memory limits with `m` in kubelet

This would fail later, but won't involve changes to the apiserver, common APIs or admission controller. The error messages can still be made consistent between Linux & Windows, but different minimums can be enforced in each side. This could be implemented in the code that creates the container configs before passing them to CRI.

Source locations:

Linux: https://github.com/kubernetes/kubernetes/blob/33081c1f07be128a89441a39c467b7ea2221b23d/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L38
Windows: https://github.com/kubernetes/kubernetes/blob/b39d8f4777b3a01359046d05b1de17298b818f2f/pkg/kubelet/kuberuntime/kuberuntime_container_windows.go#L34

### Full error logs

Here's what the status looks like for the failed pod:

```
$ kubectl get pod
NAME                                       READY   STATUS              RESTARTS   AGE
iis-test1                                  1/1     Running             0          10m
iis-test2                                  1/1     Running             0          10m
nginx-test1                                1/1     Running             0          10m
nginx-test2                                0/1     ContainerCreating   0          10m

patrick@planglx1:~/gist/a92766f23d39b442e5c8d92cb4ed05f2$ kubectl describe pod nginx-test2
Name:               nginx-test2
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-20293662-vmss000000/10.240.0.4
Start Time:         Tue, 09 Jul 2019 23:44:09 +0000
Labels:             <none>
Annotations:        <none>
Status:             Pending
IP:                 
Containers:
  nginx:
    Container ID:   
    Image:          library/nginx
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  800m
    Requests:
      cpu:        100m
      memory:     300m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jrvwx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-jrvwx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jrvwx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                    From                                        Message
  ----     ------                  ----                   ----                                        -------
  Normal   Scheduled               10m                    default-scheduler                           Successfully assigned default/nginx-test2 to aks-nodepool1-20293662-vmss000000
  Warning  FailedCreatePodSandBox  10m                    kubelet, aks-nodepool1-20293662-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-test2": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:293: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
  Warning  FailedCreatePodSandBox  10m                    kubelet, aks-nodepool1-20293662-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-test2": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"read init-p: connection reset by peer\"": unknown
  Warning  FailedCreatePodSandBox  5m52s (x230 over 10m)  kubelet, aks-nodepool1-20293662-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-test2": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"EOF\"": unknown
  Normal   SandboxChanged          52s (x538 over 10m)    kubelet, aks-nodepool1-20293662-vmss000000  Pod sandbox changed, it will be killed and re-created.
```
**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.0
- Cloud provider or hardware configuration: AKS

**Comment by liggitt** [comment]
/remove-sig api-machinery

cc @kubernetes/api-reviewers 

See previous discussion in https://github.com/kubernetes/kubernetes/issues/49442

Tightening pod API validation is not generally feasible, since that can cause existing persisted data to be treated as invalid, and in some cases, not be able to be updated in order to be deleted. See https://github.com/kubernetes/kubernetes/issues/64841

If the windows CRI cannot allocate sub-megabyte memory values, I would expect an attempt to do so to either get as close as possible (e.g. 1MB) or error.

**Comment by PatrickLang** [comment]
Just to clarify here - the bad impact is actually on Linux, not Windows. Windows assumes a "m" in a memory unit is Mi. Linux drops ignores the letter. That means `800m` = 800 bytes on Linux, but 800 Mi on Windows

**Comment by lavalamp** [comment]
"800m" actually means 800 *millibytes*, which isn't sensible. The config is very wrong and apparently there's another bug somewhere, too. Is kubelet not using the resource.Quantity type to interpret this value before handing it to the container runtime?

**Comment by liggitt** [comment]
both can be bad. linux fails to run the container (as expected for an untenably small memory amount). windows allows a container to consume 1024*1024 as much memory as was reserved in resourcequota for it, right?

**Comment by lavalamp** [comment]
https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go#L46

**Comment by lavalamp** [comment]
Do the platforms both behave the same if you pass the intended value of "800M" or "800Mi"? (capital M)

**Comment by PatrickLang** [comment]
yes, both work with `M` or `Mi`. Windows works with `m`, but Linux doesn't.

**Comment by lavalamp** [comment]
Are you sure it's turned into 800 bytes on linux? I'd expect this to be rounded to either 1 byte or 0 bytes if it's handled correctly.

800m should not work on windows, either, unless windows can allocate 6.4 bits to a program? :)

**Comment by lavalamp** [comment]
I do think that validation should forbid memory requests smaller than a byte, but as Jordan points out, the validation change is dangerous.

**Comment by PatrickLang** [comment]
```[  +0.000002] Task in /kubepods/burstable/pod52c7f930-28e7-473e-bc7b-cf480d845528/0d3abb025828db37f2edecadef54e113c693adf5d4871189ea21577de8f33db7 killed as a result of limit of /kubepods/burstable/pod52c7f930-28e7-473e-bc7b-cf480d845528
[  +0.000006] memory: usage 0kB, limit 0kB, failcnt 14428
[  +0.000001] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[  +0.000002] kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
[  +0.000000] Memory cgroup stats for /kubepods/burstable/pod52c7f930-28e7-473e-bc7b-cf480d845528: cache:0KB rss:0KB rss_huge:0KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB inactive_anon:0KB active_anon:0KB inactive_file:0KB active_file:0KB unevictable:0KB
[  +0.000061] Memory cgroup stats for /kubepods/burstable/pod52c7f930-28e7-473e-bc7b-cf480d845528/0d3abb025828db37f2edecadef54e113c693adf5d4871189ea21577de8f33db7: cache:0KB rss:0KB rss_huge:0KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB inactive_anon:0KB a
[  +0.000034] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[  +0.000104] [ 9263]     0  9263     1942        1    45056        0          -999 exe
[  +0.000001] Memory cgroup out of memory: Kill process 9263 (exe) score 12000 or sacrifice child
[  +0.026231] Killed process 9263 (exe) total-vm:7768kB, anon-rss:4kB, file-rss:0kB, shmem-rss:0kB
[  +0.013503] oom_reaper: reaped process 9263 (exe), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by liggitt** [comment]
> Are you sure it's turned into 800 bytes on linux? I'd expect this to be rounded to either 1 byte or 0 bytes if it's handled correctly.

I think it rounds to the nearest byte, and below a certain threshold (like 4MB), containers will just not start

**Comment by liggitt** [comment]
> I do think that validation should forbid memory requests smaller than a byte, but as Jordan points out, the validation change is dangerous.

I think it can be done relatively safely with ratcheting validation. memory requests that are fractions of a byte are certainly a mistake, and do not work properly on any container runtime.

**Comment by lavalamp** [comment]
> `limit 0kB`

I think it would be best if windows also interpreted 'm' values as a request for 0 bytes and failed them, rather than "helping" people and training them to do the wrong thing :/

**Comment by lavalamp** [comment]
If these always fail, then the risk of breaking an existing setup is pretty low and it might be safe to forbid them in the API.

**Comment by liggitt** [comment]
> If these always fail, then the risk of breaking an existing setup is pretty low and it might be safe to forbid them in the API.

that was my claim in https://github.com/kubernetes/kubernetes/issues/64841#issuecomment-405436597. I'm happy to resurrect the ratcheting for the truly impossible-to-succeed cases.

**Comment by liggitt** [comment]
> I think it would be best if windows also interpreted 'm' values as a request for 0 bytes and failed them, rather than "helping" people and training them to do the wrong thing :/

even more than that, the current handling makes ResourceQuota ineffective for memory on windows

**Comment by liggitt** [comment]
(though LimitRange could be used to specify a minimum memory amount a pod could request)

**Comment by PatrickLang** [comment]
I'm not sure where the `m` is being interpreted at the moment. need more digging. That was a valid abbreviation in the Moby/Docker codebase which Windows is still using [doc](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory)

**Comment by PatrickLang** [comment]
I can't figure out exactly what's going on. Docker shows 1 byte on Windows but yet it still runs. I think it's ignored not applied

**Comment by drewboswell** [comment]
> > Are you sure it's turned into 800 bytes on linux? I'd expect this to be rounded to either 1 byte or 0 bytes if it's handled correctly.
> 
> I think it rounds to the nearest byte, and below a certain threshold (like 4MB), containers will just not start

@liggitt  Completely outside of this issue I guess, but the 4MB limit... I can' t find it documented anywhere and I've had that problem happen to me. If you set less than 4MB you'll get a nice failure to start container.

What's the reasoning for this? is it documented somewhere?

**Comment by drewboswell** [comment]
Woops, never mind. It's in the docker and OCI runtime specs. Min supported 4MB ignore my comment.

**Comment by matthyx** [comment]
I think it's up to sig windows to ensure we have consistent behavior here...
/remove-sig node

**Comment by marosset** [comment]
Let me check if this is still an issue with containerd.

**Comment by SJrX** [comment]
FYI I spent the past 8 hours debugging an issue with a cluster where this was the cause using kubernetes v1.24.1, using containerd 1.6.8 on Ubuntu 22.04.

The behaviour that I saw gave no clue as the problem, scheduling the following container:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 128m
```

Gave the error:
```
MountVolume.SetUp failed for volume "kube-api-access-gn8vg" : write /var/lib/kubelet/pods/cb97d7e0-3a38-473c-8b26-3a6ca218a0da/volumes/kubernetes.io~projected/kube-api-access-gn8vg/ │
│ ..2022_10_11_15_27_51.1036926517/token: no space left on device
```

Disabling the service account gave the following cryptic error:

```
 Warning  FailedCreatePodSandBox  8s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: star
ting container process caused: process_linux.go:385: applying cgroup configuration for process caused: error while starting unit "cri-containerd-becc22e57d63d34a2b7945a774d7b78f188e3e38abf24a6bd544628604c865ca.scope" with properties [{
Name:Description Value:"libcontainer container becc22e57d63d34a2b7945a774d7b78f188e3e38abf24a6bd544628604c865ca"} {Name:Slice Value:"kubepods-burstable-pode450a15e_4b71_4dfa_8777_09a3b7210005.slice"} {Name:PIDs Value:@au [36355]} {Name
:Delegate Value:true} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]: error creating systemd unit `cri-contain
erd-becc22e57d63d34a2b7945a774d7b78f188e3e38abf24a6bd544628604c865ca.scope`: got `failed`: unknown       
```
And looking at containerd didn't really give much insight.
```
ime="2022-10-11T16:53:55.968165146Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-nosa,Uid:1f7bd06f-badc-457f-ab12-35962d4dd6c5,Namespace:bind-dns-server,Attempt:0,} failed, error" error="failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope\" (properties [{Name:Description Value:\"libcontainer container aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147\"} {Name:Slice Value:\"kubepods-burstable-pod1f7bd06f_badc_457f_ab12_35962d4dd6c5.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [23299]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): error creating systemd unit `cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope`: got `failed`: unknown"
```

Systemd didn't give much insight:
```
ct 11 16:53:54 conway05 systemd[1]: cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope: Failed with result 'resources'.
Oct 11 16:53:54 conway05 systemd[1]: cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope: Failed to add PIDs to scope's control group: Cannot allocate memory
Oct 11 16:53:54 conway05 systemd[1]: cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope: Failed to create cgroup /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1f7bd06f_badc_457f_ab12_35962d4dd6c5.slice/cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope: Cannot allocate memory
Oct 11 16:53:54 conway05 systemd[1]: cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope: Failed to create cgroup /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1f7bd06f_badc_457f_ab12_35962d4dd6c5.slice/cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6694efcd4f3a147.scope: Cannot allocate memory
Oct 11 16:53:54 conway05 systemd[1]: cri-containerd-aaa6d7be604e388d4c0989b6e6ff2aca068f970782ed239ca6
```

Some kernel log messages gave me a hint.

```
Oct 11 16:36:48 conway05 kernel: Memory cgroup stats for /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1f7bd06f_badc_457f_ab12_35962d4dd6c5.slice:
Oct 11 16:36:48 conway05 kernel: swap: usage 0kB, limit 9007199254740988kB, failcnt 0
Oct 11 16:36:48 conway05 kernel: memory: usage 0kB, limit 0kB, failcnt 1653
```

Namely that the memory limit is 0kB, and some how I found this bug report right away. If actually restricting the value here is not feasible, what about logging warnings messages.

**Comment by marosset** [comment]
/assign
/milestone v1.26
Let me see what we can do here.
At a minimum we should be able to log warnings.

**Comment by liggitt** [comment]
we've logged warnings on fractional memory requests/limits/overhead since 1.22:

https://github.com/kubernetes/kubernetes/commit/ecdecafdc89cb574a08c951d7771ddfdba1aa201#diff-8c706a0acd7507b84031c381f4faef39794109ae88a0df95fabc45af5b58f4beR219-R240

**Comment by jsturtevant** [comment]
since logs are in place we can close this for now
/close
