### ISSUE TITLE
kubectl apply failing for pod with imagePullSecrets and resources defined in yaml

### ISSUE THREAD

**Issue by bikashkarmakar** [kubernetes/kubernetes#79975]
**What happened**: Trying to deploy a pod from a private container registry with kubernetes secret and resources with the attached YAML file
kubectl apply -f cloudlink-pyapp2-pod.yaml 
error: error validating "cloudlink-pyapp2-pod.yaml": error validating data: [ValidationError(Pod.spec.containers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container, ValidationError(Pod.spec): unknown field "resources" in io.k8s.api.core.v1.PodSpec]; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**: pod created successfully

**How to reproduce it (as minimally and precisely as possible)**: kubectl apply -f cloudlink-pyapp2-pod.yaml . Rename the attached txt file to "cloudlink-pyapp2-pod.yaml"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):Mac OS X 10.14.3
- Kernel (e.g. `uname -a`):
- Install tools: kubectl
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bikashkarmakar** [comment]
@kubernetes/sig-cli-bugs as per https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ ,the yaml should  specify the resouces for the containers. But getting rror: error validating "cloudlink-pyapp2-pod.yaml": error validating data: [ValidationError(Pod.spec.containers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container, ValidationError(Pod.spec): unknown field "resources" in io.k8s.api.core.v1.PodSpec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by liggitt** [comment]
imagePullSecrets is a field in the podSpec, not in the container. check the nesting of your yaml file to make sure the imagePullSecrets field is specified at the correct level.

/close
