### ISSUE TITLE
Better default value for resource limits

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#79988]
When a container specifies a higher request value than the limitrange default value, then Kubernetes fails the deployment with complaints about `must be less than or equal to cpu limit` or `must be less than or equal to memory limit`.

This is not particularly helpful for the user. I would argue that it is more intuitive to apply a default limit value of `MAX(request, limitrange default)` here.

**Comment by aerfio** [comment]
at least more helpful error message could be helpful 😞
