### ISSUE TITLE
kubeadm doesn't fallback to client version when there is 502 Bad Gateway

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/kubernetes#79997]
**What happened**:
I was using kubeadm to generate cluster ca:

```
kubeadm init phase certs ca --cert-dir /etc/kubernetes/pki/
```

The CA generation failed because of 502 bad gateway returned and the response body isn't empty when it's trying to fetch stable version from internet. In this case, the `KubernetesReleaseVersion` function returns error instead of falling back to local client version:

```
unable to fetch file. URL: "https://dl.k8s.io/release/stable-1.txt", status: 502 Bad Gateway
failed to run commands: exit status 1
```

[here](https://github.com/kubernetes/kubernetes/blob/v1.13.7/cmd/kubeadm/app/util/version.go#L176) is how kubeadm fetches stable version and [here](https://github.com/kubernetes/kubernetes/blob/v1.13.7/cmd/kubeadm/app/util/version.go#L90) is how the error is handled for `fetchFromURL`.

Should kubeadm always fall back to client version when there is any internet issue? Otherwise, this sounds defeat the purpose of fallback.

/sig cluster-lifecycle

**What you expected to happen**:
kubeadm falls back to local client version when there is any internet issue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.7
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by RainbowMango** [comment]
@timothysc 
I'd like to take this issue.  It would be better if you could give some directions.
/assign

**Comment by leakingtapan** [comment]
recreate the issue in kubernetes/kubeadm: https://github.com/kubernetes/kubeadm/issues/1662

/close

**Comment by leakingtapan** [comment]
@RainbowMango the fix will be removing the [if condition](https://github.com/kubernetes/kubernetes/blob/v1.13.7/cmd/kubeadm/app/util/version.go#L90) when failed to `fetchFromURL` and add some unit test if I don't missing anything

**Comment by RainbowMango** [comment]
@leakingtapan Got it. Thanks.
