### ISSUE TITLE
k8s node not support field selector well

### ISSUE THREAD

**Issue by kitianFresh** [kubernetes/kubernetes#80010]
following is version of kubernetes client and server version

`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-mt20190128.5+47e1f54c020515", GitCommit:"47e1f54c020515363ccecf297239de41560831a5", GitTreeState:"clean", BuildDate:"2019-02-19T11:09:04Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}`

when i use `kubectl get nodes --field-selector spec.Unscheduable=true` or `kubectl get nodes --field-selector status.Phase=running` , all will report
`Error from server (BadRequest): Unable to find "nodes" that match label selector "", field selector "spec.Unschedulable=true": field label not supported: spec.Unschedulable`

but for pod, it's fine.
`kubectl get pods --field-selector status.phase=Running`

**Comment by ricky1993** [comment]
kubectl get nodes --field-selector spec.unschedulable=true
Have a try this command, it works for me

**Comment by ricky1993** [comment]
BTW, node field-selector only support metadata.name and spec.unschedulable.
