### ISSUE TITLE
Update libopenstorage/openstorage dependency to a release version

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#80029]
Found this when trying to see which vendored dependencies does not use a proper tag (and is using a random SHA). 

The https://github.com/libopenstorage/openstorage dependency is very old and there have been a lot of updates to it:
Looks like the https://github.com/libopenstorage/openstorage/compare/093a0c388875...v8.0.0

However there does not seem to be anyone around to take care of the portworx plugin. Is it time to deprecate it? is anyone using it?

/sig storage

**Comment by dims** [comment]
cc @harsh-px ?

**Comment by harsh-px** [comment]
Hello @pditommaso, The portworx volume plugin is definitely in use.

The portworx volume plugin doesn't need frequent updates since the plugin acts as a simple client to all provisioning calls. In the same view, the vendored openstorage package doesn't need to be updated too. The server side implementation in Portworx handles all the latest Portworx features.

**Comment by harsh-px** [comment]
cc: @lpabon

**Comment by dims** [comment]
@harsh-px in that case, can you please update the dependency to a specific tag instead of a random SHA?

**Comment by dims** [comment]
/assign @harsh-px 

updated the title of the issue as well

**Comment by dims** [comment]
@lpabon my request is not for a new release or tag in libopenstorage/openstorage repository. Just to update the SHA we use in our k/k repository to one of the released versions ( https://github.com/libopenstorage/openstorage/tags ). This is not asking or demanding anything to be done in libopenstorage/openstorage, just that we should update what we use from there (and avoid a random SHA). We are trying to do this for all vendored libraries (one by one … slowly as part of the sig-arch code organization sub project, so it’s not a random request)

**Comment by dims** [comment]
After a chat with @lpabon - apparently this request is coming across the wrong way https://kubernetes.slack.com/archives/C09QZFCE5/p1563402365367900

```
lpabon  [5 minutes ago]
no problem @dims, but can you do me a favor? Can you bring this up the chain that this is not the way to run this project and in a way push other projects to do what this one wants? If they have questions, they can talk to me directly.
```

I am closing this out as it seems to add a over head 
```
The point is that a project A should not be dictating to project B what to do
Think of ubuntu telling all the repos they use that they must tag at a certain point.. that's not how things work
```

/close
