### ISSUE TITLE
pod with pv  cannot be scheduled

### ISSUE THREAD

**Issue by clh-kubernetes** [kubernetes/kubernetes#80035]
**What happened**:
Start two pods, both pods have pv, and the two pods are set to anti-affanity.
pod1 is scheduled on node1，and the pv bounded to pod2 is also on node1
the anti-affinity is set between pod2 and pod1, causing pod2 to always be pending.
[detail error](https://github.com/clh-kubernetes/program1/blob/master/error.png)

**What you expected to happen**:
pod1 and pod2  are scheduled to different nodes 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):kubernetes 1.11.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): redhat 7u3
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by SataQiu** [comment]
Hmm... I guess you created PV manually. You should not bind the PVs to the same node.
I suggest you use PVC instead of PV, dynamic provisioning can shedule Pod with PV well.

**Comment by clh-kubernetes** [comment]
> Hmm... I guess you created PV manually. You should not bind the PVs to the same node.
> I suggest you use PVC instead of PV, dynamic provisioning can shedule Pod with PV well.

**Comment by clh-kubernetes** [comment]
To: SataQiu
By studying the source code of k8s(1.11.4), we find that  after binding the PVC and PV of the pod, the bindVolumeWorker will execute a new sched. config. Error () and reschedule the pod whether the bind result is successful or not.

when affinity-pods are scheduled for the first time, if a pod with unbound PVC, it binds PVC and PV first , and then the pod is rescheduled. Before the pod is scheduled to a node for the second time  or Running on this node. Another anffinity pod may also be scheduled on the node and then bound to PVC. In this way, two affinity-pods, one pod Running to the node,  the other pod scheduled for the first time, only bound its PVC to the PV on the node. Then, on the second schedule, it can only be scheduled to the node, but the node already has a Running pod that is affinity to the pod. Ultimately, the pod will never be scheduled.

Namely, in the current K8S cluster, a node can not satisfy the MatchInterPodAffinity, and can not be selected. And because the pv.Spec.NodeName of the PV has been fixed, other nodes can not be selected because they can not satisfy the CheckVolumeBinding. Ultimately, the pod can never be scheduled.
