### ISSUE TITLE
Kubernetes should get correct Pause image based on windows build number

### ISSUE THREAD

**Issue by jwlogemann** [kubernetes/kubernetes#80032]
**What would you like to be added**:
K8s uses a pause images for infrastructure reasons. On Windows this image must match the kernel version of the host operating system, or trying to run pods will fail with the fairly vague error message "Container OS version must match the host OS version".

Kubernetes on windows uses the "mcr.microsoft.com/k8s/core/pause:1.0.0" image as pause image. This is based on nanoserver:1809, so running k8s on Server 1903 will fail every workload with a strange error message about container OS version mismatch. 

The obvious solution seems to me to build several versions of the pause image with every supported version of Nanoserver as the base (1803, 1809, 1903), and then tag them accordingly, and use the right one when starting k8s. So instead of using "mcr.microsoft.com/k8s/core/pause:1.0.0" use "mcr.microsoft.com/k8s/core/pause:1809" or "mcr.microsoft.com/k8s/core/pause:1903"

**Why is this needed**:
This will make running k8s on windows a lot more user friendly, by removing difficult to debug default behaviour.

/sig windows

**Comment by michmike** [comment]
our goal is to build additional images for all the operating systems we support. today, we only support 1809 which is why that's the only image available. we also revamped the image to a new version to include new capabilities like port-forward

**Comment by artisticcheese** [comment]
This needs to be reoponed as issue is not fixed and shall  be using multiplatform image for pause image.

**Comment by michmike** [comment]
@marosset PTAL

**Comment by michmike** [comment]
cc: @adelina-t

**Comment by marosset** [comment]
We a multiarch/multiplatform pause image for Windows published at mcr.microsoft.com/oss/kubernetes/pause:1.3.0

This image should contain imags for Windows versions 1803, 1809 / 2019, 1903, and 1909.

@artisticcheese can you take a look at this image and see if it meets your needs?

**Comment by artisticcheese** [comment]
So to make use of it I need to modify kubelet service start up parameter, correct? Because it's currently set to 1.2.0

**Comment by marosset** [comment]
The image name changed as well due to some new requirements on naming for mcr images.
mcr.microsoft.com/k8s/core/pause:1.2.0 to mcr.microsoft.com/oss/kubernetes/pause:1.3.0

Our goal moving forward is to publish new versions of mcr.microsoft.com/oss/kubernetes/pause which container support for new windows server releases as they happen.

**Comment by marosset** [comment]
Yes - you'll need to have the --pod-infra-countainer-image argument for the kubelet to point to the new pause image when running on Windows versions released after 1809/2019

**Comment by artisticcheese** [comment]
Yes, this works with `mcr.microsoft.com/oss/kubernetes/pause:1.3.0`. Docs needs to be updated and binaries, otherwise out of the box kubernetes installed on 1909 and using 1909 images would fail straight up.

**Comment by marosset** [comment]
Yes, we should update docs for this.
Also I noticed that the Windows version support matrix at https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#compute is out of date.
We should update at the same time.
cc @michmike

**Comment by artisticcheese** [comment]
How do you guys build 1909 images since apparently none of K8s images are 1909 compatible since Github actions do not have 1909 runner (https://github.com/kubernetes-sigs/sig-windows-tools/issues/61)
