### ISSUE TITLE
deploymenet delete history

### ISSUE THREAD

**Issue by mhamzeh27903** [kubernetes/kubernetes#80038]
Dear Kuberenetes,

We are supporting products running ontop k8s systems, all our applications are installed using helm and they are templated. 

If a customer deletes parts of the deployment we have no way of figuring out when did that happen and what user did that. 

Can we include a feature to list the delete history of deployment?

Thanks,
Mohammed

**Comment by php-coder** [comment]
@mhamzeh27903 It seems like the case for audit: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/ ? Would it help in your case?

/sig apps

**Comment by kow3ns** [comment]
We feel that audit logging is implemented specifically to meet this use case. Please feel free to reopen with clarification if we misunderstand your requirements.
