### ISSUE TITLE
Kubelet pod names break log directory path

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#80042]
**What happened**:
Kubelet log directories are joined with a flat _NAMESPACE_PODNAME_UID_ directory path. The limit on pod names are 253 characters https://github.com/kubernetes/kubernetes/pull/78188#issuecomment-494609951. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/helpers.go#L180-L183

```go
func BuildPodLogsDirectory(podNamespace, podName string, podUID types.UID) string {
	return filepath.Join(podLogsRootDirectory, strings.Join([]string{podNamespace, podName,
		string(podUID)}, logPathDelimiter))
}
```

Joining a long pod name with the namespace and UID will be over 255 characters causing the directory creation and file open to fail. Most modern filesystems have a limit of 255 characters for file directory names and filenames. 

The pod with a long pod name will silently fail to log.

ref: https://github.com/kubernetes/kubernetes/pull/74441
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1711544

**What you expected to happen**:
Long pod names should not impact the ability to log.

**How to reproduce it (as minimally and precisely as possible)**:
[Test Case](https://github.com/openshift/origin/blob/4ecc8c3a2bd6ad0a49325d0511b33aeaeb3be22e/test/extended/builds/long_names.go#L11)

**Anything else we need to know?**:

**Environment**:
Kubernetes 1.14.0 and later

**Comment by smarterclayton** [comment]
Hrm, I thought we had an auto "hashify" the extended part of the string when it exceeded length, but maybe I'm wrong.  That might have been the very, very, very, very old implementation.
