### ISSUE TITLE
tests: Cannot build jessie-dnsutils image

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#80052]
**What happened**:

The image ``jessie-dnsutils`` cannot be built anymore, since its mirrors has been archived. For more details, see: https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**What you expected to happen**:

The image should be buildable.

**How to reproduce it (as minimally and precisely as possible)**:

    cd kubernetes/tests/images
    make all-container WHAT=jessie-dnsutils

**Anything else we need to know?**:

/sig testing
/area conformance

/priority important-soon

**Environment**: N/A
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A 
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/76838#issuecomment-510553220
