### ISSUE TITLE
kubeadm: ignored certificate-authority option in discovery file

### ISSUE THREAD

**Issue by vkhromov** [kubernetes/kubernetes#80065]
**What happened**:
`kubeadm join` with discovery file containing `certificate-authority` option pointed to a file with CA certificate (instead of default `certificate-authority-data`) fails.

**What you expected to happen**:
`kubeadm join` with discovery file containing `certificate-authority` option pointed to a file with CA certificate successfully load the certificate from the file and use it.

**How to reproduce it (as minimally and precisely as possible)**:
For a discovery file
* extract CA certificate from `certificate-authority-data` into an external file
* remove `certificate-authority-data`
* add `certificate-authority` pointing to the external file

**Anything else we need to know?**:
nope

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.1-dirty", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"dirty", BuildDate:"2019-07-01T19:30:04Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
`Linux kubestage1-uswest1adevc 4.4.0-1085-aws #96-Ubuntu SMP Tue Jun 11 09:08:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
`kubeadm`
- Network plugin and version (if this is a network-related bug):
N/A
- Others:

@kubernetes/sig-cluster-lifecycle-kubeadm

**Comment by RainbowMango** [comment]
/assign @vkhromov 

Assign this issue to you as you have present a PR.
