### ISSUE TITLE
Container termination reason while SIGTERM

### ISSUE THREAD

**Issue by lhsm** [kubernetes/kubernetes#80089]
**What would you like to be added**:
New reason for exit code 143 or map SIGTERM to "Completed" instead current "Error"

**Why is this needed**:
When you redeploy the pod container (a Java app) that received SIGTERM and ends with code 143. As a result, container.state.terminated.reason becomes “Error”
So container is restarted in the normal way, but the reason for its termination is "Error".
In addition, the monitoring tool check this reason and report it.

**Comment by BenTheElder** [comment]
@kubernetes/sig-node-feature-requests

**Comment by BenTheElder** [comment]
Re-reading this:
> New reason for exit code 143 or map SIGTERM to "Completed" instead current "Error"

143 is an application specific exit code. SIGTERM is a signal, not an exit code.
Non-zero exit codes are not success.

https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdlib.h.html

If you'd like a non-zero exit code to be ignored, you can wrap your process like this:
```
command:
- sh
- -c
- 'foo || (r=$?; [ $r -eq 128 ] || exit $r)'
```

> When you redeploy the pod container (a Java app) that received SIGTERM and ends with code 143. As a result, container.state.terminated.reason becomes “Error"
> So container is restarted in the normal way, but the reason for its termination is "Error".

It is not normal to exit non-zero on Linux / POSIX except when the process is in error.

If you're interested in some change to error handling, even though I don't think it's likely, you'll need to file an enhancement https://github.com/kubernetes/enhancements

/close

**Comment by php-coder** [comment]
> If you'd like a non-zero exit code to be ignored, you can wrap your process like this:
> 
> command:
> - sh
> - -c
> - 'foo || (r=$?; [ $r -eq 128 ] || exit $r)'

I recall that there was a pitfall with such approach where `sh` doesn't send a signal that it got to its children: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ This might lead to zombie process and slower the time of container shutdown. Please, correct me if I'm wrong here.
