### ISSUE TITLE
Preference/optional form of PodSpec.NodeSelector

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#8008]
Borg has preferences a.k.a. "soft constraints." We should have the same thing in Kubernetes. (Try to place this pod on a node that satisfies this selector, but if you can't, schedule it anywhere else.) We could call it PodSpec.PreferredNodeSelector or something like that.

Sorry if this issue is already filed but I didn't immediately see it.

**Comment by davidopp** [comment]
This is related to #367

**Comment by timothysc** [comment]
subscribe

**Comment by davidopp** [comment]
This is part of #18261

**Comment by timothysc** [comment]
Can we close this one then, and rally on the proposals?

**Comment by davidopp** [comment]
Agreed.
