### ISSUE TITLE
Switch to k8s.io/utils/inotify 

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#80092]
- [x] Fix fd leak
- [x] Fixing golint issues in k8s.io/utils/inotify 
- [x] Switch cadvisor to use k8s.io/utils/inotify  ( https://github.com/google/cadvisor/pull/2269 )
- [ ] Switch k/k to use k8s.io/utils/inotify  ( https://github.com/kubernetes/kubernetes/pull/80689 )
- [ ] Switch k/k to use cadvisor (with the change above)

**Comment by dims** [comment]
/area code-organization
/sig architecture

cc @Pothulapati @alok87 @rohitsardesai83

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/75526

**Comment by Pothulapati** [comment]
Working on golint issues right now.

**Comment by cpuguy83** [comment]
Did you fix the fd leak issues?

**Comment by dims** [comment]
@cpuguy83 this was just migration. please go ahead and file a PR for the fd leak issue specifically

**Comment by cpuguy83** [comment]
https://github.com/kubernetes/utils/pull/101

**Comment by Pothulapati** [comment]
CAdvisor is switched to `k8s.io/utils/inotify` https://github.com/google/cadvisor/pull/2269 

Next, should be switching k/k. :)

**Comment by dims** [comment]
@Pothulapati please don't forget to update cadvisor in k/k as well.
