### ISSUE TITLE
Support kubectl configuration file loading from a '~/.kube/config.d' directory

### ISSUE THREAD

**Issue by dwmkerr** [kubernetes/kubernetes#80120]
(Originally based on #569)

cc @kubernetes/sig-cli-feature-requests

This feature request is to allow the `kubectl` tool to load configuration automatically from the `$HOME/.kube/config.d/` directory. This would allow configuration files to be broken down and structured in a more simple fashion, and allow users more organisation when managing many clusters.

## Design Document

The design document is at:

https://github.com/kubernetes/community/pull/3890

## Related Issues / Links

- [Design Document PR](https://github.com/kubernetes/community/pull/3890)
- [Feature Request: Support $HOME/.kube/config.d/*](https://github.com/kubernetes/kubectl/issues/569)
- #38791

## Other Notes

I have read the new contributor guidelines, setup my development environment, signed the contributor agreement and would be happy to develop the feature after connecting with the appropriate sig-cli members.

**Comment by dwmkerr** [comment]
@fejta any thoughts on this one? I opened up a discussion in slack but very little input so far.

**Comment by fejta** [comment]
Sounds fine to me, but I'm not a maintainer of kubectl. You'll need to get the attention of sig-cli

https://github.com/kubernetes/community/tree/master/sig-cli

**Comment by dwmkerr** [comment]
OK thanks!
