### ISSUE TITLE
[Failing Test] Scalability tests - cluster creation fails

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#80124]
**Which jobs are failing**:
All scalability ci-jobs

**Which test(s) are failing**:

**Since when has it been failing**:
07/12/2029 17:40 PDT

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100

**Reason for failure**:
cluster creation fails

**Anything else we need to know**:

**Comment by krzysied** [comment]
Also `make quick-release` fails, even for k8s checkouts from before 07/12/2029 17:40 PDT.
```
+++ [0713 16:07:57] Syncing sources to container
docker: Error response from daemon: driver failed programming external connectivity on endpoint kube-rsync-e792732d5c-5-v1.12.7-1 (4876779e453b6ffb3def367f4932b7b09d4c2a932b4a6a4278570640761657cf):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32953 -j DNAT --to-destination 192.168.9.2:8730 ! -i docker0: iptables v1.8.2 (nf_tables): Chain 'DOCKER' does not exist
 (exit status 1)).
!!! [0713 16:07:58] Call tree:
!!! [0713 16:07:58]  1: build/../build/common.sh:629 kube::build::run_build_command_ex(...)
!!! [0713 16:07:58]  2: build/../build/common.sh:685 kube::build::start_rsyncd_container(...)
!!! [0713 16:07:58]  3: build/../build/common.sh:436 kube::build::sync_to_container(...)
!!! [0713 16:07:58]  4: build/release.sh:35 kube::build::build_image(...)
Makefile:461: recipe for target 'quick-release' failed
```

**Comment by dims** [comment]
@krzysied i'd bet on this? https://github.com/kubernetes/kubernetes/pull/80047/files as the cause of the problem

given the errors i see from the https://paste.fedoraproject.org/paste/Qe2Vj5nNK-Q1yrbITzYNCA/raw (grep of logs from https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1150041374645555200/artifacts/e2e-big-master/)

**Comment by wojtek-t** [comment]
I bet it's something different - all GCE tests (not just scalability) are completely down in the last N hours.

I tried building stuff myself locally without rebasing (i.e. from commint from Thu) and it failed the same way.
It's some environmental thing (or test-infra issue).

**Comment by dims** [comment]
@wojtek-t @javier-b-perez we need to merge this to get back on our feet? https://github.com/kubernetes/kubernetes/pull/80054

**Comment by wojtek-t** [comment]
@dims - as I wrote above, I don't think the reason of it is related to any PR (at least in k/k repo).
I had exactly the same issue when trying to build on my workstation (from commit on Thursday which worked perfectly fine back then).
I restarted docker daemon and that fixed the problem (without any rebases, changes to code etc.) so I think that those problems aren't really related to any particular change.

**Comment by javier-b-perez** [comment]
if we are using "set -u" mode in the scripts, then the code in https://github.com/kubernetes/kubernetes/pull/80054/files will fail with something like:
line XX: local: manifest_name: readonly variable

This should only break GCE clusters. I working on a fix.

**Comment by dims** [comment]
@javier-b-perez please see https://github.com/kubernetes/kubernetes/pull/80141

**Comment by javier-b-perez** [comment]
> @javier-b-perez please see #80141

I saw it, thanks! Who can approve it?

**Comment by dims** [comment]
@krzysied https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100 is green again :)

/close
