### ISSUE TITLE
quay.io/fluentd_elasticsearch/elasticsearch:v7.1.1 doesnt exist

### ISSUE THREAD

**Issue by librannk** [kubernetes/kubernetes#80133]
for kubernetes\cluster\addons\fluentd-elasticsearch

quay.io/fluentd_elasticsearch/elasticsearch:v7.1.1 doesn't exist in quay, thereby giving error doesn't exist while pulling.

**Comment by librannk** [comment]
@kubernetes/sig-testing-test-failures

**Comment by monotek** [comment]
Sorry, guys!
Just uploaded it! :-)

https://quay.io/repository/fluentd_elasticsearch/elasticsearch?tab=tags

**Comment by librannk** [comment]
thanks for adding .....@monotek
