### ISSUE TITLE
Daemonset need more RollingUpdateStrategy

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#80130]
**What would you like to be added**:
/sig apps

**Why is this needed**:
Now we find Daemonset has a weak ability to do rollingUpdate.  So we need to do moere enhancement, such as pause, selector & and surge and more.

**Comment by draveness** [comment]
/assign

Do we need a KEP for this?

**Comment by zhangxiaoyu-zidif** [comment]
> /assign
> 
> Do we need a KEP for this?

yes, this KEP is ongoing. Welcome to join us.

**Comment by draveness** [comment]
> yes, this KEP is ongoing. Welcome to join us.

Thanks, I could work on this when the KEP becomes implementable.
