### ISSUE TITLE
events v1beta1: absence of optional `Related` event gives an error

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#80146]
Per the comments in v1beta1 Event:

https://github.com/kubernetes/kubernetes/blob/7285829b8306a7cc1a2dc0da943afcfe45c06579/staging/src/k8s.io/api/events/v1beta1/types.go#L61-L64

The `Related` field claimed to be optional, but an error is dumped if it's illegal - including the `nil` case:

https://github.com/kubernetes/kubernetes/blob/7285829b8306a7cc1a2dc0da943afcfe45c06579/staging/src/k8s.io/client-go/tools/events/event_recorder.go#L52-L55

This doesn't look right as it means the caller which passes in `nil` Related field will always get an err, for example, the scheduler binding event:

https://github.com/kubernetes/kubernetes/blob/7285829b8306a7cc1a2dc0da943afcfe45c06579/pkg/scheduler/scheduler.go#L440

If appropriate, I'm gonna raise a PR to tolerate the nil case. @yastij please advice.

**Comment by yastij** [comment]
/assign

I'll update the log to info or warning cc @wojtek-t

**Comment by wojtek-t** [comment]
It shouldn't be warning - it's a valid and allowed case.
I'm wondering if we even should be logging info, but maybe we can for now.
