### ISSUE TITLE
lookup ip from node name by NDS in kubelet node status setter take a long time, then controller-manager mark this node as `NotReady`

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#80154]
**What happened**:
kubelet periodically report node status including nodeIP to apiserver, it tries to get nodeIP in below order (you can find this logical at [here](https://github.com/kubernetes/kubernetes/blob/7285829b8306a7cc1a2dc0da943afcfe45c06579/pkg/kubelet/nodestatus/setters.go#L153-L192)):
1) Use nodeIP if set
2) If the user has specified an IP to HostnameOverride, use it
3) Lookup the IP from node name by DNS and use the first valid IPv4 address.
   If the node does not have a valid IPv4 address, use the first valid IPv6 address.
4) Try to get the IP from the network interface used as default gateway

At step 3, there are some corner cases will make getting nodeIP hang for a long time, even exceed the `node-monitor-grace-period` flag setting specified in controller-manager, then controller-manager will mark this node as `NotReady` state.   
these corner cases include but are not limited to below:
 1). dns server has some network failure
 2). node's `/etc/resolv.conf` has a long timeout value setting

here are some log from kubelet,  as you can see, setting node status at position 0 (which is setting nodeIP actually) take more than 20s
```shell
I0714 21:45:42.450816   27532 kubelet_node_status.go:503] Setting node status at position 0
... delete some unrelated messg.....
I0714 21:46:02.452322   27532 interface.go:384] Looking for default routes with IPv4 addresses
I0714 21:46:02.452326   27532 interface.go:389] Default route transits interface "ens33"
I0714 21:46:02.452629   27532 interface.go:196] Interface ens33 is up
I0714 21:46:02.452679   27532 interface.go:244] Interface "ens33" has 2 addresses :[172.16.152.137/24 fe80::e4b:cf31:c0f6:4d7f/64].
I0714 21:46:02.452687   27532 interface.go:211] Checking addr  172.16.152.137/24.
I0714 21:46:02.452690   27532 interface.go:218] IP found 172.16.152.137
I0714 21:46:02.452693   27532 interface.go:250] Found valid IPv4 address 172.16.152.137 for interface "ens33".
I0714 21:46:02.452696   27532 interface.go:395] Found active IP 172.16.152.137
I0714 21:46:02.452714   27532 kubelet_node_status.go:503] Setting node status at position 1
I0714 21:46:02.452735   27532 kubelet_node_status.go:503] Setting node status at position 2
I0714 21:46:02.453883   27532 kubelet_node_status.go:503] Setting node status at position 3
I0714 21:46:02.453886   27532 kubelet_node_status.go:503] Setting node status at position 4
I0714 21:46:02.453890   27532 kubelet_node_status.go:503] Setting node status at position 5
I0714 21:46:02.453891   27532 kubelet_node_status.go:503] Setting node status at position 6
I0714 21:46:02.453923   27532 kubelet_node_status.go:503] Setting node status at position 7

```

**What you expected to happen**:
add a context to invoke `net.LookupIP`and use this context timeout a DNS lookup, so that we can rollback to step 4 and kubelet will report it's status timely, then the node will stay healthy state.

**How to reproduce it (as minimally and precisely as possible)**:
1. set up a cluster
2. increase kubelet's logging level to 6 to debug, then add flag `--node-status-update-frequency=5s`
3. change controller-manager's `node-monitor-grace-period` flag to a smaller value intentionally to make it easily reproduce, such as `--node-monitor-grace-period=10s`
4. change one node's /etc/resolv.conf `nameserver` filed to a wrong ip to  simulate DNS server failuer
 5. dig into kubelet's log, you'll find log `Setting node status at position 0` takes a long time

**Anything else we need to know?**:
dns lookup timeout value is different depending on the host setting and language default value,  golong's default setting is `timeout * attempt count * length of DNS server list`,  timeout is 5s, attempt count is 2 by default, length of DNS server list is depending on your `/etc/reslov.conf`

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

not actually a bug, but indeed cause some failure, so mark as bug for now.
/kind bug
/sig node
/assign

**Comment by mattjmcnaughton** [comment]
Taking a look at your pr now! This is a _very_ detailed issue, thanks for doing such a great job filing :)
