### ISSUE TITLE
The etcd pod is always running after closing down node for a long time

### ISSUE THREAD

**Issue by Hughen** [kubernetes/kubernetes#80168]
**What happened**:
I have deployed a `v1.14.4` of the k8s cluster via kubeadm, with 3 masters, 3 etcd nodes, and the k8s cluster size of 5 nodes. As follow:
```text
node-1(master, etcd)
node-2(master, etcd)
node-3(master, etcd)
node-4(cluster worker)
node-5(cluster worker)
```
And then, the `node-2` is closed down for a long time, but `kubectl` outputs is running of the etcd pod status.
```bash
kubectl -n kube-system get pod etcd-node-2 -o wide
```
```text
NAME          READY   STATUS    RESTARTS   AGE     IP                NODE      NOMINATED NODE   READINESS GATES
etcd-node-2   1/1     Running   2          3h21m   192.168.200.202   node-2    <none>           <none>
```
And, the every node status:
```text
NAME      STATUS     ROLES    AGE     VERSION
node-1    Ready      master   3h29m   v1.14.4
node-2    NotReady   master   3h22m   v1.14.4
node-3    Ready      master   3h9m    v1.14.4
node-4    Ready      <none>   159m    v1.14.4
node-5    Ready      <none>   174m    v1.14.4
```

**What you expected to happen**:
All pods should be `unknown` or `error` instead of `running`

**Environment**:
- Kubernetes version (use `kubectl version`):
```text
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:51:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: not virtual machine
- OS (e.g: `cat /etc/os-release`):
```bash
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```text
Linux s01 4.19.58-041958-generic #201907100436 SMP Wed Jul 10 08:40:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug): `flannel v0.11.0`

/sig scalability

**Comment by neolit123** [comment]
/remove-sig scalability
/sig scheduling

> And then, the node-2 is closed down

by closed down, do you mean the node has shutdown?
i have no information why this is happening.

my guess is that if you do `kubectl delete` on that node the pod will be terminated.

**Comment by Hughen** [comment]
@neolit123 
Yeah, the `node-2` has been down for a long time.
Don't you think this is not in line with the scheduling rules? `Kubelet` knows that the `node-2` has been down, but it has not changed the status of the pod, which does not meet the scheduling principle.

If pods' status are changed by do `kubectl delete pod`, I won't believe that `k8s` can also implement automatic smooth scheduling for everything.

**Comment by neolit123** [comment]
> but it has not changed the status of the pod, which does not meet the scheduling principle.

indeed, something is not right here.

**Comment by Hughen** [comment]
So, is there any progress?
