### ISSUE TITLE
e2e: remove usage of the DeprecatedMightBeMasterNode function from the e2e testing framework

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#80177]
EDIT: the function was renamed to DeprecatedMightBeMasterNode, but the remove action is still pending.

instead of making assumptions that a node is "master" or not, we should make the choices more granular - e.g. can this node host workloads? we should remove usage of the function `IsMasterNode` from `e2e/framework`

see discussion here:
https://github.com/kubernetes/kubernetes/pull/80021#issuecomment-511507244

part of:
https://github.com/kubernetes/kubernetes/issues/75601

help wanted!

cc @andrewsykim @oomichi @alejandrox1 
/area e2e-test-framework
/sig testing
/kind cleanup

**Comment by BenTheElder** [comment]
cc

**Comment by neolit123** [comment]
> Should IsMasterNode be replaced with something?

that's the tricky part...
there is no sane way in kubernetes to tell if a node hosts a control plane or not.

which means that any calls to IsMasterNode have to be replaced with something that solves the underlying problem - for example are we calling IsMasterNode because we want to know if this node accepts workloads? or are we calling it to determine if there is a controller-manager on the node so that we can scrape metrics from it.

**Comment by oomichi** [comment]
@neolit123 
This issue seems interesting for me, because I am facing a conformance test issue which seems related to this on my local environment.
Even if a node is master, the node can host workload if the taint is removed from the node.
So do we want to use some function which checks a node is tainted instead of current  IsMasterNode()?

**Comment by oomichi** [comment]
Some investigation related to this issue:
Now all 7 callers of `IsMasterNode()` are
```
e2e/framework/metrics/metrics_grabber.go:               if system.IsMasterNode(node.Name) {
e2e/framework/metrics/latencies.go:             if system.IsMasterNode(node.Name) {
e2e/framework/resource_usage_gatherer.go:               if (options.Nodes == MasterNodes) && !system.IsMasterNode(pod.Spec.NodeName) {
e2e/framework/resource_usage_gatherer.go:               if (options.Nodes == MasterAndDNSNodes) && !system.IsMasterNode(pod.Spec.NodeName) && pod.Labels["k8s-app"] != "kube-dns" {
e2e/framework/resource_usage_gatherer.go:               if options.Nodes == AllNodes || system.IsMasterNode(node.Name) || dnsNodes[node.Name] {
e2e/framework/node/resource.go:         if system.IsMasterNode(n.Name) {
e2e/framework/node/wait.go:                     if !system.IsMasterNode(node.Name) {
```
1. `e2e/framework/metrics/metrics_grabber.go:               if system.IsMasterNode(node.Name) {`
This is for knowing a master node is registered or not for grabbing metrics.
So I think we can keep this code as current one because it is not related to workload.
2. `e2e/framework/metrics/latencies.go:             if system.IsMasterNode(node.Name) {`
The same as 1
3. `e2e/framework/resource_usage_gatherer.go:               if (options.Nodes == MasterNodes) && !system.IsMasterNode(pod.Spec.NodeName) {`

**Comment by neolit123** [comment]
> Even if a node is master, the node can host workload if the taint is removed from the node.
So do we want to use some function which checks a node is tainted instead of current IsMasterNode()?

in some cases yes.

system.IsMasterNode will be removed and the idea is not have a function in the framework (or k8s as a whole) that makes node-role assumptions based on node names or labels.

but quite frankly it think the usage of the function is bogus and outdated:
https://github.com/kubernetes/kubernetes/blob/d8695d06b7191db56ebbbc0340da263833c9bb6f/pkg/util/system/system_utils.go#L23-L37

e.g. kubeadm control-plane nodes don't have `master` in their names, unless the user name them like so, so this might or might not work for some bootstrappers or user setups, so by removing the function or changing the behavior of some of these tests we might as well break someone or at least change their expected test results...

**Comment by oomichi** [comment]
@neolit123 
> but quite frankly it think the usage of the function is bogus and outdated:

OMG, I never see the internal code of the function.
Yeah I agree with you here. The function seems fake according to the code.
Usually I am naming master node which include "master" but I didn't know the naming way is mandatory on this function..

**Comment by neolit123** [comment]
yeah, the function has to be removed, one way or another.
by making node name assumptions part of the tests may or may not work depending on the user setup.

**Comment by wongma7** [comment]
Here's the KEP (link to e2e specific part) https://github.com/kubernetes/enhancements/pull/1144/files#diff-55982acee19ca4466736d3b3c150218aR160

**Comment by erheron** [comment]
Hi! Would this issue be suitable for me as first-time contributor?
I will be happy to help with it, came because of "help wanted" label

**Comment by BenTheElder** [comment]
I think the issue may be to figure out what the correct replacement is. The code changes are probably not hard but knowing what they should be may be interesting and require buy in.

"good first issue" is used on issues that are targeting for first time contributors, "help wanted" has been a little more contentious :sweat_smile:

**Comment by oomichi** [comment]
Since a49a554211101f594e55e4b7d4574b535249db58 `IsMasterNode()` has been renamed to `DeprecatedMightBeMasterNode()`.
It is better to change the title for finding the problematic function easily.
(I faced it today ;-) )

**Comment by neolit123** [comment]
we have a retitle command :)
/retitle e2e: remove usage of the DeprecatedMightBeMasterNode function from the e2e testing framework

**Comment by oomichi** [comment]
Interesting, it is helpful command for me :-)

**Comment by ZhiFeng1993** [comment]
Can I take on this one?

**Comment by erheron** [comment]
> Can I take on this one?

No problem for me

**Comment by oomichi** [comment]
I am trying to reduce references of master nodes in those e2e tests as possible to solve this issue.

/assign @oomichi
