### ISSUE TITLE
Kubectl port forward drops the connections after 10 mins

### ISSUE THREAD

**Issue by ranjeetbath** [kubernetes/kubernetes#80171]
We are using Port Forward to forward DB2 connections to Nginx which is proxing to Cloud DB2.  What seems to happening is we are loosing the connection after about 10 mins even if DB2 query is still running (db2 update to a large table). We could also see the issue if we open a db2 connection and after 10 mins do some select statement. The connections seems to have dropped and we will need to reconnect.

**Comment by ranjeetbath** [comment]
sig/network

**Comment by ranjeetbath** [comment]
USER <> DB2 Client - PORT FORWARD on a linux server <> Nginx <> Db2 on CLlous

**Comment by ranjeetbath** [comment]
@kubernetes/sig-network-test-failures

**Comment by vllry** [comment]
Which cloud provider are you using?

**Comment by ranjeetbath** [comment]
@vllry , We are using IBM Cloud
