### ISSUE TITLE
Reuse FIFO code in DeltaFIFO

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#80178]
**What would you like to be added**:
DeltaFIFO can reuse some code from FIFO (through composition)

**Why is this needed**:
Currently there is some code duplication between DeltaFIFO and FIFO.
Here are some overlapping fields:
```
	queue []string
	keyFunc KeyFunc
	closed     bool
	closedLock sync.Mutex
```

**Comment by Moriadry** [comment]
@tedyu Hi ted, I would like to provide some strength on this issue. Would you mind if I give it a shot?

**Comment by tedyu** [comment]
Please go ahead.

You may want to outline your plan before going very deeply in refactoring.

**Comment by Moriadry** [comment]
Okay, sure!

This is my very start of k8s, so I am willing to discuss about the plan deeply. If you don't mind :)

**Comment by liggitt** [comment]
are the uses and meaning of those fields identical between those types? if not, I'd avoid nesting FIFO within DeltaFIFO

**Comment by deads2k** [comment]
The intent of these types is different and embedding one within another will create unexpected cross dependencies and usage.  We should not combine different ideas based on similar field names.

/close
