### ISSUE TITLE
CI image tarballs include wrong repository

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#80184]
related to:
https://github.com/kubernetes/kubernetes/pull/80047

discussion on slack;
https://kubernetes.slack.com/archives/CEKK1KTN2/p1563193786381200

steps to reproduce:
```
wget https://storage.googleapis.com/kubernetes-release-dev/ci/v1.16.0-alpha.0.2264+12f36302f9ee98/bin/linux/amd64/kube-proxy.tar
```

open the `repositories` file in the tarball.

it has:
```
{"k8s.gcr.io/kube-proxy-amd64":{"v1.16.0-alpha.0.2264_12f36302f9ee98":"d9e459d06c6c2d2376c11b58a62138768a2d9a4fcc3aaf43917cff4728544b1e"}}
```

should be:
```
{"gcr.io/kubernetes-ci-images/kube-proxy-amd64":{"v1.16.0-alpha.0.2264_12f36302f9ee98":"d9e459d06c6c2d2376c11b58a62138768a2d9a4fcc3aaf43917cff4728544b1e"}}
```

/assign @javier-b-perez 
cc @BenTheElder @cblecker @justaugustus @fabriziopandini 
/sig release testing
/kind bug
/priority important-soon

**Comment by javier-b-perez** [comment]
when you do the build (make quick-release or release) you need to specify the KUBE_DOCKER_REGISTRY and KUBE_DOCKER_IMAGE_TAG. Example:

KUBE_DOCKER_IMAGE_TAG=v1.13.9-beta.0.59_c00becd203d4ea
KUBE_DOCKER_REGISTRY=gcr.io/my-project

manifest.json:
"RepoTags":["k8s.gcr.io/kube-proxy:v1.13.9-beta.0.59_c00becd203d4ea","gcr.io/my-project/kube-proxy-amd64:v1.13.9-beta.0.59_c00becd203d4ea"]

**Comment by javier-b-perez** [comment]
The only issue that I have right now, is that you cannot leave KUBE_DOCKER_IMAGE_TAG.
I will send a fix for that. If empty it should use the same docker tag as the k8s.gcr.io name.

**Comment by BenTheElder** [comment]
I would generally expect k8s.gcr.io/* to at least be one of the tags unless overridden.

**Comment by javier-b-perez** [comment]
yes, k8s.gcr.io/* name will always be there. KUBE_DOCKER_REGISTRY is to add an additional name to the image achive

**Comment by neolit123** [comment]
> yes, k8s.gcr.io/* name will always be there. 

Q: would that mean that if you do `docker load` on the image tarball it will create a couple of image tags pointing to the same image SHA?

**Comment by javier-b-perez** [comment]
> > yes, k8s.gcr.io/* name will always be there.
> 
> Q: would that mean that if you do `docker load` on the image tarball it will create a couple of image tags pointing to the same image ID?

yes

**Comment by neolit123** [comment]
it still feels odd to me that one of the `repo/image:tag` locations will be technically invalid as this image only exists in the CI location. but no strong opinions on my side.

**Comment by BenTheElder** [comment]
> it still feels odd to me that one of the repo/image:tag locations will be technically invalid as this image only exists in the CI location. but no strong opinions on my side.

this is going to be true regardless for any image any time you build and image locally and don't push it.
(including say, building a kind node image ...)

**Comment by neolit123** [comment]
/close
should be resolved at this point.
