### ISSUE TITLE
Add IPv6 support to agnhost image

### ISSUE THREAD

**Issue by saiyan86** [kubernetes/kubernetes#80198]
**What would you like to be added**:

Add IPv6 support to ```agnhost``` image.

**Why is this needed**:

For testing we need to include IPv6, which is becoming more and more important. IPv4/v6 dualstack PR #73977 just got merged, and we should support IPv6 in ```agnhost``` image too.

PR #77794 also needs IPv6 support.

**Comment by BenTheElder** [comment]
cc @aojea

**Comment by aojea** [comment]
@saiyan86 what IPv6 utility are you missing from `agnhost` ? 
It has installed `apk --update add curl netcat-openbsd iproute2 iperf` that works with IPv6 too

**Comment by saiyan86** [comment]
> @saiyan86 what IPv6 utility are you missing from `agnhost` ?
> It has installed `apk --update add curl netcat-openbsd iproute2 iperf` that works with IPv6 too

```runner``` doesn't support ipv6. But as you suggested, we can use ```nc``` for ipv6 for network connectivity tests.

**Comment by aojea** [comment]
yeah, it also has a `connect` function, you have an example here https://github.com/kubernetes/kubernetes/blob/9aefaa163f9a8a397de20f4acd41aa25658e9133/test/e2e/network/service.go#L1873

**Comment by aojea** [comment]
@saiyan86 should we close this?

**Comment by saiyan86** [comment]
> @saiyan86 should we close this?

Yes, I just closed it. Thanks!
