### ISSUE TITLE
Upgrade agnhost image to add build-tools

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#80194]
**What would you like to be added**:
Add `build-tools` package to include `dig` (+nslookup) tool in Agnhost image.

**Why is this needed**:
`dig` is important tool used in most of the network testing suite.
[Issue Source]: https://github.com/kubernetes/kubernetes/pull/79667#discussion_r303560200

/area conformance
/sig testing
/assign @bclau

**Comment by mgdevstack** [comment]
Seems `bind-tools-9.11.6_p1-r1` already exist in agnhost:2.4.

**Comment by mgdevstack** [comment]
https://github.com/kubernetes/kubernetes/pull/79667#discussion_r303732059
E2E failing with `dig` is not found.

**Comment by bclau** [comment]
Do we still need this? I could add this if needed.

**Comment by mgdevstack** [comment]
Yes, we are looking to use `dig` for most of the network testing aspects and having it in agnhost is very useful.

**Comment by mgdevstack** [comment]
#81170 supposed to fix this issue. (based on #81170 PR description)
/open

**Comment by bclau** [comment]
> 
> 
> #81170 supposed to fix this issue. (based on #81170 PR description)
> /open

PR https://github.com/kubernetes/kubernetes/pull/81008 was also included in #81170, but #81008 already merged, but ``agnhost:2.5`` has not been built and pushed as it should.
