### ISSUE TITLE
Support rerun of Job on update

### ISSUE THREAD

**Issue by msvticket** [kubernetes/kubernetes#80207]
**What would you like to be added**:
Support for having a job being rerun on change of spec.template.  Something like a new field `updatePolicy` that defaults to the current behaviour with a value like `reject` and another value `rerun` for the new behaviour.

**Why is this needed**:
With a declarative approach for managing a k8s resources (using helm for example) the current workflow for handling jobs that need an update to their behaviour is getting cumbersome.

Since jobs can fail for various reasons and then are rerun by the Job controller (if restartPolicy is OnFailure) they already need to be idempotent. So it would be natural to let a job be rerun if updated with for example a new image. Instead now you get an error like:

    The Job "..." is invalid: spec.template: Invalid value: core.PodTemplateSpec{...}: field is immutable': exit status 1

**Comment by msvticket** [comment]
@kubernetes/sig-apps-workloads-api

**Comment by msvticket** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by msvticket** [comment]
It would probably make sense to also support the value `ignore` on `updatePolicy`.

**Comment by soltysh** [comment]
This is the how jobs where designed to work, so I don't think this is going to be changed. Also you can always get a job and re-create it with a new name. Alternatively create a kubectl plugin to do that for you. 
/close
