### ISSUE TITLE
[CSI] add support block volume when expand volume 

### ISSUE THREAD

**Issue by GongWilliam** [kubernetes/kubernetes#80208]
hello, I found a problem that I think maybe need to be solved。

problem:
when mount a volume with block device form and need to call NodeExpandVolume RPC(because want to reflesh the block device info, e.g. iscsi lun), the response have to set  NodeExpansionRequired to true. So the resizer sidecar will set PVC type to PersistentVolumeClaimFileSystemResizePending, this means need to restart the pod.
And after restart pod, you will find the pvc is still not resize.
I look into the k8s source code found that kubernetes will not do the resize work when call MountVolume function with block device form, but it will do the resize work with filesystem form.

so, how to solve this problem?

**Comment by davidz627** [comment]
is this issue related: https://github.com/kubernetes/kubernetes/issues/79990

**Comment by davidz627** [comment]
Looks like this has been resolved by the linked issue: #79990, feel free to reopen if that is not the case
/close
