### ISSUE TITLE
[Failing Test] k8s 1.13 pull-kubernetes-verify#godeps failed

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#80204]
**Which jobs are failing**:

 pull-kubernetes-verify

**Which test(s) are failing**:

godeps

**Since when has it been failing**:

when I cherry picked this PR  a k8s 1.13, I found this Issue
https://github.com/kubernetes/kubernetes/pull/80197

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80197/pull-kubernetes-verify/1151003608582459392/

**Reason for failure**:

**Anything else we need to know**:

I have not found this issue in k8s 1.14 k8s1.15, and godeps verification has not been triggered.

**Comment by cwdsuzhou** [comment]
someone has fixed it

**Comment by spiffxp** [comment]
FYI @kubernetes/dep-approvers 

I'm seeing this across a few verify jobs against release-1.13

eg: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80268/pull-kubernetes-verify/1151855637198540803/
```
Your Godeps.json is different:
--- Godeps/Godeps.json	2019-07-18 14:07:01.894620213 +0000
+++ /tmp/gopath.GAa1TL/src/k8s.io/kubernetes/Godeps/Godeps.json	2019-07-18 14:50:14.597334737 +0000
@@ -2983,7 +2983,7 @@
 		},
 		{
 			"ImportPath": "github.com/robfig/cron",
-			"Comment": "v1-53-gdf38d32658d878",
+			"Comment": "v1.0.0-53-gdf38d32658d878",
 			"Rev": "df38d32658d8788cd446ba74db4bb5375c4b0cb3"
 		},
```

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/pull/80559 should fix it

**Comment by spiffxp** [comment]
/close
Yeah I see it passed against https://github.com/kubernetes/kubernetes/pull/80326

Thanks for the fix @jfbai!
