### ISSUE TITLE
Kubelet: cpu manager use the part of cpus

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubernetes#80205]
I use the Kubernetes version `v1.11.6`, and i enable the cpu manager policy to `static`, i change the kubelet config file, and restart the kubelet, it works well. Now i want to set the container only use the part of cpus, but i find the cpu manager also use the all cpus on the node, so i want to how to do in my case? Is the Kubernetes can support this case?

**Comment by moshe010** [comment]
Are you requesting cpu in the pod spec?  
adding the lines below will request 2 cpus for the pod
resources:
      requests:
        cpu: 2
      limits:
        cpu: 2

**Comment by pytimer** [comment]
> Are you requesting cpu in the pod spec?

No, i have two case about this issue.

One, allocate exclusive CPUs to the pod containers. I read the [Control CPU Management Policies on the Node](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) document and try it in my Kubernetes cluster, it works.

Two, the cpu manager use all the node cpusets, but i want the cpu manager only use the part of cpus, not all, because my node have other non-container applications.

The second case i don't know how to do.

**Comment by moshe010** [comment]
so you can use the --system-reserved=cpu=<num of cpus to reserve> in kubelet to do that.  For example --system-reserved=cpu=4 will reserve 4 cpus

**Comment by pytimer** [comment]
I set the `--system-reserved` is 2000m, it reserve 2 cpus. How to do it if i want to use cpus like `0-1,3`?

**Comment by moshe010** [comment]
according to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/policy_static.go#L51-L56 Reserved CPUs are taken topologically starting with lowest-indexed physical core. So this need to be extended if you want spacify what cpus to reserve

**Comment by pytimer** [comment]
You mean if i want specify what cpus to reserve, i should modify the kubelet code about cpu manager, is it?

**Comment by moshe010** [comment]
Yes,  selecting specific cpus are not supported so you need to modify the code to support that

**Comment by pytimer** [comment]
Thanks, I know.
