### ISSUE TITLE
access by pods hostanme

### ISSUE THREAD

**Issue by kapil70war** [kubernetes/kubernetes#80210]
Hi,@kubernetes/sig-Network-network
@kubernetes/sig-policy-network

Is there a way to access a pod by its hostname?
I have a pod with hostname my-pod-1 that need to connect to another pod
my-pod-2

what is the best way to achieve this with out services?

**Comment by neolit123** [comment]
hi, you are probably going to get better response if you post this question on slack/stack-overflow/reddit.

/triage support
/close
