### ISSUE TITLE
Performance regression(s) in ci-kubernetes-e2e-gci-gce-scalability 

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#80212]
**Which jobs are failing**: ci-kubernetes-e2e-gci-gce-scalability

**Which test(s) are failing**: Density test

**Since when has it been failing**: First observed failure was on 2019-07-12 09:02:59 +0000 UTC

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100

**Reason for failure**: resource usage constraints are violated (flaky)

/sig scalability
/assign

**Comment by mm4tt** [comment]
Looking at the scheduler cpu usage it's definitely became more spiky. The first failure occurred at 2019-07-12, but there were no changes in scheduler code around that time.

![W9woh9v26hC](https://user-images.githubusercontent.com/2604887/61290964-6b30b800-a7cd-11e9-87da-965696167048.png)

Golang version was updated on 2019-07-12, from v1.12.6-1 to v1.12.7-1, this might be related.

**Comment by wojtek-t** [comment]
Does the increase correlate with this PR: https://github.com/kubernetes/kubernetes/pull/78447 ?

@yastij - FYI

**Comment by mm4tt** [comment]
Hard to say, the first failure occurred before the PR was merged.
Also it started failing more often on Jul 15th, it might be that the failure on Jul 12th was a flake and the actual issue started on Jul 15th.

**Comment by yastij** [comment]
@wojtek-t - it might be #78447 as it was merged on the 12th IIRC

**Comment by mm4tt** [comment]
Summarizing what I've found so far:

There are two issues here
  1. Increased cpu usage of some components (mostly scheduler, sometimes api-server)
  2. Prometheus version of API Responsiveness sometimes fails for a lot of calls, e.g.
      ```
      [measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheus error: top latency metric: there should be no high-latency requests, but: [got: {Resource:configmaps Subresource: Verb:POST Scope:namespace Latency:perc50: 25ms, perc90: 45ms, perc99: 1m0s Count:72}; expected perc99 <= 1s got: {Resource:configmaps Subresource: Verb:LIST Scope:namespace Latency:perc50: 25ms, perc90: 45ms, perc99: 1m0s Count:39}; expected perc99 <= 5s got: {Resource:configmaps Subresource: Verb:LIST Scope:cluster Latency:perc50: 25ms, perc90: 45ms, perc99: 1m0s Count:2}; expected perc99 <= 10s got: {Resource:endpoints Subresource: Verb:LIST Scope:namespace Latency:perc50: 25ms, perc90: 45ms, perc99: 1m0s Count:39}; expected perc99 <= 5s got: {Resource:namespaces Subresource: Verb:LIST Scope:cluster Latency:perc50: 25ms, perc90: 45ms, perc99: 1m0s Count:36}; expected perc99 <= 10s got: {Resource:namespaces Subresource: Verb:GET Scope:cluster Latency:perc50: 25ms, perc90: 45ms, perc99: 1m0s Count:171}; expected perc99 <= 1s got: {Resource:pods Subresource: Verb:LIST Scope:namespace Latency:perc50: 35ms, perc90: 194.999999ms, perc99: 1m0s Count:1052}; expected perc99 <= 5s got: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:perc50: 25.489588ms, perc90: 45.881259ms, perc99: 43.8224775s Count:4064}; expected perc99 <= 1s got: {Resource:persistentvolumes Subresource: Verb:GET Scope:cluster Latency:perc50: 25ms, perc90: 45ms, perc99: 43.813365s Count:14}; expected perc99 <= 1s got: {Resource:persistentvolumes Subresource: Verb:LIST Scope:cluster Latency:perc50: 25ms, perc90: 45ms, perc99: 43.813365s Count:36}; expected perc99 <= 10s got: {Resource:persistentvolumeclaims Subresource: Verb:GET Scope:namespace Latency:perc50: 25ms, perc90: 45ms, perc99: 43.813365s Count:14}; expected perc99 <= 1s got: {Resource:persistentvolumeclaims Subresource: Verb:LIST Scope:namespace Latency:perc50: 25ms, perc90: 45ms, perc99: 43.813365s Count:36}; expected perc99 <= 5s]]
      ```
      or
      ```
      [measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheus error: top latency metric: there should be no high-latency requests, but: [got: {Resource:deployments Subresource: Verb:LIST Scope:cluster Latency:perc50: 175ms, perc90: 195ms, perc99: 54.617955s Count:3}; expected perc99 <= 10s got: {Resource:deployments Subresource: Verb:GET Scope:namespace Latency:perc50: 27.474115ms, perc90: 49.453407ms, perc99: 54.613307142s Count:412}; expected perc99 <= 1s got: {Resource:replicasets Subresource: Verb:LIST Scope:namespace Latency:perc50: 27.777777ms, perc90: 95.5ms, perc99: 54.61305s Count:20}; expected perc99 <= 5s got: {Resource:deployments Subresource: Verb:POST Scope:namespace Latency:perc50: 27.890399ms, perc90: 52.566355ms, perc99: 54.61242s Count:331}; expected perc99 <= 1s]]
      ```

Regarding 1, the mitigation has been already put in place, the threshold has been temporary raised. I'm still far from pinpointing the culprit, but have some new findings, which I will share shortly. 

Regarding 2, the Prometheus violations has been enabled recently (https://github.com/kubernetes/test-infra/pull/13347). I believe we should rollback it (to mitigate and deflake this release-blocking test) and investigate why there are violations reported by Prometheus measurement, but not by the old version of the measurement. Given that the test takes below 5h there shouldn't be that big difference. The investigation should be part of the https://github.com/kubernetes/perf-tests/issues/498 issue

**Comment by mm4tt** [comment]
Regarding 1, I found that there are more symptoms than just increased scheduler cpu usage.
Around that time, other things started to happen, e.g.

Scheduler binding latency went up:
![EsZT5dm8BEc](https://user-images.githubusercontent.com/2604887/61366573-1dc65080-a88a-11e9-9f14-e00354dc3b5e.png)

Api Call Latency of POST pods/binding went up:
![0CQibnW4cBP](https://user-images.githubusercontent.com/2604887/61366633-40586980-a88a-11e9-8cbf-e2af5558d753.png)

It all started on Jul 12th, so luckily we can exclude golang version update.

There is one change that correlates in time with all these symptoms. It's enabling node-exporter on master in this test. It may be related, i.e. node-exporter monitors network, it's possible that in order to do so it acquires some lock which slows down network for a short period of time. That would explain slower api calls, which in turn could explain scheduler CPU to go up (longer requests -> more requests in parallel -> more cpu usage).
I'll try disabling node-exporter to see if it helps.

**Comment by mm4tt** [comment]
Unfortunately, the node-exporter turned out to be a red herring. Some graphs showing that

1. Node-exporter was disabled
![dmEC2PwJa6f](https://user-images.githubusercontent.com/2604887/61443472-dd2e0c00-a949-11e9-8829-328d50d61c7c.png)

2. Apiserver pod/binding post latency is still up
![KoWp3ykNZA1](https://user-images.githubusercontent.com/2604887/61443546-ffc02500-a949-11e9-93b1-7dc2018ef646.png)

3. Scheduler binding latency is still up
![dLexNkDUNvP](https://user-images.githubusercontent.com/2604887/61443507-ee771880-a949-11e9-96c0-e0fedd9e7358.png)

4. Scheduler CPU still records higher spikes than it used to
![7L8M3LZjfTf](https://user-images.githubusercontent.com/2604887/61443621-29794c00-a94a-11e9-89c3-550f6cf5fe97.png)

I'll revert the PR that disabled node-exporter, there is no correlation.

So we're back to the beginning. At this point the only thing that comes to my mind, that can help, is to enable prometheus snapshots in gce-100 test. With prometheus snapshot and grafana dashboards we might be able to get more insights and data about this issue, e.g. is there a particular moment when scheduler CPU spikes up?

**Comment by mm4tt** [comment]
I compared prometheus data from two runs, one that reported ~0.5 scheduler CPU and other that reported ~0.1 scheduler CPU. To my surprise, they are basically identical... :)

**0.5 CPU run**
![NEmaj7RYPL2](https://user-images.githubusercontent.com/2604887/61871435-1da8ff00-aee1-11e9-8b77-af0b2e6e6419.png)

**0.1 CPU run**
![Z9OzfArWkgE](https://user-images.githubusercontent.com/2604887/61871437-1e419580-aee1-11e9-9524-b9585404919e.png)

I checked the code and the CPU flakiness comes from the way we calculate resource usage. For short tests (like gce-100 density that takes ~10-20 minutes) we have only 4 cpu measurements. In such case the 99th and 90th percentiles are basically max that we measured. Each density test has an initial scheduler spike, where we schedule 3K pods in ~30s. If we hit this spike with one of the measurements the test will report ~0.5 CPU usage, if we don't hit it, it will report ~0.1 CPU usage. 

We need to fix that and figure out a better way for measuring resource usage.

**Comment by mm4tt** [comment]
And regarding two other symptoms described in https://github.com/kubernetes/kubernetes/issues/80212#issuecomment-512188450, I believe they are totally unrelated to scheduler CPU consumption. They are most likely connected, but this is a separate regression.

**Comment by mm4tt** [comment]
The resource usage issues were fixed in https://github.com/kubernetes/perf-tests/issues/694
I'm closing this one, while there was some increase in api-call-latency for some requests it was really minor and still well withing scalability SLOs. It was visible only in 100 node clusters and didn't affect any bigger clusters. What's more we don't have logs for these runs anymore, so debugging it would be hard.
While it would be good to understand it, we have more important things to work on right now. 

/close
