### ISSUE TITLE
why --delete-local-data

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#80228]
When draining a node, it complains about any pods that utilize an emptyDir volume, asking you to specify --delete-local-data to override. emptyDir is no different in lifecycle then the containers themselves, so why require a flag for emptyDir containing pods and not just all pods?

I think we should not need --delete-local-data for emptyDir pods.

**Comment by kfox1111** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by BenTheElder** [comment]
@msau42 WDYT?

**Comment by kfox1111** [comment]
Without --delete-local-data, it gives a scary warning. But if the flag only ever talks about emptyDir, and thats only as scary as deleting regular pods without emptyDirs, then alternately, maybe the flag should be --delete-emptydir-data. That would be at least somewhat less scary then --delete-local-data, which kind of looks like it might delete local pv's (also a form of local data you never want deleted). I'd still prefer it to not even ask, as it really is no different then just having a container store the data though.

**Comment by msau42** [comment]
I agree we shouldn't need an override to delete emptyDir volumes because the expectation is that emptyDir volumes are ephemeral.

However, the reason we have the flag now is due to backwards compatibility and users potentially depending on this behavior now.

**Comment by BenTheElder** [comment]
Thanks @msau42 -- If the only reason is backwards compatibility, we could begin to deprecate the flag and start the (slow) timer to remove it?

**Comment by kfox1111** [comment]
What needs to be done to deprecate?

**Comment by msau42** [comment]
I would suggest to bring this up at sig-cli

**Comment by kfox1111** [comment]
In general, a good plan. But my time is unfortunately rather constrained at the moment and I'm being asked to bring things up to more and more sig's. Anyone else that could bring up the issue in that forum?

**Comment by BenTheElder** [comment]
It shouldn't be too involved to mention it in a slack channel or mailinglist, versus this issue tracker being stuffed with >2000 open issues 🙃 
I've just brought this up, but in general if nobody has even been up for doing that much it seems unlikely to get resolved...

**Comment by willzhang** [comment]
what local date it is ,it's not clear, so when i run this command ,it make me nervous.

**Comment by kfox1111** [comment]
Still relevant.

/remove-lifecycle stale

**Comment by kfox1111** [comment]
Still relevant.

/remove-lifecycle stale

Had to explain this to another user the other day.

**Comment by msau42** [comment]
Please bring this up with sig-cli to find an owner for this

**Comment by pwittrock** [comment]
Rather than changing the behavior which some folks could be depending upon, WDYT of:

- Rename the flag (deprecate old and create a new) to `--delete-emptydir-data`
- Introduce a short name for the flag so users don't have to type as much `-d`

**Comment by dougsland** [comment]
let me try to help here.

**Comment by kfox1111** [comment]
--delete-emptydir-data would be far less scary.

**Comment by eddiezane** [comment]
Closed via https://github.com/kubernetes/kubernetes/pull/95076

/close
