### ISSUE TITLE
Simplify bind extension point integration tests

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#80227]
**What would you like to be added**:
The [integration test for the scheduler framework bind extension point](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/framework_test.go#L676) is very complex and I should be simplified.

**Why is this needed**:
Tests should be simple to reason about, and also to avoid flakes.

/sig scheduling
/kind cleanup

**Comment by congliu01** [comment]
I'd like to take a look at this.

**Comment by ahg-g** [comment]
Bind plugin is flaky: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80305/pull-kubernetes-integration/1151863322098798593/

**Comment by chenchun** [comment]
I think the racy comes from calling recordSchedulingFailure in case of bind failure before running unreserve plugin. The test is not flaky and it proves we should move recordSchedulingFailure after calling unreserve plugin just like what it does in https://github.com/kubernetes/kubernetes/pull/79639.
If we don't do that, a plugin which is registered as reserve + bind + unreserve plugin will have a chance to be called bind twice without cleaning its last state from unreserve phase.
