### ISSUE TITLE
API server etcd preflight check all member belongs to the same cluster

### ISSUE THREAD

**Issue by ricky1993** [kubernetes/kubernetes#80244]
**What would you like to be added**:
API server etcd preflight check all member belongs to the same cluster
**Why is this needed**:
Here is the story:
We find a etcd member abnormal and remove it from cluster, but we forget to remove it from apiserver options.
After one day, we fix the etcd server, and it restart for a new cluster.
Unfortunately, we restart apiserver and it writes part of data to the new etcd cluster.
If we have this feature, we can avoid this tragedy.

**Comment by liggitt** [comment]
Using distinct client credentials for each etcd cluster would prevent that. Checking all members would require all members to be available for an API server to start, which would impact availability

**Comment by yue9944882** [comment]
sounds more like brain-splitting the guy's talking about

**Comment by ricky1993** [comment]
> Using distinct client credentials for each etcd cluster would prevent that. Checking all members would require all members to be available for an API server to start, which would impact availability

How about just checking the living member? It would not impact availability and provide more safety.

**Comment by ricky1993** [comment]
> sounds more like brain-splitting the guy's talking about

I think it is misconfigured. If the apiserver connect to two different etcd cluster would cause that.

**Comment by ricky1993** [comment]
> Using distinct client credentials for each etcd cluster would prevent that.

Of course we have used different credentials for each etcd cluster, but in the story, the etcd server was start up with the original credential and empty-data as a new cluster unexpectedly (The original plan is restart it and add it to the original cluster).

**Comment by ricky1993** [comment]
> > Checking all members would require all members to be available for an API server to start, which would impact availability
> 
> How about just checking the living member? It would not impact availability and provide more safety.

Maybe we can check: uniq count cluster id == 1

**Comment by roycaihw** [comment]
cc @jpbetz @wenjiaswe @jingyih

**Comment by jpbetz** [comment]
I thought about this a bit. While I agree the failure mode is bad, I don't think we should put a check directly in Kubernetes. As mentioned in https://github.com/kubernetes/kubernetes/issues/80244#issuecomment-512619744, client creds can already be used to defend against this. We need to test and maintain anything we put into Kubernetes, and I'm not convinced there is a check that offers sufficient value that couldn't be better achieved in other ways.

FWIW, more details on how etcd become misconfigured would be valuable to discuss with the etcd community. maybe we can identify improvements to etcd to prevent this type of mis-configuration in the first place.

**Comment by ricky1993** [comment]
>  I don't think we should put a check directly in Kubernetes. 
So where is the best place to put these checks. I find preflight check haven't change for years. It's really confuse me.

> and I'm not convinced there is a check that offers sufficient value that couldn't be better achieved in other ways.
Do you mean we should put the check in setup/ops tools (like kubeadm)? I am not sure I totally get your points.

> maybe we can identify improvements to etcd to prevent this type of mis-configuration in the first place.
I think the configuration is legal for etcd (two different etcd clusters cannot perceive each other), because it's a mis-configuration for apiserver, it tries to connect two different etcd clusters.
