### ISSUE TITLE
kubectl get sources too slow

### ISSUE THREAD

**Issue by kong62** [kubernetes/kubernetes#80245]
version: v1.14.2
kubeadm: v1.14.2

First time:
kubectl get nodes -v=10
...
I0717 16:14:48.181289 2723522 request.go:942] Response Body: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"scheduling.k8s.io/v1beta1","resources":[{"name":"priorityclasses","singularName":"","namespaced":false,"kind":"PriorityClass","verbs":["create","delete","deletecollection","get","list","patch","update","watch"],"shortNames":["pc"]}]}
I0717 16:14:48.187025 2723522 request.go:942] Response Body: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"coordination.k8s.io/v1","resources":[{"name":"leases","singularName":"","namespaced":true,"kind":"Lease","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]}]}

I0717 16:15:02.863401 2723522 round_trippers.go:438] GET https://10.64.57.201:8443/apis/metrics.k8s.io/v1beta1?timeout=32s  in 15025 milliseconds

I0717 16:15:02.863461 2723522 round_trippers.go:444] Response Headers:
I0717 16:15:02.863567 2723522 cached_discovery.go:78] skipped caching discovery info due to Get https://10.64.57.201:8443/apis/metrics.k8s.io/v1beta1?timeout=32s: unexpected EOF
I0717 16:15:02.864847 2723522 cached_discovery.go:114] returning cached discovery info from /root/.kube/cache/discovery/10.64.57.201_8443/servergroups.json
I0717 16:15:02.865153 2723522 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.14.2 (linux/amd64) kubernetes/66049e3" 'https://10.64.57.201:8443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I0717 16:15:02.866621 2723522 cached_discovery.go:71] returning cached discovery info from /root/.kube/cache/discovery/10.64.57.201_8443/certificates.k8s.io/v1beta1/serverresources.json
..
NAME          STATUS   ROLES    AGE   VERSION
sit-test-39   Ready    master   43d   v1.14.2
sit-test-40   Ready    <none>   43d   v1.14.2
sit-test-41   Ready    <none>   43d   v1.14.2
sit-test-42   Ready    <none>   43d   v1.14.2
sit-test-43   Ready    <none>   43d   v1.14.2
sit-test-44   Ready    <none>   43d   v1.14.2
sit-test-45   Ready    master   43d   v1.14.2
sit-test-46   Ready    <none>   43d   v1.14.2
sit-test-47   Ready    master   43d   v1.14.2
sit-test-48   Ready    <none>   43d   v1.14.2
sit-test-49   Ready    <none>   43d   v1.14.2

real    0m15.454s
user    0m0.276s
sys     0m0.085s

second time:
NAME          STATUS   ROLES    AGE   VERSION
sit-test-39   Ready    master   43d   v1.14.2
sit-test-40   Ready    <none>   43d   v1.14.2
sit-test-41   Ready    <none>   43d   v1.14.2
sit-test-42   Ready    <none>   43d   v1.14.2
sit-test-43   Ready    <none>   43d   v1.14.2
sit-test-44   Ready    <none>   43d   v1.14.2
sit-test-45   Ready    master   43d   v1.14.2
sit-test-46   Ready    <none>   43d   v1.14.2
sit-test-47   Ready    master   43d   v1.14.2
sit-test-48   Ready    <none>   43d   v1.14.2
sit-test-49   Ready    <none>   43d   v1.14.2

real    0m0.283s
user    0m0.214s
sys     0m0.024s

wait for a long time after
first time:
NAME          STATUS   ROLES    AGE   VERSION
sit-test-39   Ready    master   43d   v1.14.2
sit-test-40   Ready    <none>   43d   v1.14.2
sit-test-41   Ready    <none>   43d   v1.14.2
sit-test-42   Ready    <none>   43d   v1.14.2
sit-test-43   Ready    <none>   43d   v1.14.2
sit-test-44   Ready    <none>   43d   v1.14.2
sit-test-45   Ready    master   43d   v1.14.2
sit-test-46   Ready    <none>   43d   v1.14.2
sit-test-47   Ready    master   43d   v1.14.2
sit-test-48   Ready    <none>   43d   v1.14.2
sit-test-49   Ready    <none>   43d   v1.14.2

real    0m15.454s
user    0m0.276s
sys     0m0.085s

second time:
NAME          STATUS   ROLES    AGE   VERSION
sit-test-39   Ready    master   43d   v1.14.2
sit-test-40   Ready    <none>   43d   v1.14.2
sit-test-41   Ready    <none>   43d   v1.14.2
sit-test-42   Ready    <none>   43d   v1.14.2
sit-test-43   Ready    <none>   43d   v1.14.2
sit-test-44   Ready    <none>   43d   v1.14.2
sit-test-45   Ready    master   43d   v1.14.2
sit-test-46   Ready    <none>   43d   v1.14.2
sit-test-47   Ready    master   43d   v1.14.2
sit-test-48   Ready    <none>   43d   v1.14.2
sit-test-49   Ready    <none>   43d   v1.14.2

real    0m0.244s
user    0m0.198s
sys     0m0.023s

**Comment by kong62** [comment]
solved!
 kubectl delete pod metrics-server-6c66b78c97-lt9ph -n kube-system

**Comment by kong62** [comment]
kubectl delete pod metrics-server-6c66b78c97-lt9ph -n kube-system

**Comment by xieyanker** [comment]
@kong62 Hello, I meet a same issue, such as `kubectl get node` slowly, and the pod ` metrics-server` exists in my cluster. I try to delete the deployment of it, but no help to me. I want to kown why it worked for you when you deleted the pod `metrics-server-6c66b78c97-lt9ph`.

**Comment by kong62** [comment]
@xieyanker One time it was caused by a calico network problem，when network good，solved
