### ISSUE TITLE
NVMe AWS EBS volumes with partitions can't be mounted

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#80251]
**What happened**:
Checking `getDiskByIDPaths` for an unrelated bug I discovered that AWS volume plugin does not really support partitions on NVMe volumes. When `awsElasticBlockStore.partition` is set to say "1", these two cases can happen:

1. `devicePath` is set (e.g. from node.status). The function just appends partition number ("1") to it:
https://github.com/kubernetes/kubernetes/blob/29669a5e219ffabb99e5e68775f8ad55bf19c5e0/pkg/volume/awsebs/aws_util.go#L221-L225
    That works for /dev/sda -> /dev/sda1. It does not work for NVMe: /dev/nvme0n1 -> /dev/nvme0n1p1 (notice extra "p").

2. `devicePath` is not set. Then the code does not use `partition` at all:
https://github.com/kubernetes/kubernetes/blob/29669a5e219ffabb99e5e68775f8ad55bf19c5e0/pkg/volume/awsebs/aws_util.go#L235-L241

/sig storage

cc: @gnufied @leakingtapan  @kubernetes/sig-aws-misc

**Comment by gnufied** [comment]
nvme code path does not uses devicePath set in node object at all, afaik. So we have to fix this in the code that waits for device attachment on the node..
