### ISSUE TITLE
Core k8s images should have 'amd64' in the container name

### ISSUE THREAD

**Issue by javier-b-perez** [kubernetes/kubernetes#80262]
**What happened**:
When we build with make to build k8s, it will use 'amd64' in the container names. This is not the case for bazel builds, which are still using something like 'kube-apiserver' instead of 'kube-apiserver-amd64'

**What you expected to happen**:
Images build with make or bazel should have 'amd64' in the container name

**How to reproduce it (as minimally and precisely as possible)**:
make quick-release
cat manifest.json inside tar
"RepoTags": ["k8s.gcr.io/kube-apiserver-amd64:v1.16.0-alpha.1.15_de9fb983e7dc80"

make bazel-release
cat manifest.json inside tar
"RepoTags": ["k8s.gcr.io/kube-apiserver:v1.16.0-alpha.1.15_de9fb983e7dc80"

**Comment by dims** [comment]
+1 we need to standardize both builds to generate the same. 
+1 to add `-amd64` to the bazel build

**Comment by BenTheElder** [comment]
FYI @neolit123 @fabriziopandini

**Comment by BenTheElder** [comment]
+1, cc @cblecker

**Comment by neolit123** [comment]
bazel / docker build parity SGTM.

**Comment by cblecker** [comment]
+1. Perhaps we should document a standard, like:
- All docker images that are arch specific should have the arch in the name
- Arch is only able to be omitted when it's a manifest-based tag (multi-arch)
- Document legacy exceptions, and hopefully bring them into compliance

/cc @kubernetes/sig-release

**Comment by dims** [comment]
@cblecker i like it. where is the best spot to doc this?

**Comment by justaugustus** [comment]
@cblecker @dims -- please doc as updates to: https://github.com/kubernetes/sig-release/blob/master/release-engineering/artifacts.md

**Comment by javier-b-perez** [comment]
Created https://github.com/kubernetes/sig-release/pull/728
