### ISSUE TITLE
PodOverhead: add scheduler integration test

### ISSUE THREAD

**Issue by egernst** [kubernetes/kubernetes#80264]
**What would you like to be added**:

add a scheduler integration test for Pod Overhead feature

**Why is this needed**:

Add test coverage, and help guarantee continued functionality of the PodOverhead feature in the scheduler.

**Comment by egernst** [comment]
Thanks @alenkacz!

**Comment by egernst** [comment]
@alenkacz I wanted to check in -- are you making any progress on this?

**Comment by alenkacz** [comment]
@egernst sorry got busy with other stuff but I'll get back to this - but if you want to take it and have time for it now, feel free to take it :)

**Comment by egernst** [comment]
@ahg-g, @bsalamat  - I'm working to push PodOverhead to beta status in 1.18, and as part of this am working to add integration tests as well as e2e tests.

1. Are these the same?
2. For e2e, it seems low hanging fruit would be something along the lines of   https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/predicates.go#L210-L308, only with concept of PodOverhead and RuntimeClass included, and being just a standard test instead of conformance. Seem appropriate?

Can you help with a bit of guidance on what / where to get started?
