### ISSUE TITLE
Add unit tests for Scheduler framework

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#80272]
**What would you like to be added**:
Add unit tests for Scheduler [framework](https://github.com/congliu01/kubernetes/blob/73704f1b8e04c573185f230019cc1891375c283b/pkg/scheduler/framework/v1alpha1/framework.go#L264). 

Currently there are only [integration tests](https://github.com/congliu01/kubernetes/blob/c54c4d1962d84b0659644f8ae9c9976b547d021f/test/integration/scheduler/framework_test.go#L435-L434) for the framework. 

**Why is this needed**:
* Unit tests are easier to write and maintain. 

The integration tests requires spawning up etcd and the scheduler reconcile loop, which includes way more logic than the framework itself. It's also hard to control and inspect the input/output easily due to the fact that the Scheduler is a "black box" during integration test. As a result, we can find tests that are really hard to understand and maintain, see [example](https://github.com/kubernetes/kubernetes/issues/80227)

* Unit tests can run fast and deterministically.

Due to the asynchronous and "black box" nature of running the Scheduler reconcile loop, the current integration tests takes longer time and flaky. Here is a recent [example](https://github.com/kubernetes/kubernetes/issues/80255) of this.

* Unit tests can potentially cover more cases than integration tests.

Again, it's hard to control and inspect the system state running integration test. For example, it's not possible to inspect the full output of the Score plugin with integration test.

**Comment by congliu01** [comment]
Improves or fixes #79427 #80255 #80227

**Comment by liu-cong** [comment]
/remove-lifecycle stale

We should continue to add more tests.

**Comment by liu-cong** [comment]
At the time of writing, only RunScorePlugins and RunPreFilterPlugins are tested. We should continue to add tests for other extension points.

**Comment by charleszheng44** [comment]
@liu-cong please let me know if you still need help. I would love to add unit tests for the framework.

**Comment by liu-cong** [comment]
@charleszheng44 We still need help for this. Feel free to add more unit tests. Let me know if you need any help. Thanks!

**Comment by charleszheng44** [comment]
Hi, @liu-cong I created a PR (#85188) refers to this issue. Would you like to have a look?

**Comment by TisonKun** [comment]
It seems this issue should be closed by #85188 :-)

**Comment by SomtochiAma** [comment]
Hi, New contributor here, Has this issue been totally resolved, or can I pick it up?

**Comment by avhvr** [comment]
@SomtochiAma Have you started working on this issue? If not, can I pick it up?

**Comment by SomtochiAma** [comment]
> @SomtochiAma Have you started working on this issue? If not, can I pick it up?

Sorry, I have
