### ISSUE TITLE
kubectl cp is still escape when copy file from pod 

### ISSUE THREAD

**Issue by ks864148379** [kubernetes/kubernetes#80283]
/sig cli

**What happened**:
Redacted

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.0.1722+bf86300241e51f", GitCommit:"bf86300241e51f011040d208e43f1cd2a5c0378a", GitTreeState:"clean", BuildDate:"2019-07-18T02:23:03Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-tke.3", GitCommit:"ab6e1c10a35382c2ec70036e0e51c201eb3fc3f8", GitTreeState:"clean", BuildDate:"2019-06-18T12:12:29Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ks864148379** [comment]
/area/kubelet

**Comment by tallclair** [comment]
Do not report security issues through github. In the future, please follow the process described here: https://kubernetes.io/docs/reference/issues-security/security/

**Comment by ks864148379** [comment]
reply

**Comment by tallclair** [comment]
Obsolete with https://github.com/kubernetes/kubernetes/pull/82143
