### ISSUE TITLE
Pods stuck in "Terminating" state indefinitely if the sole node in a single-node cluster goes down.

### ISSUE THREAD

**Issue by Dev0Null** [kubernetes/kubernetes#80309]
**What happened**:
Using a `kubeadm`-based local cluster, I've setup some simple "hello world" type applications as pods, deployments, etc. There is a single node on which these applications can run (master has not been configured to allow pods to run on it).

If the node is suddenly removed from the cluster (i.e. power is disconnected), `kubectl` will report the pods as being in a "Terminating" state indefinitely. Attempting to forcibly remove the pods has no effect.

When the node is eventually brought back online, the pods automatically conclude their cleanup routine, and eventually get re-scheduled on the node.

**What you expected to happen**:
After some "reasonable" amount of time, the pods to go from "Terminating" to "Terminated" (i.e. no longer reported by `kubectl get pods`), or for attempts to just issue `kubectl delete pods/${POD_NAME}` to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Setup minimal `kubeadm` based cluster with 1x nodes. Setup a few simple pods and deployments. Power off the node, and inspect the status of pods via `kubectl get pods`: the pods remain in the "Terminating" state indefinitely.

**Anything else we need to know?**:
N/A.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
N/A. Using locally-setup cluster with `kubeadm`.

- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.2 LTS (Server).

- Kernel (e.g. `uname -a`):
Linux eagle-k8s-1-0 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
N/A.

- Network plugin and version (if this is a network-related bug):
N/A.

- Others:
N/A.

**Comment by liggitt** [comment]
cc @smarterclayton for pod safety

**Comment by smarterclayton** [comment]
The use case you describe is working as designed.

It sounds like the bug here is that you didn't know how to manually indicate the node isn't coming back to kubeadm/kubernetes, which is a documentation / usability gap, and potentially the other components of the system (node object) should do a better job of indicating what the next steps are.

If the node isn't coming back, you would delete the Node object.

**Comment by Dev0Null** [comment]
@smarterclayton Is there a way to configure nodes so that, if they are inaccessible for a specific amount of time, the pod will eventually die automatically (and if the node does come back "too late", we can then just trigger a job to reboot the node to force it into a "vanilla" state)? I'd like to automate the removal and/or rebooting of the node in such a use case, rather than having to manually delete the node.

Thank you.

**Comment by smarterclayton** [comment]
Rebooting a node is generally something your infrastructure would provide.
You would automate it by checking every few minutes if your node has had
the NotReady condition for more than X minutes, then trigger a remote
reboot (however that is done).

Kubernetes lets cloud providers handle this automatically, but you have to
write your own to do otherwise.

**Comment by Dev0Null** [comment]
@smarterclayton Thank you for the help and detailed explanation.

Closing.
