### ISSUE TITLE
kubectl cp Permission denied

### ISSUE THREAD

**Issue by zhaofengcumt** [kubernetes/kubernetes#80308]
kubectl version:v1.12.4
when i cp a directory in the loclhost to a remote pod it says:
```
[root@wlwk8s86 ~]# kubectl cp test jre-764864d479-9pbxc:/home
tar: can't create directory 'test': Permission denied
tar: can't open 'test/Dockerfile': No such file or directory
error: Internal error occurred: error executing command in container: read unix @->/var/run/docker.sock: read: connection reset by peer
```
i am the root user in the local host and iotapp user in the pod

**Comment by WanLinghao** [comment]
It seems you are trying to copy a directory located in a unauthorized directory. The `kubectl` command will compress the `test` directory and you have no authority to create files.
