### ISSUE TITLE
Scheduler's bind extension point is flaky

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#80310]
**What happened**:
Bind extension point in the scheduler framework is flaky

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80305/pull-kubernetes-integration/1151863322098798593/

/sig scheduling
/kind flake

**Comment by draveness** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80104/pull-kubernetes-integration/1151858154917597187

The last test case in `TestBindPlugin` cause the two flakes:

```go
framework_test.go:954: test #3: Expect invoke event 1 from plugin mock-unreserve-plugin instead of bind-plugin-1
framework_test.go:957: test #3: Expect val of invoke event 1 to be 1 instead of 2
framework_test.go:954: test #3: Expect invoke event 2 from plugin bind-plugin-1 instead of mock-unreserve-plugin
framework_test.go:957: test #3: Expect val of invoke event 2 to be 2 instead of 1
```

**Comment by draveness** [comment]
/close

ref: #80341
