### ISSUE TITLE
NoRouteCreated NodeNetworkUnavailable condition should be set by a cloud-provider webook, not kubelet

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#80311]
Instead of the layering violation that is kubelet setting NodeNetworkUnavailable/NoRouteCreated on startup, because this is only required by GCE + Kubenet, instead the GCE cloud provider should include a mutating admission webhook to set NodeNetworkUnavailable/NoRouteCreated on Node object admission.

This moves the responsibility for setting the condition to where it should actually live: in the cloud-specific code that requires it.

**Comment by dcbw** [comment]
Things that touch this:

pkg/controller/cloud/node_controller.go
pkg/controller/route/route_controller.go
pkg/kubelet/kubelet_node_status.go

The only big problem is kubelet setting the node condition on startup when the cloud provider is GCE. Only Kubenet needs this condition; other network plugins used on GCE (including OpenShift's default) do not need the condition as they do not use the cloud routes. So instead of kubelet setting the condition, the cloud provider itself should set it on Node object admission to ensure there is no race.

**Comment by andrewsykim** [comment]
Worth noting that applying the `NoRouteCreated` condition for AWS was also proposed https://github.com/kubernetes/kubernetes/pull/33573. I agree that checks like this should be removed, the GCE check in the kubelet is only there for legacy reasons.

> the cloud provider itself should set it on Node object admission to ensure there is no race.

The problem with doing this from the cloud provider is that the node can be scheduled pods prior to the provider setting the condition. I proposed a generic way of doing checks like this in https://github.com/kubernetes/enhancements/pull/1003.
