### ISSUE TITLE
Error when using go get with go modules

### ISSUE THREAD

**Issue by MrD2** [kubernetes/kubernetes#80316]
**What happened**:
go get k8s.io/kubernetes/pkg/apis/core/v1 errors with

[...]
go: k8s.io/kube-aggregator@v0.0.0: unknown revision v0.0.0
go: error loading module requirements

**What you expected to happen**:
Correct installation of all indirect dependencies? Error does not specify problem

**How to reproduce it (as minimally and precisely as possible)**:
go mod init dns-tools
go get k8s.io/kubernetes/pkg/apis/core/v1 errors with

**Environment**:
- Kubernetes version (use `kubectl version`):kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: OpenStack
- OS (e.g: `cat /etc/os-release`): cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):uname -a
Linux Somewho 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by MrD2** [comment]
/sig api-machinery
@kubernetes/sig-api-machinery-bugs

**Comment by roycaihw** [comment]
cc @dims @liggitt

**Comment by liggitt** [comment]
k8s.io/kubernetes is not intended to be used with go get

the published k8s.io/api repos can be used that way

If you want to depend on k8s.io/kubernetes with go modules, you would need to define require directives for matching levels of all of the published staging repositories in your go.mod file

/close

**Comment by idevz** [comment]
hi, @liggitt what did you mean by
>If you want to depend on k8s.io/kubernetes with go modules, you would need to define require directives for matching levels of all of the published staging repositories in your go.mod file

is it like I import "client-go" using `import "k8s.io/kubernetes/staging/src/k8s.io/client-go/kubernetes"` instead of `import "k8s.io/client-go/kubernetes"`?

**Comment by idevz** [comment]
hi, @liggitt 
thanks a lot, I did this below, and it work for me:
```go.mod

	k8s.io/api => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/api
	k8s.io/apiextensions-apiserver => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/apiextensions-apiserver
	k8s.io/apimachinery => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/apimachinery
	k8s.io/apiserver => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/apiserver
	k8s.io/cli-runtime => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/cli-runtime
	k8s.io/client-go => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/client-go
	k8s.io/cloud-provider => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/cloud-provider
	k8s.io/cluster-bootstrap => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/cluster-bootstrap
	k8s.io/code-generator => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/code-generator
	k8s.io/component-base => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/component-base
	k8s.io/cri-api => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/cri-api
	k8s.io/csi-translation-lib => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/csi-translation-lib
	k8s.io/kube-aggregator => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/kube-aggregator
	k8s.io/kube-controller-manager => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/kube-controller-manager
	k8s.io/kube-proxy => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/kube-proxy
	k8s.io/kube-scheduler => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/kube-scheduler
	k8s.io/kubectl => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/kubectl
	k8s.io/kubelet => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/kubelet
	k8s.io/kubernetes => /Users/idevz/code/k8s-x/kubernetes
	k8s.io/legacy-cloud-providers => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/legacy-cloud-providers
	k8s.io/metrics => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/metrics
	k8s.io/sample-apiserver => /Users/idevz/code/k8s-x/kubernetes/staging/src/k8s.io/sample-apiserver
```
