### ISSUE TITLE
the OWNERS file for /volume/portworx contains invalid format

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#80312]
the OWNERS file for portworx volume contains a list of "maintainers" with a single person that is not a member of the k8s org.

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/portworx/OWNERS

in any case the OWNERS file should use a list of approvers and reviewers, see:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/OWNERS

options:
- promote the user to a member of the k8s org
- remove the OWNERS file and rely on the parent folder OWNERS file
- remove current "maintainer" and add other people.

it's up to sig-storage to decide what action to take.

/kind bug
/sig storage
/assign @saad-ali @msau42

**Comment by msau42** [comment]
@lpabon can you help to address the inconsistencies

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/kubernetes/commit/ab72c099373bbde86f7bec50cc5c2f21a07505b0

/close
