### ISSUE TITLE
Error when deploy nifi on K8s

### ISSUE THREAD

**Issue by tle-totalwine** [kubernetes/kubernetes#80323]
E 2019-07-18T18:54:48.222235840Z chmod: cannot access '/tmp/configure_statefulset.sh': No such file or directory
 
E 2019-07-18T18:54:48.222412340Z /bin/sh: 1: /tmp/configure_statefulset.sh: not found
 
E 2019-07-18T18:54:48.246670693Z E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
 
E 2019-07-18T18:54:48.246708973Z E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
 
E 2019-07-18T18:54:48.250372025Z /bin/sh: 1: nslookup: not found
 
E 2019-07-18T18:54:48.253369805Z sed: can't read /conf/nifi.properties: No such file or directory
 
E 2019-07-18T18:54:48.255494882Z /bin/sh: 1: nslookup: not found
 
E 2019-07-18T18:54:48.258729940Z sed: can't read /conf/nifi.properties: No such file or directory
 
E 2019-07-18T18:54:48.263223449Z /bin/sh: 1: nslookup: not found
 
E 2019-07-18T18:54:48.265267527Z sed: can't read /conf/nifi.properties: No such file or directory
 
E 2019-07-18T18:54:48.267619412Z sed: can't read /conf/nifi.properties: No such file or directory
 
E 2019-07-18T18:54:48.268869584Z mkdir: cannot create directory ‘/state’: Permission denied
 
E 2019-07-18T18:54:48.270027356Z touch: cannot touch '/state/zookeeper/myid': No such file or directory
 
E 2019-07-18T18:54:48.273782481Z /bin/sh: 1: cannot create /state/zookeeper/myid: Directory nonexistent
 
E 2019-07-18T18:54:48.275396463Z sed: can't read /opt/nifi/nifi-1.9.2/conf/nifi.properties: No such file or directory
 
E 2019-07-18T18:54:48.276965078Z sed: can't read /opt/nifi/nifi-1.9.2/conf/nifi.properties: No such file or directory
 
E 2019-07-18T18:54:48.278581080Z sed: can't read /opt/nifi/nifi-1.9.2/conf/bootstrap.conf: No such file or directory
 
E 2019-07-18T18:54:48.280060639Z sed: can't read /opt/nifi/nifi-1.9.2/conf/bootstrap.conf: No such file or directory
 
E 2019-07-18T18:54:48.287937054Z grep: /opt/nifi/nifi-current/conf/bootstrap.conf: No such file or directory
 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> Error when deploy nifi on K8s

if "nifi" has an issue tracker repository or a slack channel it would be best to get feedback there first.

/remove-kind ubg
/triage support
