### ISSUE TITLE
Remove deprecated ExternalID from NodeSpec

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#80334]
Remove deprecated ExternalID from NodeSpec since it should be removed in 1.13

> 	// Deprecated. Not all kubelets will set this field. Remove field after 1.13.	
	// see: https://issues.k8s.io/61966	
	// +optional	

ref: 61966

/sig node
/kind cleanup
/assign

**Comment by swatisehgal** [comment]
https://github.com/kubernetes/kubernetes/pull/61877 addressed this issue.

/close
