### ISSUE TITLE
Storage tests of form "multiVolume [Slow] should access to two volumes ... on different node" tests periodically skip

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#80333]
Tests of the form  `should access to two volumes ... on different node` periodically skip in all jobs. Some examples include:
```
[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Pre-provisioned PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single volume from pods on different node
[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single volume from pods on different node
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with different volume mode and retain data across pod recreation on different node
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node
[sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single volume from pods on different node
[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node
```

I think it has to do with some non-determinism in how the pods are scheduled in the test and then the test just gets skipped.

I think this line is getting triggered every couple of runs to skip the test:
https://github.com/kubernetes/kubernetes/blob/477304cdbdafed50826a3538c8a51fd91b89ad4e/test/e2e/storage/testsuites/multivolume.go#L389

However, there are definitely available nodes for the second pod. It may just be that the anti-affinity preference is not strong enough of a guarantee?

/sig storage
/kind test-failure

See testgrid for these tests:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-slow

/assign @tsmetana 
/cc @msau42 @saad-ali @hantaowang

**Comment by davidz627** [comment]
Since its hard to link to a specific case for testgrid, here's an example of what it looks like (white boxes indicate the test was skipped that run):

![skippy](https://user-images.githubusercontent.com/5459214/61499861-90fcbf00-a97d-11e9-8680-445cd6730b8d.png)

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures 
/assign @jsafrane 

I don't like the way the fix in https://github.com/kubernetes/kubernetes/pull/78697 was done.  Tests should be using hard anti-affinity instead of preference otherwise you get flaky behavior like this.  We should have a per-driver method in the beginning of the test to check number of nodes in each driver's topology and skip if it doesn't meet the criteria.

**Comment by jsafrane** [comment]
> We should have a per-driver method in the beginning of the test to check number of nodes in each driver's topology and skip if it doesn't meet the criteria.

That won't work for CSI.

**Comment by msau42** [comment]
Can we check topology after driver has been installed?

**Comment by jsafrane** [comment]
For example, OpenShift runs one master (tainted) and one node in each zone for tests. So the test needs to check for taints, topology, attach limits and who knows what else. The test would probably need to replicate all scheduler predicates.

**Comment by msau42** [comment]
I don't think the check needs to be that complex.  Attach limits could potentially be inferred at the general test case level by checking the limit after driver installation (and in this case I really hope a plugin can support 2).  So all the plugin's check needs to do is go through all the schedulable nodes and make sure there are enough nodes per its topology.

**Comment by jsafrane** [comment]
> go through all the schedulable nodes and make sure there are enough nodes per its topology.

Does it include taints?

**Comment by msau42** [comment]
On my kube-up cluster, my master status says "SchedulingDisabled" and most of e2e tests that do check node count look for this status. I'm not sure how taints impact that status:
```
NAME                              STATUS                     ROLES    AGE   VERSION                            INTERNAL-IP   EXTERNAL-IP     OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
e2e-test-msau-master              Ready,SchedulingDisabled   <none>   10d   v1.15.1-beta.0.41+e49830053f470d   10.128.0.2    35.222.11.36    Container-Optimized OS from Google   4.14.94+         docker://18.9.3
e2e-test-msau-minion-group-bj20   Ready                      <none>   10d   v1.15.1-beta.0.41+e49830053f470d   10.128.0.4    35.192.70.205   Container-Optimized OS from Google   4.14.94+         docker://18.9.3
e2e-test-msau-minion-group-hbwd   Ready                      <none>   10d   v1.15.1-beta.0.41+e49830053f470d   10.128.0.5    35.239.49.50    Container-Optimized OS from Google   4.14.94+         docker://18.9.3
e2e-test-msau-minion-group-x588   Ready                      <none>   10d   v1.15.1-beta.0.41+e49830053f470d   10.128.0.3    35.192.83.247   Container-Optimized OS from Google   4.14.94+         docker://18.9.3
```

**Comment by tsmetana** [comment]
I admit I was also not very happy with the solution implemented in the PR #78697. I just could not come with anything better. I used the maximum weight for the affinity preference so it's somewhat surprising the scheduler decides to schedule the pod against the preference though there are nodes that could have been used. And if the affinity preference works this way then yes, the fix is broken... It's a bit surprising behaviour though.

**Comment by msau42** [comment]
In the topology test suite, I implemented a check on [number of available topologies](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/topology.go#L135) in the cluster. You can consider reusing that for these tests

**Comment by tsmetana** [comment]
Forgot about this one but I'll try again...
/remove-lifecycle stale

**Comment by davidz627** [comment]
@tsmetana did your PR resolve this issue?
/remove-lifecycle stale

**Comment by msau42** [comment]
This should be resolved
/close
