### ISSUE TITLE
error: yaml: line 2: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Avy4140** [kubernetes/kubernetes#80340]
Asarma-M15MBP:~ asarma$   curl -LO https://k8s.io/examples/application/wordpress/mysql-deployment.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    671      0 --:--:-- --:--:-- --:--:--   672
100  1238  100  1238    0     0   2009      0 --:--:-- --:--:-- --:--:--  2009
Asarma-M15MBP:~ asarma$   curl -LO https://k8s.io/examples/application/wordpress/wordpress-deployment.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0   1019      0 --:--:-- --:--:-- --:--:--  1022
100  1323  100  1323    0     0   3165      0 --:--:-- --:--:-- --:--:--  3165
Asarma-M15MBP:~ asarma$ nano kustomization.yaml
Asarma-M15MBP:~ asarma$ kubectl apply -k ./
error: yaml: line 2: mapping values are not allowed in this context
Asarma-M15MBP:~ asarma$ 
Im trying to Add resource configs for MySQL and WordPress and getting this error on my minikube. What can be the issue?

**Comment by neolit123** [comment]
> error: yaml: line 2: mapping values are not allowed in this context

best to share the contents of the YAML.

/triage support
