### ISSUE TITLE
client-go/testing: Can’t list pods after creating eviction

### ISSUE THREAD

**Issue by bouk** [kubernetes/kubernetes#80354]
The client-go Kubernetes fake client can’t list pods after an eviction is created.

**What happened**:

https://github.com/kubernetes/kubernetes/pull/71599 introduced a regression in the fake clientset, where creating an Eviction causes listing pods to fail with `item[0]: can't assign or convert v1beta1.Eviction into v1.Pod`. This is because the Eviction is stored next to the pods, so listing the pods also lists the evictions which then fail to get assigned to the PodList.

**What you expected to happen**:

Listing pods to work after creating an eviction

**How to reproduce it (as minimally and precisely as possible)**:

```

package main

import (
        v1 "k8s.io/api/core/v1"
        policy "k8s.io/api/policy/v1beta1"
        meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/client-go/kubernetes/fake"
)

func main() {
        client := fake.NewSimpleClientset(
                &v1.Pod{
                        ObjectMeta: meta_v1.ObjectMeta{
                                Name:      "pod-1",
                                Namespace: "default",
                        },
                },
        )
        client.CoreV1().Pods("default").Evict(&policy.Eviction{
                ObjectMeta: meta_v1.ObjectMeta{
                        Name: "pod-1",
                },
        })
        _, err := client.CoreV1().Pods("default").List(meta_v1.ListOptions{})
        // err: item[0]: can't assign or convert v1beta1.Eviction into v1.Pod
}
```

**Anything else we need to know?**:

To fix this we could filter out the resources that have a ‘subresource’ when listing, or not store the evictions at all.

**Environment**:
- client-go version: `k8s.io/client-go v0.0.0-20190620085101-78d2af792bab`

**Comment by lynx-coding** [comment]
Is there a way to solve this issue on client side? E.g. filtering when I request a list of deployments?

**Comment by ElliotPenson** [comment]
@lynx-coding Unfortunately filtering doesn't to help. I've tried selecting on kind and labels.

Note that this issue also affects `client.CoreV1().Pods().Get()`.
```
can't assign or convert v1beta1.Eviction into v1.Pod
```

**Comment by varshavaradarajan** [comment]
👋 I'd like to pick this up as it is affecting some of the tests we have. Can this please be reopened? 

I looked into the issue and saw that when a subresource is added, we replace the parent resource with it: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L107 and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L404. So, both list and get are problematic after a subresource like eviction or binding is created. 

As per https://github.com/kubernetes/kubernetes/pull/80426#discussion_r306928468, can I check if the subresource is present in the list and action.Resource is either `pods` or `nodes` and not update the parent resource?

**Comment by fedebongio** [comment]
thank you @varshavaradarajan 
/triage accepted
