### ISSUE TITLE
Concurrent read/write error for NodeInfoSnapshot between scheduler and plugins

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#80357]
**What happened**:

In the new scheduler framework, plugins and scheduler core share the same `NodeInfoSnapshot`, both of them use the `NodeInfoSnapshot` returned by [`func (f *framework) NodeInfoSnapshot()`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/framework.go#L444).  When scheduler core updates([`UpdateNodeInfoSnapshot`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/cache/cache.go#L211)) the `NodeInfoSnapshot` in the beginning of every schedule cycle, plugins(e.g. permit plugins, bind plugins) in another goroutine might read the `NodeInfoSnapshot` in the same time. Then there will be a concurrent read/write error(refer https://golang.org/doc/go1.6#runtime).

> The runtime has added lightweight, best-effort detection of concurrent misuse of maps. As always, if one goroutine is writing to a map, no other goroutine should be reading or writing the map concurrently. 

**What you expected to happen**:

No concurrent read/write error happens.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling
/assign
/cc @bsalamat @ahg-g

**Comment by ahg-g** [comment]
That is a very good catch. The binding cycle is run in a [separate goroutine](https://github.com/kubernetes/kubernetes/blob/c2a4369ba4f37ef8b1e639382b2f9fc14069ca7b/pkg/scheduler/scheduler.go#L545), and so updating NodeInfoSnapshot could happen concurrently with the execution of permit/prebind/bind/postbind plugins of another pod.

**Comment by hex108** [comment]
There are 2 proposals to solve it:

* Proposal 1: Add a RWLock for the struct `NodeInfoSnapshot`. It is an intuitive solution. Code need to hold a lock when visiting data of `NodeInfoSnapshot`.

   Pros:

   * No need to change the interface of [`FrameworkHandle`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/interface.go#L283).
   * There is little performance impact since most operations are read, RWLock works well for this case.

   Cons:

   * Code need to hold a lock first. And it is error prone for plugins to forget it.

* Proposal 2: Add other methods for  interface [`FrameworkHandle`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/interface.go#L283), replacing `NodeInfoSnapshot() *internalcache.NodeInfoSnapshot` with `GetNodeInfo(nodeName string) NodeInfo` and `IterateOverNode(...)`, it works similar to `WaitingPod`'s two method `IterateOverWaitingPods()` and `GetWaitingPod()`.

   Pros:

   * Easy to use
   * Little performance impact. We will also use RMLock for it.

   Cons:
 
   * Need to change the interface of `FrameworkHandle`.

I prefer to choose proposal 2, because it is easier to use and it is acceptable to change interface at alpha stage.

**Comment by bsalamat** [comment]
A NodeInfo snapshot is meant to be used during a scheduling cycle, not in a bind cycle. Please refer to [this for the definition](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#scheduling-cycle--binding-cycle). It does not make sense for plugins in "binding cycle" to use the nodeinfo snapshot. A snapshot is meant to be fixed and non-changing. Binding cycle plugins should use the scheduler cache instead.

**Comment by bsalamat** [comment]
We have already [pointed out](https://github.com/kubernetes/kubernetes/blob/0d2b85878d417daf98ea59e8dc7a264a5533ae5a/pkg/scheduler/framework/v1alpha1/interface.go#L284) that the snapshot changes after "Reserve". I think we should expand that comment and explicitly state that plugins in the binding cycle should not use the snapshot.

**Comment by ahg-g** [comment]
Documenting sounds good to me, I think the comment should explicitly warn against using it in permit/prebind/bind/postbind plugins, and mention that using it in those plugins is practically a bug.

**Comment by hex108** [comment]
Thanks for the explanation. It is OK if it is not intended for use by bind cycle. I'll update the document for it.

BTW: I could not find any scheduler cache related code in the framework code.  Anyway we can add it when it is needed.
