### ISSUE TITLE
Node Lifecycle Controller Races

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#80366]
**What happened**:
I have been looking at `pkg/controller/nodelifecycle/node_lifecycle_controller.go` due to a customer issue where pods not getting evicted. The [controller](https://github.com/kubernetes/kubernetes/blob/de967b717d0a31353c2e1e64960773cfdd7a9001/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L358-L391) is designed to spawn a few go routines. In the case of using taints the following go routines are run:

* taintManager
* nodeProcessingPassWorker
* doNoexecuteTaintingPass
* monitorNodeHealth

In the case where evictions are used these go routines are spawned:

* NodeProcessingPassWorker
* doEvictionPass
* monitorNodeHealth

I am specifically looking at the *eviction* code paths and *not* the tainting code path. [doEvictionPass](https://github.com/kubernetes/kubernetes/blob/de967b717d0a31353c2e1e64960773cfdd7a9001/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L513) has an evictorLock protecting unspecified instance variables. When `doEvictionPass` and `monitorNodeHealth` run in parallel both are reading and writing non-protected (mutex locked) instance variables. zoneStates is particularly problematic [instance1](https://github.com/kubernetes/kubernetes/blob/de967b717d0a31353c2e1e64960773cfdd7a9001/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L915-L919) and [instance2](https://github.com/kubernetes/kubernetes/blob/de967b717d0a31353c2e1e64960773cfdd7a9001/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1040). `nodeHealthMap` appears to be another problematic variable [instance3](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L698) and [instance4](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L698).

**What you expected to happen**:
The customer issue is pods are failing to be evicted, but they are being queued into the eviction queue. I suspect the variables are stomping on each other to prevent the evictions. Could someone double check this code path? Are these races supposed to happen in this module?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.x

/cc @kubernetes/sig-node-bugs 
/cc @sjenning @derekwaynecarr

**Comment by tedyu** [comment]
It seems evictorLock is used to protect nc.zonePodEvictor , not nc.zoneStates .

**Comment by tedyu** [comment]
Do you see any error in the log.
Such as:
```
                        klog.Errorf("Setting initial state for unseen zone: %v", k)
```

**Comment by tedyu** [comment]
handleDisruption is called by monitorNodeHealth.

Not clear why evictorLock is needed in methods such as addPodEvictorForNewZone which are only called by monitorNodeHealth.
