### ISSUE TITLE
Azure LoadBalancer would lose backends when the nodes are upgraded to latest model

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#80365]
**What happened**:

After fixing https://github.com/kubernetes/kubernetes/issues/71594, Azure cloud provider updates the network configurations per instance, so that the nodes would be rebooted when they are added to ALB. But this introduces a problem, that the latest model of each instance is different now from VMSS.

Refer https://github.com/Azure/aks-engine/issues/1615#issuecomment-513158712:

> Initially, everything looks ok, but if you go to the instances in the VMSS pool you will see that you have a warning icon in the "last model".
> 
> The app is still available, but if you press "update" in the VMSS instances you will lose the connectivity between the LB and the VMSS Instances, and later the "last model" column is with all the instances in "yes".
> After this, the App is not accessible anymore.

So, Azure LoadBalancer would lose backends when the nodes are upgraded to the latest model.

**What you expected to happen**:

Azure LoadBalancer should still work when instances are upgraded to the latest model.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/sig azure
/kind bug
/milestone v1.16

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mo-saeed** [comment]
@feiskyer Any thoughts when the fix can be ready ?

**Comment by feiskyer** [comment]
@mo-saeed Would be fixed in v1.16.0

**Comment by mo-saeed** [comment]
@feiskyer Can this be included in other versions mainly 1.14 and 1.15 as well ?

**Comment by feiskyer** [comment]
sure, would cherry pick when it's finished

**Comment by mo-saeed** [comment]
That's great it's fixed, Would be cool if it can be included in 1.13, 1.14 and 1.15. 

Thanks a lot !!

**Comment by alexeldeib** [comment]
@feiskyer I'm hitting this and it's blocking certain progress for my team -- let me know if I can put on my release-engineering-associate hat and help cherry pick this?

Additionally, regarding this: 
> Note that even after we add this back to VMSS model, the latest model issues are still there because Kubernetes won't do the model upgrade for each instance. Customers may decide to do that, but should also aware that all the instances may be rebooted at the same time.

There's no negative impact there as long as all the instances have been added to the LB pool, right?

**Comment by feiskyer** [comment]
@nilo19 Could you create cherry picks for 1.15 and 1.14 branch?

**Comment by nilo19** [comment]
> @nilo19 Could you create cherry picks for 1.15 and 1.14 branch?

Sure, I'll do it.

**Comment by mo-saeed** [comment]
Reminder for 1.14 and 1.15 cherry picks :)

**Comment by feiskyer** [comment]
Cherry picks have already merged at https://github.com/kubernetes/kubernetes/pull/81765 and https://github.com/kubernetes/kubernetes/pull/81763.

**Comment by mboersma** [comment]
I verified that the "press update" scenario described here does not cause any loss of LB connectivity with Kubernetes 1.16.0 and 1.15.4 clusters provisioned with aks-engine v0.41.0.
