### ISSUE TITLE
TypeError: Request path contains unescaped characters

### ISSUE THREAD

**Issue by yangquanxyz** [kubernetes/kubernetes#80367]
在kubernetes环境中部署的nodejs项目中发送发送request的get请求时url中携带有中文参数时出现TypeError: Request path contains unescaped characters错误，在其他环境则不会

**Comment by konghui** [comment]
这个应该是你请求url的时候没有做url的编码，发送请求的时候如果出现中文需要做编码的，不可以直接发送的，这类问题你可以直接到stackoverflow看下，和k8s没有关系的。这里发问题最好用英文吧。
