### ISSUE TITLE
Allow for composable pipelines for capturing logs etc

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#80370]
At least on EKS, the config to send logs to CloudWatch is ridiculously verbose and complex. What happened to a standard pipeline:

```bash
docker run app |  docker run -i capture-logs 
```

I have this question on SuperUser and looking for an answer:
https://superuser.com/questions/1461621/is-there-a-way-to-define-a-second-container-which-can-capture-stdout-stderr

Our company is _not_ using kubernetes for everything, and as a devops engineer, I don't want to setup logging 5 different ways.  So to setup logging 1 way for all our services, we could use `docker run -i capture-logs` to send our logs to CloudWatch in a standardized manner.

So is there some way to configure K8S to use a user-defined container to capture stdout/stderr?

@k8s-ci-robot  - please list the sigs in your bot message, and tell people what a sig is

**Comment by mister-cholo** [comment]
Good thinking, for example, fluentd can capture the stdout/stderr, so there must be some way for users to define other containers that can be put in a linux shell pipeline by k8s?
