### ISSUE TITLE
[Scheduler] Remove dependency of cache on algorithms

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#80372]
`pkg/scheduler/internal/cache` shouldn't depend on `pkg/scheduler/algorithm`

We can move the listers into a a new package `pkg/scheduler/internal/listers` that both `algorithm` and `cache` can depend on.

We can also consider moving `predicates.NodeInfo` into the lister package or another one. This way, `Cache` interface doesn't need to repeat the NodeInfo's functions signatures but rather embed the interface.

/sig scheduling

**Comment by alculquicondor** [comment]
Hi @draveness I was planning to work on this.

**Comment by alculquicondor** [comment]
@bsalamat what would be your suggestion for NodeInfo? Maybe we can keep both listers and NodeInfo in a single package that is not internal.

**Comment by alculquicondor** [comment]
@draveness do you mind if we take this?

**Comment by draveness** [comment]
Please do. I thought you are working on this. :)

/unassign

Regards,
Draven

**Comment by alculquicondor** [comment]
I want to first know what we should do with `NodeInfo`.

**Comment by liu-cong** [comment]
I can work on this if @alculquicondor doesn't mind

**Comment by tedyu** [comment]
As Aldo said above, we should decide how NodeInfo is handled.
It's better to get consensus first.

**Comment by Huang-Wei** [comment]
> We can move the listers into a new package pkg/scheduler/internal/listers that both algorithm and cache can depend on.

`internal` package has implicit [limitations](https://golang.org/doc/go1.4#internalpackages). Although we're sometimes breaking it (e.g. pkg/scheduler/core depends on pkg/scheduler/internal), this is not a pattern we should promote. If we don't gain enough benefits, I'd say leave them in `pkg/scheduler/algorithm` - this may have already been considered in the refactoring lead by @misterikkit.

> We can also consider moving predicates.NodeInfo into the lister package or another one. This way, Cache interface doesn't need to repeat the NodeInfo's functions signatures but rather embed the interface.

kubelet.go` is dependent on this, we can't move into an internal pkg. But I think it makes sense to move to `pkg/scheduler/algorithm`.

**Comment by liu-cong** [comment]
Based on @Huang-Wei 's insightful input, there doesn't seem to be an obvious solution. Leaving them as is seems reasonable - it's not great, but not a deal breaker either. 

@alculquicondor WDYT?

**Comment by alculquicondor** [comment]
I'm unfamiliar with this refactoring by @misterikkit.

The point is that it's semantically incorrect that cache depends on algorithms (See [here](https://github.com/kubernetes/kubernetes/pull/80220#discussion_r305156226) for original motivation). Another package I could propose is `pkg/scheduler/clusterstate`, which should be able to host both listers and NodeInfo.

**Comment by Huang-Wei** [comment]
> Another package I could propose is `pkg/scheduler/clusterstate`

`pkg/scheduler/internal/<pkgname>` sounds better.. - if we have to make changes. Again, my concern is that we're not following the semantics of Golang `internal` package. But it seems we don't have other alternatives, so I'm fine with creating a new internal pkg.

**Comment by liu-cong** [comment]
I am not a big fan of refactoring without adding much business value and with potential risks to break other things. Unless this current structure blocks anything that I'm not aware of. 

I am going to unassign myself for now. But I am willing to help again if there is a good reason to refactor.

**Comment by alculquicondor** [comment]
/kind cleanup
/remove-kind feature

I believe it's important to increase the separation of concerns of our packages and/or structures. I don't think this cleanup in particular is a risk, as we are only moving structs from one place to another. But we don't need to do it now.

A short term solution I can think of is to move `NodeInfo` back to `algorithm` so that Cache can embed the interface. The package `algorithm` is actually pretty independent from `predicates` and `priorities`.

**Comment by Huang-Wei** [comment]
> A short term solution I can think of is to move `NodeInfo` back to `algorithm` so that Cache can embed the interface. The package `algorithm` is actually pretty independent from `predicates` and `priorities`.

Agree.

**Comment by liu-cong** [comment]
> I'm unfamiliar with this refactoring by @misterikkit.
> 
> The point is that it's semantically incorrect that cache depends on algorithms (See [here](https://github.com/kubernetes/kubernetes/pull/80220#discussion_r305156226) for original motivation). Another package I could propose is `pkg/scheduler/clusterstate`, which should be able to host both listers and NodeInfo.

This might be the refactoring issue: https://github.com/kubernetes/kubernetes/issues/68951

**Comment by alculquicondor** [comment]
It looks like this one specifically #71863

**Comment by alculquicondor** [comment]
/assign @draveness 

I think you will need to address this before your PR.

My vote would be for `pkg/scheduler/listers` (just dropping the `internal` initial suggestion)

**Comment by draveness** [comment]
> My vote would be for `pkg/scheduler/listers` (just dropping the `internal` initial suggestion)

+1 on `pkg/scheduler/listers`, I'll send the PR to unblock my #83670.

**Comment by alculquicondor** [comment]
Hi @draveness 
Do you mind finishing up this refactoring? It looks like most of the dependencies were moved already, except for `algorithm.PodFilter`. Did you reach a consensus about where to move that one?

**Comment by draveness** [comment]
> Hi @draveness
> Do you mind finishing up this refactoring? It looks like most of the dependencies were moved already, except for `algorithm.PodFilter`. Did you reach a consensus about where to move that one?

I think the PodFilter has already been moved to listers package by @ahg-g

**Comment by draveness** [comment]
we could close this one if it is the job left.

**Comment by ahg-g** [comment]
this is done indeed.

/close

**Comment by alculquicondor** [comment]
For reference, this was the fixing PR #84193

Thanks, guys
