### ISSUE TITLE
Multi-Attach error for Azure Disks still happening in v1.14 (preview for windows containers on AKS)

### ISSUE THREAD

**Issue by lingtham** [kubernetes/kubernetes#80381]
**What happened**:
This is in Azure Kubernetes Service with the Windows container preview extension 

Pods are running on node1, I deallocate node1, pods go to terminating state. Then, deployment recreates new pods on node2. However, those new pods are stuck in a ContainerCreating state for 18+ hours because of Multi-Attach error for the Azure Disks. The old pods are also stuck in a terminating state and the disks are still attached to deallocated node1 so they are not free to attach to new pods. 

This has happened all 3 times that I've attempted this. 

**What you expected to happen**:
old pods get terminated, disks detach from deallocated VM and reattach to new pods recreated on other VM

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up Kubernetes cluster on Azure with the windows container preview extension installed
2. Have 2 windows OS nodepools
3. Deploy pod with Azure disk attached (made from a PVC) to node1
4. Deallocate node1 in azure portal
5. After a few minutes, old pod on node1 will be stuck in terminating state and new pods on node2 will be stuck in ContainerCreating state with Multi-Attach error for disk

**Anything else we need to know?**:
very similar situation to what happened [here](https://github.com/kubernetes/kubernetes/issues/62282) 

**Environment**:
- Kubernetes version (use `kubectl version`): v.1.14.0
- Cloud provider or hardware configuration: Azure (westus)
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): 10.0.17763.379
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

@andyzhangx since it seems like you've handled this type of issues before

**Comment by lingtham** [comment]
/sig azure
/sig windows 

Also, sorry I just found the AKS repo after posting this so please let me know if I should move this

**Comment by andyzhangx** [comment]
@lingtham It's a known issue in upstream, in case of node failure, disk PV could not be moved to another node automatically now.
There is a working proposal in k8s community to track this issue: https://github.com/kubernetes/enhancements/pull/1116, still working on.

**Comment by andyzhangx** [comment]
@lingtham to workaround this issue, would you detach that disk and wait for a few minutes to check? thanks.

**Comment by lingtham** [comment]
Deleting and reapplying the deployment works around this issue but I was just wondering why this was happening. Thanks for letting me know!
