### ISSUE TITLE
kubectl explain display Object instead of the name of the Kind

### ISSUE THREAD

**Issue by feloy** [kubernetes/kubernetes#80386]
**What happened**:

The command `kubectl explain pod.spec` displays " Object " for the resource spec.

**What you expected to happen**:

I would expect it displays the real name of the Kind, so I can use it in a Go program, and possibly with the full path, so I can use the path for the Go import.

**How to reproduce it (as minimally and precisely as possible)**:

kubectl explain pod.spec

**Anything else we need to know?**:

**Comment by agile6v** [comment]
What can you see with `kubectl explain pod.spec --v=8` ?
