### ISSUE TITLE
Allow ConcurrentJobSyncs to be set for kube-controller-manager

### ISSUE THREAD

**Issue by millerick** [kubernetes/kubernetes#80397]
**What would you like to be added**:
The ability to set `ConcurrentJobSyncs` for the kube-controller-manager at runtime.  It looks like the option exists in the code, but a mechanism is not available to set it via kops.  If I understand the code correctly, a flag needs to be added in order to be able to set the value using kops.

**Why is this needed**:
We want to shift a lot of our batch processing jobs from running directly on our CI servers to running as jobs on Kubernetes.  Unfortunately if too many jobs are launched on kubernetes, they begin to back up.  We've noticed up to a 10 minute delay between when the logs indicate that a job has finished and when the kubernetes API actually reflects the same on our small ~30 node cluster.

**Comment by millerick** [comment]
I think scalability is the best fit since this is impacting our ability to fully utilize and scale how we use our kubernetes cluster.

**Comment by Michael0x2a** [comment]
Heyo -- we're running into a similar issue as this with our Kubernetes cluster.

Is there anything I can do to help get https://github.com/kubernetes/kubernetes/pull/85815 landed?

/reopen

**Comment by atiratree** [comment]
@Michael0x2a can you please describe your use case in a more detail? how How this affects you, and how this flag would help to achieve your goals?

**Comment by Michael0x2a** [comment]
@atiratree -- I left a comment describing my use case in the PR: https://github.com/kubernetes/kubernetes/pull/110433#issuecomment-1345608977
