### ISSUE TITLE
Env var to set location of .kube directory

### ISSUE THREAD

**Issue by OJFord** [kubernetes/kubernetes#80399]
It doesn't seem possible to entirely move the `$HOME/.kube` directory, or, therefore, to use multiple under one user (should you want to for some reason - yes I'm aware of contexts).

Setting `$KUBECONFIG` takes care of the config yaml and relative files, but not `cache` and `http-cache` dirs, which are recreated in `$HOME` even if the directory is removed following setting the env var.

It would be good to either respect `$XDG_CONFIG_HOME` (and ideally `$XDG_CACHE_HOME` separately, but I won't die on that hill) or at least a `$KUBE_HOME`, which seems to exist for kubeadm/kubelet but not kubectl.

```
$ uname -or ; kubectl version
18.6.0 Darwin
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
```

/sig cli
/sig usability

**Comment by BenTheElder** [comment]
There is some precedence for multiple home environment variables on windows, however none of them are kubernetes specfiic https://github.com/kubernetes/client-go/blob/master/util/homedir/homedir.go

cc @liggitt who is everywhere and last touched this code :-)

**Comment by knight42** [comment]
I would like to take over this.

/assign

**Comment by knight42** [comment]
@OJFord Hi! I have filed a PR #91020 the implement this feature, plz give it a try!

**Comment by ensonic** [comment]
Nice to see the work to support $XDG_CACHE_HOME in PR#91020. For ~/.kube/config shouldn't this use XDG_CONFIG_HOME?

**Comment by OJFord** [comment]
/remove-lifecycle stale

(#91020 was closed without merge, and as ensonic says, only addressed cache files)

**Comment by BenTheElder** [comment]
This isn't going in without someone driving agreement with the owners that this should exist. Please go discuss with SIG CLI (mailing list, slack, or their zoom meeting). When I brought it up before the response was negative.

**Comment by OJFord** [comment]
Just a note that I did ask about this in Slack#sig-cli on 16/12/20;  @soltysh [wrote](https://kubernetes.slack.com/archives/C2GL57FJ4/p1608141630270800):
> there is an open KEP iirc, so the work is progressing, it's slow and only limited by review capabilities, we've clearly said it's something we do want to see happen in the long run during one of previous sig-cli calls
> 
> but since this is changing the current behavior it will go through an extra scrutiny to ensure we follow the deprecation process and communicate this properly, and this is an optional feature to start with

And that appears to be here: kubernetes/enhancements#2229.

Thanks again.
