### ISSUE TITLE
Windows Node Fails on Join

### ISSUE THREAD

**Issue by sahandmax** [kubernetes/kubernetes#80400]
Hi
I want to use windows node but getting below error when use kubeadm join command
thanks for helping

[preflight] Running pre-flight checks
        [WARNING Service-Docker]: no supported init system detected: Access is denied.
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 10.0.18362
DOCKER_VERSION: 18.09.2
DOCKER_GRAPH_DRIVER: overlay2
        [WARNING Service-Kubelet]: no supported init system detected: Access is denied.
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: unsupported graph driver: overlay2
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Comment by rhockenbury** [comment]
kubeadm commands are not yet supported on windows - https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/20190424-kubeadm-for-windows.md

**Comment by neolit123** [comment]
something is not setup correctly on your Windows node.
as @rhockenbury pointed out there is a KEP for this.
the work for Windows/kubeadm integration is pre-alpha.

kubeadm already works on Windows but the setup is a bit complicated.

/sig cluster-lifecycle
/area kubeadm
/close

closing in favor of https://github.com/kubernetes/kubeadm/issues/1393
