### ISSUE TITLE
delete a service corresponding ipvs record not removed when kube-proxy in ipvs mode

### ISSUE THREAD

**Issue by leopay** [kubernetes/kubernetes#80403]
**What happened**:
delete a service corresponding ipvs record not removed when kube-proxy in ipvs mode

**Anything else we need to know?**:
it seems that the forloop will never to execute after #1703, as the line #1699
https://github.com/kubernetes/kubernetes/blob/c2a4369ba4f37ef8b1e639382b2f9fc14069ca7b/pkg/proxy/ipvs/proxier.go#L1697-L1713

**Environment**:
- Kubernetes version:
latest

**Comment by leopay** [comment]
@namreg @Lion-Wei

**Comment by gongguan** [comment]
I met the same problem, it's a logical error.
[#80942](https://github.com/kubernetes/kubernetes/pull/80942)

**Comment by andrewsykim** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/80942. Please re-open if you still encounter this bug. 

/close
