### ISSUE TITLE
Container need  preRemove hook

### ISSUE THREAD

**Issue by knightXun** [kubernetes/kubernetes#80415]
**Why is this needed**:
As we all know, containers already has prestart and prestop hook. This is useful for container lifecycle. But When container is to be remove, No hook can be chosen to act. Which will be very hard for some situations such like logs collection or some device release operations. I think we better add a preRemove hook for container. It is very useful for many situations.

If you agree with that, I will be helpful to send a pr for this.

**Comment by mattjmcnaughton** [comment]
Hi @knightXun thanks for your idea :)

This is an interesting idea! I'd recommend bringing this up in #sig-node or the weekly sig node meeting. If there's sufficient community interest, the next step would be creating a [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements/tree/master/keps).

**Comment by knightXun** [comment]
@mattjmcnaughton  maybe we can define more hook for container lifecycle

**Comment by tedyu** [comment]
Can the device release operations be done in preStop hook ?

**Comment by knightXun** [comment]
@tedyu how about some dead containers?
