### ISSUE TITLE
change-cause annotation isn't recording correct commands

### ISSUE THREAD

**Issue by nigelpoulton** [kubernetes/kubernetes#80423]
**What happened**:  
I create a Deployment (imperatively or declaratively) with the `--record=true` flag. Then I update the image using `kubectl set image` . The Deployment now owns two ReplicaSets, but the `change-cause` annotation for each ReplicaSet is showing the command that was used to create the initial RS.

**What you expected to happen**:  
I expect the `kubernetes.io/change-cause` annotation on the second ReplicaSet to have the `kubectl set image` command that was used to create. I do not expect it to have the command used to create the initial RS.

For example, each time I issue a command to change a Deployment (create a new RS) I expect that specific command to be recorded in the `kubernetes.io/change-cause:` annotation for the newly created RS. What I'm actually getting is the very first command used to create the Deployment and the initial ReplicaSet is being recorded in the `change-cause` annotation for every subsequent ReplicaSet.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Deployment with this command (the issue is the same if you declaratively create the Deployment with `kubectl apply`):
```
$ kubectl run annotate-test --image=nginx --replicas=2 --port=8080 --record=true
```
Update the Deployment with this command:
```
$ kubectl set image deployment annotate-test annotate-test=redis
```
Check the change cause annotations for each RS with this command:
```
$ kubectl rollout history deploy annotate-test
REVISION  CHANGE-CAUSE
1         kubectl run annotate-test --image=nginx --replicas=2 --port=8080 --record=true
2         kubectl run annotate-test --image=nginx --replicas=2 --port=8080 --record=true
```
You can also run a `kubectl describe` against each RS to verify the incorrect command is being recorded in the annotation.

**Anything else we need to know?**: I'm like 99.9% certain this used to work properly, but I'm seeing this same incorrect behaviour going back as far as some 1.12 releases.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.3 down to as low as some 1.12 releases
- Cloud provider or hardware configuration: GKE, play-with-kubernetes, Docker Desktop
- OS (e.g: `cat /etc/os-release`): Various, but one was `PRETTY_NAME="Alpine Linux v3.9"`
- Kernel (e.g. `uname -a`): Various, but one was `Linux f8ada25d8337 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Koderok** [comment]
I would like to work on fixing this issue. I am looking at the relevant code and reproducing the issue locally. I will check if the behavior was different pre 1.12.

**Comment by nigelpoulton** [comment]
Cheers @Koderok 

I need to update this as it seems I may have misunderstood the behavior....

It seems that if you use the `--record` flag on every command, then the right command gets stored in the annotation. 

I thought that using the `--record` flag on the command that initially created the object meant you didn't have to use it on future commands. It seems I was wrong.

**However...** I still think that storing the wrong command in the annotation is bad behavior. It would be better to do something like leave the annotation blank if the `--record` flag isn't used....

Thoughts @Koderok ?
