### ISSUE TITLE
Cassandra ENV-VARS MAX_HEAP_SIZE and HEAP_NEWSIZE not passed to the JVM

### ISSUE THREAD

**Issue by ralphlaude** [kubernetes/kubernetes#80425]
**What happened**:
i am using this configuration (https://github.com/kubernetes/examples/blob/master/cassandra/cassandra-statefulset.yaml) for my Cassandra cluster in kubernetes. Each Cassandra node runs in Centos 7 VM. The ENV-VARS `MAX_HEAP_SIZE` and `HEAP_NEWSIZE` seems not to be set or pass to the JVM. This leads to Cassandra consuming much more more memory than configure. I have these values configured `MAX_HEAP_SIZE=1024M` and `HEAP_NEWSIZE=100M` but each Cassandra nodes still use at least 4G memory.

**What you expected to happen**:
 I would like to pass those parameters (`MAX_HEAP_SIZE` and `HEAP_NEWSIZE`) to the JVM

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
just install this (https://github.com/kubernetes/examples/blob/master/cassandra/cassandra-statefulset.yaml) on kubernetes

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CENTOS 7 as VM
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel
- Others:

**Comment by neolit123** [comment]
i suggest that you post this issue in the https://github.com/kubernetes/examples repository first.
and if the maintainers of the examples inform you that this is a k8s bug, please re-open this issue.

/kind documentation
/sig apps
/close

**Comment by ralphlaude** [comment]
@neolit123 thanks for your answer. The example (https://github.com/kubernetes/examples) is the same as here (https://kubernetes.io/docs/tutorials/stateful-application/cassandra/). That is reason i decided to open the issue here.  Perhaps you can explain me more about this, i just want to understand. Thanks

**Comment by neolit123** [comment]
hi, i don't know much about cassandra. you can try asking in the #sig-apps channel on k8s slack or stackoverlfow.
