### ISSUE TITLE
WIP: Behaviour (e2e) Test Framework Requirements

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#80439]
Our current e2e framework has some pain points and techical debt that needs to be enumerated and addressed.

@hh will sync [this google doc](https://docs.google.com/document/d/1nk0lTq2LOhMjMXAPdbA9JirLvooeggOMrqGSrZDbNco/edit#heading=h.u8uazl7t2tbi) into this issue description.

**Comment by hh** [comment]
/cc @timothysc @jiatongw @alejandrox1

Feel free to add discuss here or in [the google doc](https://docs.google.com/document/d/1nk0lTq2LOhMjMXAPdbA9JirLvooeggOMrqGSrZDbNco/edit#)
I'll sync the current list at the top of this issue.

**Comment by alejandrox1** [comment]
forgot to label this for testing commons
/area e2e-test-framework
