### ISSUE TITLE
[Failing Test] Errors bringing up kube-proxy in CI

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#80434]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-alpha-features

**Which test(s) are failing**:
BeforeSuite 

**Since when has it been failing**:
Failing since 7/18 
The failure seems to have been introduced in https://github.com/kubernetes/kubernetes/compare/477304cdb...3f1cb97f9
https://github.com/kubernetes/kubernetes/pull/80229 is the only PR within that window that modifies any cluster configuration. This PR is related to https://github.com/kubernetes/kubernetes/issues/80262

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

**Reason for failure**:
kube-proxy is stuck in a pending state

/milestone v1.16
/priority critical-urgent
/kind failing-test
/sig testing
/sig cluster-lifecycle
/cc @Verolop @jimangel @soggiest @alenkacz

**Comment by BenTheElder** [comment]
almost definitely related to the image change

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1154267388221329408/artifacts/bootstrap-e2e-minion-group-8xmr/kubelet.log

> E0725 05:54:40.692992    1368 remote_image.go:113] PullImage "k8s.gcr.io/kube-proxy:v1.16.0-alpha.1.233_4ed5ea601d507c" from image service failed: rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/kube-proxy:v1.16.0-alpha.1.233_4ed5ea601d507c not found
E0725 05:54:40.693155    1368 kuberuntime_manager.go:787] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/kube-proxy:v1.16.0-alpha.1.233_4ed5ea601d507c not found

**Comment by BenTheElder** [comment]
/assign
https://github.com/kubernetes/kubernetes/pull/80566

**Comment by BenTheElder** [comment]
hmm, we should watch to ensure that actually fixed it
/reopen

**Comment by BenTheElder** [comment]
Cluster came up in the most recent run, however it looks like tests may fail (it's not done yet). That should be a new issue though.

/close
