### ISSUE TITLE
[Revisit] Odd timing behavior with Readiness Probes with `initialDelaySeconds` and `periodSeconds`

### ISSUE THREAD

**Issue by philip-fox** [kubernetes/kubernetes#80431]
/kind bug

**What happened**:
Similar to the now closed ticket: [Odd timing behavior with Readiness Probes with `initialDelaySeconds` and `periodSeconds`](https://github.com/kubernetes/kubernetes/issues/62036)

On that ticket, people have commented expressing wonder as to why the ticket was closed when the problem was never fixed. I'm also wondering this, and I've encountered the problem, and would like a fix for it in a future release, if possible :-).

It seems that if the `periodSeconds` is quite small, e.g. `60`, then the readiness probe seems to be invoked very soon after the `initialDelaySeconds` interval. However, if `periodSeconds` is relatively large, e.g. `900`, then (pretty much) no matter what `initialDelaySeconds`, `timeoutSeconds`, and `failureThreshold` are set to, then the readiness probe seems to be invoked some time after the `periodSeconds` has elapsed.

**What you expected to happen**:
See: [Odd timing behavior with Readiness Probes with `initialDelaySeconds` and `periodSeconds`](https://github.com/kubernetes/kubernetes/issues/62036)

I'd expect that the first call of the probe would be very soon after `initialDelaySeconds` elapses, but [my experiments](https://github.com/kubernetes/kubernetes/issues/80431#issuecomment-514646209) show that that's not the case.

**How to reproduce it (as minimally and precisely as possible)**:
See: [Odd timing behavior with Readiness Probes with `initialDelaySeconds` and `periodSeconds`](https://github.com/kubernetes/kubernetes/issues/62036)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8+IKS", GitCommit:"fe3e332c2b0f47d4572433c3b0a1687a27fb88c6", GitTreeState:"clean", BuildDate:"2019-07-11T13:45:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mattjmcnaughton** [comment]
Hi @philip-fox ! Thanks for reopening this.

Can you explain more about what you view as the desired behavior? I just want us to quickly think through if there are any downsides to the potential new behavior before going forward with an implementation.

**Comment by philip-fox** [comment]
Hi @mattjmcnaughton 

Thanks for the reply. I suspect that the readiness probe isn't being called before the first `periodSeconds` elapses in cases in which the `periodSeconds` is large. I would expect this not to be the case.

I'm trying to run some experiments so that I can compile a table of timings which I'll add to this ticket very soon.

Maybe I'm wrong, but I think there's something weird going on, and from looking at the [previous ticket](https://github.com/kubernetes/kubernetes/issues/62036), I don't think I'm alone.

**Comment by philip-fox** [comment]
The following three tables contain the timings witnessed for deployments for three different services. The column `first_probe_completes` shows how many seconds it took before the readiness probe returned, and `within_first_period?` shows whether the probe returned within the first time interval of its `periodSeconds`.

### Service_1_Pod
| periodSeconds | initialDelaySeconds | timeoutSeconds | failureThreshold | first_probe_completes | within_first_period? |
| -- | -- | -- | --| -- | -- |
| 120 | 15 | 5 | 3 | 86 | yes |
| 120 | 15 | 5 | 3 | 86 | yes |
| 180 | 15 | 5 | 3 | 60 | yes |
| 180 | 15 | 5 | 3 | 85 | yes |
| 180 | 15 | 5 | 3 | 198 | no |
| 180 | 15 | 5 | 3 | 55 | yes |
| 240 | 15 | 5 | 3 | 180 | yes |
| 240 | 15 | 5 | 3 | 159 | yes |
| 240 | 15 | 5 | 3 | 139 | yes |
| 300 | 15 | 5 | 3 | 143 | yes |
| 300 | 15 | 5 | 3 | 186 | yes |
| 300 | 15 | 5 | 3 | 173 | yes |
| 300 | 15 | 5 | 3 | 102 | yes |
| 480 | 15 | 5 | 3 | 344 | yes |
| 480 | 30 | 5 | 3 | 342 | yes |
| 600 | 30 | 5 | 3 | 89 | yes |
| 600 | 30 | 5 | 3 | 300 | yes |
| 900 | 30 | 5 | 3 | 251 | yes |
| 900 | 30 | 5 | 3 | 548 | yes |
| 900 | 30 | 5 | 3 | 840 | yes |
| 1800 | 30 | 5 | 3 | 972 | yes |
| 1800 | 30 | 5 | 3 | 1122 | yes |
| 1800 | 30 | 5 | 3 | 283 | yes |
| 1800 | 30 | 5 | 3 | 1714 | yes |

### Service_2_Pod
| periodSeconds | initialDelaySeconds | timeoutSeconds | failureThreshold | first_probe_completes | within_first_period? |
| -- | -- | -- | --| -- | -- |
| 120 | 10 | 5 | 3 | 43 | yes |
| 120 | 10 | 5 | 3 | 69 | yes |
| 120 | 10 | 5 | 3 | 60 | yes |
| 120 | 10 | 5 | 3 | 55 | yes |
| 240 | 10 | 5 | 3 | 240 | no |
| 240 | 10 | 5 | 3 | 221 | yes |
| 300 | 10 | 5 | 3 | 43 | yes |
| 300 | 10 | 5 | 3 | 52 | yes |
| 300 | 10 | 5 | 3 | 135 | yes |
| 300 | 10 | 5 | 3 | 25 | yes |
| 480 | 10 | 5 | 3 | 49 | yes |
| 480 | 10 | 5 | 3 | 125 | yes |
| 600 | 10 | 5 | 3 | 244 | yes |
| 600 | 10 | 5 | 3 | 347 | yes |
| 900 | 10 | 5 | 3 | 786 | yes |
| 900 | 10 | 5 | 3 | 563 | yes |
| 900 | 10 | 5 | 3 | 603 | yes |
| 1800 | 10 | 5 | 3 | 248 | yes |
| 1800 | 10 | 5 | 3 | 1146 | yes |
| 1800 | 10 | 5 | 3 | 1452 | yes |
| 1800 | 10 | 5 | 3 | 421 | yes |

### Service_3_Pod
| periodSeconds | initialDelaySeconds | timeoutSeconds | failureThreshold | first_probe_completes | within_first_period? |
| -- | -- | -- | --| -- | -- |
| 240 | 30 | 5 | 3 | 205 | yes |
| 240 | 30 | 5 | 3 | 180 | yes |
| 300 | 30 | 5 | 3 | 261 | yes |
| 300 | 30 | 5 | 3 | 315 | no |
| 300 | 30 | 5 | 3 | 143 | yes |
| 300 | 30 | 5 | 3 | 176 | yes |
| 480 | 30 | 5 | 3 | 112 | yes |
| 480 | 30 | 5 | 3 | 449 | yes |
| 600 | 30 | 5 | 3 | 361 | yes |
| 600 | 30 | 5 | 3 | 230 | yes |
| 900 | 30 | 5 | 3 | 693 | yes |
| 900 | 30 | 5 | 3 | 186 | yes |
| 900 | 30 | 5 | 3 | 152 | yes |
| 1800 | 30 | 5 | 3 | 1644 | yes |
| 1800 | 30 | 5 | 3 | 855 | yes |
| 1800 | 30 | 5 | 3 | 1285 | yes |
| 1800 | 30 | 5 | 3 | 801 | yes |

So two things seem clear from looking at those timings:
1. My initial suspicion that the first call of the probe comes after the first `periodSeconds` interval elapses if `periodSeconds` is relatively large **appears to be invalid** (see `within_first_period` in the tables above).
2. I would have expected that the first call to the readiness probe would return very soon after `initialDelaySeconds` elapses, i.e. at most, just after
   ```
   `initialDelaySeconds` + (`timeoutSeconds` * `failureThreshold`)
   ```
    but this isn't usually the case, as witnessed. My understanding of `timeoutSeconds` and `failureThreshold` might be a little suspect, but I'd at least expect the probe to return shortly after its `initialDelaySeconds` elapses once the pod is deployed.

**Comment by philip-fox** [comment]
@zouyee
Hi Zou Nengren. Do you plan to progress this issue?

**Comment by zouyee** [comment]
I don't have time for a while, if you have plans to solve it，please carry on.

**Comment by philip-fox** [comment]
@mattjmcnaughton 
Hey Matt. Can this be assigned to someone who can take a look at it?

**Comment by mattjmcnaughton** [comment]
Hi @philip-fox ! It might be useful to see if anyone in the #sig-node slack channel has the interest/capacity to pick it up?

**Comment by alanorwick** [comment]
Hi! I'm a CS student in university. My group is interested in resolving this issue for a virtualization class assignment. Can we have this assigned to us?

**Comment by philip-fox** [comment]
@alanorwick Sure, that would be great, thanks!

**Comment by alanorwick** [comment]
We have submitted a [https://github.com/kubernetes/kubernetes/pull/85769](pull request) regarding this issue. @philip-fox do you think our changes are reasonable?

**Comment by samgoncalves90** [comment]
This bug remains at version 1.17, can be reopened? [85769](https://github.com/kubernetes/kubernetes/pull/85769)

**Comment by oaicstef** [comment]
Hi, I'm having the same issue, at the beginning I was thinking that it was happening due to a misconfiguration on my side but then I see that the behavior is not the one expected reading at the documentation. 
This is the second "closed" issue I found about the same problem, is anyone trying to solve it? It seems a real issue to me, a pod to be ready is taking around 3 to 5 minutes in my pipelines and this is not a nice behavior.

Please, can anyone help on the topic?
