### ISSUE TITLE
K8S Azure Cloud Provider doesn't not set enableTcpReset to true in load balancer rules for Azure Standard Load Blancer

### ISSUE THREAD

**Issue by xuto2** [kubernetes/kubernetes#80442]
**What happened**:
1. Create a k8s cluster backed by Azure Standard Load Balancer
2. Create a LoadBalancer type service and wait till the service is up
3. Go to Azure portal and examine the Azure Standard Load Balancer

The load balancer rule added by k8s cloud provider for the new service doesn't have a "true" value in enableTcpReset property

**What you expected to happen**:
A "true" value in the enableTcpReset property of the load balancer rule is expected.

**How to reproduce it (as minimally and precisely as possible)**:
See above.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.7
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Koderok** [comment]
As per Azure documentation on this feature (https://docs.microsoft.com/en-gb/azure/load-balancer/load-balancer-tcp-reset), this is only a preview feature and not recommended for production workloads. Is the ask to to enable this by default for all K8s deployments in Azure?

![Screen Shot 2019-07-22 at 5 20 32 PM](https://user-images.githubusercontent.com/1331160/61673616-0da4db80-aca5-11e9-87d8-5fb6579626f3.png)

**Comment by feiskyer** [comment]
Agreed with @Koderok. I think we should enable this feature by an annotation, and only enable it when the service has set the annotation. e.g. `service.beta.kubernetes.io/azure-load-balancer-enable-tcp-reset=true`

**Comment by xuto2** [comment]
updated the PR with service annotation as suggested - but confirmed from PM that this feature in network is technically GA, the only reason that it is not publicly announced is because the Azure portal change is not ready, based on this - do you think we will need to remove this annotation one day? if so, should we do it now? @feiskyer @Koderok
