### ISSUE TITLE
When I change hugepage size 2Mi to 1Gi，kubelet can't update node status

### ISSUE THREAD

**Issue by DeepLJH0001** [kubernetes/kubernetes#80452]
**What happened**:

- When I change default hugepage size 2Mi to 1Gi and reboot, kubelet can't update node status

```
[root@worker-01 ~]# cat /etc/default/grub
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto default_hugepagesz=1GB rhgb quiet idle=halt biosdevname=0 net.ifnames=0 console=tty0 console=ttyS0,115200n8 noibrs"
GRUB_DISABLE_RECOVERY="true"
```

```
E0723 03:23:36.757554    2183 kubelet_node_status.go:385] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"PIDPressure\"},{\"type\":\"Ready\"}],\"allocatable\":{\"devices.kubevirt.io/tun\":\"110\",\"devices.kubevirt.io/vhost-net\":\"110\",\"hugepages-1Gi\":\"16Gi\",\"memory\":\"0\"},\"capacity\":{\"devices.kubevirt.io/kvm\":\"110\",\"devices.kubevirt.io/tun\":\"110\",\"devices.kubevirt.io/vhost-net\":\"110\",\"hugepages-1Gi\":\"16Gi\"},\"conditions\":[{\"lastHeartbeatTime\":\"2019-07-23T03:23:36Z\",\"lastTransitionTime\":\"2019-07-23T03:23:36Z\",\"message\":\"kubelet has sufficient memory available\",\"reason\":\"KubeletHasSufficientMemory\",\"status\":\"False\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2019-07-23T03:23:36Z\",\"lastTransitionTime\":\"2019-07-23T03:23:36Z\",\"message\":\"kubelet has no disk pressure\",\"reason\":\"KubeletHasNoDiskPressure\",\"status\":\"False\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2019-07-23T03:23:36Z\",\"lastTransitionTime\":\"2019-07-23T03:23:36Z\",\"message\":\"kubelet has sufficient PID available\",\"reason\":\"KubeletHasSufficientPID\",\"status\":\"False\",\"type\":\"PIDPressure\"},{\"lastHeartbeatTime\":\"2019-07-23T03:23:36Z\",\"lastTransitionTime\":\"2019-07-23T03:23:36Z\",\"message\":\"kubelet is posting ready status\",\"reason\":\"KubeletReady\",\"status\":\"True\",\"type\":\"Ready\"}],\"nodeInfo\":{\"bootID\":\"35150190-4de9-46d8-b1f5-05dd0cface2b\"},\"volumesInUse\":null}}" for node "worker-01": Node "worker-01" is invalid: [status.capacity.hugepages-1Gi: Invalid value: resource.Quantity{i:resource.int64Amount{value:17179869184, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes, status.capacity.pods: Invalid value: resource.Quantity{i:resource.int64Amount{value:250, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"250", Format:"DecimalSI"}: may not have pre-allocated hugepages for multiple page sizes, status.capacity.devices.kubevirt.io/kvm: Invalid value: resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"110", Format:"DecimalSI"}: may not have pre-allocated hugepages for multiple page sizes, status.capacity.cpu: Invalid value: resource.Quantity{i:resource.int64Amount{value:12, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"12", Format:"DecimalSI"}: may not have pre-allocated hugepages for multiple page sizes, status.allocatable.hugepages-2Mi: Invalid value: resource.Quantity{i:resource.int64Amount{value:16030629888, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes, status.allocatable.devices.kubevirt.io/tun: Invalid value: resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"110", Format:"DecimalSI"}: may not have pre-allocated hugepages for multiple page sizes]

```

**What you expected to happen**:

- kubelet can update node info and node status was ready

**How to reproduce it (as minimally and precisely as possible)**:
- change the node condition validate

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
hyperkube
```
- OS (e.g: `cat /etc/os-release`):
```
centos 7.6
```
- Kernel (e.g. `uname -a`):
```
[root@worker-01 ~]# uname -a
Linux worker-01 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubevirt(It will import kvm tun device to kubelet，but i think it is not the reason)
```
- Network plugin and version (if this is a network-related bug):
```
canal
```
- Others:
```
[root@worker-01 ~]# cat /proc/meminfo
MemTotal:       24521676 kB
MemFree:         5402000 kB
MemAvailable:    6477760 kB
Buffers:          118828 kB
Cached:          1218632 kB
SwapCached:            0 kB
Active:           916956 kB
Inactive:        1043992 kB
Active(anon):     628436 kB
Inactive(anon):     1184 kB
Active(file):     288520 kB
Inactive(file):  1042808 kB
Unevictable:       13912 kB
Mlocked:           13912 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               992 kB
Writeback:             0 kB
AnonPages:        637432 kB
Mapped:           235740 kB
Shmem:              2052 kB
Slab:             120568 kB
SReclaimable:      61004 kB
SUnreclaim:        59564 kB
KernelStack:       19392 kB
PageTables:        17148 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3872228 kB
Committed_AS:    7299148 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       64008 kB
VmallocChunk:   34359569928 kB
HardwareCorrupted:     0 kB
AnonHugePages:    319488 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:      16
HugePages_Free:       16
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB
DirectMap4k:      145256 kB
DirectMap2M:     5097472 kB
DirectMap1G:    22020096 kB
```

**Comment by odinuge** [comment]
Hi,

Ref. the error message, it looks like you have allocated hugepages for multiple sizes, `may not have pre-allocated hugepages for multiple page sizes`.

Can you run: `cat /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages` to verify? If more than one of the numbers is `> 0`, that is the reason. @DeepLJH0001 

This is currently being discussed in https://github.com/kubernetes/kubernetes/issues/77251, and the reason for implementing the check is here: https://github.com/kubernetes/community/pull/837/files#r133337110.

Imo. this should be supported, and it would only require removing an if statement in order to implement it. I see no reason to limit the node from allocating huge pages with more than one size.

Because of how it is implemented, adding support for allowing a pod to request huge pages with multiple sizes isn't trivial, and will require some potentially breaking changes, but that is not relevant to this problem. 😄

/cc @mattjmcnaughton @derekwaynecarr

**Comment by odinuge** [comment]
Also, can you also provide the result of `ls /sys/kernel/mm/hugepages`, that will list the supported huge page sizes (both when `default_hugepagesz=1GB` is set, and when it is not.).

**Comment by DeepLJH0001** [comment]
@odinuge
```
[root@worker-01 ~]# cat /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages
16
[root@worker-01 ~]# ls /sys/kernel/mm/hugepages
hugepages-1048576kB
```

**Comment by odinuge** [comment]
Thanks @DeepLJH0001 !

Looks like your kernel only enables huge pages with the default size. My kernel 5.0+ enable all (atleast 2MiB and 1GiB on x86_64) by default.

When the node booted with default_hugepagesz=1GB it "removed support" the 2MiB one, and becuse kubelet use patch on the node status when connecting to the api server, you ended up with both `hugepages-1Gi` and `hugepages-2Mi`, even tho 2Mi wast supported by your machine (the sw, not the hw). Even if the `may not have pre-allocated hugepages for multiple page sizes` error is removed, this will result in a crash when kubelet tries to write to the 2MiB hugetlb cgroup files.

I think using `default_hugepagesz=1G hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=0` should work, otherwise the only current solution is to remove the node from the cluster, and rejoin afterwords.

Ref. https://github.com/kubernetes/kubernetes/issues/80576 it looks like you have sorted out the problem, but I still think this is a valid issue, so don't close it.


The correct behaviour for kubelet is to remove unsupported sizes, and only allow use of the supported ones.

**Comment by soohoon** [comment]
"Imo. this should be supported, and it would only require removing an if statement in order to implement it. I see no reason to limit the node from allocating huge pages with more than one size."

Could you fix this one as well?
We use 2M pages only for pods but we need 1G pages for system processes.
So it was little surprising when k8s doesn't start because two different pages were configured no matter they are really used or not.
Thanks!

**Comment by yrobla** [comment]
I am hitting the same, I used tuned to change the default size from 2Mi to 1Gi, i hit the same problem, after the reboot node is NotReady and it cannot rejoin , giving the error:
 Node "test-worker-0" is invalid: [status.capacity.hugepages-2Mi: Invalid value: resource.Quantity{i:resource.int64Amount{value:20971520, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"20Mi", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes, status.allocatable.hugepages-2Mi: Invalid value: resource.Quantity{i:resource.int64Amount{value:20971520, scale:0}, 
My system just reports information for 1Gi, not 2Mi anymore.
Removing the node and rebooting fixed it, the node rejoined again reporting the right capacity. But this is not a solution for us, changing sizes should be supported.

**Comment by mJace** [comment]
Hitting same

K8s installed with my ubuntu 18 enabled 2Mi hugepage by default.
As I change my master node's hugepage to 1Gi, this happened.

I have only one master, so I have to rebuild the k8s cluster.

**Comment by andy-wolf168** [comment]
> Thanks @DeepLJH0001 !
> 
> Looks like your kernel only enables huge pages with the default size. My kernel 5.0+ enable all (atleast 2MiB and 1GiB on x86_64) by default.
> 
> When the node booted with default_hugepagesz=1GB it "removed support" the 2MiB one, and becuse kubelet use patch on the node status when connecting to the api server, you ended up with both `hugepages-1Gi` and `hugepages-2Mi`, even tho 2Mi wast supported by your machine (the sw, not the hw). Even if the `may not have pre-allocated hugepages for multiple page sizes` error is removed, this will result in a crash when kubelet tries to write to the 2MiB hugetlb cgroup files.
> 
> I think using `default_hugepagesz=1G hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=0` should work, otherwise the only current solution is to remove the node from the cluster, and rejoin afterwords.
> 
> Ref. #80576 it looks like you have sorted out the problem, but I still think this is a valid issue, so don't close it.
> 
> The correct behaviour for kubelet is to remove unsupported sizes, and only allow use of the supported ones.

@odinuge @DeepLJH0001 @neolit123 
I'm a little confused. when i used tuned to change the hugepagesz from 2Mi to 1Gi, i hit the same problem, after the reboot node is NotReady，but  when i used tuned to change the hugepagesz from 1Gi to 2Mi, after the reboot，kubelet status can still keep Ready.  why?

**Comment by odinuge** [comment]
Hi @andy-wolf168,

This will be fixed in #80831, but it is still not merged. Hoping to get it into next release.

In order to solve the issue (and use 1GiB huge pages) you have to delete the node in kubernetes via `kubectl delete node <name>`, and join the node again.

**Comment by andy-wolf168** [comment]
Thanks @odinuge

**Comment by andy-wolf168** [comment]
Thanks @odinuge

**Comment by bart0sh** [comment]
@DeepLJH0001 I think this is already fixed by https://github.com/kubernetes/kubernetes/pull/82820.
@odinuge can you confirm?

**Comment by odinuge** [comment]
Hi @bart0sh 

WIth #82820 this would not cause a crash, but https://github.com/kubernetes/kubernetes/pull/80831 is still required in order to fix this properly.

**Comment by Sarang-Sangram** [comment]
I am facing the same issue. After changing the hugepage setting to `default_hugepagesz=1G hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=0` . I stopped the kubelet process on the worker node and removed the node from the cluster using command `kubectl delete node node4` and rebooted it. 
But after it comes back online and kubelet starts, it struggles to join the cluster . 
```
host4 kubelet[9234]: E0316 02:41:34.186493    9234 kubelet.go:2263] node "host4" not found
Mar 16 02:41:34 host4 kubelet[9234]: I0316 02:41:34.250264    9234 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Mar 16 02:41:34 host4 kubelet[9234]: E0316 02:41:34.286740    9234 kubelet.go:2263] node "host4" not found
Mar 16 02:41:34 host4 kubelet[9234]: E0316 02:41:34.387072    9234 kubelet.go:2263] node "host4" not found
Mar 16 02:41:34 host4 kubelet[9234]: I0316 02:41:34.401295    9234 kubelet_node_status.go:70] Attempting to register node host4
Mar 16 02:41:34 host4 kubelet[9234]: E0316 02:41:34.404777    9234 kubelet_node_status.go:92] Unable to register node "host4" with API server: Node "host4" is invalid: [status.capacity.hugepages-2Mi: Invalid value: resource.Quantity{i:resource.int64Amount{value:268435456, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes, status.capacity.memory: Invalid value: resource.Quantity{i:resource.int64Amount{value:540977541120, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"528298380Ki", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes, status.capacity.pods: Invalid value: resource.Quantity{i:resource.int64Amount{value:110, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"110", Format:"DecimalSI"}: may not have pre-allocated hugepages for multiple page sizes, status.allocatable.hugepages-2Mi: Invalid value: resource.Quantity{i:resource.int64Amount{value:268435456, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes, status.allocatable.memory: Invalid value: resource.Quantity{i:resource.int64Amount{value:6954561536, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"6791564Ki", Format:"BinarySI"}: may not have pre-allocated hugepages for multiple page sizes]
Mar 16 02:41:34 host4 kubelet[9234]: E0316 02:41:34.487421    9234 kubelet.go:2263] node "host4" not found
```

Do I have to run the join command again ?
