### ISSUE TITLE
Could not compile generated informer with +genclient:nonNamespaced

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#80457]
**What happened**:

if I annotate non namespaced CRD type like this:

```go
// ...
// +genclient                                                                                                                                                                     
// +genclient:nonNamespaced                                                                                                                                                       
// ...
type Foo struct {
...
```

informer-gen generates code which cannot compile:

```
unknown field 'namespace' in struct literal of type fooInformer
```

It looks like nonNamspaced tag is not respected somewhere.

**What you expected to happen**:

Generated code should compile just fine.

**How to reproduce it (as minimally and precisely as possible)**:

See what happened.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yliaog** [comment]
i think the root cause of the issue is the missing blank line between the tag "// +genclient                                                                                                                                                                     
// +genclient:nonNamespaced " and the type def "type Foo struct {"

if you add a blank line, the informer would be generated correctly.

**Comment by tatsuhiro-t** [comment]
I disagree.  The other generators can handle this without extra blank lines.  Actually, informer-gen partially handles this except for the broken portion which #80458 tries to fix.
Leaving generator tool like this in inconsistent state is huge UX regression.   This is clearly a bug to me.

**Comment by trierra** [comment]
I have a similar issue. Getting the following error, despite `+genclient:nonNamespaced` annotation:
```
 "unit-test-rule" is invalid: metadata.namespace: Required value
```

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/pull/80458 should fix it, @trierra could you try it?

**Comment by trierra** [comment]
sure, thank you
