### ISSUE TITLE
Kubectl api does not shows the correct uptime of pods even when docker daemon is restarted

### ISSUE THREAD

**Issue by Bipin143** [kubernetes/kubernetes#80464]
I have observed that the value of age in kubectl get pods does not shows the correct age (uptime) value of pods even when the underlying docker daemon is restarted which effectively also restarts the required daemon.

@kubernetes/sig-node-bugs
we have the below pods running.
NAMESPACE     NAME                                                              READY   STATUS    RESTARTS   AGE
default       cstor-sparse-pool-5wtc-6f6d94b966-6xkpt                           3/3     Running   6          40d
default       cstor-sparse-pool-aes1-56f97f976d-twzkr                           3/3     Running   0          43d
default       cstor-sparse-pool-wr7n-699bb78989-lpzkk                           3/3     Running   0          43d
default       jenkins2-64d88d4796-ddvc5                                         1/1     Running   0          40d
default       knotted-yak-openebs-admission-server-6cc4869948-hz8bk             1/1     Running   0          40d
default       knotted-yak-openebs-apiserver-65cc4dcddf-psf4d                    1/1     Running   0          40d
default       knotted-yak-openebs-localpv-provisioner-76c955cd97-nrq2p          1/1     Running   37         40d
default       knotted-yak-openebs-ndm-2qqk6                                     1/1     Running   2          59d
default       knotted-yak-openebs-ndm-8p5z4                                     1/1     Running   0          59d
default       knotted-yak-openebs-ndm-wgw9d                                     1/1     Running   0          59d
default       knotted-yak-openebs-provisioner-7db95d4bdd-4lmmp                  1/1     Running   45         40d
default       knotted-yak-openebs-snapshot-operator-8fddb8475-rqxcv             2/2     Running   42         40d
default       pvc-95bdced7-8082-11e9-8197-02f7c3aedc48-target-687b7b559cq56rz   3/3     Running   0          40d
default       redis-6445bbbff6-gxs5v                                            1/1     Running   2          28m
kube-system   coredns-fb8b8dccf-qqw67                                           1/1     Running   186        59d
kube-system   coredns-fb8b8dccf-vb8d4                                           1/1     Running   189        59d
kube-system   etcd-cs-prd-cicd-mas-4                                            1/1     Running   45         59d
kube-system   kube-apiserver-cs-prd-cicd-mas-4                                  1/1     Running   146        59d
kube-system   kube-controller-manager-cs-prd-cicd-mas-4                         1/1     Running   516        59d
kube-system   kube-proxy-7ds2b                                                  1/1     Running   0          59d
kube-system   kube-proxy-kvw8n                                                  1/1     Running   3          59d
kube-system   kube-proxy-lnvsg                                                  1/1     Running   0          59d
kube-system   kube-proxy-x5v9k                                                  1/1     Running   4          59d
kube-system   kube-scheduler-cs-prd-cicd-mas-4                                  1/1     Running   500        59d
kube-system   tiller-deploy-85494c96cf-xsstl                                    1/1     Running   0          40d
kube-system   weave-net-77fsd                                                   2/2     Running   10         59d
kube-system   weave-net-ctjkc                                                   2/2     Running   7          59d
kube-system   weave-net-m2b52                                                   2/2     Running   0          59d
kube-system   weave-net-nxjn9                                                   2/2     Running   1          59d
openebs       maya-apiserver-6645c46687-jzdp5                                   1/1     Running   0          40d
openebs       openebs-provisioner-6ddb988659-bk79w                              1/1     Running   43         40d
openebs       openebs-snapshot-operator-787999b887-vkg6f                        2/2     Running   41         40d
openebs       pvc-95bdced7-8082-11e9-8197-02f7c3aedc48-target-f968f6788-2z6vc   3/3     Running   0          40d

we have then stopped docker daemon in one of the nodes where redis was running.
all the container restarted when the docker daemon was started again.
however when we checked the pods status again it did not show the correct age of the pods that would indicate its been recently started.

**Comment by zouyee** [comment]
```
// ensure that the start time does not change across updates.
	if oldStatus.StartTime != nil && !oldStatus.StartTime.IsZero() {
		status.StartTime = oldStatus.StartTime
```
