### ISSUE TITLE
PVC protection controller can fail to remove finalizer from PVC even if no pod is using it

### ISSUE THREAD

**Issue by matte21** [kubernetes/kubernetes#80475]
**What happened**:
While studying https://github.com/kubernetes/kubernetes/blob/255a73ffc64d1c4e0f9a378ebf8d0005edfe6962/pkg/controller/volume/pvcprotection/pvc_protection_controller.go to address https://github.com/kubernetes/kubernetes/issues/75980 I noticed another error. When the PVC protection controller receives an update notification for a pod, it enqueues all the PVCs referenced by the new version of the Pod, and it ignores the old version of the pod:
https://github.com/kubernetes/kubernetes/blob/255a73ffc64d1c4e0f9a378ebf8d0005edfe6962/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L87-L89
That is fine as long as the two versions are for the same Pod. But if the update notification masks a delete followed by a create with the same namespaced name and the deleted Pod was blocking deletion of a PVC which is not referenced by the new Pod the finalizer will incorrectly not be removed from the PVC, which in turn will not be deleted even if no pod is using it.  

**What you expected to happen**:
I expected https://github.com/kubernetes/kubernetes/blob/255a73ffc64d1c4e0f9a378ebf8d0005edfe6962/pkg/controller/volume/pvcprotection/pvc_protection_controller.go to examine the PVCs referenced by a deleted pod even if the deletion is conflated with a creation in a single update event.

**Anything else we need to know?**:

**Comment by matte21** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
Were you able to reproduce this issue in a real cluster? I thought that the controller gets "pod deleted" and "pod created" events when a pod is deleted and re-created with a different UID even in the worst conditions.

**Comment by matte21** [comment]
No, I did not try to reproduce it in a real cluster.
However, this code suggests that delete and create events can be delivered via a single update: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/node/graph_populator.go#L142.

I've just asked in the sig-api-machinery slack channel: https://kubernetes.slack.com/archives/C0EG7JC6T/p1563896302039300

**Comment by MikeSpreitzer** [comment]
I answered there.  And I submitted a PR to hopefully make it clearer: #80565

**Comment by MikeSpreitzer** [comment]
@jsafrane : so the controller is _not_ guaranteed to get pod delete and create notifications in the case of a deletion and replacement creation; it is possible that the controller just gets a pod update notification.
