### ISSUE TITLE
kube-init: Easiest way to deploy a cluster for learning

### ISSUE THREAD

**Issue by arunoda** [kubernetes/kubernetes#8048]
Hi,

I recently did a [lesson](https://bulletproofmeteor.com/architecture/deploying-meteor-apps-into-a-kubernetes-cluster) on kubernetes for BulletProof Meteor. I want my users to play around with Kubernetes and learn about Kubernetes. Frankly, deploying a cluster your own is not yet easy. GKE is nice, but I want them to try using any cloud.

So, I built kube init: https://github.com/meteorhacks/kube-init

It's a way to run Kubernetes cluster on a single server. (it's based on hyperkube. may be we don't need hypekube at all). It also comes with the skydns configured too. 

Deploying the cluster is easy: `wget -qO- http://git.io/veKlu | sudo sh` 

Then I ask users to create a SOCKS proxy into the box and they can access pods and services locally.

This is never meant to be a production cluster. But, users could experiment with the cluster without worrying about deploying and configuring a cluster.

Hope this helps.

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @brendandburns

**Comment by mikedanese** [comment]
cc @vishh @pwittrock
