### ISSUE TITLE
Duplicate HPA CPU metrics dropped during conversion

### ISSUE THREAD

**Issue by josephburnett** [kubernetes/kubernetes#80481]
**What happened**:

HPA v2beta2 allows for scaling on multiple metrics, specified in a list. Duplicate metrics (e.g. same metric, different value) are not filtered out.  Except for CPU.  As a by-product of v1<-->v2 conversion, only the first CPU metric encountered is preserved.

https://github.com/kubernetes/kubernetes/blob/fdb5707194d56cbbd0da11c5be3a2a5653e714c9/pkg/apis/autoscaling/v1/conversion.go#L298-L309

This is confusing because other duplicate metrics such as memory are preserved.  It forces a user or UI to consider this special case.

**What you expected to happen**:

The first CPU metric should be converted and all additional CPU metrics should be serialized into annotations (`otherMetrics`) and preserved.

**How to reproduce it (as minimally and precisely as possible)**:

1. [Create an HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)
2. Edit the HPA with `kubectl edit hpa.v2beta2.autoscaling php-apache`
3. Add an additional CPU entry and two memory metric with different targets.
5. Get the HPA again and both memory metrics will be present.  However only one CPU metric will be present.

**Anything else we need to know?**:

/sig autoscaling

**Comment by josephburnett** [comment]
We should probably add some round-trip conversion tests.  E.g. here: https://github.com/kubernetes/kubernetes/blob/809eaa7025119712ca82c6f4dfa73a4a544ad7ec/pkg/apis/autoscaling/v2beta1/conversion_test.go

**Comment by josephburnett** [comment]
/unassign @loqutus 

I haven't seen any progress or updates on this, so I'm unassigning.  It's a good first issue for someone.  @loqutus please reassign if you are in fact working on this.  Thanks!

**Comment by ArturoTarinVillaescusa** [comment]
Thank you Joe!

Just for documentation, let me share my document [Debugging Issue # 80481: Duplicate HPA CPU metrics dropped during conversion](https://docs.google.com/document/d/1Q2GDaTvrcfzRxk1MdLuBsWaLr7OHzELYiWWYXCAXUGc).

This is a detailed document with the research that I've done, trying to debug the Kubernetes code to find the exact point when the issue arises.

I haven't find it yet, but I'll keep trying until I find it. I'm also working in the round-trip conversion tests that you suggested, I'll ask you for a pull request about them soon.

**Comment by tedyu** [comment]
Thanks @ArturoTarinVillaescusa for the detailed doc.

If possible, it would be nice to enhance the snapshot images with filename and line number - the snapshot is not as readable as text.

**Comment by ArturoTarinVillaescusa** [comment]
Hello @tedyu 

thank you for your feedback, I really appreciate your interest, and your highlight about the quality of the document. 

Please, find attached the document in several splitted pdf parts, Github does not allow uploading files greater than 10MB:

[PART 01 - Issue # 80481_ Duplicate HPA CPU metrics dropped during conversion.pdf](https://github.com/kubernetes/kubernetes/files/3613446/PART.01.-.Issue.80481_.Duplicate.HPA.CPU.metrics.dropped.during.conversion.pdf)

[PART 02 - Issue # 80481_ Duplicate HPA CPU metrics dropped during conversion.pdf](https://github.com/kubernetes/kubernetes/files/3613445/PART.02.-.Issue.80481_.Duplicate.HPA.CPU.metrics.dropped.during.conversion.pdf)

[PART 03 - Issue # 80481_ Duplicate HPA CPU metrics dropped during conversion.pdf](https://github.com/kubernetes/kubernetes/files/3613444/PART.03.-.Issue.80481_.Duplicate.HPA.CPU.metrics.dropped.during.conversion.pdf)

[PART 04 - Issue # 80481_ Duplicate HPA CPU metrics dropped during conversion.pdf](https://github.com/kubernetes/kubernetes/files/3613448/PART.04.-.Issue.80481_.Duplicate.HPA.CPU.metrics.dropped.during.conversion.pdf)

[PART 05 - Issue # 80481_ Duplicate HPA CPU metrics dropped during conversion.pdf](https://github.com/kubernetes/kubernetes/files/3613449/PART.05.-.Issue.80481_.Duplicate.HPA.CPU.metrics.dropped.during.conversion.pdf)


Also, if you  need the original I can send it by email, or if your prefer I can share an editable Google Drive version here.

**Comment by wuyafang** [comment]
I‘m confused. Why do we need dullicate HPA CPU metrics/ memory metrics?

**Comment by ArturoTarinVillaescusa** [comment]
> I‘m confused. Why do we need duplicate HPA CPU metrics/ memory metrics?

Hello @wuyafang ,

as per my understanding, we need it if we want to have more than one threshold for the same metric. Let's say we want our Kubernetes engine to take some action when we arrive to the 30% of CPU capacity consumption, but some other action when this metric reaches 60%.

Mr. @josephburnett, could you please confirm whether I'm right or wrong on it?

Kind Regards

Arturo

**Comment by josephburnett** [comment]
@pbaderia01 and update on this?

**Comment by pbaderia01** [comment]
Hey @josephburnett. Apologise for not being able to get back to you earlier, this is turning out to be a little more tricky than I expected. I'm working on this and will work on this over this weekend as well and will get back to you to see what should be the next steps either way.

**Comment by pbaderia01** [comment]
There are multiple things I tried but unfortunately there wasn't anything I could add to the amazingly detailed documentation already created by @ArturoTarinVillaescusa. So I'm unassigning myself from this issue. 

@supriya-premkumar If you're still interested maybe you'd like to take a look at it?

**Comment by josephburnett** [comment]
Hey @AbdulBasitAlvi have you been able to work on this?

**Comment by AbdulBasitAlvi** [comment]
> Hey @AbdulBasitAlvi have you been able to work on this?

Yes. Apologies for the delay, I will give an update shortly
