### ISSUE TITLE
Add resourceLockName options to leader election

### ISSUE THREAD

**Issue by ricky1993** [kubernetes/kubernetes#80510]
**What would you like to be added**:
Add a options to set resource-lock-name for leader election
**Why is this needed**:
Think about this scenario: we want to split some controllers out of controller manager and deploy it isolated. It also needs leader election for ha. But now they will use the same resource-lock-name, we need to set it to a different from kube-controller-manager.
And it is the same issue for scheduler.

**Comment by ricky1993** [comment]
@yue9944882 PTAL

**Comment by yue9944882** [comment]
what's the point of separating locks? or rather, which controller are you trying to separate from KCM? i presume separating controllers into multiple processes can lead to cache inconsistency, b/c in a single KCM process all controllers are reading from the same cache per resource. i noticed in scheduler, overriding lock name is already supported by #42961. @liggitt for thoughts

**Comment by ricky1993** [comment]
We deploy job/cronjob/daemonset controller out of KCM. Because our cluster scale is too large and KCM is often overloaded. I don't think it's a big risk if they have inconsistent cache.

**Comment by yue9944882** [comment]
/sig scalability 

@wojtek-t

**Comment by roycaihw** [comment]
cc @cheftako @andrewsykim

**Comment by andrewsykim** [comment]
We are proposing a _very_ similar thing here https://github.com/kubernetes/enhancements/pull/979 but it's specifically for the cloud provider migration case. It should be extendable to other use-cases but needs a bit more consideration there. PTAL

**Comment by liggitt** [comment]
> i noticed in scheduler, overriding lock name is already supported by #42961. @liggitt for thoughts

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go#L93-L94 already supports choosing a lock name. scheduler plumbs a flag to that. {kube,cloud}-controller-manager currently don't.

> i presume separating controllers into multiple processes can lead to cache inconsistency, b/c in a single KCM process all controllers are reading from the same cache per resource.

controller loops run asynchronously and independently. running them in separate processes would not be as efficient, but should not cause consistency issues.

**Comment by ricky1993** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go#L93-L94 already supports choosing a lock name. scheduler plumbs a flag to that. {kube,cloud}-controller-manager currently don't.

Do you think this flag make sense for CM?

> controller loops run asynchronously and independently. running them in separate processes would not be as efficient, but should not cause consistency issues.

I understand they run independently. Running them in separate processes can isolated the cpu and memory resource.

**Comment by liggitt** [comment]
> Do you think this flag make sense for CM?

since we allow running subsets of controllers with `--controllers`, probably so

**Comment by andrewsykim** [comment]
@ricky1993 I'm curious how exactly you are setting the `--controllers` flags, cause in some scenarios if we add new controllers in `kube-controller-manager` you could miss it.

**Comment by ricky1993** [comment]
@andrewsykim We set --controllers=*,-foo,-bar at main kcm. And --controllers=foo,bar at the seperated kcms. I think it would not miss new controllers because * is a wildcard to match it.

**Comment by andrewsykim** [comment]
Thanks for clarifying!
