### ISSUE TITLE
TestVolumeProvision test is flaky again

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#80528]
**Which jobs are failing**:
pull-kubernetes-integration

**Which test(s) are failing**:
TestVolumeProvision

**Since when has it been failing**:
Noticed it since 2019-07-24. But [this closed issue](https://github.com/kubernetes/kubernetes/issues/70180) also has it.

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80383/pull-kubernetes-integration/1154021402995593217/

**Reason for failure**:
Not sure.

**Anything else we need to know**:

**Comment by congliu01** [comment]
The test is [here](https://github.com/kubernetes/kubernetes/blob/2cd5fc54a10623c30b257f904244d560f1fad9a0/test/integration/scheduler/volume_binding_test.go#L688) under scheduler integ tests. So this could be a sig Scheduling issue.

**Comment by bsalamat** [comment]
SIG Storage owns volume provisioning, although parts of it is integrated in the scheduler.

**Comment by liggitt** [comment]
this is the flakiest test in the integration suite per http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by bsalamat** [comment]
cc/ @msau42

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures 
/assign @msau42 @cofyc

**Comment by msau42** [comment]
Is there a way to get test results history? I can only see the last 3 days here:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=VolumeProvision&width=5

**Comment by ddebroy** [comment]
Here are some very recent failures I found:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80864/pull-kubernetes-integration/1156947559839698945/
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80587/pull-kubernetes-integration/1156953468238303232

**Comment by ddebroy** [comment]
```
I0801 16:15:00.309] === FAIL: test/integration/scheduler TestVolumeProvision (608.25s)
I0801 16:15:00.309] W0801 16:14:30.187303  110415 feature_gate.go:208] Setting GA feature gate PersistentLocalVolumes=true. It will be removed in a future release.
I0801 16:15:00.309] I0801 16:14:30.187323  110415 feature_gate.go:216] feature gates: &{map[PersistentLocalVolumes:true TaintNodesByCondition:true]}
I0801 16:15:00.310] I0801 16:14:30.188920  110415 services.go:33] Network range for service cluster IPs is unspecified. Defaulting to {10.0.0.0 ffffff00}.
I0801 16:15:00.310] I0801 16:14:30.189106  110415 services.go:45] Setting service IP to "10.0.0.1" (read-write).
I0801 16:15:00.310] I0801 16:14:30.189189  110415 master.go:278] Node port range unspecified. Defaulting to 30000-32767.
skipped 2518 lines unfold_more
I0801 16:15:00.748] I0801 16:14:38.763183  110415 httplog.go:90] GET /api/v1/namespaces/volume-scheduling41877c9e-1ad3-42b9-a525-b6ab936af34e/pods/pod-i-pv-prebound-w-provisioned: (2.153027ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:39246]
I0801 16:15:00.748] I0801 16:14:38.863367  110415 httplog.go:90] GET /api/v1/namespaces/volume-scheduling41877c9e-1ad3-42b9-a525-b6ab936af34e/pods/pod-i-pv-prebound-w-provisioned: (2.2319ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:39246]
I0801 16:15:00.748] I0801 16:14:38.963189  110415 httplog.go:90] GET /api/v1/namespaces/volume-scheduling41877c9e-1ad3-42b9-a525-b6ab936af34e/pods/pod-i-pv-prebound-w-provisioned: (2.148781ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:39246]
I0801 16:15:00.748] I0801 16:14:39.063200  110415 httplog.go:90] GET /api/v1/namespaces/volume-scheduling41877c9e-1ad3-42b9-a525-b6ab936af34e/pods/pod-i-pv-prebound-w-provisioned: (2.102439ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:39246]
I0801 16:15:00.749] I0801 16:14:39.163009  110415 httplog.go:90] GET /api/v1/namespaces/volume-scheduling41877c9e-1ad3-42b9-a525-b6ab936af34e/pods/pod-i-pv-prebound-w-provisioned: (2.027251ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:39246]
I0801 16:15:00.749] panic: test timed out after 10m0s
```

**Comment by liggitt** [comment]
I think the package is simply taking too long (there's a 10 minute per package limit, which is already very generous)

Picking a few successful runs, the package is hovering around the 10 minute mark:

test/integration/scheduler (9m46.46s)
test/integration/scheduler (9m49.172s)
test/integration/scheduler (9m46.085s)

**Comment by liggitt** [comment]
| Seconds | Test |
|---|---|
| 5.93 | TestSchedulerExtender |
| 5.05 | TestPrefilterPlugin |
| 5.01 | TestScorePlugin |
| 5.05 | TestNormalizeScorePlugin |
| 5.04 | TestReservePlugin |
| 5.18 | TestPrebindPlugin |
| 5.08 | TestUnreservePlugin |
| 5.49 | TestBindPlugin |
| 5.15 | TestPostbindPlugin |
| 11.34 | TestPermitPlugin |
| 5.15 | TestCoSchedulingWithPermitPlugin |
| 34.99 | TestFilterPlugin |
| 5.58 | TestPreemptWithPermitPlugin |
| 7.08 | TestInterPodAffinity |
| 4.85 | TestNodePIDPressure |
| 0.45 | TestEvenPodsSpreadPredicate/place_pod_on_a_1/1/0/1_cluster_with_MaxSkew=1,_node-2_is_the_only_fit |
| 0.45 | TestEvenPodsSpreadPredicate/place_pod_on_a_2/0/0/1_cluster_with_MaxSkew=2,_node-{1,2,3}_are_good_fits |
| 0.34 | TestEvenPodsSpreadPredicate/pod_is_required_to_be_placed_on_zone0,_so_only_node-1_fits |
| 0.56 | TestEvenPodsSpreadPredicate/two_constraints:_pod_can_only_be_placed_to_zone-1/node-2 |
| 0.68 | TestEvenPodsSpreadPredicate/pod_cannot_be_placed_onto_any_node |
| 1.98 | TestEvenPodsSpreadPredicate/high_priority_pod_can_preempt_others |
| 9.77 | TestEvenPodsSpreadPredicate |
| 8.74 | TestPreemption |
| 9.91 | TestDisablePreemption |
| 7.7 | TestPreemptionStarvation |
| 24.16 | TestPreemptionRaces |
| 6.5 | TestNominatedNodeCleanUp |
| 18.19 | TestPDBInPreemption |
| 4.96 | TestNodeAffinity |
| 5.64 | TestPodAffinity |
| 4.87 | TestImageLocality |
| 0.8 | TestEvenPodsSpreadPriority/place_pod_on_a_~0~/1/2/3_cluster_with_MaxSkew=1,_node-1_is_the_preferred_fit |
| 0.91 | TestEvenPodsSpreadPriority/combined_with_hardSpread_constraint_on_a_~4~/0/1/2_cluster |
| 6.99 | TestEvenPodsSpreadPriority |
| 4.12 | TestSchedulerCreationFromConfigMap |
| 3.52 | TestSchedulerCreationFromNonExistentConfigMap |
| 14.63 | TestUnschedulableNodes |
| 10.18 | TestMultiScheduler |
| 9.84 | TestAllocatable |
| 5.1 | TestSchedulerInformers |
| 1.58 | TestTaintNodeByCondition/not-ready_node |
| 1.56 | TestTaintNodeByCondition/unschedulable_node |
| 1.7 | TestTaintNodeByCondition/memory_pressure_node |
| 1.68 | TestTaintNodeByCondition/disk_pressure_node |
| 1.56 | TestTaintNodeByCondition/network_unavailable_and_node_is_ready |
| 1.68 | TestTaintNodeByCondition/network_unavailable_and_node_is_not_ready |
| 1.57 | TestTaintNodeByCondition/pid_pressure_node |
| 1.11 | TestTaintNodeByCondition/multi_taints_on_node |
| 18.58 | TestTaintNodeByCondition |
| 53.96 | TestVolumeBinding |
| 13.63 | TestVolumeBindingRescheduling |
| 55.03 | TestVolumeBindingStress |
| 36.5 | TestVolumeBindingStressWithSchedulerResync |
| 20.22 | TestVolumeBindingDynamicStressFast |
| 50.21 | TestVolumeBindingDynamicStressSlow |
| 7.72 | TestVolumeBindingWithAntiAffinity |
| 8.23 | TestVolumeBindingWithAffinity |
| 20.48 | TestPVAffinityConflict |
| 25.75 | TestVolumeProvision |
| 5.04 | TestRescheduleProvisioning |

**Comment by msau42** [comment]
I can look into moving the volume scheduling tests into a separate package. It seems like they take the most time

**Comment by liggitt** [comment]
thanks. that also explains why TestVolumeProvision and TestRescheduleProvisioning were the ones that flaked, since they ran last

**Comment by msau42** [comment]
What I would be curious to see is if these times have increased recently.  There have been changes made to the volume scheduling over the last month or so

**Comment by liggitt** [comment]
looks like it was mostly new tests added

delta from 1.15.0 (mid-june) to master:

| v1.15.0                                                            | master | delta |     |
|--------------------------------------------------------------------|--------|-------|-----|
| TestSchedulerExtender                                              | 6      | 6     | 0   |
| TestPrefilterPlugin                                                |        | 5     | 5   |
| TestScorePlugin                                                    |        | 5     | 5   |
| TestNormalizeScorePlugin                                           |        | 5     | 5   |
| TestReservePlugin                                                  | 5      | 5     | 0   |
| TestPrebindPlugin                                                  | 5      | 5     | 0   |
| TestUnreservePlugin                                                | 5      | 5     | 0   |
| TestPostbindPlugin                                                 | 5      | 6     | 1   |
| TestPostbindPlugin                                                 |        | 5     | 5   |
| TestPermitPlugin                                                   | 11     | 11    | 0   |
| TestCoSchedulingWithPermitPlugin                                   | 5      | 5     | 0   |
| TestFilterPlugin                                                   |        | 35    | 35  |
| TestPreemptWithPermitPlugin                                        |        | 5     | 5   |
| TestInterPodAffinity                                               | 7      | 7     | 0   |
| TestNodePIDPressure                                                | 5      | 5     | 0   |
| TestEvenPodsSpreadPredicate/place_pod_on_a_1                       |        | 0     | 0   |
| TestEvenPodsSpreadPredicate/place_pod_on_a_2                       |        | 0     | 0   |
| TestEvenPodsSpreadPredicate/pod_is_required                        |        | 0     | 0   |
| TestEvenPodsSpreadPredicate/two_constraints                        |        | 1     | 1   |
| TestEvenPodsSpreadPredicate/pod_cannot_be_placed                   |        | 1     | 1   |
| TestEvenPodsSpreadPredicate/high_priority_pod                      |        | 2     | 2   |
| TestEvenPodsSpreadPredicate                                        |        | 10    | 10  |
| TestPreemption                                                     | 9      | 9     | 0   |
| TestDisablePreemption                                              | 10     | 10    | 0   |
| TestPreemptionStarvation                                           | 6      | 8     | 1   |
| TestPreemptionRaces                                                | 35     | 35    | 0   |
| TestNominatedNodeCleanUp                                           | 6      | 7     | 0   |
| TestPDBInPreemption                                                | 19     | 18    | 0   |
| TestNodeAffinity                                                   | 5      | 5     | 0   |
| TestPodAffinity                                                    | 6      | 5     | 0   |
| TestImageLocality                                                  | 5      | 5     | 0   |
| TestEvenPodsSpreadPriority/place_pod_on                            |        | 1     | 1   |
| TestEvenPodsSpreadPriority/combined_with                           |        | 1     | 1   |
| TestEvenPodsSpreadPriority                                         |        | 7     | 7   |
| TestSchedulerCreationFromConfigMap                                 | 4      | 4     | 0   |
| TestSchedulerCreationFromNonExistentConfigMap                      | 3      | 4     | 0   |
| TestUnschedulableNodes                                             | 15     | 15    | 0   |
| TestMultiScheduler                                                 | 10     | 10    | 0   |
| TestAllocatable                                                    | 10     | 10    | 0   |
| TestSchedulerInformers                                             | 5      | 5     | 0   |
| TestTaintNodeByCondition/not-ready_node                            | 2      | 2     | 0   |
| TestTaintNodeByCondition/unschedulable_node                        | 2      | 2     | 0   |
| TestTaintNodeByCondition/memory_pressure_node                      | 2      | 2     | 0   |
| TestTaintNodeByCondition/disk_pressure_node                        | 2      | 2     | 0   |
| TestTaintNodeByCondition/...node_is_ready     | 2      | 2     | 0   |
| TestTaintNodeByCondition/...node_is_not_ready | 2      | 2     | 0   |
| TestTaintNodeByCondition/pid_pressure_node                         | 2      | 2     | 0   |
| TestTaintNodeByCondition/multi_taints_on_node                      | 1      | 1     | 0   |
| TestTaintNodeByCondition                                           | 18     | 19    | 0   |
| TestVolumeBinding                                                  | 67     | 50    | -17 |
| TestVolumeBindingRescheduling                                      | 13     | 13    | 0   |
| TestVolumeBindingStress                                            | 40     | 41    | 1   |
| TestVolumeBindingStressWithSchedulerResync                         | 56     | 40    | -15 |
| TestVolumeBindingDynamicStressFast                                 | 34     | 33    | -2  |
| TestVolumeBindingDynamicStressSlow                                 | 66     | 57    | -9  |
| TestVolumeBindingWithAntiAffinity                                  | 9      | 9     | 0   |
| TestVolumeBindingWithAffinity                                      | 10     | 10    | 0   |
| TestPVAffinityConflict                                             | 6      | 7     | 0   |
| TestVolumeProvision                                                | 24     | 28    | 4   |
| TestRescheduleProvisioning                                         | 5      | 5     | 0   |
|                                                                    |        |       | 49  |

**Comment by Huang-Wei** [comment]
@liggitt When subtest is involved, my understanding is that time showed in parent entry includes (1) time spent on setup and teardown + (2) time spent on each subtest, for example:

Seconds | Test
-- | --
1.58 | TestTaintNodeByCondition/not-ready_node
1.56 | TestTaintNodeByCondition/unschedulable_node
1.7 | TestTaintNodeByCondition/memory_pressure_node
1.68 | TestTaintNodeByCondition/disk_pressure_node
1.56 | TestTaintNodeByCondition/network_unavailable_and_node_is_ready
1.68 | TestTaintNodeByCondition/network_unavailable_and_node_is_not_ready
1.57 | TestTaintNodeByCondition/pid_pressure_node
1.11 | TestTaintNodeByCondition/multi_taints_on_node
18.58 | TestTaintNodeByCondition

We should only count `18.58` as the total time, instead of `18.58 + 1.58 + ... + 1.11`, correct?

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/81050

/close
