### ISSUE TITLE
Bind pre-existing Role to specific resource

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#80535]
**What would you like to be added**:
I would like a way to bind a pre-existing (Cluster)Role to a specific instance without the need to make a copy of that  (Cluster)Role.

**Why is this needed**:
Kubernetes comes with built-in roles, and operators, when installed, define their own roles.
When you want to give a subject permission to act on a specific instance, within a namespace with several instances, it is possible, but tedious and non-declarative to do this, and it involves copying the ClusterRole/Role defined by some package.

**Longer Explanation**

A Kubernetes Extension (operator) may come packaged with its own ClusterRoles.
For example, an operator that adds a Widget CRD might also install ClusterRoles called `widget-editor` and `widget-viewer`.  

Now suppose I want to give subject `default:my-sa` permission to edit a specific Widget named `my-widget`.

To do that today, I have to do something like this:
```
# Copy the original cluster role definition
$ kubectl get clusterroles widget-editor -o yaml > scopedrole.yaml

# Append a `resourceName` field.  This trick only works if the Role has
# a single `rules` item, which is often the case for a Role that you would want
# scope to one resource.
$ echo 'resourceNames: ["my-widget"]' >> scopedrole.yaml

# Rename the resource
$ sed s/  name: widget-editor/  name: widget-editor-on-my-widget/ scopedrole.yaml

# Create the new Role
$ kubectl create -f scopedrole.yaml

# Bind some subject to the new role
$ kubectl create rolebinding my-sa-edits-my-widget--clusterrole widget-editor --serviceaccount=default:my-sa
```

This works, but it has some drawbacks:
  - Tedious
  - Imperative rather than declarative.
  - Creates excess number of Roles/ClusterRoles.

The experience I would rather have is something like this:
```
# Make a resource-scoped role by reference to a pre-existing Role
$ kubectl create -f -  <<EOF
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  my-sa-can-edit-my-widget
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
resourceNames: 
  - my-widget
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
EOF
```

And also:
```
$ kubectl create rolebinding my-sa-can-edit-my-widget--clusterrole widget-editor --serviceaccount=default:my-sa --resourcename mywidget
```

The above is an example.  There could be other implementation alternative that would work fine too, such as:

-  a CRD which makes a ClusterRole and a ClusterRoleBinding as a child resource. 
- a new built-in resource that is part of rbac.authorization.k8s.io/v1 which is for this specific use case.

**Comment by erictune** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by WanLinghao** [comment]
One thing is, if admin wants to change any clusterrole/role, he must check if any reference exists in advance.  Could this also be complicated?

**Comment by mikedanese** [comment]
Kubernetes currently supports two levels of role binding (on the cluster with ClusterRoleBinding, and on a namespace with RoleBinding). To make a slight distinction between how I think an object level role binding *should* act and how `echo 'resourceNames: ["my-widget"]' >> scopedrole.yaml` acts, namespace and cluster bindings do not persist over bound object delete/recreate.
