### ISSUE TITLE
Update Elastic Search Variable in Kibana 7.1.1

### ISSUE THREAD

**Issue by librannk** [kubernetes/kubernetes#80530]
**What would you like to be added**:
Change Variable ELASTICSEARCH_URL to ELASTICSEARCH_HOSTS in kibana-depoloyment manifest for EFK
**Why is this needed**:
Kibana now changed there variables to link to Elastic search , please fix the same here as it took a while for me to figure it out and dont want anyone else to face same .

**Comment by mattjmcnaughton** [comment]
/remove sig-node
/sig cluster-lifecycle

Great that you're trying to help others from facing the same issue you ran into :)

Just updating this to be the proper sig.

**Comment by nabheet** [comment]
Looks like this might be fixed? It seems to be working now.

**Comment by librannk** [comment]
yes its fixed now, variable is updated
