### ISSUE TITLE
`kubectl get` with file input and `--ignore-not-found` fails on resources which are not found

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#80541]
**What happened**:
When using a yaml file for input, `kubectl get --ignore-not-found` silently fails at the first missing resource, not returning any further results.

**What you expected to happen**:
Searching with cli arguments properly ignores missing resources and continues the query, eg:
```
$ kubectl get -n kube-system --ignore-not-found secrets/attachdetach-controller-token-lkzp4 secrets/fake secrets/certificate-controller-token-847pm
NAME                                  TYPE                                  DATA   AGE
attachdetach-controller-token-lkzp4   kubernetes.io/service-account-token   3      7m52s
certificate-controller-token-847pm    kubernetes.io/service-account-token   3      7m55s
```
Would expect similar results with a file input, eg:
`$ kubectl get -f search.yaml --ignore-not-found`

**How to reproduce it (as minimally and precisely as possible)**:
With an input file of `search.yaml`:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: attachdetach-controller-token-lkzp4
    namespace: kube-system
  type: kubernetes.io/service-account-token
- apiVersion: v1
  kind: Secret
  metadata:
    name: fake-noexist
    namespace: kube-system
  type: kubernetes.io/service-account-token
- apiVersion: v1
  kind: Secret
  metadata:
    name: certificate-controller-token-847pm
    namespace: kube-system
  type: kubernetes.io/service-account-token
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```
the command `kubectl get -f search.yaml --ignore-not-found` fails at apparently the first missing resource:
```
$ kubectl get -f search.yaml --ignore-not-found
NAME                                  TYPE                                  DATA   AGE
attachdetach-controller-token-lkzp4   kubernetes.io/service-account-token   3      8m57s
```
**Note**: that rearranging the inputs in `search.yaml` (so that the missing resource is last) produces the "expected" output:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: attachdetach-controller-token-lkzp4
    namespace: kube-system
  type: kubernetes.io/service-account-token
- apiVersion: v1
  kind: Secret
  metadata:
    name: certificate-controller-token-847pm
    namespace: kube-system
  type: kubernetes.io/service-account-token
- apiVersion: v1
  kind: Secret
  metadata:
    name: fake-noexist
    namespace: kube-system
  type: kubernetes.io/service-account-token
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
```
$ kubectl get -f search.yaml --ignore-not-found
NAME                                  TYPE                                  DATA   AGE
attachdetach-controller-token-lkzp4   kubernetes.io/service-account-token   3      11m
certificate-controller-token-847pm    kubernetes.io/service-account-token   3      11m
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.1.136+5c346f36fbc0d6", GitCommit:"5c346f36fbc0d612a81ccc05478816d8bb51a148", GitTreeState:"clean", BuildDate:"2019-07-24T19:48:53Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.1.136+5c346f36fbc0d6", GitCommit:"5c346f36fbc0d612a81ccc05478816d8bb51a148", GitTreeState:"clean", BuildDate:"2019-07-24T19:44:38Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
local
- OS (e.g: `cat /etc/os-release`):
fedora 30
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
x-ref: https://bugzilla.redhat.com/show_bug.cgi?id=1727917

**Comment by kharunsamuel1** [comment]
Got around to reproducing it and can confirm that I'm getting the same behavior. I'm looking into fixing it now

**Comment by damemi** [comment]
@kharunsamuel1 thanks, any updates on this?

**Comment by kharunsamuel1** [comment]
I've learned that in the case of a fake entry, kubectl stops sending API get requests altogether. Learned by running kubectl get -f search.yaml --ignore-not-found --v=10, the result is shown below. Till now I've been looking into the cobra command framework but now I'm trying to find out where kubectl is making these API calls from(pretty blocked on finding out where this connection is happening). This is my first ticket so its taking quite a while my apologies. 
<img width="1440" alt="Screen Shot 2019-08-12 at 4 13 41 PM" src="https://user-images.githubusercontent.com/46697060/62860691-a2d44680-bd1e-11e9-8a51-c847ae100c71.png">

**Comment by damemi** [comment]
@kharunsamuel1 that's an interesting find, definitely helpful. When I looked into this I got to the `ResourceBuilder` section of get's main run function, and it seems like it *should* be continuing on any errors (see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get/get.go#L475) but maybe the ResourceBuilder is actually stopping when it hits a 404?

**Comment by richardmarshall** [comment]
This behavior comes from where the not found errors are being ignored and where the input list is flattened.

Errors are ignored here:

https://github.com/kubernetes/kubernetes/blob/ca6290538b91ebd6fa65408a5d4030efa8c15918/staging/src/k8s.io/cli-runtime/pkg/resource/result.go#L113

While flattening occurs here:

https://github.com/kubernetes/kubernetes/blob/ca6290538b91ebd6fa65408a5d4030efa8c15918/staging/src/k8s.io/cli-runtime/pkg/resource/visitor.go#L391

As the visitor iterates through the objects in the list if an error occurs, such as not found, it will stop iterating over the objects in the list and return that not found error. The `Result` logic will then ignore it and continue. Any objects that came before the not found object in the list will have been visited and will then be included in the output.

To make the behavior consistent between the two ways of getting the set of objects, the `FlattenListVsitor` would need to be updated to support filtering errors.

**Comment by kharunsamuel1** [comment]
Just submitted a PR adding that functionality to the FlattenListVisitor. The behavior is now consistent between the two methods.
