### ISSUE TITLE
/build/dependencies.yaml should be in a sub-folder with multiple SIG owners

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#80546]
@dims @yastij 

hello, as much as i like the new dep check with `build/dependencies.yaml` it introduced a bit of an ownership problem.
e.g. now every time we bump versions of etcd or coredns in kubeadm we need an approver from this OWNER file:
https://github.com/kubernetes/kubernetes/blob/master/build/OWNERS

realistically we only have to bump these once a cycle, but it feels like a minor issue in terms of project organization.

should the YAML file be in a sub-folder with representatives from key sigs?

suggesting:
build/dependencies.yaml -> build/dependencies/dependencies.yaml
and having an OWNERS file in there.

WDYT?

/assign @dims @yastij 
/sig architecture
/area code-organization

**Comment by BenTheElder** [comment]
> e.g. now every time we bump versions of etcd or coredns in kubeadm we need an approver from this OWNER file:
> https://github.com/kubernetes/kubernetes/blob/master/build/OWNERS

:wave: one of those approvers ... FWIW @cblecker and I are both in that one and (go) dependencies (dep-approvers) as-is, we have some precedence in the latter for [dependency review](https://github.com/kubernetes/community/blob/9258fa171f569a33b62a07239c10bce137598527/contributors/devel/sig-architecture/godep.md#reviewing-and-approving-dependency-changes) specifically, we might want some details similar to this to cover other things referenced here.

I can't speak for Christoph but I'm happy to help handle these PRs. Feel free to `/assign @BenTheElder`.

> should the YAML file be in a sub-folder with representatives from key sigs?

I would say that approval should be based on review etc. like usual rather than being from a SIG? (I.E. maybe, but this sort of reads like a suggestion to short-circuit [approvers](https://github.com/kubernetes/community/blob/f5dcf5c3520e5b9f964109052b1b097b80abcf84/community-membership.md#approver) which imho we should not do)

> realistically we only have to bump these once a cycle, but it feels like a minor issue in terms of project organization.

Perhaps not such a problem then?

**Comment by neolit123** [comment]
@BenTheElder 
hi, while i do agree that you and @cblecker are quite responsive, it still feels to me that we are introducing a unnecessary bottle neck.

when we were discussing something similar to this YAML logic today, the proposal was to have representatives from different SIGs in the OWNER file that shepherds the dep list.

if feels to me at the minimum we should have a couple of SIG Cluster Lifecycle representatives given most of the paths are `/cluster` and `cmd/kubeadm`.

but given https://github.com/kubernetes/kubernetes/blob/master/build/OWNERS is the build root i stand to this proposal:
> suggesting:
> build/dependencies.yaml -> build/dependencies/dependencies.yaml
> and having an OWNERS file in there

cc @fejta @justaugustus

**Comment by BenTheElder** [comment]
I would still suggest these should be under something similar if not the same as the `dep-approvers` process with written guidelines and promotion of reviewers -> approvers (though this would be best done with a specific directory like `build/dependencies` :+1:)

If _exactly_ that process / team I'm also sure it would not hurt to try to grow that team with some dep-reviewers ...

**Comment by neolit123** [comment]
during the code-organization meeting @dims was a +1 on my proposal.

but i also agree with you that the deps team needs growth.
problem with the growth of the OWNERS there is that it can be quite slow and people don't have the bandwidth.

**Comment by justaugustus** [comment]
I think Release Engineering should be a stakeholder here (if not the primary stakeholder).
I've created #80631, which adds Release Engineering OWNERS, and we can develop a policy similar to the dep-approvers one to ensure we're vetting this throughout the release cycle.

+1 to `build/dependencies/{dependencies.yaml,OWNERS}` (even though it stutters).
Actually, maybe `build/dependencies/versions.yaml` instead?

/priority important-soon
/milestone v1.16

**Comment by cblecker** [comment]
My understanding is that this file and check was literally designed to be a slight bottle neck so we understand when these dependencies are bumped, and ensuring that all the right places are bumped. So it being a bottleneck isn't a problem, but that doesn't mean we can see if we can make it smoother.

The biggest question I have is directed at the release folks: What do reviewers/approvers in this area need to look for? As a current build/ approver, I know how to "do the right thing" but I would be way more comfortable having a defined policy around what we need to do for these different version bumps (I know the go version is different than other components like coredns, for example).

If we had that, then I think there would be very little concerns around having multiple teams share ownership of this file.

**Comment by neolit123** [comment]
@yastij @dims 
another problem that i found is that the coredns version being coupled between kubeadm and kube-up will block kubeadm PRs from merging see: https://github.com/kubernetes/kubernetes/pull/78033

while we want to keep the versions in sync, i don't think we should block in such cases.

/kind bug

**Comment by justaugustus** [comment]
> The biggest question I have is directed at the release folks: What do reviewers/approvers in this area need to look for? As a current build/ approver, I know how to "do the right thing" but I would be way more comfortable having a defined policy around what we need to do for these different version bumps (I know the go version is different than other components like coredns, for example).

@cblecker -- [We don't have a policy yet](https://github.com/kubernetes/kubernetes/issues/80546#issuecomment-515386171), but we'll get something drafted. Given that you've got experience here, how can we ensure we're "do[ing] the right thing"?

The immediate things that come to mind are:
- bump version in dependencies.yaml
- update files referenced in `refPaths`
- communicate w/ and get approval from stakeholders e.g., CoreDNS --> SIG Network
- ???
- profit

Opened https://github.com/kubernetes/kubernetes/pull/80799 to move this into its' own directory under `build/` and seed an initial OWNERS w/ SIG Release/Release Engineering as approvers/reviewers.

**Comment by cblecker** [comment]
I think each one of these might need a little bullet point list. Like if the dependencies.yaml points to a markdown file somewhere with a TOC with headings that match each one of the dependencies, with a list of what you need to do. CoreDNS is probably diff than golang, for example

**Comment by justaugustus** [comment]
@cblecker -- that's the plan. It'll live in `k/sig-release/release-engineering/{managing,updating,external}-dependencies.md`, with a link somewhere in `k/community/contributors/foo`.

There's still some archaeology to do before I can write something tangible though...

See as examples:
### CNI
- https://github.com/kubernetes/kubernetes/pull/78819#issuecomment-500363068
- https://github.com/kubernetes/release/pull/731#issuecomment-499571767

### CRI 
- https://github.com/kubernetes/release/issues/739

**Comment by justaugustus** [comment]
(for the above, I'm trying to prove the "right" way to bump CNI and document it, before moving on to CRI.)

**Comment by cblecker** [comment]
fantastic! yeah, that's awesome. but yeah, otherwise your [list](https://github.com/kubernetes/kubernetes/issues/80546#issuecomment-516775698) (along with the announce to k-dev when it makes sense) would be the other things I'd think of

**Comment by justaugustus** [comment]
SGTM!

**Comment by justaugustus** [comment]
Tracking issue for this: https://github.com/kubernetes/sig-release/issues/601

**Comment by makoscafee** [comment]
@dims @justaugustus @yastij Hello! I'm bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by xmudrii** [comment]
@justaugustus Do we have any update on this?

**Comment by cblecker** [comment]
This isn't v1.16 blocking

**Comment by jtslear** [comment]
Hello @justaugustus 
Bug Triage team here for the 1.18 release.  Is this issue still intended for milestone 1.18?

**Comment by jtslear** [comment]
Hello @kubernetes/sig-architecture-feature-requests and @kubernetes/kubernetes-release-managers

This is tied to the 1.18 milestone, however, there's been no movement this year.  Should this be tied to any milestone?  I suspect it is non-blocking based solely on the history.

**Comment by justaugustus** [comment]
Thanks for checking in. We're not working on this for 1.18, so:
/milestone clear

**Comment by justaugustus** [comment]
Going to really try and tie this off for v1.21.
/milestone v1.21

**Comment by ams0** [comment]
Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (today!).

As the Issue is tagged for 1.21, but no PR is linked, are we still working on this?

**Comment by erismaster** [comment]
@justaugustus Do you want to try for this one in v1.22 or clear the milestone for now?
Thanks!

**Comment by dims** [comment]
/milestone v1.22

moving it. I don't think we will reach a consensus in in time.

**Comment by jgavinray** [comment]
Hi @LappleApple,
Bug Triage team here for the 1.22 release. Is this issue still intended for milestone 1.22?

**Comment by BenTheElder** [comment]
this is now also the case in https://github.com/kubernetes/release/blob/master/dependencies.yaml including entries that are for a single file, people that could previously approve the base images cannot anymore.

I haven't seen any movement there, I don't think there's any change here.

**Comment by justaugustus** [comment]
I haven't been able to work on this, but as it's been open for a while, and I haven't seen work-stopping friction, it leads me to believe we don't actually need it.

If anyone feels differently, feel free to reopen.
/close
/unassign
