### ISSUE TITLE
Service Controller loop creates orphaned resources

### ISSUE THREAD

**Issue by MSSedusch** [kubernetes/kubernetes#80571]
**What happened**:
The issue has been observed on Azure but should also apply to other providers as well. On Azure we observed that there are orphaned Public IPs that don't belong to any Kubernetes LoadBalancer service but from looking at the tags and the name it is clear that Kubernetes created them. In the Azure Activity Log, you can see that the Public IP was deleted when the K8s service was deleted but recreated a few minutes later. That re-creation is also visible in the K8s controller manager logs as a reconcile of the service.

In our case, we add additional worker nodes and delete services at the same time. I think this leads to the re-creation here https://github.com/kubernetes/kubernetes/blob/41b3e60f0e4032eec2caf38348d82641395f7af6/pkg/controller/service/service_controller.go#L686

Because the service list is retrieved at the beginning of the reconcile loop, services that are deleted while the loop is reconciling a recreated by that loop and afterwards orphaned.

**What you expected to happen**:
No orphaned public IPs

**How to reproduce it (as minimally and precisely as possible)**:
Create a few Kubernetes Load Balancer services (we have around 20). Then scale your worker nodes and delete one service at the same time.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.0
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Core OS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MSSedusch** [comment]
@kubernetes/sig-azure

**Comment by feiskyer** [comment]
@MSSedusch Thanks for reporting the issue. I think this should be fixed during v1.16 release cycle.

/milestone v1.16

**Comment by tedyu** [comment]
```
// Updates the load balancer of a service, assuming we hold the mutex
// associated with the service.
func (s *ServiceController) lockedUpdateLoadBalancerHosts(service *v1.Service, hosts []*v1.Node) error {
```
In the nodeSyncLoop -> updateLoadBalancerHosts -> lockedUpdateLoadBalancerHosts call chain, I don't see where the mutex lock is obtained.

**Comment by xmudrii** [comment]
@MSSedusch @feiskyer Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 4 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by feiskyer** [comment]
The issue would probably not able to be fixed in v1.16. AFAIK, no one is working on it now.

**Comment by xmudrii** [comment]
@feiskyer Thank you for the update! I'll go ahead and remove the issue from the milestone. If anything changes in the meanwhile, please let us know.

/milestone clear

**Comment by ritazh** [comment]
@chewong

**Comment by andrewsykim** [comment]
Doesn't LB Finalizer support fix this? We enabled this by default starting v1.16

**Comment by andrewsykim** [comment]
Initial PR: https://github.com/kubernetes/kubernetes/pull/78262
Bump to beta in v1.16: https://github.com/kubernetes/kubernetes/pull/81691
