### ISSUE TITLE
CronJob Schedule does not use master's timezone - instead it uses UTC

### ISSUE THREAD

**Issue by justgotthis** [kubernetes/kubernetes#80577]
**What happened**:
The master is at PDT (-7).

Verified local time on master:

``` 
timedatectl
                      Local time: Fri 2019-06-07 09:21:42 PDT
                  Universal time: Fri 2019-06-07 16:21:42 UTC
                        RTC time: Fri 2019-06-07 16:21:42
                       Time zone: America/Los_Angeles (PDT, -0700)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
```
Created a cronjob with schedule of `"0 12 * * 5"` to run on Friday noon.

```
kubectl describe cj manager-weekly-us
Name:                          manager-weekly-us
Namespace:                     default
Labels:                        environment=production
                               function=report
Annotations:                   <none>
Schedule:                      0 12 * * 5
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  824638405216
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  <none>
  Containers:
   manager-weekly-us:
    Image:      mantisphp7:0.8
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/sh
      -c
      /usr/bin/php  /var/www/html/mantis/reports/manager_report.php -i summary -m -t "us.field us.devops et carrier"
    Environment:  <none>
    Mounts:
      /mantis_file_upload from upload (rw)
      /scripts from scripts (rw)
      /var/www/html/mantis from www (rw)
  Volumes:
   www:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mantis-www
    ReadOnly:   false
   upload:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mantis-upload
    ReadOnly:   false
   scripts:
    Type:            PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:       mantis-scripts
    ReadOnly:        false
Last Schedule Time:  Fri, 07 Jun 2019 05:00:00 -0700
Active Jobs:         <none>
Events:              <none>
```
You can see it actually ran on 12 UTC, which is 5AM PDT.

**What you expected to happen**:
According to the document:

`Note: All CronJob schedule: times are based on the timezone of the master where the job is initiated.`

**How to reproduce it (as minimally and precisely as possible)**:

- make sure your host is on some timezone not UTC
- create a cronjob with schedule '0 12 * * *' (or any hour that fits you)
- observe when the cronjob runs.

**Environment**:
```
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud provider or hardware configuration:
self hosted
OS (e.g: cat /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Kernel (e.g. uname -a):
Linux smart-sjc-node1 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Install tools:
kubeadm

Network plugin and version (if this is a network-related bug):

Others:

**Comment by justgotthis** [comment]
Please note, do not close the ticket with multiple timezone support for cronjobs (#47202). This is regarding CronJobs respecting the TimeZone from the Master so it is not working as intended.

**Comment by zq-david-wang** [comment]
Just out of curiosity, are you running your master components in container? Each container would have its own timezone.  I think the timezone used by controller is used for parsing cronjob schedule, not necessary the timezone on the host.

**Comment by justgotthis** [comment]
`Note: All CronJob schedule: times are based on the timezone of the master where the job is initiated.`

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by zq-david-wang** [comment]
timezone of master is not timezone of the host where master is running on....my understanding is that " timezone of the master" means "timezone **used by** master".

(timezone is an application-level configuration, each container  has its own timezone.)

The information that whether you're running master component in containers would help people who would or want to help solve your issue, could you clarify it?

**Comment by justgotthis** [comment]
I am running the master components in containers. I built my master in PDT but my cronjobs are executed in UTC. I would like to have consistency and have my cronjobs also executed at PDT along with my masters TZ.

**Comment by kazusa-qooq** [comment]
@zq-david-wang Could you tell me how to set the master container’s timezone? I made the master with kubeadm.
I want to write schedules for cronjob by my timezone not UTC.
According to what you say, I must set my timezone to master containers.

**Comment by justgotthis** [comment]
Workaround now is to mount timezone to controller-manager and restart it. Although, I have seen that running a `date` within the cronjob container will still list it in UTC but the job will execute in my TZ.

**Comment by kazusa-qooq** [comment]
@justgotthis Thank you. Let me know what you edit? Did you change File; /etc/kubernetes/manifests/kube-controller-manager.yaml?

**Comment by justgotthis** [comment]
Not sure where your manifest file is but wherever controller-manager is
configured. Then mount a volume to /etc/localtime and have the source be
/usr/share/zoneinfo/<TZ> (hostPath).

Hopefully we can get this bug fixed so cronjobs will respect where the
master is at and just have this configured properly without this hack.

*Luis Lazo*
Solutions Architect
Platform9
luis@platform9.com
650-966-6207

**Comment by justgotthis** [comment]
*bump*, would love to have some assistance with this if anyone has ran into this behavior.

**Comment by cpiment** [comment]
> 
> 
> Workaround now is to mount timezone to controller-manager and restart it. Although, I have seen that running a `date` within the cronjob container will still list it in UTC but the job will execute in my TZ.

@justgotthis sorry to bump and old issue but we are facing the same problems setting cronjob schedules. I have read in different places about this workaround, but I would like to know if it has caused you any trouble, since the controller-manager runs in a timezone but etcd, api-server, and scheduler run in UTC. I'm afraid the change can break other things...

**Comment by justgotthis** [comment]
Hello, when I ran this mount in my controller manager, it fixed the time
zone issue and I did not experience any other negative behavior at the time.

-Luis.
