### ISSUE TITLE
pull-kubernetes-conformance-image-test is failing

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#80589]
**Which jobs are failing**:
pull-kubernetes-conformance-image-test 

**Which test(s) are failing**:
Overall

**Since when has it been failing**:
Last green: [2019-07-17 17:23:46 UTC](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-image-test/1151542712869064704)
First red with this failure: [2019-07-18 06:02:43 +0000 UTC](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-image-test/1151733966336692224)
Most recent failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-image-test/1154399007229874176

**Testgrid link**:
https://testgrid.k8s.io/sig-testing-misc#pull-kubernetes-conformance-image-test&width=20

**Reason for failure**:
```
I0725 14:38:47.484] Pulling: kindest/kindnetd:0.5.0
I0725 14:38:47.484] Pulling: k8s.gcr.io/kube-proxy:v1.16.0-alpha.1.243_037619f932b2dc
I0725 14:38:47.485] Pulling: k8s.gcr.io/kube-scheduler:v1.16.0-alpha.1.243_037619f932b2dc
I0725 14:38:47.485] Pulling: k8s.gcr.io/kube-controller-manager:v1.16.0-alpha.1.243_037619f932b2dc
I0725 14:38:47.485] Pulling: k8s.gcr.io/kube-apiserver:v1.16.0-alpha.1.243_037619f932b2dc
I0725 14:38:47.485] Pulling: k8s.gcr.io/etcd:3.3.10
I0725 14:38:47.485] Pulling: k8s.gcr.io/pause:3.1
I0725 14:38:47.486] Pulling: k8s.gcr.io/coredns:1.3.1
I0725 01:59:19.172] time="01:59:19" level=error msg="Image build Failed! Failed to pull Images: exit status 1\nexit status 1\nexit status 1\nexit status 1\n"
W0725 01:59:21.465] Error: error building node image: exit status 1
W0725 01:59:21.465] exit status 1
W0725 01:59:21.465] exit status 1
W0725 01:59:21.465] exit status 1
W0725 01:59:21.465] 
W0725 01:59:21.470] + cleanup
W0725 01:59:21.470] + kind export logs /workspace/_artifacts/logs
W0725 01:59:21.629] Error: unknown cluster "kind"
```

**Anything else we need to know**:
It's non blocking, but if it's going to be left in this state perhaps we should consider disabling reporting.

It's not clear to whether this is a problem with kind, the conformance image, or something else

/assign @BenTheElder @johnSchnake @dims 
/sig testing
/sig architecture
/area conformance

**Comment by BenTheElder** [comment]
kind needs to be upgraded in the script to deal with a Kubernetes breakage.

**Comment by BenTheElder** [comment]
/lifecycle active
https://github.com/kubernetes/kubernetes/issues/80589

**Comment by spiffxp** [comment]
/close
The testgrid link now shows some green runs, thanks @BenTheElder
