### ISSUE TITLE
Support TLS Server Name overrides in kubeconfig file

### ISSUE THREAD

**Issue by stevehorsfield** [kubernetes/kubernetes#80596]
We are using multiple AWS EKS deployed clusters with private VPC-only access in combination with VPC-peering and tooling to provide multiple environments.

Currently, we deploy intermediary proxies to get round the limitation in EKS that the API servers are only routable from within the same VPC.

To establish a connection from another location, we have to include a `hosts` file override to point to the proxy because the TLS SNI is not separately configured from the address resolution.

Would be great to have this added to the code here: https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/api/types.go.

**Comment by liggitt** [comment]
This is already supported by the `rest.Config` struct, it seems useful to allow control over

/priority backlog
/sig api-machinery

**Comment by surki** [comment]
@liggitt Can you please take a look at PR #82056
