### ISSUE TITLE
Sort Field for ListOptions

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/kubernetes#80602]
I would like to have the ability to sort objects server side by a particular field on the object being returned when issuing a get request that returns a list of objects.

I am wondering about the impact of potentially adding a `Sort` field to [ListOptions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L316) so that a sort field can be specified as part of a get request.

If there is already an option available, I would like to know where I can find an example. 

**What would you like to be added**:

An example of how to return a list of objects in a sorted order using a go-client or the ability through ListOptions to specify a sort field.

**Why is this needed**:

An example of where I would like to use such a field can be found as part of the [Tekton](https://github.com/tektoncd/pipeline/blob/master/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipelinerun.go#L78) project. The idea here would be to sort `pipelineruns` by their start times and then returned to the requestor.

**Comment by roycaihw** [comment]
cc @cheftako 
/sub

**Comment by liggitt** [comment]
> I am wondering about the impact of potentially adding a `Sort` field to [ListOptions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L316) so that a sort field can be specified as part of a get request.

Without datastore-level support, this would both be very expensive and interact very poorly with [list paging](https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks).

**Comment by danielhelfand** [comment]
@liggitt Is there a recommended way to sort results server side with a cluster using a go client?

**Comment by liggitt** [comment]
> @liggitt Is there a recommended way to sort results server side with a cluster using a go client?

no, that's not an option supported by the API currently.

kubectl support `--sort-by` by serializing objects to json client-side, then evaluating jsonpath expressions against each object and sorting in memory

**Comment by danielhelfand** [comment]
@liggitt Thank you for the explanation. I believe this would be a really nice feature to have available, but I am not fully aware of the details of what would be needed to implement something akin to `--sort-by` or a different sorting approach. If there's any ideas around this or if this is in any way being discussed, would like to know more.

**Comment by cheftako** [comment]
I believe we should be increasingly moving toward paginated clients. Before you pull a resource you don't know how large it is. Pulling an unpaginated list of a large resource can already cause problems to the control plane. So we should be moving clients to using paginated lists. As Jordan indicated we don't currently have data store level support for indexed/ordered reads. Without ordering at the data storage server we would have to order at the KAS and either recompute per request or keep the list in memory. Either of which reduces the value we get from pagination.

**Comment by danielhelfand** [comment]
I can agree with the thoughts on paginated clients, but what I struggle with is the idea that a Limit field is available but the client can in no way determine how that data returned is ordered. 

Maybe what I’m proposing is truly an edge case for the API, but I think not allowing the determination of order gets rid of use cases for Limit. In the case of pipelineruns, pulling them back by name makes a lot less sense than by start time. But there’s no say in how data is returned. It’s somewhat of an all or nothing approach from my understanding. 

I will defer to both of you since you both understand the API extremely well and also its users. But the use of Limit without sorting is my main concern.

**Comment by tomqwpl** [comment]
I too am frustrated by the lack of this functionality.
I'm wanting to provide a user interface that displays information where the primary source of truth is stored in CRs. Naturally I want to provide paging in the user interface so that it only shows limited data, and is scalable regardless of the number of instances. Naturally I want to provide sorting to allow users to sort by name, creation date etc. The only way of apparently doing this is for the API server to read the complete list of CRs each time and then perform its own sorting and then paging.

**Comment by psevestre** [comment]
>  The only way of apparently doing this is for the API server to read the complete list of CRs each time and then perform its own sorting and then paging.
A possible workaround is to use an initial client-side sort and a watch to keep track of changes in an incremental way..

**Comment by hookenz** [comment]
> I too am frustrated by the lack of this functionality. I'm wanting to provide a user interface that displays information where the primary source of truth is stored in CRs. Naturally I want to provide paging in the user interface so that it only shows limited data, and is scalable regardless of the number of instances. Naturally I want to provide sorting to allow users to sort by name, creation date etc. The only way of apparently doing this is for the API server to read the complete list of CRs each time and then perform its own sorting and then paging.

Likewise!   the whole API is not build with dashboards and UI's in mind.
