### ISSUE TITLE
K8S using kata container mounted ssd local pv failed when enable privilege

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#80621]
**What happened**:

When mounted local pv to pod(kata enable privilege) configured block devices, however ssd mounted failed and sata mounted successfully. Using fdisk -l, we can not find the ssd but can found sata.

**What you expected to happen**:

Mount ssd successfully 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: k8s 1.13 kata
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig storage 
/sig node

(seems like a runtime issue)

**Comment by dims** [comment]
@cwdsuzhou can you please follow up with the kata container folks and open the issue there?

/close
