### ISSUE TITLE
metric namespace went away in PR #71300

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#80622]
**What happened**:
I started trying to use the new workqueue metrics and noticed that the "namespace" part of the usual metric name form --- `namespace_subsystem_name` --- is now gone.
See how https://github.com/kubernetes/kubernetes/blob/b234dd06aa3aea6e7c0cda4a5d6bad9c3f859428/pkg/util/workqueue/prometheus/prometheus.go#L42-L46 provides the "Subsystem" and the "Name" --- as fixed quantities --- and omits the "Namespace" field of `Opts`.  Formerly the queue name --- which is fully under client developer control --- was provided as the "Name" while both "Namespace" and "Subsystem" were omitted, allowing the client developer to sneak them in through the queue name.

**What you expected to happen**:
I expected the Prometheus metric names to have the usual tripartate form.  As a client developer I expected to be able to provide more structure than a single name; admittedly I was previously providing only a single name string, but it had a commonly-understood tripartate structure.  I can still provide that same tripartate string, but nothing is expecting/understanding that tripartate structure in the `name` label of these metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Read the doc or look at the metrics.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by roycaihw** [comment]
cc @logicalhan

**Comment by RainbowMango** [comment]
It's interesting things...

@MikeSpreitzer 
Do you know if there any guidelines from Prometheus about the `Namespace`, `Subsystem` and `Subsystem`? 
I will back on this issue after 1.17.

/remove-lifecycle stale
/assign
