### ISSUE TITLE
[Scheduler] Default spreading should be configurable for a topology

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#80639]
By default, the scheduler spreads pods by zone, in order to provide some level of reliability for services.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/selector_spreading.go#L108

**What would you like to be added**:

Cluster operators should be able to change this to a topology label that better fits their need.

This can be done with a flag to the binary that is set to `zone` by default, so that current behavior remains.

**Why is this needed**:

On-prem clusters have different topologies than cloud providers. If the scheduler uses the zone topology for default spreading, on-prem cluster operators don't have another alternative but to abuse the zone label even though that might violate its semantic meaning.

/sig scheduling

**Comment by ahg-g** [comment]
Sounds good, during the sig meeting we also discussed making a change to the scheduler config to specify multiple levels of default spreading, not just one. So it is something to consider.

I this this will need a KEP, and we can target it for 1.17.

**Comment by ahg-g** [comment]
We should think about leveraging even pod spreading for this and completely deprecate the [selector_spreading.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/selector_spreading.go) priority function. 

For example, allow admins to configure the scheduler with a default spreading policy using even pod spreading API embedded in the scheduler's component config, or define a simpler API in component config that gets converted to an even pod spreading configuration applied to pods without one.

**Comment by Huang-Wei** [comment]
I agree even pod spreading can be more flexible than the "implicit" `selector_spreading` priority. However, we should only deprecate that once even pods spread gets to Beta.

@alculquicondor Yes, we need a KEP and involve end-users to pick their brain if appropriate.

**Comment by ahg-g** [comment]
Yes, we need to wait until even pod spreading is in Beta. We can start with the KEP to make progress on how the component config API will look like.

**Comment by ahg-g** [comment]
It seems that we have something similar already called [ServiceAntiAffinity](https://github.com/kubernetes/kubernetes/blob/35cf6b6cbc7c55258ac0e3af51f6b0f5119750b1/pkg/scheduler/algorithm/priorities/selector_spreading.go#L162:6)
