### ISSUE TITLE
Pods cannot work due to failing to access /etc/hosts inside container if umask of kubelet is configured as 0027

### ISSUE THREAD

**Issue by luckyfengyong** [kubernetes/kubernetes#80668]
**What happened**:
Application running inside a pod failed to work as it cannot access /etc/hosts inside the container when umask of the kubelet which starts the pods is configured as `0027`. 

It is because the [ioutil.WriteFile()](https://github.com/kubernetes/kubernetes/blob/v1.15.0/pkg/kubelet/kubelet_pods.go#L329) used to create `/etc/hosts` is impacted by umask. Even though kubelet specify the permission of `0644` explicitly, with umask of `0027`, it will be configured as `0640`. As a result, application running inside the pods with non-root user, failed to access it. 

**What you expected to happen**:
kubelet should pre-configure required umask by itself, instead of depending on the environment. At least we should document the required umask. 

**How to reproduce it (as minimally and precisely as possible)**:
Launch kubelet with umask of `0027`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15 (actually untill 1.15)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.4.1708
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools: from souce code
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by luckyfengyong** [comment]
@dchen1107 @derekwaynecarr @tallclair Any comment?

**Comment by mattjmcnaughton** [comment]
Thanks for filing this @luckyfengyong !

I like your idea about adding documentation/logging around when this happens. What if when the kubelet wrote the `/etc/hosts` file, it performed a check of whether it was 644 vs 640, and if the latter, it at the very least logged an error message and potentially raised an exception. I think that could make debugging this type of issue much easier in the future.

If that idea sounds good to you, I'm happy to review a PR - or if you don't have capacity to create one, I can create one as well. Just let me know :)

**Comment by luckyfengyong** [comment]
Thank you @mattjmcnaughton for the comments.

Adding an error message is good. Can we make a further step to enhance kubelet not depending on umask configured outside? When developing a Linux daemon, people usually write the following logic to make sure the permission of the newly created file is what they want.

```
  mask = umask(0);
  create new direcotry or file
  umask(mask);
```

Can we follow the same logic to fix it? If it is OK, I am very glad to submit a PR.

**Comment by mattjmcnaughton** [comment]
Interesting! I'm curious to hear the opinions of others... to be honest, I'm not sure I have enough experience writing Linux daemons to say what is the standard behavior.

**Comment by luckyfengyong** [comment]
@mattjmcnaughton Sure. It is always good to hear more comments from others. 

I just try to share some info about the best practice of writing a daemon from old Linux world :-)

https://stackoverflow.com/questions/3095566/linux-daemonize/3095624#3095624
http://cjh.polyplex.org/software/daemon.pdf 
http://www.netzmafia.de/skripten/unix/linux-daemon-howto.html

Calling umask(0) is used to make sure that a daemon has full control of the permission of the newly created file or directory. I believe that is also what kubelet wants.
