### ISSUE TITLE
A roadmap for migrating to the scheduler framework

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#80670]
**What would you like to be added**:
We need a roadmap for migrating the scheduler core, including predicates and priorities, to the new scheduling framework.

**Why is this needed**:
Most of the extension points of the framework has now been implemented, and we need to refactor existing features into the framework

/sig scheduling
/assign

**Comment by hex108** [comment]
Thanks for it! We could break them down by extension points, then break them into small tasks. I have a patch for queue sort plugin at https://github.com/kubernetes/kubernetes/issues/80304, maybe we could start to discuss how to migrate them by this case.

**Comment by ahg-g** [comment]
Thoughts and discussion in the following doc: https://docs.google.com/document/d/1P1eBaePxuko22B8LLOrPEonoj1awc1dCVBDefuRWUA4/edit

**Comment by ahg-g** [comment]
This is done.

Phase 1 migration: #83554
Phase 2 migration: #85822
