### ISSUE TITLE
error info when using `make kubelet GOGCFLAGS="-N -l" GOLDFLAGS=""` 

### ISSUE THREAD

**Issue by yanghaichao12** [kubernetes/kubernetes#80674]
**What happened**:
when i execute 
```shell
make kubelet GOGCFLAGS="-N -l" GOLDFLAGS=""
```
but got：
```shell
2019/07/27 15:27:02 Code for OpenAPI definitions generated
+++ [0727 15:27:02] Building go targets for linux/amd64:
    ./vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0727 15:27:04] Building go targets for linux/amd64:
    cmd/kubelet
# k8s.io/kubernetes/cmd/kubelet
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-build474287534/b001/exe/a.out: 
collect2: error: ld returned 1 exit status

!!! [0727 15:28:14] Call tree:
!!! [0727 15:28:14]  1: /home/ubuntu/workspace/src/k8s.io/kubernetes/hack/lib/golang.sh:616 kube::golang::build_some_binaries(...)
!!! [0727 15:28:14]  2: /home/ubuntu/workspace/src/k8s.io/kubernetes/hack/lib/golang.sh:752 kube::golang::build_binaries_for_platform(...)
!!! [0727 15:28:14]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0727 15:28:14] Call tree:
!!! [0727 15:28:14]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0727 15:28:14] Call tree:
!!! [0727 15:28:14]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
```
here is my golang.sh and  .shellcheck_failures:
```shell
goldflags="${GOLDFLAGS=-s -w} $(kube::version::ldflags)"
```
```shell
./hack/cherry_pick_pull.sh
./hack/ginkgo-e2e.sh
./hack/grab-profiles.sh
./hack/lib/golang.sh
./hack/lib/init.sh
./hack/lib/swagger.sh
./hack/lib/test.sh
```
**What you expected to happen**:
no errors 

**Environment**:

Kubernetes version (use kubectl version):1.13.6
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release):Ubuntu 16.04 LTS
Kernel (e.g. uname -a):4.4.0-21
Install tools:
Network plugin and version (if this is a network-related bug):
Others:

**Comment by YoubingLi** [comment]
I can successfully run your command in my workspace basing on following commit

commit cc0137cdc6a4511049838de5937ccd0ed5c55349
Merge: 2321d1e9e8 bd15f3f9f7
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Thu Jul 25 18:12:00 2019 -0700

    Merge pull request #80398 from aojea/ipfamily
    
    Add ip family autodetection to the testing framework

make kubelet GOGCFLAGS="-N -l" GOLDFLAGS=""
`
+++ [0728 22:21:20] Building go targets for linux/amd64:
    cmd/kubelet
40.089u 26.900s 1:30.36 74.1%   0+0k 1659216+2296680io 0pf+0w
`

**Comment by yanghaichao12** [comment]
i‘v try again on rhel，everthing is ok, so i believe it's not about k8s.
