### ISSUE TITLE
kubelet can't "get" node from apiserver for up to ~2 minutes

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#8068]
This makes cluster startup pretty painful and have wide variance, causing problems for monitoring and testing cluster turnup. After the kubelet can first talk to the apiserver, in can be from ~0 seconds to ~2 minutes until the kubelet can "get" its own node. Only then can it start pulling images to get pods running.

We see repeating errors for up to 2 minutes that look like:

```
E0505 02:03:19.746214    4659 kubelet.go:1534] error getting node: node <node name> not found
E0505 02:03:26.003989    4659 kubelet.go:1710] error updating node status, will retry: error getting node "<node name>": minion "<node name>" not found
```

this has, I believe, been plaguing us for quite a while. It would be really great if we could figure out why. The master logs, if I recall correctly, don't have anything interesting in them (similar errors). (The most recent cluster I had that had these problems is gone, but I'll check further in the next.)

+cc @roberthbailey (hoping that "kubelet registering with master" change will fix this)
+cc @zmerlynn (has looked into this too)
+cc @davidopp (master)
+cc @dchen1107 (node)

**Comment by zmerlynn** [comment]
When I've seen it, it's actually been fairly bimodal. Either the kubelet gets stuck for 2m doing this, or it doesn't. I actually have a dataset of cluster-up timings on GKE that show a weird pile of "fast" up timing (1:30-ish) and "slow" up timing (3:30-ish), and when I stopped and debugged one of the slow ones, it was this bug.

**Comment by roberthbailey** [comment]
Self registration should help here, since the kubelet won't be waiting for the master to list nodes with the cloud provider -- it will just add itself directly. There will still be a delay before it can do anything useful, because it will need to wait for the master to assign it a CIDR and then reconfigure the local docker bridge, but that should be fairly quick and (hopefully) have low variance.

**Comment by dchen1107** [comment]
@zmerlynn When you mentioned this bug, which bug are you referring to? Literally #8068? 

Agreed with @roberthbailey that self registration should help here.

**Comment by zmerlynn** [comment]
Yeah, I mean this one. It just look like it sat there for 2m waiting in "not found".

FWIW, my data was "anecdotally bimodal". It's probably a little more skewed than just 2m or not. But this is actually now the largest variance in cluster creation time. (And that's taking into account everything in GCE, startup scripts, etc.)
