### ISSUE TITLE
apiserver leaks memory cause by bookmark

### ISSUE THREAD

**Issue by ricky1993** [kubernetes/kubernetes#80690]
**What happened**:
I try to backport bookmark feature to our internal branch. When I enable bookmark feature, apiserver leaks memory. I spend some time to dig the root cause and find the bookmarkWatchers of service cacher is keep increasing. I am not sure if it exists at upstream code. Please let me know if it is ok at latest code.

**What you expected to happen**:
Avoid memory leaking

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a cluster.
2. Do not update service.
3. You will find kube-apiserver's memory keep increasing.

**Anything else we need to know?**:
Kubelet will watch service with bookmark, and add a watcher to bookmarkWatchers.
https://github.com/kubernetes/kubernetes/blob/23649560c060ad6cd82da8da42302f8f7e38cf1e/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L508-L510

and service init resource version is 0
https://github.com/kubernetes/kubernetes/blob/23649560c060ad6cd82da8da42302f8f7e38cf1e/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L773

Without updating service, we cannot update "lastProcessedResourceVersion", it will keep 0,  bookmarkTimer branch will always be continued.
https://github.com/kubernetes/kubernetes/blob/23649560c060ad6cd82da8da42302f8f7e38cf1e/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L774-L802

As a result, it cannot trigger popExpiredWatchers, so the service watcher will keep increasing every watching.
https://github.com/kubernetes/kubernetes/blob/23649560c060ad6cd82da8da42302f8f7e38cf1e/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L197

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ricky1993** [comment]
/sig scalability
@wojtek-t PLAT :)

**Comment by tedyu** [comment]
```
diff --git a/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go b/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
index 2fa49efaff..5c5d898d71 100644
--- a/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
+++ b/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
@@ -784,6 +784,8 @@ func (c *Cacher) dispatchEvents() {
                        // Never send a bookmark event if we did not see an event here, this is fine
                        // because we don't provide any guarantees on sending bookmarks.
                        if lastProcessedResourceVersion == 0 {
+                               // pop expired watchers in case there has been no service update
+                               c.startDispatchingBookmarkEvents()
                                continue
                        }
                        bookmarkEvent := &watchCacheEvent{
```

**Comment by wojtek-t** [comment]
@hormes - can you also please take a look?

**Comment by ricky1993** [comment]
@tedyu Agree with u. That's same way I fix in our branch.
But I wanna hear the suggestion of @wojtek-t and @hormes .

**Comment by ricky1993** [comment]
![image](https://user-images.githubusercontent.com/10073361/62018263-957e6e80-b1ec-11e9-8a33-4519b0fe8a15.png)
With the same bugfix @tedyu wrote above, we can see the memory not increasing any more.

**Comment by wojtek-t** [comment]
Given that watch-bookmarks doesn't create any additional go-routines (well, creates 1, but cannot leak them), it has to leak the data. The only data that can be leaked is exactly bookmarkWatchers.

So I looked into the code and got into exactly the same conclusion - that we must be leaking watchers for resources that aren't changing.

The fix as above makes sense (though we also need a unit test for it).

**Comment by ricky1993** [comment]
Thanks a lot.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/80692 has the fix by @tedyu

**Comment by hormes** [comment]
Thanks for reporting the bug, I will look at #80692 this day later.

In addition, also need to think carefully about whether need to send a bookmark when there are no events at all. @wojtek-t

**Comment by zuoxiu-antfinancial** [comment]
cc @adohe
