### ISSUE TITLE
need help with examples/iscsi

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#8070]
Hi @rootfs, I'm trying to update the examples/iscsi to v1beta3. I'm having trouble install iscsitarget-dkms on Debian node of my kubernetes cluster. I've tried various versions of iscsitarget-dkms but none of them works. Could you let me know if there is any workaround, or could you validate the iscsi.json in the v1beta3 folder on your cluster so that we can merge it? Thank you.

@nikhiljindal

**Comment by rootfs** [comment]
what was the error you got on the node? you probably needs to install iscsi initiator on your node (not iscsi target, which lives out of kube). A reference can be found here http://www.server-world.info/en/note?os=Debian_7.0&p=iscsi&f=2

I haven't tried debian, my test was on fedora 21.

**Comment by rootfs** [comment]
@jsafrane

**Comment by caesarxuchao** [comment]
Thank you @rootfs. I am following the server-world reference. I have tried to install several versions of iscsitarget: 
```
iscsitarget-dkms (1.4.20.2-10.1)
iscsitarget-dkms_1.4.20.3+svn490-2ubuntu1_all.deb
iscsitarget-dkms_1.4.20.3+svn499-0ubuntu2_all.deb
```
None of them can be made successfully. The error I got for iscsitarget-dkms_1.4.20.3+svn499-0ubuntu2_all.deb is 
```
/var/lib/dkms/iscsitarget/1.4.20.3+svn499/build/kernel/block-io.c:90:6: error: ‘struct bio’ has no member named ‘bi_sector’
```

This is the 'uname -a' of my node:
```
uname -a
Linux kubernetes-minion-74ge 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1~bpo70+1 (2015-04-27) x86_64 GNU/Linux
```

**Comment by rootfs** [comment]
This error looks a kernel mismatch. Debian site suggests latest is [svn502](https://packages.debian.org/stable/kernel/iscsitarget-dkms). 

I personally haven't tested this iscsi target, I used [Linux SCSI target](http://linux-iscsi.org/wiki/Targetcli), but debian doesn't seem to support it.

Back to my first question, do you have to install iscsi target (instead of initiator) on your debian node? Since kubelet only uses iscsi initiator to use the resources that iscsi target provides.

**Comment by rootfs** [comment]
there is yet another iscsi target you can try on debian
https://packages.debian.org/jessie/tgt

**Comment by caesarxuchao** [comment]
Thanks. I see. I guess I can create another node running Fedora and run iscsi target there, then I only need iscsi initiator on the debian node, right?

**Comment by rootfs** [comment]
yes, that'll make life easier

**Comment by caesarxuchao** [comment]
Hi @rootfs, I'm able to start the iscsitarget on a node running ubuntu 12.04. I can log in to the target and show the session using iscsiadm. But when I try to create the pod, it's never deployed, I got a "Image: kubernetes/pause is not ready on the node" message. 

Here is some information may help the dubugging.
* I noticed that after I created the pod, the iscsiadm on the initiator node did create a session with the target:
```
root@kubernetes-minion-bz1p:/home/xuchao# iscsiadm -m session -o show
tcp: [4] 10.240.205.13:3260,1 iqn.2012-07.world.server:target0
```

* I setup the initiator following this [tutorial] (http://www.server-world.info/en/note?os=Debian_7.0&p=iscsi&f=2). I didn't use "parted" or "mkfs.ext4" to partition the iscsi device.

* here is my pod.json file:
```
 {
     "id": "iscsipd",
     "kind": "Pod",
     "apiVersion": "v1beta1",
     "desiredState": {
         "manifest": {
             "version": "v1beta1",
             "id": "iscsipd",
             "containers": [
                 {
                     "name": "iscsipd-ro",
                     "image": "kubernetes/pause",
                     "volumeMounts": [
                         {
                             "mountPath": "/mnt/iscsipd",
                             "name": "iscsipd-ro"
                         }
                     ]
                 }
             ],
             "volumes": [
                 {
                     "name": "iscsipd-ro",
                     "source": {
                         "iscsi": {
                             "targetPortal": "10.240.205.13:3260",
                             "iqn": "iqn.2012-07.world.server:target0",
                             "lun": 0,
                             "fsType": "ext4",
                             "readOnly": false
                         }
                     }
                 }
             ]
         }
     },
     "nodeSelector": {
         "name": "iscsi"
     }
 
 }
```

**Comment by jsafrane** [comment]
>  I didn't use "parted" or "mkfs.ext4" to partition the iscsi device.

Kubernetes expect that there is a filesystem on the device. It won't create one for you. You should call mkfs.ext4 on the device either on the iscsi target or the initatior.

**Comment by caesarxuchao** [comment]
@jsafrane Thanks. That makes sense.

**Comment by caesarxuchao** [comment]
I can successfully repeat the example/iscsi. But the first several times of creating the pods always fail. 
```
POD       IP            CONTAINER(S)   IMAGE(S)           HOST                                    LABELS    STATUS    CREATED     MESSAGE
iscsipd   10.244.3.13                                     kubernetes-minion-bz1p/104.154.61.231   <none>    Pending   3 minutes
                        iscsipd-rw     kubernetes/pause                                                     Waiting               API error (500): Cannot start container fb83
f31c1273ddfa075fe90552b3c13d5017698bbe45079e7b05d0e72556eaee: [8] System error: read parent: connection reset by peer

                    iscsipd-ro   kubernetes/pause                       Waiting             API error (500): Cannot start container 4bc2f3bb9f9aadc3e4f12d98129411e185481c29a8
ede8533e4ee83baea81d8e: [8] System error: read parent: connection reset by peer
```

and the dmesg on the node shows this repeatedly:
```
[88964.319009] aufs au_opts_verify:1570:docker[32310]: dirperm1 breaks the protection by the permission bits on the lower branch
[88964.950312] aufs au_opts_verify:1570:docker[32310]: dirperm1 breaks the protection by the permission bits on the lower branch
[88964.979445] aufs au_opts_verify:1570:docker[32310]: dirperm1 breaks the protection by the permission bits on the lower branch
[88965.045433] aufs au_opts_verify:1570:docker[32310]: dirperm1 breaks the protection by the permission bits on the lower branch
[88965.057635] aufs au_opts_verify:1570:docker[32310]: dirperm1 breaks the protection by the permission bits on the lower branch
[88965.075268] aufs au_opts_verify:1570:docker[32310]: dirperm1 breaks the protection by the permission bits on the lower branch
[88974.217840] EXT4-fs (sdb): re-mounted. Opts: (null)
```

After creating/deleting the pod many times, then I can always create the pod without any problem. When I check dmesg, it still records the "dirperm1 breaks the protection by the permission bits on the lower branch", but only once, not repeatedly.

Could someone suggest what causes this? Thanks.

**Comment by rootfs** [comment]
about that annoying message, it seems a [reported docker problem](https://github.com/dockerimages/docker-systemd/issues/1)

**Comment by lavalamp** [comment]
Closing as this seems obsolete. Reopen if not.
