### ISSUE TITLE
Support Container Isolation of Hugepages

### ISSUE THREAD

**Issue by bg-chun** [kubernetes/kubernetes#80716]
**What would you like to be added**:
/kind feature

**Why is this needed**:

This issue is intended to start discussion for future enhancement of kubelet.

## What is an issue?
- At this point, Kubernetes supports only pod isolation of hugepages where aggregated hugepages each container requests in a pod are managed as pod's resource in total. (even Hugepages are specified as ‘hugepages-<size>’ field under container field of Pod spec.)
- The problem will happen if one of containers in a pod consumes a hugepage resource larger than one requested before, which leads unexpected starvation of hugepages to the other containers in same pod. 
- As an concrete example, if a pod has two containers and each requests 4 1GB hugepages, then the current kubelet assigns 8 1GB hugepages to the pod in total. In this situation, it is possible that one container with faulty implementation for hugepage usage consume all hugepages. Then the other can not use the requested 4 hugepages.

## Current implementation
- At first, pod isolation of hugepages in kubelet is performed by adding all requested hugepage limits over containers in a pod (see below).
https://github.com/kubernetes/kubernetes/blob/a78cd38532421bf336e66a02fbcd5f8f9431ac04/pkg/kubelet/cm/pod_container_manager_linux.go#L79 https://github.com/kubernetes/kubernetes/blob/a78cd38532421bf336e66a02fbcd5f8f9431ac04/pkg/kubelet/cm/pod_container_manager_linux.go#L87 https://github.com/kubernetes/kubernetes/blob/a78cd38532421bf336e66a02fbcd5f8f9431ac04/pkg/kubelet/cm/helpers_linux.go#L142-L149
Then kubelet sets the aggregated hugepage limitation on pod's cgroup under hugetlb subsystem.
https://github.com/kubernetes/kubernetes/blob/a78cd38532421bf336e66a02fbcd5f8f9431ac04/pkg/kubelet/cm/pod_container_manager_linux.go#L92
- Current CRI implementation([LinuxContainerResources](https://github.com/kubernetes/cri-api/blob/247eeb1afecb07101bb58883f79b8b463864b035/pkg/apis/runtime/v1alpha2/api.pb.go#L2204)) does not support to update hugepage limit at all even though [OCI runtime specification](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#huge-page-limits) specifies ‘hugepageLimits’ for Container.for container as below.
>     "hugepageLimits": [
>        {
>            "pageSize": "2MB",
>            "limit": 209715200
>        },
>        {
>            "pageSize": "64KB",
>            "limit": 1000000
>        }
>     ] 

## Conclusion
- First, CRI implementation(LinuxContainerResources) should be enhanced to support "hugepageLimits".
- Second, containerd and runc should support to set hugepage limitation on container's cgroup.

## Related Issue and KEP
- Issue: [Hardware topology awareness at node level (including NUMA)](https://github.com/kubernetes/kubernetes/issues/49964)
- KEP: [Node Topology Manager](https://github.com/kubernetes/enhancements/blob/dcc8c7241513373b606198ab0405634af643c500/keps/sig-node/0035-20190130-topology-manager.md)
- KEP: [HugePages support in Kubernetes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-hugepages.md)

**Comment by bg-chun** [comment]
@ConnorDoyle @balajismaniam @lmdaly @derekwaynecarr @sjenning @PiotrProkop @dchen1107 
Hi all!
I have a plan for this issue, I wanna get any comment from you guys. :)

As i mentioned above, it seems current hugepages implementation has a potential issue(Resource Startving).
And my plan is writing a new KEP to address it.
But my concern is this is not only matter of kubernetes but also containerd, runc and other runtimes.
Below is my personal thought for new KEP.

### Goal of KEP: support Container Isolation of Hugepages
### Alpha
- use magic(set container's hugepage limits directly from kublet)
-new feature flag(default: false)
### Beta
- enhance LinuxContainerResources to support hugepage config for container.
-feature flag(default: false)
### GA
- waiting for containerd and runc support to hugepage config 
- remove magic(Alpha impl) and set Beta impl to default.
- feature flag(default: true)
- then Graduation!

**Comment by derekwaynecarr** [comment]
/assign

i will try to prioritize review of the kep in the next couple weeks.  thanks for engaging with the us.

**Comment by derekwaynecarr** [comment]
is it possible to open a PR that acts as a delta on the existing huge pages kep so we can iterate on a pr rather than this issue?

**Comment by odinuge** [comment]
I have also done some thinking about this, and agree with you that it would be a nice feature.

In order to do this, I also think we have to rethink the way we mount the huge page volume, since volumes are a part of the pod spec and not the container spec. Today it is implemented using an emptyDir with medium `HugePages`. Since a pod only can use on huge page size at a time, and the requested huge page memory is "pod wide" this works. I think it is natural next step together with this (or at least something we should consider), is to allow two containers to request different huge page sizes. We then have to solve the volume issue in a way that is intuitive to the user, while still making it simple and usable.

I am also willing to work on this, both the KEP and the implementation! :smile:

**Comment by lmdaly** [comment]
+1 on enhancing this feature and to take advantage of the upcoming Topology Manager

**Comment by bg-chun** [comment]
Regarding Memory Manager KEP, my original thought was a writing a single KEP that covers 1) enhancing current hugepage feature and 2) proposing new Memory Manager.

But it seems that updating exist hugepage KEP and writing KEP for Memory Manager is the better way(as @derekwaynecarr mentioned above).

Now, i'm working to migrate "hugepages content" to original hugepage KEP.
I guess it will be done soon(8/5 or 8/6).

**Comment by derekwaynecarr** [comment]
thanks @bg-chun , i would also like to understand what workloads are targeted that demand more than one page size per node before taking on multiple page sizes per node.  we restricted it to a single page size per node for simplicity.

**Comment by bg-chun** [comment]
@derekwaynecarr , @odinuge
As mentioned in official [docs](https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/#before-you-begin), Kubernetes supports only single page size per node.
**I don't against it at all.**

My personal thought is there is no **actual** use case that containers consume 1GB-hugepages  and 2MB-hugepages together in a same pod(at least in NFV world).

Concept of hugepages is boosting I/O access performance by reducing TLB miss. If CPU supports 1GB-hugepages and there is enough memory on server machine, why do we use a 2MB-hugepages? As i know, nowadays most of modern CPU supports 1GB-hugepages.

**Comment by bg-chun** [comment]
Regarding Memory Manager, I file an issue and open a new KEP for it.

[Memory Manager]
Issue: Support isolating memory to single NUMA node
https://github.com/kubernetes/kubernetes/issues/81009
 
KEP: Propose Memory Manager for NUMA awareness
https://github.com/kubernetes/enhancements/pull/1203
 

[Hugepages]
Issue: Support Container Isolation of Hugepages
https://github.com/kubernetes/kubernetes/issues/80716 

KEP: update existing hugepages kep
https://github.com/kubernetes/enhancements/pull/1199
