### ISSUE TITLE
[kubelet]pods become MatchNodeSelector after reboot master nodes in cluster

### ISSUE THREAD

**Issue by mzyfree** [kubernetes/kubernetes#80745]
**What happened**:
My K8S Cluster has three masters with a vip.Some pods become matchNodeSelector when I reboot three master nodes at the same time.

**What you expected to happen**:
All pods are running.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy three masters and reboot them at the same time.

**Anything else we need to know?**:
Kubelet ListAndWatch Pod/Node connections to Apiserver are always refused when the vip is not ready after reboot three nodes at the same time.
 log show:

> E0729 11:14:30.570669    2016 reflector.go:205] matrix debug haha k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.99.212.145:6443/api/v1/pods?fieldSelector=spec.nodeName%3D180&limit=500&resourceVersion=0: dial tcp 10.99.212.145:6443: connect: connection refused
E0729 11:14:30.573812    2016 reflector.go:205] matrix debug haha k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Get https://10.99.212.145:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.99.212.145:6443: connect: connection refused
E0729 11:14:30.574846    2016 reflector.go:205] matrix debug haha k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get https://10.99.212.145:6443/api/v1/nodes?fieldSelector=metadata.name%3D180&limit=500&resourceVersion=0: dial tcp 10.99.212.145:6443: connect: connection refused

These three LW threads failed and restart in the order LW pods --> LW services --> LW nodes.When the vip and the apiserver are ready,LW pods will push the pods config into the cache and the updates channel,trigger HandlePodAdditions() and canAdmitPod().But the node info is not ready in cache so kubelet inits an original node info without the labels through api.Then the pod in canAdmitPod() leads to MatchNodeSelector status.
log show:

> I0729 11:14:43.652258    2016 predicates.go:785] matrix debug: node 180, labels map[kubernetes.io/hostname:180 beta.kubernetes.io/os:linux beta.kubernetes.io/arch:amd64],pod influxdb-nginx-65wdb, selector map[role:master].
I0729 11:14:43.652366    2016 kubelet_getters.go:217] matrix debug 02 else: node: nil, error: node "180" not found, time: 2019-07-29 11:14:43.652360613 +0000 UTC m=+38.389099613.
I0729 11:14:43.652381    2016 kubelet_node_status.go:274] Setting node annotation to enable volume controller attach/detach
I0729 11:14:43.656450    2016 predicates.go:785] matrix debug: node 180, labels map[beta.kubernetes.io/os:linux beta.kubernetes.io/arch:amd64 kubernetes.io/hostname:180],pod influxdb-rs1-7cccfb8764-gb645, selector map[master:master1].

So can we just change the LW threads to order nodes --> pods --> service due to admit pods depending on the node information from cache？cni plugin multus has a bug when deleting matchNodeSelector pods.It does not free pods' ip when deleting the matchNodeSelector pods ,due to get pod info from apiserver failed ,while the info has been force deleted by apiserver ,not a graceful deleting on failed status pod.

**Environment**:
- Kubernetes version (use `kubectl version`):
 v1.11.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
- Kernel (e.g. `uname -a`):
Linux 181 3.10.0-862.el7.x86_64
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
multus
- Others:
NAME      STATUS    ROLES     AGE       VERSION
180       Ready     master    6d        v1.11.5
181       Ready     master    6d        v1.11.5
182       Ready     master    6d        v1.11.5

**Comment by mattjmcnaughton** [comment]
Hi @mzyfree ! Thanks for the detailed description of your issue. It looks like you are currently using version 1.11.5 of k8s, which is no longer supported. Would it be possible for you to upgrade to 1.13, 1.14, or 1.15? I think that will make it easier for the community to help you debug (and your issue may have even already been fixed).

**Comment by zouyee** [comment]
/assign 
 
The problem also exists in the 1.13.2

**Comment by mzyfree** [comment]
@mattjmcnaughton 
The problem maybe exists in v1.15.0,I read the 1.15.0 kubelet code and the order does not change.But I haven't done any test to verify it.

**Comment by lukasmrtvy** [comment]
I can confirm this. I am using kubespray (v2.12.5, baremetal), problem is with deployments using node selector.
After cluster restart, ( all masters ) a lot of pods will get MatchNodeSelector state. ( Perfect answer: https://stackoverflow.com/questions/56609029/how-pod-status-becomes-matchnodeselector/61402065#61402065 )

Labels are set via API:
* kubectl label node node1 foo=bar
* kubectl patch node node1  -p '{"metadata":{"labels":{"foo":"bar"}}}'

AFAIK, `kubelet --node-labels foo=bar` will work only on first registration => not possible to dynamically change kubelet labels to prevent this behaviour.

Any idea? Is there something like Node API cache? 

Thanks
