### ISSUE TITLE
TestStartupSequenceHealthzAndReadyz in top 3 flaking integration tests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#80748]
**Which jobs are failing**:
pull-kubernetes-integration

**Which test(s) are failing**:
TestStartupSequenceHealthzAndReadyz

http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Since when has it been failing**:

**Testgrid link**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestStartupSequenceHealthzAndReadyz

**Reason for failure**:

**Anything else we need to know**:

/sig api-machinery
/assign @logicalhan

**Comment by logicalhan** [comment]
I'll investigate.

**Comment by liggitt** [comment]
flake fixed in https://github.com/kubernetes/kubernetes/pull/80928

/close
