### ISSUE TITLE
Remove compute-rw scope from GCE nodes

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#8074]
AFAIK this is currently necessary only for mounting GCE PDs onto a kubelet. If we moved the PD mounting from the kubelet to the master then we could drop this scope from the node VMs.

**Comment by lavalamp** [comment]
Agree with goal, but not with proposed solution. My preferred solution here is to declare that the cloud provider library is responsible for getting auth tokens for any operations it needs to perform, and write that logic there. Reasoning:

* There's no convenient master component to stick this logic into.
* Counting on the default scopes that come with VM creation is a non-solution anyway, since e.g. some parties want to do cross-project VMs and scopes in GCE at least don't work that way AFAIK.
* Making the cloud provider library responsible for this provides a model that should work in all environments.
* This will be a lot less code churn (i.e., no api change) than moving the mount call out of kubelet.

**Comment by roberthbailey** [comment]
Would that be the cloud provider library that is part of the kubelet? If so, how does that allow us to remove the overly broad scopes? Or are you saying that something on the master would get the auth token and pass it to the kubelet (maybe as part of the pod spec)?

**Comment by lavalamp** [comment]
We already have a mechanism to pass a configuration file to the cloud
provider; we could use that. Master could make a secret for kubelets with
an auth token. Or we could do that at start up time.

**Comment by cjcullen** [comment]
On GCE, we have to end up with a Google trusted (not just k8s master trusted), compute-rw scoped access token at the point where we make the AttachDisk call.
If we want this call to happen in the kubelet (as it does today), I see three options:

1. Node VM has compute-rw scope (status quo). Google client libraries know how to get access token from metadata server.
  * This means that everything running on that node also has compute-rw capabilities (trivially).

2. Node VM gets refresh token passed to cloudprovider config at startup. Configure Google client calls to exchange refresh token for access token (or use cached access token).
  * This would mean that anything that can see that config has permanent (until revoked) compute-rw access.
  * I'm also not sure if we have a way to dish out service account tokens, so these might have to be end-user credentials, which is bad.

3. Node VM gets a master-created secret at startup, uses that secret to request access tokens from master, then makes Google client calls with those tokens.
  * Anything that can see that secret can get (short-lived) compute-rw access.
  * We are putting the master in the loop, why not just make it responsible.

If we had a PersistentDiskController in the master, it could just find scheduled pods that need disks attached, and find attached disks that are no longer needed by the current set of scheduled pods.

If we say that the cloudprovider inside kubelet is responsible for being able to make authorized requests, I think we are also saying that anything within the same security boundary as the kubelet will be able to make the same authorized requests.

**Comment by erictune** [comment]
From a security standpoint, I like the idea of a PersistentDiskController
which runs wherever its runs (let's try not to use the word master), and
which has a GCE token to let it mount disks.

Need to analyze what happens in bootstrapping and failure situation.

Also, wonder how many other types of cluster filesystems support a remote
attachment approach.  If it is just GCE, maybe not worthwhile.

Another option is to wait until GCE has some sort of finer grained
permissions.

**Comment by cjcullen** [comment]
And if we move to a reconciler-style controller for attaching the disk, we'd decouple that from the local mounting that kubelet has to do, hopefully preventing issues like #7972.

**Comment by cvle** [comment]
Having the Attach/Detach Controller landed in 1.3 (https://github.com/kubernetes/kubernetes/pull/26351), does it mean we can remove the compute-rw scope from the nodes?

**Comment by roberthbailey** [comment]
That (and moving the ingress controller to the master) were the last remaining things that I knew of blocking us, but we'd need to run e2e tests on a cluster w/o scopes to see what might have picked up an inadvertent dependency on having the scope available. 

For example, @vishh found (in https://github.com/kubernetes/kubernetes/pull/28871) that the kubelet had picked up a dependency on having a service account attached to the VM. There may be other dependencies that we haven't found yet.

**Comment by vishh** [comment]
Auto-configuring gcr.io credentials require service accounts as of now. I
wonder if there is a way to work around that?
