### ISSUE TITLE
kube-apiserver print  lots of grpc log: got update addr from Notify

### ISSUE THREAD

**Issue by RayHuangCN** [kubernetes/kubernetes#80741]
I got lots of logs like: 
I0730 15:38:27.137684       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{etcd.xxx.com:2379 <nil>}]
I0730 15:38:27.137709       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{etcd.xxx.com:2379 <nil>}]
I0730 15:38:27.137733       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{etcd.xxx.com:2379 <nil>}]
I0730 15:38:27.142843       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{etcd.xxx.com:2379 <nil>}]

(10+ lines / 20s)

etcd.xxx.com is LB of etcd cluster
kube-apiserver version is 1.14.3 
i found that cluster can work normally
so ,how can i close those logs??

**Comment by tedyu** [comment]
This is from vendor/google.golang.org/grpc/balancer_v1_wrapper.go

Maybe surface to grpc project ?

**Comment by xieydd** [comment]
I meet this problem too, k8s version is 1.15.1

**Comment by gyuho** [comment]
We do set the gRPC logger by default, in etcd

https://github.com/etcd-io/etcd/blob/a65e4d3357c260504d47f08a433b355e36dbcb51/clientv3/logger.go#L36-L40

to ignore all such logs.

@jpbetz @liggitt Do we override gRPC logger somewhere in kube-apiserver?

I tried

```
env:
- name: GRPC_GO_LOG_SEVERITY_LEVEL
  value: warning
```

but no luck...

```
I1017 18:22:59.790791       6 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: []
I1017 18:22:59.790877       6 controlbuf.go:382] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I1017 18:22:59.790986       6 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{...:2379 <nil>}]
I1017 18:22:59.791038       6 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{...:2379 <nil>}]
I1017 18:22:59.793949       6 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{...:2379 <nil>}]
```

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/logger.go#L27

**Comment by liggitt** [comment]
should we adjust the klog adapter to make all info-level logs from etcd a higher verbosity (e.g. V3 or V4?)

**Comment by tedyu** [comment]
V3 sounds good to me.

**Comment by gyuho** [comment]
@liggitt I think we need a way to disable the whole `Info` level logging in `klog` package. Can we translate the kube-apiserver log level to gRPC log writer? Seems like gRPC doesn't really use leveled logging. For example, even if we set the log level, this line will still print:

https://github.com/grpc/grpc-go/blob/7c8e60372e19da88fb3fe8ac6a8de781eef7f547/balancer_v1_wrapper.go#L116

which runs for every single gRPC connection.

To discard info level logging in gRPC, we can pass `ioutil.Discard` to `grpclog.NewLoggerV2` or `grpclog.NewLoggerV2WithVerbosity`. Or implement this to the `klog`?

**Comment by gyuho** [comment]
On second thought, I don't think we need gRPC info level logs at all. etcd client is migrating to zap logger, and it logs all the critical information.
