### ISSUE TITLE
Kubernetes logs with label selector does not work for some labels

### ISSUE THREAD

**Issue by imriss** [kubernetes/kubernetes#80751]
**What happened**:
When retrieving the logs using `kubectl logs -l`, it returns the logs for some of the labels, but it does not return anything for some other labels.

For example:
```
~/ $ kubectl logs -n test -lapp=testapp
~/ $ kubectl logs -n test -lapp.kubernetes.io/instance=test
2019-07-30 15:28:39.913  INFO 1 ---
```

The labels of the deployment:
```
~/ $ kubectl get deployments.apps -n test --show-labels 
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE     LABELS
testapp                 1/1     1            1           55m     app.kubernetes.io/instance=test,app=testapp
```

**What you expected to happen**:
To see the logs when I use the label selector for the `app` label.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-11T03:47:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
`EKS`

- OS (e.g: `cat /etc/os-release`):
Nodes:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
Terminal: `Arch Linux`

- Kernel (e.g. `uname -a`):
Nodes: `4.14.128-112.105.amzn2.x86_64`
Terminal: `5.2.3-arch1-1-ARCH`

- Install tools:
`EKS`
- Network plugin and version (if this is a network-related bug):
N/A
- Others:
N/A

Thanks

**Comment by liggitt** [comment]
what are the labels on the pods?

**Comment by imriss** [comment]
@liggitt Thanks. I think that it was my mistake. At first, I put the `app` label in:
```
metadata:
  labels:
```
Now, when I moved it to here, the issue was resolved, and logs appeared:
```
spec:
  template:
    metadata:
      labels:
```

**Comment by liggitt** [comment]
yes, by default `kubectl logs` looks for pods. you can also do `kubectl logs deployment/testapp` and it will look up the selector from the deployment object and find the right pods for you
