### ISSUE TITLE
Conformance Tests for AdmissionWebhook

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#80767]
- [x] write e2e tests for all admission operations
   - [x] https://github.com/kubernetes/kubernetes/pull/81381 (for resource APIs)
   - [ ] https://github.com/kubernetes/kubernetes/pull/82019 (for discovery docs)
   - [apisnoop beta admissionregistration coverage](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-beta-admissionregistration)
- [x] switch to v1 admission APIs in e2e - https://github.com/kubernetes/kubernetes/pull/81558
    - [apisnoop stable admissionregistration coverage](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-stable-admissionregistration)
- [x] remove skips/time.Sleeps - https://github.com/kubernetes/kubernetes/pull/81684
- [ ] [monitor for flakes](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=AdmissionWebhook&show-stale-tests=&width=5&sort-by-flakiness=) and promote to conformance tests - https://github.com/kubernetes/kubernetes/pull/81857

AdmissionWebhook should have tests for all stable operations.
Those tests should go through the conformance process before being released.
This ticket is to help track what operations are yet to be covered by conformance tests.

## 15 Untested Stable Operations need Conformance Tests

These stable endpoints should be hit by e2e tests tagged with [conformance].
There are tests currently hitting 6 of the corresponding beta endpoints that could be updated to use stable.
Tests should be written to exercise the remaining 9 untested stable endpoints as well.

## 12 Tests that hit 6 out of 15 Beta Operations

These twelve tests could be updated to use the stable API, and subsequently promoted to conformance.

[apisnoop.cncf.io tests for listAdmissionregistrationV1beta1ValidatingWebhookConfiguration](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=operationId-beta-admissionregistration-listAdmissionregistrationV1beta1ValidatingWebhookConfiguration) / [test-grid](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=AdmissionWebhook&show-stale-tests=)

![image](https://user-images.githubusercontent.com/31331/62168173-0bafdc00-b379-11e9-92ec-521d5a4659bb.png)

![image](https://user-images.githubusercontent.com/31331/62166416-d2756d00-b374-11e9-9f87-c3da66c72bb0.png)

## Remaining 9 Untested Beta Operations

These will need tests written for them.

[apisnoop.cncf.io untested beta/admissionregistration](https://apisnoop.cncf.io/?showUntested=true&showTested=false&showConformanceTested=false&zoomed=category-beta-admissionregistration
) 

![image](https://user-images.githubusercontent.com/31331/62166638-69422980-b375-11e9-8d65-0402ca7c05e0.png)

**Comment by timothysc** [comment]
/assign @caesarxuchao  
^ This is a requirement for graduation to GA.

**Comment by jpbetz** [comment]
@hh can we get another apisnoop run? We've added coverage for admissionregistration and apiextensions and I'd like to get confirmation from apisnoop that we've got full coverage now.

**Comment by liggitt** [comment]
Keeping this open until tests are actually promoted to conformance

**Comment by jpbetz** [comment]
https://github.com/kubernetes/kubernetes/pull/81857 is ready for review. It adds our admission e2e tests to conformance as part of graduation to GA.

**Comment by hh** [comment]
apisnoop.cncf.io is updated @jpbetz

- [getAdmissionregistrationV1APIResources](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=operationId-stable-admissionregistration-getAdmissionregistrationV1APIResources) is currently your only API operation hit by a Conformance test.

- [getAdmissionregistrationAPIGroup](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=operationId-stable-admissionregistration-getAdmissionregistrationAPIGroup) is currently not hit by any tests, one will need to be updated or written to cover it.

The 14 other API operations / endpoints of stable / admissionregistration that have tests we will need to promote some of them to Conformance by adding the [Conformance] tag.

The sig-architecture instruction for promotion are [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#promoting-tests-to-conformance), or @ii can give a hand.

https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-stable-admissionregistration

![image](https://user-images.githubusercontent.com/31331/63736167-52401a00-c8d6-11e9-9cef-132d4b5a9001.png)
