### ISSUE TITLE
Allow Filter plugins of the scheduling framework to identify whether a pod could be schedulable after preemption

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#80775]
**What would you like to be added:**
`Filter` plugins of the scheduling framework need to indicate whether a pod that is unschedulable on a node could potentially be schedulable if one or more other existing pods are removed from the node. In other words, whether preemption can help make the pod schedulable. For example, a taint filter may return an "unresolvable" infeasibility for a node, because removal of other pods is not going to change taints, while a resource check filter return a "resovable" infeasibility.

One idea to address this problem is to add another [`Status.Code`](https://github.com/kubernetes/kubernetes/blob/75d51896125b1cafd9e995212b02ccda9b8a0aed/pkg/scheduler/framework/v1alpha1/interface.go#L48) for unresolvable infeasibility. We currently have `Unschedulable`. We can add something like `UnschedulableAndUnresolvable` (or a better name). If a filter plugin returns this code for a node, the scheduler will not attempt preemption for that node.

Another idea is to put the information in the scheduler plugin config. For each filter plugin, the config indicates whether it is resolvable or not. This will act similar to what we [currently have in the scheduler code](https://github.com/kubernetes/kubernetes/blob/75d51896125b1cafd9e995212b02ccda9b8a0aed/pkg/scheduler/core/generic_scheduler.go#L65) (it is hard coded). This approach works well too, but it is static. The previous approach allows filter plugins to return different codes dynamically and depending on the conditions of the cluster. For example, a plugin that checks availability of resources may return `UnschedulableAndUnresolvable` when it sees that the incoming pod has lower priority than all other existing pods on the node.

Please share your opinion about the two approaches or other proposals so that we can choose one to implement.

/sig scheduling
/priority important-soon
ref/ kubernetes/enhancements#624

**Comment by hex108** [comment]
Prefer the first idea. :)

>  For each filter plugin, the config indicates whether it is resolvable or not. 

A filter plugin might contains both taint filter and common filter(e.g. resource filter), so the config might not work for these plugins.

**Comment by ahg-g** [comment]
> A filter plugin might contains both taint filter and common filter(e.g. resource filter), so the config might not work for these plugins.

I don't think we want to encourage this pattern, a plugin should be implementing a single feature.

**Comment by bsalamat** [comment]
> Prefer the first idea. :)

+1 

> A filter plugin might contains both taint filter and common filter(e.g. resource filter), so the config might not work for these plugins.

I agree with ahg-g that this is not a great design pattern for plugins, but even in such cases a plugin can always be conservative and indicate that preemption can resolve infeasibility of a node. Obviously, this will be less efficient compared to a case that a plugin can indicate resolvability for each pod.

**Comment by ahg-g** [comment]
I am also leaning towards option 1, I just hope that we can somehow make it easy to track which filters are resolvable by preemption and which are not.

**Comment by Huang-Wei** [comment]
I'm also learning towards option 1.

Some other thought on this: given that a combination of two statuses (Unschedulable + Unresolvable) have emerged, **_if_** it proves to be a pretty common case, maybe we should change status.code from `itoa` to ANDable bits - like "error1" = 2<sup>1</sup>, "error2" = 2<sup>2</sup>, so if the ANDed error code is 3 (in bits it's 11), we know it represents error1 && error2. This can gives us more status info by a signle error code.

**Comment by bsalamat** [comment]
Thinking more about the two options, I think we should choose option 1 for the following reasons:

1. Whether a pod is "unschedulable but **resolvable**" or "unschedulable and **unresolvable**" is not an "option" that can be configured. It is a fact that depends on the internal logic of a filter plugin. In other words, the config option cannot be changed arbitrarily based on user preferences. So, a config option is not the right choice.

2. Option 1 makes shipping plugins easier. With option 2, each plugin must have specific instruction for users to choose the right value for the config. If a users uses a wrong value, the scheduler may not function correctly.

**Comment by ahg-g** [comment]
@Huang-Wei while using bits to represent a status addresses one issue with how to represent unschedulable and unresolvable, it opens the door for many invalid combinations.

Instead of adding a completely new status code (which means we have multiple statues representing unschedulable), how about adding a boolean to Status that indicates whether or not unschedulable is unresolvable, that way we maintain one Status.code per "status" (as in we have a single code for unschedulable).

**Comment by bsalamat** [comment]
> while using bits to represent a status addresses one issue with how to represent unschedulable and unresolvable, it opens the door for many invalid combinations.

+1

> Instead of adding a completely new status code (which means we have multiple statues representing unschedulable), how about adding a boolean to Status that indicates whether or not unschedulable is unresolvable, that way we maintain one Status.code per "status" (as in we have a single code for unschedulable).

IMO, having multiple unschedulable values is better than having a field that does not apply to codes other than "unschedulable".

**Comment by ahg-g** [comment]
I think having multiple statues that carry the same meaning is also not ideal and has the potential for bugs (like checking for "unschedulable" code and forgetting to check also for "UnschedulableUnresolvable"). I get that you can have a function to abstract that, but that I does not prevent the possibility of the problem above.

A separate member representing specific semantics I think is totally fine even if it is not applicable in all cases because you are not going to look at it unless you want more info about the status.

**Comment by bsalamat** [comment]
Yes, I agree with your point, but a function can reasonably address the problem. We already use a function for `IsSuccess` that considers both nil and the `Success` code as successful outcome. Granted, if someone is not careful, they may introduce bugs by checking the code directly and not using the function, but I'd prefer it over having an extra field. That being said, this is not a strong preference. If others prefer having an extra field, I am fine with it.

**Comment by ahg-g** [comment]
I just feel that we are combining two pieces of information in one value by combining it with the Code, but I also defer to the majority.

**Comment by draveness** [comment]
I think `UnschedulableAndUnresolvable ` is fine since we have some precedence like `RequiredDuringSchedulingIgnoredDuringExecution`

**Comment by alculquicondor** [comment]
To summarize what we have already discussed: We lean towards the option of having the plugin decide whether or not they can resolve the pod with preemption.

Pending alternatives:

1. Add a new Status code, likely `UnschedulableAndUnresolvable`
1. An extra return value for `FilterPlugin.Filter`
1. An extra field in Status.

I agree with @ahg-g's concerns for 1. I don't see problems with 2. The disadvantage of 3 is that only one type of plugin has a meaning for the value. Alternatively, the field could be `flags` and be a bitmask.

**Comment by alculquicondor** [comment]
@bsalamat any thoughts on the latest proposed solutions?

**Comment by bsalamat** [comment]
I still like option #1 with an `IsUnschedulable` function in `Status`, but I do not have a strong preference. Please feel free to proceed with other options any of those has more votes.

**Comment by alculquicondor** [comment]
The benefit of using the the new status code is that it makes it easier to pass around.
The downside is that we need to be extra careful when writing and reviewing code.

I think option 3 (extra field in Status) is both easier to pass around and easy to write and review. It only uses a tiny bit more memory, but given that the number of plugins is small, that shouldn't be an issue.

**Comment by alculquicondor** [comment]
I have a better idea that should comply with all concerns:

- Add `UnschedulableAndUnresolvable`
- Rename `Unschedulable` to `MaybeUnschedulable`
- Add `IsUnschedulable` method.

Names can be adjusted, but WDYT?

**Comment by Huang-Wei** [comment]
> Rename `Unschedulable` to `MaybeUnschedulable`

`MaybeUnschedulable` sounds vague.. My 2 cents is to keep the name `Unschedulable` or a better name.

**Comment by tedyu** [comment]
Unschedulable can be kept.
We can add godoc to explain its meaning.

**Comment by ahg-g** [comment]
I suggest we move on with @bsalamat suggestion.
