### ISSUE TITLE
Identifying Features / API Operations as optional

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#80770]
createCoreV1NamespacedServiceAccountToken is included core, but is optional and hence can't be a Conformance test.

It would be useful to know the specific API Operations/Kinds that designated feature gates enable on the API Server.

It's currently a manual process to know what operations/endpoints are optional from statically inspecting the kubernetes source or openapi spec at rest.

Other operations/endpoints are only usable once a metric-server is installed, which it's unclear how such a dependency should be discovered.

Case law question from the last SIG-Arch Conformance Subgroup meeting:
> If a feature gate goes GA, aka defaults to true, can you turn it off and still expect to be considered conformant?

**Comment by timothysc** [comment]
/cc @kubernetes/sig-architecture-misc-use-only-as-a-last-resort 

There is an issue that we have fields that exist on api objects that only work when certain args are passed the api-server.  One would argue that if they are core api's they should be on by-default, or we should craft some policy around these fields.  

/assign @bgrant0607 @liggitt @thockin @smarterclayton

**Comment by liggitt** [comment]
> openapi spec at rest

The static spec checked into the source tree is for convenience only. The authoritative source is the live discovery doc against a given API. In this case, if the API server was not started with the signing keys required to support the API, it is not enabled at all, and is not included in discovery or openapi.

For this particular API, I'm in favor of progressing it to default enabled, but it is not ambiguous whether it is available or not to clients.

**Comment by hh** [comment]
It would help if we could clearly identify which feature flags enable which API operations (and corresponding paramaters/objects).

For sake of clarification in this instance, is createCoreV1NamespacedServiceAccountToken tied to a particular feature flag?

Is there a generalized way to see the APIS a particular feature flag is connected to by examining the source / AST or is it something we can currently only detect at runtime?

**Comment by thockin** [comment]
I think we really want disabled fields to not appear in discovery schemas right?  To do that, we'd need to get to a more declarative and dynamic way of decorating the API IDL with flag gates that govern field availability, right?

**Comment by hh** [comment]
We've attempted to identify schema fields that are feature gated by inspecting the description field.

We have opened a issue to incorporate into the openapi schema via `x-schema-field-featuregate` or similar:   https://github.com/kubernetes/kubernetes/issues/81759

This allowed us to find these 4 GA schema fields that required feature gates.

The feature gating of a schema field seems unrelated to feature gating of an operation like createCoreV1NamespacedServiceAccountToken.

I'm unsure how to do this for API Operations, and it's currently it's unclear if that's possible.

req | depr | gated | schema | field
-- | -- | -- | -- | --
f | f | t | io.k8s.api.core.v1.SecurityContext | procMount
f | f | t | io.k8s.api.storage.v1.StorageClass | allowedTopologies
f | f | t | io.k8s.api.storage.v1.StorageClass | volumeBindingMode
f | f | t | io.k8s.api.core.v1.PersistentVolumeClaimSpec | dataSource

**Comment by lavalamp** [comment]
There is currently no programmatic way to determine the relationship between feature gates and api object fields or validation rules.

A thing in this category that we'd consider is showing or hiding fields based on whether a feature is enabled, but this has never won a prioritization session.

Feature gates that completely prevent an api from being installed are reflected by that api being absent in the openapi spec apiserver publishes, but there's no programatically discernible linkage back to the feature gate.

Anyway, I think conformance tests shouldn't have access to the feature gates on the cluster they're testing, so I don't understand why that is important.

> Case law question from the last SIG-Arch Conformance Subgroup meeting:

> > If a feature gate goes GA, aka defaults to true, can you turn it off and still expect to be considered conformant?

I think no, feature gates are used to turn off / try out incomplete features; feature gates are not intended for use in an ongoing manner to serve the role of configuration.

**Comment by johnbelamaric** [comment]
> I think no, feature gates are used to turn off / try out incomplete features; feature gates are not intended for use in an ongoing manner to serve the role of configuration.

+1. Once it is GA, shouldn't we clean up the feature gate?

**Comment by liggitt** [comment]
> > I think no, feature gates are used to turn off / try out incomplete features; feature gates are not intended for use in an ongoing manner to serve the role of configuration.
> 
> +1. Once it is GA, shouldn't we clean up the feature gate?

Yes, we do. Once GA, we lock the gate on (so it cannot be turned off), announce deprecation, then remove in 2 releases.

**Comment by lavalamp** [comment]
> Is there a way we can add metadata within the fields or operations that we could extract to support identifying them?

Not really. Stuff like this is on our list for being done eventually but not in a useful time frame for you.

**Comment by hh** [comment]
@lavalamp Do we have any plan/timeframes on metadata within the fields or operations that we could extract to support identifying Features->Fields?

**Comment by lmktfy** [comment]
For historical interest, this may be relevant to https://github.com/kubernetes/kubectl/issues/1852
