### ISSUE TITLE
sig-cluster-lifecycle: best practices for immutable upgrades

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#80774]
EDIT: please excuse me as this ended up being a bit long, but the TL;DR is "version skew, in-place vs re-place upgrades and cluster topology"

during today's SIG Cluster Lifecycle meeting we had a discussion that covered some aspects of upgrades that tools like kubeadm and kops perform. the discussion started at this timestamp:
https://youtu.be/mTTYQdrYUSM?t=2411

[later in the meeting](https://youtu.be/mTTYQdrYUSM?t=2852) we started discussing the topic of upgrades with replacement immutable control-plane nodes.

an example cluster:
- **[1]** control-plane 1.14, kubelet 1.14 
- control-plane 1.14, kubelet 1.14
- control-plane 1.14, kubelet 1.14
- worker kubelet 1.14
- worker kubelet 1.14
- worker kubelet 1.14

by adding a set of new immutable control-plane nodes:
- control-plane 1.15, kubelet 1.15 **[2]**
- control-plane 1.15, kubelet 1.15
- control-plane 1.15, kubelet 1.15

and then removing the old control-plane nodes, the control-plane (as a whole) of this cluster can be upgraded.

this introduces a scenario where the [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-component-upgrade-order
) is temporary violated and a kubelet with a newer version than the api-server version will temporary exists (see [2] vs [1]).

> kubelet instances on all nodes are at version 1.n or 1.(n-1) (this ensures they are not newer than the existing API server version, and are within 2 minor versions of the new API server version)

it was discussed that this violation only happens in the case when a control-plane on a node is run using static-pods on the same node. in cases where the control-plane components are not run as pods, the [recommended upgrade process order](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-component-upgrade-order) can be partially respected, given we are still updating all components at once.

however, if there is a notion that a single "control-plane node" hosts all the components, the upgrade order seems to imply mutability of a "control-plane node" as a requirement.

> The kube-apiserver instances these components communicate with are at 1.(n+1) (in HA clusters in which these control plane components can communicate with any kube-apiserver instance in the cluster, all kube-apiserver instances must be upgraded before upgrading these components)

alternatively, if the components are hosted on separate machines (or hosts) - kube-apiserver on one, and the rest of the components on another, then such machines can be replaced with new immutable machines and the order can be respected. this seems to establish the _canonical topology_ that will conform the current version skew and upgrade order definition of Kubernetes.

this raises some questions, such as:
- should immutable node upgrades be claimed as supported in cases where all the control-plane components are hosted on the same node?
  - can the introduction of such a n+1 node during upgrades lead to catastrophic behavior?
- should the kubelet version skew be extended to also cover n+1 (of the api-server version), with respect to supporting immutable upgrades where the control-plane is hosted on a node using static pods?
  - would this complicate the development process in kubernetes/kubernetes (probably yes)?
  - with the current skew, how catastrophic such a temporary violation can end up being?

/sig cluster-lifecycle
/kind design
/assign @justinsb @timothysc @neolit123 
cc @liggitt @smarterclayton @ncdc @fabriziopandini @dlipovetsky @moshloop

**Comment by liggitt** [comment]
>   * can the introduction of such a n+1 node during upgrades lead to catastrophic behavior?

yes. The kubelet assumes it can trust API content to be served from a current API server, and does not do its own defaulting of API fields. When talking to old API servers, that leads to unexpectedly nil fields (at worst) or undefined behavior (for fields whose defaults should be goverened by the API). Making both the API server and the kubelet separately responsible for knowing default behavior associated with unset fields is fragile and has been avoided.

> * should the kubelet version skew be extended to also cover n+1 (of the api-server version), with respect to supporting immutable upgrades where the control-plane is hosted on a node using static pods?

I'm hesitant to expand the skew matrix while we still lack test coverage for the matrix we already have.

>   * would this complicate the development process in kubernetes/kubernetes (probably yes)?

definitely

>   * with the current skew, how catastrophic such a temporary violation can end up being?

see above comments about nil pointers and undefined behavior

**Comment by liggitt** [comment]
(while not ideal because of the n-1 kubelet) you could achieve immutable control plane nodes with the following configuration:

kubelet: version n-1
apiserver: version n
controllers/scheduler: version n, configured to speak only to the local apiserver

**Comment by liggitt** [comment]
another possibility is to upgrade control plane nodes in phases, rolling out images which increment one component (or set of components) at a time, e.g.:
* phase 1:
  * apiserver@n
  * controllers/scheduler/kubelet@n-1
* phase 2:
  * apiserver/controllers/scheduler@n
  * kubelet@n-1
* phase 3:
  * apiserver/controllers/scheduler/kubelet@n

each phase gets its own immutable image

nice things about that:
* skew testing is pre-baked into the rollout process
* you can halt at any phase before proceeding
* once complete, all components are at version n
downsides:
* more images to build (each of which has inputs from two release streams)
* more node rollouts/churn

**Comment by neolit123** [comment]
thanks for the comments here @liggitt 
i was hoping that we can get more responses from others.

i'm going to go ahead and archive this ticket but we can always reopen the it if more people are interested in the discussion.

/close
