### ISSUE TITLE
Hide secrets exposed as environment variables if an account does not have access to it

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#80789]
**What would you like to be added**:
If an environment variable was created from a secret (eg as a `secretRef`) and if a current serviceaccount has access to describe pod, yet does not have access to the corresponding secret - it should not be exposed.

I originally posted it as a feature request to the dashboard https://github.com/kubernetes/dashboard/issues/4139

And @floreks created a demo:
```
10:21 $ kubectl get pod
NAME            READY   STATUS    RESTARTS   AGE
env-variables   1/1     Running   0          16m
10:24 $ kubectl get secret
Error from server (Forbidden): secrets is forbidden: User "system:serviceaccount:kube-system:pod-reader" cannot list resource "secrets" in API group "" in the namespace "default"
10:24 $ kubectl describe pod
Name:         env-variables
Namespace:    default
Priority:     0
Node:         kind-control-plane/172.17.0.2
Start Time:   Tue, 30 Jul 2019 10:07:20 +0200
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"env-variables","namespace":"default"},"spec":{"containers":[{"args":[...
Status:       Running
IP:           10.244.0.4
Containers:
  test-container:
    Container ID:  containerd://2d7a29241f043b2e7491704bf5cb0323dec2015992696b8c51f3d2d49e6879fd
    Image:         k8s.gcr.io/busybox
    Image ID:      sha256:36a4dca0fe6fb2a5133dc11a6c8907a97aea122613fa3e98be033959a0821a1f
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      while true; do echo -en '\n'; printenv MY_POD_NAME; printenv MY_MEM_REQUEST MY_MEM_LIMIT; printenv MY_CONST_VALUE; printenv MY_SECRET_VALUE; sleep 10; done;
    State:          Running
      Started:      Tue, 30 Jul 2019 10:07:23 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  64Mi
    Requests:
      cpu:     125m
      memory:  32Mi
    Environment:
      MY_POD_NAME:      env-variables (v1:metadata.name)
      MY_MEM_REQUEST:   33554432 (requests.memory)
      MY_MEM_LIMIT:     67108864 (limits.memory)
      MY_CONST_VALUE:   test-const-value
      MY_SECRET_VALUE:  <set to the key 'username' in secret 'secret-env'>     Optional: false
      MY_CM_VALUE:      <set to the key 'test' of config map 'configmap-env'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-468fw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-468fw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-468fw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Why is this needed**:
An account does not have access to secrets hence they should not see them, regardless at what context.

**Comment by liggitt** [comment]
it's unclear what this is asking for. kubectl describe does not show the secret value in the situation you describe (`MY_SECRET_VALUE:  <set to the key 'username' in secret 'secret-env'>     Optional: false` is omitting the value)

**Comment by zerkms** [comment]
![Screenshot from 2019-08-01 11-14-06](https://user-images.githubusercontent.com/302295/62254529-92ce8400-b44d-11e9-81ac-5a80992adbb6.png)

See the screenshot from kubernetes dashboard: here if you click on an "eye" icon you get the secret plaintext, while the account does not have any access to secrets whatsoever.

Indeed, my example does not demonstrate the problem (I did not notice that, sorry), but if the dashboard could extract it - then there is some API method that allows that. I'll try to contact the dashboard team to get more details, sorry.

**Comment by liggitt** [comment]
Yes, that would be a question for the dashboard component

/close

**Comment by zerkms** [comment]
@liggitt well, it would not: if dashboard can obtain that info using an account token that does not have access to secrets - it means they leak somewhere.

**Comment by liggitt** [comment]
All API methods require authorization. Are you logged into the dashboard as a user that has secret access? If so, the dashboard makes API requests using the API credentials you log in with.

**Comment by zerkms** [comment]
> Are you logged into the dashboard as a user that has secret access?

I'm logged as a user that DOES NOT have any secrets access (not listing or reading).

**Comment by liggitt** [comment]
The dashboard also has its own API credentials, though I didn't think those were used by the dashboard to fetch data exposed to users. If they are in this case, that is also an issue for the dashboard component

Let's move this issue to that component and get more details about the dashboard configuration and permissions.
