### ISSUE TITLE
Ability to evaluate multiple HPA metrics with "AND" operator

### ISSUE THREAD

**Issue by salmaanrizvi** [kubernetes/kubernetes#80783]
**What would you like to be added**:
Currently, multiple metrics are scaled off of an "or" condition, i.e. if either CPU or nginx.net.connections exceed their threshold, scale to ensure the failing condition is met. Ideally, we could only scale if _both_ of those conditions are met.

**Why is this needed**:
Extra resources are created / used unnecessarily if users know their application code requires attention only if both metrics are triggered. For example, say we see a spike in connections above our acceptable threshold but CPU has only been marginally impacted, the default behavior would have scaled, but we haven't seen any real impact to our application.

The argument could be made the metrics you're scaling off of should be re-evaluated but I do think there's potential for compound metrics evaluation as opposed in isolation.

@kubernetes/sig-autoscaling-feature-requests
/sig autoscaling

**Comment by bskiba** [comment]
@josephburnett for visibility

**Comment by pytimer** [comment]
@salmaanrizvi I have the same question, how to do it using HPA?
