### ISSUE TITLE
Kube-apiserver going down periodically while adding user based authentication in kubernetes

### ISSUE THREAD

**Issue by hiteshsardana99** [kubernetes/kubernetes#80791]
I am facing some issues after adding some changes in kube-apisever.yaml file for Access based authentication.

Steps that I have performed :-

1) I have installed v1.15.0 kubernetes on my ubuntu machine ( 16.04 ).

root@stack33:~# kubectl version Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

2 ) After that I have installed flannel having v0.11.0 version.

Now successfully able to up kubernetes cluster :-

Outut of kubectl get pod --all-namespaces -o wide
https://i.stack.imgur.com/33v0Q.png

Node is also in ready state.

root@stack33:/var/lib# kubectl get node NAME STATUS ROLES
AGE VERSION stack33 Ready master 17m v1.15.0

3) Added two files inside /etc/kubernetes/pki folder that is by default mounted with kube-apiserver pod.

a) policy.json

{
"apiVersion": "abac.authorization.kubernetes.io/v1beta1",
"kind": "Policy",
"spec": {
    "user": "admin",
    "namespace": "*",
    "resource": "*",
    "apiGroup": "*"
 }
}

b) known_users.csv

 admin,admin,admin
4) Final output of Kube-apiserver.yaml file

> apiVersion: v1  kind: Pod  metadata:   creationTimestamp: null  
> labels:
>     component: kube-apiserver
>     tier: control-plane   name: kube-apiserver   namespace: kube-system spec:   containers:
>   - command:
>     - kube-apiserver
>     - --advertise-address=172.19.63.33
>     - --allow-privileged=true
>     - --authorization-mode=Node,RBAC,ABAC
>     - --authorization-policy-file=/etc/kubernetes/pki/policy.json
>     - --basic-auth-file=/etc/kubernetes/pki/known_users.csv
>     - --anonymous-auth=false
>     - --bind-address=0.0.0.0
>     - --client-ca-file=/etc/kubernetes/pki/ca.crt
>     - --enable-admission-plugins=NodeRestriction
>     - --enable-bootstrap-token-auth=true
>     - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
>     - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
>     - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
>     - --etcd-servers=https://172.19.63.33:2379
>     - --insecure-port=0
>     - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
>     - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
>     - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
>     - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
>     - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
>     - --requestheader-allowed-names=front-proxy-client
>     - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
>     - --requestheader-extra-headers-prefix=X-Remote-Extra-
>     - --requestheader-group-headers=X-Remote-Group
>     - --requestheader-username-headers=X-Remote-User
>     - --secure-port=6443
>     - --service-account-key-file=/etc/kubernetes/pki/sa.pub
>     - --service-cluster-ip-range=10.96.0.0/12
>     - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
>     - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
>     image: k8s.gcr.io/kube-apiserver:v1.15.0
>     imagePullPolicy: IfNotPresent
>     livenessProbe:
>       failureThreshold: 8
>       httpGet:
>         host: 172.19.63.33
>         path: /healthz
> -
-

After doing these above steps. 1. sometimes coredns pod goes in crashloopbackoff state 2. sometimes kubeapiserver goes down periodically.

I am facing this issue everytime..

https://i.stack.imgur.com/cJV2k.png

I have tried to mount other directory also and added policy.json and known_users in that file. But not able to solve my problem.
https://superuser.com/questions/1465989/kube-apiserver-going-down-periodically-while-adding-user-based-authentication-in

**Comment by SataQiu** [comment]
Thanks for reporting it @hiteshsardana99 
I found that if you write the policy content as a single line, it worked.
```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "admin", "namespace": "*", "resource": "*", "apiGroup": "*"}}
```
Maybe it is a bug. I'll dig into this.

**Comment by SataQiu** [comment]
It's deliberately designed like this. You must wirte authorization policy in json line by line format.
Ref: https://kubernetes.io/docs/reference/access-authn-authz/abac/  
```
The file format is one JSON object per line. There should be no enclosing list or map, just one map per line.
```

**Comment by hiteshsardana99** [comment]
@SataQiu  I have used the policy content file in single file.  Actually I am able to authenticate user by adding this policy. My problem is kube-apiserver is going down periodically because cordns pods are not running properly. Coredns pods remains in crashloopbackoff. For few seconds it comes in running state .
