### ISSUE TITLE
How to deprecate/migrate scaleio volume plugin

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#80819]
Continuing discussion from https://github.com/kubernetes/kubernetes/pull/80321#issuecomment-516921824

Technically because scaleio volume plugin is in the core/v1 API, we cannot remove it until core/v2, which is not coming anytime in distant future.

That brings up the question of how we can consolidate in-tree + CSI driver implementations into one, and migrate users off of in-tree.  There are two main ways I see to do it:

* Deprecate in-tree API and remove support for it later (while keeping the apis). This technically breaks the Kubernetes API deprecation policy which prevents us from removing the API (+ functionality) until we have a new API version.

* Implement CSI migration.  This project consists of writing a translation layer for scaleio that translates between in-tree APIs and the CSI driver API.  Every volume call is going to go through this translation layer so that the CSI driver can handle everything.  It requires your CSI driver to be backwards compatible with all the in-tree functionality.  And also the CSI driver must be installed on the cluster.  This lets us remove the in-tree plugin code but still keep the core/v1 API support for it.  This is our recommended solution, and I would suggest syncing up with @davidz627 for more details.

@kubernetes/sig-storage-misc

**Comment by ddebroy** [comment]
Adding a pointer to the Dell EMC VxFlex OS (formerly named Dell EMC ScaleIO) CSI driver: https://github.com/dell/csi-vxflexos if the CSI migration route is chosen.

**Comment by astripei70** [comment]
@msau42 Appreciate for opening this issue. We will get back to you on this within a few days. Please let me know if this urgent.

**Comment by davidz627** [comment]
see doc for details on migrating a in-tree plugin to driver: https://docs.google.com/document/d/16h9vLLbqQCN83KnlPtn7qL_GB1TYwhWkoA5G4FS3KBI/edit?usp=sharing

**Comment by msau42** [comment]
@davidz627 can we publish this doc somewhere more easily accessible? (like under our sig storage community page?)

**Comment by davidz627** [comment]
Doc is still in flux (some changing sections since we're still going from alpha/beta) and I want to leave it open to comments for now. When it starts to stabilize we will publish as a `.md` somewhere in sig storage.

**Comment by astripei70** [comment]
@msau42 In lieu of upcoming ScaleIO driver deprication,  I am doing research on the use of it. Any info on the usage that you could share would be highly appreciated.

**Comment by msau42** [comment]
@astripei70 can you clarify what usage you are asking about?

**Comment by astripei70** [comment]
@msau42 Michelle, I am looking for any recommendations to estimate the number of ScaleIO driver users. I have looked at the issues and PRs.

**Comment by msau42** [comment]
I don't think there's any good way to get a good estimate without checking with each of the Kubernetes providers and/or directly with scaleio customers.

**Comment by astripei70** [comment]
Hi,
Our research indicates that in-tree ScaleIO volume plugin has no active users at this time. Hence we recommend marking the in-tree ScaleIO volume plugin “Deprecated” as early as practically possible. It is worth noting that the CSI Driver for ScaleIO has been published for over two years. Also, Dell EMC has released an updated version of this driver [here ](https://github.com/dell/csi-vxflexos) recently. Dell EMC will continue updating and supporting the new VxFlexOS CSI driver moving forward as per the support terms outlined [here](https://github.com/dell/csi-vxflexos#support).
Due to the above, Dell EMC does not see the need to develop CSI migration module for the in-tree ScaleIO plugin.

**Comment by dims** [comment]
scaleio was deprecated here: https://github.com/kubernetes/kubernetes/pull/80099
