### ISSUE TITLE
Add ability to "docker commit" from a running container

### ISSUE THREAD

**Issue by Philbewan** [kubernetes/kubernetes#80818]
**What would you like to be added**: We would like to be able to docker commit a running container to a new layer that is based upon the container's docker image.  The new layer could optionally be pushed to the same repo, or a different one designated in the yaml for the Pod.

For example - say I have a Running Pod called: "ide-juypter-01" - and I've installed a lot of libraries, etc. onto its ephemeral filesystem that I do NOT want to lose.

From CLI - a user with proper privileges should be able to perform a commit and push to a docker repository - with a command like:
`kubectl image-layer-commit pod ide-jupyter-01 --tag us.gcr.io/my-custom-image:1.0.0`

Of course - there would be API calls provided to accomplish the same thing.

**Why is this needed**: We use kubernetes for data science IDE environments - and our users frequently install data science libraries that can take several minutes to install/compile.  Because the IDE environments typically are shut down each night, they lose those installed libraries, and thus have to do the same installs again the next day, and each day after that.  I understand that we could have them build their own docker images, however it would be much easier if within kubernetes we could "snapshot" the container image in real-time via a docker commit (with tag of course) - that way the next day the user could just spin up their image with the installed libraries and pick up where they left off.

Thank you for considering my request!
/sig usability

**Comment by mattjmcnaughton** [comment]
Hi @Philbewan !

Interesting idea :)

One option to consider would be whether you could accomplish this via a controller you deploy on your k8s cluster and accomplishes your task via calls to the k8s api. I think a controller, which isn't part of main line k8s, would allow development to proceed much faster. You wouldn't need to wait for new k8s releases/go through api review, etc...

If you are interested in this being part of mainline k8s, the first step would be to see if you can generate community interest. The k8s slack, kubernetes-dev mailing lists, and weekly sig meetings are good places to start those conversations. If there is interest, we'd want to file a [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements).

**Comment by Philbewan** [comment]
> Hi @Philbewan !
> 
> Interesting idea :)
> 
> One option to consider would be whether you could accomplish this via a controller you deploy on your k8s cluster and accomplishes your task via calls to the k8s api. I think a controller, which isn't part of main line k8s, would allow development to proceed much faster. You wouldn't need to wait for new k8s releases/go through api review, etc...
> 
> If you are interested in this being part of mainline k8s, the first step would be to see if you can generate community interest. The k8s slack, kubernetes-dev mailing lists, and weekly sig meetings are good places to start those conversations. If there is interest, we'd want to file a [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements).

Hi @mattjmcnaughton !

Thank you for the feedback.  I've never contributed (even ideas) to open source software before, so this is a little bit out of my comfort zone :)  I like the idea of a controller, I'll research that a little more as you suggest.

Regarding the slack, mailing lists, etc. - I'll also try to do that.

Thanks very much!

**Comment by mattjmcnaughton** [comment]
Awesome that you're getting started contributing @Philbewan ! Please ask if there's any thing else we can do to help (most likely on Slack, unless you're identifying a specific bug or feature request).

**Comment by tarjintor** [comment]
I have the same requirement,and I solved it in 2 diffrent ways 
1.use ansible
2.use daemon set with mount hostpath of /var/run/docker.sock
both ways are try to execute docker commit in slave nodes
If there is a better way,I would like to know.
Since this issue closed for a long time,I wonder if there is any new solution today?
@Philbewan

**Comment by DavidSpek** [comment]
@tarjintor I'm not sure, but this seems to be what Rok from Arrikto is doing. https://www.arrikto.com/features/data-management/

**Comment by DavidSpek** [comment]
Another thing that might be of interest is `docker checkpoint`, which uses [CRIU](https://www.criu.org/Main_Page).

**Comment by rishi1111** [comment]
> I have the same requirement,and I solved it in 2 diffrent ways
> 1.use ansible
> 2.use daemon set with mount hostpath of /var/run/docker.sock
> both ways are try to execute docker commit in slave nodes
> If there is a better way,I would like to know.
> Since this issue closed for a long time,I wonder if there is any new solution today?
> @Philbewan

Do you have any references to how do this with ansible?

**Comment by mohammedi-haroune** [comment]
We're in the exact same situation with our MLOps platform https://iko.ai, any news about this issue ? @philipmoore-8451 how did you handled that ?
