### ISSUE TITLE
kubectl wait unable to not wait for service ready

### ISSUE THREAD

**Issue by JoeyLuffa** [kubernetes/kubernetes#80828]
I am trying to use `kubectl wait --for=condition=ready service/<service-name> --timeout=60s` to wait a service to be ready. However, it doesn't work. And I have to switch to `kubectl wait --for=condition=ready pod -l app=<app-name> --timeout=60s`. 

Any commands I can use to wait for a service to be ready with `kubectl wait` command? Thanks.

@kubernetes/sig-usability-feature-requests

**Comment by JoeyLuffa** [comment]
@kubernetes/sig-usability-feature-requests

**Comment by hainesc** [comment]
When you run `kubectl describe` on a pod, you can see a condition list like this:
```
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
```

While run `kubectl describe` on a service, there is no condition list. That is reason why `kubectl wait` does no work on `service`.

I will take a look whether should we make sure condition list should be available for all kind of resources.

/assign

**Comment by liggitt** [comment]
Services do not have conditions in their status. The ability to wait for an arbitrary status field value is covered by feature request https://github.com/kubernetes/kubernetes/issues/83094

/close

**Comment by jonashackt** [comment]
For others seeking a solution until `v1.23` is available broadly (see https://stackoverflow.com/a/70108500/4964553):
```
until kubectl get service/<service-name> --output=jsonpath='{.status.loadBalancer}' | grep "ingress"; do : ; done
```

**Comment by jonashackt** [comment]
For others seeking a solution until `v1.23` is available broadly (see https://stackoverflow.com/a/70108500/4964553):
```
until kubectl get service/<service-name> --output=jsonpath='{.status.loadBalancer}' | grep "ingress"; do : ; done
```
