### ISSUE TITLE
Kubernetes deletes all ServicePort items with same "port" value when deleting one in a Service's "ports" array

### ISSUE THREAD

**Issue by ricardbejarano** [kubernetes/kubernetes#80823]
### What happened:

I deleted a `ServicePort` item from a `Service`'s `ports` array and all other `ServicePort` items with the same `port` value were deleted too. 

### What you expected to happen:

I only expected one `ServicePort` to be deleted.

#### Manifests

`misbehaving-service.A.yml`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: misbehaving-service
spec:
  selector:
    key: value
  ports:
    - name: 5000tcp
      port: 5000
      protocol: TCP
    - name: 5001tcp
      port: 5001
      protocol: TCP
    - name: 5001udp
      port: 5001
      protocol: UDP
```

`misbehaving-service.B.yml` (last port deleted):

```yaml
apiVersion: v1
kind: Service
metadata:
  name: misbehaving-service
spec:
  selector:
    key: value
  ports:
    - name: 5000tcp
      port: 5000
      protocol: TCP
    - name: 5001tcp
      port: 5001
      protocol: TCP
    # - name: 5001udp
    #   port: 5001
    #   protocol: UDP
```

#### Steps

*Check the `PORT(S)` columns.*

```
$ kubectl apply -f misbehaving-service.A.yml
service/misbehaving-service created

$ kubectl get service/misbehaving-service
NAME                  TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
misbehaving-service   NodePort   10.103.167.232   <none>        5000:31000/TCP,5001:31001/TCP,5001:31002/UDP   5s

$ kubectl apply -f misbehaving-service.B.yml
service/misbehaving-service configured

$ kubectl get service/misbehaving-service
NAME                  TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
misbehaving-service   NodePort   10.103.167.232   <none>        5000:31000/TCP   15s
```

**When I update `misbehaving-service` to remove one item of its `ports` array, Kubernetes removes two.**

### Anything else we need to know?

As far as I can tell, this is when it occurs:

1. You have a service with two items in its `ports` array, which both share the same `port` value but different `protocol` value (or else they would conflict)
2. You update that service to remove one of those items in the `ports` array (removing one of the protocols)
3. Kubernetes removes all items in the `ports` array with the same `port` value as the to-be-deleted one

So if I have a service with `5000/tcp` and `5000/udp`, and I delete `5000/udp`, Kubernetes deletes `5000/tcp` too. *In fact, if you try this exact example, Kubernetes will throw a `The Service "misbehaving-service" is invalid: spec.ports: Required value` error when deleting `5000/udp` because it deletes both ports, emptying the service's `ports` array and conflicting.*

### Environment

I've managed to reproduce this issue in two different clusters:

Cluster one (on-prem with `kubeadm`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -r
4.15.0-55-generic
```

Cluster two (managed @ DigitalOcean):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ricardbejarano** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
This is a known bug & we're waiting on server side apply to fix.

**Comment by ricardbejarano** [comment]
Oh, great!

Do you have a PR or something I can track the issue's lifecycle with?

**Comment by yue9944882** [comment]
please check the feature on the offical doc site https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

**Comment by ricardbejarano** [comment]
Alright, thanks!

I'm closing as this is a well-known issue on it's path to be fixed.
