### ISSUE TITLE
Windows container reports wrong container log usedbytes

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#80838]
While testing windows container disk usage matrices, noticed that the reported log usage of a container is wrong. It actually shows the root file system disk used bytes.

{
 "node": {
  "nodeName": "e2e-test-windows-node-group-h3bt",
  "systemContainers": [
   {
    "name": "pods",
    "startTime": "2019-08-01T00:53:54Z",
    "cpu": {
     "time": "2019-08-01T00:53:54Z",
     "usageCoreNanoSeconds": 5156250000
    },
    "memory": {
     "time": "2019-08-01T00:53:54Z",
     "workingSetBytes": 42528768
    },
    "userDefinedMetrics": null
   }
  ],
  "startTime": "2019-07-18T18:00:53Z",
  "cpu": {
   "time": "2019-08-01T00:53:51Z",
   "usageCoreNanoSeconds": 1249975420000000
  },
  "memory": {
   "time": "2019-08-01T00:53:51Z",
   "availableBytes": 7136661504,
   "usageBytes": 2489614336,
   "workingSetBytes": 915984384,
   "rssBytes": 0,
   "pageFaults": 0,
   "majorPageFaults": 0
  },
  "fs": {
   "time": "2019-08-01T00:53:51Z",
   "availableBytes": 87166541824,
   "capacityBytes": 107372081152,
   "usedBytes": 20205539328
  },
  "runtime": {
   "imageFs": {
    "time": "2019-08-01T00:53:52Z",
    "availableBytes": 87166541824,
    "capacityBytes": 107372081152,
    "usedBytes": 20205539328
   }
  }
 },
 "pods": [
  {
   "podRef": {
    "name": "emptydirpod-no",
    "namespace": "default",
    "uid": "070694c7-12f0-4c54-8936-856b0d5c29cc"
   },
   "startTime": "2019-08-01T00:53:38Z",
   "containers": [
    {
     "name": "test-container",
     "startTime": "2019-08-01T00:53:40Z",
     "cpu": {
      "time": "2019-08-01T00:53:54Z",
      "usageCoreNanoSeconds": 5156250000
     },
     "memory": {
      "time": "2019-08-01T00:53:54Z",
      "workingSetBytes": 42528768
     },
     "rootfs": {
      "time": "2019-08-01T00:53:54Z",
      "availableBytes": 87166545920,
      "capacityBytes": 107372081152,
      "usedBytes": 0
     },
     "logs": {
      "time": "2019-08-01T00:53:54Z",
      "availableBytes": 87166541824,
      "capacityBytes": 107372081152,
      "usedBytes": 20205535232,
      "inodesUsed": 0
     },
     "userDefinedMetrics": null
    }
   ],
   "cpu": {
    "time": "2019-08-01T00:53:40Z",
    "usageNanoCores": 0,
    "usageCoreNanoSeconds": 5156250000
   },
   "memory": {
    "time": "2019-08-01T00:53:54Z",
    "availableBytes": 0,
    "usageBytes": 0,
    "workingSetBytes": 42528768,
    "rssBytes": 0,
    "pageFaults": 0,
    "majorPageFaults": 0
   },
}

**Comment by jingxu97** [comment]
cc @yujuhong

**Comment by PatrickLang** [comment]
@yujuhong @jingxu97 - is this still an issue? I'm seeing 0 reported after Jing's fix in https://github.com/kubernetes/kubernetes/pull/81437

**Comment by jingxu97** [comment]
I plan to work on enable or add some e2e tests for it if possible.
