### ISSUE TITLE
Azure Disk fails when reference storage class with no account type

### ISSUE THREAD

**Issue by rmweir** [kubernetes/kubernetes#80836]
**What happened**:
When creating an azure disk PVC, an error will be received if it references a storage class that is of kind "shared" and has no "storageaccounttype" value. This occurs in newer versions (1.12+). This is because when making a storage account, Kubernetes now passes on the empty value, which is not a valid value for the storage account parameter. Kubernetes used to detect the empty value and pass on a default instead.

**What you expected to happen**:
The storage account should be created with the default type of Standard_LRS.

**How to reproduce it (as minimally and precisely as possible)**:
Create an azure disk storage class with no storage account type.
Create a PVC that references that storage class.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
fails on v1.12+

- Cloud provider or hardware configuration:
Azure

/sig storage

**Comment by andyzhangx** [comment]
hi @rmweir, do you want ot cherry pick to old k8s release?

**Comment by rmweir** [comment]
@andyzhangx that would be great, I will work on this today or next week
