### ISSUE TITLE
Confusing message in kubectl get when no cluster-scoped resources found

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#80855]
**What happened**:
When running `kubectl get <cluster-scoped resource kind>` and no resource is found, kubectl returns `No resources found in mynamespace namespace`, which is confusing, since we're trying to list instances of a *cluster-scoped* resource.

**What you expected to happen**:
When listing cluster-scoped resources, the message should either be
```
No resources found.
``` 
or 
```
No resources found at the cluster scope.
```

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl get volumeattachments
```
(assuming there are no `volumeattachments`; can also try `validatingwebhookconfigurations` or similar)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.2.130+4ce69dd32ef9c3-dirty", GitCommit:"4ce69dd32ef9c34b11f06ef195438f4e2ee7c5ed", GitTreeState:"dirty", BuildDate:"2019-08-01T10:54:52Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by luksa** [comment]
/reopen

Reopening, because #80873 did not fix this issue. It only fixed `kubectl get --all-namespaces`, which also had a misleading message, but that's not what this issue is about. This issue is about cluster-scoped resources, not about listing namespaced resources in all namespaces.

**Comment by kristinnardal2** [comment]
/reopen

This seems to be an error in the get code for kubectl, it looks like it tries to figure out if all the requested resources are namespaced and only then return specify the namespace in the output. This seems to be happening when we have only cluster-wide resources.

https://github.com/kubernetes/kubernetes/blob/b0c1fd19fcb6cc508bb6aa461594eac9e456960a/staging/src/k8s.io/kubectl/pkg/cmd/get/get.go#L586-L593
