### ISSUE TITLE
Remove v1beta1 and v1beta2 api from the codebase, docs, and gh_pages

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#8087]
As part of migrating everything to an official v1 api, we should remove the earlier versions from the code base and documentation on kubernetes.io

As part of this, I'm going to remove all the v1beta1 and v1beta2 specific code and test cases. I'm also going to update the scripts to stop generating swagger specs for them.

@bgrant0607 @nikhiljindal, any other tasks that I most likely missed?

**Comment by bgrant0607** [comment]
Delete LegacyHostIP

**Comment by bgrant0607** [comment]
Stop running v1beta1 tests on shippable/travis

**Comment by lavalamp** [comment]
@nikhiljindal has a change in progress for this-- he needed it for the upgrade script.

**Comment by nikhiljindal** [comment]
@dchen1107 Was going to generate a new container VM image with v1beta3 support, which was required before we can start deleting v1beta1.

**Comment by smarterclayton** [comment]
This change should not remove the legacy scope behavior.  It can remove the tests and any Kube specific stuff, but we need to leave legacy in for a bit longer.

**Comment by bgrant0607** [comment]
@smarterclayton What do you mean by "legacy scope"?

**Comment by smarterclayton** [comment]
The pkg/apiserver and pkg/api/meta concepts for RESTScopeNamespaceLegacy and the support in api_installer.go for the legacy paths.  We'll need those for a few more weeks in OpenShift.

----- Original Message -----

**Comment by bgrant0607** [comment]
Note that examples and docs are covered by #6584. See also #5475.

@nikhiljindal @caesarxuchao @krousey

**Comment by bgrant0607** [comment]
There are still 150 references to v1beta1:
https://github.com/GoogleCloudPlatform/kubernetes/search?p=9&q=v1beta1&utf8=%E2%9C%93

I suggest dividing them up among multiple people. Possible categories:
* UI javascript
* /cluster
* docs
* getting-started guides
* examples
* contrib
* Kubelet and its client
* kubectl
* API validation tests
* misc. tests

**Comment by caesarxuchao** [comment]
I will first work on

   - contrib
   - docs



On Wed, May 13, 2015 at 12:02 AM, Brian Grant <notifications@github.com>
wrote:

> There are still 150 references to v1beta1:
>
> https://github.com/GoogleCloudPlatform/kubernetes/search?p=9&q=v1beta1&utf8=%E2%9C%93
>
> I suggest dividing them up among multiple people. Possible categories:
>
>    - UI javascript
>    - /cluster
>    - docs
>    - getting-started guides
>    - examples
>    - contrib
>    - Kubelet and its client
>    - kubectl
>    - API validation tests
>    - misc. tests
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/8087#issuecomment-101541037>
> .
>



-- 
Regards,
Chao Xu

**Comment by krousey** [comment]
I will take a look at /cluster

**Comment by dchen1107** [comment]
@nikhiljindal We already cut one image: container-vm-v20150505 which includes kubernetes 0.16.2 and docker 1.6.0. Next one can include kubernetes 0.17.X and docker 1.6.2. So that we have two image releases include both APIs. You can drop v1beta1 now. 

cc/ @zmerlynn

**Comment by bgrant0607** [comment]
We also need to eliminate minions from the API: #8240

**Comment by bgrant0607** [comment]
GUI: #8304

**Comment by bgrant0607** [comment]
Eliminate watch from path: #8337

**Comment by bgrant0607** [comment]
Delete ContainerManifest from everywhere.

**Comment by nikhiljindal** [comment]
v0.18 will be our last release that will support both v1beta1 and 3.
We will start ripping off beta1 once 0.18 is cut.

**Comment by krousey** [comment]
@smarterclayton I'm looking at taking v1beta1 out of https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/apiserver_test.go and trying to figure what The Right Thing™ is. I looked through the history and found 870da687d0c2477dc7be1c659a379cfa35a2e850. Would going back to a single version be ok?

**Comment by krousey** [comment]
I'm going to work on keeping the two version approach, but not depending on any official version.

**Comment by bgrant0607** [comment]
I see us needing to support, and therefore test, multiple versions indefinitely.

**Comment by krousey** [comment]
Having to update heapster. See https://github.com/GoogleCloudPlatform/heapster/pull/298

**Comment by bgrant0607** [comment]
@krousey Do you have any WIP PRs for any of the other necessary changes? What could be picked up by other people?

**Comment by krousey** [comment]
Created a WIP PR. I'm currently blocked on getting heapster updated and will be working on that. Someone could probably take #8240 from me.

**Comment by bgrant0607** [comment]
We should also rip out externalID -- see #7775.

**Comment by bgrant0607** [comment]
@smarterclayton Do you still need RESTScopeNamespaceLegacy?

**Comment by bgrant0607** [comment]
There's no way we can finish it, but we need to wean ourselves off "minion": #1111

**Comment by smarterclayton** [comment]
Yes for at least a month or so more.  We have a slightly longer window on our v1beta1 window than you guys.

**Comment by smarterclayton** [comment]
If apiserver is left as is we're ok

**Comment by bgrant0607** [comment]
ContainerManifest is defined here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L1793

PodContainerInfo:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L806

**Comment by bgrant0607** [comment]
Loose ends exposed by the API:
* Minions
* LegacyHostIP
* ContainerManifest
* PodContainerInfo
* externalID

Non-critical cleanups:
* `pkg/api/validation/validation.go`
* `pkg/api/validation/testdata/v1beta1/*`
* `pkg/config/config_test.json`
* `cluster/ubuntu/skydns-*.yaml.template`
* `pkg/api/testapi/testapi_test.go`
* `examples/k8petstore/k8petstore.sh`
* `pkg/registry/generic/rest/streamer_test.go`
* `pkg/kubelet/config/common_test.go`
* `pkg/client/clientcmd/api/types_test.go`
* `pkg/api/unversioned.go`
* `pkg/client/cache/listwatch_test.go`
* `docs/getting-started-guides/mesos.md`
* `pkg/client/testclient/testclient.go`
* `pkg/client/client_test.go`
* `pkg/api/conversion.go`
* `pkg/client/helper.go`
* `contrib/podex/podex.go`
* `pkg/kubectl/cmd/cmd_test.go`
* `hack/test-cmd.sh`
* `pkg/client/helper_test.go`
* `docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml`
* `pkg/client/request.go`

**Comment by bgrant0607** [comment]
I think enough of this has been done for the 1.0 release candidate.

**Comment by bgrant0607** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event_test.go#L76
```
	testRef, err := api.GetPartialReference(testPod, "desiredState.manifest.containers[2]")
	testRef2, err := api.GetPartialReference(testPod2, "desiredState.manifest.containers[3]")
```
The above is v1beta1/2 syntax, not v1beta3/v1. Other lines in that file need to similarly be updated.

**Comment by bgrant0607** [comment]
Not sure if this is related to the sporadic test failures I see on travis or not.

**Comment by caesarxuchao** [comment]
I'll take a look on this.

**Comment by caesarxuchao** [comment]
I don't think this will cause any damage, these strings are not parsed. I will send a PR to fix them anyway.

**Comment by bgrant0607** [comment]
Ugh, we're still exposing minions in the API:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L474

**Comment by bgrant0607** [comment]
Ah, no, we're not:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L730
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L746

**Comment by satnam6502** [comment]
Milestone?

**Comment by bgrant0607** [comment]
This was 1.0. Added 1.0 milestone again, but reduced priority. We should allow outstanding PRs related to this to go in, but should look for higher-priority things to spend effort on.

**Comment by nikhiljindal** [comment]
v1beta1 and 2 have been long gone. Closing the issue.
