### ISSUE TITLE
Directory permissions under /var/lib/kubelet/pods

### ISSUE THREAD

**Issue by jasonkyzer** [kubernetes/kubernetes#80872]
A random 0 byte file is created when we deploy a deployment or daemon-set:

ls -lart /var/lib/kubelet/pods
0666 *container id*/containers/*container name*/*random file name*

Might you be able to provide more information on this file? How may we direct kubernetes to create this file with 0644 or 0640? is there a flag we may pass to kubelet for this?

It is showing up in our security scans as less secure.

@kubernetes/sig-node

**Comment by tsunny** [comment]
@kubernetes/sig-node

**Comment by jasonkyzer** [comment]
It seems as though the 666 is needed for something because it's being set explicitly: https://github.com/kubernetes/kubernetes/search?q=0666&unscoped_q=0666

**Comment by dlaidlaw** [comment]
Can someone provide some feedback on this issue. The world writeable file permissions cause security warnings for us as well. World writeable permissions should not be required.

**Comment by jlruizmlg** [comment]
Any update on this issue? thanks!
