### ISSUE TITLE
Refactor kubelet convertStatusToAPIStatus

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#80875]
The kubelet's `convertStatusToAPIStatus()` in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go iterates `podStatus` 3 times in order to construct the 3 container status lists in `PodStatus`. This could be refactored to make a single pass through `podStatus`.

/kind cleanup
/sig node

**Comment by praveensastry** [comment]
Hi, I would like to contribute to this.

**Comment by verb** [comment]
@praveensastry fantastic! If I could ask you to start out with my branch in #59484 (which should merge soon) it would mean less rebasing for one or both of us.

I'll grab this issue, but I'm not working on it, you are. Let me know if I can help.

/assign @verb

**Comment by verb** [comment]
#59484 has merged so this is fully unblocked. @praveensastry do you still plan on working on this?

**Comment by praveensastry** [comment]
@verb yes please, I was busy for a while with personal stuff.. I'll try and finish this within this week.

**Comment by verb** [comment]
ok, maybe this doesn't meet all of the good first issue criteria.

/remove-good-first-issue

**Comment by Rand01ph** [comment]
I would like contribute to this。

**Comment by verb** [comment]
@Rand01ph great! Your help would be most appreciated. Feel free to ask questions in issue.

@praveensastry I haven't heard from you, have you made any progress? Do you want to work with @Rand01ph or hand it off?

**Comment by Rand01ph** [comment]
@verb I think I will refactoring the func `convertToAPIContainerStatuses()` and can handle all type of container such as `InitContainer` or `EphemeralContainer`, whitout some func args。

**Comment by verb** [comment]
@Rand01ph I think that would address the problem, but I'm not sure exactly what you have in mind. Here's what I had in mind:

When `convertStatusToAPIStatus()` was written, there was a single list of containers, so it iterated that list to covert statuses. Now there are 3 lists of containers, but still only a single list of `kubecontainer.ContainerStatus`, so it probably makes more sense to iterate that list instead, sorting into the 3 types of container statuses.

It's this piece of code with the passing in of additional information as function arguments that feels like the abstraction is no longer quite right:

```
	apiPodStatus.ContainerStatuses = kl.convertToAPIContainerStatuses(
		pod, podStatus,
		oldPodStatus.ContainerStatuses,
		pod.Spec.Containers,
		len(pod.Spec.InitContainers) > 0,
		false,
	)
	apiPodStatus.InitContainerStatuses = kl.convertToAPIContainerStatuses(
		pod, podStatus,
		oldPodStatus.InitContainerStatuses,
		pod.Spec.InitContainers,
		len(pod.Spec.InitContainers) > 0,
		true,
	)
	if utilfeature.DefaultFeatureGate.Enabled(features.EphemeralContainers) {
...
		apiPodStatus.EphemeralContainerStatuses = kl.convertToAPIContainerStatuses(
			pod, podStatus,
			oldPodStatus.EphemeralContainerStatuses,
			ecSpecs,
			len(pod.Spec.InitContainers) > 0,
			false,
		)
	}
```

Iterating `kubecontainer.ContainerStatus` may not be quite right since it's possibly incompleted, but I haven't looked into it enough. An alternative may be to use `ContainerVisitor`, but since it requires different action per container type you'd need #82192 to be merged first.

No matter what, the first step here is to ensure good test coverage. Good test coverage should give us confidence that we haven't changed any behavior.

@yylt is interested in working on this, too. You two should coordinate so you don't duplicate effort. Thank you both for your help!

**Comment by Rand01ph** [comment]
@verb Thanks, I'll write some test for `convertStatusToAPIStatus()`  before refactoring.

**Comment by yylt** [comment]
Oh, At the beginning , I think the question is how to shorten time in `convertStatusToAPIStatus()` , I have wrong understanding about this

Hi, @Rand01ph , what is your plan ?

If make a single pass in  `convertStatusToAPIStatus()` , I will use below

~~~

convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecontainer.PodStatus, oldpodStatus *v1.PodStatus,podSpec *v1.Pod.Spec,  useEphemeralPodSpec bool) *v1.PodStatus{
    ...
    iterFn = func(pod *v1.Pod, podStatus *v1.PodStatus, isInitContainer bool) []v1.containerStatus {...}
    ...
}

~~~

**Comment by Rand01ph** [comment]
Hi, @yylt . I think the `oldPodStatus` only used by `convertStatusToAPIStatus()`. So, maybe refactoring `convertToAPIContainerStatuses()` just like below:

`convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecontainer.PodStaus, apiPodStatus *v1.PodStatus)
`

**Comment by Rand01ph** [comment]
@verb Hi, I have open a PR for this, PTAL.
