### ISSUE TITLE
Test failure: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#80878]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach

**Since when has it been failing**:
7/31

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1156944661269450752

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:99
Timeout error fetching storage c-m metrics : timed out waiting for the condition
Unexpected error:
    <*errors.errorString | 0xc0002afcd0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:561
```

**Anything else we need to know**:

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures 
/assign @gnufied @yuxiangqian

**Comment by yuxiangqian** [comment]
Taking a look.
Running using my own build seems to be good. And I saw a successful run on 8/1 on as well.
i.e.,
kubetest --test --test_args="--ginkgo.skip=Alpha|Experimental|Disruptive|Flaky|\[Driver --ginkgo.focus=\[sig-storage\]\s\[Serial\]\sVolume\smetrics" -v=8 --provider=gce

returns after running serial test cases successfully.

note that the latest failure also contains a kubelet performance failure:
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet_perf.go:265
Aug  2 11:16:24.881: Memory usage exceeding limits:
 node bootstrap-e2e-minion-group-p5hs:
 container "runtime": expected RSS memory (MB) < 131072000; got 138428416

**Comment by yuxiangqian** [comment]
so far I am not able to reproduce.
[This](https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial) shows its now back to normal.
