### ISSUE TITLE
Does k8s support Omni-Path Architecture (OPA) ?

### ISSUE THREAD

**Issue by 928234269** [kubernetes/kubernetes#80887]
Omni-Path Architecture (OPA) is Intel®'s experience and lessons in the True Scale architecture and standard InfiniBand. It is a high-performance network architecture developed for HPC that enables each link to reach 100 Gbps. A new interconnect technology designed to optimize high performance computing is also an end-to-end interconnect solution.

**Comment by dims** [comment]
Please ask intel folks, someone may be working on a CNI implementation

/close
