### ISSUE TITLE
How Kubernetes Horizontal Pod Autoscaler calculates CPU percentage?

### ISSUE THREAD

**Issue by avarf** [kubernetes/kubernetes#80890]
**What happened**:
HPA calculates cpu usage wrong

**Anything else we need to know?**:
I set up my cluster and I want my deployments to scale up when the first pod uses 75% of one cpu (core). I did this with hpa and everything is working but I noticed that the hpa percentage is strange.

Based on what I know `1 cpu = 1000 milliunits` and what I see in `kubectl top pods` is pod-A using 9m but what I see in `kubectl get hpa` is `pod-A 9%/75%` which doesn't make sense, 9% of 1000 is 90 and not 9. I want to know how hpa is calculating the percentage and how shall I configure it so when I reach 75% of one cpu it scales up?

**Environment**:
I am running k8s on Microk8s
- Kubernetes version (use `kubectl version`):
Client Version: v1.14.1
Server Version: v1.15.0

- OS (e.g: `cat /etc/os-release`):
Ubuntu

**Comment by SimonCqk** [comment]
may you post your manifest yaml file ?

**Comment by avarf** [comment]
Actually I found my answer:
The HPA is calculating the percentage based on the resource request for a deployment: https://stackoverflow.com/a/57323614/5553963
