### ISSUE TITLE
CSI resize doesn't handle multi-attached volumes quite right

### ISSUE THREAD

**Issue by bswartz** [kubernetes/kubernetes#80918]
if a CSI volume is attached to more than 1 node, and it is expanded, and if the CSI plugin returns true from ControllerResizeVolume, then the PVC will get marked for node resize, but there's no mechanism to ensure that every node currently using the volume will call the CSI node plugin.

**What happened**: One node called the NodeExpandVolume RPC, the rest did not.

**What you expected to happen**: All nodes should call the NodeExpandVolume RPC.

**How to reproduce it (as minimally and precisely as possible)**: Use a CSI plugin that supports mutli-attach, create a PVC using that CSI plugin, create 2 or more pods using the same PVC on different nodes, then resize the PVC.

**Anything else we need to know?**: There are 2 necessary activities getting combined into a single operation: 1. node-side work required to complete the resize operation, such as resizing of a filesystem and 2. node-side work required to make pods aware of the updated volume size. (1) needs to be done only a single time but needs to be done before the resize can be considered complete. It needs to be done even if the volume is not in use at the time of the resize. (2) needs to be done for every node currently accessing the volume so they all find out about the new size, but if no nodes are accessing the volume, then it could be skipped without harm.

Consider the case of an iSCSI-based plugin implementing raw block volumes. iSCSI supports r/w multi attach as long as it's raw blocks and not filesystem mode. To perform a resize of such a volume, the underlying LUN needs to be resized (on the storage controller) and then the iSCSI initiators all have to rescan their buses to see the new size. In CSI, the iSCSI rescan operation needs to happen in NodeExpandVolume, because this is the only place where such a thing is possible. This is a case of using NodeExpandVolume for purpose (2) above, though, and kubelet only supports purpose (1) currently.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.1
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): Arch Linux
- Kernel (e.g. `uname -a`): 5.2.5-arch1-1-ARCH
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): bridge
- Others: containerd

**Comment by bswartz** [comment]
@kubernetes/sig-storage-bugs 
@gnufied

**Comment by gnufied** [comment]
We spoke briefly about this offline and problem is - if multiple pods are using (i.e not necessarily mounting) same volume as RW on multiple nodes then resizing is essentially racy. A pod that sees resize request first will call `NodeExpandVolume` and update `pvc` to reflect new size. As a result `NodeExpandVolume` *may* not be called on other nodes that use same PVC.

A solution that will probably work is to record actual and desired sizes in kubelet. This way even if PVC is updated by other nodes, the actual size on current node won't be updated until resize actually happens. We have to consider other implications though such as - we should not be resizing a volume which was already resized (although both RPC calls are supposed to be idempotent).

**Comment by bswartz** [comment]
Well the ideal solution would be to have yet another RPC on the CSI node plugin. We could ensure that `NodeExpandVolume` gets called _exactly once_ if required, but there could be another optional RPC that would get called _on every attached node_ if required. The second RPC would address this multi-attached iSCSI raw-block case I'm thinking of.

However, given that modifying CSI is hard I think we can get by with a single RPC, because there is never a case (that I can think of) where you need to do both activities. In every case where you need expand volume to be called exactly once, the volume wouldn't support multi attach anyways, so calling it on all attached nodes would mean zero or one calls. In the cases where you need it to be called on every node, there wouldn't be a race because every node would do exactly the same thing. So if we can just make kubelet ensure `NodeExpandVolume` happens on all attached nodes, it's possible to make my plugin behave correctly always.

**Comment by b0b0haha** [comment]
Is there any progress on this  issue?

**Comment by gnufied** [comment]
This should be fixed now via - https://github.com/kubernetes/kubernetes/pull/108693
