### ISSUE TITLE
ReclaimPolciy fails to delete Persistent Volumes after mounted to a pod [vsphere]

### ISSUE THREAD

**Issue by taylorsilva** [kubernetes/kubernetes#80929]
Originally posted at kubernetes/cloud-provider-vsphere/issues/219

**What happened**: When I deleted a PVC, the corresponding PV was not automatically deleted. The reclaim policy was set to `DELETE`. Describing the PV shows an error:

```
$ kubectl describe pv pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c
Name:            pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c
Labels:          <none>
Annotations:     kubernetes.io/createdby: vsphere-volume-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller: yes
                 pv.kubernetes.io/provisioned-by: kubernetes.io/vsphere-volume
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    concourse-storage-class
Status:          Failed
Claim:           default/nginx-pvc-claim
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         Error caused by file /vmfs/volumes/57f6b68b-54df1c80-56db-00253028000d/kubevols/kubernetes-dynamic-pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c.vmdk
Source:
    Type:               vSphereVolume (a Persistent Disk resource in vSphere)
    VolumePath:         [vnx5600-wild-2] kubevols/kubernetes-dynamic-pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c.vmdk
    FSType:             ext4
    StoragePolicyName:
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  VolumeFailedDelete  11s   persistentvolume-controller  Error caused by file /vmfs/volumes/57f6b68b-54df1c80-56db-00253028000d/kubevols/kubernetes-dynamic-pvc-c7bd01cd-afe0-11e9-89ec-005056b9048c.vmdk

```

**What you expected to happen**: The PV is automatically deleted when the PVC is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Environment might matter here. I've reproduced it with k8s on vsphere. I can't reproduce this with GKE.
See this gist for exact steps to reproduce: https://gist.github.com/taylorsilva/6dbb045650635bc7709a5e4ce1f3a77f

The error with deleting the PV only happens **after** the PV has been mounted in a container. If you create a PVC and then delete it before it's mounted to a container, the PV is created and deleted without error.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:27:10Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vsphere (not sure about version of this layer)
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux 8a6d3591-522f-467a-87a2-e5f748ccad91 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` 
- Install tools: Bosh deployed PKS using PAS (v2.6)

Let me know if any more information would help. Thank you!

**Comment by taylorsilva** [comment]
@kubernetes/sig-storage-bugs

**Comment by misterikkit** [comment]
Do you have logs from `vsphere-cloud-provider`?

**Comment by taylorsilva** [comment]
I've been busy but I'll get some logs soon (hopefully). I have this on my TODO 😅

**Comment by taylorsilva** [comment]
Figured it out, was a setup issue. Thanks for the responses.
