### ISSUE TITLE
test: data race of `ready` in `TestSyncPodsDeletesWhenSourcesAreReady`

### ISSUE THREAD

**Issue by yuzeming** [kubernetes/kubernetes#80940]
What type of PR is this?
/kind bug

What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/blob/9827a6edc88adf3b2a87b376150d852dbacc294a/pkg/kubelet/kubelet_test.go#L400-L427

There is a data race between read L407 `return ready` and write L423 `ready = true `. 
There is no guarantee that the write to ready will ever be observed by anonymous function , since there are no synchronization events between the two threads.

Does I miss some synchronizations between them?
 
Should we replace it with `atomic.Load` and `atomic.Store`?

PS: this result comes from work-in-progress static race analysis so I can't 100% sure it's right.
Does this PR introduce a user-facing change?:
NONE

**Comment by tedyu** [comment]
Does your static analysis reveal bug in non-test code ?

For the issue you reported, does TestSyncPodsDeletesWhenSourcesAreReady fail ?
I haven't seen it in flaky tests.

**Comment by yuzeming** [comment]
@tedyu Thanks for your response.
My analysis covers all code but doesn't find anything yet.

In this test, it works well for now and looks like a benign data race.

The root cause is cache inconsistency since writing to memory is expensive and CPUs tend to buffer it in cache. However other CPU's can't observe writing in time until cache flush. It finally leads to a speculative bug. 

Also, according to [Go's Memory Model](https://golang.org/ref/mem), it's a Incorrect synchronization which means it could work for now. However there is no guarantee that it will work correctly when a new optimizer was added or Go was ported to other platforms,
