### ISSUE TITLE
Pods on node with temporary unknown status never marked ready again

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#80968]
# Summary

When a node (kubelet) is unable to heartbeat with the apiserver for a long time, the node-lifecycle controller sets the status of the node to "unknown" and immediately adds the following taint to the node 
```
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2019-08-03T00:34:24Z"
```
And immediately marks all pods on the node as `NotReady`. This is done [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L796)

5 seconds later (this is the frequencey of the node lifecycle contrller's node health checking loop) the following taint is added

```
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2019-08-03T00:34:30Z"
```

Which evicts most pods from the node.
However, in some cases the node heartbeats *after* the first taint is added but *before* the second taint is added. In this case, pods don't get evicted from the node however *they stay not ready despite the fact that all containers on the pod are ready and the node the pods are running on is now healthy (Ready)*. This state never recovers without manual intervention, either by marking the pod ready manually, or deleting it if there is a controller that will bring it back.  

Expected is that if a pod is scheduled on a healthy node and all containers of the pod are ready, the pod should be marked as ready regardless of edge cases of lifecycle transition of the node.

# Repro

One way to repro this is to cause a node to fail to heartbeat for long enough that the node goes into unknown status, but not long enough that the no execute taint is added.
I did this by breaking comms with the apiserver with the kubelet using some iptables hacks:

./break-network.sh
```
#!/bin/bash

# ips the kubelet uses to talk to the apiserver
ips=""

for ip in $ips; do
    echo $ip
    iptables -I OUTPUT -d $ip -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j DROP
done
```

and a hacky script to restore
./restore-network.sh
```
#!/bin/bash

# ips to be restored after running above script
ips=""

for ip in $ips; do
    echo $ip
    iptables -D OUTPUT 1
done
```

Note that stopping the kubelet, waiting, then starting the kubelet isn't a good way to repro this because when the kubelet starts up it repairs the broken (not ready) pods. 

The timing of this is pretty hard to get right, because unless you tolerate the no execute taint, 5 seconds after the node is unreachable, the no execute taint gets added and the pod gets evicted.
So I wrote [this script](https://gist.github.palantir.build/rmcnamara/227d622ebdd8548e5f6eec561fddb309) that heartbeats on behalf of the node the moment it becomes Unreachable to simulate the kubelet doing it. After this fake heartbeart, fix the kubelet network and stop the script and you'll see the pod never becomes ready again.

You can also repro this by just tolerating the no execute taint, then causing the heartbeat to the apiserver to fail, then fixing it and see that the pod never becomes ready again. I wanted to include the other repro however because it's more realistic.

# Impact

This occurred in production for us and led to a customer outage. In our case, we had a node that was intermittently unable to heartbeat, and the failure wound up cascading in this way that led to a full cluster dns outage for all 3 coredns pods we were running.

# Versions
k8s: 1.14.3

**Comment by ryanmcnamara** [comment]
I wasn't able to repro as above 100% of the time. Sometimes, if the kubelet has an unrelated update for the pod it will update its status as Ready. The repro worked most of the time and this is still a bug as far as I can tell because there isn't a guarantee (nor is it even likely) that the pod will be ready in the steady state once the kubelet returns to being healthy

**Comment by tedyu** [comment]
If the heartbeat happens between the second taint is applied,
```
			if observedReadyCondition.Status == v1.ConditionTrue {
				if nc.useTaintBasedEvictions {
					removed, err := nc.markNodeAsReachable(node)
```
shouldn't the above code (starting on line 777) kick in ?

**Comment by alexodle** [comment]
@tedyu I tried reproing this using @ryanmcnamara 's repro steps (using the eviction toleration version), and I can say for sure we enter the if statement you reference when I restore the connection, as I see "Node %s is healthy again, removing all taints" in the logs. Even so, I can confirm the pods on that node are never marked as Ready.

**Comment by tedyu** [comment]
```
			if currentReadyCondition.Status != v1.ConditionTrue && observedReadyCondition.Status == v1.ConditionTrue {
				nodeutil.RecordNodeStatusChange(nc.recorder, node, "NodeNotReady")
				if err = nodeutil.MarkAllPodsNotReady(nc.kubeClient, node); err != nil {
```

**Comment by alexodle** [comment]
Yeah, it enters that condition after you cut off heartbeats (the ./break-network.sh step above). The problem I think is that if the heartbeats start up again and the pod isn't deleted, then nothing will go and reevaluate whether or not the pod should be marked as ready again.

**Comment by towolf** [comment]
We are pretty confident that we have been hit by this as well. It's bad.

Our API loadbalancer had a too short backend health check timeout and many nodes couldn't reach the API intermittently.

So we had lots of spurious episodes of this, where all Pods from a node where non-ready and removed from service endpoints.

**Comment by alexodle** [comment]
@tedyu my guess is that the kubelet should reevaluate pod readiness when the node becomes ready again. Does that sound right?

Reason being, the kube-controller-manager has the logic you pointed out to explicitly `MarkAllPodsNotReady` when the node becomes unresponsive, but it doesn't appear that anything actually goes and decides whether or not the pods should become ready again if the node comes back.

**Comment by derekwaynecarr** [comment]
@sjenning let’s talk later today if we see an obvious place to fix this unless the reporter has a proposed fix already.

**Comment by tedyu** [comment]
I am thinking about the following change:
```
diff --git a/pkg/controller/nodelifecycle/node_lifecycle_controller.go b/pkg/controller/nodelifecycle/node_lifecycle_controller.go
index b0ebcc6df9..1f3b4f2e31 100644
--- a/pkg/controller/nodelifecycle/node_lifecycle_controller.go
+++ b/pkg/controller/nodelifecycle/node_lifecycle_controller.go
@@ -797,6 +797,10 @@ func (nc *Controller) monitorNodeHealth() error {
                                        utilruntime.HandleError(fmt.Errorf("Unable to mark all pods NotReady on node %v: %v", node.Name, err))
                                }
                        }
+                       if currentReadyCondition.Status == v1.ConditionTrue && observedReadyCondition.Status != v1.ConditionTrue {
+                               nodeutil.RecordNodeStatusChange(nc.recorder, node, "NodeReady")
+                               nodeutil.MarkAllPodsReady(nc.kubeClient, node)
+                       }
                }
        }
        nc.handleDisruption(zoneToNodeConditions, nodes)
```
MarkAllPodsReady is to be implemented.

**Comment by sjenning** [comment]
@tedyu not sure that we can do that.

The pods on the node might actually not be ready (readiness probe/gate failure or container failing to start).  We can't just blindly make all pods ready on the node like we can blindly make them not ready.  Marking them not ready is a conservative action to remove the pods from service endpoints until contact with the kubelet can be established again.  Marking them ready, if they are not, will cause service disruption.   Unless I'm totally missing something here.

**Comment by tedyu** [comment]
@sjenning 
I agree with you.
MarkAllPodsReady is just a placeholder where per pod action needs to be taken based on liveness check.

**Comment by ryanmcnamara** [comment]
What about @alexodle's suggestion here: https://github.com/kubernetes/kubernetes/issues/80968#issuecomment-521422422?

Should the kubelet reconcile all the pods again when it notices it goes from a unknown -> ready state? My perspective is that the kubelet should be responsible for continually making sure that pods that should be ready are marked as ready.

**Comment by tedyu** [comment]
It seems node_lifecycle_controller.go may not be the best place where the new logic should be added as it is concerned with node lifecycle - not so much about (individual) Pod status.

**Comment by ryanmcnamara** [comment]
Friendly ping @sjenning @derekwaynecarr 
Proposed fix would be for the kubelet to notice this and fix it

**Comment by alexodle** [comment]
I've been playing around with this a bit in the last week or so, and I have a better sense of what's happening here, but I'm not sure yet what the right fix is. Recording my findings/thoughts here for the group.

**Setup**

1. Remove the if statement here, forcing a reconcile for a pods even with readiness gates: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L705 (Note, I'm not 100% sure this part is necessary, but I've been using it to make testing easier)

**Problem**

Even though we force the pods to reconcile after connectivity is returned to the node, and the pod readiness is calculated to be True, as it should, the cached version of the pod on the kubelet is also showing itself as Ready:true, and this line prevents it from actually pushing a new status because isPodStatusByKubeletEqual() returns true: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L705

**Thoughts**

In the case where heartbeats/status updates fail for a given amount of time, it seems like we should either clear the cache OR force an update. Both of those options feel right to me, but I worry that it would have unintended concurrency consequences (based on this comment: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L405).

Also, wondering if there is a way for the kubelet to tell, once connectivity is restored, that the api server explicitly marked its pods as not ready. If so, it seems the most targeted fix would be to listen for that change, and immediately force a reconcile/status update.

**Comment by sukhong** [comment]
We are encountering this issue as well...

We suddenly see all pods in one node being marked as not ready in pod.status.conditions:

status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-21T00:00:57Z"
    status: "True"
    type: Initialized
  - **lastProbeTime: null
    lastTransitionTime: "2019-10-02T11:10:44Z"
    status: "False"
    type: Ready**
  - lastProbeTime: null
    lastTransitionTime: "2019-09-21T00:01:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-21T00:00:52Z"
    status: "True"
    type: PodScheduled

I found that at this exact lastTransitionTime ("2019-10-02T11:10:44Z"), node was unreachable for a brief period of time (saw **node.kubernetes.io/unreachable** taint being applied to this node).

Is this issue fixed yet? This seems to be a very critical bug...

We are running Kubernetes 1.15.3

**Comment by tedyu** [comment]
Created #83455

We can discuss how the default inactivity period should be determined.

**Comment by sukhong** [comment]
This issue seems to share the same root cause: https://github.com/kubernetes/kubernetes/issues/72226

**Comment by ekeih** [comment]
It looks like we have the same problem with 0.15.3.

Maybe the following two snippets help other people to find their affected pods faster.

In case you want to alert based on this until there is a solution:
```
- alert: PodUnreadyWithAllContainersReady
expr: >
  (count by (namespace, pod) (kube_pod_status_ready{condition="true"} == 0))
  and
  (
    (count by (namespace, pod) (kube_pod_container_status_ready==1))
    unless
    (count by (namespace, pod) (kube_pod_container_status_ready==0))
  )
for: 5m
annotations:
  message: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} is unready even though all its containers are ready.'
labels:
  severity: critical
```

Or if you do not have access to Prometheus, you can use `jq`:
```
kubectl get po -A -o json | jq -r '.items[] | {"name": .metadata.name, "node": .spec.nodeName, "ContainersReady": .status.conditions[] | select(.type|contains("ContainersReady")) | .status, "Ready": .status.conditions[] | select(.type|contains("Ready")) | .status } | select(.Ready=="False" and .ContainersReady=="True")'
```

**Comment by sukhong** [comment]
We were affected by this issue again today:
![image](https://user-images.githubusercontent.com/3857851/67812163-acd32f00-fa5b-11e9-94f8-b17f21b014e3.png)

A node became temporarily unreachable for 1 minute, and all the pods within this node were marked Unready and never recovered.

Can we please get some attention to this issue? This is a pretty serious bug that can impact a lot of production clusters.

I am not sure why this node became unreachable for 1 minute (I remoted into the node and looked at journalctl logs, but could not find anything interesting during this time period).

Probably a very transient network issue? (We are hosting our Kubernetes cluster on Azure).

But still, Kubernetes should handle this transient node outage gracefully.

**Comment by sukhong** [comment]
This occurred again in Kubernetes 1.16.2

**Comment by multi-io** [comment]
I just hacked this https://github.com/multi-io/kube-pod-update-status to fix pods broken by this in a cluster.

**Comment by bashofmann** [comment]
The patch in PR https://github.com/kubernetes/kubernetes/pull/83455 fixes this issue for us.

**Comment by SerialVelocity** [comment]
/remove-lifecycle stale

The PR hasn't merged yet.

**Comment by andy-wolf168** [comment]
I understand is that once the heartbeat of the kubelet is restored, the kubelet will receive the SyncLoop (RECONCILE, "api") message and carry the pod Raedy: False status from the apiserver. The pod on this node will be processed by statusmanager # syncBatch every 10s, compared The difference with the cache state, and then upload the difference state to the apiserver. So, I understand that once the heartbeat of kubelet is restored, even if the pod is not marked as the eviction state, there is still a chance to synchronize the state.

**Comment by xavierW** [comment]
is there any pr merge to  kubernete now?

**Comment by tedyu** [comment]
@xavierW
See https://github.com/kubernetes/kubernetes/pull/89155#issuecomment-605662801

**Comment by SerialVelocity** [comment]
/remove-lifecycle stale

Still waiting on the PR to merge

**Comment by cynron** [comment]
@tedyu  @sjenning `Ready` condition can be updated by kubelet & controller-manager and it may lead to race. IMHO, maybe we can split `ready` condition into something like `ReadinessProbeReady` and `NodeHealthReady`. controller-manager will update `NodeHealthReady` to true if node changed to  healthy, and kubelet will update `ReadinessProbeReady` to true if readiness  probe succeeded. pod is treated as ready iff  both `readinessProbeReady` and `nodeHealthReady` were true. 
It is just an immature idea, I think maybe you can consider it.

**Comment by SerialVelocity** [comment]
/remove-lifecycle stale

The PR hasn't merged yet.

**Comment by qmloong** [comment]
> I wasn't able to repro as above 100% of the time. Sometimes, if the kubelet has an unrelated update for the pod it will update its status as Ready. The repro worked most of the time and this is still a bug as far as I can tell because there isn't a guarantee (nor is it even likely) that the pod will be ready in the steady state once the kubelet returns to being healthy

I have not been able to reproduce it by the script. is there anyone same with me?

**Comment by SergeyKanzhelev** [comment]
/triage accepted

(maybe even fixed, @endocrimes to check)

**Comment by SerialVelocity** [comment]
/remove-lifecycle rotten

Still waiting on #89155 to merge.

**Comment by SerialVelocity** [comment]
/remove-lifecycle rotten

Still waiting on https://github.com/kubernetes/kubernetes/pull/89155 to merge.
