### ISSUE TITLE
Improve Node-specific Volume Limit Calculation

### ISSUE THREAD

**Issue by ripta** [kubernetes/kubernetes#80967]
**What would you like to be added**: Better algorithm for node-specific volume limits, or the ability to set the maximum volume limit (or both?). Ideally, the volume limit would be able to be set per node (or per nodegroup if using higher-level tooling), such that we can leverage heterogeneous instance types for the nodes in the cluster.

**Why is this needed**:

In some cases—one described below—both the default volume limits and the dynamic volume limits as outlined in the [Node-specific Volume Limits](https://kubernetes.io/docs/concepts/storage/storage-limits/) docs are still too high. 

Specifically, in regards to the limit relating to Amazon EBS volumes, dynamic volume limits says:

> For Amazon EBS disks on M5,C5,R5,T3 and Z1D instance types, Kubernetes allows only 25 volumes to be attached to a Node. For other instance types on Amazon Elastic Compute Cloud (EC2), Kubernetes allows 39 volumes to be attached to a Node.

which is not the full picture. The AWS [EC2 User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html) describes, in-paragraph emphasis added:

> **Instance Type Limits**
>
> A1, C5, C5d, C5n, I3en, M5, M5a, M5ad, M5d, p3dn.24xlarge, R5, R5a, R5ad, R5d, T3, T3a, and z1d instances support a **maximum of 28 attachments,** including network interfaces, EBS volumes, and NVMe instance store volumes. Every instance has at least one network interface attachment. NVMe instance store volumes are automatically attached. For example, if you have no additional network interface attachments on an EBS-only instance, you can attach up to 27 EBS volumes to it. If you have one additional network interface on an instance with 2 NVMe instance store volumes, you can attach 24 EBS volumes to it. 

Take for example [m5d.24xlarge](https://aws.amazon.com/ec2/instance-types/m5/), which has 1x network interface and 4x NVMe instance store volumes. The maximum volume limit is 23 (= 28 - 1 - 4), which is already lower than the 25 from the dynamic volume limit.

Furthermore, if you use a CNI plugin that leverages first-class VPC networking like [amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s), you'll end up with additional network interfaces. Still taking the example of m5d.24xlarge and limiting to 110 pods per node, the instance [supports 50 IPs/ENI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html), so 110/50 rounded up makes 3. This pushes the volume limit further down to 20 (= 28 - 1 - 4 - 3).

Because kube-scheduler's limit is higher, it means we end up with pods needing PVs getting scheduled onto nodes that have exhausted their attachment limit, causing PV attachments to fail for some period of time before getting [automatically tainted with `NodeWithImpairedVolumes`](https://github.com/kubernetes/kubernetes/blob/b120bc7e33f38d655b7e3998b1efb9d321d2b66c/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2048-L2066) with no automatic recovery path.

At the moment, this means we've had to resort to using the `KUBE_MAX_PD_VOLS` environment variable, which while documented in that same page, does not use the same config mechanism as the rest of kube-scheduler. This means, I've needed to open a PR under the tooling project (kops for us, cf. kubernetes/kops#7346), which is far from ideal. We chose a low limit to account for different node sizes and also set the same environment variable on the cluster-autoscaler.

**Comment by ripta** [comment]
Looking at the group list this feels cross-SIG, so I'll let you all triage:

/sig autoscaling
/sig scheduling
/sig cloudprovider

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by gnufied** [comment]
Can this function https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/awsebs/aws_ebs.go#L107 here be used to detect dynamic nature of the node and return appropriate limits? 

In the long run this has to be moved to CSI and it should be possible to configure a driver to lower limits when driver is started on the node.

**Comment by justinsb** [comment]
Probably - I think the challenge is that for users running the AWS VPC CNI, ENIs are also dynamic and thus:

* we'd need a mechanism for the AWS VPC CNI to also indicate its usage
* we'd need not to assume the volume limit is constant, which I believe we currently do.

I've also realized it is not just volumes ... volume attachment reduces our ability to attach ENIs, and thus we might not be able to launch more pods on a node with a lot of volumes attached.

**Comment by msau42** [comment]
I'm unsure if there's a great general solution we can do here.  Would it be worth considering adding an aws scheduler plugin to handle this? With volume attach limits, we made a fundamental design assumption that the attach limits are only for volumes and no other devices.

**Comment by ripta** [comment]
Can it be a plugin from the node side instead of the scheduler? Reading this snippet:

https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/kubelet/kubelet_node_status.go#L534-L545

the kubelet seems to export the capacity of the node to the API server, resulting in, for example:

```
status:
  capacity:
    attachable-volumes-aws-ebs: "25"
    cpu: "96"
    ephemeral-storage: 3458874672Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 387738952Ki
    pods: "110"
```

Being able to set each node seems more flexible, though it still doesn't solve the case of multiple components (e.g., volume manager and CNI plugin) needing to coöperate to converge to a schedule.

I guess I don't yet have a holistic understanding of how the node status capacity is used by the scheduler (or if it does at all, since `KUBE_MAX_PD_VOLS` needs to be set in kube-scheduler).

**Comment by leakingtapan** [comment]
> In the long run this has to be moved to CSI and it should be possible to configure a driver to lower limits when driver is started on the node.

Similar logic is already added in EBS CSI driver [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/node.go#L508) by using instance type to look up the volume attach limit.

Agree with @justinsb that, to make it working correctly, the challenge comes from storage driver need to be aware of the CNI attachment and vice versa.

**Comment by gnufied** [comment]
@leakingtapan the CSI driver should support overriding the limits via CLI parameter, if it does not do that already. This was always on my mind but it is hard to track this across different drivers. 

@ripta currently since node's status is periodically synced by kubelet, it will cause any external updates to `node.Status.Capacity` to be wiped when kubelet resyncs the status.  But we are getting pretty close to migrating stuff to CSI and hence limit specified in node is being deprecated in favour of limit coming from `CSINode` object -https://github.com/kubernetes/enhancements/pull/942 .

**Comment by ripta** [comment]
> it will cause any external updates to node.Status.Capacity to be wiped when kubelet resyncs the status

A-ha! Ok, I incorrectly assumed the nodestatus package updates only capacity keys it knows about.

> But we are getting pretty close to migrating stuff to CSI and hence limit specified in node is being deprecated in favour of limit coming from `CSINode` object

Thanks for the link. I'll need to learn more about CSINode.

**Comment by justinsb** [comment]
Once we have CSINode, I'm guessing the AWS VPC CNI driver will need to dynamically update CSINode allocatable for the AWS EBS driver, and the scheduler will watch CSINode objects.  I'm assuming the scheduler keeps a watch on CSINode objects anyway, so this should work, modulo annoying race conditions (?)

Have we thought more about how the scheduler can know not to schedule too many pods?  Should the AWS VPC CNI driver dynamically update the pod limits on the node also?  Can we tell the kubelet know not to update the pod limits in this case?

Or ... we can just give nodes a fixed "shape" - divide those 28 attachments in a vaguely sensible way, e.g. 20 EBS volumes, 4 ENIs, 4 local.  This might vary by instance type, but it doesn't feel crazy.

**Comment by leakingtapan** [comment]
> Once we have CSINode, I'm guessing the AWS VPC CNI driver will need to dynamically update CSINode allocatable for the AWS EBS driver 

Since kubelet is already setting CSINode's attach limit by calling CSI driver, suspect there will be conflict if CNI driver is also setting the allocatable.

**Comment by gnufied** [comment]
@justinsb yeah so updating `CSINode` object by CNI driver will likely have similar problem that updating `Node` object directly has.  `CSINode` object is also periodically reconciled by kubelet to report values coming from CSI driver and hence any modifications done by CNI driver will be wiped away when `CSINode` object is reconciled by kubelet. 

There are couple of things we could do I think:
1. Do not update attach-limits available on `CSINode` object if it is already non-zero/non-negative value. The downside of this approach is - if a new version of CSI driver is deployed and somehow it supports lower/higher volume limits, then values reported by CSI driver will not be respected and it could cause some problems in some deployment configurations. 
2.  CNI driver could set limits for csi driver if it detects it is configured to run on the node - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/347  (rather than CNI driver directly modifying `CSINode` object).

> Have we thought more about how the scheduler can know not to schedule too many pods? Should the AWS VPC CNI driver dynamically update the pod limits on the node also? Can we tell the kubelet know not to update the pod limits in this case?

These are non-EBS volumes pods right? So basically - a node that has too many EBS volumes attached could have reduced ability to attach ENIs and hence it can handle a reduced number of pods? I am not familiar with the spread of ENIs to pods. Is there a limit? Like 1ENI per 40 pod? We haven't though about it...yet.

**Comment by matthias50** [comment]
@ripta, would the approach I am proposing in #81805 be workable to address your issue?

**Comment by bertinatto** [comment]
FYI, updated the CSI docs recommending CSI drivers to allow for customization of volume limits: https://kubernetes-csi.github.io/docs/volume-limits.html

Note that once CSI migration in AWS is GA (it's beta now, but [disabled by default](https://github.com/kubernetes/kubernetes/blob/27babd49b953820cadbe67bb59d3b1742597ffd2/pkg/features/kube_features.go#L600)), the CSI driver will be the *source* for the volume limits value.

**Comment by jqmichael** [comment]
The fundamental resource limits that AWS enforces is the # of ENIs that can be attached to an ec2 instance, nothing CNI/CSI specifically. Imagine if there're other resources that need to attach ENI, they will run into the same limit. 

If # of ENI is modeled as a Node resource, similar to CPU/memory, Scheduler/CNI/CSI/any other component can be aware of the Node limit and capacity before placing pods or adding additional ENIs.

**Comment by isindir** [comment]
before mainstream fixes the issue I created this small operator: https://github.com/isindir/eks-ebs-node-operator
