### ISSUE TITLE
Switch to VM Update call

### ISSUE THREAD

**Issue by MSSedusch** [kubernetes/kubernetes#80980]
**What would you like to be added**:
Instead of using the VM CreateOrUpdate (https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2019-07-01/compute/virtualmachines.go#L215) function of the Azure Go SDK, use the VM Update function (https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2019-07-01/compute/virtualmachines.go#L1682) in the azure_client (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_client.go#L200)

**Why is this needed**:
Currently, the Azure Cloud Provider is using the VM CreateOrUpdate call when e.g. detach/attaching disks to a VM. In some scenarios, this will re-create a VM that was deleted by an external application. This can lead to orphaned VMs or blocked resources. The Update function will only update an existing VM and will fail if the VM does not exist.

**Comment by feiskyer** [comment]
> n some scenarios, this will re-create a VM that was deleted by an external application. This can lead to orphaned VMs or blocked resources.

Could you describe more about the scenarios? 

@andyzhangx Have you noticed such issues? I wonder adding etags to the API call could help to prevent this?

**Comment by MSSedusch** [comment]
If you have an application that maintains your K8s clusters, e.g. takes care of OS update/patching. If the application wants to patch the OS of a worker node, it would drain the node first. If draining times out, it will go ahead and delete the VM anyway. But K8s might still be detaching disks. These detach operations, because they use CreateOrUpdate, will recreate the VM.

Is there a reason why you would want to create a VM i.e. why CreateOrUpdate is required and Update would not work?

AFAIK, Azure Compute RP does not support etags.

**Comment by andyzhangx** [comment]
that sounds reasonable, thanks @MSSedusch change to use `Update` function would be safer since it's only detach/attach disk operation. I will do that.

**Comment by feiskyer** [comment]
@MSSedusch thanks for the information. Reasonable enough.

/assign @andyzhangx

**Comment by andyzhangx** [comment]
BTW, the reason why we only use `CreateOrUpdate` func in the beginning is that Azure Compute go sdk did not provide a `Create` func at that time...

**Comment by MSSedusch** [comment]
Great. Thanks!
