### ISSUE TITLE
eviction: should pod overhead be considered 

### ISSUE THREAD

**Issue by egernst** [kubernetes/kubernetes#80993]
**What would you like to be added**:

Today, a portion of eviction logic will make a decision based on the utilized resources versus what was specified in requests.

With this in mind, the pod resource requests are determined in the `podRequest` [function in eviction/helpers.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L570-L603).

The usage is calculated as the sum of the container stats, as is shown in [listPodStats](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/stats/cri_stats_provider.go#L121-L222).  

What is missing here is accounting for overheads that are incurred by using a pod, and this is particular evident when considering sandboxed runtimes, which may incur extra cost when doing high network IO, etc, which isn't a part of any one of the container cgroups.

To me, it makes more sense to account for Pod Overhead, both in summed requests as well as for the actual resource utilization.  Since you are making a decision based on "pod totals", is there any reason to *not* just use the pod cgroup created by Kubelet to gather a more accurate summation of resource utilization on the host?

**Why is this needed**:

Seems like a good idea for node stability, as you're accounting for the enitre pod, including its overheads.

Looking for feedback from other node/resource management folks.

/cc @tallclair @dashpole

**Comment by egernst** [comment]
My initial Kubelet focused PR for enabling PodOverhead can be found at https://github.com/kubernetes/kubernetes/pull/79247

In particular, I was looking at deduplicating existing code, and if we were to measure stats at the pod cgroup level, I'd recommend including the following commit: https://github.com/kubernetes/kubernetes/pull/79247/commits/7bbd37ab93da31582c17ce2eb834b2ae49752c7e

I'd need more background on why a sum of container cgroups is being used instead of just measuring the pod cgroup (caching? Historical debt? Other?).

/cc @Random-Liu

**Comment by tallclair** [comment]
Including overhead makes sense to me, but I don't know the nuances of eviction. sig-node seems like the right place to discuss it (I see you added it to the agenda).

**Comment by egernst** [comment]
Somewhat relevant, as there's discussion on "root container" stats gathering from @derekwaynecarr

**Comment by dchen1107** [comment]
@egernst Taking pod overhead into account for the eviction handling is very reasonable to me. 

The reason we were calculating the sum of container's cgroups, instead of measuring the pod cgroup directly is due to the legacy reason. The initial QoS implementation didn't have pod cgroup concept since there is no request & limit at pod level. We later introduced pod cgroup and convinced the community QoS class, evicition, and preemption are all handled at Pod level, not container level. 

After introducing the pod cgroup, we didn't change it due to many provider's production status first; later we kicked out CRI project, along with that project, we roughly decided to introduce different container runtime which has different overhead, etc. Until all of them are done, we can switch to measure pod cgroup directly.

**Comment by dchen1107** [comment]
At SIG Node, from @dashpole 

https://github.com/kubernetes/kubernetes/blob/7c23e1a4ac690aa60bfe677bfdf49f60b38113fd/pkg/kubelet/stats/cri_stats_provider.go#L452 https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L557 PR that added it: https://github.com/kubernetes/kubernetes/pull/64280

**Comment by egernst** [comment]
Thanks.  During the eviction manager's synchronization function, it does indeed still [call](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L245) into the cri-stats-provider here:  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/summary.go#L88-L91

I'll need to trace it a bit more to see how this is or isn't actually being used.

**Comment by dashpole** [comment]
> I'll need to trace it a bit more to see how this is or isn't actually being used.

It is used.  The summary API includes pod-level metrics in addition to container-level metrics.

**Comment by egernst** [comment]
Thanks @dashpole.  Usage is good now, then, and accounting for Pod Overhead for requests will be handled once https://github.com/kubernetes/kubernetes/pull/79247 is merged.
