### ISSUE TITLE
Service finalizer e2e tests are very flaky

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#81000]
**Which jobs are failing**: gce-lb-finalizer

**Which test(s) are failing**: 
Many of the service related tests are pretty flaky, including (non-exclusive list):
```
[sig-network] Services should have session affinity work for service with type clusterIP
[sig-network] Services should be able to switch session affinity for service with type clusterIP
[sig-network] Services should be able to create a functioning NodePort service
[sig-network] Services should be able to change the type from ExternalName to NodePort
[sig-network] Services should have session affinity work for NodePort service
[sig-network] Services should be able to change the type from ExternalName to ClusterIP
[sig-network] Services should be able to switch session affinity for NodePort service
```

**Since when has it been failing**:
From the commits it looks like https://github.com/kubernetes/kubernetes/pull/79667.

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-network-gce#gce-lb-finalizer

**Reason for failure**:
Mostly with this error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1733
Service is not reachable on following endpoint affinity-clusterip-transition:80 over TCP protocol
```

**Anything else we need to know**:
This may be related to https://github.com/kubernetes/kubernetes/issues/80760, but from testgrid it seems like tests are less flaky outside of the finalizer test job. e.g. the usual test jobs are pretty green so far:
- https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce
- https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-slow

cc @mgdevstack

**Comment by MrHohn** [comment]
More snippets on the error:
```
I0805 23:26:06.784] Aug  5 23:26:06.783: INFO: Creating new exec pod
I0805 23:26:09.913] Aug  5 23:26:09.907: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://34.83.124.131 --kubeconfig=/workspace/.kube/config exec --namespace=services-3148 execpod-affinitykwhms -- /bin/sh -x -c nc -z -t -w 2 affinity-clusterip 80'
I0805 23:26:12.593] Aug  5 23:26:12.593: INFO: rc: 1
I0805 23:26:12.594] Aug  5 23:26:12.593: INFO: Unexpected error occurred: error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://34.83.124.131 --kubeconfig=/workspace/.kube/config exec --namespace=services-3148 execpod-affinitykwhms -- /bin/sh -x -c nc -z -t -w 2 affinity-clusterip 80] []  <nil>  + nc -z -t -w 2 affinity-clusterip 80
I0805 23:26:12.594] command terminated with exit code 1
I0805 23:26:12.595]  [] <nil> 0xc0018b9290 exit status 1 <nil> <nil> true [0xc002e602f8 0xc002e60310 0xc002e60328] [0xc002e602f8 0xc002e60310 0xc002e60328] [0xc002e60308 0xc002e60320] [0xa211a0 0xa211a0] 0xc00237c1e0 <nil>}:
I0805 23:26:12.595] Command stdout:
I0805 23:26:12.595] 
I0805 23:26:12.595] stderr:
I0805 23:26:12.595] + nc -z -t -w 2 affinity-clusterip 80
I0805 23:26:12.596] command terminated with exit code 1
I0805 23:26:12.596] 
I0805 23:26:12.596] error:
I0805 23:26:12.596] exit status 1
```

Test usually fails when trying to run a command on an execPod.

**Comment by mgdevstack** [comment]
https://github.com/kubernetes/kubernetes/blob/7c23e1a4ac690aa60bfe677bfdf49f60b38113fd/test/e2e/framework/service/jig.go#L809
2 second of timeout (`-w 2`) should be sufficient to check service reachability, as test waits for at least 1 endpoint to be available before checking service reachability but I'm not sure what is causing the services to be not reachable on certain nodes (testgrid jobs).


> the usual test jobs are pretty green so far:

Tests do not seem flaky on `kind` cluster.

We can verbose to see whether it's operation timeout or connection refused on that port.
```nc -zv -t -w 2 affinity-clusterip 80```

Any other suggestion? @kubernetes/sig-network-test-failures

**Comment by MrHohn** [comment]
FWIW seems like the session affinity test is flaky in 31 jobs (not only specific to the lb-finalizer job): https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=session%20affinity

**Comment by MrHohn** [comment]
> 2 second of timeout (-w 2) should be sufficient to check service reachability, as test waits for at least 1 endpoint to be available before checking service reachability but I'm not sure what is causing the services to be not reachable on certain nodes (testgrid jobs).

Endpoint being available is not equal to the actual server being ready to serve request --- once the server pod is in running & ready state (which doesn't correlate to server being ready if we don't configure readiness probe), it will be included in the endpoint set.

Endpoint being available on the other hand also doesn't mean pod can send traffic to the service VIP and expect it to work. It may take longer for kube-proxy on each node to react to the newly available endpoint (it watches updates from k8s-apiserver) and configure the routing rules on the node, after which pod->service-VIP->pod-IP can happen.

On a busy test cluster above cases may happen more frequently.

It seems like the testReachability func runs command only once:
https://github.com/kubernetes/kubernetes/blob/1438a3c8fc88d6422b716326dc8f9b19921743f5///test/e2e/framework/service/jig.go#L783-L801

We may need to change it to do polling instead to tolerate the initial error. Or somehow guarantee that the server and the node are completely ready to serve & route the request prior to the reachability test.

**Comment by MrHohn** [comment]
> We can verbose to see whether it's operation timeout or connection refused on that port.
nc -zv -t -w 2 affinity-clusterip 80

SG, sounds like useful debug info.

**Comment by MrHohn** [comment]
Error from the latest run: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-lb-finalizer/1160916144257765376
```
    error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://35.233.234.167 --kubeconfig=/workspace/.kube/config exec --namespace=services-6426 execpodh9ml4 -- /bin/sh -x -c nc -zv -t -w 2 nodeport-test 80] []  <nil>  + nc -zv -t -w 2 nodeport-test 80
    nc: connect to nodeport-test port 80 (tcp) failed: Connection refused
    command terminated with exit code 1
     [] <nil> 0xc001b802a0 exit status 1 <nil> <nil> true [0xc00348a0c0 0xc00348a0f0 0xc00348a128] [0xc00348a0c0 0xc00348a0f0 0xc00348a128] [0xc00348a0d0 0xc00348a110] [0x10e7d70 0x10e7d70] 0xc002bfa720 <nil>}:
    Command stdout:
    
    stderr:
    + nc -zv -t -w 2 nodeport-test 80
    nc: connect to nodeport-test port 80 (tcp) failed: Connection refused
    command terminated with exit code 1
```
and
```
    error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://35.233.234.167 --kubeconfig=/workspace/.kube/config exec --namespace=services-8297 execpod2lrzv -- /bin/sh -x -c nc -zv -t -w 2 externalname-service 80] []  <nil>  + nc -zv -t -w 2 externalname-service 80
    nc: connect to externalname-service port 80 (tcp) timed out: Operation in progress
    command terminated with exit code 1
     [] <nil> 0xc002f98f60 exit status 1 <nil> <nil> true [0xc0035ae420 0xc0035ae438 0xc0035ae450] [0xc0035ae420 0xc0035ae438 0xc0035ae450] [0xc0035ae430 0xc0035ae448] [0x10e7d70 0x10e7d70] 0xc00270e780 <nil>}:
    Command stdout:
    
    stderr:
    + nc -zv -t -w 2 externalname-service 80
    nc: connect to externalname-service port 80 (tcp) timed out: Operation in progress
    command terminated with exit code 1
    
    error:
    exit status 1
```

**Comment by MrHohn** [comment]
Thanks, tests have been green since #81341. Closing this.
