### ISSUE TITLE
AWS provider modified untagged security group

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#81007]
**What happened**:

I have AWS environment with workers tagged with kubernetes.io/cluster/$cluster=owned.
The workers use security group that is NOT tagged with any k8s tags. I am using kube-controller-manager with AWS cloud support.

When I created service of type LoadBalancer AWS provider configured everything correctly, including adding ingress rules to the untagged instance security group.

I then removed the service which removed ELB but left behind k8s created security group. I could see the following in kube-controller-manager logs:
```
aws.go:4271] Ignoring DependencyViolation while deleting load-balancer security group (sg-xxx), assuming because LB is in process of deleting
```

**What you expected to happen**:

I expected k8s service creation to fail because worker security group was not tagged correctly.
Alternatively, if the provider chooses to edit worker ingress anyway, it should clean up correctly after service removal.

**How to reproduce it (as minimally and precisely as possible)**:

* deploy cluster on AWS, tag instances with "kubernetes.io/cluster/$cluster=owned". Do NOT tag instance security group
* configure IAM policy, example can be found here: https://github.com/kubernetes/cloud-provider-aws
* create service, for example:
```
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
* above works. To trigger the problem remove the service:
```
kubectl delete svc test
```
* wait 5min. ELB is removed but security group created by the provider is left behind. Also security group attached to my worker still has k8s ELB related ingress

**Anything else we need to know?**:

My environment was certainly not tagged properly but I think the AWS provider behavior is still abnormal - it edited security group that was not tagged correctly and IMO for safety it should not touch it.
This behavior will also leaves k8s created secgrups behind which can be problematic in frequently changing environments.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`):
4.4.0-1087-aws #98-Ubuntu SMP
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jacekn** [comment]
@kubernetes/sig-cloud-provider-bugs

**Comment by M00nF1sh** [comment]
@jacekn 
1. The tags on worker node's securityGroup is only required when you have multiple securityGroup on the primary ENI of worker nodes. If you only have one securityGroup, then the tags are not required, so that behavior is working as expected.
2. For the uncleaned securityGroup, i can see the logs came from `https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/aws/aws.go#L4329`, so we tried to delete the securityGroup with a total timeout with 600 seconds, so i suspect there is something wrong with AWS's eventual consistency model at that period that caused the deletion failed.  We should add finalizer support on this case to always make sure resources are cleaned up before removing service object.
