### ISSUE TITLE
Support isolating memory to a single NUMA node

### ISSUE THREAD

**Issue by bg-chun** [kubernetes/kubernetes#81009]
**What would you like to be added**:

/kind feature

**Why is this needed**:

This issue is intended to start discussion for future enhancement of kubelet

## What is an issue?
- Currently, there is no way to guarantee `local memory access` when container is deployed to machine that has multiple NUMA nodes. 

- When container is pinned to specific `CPUs` by using `CPU Manager`, It can cause inter-NUMA node communication(`remote memory access`) for Memory access which leads to increase an I/O latency and decrease performance.

- `remote memory access` produces high latency and leads performance degradation of `DPDK` containers.

## Cgroups cpuset subsystem
- Using the `cpuset subsystem`, `CPU` and `Memory` can be isolated to a single NUMA node.
- `cpuset.mems` requires memory node selection to permit processes to access a certain NUMA memory node.
- Setting `cpuset.mems` to use a specific NUMA memory node also influence a `hugepages` allocation policy so that hugepages can be isolated to the desired NUMA node.

## Conclusion
- `kubelet` should provide a way to guarantee `local memory access` on multi NUMA node machine.
- `Cpuset subsystem` is key solution for this issue.

## Related issue, KEP and link 
- Link: [Memory in Data Plane Development Kit Part 1: General Concepts](https://software.intel.com/en-us/articles/memory-in-dpdk-part-1-general-concepts)
- Issue: [Hardware topology awareness at node level (including NUMA)](https://github.com/kubernetes/kubernetes/issues/49964)
- Issue: [Support Container Isolation of Hugepages](https://github.com/kubernetes/kubernetes/issues/80716)
- KEP: [Node Topology Manager](https://github.com/kubernetes/enhancements/blob/dcc8c7241513373b606198ab0405634af643c500/keps/sig-node/0035-20190130-topology-manager.md)
- KEP: [CPU Manager](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/cpu-manager.md#implementation-roadmap)
- KEP: [HugePages support in Kubernetes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-hugepages.md)

**Comment by bg-chun** [comment]
Relate this issue, I propose new component(a.k.a Memory Manager) to sig-node.
It can be found [here](https://github.com/kubernetes/enhancements/pull/1203).

**Comment by cy-zheng** [comment]
/reopen
We are looking forward to any solution about that.

**Comment by bg-chun** [comment]
@cy-zheng 
For memory, I(me and my team) will do
1) New CPU policy for NUMA-aware cpu sharing & cpu pinning
[2) Memory Manager(new component of kubelet)](https://github.com/kubernetes/enhancements/pull/1203)

For another, i(me and another contributor) will do
1) enhance scheduler
2) add new policy to topology mnager to refer crd to consider desired resource topology of Pod
