### ISSUE TITLE
Please include security notices in the release notes

### ISSUE THREAD

**Issue by bootc** [kubernetes/kubernetes#81011]
**What would you like to be added**:

The release notes state "No notable changes for this release":
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#changelog-since-v1151
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1144
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#changelog-since-v1138

However it turns out these releases fix important security problems:

* https://seclists.org/oss-sec/2019/q3/117
* https://groups.google.com/d/msg/kubernetes-security-announce/vUtEcSEY6SM/v2ZZxsmtFQAJ

**Why is this needed**:

If people track releases in, for example, GitHub and then use the release notes to see what's changed, they will totally miss that important security problems have been fixed in these releases. People should not have to look in multiple places to find news of such fixes.

The current practice risks people not upgrading because there were "no notable changes" and being oblivious to the risks they run.

**Comment by bootc** [comment]
I expect this is one for @kubernetes/product-security-committee and probably others but I don't really have any clue who.

**Comment by liggitt** [comment]
/sig release

This has to do with the timing of cutting the releases vs sending the announcements. The notices were included in the announcement, but not in the generated md files.

/assign @joelsmith 
can you open a PR to update those?

**Comment by sfxworks** [comment]
Looks like they put it in the email and the group, but not the release notes.
https://groups.google.com/forum/#!topic/kubernetes-security-announce/vUtEcSEY6SM/discussion

**Comment by praseodym** [comment]
Just opened a PR to fix this: https://github.com/kubernetes/kubernetes/pull/81044

(I only noticed that this issue was already assigned after committing my changes, hope that's OK)

**Comment by bootc** [comment]
Thanks @praseodym that PR looks exactly like what I'm after for this particular update!
