### ISSUE TITLE
cpu shares should not be more than 1024

### ISSUE THREAD

**Issue by kstiehl** [kubernetes/kubernetes#81021]
## Background

To understand the actual problem we might need a little bit of background information. 
Kubernetes allows you to specify requested resources on your deployment, for example you can specify that your pod needs two cores. Kubernetes enforces this request by setting `cpu.shares` to `2048`

Currently there is no standard which tells us that `1024` is one core and `2048` is two cores. Its quite the opposite the idea behind `cpu.shares` is that 1024 means no limitations (all cores of your machine).  If you have 4 cores and want to give 2 to your pod you should set `cpu.shares` to `512` and not to `2048`.

if you execute 

     docker run --rm -ti alpine:latest cat /sys/fs/cgroup/cpu,cpuacct/cpu.shares

it outputs 

    1024

because 1024 mean no limitations and not 1 core like it does in kubernetes.

##  But why does it work at the moment?

It works because `cpu.shares` is a relative value. The worth of 1 share depends on how many other shares are around. 
Kubernetes creates it's own cgroup called `kubernetes-pods` which has a `cpu.share` value of `1024` (No limitations). Inside of this cgroup kubernetes creates new cgroups for each pod created on that node. It can give higher values to the pod cgroups since `cpu.shares` are relative to other shares around in that `kubernetes-pods` cgroup.
 
## So everything works why fine should we change it?

Because if you have an application like a JVM that needs to know how many cores it can use, you need a consistent way of setting `cpu.shares`. 

### Here an example

If you are in your application and see a `cpu.share` value of 1024 does it mean you have all the cores available or just one? The answer depends on whether the application is running in kubernetes or not.

If your `cpu.share` value is set to 512 does it mean you have one half of your available cores or one half of one core available? Again, it depends on whether you are running in kubernetes.

To prove that I am not making stuff up here I created this little snippet

```
for shares in 1024 2 2048
do
    docker run --rm -i -c $shares openjdk:11-stretch jshell <<EOF
    Runtime.getRuntime().availableProcessors()
EOF
done
```

It outputs how the number of core that the JVM thinks it has available. (This example only makes sense if you have more than 3 cores in your machine)

As you can see the JVM implemented `1024` correctly (no limitations, all cores). Setting a higher value like `2048` lets the JVM "guess" that it is probably running inside kubernetes (because no one  else sets a higher value than `1024`) and uses less cores than with the value `1024`.

More shares less cores?
As you can see the fact that kubernetes ignores the convention that there should not be a higher value than `1024` bring application developers in a tricky situations since they need to support both somehow.

### It gets even funnier

What happens if we remove one share and set  value like `1023`. We should have a little bit less than all available cores now. But the jvm switches back to the kubernetes standard and prints out one that we have one core.

So what would `2047` shares be ? One core or or all cores?
You guessed correctly it still shows `2` cores.

## Summary
So as you can see the fact that kubernetes decided to do it's own thing brings many problems to application developers. It's not only the JVM which has problems with that. Every application who wants to support running in docker properly will run into this problem and has to decide which  standard it wants to implement.

We should at least have a discussion about this :beers:

**Comment by kstiehl** [comment]
@kubernetes/sig-node

**Comment by zq-david-wang** [comment]
cpulimit = cpu_quota / cpu_period
As for cpu share, it is not what you think it is.....

> cpu.shares
    contains an integer value that specifies a relative share of CPU time available to the tasks in a cgroup. For example, tasks in two cgroups that have cpu.shares set to 100 will receive equal CPU time, but tasks in a cgroup that has cpu.shares set to 200 receive twice the CPU time of tasks in a cgroup where cpu.shares is set to 100. The value specified in the cpu.shares file must be 2 or higher.

**Comment by kstiehl** [comment]
cpu limits have nothing to do with this discussion. I am talking about resource requests in kubernetes which are realised by cpu.shares, which work exactly like you say. 
This issue is not about that what kubernetes is doing with cpu.shares is not working. It is about that it is not going by the convention that 1024 cpu.shares is equal to 100% of the available resources. Which leads to various side effects in applications like the JVM or other application that want to find out how many guaranteed cpus they have.

As you can see in the snippet I attached it alredy leads to problems in the JVM.

**Comment by zq-david-wang** [comment]
the number of core could be used by container  = cpu limit = cpu_quota / cpu_period

Strange to see JVM  would use cpu share to determine the number of core that it can use.

**Comment by kstiehl** [comment]
It's actually quite logical to use the cpu.shares instead of the cpu_limit. Because  cpu_quota / cpu_period is just the max limit the JVM can use if no other pod is using the cpu right now. cpu.shares are guaranteed. 
The JVM needs to know the number of guaranteed cores because almost every Java framework and all java servers align their thread pools to the number of available cores.

**Comment by zq-david-wang** [comment]
If you run two or more JVMs on the same non-container environment, what the available core used by each JVM? Could JVM calculate correctly the "need to know number of guaranteed cores"?
I am no java expert, but my guess is that each JVM would use total number of cores on host without considering other process.  So what JVM needs is the upper limit of CPU resource  it can use, not the minimum/guaranteed CPU resource (which normally could not be calculated correctly)
 
But JDK do use cpu share to calculate cpu cores when cpu.q**uota is not set**.


Some openjdk code online http://cr.openjdk.java.net/~sgehwolf/webrevs/JDK-8216366/webrev.01/raw_files/new/src/hotspot/os/linux/osContainer_linux.cpp
```
 /* active_processor_count
 *
 * Calculate an appropriate number of active processors for the
 * VM to use based on these three inputs.
 *
 * cpu affinity
 * cgroup cpu quota & cpu period
 * cgroup cpu shares
 *
 * Algorithm:
 *
 * Determine the number of available CPUs from sched_getaffinity
 *
 * If user specified a quota (quota != -1), calculate the number of
 * required CPUs by dividing quota by period.
 *
 * If shares are in effect (shares != -1), calculate the number
 * of CPUs required for the shares by dividing the share value
 * by PER_CPU_SHARES.
 *
 * All results of division are rounded up to the next whole number.
 *
 * If neither shares or quotas have been specified, return the
 * number of active processors in the system.
 *
 * If both shares and quotas have been specified, the results are
 * based on the flag PreferContainerQuotaForCPUCount.  If true,
 * return the quota value.  If false return the smallest value
 * between shares or quotas.
 *
 * If shares and/or quotas have been specified, the resulting number
 * returned will never exceed the number of active processors.
 *
 * return:
 *    number of CPUs
 *
```
The code may also explain your question about rounding.
 The code may be old and current implement dose not quite coincide with it,  I run some test with openjdk:11, as long as cpu.quota is set, cpu.share could not have effect no matter whether PreferContainerQuotaForCPUCount is true or false
