### ISSUE TITLE
Improve coverage of authentication metrics in apiserver

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#81028]
Possible generic metrics:
* overall success, failure, error count
* overall latency
* per authenticator success and error count
* per authenticator latency

Authenticator specific metrics:
* Expired service account tokens observed.
* TTL of succesfully authenticated client certs observed during authentication,
* Count of expired client certs observed during client authentication that would have otherwise been authenticated.

/sig auth
/kind feature

**Comment by RainbowMango** [comment]
Can I take this task?

**Comment by mikedanese** [comment]
Yes please.

**Comment by RainbowMango** [comment]
@mikedanese @enj 

For `overall latency`, how about this:
```
	authenticationLatency = metrics.NewHistogramVec(
		&metrics.HistogramOpts{
			Name: "authentication_latency",
			Help: "Latency of overall authentication",
			StabilityLevel: metrics.ALPHA,
		},
		[]string{"success"},
	)
```

**Comment by RainbowMango** [comment]
> per authenticator success and error count
per authenticator latency

Does the authenticator here mean the user?
If possible, please help some more detail instructions for the metrics we wanted.

**Comment by mikedanese** [comment]
> Does the authenticator here mean the user?

Authenticator here means which authenticator performed the authentication (Client TLS, service account token, etc...). I think overall latency would also be useful but I might try to do that with tracing logs. Let me take a look.

**Comment by RainbowMango** [comment]
Following is overall latency dump from my local up cluster. Is it ok?
```
# HELP authentication_latency_seconds [ALPHA] Authentication overall latency in seconds. Broken out by result.
# TYPE authentication_latency_seconds histogram
authentication_latency_seconds_bucket{result="success",le="0.001"} 1341
authentication_latency_seconds_bucket{result="success",le="0.002"} 1344
authentication_latency_seconds_bucket{result="success",le="0.004"} 1344
authentication_latency_seconds_bucket{result="success",le="0.008"} 1344
authentication_latency_seconds_bucket{result="success",le="0.016"} 1345
authentication_latency_seconds_bucket{result="success",le="0.032"} 1345
authentication_latency_seconds_bucket{result="success",le="0.064"} 1345
authentication_latency_seconds_bucket{result="success",le="0.128"} 1345
authentication_latency_seconds_bucket{result="success",le="0.256"} 1345
authentication_latency_seconds_bucket{result="success",le="0.512"} 1345
authentication_latency_seconds_bucket{result="success",le="+Inf"} 1345
authentication_latency_seconds_sum{result="success"} 0.18180206400000004
authentication_latency_seconds_count{result="success"} 1345
```

Definition of the metric: 
```go
	authenticationLatency = metrics.NewHistogramVec(
		&metrics.HistogramOpts{
			Name: "authentication_latency_seconds",
			Help: "Authentication overall latency in seconds. Broken out by result.",
			Buckets: prometheus.ExponentialBuckets(0.001, 2, 10),
			StabilityLevel: metrics.ALPHA,
		},
		[]string{"result"},
	)
```

**Comment by mikedanese** [comment]
Yes that looks good with the result.

**Comment by mikedanese** [comment]
I think we want metrics for the authenticator cache.

**Comment by RainbowMango** [comment]
> I think we want metrics for the authenticator cache.

How time flies! I turned to work on the metrics stability framework after done part of this, now it's time back to this issue now.

/remove-lifecycle stale
/milestone v1.18

**Comment by RainbowMango** [comment]
> I think we want metrics for the authenticator cache.

@mikedanese 
Do you mean here?
https://github.com/kubernetes/kubernetes/blob/cfdfd043a086eba12a673faf7a7dee89d28c82e3/staging/src/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go#L25-L33

Well, please walk me through your thoughts anyway. I guess you want a counter vector here.

**Comment by mikedanese** [comment]
I think this is actually good for now.
