### ISSUE TITLE
Deprecate and remove cloud-controller-manager binary

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#81027]
We dropped cloud-controller-manager deb from the release in https://github.com/kubernetes/kubernetes/pull/65338. Since all external cloud providers will end up having their own custom controller-manager, we should deprecate and eventually remove this binary and associated bits.

/sig cloud-provider

**Comment by dims** [comment]
cc @cheftako @andrewsykim

**Comment by BenTheElder** [comment]
Er #65338 only changed the bazel build which is not used for releases?

**Comment by cheftako** [comment]
I agree that there is little/no value in shipping a CCM binary from K/K. I think there is value in keeping some sort of CCM framework in K/K which can be easily extended to cloud providers to generate their flavor of CCM.

**Comment by justaugustus** [comment]
@cheftako @dims -- Do we know what remains to be done here?
/remove-lifecycle stale

**Comment by dims** [comment]
/close

that should be it! thanks @justaugustus
