### ISSUE TITLE
kubelet --docker key doesn't have effect on all requests to docker

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#8102]
When I've changed the docker socket for kubelet, it seem to be working from the glance view, but it actually opens /var/run/docker.sock for most of requests. 
The only way to make it working properly was to change docker socket to /var/run/real_docker.sock and put my wrapper into /var/run/docker.sock. 
Following strace output (download that 'image' and rename to txt or just open with plaintext editor) proves it:
![kubelet strace out](https://cloud.githubusercontent.com/assets/407040/7580498/eb380f7c-f8a8-11e4-8e04-1d9d2678e227.PNG)

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-node

**Comment by dims** [comment]
Setting the DOCKER_HOST environment variable seems to work
https://github.com/dims/kubernetes/blob/3c0c5ed4e019f2c1aef520a7d1f78763368bede7/vendor/github.com/docker/engine-api/client/client.go#L58

**Comment by yujuhong** [comment]
@onorua what version of kubelet do you use and how did you change the docker endpoint?

**Comment by dims** [comment]
There's a new --docker-endpoint parameter in kubelet that can be used as well. 
https://github.com/kubernetes/kubernetes/blob/75ef1ca27041f76f6d5b865f5070554c5276a72b/cmd/kubelet/app/options/options.go#L177

@onorua @nikhiljindal @yujuhong - we should close this one

**Comment by Random-Liu** [comment]
I believe this should work now: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L305-L309

Let's close this one now. If anyone meets this problem again, feel free to reopen this.
