### ISSUE TITLE
Show output while validating the cluster (in kube-up)

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#8103]
Since #8005 was merged, running `./cluster/kube-up.sh` is really quiet while calling validate-cluster (previously you could see each time it called kubectl to check the master components or get the nodes). It would be nice to print some output (like the dots you see while waiting for the API to be reachable) so that you know the script is still doing something and isn't stuck. 

/cc @lavalamp

**Comment by lavalamp** [comment]
As long as it doesn't cause ./cluster/kubectl.sh to print out junk every time I do anything (bad for using it from scripts!), I'll be happy. :)

**Comment by bgrant0607** [comment]
Obsolete
