### ISSUE TITLE
Conformance tests should not require access to kubelet API

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#81052]
**What happened**: 
In reviewing  a test for promotion to conformance I noticed the kubelet API was being accessed via the API server's node proxy endpoint (ref: https://github.com/kubernetes/kubernetes/pull/80731#discussion_r310836102).  This seemed off, so I reviewed [our conformance test requirements doc](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements).  It doesn't explicitly call out kubelet API access as allowed or disallowed.

[I asked #k8s-conformance if we had an opinion on this](https://kubernetes.slack.com/archives/C78F00H99/p1565050383095300).  @timothysc and @liggitt agreed kubelet API access seems like a bad idea.

I'm now surveying what we have that _does_ assume kubelet API access.  It's definitely used by parts of e2e framework and some Conformance tests. I'm trying to verify how critical its use is.  It appears that much of it is related to debugging or verifying whether kubelets and the control plane agree on who is running what.

**What you expected to happen**: 
Find a blanket policy that bans kubelet API access for Conformance tests, whether directly, or indirectly through the API server's node proxy endpoint, at any time.

Alternatively, find a policy that says kubelet API access may be allowed, but only for debugging or failure purposes (must not be on the critical path to make the test pass)

Alternatively, find a policy that says kubelet API access is allowed, but only indirectly through the API server, and evaluated against the same constraints we use for control plane access (GA, non-optional)

If we want to say kubelet API access is banned, we can use this as a tracking issue to demote whichever tests rely on it, and come up with a plan to verify the same behavior without kubelet API access.

/area conformance
/sig architecture
/priority important-soon
/milestone v1.16
/assign

**Comment by spiffxp** [comment]
Look for anything that ends up calling `ProxyRequest`
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/node/resource.go#L254

----

`framework.AfterEach` may end up calling it if the test fails, via:
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/framework.go#L345
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/util.go#L1735
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/util.go#L1768
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/util.go#L1787
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/kubelet/kubelet_pods.go#L29
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/framework/kubelet/kubelet_pods.go#L41

----

Conformance test `Pods should be submitted and removed [NodeConformance]` requires kubelet API access to pass
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/common/pods.go#L291

----

Some `Kubectl client` Conformance tests may end up calling this if the test fails
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/kubectl/kubectl.go#L237

specifically
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/kubectl/kubectl.go#L1029 
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/kubectl/kubectl.go#L1134
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/kubectl/kubectl.go#L1375

----

`SchedulerPredicates [Serial]` calls this in BeforeEach, which will happen before some Conformance tests

https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/scheduling/predicates.go#L102

----

Other areas this is used:

only if the test fails

https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/apps/daemon_restart.go#L318

required for a pre-stop hook test to pass

https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/node/pre_stop.go#L212

required to make sure the readonly kubelet apis aren't exposed via api server proxy

https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/lifecycle/kubelet_security.go#L50

resource usage tracking tests require kubelet api access to pass

https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/node/kubelet_perf.go#L113
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/node/kubelet_perf.go#L148

`EquivalenceCache [Serial]` tests call this in `BeforeEach`
https://github.com/kubernetes/kubernetes/blob/6049253aae49f87985a59ba45bedded94023b093/test/e2e/scheduling/equivalence_cache_predicates.go#L86

**Comment by spiffxp** [comment]
Looking for `ports.KubeletPort` doesn't turn up any additional conformance tests, and I don't feel compelled to link the two other tests that use it as they are unlikely to ever be eligible.

**Comment by spiffxp** [comment]
The examples pointed out by @liggitt on slack, the kubelet's `/logs` endpoints is required to be available for these to pass

https://github.com/kubernetes/kubernetes/blob/7f1ae0e32d2d42efc243b0b3d69a95797ce67046/test/e2e/network/proxy.go#L70

https://github.com/kubernetes/kubernetes/blob/7f1ae0e32d2d42efc243b0b3d69a95797ce67046/test/e2e/network/proxy.go#L77

**Comment by xmudrii** [comment]
@spiffxp Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by liggitt** [comment]
are there further changes for this targeted at 1.16?

**Comment by xmudrii** [comment]
@spiffxp Any update on this?

**Comment by kikisdeliveryservice** [comment]
Bug Triage Release Team checking in.  Code freeze for the 1.17 release is on November 18. Will this make it in?  Thanks!

**Comment by kikisdeliveryservice** [comment]
hi @johnbelamaric is this still targetting for 1.17 or can we move to 1.18? Code freeze is Nov 14th.  thanks!

**Comment by spiffxp** [comment]
So we've updated the documented policy.  

My suggestion to close this out is to drop the [Conformance] tag from the tests that currently require the kubelet API to pass, and open issues that they need to be rewritten.  Ignore whether the API is needed for diagnostic info in failure modes.

>SchedulerPredicates [Serial] calls this in BeforeEach, which will happen before some Conformance tests (if this fails, the tests will fail)

>Conformance test Pods should be submitted and removed [NodeConformance] requires kubelet API access to pass

**Comment by dims** [comment]
i'd support this @spiffxp @liggitt ^^

**Comment by jtslear** [comment]
Hello @spiffxp , @liggitt, @johnbelamaric 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18?

**Comment by jtslear** [comment]
Hello @kubernetes/sig-architecture-bugs 
There's been no movement on this issue this year.  Should this get pushed to the next milestone?

**Comment by johnbelamaric** [comment]
yes, please
