### ISSUE TITLE
Kube-proxy should not watch endpoints from headless services

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/kubernetes#81060]
**What happened**:
With several large headless services in the cluster providing DNS records for statefulset pods, we see about 1TB of watch traffic for Endpoints per day! Some of these Endpoints objects approach 1MB in size and we have thousands of nodes, so a single update to the Endpoints object results in gigabytes of broadcast.

**What you expected to happen**:
kube-proxy does not need to receive any updates for headless services.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Big headless services like this are a stand-in for the lack of other pod-addressable DNS features. There's a lot of improvements that could be made to prevent this, but it seems like an extremely easy change to prevent kube-proxy from receiving updates for headless services.

A simple solution:
1. Make the Service controller propagate `ClusterIP: None` to a label on the Endpoints object like `service.k8s.io/headless: "true"` or similar.
2. Add a filter in kube-proxy's endpoints watch to exclude the headless label.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: EC2
- OS (e.g: `cat /etc/os-release`): custom distro
- Kernel (e.g. `uname -a`): 4.14.133
- Install tools: custom

**Comment by rikatz** [comment]
@thockin does this need a KEP? Otherwise I can try start working on this.

**Comment by rikatz** [comment]
@PaulFurtado I've made a PR, take a look to see if this is applicable :)

I'll wait until someone from the ORG also take a look and see what else can be improved.

**Comment by thockin** [comment]
@freehan @robscott PTAL at this wrt EndpointSlice
