### ISSUE TITLE
How to specify container's runtime,eg. nvidia-docker or runC?

### ISSUE THREAD

**Issue by qiuhui** [kubernetes/kubernetes#81062]
I can not see anything related to container's runtime in the API Object。Can anyone help me?

**Comment by zouyee** [comment]
https://kubernetes.io/docs/concepts/containers/runtime-class/#upgrading-runtimeclass-from-alpha-to-beta
we could use `runtimeclass` feature.

**Comment by lzfxxx** [comment]
> https://kubernetes.io/docs/concepts/containers/runtime-class/#upgrading-runtimeclass-from-alpha-to-beta
> we could use `runtimeclass` feature.

@zouyee how to use runtimeclass for nvidia-docker2/nvidia-container-runtime

I've tried several config, but not working.
```
apiVersion: node.k8s.io/v1beta1  # RuntimeClass is defined in the node.k8s.io API group
kind: RuntimeClass
metadata:
  name: nvidia 
handler: "nvidia runc" / nvidia / nvidia-container-runtime  # these three values are tried
```

And this is my runtime config for docker
```
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
```

**Comment by CermakM** [comment]
Very interested in the solution to this. Was there any?

**Comment by HenryLiu0** [comment]
> > https://kubernetes.io/docs/concepts/containers/runtime-class/#upgrading-runtimeclass-from-alpha-to-beta
> > we could use `runtimeclass` feature.
> 
> @zouyee how to use runtimeclass for nvidia-docker2/nvidia-container-runtime
> 
> I've tried several config, but not working. k8s version is 1.15.3
> 
> ```
> apiVersion: node.k8s.io/v1beta1
> kind: RuntimeClass
> metadata:
>   name: nvidia 
> 
> # these five values were tried
> handler: "nvidia runc" / nvidia / nvidia-container-runtime / nvidia-docker / nvidia-docker2
> ```
> 
> And this is my runtime config for docker
> 
> ```
>     "runtimes": {
>         "nvidia": {
>             "path": "nvidia-container-runtime",
>             "runtimeArgs": []
>         }
>     },
> ```

@lzfxxx  Have you found any solution for k8s 1.15 for docker?
