### ISSUE TITLE
Control plain won't join

### ISSUE THREAD

**Issue by oaudry** [kubernetes/kubernetes#81071]
**What happened**:

I got 3 masters. I try to replace them with new hardware. One by one. 

I removed the first.  gra3-k8s001

```
k drain gra3-k8s001
k delete node gra3-k8s001
```

I probably should use kubeadm reset -f. But I found that I need to update the kubeadm init config map. What I did : (perhaps something else to do)

```
$ k -n kube-system get cm kubeadm-config -o yaml
+ kubectl -n kube-system get cm kubeadm-config -o yaml
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - api.k8s.smobe.fr
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: api.k8s.smobe.fr:5443
    controllerManager: {}
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.15.0
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    scheduler: {}
  ClusterStatus: |
    apiEndpoints:
      rbx4-k8s001:
        advertiseAddress: 192.168.208.14
        bindPort: 6443
      sbg2-k8s001:
        advertiseAddress: 192.168.208.12
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2019-07-17T17:23:02Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "6459001"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
  uid: 7880b246-c404-4a1c-867a-1a41e767e00b

```

But on the new installed device the join command failed on etcd health check. The device got the same hostname and same private ip, not same public ip. The old master became a worker with a new private ip and his own public ip. Meaning that this worker got the public ip of the old control plane. Is that an issue ? I don't think so.

**What you expected to happen**:

The new control plan to join

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

+ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: my own hardware.
- OS (e.g: `cat /etc/os-release`): debian buster
- Kernel (e.g. `uname -a`): 4.19.0-5-amd64
- Install tools: kubeadm

here the logs :

```
root@gra3-k8s001:~# kubeadm join --v=6 api.k8s.smobe.fr:5443 --token 1ldzme.ctze95ddy1zwfi1m     --discovery-token-ca-cert-hash sha256:8dde796074f0ac86f72deb521a90ba4a04fc88d4f6c1336ae4e796dcd5fe87df  --apiserver-advertise-address "192.168.208.13" --control-plane  --certificate-key ed415450203c34432119330bc7df6baf9742386f9b87f3fcf21adaaaaa7346bb  
I0807 11:52:17.758456   41373 join.go:364] [preflight] found NodeName empty; using OS hostname as NodeName
I0807 11:52:17.758496   41373 initconfiguration.go:105] detected and using CRI socket: /var/run/dockershim.sock
[preflight] Running pre-flight checks
I0807 11:52:17.758531   41373 preflight.go:91] [preflight] Running general checks
I0807 11:52:17.758555   41373 checks.go:254] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0807 11:52:17.758581   41373 checks.go:292] validating the existence of file /etc/kubernetes/kubelet.conf
I0807 11:52:17.758586   41373 checks.go:292] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0807 11:52:17.758591   41373 checks.go:105] validating the container runtime
I0807 11:52:17.806413   41373 checks.go:131] validating if the service is enabled and active
I0807 11:52:17.861355   41373 checks.go:341] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0807 11:52:17.861388   41373 checks.go:341] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0807 11:52:17.861402   41373 checks.go:653] validating whether swap is enabled or not
I0807 11:52:17.861418   41373 checks.go:382] validating the presence of executable ip
I0807 11:52:17.861433   41373 checks.go:382] validating the presence of executable iptables
I0807 11:52:17.861443   41373 checks.go:382] validating the presence of executable mount
I0807 11:52:17.861451   41373 checks.go:382] validating the presence of executable nsenter
I0807 11:52:17.861458   41373 checks.go:382] validating the presence of executable ebtables
I0807 11:52:17.861466   41373 checks.go:382] validating the presence of executable ethtool
I0807 11:52:17.861473   41373 checks.go:382] validating the presence of executable socat
I0807 11:52:17.861480   41373 checks.go:382] validating the presence of executable tc
I0807 11:52:17.861487   41373 checks.go:382] validating the presence of executable touch
I0807 11:52:17.861496   41373 checks.go:524] running all checks
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.1. Latest validated version: 18.09
I0807 11:52:17.877403   41373 checks.go:412] checking whether the given node name is reachable using net.LookupHost
I0807 11:52:17.877469   41373 checks.go:622] validating kubelet version
I0807 11:52:17.904585   41373 checks.go:131] validating if the service is enabled and active
I0807 11:52:17.909600   41373 checks.go:209] validating availability of port 10250
I0807 11:52:17.909667   41373 checks.go:439] validating if the connectivity type is via proxy or direct
I0807 11:52:17.909682   41373 join.go:433] [preflight] Discovering cluster-info
I0807 11:52:17.909756   41373 token.go:199] [discovery] Trying to connect to API Server "api.k8s.smobe.fr:5443"
I0807 11:52:17.910015   41373 token.go:74] [discovery] Created cluster-info discovery client, requesting info from "https://api.k8s.smobe.fr:5443"
I0807 11:52:17.934832   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-public/configmaps/cluster-info 200 OK in 24 milliseconds
I0807 11:52:17.936164   41373 token.go:140] [discovery] Requesting info from "https://api.k8s.smobe.fr:5443" again to validate TLS against the pinned public key
I0807 11:52:18.008949   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-public/configmaps/cluster-info 200 OK in 72 milliseconds
I0807 11:52:18.009873   41373 token.go:163] [discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "api.k8s.smobe.fr:5443"
I0807 11:52:18.009911   41373 token.go:205] [discovery] Successfully established connection with API Server "api.k8s.smobe.fr:5443"
I0807 11:52:18.009963   41373 join.go:447] [preflight] Fetching init configuration
I0807 11:52:18.009980   41373 join.go:480] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
I0807 11:52:18.043675   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-system/configmaps/kubeadm-config 200 OK in 32 milliseconds
I0807 11:52:18.079034   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-system/configmaps/kube-proxy 200 OK in 33 milliseconds
I0807 11:52:18.116406   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-system/configmaps/kubelet-config-1.15 200 OK in 33 milliseconds
I0807 11:52:18.119681   41373 interface.go:384] Looking for default routes with IPv4 addresses
I0807 11:52:18.119710   41373 interface.go:389] Default route transits interface "eno1"
I0807 11:52:18.120141   41373 interface.go:196] Interface eno1 is up
I0807 11:52:18.120271   41373 interface.go:244] Interface "eno1" has 1 addresses :[51.91.31.182/24].
I0807 11:52:18.120309   41373 interface.go:211] Checking addr  51.91.31.182/24.
I0807 11:52:18.120331   41373 interface.go:218] IP found 51.91.31.182
I0807 11:52:18.120351   41373 interface.go:250] Found valid IPv4 address 51.91.31.182 for interface "eno1".
I0807 11:52:18.120371   41373 interface.go:395] Found active IP 51.91.31.182 
I0807 11:52:18.120461   41373 preflight.go:102] [preflight] Running configuration dependant checks
[preflight] Running pre-flight checks before initializing the new control plane instance
I0807 11:52:18.120509   41373 checks.go:581] validating Kubernetes and kubeadm version
I0807 11:52:18.120554   41373 checks.go:172] validating if the firewall is enabled and active
I0807 11:52:18.140672   41373 checks.go:209] validating availability of port 6443
I0807 11:52:18.140807   41373 checks.go:209] validating availability of port 10251
I0807 11:52:18.140879   41373 checks.go:209] validating availability of port 10252
I0807 11:52:18.140947   41373 checks.go:292] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0807 11:52:18.140979   41373 checks.go:292] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0807 11:52:18.141001   41373 checks.go:292] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0807 11:52:18.141023   41373 checks.go:292] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0807 11:52:18.141044   41373 checks.go:439] validating if the connectivity type is via proxy or direct
I0807 11:52:18.141082   41373 checks.go:475] validating http connectivity to first IP address in the CIDR
I0807 11:52:18.141115   41373 checks.go:475] validating http connectivity to first IP address in the CIDR
I0807 11:52:18.141140   41373 checks.go:209] validating availability of port 2379
I0807 11:52:18.141210   41373 checks.go:209] validating availability of port 2380
I0807 11:52:18.141276   41373 checks.go:254] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0807 11:52:18.200527   41373 checks.go:842] image exists: k8s.gcr.io/kube-apiserver:v1.15.0
I0807 11:52:18.223985   41373 checks.go:842] image exists: k8s.gcr.io/kube-controller-manager:v1.15.0
I0807 11:52:18.245761   41373 checks.go:842] image exists: k8s.gcr.io/kube-scheduler:v1.15.0
I0807 11:52:18.268162   41373 checks.go:842] image exists: k8s.gcr.io/kube-proxy:v1.15.0
I0807 11:52:18.290190   41373 checks.go:842] image exists: k8s.gcr.io/pause:3.1
I0807 11:52:18.311920   41373 checks.go:842] image exists: k8s.gcr.io/etcd:3.3.10
I0807 11:52:18.333916   41373 checks.go:842] image exists: k8s.gcr.io/coredns:1.3.1
[download-certs] Downloading the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
I0807 11:52:18.370331   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-system/secrets/kubeadm-certs 200 OK in 36 milliseconds
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0807 11:52:18.384054   41373 certs.go:39] creating PKI assets
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [gra3-k8s001 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local api.k8s.smobe.fr api.k8s.smobe.fr] and IPs [10.96.0.1 192.168.208.13]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [gra3-k8s001 localhost] and IPs [192.168.208.13 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [gra3-k8s001 localhost] and IPs [192.168.208.13 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Valid certificates and keys now exist in "/etc/kubernetes/pki"
I0807 11:52:19.472594   41373 certs.go:70] creating a new public/private key files for signing service account users
[certs] Using the existing "sa" key
[kubeconfig] Generating kubeconfig files
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
I0807 11:52:19.713900   41373 manifests.go:115] [control-plane] getting StaticPodSpecs
I0807 11:52:19.717529   41373 manifests.go:131] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I0807 11:52:19.717579   41373 manifests.go:115] [control-plane] getting StaticPodSpecs
I0807 11:52:19.718152   41373 manifests.go:131] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[control-plane] Creating static Pod manifest for "kube-scheduler"
I0807 11:52:19.718176   41373 manifests.go:115] [control-plane] getting StaticPodSpecs
I0807 11:52:19.718554   41373 manifests.go:131] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[check-etcd] Checking that the etcd cluster is healthy
I0807 11:52:19.718897   41373 loader.go:359] Config loaded from file:  /etc/kubernetes/admin.conf
I0807 11:52:19.719296   41373 local.go:66] [etcd] Checking etcd cluster health
I0807 11:52:19.719311   41373 local.go:69] creating etcd client that connects to etcd pods
I0807 11:52:19.752327   41373 round_trippers.go:438] GET https://api.k8s.smobe.fr:5443/api/v1/namespaces/kube-system/configmaps/kubeadm-config 200 OK in 32 milliseconds
I0807 11:52:19.753223   41373 etcd.go:106] etcd endpoints read from pods: https://192.168.208.14:2379,https://192.168.208.12:2379
I0807 11:52:19.781245   41373 etcd.go:147] etcd endpoints read from etcd: https://192.168.208.12:2379,https://192.168.208.13:2379,https://192.168.208.14:2379
I0807 11:52:19.781314   41373 etcd.go:124] update etcd endpoints: https://192.168.208.12:2379,https://192.168.208.13:2379,https://192.168.208.14:2379
error execution phase check-etcd: etcd cluster is not healthy: context deadline exceeded
```
the etcd nodes https://192.168.208.12:2379 and https://192.168.208.14:2379 are reachable.

As the etcd check is not working the node is not bootstrapped.

**Comment by oaudry** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by neolit123** [comment]
> I probably should use kubeadm reset -f. But I found that I need to update the kubeadm init config map. What I did : (perhaps something else to do)

`reset` should be enough to remove members from the ClusterStatus list.

> But on the new installed device the join command failed on etcd health check. The device got the same hostname and same private ip, not same public ip. The old master became a worker with a new private ip and his own public ip. Meaning that this worker got the public ip of the old control plane. Is that an issue ? I don't think so.

this sounds to me like etcd lost quorum
https://blog.containership.io/etcd/

unfortunately once the etcd cluster becomes unhealthy it's not so user-friendly to recover.
to debug this you can use etcdctl. open the file /etc/kubernetes/manifests/etcd.yaml and find a line that has etcdct with certificates as flags. you can either exec into the same container and use a similar command line or install etcdctl on the host.

this is not exactly a kubeadm issue but more of how etcd is designed.

/remove-kind bug
/triage support

**Comment by oaudry** [comment]
@neolit123 you save my day !! So many thx.

For the record here the command to run on one of the remaining etcd pod :

Find the id of the member to remove

```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
740381e3c57ef823, started, gra3-k8s001, https://192.168.208.13:2380, https://192.168.208.13:2379
77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379

```
I want to remove 740381e3c57ef823

```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member remove 740381e3c57ef823
Member 740381e3c57ef823 removed from cluster a2c90ef66bb95cc9
```

Checking

```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
```

Now I can join my new master.

**Comment by ricardbejarano** [comment]
> @neolit123 you save my day !! So many thx.
> 
> For the record here the command to run on one of the remaining etcd pod :
> 
> Find the id of the member to remove
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
> 5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
> 740381e3c57ef823, started, gra3-k8s001, https://192.168.208.13:2380, https://192.168.208.13:2379
> 77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
> ```
> 
> I want to remove 740381e3c57ef823
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member remove 740381e3c57ef823
> Member 740381e3c57ef823 removed from cluster a2c90ef66bb95cc9
> ```
> 
> Checking
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
> 5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
> 77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
> ```
> 
> Now I can join my new master.

This solved it for me. Thanks!

**Comment by Piranha900** [comment]
You're a life saver! 

> @neolit123 you save my day !! So many thx.
> 
> For the record here the command to run on one of the remaining etcd pod :
> 
> Find the id of the member to remove
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
> 5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
> 740381e3c57ef823, started, gra3-k8s001, https://192.168.208.13:2380, https://192.168.208.13:2379
> 77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
> ```
> 
> I want to remove 740381e3c57ef823
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member remove 740381e3c57ef823
> Member 740381e3c57ef823 removed from cluster a2c90ef66bb95cc9
> ```
> 
> Checking
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
> 5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
> 77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
> ```
> 
> Now I can join my new master.

you're a ilifesaver

**Comment by lemongarbage** [comment]
> @neolit123 you save my day !! So many thx.
> 
> For the record here the command to run on one of the remaining etcd pod :
> 
> Find the id of the member to remove
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
> 5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
> 740381e3c57ef823, started, gra3-k8s001, https://192.168.208.13:2380, https://192.168.208.13:2379
> 77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
> ```
> 
> I want to remove 740381e3c57ef823
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member remove 740381e3c57ef823
> Member 740381e3c57ef823 removed from cluster a2c90ef66bb95cc9
> ```
> 
> Checking
> 
> ```
> ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key member list
> 5a4945140f0b39d9, started, sbg2-k8s001, https://192.168.208.12:2380, https://192.168.208.12:2379
> 77a8fbb530b10f4a, started, rbx4-k8s001, https://192.168.208.14:2380, https://192.168.208.14:2379
> ```
> 
> Now I can join my new master.

Yeah this did it for me. Thanks!!

**Comment by B1ue-W01f** [comment]
Unless I'm incredibly unlucky and every single node failed to unjoin correctly, the bottom line appears to be that removing a control plane from the cluster leaves it as part of the etcd cluster - which is rather important, leaving the etcd cluster unhealthy with a none responsive node and unable to accept a rejoin.

At a minimum this could do with better documentation.

**Comment by neolit123** [comment]
> removing a control plane from the cluster leaves it as part of the etcd cluster - which is rather important, leaving the etcd cluster unhealthy with a none responsive node and unable to accept a rejoin.

Calling 'kubeadm reset' on a control plane host removes the etcd member for that host. Kubeadm reset is already a documented step for proper cleanup.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tear-down

**Comment by B1ue-W01f** [comment]
> > removing a control plane from the cluster leaves it as part of the etcd cluster - which is rather important, leaving the etcd cluster unhealthy with a none responsive node and unable to accept a rejoin.
> 
> Calling 'kubeadm reset' on a control plane host removes the etcd member for that host. Kubeadm reset is already a documented step for proper cleanup.
> 
> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tear-down

Ive just carried out migration from dockershim to crio on around 100 nodes, running kubeadm on every instance. Not a single control plane was removed from the etcd cluster without manual intervention of etcdctl.
