### ISSUE TITLE
Kubeadm upload component configuration from file to configmap

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubernetes#81070]
**What would you like to be added**:

Upload kubelet configs from file to configmap, something like,

`kubeadm config upload from-file --component-configs KubeletConfiguration --config kubeadm-kubelet.yaml`

```kubeadm-kubelet.yaml
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
systemReserved:
  cpu: "500m"
    memory: "200M"
systemReservedCgroup: "/system.slice"
cgroupDriver: "systemd"
```

**Why is this needed**:

In order to maintain kubelet config in a consistent way by kubeadm, from upload to download.

**Comment by neolit123** [comment]
hi @jfbai thanks for logging this.

this seems like a feature that should be tracked the kubernetes/kubeadm repository.
please create the issue in that repository. 

/area kubeadm
/close
