### ISSUE TITLE
DNS tests fail on Windows due to getent usage

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#81080]
**Which jobs are failing**:

    sig-windows#flannel-overlay-windows-master

**Which test(s) are failing**:

    [sig-network] DNS should provide DNS for the cluster [Conformance]
    [sig-network] DNS should provide DNS for services [Conformance]

**Since when has it been failing**:

Since this PR merged: https://github.com/kubernetes/kubernetes/pull/75243

**Testgrid link**:

    https://testgrid.k8s.io/sig-windows#flannel-overlay-windows-master

**Reason for failure**:

The mentioned PR replaces the usage of ``hostname -i`` with ``getent hosts``, command which has issues on Windows, especially since the ``hosts`` file is not managed by Kubernetes.

**Anything else we need to know**:

/sig testing
/sig windows
/area conformance

**Comment by aojea** [comment]
@bclau a little help here :sweat_smile: , how can I test this to come up with a fix?
I can't see how is the output of getent in windows

**Comment by bclau** [comment]
> 
> 
> @bclau a little help here sweat_smile , how can I test this to come up with a fix?
> I can't see how is the output of getent in windows

Yeah, so, ``getent hosts`` basically outputs things from the ``/etc/hosts`` file (or on Windows, ``C:/Windows/System32/drivers/etc/hosts``). From what I see in the Windows containers, every single line in the ``hosts`` file is commented. Keep in mind that that file is not managed by Kubelet because we cannot mount individual files in Windows containers at the moment (that's how it's done on Linux), until the ContainerD work is done for Windows as well.

I couldn't find a platform-agnostic command that could work on both OSes and for both IPv4 and IPv6 as you'd like. I was instead thinking of adding a subcommand to the ``agnhost`` binary that would output the required IPv4 / IPv6 (see last posts in the conversation here: https://github.com/kubernetes/kubernetes/issues/76342). Nonetheless, I think IPv6 should be tested explicitly in another tests (I'm not sure it would be considered ``[Conformance]`` from the start, if memory serves, other IPv6 tests are considered experimental), especially since we don't really support IPv6 at this point on Windows.

Thoughts, @PatrickLang , @spiffxp ?

**Comment by aojea** [comment]
@bclau one way to solve this is using the new feature added to e2e tests with https://github.com/kubernetes/kubernetes/pull/80398 to autodetect the IP family of the cluster.

That will imply reverting https://github.com/kubernetes/kubernetes/pull/75243 and rewriting the DNS tests leveraging that new functionality.
