### ISSUE TITLE
EmptyDir disk usage reports the whole file system used bytes for windows

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#81088]
For emptyDir volume, it uses metricsDu package to report the disk used bytes. However, the fs utility used by metricsDu reports the whole file system usage instead of the specific dir usage for windows https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/fs/fs_windows.go.

Due to this wrong information, set a sizeLimit for emptyDir will trigger an eviction action wrongly.

**Comment by jingxu97** [comment]
cc @yujuhong @andyzhangx

**Comment by yujuhong** [comment]
@kubernetes/sig-windows-bugs 
@PatrickLang @benmoss is this a known issue/limitation?

**Comment by benmoss** [comment]
I wasn't aware of this, we should definitely look at fixing this

**Comment by PatrickLang** [comment]
resolved in https://github.com/kubernetes/kubernetes/pull/81437
/close
