### ISSUE TITLE
Preseed --conntrack-max-per-core 0 on kubeadm init/join

### ISSUE THREAD

**Issue by hanoisteve** [kubernetes/kubernetes#81090]
**What would you like to be added**:
kube-proxy doesn't start inside a container, because it is unallowed to change conntrack hashsize. there is a workaround in adding `--conntrack-max-per-core 0` to it's command line parameters, but all solutions that I found are like "start the cluster, wait kube-proxy to crash, edit it's daemon set and delete it's pod". All I want is to have it that parameter from start, without having to manually edit anything after init
**Why is this needed**:
I need to pass the infamous --conntrack-max-per-core 0 to it, to be able start in LXD container. usually have to wait for crash before this can be done.

**Comment by neolit123** [comment]
/remove-sig node
/area kubeadm
/sig cluster-lifecycle

hi, kubeadm currently does not allow customizing the kube-proxy DaemonSet and it's template Pod spec:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L79-L81

we have a tracking issue to support such kustomizations, but the first phase of this support (that will happen in 1.16) will only be for the control-plane static pods and not for addons such as kube-proxy:
https://github.com/kubernetes/kubeadm/issues/1379
the case of addon kustomizations is not yet clear.

> but all solutions that I found are like "start the cluster, wait kube-proxy to crash, edit it's daemon set and delete it's pod"

this is actually a viable solution for now and some users are already doing it, even outside of the LXD case.

/close
