### ISSUE TITLE
Volume controller detach behavior

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#81097]
**What happened**:
Does volume controller handles the situation where controller manager restart during a failed detach call? 

The code here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L206 - understandably - updates the node `attached volumes` before it actually performs the detach.
 
**What you expected to happen**:
The reconciler should retry detach after a restart.

**How to reproduce it (as minimally and precisely as possible)**:
perform a failed detach and restart CM as the call is in flight

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `head`

@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
cc @jingxu97

**Comment by gnufied** [comment]
That is the main reason we introduced - dangling volume errors (https://github.com/kubernetes/kubernetes/issues/80488) . It is currently implemented only for EBS and Cinder but even if controller-manager was restarted during a detach and detach failed and next time some other pod tried to use same volume then plugin will throw `DanglingAttachError` which will cause the volume to be marked as attached to that node and if no pod is using the volume on that node, it will be detached.

cc @leakingtapan

**Comment by gnufied** [comment]
This also applies to controller-manager crash before attach could finish but attach was started. In that case - the volume state may not be recorded in the node and hence even though volume is attached to a node, it may not be detached.

**Comment by gnufied** [comment]
Since this is not a generic problem with controller-manager and a fix is in works for Azure, I am going to close this issue.

/close

**Comment by andyzhangx** [comment]
this issue is fixed by https://github.com/kubernetes/kubernetes/pull/81266 on Azure, @khenidak
