### ISSUE TITLE
examples for RC with PodTemplate ref

### ISSUE THREAD

**Issue by kazegusuri** [kubernetes/kubernetes#8109]
PodTemplate is now available as a resource type, and [it seems to be able to use in RC](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L895-L896). But there are no examples, and [Template is validated as required field](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L1097). Still need more work?

**Comment by nikhiljindal** [comment]
@smarterclayton @bgrant0607

**Comment by bgrant0607** [comment]
Yes, it needs more work. It isn't fully implemented. We either should finish it, or remove the field from the API for now.

**Comment by smarterclayton** [comment]
It's not terrible to implement.  What's the cutoff date in your mind brian to implement it?

**Comment by bgrant0607** [comment]
End of May.

If we missed that, we'd just remove ReplicationControllerSpec.TemplateRef, and add it back later with the full implementation.

**Comment by bgrant0607** [comment]
@caesarxuchao Please remove ReplicationControllerSpec.TemplateRef from the v1 API for now.
