### ISSUE TITLE
EKS delete pv hung on `Terminating`

### ISSUE THREAD

**Issue by nodesocket** [kubernetes/kubernetes#81101]
Running on Amazon EKS. I created a few services using Helm which create persistent volumes.

When I run `helm delete` it does not delete the persistent volumes. So, I tried manually removing them using:

```
kubectl delete pv pvc-08e65270-b7ce-11e9-ba0b-0a1e280502e2
```

The command shows `persistentvolume "pvc-08e65270-b7ce-11e9-ba0b-0a1e280502e2" deleted`, but the delete command does not exist, it just hangs. So, I CONTROL+C and ran:

```
kubectl get pv
```

And it shows the persistent volume in a `Terminating` state. It has been over an hour and half and still showing the persistent volumes in `Terminating`.

Running:

```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:37:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nodesocket** [comment]
After running the following command, the persistent volume successfully deleted.

```
kubectl patch pv pvc-08e65270-b7ce-11e9-ba0b-0a1e280502e2 -p '{"metadata":{"finalizers":null}}'
````

Is there a way to prevent having to manually run that command every time I want to delete a pv?

**Comment by tomerleib** [comment]
Facing the same issue

**Comment by spence95** [comment]
I'm still getting this issue

**Comment by alkoclick** [comment]
For anyone arriving here like me who had this issue, check that your PV does not have any [protection finalizers](https://stackoverflow.com/questions/51358856/kubernetes-cant-delete-persistentvolumeclaim-pvc/53305538). If it does, you should delete them. In my case, the PV immediately got deleted after clearing them.
