### ISSUE TITLE
pods/exec should not be a "get"

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#8112]
"pods/exec" should not use a "get" verb, it should use a "post".  That would more effectively communicate what it's doing (I'm creating an exec on a pod) and it eliminates weirdness with policy granting permission to perform "readonly" operations allowing "pods/exec"

**Comment by smarterclayton** [comment]
@ncdc may know if we *can't* use POST, but the initial problems we considered were that some proxies may not be able to handle HTTP connection upgrade for non GET requests.  According to the HTTP spec upgrade is in theory allowed on any method, but it's likely proxy implementors may have made mistakes.

We should test with HAProxy and other connection-upgrade aware proxies and verify we can POST.

**Comment by deads2k** [comment]
cc @csrwng

**Comment by smarterclayton** [comment]
If we don't support GET we can't use web sockets to connect to exec from a browser.  Therefore we must support exec over GET.

**Comment by smarterclayton** [comment]
See https://github.com/kubernetes/kubernetes/pull/13885 for more.
