### ISSUE TITLE
TOB-K8S-025: Incorrect docker daemon process name in container manager

### ISSUE THREAD

**Issue by cji** [kubernetes/kubernetes#81139]
This issue was reported in the [Kubernetes Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Description**
The container manager used in kubelet checks for docker daemon process either via pidfile or process name. While the pidfile points to the docker daemon process PID, the dockerProcessName constant stores a docker cli name (docker) instead of docker daemon name (dockerd).

```
const (
      // (...)
	dockerProcessName     = "docker"
	dockerPidFile         = "/var/run/docker.pid"
      // (...)
)
```
Figure 30.1: Constants in pkg/kubelet/cm/container_manager_linux.go file.

**Recommendation**
Correct the docker process name to dockerd.

**Anything else we need to know?**:

See #81146 for current status of all issues created from these findings.

The vendor gave this issue an ID of TOB-K8S-025 and it was finding 31 of the report.

The vendor considers this issue Informational Severity.

To view the original finding, begin on page 77 of the [Kubernetes Security Review Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Environment**:

- Kubernetes version: 1.13.4

**Comment by sjenning** [comment]
lol, this is the issue. my bad!
