### ISSUE TITLE
REST api - plural form for endpoint entity kind

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#8115]
This is inconsistent with other entities which use a singular form for the kind field.
Please see here:
https://github.com/abonas/kubeclient/issues/81

Can this be fixed on server side so all clients won't have to do special case handling?

**Comment by thockin** [comment]
Yes, Endpoints objects are a set of individual IP endpoints.  It's perhaps
an unfortunate name in the hidden double-pluralness - technically the REST
path should be "endpointses" I guess, but I don't think we're going to do
that.

I'd MAYBE be open to a better name, but that is a post-1.0 change, at
earliest.

As for defining endpoints for external services, we toyed with embedding an
Endpoints into Service as an alternative to Selector, but we just ran out
of time to explore it further before 1.0

**Comment by bgrant0607** [comment]
Superseded by #18622.

The discovery API will make it unnecessary for clients to special-case Endpoints.

cc @kubernetes/sig-api-machinery

**Comment by cben** [comment]
For anyone else looking, in kubernetes as of 1.12, `Endpoints` remains the only API resource with plural kind.
https://github.com/cben/kubernetes-discovery-samples/blob/master/kubernetes-v1.12.0/api/v1/index.json#L50

In openshift, as of 3.11, there is one more: `SecurityContextConstraints`.
https://github.com/cben/kubernetes-discovery-samples/blob/master/openshift-origin-v3.11.0/api/v1/index.json#L440
https://github.com/cben/kubernetes-discovery-samples/blob/master/openshift-origin-v3.11.0/apis/security.openshift.io/v1/index.json#L53

(Easy way to search: `git grep --only-matching -h '"kind": "[^"]*s"' | sort -u`.
The swagger types also include many plural kinds like `DeleteOptions` used inside other types, and kinds like `APIVersions` used in discovery results.)
