### ISSUE TITLE
pull-kubernetes-e2e-gce-csi-serial Flaky

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#81181]
**Which jobs are failing**:
pull-kubernetes-e2e-gce-csi-serial

**Which test(s) are failing**:
TearDown
Timeout

**Since when has it been failing**:
I've seen failures over the past few days (6Aug or so)

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80247/pull-kubernetes-e2e-gce-csi-serial/1159435482896011265
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80492/pull-kubernetes-e2e-gce-csi-serial/1159199301683908609
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81087/pull-kubernetes-e2e-gce-csi-serial/1159199050960998401

**Reason for failure**:
No tests seem to fail but failure reported due to non-zero exit status:
```
I0807 22:28:22.976] Ran 45 of 4296 Specs in 4810.732 seconds
I0807 22:28:22.977] FAIL! -- 45 Passed | 0 Failed | 0 Flaked | 0 Pending | 4251 Skipped
I0807 22:28:22.994] 
I0807 22:28:22.995] Ginkgo ran 1 suite in 1h20m12.988984559s
I0807 22:28:22.998] Test Suite Failed
I0807 22:28:23.008] Checking for custom logdump instances, if any
I0807 22:28:23.020] Sourcing kube-util.sh
I0807 22:28:23.091] Detecting project
I0807 22:28:23.092] Project: k8s-gce-ingress1-5
I0807 22:28:23.092] Network Project: k8s-gce-ingress1-5
I0807 22:28:23.092] Zone: us-west1-b
I0807 22:28:23.092] Dumping logs from master locally to '/workspace/_artifacts'
W0807 22:28:23.193] !!! Error in ./hack/ginkgo-e2e.sh:146
W0807 22:28:23.194]   Error in ./hack/ginkgo-e2e.sh:146. '"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- "${auth_config[@]:+${auth_config[@]}}" --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" --host="${KUBE_MASTER_URL}" --provider="${KUBERNETES_PROVIDER}" --gce-project="${PROJECT:-}" --gce-zone="${ZONE:-}" --gce-region="${REGION:-}" --gce-multizone="${MULTIZONE:-false}" --gke-cluster="${CLUSTER_NAME:-}" --kube-master="${KUBE_MASTER:-}" --cluster-tag="${CLUSTER_ID:-}" --cloud-config-file="${CLOUD_CONFIG:-}" --repo-root="${KUBE_ROOT}" --node-instance-group="${NODE_INSTANCE_GROUP:-}" --prefix="${KUBE_GCE_INSTANCE_PREFIX:-e2e}" --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" --node-tag="${NODE_TAG:-}" --master-tag="${MASTER_TAG:-}" --cluster-monitoring-mode="${KUBE_ENABLE_CLUSTER_MONITORING:-standalone}" --prometheus-monitoring="${KUBE_ENABLE_PROMETHEUS_MONITORING:-false}" --dns-domain="${KUBE_DNS_DOMAIN:-cluster.local}" --ginkgo.slowSpecThreshold="${GINKGO_SLOW_SPEC_THRESHOLD:-300}" ${KUBE_CONTAINER_RUNTIME:+"--container-runtime=${KUBE_CONTAINER_RUNTIME}"} ${MASTER_OS_DISTRIBUTION:+"--master-os-distro=${MASTER_OS_DISTRIBUTION}"} ${NODE_OS_DISTRIBUTION:+"--node-os-distro=${NODE_OS_DISTRIBUTION}"} ${NUM_NODES:+"--num-nodes=${NUM_NODES}"} ${E2E_REPORT_DIR:+"--report-dir=${E2E_REPORT_DIR}"} ${E2E_REPORT_PREFIX:+"--report-prefix=${E2E_REPORT_PREFIX}"} "${@:-}"' exited with status 1
W0807 22:28:23.194] Call stack:
W0807 22:28:23.194]   1: ./hack/ginkgo-e2e.sh:146 main(...)
W0807 22:28:23.194] Exiting with status 1
W0807 22:28:23.195] 2019/08/07 22:28:23 process.go:155: Step './hack/ginkgo-e2e.sh --ginkgo.focus=CSI.*(\[Serial\]|\[Disruptive\]) --ginkgo.skip=\[Flaky\]|\[Feature:.+\]|gcePD-external --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true' finished in 1h20m14.251820126s
```

**Anything else we need to know**:
Multiple PRs with completely different types of changes. Seemed to be either a transient issue or something with the actual test-infra code. However, the job history didnt show _all_ red so I assume transient? If it was something misconfigured I would expect a more consistent failure.

**Comment by alejandrox1** [comment]
for reference https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-e2e-gce-csi-serial
This seems to still be happening.
/milestone v1.17
/priority critical-urgent

**Comment by alejandrox1** [comment]
/cc @kubernetes/sig-storage-test-failures 
ptal

**Comment by alejandrox1** [comment]
forgot one thing
/sig-remove testing

**Comment by msau42** [comment]
I looked at one of the recent failing tests, and they all seem to failing with:
```
manifest for gcr.io/kubernetes-e2e-test-images/agnhost:2.7 not found
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81226/pull-kubernetes-e2e-gce-csi-serial/1174720142538444800

**Comment by msau42** [comment]
I'm not even sure where it's getting this image from, because the tests are supposed to be using busybox: https://github.com/kubernetes/kubernetes/blob/74c0cc27902548243d8a863c9e2c6345a8e6b548/test/e2e/storage/testsuites/subpath.go#L499

**Comment by msau42** [comment]
Ok I think the subpath tests are invoking a host exec pod, which is where agnhost is used.  However, the agnhost version configured in e2e is 2.5, but the test is trying to pull 2.7:
https://github.com/kubernetes/kubernetes/blob/07e0cce409efd8f8d6d49ea66c23464ba630d224//test/utils/image/manifest.go#L207

**Comment by msau42** [comment]
The answer is because the PR is actually trying to change it:
https://github.com/kubernetes/kubernetes/pull/81226/files

Sorry, I'm not going to spend anymore time debugging pull job failures unless there appears to be some systematic problem that's unrelated. These same test cases are run in CI serial, and if there were problems with the tests, then they would be showing up in CI too.

/close
