### ISSUE TITLE
Enhance Logs around unauthenticated proxy users

### ISSUE THREAD

**Issue by distortedsignal** [kubernetes/kubernetes#81188]
**What would you like to be added**:
I'm writing an authenticating proxy for Kubernetes, and I feel like the logs could be enhanced to make the reasons behind user refusal more clear.

Local client (this gets repeated a few times, because of retries, repeat symbolized by '...'):
```
> kubectl get pods -v=10
I0808 13:05:24.108781   48567 loader.go:359] Config loaded from file:  /Users/tom/.kube/config
I0808 13:05:24.109672   48567 round_trippers.go:419] curl -k -v -XGET  -H "User-Agent: kubectl/v1.15.0 (darwin/amd64) kubernetes/e8462b5" -H "Accept: application/json, */*" 'https://proxy_host:9500/api?timeout=32s'
I0808 13:05:24.809746   48567 round_trippers.go:438] GET https://proxy_host:9500/api?timeout=32s 401 Unauthorized in 700 milliseconds
I0808 13:05:24.809782   48567 round_trippers.go:444] Response Headers:
I0808 13:05:24.809788   48567 round_trippers.go:447]     Content-Length: 129
I0808 13:05:24.809791   48567 round_trippers.go:447]     Content-Type: application/json
I0808 13:05:24.809795   48567 round_trippers.go:447]     Date: Thu, 08 Aug 2019 20:05:24 GMT
I0808 13:05:24.828139   48567 request.go:947] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
...
I0808 13:05:25.855247   48567 cached_discovery.go:121] skipped caching discovery info due to Unauthorized
I0808 13:05:25.855433   48567 helpers.go:199] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}]
F0808 13:05:25.855453   48567 helpers.go:114] error: You must be logged in to the server (Unauthorized)
```

What I see in the kube-apiserver when tailing the logs with a local version of kubectl (logs again redacted for length, replaced with ellipsis):
```
> kubectl logs --namespace=kube-system kube-apiserver --tail=10 -f -v=10
(log redacted for length)
E0808 20:02:33.360389       1 authentication.go:65] Unable to authenticate the request due to an error: [x509: subject with cn=front-proxy-client is not in the allowed list, x509: certificate signed by unknown authority]
...
```

(On further inspection, it looks like this log message is inconsequential. It even happens when authentication succeeds.)

This request got rejected, and the logs suggest that this is because of a certificate issue. However, the only thing that changes between this (failing) request and a future (successful) request is adding a header to the proxy's request to the server that specifies the user. So, for instance, where the first (failing) request had this list of headers:

```
[{"Accept","application/json, */*"},
 {"Accept-Encoding","gzip"},
 {"User-Agent","kubectl/v1.15.0 (darwin/amd64) kubernetes/e8462b5"},
 {"X-Remote-Group","system:masters"}
]
```

a successful request would have these headers:

```
[{"Accept","application/json, */*"},
 {"Accept-Encoding","gzip"},
 {"User-Agent","kubectl/v1.15.0 (darwin/amd64) kubernetes/e8462b5"},
 {"X-Remote-User","admin"}, # Note the addition of this header
 {"X-Remote-Group","system:masters"}
]
```

**Why is this needed**:

I wasted a week of my life not understanding why this wasn't working. Don't make other people do the same.

**Comment by distortedsignal** [comment]
@kuberentes/sig-auth-feature-requests

**Comment by distortedsignal** [comment]
Boop.

**Comment by distortedsignal** [comment]
What evidence would you like to see, @liggitt ? I gave both a successful request and a failing request, and showed that logs are not enough to distinguish this problem.

**Comment by liggitt** [comment]
logging the *absence* of a header that an authenticating proxy should set would pollute the logs for all requests not made via the proxy (the check for the header gates all subsequent auth proxy logic)
