### ISSUE TITLE
[Failing Test] ci-kubernetes-e2e-gci-gce-serial is timing out

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#81197]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial 

**Which test(s) are failing**:
Job is timing out.

**Since when has it been failing**:
The timeouts started around 8/6 at 13:00 PDT
k/k diff for context https://github.com/kubernetes/kubernetes/compare/16d9a659d...6049253aa

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:
These are the args passed to kubetest
```
Args: --job=ci-kubernetes-e2e-gci-gce-serial --service-account=/etc/service-account/service-account.json --upload=gs://kubernetes-jenkins/logs --timeout=520 --bare --scenario=kubernetes_e2e -- --check-leaked-resources --env=NODE_LOCAL_SSDS_EXT=1,scsi,fs --extract=ci/latest --gcp-master-image=gci --gcp-node-image=gci --gcp-zone=us-west1-b --provider=gce '--test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8' --timeout=500m
```

There is a timeout of 500m (~8 hours).
The latest runs have latest 8+ hours https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1159223580651687936

Everything else seems ok, all tests passed, https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1159223580651687936#0:build-log.txt%3A45205

/milestone v1.16
/priority critical-urgent
/kind failing-test
/sig sig-storage
/cc @kubernetes/sig-storage-test-failures
/cc @Verolop @jimangel @soggiest @alenkacz

**Comment by davidz627** [comment]
Looks like some sort of test teardown failure? @krzyzacy

**Comment by alejandrox1** [comment]
Forgot to mention... I ping sig-storage because it seems that the timeouts started with changes to csi e2e tests but not sure if that is a problem or the timeouts just need to be increased.
/cc @kubernetes/sig-storage-test-failures

**Comment by alejandrox1** [comment]
Forgot to mention... I ping sig-storage because it seems that the timeouts started with changes to csi e2e tests but not sure if that is a problem or the timeouts just need to be increased.

/sig sig-testing

**Comment by lachie83** [comment]
I pinged @krzyzacy in the testing-ops channel today to see if we can get this issue triaged.

**Comment by msau42** [comment]
> the timeouts started with changes to csi e2e tests

@alejandrox1 can you point to which PRs you are referring to?

**Comment by bertinatto** [comment]
Looking at the diff https://github.com/kubernetes/kubernetes/compare/16d9a659d...6049253aa, seems like this is the PR @alejandrox1 is talking about:

https://github.com/kubernetes/kubernetes/pull/75071

**Comment by alejandrox1** [comment]
Yes, I was looking at what @bertinatto mentioned.

I was checking more of these runs, https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1160911612807221248#0:build-log.txt%3A44652 ,
and other than some flakes it really is just a timeout. 

The big question is whether the timeout is due to the number of tests being run (all of them are being run serially) or whether anything in https://github.com/kubernetes/kubernetes/compare/16d9a659d...6049253aa caused one or more tests to take longer than normal @msau42

**Comment by msau42** [comment]
When I initially created this (optional) pull job, tests took around 3-4 hrs.  8 is definitely not reasonable for a pull job. We should investigate which tests are taking a long time, and also see if we can trim test cases from the pull job. It's only meant to be a quick sanity check of basic CSI functional, not a comprehensive test suite (that's what the periodic jobs are for)

**Comment by msau42** [comment]
Sorry, ignore my last comment. I thought this was referring to the pull-csi-storage-serial job.

**Comment by msau42** [comment]
Looking at the run referenced above, I see the longest test cases are:
```
[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] Deployment Should scale from 5 pods to 3 pods and from 3 to 1	12m39s

[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicaSet Should scale from 5 pods to 3 pods and from 3 to 1	12m52s

[k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node	24m12s

[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 5 pods to 3 pods and from 3 to 1 and verify decision stability	22m43s

```

**Comment by msau42** [comment]
Since the majority of test cases are sig-storage, would it help the serial run if we broke up the serial job into multiple jobs? 

I can at least see the following splits:
* all non sig-storage tests + sig storage tests not part of the storage test framework
* csi storage framework tests
* in-tree storage framework tests

The problem is this split has to be propagated to all other cluster configs too (like multi-zone clusters, upgrade/downgrade tests, etc)

**Comment by msau42** [comment]
Longer term, I want to look into reducing the number of permutations of test cases.  For example, most test cases don't need to test all permutations of "dynamic pvs, preprovisioned pvs, and inline volumes".  Testing dynamic pvs is usually sufficient, and preprovisioned and inline volumes wouldn't make a difference to the test case.  But we'll need to think about this on a case by case basis, and also figure out how to conditionally skip certain permutations since some drivers don't support dynamic provisioning.

**Comment by msau42** [comment]
> reducing the number of permutations of test cases

PR to reduce number of test permutations here https://github.com/kubernetes/kubernetes/pull/81375

**Comment by msau42** [comment]
Looks like we're under the 8hrs now that https://github.com/kubernetes/kubernetes/pull/81375 has merged

**Comment by dims** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial is consistently green, @alejandrox1 can we close this now?

**Comment by alejandrox1** [comment]
Ah sorry for the delay.
This has indeed been resolved.
/close
