### ISSUE TITLE
Conformance Tests for CRDs

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#81192]
- [x] write e2e tests for all CRD operations 
  - [x] https://github.com/kubernetes/kubernetes/pull/81240
  - [x] https://github.com/kubernetes/kubernetes/pull/82036 - discovery
  - 5 Untested beta Operations:
        - list ApiextensionsV1beta1 CustomResourceDefinition
        - deletecollection ApiextensionsV1beta1 CustomResourceDefinition
        - replace ApiextensionsV1beta1 CustomResourceDefinitionStatus
        - patch ApiextensionsV1beta1 CustomResourceDefinitionStatus
        - read ApiextensionsV1beta1 CustomResourceDefinitionStatus
    - [apisnoop beta coverage](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-beta-apiextensions)
- [x] switch to v1 CRD APIs
    - [x] https://github.com/kubernetes/kubernetes/pull/81497
    - [x] https://github.com/kubernetes/kubernetes/pull/81684
    - [apisnoop stable coverage](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-stable-apiextensions)
- [x] remove skips/time.Sleeps - https://github.com/kubernetes/kubernetes/pull/81684
- [x] [monitor for flakes](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=CustomResource&show-stale-tests=&width=5) and promote to conformance tests - https://github.com/kubernetes/kubernetes/pull/81864
- [x] [monitor https://github.com/kubernetes/kubernetes/pull/82036 for flakes](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&width=20&sort-by-flakiness=&include-filter-by-regex=&include-filter-by-regex=CustomResource.*discovery) and promote to conformance - https://github.com/kubernetes/kubernetes/pull/82198

![crd-conformance-apisnoop](https://user-images.githubusercontent.com/523590/62738079-46072200-b9e6-11e9-8afb-3fa4d13601e8.png)

[apisnoop for CRDs](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-beta-apiextensions) / [test grid](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=CustomResource&show-stale-tests=&width=5)

/cc @liggitt @sttts @roycaihw @caesarxuchao @hh 
/sig api-machinery
/area conformance
/area custom-resources
/kind feature

**Comment by liggitt** [comment]
still in progress

**Comment by jpbetz** [comment]
https://github.com/kubernetes/kubernetes/pull/81864 is ready for review. It adds our CRD e2e tests to conformance as part of graduation to GA.

**Comment by liggitt** [comment]
reopening until the discovery API e2e is merged and promoted

**Comment by liggitt** [comment]
discovery PR is merged

can observe run history at https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&width=20&sort-by-flakiness=&include-filter-by-regex=&include-filter-by-regex=CustomResource.*discovery

PR to promote is at https://github.com/kubernetes/kubernetes/pull/82198

**Comment by liggitt** [comment]
All endpoints and operations are now covered by conformance tests

/close
