### ISSUE TITLE
Job controller should remember number of completion

### ISSUE THREAD

**Issue by yuha0** [kubernetes/kubernetes#81227]
**What happened**:
When a `Completed` pod is deleted, `Job` controller decreases the number of completions and schedule new pods.

```
kubectl get job backfill --watch
NAME          COMPLETIONS   DURATION   AGE
backfill   30/36         41h        41h
backfill   29/36         41h        41h
backfill   28/36         41h        41h
backfill   27/36         41h        41h
backfill   26/36         41h        41h
backfill   27/36         41h        41h
backfill   28/36         41h        41h
backfill   29/36         41h        41h
backfill   30/36         41h        41h
backfill   31/36         41h        41h
backfill   32/36         41h        41h
```

**What you expected to happen**:
Completed is completed for good. Logically speaking, a completed task cannot be "uncompleted". 
So, when a `Completed` pod is deleted, `Job` controller should not decrease the number of completions.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a batchjob with `.spec.completions=X`.
2. When there are Y pods reaches `Completed` phase, you should see `Y/X` in `COMPLETIONS` column when you `kubectl get job`
3. Manually delete some completed pods
4. You should now see number of completions decreases and new pods will be scheduled.

**Anything else we need to know?**:
In our environment, we have a cluster autoscaler that kills idling nodes. When the node is terminated, all the `Completed` pods on it will be gone. That's when I notice this behavior.
I looked into the Job controller's code and it seems like the controller is stateless and is completely rely on the result of listing pods to determine the status of the job.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.8
- Cloud provider or hardware configuration: AWS

**Comment by hainesc** [comment]
Hi @kharunsamuel1 how is the process going?

**Comment by hainesc** [comment]
/remove-lifecycle stale

Please do not close this until #83105 merged or closed.

**Comment by soltysh** [comment]
This is duplicate of https://github.com/kubernetes/kubernetes/issues/28486
/close
