### ISSUE TITLE
How to distinguish flows in K8s world

### ISSUE THREAD

**Issue by FOSquare** [kubernetes/kubernetes#81222]
i run one media-streaming applicaiton in K8s, but when I use tcpflow i find hundreds of flow. The usual way by distinguishing the 5 tuple (ethernet type, Source & destination IP, source and destination port) do not work any more. 

Then how can I distinguish the flows from K8s efficiently？ Thanks a lot.

**Comment by zouyee** [comment]
`kubectl krew install sniff`
