### ISSUE TITLE
TestPreemptWithPermitPlugin flakes

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#81238]
**Which jobs are failing**:

pull-kubernetes-integration

**Which test(s) are failing**:

TestPreemptWithPermitPlugin

**Since when has it been failing**:

13:30 PST, Sep 9, 2019

**Testgrid link**:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81229/pull-kubernetes-integration/1159912162789953536/
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81068/pull-kubernetes-integration/1159945886181101569/

**Reason for failure**:

Need investigations.

**Anything else we need to know**:

/sig scheduling

**Comment by draveness** [comment]
Another flaky [here](https://github.com/kubernetes/kubernetes/pull/81006#pullrequestreview-271138457) https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81006/pull-kubernetes-integration/1158614573872320512/ 

```go
--- FAIL: TestPreemptWithPermitPlugin (64.95s)
    framework_test.go:1618: Expected the preemptor pod to be scheduled. error: timed out waiting for the condition
    framework_test.go:1622: Expected the waiting pod to get preempted and deleted
```

**Comment by tedyu** [comment]
```
Sep 9, 2019
```
I think you meant Aug 9, 2019

**Comment by tedyu** [comment]
```
I0810 03:03:26.425702  110762 factory.go:557] Unable to schedule preempt-with-permit-plugin8c137daf-8329-4b96-9319-9fbe8fa8ae1f/preemptor-pod: no fit: 0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory.; waiting
```
The above repeated for 30 seconds.

**Comment by hex108** [comment]
I checked the code and log again. I think the reason is as following:

When scheduler preempted `waiting-pod`, it failed to delete the pod(same as the case for `signaling-pod`, there might be something wrong with etcd), so it could not schedule `preemptor-pod` because `waiting-pod` had not been deleted successfully.

**Comment by hex108** [comment]
/assign

Find the root cause now, will send a PR soon.

**Comment by hex108** [comment]
@tedyu Thanks for your work! Not sure whether you are still investigating it, the flaky test is impacting many PRs now, so I send a PR for it now, sorry for it.
