### ISSUE TITLE
Make sub e2e framework independent as possible

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#81232]
**What happened**:

To provide necessary e2e functionality for consumers instead of a single giant e2e framework, we are separating core e2e framework (`test/e2e/framework`) into sub e2e frameworks(e.g. `test/e2e/framework/auth`).
Now sub e2e frameworks have multiple dependencies and sometime we are facing circular dependency issues.
So it is better to make sub framework independent as possible for avoiding such issues again.

**NOTE related to import dependency**:

It is fine that sub framework packages (e.g. `test/e2e/framework/auth`) can import core framework(`test/e2e/framework`).
And opposite import(e.g. `test/e2e/framework` imports `test/e2e/framework/auth`) is invalid.

Ref: https://github.com/kubernetes/kubernetes/issues/81245

**Sub e2e frameworks we need to investigate**:
- [x] test/e2e/framework/auth (This imports are simple and doesn't depend on any k/k code)
- [x] test/e2e/framework/config (This imports are simple and doesn't depend on any k/k code)
- [ ] test/e2e/framework/deployment (https://github.com/kubernetes/kubernetes/pull/81231, still e2elog and other k/k)
- [ ] test/e2e/framework/deviceplugin (https://github.com/kubernetes/kubernetes/pull/81393 depending on k8s.io/kubernetes/test/e2e/framework/testfiles)
- [ ] test/e2e/framework/endpoints (https://github.com/kubernetes/kubernetes/pull/81235 still e2elog)
- [x] test/e2e/framework/ginkgowrapper (This imports are simple and doesn't depend on any k/k code)
- [x] test/e2e/framework/gpu (https://github.com/kubernetes/kubernetes/pull/81391)
- [ ] test/e2e/framework/ingress (e2elog, e2enode, e2eservice and e2etestfiles, a lot of dependencies to k/k)
- [ ] test/e2e/framework/job (depending on e2elog, core e2e framework of k/k)
- [ ] test/e2e/framework/kubelet (depending on e2elog and e2enode)
- [ ] test/e2e/framework/lifecycle (depending on core e2e framework and e2elog)
- [ ] test/e2e/framework/log (depending on ginkgowrapper e2e framework)
- [ ] test/e2e/framework/metrics (depending on e2elog , e2eperftype, e2essh, k/k(kubelet_metrics.go, latencies.go, metrics_grabber))
- [ ] test/e2e/framework/node (https://github.com/kubernetes/kubernetes/pull/81389 depending on a lot of k/k)
- [ ] test/e2e/framework/perf (depending on e2ekubelet, e2elog, e2emetrics and k/k perftype)
- [ ] test/e2e/framework/pod (depending on e2elog, e2eresource and k/k conditions, kubepod, testutils, podutil and imageutils)
- [x] test/e2e/framework/podlogs (This imports are simple and doesn't depend on any k/k code)
- [ ] test/e2e/framework/providers
- [x] test/e2e/framework/psp (This is core framework, not sub framework)
- [ ] test/e2e/framework/replicaset (depending on e2elog, core, k/k: testutils, deploymentutil)
- [ ] test/e2e/framework/resource (depending on k/k)
- [ ] test/e2e/framework/service (depending on core, e2elog, e2epod, e2essh and k/k imageutils)
- [ ] test/e2e/framework/ssh (depending on e2elog, k/k: sshutil )
- [ ] test/e2e/framework/statefulset (https://github.com/kubernetes/kubernetes/pull/81478 still e2elog, framework and other k/k)
- [x] test/e2e/framework/testfiles  (This imports are simple and doesn't depend on any k/k code)
- [ ] test/e2e/framework/timer
- [x] test/e2e/framework/viperconfig (This imports are simple and doesn't depend on any k/k code)
- [ ] test/e2e/framework/volume

**Comment by spiffxp** [comment]
@oomichi is this still relevant? I don't have the bandwidth to shepherd this as help-wanted and am considering /remove-help
