### ISSUE TITLE
Core e2e test framework should not import sub e2e test frameworks

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#81245]
**What happened**:

As https://kubernetes.slack.com/archives/C9NK9KFFW/p1565372337078100 Core e2e test framework(`test/e2e/framework`) should not import sub e2e test frameworks (e.g. `test/e2e/framework/auth`) for avoiding circular dependency.
This issue is for managing such issues.

The following files are in e2e core framework:
- [x] cleanup.go (no dependency to sub packages)
- [x] exec_util.go (no dependency to sub packages)
- [x] expect.go (no dependency to sub packages)
- [x] flake_reporting_util.go (no dependency to sub packages)
- [ ] framework.go (https://github.com/kubernetes/kubernetes/pull/86679 is a part, but still we should have more PRs)
- [x] get-kubemark-resource-usage.go
- [x] google_compute.go (no dependency to sub packages)
- [ ] log.go
- [ ] log_size_monitoring.go
- [ ] nodes_util.go
- [ ] pods.go
- [x] profile_gatherer.go (https://github.com/kubernetes/kubernetes/pull/85304)
- [x] provider.go (no dependency to sub packages)
- [ ] psp.go
- [x] rc_util.go (no dependency to sub packages)
- [ ] resource_usage_gatherer.go
- [x] size.go (no dependency to sub packages)
- [x] skip.go (https://github.com/kubernetes/kubernetes/pull/87031 and https://github.com/kubernetes/kubernetes/issues/87047)
- [x] suites.go (https://github.com/kubernetes/kubernetes/pull/85235)
- [x] test_context.go (no dependency to sub packages)
- [ ] util.go

**Comment by oomichi** [comment]
Now the core framework imports the following sub frameworks:
```
k8s.io/kubernetes/test/e2e/framework/config: 1
k8s.io/kubernetes/test/e2e/framework/kubelet: 3
k8s.io/kubernetes/test/e2e/framework/log: 20
k8s.io/kubernetes/test/e2e/framework/metrics: 7
k8s.io/kubernetes/test/e2e/framework/node: 3
k8s.io/kubernetes/test/e2e/framework/pod: 9
k8s.io/kubernetes/test/e2e/framework/resource: 1
k8s.io/kubernetes/test/e2e/framework/ssh: 5
k8s.io/kubernetes/test/e2e/framework/auth: 1
k8s.io/kubernetes/test/e2e/framework/ginkgowrapper: 1
k8s.io/kubernetes/test/e2e/framework/testfiles: 1
```

**Comment by alejandrox1** [comment]
We should update https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/.import-restrictions as we do this type of refactoring

**Comment by oomichi** [comment]
> We should update https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/.import-restrictions as we do this type of refactoring

Thanks, that also is a nice idea!

**Comment by ZhiFeng1993** [comment]
@oomichi  my understanding of this issue is to avoid dependence on the sub packages as much as possible, so why did we do this: https://github.com/kubernetes/kubernetes/pull/84613? This PR's upside is to make code structure more modular but at the same time makes this TODO(https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L67) more difficult. Which direction are we moving towards?

**Comment by oomichi** [comment]
@ZhiFeng1993 You are right and that is a nice point.
Works for making sub e2e packages created difficult dependency issues.
After this issues happened, we defined valid dependency way(sub frameworks can import core framework, but the core cannot import subs). 

Now we are solving this issue to move core framework code into e2e test code or sub packages.
But that is really difficult to do that because complex dependencies. it takes time.

**Comment by ZhiFeng1993** [comment]
@oomichi  thanks for the explanation. Today I did some research and I found several issues- most of them are about cycle import. One of them is this:

Based on the previous conversations in this issue, I think we've agreed to put log in the framework core, so that means we need to deprecate the fw/log package. Take `kubectl_utils.go` as an example, e2ekubectl uses e2elog, if we replace it with fw log, then that means e2ekubectl will depend on fw core, which is fine. But the problem is, fw core depends on e2ekubectl. That becomes a cycle import. So my conclusion is that we have to move some e2ekubectl functions back into fw core. Does that make sense to you?

**Comment by oomichi** [comment]
> So my conclusion is that we have to move some e2ekubectl functions back into fw core. Does that make sense to you?

No, please don't do that. That is not a good direction.
The best way is
- move code which depends on e2ekubectl from the core to sub framework
- move code which depends on e2ekubectl from the core to e2e test code

without moving the code back to e2e core to avoid conflict against works like https://github.com/kubernetes/kubernetes/pull/84613

**Comment by ZhiFeng1993** [comment]
> > So my conclusion is that we have to move some e2ekubectl functions back into fw core. Does that make sense to you?
> 
> No, please don't do that. That is not a good direction.
> The best way is
> 
> * move code which depends on e2ekubectl from the core to sub framework
> * move code which depends on e2ekubectl from the core to e2e test code
> 
> without moving the code back to e2e core to avoid conflict against works like #84613

Thanks! That sounds clearer to me. One last question, you've mentioned 'e2e test code' several times, what does that refer to?

**Comment by oomichi** [comment]
> One last question, you've mentioned 'e2e test code' several times, what does that refer to?

That is outside of e2e framework(`test/e2e/framework`) under e2e tests (`test/e2e`, `test/e2e_node` and `test/e2e_kubeadm`).
`test/e2e/apps/daemon_set.go` and `test/e2e/common/kubelet.go` are examples.
Those files contains e2e tests which are implemented with `framework.ConformanceIt()` or `ginkgo.It()`.

**Comment by ZhiFeng1993** [comment]
> > One last question, you've mentioned 'e2e test code' several times, what does that refer to?
> 
> That is outside of e2e framework(`test/e2e/framework`) under e2e tests (`test/e2e`, `test/e2e_node` and `test/e2e_kubeadm`).
> `test/e2e/apps/daemon_set.go` and `test/e2e/common/kubelet.go` are examples.
> Those files contain e2e tests which are implemented with `framework.ConformanceIt()` or `ginkgo.It()`.
 
Thanks a lot for the clarification.

**Comment by alejandrox1** [comment]
Coming back to this issue.
Following the discussion with the rest of sig testing, we should work on defining a design for the e2e framework before proceeding with this - there are some tricky instances in which if we remove subpackage dependencies from the e2e framework we will be removing non-trivial functionality for users.
Have a "design" doc going on in https://docs.google.com/document/d/1ASPcrEC3iSFqD2K2ANaljfLeBZUPxKr-8nrJpRpH9rI/edit?usp=sharing

**Comment by oomichi** [comment]
@alejandrox1 Thanks for sharing that.
OK, I'd like to join the discussion on the above doc.

**Comment by jingxu97** [comment]
I am hitting this issue too. What I need is to import "k8s.io/kubernetes/test/e2e/framework" inside of "k8s.io/kubernetes/test/e2e/framework/pod package to get NodeOSDistroIs information..

**Comment by spiffxp** [comment]
@oomichi is this still relevant? I don't have the bandwidth to shepherd this as help-wanted and am considering /remove-help

**Comment by mauriciopoppe** [comment]
@oomichi @alejandrox1 @spiffxp I've created a doc about moving the test/e2e/framework/pod, any feedback would be appreciated https://docs.google.com/document/d/12QckcyZpBzmgdQZ91h21co4J0rtoXIH76QJBgR1nD6Y/edit#

**Comment by spiffxp** [comment]
> @oomichi @alejandrox1 @spiffxp I've created a doc about moving the test/e2e/framework/pod dependency, any feedback would be appreciated https://docs.google.com/document/d/12QckcyZpBzmgdQZ91h21co4J0rtoXIH76QJBgR1nD6Y/edit#

Will review today

**Comment by spiffxp** [comment]
@mauriciopoppe First, thanks for the well written proposal!

>Glossary:
> - `f/` = `test/e2e/framework/`
> - `f/pod` = `test/e2e/framework/pod`

>Plan:
> - Move all of the functions of `f/pod.go` (PodClient) to `f/pod/` inside another compat module e.g. `e2epodcompat`
> - Move all of the functions of `f/utils.go` to `f/pod/`, this one is easier and can be moved to `f/pod` as it is
> - Refactor the usage of these functions to the new signature `e2epodcompat.Create`, `e2epodcompat.Update`, etc
> - Match `e2epodcompat.Create` with existing methods inside `e2epod`, eventually remove `e2epodcompat`

This sounds reasonable to me.  My concern is potential code/rebase churn this may cause during the runup to code freeze in the next week.
```
# from kubernetes/kubernetes/test
$ rg -l 'PodClient()' | xargs -n1 dirname | sort | uniq -c
   4 e2e/apps
   1 e2e/auth
  13 e2e/common
   1 e2e/common/node
   7 e2e/common/storage
   3 e2e/framework
   1 e2e/framework/network
   1 e2e/framework/security
   1 e2e/instrumentation/logging/utils
   1 e2e/instrumentation/monitoring
   6 e2e/network
   5 e2e/node
   1 e2e/scheduling
   2 e2e/storage
   2 e2e/upgrades
  10 e2e/windows
  32 e2e_node
```
So one suggestion I have is: go with the above plan, but don't land anything that's going to cause a lot of in-flight PR's to need to rebase.  After code freeze, go nuts, but need to complete prior to test freeze, and be prepared to back off if it's too disruptive.

---

Another suggestion would be to try hiding `PodClient`'s framework dependency behind a shim, e.g.

Modify `Framework` to expose some things via functions instead of direct struct access (this isn't very golang, but bear with me)
```golang
// f/framework.go
func (f *Framework) GetNamespace() *v1.Namespace {
  return f.Namespace
}
func (f *Framework) GetClientSet() clientset.Interface {
  return f.ClientSet
}
// I'm not sure how I feel about this part, purely for the shim
// but others might start using it (and may need ExpectWithOffset tweak)
func (f *Framework) ExpectNoError(err error, explain ...interface{}) {
  ExpectNoError(err error, explain ...interface{})
}
```
Use the shim instead of framework to implement `e2epod.PodClient`
```golang
// f/pod/client.go
type FrameworkShim interface {
  GetNamepace() *v1.Namespace
  GetClientSet() clientset.Interface
  ExpectNoError(err, error, explain ...inteface{})
  // etc...
}
type PodClient struct {
  f FrameworkShim
  v1core.PodInterface
}
func NewPodClient(f FrameworkShim) *PodClient {
  return &PodClient{
    f:            f,
    PodInterface: f.GetClientSet().CoreV1().Pods(f.GetNamespace().Name),
  }
} 

// sample implementation 
func (c *PodClient) CreateSync(pod *v1.Pod) *v1.Pod {
  namespace := c.f.GetNamespace().Name
  p := c.Create(pod)
  c.f.ExpectNoError(e2epod.WaitTimeoutForPodReadyInNamespace(c.f.GetClientSet(), p.Name, namespace, PodStartTimeout))
  // Get the newest pod after it becomes running and ready, some status may change after pod created, such as pod ip.
  p, err := c.Get(context.TODO(), p.Name, metav1.GetOptions{})
  c.f.ExpectNoError(err)
  return p
} 
// etc...
```
Then progressively migrate tests to use the new client instead of the old one
```golang
// f/foo/foo_test.go
import e2epod "k8s.io/kubernetes/test/framework/pod"

// migrate from code using the old client
var oldClient *framework.PodClient = f.PodClient()
podOld := f.PodClient().CreateSync(pod)

// to code using the new client
var newClient *e2epod.PodClient = e2epod.PodClient(f)
podNew := e2epod.PodClient(f).CreateSync(pod)
```

I'm not _100%_ sure the shim approach lacks tangles? But I think it changes fewer function signatures, and could be landed without forcing a ton of code to migrate at once.

**Comment by mauriciopoppe** [comment]
@spiffxp thank you for the throughout review! I understand that I can work on this after code freeze (March 9) and should finish before test freeze (Wed March 24), the signature in the proposal is like the signatures in the e2epod public functions have the client and a config

```
func CreateClientPod(c clientset.Interface, ns string, pvc *v1.PersistentVolumeClaim) (*v1.Pod, error) {}
func CreateSecPod(client clientset.Interface, podConfig *Config, timeout time.Duration) (*v1.Pod, error) {}
```

Hiding it behind a shim sounds like a better approach, thanks for providing the a skeleton for a sample implementation too!

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
Sadly https://github.com/kubernetes/kubernetes/pull/100304 fell off my radar this cycle but I think that would get us a bunch of progress here

**Comment by pohly** [comment]
/reopen
/lifecycle frozen

I am reopening this one instead of https://github.com/kubernetes/kubernetes/issues/81232 because that looks like a duplicate.

**Comment by oomichi** [comment]
I think it is so difficult to solve this issue.
Let's close this issue at this time, and feel free to re-open if necessary.

**Comment by pohly** [comment]
> I think it is so difficult to solve this issue.

It wasn't easy, but doable: It was solved in https://github.com/kubernetes/kubernetes/pull/112043. Not sure why GitHub kept the issue open when that PR was merged.
