### ISSUE TITLE
Initialize all images as exported variables in test initialization.

### ISSUE THREAD

**Issue by saiyan86** [kubernetes/kubernetes#81258]
**What would you like to be added**:

Initialize all images as exported variables in test initialization.

**Why is this needed**:

We have a number of ```imageutils.GetE2EImage()``` calls scattered around in the test files. We should just initialize all images as exported variables during test initialization.

**Comment by saiyan86** [comment]
kind/cleanup

**Comment by liggitt** [comment]
A function is less susceptible to accidental modification. Is there a reason the function is problematic?

**Comment by saiyan86** [comment]
Because I see the same images get assigned to many vars in the test code base. This might be confusing and hard to maintain...
