### ISSUE TITLE
k8s GPU cannot not be isolated when privileged is set true? 

### ISSUE THREAD

**Issue by bluebeach** [kubernetes/kubernetes#81256]
**What happened**:
for some reason , my pod need to be root. so privileged is set true in yaml.
but when I set resources request `nvidia.com/gpu: "1"`, I can see all two GPU cards in the container using nvidia-smi.
![image](https://user-images.githubusercontent.com/4569903/62824062-241ac480-bbcb-11e9-8640-44e36c221362.png)

when I remove `privileged: true`, as expected I can see only one GPU card in my container.
how can I only see one GPU card while `privileged: true`???

**What you expected to happen**:
GPU is isolated when  `privileged: true`
can only see one GPU card in the container

**How to reproduce it (as minimally and precisely as possible)**:
nvidia.com/gpu: "1" && 
securityContext:
      privileged: true

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos 7.4
- Kernel (e.g. `uname -a`): Linux vcs-algo-k8s-master001 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): k8s-device-plugin/1.0.0-beta
- Others:

**Comment by bluebeach** [comment]
in other word, can GPU be isolated while `dmidecode` work in the container ??

**Comment by neolit123** [comment]
please ask in the #sig-node channel if you are not getting a response here. thanks.
/sig node

**Comment by zouyee** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by mattjmcnaughton** [comment]
@bluebeach I'm definitely not an expert in this area of the code, but to be honest, it doesn't surprise me that a privleged container can see all the resources available on the machine.

Another way to address this would be to make your container not need to run in privileged mode (which has other advantages as well). Is that an option?

**Comment by liucimin** [comment]
@bluebeach
Yes.It because if u use the privileged.The container will use the host's device.
So all the nvidia-gpu in the host's  /dev will also in the contianer.
So in the container will see all the gpu cards.

Maybe u can use capabilities to get the Container Capability to limit the conatiner use all the root devices.
  ```
  securityContext:
      capabilities:
        add:
        - NET_ADMIN
        drop:
        - KILL
```

**Comment by bluebeach** [comment]
> https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

could you please tell me which capability can be used to solve this problem ?

**Comment by bluebeach** [comment]
> @bluebeach I'm definitely not an expert in this area of the code, but to be honest, it doesn't surprise me that a privleged container can see all the resources available on the machine.
> 
> Another way to address this would be to make your container not need to run in privileged mode (which has other advantages as well). Is that an option?

Yeah it's reasonable a privileged container can see all the resources . 
I am confused that how a unprivileged container's GPU can be isolated by k8s

**Comment by windniw** [comment]
@bluebeach kubelet manage the GPU on the node with device-plugin, which get how many nvidia.com/GPU your pod requests in the spec.resources.requests && limits and put it in the mounting volume of the pod. That's how a unprivileged container's GPU be isolated.

**Comment by DemonZSD** [comment]
it's worked, replace privileged with capabilities : 
securityContext:
    capabilities:
      add:  ["ALL"]
