### ISSUE TITLE
Error not well handled in checkpoint.go

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#81273]
/kind bug

During reading the codes of pkg/kubelet/checkpoint/checkpoint.go 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/checkpoint/checkpoint.go#L98
I find we missed the error returned since https://github.com/kubernetes/kubernetes/pull/56040.
See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/config.go#L125 , we would alway send `PodUpdate` to `updates` when we call `LoadPods(c.checkpointManager)`

**Comment by mattjmcnaughton** [comment]
Thanks for taking such a careful look at the code @cwdsuzhou :)

I responded in your pr - I'm not actually convinced that `LoadPods` ignoring the error is a bad thing. Let's chat more on the pr :)

**Comment by cwdsuzhou** [comment]
> Thanks for taking such a careful look at the code @cwdsuzhou :)
> 
> I responded in your pr - I'm not actually convinced that `LoadPods` ignoring the error is a bad thing. Let's chat more on the pr :)

Thanks, let's talk about it

**Comment by liggitt** [comment]
based on feedback in https://github.com/kubernetes/kubernetes/pull/72202 (see https://github.com/kubernetes/kubernetes/pull/72202#issuecomment-528366080 this will be removed in 1.17

/close
