### ISSUE TITLE
Need a reliable way to determine if a Pod is preempted (evicted/garbageCollected) [A.K.A. Stop Pod API]

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/kubernetes#81285]
**What would you like to be added**:
Need a reliable way to determine if a Pod is preempted (evicted/garbageCollected)

**Why is this needed**:
Seems currently, we can only determine this by searching the Pod UID in all events in the namespace. See https://github.com/kubernetes/kubernetes/pull/50949.

However, seems **K8S events are not relaible** in many aspects, such as deleted after a while (TTL expired), best effort to send to APIServer (error seems ignored and will not retry until success), pod deletion and event recording is not executed in an all-or-nothing fashion, etc. In these cases, we cannot determine if a Pod is preempted, **we just know the Pod is deleted (i.e. missing alarm).** 

However, it may be very useful for user/admin/client to understand/know the Pod is preempted, and preempted by who, and the overall cluster preemption detail history. And adopt special reactions for the preemption, such as always retry, optimize resource placement, etc.

K8S events seems to be more like a human debugging helper, it seems it is not a good approach to programmatically and reliablely determine what is happened. 

Another apporach is to provide a new Pod API, say **Stop Pod**: it just stop the Pod execution (i.e. also release the physical resource), and does not really delete the Pod object from APIServer. So that we can record the preemption info inside the Pod object along with the "Stop" action info.

In this apporach, we can also make the Pod eviction/garbageCollected message recorded into Pod object, instead of just delete the Pod, without any message for users/clients to understand and react on this. Besides, the final exit info caused by graceful Pod deletion (such as controller want to graceful shutdown the Pod), can also be reliablely fetched, otherwise the Pod may be deleted immediately, and controllers/users may have no chance to fetch the final exit info, to determine if it is graceful exited, etc.

Maybe we can leverage **Pod finalizer** to achieve the same basic behaviour of "Stop Pod API" when scheduler try to preempt Pod, but it would be great if we can make an API for it, so that scheduler can directly call it, and garbageCollector, Pod evictor and other controllers can also directly reuse it.

Anyway, in principle, it also looks like more reasonable to **decouple** 2 things to 2 different APIs:
1. Stop a Pod execution (like `docker stop`)
2. Delete a Pod object (like `docker rm`)

I.e. Stop Pod doesn't have to be deleted.

**Comment by yqwang-ms** [comment]
@bsalamat @wojtek-t @davidopp Could you please take a look at this? Thanks!!!

**Comment by yqwang-ms** [comment]
Also cc @gmarek in case the K8S event plans to also cover this issue.

**Comment by yqwang-ms** [comment]
Thanks @krmayankk added this to debt, so, any progress there?
Could anyone help on this? :)

**Comment by lavalamp** [comment]
For eviction, there is already: https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#eviction-api

The other part of the request seems to be about having a historical record. There are audit logs for that. Alternatively, you could use a finalizer with a controller recording the fact that the pod is getting deleted (and why) to some persistent location (i.e., write a tombstone).

It's too late to change the deletion workflow to mean something other than what it already does.

Note that some pod termination methods do leave the pod object around, and there's a podgc controller to clean those up.

**Comment by lavalamp** [comment]
Sorry, it looks like the old triage process missed this when you tried to give it back to us. api-machinery is not about the api, it's about the mechanisms that enable the api. sig arch owns the api (or in this case, sig node and/or sig apps).

I don't think there's any system change we can make here, but I guess I'll leave this open for sig arch to look at.

**Comment by yqwang-ms** [comment]
@lavalamp  Thanks for the response, my main point is about the **reliable** way to get the deletion reason, as all other **ways** are **besteffort**, such as events, logs, etc.
For the **reliable** way, we need to persist the reason, as the same way to persist pod's other fields, such as Pod.State, etc

**Comment by lavalamp** [comment]
Audit logs are reliable (if you log everything).

This can be built with the finalizer mechanism and doesn't need to be done in-tree.

**Comment by yqwang-ms** [comment]
Do you mean the finalizer controller needs to parse the audit log?

Anyway, seems even log are besteffort, as they are aysnc write to disk, so if the writer process or the whole node unexpectedly shutdown, the log will lost

**Comment by lavalamp** [comment]
> Do you mean the finalizer controller needs to parse the audit log?

No, audit log is a separate mechanism.

A finalizer on the object prevents it from finishing the deletion process and being removed, until your controller removes the finalizer. You could have your controller record any fact you like about the pod first.

> Anyway, seems even log are besteffort, as they are aysnc write to disk, so if the writer process or the whole node unexpectedly shutdown, the log will lost

How much certainty do you need here? Audit logs are for doing audits for compliance etc. Do you need really more certainty than that? And you can configure them to be pushed off-system.

**Comment by yqwang-ms** [comment]
But anyway, to know the pod deletion reason should be a common request, why we do not want support a **Stop Pod** API like all other system such as docker, to resolve this. 
Depends on log seems not to be the final solution, right?

**Comment by lavalamp** [comment]
I do not think it is realistic to change the existing deletion sequence, too hard to maintain backwards compatibility. AFAICT there's essentially no chance we would attempt a modification to this.

I described how to build a system using the finalizer mechanism to capture the final state of pods and store it wherever you wish.

IMO the way forward here is to build a system that solves your needs using that mechanism. Package it so others can easily install and use it. Get wide adoption. Then it will be an easy sell for inclusion here in upstream Kubernetes. Note that this wouldn't change the existing path, and you don't need our sign-off to try this.

Lastly, I don't actually know what your use case is-- audit logs are good for some things and not others.
