### ISSUE TITLE
unknown flag: --record for "kubectl create" command 

### ISSUE THREAD

**Issue by serefacet** [kubernetes/kubernetes#81289]
**What happened**
I am not able to pass `--record=true` parameter while using `kubectl create` command. Hence, I can't register change cause seen in `kubectl rollout history` output when I use `kubectl create`

```
$ kubectl create deployment --image=nginx --record=true
Error: unknown flag: --record
```

**What you expected to happen:**
I should record the command while using `kubectl create` command. The ambigious thing is that I'm able to pass `--record` parameter with deprecated `kubectl run` command. In addition to that, I can pass `--record` with `kubectl set` as expected.

**How to reproduce it (as minimally and precisely as possible):**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl create deployment --image=nginx --record=true
Error: unknown flag: --record
```
**Anything else we need to know?:**
I'm aware of issue [#40422](https://github.com/kubernetes/kubernetes/issues/40422) however `--record` options are deleted only for `kubectl create` as far as I investigate. We need to clarify the usage of change-cause in `kubectl rollout history` command.

**Comment by borball** [comment]
I saw lots of mismatchings (in version 1.15.4, probably other newer version as well) between help information/documents and the real commands output, for example:  

Command 'kubectl help create' printed '--record' is supported as an option, but when we ran 'kubectl create deployment nginx --image=nginx --record ', it gave an error like 'Error: unknown flag: --record'.

Also, the 'CHANGE-CAUSE' in output of 'kubectl rollout history' looks like always empty now. 

We may need a full review and correction in all the places including document, kubectl help information and release notes.

**Comment by monotek** [comment]
Also run in this on 1.15.1.
Downgrading kubectl down to 1.9.0 did not help too.
When did this work the last time?

**Comment by nautilor** [comment]
I think it was working until 1.6

does [this](https://github.com/kubernetes/kubernetes/issues/40422) help?

**Comment by monotek** [comment]
Thanks for the link :)
Not sure if the "CHANGE-CAUSE" table in rollout history makes any sense without this ¯\_(ツ)_/¯

**Comment by tedyu** [comment]
I encountered this issue too.
```
kubectl apply -f x.yaml --record
```
As workaround, you can use apply command.

**Comment by gabrielbcn** [comment]
issue still present in 1.19.2
