### ISSUE TITLE
rs keeps creating pods until there is a pod ready 

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#81284]
**What happened**:
Rs keeps creating pods until there is a pod ready and it doesn't clean up the invalid pods for me. I see that there is a parameter .spec.minReadySeconds defaults to 0. If readiness initialDelaySeconds is not empty, it may be can used as the default. 
In addition, if the service has not been able to run successfully, the pod will be created continuously.
```
[root@iZ2zehkmdztgqr9gfnfrttZ log]# kubectl get rs jxing-nginx-ingress-controller-dc55776d7 -n kube-system
NAME                                       DESIRED   CURRENT   READY   AGE
jxing-nginx-ingress-controller-dc55776d7   1         1         1       36m
[root@iZ2zehkmdztgqr9gfnfrttZ log]# kubectl get po -n kube-system -l release=jxing
NAME                                                   READY   STATUS             RESTARTS   AGE
jxing-nginx-ingress-controller-dc55776d7-57zq5         1/1     Running            0          35m
jxing-nginx-ingress-controller-dc55776d7-rmt65         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-s5c8s         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-sbz84         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-wngz8         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-wx5g8         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-xh59b         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-xrkzr         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-xzzzq         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-z5j79         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-controller-dc55776d7-zl4j9         0/1     PodFitsHostPorts   0          35m
jxing-nginx-ingress-default-backend-64488c75fd-tqcsq   1/1     Running            0          35m
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
[root@iZ2zehkmdztgqr9gfnfrttZ log]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"4304b26", GitTreeState:"", BuildDate:"2019-04-08T08:50:29Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-04-22T11:34:20Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by WanLinghao** [comment]
seems duplicate #72593

**Comment by zjj2wry** [comment]
Close because duplicate #72593
