### ISSUE TITLE
IsLocalEphemeralVolume function misses secret volume type

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#81317]
In the function IsLocalEphemeralVolume to check whether volume is using ephemeral storage or not, it misses "secret" volume type. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L544

**Comment by mrkm4ntr** [comment]
Secrets are mounted as tmpfs, so I think they are not local ephemeral "volumes".

**Comment by NickrenREN** [comment]
agree with @mrkm4ntr

**Comment by jingxu97** [comment]
close this since it is not an issue
