### ISSUE TITLE
Enable snapshot tests for pd csi driver

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#81318]
**What would you like to be added**:
Enable snapshot tests for gce-pd csi driver tests in k/k

**Why is this needed**:
Snapshot is moving to beta in 1.16. We should enable snapshot e2e tests with a real storage driver.

**Comment by msau42** [comment]
/assign @jingxu97 
cc @xing-yang

**Comment by yuxiangqian** [comment]
cc @yuxiangqian @boylee1111

**Comment by yuxiangqian** [comment]
target 1.17 instead of 1.16
