### ISSUE TITLE
[Failing Test] [sig-scheduling] SchedulerPriorities [Serial] Pod should be preferably scheduled to nodes pod can tolerate

### ISSUE THREAD

**Issue by soggiest** [kubernetes/kubernetes#81316]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-scheduling] SchedulerPriorities [Serial] Pod should be preferably scheduled to nodes pod can tolerate

**Since when has it been failing**:
2019-08-10

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:220
Expected
    <string>: bootstrap-e2e-minion-group-rpd8
to equal
    <string>: bootstrap-e2e-minion-group-qvr9
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1359
```

**Anything else we need to know**:

/milestone v1.16
/priority critical-urgent
/kind failing-test
/sig scheduling
/cc @kubernetes/sig-scheduling-misc 
/cc @Verolop @jimangel @soggiest @alenkacz

**Comment by Huang-Wei** [comment]
The changes has been reverted by #81295.

/cc @ravisantoshgudimetla

**Comment by jimangel** [comment]
@Huang-Wei it still seems to be failing on `test` / `timeout` with:
```
error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true (interrupted): exit status 1
 
#and

kubetest --timeout triggered
```

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Comment by Huang-Wei** [comment]
@jimangel the testgrid is green since the PR reverting:

![image](https://user-images.githubusercontent.com/1425903/63146680-aa128300-bfb0-11e9-9eef-be502bf6b898.png)

**Comment by jimangel** [comment]
Thanks @Huang-Wei, sorry to mix up the tests.

We'll keep our eye on it for a little longer before closing and I'll make sure we have issues for the other failures.
