### ISSUE TITLE
When creating a cronjob, Reference an existing job

### ISSUE THREAD

**Issue by mouyang** [kubernetes/kubernetes#81329]
**What would you like to be added**:

An ad-hoc run of a cronjob can be triggered by using the `kubectl job --from=<cronjob>`.  The inverse operation should be available as well: 

Sample Command Line: `kubectl create cronjob --from-job=<job>`

Sample YAML definition:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplateFrom: 
    name: <JobTemplateSource>
```

**Why is this needed**:

Usability from multiple perspectives:
* For unit testing, it is more intuitive to verify a job works standalone before putting it on a cronjob schedule.
* The domain model suggested by the current functionality feels inverted.  A job does not have to be connected to a cronjob in order to exist, but a cronjob can't exist without a job.
* For a command-line user unaware of the existing functionality, in order to test the job they would need to either wait a potentially long time for a scheduled run, or overwrite the schedule in the cronjob spec using Helm or other means.  Even if they knew about it, it is a very roundabout way of doing a simple task.
* For a Dashboard user, the only way to unit test a job defined within a cronjob is to trigger it manually from a cronjob.  Since there is an clear "Trigger" link in the Dashboard, this gives the impression that a manually triggered job from a cronjob will be cleaned up automatically as per the (successful/failed)JobsHistoryLimit when (I personally agree with this) it is not.

**Comment by north-cackalacky** [comment]
Is this enhancement on the agenda?

**Comment by crigas1** [comment]
this would be a very useful feature

**Comment by ojaswa1942** [comment]
Is any particular reason why this is not discussed?

From my understanding, CronJobs create `Jobs` as per the specified schedule. As a result, an existing job is expected to be short-lived and cannot be referenced in the CronJob. That might be a challenge.   

However, it'd be great to be able to reference an existing job template in multiple locations. A genuine use case is to run a job at creation, followed by CronJob with an identical job template. With this in place, we will not need to maintain duplicate configurations for the same purpose, which is often missed with frequently-changing teams.
