### ISSUE TITLE
cpumanager will remove all entries in state file after restart.

### ISSUE THREAD

**Issue by choury** [kubernetes/kubernetes#81324]
**What happened**:
PR #68619 , it will remove "inactive containers" while reconciling. But the cpumanager started very beginning, it will get empty activePods at it first run. This make state file no sense.

**What you expected to happen**:
We should wait a moment or  notification from podmanager before starting reconcile.
 Some log may be added before remove "inactive containers".

**How to reproduce it (as minimally and precisely as possible)**:
restart kubelet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
In reconcileState :
```
	for containerID := range m.state.GetCPUAssignments() {
```
You mean the cpu assignments would be wiped for the first reconciliation ?

**Comment by choury** [comment]
@tedyu Yes, you can test it by restarting kubelet.

**Comment by tedyu** [comment]
Do you see any of the following log:
```
				klog.Warningf("[cpumanager] reconcileState: skipping pod; status not found (pod: %s)", pod.Name)

				klog.Warningf("[cpumanager] reconcileState: skipping container; ID not found in status (pod: %s, container: %s, error: %v)", pod.Name, container.Name, err)

					klog.V(4).Infof("[cpumanager] reconcileState: container is not present in state - trying to add (pod: %s, container: %s, container id: %s)", pod.Name, container.Name, containerID)
```

**Comment by choury** [comment]
I see this
`klog.V(4).Infof("[cpumanager] reconcileState: container is not present in state - trying to add (pod: %s, container: %s, container id: %s)", pod.Name, container.Name, containerID)`
