### ISSUE TITLE
Question about local E2E test

### ISSUE THREAD

**Issue by zhlhahaha** [kubernetes/kubernetes#81323]
Recently I am trying to do e2e test in my local server and I followed this guidance,
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#local-clusters

However, I found local e2e test had been removed from source code. I tracked the change log, but did not find any information on why remove it. 
Here are two pr for removing the code:
https://github.com/kubernetes/kubernetes/pull/49148
https://github.com/kubernetes/kubernetes/pull/76711 

So here is my question, is it still possible to do local e2e test now and how? If not, is there any plan to enable local e2e test in the future?

Thanks a lot for your answer, I have trapped here really a long time.
/sig Testing
/sig Docs

**Comment by dims** [comment]
you can use `kubetest` directly to run e2e tests. example https://github.com/kubernetes/test-infra/issues/8698#issue-341745242

**Comment by zhlhahaha** [comment]
Sorry @dims , I just saw your answer. Kubetest still not work for e2e local test, but I am currently using e2e.test binary to run the test. It works fine. Thanks for your answer.

**Comment by zhlhahaha** [comment]
> @zhlhahaha How did you run the binary,I just run it and errors occured:
> 
> ```
> Error loading client: error creating client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
> ```
> 
> * I already have a cluster ：master + node*2,
> * My kubernetes version is 1.14.2

Hi tomatoAres,

I build kubernetes cluster via ./hack/local-up-cluster.sh, and I just checked that e2e.test can run on it.
Form your output, it miss some environmental variable. If you build your cluster via kubeadm, have you set following variable?
"export KUBECONFIG=/etc/kubernetes/admin.conf"

BR,
Howard
