### ISSUE TITLE
TestVolumeProvision is flaky 

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#81368]
**Which jobs are failing**:

pull-kubernetes-integration

**Which test(s) are failing**:

TestVolumeProvision

Example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81330/pull-kubernetes-integration/1161315691412852736/

```
--- FAIL: TestVolumeProvision (12.16s)
    volume_binding_test.go:1149: Provisoning annotaion on PVC volume-schedulingfc108048-dc1f-4999-8323-f3302c9eb3ca/pvc-w-canbind not bahaviors as expected: PVC volume-schedulingfc108048-dc1f-4999-8323-f3302c9eb3ca/pvc-w-canbind not expected to be provisioned, but found selected-node annotation
    volume_binding_test.go:1191: PV pv-w-canbind phase not Bound, got Available
```

**Since when has it been failing**:

Not sure, [triage board](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestVolumeProvision) and [test grid](https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&sort-by-flakiness=) aren't displaying any results

/sig storage

**Comment by msau42** [comment]
/assign @msau42 @cofyc 
/remove-lifecycle rotten
Still seeing this, although not very frequently. Could indicate a race.

**Comment by cofyc** [comment]
latest failures:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1287138465619644420
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1287061710439452674
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1286724218758631424

**Comment by cofyc** [comment]
take `https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1287138465619644420` as an example

the test fails b/c `selected-node` is set to PVC `pvc-w-pv-prebound`, which is not expected.

```
    volume_binding_test.go:1310: Provisoning annotation on PVC volume-scheduling3589f896-5d5f-486a-be2e-4b25290b159f/pvc-w-pv-prebound not as expected: PVC volume-scheduling3589f896-5d5f-486a-be2e-4b25290b159f/pvc-w-pv-prebound not expected to be provisioned, but found selected-node annotation
```

this may happen when the PV controller fails to bind the PVC `pvc-w-pv-prebound` with `pv-w-prebound` before the scheduler tries to scheduler the pod:

```
I0725 22:01:59.630783  115070 pv_controller.go:913] updating PersistentVolume[pv-w-prebound]: binding to "volume-scheduling3589f896-5d5f-486a-be2e-4b25290b159f/pvc-w-pv-prebound" failed: Operation cannot be fulfilled on persistentvolumes "pv-w-prebound": the object has been modified; please apply your changes to the latest version and try again
I0725 22:01:59.630805  115070 pv_controller.go:995] error binding volume "pv-w-prebound" to claim "volume-scheduling3589f896-5d5f-486a-be2e-4b25290b159f/pvc-w-pv-prebound": failed saving the volume: Operation cannot be fulfilled on persistentvolumes "pv-w-prebound": the object has been modified; please apply your changes to the latest version and try again
I0725 22:01:59.630834  115070 pv_controller_base.go:265] could not sync claim "volume-scheduling3589f896-5d5f-486a-be2e-4b25290b159f/pvc-w-pv-prebound": Operation cannot be fulfilled on persistentvolumes "pv-w-prebound": the object has been modified; please apply your changes to the latest version and try again
```

when the scheduler is scheduling the pod while the PVC `pvc-w-pv-prebound` is not bound. our volume binder will try to dynamically provision it.

**Comment by cofyc** [comment]
as for https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1286724218758631424

the test `TestVolumeProvision/with_CSIStorageCapacity/wait_one_bound,_one_provisioned` fails for the same reason

```
    volume_binding_test.go:1310: Provisoning annotation on PVC volume-scheduling49829bca-acdd-42c1-8dfe-b018acca07c9/pvc-w-canbind not as expected: PVC volume-scheduling49829bca-acdd-42c1-8dfe-b018acca07c9/pvc-w-canbind not expected to be provisioned, but found selected-node annotation
```

when the scheduler volume binder tries to find volumes for PVC `pvc-w-canbind`, its corresponding volume `pv-w-canbind` is not synced to volume binder `PVAssumeCache`

```
I0724 18:37:04.098547  114928 scheduler.go:454] Attempting to schedule pod: volume-scheduling49829bca-acdd-42c1-8dfe-b018acca07c9/pod-pvc-canbind-or-provision
I0724 18:37:04.098798  114928 scheduler_binder.go:819] No matching volumes for Pod "volume-scheduling49829bca-acdd-42c1-8dfe-b018acca07c9/pod-pvc-canbind-or-provision", PVC "volume-scheduling49829bca-acdd-42c1-8dfe-b018acca07c9/pvc-w-canbind" on node "node-1"
```

so the volume binder will try to dynamically provision it too

**Comment by cofyc** [comment]
I think the root cause is that the scheduler fails to find matching PVs in PV Assume Cache for the PVC because the PV in the Assume Cache is not in Available state or does not exist due to event delay.

We should wait for the PV/PVC Assume Cache to be up to date before scheduling the pod. However, it's not possible in integration tests. I think we can wait for the PV to be available or bound. This should reduce failures.
