### ISSUE TITLE
CoreDNS fails to start after upgrading from 1.14.5 to 1.15.2

### ISSUE THREAD

**Issue by jeanluclariviere** [kubernetes/kubernetes#81371]
**What happened**:
After upgrading a cluster from 1.14.5 to 1.15.2, each coredns pod fails and gets stuck in the "ContainerCreating" stage with error:

>  Warning  FailedCreatePodSandBox  2m9s                 kubelet, jl-kube-worker-linux-1.mi.lab  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "c57a80147ac6decdf8cf431693f9c202e8061498d902357a8212240ce89a2b83" network for pod "coredns-584795fc57-ccdhp": NetworkPlugin cni failed to set up pod "coredns-584795fc57-ccdhp_kube-system" network: connection is unauthorized, failed to clean up sandbox container "c57a80147ac6decdf8cf431693f9c202e8061498d902357a8212240ce89a2b83" network for pod "coredns-584795fc57-ccdhp": NetworkPlugin cni failed to teardown pod "coredns-584795fc57-ccdhp_kube-system" network: connection is unauthorized]

**What you expected to happen**:
For coredns pods to come up like normal

**How to reproduce it (as minimally and precisely as possible)**:
using kubeadm, perform the upgrade from 1.14.5 to 1.15.2: sudo kubeadm apply 1.15.2

**Anything else we need to know?**:
While upgrading the cluster, I checked the events in the kube-system namespace and could see the exact same error occurring on all of the new "upgrade" pods being started - in the end, the errors cleared and kubeadm deemed the upgrade a "success". Describing the running pods within the kube-system namespace does indicate that the new images are being used. We also have podSecurityPolicies enabled, but the coredns service account was granted privileged permissions so i don't believe this is a problem.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
openstack, on-prem.

- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

- Kernel (e.g. `uname -a`):
Linux 3.10.0-957.21.2.el7.x86_64 #1 SMP Tue May 28 09:26:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm

- Network plugin and version (if this is a network-related bug):
flannel

**Comment by jeanluclariviere** [comment]
I got lucky, it seems i was able to solve the problem by re-installing flannel.

**Comment by neolit123** [comment]
hi,

> Describing the running pods within the kube-system namespace does indicate that the new images are being used

the coredns version in kubeadm, between 1.14 and 1.15 did not change - 1.3.1, so not sure how new images would have been used.

> We also have podSecurityPolicies enabled, but the coredns service account was granted privileged permissions so i don't believe this is a problem.

the fact that re-installing flannel has solved this, indicates to me that this might be a PSP related problem. our e2e upgrade tests currently don't have PSPs enabled, so we have not seen such a problem.

i'm pretty sure this will re-occur the next time you upgrade.

you re-open your ticket in the k/kubeadm repository for better visibility of the kubeadm team and please:
- include "using PSP" in the ticket title
- link to this closed ticket

thanks
/close
