### ISSUE TITLE
resource.Quantity.Format isn't set consistently for each v1/type resource

### ISSUE THREAD

**Issue by egernst** [kubernetes/kubernetes#81379]
**What happened**:
Each v1/type Resource type should have a particular format for its quantity. In assessing appropriate values for resource's Quantity.Format (ie, BinarySI, DecimalSI), I see that usage for a given type is not consistent (particularly within test code).

**What you expected to happen**:

I *think* these should be set consistently for a given define resource type.

**How to reproduce it (as minimally and precisely as possible)**:

For example, looking at the type ResourceStorage, from top of k/k source tree:
git grep ResourceStorage  | grep -E BinarySI | wc
      4      16     467
git grep ResourceStorage  | grep -E DecimalSI | wc
     20      80    2752

**Anything else we need to know?**:

Happy to fix this - just wanted confirmation first that it should be consistent, and follow what is detailed here:
```golang
        switch resourceName {
        case v1.ResourceCPU:
                requestQuantity = resource.Quantity{Format: resource.DecimalSI}
        case v1.ResourceMemory:
                requestQuantity = resource.Quantity{Format: resource.BinarySI}
        case v1.ResourceStorage:
                requestQuantity = resource.Quantity{Format: resource.BinarySI}
        case v1.ResourceEphemeralStorage:
                requestQuantity = resource.Quantity{Format: resource.BinarySI}
        }
```
 
**Environment**:

Master k/k codebase

**Comment by dashpole** [comment]
The proposed values look correct to me

**Comment by egernst** [comment]
Thanks -- I'll sed a PR to make the tests consistent in their usage. I wonder if this should be documented somewhere in the code?
