### ISSUE TITLE
scale client: support non-namespaced resources

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/kubernetes#81380]
**What would you like to be added**:
The scale client (`k8s.io/client-go/scale`) currently works fine with namespaced resources. However, it doesn't work for non-namespaced resources e.g. cluster-scoped CRDs. The current implementation should be extended in order to support non-namespaced resources.

The current `ScalesGetter` interface:
https://github.com/kubernetes/kubernetes/blob/f020c9159869918c63e0aad56abd01e655e61e78/staging/src/k8s.io/client-go/scale/interfaces.go#L25-L29

/area custom-resources
/sig autoscaling

**Comment by MaciekPytel** [comment]
I think scale subresource support for CRDs falls more into sig-apimachinery domain. After DirectXMan12 moved on from sig-autoscaling I don't think there is anyone in our sig-autoscaling with knowledge of scale subresource internals. 

/sig api-machinery

**Comment by roycaihw** [comment]
The bug report sounds legit. Does the generic scale client need to be changed (I think so), or does https://github.com/kubernetes/dashboard/pull/4195 solve your issue?

**Comment by eloyekunle** [comment]
No, the dashboard PR doesn't solve this. I discovered this issue while working on that PR so when https://github.com/kubernetes/dashboard/pull/4195 gets merged, it will only work for namespaced CRDs.

I think the generic scale client needs to be updated, maybe by adding another getter to the ScalesGetter interface:

```go
ScalesIfScoped(namespace string, isScoped bool) ScaleInterface
```

**Comment by eloyekunle** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/81507
