### ISSUE TITLE
external provisioner tests failing in alpha suites

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#81403]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-alpha-enabled-default

**Which test(s) are failing**:
CSI hostpath-v0 tests

**Since when has it been failing**:
8/8

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-alpha-enabled-default

**Reason for failure**:
#80978

**Anything else we need to know**:
We need to update client-go to get the fix for selfLink, build new nfs provisioner images, and update them in the e2e test.  The fix for client-go is being cherry-picked to 1.15 if you want to use a tagged release: https://github.com/kubernetes/kubernetes/pull/81355

**Comment by msau42** [comment]
/assign @childsb @jsafrane 
@kubernetes/sig-storage-test-failures

**Comment by jsafrane** [comment]
This implies rebase to 1.15.x in external-storage, which seem to be challenging (at least to me :-) )

**Comment by msau42** [comment]
1.14 cherry pick also in progress: https://github.com/kubernetes/kubernetes/pull/81407

**Comment by wongma7** [comment]
OK, I guess this line in the lib is the culprit: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/c525773885fccef89a1edd22bb3f813d50548ed1/controller/controller.go#L1214
So I need to update lib then external-storage to pull it in

**Comment by msau42** [comment]
I don't think the lib itself needs to be updated.  Only updating go-client to get the fix to `GetReference` is needed.

**Comment by wongma7** [comment]
Right, lib doesn't dictate what version of client-go to use. Will wait for client-go release

**Comment by wojtek-t** [comment]
@wongma7 - thanks a lot for bumping the dependency.
Did you have a chance to build the new container with it so that we could update it here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/utils/utils.go#L446

**Comment by wongma7** [comment]
@wojtek-t yeah, opened https://github.com/kubernetes/kubernetes/pull/81620 . (Not sure how to trigger test, or we can just merge and see.)

**Comment by msau42** [comment]
You can manually create a PVC on an alpha cluster to test.
