### ISSUE TITLE
kubelet_running_pod_count metric is not correct

### ISSUE THREAD

**Issue by shiyan2016** [kubernetes/kubernetes#81412]
**What happened**:
kubelet_running_pod_count is larger than the pod actually running on the node, as follows:

Getting metic on prometheus:
```
kubelet_running_pod_count{instance="k8s-node01"}
```
result is:
```
kubelet_running_pod_count{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",instance="k8s-node01",job="kubernetes-nodes",kubernetes_io_hostname="k8s-node01"}  98
```
But using kubectl describe node:
```
kubectl  describe node k8s-node01
```
result is:
```
Non-terminated Pods:         (95 in total)
```
kubelet_running_pod_count is 98 but actually there is only 95 pod running on the node.

**What you expected to happen**:
kubelet_running_pod_count should equal the pod actually running on the node

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  centos linux 7 
- Kernel (e.g. `uname -a`): 4.14.67-2.el7.centos.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zouyee** [comment]
`pc.containerCache.GetPods()`
 It use a cache structure, so there is a delay.

**Comment by shiyan2016** [comment]
> `pc.containerCache.GetPods()`
> It use a cache structure, so there is a delay.

I look it again now, it still show 98 in prometheus, but actually 95 on the node.

**Comment by zouyee** [comment]
Execute the following command：
`curl http://your host:10255/metrics|grep kubelet_running_pod`

**Comment by zouyee** [comment]
If you want to monitoring K8S object, I recommend you to use [ksm](https://github.com/kubernetes/kube-state-metrics).

**Comment by shiyan2016** [comment]
> Execute the following command：
> `curl http://your host:10255/metrics|grep kubelet_running_pod`

The result is still 98, as below：
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP kubelet_running_pod_count Number of pods currently running
# TYPE kubelet_running_pod_count gauge
kubelet_running_pod_count 98
100 80107  100 80107    0     0   472k      0 --:--:-- --:--:-- --:--:--  474k
```

**Comment by shiyan2016** [comment]
> If you want to monitoring K8S object, I recommend you to use [ksm](https://github.com/kubernetes/kube-state-metrics).

I want to get the non-running pod count on the node. So I use the prometheus query:
```
(sum(label_replace((kube_pod_info), "instance", "$1", "node", "(.+)")) by(instance) - sum by (instance) (kubelet_running_pod_count)) != 0
```
And found that there are negative result. Checking the negative result, it shows the kubelet_running_pod_count is not correct. 

Getting kubelet_running_pod use ksm, I think I can add pod node info in the metric kube_pod_status_phase. But kubelet_running_pod_count in kubelet prometheus metic is still a bug.

**Comment by zouyee** [comment]
Would you mind to provide the following results? 
`kubectl get po --all-namespaces -owide|grep k8s-node01|grep Running|wc -l`   
`kubectl get po --all-namespaces -owide|grep k8s-node01|wc -l`
`docker ps|grep pause|wc -l`
`count(kube_pod_info unless on (pod, namespace) (kube_pod_status_phase{job="kube-state-metrics", phase="running"} > 0))  by (node) `

**Comment by shiyan2016** [comment]
> Would you mind to provide the following results?
> `kubectl get po --all-namespaces -owide|grep k8s-node01|grep Running|wc -l`
> `kubectl get po --all-namespaces -owide|grep k8s-node01|wc -l`
> `k8s-node01: docker ps|grep pause|wc -l`
> `count(kube_pod_info unless on (pod, namespace) (kube_pod_status_phase{job="kube-state-metrics", phase="running"} > 0)) by (node) `

`kubectl get po --all-namespaces -owide|grep k8s-node01|grep Running|wc -l`
95
`kubectl get po --all-namespaces -owide|grep k8s-node01|wc -l`
95

k8s-node01: docker ps|grep pause|wc -l
98
 `count(kube_pod_info unless on (pod, namespace) (kube_pod_status_phase{job="kube-state-metrics", phase="running"} > 0)) by (node) `
95

**Comment by zouyee** [comment]
`kubelet_running_pod_count` == `docker ps|grep pause|wc -l`
related code :https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L297

**Comment by shiyan2016** [comment]
> `kubelet_running_pod_count` == `docker ps|grep pause|wc -l`
> related code :https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L297

I found that one pod had start 3 pause containers, and another pod started 2 pause containers. Do not quite understand what makes that start more pause containers since our pod did not specify extra container use pause image.

**Comment by shiyan2016** [comment]
> `kubelet_running_pod_count` == `docker ps|grep pause|wc -l`
> related code :https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L297

I think using pause container count to calculate kubelet_running_pod_count is not correct. For example, the pod's pause container had set up successfully, but other container in pod does not in running state.

**Comment by zouyee** [comment]
The judgment of the pod running for kubelet is different from other components.

**Comment by ddobrijalowski** [comment]
We run a lot of small jobs as part of Argo workflows. When they are done workflow and pods are removed. 

Describe node and docker ps are showing 12 pods. kubelet_running_pod_count is showing 562.
`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by tyrken** [comment]
We run a CronJob (https://github.com/kubernetes-sigs/descheduler) and noticed that the "CompletedJobs" it periodically produces are included in the reported metric `kubelet_running_pod_count`.  Ideally they shouldn't...

**Comment by tyrken** [comment]
Links to PRs trying to fix this:
* https://github.com/kubernetes/kubernetes/pull/85983 (looks stale)
* https://github.com/kubernetes/kubernetes/pull/92187 (hopeful)

**Comment by pacoxu** [comment]
> Links to PRs trying to fix this:
> 
> * #85983 (looks stale)
> * #92187 (hopeful)

#85983 is merged on 31 Jul 2020.

Can we close this?
