### ISSUE TITLE
Use log functions of core e2e framework instead of e2elog sub package

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#81427]
**What happened**:

We tried to separate logger functionality as subpackage of e2e test framework,
but we've recognized that should be core functionality and we should keep it as
core of e2e test framework after facing circular dependency issues.
After merging https://github.com/kubernetes/kubernetes/pull/81426 the existing callers of subbackage e2elog need to switch
to use log functions of core e2e framework instead.
This issue is for tracking this working items.

**Necessary callers to be updated**:
- [x] test/e2e/framework/create.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/exec_util.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/flake_reporting_util.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/framework.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/get-kubemark-resource-usage.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/google_compute.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/log_size_monitoring.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/networking_utils.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/nodes_util.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81693)
- [x] test/e2e/framework/resource_usage_gatherer.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81685)
- [x] test/e2e/framework/rc_util.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81685)
- [x] test/e2e/framework/size.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81685)
- [x] test/e2e/framework/suites.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81685)
- [x] test/e2e/framework/test_context.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81685)
- [x] test/e2e/framework/util.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81685)
- [x] test/e2e/framework/pv_util.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81809)
- [x] test/e2e/framework/pods.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81809)
- [x] test/e2e/framework/deployment/*.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81811)
- [x] test/e2e/framework/endpoints/ports.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81811)
- [x] test/e2e/framework/ingress/ingress_utils.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81811)
- [x] test/e2e/framework/job/rest.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81814)
- [x] test/e2e/framework/kubelet/*.go (@oomichi Need to solve circular dependencies)
- [x] test/e2e/framework/lifecycle/upgrade.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81814)
- [ ] test/e2e/framework/metrics/*.go (@oomichi Need to solve circular dependencies https://github.com/kubernetes/kubernetes/pull/82108 but need more work)
- [ ] test/e2e/framework/node/*.go (@oomichi Need to solve circular dependencies)
- [x] test/e2e/framework/perf/perf.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81849)
- [ ] test/e2e/framework/pod/*.go (@oomichi Need to solve circular dependencies)
- [x] test/e2e/framework/providers/aws/aws.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81855)
- [x] test/e2e/framework/providers/azure/azure.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81855)
- [x] test/e2e/framework/providers/gce/*.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81855)
- [x] test/e2e/framework/replicaset/rest.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81973)
- [x] test/e2e/framework/service/*.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81973)
- [ ] test/e2e/framework/ssh/ssh.go (@oomichi Need to solve circular dependencies)
- [x] test/e2e/framework/statefulset/*.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81973)
- [x] test/e2e/framework/psp/psp.go (https://github.com/kubernetes/kubernetes/pull/84509)
- [x] test/e2e/framework/profile_gatherer.go (@oomichi https://github.com/kubernetes/kubernetes/pull/81973)
- [x] test/e2e/apps/*.go (@k-toyoda-pi https://github.com/kubernetes/kubernetes/pull/81935)
- [x] test/e2e/gke_node_pools.go (@hwdef )
- [x] test/e2e/apimachinery/*.go (https://github.com/kubernetes/kubernetes/pull/83011)
- [x] test/e2e/instrumentation/monitoring/*.go (@hwdef )
- [x] test/e2e/instrumentation/logging/*.go (@hwdef https://github.com/kubernetes/kubernetes/pull/81997)
- [x] test/e2e/network/*.go (@hwdef https://github.com/kubernetes/kubernetes/pull/81988)
- [x] test/e2e/common/*.go (@YuikoTakada)
- [x] test/e2e/scheduling/*.go (@s-ito-ts)
- [x] test/e2e/auth/*.go (https://github.com/kubernetes/kubernetes/pull/81987)
- [x] test/e2e/windows/*.go (https://github.com/kubernetes/kubernetes/pull/81987)
- [x] test/e2e/kubectl/*.go (https://github.com/kubernetes/kubernetes/pull/81987)
- [x] test/e2e/scalability/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81985)
- [x] test/e2e/cloud/nodes.go (@carlory https://github.com/kubernetes/kubernetes/pull/81985)
- [x] test/e2e/lifecycle/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81980)
- [x] test/e2e/servicecatalog/podpreset.go (@carlory https://github.com/kubernetes/kubernetes/pull/81980)
- [x] test/e2e/ui/dashboard.go (@carlory https://github.com/kubernetes/kubernetes/pull/81980)
- [x] test/e2e/storage/drivers/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81983)
- [x] test/e2e/storage/testsuites/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81983)
- [x] test/e2e/storage/vsphere/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81983)
- [x] test/e2e/storage/*.go (@carlor https://github.com/kubernetes/kubernetes/pull/81983)
- [x] test/e2e/storage/utils/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81983)
- [x] test/e2e/autoscaling/*.go (@carlory)
- [x] test/e2e/node/*.go (@carlory)
- [x] test/e2e/upgrades/apps/daemonsets.go (@carlory)
- [x] test/e2e/upgrades/*.go (@carlory)
- [x] test/e2e/upgrades/storage/persistent_volumes.go (@carlory)
- [x] test/e2e_kubeadm/*.go (@SataQiu https://github.com/kubernetes/kubernetes/pull/81925)
- [x] test/e2e_node/*.go (@carlory https://github.com/kubernetes/kubernetes/pull/81974)
- [x] test/e2e/examples.go (@carlory https://github.com/kubernetes/kubernetes/pull/81974)
- [x] test/e2e/gke_local_ssd.go (@carlory https://github.com/kubernetes/kubernetes/pull/81974)
- [x] test/utils/crd/crd_util.go (@carlory https://github.com/kubernetes/kubernetes/pull/81974)

/kind cleanup
/sig testing

**Comment by oomichi** [comment]
temporary closing this issue for making consensus before doing this.

**Comment by oomichi** [comment]
https://github.com/kubernetes/kubernetes/pull/81426 has been merged, so we can start this work.

**Comment by oomichi** [comment]
I am working for `test/e2e/framework/*` for removing the invalid dependency of the test framework.

**Comment by alejandrox1** [comment]
Logging this from a slack conversation, https://kubernetes.slack.com/archives/C9NK9KFFW/p1566333353129800?thread_ts=1566323033.124200&cid=C9NK9KFFW:

> The thing is that we still need to refactor all the *_util.go files from the framework and importing logging methods from the framework can cause circular dependencies (e2epkg import framework for error and logging but framework imports e2epkg).
May be a good place to start would be to use e2elog for refactoring pkgs inside of the framework and use framework.Logf for everything else outside of the framework?

/cc @oomichi @andrewsykim @timothysc 
/cc

**Comment by oomichi** [comment]
@alejandrox1  Thanks for bring it up here.

> May be a good place to start would be to use e2elog for refactoring pkgs inside of the framework and use framework.Logf for everything else outside of the framework?

That is a nice idea, big +1 :-)

**Comment by oomichi** [comment]
The bot've removed the label `kind/bug` today, why it blames me now :-(

`@oomichi: Those labels are not set on the issue: kind/bug`

/kind bug

**Comment by alejandrox1** [comment]
> The bot've removed the label `kind/bug` today, why it blames me now :-(
> 
> `@oomichi: Those labels are not set on the issue: kind/bug`
> 
> /kind bug

I think it may be because you added the following to the issue
> /remove-kind bug

the robot keeps on trying to remove the `/kind bug` label.
Delete it from the beginning may also help if the bot keeps on doing it :sweat_smile:

**Comment by oomichi** [comment]
Ah, I got it. Thanks.
Yeah the bot should blame me (^_^;)

**Comment by alejandrox1** [comment]
Forgot to add this for discoverability
/area e2e-test-framework

**Comment by k-toyoda-pi** [comment]
I will work on ```test/e2e/apps/*.go```

**Comment by SataQiu** [comment]
`test/e2e_kubeadm/*` fixed by #81925

**Comment by s-ito-ts** [comment]
I will work on test/e2e/scheduling/*.go

**Comment by carlory** [comment]
I will pick up

```
test/utils/crd/crd_util.go
test/e2e/gke_local_ssd.go
test/e2e/examples.go
test/e2e_node/*.go
```

**Comment by carlory** [comment]
I will pick up

```
test/e2e/autoscaling/*.go
test/e2e/node/*.go
test/e2e/upgrades/apps/daemonsets.go
test/e2e/upgrades/*.go
```

**Comment by carlory** [comment]
@oomichi Sorry,  `test/e2e/node/*.go` is also in the pr #81974. It is my mistake. I will update my task list.

Can you assign `test/e2e/upgrades/storage/persistent_volumes.go` to me? I will fix it together in the next pr.

**Comment by carlory** [comment]
I will pick up

```
 test/e2e/storage/drivers/*.go
  test/e2e/storage/testsuites/*.go
  test/e2e/storage/vsphere/*.go
  test/e2e/storage/*.go
  test/e2e/storage/utils/*.go
```

and

```
  test/e2e/lifecycle/*.go
  test/e2e/servicecatalog/podpreset.go
  test/e2e/ui/dashboard.go
```

**Comment by hwdef** [comment]
I will pick up 
```
test/e2e/network/*.go
```

**Comment by carlory** [comment]
working on 

```
test/e2e/scalability/*.go
test/e2e/cloud/nodes.go
```

and

```
test/e2e/auth/*.go
test/e2e/windows/*.go
test/e2e/kubectl/*.go
```

**Comment by tanjunchen** [comment]
I will pick up  test/e2e/common/*.go

**Comment by hwdef** [comment]
I will pick up 
```
test/e2e/apimachinery/*.go
test/e2e/gke_node_pools.go
test/e2e/instrumentation/monitoring/*.go
test/e2e/instrumentation/logging/*.go
```

**Comment by Zhuzhenghao** [comment]
I will pick up 
```
test/e2e/framework/pods.go (@oomichi #81809)
test/e2e/framework/deployment/*.go (@oomichi #81811)
test/e2e/framework/endpoints/ports.go (@oomichi #81811)
test/e2e/framework/ingress/ingress_utils.go (@oomichi #81811)
```

**Comment by oomichi** [comment]
Solving `test/e2e/framework/metrics/*.go (@oomichi Need to solve circular dependencies)`

Core framework files which use e2ekubelet:
- flake_reporting_util.go: e2emetrics.PrettyPrintJSON(f)
- framework.go: e2emetrics.Collection, e2emetrics.NewMetricsGrabber, e2emetrics.ComponentCollection
- log_size_monitoring.go: e2emetrics.PrettyPrintJSON
- resource_usage_gatherer.go: e2emetrics.PrettyPrintJSON
- suites.go: e2emetrics.NewMetricsGrabber, e2emetrics.ComponentCollection
- util.go: e2emetrics.HighLatencyKubeletOperations

**Comment by oomichi** [comment]
Solving `test/e2e/framework/node/*.go (@oomichi Need to solve circular dependencies)`

- networking_utils.go: e2enode.FirstAddress, e2enode.GetExternalIP, e2enode.WaitConditionToBe
- nodes_util.go: e2enode.TotalRegistered, e2enode.CheckReady
- util.go: e2enode.IsConditionSetAsExpected, e2enode.IsConditionUnset, e2enode.IsConditionSetAsExpectedSilent, e2enode.Filter,

**Comment by hwdef** [comment]
@oomichi 
Please this issue,I accidentally closed it.
Sorry about it.

**Comment by oomichi** [comment]
test/e2e/framework/kubelet
----------------------------

```
resource_usage_gatherer.go:	e2ekubelet "k8s.io/kubernetes/test/e2e/framework/kubelet"
util.go:	e2ekubelet "k8s.io/kubernetes/test/e2e/framework/kubelet"
```

**Comment by k-toyoda-pi** [comment]
I created PR for `storage/testsuites/topology.go`
The file was created after previous commit #81983 was merged.

**Comment by k-toyoda-pi** [comment]
@oomichi I created new PR for log function. Could you review it at your convenience? Thanks.

**Comment by spiffxp** [comment]
@oomichi is this still relevant? I don't have the bandwidth to shepherd this as help-wanted and am considering /remove-help
