### ISSUE TITLE
Propose a cleanup extension point to the scheduling framework

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#81438]
/sig scheduling
/priority important-soon
/assign

**Why is this needed**:

The scheduling framework plugin could save pod related states in some extension points and used in others, ex:

1. [Save](https://github.com/kubernetes/kubernetes/pull/80898/files#diff-f58124514ebdc62aefca3f447c95bdadR59-R60) the pod to podAffinityPriorityMap in the Score extension point 
2. [Use](https://github.com/kubernetes/kubernetes/pull/80898/files#diff-f58124514ebdc62aefca3f447c95bdadR157-R160) and [delete](https://github.com/kubernetes/kubernetes/pull/80898/files#diff-f58124514ebdc62aefca3f447c95bdadR191) the map in the Normalize Score extension point.

If nothing goes wrong, the plugin would save, use and delete as usual. However, if the other score plugins return an `Error` status, the generic scheduler would return immediately without any callback to the plugin.

We could meet one of these problems:

1. If the pod was deleted and never scheduled again, the `podAffinityPriorityMap` will be saved in the plugin forever.
2. If the scheduler schedules the pod again, the plugin will use the data calculated in the last time. Though we could use a hack for this, ex: check whether the data was initialized before, if it was, delete the original data and initialize a new one, it does not sound like a good idea.

These problems happen because of:

1. There is no cleanup phase which notifies the plugin of the scheduling result (success or failure).
2. Scheduling the same pod could be a different scheduling process, the same extension point of the plugin could be called with multiple times with the same pod.

**What would you like to be added**:

We could solve these problems through the following approaches.

1. Introducing a new cleanup phase to the plugin which would be called once after a successful or failed scheduling.

```go
type CleanupPlugin interface {
	Plugin
	Cleanup(pc *PluginContext, p *v1.Pod)
}
```

2. Add a `cleanup` method to the `Plugin` interface

```go
type Plugin interface {
	Name() string
	Cleanup(pc *PluginContext, p *v1.Pod)
}
```

cc/ @bsalamat @Huang-Wei @ahg-g

**Comment by hex108** [comment]
> We could meet one of these problems:

> If the pod was deleted and never scheduled again, the podAffinityPriorityMap will be saved in the plugin forever.
If the scheduler schedules the pod again, the plugin will use the data calculated in the last time. Though we could use a hack for this, ex: check whether the data was initialized before, if it was, delete the original data and initialize a new one, it does not sound like a good idea.

Not sure I understand it correctly, I think plugins should run with initialized data for each schedule cycle,  and should not keep data across each cycle, then there will be no problem?

**Comment by liu-cong** [comment]
I am afraid I don't fully understand the problem.  Are you saying that some plugins may maintain an internal state and the state needs to be cleaned up? Can we design the plugins to be stateless?

**Comment by draveness** [comment]
> Not sure I understand it correctly, I think plugins should run with initialized data for each schedule cycle, and should not keep data across each cycle, then there will be no problem?
>
> I am afraid I don't fully understand the problem. Are you saying that some plugins may maintain an internal state and the state needs to be cleaned up? Can we design the plugins to be stateless?

@hex108 @liu-cong We **could** design the plugins to be stateless, but I don't think it should be the only option. And in fact, we have an [example](https://github.com/kubernetes/kubernetes/blob/bc1d8c6d61078269540f807248a455cba09e672c/pkg/scheduler/framework/plugins/examples/stateful/stateful.go#L32-L78) of a stateful plugin, and as bobby mentioned before - score plugin could keep whatever internal state as it wants to calculate the priority.

Besides, there are two cycles in the scheduling framework, in a binding cycle:

+ if it is aborted, it will trigger the un-reserve phase.
+ if it is successful, it will trigger the post-bind phase.

However, we don't have such a thing in the scheduling cycle. If the scheduling cycle is accidentally aborted, we can't get a callback in the plugin.

Use plugin context to pass the data through extension point could be an alternative (e.g. alloc the data structure in post-filter and store it in the plugin context). As data stores in the `PluginContext` can be read, altered, or deleted by another plugin, and there is a possibility that different plugin could use the same key, if the data is only used inside the plugin, an internal state is preferred here IMO.

> // PluginContext provides a mechanism for plugins to store and retrieve arbitrary data.
// ContextData stored by one plugin can be read, altered, or deleted by another plugin.
// PluginContext does not provide any data protection, as all plugins are assumed to be
// trusted.

**Comment by liu-cong** [comment]
Thanks @draveness for the explanation.
> 
> 1. Introducing a new cleanup phase to the plugin which would be called once after a successful or failed scheduling.
> 
> ```go
> type CleanupPlugin interface {
> 	Plugin
> 	Cleanup(pc *PluginContext, p *v1.Pod)
> }
> ```
Pros:  Only stateful plugins need to implement this extension point.
Cons: Admin needs to also configure Cleanup PluginSet in the config. This could be error prone if not configured properly.

> 1. Add a `cleanup` method to the `Plugin` interface
> 
> ```go
> type Plugin interface {
> 	Name() string
> 	Cleanup(pc *PluginContext, p *v1.Pod)
> }
> ```
Pros: No added complexity for scheduler admin.
Cons: Adds complexity for plugin developers. Now they have to implement `Cleanup` even it's a noop.

Maybe we can come up with an approach without adding too much complexity. e.g., for Option 1, instead of adding CleanupPlugin explicitly in the config, we can instead check for every plugin to see if it implements the Cleanup extension point and run it if it does. This makes `Cleanup` a somewhat special extension point where we don't allow enabling/disabling through config ,similar to NormalizeScore.

**Comment by liu-cong** [comment]
Thinking a bit more about this. I think the problem isn't related whether the plugin is stateful or not, it's about whether the plugin can maintain a valid state for each scheduling cycle.

Can the plugin make sure its state is fresh for every scheduling cycle? Are we losing performance by initializing the state each time? If so, how can the Cleanup approach solve it?

**Comment by draveness** [comment]
The intention of the second option you provided is good, but the cleanup plugin is only called when the scheduling cycle is completed, we have two cycles running separately in the scheduling framework, it could be weird if a plugin which only cares about the binding cycle should implements `Cleanup`.

>  for Option 1, instead of adding CleanupPlugin explicitly in the config, we can instead check for every plugin to see if it implements the Cleanup extension point and run it if it does. 

This seems like a reasonable approach, but it also adds a convention to the scheduling framework which could make it little confused for the developer who uses it.

**Comment by draveness** [comment]
> Thinking a bit more about this. I think the problem isn't related whether the plugin is stateful or not, it's about whether the plugin can maintain a valid state for each scheduling cycle.

Think about the case:

1. The scheduler schedules a new pod, and we initialize the state (used to do some calculation cross extension points) in let's say post-filter extension point.
2. In the score extension point, some plugins abort the scheduling cycle, and the following extension points for the pod never got executed.
3. The developer deletes the pod

The state we initialized in the plugin for the pod could stay forever in the memory because we don't get any callback from the scheduler and the pod would never be rescheduled again (has already been deleted). At this point, I don't think the plugin is in a valid state because of the memory leak.

**Comment by draveness** [comment]
> Can the plugin make sure its state is fresh for every scheduling cycle? Are we losing performance by initializing the state each time? If so, how can the Cleanup approach solve it?

I think we could make the state fresh since we ran the scheduling cycle for each pod serially, we could override the previous state at post-filter extension point or even earlier. But the developers need to understand some about the underlying implementation of the scheduling framework.

**Comment by ahg-g** [comment]
> > Can the plugin make sure its state is fresh for every scheduling cycle? Are we losing performance by initializing the state each time? If so, how can the Cleanup approach solve it?
> 
> I think we could make the state fresh since we ran the scheduling cycle for each pod serially, we could override the previous state at post-filter extension point or even earlier. But the developers need to understand some about the underlying implementation of the scheduling framework which could make it harder to use.

using pre-filter as the extension point to freshen up the state is what I suggested to Cong as well in an offline discussion. I don't think it is confusing, developers need to be aware of the plugins call sequence anyways, we document that: https://kubernetes.io/docs/concepts/configuration/scheduling-framework/

**Comment by liu-cong** [comment]
Instead of tying the cleanup in a specific extension point, can we generalize it to be the extension point where the state is created? In Draven's example, if podAffinity only needs Score and NormalizeScore extension points, then it should make sure to cleanup/refresh the podAffinityPriorityMap where the map is created (in the Score extension point).

**Comment by draveness** [comment]
> in the Score extension point

We should initialize the map in the post-filter phase, I'll update the PR to reflect the change.
