### ISSUE TITLE
Support dynamic cpu limit for burstable services ?

### ISSUE THREAD

**Issue by saiwl** [kubernetes/kubernetes#81446]
**What would you like to be added**:
Can kubelet support config cpu limit dynamicly without pod restart? Just a simple advice without specific proposals.

**Why is this needed**:
I personally think this is useful for some burstable services of low QoS such as offline workers. We usually want to make them run slowly rather than killing them when when face resource shortage. Just for burstable services, not the guarantees.

**Comment by mattjmcnaughton** [comment]
Hi @saiwl :)

Take a look at https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-burstable and let me know if you think it could support your use case.

**Comment by saiwl** [comment]
Thanks for replying! I read the instructions, but it seems not to be what we need. Here are our two typical scenarios：
1、Some services has high cpu usage peaks which will only last for a few seconds or shorter. If they request CPU by the usage peak，there may be a lot resource waste. So we usually set them burstable. The limits cannot be setted too low because of the cpu usage peaks, otherwise the P95/P99 will be influenced. Usually this works well, because the cpu peaks comes at random time. However when some services go wrong and take a lot of cpu for a long time, which leads to a bad situation. So I guess when burstable services 'burst' too much for a relatively long time, if kubelet can punish them by setting their limits lower dynamically.
2、When there comes to resource shortage, we sometimes prefer to lower the running speed rather than killing some burstable services directly. 
I'm not sure if I have expressed explicitly. Thank you for reading!

**Comment by mattjmcnaughton** [comment]
One additional option you have is that - instead of trying to add this behavior directly to k8s - you could write a controller which monitors the appropriate k8s api endpoints and dynamically updates your pod cpu limits accordingly? The advantage of this approach is that it would free you from k8s release cycles and getting community consensus on your approval - i.e. it might result in you having the feature you desire faster :)

**Comment by saiwl** [comment]
We have the plan to do this, just want to know if the k8s team has the plan to support this feature.Thank you for your advice! 
I will close this issue. Thank you!
