### ISSUE TITLE
should DevicePlugin pluginapi.AllocateRequest add pod info and container info

### ISSUE THREAD

**Issue by davidstack** [kubernetes/kubernetes#81442]
**What would you like to be added**:
when kubelet call deviceplugin api Allocate,add pod info and container info paramerent, such as

`type AllocateRequest struct {
        Pod  *v1.Pod
       Container Container
	ContainerRequests []*ContainerAllocateRequest 
}

` 

**Why is this needed**:
in machine learning, when schedule GPU for Pod, because of NUMA info,user may want to select GPU ID on the node,one pod should use the GPU in same NUMA . when we use custom schedule to select GPU ID ,and add this information in Pod annoation, but now DevicePlugin can not find which pod or which container use this device.
if we can add pod info in AllocateRequest ,then deviceplugin can select the right pod from k8s,and then ,make the right GPU env for this pod

**Comment by davidstack** [comment]
/sig scalability  /sig Architecture /sig Machine Learning /sig Machine Learning /sig Node /sig Scheduling

**Comment by wgliang** [comment]
This seems to need to start with [KEP](https://github.com/kubernetes/enhancements).

**Comment by davidstack** [comment]
move this issue to [KEP #1215 ](https://github.com/kubernetes/enhancements/issues/1215)

**Comment by davidstack** [comment]
@wgliang  thanks, i will close this issue and move to KEP
