### ISSUE TITLE
garbage collect dead containers that have exited for a very long time

### ISSUE THREAD

**Issue by Dieken** [kubernetes/kubernetes#81451]
**What would you like to be added**:
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#container-collection

Currently container garbage collection doesn't consider exit time of dead containers,  there are many dead containers that exited some months ago on our production kubernetes clusters.

**Why is this needed**:

These dead containers interfere our log collector, and they occupy a lot of disk space,  it's better to delete too old dead containers.

@kubernetes/sig-node-feature-requests  @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by mattjmcnaughton** [comment]
Hi @Dieken 

Thanks for sharing your issue. To be sure I'm understanding, is the issue that no garbage collection of dead container is occurring? Or is it that specific containers that you'd expect to be garbage collected are not being garbage collected? Any logs you can share would be great.

From reading the link you posted, it does appear that k8s considers the age of containers when deciding what to garbage collection.

One question I had - do you know your value for the following are:

```
    image-gc-high-threshold, the percent of disk usage which triggers image garbage collection. Default is 85%.
    image-gc-low-threshold, the percent of disk usage to which image garbage collection attempts to free. Default is 80%.
```

**Comment by SataQiu** [comment]
Maybe we should add a new flag `--container-maximum-surviving-age`. If the container lives longer than this threshold, clean it up. @Dieken

**Comment by Dieken** [comment]
@mattjmcnaughton 

Those two settings are for image gc, not container gc.

This issue is a feature request, not a bug report,  currently k8s container gc works correctly,  we have many pods that each has exactly one long dead container,  this doesn't violate maximum-dead-containers-per-container=1,  but those containers have exited for *many months*,  they should be automatically removed because they are not useful any more for debug.

I agree with @SataQiu ,  but a little change to the flag name to make it more clear,  `--container-maxium-dead-age`,  if the container has exited longer than this threshold, clean it up.

**Comment by mattjmcnaughton** [comment]
Whoops, you're right @Dieken :)

One other question... would setting `--maximum-dead-containers-per-container=0` work? Or do you want to retain them for some team (but not indefinite)?

**Comment by Dieken** [comment]
> Whoops, you're right @Dieken :)
> 
> One other question... would setting `--maximum-dead-containers-per-container=0` work? Or do you want to retain them for some team (but not indefinite)?

Yes, I would like maximum-dead-containers-per-container=1 to retain dead container a while for debug, if it’s zero, I’m afraid it will be gc-ed too soon.

**Comment by mattjmcnaughton** [comment]
On Fri, Aug 16, 2019 at 04:23:46PM -0700, Liu Yubao wrote:
> > Whoops, you're right @Dieken :)
> > 
> > One other question... would setting `--maximum-dead-containers-per-container=0` work? Or do you want to retain them for some team (but not indefinite)?
> 
> Yes, I would like maximum-dead-containers-per-container=1 to retain dead container a while for debug, if it’s zero, I’m afraid it will be gc-ed too soon.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/81451#issuecomment-522179722

I responded in the PR opened about I way that (I think) we could accomplish your
goal without adding new flags. Let's chat there :)

**Comment by SataQiu** [comment]
I think there's a scenario that doesn't work with existing flags: I want to keep as many dead containers as possible, but too old dead containers don't make sense to me, and I'd like to delete containers that have been dead for more than a month。

**Comment by dashpole** [comment]
/cc

> These dead containers interfere our log collector

Can you explain this some more?  Why would exited containers impact a log collector?

Disk space management in the kubelet is currently lazy.  We generally only reclaim it when it gets close to being full.  Leaving containers on disk means that they can be inspected, e.g. for logs.

**Comment by SataQiu** [comment]
Perhaps your intention is to focus only on recent logs ? @Dieken
The redundant logs not only take up disk space, but also put pressure on log analysis.

**Comment by Dieken** [comment]
@dashpole  

@SataQiu is right, I want to collect only recent stdout logs by watching docker daemon’s CONTAINER_ID/CONTAINER_ID-json.log files, originally my log collector has a bug, it thought a pod that declared only one container in YAML would correspond to one container at runtime, but actually it may have two, one dead, one live, unluckily my log collector sometimes watched the dead container’s log files, it wouldn’t pick new live container’s log because the dead container was kept for several months!

I fixed the bug of my stupid log collector by always picking latest container log files,  but it’s annoying those dead containers were kept as long as their replacement containers don’t exit, that means months or even quarters! It indeed  interferes with logging and debugging.

**Comment by Dieken** [comment]
I use `/var/log/containers/<pod_name>_<pod_namespace>_<container_name>-<container_id>.log` to get `container_id` and directly collect `/var/lib/docker/containers/CONTAINER_ID/CONTAINER_ID-json.log`.

I checked `/var/log/pods/<podUID>/<containerName>/<instance#>.log`,  it's indeed better that I don't have to the details of container runtime,  thanks!

Well, back to the topic, about those "long lived dead containers", I still hope a new parameter to delete them if they died too long, current parameters can't achieve that,  see the discussion above and in PR #81473.

**Comment by Dieken** [comment]
> I'm still trying to figure out the motivation behind your change. Why are "long lived dead containers" a problem?

@dashpole  They occupy disk space, interfere with log collection and debugging, may slow down  docker to scan container list.

Let's think on the other side, what's the point to keep dead containers for several weeks, months or even years? This can indeed happen with current container gc settings as discussed above.

**Comment by dashpole** [comment]
As stated above, this allows them to be inspected even after they are in a terminated state.  If users want the dead containers to be deleted, they are free to delete the pod that is in the failed state.

Occupying disk space isn't a downside unless the kubelet doesn't reclaim it when it is by pods.
It doesn't appear to interfere with log collection based on our discussion above.
Do you have any benchmarks to demonstrate the performance impact of a dead container on docker container list scanning?  I don't have enough knowledge of the internals of docker/containerd to reason about how expensive it would be.

**Comment by Dieken** [comment]
I'm not sure whether you have read the issue description,  will you inspect a dead container that exited several months ago?

Of course I can do GC it myself, I can do log collection myself too,  what's the benefit to kubernetes project and community?

It's lucky I keep using as few features of kubernetes as possible.

@SataQiu Thank you very much for your time to contribute the patch, let's not waste more time.
