### ISSUE TITLE
Add context name to output when using kubectl calls

### ISSUE THREAD

**Issue by bdelsaz** [kubernetes/kubernetes#81459]
Hi all,
It would be useful to have the context name included when performing kubectl calls. 
Below an example of what I mean:
![image](https://user-images.githubusercontent.com/46991222/63079905-ee196f80-bf3f-11e9-8aee-8ccfe200a0ff.png)

I think this would be an useful feature for folks who work with multiple contexts on the console. Sometimes it is way too easy to perform an action in the wrong context, since there seens to be no visual feedback.

Edit: hope I put the right label: 
@kubernetes/sig-cli-maintainers
/sig cli

**Comment by deiga** [comment]
I really like this idea. I wonder what it would take to start this.

**Comment by deiga** [comment]
This would require design work to figure out that the best positioning for this information would be.
I don't think the place you highlighted would be the best place as it could confuse people what "NAME - MY PROD CLUSTER" would mean.

I would rather suggest printing the context information before the table, but then we have 1 additional row before content starts. Which ist also not ideal
