### ISSUE TITLE
Override NLB health check values based on annotations

### ISSUE THREAD

**Issue by krish7919** [kubernetes/kubernetes#81469]
**What happened**:
Please refer: https://github.com/kubernetes/cloud-provider-aws/issues/51

I set the proper annotations, as per the documentation in Kubernetes, to the service of `type: LoadBalancer`  using an AWS NLB:

```
service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "30"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
```

However, these settings do not have any effect on the code as per the code [here](https://github.com/kubernetes/cloud-provider-aws/blob/8f6e1e3d2cfa20a0deac088b9c4022d433500369/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L390-L400):

```
                  input := &elbv2.CreateTargetGroupInput{
			VpcId:                      aws.String(vpcID),
			Name:                       aws.String(name),
			Port:                       aws.Int64(mapping.TrafficPort),
			Protocol:                   aws.String("TCP"),
			TargetType:                 aws.String("instance"),
			HealthCheckIntervalSeconds: aws.Int64(30),
			HealthCheckPort:            aws.String("traffic-port"),
			HealthCheckProtocol:        aws.String("TCP"),
			HealthyThresholdCount:      aws.Int64(3),
			UnhealthyThresholdCount:    aws.Int64(3),
		}
```

**What you expected to happen**:
The configured settings should supersede the default settings.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service of `type: LoadBalancer` with an NLB in AWS and check the Health Check configured in AWS.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.9
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by krish7919** [comment]
@kubernetes/sig-aws

**Comment by krish7919** [comment]
Would a PR help here?

And can it be backported to v1.11.9 which is being used by EKS?

**Comment by krish7919** [comment]
Any updates? @zegl?

**Comment by krish7919** [comment]
@kubernetes/sig-aws-bugs

**Comment by krish7919** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/73362

**Comment by selslack** [comment]
@zegl any updates?

**Comment by krish7919** [comment]
I can send a PR if one can let me know if this will be merged.

**Comment by galindro** [comment]
@krish7919 would be nice to include an option to set the health check path. I could not find a way to do that...

**Comment by yosefrow** [comment]
@galindro apparently you can set healthcheck path via 'healthchecks: /health/check/path` annotation in the service.yaml manifest for classic LB. maybe it works for nlb too. Didn't find a way to choose a port though

**Comment by krish7919** [comment]
Is there an update on this?

**Comment by mailjunze** [comment]
> @krish7919 would be nice to include an option to set the health check path. I could not find a way to do that...

NLB currently support only TCP health checks.

**Comment by Spareo** [comment]
> > @krish7919 would be nice to include an option to set the health check path. I could not find a way to do that...
> 
> NLB currently support only TCP health checks.

Not sure this is true because if you set ExternalTrafficPolicy on the service to Local the NLB creates a health check using the http protocol. 

Note this won’t work if the service and NLB already exist.

**Comment by Spareo** [comment]
> > @krish7919 would be nice to include an option to set the health check path. I could not find a way to do that...
> 
> NLB currently support only TCP health checks.

Not sure this is true because if you set ExternalTrafficPolicy on the service to Local the NLB creates a health check using the http protocol. 

Note this won’t work if the service and NLB already exist.
