### ISSUE TITLE
The serial HPA e2e tests are too slow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#81491]
**What happened**:
The following two tests take roughly 70 minutes in ci-kubernetes-e2e-gci-gce-serial:
- `[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stability`
- `[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicaSet Should scale from 5 pods to 3 pods and from 3 to 1`
- `[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] Deployment Should scale from 5 pods to 3 pods and from 3 to 1`
- `[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] Deployment Should scale from 1 pod to 3 pods and from 3 to 5`
- `[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicaSet Should scale from 1 pod to 3 pods and from 3 to 5`

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial&include-filter-by-regex=HPA&graph-metrics=test-duration-minutes

The job currently has a 500 minute time limit, which it's been hovering close to for a while now. Kicking these five tests out would give us 70 minutes of headroom

I will admit, the 1->3,3->5 (w/o decision stability) tests are under 5min each, which isn't egregious.  But if we're going to move these tests, I think they should be moved as a batch.

**What you expected to happen**:

I think these tests should be kicked out of any jobs that execute regular serial tests, by giving them a `[Feature:foo]` tag.

They can have the tag dropped if they are re-implemented to be faster. Alternatively, if they are critical to a release going out the door, they can be run in their own feature-specific test (as is done for ingress) and proven to meet release-blocking criteria

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

ref: https://github.com/kubernetes/sig-release/issues/347#issuecomment-521845244

/area test
/sig testing
/sig release
it's your release-blocking dashboard
/sig autoscaling
it's your tests
/priority important-soon
/milestone v1.16

**Comment by spiffxp** [comment]
/remove-area kubelet
bad copy-pasta

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/81537 to add a `[Feature:foo]` tag

**Comment by MaciekPytel** [comment]
cc: @mwielgus @josephburnett

**Comment by josephburnett** [comment]
@spiffxp HPA is an important component of K8s and these tests should be release blocking.

Let's work on moving these to a separate job as a fast workaround.  Then I'll work on getting these to run faster or in parallel.

How do we go about creating a new job for these?

**Comment by spiffxp** [comment]
I would add a job that looks similar to what sig-network is doing to have their specific ingress feature tested as release-blocking:
https://github.com/kubernetes/test-infra/blob/41b0f74ec5dcbb8a1f818b82e84362bbaa7ee4f6/config/jobs/kubernetes/sig-network/sig-network-misc.yaml#L208-L236

You can either update https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-autoscaling/sig-autoscaling-config.yaml or make a new file

Per https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md#promoting-or-demoting-jobs make sure you get sign off from the release team (ie: @lachie83 as lead, @alejandrox1  as ci signal).  Ordinarily I would ask that new jobs be placed on release-informing first, so we can gather data about them.  I'm OK making an exception for new jobs that represent splits from existing release-blocking jobs if they are.

**Comment by josephburnett** [comment]
I've added a job to sig-autoscaling: https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gce-cos-autoscaling-hpa-cpu  

But it isn't selecting any tests.
```
I0821 12:57:34.254] Running Suite: Kubernetes e2e suite
I0821 12:57:34.255] ===================================
I0821 12:57:34.255] Random Seed: 1566392252 - Will randomize all specs
I0821 12:57:34.255] Will run 0 of 4413 specs
```

**Comment by josephburnett** [comment]
@spiffxp do we need to rebuild the e2e test image to pick up #81537?

**Comment by tweks** [comment]
@spiffxp, following up on this - is there anything else to be done on our side?

**Comment by tweks** [comment]
Hey. We took a look with @jbartosik today. The job is not selecting any tests, because it is extracting tests from 1.15 [1] and 1.15 still uses [HPA] tag: [2].

The solution will be to change HPA test config to `--extract=ci/latest` instead `ci/k8s-stable1`: [3], exactly the same as other tests are configured. I'll do that in a moment.

No changes are planned in release-1.16 branch (it's only a change in test-infra repository), so I hope it does not collide with v1.16 code freeze.

[1] https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-hpa-cpu/1167052769421430787
`W0829 12:34:17.044] 2019/08/29 12:34:17 extract_k8s.go:286: U=https://storage.googleapis.com/kubernetes-release-dev/ci R=v1.15.4-beta.0.22+7b85be021cd294 get-kube.sh`

[2] https://github.com/kubernetes/kubernetes/blob/release-1.15/test/e2e/autoscaling/horizontal_pod_autoscaling.go
[3] https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-autoscaling/sig-autoscaling-config.yaml#L380

**Comment by tweks** [comment]
Verified that now job selects all CPU tests: https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gce-cos-autoscaling-hpa-cpu.

**Comment by xmudrii** [comment]
@spiffxp What is the status of this issue? Should we move it to the next milestone?

**Comment by kikisdeliveryservice** [comment]
Hi everyone,
Bug Triage Release Team checking in.  Code freeze for the 1.17 release is on November 18. Will this make it in?  Thanks!

**Comment by josiahbjorgaard** [comment]
@alejandrox1 Should this issue be moved to v1.18?

**Comment by spiffxp** [comment]
/close
If you'd like https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gce-cos-autoscaling-hpa-cpu to be considered as a release-informing or release-blocking test, please discuss with the release team
