### ISSUE TITLE
The serial regular resource usage tracking e2e tests are too slow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#81490]
**What happened**:
The following two tests take roughly 65 minutes in ci-kubernetes-e2e-gci-gce-serial:
- `[k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node`
- `[k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 0 pods per node`

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial&include-filter-by-regex=resource%20usage%20tracking&graph-metrics=test-duration-minutes&width=20

The job currently has a 500 minute time limit, which it's been hovering close to for a while now.  Kicking these two tests out would give us a fair amount of headroom

**What you expected to happen**:

I think these tests should be kicked out of any jobs that execute regular serial tests via a `[Feature:foo]` tag.

They can have the tag dropped if they are re-implemented to be faster.  Alternatively, if they are critical to a release going out the door, they can be run in their own feature-specific test (as is done for ingress)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

ref: https://github.com/kubernetes/sig-release/issues/347#issuecomment-521845244

/area test
/area kubelet
/sig testing
/sig release
it's your release-blocking dashboard
/sig node
it's your tests
/priority important-soon

**Comment by spiffxp** [comment]
Looking for historical context, putting my notes here (WIP):
- These tests live in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/kubelet_perf.go
  - https://github.com/kubernetes/kubernetes/pull/48910 is the earliest PR that touched the file under this name (rename from test/e2e/kubelet_perf)
- There is also https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/resource_usage_test.go
  - https://github.com/kubernetes/kubernetes/pull/29764 is earliest PR that touches the file under this name (rename from test/e2e_node/kubelet_perf_test)

**Comment by spiffxp** [comment]
/assign @yujuhong 
as someone who shows up in the history for these tests a fair amount

**Comment by spiffxp** [comment]
The tests mention deprecation once a soak cluster is available for them https://github.com/kubernetes/kubernetes/issues/36621

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/81535 to add a `[Feature:foo]` tag

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/81535#issuecomment-522191164 - next step, include these in soak tests

**Comment by xmudrii** [comment]
@spiffxp Is this something we are still targeting for 1.16 or can we move it to 1.17?

**Comment by kikisdeliveryservice** [comment]
Hi @spiffxp @alejandrox1 @yujuhong !

Bug Triage Release Team checking in.  Code freeze for the 1.17 release is on November 18. Will this make it in?  Thanks!

**Comment by kikisdeliveryservice** [comment]
Hi @spiffxp @alejandrox1 @yujuhong,

Is this still a 1.17 target or can we move it to 1.18?  Code Freeze is Nov. 14th.

Thanks!
