### ISSUE TITLE
Proposal: Use context throughout kubernetes

### ISSUE THREAD

**Issue by pnasrat** [kubernetes/kubernetes#815]
In an ideal world we need a way to seamlessly carry trace, debugging, cancellation and other data across boundaries - whether that be process, goroutine or RPC.

The code.google.com/p/go.net/context package provides wiring to do this.
References http://blog.golang.org/context

I'd like to wire this into kubernetes, but want blessing before going off and doing it. If you think this would be of value let me know and I'll send a PR.

**Comment by brendandburns** [comment]
go 1.7 introduces context into the HTTP libs as well as the httptrace library, we should re-consider this in light of those additions.

https://golang.org/doc/go1.7#context

**Comment by smarterclayton** [comment]
I agree, we should wire context (as is) into more places.  Storage did it for the etcd3 work.

I don't know that we've resolved the "acting-as" wrinkles with controllers in a coherent way where the context would be related to the end user.

**Comment by bgrant0607** [comment]
There's also OpenTracing.

http://opentracing.io/

**Comment by ash2k** [comment]
It would be useful to add context to all client methods. Also a lot of places use `stopCh <-chan struct{}` and context could be used there instead.

**Comment by odeke-em** [comment]
How's it going here?
```go
import (
   "context"
)
```
"context" is now mainstream for Go1.7, Go1.8 and soon Go1.9.

**Comment by MadhavJivrajani** [comment]
/remove-kind design
/kind feature

`kind/design` will soon be removed from `k/k` in favor of `kind/feature`. Relevant discussion can be found here: https://github.com/kubernetes/community/issues/5641

**Comment by thockin** [comment]
I'm not sure that keeping this open as an issue is useful any more?
