### ISSUE TITLE
Investigate golangci-lint to simplify our verify-* scripts

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#81518]
A lot of our go verification scripts are included in [golangci-lint](https://github.com/golangci/golangci-lint), which is designed to aggregate the tools for CI. It looks like the following are included:

- govet
- golint
- gofmt
- misspell
- staticcheck (https://github.com/kubernetes/kubernetes/pull/81189)

This tool might be able to simplify our verify scripts, as it encapsulates some of the functionality. Also, by aggregating the linters it may be much faster than running each tool independently. Finally, it would make adding new linters (supported by golangci-lint) much easier.

**Comment by ericzhang08** [comment]
Hi @tallclair. Can I work on This issue?

**Comment by alejandrox1** [comment]
@ericzhang08 please feel free to work on it.
If you want to discuss any details I think #k8s-code-organization in slack may be a good place to discuss anything that comes up.

On the implementation side, it would probably be easier to go one by one.
[./hack/verify-govet.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-govet.sh) might be a good place to start.
[./hack/verify-spelling.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh) would be a good second step.

**Comment by andrewsykim** [comment]
ping @ericzhang08, any updates on this?

**Comment by ericzhang08** [comment]
@andrewsykim  I am sorry to forget to finish this issue. I have unassigned this issue.

**Comment by BenTheElder** [comment]
@dims actually has a WIP PR related to this

**Comment by tallclair** [comment]
/remove-lifecycle rotten

I still think this is something we should do.
