### ISSUE TITLE
When runtime imagefs mount is not on root filesystem, writable layer usage does not count toward ephemeral storage consumption

### ISSUE THREAD

**Issue by RobertKrawitz** [kubernetes/kubernetes#81523]
**What happened**: When the writable layer of a pod is not on the Kubernetes root filesystem (e. g. /var/lib/crio or /var/lib/docker is not on the Kubernetes root filesystem), it's possible to create an arbitrary amount of data without triggering eviction based on ephemeral storage limit

**What you expected to happen**: When creating 1GB of data in /tmp on a pod whose ephemeral-storage limit is 1MB, it should be evicted.

**How to reproduce it (as minimally and precisely as possible)**:

1) Ensure that /var/lib/crio or /var/lib/docker is on a different filesystem from the Kubernetes root.
2) Run the following pod:

```apiVersion: v1
kind: Pod
max:
metadata:
  name: "failpod"
spec:
  containers:
  - name: "failpod"
    image: "busybox"
    resources:
      limits:
        ephemeral-storage: "100Ki"
    command:
      - /bin/sh
      - -c
      - |
        dd if=/dev/zero of='/tmp/test.file' bs=1024 count='1000'
        sleep infinity
```

**Anything else we need to know?**: Fix is in PR 81516

**Environment**:
- Kubernetes version (use `kubectl version`): Any since late 2017
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by ahmsb8884** [comment]
> **What happened**: When the writable layer of a pod is not on the Kubernetes root filesystem (e. g. /var/lib/crio or /var/lib/docker is not on the Kubernetes root filesystem), it's possible to create an arbitrary amount of data without triggering eviction based on ephemeral storage limit
> 
> **What you expected to happen**: When creating 1GB of data in /tmp on a pod whose ephemeral-storage limit is 1MB, it should be evicted.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Ensure that /var/lib/crio or /var/lib/docker is on a different filesystem from the Kubernetes root.
> 2. Run the following pod:
> 
> ```
> kind: Pod
> max:
> metadata:
>   name: "failpod"
> spec:
>   containers:
>   - name: "failpod"
>     image: "busybox"
>     resources:
>       limits:
>         ephemeral-storage: "100Ki"
>     command:
>       - /bin/sh
>       - -c
>       - |
>         dd if=/dev/zero of='/tmp/test.file' bs=1024 count='1000'
>         sleep infinity
> ```
> 
> **Anything else we need to know?**: Fix is in PR 81516
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`): Any since late 2017
> * Cloud provider or hardware configuration: N/A
> * OS (e.g: `cat /etc/os-release`): N/A
> * Kernel (e.g. `uname -a`): N/A
> * Install tools: N/A
> * Network plugin and version (if this is a network-related bug): N/A
> * Others: N/A

Can anyone please clarify to me, what is the behavior now, am running k8s 1.13.5 In production and observing pod evictions due to pods writing too many logs and pods are getting evicted. Here, I thought we could bypass this pod evictions by making pods write to some other partition but seems like we cannot?
