### ISSUE TITLE
Too many EBS volumes mounted to a node

### ISSUE THREAD

**Issue by matthias50** [kubernetes/kubernetes#81533]
**What happened**:

Kubernetes allowed more that 40 EBS volumes to be mounted to a node in violation of the AWS recommended limit.

**What you expected to happen**:

The number of EBS volumes mounted is capped at the limit for the node type.

**How to reproduce it (as minimally and precisely as possible)**:

Mount an EBS volume to an AWS instance outside of Kubernetes. An example use case would be for a separate volume for /var/lib/docker.

Schedule a bunch of pods to the node which use PVCs.

Then this happens:

$ kubectl get  node -o json ip-10-116-2-155.eu-west-1.compute.internal | jq '.spec.providerID'
"aws:///eu-west-1a/i-<redacted>"
$ aws ec2 describe-instances --region eu-west-1 --instance-ids i-<redacted> | grep VolumeId | wc -l
43

Kubelet reports fewer volumes in use:

expr $(kubectl get node -o json <redacted_node_name> | jq -r '.status.volumesInUse' | wc -l) - 2
37

Note the subtract by 2 because the output from jq includes a line with [ and one with ]

**Anything else we need to know?**:

It looks like this is because the values for the max volumes which Kubernetes can allow to be mounted to a node are hard coded in attach_limit.go to this:

```
	// DefaultMaxEBSVolumes is the limit for volumes attached to an instance.
	// Amazon recommends no more than 40; the system root volume uses at least one.
	// See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html#linux-specific-volume-limits
	DefaultMaxEBSVolumes = 39
	// DefaultMaxEBSNitroVolumeLimit is default EBS volume limit on m5 and c5 instances
	DefaultMaxEBSNitroVolumeLimit = 25
	// AzureVolumeLimitKey stores resource name that will store volume limits for Azure
```

aws_ebs.go then uses these values but it doesn't do anything to account for volumes which might exist that kubrernetes doesn't know about.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux ip-10-121-0-226.us-west-2.compute.internal 5.2.8-1.el7.elrepo.x86_64 #1 SMP Fri Aug 9 13:40:33 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Custom bootstrap.
- Network plugin and version (if this is a network-related bug):
- Others:
Instance type: r4.8xlarge

**Comment by matthias50** [comment]
It seems like having some command line parameter to kubelet which would inform it of the number of volumes outside of its control could address this issue. Then kubelet could subtract that from the constants defined in attach_limits.go when reporting capacity for the node.

**Comment by mattjmcnaughton** [comment]
/remove-sig node
/sig storage

I think the folks on sig-storage might be better equipped to deal with this, so updating the sig label.

**Comment by gnufied** [comment]
The hardcoded values refer to older predicates but newer predicates take volume limit values from - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/awsebs/aws_ebs.go#L107 function. But even then since AWS provides no API for fetching volume limits, we basically have a table of volume limits based on instance type. 

> $ aws ec2 describe-instances --region eu-west-1 --instance-ids i- | grep VolumeId | wc -l
43

So you have at least 6 volumes attached outside k8s? That doesn't seem like an ideal situation. Beyond root and docker disk, you should not be attaching volumes outside k8s.

For now - I think the workaround that will work for you is, setting up value of `KUBE_MAX_PD_VOLS`. This is an environment variable that can be configured in the scheduler and scheduler will only schedule that many maximum number of volumes.  The value is cluster global and will apply to all the nodes.

**Comment by matthias50** [comment]
We have 5 volumes attached outside of k8s currently. I can't explain why the math comes out to 6 except perhaps we are also hitting this issuehttps://github.com/kubernetes/kubernetes/issues/73724 since we are using WaitForFirstConsumer. We will be reducing this to 1 as you suggest. However, this will still result in 2 EBS volumes, one for root and one for the additional EBS volume which we are carving into LVMs for various purposes including docker, so we would still end up with one more than the AWS recommended max.

KUBE_MAX_PD_VOLS doesn't work for us because we have a heterogeneous cluster where some instances are Nitro nodes. These can only mount 25 EBS volumes, and we can't set a global limit of 25 because we need the higher number of mounts for the non-Nitro instances.

**Comment by matthias50** [comment]
#81805
