### ISSUE TITLE
pull-kubernetes-local-e2e always fails

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#81565]
**Which jobs are failing**:
pull-kubernetes-local-e2e is failing

**Which test(s) are failing**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80547/pull-kubernetes-local-e2e/1163011106638139392/

where 14 out of 1398 tests failed.
I have run pull-kubernetes-local-e2e around 10 times in the past week.
The particular test that failed was not deterministic.

**Since when has it been failing**:
7 days ago (Aug 10th).

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80547/pull-kubernetes-local-e2e/1163011106638139392/

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81257/pull-kubernetes-local-e2e/1162820605175664640/

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/81257/pull-kubernetes-local-e2e/1162852063370022912/build-log.txt

**Reason for failure**:
Most common symptom was:

        s: "expected pod \"pod-configmaps-306d69fc-c950-4ad6-ab44-4d818b656f0e\" success: Gave up after waiting 5m0s for pod \"pod-configmaps-306d69fc-c950-4ad6-ab44-4d818b656f0e\" to be \"success or failure\"",

**Anything else we need to know**:

**Comment by dims** [comment]
the CI job is green for a while now - https://testgrid.k8s.io/sig-testing-misc#local-up-cluster,%20master%20(dev)&width=20

/close
