### ISSUE TITLE
Unable to start server when multiple tmpfs exist

### ISSUE THREAD

**Issue by SerialVelocity** [kubernetes/kubernetes#81575]
**What happened**:
Kubelet fails to start up on CoreOS which has been PXE booted
```
Aug 18 22:40:07 hostname kubelet-wrapper[20685]: F0818 22:40:07.479501   20685 kubelet.go:1370] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 36 in cached partitions map
```

**What you expected to happen**:
Kubelet starts up successfully

**How to reproduce it (as minimally and precisely as possible)**:
Have multiple tmpfs mounts which have different major:minor pairs, e.g.:
```
root@hostname:/# cat /proc/self/mountinfo | grep tmpfs
394 278 0:6 / /dev rw,nosuid shared:21 - devtmpfs devtmpfs rw,seclabel,size=1787428k,nr_inodes=446857,mode=755
404 394 0:18 / /dev/shm rw,nosuid,nodev shared:22 - tmpfs tmpfs rw,seclabel
1328 1326 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:6 - tmpfs tmpfs ro,seclabel,mode=755
1655 278 0:67 / /tmp rw,relatime shared:687 - tmpfs tmpfs rw,seclabel
1670 278 0:20 / /run rw,nosuid,nodev shared:24 - tmpfs tmpfs rw,seclabel,mode=755
1700 278 0:36 /etc/machine-id /etc/machine-id ro,relatime shared:1 - tmpfs tmpfs rw,seclabel,mode=755
1715 278 0:36 /var/lib/kubernetes/ssl/kubelet /var/lib/kubernetes/ssl ro,relatime shared:1 - tmpfs tmpfs rw,seclabel,mode=755
1775 278 0:36 /var/lib/kubelet /var/lib/kubelet rw,relatime shared:1 - tmpfs tmpfs rw,seclabel,mode=755
1820 278 0:36 /etc/kubernetes /etc/kubernetes rw,relatime shared:1 - tmpfs tmpfs rw,seclabel,mode=755
1845 278 0:36 /etc/ssl/certs /etc/ssl/certs ro,relatime shared:1 - tmpfs tmpfs rw,seclabel,mode=755
1877 278 0:36 /etc/hosts /etc/hosts rw,relatime shared:1 - tmpfs tmpfs rw,seclabel,mode=755
```

**Anything else we need to know?**:
[A PR to enable tmpfs in cadvisor was merged in 2017](https://github.com/google/cadvisor/pull/1667) (CC @dashpole @dims) which didn't deal with this edge case. 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.2 (using hyperkube in rkt)
- Cloud provider or hardware configuration: Bare-metal, booted over PXE
- OS (e.g: `cat /etc/os-release`): CoreOS 2135.6.0
- Kernel (e.g. `uname -a`): Linux 4.19.56-coreos-r1
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by SerialVelocity** [comment]
@kubernetes/sig-node-bugs

**Comment by zouyee** [comment]
Because you mounted `/etc/machine-id` `/var/lib/kubernetes/ssl/kubelet` `/var/lib/kubelet` under the same peer group ( ID: 1), these mount points owns same `major:minor`.

**Comment by SerialVelocity** [comment]
/remove-lifecycle stale

@zouyee Any update on this? I saw the PR went up against cadvisor but hasn't been touched in a couple of months.

**Comment by dashpole** [comment]
Sorry, that is my bad.  I finished my review of the cAdvisor PR.

**Comment by zouyee** [comment]
Is the corresponding cadvisor cut a new branch before the 1.17 is released? @dashpole

**Comment by dashpole** [comment]
I don't know if we will make the 1.17.0 release.  I'll see if I can get to it tomorrow.

**Comment by SerialVelocity** [comment]
Thanks @zouyee and @dashpole!
