### ISSUE TITLE
AWS NLB: support for access log annotations

### ISSUE THREAD

**Issue by dahu33** [kubernetes/kubernetes#81584]
**What would you like to be added**:
Add support for AWS NLB access log configuration via annotations. The same annotations currently supported by the ELB classic could be reused:
```
service.beta.kubernetes.io/aws-load-balancer-access-log-enabled
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix
```

**Comment by IngussNeilands** [comment]
Unresolved and Closed - any plans to reopen this issue?

**Comment by iusergii** [comment]
Also looking forward for this.

**Comment by betinro** [comment]
Yes, we need this. And we also need for NLB to work the following annotations:

- service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval
- service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout

**Comment by BrenemanR** [comment]
I know this issue is closed, but I'm following up to see if enabling NLB access logs via annotations is or will be supported. I'm looking to enable logs using the same annotations as in the previous comment. If this is not currently supported, what is the best way to enable the logs in the deployment? I'm looking for a way that isn't manually enabling them in the AWS console.

**Comment by rubenstolk** [comment]
Please...

**Comment by M00nF1sh** [comment]
This is already supported by https://github.com/kubernetes/kubernetes/pull/78497. 
however, there is still a known issue.
You need to create the service first and then adding these lb attributes annotations later to make it work, we'll fix it.

**Comment by TBBle** [comment]
> however, there is still a known issue.
> You need to create the service first and then adding these lb attributes annotations later to make it work, we'll fix it.

#82595 is this issue. It was accidentally closed by a related MR that didn't resolve the issue (it was fixing _health check_ annotation issues) and will hopefully be reopened soon.
