### ISSUE TITLE
HPA two downscale action cooldown time is too short

### ISSUE THREAD

**Issue by guoweikuang** [kubernetes/kubernetes#81581]
**What happened**:
I using CPU metrics to scale, when sending the downscale action, it was found that the two downscale times were too short. my cluster hpa settings is --horizontal-pod-autoscaler-downscale-stabilization=5min, two downscale action 5 min, Is this a bug or is it like this?

**What you expected to happen**:
I hope that the time for two downscale operations will be around 5 minutes(horizontal-pod-autoscaler-downscale-stabilization)

**How to reproduce it (as minimally and precisely as possible)**:
![屏幕快照 2019-08-19 下午2 09 15](https://user-images.githubusercontent.com/12684035/63243104-20063b00-c28c-11e9-8eee-bccab4dd3e4b.png)

And the hpa:
```
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: spring-boot-sample
  targetCPUUtilizationPercentage: 60
```

As seen from the above figure, the last two downscale cooldown times are less than horizontal-pod-autoscaler-downscale-stabilization

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"1.15.0", GitCommit:"cf11a44", GitTreeState:"clean", BuildDate:"2019-07-09T03:32:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
```
MacVlan network
```
- Others:

**Comment by SocietyCao** [comment]
please provide the hpa version.
 is v2beta2?

**Comment by SocietyCao** [comment]
before version 1.12,the controller manager arg is --horizontal-pod-autoscaler-downscale-**delay**.
 from 1.12 to now, --horizontal-pod-autoscaler-downscale-**stabilization** replace it,new arg does't mean  the  controller will wait 5 min between two downscales.

here are kubernetes 1.12 release log:
       Replace scale down forbidden window with scale down stabilization window. **Rather than waiting a fixed period of time between scale downs** HPA now scales down to the highest recommendation it during the scale down stabilization window. (#68122, @krzysztof-jastrzebski)

and more info url:
https://github.com/kubernetes/kubernetes/pull/68122
https://github.com/kubernetes/kubernetes/pull/67771
https://docs.google.com/document/d/1IdG3sqgCEaRV3urPLA29IDudCufD89RYCohfBPNeWIM
