### ISSUE TITLE
kube-state-metrics get metrics forbidden

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#81590]
I use scripts under https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/prometheus to install kube-state-metrics, but found that there is no metrics be collected from it, and it always output error like this, although I have config rbac for it.
I0819 10:03:47.668858       1 round_trippers.go:438] GET https://10.150.0.1:443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests?limit=500&resourceVersion=0 403 Forbidden in 0 milliseconds
E0819 10:03:47.669135       1 reflector.go:125] k8s.io/kube-state-metrics/internal/store/builder.go:295: Failed to list *v1beta1.CertificateSigningRequest: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:serviceaccount:default:kube-state-metrics" cannot list resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope

**Comment by zouyee** [comment]
/assign
@kubernetes/sig-instrumentation-bugs

**Comment by brancz** [comment]
this addon is not maintained and is about to be removed: https://github.com/kubernetes/kubernetes/pull/80351#issuecomment-522519774

**Comment by zouyee** [comment]
/uncc
This add-on is an experimental configuration, and you can use the following repos as an alternative.
[kube-state-metrics]
(https://github.com/kubernetes/kube-state-metrics/blob/master/kubernetes/kube-state-metrics-cluster-role.yaml)
[kube-prometheus](https://github.com/coreos/kube-prometheus)

**Comment by like-inspur** [comment]
I reference https://github.com/kubernetes/kubernetes/blob/5c3909e93eb6fc7d11ac4554ced962772ae82260/cluster/addons/prometheus/kube-state-metrics-rbac.yaml  and it works!
