### ISSUE TITLE
How can I use the configmap in endpoints ?

### ISSUE THREAD

**Issue by qiuwenxiang** [kubernetes/kubernetes#81597]
Hello!
    Does configmap supported in endpoints ？
    I would create a lot of endpoints which hava a same ip-value, I want to define the ip-value in configmap, and then endpoints use it.
    like :
     a1-endpoints.yaml
 ***
    -ip : 192.168.0.1 (want to define in config)
    port: 11000
***
    a2-endpoints.yaml
***
    -ip: 192.168.0.1
    port: 12000
***

Thanks!

**Comment by zouyee** [comment]
Using service instead.
