### ISSUE TITLE
hack/verify-gendocs.sh is slow

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8160]
The slowest part of every commit is waiting for hooks.  I added some printouts to find the culprit - see $SUBJECT.  Can we not run this test on every commit and rebase?

If we switched to using pre-commit instead of prepare-commit-msg we could force-override it (--no-verify) if needed.

@lavalamp

**Comment by lavalamp** [comment]
I'm OK with only running verify-gendocs.sh in travis/shippable. Honestly it only ever produces noise for me locally (when you switch branches and fail to `make clean`, it fails you for no reason). But maybe it's different if you work on the cli a lot?
