### ISSUE TITLE
FakeMount doesn't imitate Windows behavior

### ISSUE THREAD

**Issue by almos98** [kubernetes/kubernetes#81609]
**What happened**:
[FakeMounter](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/fake.go) doesn't return an error when the path already exists when running Windows tests.

**What you expected to happen**:
Expected FakeMounter to return an error if running Windows tests and trying to mount a path that already exists. In [mount_windows.go](https://github.com/kubernetes/kubernetes/blob/f4521bf5a21865738f49a1c73e6aa75200a99240/pkg/util/mount/mount_windows.go#L110), this error happens when you try to create a symlink if the path already exists.

**How to reproduce it (as minimally and precisely as possible)**:
Run Windows unit tests as done [here](https://github.com/almos98/gcp-filestore-csi-driver/blob/45ddc23ca153b06ce3f684fb6deb1d56565ab727/pkg/csi_driver/node_test.go#L209).

**Anything else we need to know?**:
FakeMount currently only imitates Linux mount behavior, which differs from Windows mount behavior. Linux mount will fail if the target path doesn’t exist and succeed if it does, but Windows is the opposite; fail when target path exists and succeed when it doesn’t.

**Comment by pjh** [comment]
cc @andyzhangx @msau42

**Comment by pjh** [comment]
cc @jingxu97

**Comment by andyzhangx** [comment]
I think that's expected, since on Linux mount, it will first create a dir and then mount that dir with the target directly, while on Windows, should make sure current dir does not exist, and then make a symlink to the target, that's different behavior.
