### ISSUE TITLE
add livenessProbe and readinessProbe for kube-proxy

### ISSUE THREAD

**Issue by KevinTHU** [kubernetes/kubernetes#81630]
**What would you like to be added**:
1. client-go distinguish the errors of 4 layer and 7 layer. like "Connection reset by peer"(4 layer) and http error from server(7 layer). [now the 4 layer is fused into 7 layer error to make response. ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L771)
2. add livenessProbe and readinessProbe for kube-proxy.

**Why is this needed**:
**for 1**, some times if the kube-proxy is not healthy, the rule of ipvs or iptables for nat lb will be wrong, and at this time, api-server may be unreachable through clusterip like 10.96.0.1, so there will be some error from add-ons(calico-node, coredns, etc.) like "**an error on the server ("") has prevented the request from succeeding**",  but by reading code, we would know that **("") here** should be the error message, but because we didn't expose 4 layer error, so ("") here is empty. for some new k8s user, it is really confusing and cause time to debug and fix. 

**for 2(when solving problem 1, I find problem 2 is also important)**, some times if api-servers don't response correct through clusterip, we would like to see whether kube-proxy is healthy by `kubectl get pods -n kube-system` (of cause `ipvsadm -ln` or `iptable -t nat -L` can show the lb rules, but for new k8s user, it is really not friendly), but no matter kube-proxy is healthy or unhealthy, it is READY always, because there is no livenessProbe or readinessProbe for kube-proxy, but in fact, if the endpoint of api-servers for kube-proxy is not right (e.g. you change the lb ip for api-servers, but forget to update ConfigMap kube-proxy and restart the Pod), the kube-proxy will be unhealthy (use `kubectl logs`, you will find lots of errors to connect api-server), so if we config  livenessProbe and readinessProbe, this will be easy to find out and we can do something to fix at the first time, and for Problem 1, it will be aslo easy to find out and fix.

**Comment by KevinTHU** [comment]
@kubernetes/sig-api-machinery @kubernetes/sig-node @kubernetes/sig-cluster-lifecycle

**Comment by rikatz** [comment]
@KevinTHU Are you willing something like kube-proxy having a healthz endpoint?

If this is the case, according to https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/ you do have, so the only thing you have to change is the DaemonSet object to run kube-proxy with the Health Check port exposed to kubelet, and liveness and readiness into this object.

About the item 1 livenessProbe supports L7 requests also (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request), so this might be helpful as when using HTTP protocol you're making a L7 probe.

**Comment by KevinTHU** [comment]
@rikatz thanks for reply, the link about healthz endpoint is really helpful, I will try to add healthcheck for kube-proxy, but maybe for kubadm it should be added as default, that will be more user-friendly. 
Another problem, for question 1, it is not aboult livenessProbe, it is about that `client-go ` package can not find out whether apiserver endpoints is not connected by 4 layer error or 7 layer. like coredns or calico, they all use `client-go` package to connect apiserver, if kube-proxy is not healthy, the ipvs for apiserver may be unwork, so `client-go` will throw an error, but you cannot easily find out whether it is  a 4 layer error(ipvs problem) or a 7 layer(http problem) by the error msg.

**Comment by rikatz** [comment]
@KevinTHU got it. I think dealing with client-go is something bigger to me so I may not help right now in this one.

About kubeadm configuring kube-proxy (and other components) with livenessProbe I'll take a look into how it's assembled and make some PR

@yagonobre any thoughts on this?

**Comment by KevinTHU** [comment]
@rikatz thanks, without modifying client-go, adding livenessProbe for kube-proxy(by kubeadm) would be helpful too, at least we could have some clue for the reason of client-go error.

**Comment by rikatz** [comment]
@KevinTHU sorry for taking so long, pretty busy here. Will take a look into this ASAP

**Comment by rikatz** [comment]
@KevinTHU I've verified here and kube-proxy is deployed by kubeadm with its healthz port enabled in port 10256

For this case, you can edit kube-proxy daemonset (``kubectl  edit daemonset -n kube-system kube-proxy``) and add the liveness and readiness checks there.

I'll anyway take a look into the options from kubeadm to make this a default, and also verify with the sig members if this is something they want into kubeadm :)

**Comment by KevinTHU** [comment]
@rikatz all right, I will add it manually first, and thanks for your help and following work, hope for a further improvement on kubeadm :)

**Comment by rikatz** [comment]
Hi @KevinTHU 

Reached the community and they pointed me to this PR: https://github.com/kubernetes/kubernetes/pull/75323

It's on hold right now, but please follow there :)
