### ISSUE TITLE
duplicate update notification when kube-apiserver restart

### ISSUE THREAD

**Issue by likakuli** [kubernetes/kubernetes#81638]
**What happened**:
Duplicate update notification event will be triggered even nothing changes when the apiserver restarted.
**What you expected to happen**:
DO NOT produce duplicate notification.
**How to reproduce it (as minimally and precisely as possible)**:
Use client-go's informer and regist an udpate event handler, then restart the apiserver.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by likakuli** [comment]
If confirmed, i can fix it.

**Comment by yue9944882** [comment]
> update notification

if you mean by "add" event. that's by-design. informer populates events on the first round of list-watching. to get rid of these syncing events, hold your controller until informer cache syncs. e.g. XXXInformer#hasSynced

**Comment by likakuli** [comment]
> > update notification
> 
> if you mean by "add" event. that's by-design. informer populates events on the first round of list-watching. to get rid of these syncing events, hold your controller until informer cache syncs. e.g. XXXInformer#hasSynced

I mean the "update" event

**Comment by likakuli** [comment]
```
func (s *sharedIndexInformer) HandleDeltas(obj interface{}) error {
	s.blockDeltas.Lock()
	defer s.blockDeltas.Unlock()

	// from oldest to newest
	for _, d := range obj.(Deltas) {
		switch d.Type {
		case Sync, Added, Updated:
			isSync := d.Type == Sync
			s.cacheMutationDetector.AddObject(d.Object)
			if old, exists, err := s.indexer.Get(d.Object); err == nil && exists {
				if err := s.indexer.Update(d.Object); err != nil {
					return err
				}
				s.processor.distribute(updateNotification{oldObj: old, newObj: d.Object}, isSync)
			} else {
				if err := s.indexer.Add(d.Object); err != nil {
					return err
				}
				s.processor.distribute(addNotification{newObj: d.Object}, isSync)
			}
		case Deleted:
			if err := s.indexer.Delete(d.Object); err != nil {
				return err
			}
			s.processor.distribute(deleteNotification{oldObj: d.Object}, false)
		}
	}
	return nil
}
```

when the object already in the cache, informer will directly distribute an update notification without compare the equality of the old and new object. Is this a feature for resync or a bug? In most cases, we don's want to receive an update notification when there is no changes.

**Comment by yue9944882** [comment]
> when the object already in the cache, informer will directly distribute an update notification without compare the equality of the old and new object.

you're supposed to filter by equality in the notification handler

**Comment by liggitt** [comment]
Update events are sent on repost, which is required on API server restart when the watch connection is broken.
