### ISSUE TITLE
worker nodes appear many created status containers

### ISSUE THREAD

**Issue by Erically** [kubernetes/kubernetes#81646]
**What happened**:
```worker nodes appear many created status containers```
**What you expected to happen**:
```will not appear any created status conatiners```
**How to reproduce it (as minimally and precisely as possible)**:
```run k8s cluster for serveral days```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@node1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
```
ali cloud
worker 8 core 32GB
```

- OS (e.g: `cat /etc/os-release`):
```
[root@node13 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
```
[root@node13 ~]# uname -a
Linux node13 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
```
kubespray
```

- Network plugin and version (if this is a network-related bug):
```
[root@node13 ~]# calicoctl version
Client Version:    v3.4.0
Git commit:        a7e09d5
Cluster Version:   v3.4.0
Cluster Type:      kubespray,bgp,k8s
```

- Others:

**Comment by Erically** [comment]
@kubernetes/sig-Node-bugs

**Comment by Erically** [comment]
so many created status containers
![image](https://user-images.githubusercontent.com/7445436/63329870-55328c00-c365-11e9-881a-0da765c881b6.png)

**Comment by Erically** [comment]
because of this?It does nothing.
![image](https://user-images.githubusercontent.com/7445436/63330041-acd0f780-c365-11e9-9f99-395454382567.png)

**Comment by Erically** [comment]
check the dir /var/lib/docker/containers,the result as below:
![image](https://user-images.githubusercontent.com/7445436/63332427-2ec31f80-c36a-11e9-8729-d5d0285af0bd.png)

**Comment by SocietyCao** [comment]
are you use the devicemapper driver?
It might a storage problem,please exec 'docker info | grep "Space"',check the thin pool of metadata has available space.

**Comment by Erically** [comment]
> are you use the devicemapper driver?
> It might a storage problem,please exec 'docker info | grep "Space"',check the thin pool of metadata has available space.
```
[root@node12 ~]# docker info
Client:
 Debug Mode: false

Server:
 Containers: 297
  Running: 72
  Paused: 0
  Stopped: 225
 Images: 1161
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.4.189-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.42GiB
 Name: node12
 ID: R2Y3:6PPT:4RBP:2O4X:Y7LB:HIXT:WHXT:BOLU:FRZF:W4DZ:BM4S:76OM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  gcr.io
  quay.io
  127.0.0.0/8
 Live Restore Enabled: false

No Space option,we use overlay2.
```

**Comment by SocietyCao** [comment]
@Erically 
First,you should delete that pod. 
I have know the problem,you env $JAVA_COMMAND is empty,and your pod args is sh -c $JAVA_COMMAND,it equal to  "sh -c" .
I test it,when args is "sh -c ",kubernetes will automatic create containers all the day.
so you should ensure the env $JAVA_COMMAND have existed.

**Comment by Erically** [comment]
```There is not pod about this container,another container likes this:```
![image](https://user-images.githubusercontent.com/7445436/63573266-74285c80-c5b7-11e9-913b-c6679dea47d5.png)
Both may be similar,command has problem,i.e. $JAVA_COMMAND is null,the #(nop) string exists.

**Comment by SocietyCao** [comment]
The reason is container has been created,but it can't start successfully.
You can use 'docker start ' to start Created status container.
Then you will be get log about the container start error.
It will be  more easily to slove the question.
About:
https://docs.docker.com/engine/reference/commandline/create/

**Comment by Erically** [comment]
okay,I will try.
