### ISSUE TITLE
Fix static check failures

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubernetes#81657]
As #81189 has been merged, there are a lot of packages that cannot pass the static check and we need to clean them up!

Step 1: Remove one or two packages (related packages) from the list in - https://github.com/kubernetes/kubernetes/blame/master/hack/.staticcheck_failures
Step 2: Run hack/verify-staticcheck.sh and look at the logged errors
Step 3: Fix the code to ensure that hack/verify-staticcheck.sh runs cleanly.
Step 4: Run hack/update-bazel.sh and hack/update-gofmt.sh to make sure we fix any problems with gofmt or bazel.
Step 5: File a PR with the change

- please append the packages you picked at the end.
- For existing contributor, please make sure this list is update to date

- Don't use `Fixes: #81657` which will shut down the issue,  just use `Ref:#81657`

**Comment by hpandeycodeit** [comment]
I was trying to run `hack/verify-staticcheck.sh` on my mac and getting this error: 
`mapfile: command not found` 

Is there an easy way to install this command? I don't find much help online.

**Comment by sadlil** [comment]
@hpandeycodeit looks like its an issue with macOS default bash. I update my bash to 5.0.9 in MacOS following this - https://itnext.io/upgrading-bash-on-macos-7138bd1066ba and seems like its working now. 

BTW if you are going to work on some of the packages - I am interested to work on some packages too. Lets split a few so we don't end up having conflicts.

**Comment by hpandeycodeit** [comment]
@sadlil Thanks for sharing that. It worked after upgrading my bash. 
Thanks for the PR! Are you working on more of the packages? If yes, I will work on different ones.

**Comment by sadlil** [comment]
@hpandeycodeit yes, i am also trying to put together  few PR from `/pkg/controller` - bottom to top in the list. Will try to pick up few more later. Would be happy to help.

**Comment by xichengliudui** [comment]
Let us know，when creating a new pr, the description of the pr should not be: Fixes #81657, which will shut down the issue (I think it's a long-term effort); it should be ref #81657.

**Comment by RainbowMango** [comment]
Fixed packages:
```
vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration	
vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/helper	
vendor/k8s.io/kube-aggregator/pkg/controllers/autoregister	
vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator
```

**Comment by RainbowMango** [comment]
Following packages has been reserved:
```
-vendor/k8s.io/code-generator/cmd/client-gen/generators/fake
-vendor/k8s.io/code-generator/cmd/client-gen/generators/util
-vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf
```

/assign

**Comment by RainbowMango** [comment]
Following packages, `vendor/k8s.io/apiserver/*` has been reserved:
```
vendor/k8s.io/apiserver/pkg/admission/initializer
vendor/k8s.io/apiserver/pkg/authentication/request/x509
...
vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook
vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook
```

**Comment by SataQiu** [comment]
I will pick these up :)
```
test/e2e/framework
test/e2e/framework/ingress
test/e2e/framework/kubelet
test/e2e/framework/node
test/e2e/framework/pod
test/e2e/framework/podlogs
test/e2e/framework/providers/aws
test/e2e/framework/providers/gce
test/e2e/framework/psp
test/e2e/framework/service
test/e2e/framework/volume
```

**Comment by hwdef** [comment]
Fixed packages:
```
cluster/images/conformance/go-runner
```

**Comment by RainbowMango** [comment]
FYI.

Packages in `pkg/kubelet/*` aready in #81206.

**Comment by praseodym** [comment]
I'll pick up:
```
pkg/registry/autoscaling/horizontalpodautoscaler/storage
pkg/registry/core/namespace/storage
pkg/registry/core/persistentvolumeclaim/storage
pkg/registry/core/resourcequota/storage
pkg/registry/core/service/ipallocator
pkg/registry/core/service/portallocator
pkg/registry/core/service/storage
pkg/registry/extensions/controller/storage
```

**Comment by mattjmcnaughton** [comment]
I'll fix `test/integration/kubelet`.

**Comment by praseodym** [comment]
I'll also fix:
```
pkg/proxy/healthcheck
pkg/proxy/iptables
pkg/proxy/ipvs
pkg/proxy/userspace
pkg/proxy/winkernel
pkg/proxy/winuserspace
```

**Comment by mattjmcnaughton** [comment]
I'll take `test/utils/...`.

**Comment by palnabarun** [comment]
I'm taking up

```
pkg/security/podsecuritypolicy/sysctl
test/e2e_node
test/e2e_node/environment
test/e2e_node/remote
test/e2e_node/runner/remote
test/images/agnhost/dns
test/images/agnhost/inclusterclient
test/images/agnhost/net/nat
test/images/agnhost/netexec
test/images/agnhost/pause
test/images/agnhost/serve-hostname
test/images/agnhost/webhook
test/images/pets/peer-finder
```

**Comment by praseodym** [comment]
@palnabarun there already is a PR for `test/images`, see above

**Comment by palnabarun** [comment]
@praseodym Oh! Sorry. While searching for taken up files, I missed that.

I am removing those from my list.

**Comment by carlory** [comment]
I'm taking up

```
cluster/images/etcd-version-monitor
cluster/images/etcd/migrate
```

**Comment by hwdef** [comment]
@carlory 
there already is a PR for cluster/images/etcd/migrate, see [https://github.com/kubernetes/kubernetes/pull/81757](url)

**Comment by carlory** [comment]
@hwdef Sorry. I am removing those from my list

**Comment by carlory** [comment]
I will also pick up

```
cmd/controller-manager/app
cmd/kube-controller-manager/app
cmd/kube-proxy/app
cmd/linkcheck
cmd/preferredimports
```

**Comment by carlory** [comment]
I will also pick up

```
pkg/client/tests
pkg/credentialprovider
pkg/kubeapiserver/admission
pkg/kubectl/cmd/get
pkg/master
pkg/printers
pkg/probe/http
```

**Comment by palnabarun** [comment]
I'm picking up:
```
vendor/k8s.io/client-go/*
```

and

```
vendor/k8s.io/kubectl/*
```

**Comment by RainbowMango** [comment]
@palnabarun 
I'm working on `vendor/k8s.io/client-go/*`, maybe you can fix `vendor/k8s.io/kubectl/*` first.

**Comment by palnabarun** [comment]
@RainbowMango Sure. Your comment was minimized so missed it. :)

**Comment by carlory** [comment]
I'm picking up:

```
vendor/k8s.io/apiserver
```

**Comment by Songjoy** [comment]
I'm picking up:

```
vendor/k8s.io/metrics/pkg/client/custom_metrics
```

**Comment by Zhuzhenghao** [comment]
I'm picking up: 
```
vendor/k8s.io/component-base/metrics
```

**Comment by palnabarun** [comment]
I am also picking up:

```
test/integration/*
test/e2e/*
```

except the following as they have been taken up

```
test/e2e/framework
test/e2e/framework/ingress
test/e2e/framework/kubelet
test/e2e/framework/node
test/e2e/framework/pod
test/e2e/framework/podlogs
test/e2e/framework/providers/aws
test/e2e/framework/providers/gce
test/e2e/framework/psp
test/e2e/framework/service
test/e2e/framework/volume
test/e2e/scheduling
test/integration/kubelet
test/integration/scheduler
test/integration/scheduler_perf
test/integration/volumescheduling
```

**Comment by RainbowMango** [comment]
> I'm picking up:
> 
> ```
> vendor/k8s.io/apiserver/*
> vendor/k8s.io/legacy-cloud-providers/*
> vendor/k8s.io/sample-controller/*
> ```

@carlory The items you picking up conflict with others.  I will try to post the unclaimed list that you can pick from.

**Comment by RainbowMango** [comment]
For guys easy pick task, anyone wants help can pick from this list, I will delete items once it has been picked.

```
cluster/images/etcd-version-monitor
hack/make-rules/helpers/go2make/testdata/dir-with-gofiles
pkg/apis/scheduling/v1alpha1
pkg/apis/scheduling/v1beta1
pkg/printers/internalversion
pkg/proxy/healthcheck
pkg/proxy/iptables
pkg/proxy/ipvs
pkg/proxy/userspace
pkg/proxy/winkernel
pkg/proxy/winuserspace
pkg/util/coverage
pkg/util/ebtables
pkg/util/ipconfig
pkg/util/iptables
pkg/util/ipvs/testing
pkg/util/mount
pkg/util/netsh
plugin/pkg/admission/imagepolicy
plugin/pkg/admission/podnodeselector
test/instrumentation
vendor/k8s.io/api/events/v1beta1
vendor/k8s.io/cli-runtime/pkg/resource
vendor/k8s.io/cloud-provider/service/helpers
vendor/k8s.io/legacy-cloud-providers/azure
vendor/k8s.io/sample-controller
```

**Comment by palnabarun** [comment]
I was thinking of taking up:

```
pkg/proxy/*
pkg/util/*
```

**Comment by carlory** [comment]
@RainbowMango thanks for your time, I will take up:

```
plugin/pkg/admission/*
test/instrumentation
hack/make-rules/helpers/go2make/testdata/dir-with-gofiles
```

**Comment by RainbowMango** [comment]
Remaining tasks:
```
cluster/images/etcd-version-monitor
hack/make-rules/helpers/go2make/testdata/dir-with-gofiles
pkg/apis/scheduling/v1alpha1
pkg/apis/scheduling/v1beta1
pkg/printers/internalversion
vendor/k8s.io/api/events/v1beta1
vendor/k8s.io/cli-runtime/pkg/resource
vendor/k8s.io/cloud-provider/service/helpers
vendor/k8s.io/legacy-cloud-providers/azure
vendor/k8s.io/sample-controller
```

**Comment by carlory** [comment]
@RainbowMango

 there already is a PR for `cluster/images/etcd-version-monitor`, see #81923

**Comment by RainbowMango** [comment]
Thanks. @carlory 

Update remaining tasks:
```
pkg/apis/scheduling/v1alpha1
pkg/apis/scheduling/v1beta1
pkg/printers/internalversion
vendor/k8s.io/api/events/v1beta1
vendor/k8s.io/cli-runtime/pkg/resource
vendor/k8s.io/cloud-provider/service/helpers
vendor/k8s.io/legacy-cloud-providers/azure
vendor/k8s.io/sample-controller
```

**Comment by carlory** [comment]
I will pick up 

```
pkg/apis/scheduling/v1alpha1
pkg/apis/scheduling/v1beta1
```

@RainbowMango there already is a PR for `pkg/printers/*`, see https://github.com/kubernetes/kubernetes/pull/81934

**Comment by carlory** [comment]
Update remaining tasks:

```
vendor/k8s.io/api/events/v1beta1
vendor/k8s.io/cli-runtime/pkg/resource
vendor/k8s.io/cloud-provider/service/helpers
vendor/k8s.io/legacy-cloud-providers/azure
vendor/k8s.io/sample-controller
```

**Comment by carlory** [comment]
I will pick up

```
vendor/k8s.io/api/events/v1beta1
vendor/k8s.io/cloud-provider/service/helpers
```

**Comment by carlory** [comment]
Update remaining tasks:

```
vendor/k8s.io/legacy-cloud-providers/azure
```

**Comment by beautytiger** [comment]
working on
```
vendor/k8s.io/legacy-cloud-providers/azure
```

**Comment by beautytiger** [comment]
@SataQiu 
Can you explain to me why we should clean code in vendor folder instead of in its origin repo? I think once it's updated, all changes in vendor will be lost.
Thank you.

**Comment by carlory** [comment]
@beautytiger 

you can run the following commend to make sure the symbol link is alway avaliable.

```
hack/update-vendor.sh
```

if you change `api` or `apis` package, you should regenerate code and docs.

```
hack/update-codegen.sh
hack/update-generated-docs.sh
```

**Comment by beautytiger** [comment]
@carlory 
Got it, thanks!

**Comment by shivi28** [comment]
Hi all, I am picking up 
`pkg/controller/nodeipam/ipam/cidrset`

**Comment by mayankshah1607** [comment]
Hi, I'm a new contributor, and was wondering if I could help with this issue. Are there any tasks remaining that I can pickup?

**Comment by dims** [comment]
@mayankshah1607 see "step 1" :) also see comments above where some folks have expressed interest in specific packages (look for PRs from those folks to avoid duplication)

**Comment by RainbowMango** [comment]
@mayankshah1607 
If I remember correctly, all the tasks have been picked.

Let's remove help-wanted flag now.

/remove-help

**Comment by mattjmcnaughton** [comment]
I'll take `test/e2e/node` (which I don't believe anyone has taken yet).

**Comment by mattjmcnaughton** [comment]
I'll take `test/e2e/lifecycle` and `test/e2e/lifecycle/bootstrap`.

**Comment by mattjmcnaughton** [comment]
Ahhh whoops, I searched for `test/integration/...` full file name, but not the `*`.

**Comment by mattjmcnaughton** [comment]
Apologies @palnabarun ! Well, I only got to one or two so still plently left. Lmk if you want to divide them up, or if you are working on all of them, that's great too.

**Comment by YuikoTakada** [comment]
@palnabarun are you still working on this issue? if you can't, I'll assign test/integration/* to myself, thanks.

**Comment by palnabarun** [comment]
@YuikoTakada Sure. Please take that lot up. :) I had reserved them for new contributors.

**Comment by YuikoTakada** [comment]
@palnabarun thanks!

**Comment by palnabarun** [comment]
@YuikoTakada Welcome!

**Comment by 928234269** [comment]
@palnabarun  I want to fix this static check. I'll assign pkg/volume/hostpath to myself.

**Comment by palnabarun** [comment]
Sure! Please go ahead.

**Comment by gavinfish** [comment]
@palnabarun  I will pick up `pkg/util/netsh` and `vendor/k8s.io/kubectl/*`, thanks.

**Comment by palnabarun** [comment]
@gavinfish Awesome!

**Comment by yiyang5055** [comment]
Before change code, when i run hack/verify-staticcheck.sh at master, have errors:
```/usr/local/go/src/runtime/cgo/cgo.go:31:8: could not import C (Config.Importer.Import(C) returned nil but no error) (compile)
-: could not analyze dependency k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration [k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration.test] of k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration.test (compile)
-: could not analyze dependency k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration of k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/scheme (compile)
-: could not analyze dependency k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration of k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/registry/apiservice (compile)
-: could not analyze dependency k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/install of k8s.io/kubernetes/vendor/k8s.io/kube-aggregator (compile)
-: could not analyze dependency k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1 of k8s.io/kubernetes/test/integration/etcd [k8s.io/kubernetes/test/integration/etcd.test] (compile)`
```
@palnabarun

**Comment by 928234269** [comment]
@palnabarun I'll assign test/integration/etcd to myself.thinks.

**Comment by 928234269** [comment]
@palnabarun  I will pick up  pkg/util/coverage.

**Comment by 928234269** [comment]
@palnabarun I will pick up  vendor/k8s.io/apimachinery/pkg/api/resource

**Comment by gavinfish** [comment]
/reopen
for not all the PRs are merged.

**Comment by k-toyoda-pi** [comment]
`hack/.staticcheck-failures` has some files yet.
Although there is not much progress, do we still need the cleanup?

**Comment by BenTheElder** [comment]
we should fix all of these but this page is not loading so well with so many comments.
moving to a new issue https://github.com/kubernetes/kubernetes/issues/81657
/close
