### ISSUE TITLE
[Failing Test] gce-master-scale-performance - 5k load

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#81665]
**Which jobs are failing**:
gce-master-scale-performance

**Which test(s) are failing**:
load

**Since when has it been failing**:
load failed on 2019-08-19, green otherwise

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance

**Reason for failure**:
> [measurement call APIResponsiveness - APIResponsiveness error: top latency metric: there should be no high-latency requests, but: [
> got: {Resource:pods Subresource: Verb:LIST Scope:namespace Latency:perc50: 972.736ms, perc90: 10.494616s, perc99: 10.494616s Count:9}; expected perc99 <= 5s
>  got: {Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:perc50: 9.454ms, perc90: 92.711ms, perc99: 10.082688s Count:35287}; expected perc99 <= 1s
> got: {Resource:configmaps Subresource: Verb:POST Scope:namespace Latency:perc50: 2.127ms, perc90: 8.71286s, perc99: 8.71286s Count:9}; expected perc99 <= 1s
> got: {Resource:leases Subresource: Verb:GET Scope:namespace Latency:perc50: 6.819ms, perc90: 260.286ms, perc99: 6.098189s Count:12511}; expected perc99 <= 1s
> got: {Resource:nodes Subresource: Verb:GET Scope:cluster Latency:perc50: 122µs, perc90: 2.251ms, perc99: 5.64505s Count:76388}; expected perc99 <= 1s
> got: {Resource:configmaps Subresource: Verb:PUT Scope:namespace Latency:perc50: 3.281ms, perc90: 18.9ms, perc99: 1.296968s Count:38}; expected perc99 <= 1s
> got: {Resource:pods Subresource: Verb:GET Scope:namespace Latency:perc50: 2.579ms, perc90: 36.87ms, perc99: 1.267748s Count:1736}; expected perc99 <= 1s]]

**Anything else we need to know**:
/sig scalability

**Comment by jkaniuk** [comment]
/assign @jkaniuk

Master node was restarted and during that time apiserver did not respond for ~1.5min. After apiserver came back online, number of incoming requests caused increased latency failing the test.

Master node was restarted at the end of the load test, during services deletion:
systemd.log
`Aug 20 05:00:51.707010 gce-scale-cluster-master dockerd[2594]: time="2019-08-20T05:00:51.706944318Z" level=debug msg="Calling GET /containers/json? [...]
-- Reboot --
Aug 20 05:01:25.835010 localhost kernel: Linux version 4.14.94+ [...]
Aug 20 05:01:25.835046 localhost kernel: Command line: BOOT_IMAGE=/syslinux/vmlinuz.A [...]`

apiserver stops responding for ~1.5min:
`Aug 20 05:01:20..05:02:51 kubelet[2164]: ... context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Aug 20 05:02:00..05:02:58 kubelet[2164]: ... dial tcp 34.74.135.163:443: i/o timeout
Aug 20 05:02:10..05:02:27 kubelet[2164]: [...] dial tcp 34.74.135.163:443: connect: connection refused
Aug 20 05:02:36..05:03:41 kubelet[2164]: [...] no relationship found between node "gce-scale-cluster-minion-heapster" and this object`

During apiserver unavailability, all 313 coredns pods failed liveness probes and were restarted by kubelets which additionally increased apiserver latency.

**Comment by chrisohaver** [comment]
> During apiserver unavailability, all 313 coredns pods failed liveness probes and were restarted by kubelets which additionally increased apiserver latency.

FWIW, CoreDNS 1.5.0 and later versions can answer liveness and readiness probes separately/more correctly.  CoreDNS 1.3.1 provided the same answer for liveness and readiness. CoreDNS 1.6.2 is planned for k8s 1.16. My expectation is that in this kind of situation the CoreDNS Pods will fail readiness probes without failing liveness probes (i.e. they'd be unready, but not restart).

**Comment by jkaniuk** [comment]
Master node was restarted due to kernel panic:
"2019-08-19 22:01:05.765 PDT - GuestPanicEvent"
No logs of that were saved so there is no way to debug it further.

Filed https://github.com/kubernetes/test-infra/issues/14149 to be prepared for future occurences.
