### ISSUE TITLE
Does kubernetes APIServer support executing batch operations in one call ?

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#81694]
For example, we send one binding API call, and bind several pods to nodes during this call.

/sig api-machinery

/kind support

**Comment by NickrenREN** [comment]
If not, any plans for this ?

**Comment by liggitt** [comment]
It does not. API requests are limited to a single transaction on a single resource. Even deletecollection calls are non-transactional (some resources can succeed deleting and others may not)

This was discussed at length, but is not currently planned.
