### ISSUE TITLE
cpuset.cpus file is not updated for the pod created with Guaranteed QoS class

### ISSUE THREAD

**Issue by pperiyasamy** [kubernetes/kubernetes#81728]
**What happened**:

The k8s is installed with cpu manager 'static' policy. Then while trying to create a pod with Guaranteed QoS class for CPU,  noticed this [issue](https://github.com/kubernetes/kubernetes/issues/66614) then applied this workaround mentioned in the [comment](https://github.com/kubernetes/kubernetes/issues/66614#issuecomment-427738719) to fix the issue. Now the pod is created successfully and seeing the following kubelet logs.

```
Aug 21 15:37:26 my-centos kubelet[2715]: 2019-08-21 15:37:26.741 [INFO][25946] k8s.go 420: Wrote updated endpoint to datastore ContainerID="dc1eb1ab0c9ca86cec51a94aced27ecf47fbc0ab231da971771fed5d15939da8" Namespace="default" Pod="pod-dpdk-uio" WorkloadEndpoint="my--centos-k8s-pod--dpdk--uio-eth0"
Aug 21 15:37:26 my-centos kubelet[2715]: I0821 15:37:26.780697    2715 policy_static.go:177] [cpumanager] static policy: AddContainer (pod: pod-dpdk-uio, container: appcntruio3, container id: 6c7467c08cc4f97496703a939bcf9bd23e54a5064bdd871b103c19177784bf0b)
Aug 21 15:37:26 my-centos kubelet[2715]: I0821 15:37:26.780718    2715 policy_static.go:207] [cpumanager] allocateCpus: (numCPUs: 5)
Aug 21 15:37:26 my-centos kubelet[2715]: I0821 15:37:26.780855    2715 state_mem.go:84] [cpumanager] updated default cpuset: "0-1,7-17"
Aug 21 15:37:26 my-centos kubelet[2715]: I0821 15:37:26.781648    2715 policy_static.go:215] [cpumanager] allocateCPUs: returning "2-6"
Aug 21 15:37:26 my-centos kubelet[2715]: I0821 15:37:26.781668    2715 state_mem.go:76] [cpumanager] updated desired cpuset (container id: 6c7467c08cc4f97496703a939bcf9bd23e54a5064bdd871b103c19177784bf0b, cpuset: "2-6")
```

But the POD container's `cpuset.cpus` file contains all the cores of worker instead of just 2-6.
```
root@pod-dpdk-uio:/usr/src/dpdk-stable-17.11.3# cat /sys/fs/cgroup/cpuset/cpuset.cpus
0-17
```

**What you expected to happen**:

The `cpuset.cpus` file and `/proc/cpuinfo` are supposed to have cores 2-6 instead of 0-17.

**How to reproduce it (as minimally and precisely as possible)**:

K8s with single node cluster, cpu manager with 'static' policy and pod created with Guaranteed QoS class.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux my-centos 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pperiyasamy** [comment]
The isolated cores are seen in `Cpus_allowed & Cpus_allowed_list` attributes of /proc/1/task/1/status file. 
```
root@pod-dpdk-uio:/# cat /proc/1/task/1/status | grep Cpus_allowed
Cpus_allowed:   0007c
Cpus_allowed_list:      2-6
```
is this the right way to find out which cores are pinned inside the container ? This info is needed for running high performance DPDK applications (telco workloads) on specific isolated cores.

**Comment by xiaoanyunfei** [comment]
> root@pod-dpdk-uio:/usr/src/dpdk-stable-17.11.3# cat /sys/fs/cgroup/cpuset/cpuset.cpus
0-17

It's strange. I tried on my cluster,  and the cpuset.cpus is surelly `2-6`
I guess this may have something to do with your docker version or kernel version

You can check the file `/var/lib/kubelet/cpu_manager_state` which indicates the cpuset that pod should use

You can get the actual cpuset that pod used as below:

> cat /proc/{container pid} /cgroup
9:cpuset:/kubepods.slice/kubepods-poda98f5975_aa94_4ae6_bcad_ed557680fd5d.slice/docker-b8f750fe548e72605e365d10519fdd08e96c3ea9a1ebd9c30b2a4a4823adec62.scope

>cat /sys/fs/cgroup/cpuset/kubepods.slice/kubepods-poda98f5975_aa94_4ae6_bcad_ed557680fd5d.slice/docker-b8f750fe548e72605e365d10519fdd08e96c3ea9a1ebd9c30b2a4a4823adec62.scope/cpuset.cpus

**Comment by pperiyasamy** [comment]
> You can check the file `/var/lib/kubelet/cpu_manager_state` which indicates the cpuset that pod should use

Yes, I can see it from the below content:

```
$ cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0-1,7-17","entries":{"176f110ce7745a4c602930ffbc86a54d8e2d09eea7c18f7c5350449b9daede3a":"2-6"},"checksum":2400489974}
```

As this info exists on the host (worker node), but application running on the pod should get to know the isolated cores in some way on the pod itself to run dpdk specific applications on those cores. 
we could parse `Cpus_allowed` parameter in the `/proc/1/task/1/status` file, but it would be good if we have it on the pod's `/sys/fs/cgroup/cpuset/cpuset.cpus` file.

The following docker and kernel version used.
```
$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ uname -a
Linux my-centos 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
Do you see any issue with it ?

**Comment by pperiyasamy** [comment]
Hi, Any update on this issue ? I recently checked it with k8s v1.16.2, the issue still exists when k8s is installed on VM. The pod's /sys/fs/cgroup/cpuset/cpuset.cpus file is not updated. 
But this seems to be working fine with baremetal deployment.

**Comment by pperiyasamy** [comment]
I just noticed the host's /sys directory as volume mount inside the pod which was the reason pod's cpuset.cpus file just having host's file content. 
closing the issue.
