### ISSUE TITLE
bitbucket.org/ww/goautoneg dependency at risk of being deleted

### ISSUE THREAD

**Issue by twaugh** [kubernetes/kubernetes#81724]
The bitbucket.org/ww/goautoneg package is hosted at bitbucket.org using a Mercurial repository. This is currently at risk of being deleted next year: https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket

**Comment by dims** [comment]
We should switch to `github.com/munnerz/goautoneg` maintained by @munnerz

**Comment by nikhita** [comment]
We also use `bitbucket.org/bertimus9/systemstat` which we can replace with https://github.com/nikhita/systemstat.

/sig architecture
/assign

**Comment by nikhita** [comment]
My bad, `bitbucket.org/bertimus9/systemstat` uses git and not `hg` (can be seen with `hg identify`).

The only repo that used mercurial was `goautoneg` and we use `github.com/munnerz/goautoneg` for release-{1.13, 1.14, 1.15, 1.16} and master branches already. IMO this issue can be closed.

For completeness:

- 1.13:

https://github.com/kubernetes/kubernetes/blob/723783951019e10d3292bb1162835e08a0546739/Godeps/Godeps.json#L2581

- 1.14:

https://github.com/kubernetes/kubernetes/blob/89c2668a5f477650b31a018c48c71d0a6db6695a/Godeps/Godeps.json#L2766


- 1.15:

https://github.com/kubernetes/kubernetes/blob/78aa54348f26e426323815b3a0a8fabf9f47c0bc/go.mod#L113

- 1.16:

https://github.com/kubernetes/kubernetes/blob/7501d5a6edd50dbaa72faffc434ba0ea0a19c33e/go.mod#L98

- master:

https://github.com/kubernetes/kubernetes/blob/c008cf95a92c5bbea67aeab6a765d7cb1ac68bd7/go.mod#L98

**Comment by dims** [comment]
Thanks for the research @nikhita !

/close
