### ISSUE TITLE
SSH in Windows test cluster doesn't work

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#81734]
I followed the document to create an e2e cluster https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/README-GCE-Windows-kube-up.md

However, `gcloud compute ssh` doesn't work after the cluster is up.

I got the following error:
```
Warning: Permanently added 'compute.3660176483394069101' (ECDSA) to the list of known hosts.
lantaol@XX.XXX.XXX.X: Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

/cc @yujuhong @kubernetes/sig-windows-misc

**Comment by pjh** [comment]
@Random-Liu where are you trying to ssh _from_? Can you ssh to a Linux instance in GCE?

If you run `gcloud compute project-info describe --flatten commonInstanceMetadata.items.ssh-keys` do you see ssh keys there? Do any of them match a public key that you have under `~/.ssh`?

There could be a delay the very first time you try to ssh; we noted this in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/testonly/install-ssh.psm1#L256, but we could add it to the README too. If you try a second time after a couple minutes does it still fail?

**Comment by Random-Liu** [comment]
> Random-Liu where are you trying to ssh from? Can you ssh to a Linux instance in GCE?

Yeah I can ssh to a linux instance in the same cluster.

**Comment by Random-Liu** [comment]
@pjh I still got the same error after recreating the cluster.

```
$ gcloud compute ssh e2e-test-lantaol-windows-node-group-8f0s --zone=us-central1-b
Warning: Permanently added 'compute.6924243725890619375' (ECDSA) to the list of known hosts.
lantaol@35.222.146.232: Permission denied (publickey,keyboard-interactive).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

I can ssh into linux nodes in the same cluster just fine.
