### ISSUE TITLE
Add OpenAPI Field/Properties for release, feature_gate, required, and deprecated metadata 

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#81759]
This is likely related to #80586, but is required for us to measure and increase coverage in the right areas of Kubernetes.

We'd like verification, but this seems to have led us to discover:
- [69 gated, deprecated, or non-ga fields](https://github.com/cncf/apisnoop/blob/v3_rainbow/org/explorations/field_properties.md#69-gated-deprecated-or-non-ga-fields)
- [12 NonDeprecated GA fields behind FeatureGates](https://github.com/cncf/apisnoop/blob/v3_rainbow/org/explorations/field_properties.md#12-nondeprecated-ga-fields-behind-featuregates)
- [606 required of 2797 total fields](https://github.com/cncf/apisnoop/blob/v3_rainbow/org/explorations/field_properties.md#606-required-of-2797-total-fields)

### Suggested OpenAPI Schema Object Field/Property updates<a id="sec-1"></a>

In our work to measure and increase the tested surface area of Kubernetes, we required knowing  more information about each field.

This led to us calculating a few fields that would probably be better served by inclusion in our OpenAPI schema.

#### Release status<a id="sec-1-1"></a>

This could probably be applied to operations and parameters as well.

APISnoop generates \`api-schema-field.release\` by searching for for 8 variations of alpha/beta within the description to set this as 'alpha', 'beta', or 'ga'.

This would likely better be set as as string via \`x-k8s-field-release\` or similar.

#### Feature Gated<a id="sec-1-2"></a>

APISnoop generates \`api-schema-field.feature-gated\` by searching for 8 variation of 'feature gate' to set a boolean. This would likely better be set as as string via \`x-k8s-field-feature-gate\` or similar.

This could probably be applied to operations and parameters as well.

#### Required<a id="sec-1-3"></a>

APISnoop currently generated \`api<sub>schema</sub><sub>field.required</sub>\` by looking for \`api<sub>schema</sub><sub>field.name</sub>\` in the \`api<sub>schema.required</sub>\` array.

Both V2 and V3 have a \`required\` field which may be a bit more clear.

Would it be better to store this directly in the object itself?

-   **[OpenAPIv2.schemaObject.parameterObject](https://swagger.io/specification/v2/#parameterObject).required:** boolean :
-   **[OpenAPIv3.schemaObject.parameterObject](https://swagger.io/specification/#parameterObject).required:** boolean :

#### Deprecated<a id="sec-1-4"></a>

Note the distinction in deprecated field/property VS object/schema.

In v3 we can use deprecated, but should we look into generating \`x-k8s-field-deprecated: true\` until then?

-   **[OpenAPIv2.schemaObject.parameterObject](https://swagger.io/specification/v2/#parameterObject).<sup>x</sup>-k8s-field-deprecated:** boolean - specifies that this parameter is deprecated
-   **[OpenAPIv3.schemaObject.parameterObject](https://swagger.io/specification/#parameterObject).deprecated:** boolean : Specifies that a parameter is deprecated and SHOULD be transitioned out of usage. Default value is false.

#### Mutable<a id="sec-1-5"></a>

These look like they should only apply to fields, but either way we don't currently have method to enumerate immutable fields.

-   **[OpenAPIv2.schemaObject](https://swagger.io/specification/v2/#schemaObject).readOnly:** boolean
-   **[OpenAPIv3.schemaObject](https://swagger.io/specification/v2/#schemaObject).readOnly:** boolean
-   **[OpenAPIv3.schemaObject](https://swagger.io/specification/v2/#schemaObject).writeOnly:** boolean

### Manual Field Calculation<a id="sec-2"></a>

-   **release:** 'alpha', 'beta', or 'ga' - via a very specific description search

```sql-mode
CASE
WHEN (   description ilike '%This field is alpha-level%'
      or description ilike '%This is an alpha field%'
      or description ilike '%This is an alpha feature%') THEN 'alpha'
WHEN (   description ilike '%This field is beta-level%'
      or description ilike '%This field is beta%'
      or description ilike '%This is a beta feature%'
      or description ilike '%This is an beta feature%'
      or description ilike '%This is an beta field%') THEN 'beta'
ELSE 'ga'
END AS release,
```

-   **feature-gated:** boolean - via a very specific description search

```sql-mode
CASE
WHEN (   description ilike '%requires the % feature gate to be enabled%'
      or description ilike '%depends on the % feature gate being enabled%'
      or description ilike '%requires the % feature flag to be enabled%'
      or description ilike '%honored if the API server enables the % feature gate%'
      or description ilike '%honored by servers that enable the % feature%'
      or description ilike '%requires enabling % feature gate%'
      or description ilike '%honored by clusters that enables the % feature%'
      or description ilike '%only if the % feature gate is enabled%'
) THEN true
ELSE false
END AS feature_gated,
```

-   **required:** <span class="underline">boolean</span> : checks field exist in required section of schema

```sql-mode
-- within our api_schema pulling from each .definition
ARRAY(SELECT jsonb_array_elements_text(d.value -> 'required')) as required_fields
-- within our api_schema_field checking for the field name in the array above
CASE
WHEN d.key = ANY(api_schema.required_fields) THEN true
ELSE false
END AS required,
```

-   **deprecated:** <span class="underline">boolean</span> : property description containing 'deprecated' cases insensitive

```sql-mode
CASE
WHEN d.value->>'description' ilike '%deprecated%' THEN true
ELSE false
END AS deprecated,
```

**Comment by hh** [comment]
@liggitt Thought it would be good to capture this for discussion so we don't have to chase down new description search criteria. :)

**Comment by lavalamp** [comment]
This design was approved by SIG API Machinery but never implemented: https://docs.google.com/document/d/1wuoSqHkeT51mQQ7dIFhUKrdi3-1wbKrNWeIL4cKb9zU/edit (join kubernetes-dev, kubernetes-announce, or kubernetes-sig-api-machinery groups for access).

**Comment by hh** [comment]
Where we generate 'optional' metadata for OpenAPI Fields/Properties from code comments:

https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/kube-openapi/pkg/generators/openapi.go#L38
https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/kube-openapi/pkg/generators/openapi.go#L78-L86
https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/kube-openapi/pkg/generators/openapi.go#L300-L302

Thanks @liggitt for the info.

**Comment by timothysc** [comment]
So I'm going to defer to daniel on this one. 
/unassign @timothysc 
/assign @lavalamp

**Comment by lavalamp** [comment]
Just to set expectations, this is not currently a high priority for SIG API Machinery.
