### ISSUE TITLE
Kubelet garbage-collects the pause image, which might be unpullable in ContainerD

### ISSUE THREAD

**Issue by jmillikin-stripe** [kubernetes/kubernetes#81756]
**What happened**:
When the Kubelet is under disk pressure, it garbage-collects unused container images. If this isn't enough, it evicts pods and then deletes their (now unused) container images. If the disk pressure is due to external data files present in the same partition as the datastore, this can proceed until all container images have been deleted from the CRI runtime.

The pause image is not special cased, so it might be deleted. Unfortunately ContainerD is unable to pull the pause image from private repositories such as Amazon ECR (see https://github.com/containerd/cri/issues/1131), so the result of Kubelet's behavior is that if the disk fills up enough to trigger a GC then the machine might go bad. It still reports Ready and accepts new workloads, but can't run them due to the missing pause image.

**What you expected to happen**:
Filling up the partition used for container filesystems should not cause the machine to become unable to run containers.

**How to reproduce it (as minimally and precisely as possible)**:
* Run Kubelet with ContainerD as its runtime, using a pause image loaded in manually by `ctr load` (see https://github.com/containerd/cri/issues/1131 for context + example command).
* Write a large file to the containerd data partition.
* Watch Kubelet delete the pause image.
* Observe that pods can no longer be created via ContainerD-CRI.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux 4.4
- ContainerD: 1.2.4

**Comment by jmillikin-stripe** [comment]
Note: this _may_ just be a documentation problem. The flag `--pod-infra-container-image` is documented as:
```
      --pod-infra-container-image string                                                                          The image whose network/ipc namespaces containers in each pod will use. This docker-specific flag only works when container-runtime is set to docker. (default "k8s.gcr.io/pause:3.1")
```
but I can confirm that if I set this to the URI of the pause image, Kubelet correctly preserves it even though we're not using the Docker container runtime.

**Comment by zouyee** [comment]
ImageGC will mark sandbox image in used, but according to your description, the situation is strange, it may be an interface `GetImageRef` problem. Have a more detailed explanation?
```
// Always consider the container runtime pod sandbox image in use
	imageRef, err := im.runtime.GetImageRef(container.ImageSpec{Image: im.sandboxImage})
	if err == nil && imageRef != "" {
		imagesInUse.Insert(imageRef)
	}
```

**Comment by jmillikin-stripe** [comment]
@zouyee See my second comment. The docs for `--pod-infra-container-image` say that it only applies when using Docker as the container runtime, so most users of ContainerD CRI are probably not setting it. I was able to fix the GC issue by setting that flag. It might be possible to solve this by simply changing the flag documentation of `--pod-infra-container-image`.

**Comment by zouyee** [comment]
related PR: https://github.com/kubernetes/kubernetes/pull/62982

**Comment by mattjmcnaughton** [comment]
Interesting! So @zouyee am I understanding right that you're suggesting `--pod-infra-container-image` is mistakenly listed as a docker only flag, which it actually applies to multiple CRIs? Is it guaranteed that it will apply to the CRIs in the future, or is that just by chance?

**Comment by zouyee** [comment]
Yes, `--pod-infra-container-image` also applies to other CRI, but only works on `imageGC`.

**Comment by mattjmcnaughton** [comment]
On Sat, Aug 24, 2019 at 08:10:50AM -0700, Zou Nengren wrote:
> Yes, `--pod-infra-container-image` also applies to other CRI, but only works on `imageGC`.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/81756#issuecomment-524558198

Cool - yeah, definitely sounds like some documentation updates could be helpful.
Happy to review a pr :)

**Comment by neolit123** [comment]
/reopen
/remove-lifecycle rotten

this feels like a viable bug to fix.

**Comment by neolit123** [comment]
evicting the sandbox image doesn't feel correct WRT imageGC, but it's tricky as you need to tell the kubelet which is the sandbox image. this implies that --pod-infra-container-image is really not a dockshim only flag.

**Comment by neolit123** [comment]
@zouyee did you manage to get PR / fix for this?
if not, probably best to notify #sig-node or their mailing list about it for more visibility.
https://github.com/kubernetes/community/tree/master/sig-node#contact

**Comment by adisky** [comment]
so for container runtimes  other than docker `pod-infra-container-image` is only used by GC. It could be problematic in some cases e.g. 
- if the sandbox image differs between container runtime and kubelet, then kubelet might evict the actually used one.
 Either we need to update the doc to make it aware to the user, that `pod-infra-container-image` configuration should be in sync with the container runtime. OR Remove use of `pod-infra-container-image` from GC and and Kubelet can get  this information from container runtime?

**Comment by DingGGu** [comment]
I think this is not fixed yet, please re-open the issue.

**Comment by neolit123** [comment]
What version of k8s are you using?

**Comment by neolit123** [comment]
See https://github.com/kubernetes/website/pull/26713
You can use the flag mentioned there.

**Comment by DingGGu** [comment]
If I use the flag in containerd as well, does the image gc prevent that image? There is no such thing in PR.

**Comment by DingGGu** [comment]
I think flag is no helpful in containerd

```
kubelet --version
Kubernetes v1.22.6
```

```
Apr 12 11:33:42 ip-10-91-44-102 kubelet-eks.daemon[153175]: I0412 11:33:42.612160  153175 server.go:199] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
```

**Comment by neolit123** [comment]
See https://github.com/kubernetes/kubernetes/issues/81756#issuecomment-773235889
