### ISSUE TITLE
Use hostpath pod instead of ssh in volumemode e2e test

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#81751]
**What happened**:
A new test case was added [here](https://github.com/kubernetes/kubernetes/pull/81163/files#diff-0d21a89b3adc375caf1b557b014e1111R643) that ssh's into the node and lists the pod directories there.  Can we do this with a hostpath pod instead?  Many test environments are not configured with SSH access, such as the kind cluster we use for kubernetes-csi sidecar testing: https://k8s-testgrid.appspot.com/sig-storage-csi#1.13-on-master

**What you expected to happen**:
Test doesn't need to SSH

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
@wongma7 is this something you can help with?

**Comment by msau42** [comment]
Another thought I had was can we remove this test case out of the storage driver test framework?  This is testing only K8s-level logic, not driver logic right?

**Comment by wongma7** [comment]
Yes that's a good point, it's testing that kubernetes doesn't call mount/stage/publish to x directory in the first place, it won't be driver-dependent. however it depends on a lot of nice to have stuff in the framework
/assign
/cc @jsafrane

**Comment by wongma7** [comment]
@msau42 opened https://github.com/kubernetes/kubernetes/pull/81755/files to skip the test if SSH not present. Seems the sidecar e2es have provider=skeleton so they should be skipped.

Long-term, should have a good story for organizing k8s-specific versus driver-specific tests while allowing k8s-specific tests to reuse the same useful driver/testsuites framework. For example, are all subpath tests going to vary between drivers, isn't subpath k8s-specific?

**Comment by wongma7** [comment]
btw I do think the pod could simply use hostpath to check, https://github.com/kubernetes/kubernetes/pull/81755 is just a quickfix

**Comment by msau42** [comment]
Yes, longer term, we should move out all tests that are not driver-specific.

We've found that subpath has subtle behavior differences depending on the underlying storage mount (ie nfs, vs block vs local directory vs csi), which is why it's being tested per driver.  But there's probably room for improvement

**Comment by msau42** [comment]
I believe this has been addressed by https://github.com/kubernetes/kubernetes/pull/83108

/close
