### ISSUE TITLE
pod successfully assigned event miss when pod first encounter FailedScheduling

### ISSUE THREAD

**Issue by w313062006** [kubernetes/kubernetes#81773]
**What happened**:

1. when I create a pod,the pod first has no resource to allocate

![1](https://pbs.twimg.com/media/ECj2Te5UcAERO4P?format=jpg&name=large)

desc pod:

![2](https://pbs.twimg.com/media/ECj2Te5U4AAH0kh?format=png&name=large)

2.wait some minutes for resource release
3.when have enough resource,the pod from pending to running

but I can't find [successfully assigned] event,the next event is [pulling image] event

![3](https://pbs.twimg.com/media/ECj2Te5VUAAqCtv?format=jpg&name=large)

![4](https://pbs.twimg.com/media/ECj2Te6U8AAVMZP?format=jpg&name=large)

**What you expected to happen**:
when I create a pod has enough resource or wait resource time not too long

![5](https://pbs.twimg.com/media/ECj56BzUEAAA0Ji?format=jpg&name=large)

has a successfully assigned event.

**How to reproduce it (as minimally and precisely as possible)**:
see What happened

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.5
- Cloud provider or hardware configuration: no
- OS (e.g: `cat /etc/os-release`): debian
- Kernel (e.g. `uname -a`):4.9.0-6-amd64

can someone tell me is this a bug？ or how is it happen？
I see kubernetes schedule source code，can't find how. 
thx

**Comment by Pingan2017** [comment]
see
https://github.com/kubernetes/kubernetes/blob/2166946f41b36dea2c4626f90a77706f426cdea2/staging/src/k8s.io/client-go/tools/record/events_cache.go#L44-L49

**Comment by w313062006** [comment]
> see
> https://github.com/kubernetes/kubernetes/blob/2166946f41b36dea2c4626f90a77706f426cdea2/staging/src/k8s.io/client-go/tools/record/events_cache.go#L44-L49

ok,thx
