### ISSUE TITLE
Document the use of import-boss

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#81804]
[import-boss](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/cmd/import-boss/main.go) is used in our CI tests ([./hack/verify-import-boss.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-import-boss.sh)) to verify import restrictions in various places throughout k/k.
Currently, the only existing documentation is within the script itself and this.

xref: https://github.com/kubernetes/kubernetes/issues/81102 - import-boss ignores import in a _test.go file
xref: https://github.com/kubernetes/kubernetes/issues/81803 - failed to implement verify import restrictions in the e2 test framework.

Seems that import-boss is owned by API machinery
/sig api-machinery
/area code-organization
/kind documentation
/priority important-longterm
/cc @jaypipes

**Comment by MorrisLaw** [comment]
PR is ready to be reviewed: https://github.com/kubernetes/kubernetes/pull/85564

**Comment by MorrisLaw** [comment]
Hey @alejandrox1 👋 

Maybe we can close this now since [PR #85564](https://github.com/kubernetes/kubernetes/pull/85564) has been merged?

**Comment by BenTheElder** [comment]
ping -- scanning for signs of life :alien:

**Comment by oomichi** [comment]
> Maybe we can close this now since PR #85564 has been merged?

Yeah, I think we can close this issue thanks to @MorrisLaw work.

**Comment by BenTheElder** [comment]
thanks all!
