### ISSUE TITLE
Leader election when Leader Machine goes down

### ISSUE THREAD

**Issue by javendo** [kubernetes/kubernetes#81837]
**What happened**: Kubernetes takes much time to realize the Node goes down when it is the one that `locks the kube-control-manager endpoint`.

**What you expected to happen**: Kubernetes should take the same time when I remove the `NIC interface` from a note that `locks the kube-control-manager endpoint` realizes the node goes down and put it as `NotReady`

**How to reproduce it (as minimally and precisely as possible)**: Installing kubernetes using the information below using 3 Nodes Kubernetes where those nodes act as `Master` and `Minions` and they are running the etcd too. When the cluster is ready try to remove the `NIC interface` from the one that `locks the kube-control-manager endpoint`. **It happens when you repeat these steps 5 or 6 times**, I mean:

- See what is the leader using `kubectl -n kube-system get endpoints kube-controller-manager -o yaml`,
- Remove its NIC,
- Wait about 2 minutes (I have tuned the controller manager do realizes faster as described below)
- See if the leader changes and the node become NotReady
- If so, add the NIC again
- Wait until the Node become Ready
- Do the same procedures for more 5 or 6 times.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 14.4
- Etcd version: 3.2.26
- Cloud being used: bare-metal
- Installation method: Kubeadm
- Host OS: Centos 7.5
- Kernel Version: 3.10.0-957.12.2.el7.x86_64
- CNI and version: Flannel 0.11.0-amd64
- CRI and version: Docker 18.06.1-ce, build e68fc7a
- **HAProxy balancing request to port 443 to the master nodes in the port 6443**

During some HA Tests I have realized if I remove the NIC interface of a Node where control plane is running it takes more time than the usual (about 1 minute) to realize that `Node` is `NotReady`. Sometimes it realizes fast but **if you persist with this test, like 5 or 6 times it would take more time than the usual (about 20 minutes)**

I would like to avoid this because I have an `stateful` application that I cannot have replicas running and if it is located in that `Node` my app will be out for 20 minutes instead of the normal 1 minute because Kubernetes does not know that that Node is `NotReady` and does not start another instance of my application in `another Node`.

After some investigations it seems related to apiserver showing error related to the grpcd connection like you can see in the logs below.

Changed arguments:

```
kube-apiserver:
    - --default-not-ready-toleration-seconds=16
    - --default-unreachable-toleration-seconds=16
```

```
kube-controller-manager:
    - --node-monitor-grace-period=16s
    - --node-monitor-period=2s
    - --pod-eviction-timeout=30s
```

**Errors:**

**kube-apiserver logs**
```
I0907 14:30:43.442225       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{172.31.59.1:2379 <nil>}]
W0907 14:30:43.442345       1 asm_amd64.s:1337] Failed to dial 172.31.59.3:2379: grpc: the connection is closing; please retry.
W0907 14:30:43.442485       1 asm_amd64.s:1337] Failed to dial 172.31.59.3:2379: grpc: the connection is closing; please retry.
W0907 14:30:44.759551       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
W0907 14:30:44.759599       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
I0907 14:44:27.880215       1 trace.go:81] Trace[1051067580]: "Get /api/v1/namespaces/kube-system/pods/kube-apiserver-private-59-1/log" (started: 2019-09-07 14:43:27.827115376 +0000 UTC m=+5253.188773608) (total time: 1m0.053025354s):
Trace[1051067580]: [1m0.053022292s] [1m0.048443897s] Transformed response object
```

**kube-controller-manager**

```
E0907 15:02:27.762584       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0907 15:02:40.113172       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0907 15:02:52.997606       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0907 15:03:05.627586       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**kube-scheduller**
```
E0907 14:56:11.759352       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0907 14:56:25.806707       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0907 14:56:38.682895       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0907 14:56:51.210413       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded
E0907 14:57:05.085261       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Seems the apiserver is not able to connect to the etcd.

Regards

**Comment by javendo** [comment]
I have retested this issue with the kubernetes version 1.16 and it seems the same behavior happens.

After execute the procedures described in this issue. After do the steps about 4 times the error happens.

The image below shows the last time the private-59-3, *the one I have removed the NIC Interface*, was renewed.

![image](https://user-images.githubusercontent.com/784975/65337158-06635680-db9e-11e9-8f04-a2a61ddad3d2.png)

This second image below, shows the moment it realizes the node private-53-3 is NotReady and elect another node to be the new leader.

![image](https://user-images.githubusercontent.com/784975/65337495-a5884e00-db9e-11e9-98a7-5b485284ecdf.png)

See that it happened about 20 minutes from the time I remove the NIC and not the usual 2 minutes as normal.

**Comment by javendo** [comment]
Some additional logs from kube-apiserver

```
I0920 14:46:11.689988       1 trace.go:116] Trace[1708450495]: "Get" url:/api/v1/namespaces/default (started: 2019-09-20 14:45:53.402369453 +0000 UTC m=+61936.921241121) (total time: 18.287609475s):
Trace[1708450495]: [18.287592496s] [18.287567439s] About to write a response
W0920 14:46:11.707650       1 lease.go:222] Resetting endpoints for master service "kubernetes" to [172.31.59.1 172.31.59.2 172.31.59.3]
E0920 14:46:11.772488       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E0920 14:46:11.872865       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
W0920 14:46:12.772678       1 cacher.go:162] Terminating all watchers from cacher *core.Namespace
E0920 14:46:12.775117       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
W0920 14:46:12.779078       1 reflector.go:299] k8s.io/client-go/informers/factory.go:134: watch of *v1.Namespace ended with: too old resource version: 143 (118233)
W0920 14:46:12.873057       1 cacher.go:162] Terminating all watchers from cacher *apps.StatefulSet
W0920 14:46:13.775281       1 cacher.go:162] Terminating all watchers from cacher *unstructured.Unstructured
I0920 14:46:46.444807       1 log.go:172] http: TLS handshake error from 172.31.59.2:47346: EOF
I0920 14:46:48.868368       1 log.go:172] http: TLS handshake error from 172.31.59.2:47388: EOF
I0920 14:46:52.356346       1 log.go:172] http: TLS handshake error from 172.31.59.2:47424: EOF
I0920 14:46:58.363476       1 log.go:172] http: TLS handshake error from 172.31.59.2:47506: EOF
I0920 14:46:58.525003       1 log.go:172] http: TLS handshake error from 172.31.59.1:38596: EOF
I0920 14:46:58.528318       1 log.go:172] http: TLS handshake error from 172.31.59.1:38600: EOF
I0920 14:46:58.528812       1 log.go:172] http: TLS handshake error from 172.31.59.1:38604: EOF
I0920 14:47:05.361309       1 log.go:172] http: TLS handshake error from 172.31.59.2:47604: EOF
E0920 15:02:16.518775       1 watch.go:256] unable to encode watch object *v1.WatchEvent: client disconnected (&streaming.encoder{writer:(*http2.responseWriter)(0xc00f43f000), encoder:(*versioning.codec)(0xc012290510), buf:(*bytes.Buffer)(0xc01228eae0)})
E0920 15:20:25.566110       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
```

**Comment by emasyakin** [comment]
@javendo were you able to get to the bottom of it?
I have a very similar problem with NIC removal tests.

**Comment by javendo** [comment]
Have you seen the other issue I had mentioned https://github.com/kubernetes/kubernetes/issues/72102

**Comment by chilicat** [comment]
I also see the problem that kube-control-manager and kube-scheduler can not retrieve the lock because of Client.Timeout exceeded. 

I can reproduce it relatively often when I force shutoff the machine which currently holds the log. 
I have a 3 Master setup where all services connect to kube-apiserver thru an HAProxy. 

The interesting part is that e.g. "kubectl get po" works as expected, meaning the HAProxy detected correctly the node which is down and removes it from the list. But all "long running" processes will be stuck in the Client.Timeout eventually. It almost looks like that the long-running client insists to use an old/broken connection.

The solution to the problem is restarting kube-control-manager and kube-scheduler when I detect the problem in the log files.
