### ISSUE TITLE
[Framework] Filter plugins are not been called during preemption

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#81866]
/sig scheduling

code reference: https://github.com/kubernetes/kubernetes/blob/f3816fb757732200a9357fd06241411de63a545a/pkg/scheduler/core/generic_scheduler.go

`genericScheduler.Preempt` calls directly `podFitsOnNode`, whereas `genericScheduler.Schedule` calls `podFitsOnNode` and later `framework.RunFilterPlugins`.

We need to make them consistent or move `framework.RunFilterPlugins` to `podFitsOnNode`.

I think that, with current behavior, since Filter plugins are not queried, it's like they are saying that any pod passes the filter during preemption.

/priority important-soon

**Comment by wgliang** [comment]
/assign
I can work on this

**Comment by hex108** [comment]
I think we could convert `podFitsOnNode` to one or some filter plugins. And `genericScheduler.Preempt` could call `framework.RunFilterPlugins`.
