### ISSUE TITLE
Metric validation static analysis should be able to support const strings for Subsystem and Name

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#81863]
Metric validation currently expects stable metrics to have strings directly in the metric definition. However, we should probably also allow consts and vars which are declared in the pkg/file scope, since those can easily be evaluated to their respective string values.

/assign @serathius 
/sig instrumentation

**Comment by serathius** [comment]
SGTM, I will try to work on it next week.

**Comment by conwaychriscosmo** [comment]
I am interested in contributing and noticed this is the most recent unclaimed issue that is related to metrics.  What is the status of this issue?

**Comment by serathius** [comment]
Sorry @conwaychriscosmo for taking long to respond. I was working on it, even thou it was not visible on Github.

**Comment by serathius** [comment]
Hey Han, I think issue was closed as it was implemented in https://github.com/kubernetes/kubernetes/pull/84373
Anything left here?

**Comment by logicalhan** [comment]
@serathius pkg/kubelet/certificate/kubelet.go fails (as expected since it doesn't read consts from other files) but the error message isn't sufficiently descriptive (I believe it is using the wrong one.

**Comment by logicalhan** [comment]
> Hey Han, I think issue was closed as it was implemented in #84373
> Anything left here?

@serathius pkg/kubelet/certificate/kubelet.go fails (as expected since it doesn't read consts from other files) but the error message isn't sufficiently descriptive (I believe it is using the wrong one.

**Comment by logicalhan** [comment]
/cc @coffeepac 

This is one of the existing issues, probably a good one for getting your feet wet. In order to repro, you can go into `pkg/kubelet/certificate/kubelet.go` and set one of the metrics to stable (like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/certificate/kubelet.go#L63). Then, if you run [hack/verify-generated-stable-metrics.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-generated-stable-metrics.sh), it should explode. The explosion is expected, since we don't currently support inferring consts/vars which are imported (which is what we specifically need).

**Comment by coffeepac** [comment]
@logicalhan I am able to repro the error from the hack/verify- script.  Is the ask to allow this metric because `metrics.KubeletSubsystem` is a resolvable string or to use an error message that says 'static analysis does not currently support strings defined outside of the `pkg/file` scope'?

**Comment by logicalhan** [comment]
The ask would be to resolve it to a string. It would involve having to pull in the dependent files and parse them though.

**Comment by coffeepac** [comment]
Okay.  I'll start working through this.

Any gotchas about this I should be aware of ahead of time?  Is there a list of packages we don't want to important strings from or should I be applying some kind of foul language filter?

**Comment by logicalhan** [comment]
No I think it should be okay to pull strings from any file, since these are all checked in. The one thing which seems like a gotcha to me are dynamically constructed strings, which may not be interpretable at compile time, like a string which is constructed with an input parameter from a function argument.

**Comment by coffeepac** [comment]
sounds good.  thank you.

**Comment by coffeepac** [comment]
actually, does that gotcha matter?  this seems to be a type analysis operation so even if the value is determined at runtime the type is still known when this hack/verify- runs so it should be fine to just check the type, right?

**Comment by logicalhan** [comment]
It does matter because there are two scripts.. the second generates the stable metric list and the reason we want to support const interpretation is so that we can expand our generator to alpha metrics (which there are way more of).

**Comment by coffeepac** [comment]
I've been working on this.  I am, as probably expected, struggling to locate the dependent files on disk.  But progress is being pursued at least.

**Comment by logicalhan** [comment]
> I've been working on this. I am, as probably expected, struggling to locate the dependent files on disk. But progress is being pursued at least.

Nice! Yeah it's definitely non-trivial functionality but it would be amazing to have since it would allow us to expand the scope of functionality quite a bit. 

One idea is to read all the files in a single pass, mapping from the golang package name to a list of files which correspond to that package name. This wouldn't be exact and perhaps there ways to improve on the heuristic, but it could be a decent starting point for gathering and parsing through the potential files that contain the var/const that needs to be resolved.

**Comment by coffeepac** [comment]
yep, I'm having trouble loading the files from the listed import paths.  I tried naively using GOPATH and GOMODCACHE just to see what happens and I think I need to go look how the compiler does it.

**Comment by coffeepac** [comment]
continuing issues:

**Comment by coffeepac** [comment]
the linked PR from me expanded scope to include all of k/k and stdlib.  we're still missing generic, go.mod specified packages.  do we want to include those or is this sufficient?

**Comment by logicalhan** [comment]
This is fixed.
