### ISSUE TITLE
Pod-level liveness probes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8186]
All of our health checks are currently on containers.  If a check fails, we restart the single container.  I'm looking at the DNS pod, which runs etcd and kube2sky and skydns.  We have a healthcheck for skydns - do a DNS lookup.  But sometimes it fails because there's an etcd failure or a kube2sky bug.  what I really want is to restart the whole pod when the healthcheck fails.

**Comment by rjnagal** [comment]
Shouldn't a probe for kube2sky/etcd catch this and restart those? It sounds more like a e2e probe. If the problem is, say a kube2sky bug, how would restart help?

**Comment by thockin** [comment]
There once was a bug in kube2sky's watch loop.  It stopped updating DNS.
Hypothetically we could TTL all our etcd entries and then the healthcheck
would fail and a whole-pod kill would fix it.

But point taken, kube2sky would not add new records but it would have old
records.  Maybe we should have a sentinel DNS value that has a TTL that
kube2sky has to update periodically.
