### ISSUE TITLE
Passed in context is ignored in some GCE operations 

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#81874]
**What happened**:
Ref #81771, there are some GCE wrapper functions that don't properly respect the passed in context, e.g:
https://github.com/kubernetes/kubernetes/blob/5a3301a59d0c4d5e76002cff99a2f5450d2eea80/staging/src/k8s.io/legacy-cloud-providers/gce/gce_routes.go#L41-L45

We need to figure out a better way to handle this, but I'm hesitate to change it right away without enough thinking. File this issue for tracking purpose.

cc @RainbowMango @dominikh

**Comment by tedyu** [comment]
How about checking the deadline of the passed in ctx:
```
	if deadline, hasDeadline := ctx.Deadline(); hasDeadline {
		// compute the timeout
		if timeout := time.Until(deadline); timeout > time.Hour {
			_, cancel := cloud.ContextWithCallTimeout()
			defer cancel()
		}
	}
```
If the timeout is longer than what cloud.ContextWithCallTimeout expects, create context with 1 hour timeout.

**Comment by RainbowMango** [comment]
We should consider ctx.cancel() as well as deadline.

```go
func (g *Cloud) ListRoutes(ctx context.Context, clusterName string) ([]*cloudprovider.Route, error) {
	timeoutCtx, cancel := cloud.ContextWithCallTimeout()

	timeout := time.NewTicker(1 * time.Hour)
	defer timeout.Stop()

	go func() {
		defer cancel()

		select {
		case <- ctx.Done(): // user cancelled or timeout at user side
		case <-timeout.C:  // exit goroutine in case (task finish before timeout)
		}
	}()

	mc := newRoutesMetricContext("list")
	prefix := truncateClusterName(clusterName)
	f := filter.Regexp("name", prefix+"-.*").AndRegexp("network", g.NetworkURL()).AndRegexp("description", k8sNodeRouteTag)
	routes, err := g.c.Routes().List(timeoutCtx, f)
```

How about monitor user's timeout like this? cancel our context when timeout.

**Comment by tedyu** [comment]
If the time period till ctx.Deadline() is shorter than 1 hour, there is no need to call cloud.ContextWithCallTimeout().
We can use ctx directly in that case.

**Comment by RainbowMango** [comment]
Another option may be better:
```diff
 func (g *Cloud) ListRoutes(ctx context.Context, clusterName string) ([]*cloudprovider.Route, error) {
-       timeoutCtx, cancel := cloud.ContextWithCallTimeout()
+       timeoutCtx, cancel := context.WithTimeout(ctx, 1 * time.Hour)
        defer cancel()
```
