### ISSUE TITLE
Allow modules that have an indirect dependency on k8s.io/kubernetes to do a minor module upgrade

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#81878]
Any module that has a dependency on `k8s.io/kubernetes` cannot do minor module upgrades. This is true regardless of whether the dependency is direct (module has a k8s.io/kubernetes import) or indirect (module imports something that has this k8s.io/kubernetes import).

Reproduce with the following:

```console
$ go get -u k8s.io/test-infra  # or anything with k8s.io/kubernetes in its go.mod file
...
go: k8s.io/metrics@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-proxy@v0.0.0: unknown revision v0.0.0
go: k8s.io/apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-scheduler@v0.0.0: unknown revision v0.0.0
go: k8s.io/csi-translation-lib@v0.0.0: unknown revision v0.0.0
go: k8s.io/cri-api@v0.0.0: unknown revision v0.0.0
go: k8s.io/sample-apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/code-generator@v0.0.0: unknown revision v0.0.0
go get: error loading module requirements
```

This happens because we intentionally ship a broken `go.mod` file declaring `v0.0.0` dependencies that do not exist, as a way to encourage them to use `k8s.io/metrics` instead of depending on the staging dir.

https://github.com/kubernetes/kubernetes/blob/1afcd7d0c8d9a649dbf6bb5f2707189e0ac8fd9a/go.mod#L148-L157

**Comment by fejta** [comment]
/cc @cjcullen 
I think this might be what you're running into

**Comment by liggitt** [comment]
The v0.0.0 versions mean something in your tree is depending directly on k8s.io/kubernetes, instead of one of the published staging repos

**Comment by fejta** [comment]
Any tips on how I can track down the indirect dependency on k8s.io/kubernetes?

**Comment by liggitt** [comment]
> Any tips on how I can track down the indirect dependency on k8s.io/kubernetes?

In your case, it looks like a direct dependency… test-infra depends directly on k8s.io/kubernetes

**Comment by fejta** [comment]
Can you point to a file in the repo that depends on it?

This isn't what go.mod says, and I am struggling to find any files that import it. I must be missing something?

**Comment by liggitt** [comment]
Oops, missed that it was indirect

`go mod graph` will tell you where that dependency comes from

**Comment by fejta** [comment]
Shouldn't `go mod tidy` work from within this repo?

**Comment by liggitt** [comment]
We script and verify use of `go mod tidy` in hack/update-vendor.sh

**Comment by Uzuku** [comment]
I encountered same error when importing virtual-kubelet, which imports k8s.io/kubernetes.
see https://github.com/virtual-kubelet/virtual-kubelet/issues/767

**Comment by jianzhangbjz** [comment]
Get the same issue when initing the `go.mod`. Must I replace all of the `k8s.io/kubernetes/test` with `k8s.io/test`? If yes, do we have a command to do it? So many files, I cannot do it one by one manually. Thanks!
```console
mac:openshift-tests-private jianzhang$ go build ./...
go: finding github.com/openshift/openshift-tests latest
go: finding github.com/openshift/library-go latest
go: finding github.com/RangelReale/osincli latest
go: k8s.io/kubernetes@v1.18.1 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by jianzhangbjz** [comment]
After replace `k8s.io/kubernetes/` by using the command: ` grep -rl "k8s.io/kubernetes" . | xargs sed -i "" 's/k8s.io\/kubernetes/k8s.io/g'`, still get the `k8s.io/kubectl` errors below, how to fix it? Thanks!
```console
mac:openshift-tests-private jianzhang$ go build ./...
go: finding github.com/openshift/library-go latest
go: finding github.com/openshift/openshift-tests latest
go: finding github.com/RangelReale/osincli latest
go: github.com/openshift/openshift-tests@v0.0.0-20200415025103-ee1cab1f937e requires
	k8s.io/kubectl@v0.0.0: reading k8s.io/kubectl/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by ghostsquad** [comment]
this doesn't seem to apply for anything at `k8s.io/kubernetes/pkg`. Is that stuff being moved?

**Comment by afirth** [comment]
/reopen

Seems like this is working for some things, but not others
Examples: `k8s.io/kubernetes/pkg/util/tolerations` and from @ghostsquad `k8s.io/kubernetes/pkg/auth`

**Comment by liggitt** [comment]
The `k8s.io/kubernetes` module is not intended for use as a library. The individual exported repos (e.g. `k8s.io/client-go`) have go.mod files with valid versions of all dependencies (not the v0.0.0 versions referenced in this issue's description), but have internal and external dependencies that change between minor versions, so do not claim support for `go get -u`

/close
