### ISSUE TITLE
Create command `evict` to evict a single pod

### ISSUE THREAD

**Issue by lukemassa** [kubernetes/kubernetes#81873]
**What would you like to be added**:

Create command `evict` to evict a pod/group of pods matching a label.

**Why is this needed**:

For debugging and testing `PodDisruptionBudgets`, it would be nice to be able to evict a specific pod/pods instead of draining an entire node.

https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api says to create an Eviction subresource then use curl, but this is clunky and hard to get right with auth.

I would assume this would have similar usage to say `logs`, just `kubectl evict ` followed by a pod or selector.

I'm more than happy to take a swing at it if people think this is a reasonable thing to have.

**Comment by rajatjindal** [comment]
Hi, I ended up implementing a kubectl plugin for this here:

https://github.com/rajatjindal/kubectl-evict-pod

this is a very simple implementation which just evict a specific pod, but surely can be extended to do it based on label selector (PR welcome).

Thanks
Rajat Jindal

**Comment by liggitt** [comment]
fyi, `kubectl drain` supports `--pod-selector` to filter down to specific pods

**Comment by lukemassa** [comment]
FYI it looks like this was implemented via krew https://github.com/rajatjindal/kubectl-evict-pod

**Comment by jtslear** [comment]
Hello, @jtslear as Bug Triage Shadow for 1.19. Assigning to sig-contributor-experience. If this is incorrect, please notify us and remove the sig.

/sig contributor-experience
