### ISSUE TITLE
Data discrepancy in Current memory usage metrics between kubectl top command and metrics exposed by kubelet(scraped by Prometheus)

### ISSUE THREAD

**Issue by achilles42** [kubernetes/kubernetes#81905]
**What happened**:
There is a metrics discrepancy in current memory usage metrics for pods. 
Using the following sources to view the memory usage for a pod
1. Kubectl top po <pod_name>
2. container_memory_usage_bytes metrics exposed by CAdvisor and scraped by Prometheus.

For example, a pod with memory request: 16GB, memory limit: 26 GB has current memory. Kubectl command is returning 7547Mi. Metrics container_memory_usage_bytes is showing 42GB of memory usage.

As per Kubernetes monitoring [Doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/monitoring_architecture.md) it should be same as the source of the metrics data is CAdvisor for both kubectl top and Kubelet.

Can someone from the community help me understand the difference between top command and metrics exposed by CAdvisor?

**What you expected to happen**: 

**Kubectl top**, metrics exposed by **kubelet** and **top** command(inside pod) should show the same result.

**How to reproduce it (as minimally and precisely as possible)**: 

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:38:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-gke.5", GitCommit:"5aa3a95d828fe45aab3611dfc4ebdc0341fe1507", GitTreeState:"clean", BuildDate:"2019-05-29T17:25:39Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): 
```
BUILD_ID=10895.23.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=e7d0ede66eb4efd21bf8935391cc2797f480c15f
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=69
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=69
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```
- Kernel (e.g. `uname -a`):
```
Linux gke-node-5c0fb5b8-cwk1 4.14.56+ #1 SMP Sat Aug 11 23:13:59 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**Comment by achilles42** [comment]
> @achilles42: There are no sig labels on this issue. Please add a sig label by either:
> 
> 1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
>    e.g., `@kubernetes/sig-contributor-experience-<group-suffix>` to notify the contributor experience sig, OR
> 2. specifying the label manually: `/sig <group-name>`
>    e.g., `/sig scalability` to apply the `sig/scalability` label
> 
> Note: Method 1 will trigger an email to the group. See the [group list](https://git.k8s.io/community/sig-list.md).
> The `<group-suffix>` in method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

**Comment by chelnak** [comment]
@achilles42 Did you work out what was causing this?

**Comment by achilles42** [comment]
Yes, that was happening due to misconfiguration in the Prometheus setup. Closing this issue, thanks.

**Comment by langecode** [comment]
May I ask what the actual misconfiguration turned out to be? I am seeing something similar.

```
kubectl top po
NAME                                            CPU(cores)   MEMORY(bytes)
xxx-54776f586c-62k4b   366m         1386Mi
xxx-54776f586c-ltsbf   74m          770Mi
xxx-54776f586c-n9ll6   183m         65Mi
xxx-54776f586c-zfvx7   215m         600Mi
```

Note container with postfix `62k4b`. If I look at `/metrics/cadvisor` on the kubelet I have:
```
container_memory_usage_bytes{container="consumer",container_name="consumer",id="/kubepods/burstable/pod4dd4585b-fc16-11e9-adb7-8aa6f091a905/a8c79e9db21083b0127b875db5fd7c36218d96319d08e01e67c8d75fa35434fb",image="xxx.azurecr.io/xxx/go-parquet-consumer@sha256:cbeaa57fee3886d0ddb4fcc0edfa1bcd8b735dc530b134aa9fb836143ca4bbd0",name="k8s_consumer_xxx-54776f586c-62k4b_xxx_4dd4585b-fc16-11e9-adb7-8aa6f091a905_0",namespace="xxx",pod="xxx-54776f586c-62k4b",pod_name="xxx-54776f586c-62k4b"} 2.898300928e+10 1572610623410
```
Should be about 26 GiB? So there is quite a huge difference between 1386 Mi and 26 GiB.

**Comment by achilles42** [comment]
Hey @langecode,
In my case, we had 2 services running for the same pod and Prometheus was scraping twice.


For your case, you should be looking at below query to match data with kubectl top command - 
```sum by(container_name) (container_memory_working_set_bytes{cluster_name="cluster-name",job="kubelet", namespace="default", pod_name="foobar-123n123n123n12", container_name=~"foobar", container_name!="POD"})```

**Comment by langecode** [comment]
Thank you for the feedback. Digging deeper into the cadvisor metrics I also discovered that `container_memory_working_set_bytes` would be the correct timeseries not `container_memory_usage_bytes`. I has just stitched together some Grafana dashboards based on coreos kube-prometheus - and they used the `container_memory_usage_bytes` metric.

**Comment by danksim** [comment]
> Should be about 26 GiB? So there is quite a huge difference between 1386 Mi and 26 GiB.

how can `container_memory_usage_bytes` be 26GiB and `container_memory_working_set_bytes`/`kubectl top pod` be 1386Mi? I am confused since the only difference would be cached files. Thoughts? @langecode @achilles42

**Comment by aman-raza** [comment]
why is it so that `kubectl top` command and the data scraped by prometheus is different
![image](https://github.com/kubernetes/kubernetes/assets/53443872/a1271cb6-887e-4925-b36c-0cb25ebb7b75)
and my grafana dashboard is showing this instead, a bit confused here
![image](https://github.com/kubernetes/kubernetes/assets/53443872/904c8fd9-0696-4a01-a754-e892b0a03a45)
the query used here is:
 ```sum by (pod) (container_memory_working_set_bytes{namespace="regal-perf"}) / count by (pod) (container_memory_working_set_bytes{namespace="regal-perf"})```
