### ISSUE TITLE
Events API hangs

### ISSUE THREAD

**Issue by Moshem123** [kubernetes/kubernetes#81906]
**What happened**:
I cannot run `kubectl describe...` for anything (deployment, pod, node, every possible object), I'm getting 504 Gateway Timeout:
```
I0825 19:06:28.639454   60294 round_trippers.go:438] GET https://internal-api.us-east-1.elb.amazonaws.com/api/v1/namespaces/kube-system/events?fieldSelector=involvedObject.name%3Dtiller-deploy%2CinvolvedObject.namespace%3Dkube-system%2CinvolvedObject.kind%3DDeployment%2CinvolvedObject.uid%3D2ff58c21-c74e-11e9-90e8-0aac4da3aa68 504 Gateway Timeout in 60143 milliseconds

I0825 19:06:28.639664   60294 request.go:947] Response Body: {"metadata":{},"status":"Failure","message":"Timeout: request did not complete within 1m0s","reason":"Timeout","details":{},"code":504}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl describe deployment -n kube-system tiller-deploy -v=10`

**Anything else we need to know?**:
I noticed only calls to `/api/.../events` are failing, all other API requests give the right output.
Seeing the api-server logs, I see a lot of:
```
E0825 16:04:33.192758       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
```
I don't know if it's related but that's all I have.
I tried deleting all of the service-account tokens:
```
kubectl get secret -A | grep "service-account-token" | while read -r line; do
  m_ns=$(awk '{print $1}' <<< "$line")
  m_name=$(awk '{print $2}' <<< "$line")
  kubectl delete secret -n $m_ns $m_name &
done
```
All of them got re-created, but the log is still the same,
I restarted API server pods on all masters, still the same,
I terminated the master instances (I'm running a KOPS cluster - not sure it's related), new masters came up, still the same.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): `PRETTY_NAME="Debian GNU/Linux 9 (stretch)"`
- Kernel (e.g. `uname -a`): `Linux ip-10-21-113-146 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug): calico

**Comment by roycaihw** [comment]
/sig auth

/sig cli
for cli error message

/sig cloud-provider
for AWS WG

the client-server version skew is huge and not supported, could you try using a 1.11 client to see if it helps?

**Comment by liggitt** [comment]
authentication issues would not cause a 504 error
/remove-sig auth

**Comment by liggitt** [comment]
Closing due to insufficient information
