### ISSUE TITLE
image tags is not correctly defined on arm paltform

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#81920]
**What happened**:
some of base images support multi-arch,  if no platform specified, the image pulled will actually reflect where the operation is performed, current implementation always assume the default platform is amd64 which make the tags is not correctly defined.

for example,

on arm64 platform, here is what I got after build the image of ipc-utils, 
```
# docker inspect gcr.io/kubernetes-e2e-test-images/ipc-utils-amd64:1.0
...
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 9732491,
        "VirtualSize": 9732491,
        "GraphDriver": {
  ...
```

**What you expected to happen**:
tag should be defined correctly

**How to reproduce it (as minimally and precisely as possible)**:
on arm64 platform, 
```
cd /test/images.
make all WHAT=ipc-utils
docker image ls | grep ipc-utils
docker image inspect gcr.io/kubernetes-e2e-test-images/ipc-utils-amd64:1.0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: all arch except x86 
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mkumatag** [comment]
This is the side effect of `docker build` command, you can fix it by specifying `--platform` tag while building the image.

**Comment by mkumatag** [comment]
The `--platform` tag is still experimentall and introduced in `API 1.32+` so I really doubt about using this anywhere, I feel it is just a cosmetic issue and only applies for the images with `-ARCH` tag. As we are pushing fat manifest images with proper archs so we don't have to worry much about it.
