### ISSUE TITLE
HTTP readiness/liveness probes always fail from Windows node against container running on same node

### ISSUE THREAD

**Issue by dcopestake** [kubernetes/kubernetes#81938]
**What happened**:

Readiness/liveness probes from a Windows node against container running on same node using `httpGet` always seem to fail causing a never-ending loop of pods being terminated and recreated.

**What you expected to happen**:

If I configure a readiness/liveness probe for a Windows container in a pod and that container is functioning as expected, I expect the probe to succeed and the pod to continue running.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add Windows node to a K8s cluster running in overlay mode
2. Create a pod with a Windows container which exposes an HTTP endpoint and a liveness/readiness `httpGet` probe that queries that endpoint
3. Note the pod getting terminated due to the failing probe
4. Update/patch the pod to remove the probe
5. Grab the pod IP
6. Query the probe target using the pod IP from a Linux node and confirm it succeeds
7. Query the probe target using the pod IP from the Windows node and note that it times out

**Anything else we need to know?**:

I've uploaded the [route table](https://github.com/coreos/flannel/files/3540852/route-table.txt) for the Windows node just in case that helps. I assume there should be routes configured for the pod network CIDR but I don't see any?

**Environment**:
- Kubernetes version: v1.15.1
- Cloud provider or hardware configuration: Local Hyper-V VMs
- OS: Windows Server 2019 1809 (17763)
- Network plugin and version: flannel 0.11.0

**Attachments**:
* [route-table.txt](https://github.com/coreos/flannel/files/3540852/route-table.txt)
* [net-conf.json](https://github.com/coreos/flannel/files/3540864/net-conf.json.txt)
* [cni.conf](https://github.com/coreos/flannel/files/3540865/cni.conf.txt)

**Comment by dcopestake** [comment]
@kubernetes/sig-windows

**Comment by dcopestake** [comment]
@kubernetes/sig-windows-bugs

**Comment by zhiweiv** [comment]
It is a Windows bug, https://github.com/Azure/AKS/issues/1014.

**Comment by dcopestake** [comment]
@daschott yep, or at least, when I manually downloaded and tried to install it failed saying it already was installed.

**Comment by dcopestake** [comment]
@zhiweiv forgive me as this may be my lack of knowledge showing here, but surely this is to do with the node not being able to communicate with the pod address? Azure/AKS#1014 seems to be more related to containers being unable to connect to external addresses?

**Comment by zhiweiv** [comment]
You can check this comment, https://github.com/Azure/AKS/issues/1014#issuecomment-522684583.

**Comment by dcopestake** [comment]
@zhiweiv yep, that's what @daschott was confirming, I have that KB applied.

**Comment by zhiweiv** [comment]
That is strange, it works fine for me and some other guys.

**Comment by zhaoyc1990** [comment]
[flannel#1096](https://github.com/coreos/flannel/pull/1096) Maybe it can help you.

**Comment by daschott** [comment]
Can you share the [collectlogs](https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1) output?

**Comment by NerdyGroupAffiliate** [comment]
I was going an issue with this.

When I did 

      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8  

In my deployment file

Then in the CoreDNS
I forwared 8.8.8.8  to Microsoft's name servers of 168.63.129.16.

The probes seemed to work.

Try this https://www.danielstechblog.io/setting-custom-upstream-nameservers-for-coredns-in-azure-kubernetes-service/

I am still working on the rolling updates though.

**Comment by daschott** [comment]
Is this issue still active? Neither Flannel upgrade nor KB helped?

**Comment by benmoss** [comment]
I am also running into this, running flanneld from master and KB4523205 installed. That's the latest cumulative one that I'm assuming includes all the previous stuff. Here's a gist with all the logs from collectlogs: https://gist.github.com/benmoss/9556574fc50b4153b75da98531e946f2

**Comment by ksubrmnn** [comment]
@dcopestake are you using FlannelD built from master? Unfortunately, we haven't gotten a new release yet which contains a fix you need for this to work.

**Comment by benmoss** [comment]
I don't the OP's issue was with with NodePort services as mentioned in #85611, I don't think you can even do a readiness/liveness probe through a service.

/reopen

**Comment by benmoss** [comment]
I ended up figuring out what was wrong for my cluster, it was just that L2Bridge CNI configuration was being applied instead of VXLAN :man_facepalming:. That doesn't seem to be the OP's issue though. Readiness probes are working as expected.

**Comment by vitaliy-leschenko** [comment]
@benmoss, can you say how to configure flannel via VXLAN to pass readiness probe if it fixed?
I used [this instructions](https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/).
When I use VXLAN mode, kubelet can't access to pod for readiness (and liveness) probe because node has no ip address in pod's network.
When I use "host-gw" pods can't access to node's network but readiness/liveness are working. Also in this mode flannel doesn't start after restart computer.

**Comment by benmoss** [comment]
Can you post the results of running `Get-HNSNetwork | ? Type -eq Overlay | Select-Object Name, Policies | ConvertTo-Json`

**Comment by benmoss** [comment]
I just made this simple Go app that will patch an HNS network to add the HostRoute policy: https://github.com/benmoss/fix-hostroute-policy, give it a shot to just patch your network. It'd be nice if this was possible with Powershell but I didn't see an easy way.

**Comment by vitaliy-leschenko** [comment]
```
PS C:\k> kubectl get nodes -o wide
NAME           STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION      CONTAINER-RUNTIME
k8s-master     Ready    master   24d   v1.16.3   192.168.2.17   <none>        Ubuntu 18.04.3 LTS        4.15.0-70-generic   docker://19.3.5
k8s-ws1809-1   Ready    worker   24d   v1.16.3   192.168.2.18   <none>        Windows Server Standard   10.0.17763.864      docker://19.3.4
k8s-ws1809-2   Ready    worker   24d   v1.16.3   192.168.2.19   <none>        Windows Server Standard   10.0.17763.864      docker://19.3.4
```

Results from k8s-ws1809-1 - 192.168.2.18
```
PS C:\k> Get-HNSNetwork | ? Type -eq Overlay | Select-Object Name, Policies | ConvertTo-Json
[
    {
        "Name":  "vxlan0",
        "Policies":  [
                         "@{DestinationPrefix=10.244.4.0/24; DistributedRouterMacAddress=00:15:5d:67:64:7d; IsolationId=4096; ProviderAddress=192.168.2.19; Type=RemoteSubnetRoute}",
                         "@{DestinationPrefix=10.244.0.0/24; DistributedRouterMacAddress=16:77:5c:1c:76:90; IsolationId=4096; ProviderAddress=192.168.2.17; Type=RemoteSubnetRoute}"
                     ]
    },
    {
        "Name":  "External",
        "Policies":  [

                     ]
    }
]
```
Resutls from k8s-ws1809-2 - 192.168.2.19
```
PS C:\k> Get-HNSNetwork | ? Type -eq Overlay | Select-Object Name, Policies | ConvertTo-Json
[
    {
        "Name":  "vxlan0",
        "Policies":  [
                         "@{DestinationPrefix=10.244.3.0/24; DistributedRouterMacAddress=00:15:5d:15:e9:f0; IsolationId=4096; ProviderAddress=192.168.2.18; Type=RemoteSubnetRoute}",
                         "@{DestinationPrefix=10.244.0.0/24; DistributedRouterMacAddress=16:77:5c:1c:76:90; IsolationId=4096; ProviderAddress=192.168.2.17; Type=RemoteSubnetRoute}"
                     ]
    },
    {
        "Name":  "External",
        "Policies":  [

                     ]
    }
]
```

**Comment by benmoss** [comment]
Yep, it's a result of running v0.11.0 of flannel. You can either run the binary from https://github.com/benmoss/fix-hostroute-policy to patch your network or switch to my pre-release version of Flannel [from here](https://github.com/benmoss/flannel/releases/tag/v0.12.0-rc1)

**Comment by vitaliy-leschenko** [comment]
I did both: patched vxlan0 and replaced flanneld.exe

May be this is another issue, may be not: I can't ping my local network from pods and pods from other nodes.

**Comment by ksubrmnn** [comment]
> @dcopestake are you using FlannelD built from master? Unfortunately, we haven't gotten a new release yet which contains a fix you need for this to work.

@benmoss @vitaliy-leschenko as mentioned here (:

**Comment by EagleIJoe** [comment]
flanneld 0.12.0 fixed it for me.
