### ISSUE TITLE
DNS healthchecks won't catch hung kube2sky or etcd

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8194]
if kube2sky hangs and stops adding new records to DNS, our health checking won't catch it.  Likewise if etcd fails to accept new writes.  I'm filing this so we come back to it later and work out a better answer.

**Comment by bprashanth** [comment]
Updating an etcd key every 10s through post should be easy, if we want soon.

**Comment by thockin** [comment]
@ArtfulCoder can you link this from you mondo PR's first comment, so it auto-closes

**Comment by thockin** [comment]
dup
