### ISSUE TITLE
Cleanup MakeFile/MakeDir in hostpath volume driver

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/kubernetes#81963]
**What would you like to be added**:

As part of https://github.com/kubernetes/kubernetes/pull/81739, it was discovered that the two methods `MakeFile` and `MakeDir` probably do not behave as expected. Details are captured [here](https://github.com/kubernetes/kubernetes/pull/81739#issuecomment-523623167), but the basic issues are:

- The methods do not do any check if the requested path already exists, and do not return an error if they do so
- To the above point, the two functions behavior differently from each other
- No attempt is made to ensure that the proper permissions exist if the directory/file already exist
- The `MakeFile` method will return no error if the file to be created already exists and is a directory

**Why is this needed**:

General correctness. The existing code has been working for `HostPath` for some time, but there are some edge cases here that may trigger unexpected side effects.

/sig storage
/kind cleanup

**Comment by erheron** [comment]
HI! Is this still actual? I would like to work on this, but I probably would need Your help @codenrhoden (this would be my first contribution)

**Comment by sshukun** [comment]
Looks like this is not solved yet, I would like to work on this.
/assign

**Comment by vaibhavk** [comment]
Hi, I would like to work on it.
/assign
