### ISSUE TITLE
I'm going to perform a timed task that I don't know how to write an expression like this every 90 minutes.

### ISSUE THREAD

**Issue by wangyp0701** [kubernetes/kubernetes#81979]
I'm going to perform a timed task that I don't know how to write an expression like this every 90 minutes

**Comment by zouyee** [comment]
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule

**Comment by wangyp0701** [comment]
> https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule

I know, but it doesn't seem to work every 90 minutes.

**Comment by Joseph-Irving** [comment]
/sig apps

Can you provide more information about your setup? The bug report template is a good place to start https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md.

Also can you share the cronjob that you're attempting to run? `kubectl get cronjob <cron-name> -o yaml` and `kubectl describe cronjob <cron-name> `

**Comment by Joseph-Irving** [comment]
It's worth pointing out that you can't easily write a cron job for every 90 minutes, `*/90 * * * *` is not valid, that means at the 90th minute of the hour.

You have to split it into two crons to achieve this see https://stackoverflow.com/questions/247626/how-can-i-set-cron-to-run-certain-commands-every-one-and-a-half-hours

**Comment by wangyp0701** [comment]
> 值得指出的是，你不能轻易地每90分钟编写一个cron作业，这`*/90 * * * *`是无效的，这意味着在每小时的第90分钟。
> 
> 你必须将它分成两个crons来实现这一点，请参阅[https://stackoverflow.com/questions/247626/how-can-i-set-cron-to-run-certain-commands-every-one-and-a-半小时](https://stackoverflow.com/questions/247626/how-can-i-set-cron-to-run-certain-commands-every-one-and-a-half-hours)

You're right
