### ISSUE TITLE
Properly deprecate ssh tunnel metrics

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#81984]
SSH tunnels are a deprecated feature, yet we emit metrics for them. We should properly deprecate ssh tunnel metric so we can remove them at a future date without breaking people's ingestion pipelines. 

/cc @cheftako 
/sig api-machinery
/sig instrumentation

**Comment by irajdeep** [comment]
@logicalhan I can work on this if no one else is currently.

**Comment by irajdeep** [comment]
Hey folks, just to double-check the ssh-tunnel metrics are: `tunnelOpenCounter` and `tunnelOpenFailCounter` . Right?

**Comment by cheftako** [comment]
Yes. the actual metrics show up as : 

# HELP ssh_tunnel_open_count [ALPHA] Counter of ssh tunnel total open attempts
# TYPE ssh_tunnel_open_count counter
ssh_tunnel_open_count 0

# HELP ssh_tunnel_open_fail_count [ALPHA] Counter of ssh tunnel failed open attempts
# TYPE ssh_tunnel_open_fail_count counter
ssh_tunnel_open_fail_count 0

**Comment by RainbowMango** [comment]
@irajdeep 
Are you ok to back to this issue?

I think you can just deprecate them by `DeprecatedVersion` field of counter opts. 
```diff
diff --git a/pkg/ssh/ssh.go b/pkg/ssh/ssh.go
index 5b6072244ac..7d2dfb79d58 100644
--- a/pkg/ssh/ssh.go
+++ b/pkg/ssh/ssh.go
@@ -57,16 +57,18 @@ import (
 var (
        tunnelOpenCounter = metrics.NewCounter(
                &metrics.CounterOpts{
-                       Name:           "ssh_tunnel_open_count",
-                       Help:           "Counter of ssh tunnel total open attempts",
-                       StabilityLevel: metrics.ALPHA,
+                       Name:              "ssh_tunnel_open_count",
+                       Help:              "Counter of ssh tunnel total open attempts",
+                       StabilityLevel:    metrics.ALPHA,
+                       DeprecatedVersion: "1.18.0",
                },
        )
        tunnelOpenFailCounter = metrics.NewCounter(
                &metrics.CounterOpts{
-                       Name:           "ssh_tunnel_open_fail_count",
-                       Help:           "Counter of ssh tunnel failed open attempts",
-                       StabilityLevel: metrics.ALPHA,
+                       Name:              "ssh_tunnel_open_fail_count",
+                       Help:              "Counter of ssh tunnel failed open attempts",
+                       StabilityLevel:    metrics.ALPHA,
+                       DeprecatedVersion: "1.18.0",
                },
        )
 )

```

**Comment by irajdeep** [comment]
@RainbowMango sure I can do that, I will update the corresponding PR:
https://github.com/kubernetes/kubernetes/pull/82627
