### ISSUE TITLE
No reliable way to get original YAML used to create a resource

### ISSUE THREAD

**Issue by hanoisteve** [kubernetes/kubernetes#81999]
**What happened**:
I simply wanted to get back the original yaml file used to create a resource on Kubernetes cluster. So far either its not documented or this feature does not exist. Its a non trivial problem to go about deleting not needed fields etc that were added to the original yaml. Why would it not be available to compare with the updated yaml?  Of course we could version it outside kubernetes but this has no advantages since its a deployment operation that determines the exact yaml in use.

**What you expected to happen**:
That there would be an option to get back the original yaml used to create the resource.
I am aware of both and -export option (deprecated) and -o yaml
**How to reproduce it (as minimally and precisely as possible)**:
On any resource you always get back additional fields like status etc.  What about the original yaml used to create the resource in the first place? Where is this kept? And how can I get it back.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12 multiple versions
- Cloud provider or hardware configuration:GCP and Bare Metal
- OS (e.g: `cat /etc/os-release`):Ubuntu Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig docs /sig usability /sig cli

**Comment by Joseph-Irving** [comment]
There is no way to get the original yaml at present, export was deprecated (https://github.com/kubernetes/kubernetes/pull/73787) and the potential replacement of server-side exporting does not appear to be progressing (https://github.com/kubernetes/kubernetes/issues/24855).

Depending on your use case you could potentially look at keeping your manifests in version control or you can write a script to remove some of the added fields such as status, see https://github.com/tmattausch/k8s-cluster-export for some examples.

**Comment by hanoisteve** [comment]
I think this feature should be implemented because:
1) The devops engineer does not necessarily have access to the versioned yaml files.
2) Its not clear how to track a given version of a file to a deployment in kubernetes.  
3) There is no reason not to keep this original state. Its part of the history of the state of the deployment of the resource. Its stage: 0.  The fact that it is versioned in a file somewhere is not really something that a devops engineer should be concerned with. He should have a history that starts from the beginning and be able to reproduce a deployment exactly as it was deployed initially without accessing a versioned file somewhere.

**Comment by stedwick** [comment]
+1

**Comment by piotr-ce** [comment]
+1

**Comment by borissnd** [comment]
+1
