### ISSUE TITLE
Issue related to kubernetes cluster initailization on ubuntu 18.04

### ISSUE THREAD

**Issue by Soorya135** [kubernetes/kubernetes#82001]
**What happened**:
As part of running the kubernetes cluster initialiazation getting below error.

root@btpvm0863:~# sudo kubeadm init --pod-network-cidr=10.244.10.0/16 --apiserver-advertise-address=10.0.15.10 --kubernetes-version "1.14.0"
[init] Using Kubernetes version: v1.14.0
[preflight] Running pre-flight checks
        [WARNING HTTPProxy]: Connection to "https://10.0.15.10" uses proxy "http://web-proxy.in.softwaregrp.net:8080". If that is not intended, adjust your proxy settings
        [WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://web-proxy.in.softwaregrp.net:8080". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
        [WARNING HTTPProxyCIDR]: connection to "10.244.10.0/16" uses proxy "http://web-proxy.in.softwaregrp.net:8080". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [btpvm0863.hpeswlab.net localhost] and IPs [10.0.15.10 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [btpvm0863.hpeswlab.net localhost] and IPs [10.0.15.10 127.0.0.1 ::1]
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [btpvm0863.hpeswlab.net kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.0.15.10]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster

**What you expected to happen**:
Cluser initializtion should happen sucessfully.

**How to reproduce it (as minimally and precisely as possible)**:
run kubernetes init cluster initilaization command.

**Anything else we need to know?**:
============================================================
output of systemctl status kubelet

● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2019-08-27 11:48:08 IST; 9min ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 10545 (kubelet)
    Tasks: 16 (limit: 4663)
   CGroup: /system.slice/kubelet.service
           └─10545 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgr

Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.034517   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.134958   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.235472   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.335898   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.374652   10545 controller.go:115] failed to ensure node lease exists, will retry in 7s, error: Get https://10.0.15.10:6443/apis
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.436367   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.469722   10545 kubelet.go:2170] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:do
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.537268   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.638770   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 11:57:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 11:57:44.739600   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not fo

=====================================================
Output of 
journalctl -xeu kubelet

root@btpvm0863:~# journalctl -xeu kubelet
Aug 27 12:00:41 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:41.827444   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:41 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:41.928525   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.029529   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.130236   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.231180   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.331613   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.431981   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.532497   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.633178   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.734087   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.835056   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:42 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:42.936253   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.037286   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.138362   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.240317   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.340603   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.440985   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.541343   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.641596   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: W0827 12:00:43.721942   10545 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.741907   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.842552   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:43 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:43.943015   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.043539   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.144030   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.244999   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.345410   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.445917   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.542393   10545 certificate_manager.go:385] Failed while requesting a signed certificate from the master: cannot create certific
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.546407   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.602554   10545 kubelet.go:2170] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:do
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.647408   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.747825   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.848355   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:44 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:44.948993   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:45 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:45.050051   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:45 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:45.150456   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:45 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:45.250871   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:45 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:45.351546   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:45 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:45.451980   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found
Aug 27 12:00:45 btpvm0863.hpeswlab.net kubelet[10545]: E0827 12:00:45.552422   10545 kubelet.go:2244] node "btpvm0863.hpeswlab.net" not found

**Environment**:
- Kubernetes version (use `kubectl version`):

root@btpvm0863:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@btpvm0863:~#

- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):

root@btpvm0863:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@btpvm0863:~#

- Kernel (e.g. `uname -a`):

root@btpvm0863:~# uname -a
Linux btpvm0863.hpeswlab.net 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
  

/sig bug

**Comment by Soorya135** [comment]
@kubernetes/sig-experience-bugs

**Comment by Soorya135** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by danielszot** [comment]
Where you have http_proxy configured? Is that added to /etc/environment?
To avoid proxying internal traffic, you should also add "no_proxy" in the same place with list of IP's you use internally, like k8s node IP addresses.
