### ISSUE TITLE
full stack trace in E2E testing incorrect (Ginkgo bug)

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#82013]
**What happened**:

Ginkgo no longer handles the `runtime.Stack()` from current Go correctly, which leads to broken output when using `e2e.test -ginkgo.trace`:
```  Full Stack Trace
=>  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/util.go:1362 +0x112
=>  k8s.io/kubernetes/test/e2e/framework.ExpectNoError(...)
=>  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/util.go:1356
  k8s.io/kubernetes/test/e2e/framework/log_test.glob..func1.4()
  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/log/logger_test.go:49 +0xc9
  k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00053ea20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/log/logger_test.go:65 +0x1c8
  testing.tRunner(0xc00023ac00, 0x1aa7818)
  	/nvme/gopath/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/nvme/gopath/go/src/testing/testing.go:916 +0x35a
```

**What you expected to happen**:

The output should start with:
```
  k8s.io/kubernetes/test/e2e/framework/log_test.glob..func1.4()
  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/log/logger_test.go:49 +0xc9
```

**How to reproduce it (as minimally and precisely as possible)**:

See `TestFailureOutput` in test/e2e/framework/log/logger_test.go.

**Anything else we need to know?**:

Steps to fix it:
- get https://github.com/onsi/ginkgo/pull/590 merged
- update Ginkgo in Kubernetes
- re-enabled the commented out test case in test/e2e/framework/log/logger_test.go
- update test cases in that file

/area e2e-test-framework

**Comment by beautytiger** [comment]
how about let me working on this?
/assign

**Comment by pohly** [comment]
I forgot that I had opened a bug for this. https://github.com/kubernetes/kubernetes/pull/82176 fixes all of the aspects of this problem.

**Comment by pohly** [comment]
@beautytiger: But thanks for your offer to help nonetheless!

**Comment by beautytiger** [comment]
Ok, got it.
