### ISSUE TITLE
[Flaky tests] ci-kubernetes-node-kubelet-serial

### ISSUE THREAD

**Issue by odinuge** [kubernetes/kubernetes#82017]
**Which jobs are failing**:

`ci-kubernetes-node-kubelet-serial`

**Which test(s) are failing**:
Several tests

Eg. this run: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1166025651765907456

**Since when has it been failing**:
Unknown

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Reason for failure**:

`ErrImageNeverPull: Container image "google/cadvisor:latest" is not present with pull policy of Never` (happens to all the images).

Pods in the e2e test suites use pull policy [Never](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pods.go#L213), , and it looks like the test `[k8s.io] SystemNodeCriticalPod [Slow] [Serial] [Disruptive] [NodeFeature:SystemNodeCriticalPod]` [evicts pods](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system_node_critical_test.go#L75) during DiskPressure, resulting in kubelet removing some of the pre pulled images.

**Anything else we need to know**:
The `EvictionTest` runs `PrePullAllImages` after each test. This should also be the case in the `SystemNodeCriticalPod` test too.

**Comment by odinuge** [comment]
These tests are now constantly failing due to missing images. This makes it hard to see if some of the stuff we do now, or have done in the last few weeks, breaks some of the tests. PR #82018 should hopefully fix this, but it is not in the 1.16 milestone, but has `/lgtm` and `/approve`.

Should we get this merged into master so that we can see if if fixes the problem, or should we wait until code thaw? Any thoughts?

/cc @alejandrox1
/cc @mattjmcnaughton 
/cc @oomichi

**Comment by alejandrox1** [comment]
Thanks for all the work you've put into this @odinuge ! I think we should add #82018 to the milestone

**Comment by mattjmcnaughton** [comment]
+1 to @alejandrox1  - thanks for your hard work @odinuge :)

**Comment by alejandrox1** [comment]
@odinuge @mattjmcnaughton https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial still has a lot of failing tests. What are the next steps?

/reopen

**Comment by odinuge** [comment]
Yes, it has over the few last weeks become quite a mess... Looks like  #82018 fixed some of the issues about image eviction problems, but there are still a few left. I think I have a solution, so ill try to submit a PR in a few hours.

A lot of new tests started failing 8-28, and that may be related to #81534, but I am not totally sure..

**Comment by odinuge** [comment]
Looks like #82654 fixed the flaking in https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial!
The last 7 runs was executed after that was merged!

![Screenshot from 2019-09-25 11-02-32](https://user-images.githubusercontent.com/1467188/65586243-21f6a480-df84-11e9-9e97-fbf558af18de.png)


We still have a lot of failing tests, but those are not flaky; they are failing (ref. comment above).

Ill create a new issue about all the failing tests where we can track them each together.

Closing this issue, as this was only filed for the flaking becuase of the evicted images. :smile: 

/close
cc @alejandrox1
