### ISSUE TITLE
kubectl cluster-info dump -o yaml output invalid file extension 

### ISSUE THREAD

**Issue by hajmsta** [kubernetes/kubernetes#82011]
When cluster information is dumped by operating the kubectl command, the file name extension is not appropriate.
example:
 kubectl cluster-info dump --output-directory=./xxxxxxx/  
 this command works fine, but 
 kubectl cluster-info dump -o yaml --output-directory=./xxxxxxx/
 this command works output configuration file with yaml format, but the file extension is json.
 head -5 ./xxxxxxx/nodes.json
 --------
 apiVersion: v1
 items:
 - metadata:
     annotations:
       node.alpha.kubernetes.io/ttl: "0"
 --------
- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9+IKS", GitCommit:"858a7bdfc1b3c9dd7a4a035e563a13eb87587de4", GitTreeState:"clean", BuildDate:"2019-08-07T11:03:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sftim** [comment]
Slightly related to issue #87868

**Comment by hally9k** [comment]
Bump, this is still an issue I think...

**Comment by olivierlemasle** [comment]
@hally9k It should be fixed by #82070
Did you test on `master`?

**Comment by hally9k** [comment]
Oops misread the ci-bots message, apologies for the noise.
