### ISSUE TITLE
DNS subdomain validation is wrong

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8202]
We validate that the total length is < 253, but we do not validate that each part is < 63 characters.

@smarterclayton since this is technically a breaking change

**Comment by smarterclayton** [comment]
Ugh, yeah, we should fix this.  I bet this breaks some people...

**Comment by liggitt** [comment]
And now that namespace is limited to a single segment, namespace would have to be < 63 chars as well?

**Comment by thockin** [comment]
Namespace validation in #8140

**Comment by thockin** [comment]
Reasonably easy for someone to contribute!

**Comment by kargakis** [comment]
cc: @shiywang @wanghaoran1988

**Comment by wanghaoran1988** [comment]
@shiywang Any updates?

**Comment by shiywang** [comment]
@wanghaoran1988 sorry, I haven't started, you could work on this first if you want

**Comment by thockin** [comment]
too late.  I don't think we can actually fix this without breaking.
