### ISSUE TITLE
Serialization of fieldsets in managedFields should always be the same

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/kubernetes#82042]
**What happened**:
The serialization of managedFields field sets can change, resulting in an otherwise no-op update causing a write to etcd. The issue arises when a fieldset like this
```
"k:{\"name\":\"test-container-a\"}": {
    ".": {},		
    "f:image": {},
    "f:name": {}
}
```
is decoded and re-encoded as part of a modifying request, which causes it to become
```
"k:{\"name\":\"test-container-a\"}": {
    "f:image": {},
    "f:name": {}
    ".": {},		
},
```

This isn't too serious, as it only seems to happen on the first update after a new list item is added, but we should try to understand this better and fix it.

**What you expected to happen**:
The fieldset serialization should be unaffected by round tripping through the internal structured-merge-diff type.

/sig api-machinery
/wg apply
/priority help-wanted
/cc @lavalamp @apelisse

**Comment by lavalamp** [comment]
oh wait. I thought (during the bug scrub) this was a PR to fix the problem and got excited

**Comment by jennybuckley** [comment]
/reopen
It looks like this issue still occurs under certain conditions, might be the cause of https://github.com/kubernetes/kubernetes/issues/87131
