### ISSUE TITLE
Support statically configured ValidatingAdmissionWebhook / MutatingAdmissionWebhook in apiserver

### ISSUE THREAD

**Issue by jmillikin-stripe** [kubernetes/kubernetes#82052]
**What would you like to be added**:
The `ImagePolicyWebhook` and `SubjectAccessReview` webhooks are both configured statically via `apiserver` command-line flags. This feature request is for similar static configuration to be available for `ValidatingAdmissionWebhook` and `MutatingAdmissionWebhook`.

A reasonable implementation might be flags that take the path to a file, which contains the appropriate configuration resource (e.g. `ValidatingWebhookConfiguration`).

**Why is this needed**:
Stripe uses admission control as part of our authorization policy, to enforce rules such as "pods in a dedicated namespace may only schedule on that namespace's dedicated machines". Our control plane runs in static pods on dedicated `kubemaster` machines, with each `apiserver` sending webhooks only to processes running on its local machine.

This doesn't work well with webhooks defined in cluster state, because the URL that the apiserver includes the local machine's hostname. It's also rather difficult to cleanly mutate cluster state during bootstrap (we don't have any sort of elaborate `kops`-style tools).

/sig api-machinery

**Comment by lavalamp** [comment]
I think the primary argument for something like this is the desire to have webhooks that the end user cannot mutate. I am not sure that static config file is the best way to offer that-- maybe we can come up with some auth/policy mechanism instead.

> This doesn't work well with webhooks defined in cluster state, because the URL that the apiserver includes the local machine's hostname

You should be able to make a URL that goes to localhost? https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#url

**Comment by jmillikin-stripe** [comment]
> I think the primary argument for something like this is the desire to have webhooks that the end user cannot mutate. I am not sure that static config file is the best way to offer that-- maybe we can come up with some auth/policy mechanism instead.

From a strictly authz perspective, the existing `SubjectAccessReview` webhook is enough to prevent modification of the `ValidatingWebhookConfiguration ` resources. It still depends on etcd state, though, which is undesirable for core components of the control plane. Our general goal is that it should be possible to bootstrap a cluster up to the "schedule hello-world pod" stage without having to make any mutating requests to the kubemaster.

> You should be able to make a URL that goes to localhost? https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#url

`https://localhost/` isn't commonly supported by most TLS certificates -- our machine certs only have SANs containing the machine hostnames, for example.

**Comment by lavalamp** [comment]
> From a strictly authz perspective, the existing `SubjectAccessReview` webhook is enough to prevent modification of the `ValidatingWebhookConfiguration` resources.

Yes, but you have to write something custom for that. It's hard to do this with e.g. RBAC while still permitting users to run their own webhooks.

> It still depends on etcd state, though, which is undesirable for core components of the control plane.

Why is that undesirable?

>  Our general goal is that it should be possible to bootstrap a cluster up to the "schedule hello-world pod" stage without having to make any mutating requests to the kubemaster.

apiserver does internal self-requests on startup, so what you say is not possible if interpreted sufficiently literally. Why is this a goal?

> `https://localhost/` isn't commonly supported by most TLS certificates -- our machine certs only have SANs containing the machine hostnames, for example.

That's an interesting point, if you're using premade certs. I think you would have this problem even if you configured the webhooks via static file?

Is there a reason why using the addon manager delivery mechanism doesn't work for you?

**Comment by jmillikin-stripe** [comment]
> Yes, but you have to write something custom for that. It's hard to do this with e.g. RBAC while still permitting users to run their own webhooks.

I think it's fair to say that if you're using Kubernetes in an advanced enough way to need admission controllers, it's fine to say you need to write some custom code. The whole point of an admission controller webhook is to inject custom behavior into the Kubernetes API, after all.

We don't want product teams to be able to inject webhooks into the cluster. That permission is reserved for the cluster operations team.

>> It still depends on etcd state, though, which is undesirable for core components of the control plane.
>
> Why is that undesirable?

If a cluster can be bootstrapped without mutating etcd state, then the entire process can be automated using cloud provider primitives (e.g. AWS auto-scaling groups, or GCP's equivalent). If etcd state needs to be mutated during that process then you need a bootstrap service that can manage cluster lifetimes, and somewhere to store state about what stage of bootstrap each cluster is in.

> apiserver does internal self-requests on startup, so what you say is not possible if interpreted sufficiently literally. Why is this a goal?

This only applies to requests a human (or human-like automation) needs to make. I don't want the equivalent of `kubectl apply -f` to be in the boostrap path. If the apiserver itself needs to take out a service lease or something, that's fine, it doesn't affect the externally visible behavior.

> That's an interesting point, if you're using premade certs. I think you would have this problem even if you configured the webhooks via static file?

We can inject the current machine's hostname into the static file (the open-source world has many things that approximate MSV).

> Is there a reason why using the addon manager delivery mechanism doesn't work for you?

We don't allow pods to be scheduled onto the control plane. It's a lot easier to reason about the security properties of a cluster if there's a hard line between privileged and unprivileged components, with privileged components running on machines that can't be compromised via the API.

**Comment by lavalamp** [comment]
> We don't want product teams to be able to inject webhooks into the cluster. 

Webhooks are getting added into conformance tests as we speak, BTW.

> I don't want the equivalent of kubectl apply -f to be in the boostrap path.

I don't understand why not?

> > Is there a reason why using the addon manager delivery mechanism doesn't work for you?

> We don't allow pods to be scheduled onto the control plane. 

You don't need to start doing that to use the addon manager (or similar mechanism) to deliver the webhook configuration manifest to apiserver?

I think over time there will be more, not less, thingies (webhooks, CRDs, ...) where you'll want to apply them as part of cluster start up. The project doesn't have a canonical way of doing this at the moment; it's a general problem, and I don't think we should solve it only for webhooks, we need a general mechanism.
