### ISSUE TITLE
docker environment install kubernetes error

### ISSUE THREAD

**Issue by kevinsingapore** [kubernetes/kubernetes#82068]
1、Tencent vps machine , centos7 ;
2、docker version : 19.03.1
3、after run 'make quick-release' , errors ocurred like below:
[root@VM_16_5_centos kubernetes]# make quick-release
+++ [0828 16:31:06] Verifying Prerequisites....
+++ [0828 16:31:11] Building Docker image kube-build:build-8c3f89370d-5-v1.12.9-1
+++ [0828 16:31:13] Syncing sources to container
+++ [0828 16:31:18] Running build command...
+++ [0828 16:32:06] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
+++ [0828 16:34:11] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kubeadm
    cmd/kubelet
+++ [0828 16:34:56] Building go targets for linux/amd64:
    cmd/kubectl
+++ [0828 16:35:15] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cluster/images/conformance/go-runner
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
k8s.io/kubernetes/cmd/genkubedocs
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: signal: killed

!!! [0828 16:36:17] Call tree:
!!! [0828 16:36:17]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:714 kube::golang::build_some_binaries(...)
!!! [0828 16:36:17]  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:853 kube::golang::build_binaries_for_platform(...)
!!! [0828 16:36:17]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0828 16:36:17] Call tree:
!!! [0828 16:36:17]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0828 16:36:17] Call tree:
!!! [0828 16:36:17]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile:93: all] Error 1
make: *** [Makefile:520: cross] Error 1
!!! [0828 16:36:17] Call tree:
!!! [0828 16:36:17]  1: build/../build/common.sh:521 kube::build::run_build_command_ex(...)
!!! [0828 16:36:17]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [quick-release] Error 1
[root@VM_16_5_centos kubernetes]#
4、how to solve the prolem? thank u!

**Comment by hoyho** [comment]
Have you pulled the builder image to your vps.  Since the image is published at gcr.io , it is not easy to pull it due to Chinese GFW.

**Comment by kevinsingapore** [comment]
> Have you pulled the builder image to your vps. Since the image is published at gcr.io , it is not easy to pull it due to Chinese GFW.

yes，i had pulled the builder image；and the Tencent VPS in hongkong Zone，so the vps has the hongkong zone ip，there is no GFW.

**Comment by xiaoanyunfei** [comment]
How much memory does your vm have, It seems like an OOM kill

**Comment by kevinsingapore** [comment]
> How much memory does your vm have, It seems like an OOM kill

8G

**Comment by neolit123** [comment]
/remove-kind bug
/triage support

8G should be enough for a quick release build...unless it now needs more.
i have seen these numbers grow constantly over time.

**Comment by justaugustus** [comment]
@kevinsingapore -- Are you still having issues with this?
/remove-lifecycle stale

**Comment by kevinsingapore** [comment]
> @kevinsingapore -- Are you still having issues with this?
> /remove-lifecycle stale

have solved it. thank u!

**Comment by justaugustus** [comment]
Thanks for the update!
/close
