### ISSUE TITLE
How to change context for just one shell session etc

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#82098]
On our jenkins server, I use docker to run kubectl, because apparently kubectl context is global (based on files in user $HOME). And I want to make sure there's not context conflicts, so I run kubectl from within containers. So my question is - is there a way to change the kubectl context just for the current process or shell session? This would be a useful feature, maybe put it behind a flag --local or something.

Or maybe there's a way to use context inline, like:

```bash
 kubectl get pods --namespace foo --context bar
```

/sig cli

**Comment by liggitt** [comment]
kubectl takes a --context flag that allows this

/close
