### ISSUE TITLE
Enable scopelint in k/k

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubernetes#82117]
**What happened**:
We have a lot of code like this:
```go
	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			out := templateYAMLIndent(tc.indent, tc.input)
			if out != tc.expected {
				t.Fatalf("\nout:\n%+q\nexpected:\n%+q\n", out, tc.expected)
			}
		})
	}
```
`scopelint` will report the following error:
```sh
Using the variable on range scope `tc` in function literal
```
This is because we used the variable loop of range in the anonymous function.
The right way to do it is to redeclare the range variable, like:
```go
	for _, tc := range testcases {
                tc := tc
		t.Run(tc.name, func(t *testing.T) {
			out := templateYAMLIndent(tc.indent, tc.input)
			if out != tc.expected {
				t.Fatalf("\nout:\n%+q\nexpected:\n%+q\n", out, tc.expected)
			}
		})
	}
```

In some cases, this may cause potential concurrency problems.
We should introduce `scopelint` to avoid potential problems.
If it makes sense, I'm willing to try to enable `scopelint` in k/k.

/sig testing
/cc @fejta @dims 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
+1, we're using scopelint in kind via golangci-linter. there is another issue open about considering migrating to that and enabling more lints, it would be great if someone wanted to figure that out
