### ISSUE TITLE
k8s Pod running but describe pod can see :Liveness probe errored: rpc error: code=Unknow desc = Error: no such container xxxxxxx , docker ps -a has no such container

### ISSUE THREAD

**Issue by mengqiuyuwl** [kubernetes/kubernetes#82126]
**What happened**:
After reboot my linux vm,rabbit cluster not healty

kubectl get pod|grep rabbit,see:
rabbitmq-2-0 1/1 Running 0 9d 172.34.230.185 192.168.56.88

but kubectl describe pod rabbitmq-2-0,see:
Normal Pulled kubelet, 192.168.56.88 Container image "h3crd-wlan1.chinacloudapp.cn:5000/rabbitmq:v5" already present on machine
Normal Created kubelet, 192.168.56.88 Created container
Normal Started kubelet, 192.168.56.88 Started container
Warning Unhealthy (x5 over ) kubelet, 192.168.56.88 Liveness probe errored: rpc error: code = Unknown desc = Error: No such container: 8f855a814a503b0c7748f58212bef343448f7a5544ba7a6a8e1aa9f44708632e

[root@centos88 kubelet]# docker ps -a|grep rabbit
9b1335ed6eec h3crd-wlan1.chinacloudapp.cn:5000/private-cloud/pause-amd64:3.1 "/pause" Less than a second ago Up Less than a second k8s_POD_rabbitmq-2-0_default_d0765531-ca24-11e9-8257-525400672304_0
only pause container ,no rabbit container
after restart pod,it is running.

**What you expected to happen**:
reboot linux ,  all pod will be ok
**How to reproduce it (as minimally and precisely as possible)**:
reboot linux much times
**Anything else we need to know?**:
**Environment**:
- Kubernetes version (use `kubectl version`):k8s version:1.11.6 docker version:1.13.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos7.4
- Kernel (e.g. `uname -a`):,kernel 3.10.693
- Install tools:
- Network plugin and version (if this is a network-related bug):
calico3.7.5
- Others:

**Comment by neolit123** [comment]
/sig node

> k8s version:1.11.6
hi, 1.11 is outside of the supported versions for k8s.
please try with at least k8s 1.13+ and re-open if the problem persists.

/close

**Comment by shaopenghui** [comment]
I also have this problem
I found that the state of the containers is running when I describe pod
However, in fact, this container does not exist
k8s version:1.15.3
docker version:1.13.1

**Comment by ChanKunggc** [comment]
I have the same problem. Can ofiicals provide some idea about thie problem?

**Comment by mengqiuyuwl** [comment]
@neolit123 neolit123
@k8s-ci-robot 
i upgrade docker version and k8s version but problem exists
k8s version:1.15.3
docker version:1.13.1

**Comment by feige0304** [comment]
I also have this problem
I found that the state of the containers is running when I describe pod
However, in fact, this container does not exist
k8s version:1.15.9
docker version:18.09

**Comment by feige0304** [comment]
this issue should be reopened.
