### ISSUE TITLE
Error while submitting spark jobs on k8s V1.14.6

### ISSUE THREAD

**Issue by dharam1** [kubernetes/kubernetes#82131]
In previous version of K8s i.e. 1.12.x spark jobs were running properly, but when i update the version to 1.14.6 and running spark jobs on updated version faced the following error:

Error : 566984292910-driver-svc.default.svc:7078/jars/spark-examples_2.11-2.4.0.jar with timestamp 1566984300797
2019-08-28 09:25:02 INFO  ExecutorPodsAllocator:54 - Going to request 2 executors from Kubernetes.
2019-08-28 09:25:02 WARN  WatchConnectionManager:185 - Exec Failure: HTTP 403, Status: 403 -
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

If anyone can help with this. Would really appreciate it. Productionn landscape is getting break due to this.
Thanks.

**Comment by neolit123** [comment]
have you tried contacting the spark developers about this?

**Comment by chamhaw** [comment]
same issue +1

**Comment by dharam1** [comment]
I dont think it's the issue on spark end as everything works perfectly in kubernetes v1.14.5. I think there is some security patch issue in k8s. I found something relevant if it might help everyone.
https://issues.jenkins-ci.org/browse/JENKINS-59000?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by chamhaw** [comment]
Also, there is a question on StackOverFlow for the issue.
https://stackoverflow.com/questions/57643079/kubernetes-watchconnectionmanager-exec-failure-http-403

**Comment by dharam1** [comment]
Yeah kubernetes client jar in spark image solved the issue. Apparently jar in spark was of old version (4.1.2).  Update it to 4.4.2 works perfectly.

**Comment by dharam1** [comment]
Updating kubernetes client jar to latest version in spark image solved the issue. Apparently jar in spark was of old version (4.1.2). Updated it to 4.4.2 works perfectly.

**Comment by aymankh86** [comment]
I replaced kubernetes-client default version with 4.4.2 still didn't work. I tried 4.3.1 then worked for me? is this issue will be fixed in future version of spark?

**Comment by Jeffwan** [comment]
The change has been merged back to Spark-2.4 branch.

**Comment by albertmichaelj** [comment]
@Jeffwan has this been released in Spark 2.4 yet? I've seen the issue [here](https://issues.apache.org/jira/browse/SPARK-28921) for this fix in 2.4.5, but 2.4.5 has not been released yet. Is there a way to get the submitting of spark jobs working on 2.4.4?

Sorry for necro-ing this, but I really need to figure out a way (using release software) to be able to submit spark jobs on an AWS EKS cluster.

**Comment by Jeffwan** [comment]
@albertmichaelj Hey, it's not released yet. What you can do is you can download Spark source code and build a v2.4.5-SNAPSHOT version with the fix. 

Spark release cycle is different, it normally takes > 3 months.

**Comment by jamesthegiantpeach** [comment]
Getting this error on k8s v1.15.6

**Comment by pisymbol** [comment]
No 4.6.4 works. Make sure you delete the old ones. I do something like this:

```
FROM spark-py:v2.4.4

COPY *.jar /opt/spark/jars/
RUN rm /opt/spark/jars/kubernetes-client-4.1.2.jar /opt/spark/jars/kubernetes-model-4.1.2.jar /opt/spark/jars/kubernetes-model-common-4.1.2.jar
```

**Comment by jamesthegiantpeach** [comment]
I made sure that the jars were deleted, but not having this issue anymore after changing k8s version to 1.15.0.

**Comment by Jeffwan** [comment]
2.4.5 RC2 approved and you won't see this problem again in 2.4.5
