### ISSUE TITLE
docker-credential-desktop doesn't pad the auth field

### ISSUE THREAD

**Issue by bbourbie** [kubernetes/kubernetes#82147]
**What happened**:

docker now provides a new favorite way to store the credentials with the variable credsStore in the file ~/.docker/config 

it it is set to desktop, which will be using the executable docker-credential-desktop whose source code is https://github.com/docker/docker-credential-helpers

docker-credential-desktop doesn't pad the auth field. 

So, if we use the command 

```
kubectl create secret generic regcred  --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=~/.docker/config.json
```
k8s credential provider won't be able to decode the field because of the error

Failed to pull image "myrepo/myimage:tag": illegal base64 data at input byte

**What you expected to happen**:

Image pulled normally

**How to reproduce it (as minimally and precisely as possible)**:

open docker config file, and have credsStore set to desktop. 
Run docker login and then use the ~/.docker/plaintext-passwords.json to create a k8s dockerconfigjson secret, the error will directly show

**Anything else we need to know?**:
I wrote a patch that I will submit

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:38:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"
- Cloud provider or hardware configuration:
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
- OS (e.g: `cat /etc/os-release`):
Mac
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bbourbie** [comment]
This belongs to /sig Apps I think

**Comment by BenTheElder** [comment]
/remove-sig apps
/sig auth
/sig node
cc @liggitt to triage
