### ISSUE TITLE
Hard coded endpoints in examples/glusterfs/endpoints/glusterfs-endpoints.json

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#8214]
Hi @rootfs, I'm trying to repeat the glusterfs example. Could you elaborate on where are those hard coded IP addresses come from? Thanks.

```
    "Endpoints": [
        "10.16.154.81:0",
        "10.16.154.82:0",
        "10.16.154.83:0"
    ]
```

**Comment by rootfs** [comment]
these are gluster hosts' IP addresses. When you set up a gluster hosts, you have a collection of participating hosts. Get the IPs of these hosts and put them in the endpoints. The port is not really used.

**Comment by caesarxuchao** [comment]
Thank you @rootfs, I can repeat the example now : ) I have sent #8266 to add some explanation of the endpoints in the README.
