### ISSUE TITLE
delegated authn does not automatically reload when ca bundles change

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#82141]
The delegated authn in the generic apiserver doesn't automatically reload when the default ca bundle changes.  We should update to make this happen transparently.  There is a prototype of how to do this in openshift that we can upstream.

@kubernetes/sig-api-machinery-bugs 
@kubernetes/sig-auth-bugs 
/priority important-soon
/assign

For aggregated apiservers, we created delegated authentication options.  These pull from `kubectl get -n kube-system configmap/extension-apiserver-authentication`.  ConfigMaps are logically dynamic, but the delegated authentication doesn't automatically pick up the changes. This causes drift between intent and reality.

- [x] part 1 - update the core authenticators to allow dynamic changes to x509 verification options
- [x] part 2 - update options to plumb the basic verification functions through
- [x] part 3 - update the apiserver to allow dynamic updates to the tls connection options
- [ ] part 4 - wire up a simple controller to back the dynamic verification functions by an efficient and thread-safe informer/lister

**Comment by enj** [comment]
#79083
#79285

@jackkleeman

**Comment by jackkleeman** [comment]
I suspect part 3 will be a lot easier once #79285 or similar is merged. I would be interested in picking this up

**Comment by deads2k** [comment]
> I suspect part 3 will be a lot easier once #79285 or similar is merged. I would be interested in picking this up

I agree.  I'm moving through a similar arc, but for CA bundles only.  I think the approaches are compatible and complementary.

**Comment by jackkleeman** [comment]
I've tried to bring part 3 into my PR #79285, using a filewatch on a list of CA bundle files

**Comment by jackkleeman** [comment]
My open PRs on this:
#83580
#83627
