### ISSUE TITLE
VisitContainers called from *InUse methods is not safe

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#82158]
**What happened**:

In 1.16, #59416 modified the `VisitContainers()` helper method to conditionally iterate over the EphemeralContainers field, based on whether the EphemeralContainers feature gate was enabled.

This method is called in pkg/api/pod/util.go to:
1. determine if any containers are using a particular alpha field
2. clear a particular alpha field in all containers

On update, if the existing pod has ephemeral containers, the new pod is permitted to specify those ephemeral containers as well, even if the feature is currently disabled (this avoids data loss on API object update).

That means that when the ephemeral feature is not enabled:
1. an existing pod that is using a particular feature in an ephemeral container may not be detected correctly
2. alpha fields might not be cleared correctly in the ephemeral containers in the pod
3. node authorizer will not recognize secrets/configmaps in envFrom in ephemeral containers in existing pods, so kubelets will not be authorized to fetch those secrets/configmaps

The caller needs to indicate whether they want to iterate over all containers or just ones that are feature-enabled

/cc @verb

**Comment by verb** [comment]
Glancing through the fields dropped in pod/util.go I'd say about half of them are eligible for use in ephemeral containers.

It should be a pretty easy fix. We should introduce the mask [described here](https://github.com/kubernetes/kubernetes/pull/79176#issuecomment-523848648). @tedyu already has opened #81941 for that, which could be easily adapted.

@liggitt Do you want to try to get this fix into the initial 1.16 release or would it be reasonable to address it in a point release?

**Comment by verb** [comment]
Thinking about it some more, it's better that we not block on #81941. I'm going to prepare a PR with a `VisitContainersUnconditional`. We can remove it later if necessary, and it'll be a self-contained bug fix that's not blocked on another conversation.

**Comment by tedyu** [comment]
minor correction: please use #82192 for future discussion on the mask API.

**Comment by verb** [comment]
Although it's incorrect behavior, I don't think this is a bug in practice. The goal is to drop alpha fields from EphemeralContainers in 2 cases: create & update.

This isn't an issue for create, because all of the ephemeral containers will be dropped if `features.EphemeralContainers` is disabled (and ephemeral containers aren't allowed on create, anyway).

For pod updates, we want to drop updates to alpha fields that were not set in the old object, but we don't allow updates to existing EphemeralContainers *at all*, so the update would fail validation for a different reason.

I'm still sending a PR to fix this, I just want to make sure I didn't miss something. If it's not a problem in practice, then I won't initiate a cherry-pick for 1.16.

**Comment by liggitt** [comment]
I think I agree with that logic

**Comment by smourapina** [comment]
@verb Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 18. Is this issue still intended for 1.17?

**Comment by verb** [comment]
@smourapina Yes, please keep it in 1.17. I will look at it more today.

**Comment by verb** [comment]
I want to use #82192 to resolve this.

/priority important-soon

**Comment by smourapina** [comment]
@verb Friendly reminder that code freeze is rapidly approaching and will take place in November 14th. Is this issue still on track for 1.17? Otherwise we will need to move it to 1.18 milestone.

**Comment by verb** [comment]
@smourapina This is blocked on #82192. This is trivial to fix if #82192 lands, but I think it's a high risk of slipping.

**Comment by josiahbjorgaard** [comment]
/milestione v1.18

(code freeze is near)

**Comment by gianarb** [comment]
Hello @verb !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by verb** [comment]
@gianarb ack, please leave it in 1.18. If there's not movement on the blocking issue soon I'll reopen the PR that fixes it without the blocker.

**Comment by gianarb** [comment]
Hello @verb !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by gianarb** [comment]
Hello @verb @liggitt  !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by verb** [comment]
@gianarb This is still intended for 1.18. #87865 resolves this issue and has lgtm.

/cc @tedyu

**Comment by smourapina** [comment]
We are now in code freeze for 1.18, so I am moving this to the next milestone.
/milestone v1.19

**Comment by liggitt** [comment]
this has an active PR in progress in https://github.com/kubernetes/kubernetes/pull/87865

/milestone v1.18

**Comment by gianarb** [comment]
The PR is merged! The issue is still open @liggitt is it right?
Thanks!

**Comment by verb** [comment]
@gianarb #87865 resolved the issue described here. We have a follow-up item, but I've opened issue #88909 for that, so let's leave this in 1.18 as fixed.

/close
