### ISSUE TITLE
Add fscrypt support for emptyDir

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/kubernetes#82159]
**What would you like to be added**:
It would be nice if there was a way to have an ephemeral encrypted volume via emptyDir. It looks like fscrypt is supported in ext4 and a few other file systems and is written in Go.

**Why is this needed**:
I'd like to write sensitive data to a scratch disk and then crypto-shred it as soon as the data processing is complete.

I'd be willing to implement this if someone gives me pointers in writing Kubernetes plugins.

**Comment by rikatz** [comment]
Hi @jeremyje and thanks for raising this.

The code from emptydir is here: https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/emptydir

It supports actually 3 kinds of mounts, described here: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/emptydir/empty_dir.go#L223

Maybe one idea is to create some "new" kind of storage (as tmpfs and hugepages), but with the option to specify the passphrase or read it from a Secret.

The bigger "problem" here in my point of view is that this might require some API change also (unless you use annotations, which I don't know if guys from the ORG will think it's a good idea) and this might require a KEP.

So a KEP is, if this is some kind of bigger feature pack, and you think this might be a nice improvement to Kubernetes you can write a document with this feature to be reviewed. [KEPs - Kubernetes Enhancements Proposals](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage) and maybe write some 

My final thoughts, if you think this is some kind of easy thing, do the PR so at least someone can review to you and point you in the right direction :)

This is no waste of time, as you learn how to develop and surf into Kubernetes code ;)

Almost forgot, you can also write a CSI and point into it: https://kubernetes-csi.github.io/docs/

**Comment by jeremyje** [comment]
I was thinking that the key itself is ephemeral so that it's autogenerated on the fly without configuration. If the PVC is lost (host crash) the data associated with it is lost. I wanted it to be zero config other than give me encryption.

Would it be better to offer an encryptedEmptyDir plugin that does this instead? That way it doesn't have to be a part of Kubernetes itself. Is that possible?

**Comment by rikatz** [comment]
> Would it be better to offer an encryptedEmptyDir plugin that does this instead? That way it doesn't have to be a part of Kubernetes itself. Is that possible?

Yes it is :) You can create your very own CSI (Container Storage Interface) and use it. It works the same way as CNI, CRI and so on. Kubernetes calls your "external" program to create, attach, detach and remove the volume when needed (instead of having this internally in the code)

Take a look into CSI documentation here: https://kubernetes-csi.github.io/docs/ it should be helpful. There are some examples as well on how to build and use your own CSI.

**Comment by schlichtanders** [comment]
@jeremyje have you been successful in creating an encryptedEmptyDir csi driver? 

I am also looking for an easy way to encrypt the standard ephemeral volume but couldn't find anything.

**Comment by jeremyje** [comment]
I'm looking into this. It may take some time though
