### ISSUE TITLE
Problem configure External CA mode in Kubernetes Cluster on premise 

### ISSUE THREAD

**Issue by WeAreHadock** [kubernetes/kubernetes#82178]
Hi everyone,

We have install cluster Kubernetes 1.14.

We want to certify the api server access with an external ca authorities.
We use ExternalCA mode but have problem during the kubeadm init.

In the externalCA mode, we have only the ca.crt and not the ca.key.
In this mode, we have to provide all the certificate : apiserver and  apiserver-kubelet-client crt and key.

We also have to provide all the kubeconfig file but we dont know how to generate it : the certificate-authority-data correspond to the ca.crt | decode64 but we dont know how to genereate the user credentials.

When we lauch kubeadm init, we have a timeout with problem with kubelet.

Are anyone here who have already use External CA mode and use only the ca.crt to iniate a kubernetes cluster ??

**Comment by neolit123** [comment]
> In the externalCA mode, we have only the ca.crt and not the ca.key.
In this mode, we have to provide all the certificate : apiserver and apiserver-kubelet-client crt and key.

hi, if you feed a custom ca.crt before `kubeadm init`, kubeadm should be able to generate everything else for you.

> We also have to provide all the kubeconfig file but we dont know how to generate it : the certificate-authority-data correspond to the ca.crt | decode64 but we dont know how to genereate the user credentials.

i don't think you have to (as per my message above).
but if you wish to generate a kubeconfig for a new user you can have a look at `kubeadm alpha kubeconfig user`.

**Comment by neolit123** [comment]
also don't forget to call `kubeadm reset` before adding the `ca.crt` and `kubeadm init`.

**Comment by WeAreHadock** [comment]
Hi,

We reset kubeadm withou any errors.
We put the external ca.crt in default directory (/etc/kubernetes/ssl) and tried `kubeadm init` but we have to provide `--config` parameters (to set images repos, ...) and we have the following error :

`invalid or incomplete external CA: failure loading certificate for API server: failed to load certificate: couldn't load the certificate file /etc/kubernetes/ssl/apiserver.crt: open /etc/kubernetes/ssl/apiserver.crt: no such file or directory`

Note:  the ssl directory is empty (except our ca.crt) due to `kubeadm reset`

Thanks for you help

**Comment by neolit123** [comment]
> We put the external ca.crt in default directory (/etc/kubernetes/ssl)

please try the default path, it should be /etc/kubernetes/pki.
which means you need to not set `certificatesDir: "/etc/kubernetes/ssl"` in the ClusterConfiguration.

**Comment by WeAreHadock** [comment]
Hi,
/etc/kubernetes/pki is a symbolic link to /etc/kubernetes/ssl. 

In adition, when we have a look on doc : 
(https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#external-ca-mode)

> It is also possible to provide just the ca.crt file and not the ca.key file (this is only available for the root CA file, not other cert pairs). If all other certificates and kubeconfig files are in place, kubeadm recognizes this condition and activates the “External CA” mode.

We understand that we have to provide all other certificates and kubeconfig files, so kubeadm init can't generate files in external CA mode, isn't it ?

**Comment by neolit123** [comment]
> /etc/kubernetes/pki is a symbolic link to /etc/kubernetes/ssl.

please try without a symbolic link to check if this is a bug.

> We understand that we have to provide all other certificates and kubeconfig files, so kubeadm init can't generate files in external CA mode, isn't it ?

that part of the doc is out of date.

to explain again how i got it working:
- call kubeadm reset
- i placed `ca.crt` in `/etc/kubernetes/pki`
- call kubeadm init

**Comment by WeAreHadock** [comment]
It's still not working we have the same error ...

- We call kubeadm init
- We place the ca.crt in /etc/kubernetes/pki and empty the folder ssl
- We call kubeadm init -v=9 --config kubeadm-config.yaml ( with certificatesDir: /etc/kubernetes/pki in the kubeadm-config.yaml
We have the same error : I0903 13:46:07.556130   14254 initconfiguration.go:186] loading configuration from "kubeadm-config.yaml"
I0903 13:46:07.566314   14254 feature_gate.go:226] feature gates: &{map[]}
invalid or incomplete external CA: failure loading certificate for API server: failed to load certificate: couldn't load the cepiserver.crt: no such file or directory


Nb : We also try to use kubeadm init ( without the kubeadm-config.yaml in parameter and have the same error.

Any ideas ?

**Comment by neolit123** [comment]
> We place the ca.crt in /etc/kubernetes/pki and empty the folder ssl

try removing the ssl folder / symbolic link completely.
just use the /etc/kubernetes/pki folder.

> We call kubeadm init

did you mean "reset" on the first line?

**Comment by WeAreHadock** [comment]
Yes the first command is kubeadm reset

I delete the ssl folder and replace the pki which was a link to ssl folder in a folder pki and place the ca.crt.

Still the same error ...

**Comment by neolit123** [comment]
looking at your log `cepiserver.crt` is not a file managed by kubeadm, where does it come from?

**Comment by neolit123** [comment]
i was able to reproduce the problem on 1.14. do you have the option to move to 1.15, where my above steps should just work?

**Comment by neolit123** [comment]
actually never mind, looks like i made a misted when i tested this.

the logic for external CA even in 1.16 is the following:
- the user provides a `ca.crt`
- they also provides a `apiserver.crt/key` that is the api-server serving certificate signed by the external CA.
- same for `apiserver-kubelet-client.crt/key` which is the kubelet client certificate for the api server

we probably need to add some notes about "external CA" in this document:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#renew-certificates-with-external-ca

**Comment by neolit123** [comment]
@WeAreHadock 
i will close this ticket and create a new one in the kubeadm repository.
will ping you on that.

/close

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubeadm/issues/1770

**Comment by cloudcafetech** [comment]
@neolit123 
Using 1.20 kubeadm, I followed as per your instruction ```kubeadm reset``` then adding the ca.crt in /etc/kubernetes/pki folder then run ```kubeadm init``` but got following error .... (Seems its looking ```ca.key``` file)

```
I0910 04:43:12.115739 2101926 checks.go:839] image exists: k8s.gcr.io/etcd:3.4.13-0
I0910 04:43:12.140561 2101926 checks.go:839] image exists: k8s.gcr.io/coredns:1.7.0
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0910 04:43:12.140753 2101926 certs.go:474] validating certificate period for ca certificate
[certs] Using existing ca keyless certificate authority
open /etc/kubernetes/pki/ca.key: no such file or directory
couldn't load the private key file /etc/kubernetes/pki/ca.key
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadKeyFromDisk
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:266
```

**Comment by neolit123** [comment]
we have our external CA mode e2e test green, so you must be doing something wrong:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-ca-1-20

probably not providing all the required certificates if ca.key is missing.
https://kubernetes.io/docs/setup/best-practices/certificates/

here is how the e2e test works. you can use `kubeadm init phase ...` to generate the missing certs too.
https://github.com/kubernetes/kubeadm/blob/ebd1ae0b04a22e94bc73d07f10a5c2416ac7afe0/kinder/pkg/cluster/manager/actions/setup-external-ca.go#L28

**Comment by cloudcafetech** [comment]
@neolit123 

Thanks for reply ...

In this comments (https://github.com/kubernetes/kubernetes/issues/82178#issuecomment-527230686) you mentioned 
> hi, if you feed a custom ca.crt in /etc/kuberentes/pki before kubeadm init, kubeadm should be able to generate everything else for you.

And that I did.

Then Why?
>probably not providing all the required certificates if ca.key is missing.

I am using below init command

```kubeadm init --control-plane-endpoint drk8s.example.com:6443 --pod-network-cidr=10.244.0.0/16 --upload-certs --v=9 | tee kubeadm-output.txt```

**Comment by cloudcafetech** [comment]
>probably not providing all the required certificates if ca.key is missing.

I did generating all certs using below command ... but same error (Seems its looking ca.key file)

```kubeadm init phase certs all --control-plane-endpoint=drk8s.example.com:6443 --apiserver-cert-extra-sans=localhost --v=9```

- Error

```
I0911 19:58:52.928595  973257 initconfiguration.go:104] detected and using CRI socket: /var/run/dockershim.sock
I0911 19:58:52.928858  973257 interface.go:400] Looking for default routes with IPv4 addresses
I0911 19:58:52.928866  973257 interface.go:405] Default route transits interface "eth0"
I0911 19:58:52.929615  973257 interface.go:208] Interface eth0 is up
I0911 19:58:52.929666  973257 interface.go:256] Interface "eth0" has 2 addresses :[172.25.32.171/22 fe80::250:56ff:feaa:b59a/64].
I0911 19:58:52.929684  973257 interface.go:223] Checking addr  172.25.32.171/22.
I0911 19:58:52.929690  973257 interface.go:230] IP found 172.25.32.171
I0911 19:58:52.929695  973257 interface.go:262] Found valid IPv4 address 172.25.32.171 for interface "eth0".
I0911 19:58:52.929701  973257 interface.go:411] Found active IP 172.25.32.171
I0911 19:58:53.117572  973257 version.go:182] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I0911 19:58:53.241785  973257 version.go:251] remote version is much newer: v1.22.1; falling back to: stable-1.20
I0911 19:58:53.241818  973257 version.go:182] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.20.txt
I0911 19:58:53.322689  973257 certs.go:474] validating certificate period for CA certificate
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0911 19:58:53.322904  973257 certs.go:474] validating certificate period for ca certificate
[certs] Using existing ca keyless certificate authority
open /etc/kubernetes/pki/ca.key: no such file or directory
couldn't load the private key file /etc/kubernetes/pki/ca.key
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadKeyFromDisk
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:266
k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.TryLoadCertAndKeyFromDisk
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil/pki_helpers.go:235
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.LoadCertificateAuthority
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:172
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.CreateCertAndKeyFilesWithCA
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:156
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runCertPhase.func1
```

**Comment by neolit123** [comment]
i will give it a try with 1.20 and report back.

**Comment by neolit123** [comment]
i cannot reproduce the problem with the latest 1.20.x:

```
$ sudo kubeadm reset -f
$ sudo kubeadm init phase certs all
$ sudo kubeadm iinit phase kubeconfig all
$ sudo rm /etc/kubernetes/pki/ca.key

$ kubeadm init ....

# output looks fine and kubeadm creates the node

[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca keyless certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using existing sa keys

...
```


maybe you are missing the kubeconfig part?

also move to 1.21 or .22 because 1.20 will be going out of support later this year.

**Comment by cloudcafetech** [comment]
Thanks.

Will update you shortly.

**Comment by cloudcafetech** [comment]
@neolit123 

I am doing as follows just adding --control-plane-endpoint=drk8s.example.com:6443 along with your set of commands

```
kubeadm reset -f
kubeadm init phase certs all --control-plane-endpoint=drk8s.example.com:6443 --apiserver-cert-extra-sans=localhost --v=9
kubeadm init phase kubeconfig all --control-plane-endpoint=drk8s.example.com:6443
```

Till now its OK, generating cerificate & kubeconfig.

But when run below command

```kubeadm init --control-plane-endpoint drk8s.example.com:6443 --pod-network-cidr=10.244.0.0/16 --upload-certs --v=9 | tee kubeadm-output.txt```

- Getting below error 

```
I0914 21:36:31.948118 2555012 round_trippers.go:451] Response Headers:
I0914 21:36:31.948170 2555012 round_trippers.go:425] curl -k -v -XGET  -H "User-Agent: kubeadm/v1.20.0 (linux/amd64) kubernetes/af46c47" -H "Accept: application/json, */*" 'https://drk8s.example.com:6443/healthz?timeout=10s'
I0914 21:36:31.951052 2555012 round_trippers.go:445] GET https://drk8s.example.com:6443/healthz?timeout=10s  in 2 milliseconds
I0914 21:36:31.951062 2555012 round_trippers.go:451] Response Headers:

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in docker:
                - 'docker ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'docker logs CONTAINERID'

couldn't initialize a Kubernetes cluster
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:114
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:151
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
error execution phase wait-control-plane
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:151
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
``` 

- LB response also OK

```
nc -v -w 2 drk8s.example.com 6443
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 172.25.32.80:6443.
```

**Comment by neolit123** [comment]
You need to figure out why the api server is not starting or responding on
healthz.

**Comment by cloudcafetech** [comment]
@neolit123 

Not able to :(

If I use l 3rd command ```kubeadm init phase kubeconfig all``` without LB (drk8s.example.com) then there was no issue, API server coming up with local end point.

```
kubeadm reset -f
kubeadm init phase certs all --control-plane-endpoint=drk8s.example.com:6443 --apiserver-cert-extra-sans=localhost --v=9
**kubeadm init phase kubeconfig all**
kubeadm init --control-plane-endpoint drk8s.example.com:6443 --pod-network-cidr=10.244.0.0/16 --upload-certs --v=9 | tee kubeadm-output.txt
```

But if I use ... then error coming ...

```
kubeadm reset -f
kubeadm init phase certs all --control-plane-endpoint=drk8s.example.com:6443 --apiserver-cert-extra-sans=localhost --v=9
kubeadm init phase kubeconfig all --control-plane-endpoint=drk8s.example.com:644
kubeadm init --control-plane-endpoint drk8s.example.com:6443 --pod-network-cidr=10.244.0.0/16 --upload-certs --v=9 | tee kubeadm-output.txt
```
