### ISSUE TITLE
nodeSelector: when will it be deprecated?

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kubernetes#82184]
Current documentation about nodeSelector states the following:
nodeSelector continues to work as usual (e.g. in 1.15), but will eventually be deprecated, as node affinity can express everything that nodeSelector can express.

Do you know when nodeSelector will be deprecated?

**Comment by stevebail** [comment]
@kubernetes/sig-scheduling
/sig scheduling

**Comment by ahg-g** [comment]
We will add this as one of the work items sig scheduling will be working on in 1.17 (no completely deprecate in 1.17, but start the conversation, KEP and sync with sig arch)

**Comment by ahg-g** [comment]
nodeSelector can't be deprecated because it is a GA feature, see: https://github.com/kubernetes/kubernetes/issues/82331
