### ISSUE TITLE
Deprecate alwaysCheckAllPredicates configuration parameter in the scheduler

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#82180]
**What would you like to be added**:
Deprecate [alwaysCheckAllPredicates](https://github.com/kubernetes/kubernetes/blob/03097277a456cfe4fc87188961f091870e1f67e4/pkg/scheduler/api/types.go#L68)

**Why is this needed**:
Now that we are transitioning to the scheduling framework, predicates will be converted into filter plugins. By design, we stop evaluating the rest of filter plugins on a node once a plugin rejects the node. During the transition phase (where some predicates are converted to filter and some are not), the semantics of this configuration parameter can't be supported, and so it is better to remove this parameter.

/sig scheduling

**Comment by draveness** [comment]
/assign

According to the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/), we need 12 months to deprecate the parameter.

**Comment by Adirio** [comment]
Will this be deprecated for 1.16? Not being able to do so will inevitably delay the transition to the scheduling framework to 1.19, wouldn't it?

**Comment by draveness** [comment]
We need more discussion on how to deprecate it and may start in 1.17

Regards,
Draven

**Comment by Adirio** [comment]
The implications of that are delaying transforming predicates into Filter
plugins until 1.19, or modifying `framework.RunFilterPlugin` to handle this
configuration parameter.

The signature could be changed to `RunFilterPlugins(pc *PluginContext, pod
*v1.Pod, nodeName string, allwaysCheckAllPredicates bool) []*Status`

**Comment by ahg-g** [comment]
> /assign
> 
> According to the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/), we need 12 months to deprecate the parameter.

This is not a user-facing feature, it is an admin facing one, so I think the following applies: "GA: 6 months or 1 release (whichever is longer)"

As to how this is going to be deprecated, I think it depends on what impact does setting this value to true have (i.e., why would anyone change the default value). This flag does not change how the system behaves from the user's perspective, it controls an optimization (the optimization being existing on the first failed predicate). 

We discussed this during the sig meeting, it seems that the historical reason for adding this flag was to provide a way to disable the change in case that optimization caused problems. While it is not ideal, I think we will be fine if we do not support this flag in RunFilterPlugins.

**Comment by ahg-g** [comment]
@Huang-Wei @bsalamat do we have examples from the past on deprecating parameters from the scheduler's Policy? I asked a question on the #wg-component-standard slack channel to understand which rule applies to this case.

**Comment by wgliang** [comment]
_the semantics of this configuration parameter can't be supported, and so it is better to remove this parameter._

I agree with that deprecate it. And I originally wanted to set it as the default behavior(FYI:#56926). But this does not seem to be the real reason. More precisely, it seems that the user does not have the will to update `alwaysCheckAllPredicates`.

**Comment by Adirio** [comment]
If this falls into the 6 months or 1 version category and it gets deprecated for 1.16, it can be removed for 1.17 that is when the framework will enter the beta stage.

**Comment by Huang-Wei** [comment]
@ahg-g I'm not aware of any previous example which can be referenced here.

Given that **(1)** the scheduler component config is in version v1alpha1 (under the hood we care about the policyConfig), and **(2)** removing this doesn't impact end-users - it only brings in _indifferent_ debugging inconveniences.

Is it OK to mark it as a Deprecated flag for now (in 1.17)? Or you want to totally remove it from policyConifg?

**Comment by ahg-g** [comment]
> @ahg-g I'm not aware of any previous example which can be referenced here.
> 
> Given that **(1)** the scheduler component config is in version v1alpha1 (under the hood we care about the policyConfig), 

Is it considered v1alpha1 though? it is under pkg/scheduler/api/v1, that is why is confusing me.

> and **(2)** removing this doesn't impact end-users - it only brings in _indifferent_ debugging inconveniences.
> 
It *could* impact preemption performance: if we run through all predicates, there is a higher chance of finding an unresolvable filtering decision. But I don't expect that to be a reason why someone would flip this flag.


> Is it OK to mark it as a Deprecated flag for now (in 1.17)? Or you want to totally remove it from policyConifg?

As a first step, we will be fine with just deprecating it, the part that I am confused about is whether or not the Policy struct is v1 or v1alpha1 (i.e., part of component config)

**Comment by ahg-g** [comment]
I suggest we take a semi-conservative approach here: mark it as deprecated and keep supporting it for a year for predicates only. It has no user facing impact other than a log message, which is not really part of the API's definition I presume.

**Comment by k82cn** [comment]
>  mark it as deprecated and keep supporting it for a year for predicates only

+1, it's better to follow deprecated process to do that :)

> It has no user facing impact other than a log message, which is not really part of the API's definition I presume.

I'm not sure whether it's the case in k8s, but there are some cases in other product that the customized features dependent on log message, e.g. monitoring.  


> As a first step, we will be fine with just deprecating it, the part that I am confused about is whether or not the Policy struct is v1 or v1alpha1 (i.e., part of component config)

`Policy` by scheduler is `v1`, and `ComponentConfig` is `v1alpha1`. Two different features, so different version; although they try to resolve the same problem. Regarding `v1.Policy`, should we deprecate it and move to `ComponentConfig`?

/cc @luxas

**Comment by ahg-g** [comment]
> 
> > As a first step, we will be fine with just deprecating it, the part that I am confused about is whether or not the Policy struct is v1 or v1alpha1 (i.e., part of component config)
> 
> `Policy` by scheduler is `v1`, and `ComponentConfig` is `v1alpha1`. Two different features, so different version; although they try to resolve the same problem. Regarding `v1.Policy`, should we deprecate it and move to `ComponentConfig`?
> 

I think we should move everything currently under api/ to apis/, the part that is related to configuring the scheduler (e.g., Policy) should move under apis/config (i.e., component config), the other parts that we expose for extenders should move to apis/extenders for example, and each should have its own versions. kubelet does this: https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/apis

**Comment by ahg-g** [comment]
I asked on k8s-code-organization: https://kubernetes.slack.com/archives/CHGFYJVAN/p1567697828012800

The summary is this: we can restructure the code without a KEP (will allow us to remote scheduler/api), but we will have to register Policy under both ```apiVersion: kubescheduler.config.k8s.io/v1``` and ```apiVersion: v1```.

**Comment by Huang-Wei** [comment]
That "dual-registration" sounds new and fun. I'd like to volunteer to own the "API cleanup" item in 1.17 including:

- this item
- dual-register policy to `apiVersion: kubescheduler.config.k8s.io/v1` and `apiVersion: v1` for backwards compatibility
- code refactoring

**Comment by draveness** [comment]
/unassign
/assign @Huang-Wei 

Since @Huang-Wei is working on the API version change.

**Comment by ahg-g** [comment]
This will be deprecated as part of deprecating v1.Policy
