### ISSUE TITLE
Improve handling of nodestage/nodepublish in kubelet

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#82190]
Currently we appear to have a bug in how kubelet processes nodestage/nodepublish for CSI.

1. Kubelet receives pod A with volume A and before mounting/staging the volume it adds the volume to ASOW (but volume is not globally mounted yet)
2. Kubelet tries NodeStage.. nodestage fails with timeout error and naturally kubelet retries it
3. user deletes the pod from the node and that causes pod+volume to be removed from DSOW.
4. CSI driver finally finishes mounting/staging but kubelet does not know it.
5. Kubelet removes the volume from ASOW:

```
				if rc.controllerAttachDetachEnabled || !attachedVolume.PluginIsAttachable {
					rc.actualStateOfWorld.MarkVolumeAsDetached(attachedVolume.VolumeName, attachedVolume.NodeName)
					klog.Infof(attachedVolume.GenerateMsgDetailed("Volume detached", fmt.Sprintf("DevicePath %q", attachedVolume.DevicePath)))
```

6. But kubelet never unmounts or unstages the volume, because volume was never globally mounted.

**Comment by gnufied** [comment]
/sig storage
@kubernetes/sig-storage-bugs 

/assign

**Comment by humblec** [comment]
@gnufied thanks for filing this, yeah this is an important issue which has to be fixed in priority  due to the fact that, in some scenarios this can cause the volume to staged on more than one node at same time even if it is `RWO` and thus cause the FS data corruption or integrity issues.

**Comment by gnufied** [comment]
Another related problem is - for raw block devices because `SetUpDevice` does both NodeStage and NodePublish and lets say if `NodeStage` succeeded but `NodePublish` failed - we never record successful `NodeStage` in the code because `MarkDeviceAsMounted` and `MarkVolumeAsMounted` is called one after the other and this creates problems when trying to recover from error.

**Comment by gnufied** [comment]
For now I am tracking issue with raw block devices as a separate item - https://github.com/kubernetes/kubernetes/issues/82340

**Comment by gnufied** [comment]
I am using this as a top-level issue to track some of the remaining issues and hence keeping this open for now.

/remove-lifecycle stale

**Comment by joshimoo** [comment]
@gnufied I am the fixes have been merged already, but are there issues left in this regard, since it was closed by stale bot?
