### ISSUE TITLE
CRI pod CPU metrics incorrect for pods with 20+ CPUs

### ISSUE THREAD

**Issue by vllry** [kubernetes/kubernetes#82195]
**What happened**:
CRI CPU metrics are incorrect when using a large number of cores, due to a `uint64` overflow.

**What you expected to happen**:
CPU metrics should be correct for arbitrarily high numbers of cores.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a pod with 20 CPU units allocated, and fetch the CRI metrics. The metrics will be incorrect.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.4
- CRI: CRI-O

cc @paulnivin
cc @ashleykasim
/sig node
/sig scalability

**Comment by xiaoanyunfei** [comment]
`CRI CPU metrics are incorrect when using a large number of cores, due to a uint64 overflow.`
How did you get the cri cpu metrics?

**Comment by paulnivin** [comment]
> How did you get the cri cpu metrics?

kubelet /stats/summary API. For "large" pods, we confirmed that cri-o/cgroupfs calculations were being generated correctly and CPU data overflows at the kubelet CRI stats provider layer. Overflows of CPU data in /stats/summary results in metrics-server having bad data which further propagates to the HPA scaling Pods incorrectly.
