### ISSUE TITLE
namespace conditions are not consistently set during termination

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#82194]
In https://github.com/kubernetes/kubernetes/pull/73405, terminating namespaces got new conditions, but they are not cleared on fully successful runs and when they are `False` (the good state), they are not written if they aren't present.

I think it's ok that these are not present when namespaces active (not in terminating), but once we observe terminating namespaces, the conditions need to be consistently present and correct.

/assign
@kubernetes/sig-api-machinery-bugs 
/priority important-soon

**Comment by lavalamp** [comment]
I was OK-ish with them remaining absent as long as there's no problems, but if there is a problem and it is fixed, they need to get the False state.
