### ISSUE TITLE
Flex volume: inconsistency between directory name and plugin name cause orphaned pod to fail to clean up

### ISSUE THREAD

**Issue by zhan849** [kubernetes/kubernetes#82215]
**What happened**:
Volume manager reconciler is getting volume / directory information from pod volume path, where volume plugin name is retrieved directly from volume directory name: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L684

```bash
# ls -als /mnt/kubelet/pods/3bca6595-cb6a-11e9-8e7d-0ec87644dab8/volumes/
total 0
0 drwxr-x--- 5 root root 92 Aug 30 21:07 .
0 drwxr-x--- 5 root root 71 Aug 30 21:07 ..
0 drwxr-xr-x 2 root root  6 Aug 30 21:08 kubernetes.io~empty-dir
0 drwxr-xr-x 2 root root  6 Aug 30 21:08 kubernetes.io~secret
0 drwxr-x--- 4 root root 56 Aug 30 21:07 pinterest~podvolume # our flex volume driver
```

However, when flex volume driver returns it's driver name, it adds a prefix:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/plugin.go#L116

But when flex volume constructs it's device path, it does not add this prefix:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/volume.go#L54

Which caused these directories failed to get cleaned up during volume manager reconciliation:
```bash
# below is our customized debug log, does not appear in upstream
Sep  1 06:18:02 node-0a037cef kubelet[72549]: I0901 06:18:02.256252   72549 plugins.go:732] plugin name: "pinterest/podvolume"; probed: [flexvolume-pinterest/podvolume]; plugins: [kubernetes.io/gce-pd kubernetes.io/nfs kubernetes.io/azure-file kubernetes.io/scaleio kubernetes.io/storageos kubernetes.io/iscsi kubernetes.io/photon-pd kubernetes.io/host-path kubernetes.io/empty-dir kubernetes.io/glusterfs kubernetes.io/aws-ebs kubernetes.io/rbd kubernetes.io/cinder kubernetes.io/cephfs kubernetes.io/flocker kubernetes.io/local-volume kubernetes.io/secret kubernetes.io/fc kubernetes.io/projected kubernetes.io/portworx-volume kubernetes.io/quobyte kubernetes.io/downward-api kubernetes.io/configmap kubernetes.io/vsphere-volume kubernetes.io/azure-disk kubernetes.io/git-repo kubernetes.io/csi]
```

Which as a result caused orphaned pod cannot be deleted because its directories are not able to get cleaned up:

```
Sep  1 06:18:02 node-0a037cef kubelet[72549]: W0901 06:18:02.256331   72549 reconciler.go:394] Could not construct volume information, cleanup the mounts. (pod.UID 3bca6595-cb6a-11e9-8e7d-0ec87644dab8, volume.SpecName system-thrift-logger): no volume plugin matched
Sep  1 06:18:02 node-0a037cef kubelet[72549]: I0901 06:18:02.256338   72549 reconciler.go:429] Reconciler sync states: could not find information (PID: 3bca6595-cb6a-11e9-8e7d-0ec87644dab8) (Volume SpecName: system-thrift-logger) in desired state, clean up the mount points
```

```
176440:Sep  1 07:08:30 node-0a037cef kubelet[111622]: I0901 07:08:30.345310  111622 kubelet_volumes.go:69] pod "3bca6595-cb6a-11e9-8e7d-0ec87644dab8" found, but volumes are still mounted on disk [/mnt/kubelet/pods/3bca6595-cb6a-11e9-8e7d-0ec87644dab8/volumes/pinterest~podvolume/system-thrift-logger /mnt/kubelet/pods/3bca6595-cb6a-11e9-8e7d-0ec87644dab8/volumes/pinterest~podvolume/system-pod-log]
176441:Sep  1 07:08:30 node-0a037cef kubelet[111622]: I0901 07:08:30.345335  111622 kubelet_pods.go:1732] Orphaned pod "3bca6595-cb6a-11e9-8e7d-0ec87644dab8" found, but volumes not yet removed.  Reducing cpu to minimum
```

**What you expected to happen**:
volume reconciliation should clean up directories for orphaned pod

**How to reproduce it (as minimally and precisely as possible)**:
very hard to reproduce but we only see it for orphaned pods. however this happens in production intermittently, and given the scale we have, that's a fairly frequent and would need to get things cleaned up manually 

/kind bug
/sig node
/sig storage

/cc @gnufied @msau42 @jsafrane

**Comment by zhan849** [comment]
I think the root cause is that flex volume does not honor the assumption that 1 level below kubelet's volume dir is the plugin name: it is not consistent when constructing its volume path and constructing it's plugin name.

Though fixing the volume path name is likely to be a must have, but it will break existing flex volumes. We need to think about a smooth way to get this inconsistency fixed.

**Comment by xiaoanyunfei** [comment]
The Pr https://github.com/kubernetes/kubernetes/pull/80973 will fix it, but it has been pending for a long time

**Comment by zhan849** [comment]
thanks @xiaoanyunfei for proposing the fix, will continue the discussion in your thread

**Comment by zhan849** [comment]
lets follow discussion in #80972 and #80973

/close
