### ISSUE TITLE
Test cluster must configure test-handler

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#82213]
/sig testing
/sig node

Make runtime handler a variable that gets filled in by the test setup.

This is a follow-up issue  https://github.com/kubernetes/kubernetes/pull/81915#discussion_r319733052

**Comment by RainbowMango** [comment]
Wow...sorry seems I made a mistake.

**Comment by RainbowMango** [comment]
I need more context and description. @draveness Can you help provide more details information?

/help
Add help back, anyone can take this task if you want to take it.
