### ISSUE TITLE
OIDC: Allow any claim from an ID token to be mapped to userinfo extra attributes

### ISSUE THREAD

**Issue by anderseknert** [kubernetes/kubernetes#82236]
**What would you like to be added**:
The ability to provide a list attributes that (if present) should be mapped from the ID token used for authentication into userinfo.extra fields. These attributes could then be used for authorization decisions.

**Why is this needed**:
Current implementation maps group membership only, essentially limiting authorizers following OIDC authentication to RBAC, or variations thereof. While one could of course go for a custom webhook authentication, it seems drastic to throw out the whole OIDC baby with the bathwater just for needing some non-group authentication attributes from the ID token. Concrete example: for certain actions we have a requirement that an admin must have authenticated using at least two factors. This level of assurance (LOA) level is present in the ID tokens `acr` claim, but not available to our custom authorization webhook.

**Comment by enj** [comment]
@anderseknert with #121078 merged, this should be possible now as an alpha feature in v1.29.
