### ISSUE TITLE
resource.Quantity.String() destroys reflect.DeepEqual()

### ISSUE THREAD

**Issue by kdada** [kubernetes/kubernetes#82242]
**What happened**:

```
	q := resource.MustParse("512Mi")
	p1 := &corev1.Pod{
		Spec: corev1.PodSpec{
			Volumes: []corev1.Volume{
				{
					VolumeSource: corev1.VolumeSource{
						EmptyDir: &corev1.EmptyDirVolumeSource{
							SizeLimit: &q,
						},
					},
				},
			},
		},
	}

	p2 := p1.DeepCopy()
	fmt.Println(reflect.DeepEqual(p1, p2))    // ture
	fmt.Print(p1)
	fmt.Println(reflect.DeepEqual(p1, p2))    // false
```

The result is caused by resource.Quantity.String():
```
// String formats the Quantity as a string, caching the result if not calculated.
// String is an expensive operation and caching this result significantly reduces the cost of
// normal parse / marshal operations on Quantity.
func (q *Quantity) String() string {
	if len(q.s) == 0 {
		result := make([]byte, 0, int64QuantityExpectedBytes)
		number, suffix := q.CanonicalizeBytes(result)
		number = append(number, suffix...)
		q.s = string(number)
	}
	return q.s
}
```

**What you expected to happen**:

Quantity should not change in a `Get` method.

I think we could simply remove the field `s`, since It just takes a little overhead.

**Comment by tedyu** [comment]
How about introducing a DeepEqual func to Quantity which ignores the s field ?

**Comment by RainbowMango** [comment]
/assign @kdada 
I see you are trying to fix the issue you reported.

**Comment by kdada** [comment]
@RainbowMango I've filed a PR to fix this issue. #82253. In my PR, I removed the field `s`. 

There is a PR #82246 has a totally different implementation. It fills the field `s` everywhere.

@tedyu Did you test the following case?
```
q := &resource.Quantity{}
q.String()
```

**Comment by tedyu** [comment]
The field s is for speeding up String operation. I don't think it should be removed.

For the test case above, I think it is up to the creator of Quantity to fill the field s - we can provide helper func which creates Quantity and fills the field s.

**Comment by tedyu** [comment]
Another approach is to create a helper func wrapping reflect.DeepEqual where we first call String() on Quantity's involved in the comparison.

**Comment by yue9944882** [comment]
/remove-kind bug

consider use `k8s.io/apimachinery/pkg/api/equality.Semantic#DeepEqual`

**Comment by tedyu** [comment]
```
panic: an unexported field was encountered, nested like this:  [recovered]
	panic: an unexported field was encountered, nested like this: int64 [recovered]
	panic: an unexported field was encountered, nested like this: resource.int64Amount -> int64 [recovered]
	panic: an unexported field was encountered, nested like this: resource.Quantity -> resource.int64Amount -> int64 [recovered]
	panic: an unexported field was encountered, nested like this: resource.Quantity -> resource.int64Amount -> int64
```
Here is test code:
```
	q := MustParse("512Mi")
	q.String()
	q1 := MustParse("512Mi")
	if !apiequality.Semantic.DeepEqual(q, q1) {
		t.Errorf("not equal %v %v", q, q1)
	}
```

**Comment by smarterclayton** [comment]
There are plenty of objects with hidden state in Kube which are not DeepEqual due to side effects.

I don't consider this a bug.

**Comment by tedyu** [comment]
I think we can give the fields which mutate after certain operations known prefix so that a helper can be written to perform DeepEqual immune to side effects.

@smarterclayton 
What do you think ?

**Comment by smarterclayton** [comment]
Why do we need to do that?

**Comment by tedyu** [comment]
The helper would make deep equal check idempotent (reducing surprises as shown in the description).

**Comment by smarterclayton** [comment]
There is no real requirement that deep equal apply in this case.  We have
semantic deep equal to cover these cases when talking about objects in
Kube.  If there's bugs in semantic deep equal, we should fix those.

**Comment by tedyu** [comment]
What do you think of the error shown in https://github.com/kubernetes/kubernetes/issues/82242#issuecomment-527517315 ?

**Comment by kdada** [comment]
@smarterclayton I don't think it's a bug. I consider that it's a convention problem.

`resource.Quantity` changes itself by the `String()` which is a `GET` method. `resource.Quantity.String()` only affects when the receiver is a pointer. That means it may have two behaviors in an object. 

ex. corev1.Pod:
```
type ResourceList map[ResourceName]resource.Quantity

type EmptyDirVolumeSource struct {
	SizeLimit *resource.Quantity
}
``` 

1. Marshaling `corev1.Pod` won't change anything.
2. `fmt.Print()` changes `EmptyDirVolumeSource.SizeLimit` but have no effect to ResourceList.

**Comment by yue9944882** [comment]
> Here is test code:

?

**Comment by caesarxuchao** [comment]
Using the Semantic.DeepEqual is the right solution here. In fact, resource.Quantity is explicitly handled there, see [code](https://github.com/kubernetes/kubernetes/blob/836b901658557ee18936d3690dc9c48fc588eba8/staging/src/k8s.io/apimachinery/pkg/api/equality/semantic.go#L30).

The failure in https://github.com/kubernetes/kubernetes/issues/82242#issuecomment-527517315 was caused by the "staging/src -> vendor" symlink in the k8s repo.

From the root of the k8s/k8s, if I ran the following commands, I can reproduce the error in https://github.com/kubernetes/kubernetes/issues/82242#issuecomment-527517315:
```
cd staging/src/k8s.io/apimachinery/pkg/api/resource/mytest
go test -run <TestName>
```

If instead I `cd` into the vendor folder, the test passed, i.e., 
```
cd vendor/k8s.io/apimachinery/pkg/api/resource/mytest
go test -run <TestName>
```

**Comment by kdada** [comment]
@caesarxuchao  `Semantic.DeepEqual` solves the comparison. What do you think about the Inconsistent behaviors in `ResourceList ` and `EmptyDirVolumeSource . SizeLimit `?

**Comment by caesarxuchao** [comment]
@kdada @tedyu see https://github.com/kubernetes/kubernetes/pull/82452#issuecomment-529690509
