### ISSUE TITLE
When will we upgrade the etcd client to the new Client Balancer

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kubernetes#82251]
**What would you like to be added**:
Since we have already made some upgrade on etcd client with new client balancer
from https://kubernetes.io/blog/2019/08/30/announcing-etcd-3-4/.
**Why is this needed**:
I think k8s needs it because it is more robust and make the etcd traffic more balance.

@jingyih @jpbetz @xiang90

**Comment by jingyih** [comment]
/sig api-machinery

The new client balancer was backported to v3.3.14+. It will be included in 1.16 release.

/cc @gyuho

**Comment by WIZARD-CXY** [comment]
good to know @jingyih thx

**Comment by gyuho** [comment]
https://github.com/kubernetes/kubernetes/pull/81434 is the PR that upgrades etcd client in Kubernetes.

**Comment by yue9944882** [comment]
@adohe
