### ISSUE TITLE
[Scheduler] Golang channels to parallelize Node filtering

### ISSUE THREAD

**Issue by Adirio** [kubernetes/kubernetes#82265]
**What would you like to be added**:
Stop using the generic parallelizer code from `client-go` in the generic scheduler.

**Why is this needed**:
Currently the generic scheduler is using the `client-go` parallelizer:
https://github.com/kubernetes/kubernetes/blob/c7c89f8c6140e0639dc8ba2d8dcdd6fdbd5409ae/pkg/scheduler/core/generic_scheduler.go#L535

This paralelizer is very generic, the function signature is `func(piece int)`. The `piece` parameter is not being used by `checkNode`, and it has to use shared memory with locks to output the list of filtered nodes.

Using a less generic parallelizer with the right signature would allow to benefit from Golang concurrency.

**Proposed solution**:
1. Use a generic parallelizer with a `chan interface{}` as the output channel so that we can output the nodes. The channel could be provided to the parallelizer function in order to set its buffering size. The parallelizer function could return the wait group so that you can wait for a certain number of elements or until all the workers are done.
2. Use an internal parallelizer with a `chan *v1.Node` as the output channel. As this implementation would be less generic, the chan size could signal the workers that all the required Nodes were retreived and all this logic could be implemented inside the parallelizer.

**Comment by draveness** [comment]
I don't think this could improve the performance of the scheduler obviously, but you could send a PR and give the benchmark numbers for the change.

**Comment by Adirio** [comment]
I was not thinking about performance boost, but it looked to me more like C or Python than Golang. Would this change only be useful if it improves the performance?

**Comment by draveness** [comment]
> I was not thinking about performance boost, but it looked to me more like C or Python than Golang. Would this change only be useful if it improves the performance?

I understand golang has a preference on using channel instead of sharing memory when communicating between goroutines, but I don't see the value of doing this without performance improvement.

1. If you pass an unbuffered channel to the parallelizer, there is a chance it could increase the cost of context switching.
2. If you pass a buffered channel to the parallelizer, it could take a lot of memory (O(#nodes)) since in each round of the scheduling, we have to calculate the result for each node.

**Comment by Adirio** [comment]
Locks have also the potential to have a high context switch cost, but I agree unbuffered channels could have that issue.

A buffered channel's memory consumption could be limited to the number of nodes to consider (between 5% and 50% of the total number of nodes with a minimum of 100 nodes). Right now an array of that size is being used, so the only relevant memory increase would be when extracting the values to an array where both the channel and the array would coexist.

In this case, workers that try to write a node into the channel and find it full could discard that node and stop iterating over the rest.
