### ISSUE TITLE
[Failing Test] [sig-network] DNS configMap nameserver [IPv4] 

### ISSUE THREAD

**Issue by soggiest** [kubernetes/kubernetes#82298]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial 

**Which test(s) are failing**:
[sig-network] DNS configMap nameserver [IPv4] Change stubDomain should be able to change stubDomain configuration [Slow][Serial]
[sig-network] DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]
[sig-network] DNS configMap nameserver [IPv4] Forward PTR lookup should forward PTR records lookup to upstream nameserver [Slow][Serial]

**Since when has it been failing**:
8/30/2019

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_configmap.go:507
Sep  3 13:27:20.814: dig result did not match: []string{";; connection timed out; no servers could be reached"} after 2m0s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:104
```

**Anything else we need to know**:
https://github.com/kubernetes/kubernetes/compare/c3463ac4d...e176e4771

/milestone v1.16
/priority critical-urgent
/kind failing-test
/cc @kubernetes/sig-network-test-failures 
/cc @alejandrox1 @jimangel @alenkacz @Verolop

**Comment by rajansandeep** [comment]
/assign
The fix for this has already been merged: https://github.com/kubernetes/kubernetes/pull/82274

**Comment by alejandrox1** [comment]
Thank you @soggiest for creating this one!
We can track the job's health in here https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial while testgrid is being worked on

**Comment by liggitt** [comment]
tests passed in last 6 runs

**Comment by alejandrox1** [comment]
Thank you @rajansandeep for working on this!
/close
