### ISSUE TITLE
Watches each require an etcd connection (leak connections)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8229]
Symptom: After a few hours, kube-apiserver stops responding.

Observations: perf top shows a lot of time spent in __inet_check_established.  Google tells me that is related to large numbers of connections.

And indeed:

```
> netstat -anp
...
tcp        0      0 127.0.0.1:4001          127.0.0.1:43320         ESTABLISHED 6162/etcd
tcp        0      0 127.0.0.1:43099         127.0.0.1:4001          ESTABLISHED 6081/kube-apiserver
tcp        0      0 127.0.0.1:4001          127.0.0.1:35694         ESTABLISHED 6162/etcd
tcp        0      0 127.0.0.1:50859         127.0.0.1:4001          ESTABLISHED 6081/kube-apiserver
tcp        0      0 127.0.0.1:44242         127.0.0.1:4001          ESTABLISHED 6081/kube-apiserver
tcp        0      0 127.0.0.1:4001          127.0.0.1:55018         ESTABLISHED 6162/etcd
...
```

```
> netstat -anp | wc -l
56683
> netstat -anp | grep 127.0.0.1.4001 | wc -l
56467
```

The api server is (more or less constantly) printing errors like this:

```
I0514 01:06:09.977426       6 handlers.go:135] POST /api/v1beta3/namespaces/default/pods: (443.823µs) 403
goroutine 985845 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc27e728720, 0x193)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x193, 0x7f8e083fe8e8, 0xc20806c480, 0x7f8e083feb00, 0xc272d6f000, 0x7f8e08255e50, 0xc27e728720)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:284 +0x232
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7f8e084013b8, 0xc272d6ef80, 0x7f8e083fe8e8, 0xc20806c480, 0x7f8e08255e50, 0xc27e728720, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:291 +0xa3
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·024(0xc27d3bed20, 0xc27e8c8190)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:298 +0x880
github.com/emicklei/go-restful.func·005(0xc27d3bed20, 0xc27e8c8190)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:215 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc27d3bf110, 0xc27d3bed20, 0xc27e8c8190)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·003(0xc27d3bed20, 0xc27e8c8190, 0xc27d3bf110)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:95 +0x88
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc27d3bf110, 0xc27d3bed20, 0xc27e8c8190)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go [[kubelet/v0.17.0 (linux/amd64) kubernetes/fe24da8] 172.20.0.10:53714]
```

(This is on AWS, so I could have misconfigured something.)

I can get kubectl to start responding again by killing the kube-apiserver pod.  Kubelet restarts it and I can use kubectl again.

However, the number of connections in use starts climbing rapidly, by ~ 5/s.

```
netstat -anp | grep 127.0.0.1.4001 | wc -l; sleep 10; netstat -anp | grep 127.0.0.1.4001 | wc -l
889
945
```

**Comment by justinsb** [comment]
Anyone know if this is happening e.g. on GCE?  I see this got tagged as P1, but it also got tagged as aws.

It'll help me narrow it down if I know whether I'm looking for something in the aws setup or in k8s itself.

**Comment by justinsb** [comment]
This seems to have been fixed; I haven't seen this with any of the deployments I was doing this weeked, nor from one I did this morning onto the same system.  Closing.

**Comment by justinsb** [comment]
I was overly optimistic; this is still happening.  It does seem to be leaking a little slower with the newer code though!

**Comment by lavalamp** [comment]
We purposely keep lots of idle connections open; if your setup has more than one etcd server, this would cause us to keep way too many connections open. Is this the case? (also there may be other problems with this setup)

**Comment by justinsb** [comment]
It's a stock setup.  It doesn't seem to be leaking on GCE with the e2e tests.

We do have some processes running on this cluster that use the k8s API, including watching for changes.  These are our own code; my guess is that I messed up in some way here.

This would make sense because it would explain why nobody else has hit this.  I'll try to see if I can figure out what we're doing that is wrong.  (We aren't doing something like starting a new etcd connection for each API watch, are we?)

**Comment by justinsb** [comment]
Ah, I've realized that we are almost definitely opening another etcd connection for each API watch, because etcd uses long-polling.

This means that if "someone" writes a client that leaks watches - which I would _never_ do ;-) - then I think we run out of sockets after ~50000 connections.  And we don't recover particularly well from this - the API essentially hangs.

I don't know if we need to fix this; it is a DoS but relies on having API credentials; there are plenty of more expensive things you can do with credentials.  I'd rather not have a per-account watch quota because it's the sort of thing which ends up biting you when you least expect it.

The most API-user-friendly option would probably be to multiplex API watchers onto etcd watchers, although this is non-trivial if you want to protect against people trying to break you and construct multiple keys to watch.

For the record, an approach would be to combine strictly identical API watches into etcd watches, and  do this until you have N unique keys on a subtree (e.g. /services/).  Once we go >N, we give up on subtree matching and just have one watch on the whole parent /services.  I think this could even be unaware of our structure, and just work with any etcd tree structure.

**Comment by lavalamp** [comment]
@wojtek-t is doing some work that will eventually let us multiplex a few etcd watches instead of our current 1:1 behavior.

**Comment by wojtek-t** [comment]
Actually, we already enabled watch in apiserver (for pods, endpoints and nodes) 2 days ago. This means, that there is exactly one watch connection open to etcd for each of those resources, and the watch is handled completely in apiserver (not "transfered" to etcd).

**Comment by lavalamp** [comment]
Yeah, I think this can be closed as implemented.

**Comment by krmayankk** [comment]
@wojtek-t does this require a flag or feature to be enabled in apiserver ? i am using 1.7.4 and seeing lots of tcp connections open from apiserver to etcd , somewhere around ~2000

**Comment by wojtek-t** [comment]
The watch cache in apiserver is enabled by default since 1.2 or sth like that.
