### ISSUE TITLE
Kubelet service fails to start

### ISSUE THREAD

**Issue by mishaque** [kubernetes/kubernetes#82293]
**What happened**:
Kubelet service fails to start

**What you expected to happen**:
Kubelet service should start without error after installation

**How to reproduce it (as minimally and precisely as possible)**:
yum install kubeadm
systemctl restart kubelet && systemctl enable kebelet

**Anything else we need to know?**:
Here is the error from service:
`Sep 03 15:22:25 lxappstrlprd002 audispd[1483]: node=lxappstrlprd002 type=SERVICE_START msg=audit(1567538545.983:3463): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=kubelet comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

Sep 03 15:22:26 lxappstrlprd002 kubelet[4347]: F0903 15:22:26.035578    4347 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory

Sep 03 15:22:26 lxappstrlprd002 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a

Sep 03 15:22:26 lxappstrlprd002 systemd[1]: Unit kubelet.service entered failed state.

Sep 03 15:22:26 lxappstrlprd002 audispd[1483]: node=lxappstrlprd002 type=SERVICE_STOP msg=audit(1567538546.036:3464): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=kubelet comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'`

**Environment**:
RHEL 7

- Kubernetes version (use `kubectl version`):
1.15.03
kubectl-1.15.3-0.x86_64

- Cloud provider or hardware configuration:
on prem

- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux Server"

VERSION="7.6 (Maipo)"

ID="rhel"

- Kernel (e.g. `uname -a`):
Linux lxappstrlprd002 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
yum

- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zouyee** [comment]
` open /var/lib/kubelet/config.yaml: no such file or directory`

**Comment by neolit123** [comment]
hi, this is not a bug.
the kubelet that the kubeadm packages deploy is crashlooping until you run `kubeadm init`, so you are going to see this error.

once you run `init` it the `config.yaml` file will be created.

i'm going to clsoe this but please ask if you ahve further questions.

/close
