### ISSUE TITLE
Unnecessarily Exported MaxInt in scheduler api types

### ISSUE THREAD

**Issue by ahmad-diaa** [kubernetes/kubernetes#82306]
MaxInt const is exported in scheduler api https://github.com/kubernetes/kubernetes/blob/6cb788c80e93bf0292f0a846ff1b55f690fcc970/pkg/scheduler/api/types.go#L31 although it is not needed to be exported. It is only used by `plugins_test.go`.

https://github.com/kubernetes/kubernetes/pull/81263#discussion_r317606153 discussed that the common practice is to have API constants in `defaults.go`

/sig scheduling

**Comment by ahmad-diaa** [comment]
cc @alculquicondor @ahg-g

**Comment by ahg-g** [comment]
The problem is that it is part of a v1 API :(

**Comment by ahg-g** [comment]
Ok, it turns out they are not actually considered part of the API: https://github.com/kubernetes/kubernetes/pull/82283#issuecomment-528952678

**Comment by ahmad-diaa** [comment]
@ahg-g Should I open a PR to address removing those const values from `types.go`?

**Comment by ahg-g** [comment]
Yes, we can remove those in a followup PR to the one handling sized values.

**Comment by ahmad-diaa** [comment]
Yes, this was the plan.
/assign
