### ISSUE TITLE
Cluster up failure because `kube-controller-manager` is grumpy with GCE

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#8231]
Almost thought it was related to #8196, but it just showed similar symptoms. One of our internal probers failed to bring up a cluster because the node wasn't reporting healthy. It's a 1-node cluster, and `kubectl get nodes` shows as empty. We see a lot of the following in the 

```
E0513 21:35:57.860505       8 nodecontroller.go:247] Error syncing cloud: Get https://www.googleapis.com/compute/v1/projects/cloud-kubernetes-prober/zones/us-central1-f/instances?alt=json&filter=name+eq+k8s-prober-2015-05-13t14-32-12-node.%2A: oauth2/google: can't get a token from the metadata service; not running on GCE
```

Meanwhile, node-1 is trying to dial the master and getting rebuffed:
```
E0513 21:34:27.925099    2961 reflector.go:130] Failed to list *api.Node: Get https://k8s-prober-2015-05-13t14-32-12-master.c.cloud-kubernetes-prober.internal/api/v1beta3/nodes?fieldSelector=metadata.name%3Dk8s-prober-2015-05-13t14-32-12-node-1: dial tcp 10.240.194.68:443: connection refused
```

cc @davidopp @cjcullen (who I think saw something similar).
cc @dchen1107 (don't think it's a node issue this time, though).

I have the cluster up still if someone wants to poke around.

**Comment by gmarek** [comment]
Is there a way to reproduce this problem?

**Comment by zmerlynn** [comment]
> I have the cluster up still if someone wants to poke around.

**Comment by zmerlynn** [comment]
It's actively grumpy.

**Comment by brendandburns** [comment]
The node controller uses GCE MIG introspection to find the set of node machines to add, so it's not surprising that if it can't get an access token, that the cluster doesn't have any nodes.

The question is: why can't it talk to the metadata server? 

And what should we do when this happens?

This looks like a GCE problem, can you ssh into the machine and try to get the token manually?

If that doesn't work, I'd ping someone on the VMM team to diagnose what is hosed in the machine.

I don't think this is P0, as a) it doesn't happen that often, and b) I'm not sure if there is a fix our our side.

**Comment by mikedanese** [comment]
this is very stale at this point, probably not worth leaving open
