### ISSUE TITLE
PodSpec - new readinessGates test

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/kubernetes#82313]
Umbrella issue: #82312

/area conformance
/sig testing

**Comment by BobyMCbobs** [comment]
Last PR related to this: https://github.com/kubernetes/kubernetes/pull/79875

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/issues/75355 there is a test out there already that exercise this, but it's one of our top ten flakes at the moment

**Comment by hh** [comment]
This should probably be left in Backlog, I think Caleb may have moved it by mistake.
I'd like to focus on increasing Endpoints, as it's the only agreed metric we are measuring right now.

**Comment by hh** [comment]
/close
We are focusing on stable endpoints not parameters for now.
We can reopen when we have behaviors up and running.
