### ISSUE TITLE
[Umbrella Issue] PodSpec endpoints

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/kubernetes#82312]
Here are some untested PodSpec endpoints that new tests will be written for, which will be prioritised in this order:
- [readinessGates](https://github.com/kubernetes/kubernetes/issues/82313)
- [prorityClassName](https://github.com/kubernetes/kubernetes/issues/82545)
- hostIPC
- [hostPID](https://github.com/kubernetes/kubernetes/issues/82547)

**Comment by hh** [comment]
hostIPC and hostPID will be a bit different on Windows.

**Comment by devaips** [comment]
PodSpec - new prorityClassName test #82351

**Comment by Jefftree** [comment]
SubIssue: PodSpec endpoints - hostPID test #82547

**Comment by Jefftree** [comment]
@hh @BobyMCbobs It seems that we already have e2e testing for hostIPC and hostPID (https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/security_context_test.go). Is there something you want to cover which is missing from that test?

**Comment by hh** [comment]
I've looked at the test and I think that seems to be promotable.

With regards to the audit logs, I see the e2e.test binary user agent in the logs when this test hits, but the test string (after the --) seems to be missing.

**Comment by Jefftree** [comment]
The hostIPC and hostPID tests are under `tests/e2e_node` and don't get run as a part of Conformance (https://github.com/kubernetes/kubernetes/issues/66875#issuecomment-410893548). We may need to migrate the tests to the `tests/e2e` folder or create some other mechanism.
