### ISSUE TITLE
kubectl describe secret got "namespace: 12bytes"

### ISSUE THREAD

**Issue by farmer-hutao** [kubernetes/kubernetes#82323]
**What happened**:
When I use `kubectl describe secret xxx`, I got something like:
ca.crt: 1025 bytes
namespace: 12bytes

I wander if it should be some info more useful?
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
describe intentionally does not print text content of secrets, just the keys and enough info to see how much data is contained in each

/close
