### ISSUE TITLE
Support newer versions of docker: 19.x

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/kubernetes#82326]
**What would you like to be added**:
Support for newer docker versions: 19.x

**Why is this needed**:
New users trying to use kubernetes install the latest docker version. It's inconvenient see the following warning and have to uninstall docker and then install an older version.

`[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.2. Latest validated version: 18.09`

Also, it's not clear what could happen if someone uses a newer version of docker.
Lastly, I believe that kubernetes should be able to keep up with docker.
Is there any roadmap for this, that I have missed?

**Comment by dims** [comment]
@LSmyrnaios you could work with sig-testing and sig-node to set up CI jobs when new versions of Docker shows up. Believe me, it's more inconvenient to debug failures in a new docker version as a end use than the downgrade. We have to have some CI coverage of a version before we ok its use by the community.

**Comment by LSmyrnaios** [comment]
Hi @dims,
I'm new to this, so I'm not sure how to apply your suggestions about "sig-testing", "sig-node" and "CI jobs".

Is there any documentation that I could use?

**Comment by dims** [comment]
SIGs are teams working on specific areas of kubernetes
- https://github.com/kubernetes/community/tree/master/sig-testing
- https://github.com/kubernetes/community/tree/master/sig-node

All our test infrastructure for CI jobs ("Continuous Integration") is in:
- https://github.com/kubernetes/test-infra

Out test-grid is here (please type docker in the search box on top to see the current CI jobs):
- https://testgrid.k8s.io/

**Comment by mrueg** [comment]
Since docker-ce 18.09 has reached EOL and there are no new versions planned (https://github.com/docker/docker-ce/pull/621#issuecomment-545649667), it would be great to have official support for a newer version of docker-ce.

**Comment by neolit123** [comment]
please see:
https://github.com/kubernetes/kubeadm/issues/1821#issuecomment-539059244

**Comment by david-yu** [comment]
Hi folks, David from Docker here, we have run and validated Docker Engine 19.03 for Kubernetes 1.14 back in June, so Docker 19.03 is indeed supported for Kubernetes 1.14 and above: https://testgrid.k8s.io/sig-node-docker#Summary

Let me know how else we can help.

**Comment by neolit123** [comment]
thanks for confirming @david-yu 
PR is here https://github.com/kubernetes/kubernetes/pull/84476

**Comment by david-yu** [comment]
Thank you @neolit123. Appreciate the PR, we typically test engines for major versions of Engine that are released like 19.03 with the latest version of Kubernetes that is available at the time. On our next engine, we will re-run the test and submit the results to testgrid. Let me know how I can better coordinate this.

**Comment by david-yu** [comment]
Also let me know if there is anything else that is needed to close this issue out. Thanks.

**Comment by neolit123** [comment]
hi, the PR should close this issue.

> Let me know how I can better coordinate this.

i guess, one option is just creating a similar issue once the test job is available in test-grid and running green for a while? @yastij or me can then proceed to update the validators.

**Comment by david-yu** [comment]
Ok thank you, that sounds like a good process we can follow moving forward.

**Comment by hakman** [comment]
Hi @neolit123. Any chance this can make its way into 1.16 at least?

This way it may get picker up by Kops and not have to rely on some old and unpatched Docker version. At the moment Docker CE 18.09 is no longer actively supported https://github.com/docker/for-linux/issues/824.

**Comment by neolit123** [comment]
hi, we cannot backport this as it's not a critical fix.
at least in the case of kubeadm the 19.* versions of docker would only print a warning.

**Comment by mrueg** [comment]
@neolit123 but doesn't the existence of a vulnerability make this critical enough?

**Comment by neolit123** [comment]
the usage of Docker 19.* is not blocked in any way in 1.16.
you can ignore the `WARNING SystemVerification` and just use it.

if something was blocking the usage of 19.*, then this is backport worthy.

**Comment by hakman** [comment]
I saw this as the first step before adding 19.03 as a validated external release. Without being documented as such Kops will not pick it up as default and will leave people with old and vulnerable Docker versions.
If this I understand correctly the above comments, 19.03 has been validated for some time, just not documented.

**Comment by neolit123** [comment]
i don't think kops uses the kubeadm validators that reside in k/k/cmd/kubeadm/app/...
this was resolved in this PR https://github.com/kubernetes/kubernetes/pull/84476

the k8s docs for CRI are still out of date:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

so if someone wants to send a PR for that page please go ahead:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/container-runtimes.md

**Comment by hakman** [comment]
I couldn't find any repos missing docker 19.03.4.

Any chance to do the change in the changelog?
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#dependencies
> The list of validated docker versions remains unchanged.
> The current list is 1.13.1, 17.03, 17.06, 17.09, 18.06, 18.09. (#72823, #72831)
