### ISSUE TITLE
kubectl logs should show default container's log if no container specified

### ISSUE THREAD

**Issue by hoyho** [kubernetes/kubernetes#82339]
**What would you like to be added**:
kubectl logs command should show default container's log if no container is specified

**Why is this needed**:
If there's more than one container in a pod, command like `kubectl logs your-pod` will fail. However, we can make it to output default container's log if no specified container name is following. Command like `kubectl exec your-pod sh ` can choose default container in this case.

```bash
➜  ~ kubectl logs csi-xsky-nfs-driver-42zck
Error from server (BadRequest): a container name must be specified for pod csi-xsky-nfs-driver-42zck, choose one of: [driver-registrar csi-xsky-nfs-driver]
➜  ~ kubectl exec -it csi-xsky-nfs-driver-42zck sh
Defaulting container name to driver-registrar.
Use 'kubectl describe pod/csi-xsky-nfs-driver-42zck -n default' to see all of the containers in this pod.
/ #
/ #
```

**Comment by VigneshSP94** [comment]
I am a beginner dev, would love to contribute to the project Kubernetes. I can take this up if some contributors can mentor me with implementing this 👍

**Comment by yue9944882** [comment]
sgtm

**Comment by hoyho** [comment]
There's already a branch to fix it. https://github.com/hoyho/kubernetes/tree/feat/default_log

**Comment by liggitt** [comment]
I'm not sure this is a good idea. If there is more than one container, it is ambiguous which is intended. Especially in the context of admission-injected sidecar containers, it is not clear that picking a random container produces better outcomes for the log consumer. What is the downside to requiring the invocation to be unambiguous?

**Comment by frzme** [comment]
While a random container would certainly be bad the first container in the list seems like a reasonable default. Making it more easy to get to the logs I want would be appreciated

**Comment by liggitt** [comment]
A logs request that doesn't specify a container in a multi-container pod is underspecified. Allowing it to work by defaulting to the first container means an existing scripted logs invocation could silently break if a second container was added to a deployment. Failing early rather than allowing potentially bad data to be returned/propagated/acted on is preferable.

/close

**Comment by captain-kark** [comment]
In my experience, the only time scripts seem to break is when the pod gets a second container and there was no `-c` set in the script.

If containers are a list, wouldn't that imply that every pod is "multi-container"? Seems like the current default behavior is already set to use the first container in the pod, there's just an unspoken condition that the pod is examined up front and checked that there's only one container first.

I don't see a problem converting the current error to warning text to stderr, and reporting that the first container in the pod is being used (or providing that option to the client to use that behavior as the default).

**Comment by dpc** [comment]
Can we just get a field so we can explicitly specify a container as a default one? Pretty pleaase.
