### ISSUE TITLE
Deprecate nodeSelector

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#82331]
**What would you like to be added**:
nodeSelector functionality is covered by node affinity, and so we should consider deprecating the old nodeSelector API.

**Why is this needed**:
Remove redundant functionality and code.

/sig scheduling
/cc @draveness

**Comment by k82cn** [comment]
AFAIK, we can not remove fields of kind without change the version of API; is it possible to reject pod creation if deprecation cycle expired?

/cc @liggitt

**Comment by liggitt** [comment]
no, the field will not be removed from the v1 Pod API

**Comment by liggitt** [comment]
See https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api

> Rule #1: API elements may only be removed by incrementing the version of the API group.
> Once an API element has been added to an API group at a particular version, it can not be removed from that version or have its behavior significantly changed, regardless of track.

https://kubernetes.io/docs/reference/using-api/deprecation-policy/#fields-of-rest-resources

> an individual field which was present in API v1 must exist and function until API v1 is removed

**Comment by draveness** [comment]
In the current documentation https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity, it says

> nodeSelector continues to work as usual, but will eventually be deprecated, as node affinity can express everything that nodeSelector can express.

Do we need to remove the statement from the website to avoid further confusion (this is the second time I saw these kind of questions) or this will probably be removed from in API v2

**Comment by liggitt** [comment]
the statement should be removed from public facing documentation for now
