### ISSUE TITLE
CSI Raw block  error recovery is problematic

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#82340]
It looks like recovery from errors on nodestage and nodepublish is problematic for raw block devices because currently both are clubbed into one operation - `SetUpDevice`.

So what happens if staging succeeds but publishing fails? In that case - volume state is *not* recorded in volume_manager and as a result when pod will be deleted, no `NodeUnstage` will be performed. 

/sig storage
cc @msau42 @vladimirvivien @jsafrane @bertinatto

**Comment by gnufied** [comment]
cc @kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/73773

**Comment by msau42** [comment]
/remove-lifecycle stale
Is this still an issue?
/assign @jsafrane

**Comment by jsafrane** [comment]
This is most likely fixed by @mkimuram's refactoring, added to https://github.com/orgs/kubernetes-csi/projects/4 to re-check.

**Comment by jsafrane** [comment]
Checked in 1.17, `SetupDevice` now calls only `NodeStageVolume`
https://github.com/kubernetes/kubernetes/blob/4578c6c8ce85ea89c055b6be7a51b7c8e573e809/pkg/volume/csi/csi_block.go#L300

`NodePublishVolume` is called only by `MapPodDevice`.

/close
