### ISSUE TITLE
Kubelet marking pods as not ready when all containers are ready (and seem to be running fine)

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kubernetes#82346]
**What happened**:

We occasionally get alerts from our monitoring system that indicate that certain pods that we run as daemonsets are not ready. Upon inspection the pods seem perfectly healthy (logs are flowing work is being done). A `kubectl describe` of the pod shows:

```
...
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   True
  PodScheduled      True
...
```

(in our specific case these pods are kube-proxy, flannel, veneur, & kube2iam)

None of these pods have defined readiness probes, but one of them (veneur) does have a liveness probe.

It is my understanding that if ContainersReady is true and no readiness probe is specified then Ready should always be true.

During one of these incident's I did go ahead and send sigabt the kubelet for the effected node, after that restarted the kubelet the pods were immediately ready again and I pulled the following goroutine dump: https://gist.github.com/SleepyBrett/1375e0e91499aeed1718a95f57574d2e
 
**What you expected to happen**:

Based on my understanding Pods with no defined readiness probe should always be ready unless one of it's containers is in the process of being restarted or is somehow not properly running.

**How to reproduce it (as minimally and precisely as possible)**:

I have no repro for this as such, I'm not sure what causes the situation, at present I have seen no link between the kubelets that exhibit this. Age and load don't seem to be a factor.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.6.0
VERSION_ID=2135.6.0
BUILD_ID=2019-07-30-0722
PRETTY_NAME="Container Linux by CoreOS 2135.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`): Linux ip-172-16-194-142 4.19.56-coreos-r1 #1 SMP Tue Jul 30 06:40:10 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
- Install tools: bootkube/custom bootstrap
- Network plugin and version (if this is a network-related bug): flannel v0.11.0
- Others:

**Comment by ryanmcnamara** [comment]
I saw this issue: https://github.com/kubernetes/kubernetes/issues/80968 which could explain it
But only if your node the pod was running on went into an unknown state

**Comment by SleepyBrett** [comment]
I did some prometheus searching... it seem to effect all pods on the node regardless of defined readiness probe. 

![image](https://user-images.githubusercontent.com/279521/64288340-b4bc9a00-cf16-11e9-8b67-db866093d9c7.png)

**Comment by SleepyBrett** [comment]
> I saw this issue: #80968 which could explain it
> But only if your node the pod was running on went into an unknown state

This looks like it might be the same issue, i do see several kubelet statuses go unknown during the event (pidpressure, memorypressue, diskpressure, ready)

**Comment by sukhong** [comment]
We are encountering this issue as well, and seems like #80968 is the root cause.

We suddenly see all pods in one node being marked as not ready in pod.status.conditions:

status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-21T00:00:57Z"
    status: "True"
    type: Initialized
  - **lastProbeTime: null
    lastTransitionTime: "2019-10-02T11:10:44Z"
    status: "False"
    type: Ready**
  - lastProbeTime: null
    lastTransitionTime: "2019-09-21T00:01:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-21T00:00:52Z"
    status: "True"
    type: PodScheduled

I found that at this exact lastTransitionTime ("2019-10-02T11:10:44Z"), node was unreachable for a brief period of time (saw **node.kubernetes.io/unreachable** taint being applied to this node).

Is this issue fixed yet? This seems to be a very critical bug...

**Comment by SleepyBrett** [comment]
Just had this happen again on a node running 1.16.2

restarting containerd seems to solve this issue

Found the following logs in the kubelet, this may be just before or just after the event.

```
I1024 14:09:16.663246    1392 kubelet.go:1839] skipping pod synchronization - container runtime is down
I1024 14:09:16.747628    1392 log.go:172] http: TLS handshake error from 25.128.28.2:55444: EOF
I1024 14:09:16.784964    1392 kubelet.go:1839] skipping pod synchronization - container runtime is down
I1024 14:09:16.894607    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40190: EOF
W1024 14:09:16.906819    1392 container.go:422] Failed to get RecentStats("/kubepods/burstable/pod53f1a8d0-909a-4d6e-b65a-a766c7b6e6af/cf0bc5ec85693307e91d8fea48edb3463a0183437350215268e85d0f13e1d6ee") while determining the next housekeeping: unable to find data in memory cache
E1024 14:09:16.924084    1392 kuberuntime_container.go:476] preStop hook for container "highlights-composition-nonprod" failed: command '/bin/bash -c sleep 20' exited with 126:
I1024 14:09:16.957957    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40512: EOF
I1024 14:09:16.960222    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40456: EOF
I1024 14:09:17.002791    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40454: EOF
I1024 14:09:17.008454    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40202: EOF
I1024 14:09:17.033286    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40414: EOF
I1024 14:09:17.033985    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40522: EOF
I1024 14:09:17.038586    1392 log.go:172] http: TLS handshake error from 172.16.197.122:40460: EOF
E1024 14:09:17.045038    1392 server.go:767] Error writing response: write tcp 172.16.194.55:10250->25.128.28.2:33432: write: broken pipe
```

**Comment by haosdent** [comment]
https://github.com/kubernetes/kubernetes/pull/83455 could fix this issue.

**Comment by bartelsb** [comment]
We are also experiencing this issue on 1.15.5. Hoping it's fixed in later versions.

**Comment by tedyu** [comment]
@bartelsb 
See @89155
