### ISSUE TITLE
service hairpin test fails when run with CRI-O

### ISSUE THREAD

**Issue by haircommander** [kubernetes/kubernetes#82341]
**Which jobs are failing**:
CRI-O CI
**Which test(s) are failing**:
Services should allow pods to hairpin back to themselves through services
**Since when has it been failing**:
Since https://github.com/kubernetes/kubernetes/pull/81955 merged
**Testgrid link**:
https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/cri-o_cri-o/2759/test_pull_request_crio_e2e_fedora/6815/
**Reason for failure**:
```
Sep  4 10:57:52.251: INFO: Running '/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://172.18.18.64:6443 --kubeconfig=/var/run/kubernetes/admin.kubeconfig exec --namespace=services-5717 hairpin -- /bin/sh -x -c nc -zv -t -w 2 hairpin-test 8080'
Sep  4 10:57:54.382: INFO: rc: 1
Sep  4 10:57:54.382: INFO: Service reachability failing with error: error running &{/go/src/k8s.io/kubernetes/_output/bin/kubectl [kubectl --server=https://172.18.18.64:6443 --kubeconfig=/var/run/kubernetes/admin.kubeconfig exec --namespace=services-5717 hairpin -- /bin/sh -x -c nc -zv -t -w 2 hairpin-test 8080] []  <nil>  + nc -zv -t -w 2 hairpin-test 8080
nc: connect to hairpin-test port 8080 (tcp) timed out: Operation in progress
command terminated with exit code 1
 [] <nil> 0xc001f00240 exit status 1 <nil> <nil> true [0xc0051050f0 0xc005105108 0xc005105120] [0xc0051050f0 0xc005105108 0xc005105120] [0xc005105100 0xc005105118] [0x10ee940 0x10ee940] 0xc00351fc80 <nil>}:
Command stdout:

+ nc -zv -t -w 2 hairpin-test 8080
nc: connect to hairpin-test port 8080 (tcp) timed out: Operation in progress
command terminated with exit code 1
```

It is possible we don't configure a sysctl needed for hairpinning (we try to set as few as possible). Or nc implementations may vary
**Anything else we need to know**:

**Comment by danwinship** [comment]
what network plugin does this run with?

**Comment by haircommander** [comment]
we configure bridge and loopback

**Comment by danwinship** [comment]
adding `"hairpinMode": true` to the bridge CNI config should fix it, I think.

**Comment by haircommander** [comment]
I'll try that, thanks!

**Comment by haircommander** [comment]
@danwinship that worked, thanks!
