### ISSUE TITLE
kube-scheduler bind is async, scheduler-extender how to maintain node/pod cache

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/kubernetes#82359]
**What would you like to be added**:

**Why is this needed**:
according to  [scheduler-extender](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md)

we can configure scheduler.conf  extenders section:  filterVerb, prioritizeVerb, bindVerb.
but, kube-scheduler  filter and prioritize is sync, bind is async,  before bind will call  assume.
maybe some request should be send to scheduler-extender when assumePod in kube-scheduler.

**Comment by Adirio** [comment]
The scheduling framework is adding multiple other points where you will be able to add extensions. You can find all the extension points that are being added [here](https://kubernetes.io/docs/concepts/configuration/scheduling-framework/#extension-points). Scheduling framework is expected to be in beta for version 1.17.

**Comment by draveness** [comment]
> maybe some request should be send to scheduler-extender when assumePod in kube-scheduler.

Emmm, what do you mean by this, could you elaborate a little bit more?

**Comment by teijinyer** [comment]
> > maybe some request should be send to scheduler-extender when assumePod in kube-scheduler.
> 
> Emmm, what do you mean by this, could you elaborate a little bit more?

node only schedulerd  limit the number of  pods of  the same type ， I can use filterVerb to do this feature ，but bind is async
