### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by VigneshSP94** [kubernetes/kubernetes#82354]
So I was reading this nice IBM [article ](https://developer.ibm.com/opentech/2017/06/21/tour-kubernetes-source-code-part-one-kubectl-api-server/) on Kubernetes code base walkthrough, but I could not find the files that the author has mentioned.

For example, he is taking a peek at create.go under the location https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd , but I do not see the file in there.

Instead, I see the create.go under kubectl main repo https://github.com/kubernetes/kubectl/tree/master/pkg/cmd .

How do I go about understanding the codebase?

PS - I am a beginner, apologies if this isn't the right place for this question.

**Comment by dims** [comment]
@VigneshSP94 this is an active project, so lots of movement in the code base. That article is from 2017 as well, so lot of things under the bridge.

@bradtopol can you please help? :)

/close
