### ISSUE TITLE
NetworkProgrammingLatency regressed in 5k-node clusters

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#82364]
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Network&metricname=Load_NetworkProgrammingLatency&Metric=NetworkProgrammingLatency

We regressed between 8/28 and 8/31, basically from: ~30s to 300s+.

Knowing the internals, it's probably that we have more node restarts (or kube-proxy restarts) or sth like that.

This may (or may not) be related to these flakes:
https://github.com/kubernetes/kubernetes/issues/82182

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability-bugs 

Please take a look when you have a chance
/assign @oxddr

**Comment by oxddr** [comment]
I am having a look at 5k run from today. The fail was caused by long POST on nodes during the test, which indicates node/kubelet (the latter in this case) was restarted. I am trying to find a root cause of restarts. High NetworkProgrammingLatency would be cause by those restarts + https://github.com/kubernetes/kubernetes/issues/82378.

**Comment by lachie83** [comment]
Spoke with @wojtek-t and currently this issue is NOT 1.16 RELEASE BLOCKING

**Comment by liggitt** [comment]
@wojtek-t is this still a current issue?

**Comment by wojtek-t** [comment]
I wasn't fixed. But it's definitely not 1.17 issue.

**Comment by wojtek-t** [comment]
I finally looked into it a little bit.
Here are the last findings:

There are a number of test runs that report extremely high values for NetworkProgrammingLatency, e.g.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1313719396765536256
```
{
  "version": "v1",
  "dataItems": [
    {
      "data": {
        "Perc50": 7231.309118,
        "Perc90": 300000,
        "Perc99": 300000
      },
      "unit": "ms",
      "labels": {
        "Metric": "NetworkProgrammingLatency"
      }
    }
  ]
```

Fortunately, whenever we report the metric in kube-proxy, we also log the value there:
https://github.com/kubernetes/kubernetes/blob/a18e5de51a7a4dbbb3bc7cc291df69d5f4c432c1/pkg/proxy/iptables/proxier.go#L1583

So I grepped through all kube-proxy logs and indeed there are some extremely high values there.
Roughly in each kube-proxy I see:
```
I1007 06:15:47.725036       1 proxier.go:1584] Network programming of probes/dns took 431.724983 seconds
I1007 06:15:47.725094       1 proxier.go:1584] Network programming of probes/ping-client took 431.725062 seconds
I1007 06:15:57.755115       1 proxier.go:1584] Network programming of probes/ping-server took 441.755062 seconds
```

All of them are for things from probes/ namespace.

Interestingly the timing matches closing of the previous (density) test.
So it seems to be related to deletion probes in the previous test.

[Note that all other values seem to look reasonable (<30 seconds).]

So the next AI here is to look what is happening in case of deletions and figure out how to fix that.
@robscott - FYI

**Comment by wojtek-t** [comment]
Another data point - it seems to be somehow related to the fact that the "namespace" itself is being deleted before the service itself. [This may explain why we don't observe this behavior for any of our test services.]

**Comment by wojtek-t** [comment]
The corresponding logs from kube-apiserver:
```
I1007 06:15:42.566642      11 httplog.go:89] "HTTP" verb="DELETE" URI="/api/v1/namespaces/probes" latency="3.338392ms" userAgent="clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="35.232.97.226:34778" resp=200


I1007 06:15:47.677449      11 httplog.go:89] "HTTP" verb="DELETE" URI="/api/v1/namespaces/probes/endpoints/ping-client" latency="3.204884ms" userAgent="kube-controller-manager/v1.20.0 (linux/amd64) kubernetes/7a5b058/system:serviceaccount:kube-system:endpoint-controller" srcIP="[::1]:56746" resp=404
I1007 06:15:47.680138      11 httplog.go:89] "HTTP" verb="DELETE" URI="/api/v1/namespaces/probes/endpoints/ping-client" latency="1.79059ms" userAgent="kube-controller-manager/v1.20.0 (linux/amd64) kubernetes/7a5b058/system:serviceaccount:kube-system:endpoint-controller" srcIP="[::1]:56746" resp=404
I1007 06:15:47.680184      11 httplog.go:89] "HTTP" verb="DELETE" URI="/api/v1/namespaces/probes/services/ping-client" latency="11.209295ms" userAgent="kube-controller-manager/v1.20.0 (linux/amd64) kubernetes/7a5b058/system:serviceaccount:kube-system:namespace-controller" srcIP="[::1]:56746" resp=200
I1007 06:15:47.682818      11 httplog.go:89] "HTTP" verb="DELETE" URI="/apis/discovery.k8s.io/v1beta1/namespaces/probes/endpointslices/ping-client-l66p8" latency="5.07612ms" userAgent="kube-controller-manager/v1.20.0 (linux/amd64) kubernetes/7a5b058/system:serviceaccount:kube-system:generic-garbage-collector" srcIP="[::1]:56746" resp=200
```

**Comment by wojtek-t** [comment]
I think I know what is happening here now.

Basically the problem is that if deletion of Endpoints/EndpointSlice object is actually removing some endpoints (underlying pods), then we basically take into account trigger-time from the Endpoints/EndpointSlice object:
https://github.com/kubernetes/kubernetes/blob/e99df0e5a75eb6e86123b56d53e9b7ca0fd00419/pkg/proxy/endpoints.go#L225
https://github.com/kubernetes/kubernetes/blob/e99df0e5a75eb6e86123b56d53e9b7ca0fd00419/pkg/proxy/endpoints.go#L171

But given this is actually the object from before the deletion (last update) it may be arbitrary old.

So for now, we should simply not upload the trigger time from the old objects.
Eventually, we would like to handle service deletions, but these aren't handled well anyway, so that's a separate thing to fix in the future.

I will send out a PR fixing that later today or this week.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/95363 is out of review

**Comment by wojtek-t** [comment]
It seems fine now:
https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Network&metricname=Load_NetworkProgrammingLatency&Metric=NetworkProgrammingLatency
