### ISSUE TITLE
api server discards oidc settings

### ISSUE THREAD

**Issue by Strange-Account** [kubernetes/kubernetes#82362]
**What happened**:
apiserver discards oidc settings

**What you expected to happen**:
apiserver accepts and uses oidc settings

**How to reproduce it (as minimally and precisely as possible)**:
Insert into /etc/kubernetes/manifests/kube-apiserver.yaml

    - --oidc-ca-file=/etc/ssl/certs/oc_ca.crt
    - --oidc-client-id=kubelogin
    - --oidc-groups-claim=groups
    - --oidc-issuer-url=https://KEYCLOAK-FQDN/auth/realms/Kubernetes
    - --oidc-username-claim=email

**Anything else we need to know?**:
After modifying the manifest file, the apiserver restarts for a view seconds (I can see the oidc settings in the api server pod description) and then restart without the settings.

Testing the oidc issuer url from inside the api server pod with curl and the ca certificate was successfull.

The same keycloak server (with the same settings) is working in a kubernetes 1.10 cluster in the same lan.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
VMWare On Premise
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Can you clarify what you mean by "restarts without the settings"?

**Comment by liggitt** [comment]
closing due to lack of information

/close
