### ISSUE TITLE
Allow user/storage plugin to pass filesystem formatting options to mount_linux. 

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#82372]
**What would you like to be added**:

Option to specify "FS formatting" args for `mkfs`  in `mount_linux.go.`

**Why is this needed**:

At present, there is no way to pass `ext4/xfs` formatting options for `mkfs` command in mount_linux.go . It is very useful or necessary to pass various options at time of `mkfs` to speed up the operation..etc . This option can be specified by the user or storage plugin and  it need to be respected at mounter. Unfortunately its not possible atm.

At present, the formatting is done with default options like `-F , -m0`..etc.

~~~
			args = []string{
					"-F",  // Force flag
					"-m0", // Zero blocks reserved for super-user
					source,
				}
			}
			klog.Infof("Disk %q appears to be unformatted, attempting to format as type: %q with options: %v", source, fstype, args)
			_, err := mounter.Exec.Run("mkfs."+fstype, args...)
~~~

https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L316

**Comment by humblec** [comment]
@kubernetes/sig-storage-bugs

**Comment by humblec** [comment]
@msau42 @jsafrane any thoughts on this ?

**Comment by msau42** [comment]
Can the CSI driver make this a StorageClass param if they want to support that?

**Comment by humblec** [comment]
> Can the CSI driver make this a StorageClass param if they want to support that?

Considering `fstype` is a SC option, we can think about `fsOptions` or similar param in SC too. However with current code in mount_linux, we can not make use of this newly added SC param, as `formatAndMount` ONLY have, `options` ( ie mountoptions) as a possible arg in func signature. This `options` arg is filled from all the SPs with `mountoptions` .  

~~~
formatAndMount(source string, target string, fstype string, options []string)
~~~

@msau42  So, my question would be, even if we add new SC parameter , how would we make use of it in mount_linux for FS formatting?

**Comment by humblec** [comment]
One of the obvious method which I can think of here is, introducing a new func similar to `formatAndMountWithOptions`  (....., formatArgs)` then move the core formatting logic to new func, so that the backward compatibility of `formatAndMount` is preserved. Any other suggestions ?

**Comment by humblec** [comment]
Also, in case of CSI, we can fix it with our own implementation of `formatAndMount` , but this issue was opened considering both CSI and in tree drivers. For example, in tree iscsi like drivers make use of this func. If we are only considering CSI, it can be handled via driver code.
