### ISSUE TITLE
Add Authenticator name to authentication.v1.UserInfo

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#82379]
**What would you like to be added**:

Today it is impossible to differentiate users of the same username based on how they authenticated. For example, I could use OIDC to authenticate to a cluster and have the same username as an X509 certificate, but backend authorizers or aggregate API servers wouldn't know the difference between the two users. This would also be helpful in the audit log.

**Why is this needed**:

This would allow more robust authorization based on how the user authenticated. 

For example, if I wanted a cert approver to only approve certificates made by token based users, not by certificate based users, I could later modify the CertificateSigningRequestSpec to add this info and take action on it. This also would allow aggregate API servers to differentiate users.

This could also be beneficial for the implementation of #81028

**Comment by mikedanese** [comment]
I have wanted this. What do people think about surfacing this in extra info?

@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
> This would also be helpful in the audit log.

Including the info in audit probably makes sense, but that doesn't require exposing the info beyond the authentication layer.

> This also would allow aggregate API servers to differentiate users.

Can you give an example of that?

> I have wanted this. What do people think about surfacing this in extra info?

Do you care about the specific named authenticator (e.g. legacy-service-account-token, service-account-token, tokenfile, webhook), or the authentication mechanism (e.g. token, x509, authproxy)?

how would you envision that interacting with mechanisms like impersonation? what would it mean for that field to be absent?

**Comment by mikedanese** [comment]
> Including the info in audit probably makes sense, but that doesn't require exposing the info beyond the authentication layer.

In the certificate API, it would be useful to be able to tell if the x509 authenticator was used to authenticate a CSR creation. Right now there's no good way to create an approver that allows a service account to requests client certs for itself. A one time exfiltrated client cert/key can be used to arbitrarily extend the lifetime of the cert which grants an attacker persistence. I really want an approver to be able to do this (see https://github.com/kubernetes/kubernetes/issues/63732), but I can rationalize building it with this issue.

**Comment by mikedanese** [comment]
> Do you care about the specific named authenticator (e.g. legacy-service-account-token, service-account-token, tokenfile, webhook), or the authentication mechanism (e.g. token, x509, authproxy)?

For the CSR issue, I care about x509.
For auditing, I could go either way.
For authenticator metrics (see #81028), authenticator names would be nice.

**Comment by deads2k** [comment]
If an authenticator/authorizer pair really wanted to do this today, couldn't they use the user.Extra field to provide that information?  

I don't think that we want to introduce the concept of "how did Bob enter" into the primitives we have in kubernetes today, but if a particular set of webhooks wanted to, I think they could do that today.

**Comment by liggitt** [comment]
When authentication methods are stacked, what would the interaction be?

Example:
1. user makes API request to aggregator with a bearer token
2. the aggregator sees the user authenticated via bearer token
3. the aggregator acts as an auth proxy, proxying the request to the aggregated server, encoding user info in headers and vouching for the headers with a client cert
4. the aggregated server sees the user authenticated via an authproxy

is it expected 2 and 4 would authorize things differently?

**Comment by micahhausler** [comment]
>> This also would allow aggregate API servers to differentiate users.

> Can you give an example of that?

If I wanted to write an aggregate API server that did cloudy things but required the authn method to be something specific.

> Do you care about the specific named authenticator (e.g. legacy-service-account-token, service-account-token, tokenfile, webhook), or the authentication mechanism (e.g. token, x509, authproxy)?

Ideally, the specific named authenticator would get included, with webhoook metadata.

**Comment by micahhausler** [comment]
> how would you envision that interacting with mechanisms like impersonation? 

> When authentication methods are stacked, what would the interaction be?

The original method should be included, and additional fields about about the stack could be added. AWS does this today with the encrypted `AWS_SESSION_TOKEN`, each chained assumed role is added there, as well as how the user authenticated

**Comment by micahhausler** [comment]
> If an authenticator/authorizer pair really wanted to do this today, couldn't they use the user.Extra field to provide that information?
> I don't think that we want to introduce the concept of "how did Bob enter" into the primitives we have in kubernetes today, but if a particular set of webhooks wanted to, I think they could do that today.

Ideally, I'd like to know from K8s how this user initially authenticated, not from a 3rd party webhook

**Comment by enj** [comment]
> I don't think that we want to introduce the concept of "how did Bob enter" into the primitives we have in kubernetes today, but if a particular set of webhooks wanted to, I think they could do that today.

In a similar vain, since this seems to be related to controlling authorization based on authentication source, this forces us to turn that source metadata into an API.  To me that is just an implementation detail of the system today.

**Comment by mikedanese** [comment]
@enj what do you think about https://github.com/kubernetes/kubernetes/issues/82379#issuecomment-528504051

**Comment by deads2k** [comment]
> @enj what do you think about [#82379 (comment)](https://github.com/kubernetes/kubernetes/issues/82379#issuecomment-528504051)

@mikedanese 

I think that comment is interested in those particular fields because it considers the case where a CSR is used to produce a client certificate which is later used against the API as a "first among equals" case for the CSR API.

I'd rather see something like the kubelet CSR flow be the first to demonstrate the generic ability to provide signed assertions (or some other mechanism) for proving they had a previously signed certificate. That way the work produced could be leveraged by others to fulfill the same purpose.

**Comment by mikedanese** [comment]
> I think that comment is interested in those particular fields because it considers the case where a CSR is used to produce a client certificate which is later used against the API as a "first among equals" case for the CSR API.

I believe this is the opposite of what I'd like to have. I want to disallow arbitrary credential lifetime extension by writing an approved the with a policy that says it will *not* approve a csr if the creation request was authenticated using the x509 authenticator. This forces the client to e.g. use a service account token, so the time of access after credential exfil is limited to token ttl + cert ttl.

**Comment by anderseknert** [comment]
We use the `--oidc-username-prefix` flag to differentiate OIDC authenticated users from others. Couldn't similar (optional) prefixes be used for other authentication methods as well? It would require any registered prefix to be reserved to it's respective authenticator though, but perhaps that's enforced already. Not sure about the stacked authentication method scenario mentioned by @liggitt though - perhaps that's where a simple model like that breaks down.

**Comment by deads2k** [comment]
> > I think that comment is interested in those particular fields because it considers the case where a CSR is used to produce a client certificate which is later used against the API as a "first among equals" case for the CSR API.
> 
> I believe this is the opposite of what I'd like to have. I want to disallow arbitrary credential lifetime extension by writing an approver with a policy that says it will _not_ approve a csr if the creation request was authenticated using the x509 authenticator. This forces the client to e.g. use a service account token, so the duration of access after credential exfil is limited to token ttl + cert ttl.

That being the case, I think you already have what you need since the kubelet's client certificate should never have the same username as the service account token.

**Comment by mikedanese** [comment]
I don't know how kubelet got mixed in here. The issue I linked above, #63732, concerns certificate issuance for service accounts. It is not currently possible to write an approver (in or out of tree) to write an approver that allows service accounts to request certificates for themselves without introducing a vector for arbitrary credential lifetime extension.

**Comment by immutableT** [comment]
I have a scenario where knowing the name of the authenticator would be very useful. 
Concretely, I am trying to understand how widespread the use of BasicAuth is in my environment.
If [authenticatedUserCounter](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/filters/authentication.go#L50) or [authenticatedAttemptsCounter](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/filters/authentication.go#L59) metric had a label that identified the authenticator this would be a very simple quesiton to answer.
In this context, the name of the authenticator could either be attached to the UserInfo or the Request Interface could be extended to support Name method.
