### ISSUE TITLE
[scheduler] Remove deprecated EBS/GCE/Azure/Cinder predicates

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#82375]
/sig scheduling
/priority important-longterm
/assign

We should remove the EBS/GCE/Azure/Cinder predicates from scheduler after CSIMigration goes GA (probably in 1.18).

https://github.com/kubernetes/kubernetes/blob/8c537b46939beed3713356f71449a8ad6829b725/pkg/scheduler/algorithm/predicates/predicates.go#L80-L95

> Since we are in process of migrating in-tree volume plugins to CSI, there is already a CSI predicate available which handles all volume plugins and hence when using CSI volumes - the cloudprovider specific predicates are not required. We will be able to truly remove these predicates once CSI migration goes GA but we will have a translation layer as well, which would take care of handling in-tree volume plugins even if you are not using CSI. https://github.com/kubernetes/kubernetes/pull/74544#issuecomment-467531169

#### Reference

+ https://github.com/kubernetes/kubernetes/pull/74544#issuecomment-467531169
+ https://github.com/kubernetes/enhancements/issues/625

**Comment by alculquicondor** [comment]
@msau42 do you think it's safe to do this now?

**Comment by msau42** [comment]
We need to confirm that the remaining csi limit predicate correctly translates the intree api objects to csi. @carlory can you check if we have unit test coverage for this?

**Comment by carlory** [comment]
@msau42  The TestCSILimits tests for in-tree volume migration.

https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go#L383-L446
