### ISSUE TITLE
Investigate issues with Network Programming Latency SLO 

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#82378]
**What happened**:
Currently kube-proxy when restarted exposes NetworkProgrammingLatency metric for all endpoints. When it gets restarted it records very long NetworkProgrammingLatency for services, which hasn't changed in a while, causing skew in NetworkProgrammingLatency. 

**What you expected to happen**:
kube-proxy should only record NetworkProgrammingLatency for endpoints, which has been changed from the recent sync.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scalability
/priority important-soon

**Comment by oxddr** [comment]
/retitle Investigate issues with Network Programming Latency SLO

**Comment by wincus** [comment]
I was trying to figure out why our Network Programming Latency had so many spikes and turns out this is the reason. Because of this the metric is of little use as there is no way to discriminate valid from invalid observations.
