### ISSUE TITLE
kubectl hangs on config set

### ISSUE THREAD

**Issue by anderseknert** [kubernetes/kubernetes#82382]
**What happened**:
`kubectl config set` hangs on certain input.

**What you expected to happen**:
That the command returns either successfully or with an error (and a message).

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl config set users.my-user.user.exec.command test`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): tried 1.15.3 and 1.12.10
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): OS X
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/79000?

**Comment by anderseknert** [comment]
Excellent! Thanks @liggitt.
