### ISSUE TITLE
Should recreate evicted statefulset conformance test may encounter host port conflict

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#82387]
**What happened**:

The `Should recreate evicted statefulset` conformance test in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/statefulset.go fails because `Pod ss-0 expected to be re-created at least once`.  This was caused by the `Predicate PodFitsHostPorts failed` scheduling error.  The root cause was a host port conflict for port `21017`.  This port was in-use as an ephemeral port by another application running on the node.

**What you expected to happen**:

`Should recreate evicted statefulset` conformance test handles potential host port conflicts.

**How to reproduce it (as minimally and precisely as possible)**:

Since this is timing related, reproducing the problem is not easy.  Running conformance tests in parallel like is described in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#running-conformance-tests makes it a little easier to reproduce the problem provided there is an application on the host that could yield the host port conflict.

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`): Any
- Cloud provider or hardware configuration: IBM cloud provider
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 4.15.0-58-generic
- Install tools: IBM Cloud Kubernetes Service
- Network plugin and version (if this is a network-related bug): N/A
- Others: None

**Comment by alenkacz** [comment]
This is pretty flaky in our master-blocking dashboards, any chance someone can dive into this @rtheis ?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#GCE,%20master%20(dev)

**Comment by rtheis** [comment]
@alenkacz We stopped running the test because it was so flaky.  Unfortunately, I don't have time in the near term to fix the test.

**Comment by alenkacz** [comment]
@rtheis so when did you disable it and where? It's the test that's failing here, right? https://k8s-testgrid.appspot.com/sig-release-master-blocking#GCE,%20master%20(dev)

**Comment by wongma7** [comment]
The test is racy and relying on `Events`. The PodFitsHostPorts failure is expected, basically the tests creates a situation where kubelet rejects a pod then the test expects statefulset controller to delete and recreate the failed pod.

For example in this failure https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1197810149796876291...

The test starts its watch after the statefulsetcontroller has already deleted 2 failed pods 9e390b91-f904-47e3-b6f4-80f6be7bd67b and 9383a4a9-3ba6-47f7-8c1b-46ad51f8d53c. Then it finds pod 8039864d-5158-4fd9-9b36-f5d438f08456 at 09:54:44.856 in Pending at 09:54:44.856 and waits for it to be deleted. But actually the pod was already deleted by the statefulset controller at about 09:54:42Z

Nov 22 09:54:44.856: INFO: Observed stateful pod in namespace: statefulset-4966, name: ss-0, uid: 8039864d-5158-4fd9-9b36-f5d438f08456, status phase: Pending. Waiting for statefulset controller to delete.

```
{
   "kind":"Event",
   "apiVersion":"audit.k8s.io/v1",
   "level":"RequestResponse",
   "auditID":"dd49ba39-b957-492d-be1c-82268cc086fb",
   "stage":"ResponseComplete",
   "requestURI":"/api/v1/namespaces/statefulset-4966/pods/ss-0",
   "verb":"delete",
   "user":{
      "username":"system:serviceaccount:kube-system:statefulset-controller",
      "uid":"9fae1274-b052-4bcf-a63b-21eb675c5eaa",
      "groups":[
         "system:serviceaccounts",
         "system:serviceaccounts:kube-system",
         "system:authenticated"
      ]
   },
   "sourceIPs":[
      "::1"
   ],
   "userAgent":"kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/d87c921/system:serviceaccount:kube-system:statefulset-controller",
   "objectRef":{
      "resource":"pods",
      "namespace":"statefulset-4966",
      "name":"ss-0",
      "apiVersion":"v1"
   },
   "responseStatus":{
      "metadata":{

      },
      "code":200
   },
   "responseObject":{
      "kind":"Pod",
      "apiVersion":"v1",
      "metadata":{
         "name":"ss-0",
         "generateName":"ss-",
         "namespace":"statefulset-4966",
         "selfLink":"/api/v1/namespaces/statefulset-4966/pods/ss-0",
         "uid":"8039864d-5158-4fd9-9b36-f5d438f08456",
         "resourceVersion":"7168",
         "creationTimestamp":"2019-11-22T09:54:42Z",
         "deletionTimestamp":"2019-11-22T10:00:16Z",
         "deletionGracePeriodSeconds":30,
         "labels":{
            "baz":"blah",
            "controller-revision-hash":"ss-794f5654c6",
            "foo":"bar",
            "statefulset.kubernetes.io/pod-name":"ss-0"
         },
         "ownerReferences":[
            {
               "apiVersion":"apps/v1",
               "kind":"StatefulSet",
               "name":"ss",
               "uid":"a2901bae-2b8c-4af7-af6d-73e6c562f897",
               "controller":true,
               "blockOwnerDeletion":true
            }
         ]
      },
      "spec":{
         "volumes":[
            {
               "name":"default-token-xw4l6",
               "secret":{
                  "secretName":"default-token-xw4l6",
                  "defaultMode":420
               }
            }
         ],
         "containers":[
            {
               "name":"webserver",
               "image":"docker.io/library/httpd:2.4.38-alpine",
               "ports":[
                  {
                     "name":"conflict",
                     "hostPort":21017,
                     "containerPort":21017,
                     "protocol":"TCP"
                  }
               ],
               "resources":{

               },
               "volumeMounts":[
                  {
                     "name":"default-token-xw4l6",
                     "readOnly":true,
                     "mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"
                  }
               ],
               "terminationMessagePath":"/dev/termination-log",
               "terminationMessagePolicy":"File",
               "imagePullPolicy":"IfNotPresent"
            }
         ],
         "restartPolicy":"Always",
         "terminationGracePeriodSeconds":30,
         "dnsPolicy":"ClusterFirst",
         "serviceAccountName":"default",
         "serviceAccount":"default",
         "nodeName":"bootstrap-e2e-minion-group-sslk",
         "securityContext":{

         },
         "hostname":"ss-0",
         "subdomain":"test",
         "schedulerName":"default-scheduler",
         "tolerations":[
            {
               "key":"node.kubernetes.io/not-ready",
               "operator":"Exists",
               "effect":"NoExecute",
               "tolerationSeconds":300
            },
            {
               "key":"node.kubernetes.io/unreachable",
               "operator":"Exists",
               "effect":"NoExecute",
               "tolerationSeconds":300
            }
         ],
         "priority":0,
         "enableServiceLinks":true
      },
      "status":{
         "phase":"Pending",
         "qosClass":"BestEffort"
      }
   },
   "requestReceivedTimestamp":"2019-11-22T09:59:46.039898Z",
   "stageTimestamp":"2019-11-22T09:59:46.042797Z",
   "annotations":{
      "authorization.k8s.io/decision":"allow",
      "authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:controller:statefulset-controller\" of ClusterRole \"system:controller:statefulset-controller\" to ServiceAccount \"statefulset-controller/kube-system\""
   }
}
```

**Comment by wongma7** [comment]
NVM I read the logs wrong, 8039864d-5158-4fd9-9b36-f5d438f08456 wasn't deleted until 09:59:46 after the test already failed. So actually the controller is NOT recreating 8039864d-5158-4fd9-9b36-f5d438f08456 within the 5min timeout even though it did it for 9e390b91-f904-47e3-b6f4-80f6be7bd67b and 9383a4a9-3ba6-47f7-8c1b-46ad51f8d53c:

I1122 09:54:42.743990       1 event.go:281] Event(v1.ObjectReference{Kind:"StatefulSet", Namespace:"statefulset-4966", Name:"ss", UID:"a2901bae-2b8c-4af7-af6d-73e6c562f897", APIVersion:"apps/v1", ResourceVersion:"6230", FieldPath:""}): type: 'Warning' reason: 'RecreatingFailedPod' StatefulSet statefulset-4966/ss is recreating failed Pod ss-0

I1122 09:54:42.801594       1 event.go:281] Event(v1.ObjectReference{Kind:"StatefulSet", Namespace:"statefulset-4966", Name:"ss", UID:"a2901bae-2b8c-4af7-af6d-73e6c562f897", APIVersion:"apps/v1", ResourceVersion:"6230", FieldPath:""}): type: 'Warning' reason: 'RecreatingFailedPod' StatefulSet statefulset-4966/ss is recreating failed Pod ss-0

**Comment by wongma7** [comment]
kubelet says it put 8039864d-5158-4fd9-9b36-f5d438f08456 in Failed state so why is it stuck in Pending?

I1122 09:54:42.875414    1375 event.go:281] Event(v1.ObjectReference{Kind:"Pod", Namespace:"statefulset-4966", Name:"ss-0", UID:"8039864d-5158-4fd9-9b36-f5d438f08456", APIVersion:"v1", ResourceVersion:"6239", FieldPath:""}): type: 'Warning' reason: 'PodFitsHostPorts' Predicate PodFitsHostPorts failed
I1122 09:54:42.893846    1375 config.go:303] Setting pods for source api
I1122 09:54:42.894119    1375 status_manager.go:544] Patch status for pod "ss-0_statefulset-4966(9e390b91-f904-47e3-b6f4-80f6be7bd67b)" with "{}"
I1122 09:54:42.894263    1375 status_manager.go:551] Status for pod "ss-0_statefulset-4966(8039864d-5158-4fd9-9b36-f5d438f08456)" updated successfully: (2, {Phase:Failed Conditions:[] Message:Pod Predicate PodFitsHostPorts failed Reason:PodFitsHostPorts NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2019-11-22 09:54:42 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]})
I1122 09:54:42.894419    1375 status_manager.go:517] Status for pod "8039864d-5158-4fd9-9b36-f5d438f08456" is up-to-date; skipping

**Comment by wongma7** [comment]
Well, the lines I pasted above are extremely suspect.

Good: 

I1122 09:54:42.745101    1375 status_manager.go:544] Patch status for pod "ss-0_statefulset-4966(9383a4a9-3ba6-47f7-8c1b-46ad51f8d53c)" with "{\"status\":{\"message\":\"Pod Predicate PodFitsHostPorts failed\",\"phase\":\"Failed\",\"qosClass\":null,\"reason\":\"PodFitsHostPorts\",\"startTime\":\"2019-11-22T09:54:42Z\"}}"
I1122 09:54:42.745376    1375 status_manager.go:551] Status for pod "ss-0_statefulset-4966(9383a4a9-3ba6-47f7-8c1b-46ad51f8d53c)" updated successfully: (1, {Phase:Failed Conditions:[] Message:Pod Predicate PodFitsHostPorts failed Reason:PodFitsHostPorts NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2019-11-22 09:54:42 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]})

GOod:

I1122 09:54:42.824737    1375 status_manager.go:544] Patch status for pod "ss-0_statefulset-4966(9e390b91-f904-47e3-b6f4-80f6be7bd67b)" with "{\"status\":{\"message\":\"Pod Predicate PodFitsHostPorts failed\",\"phase\":\"Failed\",\"qosClass\":null,\"reason\":\"PodFitsHostPorts\",\"startTime\":\"2019-11-22T09:54:42Z\"}}"
I1122 09:54:42.824770    1375 status_manager.go:551] Status for pod "ss-0_statefulset-4966(9e390b91-f904-47e3-b6f4-80f6be7bd67b)" updated successfully: (1, {Phase:Failed Conditions:[] Message:Pod Predicate PodFitsHostPorts failed Reason:PodFitsHostPorts NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2019-11-22 09:54:42 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]})

Bad:

**I1122 09:54:42.894119    1375 status_manager.go:544] Patch status for pod "ss-0_statefulset-4966(9e390b91-f904-47e3-b6f4-80f6be7bd67b)" with "{}"**
I1122 09:54:42.894263    1375 status_manager.go:551] Status for pod "ss-0_statefulset-4966(8039864d-5158-4fd9-9b36-f5d438f08456)" updated successfully: (2, {Phase:Failed Conditions:[] Message:Pod Predicate PodFitsHostPorts failed Reason:PodFitsHostPorts NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2019-11-22 09:54:42 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]})

**Comment by wongma7** [comment]
I think there is a race in kubelet but cannot narrow it down to being introduced by any recent changes. (Sorry for all the noise, seeing this flake frequently in internal CI and want to fix it)

When kubelet is removing a pod, it syncs it and updates its status. Say it's updating the status of pod 9e390b91-f904-47e3-b6f4-80f6be7bd67b which is being deleted.

https://github.com/kubernetes/kubernetes/blob/72cd1c14ef35e249fddbac1e9410999c24e9ddc8/pkg/kubelet/status/status_manager.go#L522

The Get returns a pod with UID 9e390b91-f904-47e3-b6f4-80f6be7bd67b. The contents of the patch is empty (the diff) because 9e390b91-f904-47e3-b6f4-80f6be7bd67b is already in `Failed` state.

It performs patch anyway. But at this point, in between the Get and the Patch, 9e390b91-f904-47e3-b6f4-80f6be7bd67b in has been deleted and replaced by pod 8039864d-5158-4fd9-9b36-f5d438f08456

https://github.com/kubernetes/kubernetes/blob/72cd1c14ef35e249fddbac1e9410999c24e9ddc8/pkg/kubelet/status/status_manager.go#L543

So 8039864d-5158-4fd9-9b36-f5d438f08456 ends up getting patched. 

It then updates apiStatusVersions for 8039864d-5158-4fd9-9b36-f5d438f08456. https://github.com/kubernetes/kubernetes/blob/72cd1c14ef35e249fddbac1e9410999c24e9ddc8/pkg/kubelet/status/status_manager.go#L552

Shortly after, when kubelet receives pod 8039864d-5158-4fd9-9b36-f5d438f08456 and goes to update its status to `Failed`, it skips it because apiStatusVersions for 8039864d-5158-4fd9-9b36-f5d438f08456 was updated above even though the patch, which was empty, was intended for 9e390b91-f904-47e3-b6f4-80f6be7bd67b.

```
I1122 09:54:42.894419    1375 status_manager.go:517] Status for pod "8039864d-5158-4fd9-9b36-f5d438f08456" is up-to-date; skipping
```

So 8039864d-5158-4fd9-9b36-f5d438f08456 never enters `Failed` state and stays stuck `Pending`.

**Comment by wongma7** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1197810149796876291 is the failure I have been looking at

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/86320 to add a uid precondition to the kubelet pod status patch

**Comment by liggitt** [comment]
The uid-precondition patch should resolve the issue @wongma7 described, will monitor https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master&sort-by-flakiness=&width=10&include-filter-by-regex=StatefulSet for a few days before closing this.

Because this was a real bug, I've opened cherry-picks to release branches as well, but would like to let the fix soak in master for a bit before merging those.

**Comment by liggitt** [comment]
testgrid on that test looks good, will unhold the cherrypicks

/close
