### ISSUE TITLE
Please move pkg/credentialprovider out of tree

### ISSUE THREAD

**Issue by jonjohnsonjr** [kubernetes/kubernetes#82396]
**What would you like to be added**:

I would like to be able to import pkg/credentialprovider.

**Why is this needed**:

https://github.com/google/go-containerregistry/issues/496

**Comment by jonjohnsonjr** [comment]
/sig auth
/sig release
/sig cloud-provider

cc @fejta @ImJasonH @bobcatfish

**Comment by liggitt** [comment]
See also https://github.com/kubernetes/kubernetes/issues/74379

/area code-organization

**Comment by BenTheElder** [comment]
cc

**Comment by andrewsykim** [comment]
cc @mcrute @nckturner @M00nF1sh

**Comment by andrewsykim** [comment]
So @mcrute is doing some work on external credential providers https://github.com/kubernetes/enhancements/pull/1284 -- but I wonder if it's worthwhile to stage `pkg/credentalprovider` in the meantime anyways? Are there enough external consumers of `pkg/credentialprovider` to justify this?

**Comment by jonjohnsonjr** [comment]
> I wonder if it's worthwhile to stage pkg/credentalprovider in the meantime anyways?

I think it would be nice from an open source stewardship perspective. There's been a mechanism in go since [1.4](https://golang.org/doc/go1.4#internalpackages) for making packages private that kubernetes doesn't use. Instead, kubernetes just [intentionally breaks](https://github.com/kubernetes/kubernetes/issues/81878) anyone who took a dependency on the "wrong" packages, which, IMHO, is pretty rude :smile: 

>  Are there enough external consumers of pkg/credentialprovider to justify this?

I get harassed about this pretty frequently, so _I'd_ certainly appreciate it :smile: How many people would have to be affected by this to make it worth doing?

**Comment by jonjohnsonjr** [comment]
Is there any way I can help with this?

**Comment by glyn** [comment]
https://github.com/google/go-containerregistry is consumed by many projects including some that I'm involved with, so I'd like to see progress on this issue and am also happy to help. How's it going @andrewsykim?

**Comment by dims** [comment]
@glyn @jonjohnsonjr let's help by reviewing https://github.com/kubernetes/enhancements/pull/1406
