### ISSUE TITLE
"Must be a valid IP address or a valid RFC-1123 DNS subdomain" error occurred when installing kubernetes 1.15 cluster using kubeadm

### ISSUE THREAD

**Issue by Rettpa** [kubernetes/kubernetes#82399]
kubeadm-config.yaml:
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.3
controlPlaneEndpoint: "internal-ELB-K8sApiHTTP-APP-1600381234.cn-northwest-1.elb.amazonaws.com.cn:9443"
networking:
 podSubnet: "10.244.0.0/16"
apiServer:
 certSANs:
 - "internal-ELB-K8sApiHTTP-APP-1600381234.cn-northwest-1.elb.amazonaws.com.cn"

Use commands：kubeadm init --config=kubeadm-config.yaml
errors： “hostport internal-ELB-K8sApiHTTP-APP-1600381234.cn-northwest-1.elb.amazonaws.com.cn:9443: host 'internal-ELB-K8sApiHTTP-APP-1600381234.cn-northwest-1.elb.amazonaws.com.cn' must be a valid IP address or a valid RFC-1123 DNS subdomain”

"Internal-ELB-K8s ApiHTTP-APP-1600381234.cn-northwest-1.elb.amazonaws.com.cn" domain name is available

**Comment by MartinForReal** [comment]
according to [code](https://github.com/kubernetes/apimachinery/blob/461753078381c979582f217a28eb759ebee5295d/pkg/util/validation/validation.go#L132)
domain name should be in lower case.  you could add a record in route53. FYI
