### ISSUE TITLE
health-monitor should save kubelet coredump before restarting it

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#82408]
**What would you like to be added**:
[health-monitor.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/health-monitor.sh#L79) should save kubelet coredump before restarting it. 

**Why is this needed**:
We were unable to understand kubelet restart, which caused https://github.com/kubernetes/kubernetes/issues/82377. Logs didn't have enough information to determine the cause. 

/sig scalability

**Comment by brysonshepherd** [comment]
I agree that this is needed
