### ISSUE TITLE
kubectl proxy fails to proxy http call to service

### ISSUE THREAD

**Issue by niklun** [kubernetes/kubernetes#82402]
**What happened**:
Used `kubectl proxy` to proxy http calls to a service. Included a dryRun query parameter. The request failed and the api responded HTTP 400:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "dryRun is not supported",
  "reason": "BadRequest",
  "code": 400
}
```

**What you expected to happen**:
I expected a call like `DELETE http://127.0.0.1:8080/api/v1/namespaces/default/services/myservice/proxy/api/delete?dryRun=true` to end up in my service. The dryRun parameter has nothing to do with the kubernets api in this case, anything after /proxy should just be forwarded to the service.

**How to reproduce it (as minimally and precisely as possible)**:
Start `kubectl proxy` and make a call to to any service proxy and include a dryRun query parameter.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:18:50Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by laddng** [comment]
@niklun I did some digging and found this PR that disables dry runs for most commands: https://github.com/kubernetes/kubernetes/pull/66083 might be useful information for your issue.

**Comment by niklun** [comment]
@laddng thanks. I've made a comment on that PR because I don't understand why it should be rejected.

**Comment by zryfish** [comment]
Ran into the same issue here,  @niklun how do you solve this?

**Comment by niklun** [comment]
@zryfish It is not solved. Using port-forward when I need to access an internal api with dryRun... not the best solution in the long run.
