### ISSUE TITLE
kubeadm should support domain name in --apiserver-advertise-address in phase "kubeadm alpha kubeconfig" 

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/kubernetes#82404]
**What would you like to be added**:
kubeadm should support domain name in AdvertiseAddress in phase "kubeadm alpha kubeconfig" 
only ip address is supported now. 

**Why is this needed**:
I need to generate discovery file for worker node on cloud and I don't know the ip address of control plane before master node is provisioned. 
Here I can use dns record to resolve this issue.

**Comment by neolit123** [comment]
hi, please re-open this in the kubernetes/kubeadm repository where we track kubeadm tickets.
thanks

/close
