### ISSUE TITLE
[Failing Test] [k8s.io] Security Context

### ISSUE THREAD

**Issue by zhlhahaha** [kubernetes/kubernetes#82419]
**Which jobs are failing**:
ci-kubernetes-node-kubelet-orphans

**Which test(s) are failing**:
[k8s.io] Security Context When creating a container with runAsNonRoot should run with an image specified user ID

**Since when has it been failing**:
https://github.com/kubernetes/kubernetes/compare/a1f1f0b59...baaec43cd

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-orphans

**Reason for failure**:
```
• Failure [6.248 seconds]
[k8s.io] Security Context
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:693
  When creating a container with runAsNonRoot
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/security_context.go:98
    should run with an image specified user ID [It]
    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/security_context.go:145

    Image "gcr.io/kubernetes-e2e-test-images/nonroot:1.0" is not in the white list, consider adding it to CommonImageWhiteList in test/e2e/common/util.go or NodeImageWhiteList in test/e2e_node/image_list.go
    Expected
        <bool>: false
    to be true

    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:210
```
**Anything else we need to know**:

**Comment by zouyee** [comment]
duplicate https://github.com/kubernetes/kubernetes/issues/82352

**Comment by zhlhahaha** [comment]
Hi @zouyee  The two issues are report different test errors. Do they duplicate?
