### ISSUE TITLE
kube-proxy error when use hack/local-up-cluster.sh

### ISSUE THREAD

**Issue by zhlhahaha** [kubernetes/kubernetes#82412]
**What happened**:
When I use local-up-cluste.sh to build a local k8s environment, it end up with following information "kube-proxy terminated unexpectedly, see /tmp/kube-proxy.log" 

In /tmp/kube-proxy.log
```
E0906 18:25:04.661869   41689 node.go:124] Failed to retrieve node info: nodes "127.0.0.1" not found
E0906 18:25:05.837213   41689 node.go:124] Failed to retrieve node info: nodes "127.0.0.1" not found
E0906 18:25:08.212099   41689 node.go:124] Failed to retrieve node info: nodes "127.0.0.1" not found
E0906 18:25:12.701344   41689 node.go:124] Failed to retrieve node info: nodes "127.0.0.1" not found
E0906 18:25:21.183640   41689 node.go:124] Failed to retrieve node info: nodes "127.0.0.1" not found
F0906 18:25:21.183724   41689 server.go:443] unable to get node IP for hostname 127.0.0.1
```
And kube-proxy failed to start.

**What you expected to happen**:
All service start successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Get recent kubernetes code, and run ./hash/local-up-cluster.sh
Then, follow the instruction to setup etcd and install necessary software.
After finish setup, the error can be seen.

**Anything else we need to know?**:
I reproduced it on both arm and x86 servers.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.0-alpha.0.1154+674518a561521b-dirty
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS 
- Kernel (e.g. `uname -a`): Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:32:18 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: run ./hash/local-up-cluster.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by janitha09** [comment]
HOSTNAME_OVERRIDE

**Comment by yacinelazaar** [comment]
@zhlhahaha did you manage to solve this?

> HOSTNAME_OVERRIDE

@janitha09 Care to elaborate on this?

**Comment by zhlhahaha** [comment]
hi @yacinelazaar  I think it had been fixed in following commit.
[commit](https://github.com/kubernetes/kubernetes/commit/c13f2d47483a3ba712ee820a76d9c089e3f25a4a)
