### ISSUE TITLE
kubectl --dry-run does not report error when secret is not encrypted with base64

### ISSUE THREAD

**Issue by jessie-JNing** [kubernetes/kubernetes#82421]
**What happened**:
When deployed an experimental `secret` resource using `kubectl create -f secret.yaml`, an error was thrown as below, since one of the secret is not encrypted with base64. 
```
Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 2, error found in #10 byte of
```
However, it worked fine during dry-run `kubectl create -f secret.yaml --dry-run`.

**What you expected to happen**:
- The error should be caught during dry-run.
- The error message exposes secret key-values. Sensitive info should be suppressed in message . 

**How to reproduce it (as minimally and precisely as possible)**:
<details><summary>secret.yaml</summary>
<p>

```
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  username: my_username
  password: cGFzc3dvcmQ=
```
</p>
</details>

with dry-run: 
```
> kubectl --context=minikube create -f secret.yaml --dry-run
secret/hello-secret created (dry run)
```
without dry-run:
```
> kubectl --context=minikube create -f secret.yaml
Error from server (BadRequest): error when creating "test/fixtures/hello-cloud/secret.yml": Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 2, error found in #10 byte of ...|_username"},"kind":"|..., bigger context ...|"password":"cGFzc3dvcmQ=","username":"my_username"},"kind":"Secret","metadata":{"name":"hello-secret|...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.7
- OS (e.g: `cat /etc/os-release`): linux/amd64
- Kernel (e.g. `uname -a`): Darwin

**Comment by zouyee** [comment]
using `--server-dry-ru` instead.

**Comment by liggitt** [comment]
The format validation happens server-side, not client-side, so `--dry-run` would not be able to perform that validation. Use `--server-dry-run` to perform server-side validation.

**Comment by jessie-JNing** [comment]
Thanks @zouyee and @liggitt !
It's good to know `--server-dry-run`, and it works for us~
