### ISSUE TITLE
Unable to use go modules in device plugins

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#82437]
**What happened**:

As described at https://github.com/intel/sriov-network-device-plugin/pull/160#issuecomment-528482988 when I ran "go get k8s.io/kubernetes" it gave me the following error:

...initial bit snipped...
go: k8s.io/cluster-bootstrap@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-proxy@v0.0.0: unknown revision v0.0.0
go: k8s.io/code-generator@v0.0.0: unknown revision v0.0.0
go: k8s.io/metrics@v0.0.0: unknown revision v0.0.0
go: k8s.io/kubelet@v0.0.0: unknown revision v0.0.0
go: k8s.io/legacy-cloud-providers@v0.0.0: unknown revision v0.0.0
go: error loading module requirements

**What you expected to happen**:

That it would update the kubernetes dependency appropriately.

**How to reproduce it (as minimally and precisely as possible)**:

git clone git@github.com:intel/sriov-network-device-plugin.git
cd sriov-network-device-plugin
go get k8s.io/kubernetes

**Anything else we need to know?**:

According to golang/go#32776 it might be a problem with specifying k8s.io/kubernetes as a dependency.  At that link it says " k8s.io/kubernetes is not primarily intended to be consumed as a module. Only the published subcomponents are (and go get works properly with those)."  If that's the case, then the deviceplugin API needs to be published as a subcomponent because clearly all device plugins need to be able to import the deviceplugin API.

**Comment by cbf123** [comment]
@kubernetes/sig-node-bugs

**Comment by dims** [comment]
Looks like the repo in question just uses code under `k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin`, we could just move that to staging hopefully

**Comment by dims** [comment]
note from @RenaudWasTaken in email:

```
We probably need to graduate the device plugin to v1 beforehand.

We expect changes in that api for the NUMA effort though so we might want to wait for the next release.
```
