### ISSUE TITLE
[Tracking Issue] Ensure SIG-Networking Source Pod IP preservation test errors properly

### ISSUE THREAD

**Issue by soggiest** [kubernetes/kubernetes#82445]
Per PR [82420](https://github.com/kubernetes/kubernetes/pull/82420) the test `Kubernetes e2e suite [sig-network] Services should preserve source pod IP for traffic thru service cluster IP [LinuxOnly]` fails to error properly. One line of particular interest from that PR:

`
If you wonder why it does not fail on docker, that's because the test does not report the error correctly but fails the same way.
`

This issue is intended to track the discussion and resolution of making this test error properly so that it is useful to CI Signal

/sig networking
/cc @alejandrox1 @lachie83 @liggitt

**Comment by saschagrunert** [comment]
I'm following up on this in #82491
