### ISSUE TITLE
RWX PVC fails with 'multi attach error'

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#82453]
Description of problem:
 A shared PVC (on Ceph and VolumeMode=Filesystem ) can't be used at same time in more than one pod.

The second pod is stuck in "ContainerCreating" state with error:

~~~
# oc get pod
NAME                               READY     STATUS              RESTARTS   AGE
virt-launcher-vm-dv-cirros-mk5vg   0/1       ContainerCreating   0          25s
virt-launcher-vm-dv-cirros-v72rs   1/1       Running             0          2m5s
~~~

~~~
# oc describe pod virt-launcher-vm-dv-cirros-mk5vg
 .
 Warning  FailedMount  27s (x8 over 1m)  kubelet, cluster1-4pt9b-worker-0-rwq2g  MountVolume.SetUp failed for volume "pvc-eb52992f-d00c-11e9-be37-5254001e809d" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume pvc-eb52992f-d00c-11e9-be37-5254001e809d for pod default/virt-launcher-vm-dv-cirros-mk5vg. Volume is already attached by pod default/virt-launcher-vm-dv-cirros-v72rs. Status Running

# oc get pv
pvc-eb52992f-d00c-11e9-be37-5254001e809d   2Gi        RWX            Retain           Released    default/dv-cirros                       rook-ceph-block             8m

~~~

**Comment by humblec** [comment]
@kubernetes/sig-storage-bugs

**Comment by humblec** [comment]
@msau42 @jsafrane

**Comment by msau42** [comment]
That looks like an error from Rook, not k8s

**Comment by humblec** [comment]
> That looks like an error from Rook, not k8s

Indeed I was expecting some other layer than Kube. The main reason being if this is the case, it would be a general/common issue in kube and a nasty one. But one thing which I am not understanding here is, the `failedMount` is executed from Kubelet and the status or error is from kube source. The suspects in user/storage vendor side are 'accessModes` in PV and PVC , but from above outputs those are `RWX`, so confused. Any thoughts on what else can be checked.

**Comment by cwdsuzhou** [comment]
Can you  show more logs?

**Comment by humblec** [comment]
I am still trying to capture logs, but it looks like , eventhough the kubelet reported the error, the validation of multi attach and failure is actually attempted and reported from Rook to Kubelet. So, the culprit would be Rook here than kubelet. Let me close this issue for now and reopen if required. Thanks for sharing the thoughts.
