### ISSUE TITLE
update pod failed

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#82451]
kubernetes 1.13
if I change mounted configmap data
then update one pod image by "kubectl edit pod"
pod fail to start

   message: |
          oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/ae8515fc-d13c-11e9-8dd5-0017a477045c/volume-subpaths/ddd-x0/devfelix1/0\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/3b0f1ed4c5770712682cfa4e470c39d9173270a46715b9dee21df285a6c25649/rootfs\\\" at \\\"/var/lib/docker/devicemapper/mnt/3b0f1ed4c5770712682cfa4e470c39d9173270a46715b9dee21df285a6c25649/rootfs/xx/vv/kk\\\" caused \\\"no such file or directory\\\"\""
        reason: ContainerCannotRun

**Comment by timchenxiaoyu** [comment]
@kubernetes/sig-node-bugs

**Comment by zouyee** [comment]
would you like to share your manifest？

**Comment by timchenxiaoyu** [comment]
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
  creationTimestamp: "2019-09-06T07:32:15Z"
  generation: 11
  labels:
    grey: from
    paas.io/clusterName: k8s-dev
    paas.io/name: devfelix1
    paas.io/serviceName: devfelix1
  name: devfelix1
  namespace: dev
  resourceVersion: "5274843"
  selfLink: /apis/extensions/v1beta1/namespaces/dev/deployments/devfelix1
  uid: 73184759-d078-11e9-8dd5-0017a477045c
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      paas.io/name: devfelix1
      paas.io/serviceName: devfelix1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        grey: from
        paas.io/clusterName: k8s-dev
        paas.io/name: devfelix1
        paas.io/serviceName: devfelix1
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep 3600
        env:
        - name: KUBERNETES_FILELOGS
          value: /viewlogs
        - name: GO
          value: ffDDDVVVll
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: devfelix1
              divisor: "0"
              resource: limits.cpu
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: devfelix1
              divisor: "0"
              resource: limits.memory
        image: xxxx/dev/devfelix1:20190620193804826923691
        imagePullPolicy: IfNotPresent
        name: devfelix1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4096M
          requests:
            cpu: 200m
            memory: 3276M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /xx/vv/kk
          name: ddd-x0
          subPath: kk
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 511
          items:
          - key: kk
            path: kk
          name: ddd
        name: ddd-x0


-----------------------
apiVersion: v1
items:
- apiVersion: v1
  data:
    kk: vvvvkkk
  kind: ConfigMap
  metadata:
    name: ddd
    namespace: dev

**Comment by windniw** [comment]
@timchenxiaoyu could you format the manifest?

**Comment by ProgramerGu** [comment]
Can pod been updated without rebuild?
