### ISSUE TITLE
kubeadm: Ability to add environment variables to static pod manifests

### ISSUE THREAD

**Issue by rkojedzinszky** [kubernetes/kubernetes#82456]
**What would you like to be added**:
It would be useful to be able to add environment variables to ClusterConfiguration in a similar way as extraArgs can be.

**Why is this needed**:
I use k8s on PI boards, where RAM is limited. Now I've added GOGC=25 to my generated static pod manifest files, but a kubeadm upgrade will overwrite that. You can see the difference of memory usage after the setting has been applied at 16:40 09/07/2019 CEST: https://snapshot.raintank.io/dashboard/snapshot/1FqncpBN0vU32o9GUOYu6RfhvOQm2QDG

**Comment by neolit123** [comment]
hi, we took a different approach and allowed kustomizations over the static pod manifests, which is patching over the kubeadm defaults:
https://github.com/kubernetes/kubeadm/issues/1379

please re-open this ticket in the k/kubeadm repo if you think your approach is still viable.

/close
