### ISSUE TITLE
Document what kind of PRs are good for cherry-picks

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#82467]
We have a document on how to do cherry picks:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#initiate-a-cherry-pick

But we don't have a document which lays out what PRs are good candidates for cherry-picks, do we? This will help both reviewers and release managers when the times comes to make a decision. This is a good source to point at for folks in the community when they come asking for specific cherry-picks.

/sig release

**Comment by dims** [comment]
case in point https://github.com/kubernetes/kubernetes/pull/82446

**Comment by dims** [comment]
related to https://github.com/kubernetes/sig-release/issues/611

**Comment by tpepper** [comment]
@dims does https://github.com/kubernetes/community/pull/4186 help?

**Comment by dims** [comment]
yes it does. thanks @tpepper

**Comment by feiskyer** [comment]
so I think https://github.com/kubernetes/community/pull/4186 already provides the enough information. All cherry pick PRs would be filled with its link, e.g. 

> For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

**Comment by tpepper** [comment]
@dims is there additional info sought, if so I'm happy to do more or ready to close this?

**Comment by dims** [comment]
+1 to close this for now @tpepper 

/close
