### ISSUE TITLE
Some questions about Huge Pages and NUMA

### ISSUE THREAD

**Issue by andyzheung** [kubernetes/kubernetes#82469]
I read  community/contributors/design-proposals/resource-management/hugepages.md, and said that :

Initially, a pod may not consume multiple huge page sizes in a single pod spec. Attempting to use hugepages-2Mi and hugepages-1Gi in the same pod spec will fail validation. We believe it is rare for applications to attempt to use multiple huge page sizes. **This restriction may be lifted in the future with community presented use cases.** Introducing the feature with this restriction limits the exposure of API changes needed when consuming huge pages via volumes.

---> Is this the roadmap that which time will lifted the restriction? So that we can use multiple hugespages in the same pod?

NUMA is complicated. To support NUMA, the node must support cpu pinning, devices, and memory locality. Extending that requirement to huge pages is not much different. It is anticipated that the kubelet will provide future NUMA locality guarantees as a feature of QoS. In particular, pods in the Guaranteed QoS class are expected to have NUMA locality preferences.

-->In the nearly new kubernetes version, NUMA is still not supported. Does this also  have any roadmap how we can use NUMA in pod?

**Comment by odinuge** [comment]
Hi @andyzheung! Here are some simple answers to your questions. :smile: 

> Is this the roadmap that which time will lifted the restriction? So that we can use multiple hugespages in the same pod?

Node level support for multiple sizes is discussed in https://github.com/kubernetes/kubernetes/issues/77251. Pod level support will be a bit cumbersome to support, as it will require (potentially) breaking changes to how to volumes are mounted. It has been discussed briefly in https://github.com/kubernetes/kubernetes/issues/80716, but I haven't seen anyone request it. If you are interested in pod level support for using huge pages with different sizes, i think you should create a new issue with your usecase so we can start the discussion.

> -->In the nearly new kubernetes version, NUMA is still not supported. Does this also have any roadmap how we can use NUMA in pod?

There has been some work on a new topology manager (that is related to NUMA, but consists of some other things as well), and you can read more about it here: https://github.com/kubernetes/enhancements/issues/693.

Regarding huge pages and NUMA, there has been some discussion in
https://github.com/kubernetes/kubernetes/issues/81009 & https://github.com/kubernetes/kubernetes/issues/80716, together with their corresponding KEPs.


I hope this answers some of your questions! Feel free to ask follow up questions here (or in the other issues/prs), and close it if i answered all your questions. :smile:

**Comment by andyzheung** [comment]
> Hi @andyzheung! Here are some simple answers to your questions. 😄
> 
> > Is this the roadmap that which time will lifted the restriction? So that we can use multiple hugespages in the same pod?
> 
> Node level support for multiple sizes is discussed in #77251. Pod level support will be a bit cumbersome to support, as it will require (potentially) breaking changes to how to volumes are mounted. It has been discussed briefly in #80716, but I haven't seen anyone request it. If you are interested in pod level support for using huge pages with different sizes, i think you should create a new issue with your usecase so we can start the discussion.
> 
> > -->In the nearly new kubernetes version, NUMA is still not supported. Does this also have any roadmap how we can use NUMA in pod?
> 
> There has been some work on a new topology manager (that is related to NUMA, but consists of some other things as well), and you can read more about it here: [kubernetes/enhancements#693](https://github.com/kubernetes/enhancements/issues/693).
> 
> Regarding huge pages and NUMA, there has been some discussion in
> #81009 & #80716, together with their corresponding KEPs.
> 
> I hope this answers some of your questions! Feel free to ask follow up questions here (or in the other issues/prs), and close it if i answered all your questions. 😄

I am so happy that you reply, and is the multiple hugepage patch can show me to refer?

**Comment by odinuge** [comment]
> I am so happy that you reply, and is the multiple hugepage patch can show me to refer?

I replied in #77251. Closing this, so we can continue the discussion in #77251. :smile: 

/close
