### ISSUE TITLE
Reduce vmssVM API calls with InstanceView expansion

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#82460]
**What would you like to be added**:

Currently, Azure cloud provider invokes `VirtualMachineScaleSetVMsClient.Get()` and `VirtualMachineScaleSetVMsClient.GetInstanceView()` to fetch VMSS nodes information:

https://github.com/kubernetes/kubernetes/blob/90f41951cd53ec63bf13d52371f88bbc3bb764db/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go#L190-L219

This is because instanceView expansion is not supported in VirtualMachineScaleSetVMsClient.

However, with Azure Go SDK v33.1.0, the expansion is supported:

https://github.com/Azure/azure-sdk-for-go/blob/98353253a537e7e94652d100d7d78b30a4a7ee21/services/compute/mgmt/2019-07-01/compute/virtualmachinescalesetvms.go#L202-L208

We should update SDK and remove `VirtualMachineScaleSetVMsClient.GetInstanceView()` calls.

**Why is this needed**:

/area provider/azure
/milestone v1.17
/assign

**Comment by hasheddan** [comment]
@feiskyer I would be happy to take this issue!

**Comment by feiskyer** [comment]
@hasheddan  Cool, thanks.
