### ISSUE TITLE
Should we give bind a timeout mechanism?

### ISSUE THREAD

**Issue by ProgramerGu** [kubernetes/kubernetes#82476]
**What would you like to be added**:a timeout mechanism for bind

**Why is this needed**:if kube-schduler already pick a suggest-host for pod,it 
call bind() function ,if it didn`t return fail then put result in cache .And in cache cleanup mechanism.If it haven`t been finished,it stuck forever,unless we restart kube-scheduler or call forget.Should we git it a timeout error and stop syce this pod?

**Comment by draveness** [comment]
/sig scheduling

Do you mean `BindTimeoutSeconds` in the scheduler configuration?
