### ISSUE TITLE
No (auto)generated conversions for apimachinery and apiserver objects

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#82484]
I was recently looking into pprof graphs from our tests, and found out that we're spending a lot of time in `defaultConvert` function (e.g. this run:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1169656830515744771/artifacts/?marker=logs%2fci-kubernetes-e2e-gce-scale-performance%2f1169656830515744771%2fartifacts%2fgce-scale-cluster-minion-group-vpbl%2f
)

I looked into it and it seems that most of these are coming from;
- `v1.UserInfo` -> `audit.UserInfo`
- `v1.ListOptions` -> `internal.ListOptions`
[and other similar]

Obviously, defaultConvert (that works on reflection) is waaay less optimal than auto-generated stuff.

We're auto-generating conversion function for our APIs, that apparently, we're not doing that for:
- [x] meta.v1, meta.v1beta1: https://github.com/kubernetes/apimachinery/tree/master/pkg/apis/meta/v1
- [x] for `v1.UserInfo` - apparently, `UserInfo` is not a type in `apiserver/pkg/apis/audit/v1/types.go` (only in internal) and its converted from `authentication/v1`

It seems we can save a lot of allocations by avoiding these.

@kubernetes/sig-scalability-bugs @kubernetes/sig-api-machinery-bugs

**Comment by wojtek-t** [comment]
@liggitt - meta.v1/meta.v1beta1 it seems we can simply autogenerate those.

But do you have a suggestion for the second point? We can do manual-conversion, but that would introduce maintainence cost.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/82490 to address the userinfo conversion issue

**Comment by liggitt** [comment]
@smarterclayton was looking into removing the reflective conversion path entirely in https://github.com/kubernetes/kubernetes/pull/65881... I think that would be good to do to flush out reflective conversions, which we don't want any of

**Comment by wojtek-t** [comment]
Thanks a lot for opening this PR Jordan.

I took a quick glance into the remaining ones and couple examples are:
`v1.DeleteOptions" "v1.DeleteOptions"`
`internalversion.ListOptions" "v1.ListOptions"`
`v1.PodExecOptions" "url.Values"`
`"v1.ListOptions" "url.Values"`

Couple of those are simply missing conversions (so lack of those is expected).

But I don't understand this one yet:
`internalversion.ListOptions" "v1.ListOptions"`
we clearly have a conversion for it and it is registered:
https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/internalversion/zz_generated.conversion.go#L48

**Comment by smarterclayton** [comment]
Internal version list is only in one scheme (meta internal, which we use
sparingly) so maybe it got missed?

I’m trying to move away from meta internal, but it has uses for new api
objects being tested (like Table and PartialObjectMetadata were).


On Sep 9, 2019, at 9:31 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

Thanks a lot for opening this PR Jordan.

I took a quick glance into the remaining ones and couple examples are:
v1.DeleteOptions" "v1.DeleteOptions"
internalversion.ListOptions" "v1.ListOptions"
v1.PodExecOptions" "url.Values"
"v1.ListOptions" "url.Values"

Couple of those are simply missing conversions (so lack of those is
expected).

But I don't understand this one yet:
internalversion.ListOptions" "v1.ListOptions"
we clearly have a conversion for it and it is registered:
https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/internalversion/zz_generated.conversion.go#L48

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/82484?email_source=notifications&email_token=AAI37J2TL3TY4JZV4DIRFMTQIZF4XA5CNFSM4IUZZVH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6HSQ2I#issuecomment-529475689>,
or mute the thread

**Comment by wojtek-t** [comment]
> Internal version list is only in one scheme (meta internal, which we use
sparingly) so maybe it got missed?

> I’m trying to move away from meta internal, but it has uses for new api
objects being tested (like Table and PartialObjectMetadata were).

Re metav1 Types, we seem to be creating a dedicated scheme object:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/register.go#L81
and then ParameterCodec from it (which I guess is what we use)

It seems that we're creating a `separate` ParameterCodec` in internalversion package and only there the conversions are registered...

Did yet have time to look which ParameterCodec we are actually using...

**Comment by wojtek-t** [comment]
Unassigning - until I know I will have time to work on it.

**Comment by wojtek-t** [comment]
@smarterclayton 

> Internal version list is only in one scheme (meta internal, which we use
sparingly) so maybe it got missed?

```
wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ git grep "internalversion.ParameterCodec"
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go:          if err := metainternalversion.ParameterCodec.DecodeParameters(values, scope.MetaGroupVersion, options); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go:                          if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), scope.MetaGroupVersion, options); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go:          if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), scope.MetaGroupVersion, &listOptions); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go:                          if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), scope.MetaGroupVersion, options); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go:                             if err := metainternalversion.ParameterCodec.DecodeParameters(values, scope.MetaGroupVersion, &exports); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go:                             if err := metainternalversion.ParameterCodec.DecodeParameters(values, scope.MetaGroupVersion, &options); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go:             if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), scope.MetaGroupVersion, &opts); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:           if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), scope.MetaGroupVersion, options); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go:          if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), scope.MetaGroupVersion, options); err != nil {
staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go:              if err := metainternalversion.ParameterCodec.DecodeParameters(req.URL.Query(), metav1.SchemeGroupVersion, &opts); err != nil {
```

So `metainternalversion.ParameterCodec` is actually used for parsing options for every single apiserver request.

That said, looking into code, this one should some the conversions registered, e.g. `internalversion.ListOptions" "v1.ListOptions"` so something else may be wrong.

**Comment by wojtek-t** [comment]
OK - I think I got it - it seems AddToScheme() is not called anywhere. I will test it and send out a PR to fix it.

**Comment by wojtek-t** [comment]
Apparently, it will require a non-negligible refactoring to do this.
The problem is that we have init() function in register.go (which is supposed to initialize the scheme local to the metainternalversion package), and we also have init() function in autogenerated conversions file - given that we can't force the order of initialization within a package this is not working.

It seems that we will need to do something similar we do for all other types where:
- in the packages (metav1, metainternalversion) we only register in localSchemeBuilder
- we register in schema in a separate (install/ ?) package (that depends on all versions, thus will be initialized later)

However, that would require making individual "Scheme" object from all those packages public...

@smarterclayton - thoughts?

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/82585 is out for review

**Comment by markyjackson-taulia** [comment]
@wojtek-t  Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 14. Is this issue still intended for 1.17?

**Comment by wojtek-t** [comment]
@markyjackson-taulia - yes, I believe we will have it done in 1.17 - the #84670 should be the second last PR for this

**Comment by markyjackson-taulia** [comment]
@wojtek-t ok to close now?

**Comment by wojtek-t** [comment]
@markyjackson-taulia - let me validate it - I will have an answer for you by Thursday morning if this is all or requires any other changes

**Comment by wojtek-t** [comment]
There is one more question to answer in this case. But I opened a dedicated bug for it:
https://github.com/kubernetes/kubernetes/issues/84976

Closing this one as done now.
