### ISSUE TITLE
Provide a mechanism for custom collectors to use the metrics stability framework

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#82509]
Currently custom prometheus collectors are ingested into metrics stability framework without any stability metadata. We need some mechanism for wrapping custom prometheus collectors so that we can annotate them with stability metadata. 

/sig instrumentation

**Comment by RainbowMango** [comment]
Maybe I can help.
/assign

**Comment by RainbowMango** [comment]
Copy @logicalhan 's [comments](https://github.com/kubernetes/kubernetes/pull/82583#issuecomment-530603913) to here:

We also need to wrap the prometheus.Collector and prometheus.Desc objects. It is slightly more involved because we also want to be able to add stability level annotations to prometheus.Desc but the current mechanism through which this works does not make it a simple change.

A simpler alternative approach is to intercept the prometheus.Desc during instantiation and just immediately set the Desc help text to alpha.

**Comment by RainbowMango** [comment]
> A simpler alternative approach is to intercept the prometheus.Desc during instantiation and just immediately set the Desc help text to alpha.

Do you mean intercept prometheus.Desc during metrics.NewDesc() ?
Indeed, we can add stability level annotations, but we should consider how `Create()` it during registry.

**Comment by RainbowMango** [comment]
@logicalhan 

For this todo
```golang
	// todo: handle defaulting better
	if opts.StabilityLevel == "" {
		opts.StabilityLevel = ALPHA
	}
```
I'd like to provide a method to `type StabilityLevel string`, that will be used in custom collector too.
e.g. 
```golang
func (sl *StabilityLevel) redressLevel() StabilityLevel {
	switch *sl {
	case ALPHA:
	case STABLE:
	default:
		*sl = ALPHA
	}

	return *sl
}
```
How do you feel?  If ok, can you propose a method name? I think it's not good.

By the way please help review the PR #82823.

**Comment by RainbowMango** [comment]
@logicalhan 
I tried a solution that can help to annotate custom metrics with stability metadata.

The custom metrics that I took to my testing as follows:
```golang
	descLogSize = metrics.NewDesc(
		"kubelet_container_log_filesystem_used_bytes",
		"Bytes used by the container's logs on the filesystem.",
		[]string{ "uid","namespace","pod","container",},nil,
		metrics.ALPHA, "1.17.0",
	)

	deprecateddescLogSize = metrics.NewDesc(
		"kubelet_container_log_filesystem_used_bytes_testing_deprecated",
		"Bytes used by the container's logs on the filesystem.",
		[]string{ "uid", "namespace","pod","container",},nil,
		metrics.ALPHA, "1.15.0",
	)
```


I collect metrics on my local cluster by command `curl localhost:10255/metrics`: 
```
# HELP kubelet_container_log_filesystem_used_bytes [ALPHA] (Deprecated since 1.17.0) Bytes used by the container's logs on the filesystem.
# TYPE kubelet_container_log_filesystem_used_bytes gauge
kubelet_container_log_filesystem_used_bytes{container="dnsmasq",namespace="kube-system",pod="kube-dns-68496566b5-zcs7t",uid="33a4b3e0-6a51-4514-8035-2eb68c6c4979"} 24576
kubelet_container_log_filesystem_used_bytes{container="kubedns",namespace="kube-system",pod="kube-dns-68496566b5-zcs7t",uid="33a4b3e0-6a51-4514-8035-2eb68c6c4979"} 24576
kubelet_container_log_filesystem_used_bytes{container="sidecar",namespace="kube-system",pod="kube-dns-68496566b5-zcs7t",uid="33a4b3e0-6a51-4514-8035-2eb68c6c4979"} 24576
```

The point: 
1. The stability metadata be added to HELP; 
2. The hidden metric be ignored automatically; 
3. All directly import prometheus methods be removed;

**Comment by RainbowMango** [comment]
# Solution

## prometheus.Desc to metrics.Desc 
We have to wrap Desc first, named metrics.Desc here. 
The metrics.Desc works very similarly with metrics.lazyMetric. 

metrics.Desc not be initialized until metric registration. We can mark the stability metadata when registration.

to be continue...
