### ISSUE TITLE
Is there any way not to kill container when exceed memory limit，but to stop the process inside the container？

### ISSUE THREAD

**Issue by toyow** [kubernetes/kubernetes#82516]
when ommkill happened，the  third party librar  installed by user  can‘t be recovered。Is there any way to  solve this problem？
community/question

**Comment by tossmilestone** [comment]
@toyow The behavior of OOMKill is killing the container process, not the Pod. And that's exactly what you desire.

**Comment by toyow** [comment]
> @toyow The behavior of OOMKill is killing the container process, not the Pod. And that's exactly what you desire.

Thank you for your reminder
