### ISSUE TITLE
Exit codes for terminated pods 

### ISSUE THREAD

**Issue by ionuthim** [kubernetes/kubernetes#82519]
Hello, 

Can someone inform what means exit code : 3 ? 
Also if somebody know, please explain a little what means every code when the pod is terminated ?  
I've searched on internet what means code :3, but without success . 

Example :
    State:          Running
      Started:      Sun, 08 Sep 2019 21:53:04 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    3
      Started:      Sat, 07 Sep 2019 06:28:37 +0000
      Finished:     Sun, 08 Sep 2019 21:53:03 +0000
    Ready:          True
    Restart Count:  2

Thank you !

**Comment by xiaoanyunfei** [comment]
/sig node
The `Exit Code` is obtained from  docker's `ExitCode` 
Normally it will be the exit status of the process
`docker run -it centos:7  /bin/sh -c 'exit 3' ` can reproduce the same exitcode

https://stackoverflow.com/questions/31297616/what-is-the-authoritative-list-of-docker-run-exit-codes

**Comment by drightchao** [comment]
Hi, we met exactly the same issue on openshift, pod restarts occassionally, with exit code 3

**Comment by MeherHihi** [comment]
/reopen /remove-lifecycle rotten

Hello,

I'm facing the same behaviour on Openshift. My application is deployed on 4 pods and only one pod restarts frequently with exitcode 3.

Example:
lastState:
        terminated:
          exitCode: 3
          reason: Error
          startedAt: '2022-04-06T13:36:33Z'
          finishedAt: '2022-04-06T17:29:42Z'

I'm searching for the meaning of this exitcode. 
And for information, it's not related to limits of CPU or Memory issues.

Thank you,
