### ISSUE TITLE
Remove direct references to prometheus methods

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#82510]
To get metrics stability into Beta, we will make it illegal to directly import prometheus methods in Kubernetes components. This will insure that all new metrics are instantiated using the correct wrapper methods. To do this, we need to provide wrappers for the direct prometheus method calls (namely, prometheus.Bucket methods and prometheus.Collector/Desc methods). 

/sig instrumentation

**Comment by RainbowMango** [comment]
@irajdeep 
I just saw this issue...

We have wrapped Prometheus bucket functionality in https://github.com/kubernetes/kubernetes/pull/82583. 

For Prometheus Collector/Desc functionality, these usually used in custom collector scenario. 
Maybe not simply provide a wrapper but should provide a mechanism to annotate the custom collector with stability metadata.  Actually, I'm working on it.  Refer https://github.com/kubernetes/kubernetes/issues/82509 

Welcome to provide ideas about it, we can work together.
