### ISSUE TITLE
Pods are not restarted when changing the init container's image

### ISSUE THREAD

**Issue by sofat1989** [kubernetes/kubernetes#82523]
From the doc here, https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons
```
A user updates the Pod specification, causing the init container image to change. Any changes to the init container image restarts the Pod. App container image changes only restart the app container.
```
I updated the init container image, we didnt get any changes for these pods.
init containers are not re-executed. 

From the logic of `computePodActions` here, it does not calculate the hash change for the init container.

```
// Check initialization progress.
	initLastStatus, next, done := findNextInitContainerToRun(pod, podStatus)
	if !done {
		if next != nil {
			initFailed := initLastStatus != nil && isInitContainerFailed(initLastStatus)
			if initFailed && !shouldRestartOnFailure(pod) {
				changes.KillPod = true
			} else {
				// Always try to stop containers in unknown state first.
				if initLastStatus != nil && initLastStatus.State == kubecontainer.ContainerStateUnknown {
					changes.ContainersToKill[initLastStatus.ID] = containerToKillInfo{
						name:      next.Name,
						container: next,
						message: fmt.Sprintf("Init container is in %q state, try killing it before restart",
							initLastStatus.State),
					}
				}
				changes.NextInitContainerToStart = next
			}
		}
		// Initialization failed or still in progress. Skip inspecting non-init
		// containers.
		return changes
	}
```
/sig node

**Comment by krmayankk** [comment]
@sofat1989 did you test this with deployment or statefulset or with a plain pod yaml ?

**Comment by sofat1989** [comment]
@krmayankk I tested this using a plain pod yaml. I have some use cases that we dont want to re-create the pods and just want to update the pods' yaml

**Comment by iy116** [comment]
Not sure if I'm misunderstanding this, but does this issue mean that changing the image name does not restart the pod? Because it works for me.

**Comment by underflow00** [comment]
Not sure if I'm misunderstanding this, but does this issue mean that changing the image _name_ of the init container does not restart the pod? Because it works for me?
