### ISSUE TITLE
Procedure for tenants to collect core dumps of failing containers

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#82530]
**What would you like to be added**:

An automated, straightforward procedure for cluster tenants to collect core dumps of failing containers.

**Why is this needed**:

So that segmentation faults can be diagnosed at scale without exposing unnecessary privileges to k8ts tenants.

**Comment by mcandre** [comment]
@kubernetes/feature-requests

**Comment by mcandre** [comment]
You are a stupid bot.

**Comment by neolit123** [comment]
/sig node auth
please try to provide more detail in the issue description.
to get attention on this topic try posting a message in the k8s slack channel: #wg-multitenancy
