### ISSUE TITLE
PodSpec - new priorityClassName test

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/kubernetes#82545]
Umbrella issue: #82312

/area conformance
/sig testing

**Comment by BobyMCbobs** [comment]
[Create PR #82546](https://github.com/kubernetes/kubernetes/pull/82546)

**Comment by BobyMCbobs** [comment]
The goal of this test is to ensure that PriorityClasses via their PriorityClassNames function as expected.

The test should:
1. prepare Pods to be created, with Replicas, a pre-defined PriorityClassName, and fake CPU limitation
2. Create Pods with a lower PriorityClassName, leaving the higher ones
3. Create Pods with a higher PriorityClassName, ensure that lower Pods adjust their Replica amount

**Comment by hh** [comment]
/close
This was the older workflow based on increasing PodSpec field coverage .
