### ISSUE TITLE
Promote VolumeSubpathEnvExpansion to GA

### ISSUE THREAD

**Issue by kevtaylor** [kubernetes/kubernetes#82577]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind api-change
/sig storage
/sig node
/milestone v1.17

**Description:**
This is the issue that is used to upgrade VolumeSubpathEnvExpansion feature gate to GA.

Related Issues:
Beta Upgrade: https://github.com/kubernetes/kubernetes/pull/76546
Feature Request: https://github.com/kubernetes/features/issues/559
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20181029-volume-subpath-env-expansion.md

**Comment by neolit123** [comment]
please update https://github.com/kubernetes/enhancements/issues/559 with the GA target.

**Comment by msau42** [comment]
Should we also consider adding the e2e tests to the conformance suite (as a separate pr)? cc @kubernetes/cncf-conformance-wg

**Comment by kevtaylor** [comment]
@msau42 Do you want me to put in a PR to switch the e2e tests to conformance level?
If so, just need some advice on that - seems like to just change `It` to `ConformanceIt` ?
Do we then need to leave the `[sig-storage]` tags - or remove them?
Any other additional tags that we need?

**Comment by johnbelamaric** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md

Please do that ASAP if you want it to make the release!

**Comment by johnbelamaric** [comment]
You can leave the sig-storage tags

**Comment by msau42** [comment]
sgtm!

**Comment by kevtaylor** [comment]
This has been released now, so closing
