### ISSUE TITLE
Cut off connections from kube-aggregator to aggregated apiserver lead to panic in the logs

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#82591]
The kube-aggregator uses Golang's reverse proxy code to forward requests to aggregated API server. Whenever such a connection is uncleanly closed, the Golang code panics. The panic is passed through the handler chain down to the panic handler which prints it.

This leads to main panic stack traces in the kube-apiserver logs whenever an aggregated API server terminates, because every long-running connection (e.g. watches) is uncleanly closed leading to that panic.

This applies to 1.16.

**Comment by liggitt** [comment]
/priority critical-urgent

given this is a regression in 1.16 and spams the log badly, making it difficult to see actual errors

**Comment by lachie83** [comment]
@sttts @liggitt as I'm sure you are both already aware that the 1.16.0 cherry-pick deadline is EoD tomorrow. Do you expect to have a PR and associate cherry-pick PR ready to merge in that time frame?

**Comment by liggitt** [comment]
> Do you expect to have a PR and associate cherry-pick PR ready to merge in that time frame?

PRs are open/green/approved for master (https://github.com/kubernetes/kubernetes/pull/82588) and 1.16 (https://github.com/kubernetes/kubernetes/pull/82593) branches
