### ISSUE TITLE
can not get the statefulset rollout history details

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#82612]
with kubernetes v1.14.0, it can not get the statefulset revision details via `kubectl` command line:

```
hchenxa@hchenxadembp:~/Documents/hchenxa/src/ICP/icp-sert-bats$ kubectl rollout history sts/test-sts -n sert-workns --revision=2
statefulset.apps/test-sts with revision #2
REVISION
0
0
1
2
```

looks like the command can get the deployment resources revision info and shows result contain the image name, labels and other information.

**Comment by hchenxa** [comment]
just want to know if we can have the simliar info like deployment revision details:
```
hchenxa@hchenxadembp:~/Documents/hchenxa/src/ICP/icp-sert-bats$ kubectl rollout history deployment/nginx -n sert-workns --revision=3
deployment.extensions/nginx with revision #3
Pod Template:
  Labels:	pod-template-hash=7fb446998b
	run=nginx
  Containers:
   nginx:
    Image:	nginx:1.14.2-alpine
    Port:	80/TCP
    Host Port:	0/TCP
    Environment:	<none>
    Mounts:	<none>
  Volumes:	<none>
```

**Comment by dineshba** [comment]
I would love to work on this. Can i work on this ?

**Comment by hchenxa** [comment]
and @dineshba already have PR and waiting for review.

**Comment by eddiezane** [comment]
Closed via https://github.com/kubernetes/kubernetes/pull/86506

/close
