### ISSUE TITLE
rkt: Better intergration

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#8262]
This issue tracks the some of the TODOs to make using rkt in k8s have better experience.
- [x] Add a README.md or doc.go in rkt package (update: README can be found [here](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/rkt) now)
- [x] Integrate the reference manager, readiness manager.
- [x] Per container logs
- [ ] Stdin and TTY (https://github.com/GoogleCloudPlatform/kubernetes/pull/12168)
- [x] Integrate with the cAdvisor.
- [x] More message and reasons for events like pull failures.
- [x] Image GC (https://github.com/kubernetes/kubernetes/pull/14686)
- [x] Enforce container/image gc policy.
- [ ] Run ACI, integrate `rkt trust`.
- [x] Being able to change stage1 image.
- [x] e2e tests.
- [x] Network plugins. Join existing network?
- [ ] Per container lifecycle hooks
- [ ] Replace cli calls with [rkt API](https://github.com/coreos/rkt/pull/1411)
- [x] security context

/cc @dchen1107 @vmarmol @yujuhong @jonboulle @bakins

**Comment by kamalmarhubi** [comment]
Should the "Stdin and TTY" item be checked off now that #12168 has been merged? Is the rest of the status up to date? I'm quite interested in using rkt over Docker and might be willing to do some work here.

**Comment by yifan-gu** [comment]
@kamalmarhubi No jobs have been done for the Stdin & TTY yet, helps welcome :)
The image gc also should be easier than the others. 
Enabling as many e2e tests as possible for rkt might be a little painful...

Besides, we are currently design/develop APIs for rkt, which should save us many effort maintaining all these in long term.

**Comment by kamalmarhubi** [comment]
@yifan-gu when you saw developing APIs, do you mean as a Go library, or something akin to the Docker daemon with, eg, an HTTP interface?

**Comment by yifan-gu** [comment]
@kamalmarhubi No restful API at this time, we are going to use grpc. It should be easy to generate client bindings, and maybe we will do a more "docker client like" wrapper over the binding.

**Comment by kamalmarhubi** [comment]
That makes sense. Does this mean there will be a new daemon to go along side the metadata service?

**Comment by yifan-gu** [comment]
@kamalmarhubi Yes. but it's also optional, you don't require it to run rkt. It just provides easy access to the pod/image information.
That means it should run in non-root, and it's failover should not affect running pods.

**Comment by kamalmarhubi** [comment]
@yifan-gu ah so it's not used for starting pods?

**Comment by yifan-gu** [comment]
@kamalmarhubi No.

**Comment by yifan-gu** [comment]
@kamalmarhubi FYI, here's the PR for the API interface https://github.com/coreos/rkt/pull/1359

**Comment by kamalmarhubi** [comment]
Awesome thanks!

**Comment by yifan-gu** [comment]
Run e2e tests on local:
```
Ran 109 of 185 Specs in 7246.865 seconds
FAIL! -- 60 Passed | 49 Failed | 2 Pending | 74 Skipped --- FAIL: TestE2E (7246.87s)
FAIL
```
Detailed logs are here:
https://gist.github.com/yifan-gu/da1d30bf077d99cfa71f

**Comment by yifan-gu** [comment]
Trying to setup gce env for e2e tests next.

**Comment by yujuhong** [comment]
I've never run e2e in a non-gce environment, and I wouldn't be surprised if a lot of them fail. Yes, setting up a gce cluster would definitely help.

**Comment by yifan-gu** [comment]
e2e result for gce/cores with docker:
```
Summarizing 3 Failures:

[Fail] Services [It] should serve identically named services in different namespaces on different load-balancers 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:829

[Fail] ServiceLoadBalancer [It] should support simple GET on Ingress ips 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/serviceloadbalancers.go:271

[Fail] Monitoring [It] should verify monitoring pods and all cluster nodes are available on influxdb using heapster. 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:236

Ran 140 of 187 Specs in 14110.233 seconds
FAIL! -- 137 Passed | 3 Failed | 2 Pending | 45 Skipped --- FAIL: TestE2E (14110.91s)
FAIL

Ginkgo ran 1 suite in 3h55m10.961690619s
Test Suite Failed
```

**Comment by ppalucki** [comment]
there a additional rather minor issues, I found related to rkt driver:
- [ ] cannot start new pod with "runonce"
- [ ] better error handling eg. "ppid file not found" message for not-defined but required volume scenario
- [ ] "container runtime" (describe node) always says "docker" regardless `--container-runtime`
- [ ] (feature) rkt support for /cluster/* deployment scripts (we have that for libvirt)
- [ ] rkt with kvm engine support: kubelet logs/exec, gc 

some of them are under our investigation 

@yifan-gu: my question is, are you aware some of those ? are you working on some of them ? we can/will help you with some of them, but want to make sure, that we done overalp

**Comment by yifan-gu** [comment]
@ppalucki I am setting gce e2e test environments for rkt/k8s, so will get to these later, but feel free to take them, thanks :)

**Comment by woodbor** [comment]
@yifan-gu : Can you tell, what's the current status of `e2e tests` with rkt, or is there any PR related with it ? I see only https://github.com/kubernetes/kubernetes/issues/7205

**Comment by yifan-gu** [comment]
@woodbor  Here is the brief result 
FAIL! -- 65 Passed | 103 Failed | 0 Pending | 69 Skipped
Run last week
logs here: https://gist.github.com/yifan-gu/f970a0b3748543ee919f

FAIL! -- 109 Passed | 59 Failed | 0 Pending | 69 Skipped
Run yesterday with a hacked rkt that supports hostname /etc/hosts
logs here: https://gist.github.com/yifan-gu/51e29ef92428e4272d04

We are tracking more status in this google doc https://docs.google.com/document/d/1otDQ2LSubtBUaDfdM8ZcSdWkqRHup4Hqt1VX1jSxh6A/edit#

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
