### ISSUE TITLE
Update to etcd 3.4 in Kubernetes 1.17 release

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#82641]
follow the same pattern that we updated to 3.3.15:
- client side changes needs to be vendored in (similar to https://github.com/kubernetes/kubernetes/pull/81434)
- update default etcd server (similar to https://github.com/kubernetes/kubernetes/pull/82199)

**Comment by alejandrox1** [comment]
random question: how are these things updated? How are PRs such as https://github.com/kubernetes/kubernetes/pull/83209 generated?

**Comment by wenjiaswe** [comment]
@alejandrox1 I am following [Adding or updating a dependency](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#adding-or-updating-a-dependency) to update etcd.

**Comment by jingyih** [comment]
Sounds good. I will work on updating default etcd server to 3.4.3.

/assign
