### ISSUE TITLE
Injecting Additional Container to a Running POD

### ISSUE THREAD

**Issue by Sisir-Chowdhury** [kubernetes/kubernetes#82668]
**What would you like to be added**:

Ability to inject additional Container to a running K8s POD

**Why is this needed**:
This is needed to define/monitor certain aspects of the running POD which can be turned on/off on demand basis.

**Comment by Joseph-Irving** [comment]
/sig node
This sounds a lot like https://github.com/kubernetes/enhancements/issues/277, which should be going alpha in kube 1.17

**Comment by Sisir-Chowdhury** [comment]
Thanks @Joseph-Irving  . This feature is needed (through K8s API) to inject additional Containers on a running POD.

**Comment by tedyu** [comment]
@Sisir-Chowdhury 
Is there additional requirement for the container (to be injected) which is beyond ephemeral container ?

thanks

**Comment by Sisir-Chowdhury** [comment]
@tedyu  Requirement is something like this - An istio cluster is up and running where each POD has 2 Containers - App and Envoy Containers. We'd like to inject another container(Ubuntu) in each of those PODs through K8s REST APIs (ex: kubectl utility).

**Comment by markzhang0928** [comment]
> @tedyu Requirement is something like this - An istio cluster is up and running where each POD has 2 Containers - App and Envoy Containers. We'd like to inject another container(Ubuntu) in each of those PODs through K8s REST APIs (ex: kubectl utility).

I suppose that it's still not clear why you need an additional container running in the same pod?

**Comment by YangKeao** [comment]
@markzhang0928 I need to set up a container with `NET_ADMIN`. However, ephemeral container doesn't provide configurable security context. 

Maybe in most case `SYS_ADMIN` and `SYS_PTRACE` is enough for debugging, but in some situation when I want to debug with tc netem, I need the help with `NET_ADMIN`. (Sorry for complaining about this in comment area of many issues.)

**Comment by markzhang0928** [comment]
> @markzhang0928 I need to set up a container with `NET_ADMIN`. However, ephemeral container doesn't provide configurable security context.
> 
> Maybe in most case `SYS_ADMIN` and `SYS_PTRACE` is enough for debugging, but in some situation when I want to debug with tc netem, I need the help with `NET_ADMIN`. (Sorry for complaining about this in comment area of many issues.)

The enhancement of this KEP is still in alpha feature, so it will be satisfied when it's in Beta I suppose.
