### ISSUE TITLE
gcepersitentdisk empty after rc deletion then creation

### ISSUE THREAD

**Issue by bnprss** [kubernetes/kubernetes#8267]
Hi, 

I've got an annoying issue where gcepersitentdisk volumes are empty after rc is being delete/created. 
I've got that issue on 0.16.1, on coreos 633.1, reproducible? always!

Tomorrow I'll update to 0.17 and post back if I've got similar issue.

**Comment by lavalamp** [comment]
@mbforbes 

xref/ #6084

**Comment by brendandburns** [comment]
I'm closing this as obsolete, there have been countless bugs fixed between this issue and present.
