### ISSUE TITLE
Regression in Kubelet Status Calls

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#82671]
**What happened**:
In 1.16 CI testing we came across integration tests failing on liveness and readiness probes with payloads of 50KB (the max is 10KB).

```
  Warning  Unhealthy  94s (x9 over 2m54s)   kubelet, [snip].ec2.internal  Liveness probe errored: the read limit is reached
  Warning  Unhealthy  86s (x12 over 3m16s)  kubelet, [snip].ec2.internal  Readiness probe errored: the read limit is reached
```

**What you expected to happen**:
We would expect Readiness and Liveness probes to not fail on payloads over 10KB.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.beta2
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
RHCOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
fixed in #82669 / #82688

/close
