### ISSUE TITLE
[Failing Test] ci-kubernetes-e2e-gce-scale-correctness 

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#82695]
**Which jobs are failing**: ci-kubernetes-e2e-gce-scale-correctness

**Which test(s) are failing**: [sig-network] Loadbalancing: L7 [Slow] Nginx should conform to Ingress spec

**Since when has it been failing**: Sep 12, 2019

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness

**Reason for failure**: https://github.com/kubernetes/kubernetes/pull/82416 fixed it in private clusters, but unfortunately broke in very large clusters

**Anything else we need to know**:
We need to figure out if increase the timeout for nginx load balancer can fix this. If not, then we'll most likely need to rollback https://github.com/kubernetes/kubernetes/pull/82416

**Comment by alejandrox1** [comment]
/milestone v1.17
(labeling critical urgent as this is something that is being currently worked on)
/priority critical-urgent

**Comment by mm4tt** [comment]
Yeah, I'm working on that. Have a pending PR that should fix the problem, but need to verify it first.

**Comment by jkaniuk** [comment]
PR fixed the issue:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness
two tests green, the last one failed for different reason

Could be closed

**Comment by alenkacz** [comment]
I see the last failure at 19.9. so marking this as resolved. Thanks @jkaniuk
