### ISSUE TITLE
kubectl kustomize gives random result

### ISSUE THREAD

**Issue by lboclboc** [kubernetes/kubernetes#82706]
**What happened**:
When I run kubectl kustomize <dire> the result is different between runs. I have the problem right now with services. The base service.yaml has no node-ports assigned but the overlay "development" does. When I run kubectl kustomize development I sometimes get the nodeports added, sometimes not. 

**What you expected to happen**:
Same result each time.

**How to reproduce it (as minimally and precisely as possible)**:
I will attached my yaml:s. To reproduce just run kubectl kustomize development
multiple times.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Private
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04
- Kernel (e.g. `uname -a`):
Linux tooextlb-laptop 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Installed kubernetes from http://apt.kubernetes.io/

- Network plugin and version (if this is a network-related bug):

- Others:

**Comment by liggitt** [comment]
cc @monopole

**Comment by lboclboc** [comment]
[files.zip](https://github.com/kubernetes/kubernetes/files/3610710/files.zip)

**Comment by lboclboc** [comment]
Sample from running multiple times:
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kc kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kc kustomize development|grep 30
    nodePort: 30911
    nodePort: 30913
    nodePort: 30915
    nodePort: 30917
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kc kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kc kustomize development|grep 30
    nodePort: 30911
    nodePort: 30913
    nodePort: 30915
    nodePort: 30917
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kc kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kubectl kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kubectl kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kubectl kustomize development|grep 30
    nodePort: 30911
    nodePort: 30913
    nodePort: 30915
    nodePort: 30917
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kubectl kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kubectl kustomize development|grep 30
          value: "300"
labe@tooextlb-laptop:~/git/kubernetes/deployments/elasticsearch$ kubectl kustomize development|grep 30
    nodePort: 30911
    nodePort: 30913
    nodePort: 30915
    nodePort: 30917
          value: "300"

**Comment by ZP-AlwaysWin** [comment]
kubectl kustomize development|grep 30 is a new commond?

```
# kubectl kustomize development|grep 30
Error: unknown command "kustomize" for "kubectl"
Run 'kubectl --help' for usage.
unknown command "kustomize" for "kubectl"



# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lboclboc** [comment]
> kubectl kustomize development|grep 30 is a new commond?
> 
> ```
> # kubectl kustomize development|grep 30
> Error: unknown command "kustomize" for "kubectl"
> Run 'kubectl --help' for usage.
> unknown command "kustomize" for "kubectl"
> 
> 
> 
> # kubectl version
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
> ```

I think it was integrated with kubectl in version 1.14. Earlier it was a standalone command.

**Comment by lboclboc** [comment]
Sorry, my fault. Syntax error in the kustomization.yaml, used resource instead of patchesStrategicMerge.
