### ISSUE TITLE
[migration] Translate predicates/priorities config to Plugin configuration

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#82708]
**What would you like to be added**:
A way to configure future default plugins, and translation between [Predicate/Priority Policy](https://github.com/kubernetes/kubernetes/blob/926bd4ddbbee7afbb52e15afd890fccb6e1e69cf/pkg/scheduler/api/types.go#L49-L57) and [component config Plugins](https://github.com/kubernetes/kubernetes/blob/926bd4ddbbee7afbb52e15afd890fccb6e1e69cf/pkg/scheduler/apis/config/types.go#L91-L100).

**Why this is needed**:
Two reasons:
1) Facilitate incremental migration of predicates/priorities to framework Plugins. The goal is to create a mapping for default predicates/priorities to corresponding Filter/Score plugins.
2) Even after we have all predicates/priorities implemented as Filters, this translation layer is necessary to maintain compatibility with the old v1 Policy API, which we can't start deprecating until the scheduler's Component Config is GA.

This is also discussed under [backward compatibility](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#backward-compatibility) in the framework's KEP.

/sig scheduling
/assign

**Comment by ahg-g** [comment]
This is to facilitate incremental migration of predicates/priorities to framework Plugins. The goal is to create a mapping for default predicates/priorities to corresponding Filter/Score plugins.

**Comment by Huang-Wei** [comment]
Maintaining the relationship using an internal map can make the migration progress smoothly. Thanks.

**Comment by Huang-Wei** [comment]
BTW: it'd be good to _explicitly_ list all related PRs as bullets in the description section (e.g., #82896 and further ones)

**Comment by ahg-g** [comment]
/close 

This is done.
