### ISSUE TITLE
Migrate Predicates to plugins

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#82715]
**What would you like to be added**:

Write equivalent Plugins for all currently supported priorities and predicates. Those plugins should only call the existing predicates/priorities logic

/sig scheduling
/assign

**Comment by Huang-Wei** [comment]
Hold on...

Let's [discuss first](https://docs.google.com/document/d/1P1eBaePxuko22B8LLOrPEonoj1awc1dCVBDefuRWUA4/edit#heading=h.u7jfy9wqpd2b) before heading into implementation. And I think @ahg-g will make detailed a roll-out plan and timeline.

**Comment by draveness** [comment]
> Hold on...
> 
> Let's [discuss first](https://docs.google.com/document/d/1P1eBaePxuko22B8LLOrPEonoj1awc1dCVBDefuRWUA4/edit#heading=h.u7jfy9wqpd2b) before heading into implementation. And I think @ahg-g will make detailed a roll-out plan and timeline.

Sure, I started this as a test to find what we else we need to do except what listed in the document.
