### ISSUE TITLE
SecretTypeServiceAccountToken -> SecretTypeAccountToken

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#8271]
A comment of mine did not get resolved before merging the service accounts: https://github.com/GoogleCloudPlatform/kubernetes/pull/7101/files#r30173041

Basically, all mentions of "ServiceAccount" in the secret type tokens need to be replaced with a more general user account. ServiceAccounts may not be the only source of such secrets.

Service account manager can add an annotation or something to track which secrets it "owns".

**Comment by lavalamp** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
Are there going to be non-ServiceAccount auth token secrets? Why wouldn't they have the same format?

Are the ServiceAccount name and UID really needed as part of the secret data? That seems like a backdoor downward API. How about a created-by annotation similar to that produced by ReplicationController?
https://github.com/GoogleCloudPlatform/kubernetes/blob/0da12c1ba96b6b6deb5ef168487a3caf112fb392/pkg/controller/controller_utils.go#L206

How does the ServiceAccount controller filter secrets for just the ones it should manage? Do we imagine other secrets being managed by other components? What does "management" entail? Just deletion? That sounds like the existence dependence proposed here: https://github.com/GoogleCloudPlatform/kubernetes/issues/1535#issuecomment-91413501

cc @liggitt @smarterclayton

**Comment by bgrant0607** [comment]
Ref #8190

**Comment by bgrant0607** [comment]
This is not worth fixing
