### ISSUE TITLE
Environment variables support - kubectl create secret --from-literal

### ISSUE THREAD

**Issue by ajinkya599** [kubernetes/kubernetes#82724]
@kubernetes/sig-cli-feature-requests

**What would you like to be added**:
Support for passing environment variables in `create secret` command:

`kubectl create secret generic mysecret --from-literal=username=sudouser --from-literal=password=$sudopass`

or maybe something like `password=(-env sudopass)`

**`sudopass`** above being an environment variable.
`kubectl` can substitute the correct value of `sudopass`.

**Why is this needed**:
This will be handy in automated deployments. The user can define the secrets as environment variables (configured in pipeline) and pass it down to kubectl.

This way the logs can stay clean (no secrets exposed in logs).

/sig cli

**Comment by dfang** [comment]
do we really need  env substitution in kubectl command ?  it seems only `kubectl create secret` needs this env substitution.

i prefer this syntax over the second one.

`kubectl create secret generic mysecret --from-literal=username=sudouser --from-literal=password=$sudopass`.

maybe we can take it further like [this](https://github.com/a8m/envsubst).

**Comment by RickyRajinder** [comment]
I can work on this if this is something worth pursuing.

**Comment by ajinkya599** [comment]
> 
> 
> do we really need env substitution in kubectl command ? it seems only `kubectl create secret` needs this env substitution.
> 
There could be other such cases as well (especially in case of automation), where the kubectl command is not invoked from a shell that supports environment substitution, but invoked as a process.

For instance, take `get deployment` (In my automation, I want to verify the deployment):
`kubectl get deployment $deploymentname -o yaml`

I would also love to contribute.

**Comment by RickyRajinder** [comment]
@ajinkya599 Kubernetes uses [github.com/spf13/cobra](https://github.com/spf13/cobra) to create commands; I think this would be a better issue for that project.
