### ISSUE TITLE
CronJob reports active job even when that job was deleted

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#82753]
**This is not a _duplicate_ of #37957, but rather a "the problem seems to have re-appeared."**

**What happened**:

I have a weekly cronjob that last week failed in a way that made me delete the spawned job. The specific failure was caused by a bug in our code, and as such is not a problem for Kubernetes. This week I noticed that the cronjob did not trigger at the expected time, and when looking at it with `kubectl describe` I notice that the cronjob still has a reference to the job in "Active Jobs" list. I checked again, and that job name does not exist in the server.

**What you expected to happen**:

Deleting the job last week kills the pod (did that), *and* makes the cronjob in some way inactive and ready for the next run. IOW: I'm ok with the job having failed this time, and would simply want it to start again next time.

**How to reproduce it (as minimally and precisely as possible)**:

Unknown, but from what I see:
1. create a cronjob and let it trigger
2. delete the job while it is running
3. check that the cronjob recognizes that the job was deleted, and that it is not active

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
   ~~~~
   Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-22T06:44:59Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
   ~~~~
- Cloud provider or hardware configuration: AWS hosted EKS
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2 (unmodified images for EKS)
- Kernel (e.g. `uname -a`): (unknown)
- Install tools: AWS CLI/CloudFormation
- Network plugin and version (if this is a network-related bug): -
- Others: -

**Comment by ankon** [comment]
Rough guess: @kubernetes/sig-apps-bugs

**Comment by nikicat** [comment]
We experience this too.

**Comment by ankon** [comment]
Is there anything I can do to help with analysis?

**Comment by ankon** [comment]
@fejta-bot: Issue is blocked on the k8s side, waiting for reply/feedback. :)

**Comment by ankon** [comment]
@fejta-bot: Meh!
