### ISSUE TITLE
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver

### ISSUE THREAD

**Issue by sharathmankala** [kubernetes/kubernetes#82756]
Hi Team,
I am new to k8s.
i am installed k8s cluster successfully and i am able to access k8s Dashboard.
But i am unable to access other apps from outside.
i am getting below error.
Kindly suggest me.

```
root@k8s-master:~# kubectl get svc --all-namespaces
NAMESPACE              NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default                kubernetes                  ClusterIP   10.96.0.1       <none>        443/TCP                  4d9h
default                nginx                       NodePort    10.99.240.41    <none>        80:31886/TCP             7h1m
kube-system            calico-etcd                 ClusterIP   10.96.232.136   <none>        6666/TCP                 3d10h
kube-system            kube-dns                    ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   4d9h
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.107.90.107   <none>        8000/TCP                 4d9h
kubernetes-dashboard   kubernetes-dashboard        NodePort    10.100.20.227   <none>        443:31074/TCP            4d9h
root@k8s-master:~# telnet 172.105.41.155 31074
Trying 172.105.41.155...
Connected to 172.105.41.155.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
root@k8s-master:~# telnet 172.105.41.155 31886
Trying 172.105.41.155...
telnet: Unable to connect to remote host: No route to host
root@k8s-master:~#
```

 

Sep 16 14:30:57 k8s-master kubelet[1896]: E0916 14:30:57.426517    1896 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.105.35.5 172.105.36.5 172.105.37.5
Sep 16 14:31:25 k8s-master kubelet[1896]: E0916 14:31:25.426298    1896 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.105.35.5 172.105.36.5 172.105.37.5
Sep 16 14:31:32 k8s-master kubelet[1896]: E0916 14:31:32.426270    1896 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.105.35.5 172.105.36.5 172.105.37.5
Sep 16 14:31:56 k8s-master kubelet[1896]: E0916 14:31:56.426208    1896 dns.go:130] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 172.105.35.5 172.105.36.5 172.105.37.5

**Comment by cameronbraid** [comment]
I've hit the same issue, did you find the cause ?

An event on the `kube-controller-manager-node03`

```
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 4.2.2.1 4.2.2.2 208.67.220.220
```

**Comment by ArPharazon** [comment]
sigh

**Comment by caboteria** [comment]
For posterity's sake (because this issue is both unhelpful and a top search result) this reddit thread has some relevant info: https://www.reddit.com/r/kubernetes/comments/7ruq0f/kubelet_nameserver_limits_were_exceeded/

**Comment by XtremeOwnageDotCom** [comment]
> For posterity's sake (because this issue is both unhelpful and a top search result) this reddit thread has some relevant info: https://www.reddit.com/r/kubernetes/comments/7ruq0f/kubelet_nameserver_limits_were_exceeded/

Thanks!

(The bots on this repo are worthless. Couldn't say how many issues I have googled, just to run into an issue closed by a bot)

**Comment by caboteria** [comment]
Silly human! How dare you question the decisions of our robot overlords!

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/blob/dbbce2aaba2501d2409e1829be1637a976990e3b/pkg/apis/core/validation/validation.go#L3489-L3493

**Comment by Routhinator** [comment]
I don't use reddit, which is why I'm here on github.

I'm getting this and I have 1 nameserver line : for systemd-resolved:

```
nameserver 127.0.0.53

```

How are we supposed to deal with this when systemd  controls it's resolver list? This seems like an odd situation to be in.

**Comment by Routhinator** [comment]
Looked at my pods and realized that this Kubernetes shooting itself in the foot and there looks to be little I can do about the neverending spam of warnings from this.

My nodes get their DNS from DHCP and there are 2 DNS servers. I have dual stack IPv4 and IPv6 - and each DNS server has an IP for each IP version. So 2 servers * 2 protocols = 4 entries.

Kubernetes should handle this a little more gracefully.

**Comment by jpetazzo** [comment]
I stumbled upon this and did some research.

Short version: the warning message is totally harmless, and you can ignore it.

Longer version: details in [this blog post](http://jpetazzo.github.io/2024/05/12/understanding-kubernetes-dns-hostnetwork-dnspolicy-dnsconfigforming/).

**Comment by rptaylor** [comment]
The condition itself may be harmless but the warning message is not - it pollutes the logs and generates a lot of spam events which clutter up etcd and contribute to unnecessary IOPS and latency, especially for very large clusters. Given that there is not an easy way to limit the number of DNS servers detected by DHCP and managed by NetworkManager, is there any way to disable the warning message so it stops making useless noise?

**Comment by jpetazzo** [comment]
@rptaylor there is no *generic* solution, but one thing you could do is generate a specific resolv.conf file for k8s (e.g. /etc/resolv-k8s.conf) and then reconfigure kubelet to use that.

*How* to do it exactly varies a lot depending on your k8s distro; in my case, with Hetzner, I'm using k3s and I didn't want to meddle too much with it so I accepted the extra error messages.

However I'm working on another set of clusters based on Flatcar running on Proxmox, and my plan there is to automatically create the file at boot time, and *perhaps* use an extra systemd timer to regenerate it (I don't expect the DNS servers to change *ever* in that environment, but you never know!). I haven't looked yet into the exact details to reconfigure kubelet in a "nice" way on Flatcar but I'm confident that it shouldn't be too tricky (...famous last words 😅)

**Comment by rptaylor** [comment]
@jpetazzo  Yes but there is not always a good way to create a different resolv.conf.  We need to use the DNS servers provided by DHCP in each cloud tenant, and the IP addresses are different in each cloud tenant/cluster. All 4 DNS servers provided are correct and useable; it's best to have all 4 for redundancy (for applications not affected by the libc resolver issue).

I guess one could e.g. write a bash script that automatically truncates the lines with /usr/bin/cut and copies the file, running as a cron job on each node so it will pick up changes that may be propagated by DHCP, but this is really too much of a hack, and would introduce a risk of breakage. Kubernetes is the only application that produces these noisy complaints so it would be nice to address it in kubernetes.

**Comment by jpetazzo** [comment]
@rptaylor I hear you! But keep in mind that both glibc and musl will use up to 3 nameservers maximum. If you have more, they'll be silently dropped anyway. I totally see where you're coming from (I'm in the exact same place!) but if you have 4 servers and want redundancy, your only solution is to go through systemd-resolved (which, I believe, will be happy to have more than 3 resolvers and try them all); but now we're talking about a completely different issues (specifically: how to piggyback CoreDNS to systemd-resolved stub resolver!) 😉

Note that if all resolvers come from the same source (e.g. DHCP) it's relatively straightforward to patch DHCP client scripts to truncated the list. In my specific case however, that doesn't work, since some servers come from DHCP and others from cloud-init; so the complexity escalates quite a bit, alas.

**Comment by rptaylor** [comment]
> they'll be silently dropped anyway

Fine with me, emphasis on silently!  ;)

What is the straightforward patch for DHCP client scripts that could workaround this problem? Can this be done on Almalinux 8 / 9 ?

Using > 3 servers for redundancy isn't really a significant concern anyway, 3 or 4 or whatever should be enough. Anyway I opened https://github.com/kubernetes/kubernetes/issues/126585  and as I mentioned there the main point is that the noise produced by these warnings is worse than the actual condition that they are warning about.

**Comment by jpetazzo** [comment]
I'm not familiar with Almalinux, so I booted an Almalinux 9 VM; apparently it's using NetworkManager and its embedded DHCP client. Short of installing an external DHCP client (e.g. dhclient) and patching its script, here is what you can do:

List the connections that you have:
```
nmcli con show
```
On my VM, there is one named "System eth0".

Check the DNS parameters:
```
nmcli con show "System 0" | grep dns
```
Now you have a few possibilities here, depending on what you see.

If you see hard-coded DNS servers (which will typically be the case when network provisioning is done through cloud-init), you can keep just the first one, for instance like this:
```
DNS=$(nmcli --terse con show "System eth0" | grep ^ipv6.dns: | cut -d: -f2- | cut -d, -f1)
nmcli con modify "System eth0" ipv6.dns $DNS
nmcli device reapply eth0
```
The changes are persistent (you don't need to repeat them at each boot). If cloud-init overwrites them you can run the command again.

Now, if DHCP is used for both IPv4 and IPv6, you could either disable the DNS servers obtained through one of the protocols; or, if you don't like that, you could trim the DNS list on one or both protocols by getting the DNS server address, and then set it to be hardcoded:
```
DNS=$(nmcli --terse con show "System eth0" | grep ^IP4.DNS | head -n1 | cut -d: -f2)
nmcli con modify "System eth0" ipv4.ignore-auto-dns yes
nmcli con modify "System eth0" ipv4.dns $DNS
nmcli device reapply eth0
```

I hope this helps!

**Comment by rptaylor** [comment]
Thanks for looking into it! Right, I suppose a bash script like that could run to statically set DNS servers based on what DHCP provided at the time, but then another ongoing cron hack would be needed to update the static DNS definition whenever there is a potential DHCP update. I think this highlights the need for a clean solution in k8s (or e.g. NetworkManager).

**Comment by PAStheLoD** [comment]
Hello,

for anyone wondering how to make this warning go away with systemd-resolved one option is to delete the resolv.conf generated by systemd (because k8s picks that instead of using the stub resolver).


So add this to `/etc/systemd/system/systemd-resolved.service.d/override.conf`

```ini

[Service]
ExecStartPost=/bin/bash -c 'rm -f /run/systemd/resolve/resolv.conf'
Type=notify
```


(Note, systemd since v256 supports reloading resolved by setting `Type=notify-reload`, which regenerates the deleted file. Of course if someone manually sends HUP the file will appear again.)
