### ISSUE TITLE
Deprecated mondo test tarball needs removed

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#82767]
**What happened**:
On 2019-02-22 https://github.com/kubernetes/kubernetes/pull/74065 was merged with an indication that the mondo test tarball noted as deprecated as per https://git.k8s.io/enhancements/keps/sig-testing/20190118-breaking-apart-the-kubernetes-test-tarball.md.  But it did not include a timeline for eventual removal.

**What you expected to happen**:
It's been 7 months now.  We should formalize a plan for removal.

/sig testing
/sig release
/kind cleanup
/priority important-soon

**Comment by mrbobbytables** [comment]
Enhancement tracking issue ref: https://github.com/kubernetes/enhancements/issues/714

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/pull/83093 removes the deprecated mondo test tarball.
