### ISSUE TITLE
kube-apiserver sometimes times out contacting MutatingWebhook

### ISSUE THREAD

**Issue by jurgenweber** [kubernetes/kubernetes#82768]
**What happened**:
the kube-apiserver pods reporting the following error when contacting the webhook we are using: 
```
"dispatcher.go:67] Failed calling webhook, failing open pods.vault-secrets-webhook.admission.banzaicloud.com: failed calling admission webhook \"pods.vault-secrets-webhook.admission.banzaicloud.com\": Post https://secrets-webhook-vault-secrets-webhook.secrets.svc:443/pods?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

**What you expected to happen**:
I expected all posts to the webhook to be successful and without error.

**How to reproduce it (as minimally and precisely as possible)**:
Create a webhook using create pod:
```
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    resources:
    - pods
```
reference a service as the clientConfig endpoint.
```
    caBundle: "..."
    service:
      name: secrets-webhook-vault-secrets-webhook
      namespace: secrets
      path: /pods
```

**Anything else we need to know?**:
The error follows the kube-apiserver pod that is the current kube-controller-manager (identified by using `kubectl describe ep -n kube-system kube-controller-manager`). I can quite easily kill the pod leader change and the error follows it. 

I have tested all networking, I can telnet from the host and the pods to the webhook pods via the service without issue. I have changed my AWS ec2 instance types to be gen 5 (better networking bandwidth, etc). I have cycled all masters with new instances (just in case). 

I resolved the issue by creating an ingress and using the clientConfig.url parameter with a suitable caBunble but I do not consider this a solution going forward.

Approx 15% of all pods fail their mutation which causes problems. As far as I can tell these requests just never make it to the webhook pods.

I have seen some other issues that are similar but do not make the correlation with the controller-manager. for example: https://github.com/kubernetes/kubernetes/issues/80313

maybe this is a kops issue, maybe this is a canal issue. I don't know.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
I originally was on 1.11.6 and upgraded, both versions have the error.
- Cloud provider or hardware configuration:
AWS using kops.
- OS (e.g: `cat /etc/os-release`):
Debian Stretch
- Kernel (e.g. `uname -a`):
```
Linux ip-10-10-5-85 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
CNI is Canal.
```
$ kubectl describe pod canal-p5ww5 -n kube-system | grep -i image
    Image:          quay.io/calico/node:v3.2.3
    Image ID:       docker-pullable://quay.io/calico/node@sha256:e546014887cd5663cdd199d3a84dfc355cfe704dedfd1b489c799e040e7e828f
    Image:         quay.io/calico/cni:v3.2.3
    Image ID:      docker-pullable://quay.io/calico/cni@sha256:ae3352d2c5dc1631a82777b4f584655d78089d9c8aa5bcdf535dfc0f5deea87a
    Image:         quay.io/coreos/flannel:v0.9.0
    Image ID:      docker-pullable://quay.io/coreos/flannel@sha256:dd3bcb1682a80dbd49776f2a9de036719685c0f9a7a5919876f3f685d6c0b7f4
```
- Others:

**Comment by liggitt** [comment]
The controller manager does not speak to the webhook, only the apiserver does.

**Comment by liggitt** [comment]
the correlation with the controller manager is likely just because the controller manager speaks to its local apiserver, so the volume of pod write requests is much higher on that api server.

**Comment by liggitt** [comment]
A few questions:
1. Is the backing pod (or pods) for the webhook restarting around when this is occurring?
2. Do you have multiple pods backing that service?
3. Are you using `--enable-aggregator-routing` on the API server?

**Comment by jurgenweber** [comment]
> Is the backing pod (or pods) for the webhook restarting around when this is occurring?
no
> Do you have multiple pods backing that service?
yes
> Are you using --enable-aggregator-routing on the API server?
no, but kube-proxy is on the master nodes.

note: https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/
> If you are not running kube-proxy on a host running the API server, then you must make sure that the system is enabled with the following kube-apiserver flag:
> --enable-aggregator-routing=true

**Comment by liggitt** [comment]
Note that 1.11.x is out of support, we'll need to reproduce against 1.13+

If the issue is dead TCP connections, that issue is still a general client-go issue that is known and unresolved (it is on the list for investigation in 1.17)

**Comment by liggitt** [comment]
Re: https://github.com/kubernetes/kubernetes/issues/75791, concurrent requests load balance better in 1.16 due to switching to http/1.1 for webhook connections

**Comment by jurgenweber** [comment]
> Note that 1.11.x is out of support, we'll need to reproduce against 1.13+

yeah, I thought you might say that.

> If the issue is dead TCP connections, that issue is still a general client-go issue that is known and unresolved (it is on the list for investigation in 1.17)

How can I confirm if it is that issue?

**Comment by chadlwilson** [comment]
/remove-lifecycle rotten

To my knowledge this issue is still ongoing - at least we are still seeing it on 1.14 with EKS with dead connections; see https://github.com/istio/istio/issues/13840 for an example with a specific webhook (istio-sidecar-injector). After a 15 minute or so timeout, the webhooks can be contacted again.

Perhaps it's the issue @liggitt refers to above with the "general client-go issue". If so, could someone supply a link? I'm a bit lost in the sea of related issues pertaining to webhook connectivity issues.

**Comment by chadlwilson** [comment]
Sorry, perhaps found it at https://github.com/kubernetes/client-go/issues/374
