### ISSUE TITLE
Not able to deploy kind:pod from another cluster.

### ISSUE THREAD

**Issue by dhineshbabuelango** [kubernetes/kubernetes#82774]
Hi All,
We have two EKS cluster running, we are running the kubectl command from one cluster to deploy the pod in other cluster, we are getting error like below. 
when the kind is deployment instead of pod, we are able to deploy.

**Error: release test-api failed: pods "test-api" is forbidden: pod does not have "kubernetes.io/config.mirror" annotation, node "XXXXX..compute.internal" can only create mirror pods**

**Comment by liggitt** [comment]
Kubelets are only permitted by the `NodeRestriction` admission plugin to create "mirror pods", in order to protect against one compromised node scheduling workloads to run on another node. You will need to use a non-kubelet credential to create the pods.

/close

**Comment by eightlimbed** [comment]
I ran into this error and realized it was because I had the environment variable `KUBERNETES_SERVICE_HOST` set incorrectly.

**Comment by diegoturcios** [comment]
@eightlimbed which is the value that `KUBERNETES_SERVICE_HOST` needs to have?
