### ISSUE TITLE
[Failing Test] [sig-node] pod infra containers oom-score-adj should be -998 and best effort container's should be 1000

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kubernetes#82771]
**Which jobs are failing**:
ci-kubernetes-node-kubelet-serial

**Which test(s) are failing**:
[k8s.io] Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup pod infra containers oom-score-adj should be -998 and best effort container's should be 1000

**Since when has it been failing**:

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Reason for failure**:
```
framework.ServeHostnameImage started with  the process of agnhost 
```
**Anything else we need to know**:

**Comment by zouyee** [comment]
@kubernetes/sig-node-test-failures

**Comment by alejandrox1** [comment]
Let's monitor this one and see if #82772 worked
/reopen
/milestone v1.17
/priority critical-urgent

**Comment by zouyee** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1174077362866753536
 It seems work well.

**Comment by odinuge** [comment]
These now have 8 successful runs without a single flake. Looks like #82772 worked! :smile: 

cc @alejandrox1

**Comment by liggitt** [comment]
thanks

/close
