### ISSUE TITLE
kube-controller-manager crash when node.Spec.PodCIDR is out of range, is the result as expected?

### ISSUE THREAD

**Issue by snowplayfire** [kubernetes/kubernetes#82773]
**What happened**:
If a node with illegal cidr is added into a cluster,  there is a error message in kube-controller-manager.ERROR. The error message only appears once,  the cluster will be thought as normal and do nothing if the error message is missed. Everything is ok until controller-managers change leader or restart. 

When controller-managers restart, the new leader controller-manager's nodeipam controller iterates all nodes' cidr. If a node's cidr is illegal(not cidr format or out of range),  leader controller-manager will crash. Next a new leader will be chosen and crash......chosen and crash....., controller-manager can not work until the node is deleted.

I have a confusion here. Only print  an error message once when a node with illegal cidr is added but crash when one existed node has illegal cidr, the inconsistent behaviors of nodeipam controller are as expected? or is it a bug? If it is a bug, I can help to fix it.

**How to reproduce it**:
Add a node with illegal cidr into cluster, then restart kube-controller-manager. You can see kube-controller-manager can not work until the node is deleted.

**Environment**:
kubernetes v1.13.2

**Fix suggestions**:
1.  Keep consistent behaviors for nodeipam controller. A node with illegal cidr now will cause controller-manager's crash when controller-manager restarts, I think the behavior is too serious. Maybe we can just print  the error message rather than crash  when nodeipam controller restarts, it is consistent with the behavior when a node with illegal cidr is added.

2. Refuse the illegal nodes to join the cluster.

**Comment by zouyee** [comment]
https://github.com/kubernetes/kubernetes/issues/82765

**Comment by ZP-AlwaysWin** [comment]
> #82765

These two should not be the same problem.The second problem is a bug introduced in the new version.The current problem is the problem of the old version.

**Comment by ZP-AlwaysWin** [comment]
kube-controller-manager crash when node.Spec.PodCIDR is out of range，kube-controller-manager ，It can't be started. It's always in a state of selection.You can see the problem from the logs of the chooser。maybe the best way is  not let the wrong nodes join the cluster

**Comment by snowplayfire** [comment]
@ZP-AlwaysWin Yes, it is also a "Fix suggestion" which involves not only kube-controller-manager.

**Comment by kow3ns** [comment]
Hello @snowplayfire. This is issue should be assigned to a combination of SIG Cluster Lifecycle and (potentially) SIG Node.

**Comment by snowplayfire** [comment]
@kow3ns I think the issue is relevant to controller-manager. When an illegal node is added into a cluster, nodeipam controller only prints one line error message one time, and does nothing until controller-manager restarts.  If controller-manager restarts,  something catastrophic happen.

I think controller-manager should achieve:
1. remind an illegal node is in the cluster again and again rather only one time. It is only one time now, sometimes we may miss the one line error message, so we think the cluster is right. When catastrophic crashs happen, it is difficult for us to find the cause.

2. when an illegal node is added into a cluster, nodeipam controller prints one line error message one time rather than crash.  If nodeipam controller  restarts, controller-manager will crash. The two behaviors of nodeipam controller are inconsistent. Maybe they should be consistent.

To solve it thoroughly,  maybe we can add a status for node lifecycle before the node is really joind into the cluster.

**Comment by junjieyjj** [comment]
I think my cluster also encountered a similar situation. After two new nodes were added, controller-manager log output CIDR out of range.  how can I  restore the cluster? pls help

**Comment by snowplayfire** [comment]
@junjieyjj   The two new nodes' cidrs are allocated by controller-manager or by hand?
