### ISSUE TITLE
Azure: Add Support for Write Accelerator

### ISSUE THREAD

**Issue by MSSedusch** [kubernetes/kubernetes#82781]
**What would you like to be added**:
Add support for Azure Write Accelerator on Azure Disks - https://docs.microsoft.com/azure/virtual-machines/windows/how-to-enable-write-accelerator

**Why is this needed**:
For high performance applications, like databases, using Write Accelerator on disks where the database log is stored can improve performance. If customers are already using M or Mv2 VM types, they can use Write Accelerator at no additional costs.

**Comment by andyzhangx** [comment]
hi @MSSedusch , do you know what if user enable `WriteAccelerator` on a VM size does not support this or on a standard HDD disk?
/assign

**Comment by MSSedusch** [comment]
If the VM size does not support it, Azure API returns the following response:
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "VM size Standard_D4s_v3 is not supported on Virtual Machines with 'Write Accelerator' enabled.",
    "target": "writeAcceleratorEnabled"
  }
}
```

If you enable write accelerator for Standard HDD and the VM is deallocated, it works but the VM cannot start with this configuration. If the VM is running and you enable WA for a Standard HDD, Azure API responds with:
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "Write Accelerator is supported with Premium_LRS storage account type only. Please use correct storage account type for disk dataDisk(lun1).",
    "target": "writeAcceleratorEnabled"
  }
}
```

**Comment by andyzhangx** [comment]
@MSSedusch do you have any rough perf improvement in specific scenario? In general, it's doable, while I would like to know the business impact, thanks.

**Comment by MSSedusch** [comment]
/remove-lifecycle rotten
it would still be great to support Write Accelerator in K8s on Azure

**Comment by MSSedusch** [comment]
The write latency will be sub milliseconds which is one of the KPI required by SAP HANA. Premium Disk Write latency is usually in the lower single digits millisecond so it improves write latency a lot.

**Comment by andyzhangx** [comment]
> The write latency will be sub milliseconds which is one of the KPI required by SAP HANA. Premium Disk Write latency is usually in the lower single digits millisecond so it improves write latency a lot.

@MSSedusch ok, I will try to add `writeAcceleratorEnabled` support for data disk in k8s 1.18

**Comment by MSSedusch** [comment]
great, thanks!
