### ISSUE TITLE
k8s high availability /  multi master cluster issue 

### ISSUE THREAD

**Issue by mannevijayakrishna** [kubernetes/kubernetes#82792]
hi, I am trying to build a 3 master cluster but I am getting below error c. can some help me. 

kubeadm init --config config.yaml
W0917 10:44:31.802396   10260 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta1", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "apiServerCertSANs"
[init] Using Kubernetes version: v1.15.3
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ExternalEtcdVersion]: Get https://192.168.1.21:2379/version: dial tcp 192.168.1.21:2379: connect: connection refused
        [ERROR ExternalEtcdVersion]: Get https://192.168.1.22:2379/version: dial tcp 192.168.1.22:2379: connect: no route to host
        [ERROR ExternalEtcdVersion]: Get https://192.168.1.23:2379/version: dial tcp 192.168.1.23:2379: connect: no route to host
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Comment by neolit123** [comment]
> W0917 10:44:31.802396 10260 strict.go:54] error unmarshaling configuration 

v1beta1 ClusterConfiguration does not have `apiServerCertSANs`, see examples at:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

also better migrate to v1beta2:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

> [ERROR ExternalEtcdVersion]: Get https://192.168.1.21:2379/version: dial tcp 192.168.1.21:2379: connect: connection refused

make sure your external etcd cluster is healthy.

/triage support
/sig cluster-lifecycle

**Comment by mannevijayakrishna** [comment]
I have resolved the issue.   thank you very much for all your help.
