### ISSUE TITLE
Add --focus and --skip arguments to Jenkins so that it reports test run results correctly

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#8279]
http://onsi.github.io/ginkgo/#focused-specs

Right now, GinkgoRunner returns 1 if there are any programmatically Focussed, Skipped or Pending tests, so Jenkins reports all tests runs as failed, when they should be considered passed.

Adding the Focussed, Skipped and Pending tests to Ginkgo's command line (which overrides programatic settings) within the Jenkins (and in fact any Continuous Integration environment), will cause the CI to report successes and failures correctly.

**Comment by quinton-hoole** [comment]
Probably here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/4e023e9f8e6914b3cd8613ef1d099e8e544bb436/hack/jenkins/e2e.sh#L41

**Comment by quinton-hoole** [comment]
To be clear, the failure reports that I'm referring to are in the Jenkins Test Results Analyser tool (even if all e2e tests pass, the test reun is reported as failed).  I assume that the above is the reason why.

Curiously, in other contexts, Jenkins reports success for such test runs.

**Comment by quinton-hoole** [comment]
cc: @ixdy @zmerlynn FYI

**Comment by zmerlynn** [comment]
That's a bug in Test Results Analyzer and not a product bug at all. Why is this a k8s bug?

**Comment by quinton-hoole** [comment]
I retrospect I think you're right.  I think I misread the following and got
confused.

"When Ginkgo detects that a passing test suite has a programmatically
focused test it causes the suite to exit with a non-zero status code. This
is to help detect erroneously committed focused tests on CI systems. When
passed a command-line focus/skip flag Ginkgo exits with status code 0 - if
you want to focus tests on your CI system you should explicitly pass in a
-focus or -skip flag."

**Comment by ixdy** [comment]
The Test Results Analyzer doesn't look at the exit code at all, AFAIK. Unless the junit XML somehow indicates a failure, I think this is a bug in the Jenkins plugin, not in any of our process.

Also, by default, Ginkgo only exits non-zero if there are any programmatically *focused* tests. Any programmatically *pending* tests (as we have) will not exit non-zero unless `--failOnPending` is passed.

(In any case, we ignore the exit code from Ginkgo entirely, as that would mark the job in Jenkins as red rather than yellow.)

Closing because I don't think there's anything for us to do here.

**Comment by quinton-hoole** [comment]
Well, we either need to:
1. cause the Jenkins plugin to be fixed upstream
2. fix it ourselves (if it's open source)
3. work around it in our Jenkins or Ginkgo config.

**Comment by ixdy** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-27628 is the relevant bug against the Test Results Analyzer plugin. There's even a patch there, though there seems to be no movement. I'm not sure if it should have been presented as a PR instead, or if there's no active development on the plugin.

**Comment by ihmccreery** [comment]
Closing as obsolete.
