### ISSUE TITLE
kubectl exec sometimes interprets options right of the opening command as its own

### ISSUE THREAD

**Issue by nfd9001** [kubernetes/kubernetes#82806]
Hi; I'm tapping this out on my phone, so please forgive the missing boilerplate. Using client v1.15.0, server 1.15.3, kubectl 1.15.3 (as reported by apt) on Ubuntu 18.04, kubectl isn't working the way I expect. 

Try some command `kubectl -n namespace exec podname -c containername -ti bash -c "command"`. I tried this within a script I'm using, and I get an error... 
`Error from server (BadRequest): container vim (file path) is not valid for pod podname`. I expected the second `-c ` option to be ignored by kubectl and passed through to the command. 

I have yet to find a suitable workaround for this, due to needing bash to do some expansion before passing the command to kubectl, and due to needing an interactive session (which apparently doesn't work if I try to pass in a here-string with `...bash << EOF (code) EOF`—kubectl determines that this is NOT a tty).

It would be nice if kubectl let *all* options to the right of the beginning of the command through to the command itself.

**Comment by liggitt** [comment]
you can add `--` and all options following it are assumed to be part of the command to be sent to the pod, not to be interpreted by `kubectl exec`

In your example:
```
kubectl -n namespace exec podname -c containername -ti -- bash -c "command"
```

This follows posix guidelines:

> POSIX.1-2017
> 
> 12.2 Utility Syntax Guidelines
> 
> Guideline 10:
> 
> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

/close
