### ISSUE TITLE
/healthz?verbose=true should report component timings

### ISSUE THREAD

**Issue by jktomer** [kubernetes/kubernetes#82808]
**What would you like to be added**:
Getting `/healthz?verbose=true` from apiserver presently returns output like:
```
[+]ping ok
[+]log ok
[+]etcd ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok
[+]SSH Tunnel Check ok
[+]poststarthook/ca-registration ok
[+]poststarthook/start-kube-apiserver-informers ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/apiservice-openapi-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
healthz check passed
```

It would be nice if each of these lines included a statement of how long that check took to run.

**Why is this needed**:
We were debugging a cluster with inexplicably slow /healthz responses today and knowing why/what was slow would have been helpful.

**Comment by paivagustavo** [comment]
I like this idea, I would like to take this one. I was thinking that we could simply add the time in the end of each line, for example:

```
[+]ping ok 15ns
[+]log ok 1.739µs
[+]etcd ok 2.5s
```

The implementation seems pretty straight-forward, just time each check in the handler `handleRootHealthz` at the file `staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go`.

If we don't want to add this directly maybe could add another request parameter.

Could anyone validate?

**Comment by liggitt** [comment]
it's unclear if the output of that endpoint is supposed to be considered machine-parseable. if so, we might need a separate parameter to include timing info

**Comment by paivagustavo** [comment]
Yes, that is what I was afraid. We could add a `includeTime` parameter?

**Comment by jktomer** [comment]
Or perhaps ?verbose=trace so as not to introduce a new parameter. (Especially since including the timings is not meaningful when !verbose.)

**Comment by liggitt** [comment]
a distinct value for verbose seems reasonable

**Comment by logicalhan** [comment]
> Or perhaps ?verbose=trace so as not to introduce a new parameter. (Especially since including the timings is not meaningful when !verbose.)

Alternatively, we can output timings in outputted logs when includeTiming query param is set. This would mean that we can decouple the two query params and customize the behavior for verbose output when the two are both present. 

It makes using healthz with query params a bit simpler and more intuitive since we can do this:

`curl localhost:8080/healthz?verbose&includeTimings`
`curl localhost:8080/healthz?verbose`
`curl localhost:8080/healthz?includeTimings`

**Comment by paivagustavo** [comment]
@logicalhan but what `includeTimings` without `verbose` would return? If it returns the timing of every check, isn't this already verbose? 

@jpbetz suggested that we return a structured data, with JSON or something (based on the `Accept` header). It is easier and more extensible, I like this approach better. 

One thing that I would prefer is using query parameters instead of Headers, to be easier to use and share with others. Maybe `/healthz?json`? or `/healthz?format=json` to be more explicit.

Suggestion of a possible JSON for this:
```js
{
    "status" : "healthy", // aggregation of all checks
    "checks" : [
        { 
            "name" : "ping",
            "status" : "healthy",
            "duration" : 15 // milliseconds
            // "reason" : "timeout", "connection failed" or whatever reason.
        },
        {
            "name" : "etcd",
            "status" : "healthy",
            "duration" : 27
        }
    ]
}
```

 WDYT?

**Comment by logicalhan** [comment]
> @logicalhan but what `includeTimings` without `verbose` would return? If it returns the timing of every check, isn't this already verbose?

My thought was that it would individually log out the timing details into kube-apiserver.log. The actual output of healthz would be the same.

**Comment by logicalhan** [comment]
> @jpbetz suggested that we return a structured data, with JSON or something (based on the `Accept` header). It is easier and more extensible, I like this approach better.
> 
> One thing that I would prefer is using query parameters instead of Headers, to be easier to use and share with others. Maybe `/healthz?json` or `/healthz?format=json` to be more explicit.
> 
> Suggestion of a possible JSON for this:
> 
> ```js
> {
>     "status" : "healthy", // aggregation of all checks
>     "checks" : [
>         { 
>             "name" : "ping",
>             "status" : "healthy",
>             "duration" : 15 // milliseconds
>             // if unhealthy return a field "reason"
>             // example of values "timeout", "connection failed" or whatever reason.
>         },
>         {
>             "name" : "etcd",
>             "status" : "healthy",
>             "duration" : 27
>         }
>     ]
> }
> ```
> 
> WDYT?

I (and @DirectXMan12) think supporting json format would be super nice (it is an orthogonal issue to this one, however). Also, we should specify the content type through the header and not through query params.

**Comment by paivagustavo** [comment]
@logicalhan You said it is an orthogonal issue, to clarify that, Do you mean that it should be done in another issue?

I changed my mind and agree with the header instead of query parameter.

**Comment by DirectXMan12** [comment]
Yeah, it's probably a good idea to just split the JSON output to a separate issue
