### ISSUE TITLE
Migrate kube-scheduler to use v1beta1 Events

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubernetes#82835]
Now that new Events API is ready, we can migrate the kube-scheduler to emit events against the new API.

This is part of #76674

/assign

**Comment by jfbai** [comment]
cc @wojtek-t @shoucongc @yastij

**Comment by yastij** [comment]
the scheduler itself already emits such Events. the only missing part is the leader election package

**Comment by jfbai** [comment]
> the scheduler itself already emits such Events. the only missing part is the leader election package

Thanks a lot, Closed this issue.
