### ISSUE TITLE
NodeStageVolume is called before each call to NodePublishVolume

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#82838]
**What happened**:
Moving https://github.com/kubernetes-csi/external-provisioner/issues/90 to k/k repo

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
This needs help with repro, and investigation

**Comment by hoyho** [comment]
I would like to do it

**Comment by gnufied** [comment]
This might be because both `NodeStage` and `NodePublish` are part of same general `MountVolume` function in operation_generator. The isolation we are looking for does not exist.

Fixing it will require detangling MountDevice and Setup calls, which could be tricky..
