### ISSUE TITLE
kubectl top command

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kubernetes#82843]
I am running k8s 1.15 and I see kubectl top --help is returning the following info:
...This command requires Heapster to be correctly configured and working on the server.

As far as I know Heaspter is deprecated since 1.11.

1) Should the command help be updated i.e. replace Heapster with Metrics Server?

2) Will the command work if Metrics Server is deployed in the cluster?

3) Is kubectl top utility the easiest way to display (actual) resource usage info for pods and nodes? Any suggestions?

**Comment by dfang** [comment]
[depreaction timeline for heapster](https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md)

1.  submitted a pr for this
2.  yes
3.  yes, or kubernetes dashboard
