### ISSUE TITLE
can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already in use

### ISSUE THREAD

**Issue by YouDail** [kubernetes/kubernetes#82851]
I installed isti v1.3 in the kubernetes v1.1.4.3 cluster and created the service named NodePort in the name: istio-ingressgateway.

Service/istio-ingressgateway NodePort 10.101.149.203 <none> 15020:30039/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30557/TCP,15030:31540/TCP,15031: 30098/TCP, 15032:30811/TCP, 15443:32141/TCP 44s

At this time, on the master1 node, the traffic of its pod is abnormal, and the external application cannot be accessed. I checked the kube-proxy of the master1 node. The kube-proxy keeps reporting errors. The error message is:

E0918 10:21:56.675529 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:06.853574 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:13.199552 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:28.794474 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:32.486351 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:33.672319 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:34.980481 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:35.228433 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use
E0918 10:22:37.437673 1 proxier.go:1054] can't open "nodePort for istio-system/istio-ingressgateway:tcp" (:31400/tcp), skipping this nodePort: listen tcp :31400: bind: address already In use

I looked at port 31400 on the master1 node, and surely port 31400 is being used by the nginx service:

[root@kmaster1 /]# ss -altunp | grep 31400
Tcp LISTEN 0 128 *:31400 *:* users:(("nginx", pid=18445,fd=285),("nginx",pid=18392,fd=285),("nginx",pid=18357, Fd=285), ("nginx", pid=18323, fd=285), ("nginx", pid=18284, fd=285), ("nginx", pid=18243, fd=285), ("nginx ", pid=18157, fd=285), ("nginx", pid=18134, fd=285), ("nginx", pid=18123, fd=285), ("nginx", pid=18090, fd= 285), ("nginx", pid=18025, fd=285), ("nginx", pid=18019, fd=285), ("nginx", pid=17986, fd=285), ("nginx", Pid=17920,fd=285),("nginx",pid=17912,fd=285),("nginx",pid=17874,fd=285),("nginx",pid=17770,fd=285) , ("nginx", pid=17741, fd=285), ("nginx", pid=17735, fd=285), ("nginx", pid=17730, fd=285), ("nginx", pid= 17699,fd=285),("nginx",pid=17601,fd=285),("nginx",pid=17590,fd=285),("nginx",pid=17589,fd=285),( "nginx", pid=17556, fd=285), ("nginx", pid=17456, fd=285), ("nginx", pid=17455, fd=285), ("nginx", pid=17454, Fd=285), ("nginx", pid=17453, fd=285), ("nginx", pid=17452, fd=285), ("nginx", pid=17451, fd=285), ("nginx ", pid=17447, fd=285), ("nginx", pid=17446, fd=285))

So I'm not sure if this is the service. It didn't detect if the 31400 port has been used. This problem is more troublesome unless I choose the default ClusterIp type when I create the isti-ingressgateway service.

**Environment**:
- Kubernetes version (use `kubectl version`):

[root@kmaster1 /]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44: 30Z", GoVersion: "go1.12.5", Compiler: "gc", Platform: "linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36: 19Z", GoVersion: "go1.12.5", Compiler: "gc", Platform: "linux/amd64"}

- Cloud provider or hardware configuration:
   Physical machine

- OS (e.g: `cat /etc/os-release`):
[root@kmaster1 /]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
[root@kmaster1 /]# uname -a
Linux kmaster1.local 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Network plugin and version (if this is a network-related bug):
Calico:v3.6.0
Kube-proxy: image: k8s.gcr.io/kube-proxy:v1.14.3

**Comment by dims** [comment]
/close

please open a bug report in istio github repo
