### ISSUE TITLE
[v1.16.1] informer-gen is broken for packages in a folder with a dot in them?

### ISSUE THREAD

**Issue by ibuildthecloud** [kubernetes/kubernetes#82860]
**What happened**:

I have the folder `pkg/apis/k3s.cattle.io/v1` where the folder k3s.cattle.io is the package k3s. Running informer-gen with v1.15 would produce `pkg/generated/informers/externalversions/k3s.cattle.io/v1/` and the folder k3s.cattle.io would be the package k3s.  In 1.16 the folder k3s.cattle.io generates code as the package `k3s.cattle.io` which is invalid and fails.

This change causes the issue https://github.com/kubernetes/kubernetes/pull/80440/commits/73dc5a96de2836bd7a7fab57241810af47c7e3ee

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/pull/82410 https://github.com/kubernetes/code-generator/issues/77

cc @munnerz @sttts @nikhita

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/82410 and https://github.com/kubernetes/kubernetes/pull/83077 (will be present in v1.16.1)

/close
