### ISSUE TITLE
pkg/volume/rbd/rbd_util.go can't use rbd-nbd

### ISSUE THREAD

**Issue by BruceShenC** [kubernetes/kubernetes#82864]
**What happened**:

In order to use rbd-nbd, installed rbd-nbd and disabled krbd.
But kubelet still saied:
"
rbd-nbd: getting rbd-nbd version failed with error
"

checked the code:
pkg/volume/rbd/rbd_util.go:
in line 246:
"
if _, err := e.Run("rbd-nbd", "--version"); err != nil {
		klog.V(5).Infof("rbd-nbd: getting rbd-nbd version failed with error %v", err)
		return false
	}
"

kubelet run "rbd-nbd --version" to check whether rbd-nbd installed.

But from "https://github.com/ceph/ceph/blob/master/src/tools/rbd_nbd/rbd-nbd.cc"

"
 std::cout << "Usage: rbd-nbd [options] map <image-or-snap-spec>  Map an image to nbd device\n"
            << "               unmap <device|image-or-snap-spec>   Unmap nbd device\n"
            << "               [options] list-mapped               List mapped nbd devices\n"
            << "Map options:\n"
            << "  --device <device path>  Specify nbd device path (/dev/nbd{num})\n"
            << "  --read-only             Map read-only\n"
            << "  --nbds_max <limit>      Override for module param nbds_max\n"
            << "  --max_part <limit>      Override for module param max_part\n"
            << "  --exclusive             Forbid writes by other clients\n"
            << "  --timeout <seconds>     Set nbd request timeout\n"
            << "  --try-netlink           Use the nbd netlink interface\n"
            << "\n"
            << "List options:\n"
            << "  --format plain|json|xml Output format (default: plain)\n"
            << "  --pretty-format         Pretty formatting (json and xml)\n"
            << std::endl;
"

rbd-nbd doesn't support "--version".

It means kubelete will not use rbd-nbd forever.

**What you expected to happen**:
It should use rbd-nbd
**How to reproduce it (as minimally and precisely as possible)**:
create pod yaml and used ceph volume
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by danielqsj** [comment]
@BruceShenC this is interesting, I download rbd-nbd in ubuntu 18.04, it says it has the `--version` option:
```
~$ rbd-nbd -h
Usage: rbd-nbd [options] map <image-or-snap-spec>  Map a image to nbd device
               unmap <device path>                 Unmap nbd device
               list-mapped                         List mapped nbd devices
Options:
  --device <device path>                    Specify nbd device path
  --read-only                               Map readonly
  --nbds_max <limit>                        Override for module param nbds_max
  --max_part <limit>                        Override for module param max_part

  --conf/-c FILE    read configuration from the given configuration file
  --id/-i ID        set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --setuser USER    set uid to user or uid (and gid to user's gid)
  --setgroup GROUP  set gid to group or gid
  --version         show version and quit

  -d                run in foreground, log to stderr.
  -f                run in foreground, log to usual location.
  --debug_ms N      set message debug level (e.g. 1)
```
But actually it failed: 
```
~$ rbd-nbd --version
rbd-nbd: unknown command: --version
```

**Comment by BruceShenC** [comment]
@danielqsj Yes.  "--version" is in rbd-nbd's help info  but it doesn't support.

**Comment by cwdsuzhou** [comment]
Seems we need change the command the check the existence of rbd-nbd

**Comment by danielqsj** [comment]
@BruceShenC please upgrade your rbd-nbd client. From my side, after upgrade to `12.2.8`, the `--version` works:
```
$ rbd-nbd --version
ceph version 12.2.8 (ae699615bac534ea496ee965ac6192cb7e0e07c0) luminous (stable)
```
