### ISSUE TITLE
kubernetes-e2e-gce-100-performance is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#82875]
One example:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82832/pull-kubernetes-e2e-gce-100-performance/1174602482194583552/

```
:0
[measurement call APIResponsiveness - APIResponsiveness error: top latency metric: there should be no high-latency requests, but: [got: {Resource:persistentvolumes Subresource: Verb:POST Scope:cluster Latency:perc50: 200.218ms, perc90: 959.78ms, perc99: 1.032768s Count:43}; expected perc99 <= 1s]]
:0
```

**Comment by krzysied** [comment]
```
[measurement call WaitForControlledPodsRunning - WaitForRunningDaemonSets error: 1 objects timed out: DaemonSets: test-siwk1t-1/daemonset-0]
```
There is a problem with creating deamonsets when node killer is enabled. When clusteroader creates daemonset it stores expected number of pods. When killed node reappears, the expected number of pods is not update, causing #pods != #expected pods.

**Comment by mm4tt** [comment]
Wouldn't just stop ignoring the NotReady nodes when calculating number of replicas for DeamonSet fix the issue?

**Comment by krzysied** [comment]
As a short term fix - yes it would.
There will be a problem if at some point we want to have NotReady nodes and then change it status to Ready and see how big cluster handles it...

**Comment by mm4tt** [comment]
I think this should be good enough for know, given that it's going to be a one line change.

**Comment by mm4tt** [comment]
I think the fix we applied as a part of this issue helped (at least when it comes to the symptoms describe here).
Closing this one.

/close
