### ISSUE TITLE
Traffic routed to replica set with not ready pods 

### ISSUE THREAD

**Issue by rishiraaz** [kubernetes/kubernetes#82872]
**What happened**:
We upgraded a new deployment using helm in a kubernetes 1.13.10 cluster, the new pods failed liveness due to some issue, but traffic was being routed to these new pods instead of being sent to the old healthy pods.

**What you expected to happen**: 
Until the new pods are healthy traffic should now be routed to them

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.10
- Cloud provider or hardware configuration: AWS, ec2 instances
- OS (e.g: `cat /etc/os-release`): debian stretch
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): nginx
- Others:

**Comment by liggitt** [comment]
Liveness probes are used to determine when a container needs to be restarted.

Readiness probes are used to determine when a container is ready to receive traffic. If you define a readiness probe, you will get the behavior you want. See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ for details

/close
