### ISSUE TITLE
cannot join network of a non running container  --on ARM Ubuntu 16.04

### ISSUE THREAD

**Issue by LZhipeng** [kubernetes/kubernetes#82880]
I deploy the nginx on k8s. One of the nodes is the ARM Ubuntu16.04.
The pod on the ARM can't enter the Running state.
I'll be appreciate if someone give me a solution.

[root@k8s-master2 ssl]# kubectl get pods
NAME                     READY   STATUS             RESTARTS   AGE
nginx-7bb7cd8db5-6s9m4   1/1     Running            0          26m
nginx-7bb7cd8db5-lz26n   0/1     CrashLoopBackOff   10         26m

[root@k8s-master2 ssl]# kubectl describe pod nginx-7bb7cd8db5-lz26n
......
Events:
  Type     Reason          Age                    From                     Message
  ----     ------          ----                   ----                     -------
  Normal   Scheduled       48m                    default-scheduler        Successfully assigned default/nginx-7bb7cd8db5-lz26n to 192.168.11.233
  Warning  Failed          48m                    kubelet, 192.168.11.233  Error: failed to start container "nginx": Error response from daemon: cannot join network of a non running container: b280ef9e64529c2ddc0851eb67e6e41df4b70f9d6df09d80b884061a6d632a94
  Warning  Failed          48m                    kubelet, 192.168.11.233  Error: failed to start container "nginx": Error response from daemon: cannot join network of a non running container: f74a37759272d1da7a55f5f5902956a7e09d802246d6b1facf334e6ad0a07fb5
  Normal   Pulling         48m (x3 over 48m)      kubelet, 192.168.11.233  Pulling image "nginx"
  Normal   Pulled          48m (x3 over 48m)      kubelet, 192.168.11.233  Successfully pulled image "nginx"
  Normal   Created         47m (x3 over 48m)      kubelet, 192.168.11.233  Created container nginx
  Warning  Failed          47m                    kubelet, 192.168.11.233  Error: failed to start container "nginx": Error response from daemon: cannot join network of a non running container: ab85fcf17b046da9e64ebfdbc16677844db040f0c0b90d9003d5003fbe71b913
  Normal   SandboxChanged  8m14s (x258 over 48m)  kubelet, 192.168.11.233  Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff         3m12s (x437 over 48m)  kubelet, 192.168.11.233  Back-off restarting failed container

----node-----
root@localhost:/opt/kubernetes/cfg# uname -a
Linux k8s-node3 4.4.52-armada-17.10.3 #1 SMP PREEMPT Wed Sep 11 11:46:13 CST 2019 aarch64 aarch64 aarch64 GNU/Linux
root@localhost:~# /opt/kubernetes/bin/flanneld --version
v0.10.0
root@localhost:~# /opt/kubernetes/bin/kubelet --version 
Kubernetes v1.15.3

root@localhost:/opt/kubernetes/cfg# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:c1:f4:57:10  
          inet addr:172.17.64.1  Bcast:172.17.64.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth1      Link encap:Ethernet  HWaddr 0c:fe:5d:00:01:20  
          inet addr:192.168.11.233  Bcast:192.168.11.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1307269 errors:0 dropped:0 overruns:0 frame:0
          TX packets:641675 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:536086367 (536.0 MB)  TX bytes:143158942 (143.1 MB)

flannel.1 Link encap:Ethernet  HWaddr da:82:30:4c:ef:9f  
          inet addr:172.17.64.0  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:31 errors:0 dropped:0 overruns:0 frame:0
          TX packets:36 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2467 (2.4 KB)  TX bytes:4366 (4.3 KB)

Log on node:
E0919 10:42:35.432103   27855 remote_runtime.go:222] StartContainer "df9898b4365d7283b8877471483e2185508b9a15378cfeac0309f101fbbeebc6" from runtime service failed: rpc error: code = Unknown desc = failed to start container "df9898b4365d7283b8877471483e2185508b9a15378cfeac0309f101fbbeebc6": Error response from daemon: cannot join network of a non running container: ba4cfdaff83f88348ce93585c71bc7ca780f2599ca65c1bd5b888ec66fd53cac
E0919 10:42:35.432628   27855 kuberuntime_manager.go:779] container start failed: RunContainerError: failed to start container "df9898b4365d7283b8877471483e2185508b9a15378cfeac0309f101fbbeebc6": Error response from daemon: cannot join network of a non running container: ba4cfdaff83f88348ce93585c71bc7ca780f2599ca65c1bd5b888ec66fd53cac
I0919 10:42:35.432765   27855 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-7bb7cd8db5-lz26n", UID:"b91290f7-a43e-4418-a228-b77d89883487", APIVersion:"v1", ResourceVersion:"217992", FieldPath:"spec.containers{nginx}"}): type: 'Warning' reason: 'Failed' Error: failed to start container "nginx": Error response from daemon: cannot join network of a non running container: ba4cfdaff83f88348ce93585c71bc7ca780f2599ca65c1bd5b888ec66fd53cac
E0919 10:42:35.432963   27855 pod_workers.go:190] Error syncing pod b91290f7-a43e-4418-a228-b77d89883487 ("nginx-7bb7cd8db5-lz26n_default(b91290f7-a43e-4418-a228-b77d89883487)"), skipping: failed to "StartContainer" for "nginx" with RunContainerError: "failed to start container \"df9898b4365d7283b8877471483e2185508b9a15378cfeac0309f101fbbeebc6\": Error response from daemon: cannot join network of a non running container: ba4cfdaff83f88348ce93585c71bc7ca780f2599ca65c1bd5b888ec66fd53cac"
I0919 10:42:35.839157   27855 generic.go:153] GenericPLEG: b91290f7-a43e-4418-a228-b77d89883487/df9898b4365d7283b8877471483e2185508b9a15378cfeac0309f101fbbeebc6: non-existent -> unknown
I0919 10:42:35.848367   27855 kuberuntime_manager.go:880] getSandboxIDByPodUID got sandbox IDs ["ba4cfdaff83f88348ce93585c71bc7ca780f2599ca65c1bd5b888ec66fd53cac" "321432d1e751625e6bb20eb878ac1a567f378f3786751571c4450b0f7d9284c6"] for pod "nginx-7bb7cd8db5-lz26n_default(b91290f7-a43e-4418-a228-b77d89883487)"
W0919 10:42:35.853270   27855 docker_sandbox.go:384] failed to read pod IP from plugin/docker: Couldn't find network status for default/nginx-7bb7cd8db5-lz26n through plugin: invalid network status for
I0919 10:42:35.899255   27855 generic.go:395] PLEG: Write status for nginx-7bb7cd8db5-lz26n/default: &container.PodStatus{ID:"b91290f7-a43e-4418-a228-b77d89883487", Name:"nginx-7bb7cd8db5-lz26n", Namespace:"default", IP:"", ContainerStatuses:[]*container.ContainerStatus{(*container.ContainerStatus)(0x400010da40), (*container.ContainerStatus)(0x4000904e00)}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0x4000ab75c0), (*v1alpha2.PodSandboxStatus)(0x4000ab7ce0)}} (err: <nil>)

**Comment by kadisi** [comment]
please check `--pod-infra-container-image` config of kubelet

**Comment by LZhipeng** [comment]
@kadisi Thanks a lot!
This issue resolved by:
--pod-infra-container-image=mirrorgooglecontainers/pause-arm64:3.0
