### ISSUE TITLE
kubectl completion is too slow

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#82883]
**What happened**:

Kubectl shell completion might be depressingly slow.
Main problem that completion uses constructions like:

```
kubectl get -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' configmap
```

to get resource names. But in large installations they can be extremely slow.

**What you expected to happen**:

I expecting that completion will not download tens of megabytes for each `<TAB>` pressing and will work much faster, actually same speed which is need for getting all resources list.

**How to reproduce it (as minimally and precisely as possible)**:

For example if you use single helm tiller per cluster. And install ~200 releases. You can face with the next situation:

```bash
time kubectl get -n=kube-system -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' configmap > /dev/null

real    0m14.563s
user    0m9.625s
sys     0m1.257s
```

This is happening because of using template option will download all the resources body and then try parse it, but this is too a lot of information:

```bash
# kubectl get -n=kube-system -o json configmaps > /tmp/configmaps.yaml 
# du -hs /tmp/configmaps.yaml 
59M     /tmp/configmaps.yaml
```

You will face with the same problem if you have many pods:

```bash
# kubectl get pod -n kube-system | wc -l
1759

# kubectl get pod -n kube-system -o yaml > /tmp/pod.yaml
# du -hs /tmp/pod.yaml 
7.8M    /tmp/pod.yaml

# time kubectl get -n=kube-system -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' pod > /dev/null

real    0m4.018s
user    0m4.060s
sys     0m0.173s
```

**Anything else we need to know?**:

Simple solution for this issue is not using `-o template` for getting resource names.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: basremetal
- OS (e.g: `cat /etc/os-release`):
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
- Kernel (e.g. `uname -a`):
```
Linux kvaps-laptop 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): bridget
- Others:

**Comment by kvaps** [comment]
My simple solution for that:

```diff
--- a/.kube/completion.bash.inc
+++ b/.kube/completion.bash.inc
@@ -329,10 +329,8 @@
 # $2 is template string for kubectl get (optional)
 __kubectl_parse_get()
 {
-    local template
-    template="${2:-"{{ range .items  }}{{ .metadata.name }} {{ end }}"}"
     local kubectl_out
-    if kubectl_out=$(__kubectl_debug_out "kubectl get $(__kubectl_override_flags) -o template --template=\"${template}\" \"$1\""); then
+    if kubectl_out=$(__kubectl_debug_out "kubectl get $(__kubectl_override_flags) \"$1\" | awk 'FNR>=2 {print \$1}'"); then
         COMPREPLY+=( $( compgen -W "${kubectl_out[*]}" -- "$cur" ) )
     fi
 }
```

but I'm sure there is should be way without awk

**Comment by giovannirco** [comment]
Did this get merged? I have always suffered from this slowness and just decided to search for it on google. Not sure if this is the same problem though, my kubectl takes like 5 seconds to just get pods on a NS that have under 10 pods. I tend to think that the autocomplete slowness is just kubectl working then started to think in a way to cache kubectl responses for like 5 minutes or something else that could  smartly improve tab completion without querying it so much.

**Comment by kustodian** [comment]
Why was this closed? This is still an issue for large K8s environments.
