### ISSUE TITLE
Can't upgrade to 1.16.0: [ERROR CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS 

### ISSUE THREAD

**Issue by vistalba** [kubernetes/kubernetes#82889]
```
kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
        [ERROR CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS Corefile
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```
Any ideas how to solve this?

```
kubectl get nodes -o wide
host1  Ready    master   207d   v1.16.0   10.10.0.10    <none>        Ubuntu 18.04.3 LTS   4.15.0-64-generic   docker://18.6.1
```

**Comment by rajansandeep** [comment]
What does your `Corefile` look like?

**Comment by vistalba** [comment]
```
kubectl -n kube-system get cm coredns -oyaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-02-24T17:26:14Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "210"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 491a7893-3859-11e9-916c-005056af9870
```

**Comment by rajansandeep** [comment]
@vistalba I see that the `proxy` plugin is present in the config. 
From what version of Kubernetes are you upgrading from?

**Comment by vistalba** [comment]
I was on 1.15.3 and now trying upgrading to 1.15.4 first.

**Comment by rajansandeep** [comment]
The preflight check is showing `CoreDNSUnsupportedPlugins` due to the presence of the `proxy` plugin, as it has been deprecated. The `forward` plugin is to be used in its place.

If the `Corefile` is the same as you've mentioned [here](https://github.com/kubernetes/kubernetes/issues/82889#issuecomment-533251094), you can
use the `--ignore-preflight-errors=CoreDNSUnsupportedPlugins`. The `proxy` plugin will be replaced to use `forward` automatically.

**Comment by vistalba** [comment]
Worked for me. Looks like all services are back up :-) Thanks!

**Comment by smirnov-mi** [comment]
Having the same issue here. I installed clean k8s 1.13.4 , didn't install or added anything.
Just upgraded to 1.14.7, then to 1.15.4 and now see the same issue trying to upgrade to 1.16.0

**Comment by TomHutter** [comment]
Found https://github.com/coredns/coredns/issues/1443 and follow ups.

removed `proxy . /etc/resolv.conf` from configMap kube-system/coredns

no more complaints

**Comment by TomHutter** [comment]
Seems, I was a little bit to fast. After upgrading I saw a lot of errors in the coredns POD logs and (external) DNS resolution didn't work at all:

`plugin/errors: 2 example.com. A: plugin/loop: no next plugin found`

Then I added:

`forward . /etc/resolv.conf`

Forwarding all requests to the nameservers in the nodes /etc/resolv.conf

So the solution is **replace** in `configMap kube-system/coredns`:

`proxy . /etc/resolv.conf`

with:

`forward . /etc/resolv.conf`

see also: https://coredns.io/plugins/loop/#troubleshooting

**Comment by cluries** [comment]
Hello, I have the same problem, my Corefile like this, which plugin not supported now?  thanks.

```
Corefile:
----
.:53 {
    errors
    health
    hosts {
        200.200.209.66   xxxx
        fallthrough
    }
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```

**Comment by veeshall** [comment]
@rajansandeep I am having a similar issue, but this is related to rewrite plugin, which I believe is supported in the newer coredns version as well. I can workaround by skipping (or removing rewrite rule and adding it back again). Let me know if you want me to create a new issue to track this, or if this is already tracked.

Kubernetes upgrade from 1.15.3 to 1.16.2

kubeadm upgrade plan
```
[preflight] Some fatal errors occurred:
        [ERROR CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS Corefile
```

coreFile
```
    .:53 {
        errors
        health
        rewrite name exact some-url-1 some-url-2
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache
        reload
    }```

**Comment by rajansandeep** [comment]
@veeshall Yes, the upgrade should happen smoothly by just skipping the preflight check. 
I’ll improve the functionality of the preflight check since more than a few users are having trouble with this. 
/reopen

**Comment by couloum** [comment]
Hi @rajansandeep ,

I have the same issue here due to the plugin `hosts` of coredns that is reported as unsupported.

My coredns config:
```
.:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        hosts {
            1.1.1.1    redacted-entry.domain.com
            fallthrough
        }
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

Result of `kubeadm upgrade plan`

```
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
        [ERROR CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS Corefile
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```
Kubadm version: 
```
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:44:45Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

If I change my coredns configuration to remove usage of `hosts` plugin, the upgrade plan works:

```
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

```
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.15.7
[upgrade/versions] kubeadm version: v1.16.4
I0110 08:07:14.103730   11521 version.go:251] remote version is much newer: v1.17.0; falling back to: stable-1.16
[upgrade/versions] Latest stable version: v1.16.4
[upgrade/versions] Latest version in the v1.15 series: v1.15.7

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
Kubelet     4 x v1.15.7   v1.16.4

Upgrade to the latest stable version:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.15.7   v1.16.4
Controller Manager   v1.15.7   v1.16.4
Scheduler            v1.15.7   v1.16.4
Kube Proxy           v1.15.7   v1.16.4
CoreDNS              1.3.1     1.6.2
Etcd                 3.3.10    3.3.15-0

You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.16.4

_____________________________________________________________________
```

I don't think `hosts` plugin is unsupported by Coredns, unless I'm missing something.

**Comment by chrisohaver** [comment]
> I don't think hosts plugin is unsupported by Coredns, unless I'm missing something.

Hosts is not currently supported by the [corefile migration library](https://github.com/coredns/corefile-migration).  However, the presence of a plugin that is not supported by migration library should not be preventing the kubeadm upgrade from proceeding if you use the `--ignore-preflight-errors=CoreDNSUnsupportedPlugins` flag, per [comment above](https://github.com/kubernetes/kubernetes/issues/82889#issuecomment-533256854).

**Comment by neolit123** [comment]
+1 Lets treat ignoring the error as the workaround users should do, for
this unsupported scenario.

/close

**Comment by chrisohaver** [comment]
Sounds good.  FWIW, The original reasoning for requiring the explicit ignoring of the pre-flight check was to make the user aware of the risk that proceeding with the upgrade could result in an invalid Corefile.  So, in that sense, its working as intended, but the error message is perhaps too cryptic.

_Currently_: "There are unsupported plugins in the CoreDNS Corefile"

_What was intended to be conveyed_: "There are plugin configurations in the CoreDNS Corefile that cannot be migrated.  Continuing with the upgrade without migrating those plugin configurations could result in an invalid Corefile and therefore DNS interruption."

**Comment by neolit123** [comment]
I think improving the message is fine or even enumerating which plugins.

**Comment by mxey** [comment]
Why was this closed? As I understand the issue, kubeadm fails to upgrade without additional options because of a configuration that was created by a previous kubeadm?

**Comment by neolit123** [comment]
> because of a configuration that was created by a previous kubeadm?

i don't believe this part is true.

the "hosts" plugin is not part of the kubeadm 1.16 manifests, so it's user added:
https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/phases/addons/dns/manifests.go#L313-L329

**Comment by mxey** [comment]
@neolit123 hosts is, but proxy was in the default: https://github.com/kubernetes/kubernetes/commit/c346ae1e49883852bda88bd429f2dcd42063548d#diff-81c5511bc26ac9a2e5cdf87b9d5da921

**Comment by neolit123** [comment]
the proxy plugin is mentioned as deprecated:
https://github.com/kubernetes/kubernetes/issues/82889#issuecomment-533256854

**Comment by mxey** [comment]
@neolit123 I know, but ignoring the preflight warning makes the upgrade go through just fine, including migration the ConfigMap. So what is the point of the warning?

**Comment by chrisohaver** [comment]
I think the migration logic in kubeadm checks the supportability of the current config in all versions from the starting point to the destination - hence kubeadm was alerting incorrectly about _proxy_, which would have been valid in the current version, but then deprecated/removed by the destination version.  It should instead check only the starting point - ensuring that there are no unsupported plugins present in the current version.

**Comment by neolit123** [comment]
@chrisohaver @rajansandeep please reopen this issue if you think there are PRs that we should sent.

**Comment by chrisohaver** [comment]
Yes after looking at the related code, it looks like kubeadm uses a "dry run" call to `migrate.Migrate()` in the preflight check to see if there are any unsupported plugins.  It should probably instead call `migrate.Unsupported()`, for the starting version only.

/reopen

**Comment by chrisohaver** [comment]
Something didn't seem right about my explanation above so I took a second look - looks like there are _two_ preflight checks.  One dry run call to `Migrate()`, _which is OK as is._  There is another preflight check, that calls `Unsupported()`. It is called with both the starting version and destination version, which checks if the existing config contains any plugins that are unsupported in any version from start to destination.  Instead it should be called with only the starting version.

**Comment by couloum** [comment]
> Sounds good. FWIW, The original reasoning for requiring the explicit ignoring of the pre-flight check was to make the user aware of the risk that proceeding with the upgrade could result in an invalid Corefile. So, in that sense, its working as intended, but the error message is perhaps too cryptic.
> 
> _Currently_: "There are unsupported plugins in the CoreDNS Corefile"
> 
> _What was intended to be conveyed_: "There are plugin configurations in the CoreDNS Corefile that cannot be migrated. Continuing with the upgrade without migrating those plugin configurations could result in an invalid Corefile and therefore DNS interruption."

Totally agree with that.
When I got the error, I did not know what to do. I had to go on google and hopefully found this post. I removed "proxy" module myself in configuration file, but the issue persisted. I had to look at the code to understand why I got this error. This is not something I should need to do.
Providing the list of unsuported modules would be a good starting point, because we would know why the preflight check is failing.
Also, a more explicit error message would be great as well. If I understand well, the message could be something like this: "There are plugin in the CoreDNS Corefile that are not supported by Kubeadm or are deprecated in the next release. Please, review your CoreDNS configuration against Changelog to ensure all your plugins are supported by the new version of CoreDNS" (English is not my native language, so you may found better formulation).

**Comment by chrisohaver** [comment]
Thanks, Just to summarize, there are two issues raised here:
1. There is a [bug](https://github.com/kubernetes/kubernetes/issues/82889#issuecomment-573717746) in kubeadm's CoreDNS configuration migration preflight check. When the _proxy_ plugin is in use, the preflight check falsely alerts that the _proxy_ plugin is not supported by the configuration migration _when in fact it is_ - the migration will automatically replace _proxy_ with the _forward_ plugin.
2. For plugins that are actually not supported by the configuration migrator (e.g. _hosts_ for now), the warning is cryptic and should be expanded/rephrased to more clearly convey the following:
   * The corefile contains plugins that kubeadm/CoreDNS does not know how to migrate. A list of those plugins should be provided in the preflight check message.
   *  To be safe, each plugin listed should be manually verified for compatibility with the newer version of CoreDNS.  Once ready, the upgrade can be initiated by skipping the preflight check. During the upgrade, kubeadm will migrate the configuration while leaving the listed plugin configs untouched, but cannot guarantee that they will work with the newer version of CoreDNS.
   * Perhaps a link to more detailed documentation if it gets too hard to succinctly explain this (could go in coredns/corefile-migration).
