### ISSUE TITLE
kubernetes.io/azure-file provisioner to add metadata to the persistent file share in azure (not just in the cluster).

### ISSUE THREAD

**Issue by tam203** [kubernetes/kubernetes#82881]
@kubernetes/sig-Storage-feature-requests
/sig Storage

**What would you like to be added**: 
I would like the `kubernetes.io/azure-file` provisioner to add metadata to the file share such as `KubernetesCluster`, `Name`, `kubernetes.io/created-for/pv/name`, `kubernetes.io/created-for/pvc/name`, etc. This would be in line with the behaviour of the `kubernetes.io/aws-ebs` provisioner that adds these metadata items as tags.

I have raised a StackOverflow questions on this but it seems that it is currently not possible (automatically) - 
https://stackoverflow.com/questions/57989186/when-creating-a-azurefile-persistent-volume-via-a-dynamic-persistent-volume-clai

**Why is this needed**:

It's very useful from a management and monitoring point of view. The best example I have is when we had an issue with our cluster and it was destroyed and re-build it. **Because there was** this metadata like `kubernetes.io/created-for/pvc/name` and because we had set the PVs to `Retain` we were able to reattach all the users home directories (it's a JupyterHub deployment) to the correct users. Without this metadata living with the persistent data outside of the cluster we would have lost our users home directories.  Not because the data was destroyed but because we would not know who's data is who's. We have moved to Azure and are using `kubernetes.io/azure-file` provisioner and I believe if the same issue occurred we would not be able to recover as we did using the `kubernetes.io/aws-ebs` provisioner.

**Comment by tam203** [comment]
P.s. If there is a desire in the community and it's an easy-ish issue I'd be happy to take a crack at it. I'm an experienced dev but never contributed to kubernettes or a go project.

**Comment by petermicuch** [comment]
This would really be helpful. E.g. https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client adds automatically namespace and PVC name into the NFS folder (e.g. namespace-pvc_name-pvc-8b769c34-e373-48af-a415-de91928db7b2). I would expect the same for kubernetes.io/azure-file provisioner. Otherwise finding the right one is really a pain.
