### ISSUE TITLE
A new API for updating prefilter calculations

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#82897]
**What would you like to be added**:
An interface that allows PreFilter plugins to update their state after PreFilter was called, similar to what we have for [predicates metadata (add/remove pods)](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go#L38-L41).

**Why is this needed**:
This is needed to allow efficient preemption simulations: during preemption, we remove/add pods from each node before running the filter plugins again to evaluate whether removing/adding specific pods will allow the incoming pod to be scheduled on the node. 

Roughly, a scheduling cycle with preemption works as follows (function names in the pseudo code below are made up):

- meta = ProduceMetadata(pod, nodes)
- For each nodeInfo in nodes
  - RunAllPredicates(pod, nodeInfo, meta)
- If preemption
  - for each nodeInfo in nodes   *// actual logic is in [selectVictimsOnNode](https://github.com/kubernetes/kubernetes/blob/master///pkg/scheduler/core/generic_scheduler.go#L1088:28)*
       - nodeInfoCopy, victimPods = RemoveLowerPriorityPods(nodeInfo)
       - metaCopy = meta
       - **metaCopy.RemovePods(victimPods)**
       - RunAllPredicates(pod, nodeInfoCopy, metadataCopy)

A number of predicates that we plan to migrate produce metadata, the most important of which are pod affinity and even pod spreading. The current predicate metadata interface requires implementing APIs for [adding and removing pods](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go#L38-L41).

In the scheduling framework, PreFilters will be used to compute what we currently call [predicate metadata](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go) in the scheduler, but the preemption logic currently have no way to call the plugin again to modify that state, and so we have two options:

**Option 1**: Call PreFilter again 
- pros: 
  - does not require changes to the framework
- cons:
  - harder to migrate current predicates because that is not how predicate metadata works
  - performance regression
  - change PreFilter semantics to indicate that it can be called multiple times on the same PluginContext and pod, making PreFilter trickier to implement.

**Option 2**: Allow PreFilter plugins to implement APIs to make incremental updates to its pre-computed state.
- pros: 
  - easier to migrate current predicates
  - no performance regression
  - no changes to PreFilter semantics, stays simple.
- cons:
  - need to add more logic to the framework core.

I suggest we go with option 2. Specifically, add two optional APIs to PreFilter, namely ```AddPod``` and ```RemovePod```.  By optional I mean similar to what we did for NormalizeScore API in Score Plugins.

/assign
/sig scheduling

**Comment by draveness** [comment]
I think we should start the discussion on this and update the KEP first.

> we should allow the plugin to do incremental update to its pre-computed state.

This seems like optimization to me. If it is, we should focus on the function of the scheduling framework in the alpha stage. And it would be better if we do such optimization after the feature bump to beta and the performance becomes a serious problem IMO.

**Comment by ahg-g** [comment]
> I think we should start the discussion on this and update the KEP first.
SG, this issue is for the discussion.

> 
> > we should allow the plugin to do incremental update to its pre-computed state.
> 
> This seems like optimization to me. If it is, we should focus on the function of the scheduling framework in the alpha stage. And it would be better if we do such optimization after the feature bump to beta and the performance becomes a serious problem IMO.

It is an optimization, but one that I think we can't afford to ignore because it will cause performance regression when migrating current predicates, especially pod affinity. I updated the description of the issue with more details and pros/cons of the two possible solutions.

**Comment by alculquicondor** [comment]
I have no concerns with option 2.

**Comment by draveness** [comment]
> it will cause performance regression when migrating current predicates

I was working on migrating the existing predicates and didn't meet this problem. Could you be more specific about which predicates would be hard to migrate with the current API and it would be better if we have benchmark numbers for this optimization.

**Comment by alculquicondor** [comment]
@draveness how do you update the metadata (`PluginContext` in framework terms) when pods are added/removed by the preemption algorithm?
Note that the current implementation of the framework was actually broken when it comes to preemption  #82842. The nodeinfo is modified, but the Filter plugins didn't have access to that modification.

**Comment by ahg-g** [comment]
> > it will cause performance regression when migrating current predicates
> 
> I was working on migrating the existing predicates and didn't meet this problem. 

You can't possibly have met this problem because we are not calling prefilter during preemption now. 

> Could you be more specific about which predicates would be hard to migrate with the current API 

This is explained in the updated description, any predicate that uses [predicate metadata](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go), examples include pod affinity and even pod spread.

> and it would be better if we have benchmark numbers for this optimization.

The optimization already exist in the current predicates implementation, so we are trying to preserve an existing behavior. Have you looked at [predicate metadata](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go#L38-L42)?

**Comment by Huang-Wei** [comment]
I'm leaning towards option 2.

During the implementation of EvenPodsSpread, the predicate metadata is extremely important to support not only its core function but also preemption. Upon migration to the scheduler framework, a pre-processed metadata is still inevitable to serve as fact-of-truth of that Filter Plugin.

@draveness Basically some simply plugins don't need the metadata too much, but some ones such as EvenPodsSpread and PodAffinity need to pre-know the state of the whole cluster (as they're related with topology domains rather than just nodes).

**Comment by ahg-g** [comment]
Note that if we don't provide those methods, we will have to call prefilter **for every node** during preemption cycle of a single pod, which is prohibitively expensive.

**Comment by ahg-g** [comment]
Another thing we have to add is support for cloning the PluginContext, and so we need to modify the [ContextData](https://github.com/kubernetes/kubernetes/blob/a2760c9c139d8f3efa6eaeb02a553c470362e8e5/pkg/scheduler/framework/v1alpha1/context.go#L30) interface to add a ```Clone``` method.

**Comment by alculquicondor** [comment]
I assume we clone metadata today already? Otherwise, how expensive could it be to (deep) clone PluginContext.

**Comment by ahg-g** [comment]
> I assume we clone metadata today already? 
Yes, we already clone it: https://github.com/kubernetes/kubernetes/blob/a2760c9c139d8f3efa6eaeb02a553c470362e8e5/pkg/scheduler/core/generic_scheduler.go#L584

> Otherwise, how expensive could it be to (deep) clone PluginContext.
Depends on what is stored in PluginContext. In a future iteration, we could provide a way to do selective of the keys, but for now lets just copy the whole thing as we do for metadata.

**Comment by Huang-Wei** [comment]
A side note on this: depending on the internal data structure design, some data structure (like `slice)` with data addition can be "shallow" copied, while other cases like `map` or data deletion are involved, we need to do "deep" copy.

**Comment by draveness** [comment]
> The optimization already exist in the current predicates implementation, so we are trying to preserve an existing behavior.

SG
