### ISSUE TITLE
Restart policy should be able to specify maximum running time (aka deadline)

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#829]
The restart policy mechansim specified in #127 should be able to specify a maximum running time for a container.  Restricting the running time of a task is a common requirement for a number of use-cases.  I propose that this should be a distinct restart policy - 'run until timeout', with a configurable timeout.  The range of workloads that could conceivably be run makes it hard to imagine what an appropriate default would be.  Any thoughts @smarterclayton @thockin @ironcladlou @ncdc ?

**Comment by bgrant0607** [comment]
I'd add a `StopAtTime` field to the pod. It shouldn't be part of the restart policy. It would be useful for evicting pods sort of gracefully in addition to bounding duration of run-once pods.

**Comment by bgrant0607** [comment]
@derekwaynecarr expressed interest in this, IIRC.

**Comment by derekwaynecarr** [comment]
I will synch up with @pmorie based on our chat at summit.  I think your recommendation is a good stop gap before we get a JobController and is something we would get value from having in the API.

**Comment by erictune** [comment]
Jobs have deadlines.  Job is the preferred way to run a pod that terminates.  Closing.
