### ISSUE TITLE
CRDs: OpenAPI validation of common formats

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#82901]
**What would you like to be added**:

Automatic validation of OpenAPI fields that contain common formats like IP addresses, dates and timestamps.

We would need to identify a list of common validations.

Validation of common formats should work well for native types and CRDs. We don't want to do something that just works for CRDs here.

**Why is this needed**:

Eliminates the need to add a validating webhook for a CRD just to do basic validation of common types.

/sig api-machinery
/area custom-resources
/priority important-longterm
/cc @liggitt @roycaihw @sttts @thockin

**Comment by irajdeep** [comment]
@jpbetz I would be interested in working on this

**Comment by roycaihw** [comment]
/assign @irajdeep

We need to check what formats are specified in JSON Schema and supported by the third party [validator](https://github.com/kubernetes/kubernetes/blob/ac8ac0fc170eec7cdf292d841f8d026a65ce1681/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go#L42) and test them. It looks like IP address (e.g. ipv4) is [supported](https://github.com/kubernetes/kubernetes/blob/ac8ac0fc170eec7cdf292d841f8d026a65ce1681/vendor/github.com/go-openapi/strfmt/format.go#L96-L169) already 

validation error message:
```
$ k apply -f bar.yaml 
The Bar "test-bar" is invalid: address: Invalid value: "a": address in body must be of type ipv4: "a"
```

**Comment by jpbetz** [comment]
This probably needs a short KEP.

We should also coordinate with the server side apply work. What we do for CRDs should also be well aligned with what we do for native types..

**Comment by irajdeep** [comment]
@jpbetz @roycaihw I am starting to write a short KEP for this issue. 

Just to confirm this validation would be a client-side validation right?

**Comment by liggitt** [comment]
> Just to confirm this validation would be a client-side validation right?

No, this would be done server-side

**Comment by roycaihw** [comment]
this is fixed by https://github.com/kubernetes/kubernetes/pull/85381

/close
