### ISSUE TITLE
Flexvolume binary mount succeed, but kubelet cannot observe mounted volume if there are too many files in the mount directory with fsGroup

### ISSUE THREAD

**Issue by sungjunyoung** [kubernetes/kubernetes#82918]
**What happened**: Flexvolume binary mount succeed, but kubelet cannot observe mounted volume if there are too many files in the mount directory when use `securityContext.fsGroup`

**What you expected to happen**: Mount succeed, Pod comes to `Running` state

**How to reproduce it (as minimally and precisely as possible)**: 
1. Write 3000 over files (with hierarchy) to the volume
2. Mount this volume by flexvolume plugin with `securityContext.fsGroup`

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/5b97b2860d9b490eba3325bb1e3ae0a748222d9d/pkg/volume/flexvolume/mounter.go#L96
Above code may be cause this kind of bug. Changing file owner group recursively takes long time if there are too many files.
```bash
[root@k8s-test.naver cephfs]# find ./ -type f | wc -l
2983
[root@k8s-test.naver cephfs]# time (chown root:101 -R ./)

real    0m30.811s
user    0m0.033s
sys     0m0.203s
```
This situation persists indefinitely, creating infinite pod directories (`/var/lib/kubelet/pods`) that can cause problems for nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.3
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`): 4.19.52-1.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chakri-nelluri** [comment]
@sungjunyoung This is not specific to Flexvolume and is similar to other in-tree plugins. Ping @msau42. This should also be similar for CSI drivers AFAIK.

**Comment by tedyu** [comment]
filepath.Walk() is used to iterate the mount directory.
I wonder if this call can be made asynchronous: we first walk one or two levels synchronously and if there is no error, perform the rest in goroutine.

**Comment by msau42** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/69699
