### ISSUE TITLE
Cronjobs not creating new jobs after considerable amount of time.

### ISSUE THREAD

**Issue by lukaszgryglicki** [kubernetes/kubernetes#82915]
**What happened**:
Cron jobs stopped creating new jobs after many days running OK. I have more than 100 cronjobs.

**What you expected to happen**:
Cronjobs should be created as usual.

**How to reproduce it (as minimally and precisely as possible)**:
Create, say, 150 cron jobs that create new job hourly. Leave it running for at least month, and finally observe that, for an unknown reason, no new pods are created, and every cronjob says AGE: 13h (which means 12 jobs were not created in a row for every cronjob).

**Anything else we need to know?**:
I think this can be related to successful jobs history log, more detailed description:
Does K8s really support `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` flags? I’m setting:
```
  schedule: 45 3 * * *
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
```
via `kubectl edit cronjob some-cronjob`, and then executing: `kubectl describe cj some-cronjob | grep History`:
```
Successful Job History Limit:  824645153596
Failed Job History Limit:      2
```
so `successfulJobsHistoryLimit`, setting to 2 or whatever returns: `824645153596`, while `failedJobsHistoryLimit` seems to work.

The problem is that I have 100+ cronjobs, and after some days, suddenly no new cron jobs are created, they should be created hourly but the last job was 13h old. When I’ve deleted and recreated cron jobs they’re back OK, but I’m afraid that after say 30 days, cronjobs won’t be created anymore. I suspect that it tries to hold `824645153596` successful results for each of 100+ cronjobs and that’s why it fails. To be funnier, I can see only the last 3 successful jobs for each cronjob, but maybe more of them are stored somewhere internally and block creating new jobs after some time?

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare metal server:
```
Linux node-0.k8s.devstats.cncf.io01 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
4 identical nodes packet.net's `m2.xlarge.x86`:
```
PROC: 2 x Intel Scalable Gold 5120 28-Core Processor @ 2.2GHzRAM384GB
DISK: 2 x 120GB SSD
DISK: 1 x 3.8TB NVME
NIC: 2 x 10Gbps Bonded Ports
```
Ubuntu 18.04 LTS.
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): `Linux master.k8s.devstats.cncf.io 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm` manually, this worked flawlessly for about 2 months, recreating cronjobs helped.
- Network plugin and version (if this is a network-related bug): default
- Others:

**Comment by lukaszgryglicki** [comment]
Is this @kubernetes/sig-architecture-bugs related issue? I think this is the closest SIG that I can find, please correct me if I'm wrong.

**Comment by Joseph-Irving** [comment]
How many jobs/cronjobs do you have in your cluster in total? there's a bug in 1.14 where if you go over 500 jobs/cronjobs, the cronjobs stop scheduling see https://github.com/kubernetes/kubernetes/issues/77465 there is a fix in v1.14.7

**Comment by lukaszgryglicki** [comment]
268 cronjobs now ... and I didn't have>= 500. But if speaking about jobs, not cronjobs - there could be up to 4x that number, because it held a history of 3 successful and 1 failed. So basically I should update K8s, right?
Is it possible to bump from v1.14 directly to v1.16?

**Comment by Joseph-Irving** [comment]
The general rule when upgrading Kubernetes is to only upgrade the masters one minor version at at time so you would go 1.14 -> 1.15 -> 1.16. The nodes (kubelet) are meant to be compatible with up to two kubernetes versions ahead, so a 1.14 node should work with a 1.16 master.

**Comment by lukaszgryglicki** [comment]
I've upgraded cluster from `v1.14.2` -> `v1.15.4` -> `v1.16.0`, I'll let you know if that happens again. Thanks for helping.
