### ISSUE TITLE
Enable strict serializers in components by default

### ISSUE THREAD

**Issue by obitech** [kubernetes/kubernetes#82924]
**What would you like to be added**:
With #76805 merged we should enable strict serializers in Kubernetes components:
- [x] kube-proxy (#82927)
- [x] kube-scheduler (#83030)
-  ~~kube-controller-manager~~ (not using a config file right now, see [enhancements#786](https://github.com/kubernetes/enhancements/issues/786) and [enhancements#1052](https://github.com/kubernetes/enhancements/pull/1052))
- [x] kubelet (#83204)

Lenient path implemented:
- [x] kube-proxy (#84143)
- [x] kube-scheduler (#84129)
- [x] kubelet (#83204)

With strict serializers enabled, an error will be thrown on things such as duplicate or unknown fields when parsing a YAML file.

**Why is this needed**:
This will improve code quality of user's configuration files as it enforces a proper configuration file to be present when starting a component.

**Comment by xiaoanyunfei** [comment]
Is this an issue for help ? I don't quite understand the rules.
If so, I can help on kubelet.

**Comment by obitech** [comment]
After discussion with @mtaufen and @rosti we agreed to always implement a lenient path with warnings first. This means we would prepare a scheme that has only the current version registered into it, as well as CodecFactory with non-strict decoding. This is then to be dropped when support for said version is dropped. See the discussion in #83204 for more information on the implementation.

Reasons are that many people depend on these configs already and we don't want to cause any production crashes without giving warnings first. Another reason is that currently  Kustomize needs a `metadata.name` field to be present for patches and right now users are adding a dummy `metadata.name` field so they can use Kustomize for component configs. However this would not be possible with strict decoding.
