### ISSUE TITLE
start apiserver error

### ISSUE THREAD

**Issue by anstns** [kubernetes/kubernetes#82937]
[root@iZj6c2fj4e2ampu34u8c1wZ kubernetes]# systemctl status kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-09-20 19:26:24 CST; 22s ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 16219 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─16219 /usr/bin/kube-apiserver --logtostderr=false --log-dir=/opt/logs/apiserver --v=4 --etcd-servers=https://172.31.248.231:2379,https://172.31.248.232:2379,https://172.31.248.233:2379 --bind-address=172.31.248.231 --secure-port=6443 --adve...

Sep 20 19:26:24 iZj6c2fj4e2ampu34u8c1wZ systemd[1]: Started Kubernetes API Server.
Sep 20 19:26:26 iZj6c2fj4e2ampu34u8c1wZ kube-apiserver[16219]: E0920 19:26:26.850065   16219 controller.go:154] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/17...ditionalErrorMsg:
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by tedyu** [comment]
The last line is an error log, Controller#Start should continue.

Do you observe other error(s) ?

**Comment by anstns** [comment]
> 最后一行是错误日志，Controller＃Start应该继续。
> 
> 您是否观察到其他错误？

No other errors were found.

**Comment by anstns** [comment]
> The last line is an error log, Controller#Start should continue.
> 
> Do you observe other error(s) ?

No other errors were found.

**Comment by liggitt** [comment]
The description shows the apiserver is running:
> Active: active (running) since Fri 2019-09-20 19:26:24 CST; 22s ago

The message about not removing old endpoints from the kubernetes service is non-fatal.

/close
