### ISSUE TITLE
Empty Azure VM scale sets consume vmss_list API needlessly

### ISSUE THREAD

**Issue by dharmab** [kubernetes/kubernetes#82948]
**What happened**:

One of our production Azure clusters was experiencing severe rate limiting. `increase(cloudprovider_azure_api_request_errors[3m])` showed hundreds of errors per minute, specifically for the vmss_list call.

This particular cluster had ten worker scale sets. We noticed that two of these scale sets were scaled to zero (they were running an older VM image we had migrated off of). We determined that we could safely delete these scale sets and deleted both of them. Finally, we did a rolling restart of the controller manager.

Immediately the rate limiting was fully relieved and no errors appeared in the metrics or cloud controller logs.

**What you expected to happen**:

vmss_list calls shouldn't be performed against empty scale sets, since the vmss_list call is subject to aggressive rate limiting. The `sku.capacity` property of the VM scale set should be checked first, and the vmss_list call should only be performed if the capacity is greater than zero.

**How to reproduce it (as minimally and precisely as possible)**:

Scale a worker scale set to zero and observe that vmss_list requests are still performed against it in the Azure API Activity Log and controller manager logs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: Azure (not AKS)
- OS (e.g: `cat /etc/os-release`): CoreOS 2191.4.1
- Kernel (e.g. `uname -a`): `Linux vmss-agent-worker0-11prodva7-baqwm00000W 4.19.66-coreos #1 SMP Mon Aug 26 21:06:50 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux`
- Install tools: custom internal tooling, broadly similar to AKS engine
- Network plugin and version (if this is a network-related bug):
- Others:

Cloud config:

```
cloud: AzurePublicCloud
cloudProviderBackoff: true
cloudProviderBackoffDuration: 5
cloudProviderBackoffExponent: 1.5
cloudProviderBackoffJitter: 1
cloudProviderBackoffRetries: 6
cloudProviderRateLimitBucket: 10
cloudProviderRateLimitQPS: 3
cloudProviderRatelimit: true
```

**Comment by dharmab** [comment]
@kubernetes/sig-cloud-provider-bugs

**Comment by jcrowthe** [comment]
Tagging @feiskyer who we had offline conversations with regarding this issue.

**Comment by feiskyer** [comment]
@dharmab  Thanks for reporting the issue.

/assign
