### ISSUE TITLE
kubectl: how to print a union of fields in custom-columns

### ISSUE THREAD

**Issue by myan9** [kubernetes/kubernetes#82950]
**What happened**:
I'd like to print a column which shows multiple information under one header, just like the one in events table:`Object:pod/eventgen`, but I can't reproduce this with custom-columns. I wonder if it's because my jsonpath is wrong, or kubectl puts restriction of  jsonpath usage in custom-columns. Thanks!!

Tried plain jsonpath in a specific event:
![屏幕快照 2019-09-20 下午1 49 49](https://user-images.githubusercontent.com/21212160/65347809-c4daa780-dbad-11e9-9e55-9a01611b9b18.png)

Tried custom-columns in the events table:
![屏幕快照 2019-09-20 下午1 50 41](https://user-images.githubusercontent.com/21212160/65347833-d754e100-dbad-11e9-94d6-0c931e937f43.png)

/sig cli

**Environment**:
- Kubernetes version (use `kubectl version`): client: 1.14, server: 1.14
- OS (e.g: `cat /etc/os-release`): macos

**Comment by hpandeycodeit** [comment]
@myan9 The following should work: 

```
kubectl get events -o custom-columns=Object:'.involvedObject.kind'/'.involvedObject.name'
```

**Comment by myan9** [comment]
@hpandeycodeit Thanks for your help! I got a column of ```<none>``` with your suggestion, so I guess this doesn't work...
