### ISSUE TITLE
CertificateSigningRequest and the root CA pubkey

### ISSUE THREAD

**Issue by costinm** [kubernetes/kubernetes#82952]
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

The note mentions that the CA that sings the CertificateSigningRequest may be different than the cluster CA. Typically ( at least on GKE ) the clusterCA is used.

This creates a number of problems:
- there is no way (that I found) to identify which CA signed the certificate. The signed certificate has the SHA of the public key of the root CA - but not the full public key ( it is not a chain, 
just the leaf cert)

- distribution of such key is problematic - creating a configmap in each namespace requires RBAC permissions, mounting, etc.

**What would you like to be added**:

Kubelet distributes the apiserver CA in a well-known location. If the Cluster signing public key is different from the cluster, it should be provided in a similar fashion. One option is to have 
the set of public keys in the same well-known location (bundle), which may also help in cases
of root cert rotation. 

Alternatively, the CA used by CertificateSigningRequest should also be used to sign the apiserve key ( possibly via an intermediate), and be the only CA that is distributed by kubelet.

Alternatively, the doc should be updated to remove the option of having 2 different root CAs.

**Why is this needed**:

As is I don't think the API is usable except in cases where 'dedicated' CA different from cluster CA is used. 

We are planning to use this API in Istio - to simplify the bootstrap and TLS for control plane - but
it won't work for dedicated CA. I assume most K8S installs use the same CA and it might not be a big issue, we  could test at install if the cluster CA matches and not support clusters with 'dedicated' CA.

**Comment by liggitt** [comment]
cc @mikedanese @deads2k 

there is also the possibility for different CSRs to be signed by different roots (e.g. one signer for in-cluster serving certificates, a different one for external hostname serving certificates, another one for client certificates, etc)

**Comment by costinm** [comment]
That's great - but if K8S has multiple entities signing certificates ( which will allow seemless integration with ACME or external CA or Vault ) - the signers should either use the internet CAs or have the public keys distributed by kubelet. It is otherwise impossible for a workload to know which CA are trusted.

**Comment by liggitt** [comment]
trust distribution is one of the items that needs to be resolved as part of bringing the CSR API to GA. See https://github.com/kubernetes/kubernetes/issues/69836

/close
closing this issue in favor of https://github.com/kubernetes/kubernetes/issues/69836

**Comment by costinm** [comment]
But until there is a solution for trust distribution - can the comment on the site be updated and instead make a recommendation to use the public key of apiserver ( which is already distributed ) ? 

Otherwise the feature is not usable, and we can't depend on it since on some clusters we might 
get certs without knowing the public key. When trust distribution is solved you can add back the comment and indicate how other root CAs are integrated.

**Comment by liggitt** [comment]
> But until there is a solution for trust distribution - can the comment on the site be updated and instead make a recommendation to use the public key of apiserver ( which is already distributed ) ?

I would not be in favor of that. It would harden incorrect assumptions about issuers. The only two scenarios in which the CSR API is used by kubernetes components today are for kubelets to request client and serving certificates. In both cases, the cluster administrator is responsible for distributing the signer to the kube-apiservers (in the `--client-ca-file` and `--kubelet-certificate-authority` bundles).

**Comment by deads2k** [comment]
> I would not be in favor of that. It would harden incorrect assumptions about issuers. The only two scenarios in which the CSR API is used by kubernetes components today are for kubelets to request client and serving certificates. In both cases, the cluster administrator is responsible for distributing the signer to the kube-apiservers (in the `--client-ca-file` and `--kubelet-certificate-authority` bundles).

I concur.  The only in-tree usage of CSR API is used today to provision kubelet client and serving certs.  Any relationship to a signer used to recognizing the in-cluster kube-apiserver serving cert is purely coincidental on a a per-distro basis, that is not the way it is designed.

**Comment by costinm** [comment]
Then document that the CSR API is not meant for user-space components and should be used only by kubelet. 

Right now there is nothing that I've seen that mark the CRD as internal-only.

**Comment by costinm** [comment]
My point is you can't have it both ways - if it is meant for apiserver and kubelet, document that explicitly so people don't attempt to use it for other things.

If it is a normal API that any app can use - there is no way to use it if the root CA is unknown. The only root CA that is currently available to pods is the apiserver CA.

**Comment by mikedanese** [comment]
Would you say that this concern is covered by "No clear way for signers to indicate/distribute trust roots for issued certs" from #69836 and "No guarantee on who trusts the certificate" from https://github.com/kubernetes/enhancements/pull/1097#discussion_r321007736? If so, we are tracking it. We are in a situation where the certificates API grew organically over a few years and the current form isn't well suited for all the uses it's grown into. Big picture, I'd like to see the Certificates API develop into something that can portably solve PKI needs of both infrastructure and user workloads but we aren't quite there yet. This is under active consideration in sig-auth though.

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/issues/63726 is also relevant.

**Comment by costinm** [comment]
Understood - however even as it is today, organically grown and all, the API is quite useful and can solve major usability problems for Webhooks  and systems like Istio. The main gap is just the documentation that states that unknown roots might sign the cert. If it is updated to recommend that only the apiserver cert ( distrubted by kubelet to all pods) will be used to sign for regular workloads -  the API can become quite useful now.

**Comment by costinm** [comment]
For the record - the current plan for Istio is to attempt to use this API as is, but verify if the cert is signed by the apiserver key. If it is - we'll use it, and enable use of SDS ( which is the protocol used by envoy to provision certificates). Otherwise we'll fallback to Citadel and mounted secrets.
