### ISSUE TITLE
kubectl get all not documented

### ISSUE THREAD

**Issue by pavgup** [kubernetes/kubernetes#82979]
**What happened**: `kubectl get all` is not documented therefore `kubectl get -h` provides no content about this hidden, but powerful option

**What you expected to happen**: `kubectl get -h` provides the "all" resource as, at least, an example.

**How to reproduce it (as minimally and precisely as possible)**: `kubectl get -h`

**Anything else we need to know?**: nada

**Environment**:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: `bare metal`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): 
```
Linux osboxes 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Thanks for the issue, but the `all` alias was intentionally removed fro documentation due to lots of user confusion about it not actually including all resources, and the inability to make it actually include all resources to to compatibility issues with scripts making use of it to do destructive things like deletion 

/close

**Comment by Yunir** [comment]
Then maybe to name it like `workloads` instead of all? Undocumented option is like a secret knowledge is not a good idea. 
k9s named the analogue of `kubectl get all` like `workloads`. 
Link :https://stackoverflow.com/questions/70742380/how-to-kubectl-get-all-in-k9s
