### ISSUE TITLE
kubeadm init --feature-gates panic

### ISSUE THREAD

**Issue by 41tair** [kubernetes/kubernetes#82978]
**What happened**:
kubeadm init --feature-gates get panic 
![image](https://user-images.githubusercontent.com/18530891/65382166-87068c00-dd31-11e9-8d01-05b35451eb5d.png)

**What you expected to happen**:
no panic
**How to reproduce it (as minimally and precisely as possible)**:
kubeadm init --feature-gates
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
@41tair 
what version of kubeadm are you using?

**Comment by neolit123** [comment]
cc @Arvinderpal
