### ISSUE TITLE
kubectl proxy and delete-context command should follow similar design pattern as other commands.

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#82970]
**What would you like to be added**:

Few days ago I watched this kubectl code base tour by @soltysh on Youtube
(https://www.youtube.com/watch?v=uz8TS3V9qqY). He talks about a design
pattern that almost every command follows. But I found out that some `kubectl` commands do not follow this design pattern.

- [x] `kubectl proxy`

- [ ] `kubectl config delete-context`

**Why is this needed**:

 All kubectl commands follow similar design pattern.

**Comment by luigi-riefolo** [comment]
@AnishShah can you provide an example of the desired functionality/change?

**Comment by zillani** [comment]
This request makes sense. Almost every kubectl command now has Options struct as this simplifies unit testing (I believe) and so they planned to use this pattern just like in, annotate.go, apply.go etc..
