### ISSUE TITLE
Going from single master to 3 masters triggers Fabric8 Java client watcher EOFException+reconnect

### ISSUE THREAD

**Issue by brentpearson** [kubernetes/kubernetes#82999]
I've got a Java application that uses the Fabric8 kubernetes-client to create a job, and then set a watch on it. I recently started seeing a new warning msg in the application log.

I'm using K8s 1.15.3 and kubernetes-client 4.5.2.

I have a K8s cluster with 3 master nodes and 1 worker/minion node (adding more, but was testing one first when I came across this issue). All are CentOs 7.7.

The Java application has been working without this warning for the past ~1.5 years, but I recently updated K8s from a 1 master node 1.13 cluster to a 1 master node 1.15.3 cluster. That required updating the client from 3.2.0 to 4.4.2. I *wasn't* seeing this warning at that point (with the 1 master 1.15.3 K8s), but then I updated my cluster to have 3 masters. The warning started then, so I tried updating the client to 4.5.2, but it's is still occurring.

So onto the actual issue.
I create the client object with:
```
    final Config config = new ConfigBuilder().withMasterUrl("MASTER_1_ADDRESS").build();
    final KubernetesClient client = new DefaultKubernetesClient(config);
```
I successfully create the job, get the job name, then set the watch with:
```
    public Watch createWatch(
        final String jobName, 
        final Watcher<io.fabric8.kubernetes.api.model.batch.Job> k8sJobWatcher)
    {
        return client.batch().jobs().withName(job.id).watch(k8sJobWatcher);
    }
```

The job successfully runs to completion, and my watch even gets all the updates, and my application runs fine, as being notified of the job completion goes.

However, I get this warning (and related msgs) in the log, repeating every 4 seconds until the job completes:
```
[WARN ][WatchConnectionManager][OkHttp MASTER_1_ADDRESS...] - Exec Failure
java.io.EOFException: null
        at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[okio-1.15.0.jar:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[okio-1.15.0.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[okhttp-3.12.0.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.12.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [okhttp-3.12.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [okhttp-3.12.0.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) [okhttp-3.12.0.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.12.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[DEBUG][WatchConnectionManager][OkHttp MASTER_1_ADDRESS...] - Submitting reconnect task to the executor
[DEBUG][WatchConnectionManager][scheduleReconnect|Executor for Watch 574252868] - Scheduling reconnect task
[DEBUG][WatchConnectionManager][scheduleReconnect|Executor for Watch 574252868] - Current reconnect backoff is 1000 milliseconds (T0)
[DEBUG][WatchConnectionManager][reconnectAttempt|Executor for Watch 574252868] - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@223a6744
[DEBUG][WatchConnectionManager][OkHttp MASTER_1_ADDRESS...] - WebSocket successfully opened
```

Any idea why this started happening? Could it be related to the client now talking to a load balancer instead of directly to a lone master?

If I reset the cluster and go back to a single master node the EOFException + watcher reconnect goes away.

**Comment by roycaihw** [comment]
Could you file an issue in the Fabric8 kubernetes-client repo? I wonder if this is a problem in the client. Is this producible with client-go?

**Comment by brentpearson** [comment]
I actually did that first, but it hasn't gotten any responses. Doesn't seem to be much activity over there.
https://github.com/fabric8io/kubernetes-client/issues/1773

I haven't tried it with the client-go... is that a Java client? I am using the io.kubernetes Java client as well as the Fabric8 one, so I will probably try switching the watch from Fabric8 to io.kubernetes and see if that works (although I'm think that that reason I'm using both is that io.kubernetes didn't support setting watches... could be wrong about that though).

**Comment by roycaihw** [comment]
[client-go](https://github.com/kubernetes/client-go) is a Golang client which is also used by Kubernetes itself. It looks like the io.kubernetes Java client supports [watch](https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java) as well
