### ISSUE TITLE
update the daemonSet default updateStrategy type to OnDelete

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#83007]
**What happened**:

the default DaemonSetUpdateStrategyType was changed to Ondelete by default, but the document still say that the default value was `RollingUpdate`

refer doc https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by hchenxa** [comment]
refer the code https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L506 for the default value of daemonset updateStrategytype

**Comment by Joseph-Irving** [comment]
The default update strategy for Daemonset should be `RollingUpdate` see here https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1/defaults.go#L72, I believe that code comment that you linked to is mistaken.

**Comment by danielqsj** [comment]
yep, I think the code comment is outofdate, I will fix it.
/assign
