### ISSUE TITLE
K8s node NotReady

### ISSUE THREAD

**Issue by HelenaZheng** [kubernetes/kubernetes#83002]
One of my nodes in K8S not ready， as below

10.40.24.49   NotReady   <none>    108d      v1.11.2

[root@idp-01-p2pi-k8s-node-10.40.24.49]#
[~]#journalctl -f -u kubelet
-- Logs begin at Wed 2019-08-14 20:57:07 WIB. --
Sep 20 15:22:42 ida-lj4700146 kubelet[3975]: I0920 15:22:42.117196    3975 fsHandler.go:135] du and find on following dirs took 3.445096248s: [/wls/docker/overlay2/8290844e67d76cab07ad40799b5d7a683741f72bca76f300f4235008c6f56b68/diff /wls/docker/containers/ff5223df126681b875f84903d808c47c3e17f247b8a52f0581fd892a7c976a36]; will not log again for this container unless duration exceeds 2s
Sep 20 15:22:48 ida-lj4700146 kubelet[3975]: I0920 15:22:48.607898    3975 fsHandler.go:135] du and find on following dirs took 5.240306653s: [/wls/docker/overlay2/6fde32e7cf69db03150dfb28d45dac681ad03d64cb0c055614e55876baa4e98e/diff /wls/docker/containers/895f6f5b66c3a9a604655250c02dbb83f2bc007dd19e7fe6d346955434e725bd]; will not log again for this container unless duration exceeds 4s
Sep 20 15:22:50 ida-lj4700146 kubelet[3975]: I0920 15:22:50.619735    3975 fsHandler.go:135] du and find on following dirs took 5.126140263s: [/wls/docker/overlay2/4645d15ce6197f1922d5ff42a86c3e63458510aeb712d24a04be6edb304cdad5/diff /wls/docker/containers/4cabf6aa0a96bae5c01ca5b674e7cb332bea6a8721925f2c8a8cbe6c9d0df152]; will not log again for this container unless duration exceeds 2s
Sep 20 15:22:51 ida-lj4700146 kubelet[3975]: I0920 15:22:51.025367    3975 fsHandler.go:135] du and find on following dirs took 3.149603807s: [/wls/docker/overlay2/8537526360f289f1a566ee76efcdcad10b35604920b912c87760b2ec5d33fc4e/diff /wls/docker/containers/874cf2f669565ca4d21fefa6e023c4f983b4e154c9011bc7c5ae577e542dd475]; will not log again for this container unless duration exceeds 2s
Sep 20 15:22:54 ida-lj4700146 kubelet[3975]: I0920 15:22:54.522455    3975 fsHandler.go:135] du and find on following dirs took 12.767930972s: [/wls/docker/overlay2/dedeea2a5371cdb65f39f21a8073479d429cff2f5c649fc859aae9be5810fc9d/diff /wls/docker/containers/da86613d8e1adb0dac363c5e68a7f69e7c2c5b7c4afa09ad06a7873a6d089322]; will not log again for this container unless duration exceeds 4s
Sep 20 15:23:07 ida-lj4700146 kubelet[3975]: I0920 15:23:07.259814    3975 fsHandler.go:135] du and find on following dirs took 7.434074205s: [/wls/docker/overlay2/0a9e60932809dcca3e149f670f6e0d90c2745ea825fec1f9b2c78dc9d6cbe8ab/diff /wls/docker/containers/d137873a1bbd04cd1adff6fe211285b3b9474c3aa5170dab92a90382f9b1c349]; will not log again for this container unless duration exceeds 2s
Sep 20 15:23:08 ida-lj4700146 kubelet[3975]: I0920 15:23:08.168196    3975 fsHandler.go:135] du and find on following dirs took 5.173957784s: [/wls/docker/overlay2/f5d0b92e3bf739a86efaa1cfe2526e0e759174fb271a9a14c05f86866293e2d7/diff /wls/docker/containers/29aff0e483e6796582e81653c3a442e7049adb6376ad0a9f7fd5765d67d57fe7]; will not log again for this container unless duration exceeds 3s
Sep 20 15:23:08 ida-lj4700146 kubelet[3975]: I0920 15:23:08.965189    3975 fsHandler.go:135] du and find on following dirs took 3.868806255s: [/wls/docker/overlay2/15c1b4ff3c4a794f03300900c5a49db3f9f7996de70d69238ec13f453e882400/diff /wls/docker/containers/58eeac8e51ba10bf61f6f5f760347b8271fcd033fb69876bd0854fb83cfdb68c]; will not log again for this container unless duration exceeds 2s
Sep 20 15:23:09 ida-lj4700146 kubelet[3975]: I0920 15:23:09.464855    3975 fsHandler.go:135] du and find on following dirs took 4.368483284s: [/wls/docker/overlay2/ff1edcdeec2882fcf88c3da2374cc0d74a1172304d21084cdbaed9a13c6862f5/diff /wls/docker/containers/5e792874c4d2e83bdeb2cdb855da2bebf38ac507c9554fb6f078afaecbbae82b]; will not log again for this container unless duration exceeds 2s
Sep 20 15:23:09 ida-lj4700146 kubelet[3975]: I0920 15:23:09.466895    3975 fsHandler.go:135] du and find on following dirs took 4.444609977s: [/wls/docker/overlay2/c3f1d0f18102c2ecb035f69d514c25e107adb1cbd71af23f634a3a8b1e551f96/diff /wls/docker/containers/004628151bd749c122702438db0bb38dbc03428df9f45f68acaaac018053d680]; will not log again for this container unless duration exceeds 2s
^C
[root@idp-01-p2pi-k8s-node-10.40.24.49]#

**Comment by HelenaZheng** [comment]
@/sig Node
@kubernetes/sig-Node-NotReady

**Comment by HelenaZheng** [comment]
I restart the kubelet service， the node status change to Ready.
But I do not know what cause the node not ready.
Can anybody find out?

**Comment by zouyee** [comment]
may be apiserver connection break

**Comment by HelenaZheng** [comment]
@zouyee 
@/sig Node

I telnet the apiserver on the node, is ok. Is this can be think the connection between the node and apiserver  is ok?

And I found some other log

kubelet[3975]: ' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"read init-p: connection reset by peer\": unknown\r\n"
