### ISSUE TITLE
Regression of watch bookmarks

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#83016]
It seems that again we started sending waaaay more watch bookmarks:
http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadInitEventsCount&resource=*core.Secret

The regression happened between these two runs:
https://github.com/kubernetes/kubernetes/compare/c7c89f8c6...84fe3db5c

@kubernetes/sig-scalability-bugs 
@mm4tt

**Comment by mm4tt** [comment]
It correlates with enabling secrets in gce-5K - https://github.com/kubernetes/test-infra/pull/14189

**Comment by wojtek-t** [comment]
Yes. So this probably explains it.
We basically create O(15k) secrets during roughly 4 hours - so O(1) secret per second on average.
Given we send bookmark ~2s before closing watch, there are two event happening between this and when watch is restarted.

So given we have O(150k) watches (for default accounts) [well, the number is growing over time from zero as we create pods], and we restart watch every 7.5 minute on average, that would give us O(6M) init events for the first 5 hours of the test.
The graph is reporting O(10M), so we're with the same ballpark here.

So this is actually working as intended.
