### ISSUE TITLE
Simplify Installation of K8s

### ISSUE THREAD

**Issue by sjkeerthi** [kubernetes/kubernetes#83012]
**Kubernetes Installation Make Easy**:

**I feel lets make to improve the Kubernetes installation little easy rather doing to many stuff in too many nodes of commands.*:

How Can we approach:

I feel that writing up a config file of which node to be controlplane / etcd / worker and Type of Network with Kube-install up should do all the necessary install on the nodes

To add worker node just update the same config file and then do kube-install update should do the node. 

We are been add more and more features inside the Kubenetes but to use them and if every one to adopt, I believe the installation should be simply that bring more users to convert there own DataCenter to kubernetes with fear less.

Why do we want the Kubernetes installation to make complete way.

Let Vote if any one really want this ticket to Consider in the community

**Comment by neolit123** [comment]
hi, that is why projects like kubeadm, kind, kops, cluster-api and minikube exist.
your feature requests is already being tackled by these projects.

/sig cluster-lifecycle
/close
