### ISSUE TITLE
kubelet service not Runing -- kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)

### ISSUE THREAD

**Issue by HelenaZheng** [kubernetes/kubernetes#83044]
The k8s node not Running, I found the kubelet service not running. 

@/sig Architecture
@/sig Node
@/sig K8s Infra

KB rss:700KB rss_huge:0KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:700KB inactive_file:40KB active_file:36KB unevictable:0KB
Sep 20 15:21:56 ida-lj4700146 kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Sep 20 15:21:56 ida-lj4700146 kernel: [ 6433]     0  6433      254        1       4        0          -998 pause
Sep 20 15:21:56 ida-lj4700146 kernel: [ 1092]   602  1092    27093      391      15        0           978 sh
Sep 20 15:21:56 ida-lj4700146 kernel: [ 1201]     0  1201    25780      195      12        0           978 chown
Sep 20 15:21:56 ida-lj4700146 kernel: [ 1249]     0  1249     4977      812      17        0           978 runc:[2:INIT]
Sep 20 15:21:56 ida-lj4700146 kernel: Memory cgroup out of memory: Kill process 1249 (runc:[2:INIT]) score 978 or sacrifice child
Sep 20 15:21:56 ida-lj4700146 kernel: Killed process 1249 (runc:[2:INIT]) total-vm:19908kB, anon-rss:2716kB, file-rss:532kB, shmem-rss:0kB
Sep 20 15:21:56 ida-lj4700146 dockerd[3171]: time="2019-09-20T15:21:56.656633371+07:00" level=error msg="stream copy error: reading from a closed fifo"
Sep 20 15:21:56 ida-lj4700146 dockerd[3171]: time="2019-09-20T15:21:56.657904907+07:00" level=error msg="stream copy error: reading from a closed fifo"
Sep 20 15:21:56 ida-lj4700146 dockerd[3171]: time="2019-09-20T15:21:56.674603041+07:00" level=error msg="Error running exec ca14ed914fdb65c95e22d5aa5dd00c40612e17c517e183d2a5872b6c5f31a2d0 in container: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"read init-p: connection reset by peer\": unknown"
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: I0920 15:21:56.675322    3975 handlers.go:62] Exec lifecycle hook ([bash -c sleep 60 && /home/wls81opr/bin/tomcatctl $APPNAME stop]) for Container "wmc-amp-srv" in Pod "wmc-amp-srv-54497f94b6-p8dnf_idp-02(fc49d55b-a9c8-11e9-8b57-fa163ea8ee45)" failed - error: command 'bash -c sleep 60 && /home/wls81opr/bin/tomcatctl $APPNAME stop' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"read init-p: connection reset by peer\": unknown\r\n"
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: E0920 15:21:56.675350    3975 kuberuntime_container.go:466] preStop hook for container "wmc-amp-srv" failed: command 'bash -c sleep 60 && /home/wls81opr/bin/tomcatctl $APPNAME stop' exited with 126:
Sep 20 15:21:59 ida-lj4700146 kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Sep 20 15:21:59 ida-lj4700146 kernel:   cache: kmalloc-1024(5668:c8b5a542e04688a32abbfb47b391c9170ef08ddc611bdd8e2fca00070b4df8b3), object size: 1024, buffer size: 1024, default order: 3, min order: 0
Sep 20 15:21:59 ida-lj4700146 kernel:   node 0: slabs: 7, objs: 224, free: 0
Sep 20 15:21:59 ida-lj4700146 kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Sep 20 15:21:59 ida-lj4700146 kernel:   cache: kmalloc-1024(5668:c8b5a542e04688a32abbfb47b391c9170ef08ddc611bdd8e2fca00070b4df8b3), object size: 1024, buffer size: 1024, default order: 3, min order: 0

**Comment by HelenaZheng** [comment]
@/sig Architecture
@/sig Node
@/sig K8s Infra

#du -sh /wls/docker/overlay2/5c7105ac9ffea5fc430efd8b17efbfeb75f0ab1ca65dcaf4a4c512ad31a9d8a5/diff /wls/docker/containers/8af95b66e758dbaebd0e3d279245f1131e46ed0357bd87da848a0da246486bca
du: cannot access ‘/wls/docker/overlay2/5c7105ac9ffea5fc430efd8b17efbfeb75f0ab1ca65dcaf4a4c512ad31a9d8a5/diff’: No such file or directory
du: cannot access ‘/wls/docker/containers/8af95b66e758dbaebd0e3d279245f1131e46ed0357bd87da848a0da246486bca’: No such file or directory

**Comment by HelenaZheng** [comment]
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: ' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"read init-p: connection reset by peer\": unknown\r\n"
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: I0920 15:21:56.593204    3975 kuberuntime_container.go:553] Killing container "docker://c8b5a542e04688a32abbfb47b391c9170ef08ddc611bdd8e2fca00070b4df8b3" with 300 second grace period
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: I0920 15:21:56.607100    3975 kubelet.go:1882] SyncLoop (PLEG): "wmc-amp-srv-54497f94b6-p8dnf_idp-02(fc49d55b-a9c8-11e9-8b57-fa163ea8ee45)", event: &pleg.PodLifecycleEvent{ID:"fc49d55b-a9c8-11e9-8b57-fa163ea8ee45", Type:"ContainerStarted", Data:"c8b5a542e04688a32abbfb47b391c9170ef08ddc611bdd8e2fca00070b4df8b3"}
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: I0920 15:21:56.675322    3975 handlers.go:62] Exec lifecycle hook ([bash -c sleep 60 && /home/wls81opr/bin/tomcatctl $APPNAME stop]) for Container "wmc-amp-srv" in Pod "wmc-amp-srv-54497f94b6-p8dnf_idp-02(fc49d55b-a9c8-11e9-8b57-fa163ea8ee45)" failed - error: command 'bash -c sleep 60 && /home/wls81opr/bin/tomcatctl $APPNAME stop' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"read init-p: connection reset by peer\": unknown\r\n"
Sep 20 15:21:56 ida-lj4700146 kubelet[3975]: E0920 15:21:56.675350    3975 kuberuntime_container.go:466] preStop hook for container "wmc-amp-srv" failed: command 'bash -c sleep 60 && /home/wls81opr/bin/tomcatctl $APPNAME stop' exited with 126:

**Comment by HelenaZheng** [comment]
Sep 20 15:21:59 ida-lj4700146 kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x20)
Sep 20 15:21:59 ida-lj4700146 kernel:   cache: kmalloc-1024(5668:c8b5a542e04688a32abbfb47b391c9170ef08ddc611bdd8e2fca00070b4df8b3), object size: 1024, buffer size: 1024, default order: 3, min order: 0

**Comment by xigang** [comment]
The limit of the pod container memory cgroup is set to 8G, but the program only uses 400M, and the process is OOM.

contianer memory cgroup limit:
```
cat /sys/fs/cgroup/memory/kubepods/burstable/pod0046bc29-1636-11ea-ab85-fa163e904f35/6232a31aa008cc426bae5557687d53468f64c8a76049aa87ccbca1c670871e7d/memory.limit_in_bytes
8388608000
```

contianer memory cgroup usage:
```
at /sys/fs/cgroup/memory/kubepods/burstable/pod0046bc29-1636-11ea-ab85-fa163e904f35/6232a31aa008cc426bae5557687d53468f64c8a76049aa87ccbca1c670871e7d/memory.usage_in_bytes
451563520
```

dmesg -Tw system logs:

```
at /sys/fs/cgroup/memory/kubepods/burstable/pod0046bc29-1636-11ea-ab85-fa163e904f35/6232a31aa008cc426bae5557687d53468f64c8a76049aa87ccbca1c670871e7d/memory.usage_in_bytes
451563520
```

What causes this problem?

**Comment by haosdent** [comment]
this error looks like memory problem. can try to latest stable kernel first.

**Comment by xigang** [comment]
@haosdent 
The free command shows that the system has a lot of available memory, but it cannot allocate memory through malloc. It is suspected that the kernel memory leaks.

Execute the following command:
```
sync
echo 3 > /proc/sys/vm/drop_caches
```
Process can allocate memory normally. But the specific problems have not been identified.

**Comment by haosdent** [comment]
yep, I encounter similar problem as well, it not related to kubernetes' problem. Related to cgroup bug, can try the latest stable kernel version.

**Comment by HelenaZheng** [comment]
@haosdent
when I restart the kubelet service, the problem not happend. Do I need try the latest kernel version.
