### ISSUE TITLE
namespaces status is Terminating,but resources is running,Pod status was running

### ISSUE THREAD

**Issue by bjliyp** [kubernetes/kubernetes#83053]
**What happened**:
We found that one of the namespaces in our k8s cluster has suddenly changed to Terminating, but all the resources in it are in normal use, and pod is running. Now I don't know why the namespaces have changed to Termination. Could you please tell me if there is any direction to address this problem?

**Environment**:
- Kubernetes version (use `kubectl version`):v1.11.3
- OS (e.g: `cat /etc/os-release`):CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):3.10.0-693.el7.x86_64

**Comment by liggitt** [comment]
That means a delete request was issued against the namespace. The API server log or the [audit log](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) (if you have it enabled) can be used to determine when the namespaces deleted and by who.

/close
