### ISSUE TITLE
Allow updating the Spec.Container.Command

### ISSUE THREAD

**Issue by chmouel** [kubernetes/kubernetes#83059]
**What would you like to be added**:

As stated by the error we are not able to change a Container entrypoing  in the spec  : 

```
invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image
```

We would like to know if there is a rational denying a modification of an Entrypoint

**Why is this needed**:

As the error says we do allow changing the Image name but when we change the image name the argument of the new image can/should be different and it would be great if we can modify it as the new image name would not work without.

We use the modification of the image name for our sidecar functionality in tektoncd, cf :  

https://github.com/tektoncd/pipeline/issues/1347

**Comment by liggitt** [comment]
In retrospect, allowing the image to be modified was likely a mistake. Immutability of pods is a desirable property. Running a completely different command is generally a good reason to roll out another pod, not rewrite an existing pod.
