### ISSUE TITLE
How to cleanup unused containers and images?

### ISSUE THREAD

**Issue by HardySimpson** [kubernetes/kubernetes#8305]
I've seen many issuses about that, but none solve it.  like https://github.com/GoogleCloudPlatform/kubernetes/issues/1148

Maybe it is a problem docker should solve. Here is my solution:

```
# cat docker.cleanup.sh 
#!/bin/sh

docker ps -a -q | while read cid
do
    fini=$(docker inspect $cid | grep FinishedAt | awk -F\" '{printf("%.19s", $4)}')
    diff=$(expr $(date +"%s") - $(date --date="$fini" +"%s"))    
    echo $diff
    if [ $diff -gt 86400 ]
    then
        docker rm $cid
    fi 
done

docker rmi $(docker images -a)
```

It deletes containers that stopped before 1 day, and all unused images. 

Hope it helps

**Comment by HardySimpson** [comment]
This shell has some bugs, I put a good one on https://github.com/HardySimpson/docker-cleanup

**Comment by vmarmol** [comment]
@HardySimpson are you running into disk is full issue on Kubernetes nodes? The Kubelets have cleanup policies that delete old containers and images which should prevent that from happening. Are you still seeing issues?

**Comment by yujuhong** [comment]
Whether the disk is full or not, I think it'd be an optimization if we teach container GC to delete all containers associated with deleted pods (or to directly remove the containers in killPod). There is no need to keep these containers around since user can no longer find the pod. I considered doing that, but didn't get to it :)

**Comment by vmarmol** [comment]
The argument for keeping those around is for the logs of the pod, although I don't know if we can even query the logs of a dead pod...if we can't then yeah we can just clean them up. You can file an issue @yujuhong so we don't forget :)

**Comment by yujuhong** [comment]
Filed #8134 

@vmarmol, kubelet cannot locate the container if the pod has been deleted, so no, user cannot query kubelet for logs in such cases. Of course, they could read kubelet.log, identify the container id, and manually ask docker (or any other container runtime) for the log. But I am guessing that once a pod has been deleted, we don't really guarantee anything.

**Comment by HardySimpson** [comment]
@vmarmol, I heard about kubelet can clean up  old containers and images, but how to config or start it? Is there any docs or links? thanks

**Comment by HardySimpson** [comment]
I see this:

```
	fs.DurationVar(&s.MinimumGCAge, "minimum-container-ttl-duration", s.MinimumGCAge, "Minimum age for a finished container before it is garbage collected.  Examples: '30
0ms', '10s' or '2h45m'")
	fs.IntVar(&s.MaxPerPodContainerCount, "maximum-dead-containers-per-container", s.MaxPerPodContainerCount, "Maximum number of old instances of a container to retain pe
r container.  Each container takes up some disk space.  Default: 5.")
	fs.IntVar(&s.MaxContainerCount, "maximum-dead-containers", s.MaxContainerCount, "Maximum number of old instances of a containers to retain globally.  Each container t
akes up some disk space.  Default: 100.")
```

So, the policies of kubelet cleanup is that 
1. a stop container will be removed after the `minimum-container-ttl-duration`
2. if on one node there is more than `maximum-dead-containers`, will trigger kubelet remove containers  until there are 100 dead containers

But, how kubelet cleanup old images? And what is the meaning of `maximum-dead-containers-per-container`, does it mean `maximum-dead-containers-per-image`?

**Comment by vmarmol** [comment]
@HardySimpson it seems like I should write a document about it since it is a question we get somewhat frequently :) Filed #8416.

What you've described is correct. Also, `maximum-dead-containers-per-container` is the number of dead containers allowed per container in your pod. So if your pod has 2 containers, each of those will be allowed to have up to MAX-NUM dead containers which we keep around for logs and exit status.

**Comment by HardySimpson** [comment]
Thanks I've seen the code yesterday afternoon. `maximum-dead-containers-per-pod-container` maybe a better name...still it is too long...

**Comment by vmarmol** [comment]
Ah, that is a better name :)

**Comment by yujuhong** [comment]
Closing this issue since #8416 is intended for documentation.

**Comment by mnuttall** [comment]
Today I found that `docker rmi $(docker images --filter "dangling=true" --format "{{.ID}}")` does the trick

**Comment by arpitjindal97** [comment]
For those who want to remove old containers created by `minikube` after every start

`docker ps -a | awk '/Exited/ {print $1}' | xargs docker rm`

**Comment by BruceShenC** [comment]
how about run docker system prune?

**Comment by eyz** [comment]
It appears that if an exited Kubernetes pod init container is pruned / removed it will be started again by Kubernetes. Is this the correct behavior? It results in pods being unready while the init containers launching/running again once they are pruned away.

**Comment by giladsh1** [comment]
I would suggest 
`docker container prune`
