### ISSUE TITLE
Columns missing from kubectl get events watch

### ISSUE THREAD

**Issue by taisph** [kubernetes/kubernetes#83056]
**What happened**:

Running `kubectl get events --all-namespaces --watch` shows the usual initial events with the usual columns like message, kind, reason etc. But all events printed after those only show the namespace, name and age column which are useless on their own.

**What you expected to happen**:

Prior to kubectl 1.16.0 the initial columns and the watched events where identical. I expected this to be the same with 1.16.

**How to reproduce it (as minimally and precisely as possible)**:

Run `kubectl get events --all-namespaces --watch` with version 1.16 and an older version.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.15", GitCommit:"b48a8d693e191192e27c2f807daa51b54d0b0a61", GitTreeState:"clean", BuildDate:"2019-08-12T17:49:30Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

I've verified it works with older kubectl:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:50:59Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.15", GitCommit:"b48a8d693e191192e27c2f807daa51b54d0b0a61", GitTreeState:"clean", BuildDate:"2019-08-12T17:49:30Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

GCP/GKE

**Comment by liggitt** [comment]
Kubectl uses capabilities added to the server in 1.15 (in https://github.com/kubernetes/kubernetes/pull/71548). Kubectl currently supports +/- 1 version of skew from the server, so upgrading to a 1.15 server would allow displaying full event output with --watch 

/close
