### ISSUE TITLE
Pause container got deleted but main container in Pod still run

### ISSUE THREAD

**Issue by pdhung** [kubernetes/kubernetes#83068]
@kubernetes/sig-node-bugs @kubernetes/sig-api-machinery-bugs

Hi everyone,

During some maintenance of our kubernetes cluster, I have noticed that there are some pods that have orphaned pod containers; meaning their main Docker containers are running, but there is no corresponding pause container. 

Some background info:
- _kubectl_ get pods doesn't show info about this pod, so it seems to have been deleted by kubernetes
- Our users do not have access to docker daemon to delete container individually
- _ps -aux_ hang when run on the worker with orphaned pod containers

My question is: how can such a situation happen? 

I have read https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods but I am still confused. One of my guess is the main containers stuck in uninterruptible (D) state, but cannot check since running _ps_ hangs

Docker info:
Server Version: 19.03.2
 Storage Driver: devicemapper
  Pool Name: rhel-docker

Kubernetes version 1.15.3. Cluster is HA with 3 nodes for controlplane and etcd; 8 nodes for workers.

The pod that has this problem is:
- The init process (pid 1) is _tini_ , which:
- Run java (elasticsearch) with min heap (Xmx) 5G and max heap (Xms) 15G
- Pod resources limit: 15G memory and 4 CPUs and have a PV Ceph RBD attached
- User has reported that when the heap size of Java shot up to near 15G, the Pod was actually not OOMkilled, but in a weird state (running but not responsive) and they have deleted it with --force and --grace-period=0 flag

**Comment by tedyu** [comment]
Can you give information about your deployment environment and k8s version ?

Thanks

**Comment by pdhung** [comment]
@kubernetes/sig-node-bug @kubernetes/sig-api-machinery-bug

**Comment by pdhung** [comment]
@tedyu: we are using docker 19.03.2 and k8s 1.15.3. k8s Cluster is HA with 3 nodes for controlplane and etcd; 8 nodes for workers.

The pod that has this problem is:
- The init process (pid 1) is _tini_ , which:
- Run java (elasticsearch) with min heap (Xmx) 5G and max heap (Xms) 15G
- Pod resources limit: 15G memory and 4 CPUs and have a PV Ceph RBD attached
- User has reported that when the heap size of Java shot up to near 15G, the Pod was actually not OOMkilled, but in a weird state (running but not responsive) and they have deleted it with --force and --grace-period=0 flag

**Comment by pdhung** [comment]
@kubernetes/sig-node-bugs @kubernetes/sig-api-machinery-bugs

**Comment by rshiva777** [comment]
/reopen

I have deleted pods running on a particular node and using kubectl pods are not showing.

But inside the node using docker ps, i am able to see the containers are still running

**Comment by rshiva777** [comment]
I have deleted pods running on a particular node and using kubectl pods are not showing.

But inside the node using docker ps, i am able to see the containers are still running
