### ISSUE TITLE
git-sync container in contrib/git-sync/ keeps restarting

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#8307]
I followed the instructions in cotrib/git-sync/demo/README.md, but when I try to access the external IP, I got ERR_CONNECTION_RESET.

'kubectl get pods' shows the git-sync container terminated with exit code 0. 'kubectl describe' shows the git-sync container is repeatedly being recreated. 'docker logs' show
```
2015/05/15 06:34:30 fetch "master": From https://github.com/GoogleCloudPlatform/kubernetes
 * branch            master     -> FETCH_HEAD
2015/05/15 06:34:30 reset "HEAD": HEAD is now at a91a7bf Merge pull request #8265 from pmorie/e2e
2015/05/15 06:34:30 wait 0 seconds
2015/05/15 06:34:30 done
```
which seems normal to me.

@proppy, could you help? Thank you.

**Comment by proppy** [comment]
The `git-sync` exits to "periodically" sync the git repo, you can configure the period with the `GIT_SYNC_WAIT` env var.

The service will map to the port of the nginx container in the same pod, can you double check if the nginx container is running, and try to curl it directly using the pod IP?

Then double check than the service labels query match one of those pods.

**Comment by caesarxuchao** [comment]
Thank you @proppy. nginx container seems to be running properly. A directly curl shows the html of
```
example blog

An elegant open source and mobile first theme for hugo made by @mdo. Originally made for Jekyll.
```

The service selector does match the pod label. 

It seems the problem is the service. I will dig deeper tomorrow. Thanks again.

**Comment by goltermann** [comment]
This appears fixed, please reopen if not.
