### ISSUE TITLE
Windows: Pod's Source IP address is not preserved when connecting to another pod through a Service Cluster IP

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#83072]
**What happened**:

When connecting a Pod to another Pod through a Kubernetes Cluster Service, the client Pod's IP is not preserved, and instead, the Client IP seems to be the Pod's host node IP.

This can cause some tests to fail:

    should preserve source pod IP for traffic thru service cluster IP
    should create and stop a working application

**What you expected to happen**:

Pod's IP should be preserved, even if a Kubernetes Cluster service is used instead of direct Pod IP.

**How to reproduce it (as minimally and precisely as possible)**:

    kubectl create -f example.yaml  # https://paste.ubuntu.com/p/KwXwD4DKwS/
    kubectl exec -n test-ns execpod-sourceip -- curl.exe -s sourceip-test:8080/clientip
    # the result of the above command will be a node's IP, which can be seen here:
    kubectl get nodes -o wide

    # the result above can be compared to when the Pod's IP is used directly.
    kubectl exec -n test-ns execpod-sourceip -- curl.exe -s ${ECHO_SERVER_POD_IP}:8080/clientip

**Anything else we need to know?**:

/sig windows

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`):
- Install tools: aks-engine v0.39.1
- Network plugin and version (if this is a network-related bug): azure-vnet-cni v1.0.22
- Others:

**Comment by daschott** [comment]
These tests should pass on DSR
