### ISSUE TITLE
[Azure] EnsureHostInPool TooManyRequests

### ISSUE THREAD

**Issue by ArchangelSDY** [kubernetes/kubernetes#83073]
**What happened**:
Recently we upgraded our cluster from 1.14.4 to 1.14.7. Then we started to observe tons of following errors:
```
E0924 07:21:12.021680       1 service_controller.go:219] error processing service ingress-nginx/ingress-nginx126 (will retry): failed to ensure load balancer for service ingress-nginx/ingress-nginx126: [EnsureHostInPool(ingress-nginx/ingress-nginx126): backendPoolID(/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/loadBalancers/srprodacseastusb/backendAddressPools/***) - failed to ensure host in pool: "compute.VirtualMachineScaleSetVMsClient#Get: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\"OperationNotAllowed\" Message=\"The server rejected the request because too many requests have been received for this subscription.\" Details=[{\"code\":\"TooManyRequests\",\"message\":\"{\\\"operationGroup\\\":\\\"GetVMScaleSetVM3Min\\\",\\\"startTime\\\":\\\"2019-09-24T07:21:11.6439379+00:00\\\",\\\"endTime\\\":\\\"2019-09-24T07:23:11.6439379+00:00\\\",\\\"allowedRequestCount\\\":500,\\\"measuredRequestCount\\\":534}\",\"target\":\"GetVMScaleSetVM3Min\"}] InnerError={\"internalErrorCode\":\"TooManyRequestsReceived\"}", .....
```

I guess the cause may be related to this line which was introduced recently:
https://github.com/kubernetes/kubernetes/blob/6f0f05150028dcaad4c3b5001d84b230502c16e6/pkg/cloudprovider/providers/azure/azure_vmss.go#L805

As we have hundreds of services with LoadBalancer type, and we also enable cluster-autoscaler, the nodes list change very often. For each service, there will be one call to GetScaleSet. The quota will be exhausted quickly. When `EnsureHostInPool` fails, new nodes created by cluster-autoscaler will lose connectivity to load balancer.

**What you expected to happen**:
Kubernetes should not hit VMSS throttling threshold.

**How to reproduce it (as minimally and precisely as possible)**:
1. Provision a cluster with aks-engine. Use VMSS.
2. Create 200 services with LoadBalancer type.
3. Scale up VMSS to 50 nodes
4. Scale down VMSS to 60 nodes
5. Repeat scaling up and down VMSS

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.7
- Cloud provider or hardware configuration: Azure, VMSS
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nilo19** [comment]
https://github.com/kubernetes/kubernetes/pull/85885

I create a PR to mitigate the issue.

**Comment by andyzhangx** [comment]
> #85885
> 
> I create a PR to mitigate the issue.

@nilo19 do we have a rough num about how this PR would mitigate this issue? looks like we need to  cherry-pick this PR to old releases. it's better if we have a rough estimation.

**Comment by nilo19** [comment]
> > #85885
> > I create a PR to mitigate the issue.
> 
> @nilo19 do we have a rough num about how this PR would mitigate this issue? looks like we need to cherry-pick this PR to old releases. it's better if we have a rough estimation.

The revised version of code calls cache.get instead of azure API. The cache refreshes itself every 10 min. I believe this will solve the throttling issue.

**Comment by mmisztal1980** [comment]
I believe we're being affected by this. Apart from getting the `failed to ensure host in pool` - when creating our `nginx-ingress` to use a pre-configured Azure Public IP, the ingress appears to be getting a different IP each time

**Comment by ArchangelSDY** [comment]
Thank you all!

**Comment by nilo19** [comment]
> I believe we're being affected by this. Apart from getting the `failed to ensure host in pool` - when creating our `nginx-ingress` to use a pre-configured Azure Public IP, the ingress appears to be getting a different IP each time

The PR is merged. Does your issue remain? @mmisztal1980

**Comment by andyzhangx** [comment]
> > I believe we're being affected by this. Apart from getting the `failed to ensure host in pool` - when creating our `nginx-ingress` to use a pre-configured Azure Public IP, the ingress appears to be getting a different IP each time
> 
> The PR is merged. Does your issue remain? @mmisztal1980

@nilo19 pls cherry-pick that fix to old release, thanks

**Comment by nilo19** [comment]
> > > I believe we're being affected by this. Apart from getting the `failed to ensure host in pool` - when creating our `nginx-ingress` to use a pre-configured Azure Public IP, the ingress appears to be getting a different IP each time
> > 
> > 
> > The PR is merged. Does your issue remain? @mmisztal1980
> 
> @nilo19 pls cherry-pick that fix to old release, thanks

Cherry picked to release 1.14-1.16
https://github.com/kubernetes/kubernetes/pull/86047
https://github.com/kubernetes/kubernetes/pull/86048
https://github.com/kubernetes/kubernetes/pull/86049

**Comment by mmisztal1980** [comment]
I’ll retry today and let you know

Wysłane z iPhone'a

**Comment by oronboni** [comment]
Issue returned in K8S 1.15.4
Warning   UpdateLoadBalancerFailed   service/nginx-ingress-controller   Error updating load balancer with new hosts map[<nodes names>]: [EnsureHostInPool(ingress/nginx-ingress-controller): backendPoolID(/subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.Network/loadBalancers/<rg>/backendAddressPools/<rg>) - failed to ensure host in pool: "azure - cloud provider rate limited(read) for operation:VMSSGet", EnsureHostInPool(ingress/nginx-ingress-controller):
