### ISSUE TITLE
TTLAfterFinished feature does not work in 1.15.2

### ISSUE THREAD

**Issue by kvokka** [kubernetes/kubernetes#83081]
**What happened**:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: pi-with-ttl
  name: pi-with-ttl
  namespace: default
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        job-name: pi-with-ttl
    spec:
      containers:
        - command:
            - perl
            - -Mbignum=bpi
            - -wle
            - print bpi(2000)
          image: perl
          imagePullPolicy: Always
          name: pi
          resources: {}
      restartPolicy: Never
```

```bash
$ minikube version                                           
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
$ minikube start --feature-gates="TTLAfterFinished=true"
😄  minikube v1.3.1 on Darwin 10.14.6
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
$ kubectl apply -f job.yaml               
job.batch/pi-with-ttl created
$ kubectl get po                                                                                              
NAME                  READY   STATUS      RESTARTS   AGE
pi-with-ttl-2-96xlt   0/1     Completed   0          50m
```

```bash
$ minikube ssh sudo kubeadm config view
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
    enable-admission-plugins: NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    feature-gates: TTLAfterFinished=true
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /var/lib/minikube/certs/
clusterName: kubernetes
controlPlaneEndpoint: localhost:8443
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /data/minikube
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.15.2
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true
```

**What you expected to happen**:

Job should be cleaned up after TTL

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.2
- Cloud provider or hardware configuration: minikube
- OS (e.g: `cat /etc/os-release`): macOs 10.14.6
- Kernel (e.g. `uname -a`): Darwin MBP-Mike 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

/kind bug
/sig apps

**Comment by liggitt** [comment]
Did you enable the feature in the apiserver and controller manager? It's an alpha feature and is not enabled by default

**Comment by kvokka** [comment]
@liggitt As you can see in the first message, there is the output from the command `minikube ssh sudo kubeadm config view` with information, that the feature is enabled.

Corrent me, please if it was done wrong or there is not enough provided information.

Thank you.

**Comment by Joseph-Irving** [comment]
I've replicated your set-up (minikube 1.3.1, kube 1.15.2, same job manifest) and I've been unable to reproduce the issue, does this consistently happen or only sometimes? 

Could you show what version of kubectl are you using `kubectl version --client`?
Also what does ` kubectl get job pi-with-ttl -o yaml` show?

**Comment by kvokka** [comment]
From the previous attempt I had to reset the minikube with `minikube start --cpus 8 --memory='4096mb' --feature-gates="TTLAfterFinished=true"` and then I tried it again and it works.

Have no idea why it did not work at the first attempt.

But it is resolved, so we may close it.
