### ISSUE TITLE
kube-apiserver should oportunistically notify about its startup readiness

### ISSUE THREAD

**Issue by stefwalter** [kubernetes/kubernetes#8311]
kube-apiserver should use the sd_notify() systemd API, either directly, or by reimplementing it (since it's trivial).

http://www.freedesktop.org/software/systemd/man/sd_notify.html

The sd_notify() systemd API tells systemd that the service is ready to accept connections. systemd will track its status correctly. 

In particular `systemctl start kube-apiserver.service` should not return until kube-apiserver is ready to accept connections. This allows other services, tests or consumers of kube-apiserver to deterministically depend on it.

**Comment by smarterclayton** [comment]
Was implemented before 1.7
