### ISSUE TITLE
CSI driver should not attempt to rollback mount on ownership change failure

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#83129]
As I was reading this code, I looked into bits that try to rollback the mount operation if `SetVolumeOwnership` fails - https://github.com/kubernetes/kubernetes/pull/62486/files

I am not sure if this is the right thing to do because what could happen is,  a volume gets mounted but if `SetVolumeOwnership` fails, the volume will not be recorded as mounted in actual state of the world, which in itself is not a problem but since `NodeUnpublish` or `removeMountDir` calls could fail with transient errors, nothing will retry to unmount the volume correctly if pod was deleted after first mount attempt failed in `SetVolumeOwnership` function.

cc @kubernetes/sig-storage-bugs

**Comment by gnufied** [comment]
None of the other in-tree drivers attempt to "undo" a failed `SetVolumeOwnership` change and I am not entirely sure why should CSI driver do this differently.

cc @jsafrane @msau42 @vladimirvivien

**Comment by tedyu** [comment]
In csiMountMgr#applyFSGroup, only one error is returned.
It seems the following if block can log the error (instead of rolling back)
```
	if err != nil {
		// attempt to rollback mount.
```

**Comment by msau42** [comment]
/remove-lifecycle rotten
cc @jingxu97

**Comment by gnufied** [comment]
This is fixed by https://github.com/kubernetes/kubernetes/pull/82492
