### ISSUE TITLE
decisions about the kubeadm release process

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#83127]
with kubeadm moving out of tree (parent issue is here https://github.com/kubernetes/kubernetes/issues/78534)
sig release and sig cluster lifecycle need to make some decisions.

- should the kubeadm binary continue to be packaged as part of the node tarballs.
- what to do with some of the deb/rpm packages that kubeadm needs:
  - cri-tools
  - kubernetes-cni
- given kubeadm lives in a separate repo, how to tag/branch that repository.

ideally we should book a call for this, but i'm opening this ticket so that we can get the discussion going beforehand.

document with proposals about the kubeadm build/release after it moves out:
https://docs.google.com/document/d/1xFAGAjfPQZrcqmapTwpJR5aUA7-2ku1asVeq3dBrjnQ/edit?usp=sharing

/kind design
/area kubeadm
/priority important-soon
/sig cluster-lifecycle release
/assign @neolit123 @timothysc @justaugustus @tpepper 
cc @dims

**Comment by justaugustus** [comment]
@neolit123 -- want to pop this on the agenda for next week's Release Engineering meeting?
https://docs.google.com/document/d/16GqCjnEh86w8yADcrUylNoE1y1sqjIMYNC_gdk5WPSQ/edit?usp=sharing

**Comment by neolit123** [comment]
@justaugustus is that Monday, 15:00 UTC?
@timothysc are you OK with that day and time?

**Comment by neolit123** [comment]
added agenda item for Monday, 30th.

**Comment by neolit123** [comment]
wrote document to outline some ideas about the kubeadm build and release once moved out of tree:
https://docs.google.com/document/d/1xFAGAjfPQZrcqmapTwpJR5aUA7-2ku1asVeq3dBrjnQ/edit?usp=sharing

**Comment by neolit123** [comment]
/close

discussion is happening at 
https://docs.google.com/document/d/1xFAGAjfPQZrcqmapTwpJR5aUA7-2ku1asVeq3dBrjnQ/edit?usp=sharing

new kubeadm tracking issue:
https://github.com/kubernetes/kubeadm/issues/1949
