### ISSUE TITLE
Strict APT check just for debian-based linuxes

### ISSUE THREAD

**Issue by cusspvz** [kubernetes/kubernetes#8313]
I'm using Mac OS X, and installed juju via `brew`.

Cannot deploy under `juju` since it is checking for packages and stuff.

``` bas
Starting cluster using provider: juju
... calling verify-prereqs
... Detected missing dependencies.. running
... add-apt-repository ppa:juju/stable
sudo: add-apt-repository: command not found
josemoreira@MacBook-Pro-de-JM ~/A/kubernetes>
```

Fixed up editing prereqs to check if `juju` and `juju-quickstart` are available trough `brew`.

```
josemoreira@MacBook-Pro-de-JM ~/A/kubernetes> cluster/kube-up.sh 
Starting cluster using provider: juju
... calling verify-prereqs
ok
... calling kube-up
```

**Comment by chuckbutler** [comment]
cusspvz - this sounds like a great contribution. Do you have a PR to add this functionality?

**Comment by chuckbutler** [comment]
Can I get someone to assign this bug to me? I'd like to work through this and make the experience better -- (even though this is much later than the bug was originally filed)

**Comment by cusspvz** [comment]
I don't use JuJu anymore.

But it should be an easy implementation.

**Comment by cusspvz** [comment]
Done, because of my limited time, @chuckbutler just need you to check where is the OS detection being made. Tested the file on the PR and it is working.

**Comment by chuckbutler** [comment]
Brilliant, thanks for the contribution @cusspvz, I'll take a look later today/tomorrow and add any additional sugar if required.

Again, thanks for the effort here! Especially considering you dropped using juju as your path to delivering Kubernetes. That's above and beyond.

**Comment by chuckbutler** [comment]
@cusspvz - I've folded your work in and it's a great start. I'm hacking through the other OSX incompatibilities we've found in the util.sh, namely that OSX doesn't have a GNU compliant readline. #TIL that we have a lot further to go to support the major flavors. 

I'm going to fold in that work, and submit as a new PR, but I'll be sure to give you credit for the effort done, and will link against this bug. Thanks again for everything done to this point :)

**Comment by cusspvz** [comment]
>  I'm hacking through the other OSX incompatibilities we've found in the util.sh, namely that OSX doesn't have a GNU compliant readline. 

Just add the readline package on my commit. :)

```diff
    fi

+    package_status 'readline'
    package_status 'juju'
    package_status 'charm-tools'
}
```

> I'm going to fold in that work, and submit as a new PR, but I'll be sure to give you credit for the effort done, and will link against this bug.

Thank you! Feel free to mention me whenever you need. :)

**Comment by roberthbailey** [comment]
/cc @chuckbutler @castrojo @marcoceppi @mbruzek (owners of the juju directory). 

Can one of you triage and determine if this is still an active issue that is being worked on or can it be closed?

**Comment by chuckbutler** [comment]
I think we're good to close this @roberthbailey.

**Comment by roberthbailey** [comment]
Thanks.
