### ISSUE TITLE
Health check latency metrics

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#83136]
**What would you like to be added**:

Currently the apiserver has request latencies metrics, which are a histogram of requests to the apiserver. However, these request metrics do not include healthz. While we have recently added the ability to get back health check metrics from the healthz endpoint directly, we should also emit this data as a metric, so that we can monitor health check latencies. 

/assign @jktomer
/sig api-machinery instrumentation

**Comment by conwaychriscosmo** [comment]
I noticed this is informally assigned.  Has there been any progress?  Is this a place I can fit in?

**Comment by jktomer** [comment]
Yes, I'm working on a PR.
