### ISSUE TITLE
Endpoint object not updated if service port has a name instead of a numeric port

### ISSUE THREAD

**Issue by mrrandrade** [kubernetes/kubernetes#83145]
**What happened**: Kubernetes didn't update the **endpoints** object if **service** had a targetPort with name instead of 

**What you expected to happen**: Endpoints to be updated.

**How to reproduce it (as minimally and precisely as possible)**:

Our cluster is up-to-date, but it has a lot of ancient residues like this yaml file from a very old metrics-server installation: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/metrics-server/metrics-server-service.yaml

This yaml file describes metrics-server **service** as:

```
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
```

So we updated Kubernetes from 1.13 to 1.15 and it failed to update the endpoints object.

Changing targetPort: https to targetPort: 443 solves the issue.

Making it back https removes the pod address from endpoints, so it's a pretty consistent behavior.

**Anything else we need to know?**: It's not like I care about using names on ports definitions on services, but I didn't find any mentions to not being able to use it anywhere on the release notes so I'm guessing it's really a bug.

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: on-prem
- OS (e.g: `cat /etc/os-release`): CoreOS 2191.5.0 but i dont think its relevant.
- Kernel (e.g. `uname -a`): 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 
- Install tools: by hand.
- Network plugin and version (if this is a network-related bug): -
- Others: -

**Comment by mrrandrade** [comment]
Api documentation says clearly that you have to specify the name (in this case, 'https') as a named port in the Pod's spec.

```
targetPort: Number  or name of the port to access on the pods targeted by the service.  Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports.  If this is not specified, the value of the 'port' field is used (an  identity map). This field is ignored for services with clusterIP=None,  and should be omitted or set equal to the 'port' field. More info:  https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

```
I'm guessing just a mention in the official documentation [here, maybe](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service) will suffice to clear things up!

**Comment by liggitt** [comment]
correct, the name has to match a named port in a pod spec. a documentation change to clarify that would be welcome

/remove-kind bug
/kind documentation
