### ISSUE TITLE
CRITICAL!! PV-Binder-Controller will delete the new created PV

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#83177]
**What happened**:

[PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go) will delete the new created (unused and unbound) PV if PV-Binder-Controller is on heavy load, when the PV related StorageClass ReclaimPolicy is OnDelete.

**What you expected to happen**:

Fix this critical bug to avoid to delete PV in mistake.

**How to reproduce it (as minimally and precisely as possible)**:

We need to make [PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go) on heavy load to reproduce this issue, actually 100 PVC/PV creation in same time will make [PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go) to be this heavy load state.  I will share the PV-Loader project to [perf-tests](https://github.com/kubernetes/perf-tests) later.

- Background

[PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go) actual has two Queue which are PV and PVC Queue, and combine two controllers to [PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go). I called these two controllers to `PV-Controller` and `PVC-Controller` respectively. `PVC-Controller` has some performance issue, it process PVC may cost a long latency(I will post another issue to talk about the performance of [PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go)). However, `PV-Controller` performance is better than `PVC-Controller`, it process PV is faster than `PVC-Controller`.

These two controller get PVC from the inner [cache](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L181) firstly, and only in same cases will get PVC from Informer Lister and API Server. And a PVC in [cache](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L181)  will only be updated when `PVC-Controller` finished processed this PVC.

- Bug timeline

1. User create a PVC (StorageClass RelaimPolicy is OnDelete)
2. CSI Provisioner create a pre-bound PV
3. `PVC-Controller` is busy with processing another backlog PVCs, and the created PVC is not updated in [cache](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L181) .
4. `PV-Controller` process the created PV,  can't get the related PVC, treat the PV as Released and reclaimVolume, then if the StorageClass RelaimPolicy is OnDelete, delete the PV. Code at [PVC-Binder-Controller#L522 - L583](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L522)

- Examples

1. StorageClass

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: foo
provisioner: foo-csi
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

2. PVC

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi
  storageClassName: foo
```

2. PV provisioned by CSI Provisioner according PVC

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-pvc
    namespace: default
    resourceVersion: "1"
    uid: "foo-uid"
  csi:
    ...
```

**Anything else we need to know?**:

1. I will post another issue to talk about the performance of [PV-Binder-Controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go).
2. I will post PV-Loader performance tests to [perf-tests](https://github.com/kubernetes/perf-tests).

**Environment**:

No need to care about this.

**Comment by jsafrane** [comment]
> Bug timeline
> 1. User create a PVC (StorageClass RelaimPolicy is OnDelete)
> 2. CSI Provisioner create a pre-bound PV
> 3. PVC-Controller is busy with processing another backlog PVCs
> 4. PV-Controller process the created PV, can't get the related PVC, treat the PV as Released and reclaimVolume

Something does not sound right between steps 1. and 2. The external provisioning is initiated by the PVC controller itself. It gets a PVC, checks it does not know how to provision it and adds annotation that it should be provisioned externally. So the PVC controller has seen the PVC and should have it in its cache.

In theory this should be pretty robust. There must be a bug somewhere. Did the controller forgot to add the PVC to the controller cache? Was the PVC deleted from the cache? Or does the external provisioner start provisioning without the [external provisioning annotation](https://github.com/kubernetes/kubernetes/blob/ad333ac4217f442b56a5dac8407617ba359e6e17/pkg/controller/volume/persistentvolume/util/util.go#L70)?

**Comment by msau42** [comment]
What version of CSI provisioner are you using? There was a bug in older releases in the lib-external-provisioner where it was not checking for the annotation.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by alejandrox1** [comment]
What version of Kubernetes are you using?

**Comment by ddebroy** [comment]
@answer1991 can you please specify the CSI driver you are using and it's version?
Do you happen to be using something like EBS CSI or GCE PD CSI by any chance?

**Comment by cwdsuzhou** [comment]
agree with @jsafrane , pv controller should have seen the pvc.


See the codes and the comments.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L524-532

From the comments, we should `double check` pvc when pvc it not found and the pv is bound by` external binder`.

But from the codes, we should `double check` pvc when pvc is not found and pv is bound by `controller`?

**Comment by answer1991** [comment]
> Or does the external provisioner start provisioning without the [external provisioning annotation](https://github.com/kubernetes/kubernetes/blob/ad333ac4217f442b56a5dac8407617ba359e6e17/pkg/controller/volume/persistentvolume/util/util.go#L70)?

> There was a bug in older releases in the lib-external-provisioner where it was not checking for the annotation.

Yes, I checked and found our external provisioner start to provision without this annotation. Our CSI components' lib version is 0.4.0, it is alpha version?

I should fix our external provisioner to provision PVs only when PVCs has annotation `volume.beta.kubernetes.io/storage-provisioner`

@msau42 @jsafrane @alejandrox1

**Comment by answer1991** [comment]
@ddebroy 

> Do you happen to be using something like EBS CSI or GCE PD CSI by any chance?

Sorry, we have not ever used EBS CSI or GCE PD CSI.

**Comment by answer1991** [comment]
@cwdsuzhou 

> From the comments, we should double check pvc when pvc it not found and the pv is bound by external binder.
But from the codes, we should double check pvc when pvc is not found and pv is bound by controller?

Yes, maybe you are right. I do not know why we need check annotation here.

@jsafrane @msau42 What's your opinion?

**Comment by msau42** [comment]
The fix to check for the annotation was made here: https://github.com/kubernetes-incubator/external-storage/pull/521 which was release with external-storage v5.5.0.  CSI external-provisioner v0.4.x [imports v5.2.0](https://github.com/kubernetes-csi/external-provisioner/blob/release-0.4/Gopkg.toml#L41) which does not contain the fix.  CSI external-provisioner v1.0+ should have the fix.
