### ISSUE TITLE
TaintBasedEviction test is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#83182]
e.g. this one:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83179/pull-kubernetes-integration/1177132150030340097/

/assign @krzysied 
who was already looking into that

**Comment by neolit123** [comment]
/sig scheduling
/remove-kind bug
/kind flake

was this resolved by these PRs:
https://github.com/kubernetes/kubernetes/pull/83179
https://github.com/kubernetes/kubernetes/pull/82884

**Comment by spiffxp** [comment]
/close
Something happened around mid november that dramatically reduced failures for this test. No failures in past two weeks as of today, considering this closed.

- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-11-01&pr=1&job=integration&test=TaintBasedEviction
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-11-15&pr=1&job=integration&test=TaintBasedEviction
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-12-01&pr=1&job=integration&test=TaintBasedEviction
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=integration&test=TaintBasedEviction
