### ISSUE TITLE
Kubernetes Node NotReady and unreachable

### ISSUE THREAD

**Issue by akumadare** [kubernetes/kubernetes#83186]
**What happened**:

After high memory usage for a pod with Burstable QoS the Kubernetes node goes into a **NotReady** state. 

kube-proxy logs show **iptables save** messages:

> {"log":"I0725 13:35:08.909381       1 trace.go:81] Trace[1587491415]: \"iptables save\" (started: 2019-09-25 13:35:05.643320751 +0000 UTC m=+20513.998480418) (total time: 2.163853971s):\n","stream":"stderr","time":"2019-09-25T13:35:08.909537868Z"}
> {"log":"Trace[1587491415]: [2.163853971s] [2.163853971s] END\n","stream":"stderr","time":"2019-09-25T13:35:08.963956436Z"}
> {"log":"I0725 13:35:12.793960       1 trace.go:81] Trace[882864489]: \"iptables save\" (started: 2019-09-25 13:35:08.909507347 +0000 UTC m=+20517.264666418) (total time: 3.025689401s):\n","stream":"stderr","time":"2019-09-25T13:35:12.794107718Z"}
> {"log":"Trace[882864489]: [3.025689401s] [3.025689401s] END\n","stream":"stderr","time":"2019-09-25T13:35:12.794139795Z"}
> {"log":"I0725 13:35:18.137746       1 trace.go:81] Trace[1340039994]: \"iptables restore\" (started: 2019-09-25 13:35:13.210448634 +0000 UTC m=+20521.565608308) (total time: 4.514881276s):\n","stream":"stderr","time":"2019-09-25T13:35:18.686412344Z"}
> {"log":"Trace[1340039994]: [4.514881276s] [4.514489973s] END\n","stream":"stderr","time":"2019-09-25T13:35:18.686443269Z"}
> {"log":"I0725 13:40:17.032152       1 trace.go:81] Trace[827047055]: \"iptables save\" (started: 2019-09-25 13:40:03.511447639 +0000 UTC m=+20811.866607200) (total time: 12.139123785s):\n","stream":"stderr","time":"2019-09-25T13:40:17.652871171Z"}
> {"log":"Trace[827047055]: [12.139123785s] [12.139123785s] END\n","stream":"stderr","time":"2019-09-25T13:40:18.304376479Z"}
> {"log":"I0725 13:40:32.345939       1 trace.go:81] Trace[64455451]: \"iptables save\" (started: 2019-09-25 13:40:17.990449893 +0000 UTC m=+20826.345609311) (total time: 12.171540284s):\n","stream":"stderr","time":"2019-09-25T13:40:36.552179901Z"}
> {"log":"Trace[64455451]: [12.171540284s] [12.171540284s] END\n","stream":"stderr","time":"2019-09-25T13:40:37.421655417Z"}
> {"log":"I0725 13:40:55.716356       1 trace.go:81] Trace[1711868348]: \"iptables restore\" (started: 2019-09-25 13:40:34.758185622 +0000 UTC m=+20843.113344952) (total time: 20.957895325s):\n","stream":"stderr","time":"2019-09-25T13:40:56.728845842Z"}
> {"log":"Trace[1711868348]: [20.957895325s] [20.957733184s] END\n","stream":"stderr","time":"2019-09-25T13:40:56.827681002Z"}

kubelet shows error trying to update lease:

> 7025 controller.go:149] failed to update node lease, error: Put https://10.15.100.137:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/ip-10-15-100-123.eu-west-1.compute.internal?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

TCP connection test to the node using **netcat** is successful on kubelet port (10250) and an example nodeport (32767).

TCP connection test to node using **netcat** on SSH port (22) succeeds. SSH connection to node fails as hangs after establisin(see verbose output):

> Macbook-5:test macbook$ ssh -v 10.15.100.122
> OpenSSH_7.9p1, LibreSSL 2.7.3
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 48: Applying options for *
> debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port 22.
> debug1: Connection established.
> debug1: identity file /Users/macbook/.ssh/id_rsa type -1
> debug1: identity file /Users/macbook/.ssh/id_rsa-cert type -1
> debug1: identity file /Users/macbook/.ssh/id_dsa type -1
> debug1: identity file /Users/macbook/.ssh/id_dsa-cert type -1
> debug1: identity file /Users/macbook/.ssh/id_ecdsa type -1
> debug1: identity file /Users/macbook/.ssh/id_ecdsa-cert type -1
> debug1: identity file /Users/macbook/.ssh/id_ed25519 type -1
> debug1: identity file /Users/macbook/.ssh/id_ed25519-cert type -1
> debug1: identity file /Users/macbook/.ssh/id_xmss type -1
> debug1: identity file /Users/macbook/.ssh/id_xmss-cert type -1
> debug1: Local version string SSH-2.0-OpenSSH_7.9

The only way to clear the issue that I have found is to reboot the node. The issue looks to be network related possibly relating to interruption to Calico / kube-proxy.

Is there any way to prevent or recover from this state? 

Our load-balancer health checks use an HTTP health endpoint but this still passes when it is in this state so our autorecovery process does not get invoked.

**Environment**:
- Kubernetes version: 14.6
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core) 
- Kernel (e.g. `uname -a`): Linux xxxxxx.eu-west-1.compute.internal 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): using quay.io/calico/cni:v3.1.6 container
- Others:

**Comment by akumadare** [comment]
@kubernetes/sig-network-bugs

**Comment by saiyan86** [comment]
hi @akumadare have you tried opening a support ticket on AWS? It seems this needs some in-depth troubleshooting like ```tcpdump```.

**Comment by akumadare** [comment]
Hi, I will try to replicate this issue and get some more stats.

Setting more strict memory limits for pods has seemed to prevent the issue from happening. It would be nice to find a way to prevent this from happening when the kernel OOM killer kicks in

**Comment by saiyan86** [comment]
> Hi, I will try to replicate this issue and get some more stats.
> 
> Setting more strict memory limits for pods has seemed to prevent the issue from happening. It would be nice to find a way to prevent this from happening when the kernel OOM killer kicks in

Can try this config in ```kubelet```: --kube-reserved 
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by akumadare** [comment]
> > Hi, I will try to replicate this issue and get some more stats.
> > Setting more strict memory limits for pods has seemed to prevent the issue from happening. It would be nice to find a way to prevent this from happening when the kernel OOM killer kicks in
> 
> Can try this config in `kubelet`: --kube-reserved
> https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

Hi. This is a parameter i have considered but it is only relevant to scheduling rather than protecting any of the pod runtime processes under OOM conditions. From what I have read the kubelet should have a very negative oom_score_adj and should also set a very negative oom_score_adj for system critical pods - I have confirmed this within the cluster.
