### ISSUE TITLE
kube-scheduler should fallback to core/v1 Events if events.k8s.io/v1beta1 is unavailable

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#83203]
In v1.16.0 https://github.com/kubernetes/kubernetes/pull/78447 migrated kube-scheduler to emit events against the v1beta1 API, but didn't implement a fallback to core/v1 in case `events.k8s.io/v1beta1` is not available. we should fix this.

The fix would targed v1.16.2

/assign @yastij 
cc @wojtek-t @liggitt 

/sig scheduling
/priority important-soon

**Comment by yastij** [comment]
@liggitt @wojtek-t - I think we might want to do the check at the kube-scheduler level as it would be easier. otherwise we'd need to change a lot of the implementation in the client-go's event package

**Comment by wojtek-t** [comment]
That's a good point. I think that's fine.
