### ISSUE TITLE
Support long-running requests on aggregated apiservers

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubernetes#83200]
**What would you like to be added**:

Allow aggregated apiservers to register long-running request (to e.g. filter them out like it is done with the `logs` subresource), or leave it completely up to the aggregated apiserver to terminate connections after timeouts.

**Why is this needed**:

There are cases where one wants to create subresources on aggregated apiservers which should be allowed to run for a long time, similar to like `log` is allowed to. For instance in [kubevirt](https://github.com/kubevirt/kubevirt) we support connecting to serial consoles of virtual machines, or via VNC. In both cases it is common that you want to keep them open for a longer period and also in both cases it can happen that for a very long time nothing is exchanged.

**Comment by deads2k** [comment]
The aggregator does not have enough information to decide whether proxied requests are long running or not.  That responsibility logically belongs to the aggregated apiserver.  Proper plumbing may be a challenge.

**Comment by tedyu** [comment]
I think we should also control the number of live long-running requests so that aggregated apiserver is not overloaded.

**Comment by rmohr** [comment]
@tedyu would it make sense to make that based on the actual traffic? For instance especially in the kubevirt case, we have "serial console" connections to VMs, which very often send nothing for a long time.

**Comment by rmohr** [comment]
> The aggregator does not have enough information to decide whether proxied requests are long running or not. That responsibility logically belongs to the aggregated apiserver. Proper plumbing may be a challenge.

I was thinking that maybe registering this on the apiregistration object might be a solution. Not sure if at this level the aggregator can differentiate based on that.

**Comment by deads2k** [comment]
> I think we should also control the number of live long-running requests so that aggregated apiserver is not overloaded.

Aggregated apiservers are specified by cluster-admins.  The control of how long the request stays open belongs to the destination server.  Control over requests overall belongs to priority/fairness (see other KEP).  I don't think we want a secondary system controlling the lifespan of proxied connections.

**Comment by rmohr** [comment]
> Aggregated apiservers are specified by cluster-admins. The control of how long the request stays open belongs to the destination server.

So moving that filter to the apiserver library and doing the filter in the core apiserver should do the trick?

I guess we would probably need a feature flag or something, since all currently built apiservers rely on the global timeout.
