### ISSUE TITLE
CRD AllowUnconditionalUpdate modify

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes/kubernetes#83222]
Kubenetes built-in resource objects StatefulSet、Deployment、DaemonSet ... of fields AllowUnconditionalUpdate default is true。

```
// AllowUnconditionalUpdate is the default update policy for daemon set objects.
func (daemonSetStrategy) AllowUnconditionalUpdate() bool {
	return true
}
``` 
Why CRD resource of fields AllowUnconditionalUpdate default is false?

```
func (customResourceStrategy) AllowCreateOnUpdate() bool {
	return false
}
```

**What would you like to be added**:
Can add a way to modify the update policy of the default CRD?

**Why is this needed**:

Because there are many custom resources, not every custom resource needs to AllowUnconditionalUpdate default is true

**Comment by ZP-AlwaysWin** [comment]
/assign @deads2k  
hi @deads2k  I looked at the source code, this part of the code is written by you, can you specify this parameter when creating CRD? 
Best Wishes

**Comment by roycaihw** [comment]
I don't know if we want to encourage `AllowUnconditionalUpdate` in our API. In fact it was proposed that we should disallow unconditional update. See related discussion: https://github.com/kubernetes/kubernetes/issues/21330

/unassign
/sig architecture

**Comment by dims** [comment]
@roycaihw Do we really need this to be discussed in sig-arch? can you please start a thread on the mailing list and/or line up an item in the next meeting. I think this might be just handled in api-machinery if not please do as mentioned before.

**Comment by liggitt** [comment]
Custom resources bake in many of the lessons we've learned over the last five years building APIs, and allowing unconditional update is not a best practice. It makes it too easy to overwrite data unintentionally. You can use patch updates without a resourceVersion set to overwrite fields regardless of current content, if desired.

/close
