### ISSUE TITLE
Feature Request: Scale in StatefulSet at an arbitrary position

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#83224]
**What would you like to be added**:

We encountered a problem in production to run databases with local PVs and StatefulSet. It's inconvenient to scale in the database when pods on the node to delete are not the last ordinal indices of the StatefulSet.

I hope we can scale in StatefulSet at an arbitrary position, e.g. delete pod-1 but keep pod-2 in a StatefulSet of 3 replicas.

**Why is this needed**:

Although pods created from the same spec in StatefulSet, but are not interchangeable because each of them has associated persistent storage. 

| node A | node B | node C|
| -------| ------- | ------ |
| pod-0 | pod-2 | pod-1 |

Using local PVs, pods are tied to nodes. When we scale in the node pool or take down a node in the on-premise data center. If the pod on that node is not the last ordinal of the StatefulSet, it's hard to scale in the StatefulSet to free the node. We need at the first scale in the StatefulSet to free the node B, and then migrate the pod-1 to node B.

It requires to migrate data between nodes. It's often unacceptable when the amount of data on the node is large, e.g. databases.

Current StatefulSet has some limitations when pods cannot be rescheduled freely. So, I think it's time to implement an alternative indexing method (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/apps/stateful-apps.md#how-identities-are-managed).

An intuitive solution is to move off the deleted slots. The network identifiers are ordinal, stable the same as before except holes can exist. 

I've done a quick hack on builtin StatefulSet using annotations:  https://github.com/cofyc/kubernetes/compare/1aea0dd9383a2f7ac9f7e055ff10a08ea241db51...cofyc:scale-in-statefulset-at-arbitrary-position and verified that basic operations like create, scale in/out work.

**Comment by msau42** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by tedyu** [comment]
```
basic operations like create, stale in/out work
```
Did you mean scale in/out ?

**Comment by cofyc** [comment]
Yes, sorry, my typo.

**Comment by cofyc** [comment]
FYI, I've implemented this feature in CRD based on Kubernetes 1.16.0 StatefulSet code: https://github.com/cofyc/advanced-statefulset

**Comment by haosdent** [comment]
@cofyc I think your CRD solution is preferred, so this issue could be closed?

**Comment by cofyc** [comment]
this can be closed

**Comment by zhubby** [comment]
https://gitlab.bangdao-tech.com/kubeease/doc/docs/blob/develop/redis-operator/Redis%20Operator%209a152342dffb4d5d8f210445b04dbf5f.md
