### ISSUE TITLE
failed to ensure node lease exists, will retry in 7s ,the k8s node offen notReady

### ISSUE THREAD

**Issue by zxx287856774** [kubernetes/kubernetes#83230]
controller.go:115] failed to ensure node lease exists, will retry in 7s, error: Get https://10.204.243.89:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/10.204.60.13?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
k8s version v1.15
i config kube-apiserver  --feature-gates=NodeLease=false ,but it's not worker

**Comment by jennybuckley** [comment]
It looks like this error message is from the [kublet log](https://github.com/kubernetes/kubernetes/blob/9873f0bfe8d77c8dca5ece565eb3135b9bba4602/pkg/kubelet/nodelease/controller.go), did you disable the NodeLease feature in the kubelet as well? or just the kube-apiserver

**Comment by wmcnamee-tunein** [comment]
why was this issue closed so quickly?

**Comment by mulhome-com** [comment]
Same issue while executing the command :  kubeadm join ...
The logging message just list this :
**kubelet[2252]: E0124 15:11:57.110928    2252 controller.go:146] "Failed to ensure lease exists, will retry" err="Unauthorized" interval="7s"**

So how to fixed this problem ?
