### ISSUE TITLE
[framework] a consistent interface for plugin extended functionality

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83244]
**What would you like to be added**:
A consistent way for adding extended functionality to plugins.

**Why is this needed**:
Currently we have two types of plugins that support adding some sort of optional functionality: PreFilter allow adding "AddPod/RemovePod" implementations through an "Updater" interface, while Score includes a NormalizeScore, which must be implemented, but plugins that don't require it can return nil.

The two cases above support adding "optional" functionality in different ways, what I suggest we do is have a common pattern, with common naming conventions to support that:

Any plugin that needs an extended functionality should define an ```_PluginName_Extensions``` interface, and have a method named ```Extensions()``` that returns the interface or nil if the plugin does not implement those extensions.

If we do that for PreFilter and Score plugins, it would look like this:

```
type PreFilterExtensions interface {
	AddPod(pc *PluginContext, podToSchedule *v1.Pod, podToAdd *v1.Pod, nodeInfo *schedulernodeinfo.NodeInfo) *Status
	RemovePod(pc *PluginContext, podToSchedule *v1.Pod, podToRemove *v1.Pod, nodeInfo *schedulernodeinfo.NodeInfo) *Status
}

type PreFilterPlugin interface {
	Plugin
	PreFilter(pc *PluginContext, p *v1.Pod) *Status
	Extensions() PreFilterExtensions
}


type ScoreExtensions interface {
    NormalizeScore(pc *PluginContext, p *v1.Pod, scores NodeScoreList) *Status
}

type ScorePlugin interface {
	Plugin
        Score(pc *PluginContext, p *v1.Pod, nodeName string) (int, *Status)
	Extensions() PreFilterExtensions
}
```

One concern here is that if the plugin wants to implement a single method of the extensions interface, they it will have to implement all the extensions methods, but i think that is fine since we don't expect to have many methods anyways.

**Comment by alculquicondor** [comment]
`Extensions` should have only 2 implementations:

```go
func (p* MyPlugin) Extensions() PreFilterExtensions {
    return p
}
```

or

```go
func (p* MyPlugin) Extensions() PreFilterExtensions {
    return nil
}
```

I think `Extensions` is a good suffix.

**Comment by Huang-Wei** [comment]
A kind reminder that `/good-first-issue` issue is more prepared for new contributors.

If you're active/experienced contributors, hold on jumping in unless it's not taken after several days.

**Comment by draveness** [comment]
Emmm.. I'm sorry to say this but this looks like a hack to me, I never saw this in any of Golang interfaces. Is it quite common when we want to have an optional method in Golang? If it isn't, I prefer to have the original approach.

**Comment by alculquicondor** [comment]
What we are trying to do is to have a common pattern for our interfaces.
Sadly, this is the best we can do with golang's type system.

But, I somewhat agree with @draveness. Maybe we can wait until we see that a new optional method is needed for other extension points?

**Comment by ahg-g** [comment]
> Emmm.. I'm sorry to say this but this looks like a hack to me, I never saw this in any of Golang interfaces. Is it quite common when we want to have an optional method in Golang? If it isn't, I prefer to have the original approach. Besides, there won't be that much extension point with optional methods IMO.

As Aldo mentioned, we don't have a way to properly define "optional" methods in golang, we already have this pattern for the PreFilter interface, I see value in making it consistent between PreFilter and Score.

> 
> > One concern here is that if the plugin wants to implement a single method of the extensions interface, they it will have to implement all the extensions methods, but i think that is fine since we don't expect to have many methods anyways.
> 
> And as you point out, this won't solve the problem if someone just wanna implement some of the optional methods.

We don't expect that to happen very often, so to me this is less of a concern.

**Comment by ahg-g** [comment]
> `Extensions` should have only 2 implementations:
> 
> ```go
> func (p* MyPlugin) Extensions() PreFilterExtensions {
>     return p
> }
> ```
> 
> or
> 
> ```go
> func (p* MyPlugin) Extensions() PreFilterExtensions {
>     return nil
> }
> ```
> 
> I think `Extensions` is a good suffix.

we can even make Extensions a variable of type PreFilterExtensions rather than a function, and so a plugin implementation doesn't even need to implement any extra methods beyond PreFilter or Score.

**Comment by Huang-Wei** [comment]
> I'm sorry to say this but this looks like a hack to me, I never saw this in any of Golang interfaces.

The most basic API machinery type system used this. E.g., `runtime.Object`:

https://github.com/kubernetes/kubernetes/blob/cd95e57c71a194a80064b00a44e42a222003dac8/staging/src/k8s.io/apimachinery/pkg/runtime/interfaces.go#L250-L257

**Comment by notpad** [comment]
Can I help with this?

**Comment by draveness** [comment]
> The most basic API machinery type system used this. E.g., runtime.Object:

Thanks, @huang-wei, that's good example.

**Comment by ahg-g** [comment]
thanks @notpad
