### ISSUE TITLE
[Scheduler framework] Split scheduling cycle into filter and score cycles

### ISSUE THREAD

**Issue by Adirio** [kubernetes/kubernetes#83240]
**What would you like to be added**:

A separate cycle for filtering and scoring phases in the scheduler framework.

**Why is this needed**:

Currently, the scheduler framework is divided into two separate cycles, the schedulign and the binding cycles. These cycles are run in different threads which give some asynchronous capacity to the scheduler. This allows the first hook in the second cycle to act as some sort of contention mechanism (e.g. [co-scheduling](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#coscheduling)), among other advantages.

A similar approach could be used to split the filtering and scoring sections (between the `Post-filter` and `Scoring` hooks).  By doing so a new hook, similar to the `Permit` one, could be added before `Scoring`. This would allow this new hook to make decissions based on the results of filtering not only itself but also other nodes.

Take as an example a set of pods that must be scheduled either all of them or none of them, as they require each others to work. Usually, filtering is quite a simple process. Scoring may get trickier. While the default scheduler follows a quite simple approach, there has been a ton of scientific effort directed to planification algorithms, that can get really complex, and scale pretty poorly with the number of nodes. Being able to make a decission if a set of pods should be scheduled after filtering could avoid the scheduler a lot of work scoring all these pods if some of them have already failed.

/sig scheduling

**Comment by draveness** [comment]
> Usually, filtering is quite a simple process. Scoring may get trickier.

I'm not sure I agree with this statement.

Are you suggesting the pod has to wait before scoring extension point if the pods have to scheduled by a group? Please feel free to correct me if I'm wrong.

If we decided to implement this, we have to face the same metadata update problem in the permit plugin, and probably we'll come up with another version of `Updater`.

The binding cycle could run in parallel, have a `Permit` extension point which executes time-consuming work is acceptable. But adding another extension point with `Updater` could affect the performance and complexity of the scheduling cycle.

1. We have to make the pod wait in the middle of the scheduling cycle and get back when the condition is valid.
2. Every node and pod get added or deleted could potentially invalidate the result we get in the filter extension point.

**Comment by Adirio** [comment]
> > Usually, filtering is quite a simple process. Scoring may get trickier.
> 
> I'm not sure I agree with this statement.

I think we could debate this for quite long, but filtering is usually linear to the number of nodes while scoring can have cuadratic or cubic relations to the number of nodes if you start adding complex metrics that depends on where others pods are scheduled.

> > Being able to make a decission if a set of pods should be scheduled after filtering could avoid the scheduler a lot of work scoring all these pods if some of them have already failed.
> 
> Are you suggesting the pod has to wait before scoring extension point if the pods have to scheduled by a group? Please feel free to correct me if I'm wrong.

Yes

> The binding cycle could run in parallel, have a Permit extension point which executes time-consuming work is acceptable. But adding another extension point with Updater could affect the performance and complexity of the scheduling cycle.

The idea is to be able to run filtering and scoring cycles also in parallel. Similar to how the binding cycle has been extracted from the main cycle to improve performance, my suggestion was to extract the filtering cycle from the main cycle (which would be the scoring one), to reduce the length of the critical sction, this time from the front instead of from the back. I have read the list of current filters and I only remember one that may get outdated, the one that checks if there is enough space/memory in the node. Do you remember any other filter that is expected to be dynamic in this same sense?
