### ISSUE TITLE
[migration] Refactor priorities to use NodeScore/NodeScoreList

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83241]
**What would you like to be added**:
Refactor priorities to use [NodeScore/NodeScoreList](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/interface.go#L35-L44) instead of [HostPriority/HostPriorityList](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/api/types.go#L337-L345)

**Why is this needed**:
The next step for migration is to implement Priorities as Score plugins. In phase 1 of the migration, we want to do that by calling the priorities functions directly from the score plugins instead of actually moving the code. 

Currently priorities return HostPriority/HostPriorityList, and so to avoid converting that to NodeScore/NodeScoreList when those are called from Score plugins, we should just refactor priorities to use NodeScore/NodeScoreList directly. This should be straightforward since NodeScore and HostPriority have one to one mapping of parameters.

/sig scheduling
/help
/priority important-soon

**Comment by damemi** [comment]
I'd like to help with this if that's okay
/assign

**Comment by ahg-g** [comment]
Certainly, thanks Mike.

**Comment by damemi** [comment]
This is now covered in https://github.com/kubernetes/kubernetes/pull/83262

**Comment by damemi** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/83262 merged I think this can be closed

**Comment by ahg-g** [comment]
/close

Thanks Mike!
