### ISSUE TITLE
Authentication token cache can live-lock

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#83259]
https://github.com/kubernetes/kubernetes/blob/release-1.16/staging/src/k8s.io/apiserver/pkg/authentication/token/cache/cached_token_authenticator.go#L70-L91

This code releases the lock to do the actual work. This means if there are N simultaneous requests for a token, apiserver will look it up N times. If that happens in parallel, OK, maybe it's not the end of the world, but as it happens it might not. Even if we didn't have a [self-client](https://github.com/kubernetes/kubernetes/pull/22423/files#diff-36e1d7088209b1ab6ff878b18bb35210R262) rate limit, etcd might be sluggish or serialize requests, or the webhook could be slow...

Since this cache holds results for a maximum of 10 seconds and we had a 50 qps rate limit for looking them up, in reality, only 500 items could be in the cache at any one given time, even though the cache could hold 4096 entries.

With a poor request order, just a few more than 500 items can therefore to trigger a serious issue (most requests making token-auth calls time out and leak a go routine due to our behavior on global time out).

With a pessimal request order and pessimal set of tokens, just a few more than 128 are necessary due to the way this is sharded into 32 caches of 128.

1.14 and 1.16 both contain changes that effectively prevent this behavior, and we've back-ported [removing the self-client rate limit](https://github.com/kubernetes/kubernetes/pull/80465) to 1.13. But, those just address a trigger for this; I think defense-in-depth demands we actually fix the cache, too.

So, this issue has two requests:
* Fix the cache, such that two simultaneous requests for an un-cached token will share work.
* Make the cache bigger and/or make the 4096 limit shared between shards rather than divided into 128 for each, which is too small.

/sig auth
/priority important-soon

**Comment by tedyu** [comment]
For #2 above, it seems stripedCache would be used this way:
```
		cache:         newStripedCache(1, fnvHashFunc, func() cache { return newSimpleCache(4096, clock) }),
```

**Comment by tedyu** [comment]
If I read the code right, the use of stripedCache is to reduce the collision between requests.

Some benchmark run may be needed across different choices of number of shards.

I looked under staging/src/k8s.io/apiserver/pkg/authentication/token/cache/ - there is BenchmarkStripedCache

**Comment by tedyu** [comment]
32 shards of 128 each:
```
BenchmarkStripedCache-12    	 5000000	      1870 ns/op
```
1 shard of 4096
```
BenchmarkStripedCache-12    	  500000	      3184 ns/op
```

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kubernetes/pull/83519 fixes the cache and includes a benchmark demonstrating that to trigger this live-lock behavior, it's not enough for calls to check a token to be slow; they must also be constricted / serialized in some way. (imagine: self client QPS limit, or etcd response time gets slower as the number of concurrent requests goes up, or the external webhook checker rate-limits, or ...)

**Comment by josiahbjorgaard** [comment]
Bug triage for release 1.17 here. Since this issue has been tagged for the milestone, we would like to check it's status. Code freeze is on Nov. 19. Will this issue be resolved before then?

**Comment by josiahbjorgaard** [comment]
@mikedanese Code freeze is in just a few days on Thursday, EOD, pacific time. Let us know if we should move this out of the v1.17 milestone.

**Comment by josiahbjorgaard** [comment]
/milestone v1.18

(v1.17 code freeze)
