### ISSUE TITLE
To increase the CPU load on a pod so that it would get scheduled to a new node

### ISSUE THREAD

**Issue by uditgaurav** [kubernetes/kubernetes#83256]
@kubernetes/sig-contributor-experience-<group-suffix>
PROBLEM STATEMENT
Is there any way by which i can increase the CPU load on a pod such that for time being the CPU Request is more than the CPU Limits so that the pod gets reschedule to a new node.
```
Limits:
      cpu:  500m
    Requests:
      cpu:     500m
```

**Comment by 928234269** [comment]
Do you just want pods not to be dispatched to a node? You can add anti-affinity to the pod.

**Comment by uditgaurav** [comment]
i just want to increase the load (stress) on the pod (in terms of cpu) and want to observe that whether it is getting rescheduled to a new node when the cpu request get increased and crossed the cpu limit.
Here is what i tried :
i first enter into the pod by this command.
`kubectl exec -it pod-name  --container container-name`
then i used stress command to increase the cpu load 
`stress --cpu 2 --timeout 60s`
But nothing happening to the pod even it's cpu-requests and limits remains same 
So what i'm missing ?
or there is some other way also?

**Comment by 928234269** [comment]
you can try use "kubectl edit deploy-name -o yaml" or "kubectl edit pod-name -o yaml" to modify the cpu limit and cpu request.
