### ISSUE TITLE
local blockdevice

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#83265]
I tried to use a local volume block device in minikube. Its trying to call losetup with the -j option and its failing as the losetup in minikube does not provide this option. This may effect other distro's as well. The end result is lock block devices don't work on the platform.

**Comment by pohly** [comment]
Probably caused by this code: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go

**Comment by kfox1111** [comment]
Did a strace on losetup -j. looks like the same info can be had by:
cat /sys/block/loop0/loop/backing_file

**Comment by irizzant** [comment]
Just had the same problem with Ceph cluster creation in minikube, the osd-prepare doesn't start because of this:
```
Events:
  Type     Reason           Age                 From               Message
  ----     ------           ----                ----               -------
  Normal   Scheduled        2m2s                default-scheduler  Successfully assigned rook-ceph/rook-ceph-osd-prepare-set1-0-data-sgpq7-j8tf9 to minikube
  Warning  FailedMapVolume  58s (x8 over 2m2s)  kubelet, minikube  MapVolume.MapBlockVolume failed for volume "local-pv-c84df416" : blkUtil.AttachFileDevice failed. globalMapPath:/var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/local-pv-c84df416, podUID: a477949a-a571-47ef-8409-6f8a3404dc64: GetLoopDevice failed for path /var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/local-pv-c84df416/a477949a-a571-47ef-8409-6f8a3404dc64: losetup -j /var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/local-pv-c84df416/a477949a-a571-47ef-8409-6f8a3404dc64 failed: exit status 1
```

**Comment by mwennrich** [comment]
FYI: https://github.com/kubernetes-csi/csi-driver-host-path has the same problem in minikube. Replacing the /sbin/losetup busybox link with a "real" losetup helped for now, but isn't a solution of course.
