### ISSUE TITLE
support delete resource by name with --all-namespaces=true

### ISSUE THREAD

**Issue by ruchikaguptaa** [kubernetes/kubernetes#83266]
**What would you like to be added**:
Something like kubectl delete cm abcd --all-namespaces

**Why is this needed**:
There is no other way of doing this apart from scripting it. This would come in really handy if a bad change caused a resource to be created across namespaces.

**Comment by yasongxu** [comment]
found same issue

 [https://github.com/kubernetes/kubernetes/issues/44718](https://github.com/kubernetes/kubernetes/issues/44718)

[https://github.com/kubernetes/kubernetes/issues/18282](https://github.com/kubernetes/kubernetes/issues/18282)

```
might prefer --namespace=ns1, ns2, ns3 to --all-namespaces for delete command. Take care of your kube-system
```

**Comment by ruchikaguptaa** [comment]
Is there any hack/workaround I can use for now?

**Comment by rajatjindal** [comment]
I implemented a quick kubectl plugin for doing this. It can be downloaded from here: https://github.com/rajatjindal/kubectl-delete-in-allns

Please refrain from using this in production as it can potentially cause disruption. There are currently no safe-guards for preventing delete from system namespaces (PR welcome)
