### ISSUE TITLE
Conformance script for v1.16.0 doesn't report results to Sonobuoy if failures

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#83272]
Same as an issue that occurred for v1.14.0: the failing test causes ginkgo to exit non-zero which causes the script to abort without running the `saveResult` routine.

A recent PR to this script fixed a race but we didn't realize that now that the command was running in the foreground (and not the background) that the non-zero status would impact that script.

Currently, Sonobuoy can get around this by just using the Golang based runner via `--plugin-env=e2e.E2E_USE_GO_RUNNER=true`. The Go-runner does not seem to have a similar vulnerability. This is going to be the default for Sonobuoy runs starting in Sonobuoy v0.16.0 if the PR gets merged.

Honestly, I think that we may want to consider just removing the bash script all-together for v1.17.0 if the go runner works well for this entire cycle.

See the original reporting of the issue and diagnosis here: https://github.com/heptio/sonobuoy/issues/910

/sig testing
/area conformance
/priority important-soon

**Comment by johnSchnake** [comment]
/assign

The PR in question that re-emerged this problem.

FWIW Sonobuoy is adding an integration suite that will be able to test this going forward (soon).

 - I think we need to fix the script (and get it cherrypicked into v1.16.x branches)
 - I think that if the go runner proves stable over v1.16 then we default to it going forward
 - We consider removing run_e2e.sh entirely if we think we can do that without impacting other workflows. Maybe that wont be possible due to other workflows though.

cc @dims @erikwilson

**Comment by erikwilson** [comment]
`saveResults` is probably never called due to `set -o errexit`, it can probably be fixed by adding a `set +e` or `set +o errexit` before line 70.

**Comment by johnSchnake** [comment]
Yes that is exactly why it is but in the past when I recommended removing/modifying the errexit code I've gotten pushback from a googler just due to convention: see https://github.com/kubernetes/kubernetes/pull/76039#discussion_r271507996

Just will add something like `... && ret=0 || ret=$?` to the lines that need this
