### ISSUE TITLE
Add the priority policy of least limits to scheduler

### ISSUE THREAD

**Issue by ximenzaoshi** [kubernetes/kubernetes#83285]
**What would you like to be added**:
In the scheduler's priority process, calculating one node's score based on the node's allocated pods' limits. The less the limits are, the higher score the node will get.
**Why is this needed**:
In a typical k8s cluster, most pods may be burstable, which means their limits >= requests. When scheduling these pods, we want to make the resource limits per node more even, avoiding to set too much resource limits on one node.

**Comment by draveness** [comment]
/assign

Are you requesting something like LeastResourceAllocation but score the nodes with `limits` instead of `requests`?

**Comment by ximenzaoshi** [comment]
yes, but maybe a little different.  The score should be caculated on a ratio like limit/capacity instead of a absolute value. I am not sure this request of feature is regular enough, just raise a discussion here.
