### ISSUE TITLE
kubectl cp : error: src doesn't exist in local filesystem

### ISSUE THREAD

**Issue by gauravjain59** [kubernetes/kubernetes#83287]
**What happened**:
kubectl cp from pod container to local file system always give below error
error: src doesn't exist in local filesystem

**What you expected to happen**:
should copy file from pod to local file system

**How to reproduce it (as minimally and precisely as possible)**:
kubectl cp pod:remote/file d:\local-folder -c container1 -n local-namespace

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by odinuge** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/77310
/sig cli
/closing

**Comment by PoornimaDevii** [comment]
Saw this issue when I tried copying directly from one pod to another. 

As an alternative try copying contents from the source pod to your local. Then from local to the destination pod.

kubectl cp <source-pod-name>:<path> <local-path> -n <namespace>
kubectl cp <same-local-path> <dest-pod-name>:<path> -n <namespace>

**Comment by BSVogler** [comment]
I got this error when attempting to copy a file using
`kubectl cp <source-namespace>/<source-pod-name>:<path> <dest-namespace>/<dest-pod-name>:<path>`
