### ISSUE TITLE
Adding support for _ (underscore) to the configmap metadata.name field

### ISSUE THREAD

**Issue by shubhamsre** [kubernetes/kubernetes#83290]
**What would you like to be added**:
Adding _ to the configmap name as configuration files that are fetched from various configuration management tools support it.

**Why is this needed**:
Allow underscore in configMapKeyRef key's #23722
When it is allowed in the configMapKeyRef key's, it should also be allowed in metadata.name field of configmap.

**ConfigMap File:** 
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap_test
data:
  Values1: config_dir
  Values2: service
```
**Error:** The ConfigMap "configmap_test" is invalid: metadata.name: Invalid value: "configmap_test": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**name: configmap_test <-- Why is underscore not allowed?**

From https://en.wikipedia.org/wiki/Hostname
```
While a hostname may not contain other characters, such as the underscore character (_),
other DNS names may contain the underscore.[5][6] Systems such as DomainKeys and 
service records use the underscore as a means to assure that their special character is 
not confused with hostnames. For example, _http._sctp.www.example.com specifies a 
service pointer for an SCTP-capable webserver host (www) in the domain example.com.
Notwithstanding the standard, Chrome, Firefox, Internet Explorer, Edge and Safari allow
underscores in hostnames, although cookies in IE do not work correctly if any part of 
the hostname contains an underscore character.[7]

However, it is valid to attempt to resolve a hostname that consists of an underscore.
E.g. _.example.com. This is used by RFC 7816 to reduce the amount of information 
that is made available to intermediate DNS servers during an iterative query[8].
The Query Name Minimisation feature is enabled by default in BIND 9.14.0[9].
```
From https://en.wikipedia.org/wiki/Domain_name#Domain_name_syntax 
```A valid hostname is also a valid domain name```

**Changes required** 
https://github.com/kubernetes/kubernetes/blob/654aa1d846a72ba842967424d287304db1dad803/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L110

Please correct me if I am wrong and if that is a standard.

**Comment by neolit123** [comment]
> Error: The ConfigMap "configmap_test" is invalid: metadata.name: Invalid value: "configmap_test": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(.a-z0-9?)*')

this error is misleading because TMK there is no such definition as a `DNS-1123 subdomain`, there is the [RFC-1123](https://tools.ietf.org/html/rfc1123), which applies it's naming restrictions to hostnames and not domain names.

if `dns1123LabelFmt` is following RFC-1123 then related errors and documentation should be updated that this regexp tolerates host names and a subset of domain names as per the RFC-1123 standard's clause 2.1 "Host Names and Numbers".

also `s/subdomain/domain/` because a subdomain is a domain too and it will pass as a valid RFC-1123 hostname.

https://stackoverflow.com/a/2183140

/sig network api-machinery

**Comment by ttfreeman** [comment]
This doesn't look like a kin/documentation? It's more a new feature request.

**Comment by neolit123** [comment]
it has to be documented possibly once / if this change goes in.

**Comment by ttfreeman** [comment]
@neolit123 I'd be happy to help as my first issue if you clarify exactly what I am supposed to do for the documentation side.

**Comment by neolit123** [comment]
> @neolit123 I'd be happy to help as my first issue if you clarify exactly what I am supposed to do for the documentation side.

thanks. the feature has to be enabled first before we document it.

**Comment by zeniri** [comment]
@neolit123 Do the changes in the validation.go file are the only changes or are there any more changes required? Please let me know that so that I can raise a PR against it.
@ttfreeman once this is passed you can document it.

**Comment by neolit123** [comment]
Hi, you need to ask the owners of this code. Their slack channel is
#sig-api-machinery.

**Comment by zeniri** [comment]
https://kubernetes.slack.com/archives/C0EG7JC6T/p1576651152067200
@neolit123 Link to thread in slack

**Comment by neolit123** [comment]
this received some comments here and the change was not approved:
https://kubernetes.slack.com/archives/C0EG7JC6T/p1576651152067200

/close
