### ISSUE TITLE
`kubectl get services` should warn the user if the service has no endpoints

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#8329]
It would be helpful if `kubectl get services` can warn the user when a service has no endpionts.

It would be even more useful If 'kubectl get services' prints out why a service has no endpoints. For example, in #8327, it will be helpful if 'kubectl get services' can report the service has no endpoints and points out the reason is that the pod is not ready.

@nikhiljindal @bgrant0607 @lavalamp

**Comment by pwittrock** [comment]
@monopole This would be a good one to get started

**Comment by pwittrock** [comment]
@monopole This is a good one to start with.

**Comment by monopole** [comment]
ack, on it

**Comment by pwittrock** [comment]
As monopole pointed out to me offline, kubectl get can't do this.  Describe already shows the endpoints @monopole.  Closing for now.
