### ISSUE TITLE
Add more scheduler metrics with different granularity

### ISSUE THREAD

**Issue by peter-wangxu** [kubernetes/kubernetes#83298]
**What would you like to be added**:
With the support of scheduler v2 support, we are now able to develop a lot of plugins out of tree. while the current metrics in sheduler lacks of state for plugins, for example, i need to know:
1. which plugins failed(the name, the type of error?)
2. how many errors occurred in different scheduling phase(prefilter,postfilter,prebind,postbind??)
3. also for main scheduler, we need to know why fail to scheduling? resource not enough, bind failure, or volumebinding failure. etc.
**Why is this needed**:
With above metrics and grafana/prometheus suport, we can easily know the scheduler and its plugin state.

Not sure if this deserve a KEP, please let me know.

**Comment by wgliang** [comment]
It is reasonable to count the number of calls and the time consumption of different scheduling stages. We also need to better understand the scheduling process and performance.

/assign

**Comment by ahg-g** [comment]
This is something @liu-cong is already working on as part of #82427. Lets track all metric-related improvements under one issue. How about we close this one and add all your requests to #82427.

@liu-cong, do you have a doc that you can share so that the community can make suggestions what other metrics we may want to add?

**Comment by liu-cong** [comment]
> This is something @liu-cong is already working on as part of #82427. Lets track all metric-related improvements under one issue. How about we close this one and add all your requests to #82427.
> 
> @liu-cong, do you have a doc that you can share so that the community can make suggestions what other metrics we may want to add?

Actually I am working on a doc that aims to include all metrics(existing and new) in scheduler. I am gonna share it shortly and create a master issue that tracks them all.

**Comment by liu-cong** [comment]
/close

I am closing this bug in favor of  #83356. I believe the request is covered there. If there is anything missing, please comment in  #83356 and we can track them all there.
