### ISSUE TITLE
Enhancement Request: Allow forcing a drain, even with PodDisruptionBudgets

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kubernetes#83307]
**What would you like to be added**:
Allow `kubectl drain` to have an additional flag (e.g. `--ignore-poddisruptionbudgets` or `--ignore-pdbs`) to allow a `drain` to drain pods off a node, even if they violate PodDisruptionBudgets

**Why is this needed**:
There are times where you want to drain pods off a node even if violating a PDB. For example, if you are running a one-worker node kubernetes cluster (not minikube), and you want to upgrade it. Or, like me, you are running a test cluster and want to scale down to zero nodes when you're not going to be using the cluster for a while in order to save costs.

If that worker node has a deployment with a PDB, then `kubectl drain` will get stuck as it cannot get rid of the pod while respecting the PDB, which is expected; but in this case, it is a hindrance.

Adding the switch will allow users to explicitly acknowledge that they want to ignore the PDBs (and accept the corresponding downtime for an application/service)

**Comment by pirminjanka** [comment]
+1

**Comment by dmlabs** [comment]
+1
Our company offers Kubernetes as PaaS. We manage Kubernetes, including IaaS OS updates and if a customer does not specify the PDB correctly, we are not able to drain the node for the OS updates.
A `--ignore-poddisruptionbudget` flag would be werry helpfull for our use case.

**Comment by michaelgugino** [comment]
I have created https://github.com/kubernetes/kubernetes/pull/85571 to address this.  This is a pretty simple implementation, but I think it achieves the desired results.

A suitable workflow would be: 1) Configure you component to use drain as normal 2) After some timeout, run drain with --disable-eviction option.

**Comment by huang-jy** [comment]
> I have created #85571 to address this. This is a pretty simple implementation, but I think it achieves the desired results.
> 
> A suitable workflow would be: 1) Configure you component to use drain as normal 2) After some timeout, run drain with --disable-eviction option.

I'll wait until the PR is merged and released before testing, but if I understand right, it would require me do this, right?

```
TIMEOUT=30s
DRAIN_ARGS="--delete-local-data --force --ignore-daemonsets"
timeout --kill-after=$TIMEOUT --signal=KILL kubectl drain $DRAIN_ARGS {nodename} || \
  kubectl drain $DRAIN_ARGS --disable-eviction {nodename}
```

**Comment by michaelgugino** [comment]
> Where `--disable-evict-after` implies that if the drain is still running after this time, switch to the `--disable-evict` mode _without having to call kubectl again_

I think that would require a sizeable refactor or add a great deal of complexity to the code, the same could be achieved with ```kubectl drain --timeout=30s ... || kubectl --disable-eviction ...```

In practical terms, I'm focused on automatic node remediation via destroying the node and getting a new one.  The timeout would be very large, the drain library is blocking, so I want it to fail quickly and requeue.  I'm going to be performing the calculation of when it's appropriate to evict/delete outside of the drain library, and I suspect most will be as well, so there's not really a great incentive to do it in the drain library itself IMO.

**Comment by huang-jy** [comment]
> I think that would require a sizeable refactor or add a great deal of complexity to the code, the same could be achieved with `kubectl drain --timeout=30s ... || kubectl --disable-eviction ...`

That's all good, I have no issue using the `--timeout` flag as long as `kubectl` does error out and return a non-zero code as expected (there's been a few times where it seems to error out, but still return 0)
