### ISSUE TITLE
kubelet service not starting

### ISSUE THREAD

**Issue by Ravibhardwaj05** [kubernetes/kubernetes#83308]
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-09-30 13:29:40 IST; 1s ago
     Docs: https://kubernetes.io/docs/
  Process: 12806 ExecStart=/usr/bin/kubelet (code=exited, status=255)
 Main PID: 12806 (code=exited, status=255)

Sep 30 13:29:40 kubeworker systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 30 13:29:40 kubeworker systemd[1]: Unit kubelet.service entered failed state.
Sep 30 13:29:40 kubeworker systemd[1]: kubelet.service failed.

**Comment by tedyu** [comment]
Which release are you using ?

**Comment by samkrish123** [comment]
I had similar issue, I just following following step.
Purge following application.
apt-get purge -y kubelet kubeadm kubectl  docker.

apt-get update && apt-get upgrade -y
apt-get install -y docker.io
apt-get install -y kubeadm=1.16.1-00 kubelet=1.16.1-00 kubectl=1.16.1-00 docker.io=1.16.1-00

Then it started working. 
Note: I was using Ubuntu 16.04, there is compatibility issue, so we need to update and upgrade package. I hope this will fix your issue as well.
