### ISSUE TITLE
kubectl error tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by gayathrimenathtcl** [kubernetes/kubernetes#83304]
**What happened**:
I am deploying an admission controller with kube-rbac-proxy as a sidecar container to validate the yaml before creating it. TLS has enabled [https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers](using this). I am getting a tls error while applying the yaml. 

> error when creating "test.yaml": Internal error occurred: failed calling webhook "test.testns.svc": tls: failed to find any PEM data in certificate input

I am able to log the certificate, but it is in not readable format.

**What you expected to happen**:
yaml creation should be success

**How to reproduce it (as minimally and precisely as possible)**:
Created an admission controller with TLS enabled and a proxy container kube-rbac-proxy which will upstream the requests to admission controller. Added the necessary argumants on kube-apiserver to support tls.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Major:"1", Minor:"13"
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7 Linux

**Comment by liggitt** [comment]
can you verify your CA bundle in the webhook YAML or JSON is the `base64-encoded version of the PEM-bundle` (so that base-64-decoding what is in the YAML/JSON displays PEM content)?

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#service-reference

**Comment by gayathrimenathtcl** [comment]
@liggitt The CA bundle is base64 encoded, and I am able to decode it and able to the same certificate.

**Comment by gayathrimenathtcl** [comment]
@liggitt The CA bundle in the webhook is base64 encoded.

**Comment by liggitt** [comment]
> @liggitt The CA bundle is base64 encoded, and I am able to decode it and get the same certificate.

when you base64-decode the caBundle content, do you get PEM content like this:
```
-----BEGIN CERTIFICATE-----
MIID...
```

**Comment by gayathrimenathtcl** [comment]
> > @liggitt The CA bundle is base64 encoded, and I am able to decode it and get the same certificate.
> 
> when you base64-decode the caBundle content, do you get PEM content like this:
> 
> ```
> -----BEGIN CERTIFICATE-----
> MIID...
> ```

Yes, I am getting like this.

> -----BEGIN CERTIFICATE-----
> ....
> -----END CERTIFICATE-----

**Comment by liggitt** [comment]
are you able to provide the yaml used for debugging?

**Comment by gayathrimenathtcl** [comment]
yes, I am getting error mentioned above while applying the yaml. Yaml creation getting failed.

**Comment by liggitt** [comment]
are you able to paste the yaml file here to assist in figuring out the issue?

**Comment by gayathrimenathtcl** [comment]
@liggitt It is a custom crd. I am using this to support one of my application

**Comment by liggitt** [comment]
can you provide the snippet of the admission controller yaml that contains the `caBundle` line, for debugging?

**Comment by gayathrimenathtcl** [comment]
I am adding cabundle via go code.

`	namespace, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
	if err != nil {
		glog.Info("error Reading Namespace")
	}
	cabundle, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
	if err != nil {
		glog.Info("error Reading Ca.crt")
	}
	fp := admissionregistration.Fail
	path := "/"
	service := &admissionregistration.ServiceReference{
		Name:      "test",
		Namespace: string(namespace),
		Path:      &path,
	}
	rules := []admissionregistration.RuleWithOperations{}
	rule := admissionregistration.RuleWithOperations{
		Operations: []admissionregistration.OperationType{"CREATE"},
		Rule: admissionregistration.Rule{
			APIGroups:   []string{"test.com"},
			APIVersions: []string{"v1alpha1"},
			Resources:   []string{"templates"},
			//Scope: admissionregistration.NamespacedScope,
		},
	}
	rules = append(rules, rule)
	webhooksarray := []admissionregistration.ValidatingWebhook{}
	webhook := admissionregistration.ValidatingWebhook{
		Name: "test.testns.svc",
		ClientConfig: admissionregistration.WebhookClientConfig{
			Service:  service,
			CABundle: cabundle,
		},
		Rules:         rules,
		FailurePolicy: &fp,
		
	}
	webhooksarray = append(webhooksarray, webhook)
	return &admissionregistration.ValidatingWebhookConfiguration{
		ObjectMeta: metav1.ObjectMeta{
			Name: "test",
		},
		Webhooks: webhooksarray,

	}`

**Comment by gayathrimenathtcl** [comment]
> can you provide the snippet of the admission controller yaml that contains the `caBundle` line, for debugging?

I am adding the cabundle via code.

```
namespace, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
if err != nil {
	glog.Info("error Reading Namespace")
}
cabundle, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
if err != nil {
	glog.Info("error Reading Ca.crt")
}
fp := admissionregistration.Fail
path := "/"
service := &admissionregistration.ServiceReference{
	Name:      "test",
	Namespace: string(namespace),
	Path:      &path,
}
rules := []admissionregistration.RuleWithOperations{}
rule := admissionregistration.RuleWithOperations{
	Operations: []admissionregistration.OperationType{"CREATE"},
	Rule: admissionregistration.Rule{
		APIGroups:   []string{"test.com"},
		APIVersions: []string{"v1alpha1"},
		Resources:   []string{"templates"},
	},
}
rules = append(rules, rule)
webhooksarray := []admissionregistration.ValidatingWebhook{}
webhook := admissionregistration.ValidatingWebhook{
	Name: "test.testns.svc",
	ClientConfig: admissionregistration.WebhookClientConfig{
		Service:  service,
		CABundle: cabundle,
	},
	Rules:         rules,
	FailurePolicy: &fp,
}
webhooksarray = append(webhooksarray, webhook)
return &admissionregistration.ValidatingWebhookConfiguration{
	ObjectMeta: metav1.ObjectMeta{
		Name: "test",
	},
	Webhooks: webhooksarray,

}
```

**Comment by liggitt** [comment]
interesting... and there is no error reading the /var/run/secrets/kubernetes.io/serviceaccount/ca.crt file?

**Comment by gayathrimenathtcl** [comment]
> interesting... and there is no error reading the /var/run/secrets/kubernetes.io/serviceaccount/ca.crt file?

No, I am able to see the base64 encoded certificate while describing `validatingwebhookconfigurations.admissionregistration.k8s.io`
