### ISSUE TITLE
Topology manager offer hints make pod bind cpuset fail.

### ISSUE THREAD

**Issue by PengTaoWW** [kubernetes/kubernetes#83311]
**What happened**:

I want to bind the CPU to which the numa node belongs, but the pod creation fails after specifying the number of CPUs in the yaml of the pod. The reason for the failure is Topology Affinity Error. I read the relevant code and found that a piece of code caused the hints generated by the topology manager to be unschedulable. If  delete it,  can successfully complete the binding I want.
![image](https://user-images.githubusercontent.com/24522133/65863052-06cfce80-e3a2-11e9-9e26-aab5ccebd6c8.png)
The comment is like this“ Special case PolicySingleNumaNode to only prefer hints where all providers have a single NUMA affinity set. ” I don't know why it is like this.

ps：

kubelet args：
`
./bin/kubelet   --address=0.0.0.0   --feature-gates=TopologyManager=true,CPUManager=true   --cpu-manager-policy=static   --topology-manager-policy=single-numa-node   --pod-infra-container-image=k8s.gcr.io/pause-amd64:3.1   --kubeconfig=./kubelet.kubeconfig   --logtostderr=true   --network-plugin=cni   --make-iptables-util-chains=false    --cert-dir=''   --v=2    --kube-reserved=cpu=1,memory=1Gi  --system-reserved=cpu=1,memory=1Gi --cgroup-driver=cgroupfs
`

pod.yaml:

`
      resources:
        limits:
          memory: "200Mi"
          cpu: "12"
`

**What you expected to happen**:
I want to bind the CPU I need directly according to the configuration.
![image](https://user-images.githubusercontent.com/24522133/65863593-fa984100-e3a2-11e9-9124-ea7c88ca9f88.png)

**How to reproduce it (as minimally and precisely as possible)**:

take pod.yaml like me, and kubelet use my args

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zouyee** [comment]
This pod must runs in the Guaranteed QoS class which requests are equal to limits

**Comment by PengTaoWW** [comment]
@zouyee this case run pod in the Guaranteed QoS class which requests are equal to limits。but still wrong

**Comment by zouyee** [comment]
<details>
  <summary>busybox mainfest for test and result</summary>
  ```apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: default
spec:
  containers:
  - args:
    - sh
    image: busybox:1.29
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "2"
        memory: 1Gi
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: paasn1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
```
 cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0-1,4-7","entries":{"b428b696aa0bda2565950fbbe4bc113f43c46e8f12080d2137a89d1dd6a76dfe":"2-3"},"checksum":2302528297}
```
</details>

**Comment by PengTaoWW** [comment]
https://github.com/kubernetes/kubernetes/pull/83751 look like fixed
