### ISSUE TITLE
[k8s.io] [sig-node] kubelet [k8s.io] [sig-node] Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s.

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#83316]
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness
**Which test(s) are failing**:

[k8s.io] [sig-node] kubelet [k8s.io] [sig-node] Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s.
**Since when has it been failing**:
2019-09-26
**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1177191542352252931

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet.go:308
Sep 29 12:41:34.198: Unexpected error:
    <*errors.errorString | 0xc0000af060>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/kubelet.go:321
```
**Anything else we need to know**:

/cc @kubernetes/sig-node-bugs

**Comment by alenkacz** [comment]
is there someone who can pick this up since it's constantly failing in the master-informing? Thanks :)

**Comment by mborsz** [comment]
@dchen1107 Could you help us here?

**Comment by liyanhui1228** [comment]
Looked into the test logs, and it seems like the `numNodes` in `kubelet.go` was accidentally removed in [this commit](https://github.com/kubernetes/kubernetes/commit/3c445b2ad0fe87b5c21fd00c5b08e619b26bad9a), which caused its value to be 0.

As the current log is showing:
```
Creating a RC of 0 pods and wait until all pods of this RC are running
```
And last succeeded test log is:
```
Creating a RC of 100 pods and wait until all pods of this RC are running
```

**Comment by wojtek-t** [comment]
It seems that this PR didn't help.
This run already contains this PR and it failed:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1179728189669249025

**Comment by cheftako** [comment]
I0926 12:39:42.660] I0926 12:35:26.532235   10594 trace.go:116] Trace[1804745705]: "Reflector ListAndWatch" name:k8s.io/kubernetes/test/utils/pod_store.go:56 (started: 2019-09-26 12:33:26.531728309 +0000 UTC m=+1132.795092692) (total time: 2m0.000301191s):

**Comment by cheftako** [comment]
Seems like the test is timing out creating the pods and reflector to watch those pods.

**Comment by cheftako** [comment]
Looks like the section of code taking a long time is https://github.com/kubernetes/kubernetes/blob/8f968c41d29c9fb2a322825b0e2c19ed7e589966/staging/src/k8s.io/client-go/tools/cache/reflector.go#L194

**Comment by cheftako** [comment]
Checked KAS log and seeing about 7000 requests of the form 

I1010 12:26:59.668321       1 httplog.go:90] GET /api/v1/nodes/gce-scale-cluster-minion-group-1-4p2m:10250/proxy/stats/summary: (9.753712ms) 200 [e2e.test/v1.17.0 (linux/amd64) kubernetes/3edbc6a -- [k8s.io] [sig-node] kubelet [k8s.io] [sig-node] Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s. 146.148.73.158:37248]

between replicationcontroller being created and the pod list/watch request.

**Comment by roycaihw** [comment]
I think this is related:

https://github.com/kubernetes/kubernetes/blob/948870b5840add1ba4068e3d27d54ea353839992/test/e2e/node/kubelet.go#L277-L283
