### ISSUE TITLE
Test framework should support custom taints during testing

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#83329]
**What would you like to be added**:
A flag/config option for the framework which allows you to specify taints which should be supported by workloads.

What we would do is create a mutating webhook which would ensure pods tolerate a given list of taints. After the tests are completed, the webhook would be removed.

**Why is this needed**:
This helps users who run in heavily tainted environments continue to run the test suite.

This is a follow-up issue based on the discussion here: https://github.com/kubernetes/kubernetes/pull/81043#discussion_r311337164

/area conformance
/area e2e-framework
/sig testing
/priority important-soon

**Comment by rahul-kumi** [comment]
@johnSchnake, this issue is still relevant to run e2e tests on a live cluster with taints enabled.

How to get the respective SIG to take note of this issue?
