### ISSUE TITLE
"No ref for container" during pod deletion

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/kubernetes#83336]
**What happened**:

When deleting a pod, we require accurate containerStatus information in the pod status so that we can ensure orderly deletion of containers during our preStop hooks. However, it seems that sometimes kubelet gets into a bad state during pod termination and stops syncing container status updates. Logging messages like:
```
W0930 19:50:28.703232    8155 prober.go:103] No ref for container "docker://1de231b5d38a351208c118e8141da4de5b800843651ed5a08f20d2598d2f5c32" (todo-0-2_vt(13710f39-e3ba-11e9-b252-12f29d1d849c):vttablet)
```
The container in that log line was indeed successfully killed and you could still `docker inspect` it from the docker daemon.

**What you expected to happen**:

When containers finish terminating, they should be marked as terminated in the containerStatuses list.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I'm kind of wondering if the issue is that kubelet is filtering away non-running containers when querying dockerd, making it unable to get the container's status. If I run a dockerd with debug logs on, I see:
```
time="2019-09-30T20:52:16.066345810Z" level=debug msg="Calling GET /v1.38/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
time="2019-09-30T20:52:16.073138176Z" level=debug msg="Calling GET /v1.38/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%7D&limit=0"
time="2019-09-30T20:52:16.093795163Z" level=debug msg="Calling GET /v1.38/containers/json?filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
time="2019-09-30T20:52:16.099623969Z" level=debug msg="Calling GET /v1.38/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%2C%22status%22%3A%7B%22running%22%3Atrue%7D%7D&limit=0"
```
so for at least one of those queries it's filtering by status=running. Maybe it meant to make a different query?

Also note that restarting kubelet causes the status updates to recover correctly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.10
- Cloud provider or hardware configuration: ec2
- OS (e.g: `cat /etc/os-release`): custom
- Kernel (e.g. `uname -a`): 4.14.143
- Install tools: custom
- Network plugin and version (if this is a network-related bug): NA
- docker version: 18.06.3-ce

**Comment by pietdaniel** [comment]
We've seen this issue as a bug of old `containerd` versions. We couldn't delete a pod using an image which has been garbage collected. Force deleting the container on the host has resolved this. Not sure if this helps your use case though.
