### ISSUE TITLE
Volume limits can be shared among several CSI drivers

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#83351]
**What would you like to be added**:
iSCSI CSI driver from various vendors should share limit of volumes that can be attached to a  node - all of them will share the same iscsid daemon on the node and/or any iSCSI initiator HW.

Note that we don't have any limit for in-tree iSCSI volumes and nobody has complained so far. 

/sig storage

**Comment by jsafrane** [comment]
It may be solved by documentation, e.g. by recommending all the CSI drivers to have the limit configurable so cluster admins may distribute the volume limit to individual drivers according to their individual needs and calculations.

**Comment by msau42** [comment]
@kubernetes/sig-storage-misc 
Let's document some recommendations in https://github.com/kubernetes/website/pull/17432
cc @bertinatto

**Comment by jsafrane** [comment]
> Let's document some recommendations in kubernetes/website#17432

Since it's CSI driver vendor thing, it should be covered also in https://github.com/kubernetes-csi/docs.

**Comment by bertinatto** [comment]
So we tried to address this through docs, as suggested in https://github.com/kubernetes/kubernetes/issues/83351#issuecomment-536941626.

Closing, feel free to re-open if you disagree.

/close
