### ISSUE TITLE
[migration] possibly refactor EvenPodSpread and PodAffinity priority functions

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83361]
Currently EvenPodsSpread and PodAffinity priority functions use the old priority function interface, which is not compatible with the framework's Score/NormalizeScore interfaces that we plan to migrate to eventually.

During the first stage of migration to the scheduler's framework, we plan to call predicates/priorities functions directly from their equivalent framework plugins. There are two approaches to do that for :

1) Refactor EvenPodsSpread and PodAffinity priority functions to use the map/reduce pattern, which maps well to Score/NormalizeScore once we start moving the code to the plugins in the second phase of framework migration.

2) Hack EvenPodsSpread and PodAffinity in the framework as a NormalizeScorePlugin, basically return success for Score, and do all the work in NormalizeScore.

I prefer we go with the first approach.

/assign 
/assign @Huang-Wei 
/sig scheduling

**Comment by Huang-Wei** [comment]
I will evaluate the migration efforts first and come back with a high-level implementation plan.

**Comment by ahg-g** [comment]
Thanks Huang, as discussed offline, I will take a look at the inter-pod affinity one.

**Comment by hprateek43** [comment]
@ahg-g @Huang-Wei Do we have a roadmap around this ? Im looking to pick up this issue

**Comment by Huang-Wei** [comment]
@hprateek43 I'm working on the EvenPodsSpread part. Will send out a PR this week.

**Comment by ahg-g** [comment]
This is done.
