### ISSUE TITLE
kubectl version output does not allow jsonpath

### ISSUE THREAD

**Issue by Joseph-Goergen** [kubernetes/kubernetes#83360]
**What would you like to be added**:
`kubectl version -o jsonpath ...`
It is currently not supported but is expected to be support

**Why is this needed**:
So someone can easily grab the information presented (such as server version) when running the command `kubectl version` without resorting to output the json then `jq` on that result

/sig cli

**Comment by MartinKaburu** [comment]
Hey @Joseph-Goergen 
Have you tried `kubectl version --output=json`
It returns the output in json. Many command utilities allow you to grab info easily from this

**Comment by Joseph-Goergen** [comment]
Yea, I know you can get the output to json and then do what you want from there. I just used `jsonpath` for a few other kubectl operations and found it odd that `kubectl version` was excluded from that. Either way, not a big deal, just thought you guys would like to know (in case you guys didn't).

**Comment by qalinn** [comment]
Any update on this ticket?
