### ISSUE TITLE
Support for /watch in api paths should be removed

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#8337]
I still see watch in the path at many places: http://kubernetes.io/third_party/swagger-ui/#!/v1beta3/watchEndpointslist

I know we were working on making it a query param and removing it from the path.

@smarterclayton @bgrant0607

**Comment by smarterclayton** [comment]
Once we drop v1beta1/2 we should switch all the clients to using the new query parameter.

----- Original Message -----

**Comment by nikhiljindal** [comment]
Do we want to support both: as a query param and in path for v1beta3 and v1?

**Comment by smarterclayton** [comment]
I would prefer not to.  Although we don't support watch on a single resource with the query param option (you have to pass metadata.name).  That's slightly less user friendly.  The benefit is that everything for watch goes through the same path.  @lavalamp probably has an opinion.

----- Original Message -----

**Comment by lavalamp** [comment]
Is there a compelling reason for using a query parameter as opposed to a custom verb?

**Comment by smarterclayton** [comment]
Not having a custom verb, clear versioning, general restfulness.  It makes admission control and policy easier to reason about.  Watch returns a list of events which are another representation of the object.

With that change we would not have any custom verbs (proxy is a subresource now for pods and nodes).

**Comment by bgrant0607** [comment]
Ref #8087

**Comment by nikhiljindal** [comment]
IIUC, Shouldnt this be part of https://github.com/GoogleCloudPlatform/kubernetes/issues/7018 as well to not support watch in path in v1?

**Comment by bgrant0607** [comment]
Watch is already supported as a query parameter. Eliminating the legacy form is part of getting rid of the legacy versions.

**Comment by davidopp** [comment]
We should re-title this issue to make it clearer, so someone can pick it up (it is currently unassigned and marked for 1.0). IIUC from @bgrant0607 's last entry, the work here is simply to remove watch-in-the-path everywhere. Is that right?

**Comment by bgrant0607** [comment]
@smarterclayton Could someone from Redhat tackle this?

**Comment by smarterclayton** [comment]
Yeah

**Comment by brendandburns** [comment]
@smarterclayton @bgrant0607 
Is this in flight?  Is this just going to happen by default when we disable v1beta3?

**Comment by bgrant0607** [comment]
We're not working on it here.

No, it won't happen for free. The registration of the paths is unconditional:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/api_installer.go#L308

Actually, @caesarxuchao was looking for something to do now that the v1 api is done.

**Comment by bgrant0607** [comment]
IIRC, watch using the query param was added by PR #5763

**Comment by smarterclayton** [comment]
If we could memoize APIRequestInfo for use in both the limit check and the authorizer then I would say we should do that.  In theory the context for a request should be populated early with the desired API request (version, resource, etc) structure, then all the subordinate / wrapped handlers can reuse that.  The ultimate goal is to be able to make intelligent statements about a request before it is processed by the authenticator / authorizer / limiter / metrics / API serving code, and to do so consistently across all of them.  

If we moved the authorizer logic into an early stage filter for the API server, that would accomplish part of that goal, although it's still very difficult to ensure all requests are properly authenticated.  @deads2k and @liggitt and I went around and around on this and establishing APIRequestInfo early (and reusing it later, or at least testing it is consistent with what is served) is still probably the best way forward.

Possibly a post 1.0 thing, but:

1. Decompose request early into APIRequestInfo and store with the context
2. Use precalc'd APIRequestInfo in limiter and authorizer
3. Have API server check the request info matches the expected call
4. Rate limiter can check known endpoints ("subresource" in "proxy,logs,exec", "method"="get" and "hasparam="watch") and limit independently (we need to limit the first 3 as well).

Long term I think we need changes to our HTTP server code to let us set timeouts per connection / request more effectively as well.

**Comment by bgrant0607** [comment]
@smarterclayton Perhaps you intended to post your [latest comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/8337#issuecomment-109781954) to another issue?

**Comment by smarterclayton** [comment]
It was combining https://github.com/GoogleCloudPlatform/kubernetes/pull/6207 which rate limited watch separately, with the removal of the thing that allow watches to be detected.  We need a better way to unambiguously identify watch requests so that they can be rate limited in a separate bucket.  If we remove watch here we have no effective way to bucket regular calls and watch calls separately, so in theory watches can exhaust the regular pool of the apiserver rate limiter.  We can look for the "watch" query param in the short term, but that doesn't fix "pod/proxy" or "pod/exec" or "pod/logs" which are all bound in the same rate limit.

**Comment by smarterclayton** [comment]
Spawned https://github.com/GoogleCloudPlatform/kubernetes/issues/9403

**Comment by caesarxuchao** [comment]
Hi @smarterclayton, I'm trying to remove the "watch" from the path for api versions starting from v1. I guess this should be done in a similar fashion as how the apiserver tells whether namespace should be in the path or as a query, which is encoded in RESTScopeName. Shall I add a similar field in RESTScope for "watch", or is there any better way to handle this? Thanks.

**Comment by bgrant0607** [comment]
This change seems risky, so punting from 1.0.

**Comment by caesarxuchao** [comment]
I will work on this later. Just for the record, in test/integration/client_test.go, in func TestSingleWatch, I modify the watch request from:
```
		w, err = client.Get().
			Prefix("watch").
			NamespaceIfScoped(ns, len(ns) > 0).
			Resource("events").
			Name("event-9").
			Param("resourceVersion", rv1).
			Watch()
```
to:
```
		w, err = client.Get().
			NamespaceIfScoped(ns, len(ns) > 0).
			Resource("events").
			Name("event-9").
			Param("resourceVersion", rv1).
			Param("watch", "true").
			Watch()
```
and I get error
```
client_test.go:179: Watch channel closed unexpectedly.
```

@smarterclayton Do you have any suggestions? Thanks.

**Comment by bgrant0607** [comment]
All our clients still use `Prefix("watch")`, AFAICT. We need to convert them to `Param("watch", "true")`.

Also, does the query-param form of watch work for watching individual objects?

**Comment by smarterclayton** [comment]
No, you'd need to list with "fields"="metadata.name" (which is what individual watch is a shortcut for)

----- Original Message -----

**Comment by caesarxuchao** [comment]
As a first step, I will update the occurrences of "watching on a list" in the client code to use query param.

**Comment by bgrant0607** [comment]
Ok, that is consistent with my reading of the code. Only ListResources implements watch.

**Comment by lavalamp** [comment]
@krousey can you do an audit of the code to see if there's work to be done here? It would be good to finish this for 1.2 if it's no longer risky.

**Comment by liggitt** [comment]
to be clear, this is for removing use of it, not support for it under `/v1/watch/...`, correct?

**Comment by lavalamp** [comment]
@liggitt If you think we're still using it, I'll just kick it out of the milestone now...

Actually, I think we should just not support this for non-v1 paths, and never remove it from the v1 paths, that would be a breaking change.

On further thought I don't think we should spend time on this right now.

**Comment by lavalamp** [comment]
Action item: make api installer not have the watch/ path for any new APIs or api versions.

**Comment by liggitt** [comment]
> I think we should just not support this for non-v1 paths, and never remove it from the v1 paths, that would be a breaking change.

exactly

**Comment by ghodss** [comment]
Another more immediate action item here is that right now, this works as expected:

`/api/v1/namespaces/default/pods?resourceVersion=6374&watch=true`

... results in a watch on the pod list.

But the same thing with a pod name appended:

`/api/v1/namespaces/default/pods/hello-www-2798522470-18wnc?resourceVersion=6374&watch=true`

...simply returns the pod without a watch. Expected is that it would give you a watch, as above.

This does work:

`/api/v1/watch/namespaces/default/pods/hello-www-2798522470-18wnc?resourceVersion=6374&watch=true`

This pattern and result seems to hold true for all objects, including those in /apis/extensions/v1beta1 (e.g. deployment).

+1 on removing the watch verb (another benefit of param over verb is that selfLink works very nicely with simply appending a watch param), especially in extensions/v1beta1, but in the mean time, it would be good to add proper support for the watch param for individual items.

**Comment by liggitt** [comment]
Watch on an individual item has weird semantics if the item doesn't exist. Watching the list filtered to the item is more consistent.

**Comment by liggitt** [comment]
All in tree clients were converted to use the watch param in https://github.com/kubernetes/kubernetes/pull/41722

**Comment by smarterclayton** [comment]
Definitely the oldest feature we've been trying to deprecate and remove
