### ISSUE TITLE
Improper use of SuggestsClientDelay in api-server GenericWebhook

### ISSUE THREAD

**Issue by shturec** [kubernetes/kubernetes#83377]
**What would you like to be added**:
Fix the improper use of [`SuggestsClientDelay`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L596-L616) for request retries in [`GenericWebhook`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L113-L120).

**Why is this needed**:
An earlier fix (https://github.com/kubernetes/kubernetes/commit/04846cc25b862c1eabff03ea0b11cbf2f7fae8e2) emphasizes on the fact that the [`SuggestsClientDelay`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L596-L616) function merely suggests a delay and is not instruction for the operation after that, i.e. it's not necessarily a **retry** trigger. Quoting its doc: `It does not address whether the error *should* be retried, since some errors (like a 3xx) may request delay without retry.`. Therefore `SuggestsClientDelay` cannot be used alone to figure if an error hints a retriable request, without analyzing further the actual error semantics.

The timeout period returned by `SuggestsClientDelay` for an error identified as _retriable_, can hardly be used in the webhook client context without risking the endpoint responsiveness. Using the timeout provided by an out-of-tree webhook may effectively stall the client in retry mode with enormous wait timeouts. Whether such misconfigurations are an acceptable risk depends on where you draw the security boundary, i.e. are webhooks considered highly trusted extension of the api server security domain. A question that may have different answers in self-hosted and managed k8s offerings.

Considering there is no point in retrying requests, if a provided `Retry-After` header timeout is not respected, `SuggestsClientDelay` should not be employed for retry guard condition checks. Otherwise, the timeouts suggested by the header should be respected, but only after a more careful analysis of the response confirms that a **retry** is expected.

There are a couple of more inconsistencies that need to be addressed wrt retries on error. Considering that _retriable_ API errors are those that feature [`RetryAfterSeconds`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L658), the error type [check](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L114) in `GenericWebhook`'s `WithExponentialBackoff` func is inconsistent:
- `StatusReasonInternalError` - neither the [status reason definition](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L799-L804), nor the [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.6.1), nor the [factory function](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L321-L332) suggest retriable action. Unless there are other valid reasons it should be removed from the retry criteria;
- `StatusReasonRequestEntityTooLarge`  - [RFC 7231 suggests](https://tools.ietf.org/html/rfc7231#section-6.5.11) that the `413` error code affiliated with this reason MAY indicate a _retry after_ period, i.e. it should be considered in the retry criteria too.

And finally, `StatusReasonTooManyRequests` is not considered in the tests for the `WithExponentialBackoff` yet.

/sig api-machinery
/sig auth

**Comment by shturec** [comment]
Let me try to rephrase and add to that.

Currently, the default `ShouldRetry` implementation for handling transient errors is to retry on connection reset error, `429`, `500`, `504` http errors and on errors that suggest client delay (i.e. http responses with error code > `399` that had header `Retry-After`) in that order. 

There are a couple of issues in that approach. 
- Using error codes to discriminate transient errors implies non-standard assumptions for the webhooks implementations
For example, it is not clear why the pretty generic `Internal Server Error` (`500`) is considered transient. None of its semantics implies that. Equally, why `Service Unavailable` (`503`) is not, while RFC7231 suggests that it may well be, is also not clear. Same for `Payload Too Large` (`413`). The RFC rather relies on the `Retry-After` header to signal transient characteristic. If the webhook clients add to that, that's not standard and should be surfaced e.g. through better documentation how to write webhooks for such clients. 
- `Retry-After` header is not used on purpose
The [SuggestsClientDelay](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L596-L616) func resolves errors that make use of `Retry-After` header to signal when would be appropriate time to make another attempt to contact the server. In the `ShouldRetry` default implementation it is used merely as a hint that a retry may be performed. The timeout for the next attempt suggested by the header is completely ignored in favor to a hard-coded exponential backoff policy. That may be equally inadequate as not retrying at all. Consider for a moment that a webhook sends a `Retry-After` header with value 3600 seconds (1h). The current implementation will make 5 completely useless attempts to call the webhook because they will all hit the webhook way before the suggested timeout. The fact that `Retry-After` can be used to trigger retry when used with error code and how the `GenericWebhook` client will react is not evident at all too.

One way to approach the situation is to document how to write transient errors handling. But some changes may go further:
- Completely remove the http errors considered semantically transient and start relying on a header for that. Or change it to comprise `413 Payload Too Large`, `429 Too Many Requests`, `503 Service Unavailable` and `504 Gateway Timeout` to stick closer to the RFC suggestions.
- Reconsider how `Retry-After` is used. There are multiple possible approaches here:
    - Respect the hints for timeout before retrying encoded in the `Retry-After` header. The upside here is that it may help tuning the client-server communication a lot. But a number of things need to be considered too. For example, how to handle inappropriate timeouts that may have detrimental effect on the API server? How does that affect the exponential backoff? How such change affects existing implementations?
    - Keep current hard-coded behavior, but introduce custom header with clear semantics (e.g. `Retry` with an irrelevant value). The upside here is the clarity in expectations. The downside is that it's still non-standard. It will not be directly compatible with existing implementations using `Retry-After`.

**Comment by g-pavlov** [comment]
/reopen

It would be great at least to have some statement from assignee already or reassign to somebody who could actually move this forward with argumentation for closing or fixing.

**Comment by shturec** [comment]
/reopen

It would be great at least to have some statement from assignee already or reassign to somebody who could actually move this forward with argumentation for closing or fixing.
