### ISSUE TITLE
nfs provisioner tests failing in alpha clusters

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#83380]
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-alpha-enabled-default

**Which test(s) are failing**:
all nfs provisioner tests

**Since when has it been failing**:
10/1/2019

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-alpha-enabled-default
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1179132062376923138

**Reason for failure**:
tbd

**Anything else we need to know**:

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures 
cc @wongma7 @jsafrane

**Comment by wongma7** [comment]
fix on the way, https://github.com/kubernetes/kubernetes/pull/81093 got merged but when it rebased the version wasn't updated (needs to be v2.2.2 for that selflink thing)
