### ISSUE TITLE
Update PVC after manually resizing a local volume

### ISSUE THREAD

**Issue by lalinsky** [kubernetes/kubernetes#83392]
**What happened**:

1. I create a local PersistentVolume with size 1Gi
2. I create a StatefulSet with persitentVolumeClaimTemplate asking for 1Gi volume
3. I resize the local PersistentVolume to 2Gi
4. I can't update the PersistentVolumeClaim to 2Gi, even though the volume it's bound is large enough, claiming only dynamically provisioned volumes can be resized

**What you expected to happen**:

When the bound volume matches the required size, editing PersistentVolumeClaim should allow me to resize it.

It could even update the capacity manually, after the volume has been resized.

**How to reproduce it (as minimally and precisely as possible)**:

```console
$ lvcreate -L1Gi -ntest1 vg0
$ mkfs.ext4 /dev/vg0/test1
$ mkdir /mnt/test1
$ mount /dev/vg0/test1 /mnt/test1

$ kubectl apply -f step1.yaml

$ kubectl get pv/test1
NAME    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM            STORAGECLASS   REASON   AGE
test1   1Gi        RWO            Retain           Bound    acoustid/test1   test1                   3s

$ kubectl get pvc/test1
NAME    STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test1   Bound    test1    1Gi        RWO            test1          3s

$ lvresize -L2Gi /dev/vg0/test1
$ resize2fs /dev/vg0/test1

$ kubectl apply -f step2.yaml

$ kubectl get pv/test1
NAME    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM            STORAGECLASS   REASON   AGE
test1   2Gi        RWO            Retain           Bound    acoustid/test1   test1                   10s

$ kubectl get pvc/test1
NAME    STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test1   Bound    test1    1Gi        RWO            test1          10s

$ kubectl apply -f step3.yaml
...
for: "step3.yaml": persistentvolumeclaims "test1" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

step1.yaml:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test1
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /mnt/test1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - h8
  persistentVolumeReclaimPolicy: Retain
  storageClassName: test1
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: test1
```

step2.yaml:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  local:
    path: /mnt/test1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - h8
  persistentVolumeReclaimPolicy: Retain
  storageClassName: test1
  volumeMode: Filesystem
```

step3.yaml:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: test1
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6
- Cloud provider or hardware configuration: Custom hardwade
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 4.15.0-64-generic
- Install tools: RKE

**Comment by lalinsky** [comment]
@kubernetes/sig-storage-bugs

**Comment by Stephane-Thales** [comment]
Dear @lalinsky ,
Did you found a fix to this issue ?
Does the resizing now work ?

**Comment by lalinsky** [comment]
@Stephane-Thales No, I didn't find solution.

**Comment by lknaubkonrad** [comment]
Does not appear to be supported for local-storage.  I've tried several approaches using HostPath and Local volumes without success. 
  https://kubernetes.cn/docs/concepts/storage/storage-classes/
If anyone has found CSI sidecars or external controllers to work please let me know.

**Comment by lknaubkonrad** [comment]
I was able to successfully expand/decrease storage capacity for PVC by doing the following on a PostgreSQL pod:
kubectl patch statefulset <> -n <>  -p '{"spec":{"replicas":0}}'
kubectl delete pvc -n <> <pvc name>
kubectl edit pv <pv name> - update the capacity/storage
kubectl apply -f <pvc>.yaml
kubectl patch statefulset <> -n <>  -p '{"spec":{"replicas":1}}'
