### ISSUE TITLE
Add a metric to track scheduler cache size

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#83404]
**What would you like to be added**:
Add a metric to track scheduler cache size.

metric name | metric definition | Description
-- | -- | --
scheduler_cache_size | Type: Gauge Labels: type={“nodes”,”pods”,”assumed_pods”} | Number of elements in scheduler cache.

**Why is this needed**:
Gives better observability of scheduler cache. For, the number of "assumed_pods" gives us an idea of how many pods are "assumed" and therefore being "bound". We can compare this with number of [binding goroutines](https://github.com/kubernetes/kubernetes/issues/83403) to make sure assume-bind works as expected.

/sig scheduling

**Comment by damemi** [comment]
Is anyone already working on these metrics? If not I'd like to help out
/assign

**Comment by liu-cong** [comment]
Thanks @damemi .

Feel free to work on this one. Just a reminder, we may need feedback/approval from sig-instrumentation.
