### ISSUE TITLE
Add result code and failed plugins labels to scheduler attempt metric

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#83411]
**What would you like to be added**:

metric name | metric definition | Description
-- | -- | --
schedule_attempts_total | Type: CounterLabels: result={“scheduled”, “unschedulable”, “error”}extension_point={“prefilter”, “filter”, ...}name={plugin name} | Number of scheduling attempts by the result.

**Why is this needed**:
Right now this metric only has 3 possible result labels: “scheduled”, “unschedulable”, “error”. There are more [result codes](https://github.com/kubernetes/kubernetes/blob/89f936f6ac3af4ee8a9c00d3c4e1745f448e2c05/pkg/scheduler/framework/v1alpha1/interface.go#L53).
When the result is not "scheduled", we would also like to know which plugin and extension point caused this.

/sig scheduling

**Comment by ahg-g** [comment]
It is likely that the other codes are irrelevant, final result should one of the three existing ones anyways.

**Comment by liu-cong** [comment]
actually we may not need this. we will have a metric to record plugin results. This metric provides an "overview" of results, while the plugin specific result provide more details into which plugin causes error/unschedulable. 

I will hold on this.

/hold

**Comment by liu-cong** [comment]
/close

The framework metrics can provide more details on failures on each extension point and plugin. Keeping `schedule_attempts_total` as is is probably better.
