### ISSUE TITLE
Inconsistency in PredicateFailureError Usage

### ISSUE THREAD

**Issue by ahmad-diaa** [kubernetes/kubernetes#83425]
The field `PredicateName` in Type `PredicateFailureError` is used inconsistently
https://github.com/kubernetes/kubernetes/blob/0960c74c3788b1724bd7e7b9933bc49c7e5b5afa/pkg/scheduler/algorithm/predicates/error.go#L120-L124

For example sometimes it does not have a valid predicate name in some cases
https://github.com/kubernetes/kubernetes/blob/0960c74c3788b1724bd7e7b9933bc49c7e5b5afa/pkg/scheduler/algorithm/predicates/error.go#L43

On the other hand, the error function is using it as valid predicate names
https://github.com/kubernetes/kubernetes/blob/0960c74c3788b1724bd7e7b9933bc49c7e5b5afa/pkg/scheduler/algorithm/predicates/error.go#L130-L132

What is the right behavior here? Should the struct fields be changed  as well as the `Error` function so it is less confusing? or Is it better to change the errors not matching their predicate names?

/kind bug
/sig scheduling

**Comment by ahmad-diaa** [comment]
cc @liu-cong

**Comment by liu-cong** [comment]
Looking at how `PredicateFailureError` is used, it's used as failure "reason"
https://github.com/kubernetes/kubernetes/blob/b82a1d46003bf38f13cab864c0be09feefd27c4f/pkg/kubelet/lifecycle/predicate.go#L130
which is used to populate pod status
https://github.com/kubernetes/kubernetes/blob/3948f16ff4060955b7f25d26d261b99589963ade/pkg/kubelet/kubelet.go#L1777
And interestingly, it does provide a GetReason() method
https://github.com/kubernetes/kubernetes/blob/e0e3889d745039b73c9a2bb981c6a5201e64cf1b/pkg/scheduler/algorithm/predicates/error.go#L135



My suggestion is:
* do not directly export the `PredicateName` and `PredicateDesc` fields, and `PredicateDesc`  should probably be renamed to `reason` 
* provide `GetReason()`, `GetPredicateName()` methods and let the caller use them wherever appropriate. These method could return the corresponding fields directly or they can provide a calculated string based on the fields, if that's desired. 
* when passing the `predicateName` like 
https://github.com/kubernetes/kubernetes/blob/e0e3889d745039b73c9a2bb981c6a5201e64cf1b/pkg/scheduler/algorithm/predicates/error.go#L43
, use the predicate name constants defined in `predicate.go`, like so
https://github.com/kubernetes/kubernetes/blob/7cb4850699a4a3c1008382c8b05f245b66ce19ad/pkg/scheduler/algorithm/predicates/predicates.go#L56

**Comment by alculquicondor** [comment]
I'm ok with exporting the fields, but:

- +1 to renaming `PredicateDesc` to `reason` or `Reason`.
- +1 to use the constants

And also: any usage of the field `err.PredicateName` should make it clear that it's referring to the name of the predicate, not the state of the pod.

cc @ahg-g

**Comment by ahmad-diaa** [comment]
I think unexporting the fields could be useful to decrease the possibility misusing the fields once more

**Comment by xiexiaojing** [comment]
1，Renaming PredicateDesc to reason or Reason.
2，Unexporting the fields
If these two are the right thing to do, there should be a new one to do the right thing. And the old one is better to export the field  less confusingly.

**Comment by ahg-g** [comment]
All uses of PredicateFailureError will change to framework.Status. We can wait until that is the case, or if you feel strongly about it, we can now do what Cong and Aldo are suggesting.

**Comment by draveness** [comment]
> All uses of PredicateFailureError will change to framework.Status. We can wait until that is the case, or if you feel strongly about it, we can now do what Cong and Aldo are suggesting.

+1 on waiting, even if we change the predicate failure now, we can't deliver the patch to users since we are in the middle of a release. We can change to `framework.Status` directly and save the effort of doing redundant work.

**Comment by ahmad-diaa** [comment]
+1 on waiting as well, doesn't make sense to change it if it's going to change to `framework.Status` in the same release.

**Comment by alculquicondor** [comment]
We seem to have an consensus

/close
