### ISSUE TITLE
Kube-apiserver request timeouts are double-counted into request metrics

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#83424]
**What happened**:

When the kube-apiserver timeouts on a request, we end up doubling the counts measured in [`MonitorRequest()`](https://github.com/kubernetes/kubernetes/blob/release-1.16/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L287-L302):

 - apiserver_request_counts
 - apiserver_request_total
 - apiserver_request_latencies
 - apiserver_request_latencies_summary
 - apiserver_request_duration_seconds
 - apiserver_response_sizes

**What you expected to happen**:

We only count our requests a single time in our metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Add a 60 second sleep in the func [InstrumentRouteFunc](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L324). You may want to filter by resource (like pods or something) and verb for testing (otherwise this will be quite annoying). Manually hit that endpoint and look at the metric output. 

/assign @logicalhan

**Comment by lavalamp** [comment]
Thanks for filing. Can we, while fixing this, add a metric counting timed-out requests? You can't tell from the latency distribution, even if we made the buckets more useful.

**Comment by logicalhan** [comment]
> Thanks for filing. Can we, while fixing this, add a metric counting timed-out requests? You can't tell from the latency distribution, even if we made the buckets more useful.

Yeah, that's the current plan. I've relayed the idea to @sttts offline and he has concurred.
