### ISSUE TITLE
Manually defined cmd/args are not reset for the container after original deployment is re-applied

### ISSUE THREAD

**Issue by MikkCZ** [kubernetes/kubernetes#83438]
**How to reproduce it (as minimally and precisely as possible)**:
1. Apply a K8S deployment without specific `cmd` and `args` in the deployment manifest defined for a container (only entrypoint in Dockerfile). (`kubectl apply -f foo-bar-deployment.yaml`)
1. Edit the deployment manually and add `cmd` and `args` to run a custom command in the container, e.g. for debugging. (`kubectl edit deployment foo-bar`)
1. Re-apply the original manifest with no `cmd` and `args` specified. (`kubectl apply -f foo-bar-deployment.yaml`)

**What happened**:
`kubectl get deployment foo-bar -o yaml` still shows `cmd` and `args` even after the manifest without them has been applied. It could be applied even several times.

**What you expected to happen**:
After a manifest with `cmd` and `args` for a container is applied, the previous `cmd` and `args` should disappear.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10"`
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
This is working as designed. Apply is intended to leave alone fields set by other actors/processes, and only unset/modify fields present in the applied manifest (or in the previously applied manifest). If you want to clear cmd/args, you can set them to null explicitly in the manifest you apply

/close
