### ISSUE TITLE
Assign specific cpu number to a pod in kubernetes

### ISSUE THREAD

**Issue by chiraggupta06** [kubernetes/kubernetes#83439]
**What happened**:
does Kubernetes provide some mechanism to assign a specific number of CPU to a pod?

**What you expected to happen**:
Currently, I am not able to assign a specific CPU cores to a pod.
**How to reproduce it (as minimally and precisely as possible)**:
---
apiVersion: v1
kind: Pod
metadata:
  name: new15
spec:
  containers:
  - name: new15
    image: rastasheep/ubuntu-sshd
    resources:
      limits:
        memory: "10Mi"
        cpu: "1"
      requests:
        memory: "10Mi"
        cpu: "1"
root@new15:/# cat /proc/self/status |grep Cpus
Cpus_allowed:   0000,00000001
Cpus_allowed_list:      0

it is assigning 1 cpu(random) from the list of available cpu core(0,1,2,3) but how can i assign a specific cpu(like number 3 out of 0,1,2,3)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13/1.15
- Cloud provider or hardware configuration:
ubuntu
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Please let me know in case of any other information is required.

Thanks in advance.
Regards,
Chirag Gupta

**Comment by zjj2wry** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/
