### ISSUE TITLE
rollout restart of deployments doesn't clear up old replica-sets

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#83448]
**What happened**:

When doing a `kubectl rollout restart` of a deployment the old replica set seems to hang around.

**What you expected to happen**:

Replicaset should be cleared up once the deployment rollout is complete

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl -n kube-system rollout restart deployment/calico-kube-controllers
deployment.apps/calico-kube-controllers restarted
$ kubectl -n kube-system rollout restart deployment/coredns
deployment.apps/coredns restarted
$ kubectl -n kube-system get rs
NAME                                 DESIRED   CURRENT   READY   AGE
calico-kube-controllers-564b6667d7   0         0         0       81m
calico-kube-controllers-59c748b9cc   1         1         1       50s
calico-kube-controllers-6494588974   0         0         0       5m36s
coredns-5644d7b6d9                   0         0         0       81m
coredns-5f5b5c6689                   2         2         2       38s
coredns-655f49c95f                   0         0         0       17m
coredns-6988bf6d4                    0         0         0       80m
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T05:14:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.3 LTD
- Kernel (e.g. `uname -a`):
Linux bionic-vm 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:58:27Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Network plugin and version (if this is a network-related bug):
Calico 3.8
- Others:

**Comment by NeilW** [comment]
@kubernetes/sig-cli-bugs 

because we have to start somewhere...

**Comment by kargakis** [comment]
This is unrelated to the CLI and depends on the revisionHistoryLimit set in the Deployment.
