### ISSUE TITLE
kubeadm init ... upgrade results in 1.13 kubelet speaking to 1.12 API server

### ISSUE THREAD

**Issue by DandyDeveloper** [kubernetes/kubernetes#83440]
**What happened**:
I have upgraded a node from 1.12 -> 1.13 and I am attempting to enable networking by running kube-router (Working in other nodes on 1.12). 

On upgrading using the `kubeadm init phase ...` commands,  everything appears running, but no pods are scheduled. I see the following exception in the kubelet logs: 

```
Oct 03 07:53:58 d153 kubelet[1423]: I1003 07:53:58.212021    1423 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/f47f9429-e5b2-11e9-8c31-ac1f6b6d904e-lib-modules") pod "kube-router-vvbgd" (UID: "f47f9429-e5b2-11e9-8c31-ac1f6b6d904e")
Oct 03 07:53:58 d153 kubelet[1423]: I1003 07:53:58.212049    1423 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-router-cfg" (UniqueName: "kubernetes.io/configmap/f47f9429-e5b2-11e9-8c31-ac1f6b6d904e-kube-router-cfg") pod "kube-router-vvbgd" (UID: "f47f9429-e5b2-11e9-8c31-ac1f6b6d904e")
Oct 03 07:53:58 d153 kubelet[1423]: I1003 07:53:58.212064    1423 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-t7xp9" (UniqueName: "kubernetes.io/secret/f47f9429-e5b2-11e9-8c31-ac1f6b6d904e-default-token-t7xp9") pod "kube-router-vvbgd" (UID: "f47f9429-e5b2-11e9-8c31-ac1f6b6d904e")
Oct 03 07:53:58 d153 kubelet[1423]: I1003 07:53:58.212083    1423 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/f47f9429-e5b2-11e9-8c31-ac1f6b6d904e-kubeconfig") pod "kube-router-vvbgd" (UID: "f47f9429-e5b2-11e9-8c31-ac1f6b6d904e")
Oct 03 07:53:58 d153 kubelet[1423]: I1003 07:53:58.212121    1423 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "cni-conf-dir" (UniqueName: "kubernetes.io/host-path/f47f9429-e5b2-11e9-8c31-ac1f6b6d904e-cni-conf-dir") pod "kube-router-vvbgd" (UID: "f47f9429-e5b2-11e9-8c31-ac1f6b6d904e")
Oct 03 07:53:59 d153 kubelet[1423]: E1003 07:53:59.478649    1423 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
Oct 03 07:53:59 d153 kubelet[1423]: /usr/local/go/src/runtime/asm_amd64.s:522
Oct 03 07:53:59 d153 kubelet[1423]: /usr/local/go/src/runtime/panic.go:513
Oct 03 07:53:59 d153 kubelet[1423]: /usr/local/go/src/runtime/panic.go:82
Oct 03 07:53:59 d153 kubelet[1423]: /usr/local/go/src/runtime/signal_unix.go:390
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:546
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:449
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:192
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:115
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:721
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1691
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:824
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:174
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:183
Oct 03 07:53:59 d153 kubelet[1423]: /workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:221
Oct 03 07:53:59 d153 kubelet[1423]: /usr/local/go/src/runtime/asm_amd64.s:1333
```

**What you expected to happen**:
Kube-router to start successfully and networking to be enabled for this node. 

**How to reproduce it (as minimally and precisely as possible)**:
In my case, I simply ran the phased `kubeadm init phase` commands against a ClusterConfiguration yaml file. 

After upgrading, deploy any pods (kube-router runs specifically as a DaemonSet), but I see no other pods are actually running successfully beyond the system services enabled by kubeadm. 

**Anything else we need to know?**:
I have tried running this in every 13.X version available, and all of them experience the same problem on the upgrade.

We are a bare metal implementation, no cloud providers used. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare Metal. 
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2191.5.0
VERSION_ID=2191.5.0
BUILD_ID=2019-09-04-0357
PRETTY_NAME="Container Linux by CoreOS 2191.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
`Linux d153 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz GenuineIntel GNU/Linux`
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
kube-router v3.2.0

**Comment by deads2k** [comment]
apimachinery provides the function dumping the stack, it's not actually in the stack here.  Looks like you crashed in kubelet_pods.

**Comment by liggitt** [comment]
this is a duplicate of #71749, and means you are running a 1.13 kubelet against a 1.12 API server. ensure the API server is at least as new as the kubelets running against it, per https://kubernetes.io/docs/setup/release/version-skew-policy/#kubelet

I'm not sure if the kubeadm upgrade properly orders the kubelet and apiserver upgrades. xref https://github.com/kubernetes/kubeadm/issues/1311 https://github.com/kubernetes/kubernetes/issues/72871#issuecomment-454022469

**Comment by liggitt** [comment]
/assign @neolit123 

was https://github.com/kubernetes/kubeadm/issues/1311 resolved by making kubeadm do something differently, or by changing documentation to indicate the correct order of operations? if the current documentation is followed, are the requirements of https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-component-upgrade-order met?

**Comment by DandyDeveloper** [comment]
@liggitt I just took a look to make sure, but it looks like all my components are on the same version:

```
aaron@aaron-XPS-15-9570:$ klogs -n kube-system kube-apiserver-d153
I1003 07:46:57.468088       1 server.go:557] external host was not specified, using 208.81.97.137
I1003 07:46:57.468211       1 server.go:146] Version: v1.13.11
aaron@aaron-XPS-15-9570:$ klogs -n kube-system kube-controller-manager-d153
I1003 07:47:01.146230       1 serving.go:318] Generated self-signed cert in-memory
I1003 07:47:01.741894       1 controllermanager.go:151] Version: v1.13.11
aaron@aaron-XPS-15-9570:$ klogs -n kube-system kube-scheduler-d153
I1003 07:47:02.301515       1 serving.go:318] Generated self-signed cert in-memory
I1003 07:47:02.620257       1 server.go:150] Version: v1.13.11
```

Kubelet:
```
blah@dddd ~ $ kubelet --version
Kubernetes v1.13.11
```

**Comment by tedyu** [comment]
It seems Kubelet#GenerateRunContainerOptions was involved in the panic.
```
        opts, err := kl.containerManager.GetResources(pod, container)
```
```
        volumes := kl.volumeManager.GetMountedVolumesForPod(podName)
```
It was from either of the above two places.

**Comment by neolit123** [comment]
@liggitt 

> was kubernetes/kubeadm#1311 resolved by making kubeadm do something differently, or by changing documentation to indicate the correct order of operations

we just changed the docs, but maybe the old website branches did not include the change.

> if the current documentation is followed, are the requirements of https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-component-upgrade-order met?

newer documentation should instruct users to upgrade the api servers first, kubelets last.

@DandyDeveloper 

> I just took a look to make sure, but it looks like all my components are on the same version:

can you reproduce the error consistently?
what are the upgrade steps that you followed and from which document?

**Comment by DandyDeveloper** [comment]
@neolit123 I changed around my upgrade phasing and also tried on a different note and can't recreate the problem. 

Now I just can't get networking to work on the actually pods. New problems!

**Comment by neolit123** [comment]
> I changed around my upgrade init phase steps and also tried on a different note and can't recreate the problem.

ok, given this issue was related to upgrades. let's close it.
if you find a bug please feel free to report it in another issue.
thanks.

/close
