### ISSUE TITLE
Scheduler cache.GetNodeInfo should return IsNotFound error if applicable

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#83458]
**What happened**:
This [PR](https://github.com/kubernetes/kubernetes/commit/30b0f8bf3bed2c1c146a85ecdfc6b9cb18c5a303) switches NodeLister to scheduler cache for `GetNodeInfo`.  However, the new `GetNodeInfo` implementation in the cache never returns IsNotFound error any more. Rather, it returns a normal error:
https://github.com/kubernetes/kubernetes/blob/67d750bb2893d7a66d45d435dfc075fb17cc15ee/pkg/scheduler/internal/cache/cache.go#L696-L706

However, we rely on the error type for logging, for example:
https://github.com/kubernetes/kubernetes/blob/7cb4850699a4a3c1008382c8b05f245b66ce19ad/pkg/scheduler/algorithm/predicates/predicates.go#L1386-L1394
**What you expected to happen**:
The cache `GetNodeInfo()` should return IsNotFound error if applicable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/sig scheduling
@draveness  cc @ahg-g

**Comment by evanmcclure** [comment]
Hi. I'd like to work on this for #Hacktoberfest.

**Comment by mcaci** [comment]
Hello, I would love to contribute too in case. I'm already looking at the code in fact :D

**Comment by ahg-g** [comment]
Thanks all for the interest, will assign to @evanmcclure since he expressed interest first.

/assign @evanmcclure

**Comment by evanmcclure** [comment]
I was browsing around the rest of the implementation of the cache and noticed that none of the other accessors return `IsNotFound`. Also, I couldn't determine if `GetNodeInfo` returned anything other than an `error`. I'm new here, so I may be doing it wrong.

@liu-cong Are you sure the behavior changed, and are you sure returning `IsNotFound` is expected? Should we change the other accessors, too?

**Comment by liu-cong** [comment]
Let's look at previous release.

The `NodeInfo` object is initialized in [`getPluginArgs()`]

https://github.com/kubernetes/kubernetes/blob/9a83f46a506124685802559c4a3981f4f415d1de/pkg/scheduler/factory/factory.go#L567
 where it creates a `CachedNodeInfo`.  Now let's take a look at  `CachedNodeInfo` implementation:
https://github.com/kubernetes/kubernetes/blob/9a83f46a506124685802559c4a3981f4f415d1de/pkg/scheduler/algorithm/predicates/predicates.go#L203-L215

There you can see that it calls NodeLister Get() method, which can return a IsNotFound error.
https://github.com/kubernetes/client-go/blob/a746c2f219b70f14fbaaa89aede1c0c63ccbc005/listers/core/v1/node.go#L56-L65

**Comment by hv7214** [comment]
Hello, is this issue being solved ? If not, i am interested in solving this issue.

**Comment by evanmcclure** [comment]
Thanks @hv7214, but I am working on this currently.

**Comment by phiremande** [comment]
@evanmcclure , if you haven't started your work yet, let me know if I can raise a PR for this issue. I have the change ready.

**Comment by evanmcclure** [comment]
I started, but haven’t been able to finish creating the PR. Go ahead and submit yours. Thanks.
