### ISSUE TITLE
Enable configuration of C: drive size for pods

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes/kubernetes#83450]
**What would you like to be added**: Support configuration of the size of the C: drive in Windows containers running on Kubernetes. 

One option is to enable [storage-opt](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#image-size).

**Why is this needed**: Many Windows software packages are coded (sometimes as bugs) to examine the free space in the C: drive even when the space they need is somewhere else. This causes some software to fail to operate correctly with the default 20 GB C: drive.

**Comment by wawa0210** [comment]
@craiglpeters  @PatrickLang  
Hey, is anyone now following up or developing this feature? If not, I think I can contribute my strength.

**Comment by PatrickLang** [comment]
I don't think anyone has investigated this yet. A few things to check:

Setting it system-wide:

- Currently storage-opt is broken in some combinations of Docker+Windows - see https://github.com/docker/engine/pull/429 and https://github.com/microsoft/hcsshim/issues/708
- Once that's fixed, I think you could write a daemonset that would change this docker config system wide, but I don't know if that requires restarting Docker or not

Setting it per container:

This needs to have APIs available in:

- OCI runtime-spec https://github.com/opencontainers/runtime-spec
- HCSShim https://github.com/microsoft/hcsshim
- Moby (for now), then vendored into Docker EE
- ContainerD (for sometime in 2020)
- CRI

If you want to take a look and try it out, go ahead and share what you find here.

**Comment by wawa0210** [comment]
@PatrickLang  Very comprehensive  

As far as i know 
Setting it system-wide:
 + After my testing, this parameter `storage-opt` is no problem in docker-ee, there is a problem in docker-ce, it seems to have been fixed
+ If we run daemonset to change the docker daemon.json, this requires restarting docker to work, which is very risky

Therefore, I thought we could specify this parameter by configuring yaml when running each pod, and then dynamically expand the size of the C drive

To achieve this, we need to change CRI and add this property. Currently this parameter is normal in docker-ee, and soon docker-ce should be able to fix this error and release a new version
