### ISSUE TITLE
Fine grained Kubelet API authorization

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#83465]
**Summary**
The node API authorization is too coarse. We need finer grained authorization of different request types, and maybe resources acted on.

**Background**

The Kubelet API on the authenticated (10250) port currently uses a very coarse-grained scheme for authorizing requests. For example, reading `/healthz` and calling `/exec/...` (i.e. execute arbitrary code) require the same `proxy` subresource. The SubjectAccessReviews are currently populated with:

- Requisting user (generally from a TokenReviewRequest or client certificate authentication)
- Request verb
- A resource request with:
    - `APIGroup: ""`
    - `APIVersion: "v1"`
    -  `Resource: "nodes"`
    - `Name: nodeName` (the name of the node the request was against)
    - `Subresource:` one of: proxy, log, metrics, spec, stats

The full mapping of request paths to subresources can be found here: https://github.com/kubernetes/kubernetes/blob/14344b57e56258e87cbe80c8cd80399855eca424/pkg/kubelet/server/auth_test.go#L110-L143

Fixing this issue is a prerequisite to removing the Kubelet's unauthenticated API: https://github.com/kubernetes/kubernetes/issues/12968

Although this issue is specific to the Kubelet API, other components that use delegated authorization for a subdivided API will face the same problems.

**Desired State**

In an ideal world, authorization would happen against the following criteria:

1. Requester has permission to use the node API for this Kubelet.
2. If it's a resource request with a Kubernetes API analog, the requester is authorized to make the request through the regular API
    - E.g. `/exec/podNamespace/podID/containerName` maps to:
      ```
      apiGroup: "core"
      apiVersion: "v1"
      resource: "pods"
      namespace: podNamespace
      name: podName
      subresource: "exec"
      ```
    - E.g. `/pods/` maps to:
      ```
      apiGroup: "core"
      apiVersion: "v1"
      resource: "pods"
      verb: "list"
      ```
3. If it's a non-resource request (e.g. `/healthz`, `/logs`), then it's a regular non-resource request authorization check (still requiring [1]), with the requested path being the requested path.
   - _optional:_ We could prefix the request path to indicate a request via the kubelet API, so the authorization can't be used against other non-kubelet targets.

These changes need to maintain backwards compatibility with the current coarse grained permissions.

/sig auth
/sig node
/kind feature
/area kubelet-api
/priority important-longterm

See also:
- https://github.com/kubernetes/kubernetes/issues/12968
- https://github.com/kubernetes/kubernetes/issues/28138
- https://github.com/kubernetes/kubernetes/issues/2098

**Comment by tallclair** [comment]
Brainstorming a few different approaches:

**1. Issue a SAR for `nodes/${node_name}/api` AND a SAR for the specific request**
- First SAR covers the first check (kubelet API access), second covers the other cases
- No way to authorize only access via the kubelet API (do we care?)
- Probably requires the prefix for [3]

**2. Introduce an analogue to the TokenRequest audience for authorization**
- "audience" (target?) would be the request target node (`system:nodes:<node_name>`)
- need to extend authorizers (RBAC) with target notion
- a broad change for a pretty specialized usecase

**3. Add per-request subresources**
- Simplest change
- Doesn't quite meet desired criteria, since there's no way to grant permission on specific resources (pods; at least without a hacky subresource encoding scheme)

**4. Overload impersonation**
- A few different ways this could work, but they're all horrible. Let's not do this...
- Ends up being semantically equivalent to [1], but the second authorization check is made on the apiserver side

I'm leaning towards [3]. The first [1] looks pretty tempting, but I'm worried about the scalability of issuing a second request, especially if we move all traffic off the read-only port.

To address backwards compatibility, I think there are 2 approaches:
1. Use a fallback - first check against the new authorization scheme, and if the request is denied check against the old scheme.
  - Could introduce an optional header to skip the fallback
2. Use new endpoints - I.e. "kubelet API v2"
  - Tempting, and it also offers an opportunity to clean up the API (make it look more like the cluster API)
  - Greatly increases the scope of the change, as it will inevitably become much more focused on designing a Kubelet v2 API.

**Comment by tallclair** [comment]
Going to mark this as
/help-wanted
since I don't have time to tackle it now.

If you're interested in working on this, it will definitely need a KEP to start, and you should engage both the sig-auth and sig-node communities.

**Comment by tedyu** [comment]
I think option #2 anove:

Use new endpoints - I.e. "kubelet API v2"

is better.
With option 1, it is hard to maintain new authorization scheme.

**Comment by serathius** [comment]
Hey Tim I would be interested in looking into this.

**Comment by pacoxu** [comment]
/remove-lifecycle stale
/assign
I will take this up as I am working on #12968 and #101139. (Hope it can be started in this release cycle and KEP discussion in 1.23?)

It needs a KEP for `kubelet API v2`. 
- `/pods` API  for monitoring systems
- `/healthz` not just on loopback

**Comment by tallclair** [comment]
Thanks @pacoxu !

I was thinking about this recently, and have a couple thoughts:

1. I think we might be able to implement this without a v2 API (although I think we should have a v2 API) by issuing serial SubjectAccessReviews (SARs): I.e. first send a SAR for the new permission. If the response is not authorized, then send another SAR with the original permission. Since these APIs are mostly only consumed by system components, those components can be migrated to the new permissions to avoid introducing the additional latency & load of the second request. We could optionally work towards deprecating the original permission.
2. For an interim solution, we could consider adding support for an authenticating proxy (e.g. envoy) to the Kubelet. We may want to consider this regardless, but it's sort of orthogonal.

**Comment by fromanirh** [comment]
/triage accepted
per https://github.com/kubernetes/kubernetes/issues/83465#issuecomment-866491811

**Comment by serathius** [comment]
@pacoxu Please consider including https://github.com/kubernetes/kubernetes/issues/99918 in `Kubelet v2 API` design

**Comment by tallclair** [comment]
This is still a relevant issue, especially with the removal of the read-only port. IMO a viable end state would also be to deprecate a bunch of the kubelet apis. Either way, we should figure out some strategy for handling this.

/triage accepted

**Comment by tallclair** [comment]
I think we can close this. It's tracked by the enhancements issue instead: https://github.com/kubernetes/enhancements/issues/2862#issuecomment-2254346191

/close

/cc @vinayakankugoyal
