### ISSUE TITLE
Change scheduler pod_preemption_victims from Gauge to Histogram

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#83464]
**What would you like to be added**:
Change scheduler `pod_preemption_victims` metric  from Gauge to Histogram

**Why is this needed**:
`pod_preemption_victims` is recorded for each preemption attempt. A histogram is better.

/sig scheduling
/help
/good-first-issue

**Comment by Tabrizian** [comment]
I can work on this issue.

**Comment by aladhims** [comment]
I could work on this as well if @Tabrizian doesn't have time to work on this.

**Comment by Tabrizian** [comment]
@aladhims  I am working on it, I will create the initial PR in less than a week. Sorry for the delay.
