### ISSUE TITLE
TopologyManager: Guarantee Aligned resources for Multiple Containers

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#83476]
The `TopologyManager` is currently only guaranteed to work if a _single_ container in the pod spec requires aligned resources.

The reason for this is the following:

* The admit handler for the `TopologyManager` loops through all containers, calling out to the `CPUManager` and `devicemanager` to generate hints for each of them individually, rather than on the entire pod as a whole.

* Generating hints relies on looking at the current resource request and considering the current allocation state to figure out what the appropriate set of hints to send back should be.

* However, the admit handler in the `TopologyManager` is called strictly before the `CPUManager` and `devicemanager` have the opportunity to do any device allocation.

* This results in unreliable hint generation for all but the first container, since subsequent containers have no idea what the allocation state will be once that first container is allocated some resources.

This can be solved in one of two ways:

1. Change the pod admit handler for the `TopologyManager` to loop through each container, first calling out to the `CPUManager` and `devicemanager` to generate hints and then immediately calling out to perform device allocation in the same iteration of the loop.

1. Change the `TopologyManager` to do hint generation at the pod level rather than the container level. It is unclear if this is desirable, however, since each container should be able to have its resources aligned separately, and not forced to a single alignment for all resources across the entire pod.

Option (1) seems like the better option, but it will require significant updates to both the `CPUManager` and the `devicemanager`. The `CPUManager` will need to be updated to support CPU allocation at pod admit time (currently it is done at container start time). The `devicemanager` will need to be updated to allocate devices on a container-by-container basis. Currently, it loops through the resource list for all containers at once and allocates devices to them accordingly.

As we iterate on a solution to this, we should update the existing KEPs for the [CPUManager](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/cpu-manager.md) and [TopologyManager](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0035-20190130-topology-manager.md) with the proposed changes.

Tracking PRs:
~~https://github.com/kubernetes/kubernetes/pull/84196 Refactor parts of CPUManager~~
~~https://github.com/kubernetes/kubernetes/pull/84462 Update CPUManager state information~~
~~https://github.com/kubernetes/kubernetes/pull/84300 Update logic in `CPUManager` `reconcileState()`~~
TBD Refactor devicemanager Allocate / UpdatePluginResources logic
TBD Move CPU allocation to pod admit time instead of container start time
TBD Update the `devicemanager` to allocate devices on a container-by-container basis
TBD Move TopologyHint generation and final resource allocation into the same synchronous loop

**Comment by cbf123** [comment]
Just a note that we should make sure the solution to this also solves issue https://github.com/kubernetes/kubernetes/issues/84749

**Comment by cbf123** [comment]
Ideally the solution here should account for the fact that the init containers are run sequentially (and thus can re-use the same resources), while the app containers can run in parallel (but can re-use resources from the init containers).  (See https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources for details.)

So I think we should first determine the *effective* init request/limit in order to generate a hint that would apply to all init containers, then do device allocation for the init containers.  Then basically "return" those resources back into the "available" list and generate hints and device allocation for each app container.

**Comment by klueska** [comment]
Yes. This is part of the plan. Once we are able to do the allocation for all containers up-front at pod-admit time, we will share CPUs accordingly across init-containers and into app-containes. This is exactly what the device manager does as well, for refererence.

**Comment by abel-von** [comment]
We are using k8s to run kata container, the resource topology should be aligned in pod level, so I think change hint generation to pod level is a better choice. I don't think alignning resource separately is any necessary.

**Comment by bg-chun** [comment]
@abel-von 
Here is related discussion for the topic what you mentioned.
https://docs.google.com/document/d/1YTUvezTLGmVtEF3KyLOX3FzfSDw9w0zB-s2Tj6PNzLA/edit?disco=AAAADdeMnZA
