### ISSUE TITLE
Duplicate Custom Predicates/Priorities

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83472]
Currently custom predicate and priorities can be created through the [Policy API](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/api/v1/types.go#L51-L71). 

The problem is that a custom predicate/priority, like ServiceAffinity, can be [listed](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/api/v1/types.go#L32-L35) multiple times in the Policy with different names, possibly with different arguments. 

This semantic (i.e., specifying multiple instances of the same custom predicate with different arguments) is only useful if different ```Weight```s were specified because in all cases of custom predicates/priorities the arguments are merge-able (for example, ```Labels``` from multiple CheckServiceAffinity custom predicates can be merged into one set).

In the world of framework plugins, we don't currently have a way to maintain those semantics. [```PluginConfig```](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/types.go#L98), which specifies plugins' arguments is separate from list that specifies which [```Plugins```](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/types.go#L91) to run.

The question here: do we really want to maintain the old semantics of custom predicates and priorities? in other words, do we need to change the ComponentConfig API to somehow allow specifying multiple instances of the same Plugin with different arguments/weights, or should we consider that this is not supported?

I always lean towards simplifying things, so my suggestion is to not support that, but I would like to know if there are actual deployments that rely on this.

/sig scheduling

/cc @bsalamat @misterikkit @Huang-Wei @k82cn @ravisantoshgudimetla

**Comment by ahg-g** [comment]
We discussed this in the sig meeting, and put the issue for discussion on the scheduler and kubernetes-dev mailing list, I believe this behavior is not intentional, and so we should add logic to fail the scheduler configuration when a policy includes more than one custom predicate/priority of the same type.

/assign @ravisantoshgudimetla

**Comment by ahg-g** [comment]
any progress on this one?

**Comment by damemi** [comment]
I haven't made any progress on this yet, but it's on my priority now

**Comment by liu-cong** [comment]
In migrating custom predicates to filter plugins #84187, I am gonna ignore the custom predicate name and use the default name.
