### ISSUE TITLE
Topology Manager for 1.17 Tracking Issue

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#83479]
This issue is used to track the enhancements we plan to make to the `TopologyManager` in the 1.17 timeframe.

The tracking issue for the full `TopologyManager` feature can be found here:
kubernetes/enhancements#693

The following PRs track each of the 1.17 enhancements individually:

Bug Fixes:
~~https://github.com/kubernetes/kubernetes/pull/84525~~ Fix bug in TopologyManager hint generation after kubelet restart
~~https://github.com/kubernetes/kubernetes/pull/83777~~ Fixed bug in TopologyManager with SingleNUMANode Policy
~~https://github.com/kubernetes/kubernetes/pull/82104~~ Fix bug in CPUManager with setting topology for policies
~~https://github.com/kubernetes/kubernetes/pull/83196~~ using online file instead to fix NUMA nodes init

Features:
~~https://github.com/kubernetes/kubernetes/pull/83043~~ Delegate topology hint gen to CPU manager policy
~~https://github.com/kubernetes/kubernetes/pull/83033~~ Rename package socketmask to bitmask.
~~https://github.com/kubernetes/kubernetes/pull/83492~~ Topology manager aligns pods of all QoS classes.
~~https://github.com/kubernetes/kubernetes/pull/84721~~ Base Infrastructure for adding Merge() API to TopologyManager Policies

Documentation:
~~https://github.com/kubernetes/website/pull/17451~~ Topology management doc updates

**Comment by josiahbjorgaard** [comment]
Bug triage for release 1.17 here. Since this issue has been tagged for the milestone, we would like to check it's status. Code freeze is on Nov. 19. Will this issue be resolved before then? If not, we should move it out of the milestone.

**Comment by josiahbjorgaard** [comment]
Hi bug triage team for 1.17, will this issue be resolved before code freeze on Nov. 14 (next Thursday)?

**Comment by klueska** [comment]
@josiahbjorgaard We are still pushing for it, but it's definitely at risk of not making it

/cc @ConnorDoyle 
/cc @derekwaynecarr 
/cc @lmdaly

**Comment by klueska** [comment]
I have updated the description for this issue to only include the PRs we actually plan on getting into 1.17 at this point. The only remaining PR is the documentation one from @lmdaly. All others have been merged already.

Unfinished work has been pushed out to a tracking issue for 1.18:
https://github.com/kubernetes/kubernetes/issues/85093

**Comment by josiahbjorgaard** [comment]
@klueska Will you please make sure to close the issue once all v1.17 is complete?

**Comment by josiahbjorgaard** [comment]
/milestone clear

(v1.17 code freeze)

**Comment by lmdaly** [comment]
https://github.com/kubernetes/website/pull/17451 is now merged

**Comment by klueska** [comment]
All PRs tracked by this issue have now been merged. Closing
