### ISSUE TITLE
interaction between secret, optional, and PodPreset 

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubernetes#83488]
Details refer to [this](https://github.com/kubernetes/website/pull/16657#issue-323553510).

I am not sure this is only doc issue, as @sftim said.

My env is v1.15.3

**Comment by sftim** [comment]
Hi @daixiang0 
I'm not sure I understand. Are you describing a bug?
/priority awaiting-more-evidence
/triage needs-information

**Comment by daixiang0** [comment]
@sftim it is a question indeed.

**Comment by liggitt** [comment]
PodPresets only modify the creation of the pod manifest. The only errors they can detect are conflicts between what is specified in the PodPreset manifest and what is in the Pod manifest (things like duplicate volume names, etc).

Once a pod is created, the actual behavior at run time (for cases like missing secrets, volume mounts with errors, etc) is the same regardless of whether a pod preset was involved in the creation of the pod manifest or not. For secret volumes, a missing secret prevents the pod from starting unless the secret is explicitly marked as optional. This is true for normal pods and for pods created with the help of a PodPreset.

/close

**Comment by daixiang0** [comment]
@liggitt I got the key, i misunderstand that the `on error` means any error when create pod, in the other hand, it should be better to change ` Attempt to merge the various resources defined by the `PodPreset` into the Pod being created` to ` Attempt to merge the various resources defined by the `PodPreset` into the Pod before it create`, as you said, all check that podpreset does is before creating pod.

**Comment by daixiang0** [comment]
@liggitt any input?
