### ISSUE TITLE
TopologyManager: Add support for device-specific topology constraints

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#83483]
The current `TopologyManager` only allows devices to be aligned by NUMA node. However, certain devices have internal constraints which dictate how they should be aligned when multiple devices of the same type are requested.

This issue tracks the effort to add support for such "inter-device" topology constraints when allocating devices to a container. The proposed solution allows each device plugin to specify preferred device allocations based on internal topology constraints, while still leaving the final allocation decision up to the `devicemanager`. 

KEP Update:https://github.com/kubernetes/enhancements/pull/1121
Implementation PR: TBD

**Comment by YuxiJin-tobeyjin** [comment]
Following, any news?

**Comment by klueska** [comment]
The proposal linked in the description was accepted and merged earlier this month: https://github.com/kubernetes/enhancements/pull/1121

The plan is to get the code merged by the code freeze on July 9th to make it into 1.19. if that doesn’t happen, it will be added for 1.20.
