### ISSUE TITLE
TopologyManager: Write improved documentation

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#83482]
The current documentation for the `TopologyManager` feature is quite lacking.

At a minimum we should provide guides for:
* How to create a HintProvider
* How to extend a device plugin

This Issue will be updated as appropriate to track this documentation effort over time.

**Comment by lmdaly** [comment]
Documentation PR: https://github.com/kubernetes/website/pull/17451

**Comment by alena1108** [comment]
Having the document on how to create a HintProvider, would definitely be useful. As it's the biggest pluggable part of the framework, and people would want to define their own eventually.
