### ISSUE TITLE
Function to limit the number of deployments created with RBAC

### ISSUE THREAD

**Issue by takezyou** [kubernetes/kubernetes#83496]
**What would you like to be added**:
Function to limit the number of deployments created with RBAC.

**Why is this needed**:
I wanted to limit the number of deployments per user.
By doing so, I think that it will be possible to regulate more detailed resources for individual users.

**Comment by liggitt** [comment]
Thanks for the request, but there are no plans for per-user resource quota at the moment. per-namespace quotas can be applied (see https://kubernetes.io/docs/concepts/policy/resource-quotas/), and users limited to specific namespaces using RBAC.

A per-user quota mechanism could also be built as an extension using [admission webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).

/close
