### ISSUE TITLE
Better handling of some in-tree plugins mount setup failures

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#83515]
In some in-tree plugins (including gce-pd, awsebs), during mount set up, if mount fails, it requires to do some clean up work to unmount and remove dir etc. However, in current code, there are a number of places to use IsLikelyNotMountPoint to check the mounting status and take actions based on the result. I think this check is not necessary and not very reliable. It would be better to simplify this mount failure handling logic to just run cleanupMountpoint function and remove dir.

**Comment by tedyu** [comment]
In pkg/util/mount/mount_helper_common.go :
```
                if extensiveMountPointCheck {
                        notMnt, err = IsNotMountPoint(mounter, mountPath)
                } else {
                        notMnt, err = mounter.IsLikelyNotMountPoint(mountPath)
```
Can IsNotMountPoint be used in place of IsLikelyNotMountPoint() ?
