### ISSUE TITLE
podConditionUpdater and podPreemptor consist of a clientset only

### ISSUE THREAD

**Issue by ahmad-diaa** [kubernetes/kubernetes#83514]
After Moving podConditionUpdater and podPreemptor types to the scheduler, both of them only consists of `clientSet` which is already a part of the `scheduler` struct. https://github.com/kubernetes/kubernetes/pull/83342#discussion_r330850183 suggested that we remove them and have their methods as private methods of the scheduler.

They might as well be kept as they provide more context for the associated methods (i.e `setNominatedNodeName` during preemption, might be easier to understand the method usage when it's bound to `podPreemptor` type).

This issue is to further discuss whether or not we will remove those types.

cc @alculquicondor @ahg-g 

/kind cleanup
/sig scheduling

**Comment by ahg-g** [comment]
I don't think it is necessary to "create interfaces" to clarify "context". It bloats the file with unnecessary types, the function docs should clarify the context if the function name can't be made clear enough.

**Comment by ahmad-diaa** [comment]
SG
/assign
