### ISSUE TITLE
[Scheduler] Add more method to the framework handle

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#83523]
/sig scheduling
/assign
/kind feature

Per discussion in https://github.com/kubernetes/kubernetes/pull/82432#issuecomment-537043208, and the scheduling framework [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#frameworkhandle)

> While the PluginContext provides APIs relevant to a single scheduling context, the FrameworkHandle provides APIs relevant to the lifetime of a plugin. This is how plugins can get a client (kubernetes.Interface) and SharedInformerFactory, or read data from the scheduler's cache of cluster state. The handle will also provide APIs to list and approve or reject waiting pods.

We decided to add the following methods to the framework handle:

https://github.com/kubernetes/kubernetes/blob/99cf24c2c65ca6349b102716e39eae407d3ea9a9/pkg/scheduler/framework/v1alpha1/interface.go#L411-L428

- [x] ClientSet: this is for push updates, e.g., plugins could update resources with clientset https://github.com/kubernetes/kubernetes/pull/82432
- [x] SharedInformersFactory: for plugins to access listers for resources not cached in the scheduler cache (like Services, ReplicaSets etc.) #83663
- [ ] SharedSchedulerListers: a new interface that encapsulates listers for objects cached in the scheduler. #83523

**Comment by alejandrox1** [comment]
@draveness could you provide more details on this issue?
What do you mean by adding more methods to the framework handle? Why is this necessary? Could you please elaborate on the three bullet points you listed?

Is there a KEP for this? 
/cc @Huang-Wei @ahg-g @hex108 

/milestone v1.17

**Comment by draveness** [comment]
> could you provide more details on this issue?

Update the description

> Why is this necessary? Could you please elaborate on the three bullet points you listed?

The reason for adding the field is after the comma, e.g. "for plugins to access listers for resources not cached in the scheduler cache"

**Comment by ahg-g** [comment]
> @draveness could you provide more details on this issue?
> What do you mean by adding more methods to the framework handle? Why is this necessary? Could you please elaborate on the three bullet points you listed?
> 
> Is there a KEP for this?
> /cc @Huang-Wei @ahg-g @hex108
> 
> /milestone v1.17

No KEP is required for this issue, it is an implementation detail of the framework.

**Comment by ahg-g** [comment]
@draveness it would be great if you can prioritize finishing this issue, it will allow us to start the work on moving multiple predicates/priorities in parallel to the framework once #83537 is merged.

**Comment by ahg-g** [comment]
> @draveness it would be great if you can prioritize finishing this issue, it will allow us to start the work on moving multiple predicates/priorities in parallel to the framework once #83537 is merged.

nevermind, this is a priority for phase 2 of the migration plan :)

**Comment by ahg-g** [comment]
sorry for the back and forth, actually the SharedSchedulerListers type is something we need now. We need to pass it along with SharedInformerFactory to plugins.NewDefaultRegistry() so that we can instantiate predicates/priorities that need those listers. So this is issue is very high priority now.

**Comment by draveness** [comment]
> sorry for the back and forth, actually the SharedSchedulerListers type is something we need now. We need to pass it along with SharedInformerFactory to plugins.NewDefaultRegistry() so that we can instantiate predicates/priorities that need those listers. So creating the new SharedSchedulerListers is important now for phase 1.

I'll send a PR to add SharedSchedulerListers soon.

**Comment by draveness** [comment]
@ahg-g Do we still need a SharedSchedulerLister? if not, I'd like to close this issue.

**Comment by ahg-g** [comment]
We do need it, but in a different form. Luckily we managed to work around it for phase 1 of plugin migration. I think we can't close this one, thanks a lot for leading this effort.

/close
