### ISSUE TITLE
Cassandra sample should use Cassandra more

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#8355]
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/cassandra

There’s no ah-ha moment here - it’s just a tour of pods/labels/replication controllers.

I would have liked another couple of steps to actually use Cassandra to create a basic DB then kill the pod it was working on, then query the DB and see the service just serve it from a different pod.  I assume either that, or showing the LB properties of a service would be cool.

**Comment by jayunit100** [comment]
There is now a stress test in e2e which continuously resizes (up and dowa replication controller.) 

Certainly we could use this approach for a Cassandra e2e test - predefined a set of key values, shrink and expand the rc several times; and confirm at the end that those values still are readable and correct

**Comment by chrislovecnm** [comment]
@goltermann more information please

**Comment by goltermann** [comment]
I looked back over examples/storage/cassandra/README.md, which has changed since this issue was filed.  It's much clearer and more fleshed out than it was when I opened the issue, so I think we're good.
