### ISSUE TITLE
1.16: etcd client does not parse IPv6 addresses correctly when members are joining

### ISSUE THREAD

**Issue by hangxie** [kubernetes/kubernetes#83550]
**What happened**:
Running kubeadm 1.16.1 on CentOS7 with local etcd, the first kube master (`2001:db8:101:53e9::1:17`) is up and running, try to make the second master (`2001:db8:101:53e9::1:2d`) join the cluster and got error:
```
I1006 00:05:57.730235   30231 etcd.go:107] etcd endpoints read from pods: https://[2001:db8:101:53e9::1:17]:2379
I1006 00:05:57.750843   30231 etcd.go:156] etcd endpoints read from etcd: https://[2001:db8:101:53e9::1:17]:2379
I1006 00:05:57.750907   30231 etcd.go:125] update etcd endpoints: https://[2001:db8:101:53e9::1:17]:2379
failed to dial endpoint https://[2001:db8:101:53e9::1:17]:2379 with maintenance client: context deadline exceeded
etcd cluster is not healthy
k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd.CheckLocalEtcdClusterStatus
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd/local.go:87
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runCheckEtcdPhase
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/checketcd.go:68
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:236
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:424
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:209
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:169
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
error execution phase check-etcd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:237
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:424
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:209
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:169
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

log of etcd on the first kube master shows:
```
2019-10-06 18:31:14.493853 I | mvcc: finished scheduled compaction at 56939 (took 1.44269ms)
2019-10-06 18:33:03.880905 I | embed: rejected connection from "[2001:db8:101:53e9::1:2d]:60812" (error "remote error: tls: bad certificate", ServerName "[2001")
2019-10-06 18:33:04.891260 I | embed: rejected connection from "[2001:db8:101:53e9::1:2d]:60818" (error "remote error: tls: bad certificate", ServerName "[2001")
2019-10-06 18:33:06.416960 I | embed: rejected connection from "[2001:db8:101:53e9::1:2d]:60820" (error "remote error: tls: bad certificate", ServerName "[2001")
2019-10-06 18:33:08.748958 I | embed: rejected connection from "[2001:db8:101:53e9::1:2d]:60822" (error "remote error: tls: bad certificate", ServerName "[2001")
2019-10-06 18:33:13.451584 I | embed: rejected connection from "[2001:db8:101:53e9::1:2d]:60828" (error "remote error: tls: bad certificate", ServerName "[2001")
2019-10-06 18:33:18.742184 I | embed: rejected connection from "[2001:db8:101:53e9::1:2d]:60834" (error "remote error: tls: bad certificate", ServerName "[2001")
2019-10-06 18:36:14.504374 I | mvcc: store.index: compact 57302
```

Verified the cert used by the 2nd kube master has the right server name (of the IP).

**What you expected to happen**:
`kubeadm join` bring the 2nd kube master into the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1. `kubeadm init` on master-1
2. `kubeadm join` on master-2

**Anything else we need to know?**:
1. I used the same steps to create 1.15.3 without problem
2. This is a pure IPv6 env that does not have any IPv4.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Openstack
- OS (e.g: `cat /etc/os-release`):
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux x1-master-2.x1-host.rkn.ksng.io 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:58:27Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Network plugin and version (if this is a network-related bug):
calico
- Others:
host has IPv6 only, there is no IPv4 interfaces.

**Comment by hangxie** [comment]
@kuberbetes/sig-cluster-lifecycle-bugs

**Comment by neolit123** [comment]
/area kubeadm
/priority awaiting-more-evidence

> I used the same steps to create 1.15.3 without problem

are you using the automatic copy of certificates when joining new control plane nodes?

**Comment by neolit123** [comment]
> Running kubeadm 1.16.1 on CentOS7 with local etcd, the first kube master (2001:db8:101:53e9::1:17) is up and running, try to make the second master (2001:db8:101:53e9::1:2d) join the cluster and got error:

is this reproducible consistently?

**Comment by hangxie** [comment]
> are you using the automatic copy of certificates when joining new control plane nodes?

This is what I was using:
```
kubeadm join [2001:db8:101:53e9::1:e]:6443 --token v3unpj.g914vnnk70a9d89j --discovery-token-ca-cert-hash sha256:bd760e4bd3542e4fb5861bc094477e5de3935ddb3ff6e0ff97df0936e0f94048 --control-plane --certificate-key 03a9bbb5f50ec09be4b78702b4909c2ad39d43ac4a51b7e76ea4ab8ce289221b --node-name master-2 -v 9
```
> is this reproducible consistently?

Yes, it is, I tried 5 or 6 times with the same result.

**Comment by neolit123** [comment]
@aojea @BenTheElder as far as i know we already have signal for kubeadm/kind cluster for single control planes clusters using ipv6, but we don't have the same for multi-CP.

https://k8s-testgrid.appspot.com/sig-testing-kind#kind-ipv6-1.16-parallel
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel-latest-1-16/1181513465345347592/build-log.txt

do you have any plans or reservations for extending the kind config there to be HA?

cc @Arvinderpal

**Comment by neolit123** [comment]
@hangxie 
i don't think we have test signal for HA clusters using kubeadm with ipv6, but i can test this locally.

> I used the same steps to create 1.15.3 without problem

and this works consistently?
also please mind that 1.16 includes a new version of etcd,

**Comment by aojea** [comment]
I guess that this error snippet can be a good hint, it seems it's adding some part of the IP address as servername. Will try to reproduce it too

` ServerName "[2001`

There no signal for HA cluster with ipv6 AFAIK

**Comment by neolit123** [comment]
i'm starting to suspect a bug in etcd-3.3.15 that we use from kubeadm / k8s.

the kubeadm certificates are signed properly, yet member add using the client API (kubeadm uses that, and not raw etcdctl calls), fails:

```
2019-10-08T14:15:21.808182892Z stderr F 2019-10-08 14:15:21.807982 I | embed: rejected connection from "[2001:db8:1::242:ac11:3]:53740" (error "remote error: tls: bad certificate", ServerName "[2001")
```

```
ETCDCTL_API=3 ./etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/peer.crt --key=/etc/kubernetes/pki/etcd/peer.key --endpoints=https://[2001:db8:1::242:ac11:6]:2379 member list
467e2f41c172c89f, started, kind-control-plane, https://[2001:db8:1::242:ac11:6]:2380, https://[2001:db8:1::242:ac11:6]:2379
```

the suspicion for the time being is that `"[2001"` is the result of everything after the `:` is being cut when constructing the the golang TLS client with `SeverName` in it's config.

**Comment by neolit123** [comment]
just tested etcd-3.3.10 and i'm seeing the same problem with it.
which possibly indicates the problem is elsewhere. trying k8s 1.15 now.

**Comment by alexbrand** [comment]
Probably not, but I wonder if this is related to https://github.com/kubernetes/kubernetes/issues/83028

**Comment by neolit123** [comment]
@alexbrand 
i think that problem existed back when we were still using 3.3.10:
https://github.com/kubernetes/kubernetes/issues/83028#issuecomment-534307447

but i was able to create a good etcd cluster with 3.3.10 from 1.15, so i started bisecting the problem to see when in k/k it was introduced.

**Comment by hangxie** [comment]
> and this works consistently?
Yes 1.15.3 always worked fine, fyi, we have 5 or 6 clusters running 1.15.3 (both ubuntu and centos, if it matters), couple of dev/test clusters got redeployed roughly once a week in the past couple of months, there are more personal deployments.

> also please mind that 1.16 includes a new version of etcd,
I tried to tag k8s.gcr.io/etcd:3.3.10 from 1.15.3 to the new version and the behavior was the same, I tested only once though.

**Comment by neolit123** [comment]
@gyuho @liggitt @dims @jpbetz 

i think seeing this regression in the etcd client we vendor in k/k.

after hours of bisecting i ended at:
https://github.com/kubernetes/kubernetes/pull/81434

to summarize again:

we are seeing:
```
2019-10-08T14:15:21.808182892Z stderr F 2019-10-08 14:15:21.807982 I | embed: rejected connection from "[2001:db8:1::242:ac11:3]:53740" (error "remote error: tls: bad certificate", ServerName "[2001")
```

when multiple ipv6 etcd nodes join the cluster.

this starts happening only after https://github.com/kubernetes/kubernetes/pull/81434
it seems as the `ServerName` for the golang TLS client config is malformed and everything after `:` is trimmed.

(location in `master`)
https://github.com/etcd-io/etcd/blob/master/embed/config.go#L430

i did try etcdctl 3.3.15 from github and TLS worked fine:
```
ETCDCTL_API=3 ./etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/peer.crt --key=/etc/kubernetes/pki/etcd/peer.key --endpoints=https://[2001:db8:1::242:ac11:6]:2379 member list
467e2f41c172c89f, started, kind-control-plane, https://[2001:db8:1::242:ac11:6]:2380, https://[2001:db8:1::242:ac11:6]:2379
```

@gyuho do you happen to remember any changes in this area?
i did find `ServerName` related changes in the 3.x changelogs, but nothing apparent without checking the code.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/commit/3d6ae5ef12b2acc7427be43114c4a8da50c042e7#diff-73e6227e3f7452a2c93cff8771f41e2bR368-R396 might be related

**Comment by liggitt** [comment]
cc @jpbetz @gyuho

**Comment by liggitt** [comment]
adding api-machinery / apiserver in case this also affects failover

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.16/vendor/google.golang.org/grpc/credentials/credentials.go#L169-L173 looks very wrong and very related, but was also present in 1.15 (https://github.com/kubernetes/kubernetes/blob/release-1.15/vendor/google.golang.org/grpc/credentials/credentials.go#L139-L143)

@jpbetz, do you know if something in the etcd v3.3.15 bump started making use of that codepath?

**Comment by liggitt** [comment]
oh, nevermind, it's https://github.com/kubernetes/kubernetes/blob/release-1.16/vendor/github.com/coreos/etcd/clientv3/balancer/resolver/endpoint/endpoint.go#L231-L240

**Comment by liggitt** [comment]
that method should switch to using net.SplitHostPort(); I'm unsure whether it should unwrap ipv6 hosts or return them still in brackets

**Comment by neolit123** [comment]
/retitle 1.16: etcd client does not parse IPv6 addresses correctly when members are joining

**Comment by jpbetz** [comment]
We will backport the etcd fix to 3.4 and 3.3 once it is merged to master.

**Comment by jpbetz** [comment]
etcd backports:
- 3.4: https://github.com/etcd-io/etcd/pull/11213
- 3.3: https://github.com/etcd-io/etcd/pull/11216

**Comment by svallala** [comment]
Seeing the same issue after upgrading to v3.3.17

019-10-24 23:54:17.742204 I | etcdserver: starting server... [version: 3.3.17, cluster version: to_be_decided]
2019-10-24 23:54:17.744517 I | etcdserver: 3286414e675bdaa2 as single-node; fast-forwarding 9 ticks (election ticks 10)
2019-10-24 23:54:17.745133 I | etcdserver/membership: added member 3286414e675bdaa2 [https://[fd74:ca9b:3a09:868c:10:9:60:218]:2380] to cluster dc2df941b6f4bcc1
2019-10-24 23:54:17.755251 I | embed: ClientTLS: cert = /etc/kubernetes/pki/etcd/server.crt, key = /etc/kubernetes/pki/etcd/server.key, ca = , trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true, crl-file = 
2019-10-24 23:54:17.755834 I | embed: listening for metrics on http://127.0.0.1:2381
2019-10-24 23:54:18.709225 I | raft: 3286414e675bdaa2 is starting a new election at term 1
2019-10-24 23:54:18.709302 I | raft: 3286414e675bdaa2 became candidate at term 2
2019-10-24 23:54:18.709360 I | raft: 3286414e675bdaa2 received MsgVoteResp from 3286414e675bdaa2 at term 2
2019-10-24 23:54:18.709391 I | raft: 3286414e675bdaa2 became leader at term 2
2019-10-24 23:54:18.709412 I | raft: raft.node: 3286414e675bdaa2 elected leader 3286414e675bdaa2 at term 2
2019-10-24 23:54:18.709831 I | etcdserver: setting up the initial cluster version to 3.3
2019-10-24 23:54:18.712158 N | etcdserver/membership: set the initial cluster version to 3.3
2019-10-24 23:54:18.712283 I | etcdserver/api: enabled capabilities for version 3.3
2019-10-24 23:54:18.712359 I | etcdserver: published {Name:centos-60-218 ClientURLs:[https://[fd74:ca9b:3a09:868c:10:9:60:218]:2379]} to cluster dc2df941b6f4bcc1
2019-10-24 23:54:18.712737 I | embed: ready to serve client requests
2019-10-24 23:54:18.712929 I | embed: ready to serve client requests
2019-10-24 23:54:18.721854 I | embed: serving client requests on [fd74:ca9b:3a09:868c:10:9:60:218]:2379
2019-10-24 23:54:18.722025 I | embed: serving client requests on 127.0.0.1:2379
2019-10-25 00:00:56.365432 I | embed: rejected connection from "[fd74:ca9b:3a09:868c:10:9:60:219]:42664" (error "remote error: tls: bad certificate", ServerName "[fd74")
2019-10-25 00:00:57.370740 I | embed: rejected connection from "[fd74:ca9b:3a09:868c:10:9:60:219]:42668" (error "remote error: tls: bad certificate", ServerName "[fd74")
2019-10-25 00:00:59.297547 I | embed: rejected connection from "[fd74:ca9b:3a09:868c:10:9:60:219]:42674" (error "remote error: tls: bad certificate", ServerName "[fd74")
2019-10-25 00:01:01.577043 I | embed: rejected connection from "[fd74:ca9b:3a09:868c:10:9:60:219]:42680" (error "remote error: tls: bad certificate", ServerName "[fd74")
2019-10-25 00:01:05.930298 I | embed: rejected connection from "[fd74:ca9b:3a09:868c:10:9:60:219]:42692" (error "remote error: tls: bad certificate", ServerName "[fd74")
2019-10-25 00:01:12.178388 I | embed: rejected connection from "[fd74:ca9b:3a09:868c:10:9:60:219]:42706" (error "remote error: tls: bad certificate", ServerName "[fd74")

Did anyone verify that it works with this version?
K8s Version: 1.16.2
k8s.gcr.io/etcd: 3.3.17

**Comment by liggitt** [comment]
The issue is client-side, and will be fixed in 1.16.3 by https://github.com/kubernetes/kubernetes/pull/83968

**Comment by libnux** [comment]
@liggitt  Could you please tell release date of v1.16.3?  Thanks.

**Comment by liggitt** [comment]
https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#timelines

Target date of 2019-11-13
