### ISSUE TITLE
Horizontal Pod Autoscaler fooled by terminating pods

### ISSUE THREAD

**Issue by f-ld** [kubernetes/kubernetes#83561]
**What would you like to be added**:

An option inside HPA to ignore "Terminating" pods (i.e. pods that have been elected for downscale but are for example waiting for the prestop hook to give permission to k8s to actually stop them) when computing resource usage.

**Why is this needed**:

Let's take an example.

I have a service S processing some short to long queries (for this example, think 1min in general, but with some queries taking by nature up to 30 min). Each query uses about 5% of CPU. We configure 75% utilisation of the cluster (so an average of 15 queries running on each instance).
_To make this example simpler lets assume that the service doing nothing takes 0% and that we start with only one instance of the service_

When we start the 16th concurrent query, CPU of first instance will be 80% -> HPA will start a second one.
If we keep running 16-30 queries for some time, we will end up having 2 evenly loaded instances with 8-15 queries each. So far so good.

But if for some time we go down to 12 queries, both instances will be at 30% then a downscale will happen and one instance will be "terminating" (and thanks to the prestop hook, it will stay in that state until the last query ends, so up to 30 min based on our initial assumption of the duration of queries). And thanks to Murphy's law, the instance elected for termination was running 5 short queries that end quickly and one long that was started just before the downscale and that will last for 30 min. So for more than 25 minutes, that terminating instance will be using 5% CPU.

Let's assume we go up again adding queries quickly one by one:
- when reaching 16 queries then CPU will be 75% for first instance running 15 queries and 5% for terminating instance running 1 query. Average is 40%, so no upscaling
- when reaching 21 queries then CPU will be 100% for first instance running 20 queries and 5% for terminating instance still running 1 query. Average is 52.5% so still not upscaling
- adding more queries will be an issue (either queued / rejected or CPU throttled on first instance).

If there is some issue in query running on stopping instance and if it never stops, then HPA is totally blocked. Even if we have 100 queries in the system, we will keep one instance of the service saturated.

Setting HPA target utilisation to 50% would solve this example. But think 3 instances, downscaling 2 and then you need it to be 33%. And so on. 

We've been facing that use case a few times. After receiving alerts for CPU over limit, the solution was to change the HPA minimum to force it to upscale.

**Comment by f-ld** [comment]
@kubernetes/sig-autoscaling-feature-requests

**Comment by johscheuer** [comment]
I think this actually is a bug in the pod autoscaler since the endpoint controller will also remove the pod from the endpoints list (which means it doesn't receive any traffic anymore). Probably nobody noticed this since most of the pods are terminated pretty fast.

**Comment by jim-barber-he** [comment]
This caused an outage for us.
We had 6 running webserver pods serving our website and then we performed a deployment.
6 more new pods came up, and the 6 old pods went into a Terminating state, all of which were there for several minutes due to the preStop lifecycle rules.
During this time, the HPA was including the terminating pods in its CPU calculations and decided it would scale down the new webservers by half reducing the 6 new pods to 3.
The 3 remaining webservers were quickly overloaded and an outage ensued.

**Comment by f-ld** [comment]
On our side we have a custom load balancer (that reads metrics from instances targetted by service and send requests accordingly) and we added an option to that load balancer to get cpu of all target instances and compute what it thinks should be the minimum number of instances acceptable and set it as HPA min.

So we keep using HPA, we only have that custom LB instance changing the min to push it up if it considers the HPA will be misbehaving because of terminating instances.

**Comment by josephburnett** [comment]
/triage accepted
/assign josephburnett

We classify pods into three sets, `readyPodCount`, `ignoredPods` and `missingPods` (missing metrics).  The ignored pods are those which are not yet ready, and hold back scaleup.  Missing pods are those whose metrics we "manufacture" with the most conservative value.

However in the case of failed or deleted pods, we skip right over them.  The don't go into any of the three sets: https://github.com/kubernetes/kubernetes/blob/v1.15.12/pkg/controller/podautoscaler/replica_calculator.go#L372

As such, when we remove the ignored pod metrics: https://github.com/kubernetes/kubernetes/blob/v1.15.12/pkg/controller/podautoscaler/replica_calculator.go#L78 these deleted pod metrics *remain* (!?) which is incorrect for pods which are lameducking for deletion.

It looks like this bug is introduced in this commit where we were previously deleting the metrics: https://github.com/kubernetes/kubernetes/commit/7d6676eab1b7d6a1ee241b9482e3f8dfc12a29bc#diff-4965c0381afe90ef9a428cfcda88dd1fd167e6eb202b48b4eecf9e5f7354499aL100

**Comment by josephburnett** [comment]
There is a unit test for ignoring deleted pods.  But it assumes deleted pods will not be producing metrics.  I "fixed" this and now the test fails, as expected.

```diff
diff --git a/pkg/controller/podautoscaler/replica_calculator_test.go b/pkg/controller/podautoscaler/replica_calculator_test.go
index 7fd85ab88b4..18bc5b60ddf 100644
--- a/pkg/controller/podautoscaler/replica_calculator_test.go
+++ b/pkg/controller/podautoscaler/replica_calculator_test.go
@@ -929,7 +929,7 @@ func TestReplicaCalcScaleDownIgnoresDeletionPods(t *testing.T) {
                resource: &resourceInfo{
                        name:     v1.ResourceCPU,
                        requests: []resource.Quantity{resource.MustParse("1.0"), resource.MustParse("1.0"), resource.MustParse("1.0"), resource.MustParse("1.0"), resource.MustParse("1.0"), resource.MustParse("1.0"), resource.MustParse("1.0")},
-                       levels:   []int64{100, 300, 500, 250, 250},
+                       levels:   []int64{100, 300, 500, 250, 250, 0, 0},

                        targetUtilization:   50,
                        expectedUtilization: 28,
```

```
--- FAIL: TestReplicaCalcScaleDownIgnoresDeletionPods (0.10s)
    replica_calculator_test.go:373:
                Error Trace:    replica_calculator_test.go:373
                                                        replica_calculator_test.go:939
                Error:          Not equal:
                                expected: 3
                                actual  : 2
                Test:           TestReplicaCalcScaleDownIgnoresDeletionPods
                Messages:       replicas should be as expected
    replica_calculator_test.go:374:
                Error Trace:    replica_calculator_test.go:374
                                                        replica_calculator_test.go:939
                Error:          Not equal:
                                expected: 28
                                actual  : 20
                Test:           TestReplicaCalcScaleDownIgnoresDeletionPods
                Messages:       utilization should be as expected
    replica_calculator_test.go:375:
                Error Trace:    replica_calculator_test.go:375
                                                        replica_calculator_test.go:939
                Error:          Not equal:
                                expected: 560
                                actual  : 400
                Test:           TestReplicaCalcScaleDownIgnoresDeletionPods
                Messages:       raw value should be as expected
```

**Comment by jinleileiking** [comment]
This issue remains. Consider this:

pod is working R metric: running = 1, total = 1    
pod is not working F metric: running = 0, total = 1

hpa target = sum(running) / sum(total), the target is 50%, that is, if it is less than half of the pods that are not working, it needs to be expanded.

        
Now four pod status TRRF, target = 66%, T = terminating

        
After calculating hpa, 2 / 4 = 50%, 4 pods are needed, but the terminating pod is included in the 4, so it is not scaled up.
