### ISSUE TITLE
node-kubelet-master tests fail during startup

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#83560]
**Which jobs are failing**:
node-kubelet-master in master blocking
https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master

**Which test(s) are failing**:
test startup, the tests don't even get run

**Since when has it been failing**:
10/02

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master

**Reason for failure**:
```
I1002 02:30:10.594] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I1002 02:30:10.594] >                              START TEST                                >
I1002 02:30:10.594] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I1002 02:30:10.595] Start Test Suite on Host 
I1002 02:30:10.595] 
I1002 02:30:10.595] Failure Finished Test Suite on Host 
I1002 02:30:10.595] unable to create gce instance with running docker daemon for image cos-stable-60-9592-84-0.  googleapi: Error 404: The resource 'projects/k8s-jkns-ci-node-e2e/zones/us-west1-b/instances/tmp-node-e2e-3039b3ed-cos-stable-60-9592-84-0' was not found, notFound
```

**Anything else we need to know**:
/kind flake
/priority important-soon
/milestone v1.17
/sig node
cc. @droslean @hasheddan @Verolop @epk

**Comment by derekwaynecarr** [comment]
will raise in sig-node.

**Comment by derekwaynecarr** [comment]
@dashpole i have little ability to look at cos related issues, is someone able to assist on the google side?

**Comment by dashpole** [comment]
@derekwaynecarr sorry I didn't get to this... It is all green now, so I think we can close.

**Comment by alenkacz** [comment]
/close

I'll move this to observing but it looks like it got resolved somehow 🤷‍♀
