### ISSUE TITLE
Improving scheduler tests 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83574]
The scheduler has evolved at a very fast pace over the past few years, it is important to revisit our unit and integration test coverage of all scheduler features and config combinations. 

This is critical now that we are going through a major refactoring of the scheduler core, and so it is a good opportunity to refactor and improve the scheduler's tests at the same time.

What we need is a better understanding of our current coverage and a plan to cover the gaps. 

/assign @alculquicondor 
/assign @ahg-g 
/sig scheduling

**Comment by SataQiu** [comment]
/cc 
Do we have any specific plans? @ahg-g 
I volunteer to help.

**Comment by alculquicondor** [comment]
Please stay tuned until after the code freeze.

**Comment by alculquicondor** [comment]
/close

because of the scope being too broad. I'm opening specific issues as I see fit.
