### ISSUE TITLE
Uncomment interpod affinity integration tests

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83581]
A significant number of the of [InterPodAffinity integration tests](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/predicates_test.go#L77-L589) are commented out, possibly was done by mistake in the past. I uncommented the tests to see if they pass, but one of them failed.

What we need is to uncomment those tests, fix the one that is not passing and remove the redundant ones if there are any.

/sig scheduling
/help

**Comment by alculquicondor** [comment]
/assign

I will be moving some of the tests to unit tests and leave a cleaner set of integration tests.

**Comment by alculquicondor** [comment]
@ingvagabund, would you like to take this? I can provide guidance.
