### ISSUE TITLE
Vsphere cloud provider is reporting link local IP address as node internal/external IP

### ISSUE THREAD

**Issue by shyaamsn** [kubernetes/kubernetes#83584]
**What happened**:
Vsphere cloud provider is reporting link local IP address as node internal/external IP

```
ubuntu@ops-manager:~$ kubectl get nodes -o wide
NAME                                   STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                  KERNEL-VERSION      CONTAINER-RUNTIME
329114da-30ed-44f4-be76-aaf80d654ce3   Ready    <none>   36m   v1.14.5   169.254.1.0   169.254.1.0   Windows Server 2019 Standard Evaluation   10.0.17763.737      docker://18.9.0
a7fa28bf-1f2f-4b6b-8ff5-5eb43850f27f   Ready    <none>   34m   v1.14.5   169.254.1.0   169.254.1.0   Windows Server 2019 Standard Evaluation   10.0.17763.737      docker://18.9.0
e5eeaba4-5ce4-49d4-9930-74cafa900dde   Ready    <none>   38m   v1.14.5   40.0.1.3      40.0.1.3      Ubuntu 16.04.6 LTS                        4.15.0-55-generic   docker://18.9.8
```
```
ubuntu@ops-manager:~$ kubectl get node 329114da-30ed-44f4-be76-aaf80d654ce3 -o json | jq .status.addresses
[
  {
    "address": "169.254.1.0",
    "type": "ExternalIP"
  },
  {
    "address": "169.254.1.0",
    "type": "InternalIP"
  },
  {
    "address": "40.0.1.4",
    "type": "ExternalIP"
  },
  {
    "address": "40.0.1.4",
    "type": "InternalIP"
  },
  {
    "address": "40.0.1.4",
    "type": "Hostname"
  }
]
```

**What you expected to happen**:
Vsphere cloud provider should filter out the link local IP address when detecting the node IP

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.5
- Cloud provider or hardware configuration: vsphere
- OS (e.g: `cat /etc/os-release`): windows server 2019 - OS version - 10.0.17763
- Kernel (e.g. `uname -a`): windows server 2019
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by shyaamsn** [comment]
/sig cloud-provider
/area/provider/vmware

**Comment by hubv** [comment]
/assign
PR #86001 may fix this issue

**Comment by hubv** [comment]
Could someone help to cherry-pick PR #86001 into v1.17.x or v1.16.x? Then we can adopt it before v1.18.
