### ISSUE TITLE
flaky test for GCE PD e2e test "should store data"

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#83590]
**Which test(s) are failing**:
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (ntfs)][sig-windows] volumes should store data

**Since when has it been failing**:

**Testgrid link**:
https://testgrid.k8s.io/sig-windows#gce-windows-master&include-filter-by-regex=ntfs&include-filter-by-regex=should%20store%20data

**Reason for failure**:
The root case of this test failure is explained in issue https://github.com/container-storage-interface/spec/issues/388

**Anything else we need to know**:

**Comment by spiffxp** [comment]
/remove-kind failing-test
/kind flake
this isn't a continuously failing test

**Comment by spiffxp** [comment]
Based on where discussion landed in https://github.com/container-storage-interface/spec/issues/388 it seems like there is consensus to make no guarantee of data actually persisting on windows.  In which case I feel like this test should either be tagged as [Flaky] or removed if we can't make that guarantee?

**Comment by spiffxp** [comment]
/assign @jingxu97 @msau42 
cc @kubernetes/sig-windows-bugs 
What do you think about tagging this test case as [Flaky]? It's still flaking, and per above it's not deemed to be a CSI issue
- https://testgrid.k8s.io/sig-windows#gce-windows-1909-master&include-filter-by-regex=ntfs&include-filter-by-regex=should%20store%20data&width=5
- https://testgrid.k8s.io/sig-windows#gce-windows-2019-master&include-filter-by-regex=ntfs&include-filter-by-regex=should%20store%20data&width=5

**Comment by msau42** [comment]
This test case isn't actually testing CSI. 
https://github.com/kubernetes/kubernetes/pull/83591 should have fixed the flaky test issue.

@jingxu97 can you take another look at why this test is flaky?
