### ISSUE TITLE
1.16 cs age unknown

### ISSUE THREAD

**Issue by fanux** [kubernetes/kubernetes#83602]
**What happened**: 

kubectl get cs:

![image](https://user-images.githubusercontent.com/8912557/66362806-aef32200-e9b6-11e9-99b0-ee0e917e63a3.png)

- Kubernetes version (use `kubectl version`):1.16.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos7.4
- Kernel (e.g. `uname -a`):3.10

**Comment by zouyee** [comment]
Now cs only output age which default is unknown, and will be mark deprecated https://github.com/kubernetes/enhancements/issues/553
/close
