### ISSUE TITLE
Lots of `du` process are stucked when rotate the containers' logs

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#83608]
**What happened**:
One of our nodes is running out of pid, then we found there are lots of `du` processes are running 
```
-bash-4.2# ps -ef|grep -i du |wc -l
64298
```
The du process is used to check the log size 
```
root       6880      1  0 Sep27 ?        00:00:00 du -s -B 1 /var/log/pods/2b5a60a3-bd4e-11e9-b39c-3cfdfe588618/node-exporter
```

But it is stucked at:
```
stat("/var/mnt/kubelet/pods/e1f4051d-734a-11e9-ba94-3cfdfe588618/volumes/kubernetes.io~downward-api/my-annotations", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=100, ...}) = 0
brk(NULL)                               = 0x1d1f000
brk(0x1d42000)                          = 0x1d42000
stat("/run/containerd/io.containerd.grpc.v1.cri/sandboxes/2ff553d4884004c672028357eac1e923bffa99eb35d5ca7740f0e1bfaef2df96/shm", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=40, ...}) = 0
**stat("/var/mnt/kubelet/pods/8ff23167-7384-11e9-a82f-3cfdfe589718/volumes/kubernetes.io~cephfs/ceph-fs",**
```
It is caused by one ceph fuse network volume lose the connection.
`du` command need to check the  directories in `/etc/mtab` file, so it caused this issue. 
We can kick the stall ceph-fuse connection to recover, but we still need to limit the `du` processes number or we need to avoid that it blocked by checking other unnecessary dir. 

**What you expected to happen**:
- limit the `du` processes  number.
- `du` not hang in such situation.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wenlxie** [comment]
@Random-Liu  PTAL.

**Comment by Colstuwjx** [comment]
As far as I known, we are moving to disk quota rather than du to monitor, how about enable the `LocalStorageCapacityIsolationFSQuotaMonitoring=true` for testing whether fixes this issue?

See document [here](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#monitoring-ephemeral-storage-consumption) .
