### ISSUE TITLE
Don't override the node capacity if cadvisor isn't functional

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#8361]
From https://github.com/GoogleCloudPlatform/kubernetes/pull/6949

@smarterclayton said: "Anyone can call the node api. If cadvisor can't report anything, and the node already has something, should the node overwrite the capacity? I would argue it should set zero if nothing is set, but if it's explicitly set (perhaps from the last time) it shouldn't be reset. Not a massively strong feeling, but if cadvisor is dead I don't know that we should be making the node completely unschedulable (by forcing capacity to 0)"

**Comment by dchen1107** [comment]
I don't get the scenario described above. Since cadisor is part of kubelet now, when cadvisor is dead, kubelet is dead too. In this case, node is unschedulable anyway.

**Comment by vmarmol** [comment]
I'm guessing the issues are on builds when cAdvisor is not available (when not compiled in Linux).

**Comment by smarterclayton** [comment]
The simplest scenario I'm considering right now is Windows support and the number of baked in assumptions we'll have to fix at that point.  I'd like to keep the coupling points sane so that something (maybe cadvisor) can report information, but that the node registration path isn't blocked on that.

**Comment by markturansky** [comment]
When cadvisor is unavailable (say, on OS X), a node has no pod capacity and cannot schedule any pods.  This was only recently introduced.

This one liner fixes it:   https://github.com/GoogleCloudPlatform/kubernetes/pull/8826
