### ISSUE TITLE
kubectl cannot process listed objects in json file

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#8362]
kubectl cannot process the following listed objects (copied from [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/secrets.md#use-case-pods-with-prod--test-credentials))
```
[{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "prod-db-secret",
  "data": {
    "username": "dmFsdWUtMQ0K",
    "password": "dmFsdWUtMg0KDQo="
  }
},
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "test-db-secret",
  "data": {
    "username": "dmFsdWUtMQ0K",
    "password": "dmFsdWUtMg0KDQo="
  }
}]
```
```
$ kubectl create -f ...
Error: unable to get type info from "double.json": couldn't get version/kind: json: cannot unmarshal array into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
#7257 states "Group related objects together in a single file. This currently requires a List object in YAML, but it's still better than separate files. Almost nobody knows about this feature." Does this feature only work for YAML but not JSON? Thanks.
@bgrant0607 @krousey @nikhiljindal

**Comment by bgrant0607** [comment]
You can either put the objects back to back (no list syntax) or insert the following:
```
kind: List
apiVersion: v1beta2
```

**Comment by bgrant0607** [comment]
Oh, and items:. See #5840

**Comment by caesarxuchao** [comment]
Thanks, @bgrant0607. The list works. But the "back to back" doesn't. Is this what you mean by "back to back"?
```
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "prod-db-secret",
  "data": {
    "username": "dmFsdWUtMQ0K",
    "password": "dmFsdWUtMg0KDQo="
  }
},
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "test-db-secret",
  "data": {
    "username": "dmFsdWUtMQ0K",
    "password": "dmFsdWUtMg0KDQo="
  }
}
```
With or without the "," separating the two items, it doesn't work.

**Comment by bgrant0607** [comment]
If there's a way to specify multiple resources in JSON without an explicit List, we should document and test it.

EIther way, we should fix the example.

cc @JanetKuo

**Comment by JanetKuo** [comment]
Here's the test json file for specifying multiple resources in JSON (without an explicit List). https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/multi-resource-json.json
We added the test in test-cmd.sh in #14793. 

Is this the example @caesarxuchao mentioned? Looks like it's fixed. https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/secrets.md#use-case-pods-with-prod--test-credentials

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/multi-resource-json.json
is what we called "multiple resources in JSON without an explicit List". So it's fixed now. Thank you @JanetKuo. I'm closing this issue.
