### ISSUE TITLE
PodReadinessGate to support conditions defaulting to True

### ISSUE THREAD

**Issue by nimakaviani** [kubernetes/kubernetes#83628]
Currently `PodReadinessGate` requires a two-step update to the Pod for a user provided condition to be set to `True`. 

1. The `conditionType` is introduced when creating the pod
1. The  Pod `status` is patched to set the condition to `True`.

While the behavior works for the initially intended purpose of this field (ie. more control over when to make the Pod available for routing traffic), reversing this behavior is not easily achieved.

We would like to use the user provided readiness conditions as a way to notify the control plane that a given pod needs to stop serving traffic and its respective endpoints need to be removed. 

As such, ideally we would like to create the pod with the custom pod condition set to `True` by default to be able to toggle it to `False` and retrigger reconciliation at a later point as needed.

`PodReadinessGate` supporting custom conditions defaulting to `True`, appears to be the right approach to it.

/cc @greghaynes 
/sig apps
/sig api-machinery

**Comment by janetkuo** [comment]
This feature is owned by sig-network https://github.com/kubernetes/enhancements/issues/580

/sig network 
@freehan

**Comment by nimakaviani** [comment]
@freehan can you share your thoughts on this?

**Comment by bowei** [comment]
It would be good to describe the high level workflow you are trying to achieve. It's not obvious to me that Pod readiness gates should be the mechanism for what you are trying to do?

**Comment by nimakaviani** [comment]
At a high level the workflow is something like the following:

- Knative creates a deployment with custom `PodReadinessGate` set to `true` for its Pods.
- The deployment creates `X` number of Pods as specific in deployment's `replicaCount`
- At the time of scaledown:
  - Knative selectively toggles the `PodReadinessGate` condition to `false`, for the `Y` number of pods it intends to kill (basically marking them as not ready, based on metrics known to Knative autoscaler)
  - Knative autoscaler patches the `replicaCount` on the deployment to `X - Y`
  - Kubernetes notices change in pod count expectations and removes the unready Pods following [this comparison](https://github.com/kubernetes/kubernetes/blob/6a19261e96b12c83e6c69d15e2dcca8089432838/pkg/controller/controller_utils.go#L831-L873).

Essentially the idea is to utilize readiness as a means to make k8s be more decisive about pods to kill when scaling down. This will potentially help with solving similar problems for k8s like discussed here: https://github.com/kubernetes/kubernetes/issues/45509

We have tested and verified that changing Pod readiness allows for this behavior, but this is not uniformly achievable by failing the `ReadinessProbe` since configuraion parameters like `FailureThreshold` and `TimeoutSeconds` can delay the amount of time it takes for the Pod to become `Not Ready`.

Let me know if more clarification is needed.

/cc @maximilien

**Comment by maximilien** [comment]
Hi, all, any update on this @bowei and @freehan? We would love to have some resolution (or at least discussions) on this before EOY. Thanks.

**Comment by freehan** [comment]
Just glance thru the issue. 

Based on the knative use case described [here](https://github.com/kubernetes/kubernetes/issues/83628#issuecomment-558305663), if a default True option is available, it seems like it just reduces the # of patches from 2 (1 patch to unblock Ready on start up and 1 patch to mark pod NotReady on shutdown) to 1 (1 patch on shutdown). 

I feel like this should be a feature request for `sig-app` to allow users to specify priority-deletion-candidates for pods managed by replicaSet. This is the real problem is that K8s API does not allow user to express which pods should be deleted first. 

WDYT?

**Comment by maximilien** [comment]
@freehan thanks for the quick reply. However, I am afraid that sending this to another SIG will lose the context and delay this even more. Plus it’s not clear to me that `sig-app` is where it belongs.

**Comment by nimakaviani** [comment]
@freehan the issue is independent of the Knative problem we are trying to solve.

This issue is to suggest to have `to allow for predefined condition values for the `PodReadinessGate` so that its value can be set without having to go through the control plane a second time. This simplifies utilizing it as a `PodNotReadyGate` that can have multiple use cases, ours included.

**Comment by freehan** [comment]
The issue is already tagged with `sig-app`. Can anyone from @kubernetes/sig-apps-misc chime in regarding the following idea? 


> This could be a feature request for sig-app to allow users to specify priority-deletion-candidates pods managed by replicaSet. The real problem underneath is that K8s API does not allow user to express which pods should be deleted first besides built comparison [here](https://github.com/kubernetes/kubernetes/blob/6a19261e96b12c83e6c69d15e2dcca8089432838/pkg/controller/controller_utils.go#L831-L873).

**Comment by maximilien** [comment]
@freehan as you know this is important for us. How long shall we wait for `sig-app`? did you have any discussions with them? I am afraid they will ignore it. Especially since w/o addressing it we might appear to simply be throwing the “hot potatoe”... anyhow, do let us know. Can we timebox this (for responses from sig-app) to 7 or 14 days?

**Comment by bowei** [comment]
Let me see if I can rouse someone from sig-apps to keep the conversation going

**Comment by janetkuo** [comment]
> ...allow users to specify priority-deletion-candidates pods managed by ReplicaSet

ReplicaSet controller has some built-in logic for which Pods to delete first. Allowing users to specify this requires some API & controller changes. Would you write a KEP with more details?

**Comment by thockin** [comment]
> This issue is to suggest to allow for predefined condition values

You say "predefined" but it took me a minute to understand what this really meant.  Do you mean that the condition doesn't exist but is presumed to be true?  You can't create a pod and set `spec` and `status` at the same time, so you would have to first set it to true, and then set it to false.

Is that right?

@freehan if a readinessGate condition reverts from true to false, does readiness gate kick in and change "ready" to false?

So one way to tackle this would be to make readiness gates more configurable.  It's already a struct, so not very API-difficult, though rollout needs to be done carefully (consider back-rev kubelets).

But is that really what we think is the best API for biasing controllers while scaling down?  I am not so sure about this.  

@janetkuo if we simply put the requirement out there, what would you think about API ideas for it?

Requirement: A user or controller must be able to select specific pods to remove on the next scale-down.

**Comment by hex108** [comment]
/reopen

We have another use case for it.

We add a readiness gate to pod in our new kind app(https://github.com/tkestack/tapp), and it will only be set to false for some specific cases. If we support setting default value for PodReadinessGate, we could save some unnecessary update fot the pod condition(e.g. we do not need to set it to true when pod is created).

**Comment by thockin** [comment]
I'm sorry I just don't think we have enough demand for this additional complexity right now.
