### ISSUE TITLE
[migration phase 1] VolumeBindingChecker as filter plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83635]
**What would you like to be added**:

Add a filter plugin that calls into VolumeBindingChecker predicate, example #83460

**Why is this needed**:

Part of  #83554

/sig scheduling
/help
/priority important-soon

**Comment by cofyc** [comment]
We can convert the current volume binder into a plugin that implements FilterPlugin (https://github.com/kubernetes/kubernetes/issues/56180).
