### ISSUE TITLE
[migration phase 1] VolumeZoneChecker as filter plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83634]
**What would you like to be added**:

Add a filter plugin that calls into VolumeZoneChecker predicate, example #83460

**Why is this needed**:

Part of  #83554

/sig scheduling
/help
/priority important-soon

**Comment by notpad** [comment]
@ahg-g Do you have any suggestion to the plugin name, how about VolumeZone?

**Comment by ahg-g** [comment]
VolumeZone sounds good.
