### ISSUE TITLE
e2e tests to verify kubelet and docker integration 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#8365]
Forked from #8358 ...

We need a test to verify kubelet and docker integration which should covers:

1) image, registry, etc.
2) container lifecycle
3) docker exec and hooks
4) resource related ... 

We already have some tests cover 1) to 3), but missing 4) for sure.

**Comment by pmorie** [comment]
Maybe this should be combined w/ the docker containers e2e?

**Comment by yujuhong** [comment]
We have the ongoing work on docker validation test framework, and also a more generic CRI validation suite. Closing this.
