### ISSUE TITLE
Cannot remove disk pressure taint

### ISSUE THREAD

**Issue by davidq2q** [kubernetes/kubernetes#83668]
**What happened**:
Worker nodes were all under disk pressure. New pods were being evicted. After freeing up space and disk inodes disk pressure state was not refreshed. Removing the taint manually was not working either. Full restart of everything was required.

**What you expected to happen**:
Disk pressure state to be changed to false when inodes and space are freed up.

**How to reproduce it (as minimally and precisely as possible)**:
Fill up your disk space get disk pressure state to true on specific node. Then cleanup disk under pressure treshold and try to remove taint.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.13.5
- Cloud provider or hardware configuration:
Bare metal
2x Master node
3x Worker node
- OS (e.g: `cat /etc/os-release`):
```PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"```
- Kernel (e.g. `uname -a`):
```Linux node1 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 GNU/Linux```
- Install tools:
ansible (kubespray) and terraform
- Network plugin and version (if this is a network-related bug):
flannel
- Others:

**Comment by zouyee** [comment]
Unable to reproduce the problem. The taint was transient and has been removed after removed the extra file.

**Comment by k82cn** [comment]
please help to share the log of controller and kubelet.
