### ISSUE TITLE
Remove permissive-binding to all service accounts in kubernetes cluster

### ISSUE THREAD

**Issue by vkovelkar** [kubernetes/kubernetes#83675]

**Comment by vkovelkar** [comment]
I enabled the permissive-binding  to k8 cluster,  I need to remove permissive-binding now. any help please..

**Comment by liggitt** [comment]
If you're referring to https://kubernetes.io/docs/reference/access-authn-authz/rbac/#permissive-rbac-permissions, you can remove that with `kubectl delete clusterrolebinding permissive-binding`

Be aware that that any components relying on permissions granted via that binding will immediate receive forbidden errors.

/close

**Comment by vkovelkar** [comment]
thanks
