### ISSUE TITLE
[migration phase 1] Make scheduler cache, volume binder and listers available when registering default plugins

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83687]
**What would you like to be added**:

Plump through handlers, such as scheduler cache, volume binder among others to NewDefaultRegistry.

**Why is this needed**:

This is needed register factories for Plugins that need to instantiate predicates/priorities.

/sig scheduling
/assign

**Comment by hprateek43** [comment]
@ahg-g I can pick up this issue if I get a little more context around the solution

**Comment by ahg-g** [comment]
> @ahg-g I can pick up this issue if I get a little more context around the solution

Thanks, I already sent a PR.
