### ISSUE TITLE
1.17 Release Notes: “Known Issues”

### ISSUE THREAD

**Issue by evillgenius75** [kubernetes/kubernetes#83683]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.17 Release Notes. If you know of issues or API changes that are going out in 1.17, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @cartyc @evillgenius75 @bridgetkromhout

/sig release
/milestone v1.17

**Comment by josiahbjorgaard** [comment]
Bug triage for release 1.17 here. Since this issue has been tagged for the milestone, we would like to check it's status. Code freeze is on Nov. 19. Will this issue be resolved before then?

**Comment by josiahbjorgaard** [comment]
Hi bug triage team for 1.17, will this issue be resolved before code freeze on Nov. 14 (Thursday)?

**Comment by cartyc** [comment]
Hi @josiahbjorgaard based on the last release we kept a similar issue until the final Release Notes were published. This way we can keep track of any know issues that come up before release. I will bring this up at the Release Meeting tomorrow to make sure none have been missed.

**Comment by msau42** [comment]
I would like to get https://github.com/kubernetes/kubernetes/issues/85624 documented as a known issue, although it's actually been an issue for many releases now. Do we actively update previous release notes with known issues too?

**Comment by cartyc** [comment]
Hi @msau42 I will ask around to see if we need to do an update for previous notes. Thanks for getting this issue in :)

**Comment by cartyc** [comment]
@msau42 What releases does the issue affect?

**Comment by msau42** [comment]
> Michelle Au What releases does the issue affect?

1.9 when the BlockVolume feature was introduced as alpha.

**Comment by cartyc** [comment]
Adding #82387 as a known issue for the 1.17 release. 

cc @liggitt @justaugustus @rtheis

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/86149 for direct use of client-go discovery clients being rate-limited

**Comment by alejandrox1** [comment]
@evillgenius75 can we close this one?

**Comment by evillgenius75** [comment]
This issue can be closed as k/k 1.17 is released. All known issues for new Release to be commented on #86882
