### ISSUE TITLE
Storage DriverInfo has redundant fields `MaxSize` and `SupportedSizeRange`

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#83689]
Since this refactor added `SupportedSizeRange`: https://github.com/kubernetes/kubernetes/pull/78306
We seem to have these duplicate fields where `SupportedSizeRange` is used in most places and `MaxSize` is only used in one specific spot.

`MaxSize` is currently only used here:
https://github.com/kubernetes/kubernetes/blob/b8b7c376edb62ce8be42cef3728112c5c71d9fa4/test/e2e/storage/testsuites/volume_io.go#L145

Should we just remove that one usage of `MaxSize`? Not sure what the deprecation policy is on our exported struct and whether we can just remove that variable (or just mark as deprecated and not used).

**Comment by tedyu** [comment]
```
 just mark as deprecated and not used
```
+1

**Comment by davidz627** [comment]
Just saw this again and don't know what I was thinking. Seems like `MaxFileSize` is referring to file size for writing into the disk during tests - `SupportedSizeRange` is about the disk size itself. Was confused because `SupportedSizeRange` does not specify the size of what. These fields are not redundant.

**Comment by tedyu** [comment]
@davidz627 
How about adding comment above the two fields so that people looking at this code in the future would have better idea ?

I can send out a PR for this.

**Comment by davidz627** [comment]
yeah I think that would be good.
