### ISSUE TITLE
CSI cleans up MetaData file when MountDevice times out

### ISSUE THREAD

**Issue by rvakash** [kubernetes/kubernetes#83691]
**What happened**:
MountDevice calls csi.NodeStageVolume and if the call times out the defer func() cleans up the MetaData file. If the call to stage eventually goes through and the mount succeeds, future call to MountDevice will bail out since the directory is already mounted and it will return success without creating the meta files and thus causing the future UnmountDevice to fail even before making csi.NodeUnstageVolume call.

**What you expected to happen**:
UnmountDevice to go through.

**How to reproduce it (as minimally and precisely as possible)**:
Make the csi plugin NodeStageVolume implementation to take more than csiTimeout specified

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by msau42** [comment]
This is probably the same issue as https://github.com/kubernetes/kubernetes/issues/82190
/assign @gnufied

**Comment by gnufied** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/82492

closing.

/close
