### ISSUE TITLE
kubelet creates a new pod when vim opens staticPodPath file

### ISSUE THREAD

**Issue by xiaoanyunfei** [kubernetes/kubernetes#83708]
**What happened**:
when opening staticPodPath file with vim,  such as /etc/kubernetes/manifests/kube-scheduler.yaml, kubelet gets file change
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file_linux.go#L93

-  delete file : `/etc/kubernetes/manifests/4913`(It's always 4913, I don't know why)
-  /etc/kubernetes/manifests/kube-scheduler.yaml > /etc/kubernetes/manifests/kube-scheduler.yaml~

then the file becomes normal

-  /etc/kubernetes/manifests/kube-scheduler.yaml~> /etc/kubernetes/manifests/kube-scheduler.yaml

I add some log

> I1010 18:50:38.611634   11252 file_linux.go:124] name: /etc/kubernetes/manifests/4913 eventtype: 2
I1010 18:50:38.612379   11252 file_linux.go:124] name: /etc/kubernetes/manifests/kube-scheduler.yaml eventtype: 2
I1010 18:50:38.612397   11252 file_linux.go:124] name: /etc/kubernetes/manifests/kube-scheduler.yaml~ eventtype: 0

>I1010 18:50:38.613182   11252 file_linux.go:124] name: /etc/kubernetes/manifests/kube-scheduler.yaml eventtype: 0
I1010 18:50:38.613189   11252 file_linux.go:124] name: /etc/kubernetes/manifests/kube-scheduler.yaml eventtype: 1

>I1010 18:50:38.615952   11252 file_linux.go:124] name: /etc/kubernetes/manifests/kube-scheduler.yaml eventtype: 1
I1010 18:50:38.615960   11252 file_linux.go:124] name: /etc/kubernetes/manifests/kube-scheduler.yaml~ eventtype: 2

This will lead kubelet to delete the old pod and create a new pod

> I1010 14:26:15.943649   20441 kubelet.go:1910] SyncLoop (REMOVE, "file"): "kube-scheduler-gh-hulk-kubemaster-ep-dev02.mt_kube-system(dbe3704b951a6cd2cb3c367fc292f632)"

>I1010 14:26:15.946749   20441 kubelet.go:1900] SyncLoop (ADD, "file"): "kube-scheduler-gh-hulk-kubemaster-ep-dev02.mt_kube-system(dbe3704b951a6cd2cb3c367fc292f632)"

**What you expected to happen**:

opening staticPodPath file with vim will not lead kubelet to create a new pod
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest master branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:VIM - Vi IMproved 7.4

/sig node

**Comment by zouyee** [comment]
Please check if there are temporary files or new files under the directory `/etc/kubernetes/manifests/` after performing `vim` operation.

**Comment by xiaoanyunfei** [comment]
> Please check if there are temporary files or new files under the directory `/etc/kubernetes/manifests/` after performing `vim` operation.

No  temporary files or new files

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/pull/64880

creating a second manifest file containing an identical pod definition in the static pod directory is not recommended

**Comment by liggitt** [comment]
vim creates a temporary file in the directory which the kubelet can observe and (if fast enough) read and process. see https://stackoverflow.com/questions/1636297/how-to-change-the-folder-path-for-swp-files-in-vim for controlling the location where these temporary files are created.

**Comment by liggitt** [comment]
see the kubelet log indicating the temporary file: `/etc/kubernetes/manifests/kube-scheduler.yaml~`

/close
