### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by AnkitLogics** [kubernetes/kubernetes#83719]

**Comment by ZP-AlwaysWin** [comment]
This log is too obscure, there is not much valuable information, you can provide some more logs, or Yaml file is sented.

**Comment by AnkitLogics** [comment]
Project YAML : 

kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: o-trade
  selfLink: /apis/project.openshift.io/v1/projects/o-trade
  uid: 925e2549-ec1f-11e9-9294-060b8c12d11f
  resourceVersion: '48046487'
  creationTimestamp: '2019-10-11T12:06:35Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: o-trade
    openshift.io/requester: metadeepak1
    openshift.io/sa.scc.mcs: 's0:c107,c44'
    openshift.io/sa.scc.supplemental-groups: 1011430000/10000
    openshift.io/sa.scc.uid-range: 1011430000/10000
spec:
  finalizers:
    - kubernetes
status:
  phase: Active

**Comment by AnkitLogics** [comment]
Build POD YAML : 
kind: Pod
apiVersion: v1
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.7.188"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container sti-build; cpu,
      memory limit for container sti-build; cpu, memory request for init
      container git-clone; cpu, memory limit for init container git-clone; cpu,
      memory request for init container manage-dockerfile; cpu, memory limit for
      init container manage-dockerfile
    openshift.io/build.name: wildfly-1
    openshift.io/scc: privileged
  selfLink: /api/v1/namespaces/o-trade/pods/wildfly-1-build
  resourceVersion: '48047349'
  name: wildfly-1-build
  uid: a6a2bd8b-ec1f-11e9-9294-060b8c12d11f
  creationTimestamp: '2019-10-11T12:07:09Z'
  namespace: o-trade
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      kind: Build
      name: wildfly-1
      uid: a22328e4-ec1f-11e9-950d-0a580a8101c6
      controller: true
  labels:
    openshift.io/build.name: wildfly-1
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  initContainers:
    - resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 20m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      name: git-clone
      command:
        - openshift-git-clone
      env:
        - name: BUILD
          value: >
            {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"wildfly-1","namespace":"o-trade","selfLink":"/apis/build.openshift.io/v1/namespaces/o-trade/builds/wildfly-1","uid":"a22328e4-ec1f-11e9-950d-0a580a8101c6","resourceVersion":"48046900","creationTimestamp":"2019-10-11T12:07:01Z","labels":{"app":"wildfly","app.kubernetes.io/component":"wildfly","app.kubernetes.io/instance":"wildfly","app.kubernetes.io/name":"wildfly","app.kubernetes.io/part-of":"wildfly-app","app.openshift.io/runtime":"wildfly","app.openshift.io/runtime-version":"17.0","buildconfig":"wildfly","openshift.io/build-config.name":"wildfly","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"wildfly","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"wildfly","uid":"a16e9f5e-ec1f-11e9-8b5c-0a580a8201e4","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/openshift-jee-sample.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/openshift/wildfly@sha256:5a20dd8d9bfe99d9c192c2385fa55daa929ee488068de4ad0b95d397d3cc46a5"},"pullSecret":{"name":"builder-dockercfg-f794z"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/o-trade/wildfly:latest"},"pushSecret":{"name":"builder-dockercfg-f794z"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Build
            configuration
            change"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/o-trade/wildfly:latest","config":{"kind":"BuildConfig","namespace":"o-trade","name":"wildfly"},"output":{}}}
        - name: LANG
          value: en_US.utf8
        - name: SOURCE_REPOSITORY
          value: 'https://github.com/openshift/openshift-jee-sample.git'
        - name: SOURCE_URI
          value: 'https://github.com/openshift/openshift-jee-sample.git'
        - name: ALLOWED_UIDS
          value: 1-
        - name: DROP_CAPS
          value: 'KILL,MKNOD,SETGID,SETUID'
        - name: BUILD_REGISTRIES_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/registries.conf
        - name: BUILD_REGISTRIES_DIR_PATH
          value: /var/run/configs/openshift.io/build-system/registries.d
        - name: BUILD_SIGNATURE_POLICY_PATH
          value: /var/run/configs/openshift.io/build-system/policy.json
        - name: BUILD_STORAGE_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/storage.conf
        - name: BUILD_BLOBCACHE_DIR
          value: /var/cache/blobs
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: buildworkdir
          mountPath: /tmp/build
        - name: build-system-configs
          readOnly: true
          mountPath: /var/run/configs/openshift.io/build-system
        - name: build-blob-cache
          mountPath: /var/cache/blobs
        - name: builder-token-hbl42
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      args:
        - '--loglevel=0'
    - resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 20m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      name: manage-dockerfile
      command:
        - openshift-manage-dockerfile
      env:
        - name: BUILD
          value: >
            {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"wildfly-1","namespace":"o-trade","selfLink":"/apis/build.openshift.io/v1/namespaces/o-trade/builds/wildfly-1","uid":"a22328e4-ec1f-11e9-950d-0a580a8101c6","resourceVersion":"48046900","creationTimestamp":"2019-10-11T12:07:01Z","labels":{"app":"wildfly","app.kubernetes.io/component":"wildfly","app.kubernetes.io/instance":"wildfly","app.kubernetes.io/name":"wildfly","app.kubernetes.io/part-of":"wildfly-app","app.openshift.io/runtime":"wildfly","app.openshift.io/runtime-version":"17.0","buildconfig":"wildfly","openshift.io/build-config.name":"wildfly","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"wildfly","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"wildfly","uid":"a16e9f5e-ec1f-11e9-8b5c-0a580a8201e4","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/openshift-jee-sample.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/openshift/wildfly@sha256:5a20dd8d9bfe99d9c192c2385fa55daa929ee488068de4ad0b95d397d3cc46a5"},"pullSecret":{"name":"builder-dockercfg-f794z"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/o-trade/wildfly:latest"},"pushSecret":{"name":"builder-dockercfg-f794z"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Build
            configuration
            change"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/o-trade/wildfly:latest","config":{"kind":"BuildConfig","namespace":"o-trade","name":"wildfly"},"output":{}}}
        - name: LANG
          value: en_US.utf8
        - name: SOURCE_REPOSITORY
          value: 'https://github.com/openshift/openshift-jee-sample.git'
        - name: SOURCE_URI
          value: 'https://github.com/openshift/openshift-jee-sample.git'
        - name: ALLOWED_UIDS
          value: 1-
        - name: DROP_CAPS
          value: 'KILL,MKNOD,SETGID,SETUID'
        - name: BUILD_REGISTRIES_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/registries.conf
        - name: BUILD_REGISTRIES_DIR_PATH
          value: /var/run/configs/openshift.io/build-system/registries.d
        - name: BUILD_SIGNATURE_POLICY_PATH
          value: /var/run/configs/openshift.io/build-system/policy.json
        - name: BUILD_STORAGE_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/storage.conf
        - name: BUILD_BLOBCACHE_DIR
          value: /var/cache/blobs
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: buildworkdir
          mountPath: /tmp/build
        - name: build-system-configs
          readOnly: true
          mountPath: /var/run/configs/openshift.io/build-system
        - name: build-blob-cache
          mountPath: /var/cache/blobs
        - name: builder-token-hbl42
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      args:
        - '--loglevel=0'
  serviceAccountName: builder
  imagePullSecrets:
    - name: builder-dockercfg-f794z
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  nodeName: ip-10-0-135-71.us-west-1.compute.internal
  securityContext: {}
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 20m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      name: sti-build
      command:
        - openshift-sti-build
      env:
        - name: BUILD
          value: >
            {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"wildfly-1","namespace":"o-trade","selfLink":"/apis/build.openshift.io/v1/namespaces/o-trade/builds/wildfly-1","uid":"a22328e4-ec1f-11e9-950d-0a580a8101c6","resourceVersion":"48046900","creationTimestamp":"2019-10-11T12:07:01Z","labels":{"app":"wildfly","app.kubernetes.io/component":"wildfly","app.kubernetes.io/instance":"wildfly","app.kubernetes.io/name":"wildfly","app.kubernetes.io/part-of":"wildfly-app","app.openshift.io/runtime":"wildfly","app.openshift.io/runtime-version":"17.0","buildconfig":"wildfly","openshift.io/build-config.name":"wildfly","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"wildfly","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"wildfly","uid":"a16e9f5e-ec1f-11e9-8b5c-0a580a8201e4","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"https://github.com/openshift/openshift-jee-sample.git"}},"strategy":{"type":"Source","sourceStrategy":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/openshift/wildfly@sha256:5a20dd8d9bfe99d9c192c2385fa55daa929ee488068de4ad0b95d397d3cc46a5"},"pullSecret":{"name":"builder-dockercfg-f794z"}}},"output":{"to":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/o-trade/wildfly:latest"},"pushSecret":{"name":"builder-dockercfg-f794z"}},"resources":{},"postCommit":{},"nodeSelector":null,"triggeredBy":[{"message":"Build
            configuration
            change"}]},"status":{"phase":"New","outputDockerImageReference":"image-registry.openshift-image-registry.svc:5000/o-trade/wildfly:latest","config":{"kind":"BuildConfig","namespace":"o-trade","name":"wildfly"},"output":{}}}
        - name: LANG
          value: en_US.utf8
        - name: SOURCE_REPOSITORY
          value: 'https://github.com/openshift/openshift-jee-sample.git'
        - name: SOURCE_URI
          value: 'https://github.com/openshift/openshift-jee-sample.git'
        - name: ALLOWED_UIDS
          value: 1-
        - name: DROP_CAPS
          value: 'KILL,MKNOD,SETGID,SETUID'
        - name: PUSH_DOCKERCFG_PATH
          value: /var/run/secrets/openshift.io/push
        - name: PULL_DOCKERCFG_PATH
          value: /var/run/secrets/openshift.io/pull
        - name: BUILD_REGISTRIES_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/registries.conf
        - name: BUILD_REGISTRIES_DIR_PATH
          value: /var/run/configs/openshift.io/build-system/registries.d
        - name: BUILD_SIGNATURE_POLICY_PATH
          value: /var/run/configs/openshift.io/build-system/policy.json
        - name: BUILD_STORAGE_CONF_PATH
          value: /var/run/configs/openshift.io/build-system/storage.conf
        - name: BUILD_STORAGE_DRIVER
          value: overlay
        - name: BUILD_ISOLATION
          value: chroot
        - name: BUILD_BLOBCACHE_DIR
          value: /var/cache/blobs
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
      securityContext:
        privileged: true
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: buildworkdir
          mountPath: /tmp/build
        - name: buildcachedir
          mountPath: /var/lib/containers/cache
        - name: builder-dockercfg-f794z-push
          readOnly: true
          mountPath: /var/run/secrets/openshift.io/push
        - name: builder-dockercfg-f794z-pull
          readOnly: true
          mountPath: /var/run/secrets/openshift.io/pull
        - name: build-system-configs
          readOnly: true
          mountPath: /var/run/configs/openshift.io/build-system
        - name: build-ca-bundles
          mountPath: /var/run/configs/openshift.io/certs
        - name: build-proxy-ca-bundles
          mountPath: /etc/pki/ca-trust/extracted/pem
        - name: container-storage-root
          mountPath: /var/lib/containers/storage
        - name: build-blob-cache
          mountPath: /var/cache/blobs
        - name: builder-token-hbl42
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: FallbackToLogsOnError
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      args:
        - '--loglevel=0'
  serviceAccount: builder
  volumes:
    - name: buildcachedir
      hostPath:
        path: /var/lib/containers/cache
        type: ''
    - name: buildworkdir
      emptyDir: {}
    - name: builder-dockercfg-f794z-push
      secret:
        secretName: builder-dockercfg-f794z
        defaultMode: 384
    - name: builder-dockercfg-f794z-pull
      secret:
        secretName: builder-dockercfg-f794z
        defaultMode: 384
    - name: build-system-configs
      configMap:
        name: wildfly-1-sys-config
        defaultMode: 420
    - name: build-ca-bundles
      configMap:
        name: wildfly-1-ca
        items:
          - key: service-ca.crt
            path: 'certs.d/image-registry.openshift-image-registry.svc:5000/ca.crt'
        defaultMode: 420
    - name: build-proxy-ca-bundles
      configMap:
        name: wildfly-1-global-ca
        items:
          - key: ca-bundle.crt
            path: tls-ca-bundle.pem
        defaultMode: 420
    - name: container-storage-root
      emptyDir: {}
    - name: build-blob-cache
      emptyDir: {}
    - name: builder-token-hbl42
      secret:
        secretName: builder-token-hbl42
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2019-10-11T12:07:27Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2019-10-11T12:07:28Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2019-10-11T12:07:28Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2019-10-11T12:07:09Z'
  hostIP: 10.0.135.71
  podIP: 10.129.7.188
  startTime: '2019-10-11T12:07:09Z'
  initContainerStatuses:
    - name: git-clone
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2019-10-11T12:07:17Z'
          finishedAt: '2019-10-11T12:07:25Z'
          containerID: >-
            cri-o://3f0543d096ca27c5d7ce5c01d1f74f6ab0a67177ac5508bd9e42d0c538b547ca
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      imageID: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      containerID: 'cri-o://3f0543d096ca27c5d7ce5c01d1f74f6ab0a67177ac5508bd9e42d0c538b547ca'
    - name: manage-dockerfile
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2019-10-11T12:07:26Z'
          finishedAt: '2019-10-11T12:07:26Z'
          containerID: >-
            cri-o://b448847a1f12c5846a44c70b31b5a3011ce90947857d6f8bf9f8e4d2e168d4e9
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      imageID: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      containerID: 'cri-o://b448847a1f12c5846a44c70b31b5a3011ce90947857d6f8bf9f8e4d2e168d4e9'
  containerStatuses:
    - name: sti-build
      state:
        running:
          startedAt: '2019-10-11T12:07:27Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      imageID: >-
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a04e624211b9327eacde8f89792cb0b735d472a99b137368c5d3e818bc550d5
      containerID: 'cri-o://15b1de7822f663e2d3f5e789a765a33118d872ceb3b72d3bfe45fe097cd8f893'
  qosClass: Burstable

**Comment by AnkitLogics** [comment]
I am using git repo : https://github.com/openshift/openshift-jee-sample.git

**Comment by AnkitLogics** [comment]
Hi @ZP-AlwaysWin 
 I have added all YAML files,kindly check
