### ISSUE TITLE
kubelet cannot complete a Pod due to ApiServer "Forbidden: may not be transitioned to non-terminated state"

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/kubernetes#83725]
**What happened**:
For detail, please check: https://github.com/kubernetes/kubernetes/issues/83705#issuecomment-540534187

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`on-premise
`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```
- Kernel (e.g. `uname -a`):
`Linux stcal-177 4.15.0-1060-azure #65-Ubuntu SMP Wed Sep 18 08:55:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yqwang-ms** [comment]
/sig node
Because it may be caused by https://github.com/kubernetes/kubernetes/issues/83705

**Comment by liggitt** [comment]
possibly related: https://github.com/kubernetes/kubernetes/pull/77870

**Comment by yqwang-ms** [comment]
/remove-lifecycle stale
Any update for this?

**Comment by adisky** [comment]
@yqwang-ms Please free to reopen with more information, like how to reproduce and kubelet logs.
closing this for now as the related issue is closed.

/kind support
/close

**Comment by yqwang-ms** [comment]
/open
@adisky 
Actually this issue is only related to https://github.com/kubernetes/kubernetes/issues/83705, but they are not the same.
After k8s "at least once" is confirmed in https://github.com/kubernetes/kubernetes/issues/83705#issuecomment-590106808, my last question in the below snapshot is still unresolved:
![image](https://user-images.githubusercontent.com/32826762/123400709-a1415e00-d5d8-11eb-9221-01cd337b38fc.png)

And this is the reason to open this issue, I guess kubelet may not handle the "at least once" container well in some corner cases, such as previous container become terminated state, but after kubelet restarted, it created another container with the same id, so kubelet will report error in this issue "Forbidden: may not be transitioned to non-terminated state".

For logs, pls check this https://github.com/kubernetes/kubernetes/issues/83705#issuecomment-540534187

And this issue is to help kubelet to fix such corner cases.
