### ISSUE TITLE
k8s.io/client-go/tools/cache/Reflector's paging is duplicated

### ISSUE THREAD

**Issue by matte21** [kubernetes/kubernetes#83732]
**What happened**:
I was studying the code in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/tools/cache and noticed that the paginated list reflectors do against the API server to initially populate informer's caches is doubly paginated. In fact, the reflector manually performs pagination: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L206-L216 . Notice how the page function of the reflector's paginator invokes the list function of the reflector's ListerWatcher: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L209 . That ListerWatcher is of type https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/listwatch.go#L58 ; its list function (the one invoked by the reflector's paginator paging function) in turn uses paging: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/listwatch.go#L106 . The  result is that reflectors use double pagination: they use a paging function that in turn uses paging. This seems to me very odd and undesirable.

**What you expected to happen**:
I expected reflector's list to be paginated only once.

**How to reproduce it (as minimally and precisely as possible)**:
I assume there's a way to verify the issue by examining any running Kubernetes controller with no additional modifications, but I don't know how to do that, so I took a different approach.

[Here](https://github.com/matte21/sample-controller/tree/print-pager-stack-trace) you can find a fork of https://github.com/kubernetes/sample-controller that has been modified as follows:

1) Dependencies are vendored; `vendor` is included in the github repo.
2) The vendored dependency k8s.io/client-go/tools/cache has been modified by inserting a print of the stack trace in the paging function of the pager created by the ListerWatcher (not the one created by the reflector).
3) A Dockerfile, a Makefile and a few YAML manifests have been included to build and deploy the sample controller modified with a print of the stack trace in the logs.
   
You can deploy the modified controller with the appropriate Makefile target in the repo https://github.com/matte21/sample-controller/tree/print-pager-stack-trace ; if you examine the controller logs you should see the stack trace print and notice that double-paging is performed. I did that, here's the stack trace:
```
 1: goroutine 13 [running]:
 2: runtime/debug.Stack(0x0, 0x0, 0x0)
 3:		/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
 4: runtime/debug.PrintStack()
 5: 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
 6: k8s.io/client-go/tools/cache.(*ListWatch).List.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x140efa7, ...)
 7:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/cache/listwatch.go:108 +0x40
 8: k8s.io/client-go/tools/pager.SimplePageFunc.func1(0x1626fa0, 0xc00009c210, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
 9:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/pager/pager.go:40 +0x64
10: k8s.io/client-go/tools/pager.(*ListPager).List(0xc0000a0bc0, 0x1626fa0, 0xc00009c210, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
11:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/pager/pager.go:88 +0x12d
12: k8s.io/client-go/tools/cache.(*ListWatch).List(0xc0002cbc80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
13:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/cache/listwatch.go:111 +0x124
14: k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1.1.2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x140efa7, ...)
15:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/cache/reflector.go:209 +0x72
16: k8s.io/client-go/tools/pager.SimplePageFunc.func1(0x1626fa0, 0xc00009c208, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
17:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/pager/pager.go:40 +0x64
18: k8s.io/client-go/tools/pager.(*ListPager).List(0xc0000a0f10, 0x1626fa0, 0xc00009c208, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
19:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/pager/pager.go:88 +0x12d
20: k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1.1(0xc00007c5a0, 0xc00003c630, 0xc00033a180, 0xc00003a160, 0xc00003a170, 0xc000334300)
21:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/cache/reflector.go:215 +0x190
22: created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1
23:		/Users/matteo/debug-double-paging/sample-controller/vendor/k8s.io/client-go/tools/cache/reflector.go:200 +0x29d
```

Notice how a paging function at https://github.com/kubernetes/client-go/blob/master/tools/pager/pager.go#L88 gets called first at line 19 (this is the reflector's pager, the topmost one) and then again at line 11 (this is the ListerWatcher's pager, the innermost one) .

**Anything else we need to know?**:
I'll open a PR to remove paging from the reflector and keep it only in the ListerWatcher; IMO whether paging is used is a detail of how the LIST is performed which fits better in the ListerWatcher than the reflector. Notice that currently actual pagination is not done because the reflector [uses a watch cache](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L188-L191) and pagination from a watch cache is not supported. That fact, however, is orthogonal to this issue.

Edit: fixed a typo.

**Comment by liggitt** [comment]
cc @jpbetz

**Comment by jpbetz** [comment]
There is a complication with a semantic difference between how paginated and unpaginated lists are executed that matters for the stale read issue we are trying to fix.  I’m mobile but will explain in detail shortly.  Let’s hold off on removing the pager from the reflector until we discuss.

**Comment by jpbetz** [comment]
https://github.com/kubernetes/kubernetes/pull/83520 will transition reflectors from using resourceVersion="0" to using either resourceVersion="" or resourceVersion="{non-zero resourceVersion}" to prevent reflectors from "going back in time. This change should be correct regardless of if the reflector does pagination directly.

**Comment by jpbetz** [comment]
> The result is that reflectors use double pagination: they use a paging function that in turn uses paging. This seems to me very odd and undesirable.

This might not be as bad as it looks at first glance. What will happen here is that a limit will be set on the options passed from the outer pager to the inner. If the inner page returns a response without a continue, the outer pager will know it got a full response and will not do any paging.

If we did decide remove the pager in the reflector, we need to be very careful to understand the impact of all reflectors. For example, the watch cache configures it's reflector with a large page size, and the lister watcher used there would need to be updated do to the paging with that page size instead. I expect it's quite a bit of work to sort this all out.

**Comment by jpbetz** [comment]
FWIW, I'm in favor of keeping the paging in the reflector. It basically says we want paging from reflectors regardless of how the ListerWatcher is implemented, and I don't see anything wrong with that. Interested in what others think.

**Comment by tedyu** [comment]
```
paging from reflectors regardless of how the ListerWatcher is implemented
```
That's my understanding as well

**Comment by matte21** [comment]
Broadly speaking, the reflector's task is making sure that informer's caches eventually reflect the API server's content (i.e. etcd's). To that end, it issues a LIST and a WATCH, and for each object it receives it creates a delta and adds it to the deltaFIFO. On the basis of what's written above, it seems to me that the mechanics of how and whether to set up paging are a "low-level" implementation detail of how LISTs are done, hence pager set up should be done by ListerWatchers rather than reflectors; in fact, currently the reflector processes LIST results as a whole object as opposed to one chunk at a time. For these reasons I have a slight preference for confining chunking to ListerWatchers as opposed to reflectors, but by all means let's go with the latter if that's the consensus; also, even if we did confine paging to ListerWatchers some bits of pagination might still leak to clients of the ListerWatchers (e.g. setting a custom page size). And yes, as [this comment](https://github.com/kubernetes/kubernetes/issues/83732#issuecomment-540766316) points out, the fact that currently paging is done twice has no impact correctness-wise. I still think that it's unneeded and illogical and that it should be removed; also, it might provide clarity in the future to have a general guideline on whether paging (if needed) should be hidden in ListerWatchers or added on top of them by clients.

**Comment by matte21** [comment]
> If we did decide remove the pager in the reflector, we need to be very careful to understand the impact of all reflectors. For example, the watch cache configures it's reflector with a large page size, and the lister watcher used there would need to be updated do to the paging with that page size instead. I expect it's quite a bit of work to sort this all out.

@jpbetz [this](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiserver/pkg/storage/cacher) is the package you're referring to, right? Is it the only other place which would be affected? If so, one simple way of dealing with it would be the following:
1. Add a `PageSize` field to [cacherListerWatcher](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L1031); the cacher sets it (or passes the value through a constructor argument) as opposed to [setting the reflector's ListWatchPageSize field](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L380).
2. The cacherListerWatcher's List function does what the reflector currently does, i.e., sets up a pager whose page function invokes the actual list function and calls List on such pager. The actual list function is an unexported/anonymous function which does exactly what the current [cacherListerWatcher's List](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L1047) function does.

**Comment by matte21** [comment]
cc @MikeSpreitzer

**Comment by jpbetz** [comment]
I don’t feel strongly about this. If consensus is that we should simplify to pagination in listerWatchers and someone wants to own making sure we find all usages where we don’t already have pagination in the listerWatcher and get those updated, and sort out the impact to external codebases arhat import reflectors, I’d be happy to review.
