### ISSUE TITLE
Statefulset controller supports to update pods parallelly

### ISSUE THREAD

**Issue by yuyulei** [kubernetes/kubernetes#83733]
**What would you like to be added**:
Now Statefulset PodManagementPolicy [detail](https://github.com/kubernetes/kubernetes/blob/4fb75e2f0d9a36c47edcf65f89bb92f20274ee56/pkg/apis/apps/types.go#L50) only defines the policy creating/deleting pods. I hope we can expand the policy, it also can be the policy for updating pods. 

If PodManagementPolicy is "OrderedReady", meaning update pod one by one.

If PodManagementPolicy is "Parallel", meaning updata pod parallelly.

such as [code](https://github.com/kubernetes/kubernetes/blob/4fb75e2f0d9a36c47edcf65f89bb92f20274ee56/pkg/controller/statefulset/stateful_set_control.go#L506) modified like:

```
	for target := len(replicas) - 1; target >= updateMin; target-- {

		// delete the Pod if it is not already terminating and does not match the update revision.
		if getPodRevision(replicas[target]) != updateRevision.Name && !isTerminating(replicas[target]) {
			glog.V(2).Infof("StatefulSet %s/%s terminating Pod %s for update",
				set.Namespace,
				set.Name,
				replicas[target].Name)
			if err := ssc.podControl.DeleteStatefulPod(set, replicas[target]); err != nil {
				return &status, err
			}
			status.CurrentReplicas--
			if monotonic {
				return &status, nil
			}
			continue
		}

		// wait for unhealthy Pods on update
		if !isHealthy(replicas[target]) && monotonic {
			glog.V(4).Infof(
				"StatefulSet %s/%s is waiting for Pod %s to update",
				set.Namespace,
				set.Name,
				replicas[target].Name)
			return &status, nil
		}
	}
```

**Why is this needed**:
In our prod env, statefulset's replicas is >=100, every updating operation will cost hours. We can set `rollingUpdate.partition` to control the schedule of updating, we can accept once updating parallelly.

Maybe it's better for users to choose updating policy, such as one by one or parallelly, just like the policy of creating/deleting pod one by one or parallelly.

In my opinion, "PodManagermentPolicy" can cover the policy of updating pods literally, no need add another field, like "PodUpdatePolicy" to do this.

**Comment by yuyulei** [comment]
cc @kow3ns @smarterclayton @janetkuo

**Comment by yuyulei** [comment]
PTAL @kow3ns @janetkuo @smarterclayton

**Comment by yuyulei** [comment]
PTAL @kow3ns @janetkuo @smarterclayton

**Comment by smarterclayton** [comment]
Unfortunately to maintain forward compatibility, we would not be able to change the behavior of update.  Instead, we always have to add a new field or enumeration.  Update behavior is also expected to be controlled by the update strategy, so this would not be an appropriate way to proceed.

If you would like to propose improving the update strategy with a policy, let's open a new issue and then we can open a PR to discuss such a change.

/close
