### ISSUE TITLE
tests: Windows packet fragmentation issue

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#83739]
**Which jobs are failing**:

sig-windows#flannel-overlay-windows-master

**Which test(s) are failing**:

    [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should deny crd creation [Conformance]

**Since when has it been failing**:

Unknown.

**Testgrid link**:

https://testgrid.k8s.io/sig-windows#flannel-overlay-windows-master

**Reason for failure**:

There seems to be an issue regarding packet fragmentation on Windows that occurs especially when using flannel vxlan. This can also be reproduced manually:

    kubectl create namespace ns1
    kubectl create -f pods/agnhost_linux.yaml -n ns1  # https://paste.ubuntu.com/p/wqhvmpx9S7/
    kubectl create -f pods/agnhost_windows.yaml -n ns1  # https://paste.ubuntu.com/p/YrbpwtqBdM/
    kubectl create -f pods/services.yaml -n ns1  # https://paste.ubuntu.com/p/wTxnSTws4P/

    # wait for the pods to spawn...
    sleep 10

    sudo apt install jq
    linux_pod_ip=`kubectl get -o json -n ns1 pod/linux-agnhost | jq '.status.podIP' | sed 's/"//g'`
    linux_host_ip=`kubectl get -o json -n ns1 pod/linux-agnhost | jq '.status.hostIP' | sed 's/"//g'`
    windows_pod_ip=`kubectl get -o json -n ns1 pod/windows-agnhost | jq '.status.podIP' | sed 's/"//g'`
    windows_host_ip=`kubectl get -o json -n ns1 pod/windows-agnhost | jq '.status.hostIP' | sed 's/"//g'`
    cluster_ip=`kubectl get -o json -n ns1 service/node-port-service | jq '.spec.clusterIP' | sed 's/"//g'`

    # check the MTU in the containers: it should be 1450 when using flannel vxlan, and 1500 when using flannel l2bridge.
    kubectl exec -n ns1 windows-agnhost -- netsh int ipv4 show subint
    kubectl exec -n ns1 linux-agnhost -- ifconfig

    # the following pings work
    ping -c 3 $windows_pod_ip
    ping -c 3 -s 1342 $windows_pod_ip
    # the following pings work in l2bridge, but not in vxlan.
    ping -c 3 -s 1344 $windows_pod_ip
    ping -c 3 -s 1400 $windows_pod_ip
    ping -c 3 -s 1600 $windows_pod_ip

    # the following pings work
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 $linux_pod_ip
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1342 $linux_pod_ip
    # the following pings work in l2bridge, but not in vxlan.
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1344 $linux_pod_ip
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1400 $linux_pod_ip
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1600 $linux_pod_ip

    # the following pings work
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 $windows_host_ip
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1422 $windows_host_ip
    # the following pings should work, but do not.
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1424 $windows_host_ip
    kubectl exec -n ns1 windows-agnhost -- ping -n 3 -l 1600 $windows_host_ip

    # the following ping works
    kubectl exec -n ns1 linux-agnhost -- ping -c 3 -s 1900 $linux_host_ip

    # msg to be used in the tests below
    msg=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 1900 | head -n 1)

    # for UDP, the following command should work
    kubectl exec -n ns1 windows-agnhost -- curl.exe -s "http://127.0.0.1:8080/dial?host=$linux_pod_ip&port=8081&protocol=udp&request=echo%20hi"
    # when the message is larger, it won't work anymore in azure-vnet-cni v1.0.27.
    kubectl exec -n ns1 windows-agnhost -- curl.exe -s "http://127.0.0.1:8080/dial?host=$linux_pod_ip&port=8081&protocol=udp&request=echo%20$msg"

    # for flannel l2bridge, this does not work
    kubectl exec -n ns1 windows-agnhost -- curl.exe -s "http://127.0.0.1:8080/dial?host=$cluster_ip&port=90&protocol=udp&request=echo%20$msg"
    # but if the message is shorter, it works:
    kubectl exec -n ns1 windows-agnhost -- curl.exe -s "http://127.0.0.1:8080/dial?host=$cluster_ip&port=90&protocol=udp&request=echo%20hi"

The mentioned test fails because ``kube-apiserver`` will send a 1400+ bytes packet to the pod which should deny the crd creation (which is higher than the 1342 bytes limit observed), and it never gets any reply.

This issue does not occur when using flannel l2bridge, the test passes, as seen here: https://testgrid.k8s.io/sig-windows#containerd-l2bridge-windows-master

**Anything else we need to know**:

We've sent a PR which adds 2 E2E tests that sends larger HTTP / UDP packets in order to detect and check for this issue: https://github.com/kubernetes/kubernetes/pull/83680 .

As expected, the tests fail when using Windows nodes with flannel vxlan. The HTTP test passes when using Windows nodes with azure CNI, or flannel l2bridge, however the UDP test does not, which may indicate a different issue. Both the HTTP and the UDP tests pass when using Linux nodes / pods with azure CNI, flannel l2bridge, or flannel overlay.

/sig windows

**Comment by adelina-t** [comment]
/remove-lifecycle stale

This issue is still affecting K8s on Windows. It is being looked at.

**Comment by marosset** [comment]
/close
This issue was fixed by a recent Windows OS bugfix.
No further action is needed.
