### ISSUE TITLE
Question: Link containers and networking

### ISSUE THREAD

**Issue by razgon** [kubernetes/kubernetes#8375]
Hi,

I was very exited on deploying and starting using Kubernetes Cluster, but I've a couple of questions that I need to understand. Could someone please help with them?
1) Traffic routing. Right now we did setup Docker services managed by Kubernetes to work over flannel. There is an additional host with docker and flannel, that we are using as a gateway to route all traffic from external network to flannel-docker IP space. So far it works fine. Is this correct way, or shoul we do it differently with some proxy?
2) Pods, Services. Our app consists of 3 pieces Postgres, dynamodb and tomcat. We want to use Kubernetes cluster as automation framework and be able to run different versions of all this subsets in a cluster. Did I understood correct, that running Postgres and Dynamobd as a service will create a new container each time I will create a new application pod? Problem is that application pods will need to change Postgres schema after start, so each application will have a unique schema.

Thanks!

**Comment by razgon** [comment]
One more
3) SkyDNS. Is it possible to setup this guy to assigne IPs from flannel subnet instead of internal service IPs to FQDN? Can I forward my corp DNS to SkyDNS so it will start resolving names into flannel IPs?

**Comment by bprashanth** [comment]
@razgon I would suggest an email to https://groups.google.com/forum/#!forum/google-containers

**Comment by thockin** [comment]
On Sat, May 16, 2015 at 5:52 AM, Avanes Akapyan
<notifications@github.com> wrote:
>
> Hi,
>
> I was very exited on deploying and starting using Kubernetes Cluster, but I've a couple of questions that I need to understand. Could someone please help with them?
> 1) Traffic routing. Right now we did setup Docker services managed by Kubernetes to work over flannel. There is an additional host with docker and flannel, that we are using as a gateway to route all traffic from external network to flannel-docker IP space. So far it works fine. Is this correct way, or shoul we do it differently with some proxy?

I think something like this is required for machines outside the
fabric to bridge into the fabric.

> 2) Pods, Services. Our app consists of 3 pieces Postgres, dynamodb and tomcat. We want to use Kubernetes cluster as automation framework and be able to run different versions of all this subsets in a cluster. Did I understood correct, that running Postgres and Dynamobd as a service will create a new container each time I will create a new application pod? Problem is that application pods will need to change Postgres schema after start, so each application will have a unique schema.

I'm not sure I understand this question - can you maybe re-state it?

> 3) SkyDNS. Is it possible to setup this guy to assigne IPs from flannel subnet instead of internal service IPs to FQDN? Can I forward my corp DNS to SkyDNS so it will start resolving names into flannel IPs?

Our DNS only serves Service IPs, which are virtual.  There's no way to
allocate them in the flannel space.

**Comment by razgon** [comment]
@thockin, thank you very much for your answers!
Let me clarify the second question. Use case is to use Kubernetes cluster to be able to deploy same subset of linked containers running absolutely same os services and same applications. There is no container link in Pods and we have to deploy Kubernetes Services. Question is: Each time I will be deploying new Pod(Tomcat) and point it to Service(Postgres), will Kubernetes deploy new Container for each new Pod(Tomcat). Or I have to Deploy new Service each time for each new Pod(Tomcat).
Previous we were deploying same subset of linked containers on different ports.

BTW It will be very good to have DNS that we can forward company DNS to and Pod names will be resolved into container (flannel) IPs. Right now I will bring up bind on Master and reload it's table each time Pod will be created/deleted.

**Comment by thockin** [comment]
On Wed, May 20, 2015 at 9:25 AM, Avanes Akapyan
<notifications@github.com> wrote:
>
> Let me clarify the second question. Use case is to use Kubernetes cluster to be able to deploy same subset of linked containers running absolutely same os services and same applications. There is no container link in Pods and we have to deploy Kubernetes Services. Question is: Each time I will be deploying new Pod(Tomcat) and point it to Service(Postgres), will Kubernetes deploy new Container for each new Pod(Tomcat). Or I have to Deploy new Service each time for each new Pod(Tomcat).

I'm still not clear what  you mean, sorry.  Let me have a stab, and
you can tell me if I an getting close to what you need.

When you deploy a pod (e.g. kubectl create) you get a new instance of
that pod, which includes a new instance of every container in that
pod.  When those pods want to consume a service that exists in the
cluster, they can simply connect by name or IP.  If you want to have
multiple different Postgres instances with different schemas, you will
need to create different postgres services, which are backed by
different postgres pods.  That will give each Service instance a
different name and IP.

For example:

* deploy a pod named "postgres1" with label app=pg1
* deploy a service named "postgres1" with a selector app=pg1
* deploy a client pod that connects to DNS name "postgres1"

* deploy a pod named "postgres2" with label app=pg2
* deploy a service named "postgres2" with a selector app=pg2
* deploy a client pod that connects to DNS name "postgres2"

If you want to use the same name for all of them, you can create
Namespaces for each app:

* create a namespace named "pg1"
* deploy a pod named "postgres" in pg1 with label app=pg
* deploy a service named "postgres" in pg1 with a selector app=pg
* deploy a client pod in pg1 that connects to DNS name "postgres"

* create a namespace named "pg2"
* deploy a pod named "postgres" in pg2 with label app=pg
* deploy a service named "postgres" in pg2 with a selector app=pg
* deploy a client pod in pg2 that connects to DNS name "postgres"

> Previous we were deploying same subset of linked containers on different ports.
>
> BTW It will be very good to have DNS that we can forward company DNS to and Pod names will be resolved into container (flannel) IPs. Right now I will bring up bind on Master and reload it's table each time Pod will be created/deleted.

Yeah, it's an interesting problem that we just don't have implemented yet

**Comment by razgon** [comment]
@thockin,
what I was expecting is to deploy 1 Pod with 2 containers, where Application container is linked to Postgres container by doing 1 Rest API call. In my scenario it would be much easier to manage 1 Entity (Pod) instead of 3 entities.

Thank you very much for all answers. As for now we will go with burrito-container approach where all services and application are deployed in same container.
