### ISSUE TITLE
Failed test: ci-kubernetes-e2e-gce-scale-performance #1182340570157158400

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#83768]
**Which jobs are failing**: ci-kubernetes-e2e-gce-scale-performance #1182340570157158400

**Which test(s) are failing**:  ClusterLoaderV2

**Since when has it been failing**: 2019-10-10 (1 run)

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance

**Reason for failure**:

There were some internal errors when creating MIGs:
```
W1010 17:11:03.768] ERROR: (gcloud.compute.instance-groups.managed.wait-until-stable) Some requests did not succeed:
W1010 17:11:03.768]  - Internal error. Please try again or contact Google Support. (Code: '594917C803581.A6A92C6.FC0E6929')
```

Most likely due to that one node didn't go up:

```
W1010 17:43:10.388] I1010 17:43:10.387995   15126 cluster.go:108] Condition Ready of node gce-scale-cluster-minion-group-2-tgs5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
```

Then CL2 failed when setting up prometheus stack because of missing kube-proxy endpoint on that node
```
W1010 17:58:21.621] I1010 17:58:21.621088   15126 util.go:88] 5320/5321 targets are ready, example not ready target: {map[endpoint:http-metrics instance:10.40.9.202:10249 job:kube-proxy namespace:kube-system pod:kube-proxy-gce-scale-cluster-minion-group-2-tgs5 service:kube-proxy] down}
W1010 17:58:21.734] F1010 17:58:21.724609   15126 clusterloader.go:247] Error while setting up prometheus stack: timed out waiting for the condition
```

/sig scalability

**Comment by hasheddan** [comment]
@mm4tt looks like this has seen an uptick in failures in the last couple of days. Do you think we should move forward with a resolution?
ref:https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-performance
cc @alenkacz @droslean @Verolop @epk

**Comment by mm4tt** [comment]
The recent failures were due to https://github.com/kubernetes/kubernetes/issues/84151
The issue described in this bug hasn't reoccurred. I think we can close this issue it was a one-off thing.
/close

**Comment by hasheddan** [comment]
@mm4tt sounds good, thanks!
