### ISSUE TITLE
checksum mismatch for github.com/coreos/etcd@v3.3.16+incompatible

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#83761]
The publishing bot is broken right now (https://github.com/kubernetes/kubernetes/issues/56876) because of a checksum mismatch while running `go mod download`:

```
verifying github.com/coreos/etcd@v3.3.16+incompatible: checksum mismatch
	downloaded: h1:2eX1BjV6Wfvl41/35OBA5Np4BHezdTJzhIxSMYxOArA=
	go.sum:     h1:hQaR//OAeI1FQ3G5bGRL9VpFOCurqnEHSup4W693Tb4=
```

I also get this error locally while running `go mod download` on k/k.

etcd was updated to 3.3.16 in https://github.com/kubernetes/kubernetes/pull/83735.

From a quick glance, I'm not completely sure what the problem is since the CI was green for the PR, but I noticed that the PR was created ~2:50pm UTC while the tag https://github.com/etcd-io/etcd/releases/tag/v3.3.16 was created around 6pm UTC.

@jpbetz Was the tag deleted and re-pushed by any chance?

We should look into this before cherry-picking it to 1.16.x (https://github.com/kubernetes/kubernetes/pull/83712#issuecomment-540544567).

/cc @dims @liggitt @cblecker @sttts @gyuho 
/sig architecture
/area code-organization

**Comment by jpbetz** [comment]
There was an issue with the release and we had to retag it (https://github.com/etcd-io/etcd/issues/11230).

**Comment by nikhita** [comment]
/assign

I'll send a PR shortly
