### ISSUE TITLE
Why the memory limit  call the node down

### ISSUE THREAD

**Issue by kengan** [kubernetes/kubernetes#83767]
I have deploy a java application in a pod, I set the memory limit is 8G. But the application use much memory than 8G and call the node down.

**Comment by xichengliudui** [comment]
Please tell us the steps.

**Comment by kengan** [comment]
/sig/community/question

I deploy a Java  application in a pod
This application open 10 thread to receive message from rock-mq. After receiving message from mq, each thread down a pdf file in pod  and use Apache tike to analyze the content.
I deploy 32 pods, each pod set limit of 8G memory and 5 cpu.  
I found that when the application useed up 8G memory the pod was restarted. After many times restarting, the node which the pod located in also down.

**Comment by kengan** [comment]
sig /community/question

**Comment by kengan** [comment]
I deploy a Java applicatioin in k8s
This java application open 10 thread to receive message from RockMq. After receiveing message, each thread down a pdf file and analyze the content with apache tike
I deploy 32 pod, each pod set limit 8G memory and  5Cpu
After using up 8 G memory , the pod auto restart. After many time restarting, the node which the pod  at also down. I want to know why the pod restarting can affect the node

**Comment by ipuustin** [comment]
Would it be possible that OOM killer is terminating system processes, causing the host be rebooted? Your system log might have some information about this (see what has triggered OOM killer and which processes it has considered to terminate).

**Comment by kengan** [comment]
I have see my system log , I found that when the pod used up the memory, kubelet try to restart the docker, but the docker can not be restarted. The kubelet keep trying and finally the kubelet is down.
I want to know why the restarting cause the kubelet down.? Thank you
