### ISSUE TITLE
Kubernetes v1.13.11 CustomResourceDefinition deletionTimestamp is updated on each DELETE request

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#83771]
**What happened**:
With Kubernetes v1.13.x CustomResourceDefinition `deletionTimestamp` is updated to time.Now() on each delete request.

**What you expected to happen**:
I would expected the `deletionTimestamp` to be set to the time.Now() of the first delete request and subsequent delete requests to do not modify `.metadata.deletionTimestamp`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a v1.13.11 cluster.
I used minikube:
```bash
$ minikube start --profile foo --kubernetes-version "v1.13.11"
```

2. Apply CRD
```
$ cat crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
            image:
              type: string
            replicas:
              type: integer


$ k apply -f crd.yaml
```

3. Create an instance of this CRD and put a finalizer on it.
```
$ cat crontab.yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image

$ k apply -f crontab.yaml
$ k edit crontab # put a finalizer to block deletion
```

4. Delete the CRD
```
$ k delete crd crontabs.stable.example.com
customresourcedefinition.apiextensions.k8s.io "crontabs.stable.example.com" delete
```

Check that the deletionTimestamp is `deletionTimestamp: "2019-10-11T10:25:46Z"`.
Delete the CRD again. Check that the deletionTimestamp is updated and set to `deletionTimestamp: "2019-10-11T10:26:28Z"`.

**Anything else we need to know?**:
This issue occurs in v1.13.11. I tested the same steps with v1.14 and the deletionTimestamp was not being updated.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.11
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: minikube
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yue9944882** [comment]
/remove-area custom-resources

cant reproduce on master branch, probably already fixed. and on v1.13.1, the issue applies to all graceful-deleting resources..

**Comment by yue9944882** [comment]
it's fixed by #73138

**Comment by ialidzhikov** [comment]
Yep, for versions < v1.14 the `deletionTimestamp` is updated on each delete request.
Thank you @yue9944882 for digging in and finding the appropriate issue.

**Comment by liggitt** [comment]
Thanks for the report. This is a duplicate of https://github.com/kubernetes/kubernetes/issues/73098

/close
