### ISSUE TITLE
Merging unreserve plugin into reserve plugin of scheduling framework

### ISSUE THREAD

**Issue by mrkm4ntr** [kubernetes/kubernetes#83788]
**What would you like to be changed**:
Merge `UnreservePlugin` into `ReservePlugin`. Make `ReservePlugin` have `Reserve` and `Unreserve` methods.

**Why is this needed**:
In the current implementation, if one of reserve plugins fails, the plugins already reserved will not be unreserved.  I tried to fix this in #83557.
There are 2 options to solve this problem.
1. Call all unreserve plugins when some reserve plugin fails.
2. Call only unreserve plugins that correspond to already reserved ones.

My PR chose option 2.  I would not like developer to take care that  an unreserve plugin is sometimes called without calling the corresponding reserve. But how to represent which unreserve plugin corresponds to reserve plugin is only implementing them into one plugin. Then, I think it is simple and natural to merge reserve and unreserve plugins. In the current interface, it is possible to implement corresponding reserve and unreserve in different plugins (most developers won't do it, but it is better to prevent it by the interface).

/sig scheduling

**Comment by cofyc** [comment]
or skip if the plugin does not implement the Unreserve interface? we can assume the plugin does not need to unreserve if it does not implement it.

**Comment by hex108** [comment]
> or skip if the plugin does not implement the Unreserve interface? 

Yes, it could be an option.

**Comment by mrkm4ntr** [comment]
> or skip if the plugin does not implement the Unreserve interface? 

Yes, it is included in option 2.  My PR is already doing this.
The only point is whether to force the corresponding reserve and unreserve to be implemented with the same plugin by the interface.

**Comment by draveness** [comment]
cc/ @ahg-g

**Comment by mrkm4ntr** [comment]
Does anyone have opinions about this?
