### ISSUE TITLE
Remove deprecated scheduler metrics

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83782]
Cleanup deprecated scheduler metrics: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go

/sig scheduling
/assign @liu-cong

**Comment by Huang-Wei** [comment]
@nitishkumar71 would you mind leaving this @liu-cong or @loqutus , as we should follow the first-come-first-assign rule.

**Comment by danielqsj** [comment]
@ahg-g @Huang-Wei sig-instrumentation has a PR to clean all deprecated metrics in v1.18 which include scheduler part: https://github.com/kubernetes/kubernetes/pull/76496.

**Comment by danielqsj** [comment]
cc @brancz

**Comment by nitishkumar71** [comment]
> @nitishkumar71 would you mind leaving this @liu-cong or @loqutus , as we should follow the first-come-first-assign rule.

Sure. Sorry I didn't notice the assignment.

**Comment by Huang-Wei** [comment]
@danielqsj  Thanks for letting use know.

I prefer to let it handled by #76496.

/unassign @loqutus
/assign @danielqsj

**Comment by danielqsj** [comment]
#76496 was merged. Close this issue.
/close
