### ISSUE TITLE
ceph rbd resize fails because wrong provisioner is being used

### ISSUE THREAD

**Issue by fahman** [kubernetes/kubernetes#83786]
**What happened**:
Our cluster is set with ceph.com/rbd provisioner (image: quay.io/external_storage/rbd-provisioner:v2.1.1-k8s1.11) instead of default provisioner kubernetes.io/rbd. When resizing cephrbd PVCs, resizing fail.

**What you expected to happen**: Resizing succeeds when changing the size of storage.

**How to reproduce it (as minimally and precisely as possible)**:
1. Download and adjust [provisioner-test.yaml.txt](https://github.com/kubernetes/kubernetes/files/3718133/provisioner-test.yaml.txt)
2. kubectl apply -f [provisioner-test.yaml.txt](https://github.com/kubernetes/kubernetes/files/3718133/provisioner-test.yaml.txt)
3. kubectl edit pvc claim1 (and increase storage in pvc definition)

**Anything else we need to know?**:
```bash
kubectl describe pvc -n default claim1
...
Normal     ExternalProvisioning   47s                persistentvolume-controller                                                             waiting for a volume to be created, either by external provisioner "ceph.com/rbd" or manually created by system administrator
  Normal     Provisioning           47s                ceph.com/rbd_cephrbd-provisioner-58c759bccb-64p4p_af76d72b-ec19-11e9-a518-1668ccca6fcf  External provisioner is provisioning volume for claim "default/claim1"
  Normal     ProvisioningSucceeded  47s                ceph.com/rbd_cephrbd-provisioner-58c759bccb-64p4p_af76d72b-ec19-11e9-a518-1668ccca6fcf  Successfully provisioned volume pvc-1f1ccc57-d7f5-45df-b469-ed0c586821f4
  Warning    VolumeResizeFailed     8s (x13 over 29s)  volume_expand                                                                           error expanding volume "default/claim1" of plugin "kubernetes.io/rbd": failed to get admin secret from ["kube-system"/"ceph-rbd-admin-secret"]: failed to get secret from ["kube-system"/"ceph-rbd-admin-secret"]: Cannot get secret of type kubernetes.io/rbd
Mounted By:  <none>
```

The key here is
- of plugin "kubernetes.io/rbd"
- Cannot get secret of type kubernetes.io/rbd

Provisioner, StorageClass and PersistentVolumeClaim all three are configured to use ceph.com/rbd provisioner. From the log above it can be seen that initial provisioning of PVC succeeds with correct provisioner. Then, upon resize, for some reason suddenly kubernetes.io/rbd is being used. Since internal kubernetes provisioner is not configured, resizing fails of course.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: on-prem with lotsof masters and workers

- OS (e.g: `cat /etc/os-release`):
NAME                  STATUS   ROLES         AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
kubernetes-master-1   Ready    master,node   266d   v1.15.3   xx.xxx.x.x    <none>        Ubuntu 18.04.1 LTS   5.0.0-31-generic   docker://18.9.7

- Kernel (e.g. `uname -a`): 5.0.0-31-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by foshantiger** [comment]
same issue~

**Comment by RichieSams** [comment]
I ran into this issue as well, using `ceph.com/rbd`
It looks like the solution is to use the CSI driver instead of `ceph.com/rbd` https://github.com/ceph/ceph-csi

**Comment by humblec** [comment]
> I ran into this issue as well, using `ceph.com/rbd`
> It looks like the solution is to use the CSI driver instead of `ceph.com/rbd` https://github.com/ceph/ceph-csi

Yeah, instead of `external-storage` provisioner, please use ceph-csi provisioner which support resize too. Please let me know if you have any question on this.

**Comment by fahman** [comment]
I am 

> 
> 
> > I ran into this issue as well, using `ceph.com/rbd`
> > It looks like the solution is to use the CSI driver instead of `ceph.com/rbd` https://github.com/ceph/ceph-csi
> 
> Yeah, instead of `external-storage` provisioner, please use ceph-csi provisioner which support resize too. Please let me know if you have any question on this.

I am sorry but this is a non-solution.
We are using proxmox that comes bundled with ceph v12.2.10 and we just cannot easily upgrade ceph cluster to the version required by csi driver.

So I vote this bug is still open just in case some dude eventually decides to fix it.
