### ISSUE TITLE
Support dynamically set log level for kube-scheduler

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83783]
**What would you like to be added**:
Support dynamically set log level for kube-scheduler,  #68780 is blocked on node controller approval, but we can move forward with a scheduler only change.

/sig scheduling

**Comment by ahg-g** [comment]
@mrkm4ntr do you have a PR for this one?

**Comment by mrkm4ntr** [comment]
@ahg-g I submitted the PR.
