### ISSUE TITLE
kube-proxy node IP / bind address does not fall back to 127.0.0.1 anymore in iptables mode when node is missing from API

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/kubernetes#83791]
**What happened**:

Using Kubernetes 1.16.1, I started kube-proxy in iptables mode as a static pod on a master node. The master node was intentionally (and permanently) not available in the API as a Node object.

kube-proxy started up and terminated soon after because it failed to [fetch the Node from the API](https://github.com/kubernetes/kubernetes/blob/v1.16.1/pkg/util/node/node.go#L112-L138) (which is supposed to function as the bound address) and eventually returned an error:

```
E1011 15:25:45.275305       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:25:46.414712       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:25:48.557554       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:25:52.953709       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:26:01.612814       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
F1011 15:26:01.612866       1 server.go:443] unable to get node IP for hostname master-k8s-1-16
```

**What you expected to happen**:

I expected the same behavior as in Kubernetes 1.15 where failure to look up the Node in the API would result in [127.0.0.1 to be used as the default bind address when iptables mode is used](https://github.com/kubernetes/kubernetes/blob/v1.15.4/pkg/proxy/iptables/proxier.go#L315-L318).

**How to reproduce it (as minimally and precisely as possible)**:

Configure kube-proxy with iptables mode on Kubernetes 1.16 without the hosting Node being available in the Kubernetes API (under the OS hostname).

**Anything else we need to know?**:

PR #77167 (_Fix for kube-proxy to wait for some duration for the node to be defined_) introduced an additional [check for the node IP and returns an error if it is found empty](https://github.com/kubernetes/kubernetes/pull/77167/files#diff-934760ea1a4e195e49bcd10625cf4e46R146-R148). I believe this is the part that is causing the change in behavior: in Kubernetes 1.15, the check would be omitted and cause `iptables.NewProxier()` to set the default bind address to 127.0.0.1 (when iptables mode is set; I haven't checked other modes).

The PR's primary purpose seems to be a different one (retrying node IP retrieval from the API), so my understanding is that the added check was not really needed; unless I'm misunderstanding things which I don't want to rule out at all. 

The quick workaround was to explicitly configure kube-proxy with `--bind-address 127.0.0.1`. However, I'm not entirely sure if that's a good solution long-term compared to letting Kubernetes do The Right Thing, which is what I'd like to clarify through this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.1
- Cloud provider or hardware configuration: Kubernetes running on DigitalOcean VMs (droplets)
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux master-k8s-1-16-test1 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64 GNU/Linux

/sig network

/cc @paulsubrata55 @thockin who were involved in the referenced PR.

**Comment by andrewsykim** [comment]
I made a similar comment in https://github.com/kubernetes/kubernetes/pull/77167#discussion_r336275761, wondering if this is a breaking change in v1.16 that we should revert? 

Previously if `nodeIP` is nil, kube-proxy defaults to [127.0.0.1 as the node IP](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L282-L286) but now kube-proxy always exits with error instead of defaulting to local host. I think a lot of external cloud providers relied on this behavior because they needed to talk to API server prior to node addresses being set by the provider. 

Thoughts @thockin? 

/assign @thockin

**Comment by andrewsykim** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/84071 to preserve behavior before v1.16 where node IP defaults to 127.0.01 is none is found.
