### ISSUE TITLE
FlexVol not finding plugin on restart

### ISSUE THREAD

**Issue by Pure-AdamuKaapan** [kubernetes/kubernetes#83803]
**What happened**:
We installed our storage driver (https://github.com/purestorage/helm-charts/tree/master/pure-k8s-plugin) in a cluster (reproduced on both 1.14 and 1.15), and the plugin was loaded correctly. Upon rebooting a node, kubelet is throwing "no volume plugin matched" errors even though the file is still present and unmodified in the correct directory.

**What you expected to happen**:
Upon rebooting a node, the FlexVol plugin should be found as expected and used without issue.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the flex vol driver linked above
1. Create a pod with a PVC using this driver (can provide specific files if desired, but it's a pretty generic setup)
1. Reboot the node the pod is on
1. Delete the pod
1. Observe the pod being stuck in "Terminating" state and "no volume plugin matched" errors in kubelet logs

**Anything else we need to know?**:
* Issue does not reproduce 100% of the time, but is consistent enough (~60-70% of the time) to still cause issues.
* Note that this storage driver helm chart provided above normally runs in a DaemonSet: for testing purposes I disabled the "daemon" behavior so it ran only once. The issue still reproduced.
* File permissions were confirmed the same in both reproducing and non-reproducing conditions.
* File `sha1sum` was confirmed the same in both reproducing and non-reproducing conditions.
* Adding an audit watch in `auditd` to the plugin binary confirms no changes aside from the initial install.

**Environment**:
- Kubernetes version (use `kubectl version`): Server versions 1.15.4 and 1.14.7 
- Cloud provider or hardware configuration: OpenStack
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 LTS and CentOS 7
- Kernel (e.g. `uname -a`): Ubuntu 4.15.0-64-generic and CentOS 3.10.0-1062.1.2.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by xiaoanyunfei** [comment]
The related PR has pended for a long time
https://github.com/kubernetes/kubernetes/pull/80973

**Comment by Pure-AdamuKaapan** [comment]
I'll just go ahead and close this in lieu of #80973 .
