### ISSUE TITLE
SharedIndexInformers can miss notifications

### ISSUE THREAD

**Issue by matte21** [kubernetes/kubernetes#83810]
**What happened**:
I did a review of https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/tools/cache and found out a case where a SharedIndexInformer can miss a notification. Follows an example scenario where this could happen.

1) A SharedIndexInformer is running, and its reflector is WATCHing.
2) A delete notification for an API object _X_ with namespaced name _N1_ and UID _U1_ which was in the informer's cache is received.
3) The reflector [invokes the store's Delete method](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L395-L399) on _X_; the relevant store is a DeltaFIFO and its Delete method is [this](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L191).
4) The DeltaFIFO's Delete method invokes [queueActionLocked](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L219), which [enqueues _N1_ in the DeltaFIFO's queue and adds a delta of type deleted to the map from objects IDs (namespaced names) to deltas](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L320-L328).

Notice that the store of the reflector, i.e., the DeltaFIFO, is NOT the SharedIndexInformer's store/cache: [the SharedIndexInformer extracts object deltas from the DeltaFIFO and modifies its cache accordingly](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L448-L477). Assume that BEFORE _X_'s deletion is popped from the DeltaFIFO and applied to the informer's cache, the following sequence of events take place:

5) The WATCH is interrupted because of a network partition.
6) While the reflector is not watching, a new API object _Y_ with namespaced name _N1_ (same as _X_) and UID _U2_ is created.
7) The partition disappears and the reflector does a relist against the API server; there's a "hole" between the last watch notification and the list results; assume _Y_ is in the LIST results.
8) The reflector will load the LIST results in the store/DeltaFIFO with [syncWith](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L240) which in turn calls the DeltaFIFO's [replace](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L340) method. The DeltaFIFO's replace method attempts to add to the DeltaFIFO a delta of type `Sync` for every object in the LIST results: when processing _Y_ it will [invoke queueActionLocked](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L456-L462) which should [create a delta of type `Sync` for  Y and add it to the DeltaFIFO](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L320-L328). But `queueActionLocked` won't enqueue Y's delta, because it enqueues deltas of type `Sync` only if there's not already a delta of type `Deleted` for the given object ID as the last delta for that object ID (see [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L313-L318) and [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L298-L303)), to avoid recreating a deleted object during a periodic resync triggered by the SharedIndexInformer resync period. Object IDs are namespaced names,  and remember that the last delta for Y's namespaced name in the DeltaFIFO is _X_'s deletion. The consequence is that _Y_'s creation delta is not added to the DeltaFIFO: Y is not added to the SharedIndexInformer's cache and its creation notification handler does not execute. The SharedIndexInformer missed Y's creation. 

**What you expected to happen**:
I expected SharedIndexInformers to get all notifications from the API server.

**Anything else we need to know?**
Missed notifications should be rare: for them to occur a `Delete` delta must stay in the DeltaFIFO without being processed for long enough for a new List against the API server to be completed. Also, https://github.com/kubernetes/kubernetes/pull/83520 touches the reflector code that handles list and watches, and it might introduce changes relevant to this bug.

**Proposed solution**:
There's a straightforward fix: get rid of the check that skips enqueuing of a `Sync` delta for object ID _X_ if the last delta added to the DeltaFIFO (and still in it) for _X_  is of type  `Delete`;  [this](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L313-L318) is the code to remove. Notice that such check applies to deltas of type `Sync` only. `Sync` deltas are triggered only by relists and periodic resyncs. In the case of relists the check is harmful as it's the cause of this bug. In the case of periodic resyncs, that check is useless because it will either evaluate to `false` or not execute; in fact, during a period resync, [processing of an object with ID _X_ stops if there's already a delta for _X_ in the DeltaFIFO](https://github.com/kubernetes/client-go/blob/master/tools/cache/delta_fifo.go#L560-L562) and this condition is checked before the check that would be removed, OTOH, if this condition is true and processing goes on the check that would be removed can only evaluate to `false` (hence the delta for _X_ is enqueued). If this solution has consensus I'd be happy to open a PR.

**Comment by matte21** [comment]
cc @MikeSpreitzer @liggitt @jpbetz

**Comment by jpbetz** [comment]
cc @wojtek-t

**Comment by jpbetz** [comment]
xref https://github.com/kubernetes/kubernetes/issues/27004, https://github.com/kubernetes/kubernetes/pull/27435

**Comment by liggitt** [comment]
cc @deads2k

**Comment by smarterclayton** [comment]
This looks similar to failures we were seeing in kube-proxy while doing a rolling master upgrade.  It was repeatable enough that someone hacked a workaround that I later spotted - this is close enough to the description that I’m suspicious that it was real

/priority critical-urgent

Since any missed informer event can cause all sorts of safety violations.

**Comment by smarterclayton** [comment]
Note that rolling master upgrades break watches en masse, so a backlogged informer (contention / other locking / busy machine) would be more likely so see it the more caches it has.

**Comment by liggitt** [comment]
A great first step would be to craft a test that demonstrates the issue repeatably, to help verify potential fixes resolve it.

**Comment by matte21** [comment]
@liggitt IYO what would be the most appropriate kind of test, a unit test for the reflector or something higher-level like integration/e2e tests?

**Comment by wojtek-t** [comment]
The lower-level the test will be the better. So ideally unit test.

**Comment by liggitt** [comment]
the lowest level that demonstrates the problematic behavior. if the issue is with the interaction between reflector and shared informer, then ideally something at the shared informer level

**Comment by matte21** [comment]
When the reflector calls `DeltaFIFO.Replace(listResults)` it is expected that for each object _O_ with ID _X_ in `listResults` a delta is added to the DeltaFIFO, but that is (erroneously) not the case if the DeltaFIFO already stores a `Delete` delta for ID _X_ . So it's the DeltaFIFO which causes troubles and should be tested. But that alone does not show the user-visible problem; for a test to fail because a SharedIndexInformer missed a notification, the test would have to be in the SharedIndexInformer.

**Comment by liggitt** [comment]
> When the reflector calls `DeltaFIFO.Replace(listResults)` it is expected that for each object _O_ with ID _X_ in `listResults` a delta is added to the DeltaFIFO, but that is (erroneously) not the case if the DeltaFIFO already stores a `Delete` delta for ID _X_ . So it's the DeltaFIFO which causes troubles and should be tested.

That seems reasonable. I'd expect a test that sets up the described scenario and exercises both the Relist/Replace and Resync cases described here:

> * In the case of relists the check is harmful as it's the cause of this bug.
> * In the case of periodic resyncs, that check is useless because it will either evaluate to false or not execute; ...

**Comment by matte21** [comment]
Sounds good, I'm at work.

**Comment by dcbw** [comment]
@matte21 just removing those lines of code doesn't quite work though, because the Deletion delta is still in the queue and doesn't get removed when a Sync comes in.

**Comment by dcbw** [comment]
@matte21 is the testcase literally just adding this to delta_fifo_test.go?

```
func TestDeltaFIFO_ReplaceOverridesDeletions(t *testing.T) {
	f := NewDeltaFIFO(
		testFifoObjectKeyFunc,
		keyLookupFunc(func() []testFifoObject {
			return []testFifoObject{mkFifoObj("baz", 10)}
		}),
	)
	f.Delete(mkFifoObj("baz", 10))
	f.Replace([]interface{}{mkFifoObj("baz", 5)}, "0")

	expectedList := []Deltas{
		// A Replace()-generated Sync should always be enqueued even if
		// there is an existing Deleted delta. This ensures that a new
		// object with the same key as the deleted one is not ignored.
		{{Deleted, mkFifoObj("baz", 10)}},
		{{Sync, mkFifoObj("baz", 5)}},
	}

	for _, expected := range expectedList {
		cur := Pop(f).(Deltas)
		if e, a := expected, cur; !reflect.DeepEqual(e, a) {
			t.Errorf("Expected %#v, got %#v", e, a)
		}
	}
}
```

But for some reason this hangs in the Pop(f).

**Comment by matte21** [comment]
@dcbw Yes, the test looks very similar to what you posted, but there's a mistake: expectedList must be of type `Deltas`, not `[]Deltas`.

**Comment by liggitt** [comment]
(that would be caught and fail the test immediately by changing `t.Errorf` to `t.Fatalf`)

**Comment by tedyu** [comment]
How about this change ?
```
diff --git a/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go b/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
index 1db3a01b6c..1be7300850 100644
--- a/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
+++ b/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
@@ -314,7 +314,7 @@ func (f *DeltaFIFO) queueActionLocked(actionType DeltaType, obj interface{}) err
        // then we should ignore Sync events, because it would result in
        // recreation of this object.
        if actionType == Sync && f.willObjectBeDeletedLocked(id) {
-               return nil
+               delete(f.items, id)
        }

        newDeltas := append(f.items[id], Delta{actionType, obj})
```
The test from @dcbw would have this:
```
	expectedList := Deltas{
		// A Replace()-generated Sync should always be enqueued even if
		// there is an existing Deleted delta. This ensures that a new
		// object with the same key as the deleted one is not ignored.
		{Sync, mkFifoObj("baz", 5)},
	}
```

**Comment by dcbw** [comment]
> @dcbw Yes, the test looks very similar to what you posted, but there's a mistake: the expected result must be a single `Deltas` with the two `Delta` that in your example are the only elements of the two 1-element Deltas that make up `expectedList`, respectively.

Aha, you're totally right :) Had to run off to lunch before spending more time on it :)

**Comment by dcbw** [comment]
> How about this change ?

@tedyu DeltaFIFO only de-dupes deletions, but your example would do effectively extend that to compressing Delete+Sync=Sync. You used to be able to build smarter compression off DeltaFIFO (eg https://github.com/openshift/origin/pull/10070/files#diff-0220ccb2c017c89846fc17ff28c57837R176 ) but nobody actually used the DeltaCompressor stuff so we removed it. And nobody above DeltaFIFO expects compressed events now :(

In your example I'd be a bit worried about the implications of not deleting the object, since the Sync-ed one probably has a different UUID and thus technically not be the same object as the deleted one. Might not be a big issue, but this is critical path code so I'd personally rather be a bit conservative.

**Comment by liggitt** [comment]
> Might not be a big issue, but this is critical path code so I'd personally rather be a bit conservative.

I agree about not compressing. I do wonder if a sync arriving on top of a delete should turn into an Added event (in at least one path, like the one described in this issue, that is exactly what happens).

It's a little hard to reason about what this sync event should be when we know that relists can currently time-travel.

**Comment by seh** [comment]
I was [just asking about this very situation](https://kubernetes.slack.com/archives/C0EG7JC6T/p1571054208147900) this morning in the "sig-api-machinery" channel of the "Kubernetes" Slack team. My reading of the code had me expecting that I'd get a _delete_ followed by an _add_.

**Comment by liggitt** [comment]
> I was [just asking about this very situation](https://kubernetes.slack.com/archives/C0EG7JC6T/p1571054208147900) this morning in the "sig-api-machinery" channel of the "Kubernetes" Slack team. My reading of the code had me expecting that I'd get a _delete_ followed by an _add_.

This issue is specifically focused on how a queued delete event (typically via directly observing a delete watch event or via absence in a relist/replace) followed by an observed add (via presence in a relist) is handled by DeltaFIFO.

Your question is slightly broader/different, and has multiple facets:
1. Are UID changes considered when handling reflector object add/delete/update events? They are not; if an object is deleted and recreated between the reflector dropping a watch and relisting, the reflector will enqueue an Sync event with the object with the new uid (which the shared informer will turn into an Update event)
2. Are delete/add events is actively compressed into an update event? I don't think so, but it's been a while since I've traipsed through reflector/fifo code, so I'm not positive (and since the Update with a new uid can occur from scenario 1, informer clients have to be prepared for uid to change on update anyway)

**Comment by dcbw** [comment]
@seh Listeners need to handle Sync too. And the only two in-tree users of NewDeltaFIFO are cache/controller.go and cache/shared_informer.go and they look like they correctly handle Sync.

**Comment by dcbw** [comment]
>     2\. Are delete/add events is actively compressed into an update event? I don't think so, but it's been a while since I've traipsed through reflector/fifo code, so I'm not positive (and since the Update with a new uid can occur from scenario 1, informer clients have to be prepared for uid to change on update anyway)

@liggitt @seh no events are compressed at the `cache` level. It's up to DeltaFIFO listeners to do that, and to my knowledge nothing in Kubernetes does anymore.

**Comment by dcbw** [comment]
> I agree about not compressing. I do wonder if a sync arriving on top of a delete should turn into an Added event (in at least one path, like the one described in this issue, that is exactly what happens).

@liggitt if this happens, I think it should happen on top of the DeltaFIFO, not in the DF. Let's keep DF simpler since it's (a) complicated enough and (b) critical path code.

> It's a little hard to reason about what this sync event should be when we know that relists can currently time-travel backwards.
> 
> Edit: it looks like shared informer code will [turn the Sync event into an Added event](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L456-L468) if it follows a delete event.

@liggitt probably the right place for compression, if any happens. IMHO it's correct that Deletes don't get compressed, eg that Delete + Add is not compressed into Update or something like that.

**Comment by liggitt** [comment]
> IMHO it's correct that Deletes don't get compressed, eg that Delete + Add is not compressed into Update or something like that.

I agree, though that specific example **can** happen naturally if it occurs in a window while the reflector isn't getting watch events.

**Comment by seh** [comment]
> that specific example **can** happen naturally if it occurs in a window while the reflector isn't getting watch events.

Just to make sure I understand this properly, does this scenario involve an object in the cache with name "x" and UID "u1," then the reflector loses its watch, reestablishes it and lists all the relevant objects in the cluster, finds one named "x" with UID "u2," and since it already has an "x" in its cache, translates this discovery into a `ResourceEventHandler.OnUpdate` call?

**Comment by liggitt** [comment]
> ... since it already has an "x" in its cache, translates this discovery into a `ResourceEventHandler.OnUpdate` call?

exactly

**Comment by dcbw** [comment]
> It's a little hard to reason about what this sync event should be when we know that relists can currently time-travel backwards.

@liggitt does this mean we couldn't use the `resourceVersion` argument to DeltaFIFO's Replace() to work around whatever https://github.com/kubernetes/kubernetes/pull/26167 is talking about (if that problem still exists)?

**Comment by liggitt** [comment]
> @liggitt does this mean we couldn't use the `resourceVersion` argument to DeltaFIFO's Replace() to work around whatever #26167 is talking about (if that problem still exists)?

clients can only use resourceVersion to check equality, not older-than/newer-than

**Comment by MikeSpreitzer** [comment]
As noted in Slack, there is now careful commentary in https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go about what is promised.  There is no promise that a delete followed by an add is delivered as two notifications; it is allowed to be delivered as one update notification.
