### ISSUE TITLE
Performance concern for the graduation of ScheduleDaemonSetPods

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#83829]
## Overview

The primary concern for graduating ScheduleDaemonSetPods to the stable version could be the overhead to the scheduler and the startup time of daemons. After we graduate this feature, the scheduler would select nodes for all of the DaemonSet pods, which may cause a lot of pods with NodeAffinity to be processed.

This issue is used for tracking the potential performance problem after the graduation of ScheduleDaemonSetPods.

## Without ScheduleDaemonSetPods

Previously, Kubernetes schedules DaemonSet pods with daemon controller, which creates pods directly on the precalculated nodes.

https://github.com/kubernetes/kubernetes/blob/e1685b5b59b409b8479a2b5989af485dbdd84a41/pkg/controller/daemon/daemon_controller.go#L1050-L1053

## With ScheduleDaemonSetPods

With ScheduleDaemonSetPods feature beta'ed in 1.12, all the daemonset pods were scheduled by the scheduler with node affinity as the default behavior:

https://github.com/kubernetes/kubernetes/blob/e1685b5b59b409b8479a2b5989af485dbdd84a41/pkg/controller/daemon/daemon_controller.go#L1043-L1047

Instead of placing pods directly on nodes, the scheduler still needs to filter the nodes with affinity, which is the extra cost.

### Extra cost

```go
BenchmarkSchedulingNodeAffinity/500Nodes/250Pods-4         	     250	   4466390 ns/op
```

If the scheduler schedules one pod with node affinity in ~4.46ms, suppose we have a big cluster of 5000 nodes. When we create a daemonset in the API server, it will take ~22s to schedule all the 5000 pods with the scheduler, and it could take much less time to in an average cluster with hundreds of nodes.

I scanned through the issues and didn't find any performance complain about the scheduling daemonset pods.

## Reference

- https://github.com/kubernetes/enhancements/issues/548
- https://github.com/kubernetes/enhancements/pull/1299
- https://github.com/kubernetes/kubernetes/pull/82795

/sig scheduling
/cc @k82cn

**Comment by draveness** [comment]
cc/ @liggitt @guineveresaenger 

I updated the description, could you please take another look? Thanks

**Comment by draveness** [comment]
> Is a daemonset test part of our scale test suite? If it is, and we have been successfully running the 5k node tests with this feature enabled, this may be as simple as documenting the tested configurations and impact of the feature. If there is not a daemonset test scenario, I'd recommend working with sig-scalability to define one.

After some digging around the pertest codebase, I found that we have tested daemonset with 5k nodes and didn't find any code to disable the ScheduleDaemonSetPods feature.

https://github.com/kubernetes/test-infra/blob/c39959996dda01c606d6a18187be89059a263fac/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L199-L261

cc/ @wojtek-t, please feel free to correct me if there's anything wrong, thanks

**Comment by wojtek-t** [comment]
Yes - we are testing DaemonSets in our scalablity tests. The tests aren't super extensive - we just ensure that we can create DS and then upgrade it (without requiring any sophisticated latencies of that for now), but we didn't observe any issues with that.
As of now, we have regression that happened sometime on Saturday: https://github.com/kubernetes/kubernetes/issues/84151 - but before that we were completely healthy, so if nothing has changes around that time (or later), you seem to be fine.

**Comment by draveness** [comment]
> As of now, we have regression that happened sometime on Saturday: #84151 - but before that we were completely healthy, so if nothing has changes around that time (or later), you seem to be fine.

Thanks, the ScheduleDaemonSetPods feature was graduated to beta in 1.12 and enabled by default, so I don't think it's relevant.

@liggitt, is this sufficient to continue graduating the ScheduleDaemonSetPods, or we still have some other staff which needs to check?

**Comment by liggitt** [comment]
> @liggitt, is this sufficient to continue graduating the ScheduleDaemonSetPods

it seems so. can this issue be closed?

**Comment by draveness** [comment]
/close



Regards,
Draven
