### ISSUE TITLE
Should use Pod creation time instead of its last queued time to sort Pod for the same priority

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/kubernetes#83826]
**What happened**:
Currently (after https://github.com/kubernetes/kubernetes/pull/73700), we use the **Pod last queued time by scheduler** to sort Pod for the same priority:
https://github.com/kubernetes/kubernetes/blob/0599ca2bcfcae7d702f95284f3c2e2c2978c7772/pkg/scheduler/internal/queue/scheduling_queue.go#L717-L721
https://github.com/kubernetes/kubernetes/blob/0599ca2bcfcae7d702f95284f3c2e2c2978c7772/pkg/scheduler/internal/queue/scheduling_queue.go#L361-L362

Usually, it produces the same Pod ordering as the **Pod creation time** (If Pod are submitted one by one **slowly**, and previous Pods are **always allocated**).

However, if scheduler is restarted, or switched to another leader, etc, all pending Pods will be re-informed to local cache, and the scheduler will **see** the Pod comes in a **undefined order**, possibly very different with the Pod ordering produced by the **Pod creation time**.

And even if the scheduler is not re-informed by restarting etc, using last queued time still causes https://github.com/kubernetes/kubernetes/issues/83834. And the reason is that after a Pod is poped for scheduling and then added back to queue again, its **last queued time** is updated to now (above `newPodInfo `is called again). So, if still sort by the time, it is no longer represent the **Pod pending time since created**, it just represent the **Pod pending time since last scheduled** which user does not aware and does not care, they just know the former Pod pending time.

**What you expected to happen**:
The scheduler should be **near FIFO** for the same priority Pods, and the **FI(First In)** should be determined steadily by the **Pod CreationTimestamp**, instead of the unsteady **Pod last queued time**, to measure the user cared, awared, true and steady **Pod Pending time**.

**How to reproduce it (as minimally and precisely as possible)**:
Case1: Many Pods at the same priority are waiting, then restart scheduler. You will see Pods are scheduled in a **Far from FIFO** way (e.g. easy to see a Pod will not be allocated, but a Pod with the same spec except for naming submitted 2hrs later than it will be allocated).

Case2: Same as the repro steps in https://github.com/kubernetes/kubernetes/issues/83834

**Anything else we need to know?**:
I see Pod CreationTimestamp is first introduced to sort by PR https://github.com/kubernetes/kubernetes/pull/71488, however, it is later removed by PR https://github.com/kubernetes/kubernetes/pull/73700.
Is it a degradation? And Why?
BTW, I tried to fix this by PR https://github.com/kubernetes/kubernetes/pull/83835

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`on-premise
`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```
- Kernel (e.g. `uname -a`):
`Linux stcal-177 4.15.0-1060-azure #65-Ubuntu SMP Wed Sep 18 08:55:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yqwang-ms** [comment]
/sig scheduling
@bsalamat and @denkensk PTAL

**Comment by yqwang-ms** [comment]
@liu-cong I see you just refreshed the Pod timestamp.
https://github.com/kubernetes/kubernetes/blob/0599ca2bcfcae7d702f95284f3c2e2c2978c7772/pkg/scheduler/internal/queue/scheduling_queue.go#L361-L362
So, the Pod timestamp is no longer immutable after init, and no longer means:
https://github.com/kubernetes/kubernetes/blob/0599ca2bcfcae7d702f95284f3c2e2c2978c7772/pkg/scheduler/framework/v1alpha1/interface.go#L162-L163

Why you have to refresh it in your "add metrics" PR https://github.com/kubernetes/kubernetes/pull/83674?
For same Pod priority, it makes scheduler far more away from FIFO policy according to Pod pending time.

**Comment by liu-cong** [comment]
Hi,

Please take a look at the commit before mine. I was just trying to maintain
the same logic as before. The logic about podInfo.TimeStamp wasn't changed
by my commit.

**Comment by yqwang-ms** [comment]
@liu-cong I knew that later, so I deleted it. Sorry to bother you....

**Comment by liu-cong** [comment]
No worries at all :)

**Comment by ryanpeach** [comment]
I'd like to know if the kubernetes schedule queue is guaranteed FIFO for pods of the same priority. Can anyone advise?
