### ISSUE TITLE
go mod tidy fails in on go1.13 not go1.12

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/kubernetes#83847]
**What happened**:
`go mod tidy` failure for upgrading [smi-sdk-go](https://github.com/deislabs/smi-sdk-go/pull/32) to golang v1.13.

```
$ go mod tidy
.......
github.com/deislabs/smi-sdk-go/cmd/installer imports
	github.com/kubernetes-client/go/kubernetes/config tested by
	github.com/kubernetes-client/go/kubernetes/config.test imports
	k8s.io/client/kubernetes/config/api: cannot find module providing package k8s.io/client/kubernetes/config/api
```

**What you expected to happen**:

The build should be clear

**How to reproduce it (as minimally and precisely as possible)**:

1. checkout the repo, https://github.com/deislabs/smi-sdk-go
2. switch to go v1.13.1
3. `go mod tidy`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`):
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by liggitt** [comment]
support for 1.13 is being added in https://github.com/kubernetes/kubernetes/pull/82809, but I'm confused by that error message. What version of client go are you using?

**Comment by liggitt** [comment]
github.com/kubernetes-client/go and k8s.io/client/kubernetes are not packages provided by this repo

**Comment by liggitt** [comment]
This appears to be related to packages provided by https://github.com/kubernetes-client/go/blob/master/kubernetes/config/kube_config_test.go

I'd recommend asking about this issue at https://github.com/kubernetes-client/go

/close

**Comment by chenrui333** [comment]
Cool, I will ask there instead, thanks for the direction.
