### ISSUE TITLE
PV update validation ignored the capacity storge

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#83845]
**What happened**:

I  shrinks pv manifest successfully, but I pv shrinkage actually did not do that.   I think we may need forbid shrinks pv capacity as pvc

See https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L1854

we do not validate the new pv size.

But for pvc, we validate the size
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L1950 

**What you expected to happen**:

forbid to shrink the pv size

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): k8s 1.16
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs
