### ISSUE TITLE
[migration phase 1] NodeAffinity as Score plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83848]
**What would you like to be added**:

Add a Score that calls into NodAffinity priority, should be added to the existing NodeAffinity plugin, example #83460

**Why is this needed**:

Part of  #83554

/sig scheduling
/help
/priority important-soon

**Comment by draveness** [comment]
/retitle [migration phase 1] NodeAffinity as Score plugin

**Comment by hprateek43** [comment]
@draveness Is someone working on this ? If not, you can assign it to me?

**Comment by draveness** [comment]
> @draveness Is someone working on this ? If not, you can assign it to me?

I'll send the PR, thanks
