### ISSUE TITLE
kubectl create deployment not using the deployment name in the container spec

### ISSUE THREAD

**Issue by scraxxy** [kubernetes/kubernetes#83851]
**What happened**:
`kubectl create deployment` used the default image name in the container spec instead of the deployment name I specified

```
$ kubectl create deployment mark-test --image=nginx --dry-run -o yaml
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  creationTimestamp: null 
  labels: 
    app: mark-test 
  name: mark-test 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mark-test 
  strategy: {} 
  template: 
    metadata: 
      creationTimestamp: null 
      labels: 
        app: mark-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
```

**What you expected to happen**:
I expect the container spec to use the deployment name (Like how `kubectl run` does it)

**How to reproduce it (as minimally and precisely as possible)**:
$ kubectl create deployment deploy-test --image=nginx --dry-run -o yaml

compare that to;
```
$ kubectl run mark-test --image=nginx --dry-run -o yaml
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mark-test
  name: mark-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mark-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mark-test
    spec:
      containers:
      - image: nginx
        name: mark-test
        resources: {}
status: {}
```

**Anything else we need to know?**:
Is not using the deployment name changed intentionally?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

(I'm aware I'm not using the latest version, I'm studying for CKA)

/sig cli
(apologies if this is the wrong group..)

**Comment by zhouya0** [comment]
I don't think container's name must be the same with the deployement's name and actually the containers's name is not important as it's managed by pod. But looks like `kubectl run` and `kubectl create` have different policy i will check if they can be the same.

**Comment by zhouya0** [comment]
/assign

see the difference with 
`kubectl create`
https://github.com/kubernetes/kubernetes/blob/3ec5fe500d7a56be6ff6c15f916987eaa48c2e94/staging/src/k8s.io/kubectl/pkg/generate/versioned/deployment.go#L74

`kubectl run`
https://github.com/kubernetes/kubernetes/blob/3ec5fe500d7a56be6ff6c15f916987eaa48c2e94/staging/src/k8s.io/kubectl/pkg/generate/versioned/run.go#L741

These two functions show the different policy. It seems use image name for container's name is better but i don't know if it's necessary to change.

**Comment by apelisse** [comment]
The container name is mostly irrelevant, especially in that case. I don't think there's anything to fix here. I'm closing this issue, please re-open if you disagree. Thanks.
/close
