### ISSUE TITLE
[migration phase 1] EvenPodsSpread as filter plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83874]
**What would you like to be added**:

Add a filter plugin that calls into EvenPodsSpread predicate, example #83460

**Why is this needed**:

Part of  #83554

/sig scheduling
/help
/priority important-soon

**Comment by draveness** [comment]
/retitle: [migration phase 1] EvenPodsSpread as filter plugin

**Comment by draveness** [comment]
/retitle [migration phase 1] EvenPodsSpread as filter plugin

**Comment by jfbai** [comment]
@draveness May I take over this?

**Comment by draveness** [comment]
> @draveness May I take over this?

@Huang-Wei is going to take this over after the offline discussion, and he is familiar with EvenPodsSpread

**Comment by jfbai** [comment]
> > @draveness May I take over this?
> 
> @Huang-Wei is going to take this over after the offline discussion, and he is familiar with EvenPodsSpread

IC, thanks a lot.
