### ISSUE TITLE
Panic happends when deprecating metrics

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/kubernetes#83876]
**What happened**:
CI failed when deprecated metrics. Refer to https://github.com/kubernetes/kubernetes/pull/83836.

The reason is that __a hidden metrics won't be created thus can't be registered to prometheus's registry__.

I guess the other PR failed for the same reason.
#83837 #83838 #83839 #83841
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
When starting the cluster, panic happens
```
[root@ecs-d8b6 ~]# cat /tmp/kube-apiserver.log 
W1014 09:16:25.330658   31301 metric.go:103] This metric has been deprecated for more than one release, hiding.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10f827b]

goroutine 11 [running]:
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*HistogramVec).Describe(0xc0002c2c40, 0xc000097ce0)
<autogenerated>:1 +0xb
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1(0x7f6d53d79100, 0xc0002c2c40, 0xc000097ce0)
/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:273 +0x3b
created by k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register
/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:272 +0x154
[root@ecs-d8b6 ~]#
```
**Anything else we need to know?**:
In my option, we need to remove backoff from legacyregistry.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/assign @logicalhan @RainbowMango 
/sig instrumentation

**Comment by RainbowMango** [comment]
Discoveries after run go test ( by `make test`) after removing backoff and deprecating some metrics:

The kubelet's metrics are protected by the unit tests, and they work well .

The only block is https://github.com/kubernetes/kubernetes/pull/83678, that is I mean register to legacy registry and gather from Prometheus.

**Comment by jktomer** [comment]
By backoff do you mean the fallback call to prometheus.Register in the various legacyregistry register functions?

**Comment by RainbowMango** [comment]
> By backoff do you mean the fallback call to prometheus.Register in the various legacyregistry register functions?

Yes. I opened a PR and see what would happen. (I guess it should be fine now)https://github.com/kubernetes/kubernetes/pull/84135
