### ISSUE TITLE
build-packages-debs is consistently failing

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#83888]
**Which jobs are failing**:
sig-release-master-informing

**Which test(s) are failing**:
build-packages-debs

**Since when has it been failing**:
Oct 10 21:03 PDT

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#build-packages-debs

**Reason for failure**:
🤷‍♀ the log is empty

**Anything else we need to know**:

/milestone v1.17
/priority important-soon
/sig release

cc. @justaugustus

**Comment by droslean** [comment]
related with https://github.com/kubernetes/kubernetes/issues/80715

**Comment by droslean** [comment]
/reopen

Let's keep this issue opened until the next tests will pass.

**Comment by droslean** [comment]
Next run of the job passed. [ci-release-build-packages-debs/1184039767226978304](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-release-build-packages-debs/1184039767226978304)
Closing...

/close
