### ISSUE TITLE
/stats/{namespace}/{podName}/{uid}/{containerName} always return 'no matching container'

### ISSUE THREAD

**Issue by joeyxp** [kubernetes/kubernetes#83889]
In k8s environment. I try to access kubelet API to get pod stats.
`import requests
requests.get('http://localhost:10255/stats/py17484279885885120/py17484279885885120')
requests.get('http://192.168.0.196:10255/stats/jupyter/py17484279885885120/464e363c-ee5c-11e9-a89b-00163e09f676/py17484279885885120')`
They always return "no matching container".
`requests.get('http://localhost:10255/stats/summary')` is successfly.

**Comment by zouyee** [comment]
a、`/stats/<pod name>/<container name>` Default namespace is default
b、`curl http://xx:10255/stats/kube-system/prometheus-node-exporter-9tg5j/c182f4c6-e973-11e9-b783-00505683371b/prometheus-node-exporter`
It's work well.

**Comment by joeyxp** [comment]
`requests.get('http://192.168.0.196:10255/stats/jupyter/py17484279885885120/464e363c-ee5c-11e9-a89b-00163e09f676/py17484279885885120')` works for me. The uuid can be any wording.

**Comment by joeyxp** [comment]
The stats for a specific pod updates about every 10 seconds?  How can i make it more frequent?
