### ISSUE TITLE
Refactor transformObject to implement Encoder interface

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#83898]
Long-term, transformObject:
https://github.com/kubernetes/kubernetes/blob/5219ad7be209b31cdfdae2eda1cd435aff4a3cd2/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/response.go#L40
should be refactored so that it implements Encoder interface (and it has nested encoder inside):

This would allow us to cache the results for difference media.Convert options, which currently is not supported:
https://github.com/kubernetes/kubernetes/blob/5219ad7be209b31cdfdae2eda1cd435aff4a3cd2/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/response.go#L50

@kubernetes/sig-api-machinery-misc @liggitt

**Comment by tedyu** [comment]
To implement Encoder interface, the negotiation.MediaTypeOptions would be passed to the class where transformation code (Encode()) resides, right ?

**Comment by fedebongio** [comment]
Let us know if you need help

**Comment by wojtek-t** [comment]
I won't get to it any time soon TBH. So marking lifecycle frozen for now.

/lifecycle frozen
