### ISSUE TITLE
Failing test [k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull image from gcr.io [NodeConformance]

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#83890]
**Which jobs are failing**:
sig-release-master-informing#gce-windows-master

**Which test(s) are failing**:
 [k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull image from gcr.io [NodeConformance]

**Since when has it been failing**:
Oct 1, since then it is consistently red

**Testgrid link**:
sig-release-master-informing#gce-windows-master

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:367
Oct  2 09:15:20.470: All 3 attempts failed: expected container state: Running, got: "Waiting"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:352
```

**Anything else we need to know**:

/milestone v1.17
/priority important-soon
/sig windows

**Comment by droslean** [comment]
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-windows-master

**Comment by benmoss** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/83397

**Comment by droslean** [comment]
@benmoss #83397 is closed but the job is still failing.

**Comment by benmoss** [comment]
I think you are mistaken, the test referenced here doesn't exist anymore. It has been superseded by `[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull image [NodeConformance]` which is now passing. The only failing test on the most recent run is `[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]`.

**Comment by droslean** [comment]
@benmoss Yes, you are right. Thanks for letting us know. I will close this issue, and open a new one for the new failures.

**Comment by bclau** [comment]
Indeed, I've had this PR open for it: https://github.com/kubernetes/kubernetes/pull/83398
It merged, now it's fine.

As for the guestbook one, I have a PR for that as well: https://github.com/kubernetes/kubernetes/pull/83055
