### ISSUE TITLE
Ability to pull from ECR from a non EC2 instance

### ISSUE THREAD

**Issue by bakshi41c** [kubernetes/kubernetes#83891]
**What would you like to be added**:
Ability to pull docker images from ECR. This would be doable if credsStore is supported. The code to refresh credentials and pull the image is already there, but it only works if its run on AWS EC2 instance.

**Why is this needed**:
To pull docker images from private repository hosted on AWS ECR.

Related issues:
https://github.com/kubernetes/kubernetes/issues/59406

**Comment by bakshi41c** [comment]
@kubernetes/sig-apps-feature-requests
platform/aws

**Comment by boddumanohar** [comment]
I would like to take this task up.

**Comment by boddumanohar** [comment]
I think this facility is already available.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

by default, kubernetes provide support for any private docker repository using the docker login facility. So all you have to do is use `docker login` and add your credentials.

On that particular host you can pass `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and run 
`aws ecr get-login --no-include-email --region <region>`. This will give username, password and url for the your aws ecr repository and you can use those credentials with docker login and or you can create a kubenetes `Secret`.

**Comment by bakshi41c** [comment]
Yes its possible to pull from a private registry (incl. ECR), but with ECR, one needs to generate the username and password using the aws cli tool (as you mentioned) for each node. There is no way to  automate this cleanly, apart from having the username and password in regcreds for each namespace and refreshing them every 12 hours [link](https://medium.com/@xynova/keeping-aws-registry-pull-credentials-fresh-in-kubernetes-2d123f581ca6). The code to do the refreshing and updating, is already there in K8s, as ECR works out of the box when running K8s in AWS EC2 (as a separate credential provider for AWS [link] (https://github.com/kubernetes/kubernetes/tree/master/pkg/credentialprovider)). This should be available when not running on EC2 but still accessing ECR.
