### ISSUE TITLE
Memory/Timer leak in the work queue

### ISSUE THREAD

**Issue by barkbay** [kubernetes/kubernetes#83895]
Hi,

We are experiencing a memory leak in our operator and it seems to be caused by some Timers:
![image](https://user-images.githubusercontent.com/976373/66737404-27049080-ee6c-11e9-998e-91f75a5dd730.png)
_See here the original issue: https://github.com/elastic/cloud-on-k8s/issues/1984_

After some investigations I found out that the [waitingLoop](https://github.com/kubernetes/client-go/blob/172b42569ccacc5c33a885060fc0b7eab863d81e/util/workqueue/delaying_queue.go#L175)  can create a lot of timers (at least [1 every 10 seconds](https://github.com/kubernetes/client-go/blob/172b42569ccacc5c33a885060fc0b7eab863d81e/util/workqueue/delaying_queue.go#L172)) if the queue is not empty : 

https://github.com/kubernetes/client-go/blob/172b42569ccacc5c33a885060fc0b7eab863d81e/util/workqueue/delaying_queue.go#L207-L210

The problem here is that if the event in the queue is to expire in a "far" future the previous `nextReadyAt` timers will pile up and the memory will be reclaimed too late.

Could someone confirm this scenario ?

A fix would be to create some `Timer` with `time.NewTimer(...)` and close them when they are not needed (e.g. `ShutDown()` is called) or superseded by a most recent one.

Happy to discuss the issue and contribute if needed.

**Comment by liggitt** [comment]
thanks for the report, moved to the main repo for better visibility

/sig api-machinery

**Comment by liggitt** [comment]
yes, using NewTimer would be better here

**Comment by barkbay** [comment]
@liggitt thanks for your feedback, could you assign me to this issue ? I will try to provide a fix.

**Comment by barkbay** [comment]
Thanks, I have opened a PR: https://github.com/kubernetes/kubernetes/pull/83945
