### ISSUE TITLE
e2e storage: do not depend on kubectl on host

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#83913]
**What would you like to be added**:

https://github.com/kubernetes/kubernetes/blob/34db57b0071aa62f546020ad4d7cb603196dd0d7/test/e2e/storage/utils/host_exec.go#L87-L110 depends on `kubectl` being installed on the host where the E2E test suite runs.

Instead, the `IssueCommandWithResult` function should execute similar code to kubectl to run the command. Ideally, that utility function then becomes part of the E2E framework instead of being something that is only part of the storage utility package.

**Why is this needed**:

This is an unnecessary additional requirement for that host and makes it harder to invoke the test in a minimal CI environment.

**Comment by cofyc** [comment]
it makes sense, this utility is used by storage tests for now. we can remove kubectl dependency at first.

**Comment by cofyc** [comment]
/assign
I can help with this.

**Comment by pohly** [comment]
@okartau also has some code already.

**Comment by okartau** [comment]
> @okartau also has some code already.

Yes, I created (based on ideas from @pohly mostly) change:
https://github.com/intel/pmem-csi/pull/427/commits/f902111346ac9bec08deeeab20cd82b39c117dbe
which eliminates run of local kubectl and  thus enables to run VolumeIO and VolumeMode test suites in pmem-csi CI.

This was still on older k8s base.
In connection to currenlty ongoing rebase to k8s 1.16, it seems we need more framework parameter passing which is added here:
https://github.com/intel/pmem-csi/pull/427/commits/7a304fdfce760e7823147f96bffbb6039d471cb8

**Comment by cofyc** [comment]
oh, I already sent a PR (https://github.com/kubernetes/kubernetes/pull/83930) to k/k. in the master k8s code, we can simply use `ExecCommandInContainerWithFullOutput` to run the command.

**Comment by cofyc** [comment]
I simply remove kubectl dependency from the HostExec. Yours does more, free feel to make any additional improvements.

**Comment by pohly** [comment]
Yes, we need a more complete solution than the one provided by https://github.com/kubernetes/kubernetes/pull/83930.

**Comment by okartau** [comment]
Does it help if I create a PR based on work done in https://github.com/intel/pmem-csi/pull/365 ? There the changes are in vendor/ in order to enable testing in pmem-csi context

**Comment by pohly** [comment]
Once your experiment in https://github.com/intel/pmem-csi/pull/365 shows that the changes work please move them into a Kubernetes PR.

**Comment by okartau** [comment]
> please move them into a Kubernetes PR.

#84042 created. Because it was developed in context of pmem-csi, which is not using HEAD version of all files, I had to hand-merge some of changes.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/84042#issuecomment-543237627 🤔

**Comment by cofyc** [comment]
FYI, HostExec's kubectl dependency has been removed in https://github.com/kubernetes/kubernetes/pull/84444 (also added a method to replace ssh.SSH when necessary).

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/84042 was merged. As far as I know, this is resolved.

/close

**Comment by BenTheElder** [comment]
thank you!
