### ISSUE TITLE
Refactor etcd-version-monitor to use component-base metrics

### ISSUE THREAD

**Issue by conwaychriscosmo** [kubernetes/kubernetes#83917]
**What would you like to be added**:
Refactor etcd-version-monitor to use https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-base/metrics
**Why is this needed**:
This is part of a refactoring initiative run by @kubernetes/wg-component-standard to unify metrics dependencies.

/wg component-standard
@stealthybox 
@mtaufen

**Comment by hprateek43** [comment]
Your description is not descriptive enough. Can you be more verbose about the current limitations and what changes you are planning to do, along with some example to show the improvement ?

**Comment by mtaufen** [comment]
Now that util/metrics has been moved to component-base, folks are looking for places that depend directly on prometheus that should instead depend on util/metrics so we're using a standard metrics interface across the project.

@conwaychriscosmo is helping with this effort and identified etcd-version-monitor as a relatively small component with a direct prometheus dependency that they could start refactoring. 

AFAICT this would be in scope, but maybe @logicalhan @RainbowMango @yastij also have opinions?

**Comment by RainbowMango** [comment]
@mtaufen  @conwaychriscosmo 
Here is the PR that migrates etcd version monitor to component-base. https://github.com/kubernetes/kubernetes/pull/83283

The next iteration should after https://github.com/kubernetes/kubernetes/pull/83722.
