### ISSUE TITLE
CAPG e2e tests fail when running against kubernetes master

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#83923]
Found when trying to get CAPG e2e tests running against kubernetes master in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/214.

Essentially clusterctl is looking for providerID and not finding it in the `spec` (example https://pasted.tech/pastes/6e2ede088b103f9a3a501754245d8ba4ed962d4c.raw)

If i delete the node and restart kubelet then the providerID is set and clusterctl runs fine after that (example after restart https://pasted.tech/pastes/ea5462e29a813aa9765b93fe23449ebe376b42b8.raw)

Tried various versions of k/k builds from CI:
```
v1.17.0-alpha.1.10+54d49bd785ba6f  GOOD
v1.17.0-alpha.1.137+0c6ce58af9bd36 GOOD
v1.17.0-alpha.1.165+cb177dc6a10442 GOOD

v1.17.0-alpha.1.183+3f8f0a32fa980d BAD
v1.17.0-alpha.1.211+5c8d219dfe7179 BAD
v1.17.0-alpha.1.239+5ce75a873459ca BAD
```
(list of builds from https://gcsweb.k8s.io/gcs/kubernetes-release-dev/ci/?marker=ci%2fv1.17.0-alpha.1.165%2bcb177dc6a10442%2f)

Looks like the last good build was 165 and the first bad build was 183.

So the culprit is somewhere in between those two builds:
https://github.com/kubernetes/kubernetes/compare/cb177dc6a10442..3f8f0a32fa980d

**Comment by dims** [comment]
suspect number 1 is `EnsureNodeObject` from https://github.com/kubernetes/kubernetes/pull/83339

/assign @neolit123

**Comment by liggitt** [comment]
Reverted in https://github.com/kubernetes/kubernetes/pull/84012

Is this resolved?

**Comment by dims** [comment]
yes. the test grid is green - https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-stable-k8s-master

/close
