### ISSUE TITLE
HA cluster by kubeadm 1.16.0: controller manager restart exceptionally

### ISSUE THREAD

**Issue by Davidrjx** [kubernetes/kubernetes#83929]
**What happened**:
Overnight, a controller manager pod in HA cluster with three controlplane nodes had restarted once. two out of three controller manager contains weird logs resembles:
```
first:
I1014 12:53:42.155678       1 serving.go:319] Generated self-signed cert in-memory
I1014 12:53:42.822542       1 controllermanager.go:161] Version: v1.16.0
I1014 12:53:42.822961       1 secure_serving.go:123] Serving securely on 127.0.0.1:10257
I1014 12:53:42.823336       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
I1014 12:53:42.823373       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-controller-manager...
E1014 13:05:49.033649       1 leaderelection.go:330] error retrieving resource lock kube-system/kube-controller-manager: Get https://LB_VIP:16443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: unexpected EOF
E1014 23:03:24.697789       1 leaderelection.go:330] error retrieving resource lock kube-system/kube-controller-manager: Get https://LB_VIP:16443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: unexpected EOF
second:
I1014 14:32:30.132775       1 serving.go:319] Generated self-signed cert in-memory
I1014 14:32:30.568749       1 controllermanager.go:161] Version: v1.16.0
I1014 14:32:30.569440       1 secure_serving.go:123] Serving securely on 127.0.0.1:10257
I1014 14:32:30.570135       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
I1014 14:32:30.570198       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-controller-manager...
```
**What you expected to happen**:
When not deploying any applications, all controlplane component pods should be keeping normal state，namely no any restart but running
**How to reproduce it (as minimally and precisely as possible)**:
create a HA cluster with three controlplane node by kubeadm
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
bare metal
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`):
Linux **** 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
calico3.9.1 for policy and networking
- Others:
etcd 3.3.10
nginx loadbalancer applying VIP
coredns 1.6.2

**Comment by Davidrjx** [comment]
@kubernetes/sig-api-machinery-test-failures

**Comment by liggitt** [comment]
The logs from the first look like what I would expect if the connection between the controller manager and the apiserver was interrupted

The logs from the second look like what I would expect when the controller manager is waiting to acquire the lease.

Can you provide more information about the restart, or information that shows the controller manager cannot maintain a connection to the apiserver while other components from the same location can?

**Comment by neolit123** [comment]
i just saw single controller manager restart right after bootstrap of a 3CP HA 1.16 cluster:

from cm:
```
I1017 21:31:07.985703       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-controller-manager...
E1017 21:31:07.997698       1 leaderelection.go:330] error retrieving resource lock kube-system/kube-controller-manager: Get https://172.17.0.5:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: EOF
```

from api-server:
```
I1017 21:31:57.567130       1 controller.go:81] Starting OpenAPI AggregationController
I1017 21:31:57.571309       1 log.go:172] http: TLS handshake error from 172.17.0.5:59110: write tcp 172.17.0.7:6443->172.17.0.5:59110: write: connection reset by peer
I1017 21:31:57.571566       1 crd_finalizer.go:274] Starting CRDFinalizer
I1017 21:31:57.571843       1 autoregister_controller.go:140] Starting autoregister controller
I1017 21:31:57.571862       1 cache.go:32] Waiting for caches to sync for autoregister controller
I1017 21:31:57.572202       1 apiservice_controller.go:94] Starting APIServiceRegistrationController
I1017 21:31:57.572231       1 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I1017 21:31:57.576465       1 log.go:172] http: TLS handshake error from 172.17.0.5:59000: write tcp 172.17.0.7:6443->172.17.0.5:59000: write: connection reset by peer
I1017 21:31:57.576550       1 controller.go:85] Starting OpenAPI controller
```

> Overnight, a controller manager pod in HA cluster with three controlplane nodes had restarted once.

are you sure it happened after the cluster was running for a few hours?

**Comment by neolit123** [comment]
i ran a 1.16.0 HA cluster created with kubeadm for 24h and it saw no component restarts once all the components came up (see above).

@Davidrjx 
> Overnight, a controller manager pod in HA cluster with three controlplane nodes had restarted once.

please confirm if you are still seeing this.

**Comment by Davidrjx** [comment]
> i just saw single controller manager restart right after bootstrap of a 3CP HA 1.16 cluster:
> 
> from cm:
> 
> from api-server:
> 
> > Overnight, a controller manager pod in HA cluster with three controlplane nodes had restarted once.
> 
> are you sure it happened after the cluster was running for a few hours?
> 
> EDIT: i'm going to leave a cluster for 24h to see if the restart reappears.

yes, i am sure. Now, cluster health resembles below
```
calico-kube-controllers-b7fb7899c-7x5v2   1/1     Running   2          6d16h
calico-node-2nnkg                         1/1     Running   0          6d16h
calico-node-9gj5k                         1/1     Running   0          6d16h
calico-node-c4tkc                         1/1     Running   0          6d16h
calico-node-wmlcb                         1/1     Running   0          3d19h
calico-node-zgj8d                         1/1     Running   0          6d16h
calico-node-zsp67                         1/1     Running   0          6d16h
coredns-5644d7b6d9-fpj9p                  1/1     Running   0          6d16h
coredns-5644d7b6d9-gd7bm                  1/1     Running   0          6d16h
kube-apiserver-fuxi-dl-*1                 1/1     Running   0          6d16h
kube-apiserver-fuxi-dl-*2                 1/1     Running   0          6d16h
kube-apiserver-fuxi-dl-*3                 1/1     Running   0          6d16h
kube-controller-manager-fuxi-dl-*1        1/1     Running   2          6d16h
kube-controller-manager-fuxi-dl-*2        1/1     Running   1          6d16h
kube-controller-manager-fuxi-dl-*3        1/1     Running   0          6d16h
kube-proxy-4vg74                          1/1     Running   0          6d16h
kube-proxy-7prws                          1/1     Running   0          6d16h
kube-proxy-c9mg8                          1/1     Running   0          6d16h
kube-proxy-gs68z                          1/1     Running   0          3d19h
kube-proxy-hsst6                          1/1     Running   0          6d16h
kube-proxy-w2ncq                          1/1     Running   0          6d16h
kube-scheduler-fuxi-dl-*1                 1/1     Running   0          6d16h
kube-scheduler-fuxi-dl-*2                 1/1     Running   0          6d16h
kube-scheduler-fuxi-dl-*3                 1/1     Running   0          6d16h
```
after about a week, former two controller managers still had restarted.

**Comment by Davidrjx** [comment]
@neolit123 in my case, two out of three api servers logs recent error message, looks like below
```
08:17:27.823899       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 08:34:05.929978       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 08:44:04.981866       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 08:53:39.081481       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 09:07:13.112206       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 09:16:28.153087       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 09:25:15.205823       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1018 09:35:10.227176       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
I1020 16:44:45.220041       1 log.go:172] http: TLS handshake error from 10.90.*.*:41892: read tcp 10.90.*.*:6443->10.90.*.*:41892: read: connection reset by peer
```

**Comment by neolit123** [comment]
Hard to say without knowing what made the 41893 port connection. You can
increase the verbosity of the components using --v=x in their manifest
files.

**Comment by Davidrjx** [comment]
@neolit123 controller manager log verbose was changed to 4, two restarted ones restart count fall back to zero. through some period of time, again have a look if restart would exist yet

**Comment by Davidrjx** [comment]
@liggitt thanks,sorry for late reply. some log messages seem troubling if log verbose was little.
now, after verbose increased, a little clear about controller manager leader lease, like
```
I1022 08:56:50.845454       1 leaderelection.go:350] lock is held by fuxi-dl-*6_618202d8-fcd8-40a3-96f1-1d1c9212ca3a and has not yet expired
I1022 08:56:50.845483       1 leaderelection.go:246] failed to acquire lease kube-system/kube-controller-manager
I1022 08:56:53.252787       1 httplog.go:90] GET /healthz: (88.453µs) 200 [kube-probe/1.16 127.0.0.1:48308]
I1022 08:56:55.154445       1 leaderelection.go:350] lock is held by fuxi-dl-*6_618202d8-fcd8-40a3-96f1-1d1c9212ca3a and has not yet expired
I1022 08:56:55.154473       1 leaderelection.go:246] failed to acquire lease kube-system/kube-controller-manager
```
as restarted controller managers have restarted again, will observe for some time if new restart occurs

**Comment by tedyu** [comment]
@Davidrjx 
In the snippet you posted, the lock was held by 
fuxi-dl-*6_618202d8-fcd8-40a3-96f1-1d1c9212ca3a

Can you see if the lock holder was always the above ?

**Comment by Davidrjx** [comment]
@tedyu until now yes and ep lock is always held by above controller manager pod

**Comment by neolit123** [comment]
@Davidrjx 
what is the average restart rate at this point?
e.g. one restart every 3 days?

**Comment by Davidrjx** [comment]
> @Davidrjx
> what is the average restart rate at this point?
> e.g. one restart every 3 days?

hard to evaluate rate, just like  https://github.com/kubernetes/kubernetes/issues/83929#issuecomment-544353225, one or two restart occured before restarting/updating that two controller manager pods via adding log verbose flag.
After adding flag, there is no any restart so far, resembling
```
calico-kube-controllers-b7fb7899c-7x5v2   1/1     Running   2          8d
calico-node-2nnkg                         1/1     Running   0          8d
calico-node-9gj5k                         1/1     Running   0          8d
calico-node-c4tkc                         1/1     Running   0          8d
calico-node-wmlcb                         1/1     Running   0          5d15h
calico-node-zgj8d                         1/1     Running   0          8d
calico-node-zsp67                         1/1     Running   0          8d
coredns-5644d7b6d9-fpj9p                  1/1     Running   0          8d
coredns-5644d7b6d9-gd7bm                  1/1     Running   0          8d
kube-apiserver-fuxi-dl-*66                 1/1     Running   0          8d
kube-apiserver-fuxi-dl-*76                 1/1     Running   0          8d
kube-apiserver-fuxi-dl-*96                 1/1     Running   0          8d
(update)kube-controller-manager-fuxi-dl-*66        1/1     Running   0          18h 
(update)kube-controller-manager-fuxi-dl-*76        1/1     Running   0          18h
kube-controller-manager-fuxi-dl-*96        1/1     Running   0          8d
kube-proxy-4vg74                          1/1     Running   0          8d
kube-proxy-7prws                          1/1     Running   0          8d
kube-proxy-c9mg8                          1/1     Running   0          8d
kube-proxy-gs68z                          1/1     Running   0          5d15h
kube-proxy-hsst6                          1/1     Running   0          8d
kube-proxy-w2ncq                          1/1     Running   0          8d
kube-scheduler-fuxi-dl-*66                 1/1     Running   0          8d
kube-scheduler-fuxi-dl-*76                 1/1     Running   0          8d
kube-scheduler-fuxi-dl-*96                 1/1     Running   0          8d
```

**Comment by neolit123** [comment]
> After adding flag, there is no any restart so far, resembling

the --v flag?

**Comment by Davidrjx** [comment]
> > After adding flag, there is no any restart so far, resembling
> 
> the --v flag?

yes

**Comment by neolit123** [comment]
the addition of the --v flag does not affect the behaviour of the component.

**Comment by riking** [comment]
> after about a week, former two controller managers still had restarted.

> kube-controller-manager-fuxi-dl-*1        1/1     Running   2          6d16h
> kube-controller-manager-fuxi-dl-*2        1/1     Running   1          6d16h
> kube-controller-manager-fuxi-dl-*3        1/1     Running   0          6d16h

The fact that they have accumulated restarts is not actually a problem here. 2 into 2 is not a problem, 0 into 2 is.

The restart count was not improved by the flag flip, instead it was reset (to 0) by your update.

**Comment by Davidrjx** [comment]
@riking yes

**Comment by Davidrjx** [comment]
@neolit123 you are right,thanks

**Comment by neolit123** [comment]
/close

@Davidrjx please reopen if needed.
