### ISSUE TITLE
Scheduler perf test times out

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#83927]
I ran the perf test as follows:

```make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-run=^$$ -bench=BenchmarkScheduling/5000Nodes/1000Pods" ```

but after 11m it times out and fails with the following message:

*** Test killed with quit: ran too long (11m0s).

/sig scheduling
/assign @draveness

**Comment by ahg-g** [comment]
Hi @draveness , since you worked on the perf tests not long time ago, do you have any idea what is going on?

**Comment by draveness** [comment]
> Hi @draveness , since you worked on the perf tests not long time ago, do you have any idea what is going on?

Not sure, but I could take a look.

**Comment by ahg-g** [comment]
Thanks

> > Hi @draveness , since you worked on the perf tests not long time ago, do you have any idea what is going on?
> 
> Not sure, but I could take a look.

That would be great, thanks.

**Comment by ahg-g** [comment]
It seems that the test is stuck in the following for loop, it is trying to list the pods, but nothing is returned: https://github.com/kubernetes/kubernetes/blob/63bd1d7a5cda357f2d292a62dcbd6487852fc236/test/integration/scheduler_perf/scheduler_bench_test.go#L383

The logs show that the scheduler is working fine, there are scheduler logs indicating that all the "setup" pods were bounded, and so it seems the scheduler informer is working fine, but the one the test is using to list the pods is not!!

**Comment by ahg-g** [comment]
ok, I found the difference: the podinformer the test uses to check the status is created with a filter: https://github.com/kubernetes/kubernetes/blob/63bd1d7a5cda357f2d292a62dcbd6487852fc236/test/integration/scheduler_perf/scheduler_bench_test.go#L367

while the scheduler is created without one:
https://github.com/kubernetes/kubernetes/blob/63bd1d7a5cda357f2d292a62dcbd6487852fc236/test/integration/util/util.go#L106

**Comment by draveness** [comment]
> ok, I found the difference: the podinformer the test uses to check the status is created with a filter:

https://github.com/kubernetes/kubernetes/pull/80697 introduced this problem. I found this issue too and trying to fix this.
