### ISSUE TITLE
refactor test/e2e/common

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#83937]
**What would you like to be added**:

`test/e2e/common` is a mixture of tests (`test/e2e/common/downward_api.go`) and utility code (`test/e2e/common/events.go`). It would be nice to refactor it so that the utility code can be imported without also importing the tests. Most likely a better place for the utility code is under `test/e2e/framework`.

**Why is this needed**:

The specific reason was the usage of `WaitTimeoutForEvent` in a storage test, which then made it impossible to import the storage tests without those other tests. See https://github.com/kubernetes/kubernetes/pull/83609. Once `WaitTimeoutForEvent` is in an independent utility package, the copied `waitTimeoutForEvent` can be removed from `test/e2e/storage/testsuites/volumemode.go` again.

/sig testing

**Comment by alejandrox1** [comment]
/priority important-longterm
/lifecycle active
@danielqsj has been working on it
