### ISSUE TITLE
Organize packages inside pkg/cloudprovider

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#8394]
The packages directly inside `pkg/cloudprovider` seem to be of the following categories:

* Cloud provider plugins:
 * aws
 * fake
 * gce
 * mesos
 * openstack
 * ovirt
 * rackspace
 * vagrant
 * cloud.go - plugin interface
 * plugins.go - plugin initialization
* Controllers that sync data from cloud providers:
 * nodecontroller
 * servicecontroller

I propose that either we move everything plugin related into `pkg/cloudprovider/plugins` so that every subpackage represents a plugin, or move the controllers out of `pkg/cloudprovider` and into a dedicated  `pkg/cloudprovider/controllers` (unless there's a better place for them), or both. I think I prefer doing both.

This mostly stems from me being confused for a while as to how "nodecontroller" could be a cloudprovider.

If there's no objection I'm happy to make the PR for this, but wanted to see if I was missing something or if there was opposition first.

**Comment by derekwaynecarr** [comment]
Should we just move the plugins into the same plugin directory that holds scheduler and admission control handlers?

**Comment by thockin** [comment]
On Sun, May 17, 2015 at 12:33 AM, Sam Ghods <notifications@github.com> wrote:
>
> The packages directly inside pkg/cloudprovider seem to be of the following categories:
>
> Cloud provider plugins:
>
> aws
> fake
> gce
> mesos
> openstack
> ovirt
> rackspace
> vagrant
> cloud.go - plugin interface
> plugins.go - plugin initialization
>
> Controllers that sync data from cloud providers:
>
> nodecontroller
> servicecontroller

I don't see why the controllers should live under cloudprovider.
That's not the intent, as I understand it.

> I propose that either we move everything plugin related into pkg/cloudprovider/plugins so that every subpackage represents a plugin, or move the controllers out of pkg/cloudprovider and into a dedicated pkg/cloudprovider/controllers (unless there's a better place for them), or both. I think I prefer doing both.

I propose pkg/controller/*

> This mostly stems from me being confused for a while as to how "nodecontroller" could be a cloudprovider.
>
> If there's no objection I'm happy to make the PR for this, but wanted to see if I was missing something or if there was opposition first.

I think we want to do a LOT of these moves, so deferred them until after 1.0

**Comment by a-robinson** [comment]
+1, these belong elsewhere, there just hasn't been an urgent need to do so

**Comment by ghodss** [comment]
Fixed by #12403
