### ISSUE TITLE
help me kubeadm install 1.16.1 kubectl get cs scheduler <unknown> 

### ISSUE THREAD

**Issue by andy199** [kubernetes/kubernetes#83943]
[root@k8s-master01 ~]# kubectl get cs
NAME                 AGE
controller-manager   <unknown>
scheduler            <unknown>
etcd-0               <unknown>

**Comment by neolit123** [comment]
instead of using `kubectl get cs` look at `kubectl get po -A` and check the status of your control-plane pods. there was a proposal to deprecate `cs` (ComponentStatus) at some point.

thanks
/remove-kind bug
/triage support
/close
