### ISSUE TITLE
[Stale Test] Conformance Openstack (ci-cloud-provider-openstack-acceptance-test-e2e-conformance)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#83947]
**Which jobs are staling**:
Conformance Openstack (ci-cloud-provider-openstack-acceptance-test-e2e-conformance)

The last run was on 11 Oct

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Comment by ramineni** [comment]
@droslean we have been seeing multiple issues in the past week. we have fixed various issues related to kubetest biuild, go version etc https://github.com/theopenlab/openlab-zuul-jobs/pull/678 , https://github.com/theopenlab/openlab-zuul-jobs/pull/679 , one more fix in progress, https://github.com/theopenlab/openlab-zuul-jobs/pull/682  , hopefully should be resolved soon.

**Comment by ramineni** [comment]
https://github.com/kubernetes/kubernetes/issues/83985 , need this to get the CI fixed.

**Comment by droslean** [comment]
https://github.com/kubernetes/kubernetes/pull/84008

**Comment by droslean** [comment]
https://github.com/theopenlab/openlab-zuul-jobs/pull/684 is needed also.

**Comment by droslean** [comment]
/close
all required PRs merged. The job is passing now. 
https://k8s-testgrid.appspot.com/sig-release-master-informing#Conformance%20-%20OpenStack
