### ISSUE TITLE
TestServiceRegistryIPUpdate: Incorrect test in pkg/registry/service/rest_test.go (1 in 256 chance)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8397]
We used to disable randomization for IP allocation for services in the tests, but we don't any more.

I think this test: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/service/rest_test.go#L642-L649

is checking that changing the portalIP fails.

However, I believe that if we happen to be allocated .76, then it will succeed.

(Yes, I actually hit this!)

**Comment by ihmccreery** [comment]
Based on work done so far, I'm reassigning to `team/node`.

**Comment by yujuhong** [comment]
This is not a node team issue, but the issue itself is probably too old to have any value. Closing it.
