### ISSUE TITLE
the k8s-app label in /cluster addons should be disallowed

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#83977]
please, see:
https://github.com/kubernetes/enhancements/issues/1314
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190916-noderestriction-pods.md

> The Kubelet does not currently label pods, nor are there official label keys that apply to pods. However, there are a few labels that are commonly applied to system addons & static pods:
> ...
> The k8s-app label is used to match controllers for system components, and therefore should be explicitly disallowed.

the feature gate MirrorPodNodeRestriction is being added in 1.17 and will be on by default in 1.19.

/sig cluster-lifecycle
/sig cloud-provider
/area test
/kind feature
/priority important-longterm

cc @tallclair @MrHohn @cheftako @justinsb @BenTheElder
can you please help find an owner for this work?
without modifying the /cluster addons WRT the `k8s-app` label, probably a number of gce/gcp e2e tests will fail.

a temporary solution would be to have  MirrorPodNodeRestriction off until it's GA, but ideally this should be resolved on the manifest level.

**Comment by BenTheElder** [comment]
I'm somewhat inclined to suggest @tallclair -- I feel like https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190916-noderestriction-pods.md#label-restrictions should also mention updating kube-up (also, does kops need anything? @justinsb)

**Comment by neolit123** [comment]
> also, does kops need anything? @justinsb

https://github.com/kubernetes/kops/search?q=%22k8s-app%22&unscoped_q=%22k8s-app%22

i remembered that kops is also a user of `k8s-app`. also kubeadm has it in it's upgrade process.

hound search:
https://cs.k8s.io/?q=%22k8s-app%22&i=nope&files=&repos=

**Comment by neolit123** [comment]
> the feature gate MirrorPodNodeRestriction is being added in 1.17 and will be on by default in 1.19.

look like planned for GA for 1.20 for https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190916-noderestriction-pods.md#graduation-criteria

> without modifying the /cluster addons WRT the k8s-app label, probably a number of gce/gcp e2e tests will fail.

surprisingly this did not happen. a number of addons still have this :thinking: :
https://github.com/kubernetes/kubernetes/search?q=%22k8s-app%22&unscoped_q=%22k8s-app%22

/remove-sig cluster-lifecycle
/sig cloud-provider
/area provider/gcp

/remove-lifecycle frozen
(removing so that the bot reminds about this)

**Comment by tallclair** [comment]
The proposal was to allowlist labels using a special annotation on the namespace, but this created a bootstrap problem mirror pods in kube-system, hence the change never went through. I haven't come up with a better proposal yet, though I'm leaning towards the original idea to just you a hardcoded allowed prefix.

**Comment by pacoxu** [comment]
/reopen

> The proposal was to allowlist labels using a special annotation on the namespace, but this created a bootstrap problem mirror pods in kube-system, hence the change never went through. I haven't come up with a better proposal yet, though I'm leaning towards the original idea to just you a hardcoded allowed prefix.

This seems to be a chicken-egg problem. 
How about just hardcode the default allow list of kube-system? 
- For kube cluster installer, it can change the namespace annotation to the correct one during upgrade or init.
