### ISSUE TITLE
hack/local-up-cluster.sh fails if HOSTNAME_OVERRIDE is set

### ISSUE THREAD

**Issue by ramineni** [kubernetes/kubernetes#83985]
**Which jobs are failing**:
cloud-provider-openstack jobs

**Which test(s) are failing**:
hack/local-up-cluster.sh itself fails.

**Since when has it been failing**:
Recent change https://github.com/kubernetes/kubernetes/pull/82413 , checks for node ready by doing a grep of KUBELET_HOST. But when HOSTNAME_OVERRIDE is set , its unable to find the ip and exits.

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by zouyee** [comment]
@kubernetes/sig-cloud-provider-test-failures

**Comment by notpad** [comment]
Repalce KUBELET_HOST with HOSTNAME_OVERRIDE shoud fix this issue, I have created a pull request

**Comment by ramineni** [comment]
@notpad Thanks. But what if HOSTNAME_OVERRIDE is not set , then again it would fail? I guess its optional parameter

**Comment by ramineni** [comment]
cc @zhlhahaha

**Comment by notpad** [comment]
If not set, the default value is 127.0.0.1, won't fail

**Comment by zhlhahaha** [comment]
Hi ramineni, nodpad is correct. HOSTNAME_OVERRIDE do have default value which is 127.0.0.1.

**Comment by ramineni** [comment]
@notpad @zhlhahaha Thanks. Then grep HOSTNAME_OVERRIDE is ideal solution. That would work for me. Hopefully PR gets merged soon
