### ISSUE TITLE
Enhance for loops of ViewHistorys

### ISSUE THREAD

**Issue by whs-dot-hk** [kubernetes/kubernetes#83984]
**What would you like to be added**:
https://github.com/kubernetes/kubernetes/blob/4568c615269860433f914e1dc74b13e66acbe5ef/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/history.go#L118

When revision > 0
we could break out of the for loop
once we got the info

**Why is this needed**:
Finish faster

/sig cli

**Comment by ZP-AlwaysWin** [comment]
I don't quite understand what you mean. The reason for the loop is that even if revision > 0, you need to traverse the history details.

**Comment by whs-dot-hk** [comment]
Hi, I mean

```
for all rs
  v is the revision return from deploymentutil.Revision
  // keep the logic
  if revision supplied in argument > 0 and v == revision
    break
  endif
endfor
```

**Comment by zhouya0** [comment]
I think it's ok to do break for the loop.  Because the the function will return the specfic info when revision >0.
https://github.com/kubernetes/kubernetes/blob/4568c615269860433f914e1dc74b13e66acbe5ef/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/history.go#L137-L145

**Comment by ZP-AlwaysWin** [comment]
It seems like a good idea. You can try to optimize it.

**Comment by whs-dot-hk** [comment]
> It seems like a good idea. You can try to optimize it.

Thx

**Comment by whs-dot-hk** [comment]
Hi, done
