### ISSUE TITLE
Using Cloud Storage classes on a on-prem kubeadm installation

### ISSUE THREAD

**Issue by Atharex** [kubernetes/kubernetes#83991]
Guess this is just a documentation question...

https://kubernetes.io/docs/concepts/storage/storage-classes/

Are the cloud storage classes (in my case I'm trying Azure-File) possible to use on-prem or are they only supported when the Virtual Machines fully live in the cloud infrastructure (Azure Cloud)?

**Comment by zouyee** [comment]
There is no difference in use.

**Comment by Atharex** [comment]
The docs state:

`If a storage account is provided, it must reside in the same resource group as the cluster, and skuName and location are ignored.`

This means to me that it would only work when both the k8s nodes and the storage account are in  Azure and more specifically both in the same resource group. Which would be impossible when on-prem.

@zouyee how does this make it no difference in use?

**Comment by Atharex** [comment]
Looking also at the provider docs:
https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md

The config I would need to set up on all k8s nodes is very "cloud-resources" specific:
```
...
- vnetName | The name of the VNet that the cluster is deployed in 
- vnetResourceGroup | The name of the resource group that the Vnet is deployed in  
- subnetName | The name of the subnet that the cluster is deployed in 
- securityGroupName | The name of the security group attached to the cluster's subnet 
...
```
On prem I would not use any of these Azure resources, but would only want to connect to an existing storage account within a resource group, with no other resources.
