### ISSUE TITLE
API Server Should NOT Accept Resource Requests Before Cacher is Ready

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#83997]
**What would you like to be added**:

API Server should NOT accept resource requests before Cacher is ready, but should response 429 code when Cacher is not ready.

**Why is this needed**:

In our production env, when API Server restart and Cacher is not ready, clients(kubelet, DaemonSets, etc.) send too many requests. Especially too many `LIST` resource requests from informer, which will full network bandwidth between API Server and etcd. Then Cacher will not be ready for a very long time, what's worse,  which will make API Server OOM because it is preparing too many response body but can not get response data from etcd.

I think API Server should response 429 when its Cacher is not ready.

https://github.com/kubernetes/kubernetes/blob/f64c631cd7aea58d2552ae2038c1225067d30dde/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L681-L685

https://github.com/kubernetes/kubernetes/blob/f64c631cd7aea58d2552ae2038c1225067d30dde/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L551-L555

**Comment by fedebongio** [comment]
/assign @wojtek-t 
Thought you will be interested in this one

**Comment by liggitt** [comment]
as an optimization layer, it doesn't seem proper for the cacher to deny serving requests

if we consider the cacher so essential that the server should not be placed into rotation until it is populated, we could consider making it part of the readiness check

**Comment by answer1991** [comment]
@liggitt thanks for your reply.

> if we consider the cacher so essential that the server should not be placed into rotation until it is populated, we could consider making it part of the readiness check

Yes, remind me of #83745. API Server should not accept request before Cacher is ready, we should not add API Server as a backend of LoadBalance before its Cacher is ready. Because Authn will make API Server call etcd frequently before API Server informer is ready.

Have we implemented `/readyz` for now?

**Comment by ricky1993** [comment]
In our scenario, we have implemented the feature @answer1991  mentioned above for avoiding 5k kubelet List pod request penetrating to the etcd.
But I think it's just a workaround way. /readyz and request priority & fairness feature would be more graceful.
