### ISSUE TITLE
'CHANGE-CAUSE' field of the deployment rollout history is '<none>'

### ISSUE THREAD

**Issue by OPSTime** [kubernetes/kubernetes#83990]
**Version：**

> $ sudo kubectl version
> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> 

**1、'CHANGE-CAUSE' field of the deployment rollout history is '<none>'**
 **As follows：**
> $ kubectl apply -f d.yml       
> deployment.apps/nginx-deployment created
> 
> $ kubectl get deployments -o wide
> NAME               READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES        SELECTOR
> nginx-deployment   3/3     3            3           26s   nginx        nginx:1.7.9   app=nginx
> 
> 
> $ kubectl set image deployment nginx-deployment nginx=nginx:1.17.1
> deployment.extensions/nginx-deployment image updated
> 
> $ kubectl rollout history  deployment nginx-deployment 
> deployment.extensions/nginx-deployment 
> REVISION  CHANGE-CAUSE
> 1         \<none\>
> 2         \<none\>
> 
> $ kubectl get deployments -o wide                      
> NAME               READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES         SELECTOR
> nginx-deployment   3/3     3            3           103s   nginx        nginx:1.17.1   app=nginx
> 
> $ kubectl set image deployment nginx-deployment nginx=nginx:1.15.6
> deployment.extensions/nginx-deployment image updated
> 
> $ kubectl rollout history  deployment nginx-deployment 
> deployment.extensions/nginx-deployment 
> REVISION  CHANGE-CAUSE
> 1         \<none\>
> 2         \<none\>
> 3         \<none\>
> 
> $ kubectl get deployments -o wide                      
> NAME               READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES         SELECTOR
> nginx-deployment   3/3     3            3           2m5s   nginx        nginx:1.15.6   app=nginx
> 
> $ kubectl rollout undo deployment nginx-deployment
> deployment.extensions/nginx-deployment rolled back
> 
> $ kubectl rollout history  deployment nginx-deployment 
> deployment.extensions/nginx-deployment 
> REVISION  CHANGE-CAUSE
> 1         \<none\>
> 3         \<none\>
> 4         \<none\>
> 
> $ kubectl get deployments -o wide                      
> NAME               READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS   IMAGES         SELECTOR
> nginx-deployment   3/3     3            3           3m11s   nginx        nginx:1.17.1   app=nginx
> 

**2、"kubectl top" display error:**

> $ kubectl get cs
> NAME                 STATUS    MESSAGE             ERROR
> scheduler            Healthy   ok                  
> controller-manager   Healthy   ok                  
> etcd-2               Healthy   {"health":"true"}   
> etcd-0               Healthy   {"health":"true"}   
> etcd-1               Healthy   {"health":"true"}   
> $ kubectl top node        
> Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
> $ kubectl top pod --all-namespaces
> Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)

**Comment by zouyee** [comment]
add flag  `--record=true`
```
kubectl set image deployment --record=true -n 63d20405-0b5b-42d1-88b6-ac7916791e02 backdemo backdemo=nginx:1.17.3
kubectl rollout history -n 63d20405-0b5b-42d1-88b6-ac7916791e02 deploy backdemo
```

**Comment by OPSTime** [comment]
Thank you
