### ISSUE TITLE
API Server Cost too much in runtime.findrunnable, We Need to Reduce API Server Goruntine

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#84001]
**What would you like to be added**:

We need to reduce API Server goruntine, I think there are many ways to reduce API Server goruntine, such as:
1. Make API Server processing request full-stack context-aware, then try to remove timeout filter.
2. kubelet can list/watch ConfigMap/Secret(s) that the all Node's Pods needed from a single watch request, but not each ConfigMap/Secret need one watch request.

**Why is this needed**:

In our environment, if API Server has more then 300k goruntine, then API Server will cost too much CPU in runtime.findrunnable. Please see the follow graph we got from our environment:

![image](https://user-images.githubusercontent.com/2566352/66915077-be273f00-f04a-11e9-876f-85741879e87e.png)

**Comment by fedebongio** [comment]
/cc @lavalamp @wojtek-t 
Thought you might be interested since you've been digging into related issue

**Comment by lavalamp** [comment]
at 300k goroutines you probably actually have a leak.

See https://github.com/kubernetes/kubernetes/pull/83333 for a recently fixed leak.

**Comment by lavalamp** [comment]
For reference, I think a reasonable number of goroutines for a big, heavily loaded cluster is ~50k. Above that something is wrong.

**Comment by lavalamp** [comment]
And https://github.com/kubernetes/kubernetes/pull/80465 is one possible thing that could trigger leaking timeouts.

**Comment by answer1991** [comment]
@lavalamp Thanks for your reply.

I had already picked #83333 and #80465  to our environment. 

I do not think API Server still leaking goruntines, because our API Server should process about 200k+ request in every minutes and has more than 300k+ watches. And we had already set most pods `autoAmountServiceAccount` to be `false`, or more watches will be connected between API Server and kubelet. Please see more detail graph below:

* response codes in every minute

![image](https://user-images.githubusercontent.com/2566352/67062868-44509c00-f197-11e9-8429-d82526a9258d.png)

* watches by resource name

![image](https://user-images.githubusercontent.com/2566352/67062921-77932b00-f197-11e9-8954-3b290b68f3c8.png)

* API Server goruntines (we had scale API Server replica to be 5 to avoid goruntine schedule performance issue)

![image](https://user-images.githubusercontent.com/2566352/67063025-c771f200-f197-11e9-81f1-4651743632bd.png)

**Comment by wojtek-t** [comment]
I agree that in large enough clusters hundreds of thousands of goroutines is WAI.
And this is mostly coming from the fact that there are IIRC 3 goroutines per watch request:
- the main one processing the request
- per watcher one in cacher: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L523
- CloseNotify from here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/watch.go#L219

> kubelet can list/watch ConfigMap/Secret(s) that the all Node's Pods needed from a single watch request, but not each ConfigMap/Secret need one watch request.

i used to have a design proposal for bulk watch:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/bulk_watch.md
but I no longer think that is what we want. It would introduce a lot of complications.


I was thinking about that in the past, and actually I believe the solution should be different. I wanted to write a KEP about it for quite some time, but never got to it (I may try to do that in upcoming weeks). At the high level, i think that what we should do is:
- IIUC, we're basically recommending to not update secrets/configmaps - instead what we're recommending is to create a new one and do a rolling update to the new one
- with that approach, I think that we should allow for switching off auto-updates of secrets/configmaps for running pods
- with that feature, users will be able to switch it off (which will result in non-watching secrets/configmaps from apiserver - just the initial get will be send)

I will try to write down the KEP for it next week (unless someone will object in the meantime).

**Comment by lavalamp** [comment]
If you have any websocket watchers, I think it's worth the experiment to pick this (or search in your logs for the message it prints when it leaks): https://github.com/kubernetes/kubernetes/pull/84693

**Comment by wojtek-t** [comment]
And regarding watches from Secrets/ConfigMap - this KEP is supposed to help with it: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20191117-immutable-ephemeral-volumes.md

**Comment by answer1991** [comment]
> And regarding watches from Secrets/ConfigMap - this KEP is supposed to help with it: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20191117-immutable-ephemeral-volumes.md

@wojtek-t Many thanks for your excellent work. Can not wait to cherry-pick this new feature to our environment.

**Comment by riking** [comment]
All mentioned PRs are closed - is this still a problem?

**Comment by answer1991** [comment]
When I opened this issue, we have not solved the API Server load balance issue, and one or two of API Server serve most requests and their goroutine will be too much. With this #88567 merged, we can balance API Servers' request and horizontal increase API Servers' replica will be a solution.
