### ISSUE TITLE
[Failing test] GCE master, dev {ci-kubernetes-gce-conformance-latest} 

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#84004]
**Which jobs are failing**:
GCE master, dev {ci-kubernetes-gce-conformance-latest} 

**Which test(s) are failing**:
```
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset [Conformance]
```
**Since when has it been failing**:
16/10

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#GCE,%20master%20(dev)

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:691
Oct 16 11:37:13.010: Pod ss-0 expected to be re-created at least once
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/statefulset.go:742
```
**Anything else we need to know**:
https://github.com/kubernetes/kubernetes/compare/f64c631cd...d87403c2f?

**Comment by hasheddan** [comment]
It looks like this is failing [here](https://github.com/kubernetes/kubernetes/blob/129a13af983fe2b6bd4429c47e5f0cde6bf0ca42/test/e2e/apps/statefulset.go#L726). I wonder if it may be useful to replace [`UntilWithoutRetry`](https://github.com/kubernetes/kubernetes/blob/129a13af983fe2b6bd4429c47e5f0cde6bf0ca42/staging/src/k8s.io/client-go/tools/watch/until.go#L58) with either `Until` or `UntilWithSync`? Would need further context from someone who is more familiar though.

**Comment by droslean** [comment]
The next runs have completed successfully.

**Comment by hasheddan** [comment]
@droslean This popped up again today (15:58 PDT), do you think it is worth reopening?

**Comment by droslean** [comment]
Let's reopen the issue and try to observe the job. It would be better to understand if this job flakes, and how to resolve it.

**Comment by hasheddan** [comment]
I looked into it a little bit above https://github.com/kubernetes/kubernetes/issues/84004#issuecomment-542696587 but not sure if I am correct. Maybe @janetkuo would have some insight?

**Comment by droslean** [comment]
well the job is running every 3 hours and the flakes are really rare. 
I would be happy to improve that situation and have 0 flakes but until then there is no need to have this issue opened, since this was related to falling one and not the flakes.

I am closing this issue. If we need to monitor the flakes we should do it in a different issue.

/close
