### ISSUE TITLE
Allow customizable TTL for NewCachedDiscoveryClientForConfig

### ISSUE THREAD

**Issue by shanmugh** [kubernetes/kubernetes#84013]
**What would you like to be added**:
Ability to customize the discovery cache refresh interval in client-go.

**Why is this needed**:
Currently the disk cache for the client-go discovery cache uses a fixed TTL of [10mins](https://github.com/kubernetes/kubernetes/blob/30c7df5cd822067016640aa267714204ac089172/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L235). The cache refresh triggers a lot of requests to the API server even if the server has not been updated in a while. This becomes a problem when using a Kerberos based authentication mechanism that increase the load on the KDC every time the cache refresh is triggered.

**Comment by shanmugh** [comment]
@kubernetes/sig-cli

**Comment by tedyu** [comment]
Thinking of something like the following:
```
diff --git a/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go b/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
index 34b1f8e3a0..3aa7caecc3 100644
--- a/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
+++ b/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
@@ -100,7 +100,8 @@ type ConfigFlags struct {
        // If set to true, will use persistent client config and
        // propagate the config to the places that need it, rather than
        // loading the config multiple times
-       usePersistentConfig bool
+       usePersistentConfig     bool
+       discoveryClientCacheTTL int
 }

 // ToRESTConfig implements RESTClientGetter.
@@ -232,7 +233,7 @@ func (f *ConfigFlags) ToDiscoveryClient() (discovery.CachedDiscoveryInterface, e
        }

        discoveryCacheDir := computeDiscoverCacheDir(filepath.Join(homedir.HomeDir(), ".kube", "cache", "discovery"), config.Host)
-       return diskcached.NewCachedDiscoveryClientForConfig(config, discoveryCacheDir, httpCacheDir, time.Duration(10*time.Minute))
+       return diskcached.NewCachedDiscoveryClientForConfig(config, discoveryCacheDir, httpCacheDir, time.Duration(time.Minute*f.discoveryClientCacheTTL))
 }

 // ToRESTMapper returns a mapper.
@@ -337,6 +338,7 @@ func NewConfigFlags(usePersistentConfig bool) *ConfigFlags {
                ImpersonateGroup: &impersonateGroup,

                usePersistentConfig: usePersistentConfig,
+               discoveryClientCacheTTL: 10,
        }
 }
```

**Comment by shanmugh** [comment]
@tedyu thanks for the quick response.

Am I correct in assuming that this will allow the value to be configurable via kubeconfig?

**Comment by neolit123** [comment]
> Currently the disk cache for the client-go discovery cache uses a fixed TTL of 10mins. The cache refresh triggers a lot of requests to the API server even if the server has not been updated in a while. This becomes a problem when using a Kerberos based authentication mechanism that increase the load on the KDC every time the cache refresh is triggered.

client-go does not use the code you mention. it's in the cli-runtime library that is used by kubectl:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L466

> Am I correct in assuming that this will allow the value to be configurable via kubeconfig?

it would not be possible to configure this via a kubeconfig as the underlying kubeconfig structure does not have TTL:
https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/api/types.go

if you wish to expose this on the kubectl command line side then the patch from @tedyu also needs to expose a command line flag:
https://github.com/kubernetes/kubernetes/blob/30c7df5cd822067016640aa267714204ac089172/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L306

there is already a Timeout field, so i'm not sure why it's not used for:
https://github.com/kubernetes/kubernetes/blob/30c7df5cd822067016640aa267714204ac089172/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L235

**Comment by shanmugh** [comment]
@neolit123 thanks for the information.

It would be ideal to configure the ttl via kubeconfig. Do you think this approach is feasible and easy to accomplish?

**Comment by neolit123** [comment]
possibly best to ask in the #sig-cli channel on slack.

**Comment by pwittrock** [comment]
IIRC, this is in the api machinery layer.

@apelisse can you confirm and maybe give a pointer?

**Comment by apelisse** [comment]
Assuming that the problem we're trying to fix is mostly through kubectl usage rather than client-go, I think @tedyu has the best approach to this, and I think I'd be fine reviewing a pull-request going in that direction. This means we would have a new kubectl argument to set the time-out period for the discovery.

People using client-go can already invoke `NewCachedDiscoveryClientForConfig` with the proper timeout value, so I think this is not the problem we're trying to fix.

I agree that having this value in kubeconfig would be ideal, but I don't see any chance that this would ever happen ...
