### ISSUE TITLE
New branch for Ingress v1 API

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes#84026]
SIG-Network is requesting a new branch off of of master to safely iterate on the Ingress v1 API. Without this branch, we risk merging v1 api work into the release without completing all of the options mentioned in our [Ingress KEP](https://github.com/kubernetes/enhancements/pull/1113). 

This new branch will serve to collect our WIP PRs  ( i.e.  #83467 and #80179) and allow for parallel contributions from the community. We have a small working group committed to iterating quickly on the remaining items in the KEP, but the branch will safeguard the unlikely case that we do not incorporate all GA criteria for the current release.

/sig release
/sig testing

**Comment by justaugustus** [comment]
(to document decision:)
/assign

**Comment by justaugustus** [comment]
For Ingress v1, [we decided](https://kubernetes.slack.com/archives/C2C40FMNF/p1572630581112700?thread_ts=1572482976.040000&cid=C2C40FMNF) that based on the timeline, it'd made sense for this to be a contributor-owned fork w/ the rest of the team added as collaborators

For the broader discussion on feature branches/forks, see this issue: https://github.com/kubernetes/kubernetes/issues/85892
/close
