### ISSUE TITLE
Accessing service is too much slower than accessing inside container

### ISSUE THREAD

**Issue by leowucn** [kubernetes/kubernetes#84033]
I have a k8s cluster, and the version of k8s is **v1.12.1**. One of the services is below:
```
NAME            TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/flask   NodePort   10.99.101.226   <none>        8090:32010/TCP   15h
```
When accessing the service with `CLUSTER-IP` inside the cluster, it is very slow compared to accessing inside the pod container.
```
curl  10.99.101.226:8090/test_json > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2316k  100 2316k    0     0   263k      0  0:00:08  0:00:08 --:--:--  216k
```
```
kubectl exec -it flask-example-77dbd59654-2g857 -- sh
/app # curl localhost:8090/test_json > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2316k  100 2316k    0     0  75.3M      0 --:--:-- --:--:-- --:--:-- 75.3M
```

The former speed is only **216K**, but the latter speed can up to **75.3M**, I wonder to know what cause the difference.

Is there anyone can help me? thanks.

**Comment by neolit123** [comment]
> I have a k8s cluster, and the version of k8s is v1.12.1. One of the services is below:

hi, 1.12 is no longer supported by the k8s project.
please try reproducing this with 1.14 at least (which is in the support skew).

/triage needs-information
/sig network
