### ISSUE TITLE
Proposal: nested namespaces

### ISSUE THREAD

**Issue by shaunc** [kubernetes/kubernetes#84057]
/sig architecture

**What would you like to be added**:

I would like namespaces to be nestable.

**Why is this needed**:

I am learning Kubernetes, Istio, and Kubeflow, hoping to be able to recommend Kubeflow as a component of an overall application built on KNative. Unfortunately, I have had problems installing Kubeflow, and once one problem is hit, it is very difficult to recover as it creates dependencies it doesn't clean up. The problem is that it is difficult for it to know what it installed, as the cluster may or may not have previously installed dependencies.

I would suspect this is just the tip of the iceberg. When running more than one application in a cluster (which is, after all, much more efficient than running separate clusters), there will always be conflicts such as this. Best would be to have each application install its dependencies in sub-namespaces. Optionally, to share resources, sub-namespaces could be links.

Down the line, a nested name spacing system would allow dependency injection tools to consolidate resources (or not) based on tags.

**Comment by liggitt** [comment]
Thanks for the feature request, but this is effectively requesting restructuring the entire Kubernetes API, and is unlikely to make progress as an issue. A proposal that works through the design along with the implications of such a change (which are numerous) can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps).

/close

**Comment by k82cn** [comment]
xref  [volcano](https://github.com/volcano-sh/volcano) & [kube-batch](https://github.com/kubernetes-sigs/kube-batch) :)

**Comment by cupdike** [comment]
Hierarchical namespaces are now available as an extension:  
https://kubernetes.io/blog/2020/08/14/introducing-hierarchical-namespaces/
