### ISSUE TITLE
pkg/storage/etcd3/event.go still using old etcd url

### ISSUE THREAD

**Issue by sbussetti** [kubernetes/kubernetes#84053]
Attempting to run tests against a project using `k8s.io/apiserver` and run into the following:

```
# ...vendor/k8s.io/apiserver/pkg/storage/etcd3
vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:183:23: cannot use kv (type *".../vendor/go.etcd.io/etcd/mvcc/mvccpb".KeyValue) as type *".../vendor/github.com/coreos/etcd/mvcc/mvccpb".KeyValue in argument to parseKV
```

It looks like the imports referenced just need to change to the new etcd url.

**Comment by tedyu** [comment]
pkg/storage/etcd3/event.go : there is no such file in kubernetes repo.

FYI

**Comment by sbussetti** [comment]
@tedyu https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/event.go#L21-L22

**Comment by sbussetti** [comment]
Sorry, over-truncated the path in my description.

**Comment by sbussetti** [comment]
Same issue in coreos: https://github.com/coredns/coredns/issues/3087

**Comment by neolit123** [comment]
@sbussetti 

i cannot reproduce this problem with the following steps:
```
go get k8s.io/apiserver
cd k8s.io/apiserver
GO111MODULE=on go test ./pkg/...
...
ok  	k8s.io/apiserver/pkg/storage/etcd3	6.496s
?   	k8s.io/apiserver/pkg/storage/etcd3/metrics	[no test files]
ok  	k8s.io/apiserver/pkg/storage/etcd3/preflight	0.026s
?   	k8s.io/apiserver/pkg/storage/etcd3/testing	[no test files]
?   	k8s.io/apiserver/pkg/storage/etcd3/testing/testingcert	[no test files]
```

the k/k staging/src/k8s.io/apiserver is pushed to k8s.io/apiserver on each commit.

/triage needs-information

**Comment by sbussetti** [comment]
@neolit123 you have to be working on another project that imports the kubeapi api and uses the new package naming which will then clash with the old naming used in this k8s core code

**Comment by tedyu** [comment]
I searched k8s codebase but didn't find import referencing 'go.etcd.io'

**Comment by neolit123** [comment]
Please include this clarification https://github.com/kubernetes/kubernetes/issues/84053#issuecomment-544625914 in the OP.

**Comment by jingyih** [comment]
The imports will be updated as part of #83987.

cc @wenjiaswe

**Comment by wenjiaswe** [comment]
In current k8s HEAD, we are using etcd 3.3.15 which has go.mod removed (details can be found [here](https://github.com/kubernetes/kubernetes/pull/81434#issuecomment-522713511), and it seems like your vendor has etcd path with the new go.etcd.io/etcd that k8s cannot resolve now. Once we upgrade etcd client to 3.4.x in k8s 1.17, etcd vendor path will be go.etcd.io/etcd.

**Comment by liggitt** [comment]
The etcd client in master has been upgraded

/close
