### ISSUE TITLE
Calling pthread_setschedparam with capability SYS_NICE (or even privileged: true) results in error

### ISSUE THREAD

**Issue by skwokie** [kubernetes/kubernetes#84069]
**What happened**:
I'm trying to provision a server and the server code calls pthread_setschedparam. After doing some googling, I've realized that I need to give the container capability of SYS_NICE and so I did, and I've even given it privileged: true; however, the call still returns 2 (ENOENT).

**What you expected to happen**:
The calling returns without any error.

**How to reproduce it (as minimally and precisely as possible)**:
code snippet:
```
OS_THREAD_HANDLE handle;

LINUX_PTHREAD_CTL_t   *pthr;
struct sched_param my_param;
int my_policy;

if ((handle = OS_CURRENT_THREAD()) != NULL) {
    OS_CHANGE_THREAD_PRIORITY(handle, priority);
    return handle;
}

pthr = OS_CALLOC(0, sizeof(LINUX_PTHREAD_CTL_t));
strncpy(pthr->name, name, sizeof(pthr->name)-1);
pthread_mutex_init(&(pthr->mutex), NULL);
pthread_cond_init(&(pthr->cond), NULL);

OS_LINUX_THREAD_CTL_LOCK();

pthr->thread = pthread_self();
BASE_list_add(&OS_linux_thread_list, pthr);

pthread_getschedparam (pthr->thread, &my_policy, &my_param);
my_param.sched_priority = priority;
pthread_setschedparam(pthr->thread, SCHED_RR, &my_param);

OS_LINUX_THREAD_CTL_UNLOCK();

//OS_linux_thread_sched(&pthr->thread, pthr->name);
return (OS_THREAD_HANDLE) pthr;
```

yaml snippet:
```
securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_NICE
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS EKS

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux ip-192-168-2-243.us-west-2.compute.internal 4.14.128-112.105.amzn2.x86_64 #1 SMP Wed Jun 19 16:53:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cschuet** [comment]
@skwokie Did you ever resolve this issue? I'd also be interested to switch the scheduler for a process running inside a kubernetes pod.

**Comment by asrcryan** [comment]
@skwokie yes, did you ever resolve? We're running into same issue with pthread_create()
