### ISSUE TITLE
Propagate pod errors through ReplicaSet and Deployment status

### ISSUE THREAD

**Issue by wking** [kubernetes/kubernetes#84068]
Currently pod failures like:

```context
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/23983/pull-ci-openshift-origin-master-e2e-gcp-upgrade/13/artifacts/e2e-gcp-upgrade/pods.json | jq -r '.items[] | select(.status.phase != "Running" and .status.phase != "Succeeded") | .status.phase + " " + .metadata.namespace + " " + .metadata.name + " " + (.metadata.ownerReferences[].name) + "\n  " + ([.status.containerStatuses[] | select(.ready == false).state.waiting | .reason + ": " + .message] | join("\n"))'
Pending openshift-console downloads-698bcf5ff9-rtpts downloads-698bcf5ff9
  ImagePullBackOff: Back-off pulling image "registry.svc.ci.openshift.org/ci-op-b6skhzk1/stable@sha256:a188d1eb66acb81ef5d6c642c74a78bd1a1b5f3484077480a07019847ea276fd"
```

Are not reflected in the owning ReplicaSet:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/23983/pull-ci-openshift-origin-master-e2e-gcp-upgrade/13/artifacts/e2e-gcp-upgrade/must-gather/registry-svc-ci-openshift-org-ci-op-b6skhzk1-stable-sha256-dae1257b516a5c177237cfef5a6a3e241962b0d20cf54bcb2b66dc1671c5035e/namespaces/openshift-console/apps/replicasets.yaml | yaml2json | jq -r '.items[] | select(.metadata.name == "downloads-698bcf5ff9") | .spec.replicas + " " + (.status | tostring) + " " + (.metadata.ownerReferences[].name)'
{"replicas":"1","observedGeneration":"1","fullyLabeledReplicas":"1"} downloads
```

or Deployment:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/23983/pull-ci-openshift-origin-master-e2e-gcp-upgrade/13/artifacts/e2e-gcp-upgrade/must-gather/registry-svc-ci-openshift-org-ci-op-b6skhzk1-stable-sha256-dae1257b516a5c177237cfef5a6a3e241962b0d20cf54bcb2b66dc1671c5035e/namespaces/openshift-console/apps/deployments.yaml | yaml2json | jq -r '.items[] | select(.metadata.name == "downloads").status'
{
  "conditions": [
    {
      "status": "True",
      "lastUpdateTime": "2019-10-17T20:23:41Z",
      "lastTransitionTime": "2019-10-17T20:23:41Z",
      "type": "Available",
      "reason": "MinimumReplicasAvailable",
      "message": "Deployment has minimum availability."
    },
    {
      "status": "False",
      "lastUpdateTime": "2019-10-17T20:52:38Z",
      "lastTransitionTime": "2019-10-17T20:52:38Z",
      "type": "Progressing",
      "reason": "ProgressDeadlineExceeded",
      "message": "ReplicaSet \"downloads-698bcf5ff9\" has timed out progressing."
    }
  ],
  "observedGeneration": "2",
  "unavailableReplicas": "1",
  "availableReplicas": "2",
  "updatedReplicas": "1",
  "replicas": "3",
  "readyReplicas": "2"
}
```

I think we should update the `ProgressDeadlineExceeded` message to expose `ImagePullBackOff` and other Pod/container errors which are blocking the Deployment, probably by updating the ReplicaSet status with a message that can be collected when calculating the Deployment status.  That would make it easier for folks managing a Deployment to understand why it was failing to progress without having to poke into the underlying objects themselves.

For large Deployments, there could be many failing Pods, so we may want to truncate to only explain the first _n_ failing pods.  On the other hand, the chance of having a bunch of pods all failing in completely separate ways seems low, so it might be better to count the different (reason, message) tuples instead of truncating.

If this sounds interesting, I'm happy to take a stab at implementing it via the `Progressing` condition (we'd need a new `ReplicaSetConditionType` for `Progressing`).  Thoughts?

**Comment by wking** [comment]
CC @kubernetes/sig-apps-feature-requests (I'm not actually sure how `feature-requests` differs from `proposals`).

**Comment by tnozicka** [comment]
@wking I think we currently report those as events which reference the RS, so you see it if you'd do `kubectl describe` or get events directly - would it help your use case?

**Comment by wking** [comment]
> I think we currently report those as events which reference the RS...

In that case, I might as well get the pods directly, right?  And while that would work, this feels like something that should happen in the controller (who is already looking at the pods and summarizing them numerically).  Use case is operators that manage deployments, e.g. openshift/library-go#575 to replace messages like "I'm one ready, upgraded pod short of being happy" (not very actionable) with messages like "My new RS has no ready pods, because its first pod downloads-698bcf5ff9-rtpts is in ImagePullBackOff" (maybe pull-secret?  Maybe bungled pullspec?  Maybe registry/networking down?).  Including more details instead of (or in addition to) the reason-stuttering "Back-off pulling image" would be nice too.
