### ISSUE TITLE
Update to use go 1.12.12 on all supported branches

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#84065]
https://groups.google.com/d/msg/golang-announce/lVEm7llp0w0/VbafyRkgCgAJ

@kubernetes/release-team
@kubernetes/release-engineering
@kubernetes/product-security-committee 

/area release-eng
/priority important-soon
/sig release testing
/kind bug
/milestone v1.17

**Comment by liggitt** [comment]
This is important, but based on the actual impact of the resolved issue, does not seem to be critical/urgent

**Comment by cblecker** [comment]
Master branch/1.17 has been merged (https://github.com/kubernetes/kubernetes/pull/84064)

Release branch PRs:
- 1.16: https://github.com/kubernetes/kubernetes/pull/84114
- 1.15: https://github.com/kubernetes/kubernetes/pull/84115
- 1.14: https://github.com/kubernetes/kubernetes/pull/84116

Test-infra:
- https://github.com/kubernetes/test-infra/pull/14870

**Comment by josiahbjorgaard** [comment]
Bug triage for release 1.17 here. Since this issue has been tagged for the milestone, we would like to check it's status. Code freeze is on Nov. 19. Will this issue be resolved before then? If not, we should move it out of the milestone.

**Comment by liggitt** [comment]
All PRs are merged 

/close
