### ISSUE TITLE
healthz check etcd failed: error getting data from etcd: etcdserver: permission denied

### ISSUE THREAD

**Issue by tangcong** [kubernetes/kubernetes#84078]
**What happened**:
apiserver fails to pass readiness/liveness check when we upgrade k8s 1.12 to k8s.14+.
there are some detail error messages in apiserver when we increase log level to 6(healthz check etcd failed: error getting data from etcd: etcdserver: permission denied.)
our etcd cluster grant specified prefix(for example,/cluster-1) permission to k8s cluster. there is no problem in k8s1.12.
etcd healthz check is implemented by getting prefix+'/'+health path in k8s 1.14+,but prefix do not join '/'.

https://github.com/kubernetes/kubernetes/blob/0d9472c2ffccc148cb6caa49b21691c9f98ebf8f/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L82-L96

there is no problem in etcd3 store, pathPrefix is joined by '/' and prefix.

https://github.com/kubernetes/kubernetes/blob/0d9472c2ffccc148cb6caa49b21691c9f98ebf8f/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L90-L106

**What you expected to happen**:

prefix joins '/' in etcd healthz check.

**Comment by tangcong** [comment]
sig/api-machinery

**Comment by tangcong** [comment]
@kubernetes/api-machinery

**Comment by liggitt** [comment]
> etcd healthz check is implemented by getting prefix+'/'+health path in k8s 1.14+,but prefix do not join '/'.

What custom etcd prefix are you passing in? if you prefix it with `/`, that should resolve this issue for you in the short-term.

I agree the health check key prefix should be computed the same way as the etcd client prefix

**Comment by tangcong** [comment]
@liggitt thanks. yes, we prefix it with '/' to resolve this issue.
