### ISSUE TITLE
[scheduler] Cleanup CheckNodeMemoryPressure/DiskPressure/PIDPressure/Condition predicates

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#84100]
**What would you like to be added**:

Remove the following predicates

```go
		predicates.CheckNodeMemoryPressurePred,	
		predicates.CheckNodeDiskPressurePred,	
		predicates.CheckNodePIDPressurePred,	
		predicates.CheckNodeConditionPred,
```

**Why is this needed**:

The TaintNodeByConditions was graduate into a stable version in https://github.com/kubernetes/kubernetes/pull/82703, we could now remove the unused predicates for cleanup.

/assign
/sig scheduling
/kind cleanup
cc/ @ahg-g

**Comment by ahg-g** [comment]
+1 they have been practically deprecated since TaintNodeByConditions was in Beta (since 1.12).

**Comment by ProgramerGu** [comment]
The predicates structure is kind of complex and huge, so it is correct to remove unnecessary parts.

**Comment by ahg-g** [comment]
We need do two things next: 

1) document that we broke Policy API compatibility for those predicates since 1.12, the recommendation is to use ```CheckNodeUnschedulablePred```.

2) fix the compatibility test to apply feature gates.

**Comment by draveness** [comment]
> 2. fix the compatibility test to apply feature gates.

What do you mean by this?
