### ISSUE TITLE
rename FilterPlugin NodeResources  

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kubernetes#84101]
**What would you like to be added**:

Move `plugins/noderesources/node_resources.go`  to `noderesources/fit.go` and rename it with  NodeResourcesFit

**Why is this needed**:
After https://github.com/kubernetes/kubernetes/pull/84074 merged
/assign
/sig scheduling
/cc @ahg-g

**Comment by liggitt** [comment]
Does the rename break existing policy config files?

**Comment by ahg-g** [comment]
No.
