### ISSUE TITLE
Enviroment variable is not correctly added from secret.

### ISSUE THREAD

**Issue by Fennixx** [kubernetes/kubernetes#84106]
**What happened**: 
Enviroment variable is not listed when I connect to POD /bin/sh and run env command, but if I run same command via kubectl exec <pod> env it is listed there.
Name of env variable what causing this issue is:
PRCLISTENER_REST_HEADERS_x-ibm-client-id

**What you expected to happen**:
Need to have enviroment variable in pod correctly listed and recognized by app.

**Comment by ZP-AlwaysWin** [comment]
Can you give the correct method of recurrence

**Comment by Fennixx** [comment]
I cant, the exact case is confidential, but I normally created secret, with PRCLISTENER_REST_HEADERS_x-ibm-client-id and execute kubectl apply. Then using helm chart where in deployment I fulfill environment variables from this secret, and install that helm chart. Then when I connect to created pod to /bin/sh and execute env command, all envs from secret are there except this one. And when i try in my shell, not in pod, execute kubectl exec <pod> env it list that variable there.

**Comment by 928234269** [comment]
You can try using Bash, can you see the environment variable？

**Comment by Fennixx** [comment]
In my pod there is no bash by default.
