### ISSUE TITLE
Add filter plugins for "MaxEBSVolumeCount", "MaxGCEPDVolumeCount", "MaxAzureDiskVolumeCount", "MaxCinderVolumeCount" predicates.

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#84110]
**What would you like to be added**:
Add filter plugins for "MaxEBSVolumeCount", "MaxGCEPDVolumeCount", "MaxAzureDiskVolumeCount", "MaxCinderVolumeCount" predicates.

Those should be added under ```plugins/nodevolumelimits```. File names would be ```ebs.go```, ```gce```, ```azure.go``` and ```cinder.go```. Plugin struct name should be the same pattern, ```EBS```, ```GCE```, ```Azure``` and ```Cinder```.

We should rename the existing one, ```node_volume_limit.go```, to ```csi.go```.

**Why is this needed**:
Part of  #83554

/sig scheduling
/help
/priority important-soon

**Comment by hex108** [comment]
These predicates were marked DEPRECATED in  https://github.com/kubernetes/kubernetes/pull/74544 since 2019.2.29. They could be deleted when we ship these plugins, do we need to add them now?

**Comment by draveness** [comment]
> These predicates were marked DEPRECATED in #74544 since 2019.2.29. They could be deleted when we ship these plugins, do we need to add them now?

We'll remove these predicates in 1.18 after the CSI migration graduates to GA, here is the issue for tracking this https://github.com/kubernetes/kubernetes/issues/82375. I think we could do the migration:

1. It won't take too much time to do the migration
2. We can't be sure that these predicates could be removed in 1.18, maybe we have to wait for more releases.

**Comment by ahg-g** [comment]
While those are being deprecated, it will take a while to actually be able to remove them, and so we have to move them to the framework in the meantime. CSIMigrate will be graduating to beta soon, and after that it will take a year to actually be able to deprecated the old path since it was GA.

**Comment by hex108** [comment]
@draveness @ahg-g  thanks for the explanation
