### ISSUE TITLE
Should we add a preemptible field on pods?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8412]
Should we define a preemptible setting on the pod API for v1, given GCE's announcement?:
http://googlecloudplatform.blogspot.com/2015/05/Introducing-Preemptible-VMs-a-new-class-of-compute-available-at-70-off-standard-pricing.html

AWS also has spot instances, so this is not just a GCE thing.

I don't know that we have to actually implement it right away, but as any implementation would be best-efforts anyway, it seems like it might be worth getting it into the API before it is actually implemented.  By adding it now, we avoid an API revision.

I am imagining that we will either have a "premptability level" integer or an enum.

**Comment by thockin** [comment]
After 1.0 - it can be done additively, and I think we just don't have
bandwidth to hammer out the details just now.

**Comment by justinsb** [comment]
Fair enough ... I guess it could be done today with node labels.

**Comment by mikedanese** [comment]
Seems stale, feel free to reopen
