### ISSUE TITLE
DNS with Docker-standalone / hyperkube

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8413]
Is it possible to get DNS working with Docker-standalone / hyperkube?

I tried this:

* Followed these instructions https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md, but added " --cluster_dns=10.0.0.5 --cluster_domain=k8s.local" to the kubelet start command
* Created a non-templated version of the rc & service files here: https://github.com/GoogleCloudPlatform/kubernetes/tree/afedb2d24a920dc3de4f10926c1f93accf0d93ed/cluster/addons/dns
* The pods failed to start.  Based on #7359  I created a fake secret using the below YAML file, but apiserver still logs:
`event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-dns-puhce", UID:"176452e5-fd67-11e4-a074-fecaedeb7f07", APIVersion:"v1beta3", ResourceVersion:"658", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: operation not permitted`

The volume YAML file:
```
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "token-system-dns",
  "data": {
  }
}
```

Given this secret is empty, I don't think it would actually work, but I would expect the pod to start.

Even if I could create a token, I don't think it could authenticate with kube-apiserver, because kube-api-server does not have a known_tokens file in this mode:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/images/hyperkube/master.json

**Comment by vishh** [comment]
It should be possible to get kube2sky to work as part of hyperkube.
To run the existing docker image without auth (token) you can specify the
master URL `--kube_master_url=http://10.0.0.1:80` and not provide the
secret at all.

**Comment by bgrant0607** [comment]
We should make DNS work out of the box for hyperkube.

**Comment by justingrayston** [comment]
I created this https://github.com/justingrayston/kubernetes-docker-dns so I could work and test locally before deploying to container engine. Currently it still uses the kube master url flag as locally the API is accessed over of the docker host via http, 

It isn't really fit to go into the main project, but it should be possible to just configure with certs and key to be set up for use on a server.

**Comment by luxas** [comment]
Working, but manual steps are required.
Let's continue the discussion in #22752
