### ISSUE TITLE
tests: Kubernetes E2E test image echoserver no longer builds

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#84158]
**What happened**:

The Kubernetes E2E image ``echoserver`` no longer builds. This error is encountered when building:

    Building image for echoserver ARCH: s390x...
    ~/kubernetes/_tmp/test-images-build.hI1x5F ~/kubernetes/test/images
    Registering qemu-*-static binaries in the kernel
    Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
    Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
    Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
    Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
    Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
    Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
    Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
    Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
    Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
    Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
    Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
    Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
    Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
    Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
    Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
    Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
    Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
    Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
    Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
    Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
    Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
    Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
    Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
    Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
    Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
    Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
    Sending build context to Docker daemon  3.256MB
    Step 1/10 : FROM s390x/nginx:1.15-alpine
    1.15-alpine: Pulling from s390x/nginx
    Digest: sha256:ca07edf3336d3ed6511687852e8d139166c74ddcbe642574799a12d8afc97477
    Status: Image is up to date for s390x/nginx:1.15-alpine
     ---> c1dc44096563
    Step 2/10 : COPY qemu-s390x-static /usr/bin/
     ---> Using cache
     ---> 78d3c3541ee2
    Step 3/10 : RUN apk add --no-cache openssl nginx-mod-http-lua nginx-mod-http-lua-upstream
     ---> Running in 8b95bb8fe0e0
    ERROR: Unable to open root: Bad address
    ERROR: Failed to open apk database: Bad address
    The command '/bin/sh -c apk add --no-cache openssl nginx-mod-http-lua nginx-mod-http-lua-upstream' returned a non-zero code: 99
    Makefile:37: recipe for target 'all-container' failed
    make: *** [all-container] Error 99

This only occurs for the ``s390x`` image.

**What you expected to happen**:

``echoserver`` should be buildable.

**How to reproduce it (as minimally and precisely as possible)**:

    cd kubernetes/test/images
    make all-push WHAT=echoserver

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by bclau** [comment]
Hmm... I've added an ``ifconfig -a``:

     ---> c1b96828b92c
    Step 3/14 : COPY qemu-s390x-static /usr/bin/
     ---> Using cache
     ---> 6af1e60176f4
    Step 4/14 : RUN ifconfig -a
     ---> Running in e26e7bc1a788
    ifconfig: : error fetching interface information: Device not found
    The command '/bin/sh -c ifconfig -a' returned a non-zero code: 1
    Makefile:37: recipe for target 'all-container' failed
    make: *** [all-container] Error 1
