### ISSUE TITLE
Keep predicates ordering in scheduler filter plugins?

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#84155]
**What would you like to be added**:
Keep predicates ordering in scheduler filter plugins, it aims to improve scheduler performance.

**Why is this needed**:
`Predicates ordering`'s design doc could be found [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/predicates-ordering.md), and its PR is at [here](https://github.com/kubernetes/kubernetes/pull/57168). It aims to improve scheduler performance. However new scheduler frame plugins has its own order([by the order the plugins appear in the configuration](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#change-evaluation-order)).

There are some options to deal with it:

1. Keep present ordering mechanism. Then we need to give new filter plugins(including newly added and custom filter plugins) an oder.
2. Keep the order the plugins appear in the configuration. It might affect performance, and we can test it later.

This issue is used to track performance issue in migration phase 1.

/sig scheduling
/assign

**Comment by hex108** [comment]
Maybe we need an umbrella issue to track performance issue for migration phase 1? cc @ahg-g @k82cn @Huang-Wei

**Comment by wgliang** [comment]
FYI: http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingLatency&Operation=predicate_evaluation

@hex108

**Comment by ahg-g** [comment]
Re tracking performance: we certainly need to keep an eye on any performance regression, we monitor the perf dashboard which runs daily (it seems that the last two runs failed in the perf dashboard btw, so  lets see what today's one look like). 

@hex108 do you have a specific plan in mind other than monitoring the perf dashboard? do you mind running the perf benchmarks locally and compare the 1.16 release with the current HEAD?

**Comment by ahg-g** [comment]
Regarding ordering 

1) current ordering is preserved during migration [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/factory.go#L567-L575). You can see that we indeed keep the ordering in the [compatibility test](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/api/compatibility/compatibility_test.go#L1189-L1202), which matches [the ordering in we have been using for a while](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L148)

2) In phase two, when the predicate/priority -> plugin mapping is removed, the order will be determined by the set of default plugins that we will explicitly list (rather than translate from predicates/priorities). The default set of future plugins will be defined [here]( https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L239)

**Comment by ahg-g** [comment]
@hex108 I see that we had a "scheduler benchmark" under the perf dashboard, I assume this runs our scheduler_perf benchmarks: http://perf-dash.k8s.io/#/?jobname=scheduler-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults

however, it currently contain no results, can you create an issue to fix that, this is going to be important to tracking any regressions.

**Comment by hex108** [comment]
Thanks all!

1. Re tracking performance related things

> Re tracking performance: we certainly need to keep an eye on any performance regression, we monitor the perf dashboard which runs daily (it seems that the last two runs failed in the perf dashboard btw, so lets see what today's one look like).

When sending this issue, I am worrying about that we forget similar optimizations(e.g. predicates ordering) when doing migration, especially in phase two, because we might delete/change previous logic at that phase.

It is great to keep an eye on the perf dashboard. As @Huang-Wei said, it will be great to have a automatic solution to auto-report significant perf downgrade on several critical metrics. I'll ask sig-scalabilty team if there is one, I think there should be one, if not I'll try to run a similar monitor on our servers or send a PR for it.

> do you have a specific plan in mind other than monitoring the perf dashboard? do you mind running the perf benchmarks locally and compare the 1.16 release with the current HEAD?

I am doing some performance related things, and will make a summary for these optimizations, I'd like to track them and keep an eye on them.  And yes, I'll run perf benchmarks to compare them.

> I see that we had a "scheduler benchmark" under the perf dashboard, I assume this runs our scheduler_perf benchmarks: http://perf-dash.k8s.io/#/?jobname=scheduler-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults however, it currently contain no results, can you create an issue to fix that, this is going to be important to tracking any regressions.

I'll investigate and fix it.

2. Re ordering

> In phase two, when the predicate/priority -> plugin mapping is removed, the order will be determined by the set of default plugins that we will explicitly list (rather than translate from predicates/priorities). The default set of future plugins will be defined here

That is what I am concerned. The default order of future plugins will be defined at which order? Is it same as present predicates ordering, or take it as a reference? What's the order of custom register plugins? However that's another story, we could discuss it more when doing it.

**Comment by Huang-Wei** [comment]
@hex108 we're able to answer some of the questions now:

> The default order of future plugins will be defined at which order? Is it same as present predicates ordering, or take it as a reference?

It's derived from the legacy predictes/priorities, now ordered at `Config.FrameworkPlugins.<extension point>.Enabled`:

https://github.com/kubernetes/kubernetes/blob/4a5ab84dccc2d6b899a5c1d49b2478ec355071c9/pkg/scheduler/algorithmprovider/registry.go#L85

> What's the order of custom register plugins?

They are [inserted to a map](https://github.com/kubernetes/kubernetes/blob/4a5ab84dccc2d6b899a5c1d49b2478ec355071c9/pkg/scheduler/factory.go#L209-L212) firstly, and then ordered by the legacy predefined predicates/priority ordering:

https://github.com/kubernetes/kubernetes/blob/4a5ab84dccc2d6b899a5c1d49b2478ec355071c9/pkg/scheduler/factory.go#L357-L368

**Comment by hex108** [comment]
Thanks @Huang-Wei !
