### ISSUE TITLE
"Create e2e test for watch operations"

### ISSUE THREAD

**Issue by devaips** [kubernetes/kubernetes#84162]
# Goal
Make a test to create a few resources (~10) of all available resource types; Watch for updates; Update resource names; Verify updates

## Steps for creating test
- [ ] 1. Initialise client
- [ ] 2. Initialise dynamic client
- [ ] 3. List all resource types
- [ ] 4. Filter the resources to be simple (GA only, ones where only one field is required)
- [ ] 5. Set a watch  
  - [ ] 5.1. for when items are created  
  - [ ] 5.2 for when items are updated/renamed  
- [ ] 6. Create a resource based on filter resource names (e.g: `.modified`)
- [ ] 7. Update resources' names  
- [ ] 8. Ensure names have been updated  

/sig testing
/sig api-machinery

**Comment by hh** [comment]
Take another look at Sonobouy's loader or Velaro

**Comment by lavalamp** [comment]
Overall:
* Why does this need to be an e2e test?
* What are you hoping such a test will hold true about the system? (i.e., what failure modes will this detect)
* the dynamic client has no type dependent behavior so it is not clear why you would want to test it against multiple types. 

About the steps suggested:
* why did you choose those aspects to test?
* name is generally immutable, the last steps don't make a lot of sense
* we already have watch tests...

IMO the dynamic client should be unit tested, not integration or e2e tested.

**Comment by hh** [comment]
/retitle "Create e2e test for watch operations"

**Comment by lavalamp** [comment]
We already have e2e tests for watch operations?

**Comment by hh** [comment]
> Why does this need to be an e2e test?

Watch Conformance Coverage is the P1 Priority for the SIG-Arch Conformance subgroup.
(note the original title may have been misleading)

> What are you hoping such a test will hold true about the system? (i.e., what failure modes will this detect)

```feature
Given a watch for a specific kind
When we create an instance of that kind
Then a notification via the watch/informer will report the creation
``` 

```feature
Given a watch for a specific kind
And a created an instance of that kind
When we update the name for that kind
Then a notification via the watch/informer will report on the modification
``` 

> the dynamic client has no type dependent behavior so it is not clear why you would want to test it against multiple types.

It's primarily to ensure the creation and updating actions are observable via watch for a large set of object/kinds, 

> About the steps suggested:

> why did you choose those aspects to test?

It was from a general discussion in the Conformance Meeting about how we might be able to measure and increase watch coverage. We have the following metrics currently:

```
Watch Coverage Stats
      date    | total_watch_params | tested | conf_tested 
  ------------+--------------------+--------+-------------
   2019-09-16 |                164 |     38 |          34
   2019-09-30 |                164 |     38 |          35
  (2 rows)
```

> name is generally immutable, the last steps don't make a lot of sense

Agreed.

> we already have watch tests...

We have ~35 of the possible 164 operations that support watch currently being tested.
The idea was to increase that number.

**Comment by lavalamp** [comment]
> We have ~35 of the possible 164 operations that support watch currently being tested.

Testing every generic API feature on every API type leads to a combinatorial explosion in tests without adding much marginal value (there's only 2-4 relevant code paths that need to be tested for this particular thing). You need to either not do this or switch to a randomized testing strategy.

Will you test that metadata.generate-name works on every type? How about finalizers? How about label selection? How about testing that generation increases when you change the spec? ...
