### ISSUE TITLE
Scheduler policy api compatibility test should apply feature gates

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#84161]
Currently it does not, and that is not correct, it caused an accidental break in our compatibility since ```TaintNodesByCondition``` graduated to Beta: we removed the registration of "CheckNodeMemoryPressure, CheckNodePIDPressure, CheckNodeDiskPressure, CheckNodeCondition", but the compatibility test didn't catch that.

/sig scheduling
/help
/priority important-soon

**Comment by Huang-Wei** [comment]
@notpad One tip to reuse the snippet when applying featuregates in tests:

```go
defer algorithmprovider.ApplyFeatureGates()()
```

So that each unit test (or subtest) is atomic.

**Comment by notpad** [comment]
Thanks @Huang-Wei
