### ISSUE TITLE
Kubelet: Document GC Policy and Params

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#8416]
We frequently get questions about container GC, how it works, and what policies exist. We should document this somewhere better than in code.

**Comment by yujuhong** [comment]
Container/image GC is among one of the most asked questions from users. Bumping the priority.

/cc @pwittrock, would you want to give it a try and get to know our garbage collectors better?

**Comment by dchen1107** [comment]
Cleanning / refactory GC is in our 1.1 roadmap too.

**Comment by pwittrock** [comment]
Solved by #13087
