### ISSUE TITLE
After upgrading to zsh / Mac catalina, kubectl autocompletion raises error message

### ISSUE THREAD

**Issue by dirkcgrunwald** [kubernetes/kubernetes#84170]
I recently upgrade my mac to Catalina which brings with it a default shift to 'zsh' which is allegedly a superset of bash.

In vendor/github.com/spf13/cobra/bash_completions.go on line 76, the autocompletion code uses **type -t** which is a bash builtin but not a zsh bulitin (zsh aliases type to 'whence' and there's a similar -w flag).

When starting up a shell, this causes garble like
```
Last login: Mon Oct 21 19:36:53 on ttys015
/dev/fd/20:type:12303: bad option: -t
/dev/fd/20:12306: command not found: complete
```

**Comment by clarklee92** [comment]
As you switch to `zsh`, I think this is required. 
``` 
echo "source <(kubectl completion bash)" >> ~/.zprofile
source  ~/.zprofile 
```

**Comment by dirkcgrunwald** [comment]
Thanks, good catch.

Turns out that 30 years of sh/csh/tcsh/bash had left a trail through my dot files.
When switching to zsh, this was useful: https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e
