### ISSUE TITLE
[Failing Test] gce-windows-master (ci-kubernetes-e2e-windows-gce)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#84183]
**Which jobs are failing**:
`gce-windows-master (ci-kubernetes-e2e-windows-gce)`

**Which test(s) are failing**:
```
[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]
```
```
[k8s.io] [sig-node] Pods Extended [k8s.io] Delete Grace Period should be submitted and removed [Conformance]
```
```
[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull image from gcr.io [NodeConformance]
```

**Since when has it been failing**:
`22 Oct 21:02 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-master

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:691 Oct 22 10:48:23.700: Frontend service did not start serving content in 600 seconds. /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2173
```

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:691
Oct 22 10:51:05.286: kubelet never observed the termination notice
Unexpected error:
    <*errors.errorString | 0xc0000d5090>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pods.go:162
```

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:691
Oct 22 11:07:38.583: deploying extension apiserver in namespace aggregator-9589
Unexpected error:
    <*errors.errorString | 0xc00292d030>: {
        s: "error waiting for deployment \"sample-apiserver-deployment\" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:\"Available\", Status:\"False\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, Reason:\"MinimumReplicasUnavailable\", Message:\"Deployment does not have minimum availability.\"}, v1.DeploymentCondition{Type:\"Progressing\", Status:\"True\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, Reason:\"ReplicaSetUpdated\", Message:\"ReplicaSet \\\"sample-apiserver-deployment-d445977f4\\\" is progressing.\"}}, CollisionCount:(*int32)(nil)}",
    }
    error waiting for deployment "sample-apiserver-deployment" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"False", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, Reason:"MinimumReplicasUnavailable", Message:"Deployment does not have minimum availability."}, v1.DeploymentCondition{Type:"Progressing", Status:"True", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63707338958, loc:(*time.Location)(0x83fc260)}}, Reason:"ReplicaSetUpdated", Message:"ReplicaSet \"sample-apiserver-deployment-d445977f4\" is progressing."}}, CollisionCount:(*int32)(nil)}
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:327
```

**Anything else we need to know**:
/sig cli
/sig windows

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/issues/83890#issuecomment-544911236

The only failing test on the most recent run is [sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance].
to be fixed by https://github.com/kubernetes/kubernetes/pull/83055

**Comment by droslean** [comment]
We still hit 
```
[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]
```

**Comment by droslean** [comment]
We still hit 
```
[sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current 
Aggregator [Conformance]
```
```
[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]
```

/priority critical-urgent
/cc @kubernetes/release-team FYI

**Comment by yliaog** [comment]
[sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]

The failure is due to "e2eteam/etcd:3.4.3 not found". After it was added a few hours ago (https://hub.docker.com/r/e2eteam/etcd/tags), the test started passing.

--------------------------------------------------------------------------------------------
Nov  2 19:22:30.210: INFO: At 2019-11-02 19:17:50 +0000 UTC - event for sample-apiserver-deployment-75d4d48566-j9762: {kubelet e2e-cb0c48f7fb-36623-windows-node-group-l79s} Pulling: Pulling image "e2eteam/etcd:3.4.3"
Nov  2 19:22:30.210: INFO: At 2019-11-02 19:17:50 +0000 UTC - event for sample-apiserver-deployment-75d4d48566-j9762: {kubelet e2e-cb0c48f7fb-36623-windows-node-group-l79s} Started: Started container sample-apiserver
Nov  2 19:22:30.210: INFO: At 2019-11-02 19:17:51 +0000 UTC - event for sample-apiserver-deployment-75d4d48566-j9762: {kubelet e2e-cb0c48f7fb-36623-windows-node-group-l79s} Failed: Failed to pull image "e2eteam/etcd:3.4.3": rpc error: code = Unknown desc = Error response from daemon: manifest for e2eteam/etcd:3.4.3 not found
Nov  2 19:22:30.210: INFO: At 2019-11-02 19:17:57 +0000 UTC - event for sample-apiserver-deployment-75d4d48566-j9762: {kubelet e2e-cb0c48f7fb-36623-windows-node-group-l79s} Failed: Error: ImagePullBackOff

**Comment by droslean** [comment]
@yliaog Thanks for the update!

/sig cli

/cc @seans3  Can you check?
`[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]`

**Comment by soltysh** [comment]
> @soltysh Can you check? #83055

@droslean tagged it, after it merges I think you need to bump the image in https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L210

**Comment by droslean** [comment]
@listx The job is still failing, even after the images were published. 

Can you check?
