### ISSUE TITLE
sig-scalability-benchmarks#scheduler fails consistently due to build issues

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#84186]
**What would you like to be added**:
There is a tab in the k8s perf dashaboard for the scheduler perf benchmarks, but it is showing nothing, we should fix that:   http://perf-dash.k8s.io/#/?jobname=scheduler-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults

What this dashboard should be showing is multiple runs per day of 
```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false"
```

We can run it every hour, and summarize the 24 runs of each day to show 50%, 90% and 99% percentile. 

**Why is this needed**:
Having daily runs of the benchmarks is important to track performance regressions. 

/sig scheduling
/assign @hex108 
/priority important-soon

**Comment by hex108** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/80800

**Comment by hex108** [comment]
The ci job's config is at https://github.com/kubernetes/test-infra/blob/2323f5653036e46a582425b3bdaaa11fe99b96db/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L339.

And one of failed logs could be found at https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-master/1181929333778812934/build-log.txt.

I tried to reproduce it on my local machine(because I do not have Gloud credentials, I run the task directly in the container):

```
docker run --entrypoint=bash -it gcr.io/k8s-testimages/kubekins-e2e:v20191021-b891e54-master
/workspace# git clone https://github.com/kubernetes/test-infra
/workspace# cd /go/src/k8s.io
/go/src/k8s.io# rm -rf kubernetes
/go/src/k8s.io# git clone https://github.com/kubernetes/kubernetes
/go/src/k8s.io# /workspace/./test-infra/jenkins/../scenarios/execute.py ./hack/jenkins/benchmark-dockerized.sh ./test/integration/scheduler_perf
```

However it works well on my local machine. It is so weird. It will be better if anyone could help reproduce it with Gloud credentials.

**Comment by ahg-g** [comment]
can you try and reach out to the test-infra people? ping them on the slack channel perhaps.

**Comment by hex108** [comment]
yes, I have tried to get help from @krzysied , he is busy now. I'll try more.

**Comment by mm4tt** [comment]
While working on reproducing this in order to file a bug against test-infra folks I think I found a solution.
Will send PRs shortly.

/assign 
/tittle sig-scalability-benchmarks#scheduler fails consistently due to build issues

**Comment by mm4tt** [comment]
/retitle sig-scalability-benchmarks#scheduler fails consistently due to build issues

**Comment by mm4tt** [comment]
/sig scalability

Testgrid link: https://k8s-testgrid.appspot.com/sig-scalability-benchmarks#scheduler

Error logs:
```
1031 08:05:03.983] +++ [1031 08:05:03] Running tests without code coverage
I1031 08:05:04.011] 
I1031 08:05:04.012] DONE 0 tests in 0.001s
I1031 08:05:04.035] +++ [1031 08:05:04] Saved JUnit XML test report to /workspace/_artifacts/junit_d965d8661547eb73cabe6d94d5550ec333e4c0fa_20191031-080503.xml
I1031 08:05:04.052] +++ [1031 08:05:04] Cleaning up etcd
I1031 08:05:04.065] +++ [1031 08:05:04] Integration test cleanup complete
W1031 08:05:04.073] can't load package: package k8s.io/kubernetes: no Go files in /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
W1031 08:05:04.074] make[1]: *** [Makefile:185: test] Error 1
```

**Comment by mm4tt** [comment]
A word about the solution, the job uses the deprecated bootstrap.py script which is not supported anymore by test-infra oncall / folks.
I've rewritten the job definition to use pod utilities and it started working (will require https://github.com/kubernetes/kubernetes/pull/84593 to get merged first).

**Comment by ahg-g** [comment]
Thanks @mm4tt!

**Comment by hex108** [comment]
Thanks @mm4tt !
