### ISSUE TITLE
failing test: [k8s.io] Security Context when creating a pod in the host PID namespace should show its pid in the host PID namespace [LinuxOnly] [NodeFeature:HostAccess] 

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#84209]
**Which jobs are failing**: `pull-kubernetes-e2e-kind`, `pull-kubernetes-e2e-gce`

**Which test(s) are failing**: `[k8s.io] Security Context when creating a pod in the host PID namespace should show its pid in the host PID namespace [LinuxOnly] [NodeFeature:HostAccess]`

**Since when has it been failing**: since this PR introduced them https://github.com/kubernetes/kubernetes/pull/83368#issuecomment-544905429

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&sort-by-flakiness=&width=5
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind&width=5&sort-by-flakiness=

Note that this is the flakiest test in both dashboards, and failing quite frequently.

**Reason for failure**: unknown

**Anything else we need to know**:
cc @liggitt

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/kubernetes/pull/83368#issuecomment-544926506, both getting empty PID and multiple PIDs.

**Comment by johnbelamaric** [comment]
@Jefftree

**Comment by liggitt** [comment]
opened revert at https://github.com/kubernetes/kubernetes/pull/84212

**Comment by alejandrox1** [comment]
for discoverability for the release team
/priority critical-urgent
/milestone v1.17
