### ISSUE TITLE
Support, and require explicit timezones for recurring jobs

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#84201]
Please support the modern `CRON_TZ=<timezone>` suffix for clarifying exactly when recurring jobs should run, in order to avoid jobs running at the wrong time.

Furthermore, please require this suffix, so that human operators are less likely to make mistakes when configuring job intervals.

The timezone should accept both country code ("UTC", "PST", etc.), as well as regional ("UTC", "America/Los_Angeles") formats. Finally, it would be nice to support the legacy `TZ=<timezone>` suffix, in order to more seamlessly transition UNIX `cron` jobs onto Kubernetes clusters.

https://en.wikipedia.org/wiki/Cron#Timezone_handling

**Comment by neolit123** [comment]
/sig apps
?

**Comment by RickyRajinder** [comment]
Would this require changing the `schedule:` field in `CronJob` to require a timezone suffix?

**Comment by benlangfeld** [comment]
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/47202

**Comment by whut** [comment]
Yes it is duplicate, but IMHO this should be added to the Kubernetes CronJob. It is common for cron jobs to have timezone support, Kubernetes should be no different.

/remove-lifecycle stale

**Comment by benlangfeld** [comment]
@whut yes, but this should be closed and #47202 opened. There is much more valuable information in that thread.

**Comment by soltysh** [comment]
This is indeed duplicate of https://github.com/kubernetes/kubernetes/issues/47202, and I'm closing this as such. As I mentioned that in the other issue this topic is covered in  #82659 and kubernetes/enhancements#19 and that's where it will be discussed but only when we get the new controller completed. 
/close
