### ISSUE TITLE
can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes

### ISSUE THREAD

**Issue by hhxyda** [kubernetes/kubernetes#84224]
go/build: importGo k8s.io/kubernetes: exit status 1
can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes

+++ [1023 17:46:10] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen latest
go: finding k8s.io/kubernetes/vendor latest
go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator latest
go: finding k8s.io/kubernetes/vendor/k8s.io latest
can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: no matching versions for query "latest"
!!! [1023 17:46:36] Call tree:
!!! [1023 17:46:36]  1: /home/bruce/goProject/src/k8s.io/kubernetes/hack/lib/golang.sh:713 kube::golang::build_some_binaries(...)
!!! [1023 17:46:36]  2: /home/bruce/goProject/src/k8s.io/kubernetes/hack/lib/golang.sh:852 kube::golang::build_binaries_for_platform(...)
!!! [1023 17:46:36]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1023 17:46:36] Call tree:
!!! [1023 17:46:36]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1023 17:46:36] Call tree:
!!! [1023 17:46:36]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2

**Comment by liggitt** [comment]
until https://github.com/kubernetes/kubernetes/issues/82531 is merged, you will need to use go1.12 to build

/close
