### ISSUE TITLE
make WHAT='test/e2e/e2e.test' Error

### ISSUE THREAD

**Issue by regardfs** [kubernetes/kubernetes#84237]
**What happened**:
```
when run e2e test: error occured as below:
[root@k8s-01 kubernetes]# make WHAT='test/e2e/e2e.test'
go/build: importGo k8s.io/kubernetes: exit status 1
can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes
F1023 22:17:12.962911    4659 deepcopy.go:131] Failed loading boilerplate: open /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
```

**What you expected to happen**:
Pass ....
**How to reproduce it (as minimally and precisely as possible)**:
make WHAT='test/e2e/e2e.test' on tag v1.13.10
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.10
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos7.6
- Kernel (e.g. `uname -a`):  Linux k8s-01 4.19.43-300.el7.x86_64 #1 SMP Fri May 17 00:06:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubespray
- Network plugin and version (if this is a network-related bug): calico
- Others: golang v.1.12.12

**Comment by regardfs** [comment]
I want more document about how to setup an env for e2e test......

**Comment by neolit123** [comment]
/sig release testing
i haven't tried using e2e.test without bazel.
if you have bazel you can try:
```
$ bazel build //test/e2e:e2e.test
# result is in bazel-bin/test/e2e/e2e.test
```
