### ISSUE TITLE
CustomResourceDefinitionSpec missing default scope value

### ISSUE THREAD

**Issue by abursavich** [kubernetes/kubernetes#84257]
**What happened**:
The comments for the `Scope` field in `apiextensionsv1.CustomResourceDefinitionSpec` state that the default value is `Namespaced`, however no default value is set.

- Default value and comment removed: https://github.com/kubernetes/kubernetes/commit/05d8b448d274e30772750fcea71b10c8177e556e
- Comment re-added: https://github.com/kubernetes/kubernetes/commit/e60b82a7b83b982a28399fb744b05da0450b6346

**What you expected to happen**:

Maximally, I expect a valid default value to be set for non-pointer "enum" types.

Minimally, I expect the comments and behavior to match.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
N/A

**Comment by abursavich** [comment]
cc: @liggitt

**Comment by abursavich** [comment]
/sig api-machinery

???

**Comment by liggitt** [comment]
This is a documentation bug (the improved docs were copied from v1beta1 and this diff was missed). The default is intentionally omitted to make CRD creators explicitly state their scope. 

/kind documentation
