### ISSUE TITLE
Kubernetes building is failing runtime Kubernetes building is failing

### ISSUE THREAD

**Issue by hhxyda** [kubernetes/kubernetes#84278]
go version: go1.12.7.linux-amd64.tar.gz
kuberbetes-version:release-1.15
bulid problem：
k8s.io/kubernetes/cmd/kubeadm
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6785f7, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc030000000, 0x4000000, 0x85a7b8)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x842d00, 0x38c000, 0x842d10, 0x1c6)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x842d00, 0x1c6, 0x0)
	/usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x842d00, 0x1c6, 0x85a7c8, 0x842d08)
	/usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x842d00, 0x1c6, 0x7f4d52480101, 0x7f4d5248d8d8)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x842d00, 0x1c6, 0xc000000101, 0x7f4d5248d848)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x38c000, 0x450100, 0x7f4d5248d848)
	/usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

**Comment by zouyee** [comment]
```
fatal error: runtime: out of memory
```
There may be not enough memory, try opening swap

**Comment by neolit123** [comment]
last time i checked `make quick-release` required at least 8GB of ram.
building individual components requires much less.

you can try e.g. `make all WHAT=cmd/kubelet`, `make all WHAT=cmd/kubeadm`

/sig release
/triage support
