### ISSUE TITLE
Events from "kubectl describe" are incorrect when pod contains multiple contianers. (1.15.2)

### ISSUE THREAD

**Issue by vivisquirrel** [kubernetes/kubernetes#84272]
**What happened**:
The events information from "kubectl describe pod xxx" is incorrect, some important events are missing. in this case, image pulling event is missing. 
**What you expected to happen**:
new image pulling event is expect to be showed in "kubectl describe pod xxx" outputs.
**How to reproduce it (as minimally and precisely as possible)**:
[step1]
create a manifest shown as below. there's an intended typo in manifest:  "buxybox" in line 10.
**[root@master 10-24]# cat test.yaml** 
_apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test-6
spec:
  containers:
  - image: **buxybox**
    name: test
    command: ['sh','-c','sleep 99999']
  - image: nginx
    name: nginx
  - image: redis
    name: redis
  - image: luksa/kubia
    name: kubia 
  dnsPolicy: ClusterFirst
  restartPolicy: Never_

[step2]
create pod named test-6 from the above manifest. 
**[root@master 10-24]# kubectl apply -f test.yaml** 
_pod/test-6 created_

[step3]
The pod test-6 is failed to be created as expect since the image name is wrong.
**[root@master 10-24]# kubectl get po/test-6**
_NAME     READY   STATUS         RESTARTS   AGE
test-6   3/4     ErrImagePull   0          2m20s_

[step4]
Check events by issue kubectl describe.

**[root@master 10-24]# kubectl describe po/test-6**
_Name:         test-6
Namespace:    default
Priority:     0
Node:         node02/192.168.0.63
Start Time:   Thu, 24 Oct 2019 12:21:42 +0800
Labels:       run=test
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"test"},"name":"test-6","namespace":...
Status:       Pending
IP:           10.244.2.126
Containers:
  test:
    Container ID:  
    Image:         buxybox
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      sleep 99999
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pmrjd (ro)
........
........
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  62s                default-scheduler  Successfully assigned default/test-6 to node02
  Normal   Pulling    54s                kubelet, node02    Pulling image "nginx"
  Normal   Started    48s                kubelet, node02    Started container nginx
  Normal   Pulling    48s                kubelet, node02    Pulling image "redis"
  Normal   Pulled     48s                kubelet, node02    Successfully pulled image "nginx"
  Normal   Created    48s                kubelet, node02    Created container nginx
  Normal   Created    40s                kubelet, node02    Created container redis
  Normal   Pulling    40s                kubelet, node02    Pulling image "luksa/kubia"
  Normal   Started    40s                kubelet, node02    Started container redis
  Normal   Pulled     40s                kubelet, node02    Successfully pulled image "redis"
  Normal   Pulled     24s                kubelet, node02    Successfully pulled image "luksa/kubia"
  Normal   Created    24s                kubelet, node02    Created container kubia
  Normal   Started    24s                kubelet, node02    Started container kubia
  Normal   Pulling    23s (x2 over 61s)  kubelet, node02    Pulling image "buxybox"
  Warning  Failed     18s (x2 over 54s)  kubelet, node02    Error: ErrImagePull
  Warning  Failed     18s (x2 over 54s)  kubelet, node02    Failed to pull image "buxybox": rpc error: code = Unknown desc = Error response from daemon: pull access denied for buxybox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Normal   BackOff    3s (x2 over 17s)   kubelet, node02    Back-off pulling image "buxybox"
  Warning  Failed     3s (x2 over 17s)   kubelet, node02    Error: ImagePullBackOff_    

As shown above, image "buxybox" is failed to be pulled since it's a wrong image name.
 
[step5]
Then correct the typo in manifest file (buxybox -> busybox) and apply the manifest.

**[root@master 10-24]# cat test.yaml** 
_apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test-6
spec:
  containers:
  - image: busybox
    name: test
    command: ['sh','-c','sleep 99999']
  - image: nginx
    name: nginx
  - image: redis
    name: redis
  - image: luksa/kubia
    name: kubia 
  dnsPolicy: ClusterFirst
  restartPolicy: Never_

**[root@master 10-24]# kubectl apply -f test.yaml** 
_pod/test-6 configured_

[step6]
check the status and events of pod test-6.
**[root@master 10-24]# kubectl get po/test-6**
_NAME     READY   STATUS    RESTARTS   AGE
test-6   4/4     Running   0          29m_

**[root@master 10-24]# kubectl describe po/test-6**
_Name:         test-6
Namespace:    default
Priority:     0
Node:         node02/192.168.0.63
Start Time:   Thu, 24 Oct 2019 12:21:42 +0800
Labels:       run=test
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"test"},"name":"test-6","namespace":...
Status:       Running
IP:           10.244.2.126
Containers:
  test:
    Container ID:  docker://8907e25a7617698875e92f98be99232fd62de22499baa6627b93f75820623c92
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:fe301db49df08c384001ed752dff6d52b4305a73a7f608f21528048e8a08b51e
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      sleep 99999
    State:          Running
      Started:      Thu, 24 Oct 2019 12:29:50 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pmrjd (ro)
......
......
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  29m                 default-scheduler  Successfully assigned default/test-6 to node02
  Normal   Pulling    29m                 kubelet, node02    Pulling image "nginx"
  Normal   Started    29m                 kubelet, node02    Started container nginx
  Normal   Pulling    29m                 kubelet, node02    Pulling image "redis"
  Normal   Pulled     29m                 kubelet, node02    Successfully pulled image "nginx"
  Normal   Created    29m                 kubelet, node02    Created container nginx
  Normal   Created    29m                 kubelet, node02    Created container redis
  Normal   Pulling    29m                 kubelet, node02    Pulling image "luksa/kubia"
  Normal   Started    29m                 kubelet, node02    Started container redis
  Normal   Pulled     29m                 kubelet, node02    Successfully pulled image "redis"
  Normal   Pulled     28m                 kubelet, node02    Successfully pulled image "luksa/kubia"
  Normal   Created    28m                 kubelet, node02    Created container kubia
  Normal   Started    28m                 kubelet, node02    Started container kubia
  Normal   BackOff    28m (x2 over 28m)   kubelet, node02    Back-off pulling image "buxybox"
  Normal   Pulling    28m (x3 over 29m)   kubelet, node02    Pulling image "buxybox"
  Warning  Failed     28m (x3 over 29m)   kubelet, node02    Failed to pull image "buxybox": rpc error: code = Unknown desc = Error response from daemon: pull access denied for buxybox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     28m (x3 over 29m)   kubelet, node02    Error: ErrImagePull
  Warning  Failed     24m (x17 over 28m)  kubelet, node02    Error: ImagePullBackOff_

From above output, it's obvious that busybox image is pulled successfully and the busybox container is running. But the pulling event of 'busybox' is not shown in the Events output. The previous failed pull event of 'buxybox' is shown in the Event instead.
I think the correct behavior should show the new 'busybox' pull event instead of showing the previous failed pull event of 'buxybox'. 

Thanks!

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
[root@master 10-24]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
ECS on AliCloud.
- OS (e.g: `cat /etc/os-release`):
[root@master 10-24]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
[root@master 10-24]# uname -a
Linux master 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
When many events are generated for a single pod, the kubelet may rate limit events and not send them. Event recording is best effort by the kubelet in order to avoid overwhelming the API server. cc @derekwaynecarr

**Comment by liggitt** [comment]
Event delivery is best effort and may drop events under load
