### ISSUE TITLE
Migrate Kubemark to distroless

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#84284]
There are CVEs happening in different images - we already migrated Kubmeark from busybox in https://github.com/kubernetes/kubernetes/pull/84231, but we should go one step further and migrate the base image to distroless.

There are some things that would need to be changed mentioned here:
https://github.com/kubernetes/kubernetes/pull/73539

/sig scalability

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability-bugs @mm4tt

**Comment by notpad** [comment]
Can I work on this?
/assign

**Comment by wojtek-t** [comment]
@notpad - sure that would be great.

**Comment by notpad** [comment]
Hi @wojtek-t, based on the discussion in #73539, the kubmeark image has dependency on `mount` and maybe more other utilities. So it seems impossible to migrate the base image to distroless?  Or do we need something like debian-hyperkube-base?

**Comment by wojtek-t** [comment]
> Hi @wojtek-t, based on the discussion in #73539, the kubemark image has dependency on mount and maybe more other utilities.

The mount one we may get rid of - basically we should be able to switch to FakeMounter:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubemark/hollow_kubelet.go#L114
