### ISSUE TITLE
Error getting while creating elasticsearch stateful set

### ISSUE THREAD

**Issue by lordcf** [kubernetes/kubernetes#84285]
Access Modes:  [ReadWriteOnce]
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  25m                 statefulset-controller  create Claim data-es-cluster-0 Pod es-cluster-0 in StatefulSet es-cluster success
  Warning  FailedCreate      22s (x67 over 25m)  statefulset-controller  create Pod es-cluster-0 in StatefulSet es-cluster failed error: Pod "es-cluster-0" is invalid: [spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy, spec.initContainers[1].securityContext.privileged: Forbidden: disallowed by cluster policy, spec.initContainers[2].securityContext.privileged: Forbidden: disallowed by cluster policy]

Suggest me any solution do i need to change podsecuritypolicy?

**Comment by McCoyAle** [comment]
@lordcf Are you reporting a bug/issue or requesting assistance? This might be something that needs to be posted to stackoverflow and tagged with kubernetes.
