### ISSUE TITLE
kubernetes 1.13.4 patch extended-resource Invalid  sig/api-machinery

### ISSUE THREAD

**Issue by ProgramerGu** [kubernetes/kubernetes#84281]
**What happened**:
I use client-go (API) to patch a node for some Resources，information like this 
name 127.0.0.1 
type application/json-patch+json
data [{"op":"add","path":"/status/capacity/xxx-volume","value":"10"}]
It return with no error but the node status didn`t change,Resources didn`t patch successful.
Why is this happening?and what should I do to fix it?
Please......

**What you expected to happen**:

- Resources patch successful or tell me what`s wrong,maybe how should I fix it.
- The api-server reply more friendly,because return a node-info is not easy to tell.

**How to reproduce it (as minimally and precisely as possible)**:
Use patch to add extended-resource
**Anything else we need to know?**:
It happens Irregularity or I didn`t find the Law.
**Environment**:
- Kubernetes version (use `kubectl version`):1.13.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux 220.194.64.137 4.19.12-1.el7.elrepo.x86_64 #1 SMP Fri Dec 21 11:06:36 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: bin file
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Your patch is modifying fields within the status stanza of the object

All changes to the status stanza are ignored when sending updates to the main node resource endpoint (`/api/v1/nodes/<name>`). Changes to status are only effective when updating via the status subresource endpoint (`/api/v1/nodes/<name>/status`).

If we had a mechanism for warning, we could emit a warning if we detected changes to the status stanza in a request to the main resource, but we do not have such a mechanism yet (xref https://github.com/kubernetes/kubernetes/pull/73032), and changing to return an error in this scenario would not be backwards compatible.

**Comment by ProgramerGu** [comment]
> Your patch is modifying fields within the status stanza of the object
> 
> All changes to the status stanza are ignored when sending updates to the main node resource endpoint (`/api/v1/nodes/<name>`). Changes to status are only effective when updating via the status subresource endpoint (`/api/v1/nodes/<name>/status`).
> 
> If we had a mechanism for warning, we could emit a warning if we detected changes to the status stanza in a request to the main resource, but we do not have such a mechanism yet (xref #73032), and changing to return an error in this scenario would not be backwards compatible.

Thanks a lot ~
