### ISSUE TITLE
container_sockets, container_threads, container_max_threads metrics always return 0

### ISSUE THREAD

**Issue by sukhong** [kubernetes/kubernetes#84308]
**What happened**:

container_sockets, container_threads, container_max_threads metrics were added as part of Kubernetes 1.16 release. 

However, I only see 0 for these metrics.

**What you expected to happen**:

These metrics should give non-zero numbers.

**How to reproduce it (as minimally and precisely as possible)**:

New cluster using Kubernetes 1.16.2 + Prometheus 2.11.1.

Scraped container_sockets, container_threads, container_max_threads metrics always return 0

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.2
- Cloud provider or hardware configuration: Azure, cluster provisioned using aks-engine
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: aks-engine
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery
/sig node

**Comment by sukhong** [comment]
@kubernetes/sig/api-machinery
@kubernetes/sig/node

**Comment by ericsuhong** [comment]
It seems like this has only been merged into 1.17+. Is it possible to backport this fix into 1.16 as well?

**Comment by nshekhar221** [comment]
I am also seeing this issue in 1.6.9. Any possibility of backporting this fix to 1.16?

**Comment by rasebo** [comment]
Also seeing this in 1.16.9, is there anything preventing this change from being backported?

**Comment by dashpole** [comment]
Though we meant to enable process metrics in 1.16, we accidentally didn't.  I consider the collection of new metrics a feature, and don't think it should be backported.  It will likely cause some additional resource usage on the node, which isn't appropriate for a patch release.
