### ISSUE TITLE
Refactor scheduler benchmark tests to make it more extensible

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#84307]
Current benchmark tests are hardcoded to be a certain kind of workloads. It can be refactored to be more extensible and customizable, so that users can leverage the benchmark utilities while composing their own workloads to benchmark.

A possible approach is to use Golang templating to define a YAML to support customizable workloads specs.

/sig scheduling
cc/ @ahg-g @draveness
/help
Part of #81719

**Comment by liu-cong** [comment]
I'd like to see if we can unify the benchmark tests with the clusterloader test, i.e., use the same(or similar) configuration and dashboard/metrics for both. Essentially abstracting cluster set up (whether a real cluster, a kubemark cluster or just fake cluster) out of load configuration and metrics gathering.

If we can do that, we already have a good language to configure workloads - the clusterloader config.

**Comment by notpad** [comment]
@liu-cong Where can we find the clusterloader config, could you give me an example?

**Comment by liu-cong** [comment]
@notpad ,
Let me know if you would like to continue working on this and incorporate the proposal in #85662.

**Comment by notpad** [comment]
@liu-cong Yes, I'd like to continue the work based on your proposal.
