### ISSUE TITLE
deletionGracePeriodSeconds is set to 0 and --grace-period is ignored

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#84310]
**What happened**:
Deployment metadata.deletionGracePeriodSeconds is always set to 0.

**What you expected to happen**:
I would expect the value of `--grace-period` to be respected.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply a deployment with a finalizer:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  finalizers:
  - foo/bar
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

2. Delete the deployment with `--grace-period` arg
```
$ k delete deploy nginx-deployment --grace-period=300
```

3. Ensure that `.metadata.deletionGracePeriodSeconds` is set to 0.

**Anything else we need to know?**:
If you repeat the same steps with a pod with a finalizer, its metadata.deletionGracePeriodSeconds will be properly updated to the value of `--grace-period`.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: minikube
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ialidzhikov** [comment]
@liggitt, @nikhita is the `deletionGracePeriodSeconds` always set to 0 because of the presence of a custom finalizer `foo/bar`?

**Comment by liggitt** [comment]
no, because the deployment resource does not support graceful deletion (graceful deletion requires server-side support, and only the pods resource currently implements it)

**Comment by liggitt** [comment]
/remove-kind bug
/kind documentation

docs should make it clearer that graceful deletion is only supported by particular resources

**Comment by ialidzhikov** [comment]
Thank you @liggitt for the fast reply. I was digging in k/website but cannot find anything similar. It will be for sure useful to put these details in the docs.

**Comment by fedebongio** [comment]
looks like the PR for documentation update was merged, we can close this one

**Comment by liggitt** [comment]
this would be a useful thing to warn about from the server-side once we have that ability. xref https://github.com/kubernetes/kubernetes/pull/73032
