### ISSUE TITLE
Pod cannot be launched on the node after increasing the cpus of the node

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubernetes#84333]
**What happened**:
We deployed a k8s cluster on the virtual machines and it worked fine!
We configured the kubelet parameter as: 
`--cpu-manager-policy=static --kube-reserved=cpu=1,memory=1Gi --system-reserved=cpu=1,memory=1Gi`.

When we try to add CPUs to a node, we first shut down the machine and restart the node after adding CPUs.
However, we found that the Pod for this node was not created properly.
The status of these pods is always `ContainerCreating`.
Looking at the Pod event, there are errors like the following:
```sh
48m Warning FailedMount Pod MountVolume.SetUp failed for volume "default-token-f622k" : couldn't propagate object cache: timed out waiting for the condition
43m Warning FailedMount Pod MountVolume.SetUp failed for volume "default-token-f622k" : couldn't propagate object cache: timed out waiting for the condition
39m Warning FailedMount Pod MountVolume.SetUp failed for volume "default-token-f622k" : couldn't propagate object cache: timed out waiting for the condition
```
Further, by looking at the failed node kubelet log, we found that the cpumanager was not working properly:
```sh
Oct 24 14:37:23 node1 kubelet: I1024 14:37:23.556422 9720 state_mem.go:84] [cpumanager] updated default cpuset: "0-3"
Oct 24 14:37:24 node1 kubelet: E1024 14:37:24.053451 9720 policy_static.go:111] [cpumanager] static policy invalid state: current set of available CPUs "0-7" doesn't match with CPUs in state "0-3"
```
It seems that kubelet did not correctly recognize the change in the number of cpus.

**What you expected to happen**:
After adjusting the number of cpus of the node, kubelet should sense change and work correctly.

**How to reproduce it (as minimally and precisely as possible)**:
As described above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`):  3.10.0-957.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by delthas** [comment]
This is expected behaviour: when the Kubelet CPU manager is configured with a static policy, the CPU manager stores a permanent state, which includes CPU info, in a file in the kubelet directory. When the CPU info changes, the CPU manager detects a discrepancy in the availables cores and throws an error. This ensure kubelet doesn't try to assign exclusive CPUs that don't exist anymore to Guaranteed pods.

See: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy

> Note: CPU Manager doesn't support offlining and onlining of CPUs at runtime. Also, if the set of online CPUs changes on the node, the node must be drained and CPU manager manually reset by deleting the state file cpu_manager_state in the kubelet root directory.

How to fix: 
```shell
systemctl stop kubelet
rm -f /var/lib/kubelet/cpu_manager_state
systemctl start kubelet
```
