### ISSUE TITLE
Generate Definitive List of all tests from source code w/ metadata in CSV / JSON format

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#84330]
We want to utilize / generate https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-comment-metadata
to generate a comprehensive list of tests, with all available metadata.

We manually add a src path and last string in the test to identify tests as conformance tests within https://github.com/kubernetes/kubernetes/tree/master/test/conformance
but this doesn't give us the metadata necessary to automate some of the metrics necessary for Conformance.

The existing conformance walking that is useful as as starting point:
https://github.com/kubernetes/kubernetes/blob/master/test/conformance/walk.go#L40

Arguments, ala `--url`, `--conformance`, and `--version`:

```go
var (
	baseURL = flag.String("url",
                              "https://github.com/kubernetes/kubernetes/tree/master/",
                              "location of the current source")
	confDoc =   flag.Bool("conformance",
                               false,
                              "write a conformance document")
	version = flag.String("version",
                              "v1.9",
                              "version of this conformance document")
	totalConfTests, totalLegacyTests, missingComments int

	// If a test name contains any of these tags, it is ineligble for promotion to conformance
        // *** Note that v1.12 and earlier have Flaky Conformance tests 
	regexIneligibleTags = regexp.MustCompile(
                              `\[(Alpha|Disruptive|Feature:[^\]]+|Flaky)\]`)
)
```

Without any arguments it generates the conformance.txt on stdout, noting the [documentation update that @heyste did](https://github.com/kubernetes/community/pull/3948/files?short_path=95da553#diff-95da5537a24410366e75b8e34e2b8e6a):

> `go run test/conformance/walk.go test/e2e > test/conformance/testdata/conformance.txt` adds the test name to the conformance.txt file

With ``--conformance`` is uses a header of https://github.com/kubernetes/kubernetes/blob/master/test/conformance/cf_header.md and iterates through generating markdown documentation for each Conformance Test ala this PR:

https://github.com/cncf/k8s-conformance/pull/622 (note the [need to fix the paths](https://gitlab.ii.coop/ii/k8s/conformance-testing/issues/33#note_10700)) 

```shell
go run k8s.io/kubernetes/test/conformance
   --conformance
   --version v1.15
   --url https://github.com/kubernetes/kubernetes/tree/v1.15
   \~/ii/kubernetes-for-conformance/ > docs/KubeConformance-1.15.md
```

For this to work, we'd want to generate for all tests, and include any metadata that's available

- [ ] Don't skip any tests (get everything, even non-conformant and flakey
- [ ] Generate a json or CSV for now, but include all possible metadata (from comments or otherwise) for each test
- [ ] Include Line Numbers, and if possible the surrounding Context etc function tree that creates the full test name that we see in our audit logs and test-grid

**Comment by hh** [comment]
We did some initial work here: 
https://github.com/kubernetes/kubernetes/compare/master...ii:csv-output-conformance-walk

**Comment by liggitt** [comment]
not sure if you're envisioning committing the resulting file like the current conformance.txt file, but if so, including line numbers will make the resulting file a rebase magnet

**Comment by hh** [comment]
I'm hoping is that we can have generated metadata that doesn't directly refer to line numbers, but allows us to uniquely identify all tests.

Ensuring that we don't have duplicate "final string IT context" wouldn't be too hard for conformance.txt, as are around 28 that are the same.

```
cat conformance.txt  | awk -F: '{print $2}' | sort | uniq -d | wc -l
28
```

However for the entire set that would require quite a few changes.
It integer or short string in a tag [id:X], or add metadata to the tests themselves.

**Comment by hh** [comment]
@johnSchnake mentioned generating this list with an e2e dry run combined with a reporter, but that this approach lacked the comments available via the AST walker.

/assign @johnSchnake
