### ISSUE TITLE
Error "ssh: command not found"

### ISSUE THREAD

**Issue by thosieucoi** [kubernetes/kubernetes#84332]
I'm using Kubernetes Clusters to run Gitlab Runner (CICD). When I tried to ssh to an Ubuntu instance to deploy my source code I got the error "ssh: command not found"

Part of my deploy code is below

`ssh ubuntu@$xx.xx.xx.xx -tt /bin/bash <<EOT
    echo "${ENV}" > .env
    sudo docker image prune -f
    ...`

Would anyone help me in this case?

**Comment by zouyee** [comment]
You need to install ssh utils.
`apt-get install openssh-client`

**Comment by thosieucoi** [comment]
@zouyee: Thank you for your response. Sorry but where should I install it?
