### ISSUE TITLE
We need resource request/limit in the pod level

### ISSUE THREAD

**Issue by YueHonghui** [kubernetes/kubernetes#84340]
**What would you like to be added**:
Now, one of our usecases, we need to attach network NICs/ENIs into Pod. The number of NICs on a node is limited, so we create a device plugin to represent such a resource and calculate NICs requirement in scheduler. The problem is, we don't know where to put `request`/`limit` into the Pod spec. We don't think the container level is the right place, because network namespace and NICs are shared across containers in the same Pod. As a common question, do we need a way to represent resource requirement in Pod level?
 
**Why is this needed**:
See above

**Comment by ProgramerGu** [comment]
Do you mean like k8s-device-plugin?

**Comment by YueHonghui** [comment]
@ProgramerGu No, the problem is not how to add custom devices/resources and schedule it, this can be resolved by k8s-device-plugin. The problem is that some resources(such as IP or ENI-on-aws) is pod level but the only place to put resource requirements to pod spec is container level. In our case, now we push down such resource requirements from pod level to container level by choosing a container of pod randomly. This works, but not very "elegant".
