### ISSUE TITLE
why kubelet admits guaranteed pods when under disk pressure?

### ISSUE THREAD

**Issue by langyenan** [kubernetes/kubernetes#84403]
In the code below, kubelet rejects pods with QOS type guaranteed when under disk pressure, but when kubelet is **also** under memory pressure, those pods are accepted, is this behavior expected? Why is that?

https://github.com/kubernetes/kubernetes/blob/2896fb0be8515e909df71bf29074acf32c54c969/pkg/kubelet/eviction/eviction_manager.go#L128-L164

**Comment by tedyu** [comment]
See this comment:
```
		// admit it if tolerates memory pressure taint, fail for other tolerations, e.g. DiskPressure.
```
It came with commit e94d7b3802a

**Comment by gaorong** [comment]
you can find an answer from the proposal doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#feasibility-checks-during-kubelet-admission
```
The rationale for failing all pods instead of just best effort is because disk is currently a best effort resource for all QoS classes.
```

**Comment by langyenan** [comment]
thank you @tedyu @gaorong ! 

I think current code is not following the eviction design of `DiskPressure` condition.
the proposal is: `DiskPressure -> reject all pods`
but the code is:  `DiskPressure + MemoryPressure -> admit`, guaranteed pods are not rejected any more.

`kubelet` seems to be working fine though, maybe here's the reason:

`On the other hand, the DiskPressure condition if true should dissuade the scheduler from placing any new pods on the node since they will be rejected by the kubelet in admission.` 

PS: above content can be found in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#scheduler
