### ISSUE TITLE
upgrading from 1.15.0 to 1.16.2 using `kubeadm upgrade` and get two versions of server

### ISSUE THREAD

**Issue by leowucn** [kubernetes/kubernetes#84446]
**What happened**:
I have a kubernetes cluster with version v1.15.0, and I upgraded the cluster to v1.16.2 using command `kubeadm upgrade`。Then I checked the version of the cluster multiple times, the results are below:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
The problem is that the server version of the k8s is not the same. Is it running two sets of k8s even after I upgrading to `v1.16.2`?

**What you expected to happen**:
I expect the versions of k8s server should be the same, but the first time I got `v1.16.2`, and the second time I got `v1.15.0`.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy k8s v1.15.0 on centos7, and then `kubeadm upgrade` to `v1.16.2`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux istio1.add.shbt.qihoo.net 4.4.177-1.el7.elrepo.x86_64 #1 SMP Sat Mar 23 12:42:53 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by leowucn** [comment]
@kubernetes/sig-cli-bugs

**Comment by neolit123** [comment]
hi, it's unlikely this can happen without kubeadm throwing an error.
do you have logs of the kubeadm upgrade command?

/triage support

**Comment by leowucn** [comment]
It's weird, it seems ok now, and I can's reproduce the bug now. So I will close the issue.
