### ISSUE TITLE
pod quota evaluator adds termination grace period twice

### ISSUE THREAD

**Issue by bazzargh** [kubernetes/kubernetes#84459]
**What happened**:
Dev asked me to explain why deletionTimestamps for pods were in the future, went to find the line that added the grace period before setting the timestamp and found this:
https://github.com/kubernetes/kubernetes/blob/58563975c126a5807b8e272d3cb393ef5d23fa0e/pkg/quota/v1/evaluator/core/pods.go#L398
`if now.After(deletionTime.Add(gracePeriod)) {`

**What you expected to happen**:
this code seems wrong in a couple of ways. deletionTimestamp already has the grace period added here (the line of code I was looking for...):
https://github.com/kubernetes/apiserver/blob/d1b1b64dd9245cc8aa4391714eaad8eef96fe5a9/pkg/registry/rest/delete.go#L132-L133

staging link for embed:
https://github.com/kubernetes/kubernetes/blob/58563975c126a5807b8e272d3cb393ef5d23fa0e/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L132-L133

...what is more, the grace period applied for a deletion may not be the grace period that applied to any given deletion. By just comparing to the deletionTimestamp, it would make the correct comparison. Furthermore, since deletion timestamps can be in the future, the quota evaluator should be checking deletionTimestamps, whether or not the pod had a grace period set.

Suggested fix to the quota evaluator would be:
```
	if pod.DeletionTimestamp != nil {
		now := clock.Now()
		deletionTime := pod.DeletionTimestamp.Time
		if now.After(deletionTime) {
			return false
		}
	}
```

**How to reproduce it (as minimally and precisely as possible)**:

It's a code review issue, you just need to read the code at the two links above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master (in the links above I selected master branch then pressed 'y' in github to get latest commit)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by bazzargh** [comment]
/sig scheduling
(I think?)

**Comment by tedyu** [comment]
@bazzargh 
Do you want to submit a PR ?

**Comment by bazzargh** [comment]
@tedyu no, for 2 reasons - I'm not familiar enough with that quota code to write an appropriate test, and legal at $job would take an age to approve me signing the CLA (they would eventually, it's just slow - and I should probably get those wheels in motion anyway, I'm sure we'll find more stuff)

**Comment by tedyu** [comment]
The following code from staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go around line 117 verifies your assumption:
```
                        newDeletionTimestamp := metav1.NewTime(
                                objectMeta.GetDeletionTimestamp().Add(-time.Second * time.Duration(*objectMeta.GetDeletionGracePeriodSeconds())).
                                        Add(time.Second * time.Duration(*options.GracePeriodSeconds)))
```

**Comment by xiaoxubeii** [comment]
You can submit PRs directly.
