### ISSUE TITLE
NodeLabelPriority as Score Plugin

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#84456]
**What would you like to be added**:
convert NodeLabelPriority to a score plugin
https://github.com/kubernetes/kubernetes/blob/571cea0519eef38d77524f4074b3bd31bb7f5091/pkg/scheduler/algorithm_factory.go#L393-L402

**Why is this needed**:
part of #83554

**Additional Notes**
#84297 as an example for converting a custom predicate to a filter plugin. The work required here should be very similar to it.

/sig scheduling
/cc @ahg-g
/priority important-soon
/help

**Comment by ahg-g** [comment]
should be added as a Score under the existing NodeLabel plugin.

**Comment by ahg-g** [comment]
/milestone v1.17

any progress on this one?

**Comment by josiahbjorgaard** [comment]
Hi bug triage team for 1.17, will this issue be resolved before code freeze on Nov. 14 (Thursday)?
