### ISSUE TITLE
Migrate CheckServiceAffinity custom predicate to Filter plugin

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#84455]
**What would you like to be added**:
convert CheckServiceAffinity to a filter plugin

**Why is this needed**:
part of #84187 which is part of #83554

**Additional Notes**
Please refer to #84297 as an example.

/sig scheduling
/cc @ahg-g
/priority important-soon
/help

**Comment by ahg-g** [comment]
Plugin name should be ServiceAffinity.

**Comment by ahg-g** [comment]
/milestone v1.17

@danielqsj any progress on this one?

**Comment by danielqsj** [comment]
@ahg-g I'm working on it, will submit PR soon

**Comment by danielqsj** [comment]
@ahg-g @liu-cong PTAL #84635, thanks

**Comment by josiahbjorgaard** [comment]
Hi, bug triage for the v1.17 release here checking in to see if this issue intended to be resolved before code freeze on Nov. 14?

**Comment by ahg-g** [comment]
> Hi, bug triage for the v1.17 release here checking in to see if this issue intended to be resolved before code freeze on Nov. 14?

Yes.
