### ISSUE TITLE
Registrations in conversion machinery are extremely misleading

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#84452]
Currently, there are two ways of registering conversion functions:
(1) Using AddConversionFuncs():
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L341
(2) Using AddConversionFunc()/AddGeneratedConversionFunc():
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L353

And what is extremely surprising, those registrations goes into two different and *separate* sets of conversions:

(a) The ones registered by (1), are NOT used at the top-level of conversions:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/conversion/converter.go#L494
(b) But as soon as you get into "default" mode (the reflection-based), the ones registered by (2) are NO LONGER used - only the ones from the first set are used:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/conversion/converter.go#L563

This is incredibly misleading, and I think is actually leading to couple places that I guess didn't mean to do that, e.g.:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go#L29

We need to get rid of (1), and clean this stuff up.

@kubernetes/sig-api-machinery-bugs 
@liggitt @deads2k @smarterclayton - FYI

**Comment by smarterclayton** [comment]
AddConversionFunc accepts a different signature, and is newer and more performance.  AddConversionFuncs is friendlier to humans but not as performant.

All code should be using AddConversionFunc

**Comment by wojtek-t** [comment]
Thanks for confirmation @smarterclayton - this is consistent with what I wrote above.

I will try to work on that in my free cycles, unless someone else will pick it up in the meantime.
The first step towards that - #84464 is out for review

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/84503 is the second piece out for review

Once this is done, the only remaining piece would be migrating the `meta` API group from using it.
I already started doing that in https://github.com/kubernetes/kubernetes/pull/84441 but there are a bunch of test failures there that I didn't dig deep enough to (from the first glance they seem to be test issues, but it requires much deeper look into).

**Comment by wojtek-t** [comment]
I'm fairly close with it (as you can see in https://github.com/kubernetes/kubernetes/pull/84441), but I doubt I will get that to 1.17 unfortunately.
