### ISSUE TITLE
ServiceAntiAffinityPriority as score plugin

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#84457]
**What would you like to be added**:
convert ServiceAntiAffinityPriority to a score plugin
https://github.com/kubernetes/kubernetes/blob/571cea0519eef38d77524f4074b3bd31bb7f5091/pkg/scheduler/algorithm_factory.go#L382-L392

**Why is this needed**:
part of #83554

**Additional Notes**
#84297 as an example for converting a custom predicate to a filter plugin. The work required here should be very similar to it.

/sig scheduling
/cc @ahg-g
/priority important-soon
/help

**Comment by ahg-g** [comment]
Plugin name should be ServiceAffinity (so we will have a Score for this one and Filter for CheckServiceAffinity predicate under the same plugin).

**Comment by ahg-g** [comment]
/milestone v1.17

@notpad any progress on this one?

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here, code freeze is in less then two weeks on Nov. 14 (Thursday). Looks like a PR is underway. If it isn't going to be resolved before then, can we move it out of the milestone?
