### ISSUE TITLE
Dependency Injection for Kubelet initialization & startup

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#84473]
Kubelet construction and initialization is, to put it frankly, a mess. More specifically here is a (partial) list of issues:

- Kubelet's constructor is over 550 lines (and the kubelet struct is 325 lines!)
  - But actually, a big chunk of construction is hidden in KubeDeps, which is initialized over a few hundred more lines in https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go
- Construction, initialization and startup are not clearly separated
  - Example: [indexers are run (started) in the constructor](https://github.com/kubernetes/kubernetes/blob/a8220072eca6f7ae9972340422dfb46a57fa777b/pkg/kubelet/kubelet.go#L450)
  - Example: [Dockershim initializes network plugins](https://github.com/kubernetes/kubernetes/blob/a8220072eca6f7ae9972340422dfb46a57fa777b/pkg/kubelet/dockershim/docker_service.go#L250)
- Start-up ordering is not well defined or understood. This lack of well-defined startup dependencies results in bugs like https://github.com/kubernetes/kubernetes/issues/42701, which require hacky workarounds like https://github.com/kubernetes/kubernetes/pull/42939 (faking the UID)
- Kubelet is full of circular dependencies. This is mostly a result of the monolithic Kubelet struct, and lack of understanding (or clarity) of inter-dependencies

The end result is a kubelet that is hard to modify or understand with a fragile startup. We can do better!

From https://blog.golang.org/wire:

> [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection) is a standard technique for producing flexible and loosely coupled code ...
> larger applications can have a complex graph of dependencies, resulting in a big block of initialization code that's order-dependent but otherwise not very interesting. It's often hard to break up this code cleanly, especially because some dependencies are used multiple times. Replacing one implementation of a service with another can be painful because it involves modifying the dependency graph by adding a whole new set of dependencies (and their dependencies...), and removing unused old ones. In practice, making changes to initialization code in applications with large dependency graphs is tedious and slow.

I think it's worth investigating a dependency injection approach for the Kubelet. There are already a number of existing tools for automating this in Go: https://github.com/avelino/awesome-go#dependency-injection (in particular I like the compile time checking from wire)

A prerequisite to implementing dependency injection will be to break the kubelet up into more modular components.

Applying dependency injection to construction (and maybe initialization) seems straight forward (though a lot of work). It applies a bit less directly to startup, but I think it's still a good tool for addressing that. Brainstorming: one possibility is to create "started" types, and reuse the DI tool to call those in order. Alternatively we could probably assume that the startup ordering matches the constructor dependency ordering, and reuse the graph.

/sig node
/area code-organization
/area kubelet

/help

**Comment by tedyu** [comment]
```
Kubelet construction and initialization is, to put it frankly, a mess.
```
I hear you.

**Comment by tallclair** [comment]
/cc @alejandrox1 
(this is tech debt)

**Comment by mtaufen** [comment]
Modularizing the Kubelet will probably give us some good ideas on how to restructure KubeletConfiguration in future config API versions.

**Comment by gongguan** [comment]
I have ever think about the split of kubelet struct [here](https://github.com/kubernetes/kubernetes/pull/81649#issuecomment-540257679).
Is any reasonable design or work welcome now?

**Comment by draveness** [comment]
> I have ever thought about the split of kubelet struct [here](https://github.com/kubernetes/kubernetes/pull/81649#issuecomment-540257679).
> Is any reasonable design or work welcome now?

I'm working on the task now and sort out the dependency graph in the kubelet

**Comment by fromanirh** [comment]
/triage accepted
/area kubelet
/priority backlog
/remove-lifecycle frozen
It seems we all want this improvement, but yet to be seen who can work on this cleanup :\

**Comment by gongguan** [comment]
@fromanirh I think this pr makes sense, what do you think?
https://github.com/kubernetes/kubernetes/pull/90643
