### ISSUE TITLE
rebooting node (and maybe just restarting kubelet) results in running pod going "Failed"

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#84479]
I'm investigating a case where a node has 6  'windriver.com/isolcpus' devices exposed to kubelet via a device plugin.  Kubelet is running with --topology-manager-policy=restricted.

A running pod is consuming 4 of the devices.  The node was rebooted and after coming back up kubelet logged this:
topology_hints.go:46] [devicemanager] Unable to generate topology hints: requested number of devices unavailable for 'windriver.com/isolcpus': requested: 4, available: 2

This resulted in the pod transitioning to a status of  "topology affinity error", from which I was unable to recover it and ended up deleting the pod.

It seems like kubelet forgot that it had already allocated the resources for that pod, but at the same time thought they were still in use on the node.  Some time later the resources are no longer considered to be in-use on the node and I was eventually able to start up a new pod which was able to allocate the 4 devices.

**Comment by cbf123** [comment]
@kubernetes/sig-node-bugs

**Comment by klueska** [comment]
My initial guess is an incorrect assumption in `GetTopologyHints()`. It is assumed that this will only ever  be called once per container for any given hint provider. If it is called more than once, then I can clearly see why this issue might occur. The `devicemanager` itself has recovered the devices for the container, but the implementation of `GetTopologyHints()` is treating it as a new request.

I need to dig a bit more into whether pod admit handlers are re-called after `kubelet` restart on already-running pods. If they are, then this is the root of the issue. If they are not, then something else is going on

**Comment by klueska** [comment]
Seems they do go through the admithander again: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1901

Surprised we didn’t catch this earlier…

**Comment by cbf123** [comment]
I think I found a corner case in your final patch.  If the device plugin is slow to start up (or to notice that kubelet has restarted) , then kubelet can try to regenerate topology hints before the device plugin is available to report the device affinity.

In this case kubelet will log "Resource X does not have a topology preference", and will return a topology hint of {0000000000000000000000000000000000000000000000000000000000000011 true} which then (if the topology manager policy is "single-numa-node") results in the pod going into a failed state with status of "Topology Affinity Error", and the running container (which was actually perfectly fine) getting shut down.

**Comment by klueska** [comment]
Yes. I can see how that would happen. It would have happened even before the last patch. Should be easily addressable by moving the logic to restore hints for containers that already have devices above the check whether the current resource is a „plugin“ resource yet or not.

**Comment by tedyu** [comment]
How about this change ?
```
diff --git a/pkg/kubelet/cm/devicemanager/topology_hints.go b/pkg/kubelet/cm/devicemanager/topology_hints.go
index 7a8d192589..a80989c2a2 100644
--- a/pkg/kubelet/cm/devicemanager/topology_hints.go
+++ b/pkg/kubelet/cm/devicemanager/topology_hints.go
@@ -37,15 +37,14 @@ func (m *ManagerImpl) GetTopologyHints(pod v1.Pod, container v1.Container) map[s
                resource := string(resourceObj)
                requested := int(requestedObj.Value())

+               // Only consider devices that actually contain topology information.
+               if aligned := m.deviceHasTopologyAlignment(resource); !aligned {
+                       klog.Infof("[devicemanager] Resource '%v' does not have a topology preference", resource)
+                       deviceHints[resource] = nil
+                       continue
+               }
                // Only consider resources associated with a device plugin.
                if m.isDevicePluginResource(resource) {
-                       // Only consider devices that actually container topology information.
-                       if aligned := m.deviceHasTopologyAlignment(resource); !aligned {
-                               klog.Infof("[devicemanager] Resource '%v' does not have a topology preference", resource)
-                               deviceHints[resource] = nil
-                               continue
-                       }
-
                        // Short circuit to regenerate the same hints if there are already
                        // devices allocated to the Container. This might happen after a
                        // kubelet restart, for example.
```

**Comment by tedyu** [comment]
See if #85038 does what @klueska described above.
