### ISSUE TITLE
dockerd very high memory consumption

### ISSUE THREAD

**Issue by davidq2q** [kubernetes/kubernetes#84508]
**What happened**:
Yesterday one of my nodes crashed because it was out of memory. One of the reasons why it crashed was that an elasticsearch data node pod went through the roof and jumped from 30 Gi memory to 50 Gi. However besides the elasticsearch process I also noticed in htop that dockerd consumed 33% of the systems memory which is 120 Gi.

After the node crashed I imposed resource limits on more pods. Already had them on 80% of my containers except for ES. After the node rebooted this reduced memory consumption significantly. But also noticed that the dockerd process was not consuming 33% of the memory anymore. Now two of my nodes are fine. Yet a last one is still having the dockerd process consuming 33% of the memory. Now in total it's still fine with 77% memory consumption but I still want to know what is causing it. I will double the ram in the servers this week to 240 Gi to get some breathing space.

I also noticed that any docker command such as 
```docker rmi $(docker images --filter "dangling=true" --format "{{.ID}}")```
or ```docker stats``` is not working on the node that has dockerd consuming 33% of the memory. The commands just freeze and return no output.
While they do return something at the two other nodes. However the node does seem to run docker containers

**What you expected to happen**:
Dockerd to consume a normal amount of memory and not eating up 33%. Also the docker commands to work properly.

**How to reproduce it (as minimally and precisely as possible)**:
Actually I have no idea what caused it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Kubernetes v1.13.5
- Cloud provider or hardware configuration:
Bare Metal
3x HP DL360 G9 
120 Gi Memory
2x 20 cores Intel Xeon E5
- OS (e.g: `cat /etc/os-release`):
```PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```Linux node1 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 GNU/Linux```
- Install tools:
Ansible
Kubespray
Terraform
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
@davidq2q 
Do you still observe this problem ?

**Comment by davidq2q** [comment]
@tedyu yes I still observe the problem in our current production cluster. However I am in the process of migrating everything to a new kubernetes cluster that has a entirely different setup.

Our old production cluster which has this problem is running on 5 bare metal machines running on Debian 9 stretch. Provisioned with kubespray and using metallb in vrrp mode to assign ip's to kubernetes services and openebs-cstor for storage. 

I do not know what is causing docker to freeze but there are too many components where it could go wrong. Most of them core processes that cannot be messed up or restarted otherwise everything falls apart. As a temporary solution before migrating to a new cluster I added 160 gigabyte of memory to every node. As of now every node is now reaching around 100 gigabyte of memory usage in a time span of 3 months, slowly continuing to climb. Kubernetes can provision pods and continues to run. However a lot of docker cli commands either are extremely slow or do not return any output.

My new kubernetes cluster consists of 11 KVM virtual machines in a VM cluster all running flatcar linux. Provisioned with RKE and using ECMP routing in our fortinet firewall so our subnet machines can get access to the kubernetes service ip range instead of through vrrp with metallb. Openebs is replaced with ceph nautilus that is running outside the virtual machines. A plus from RKE is that it supports nearly all operating systems as long as they have docker installed. And that kubernetes runs in its entirety in docker containers. Hopefully making it a bit more manageable.

**Comment by tedyu** [comment]
```
slowly continuing to climb
```
Probably you can periodically use pprof to capture the memory uage of kubelet, etc so that you can have idea what might have caused the (potential) leak.
