### ISSUE TITLE
[Flaky Jobs] Reduce CI jobs flakiness

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#84514]
There are a lot of jobs that are important for every release.  

Most of the jobs are being reported from `testgrid` as `FLAKY` and the situation always does an unpredictable rotation. 

With this issue opened, we want to track the `FLAKY` jobs and take the necessary actions to reduce or fix their flakiness.

## Current flakes to start with:

# sig-release-master-blocking
`integration-master` 
 ```
41 of 468342 tests (0.0%) and 16 of 162 runs (9.9%) failed in the past 7 days
```

`verify-master`
```
6 of 5850 tests (0.1%) and 3 of 150 runs (2.0%) failed in the past 7 days
```

# sig-release-master-informing
`Conformance - OpenStack: FLAKY`
```
3 of 3420 tests (0.1%) and 1 of 12 runs (8.3%) failed in the past 7 days
```
`gce-cos-master-default`
```
312 of 193032 tests (0.2%) and 101 of 252 runs (40.1%) failed in the past 7 days
```
`gce-cos-master-slow`
```
506 of 47094 tests (1.1%) and 69 of 167 runs (41.3%) failed in the past 7 days
```
`kubeadm-kind-master`
```
110 of 23157 tests (0.5%) and 26 of 83 runs (31.3%) failed in the past 7 days
```
`kubeadm-kinder-upgrade-1-16-master`
```
30 of 23738 tests (0.1%) and 11 of 83 runs (13.3%) failed in the past 7 days
```
`gce-master-scale-performance`
```
12 of 98 tests (12.2%) and 3 of 7 runs (42.9%) failed in the past 7 days
```
`aks-engine-azure-1-16-windows`
```
33 of 7275 tests (0.5%) and 2 of 25 runs (8.0%) failed in the past 7 days
```
`post-release-push-image-k8s-cloud-builder`
```
No results in the past 7 days
```

# release-misc
`release-test`
```
6 of 330 tests (1.8%) and 4 of 33 runs (12.1%) failed in the past 7 days
```
`pull-cip-e2e`
```
2 of 5 tests (40.0%) and 2 of 5 runs (40.0%) failed in the past 4 days
```
`kops-build`
```
30 of 323 tests (9.3%) and 30 of 323 runs (9.3%) failed in the past 7 days
```

/sig release
/cc @guineveresaenger @justaugustus @alejandrox1 @alenkacz

**Comment by droslean** [comment]
`Conformance - OpenStack` FLAKY

@kubernetes/sig-scheduling-misc 
Can you check [ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1572106709](https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1572106709) ?

**Comment by ahg-g** [comment]
> `Conformance - OpenStack` FLAKY
> 
> @kubernetes/sig-scheduling-misc
> Can you check [ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1572106709](https://prow.k8s.io/view/gcs/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1572106709) ?

@ravisantoshgudimetla @damemi do you guys mind looking into this or tag the right people who can debug the issue?

**Comment by damemi** [comment]
I will try to find some openstack people to help with this

**Comment by msau42** [comment]
For the projected volumes test, it looks like the test container returned with an error code:
Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:OCI runtime start failed: container process is already dead: unknown

But from the output, it seems ok:
I1030 08:41:12.500] Oct 30 08:41:06.866: INFO: Output of node "bootstrap-e2e-minion-group-t61q" pod "pod-projected-secrets-6b2d585f-5051-4c3c-b2f8-98b8ea6f4cd2" container "projected-secret-volume-test": mode of file "/etc/projected-secret-volume/data-1": -r--------
I1030 08:41:12.500] content of file "/etc/projected-secret-volume/data-1": value-1

which should match the test expectations.  The test is configured with [mode 0400](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/projected_secret.go#L53)

Need to investigate this mounttest program further to figure out how it can fail after printing this.

**Comment by droslean** [comment]
@dameni Any news? 

We noticed that the test `[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset [Conformance]` flakes time to time. 

link: https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master
job: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1192026422923759619

**Comment by damemi** [comment]
@droslean not from me, I forwarded the OpenStack flake to that team and they'll take a look at it

**Comment by droslean** [comment]
@damemi Thanks a lot!

**Comment by liggitt** [comment]
is a general issue like this actionable? is this tracking specific jobs/tests and assigned to specific sigs/owners?

**Comment by liggitt** [comment]
> For the projected volumes test, it looks like the test container returned with an error code:
> 
> ```
> Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:OCI runtime start failed: container process is already dead: unknown
> ```
> 
> But from the output, it seems ok:
> 
> ```
> I1030 08:41:12.500] Oct 30 08:41:06.866: INFO: Output of node "bootstrap-e2e-minion-group-t61q" pod "pod-projected-secrets-6b2d585f-5051-4c3c-b2f8-98b8ea6f4cd2" container "projected-secret-volume-test": mode of file "/etc/projected-secret-volume/data-1": -r--------
> I1030 08:41:12.500] content of file "/etc/projected-secret-volume/data-1": value-1
> ```
> 
> which should match the test expectations. The test is configured with [mode 0400](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/projected_secret.go#L53)
> 
> Need to investigate this mounttest program further to figure out how it can fail after printing this

opened https://github.com/kubernetes/kubernetes/issues/86312 to track this specifically

**Comment by spiffxp** [comment]
I'm inclined to suggest we close this unless it's actionable, the information in the description isn't specific enough to know what needs to be done to close this out

**Comment by droslean** [comment]
/close

We should have a single issue open for each flake.
