### ISSUE TITLE
Namespace API documentation needs updates

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kubernetes#84515]
**What happened**:

I have compared the API operations between the Namespace design spec and the Namespace 1.16 API reference and found a couple of inconsistencies.

Namespace design spec can be found at 
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/namespaces.md

Namespace 1.16 API reference can be found at 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#namespace-v1-core

Discrepancy #1:  1.16 API reference does not mention support for FINALIZE action for Namespace API i.e. PUT /api/{version}/namespaces/{namespace}/finalize is missing

Discrepancy #2:  Namespace design doc does not mention support for PATCH action 
i.e. PATCH /api/v1/namespaces/{name} is missing

**What you expected to happen**:

Both documents should be aligned and consistent.

/sig kind/documentation
/cc @liggitt

**Comment by liggitt** [comment]
patch is uniformly supported on all resources that support get and update. we typically don't retrofit every design document with details of new generic behavior.

I'm not sure why the API docs do not include finalize details. They are included in the openapi spec that is used to generate those docs. From https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json:

```json
    "/api/v1/namespaces/{name}/finalize": {
      "parameters": [
        {
          "description": "When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed",
          "in": "query",
          "name": "dryRun",
          "type": "string",
          "uniqueItems": true
        },
        {
          "description": "fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.",
          "in": "query",
          "name": "fieldManager",
          "type": "string",
          "uniqueItems": true
        },
        {
          "description": "name of the Namespace",
          "in": "path",
          "name": "name",
          "required": true,
          "type": "string",
          "uniqueItems": true
        },
        {
          "description": "If 'true', then the output is pretty printed.",
          "in": "query",
          "name": "pretty",
          "type": "string",
          "uniqueItems": true
        }
      ],
      "put": {
        "consumes": [
          "*/*"
        ],
        "description": "replace finalize of the specified Namespace",
        "operationId": "replaceCoreV1NamespaceFinalize",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/io.k8s.api.core.v1.Namespace"
            }
          }
        ],
        "produces": [
          "application/json",
          "application/yaml",
          "application/vnd.kubernetes.protobuf"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/io.k8s.api.core.v1.Namespace"
            }
          },
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/io.k8s.api.core.v1.Namespace"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "schemes": [
          "https"
        ],
        "tags": [
          "core_v1"
        ],
        "x-kubernetes-action": "put",
        "x-kubernetes-group-version-kind": {
          "group": "",
          "kind": "Namespace",
          "version": "v1"
        }
      }
    },
```

**Comment by stevebail** [comment]
/cc @liggitt
Good to know, thank you!

Do you think we should also update the description for the finalize action from the openapi spec as well?
For instance, I see PUT /api/v1/namespaces/{name}/finalize has the following description: 
"description": "replace finalize of the specified Namespace"

I don't know about you but this is not very a good description :)
Maybe it should say something like this:
"description": "update the list of finalizers for the specified Namespace"

Another option is "clear the list of finalizers for the specified Namespace" but I am not sure this is 100% accurate.
Here I am assuming that each controller is responsible to remove one and one finalizer at a time.

Related question #1: do you foresee a use case where the list is larger than 2 values?
Related question #2: can the user update the spec.finalizers though other means, for instance doing a PUT or PATCH on /api/v1/namespaces/{name}?

**Comment by liggitt** [comment]
> Do you think we should also update the description for the finalize action from the openapi spec as well?
> For instance, I see PUT /api/v1/namespaces/{name}/finalize has the following description:
> "description": "replace finalize of the specified Namespace"

Not easily. That is generated from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L689, which is clever, but unlikely to work well for arbitrary subresources. That generation should probably be made more generic.

> Related question #1: do you foresee a use case where the list is larger than 2 values?

I don't typically see it happen, but nothing prevents multiple finalizer actors from using that field. Each is expected to remove only itself via the put to the /finalizers subresource.

> Related question #2: can the user update the spec.finalizers though other means, for instance doing a PUT or PATCH on /api/v1/namespaces/{name}?

yes, spec.finalizers can be added at creation time or via a put/patch to `/api/v1/namespaces/{name}`

**Comment by stevebail** [comment]
@liggitt
I just tried to a create a NS with the following spec.finalizers:

apiVersion: v1
kind:  Namespace
metadata: 
  name: alpha
spec:
  finalizers:
  - controller

I got the following error rmessage:
The Namespace "alpha" is invalid: spec.finalizers: Invalid value: "controller": name is neither a standard finalizer name nor is it fully qualified

Two follow-up questions:
1) What are the accepted standard finalizer names other than kubernetes? 
2) What benefits does spec.finallizers bring? I am still trying to figure out its purpose. What do we loose (if any) assuming spec.finalizers and finalize operation are not supported?

**Comment by stevebail** [comment]
apiVersion: v1
kind:  Namespace
metadata: 
  name: alpha
spec:
  finalizers:
  - controller

**Comment by stevebail** [comment]
See attached file for namespace yaml manifest

[namespace.pdf](https://github.com/kubernetes/kubernetes/files/3795809/namespace.pdf)

**Comment by liggitt** [comment]
It need to be namespaced (e.g. `example.com/myfinalizer`)

It allows a controller to participate in namespace termination before the namespace API object is removed. The canonical example is the namespace controller in kubernetes that first ensures all namespaced resources within the namespace are deleted before releasing the terminating namespace to be removed.

**Comment by stevebail** [comment]
@liggitt 
Last 3 questions before closing this issue :)

I see the following NS API calls are supported on the /status subresource:
- get /api/v1/namespaces/{name}/status
- put /api/v1/namespaces/{name}/status
- patch /api/v1/namespaces/{name}/status

1) What is the purpose of the NS /status subresource? 

2) Will  get /api/v1/namespaces/{name} provide the same status data as get /api/v1/namespaces/{name}/status?

3) How come the API client is allowed to change the NS status? I was thinking that NS status is always populated by the system but I see this is not true (?)

**Comment by liggitt** [comment]
> What is the purpose of the NS /status subresource?

To allow modification of the status substruct on the resource, and to allow permissioning it separately (can allow a normal user to write to `/api/v1/namespaces/{name}` to change labels/annotations without letting them change status)

> Will get /api/v1/namespaces/{name} provide the same status data as get /api/v1/namespaces/{name}/status?

Yes, gets return the same data

> How come the API client is allowed to change the NS status? I was thinking that NS status is always populated by the system but I see this is not true (?)

The system makes changes to status via the API.
