### ISSUE TITLE
Hugepages PRs Tracker

### ISSUE THREAD

**Issue by bg-chun** [kubernetes/kubernetes#84526]
# Note : The issue in enhancement repo will be used for PRs Tracker https://github.com/kubernetes/enhancements/issues/1539

--------------------------------------------------------------------------------------------------------------------------------------

This issue is Hugepages PRs Traker.
[This google doc](https://docs.google.com/document/d/1Xnb3ioEH_JmWLdFJ-i6Lp7jFc_fDuzzAa2oEXJglBbM/edit#) contains more information for these PRs.

[Hugepages KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190129-hugepages.md) have been updated for serveral enhancements.
- Support container isolation of hugepages / [KEP Update1](https://github.com/kubernetes/enhancements/pull/1199)(merged)
- Support multi size hugepages at host level /  [KEP Update2](https://github.com/kubernetes/enhancements/pull/1271)(merged)
- Support multi size hugepages at container level / [KEP Update2](https://github.com/kubernetes/enhancements/pull/1271)(merged)
- Support hugepage reservation for system-level service / part of original KEP

Now, We have some pending PRs for hugepages.
Some of them reviewed, but most of them need review, they need attention.

## Pending PRs
- Note: `*` means the PR is the top of dependency.  

PR | Description | Status | Dep | Owner
-- | -- | -- | -- | --
#83614* | Update CRI to support hugepages | merged |   | @bg-chun
#84154 | Support for setting hugepages limit during container creation | merged | #83614 | @ohsewon
#84701 | Update Dockershim | WIP | #84154 | @admanV
[M40160](https://github.com/moby/moby/pull/40160) | Add hugepages field to resource(moby) | change requrested| #83614 | @bg-chun
[C1332](https://github.com/containerd/cri/pull/1332) | Update Container runtimes(containerd) | got LGTM | #84154 | @bg-chun
[C2940](https://github.com/cri-o/cri-o/pull/2940) | Update Container runtimes(cri-o) | Merged | #84154 | @bg-chun
#87118 | e2e_node test for container isolation of hugepage | need review | #84154 | @ohsewon
#82820* | Support for pre-allocated hugepages with 2+ sizes(for host) | Merged |   | @odinuge
#84051 | Support for multiple sizes huge pages(for pod) | need sig review | #82820 | @bart0sh
#80831 | Add support for removing unsupported huge page sizes | got lgtm |   | @odinuge
#83541 | Support for reserving hugepages for system and kubelet | need 2rd review |   | @odinuge
#80605 | Add huge page usage stats to kubectl describe node | need CLI review |   | @odinuge
#81774 | Bugfix: Kubelet doesn’t update /sys/fs/cgroup/hugetlb/kubepods/hugetlb.2MB.limit_in_bytes upon Node Status Update | got lgtm |   | @rojkov

**Comment by odinuge** [comment]
I think https://github.com/kubernetes/kubernetes/pull/80831 should be added to the list too.

**Comment by bg-chun** [comment]
@odinuge I added it :)
