### ISSUE TITLE
[Failing Test] build-packages-debs (ci-release-build-packages-debs)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#84548]
**Which jobs are failing**:
`build-packages-debs (ci-release-build-packages-debs)`

**Since when has it been failing**:
29 Oct 11:47 PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#build-packages-debs

**Reason for failure**:
```console
 curl -sSL --fail --retry 5 \
	"https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.17.0/crictl-v1.17.0-linux-amd64.tar.gz" \
	| tar -C ./bin -xz
curl: (22) The requested URL returned error: 404 Not Found
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable:
```

**Anything else we need to know**:
/cc @alenkacz @alejandrox1 @hasheddan @Verolop

**Comment by droslean** [comment]
@dchen1107 Can you check why there is no such release in `cri-tools` repo?

**Comment by justaugustus** [comment]
Opened https://github.com/kubernetes/test-infra/pull/15084 to fix this.
Basically what's happening is we're trying to build a package from a release that doesn't exist yet.
`cri-tools` cuts a release closer to the actual Kubernetes release, so this is expected.
