### ISSUE TITLE
JSONSchemaProps reports to be Draft-04 but is used by OpenAPI v3 schema

### ISSUE THREAD

**Issue by Capstan** [kubernetes/kubernetes#84546]
**This is a low priority, mainly documentation-related issue.**

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go describes `JSONSchemaProps` as [JSON Schema Draft-04](https://json-schema.org/specification-links.html#draft-4). However, it is used by https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto's `CustomResourceValidation` which purports to be OpenAPI v3 Schema. OpenAPI v3 uses [Draft-05](https://json-schema.org/specification-links.html#draft-5), aka [draft-wright-json-schema-00](https://tools.ietf.org/html/draft-wright-json-schema-00), as described [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types).

The [differences](https://tools.ietf.org/html/draft-wright-json-schema-00#appendix-B) between 04 and 05 look to be pretty minimal, perhaps limited functionally just to restricting the use of `$ref` to where schemas are supported. As such, this probably has no functional impact, except that if k8s is applying 04 validation, it might be more permissive.

**Comment by liggitt** [comment]
cc @sttts
/remove-kind bug
/kind documentation

**Comment by Capstan** [comment]
Please disregard. Per http://json-schema.org/draft-06/json-schema-release-notes.html#q-what-happened-to-draft-05, one is not supposed to implement or advertise support for Draft 05. I will follow up with OpenAPI v3.

**Comment by Capstan** [comment]
Filed OAI/OpenAPI-Specification/issues/2049
