### ISSUE TITLE
Remove the pod Info in waitingPodsMap When the pod is deleted

### ISSUE THREAD

**Issue by denkensk** [kubernetes/kubernetes#84554]
**What would you like to be added**:
When the pod is scheduled to the `permit` phase and I delete the pod,  the pod still remains in the `waitingPodsMap` until the plugin allow/reject/timeout(Especially when waiting for a long time). 

**Why is this needed**:
We need to take the initiative to delete the data in the `waitingPodsMap` and terminate the process in waiting state of `permit` plugin to ensure data accuracy, if the pod has been deleted

/cc @ahg-g
/priority important-soon
/assign
/sig scheduling

**Comment by ahg-g** [comment]
I think we can update the event handler for deleting pods to reject the pod. Can you send a PR for that?

**Comment by denkensk** [comment]
OK，I will send a pr for it.
