### ISSUE TITLE
Convert interpod affinity priority to a "map-reduce" pattern

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#84570]
**What would you like to be added**:

The pre-work for this is done, so converting it to map-reduce should be straightforward and includes the following steps:

1) Factor out [topologyPairToScore calculation](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L103-L211) to be run in PriorityMetadataProducer, and store the result in [priorityMetadata](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/metadata.go#L54)

2) The [node count calculation](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L216-L219) is the map function.

3) The [score normalization logic](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L230-L242) is the reduce function. Reduce will include calculating maxCount/minCount as well.

**Why is this needed**:
This is required as a pre-request to converting it to a Score plugin.

/sig scheduling
/help

**Comment by ahg-g** [comment]
/assign @draveness 

@draveness would you like to work on this one?

**Comment by draveness** [comment]
> /assign @draveness
> 
> @draveness would you like to work on this one?

Sure, thanks for asking

/remove-help
