### ISSUE TITLE
kubeadm: allow to use the skip-phases option during upgrade

### ISSUE THREAD

**Issue by JrCs** [kubernetes/kubernetes#84584]
**Allow to skip some phases during upgrade**:
It will be great to have the `--skip-phases` option for the `kubeadm upgrade` command, or better have a key in the ClusterConfiguration manifest to specify phases to be skip.

**Why is this needed**:
I bootstrap my k8s cluster without the kube-proxy addons (using `kubeadm init --skip-phases=addon/kube-proxy` command). But when i upgrade it with `kubeadm upgrade` the kube-proxy addon is install.

@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by JrCs** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by neolit123** [comment]
/close

`kubeadm upgrade node` should already support phases and skip

> phases=addon/kube-proxy command). But when i upgrade it with kubeadm upgrade the kube-proxy addon is install.

this is tracked here:
https://github.com/kubernetes/kubeadm/issues/1318
