### ISSUE TITLE
multi master with nginx as vip， when leader master is down，the other masters can not became leader

### ISSUE THREAD

**Issue by bloodstars** [kubernetes/kubernetes#84586]
**What happened**:
when leader master is down，other masters can not became leader, so all the pod that need to be evicted are all pending.........,so i need to restart container kube-scheduler and kube-controller, after that everything is ok.........

**Anything else we need to know?**:
the kube-scheduler and kube-controller stucked and keep logging "E1031 07:00:14.976796       1 leaderelection.go:270] error retrieving resource lock kube-system/kube-scheduler: Get https://10.5.4.238:36443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)";

VIP(10.5.4.238) is nginx server, using config :
stream{
    upstream kube {
      server 10.5.4.223:6443 max_fails=1 fail_timeout=60s;
      server 10.5.4.231:6443 max_fails=1 fail_timeout=60s;
      server 10.5.4.227:6443 max_fails=1 fail_timeout=60s;
    }
    server {
        listen       36443;
        proxy_pass   kube;
    }
}

**Environment**:
- 1.12.3
- centos 7.6
- kernel 4.19.2
- kubeadm
- flannel vxlan

**Comment by neolit123** [comment]
this seems related to your setup, in my tests temporary shutting down the primary control-plane node, gives leadership to another control-plane node.
