### ISSUE TITLE
Errors returned from pod_container_manager_linux Destroy to remove a pods cgroup are swallowed

### ISSUE THREAD

**Issue by mrobson** [kubernetes/kubernetes#84595]
**What happened**:

Housekeeping sync loop finds an orphaned pod and tries to clean it up. The kubepod slice, as seen below, is not removed by `cleanupOrphanedPodCgroups -> go pcm.Destroy(val)` with no indication as to why. This leads to the docker scope timing out and entering a failed state. The returned error(s) from runc are swallowed making debugging difficult.

```
Oct 16 21:18:26 server atomic-openshift-node: I1016 21:18:26.531606    1694 kubelet.go:1907] SyncLoop (housekeeping)
Oct 16 21:18:26 server atomic-openshift-node: I1016 21:18:26.670054    1694 kubelet_pods.go:1082] Killing unwanted pod "test-cron-three-1571285880-bb"
Oct 16 21:18:26 server atomic-openshift-node: I1016 21:18:26.792307    1694 kubelet_pods.go:1682] Orphaned pod "20f666f1-f095-11e9-916f-0050568379a2" found, removing pod cgroups
Oct 16 21:18:26 server systemd: Stopping libcontainer container 4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.
Oct 16 21:19:57 server systemd: docker-4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.scope stopping timed out. Killing.
Oct 16 21:19:57 server systemd: Stopped libcontainer container 4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.
Oct 16 21:19:57 server systemd: Unit docker-4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.scope entered failed state.
```

**What you expected to happen**:
As per other areas of the sync loop, useful errors are logged at debug level due to the async calls.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by tedyu** [comment]
@mrobson 
Have you seen the comment above pcm.Destroy() call ?
```
		// We ignore errors thrown by the method, as the housekeeping loop would
		// again try to delete these unwanted pod cgroups
```
Did you have a chance to look at kubelet log to see if the above was true ?

**Comment by tedyu** [comment]
This would give us some clue about the error:
```
diff --git a/pkg/kubelet/kubelet_pods.go b/pkg/kubelet/kubelet_pods.go
index 345566d1026..27a621fc4e7 100644
--- a/pkg/kubelet/kubelet_pods.go
+++ b/pkg/kubelet/kubelet_pods.go
@@ -1735,7 +1735,11 @@ func (kl *Kubelet) cleanupOrphanedPodCgroups(cgroupPods map[types.UID]cm.CgroupN
                // by first killing all the attached processes to these cgroups.
                // We ignore errors thrown by the method, as the housekeeping loop would
                // again try to delete these unwanted pod cgroups
-               go pcm.Destroy(val)
+               go func() {
+                       if err := pcm.Destroy(val); err != nil {
+                               klog.Errorf("encountered error during destroy: %v", err)
+                       }
+               }()
        }
 }
```

**Comment by mrobson** [comment]
@tedyu yes, definitely looked! In this specific situation, the pods are never retried.

What we see happen with these pods:

ADD -> RECONCILE -> Started Volumes -> Created slice -> No sandbox for pod -> Started libcontainer -> ContainerStarted -> ContainerStarted -> RECONSILE -> ContainerDied -> RECONCILE -> Unmounts -> Killing unwanted pod -> Orphaned removing pod cgroups -> container kill failed because of 'container not found' or 'no such process' -> cleanup: failed to unmount secrets -> ContainerDied -> Container garbage collection succeeded -> SyncLoop (SYNC): 141 pods (including this one) -> stopping timed out. Killing. -> Stopped libcontainer -> Removed slice -> DELETE -> REMOVE -> err: pod not found

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L1714

Destroy all cgroups of the pod that should not be running, by first killing all the attached processes to these cgroups. We ignore errors thrown by the method, as the housekeeping loop would again try to delete these unwanted pod cgroups

Despite running, the slice is not removed and we do not log or indicate why. Subsequently, the pod is NOT determined to be either an active pod or for some reason not in the cgroup list that is passed into kl.cleanupOrphanedPodCgroups(cgroupPods, activePods) during housekeeping loops.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L1064

A more detailed look, which I believe is accurate ;):

**Comment by mrobson** [comment]
@tedyu your change is of a similar nature to what I proposed in my PR for this issue, just a level higher. I think there are a few areas noted above the could help further debug this.. Still haven't been able to get my PR merged with additional logging.

**Comment by tedyu** [comment]
The following code was relatively new (compared to when you logged this issue):
```
	containersTerminal = notRunning(status.ContainerStatuses)
	// The kubelet must accept config changes from the pod spec until it has reached a point where changes would
	// have no effect on any running container.
	podWorkerTerminal = status.Phase == v1.PodFailed || status.Phase == v1.PodSucceeded || (pod.DeletionTimestamp != nil && containersTerminal)
```

**Comment by mrobson** [comment]
Indeed... I looked into it a while ago and those changes are new via: https://github.com/kubernetes/kubernetes/pull/88440 - Could definitely make a different if the issue is related to pod getting filtered out from activePods when they have not been fully cleaned up yet on the subsequent housekeeping syncloop runs.

**Comment by mrobson** [comment]
@tedyu I think 88440 is promising, but I still think it makes sense to add some logging here. Do you want want to proceed with my open PR, your suggestion in kubelet_pods.go or both?

**Comment by tedyu** [comment]
You can proceed with your PR.
