### ISSUE TITLE
tests: should be able to pull from private registry with secret on Windows containerd

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#84609]
**Which jobs are failing**:

containerd-l2bridge-windows-master
containerd-overlay-windows-master

**Which test(s) are failing**:

[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]

**Since when has it been failing**:

Unknown.

**Testgrid link**:

https://testgrid.k8s.io/sig-windows#containerd-l2bridge-windows-master
https://testgrid.k8s.io/sig-windows#containerd-overlay-windows-master

**Reason for failure**:

When creating the container, the following error occurs:

    Failed: Error: failed to create containerd task: hcsshim::CreateComputeSystem image-pull-test: The container operating system does not match the host operating system.

Windows Server 2019 is used in the testing environment, and the image ``gcr.io/authenticated-image-pulling/windows-nanoserver:v1`` is supposed to be based on the ``windows/nanoserver:1809`` image, and the test is passing in all other jobs that are using docker instead of containerd.

But the image ``gcr.io/authenticated-image-pulling/windows-nanoserver:v1`` has been built at the beggining of 2019, so it's most likely outdated (the Microsoft official images are updated regularly), which could lead to the OS version mismatch.

Note that most of the other tests are passing for the containerd jobs, which are using the test images hosted in the ``e2eteam`` registry, which are based on the ``mcr.microsoft.com/windows/servercore:ltsc2019`` image (LTS 2019 and 1809 have the same OS version), and they're always up-to-date.

One solution could be to republish the ``gcr.io/authenticated-image-pulling/windows-nanoserver:v1`` image based on a freshly pulled nanoserver image.

**Anything else we need to know**:

/sig windows
/sig testing

**Comment by PatrickLang** [comment]
@bclau - is the login/password public so this can be debugged outside of the prow cluster?

**Comment by PatrickLang** [comment]
@bclau  - what containerd branch / hash was it built from?

**Comment by jterry75** [comment]
@Random-Liu - Some part of my memory thinks this was fixed in upstream containerd/cri. Do you recall any items around this recently?
