### ISSUE TITLE
The Scheduler should be Numa Aware and options should be given in the pod defination for the type of Numa awareness required.

### ISSUE THREAD

**Issue by DeySouvik** [kubernetes/kubernetes#84601]
**What would you like to be added**:
Currently the topology manager options does take care of attaching the cpu cores to the local numa node, but it does not consider the pci device in case SR-IOV VFs are used. As in that case to get best performance we to align the pci device and cpu from the same numa node to avoid passing network packets over QPI links. This is very important for high network throughput applications specially telecom apps.

**Why is this needed**:
As mentioned above we need to consider the pci device location too while selecting the proper numa node to place the POD. Without this there will be high performance impacts.

**Comment by DeySouvik** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by cbf123** [comment]
How are your devices reported to kubelet?  The current device plugin API allows the device plugin to report the NUMA node of each device, and the kubelet DeviceManager will generate topology hints and pass them to the topology manager.

For sriov-network-device-plugin these changes were made in commits https://github.com/intel/sriov-network-device-plugin/commit/000db15405f3ce3b7c2f9feb180c3051aa3f7aea and https://github.com/intel/sriov-network-device-plugin/commit/3abde5105b6ccc97a146f9e2baa31fef24fe258c

**Comment by DeySouvik** [comment]
Yes the SR-IOV device manager does report back the topology info with the numa node of the pci device(VF). SO you mean to say that once the numa node of the pci is known to the scheduler, it will use that info to check for the cpu resource available and if that is there then the placement/bind of the pod will be successful otherwise not correct ? 
Assuming the topology-manager-policy for kubelet is set to single-numa-node .

**Comment by cbf123** [comment]
Right.  There are open issues related to the topology manager, but the general idea is that the device plugin would report the NUMA affinity for each device, and (assuming resources and node selectors are set up appropriately) the pod will be placed on a host and NUMA node where all the resources satisfy the topology manager policy.

**Comment by JScheurich** [comment]
Isn't it too late to check NUMA topology of CPUs and PCI devices on the node after the scheduling decision has already been taken without taking any of the NUMA aspects into account? Pod creation can fail on the selected node, but might have been successful on another node. Ideally the scheduler (filter and/or scorer) should become NUMA topology aware and select the best node up front.

Also, it should be a pod/container choice to request vCPUs and PCI devices from a single NUMA node or not. Some application may require this, while others only prefer NUMA locality but would accept remote PCI devices rather than failing. Why is that a node policy?

**Comment by cbf123** [comment]
I agree that NUMA affinity should be a pod/container choice.  I brought it up with the people working on the TopologyManager during the previous cycle but it was deemed too late in the cycle to implement it.

**Comment by cbf123** [comment]
I had assumed the scheduler was checking with kubelet on the node before actually assigning the pod to the node.  If it's not doing that, then maybe a separate issue should be opened on that issue.

I've already opened https://github.com/kubernetes/kubernetes/issues/84757 for a separate but related issue.

**Comment by JScheurich** [comment]
As far as we understand the scheduler code, it only looks at int64 resources MilliCPU, Memory, EphemeralStorage, AllowedPodNumber and a map of named ScalarResources for deciding if a Pod fits a node based on the Request and Allocatable resources in nodeInfo. NUMA topology/affinity is neither known to the scheduler nor part of the Pod request today.

Hence, the scheduler is bound to take uninformed decisions that may be sub-optimal (NUMA locality would be better on a different node) or, in the worst case, even rejected by the topology manager on the selected node (as in your issue).

Being new to the Kubernetes community, I have the feeling that exposing the scheduler to NUMA topology of nodes and NUMA affinity of (device) resources and introducing filters and scores to takes these into account might be a bigger undertaking than can be driven by a simple bug ticket.

How would you recommend to proceed?

**Comment by cbf123** [comment]
Yeah, I looked at the scheduler code and it appears you're correct.  This is disappointing.  I'm actually fairly new to Kubernetes myself.  I've been reviewing and testing the topology manager work but mostly looking at the NUMA-correctness on a single node rather than the overall cluster-level view.

I think it'd be reasonable to start with another bug report (the title of this one is misleading) specifically covering the fact that the scheduler is not NUMA-aware when making decisions and could therefore place pods on suboptimal or totally invalid nodes.  The fact that they then get stuck there should be covered by the issue I mentioned above.

**Comment by DeySouvik** [comment]
Should we update the title of this issue itself than opening a newer one ?

**Comment by DeySouvik** [comment]
Did modified the title. Feel free to update the same.@cbf123

@kubernetes/sig-scheduling-feature-requests

**Comment by cbf123** [comment]
Your blurb talking about SRIOV and the topology manager is now different from the title of the issue...which could be confusing.  That's why I had suggested creating a new issue.

**Comment by bg-chun** [comment]
I suggested a single-NUMA policy to sig-node and contributors in July, with this [feedback document](https://docs.google.com/document/d/1Ytz-Qzwz65MvXOODmz9SDouN6MbyoOiZ_spaz61cUIQ/edit#heading=h.5q2ji2iu66ig).

I am one of ther persons who believes following changes should be made:
1) extending pod spec to support requesting CPUs and PCI devices with NUMA affinity.
   -to support more usecases such as binding contaienrs in the same pod to the same or multiple NUMA nodes, it will requere expensive changes of CPU Manager.
2) make scheduler NUMA Topology aware and Topology Policy aware
    (I think we can use [cadvisor/info/v2/Topology](https://github.com/google/cadvisor/blob/10bce1cd55ba0d3510852a4ad7dbb057139097cb/info/v2/machine.go#L69) structure rather than list of resources)

At this point, I am focusing on hugepages enhancement(container isolation of hugepages).

**Comment by DeySouvik** [comment]
@bg-chun : I totally agree with you that both the changes are required. I think the point 2 will be covered as a part of 84869, 
@cbf123 : are we taking care of point 1 also in there. 
Do suggest the best way forward to have both the issues covered. If we think we can take care of both , then i can go ahead and close this issue with the reference of 84869.

**Comment by ravisantoshgudimetla** [comment]
> make scheduler NUMA Topology aware and Topology Policy aware
(I think we can use cadvisor/info/v2/Topology structure rather than the list of resources)

Can you talk a bit more about how you want to use it in the scheduler? Because scheduler watches for node and pod objects only


While it may not guarantee, would it be `okay`, if we have an entity that evicts pods that are continuously rejected by Kubelet?

**Comment by cbf123** [comment]
Currently the scheduler is aware of the CPU and memory resources that each node has, and uses that to do a basic filtering to rule out nodes which cannot support the pod.

The goal is to be able to also look at CPU and memory (and PCI devices, and any other devices) on a per-NUMA-node basis if that's what the node specifies (via the topology manager policy currently) or if that's what the pod or container specifies (in the future, hopefully).

In an ideal world, these resources would also be "reserved" by the scheduler such that two pods racing to be scheduled wouldn't think that they could end up on the same node if there's only room for one of them.

**Comment by bg-chun** [comment]
@ravisantoshgudimetla 
```
Can you talk a bit more about how you want to use it in the scheduler? Because scheduler watches for node and pod objects only
```
=> I don't have clear picture yet, I think maybe we can make new node(v2?) obejct based on `cadvisor/info/v2/Topology` to demonstrate resources per NUMA node then we can put new algolithm(that find propoer node based on topology manager policy or topology requirement from pod spec in the future) somewhere in schduler package.

While it may not guarantee, would it be okay, if we have an entity that evicts pods that are continuously rejected by Kubelet?
=> It feels like what @cb123 is talking about in the issue. https://github.com/kubernetes/kubernetes/issues/84869 he said `pod should be sent back to the scheduler for re-scheduling to another node`.

**Comment by cbf123** [comment]
I had been thinking that kubelet could recognize that it can't fit the pod and explicitly send it back to the scheduler rather than failing it multiple times and having something else evict it.  But if that doesn't make sense within the overall design then something that evicted a failing pod would be better than nothing.

I agree though that it'd be better for the scheduler itself to be NUMA-aware and pick a node where the pod can fit while factoring in NUMA-affinity requirements.

**Comment by derekwaynecarr** [comment]
The SIG Scheduling and Node communities collaborated in a Resource Management WG where we established a roadmap and plan that resulted in device plugins, cpu manager, hugepages, and topology manager all getting introduced in the community.  At that time, we had deferred the idea of a scheduler having an intra-node topology view because we felt the kubelet was the intra-node scheduler and the policy modes the kubelet could run in would change over time.  Prior to re-evaluating the concept of exposing NUMA Topology to the cluster scheduler, we should finish the current journey we are working on.  This means the topology manager feature and alignment of cpu and huge pages should be our priority at the node level before delegating responsibility to the cluster scheduler.

**Comment by cbf123** [comment]
It seems to me that helper functions could be written such that the cluster scheduler used literally the same code as kubelet and wasn't explicitly aware of the policy modes.

Without the cluster scheduler being topology-aware the usefulness of a topology-aware kubelet is limited (at least in a stock Kubernetes system) as the cluster scheduler can easily choose a node that cannot possibly run the pod in question.

The cluster scheduler should to be topology-aware, and if there are race conditions we should also be able to reschedule to another node pods which fail to run for topology reasons.

**Comment by bg-chun** [comment]
@derekwaynecarr 
` This means the topology manager feature and alignment of cpu and huge pages should be our priority at the node level before delegating responsibility to the cluster scheduler.`
=> I totally agree with it, and it is the main reason why I am dealing with [hugepages ](https://github.com/kubernetes/kubernetes/issues/84526)and [memory manager ](https://github.com/kubernetes/enhancements/pull/1203) before cluster scheduler.

But i think we have to consider scheduler enhancement with node level enhancement together.
To be honestly, I have some doubt about that current Topology Manager design does consider future scheduler changes.

For now, I am trying to collect and organize the current limitations of Kubernetes to support things like NFV cluster or 5G Packet Processing stuff on this [document](https://docs.google.com/document/d/1XGTx6F8qgdq_zPvd87LAfhW1ObQ1McTDAoIWyokY88E/edit).

The document isn't limited to list down limitations, It also proposes some changes to address current limitations and user-facing issues and several solution to make the changes.
### Proposed Changes
- Supporting single socket alignment of memory and hugepages alongside with CPU and PCI devices.
- **Extending Pod Spec to be able to express topology requirements.**
- **Enhancing Topology Manager and related components of Kubelet to allocate resources based on given topology requirements.(it means adding a new topology management policy)**
- Making scheduler NUMA-aware.

**Comment by derekwaynecarr** [comment]
@bg-chun thank you for the document.  I like a number of the ideas proposed and it’s very limited impact on the pod spec.  A key reason we proceeded down the path we are on was a strong desire to not expose intra-node assignment in pod spec, and I think your doc keeps the API simple by taking the existing node policies under development and bringing the policy into the spec without the detail on what core, what device, what node.

**Comment by DeySouvik** [comment]
Found one more issue that even if the NIC port are attached to NUMA 1 in case of userspace CNI, the cpu allocated/pinned for the container is coming from numa 0. This will effect the performance as the network packets needs to traverse the QPI/UPI link to move from one NUMA to the other. 

Host side
[root@node3 ~]# ovs-vsctl show 
94adf6db-4a8d-41fc-a5e0-5b1ee35b9b4a
    Bridge "br-4"
        datapath_type: netdev
        Port "843a7dcf179a-net1"
            Interface "843a7dcf179a-net1"
                type: dpdkvhostuser
        Port "br-4"
            Interface "br-4"
                type: internal
        Port "843a7dcf179a-net2"
            Interface "843a7dcf179a-net2"
                type: dpdkvhostuser
        Port "phy0"
            Interface "phy0"
                type: dpdk
                **options: {dpdk-devargs="0000:82:00.1"}**
        Port "843a7dcf179a-net3"
            Interface "843a7dcf179a-net3"
                type: dpdkvhostuser
    Bridge "ovsbr0"
        datapath_type: netdev
        Port "ovsbr0"
            Interface "ovsbr0"
                type: internal
        Port "vhost-user1"
            Interface "vhost-user1"
                type: dpdkvhostuser
    ovs_version: "2.12.0"
pci 0000:82:00.1 is connected to numa 1.
But inside the container which is attached to the vhost port 843a7dcf179a-net*, we see that the cpu assigned are 
cat /sys/fs/cgroup/cpuset/cpuset.cpus
2,4,22,24
[root@vsbc1  ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               2873.400
CPU max MHz:           3100.0000
CPU min MHz:           1200.0000
BogoMIPS:              4399.90
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
**NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38**
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39

This clearly proves that we will require more logic in the scheduling and numa awareness allocation of the POD resources to minimize the effect on the performance. Mostly this will be an issue in case of NFV apps.

**Comment by cbf123** [comment]
@DeySouvik in your example given above, were you using the "restricted" or "single-numa-node" policy for the Topology Manager?

**Comment by DeySouvik** [comment]
I do have added the --cpu-manager-policy=static in the kubelet_args so the kubelet will have the cpu guarantee policy enabled but I dont have the --topology-manager-policy set to restricted or single-numa-node. I will set that and give a try.

**Comment by bg-chun** [comment]
@DeySouvik
BTW, The restricted policy doesn't guarantee resource allocation from a single NUMA node.
If you want to guarantee single numa resource isolation for a container, use single-numa policy :)

**Comment by cbf123** [comment]
@bg-chun 
If I set the single-numa policy it breaks the multus and sriov-cni pods in the kube-system namespace...they fail with a topology error.  I haven't bottomed it out, but my guess is that they're trying to access devices from multiple NUMA nodes on the host.

**Comment by DeySouvik** [comment]
Though I am yet to try this option out, but with the above comments does this not put us back to square one where the cpu and memory can come from different numa?

**Comment by cbf123** [comment]
*If* there are sufficient resources available on one NUMA node of the chosen worker node, then setting the topology manager policy to "single-numa policy" should result in the pod using CPU and memory from the same NUMA node.  You may get lucky and not have issues with multus/cni pods.

**Comment by bg-chun** [comment]
>If I set the single-numa policy it breaks the multus and sriov-cni pods in the kube-system namespace...they fail with a topology error. I haven't bottomed it out, but my guess is that they're trying to access devices from multiple NUMA nodes on the host.

@cbf123 
Hm.., It sounds a little bit weird to me.
I think there is no reason that multus and sriov-cni(do you mean a sriov-dp pod?) pod fail with topology error.

I've used a dual-socket server with one DPDK compatible NIC(on the NUMA node 0) and tested DPDK TestPMD with multus, sriov(CNI&DP), and single-numa policy.
With this configuration, I didnt face any issue.

I will try to configure my dual-socket server with DPDK compatible nic per each socket.
(I just hope there is no issue for multus & sriov-dp).

**Comment by bg-chun** [comment]
@cbf123 
I have configured dual-socket server with DPDK compatible nic on each socket and it seems multus pod and sriov-dp pod doesnt fail with topology error.

At the moment, I didnt configure PF/VF and bind PF driver yet, it means above pods are just depoloyed. I dont have time to check it now, later i will try it soon.
(As i know there wasn' any issue when i tried before)

See here:
>[vran@localhost ~]$ kubectl get pod --all-namespaces
NAMESPACE     NAME                                            READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5c45f5bd9f-f9btk        1/1     Running   0          71m
kube-system   calico-node-v954w                               1/1     Running   0          71m
kube-system   coredns-6955765f44-g8h4s                        1/1     Running   0          74m
kube-system   coredns-6955765f44-jzbld                        1/1     Running   0          74m
kube-system   etcd-localhost.localdomain                      1/1     Running   0          74m
kube-system   kube-apiserver-localhost.localdomain            1/1     Running   0          74m
kube-system   kube-controller-manager-localhost.localdomain   1/1     Running   0          74m
**kube-system   kube-multus-ds-amd64-l694g                      1/1     Running   0          22m**
kube-system   kube-proxy-hqr9r                                1/1     Running   0          74m
kube-system   kube-scheduler-localhost.localdomain            1/1     Running   0          74m
**kube-system   kube-sriov-device-plugin-amd64-q5g7p            1/1     Running   0          24m**


Here is my configuration:
[kubelet]
>[vran@localhost ~]$ cat /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --cpu-manager-policy=static --topology-manager-policy=single-numa-node --kube-reserved=cpu=2,memory=2Gi,ephemeral-storage=20Gi --system-reserved=cpu=2,memory=2Gi,ephemeral-storage=20Gi --system-reserved-cgroup=/system --enforce-node-allocatable=pods,system-reserved --feature-gates=TopologyManager=true

**Comment by HerbertDuan15** [comment]
m

**Comment by cbf123** [comment]
/reopen

Pretty sure this is still an issue...

**Comment by cdg-Charter** [comment]
has this been resolved?

**Comment by ffromani** [comment]
the kubernetes core scheduler is not numa-aware yet. There's an external plugin which provides numa-aware scheduling though: https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/noderesourcetopology

**Comment by ffromani** [comment]
/reopen

xref: https://github.com/kubernetes/kubernetes/issues/84601#issuecomment-1588223951
