### ISSUE TITLE
Pull kubectl functions out of e2e test framework utils

### ISSUE THREAD

**Issue by MorrisLaw** [kubernetes/kubernetes#84615]
**Why is this needed:**
The original PR, [#77592](https://github.com/kubernetes/kubernetes/pull/77592), was made to address issue [#77095](https://github.com/kubernetes/kubernetes/issues/77095). It ended up getting pretty large and difficult to iterate on and difficult for others to review.

I've decided to break this out into smaller PRs, in order to iterate on this task much quicker. The goal is to move all kubectl-related functions out of `test/e2e/framework/util.go`.

**Comment by alejandrox1** [comment]
/priority important-longterm
/lifecycle active
/retitle Pull kubectl functions out of e2e test framework utils

**Comment by SataQiu** [comment]
I'm willing to help! Is there a more detailed division of work? @MorrisLaw

**Comment by MorrisLaw** [comment]
Hey @SataQiu I’ve started work on this already with the original PR. But It was getting too big and I thought it’d be easier to break the PR down into smaller pieces.

I made this issue to track that work..
The first PR which adds a `TestKubeconfig` struct is up now and is important for being able to abstract away the `kubectl-related` functions.

I haven’t broke down a division of work, but, I planned on using my original PR as a reference and breaking that PR out into smaller ones.

**Comment by SataQiu** [comment]
@MorrisLaw I'd be happy to help you if you'd like, and we can do it bit by bit :)

**Comment by BenTheElder** [comment]
Is this done or still active?
It shouldn't both be marked "help wanted" and "lifecycle/active"

**Comment by oomichi** [comment]
I think this issue is important for e2e framework.
and I'd like to help this.
It is nice to remove `help wanted` label at this time.

/remove-help

**Comment by oomichi** [comment]
Oops, I forgot to assign myself.

/assign @oomichi

**Comment by oomichi** [comment]
https://github.com/kubernetes/kubernetes/pull/93213 can solve this issue.
In addition, I am not working for this issue as the above PR.
/unassign @oomichi 
/remove-lifecycle stale
