### ISSUE TITLE
error happened  when using 'kubeadm join --control-plane --certificate-key' to add a new master node if we are using external etcd

### ISSUE THREAD

**Issue by KevinTHU** [kubernetes/kubernetes#84627]
**What happened**:
when using 'kubeadm join --control-plane --certificate-key' to add a master node,  this error happened: "the Secret does not include the required certificate or key - name: external-etcd.key, path: /etc/etcd/apiserver-etcd-client.key"

**What you expected to happen**:
download the certification of k8s api, and I have my external etcd certification locally, so I can add this master node correctly with the command above.

**How to reproduce it (as minimally and precisely as possible)**:
1. On an existing master node: 
#kubeadm init phase upload-certs --upload-certs
#kubeadm token create --print-join-command
To generate the `kubeadm join` command like: `kubeadm join 192.168.0.1:8443 --token m3nj53.j7s5ldvwi6j7b3ha     --discovery-token-ca-cert-hash sha256:6ad3de252e357d9948cf8ecda590f08a346468477afb2601414ff1b39809db4c --control-plane --certificate-key b037d009bade35c3468a4c34d7795bb789d67857a2fa4b932818f4066d864830`
2. On a new master node you want to add:
to run the kubeadm join command above.

**Anything else we need to know?**:
I think it is a deploy bug for adding a new master node with external etcd. not just an error log problem, like https://github.com/kubernetes/kubernetes/pull/76636 fix. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
private cloud vm (4C-8G-100G)
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux hexin-k8s-151 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm version:
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:15:39Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Network plugin and version (if this is a network-related bug):
None about network
- Others:

**Comment by KevinTHU** [comment]
The new master node will be added correctly if we add it in 2 hours after `kubeadm init --config --upload-certs` the first master node, just with the `kubeadm join` command printed by the `kubeadm init` result. So, the problem is on the command `kubeadm init phase upload-certs --upload-certs`, the new **kubeadm-certs** generated by this command is lack of the information about external etcd.
I have see the **kubeadm-certs**  by `kubectl get secret kubeadm-certs -n kube-system -oyaml`, as expected, it has external etcd info. but after 2 hours, and the new  **kubeadm-certs** generated by `kubeadm init phase upload-certs --upload-certs` has no external etcd info.

**Comment by KevinTHU** [comment]
alright, maybe I need to  close this issue, with command `kubeadm --config kubeadm-config.yaml init phase upload-certs --upload-certs`, we will get the correct **kubeadm-certs**.

but maybe we need to add it into the `kubeadm init `result for a detailed describe about using external etcd, and the k8s website also.

**Comment by neolit123** [comment]
> #kubeadm init phase upload-certs --upload-certs

hi, if you are not passing the --config to the phase kubeadm has no way of knowing if external etcd is used. this is a standard practice already.

> alright, maybe I need to close this issue, with command kubeadm --config kubeadm-config.yaml init phase upload-certs --upload-certs, we will get the correct kubeadm-certs.

yes, i agree let's close this. using --config is viable here.
/close

> but maybe we need to add it into the kubeadm init result for a detailed describe about using external etcd, and the k8s website also.

SGTM, feel free to send a PR for kubernetes/website.
possibly a note in the lines of "make sure you pass --config to the phases that need to know about the kubeadm configuration"
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#init-phases
