### ISSUE TITLE
How to resolve that issue ? Readiness probe failed: HTTP probe failed with statuscode: 503 

### ISSUE THREAD

**Issue by Inv0k-er** [kubernetes/kubernetes#84632]
How to resolve that issue ?
"cniVersion": "0.3.1"

kube-system coredns-5644d7b6d9-47k52 0/1 Running 0 3h29m
kube-system coredns-5644d7b6d9-8vmzv 0/1 Running 0 3h29m

kubectl describe pod/coredns-5644d7b6d9-47k52 -n kube-system

Name: coredns-5644d7b6d9-47k52
Namespace: kube-system
Priority: 2000000000
Priority Class Name: system-cluster-critical
Node: pr40/178.88.161.72
Start Time: Wed, 30 Oct 2019 18:37:46 +0600
Labels: k8s-app=kube-dns
pod-template-hash=5644d7b6d9
Annotations:
Status: Running
IP: 172.17.1.2
IPs:
IP: 172.17.1.2
Controlled By: ReplicaSet/coredns-5644d7b6d9
Containers:
coredns:
Container ID: docker://1f8513460e1b11a5311e5f73d54a5cef35d489784fc36486292134a92dbe34d8
Image: k8s.gcr.io/coredns:1.6.2
Image ID: docker-pullable://k8s.gcr.io/coredns@sha256:12eb885b8685b1b13a04ecf5c23bc809c2e57917252fd7b0be9e9c00644e8ee5
Ports: 53/UDP, 53/TCP, 9153/TCP
Host Ports: 0/UDP, 0/TCP, 0/TCP
Args:
-conf
/etc/coredns/Corefile
State: Running
Started: Wed, 30 Oct 2019 18:37:47 +0600
Ready: False
Restart Count: 0
Limits:
memory: 170Mi
Requests:
cpu: 100m
memory: 70Mi
Liveness: http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
Readiness: http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
Environment:
Mounts:
/etc/coredns from config-volume (ro)
/var/run/secrets/kubernetes.io/serviceaccount from coredns-token-g2xt6 (ro)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
config-volume:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: coredns
Optional: false
coredns-token-g2xt6:
Type: Secret (a volume populated by a Secret)
SecretName: coredns-token-g2xt6
Optional: false
QoS Class: Burstable
Node-Selectors: beta.kubernetes.io/os=linux
Tolerations: CriticalAddonsOnly
node-role.kubernetes.io/master:NoSchedule
node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:
Type Reason Age From Message
Warning Unhealthy (x1231 over 3h24m) kubelet, pr40 Readiness probe failed: HTTP probe failed with statuscode: 503

for p in $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name); do kubectl logs --namespace=kube-system $p; done

2019-10-30T14:27:57.813Z [INFO] plugin/ready: Still waiting on: "kubernetes"
E1030 14:27:58.484210 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:27:58.484210 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:27:58.484210 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:27:58.484210 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:00.486393 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:00.486393 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:00.486393 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:00.486393 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:02.488336 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:02.488336 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:02.488336 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:02.488336 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:04.490256 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host^C
E1030 14:28:04.490256 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E1030 14:28:04.490256 1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host

**Comment by gaopeiliang** [comment]
1.   coreDNS Pod are trying to dial with api_server ,, 10.96.0.1 maybe api_server cluster_ip ...
2.  coreDNS failed dial api_server, so not ready , so probe failed ..
3.  that all POD network not work correct...  first check pod network , flannel or else ,, then check kube-proxy

**Comment by Inv0k-er** [comment]
I am sorry but can you help me ?
I don't know what command need to check it ?
Can you send me ?

**Comment by Inv0k-er** [comment]
> 
> 
>     1. coreDNS Pod are trying to dial with api_server ,, 10.96.0.1 maybe api_server cluster_ip ...
> 
>     2. coreDNS failed dial api_server, so not ready , so probe failed ..
> 
>     3. that all POD network not work correct...  first check pod network , flannel or else ,, then check kube-proxy

I am sorry but can you help me ?
I don't know what command need to check it ?
Can you send me ?
