### ISSUE TITLE
Secrets of type 'kubernetes.io/service-account-token' are not garbage collected

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#84642]
**What happened**:

We're running a EKS cluster for a couple of months now, and notice a serious amount of secrets being kept in the cluster (>15k!). Looking further into that we found that these were secrets of type `kubernetes.io/service-account-token`, which were likely not used anymore -- the service account for these secrets only mentioned _one_ secret in its own secret list.

**What you expected to happen**:

I expect these secrets to be automatically garbage collected.

**How to reproduce it (as minimally and precisely as possible)**:

Unclear; right now I deleted all of these using the attached script, and am now waiting to see whether these come back.

**Anything else we need to know?**:

1. Initially I assumed that this might be related to a similar high number of not-cleaned-up replicasets, due to `revisionHistoryLimit` being unset, which kubernetes (potentially an earlier version) interpreted as ~2**31. I fixed that, and removed all old replicasets, but the number of secrets was unchanged.
2. The cluster has been migrated multiple times, it initially started out as a 1.10 cluster (IIRC!), and is now running 1.14.
3. We do deploy quite a lot into that cluster, with each deployment likely getting updated once every few hours.
4. I can provide a snapshot of the replicasets and secrets, obviously I'd rather avoid that :)

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-22T06:44:59Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: AWS
- OS/Kernel/... (e.g: `cat /etc/os-release`): AWS Linux 2; unmodified AMIs suggested by AWS

Cleanup script:
```js
#!/usr/bin/env node

/* eslint-disable max-statements */

'use strict';

const path = require('path');
const process = require('process');

const Bottleneck = require('bottleneck/es5');
const k8s = require('kubernetes-bootstrap/src/kubernetes/k8s-client');

const userDir = process.env[process.platform === 'win32' ? 'USERPROFILE' : 'HOME'];
const argvParser = require('yargs')
	.string('kubeconfig').default('kubeconfig', process.env.KUBECONFIG || path.resolve(userDir, '.kube/config')).describe('kubeconfig', 'Kubectl configuration file to use for connecting to the cluster')
	.string('context').default('context', undefined).describe('context', 'Context in the kubectl configuration to use')
	.string('namespace').describe('namespace', 'The namespace to process').demandOption('namespace')
	.number('limit').default('limit', 25).describe('limit', 'Number of requests per second that can execute')
	.help()
	.strict();

async function main(argv) {
	const args = argvParser.parse(argv);
	const k8sClient = await k8s(args.kubeconfig, args.context);

	const limiter = new Bottleneck({minTime: 1000 / args.limit});

	// Find all secrets of type 'kubernetes.io/service-account-token', and
	// group them by metadata.annotations["kubernetes.io/service-account.name"]
	const v1 = k8sClient.group('v1').ns(args.namespace);
	const secretNamesByServiceAccountName = (await v1.secrets.list())
		.items
		.reduce((agg, item) => {
			if (item.type !== 'kubernetes.io/service-account-token') {
				return agg;
			}
			const serviceAccountName = item.metadata.annotations['kubernetes.io/service-account.name'];
			agg[serviceAccountName] = (agg[serviceAccountName] || []).concat(item.metadata.name);
			return agg;
		}, {});
	// Find the active secrets for that service account (secrets[].name), and remove all but the active secrets
	const promises = [];
	for (const [serviceAccountName, secretNames] of Object.entries(secretNamesByServiceAccountName)) {
		const serviceAccount = await v1.serviceaccount(serviceAccountName).get();
		console.log(`${serviceAccountName}: Active secret names: ${serviceAccount.secrets.map(secretRef => secretRef.name)}`);
		secretNames
			.filter(secretName => !serviceAccount.secrets.find(secretRef => secretRef.name === secretName))
			.forEach(secretName => {
				console.log(`${serviceAccountName}: Deleting ${secretName}`);
				promises.push(limiter.schedule(() => v1.secret(secretName).delete()));
			});
	}

	console.log(`Waiting for ${promises.length} deletions`);
	await Promise.all(promises);
}

main(process.argv);
```

**Comment by ankon** [comment]
/sig api-machinery

(Guessing)

**Comment by liggitt** [comment]
The tokens are still valid as credentials even if they are not referenced from the serviceaccount object as the active secret to automount. That means they cannot be safely garbage collected without knowledge of whether an external process is using that credential.

See https://github.com/kubernetes/kubernetes/issues/20165 for discussion on service account token rotation.

/close

**Comment by ankon** [comment]
They might be valid, and that's fine -- but that's not the really the main point of this issue. 

The point here is that k8s decided to create something, and then let it lie around silently, _seemingly forever_. My concern here is that over time the etcd will just run full, which makes the api server very unhappy, and which ultimately makes my cluster fail. One could say "scale etcd appropriately", but especially since in a world such as AWS EKS I do not even have control over that -- and AWS would know even less about which of my cluster's secrets are used or aren't used.

What is needed therefore is a way to work out whether these can be safely GCd, or need to be kept around. At least from my point of view the common situation is that no external entity is actually using any of these secrets, so I can work out whether a secret right now is not mounted anywhere I could delete it. This can happen in Kubernetes proper, or in something I would have to deploy. In the more generic case where an external entity is using the secret I agree that doing a GC inside Kubernetes would be a problem without additional information.

Focusing on the common (and my) case: Is "secret is mentioned in the serviceaccount.secrets array" a strong enough indicator for "at least one pod has this secret mounted somewhere?" Or would I have to list all pods, scan through their volumes, and then remove secrets not referenced in a volume?

**Comment by liggitt** [comment]
> The point here is that k8s decided to create something, and then let it lie around silently, seemingly forever.

Unless otherwise requested, Kubernetes one per service account, and when that service account is deleted, the secret is also deleted.

You can request another secret be created by removing the existing token from the serviceaccount's secrets list.

You can request a token be populated into an existing secret by creating the secret with the correct type and name/uid annotations.

The actor that clears the service account secrets list or creates the standalone secret is responsible for cleaning up the resulting tokens.

> Focusing on the common (and my) case: Is "secret is mentioned in the serviceaccount.secrets array" a strong enough indicator for "at least one pod has this secret mounted somewhere?" Or would I have to list all pods, scan through their volumes, and then remove secrets not referenced in a volume?

No, a pod that was already running and had a token mounted would remain running and could be using that token after the service account's secrets field was cleared.

**Comment by ankon** [comment]
Thanks!

> You can request another secret be created by removing the existing token from the serviceaccount's secrets list.

AHA! I think the problem here is could then actually be caused by our deployment procedure, I'll have to check that there.

>> Or would I have to list all pods, scan through their volumes, and then remove secrets not referenced in a volume?
>
> That is the correct way to determine if a secret is mounted by a pod.

Good, assuming that the above "deployment procedure assumption" turns out to be wrong, I guess I'll convert my script into something I can run continuously in the cluster and adapt it to that rule.

**Comment by ankon** [comment]
For closure: I can confirm now that fixing our deployment to not overwrite the service accounts (and thereby removing the reference to the existing secret) resolves this problem completely.
