### ISSUE TITLE
Pod with volume mounted w FileOrCreate created as directory instead of file.

### ISSUE THREAD

**Issue by joalmjoalm** [kubernetes/kubernetes#84663]
Volume hostpath is created as directory even if FileOrCreate is in config.

Install tool: 
RKE version v0.3.0
Kubernetes version 1.15.4

Docker version: (docker version,docker info preferred)
On kubernetes nodes: Docker version 18.09.9, build 039a7df9ba

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)
kernel 4.15.0-65-generic

Type/provider of hosts: 
RKE on Bare-Metal (Kubernetes as containers)

cluster.yml file:
se attached file. 
[cluster.yml.txt](https://github.com/kubernetes/kubernetes/files/3799701/cluster.yml.txt)

Steps to Reproduce:
I got the error when creating pods with hostpath w FileOrCreate like the attched example.
[fileorcreate-test.yaml.txt](https://github.com/kubernetes/kubernetes/files/3799705/fileorcreate-test.yaml.txt)

Results:
It creates a directory instead of file /tmp/some.conf.
Related tickets at 
https://github.com/kvaps/kube-linstor/issues/4
https://github.com/rancher/rke/issues/1742

/sig node
/area kubelet

**Comment by zouyee** [comment]
master branch:
`-rw-r--r--. 1 root root   0 11月  2 11:00 some.conf`

1.13.2 branch:
`-rw-r--r--. 1 root root        0 11月  2 10:48 some.conf`

release-1.15:
`-rw-r--r--.  1 root root   0 11月  2 11:12 some.conf`

**Comment by clarklee92** [comment]
I think I encountered this issue. Specify `mountPropagation ` is necessary while using `hostPath`:
https://kubernetes.io/docs/concepts/storage/volumes/  , `HostToContainer ` or `Bidirectional ` is valied.
```
Configuration
Before mount propagation can work properly on some deployments (CoreOS, RedHat/Centos, Ubuntu) mount share must be configured correctly in Docker as shown below.

Edit your Docker’s systemd service file. Set MountFlags as follows:

MountFlags=shared
Or, remove MountFlags=slave if present. Then restart the Docker daemon:

sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by joalmjoalm** [comment]
I set the MountFlags=shared but the some.conf is still created as a directory if its not existing.
 systemctl show docker.service | grep MountFlags
MountFlags=shared

Any advice on next step to isolate the issue? Is it related to running Kubernets as containers/rke?

**Comment by clarklee92** [comment]
> I set the MountFlags=shared but the some.conf is still created as a directory if it not exists.
> systemctl show docker.service | grep MountFlags
> MountFlags=shared
> 
> Any advice on next step to isolate the issue? Is it related to running Kubernets in containers/rke?
> 
> This might be related,
> #65825

After `MountFlags` set to `share`, you also need to add `mountPropagation` at  `Container.volumeMounts` like this:
```
 volumeMounts:
 - name: my-volume
   mountPath: /data
   mountPropagation: HostToContainer
```

**Comment by joalmjoalm** [comment]
Unfortunately didnt succeed w RKE with this config, MountFlags=shared + this pod-yaml. Still created as a dir.

**Comment by joalmjoalm** [comment]
I added "extra_binds" of /temp:/temp to the RKE cluster.yml and updated the cluster.
After that some-conf was created as file and not as a dir.
But my original purpose was to mount a drbd.conf file in /etc for a specific pod and Im not sure Im a fun of binding /etc on cluster-level. Maybe this should be addresses in the RKE github if there is any other way. The previous opened issue from hp resultated in they did a workaround on their own, see related issue but closed. Comments?
