### ISSUE TITLE
no dumplicate volumes are verified when creating a statefulset

### ISSUE THREAD

**Issue by chenxianpao** [kubernetes/kubernetes#84698]
**What happened**:  dumplicate volume are invalid when I create a deployment, k8s check it before creation, but no dumplicate volumes are verified when creating a statefulset.

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go
![image](https://user-images.githubusercontent.com/8839777/68096535-39fb0580-feec-11e9-949e-b09dec8a92db.png)
![image](https://user-images.githubusercontent.com/8839777/68096553-5f880f00-feec-11e9-8a64-748539a05219.png)
why not check as function ValidatePodTemplateSpec?

**Environment**:
- Kubernetes version (use `kubectl version`):  1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by clarklee92** [comment]
`statefulSet` use volumes by `volumeClaimTemplates`. The validation scenario you described does not exist in use.

**Comment by chenxianpao** [comment]
> `statefulSet` use volumes by `volumeClaimTemplates`. The validation scenario you described does not exist in use.

If statefulSet use volumes by **Template v1.PodTemplateSpec**, I use two same name volumes，statefulSet can be created, but logs show:

Warning  FailedCreate  7m56s (x421 over 4d17h)  statefulset-controller  create Pod app-anm4i0-0 in StatefulSet app-anm4i0 failed error: Pod "app-anm4i0-0" is invalid: **[spec.volumes[12].name: Duplicate value**: "nfs", spec.containers[0].volumeMounts[9].mountPath: Invalid value: "/rizhi2": must be unique, spec.containers[1].volumeMounts[7].name: Not found: "vol-15724208737329511", spec.containers[1].volumeMounts[15].mountPath: Invalid value: "/rizhi1": must be unique, spec.containers[1].volumeMounts[17].mountPath: Invalid value: "/rizhi2": must be unique.

I think statefulSet should not be created. It should check yaml with dumplicate volumes before creation.
