### ISSUE TITLE
EncryptionConfiguration Status

### ISSUE THREAD

**Issue by AlyRagab** [kubernetes/kubernetes#84697]
**What would you like to be added**:
is it stable in the latest kubernetes feature ?
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Why is this needed**:
It will be awesome in getting this feature status stable and production supported.

**Comment by AlyRagab** [comment]
Any update EncryptionConfiguration status ?

**Comment by AlyRagab** [comment]
@immutableT Please :)

**Comment by immutableT** [comment]
@AlyRagab What is exactly required from me here?

**Comment by AlyRagab** [comment]
It is just a query about the status of the EncryptionConfig in the latest version of kubernetes , Is it stable or still in beta version ?.

**Comment by liggitt** [comment]
The EncryptionConfiguration config format is at `apiVersion: apiserver.config.k8s.io/v1` in 1.13+

/close
