### ISSUE TITLE
list-type set and map lack CR validation

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#84724]
In 1.16 we added `x-kubernetes-list-type` fields for CRDs. Lists of type map and set have uniqueness invariants on keys (map) and whole elements (set). These invariants must be checked during create and update validation in the CR registry.

To be backported to 1.16.

**Comment by sttts** [comment]
SSA equality for merging sets and maps must match the equality used in the CR validation.

If SSA uses semantic equality for CRDs, this is probably a blocker for SSA GA until we have a normalization story implemented for CRDs (which replaces the need of semantic equality in post-decode logic).

**Comment by apelisse** [comment]
> SSA equality for merging of sets and maps must match the equality used in the CR validation.

> If SSA uses semantic equality for CRDs, this is probably a blocker for SSA GA until we have a normalization story implemented for CRDs (which replaces the need of semantic equality in post-decode logic).

SSA uses `reflect.DeepEqual` (actually, our own implementation of it) for built-in types and CRs. But it's also looking through `built-in -> unstructured` (normalization for built-in objects), which means that we're fine doing that. The biggest problem I see is that we deserialize the applied object directly into an unstructured, which means there is no normalization for that, that might be a problem.

**Comment by lavalamp** [comment]
I think comparison happens on fields that have been selected first with a field set, I'm not sure if that is neutral or helps with this problem.

It (SSA) does verify key-uniqueness.

I took pains to make it preserve list order but I think the json/yaml parser defeats this at the moment :/

**Comment by lavalamp** [comment]
Anyway, the result of SSA being overly / underly picky about differences isn't too bad: it means users get more or fewer conflicts. API designers shouldn't be using the things that will trigger the edge cases to drive behavioral differences anyway, as SSA already doesn't make it easy (or possible) to "own" the difference between e.g. unset / nil.

So, I'm not sure this is actually a blocker, the consequence isn't severe and well-written CRDs shouldn't have the problem anyway?

**Comment by apelisse** [comment]
Without even considering CRs, we have a problem because of how we decode existing objects and apply objects differently. Possibly, a field can be set to null in apply and be `omitEmpty`'d in etcd and they'll look different to us, impacting `sets` of atomic?

**Comment by apelisse** [comment]
Stefan and Jordan talked about this on slack, here's what we agree on:
1. Validation ratcheting is more risky than adding validation to existing objects to verify that the listType properties are respected
2. We would like the patch to be back-portable to 1.16,
3. We would like the validation to run even if server-side apply is disabled (mostly because we can't enable it everywhere just now, and it goes again 2. anyway)

**Comment by liggitt** [comment]
> Validation ratcheting is more risky than adding validation to existing objects to verify that the listType properties are respected

We were saying ratcheting validation was *less* risky than allowing known-bad data to continue being persisted in new CR objects.

**Comment by liggitt** [comment]
> We would like the validation to run even if server-side apply is disabled (mostly because we can't enable it everywhere just now, and it goes again 2. anyway)

The list-type semantics are not documented to only apply to server-side apply, and are useful for describing the data structure behavior of the custom resource. I agree we should enforce the semantics of the documented API regardless of SSA enablement/use.

**Comment by lavalamp** [comment]
We might be able to run it everywhere now if we don't persist the field,
have we tried?

**Comment by liggitt** [comment]
> We might be able to run it everywhere now if we don't persist the field, have we tried?

We made it fail open in failure cases. Given this is API-facing and data-impacting, I *really* want a fix we can backport to 1.16, and I don't think we should enable SSA more broadly in a backport.

**Comment by lavalamp** [comment]
Ah, this isn't about SSA, is it? I think I took the OP a little too
literally :)

I agree we should check this ~now in CRDs and converge on implementation
later.

**Comment by josiahbjorgaard** [comment]
/milestone clear

(v1.17 code freeze)

**Comment by liggitt** [comment]
/milestone v1.17
This is a bug I would consider release blocking

**Comment by dims** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/84920 still has to merge for this to close out
