### ISSUE TITLE
Multi-attach scenarios for CSI-migrated-inline-volumes throw warnings and take a while

### ISSUE THREAD

**Issue by ddebroy** [kubernetes/kubernetes#84736]
When running CSI migration tests focussing on multi-attach scearnios with GCE PD inline volumes that are read-only, the following error pops up in the logs and the second attachment takes > 6 mins:

```
W1102 20:18:11.821919       1 reconciler.go:369] Multi-Attach error for volume "testpd1" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.io^projects/UNSPECIF
IED/zones/UNSPECIFIED/disks/e2e-6b0e3ef1-be4c-407b-b26b-710455a06d99") from node "k8nodew8-group-93ff" Volume is already used by pods pod-disks-4475/pd-test-98a
b5dc7-b20a-4d52-beda-78d57003dc05 on node k8nodew8-group-3gss
I1102 20:18:11.822356       1 event.go:262] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pod-disks-4475", Name:"pd-test-28a74c43-8798-459a-a899-b28c8e822465"
, UID:"74def620-4cc4-4e80-9e8a-e973005ea455", APIVersion:"v1", ResourceVersion:"5548", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach
 error for volume "testpd1" Volume is already used by pod(s) pd-test-98ab5dc7-b20a-4d52-beda-78d57003dc05
W1102 20:23:09.919569       1 reconciler.go:232] attacherDetacher.DetachVolume started for volume "testpd1" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.i
o^projects/UNSPECIFIED/zones/UNSPECIFIED/disks/e2e-ea42229c-554d-46b0-ac1a-8dff390c5b7a") on node "k8nodew8-group-3gss" This volume is not safe to detach, but m
axWaitForUnmountDuration 6m0s expired, force detaching
I1102 20:23:10.196706       1 operation_generator.go:469] DetachVolume.Detach succeeded for volume "testpd1" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.
io^projects/UNSPECIFIED/zones/UNSPECIFIED/disks/e2e-ea42229c-554d-46b0-ac1a-8dff390c5b7a") on node "k8nodew8-group-3gss" 
```

For read-only inline volumes, the above warning/error around `isMultiAttachForbidden` is unexpected with CSI migration enabled and needs to be root-caused/resolved.

**What happened**:
CSI migration tests for read-only inline GCE PD volumes occasionally fails with the above messages in the logs when executing tests like `Pod Disks schedule pods each with a PD, delete pod and verify detach [Slow] for read-only PD`

**What you expected to happen**:
The tests and multi-attach scenarios to execute smoothly with no warnings in the logs.

**How to reproduce it (as minimally and precisely as possible)**:
Execute e2e.test with focus set to `Pod Disks` and run a few times. 

**Anything else we need to know?**:
This has been observed with CSI migration enabled and the tests exercising read-only inline volume scenarios.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16
- Cloud provider or hardware configuration: GCE
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools: kube-up.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ddebroy** [comment]
Looks like hard coding access modes to ReadWriteOnce during translation for GCE PD at https://github.com/kubernetes/kubernetes/blob/e62ed95ecd300d0dc56d5d19dcbae93e3794d1bc/staging/src/k8s.io/csi-translation-lib/plugins/gce_pd.go#L222 
is not causing isMultiAttachForbidden to return `true` leading down to https://github.com/kubernetes/kubernetes/blob/54c4428eb4e7c99c825e96d2a480ad4e79bc580f/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L275 . We need to set the access mode to ReadOnlyMany for in-tree inline volumes like in GCE PD (as well as others like EBS that support multi-attach) depending on `pdSource.ReadOnly`

**Comment by davidz627** [comment]
I can pick up this fix
/assign
