### ISSUE TITLE
Change the booleans in DebuggingConfiguration to pointer type

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#84734]
**What would you like to be added**:
Change the **external** [DebuggingConfiguration]( https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/config/v1alpha1/types.go#L61-L65
) member variables to pointer types.

**Why is this needed**:
So that we can set their default values to something different from golang's, for example enable profiling by default.

/sig api-machinery 
/cc @liggitt @sttts

**Comment by liggitt** [comment]
done in #84739
