### ISSUE TITLE
Enable NodeAuthorizer and NodeAuthenticator tests in E2E

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#84742]
The NodeAuthorizer & NodeAuthenticator tests are currently feature guarded, e.g. `[Feature:NodeAuthorizer]`. Unfortunately no test suites are currently running these tests, so we don't have any test signals.

We should be running these tests in CI. Options include:

1. Remove the `[Feature:....]` label on the test, and have the tests modify the environment to set the expected configuration.
2. Configure a test suite to start a cluster with the required configuration and run the tests.

/sig auth
/area test
/priority important-soon

**Comment by tallclair** [comment]
I started working on this here: https://github.com/kubernetes/kubernetes/pull/82551
But probably won't have time to follow up before v1.17 code freeze. If anyone is interested in taking this over, please do!
/help

**Comment by RickyRajinder** [comment]
Hi @tallclair I'd like to take this on. Can you provide some guidance on what else needs to be implemented? Reading through some of the comments and I saw that we can possibly use `setKubeletConfiguration()` to update the config. Is this what you were going for?

**Comment by tallclair** [comment]
I listed 2 options in the description. For (2), something like setKubeletConfiguration would be the desired approach. You should get buy-in from some of the folks who had concerns on my original PR before implementing that approach though.

**Comment by bartekzurawski** [comment]
@tallclair Hi, I would like to work on this issue? Is it available?

**Comment by tallclair** [comment]
Hi @bartekzurawski , thanks for the offer! I already started working on this in https://github.com/kubernetes/kubernetes/pull/82551, but didn't manage to push it forward. Let me update that to use feature tags instead, and then the remaining work is to configure test jobs to include these tests. I'd definitely appreciate help on the second part!
