### ISSUE TITLE
Pods which fail kubelet's canAdmitPod() due to "Topology Affinity Error" end up "stuck" in limbo rather than going back to "pending"

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#84757]
**What happened**:
Due to a race condition I ended up with a kubernetes pod scheduled to a node but on kubelet restart it failed kubelet's canAdmitPod() and ended up with a status of "Topology Affinity Error".  I then deleted the other pods (such that there was now room for this pod on the node) but it remained in the error state.

**What you expected to happen**:
On error the pod should go back to "pending".  Once there is a node with sufficient free resources the pod should get rescheduled to that node.

**How to reproduce it (as minimally and precisely as possible)**:
Run kubelet with the static cpu manager and "single-numa-node" topology manager on a multi-numa-node host.  Start up two pods with exclusive CPUs on that node consuming most of the CPUs on each NUMA node.  Start up a third pod on that node which asks for more than the number of CPUs left on a single NUMA node (but less than the number of free CPUs across both NUMA nodes).  The pod will get scheduled to the node but then error out and stay in an error state.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2
- Cloud provider or hardware configuration: dual-numa-node x86, 14 core per numa node.
- OS (e.g: `cat /etc/os-release`): centos 7
- Kernel (e.g. `uname -a`): Linux controller-0 3.10.0-957.21.3.rt56.935.el7.tis.2.x86_64 #1 SMP PREEMPT RT Thu Oct 24 16:34:45 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cbf123** [comment]
@kubernetes/sig-node-bugs

**Comment by cbf123** [comment]
Arguably it makes no sense for a pod to get "stuck" in a failed state on a given node just because the scheduler made a bad decision about whether or not the pod can fit on the node.

If it doesn't fit, we should revert the pod back to an "unscheduled" state and try again.

Now there's a risk that the pod really can't fit on any node, so maybe it needs some kind of backoff on the scheduler retries, but it shouldn't just give up because there might be someone who just deleted a pod and freed up enough space for it to fit now.

**Comment by ConnorDoyle** [comment]
Following up from the slack thread, there is no precedent I know of for a pod being unbound and going back through the scheduler if the Kubelet has a problem running the node. The "Kubernetes way" to handle the problem is to let a higher-level controller create a new pod to replace the failed one.

However, the problem you described is clearly not desirable. Your other issue (#84601) would let the scheduler make better decisions in the first place to avoid the problem.
