### ISSUE TITLE
Print object type as first column in `kubectl get`

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#8476]
When we originally implemented get, the first column was the type, i.e. "POD", not "NAME".  Over time others implemented "NAME" as the primary column in other printers.

One benefit of "\<TYPE\>" is that the output (if saved or pasted or viewed later) gives a clue about the type.  A downside is that the column width can be much longer - i.e. "SERVICE ACCOUNT".

We should make a decision and be consistent (change Pod, or change everything else).

**Comment by bgrant0607** [comment]
#9032 changes to NAME. At least then we'll have consistency. If we decide to use the kind instead, we'll need to change them all.

**Comment by bgrant0607** [comment]
Ok, still not consistent. get RCs still uses CONTROLLER

**Comment by bgrant0607** [comment]
I see the utility, but it doesn't seem viable without abbreviation for long kind names, like REPLICATION_CONTROLLER.

**Comment by smarterclayton** [comment]
We can expose our existing abbreviations - not having them makes the core
operations suck for users anyway.  Would users recognize "svc", "rc",
"pvc", etc?  Some of the abbreviations are harder "limitquota" and
"serviceaccount"

On Aug 7, 2015, at 8:22 PM, Brian Grant <notifications@github.com> wrote:

I see the utility, but it doesn't seem viable without abbreviation for long
kind names, like REPLICATION_CONTROLLER.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/8476#issuecomment-128866769>
.

**Comment by bgrant0607** [comment]
What do you mean by "expose"? Just in kubectl output, or api paths, or...?

LimitQuota: `lq`
ServiceAccount: `svcacct`

Some of the abbreviations are obscure, though (e.g., `po`).

**Comment by smarterclayton** [comment]
Expose via restmapper or the command factory for convenience.  They're
almost abstracted today.

"po" is pointless since "pod" works.  But HorizontalPodAutoScalar might be
a mouthful - hpodas?

On Aug 7, 2015, at 8:34 PM, Brian Grant <notifications@github.com> wrote:

What do you mean by "expose"? Just in kubectl output, or api paths, or...?

LimitQuota: lq
ServiceAccount: svcacct

Some of the abbreviations are obscure, though (e.g., po).

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/8476#issuecomment-128869783>
.

**Comment by bgrant0607** [comment]
I'm leaning towards NAME, for its conciseness and for uniformity.

**Comment by smarterclayton** [comment]
+1
