### ISSUE TITLE
Support removing ephemeral container from pod

### ISSUE THREAD

**Issue by shuiqing05** [kubernetes/kubernetes#84764]
**What would you like to be added**:
Ephemeral container can be removed from pod gracefully. 
**Why is this needed**:
In our K8s cluster, there are many deployed pods. We aim to use ephemeral containers as troubleshooting containers. Thus, for troubleshooting, many ephemeral containers are potentially created.
Once the need of an ephemeral container is gone, the container should be removed gracefully. Resource of the container should be released. The container should not be accessed any more for security. And the container also should be removed from pod.
Unless the pod which contains ephemeral container is destroyed, there are no ways to remove the ephemeral container totally.
However, this approach is really "intrusive". (For example, traffic may be impacted) We need a way to remove ephemeral container gracefully like how we creating it.

**Comment by verb** [comment]
/sig node

Thanks @shuiqing05 for opening this issue! Is your concern mainly about reclaiming the resources once the ephemeral container has exited? This is a thing that should happen automatically regardless of whether the container has been removed from the PodSpec. It shouldn't require a manual step. (To be clear, I'm not saying this is current behavior.)

Deleting the container would be required if, for example, you wanted to reclaim the resources without the container having exited.

**Comment by dguendisch** [comment]
My usecases for removing closely match @shuiqing05 ones:
- security: imagine I have a minimal regular container (e.g. with `shareProcessNamespace: true`); after deploying an allmighty ephemeral debug container I want to remove it after debugging was done so that my minimal container stays minimal again
- restarts: without removing it's pretty inconvenient to deploy an ephemeral debug container again if the previous one terminated (for whatever reason)

**Comment by tedyu** [comment]
@dguendisch @shuiqing05 
What would be the desired policy for removing ephemeral containers ?
For security purpose, should the container be denied access to the Pod after configurable duration ?

**Comment by dguendisch** [comment]
For my usecases I wouldn't need duration based policies. My main point would be to be able to manually delete/remove the eph container (after I'm done debugging the problem). Nice to have would be the option/policy of having it automatically removed after the container exited.

**Comment by duglin** [comment]
Hi - what's the status of this? I'm really interested in using ephemeral containers for some of my usecases but, like others, I'd like to be able to remove them and reclaim all resources as the pod itself might live for a long time but these e-containers would come and go quite frequently.

**Comment by verb** [comment]
@dguendisch @tedyu Rather than functionality in the kubelet to automatically remove a container based on a policy enforced by the kubelet, I prefer marking a pod as tainted when an ephemeral container has been added (#84353) and leaving it up the administrator how to handle this situation. I could imagine a controller than implements an automatic removal policy.

@duglin It hasn't been designed yet. Right now I'm focused on a debugging MVP. If anyone wants to pick this up the next step would be to gather requirements and propose an update to the KEP.

**Comment by verb** [comment]
I'm considering how to do this for 1.19

/remove-lifecycle stale

**Comment by verb** [comment]
A lot of use cases have been discussed here, so I thought it would be useful to enumerate them:

1. **reclaim resources after compeletion**: We don't actually need to remove an ephemeral container from the spec for this. Resources could be reclaimed after the container exits.
2. **restarting debug containers**: I'm not sure there's a strong argument here vs just starting a container with a new name, as `kubectl alpha debug` does.
3. **terminating the ephemeral container via the API**. Currently you have to exit the container process to kill the container.
4. **clean up the pod spec**: Frequent use of ephemeral containers will cause the spec to accumulate cruft, and recreating the pod may not be warranted.

Given these, I'm planning on proposing simple deletes without in-place restarts or other updates.

**Comment by verb** [comment]
One concern about allowing ephemeral containers to be removed is that it removes information that could have been used for policy decisions. For this reason it will need to be configurable.

**Comment by zhhray** [comment]
I want to know if anyone is working on this issue now? Is there a pr about this issue？

**Comment by verb** [comment]
@zhhray  I have a goal to land this in 1.21. It needs KEP modification. PR is kubernetes/enhancements#1690

**Comment by pacoxu** [comment]
Does the killing container process in [277-ephemeral-containers/README.md#killing-ephemeral-containers](https://github.com/verb/kubernetes-enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md#killing-ephemeral-containers) implemented?

Current behavior:
```
[root@daocloud ~]#  kubectl debug --share-processes app1-859d7f4f9c-7zscw -c abc  -it --image=busybox
If you don't see a command prompt, try pressing enter.
/ # exit
Session ended, resume using 'kubectl attach app1-859d7f4f9c-7zscw -c abc -i -t' command when the pod is running
[root@daocloud ~]#  kubectl debug --share-processes app1-859d7f4f9c-7zscw -c abc  -it --image=busybox
error: error updating ephemeral containers: Pod "app1-859d7f4f9c-7zscw" is invalid: spec.ephemeralContainers[9].name: Duplicate value: "abc"
```
/assign 
I would like to help to implement it or testing with this.

**Comment by verb** [comment]
@pacoxu Awesome, thanks! Removing ephemeral containers is approved in the KEP, but it hasn't been implemented yet. You'll need to change the update validation to allow removing the ephemeral container, taking care to continue denying any other modification. Also note the new requirement to check container statuses for name collisions.

You'll also need to update the kubelet to kill a container that's removed. That may be an involved change.

**Comment by pacoxu** [comment]
Thanks for the information. I will work on it this week and next. 

- [ ] serverside change: update validation to allow removing the ephemeral container
- [ ] validation: new requirement to check container statuses for name collisions.
- [ ] kubelet side:  kill an ephemeral container that's removed

**Comment by pacoxu** [comment]
for backward compatibility

kubectl version | apiserver version |  kubelet version | API: remove the ephemeral container |  kubectl debug with exist-name
-- | -- | --  | -- | -- 
1.22 | 1.22 | 1.22 | supported | supported
1.21 | 1.21 | 1.21 | unsupported | unsupported (failed for existing name)
any | 1.21 | any | unsupported | unsupported(failed for cannot be removed)
1.22  |  1.22 | 1.21 | supported | unsupported (failed for status not updated)
1.21 | 1.22 | 1.22 | supported | unsupported (failed for existing name)

**Comment by verb** [comment]
@liggitt added some questions about the use case to https://github.com/kubernetes/kubernetes/pull/103354#issuecomment-897688579 which I'll move to this issue for discussion to involve those who requested the feature.

> what is the benefit of allowing removal of an ephemeral container? it seems like it introduces the described edge cases of attempting to re-add the same name, and it loses the information about the content of ephemeral containers run in a pod that is still active

and

> if the desire is to be able to stop an ephemeral container, is there a way to accomplish that without masking the information about the container that ran?

I think we have more to discuss about the implementation of removing ephemeral containers, so I suggest we spin this out into a separate KEP and feature flag.

**Comment by m-yosefpor** [comment]
@shuiqing05 can you please reopen this issue?

**Comment by pacoxu** [comment]
The KEP was updated in the v1.23 release cycle https://github.com/kubernetes/enhancements/pull/2892. 

There are some discussions in https://github.com/kubernetes/kubernetes/pull/103354#issuecomment-897451068.

**Comment by tonyaw** [comment]
Can I say I can't use ephemeral container to run a periodic check for a  long-lived pods by using current release?
I need the ephemeral container to run and exit after each check.

**Comment by pacoxu** [comment]
> Can I say I can't use ephemeral container to run a periodic check for a long-lived pods by using current release?
> I need the ephemeral container to run and exit after each check.

No, you can run the periodic check.

The Pod can have many ephemeral containers with different names. This issue is about removing exited containers from pod's ephemeral container list. Once the ephemeral container was added to the Pod, it cannot be removed.

**Comment by tonyaw** [comment]
Right. My concern is if ephemeral containers run too many times after a long period, the list will be too long and make pod manifest reach 1.5MiB etcd limiation.
Will it be a problem? :-)

**Comment by liggitt** [comment]
Using ephemeral containers to run a planned periodic check indefinitely for a long-running pod will monotonically increase the length of the ephemeral containers list, and is not a good use case for this feature. You could include what you need to run the periodic check in one of the normal containers and use something like `exec` to run the check

**Comment by liggitt** [comment]
What you're describing sounds more like a health or liveness check, not one-off debugging... including what you need to run that in the normal containers for the app is required.

**Comment by tonyaw** [comment]
@liggitt Thanks for your info.
From KEP, looks like there is no plan to add the removing feature in the short term. Right? 
Also, for the use case I mentioned, I think there is no solution so far. Right? :-(

**Comment by verb** [comment]
@tonyaw That's correct, we won't be implementing this in the context of kubernetes/enhancements#277. It's possible we'd revisit this in the context of a new KEP, since it's popular, but I wouldn't expect it in the short term.

I agree that your use case sounds like a bad fit for ephemeral containers, which are best effort and shouldn't be part of normal pod operation. You could implement this as a health check that doesn't use ICMP (and so doesn't require NET_RAW) but I'd be worried about all of the pods exiting at once if the destination host became unavailable for some reason.

**Comment by unmarshall** [comment]
>The reason remove was not supported was for auditability 

If you need for audit reasons then why bloat the pod spec and status? Instead create yet another companion resource which has audit information (gets created when the first debug/attach is issued). This way you do not have to change the pod spec, also allows you to control how much audit information needs to be kept which could also be made configurable. Operators/Consumers can also switch on/off auditing for selected resources which they control etc.

**Comment by jackmtpt** [comment]
Is there any update on this? Any plans to allow deleting ephemeral containers?

**Comment by chengjoey** [comment]
#124271 
draft for removing ephemeral container from pod
