### ISSUE TITLE
RemoveImage call dose not real take effect in dockershim

### ISSUE THREAD

**Issue by zvier** [kubernetes/kubernetes#84762]
**What happened**:
When I use crictl tool remove a image, it response success. But the image still exist. And even if use image id, also the same phenomena. 

**What you expected to happen**:
Like docker rmi image, the command will take real effect. After the remove image operation, the image will not exist.

**How to reproduce it (as minimally and precisely as possible)**:
The operations are as fllows: 
1. crictl images | grep 'busybox'   // display busybox image info
2. crictl rmi busybox:latest           // display "Deleted: busybox:latest" with no error message
3. crictl images | grep 'busybox'   // still display busybox

**Anything else we need to know?**:
Walk through the related code in dockershim and found this <code>InspectImageByID </code> function in libdocker/kube_docker_client.go:

```
func (d *kubeDockerClient) InspectImageByID(imageID string) (*dockertypes.ImageInspect, error) {
	resp, err := d.inspectImageRaw(imageID)
	if err != nil {
		return nil, err
	}

	if !matchImageIDOnly(*resp, imageID) {
		return nil, ImageNotFoundError{ID: imageID}
	}
	return resp, nil
}
```
In the above function, the <code>matchImageIDOnly</code> call  always return nil whether image is name or id and log “the image reference %q was not a digest reference" 

```
// matchImageIDOnly checks that the given image specifier is a digest-only
// reference, and that it matches the given image.
func matchImageIDOnly(inspected dockertypes.ImageInspect, image string) bool {
       ......
	if inspected.ID == image {
		return true
	}

	// Otherwise, we should try actual parsing to be more correct
	ref, err := dockerref.Parse(image)
	if err != nil {
		klog.V(4).Infof("couldn't parse image reference %q: %v", image, err)
		return false
	}

	digest, isDigested := ref.(dockerref.Digested)
	if !isDigested {
		klog.V(4).Infof("the image reference %q was not a digest reference", image)
		return false
	}
      ......

```
And I also use crictl try connect to crio instead of kubernetes's dockershim, the same operation <code>crictl rmi image</code> can real remove a image.

If this is a reasonable design, why not correspondence with docker rmi ? And how to construct a digest reference image that we can use <code>crictl rmi</code> remove it.

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"20
19-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"20
19-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
And also found this problem in kubernetes v1.14

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
CentOS Linux 7
- Kernel (e.g. `uname -a`):
 x86_64 GNU/Linux
- Install tools:
[crictl](https://github.com/kubernetes-sigs/cri-tools)

- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by clarklee92** [comment]
Please post this issue to you CRI plugin commity(containerd or cri-o). Image  related  interface not placed here.

**Comment by zvier** [comment]
> Please post this issue to you CRI plugin commity(containerd or cri-o). Image related interface not placed here.

Sorry, the related code is about <code>kubernetes/pkg/kubelet/dockershim/docker_image.go</code>, I already modified my title.
