### ISSUE TITLE
Can't delete pods without forcing: pods always in terminating state

### ISSUE THREAD

**Issue by michelgokan** [kubernetes/kubernetes#84760]
**What happened**:
Can't delete pods without `--force -grace-period 0`. In other words, pods never getting deleted automatically, and always in terminating state, and I always have to manually force-delete them after deleting the deployments.

**What you expected to happen**:
I expect k8s to automatically delete pods when needed. i.e. when a deployment get deleted, or when I simply delete the pod without forcing (i.e. `kubectl delete pod pod_name`)

**How to reproduce it (as minimally and precisely as possible)**:
I installed Kubernetes 1.16.2 in Ubuntu 18.04 using kubeadm.

**Anything else we need to know?**:
 I'm using NFS. I'm not sure whether NFS is the reason for such behaviour or not.

**Environment**:
- Kubernetes version (use `kubectl version`): 

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Baremetal
- OS (e.g: `cat /etc/os-release`):

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):

> Linux km 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): multus + weavenet
- Others:

**Comment by Coderhypo** [comment]
Hi，Can you find some err info in kubelet(where the pod is) log？

**Comment by michelgokan** [comment]
@Coderhypo I just checked them, and there are several permission errors every second:

> 029ff98387db41464e851eb48d0916c5954": Error response from daemon: cannot stop container: 895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954: Cannot kill container 895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954: unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused "permission denied"
> Nov 05 10:21:30 khc2 kubelet[17581]: : unknown
> Nov 05 10:21:30 khc2 kubelet[17581]: E1105 10:21:30.458120   17581 remote_runtime.go:128] StopPodSandbox "895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: cannot stop container: 895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954: Cannot kill container 895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954: unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused "permission denied"
> Nov 05 10:21:30 khc2 kubelet[17581]: : unknown
> Nov 05 10:21:30 khc2 kubelet[17581]: E1105 10:21:30.458189   17581 kuberuntime_manager.go:878] Failed to stop sandbox {"docker" "895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954"}
> Nov 05 10:21:30 khc2 kubelet[17581]: E1105 10:21:30.458298   17581 kubelet.go:1576] error killing pod: [failed to "KillContainer" for "chronograf" with KillContainerError: "rpc error: code = Unknown desc = Error response from daemon: cannot stop container: a181bb7f40a831f4e5528bd73178abe232c20de4afab93969e3f05789b0c4766: Cannot kill container a181bb7f40a831f4e5528bd73178abe232c20de4afab93969e3f05789b0c4766: unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused \"permission denied\"\n: unknown", failed to "KillPodSandbox" for "f64760bf-d167-401c-b23e-69e5acd6ec6f" with KillPodSandboxError: "rpc error: code = Unknown desc = Error response from daemon: cannot stop container: 895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954: Cannot kill container 895a5e1d47052dc5a80cfd7b489f7029ff98387db41464e851eb48d0916c5954: unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused \"permission denied\"\n: unknown"]
> ...

**Comment by michelgokan** [comment]
I've removed the apparmor (as I'm in an isolated test environment) and this solves the issue (`sudo apt-get purge --auto-remove apparmor`). 

However, I'm sure this shouldn't be the way to go...for now this seems a peaceful solution for me!
I will let you know if the problem occurs again.
