### ISSUE TITLE
WaitForStableCluster in e2e tests waits for pods to get deleted

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#84787]
**What would you like to be added**:

[WaitForStableCluster](https://github.com/kubernetes/kubernetes/blob/b735a17163ac7c7c39d9888932c815260c3ceaba/test/e2e/framework/util.go#L2364:6) is used at the beginning of some e2e scheduler tests to wait until the cluster is in a stable state. It currently waits until all existing pods are scheduled, but it should also wait until pods from previous tests are actually deleted.

We can do this by assuming that pods should exist only in the kube-system namespace, and so WaitForStableCluster should wait until there are no pods in any other namespace.

**Why is this needed**:

https://github.com/kubernetes/kubernetes/issues/84715#issuecomment-549629799

/help
/sig testing
/sig scheduling

**Comment by damemi** [comment]
I'll take this one, can't figure out how to get ci bot to assign to me...
