### ISSUE TITLE
apiserver http healthcheck

### ISSUE THREAD

**Issue by george-angel** [kubernetes/kubernetes#84797]
**What would you like to be added**:

Apiserver endpoint serving `/healthz` over HTTP, no TLS.

**Why is this needed**:

Coming out of this issue: https://github.com/kubernetes/kubernetes/issues/43784

Running our own, self-signed PKI - we can only use TCP healthchecks for GCP LoadBalancer. It would be great to be able to point the LB healthcheck at a http port exposing the healthcheck.

/sig api-machinery

**Comment by johscheuer** [comment]
I'm not an GCP expert but the docs at least state the they don't perform any certification validation: https://cloud.google.com/load-balancing/docs/health-check-concepts#criteria-certificates so it shouldn't matter that you are using a self-signed PKI.

**Comment by george-angel** [comment]
@johscheuer it looks like a lot of that documentation has change since last I looked at it, and I don't quite have the time to re-dig into it all right now.

But we are using a "forwarding rule" - https://github.com/utilitywarehouse/tf_kube_gcp/blob/master/masters.tf#L96 since we want the load balance to be `EXTERNAL`.

Which must use "targets" - https://www.terraform.io/docs/providers/google/r/compute_forwarding_rule.html instead of "backend_service" (https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html) which would enable us to have a healthcheck as the one you have linked.

Mind you I don't see how we would utilize a HTTP `/healthz` endpoint either, so unless anyone is willing to jump in and argue my point, I will close this Issue and raise a new one when I can formulate the problem properly.

**Comment by lavalamp** [comment]
We discussed this at the SIG meeting and we're recommending that people in this situation can use some or all of these techniques:
a) use the authn/authz webhooks to ensure that their health check agent is never denied
b) make a lightweight separate process to proxy healthcheck info
c) rename or explain the purpose of the public info viewer role - consumers of a cluster do need to be aware of what their responsibilities are for not breaking the cluster.

We also think it might be a good idea to rename the default "public info viewer" role to something less likely to make users think "wow I don't want that, delete".
