### ISSUE TITLE
Improve the readiness and liveliness "Configure Probes" timeout values for High performance networking and Real time applications

### ISSUE THREAD

**Issue by SUYASHKARMARKAR** [kubernetes/kubernetes#84805]
**What would you like to be added**:
Real-time applications have stringent requirements with respect to jitter, latency, quality of service and packet loss. The current timeout values for configuring probes is in order of seconds so this will cause issues for real-time applications and high performing networking applications . As an example  with "fping" we can get granularity of milli-seconds. 

**Why is this needed**:
Can we have the configure probe timeout values in order of milli-seconds or lower? This will help in design of High Availability  for Real time applications and high performance networking applications in order of sub-seconds.

**Comment by SUYASHKARMARKAR** [comment]
@kubernetes/sig-apps-feature-requests 
@kubernetes/sig-architecture-feature-requests 
@kubernetes/sig-autoscaling-feature-requests

**Comment by gerred** [comment]
/remove-sig apps
/remove-sig architecture
/remove-sig autoscaling
/sig node
/sig api-machinery

I think this is assigned to the right SIGs now (cc @dims), @SUYASHKARMARKAR if you believe this should be prioritized by SIG Architecture please drop a message on the mailing list.

**Comment by SUYASHKARMARKAR** [comment]
can we reopen the feature request ? Thanks.
