### ISSUE TITLE
[Failing Test] gce-master-scale-correctness - sig-storage tests

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#84803]
**Which jobs are failing**:
Four sig-storage tests

**Which test(s) are failing**:
gce-master-scale-correctness

**Since when has it been failing**:
11/02

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1190599913549860872 

**Anything else we need to know**:
-

/sig scalability
/sig storage

**Comment by oxddr** [comment]
@kubernetes/sig-storage-test-failures

**Comment by wojtek-t** [comment]
@guineveresaenger @alenkacz - FYI

**Comment by msau42** [comment]
This should be addressed by https://github.com/kubernetes/kubernetes/pull/84745

**Comment by oxddr** [comment]
/close

Tests are green again.
