### ISSUE TITLE
CPU requests values are mutually exclusive on Windows. This should be respected when using containerd.

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#84804]
This affects the following tests:

`
[sig-node] Downward API should provide container's limits.cpu/memory and requests.cpu/memory as env vars [NodeConformance] [Conformance] 
[sig-node] Downward API should provide host IP as an env var [NodeConformance] [Conformance] 
[sig-node] Downward API should provide pod UID as env vars [NodeConformance] [Conformance] 
[sig-node] Downward API should provide pod name, namespace and IP address as env vars [NodeConformance] [Conformance] 
[sig-storage] Downward API volume should provide container's cpu limit [NodeConformance] [Conformance] 
[sig-storage] Downward API volume should provide container's cpu request [NodeConformance] [Conformance] 
[sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance] 
[sig-storage] Downward API volume should provide container's memory request [NodeConformance] [Conformance] 
[sig-storage] Projected downwardAPI should provide container's cpu limit [NodeConformance] [Conformance] 
[sig-storage] Projected downwardAPI should provide container's cpu request [NodeConformance] [Conformance] 
[sig-storage] Projected downwardAPI should provide container's memory limit [NodeConformance] [Conformance] 
[sig-storage] Projected downwardAPI should provide container's memory request [NodeConformance] [Conformance] 
`

Tests fail with the following error message when creating pods:

`Message:failed to create containerd task: invalid spec - Windows Process Container CPU Count: '0', Limit: '6250', and Weight: '5000' are mutually exclusive: unknown`

The issue occurs because, as the message implies, CPICount, CPULimit and Weight are mutually exclusive properties and should not be all set on a windows container. The error occurs here:

https://github.com/microsoft/hcsshim/blob/c49a720085d4252c2cedfa251683210403aef74b/internal/hcsoci/hcsdoc_wcow.go#L81

The pod spec in the CRI call: https://pastebin.ubuntu.com/p/kFcnXHSs2J/
You can see that the resources requests are the following:

`&WindowsContainerConfig{Resources:&WindowsContainerResources{CpuShares:5000,CpuCount:0,CpuMaximum:6250,MemoryLimitInBytes:67108864,}`

and all are passed all the way to the hcs call.

As a parallel, docker takes this into account and assigns weights to these fields:

https://github.com/moby/moby/blob/1bd184a4c291e4f60629e2cc279216f8f40495f3/daemon/daemon_windows.go#L87-L106

**Comment by PatrickLang** [comment]
per @jterry75 this should work in containerd/cri

https://github.com/containerd/cri/blob/9f79be1b887af3df40f1e807ad2a1aedf0b931ad/pkg/containerd/opts/spec_windows.go#L137

**Comment by jterry75** [comment]
I re-read @adelina-t's report here. Is the ask that we handle this case in CRI? I think the caller should be responsible for setting appropriate measures on the API. It looks like @adelina-t fully understood this "works" and based on the error message it does indeed pass them through its just that we do not honor a "fix-up" here but I also dont think we should at the CRI layer.

**Comment by adelina-t** [comment]
@PatrickLang This does not work in containerd/cri, as all the mutually exclusive values are passed along : https://github.com/containerd/cri/blob/9f79be1b887af3df40f1e807ad2a1aedf0b931ad/pkg/containerd/opts/spec_windows.go#L160-L171

**Comment by MikkelHegn** [comment]
I suggest the title of this issue is change to not be confused with the limitations of not having hard limits for CPU resources in Windows: https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190103-windows-node-support.md#v1container

@adelina-t - Is the work to implement the weights at the kubelet level, to allow this specification?

**Comment by wawa0210** [comment]
@adelina-t  @jterry75 @MikkelHegn  is the same problem ? 
#85380 
I followed this change and then went to test and found that windows conainer cpu limit worked normally

**Comment by adelina-t** [comment]
@wawa0210 Nope, not the same issue :) This one is specific to Containerd.

**Comment by adelina-t** [comment]
https://github.com/kubernetes/kubernetes/pull/85856

**Comment by smourapina** [comment]
Hello @PatrickLang and @adelina-t! 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March, which is about 3 weeks from now. Is this issue still intended for milestone 1.18? I see that the PR mentioned above was merged already.
Thanks in advance!
