### ISSUE TITLE
JSON Patch whitespace significant?

### ISSUE THREAD

**Issue by ansongoldade** [kubernetes/kubernetes#84817]
**What happened**:
`kubectl patch deployment the-deployment --type json -p '[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"the-image"}]'`
resulted in `The request is invalid` message from server. When turning up the logging level `-v=8` the request body content was `{"op:replace":null,"path:/spec/template/spec/containers/0/image":null,"value:the-image":null}]`

`kubectl patch deployment the-deployment --type json -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "the-image"}]'`
resulted in `deployment.extensions/the-deployment patched`. With the turned up logging level, the request body content was (it appears as the whitespace was removed) `[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"develop_179_504ffd20"}]`

**What you expected to happen**:
I would expect whitespace differences in the JSON patch content to not result in different outcomes.

**How to reproduce it (as minimally and precisely as possible)**:
Repro steps in description

**Anything else we need to know?**:
Running in Azure DevOps release pipelines.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS EKS

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux fv-az619 4.15.0-1059-azure #64-Ubuntu SMP Fri Sep 13 17:02:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cli

**Comment by liggitt** [comment]
I'm not able to reproduce:

```
$ kubectl patch deployment foo --type json -p '[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"the-image"}]'
deployment.apps/foo patched
```

What shell are you using, and did you quote the command exactly as shown in the description?

**Comment by liggitt** [comment]
when I use double-quotes around the patch, I see the behavior you describe:

```
$ kubectl patch deployment foo --type json -p "[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"the-image"}]" --v=9
...
Request Body: [{"op:replace":null,"path:/spec/template/spec/containers/0/image":null,"value:the-image":null}]
The request is invalid
```

**Comment by ansongoldade** [comment]
I was writing the contents to a file to eliminate quoting issues you brought up `kubectl patch deployment foo --type json -p $(cat patch.json) --v=8`. I was seeing the different behavior with this approach as well.

**Comment by liggitt** [comment]
Using cat within a subshell still needs to be quoted

**Comment by ansongoldade** [comment]
Based on what you are saying wouldn't it be `kubectl patch deployment foo --type json -p '$(cat patch.json)' --v=8` (single quotes)?

**Comment by liggitt** [comment]
single quotes prevent the subshell from being evaluated :-/

**Comment by ansongoldade** [comment]
So then I guess I need to put single quotes in the patch file I'm creating in order to ensure it's evaluated correctly. I'll give that a shot in order to make it resilient. Just for context, the script I'm writing takes an image tag that was generated during the build phase and then tries to update the patch content with that image tag. Substituting the content in the patch content and then having it evaluated correctly by `kubectl` seems to be trickier than what I'm used to when interacting with `kubectl`. That's why I chose the route of outputting the patch content to a file and then reading it back into the `-p` parameter. I think you've helped me understand the interplay better and I now have a way forward.

An example in some documentation of creating patch content with a variable and then passing that result to `kubectl` would be extremely helpful.
