### ISSUE TITLE
[Failing Test] gce-master-scale-correctness - sig-cli tests

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#84863]
**Which jobs are failing**:
gce-master-scale-correctness

**Which test(s) are failing**:
[sig-cli] Kubectl client kubectl get output should contain custom columns for each resource

**Since when has it been failing**:
11/6

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
Nov  6 12:28:23.583: Unexpected error:
    <*errors.StatusError | 0xc00202b040>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "nodes \"node1v6g5xn767k\" not found",
            Reason: "NotFound",
            Details: {
                Name: "node1v6g5xn767k",
                Group: "",
                Kind: "nodes",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    nodes "node1v6g5xn767k" not found
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2581
```

**Anything else we need to know**:
n/a

/sig cli
/sig scalability 
/cc @kubernetes/sig-cli-test-failures

**Comment by wojtek-t** [comment]
Doesn't seem to be scale-related - failed for me the same way in the presubmit:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84860/pull-kubernetes-e2e-gce/1192066446864158721/

**Comment by oxddr** [comment]
@wojtek-t - do we run correctness test in smaller scale (so we can detect whether failures are scale related or not)? I can't find them on neither https://k8s-testgrid.appspot.com/sig-release-master-blocking nor https://k8s-testgrid.appspot.com/sig-release-master-informing dashboards.

**Comment by wojtek-t** [comment]
This is a new test that seem to be flaky at head:
https://testgrid.k8s.io/google-gce#gce-cos-master-default

@robscott - seems that you added this in https://github.com/kubernetes/kubernetes/pull/83748
Can you please take a look?

**Comment by oxddr** [comment]
/reopen 

Let's wait for the test to pass
/assign

**Comment by liggitt** [comment]
That seems to be creating one of every object from the etcd data test in an e2e test.

The failing object looks like a node object, which is likely getting deleted by the Node controller as soon as it is created.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/85377 to skip nodes for this test

**Comment by droslean** [comment]
/reopen 

The job is not green

**Comment by liggitt** [comment]
failed test started from a commit prior to the fix merging (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1195310891873079296 started from 8548a253de80c787dbcd2b022faffc75c7c23025)

/close
