### ISSUE TITLE
CPU resource request of 1000m results in multiple CPUs to process

### ISSUE THREAD

**Issue by michael-pratt** [kubernetes/kubernetes#84876]
**What happened**:

When deploying a Java app with `resources.requests.cpu` set to `1000m`, the Java runtime reports it has more than 1 CPU available. Specifically, it reports the number of physical CPUs on the node (in my case, the node has 36 cores and the Java app thinks it has 36 processors).

If I set the value to anything else, the Java runtime reports the number of processors consistent with the setting. For example, setting to `500m` results in the Java runtime reporting 1 CPU. Setting to `2000m` results in 2 CPUs.

Note that setting _both_ CPU `request` and `limit` to `1000m` does result in expected behavior (Java runtime reports 1 CPU).

This doesn't necessarily impact Kubernetes and resource scheduling. However, lots of Java libraries depend on an accurate CPU count to initialize thread pools. For example:

* The `ForkJoinPool` uses number of processors as a default pool size
* Apache Ignite creates about half a dozen thread pools that are sized based on number of processors
* Netty creates an event pool based on number of processors

In my case, one app had close to 200 threads just for Apache ignite because each thread pool had 36 threads. This was leading to overall resource starvation in the app when it was under heavy load, which would then cause the app to become unresponsive to health checks.

**What you expected to happen**:

I would expect the number of processors reported by the Java runtime to be consistent with the CPU request setting. If setting to `2000m` results in 2 CPUs, it logically follows that setting to `1000m` _should_ result in 1 CPU instead of all CPUs on the node.

**How to reproduce it (as minimally and precisely as possible)**:

I created a simple Java test driver and deployment artifacts:

https://github.com/michael-pratt/k8s-resources-request-cpu

The java app just prints out number of processors, and you can tweak the deployment.yaml to different values to see how the output changes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.7
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): Linux 4.14.121-109.96.amzn2.x86_64
- Install tools: helm (2.13.1)
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zq-david-wang** [comment]
https://github.com/AdoptOpenJDK/openjdk-jdk10u/blob/89fdfabc1a51964b32744cc21f4523051d490468/src/hotspot/os/linux/osContainer_linux.cpp#L583-L590

openjdk would treat share=1024( request=1000m) as "no share setup"
No sure whether you are using openjdk, most likely your jvm has similar behavior.

**Comment by ejsuncy** [comment]
For anyone else that comes across this, I tried the test case linked above, but compiling with openjdk 11 and running FROM openjdk:11 and couldn't reproduce. 1000m cpu request is reported in-app as 1 CPU as expected.

**Comment by dr-shim** [comment]
@ejsuncy 
I don't think it's fixed in Openjdk 11 yet.

If you look into https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/src/hotspot/os/linux/osContainer_linux.cpp#L701-L708, which is master branch of openjdk 11, there still the code exist.
```cpp
int OSContainer::cpu_shares() {
  GET_CONTAINER_INFO(int, cpu, "/cpu.shares",
                     "CPU Shares is: %d", "%d", shares);
  // Convert 1024 to no shares setup
  if (shares == 1024) return -1;

  return shares;
}
```

I've tested with the below openjdk11 version, and the issue was reproduced.
```bash
root@df68b235095e:/# java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

**Comment by matthyx** [comment]
This [commit](https://github.com/openjdk/jdk/commit/d462a6b5c9bd3dae5257cca42ea38c19cb742e3c) has (presumably) solved this issue for cgroups2.
For cgroups1 **the issue still exists**.

**Comment by frankjkelly** [comment]
Wow - crazy bug to still exist.

**Comment by matthyx** [comment]
Well, again, it's not a bug in Kubernetes...

**Comment by frankjkelly** [comment]
@matthyx Yeah indeed - I did a cursory search in the Open JDK 11 and did not find any hits
https://github.com/AdoptOpenJDK/openjdk-jdk11u/issues?q=is%3Aissue+cpu+shares+

**Comment by nicoloboschi** [comment]
Just a note that this should be the bug on JDK: https://bugs.openjdk.org/browse/JDK-8274349
