### ISSUE TITLE
Generate docs for the e2e tests

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#84872]
**What would you like to be added**:
Publishing of the docs related to the e2e.test binary as part of the release cycle.

**Why is this needed**:
There are _lots_ of flags defined to customize test behavior but in order to view them you have to access the e2e binary directly which most people dont do (using Sonobuoy or some other tool to run the tests elsewhere; only interacting with the test image).

In addition, historically the flags weren't even usable via the conformance test image since it didn't recognize any other flags. But with v1.16+ there is a method to add arbitrary flags to the test invocation so more and more users are asking about tweaking various behaviors.

At this time, when asked, I have to point them to the code where the flags are defined but this is not the best experience.

** Proposed approach **:
Following the steps here: https://github.com/spf13/cobra#generating-documentation-for-your-command we add a new flag to the e2e.test binary `--generate-docs` which, if specified, will generate markdown/man pages (one? both?) and output them. Then this output is captured and published (where?).

The implementation is very straight forward but I am unsure about the release process and where the best place to put these docs would be: k/k? k/community? k/sig-release? cncf/conformance alongside the list of conformance tests?

**Comment by ttfreeman** [comment]
@johnSchnake I would be happy to work on this as my first issue. Please feel free to assign and I'll get started. Thanks.
