### ISSUE TITLE
Should scheduler be using types from "k8s.io/api"?

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#84879]
Even in internal data structures and algorithms, scheduler code uses types from "k8s.io/api", instead of their counterparts in "k8s.io/kubernetes/pkg/apis".

For example, https://github.com/kubernetes/kubernetes/blob/c33f217/pkg/scheduler/core/generic_scheduler.go#L119

Is this expected or is this legacy code that we should be updating?

**Comment by alculquicondor** [comment]
cc @bsalamat @ahg-g @liggitt

**Comment by yue9944882** [comment]
this is intended. the internal types under "k8s.io/kubernetes/pkg/apis" are meant for connecting/converting between those multi-version external types under "k8s.io/api" i.e. round-tripping. the internal should only be working inside the apiserver and the client components like sheduler/controller-manager shouldn't rely on it. the past-us used to allow internal usages everywhere in the codebase, but we will be soon forbidding that by pruning usage of internal clients and legacyscheme. https://github.com/kubernetes/kubernetes/issues/70657

**Comment by liggitt** [comment]
correct. the scheduler should act like a client of the API server (because it is), and should use the external APIs

**Comment by alculquicondor** [comment]
Thanks for the clarification.
