### ISSUE TITLE
RuntimeClass should validate that node selector and tolerations are not modified

### ISSUE THREAD

**Issue by fvoznika** [kubernetes/kubernetes#84884]
RuntimeClass admission plugin [mutates the pod spec](https://github.com/kubernetes/kubernetes/blob/28887de8cd1b51ba2416a2e60b0b023728c5a54e/plugin/pkg/admission/runtimeclass/admission.go#L190) to schedule the pod to the correct node. However, it's possible that another mutating plugin/webhook _mistakenly_ messed with the pod configuration and may prevent the pod from being scheduled in the right node. The RuntimeClass admission plug in should validate that the node selector and tolerations are still correct during the validation phase.

**Comment by zouyee** [comment]
This situation may be avoided by adjusting the admission plugin order.
/cc @liggitt

**Comment by fvoznika** [comment]
Yes, it could be made the last plugin, but then another plugin may need to be the last and so on. Validation is guaranteed to run after all mutations, so there is no confusion or misconfiguration possible.
