### ISSUE TITLE
pull-kubernetes-typecheck  is failing on the master

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#84887]
**Which jobs are failing**:

pull-kubernetes-typecheck 

**Which test(s) are failing**:

typecheck

**Since when has it been failing**:

2019-11-06 13:40 PST

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-typecheck

https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-typecheck

**Reason for failure**:

**Anything else we need to know**:

**Comment by Huang-Wei** [comment]
Almost all PRs are blocked.

**Comment by cblecker** [comment]
Known issue: https://groups.google.com/d/msg/kubernetes-dev/Yyka3G2ebXE/yQYROxLhEAAJ

Pending: https://github.com/kubernetes/kubernetes/pull/82809

/close
