### ISSUE TITLE
make update failed

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#84909]
**What happened**:

for master branch, make update failed:
```
make update
F1107 16:35:34.476353   51618 conversion.go:294] failed to find pkg: false
make[1]: *** [gen_conversion] Error 1
make: *** [generated_files] Error 2
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
I cannot reproduce this issue.

```
$ make update
+++ [1107 14:32:45] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [1107 14:32:54] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [1107 14:33:00] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [1107 14:33:10] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [1107 14:33:22] Building go targets for linux/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
Running in silent mode, run with SILENT=false if you want to see script logs.
Running in short-circuit mode; run with FORCE_ALL=true to force all scripts to run.
Running update-generated-protobuf
Running update-codegen
Running update-generated-runtime
...
```

Make sure your local branch is up to date and you are using go1.13.4+

**Comment by danielqsj** [comment]
right, after I totally clean up _output, it works again. thanks @liggitt 
/close
