### ISSUE TITLE
introduce FeatureGates to KubeSchedulerConfiguration

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kubernetes#84922]
**What would you like to be added**:
introduce FeatureGates to KubeSchedulerConfiguration
/assign
**Why is this needed**:
This threads the --feature-gates flag through the KubeSchedulerConfiguration object

**Comment by alculquicondor** [comment]
Is there a parent issue for this? I would like to know what are the semantics of precedence.

The [CC KEP](
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/wgs/0032-create-a-k8s-io-component-repo.md#flag-precedence-over-config-file) only talks about general precedence of flags over component config, which we don't support in kube-scheduler for most flags.

https://github.com/kubernetes/kubernetes/blob/37efa75/cmd/kube-scheduler/app/options/options.go#L162-L166

Now, the problem with feature flags is that some could be enabled in the component config, and different ones in the command line. What should we do when both are set? take component config's? take flags' or do a union?

Kubelet does a merge https://github.com/kubernetes/kubernetes/blob/37efa75/cmd/kubelet/app/server.go#L335-L340

This seems to be the stance of the WG https://github.com/kubernetes/kubernetes/issues/56171

cc @mtaufen

**Comment by neolit123** [comment]
similarly to kubelet, kubeadm already has feature gates both on the CLI and ClusterConfiguration:
IIRC, CLI feature gates are merged with ClusterConfigugration feature gates, but take precedence.

it feels the safest route is to phase out the CLI feature gates at some point.

**Comment by alculquicondor** [comment]
@zouyee could you include this in your PR?

**Comment by zouyee** [comment]
> @zouyee could you include this in your PR?

Ok

**Comment by mtaufen** [comment]
Yes, CLI gates merge piecewise and take precedence over those in a config file. Each feature gate should be treated as an independent flag/field that enables or disables a feature.

**Comment by Huang-Wei** [comment]
+1 on making `FeatureGates` a common struct in component-base.

**Comment by alculquicondor** [comment]
@zouyee can you follow up on that with the working group?

**Comment by zouyee** [comment]
@alculquicondor ok

**Comment by alculquicondor** [comment]
@zouyee last I remember is that we were going to add the validation logic in the staging folder.
Are you still on that?

**Comment by alculquicondor** [comment]
/remove-help

@pancernik is taking over as we haven't heard from the other contributor for a while.

**Comment by liggitt** [comment]
> Yes, CLI gates merge piecewise and take precedence over those in a config file. Each feature gate should be treated as an independent flag/field that enables or disables a feature.

Once again, we disagree :-)

Merging CLI and config file feature flags makes it difficult to understand and validate a configuration file, especially when feature enablement factors into validation ("field A is required if feature B is enabled, field X may not be set when feature Y is disabled", etc)

**Comment by alculquicondor** [comment]
What about having the flag take full precedence and overriding the config file configuration (instead of piecewise)? And emitting a `log.Warning` when this happens.

**Comment by liggitt** [comment]
> What about having the flag take full precedence and overriding the config file configuration (instead of piecewise)? And emitting a `log.Warning` when this happens.

The most confusing bit is having a config file that isn't honored (needing the full invocation to know whether the fields in the config file will be honored). I don't think piecemill or total override makes that much of a difference in that respect.

**Comment by alculquicondor** [comment]
Then, alternatives:

1. Go with status-quo from other components: piecewise override (and a warning)
1. Only honor config file, and an error in the case where the flag is used when a file is used. This should force providers to migrate.
1. Do 2, but for 1.20, given the amount of new features we have on v1beta1.

@mtaufen any thoughts?

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

@pancernik can you lead the discussion?

**Comment by pancernik** [comment]
@mtaufen @liggitt Any thoughts regarding the last @alculquicondor's  comment? We'd like to move this forward.

**Comment by liggitt** [comment]
> * Only honor config file, and an error in the case where the flag is used when a file is used. This should force providers to migrate.

That would be my recommendation - make the config file mutually exclusive with all flags other than the ones described here:

https://github.com/kubernetes/kubernetes/blob/d236e50be7da53affa670a575b8f7ac55f1420f5/cmd/kube-scheduler/app/options/options.go#L153-L159

**Comment by alculquicondor** [comment]
If we are going to start failing for all those flags, should we do that for v1beta2 only? ref #95446

**Comment by mtaufen** [comment]
Re: @liggitt 

If it's possible to enforce mutual-exclusion now (with scheduler I think it should be, there is only one instance of it/no concerns around instance-specific vs. shared config), then that would be the cleanest approach. 

The reason we interleaved for Kubelet was for backwards-compatibility during incremental flag migration because we hadn't decided (a) how to deal with instance-specific config and (b) which flags should be removed instead of graduating. If that's not a problem here I agree let's keep it simple.

**Comment by alculquicondor** [comment]
It's not a problem, given that users have to opt-in to the new API version.
