### ISSUE TITLE
update-bazel.sh fails

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#84938]
**What happened**:

```
!!! Error in ./hack/update-bazel.sh:29
  Error in ./hack/update-bazel.sh:29. 'go install ./github.com/bazelbuild/bazel-gazelle/cmd/gazelle' exited with status 1
```

**What you expected to happen**:

Command runs and bazel dependencies are updated.

**How to reproduce it (as minimally and precisely as possible)**:

Execute the command with go 1.13.4, on master

**Anything else we need to know?**:

I'm not sure if this only affecting me. However, this was working yesterday, before #82809. I installed go from official source and started with a clean GOPATH.
Running `go install ./github.com/bazelbuild/bazel-gazelle/cmd/gazelle` directly works, so the issue must be somewhere in `hack/lib/init.sh`

**Comment by alculquicondor** [comment]
/sig release

cc @liggitt

**Comment by liggitt** [comment]
I cannot reproduce. What do you get when you do the following:

```
$ go version
go version go1.13.4 darwin/amd64
$ make clean
+++ [1107 14:12:06] Verifying Prerequisites....
$ hack/update-bazel.sh 
~/go/src/k8s.io/kubernetes/vendor ~/go/src/k8s.io/kubernetes
~/go/src/k8s.io/kubernetes
```

**Comment by alculquicondor** [comment]
```
~/k8s.io/kubernetes ➤ go version
go version go1.13.4 linux/amd64
~/k8s.io/kubernetes ➤ make clean
+++ [1107 15:05:14] Verifying Prerequisites....
+++ [1107 15:05:15] Removing _output directory
Removing _tmp ..
Removing test/e2e/generated/bindata.go ..
```

And then the same failure when running `./hack/update-bazel.sh:29`

**Comment by liggitt** [comment]
what does `go env` show for you?

**Comment by alculquicondor** [comment]
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/.gvm/pkgsets/go1.13.4/k8s:/home/user/.gvm/pkgsets/go1.13.4/global"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/user/.gvm/gos/go1.13.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.gvm/gos/go1.13.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/k8s.io/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build360742005=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by alculquicondor** [comment]
FWIIW, `update-codege.sh` just works, which uses `make` and `kube::util::find-binary`. Is it worth moving update-bazel to make?

**Comment by liggitt** [comment]
> Is it worth moving update-bazel to make?

no, the existing make stuff actually has to be rewritten to work with go modules... we don't want to move more stuff to it

**Comment by liggitt** [comment]
my `go env` looks very similar to yours, and I still can't reproduce this :-/

**Comment by alculquicondor** [comment]
Maybe it's a bug in go for linux? I'll ask folks if they can reproduce.

**Comment by liggitt** [comment]
does the `go install` that exits with code 1 give any more info?

**Comment by alculquicondor** [comment]
Yes, basically that it's not resolving vendors and it only looks into the GOPATH:

```
github.com/bazelbuild/bazel-gazelle/cmd/gazelle/diff.go:25:2: cannot find package "github.com/bazelbuild/bazel-gazelle/config" in any of:
        /home/user/.gvm/gos/go1.13.4/src/github.com/bazelbuild/bazel-gazelle/config (from $GOROOT)
        /home/user/.gvm/pkgsets/go1.13.4/k8s/src/github.com/bazelbuild/bazel-gazelle/config (from $GOPATH)
```

**Comment by alculquicondor** [comment]
This is the diff between my normal `go env` and one run from inside `update-bazel.sh` right before the failure:

```diff
1c1
< GO111MODULE="on"
---
> GO111MODULE="off"
3c3
< GOBIN=""
---
> GOBIN="/home/user/k8s.io/kubernetes/_output/local/bin"
26c26
< GOMOD="/home/user/k8s.io/kubernetes/go.mod"
---
> GOMOD=""
33c33,35
< GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build089006300=/tmp/go-build -gno-record-gcc-switches"
---
> GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0
> -fdebug-prefix-map=/tmp/go-build552565387=/tmp/go-build
> -gno-record-gcc-switches"

```

**Comment by liggitt** [comment]
> Maybe it's a bug in go for linux?

seems unlikely. CI runs on linux and runs update-bazel.sh as part of every presubmit

**Comment by liggitt** [comment]
The GO111MODULE and GOBIN settings are intentionally set in the script to get consistent results regardless of user settings. We still have build tooling that requires $GOPATH

**Comment by alculquicondor** [comment]
If I do `export GO111MODULE="off"` manually and then run: `go install ./github.com/bazelbuild/bazel-gazelle/cmd/gazelle`, then I get the same error related to skipping the vendor.

**Comment by alculquicondor** [comment]
Looking at golang/go#29670, it seems that the common factor with my case is that my clone of k8s is not in the GOPATH. This is something I recently changed when upgrading to 1.13, so that I can switch go versions more easily in the future.

According to https://github.com/kubernetes/kubernetes/blob/8618c093692f753c0fad1a4ab00912e9f218872a/hack/lib/init.sh#L25-L29
scripts can opt-in if they don't rely on `GOPATH`. Can I set that?

Otherwise, I can go back to my old setup.

**Comment by liggitt** [comment]
> scripts can opt-in if they don't rely on `GOPATH`. Can I set that?

not yet, too many of our build tools still depend on $GOPATH

**Comment by alculquicondor** [comment]
I'm referring just to `update-bazel.sh`

**Comment by liggitt** [comment]
you're not going to have a good time outside of $GOPATH, generally, until we can flip on module support for all build scripts

**Comment by alculquicondor** [comment]
Well, going back to my old setup works. Thanks for all the help.

/close
