### ISSUE TITLE
Improve performance of EvenPodSpread (priority and predicate)

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#84936]
In the light of a new performance test that compares EvenPodSpread with SelectorSpread (#84606), it seems that EvenPodSpread can be faster.

Let's investigate if we can achieve parity by carefully building the data structures.

/sig scheduling

**Comment by gongguan** [comment]
`buildPodTopologySpreadMap` is expensive and will influence the result. Could it be initialized once outside the loop?
https://github.com/kubernetes/kubernetes/blob/9920b733ba56f908d48dc7d0a30bc90d28d015a4/pkg/scheduler/algorithm/priorities/spreading_perf_test.go#L63

**Comment by alculquicondor** [comment]
That goes against the purpose of the test: an end-to-end comparison.
