### ISSUE TITLE
Auto-generate user manuals for all kube binaries, not just kubectl

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#8493]
When reading user manual for kubelet. I found it contains very few options than kubelet provides, and also some errors. For example, '--etcd_servers' is no longer supported. 

Same problem for manuals of other kube binaries except kubectl.

I'm trying to fix this and re-generate the man files. I noticed there're some options used for testing. Shall I keep them in the md files or remove them?

**Comment by erictune** [comment]
fine to not document testing options.

**Comment by hurf** [comment]
When I was amending the doc, I found in some places the connector in the flag is underscode and in other places is dash. eg. `--api-servers` and `--api_servers` are all accepted by kubelet. Shall I note it in the doc?

**Comment by lavalamp** [comment]
I believe @mikedanese removed the testing flags from our binaries.

I updated the title of this issue; this should be automated.

**Comment by mikedanese** [comment]
Fixed by #13018, cc @erictune

**Comment by lavalamp** [comment]
Assigning to @eparis, since he has a PR out to fix it.

**Comment by eparis** [comment]
and I think my PR got unblocked since we fixed openstack.  I'll try to resurrect it tomorrow.

**Comment by bgrant0607** [comment]
@mikedanese Is there anything left to do here?
