### ISSUE TITLE
Pods remaining in NotReady state

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#84931]
**What happened**:
Pods remaining in running but not ready state after node become unready for few seconds.

**What you expected to happen**:
Pods should become ready when node is ready.

**How to reproduce it (as minimally and precisely as possible)**:
Created large deployment. Make node unready for few seconds. Pods will remain not ready.
However is requires node lifecycle controler to be in eviction pass, so my guess it will not be reproducible in 100% of cases. 

**Anything else we need to know?**:
I achieve this state lock with kubemark run. There is chance that vanilla k8s is unaffected.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.18
- Cloud provider or hardware configuration:
gce - kubemark
- OS (e.g: `cat /etc/os-release`):
linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by krzysied** [comment]
My guess of what happened is:
1. Few nodes become not ready.
2. Node lifecycle controller store node statuses
3. Nodes become ready again
4. Eviction pass (based on stored status) marked pods not ready even though nodes were ready at that time

**Comment by krzysied** [comment]
kube-controller-manager log:
```
I1107 13:28:27.310469       1 controller_utils.go:169] Recording status change NodeNotReady event message for node hollow-node-pz68p
I1107 13:28:27.310607       1 event.go:281] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"hollow-node-pz68p", UID:"4296a241-d0f4-47e5-8a2c-79c3040130fe", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node hollow-node-pz68p status is now: NodeNotReady
E1107 13:28:27.387889       1 node_lifecycle_controller.go:171] error checking if node hollow-node-pz68p exists: error splitting providerID
I1107 13:28:31.234461       1 controller_utils.go:116] Update ready status of pods on node [hollow-node-pz68p]
```

**Comment by krzysied** [comment]
There is a possibility that node lifecycle controller didn't spot node updates.
I'm bumping up log level for this case: https://github.com/kubernetes/kubernetes/pull/84933

**Comment by krzysied** [comment]
Apiserver logs (ragrding node status):
```
I1107 13:28:23.766320       1 httplog.go:90] PUT /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/hollow-node-pz68p?timeout=10s: (2.898907ms) 200 [kubemark/v1.18.0 (linux/amd64) kubernetes/de158c0 35.237.0.154:32966]
I1107 13:28:27.310188       1 httplog.go:90] PUT /api/v1/nodes/hollow-node-pz68p/status: (2.453214ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/de158c0/system:serviceaccount:kube-system:node-controller [::1]:37018]
I1107 13:28:27.364569       1 httplog.go:90] PATCH /api/v1/nodes/hollow-node-pz68p: (52.809816ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/de158c0/system:serviceaccount:kube-system:node-controller [::1]:37018]
I1107 13:28:30.110484       1 httplog.go:90] PATCH /api/v1/nodes/hollow-node-pz68p/status?timeout=10s: (31.375022ms) 200 [kubemark/v1.18.0 (linux/amd64) kubernetes/de158c0 35.237.0.154:32966]
I1107 13:28:30.172280       1 httplog.go:90] PATCH /api/v1/nodes/hollow-node-pz68p: (52.819529ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/de158c0/system:serviceaccount:kube-system:node-controller [::1]:37018]
I1107 13:28:33.773756       1 httplog.go:90] PUT /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/hollow-node-pz68p?timeout=10s: (1.927627ms) 200 [kubemark/v1.18.0 (linux/amd64) kubernetes/de158c0 35.237.0.154:32966]
I1107 13:28:43.791654       1 httplog.go:90] PUT /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/hollow-node-pz68p?timeout=10s: (11.188822ms) 200 [kubemark/v1.18.0 (linux/amd64) kubernetes/de158c0 35.237.0.154:32966]
```

**Comment by krzysied** [comment]
Can someone give a hint what sets the pod ready status to true, when node is ready again?

**Comment by renjian52** [comment]
I also find this bug and It is introduced by  https://github.com/kubernetes/kubernetes/pull/77661. when I   rollback this PR, This bug is fixed

**Comment by tedyu** [comment]
@renjian52 
If you have a chance, can you see if the following fixes the issue you faced (without reverting #77661) ?
```
diff --git a/pkg/kubelet/kubelet_getters.go b/pkg/kubelet/kubelet_getters.go
index fb5c85dc06..e61687b1ac 100644
--- a/pkg/kubelet/kubelet_getters.go
+++ b/pkg/kubelet/kubelet_getters.go
@@ -31,6 +31,7 @@ import (
        "k8s.io/kubernetes/pkg/kubelet/cm"
        "k8s.io/kubernetes/pkg/kubelet/config"
        kubecontainer "k8s.io/kubernetes/pkg/kubelet/container"
+       kubelettypes "k8s.io/kubernetes/pkg/kubelet/types"
        "k8s.io/kubernetes/pkg/util/mount"
        utilnode "k8s.io/kubernetes/pkg/util/node"
        utilpath "k8s.io/utils/path"
@@ -167,8 +168,10 @@ func (kl *Kubelet) GetPods() []*v1.Pod {
        // a kubelet running without apiserver requires an additional
        // update of the static pod status. See #57106
        for _, p := range pods {
-               if status, ok := kl.statusManager.GetPodStatus(p.UID); ok {
-                       p.Status = status
+               if kubelettypes.IsStaticPod(p) {
+                       if status, ok := kl.statusManager.GetPodStatus(p.UID); ok {
+                               p.Status = status
+                       }
                }
        }
        return pods
```

**Comment by krzysied** [comment]
> If you have a chance, can you see if the following fixes the issue you faced (without reverting #77661) ?

I haven't find a way to reproduce this issue every time, so it is hard for me to say if it fixes the issue.

Can you say more about what issue this patch addresses? Is there a problem with statusManager having wrong/old pod status?

**Comment by krzysied** [comment]
I've re-run the test. There was also a problem with hollow-nodes. This time test didn't have problem with pods. k8s build included patch posted above.
@tedyu It looks like your patch helps. I still would like to hear some backstory of what happens there.

**Comment by tedyu** [comment]
My patch refines the code to achieve what #77661 intended to do.

Can you say more about problem with hollow-node ?
Please post log snippet if you have it.

Thanks

**Comment by renjian52** [comment]
hi, @tedyu . I have already test your fix in kubelet_getters.go and it can solve this bug. Still, I have a suggestion. Could you use UpdatePod() function in podManager instead of directly changing pod status in podManager by p.Status=status? If some other codes also use this direct way to modify pod infos in podManager, it will be very hard to trace pod infos are modified by which code , still there is no any log show it has been changed.

**Comment by wojtek-t** [comment]
@mfpierre @Random-Liu @dashpole @yujuhong - FYI

**Comment by wojtek-t** [comment]
@kubernetes/sig-node-bugs

**Comment by tedyu** [comment]
@renjian52 
I have added log for status update over #84951

w.r.t. using UpdatePod() function in podManager, the review / test may take more time. I will think about it meanwhile.

**Comment by jmcmeek** [comment]
Is this issue the same problem?  Sure looks like it: https://github.com/kubernetes/kubernetes/issues/82346

I've been following that issue in hopes of a fix as we see this happen a few times a day (several large clusters).  Very happy to see progress.

**Comment by tedyu** [comment]
@renjian52 
Can you attach kubelet log (without the patch) somewhere and share the URL ?

Thanks

**Comment by databus23** [comment]
We are also hit by this on a regular basis with kublets v1.15.2

The following issues are reporting the same bug I think:
#85389
#82405

**Comment by kayrus** [comment]
@databus23 this as well https://github.com/kubernetes/kubernetes/issues/82346
/cc @Joseph-Irving

**Comment by databus23** [comment]
@kubernetes/sig-node-bugs @wojtek-t Maybe add a bug label? I believe there are at least 4 independent bug reports about this rather serious inconsistency that requires a kubelet restart to fix.

**Comment by databus23** [comment]
Ah, nvm. It is already attached. Sorry for the noise

**Comment by jmcmeek** [comment]
Is https://github.com/kubernetes/kubernetes/pull/83455 a different fix for the same underlying problem?

I wouldn't normally ask, but we're trying to understand if there are two different problem and fixes we need, or competing solutions for the same problem.
