### ISSUE TITLE
[kubelet] help to describe the schema for config options

### ISSUE THREAD

**Issue by drnic** [kubernetes/kubernetes#84949]
**What would you like to be added**:

Currently `kubelet -h` includes 150 flags, of which 80+ flags that are "DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag."

But it does not indicate what the YAML/JSON path is for that same config value in the KubeletConfiguration file.

The URL that it provides for more information https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ also does not provide a mapping of flags to paths within the config file.

Nor does the formal type declaration provide a mapping https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go

I would like to start updating the 80+ deprecated-to-config-file flags with their mapping, so that ppl who run `kubelet -h` can more easily migrate from flags to config files.

**Why is this needed**:

We are telling ppl to stop using flags and migrate to config files, but we don't make it as easy as it could be. I'd like to document this for users within the `kubelet -h` help.

**Proposed text**:

Before I submit an initial PR for some flags to kick things off, I'll propose the new text for agreement:

Currently a deprecated-to-config-file flag looks like:

```
$ kubelet -h
 --pod-manifest-path string    Path to the directory containing static pod files to run, or the path to a single static pod file. Files starting with dots will be ignored. (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
```

I propose we change this to:

```
$ kubelet -h
 --pod-manifest-path string    Path to the directory containing static pod files to run, or the path to a single static pod file. Files starting with dots will be ignored. (Set via .staticPodPath in --config file.) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
```

The "(DEPRECATED: ...)" message is automatically suffixed to the 80 flags and is not easily modified. Instead the suggested text above could be implemented by adding "(Set via .X.Y.Z ... in --config file.)" to each flag's own description:

```go
fs.StringVar(&c.StaticPodPath, "pod-manifest-path", c.StaticPodPath, "Path to the directory containing static pod files to run, or the path to a single static pod file. Files starting with dots will be ignored. (Set via .staticPodPath in --config file.)")
```

/sig cli

**Comment by liggitt** [comment]
There can be multiple versions of the config file (current version is v1beta1, v1 can restructure options if required). I think it would make more sense to have example config files that output commented versions of every possible field, along with their API doc, and the CLI flag they correspond to in a comment, than to try to put the config file structure in the flag help.
