### ISSUE TITLE
Minions fail to start docker service

### ISSUE THREAD

**Issue by aranw** [kubernetes/kubernetes#8496]
I tried to follow the AWS Getting Started Guide and when ```kube-up.sh``` got stuck on the "Waiting for cluster initialization." for a long time I decided to dig deeper into what was going on. I've eventually made my way onto the master and minions to find that saltstack reports failures for docker service not starting. 

When I strace the command also look at the upstart logs I find the following two errors.

The following comes from the command ```strace sudo service docker start```
```
write(2, "sudo: effective uid is not 0, is"..., 140sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

This error message comes from ```/var/log/upstart/docker.log```
```
Waiting for /var/run/docker.sock
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] Graphdriver aufs selected. Your graphdriver directory /var/lib/docker already contains data managed by other graphdrivers: devicemapper
INFO[0000] +job init_networkdriver()
no such network interface
INFO[0000] -job init_networkdriver() = ERR (1)
FATA[0000] Shutting down daemon due to errors: no such network interface
```

Does anyone have ideas what is going on here and how I might go about fixing this?

**Comment by dchen1107** [comment]
I suspect this is caused by #7984, and @justinsb was cc-ed.

**Comment by aranw** [comment]
Any ideas on a fix for this?

**Comment by aranw** [comment]
Any updates on getting a fix to this?

**Comment by justinsb** [comment]
Haven't reproduced this yet, but hopefully tomorrow / this weekend.  Hopefully if I apply the changes in #7984...

**Comment by justinsb** [comment]
Hi @aranw.  Is this still happening for you?  If so, might you have an old IAM policy configured... can you please see the discussion (towards the end of) #11297 , and the related bug #11373 .

**Comment by aranw** [comment]
Hi @justinsb I haven't given Kubernetes another go since posting this issue, not sure if I'll get chance any time soon

**Comment by justinsb** [comment]
Thanks for letting us know!  You may want to try again once we hit 1.0 - soon now :-)

**Comment by benwilson512** [comment]
For what it's worth, I've run into this issue using kubernetes 1.0.3 when trying to increase the cluster size. If I go to the auto scaling group after the cluster is already up and increase the number of instances, any new instances created exhibit this problem. Is there a documented way to increase cluster size I'm  missing?

**Comment by dchen1107** [comment]
@benwilson512 what is your cloud provider? What is the OS dist of your minion?

**Comment by benwilson512** [comment]
AWS, ubuntu vivid. All default except region change to us-east-1 following along with the official docs for aws.
