### ISSUE TITLE
Why are there so many versions of k8s?

### ISSUE THREAD

**Issue by kiddingl** [kubernetes/kubernetes#84974]
I am a new learner, I am intered in k8s. but I am confused that k8s have too many versions(1.1*，1.2，1.3...), I don't konw how to learn it,.
Have anyone give me some advice?

**Comment by liggitt** [comment]
Releases are made quarterly. See https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions for details. Using the latest stable release is recommended. 

/close
