### ISSUE TITLE
Should DeleteOptions be also parsed from url Params?

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#84976]
Currently, `DeleteOptions` can be parsed in two ways:
- from request body:
https://github.com/kubernetes/kubernetes/blob/91bddd13485082892be8e8e471e358be317c4e9b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L84
 [that's what all the client libraries are setting]
- alternatively from url params:
https://github.com/kubernetes/kubernetes/blob/91bddd13485082892be8e8e471e358be317c4e9b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L107

Is the second option really want we want to support?
@smarterclayton @deads2k @kubernetes/sig-api-machinery-bugs 

We need to add that the second option is actually exercised by one of the conformance tests:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/pods.go#L123

Assuming we want to support it, we should create a dedicated conversion method, because currently it's not really possible to set things like `Preconditions` via the url params:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L474

**Comment by liggitt** [comment]
> Is the second option really want we want to support?

Passing a body in delete requests is not uniformly supported by http libraries, so I would not expect us to drop support for options in the URL

> Assuming we want to support it, we should create a dedicated conversion method, because currently it's not really possible to set things like Preconditions via the url params

Agree. xref https://github.com/kubernetes/kubernetes/issues/21476

**Comment by wojtek-t** [comment]
Thanks Jordan.

Adding "help-wanted" label, so to quickly summarize, we need to create a manual conversion function here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/conversion.go
We need to double check how much we can auto-convert, I think the only one is "[]string -> Preconditions" and auto-generate the url.Values->DeleteOptions (there are examples of that there)

**Comment by yue9944882** [comment]
> I think the only one is "[]string -> Preconditions" and auto-generate the url.Values->DeleteOptions (there are examples of that there)

this should also be properly reflected in the openapi v2 spec. currently there's no such query param "precondition" published in all delete apis. (ref https://github.com/kubernetes/kubernetes/issues/34856)

**Comment by gongguan** [comment]
/remove-kind help
Should this issue be closed?

**Comment by wojtek-t** [comment]
Yes - thank you!
