### ISSUE TITLE
[Failing test] Conformance-GCE-master (ci-kubernetes-gce-conformance-latest)

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#84980]
**Which jobs are failing**:
Conformance-GCE-master

**Which test(s) are failing**:
```
[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]Changes

[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]Changes
```

**Since when has it been failing**:
11-07 14:41 PST probably after this PR got merged https://github.com/kubernetes/kubernetes/commit/62f66ea2f

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master

**Reason for failure**:
```
I1108 08:03:43.432] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:34[0m
I1108 08:03:43.433]   [91m[1mvalidates that NodeSelector is respected if not matching  [Conformance] [It][0m
I1108 08:03:43.433]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:680[0m
I1108 08:03:43.433] 
I1108 08:03:43.433]   [91mNov  8 08:03:42.506: Timed out after 10m0s waiting for stable cluster.[0m
I1108 08:03:43.434] 
I1108 08:03:43.434]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:55
```

**Anything else we need to know**:
/cc @droslean  @hasheddan @alejandrox1

/sig scheduling
/milestone v1.17
/priority critical-urgent

**Comment by ahg-g** [comment]
it is actually after https://github.com/kubernetes/kubernetes/pull/84806, which was trying to fix 

```
[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]Changes
```
WaitForStableCluster is timing out, sadly there are not enough logs from the test to understand why, but likely because there are pods in a namespace other than kube-system from previous tests that never get deleted.

**Comment by alenkacz** [comment]
@ahg-g oh I see... so you think it's a flake? Or we need one more fix to the WaitForStableCluster?

**Comment by ahg-g** [comment]
We need to fix WaitForStableCluster again. 

/cc @damemi

**Comment by alenkacz** [comment]
Thanks @ahg-g for such a quick turnover!
