### ISSUE TITLE
Defaulting seems to be broken for autoscaling/v2beta2 api group

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#84990]
This function is defined and not used anywhere:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v2beta2/defaults.go#L30

The reason seem to be the missing tag here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v2beta2/doc.go#L18

```
// +k8s:defaulter-gen-input=../../../../vendor/k8s.io/api/autoscaling/v2beta2
```

That said - it seems to be causing some test failures.

Please take a look and fix.

@kubernetes/sig-autoscaling-bugs 
@josephburnett

**Comment by gongguan** [comment]
It has been fixed, see
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v2beta2/doc.go#L20

**Comment by wojtek-t** [comment]
Yeah - seems to be fixed.
