### ISSUE TITLE
cannot find replacement package to k8s.io/kubernetes@1.12.6/...

### ISSUE THREAD

**Issue by carnott-snap** [kubernetes/kubernetes#85022]
**What happened**:
I would like to use the `k8s.io/kubernetes/pkg/cloudprovider/providers/aws` package version that is compatible with the other `kubernetes-1.12.6` libraries that I am importing. I am aware that we should not import `k8s.io/kubernetes` directly, per kubernetes/kubernetes#81878. I looked in [kubernetes/cloud-providers-aws](https://github.com/kubernetes/cloud-provider-aws), however I do not see any `kubernetes-1.12.6` tag and the code was removed at kubernetes/cloud-provider-aws@b377713a2f1de9d744a6f706b77b9d16f72012ed.

**What you expected to happen**:
There should be an importable location to use this logic.

**Anything else we need to know?**:
This is being done within the context of the [eksctl](https://github.com/weaveworks/eksctl) Go module.

**Comment by liggitt** [comment]
https://github.com/kubernetes/legacy-cloud-providers/tree/master/aws is the current home of that code (from 1.15+).

/close
