### ISSUE TITLE
Refactor references to object by Name to LocalReference

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#8503]
PR #7974 adds `LocalReference`, a subset of `ObjectReference`, which has been agreed to as the long-term way to refer to objects in the same namespace as another object.  This issue is to go through and refactor references to objects by name to this new type:
- Secret name
- Host name

@bgrant0607 @smarterclayton @derekwaynecarr

**Comment by bgrant0607** [comment]
We're not going to make API-visible changes for cleanups at this point
