### ISSUE TITLE
Support for NodePort in apiserver's enable-aggregator-routing

### ISSUE THREAD

**Issue by rnsv** [kubernetes/kubernetes#85039]
**What would you like to be added**:
I would like apiserver support NodePort routing when enable-aggregator-routing is enabled

**Why is this needed**:
I have my apiserver running as a systemd service(kube-proxy is not running on the node) .  To support APIServices like metrics-server, I have enabled enable-aggregator-routing flag in apiserver config.  As this resolves to EndPoint IP:Port, I have to run the metrics server or similar services with hostNetwork set to true. This poses a challenge as I have to manage host ports when multiple APIServices are deployed.
  
It would be useful, if there is an option in aggregator-routing to support NodePort with the target endpoint translating to Host:NodePort

**Comment by rnsv** [comment]
@kubernetes/sig-api-machinery

**Comment by rnsv** [comment]
@caesarxuchao I made the following changes in staging/src/k8s.io/apiserver/pkg/util/proxyproxy.go to test it out locally and it works fine.
```
	epa := ss.Addresses[rand.Intn(len(ss.Addresses))]
	var ip string
	var port int
	if svc.Spec.Type == v1.ServiceTypeClusterIP {
		ip = epa.IP
		port = int(ss.Ports[i].Port)
	} else { // NodePort or LoadBalancer
                ip = epa.NodeName
		port = int(svcPort.NodePort)
	}
```
Looking for suggestions.  (Reference to original file below)
https://github.com/kubernetes/kubernetes/blob/bb55aa7c54c327fc0d71671e978e7626ce366497/staging/src/k8s.io/apiserver/pkg/util/proxy/proxy.go#L78-L85

**Comment by liggitt** [comment]
NodeName may happen to be an IP or routable address, but definitely isn't required to be, fyi

**Comment by rnsv** [comment]
There are couple of options that I could think of to overcome the challenge.
1. Introduce another option in api-server along side --enable-aggregator-routing that tells whether to use PodIP or NodePort
2. Deprecate --enable-aggregator-routing and provide a new option that explicitly tells what option to use for aggregator routing.  For example --aggregator-routing-type = ClusterIP | EndpointIP | NodePort.  ClusterIP can continue to be the default(as is the case now) and depending on the other two options we could decide whether to use EndpointIP or NodePort.  This would keep the existing implementation as is and use NodePort only when that option is selected.
