### ISSUE TITLE
TestPreemptionRaces is Flaky

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85031]
**Which jobs are failing**:
pull-kubernetes-integration

**Which test(s) are failing**:
TestPreemptionRaces

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/1193004486889574400/

/sig scheduling
/help

**Comment by alculquicondor** [comment]
/reopen

I just saw this again

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91071/pull-kubernetes-integration/1260644528591736833

**Comment by ahg-g** [comment]
Seems to be green: https://k8s-testgrid.appspot.com/sig-release-1.19-blocking#integration-1.19&include-filter-by-regex=TestPreemptionRaces

**Comment by Huang-Wei** [comment]
It's still flaky on both master and PR testing:

- master: https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master&include-filter-by-regex=TestPreemptionRaces ([log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1322220788899647488))
- PR testing:  #96062 ([log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96062/pull-kubernetes-integration/1322282344635174912)).

/reopen

**Comment by Huang-Wei** [comment]
From the above two logs, I'm feeling that there is a "phantom" event (very likely of type Update by enforced resync) triggering the `preemptor` pod in the completed N<sub>th</sub> test, to be still alive in the N+1<sub>th</sub> test.

```
12891 I1030 21:32:21.388951  122292 scheduler.go:447] Attempting to schedule pod: preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod
12892 I1030 21:32:21.389171  122292 default_binder.go:51] Attempting to bind preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod to node1
12893 I1030 21:32:21.391156  122292 httplog.go:89] "HTTP" verb="POST" URI="/api/v1/namespaces/preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/pods/pree      mptor-pod/binding" latency="1.555975ms" userAgent="scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="127.0.0.1:52576" resp=404
12894 E1030 21:32:21.391543  122292 framework.go:743] "Failed running Bind plugin" err="pods \"preemptor-pod\" not found" plugin="DefaultBinder" pod="preem      ption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod"
12895 I1030 21:32:21.391589  122292 scheduler.go:420] Failed to bind pod: preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod
12896 E1030 21:32:21.391647  122292 factory.go:345] "Error scheduling pod; retrying" err="Binding rejected: running Bind plugin \"DefaultBinder\": pods \"p      reemptor-pod\" not found" pod="preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod"
12897 W1030 21:32:21.391663  122292 factory.go:351] Pod preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod doesn't exist in informer cache:       pod "preemptor-pod" not found
12898 I1030 21:32:21.391696  122292 scheduler.go:343] Updating pod condition for preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod to (PodS      cheduled==False, Reason=SchedulerError)
12899 I1030 21:32:21.393673  122292 httplog.go:89] "HTTP" verb="PATCH" URI="/api/v1/namespaces/preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/pods/pre      emptor-pod/status" latency="1.190797ms" userAgent="scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="127.0.0.1:52576" resp=404
12900 E1030 21:32:21.393881  122292 scheduler.go:338] Error updating pod preemption-race1543a148-7525-4510-ae9b-38fabe86d5be/preemptor-pod: pods "preemptor      -pod" not found
```

**Comment by Huang-Wei** [comment]
/triage accepted
working on a fix.

**Comment by soulxu** [comment]
It would be great if we assign a different name to the Nth round test. Currently, whatever this is Nth test, the preemptor pod is always called 'preemptor-pod'.
