### ISSUE TITLE
Resource status should be synchronized on each display interface.

### ISSUE THREAD

**Issue by AaronLux** [kubernetes/kubernetes#85080]
The display of resource status should be synchronized on each display interface.

After the resource declared by the yaml file of the resource is edited by the kubectl edit command, the corresponding yaml file should be modified synchronously or through a mechanism to reflect the change of the resource declaration.

**Comment by liggitt** [comment]
It's unclear what this is asking for. Can you describe what steps you would want to perform and what the desired outcome would be? After performing a change via `kubectl edit`, the updated resource is persisted in the API server and can be fetched/displayed.

**Comment by AaronLux** [comment]
Sorry, my bad. Wrong-way to create Kube config.

**Comment by AaronLux** [comment]
Sorry, my bad. Wrong-way to create Kube config.
