### ISSUE TITLE
Could Resource of RBAC Rule be described by labels 

### ISSUE THREAD

**Issue by idouba** [kubernetes/kubernetes#85083]
Instead of currently use resourceNames to describe the Resource of Role，Could labels be used to select the matched resources, since we  can not enumerate all the resource names in case resource is dynamically created.

**Comment by kevin-wangzefeng** [comment]
Duplicate with https://github.com/kubernetes/kubernetes/issues/56582, https://github.com/kubernetes/kubernetes/issues/44703. Closing this.
