### ISSUE TITLE
remove redundant replace block

### ISSUE THREAD

**Issue by carnott-snap** [kubernetes/kubernetes#85105]
**What would you like to be added**:
I would like to see the removal of unnecessary `replace` blocks within component repos. E.g. `k8s.io/api`:
```diff
diff --git a/go.mod b/go.mod
index 9d0f0a14..2f97d6a1 100644
--- a/go.mod
+++ b/go.mod
@@ -9,9 +9,3 @@ require (
        github.com/stretchr/testify v1.3.0
        k8s.io/apimachinery v0.0.0-20191109100837-dffb012825f2
 )
-
-replace (
-       golang.org/x/sys => golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
-       golang.org/x/tools => golang.org/x/tools v0.0.0-20190821162956-65e3620a7ae7
-       k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20191109100837-dffb012825f2
-)
```

**Why is this needed**:
This `replace` contains two override types. The first is a noop, `k8s.io/apimachinery` is required at `v0.0.0-20191109100837-dffb012825f2`, so this `replace` only serves to confuse consumers and suggest that the `replace` is necessary.

The second downgrades a transitive dependency: `golang.org/x/{sys,tools}`. Assuming this is required, and the reason for the downgrade is a regression or breaking change, I would expect this requirement to be better documented, so a fix can be tracked. To my knowledge the extended standard library, is quite stable, so I am unclear why we are downgrading this, but it will eventually break dependencies as they pull in new features from higher versions.

**Comment by carnott-snap** [comment]
cc: @liggitt

**Comment by liggitt** [comment]
The golang.org/x dependencies track the branch that corresponds to the go version we build with, and in some cases (like golang.org/x/net) are embedded into the stdlib. The go project and go modules do not provide a better way to pin to those versions.

For the peer dependencies, see https://github.com/kubernetes/kubernetes/issues/84608 and https://github.com/kubernetes/enhancements/pull/1350 for plans to start adding semver tags that are preserved in the go.mod files. As part of that we will be adjusting the way peer dependencies reference each other, and can consider dropping the replace directives that match the require versions.

**Comment by liggitt** [comment]
where would be helpful to document the golang.org/x/… reason?

**Comment by liggitt** [comment]
> it will eventually break dependencies as they pull in new features from higher versions.

We'll have to deal with that if/when we encounter it, but since we update every go release, it hasn't been an issue.

**Comment by carnott-snap** [comment]
> The golang.org/x dependencies track the branch that corresponds to the go version we build with, and in some cases (like golang.org/x/net) are embedded into the stdlib. The go project and go modules do not provide a better way to pin to those versions.

I can understand academically why it may be safer to pin to your release's branch, but none of your consumers see this override. Has this caused breakage? Should we be pushing the Go authors to be releasing the extended standard library with release specific versions? E.g. `golang.org/x/v13/...`. 

I realise there are different concerns when building the kubernetes binaries and consuming the kubernetes libraries, but should they not use the same dependency versions?

> where would be helpful to document the golang.org/x/… reason?

I think this would be best in any `go.mod` that `replace`s it:  (I think that either the postfix comment or the block comment should be enough on their own)
```go
// downgrade the resolved versions of golang.org/x/... to the release we build with.
replace (
        golang.org/x/sys => golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a // release-branch.go1.12
        golang.org/x/tools => golang.org/x/tools v0.0.0-20190821162956-65e3620a7ae7 // release-branch.go1.12
)
```

> For the peer dependencies, see #84608 and [kubernetes/enhancements#1350](https://github.com/kubernetes/enhancements/pull/1350) for plans to start adding semver tags that are preserved in the go.mod files. As part of that we will be adjusting the way peer dependencies reference each other, and can consider dropping the replace directives that match the require versions.

I completely support the move to semver tags, but today these lines are noops, right? What is the benefit of having the `replace` if it is doing nothing? Many consumers have incorrectly assumed these are required, because the kubernetes repo does it.

Again, can we document these inline:
```go
// downgrade peer dependencies to the correct release lineage.
replace (
        k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20191109100837-dffb012825f2 // kubernetes-1.15.0-alpha.0
)
```

**Comment by liggitt** [comment]
> What is the benefit of having the replace if it is doing nothing?

It guarantees that the versions used when tidying for publication match the version used by all other components in a k8s.io/kubernetes build. We can look into making the publishing bot remove them if they are indeed no-ops and match the require statement

**Comment by liggitt** [comment]
cc @sttts

**Comment by liggitt** [comment]
> I think that either the postfix comment or the block comment should be enough on their own

we use `go mod edit` to manipulate the go.mod file, and it doesn't provide comment edit capability currently
