### ISSUE TITLE
Go modules failing with "kubernetes-1.15.4" and "k8s.io/apimachinery" when GOPROXY disabled

### ISSUE THREAD

**Issue by akutz** [kubernetes/kubernetes#85103]
**What happened**:
Running `go mod download` with `GOPROXY` disabled in a project that references `k8s.io/apimachinery@kubernetes-1.15.4` fails with either:

**Go 1.12**

```shell
verifying k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/go.mod: checksum mismatch
        downloaded: h1:nEP/6rwhzfljWYGVS6pfyES3ipZTR19vzMnSM+ur3ho=
        go.sum:     h1:3jediapYqJ2w1BFw7lAZPCx7scubsTfosqHkhXCWJKw=
```

or

**Go 1.13**

```shell
go: k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d: invalid pseudo-version: does not match short name of revision (c18f71bf2947)
make: *** [Makefile:203: modules-download] Error 1
```

The failures occur because `f2f3a405f61d` was pushed as [a branch](https://github.com/kubernetes/apimachinery/commit/f2f3a405f61d) to the API machinery repository, confusing the Go module solver.

**What you expected to happen**:

For it to work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create **`main.go`**:

    ```golang
    package main

    import (
        _ "k8s.io/apimachinery"
    )

    func main() {
    }
    ```

2. Create **`go.mod`**:

    ```text
    module test

    go 1.12

    require k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d
    ```

3. Clear the modulde cache with `go clean -modcache`

4. Then run `go mod download`:
   1. Go 1.12

    ```shell
    $ GOPROXY=direct go mod download
    verifying k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/go.mod: checksum mismatch
            downloaded: h1:nEP/6rwhzfljWYGVS6pfyES3ipZTR19vzMnSM+ur3ho=
            go.sum:     h1:3jediapYqJ2w1BFw7lAZPCx7scubsTfosqHkhXCWJKw=
    ```

   2. Go 1.13

    ```shell
    $ GOPROXY=direct go mod download
    go: k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d: invalid pseudo-version: does not match short name of revision (c18f71bf2947)
    ```

**Anything else we need to know?**:

* There's are several conversations about this issue on Slack in the #sig-api-machinery channel all beginning with [this post](https://kubernetes.slack.com/archives/C0EG7JC6T/p1573486851021400).
* The are plans to delete the [offending branch](https://github.com/kubernetes/apimachinery/commit/f2f3a405f61d) after an investigation into the matter is completed.
* It's the accepted conclusion that removing the branch will cause the Go module solver to function correctly, as it did before the branch was created.
* All credit to @camilamacedo86 for first discovering this issue at https://github.com/kubernetes-sigs/kubebuilder/issues/1169 and to @ncdc for root causing the issue

cc @liggitt @ncdc @cblecker @nikhita

**Comment by akutz** [comment]
I can confirm that deleting the offending branch has resolved the issue. @ncdc also confirmed this in a private Slack thread.

**Comment by cblecker** [comment]
Root cause was identified as human error. Branch has been deleted, and functionality returned to normal.

/close
