### ISSUE TITLE
nullable in OpenAPI schema breaks server-side-apply

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#85127]
With `nullable: true` in a CRD we get:
```
E1111 19:21:58.602019       1 customresource_handler.go:655] error building openapi models for clusteroperators.config.openshift.io: ERROR $root.definitions.io.openshift.config.v1.ClusterOperator.properties.status.properties.extension has invalid property: nullable
```

This is because gnostic's OpenAPI proto types have no nullable support.

Luckily CRDs keep working because in the upper error case we don't stop serving, just set the SSA schema to nil.

**Comment by apelisse** [comment]
Thanks for reporting!

**Comment by apelisse** [comment]
> This is because gnostic's OpenAPI proto types have no nullable support.

I think it should be "This is because gnostic's OpenAPI **v2** proto types have no nullable support.".
The problem is that we're not supposed to pass-in v3.

**Comment by apelisse** [comment]
Source: #77354

**Comment by apelisse** [comment]
https://github.com/kubernetes/kubernetes/pull/77354/commits/c0617933d4bec5b00dbbfcd24edb7d7e7fc5509d#diff-2f720a7e61a4ddfcfe9a9e353be8784b

**Comment by apelisse** [comment]
OK, We'll write a test and fix this, thanks Stefan!

**Comment by sttts** [comment]
/reopen

This still happens in slightly different shape:

```
customresource_handler.go:652] error building openapi models for clusterresourcequotas.quota.openshift.io: ERROR $root.definitions.io.openshift.quota.v1.ClusterResourceQuota.properties.spec.properties.quota.properties.hard.additionalProperties.schema has invalid property: anyOf
```

This comes from `x-k-int-or-string`: https://github.com/openshift/api/blob/master/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml#L43

**Comment by apelisse** [comment]
That's a fairly different bug but yes, thanks!

**Comment by alexellis** [comment]
Is this related to the [following blog post](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) stating that use of "anyOf" wouldn't be allowed after 1.16? We're seeing issue https://github.com/openfaas/faas-netes/issues/630 on OpenFaaS after going to 1.17.5 and 1.18. Usually upgrading K8s versions hasn't caused breaking changes and we're trying to figure out where to start with this one.

**Comment by liggitt** [comment]
> Is this related to the [following blog post](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) stating that use of "anyOf" wouldn't be allowed after 1.16?

No. That post was about structural schemas. v1 CRDs are limited to structural schemas. v1beta1 CRDs can continue to create non-structural schemas until v1beta1 is no longer served (in 1.22)

Also, `anyOf` is not completely disallowed, specific restrictions inside an `anyOf` clause (like `type`) are what are not allowed ("logical constraints using oneOf, allOf, anyOf, not are allowed").

**Comment by liggitt** [comment]
extracted the newly found issue to https://github.com/kubernetes/kubernetes/issues/90902 to track separately

/close
