### ISSUE TITLE
Add ondelete updateStrategy for deployment workload

### ISSUE THREAD

**Issue by skilxn-go** [kubernetes/kubernetes#85130]
**What would you like to be added**:
Add ondelete updateStrategy for deployment.

**Why is this needed**:
For example, our service/workload is stateless. However people may still want to control the detail of pods' updating.
I can achieve this by using a StatefulSet, but I think if deployment supports this kind of updateStrategy is more suitable (for that we don't need any other feature of a StatefulSet expect the 'ondelete' strategy)

**Comment by skilxn-go** [comment]
I can do some work around this feature if that's acceptable

**Comment by munnerz** [comment]
I think this would fall under sig-apps, as they own Deployment code 😄

/sig apps

**Comment by skilxn-go** [comment]
> I think this would fall under sig-apps, as they own Deployment code 😄
> 
> /sig apps

Thanks~:D
