### ISSUE TITLE
Passing labels as number results in misleading error

### ISSUE THREAD

**Issue by cardil** [kubernetes/kubernetes#85143]
**What happened**:
Creating a resource labeled with numeric value resultd in misleading message. 

Error says: `ReadString: expects " or n, parsing XX`

**What you expected to happen**:
As labels must have values as string, error should be: `ReadString: expects ", parsing XX` or even better `ReadString: expects string value, parsing XX`

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat test-pod-label.yml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    version: 5
spec:
  containers:
  - name: test-pod
    image: nginx

$ kubectl create -f test-pod-label.yml --v=5
I1221 10:21:46.825438   26565 decoder.go:224] decoding stream as YAML
I1221 10:21:46.828584   26565 helpers.go:207] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"test-pod-label.yml\": Pod in version \"v1\" cannot be handled as a Pod: v1.Pod: Spec: v1.PodSpec: ObjectMeta: v1.ObjectMeta: Namespace: Name: Labels: ReadString: expects \" or n, parsing 65 ...version\":5... at {\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"labels\":{\"version\":5},\"name\":\"test-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"image\":\"nginx\",\"name\":\"test-pod\"}]}}",
  "reason": "BadRequest",
  "code": 400
}]
F1221 10:21:46.828627   26565 helpers.go:120] Error from server (BadRequest): error when creating "test-pod-label.yml": Pod in version "v1" cannot be handled as a Pod: v1.Pod: Spec: v1.PodSpec: ObjectMeta: v1.ObjectMeta: Namespace: Name: Labels: ReadString: expects " or n, parsing 65 ...version":5... at {"apiVersion":"v1","kind":"Pod","metadata":{"labels":{"version":5},"name":"test-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx","name":"test-pod"}]}}
```

**Environment**:
- Kubernetes version: any
- Cloud provider or hardware configuration: any

**Relations**:
* https://github.com/kubernetes/kubernetes/issues/57509

**Comment by liggitt** [comment]
Thanks for the report, but null is also accepted for string fields by the json parser, so the string token must begin with " or n (for null)

The current message, along with the context of what part of the manifest was not valid, should provide enough information to resolve the issue

/close
