### ISSUE TITLE
cannot find replacement package to k8s.io/kubernetes@1.15.4

### ISSUE THREAD

**Issue by carnott-snap** [kubernetes/kubernetes#85161]
**What happened**:
I would like to use the `k8s.io/kubernetes/cmd/kubeadm/app/util/kubeconfig` and `k8s.io/kubernetes/pkg/kubectl/cmd/util` packages in the 1.15.x line. Unfortunately, both appear to only exist in this repo, and iirc we should not import `k8s.io/kubernetes` directly, per kubernetes/kubernetes#81878.

**What you expected to happen**:
There should be an importable location to use this logic.

**Anything else we need to know?**:
This is being done within the context of the [helm-operator](https://github.com/fluxcd/helm-operator) Go module.

**Comment by carnott-snap** [comment]
/sig cluster-lifecycle cli
cc: @liggitt

**Comment by liggitt** [comment]
Making kubeadm code available for consumption is tracked in https://github.com/kubernetes/kubernetes/issues/78534

Most kubectl packages are exported to https://github.com/kubernetes/kubectl as of 1.16 (e.g. https://github.com/kubernetes/kubectl/tree/master/pkg/util)
