### ISSUE TITLE
Pull secrets don't work from static config files

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#8517]
It would be nice to be able to use kubelet to start master components from static config files, where the containers are located in a private repo. But there's no way to get kubelet to use a pull secret when master components haven't started yet.

**Comment by lavalamp** [comment]
@deads2k

**Comment by pmorie** [comment]
@jimmidyson

**Comment by pmorie** [comment]
related to #8379

**Comment by lavalamp** [comment]
Also interesting would be to just include the container in the secret, so that no pulling was necessary. (Is there a size limit on secrets?) Alternatively, a secret with some way of saying "for container foo/bar:v1, do ```wget https://foo/bar:v1``` instead of a docker pull" could be interesting.

**Comment by deads2k** [comment]
> It would be nice to be able to use kubelet to start master components from static config files, where the containers are located in a private repo. But there's no way to get kubelet to use a pull secret when master components haven't started yet.

I think this is a good fit for the node based `.dockercfg` pull secrets (or whatever other kind of secret).  Since the static file is located on the node itself, it seems reasonable to require that the authentication information for a private repo also exist on that node.
