### ISSUE TITLE
kubectl: error: error: could not get a token from the cache or provider: error while authentication: invalid token and you need to remove the cache: could not decode the json of token: json: cannot unmarshal array into Go struct field StandardClaims.aud of type string

### ISSUE THREAD

**Issue by rforberger** [kubernetes/kubernetes#85197]
**What happened**:
I get the error message 
```
error: error: could not get a token from the cache or provider: error while authentication: invalid token and you need to remove the cache: could not decode the json of token: json: cannot unmarshal array into Go struct field StandardClaims.aud of type string
```

when using any kubectl command. My kubernetes uses OpenID as authentication (keycloak).

I have been told on Stackoverflow that this is a kubectl bug with the GO implementation, which does not support the return of an Array instead of a string in the audience field for the JWT. The RFC of JWT tells that it's allowed to return an Array instead of a string.

I am using the following kubectl and go version:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

My kubectl runs on Ubuntu 18.04 LTS amd64.

I have been told, that it's maybe a problem with the go JWT implementation from https://github.com/dgrijalva/jwt-go (just a guess).

**What you expected to happen**:

kubectl correctly accessing the kubernetes api.

**How to reproduce it (as minimally and precisely as possible)**:

kubectl get pods

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
onpremise 
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
4.4.0-43-Microsoft (Windows Subsystem for Linux)
- Install tools:
kubectl was installed via APT from the official google repository.
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rforberger** [comment]
The problem disappeared without intervention on setup. Don't understand it. I leave the bug report open anyway, since someone might want to look into it.

**Comment by mikedanese** [comment]
> I have been told, that it's maybe a problem with the go JWT implementation from https://github.com/dgrijalva/jwt-go (just a guess).

Sounds about right. Looks like they don't properly handle audience claims:

https://github.com/kubernetes/kubernetes/blob/7a5929da02f9fbdb9d63b5335f159462cc553020/vendor/github.com/dgrijalva/jwt-go/claims.go#L19

What version of kubectl were you using? What kubectl plugin are you using for auth? Openstack or OIDC?

**Comment by rforberger** [comment]
@mikedanese 
I am using kubectl v1.16.2.
And I am using the OIDC plugin.

**Comment by mikedanese** [comment]
Thanks, should have read the description.

> could not get a token from the cache or provider: error while authentication: invalid token and you need to remove the cache

I'm having a really hard time finding this error string (via git grep and github/Google search).

**Comment by rforberger** [comment]
@mikedanese 
Maybe it's in the OpenID codebase? (just a guess from a non-full time programmer)

**Comment by rforberger** [comment]
The problem just occured again, but I can't track down why it is occuring. I had to delete the OIDC token again and log on to keycloak again, then everything worked fine again.

**Comment by enj** [comment]
@rforberger if it happens again, could you try to run at a high log level and provide the redacted output (along with a redacted kubeconfig)?

**Comment by rforberger** [comment]
@enj Ok, I will do that, but it didn't occur again so far.

**Comment by danieleva** [comment]
Having the same issue here. My idp returns tokens with a list of strings for the audience claim, and that breaks jwt-go. The issue is already flagged upstream, see https://github.com/dgrijalva/jwt-go/pull/355

**Comment by rforberger** [comment]
For me it didn't occur again. Not really sure when it occurs. Maybe it is a Windows Subsystem for Linux related issue, since it didn't happen to me on any real UNIX platform.
