### ISSUE TITLE
Sort out the dependency in e2e framework

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#85193]
**What would you like to be added**:

As discussed in https://github.com/kubernetes/kubernetes/pull/84439/files#r345375300, we should sort out the dependency in e2e framework.
For example, the https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pods.go has a dependency of `e2epod "k8s.io/kubernetes/test/e2e/framework/pod"`.

/sig testing
/kind feature
cc @oomichi 

**Why is this needed**:

This will eliminate the possibility of circular dependence in e2e framework.

**Comment by oomichi** [comment]
@danielqsj 
Sorry for my late comment.
This issue is duplicated with https://github.com/kubernetes/kubernetes/issues/81245
With https://github.com/kubernetes/kubernetes/issues/81245 we manage what files should be fixed actually.
So how about concentrating on the above issue instead of this?

**Comment by danielqsj** [comment]
@oomichi Thanks, that's great. I missed this issue before.
I will close this one.
