### ISSUE TITLE
 if --client-ca-file and --requestheader-client-ca-file have something different

### ISSUE THREAD

**Issue by zhaofengcumt** [kubernetes/kubernetes#85199]
K8S version : 1.13.12

```
here is my part config of kube-scheduler, I wonder if --client-ca-file and --requestheader-client-ca-file
have something different,thanks
```

**Comment by liggitt** [comment]
Yes, they are different.

--client-ca-file specifies the CA bundle used to verify client certificates where the authentication information is contained in the certificate subject

--requestheader-client-ca-file specifies the CA bundle used to verify the identity of an authenticating proxy, before trusting authentication information sent in headers like `X-Remote-User`.

See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs and https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy for details
