### ISSUE TITLE
fluentd-es-configmap use old config queue_limit_length

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#85195]
fluentd-es-configmap use old config queue_limit_length which referencing https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml
But fluentd docs says "This parameter is for v0.12 compatibility. Use total_limit_size instead for v1 configuration.",  which referencing https://docs.fluentd.org/configuration/buffer-section#argument

**Comment by RainbowMango** [comment]
@like-inspur 
Yeah, thanks for you reporting this. 
Seems we just need to remove `queue_limit_length` here, because `total_limit_size` has a default value `Default: 512MB (memory) / 64GB (file)`. 

I'm not familiar with this and I will be appreciated if you can help confirm this.

/assign

**Comment by like-inspur** [comment]
yes, I will create a pull request for this

**Comment by RainbowMango** [comment]
@like-inspur 
You can close this issue now since PR has been merged.
