### ISSUE TITLE
Using resourceVersion on different annotate requests does not guarantee atomic updates

### ISSUE THREAD

**Issue by behos** [kubernetes/kubernetes#85198]
**What happened**:

Running annotations on multiple nodes at the same time unexpectedly succeeds.

```
kubectl annotate cm/sequence id=5 --resource-version=123456 --overwrite
```

Each node receives a success with its own updates in the response and the same _new_ resourceVersion.

**What you expected to happen**:

I expect that only one of these annotations would succeed with every other one getting a conflict error.

**How to reproduce it (as minimally and precisely as possible)**:

Open 2 tmux panes and broadcast the command.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: "v1.16.0"
Server Version:"v1.10.11"
```

- Cloud provider or hardware configuration: Happens on both AWS and GCP
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

It looks like the resourceVersion check is happening on the client side based on the requests/responses logged in the command. Is that the case?

**Comment by behos** [comment]
@kubernetes/sig-cli-bug

**Comment by liggitt** [comment]
resourceVersion only increments when the bytes persisted to etcd change

two patch requests both setting identical patches can go in either order and the second is a no-op, meaning it doesn't increment the resourceVersion

**Comment by behos** [comment]
I suspected this could have been the case (one being a no-op that is) so I tried something different as well, by setting an additional annotation which was unique to each process:

```
kubectl annotate cm/sequence id=5 set-by=$MY_ID --resource-version=123456 --overwrite
```

This had the same result with both calls succeeding and the cm ending up with the values of one of these commands (I guess whichever one got there last).

The verbose output of the command looks like 2 requests are being done during an annotate:

1. A `GET` request fetching the original `cm` with the `resourceVersion` included in the response.
2. A `PATCH` request with the attributes which need to be changed in the body. The patch request itself doesn't seem to include the `resourceVersion` at all.

So I'm wondering whether the `--resource-version` argument actually checks the conditions somewhere between 1 and 2 on the client side thus only guaranteeing atomicity when the calls happen consequtively.

**Comment by behos** [comment]
Actually I think I just figured this out:

When adding the `--resource-version` attribute all this does is that it sets it in the `updated` object here:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/annotate/annotate.go#L378

Once this is set, then it's diff'ed with the original object in order to make the patch body here:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/annotate/annotate.go#L281

If the resource version between the 'old' and 'new' data is different, then it's added to the diff and is sent to the server (which causes it to fail):

```
I1114 09:04:41.071709   12712 request.go:968] Request Body: {"metadata":{"annotations":{"some-annotation":"1234"},"resourceVersion":"1"}}
```

```
F1114 09:04:41.228355   12712 helpers.go:114] Error from server (Conflict): Operation cannot be fulfilled on configmaps "cm": the object has been modified; please apply your changes to the latest version and try again
```

On the other hand, if the `resourceVersion` is the same at the time of the diff'ing, the resource version isn't added to the request at all.

```
I1114 09:10:32.169556   13715 request.go:968] Request Body: {"metadata":{"annotations":{"some-annotation":"1234"}}}
```

Which means that the server doesn't check the `resourceVersion` at all, meaning that it allows concurrent changes as long as all clients are using the same 'old' object.

It seems like the solution would be to always add the resource version in the final diff before it being sent.

**Comment by liggitt** [comment]
> It seems like the solution would be to always add the resource version in the final diff before it being sent.

You're correct. Opened #85285 to fix this
