### ISSUE TITLE
Specially crafted seccomp profiles may trap containers on exit loop indefinitely

### ISSUE THREAD

**Issue by pjbgf** [kubernetes/kubernetes#85191]
**What happened**:

Containers get stuck at `Running` state and CPU spikes at 100% usage indefinitely until a user manually stops it.

**What you expected to happen**:
1. Not be able to create a custom seccomp profile that cannot exit itself.
OR
2. Container to finish execution and move to `Completed` state.

**How to reproduce it (as minimally and precisely as possible)**:

1. Place the contents of `pod-trapped.json` into `/var/lib/kubelet/seccomp/`
2. Create the pod defined in the `pod.yaml` file
3. Confirm that `trapped` is running with `kubectl get pod trapped`
4. Check resource usage with `htop` and confirm that both `/pause` and `echo hi` are consuming 100% of CPU.

![image](https://user-images.githubusercontent.com/5452977/68747483-87fdc080-05f2-11ea-9a9a-118b28eaf6bf.png)

5. Run `strace` to confirm the problem:

![image](https://user-images.githubusercontent.com/5452977/68747608-cdba8900-05f2-11ea-9f62-5b41852fd826.png)

The same can be achieved by dropping `exit_group` and/or `exit` inside the container through a `prctl` call.

**Anything else we need to know?**:

*pod.yaml*
```
apiVersion: v1
kind: Pod
metadata:
  name: trapped
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'localhost/pod-trapped.json'
spec:
  containers:
  - name: trapped
    image: alpine
    command: ["echo", "hi"]
```
*pod-trapped.json*
```
{
   "defaultAction": "SCMP_ACT_ERRNO",
   "architectures": [
       "SCMP_ARCH_X86_64",
       "SCMP_ARCH_X86",
       "SCMP_ARCH_X32"
   ],
   "syscalls": [
       {
           "names": [
               "arch_prctl",
               "brk",
               "capget",
               "capset",
               "chdir",
               "close",
               "execve",
               "fstat",
               "fstatfs",
               "futex",
               "getdents64",
               "getppid",
               "mprotect",
               "nanosleep",
               "newfstatat",
               "openat",
               "prctl",
               "read",
               "rt_sigaction",
               "setgid",
               "setgroups",
               "setuid",
               "stat",
               "uname",
               "write",
               "epoll_create",
               "epoll_wait",
               "epoll_pwait"
           ],
           "action": "SCMP_ACT_ALLOW"
       }
   ]
}
```

The PR #85121 decreases the impact by not allowing the `pause` container to be trapped when using dockershim.

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.0.503+d366d2eaa36e0d-dirty", GitCommit:"d366d2eaa36e0d27fca529ea0be6648f56513fda", GitTreeState:"dirty", BuildDate:"2019-11-13T07:55:07Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```
- Hardware configuration:
```
AMD Ryzen 5 3600
Asus Prime 570-P
Corsair 32GB 3200mhz (DDR4) C16
Samsung 970 EVO Plus 1 TB NVMe M.2
Sapphire Radeon RX 580 8GB
```
- OS:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel: 
```
Linux passionfruit 5.0.0-35-generic #38~18.04.1-Ubuntu SMP Mon Nov 11 09:16:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Others:
```
$ docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

/sig node
/area security
/cc @tallclair

**Comment by pjbgf** [comment]
Related to https://github.com/moby/moby/issues/40205

**Comment by tallclair** [comment]
@pjbgf any updates on this issue?

**Comment by pjbgf** [comment]
@tallclair from a Kubernetes project perspective, I think the only thing we can do is to implement the sandbox container seccomp - which is already being handled by #84623. For users' containers this is probably better handled at the container run-time.

Based on that, I think we can close this issue.
