### ISSUE TITLE
GetDiskFormat can't work on util-linux 2.33.2

### ISSUE THREAD

**Issue by FengyunPan2** [kubernetes/kubernetes#85203]
\1. GetDiskFormat works fine on util-linux 2.23.2
\# blkid -v
blkid from util-linux 2.23.2  (libblkid 2.23.0, 25-Apr-2013)
\# blkid   -p -s TYPE -s PTTYPE -o export /dev/loop3
DEVNAME=/dev/loop3
PTTYPE=dos

\2.GetDiskFormat can't work on util-linux 2.33.2
/ # apk info blkid 
blkid-2.33.2-r0 description:
block device identification tool
blkid-2.33.2-r0 webpage:
https://git.kernel.org/cgit/utils/util-linux/util-linux.git
blkid-2.33.2-r0 installed size:
106496
/ # blkid   -p -s TYPE -s PTTYPE -o export /dev/loop3
/dev/loop3: UUID="b60a3828-ea89-4f6f-b9c8-670ab628f4bb" TYPE="xfs"

log:
I1113 08:26:19.386802       1 mount_linux.go:346] Attempting to determine if disk "/dev/loop3" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/loop3])
I1113 08:26:19.391630       1 mount_linux.go:349] Output: "/dev/loop3: UUID=\"1a5a2267-4faa-4860-8327-3f658cfa2ec1\" TYPE=\"xfs\"\n", err: <nil>
E1113 08:26:19.391670       1 server.go:122] GRPC error: rpc error: code = Internal desc = Could not resize volume "681f9cb3-05ea-11ea-868f-5e3e8f5ba52c":  ResizeFS.Resize - error checking format for device /dev/loop3: blkid returns invalid output: /dev/loop3: UUID="1a5a2267-4faa-4860-8327-3f658cfa2ec1" TYPE="xfs"

**What would you like to be added**:
Update the codes of GetDiskFormat()

**Why is this needed**:
make it work

**Comment by CFSworks** [comment]
I just ran into this, also on Alpine (judging by your use of `apk`), but I had the Busybox `blkid` installed and it gave the exact same output. Are you sure your `blkid` binary wasn't Busybox?

```
MountVolume.MountDevice failed for volume "ssd" : local: failed to mount device /dev/nvme0n1 at /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/ssd (fstype: ext4), error failed to get disk format of disk /dev/nvme0n1: blkid returns invalid output: /dev/nvme0n1: UUID="07beaf00-c867-4096-9a74-e77c9c2dbd5f" TYPE="ext4"
```

I'd do a fresh bug report to talk about perhaps updating `mount_linux.go` to understand the default/Busybox output format of `blkid`, but the issue form requests a *lot* of information that I can't easily collect, and installing the "real" `blkid` fixed my problem anyway.
