### ISSUE TITLE
1.15 CoreDNS immediately crash if Kubernetes apiserver is unavailable

### ISSUE THREAD

**Issue by blurpy** [kubernetes/kubernetes#85205]
**What happened**:

When the apiserver is unavailable, CoreDNS pods crash while trying to write log files to the read only file system.

**What you expected to happen**:

CoreDNS should continue to run even if the apiserver is unavailable for a short period of time. Log files should be written to an emptyDir.

**How to reproduce it (as minimally and precisely as possible)**:

Restart the apiserver. Notice when the apiserver is back up that CoreDNS pod status is either Error, CrashLoopBackOff or Running but Ready is 0/1. Restart count has increased by at least 1.

**Anything else we need to know?**:

This is a regression from #75414. The initial fix was to upgrade CoreDNS from 1.3.1 to 1.5.0, but it was later reverted, as you can see from the history [here](https://github.com/kubernetes/kubernetes/commits/release-1.15/cmd/kubeadm/app/phases/addons/dns/manifests.go). The initial issue then reappeared. A fix was made for 1.14 in pull request #82128 to mount an emptyDir to /tmp to keep the pods from crashing when writing log files. The same fix can be applied in 1.15.

This issue is blocking rollout of 1.15 for us. It would be really nice if the suggested fix could be included in 1.15.6.

**Environment**: Test
- Kubernetes version (use `kubectl version`): v1.15.5
- Cloud provider or hardware configuration: On premise, vmware nodes
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-957.5.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Canal v3.7.2
- Others:

**Comment by blurpy** [comment]
/sig cluster-lifecycle

(Just guessing based on the original issue)

**Comment by blurpy** [comment]
Thanks for the fix! I see it's been merged, but it's not listed in the release notes in the 1.15.7 cut. Should it have been picket up?

**Comment by chrisohaver** [comment]
IIUC, #85212 does not itself have a release note, so it's not listed in the release notes.

**Comment by blurpy** [comment]
I've verified that the problem has been resolved in 1.15.7.
