### ISSUE TITLE
[Umbrella Issue] Network Proxy Egress Endpoints for Beta

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#85250]
Based on the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md#kubernetes-api-server-outbound-requests), this is the list of all egress endpoints required to be implemented for network proxy.

- **Merged: (#82048)** ~~ETCD It is possible to make etcd talk via the proxy. The etcd client takes a transport. (https://github.com/etcd-io/etcd/blob/master/client/client.go#L101) We will add configuration as to which proxy an etcd client should use.(https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go) This will add an extra process hop to our main scaling axis. We will scale test the impact and publish the results. As a precaution we will add an extra network configuration 'etcd' separate from ‘master’. Etcd requests can be configured separately from the rest of 'master'.~~
- **Merged: (#78543)** ~~Pods/Exec~~, ~~Pods/Proxy~~ **(#84381)** (, Pods/Portforward, ~~Pods/Attach~~, ~~Pods/Log Pod requests (and pod sub-resource requests) are meant for the cluster and will be routed based on the ‘cluster’ NetworkContext.~~
- **Merged: (#78543)**  ~~Nodes/Proxy Node requests (and node sub-resource requests) are meant for the cluster and will be routed based on the ‘cluster’ NetworkContext.~~
- **Merged (#78543)**. ~~Services/Proxy Service requests (and service sub-resource requests) are meant for the cluster and will be routed based on the ‘cluster’ NetworkContext.~~
- **Merged: (#85168)** ~~Admission Webhooks + Dynamic Audit Webhook. Admission webhooks can be destined for a service or a URL. If destined for a service then the service rules apply (send to 'cluster'). If destined for a URL then we will use the ‘master’ NetworkContext.~~
- **Merged (#87515)** ~~Aggregated API Server (and OpenAPI requests for aggregated resources) Aggregated API Servers can be destined for a service or a URL. If destined for a service then the service rules apply. If destined for a URL then we will use the ‘master’ NetworkContext.~~
- **Merged (#85870)** ~~Authentication, Authorization and Audit Static Webhooks These Webhooks use a kube config file to determine destination. Given that we use a ‘master’ NetworkContext.~~

/sig api-machinery
/cc @cheftako
/cc @fedebongio 
/cc @caesarxuchao

**Comment by Jefftree** [comment]
@cheftako: After looking into this more, KAS communicates with the KMS GRPC Service via [unix sockets](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service.go#L70). I don't think we have the capability to support that type of connection with network proxy yet?

**Comment by Sh4d1** [comment]
@Jefftree @chektako I think the network proxy can be used on a different machine, and this leads to Unix socket to be completely unusable with the network proxy. So either we ignore the KMS endpoint for the network proxy, or it needs to go through the network no?

**Comment by Jefftree** [comment]
Discussed offline with @cheftako. I created a PR to remove KMS from the network proxy beta requirements (https://github.com/kubernetes/enhancements/pull/1389)

**Comment by caesarxuchao** [comment]
@Jefftree "PR (#85870) Authentication, Authorization and Audit Webhooks", that PR only affects the static Audit Webhooks.

Your #85168 affected the dynamic Audit Webhooks (which works very similar to the admission webhook).

Can you update? Thanks.

**Comment by Jefftree** [comment]
@caesarxuchao Updated. Was waiting for the new aggregator PR and it looks like we have everything covered again now.

**Comment by caesarxuchao** [comment]
We might missed an egress point: https://github.com/kubernetes/kubernetes/blob/b1aff7832d8ed78a013f5e0e4b9dc582734d622d/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L230

**Comment by Jefftree** [comment]
All endpoints required for beta are merged.

I will investigate https://github.com/kubernetes/kubernetes/blob/b1aff7832d8ed78a013f5e0e4b9dc582734d622d/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L230 separately.

/close
