### ISSUE TITLE
Statefulset support to update pods parallelly

### ISSUE THREAD

**Issue by yuyulei** [kubernetes/kubernetes#85256]
**What would you like to be added**:
Now StatefulSet's  update strategy including: RollingUpdate and OnDelete. 

RollingUpdate, meaning update pod one by one.
OnDelete, meaning updata after deleted.

I suggest a new policy "Parallelly". This policy also need "partition" field. 

For example, given statefulset with {name: demo, replicas: 5, policy: Parallelly, partition: 2}, then the statefulset controller will update 3 pods(demo-2,demo-3,demo-4), parallelly.

**Why is this needed**:
In my prod env, the statefulset replicas is 200+, every time I update statefulset, it will cost me hours. In case, one day I update a bad version, and all pod crash. At the same time, I rollback to previous version, but it takes hours. It is terrible. 

In the case, although, I can use "OnDelete" policy, but it is not friendly to operate.

Once, I noticed Statefulset "PodManagementPolicy"(Parallel), this policy can add/delete pod parallelly. This really help me when I scale up/down statefulset. I really hope same features can be applied to updating.

previous issue: #83733

**Comment by yuyulei** [comment]
PTAL @smarterclayton

**Comment by yuyulei** [comment]
@kow3ns @smarterclayton

**Comment by yuyulei** [comment]
ptal @liggitt

**Comment by warmchang** [comment]
I think you want StatefulSet to have a richer update stratege like Deployment:

```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```
