### ISSUE TITLE
when pod restart how to kill pause container

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#85261]
when my pod restarted,it has a error,the reason is my subpath file is not umounted,so the new container can not mount to subpath file.
my reqeust is : when my pod restart,how to kill pause container,if that can be done,the subpath file can be make to a new one,then pod can restart without error.

the error:
Nov 14 14:46:44 inspurtest13-rxhqqwykww-slave-0 kubelet[9128]: E1114 14:46:44.715538    9128 remote_runtime.go:226] StartContainer "f0de9f017160580011ae59671616044ced0c62c30f328b6066e29792b06cc687" from runtime service failed: rpc error: code = Unknown desc = failed to start container "f0de9f017160580011ae59671616044ced0c62c30f328b6066e29792b06cc687": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/af833cbc-06a9-11ea-904d-fa163e049303/volume-subpaths/myse/mynginx/0\\\" to rootfs \\\"/var/lib/docker/overlay2/e8f9fe7795420bdcd245e0e1a1cdb09578652cf46a8d5529c0a4f40ec5de05c9/merged\\\" at \\\"/var/lib/docker/overlay2/e8f9fe7795420bdcd245e0e1a1cdb09578652cf46a8d5529c0a4f40ec5de05c9/merged/opt/secret\\\" caused \\\"no such file or directory\\\"\"": unknown

**Comment by neujie** [comment]
Why your pod subpath was deleted?
Just killing the pause container won't solve your problem, cause the volumeManager notes the subpath was mounted.

**Comment by neujie** [comment]
maybe #61446 is the root cause,

**Comment by timyinshi** [comment]
ok,i resove it by deleting pause container or deleting pod
