### ISSUE TITLE
Getting a Arm64 CI for kubernetes

### ISSUE THREAD

**Issue by lubinsz** [kubernetes/kubernetes#85267]
Hi all,

Since the conformance test for arm64 has been running successfully for a long time.
(https://k8s-testgrid.appspot.com/sig-node-arm64)
It would be a good idea to have a CI setup for Arm64,  so that future stuff doesn't break on it.

I summarized some tasks.

Tasks:
* [ ] add several Arm64 servers into k8s CI system
* [ ] apply for free Arm64 machines on this page: https://github.com/WorksOnArm/cluster/issues
* [ ] arm64 CI jobs can be scheduled by Prow into the scpecific arm64 k8s cluster or arm64 nodes
* [ ] setup pull-kubernetes-e2e-kind test on Arm64

cc: @zhlhahaha @chendave @kalyxin02

**Comment by ZhengZhenyu** [comment]
Very interesting proposal, looking forward to see some progress on this issue

**Comment by lubinsz** [comment]
Also cc @BenTheElder @dims

**Comment by BenTheElder** [comment]
These are all stale:
https://testgrid.k8s.io/conformance-kind#kind,%20v1.14%20(dev,%20ARM64)
https://testgrid.k8s.io/conformance-arm

---

>  setup pull-kubernetes-dependencies test on Arm64

This should be unnecessary. This just validates that dependencies are in a sane state (vendor vs go mod).

>  setup pull-kubernetes-verify test on Arm64

This mostly does linting etc. Not sure how worth it this is

> setup pull-kubernetes-typecheck test on Arm64

This is not useful, typecheck's _job_ is typechecking code across platforms, as opposed to a full compilation.

---

In general I'm not enthused about adding any of this to presubmit, we have enough issues with flaky PR testing as is, and we've barely seen any periodic / CI signal from ARM that is reliable (one low frequency job, with several previous setups that do not function at all ...).

Similarly, we do not add every cloud provider to presubmit, I'd much rather see some strong release-blocking CI signal before we go adding PR testing.

**Comment by lubinsz** [comment]
Hi @BenTheElder 
Our conformance test result is here: https://k8s-testgrid.appspot.com/sig-node-arm64#conformance
I will move it into https://testgrid.k8s.io/conformance-arm
Regarding kind, @zhlhahaha is enabling it on Arm64 now.

And I will remove the unnecessary tasks from the list.

**Comment by BenTheElder** [comment]
I would still focus on stable release blocking CI (bring this up with sig
release in their meeting) instead of PR testing.

**Comment by lubinsz** [comment]
Hi @BenTheElder 
Our company hopes that the community can officially announce support for the Arm64 platform. What else do I need to do? Please check my another issue https://github.com/kubernetes/kubernetes/issues/86295
Can give me more suggestions about that issue? 
Thanks.

**Comment by dims** [comment]
@lubinsz the right way to "official" is to write a KEP based on all the discussions on the mailing list, this issue etc, please write one. We can use that to identify gaps, work, etc. get general agreement from everyone then take it through the release process, update documentation etc.

**Comment by BenTheElder** [comment]
/triage duplicate
there are several other issues covering aspects of this topic
/close
