### ISSUE TITLE
Make quick-release-images error

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#85277]
**What happened**:
When i do some command like :
```
KUBE_BUILD_HYPERKUBE=n \
KUBE_BUILD_CONFORMANCE=n \
KUBE_BUILD_PULL_LATEST_IMAGES=n \
 make quick-release-images 
```
An error will happen due to `KUBE_BUILD_PULL_LATEST_IMAGES=n`:
```
k8s.io/kubernetes/build/lib/release.sh:348
DOCKER_BUILD_OPTS[@]: unbound variable
```

**What you expected to happen**:
The sell is excuted normally.

**How to reproduce it (as minimally and precisely as possible)**:

Set `KUBE_BUILD_PULL_LATEST_IMAGES=n ` and run `make quick-release-images`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cblecker** [comment]
/sig release
What version of bash are you using?

**Comment by zhouya0** [comment]
Thanks for your reply.
```
[root@master ~]# echo "${BASH_VERSION}" 
4.2.46(2)-release
```
