### ISSUE TITLE
Should have better information on how to use the rest API to get information, do service config, etc.

### ISSUE THREAD

**Issue by kprobst** [kubernetes/kubernetes#8528]

**Comment by bgrant0607** [comment]
Any more specific details?

**Comment by kprobst** [comment]
@amygdala

**Comment by jeffmendoza** [comment]
We have the api docs, but maybe an example would be appropriate?

**Comment by mikedanese** [comment]
Is it that there is not an example of how to script against the apiserver without kubelet: how to authenticate, how to discover resources, how to discover apiobject structures? These things are easy for people who are comfortable with kubernetes and go but not everyone else. Would an example of how to go through this process using curl resolve this issue?

**Comment by amygdala** [comment]
@kprobst This came from a set of similar user complaints.  Looking again, I think it should probably be dup'd with #8527, then as Brian comments on the other issue, probably factor out into sub-issues. 
@mikedanese - yes, I think that #9753 is basically addressing one of those subtopics then.  We should make sure we include information on how to auth.

**Comment by satnam6502** [comment]
Note that https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/accessing-the-cluster.md does explain how to use curl with a bearer token to make REST queries against the master. Is this enough or should that section be expanded? [I am happy to add more details.]

**Comment by smarterclayton** [comment]
Closing due to age and generally better doc around client-go.  Reopen if this is more specific.
