### ISSUE TITLE
Conformance test "should invoke init containers on a RestartNever pod" doesn't meet conformance requirements

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubernetes#85295]
**What happened**:
Conformance test "should invoke init containers on a RestartNever pod" doesn't meet conformance requirements on conditions and events as stated here https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements

This is following up on https://github.com/kubernetes/kubernetes/pull/75111/files#r330271089 where @timothysc pointed that out.

**What you expected to happen**:
Fix the test so it matches the conformance requirements or remove it from conformance.

/assign @mgdevstack
(https://github.com/kubernetes/kubernetes/pull/66921)

/sig node

@kubernetes/sig-node-bugs

**Comment by mgdevstack** [comment]
I'll be away for two weeks. Post, I can look into it for fix.

**Comment by spiffxp** [comment]
/close
ref: https://github.com/kubernetes/kubernetes/pull/75111/files#r407793964
