### ISSUE TITLE
Support multiple services under one apiservice

### ISSUE THREAD

**Issue by kushalgangan** [kubernetes/kubernetes#85296]
**What would you like to be added:** Currently when we create a new resource of type 'APIService', we can point it to a single service. It would be nice to have the ability to point to multiple services and expose them under a single API.

**Why is this needed:** I am trying to use HPA with external metrics. I am creating an APIService with the name 'v1beta1.external.metrics.k8s.io'. I would like to get data from multiple services so that I can read all that data in a single APIService instead of having multiple APIService(s)

**Comment by alejandrox1** [comment]
wanna look into this
/remove-lifecycle rotten
