### ISSUE TITLE
kubectl create role for podsecuritypolicies fails

### ISSUE THREAD

**Issue by Cynerva** [kubernetes/kubernetes#85314]
**What happened**:

I followed documentation for PodSecurityPolicies from the official docs ([link](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#run-another-pod)). It indicates that you can create a Role granting access to a PodSecurityPolicy by using the `kubectl create role` command. However, the example command fails:

```
$ kubectl create role psp:unprivileged \
  --verb=use \
  --resource=podsecuritypolicy \
  --resource-name=example
error: can not perform 'use' on 'podsecuritypolicies' in group 'policy'
```

**What you expected to happen**:

The example command should successfully create a Role.

**How to reproduce it (as minimally and precisely as possible)**:

Enable PodSecurityPolicy admission plugin.
Try to create a Role that grants the 'use' verb to podsecuritypolicies by using the `kubectl create role` command.

**Anything else we need to know?**:

It works fine if I apply the Role as yaml instead:

```
$ cat test.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:unprivileged
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['example']
$ kubectl apply -f test.yaml
role.rbac.authorization.k8s.io/psp:unprivileged created
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:14:32Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): `4.15.0-1054-aws #56-Ubuntu SMP Thu Nov 7 16:15:59 UTC 2019 x86_64`
- Install tools: Juju
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Cynerva** [comment]
@kubernetes/sig-cli-bugs

**Comment by zhouya0** [comment]
It's because the the group is defined as `extensions`
https://github.com/kubernetes/kubernetes/blob/cb2684c41671f78563f8e92b6c5fafbf45471534/staging/src/k8s.io/kubectl/pkg/cmd/create/create_role.go#L63

/assign

**Comment by Cynerva** [comment]
It looks to me like this was fixed by https://github.com/kubernetes/kubernetes/pull/85406 (thanks!) and can be closed.

**Comment by disconnect3d** [comment]
Since this issue is still valid for some people out there and a workaround might sometimes be helpful, here it is: specify `--resource=podsecuritypolicies.extensions` instead of `--resource=podsecuritypolicy` when creating a role.
