### ISSUE TITLE
Delete deployment with pods

### ISSUE THREAD

**Issue by sarveshkaushal** [kubernetes/kubernetes#85310]
**What happened**: 
Deleting a deployment using cURL doesn't delete pods.

**What you expected to happen**:
Both deployment and pods under it are deleted.
**How to reproduce it (as minimally and precisely as possible)**:
I am running k8 locally using docker for desktop on Macos.
The following curl in my local just deletes the deployment and doesn't terminate pods:
`curl -k -X DELETE -H 'Accept: application/json' 'http://127.0.0.1:8001/apis/apps/v1beta1/namespaces/default/deployments?pretty=true&fieldSelector=metadata.name%3DdeploymentName'`

However following cURL works fine. It deletes the deployment and terminates the pods as well:
`curl -k -X DELETE -H 'Accept: application/json' 'http://127.0.0.1:8001/apis/apps/v1/namespaces/default/deployments?pretty=true&fieldSelector=metadata.name%3DdeploymentName`

Only difference is version v1 and v1beta1
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sarveshkaushal** [comment]
Refer this link: https://github.com/kubernetes-client/java/issues/779

**Comment by boluisa** [comment]
@sarveshkaushal  apps/v1beta1 is a deprecated apiversion in kubernetes 1.16. 
looks like your kubectl client is on version 1.16. 
Note: deployment moved to apiversion apps/v1, probably why that worked.
