### ISSUE TITLE
benchmark inline GC in expiring cache and maybe drop the background goroutine

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#85317]
Let's figure out if this is something we should do ASAP.

**Comment by mikedanese** [comment]
Expiring cache test is flaky it looks like.

**Comment by lavalamp** [comment]
It hadn't occurred to me that we could just remove the goroutine entirely, but I agree it seems very plausible that we can. If requests are so infrequent that GC isn't running often we must also not be adding many entries to the map.
