### ISSUE TITLE
add API to watch pods on Kubelet

### ISSUE THREAD

**Issue by jacksontj** [kubernetes/kubernetes#85315]
**What would you like to be added**:
Today there is a `/pods` endpoint to get the current state/status of pods. Unfortunately if I want to keep track of the current state of pods on a kubelet I have to poll this endpoint. Since the majority of other k8s APIs also have a watch mechanism -- it seems like an oversight that the kubelet API doesn't have the same

**Why is this needed**:
This will allow integrations (e.g. https://github.com/wish/katalog-sync/) to watch for changes on the kubelet instead of polling.

**Comment by jacksontj** [comment]
@kubernetes/sig-node-feature-requests

**Comment by liggitt** [comment]
this is a duplicate of https://github.com/kubernetes/kubernetes/issues/84248

cc @tallclair 
/close

**Comment by jacksontj** [comment]
@liggitt thanks, I'll subscribe to the other issue :)
