### ISSUE TITLE
TestVolumeBinding top flake in pull-kubernetes-integration

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#85320]
**Which jobs are failing**:
pull-kubernetes-integration

**Which test(s) are failing**:
TestVolumeBinding

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&sort-by-flakiness=&width=5

**Reason for failure**:
Unknown

**Anything else we need to know**:

/sig storage scheduling

**Comment by liggitt** [comment]
Failures today:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195072320641699844
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195103275389554688
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195059876619882496
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195060873266204672
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195044271225311233
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195041239775318017
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1195031559418155010
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1194992919614853121

**Comment by liggitt** [comment]
@kubernetes/sig-testing this test is not appearing in [triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-integration&test=TestVolumeBinding) or [flakes-latest.json](http://storage.googleapis.com/k8s-metrics/flakes-latest.json), despite failing dozens of times a week. Are those data sources pulling in test-integration results?

**Comment by BenTheElder** [comment]
they pull junit results

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/1195565237940523010

**Comment by alenkacz** [comment]
we're seeing this one in our release dashboards as well https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Comment by msau42** [comment]
```
I1116 05:15:27.023548  112041 pv_controller.go:856] updating PersistentVolume[pv-w-pvc-prebound]: binding to "volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound" failed: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again
I1116 05:15:27.023578  112041 pv_controller.go:938] error binding volume "pv-w-pvc-prebound" to claim "volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound": failed saving the volume: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again

I1116 05:15:27.024141  112041 scheduling_queue.go:841] About to try and schedule pod volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pod-w-pvc-prebound
E1116 05:15:27.024510  112041 framework.go:411] error while running "VolumeBinding" filter plugin for pod "pod-w-pvc-prebound": pod has unbound immediate PersistentVolumeClaims
E1116 05:15:27.024556  112041 factory.go:469] Error scheduling volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pod-w-pvc-prebound: error while running "VolumeBinding" filter plugin for pod "pod-w-pvc-prebound": pod has unbound immediate PersistentVolumeClaims; retrying

I1116 05:15:41.825846  112041 pv_controller_base.go:431] resyncing PV controller
I1116 05:15:41.828765  112041 pv_controller.go:866] updating PersistentVolume[pv-w-pvc-prebound]: bound to "volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound"
I1116 05:15:41.828776  112041 pv_controller.go:781] updating PersistentVolume[pv-w-pvc-prebound]: set phase Bound
I1116 05:15:41.828807  112041 pv_controller_base.go:542] storeObjectUpdate updating volume "pv-w-pvc-prebound" with version 32116
I1116 05:15:41.828838  112041 pv_controller.go:493] synchronizing PersistentVolume[pv-w-pvc-prebound]: phase: Available, bound to: "volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound (uid: d3381ec0-71bd-464b-b2a4-3e9680cce206)", boundByController: true
I1116 05:15:41.828848  112041 pv_controller.go:518] synchronizing PersistentVolume[pv-w-pvc-prebound]: volume is bound to claim volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound
I1116 05:15:41.828861  112041 pv_controller.go:559] synchronizing PersistentVolume[pv-w-pvc-prebound]: claim volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound found: phase: Pending, bound to: "pv-w-pvc-prebound", bindCompleted: false, boundByController: false

I1116 05:15:41.828882  112041 scheduler.go:605] Attempting to schedule pod: volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pod-w-pvc-prebound
E1116 05:15:41.829049  112041 framework.go:411] error while running "VolumeBinding" filter plugin for pod "pod-w-pvc-prebound": pod has unbound immediate PersistentVolumeClaims
E1116 05:15:41.829112  112041 factory.go:469] Error scheduling volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pod-w-pvc-prebound: error while running "VolumeBinding" filter plugin for pod "pod-w-pvc-prebound": pod has unbound immediate PersistentVolumeClaims; retrying

I1116 05:15:41.833067  112041 pv_controller.go:794] updating PersistentVolume[pv-w-pvc-prebound]: set phase Bound failed: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again
I1116 05:15:41.833088  112041 pv_controller.go:944] error binding volume "pv-w-pvc-prebound" to claim "volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound": failed saving the volume status: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again
I1116 05:15:41.833104  112041 pv_controller_base.go:256] could not sync claim "volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pvc-w-prebound": Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again

I1116 05:15:57.049865  112041 scheduler.go:601] Skip schedule deleting pod: volume-scheduling-685b76ba-7a1b-4150-8cc1-a2638161498f/pod-w-pvc-prebound
```

Looks like there are issues with syncing object updates between PV controller and scheduler, and I suspect that the two are racing on updates to the PVC object (scheduler trying to update selectedNode annotation, and PV controller trying to update PVC bound state).

**Comment by cofyc** [comment]
https://github.com/kubernetes/kubernetes/blob/81af5baff8e958dc8817913ec3c4172028f30122/test/integration/volumescheduling/volume_binding_test.go#L141-L145
in this case, the PVC is prebound which is `unbound immediate PersistentVolumeClaims`, the scheduler shouldn't set `selectedNode` annotation.

**Comment by alenkacz** [comment]
@liggitt I see this test as green in the last few days, possibly the merged patches helped? Could you confirm, please?

**Comment by liggitt** [comment]
> @liggitt I see this test as green in the last few days, possibly the merged patches helped? Could you confirm, please?

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&sort-by-flakiness=&width=5 still shows it failing very frequently… which fixes related to this merged?

**Comment by msau42** [comment]
No fixes have gone in afaik. I was out most of last week, but will focus on triaging this week

**Comment by msau42** [comment]
I actually had this integration test running in a loop all week without any failures. I just started rerunning them with "-race" on, still no failures after 250 runs.  I notice that this job is running integration tests in parallel, will investigate if other tests may be creating resources with the same names and potentially causing name conflicts.

**Comment by msau42** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/85602/pull-kubernetes-integration/1198942447145586689/build-log.txt

Ok I think the issue is that PV controller is racing within itself. There's a workqueue to handle PVs, and a workqueue to handle PVCs.  However, in the case of prebinding PVCs, the PVC workqueue is [trying to update the PV object](https://github.com/kubernetes/kubernetes/blob/7907c63fad1ccb7905d2d27c643387046ab0f4ad/pkg/controller/volume/persistentvolume/pv_controller.go#L384) and that is racing with the PV workqueue also trying to update the PV object.

Sequence of events:

1. When pv is created, the first step is to make it available by updating the status. This is done by pv workqueue:
```
I1125 12:56:08.005996  112027 pv_controller_base.go:514] storeObjectUpdate: adding volume "pv-w-pvc-prebound", version 33725
I1125 12:56:08.006025  112027 pv_controller.go:493] synchronizing PersistentVolume[pv-w-pvc-prebound]: phase: Pending, bound to: "", boundByController: false
I1125 12:56:08.006040  112027 pv_controller.go:498] synchronizing PersistentVolume[pv-w-pvc-prebound]: volume is unused
I1125 12:56:08.006046  112027 pv_controller.go:781] updating PersistentVolume[pv-w-pvc-prebound]: set phase Available
```

2. Now PVC workqueue is processing the prebound PVC and also trying to update PV
```
I1125 12:56:08.007835  112027 pv_controller_base.go:514] storeObjectUpdate: adding claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound", version 33726
I1125 12:56:08.007864  112027 pv_controller.go:245] synchronizing PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: phase: Pending, bound to: "pv-w-pvc-prebound", bindCompleted: false, boundByController: false
I1125 12:56:08.007879  112027 pv_controller.go:351] synchronizing unbound PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: volume "pv-w-pvc-prebound" requested
I1125 12:56:08.007898  112027 pv_controller.go:370] synchronizing unbound PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: volume "pv-w-pvc-prebound" requested and found: phase: Pending, bound to: "", boundByController: false
I1125 12:56:08.007916  112027 pv_controller.go:374] synchronizing unbound PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: volume is unbound, binding
I1125 12:56:08.007932  112027 pv_controller.go:935] binding volume "pv-w-pvc-prebound" to claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound"
I1125 12:56:08.007943  112027 pv_controller.go:833] updating PersistentVolume[pv-w-pvc-prebound]: binding to "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound"
I1125 12:56:08.007965  112027 pv_controller.go:853] claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound" bound to volume "pv-w-pvc-prebound"
```

3. API update for 1) goes through
```
I1125 12:56:08.008763  112027 httplog.go:90] PUT /api/v1/persistentvolumes/pv-w-pvc-prebound/status: (2.5514ms) 200 [volumescheduling.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:47672]
```

4. API update from 2) fails due to conflict:
```
I1125 12:56:08.011220  112027 httplog.go:90] PUT /api/v1/persistentvolumes/pv-w-pvc-prebound: (2.723264ms) 409 [volumescheduling.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:49736]
I1125 12:56:08.011411  112027 pv_controller.go:856] updating PersistentVolume[pv-w-pvc-prebound]: binding to "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound" failed: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again
```
The main way I see to fix this is to actually separate PV and PVC updates into the proper workqueues, but it sounds like a risky fundamental change. Another alternative is to make the test less flaky by increasing the timeout, or increasing the frequency of retries to reduce the risk of racing.

@jsafrane wdyt?

**Comment by msau42** [comment]
Another question is why did updating the PV object fail the 2nd time because now PV workqueue shouldn't be trying to update status to Available. I will continue investigating tomorrow

**Comment by liggitt** [comment]
if the PVC queue fails updating the PV, I'd expect it to requeue the PVC for processing

**Comment by msau42** [comment]
> if the PVC queue fails updating the PV, I'd expect it to requeue the PVC for processing

It does (after 10 second resync period) , but it also races the second time. And then the test times out before it can retry a 3rd

**Comment by liggitt** [comment]
> It does (after 10 second resync period) , but it also races the second time

what is updating the PV multiple times in a row?

**Comment by liggitt** [comment]
> Another question is why did updating the PV object fail the 2nd time because now PV workqueue shouldn't be trying to update status to Available.

I see you asked the same question :)

**Comment by msau42** [comment]
Sequence of events for 2nd conflicting API update:

1. PV workqueue did not do anything since phase is already set to Available:
```
I1125 12:56:22.884895  112027 pv_controller_base.go:431] resyncing PV controller
I1125 12:56:22.884996  112027 pv_controller_base.go:542] storeObjectUpdate updating volume "pv-w-pvc-prebound" with version 33727
I1125 12:56:22.885037  112027 pv_controller.go:493] synchronizing PersistentVolume[pv-w-pvc-prebound]: phase: Available, bound to: "", boundByController: false
I1125 12:56:22.885060  112027 pv_controller.go:498] synchronizing PersistentVolume[pv-w-pvc-prebound]: volume is unused
I1125 12:56:22.885071  112027 pv_controller.go:781] updating PersistentVolume[pv-w-pvc-prebound]: set phase Available
I1125 12:56:22.885080  112027 pv_controller.go:784] updating PersistentVolume[pv-w-pvc-prebound]: phase Available already set
```

2. PVC workqueue tries to update PV again and it succeeds this time:
```
I1125 12:56:22.885104  112027 pv_controller_base.go:542] storeObjectUpdate updating claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound" with version 33726
I1125 12:56:22.885125  112027 pv_controller.go:245] synchronizing PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: phase: Pending, bound to: "pv-w-pvc-prebound", bindCompleted: false, boundByController: false
I1125 12:56:22.885141  112027 pv_controller.go:351] synchronizing unbound PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: volume "pv-w-pvc-prebound" requested
I1125 12:56:22.885160  112027 pv_controller.go:370] synchronizing unbound PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: volume "pv-w-pvc-prebound" requested and found: phase: Available, bound to: "", boundByController: false
I1125 12:56:22.885180  112027 pv_controller.go:374] synchronizing unbound PersistentVolumeClaim[volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound]: volume is unbound, binding
I1125 12:56:22.885200  112027 pv_controller.go:935] binding volume "pv-w-pvc-prebound" to claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound"
I1125 12:56:22.885210  112027 pv_controller.go:833] updating PersistentVolume[pv-w-pvc-prebound]: binding to "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound"
I1125 12:56:22.885293  112027 pv_controller.go:853] claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound" bound to volume "pv-w-pvc-prebound"
I1125 12:56:22.887802  112027 httplog.go:90] PUT /api/v1/persistentvolumes/pv-w-pvc-prebound: (2.112937ms) 200 [volumescheduling.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:47672]
```

3. After updating PV with the claim, PVC workqueue tries to update the status
```
I1125 12:56:22.888047  112027 pv_controller_base.go:542] storeObjectUpdate updating volume "pv-w-pvc-prebound" with version 36795
I1125 12:56:22.888072  112027 pv_controller.go:866] updating PersistentVolume[pv-w-pvc-prebound]: bound to "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound"
I1125 12:56:22.888083  112027 pv_controller.go:781] updating PersistentVolume[pv-w-pvc-prebound]: set phase Bound
```

4. PV workqueue starts processing PV too
```
I1125 12:56:22.888121  112027 pv_controller_base.go:542] storeObjectUpdate updating volume "pv-w-pvc-prebound" with version 36795
I1125 12:56:22.888150  112027 pv_controller.go:493] synchronizing PersistentVolume[pv-w-pvc-prebound]: phase: Available, bound to: "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound (uid: 24fce4b5-77e0-4d5a-80fd-e22664a6353d)", boundByController: true
I1125 12:56:22.888166  112027 pv_controller.go:518] synchronizing PersistentVolume[pv-w-pvc-prebound]: volume is bound to claim volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound
I1125 12:56:22.888183  112027 pv_controller.go:559] synchronizing PersistentVolume[pv-w-pvc-prebound]: claim volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound found: phase: Pending, bound to: "pv-w-pvc-prebound", bindCompleted: false, boundByController: false
I1125 12:56:22.888196  112027 pv_controller.go:623] synchronizing PersistentVolume[pv-w-pvc-prebound]: all is bound
I1125 12:56:22.888203  112027 pv_controller.go:781] updating PersistentVolume[pv-w-pvc-prebound]: set phase Bound
```

5. One of them succeeds (probably the PV workqueue) and the other fails
```
I1125 12:56:22.891432  112027 httplog.go:90] PUT /api/v1/persistentvolumes/pv-w-pvc-prebound/status: (3.148263ms) 409 [volumescheduling.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:47672]
I1125 12:56:22.891662  112027 pv_controller.go:794] updating PersistentVolume[pv-w-pvc-prebound]: set phase Bound failed: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again
I1125 12:56:22.891680  112027 pv_controller.go:944] error binding volume "pv-w-pvc-prebound" to claim "volume-scheduling-5c58f9f4-61fd-48f8-afa4-5a2625bb8a2e/pvc-w-prebound": failed saving the volume status: Operation cannot be fulfilled on persistentvolumes "pv-w-pvc-prebound": the object has been modified; please apply your changes to the latest version and try again

I1125 12:56:22.891690  112027 httplog.go:90] PUT /api/v1/persistentvolumes/pv-w-pvc-prebound/status: (3.320753ms) 200 [volumescheduling.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:49736]

```

**Comment by msau42** [comment]
So the fundamental issue is that PVC workqueue calls `bind()`, which tries to make [two updates to the PV object](https://github.com/kubernetes/kubernetes/blob/7907c63fad1ccb7905d2d27c643387046ab0f4ad/pkg/controller/volume/persistentvolume/pv_controller.go#L937), and those two updates can conflict with PV workqueue [here](https://github.com/kubernetes/kubernetes/blob/7907c63fad1ccb7905d2d27c643387046ab0f4ad/pkg/controller/volume/persistentvolume/pv_controller.go#L499) and [here](https://github.com/kubernetes/kubernetes/blob/7907c63fad1ccb7905d2d27c643387046ab0f4ad/pkg/controller/volume/persistentvolume/pv_controller.go#L624)

The first race could potentially be addressed by having PVC workqueue wait for PV to be in available phase before operating on it. The [comment here](https://github.com/kubernetes/kubernetes/blob/7907c63fad1ccb7905d2d27c643387046ab0f4ad/pkg/controller/volume/persistentvolume/pv_controller.go#L373) seems to suggest that is the intention, but there are actually no checks to validate the pv phase.

The 2nd race could potentially be addressed by not trying to update the pv phase in PV workqueue and instead only let the PVC workqueue handle it, but I'm not sure what corner cases we may miss.

For now, my inclination is to make the PV controller retry more to resolve the immediate flakiness. There's only two API updates that can conflict, so a 3rd retry has to succeed :-) 

Longer term, I think adding a check for Available phase should be simple, although we currently don't check for phases anywhere. Removing the handling for the 2nd race has bigger risk in terms of causing a regression in some corner cases.  @jsafrane would appreciate your thoughts here

**Comment by tedyu** [comment]
To address the first race, I am thinking about the following (duration of the wait is up for discussion):
```
diff --git a/pkg/controller/volume/persistentvolume/pv_controller.go b/pkg/controller/volume/persistentvolume/pv_controller.go
index 1a5cfc2284..ccd8b7fc18 100644
--- a/pkg/controller/volume/persistentvolume/pv_controller.go
+++ b/pkg/controller/volume/persistentvolume/pv_controller.go
@@ -381,10 +381,25 @@ func (ctrl *PersistentVolumeController) syncUnboundClaim(claim *v1.PersistentVol
                                        if _, err = ctrl.updateClaimStatus(claim, v1.ClaimPending, nil); err != nil {
                                                return err
                                        }
-                               } else if err = ctrl.bind(volume, claim); err != nil {
-                                       // On any error saving the volume or the claim, subsequent
-                                       // syncClaim will finish the binding.
-                                       return err
+                               } else {
+                                       var vol *v1.PersistentVolume
+                                       var cnt int
+                                       for cnt = 0; cnt < 10; cnt++ {
+                                               if vol, err = ctrl.kubeClient.CoreV1().PersistentVolumes().Get(volume.Name, metav1.GetOptions{}); err != nil {
+                                                       return err;
+                                               }
+                                               if vol.Status.Phase != v1.VolumeAvailable {
+                                                       time.Sleep(time.Duration(10) * time.Second)
+                                               }
+                                       }
+                                       if cnt == 10 {
+                                               return fmt.Errorf("timed out waiting for %s to be available", volume.Name)
+                                       }
+                                       if err = ctrl.bind(volume, claim); err != nil {
+                                               // On any error saving the volume or the claim, subsequent
+                                               // syncClaim will finish the binding.
+                                               return err
+                                       }
                                }
                                // OBSERVATION: pvc is "Bound", pv is "Bound"
                                return nil
```

**Comment by liggitt** [comment]
> To address the first race, I am thinking about the following (duration of the wait is up for discussion)

we don't want to sleep inside a controller sync loop on one object... it blocks other objects that worker needs to process

**Comment by jsafrane** [comment]
> The first race could potentially be addressed by having PVC workqueue wait for PV to be in available phase before operating on it. 

The controller should not read PV/PVC.status, it reads only .spec. I don't think we should break this behavior.

I think it could be possible not to update PV.status in PVC workqueue and let the PV workqueue to own it exclusively.

**Comment by msau42** [comment]
The first race is actually PVC workqueue trying to update PV.spec.claimref  that raced against PV workqueue updating status

**Comment by jsafrane** [comment]
Is it a real issue though? The system works, it just needs one extra sync. It's only for pre-provisioned PVs whose PVCs are created at the same time.

**Comment by liggitt** [comment]
timing and available fix cleaned up failures (none since the fix merged), see https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&sort-by-flakiness=&width=5&include-filter-by-regex=TestVolumeBinding$

**Comment by msau42** [comment]
Let's continue discussion if we want to improve PV controller in https://github.com/kubernetes/kubernetes/issues/85659

/close
