### ISSUE TITLE
kubelet may use stale node info to predicate pods

### ISSUE THREAD

**Issue by keyingliu** [kubernetes/kubernetes#85334]
**What happened**:
kubelet may use stale node info to predicate pods

**What you expected to happen**:
pod should not be rejected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
If new labels are labeled in a node, and pods use nodeSelector,
kubelet may reject the pods at kubelet restarting because node
cache is not populated and kubelet still uses stale node info
which has no new labels.

This is the error from reflector of node ListWatch in a goroutine, triggered at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L457:
```
Nov 05 12:44:34 kubelet[14390]: E1105 12:44:34.893917 14390 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:452: Failed to list *v1.Node: Stream error http2.StreamError{StreamID:0x9, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
```
This is the error when predicating pods, it called here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_getters.go#L240, and if node cache is not ready, it calls initialNode instead, which has no latest node info:
```
Nov 05 12:44:34 kubelet[14390]: I1105 12:44:34.919779 14390 predicate.go:133] Predicate failed on Pod: xxx(a1bfbee0-5d58-11e9-adbb-ac1f6b0b668c), for reason: Predicate MatchNodeSelector failed
```
There is race condition between them.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): 4.15
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by keyingliu** [comment]
@danielqsj

**Comment by zouyee** [comment]
https://github.com/kubernetes/kubernetes/pull/80976
