### ISSUE TITLE
kubectl edit deploy fails with error: map: map[] does not contain declared merge key: name

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#85332]
**What happened**:

I am trying to use `kubectl edit deploy` to change the args of a container. It fails with 

```
A copy of your changes has been stored to "/tmp/kubectl-edit-3jt2v.yaml"
error: map: map[] does not contain declared merge key: name
```

**What you expected to happen**:

I expected kubectl edit to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

https://gist.github.com/tamalsaha/cbaab32c1048040911d82d8cef098e60

You deployment yaml is original.yaml
Then I use kubectl edit to change the args `--v=3` -> `--v=10`. It fails.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

I am using kind. I use `kind create cluster` to create the cluster.

$ kubectl version --short
Client Version: v1.15.0
Server Version: v1.15.3

**Comment by tedyu** [comment]
```
"imagePullSecrets":[{"name":""}]
```

**Comment by tamalsaha** [comment]
Good catch. Thanks @tedyu !

I wonder if there is a way to give better error message. May be the error message can include the json path to the key that it found invalid.
