### ISSUE TITLE
Logs emitted with asm_amd64.s as filename

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#85347]
**What happened**:

Running hyperkube's API server with `-v5` I notice that some but not all logs get emitted with filename `asm_amd64.s`

Example:
```
I1115 14:20:10.327931       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{172.17.0.2:2379 <nil>}]
```

**What you expected to happen**:

Sensible filename with `.go` in it

**How to reproduce it (as minimally and precisely as possible)**:

Run API server with `-v5`, grep log for asm_amd64.s.

**Anything else we need to know?**:

We had a similar problem in our product, it turned out to be that the log library was skipping too many stack frames when walking the stack to find the correct frame.  asm_amd64.s is the end of the stack.  This was caused by more powerful function inlining optimisations introduced in go 1.12, IIRC.  The fix was to skip fewer frames when looking for the correct stack frame.

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.14.9
- Cloud provider or hardware configuration: hyperkube running in a docker container
- OS (e.g: `cat /etc/os-release`): Ubuntu 19.04
- Kernel (e.g. `uname -a`): 5.1.16-050116-generic
- Install tools: hyperkube
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dims** [comment]
@fasaxc `The fix` <<< is there a PR open?

**Comment by tedyu** [comment]
```
The fix was to skip fewer frames when looking for the correct stack frame
```
Would this work for multiple go versions ?
Or maybe you suggest the skipping based on go version.

**Comment by dims** [comment]
@tedyu looks like this would be in klog https://github.com/kubernetes/klog/blob/master/klog.go#L585-L600

**Comment by fasaxc** [comment]
This was the fix we made over in Calico: https://github.com/projectcalico/libcalico-go/commit/1f1ababe294be198148c4232ef6c0344898d3b31#diff-ac7ff9aaa24815e5b2b4c4de2cb1debcR154
