### ISSUE TITLE
Mutation detection is no longer enabled in e2e tests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#85349]
**What happened**:
A concurrent read/write panic was found in https://github.com/kubernetes/kubernetes/issues/85331, caused by a controller modifying an object from a shared informer.

This condition was not caught by e2e tests.

A setup bug was introduced in https://github.com/kubernetes/kubernetes/commit/37b5a214bc0dc465514c3e6b232246e39788ae63 on Jul 4, 2017 which kept the mutation detection enablement from being effective

Enablement from test-infra was disabled in 
https://github.com/kubernetes/test-infra/commit/d9c42cdf593893b547615f370482d5893568bbd7 on on Aug 29, 2018

The setup bug was then fixed in https://github.com/kubernetes/kubernetes/commit/3fdb5b92f48157987d484cb1d3b78bf41ee267e2 on Oct 9, 2018

**What you expected to happen**:
At least one release-blocking e2e job must run with mutation detection enabled on all components (envvar KUBE_CACHE_MUTATION_DETECTOR=true) to catch this. Ideally, this would be a presubmit to prevent introduction of these bugs.

**How to reproduce it (as minimally and precisely as possible)**:
Looking at the log files for the e2e job, the API server / controller manager / scheduler / kubelet do not have mutation detection enabled (no "Mutation detector is enabled" message appears in their logs).

/milestone v1.17
/priority critical-urgent
/sig testing

**Comment by liggitt** [comment]
cc @deads2k @robscott @kubernetes/sig-testing

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/85350 to enable it in test-cmd/test-integration. Need test-infra assistance understanding how to thread it into our e2e run

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/test-infra/pull/15298 to re-enable in alpha e2e jobs first

**Comment by dims** [comment]
@liggitt both PRs above have merged, do we need to do anything more?

**Comment by kikisdeliveryservice** [comment]
@liggitt 

Bug Triage team here:  Is this issue ready to be closed?

**Comment by liggitt** [comment]
> @liggitt both PRs above have merged, do we need to do anything more?

we still don't have this enabled in blocking jobs, this PR is still needed

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/85350 is merged and picked, mutation detection is re-enabled in e2e in https://github.com/kubernetes/test-infra/pull/15447
