### ISSUE TITLE
Azure Files PV AuthorizationFailure when using advanced networking 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#85354]
**What would you like to be added**:
currently this create file share action is also considered as data-path operation that's the reason why it failed since create file share action happens on master node which is not in selected network, in the future, this action will not be handled as data-path operation. 

as confirmed by azure file team, api-version `2019-06-01` supports this functionality, need to upgrade the api-version:

https://github.com/kubernetes/kubernetes/blob/4c50ee993c82c6852eb3b3aa8dfa8ecc4bcfe330/staging/src/k8s.io/legacy-cloud-providers/azure/azure_storage.go#L24

**Why is this needed**:

/assign
/kind bug
/priority important-soon
/sig cloud-provider
/area provider/azure

**Comment by andyzhangx** [comment]
related issue: https://github.com/Azure/AKS/issues/804

**Comment by aramase** [comment]
@andyzhangx Are you already working on this? If not, I was wondering if I can pick it up.

**Comment by andyzhangx** [comment]
@aramase yes, it's half done already. actually the code change is already in my dev machine, let it send it out.

**Comment by aramase** [comment]
@andyzhangx ok, sounds good!

**Comment by andyzhangx** [comment]
/reopen
since it's not fixed
