### ISSUE TITLE
apiserver drops watch connection

### ISSUE THREAD

**Issue by NoAnyLove** [kubernetes/kubernetes#85366]
**What happened**:
We use aiohttp `ws_connect` to establish WebSocket connection to watch pods, the endpoint is `https://{host}:6443/api/v1/namespaces/{namespace}/pods?watch=True`.

It works perfectly with kubernetes `v1.14.6`, but the Websocket connect will be closed in 30 to 60 minutes with Kubernetes `v1.15.5`.

We also tried different versions of Kubernetes on different boxes, including `v1.15.3`, `v1.16.2`, and also tried HTTP GET request. The watch WebSocket/HTTP connections always close after 30 to 60 minutes in `v1.15.x` and `v1.16.x`.

**What you expected to happen**:
The WebSocket connection should be stable and do not disconnect.

**How to reproduce it (as minimally and precisely as possible)**:
The following Python script is tested with Python `3.6.8` and aiohttp `3.5.4`. Run the script below with Kubernetes v1.15.x or v1.16.x (or probably use [kind](https://kind.sigs.k8s.io/)), the connection should be closed within 30 to 60 minutes.

```python
import asyncio
import logging

import aiohttp

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s.%(msecs)03d|%(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)


API_SERVER = "https://localhost:6443"
TOKEN = "..."
NAMESPACE = "..."


async def main():
    headers = {"Accept": "application/json", "Content-Type": "application/json", "authorization": f"Bearer {TOKEN}"}
    async with aiohttp.ClientSession(headers=headers) as session:
        async with session.ws_connect(
            url=f"{API_SERVER}/api/v1/namespaces/{NAMESPACE}/pods?watch=True",
            origin=API_SERVER,
            verify_ssl=False,
            heartbeat=30,
        ) as ws:
            while True:
                msg = await ws.receive()
                logger.info(msg)
                if msg.type in (aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.CLOSING, aiohttp.WSMsgType.CLOSED):
                    break
            logger.error("WS connection disconnected")


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

**Anything else we need to know?**:
It seems to be related to https://github.com/rancher/rancher/issues/23957, but we could not find those error messages in our logs, no mater we use WebSocket or HTTP GET.

**Environment**:
- Kubernetes version (use `kubectl version`):
For `v1.14.6`,
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
For `v1.15.5`,
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): `4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Watch connections are not expected to remain open indefinitely. Clients are expected to reestablish watches at the last observed resourceVersion when the connection drops.

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/server/config.go#L156-158

https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/server/config.go#L173

The default minimum timeout is 30-60 minutes.

/close

**Comment by NoAnyLove** [comment]
Since the long connection works perfectly in `v1.14.x`, but behave quite differently since `v1.15.x`, (mostly likely a breaking change?). It would be nice to see it in changelog.

**Comment by liggitt** [comment]
The same configuration and intended behavior has existed for many releases. If the connection did not drop after the configured timeout in 1.14.x it was an unintentional bug.

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/blob/release-1.14/staging/src/k8s.io/apiserver/pkg/server/config.go#L157 for the same configured behavior in 1.14, for example

**Comment by NoAnyLove** [comment]
I see. Thanks.
