### ISSUE TITLE
medium: Memory can't go above half of node physical memory

### ISSUE THREAD

**Issue by hymgg** [kubernetes/kubernetes#85360]
**What happened**:

Node has 187G physical memory

# free -g
              total        used        free      shared  buff/cache   available
Mem:            187           5         162           4          19         175
Swap:             0           0           0

Need to create a pod with 128G shared memory, set sizeLimit to 128Gi

      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "128Gi"

        volumeMounts:
        - mountPath: /dev/shm
          name: dshm

Pod created with only 94G shared memory, half of node's physical

# df -h|grep /dev/shm
tmpfs                                    94G   94G  120K 100% /dev/shm

**What you expected to happen**:

Pod get 128Gi shared memory

**How to reproduce it (as minimally and precisely as possible)**:

Please add above volume setting to any pod, set sizeLimit > 1/2 node physical, < total node physical

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

K8s with on-premise Bare Metal nodes.

- OS (e.g: `cat /etc/os-release`):

$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

- Kernel (e.g. `uname -a`):

$ uname -a
Linux mtx-huawei2-bld08 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dims** [comment]
@hymgg here's what you are running into https://github.com/kubernetes/kubernetes/pull/63641

**Comment by hymgg** [comment]
@dims Thank you. Looked at that issue earlier, not exactly sure what the decision was there. So opened this one. As long as /dev/shm size will honor some input value we're good.

-Jessica
