### ISSUE TITLE
Cpu resource limit does not work properly on windows

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/kubernetes#85379]
**What happened**:

When I was using a hybrid cluster with windows, I found some problems with deployment usage.
I deployed an app and limit the cpu and memory useage,the yaml such as :

![image](https://user-images.githubusercontent.com/7907809/68991325-89e8ad80-0898-11ea-8bcf-b32f7156844f.png)

But I found that the cpu limit didn't work，i test a script in this pod for test the cpu pressure, the script is :

```
foreach ($loopnumber in 1..4){
    Start-Job -ScriptBlock{
    $result = 1
	foreach($mm in 1..2147483647){$res1=1;foreach($num in 1..2147483647){$res1=$mm*$num*1340371};$res1}
    }
}
```
And the results is that 
![image](https://user-images.githubusercontent.com/7907809/68991386-4773a080-0899-11ea-81d5-c72cb2c59278.png)

We can find that the cpu limit is not working, at the same time ,  inspect the container and the result is that :

![image](https://user-images.githubusercontent.com/7907809/68991439-e4363e00-0899-11ea-9a3d-94d111308222.png)

By read the doc https://github.com/kubernetes/community/blob/b3349d5b13/contributors/design-proposals/node/cri-windows.md . 
On Windows Server containers, the processor resource controls are mutually exclusive, the order of precedence is CPUCount first, then CPUShares, and CPUPercent last.

**What you expected to happen**:

Cpu limit works fine

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): both 1.15 and 1.16
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): windows server 2019 ltsc   4c8g
- docker: docker ee 19.03  
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel host-gw
- Others: windows container process mode

/sig windows

**Comment by wawa0210** [comment]
/assign @wawa0210 

I think i found the problem and will fix it

**Comment by PatrickLang** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/86101
/close
