### ISSUE TITLE
Long running pods turn into "unhealthy", find pod condition "ContainersReady" is true but "Ready" is false

### ISSUE THREAD

**Issue by gbjuno** [kubernetes/kubernetes#85389]
**What happened**:
Two long running pods change to "not ready" status after running about 90 days.
After investigation, we find the field "ContainersReady" in pod status.condition is true, however the field "Ready" status is false, which means that the pod is not ready.  Containers in pod don't have any readiness or liveness configuration.
We don't know how to reproduce it, but we find it happend in severval clusters with same configurations. 
After delete the unhealthy pod, we find the newly created pods are healthy, both the ContainersReady and the Ready field are true.

**What you expected to happen**:
pods should be healthy if all container in pods are ready.(we don't use any ReadinessGate feature：
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate）

**How to reproduce it (as minimally and precisely as possible)**:
cannot reproduce it.  I have 2 clusters with the same deployment configurations stuck into this situation.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04 
- Kernel (e.g. `uname -a`):
- Install tools: Linux 10-68-38-176 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Network plugin and version (if this is a network-related bug): calico 3.3.1
- Others: 
show pod status
```
root@ubuntu:/var/log/upstart# kubectl get pods --namespace system
NAME                   READY   STATUS    RESTARTS   AGE
rcmonitorng100-xcvpt   1/1     Running   0          73d
rcstatehub100-zhcx6    1/1     Running   0          73d

root@ubuntu:/var/log/upstart# kubectl get pods rcstatehub100-zhcx6 --namespace system -o yaml
....... 
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-04T12:26:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "**2019-09-07T01:11:47Z**"
    status: "**False**"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-04T12:26:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-04T12:26:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://12adbfa6e6930a27d74dff8c78176f026d07fa2089bd4ac87bb05b0c22a24672
    image: eagle/statehub:latest
    imageID: docker-pullable://eagle/statehub@sha256:423d633584e5a6c9a8a1ce1d0c137a7c3a145f8140ce9655041eec559671a939
    lastState: {}
    name: statehub-hk2-system-statehub-1-0-0
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-04T12:26:26Z"
  hostIP: 10.68.38.177
  phase: Running
  podIP: 10.173.166.152
  qosClass: BestEffort
  startTime: "2019-09-04T12:26:23Z"

root@ubuntu:/var/log/upstart# kubectl get pods rcmonitorng100-xcvpt --namespace system -o yaml
....
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-04T12:26:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "**2019-09-07T01:11:47Z**"
    status: "**False**"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-04T12:26:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-04T12:26:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0cb1bbb1712efd0809d56b697abbf08ba0ea4ea052094458cf0b15a15ccb4512
    image: eagle/monitor:latest
    imageID: docker-pullable://eagle/monitor@sha256:971de03111faefc6dc5994bb6d1f1c678a3d212fac3bd9ec1d02d3042c1f1a64
    lastState: {}
    name: monitorng-hk2-system-monitorng-1-0-0
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-04T12:26:25Z"
  hostIP: 10.68.38.180
  phase: Running
  podIP: 10.173.198.92
  qosClass: BestEffort
  startTime: "2019-09-04T12:26:23Z"
```

endpoint show
```
root@10-68-38-176:/var/log/upstart# kubectl get endpoints --namespace system
NAME              ENDPOINTS             AGE
srvmonitorng100                         73d
srvstatehub100                          73d

root@ubuntu:/var/log/upstart# kubectl get endpoints srvstatehub100 --namespace system -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2019-09-07T09:11:47+08:00"
  creationTimestamp: "2019-09-04T12:26:23Z"
  labels:
    clustertag: hk2
    servicename: statehub
    servicenamespace: system
    servicetype: internal
    serviceversion: 1.0.0
    srv_name: srvstatehub100
  name: srvstatehub100
  namespace: system
  resourceVersion: "1707182"
  selfLink: /api/v1/namespaces/system/endpoints/srvstatehub100
  uid: 749ddade-d6c4-463f-9ec3-d556e0b660d6
subsets:
- notReadyAddresses:
  - ip: 10.173.166.152
    nodeName: 10.68.38.177
    targetRef:
      kind: Pod
      name: rcstatehub100-zhcx6
      namespace: system
      resourceVersion: "1707181"
      uid: f57268ad-b3f2-48f7-9098-b30af2144e0f
  ports:
  - name: port1
    port: 8080
    protocol: TCP

root@ubuntu:/var/log/upstart# kubectl get endpoints srvmonitorng100 --namespace system -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2019-09-07T09:11:47+08:00"
  creationTimestamp: "2019-09-04T12:26:23Z"
  labels:
    clustertag: hk2
    servicename: monitorng
    servicenamespace: system
    servicetype: internal
    serviceversion: 1.0.0
    srv_name: srvmonitorng100
  name: srvmonitorng100
  namespace: system
  resourceVersion: "1707201"
  selfLink: /api/v1/namespaces/system/endpoints/srvmonitorng100
  uid: ca99fa78-fc8e-4679-948c-899f63c028f7
subsets:
- notReadyAddresses:
  - ip: 10.173.198.92
    nodeName: 10.68.38.180
    targetRef:
      kind: Pod
      name: rcmonitorng100-xcvpt
      namespace: system
      resourceVersion: "1707200"
      uid: 19344732-962d-459a-bf85-22c836687147
  ports:
  - name: port1
    port: 8888
    protocol: TCP
```

**Comment by gbjuno** [comment]
now 2 clusters with the same configuration get into this situation.

**Comment by niharkawli** [comment]
Saw same issue in our cluster as well today. 
```
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-11-26T13:16:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-11-27T02:54:28Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-11-26T13:16:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-11-26T13:16:15Z"
    status: "True"
    type: PodScheduled
```

```
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   True 
  PodScheduled      True 
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gaorong** [comment]
what's the status of the node which this pod belongs to? 

 You may find some valuable information from controller-manager and kubelet's log.

**Comment by gbjuno** [comment]
cannot find any useful log of controller-manager and kubelet.
we add some debug code segement and wait for it happens again so that we can find out something.

**Comment by andysnowden** [comment]
Looks like #83455 might be a fix for this? Needs to be back ported.

**Comment by jasonchester** [comment]
seeing this issue where endpoints are not picking up running pods.

❯ kubectl version
```sh
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
❯ kubectl get endpoints api-gateway-ui-konga -o yaml
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2020-04-21T08:22:54Z"
  creationTimestamp: "2020-03-21T02:50:33Z"
  labels:
    app: konga
    chart: konga-0.1.0
    heritage: Tiller
    release: api-gateway-ui
    velero.io/backup-name: dailymar21
    velero.io/restore-name: dailymar21-20200321081914
  name: api-gateway-ui-konga
  namespace: default
  resourceVersion: "6197100"
  selfLink: /api/v1/namespaces/default/endpoints/api-gateway-ui-konga
  uid: fbeec187-5b29-40fe-b422-15f112cbf134
subsets:
- notReadyAddresses:
  - ip: 10.51.17.136
    nodeName: aks-nodepool1-34292942-vmss000001
    targetRef:
      kind: Pod
      name: api-gateway-ui-konga-58d68766b-mqpkc
      namespace: default
      resourceVersion: "6197098"
      uid: 07619bfa-a1c8-4ce9-83b0-28d6b2d5831d
  ports:
  - name: http
    port: 1337
    protocol: TCP
```

❯ kubectl get pod api-gateway-ui-konga-58d68766b-mqpkc -o yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-21T02:50:31Z"
  generateName: api-gateway-ui-konga-58d68766b-
  labels:
    app: konga
    pod-template-hash: 58d68766b
    release: api-gateway-ui
  name: api-gateway-ui-konga-58d68766b-mqpkc
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: api-gateway-ui-konga-58d68766b
    uid: 5e9435a1-73be-46bf-a18d-05b1fb7df5ca
  resourceVersion: "6197098"
  selfLink: /api/v1/namespaces/default/pods/api-gateway-ui-konga-58d68766b-mqpkc
  uid: 07619bfa-a1c8-4ce9-83b0-28d6b2d5831d
spec:
  containers:
  - env:
# env redacted
    image: pantsel/konga:0.13.0
    imagePullPolicy: IfNotPresent
    name: konga
    ports:
    - containerPort: 1337
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-qkhsd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-34292942-vmss000001
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-qkhsd
    secret:
      defaultMode: 420
      secretName: default-token-qkhsd
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-21T02:50:33Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-04-21T08:22:54Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-24T14:12:12Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-21T02:50:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://027709f2e01e22dd266a91c01bd5d70306c73cc2803265280e2c21e9e47a0d65
    image: pantsel/konga:0.13.0
    imageID: docker-pullable://pantsel/konga@sha256:27f86fb6d12b08211de922d1d677b8a9c73a8b3b41e23b41e098b5f4ad30d9de
    lastState:
      terminated:
        containerID: docker://76e938e996506b90ffa81bd17602893531767e2b26446a22899383f94311ca3f
        exitCode: 1
        finishedAt: "2020-03-24T14:12:10Z"
        reason: Error
        startedAt: "2020-03-24T05:17:20Z"
    name: konga
    ready: true
    restartCount: 11
    state:
      running:
        startedAt: "2020-03-24T14:12:12Z"
  hostIP: 10.51.16.205
  phase: Running
  podIP: 10.51.17.136
  qosClass: BestEffort
  startTime: "2020-03-21T02:50:33Z"
```

/remove-lifecycle rotten

**Comment by mcristina422** [comment]
@jasonchester Your pod is considered not ready. The fix is in 1.15.8. Updating past that version should fix your problem 
 https://github.com/kubernetes/kubernetes/pull/86195

**Comment by msaurabhee** [comment]
This issue is still existing on kubernetes 16.4
Check condition below - 
`Name:         alertmanager-main-0	
Namespace:    instrumentation	
Priority:     0	
Node:         k8s-systempool-25664830-vmss00000t/10.240.20.189	
Start Time:   Mon, 01 Jun 2020 19:36:02 +0530	
Labels:       alertmanager=main	
              app=alertmanager	
              controller-revision-hash=alertmanager-main-6f59cf8b85	
              statefulset.kubernetes.io/pod-name=alertmanager-main-0	
Annotations:  kubernetes.io/psp: privileged	
Status:       Running	
IP:           10.240.20.196	
IPs:	
  IP:           10.240.20.196	
Controlled By:  StatefulSet/alertmanager-main	
Containers:	
  alertmanager:	
    Container ID:  docker://19bbd52c3b2d529447b4b825efe085af8b01b1166efdab45c8f57ef38712cf9a	
    Image:         quay.io/prometheus/alertmanager:v0.17.0	
    Image ID:      docker-pullable://quay.io/prometheus/alertmanager@sha256:3db6eccdbf4bdaea3407b7a9e6a41fc50abcf272a1356227260948e73414ec09	
    Ports:         9093/TCP, 9094/TCP, 9094/UDP	
    Host Ports:    0/TCP, 0/TCP, 0/UDP	
    Args:	
      --config.file=/etc/alertmanager/config/alertmanager.yaml	
      --cluster.listen-address=[$(POD_IP)]:9094	
      --storage.path=/alertmanager	
      --data.retention=120h	
      --web.listen-address=:9093	
      --web.external-url=https://alertmanager.internal.we.dev.ngenius-payments.com	
      --web.route-prefix=/	
      --cluster.peer=alertmanager-main-0.alertmanager-operated.instrumentation.svc:9094	
      --cluster.peer=alertmanager-main-1.alertmanager-operated.instrumentation.svc:9094	
    State:          Running	
      Started:      Mon, 01 Jun 2020 19:36:10 +0530	
    Ready:          True	
    Restart Count:  0	
    Limits:	
      memory:  400Mi	
    Requests:	
      memory:   200Mi	
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10	
    Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10	
    Environment:	
      POD_IP:   (v1:status.podIP)	
    Mounts:	
      /alertmanager from alertmanager-main-db (rw)	
      /etc/alertmanager/config from config-volume (rw)	
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)	
  config-reloader:	
    Container ID:  docker://aa24ba960a01637435540b51769f508690b3d91918aa4928db301157380bb16e	
    Image:         quay.io/coreos/configmap-reload:v0.0.1	
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057	
    Port:          <none>	
    Host Port:     <none>	
    Args:	
      -webhook-url=http://localhost:9093/-/reload	
      -volume-dir=/etc/alertmanager/config	
    State:          Running	
      Started:      Mon, 01 Jun 2020 19:36:13 +0530	
    Ready:          True	
    Restart Count:  0	
    Limits:	
      cpu:     100m	
      memory:  25Mi	
    Requests:	
      cpu:        100m	
      memory:     25Mi	
    Environment:  <none>	
    Mounts:	
      /etc/alertmanager/config from config-volume (ro)	
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)	
Conditions:	
  Type              Status	
  Initialized       True	
  Ready             False	
  ContainersReady   True	
  PodScheduled      True	
Volumes:	
  config-volume:	
    Type:        Secret (a volume populated by a Secret)	
    SecretName:  alertmanager-main	
    Optional:    false	
  alertmanager-main-db:	
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)	
    Medium:	
    SizeLimit:  <unset>	
  default-token-fttqb:	
    Type:        Secret (a volume populated by a Secret)	
    SecretName:  default-token-fttqb	
    Optional:    false	
QoS Class:       Burstable	
Node-Selectors:  <none>	
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s	
                 node.kubernetes.io/unreachable:NoExecute for 300s	
Events:          <none>`

`Name:         alertmanager-main-1
Namespace:    instrumentation
Priority:     0
Node:         k8s-systempool-25664830-vmss00000y/10.240.21.88
Start Time:   Tue, 18 Aug 2020 17:59:44 +0530
Labels:       alertmanager=main
              app=alertmanager
              controller-revision-hash=alertmanager-main-6f59cf8b85
              statefulset.kubernetes.io/pod-name=alertmanager-main-1
Annotations:  kubernetes.io/psp: privileged
Status:       Running
IP:           10.240.21.93
IPs:
  IP:           10.240.21.93
Controlled By:  StatefulSet/alertmanager-main
Containers:
  alertmanager:
    Container ID:  docker://11d17d1be90446d43f990139dfdebe3ac4b5f1de0b269c4345c8bebf4bc961ee
    Image:         quay.io/prometheus/alertmanager:v0.17.0
    Image ID:      docker-pullable://quay.io/prometheus/alertmanager@sha256:3db6eccdbf4bdaea3407b7a9e6a41fc50abcf272a1356227260948e73414ec09
    Ports:         9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:    0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --cluster.listen-address=[$(POD_IP)]:9094
      --storage.path=/alertmanager
      --data.retention=120h
      --web.listen-address=:9093
      --web.external-url=https://alertmanager.internal.we.dev.ngenius-payments.com
      --web.route-prefix=/
      --cluster.peer=alertmanager-main-0.alertmanager-operated.instrumentation.svc:9094
      --cluster.peer=alertmanager-main-1.alertmanager-operated.instrumentation.svc:9094
    State:          Running
      Started:      Tue, 18 Aug 2020 17:59:53 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  400Mi
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-main-db (rw)
      /etc/alertmanager/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)
  config-reloader:
    Container ID:  docker://2eaee1eeb3fd8e9b3a5ca1143317ba29a5bf7262bae592bc615f6f9b6b270b21
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      -webhook-url=http://localhost:9093/-/reload
      -volume-dir=/etc/alertmanager/config
    State:          Running
      Started:      Tue, 18 Aug 2020 17:59:58 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-main
    Optional:    false
  alertmanager-main-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-fttqb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fttqb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>`

Kubernetes verision on nodes - 
`k8s-systempool-25664830-vmss00000t   Ready    agent    79d     v1.16.4   10.240.20.189   <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.8
k8s-systempool-25664830-vmss00000y   Ready    agent    79d     v1.16.4   10.240.21.88    <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.8`
`

**Comment by qmloong** [comment]
> This issue is still existing on kubernetes 16.4
> Check condition below -
> 
> This is the first pod.
> 
> ```
> Name:         alertmanager-main-0	
> Namespace:    instrumentation	
> Priority:     0	
> Node:         k8s-systempool-25664830-vmss00000t/10.240.20.189	
> Start Time:   Mon, 01 Jun 2020 19:36:02 +0530	
> Labels:       alertmanager=main	
>               app=alertmanager	
>               controller-revision-hash=alertmanager-main-6f59cf8b85	
>               statefulset.kubernetes.io/pod-name=alertmanager-main-0	
> Annotations:  kubernetes.io/psp: privileged	
> Status:       Running	
> IP:           10.240.20.196	
> IPs:	
>   IP:           10.240.20.196	
> Controlled By:  StatefulSet/alertmanager-main	
> Containers:	
>   alertmanager:	
>     Container ID:  docker://19bbd52c3b2d529447b4b825efe085af8b01b1166efdab45c8f57ef38712cf9a	
>     Image:         quay.io/prometheus/alertmanager:v0.17.0	
>     Image ID:      docker-pullable://quay.io/prometheus/alertmanager@sha256:3db6eccdbf4bdaea3407b7a9e6a41fc50abcf272a1356227260948e73414ec09	
>     Ports:         9093/TCP, 9094/TCP, 9094/UDP	
>     Host Ports:    0/TCP, 0/TCP, 0/UDP	
>     Args:	
>       --config.file=/etc/alertmanager/config/alertmanager.yaml	
>       --cluster.listen-address=[$(POD_IP)]:9094	
>       --storage.path=/alertmanager	
>       --data.retention=120h	
>       --web.listen-address=:9093	
>       --web.external-url=https://some-random-url.com	
>       --web.route-prefix=/	
>       --cluster.peer=alertmanager-main-0.alertmanager-operated.instrumentation.svc:9094	
>       --cluster.peer=alertmanager-main-1.alertmanager-operated.instrumentation.svc:9094	
>     State:          Running	
>       Started:      Mon, 01 Jun 2020 19:36:10 +0530	
>     Ready:          True	
>     Restart Count:  0	
>     Limits:	
>       memory:  400Mi	
>     Requests:	
>       memory:   200Mi	
>     Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10	
>     Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10	
>     Environment:	
>       POD_IP:   (v1:status.podIP)	
>     Mounts:	
>       /alertmanager from alertmanager-main-db (rw)	
>       /etc/alertmanager/config from config-volume (rw)	
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)	
>   config-reloader:	
>     Container ID:  docker://aa24ba960a01637435540b51769f508690b3d91918aa4928db301157380bb16e	
>     Image:         quay.io/coreos/configmap-reload:v0.0.1	
>     Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057	
>     Port:          <none>	
>     Host Port:     <none>	
>     Args:	
>       -webhook-url=http://localhost:9093/-/reload	
>       -volume-dir=/etc/alertmanager/config	
>     State:          Running	
>       Started:      Mon, 01 Jun 2020 19:36:13 +0530	
>     Ready:          True	
>     Restart Count:  0	
>     Limits:	
>       cpu:     100m	
>       memory:  25Mi	
>     Requests:	
>       cpu:        100m	
>       memory:     25Mi	
>     Environment:  <none>	
>     Mounts:	
>       /etc/alertmanager/config from config-volume (ro)	
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)	
> Conditions:	
>   Type              Status	
>   Initialized       True	
>   Ready             False	
>   ContainersReady   True	
>   PodScheduled      True	
> Volumes:	
>   config-volume:	
>     Type:        Secret (a volume populated by a Secret)	
>     SecretName:  alertmanager-main	
>     Optional:    false	
>   alertmanager-main-db:	
>     Type:       EmptyDir (a temporary directory that shares a pod's lifetime)	
>     Medium:	
>     SizeLimit:  <unset>	
>   default-token-fttqb:	
>     Type:        Secret (a volume populated by a Secret)	
>     SecretName:  default-token-fttqb	
>     Optional:    false	
> QoS Class:       Burstable	
> Node-Selectors:  <none>	
> Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s	
>                  node.kubernetes.io/unreachable:NoExecute for 300s	
> Events:          <none>
> ```
> 
> This is the other pod -
> 
> ```
> Name:         alertmanager-main-1
> Namespace:    instrumentation
> Priority:     0
> Node:         k8s-systempool-25664830-vmss00000y/10.240.21.88
> Start Time:   Tue, 18 Aug 2020 17:59:44 +0530
> Labels:       alertmanager=main
>               app=alertmanager
>               controller-revision-hash=alertmanager-main-6f59cf8b85
>               statefulset.kubernetes.io/pod-name=alertmanager-main-1
> Annotations:  kubernetes.io/psp: privileged
> Status:       Running
> IP:           10.240.21.93
> IPs:
>   IP:           10.240.21.93
> Controlled By:  StatefulSet/alertmanager-main
> Containers:
>   alertmanager:
>     Container ID:  docker://11d17d1be90446d43f990139dfdebe3ac4b5f1de0b269c4345c8bebf4bc961ee
>     Image:         quay.io/prometheus/alertmanager:v0.17.0
>     Image ID:      docker-pullable://quay.io/prometheus/alertmanager@sha256:3db6eccdbf4bdaea3407b7a9e6a41fc50abcf272a1356227260948e73414ec09
>     Ports:         9093/TCP, 9094/TCP, 9094/UDP
>     Host Ports:    0/TCP, 0/TCP, 0/UDP
>     Args:
>       --config.file=/etc/alertmanager/config/alertmanager.yaml
>       --cluster.listen-address=[$(POD_IP)]:9094
>       --storage.path=/alertmanager
>       --data.retention=120h
>       --web.listen-address=:9093
>       --web.external-url=https://some-random-url.com
>       --web.route-prefix=/
>       --cluster.peer=alertmanager-main-0.alertmanager-operated.instrumentation.svc:9094
>       --cluster.peer=alertmanager-main-1.alertmanager-operated.instrumentation.svc:9094
>     State:          Running
>       Started:      Tue, 18 Aug 2020 17:59:53 +0530
>     Ready:          True
>     Restart Count:  0
>     Limits:
>       memory:  400Mi
>     Requests:
>       memory:   200Mi
>     Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
>     Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
>     Environment:
>       POD_IP:   (v1:status.podIP)
>     Mounts:
>       /alertmanager from alertmanager-main-db (rw)
>       /etc/alertmanager/config from config-volume (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)
>   config-reloader:
>     Container ID:  docker://2eaee1eeb3fd8e9b3a5ca1143317ba29a5bf7262bae592bc615f6f9b6b270b21
>     Image:         quay.io/coreos/configmap-reload:v0.0.1
>     Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
>     Port:          <none>
>     Host Port:     <none>
>     Args:
>       -webhook-url=http://localhost:9093/-/reload
>       -volume-dir=/etc/alertmanager/config
>     State:          Running
>       Started:      Tue, 18 Aug 2020 17:59:58 +0530
>     Ready:          True
>     Restart Count:  0
>     Limits:
>       cpu:     100m
>       memory:  25Mi
>     Requests:
>       cpu:        100m
>       memory:     25Mi
>     Environment:  <none>
>     Mounts:
>       /etc/alertmanager/config from config-volume (ro)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-fttqb (ro)
> Conditions:
>   Type              Status
>   Initialized       True
>   Ready             True
>   ContainersReady   True
>   PodScheduled      True
> Volumes:
>   config-volume:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  alertmanager-main
>     Optional:    false
>   alertmanager-main-db:
>     Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
>     Medium:
>     SizeLimit:  <unset>
>   default-token-fttqb:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  default-token-fttqb
>     Optional:    false
> QoS Class:       Burstable
> Node-Selectors:  <none>
> Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
>                  node.kubernetes.io/unreachable:NoExecute for 300s
> Events:          <none>
> ```
> 
> Kubernetes version on nodes -
> 
> ```
> k8s-systempool-25664830-vmss00000y   Ready    agent    79d     v1.16.4   10.240.21.88    <none>        Ubuntu 16.04.6 LTS   4.15.0-1082-azure   docker://3.0.8`
> ```

+1
