### ISSUE TITLE
add support for cipher-suites flag for etcd used by kubernetes

### ISSUE THREAD

**Issue by Alexc0007** [kubernetes/kubernetes#85392]
**What would you like to be added**:
i would like to control the ciphers used by etcd to communicate with other components on tls.
(same as --tls-cipher-suites on kube-apiserver , kube-controller-manager and kube-scheduler)
official etcd supports adding --cipher-suites 'LIST OF CIPHERS'
but when i try to add the flag on /etc/kubernetes/manifests/etcd.yaml - etcd just wont start anymore...

for example:
- --cipher-suites="TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"

**Why is this needed**:
to block weak ciphers(like 3DES) that are present in go standard ciphers library.

**Comment by liggitt** [comment]
Is this a feature request for etcd?

**Comment by Alexc0007** [comment]
well , basically as i already stated this feature is present on etcd...
but for some reason it doesnt work when creating etcd.yaml on kubernetes.

**Comment by liggitt** [comment]
I think the quotes might be your problem... those arguments don't pass through a shell. try 

`--cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`

**Comment by Alexc0007** [comment]
Hi , 
i tried it with quotes , without quotes or with any other possible variation...
nothing works... etcd just wont start

**Comment by liggitt** [comment]
what version of etcd does the manifest reference? that was added in 3.2.22+, 3.3.7+, and 3.4.0+?

also, what is the log output of the failed etcd container?

**Comment by Alexc0007** [comment]
ill close this case , the issue seems to be with etcd...
the cipher-suites option is working , its just breaking the cluster.
ill have to figure out what is causing the cluster to lose connection between the nodes.

**Comment by subudear** [comment]
Why is this closed. This is still an issue. Once --cipher-suites is added to etcd manifest, the pod stops starting.

**Comment by neolit123** [comment]
> the cipher-suites option is working , its just breaking the cluster.

this is not a kubernetes/kubernetes issue per se.
maybe the etcd repository has an issue logged about it already:
https://github.com/etcd-io/etcd/search?q=--cipher-suites&type=Issues

if not try logging a new one.
