### ISSUE TITLE
cluster-capacity project status

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85399]
GitHub admin team reached out regarding project cluster-capacity, they are in the process of decommissioning the kubernetes-incubator organization. 

Is cluster-capacity project still active? should sig-scheduling continue to own the project? and if so it should be moved to kubernetes-sigs.

/assign @ravisantoshgudimetla 
/sig scheduling

**Comment by ravisantoshgudimetla** [comment]
I think, this project might still be useful for federated cluster use-cases and it falls under sig-scheduling purview. AFAIK no active development is happening.

cc @ingvagabund - Do you want to move this to sig sponsored repo or archive this project?

**Comment by ingvagabund** [comment]
@ahg-g yes for keeping the project under sig-scheduling. Although there's no active development right now, people are still using the code as a library. I would like to move the project to sig sponsored repo. Do I still need to provide a roadmap/plan for a couple of releases?

**Comment by ahg-g** [comment]
ok, then lets move it. I think at the minimum we should have regular releases that are aligned with k8s

**Comment by ingvagabund** [comment]
> we should have regular releases that are aligned with k8s

I can take care of that. I have already a rebase PR ready for 1.15.3 (https://github.com/kubernetes-incubator/cluster-capacity/pulls) after which it will be easy to bump to 1.16 and higher.

**Comment by ahg-g** [comment]
This is moved to kubernetes-sigs
