### ISSUE TITLE
APIAggregator#PrepareRun should return exported type

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#85398]
**What would you like to be added**:
Looking at the usage of APIAggregator#PrepareRun, the first return value is used as runnable.
We should export runnable type (Runnable) and declare the return type for APIAggregator#PrepareRun as Runnable.

**Why is this needed**:
APIAggregator#PrepareRun returns preparedAPIAggregator which is unexported.

**Comment by liggitt** [comment]
cc @sttts @deads2k

**Comment by yue9944882** [comment]
this is a deisgned "option ----> config --(complete) --> completedConfig --(new)--> instance" code flow. the other way round, i remember we agreed refactoring and applying it throughout the codebase somewhere else offline..
