### ISSUE TITLE
`kube-up.sh` doesn't prompt for downloading

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#85405]
**What happened**:
If `kubernetes-server-linux-amd64.tar.gz` doesn't exist in $KUBE_ROOT/_output/release-tars, the script doesn't prompt for downloading from external release URL, but just move on util an error is thrown instead.
```
$ bash cluster/kube-up.sh
... Starting cluster in us-central1-b using provider gce
... calling verify-prereqs
... calling verify-kube-binaries
... calling verify-release-tars
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
... calling kube-up
Project: dave-test-kubemark
Network Project: dave-test-kubemark
Zone: us-central1-b
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
```

**What you expected to happen**:
If the tarball does not exist, it should be able to download from external release URL.

**How to reproduce it (as minimally and precisely as possible)**:
- remove the tarball `kubernetes-server-linux-amd64.tar.gz` from $KUBE_ROOT/_output/release-tars
- run `bash cluster/kube-up.sh`

**Anything else we need to know?**:
The script has everything there, but there is a minor issue has caused the script move on silently after the close the child function.
 
**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
tagging with the appropriate sigs, but please mind that kube-up is deprecated and should not be used in the wild.

please move to a different tool for cluster creation, like kubeadm, kops, minikube, kind, cluster-api etc.
/sig cluster-lifecycle testing
