### ISSUE TITLE
Metrics registered by import can not be enable after turned off

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/kubernetes#85411]
**What happened**:
The metrics be registered by `init()`, from import call tree, will lose the possibility to be enabled again by `--show-hidden-metrics-for-version`. 

Now, for a specific metric only get one chance to be registered, if it is registered by `init()` call from import, that means it will be bypass `SetShowHidden()`, so it can not be enabled again.

**What you expected to happen**:
All turned off metrics in the last release can be enable again by `--show-hidden-metrics-for-version`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We have 4 metrics be affected(had turned off 9 metrics):
- rest_client_request_latency_seconds
- apiserver_storage_transformation_latencies_microseconds
- apiserver_storage_transformation_failures_total
- apiserver_storage_data_key_generation_latencies_microseconds

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.0-alpha.0.1093
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/priority critical-urgent
/assign
/sig instrumentation
/milestone v1.17

**Comment by RainbowMango** [comment]
IMO, we can't/shouldn't stop components to register metrics by init() calls from import.
So, I'd prefer to track all the collectors inside the stability framework. 

The idea is :
- Extend Registerable interface, add a API like `Clear()` for clear all status marked in last register process; 
- track all collectors in kubeRegistry, classify by registerable, hidden, etc...
- track all registry 
- when --show-hidden-metrics-for-version be set, re-register the hidden collectors...

I'm trying it at local and will get back to you later.  (Ping more guys after kubecon :))

**Comment by dims** [comment]
thanks @RainbowMango !

**Comment by logicalhan** [comment]
We can do this in the registry as well. 

It'll require two changes:

1. ShowHidden takes a bool which sets show hidden flag. This needs to be invoked in each component. 
2. Defer all the Create calls until we call SetShowHidden is invoked.

**Comment by dims** [comment]
@logicalhan @RainbowMango other than #85444 what else do we need for 1.17.0?

**Comment by RainbowMango** [comment]
@dims 

> other than #85444 what else do we need for 1.17.0?

That is https://github.com/kubernetes/kubernetes/pull/83841, still waiting approval from sig-node.
