### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by fozziscrazy77** [kubernetes/kubernetes#85420]
Internal applets
toybox 0.7.3-37-g04940678c81a
/data/user/0/eu.thedarken.sdm/files/toybox_sdm
cat (USER), chmod (USER), chown (USER), cp (USER), du (USER), echo (USER), find (USER), grep (USER), kill (USER), mkdir (USER), mount (USER), mv (USER), pidof (USER), ps (USER), rm (USER), rmdir (USER), stat (USER), test (USER), touch (USER), xargs (USER) just wondering what this mesnsvpjü

**Comment by dims** [comment]
/close

not sure what this is about
