### ISSUE TITLE
Swagger file missing io.k8s.apimachinery.pkg.apis.meta.v1.unstructured.Unstructured 

### ISSUE THREAD

**Issue by retnuh** [kubernetes/kubernetes#85448]
**What happened**:

the `api/openapi-spec/swagger.json` does not contain an entry for the `io.k8s.apimachinery.pkg.apis.meta.v1.unstructured.Unstructured` type.

**What you expected to happen**:

As this type is consumed by downstream dependencies (specifically, argo-events), it would be nice if it were actually exported in the swagger/openapi definition.

**How to reproduce it (as minimally and precisely as possible)**:

It's not there; you can verify that in the checked-in file.

**Anything else we need to know?**:

**Environment**:
I would assume all of them!

**Comment by liggitt** [comment]
the swagger.json file only contains types referenced from served endpoints... is the unstructured type returned from served endpoints?

**Comment by retnuh** [comment]
I believe the argo-events sensors allow you to refer to arbitrary k8s objects as resources:  https://github.com/argoproj/argo-events/blob/53dc7076b03ab5afa022b33d840e302b3285963c/pkg/apis/sensor/v1alpha1/openapi_generated.go

**Comment by liggitt** [comment]
then I would expect the openapi served by the argoevents server to include the unstructured definition, but the static swagger.json file in the kubernetes/kubernetes repo only contains the types served by the kube-apiserver

**Comment by retnuh** [comment]
Why should an external project need to define a kubernetes type to work?  I don't understand.  It's a type defined in the kubernetes project; k8s should provide the definition in it's swagger file.  That's the point - a central point of authority.  If every external project has to create it's own swagger definitions, that will lead to chaos.

**Comment by liggitt** [comment]
The /openapi/v2 endpoint fetched from an actual server will return the definitions for things served by that server. The static swagger.json checked in is not expected to contain all definitions for all types that can be served by any server (it can't, given aggregated and custom resource definitions)
