### ISSUE TITLE
Scheduler resource leak: deleted pod is not deleted from nominated pods

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#85447]
**What happened**:

Environment:  kubernetes 1.13, and pod priority and preemption are enabled.
 
Pod `test` is nominated to node `node-1`. Before pod `test` is [assumed](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L529), it will never be deleted(deleted at [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L542)) from [`nominatedPods`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L138) in scheduler cache. However if the pod `test` is deleted before it is assumed, then it will always be there, and it will be used by [addNominatedPods](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L581) to added to node `node-1`'s request resource that used for predicates, it will cause node resource leak and other pods could not use it.

**What you expected to happen**:

When pod is deleted, it should be deleted from [`nominatedPods`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L138) in scheduler cache.

/sig scheduling
/assign

**Comment by khyveasna** [comment]
@k8s-ci-robot `j`

**Comment by hex108** [comment]
/close

Close it now, I do not have a reproducible enviroment for it now. But I guess it is related to https://github.com/kubernetes/kubernetes/issues/86198: pod A is scheduled to a pod, and it is put to scheduling queue because of pod annotaitons update, then it gets scheduled again and preempts a pod, and sscheduler add it as a nominated pod.
