### ISSUE TITLE
kubelet_running_pod_count metric includes also non-running pods

### ISSUE THREAD

**Issue by r0bj** [kubernetes/kubernetes#85450]
**What happened**:

`kubelet_running_pod_count` metric returns incorrect number including pods in non-running state.

**What you expected to happen**:

`kubelet_running_pod_count` metric returns correct number of pod only in running state.

**How to reproduce it (as minimally and precisely as possible)**:

Number of pods on node `k8s-worker-s53` in different state:
```
# kubectl get po -A -o wide | grep k8s-worker-s53 | grep Running | wc -l
29

# kubectl get po -A -o wide | grep k8s-worker-s53 | wc -l
161
```

Metric `kubelet_running_pod_count`:
```
$ wget -q --no-check-certificate --header="Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -SO - https://10.8.42.48:10250/metrics | grep kubelet_running_pod_count
# HELP kubelet_running_pod_count [ALPHA] Number of pods currently running
# TYPE kubelet_running_pod_count gauge
kubelet_running_pod_count 161
```

**Anything else we need to know?**:

It seems that metric `kubelet_running_pod_count` includes pod in many different states, e.g.: `Completed`, `Error` however it should includes only `Running` state.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.1
- Kernel (e.g. `uname -a`):
```
Linux k8s-worker-s53 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- containerd: 1.2.10

**Comment by zouyee** [comment]
https://github.com/kubernetes/kubernetes/issues/81412
duplicate
/close

**Comment by xiaoanyunfei** [comment]
Do you make progress in this issue ?  @zouyee
