### ISSUE TITLE
Revert PV deletion in Terminating State

### ISSUE THREAD

**Issue by uselessidbr** [kubernetes/kubernetes#85465]
**What would you like to be added**: Possibility to revert a PV deletion in Terminating State

**Why is this needed**: While the deletion was not processed, it should be possible to undo it. Ex.: mistaken deletion

**Comment by liggitt** [comment]
Setting of deletionTimestamp on an object is a one-way operation. Allowing "undoing" a deletion request would require everything reacting to observing the deletion to also be able to undo any action they took in response. This includes not only the controllers inside the kubernetes tree, but also third-party API clients.

/close
