### ISSUE TITLE
Degradation of audit-webhook in batch mode can still impact apiserver

### ISSUE THREAD

**Issue by EdwinRobbins** [kubernetes/kubernetes#85489]
**What happened**:
Had a audit-webhook configured for batch logging which received a large number of audit logs and because CPU throttled as a result. This caused the apiserver to OOM and resulted in a cluster outage.

**What you expected to happen**:
Using an audit-webhook in batch mode the expectation is that apiserver operation should be prioritized over audit logging and that failure or degradation of audit logging should be ignored by the apiserver. 

In this case the webhook being throttled delayed its ability to handle in coming logs. This in turn caused a build up of connections in the apiserver and resulted in it getting OOM killed. 

Expectation limitation on number of connections/TTL should protect it from unbounded audit logging connections and these should be dropped as needed to continue stable operation. Similar to dropping logs when the buffer is full.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run audit-webhook and set CPU limits such that it will be throttled. 
2. Increase apiserver requests until volume causes connection build up and memory consumption. 

**Anything else we need to know?**:
NA

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.602
- Cloud provider: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3
- Kernel (e.g. `uname -a`): 4.15.0-1052-aws

**Comment by tallclair** [comment]
Can you share your full audit configuration? Not the audit policy, just the flags (`--audit-*` flags)

**Comment by EdwinRobbins** [comment]
- "--audit-policy-file={{ $confDir }}/audit-policy.yml"
    - "--audit-log-path={{ $auditLogDir }}/audit.log"
    - "--audit-log-maxage=1"
    - "--audit-log-maxbackup=5"
    - "--audit-log-maxsize=200"

The webhook is being configured dynamically via AuditSinks so the following are set as well, but have used the same audit-webhook configured via runtime configuration.  
    - "--audit-dynamic-configuration"
    - "--feature-gates=DynamicAuditing=true"
    - "--runtime-config=auditregistration.k8s.io/v1alpha1=true"

**Comment by tallclair** [comment]
Ah, this is a known issue with dynamic auditing, and needs to be addressed before the feature can advance to beta. The slowdown is probably because the batch queue keeps a copy of the full request and response for every request.

**Comment by EdwinRobbins** [comment]
It appeared as though it was not an issue with the audit buffer itself, but more so that the audit-webhook when under heavy load and getting CPU throttled would cause the apiserver to maintain many connections and get OOM killed.

Due to difference in audit policy between AuditSink and the runtime one we had to make a more permissive policy and then rely on the webhook to drop them to keep the same effective policy. This increase in events was the cause of the webhook getting CPU throttled. Normal operation was restored by increasing the webhooks CPU limits. 

But the condition of the apiserver keeping too many connections when the downstream webhook is being throttled appeared as though it could affect both AuditSink or runtime configured webhooks. Even when in batch mode where the expectation would be do drop logs in favor of apiserver stability.

**Comment by waynepeking348** [comment]
@EdwinRobbins hi~ we seem to encounter the same problem as described in our production environment, so I wonder if you have any idea how to deal with this now.

**Comment by EdwinRobbins** [comment]
@waynepeking348 if you are running into this issue when using dynamic auditing I was able to mitigate the effect by running a fork of k8s with a lower timeout for the apiserver's requests to the audit webhook. The default 30s timeout was causing a connection build up in the apiserver. If your audit webhook is being throttled increasing its limits may also help
