### ISSUE TITLE
Explore e2e tests that hit a focused # of endpoints

### ISSUE THREAD

**Issue by zachmandeville** [kubernetes/kubernetes#85487]
This is an exploration to potentially help identify e2e tests that would be a good fit for promotion to conformance.  I am curious to find the intersection of tests that hit a small number of endpoints, and whether those endpoints are hit by a small number of tests.  This would highlight tests that are written specifically for that endpoint.  For example, if `listCoreFoov1Bar' is only hit by 1 test, and that test only hits a handful of endpoints including `listCoreFoov1Bar`, it's likely the test was written to intentionally check the behavior of that endpoint (compared to an endpoint that's hit by 800 tests, but it's an incidental hit).  This will help us find endpoints that are being _meaningfully_ tested.

The next step would be to find which of these meaningful tests are hitting stable/core endpoints, and are not yet part of conformance.  These would be good candidates to check against the conformance guidelines, and see if they'd be fit for promotion-- if they are, we'd be increasing our conformance coverage with focused, intentional tests.

I will be doing this exploration using Apisnoop, and running queries against audit logs from a recent master e2e job .

**Comment by neolit123** [comment]
/sig testing
/sig architecture
(for conformance sub-project)
