### ISSUE TITLE
Graceful deletion mutates object invalidating ResourceVersion in deletion precondition

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/kubernetes#85485]
**What happened**:

When developing unit tests related to PDBs/Deletion,https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L932 mutates pod resource via adding deletion timestamp, and this directly conflicts with checking resource version.

**What you expected to happen**:

No resource version mutation.

**How to reproduce it (as minimally and precisely as possible)**:

I'm attempting to add preconditions to delete call in eviction API:
https://github.com/kubernetes/kubernetes/pull/83906/files#diff-9644c646d1076728c605baed12a5813aR138

**Anything else we need to know?**:
Happens locally and in CI.

**Environment**:
- Kubernetes version (use `kubectl version`): Head of master: c97baa339b5043424522dc7932fc3891f15543cb
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
> When developing unit tests related to PDBs/Deletion, k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:conditionalDelete mutates pod resource version when it shouldn't.

can you provide more details about what you're observing?

**Comment by michaelgugino** [comment]
@liggitt 

You can see an example here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83906/pull-kubernetes-bazel-test/1197243638665449474

```
     --- FAIL: TestEviction/matching_pdbs_with_no_disruptions_allowed,_pod_pending (0.16s)
        eviction_test.go:176: expected error=false, got Operation cannot be fulfilled on pods "t2": StorageError: invalid object, Code: 4, Key: /registry/pods/default/t2, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: ResourceVersion in precondition: 2, ResourceVersion in object meta: 3; name t2 
```

Here's the relevant section of the tests:
https://github.com/kubernetes/kubernetes/blob/7eb83891d5fe585030fcb2cb89deda86b6dc8a3f/pkg/registry/core/pod/storage/eviction_test.go#L145



There really shouldn't be anything modifying the pod after creation until the delete request, thus I don't believe we should be hitting this precondition failure.  Resource Version in precondition I believe to be correct, but when we contact etcd to verify, it's increased by one.  It's not clear why this is happening, it appears to be a bug.

**Comment by michaelgugino** [comment]
Okay, I've sorted this out.  We have a conflict with 'graceful' deletion with this approach:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L932

This updates the object to add a deletion timestamp, thus the first call to eviction will always fail if we need to set ResourceVersion.
