### ISSUE TITLE
404 urls 

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kubernetes#85495]
**What happened**:
404 urls
**What you expected to happen**:
fix them

1. staging/src/k8s.io/kubectl/docs/book/pages/reference/kustomize.md,https://github.com/kubernetes-sigs/kustomize/tree/master/pkg/transformers/config/defaultconfig
1. staging/src/k8s.io/kubectl/docs/book/pages/reference/kustomize.md,https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/commonannotations.go
1. staging/src/k8s.io/kubectl/docs/book/pages/reference/kustomize.md,https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/commonlabels.go
1. staging/src/k8s.io/kubectl/docs/book/pages/reference/kustomize.md,https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/namereference.go

**Comment by tanjunchen** [comment]
@kubernetes/sig-docs-en-reviews

**Comment by tanjunchen** [comment]
https://github.com/kubernetes/kubernetes/pull/85163 fix number 19

**Comment by prksu** [comment]
#85596 fix number 1 & 2

**Comment by CriaHu** [comment]
@tanjunchen 

kubernetes/CHANGELOG-1.10/1.11/1.12.md  
https://kubernetes-csi.github.io/docs/Drivers.html(404)

kubernetes/CHANGELOG-1.14.md https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0029-20180918-kubeadm-phases-beta.md(404) https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/20190122-Certificates-copy-for-kubeadm-join--control-plane.md(404)

**Comment by tanjunchen** [comment]
@CriaHu In your similar pr, please leave in the comments
```Ref:pr url fix number xx``` 
I will remove number xx in table Once They are merged

**Comment by CriaHu** [comment]
@tanjunchen  I submit links that are not in this form. You can add these links to the form.

**Comment by tanjunchen** [comment]
#85684 fix 21   24  25
#85629 fix number 22

**Comment by KobayashiD27** [comment]
#86628 fix 10 11 12

**Comment by YuikoTakada** [comment]
#86637 fix 13 15

**Comment by tanjunchen** [comment]
/cc @neolit123 
/cc @liggitt 
Hello , Do you agree that the ulrs(CHANGELOG-1.*.md) above? They are too old , We should't  correct them . Thanks.

**Comment by neolit123** [comment]
@tanjunchen 
what do you mean by removed?

the `kustomize.md` was worth fixing, but looks like you did that already:
https://github.com/kubernetes/kubernetes/commit/efd61ae3e4826125d65ef7824e3243e2480c7205

my vote goes to not update the changelog for versions that are too old. links and infrastructure change all the time. whole pages or even components might not exists at this point.

**Comment by tanjunchen** [comment]
@neolit123 
Yes, I agree with you that old links should be kept, so I should update the above URLs to prevent someone from submitting a pr to fix them.

**Comment by neolit123** [comment]
please update the above list to only have items that need fixing.
