### ISSUE TITLE
 failed to pull image k8s.gcr.io/kube-controller-manager:v1.16.3

### ISSUE THREAD

**Issue by chennakesava1** [kubernetes/kubernetes#85498]
@kubernetes/sig-node
@kubernetes/sig-Docs

I am following the installation Docs "https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin"
**While running kubeadm init below error  **:
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.16.3: output: Trying to pull repository k8s.gcr.io/kube-apiserver ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.16.3: output: Trying to pull repository k8s.gcr.io/kube-controller-manager ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.16.3: output: Trying to pull repository k8s.gcr.io/kube-scheduler ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.16.3: output: Trying to pull repository k8s.gcr.io/kube-proxy ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Trying to pull repository k8s.gcr.io/pause ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.15-0: output: Trying to pull repository k8s.gcr.io/etcd ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.2: output: Trying to pull repository k8s.gcr.io/coredns ...
Get https://k8s.gcr.io/v1/_ping: dial tcp 172.217.218.82:443: i/o timeout
, error: exit status 1

**status of kubelet**:
[root@kubemaster ~]# systemctl status kubeadm
Unit kubeadm.service could not be found.
```
[root@kubemaster ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-11-21 00:51:19 EST; 9s ago
     Docs: https://kubernetes.io/docs/
  Process: 1468 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255)
 Main PID: 1468 (code=exited, status=255)

Nov 21 00:51:19 kubemaster systemd[1]: Unit kubelet.service entered failed state.
Nov 21 00:51:19 kubemaster systemd[1]: kubelet.service failed.
[root@kubemaster ~]#
```
**kubelet logs**:
```
[root@kubemaster ~]# journalctl -xeu kubelet| tail -5
-- The start-up result is done.
Nov 21 00:54:54 kubemaster kubelet[1676]: F1121 00:54:54.692166    1676 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Nov 21 00:54:54 kubemaster systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Nov 21 00:54:54 kubemaster systemd[1]: Unit kubelet.service entered failed state.
Nov 21 00:54:54 kubemaster systemd[1]: kubelet.service failed.
```

**OS version Info**:
```
[root@kubemaster ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
**kernal**:
[root@kubemaster ~]# uname -a
Linux kubemaster 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Docker and kube* verison info**:
```
[root@kubemaster ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false
[root@kubemaster ~]#
```

**Installed tools?**:
[root@kubemaster ~]# yum list kube*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
Installed Packages
kubeadm.x86_64                                                                                1.16.3-0                                                                                       @kubernetes
kubectl.x86_64                                                                                1.16.3-0                                                                                       @kubernetes
kubelet.x86_64                                                                                1.16.3-0                                                                                       @kubernetes
kubernetes-cni.x86_64                                                                         0.7.5-0                                                                                        @kubernetes
Available Packages
kubernetes.x86_64                                                                             1.5.2-0.7.git269f928.el7                                                                       extras
kubernetes-client.x86_64                                                                      1.5.2-0.7.git269f928.el7                                                                       extras
kubernetes-master.x86_64                                                                      1.5.2-0.7.git269f928.el7                                                                       extras
kubernetes-node.x86_64                                                                        1.5.2-0.7.git269f928.el7                                                                       extras
[root@kubemaster ~]#

**Comment by chennakesava1** [comment]
added

**Comment by neolit123** [comment]
/triage support

hi, please check if you have connectivity to the GCR bucket:
```
docker pull k8s.gcr.io/kube-proxy:v1.16.3
```

**Comment by chennakesava1** [comment]
@neolit123 Thanks! after fixing the issue with docker pull after I fixed the connectivity issue with GCR bucket it's start's working.

**Comment by Panghu98** [comment]
I got the same problem,is there some ways to resolve?
