### ISSUE TITLE
Possible Bug: /metrics/cadvisor value is wrong, it's larger than docker stats value

### ISSUE THREAD

**Issue by zhangxingdeppon** [kubernetes/kubernetes#85505]
**What happened**:
hi, buddies, I met a probelem, I found that ` /metrics/cadvisor` value is uncorrect, it's larger than `docker stats` value, did it added another resource's value?  could you give me some ideas?  it's very important for me, thanks.
**What you expected to happen**:
I expect to the value to correct.
**How to reproduce it (as minimally and precisely as possible)**:

Here is a example , `cadvisor metric` is  `container_memory_usage_bytes`,  pod name  is `zp2itj8enjuvnz8m-notebook-db7766c74-lrtwr`.
Firstly, check the cadvisor metric `container_memory_usage_bytes` value 
<pre><code>
[root@D21117U04-62-64 ~]# curl https://172.29.62.97:10250/metrics/cadvisor    --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key  --cacert /etc/kubernetes/pki/ca.crt -k |grep zp2itj8enjuvnz8m |grep container_memory_usage_bytes

container_memory_usage_bytes{container_name="zp2itj8enjuvnz8m-notebook",id="/kubepods/burstable/poda036f7c1-0b77-11ea-8085-9cb654b8ed1e/34a1d239c520271090a023b15a97c21358951c758ec778be302d0f3bf3573bb5",image="172.29.62.9:8080/notebook/deeplearning_jupyter_limit_token@sha256:dfc8a164086e77effc5fafec0ac8f8c3c479328e0b7250d750f25d2577eb9501",name="k8s_zp2itj8enjuvnz8m-notebook_zp2itj8enjuvnz8m-notebook-db7766c74-lrtwr_aipaas-notebook_a036f7c1-0b77-11ea-8085-9cb654b8ed1e_1",namespace="aipaas-notebook",pod_name="zp2itj8enjuvnz8m-notebook-db7766c74-lrtwr"} 6.294532096e+09

</code></pre>
you will find the container_memory_usage_bytes value is `6.294532096e+09`, means used `6002.9MB`.

Secondly, check the docker container  `zp2itj8enjuvnz8m-notebook` `docker stats` value, you will find `MEM USAGE` value is `84MiB`, actually this is truely value. 
 <pre><code>
[root@D21014U04-62-97 ~]# docker ps |grep zp2itj8enjuvnz8m
34a1d239c520        172.29.62.9:8080/notebook/deeplearning_jupyter_limit_token   "/usr/bin/tini -- /b…"   7 hours ago         Up 7 hours                              k8s_zp2itj8enjuvnz8m-notebook_zp2itj8enjuvnz8m-notebook-db7766c74-lrtwr_aipaas-notebook_a036f7c1-0b77-11ea-8085-9cb654b8ed1e_1
adce51fd8045        registry.aliyuncs.com/google_containers/pause:3.1            "/pause"                 24 hours ago        Up 24 hours                             k8s_POD_zp2itj8enjuvnz8m-notebook-db7766c74-lrtwr_aipaas-notebook_a036f7c1-0b77-11ea-8085-9cb654b8ed1e_0

[root@D21014U04-62-97 ~]# docker stats 34a1d239c520

CONTAINER ID        NAME                                                                                                                             CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
34a1d239c520        k8s_zp2itj8enjuvnz8m-notebook_zp2itj8enjuvnz8m-notebook-db7766c74-lrtwr_aipaas-notebook_a036f7c1-0b77-11ea-8085-9cb654b8ed1e_1   0.19%               84MiB / 32GiB       0.26%               0B / 0B             6.21GB / 2.65MB     5

</code></pre>
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
<pre><code>
[logview@D21117U04-62-64 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
</code></pre>
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
<pre><code>
[logview@D21117U04-62-64 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
</code></pre>
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhangxingdeppon** [comment]
@kubernetes/sig-apps-bugs

**Comment by zq-david-wang** [comment]
If I remember it correct, docker stats changed memory usage from "total memory usage" to "rss memory usage", you may  need to check container_memory_rss usage from cadvisor against docker stats
working set memory is a metrics indicating the memory usage of rss and cache which is currently used

**Comment by zhangxingdeppon** [comment]
@zq-david-wang yes, you're right, the `container_memory_rss` value equal the ` docker stats MEM USAGE ` value, but not `container_memory_usage_bytes`, the idea perfectly resolved my doubt, thank you very much.
