### ISSUE TITLE
Resizing PVC failed using flexvolume

### ISSUE THREAD

**Issue by windayski** [kubernetes/kubernetes#85504]
**What happened**:

I am trying to resize a pvc using flexvolume plugin, but it looks like something wrong that the flexvolume plugin didn't get expandvolume call.
And it got a expandfs call only.

**What you expected to happen**:

The flexvolume plugin get expandvolume and expandfs call.

**How to reproduce it (as minimally and precisely as possible)**:

Edit a flexvolume PVC's yaml to increate the capacity of it and waiting a flexvolume plugin to resize it.

**Anything else we need to know?**:

The flexvolume plugin installed correctly on every node. And it and its config files are mounted into kube-controller-manger pod on masters.
The plugin works correctly for attach, detach, mount, umount.

After I edited the PVC yaml and increase the capacity of PVC, I checked the kube-controller-manager log.
And I found a log showed the controller-manager got a noop volume plugin.

```
 plugins.go:929] FindExpandablePluginBySpec(530778de-ed3b-441c-a7f7-104262351c69) -> returning noopExpandableVolumePluginInstance
```

So I glanced at the code of k8s, It looks like VolumeExpandController cannot get flexvolume plugins since it didn't call the GetDynamicPluginProber function.
Only attach/detach controller call the GetDynamicPluginProber and get flexvolume plugins.

```
// GetDynamicPluginProber gets the probers of dynamically discoverable plugins
// for the attach/detach controller.
// Currently only Flexvolume plugins are dynamically discoverable.
func GetDynamicPluginProber(config kubectrlmgrconfig.VolumeConfiguration) volume.DynamicPluginProber {
	return flexvolume.GetDynamicPluginProber(config.FlexVolumePluginDir, exec.New() /*exec.Interface*/)
}
```

As the below codes showed, expc.volumePluginMgr.InitPlugins(plugins, nil, expc) function uses nil as the second parameter DynamicPluginProber. So the ExpandController did not dectect and call the plugins that support expand volume and using noopExpandableVolumePluginInstance instead.

```
func NewExpandController(
	kubeClient clientset.Interface,
	pvcInformer coreinformers.PersistentVolumeClaimInformer,
	pvInformer coreinformers.PersistentVolumeInformer,
	cloud cloudprovider.Interface,
	plugins []volume.VolumePlugin) (ExpandController, error) {

	expc := &expandController{
		kubeClient: kubeClient,
		cloud:      cloud,
		pvcLister:  pvcInformer.Lister(),
		pvcsSynced: pvcInformer.Informer().HasSynced,
		pvLister:   pvInformer.Lister(),
		pvSynced:   pvInformer.Informer().HasSynced,
	}

	if err := expc.volumePluginMgr.InitPlugins(plugins, nil, expc); err != nil {
		return nil, fmt.Errorf("Could not initialize volume plugins for Expand Controller : %+v", err)
	}
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.3

**Comment by neolit123** [comment]
@huchengze you opened a couple of similar PRs
https://github.com/kubernetes/kubernetes/pull/85568
https://github.com/kubernetes/kubernetes/pull/85569

please close one of them, i assume https://github.com/kubernetes/kubernetes/pull/85568 is the one to look at?

if you want to get a faster review please ask in the #sig-storage channel of the k8s slack.

**Comment by huchengze** [comment]
@neolit123 These PRs are belong to different branchs.Should I close one of them?

**Comment by neolit123** [comment]
ok, i didn't see that.

please add release notes to both of them instead of `NONE`.
something like a single sentence that explains the bug fix.

**Comment by huchengze** [comment]
@neolit123 Thanks for telling me this. It's my second PR,there are so many things that I don't know.

**Comment by huchengze** [comment]
@neolit123 Thanks for telling me this. It's my second PR,there are so many things that I don't know.

**Comment by neolit123** [comment]
@huchengze 

instead of writing this in the release note:
> kubernetes:release-1.14
>kubernetes:master

write something like:
> fix a bug in PVC resize when using flexvolume

i will run tests on your PRs, but sig-storage (a k8s group) still need to give their approval.

**Comment by neolit123** [comment]
another question here is why only backporting this fix the 1.14 branch?

**Comment by huchengze** [comment]
@neolit123 I fixed this bug with my  colleague，so we decided that I create the PRs for 1.14 and master, 1.15 and 1.16 are his.

**Comment by msau42** [comment]
The general process is to make the change first in master, and then create cherry-picks to release branches.  Also @gnufied can you clarify if controller expand is something we want to support for flexvolume? The current plan is to remove support for flexvolumes in controller-manager: https://github.com/kubernetes/kubernetes/issues/78737

/assign @gnufied
