### ISSUE TITLE
Move validation to be per-API-version

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8550]
Validation as it exists today is pretty wrong - it tracks internal types.  Once we have long-term support for v1 API and are deep into v2 rework, the validation errors that are produced for v1 will be less and less useful.

We've gone back and forth about this but have not yet come up with a good answer on how to do this generically.  I propose we just move it to be per-version, same as defaulting.

Given that v1beta[12] are on the block right now and v1beta3 will be soon, this is the right time.  The same day we delete v1beta3 we should move pkg/api/validation into v1 and make it use versioned types.

Yes, it will be tedious to make changes, but I think that is the cost of having multiple versioned APIs in support cycles.

**Comment by nikhiljindal** [comment]
My impression was that we have decided that we want to go this path.
Its not part of 1.0 since that will have just one API version: https://github.com/GoogleCloudPlatform/kubernetes/issues/3084#issuecomment-100033527

**Comment by hurf** [comment]
Agree with @thockin , put validation on internal structs also looks odd to me. I think better to validate template itself for each version. Though #3084 may not be an issue now, it will come out along with v2, sooner or later we had to resolve this problem. I guess @nikhiljindal 's concern is mainly about limited timeline?

**Comment by bgrant0607** [comment]
I think we have agreed in principle that validation should be versioned. I don't see this happening before 1.0, however. We should do it before introducing the v2 api.

See also #3084, #5889, #8116, #6210, #1451

@lavalamp @smarterclayton

**Comment by thockin** [comment]
That's fine, my point was we should do it after v1b3 dies and before v2b1
is born :)

**Comment by nikhiljindal** [comment]
cc @caesarxuchao

**Comment by bgrant0607** [comment]
Ref #8190 so that it's on my "v2" radar.

**Comment by sftim** [comment]
Can I check: is this issue still relevant? If it is, how does it manifest? (eg: as maintenance toil for contributors)

**Comment by thockin** [comment]
What we have is "obviously" wrong but works in practice.  We have very few places where the field-path differs between API versions, so special-casing those works "well enough".  It's smelly but not the worst smelling hunk of code we have.  Doing it per-version would have a LOT of duplicated-but-identical code.

If/when we have a v2 of something major, we may want to revisit this.  Hopefully by then we will have declarative validation for all but the most bespoke logic.  Then we have to keep the decalarations in sync across API versions, but hopefully we can automate most of that.
