### ISSUE TITLE
NoNamespaceKeyFunc doesn't need Context parameter

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#85514]
**What would you like to be added**:
The Context parameter is used to obtain namespace.
However, NoNamespaceKeyFunc is not concerned with namespace.

**Why is this needed**:
Context parameter can be dropped.

**Comment by liggitt** [comment]
we don't really need an issue to track this. keeping the signature consistent between NamespaceKeyFunc and NoNamespaceKeyFunc is reasonable

/close
