### ISSUE TITLE
Cloning volumes across different namespaces

### ISSUE THREAD

**Issue by SVronskiy** [kubernetes/kubernetes#85519]
**What would you like to be added**:
Please provide oportunity of cloning volumes across different namespaces.

**Why is this needed**:
According to [this article](https://kubernetes.io/blog/2019/06/21/introducing-volume-cloning-alpha-for-kubernetes/) cloning to another namespace is not possible.

We make daily copy of persistent data in production kubernetes to dev kubernekes cluster, then we need to make about 20 clones of those files to use them in separated namespaces for separated development environments.

**Comment by SVronskiy** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by zhucan** [comment]
@SVronskiy Is it possible to support cross-storage pool cloning in the future?

**Comment by SVronskiy** [comment]
> @SVronskiy Is it possible to support cross-storage pool cloning in the future?

Currently are able to create PVC snapshot/clone in the same namespace using OpenEBS CSI, Portworx CSI. We need cross namespace cloning of the same data storage, which uses copy-on-write (COW) features. I have no idea why we should need cross-storage pool cloning, have no idea how it could be realized.

**Comment by zhucan** [comment]
we want to store volume in a data pool and store snapshot in other pool, our custom need this function. @SVronskiy

**Comment by SVronskiy** [comment]
> we want to store volume in a data pool and store snapshot in other pool, our custom need this function. @SVronskiy

[OpenEBS cStor](https://docs.openebs.io/docs/next/ugcstor.html#snapshot-and-clone-of-a-cStor-volume), [Linstor CSI](https://github.com/LINBIT/linstor-csi/blob/master/examples/k8s/pvc-from-snapshot.yaml)  supports this,

**Comment by zhucan** [comment]
OpenEBS supports it by Velero

**Comment by msau42** [comment]
cc @j-griffith @xing-yang @yuxiangqian

**Comment by xing-yang** [comment]
Here's a new KEP for namespace transfer: https://github.com/kubernetes/enhancements/pull/1555
