### ISSUE TITLE
How to use Kubernetes directly as CI system?

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#85547]
**What would you like to be added**:

* Builds that don't produce images
* Jobs that can run more than once

**Why is this needed**:

Not all build artifacts are Docker images. Sometimes, you want to publish a different kind of artifact with Kubernetes, or just run some operational commands. Kubernetes is quite close to being a fully capable CI system in its own right, and I think we should push it over the line with minor tweaks to resources and a bit of documentation on best practices.

Continuous Integration duties are traditionally delegated to external systems like Jenkins, Travis, GitLab CI, Circle, etc. But Kubernetes actually has Web hooks for triggering image builds. If your product is a JAR, then you can hack a basic CI setup by pushing the JAR to your Maven repository as a side effect of an image build, and then later cleaning up the unneeded image.

Another way is to generate Jobs with different UUIDs in their names, with the jobs doing the JAR (or GEM or TAR ball or whatever) work.

Some users will want to continue using external CI systems, for maturation, redundancy, and other reasons. But I think it would streamline software development if we could reuse Kubernetes for this capability, rather than having to maintain Jenkins servers. I'd rather spend time writing code!

**Comment by dims** [comment]
you are describing prow :) https://github.com/kubernetes/test-infra/tree/master/prow

/close
