### ISSUE TITLE
Create e2e tests for Ephemeral Containers

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#85545]
This issue is to discuss an e2e testing plan for Ephemeral Containers.

/sig node

**Comment by jiahuif** [comment]
As a first step towards this issue, I am planning to create node-e2e tests (under `test/e2e_node`) to verify the following:

- With a running pod
    - client adds a valid EphemeralContainer resource, and the ephemeral container starts
    - from the ephemeral container, list processes of itself and other containers, and then signal other processes (if `shareProcessNamespace` is `true`)
    - from the ephemeral container, ping & curl other containers
    - try to read/write to stdin/stdout of the ephemeral container
    - verify resource request/limit values against calculated expectations
    - check oom scores of processes in the ephemeral container
    - verify volume mounts
    - restarts according to policy, when process exits
    - client tries to add EphemeralContainer resource with ports (should be rejected)
    - client tries to add EphemeralContainer resource with probes (should be rejected)
    - client tries to add EphemeralContainer resource with resources (should be rejected)
    - client tries to add EphemeralContainer resource with securityContext (should be rejected)
    - removes the ephemeral container, and the ephemeral container is stopped and deleted
    - adds multiple ephemeral containers, should all start

- With pod of non-running status
    (TBD)

**Comment by verb** [comment]
@jiahuif Awesome, thanks! This is a great start, here are some things to look out for:

>   * from the ephemeral container, list processes of itself and other containers, and then signal other processes (if `shareProcessNamespace` is `true`)

Visibility should work, but I expect signaling to fail without `CAP_SYS_PTRACE` which is not currently allowed.

>   * verify volume mounts

iirc @msau42 was interested in how this would be tested for ephemeral containers. Can you point us towards any examples that would help us get started?

>   * restarts according to policy, when process exits

Ephemeral containers will never restart (and the policy should always be never)

>   * client tries to add EphemeralContainer resource with ports (should be rejected)
>   * client tries to add EphemeralContainer resource with probes (should be rejected)
>   * client tries to add EphemeralContainer resource with resources (should be rejected)
>   * client tries to add EphemeralContainer resource with securityContext (should be rejected)

These will be denied by the api server without ever making it to the kubelet, so they are better tested in the apiserver integration tests (and I think they are already).

>   * removes the ephemeral container, and the ephemeral container is stopped and deleted

Removing ephemeral containers is not currently allowed.

/assign @jiahuif

**Comment by jiahuif** [comment]
Validation of ephemeralContainers is well tested in `pkg/apis/core/validation/validation_test.go`
Testing of removing ephemeral containers is in `TestPodUpdateEphemeralContainers`, `test/integration/pods/pods_test.go`
