### ISSUE TITLE
kubectl pods --watch no longer shows pod status

### ISSUE THREAD

**Issue by guice** [kubernetes/kubernetes#85551]
**What happened**:

`kubectl get pods -w` for a watch stream of pod status. The resulting watch status no longer shows the pod's progressive status:
```
➜  services kubectl get pods -w
NAME                            READY   STATUS        RESTARTS   AGE
search-fpm-7c8c74985b-xz6vp     0/2     Terminating   0          23m
search-fpm-d46fc96fb-7vvwv      2/2     Running       0          23s
search-fpm-d46fc96fb-98btg      2/2     Running       0          39s
search-nginx-5d977f5c94-7pcps   1/1     Running       0          32s
search-search-update-l88vc      2/2     Running       0          23m
NAME                                 AGE
search-fpm-7c8c74985b-xz6vp     23m
search-fpm-7c8c74985b-xz6vp     23m
```

**What you expected to happen**:

I expected a ready, status, etc.. stream along with the additional watching updates.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl get pods -w` and watch a pod stream.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): macOS Catalina, 10.15.1 (19B88)

@kubernetes/sig-cli-bugs

**Comment by guice** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/71548 in 1.15
