### ISSUE TITLE
metrics-server error  unable to fetch node metrics for node "": no metrics known for node

### ISSUE THREAD

**Issue by zhangyu84848245** [kubernetes/kubernetes#85560]
Metric server I used -- TLS cert file, -- TLS private key file, -- kubelet certificate authority configuration option in the production environment, and the following error occurred. 
I know adding the --kubelet-insecure-tls option can solve this problem, 
but I need to configure the certificate in the production environment.

[root@centos-1 ~]# cat /usr/local/k8s-metrics-server/metrics-server-error.log

I1122 22:00:19.566672       1 manager.go:95] Scraping metrics from 0 sources
I1122 22:00:19.569340       1 manager.go:148] ScrapeMetrics: time: 1.704µs, nodes: 0, pods: 0
I1122 22:00:19.776788       1 secure_serving.go:116] Serving securely on [::]:4443
I1122 22:00:20.069642       1 log.go:172] http: TLS handshake error from 10.10.37.0:47546: EOF
I1122 22:00:20.074065       1 log.go:172] http: TLS handshake error from 10.10.37.0:47548: EOF
I1122 22:00:20.077587       1 log.go:172] http: TLS handshake error from 10.10.37.0:47550: EOF
I1122 22:00:20.270201       1 log.go:172] http: TLS handshake error from 10.10.37.0:47552: EOF
I1122 22:00:21.179216       1 log.go:172] http: TLS handshake error from 10.10.37.0:47554: EOF
E1122 22:00:32.770012       1 reststorage.go:135] unable to fetch node metrics for node "centos-2": no metrics known for node
E1122 22:00:32.770688       1 reststorage.go:135] unable to fetch node metrics for node "centos-3": no metrics known for node
E1122 22:00:32.775982       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/monitoring-influxdb-79fc5d45cc-m6zl7: no metrics known for pod
E1122 22:00:32.776069       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/metrics-server-6b55bff68-cmv6l: no metrics known for pod
E1122 22:00:32.776091       1 reststorage.go:160] unable to fetch pod metrics for pod default/tomcat-deployment-6fbcc44698-d9gq2: no metrics known for pod
E1122 22:00:32.776108       1 reststorage.go:160] unable to fetch pod metrics for pod default/tomcat-deployment-6fbcc44698-zhftk: no metrics known for pod
E1122 22:00:32.776124       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/heapster-bc75965-mgqbq: no metrics known for pod
E1122 22:00:32.776140       1 reststorage.go:160] unable to fetch pod metrics for pod kube-system/monitoring-grafana-6746cc64c4-p87xx: no metrics known for pod
E1122 22:00:32.776156       1 reststorage.go:160] unable to fetch pod metrics for pod kubernetes-dashboard/kubernetes-dashboard-b65488c4-gn5zh: no metrics known for pod
E1122 22:00:32.776172       1 reststorage.go:160] unable to fetch pod metrics for pod kubernetes-dashboard/dashboard-metrics-scraper-76585494d8-64mm2: no metrics known for pod

My metrics-server-deployment.yaml file is as follows

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      - name: metrics-server-certs
        secret:
          secretName: metrics-server-certs
      containers:
      - name: metrics-server
        image: mirrorgooglecontainers/metrics-server-amd64:v0.3.6
        #image: k8s.gcr.io/metrics-server-amd64:v0.3.6
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 5m
            memory: 50Mi
        args:
          - --cert-dir=/tmp
          - --secure-port=4443
          - --tls-cert-file=/certs/metrics-server.pem
          - --tls-private-key-file=/certs/metrics-server-key.pem
          - --kubelet-certificate-authority=/certs/ca.pem
          - --v=2
          - --logtostderr=false
          - --kubelet-port=10250
          - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
          - --metric-resolution=60s
        ports:
        - name: main-port
          containerPort: 4443
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
        - name: metrics-server-certs
          mountPath: /certs
      nodeSelector:
        beta.kubernetes.io/os: linux

kube-apiserver enables  aggregation-layer  and  Use separate certificate and Ca

--requestheader-client-ca-file=/usr/local/k8s-certs/aggregation-layer/ca.pem \
--requestheader-allowed-names=k8s-aggregator \
--requestheader-extra-headers-prefix=X-Remote-Extra- \
--requestheader-group-headers=X-Remote-Group \
--requestheader-username-headers=X-Remote-User \
--proxy-client-cert-file=/usr/local/k8s-certs/aggregation-layer/aggregator.pem \
--proxy-client-key-file=/usr/local/k8s-certs/aggregation-layer/aggregator-key.pem \
--enable-aggregator-routing=true \

**Comment by zhangyu84848245** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      - name: metrics-server-certs
        secret:
          secretName: metrics-server-certs
      containers:
      - name: metrics-server
        image: mirrorgooglecontainers/metrics-server-amd64:v0.3.6
        #image: k8s.gcr.io/metrics-server-amd64:v0.3.6
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 5m
            memory: 50Mi
        args:
          - --cert-dir=/tmp
          - --secure-port=4443
          - --tls-cert-file=/certs/metrics-server.pem
          - --tls-private-key-file=/certs/metrics-server-key.pem
          - --kubelet-certificate-authority=/certs/ca.pem
          - --v=2
          - --logtostderr=false
          - --kubelet-port=10250
          - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
          - --metric-resolution=60s
        ports:
        - name: main-port
          containerPort: 4443
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
        - name: metrics-server-certs
          mountPath: /certs
      nodeSelector:
        beta.kubernetes.io/os: linux

**Comment by tedyu** [comment]
Which release of k8s are you using ?

**Comment by Trackhe** [comment]
same problem i m using latest version (17.0)

**Comment by i542873057** [comment]
> same problem i m using latest version (17.0)

do you resoloved the problem?I have the same case

**Comment by Trackhe** [comment]
@i542873057 yes i have. but i m not sure what was the solution.

metrixserver deployment yml.

            - '--kubelet-insecure-tls'
            - '--kubelet-preferred-address-types=InternalIP'

i think

**Comment by rossigee** [comment]
ftr, @Trackhe workaround fixed the issue for me too.

Without `--kubelet-preferred-address-types=InternalIP`, it fails as internal name resolution from node name to internal IP address doesn't work...

```
unable to fully scrape metrics from source kubelet_summary:masternode-0003: unable to fetch metrics from Kubelet masternode-0003 (masternode-0003): Get https://masternode-0003:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup masternode-0003 on 10.43.0.10:53: no such host
```

And without `--kubelet-insecure-tls`, it fails as there is the node's internal IP is not listed in the certificate presented by kubelet on the node...

```
unable to fully scrape metrics from source kubelet_summary:worker-0001: unable to fetch metrics from Kubelet worker-0001 (10.99.0.101): Get https://10.99.0.101:10250/stats/summary?only_cpu_and_memory=true: x509: cannot validate certificate for 10.99.0.101 because it doesn't contain any IP SANs
```

The cluster this happened on is version 1.17.5 deployed with Rancher 2.4.2.

**Comment by muthu31kumar** [comment]
> I am also running to the same issue with v1.18.3. I am happy to change to older version if needed?
> 
> here my configuration:
> - --cert-dir=/tmp
> - --secure-port=4443
> - --kubelet-insecure-tls
> - --kubelet-preferred-address-types=InternalIP
> image: k8s.gcr.io/metrics-server-amd64:v0.3.6
> 
> I0610 21:32:49.398586 1 serving.go:312] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
> I0610 21:32:49.798250 1 secure_serving.go:116] Serving securely on [::]:4443
> E0610 21:33:25.079358 1 reststorage.go:135] unable to fetch node metrics for node "jainmnsh2c.mylabserver.com": no metrics known for node
> E0610 21:33:25.079393 1 reststorage.go:135] unable to fetch node metrics for node "jainmnsh3c.mylabserver.com": no metrics known for node
> E0610 21:33:25.079403 1 reststorage.go:135] unable to fetch node metrics for node "jainmnsh1c.mylabserver.com": no metrics known for node
> E0610 21:33:35.811334 1 reststorage.go:160] unable to fetch pod metrics for pod default/db-cbf488c85-n6wb5: no metrics known for pod
> E0610 21:33:35.811367 1 reststorage.go:160] unable to fetch pod metrics for pod default/busybox-sleep: no metrics known for pod
> E0610 21:33:36.970485 1 reststorage.go:160] unable to fetch pod metrics for pod default/db-cbf488c85-n6wb5: no metrics known for pod
> E0610 21:33:36.970509 1 reststorage.go:160] unable to fetch pod metrics for pod default/busybox-sleep: no metrics known for pod

Yes. Am too facing issues with the same error on my both K8 cluster running with v1.18.3 and v1.17.3

Any help is appreciated..

**Comment by rodrisbach** [comment]
Hi @muthu31kumar I had the same problem and I resolved it using the following arguments on my deployment:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64:v0.3.3
        imagePullPolicy: IfNotPresent
        args:
        - /metrics-server
        - --kubelet-insecure-tls
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP
        ports:
        - name: main-port
          containerPort: 4443
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: "amd64"
`
I hope it helps you

**Comment by muthu31kumar** [comment]
> Hi @muthu31kumar I had the same problem and I resolved it using the following arguments on my deployment:
> apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: metrics-server
> namespace: kube-system
> labels:
> k8s-app: metrics-server
> spec:
> selector:
> matchLabels:
> k8s-app: metrics-server
> template:
> metadata:
> name: metrics-server
> labels:
> k8s-app: metrics-server
> spec:
> serviceAccountName: metrics-server
> volumes:
> # mount in tmp so we can safely use from-scratch images and/or read-only containers
> - name: tmp-dir
> emptyDir: {}
> containers:
> - name: metrics-server
> image: k8s.gcr.io/metrics-server-amd64:v0.3.3
> imagePullPolicy: IfNotPresent
> args:
> - /metrics-server
> - --kubelet-insecure-tls
> - --cert-dir=/tmp
> - --secure-port=4443
> - --kubelet-preferred-address-types=InternalIP
> ports:
> - name: main-port
> containerPort: 4443
> protocol: TCP
> securityContext:
> readOnlyRootFilesystem: true
> runAsNonRoot: true
> runAsUser: 1000
> volumeMounts:
> - name: tmp-dir
> mountPath: /tmp
> nodeSelector:
> beta.kubernetes.io/os: linux
> beta.kubernetes.io/arch: "amd64"
> 
> I hope it helps you

Thanks @rodrisbach. It is resolved.

**Comment by arocki7** [comment]
Adding `--kubelet-preferred-address-types=InternalIP` to the args solved the problem for me.
