### ISSUE TITLE
[Azure loadbalancer] internal LB service stuck in pending due to not able to previous delete public IP Address

### ISSUE THREAD

**Issue by tdihp** [kubernetes/kubernetes#85565]
**What happened**:
Creating an internal-loadbalancer service in AKS, the service stuck in pending.
controller-manager log shows:

```
I1123 03:11:21.220367       1 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"<masked>", Name:"<masked>", UID:"<masked>", APIVersion:"v1", ResourceVersion:"21356219", FieldPath:""}): type: 'Normal' reason: 'DeletingLoadBalancer' Deleting load balancer
E1123 03:11:21.572294       1 azure_backoff.go:348] processHTTPRetryResponse: backoff failure, will retry, err=network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/<masked>/resourceGroups/<masked>/providers/Microsoft.Network/publicIPAddresses/<masked> can not be deleted since it is still allocated to resource /subscriptions/<masked>/resourceGroups/<masked>/providers/Microsoft.Network/loadBalancers/kubernetes/frontendIPConfigurations/<masked>. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
```

Saw "kubernetes" loadbalancer rules not deleted for this public IP address.

After we removed the public IP config, the healthcheck and the rule, the service got IP address successfully.

**What you expected to happen**:
controller-manager to remove the associated ip address, LB rule correctly.

**How to reproduce it (as minimally and precisely as possible)**:
not reproduced yet.

**Anything else we need to know?**:
The new service is using internal loadbalancer, the original public IP supposed to be a public loadbalancer, however we do not remenber if it was the case.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.8
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): unrelated
- Kernel (e.g. `uname -a`): unrelated
- Install tools: unrelated
- Network plugin and version (if this is a network-related bug): unrelated
- Others:

**Comment by tdihp** [comment]
@kubernetes/sig-cloud-provider-bugs

**Comment by feiskyer** [comment]
This is a known issue that sometimes the LB resources are not fully cleanup. The issue would be resolved by service finalizer, which would be GA on 1.17. Could you upgrade the cluster when it’s released?

**Comment by tdihp** [comment]
The issue is mitigated by cleanup the loadbalancer. Closing and will reopen if occured again in >1.17

**Comment by akingscote** [comment]
Im finding this problem when trying to use a private AKS cluster with internal load balancer. Not sure what you mean by cleaning up. 
Hopefully you dont mean:
https://docs.microsoft.com/en-us/azure/load-balancer/configure-load-balancer-outbound-portal#clean-up-resources
