### ISSUE TITLE
Add missing EncodePrivateKeyPEM utility function to kubeadm/app/util/pkiutil

### ISSUE THREAD

**Issue by rajathagasthya** [kubernetes/kubernetes#85576]
**What happened**:

Issue #71004 and PR #73198 moved cert related utility functions from client-go to `kubeadm/app/util/pkiutil`, but missed moving the `EncodePrivateKeyPEM` function to `pkiutil` (in the process [breaking](https://github.com/kubernetes/kubernetes/pull/73198#issuecomment-537644205) client-go public interface). A subsequent PR #71896 removed the `EncodePrivateKeyPEM` function from client-go. This breaks all of the downstream consumers of client-go because the function now can't be found anywhere.

Can we add it back to `kubeadm/app/util/pkiutil`? I'm happy to put in a PR. 

**What you expected to happen**:

APIs to remain stable and if need to be reorganized add a deprecation notice instead of breaking. 

**How to reproduce it (as minimally and precisely as possible)**:

Checkout k/k earlier than v1.15.0. You can find that `EncodePrivateKeyPEM` is present in client-go. Checkout k/k v1.15.0 onwards and you cannot find the function anywhere.

**Comment by neolit123** [comment]
> APIs to remain stable and if need to be reorganized add a deprecation notice instead of breaking.

AFAIK originally some of these utils didn't have a public home, so the kubeadm maintainers moved them to client-go. api-machinery complained about that as some of these utils are quite generic and therefore they were moved them back to kubeadm.

but yes, breakages are bad.

yet, it's a fairly small utility function that only uses the standard library.
why no define it locally?
```
// encodePrivateKeyPEM returns PEM-encoded private key data
func encodePrivateKeyPEM(key *rsa.PrivateKey) []byte {
	block := pem.Block{
		Type:  RSAPrivateKeyBlockType,
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	}
	return pem.EncodeToMemory(&block)
}
```

> Can we add it back to kubeadm/app/util/pkiutil? I'm happy to put in a PR.

i'm hesitant about this because kubeadm does not need the function.

/remove-sig auth
/priority awaiting-more-evidence

**Comment by rajathagasthya** [comment]
@neolit123 Thanks for the response. I did copy paste it locally since it was a fairly trivial function, but just wanted to check if kubeadm needs it because everything else was copied into the generic `pkiutil` except this function. I can close this if you think this is not necessary.

**Comment by neolit123** [comment]
at this point i think it would be better to add it only when it's needed.
