### ISSUE TITLE
upgrade from etcd 3.1.12 to 3.2.24, all pods from my kubernetes cluster restarted

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#85589]
**What happened**:
upgrade from etcd 3.1.12 to 3.2.24, all pods from my kubernetes cluster restarted

**What you expected to happen**:
all pods not restarted
**How to reproduce it (as minimally and precisely as possible)**:
upgrade etcd  to 3.2.24

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> upgrade etcd to 3.2.24

hi,

- please describe your upgrade process in detail.
- what is your k8s version?
- what deployment tools are you using?

/remove-kind bug
/triage needs-information
