### ISSUE TITLE
kube-apiserver: failed to enable "DefaultStorageClass"

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/kubernetes#85608]
**What happened**:
I would like to use the `kube-apiserver` to enable the "`DefaultStorageClass`"-plugin, but I run into problems.
I installed the "`kube-apiserver`" though "`snap`" and I run the following command in the machine containing the master-node of the Kubernetes Cluster:
`sudo kube-apiserver --enable-admission-plugins=DefaultStorageClass`

Then I run into this error:
`Error: error creating self-signed certificates: mkdir /var/run/kubernetes: permission denied`

I cannot understand why it does not have permissions to do so, eve though I am running with `sudo`.

**What you expected to happen**:
The plugin `DefaultStorageClass` to get enabled.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run `sudo snap install kube-apiserver`
2. Run `sudo kube-apiserver --enable-admission-plugins=DefaultStorageClass`

**Anything else we need to know?**: None

**Environment**:
- Kubernetes version: 1.16.3
- Cloud provider or hardware configuration: 2 CPUs, 2Gb of RAM
- OS: Ubuntu 18.04.3 LTS
- Kernel: 4.15.0-70-generic
- Install tools: `snap`
- Network plugin and version (if this is a network-related bug): -
- Others: -

**Comment by liggitt** [comment]
> sudo kube-apiserver --enable-admission-plugins=DefaultStorageClass

This isn't an imperative command that you run to enable the admission plugin. That flag is something you would add to your existing kube-apiserver invocation, along with the TLS certificates required to serve securely. By not providing those, the apiserver tried to mint its own self-signed certificates at the default path (probably not what you want) and failed. I'm not familiar with the installation method, but it's possible the volume is read only, which would give a permission error even for root.

**Comment by LSmyrnaios** [comment]
@liggitt the documentation for `kube-apiserver` is poor, so I cannot understand how to use it properly.
I already submitted an issue there: https://github.com/kubernetes/website/issues/17862
As for the volume, it is writable, I am able to create files and directories as root.
