### ISSUE TITLE
HPA wrong namespace substitution

### ISSUE THREAD

**Issue by MrD2** [kubernetes/kubernetes#85607]
**What happened**: HPA engine requests wrong namespace reference for metric from custom metrics API

The Prometheus-Adapter pod receives a request for custom metrics with the wrong assigned namespace. 

```log
I1125 16:50:32.878242       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/default/metrics/avg_cpu_load_3m: (3.06389ms) 200 [[kube-controller-manager/v1.15.3 (linux/amd64) kubernetes/2d3c76f/horizontal-pod-autoscaler] 10.100.0.0:53130]
I1125 16:50:32.887760       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/load-test/metrics/nginx_ingress_controller_requests: (1.62237ms) 404 [[kube-controller-manager/v1.15.3 (linux/amd64) kubernetes/2d3c76f/horizontal-pod-autoscaler] 10.100.0.0:53130]
I1125 16:50:34.617394       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1?timeout=32s: (3.905606ms) 200 [[kube-controller-manager/v1.15.3 (linux/amd64) kubernetes/2d3c76f/generic-garbage-collector] 10.100.0.0:53130]
I1125 16:50:34.986065       1 wrap.go:42] GET /healthz: (2.249818ms) 200 [[kube-probe/1.15] 10.100.8.1:37924]
I1125 16:50:35.129393       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1?timeout=32s: (3.240788ms) 200 [[kube-controller-manager/v1.15.3 (linux/amd64) kubernetes/2d3c76f/resourcequota-controller] 10.100.0.0:53130]
I1125 16:50:37.097520       1 wrap.go:42] GET /healthz: (111.324µs) 200 [[kube-probe/1.15] 10.100.8.1:38002]
I1125 16:50:38.754492       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (7.050375ms) 200 [[Go-http-client/2.0] 10.100.0.0:53108]
I1125 16:50:38.756195       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (8.649433ms) 200 [[Go-http-client/2.0] 10.100.0.0:53108]
I1125 16:50:38.760368       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (6.993254ms) 200 [[Go-http-client/2.0] 10.100.0.0:53108]
I1125 16:50:38.764002       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (8.408427ms) 200 [[Go-http-client/2.0] 10.100.0.0:53108]
I1125 16:50:38.768689       1 wrap.go:42] GET /apis/custom.metrics.k8s.io/v1beta1: (14.107673ms) 200 [[Go-http-client/2.0] 10.100.0.0:53108]
```

The request to **/apis/custom.metrics.k8s.io/v1beta1/namespaces/load-test/metrics/nginx_ingress_controller_requests** is replaced with the wrong namespace.

**What you expected to happen**: correct url form

Here the namespace should be replaced by:
The request to **/apis/custom.metrics.k8s.io/v1beta1/namespaces/kube-system/metrics/nginx_ingress_controller_requests** as is defined under HPA.specs.metrics.type.object.describedObject.name

As we can see in the image below, the query is correctly reported by the prometheus server
![image](https://user-images.githubusercontent.com/5084445/69560966-e8a2db00-0fac-11ea-9e7d-d231396df334.png)

**How to reproduce it (as minimally and precisely as possible)**:
Using an stable/nginx-ingress graph with Prometheus metrics activated with stable/prometheus-adapter

Scalling Component:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: load-test

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: load-test
  name: curl-requester
  labels:
    app: requester
spec:
  selector:
    matchLabels:
      app: curl-requester
      aim: load-test
  replicas: 5
  template:
    metadata:
      labels:
        app: curl-requester
        aim: load-test
    spec:
      containers:
      - name: bash-curl
        image: cosmintitei/bash-curl
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        command:
        - bash
        - "/scripts/bash.sh"
        volumeMounts:
        - name: bash
          mountPath: /scripts
      volumes:
      - name: bash
        configMap:
          name: bash-command
          defaultMode: 0777

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bash-command
  namespace: load-test
data:
  bash.sh: |
    while true
    do
      curl -s 'http://test-nginx-guestbook.foo/guestbook.php?cmd=get&key=messages' \
        -H 'Connection: keep-alive' -H 'Accept: application/json, text/plain, */*' \
        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36' \
        -H 'Referer: http://test-nginx-guestbook.foo/' \
        -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.9,pt;q=0.8,fr;q=0.7' \
        --compressed --insecure > dev/null
    done

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bash-command
  namespace: load-test
  labels:
    app: requester
spec:
  minReplicas: 1
  maxReplicas: 1000
  metrics:
    - type: Object
      object:
        metric:
          name: nginx_ingress_controller_requests
        describedObject:
          kind: Namespace
          name: kube-system
        target:
          type: Value
          value: 300
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: curl-requester
```

Add the custom metric to the Prometheus-Adapter ConfigMap
```yaml
    - seriesQuery: '{__name__="nginx_ingress_controller_requests",ingress= "frontend",status="200"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        as: "nginx_ingress_controller_requests"
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,ingress= "frontend",status="200"}[1m])) by (<<.GroupBy>>)
```

**Environment**:
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Openstack Magnum
- OS (e.g: `cat /etc/os-release`): fedora atomic 29

**NOTICE>**
Although i know this metric won't do what i want (a scaling http load request application) because the metric is not a rate off the requests from the pods. There seems to be a replacement error here in the custom.metrics.k8s.io API.

**Comment by liggitt** [comment]
I would not expect to be able to trigger a cross namespace request from an HPA object. Using the same namespace as the the HPA is what I would have expected.

**Comment by MrD2** [comment]
Yes, the HPA belongs to the same namespace as the deployment, but the metric does not.

Still, when he tries to get the metric it uses the namespace of the HPA instead of the kube-system.

In this case i want to scale the container pods so i can meet total X requests per second for for the namespace of said pods

**Comment by liggitt** [comment]
> Still, when he tries to get the metric it uses the namespace of the HPA instead of the kube-system.

That is what I would expect. Allowing an HPA to drive cross-namespace metrics requests is counter to the namespaced nature of the object, and is not a pattern that is generally supported. 

This may just be a documentation issue.

**Comment by MrD2** [comment]
The only thing i see is if i am confusing the external metrics with other thing:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#externalmetricsource-v2beta2-autoscaling

Although docs under [objectMetricSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#objectmetricsource-v2beta2-autoscaling) need to be more polished, mainly the [CrossVersionObjectReference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#crossversionobjectreference-v2beta2-autoscaling)
