### ISSUE TITLE
Run local-up-cluster.sh failed on ARM server as etcd version check can not pass.

### ISSUE THREAD

**Issue by zhlhahaha** [kubernetes/kubernetes#85600]
**What happened**:
When using /hack/local-up-cluster.sh to create a local cluster, always failed in etcd version check on ARM server.
**What you expected to happen**:
local-up-cluster.sh can run successfully.
**How to reproduce it (as minimally and precisely as possible)**:
Just run it on arm server.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 
Gitcommit 9905a33fd738a52d3f7ae73cf823d82a05720e33

**Comment by liggitt** [comment]
Fixed by #85601
