### ISSUE TITLE
Kubectl version --server should return the server version

### ISSUE THREAD

**Issue by MartinKaburu** [kubernetes/kubernetes#85614]
**What would you like to be added**:
I would like for `kubectl version --server` to return the server version as `kubectl version --client` returns the client version.

**Why is this needed**:
It will make it easier to write automating scripts for checking the server version.
It will maintain consistency as there already is a `--client` flag that returns the client version.

**Comment by liggitt** [comment]
--client is necessary as it prevents network requests which can hang or fail

it's not clear why a server specific flag is required

**Comment by liggitt** [comment]
passing --json gives you structured output you can parse deterministically to get the server version (or do `kubectl get --raw /version`)

**Comment by soltysh** [comment]
I agree with Jordan here, for your usecase I'd suggest using `kubectl version -oyaml` or `kubectl version -ojson` and parse whatever you need. This will ensure you a stable, machine parsable output.

**Comment by liggitt** [comment]
/close

per https://github.com/kubernetes/kubernetes/issues/85614#issuecomment-559037064
