### ISSUE TITLE
Use `kubectl exec -it POD-NAME /bin/sh` 30 seconds free to exit

### ISSUE THREAD

**Issue by ygqygq2** [kubernetes/kubernetes#85632]
How do I set it so it doesn't automatically quit?

![image](https://user-images.githubusercontent.com/17672440/69613299-4ea26780-106c-11ea-9c4a-9f3d4a8875f1.png)

**Comment by thockin** [comment]
This is not normal behavior.  My guess is that your container is restarting (maybe a failed livenessProbe), but there's not enough info here to triage.  Regardless, it doesn't seem like a bug in Kubernetes - I just ran a long exec (hours) with no problems.

If you have indications that it is something in Kubernetes - please reopen this with whatever data you can gather.
