### ISSUE TITLE
Support apiserver dry-run in kubectl

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#85652]
**What would you like to be added**:
We need to implement a consistent server-side "dry-run" flag in kubectl.

@apelisse proposed `--dry-run=server` to provide access to the apiserver's dry-run feature for GA, which re-uses the existing boolean flag, and leaves a path for `--dry-run=client`. The server-side behavior as in `--dry-run=server` would become the new default for `--dry-run`, since most kubectl users depend on the flag for dry-run validation in CI automation, which is most at danger of breaking. 

**Why is this needed**:
Currently, the `kubectl --dry-run` flag does its best client-side to do the right thing.

kubectl users often run `kubectl apply --dry-run --validate -f ...` for best-effort server-side validation locally or in CI (see https://github.com/kubernetes/kubernetes/issues/11488), and other kubectl users run `kubectl create configmap -dry-run --local --output yaml ...` for client-side dry-run for manifest generation (see https://github.com/kubernetes/kubernetes/issues/51475).

Tasks:
- [x] add `--dry-run=[client|server|none]` values
- [x] update existing kubectl commands that already support `--dry-run=client` to also support `--dry-run=server`
- [x] error when both `--dry-run=server` and `--local` are specified because they're incompatible
- [x] add `--dry-run=server` and `--dry-run=client` support to commands without any existing `--dry-run` support at all
  - [x] `kubectl delete`
  - [ ] `kubectl scale` pending https://github.com/kubernetes/kubernetes/issues/88274
  - [x] `kubectl replace`
  - [x] `kubectl taint`

Dry-run umbrella issues: https://github.com/kubernetes/enhancements/issues/576 https://github.com/kubernetes/kubernetes/issues/68514
Dry-run kep: https://github.com/kubernetes/community/blob/master/keps/sig-api-machinery/0015-dry-run.md
Dry-run initial issue: https://github.com/kubernetes/kubernetes/issues/11488

/sig api-machinery
/sig cli

**Comment by apelisse** [comment]
@seans3 @soltysh @smarterclayton Any opinion on that? We still haven't implemented "server-dry-run" for most commands beside `kubectl apply`. I'm suggesting `--dry-run=[server|client]` with client being the default for now, and potentially changing it later. WDYT? Happy to come to sig-cli next wednesday to talk aboutt it.

**Comment by smarterclayton** [comment]
We’d have to have backward compatibility for —dry-run=true and —dry-run, but other than that I don’t see too many issues.  What would it mean to change the default later on?  We have —local, if I pass —dry-run=server and —local should I get an error?  Can we use —local to modify dry run instead of making it multi-value?

**Comment by julianvmodesto** [comment]
> What would it mean to change the default later on?

Changing the default later would use more accurate server-side validation and more accurately match intent to validate a request. This shouldn't be breaking because the existing `--dry-run` flag requires an apiserver connection.

>  Can we use —local to modify dry run instead of making it multi-value?

`--dry-run` seems like a good fit because `--local` is not as proliferated, particularly for commands such as `create` and `apply`, whereas `--dry-run` is available for `apply` and `create`.

`set` is an example of a command with both `--local` and `--dry-run`. [These are the docs for the flags](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#set), and it looks like the requested behavior is overlapping:

> dry-run
> --
> If true, only print the object that would be sent, without sending it.

> local
> --
> If true, set image will NOT contact api-server but run locally.

Could we deprecate `--local` in favor of `--dry-run`/`--dry-run=true`/`--dry-run=client`?

**Comment by apelisse** [comment]
@kubernetes/sig-cli-maintainers

**Comment by julianvmodesto** [comment]
As discussed during the sig-cli meeting, we'll proceed with extending the existing flag to support `--dry-run=server`, which is available for `kubectl apply` and `kubectl create`.

/cc @soltysh 

We'll retain the existing default for backwards compatibility. We won't be using `--local` for server-side dry-run.

I'll update the dry-run KEP with this change.

**Comment by apelisse** [comment]
As a side-note: if we want to be perfectly backward-compatible on the `--dry-run` flag, going from boolean to string is not "that trivial":
`--dry-run=true`, `--dry-run=True`, `--dry-run=1` are all valid options for the boolean. And I'm probably missing some.

**Comment by apelisse** [comment]
Also, `--local` doesn't exist for all commands and has a slightly different semantic, so I don't think we should tie the behavior of the two. It might make sense to disallow `--local` with some values of `--dry-run` though.

**Comment by julianvmodesto** [comment]
>  going from boolean to string
https://github.com/kubernetes/kubernetes/blob/f229aa0ad65a0378645a68ebc7ca2bf65e4957e9/staging/src/k8s.io/cli-runtime/pkg/resource/mapper.go#L60
Looks like we'll convert [cmdutil's `func GetDryRun() string`](https://github.com/kubernetes/kubernetes/blob/08ef34a2b0ca2b3ceefea3bcf9dc387dc204c42b/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go#L501) to `func GetDryRun() bool`. [`cobra` uses `strconv.ParseBool`](https://github.com/spf13/pflag/blob/2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab/bool.go#L35), so we should call this for parsing truthy for client-side dry-run.

> It might make sense to disallow --local with some values of --dry-run though.

It looks like we can return a LocalResourceError if `--local` and `--dry-run=server` for subcommands like `kubectl set`

https://github.com/kubernetes/kubernetes/blob/f029700630b9a049d4ca07d4dd7661b7f5759cb0/staging/src/k8s.io/kubectl/pkg/cmd/set/set_image.go#L167-L184

**Comment by julianvmodesto** [comment]
Started to update the KEP https://github.com/kubernetes/enhancements/pull/1399

Looking at cli-runtime, it looks like `--local` doesn't pass the REST mapping. I'm not sure yet, but I think omitting the REST mapper doesn't call the apiserver at all, so `--dry-run=server` would never be passed. It seems like `--local` might be useful because of this, and we probably want to deprecate the `--dry-run=client` codepath entirely... Should we do this + track this?

https://github.com/kubernetes/kubernetes/blob/f229aa0ad65a0378645a68ebc7ca2bf65e4957e9/staging/src/k8s.io/cli-runtime/pkg/resource/mapper.go#L106

**Comment by julianvmodesto** [comment]
This change is being implemented.

The original PR is https://github.com/kubernetes/kubernetes/pull/86143, but it's quite big so we're splitting it into smaller changes, starting with https://github.com/kubernetes/kubernetes/pull/86408.

**Comment by riking** [comment]
> For backwards compatibility, we'll continue to default the value for --dry-run to --dry-run=client, which is equivalent to the existing behavior for --dry-run=true.
>
> The boolean values for --dry-run will be deprecated next release, then removed in 2 releases.
>
> The default value for --dry-run with the flag set and unspecified will be deprecated in the next release, then in 2 releases we will require that a value must be specified. Users must update any scripts to explicitly set --dry-run=client or --dry-run=server.

I'm unsure this is a long enough timeline for blog posts & stuff to get updated - you may need to target a large educational campaign to avoid widespread breakage.

I'd expect to live with the defaulting for at least a year.

**Comment by apelisse** [comment]
Thanks for your comment @riking. We're are going to update as much as we can, at least to the extend of "kubernetes" website, documentation, tests and references. I agree with you that there is going to be a long tail of things to be updated. With the current plan, this offers more than 6 months for this to happen. Obviously, we can reconsider in 6 months and adjust that as needed. The goal is to eventually make "server" the default, ideally we can make that happen in less than 1.5 years :-)

**Comment by riking** [comment]
With the context of that plan, it makes a lot more sense - should probably be included in the deprecation messaging, then!

**Comment by apelisse** [comment]
Thanks, I'll look at it

**Comment by julianvmodesto** [comment]
I'm going to close this one for now as done and file a follow up for `kubectl scale` since it's kind of blocked on https://github.com/kubernetes/kubernetes/issues/88274

Next is docs!

/close
