### ISSUE TITLE
kube-proxy should fail fast

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#8567]
If you launch kube-proxy in a manner where it cannot use iptables it should fail - rather than carry on .  It can be quite confusing otherwise - as the proxy is running but it will not actually re-route ips for publicIPs and so on. 

Lets add a precondition to kube-proxy startup which confirms iptables can be properly leveraged and accessible .

**Comment by thockin-cc** [comment]
Can you explain what you're actually seeing?  kube-proxy already exits if,
for example, it can not init iptables.

**Comment by jayunit100** [comment]
Simply put... if you launch kube proxy as non root... it doesn't do anything useful wWhen you try to implement public ips.

**Comment by thockin** [comment]
Fair enough.  Patches welcome for a very short period of time before code
freeze.  VERY short window.  Otherwise it will have to wait.

**Comment by thockin** [comment]
@jayunit100 is this something you're still thinking about?

**Comment by jayunit100** [comment]
Ah I haven't checked this for a while but I definitely think it should be done.
