### ISSUE TITLE
Scheduler does not clear nominatedNodeName on Pod when node is no longer valid

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/kubernetes#85677]
**What happened**:

Scheduler decided that it wants to schedule Pod P on Node N after preempting some pods from N.
It set the P.nominatedNodeName to N. After a while (before scheduling actually happened) node N was removed from the cluster.
Scheduler did not reset P.nominatedNodeName to empty value.

**What you expected to happen**:

I would expect scheduler to unset P.nominatedNodeName when the node is no longer valid.
The trivial reason for node not being valid any more is it is removed from the cluster. 
But there are more cases to cover. Out of the top of my head I may think of:
- extra Pod was scheduled to node and there is not enough resources any more
  - either scheduled by scheduler
  - or directly as static pod/daemonset
- node became unschedulable

**How to reproduce it (as minimally and precisely as possible)**:

We did not try to reproduce issue manually. Yet following setup should work.
- create cluster with nodes A and B.
- ensure all system pods are running on A. Fill up A so it does not have spare resources.
- add a low priority Pod L with long termination, with requests matching allocatable of B. It should be scheduled to B.
- add a high priority Pod H. It should get B as nominatedNodeName
- kill node B
- the H.nominatedNodeName will still point to B which is no longer in the cluster

**Anything else we need to know?**:

Current behavior does not play well with Cluster Autoscaler which assumes that Pod with nominatedNodeName will be scheduled in a while.
Therefore such pods do not trigger scale-up. If we can have P.nominatedNodeName set incorrectly for unbounded period of time CA will never
provision node for P to run.

**Environment**:
- Kubernetes version (use `kubectl version`):

We observed the behavior during presubmit tests which run k8s built from HEAD of master on 27.11.2019.

Versions logged in test log:
I1125 18:55:11.691] Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.0.1183+414202578ba1ad", GitCommit:"414202578ba1ad53a26bc5126b3828a3a410097e", GitTreeState:"clean", BuildDate:"2019-11-25T17:04:18Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
I1125 18:55:11.692] Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.0.1183+414202578ba1ad", GitCommit:"414202578ba1ad53a26bc5126b3828a3a410097e", GitTreeState:"clean", BuildDate:"2019-11-25T17:04:18Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
GCE

/sig scheduling

**Comment by MaciekPytel** [comment]
Another interesting case would be creating a new pod with pod antiaffinity blocking the pod with nominated node name from scheduling:
1. Fill up a cluster with pods, including a long-terminating low-priority pod A. 
2. Create high-priority pod B that has the same requests as A.
3. Create pod C with negligible resource requests and zonal topology pod antiaffinity matching pod B (and no other pods in the cluster).

What I'd expect:
- Pod C keeps pending, nominatedNodeName is cleared.
- Pod A is restarted on the same node it was running before.

I haven't actually tested this scenario, so I'm not sure what will actually happen. If @losipiuk's report is correct, this may be a more convenient way of reproducing the issue (no need to add / remove nodes, it's not important which pod will go to which node).

**Comment by denkensk** [comment]
@losipiuk  I'm not sure if we need to clear nominatedNodeName on Pod when node is no longer valid immediately.  And we have other logic to clear nominatedNodeName. 

-------
Reuse your example.
- create cluster with nodes A and B.
- ensure all system pods are running on A. Fill up A so it does not have spare resources.
- add a low priority Pod L with long termination, with requests matching allocatable of B. It should be scheduled to B.
- add a high priority Pod H. It should get B as nominatedNodeName
- kill node B
- the H.nominatedNodeName will still point to B which is no longer in the cluster
-------
After this, 
1.  The H will be scheduled again. Obviously it's going to fail.
2. The H will enter the preemption process and the `potentialNodes` is empty.  It will return itself as `nominatedPodsToClear`
https://github.com/kubernetes/kubernetes/blob/9474154012eedc547e1cfa58c4a8d5d0e3308290/pkg/scheduler/core/generic_scheduler.go#L342-L347
3. The preemption process will clean nominatedNodeName on the Pod H.
https://github.com/kubernetes/kubernetes/blob/9474154012eedc547e1cfa58c4a8d5d0e3308290/pkg/scheduler/scheduler.go#L489-L500

**Comment by losipiuk** [comment]
@denkensk when I have some time I will check if reproduction steps I describe actually work. But we surely observed pods with lingering nominatedNodeName which pointed to inexistent node, during our E2E tests.

Quick thought. The `Preempt()` method (https://github.com/kubernetes/kubernetes/blob/9474154012eedc547e1cfa58c4a8d5d0e3308290/pkg/scheduler/core/generic_scheduler.go#L328) 
has many return points. 
If it returned at the place you linked it seems `nominatedNodePool` should be cleared. 
But there are many return points below, which set the list of pods to be cleared to nil. 
Is it possible that for a pod to consistently exit from `Preempt` with one of those return points?

**Comment by denkensk** [comment]
@losipiuk  I think you are right.  Actually there are many return points to return nil.  I think maybe we need to clear the `nominatedNode` of the pod after the filter failed again and before the new preemption process to avoid potential risks.  WDYT? @ahg-g

**Comment by Huang-Wei** [comment]
I believe it's a bug as in old logic, e.g., v1.18.3, if the Pod (with nominatedNodeName set) cannot be scheduled and also preemption doesn't help (@denkensk nil potentialNodes is a corner case, it's more common the pod can't fit on all potentialNodes), it won't hit L413:

https://github.com/kubernetes/kubernetes/blob/2e7996e3e2712684bc73f0dec0200d64eec7fe40/pkg/scheduler/scheduler.go#L404-L413 

then in old recordingFailure logic, nominatedNodeName remains as is.

In the latest codebase, @ahg-g introduced a fix to combine setting nominatedNodeName as well update the pod's unschedulable condition. However, this doesn't help in this issue either as it ignores the case when the pod's nominatedNodeName is nil:

https://github.com/kubernetes/kubernetes/blob/c18bc7e9f7a27d7d197053d98c52896e1dc3bb3e/pkg/scheduler/scheduler.go#L389-L396

**Comment by Huang-Wei** [comment]
/reopen
as #91750 regresses - we need to come up with a complete fix.

**Comment by ahg-g** [comment]
what are the implications of not clearing the nominated node name?
