### ISSUE TITLE
Run scheduler benchmark tests in presubmit CI checks

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#85686]
**What would you like to be added**:
Run scheduler benchmark tests in presubmit CI checks.

**Why is this needed**:
The scheduler benchmark tests are relatively fast to run (~5min). They help us catch performance regressions. By running it in Prow jobs, we have a consistent environment to run the benchmark and to compare with.

To begin with, we can just run the benchmark tests and not necessarily compare the results with master branch. Later on, we can improve by comparing the results with historical average (e.g., average of last 10 runs). If the metrics exceeds the average for a certain threshold (e.g. 20%), we should fail the check.

### Background info
Currently we run benchmark as periodic job: [code](https://github.com/kubernetes/test-infra/blob/7acdd045f98d72e44120eaa053d594bcd273c0ba/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L346)

We need to also run it as part of presubmit, similar to the [pull-kubernetes-integration](https://github.com/kubernetes/test-infra/blob/7acdd045f98d72e44120eaa053d594bcd273c0ba/config/jobs/kubernetes/sig-testing/integration.yaml#L33) job. 

/sig scheduling
/sig testing
part of #81719

**Comment by liu-cong** [comment]
cc @draveness @alculquicondor

**Comment by liu-cong** [comment]
Credits to @draveness and @alculquicondor for bringing up the idea!
Some relevant comments: [1](https://github.com/kubernetes/kubernetes/issues/81719#issuecomment-558911442) and [2](https://github.com/kubernetes/kubernetes/issues/81719#issuecomment-559136248)

**Comment by SataQiu** [comment]
I am willing to help with this.

**Comment by liu-cong** [comment]
@SataQiu ,

Great! I will add details ASAP. Thanks!

**Comment by liu-cong** [comment]
@SataQiu , added some code links.

**Comment by alculquicondor** [comment]
@ingvagabund aren't you working on this?

**Comment by ingvagabund** [comment]
@alculquicondor I am not. IIRC, we were waiting until the suite is refactored and metrics are collected. We first need some referential values before we can say if a run of the suite over a PR is good enough or not. @liu-cong did I miss anything?

**Comment by BenTheElder** [comment]
I would prefer that we run this in postsubmit and have the SIG monitor the dashboard.

We can scale up running many more tests better by running them on-merge instead of on every potential commit pre-merge. There's far less to test this way, and much clearer signal. Just building all the code across N presubmits is getting rather expensive.

Doing this in postsubmit doesn't require any input from SIG testing. Please do contact us if you still intend to push this in presubmit though, and feel free to reach out for help setting the job.
/remove-sig testing.


Adding more presubmits also worsens our odds of merging due to flakiness in the jobs.

**Comment by alculquicondor** [comment]
Maybe @adtac could pick this up if it still makes sense

**Comment by BenTheElder** [comment]
cc @liggitt 

please see: #92937 ... we're not the most enthused about adding more jobs, I understand the desire to test this though

**Comment by adtac** [comment]
I'm more interested in having this periodically tested (similar to the kubemark?). Running the benchmarks as a presubmit might be a bit of an overkill.

**Comment by liggitt** [comment]
+1 to running as a periodic job

**Comment by liggitt** [comment]
it looks like https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler and https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf need some attention ... once those are green, let's think about whether they give the signal we need for this

**Comment by ahg-g** [comment]
The problem with those tests is that they take a very long time to run all the tests (likely in the order of an hour or more), and we keep adding more test cases. May be we should configure CI to run on selected ones only.

**Comment by adtac** [comment]
Tests with `500Nodes` in their name are a good fit IMO, so we could add that to the regex used in the `-run` argument. They're certainly smaller than the 5000-node tests (about 3-5x faster from what I've seen).
