### ISSUE TITLE
Not enough capacity to schedule Prometheus in kubemark5000

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#85683]
**Which jobs are failing**:
kubemark-5000

**Which test(s) are failing**:
Up and ClusterLoaderV2

**Since when has it been failing**:
11/20

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000

**Reason for failure**:

**Anything else we need to know**:

/sig scalability
/priority important-soon
/milestone v1.18
/assign

**Comment by oxddr** [comment]
`Unable to schedule monitoring/prometheus-k8s-0: no fit: 0/84 nodes are available: 1 node(s) were unschedulable, 83 Insufficient memory.; waiting` 

Was there any recent change to resource requirements for Prometheus?

**Comment by oxddr** [comment]
A little more context: Prometheus is scheduled in the main cluster, where hollow-nodes live. In kubemark-5000 most of nodes are utilized at ~90% (memory), leaving around ~2GB free. This is not enough for Prometheus (6 GB). It doesn't have a priority set, so it stays unscheduled, causing test to fail starup. 

I am curious why the test worked before and only started to fail recently.

**Comment by mm4tt** [comment]
@oxddr, could you post on update on this?
It seems to be still happening - https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000

**Comment by oxddr** [comment]
/retitle Not enough capacity to schedule Prometheus in kubemark5000

**Comment by oxddr** [comment]
This has been fixed already. 

/close
