### ISSUE TITLE
Make util/{goroutinemap,slice} usable outside k/k ?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#85692]
We would like to see github.com/kubernetes-csi/external-snapshotter project to use 1.16.x libraries. Issue: https://github.com/kubernetes-csi/external-snapshotter/issues/200 

One of the blockers is that this project depends on k/k . It uses the following util packages:

- k8s.io/kubernetes/pkg/util/goroutinemap
- k8s.io/kubernetes/pkg/util/slice

Can these packages moved to somewhere outside k/k so that these are reusable?

**Comment by tamalsaha** [comment]
/sig api-machienry
/sig storage

cc: @liggitt @dims @msau42 @saad-ali

**Comment by dims** [comment]
@tamalsaha if you want to propose moving these to k8s.io/utils, that's a good place since you say these are reusable. caution though ... we go through rigorous review of the API of anything that goes into k/utils ( https://github.com/kubernetes/utils/#criteria-for-adding-code-here ). I do encourage you to look through older PRs in that repo to see what we ask for typically and propose a PR in kubernetes/utils.

**Comment by tamalsaha** [comment]
What is the criteria for choosing between k8s.io/utils and https://github.com/kubernetes/apimachinery/tree/master/pkg/util ?

**Comment by xing-yang** [comment]
Seems to be a good idea to move goroutinemap and slice to k8s.io/utils.

**Comment by dims** [comment]
@tamalsaha - question to ask there is "is it really usable outside of kubernetes?"

**Comment by lavalamp** [comment]
IMO:
* goroutinemap: this needs a better name and to be context-aware before I'd want to support its interface long-term. https://godoc.org/golang.org/x/sync/singleflight is an alternative people could use (though it doesn't offer failure backoff).
* slice: this is a very confusing package. It's also only implemented for `string`. I would not want to support this long-term. If we decided it was actually useful (I'm skeptical its functionality is worth the import), I guess I'd expect it to be generated as we do for the `sets` package :/
