### ISSUE TITLE
k/k ships an invalid go.mod file

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#85693]
We are trying to update our k/* dependencies to 1.16.x using go.mod. One of the challenges we are facing is that k/k repo can't be imported via go.mod. We get the following error, when we tried:

```
go: k8s.io/kubernetes@v1.16.3 requires
	k8s.io/cluster-bootstrap@v0.0.0: reading k8s.io/cluster-bootstrap/go.mod at revision v0.0.0: unknown revision v0.0.0
go: k8s.io/kubernetes@v1.16.3 requires
	k8s.io/cluster-bootstrap@v0.0.0: reading k8s.io/cluster-bootstrap/go.mod at revision v0.0.0: unknown revision v0.0.0

$ go version
go version go1.13.4 linux/amd64
```

I understand that we are not supposed to import k/k repo. But I think k/k should at least ship with a valid go.mod file. For now, I am using replace to work around this issue in my fork: https://github.com/kmodules/kubernetes/commit/9d027e3886fd70071ad933850611fd6ded73ec76

1. I understand k/k should not be used by external projects. If k/k is really serious about this, I feel this should be done the proper way and move code to an internal package instead of shipping a broken go.mod file. Also, k/k is one of the most well-known GO projects. I think the optics of shipping a broken go.mod is really bad. This makes the case that Go's module system is incapable of handling project with complexity like k/k.

2. Projects in the k8s ecosystem uses various util packages from k/k. Example: https://github.com/kubernetes/kubernetes/issues/85692 . I understand such util packages will be moved to more appropriate location from projects that are under github.com/kubernetes-* orgs. Will that be done for vendor projects that exist in the CNCF landscape? If not, should we fork the util packages and use those?

3. We have been using the internal api conversion logic from our validating webhooks so that we can handle all the app/* api versions. I understand this is handled on the server side since 1.15 release. But we still need to support older k8s releases. As a vendor, we try to support the oldest version of k8s that is supported on services like GKE, etc. So, we need to depend on thek/k package to handle the conversion in the webhook implementation. What alternative option do we have?

Looking forward to a reasonable resolution to this issue.

**Comment by tamalsaha** [comment]
/sig api-machinery

cc: @sttts @liggitt @bgrant0607

**Comment by liggitt** [comment]
kubernetes/kubernetes uses go modules to manage dependencies and its vendor directory, including in-repo dependencies within the staging folder.

The v0.0.0 version is a placeholder version used in combination with the local replace directive, as described in https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive:

> For example, if foo is a direct dependency, you cannot do replace foo => ../foo without a corresponding require for foo. If you are not sure what version to use in the require directive, you can often use v0.0.0 such as require foo v0.0.0. This was addressed in Go 1.12 with #26241.

Replacing that with a sha or tag would be inaccurate, since the version kubernetes/kubernetes expects to use is local, not a published VCS version.

/close

**Comment by liggitt** [comment]
> For now, I am using replace to work around this issue in my fork: kmodules@9d027e3

That is the most reasonable way to work around the issue while you remove dependencies on the k8s.io/kubernetes repo.

**Comment by tamalsaha** [comment]
What is your response to the #2 point in my original issue?

**Comment by liggitt** [comment]
Requests to publish utility packages are evaluated on a case-by-case basis, depending on use, how generic they are, how many dependencies they themselves have, and whether or not they are considered supportable.

**Comment by tamalsaha** [comment]
Ok. Can you please look into https://github.com/kubernetes/kubernetes/issues/85692 ?
