### ISSUE TITLE
Customize dockershim runtime name

### ISSUE THREAD

**Issue by cpuguy83** [kubernetes/kubernetes#85699]
**What would you like to be added**:

We use our own custom build of docker for dockershim and would like to more easily reflect this information in the kubelet node info.

Example:

`kubectl get nodes -o wide` currently shows `docker://` for the runtime which is hard-coded in dockershim.
I would like to be able to have a way to change this value to something else.

One potential means of doing this would be to expose a flag that just allows operators to provide a custom value.

**Why is this needed**:

Reduce user confusion.

**Comment by liggitt** [comment]
Dockershim is deprecated and efforts are being made to remove it. I don't think adding new enhancements to it matches the feature trajectory.
