### ISSUE TITLE
Kubectl stop should watch rc status

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#8572]
Could've sworn I had a bug for this, but I can't find it. Long term goal is to push stop to master, but it should be easy enough to get the rc to watch it's status.replicas instead of poll (we have all the pieces in place already). 

/ref https://github.com/GoogleCloudPlatform/kubernetes/pull/8560#issuecomment-103960327

**Comment by bprashanth** [comment]
We should consider having kubectl stop watch pods instead of the rc's status.replicas because of https://github.com/GoogleCloudPlatform/kubernetes/issues/8676#issuecomment-106564328

**Comment by kargakis** [comment]
I guess this is not an issue anymore (see https://github.com/kubernetes/kubernetes/issues/8676#issuecomment-129962893)
