### ISSUE TITLE
Service remains unavailable after node returns from NotReady

### ISSUE THREAD

**Issue by lllamnyp** [kubernetes/kubernetes#85725]
**What happened**:

One of my nodes momentarily became `NotReady`, then it came back:

```
$ kubectl get events
LAST SEEN   TYPE      REASON                    OBJECT                                                      MESSAGE
5m22s       Normal    NodeNotReady              node/192.168.234.6                                          Node 192.168.234.6 status is now: NodeNotReady
5m13s       Normal    NodeHasSufficientMemory   node/192.168.234.6                                          Node 192.168.234.6 status is now: NodeHasSufficientMemory
5m13s       Normal    NodeHasNoDiskPressure     node/192.168.234.6                                          Node 192.168.234.6 status is now: NodeHasNoDiskPressure
5m13s       Normal    NodeHasSufficientPID      node/192.168.234.6                                          Node 192.168.234.6 status is now: NodeHasSufficientPID
5m13s       Normal    NodeReady                 node/192.168.234.6                                          Node 192.168.234.6 status is now: NodeReady
```

After this I saw a deployment become unavailable:
```
$ kubectl get deploy -n gitlab 
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
gitlab   0/1     1            0           65d
...
$ kubectl describe deploy -n gitlab gitlab
...
Replicas:           1 desired | 1 updated | 1 total | 0 available | 1 unavailable
...
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  gitlab-7fcff54d4 (1/1 replicas created)
NewReplicaSet:   <none>
Events:          <none>
```

However, the pod is in the ready state:

```
$ kubectl describe po -n gitlab gitlab-7fcff54d4-vz75v 
Name:           gitlab-7fcff54d4-vz75v
Namespace:      gitlab
Priority:       0
Node:           192.168.234.6/192.168.234.6
Start Time:     Fri, 22 Nov 2019 18:21:52 +0300
<snip>
Status:         Running
IP:             10.42.2.41
IPs:            <none>
Controlled By:  ReplicaSet/gitlab-7fcff54d4
Init Containers:
<snip>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 22 Nov 2019 18:21:55 +0300
      Finished:     Fri, 22 Nov 2019 18:21:56 +0300
    Ready:          True
<snip>
Containers:
  gitlab:
<snip>
    State:          Running
      Started:      Fri, 22 Nov 2019 18:21:57 +0300
    Ready:          True
    Restart Count:  0
<snip>
  mailsidecar:
<snip>
    State:          Running
      Started:      Fri, 22 Nov 2019 18:21:58 +0300
    Ready:          True
    Restart Count:  0
<snip>
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   True 
  PodScheduled      True 
<snip>
```
So all containers in the pod are ready, but the pod is not. Accordingly, the pod IP in
```
$ kubectl get ep -n gitlab gitlab -oyaml
```
shows up in the subset of `notReadyAddresses`.

Potentially related might be this event.
```
$ kubectl get events -n gitlab
LAST SEEN   TYPE     REASON                 OBJECT                                    MESSAGE
10m         Normal   TaintManagerEviction   pod/gitlab-7fcff54d4-vz75v                Cancelling deletion of Pod gitlab/gitlab-7fcff54d4-vz75v
```

**What you expected to happen**:

I expect routing to the pods on the node to resume after the node is back to the ready state.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure, this seems to be a transient issue. I've yet to analyze the logs of k8s components.

**Anything else we need to know?**:

This is a multi-master install of k8s by RKE, 5 bare metal nodes all sharing all three roles (etcd, controlplane, worker).

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Bare metal

- OS (e.g: `cat /etc/os-release`): NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`): 4.15.0-65 on the failed node, 3 others have the same version, one has been upgraded to 5.0.0.

- Install tools: RKE

- Network plugin and version (if this is a network-related bug):
rancher/calico-node:v3.7.4
rancher/coreos-flannel:v0.11.0
rancher/calico-cni:v3.7.4

- Others:

**Comment by chenk008** [comment]
Check the pod's conditions,the ready is false.
You should check the pod's readiness/liveniess
> Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   True 
  PodScheduled      True

**Comment by lllamnyp** [comment]
@chenk008 I realize this. This is probably the root of the problem. However the pods were functioning properly, in fact several other pods which did have readiness and liveness checks continued to exist without failing those checks, since the check sends a request directly to the pod IP. Basically the pod is being marked not ready incorrectly, thus it is removed from the list of endpoints. This leads me to believe that this is not an issue with networking, but something else. Do you have an idea for the appropriate /sig?

**Comment by chenk008** [comment]
@lllamnyp Can you show the readiness config?
If using http probe,check the http response status code.

**Comment by lllamnyp** [comment]
@chenk008 here is the readiness/liveness probe for one of the affected pods (a typical nginx ingress controller)
```
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
   livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
```
I've of course promptly fixed the state of the cluster since the problem arose so I cannot check right now, but I can assure you, that the pods were functioning properly (as corroborated by the ready container state): I exec'ed in some other affected pods (gitlab) and ran some service commands (gitlab-ctl) and there was no sign of error. I can speculate, however, that the pod IP could have become unreachable.

**Comment by nickperry** [comment]
I suspect this is the same issue as #82494.

**Comment by nickperry** [comment]
As I mentioned in #82494, we had a production outage this week on 15.6 due to this exact behaviour. Nodes went to Not ready, became Ready again but Healthy pods were still not added back as endpoints days afterward. Had to manually delete pods and their replacements became endpoints immediately.

**Comment by pyaillet** [comment]
I can confirm we faced exactly the same issue with rancher and kubernetes 1.15.5
[This comment](https://github.com/kubernetes/kubernetes/issues/82494#issuecomment-591717606) seems to point the underlying cause of the problem.
