### ISSUE TITLE
Scheduler with multiple plugin configurations

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85737]
**What would you like to be added**:
The scheduler to be able to handle different plugin configurations at the same time. 

For example, be able to create a scheduler with two plugin configurations (lets call them "profiles"): one prefers spreading (e.g., the current plugin configuration we have in the scheduler) and the other prefers bin packing (e.g., uses MostRequestedCapacity instead of LeastRequestedCapacity).

At startup, the scheduler creates a Framework per profile based on the profile's plugin configuration. We will change component config to accept a list of plugin configurations.

Currently, the scheduler component config looks like this:
```
type KubeSchedulerConfiguration struct {
   ...
   SchedulerName string 
   Plugins *Plugins
   PluginConfig []PluginConfig
}
```

We can change it to:
Currently, the scheduler component config looks like this:
```
type KubeSchedulerConfiguration struct {
   ...
   Profiles []KubeSchedulerProfile
}

type KubeSchedulerProfile {
   Name string  // maps to the schedulerName specified by the pods.
   Plugins *Plugins
   PluginConfig []PluginConfig
}
```

Pods specify which profile to use using the ```Pod.Spec.SchedulerName``` field. 

**Why is this needed**:

The alternative is to run multiple schedulers. This approach has the following benefits compared to running multiple schedulers:

1) More efficient: one shared informer and scheduler cache 
2) Better scheduling decisions: a single process is placing the pods, and so we avoid race conditions that can happen in the multi-scheduler approach where different schedulers may have different assumptions regarding the cluster state.
3) Easier to manage: admins need to care about a single scheduler process instead of multiple ones.

I am creating this issue to seek early feedback, I will start a KEP as a followup.

/assign
/cc @Huang-Wei @ravisantoshgudimetla @bgrant0607 @davidopp @liggitt @alculquicondor @liu-cong @k82cn @deads2k @damemi 
/sig scheduling

**Comment by Huang-Wei** [comment]
@ahg-g The "profile" idea which provides "dynamic" scheduling ability looks promising. One concern is on:

> Pods specify which profile to use using the Pod.Spec.SchedulerName field.

We still support multi schedulers - which uses "spec.schedulerName" to tell them apart. IMO we should bring up a new field called "spec.schedulerProfile" or sth. similar.

**Comment by liggitt** [comment]
> We still support multi schedulers - which uses "spec.schedulerName" to tell them apart. IMO we should bring up a new field called "spec.schedulerProfile" or sth. similar.

I disagree. I think the schedulerName is a reasonable thing to use to associate with different scheduling profiles.

**Comment by liggitt** [comment]
The profiles are logically distinct schedulers, and you could envision splitting the profiles into separate processes running one profile each in the future if needed

**Comment by Huang-Wei** [comment]
> The profiles are logically distinct schedulers, and you could envision splitting the profiles into separate processes running one profile each in the future if needed.

The motivation for this proposal is to adopt one-scheduler strategy, or one-scheduler practice. Otherwise, two scheduler processes running in parallel can still cause racing issues.

> I disagree. I think the schedulerName is a reasonable thing to use to associate with different scheduling profiles.

I know that in API's perspective, we should reuse the existing field instead of adding a new one. However, `spec.schedulerName` has been stable for a long time; while scheduler CC (component config) is still alpha. If we tweak the semantics of `spec.schedulerName` to associate it with `CC.profiles[*].name`, which phase (beta, GA) is the best timeframe? If it's beta, should/can we still support the alpha version?

**Comment by liggitt** [comment]
> The motivation for this proposal is to adopt one-scheduler strategy, or one-scheduler practice. Otherwise, two scheduler processes running in parallel can still cause racing issues.

If you split them into separate processes, you would only want to do so in a way that made them non-overlapping (e.g. use them with distinct node pools)

> However, spec.schedulerName has been stable for a long time; while scheduler CC (component config) is still alpha. If we tweak the semantics of spec.schedulerName to associate it with CC.profiles[*].name, which phase (beta, GA) is the best timeframe? If it's beta, should/can we still support the alpha version?

The spec.schedulerName API field does not specify how to make a scheduler select pods with that name. How kube-scheduler determines what schedulerName to pay attention to is orthogonal to the definition of the API field. I don't see an issue with building/progressing a feature in kube-scheduler that allows it to schedule pods that opt into specific scheduler names using weights/priorities from different named profiles.

**Comment by bgrant0607** [comment]
I agree with @liggitt. Using schedulerName is less confusing than adding another field, and is within the scope of its original intent. This approach is the most obvious to me.

**Comment by Huang-Wei** [comment]
> If you split them into separate processes, you would only want to do so in a way that made them non-overlapping (e.g. use them with distinct node pools)

Yes, using different node pools is the only answer we can give when users ask about multi-schedulers. For sure it causes the resource fragmentation. Even with that, it's still not ideal for advanced scheduling features which needs crossing check on topology domains (e.g., Pod(Anti)Affinity, EvenPodsSpread, etc.). So that's why we're pursuing/suggesting the one-scheduler practice.

> The spec.schedulerName API field does not specify how to make a scheduler select pods with that name. How kube-scheduler determines what schedulerName to pay attention to is orthogonal to the definition of the API field. I don't see an issue with building/progressing a feature in kube-scheduler that allows it to schedule pods that opt into specific scheduler names using weights/priorities from different named profiles.

Thanks for explaining. I'm fine with reusing `spec.schedulerName`.

**Comment by ravisantoshgudimetla** [comment]
In general, I'm fine with direction we're taking however I think, we should let the community know that we're deciding to go ahead with the approach of not supporting multi-scheduler scenario. I believe there are lots of people who're running their own custom scheduler using their own informers. In a way, I think, we're forcing people to register their custom scheduler as a framework(which is the goal for the scheduler framework), so putting forward the KEP and getting early feedback is the way to go.

> Yes, using different node pools is the only answer we can give when users ask about multi-schedulers. For sure it causes the resource fragmentation. Even with that, it's still not ideal for advanced scheduling features which needs crossing check on topology domains (e.g., Pod(Anti)Affinity, EvenPodsSpread, etc.). So that's why we're pursuing/suggesting the one-scheduler practice.

Sorry but I think as of now, the main cause for race condition in case of multiple scheduler scenario is the cache that we build locally in the scheduler code, this cache not being available for other schedulers, so there is no global view of the cluster state across scheduler which causes the race conditions. With the approach outlined above where is scheduler, we can get the cluster state using `GetShapshot` and the re-use the informers, so the race conditions should be avoided unless I am mistaken, if the other scheduler is registered as a new framework.

Or are you telling that we multi-scheduler approach, we can never never avoid race conditions without static partitioning of cluster, if yes, I agree unless we move to an approach of making the cluster state global and have some locking around it.

Last but not least, I am bit a skeptical of re-using the `pod.Spec.SchedulerName` - this might actually make people think that we're having a multi scheduler configuration, I personally feel that something like `profileName` would make sense as it is a single scheduler starting multiple frameworks and each framework maps to a profile.

**Comment by liggitt** [comment]
> I think, we should let the community know that we're deciding to go ahead with the approach of not supporting multi-scheduler scenario

I'm not seeing how this removes support for that… people running custom schedulers can continue doing so as they do today, right?

**Comment by liggitt** [comment]
> Last but not least, I am bit a skeptical of re-using the pod.Spec.SchedulerName - this might actually make people think that we're having a multi scheduler configuration, I personally feel that something like profileName would make sense as it is a single scheduler starting multiple frameworks and each framework maps to a profile.

I think it is a reasonable to map distinct methods of scheduling to the schedulerName field. There is a spectrum of how much those methods can vary from and interact with each other… at one end would be these proposed profiles, using a shared cache and framework, and varying in relatively narrow ways. On the other end could be an exotic custom scheduler using a completely different approach. I see the ability to address a whole range of use cases with a single/simple dimension in the API as a strength.

**Comment by ahg-g** [comment]
Just to clarify: this proposal does not force custom schedulers to use the framework, nor does it prevent the existence of multiple schedulers. The only implication of this proposal in this regard is that the default scheduler will be able to scheduler pods from more than one schedulerName.

I also agree that reusing the schedulerName field is less confusing than adding yet another field with very close semantics.

**Comment by Huang-Wei** [comment]
> Sorry but I think as of now, the main cause for race condition in case of multiple scheduler scenario is the cache that we build locally in the scheduler code, this cache not being available for other schedulers, so there is no global view of the cluster state across scheduler which causes the race conditions. With the approach outlined above where is scheduler, we can get the cluster state using GetShapshot and the re-use the informers, so the race conditions should be avoided unless I am mistaken, if the other scheduler is registered as a new framework.

@ravisantoshgudimetla The "multi-scheduler" I meant the multi scheduler ways we support today - i.e. running multiple schedulers in different processes, not the "multi profiles" idea raised in this proposal.

I think @ahg-g has made it clear that:

1. Users can remain on their current way to run multiple schedulers - each one in a separate process. In this case, occasional racing issues are inevitable.
2. However, early adopters of this proposal can migrate their custom scheduler(s) into scheduler profile(s), use one scheduler, and hence enjoy the benefits mentioned in the description section of this issue.

**Comment by ravisantoshgudimetla** [comment]
> I'm not seeing how this removes support for that… people running custom schedulers can continue doing so as they do today, right?

> Just to clarify: this proposal does not force custom schedulers to use the framework, nor does it prevent the existence of multiple schedulers. The only implication of this proposal in this regard is that the default scheduler will be able to scheduler pods from more than one schedulerName.

@liggitt and @ahg-g Thanks for the clarification, the sentence `The alternative is to run multiple schedulers. ` made me think, we're going to take the route of not supporting multi-scheduler  configuration.

> I think it is a reasonable to map distinct methods of scheduling to the schedulerName field. There is a spectrum of how much those methods can vary from and interact with each other… at one end would be these proposed profiles, using a shared cache and framework, and varying in relatively narrow ways. On the other end could be an exotic custom scheduler using a completely different approach. I see the ability to address a whole range of use cases with a single/simple dimension in the API as a strength.

Ok, it seems reasonable then.

**Comment by Chest1** [comment]
Don't merge

**Comment by Chest1** [comment]
//cc
