### ISSUE TITLE
The dashboard has uses excessive memory over time

### ISSUE THREAD

**Issue by telefoontoestel** [kubernetes/kubernetes#85748]
On our local development machine we use a single node kubernetes cluster with minikube. This cluster can be tracked with the default kubernetes dashboard. When this dashboard is active for a long period of time (in my use case it was for about 12 to 16 hours), the memory usage sky-rockets over time ending up with using 12G just before I closed the page. I think there might be an issue with javascript objects not being cleaned-up properly.

We use minikube installed on the Windows host machine and the kubectl gcloud binary installed on the Ubuntu WSL system and configured to use the cluster created by minikube.

OS: Windows 10 Pro 1903 (18362.476)
WSL version: 1
WSL client: Ubuntu 19.04
Kubernetes version: 
`Client Version: `
`    version.Info {`
`        Major:"1", `
`        Minor:"13+", `
`        GitVersion:"v1.13.9-2+4a03651a7e7e04",`
`       GitCommit:"4a03651a7e7e04a0021b2ef087963dfb7bd0a17e", `
`        GitTreeState:"clean", `
`        BuildDate:"2019-08-16T18:57:20Z", `
`        GoVersion:"go1.11.5", `
`        Compiler:"gc", `
`        Platform:"linux/amd64"`
`    }`
`Server Version:`
`    version.Info { `
`        Major:"1", `
`        Minor:"16", `
`        GitVersion:"v1.16.2", `
`        GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b",`
`        GitTreeState:"clean", `
`        BuildDate:"2019-10-15T19:09:08Z", `
`        GoVersion:"go1.12.10", `
`        Compiler:"gc", `
`        Platform:"linux/amd64"`
`}`

Minikube version: v1.5.2 (commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty)

**Comment by telefoontoestel** [comment]
@kubernetes/sig-ui

**Comment by liggitt** [comment]
Thanks for reporting the issue. Please report it against the kubernetes/dashboard repo So it can be triaged by the dashboard team.
