### ISSUE TITLE
Error response from daemon: unknown service containerd.services.leases.v1.Leases: not implemented

### ISSUE THREAD

**Issue by hysystem** [kubernetes/kubernetes#85740]
# kubectl describe pod nginx-648fd8975f-65qxs
Name:           nginx-648fd8975f-65qxs
Namespace:      default
Priority:       0
Node:           node02/192.168.0.168
Start Time:     Fri, 29 Nov 2019 10:34:16 +0800
Labels:         pod-template-hash=648fd8975f
                run=nginx
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/nginx-648fd8975f
Containers:
  nginx:
    Container ID:   
    Image:          nginx:1.17.6
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/share/nginx/html from html (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ctdvg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  html:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/k8s_data/nginx
    HostPathType:  DirectoryOrCreate
  default-token-ctdvg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-ctdvg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Normal   Scheduled               10m                     default-scheduler  Successfully assigned default/nginx-648fd8975f-65qxs to node02
  Warning  FailedCreatePodSandBox  10m (x13 over 10m)      kubelet, node02    Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-648fd8975f-65qxs": Error response from daemon: unknown service containerd.services.leases.v1.Leases: not implemented
  Normal   SandboxChanged          10m (x12 over 10m)      kubelet, node02    Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  6m35s (x12 over 6m46s)  kubelet, node02    Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-648fd8975f-65qxs": Error response from daemon: unknown service containerd.services.leases.v1.Leases: not implemented
  Normal   SandboxChanged          107s (x263 over 6m47s)  kubelet, node02    Pod sandbox changed, it will be killed and re-created.

Linux master01 4.4.202-1.el7.elrepo.x86_64 #1 SMP Sat Nov 16 08:56:23 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tedyu** [comment]
@hysystem 
Do you encounter this problem on recent kubernetes release(s) ?
