### ISSUE TITLE
Pod expiration time

### ISSUE THREAD

**Issue by icy** [kubernetes/kubernetes#85752]
**What would you like to be added**:

Pod has new attribute "Expiration Time" after that the Pod would stop to receive any connections and exit gracefully and the deployment (or daemonset...) will launch another pod to replace it.

**Why is this needed**:

Because k8s is fun and having this feature is also fun

**Comment by liggitt** [comment]
The activeDeadlineSeconds allows bounding pod execution time

**Comment by icy** [comment]
@liggitt I think activeDeadlineSeconds is applied to Job and it's not available for deployment/daemonset.

**Comment by liggitt** [comment]
you're right:
```
		if template.Spec.ActiveDeadlineSeconds != nil {
			allErrs = append(allErrs, field.Forbidden(fldPath.Child("spec", "activeDeadlineSeconds"), "activeDeadlineSeconds in ReplicaSet is not Supported"))
		}
```

**Comment by alaxalves** [comment]
Any updates with this?
