### ISSUE TITLE
Return a distinct status code if server-side apply caused no change

### ISSUE THREAD

**Issue by bouk** [kubernetes/kubernetes#85750]
**What would you like to be added**:

Using server-side apply there's currently two status codes that can be returned, [OK and Created](https://github.com/kubernetes/kubernetes/blob/cf16e4988f58a5b816385898271e70c3346b9651/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L234-L237). It would be nice if there was a third status code or a header or something to indicate whether the request caused any changes on the server-side. 

**Why is this needed**:

This would be useful for the client to determine whether it can expect a deployment rollout to start for example, and it would also be good UX for `kubectl apply` to print out whether the request caused a change.

**Comment by kwiesmueller** [comment]
Thanks for filing the Issue.
Do you have a specific use case in mind?

For the "deployment rollout" case, there should be more reliable options.

Also what statuscode would you expect?
Not sure if a 304 Not Modified would be correct, as it is intended for cache validation and the client should not make any assumptions based on apply behavior, if there are more reliable ways to get the information.

**Comment by apelisse** [comment]
That's a reasonable ask. I don't know about deployment because the rules to trigger a roll-out are slightly more complicated than that. I agree that `kubectl apply` could print a different text based on that result.

`304 Not Modified` is mostly a cache mechanism, so I would be concerned that it'd be misinterpreted.

Let's keep digging.

**Comment by bouk** [comment]
It seems to me that there’s not a 2xx status code that’s appropriate. Perhaps a custom response header makes the most sense.

**Comment by lavalamp** [comment]
I would like to know what a client will do with this information? I can't think of a good thing for a client to do with this information.

It sounds like we'd be enabling this bug: If your client flow is "1. apply 2. if changes were made, do X"-- that's a bug; if you crash between 1 and 2 and repeat this logic, the second run will observe no changes and not run step 2.

**Comment by apelisse** [comment]
One thing to mention (that's not an opinion) is that kubectl currently tells you if something changed or not, though I don't think it's meant to be consumed by a "program":
> deployment/deployment1 created
> deployment/deployment2 configured
> deployment/deployment3 unchanged

**Comment by bouk** [comment]
Yes, that is exactly the use case I have in mind @apelisse. As a user running kubectl I want to be able to see what changed, just seeing 'server-side applied' is not useful.

**Comment by kwiesmueller** [comment]
I think that's a valid requirement.
On the server side we could figure it out, I'm not sure about a good way to communicate it to the client though.

**Comment by apelisse** [comment]
@deads2k Do you have an opinion on that?

**Comment by lavalamp** [comment]
I wonder if a header would be a better way to communicate this than a status code.

**Comment by kwiesmueller** [comment]
That's what we talked about a few minutes ago.
I'll prepare a proposal.

**Comment by apelisse** [comment]
People seem to care about this: https://github.com/kubernetes/kubernetes/issues/66450

**Comment by kwiesmueller** [comment]
@bouk feel free to follow the progress in the KEP PR and leave any feedback you have regarding the approach: https://github.com/kubernetes/enhancements/pull/1442

**Comment by apelisse** [comment]
If we want to fix this, this will require coordination between cli and api-machinery. We would need to build a new mechanism in the API server to detect the change. It doesn't exist today and might be controversial since it doesn't really match the model (one is not really supposed to care if the resource changed or not). Do we think that feature is so important that we need to engage controversial work on api-machinery? @seans @soltysh @liggitt

**Comment by seans3** [comment]
Currently we return a different exit code for `kubectl diff` based on whether there was a difference detected (with a different exit code >1 if error). Would that be analogous to this ask? I think the hard work would be in the api-machinery, so I'll defer to that team. `kubectl` is already going to have to deal with headers for api deprecation warnings: https://github.com/kubernetes/enhancements/pull/1694.

**Comment by apelisse** [comment]
Also note that Server-side Apply doesn't show "configured" vs "unchanged" so it's not just about the exit status code. But again, we can't do that without changing the apiserver.

**Comment by lavalamp** [comment]
OK the current state on this from my perspective:
* It's not clear it's important enough...
* But if it is, we'd likely use a header and not a status code to communicate it
* Note that apiserver always avoids writing to etcd for no-op mutating requests, so it actually does have this information; if we added this, it'd make sense to do it for all mutating requests.

On that first point (importance), the "why this is needed" section in the OP is actually anti-evidence. The question of "did I change something" is not, in general, going to have the same answer as "are there unresolved aspects of this object / are controllers working on it in some way". In fact we have strong evidence that these questions are different in common / important cases -- e.g., did your change to a Deployment change e.g. a label/annotation, or did you change something in the template? Even our `metadata.generation` mechanism has turned out to be a little under powered for this.

**Comment by apelisse** [comment]
> But if it is, we'd likely use a header and not a status code to communicate it

Just to make sure there's not confusion, we're mostly talking about the binary `kubectl` exit code here.

**Comment by apelisse** [comment]
For your first bullet point, quoting from #66450

> In general, what I'd like to see is consistent use of "configured" vs. "unchanged" when applying a resource via kubectl apply. This functionality appears to work now for some kinds of resources, but not all kinds. You might be wondering, why is this even important? When applying a large group of resource files, it's very helpful to know which ones have actually changed and which ones haven't. It would become immediately obvious when a resource changes when it shouldn't have, and you could investigate the issue right away, without waiting for that problem to manifest itself in other ways. As it stands now, so many are labeled as "configured" that it's not useful or accurate to rely on this statement.

**Comment by lavalamp** [comment]
Yeah that's a better argument than the OP.

It's surprising to me that you'd want different binary exit codes? Wouldn't that imply that one of these states was an error?

**Comment by apelisse** [comment]
Not necessarily, the typical diff binary returns 1 when there's a diff, doesn't mean it's an error. 
http://man7.org/linux/man-pages/man1/diff.1.html

**Comment by lavalamp** [comment]
Makes more sense for diff, I think? If I call kubectl apply from a script and got an error, I'd expect it mean something went wrong and I needed to abort and/or retry it, though. How would we communicate that there was e.g. a network problem rather than a difference?

**Comment by kwiesmueller** [comment]
I don't know if I agree on a response code.
We already wanted to clarify, that the user shouldn't take concrete actions from this but that there are better ways (which is outlined in the KEP).
A response code seems like more of an encouragement in that direction.
The feedback to the user is what I aimed for, not feedback to the "caller".

**Comment by liggitt** [comment]
> Makes more sense for diff, I think? If I call kubectl apply from a script and got an error, I'd expect it mean something went wrong and I needed to abort and/or retry it, though.

I agree. Subdividing the "successfully applied" case into "made a change" and "didn't make a change" seems like it explicitly breaks the idea of apply as an idempotent operation.

**Comment by apelisse** [comment]
>> Makes more sense for diff, I think? If I call kubectl apply from a script and got an error, I'd expect it mean something went wrong and I needed to abort and/or retry it, though.
>
> I agree. Subdividing the "successfully applied" case into "made a change" and "didn't make a change" seems like it explicitly breaks the idea of apply as an idempotent operation.

I also agree with that point. I'm not concerned at all about having to differentiate 0 from 1 exit code. The problem we're trying to solve is human beings looking at their screen and seeing if things go as they expected, not so much about scripts taking a different approach based on that.
