### ISSUE TITLE
[Failing Test] ci-kubernetes-e2e-gce-scale-{performance, correctness} fail due to hanging DumpClusterLogs

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#85753]
**Which jobs are failing**:
gce-master-scale-performance
gce-master-scale-correctness

**Which test(s) are failing**:
n/a 

**Since when has it been failing**:
11/28

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness

**Reason for failure**:
Tests timed out due to longer than usual DumpClusterLogs phase: ![5jVxEfY1vCk](https://user-images.githubusercontent.com/30298753/69868332-b85b8500-12a9-11ea-891f-3c1929a105b9.png)

**Anything else we need to know**:

/priority important-soon
/milestone v1.18
/sig scalability 
/assign

**Comment by oxddr** [comment]
/priority important-critical
All runs of performance and correctness since 11/28 are affected. 

/assign @jkaniuk  
/unassign
Jacek, could you have a look into this one?

**Comment by justaugustus** [comment]
/remove-priority important-soon
/priority critical-urgent

@kubernetes/sig-scalability-bugs -- Please provide an update to @kubernetes/release-managers and @kubernetes/release-team-leads as soon as you can as this could impact the release timeline.

**Comment by jkaniuk** [comment]
DumpClusterLogs phase is stuck on doing kubectl logs for each logexporter pod.

Relevant loop:
https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L509

Problem started occuring between commits 
7c87b5fb55 Wed Nov 27 08:25:20 2019 -0800
and
dcb7daa8851 Thu Nov 28 03:03:03 2019 -0800

There was one change to log-dump.sh merged during that time:
https://github.com/kubernetes/kubernetes/pull/83604
https://github.com/kubernetes/kubernetes/pull/83604/commits/e99a325d4e93dc604dd8299800ad4941d10f29ea#diff-5d682968f2f3b4ff2f9f2bb9a303f650L507

which modified that loop from:
```
kubectl get po |  read -r pod node; do
  echo "Fetching logs from ${pod} running on ${node}"
  ...
done
```
to:
```
while read -r pod node; do
  echo "Fetching logs from ${pod} running on ${node}"
  ...
done < <(kubectl get po)
```

Both works fine on 100 node cluster, but the latter one seems to break on 5k clusters.
First one runs in subshell caused by the pipeline, latter one runs the loop in the main shell.

Running experiments to verify.

**Comment by hasheddan** [comment]
Thank you @jkaniuk! Will monitor subsequent tests to make sure fix is working as expected :)

**Comment by jkaniuk** [comment]
Looks that the revert has helped:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1202196266734325764

previously only first batch of log exports was run (then the timeout has happened).
it looked like that:
```
I1129 05:18:19.619] Fetching logs from logexporter-225rh running on gce-scale-cluster-minion-group-2-kk2h
... (25 occurences total)
I1129 05:18:19.696] Fetching logs from logexporter-27prq running on gce-scale-cluster-minion-group-3-51wz
W1129 10:33:20.444] 2019/11/29 10:33:20 process.go:199: Interrupt after 17h30m0s timeout during ./cluster/log-dump/log-dump.sh /workspace/_artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1200097516549312512/artifacts. Will terminate in another 15m
```
25 is the level of parallelism in bash script:
https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L60
`readonly max_dump_processes=25`

This time, all passed:
```
I1204 14:32:39.764] Fetching logs from logexporter-2226h running on gce-scale-cluster-minion-group-1-0zs2
... (5000 occurences total)
I1204 14:35:05.272] Fetching logs from logexporter-zzthm running on gce-scale-cluster-minion-group-2-66kk
I1204 14:35:07.962] Successfully listed marker files for successful nodes
```

**Comment by jkaniuk** [comment]
Something that could be related to the difference between 100 nodes and 5000 nodes runs:

Output of piped command is buffered with buffer size 64k, so when the output is larger, the command is kept running. In case of 
`kubectl get pods -n logexporter -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.nodeName}{"\n"}{end}'`
the threshold should be around 1200 nodes.

Unfortunately I did not manage to reproduce the problem directly in bash.

**Comment by jkaniuk** [comment]
I have managed to reproduce it in simple bash script:

```
#!/bin/bash
output_kb=70 # works fine for 64 and below
max_dump_processes=2
function print_1k() {
  for _ in {1..102}; do
    echo -n '123456789 '
  done
  echo xyz
}
function generator() {
  for _ in $(seq 1 "$1"); do
    print_1k
  done
}
proc=${max_dump_processes}
#generator $output_kb | cat | \
while read -r pod _; do
  echo "Fetching logs from $pod" && sleep 1 &
  proc=$((proc - 1))
  if [[ proc -eq 0 ]]; then
    proc=${max_dump_processes}
    wait
  fi
done < <(generator $output_kb | cat)
if [[ proc -gt 0 && proc -lt ${max_dump_processes} ]]; then
  wait
fi
```

**Comment by jkaniuk** [comment]
Basically, wait expects number of background process to reach 0, but kubectl process that is piped into the loop is still running in the background.
Previously that was not a problem as the loop was executed in separate subshell than kubectl.
