### ISSUE TITLE
Mismatch in documentation about postStart script

### ISSUE THREAD

**Issue by HappyStoic** [kubernetes/kubernetes#85766]
Hello,
while browsing through the documentaion I found these two information:

[Pod lifecycle docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states)
* Running: Indicates that the container is executing without issues. **Once a container enters into Running, postStart hook (if any) is executed.** This state also displays the time when the container entered Running state.
 
[Lifecycle events docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states)
* The postStart handler runs asynchronously relative to the Container’s code, but Kubernetes’ management of the container blocks until the postStart handler completes. **The Container’s status is not set to RUNNING until the postStart handler completes.**

I find this mismatching and do not actually know which one is correct.

**Comment by udit249** [comment]
I am working on this issue.
