### ISSUE TITLE
Windows Nodes - Kubernetes Metrics reporting incorrect stats via https://<nodename>:10250/stats/summary

### ISSUE THREAD

**Issue by nileshkumar01** [kubernetes/kubernetes#85786]
**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.5
- Cloud provider or hardware configuration: Running on VMWare
- OS (e.g: `cat /etc/os-release`): Windows Server 1903 
- Network plugin and version (if this is a network-related bug): N/A

**What happened**:
I have been looking at the metrics thats provided by the endpoint https://nodename:10250/stats/summary i noticed that the /rootfs /logs /Volume was pulling out the volume information for the host drive and not the volume information of the Windows container it self.

**What you expected to happen**:
I expected these volume details to be of the container and not the host drive.

**How to reproduce it (as minimally and precisely as possible)**:

Run a windows node deploy a container onto it and then have a look at the endpoint https://<nodename>:10250/stats/summary  to get the stats for that pod and you will notice the volume information sent back is from the host and not the container

`{
  "node": {
   "nodeName": "win2",
   "systemContainers": [
    {
     "name": "pods",
     "startTime": "2019-12-02T04:57:00Z",
     "cpu": {
      "time": "2019-12-02T04:57:00Z",
      "usageNanoCores": 4212632,
      "usageCoreNanoSeconds": 17515625000
     },
     "memory": {
      "time": "2019-12-02T04:57:00Z",
      "workingSetBytes": 52731904
     },
     "userDefinedMetrics": null
    }
   ],
   "startTime": "2019-12-02T04:51:18Z",
   "cpu": {
    "time": "2019-12-02T04:56:58Z",
    "usageNanoCores": 1564000000,
    "usageCoreNanoSeconds": 429180000000
   },
   "memory": {
    "time": "2019-12-02T04:56:58Z",
    "availableBytes": 1968594944,
    "usageBytes": 2503663616,
    "workingSetBytes": 1226993664,
    "rssBytes": 0,
    "pageFaults": 0,
    "majorPageFaults": 0
   },
   "network": {
    "time": "2019-12-02T04:56:58Z",
    "name": "",
    "interfaces": [
     {
      "name": "Microsoft KM-TEST Loopback Adapter",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 0,
      "txErrors": 0
     },
     {
      "name": "Intel[R] PRO_1000 MT Desktop Adapter",
      "rxBytes": 177877913,
      "rxErrors": 0,
      "txBytes": 2291217,
      "txErrors": 0
     },
     {
      "name": "Intel[R] PRO_1000 MT Desktop Adapter _2",
      "rxBytes": 401250,
      "rxErrors": 0,
      "txBytes": 163175,
      "txErrors": 0
     },
     {
      "name": "Hyper-V Virtual Ethernet Adapter _2",
      "rxBytes": 14736,
      "rxErrors": 0,
      "txBytes": 18856,
      "txErrors": 0
     },
     {
      "name": "Teredo Tunneling Pseudo-Interface",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 0,
      "txErrors": 0
     },
     {
      "name": "6to4 Adapter",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 0,
      "txErrors": 0
     },
     {
      "name": "Hyper-V Virtual Ethernet Adapter",
      "rxBytes": 403003,
      "rxErrors": 0,
      "txBytes": 182169,
      "txErrors": 0
     },
     {
      "name": "Microsoft IP-HTTPS Platform Interface",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 0,
      "txErrors": 0
     },
     {
      "name": "Microsoft Kernel Debug Network Adapter",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 0,
      "txErrors": 0
     },
     {
      "name": "Hyper-V Virtual Switch Extension Adapter",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 0,
      "txErrors": 0
     }
    ]
   },
   "fs": {
    "time": "2019-12-02T04:56:58Z",
    "availableBytes": 114256048128,
    "capacityBytes": 136912564224,
    "usedBytes": 22656516096
   },
   "runtime": {
    "imageFs": {
     "time": "2019-12-02T04:56:58Z",
     "availableBytes": 114255982592,
     "capacityBytes": 136912564224,
     "usedBytes": 22656581632
    }
   }
  },
  "pods": [
   {
    "podRef": {
     "name": "win-webserver-ic-td-894b59c59-tvpsp",
     "namespace": "default",
     "uid": "8c875286-3d9c-4dc7-be9f-3c12530ef9bf"
    },
    "startTime": "2019-12-02T04:52:36Z",
    "containers": [
     {
      "name": "windowswebserver",
      "startTime": "2019-12-02T04:52:54Z",
      "cpu": {
       "time": "2019-12-02T04:57:00Z",
       "usageNanoCores": 4212632,
       "usageCoreNanoSeconds": 17515625000
      },
      "memory": {
       "time": "2019-12-02T04:57:00Z",
       "workingSetBytes": 52731904
      },
      "rootfs": {
       "time": "2019-12-02T04:57:00Z",
       "availableBytes": 114171793408,
       "capacityBytes": 136912564224,
       "usedBytes": 0
      },
      "logs": {
       "time": "2019-12-02T04:57:00Z",
       "availableBytes": 114255982592,
       "capacityBytes": 136912564224,
       "usedBytes": 0,
       "inodesUsed": 0
      },
      "userDefinedMetrics": null
     }
    ],
    "cpu": {
     "time": "2019-12-02T04:52:54Z",
     "usageNanoCores": 4212632,
     "usageCoreNanoSeconds": 17515625000
    },
    "memory": {
     "time": "2019-12-02T04:57:00Z",
     "availableBytes": 0,
     "usageBytes": 0,
     "workingSetBytes": 52731904,
     "rssBytes": 0,
     "pageFaults": 0,
     "majorPageFaults": 0
    },
    "network": {
     "time": "2019-12-02T04:57:00Z",
     "name": "36aea8b8eacb62399a443054d9db9cc395285371968fd561877c52762f4cc5e0_Calico",
     "rxBytes": 7303,
     "txBytes": 19184,
     "interfaces": [
      {
       "name": "36aea8b8eacb62399a443054d9db9cc395285371968fd561877c52762f4cc5e0_Calico",
       "rxBytes": 7303,
       "txBytes": 19184
      }
     ]
    },
    "volume": [
     {
      "time": "2019-12-02T04:53:30Z",
      "availableBytes": 114732924928,
      "capacityBytes": 136912564224,
      "usedBytes": 1874,
      "inodesFree": 0,
      "inodes": 0,
      "inodesUsed": 0,
      "name": "default-token-qc9f9"
     }
    ],
    "ephemeral-storage": {
     "time": "2019-12-02T04:57:00Z",
     "availableBytes": 114255982592,
     "capacityBytes": 136912564224,
     "usedBytes": 0,
     "inodesUsed": 0
    }
   }
  ]
 }
`
/sig windows

**Comment by jingxu97** [comment]
I think my PR https://github.com/kubernetes/kubernetes/pull/81437 fixed this issue. Could you try newer version 1.16?

**Comment by nileshkumar01** [comment]
@jingxu97 Thank you for the info will test it out and provide some feedback about my results
