### ISSUE TITLE
can not find statefulset rollback in kubernetes api

### ISSUE THREAD

**Issue by ZhaoBaymax** [kubernetes/kubernetes#85784]
I want to rollback the resource of statefulset  through the API.
In kubectl , it can use `kubectl rollout undo <statefulset_name>`.
but, I can not find any api about rollback the statefulset.

**Comment by liggitt** [comment]
There is no API to perform this operation directly, it requires fetching and restoring a controller revision for the stateful set. See https://github.com/kubernetes/kubernetes/blob/81780271497f1f25686b2799fe5a63b5dd40d2d6/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollback.go#L339-L438 for the logic used by kubectl

/close
