### ISSUE TITLE
de-prioritize ScheduleFailed pods in scheduler

### ISSUE THREAD

**Issue by yingnanzhang666** [kubernetes/kubernetes#85792]
We found performance issue for scheduler in our production env.

Scenario:
If there are several pods cannot be scheduled, it will be always add to queue, then if customer creates new pod with the same or lower priority, this pod will be added behind these FailedScheduling pods, then scheduler will schedule the new pod after finishing all the FailedScheduling pods in this loop.
In large cluster, especially for the pods with localvolume which scheduling latency is high, they are put into scheduler queue, the performance impact will be enlarged. (consider scheduler performance including waiting time in queue.)
Although backoff mechanism can relieve the impact from FailedScheduling pods on the same/lower priority new-coming pods, but the effectiveness is limited. 

Relative discuss: https://github.com/kubernetes/kubernetes/issues/81214

So we'd better to de-prioritize these FailedScheduling pod, avoid them to block the queue.

**Comment by ProgramerGu** [comment]
Do you want to cancel or optimize the priority of the new container?

**Comment by yingnanzhang666** [comment]
One proposal is that, 
- keep to de-prioritize ScheduleFailed pods when each time this pod wasn't scheduled successfully.
- set back to original priority for those pods being de-prioritized when receive events about capacity adding.

**Comment by yingnanzhang666** [comment]
**de-prioritize these ScheduleFailed pods, avoid them to block the queue.**

- keep to de-prioritize FailedScheduling pods when each time this pod wasn't scheduled successfully.
> 1. First podAttempt: dynamic-priority=priority/2
> 2. N podAttempts: dynamic-priority=dynamic-priority/(2^N)
> 3. N > M: dynamic-priority=-1

- set back to original priority for those pods being de-prioritized when receive events about capacity adding. (warmup time: start to change dynamic-priority after 1 minute when capacity adding)
> 1. Receive pod deletion events
> 2. Receive node addition events
> 3. Node status changed from NotReady to Ready

This proposal mixes with backoff mechanism. podAttempts was recorded in PodBackoffMap. Calculate the dynamic priority when this pod was moved to backoff queue, leverage the existing podAttempts in backoff mechanism.

**Comment by yingnanzhang666** [comment]
@bsalamat

**Comment by yingnanzhang666** [comment]
@ahg-g

**Comment by ahg-g** [comment]
Those are interesting heuristics, but how do we make sure that they work properly for everyone?

**Comment by yingnanzhang666** [comment]
@ahg-g 
The main idea is that
1. FailedScheduling pods shouldn't block pods with same priority or lower priority
2. If cap adding by nodes provision or removing pod, FailedScheduling pods(have opportunity to meet resource requirement) with high priority should be scheduled first.
Currently, this mechanism is added in priority queue, only the cluster which enable podpriority can use this.
I think this is a common expectation. Could you explain more about your concern?

**Comment by yingnanzhang666** [comment]
cc. @draveness @hex108

**Comment by draveness** [comment]
Thanks @yingnanzhang666, this proposal makes sense to me, but here are some concerns about this change. 

I think the best approach to implement this is by introducing another field to the PriorityClass, e.g., `reschedulePolicy`:

```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
reschedulePolicy: Removed
```

With this approach, the original behavior of priority class won't change, and it won't affect the current user. Another concern about this approach is `PriorityClass` has already graduated to GA, I'm not sure if we could add another field to it.

I'd like to implement this if we decided to have this feature in the codebase.

/assign

**Comment by alculquicondor** [comment]
/close

Let's dedup onto #86373
