### ISSUE TITLE
coredns can not start with “Failed to list *v1.Endpoints:  and “Failed to list *v1.Service”

### ISSUE THREAD

**Issue by Jwen-nus** [kubernetes/kubernetes#85794]
I have a problem when I install the kube-dns add on. My OS is CentOS Linux release 7.4

When I start the coredns thecoredns container log:

ace[768378026]: [30.002243414s] [30.002243414s] END
E1202 09:08:34.949036       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.9.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.9.0.1:443: i/o timeout
E1202 09:08:34.949036       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.9.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.9.0.1:443: i/o timeout
E1202 09:08:34.949036       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.9.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.9.0.1:443: i/o timeout
E1202 09:08:34.949013       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.9.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.9.0.1:443: i/o timeout
E1202 09:08:34.949036       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.9.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.9.0.1:443: i/o timeout
E1202 09:08:34.950370       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.9.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.9.0.1:443: i/o timeout
I1202 09:08:34.950302       1 trace.go:82] Trace[1212724865]: "Reflector pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94 ListAndWatch" (started: 2019-12-02 09:08:04.949585685 +0000 UTC m=+31.020839521) (total time: 30.000703085s):
Trace[1212724865]: [30.000703085s] [30.000703085s] END

**Comment by liggitt** [comment]
what manifest did you use to deploy coredns? the default addon includes RBAC role/binding permissions (xref https://github.com/kubernetes/kubernetes/blob/release-1.16/cluster/addons/dns/coredns/coredns.yaml.in#L12-L53)

**Comment by chrisohaver** [comment]
The errors in the log shown in the description are timeouts, not auth failures... So may be more than one issue at hand.

**Comment by johscheuer** [comment]
Could you check if `kube-proxy` is running in your cluster ? And how did you set up the cluster (and which version).

**Comment by vincent081** [comment]
> 您用来部署coredns的清单是什么？默认插件包含RBAC角色/绑定权限（外部参照https://github.com/kubernetes/kubernetes/blob/release-1.16/cluster/addons/dns/coredns/coredns.yaml.in#L12-L53）

my coredns.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: coredns
        image: coredns/coredns:1.6.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.9.0.2
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP

**Comment by vincent081** [comment]
> Could you check if `kube-proxy` is running in your cluster ? And how did you set up the cluster (and which version).

kube-proxy is running ,cluster 3.0 tks!

**Comment by nickchappell** [comment]
I'm running into the same issue, though with kube-router as the CNI plugin (proxy and pod networking on, firewall off). `firewalld` is disabled, SELinux set to permissive. Nodes and temporary pods I spin up can ping/curl the service IP of the API server, but for some reason the CoreDNS containers can't.

**Comment by chrisohaver** [comment]
@nickchappell, in your case is the error indicating "timeout"? Or are you seeing "unauthorized" or some other error.

**Comment by kris-nova** [comment]
So there are a few other errors that could be causing this

```
swapoff -a
```

will fix the swap error. Also, if you are using `cri-o` or `crio` as a container runtime you can check the following snippet in `/etc/crio/crio.conf`

```
registries = [
 	"quay.io",
	"docker.io",
	"gcr.io", # <----- Add this
]
```

**Comment by mo-mirzania** [comment]
I resolved(?) the problem by stopping firewalld!

**Comment by mercury77** [comment]
> I resolved(?) the problem by stopping firewalld!

Please can you provide more information about what you did please?
We're facing same issue .
Thanks in advance for your support !!

**Comment by mo-mirzania** [comment]
> > I resolved(?) the problem by stopping firewalld!
> 
> Please can you provide more information about what you did please?
> We're facing same issue .
> Thanks in advance for your support !!

Just stopped firewalld service on master and worker nodes!

**Comment by dick-nux** [comment]
Found the problem, it is iptables forwarding rules, check kube-proxy configuration。

**Comment by aljaxus** [comment]
> I resolved(?) the problem by stopping firewalld!
> *`- @mo-mirzania`*

Yeah this actually worked for me too - it's a rather nasty workaround, but it works `:shrug:`
