### ISSUE TITLE
failure after following macOS installation instructions

### ISSUE THREAD

**Issue by hansifer** [kubernetes/kubernetes#85816]
**What happened**:

Followed installation instructions here: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-with-curl-on-macos

Last step (kubectl version) yields `Client.Timeout exceeded while awaiting headers`

**What you expected to happen**:

Installation instructions to work.

**How to reproduce it (as minimally and precisely as possible)**:

Follow installation instructions here: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-with-curl-on-macos

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): timeout
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): `cat: /etc/os-release: No such file or directory`
- Kernel (e.g. `uname -a`): `Darwin MAY.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others:

**Comment by liggitt** [comment]
that means your client is timing out trying to reach your server. check your configuration `kubectl config view` to ensure your connection configuration is correct

**Comment by hansifer** [comment]
> that means your client is timing out trying to reach your server. check your configuration `kubectl config view` to ensure your connection configuration is correct

Does that mean there is a step missing in the installation instructions? I followed them verbatim.

**Comment by liggitt** [comment]
The way they are written, the instructions will only work if you already have a config file for a reachable cluster at $KUBECONFIG (or at `$HOME/.kube/config`), but they do not state this explicitly. There either needs to be an explicit prereq to obtain that, or the `version` commands should be changed to `kubectl version --client` to allow the version command to succeed in the absence of a server, and a "next steps" topic to set up the server connection info.

**Comment by liggitt** [comment]
I would suggest opening an issue at https://github.com/kubernetes/website/ against that page and linking to this discussion

**Comment by hansifer** [comment]
OK will do. Thanks for your help and responsiveness. It's much appreciated.
