### ISSUE TITLE
Sample Scheduler Framework plugins

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#85826]
The Scheduler Framework is designed to engage end-users to easily build custom scheduling plugins to fit their particular requirements. We do have some basic examples and documents guiding users on how to use this (internally scheduler is refactoring its code to 100% adhere to the framework: [Phase1](https://github.com/kubernetes/kubernetes/issues/83554), [Phase2](https://github.com/kubernetes/kubernetes/issues/85822)), however, for some complex and common requirements (e.g. batch), we'd like to create a SIG sub-repo (or other manner) to store qualified plugins code, so that those plugins can be developed iteratively in an open-source way, and hence reused by more users.

The eventual goal is to enable Scheduler Framework to fit more kinds of workload, so that Kubernetes itself can be more widely adopted as well.

/sig scheduling
/cc @ahg-g @ravisantoshgudimetla @hex108 @denkensk @everpeace

**Comment by hex108** [comment]
I strongly aggree it!

It will be better if community could maintain common scheduler plugins in a SIG sub-repo(e.g. same as http://github.com/kubernetes-csi, it contains a lot of plugins). I once thought we could incoperate some of them into the default scheduler code base if they are widely used. Howerver it will make schedule more complex, it needs more consideration.

Pros and cons from my perspective:
* The plugins code are under control, we could make some quality assurance for them. Howerver it needs some effort.
* We could aovid some repetitive work if plugins are developed in a same repo.

**Comment by everpeace** [comment]
Yes, I agree it, too! 

> It will be better if community could maintain common scheduler plugins in a SIG sub-repo

+1 because custom scheduler using scheduling framework can be compiled independently. So separated repo can demonstrate in the realistic example.

**Comment by damemi** [comment]
+1 for a separate sub-repo for us and the community to work on plugins. 

Maybe at some point we could also consider an index for plugins (similar to Krew for cli plugins) to encourage 3rd party plugin development without restricting contributors to our development cycle and freeing us from owning every plugin.

**Comment by everpeace** [comment]
> Maybe at some point we could also consider an index for plugins (similar to Krew for cli plugins)

wow, interesting idea.

**Comment by ravisantoshgudimetla** [comment]
+1 to the suggestion.

I think initial goals of the sig-sponsored repo should be
-  Would be to validate the extension mechanism of the scheduler plugin framework for complex examples like batch workloads
- Serve as an example to end-users on how to use develop plugins. 

We can always make the repo to be an index of plugins once we see people want to have a common location where all the plugin can be stored.

/cc @swatisehgal

**Comment by swatisehgal** [comment]
Thanks for pointing me to this. Will have a look and see use this framework to push [Telemetry Aware Scheduling](https://github.com/intel/telemetry-aware-scheduling) code here!

**Comment by ahg-g** [comment]
+1 This is exciting!

**Comment by Huang-Wei** [comment]
https://github.com/kubernetes-sigs/scheduler-plugins is live. Closing this issue.
