### ISSUE TITLE
Pod with restartPolicy: Always was not restarted 

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#85831]
**What happened**:
Pod was not restarted with error:
```
predicate.go:75] Failed to admit pod openpalette-broker-924cbc0a-1d08-47c3-968e-bcb4fc5a0cd1-1-zhq2d_opcs(68ff947d-12f8-11ea-af20-744aa400db46) - Update plugin resources failed due to failed to write checkpoint file "kubelet_internal_checkpoint": write /var/lib/kubelet/device-plugins/.449002141: no space left on device, which is unexpected.
predicate.go:75] Failed to admit pod iag-192.113.5.13_kube-system(4272d198e0e30f0de9f5eef7d0799ebc) - Update plugin resources failed due to failed to write checkpoint file "kubelet_internal_checkpoint": write /var/lib/kubelet/device-plugins/.525042640: no space left on device, which is unexpected.
```
openpalette-broker-924cbc0a-1d08-47c3-968e-bcb4fc5a0cd1-1-zhq2d is a pod with nodeAffinity.
```
NAME                                                              READY   STATUS                     RESTARTS   AGE
openpalette-broker-924cbc0a-1d08-47c3-968e-bcb4fc5a0cd1-1-zhq2d   0/1     UnexpectedAdmissionError   0          3d2h
```

iag-192.113.5.13 is a static pod.
**What you expected to happen**:
Pod can be restarted.
**How to reproduce it (as minimally and precisely as possible)**:
This accoured when disk is full.Some pods can't be restarted when disk is free.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.6

**Other**:
I'm not sure if this is similar with #72202

**Comment by tedyu** [comment]
```
Some pods can't be restarted when disk is free
```
Were the pods on the node where disk was full ?

**Comment by lojies** [comment]
@tedyu, yes.

**Comment by zouyee** [comment]
/var/lib/kubelet/device-plugins/.525042640 no space left on device

**Comment by liggitt** [comment]
A restart policy means the kubelet will attempt to restart the containers (which it is doing). error conditions (like the disk being full) can prevent the restart from succeeding. Based on the error, you need to free space on the disk.

**Comment by lojies** [comment]
> A restart policy means the kubelet will attempt to restart the containers (which it is doing). error conditions (like the disk being full) can prevent the restart from succeeding. Based on the error, you need to free space on the disk.

But when i free the disk, the pod is still not restarted.
