### ISSUE TITLE
Object exceeds last-applied-configured annotation

### ISSUE THREAD

**Issue by sh0rez** [kubernetes/kubernetes#85840]
Original issue: https://github.com/kubernetes/kubectl/issues/712

**What happened**: Tried to apply a very large `ConfigMap`, which failed because of the size limit on the `last-applied-configuration` annotation.

**What you expected to happen**: The `ConfigMap` being applied normally

**How to reproduce it (as minimally and precisely as possible)**:
Apply a `ConfigMap` with data bigger than 256kb.

**Anything else we need to know?**:
This limit feels artificial. `etcd` allows data up to 1mb, only the annotation limits us here.  
It seems like `kubectl` needs the annotation to compute the patch it applies. It does not seem to need the actual values, just the keys of the structure. Would it be possible to redact the actual data and only store the keys of the JSON structure?

**Environment**:
- `kubectl` version: `master`

/sig cli

**Comment by liggitt** [comment]
> Would it be possible to redact the actual data and only store the keys of the JSON structure?

This is not possible to change for the client-side apply algorithm, but is how the server-side-apply feature in-progress works. Closing in favor of https://github.com/kubernetes/enhancements/issues/555

/close

**Comment by sh0rez** [comment]
Hi, I am aware of server side apply, but it is only available on recent Kubernetes versions. 

Still, we cannot neglect there are older versions around that are affected by this issue, so server side apply is not an adequate solution. Thus, we shall probably find a way to solve this in kubectl itself. WDYT?

/reopen

**Comment by liggitt** [comment]
The structure and format of the last-applied annotation is fundamental to the current client-side apply design. Rather than investing resources in changing that design, the server-side apply work is being prioritized.

/close
