### ISSUE TITLE
kube-scheduler: customizable victim selection logic in preemption 

### ISSUE THREAD

**Issue by everpeace** [kubernetes/kubernetes#85871]
## What would you like to be added

kube-scheduler allows to select victims in custom logics when preemption happens.

## Background: How kube-scheduler selects victim pods in preemption

When `kube-scheculer` preempts some pods, it selects candidate victim pods in a node roughly as follows:

- selects lower priority pods in the node first
- reprieves some pods among those until preemptor pods fits to the node
  - PDB violation pods is firstly reprieved
  - and for non-PDB violation pods, `pod.spec.priority` decides the order of reprieving
  - **note that the order in the same priority value is *undecided(i.e. random)*** because [scheduler's `SortableList.Sort()`](https://github.com/kubernetes/kubernetes/blob/v1.13.3/pkg/scheduler/util/https://github.com/golang/go/blob/go1.13.1/src/sort/sort.go#L67) used in [sorting victim candidates](https://github.com/kubernetes/kubernetes/blob/v1.13.3/pkg/scheduler/core/generic_scheduler.go#L994) is not stable sort
- calls extenders (if exist) to victims *selected above* (chaining extenders if multiple extenders exist)

note: _actual function is [here](https://github.com/kubernetes/kubernetes/blob/v1.16.3/pkg/scheduler/core/generic_scheduler.go#L1071-L1162) and [here (calling extenders)](https://github.com/kubernetes/kubernetes/blob/v1.16.3/pkg/scheduler/core/generic_scheduler.go#L351-L357)_

## Why is this needed

I'm operating kubernetes cluster with multi-thousands of GPUs and its main workload is deep learning (training).  Typical job duration is several hours to days (there are several weeks for longer jobs). To promote fair use of cluster, we define several `PriorityClass`es.

In the context deep learning job cluster, even if the priority values of victim candidates are the same, we would like to select victims in our custom measures like:

- job duration (jobs started just now might be safer to preempt)
- how long does the current epoch will be expected to be finished? (if the epoch just started and the snapshot of the last epoch snapshot available, it might be safer to preempt)
- how much the training converged? (if well converged, the job is safer to preempt than others).
- etc.

Moreover, the job's priority can be varied for long-running jobs for various reasons (user's careless configuration, company-wide project importance).

## Design proposal (rough)

Introduce new extension point in scheduling framework to select victims so that user can fully control victim selection.

- Pros
  - Flexible enough
  - No race condition happens (user can use any external information to choose victims)
  - No changes to existed apis
- Cons
  - Scheduling framework changes(just adding ) by definition (need KEP probably)
  - Change amount is big (moderate?)

## Consideration for alternative designs

- Change to pass all the lower priority pods to extender's `Preempt` endpoint?
  - Pros
    - Easy and small changes
  - Cons
    - This breaks api compatibility (not breaking interface technically but breaking semantics)
- Make `pod.spec.priorityClass` fields mutable
  - Pros
    - No change might be needed in kube-scheduler
    - User can implement some controller for adjusting pod's priority class dynamically
  - Cons
    - Api changes semantically
    - It might need to apply `Priority` admission webhook in updating pods
    - In long running job cluster, priority in scheduling (when placing pods) and priority in preemption (when selecting victims) sometimes different. So, changing `pod.spec.priority` might not fit in some cases.
- Introduce some mutable field in pod spec to define victim score
  - Pros
    - Intuitive and user friendly
    - User can control the field value
    - Small changes in kube-scheduler (just selecting victims in the order of the score)
  - Cons
    - api changes
    - dynamic victim score is really suitable for pos _specification_?
    - race condition might happen because scheduler uses stable node info cache in the scheduling cycle
- kube-scheduler support some victim score annotation (e.g. `scheduling.k8s.io/victim-score`) in pods
  - Pros
    - Intuitive, user friendly
    - User can control the field value
    - Small changes in kube-scheduler (just selecting victims in the order of the score)
    - no api changes
  - Cons
    - race condition might happen because scheduler uses stable node info cache in the scheduling cycle

---
/sig scheduling
let me ping @ahg-g @Huang-Wei because we talked about this topic in KubeCon San Diego 🙇 
If design was agreed and fixed, I'm happy to contribute to solving the issue.

**Comment by Huang-Wei** [comment]
Thanks @everpeace for this detailed write-up!

I'm leaning towards the option to define several extension points such as PrePreempt, Preempt, PostPreempt to expose more control of the preemption logic to end-users. And this is also aligned with our Scheduler Framework roadmap.

**Comment by everpeace** [comment]
Thanks @Huang-Wei for your quick reply!  

> extension points such as PrePreempt, Preempt, PostPreempt to expose more control of the preemption logic to end-users. And this is also aligned with our Scheduler Framework roadmap.

I totally agree!   This requires to update [KEP document of scheduling framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md), right? Then, I would like to start drafting an updated KEP.

**Comment by ahg-g** [comment]
Thanks @everpeace I think it is reasonable to explore your first proposal further with more concrete answers to the following two questions:

1) What would the signature of the new extension point look like.
2) Where will it be invoked.

I am happy to add this to our tracker for 1.18 and review PRs for this feature.

**Comment by ahg-g** [comment]
> Thanks @Huang-Wei for your quick reply!
> 
> > extension points such as PrePreempt, Preempt, PostPreempt to expose more control of the preemption logic to end-users. And this is also aligned with our Scheduler Framework roadmap.
> 
> I totally agree! This requires to update [KEP document of scheduling framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md), right? Then, I would like to start drafting an updated KEP.

Sounds good to me, lets see what exactly you have in mind.

**Comment by Huang-Wei** [comment]
Just one more comment is that, considering we already have pretty a lot of work in our place in 1.18, for this feature, I think we can come up with a KEP (or modifying existing KEP) in 1.18, and then start implementation in the next release.

**Comment by everpeace** [comment]
> Sounds good to me, let's see what exactly you have in mind.

> I think we can come up with a KEP (or modifying existing KEP) in 1.18, and then start implementation in the next release.

Thanks.  I would like to finish writing up KEP (I will update the existing KEP) first.  Once my draft was ready for review, I will open an issue in kubernetes/enhancement repo.

**Comment by everpeace** [comment]
@ahg-g @Huang-Wei I drafted my first version of updating KEP ↑.  Please take a look at it 🙇

**Comment by everpeace** [comment]
I'm closing this issue because https://github.com/kubernetes/kubernetes/issues/91038 introduces `PostFilter` scheduler plugin which can implement custom preemption logic.
