### ISSUE TITLE
Kubernetes all nodes going bad, after reboot it is recovered.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#85888]
/sig node
/sig pod

what happened:
After keeping kubernetes for longer run. Nodes are going bad .
We are running 3 nodes (2 worker + 1 master as worker) .
We are running total 51 pods , out of which we are volume mounting(glusterfs volume mount) kafka,etcd,logstash,consul,influxdb .

deploy1 kubelet[3227]: W1128 13:51:21.059723    3227 container.go:393] Failed to create summary reader for "/system.slice/run-reb5c5dcf384d46dfba557b5e7bede185.scope": none of the resources are being tracked.
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.074384    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.074605    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.074851    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.074902    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/system.slice/run-r627a008b62d7450c9fd1271e030b82eb.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.077273    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.077324    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.077361    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.077391    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/system.slice/run-r954ff339f3ff493b8e25ee598ddd40cd.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.077471    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r9e2f0005442d48168897359373b590aa.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/system.slice/run-r9e2f0005442d48168897359373b590aa.scope: no such file or directory
Nov 28 13:51:21 deploy1 kubelet[3227]: W1128 13:51:21.077503    3227 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/run-r9e2f0005442d48168897359373b590aa.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/system.slice/run-r9e2f0005442d48168897359373b590aa.scope: no such file or directory

----------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
 kubelet[3227]: 2019-11-28 13:51:09.123 [WARNING][8491] ipam.go 792: CAS error for block, retry #2: update conflict: 'BlockKey(cidr=10.233.121.64/26)'
Nov 28 13:51:09 deploy1 kernel: [  185.752300] aufs au_opts_verify:1597:dockerd[3356]: dirperm1 breaks the protection by the permission bits on the lower branch
Nov 28 13:51:09 deploy1 kubelet[3227]: 2019-11-28 13:51:09.124 [INFO][7626] ipam.go 877: Decremented handle 'cni0.aaaefdc67e3fbd7d371c66f97ce25b68f7183e56a27de209b7b8044a72cb3a31' by 1
Nov 28 13:51:09 deploy1 kubelet[3227]: 2019-11-28 13:51:09.124 [WARNING][8705] ipam.go 792: CAS error for block, retry #1: update conflict: 'BlockKey(cidr=10.233.121.64/26)'
Nov 28 13:51:09 deploy1 kubelet[3227]: 2019-11-28 13:51:09.124 [WARNING][8492] ipam.go 792: CAS error for block, retry #2: update conflict: 'BlockKey(cidr=10.233.121.64/26)'
-------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------

deploy1 kubelet[3227]: E1128 13:51:01.932631    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.932744    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.932791    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.932845    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.932890    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933083    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933128    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933330    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933525    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933545    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933654    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933887    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.933927    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath
Nov 28 13:51:01 deploy1 kubelet[3227]: E1128 13:51:01.934039    3227 reconciler.go:376] Could not construct volume information: impossible to reconstruct glusterfs volume spec from volume mountpath

What you expected to happen:
Pods should be up and running, vm should be accessible.

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version):
Kubernetes v1.9.5
glusterfs version 
5.9

Cloud provider or hardware configuration:
VirtualBox(5) Vms with 16GB RAM and 8cpu's
OS (e.g: cat /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Kernel (e.g. uname -a):
Linux demo3 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by altreze** [comment]
Could you share :

```
cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
cat /var/lib/kubelet/kubeadm-flags.env
cat /etc/docker/daemon.json
```

**Comment by akshaysharama** [comment]
We are Installing kubernetes using kubespray.

10-kubeadm.conf 
{
  "name": "cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
          "nodename": "demo3",
          "type": "calico",
      "etcd_endpoints": "https://xx.xx.xxx.xx:2379",
      "etcd_cert_file": "/etc/ssl/etcd/ssl/node-demo3.pem",
      "etcd_key_file": "/etc/ssl/etcd/ssl/node-demo3-key.pem",
      "etcd_ca_cert_file": "/etc/ssl/etcd/ssl/ca.pem",
      "log_level": "info",
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "ipv4_pools": ["10.233.64.0/18"]
      },
              "kubernetes": {
        "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml"
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
-----------------------------------



usr/bin/dockerd --insecure-registry=10.233.0.0/18 --graph=/var/lib/docker --log-opt max-size=50m --log-opt max-file=5 --iptables=false --dns 10.233.0.3 --dns xxx.xx.xxx.xx --dns-search default.svc.cluster.local --dns-search svc.cluster.local --dns-opt ndots:2 --dns-opt timeout:2 --dns-opt attempts:2
