### ISSUE TITLE
Guestbook example - how a Docker container is started with a specific command and a list of environment variables from Kubernetes?

### ISSUE THREAD

**Issue by kcao3** [kubernetes/kubernetes#8589]
Hello,
I would like to know how Kubernetes starts a Docker container if this container belongs to a Kubernetes Pod. Specifically, when a Docker container managed by a Pod is started by a Kubelet on a particular node, how the environment variables inside the Docker container are set. Also, with Kubernetes, how does a container in a Pod is started with a specific command. 

Take for example, in the GuestBook example https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook the following JSON document is used to create the redis-slave replication controller:
{
   "kind":"ReplicationController",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"redis-slave",
      "labels":{
         "name":"redis-slave"
      }
   },
   "spec":{
      "replicas":2,
      "selector":{
         "name":"redis-slave"
      },
      "template":{
         "metadata":{
            "labels":{
               "name":"redis-slave"
            }
         },
         "spec":{
            "containers":[
               {
                  "name":"slave",
                  "image":"kubernetes/redis-slave:v2",
                  "ports":[
                     {
                        "containerPort":6379,
                        "protocol":"TCP"
                     }
                  ]
               }
            ]
         }
      }
   }
}

When this redis-slave rc is created, I notice that two redis-slave Pods are created and running on 
the nodes. On one of my node, I ran the docker ps command. The following is the output I received:

core@ip-172-31-40-136 ~ $ docker ps
CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS              PORTS               NAMES
f4f887733ef0        kubernetes/redis-slave:v2              "/bin/sh -c /run.sh"   About an hour ago   Up About an hour                        k8s_slave.7337356c_redis-slave-k8e0d_default_fd44dca8-ff24-11e4-8098-067eb345dfd3_952ff6b8

This indicates that I have a running container with an ID of f4f887733ef0. The output also shows 
me the commands that were used when the container was started: /bin/sh -c /run.sh. If these commands are NOT set from the replication controller JSON document file,  does anyone know where and how these commands were set from Kubernetes?
Also when running the docker inspect command on this container, I discovered several environment
variables are set. The following shows the actual output I received:

core@ip-172-31-40-136 ~ $ docker inspect f4f887733ef0
[{
    "AppArmorProfile": "",
    "Args": [
        "-c",
        "/run.sh"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/bin/sh",
            "-c",
            "/run.sh"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "KUBERNETES_PORT_443_TCP_ADDR=10.100.0.2",
            "REDIS_SLAVE_PORT=tcp://10.100.96.172:6379",
            "KUBE_DNS_SERVICE_PORT=53",
            "KUBE_DNS_PORT_53_TCP_PORT=53",
            "KUBERNETES_SERVICE_HOST=10.100.0.2",
            "KUBERNETES_PORT=tcp://10.100.0.2:443",
            "KUBERNETES_PORT_443_TCP=tcp://10.100.0.2:443",
            "KUBE_DNS_PORT_53_TCP_ADDR=10.100.0.10",
            "KUBERNETES_RO_PORT_80_TCP_ADDR=10.100.0.1",
            "KUBE_DNS_SERVICE_PORT_DNS_TCP=53",
            "KUBE_DNS_PORT=udp://10.100.0.10:53",
            "REDIS_MASTER_PORT_6379_TCP_PROTO=tcp",
            "REDIS_SLAVE_SERVICE_PORT=6379",
            "REDIS_SLAVE_PORT_6379_TCP=tcp://10.100.96.172:6379",
            "CASSANDRA_PORT=tcp://10.100.148.34:9042",
            "CASSANDRA_PORT_9042_TCP_ADDR=10.100.148.34",
            "KUBE_DNS_SERVICE_PORT_DNS=53",
            "KUBERNETES_PORT_443_TCP_PROTO=tcp",
            "KUBERNETES_RO_PORT_80_TCP=tcp://10.100.0.1:80",
            "REDIS_MASTER_SERVICE_PORT=6379",
            "REDIS_MASTER_PORT=tcp://10.100.56.195:6379",
            "REDIS_SLAVE_PORT_6379_TCP_PROTO=tcp",
            "CASSANDRA_SERVICE_PORT=9042",
            "KUBE_DNS_PORT_53_TCP=tcp://10.100.0.10:53",
            "KUBERNETES_RO_SERVICE_PORT=80",
            "REDIS_MASTER_PORT_6379_TCP=tcp://10.100.56.195:6379",
            "REDIS_SLAVE_PORT_6379_TCP_ADDR=10.100.96.172",
            "KUBE_DNS_SERVICE_HOST=10.100.0.10",
            "KUBE_DNS_PORT_53_UDP_PROTO=udp",
            "KUBERNETES_PORT_443_TCP_PORT=443",
            "KUBERNETES_RO_PORT_80_TCP_PROTO=tcp",
            "REDIS_MASTER_PORT_6379_TCP_ADDR=10.100.56.195",
            "CASSANDRA_PORT_9042_TCP=tcp://10.100.148.34:9042",
            "KUBE_DNS_PORT_53_UDP_PORT=53",
            "KUBERNETES_RO_PORT_80_TCP_PORT=80",
            "REDIS_MASTER_SERVICE_HOST=10.100.56.195",
            "REDIS_SLAVE_SERVICE_HOST=10.100.96.172",
            "REDIS_SLAVE_PORT_6379_TCP_PORT=6379",
            "CASSANDRA_SERVICE_HOST=10.100.148.34",
            "KUBE_DNS_PORT_53_UDP_ADDR=10.100.0.10",
            "KUBERNETES_RO_PORT=tcp://10.100.0.1:80",
            "KUBERNETES_RO_SERVICE_HOST=10.100.0.1",
            "REDIS_MASTER_PORT_6379_TCP_PORT=6379",
            "CASSANDRA_PORT_9042_TCP_PROTO=tcp",
            "CASSANDRA_PORT_9042_TCP_PORT=9042",
            "KUBE_DNS_PORT_53_UDP=udp://10.100.0.10:53",
            "KUBE_DNS_PORT_53_TCP_PROTO=tcp",
            "KUBERNETES_SERVICE_PORT=443",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/root"
        ],
        "ExposedPorts": {
            "6379/tcp": {}
        },
        "Hostname": "redis-slave-k8e0d",
        "Image": "kubernetes/redis-slave:v2",
        "Labels": {
            "io.kubernetes.pod.name": "default/redis-slave-k8e0d"
        },
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/data": {}
        },
        "WorkingDir": "/data"
    },
    "Created": "2015-05-20T19:18:26.428891137Z",
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/var/lib/kubelet/pods/fd44dca8-ff24-11e4-8098-067eb345dfd3/containers/slave/f4f887733ef08dc70744820d06e9e22bd547d047846fd3c2dce0154edc38478c:/dev/termination-log"
        ],
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": null,
        "Dns": [
            "10.100.0.10",
            "172.31.0.2"
        ],
        "DnsSearch": [
            "default.kubernetes.default.kubernetes.local",
            "default.svc.kubernetes.default.kubernetes.local",
            "svc.kubernetes.default.kubernetes.local",
            "kubernetes.default.kubernetes.local",
            "ec2.internal"
        ],
        "ExtraHosts": null,
        "IpcMode": "container:9458307fc393fec23d540ca0f251844a27c612b048277f1790e852a669c08cb8",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "container:9458307fc393fec23d540ca0f251844a27c612b048277f1790e852a669c08cb8",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/9458307fc393fec23d540ca0f251844a27c612b048277f1790e852a669c08cb8/hostname",
    "HostsPath": "/var/lib/docker/containers/9458307fc393fec23d540ca0f251844a27c612b048277f1790e852a669c08cb8/hosts",
    "Id": "f4f887733ef08dc70744820d06e9e22bd547d047846fd3c2dce0154edc38478c",
    "Image": "48a1e2b8f8599f083b09bd0b451dc062fe3ca54f4255d81e89699667cfddc0aa",
    "LogPath": "/var/lib/docker/containers/f4f887733ef08dc70744820d06e9e22bd547d047846fd3c2dce0154edc38478c/f4f887733ef08dc70744820d06e9e22bd547d047846fd3c2dce0154edc38478c-json.log",
    "MountLabel": "",
    "Name": "/k8s_slave.7337356c_redis-slave-k8e0d_default_fd44dca8-ff24-11e4-8098-067eb345dfd3_952ff6b8",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "/bin/sh",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/9458307fc393fec23d540ca0f251844a27c612b048277f1790e852a669c08cb8/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 7199,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-05-20T19:18:26.520408506Z"
    },
    "Volumes": {
        "/data": "/var/lib/docker/vfs/dir/56462ec2be678369a74fbb84c58aba34f16a2b4dbf3856c83f34173673a3365c",
        "/dev/termination-log": "/var/lib/kubelet/pods/fd44dca8-ff24-11e4-8098-067eb345dfd3/containers/slave/f4f887733ef08dc70744820d06e9e22bd547d047846fd3c2dce0154edc38478c"
    },
    "VolumesRW": {
        "/data": true,
        "/dev/termination-log": true
    }
}
]

Does anyone know how the parameters in the "Config" section such as the "Cmd", "Env", "Dns", and 
"DnsSearch" are set when the container is starting up? Also which Kubernetes component is responsible for doing this part?

**Comment by yujuhong** [comment]
> Also which Kubernetes component is responsible for doing this part?

[kubelet](https://github.com/GoogleCloudPlatform/kubernetes/blame/master/pkg/kubelet) is responsible for starting docker containers.

> Does anyone know how the parameters in the "Config" section such as the "Cmd", "Env", "Dns",

The parameters are set through the [docker API](https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-a-container). More specifically, we use [go-dockerclient](https://github.com/fsouza/go-dockerclient). Was your question about "why" we set these parameters and "how" do we generate them?

> The output also shows 
> me the commands that were used when the container was started: /bin/sh -c /run.sh. If these commands are NOT set from the replication controller JSON document file, does anyone know where and how these commands were set from Kubernetes?

Kubernetes does not set the command if you don't provide one.  By default, docker would use the command provided by the image file.
