### ISSUE TITLE
Remove priorities execution path in schedule core [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85917]
The priorities execution path in core scheduler is now not used, priorities are now executed as Score plugins. As part of phase 2 of the framework migration, this execution path should be removed.

/assign @damemi 
/sig scheduling
/priority important-soon

Part of #85822

**Comment by ahg-g** [comment]
> /assign

this is already assigned.

**Comment by wgliang** [comment]
> > /assign
> 
> this is already assigned.

Sorry, I did not notice.
/usassign

**Comment by ahg-g** [comment]
This is done.
