### ISSUE TITLE
Remove predicates execution path in schedule core [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85918]
The predicates execution path in core scheduler is now not used, priorities are now executed as Filter plugins. As part of phase 2 of the framework migration, this execution path should be removed.

/assign @Huang-Wei  
/sig scheduling
/priority important-soon

Part of #85822

**Comment by ahg-g** [comment]
> /assign

this is already assigned.

**Comment by wgliang** [comment]
> > /assign
> 
> this is already assigned.

Sorry, I did not notice.
/usassign
