### ISSUE TITLE
Break priority metadata computation into post-filter plugins [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#85924]
Priorities metadata should be broken into post-filter plugins. This issue excludes even pods spread and affinity, which we have separate issues for them.

/assign @ravisantoshgudimetla 
/sig scheduling
/priority important-soon

Part of #85822

**Comment by draveness** [comment]
/cc

I could take on this if @ravisantoshgudimetla is not available these days.

**Comment by ahg-g** [comment]
we are doing this one by one, we actually don't need this anymore.
