### ISSUE TITLE
Simple command for viewing kubectl current-context?

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#8593]
If you want to see what the current-context for your client is, you can run
`kubectl config view --minify`
but that shows you the full config associated with the current-context. If you want *just* the current-context, you have to use a template
`kubectl config view -o template --template='{{ index . "current-context" }}'`
Not great ux. Should we add a command to view just the current-context? e.g.
`kubectl config current`

cc @ghodss, @deads2k, @bgrant0607

**Comment by bgrant0607** [comment]
or `kubectl config view --current`?

**Comment by thockin** [comment]
`kubectl config view current`  or `view --current` or `view-current` or `cur-context` or anything that is more obvious and discoverable.

I'd also like something that shows me all available contexts without all the details - just a list.  `kubectl config view -q` or `kubectl config list` or something?

**Comment by deads2k** [comment]
Do you want the current-context in order to describe it to a user or to describe it to a machine in scripting?

For the former, it might be more useful to explode the content into sentence like, 
```
Using context "my-context", working in the "foo" namespace on server "https://bar" as user "deads"
```
  When I'm trying to figure out what I'm working against, I don't always remember what all the contexts are, but I do recognize servers and users.  Output like that provides both and allows users to get a message they can understand.  I don't feel as bad about having scripts have to run an ugly template.

Maybe call it `kubectl config context`.  Have the current output by default and a `--list` option to print out all the options?

**Comment by thockin** [comment]
I think I can adapt to whatever, but what I would expect, as a long-time
UNIX user and git user is something like:


```
$ kubectl config current
thockin-dev_kubernetes

$kubectl config view thockin-dev_kubernetes
<yaml dump of the one context>

$ kubectl config view
<yaml dump of all contexts>

$kubectl config summary
<one line per context>
context          namespace  server         user
my-context    foo                https://bar   deads
```

**Comment by tombenner** [comment]
Quick bump on this. Our config is too long to visually scan, so I use an alias to print the current context, but I'd love to remove the alias in favor of an official subcommand. We're hoping to have more of the team using Kubernetes soon, and the fewer aliases we have to share, the better.

This seems like a common need. If it'd help move it forward (and if there's a consensus around the subcommand's format), I'd be happy to implement it/open a PR.

**Comment by jlowdermilk** [comment]
@tombenner, if you have cycles to open a PR, I'd be happy to review it. I think calling it
```
kubectl config current-context
```
is reasonable, but that's an easy detail to decide in the PR.

**Comment by michalpiasecki1** [comment]
> In case you came here looking, like me, the command to get the name of the current context is:
> 
> `kubectl config current-context`

we need more people like this guy

**Comment by Smaxor5** [comment]
> > In case you came here looking, like me, the command to get the name of the current context is:
> > `kubectl config current-context`
> 
> we need more people like this guy

This guy 2020

**Comment by akifcardak** [comment]
You can also use `kubectx` to switch the context when necessary and can see the current context simply by `kubectx -c`.
