### ISSUE TITLE
kubernetes e2e tests images for arch mips64el

### ISSUE THREAD

**Issue by zhanw15** [kubernetes/kubernetes#85932]
Hi,  In order to verify the availability of cluster on mips, we build needed images and complete the e2e tests. I think it will be better if I put this images into an open repo, to help who what to do e2e tests on mips. So, how can I do to push this images and others can do e2e tests on mips directly?
**What would you like to be added**:
Add e2e tests images for arch mips64el.
**Why is this needed**:
Do kubernetes e2e tests on mips, see PR https://github.com/cncf/k8s-conformance/pull/779.

**Comment by ydcool** [comment]
It there a clear solution can we submit those docker images? @hh

**Comment by dankohn** [comment]
Note that the goal is not to contribute existing a Docker images but to build new ones on the Mio’s architecture as part of the regular build process.

**Comment by ydcool** [comment]
@dankohn Yes you're right, we're taking effort to this but not complete yet, I wonder if we could prove our conformance test results by providing those images.
