### ISSUE TITLE
Compiling the kubelet in providerless mode is broken for release-1.14 & release-1.15

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/kubernetes#85941]
**What happened**: Compiling the kubelet in providerless mode fails with

```shell
# k8s.io/kubernetes/pkg/cloudprovider/providers/azure
pkg/cloudprovider/providers/azure/azure_controller_common.go:66:13: undefined: lockMap
```

This is the issue for both
- [release-1.14](https://hush-house.pivotal.io/teams/k8s-c10s/pipelines/kind/jobs/kind%20master%20with%20k8s-current-minus-2/builds/259)
- [release-1.15](https://hush-house.pivotal.io/teams/k8s-c10s/pipelines/kind/jobs/kind%20master%20with%20k8s-current-minus-1/builds/254)

**What you expected to happen**: No compilation error

**How to reproduce it (as minimally and precisely as possible)**:

```shell
mkdir /tmp/lockless && cd /tmp/lockless
git clone https://github.com/kubernetes/kubernetes && cd kubernetes
GOFLAGS=-tags=providerless KUBE_VERBOSE=0 KUBE_BUILD_PLATFORMS=linux/amd64 ./build/run.sh make all WHAT=cmd/kubelet
# ==> fails
```

**Anything else we need to know?**:

Those are most probably the CPs that have introduced the issue:
- release-1.14: https://github.com/kubernetes/kubernetes/pull/85832
- release-1.15: https://github.com/kubernetes/kubernetes/pull/85830

[release-1.16](https://hush-house.pivotal.io/teams/k8s-c10s/pipelines/kind/jobs/kind%20master%20with%20k8s-current/builds/255) & [master](https://hush-house.pivotal.io/teams/k8s-c10s/pipelines/kind/jobs/kind%20master%20with%20k8s-master/builds/262) seem to be fine.

The original PR which has been cherry-picked into the releases is https://github.com/kubernetes/kubernetes/pull/85115.

/assign @aramase @andyzhangx
/kind bug
/sig cloud-provider
/area provider/azure

**Environment**:
- Kubernetes version (use `kubectl version`): release-1.1{4,5}
- Cloud provider or hardware configuration: providerless
- OS (e.g: `cat /etc/os-release`): (compiling on) Darwin (via docker) and Linux
- Kernel (e.g. `uname -a`): -
- Install tools: -
- Network plugin and version (if this is a network-related bug): -
- Others: -

**Comment by hoegaarden** [comment]
/assign
I am currently preparing patches for 1.14 & 1.15

**Comment by liggitt** [comment]
the providerless tag is not supported in 1.14/1.15, I would not expect to be able to use it with builds in those branches

**Comment by hoegaarden** [comment]
"providerless" (building with the tag `providerless`) is only a thing starting with 1.16. Before 1.16 the tag should be a noop. By cherry-picking https://github.com/kubernetes/kubernetes/pull/85115 we however brought something in that is ignored when building with the tag `providerless`, thus this tag isn't a noop anymore. The azure package is now half excluded when this tag is used and therefor won't compile.

IMHO we either should backport all the `providerless` stuff or none of it, but not half. The merged PRs are removing all `providerless` things again from release-1.14 / release-1.15 after they have by accident been cherry-picked back from master.

**Comment by liggitt** [comment]
Successfully building 1.14 or 1.15 with a providerless tag is misleading. Anyone doing that is not getting the result they think they are.

**Comment by hoegaarden** [comment]
> Successfully building 1.14 or 1.15 with a providerless tag is misleading.

> Anyone doing that is not getting the result they think they are.

I see that point. However before CP'ing https://github.com/kubernetes/kubernetes/pull/85115 that was the case, too. People building with `providerless` didn't get providerless, either. pre-1.16 the `providerless` tag is nothing special, and my intention was to keep it that way.

Honestly, IMHO it still seems reasonable to keep the behaviour re tags in the older releases and not introducing new tags "mid release", however I don't have a strong opinion about that and I am also happy to revert those two PRs.

Anyone else want to chime in? @kubernetes/patch-release-team @aramase @andyzhangx

**Comment by liggitt** [comment]
To avoid churn, I wouldn't push for a revert, but I also wouldn't feel any obligation to make a build with providerless tags succeed in 1.14/1.15 going forward.
