### ISSUE TITLE
Getting "Forbidden error while adding more than one volumeClaimTemplate to statefulSet"

### ISSUE THREAD

**Issue by RaghunathN** [kubernetes/kubernetes#85955]
What happened:
We tried to create dynamic mount using volumeClaimTemplate on AKS platform using Azure disks, it worked fine.
But when we tried to add another dynamic mount its failing with below error 
 
![image](https://user-images.githubusercontent.com/40556496/70250367-c9bdf900-17a3-11ea-9fa6-ac6bd4aedf58.png)

Please refer below for the sample template  of the yaml file
 volumeMounts:
      {{- if .Values.Common.PersistenVolumeClaim.AutoCreate }}
          - name: masterlogs
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/logs/container
          #- name: masterlogs
          #  mountPath: /opt/WebSphere/Liberty/usr/servers/default/logs/container
          - name: slaveindex
            mountPath: /mnt/search-index
      {{- end }}
      {{- if .Values.Common.Binding_ConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config   
      {{- end }}
      
  volumeClaimTemplates:
  - metadata:
      name: masterlogs
      namespace: echannel
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "eclogs"
      resources:
        requests:
          storage: 1Ti
  - metadata:
      name: slaveindex
      namespace: echannel
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ecslaveindex"
      resources:
        requests:
          storage: 3Gi

**Environment**:
- Kubernetes version : 1.14.7
- Cloud provider or hardware configuration: Azure Kubernetes Service

[search-app-master.zip](https://github.com/kubernetes/kubernetes/files/3927747/search-app-master.zip)

**Comment by liggitt** [comment]
/remove-kind bug

Updates to the volume claim template are not currently permitted. A feature request to permit this is open at https://github.com/kubernetes/kubernetes/issues/69041

/close
