### ISSUE TITLE
does kubernetes support latest nvidiad-docker

### ISSUE THREAD

**Issue by davidstack** [kubernetes/kubernetes#85978]
**What happened**:
the latest [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) change it usage method ,if we want start a container with GPU,we should  use this method:
`
docker run --gpus '"device=UUID-ABCDEF,1"' nvidia/cuda:9.0-base nvidia-smi
`
and docker 19.03 add one new parament --gpu

now k8s use deviceplugin to inset the gpu device uuid to conatienr env,  will the device plugin support insert --gpu method to container ?thanks
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
centos 7.4
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by davidstack** [comment]
kind/feature-requests

**Comment by pytimer** [comment]
What's progress this issue? I use docker 19.03.4 version and nvidia gpu, i also have the same issue, so i want to ask.

nvidia device plugin said that we still install nvidia-docker2 and use it. related document: https://github.com/NVIDIA/k8s-device-plugin#preparing-your-gpu-nodes
