### ISSUE TITLE
ERROR：Unable to attach or mount volumes，err=no volume plugin matched

### ISSUE THREAD

**Issue by yq513** [kubernetes/kubernetes#85979]
I deployed ceph, after creating the storage, the pod cannot be mounted on the PV, prompt
Unable to attach or mount volumes, err = no volume plugin matched

The main error message is as follows. What is the problem? Thank you.

Main------------
Created directory：
[root@k8s-m kubernetes]# cd /var/lib/kubelet/volumeplugins/
[root@k8s-m volumeplugins]# pwd
/var/lib/kubelet/volumeplugins

Added volume-plugin parameter：
[root@k8s-m kubernetes]# cat /opt/kubernetes/conf/kubelet.conf
KUBE_MASTER="--master=http://192.168.21.117:8080"
KUBELET_OPTS="--logtostderr=true \
--log-dir=/var/log/kubernetes/kubelet \
--v=4 \
--volume-plugin-dir=/var/lib/kubelet/volumeplugins \

ceph operator.ymal ：
- name: FLEXVOLUME_DIR_PATH
  value: "/var/lib/kubelet/volumeplugins"

After kubelet is started: Error getting volume limit for plugin：
[root@k8s-m kubernetes]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 二 2019-12-03 22:15:09 CST; 2 days ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 3302 (kubelet)
    Tasks: 21
   Memory: 62.7M
   CGroup: /system.slice/kubelet.service
           └─3302 /opt/kubernetes/bin/kubelet --logtostderr=true --log-dir=/var/log/kubernetes/kubelet --v=4 --volume-plugin-dir=/var/lib/kubelet/volu...

12月 06 09:23:49 k8s-m kubelet[3302]: I1206 09:23:49.772993    3302 prober.go:162] Exec-Probe Pod: &Pod{ObjectMeta:{calico-node-q9qct calico...n-hash:7d
12月 06 09:23:49 k8s-m kubelet[3302]: I1206 09:23:49.940048    3302 exec.go:43] Exec probe response: "2019-12-06 01:23:49.890 [INFO][2258] h...ed = 2\n"
12月 06 09:23:49 k8s-m kubelet[3302]: I1206 09:23:49.940097    3302 prober.go:129] Readiness probe for "calico-node-q9qct_kube-system(d978de...succeeded
12月 06 09:23:50 k8s-m kubelet[3302]: I1206 09:23:50.267285    3302 kubelet.go:1988] SyncLoop (housekeeping)
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.273124    3302 kubelet.go:2184] Container runtime status: Runtime Conditions: RuntimeRe... message:
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711001    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/cinder
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711030    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/gce-pd
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711040    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/aws-ebs
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711052    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/azure-disk
12月 06 09:23:52 k8s-m kubelet[3302]: I1206 09:23:52.267319    3302 kubelet.go:1988] SyncLoop (housekeeping)

pod mount PV error：
Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], unattached volumes=[default-token-gq92d mysql-persistent-storage]: 
failed to get Plugin from volumeSpec for volume "pvc-e4226e5f-04ec-4b4c-9884-53e46618a966" err=no volume plugin matched

Warning  FailedMount  31m (x610 over 10h)   kubelet, 192.168.21.118  Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], 
unattached volumes=[default-token-gq92d mysql-persistent-storage]: failed to get Plugin from volumeSpec 
for volume "pvc-9ec3d012-d434-4f8a-8791-33d3503b9316" err=no volume plugin matched
---------
CentOS Linux release 7.7.1908 (Core)
Linux k8s-m 3.10.0-1062.4.1.el7.x86_64
vmware
Rook version 1.1.7
ceph 1.14.2
Kubernetes 1.16.2
Storage backend status：
# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS      REASON   AGE
pvc-9ec3d012-d434-4f8a-8791-33d3503b9316   20Gi       RWO            Retain           Bound    default/mysql-pv-claim   rook-ceph-block            10h
pvc-af6818f9-2b21-461f-ad44-264d8ff294ff   20Gi       RWO            Retain           Bound    default/wp-pv-claim      rook-ceph-block            10h

**Comment by yuyiying** [comment]
Please provide entire info of storageclass and pvc for provisioning the volume. Thanks!

**Comment by yq513** [comment]
> Please provide entire info of storageclass and pvc for provisioning the volume. Thanks!

I use rook+ceph

[root@dk-node01 /]# ceph osd lspools
6 wcl-pool
[root@k8s-m ceph]# kubectl get storageclasses
NAME PROVISIONER AGE
rook-ceph-block ceph.rook.io/block 40s

[root@k8s-m kubernetes]# kubectl create -f wordpress.yaml
service/wordpress created
persistentvolumeclaim/wp-pv-claim created
deployment.apps/wordpress created
[root@k8s-m kubernetes]# kubectl create -f mysql.yaml
service/wordpress-mysql created
persistentvolumeclaim/mysql-pv-claim created
deployment.apps/wordpress-mysql created
[root@k8s-m kubernetes]# kubectl get pv
NAME CAPACITY ACCESS MODES RECLAIM POLICY STATUS CLAIM STORAGECLASS REASON AGE
pvc-56ba158b-d26d-486e-89e9-fac52bf28eca 20Gi RWO Retain Bound default/wp-pv-claim rook-ceph-block 10s
pvc-7ee6d95b-d9d4-4c29-95cd-0502367def27 20Gi RWO Retain Bound default/mysql-pv-claim rook-ceph-block 7s
[root@k8s-m kubernetes]# kubectl get pod
NAME READY STATUS RESTARTS AGE
dnsutils-ds-4ds7w 1/1 Running 70 2d20h
dnsutils-ds-fgck6 1/1 Running 68 2d20h
dnsutils-ds-tvcrp 1/1 Running 68 2d20h
wcl-nginx-886b56745-74z2k 1/1 Running 1 2d20h
wcl-nginx-886b56745-8hwm9 1/1 Running 1 2d20h
wordpress-578744754c-79fhz 0/1 ContainerCreating 0 4m24s
wordpress-mysql-5b697dbbfc-9s7vc 0/1 ContainerCreating 0 4m20s

[root@k8s-m kubernetes]# kubectl describe pod wordpress-578744754c-79fhz
Name: wordpress-578744754c-79fhz
Namespace: default
Priority: 0
Node: 192.168.21.118/192.168.21.118
Start Time: Fri, 06 Dec 2019 15:02:24 +0800
Labels: app=wordpress
pod-template-hash=578744754c
tier=frontend
Annotations:
Status: Pending
IP:
IPs:
Controlled By: ReplicaSet/wordpress-578744754c
Containers:
wordpress:
Container ID:
Image: wordpress:4.8-apache
Image ID:
Port: 80/TCP
Host Port: 0/TCP
State: Waiting
Reason: ContainerCreating
Ready: False
Restart Count: 0
Environment:
WORDPRESS_DB_HOST: wordpress-mysql
WORDPRESS_DB_PASSWORD: <set to the key 'password' in secret 'mysql-pass'> Optional: false
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from default-token-gq92d (ro)
/var/www/html from wordpress-persistent-storage (rw)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
wordpress-persistent-storage:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: wp-pv-claim
ReadOnly: false
default-token-gq92d:
Type: Secret (a volume populated by a Secret)
SecretName: default-token-gq92d
Optional: false
QoS Class: BestEffort
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:
Type Reason Age From Message

Warning FailedScheduling default-scheduler pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
Warning FailedScheduling default-scheduler pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
Normal Scheduled default-scheduler Successfully assigned default/wordpress-578744754c-79fhz to 192.168.21.118
Warning FailedMount 12m (x7 over 16m) kubelet, 192.168.21.118 Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[default-token-gq92d wordpress-persistent-storage]: failed to get Plugin from volumeSpec for volume "pvc-56ba158b-d26d-486e-89e9-fac52bf28eca" err=no volume plugin matched
Warning FailedMount 90s (x57 over 16m) kubelet, 192.168.21.118 Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[wordpress-persistent-storage default-token-gq92d]: failed to get Plugin from volumeSpec for volume "pvc-56ba158b-d26d-486e-89e9-fac52bf28eca" err=no volume plugin matched

**Comment by yq513** [comment]
I researched it for two weeks and solved it. The reason is that in operator.yaml, you need to understand the difference between the drive modes of CSI and FLEX. When you choose FLEX, you need to annotate the CSI configuration.
I have seen https://github.com/rook/rook/issues/4139 during configuration, and also commented below after resolving

**Comment by EKwongChum** [comment]
similar error in my  kubernetes cluster which use nfs as storage method.
when i try `kubectl describe pod my-pod` 

```bash
Unable to attach or mount volumes: unmounted volumes=[coremail-home], unattached volumes=[coremail-home cm-service-account-token-ghtmv]: timed out waiting for the condition
```

it seems to be a storage problem. After restart my nfs server, it disappear.
