### ISSUE TITLE
Flawed test: Pod Disks detach in a disrupted environment [Slow] [Disruptive] when node is deleted

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#85972]
**Which jobs are failing**:

**Which test(s) are failing**:
Pod Disks detach in a disrupted environment [Slow] [Disruptive] when node is deleted

**Since when has it been failing**:
12/4

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial

**Reason for failure**:

**Anything else we need to know**:

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
It seems very odd that https://github.com/kubernetes/kubernetes/commit/9eda99793de11f3acd2716a939e15a6f5fde8ff6#diff-2cebda6448c20d8dff9dc037fb8c0577 would cause the test to fail, but the timing seems to line up very closely.

**Comment by msau42** [comment]
In trying to fix the failure, I also noticed that the test itself is not right. If a node gets recreated fast enough, then the Pod may not get evicted, and would still remain scheduled to the same node, so the disk will also still be scheduled to the same node. However the test is checking that the disk does get detached from the node, which may never happen.  However, it's also passing because it doesn't actually fail on error.

Also I think there's a broader issue that these tests are very provider/platform specific. I would like to see if we can rewrite these tests to be more platform-agnostic, and test higher-level functionality rather than attach/detach of disks. For example, a test case for a pod being rescheduled to another node can be written in a platform-agnostic way and still test attach/detach functionality. We already have some [tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/multivolume.go) like that and we should see if any of the tests in pd.go can be removed.

**Comment by msau42** [comment]
For the short term, I'm just going to disable this test. It will require a bit of reworking to fix it properly.

**Comment by dims** [comment]
/close

we don't have this test any more in our harness.
