### ISSUE TITLE
HA Cluster by kubespray: kube-controller-manager and kube-scheduler pod restart many times in kubernetes v1.13.2

### ISSUE THREAD

**Issue by azmathasan92** [kubernetes/kubernetes#85987]
**What happened:**
We have a six node Kubernetes cluster in which we have three master nodes and three worker nodes. Everything is working fine in my cluster, but I was looking into the Kube-system namespace I saw that Kube-controller and Kube scheduler pods got restarted many times. I do not know when it happened and why.

When I was looking into the previous logs of the pod Kube-scheduler and Kube-controller, I got the same log from all three scheduler and controller pod before restart and which are:

Kube Schedular
-----------------------------------------------------------------------------------------------
Kube Schedular Logs:
`I1112 06:04:31.664359       1 leaderelection.go:249] failed to renew lease Kube-system/Kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded`
`E1112 06:04:31.664457       1 server.go:261] lost master`
`lost lease`

When we describe the Kube-scheduler pod we god the following result:
```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 29 Oct 2019 20:46:49 -0400
      Finished:     Tue, 12 Nov 2019 01:04:31 -0500
    Ready:          True
    Restart Count:  6
```

Kube Controller
-----------------------------------------------------------------------------------------------
Kube Controller Logs:
`I1115 07:29:44.112962       1 leaderelection.go:249] failed to renew lease Kube-system/Kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded`
`F1115 07:29:44.113075       1 controllermanager.go:254] leaderelection lost`

When we describe the Kube-controller pod we god the following result:
```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 12 Nov 2019 01:25:30 -0500
      Finished:     Wed, 13 Nov 2019 21:07:09 -0500
    Ready:          True
    Restart Count:  8

```
**What you expected to happen:**
NO RESTARTS and also want to know the reason for the restart.

**How to reproduce it:**
Created HA cluster by kubespray (3 master, 3 worker and 3 etcd nodes)

**Anything else we need to know?:**
- we used default leader election setting
- We have three node etcd cluster
- We used calico as a CNI

Kube-system namespace pods
--------------------------------------------------------------------------------------------------
```
NAME                                      READY   STATUS    RESTARTS   AGE
calico-kube-controllers-f5789bbb4-s2vpl   1/1     Running   2          56d
calico-node-7s845                         1/1     Running   0          56d
calico-node-8htd9                         1/1     Running   0          56d
calico-node-lqrxb                         1/1     Running   2          56d
calico-node-ttbts                         1/1     Running   0          56d
calico-node-xl4fm                         1/1     Running   0          56d
calico-node-xs5d8                         1/1     Running   0          56d
coredns-6fd7dbf94c-g4m9w                  1/1     Running   0          56d
coredns-6fd7dbf94c-r72nh                  1/1     Running   0          56d
dns-autoscaler-5b4847c446-wmcsv           1/1     Running   0          56d
filebeat-2t8zx                            1/1     Running   0          14d
filebeat-nj6qx                            1/1     Running   0          14d
filebeat-smw8d                            1/1     Running   0          14d
filebeat-vwdh8                            1/1     Running   0          14d
filebeat-wdgwh                            1/1     Running   0          14d
filebeat-z75z6                            1/1     Running   0          14d
kube-apiserver                            1/1     Running   0          56d
kube-apiserver                            1/1     Running   0          56d
kube-apiserver                            1/1     Running   0          56d
kube-controller-manager                   1/1     Running   8          56d
kube-controller-manager                   1/1     Running   7          56d
kube-controller-manager                   1/1     Running   7          56d
kube-proxy-8j5q5                          1/1     Running   0          56d
kube-proxy-bkzj6                          1/1     Running   0          56d
kube-proxy-bxcn2                          1/1     Running   0          56d
kube-proxy-hgff8                          1/1     Running   1          56d
kube-proxy-k88ll                          1/1     Running   0          56d
kube-proxy-q7l7g                          1/1     Running   0          56d
kube-scheduler                            1/1     Running   6          56d
kube-scheduler                            1/1     Running   4          56d
kube-scheduler                            1/1     Running   8          56d
kubernetes-dashboard-686f566b46-h4x9r     1/1     Running   0          29d
nginx-proxy                               1/1     Running   0          56d
nginx-proxy                               1/1     Running   0          56d
nginx-proxy                               1/1     Running   1          56d

```
We can see that except Kube-scheduler and Kube-controller some other pods have also restarted (i.e Nginx-proxy, Kube-proxy, calico node, etc). We do not have the previous logs of them.
We also want the reason for the restart of these pods.

**Environment:**
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by haosdent** [comment]
Is there any network problem, both your log show it fail when doing leader election.

**Comment by azmathasan92** [comment]
@haosdent No, I Don't think so that there is a network problem. 

Today, The controller manager pod is restarted.

![image](https://user-images.githubusercontent.com/46434910/71463268-d39fae80-27db-11ea-861b-afd43a0419bf.png)


here are the logs:

```
2019-12-26T03:00:17.138434098Z I1226 03:00:17.138281       1 leaderelection.go:249] failed to renew lease kube-system/kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
2019-12-26T03:00:17.138556883Z F1226 03:00:17.138395       1 controllermanager.go:254] leaderelection lost
```
I am worring about that, Please provide me the exact reason for this happening.

**Comment by SergeMerge** [comment]
Hello there.

I have faced the exact same problem with kubernetes installed by kubespray. My cluster configuration - 4 nodes (4 masters and 4 workers at the same time). Cluster's kube-controller-manager and kube-scheduler restarts every day without any known reason - state was just Error and that's all.

Is there any updates for this issue? Or maybe somebody knows how to fix this?

**Comment by CermakM** [comment]
Looks like I am hitting the same issue. Any updates?
