### ISSUE TITLE
Does K8s have plans to support chubaofs？

### ISSUE THREAD

**Issue by dongjiang1989** [kubernetes/kubernetes#85984]
PersistentVolumeSource struct can default chubaofs？

**Comment by alejandrox1** [comment]
/sig storage
ptal
/cc @kubernetes/sig-storage-misc 
/kind feature

**Comment by liggitt** [comment]
Support for additional storage drivers would be added via CSI implementations, not via new per-plugin fields in PersistentVolumeSource.
