### ISSUE TITLE
Transfer container status to terminated if image not exist

### ISSUE THREAD

**Issue by Binyang2014** [kubernetes/kubernetes#85992]
**What would you like to be added**:
When creating pod. If container image is not exits, container will in waiting status forever.
Since it's a permanent error. We should transfer the container status to terminated. Or at least we can set a timeout for this issue. After the timeout, container will transfer to terminate status.

**Why is this needed**:
For pod monitor or life-cycle management, we want to know if the container occur a permanent error then we can setup some retry policies for the failed container.

When container image is incorrect, the container will in waiting status and we can not known the reason from a reliable source. Transfer the container status to terminate will improve the pod life-cycle management and release the occupied resource.

**Comment by Binyang2014** [comment]
@kubernetes/sig-node

**Comment by haosdent** [comment]
Keep retry when image appears also reasonable?

**Comment by Binyang2014** [comment]
@haosdent Can we customize the retry policy for image pull? For some use cases, we don't want to waste time to retry. Since resource already allocated at this time.
How about add retryPolicy for image pull. The policy can be `Always/Never` ...

**Comment by haosdent** [comment]
@Binyang2014 Understand, your request make sense.
