### ISSUE TITLE
Is there a way to filter and process login request to kube-api-server?

### ISSUE THREAD

**Issue by lambotchi** [kubernetes/kubernetes#85991]
Our goal is to deny login using token from service accounts. 

What we plan is to

1. Capture login event 
2. Forward request to an OPA instance
3. OPA will check if the login request is using a token. It will deny user from logging in if it's using a token, otherwise it will allow it. 
4. Allowed request will be forwarded to the auth server/ identity provider so that it will not be touched and business for him as usual

@kubernetes/sig-auth
/sig auth

**Comment by liggitt** [comment]
No, there is not a policy hook for the built-in authentication methods. Also, there is no distinct "login" event. Every API request provides a credential, and the filter chain derives authenticated user info from that credential for use by the handler chain.

/close

**Comment by lambotchi** [comment]
thanks for the help. I realize what I mean really is some sort of callback

**Comment by liggitt** [comment]
Mutating requests (create, update, patch, delete) can be intercepted by mutating or validating webhooks, which can enforce external policies. See https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/ for details, though that only covers mutating requests, not get/list/watch requests
