### ISSUE TITLE
apply dry-run / prune namespace ambiguity

### ISSUE THREAD

**Issue by sh0rez** [kubernetes/kubernetes#86026]
**What happened**: While trying to write a script that can predict what resources will be applied (or pruned) to the cluster, I noticed that the output of `kubectl apply --dry-run` does not include the namespace, which makes it impossible to tell which object is affected if two objects of the same kind and name exist in different namespaces.

**What you expected to happen**: The namespace being outputted as well, to uniquely identify the object

**How to reproduce it (as minimally and precisely as possible)**: 
Using the change to the yaml:
```diff
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: a
data:
  test.yml: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: b
data:
- test.yml: test
+  test.yml: testing
```
We get the following result:
```bash
$ kubectl apply -f test.yml --server-dry-run
configmap/promtail unchanged (server dry run)
configmap/promtail configured (server dry run)
```

From this output we cannot tell which object has changed and which not.

**Anything else we need to know?**: Is there better way to accomplish getting a list of changed (and especially pruned) objects? `kubectl diff` does not seem to include pruned ones and using `-o` on `dry-run` completely redacts if something has changed or not.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1-k3s.4", GitCommit:"52f3b42401c93c36467f1fd6d294a3aba26c7def", GitTreeState:"clean", BuildDate:"2019-04-15T22:13+00:00Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

/sig cli

**Comment by apelisse** [comment]
This doesn't have much to do with dry-run, apply. It's mostly about how we print the name of the resources for operations performed by kubeclt. That seems fairly simple to fix, but I'm curious if we care about the compatibility if we change that text? @kubernetes/sig-cli-maintainers

**Comment by sh0rez** [comment]
Just checked, still an issue!

**Comment by apelisse** [comment]
@soltysh @seans3 Do you have an opinion on this?
