### ISSUE TITLE
TopologySpreadConstraint not acting as expected

### ISSUE THREAD

**Issue by eranreshef** [kubernetes/kubernetes#86037]
**How to reproduce it (as minimally and precisely as possible)**:
pre-requisites: a multi-az cluster, a deployment with 1 pod in each az.
1. apply a `topologySpreadConstraint` with `maxSkew=1` and `whenUnsatisfiable: DoNotSchedule`.
2. cordon the node(s) in 1 az.
3. delete the deployment's pod(s) from the cordoned az.

**What happened**:
A new pod was created and scheduled in a form that `number_of_pods_AZ_1 - number_of_pods_AZ_2 > maxSkew`

**What you expected to happen**:

I expected that a new pod will be created and be "stuck" in `pending` status as it shouldn't have nowhere be scheduled.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
```NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2247.7.0
VERSION_ID=2247.7.0
BUILD_ID=2019-11-19-2251
PRETTY_NAME="Container Linux by CoreOS 2247.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`): 4.19.84-coreos
- Others: I created a [screen capture video](https://youtu.be/RiLNyW5D9rk) with how I reproduce the bug

**Comment by draveness** [comment]
cc/ @Huang-Wei

**Comment by Huang-Wei** [comment]
Thanks for raising this issue.

I feel like it's a general timing issue - when you delete a Pod, that Pod may still exist for a very short time (in graceful deletion period), and at the same time, the controller backfills a Pod for it. So when scheduling tries to schedule the backfill Pod, it may read the cluster as: [1, 1, 1(deleting)].

To confirm this, can you try deleting the Pod using `kubectl delete po <pod in the cordoned topology> --force=true --grace-period=0`, and see if the problem goes away?

**Comment by eranreshef** [comment]
Yes sure I will try that. It sounds reasonable, thats why in the first demonstration I deleted all the pods and waited for all of them to completely disappear. Nevertheless, this is still something that I believe needs to be fixed. The pod's evaluation should take in consideration pods that are in `Terminating` status and don't count them as `Running` pods.

**Comment by Huang-Wei** [comment]
> The pod's evaluation should take in consideration pods that are in `Terminating` status and don't count them as `Running` pods.

I do believe we exclude the `Terminated` Pods. (if not, it should be a serious regression). What concerns me is that at that moment, scheduler may treats that (deleting) Pod as running in its cache. I will try to debug into this.

**Comment by eranreshef** [comment]
> To confirm this, can you try deleting the Pod using kubectl delete po <pod in the cordoned topology> --force=true --grace-period=0, and see if the problem goes away?

Yep, this time the new pod was in `Pending` status until I uncordoned the relevant nodes.
