### ISSUE TITLE
load-generator busybox - unable to stop/kill it

### ISSUE THREAD

**Issue by rkrgarlapati** [kubernetes/kubernetes#86038]
Kindly help. I am in trouble. There seems to be an issue with load test app.

Followed [this ](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#increase-load)article to load test HPA.

Have done CTRL+c  to stop the load run, got a message 'image deleted'. But load never stopped, it keeps growing. It's been 3 hrs, it never stops. Something is running in the background. I am clue less, where and what is running in cluster.

```
NAME            REFERENCE                  TARGETS                          MINPODS   MAXPODS   REPLICAS   AGE
myservice   Deployment/myservice   445569536/500Mi, 16%/70%         2         10        8          22m

```
Please help me to figure it out.

Thanks.

**Comment by neolit123** [comment]
hi, better try asking in the k8s slack channel #kubernetes-users or on stackoverflow.

/close
/remove-kind bug
/triage support
