### ISSUE TITLE
kubectl check existence of resource without error

### ISSUE THREAD

**Issue by dmayle** [kubernetes/kubernetes#86042]
**What would you like to be added**:
I'm requesting a kubectl command that can be used to check for the existence of a resource that doesn't throw an error when the resource doesn't exist.

**Why is this needed**:
The fact that `kubectl get pod foo` returns an error code causes problems in existing tools built around k8s.  It is difficult or impossible for other tools to distinguish between actual errors, like unreachable api servers, and a correct response where no object is found.

**Best known workaround**:
Performing a plural search with a field selector doesn't return an error: `kubectl get pods --field-selector=metadata.name=foo` will not throw an error, which is fine for bash scripts, but not for other tools that integrate kubectl (get single vs get plural error out differently).

I'm happy to provide the code that implements this.  It could either be a change to the singular `get` or a new command like `check` or `exists`

**Comment by liggitt** [comment]
Sounds like the `--ignore-not-found` flag to `kubectl get` does what you want?

**Comment by dmayle** [comment]
> Sounds like the `--ignore-not-found` flag to `kubectl get` does what you want?

That actually does work.  I'm going to try to update the tools I depend on.
