### ISSUE TITLE
Move test specific functions from e2e sub framework

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubernetes#86052]
**What happened**:

During the work for reducing invalid dependencies from the e2e core framework to subpackages of the core framework, we found a lot of particular test specific functions.
That means these each function is used at a single e2e test module only.
These functions are unnecessary to be shared as e2e framework function, so we've just
moved these functions to the particular test module like #86050

This cleanup work will help us to maintain the e2e framework in long term, so it is
helpful to share this work in volunteers as a community.

This issue is for tracking this working items.

**How to do that?:**

1.  Each volunteer selects a single e2e sub framework package which is empty (no PR, no assignee) from the following e2e sub framework
2.  List all functions in the package
3.  Check all callers of each function
4.  If finding the function is called at a single e2e test package only, let's move the function to the module with a PR

**Implementation rules**:

* If a function is called from 2+ test packages, don't move the function from the e2e sub framework.
* If moving of the function requires invalid code dependencies, don't move the function.

**List of files of e2e core framework:**
- [x] auth(@tanjunchen)
- [x] autoscaling(@haosdent)
- [x] config(@haosdent)
- [x] deployment (#86050)
- [x] deviceplugin(@haosdent)
- [x] endpoints(@haosdent)
- [x] ginkgowrapper(@hwdef)
- [x] gpu(@haosdent)
- [x] ingress(@haosdent)
- [x] job(@haosdent)
- [x] kubectl(@haosdent)
- [x] kubelet(@haosdent)
- [x] lifecycle(@tanjunchen)
- [x] log(@haosdent)
- [x] metrics(@haosdent)
- [x] network(@haosdent)
- [x] node(@haosdent)
- [x] perf(@haosdent)
- [x] pod(@hwdef)
- [x] podlogs(@hwdef)
- [x] providers(@tanjunchen)
- [x] pv(@haosdent)
- [x] rc(@tanjunchen)
- [x] replicaset(@tanjunchen)
- [x] resource(@tanjunchen)
- [x] security(@tanjunchen)
- [x] service(@clarklee92)
- [x] ssh(@clarklee92)
- [x] statefulset(@clarklee92)
- [x] testfiles(@clarklee92)
- [x] timer(@clarklee92)
- [x] viperconfig(@clarklee92)
- [x] volume(@clarklee92)

This is the continuation of #84380.
Thanks to @oomichi for his guidance.

**Comment by tanjunchen** [comment]
i will pick up lifecycle auth

**Comment by haosdent** [comment]
i would pick up lifecycle autoscaling

**Comment by haosdent** [comment]
`config` looks no need to change.

**Comment by haosdent** [comment]
i would pick up lifecycle deviceplugin

**Comment by haosdent** [comment]
i would pick up lifecycle endpoint.

**Comment by haosdent** [comment]
looks like remove any funcs in endpoint folder would requires invalid code dependencies.

**Comment by haosdent** [comment]
i would pick up lifecycle gpu.

**Comment by tanjunchen** [comment]
@haosdent hello
lifecycle  package  is picked by me,you need not to repeat it.

**Comment by haosdent** [comment]
@tanjunchen oh, sry, I think lifecycle is a prefix and didn't realize it is a package, so I add it in my comment. I didn't work on lifecycle package actually.

**Comment by haosdent** [comment]
i would pick up ingress

**Comment by clarklee92** [comment]
I can handle the ones that need to be handled：
```
service
ssh
statefulset
testfiles
timer
viperconfig
volume
```

**Comment by haosdent** [comment]
In job, looks like only 
```
func EnsureAllJobPodsRunning(c clientset.Interface, ns, jobName string, parallelism int32) error {
```
could be migrated.

I would submit a pull request for this.

**Comment by haosdent** [comment]
files in package kubectl looks like used by multiple packages.

**Comment by haosdent** [comment]
I would migrate kubelet.

**Comment by haosdent** [comment]
for log, looks like only 1 method could be migrated. Have submitted the merge request.

**Comment by haosdent** [comment]
submitted the pull request to migrate metrics.

**Comment by haosdent** [comment]
for network, the funcs looks like used by different packages as wel.

**Comment by haosdent** [comment]
for node, move the funs would cause invalid deps.

**Comment by haosdent** [comment]
for perf, the funcs looks like used by different packages as well.

**Comment by oomichi** [comment]
I'd like to join as a reviewer.

/assign @oomichi

**Comment by tanjunchen** [comment]
i will deal with
```
replicaset
 resource
 security
```

**Comment by hwdef** [comment]
I will pick up 
```
ginkgowrapper
pod
podlogs
```

**Comment by hwdef** [comment]
ginkgowrapper does not need to be changed.

**Comment by pohly** [comment]
Let me point out one caveat of this whole effort: it assumes that the framework is only used by tests in Kubernetes. If the goal is to allow others to also use the framework, then those (potential) outside usages of a package also need to be considered when deciding whether a sub-package can be moved into one particular test package.

For example, https://github.com/kubernetes/kubernetes/pull/86237 moves the e2e/framework/podlog code into e2e/storage/testsuites and at the same time makes the code private. But it is used externally, too (https://github.com/intel/pmem-csi/blob/732ab4735306f841f240333355f7f5482ef3d2e2/test/e2e/storage/csi_volumes.go#L173-L178).

I don't have a good suggestion for finding those external users. But if they are pointed out, do we agree that the code shouldn't be moved?

**Comment by SataQiu** [comment]
@pohly Thank you for pointing this out.
I think if we find a func that is being used externally, and we make sure the func is common(can be widely used), we'd better not move it. The problem is that we don't have a good way to identify these external references either.  @oomichi What do you think？

**Comment by oomichi** [comment]
> I don't have a good suggestion for finding those external users. But if they are pointed out, do we agree that the code shouldn't be moved?

That is a nice point.
We can see external users inside of kubernetes since https://cs.k8s.io/ but it is so difficult to know external users outside of kubernetes.
The above case(https://github.com/intel/pmem-csi/blob/732ab4735306f841f240333355f7f5482ef3d2e2/test/e2e/storage/csi_volumes.go#L173-L178) @pohly pointed it in advance, but I don't think that is a common case for outside users.

IMO if we've already defined e2e test framework which includes sub packages as stable interface(functions, structures, etc), we should not change these like moving/removing at all.
I am not sure what is our situation about the above, I guess we don't decide it yet.

**Comment by pohly** [comment]
I also looked at the information that godoc provides about users of a package, but for `test/e2e/framework` that list is dominated by forks of Kubernetes, which isn't very helpful.

I suppose we'll have to rely on common sense and feedback from outside users to determine whether some API in `e2e/framework` or its sub-packages is useful enough to stay there or whether it is so test specific that it belongs to the single test that uses it.

**Comment by clarklee92** [comment]
> I can handle the ones that need to be handled：
> 
> ```
> service
> ssh
> statefulset
> testfiles
> timer
> viperconfig
> volume
> ```

Nothing need to do with `ssh`, `testfiles`, `timer`and I already pushed relevant  PRs about others. Thanks for reviews.

**Comment by tanjunchen** [comment]
auth
rc
resource
security
for now , nothing to do.
/cc @SataQiu

**Comment by SataQiu** [comment]
It looks like we've checked all the folders listed in this issue.
Thank you all for your help!
/close
