### ISSUE TITLE
[Flaky Test] [sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#86068]
**Which jobs are failing**:
gce-cos-k8sbeta-default

**Which test(s) are failing**:
PreemptionExecutionPath runs ReplicaSets to verify preemption running path

**Since when has it been failing**:

**Testgrid link**:
master:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&sort-by-flakiness=&include-filter-by-regex=Preemption

release 1.17: https://testgrid.k8s.io/sig-release-1.17-informing#gce-cos-k8sbeta-default

**Reason for failure**:
```
I1209 11:04:22.876] [BeforeEach] [sig-scheduling] PreemptionExecutionPath
I1209 11:04:22.876]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:264
I1209 11:04:22.876] [1mSTEP[0m: Finding an available node
I1209 11:04:22.876] [1mSTEP[0m: Trying to launch a pod without a label to get a node which can launch it.
I1209 11:04:22.876] [1mSTEP[0m: Explicitly delete pod here to free the resource it takes.
I1209 11:04:22.877] Dec  9 11:01:39.752: INFO: found a healthy node: test-1789b1211d-minion-group-h4jr
I1209 11:04:22.877] [It] runs ReplicaSets to verify preemption running path
I1209 11:04:22.877]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:307
I1209 11:04:22.877] Dec  9 11:03:09.855: INFO: pods created so far: map[rs-pod1-2pmt5:{} rs-pod1-9lhzb:{} rs-pod1-k964d:{} rs-pod1-rkp8c:{} rs-pod1-zkqd8:{} rs-pod2-526h5:{} rs-pod2-gzm7k:{} rs-pod2-rljhp:{} rs-pod2-w5nfh:{} rs-pod3-4x9fq:{} rs-pod3-r7sgb:{} rs-pod3-v44ks:{} rs-pod3-xbs7b:{}]
I1209 11:04:22.877] Dec  9 11:03:09.855: INFO: length of pods created so far: 13
I1209 11:04:22.878] Dec  9 11:04:11.004: FAIL: Unexpected error:
I1209 11:04:22.878]     <*errors.errorString | 0xc0022e9db0>: {
I1209 11:04:22.878]         s: "replicaset \"rs-pod4\" never had desired number of .status.availableReplicas",
I1209 11:04:22.878]     }
I1209 11:04:22.878]     replicaset "rs-pod4" never had desired number of .status.availableReplicas
I1209 11:04:22.878] occurred
I1209 11:04:22.878] [AfterEach] [sig-scheduling] PreemptionExecutionPath
```

**Anything else we need to know**:
cc. @kubernetes/ci-signal 
/sig scheduling
/priority important-soon

**Comment by spiffxp** [comment]
/priority critical-urgent
This is the 3rd flakiest test for pull-kubernetes-e2e-gce

**Comment by spiffxp** [comment]
triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=PreemptionExecutionPath%20runs%20ReplicaSets%20to%20verify%20preemption%20running%20path

Retitled since this is failing for more than just the one job

**Comment by liggitt** [comment]
if there's not an obvious immediate fix, I would recommend:
1. marking the test as `[Flaky]` to skip the test in merge-blocking job runs
2. opening a second PR that reverts the `[Flaky]` change and adds debugging commits and do `/test ...` on that PR to flush out issues
3. keeping this issue open (at the current priority, since I would expect the sig to prioritize test restoring test coverage of existing features) and in the current milestone to track resolution of the test before release (either by fixing the test, finding/fixing an underlying bug, or proving we have test coverage of the function via another method and deleting the test)

**Comment by liggitt** [comment]
flakes in the last ~24 hours:

failed in 14 our of ~125 runs (~11% failure rate)

* https://github.com/kubernetes/kubernetes/pull/77253 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206529353358249984
* https://github.com/kubernetes/kubernetes/pull/80831 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206230506488729600
* https://github.com/kubernetes/kubernetes/pull/81895 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206326891414294529
* https://github.com/kubernetes/kubernetes/pull/81934 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206524947837489154
* https://github.com/kubernetes/kubernetes/pull/84425 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206625487661568001
* https://github.com/kubernetes/kubernetes/pull/85879 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206550617447731201
* https://github.com/kubernetes/kubernetes/pull/85898 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206591766485012480
* https://github.com/kubernetes/kubernetes/pull/86054 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206248501785137153
* https://github.com/kubernetes/kubernetes/pull/86199 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206423654141792256
* https://github.com/kubernetes/kubernetes/pull/86221 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206565591998009345
* https://github.com/kubernetes/kubernetes/pull/86222 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206613034324201472
* https://github.com/kubernetes/kubernetes/pull/86238 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206121665876987905
* https://github.com/kubernetes/kubernetes/pull/86284 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206342493419868164
* https://github.com/kubernetes/kubernetes/pull/86310 - failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206576664612442113

**Comment by Huang-Wei** [comment]
/assign

I will take a look.

**Comment by liggitt** [comment]
marked as `[Flaky]` in https://github.com/kubernetes/kubernetes/pull/86327, will leave this issue open to track root causing, fixing, restoring the test before release
