### ISSUE TITLE
kube-apiserver memory leak for etcd mvccpb Unmarshal

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#86074]
**What happened**:
![image](https://user-images.githubusercontent.com/8739301/70439105-37329800-1aca-11ea-8060-6a32213905df.png)

I pprof debug it found:

![image](https://user-images.githubusercontent.com/8739301/70439163-54fffd00-1aca-11ea-9b93-07d5668c6c13.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/kind bug
/sig kube-apiserver

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Linux CentOS 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wgliang** [comment]
```
46728: 47849472 [493680: 505528320] @ 0x1118d76 0x11199ea 0x11cb8a2 0x9ab272 0x1172dc9 0x1187bf6 0x1175b9c 0x117fe9b 0x11a4e62 0x120b1ce 0x45a091
#       0x1118d75       k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/mvccpb.(*KeyValue).Unmarshal+0xa55                         /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/mvccpb/kv.pb.go:427
#       0x11199e9       k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/mvccpb.(*Event).Unmarshal+0x619                            /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/mvccpb/kv.pb.go:582
#       0x11cb8a1       k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*WatchResponse).Unmarshal+0xd31        /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:11625
#       0x9ab271        k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto.(*Buffer).Unmarshal+0x151                             /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto/decode.go:411
#       0x1172dc8       k8s.io/kubernetes/vendor/google.golang.org/grpc.protoCodec.Unmarshal+0x118                                      /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/codec.go:85
#       0x1175b9b       k8s.io/kubernetes/vendor/google.golang.org/grpc.recv+0x16b                                                      /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/rpc_util.go:377
#       0x117fe9a       k8s.io/kubernetes/vendor/google.golang.org/grpc.(*clientStream).RecvMsg+0xca                                    /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/stream.go:392
#       0x11a4e61       k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*watchWatchClient).Recv+0x61           /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3217
#       0x120b1cd       k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).serveWatchClient+0x4d               /tmp/build/src/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/watch.go:565
```

**Comment by liggitt** [comment]
1.11 is out of support. What version of etcd is this using? Is this reproducible with kubernetes 1.15+?

**Comment by wgliang** [comment]
> 1.11 is out of support. What version of etcd is this using? Is this reproducible with kubernetes 1.15+?

etcd is v3.2.18, I don't know if it exists in version 1.15+, which happened by accident in my environment.

**Comment by wgliang** [comment]
> > 1.11 is out of support. What version of etcd is this using? Is this reproducible with kubernetes 1.15+?
> 
> etcd is v3.2.18, I don't know if it exists in version 1.15+, which happened by accident in my environment.

But if the root cause is in kv.pb.go, I think it should exist in almost all versions, because this code has not changed for two years.

**Comment by liggitt** [comment]
What storage backend config is this using? Do you have the kube-apiserver invocation available?

**Comment by wgliang** [comment]
> What storage backend config is this using? 

What does storage backend config mean?

> Do you have the kube-apiserver invocation available?

Yes, I have.

**Comment by wgliang** [comment]
Looks like related with https://github.com/gogo/protobuf/issues/583.

**Comment by wgliang** [comment]
Looks like related with https://github.com/etcd-io/etcd/issues/11350

**Comment by wgliang** [comment]
I check that the number of files opened by the kube-apiserver of the memory leak node is 7000+, but there are only 5 in normal node.

**Comment by liggitt** [comment]
cc @jpbetz

**Comment by liggitt** [comment]
> > Do you have the kube-apiserver invocation available?
> 
> Yes, I do.

can you provide the invocation here?

**Comment by wgliang** [comment]
> > > Do you have the kube-apiserver invocation available?
> > 
> > 
> > Yes, I do.
> 
> can you provide the invocation here?

I don't know what you mean by invocation? Is an https request?
There are a lot of warnings:

```
W1210 06: 15: 00.558922 86295 watcher.go: 235] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow dispatching events to watchers
W1210 06: 15: 00.558936 86295 watcher.go: 342] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow decoding, user not receiving fast, or other processing logic.
```

**Comment by liggitt** [comment]
The `kube-apiserver` binary invocation (including the command-line flags used to start it). Specifically, I'm looking to see if a `--storage-backend` or `--storage-media-type` flag is being passed to the `kube-apiserver` when starting it.

**Comment by wgliang** [comment]
start command

`/opt/meituan/kubernetes/bin/kube-apiserver --logtostderr=false --v=3 --etcd-servers=https://XX.XX.XX.XX:4001,https:///XX.XX.XX.XX:4001,https:///XX.XX.XX.XX:4001,https:///XX.XX.XX.XX:4001,https:///XX.XX.XX.XX:4001 --etcd-servers-overrides=/events#https:///XX.XX.XX.XX:4001;https:///XX.XX.XX.XX:4001;https:///XX.XX.XX.XX:4001;https:///XX.XX.XX.XX:4001;https:///XX.XX.XX.XX:4001 --insecure-bind-address=127.0.0.1 --insecure-port=8080 --allow-privileged=true --log-dir=/mnt/k8s/logs/kube-apiserver --service-cluster-ip-range=172.17.0.0/16 --client-ca-file=/opt/meituan/kubernetes/apiserver/cert/ca.crt --tls-cert-file=/opt/meituan/kubernetes/apiserver/cert/server.crt --tls-private-key-file=/opt/meituan/kubernetes/apiserver/cert/server.key --etcd-cafile=/opt/meituan/kubernetes/apiserver/cert/ca.crt --etcd-certfile=/opt/meituan/kubernetes/apiserver/cert/server.crt --etcd-keyfile=/opt/meituan/kubernetes/apiserver/cert/server.key --audit-log-maxage=100 --audit-log-maxbackup=500 --audit-log-maxsize=2048 --audit-log-path=/mnt/k8s/logs/audit/audit.log --authorization-mode=Node,RBAC --service-account-key-file=/opt/meituan/kubernetes/apiserver/cert/ca.key --feature-gates=AdvancedAuditing=false`

storage flag

```
I1107 21:12:54.248822   86295 flags.go:27] FLAG: --storage-backend=""
I1107 21:12:54.248826   86295 flags.go:27] FLAG: --storage-media-type="application/vnd.kubernetes.protobuf"
I1107 21:12:54.248833   86295 flags.go:27] FLAG: --storage-versions="admission.k8s.io/v1beta1,admissionregistration.k8s.io/v1beta1,apps/v1,authentication.k8s.io/v1,authorization.k8s.io/v1,autoscaling/v1,batch/v1,certificates.k8s.io/v1beta1,componentconfig/v1alpha1,events.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.k8s.io/v1,scheduling.k8s.io/v1beta1,settings.k8s.io/v1alpha1,storage.k8s.io/v1,v1"
```

**Comment by tedyu** [comment]
Proposed a PR for etcd :
https://github.com/etcd-io/etcd/pull/11438

**Comment by tedyu** [comment]
See explanation w.r.t. different behavior of test code :

https://github.com/etcd-io/etcd/issues/11350#issuecomment-564152196

**Comment by tedyu** [comment]
At first glance, one would think that the leak was related to Unmarshal().
Upon second look, Unmarshal is called by watchableStore#syncWatchers :
```
		evs = kvsToEvents(s.store.lg, wg, revs, vs)
```
The evs is used to compose WatcherBatch:
```
	wb := newWatcherBatch(wg, evs)
```
which is involved in calculating victims.

The victim cleanup bug fixed by https://github.com/etcd-io/etcd/pull/11438 would show up if watcher is not canceled for certain period of time.

**Comment by liggitt** [comment]
@tedyu is that code in the etcd process or in the kube-apiserver process?

@wgliang is the first graph in the description your system memory use or kube-apiserver memory use?

**Comment by jingyih** [comment]
What triggered the memory usage increase starting from 12/5? Let's try to reproduce it so that we know if it is a memory leak or just due to higher workload.

**Comment by tedyu** [comment]
https://github.com/etcd-io/etcd/issues/11350 fixes potential memory leak in etcd server.

**Comment by wgliang** [comment]
> What triggered the memory usage increase starting from 12/5? Let's try to reproduce it so that we know if it is a memory leak or just due to higher workload.

I can be sure that it is not caused by higher workload. In addition, we are a 5-node replica, and only one of them has this situation.

**Comment by wgliang** [comment]
> @wgliang is the first graph in the description your system memory use or kube-apiserver memory use?

It is kube-apiserver memory use.

**Comment by liggitt** [comment]
> I can be sure that it is not caused by higher workload. In addition, we are a 5-node replica, and only one of them has this situation.

Typically, one API server has the active controller-manager running against it, which would place it under higher load. Do you know if this one was the active controller?

**Comment by wgliang** [comment]
> > I can be sure that it is not caused by higher workload. In addition, we are a 5-node replica, and only one of them has this situation.
> 
> Typically, one API server has the active controller-manager running against it, which would place it under higher load. Do you know if this one was the active controller?

Yes, I found this one was the active controller. If as your said, theoretically, if the controller switches to another node, will the memory automatically return to the normal level?
