### ISSUE TITLE
kubectl command not found -help possible addition to docs

### ISSUE THREAD

**Issue by Kielan** [kubernetes/kubernetes#8608]
I am trying to set up kubernetes and can't find anywhere in the project or docs where I need to point a path to set global kubectl command.

**Comment by roberthbailey** [comment]
@Kielan -- how are you running kubernetes? If you have the source or a binary release, you should be able to run `./cluster/kubectl.sh` to execute kubectl (if you have the source you may need to build it first by running `./hack/build-go.sh`). 

You can also download the binary kubectl from the most recent release by running `wget https://storage.googleapis.com/kubernetes-release/release/v0.17.0/bin/linux/amd64/kubectl` (substituting the right os/architecture combination for your platform).

**Comment by Kielan** [comment]
I downloaded at a tar and it didn't seem to set in the code it said if the error I was getting happened I should contact the google team, I then followed this [link's](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws.md) instructions and figured it out. Maybe the way I tried going about it first is now unsupported.

**Comment by aertoria** [comment]
it now will print the following instruction on the screen upon you finish minikube installation. e.g.,
 curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.5.1/bin/darwin/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
