### ISSUE TITLE
[Failing Test] GCE 5K Performance - prometheus measurement fails

### ISSUE THREAD

**Issue by pierewoj** [kubernetes/kubernetes#86082]
**Which jobs are failing**:
 gce-master-scale-performance
 
 **Which test(s) are failing**:
load
 
 **Since when has it been failing**:
 2019-12-06
 
 **Testgrid link**:
 https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance
 
 **Reason for failure**:
 
 ```
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: query error: the server rejected our request due to an error in our request (get services http:prometheus-k8s:9090)]
 ```
 
 **Anything else we need to know**:
 
 /sig scalability
 /assign

**Comment by mm4tt** [comment]
/assign @oxddr 

With your recent PR we now know that the exact error is:
```
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: query error: the server rejected our request due to an error in our request (get services http:prometheus-k8s:9090) [body: {"status":"error","errorType":"execution","error":"query processing would load too many samples into memory in query execution"}]]
```

Do we know which query is causing that?

**Comment by mm4tt** [comment]
Last run passed. Problem seems to be fixed

![9er5mL1GRYC](https://user-images.githubusercontent.com/2604887/70695176-71b25580-1cc1-11ea-9545-2e5d8dab697d.png)

/close
