### ISSUE TITLE
About watch-event

### ISSUE THREAD

**Issue by jhz1103** [kubernetes/kubernetes#86108]
Freshman's question: how can i know the exact  occurrence time of watch event?For example, i got a response from apiServer at 9:00 am of pod-modify, is that the exact time of this event?

**Comment by liggitt** [comment]
The time a watch event occurred is not available from the API. The only consistently available timestamps are object create and delete timestamps, both stored in the metadata stanza of the object.

/close

**Comment by jhz1103** [comment]
Thanks for reply! However, i still can not understand, it should be an easy move to collect the update timestamps
