### ISSUE TITLE
generic_scheduler.go have a panic?

### ISSUE THREAD

**Issue by tiny1990** [kubernetes/kubernetes#86111]
**What you expected to happen**:
panic 

**How to reproduce it (as minimally and precisely as possible)**:
all of RunPostFilterPlugins status success.

**Anything else we need to know?**:
 I read source code 
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L226
RunPostFilterPlugins return nil if all plugin  is success.

```
// Run "prefilter" plugins.
// RunPreFilterPlugins return nil if all plugin success  
preFilterStatus := g.framework.RunPreFilterPlugins(ctx, state, pod)
if !preFilterStatus.IsSuccess() {              <-------------painc here??
	return result, preFilterStatus.AsError()
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): code master

**Comment by tiny1990** [comment]
@draveness

**Comment by tiny1990** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by draveness** [comment]
This is a typed nil, and it won't panic

/close

**Comment by tiny1990** [comment]
> This is a typed nil, and it won't panic
> 
> /close

!postfilterStatus.IsSuccess() no painc ?

**Comment by draveness** [comment]
> > This is a typed nil, and it won't panic
> > /close
> 
> `!postfilterStatus.IsSuccess()` no painc ?

No, this is not a bug. https://play.golang.org/p/0KL1gUOV1jo

```go
package main

import (
	"fmt"
)

func main() {
	var s *Status
	fmt.Println(s.IsSuccess(), ReturnStatus().IsSuccess())
}

func ReturnStatus() *Status {
	return nil
}

type Status struct {
}

func (s *Status) IsSuccess() bool {
	return s == nil
}
```

**Comment by tiny1990** [comment]
> > > This is a typed nil, and it won't panic
> > > /close
> > 
> > 
> > `!postfilterStatus.IsSuccess()` no painc ?
> 
> No, this is not a bug. https://play.golang.org/p/0KL1gUOV1jo
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> )
> 
> func main() {
> 	var s *Status
> 	fmt.Println(s.IsSuccess(), ReturnStatus().IsSuccess())
> }
> 
> func ReturnStatus() *Status {
> 	return nil
> }
> 
> type Status struct {
> }
> 
> func (s *Status) IsSuccess() bool {
> 	return s == nil
> }
> ```

sorry , it's my fault.
