### ISSUE TITLE
Add scheduling cycle e2e latency to scheduler perf dash

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#86126]
**What would you like to be added**:
We should include `e2e_scheduling_duration_seconds` in the scheduler [perf dashboard](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingLatency&Operation=binding). 

* The code that collects metrics is [here](https://github.com/kubernetes/perf-tests/blob/44971cd21c3a33916402bc13b4ec049d097e9263/clusterloader2/pkg/measurement/common/scheduler_latency.go#L124-L133)
* The code that parses test artifacts and renders dashboard UI is [here](https://github.com/kubernetes/perf-tests/blob/38d54e4886e74146aaea4b7ea873b32fd7dfc308/perfdash/parser.go#L268-L275)

**Why is this needed**:
`e2e_scheduling_duration_seconds`  is one of the most important metrics to look at.

/sig scheduling
/needs-help

cc @ahg-g

**Comment by ahg-g** [comment]
Thanks Cong, this is indeed very useful. We should add ```scheduling_duration_seconds``` as well.

**Comment by liu-cong** [comment]
The `scheduling_duration_seconds` is a `Summary` metric. It has label breakdowns for `preemption`, `binding`, etc. It provides the same information as `e2e_scheduling_duration_seconds` along with metrics by each step such as `binding_duration_seconds`.

It looks to me that `scheduling_duration_seconds` will be deprecated.

**Comment by ahg-g** [comment]
sorry, I meant ```scheduling_algorithm_duration_seconds``` which gives the scheduling latency without the binding.

**Comment by yiyang5055** [comment]
maybe i have a try

**Comment by liu-cong** [comment]
Hi @yiyang5055 , are you still interested in completing this?

#86247 is closed, and we need a replacement PR to read `e2e_scheduling_duration_seconds`, which is a Histogram.

**Comment by ahg-g** [comment]
/close

this is actually done.
