### ISSUE TITLE
Add short names for clusterrolebindings and clusterroles

### ISSUE THREAD

**Issue by todd-dsm** [kubernetes/kubernetes#86138]
Request to add short names for:
 * clusterrolebindings (crbs)
 * clusterroles (crs)

And any other resources this long or longer.

**Why is this needed**:
kubernetes can be improved by removing 1 annoyance; pods are abbreviated to 'po' and nodes to 'no' but we're still typing clusterrolebindings out every time.

**Comment by liggitt** [comment]
We've typically only added short names for commonly used CLI resources.

/sig cli auth
/priority awaiting-more-evidence

**Comment by marianopw** [comment]
/reopen
Can we please add an abbreviation for clusterrolebinding? Thanks!
