### ISSUE TITLE
k8s v1.17.0 (client-go v0.17.0) DiscoveryClient throttled

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#86149]
**What happened**:

With client-go v0.17.0, I observed many "Throttling request" when DiscoveryClient is used to get API group resources from API server.

```
I1211 09:20:33.319690       1 request.go:565] Throttling request took 174.476087ms, request: GET:https://foo/apis/batch/v1?timeout=32s
I1211 09:20:33.519663       1 request.go:565] Throttling request took 374.44575ms, request: GET:https://foo/apis/extensions/v1beta1?timeout=32s
I1211 09:20:33.719686       1 request.go:565] Throttling request took 574.463154ms, request: GET:https://foo/apis/apps/v1?timeout=32s
I1211 09:20:33.919699       1 request.go:565] Throttling request took 774.46692ms, request: GET:https://foo/apis/batch/v1beta1?timeout=32s
...
```

This didn't happen with client-go kubernetes-1.16.0.

It looks like originally this kind of discovery requests are not throttled because no rate limiter provided and QPS == 0.
But with https://github.com/kubernetes/client-go/commit/fed41f524ffccd7b19093d5ca85ce9b869531e71
rate limiter is always set if nil rate limiter is provided.

https://github.com/kubernetes/client-go/blob/b9197b961aab3c3328a2178b975cbb81dc9afcde/rest/config.go#L372 is particularly suspicious because it is always true because DefaultQPS is nonzero.

**What you expected to happen**:

Discovery requests should not be throttled as before.

**How to reproduce it (as minimally and precisely as possible)**:

Create DiscoveryClient `discovery.NewDiscoveryClientForConfig()` and then call `restmapper.GetAPIGroupResources()` with it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
The NewTokenBucketRateLimiter was added via

Always negotiate a decoder using ClientNegotiator

/cc @smarterclayton

**Comment by liggitt** [comment]
> Discovery requests should not be throttled as before.

I don't think we should completely disable throttling until more of the server-side priority work is completed, but discovery is expected to be bursty, so I could see defaulting to a different amount in the discovery client constructor, similar to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L222-L225

**Comment by smarterclayton** [comment]
Yeah, everyone must be rate limited.  I think we could give discovery a big burst value.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/86168/files
