### ISSUE TITLE
Define algorithm providers in terms of plugins instead of predicates/priorities [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#86162]
/assign @ahg-g @draveness 
/sig scheduling
/priority important-soon

Part of #85822

**Comment by ahg-g** [comment]
@draveness I will do the first part of this to unblock Cluster Autoscaler integration.

**Comment by draveness** [comment]
> @draveness I will do the first part of this to unblock Cluster Autoscaler integration.

:+1:

**Comment by hex108** [comment]
Would we create a algorithm provider for kubelet?

**Comment by ahg-g** [comment]
I am not sure, it may be too much to have the kubelet instantiate a full framework or scheduler, lets wait and see where we end up.

**Comment by hex108** [comment]
I can give it a try :)

**Comment by ahg-g** [comment]
Sure, but once we move to the new algorithm provider registry, which I am working on.
