### ISSUE TITLE
kube-controller-manager sends normal logs to stderr

### ISSUE THREAD

**Issue by altreze** [kubernetes/kubernetes#86176]
**What happened**:
The logs are being sent to stderr even if it seems just normal log with no error.

```json
{
  "_index": "logstash-2019.12.11",
  "_type": "_doc",
  "_id": "M_qn9m4BUum48S5jwks-",
  "_version": 1,
  "_score": null,
  "_source": {
    "log": "I1211 20:30:13.946398       1 event.go:255] Event(v1.ObjectReference{Kind:\"CronJob\", Namespace:\"kubeapps\", Name:\"apprepo-sync-svc-cat\", UID:\"e14bd388-b6b5-4940-83f8-ff460eb394c8\", APIVersion:\"batch/v1beta1\", ResourceVersion:\"17775381\", FieldPath:\"\"}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job apprepo-sync-svc-cat-1576094400\n",
    "stream": "stderr",
    "docker": {
      "container_id": "d513ab5fa6fd0471eb8eb601edb0e13e34f0b7d7278347b8e59e4d70054df054"
    },
    "kubernetes": {
      "container_name": "kube-controller-manager",
      "namespace_name": "kube-system",
      "pod_name": "kube-controller-manager-MY_HOSTNAME",
      "container_image": "k8s.gcr.io/kube-controller-manager:v1.16.0",
      "container_image_id": "docker-pullable://k8s.gcr.io/kube-controller-manager@sha256:c156a05ee9d40e3ca2ebf9337f38a10558c1fc6c9124006f128a82e6c38cdf3e",
      "pod_id": "dd5af708-eff2-4582-b930-eab3e44cbaa3",
      "host": "MY_HOSTNAME",
      "labels": {
        "component": "kube-controller-manager",
        "tier": "control-plane"
      },
      "master_url": "https://MY_IIP:443/api",
      "namespace_id": "be0de548-c2bd-4279-9c94-190e52600373",
      "namespace_labels": {
        "field_cattle_io/projectId": "p-dlv86"
      }
    },
    "@timestamp": "2019-12-11T20:30:13.946572295+00:00",
    "tag": "kubernetes.var.log.containers.kube-controller-manager-MY_HOSTNAME_kube-system_kube-controller-manager-d513ab5fa6fd0471eb8eb601edb0e13e34f0b7d7278347b8e59e4d70054df054.log"
  },
  "fields": {
    "@timestamp": [
      "2019-12-11T20:30:13.946Z"
    ]
  },
  "highlight": {
    "stream": [
      "@kibana-highlighted-field@stderr@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1576096213946
  ]
}
```

**What you expected to happen**:
Expecting this log to be in stdout not on stderr stream

**Environment**:
- Kubernetes version (use `kubectl version`):
`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
`

Whilst playing `k get nodes`, I am having the following
```
NAME        STATUS   ROLES    AGE   VERSION
master-...   Ready    master   76d   v1.16.3
node-...   Ready    <none>   76d   v1.16.3
node-...   Ready    <none>   26d   v1.16.3
```
The server versions seem misaligned between  `k get nodes` and `kubectl version`

- Cloud provider or hardware configuration: `Baremetal`
- OS (e.g: `cat /etc/os-release`):
`
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
`
- Kernel (e.g. `uname -a`):
`
Linux MY_HOSTNAME 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by roycaihw** [comment]
Based on the log message it looks like it comes from [here](https://github.com/kubernetes/kubernetes/blob/v1.16.0/staging/src/k8s.io/client-go/tools/record/event.go#L255) and [this controller](https://github.com/kubernetes/kubernetes/blob/v1.16.0/pkg/controller/cronjob/cronjob_controller.go#L73). 

I'm not familiar with how the pipeline is set up for `klog.Infof`, but [this comment](https://github.com/kubernetes/kubernetes/blob/v1.16.0/vendor/k8s.io/klog/klog.go#L38) suggests all log statements write to stderr by default. Could you share more about what's your configuration and how to reproduce the issue?

**Comment by altreze** [comment]
What kind of configuration you could like, could you please be more precise ?
Is there any reason why the logs are sent by default to stderr ?
