### ISSUE TITLE
[Flaky Test] [sig-apps] CronJob should delete successful/failed finished jobs with limit of one job

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#86179]
**Which jobs are flaking**:
- pull-kubernetes-e2e-gce
- ci-kubernetes-e2e-gci-gce

**Which test(s) are flaking**:
- [sig-apps] CronJob should delete successful/failed finished jobs with limit of one job

**Testgrid link**:
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&sort-by-flakiness=
- https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-default&width=10&sort-by-flakiness=

**Reason for failure**:
```
I1205 19:17:43.966] STEP: Creating a AllowConcurrent cronjob with custom failed-jobs-history-limit
I1205 19:17:43.966] STEP: Ensuring a finished job exists
I1205 19:17:43.966] STEP: Ensuring a finished job exists by listing jobs explicitly
I1205 19:17:43.967] STEP: Ensuring this job and its pods does not exist anymore
I1205 19:17:43.967] STEP: Ensuring there is 1 finished job by listing jobs explicitly
I1205 19:17:43.967] Dec  5 19:17:35.783: FAIL: Expected
I1205 19:17:43.967]     <int>: 0
I1205 19:17:43.967] to equal
I1205 19:17:43.967]     <int>: 1
...
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/cronjob.go:233
Dec  9 01:17:27.572: Expected
    <int>: 0
to equal
    <int>: 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/cronjob.go:289
```

**Anything else we need to know**:
- this is the top flake for pull-kubernetes-e2e-gce: http://velodrome.k8s.io/dashboard/db/job-health-merge-blocking?panelId=1&fullscreen&orgId=1
- triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=CronJob%20should%20delete%20successful%2Ffailed%20finished%20jobs%20with%20limit%20of%20one%20job
- specific failures
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1203842917643325441
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1203083989460455425

/sig apps
/priority important-soon

**Comment by liggitt** [comment]
this is the second flakiest test (failing on ~15% of PR runs)

**Comment by soltysh** [comment]
I'll look into it.
/assign

**Comment by liggitt** [comment]
if there's not an obvious immediate fix, I would recommend:
1. marking the test as `[Flaky]` to skip the test in merge-blocking job runs
2. opening a second PR that reverts the `[Flaky]` change and adds debugging commits and do `/test ...` on that PR to flush out issues
3. keeping this issue open and in the current milestone to track resolution of the test before release (either by fixing the test, finding/fixing an underlying bug, or proving we have test coverage of the function via another method and deleting the test)

**Comment by liggitt** [comment]
marked as `[Flaky]` in https://github.com/kubernetes/kubernetes/pull/86327, will leave this issue open to track root causing, fixing, restoring the test before release

**Comment by spiffxp** [comment]
To follow up here, this was confirmed as root-caused, fixed and restored by https://github.com/kubernetes/kubernetes/pull/86348
