### ISSUE TITLE
Mount HDFS as a regular volume within kubernetes service. 

### ISSUE THREAD

**Issue by Tombert** [kubernetes/kubernetes#86174]
**What would you like to be added**:
I would like to be able to mount an HDFS cluster as a regular volume.  

**Why is this needed**:
HDFS is a very good, well-supported distributed filesystem, but it's currently quite difficult to use it for filesytem-ey things within vanilla Kubernetes, typically forcing the containers to try and shoehorn in some support with a FUSE mount or something. 

There already exists GlusterFS and Ceph support for Kubernetes, so it doesn't seem like a completely ridiculous request.  I wouldn't even mind trying to implement this myself if someone would be kind enough to point me to the documentation to add new volume support for Kubernetes.

**Comment by Tombert** [comment]
@kubernetes/sig-storage/feature-requests

**Comment by haosdent** [comment]
this requires HDFS to support CSI as I know

**Comment by hoyho** [comment]
> There already exists GlusterFS and Ceph support for Kubernetes

Those in-tree volume plugins will be remove sooner or later.
But it is still possible to support HDFS. For example, you can use CSI to implement this. 
See the document https://kubernetes-csi.github.io/docs/ or join Slack channel [csi](https://kubernetes.slack.com/messages/C8EJ01Z46/details/)
