### ISSUE TITLE
[Flaky Test] [sig-storage] PersistentVolumes GCEPD should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#86181]
**Which jobs are flaking**:
- pull-kubernetes-e2e-gce

**Which test(s) are flaking**:
- [sig-storage] PersistentVolumes GCEPD should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk

**Testgrid link**:
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=GCEPD

**Reason for failure**:
```
test/e2e/storage/persistent_volumes-gce.go:152
Dec 11 17:11:58.309: Unexpected error:
    <*errors.errorString | 0xc0000a18a0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
test/e2e/storage/persistent_volumes-gce.go:159
```

**Anything else we need to know**:
- it seems like this started flaking more frequently during 2019-12-02
- triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=PersistentVolumes%20GCEPD%20should%20test%20that%20deleting%20the%20Namespace%20of%20a%20PVC%20and%20Pod%20causes%20the%20successful%20detach%20of%20Persistent%20Disk
- examples of failures:
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85287/pull-kubernetes-e2e-gce/1204821923024867328
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86142/pull-kubernetes-e2e-gce/1204745549492785152

/area platform/gcp
/sig storage

**Comment by spiffxp** [comment]
/sig cloud-provider
I question whether we should be running this test by default, since it seems like it's exercising a specific cloud provider's implementation of persistent volumes?

**Comment by tedyu** [comment]
Another occurrence of the test failure:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83455/pull-kubernetes-e2e-gce/1204938226029039617/

**Comment by tedyu** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85275/pull-kubernetes-e2e-gce/1206026036261687298/

**Comment by liggitt** [comment]
interestingly this is not flaky at all against master

https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-default&width=5&sort-by-flakiness=&include-filter-by-regex=GCEPD
and is exceptionally flaky in PR jobs:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=GCEPD&width=5

**Comment by liggitt** [comment]
in the last 47 runs, there were 26 failures (and only one PR looked like it could have introduced relevant failures):

* https://github.com/kubernetes/kubernetes/pull/77253
* https://github.com/kubernetes/kubernetes/pull/80973
* https://github.com/kubernetes/kubernetes/pull/81895
* https://github.com/kubernetes/kubernetes/pull/81928
* https://github.com/kubernetes/kubernetes/pull/81934
* https://github.com/kubernetes/kubernetes/pull/83437
* https://github.com/kubernetes/kubernetes/pull/84441
* https://github.com/kubernetes/kubernetes/pull/85879
* https://github.com/kubernetes/kubernetes/pull/85898 (potentially PD storage-related PR)
* https://github.com/kubernetes/kubernetes/pull/86119
* https://github.com/kubernetes/kubernetes/pull/86188
* https://github.com/kubernetes/kubernetes/pull/86199
* https://github.com/kubernetes/kubernetes/pull/86221 (x3)
* https://github.com/kubernetes/kubernetes/pull/86276
* https://github.com/kubernetes/kubernetes/pull/86282 (x3)
* https://github.com/kubernetes/kubernetes/pull/86284
* https://github.com/kubernetes/kubernetes/pull/86289
* https://github.com/kubernetes/kubernetes/pull/86293
* https://github.com/kubernetes/kubernetes/pull/86294
* https://github.com/kubernetes/kubernetes/pull/86298
* https://github.com/kubernetes/kubernetes/pull/86303
* https://github.com/kubernetes/kubernetes/pull/86304

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures 
/assign @msau42

**Comment by liggitt** [comment]
also, the timeout error is on the namespace delete, not the PD detach

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/86313 to mark flaky to unblock the queue, opened https://github.com/kubernetes/kubernetes/pull/86314 to add debugging around the timeout failure; will keep this issue open and in the milestone to ensure the test is fixed or removed before 1.18.0

**Comment by msau42** [comment]
Looking at this run:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86304/pull-kubernetes-e2e-gce/1206527716946350083/

```
I1216 11:25:50.436927       1 namespaced_resources_deleter.go:506] namespace controller - deleteAllContent - namespace: pv-797
E1216 11:26:16.154085       1 namespace_controller.go:162] deletion of namespace pv-797 failed: unexpected items still remain in namespace: pv-797 for gvr: /v1, Resource=pods
I1216 11:31:40.348967       1 namespace_controller.go:185] Namespace has been deleted pv-797
```

namespace deletion timeout in the test is 5 minutes, so looks like this took just a little longer.  Looking into what is taking the pod so long to be deleted

**Comment by msau42** [comment]
It seems like kubelet tore down and deleted the Pod pretty quickly and it was registered by apiserver log. For some reason, the namespace controller doesn't see that deletion?

kubelet.log:
```
I1216 11:25:54.715742    1335 kubelet.go:1922] SyncLoop (DELETE, "api"): "pvc-tester-bvxjs_pv-797(5122088e-c60a-415d-a74d-fee2a834ca2e)"

I1216 11:25:57.039567    1335 desired_state_of_world_populator.go:275] Removing volume from desired state for volume "gce-cqjsj" (UniqueName: "kubernetes.io/gce-pd/e2e-143519fb90-674b9-be44be34-f85a-493c-a87b-b9e96dc15221") pod "pvc-tester-bvxjs" (UID: "5122088e-c60a-415d-a74d-fee2a834ca2e")
I1216 11:25:57.039927    1335 desired_state_of_world_populator.go:275] Removing volume from desired state for volume "default-token-w69c5" (UniqueName: "kubernetes.io/secret/5122088e-c60a-415d-a74d-fee2a834ca2e-default-token-w69c5") pod "pvc-tester-bvxjs" (UID: "5122088e-c60a-415d-a74d-fee2a834ca2e")
I1216 11:25:57.082358    1335 reconciler.go:183] operationExecutor.UnmountVolume started for volume "default-token-w69c5" (UniqueName: "kubernetes.io/secret/5122088e-c60a-415d-a74d-fee2a834ca2e-default-token-w69c5") pod "5122088e-c60a-415d-a74d-fee2a834ca2e" (UID: "5122088e-c60a-415d-a74d-fee2a834ca2e")
I1216 11:25:57.082535    1335 reconciler.go:183] operationExecutor.UnmountVolume started for volume "volume1" (UniqueName: "kubernetes.io/gce-pd/e2e-143519fb90-674b9-be44be34-f85a-493c-a87b-b9e96dc15221") pod "5122088e-c60a-415d-a74d-fee2a834ca2e" (UID: "5122088e-c60a-415d-a74d-fee2a834ca2e")

I1216 11:25:57.104903    1335 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/5122088e-c60a-415d-a74d-fee2a834ca2e-default-token-w69c5" (OuterVolumeSpecName: "default-token-w69c5") pod "5122088e-c60a-415d-a74d-fee2a834ca2e" (UID: "5122088e-c60a-415d-a74d-fee2a834ca2e"). InnerVolumeSpecName "default-token-w69c5". PluginName "kubernetes.io/secret", VolumeGidValue ""
I1216 11:25:57.105808    1335 mount_helper_common.go:81] "/var/lib/kubelet/pods/5122088e-c60a-415d-a74d-fee2a834ca2e/volumes/kubernetes.io~gce-pd/gce-cqjsj" is unmounted, deleting the directory
I1216 11:25:57.106073    1335 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/gce-pd/e2e-143519fb90-674b9-be44be34-f85a-493c-a87b-b9e96dc15221" (OuterVolumeSpecName: "volume1") pod "5122088e-c60a-415d-a74d-fee2a834ca2e" (UID: "5122088e-c60a-415d-a74d-fee2a834ca2e"). InnerVolumeSpecName "gce-cqjsj". PluginName "kubernetes.io/gce-pd", VolumeGidValue "777"

I1216 11:25:57.253446    1335 operation_generator.go:800] UnmountDevice succeeded for volume "gce-cqjsj" %!(EXTRA string=UnmountDevice succeeded for volume "gce-cqjsj" (UniqueName: "kubernetes.io/gce-pd/e2e-143519fb90-674b9-be44be34-f85a-493c-a87b-b9e96dc15221") on node "e2e-143519fb90-674b9-minion-group-62ps" )
I1216 11:25:57.284393    1335 reconciler.go:303] Volume detached for volume "gce-cqjsj" (UniqueName: "kubernetes.io/gce-pd/e2e-143519fb90-674b9-be44be34-f85a-493c-a87b-b9e96dc15221") on node "e2e-143519fb90-674b9-minion-group-62ps" DevicePath "/dev/disk/by-id/google-e2e-143519fb90-674b9-be44be34-f85a-493c-a87b-b9e96dc15221"

I1216 11:25:59.536502    1335 status_manager.go:564] Pod "pvc-tester-bvxjs_pv-797(5122088e-c60a-415d-a74d-fee2a834ca2e)" fully terminated and removed from etcd
I1216 11:25:59.538536    1335 config.go:303] Setting pods for source api
I1216 11:25:59.546997    1335 kubelet.go:1916] SyncLoop (REMOVE, "api"): "pvc-tester-bvxjs_pv-797(5122088e-c60a-415d-a74d-fee2a834ca2e)"
I1216 11:25:59.647641    1335 kubelet.go:2111] Failed to delete pod "pvc-tester-bvxjs_pv-797(5122088e-c60a-415d-a74d-fee2a834ca2e)", err: pod not found
```

apiserver.log
```
I1216 11:25:59.529363       1 httplog.go:90] DELETE /api/v1/namespaces/pv-797/pods/pvc-tester-bvxjs: (898.623972ms) 200 [kubelet/v1.18.0 (linux/amd64) kubernetes/d32ff95 34.82.91.93:39088]
I1216 11:25:59.612312       1 graph_populator.go:165] deletePod pv-797/pvc-tester-bvxjs for node e2e-143519fb90-674b9-minion-group-62ps

I1216 11:28:04.014244       1 httplog.go:90] DELETE /api/v1/namespaces/pv-797/pods/pvc-tester-bvxjs: (11.233187ms) 404 [e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] PersistentVolumes GCEPD should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk 35.225.67.44:50906]
```

**Comment by tedyu** [comment]
From kubelet.log in https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/86304/pull-kubernetes-e2e-gce/1206527716946350083/artifacts/e2e-143519fb90-674b9-minion-group-62ps/ , a little earlier than the log @msau42 posted:

E1216 11:23:16.309541    1335 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/glusterfs/8cadf6af-c02f-4701-9708-b6b4621e49d3-test-volume\" (\"8cadf6af-c02f-4701-9708-b6b4621e49d3\")" failed. No retries permitted until 2019-12-16 11:23:16.809198244 +0000 UTC m=+1060.082156591 (durationBeforeRetry 500ms). Error: "recovered from panic \"runtime error: invalid memory address or nil pointer dereference\". (err=<nil>) Call stack:\ngoroutine 78440 [running]:\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0032cad50)\n\tstaging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5\npanic(0x3a27160, 0x6d2bdf0)\n\tGOROOT/src/runtime/panic.go:679 +0x1b2\nk8s.io/kubernetes/pkg/volume/util/subpath.doCleanSubPaths.func1(0xc000c94a20, 0x81, 0x0, 0x0, 0x4979460, 0xc0021d0b40, 0x0, 0x0)\n\tpkg/volume/util/subpath/subpath_linux.go:243 +0xbd\npath/filepath.walk(0xc001f82a80, 0x7f, 0x4a33500, 0xc002099790, 0xc0011a7ba8, 0x0, 0x7f)\n\tGOROOT/src/path/filepath/path.go:378 +0x20c\npath/filepath.Walk(0xc001f82a80, 0x7f, 0xc001fdcba8, 0xc001f82a80, 0x7f)\n\tGOROOT/src/path/filepath/path.go:404 +0xff\nk8s.io/kubernetes/pkg/volume/util/subpath.doCleanSubPaths(0x4a28680, 0xc00090d580, 0xc0016416c0, 0x3a, 0xc002b50dd0, 0xb, 0xc0016416c0, 0x3a)\n\tpkg/volume/util/subpath/subpath_linux.go:232 +0x8ce\nk8s.io/kubernetes/pkg/volume/util/subpath.(*subpath).CleanSubPaths(0xc0004a08b0, 0xc0016416c0, 0x3a, 0xc002b50dd0, 0xb, 0x1, 0x0)\n\tpkg/volume/util/subpath/subpath_linux.go:57 +0x5f\nk8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateUnmountVolumeFunc.func1(0xc0012f95e0, 0xc0032cad50, 0x2e, 0x1)\n\tpkg/volume/util/operationexecutor/operation_generator.go:702 +0x15a\nk8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run(0xc001dd3200, 0x45c1e0, 0xc0016b6ba0, 0xc000e16c90, 0xc0019c02a1)\n\tpkg/volume/util/types/types.go:51 +0xd6\nk8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1(0xc001039580, 0xc0010a2e10, 0x48, 0xc0020085d0, 0x24, 0xc001dd3200, 0x0, 0x0, 0x0, 0x0)\n\tpkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:146 +0x114\ncreated by k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run\n\tpkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:141 +0x39f\n"

**Comment by msau42** [comment]
I'm not sure the kubelet panic is related to this test flake. 

So far in this flake, the API server did register pod deletion, but the namespace controller still seems to think the pod is not deleted.

**Comment by zehuaiWANG** [comment]
[#8144](https://github.com/kubernetes/kops/pull/8144) This problem also happened in kops.

**Comment by zehuaiWANG** [comment]
@liggitt @spiffxp I encountered this problem in kubernetes and Kops projects, which seems to be more serious.

**Comment by liggitt** [comment]
test has been marked flaky, and can now be seen in https://testgrid.k8s.io/google-gce#gci-gce-flaky&sort-by-flakiness=&width=20&include-filter-by-regex=GCEPD

root cause is an extremely slow namespace deletion controller; see analysis in https://github.com/kubernetes/kubernetes/pull/86314#issuecomment-566357652

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/86417 to track the namespace controller issue. In the meantime, I would probably suggest rewriting this test to:
1. issue the namespace delete
2. issue deletecollection calls against the pvcs and pods
3. wait for the absence of the pvc and pod objects, rather than the namespace

**Comment by msau42** [comment]
I think then the test case would be very similar to
"[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node", which

1. Creates 2 PVCs used by a single Pod
2. Deletes the pod
3. Force reschedules the pod to a different node and validates that it was successful (which indicates that it got detached and reattached successfully)
4. Deletes Pod and PVC at the end and verifies PV deletion.

I'm in favor of just removing this test (and having a separate non-storage test for namespace deletion) since we already have similar coverage in an existing test case.

**Comment by liggitt** [comment]
Doing this inside a deleting namespace ensures nothing blocks on the inability to create events. I would keep that aspect of it and just trigger the pod/pvc deletions yourself.

**Comment by msau42** [comment]
Ok, then I would be more in favor of adding a new test case in our testsuite that explicitly does the namespace deletion. I want to start moving away from having cloud provider-specific tests, and as a bonus we'll get coverage for CSI drivers too.

**Comment by liggitt** [comment]
I'm ok adding a test specifically around namespace deletion, but ensuring the PV/PVC infrastructure behaves well in a namespace that is being deleted seems valuable as well (and that test would not need to wait on the namespace to disappear)

**Comment by msau42** [comment]
Agree. When I said "testsuite" I meant the [storage testsuite](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/testsuites)

**Comment by Nuru** [comment]
Hit by #91355 see https://github.com/kubernetes/kubernetes/pull/91355#issuecomment-636201937
