### ISSUE TITLE
e2e-gce-device-plugin-gpu fails for branch-1.16

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#86197]
**Which jobs are failing**:
pull-kubernetes-e2e-gce-device-plugin-gpu

**Which test(s) are failing**:

**Testgrid link**:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/86191/pull-kubernetes-e2e-gce-device-plugin-gpu/1204971573304365056/build-log.txt

**Reason for failure**:

W1212 03:58:56.297] 2019/12/12 03:58:56 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 193.520519ms
W1212 03:58:56.298] 2019/12/12 03:58:56 main.go:319: Something went wrong: failed to acquire k8s binaries: U=file:///go/src/k8s.io/kubernetes/_output/gcs-stage R=v1.16.4-3+98400ca2422272 get-kube.sh failed: error during /workspace/get-kube.sh: exit status 1

**Anything else we need to know**:

**Comment by tedyu** [comment]
Ref #86191

**Comment by tedyu** [comment]
Fails in 1.15 as well:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86195/pull-kubernetes-e2e-gce/1204977361292890113/

**Comment by justaugustus** [comment]
Closing to consolidate the conversation on https://github.com/kubernetes/kubernetes/issues/86182.
/close
