### ISSUE TITLE
GCE 1.14, 1.15 pod startup latency regression

### ISSUE THREAD

**Issue by pierewoj** [kubernetes/kubernetes#86217]
**What happened**:
Pod startup latency seems to degrade around 5th November, see two runs:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable3/1188908638056484864/
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable3/1194706717250686977/
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-1.14&metriccategoryname=E2E&metricname=DensityPodStartup&Metric=pod_startup

In case of 1.14:
p50 2200ms -> 2500ms (+300ms)
p90 2800ms -> 3150ms (+350ms)
p99 3150ms -> 3550ms (+400ms)

Similarly in 1.15: http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-1.15&metriccategoryname=E2E&metricname=DensityPodStartup&Metric=pod_startup

It does not fail all tests, but we're getting closer to the 5s SLO (and we crossed it once recently causing 1 fail https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/1204249626241142795/)

/sig scalability

**Comment by pierewoj** [comment]
Potentially related to https://github.com/kubernetes/test-infra/pull/15106 - then it would mean that it's not a regression but a change in what version is actually tested by sig-release jobs.

Jacek, can you PTAL?
/assign @jkaniuk

**Comment by jkaniuk** [comment]
For two stable3 runs that you mentioned:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable3/1188908638056484864/
Test started 10/28/2019, that is 1.13.13-beta.0.1+874f0559d9b358
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable3/1194706717250686977/
Test started 11/13/2019, that is 1.14.10-beta.0.1+6193bbb5d0bb9b

just before and after latency increase on 12/05/2019:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable3/1191445236493062144/
Test started 11/04/2019, 1.14.9-beta.0.16+c99bc0cf528166
after:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable3/1191626360519397378/
Test started 11/05/2019, 1.14.9-beta.0.18+ac756284b8908e

About stable2:

latency drop on 10/31/2019, before:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/1189572853767344131/
Test started 10/30/2019, 1.14.9-beta.0.16+c99bc0cf528166
after:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/1189754194408509440/
Test started 10/31/2019, 1.15.6-beta.0.14+0f71449be978a5

latency increase on 11/05/2019, before:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/1191747162694750211/
Test started 11/05/2019, 1.15.6-beta.0.16+670c7810991876
after:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/1191928364068245505/
Test started 11/06/2019, 1.15.6-beta.0.18+a1260f0d539c3b
