### ISSUE TITLE
Introduce library of helper plugins that can be used by in-tree and out of tree components

### ISSUE THREAD

**Issue by hprateek43** [kubernetes/kubernetes#86236]
**What would you like to be added**:
In general, we might need a library of helper functions that both in-tree and out-of-tree plugins can use. We should finalise a location for this library and refactor common code components there.

**Why is this needed**:
Currently the homegrown `.import-restrictions` tool requires explicit listing for all transitive dependencies, even internal ones. However, the golang compiler does not allow the import of internal libraries anyway. This leads to a challenge is cleanups of components like `scheduler` as `controller` has transitive dependencies around the `errchannels`. This could have been circumvented if such code was placed in a common library that can be used by multiple components.

**Reference PRs that were affected by this**:
https://github.com/kubernetes/kubernetes/pull/85773
https://github.com/kubernetes/kubernetes/pull/84336

**Comment by hprateek43** [comment]
@alculquicondor @ahg-g Added for reference around our discussion

**Comment by alculquicondor** [comment]
Thanks @hprateek43 for opening this. We will probably need to progress a bit more with #85822 before being able to suggest a solution to this.
