### ISSUE TITLE
GCP credentialprovider loops forever in case of metadata url cannot be reached

### ISSUE THREAD

**Issue by vdemeester** [kubernetes/kubernetes#86245]
**What happened**:

Deploying [knative](https://github.com/knative) on top of OpenShift in GCP (or [tekton](https://github.com/tekton)) currently doesn't work because one of `knative/pkg`'s dependency ([`google/go-containerrigestry`](https://github.com/google/go-containerregistry)) imports the `credentialprovider/gcp` package.

At the import of this package, the `init()` tries to do some magic, and especially tries to contact a metadata url (http://metadata.google.internal./computeMetadata/v1/). This url (amongst others) is usually blacklisted by OpenShift or other K8s distros.  

The main issue is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/gcp/metadata.go#L239), as this metadata URL is being *disallowed* by OpenShift, this loops for ever (with backofff, but still), and thus it blocks the rest of the code execution — preventing for any knative or tekton controller to ever be started.

Related issue in tekton : https://github.com/tektoncd/pipeline/issues/1742

**What you expected to happen**:

Not having this loop forever and blocking the rest of the code execution.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install OpenShift on GCP
2. Install tekton on it (using the OpenShift Pipelines operator or directly applying the release yaml)
3. Look at the controller and the resource not being created.

**Anything else we need to know?**:

The current fix happens in `go-containerregistry` by adding build tags to be able to disallow those import if needed, see https://github.com/google/go-containerregistry/pull/630. This is however just a rubber band as, this would be needed for any other dependency that imports that credentialprovider package.

**Environment**:
- Kubernetes version (use `kubectl version`): OpenShift 4.2.x (`Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+17b1cc6", GitCommit:"17b1cc6", GitTreeState:"clean", BuildDate:"2019-12-03T07:03:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`)
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dims** [comment]
Related to https://github.com/kubernetes/enhancements/pull/1406

**Comment by DanielJonesEB** [comment]
This also causes issues in Kaniko, which makes it unpossible to build OCI images in a secure environment:  https://github.com/GoogleContainerTools/kaniko/issues/937

The problematic line of code is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/gcp/metadata.go#L215

It is an unreasonable assumption that the metadata server should be reachable, and there are valid reasons for disabling access to it.

**Comment by jpbetz** [comment]
The GCP credential provider is multiple places, and I'm not yet convinced that setting a max retry limit in a safe change for all of them. The one case I'm most concerned with is having kubelets start in GCP and run indefinitely with the GCP credential provider disabled because the metadata endpoint was unavailable at the time the kubelet started up. We need to be sure we don't introduce a problem like that when we solve this.

cc @DangerOnTheRanger

**Comment by DanielJonesEB** [comment]
> We need to be sure we don't introduce a problem like that when we solve this.

Is there any precedent for feature flagging in the codebase? Seems like the sort of thing that an env var would be useful for, although I could understand uneasiness about having something deep in the code reach out to the environment rather than being explicit in the API. That said, if the proposed new behaviour was opt-in and controlled via an env var, then no existing users would be impacted and the surface area of the change is much smaller.

**Comment by DangerOnTheRanger** [comment]
When GCP moves over to a credential provider plugin (via the framework implemented by https://github.com/kubernetes/kubernetes/pull/94196 and outlined in https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2133-out-of-tree-credential-provider) this problem ought to go away. The reason being, the code that causes the infinite loop is only run when figuring out whether the GCP credential provider should be enabled. Under the out-of-tree credential provider system, the credential provider configuration file and presence of the plugin binary are used instead to figure out if a given plugin should be enabled.

Unfortunately that all doesn't help in the short-term (or at least until the out-of-tree credential provider is used and deployed), but long-term I think we ought to be able to sidestep this problem entirely. For the short-term, something optional like @DanielJonesEB mentioned might be a good way to go about it. The current behavior is expected/works well in situations like @jpbetz brought up, and having an optional timeout should provide a means to fix things like knative deployment, as well.
