### ISSUE TITLE
Create pod with spec.containers[0].resources.limits.cpu = 0

### ISSUE THREAD

**Issue by anencore94** [kubernetes/kubernetes#86244]
**What happened**:

I tried to create pods with below spec:
```
spec.containers[0].resources.limits.cpu = 0
spec.containers[0].resources.limits.memory = 0
spec.containers[0].resources.requests.cpu = 0
spec.containers[0].resources.requests.memory = 0
```
under namespaces with or without resourceQuota. (without LimitRange in such namespaces)

Then pods created successfully.

**What you expected to happen**:

First of all, I wonder that the value zero in resources.limits.ResourceName means unlimited or not.

Since I couldn't find any official docs about this subject in kubernetes.io. If there is any, apologize myself to question duplicated subject.

If it means unlimited, then it make sense that users can create inifinitely many pods in the namespace which has some limits on resourceQuota.

Otherwise, however, it seems abnormal that user could create pods regardless of resourceQuota. It seems a loophole.

Thank you for reading my report.

**How to reproduce it (as minimally and precisely as possible)**:
Create pod with below spec under any namespace.:
```
spec.containers[0].resources.limits.cpu = 0
spec.containers[0].resources.limits.memory = 0
spec.containers[0].resources.requests.cpu = 0
spec.containers[0].resources.requests.memory = 0
```

**Anything else we need to know?**:
None

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.16.2
- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
  - OS version : ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by praseodym** [comment]
A request of zero CPU and memory effectively means "infinitely small" for the scheduler deciding on which node to place the pod. In practice this means that the pod is very likely to get (OOM) killed or evicted on a node with high utilisation.

Setting a zero limit does mean there is no hard resource limit, but the risk of eviction is still present.

I'd recommend always setting a [LimitRange](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/#create-a-limitrange-and-a-pod) in addition to any [ResourceQuota](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace/#create-a-resourcequota) to prevent (accidental) abuse.

/remove-kind bug
/triage support

**Comment by anencore94** [comment]
Thanks @praseodym. I understand your recommendation to use LimitRange objects.
By the way, I just wonder what '0' means actually.
By your comment, you mean the resource.limits and resource.requests values are used only for scheduling?
If so, for example, resource.requests.cpu = 4 and resource.requests.cpu = 0 does not affect any performance of pod actually?

Thanks for your comment again.

**Comment by praseodym** [comment]
Setting a request value will set the [container’s cpu_shares value](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run), which affects its performance in periods of CPU contention (i.e. how much CPU each container gets to use when the CPU is 100% in use).

**Comment by thockin** [comment]
Setting resources to 0 lowers the overall QoS band for the pod, which makes it more likely to be evicted.  In practice, you can't set 0 for things like CPU shares, so it gets translated to a small, but representable, value.

You can also set quotas on number of pods.  https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object/

Since this is not a bug or feature request, I am going to close it now.  Please re-open if you think this is wrong :)

**Comment by tibetsam** [comment]
what if both request and limit are not specified, and no default quota for namespace? dose that mean the pod can eat up all resources on that node? i can only find explanation about no limit in k8s document. https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/

**Comment by syedrakib** [comment]
@anencore94 just to clarify your query... when you said
> .... resource.requests.cpu = 4 and resource.requests.cpu = 0 does not affect any performance of pod actually?

Did you mean?
> resource.requests.cpu = 4 and resource.limits.cpu = 0
