### ISSUE TITLE
test images: gcr.io/kubernetes-e2e-test-images/dnsutils:1.2 not built properly

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#86257]
**Which jobs are failing**:

N/A - there is a PR that requires CoreDNS (https://github.com/kubernetes/kubernetes/pull/77862), that was added in ``dnsutils:1.2``, but it can't merge because the image is not built properly.

**Which test(s) are failing**:

``DNS should support configurable pod resolv.conf``

**Since when has it been failing**:

N/A

**Testgrid link**:

N/A

**Reason for failure**:

The image ``gcr.io/kubernetes-e2e-test-images/dnsutils:1.2`` exists, but it's not built properly. It is supposed to contain CoreDNS, but it doesn't. The change that added CoreDNS to the image is: https://github.com/kubernetes/kubernetes/pull/77861

**Anything else we need to know**:

/sig testing
/area conformance

**Comment by cjwagner** [comment]
Can you add an image publishing job instead so that this is done automatically when the [version file](https://github.com/kubernetes/kubernetes/blob/master/test/images/dnsutils/VERSION) is updated? https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing

**Comment by claudiubelu** [comment]
> 
> 
> Can you add an image publishing job instead so that this is done automatically when the [version file](https://github.com/kubernetes/kubernetes/blob/master/test/images/dnsutils/VERSION) is updated? https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing

https://github.com/kubernetes/test-infra/pull/14833

**Comment by claudiubelu** [comment]
Bump. So, can we have the image rebuilt / republished?

**Comment by claudiubelu** [comment]
No longer needed, the dnsutils image has been centralized into agnhost, and it includes CoreDNS.

/close
