### ISSUE TITLE
API: frequent ResourceVersion changes (from status updates) cause false conflicts

### ISSUE THREAD

**Issue by sym3tri** [kubernetes/kubernetes#8625]
I've noticed that the `resourceVersion`of a resource will update even if only the `status` section has changed. I get that technically the RESTful resource _has_ changed and this is needed to trigger events. However this is problematic when you need to update a resource during a period of frequent status changes, b/c the `resourceVersion` in PUT requests must be in sync with the API server's version. The status could be changing so quickly that the roundtrip required for a GET then PUT will almost always be too slow.

A simple way to reproduce this:
1. Kill some of the kubelets in the cluster.
2. Create an RC with a simple pod template & set the Count to a sufficiently high number.
3. Wait a little, then attempt to update the Replication Controller.

The RC will constantly try to fulfill its desired count. Most of the pods will fail to run b/c they get scheduled to dead kubelets. This causes the RC's `status.count` to flap constantly, in turn increasing the `resourceVersion` every time. This makes it nearly impossible for the operator (or other components) to reliably update the RC b/c as soon as the resource is retrieved it's outdated very shortly after.

Related to: #2726

**Comment by derekwaynecarr** [comment]
Throttling replication controller could help.  How high are you sizing up the controller?

**Comment by sym3tri** [comment]
I view this as a general usability issue with the API. In such a dynamic system tying the status to the resource version just doesn't seem practical.

I've also noticed this with Nodes since they heartbeat back their status constantly. I'm working around this by using PATCH requests where possible, but that won't work in all cases.

**Comment by bgrant0607** [comment]
Mitigating false conflicts is something I was planning to revisit after 1.0. For now, our client library does retries.

There are clients that watch status. 

One solution would be to store spec and status separately.

Also sort of related: #7328, #1459

Ref #8190

**Comment by lavalamp** [comment]
Goal for reducing false conflicts is to split spec and status into separate resources (to be rejoined as needed for old clients).

**Comment by smarterclayton** [comment]
We really have no plans to do this in the near term.  It's in the back of peoples' minds, but PATCH generally makes this more palatable, and edit and other "smart" UIs can mitigate the impact.
