### ISSUE TITLE
cluster/get-kube.sh pulls from wrong bucket with prerelease versions

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#86267]
If you give a prerelease version to `cluster/get-kube.sh`, it'll match both `KUBE_CI_VERSION_REGEX` and `KUBE_RELEASE_VERSION_REGEX`.

Based on this logic:
https://github.com/kubernetes/kubernetes/blob/6e38a0f46e8485a76fe504e51b0f163eaa5141d3/cluster/get-kube.sh#L193-L200

We'll end up trying to pull binaries for this prerelease from the CI bucket (https://dl.k8s.io/ci) rather than the release bucket (https://dl.k8s.io).

These pre-release versions are usually* pushed to the release bucket as part of the release process (e.g. [v1.14.11-beta.0](https://gcsweb.k8s.io/gcs/kubernetes-release/release/v1.14.11-beta.0/)), and so `get-kube.sh` should probably prefer these over the CI versions (which may or may not exist, depending on whether a commit was pushed to the release branch between when the tag was created and the build occurred).

More explicitly, the current logic is:
1. Prefer the release bucket by default.
2. If a version matches the CI regex, use the CI bucket.
3. Else, if a version matches the release regex, we're good - continue to use the default (release bucket).
4. Else, bail out - invalid version.

The correct logic would probably be something like
1. Prefer the release bucket by default.
2. If a version matches the release version regex, continue to use the release bucket.
3. Else, if a version doesn't match the release version regex, but it matches the CI regex, use the CI bucket.
4. If it matches neither, bail out.

**Important note**: due to our hotfix for https://github.com/kubernetes/kubernetes/issues/86182, there is a somewhat fake prerelease tag ([v1.14.11-beta.1](https://github.com/kubernetes/kubernetes/releases/tag/v1.14.11-beta.1)) which doesn't have any bits in the release bucket, and we expect others soon. We should not fix this bug in `get-kube.sh` until the latest pointers in the CI bucket do not point to valid release/prerelease versions.

**Comment by ixdy** [comment]
/sig testing
/sig release

I guess?

**Comment by smourapina** [comment]
Hello @justaugustus, @ixdy!
With code freeze approaching for 1.18 (5 March), can you please check if the current issue is still intended for milestone 1.18?

**Comment by justaugustus** [comment]
@smourapina -- I'm pretty sure I can get to this before the cycle is out.

**Comment by liggitt** [comment]
@justaugustus if our current approach for tagging release branch pre-releases doesn't trigger this, this seems like it is not critical for the milestone, is that correct?

**Comment by justaugustus** [comment]
@liggitt -- Good point!

/milestone v1.19
/remove-priority critical-urgent
/priority important-soon

**Comment by justaugustus** [comment]
Given the priority dip on this one, I think it's fine for someone in Releng other than Tim or I to pick this up.

/unassign @tpepper @justaugustus 

@kubernetes/release-engineering -- This is a good one to work on.
/help

**Comment by cpanato** [comment]
I can look that, after the release 1.18, if is that fine @justaugustus 

then can we have a short discussion about this one?

/remove-help
/assign

**Comment by justaugustus** [comment]
@cpanato -- SGTM
