### ISSUE TITLE
Every 2 second update of kube-scheduler and kube-controller-manager endpoints

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#86286]
**What happened**:
a controller watching for endpoint add/delete/update gets update event every 2 seconds for kube-scheduler and kube-controller-manager's endpoints.

Update is triggered due to update of renewTime in both objects annotation.

kind: Endpoints
metadata:
  annotations:
    `control-plane.alpha.kubernetes.io/leader:` '{"holderIdentity":"kube-4_7a53b8ee-b00b-4a82-acd2-777cfc725f43","leaseDurationSeconds":15,"acquireTime":"2019-12-11T22:37:03Z","`renewTime`":"2019-12-16T03:17:14Z","leaderTransitions":23}'

**What you expected to happen**:
Updating annotation every 2 seconds seems to be too excessive.
**How to reproduce it (as minimally and precisely as possible)**:

Run:
` kubectl get endpoints -o yaml kube-scheduler -n kube-system`
and check `Annotations`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`): Linux kube-4 5.0.0-20-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery

**Comment by roycaihw** [comment]
This is working as intended. The leader election retry period is defaulted to 2s and configurable through

```
--leader-elect-retry-period duration     Default: 2s
--
  | The duration the clients should wait between attempting acquisition and renewal of a leadership. This is only applicable if leader election is enabled.
```
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

You can also exclude those endpoints using selectors if the controller doesn't care about them

Ref https://github.com/kubernetes/kubernetes/issues/23812

**Comment by mikedanese** [comment]
We're also in the process of migrating off of endpoints and onto leases.

**Comment by sbezverk** [comment]
@roycaihw  What would be the exclusion  selection criteria? I do not see any specific labels on kube-scheduler and kube-contoller-manager which can be used to exclude them. Checking for these two names to ignore in the controller would be very costly.  I can only see annotations, but ListOptions does not have option to filter on Annotations. Would you accept extending ListOptions to support filtering based on annotations?
Cilium seems hacked the endpoint's informer to ignore these, but it is not a generic solution.

**Comment by roycaihw** [comment]
@sbezverk sorry for the late response. I thought you could use field selector to exclude those endpoints or the entire kube-system namespace with [field selector](https://github.com/kubernetes/client-go/blob/da706024f356a0d7bf19dfb7a7133967e4c2aaa6/tools/cache/shared_informer.go#L42)

https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/
