### ISSUE TITLE
Unstructured converted to struct with anonymous field error when json is inline mode

### ISSUE THREAD

**Issue by leileiwan** [kubernetes/kubernetes#86285]
* The Struct is PytorchJob. Frist we convert the PytorchJob to Unstructed with json.Then we use function FromUnstructured convert Unstructed to PytorchJob,it cannot convert anonymous field "common.JobStatus" success.
    ```
    type PytorchJob struct {
        ...
        Status PytorchStatus `json:"status,omitempty"`
    }
    type PytorchStatus struct {
        common.JobStatus
        StatusForAdjust string `json:"statusForAdjust,omitempty"`
        ....
    }
    ```

* I printed the Unstructed and converted PytorchJob,PytorchJob does not have the Success status after the conversion is performed.And the Unstructured Status shows that the common.JobStatus part of the json is the inline attribute (excluding JobStatus Struct), but the PytorchJob receives it not through the inline form (including JobStatus Struct, from "{{[] map [] } 0 0}} ”can be seen)

    ```
    func (c *unstructuredConverter) FromUnstructured(u map[string]interface{}, obj interface{}) error {
        t := reflect.TypeOf(obj)
        value := reflect.ValueOf(obj)
        ....
        fmt.Println(reflect.ValueOf(u))
        err := fromUnstructured(reflect.ValueOf(u), value.Elem())
        fmt.Println(value.Elem())
        ...
    }
    ```

    ```
    map[kind:PytorchJob metadata:map[creationTimestamp:<nil> name:test-pytorchjob namespace:default] spec:map[block:<nil> cleanPodPolicy:All maxGPU:4 minGPU:4 pytorchReplicaSpecs:map[Master:map[replicas:1 template:map[metadata:map[creationTimestamp:<nil>] spec:map[containers:[map[args:[Fake Fake] image:test-image-for-kubeflow-pytorch-operator:latest name:pytorch ports:[map[containerPort:23456 name:pytorchjob-port]] resources:map[]]]]]] Worker:map[replicas:4 template:map[metadata:map[creationTimestamp:<nil>] spec:map[containers:[map[args:[Fake Fake] image:test-image-for-kubeflow-pytorch-operator:latest name:pytorch ports:[map[containerPort:23456 name:pytorchjob-port]] resources:map[]]]]]]] topologyGPU:<nil>] status:map[conditions:[map[lastTransitionTime:2019-12-14T09:02:53Z lastUpdateTime:2019-12-14T09:02:53Z reason:PytorchJobSucceeded status:True type:Succeeded]] replicaStatuses:<nil>]]

    {{PytorchJob } {test-pytorchjob  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {<nil> <nil> 0xc0002bb0d0 <nil> 0xc000608cf8 0xc000608d08 <nil> <nil> map[Master:0xc000139600 Worker:0xc000139b80]} {{[] map[] <nil> <nil> <nil>}  0 0}}
    ```

* When the conversion to common.JobStatus is performed, the else part of the code will be executed (I have Printed fieldInfo.name is JobStatus), and the function will take the value of the key "JobStatus" from the sv map according to JobStatus, which is obviously not found. Therefore, a zero value is set for the JobStatus
    ```
    func structFromUnstructured(sv, dv reflect.Value) error {
        st, dt := sv.Type(), dv.Type()
        if st.Kind() != reflect.Map {
            return fmt.Errorf("cannot restore struct from: %v", st.Kind())
        }

        for i := 0; i < dt.NumField(); i++ {
            fieldInfo := fieldInfoFromField(dt, i)
            fv := dv.Field(i)
            if len(fieldInfo.name) == 0 {
                // This field is inlined.
                if err := fromUnstructured(sv, fv); err != nil {
                    return err
                }
            } else {
                value := unwrapInterface(sv.MapIndex(fieldInfo.nameValue))
                if value.IsValid() {
                    if err := fromUnstructured(value, fv); err != nil {
                        return err
                    }
                } else {
                    fv.Set(reflect.Zero(fv.Type()))
                }
            }
        }
        return nil
    }
    ```
    ```
    status:map[conditions:[map[lastTransitionTime:2019-12-14T09:02:53Z lastUpdateTime:2019-12-14T09:02:53Z reason:PytorchJobSucceeded status:True type:Succeeded]] replicaStatuses:<nil>]]
    ```

* We need to handle the case where anonymous filed is included in Struct and the field is converted to Json with inline mode .After modification, we successfully converted it.
    ```
        for i := 0; i < dt.NumField(); i++ {
            fieldInfo := fieldInfoFromField(dt, i)
            fv := dv.Field(i)
            // if we cannot found fieldInfo.name of Anonymous field in json,the json is inline mode for this Anonymous field
            _, ok := sv.Interface().(map[string]interface{})[fieldInfo.name]
            if len(fieldInfo.name) == 0 || dt.Field(i).Anonymous && !ok {
                // if len(fieldInfo.name) == 0 {
                // This field is inlined.
                if err := fromUnstructured(sv, fv); err != nil {
                    return err
                }
            } else {
                ...
            }
        }
    ```

**Comment by leileiwan** [comment]
sig/api-machinery

**Comment by liggitt** [comment]
is the `,inline` json tag not required to get inline behavior?

**Comment by leileiwan** [comment]
> is the `,inline` json tag not required to get inline behavior?

Yes. But when there are no json information for StructB, the SturctB will not convert success. Beacuse len(fieldInfo.name) == 0 will not be satisfied (The fieldInfo.name is string structB),but json has no filed structB.
```
map[A:A B:B apiVersion:v1 kind:MyStruct]
```

**Comment by liggitt** [comment]
the intent is for `ToUnstructured(obj)` to match the result of:
```go
jsonData, _ := json.Marshal(obj)
v := map[string]interface{}{}
json.Unmarshal(jsonData, &v)
```

and FromUnstructured(map, obj) to match the result of:
```go
jsonData, _ := json.Marshal(map)
json.Unmarshal(jsonData, obj)
```

These were designed to work with well-behaved Kubernetes go API type definitions, which are expected to provide json tags for all fields. If you specify the json tags explicitly, does this work as expected?

**Comment by leileiwan** [comment]
There were no problem when I specified the json tag. But my project depends on other project’s struct which has no json tag. And the when I run the test case in PR ,it could not pass it without any warnning information, it may cause some potention problem.

**Comment by fedebongio** [comment]
/assign @caesarxuchao 
(assigning to Chao since the PR is assigned to him already)

**Comment by leileiwan** [comment]
> the intent is for `ToUnstructured(obj)` to match the result of:
> 
> ```go
> jsonData, _ := json.Marshal(obj)
> v := map[string]interface{}{}
> json.Unmarshal(jsonData, &v)
> ```
> 
> and FromUnstructured(map, obj) to match the result of:
> 
> ```go
> jsonData, _ := json.Marshal(map)
> json.Unmarshal(jsonData, obj)
> ```
> 
> These were designed to work with well-behaved Kubernetes go API type definitions, which are expected to provide json tags for all fields. If you specify the json tags explicitly, does this work as expected?

Sorry, It's my code error,I should just use the function ToUnstructured and FromUnstructured. I will use ToUnstructured to instead of the function ConvertMyStructToUnstructured in PR  test case.
