### ISSUE TITLE
Azure cloud provider shouldn't put route table when it's already been configured

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#86300]
**What happened**:

Kubernetes shouldn't put route table when it's already been configured. Azure cloud provider should check whether the route has already been created before invoking `az.CreateOrUpdateRoute(route)`.

https://github.com/kubernetes/kubernetes/blob/e680ad7156f263a6d8129cc0117fda58602e50ad/staging/src/k8s.io/legacy-cloud-providers/azure/azure_routes.go#L128-L131

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cloud-provider
/priority important-soon

**Comment by norshtein** [comment]
Why this is a bug? A PUT operation should be idempotent and multiple calls should get the same result?

**Comment by feiskyer** [comment]
@norshtein Right. But cloud provider shouldn't make unnecessary API calls, in case.

**Comment by norshtein** [comment]
To check whether it is configured, we need a GET call, so we're going to replace PUT call with GET call in this case?

**Comment by feiskyer** [comment]
it's not a replace, we need to LIST routes and check whether it has already been there, then PUT if it's not.

**Comment by norshtein** [comment]
I got your point. But if we directly send a PUT request, seems route RP will also do this comparation? Is there any issue making us have to do the comparation by ourselves instead of sending PUT request to route RP?

**Comment by feiskyer** [comment]
It would help to reduce the chances of ARM PUT throttling.

**Comment by zqingqing1** [comment]
I'd like to work on this
