### ISSUE TITLE
"OCI runtime start failed" runc race causes many CI failures/flakes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#86312]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce
ci-cos-containerd-e2e-ubuntu-gce
ci-kubernetes-e2e-kops-gce

Changes needed to get the fix into official containerd releases:
- [x] runc race condition fixed - https://github.com/opencontainers/runc/pull/2185
- [x] runc release - https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc10
- [x] cri bump of runc - https://github.com/containerd/cri/pull/1383
- [x] containerd bump of runc/cri - https://github.com/containerd/containerd/pull/3973
- [x] containerd 1.2.x release - https://github.com/containerd/containerd/pull/3984
- [x] containerd 1.3.x release - https://github.com/containerd/containerd/releases/tag/v1.3.3

As I understand it, this is what we need to get the fix into our CI environments:

For kind:
- [x] kind containerd build with updated runc - https://github.com/kind-ci/containerd-nightlies/pull/11
- [x] kind containerd-nightly release include patch - https://github.com/kind-ci/containerd-nightlies/pull/11
- [x] kind containerd-nightly release - https://github.com/kind-ci/containerd-nightlies/releases/tag/containerd-1.3.2-24-gda15d825
- [x] kind pick up new containerd release - https://github.com/kubernetes-sigs/kind/pull/1285

For GCE / kube-up:
- [x] https://github.com/moby/moby/pull/36097
- [x] cri bump of runc - https://github.com/containerd/cri/pull/1383
- [x] containerd bump of runc/cri - https://github.com/containerd/containerd/pull/3973
- [x] containerd 1.2.x release - https://github.com/containerd/containerd/pull/3984
- [x] containerd 1.3.x release - https://github.com/containerd/containerd/releases/tag/v1.3.3
- [ ] COS image update with new runc version - https://github.com/kubernetes/kubernetes/pull/88102

**Which test(s) are flaking**:
* [sig-storage] ConfigMap should be consumable from pods in volume as non-root with FSGroup [LinuxOnly] [NodeFeature:FSGroup]
* [sig-storage] Projected downwardAPI should provide podname as non-root with fsgroup [LinuxOnly] [NodeFeature:FSGroup]
* [sig-storage] Projected configMap should be consumable from pods in volume with mappings as non-root [NodeConformance] [Conformance]
* [sig-storage] EmptyDir volumes should support (root,0644,tmpfs) [LinuxOnly] [NodeConformance] [Conformance]
* [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support file as subpath [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly file specified in the volumeMount [LinuxOnly] 

**Testgrid link**:

**Reason for failure**:

runc race condition fixed in opencontainers/runc#2185

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=OCI%20runtime%20start%20failed

Test containers appear to be exiting with a CRI error?

/sig node
for CRI expertise

/sig storage
for test ownership

**Comment by liggitt** [comment]
From @msau42 in https://github.com/kubernetes/kubernetes/issues/84514#issuecomment-548008149

> For the projected volumes test, it looks like the test container returned with an error code:
> ```
> Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:OCI runtime start failed: container process is already dead: unknown
> ```
> But from the output, it seems ok:
> ```
> I1030 08:41:12.500] Oct 30 08:41:06.866: INFO: Output of node "bootstrap-e2e-minion-group-t61q" pod "pod-projected-secrets-6b2d585f-5051-4c3c-b2f8-98b8ea6f4cd2" container "projected-secret-volume-test": mode of file "/etc/projected-secret-volume/data-1": -r--------
> I1030 08:41:12.500] content of file "/etc/projected-secret-volume/data-1": value-1
> ```
> which should match the test expectations.  The test is configured with [mode 0400](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/projected_secret.go#L53)
> 
> Need to investigate this mounttest program further to figure out how it can fail after printing this.
> 
>

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1206958853602676741

**Comment by liggitt** [comment]
@kubernetes/sig-node-bugs @kubernetes/sig-storage-bugs

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/1206995563719954438/

**Comment by liggitt** [comment]
I think we have a general failure to start containers reliably. Almost every instance of the "In-tree volume" test flakes referenced from https://github.com/kubernetes/kubernetes/issues/86318 contained the pod status error of "OCI runtime start failed: container process is already dead: unknown"

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206995563719954438
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206995563719954438
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206989684341739522
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206963761311649796
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206944256451678211
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206933812953485313
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1206930288853127169

**Comment by liggitt** [comment]
seen in [k8s.io] Docker Containers should be able to override the image's default arguments (docker cmd) [NodeConformance] [Conformance] in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-single-flake-attempt/1206650027410198530

**Comment by liggitt** [comment]
also seen in containerd CI runs - https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1206962125457592325

**Comment by Random-Liu** [comment]
> container process is already dead: unknown

This seems to be a race condition in runc. It only happened once in 2 weeks for containerd.

In the runc code, when starting a container, `exec` will be called:
* https://github.com/opencontainers/runc/blob/master/start.go#L34
* https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L263
* https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L266

There are 2 channels being waited:
* `awaitProcessExit`: https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L298:6
* `awaitFifoOpen`: https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L317

* `awaitProcessExit` returns and throws out `container process is already dead` error, when 1) exec fifo is opened; 2) after 100 milliseconds and the init process is zombie or gone.
* `awaitFifoOpen` returns when the exec fifo is opened.

If I understand the code correctly, I can see a potential race condition:
1) `awaitFifoOpen` opens the fifo, but haven't informed `awaitProcessExit` with the channel yet;
2) container process starts running and finishes;
3) `awaitProcessExit` checks process after 100 milliseconds, and found the process is already gone;
4) The `container process is already dead` error is returned unexpectedly.

At least for the containerd failure, the test is a short running container. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/downwardapi_volume.go#L361

**Comment by liggitt** [comment]
thanks for digging.

> @liggitt This seems to be a race condition in runc. It only happened once in 2 weeks for containerd.

at first glance, it looks more frequent than that in some of the jobs - https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=OCI%20runtime%20start%20failed&job=containerd

ci-cos-containerd-e2e-ubuntu-gce - Failed in 5% (18/348) of builds:
- 1206955833544413185 12/17/2019, 10:14:46 AM
- 1206294929978953731 12/15/2019, 2:28:43 PM
- 1206003258967986176 12/14/2019, 7:09:32 PM
- 1205895803273482240 12/14/2019, 12:02:33 PM
- 1205788345360191488 12/14/2019, 4:55:35 AM
- 1205573553580150787 12/13/2019, 2:42:28 PM
- 1205542851039989763 12/13/2019, 12:40:08 PM
- 1205435476689817605 12/13/2019, 5:33:22 AM
- 1205297314126630917 12/12/2019, 8:24:21 PM
- 1204299708156088322 12/10/2019, 2:20:14 AM
- 1203992908559028229 12/9/2019, 6:01:32 AM
- 1203731936137187332 12/8/2019, 12:44:23 PM
- 1203486221536333824 12/7/2019, 8:27:44 PM
- 1203133182187147264 12/6/2019, 9:04:54 PM
- 1203025840279916544 12/6/2019, 1:58:22 PM
- 1202642098390568960 12/5/2019, 12:33:37 PM
- 1202150964170067973 12/4/2019, 4:01:54 AM
- 1201843928219783168 12/3/2019, 7:42:04 AM

**Comment by liggitt** [comment]
opened https://github.com/opencontainers/runc/issues/2183 in runc, am working on a low level reproducer/fix

**Comment by liggitt** [comment]
cc @mrunalp

**Comment by liggitt** [comment]
fix in progress at https://github.com/opencontainers/runc/pull/2185

**Comment by liggitt** [comment]
@kubernetes/sig-node-bugs the runc race condition fix has been merged at https://github.com/opencontainers/runc/pull/2185

I think the next steps are getting a runc release cut and propagating that fix into the container runtimes we use in Kube CI (docker and containerd). Who on the sig-node side would be the right people to drive those?

**Comment by yujuhong** [comment]
For the GCE tests, we'd need a new COS image once the new runc release is available.
@cheftako

**Comment by liggitt** [comment]
once a runc release is available, we'll need to update our e2e images

/assign @cheftako 
for COS image updates

/assign @BenTheElder 
for kind updates

**Comment by BenTheElder** [comment]
as soon as there's a runc release we'll roll it out in kind (preferably if containerd 1.3.X can pick it up officially... we already have infra building that), tempted to go ahead and grab a runc binary at some commit ...

**Comment by liggitt** [comment]
looks like runc rc10 is blocked on a fix for https://github.com/opencontainers/runc/issues/2197 (which should have a PR open tomorrow per https://github.com/opencontainers/runc/issues/2197#issuecomment-573830382)

**Comment by dims** [comment]
We will have to request containerd folks bump opencontainers/runc here - https://github.com/containerd/containerd/blame/master/vendor.conf#L32-L36 this is a nasty bug, hope we get a runc release quickly

(cc @estesp @crosbymichael)

**Comment by dims** [comment]
and then request docker folks after that - https://github.com/moby/moby/blob/master/vendor.conf#L83-L86

**Comment by phil9909** [comment]
Also affects `[sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path` (I guess)
 https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85846/pull-kubernetes-e2e-gce/1219654116133834752/

**Comment by BenTheElder** [comment]
Still waiting for https://github.com/opencontainers/runc/pull/2207#issuecomment-576755368 but there's recent activity :crossed_fingers: 

On the KIND side:
When this goes in and there is a runc release, next up after containerd bumping to it we'll (I'll) ensure kind picks up the new containerd release and builds new images with it.
Right now we consume the 1.3.X / release-1.3 branch, but we are good to upgrade to HEAD if necessary.

**Comment by BenTheElder** [comment]
On the GCE side:
I'm still not sure who handles COS etc. currently, but someone from node on our end (=Google) will need to get this ported into COS and into our CI.. I'm going to poke @cheftako as a starting point

**Comment by liggitt** [comment]
runc rc10 is cut. containerd and docker are up next?

**Comment by BenTheElder** [comment]
https://github.com/containerd/containerd/pull/3973

**Comment by liggitt** [comment]
As I understand it, this is what we need to get the fix into our CI environments:

Containerd stream (for kind):
- [ ] https://github.com/containerd/cri/pull/1383
- [ ] https://github.com/containerd/containerd/pull/3973
- [ ] containerd release
- [ ] k8s CI pickup new containerd release

Docker stream (for GCE / kube-up):
- [ ] https://github.com/containerd/cri/pull/1383
- [ ] https://github.com/containerd/containerd/pull/3973
- [ ] https://github.com/moby/moby/pull/36097
- [ ] maybe docker/docker-ce changes?
   * https://github.com/docker/docker-ce/blob/master/components/engine/vendor.conf#L78-L83
   * https://github.com/docker/docker-ce/blob/master/components/engine/vendor.conf#L119-L120
- [ ] docker/docker-ce release
- [ ] COS image update with new docker version

**Comment by BenTheElder** [comment]
KIND won't actually need a containerd release, just a build of the commit with updated runc.

Additionally though: per discussion we've noted that the runc bump is mostly information to downstream packaging of containerd, there are no code changes. So we're tentatively forging ahead with bumping runc in our "nightly" build ahead of that landing in containerd.

**Comment by liggitt** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=already%20dead&job=e2e-gce%24 looks clean after https://github.com/kubernetes/kubernetes/pull/88102 merged. I verified the only flakes occurring after that was merged were on past branches still using the older COS versions.

Next week, we can update the non-test kube-up config file to use the fixed version of COS as well if signal still looks good.
