### ISSUE TITLE
resource extend

### ISSUE THREAD

**Issue by HistoryGift** [kubernetes/kubernetes#86332]
when any nodes in my cluster has 2 CPU , but my requirement needs 4 CPU;
I set 4 CPU in my yaml doc 
resource:
   limits: 
      cpu: '4'
but pod is always in pending ;
the version of my k8s  is 1.16
are there some special options to meet my requirement ?

**Comment by liggitt** [comment]
To schedule a pod successfully, you need nodes in your cluster with sufficient resources. When a pod requests more resources than can be allocated, it is expected it will remain in pending state.

/close
