### ISSUE TITLE
[Flaky test] staticcheck reports used functions as unused

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#86340]
**Which jobs are flaking**:
pull-kubernetes-verify

**Which test(s) are flaking**:
staticcheck

Sometimes reports methods as unused when they are, in fact, used

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-verify&include-filter-by-regex=staticcheck

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-verify/1206827610810617858

/cc @tallclair

**Comment by dominikh** [comment]
If this is sporadic then it's probably https://github.com/dominikh/go-tools/issues/642 -- there's a fix for that on master (https://github.com/dominikh/go-tools/commit/a9480a3ec3bcedcf32d00a67bb464c058ba03281) but it's not part of a release yet.
