### ISSUE TITLE
Field selectors for job status: active, failed, succeeded

### ISSUE THREAD

**Issue by tavin** [kubernetes/kubernetes#86352]
**What would you like to be added**:

Field selectors for job status: `active`, `failed`, `succeeded`

**Why is this needed**:

Currently the only supported status selector is `successful` (which appears to match the `succeeded` field). My use case is to delete jobs that have stopped running and failed. I can obtain a list using `status.successful=0` but I still have to walk through the returned status objects and check the `active` and/or `failed` fields, then pass the resourceVersion or uid to the delete method.

**Comment by tavin** [comment]
@kubernetes/sig-architecture-feature-requests

**Comment by bverschueren** [comment]
@tavin: can you verify if #87863 covers your needs ?

**Comment by tavin** [comment]
> @tavin: can you verify if #87863 covers your needs ?

@bverschueren it looks like exactly what I was asking for, thanks

**Comment by tavin** [comment]
/remove-lifecycle stale

PR open a while now, can close after it is merged

**Comment by draeron** [comment]
anti stale comment

**Comment by tavin** [comment]
Please note a [PR](https://github.com/kubernetes/kubernetes/pull/87863) was opened more than 2.5 years ago solving this issue, since closed by Mr. Fejta Bot. What was the problem with getting the PR approved?
