### ISSUE TITLE
[Flaky test] [sig-apps] DisruptionController should block an eviction until the PDB is updated to allow it

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#86358]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce

**Which test(s) are flaking**:
`[Flaky test] [sig-apps] DisruptionController should block an eviction until the PDB is updated to allow it`

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=DisruptionController.*block

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86348/pull-kubernetes-e2e-gce/1206946772652396546/

/sig apps

**Comment by liggitt** [comment]
@kubernetes/sig-scheduling-misc @kubernetes/sig-apps-bugs

**Comment by liggitt** [comment]
cc @mortent

**Comment by liggitt** [comment]
/priority critical-urgent
top 10 flake according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by mortent** [comment]
Seems like #87205 fixed this issue. According to https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=DisruptionController.*block, this test hasn't seen a single failure in the last two weeks.

**Comment by droslean** [comment]
It seems that the issue have been fixed. Closing...
/close
