### ISSUE TITLE
Add More Metrics for cacher/watcher

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#86356]
**What happened**:

When API Server is in heavy load or even in extremely bad situation, clients can not set up their watch request normally. 

However, our API Server's metrics does not tell us this status, as watch response code is always 200, even watch request caused error "resource version too old" or API Server can not flush data to clients(force close watcher).

**What you expected to happen**:

Add Metrics to indicate that API Server may can not serve watch request normally. Especially for the following two situation:

1. Force to close watcher:

https://github.com/kubernetes/kubernetes/blob/623b6978866b5d3790d17ff13601ef9e7e4f4bf0/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L1216-L1222

2. Resource version too old:

https://github.com/kubernetes/kubernetes/blob/623b6978866b5d3790d17ff13601ef9e7e4f4bf0/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L470-L473

**How to reproduce it (as minimally and precisely as possible)**:

Make API Server in heavy load and try to set up watch request.

**Anything else we need to know?**:

None

**Environment**:

None

**Comment by answer1991** [comment]
/priority important-soon
/good-first-issue

cc @wojtek-t

**Comment by notpad** [comment]
@answer1991 `good first issue` is a label denotes the issue is suite for a new contributor, but I think this issue may need some background knowledge about the api server.

/unassign
