### ISSUE TITLE
[Flaky test] [sig-cli] Kubectl Port forwarding With a server listening on localhost that expects a client request should support a client that connects, sends DATA, and disconnects

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#86355]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce

**Which test(s) are flaking**:
* `[sig-cli] Kubectl Port forwarding With a server listening on localhost that expects a client request should support a client that connects, sends DATA, and disconnects`

```
[sig-cli] Kubectl Port forwarding With a server listening on localhost that expects a client request should support a client that connects, sends DATA, and disconnects
test/e2e/kubectl/portforward.go:469 Dec 17 12:09:21.619: Expected "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" from server, got "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" test/e2e/kubectl/portforward.go:333
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84735/pull-kubernetes-e2e-gce/1206903865241243649/

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=Kubectl%20Port

/sig cli
@kubernetes/sig-cli-misc

**Comment by droslean** [comment]
@liggitt This test seems to stop flake. Can you check if we can close this issue?

**Comment by liggitt** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=sends%20DATA still looks flaky to me

**Comment by droslean** [comment]
@soltysh Can you take a look?

**Comment by hasheddan** [comment]
@soltysh have you had a chance to look into this?

**Comment by brianpursley** [comment]
Possibly related to https://github.com/kubernetes/kubernetes/issues/86678

**Comment by aojea** [comment]
Let's see if removing `socat` makes it less flaky 
https://github.com/containerd/cri/pull/1470
