### ISSUE TITLE
NodeStage is not called after NodeUnstage timeout

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#86360]
Kubelet does not call NodeStage after NodeUnstage timed out. When a pod that uses the volume that's being unstaged is created, kubelet calls just NodePublish.

After the NodeUnstage timeout, kubelet cannot be sure if the storage backed is progressing with unstaging the volume and it should make sure that the volume is staged by calling NodeStage before calling NodePublish.

It's reproducible with #82492 and only with a volume that uses mount to stage a volume.

/sig storage

**Comment by bertinatto** [comment]
I reproduced this and this is what I found out:

1. Pod with one volume is created.

2. Pod is deleted. In the process, kubelet calls _NodeUnstageVolume_ and gets a timeout error back.

`
E0206 12:41:15.188300   22583 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/io.kubernetes.storage.mock^1\"" failed. No retries permitted until 2020-02-06 12:41:15.688279561 +0000 UTC m=+334.493070049 (durationBeforeRetry 500ms). Error: "UnmountDevice failed for volume \"mypv\" (UniqueName: \"kubernetes.io/csi/io.kubernetes.storage.mock^1\") on node \"ip-172-18-6-232.ec2.internal\" : kubernetes.io/csi: attacher.UnmountDevice failed: rpc error: code = DeadlineExceeded desc = Mock timeout"
`

3. Kubelet keeps re-trying, but _NodeUnstageVolume_ always return a time out error (this is a modified mock driver version):

`
E0206 12:51:31.204183   22583 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/io.kubernetes.storage.mock^1\"" failed. No retries permitted until 2020-02-06 12:53:33.204160417 +0000 UTC m=+1072.008950910 (durationBeforeRetry 2m2s). Error: "UnmountDevice failed for volume \"mypv\" (UniqueName: \"kubernetes.io/csi/io.kubernetes.storage.mock^1\") on node \"ip-172-18-6-232.ec2.internal\" : kubernetes.io/csi: attacher.UnmountDevice failed: rpc error: code = DeadlineExceeded desc = Mock timeout"
`

4. The volume is still mounted in the node:

```
# mount
xxx on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/mypv/globalmount type tmpfs (rw,relatime,seclabel)
xxx on /var/lib/kubelet/pods/bfa1f19e-3719-4eee-aa84-0ffb8fd7da41/volumes/kubernetes.io~csi/mypv/mount type tmpfs (rw,relatime,seclabel)
tmpfs on /var/lib/kubelet/pods/bfa1f19e-3719-4eee-aa84-0ffb8fd7da41/volumes/kubernetes.io~secret/default-token-cjn2g type tmpfs (rw,relatime,seclabel)
```

5. Now, the pod is re-created and the Volume Manager will call the CSI plugin's _MountDevice_ method (this is the CSI in-tree plugin).

6. However, kubelet sees that the given mount path is already mounted on the node:

```
I0206 12:53:30.626308   22583 csi_attacher.go:224] kubernetes.io9/csi: attacher.MountDevice(, /var/lib/kubelet/plugins/kubernetes.io/csi/pv/mypv/globalmount)
I0206 12:53:30.626644   22583 csi_attacher.go:237] kubernetes.io/csi: attacher.MountDevice skipping mount, dir already mounted [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/mypv/globalmount]
```

7. _MountDevice_ (i.e., _NodeStageVolume_) is then skipped

https://github.com/kubernetes/kubernetes/blob/a71586fac6007382db1c1dbe1ea192d4b21a0dde/pkg/volume/csi/csi_attacher.go#L230-L239

**Comment by bertinatto** [comment]
This behaviour is correct because we can't call _NodeStageVolume_ if the volume is already mounted on the node.

**Comment by gnufied** [comment]
So basically if a `NodeUnstage` timesout but it leaves a mounted volume then `NodeStage` is never called but if `NodeUnstage` timesout but does not necessarily uses mount points(or may be they got cleaned up) then `NodeStage` *does* get called. 

One of the reasons behind opening this issue was to explore if it is safe to call `NodeStage` if volume is already mounted and this would result in somewhat consistent behaviour across drivers. cc @msau42 @jsafrane

**Comment by msau42** [comment]
I think the check for if a volume is mounted is not correct. NodePublish is supposed to be idempotent so it should be safe to call multiple times (although there are probably many driver bugs around this). See also https://github.com/kubernetes/kubernetes/issues/86784

**Comment by bertinatto** [comment]
> I think the check for if a volume is mounted is not correct. NodePublish is supposed to be idempotent so it should be safe to call multiple times (although there are probably many driver bugs around this). See also #86784

The linked issue is about *NodePublish* (this one is about *NodeStage*), but indeed the same explanation should apply to *NodeStage*.
