### ISSUE TITLE
I build fluentd image but not version 1.7.4

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#86372]
I build fluentd image refercing from https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile, but found that fluentd version is not 1.7.4 like this:
Installing fluentd (1.6.3)

when I config gem 'fluentd', '~>1.7.4' in Gemfile, the build of fluentd image output error:
```
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies tzinfo (~> 1.1) and tzinfo (~> 2.0)
  Activated tzinfo-2.0.0
  which does not match conflicting dependency (~> 1.1)

  Conflicting dependency chains:
    fluentd (~> 1.7.4), 1.7.4 activated, depends on
    tzinfo (~> 2.0), 2.0.0 activated

  versus:
    activesupport (~> 6.0.1), 6.0.1 activated, depends on
    tzinfo (~> 1.1)
```
/kind bug

**Comment by neolit123** [comment]
hi, the /addons folder is mostly unmaintained at this point.
you can go to the fluentd maintainers and ask them how to build.

/sig instrumentation
or alternatively go to the #sig-insturmentation slack of k8s and ask there.
