### ISSUE TITLE
kubectl rollout status should be able to show new pod logs

### ISSUE THREAD

**Issue by lukeschlather** [kubernetes/kubernetes#86388]
**What would you like to be added**:
kubectl rollout status should provide a mechanism to view logs for all new pods until the pods are marked as healthy (or completed for init containers.)

**Why is this needed**:
When debugging deployments in CI, it's extremely frustrating to figure out what's going wrong. A somewhat related issue is #28746 , which discusses how kubectl logs frequently fails when run during or shortly after a deployment. Giving kubectl rollout status the ability to show all logs directly relevant to the new deployment would make this less of an issue.

Currently, our CI approach is just to provide a link to our centralized logging, and debugging deployments means sifting through our central logs looking for the correct container logs that correspond with the deployment time.

**Comment by lukeschlather** [comment]
@kubernetes/kubectl

**Comment by minzhang28** [comment]
@lukeschlather I am interested in learning how to contribute to k8s community, although I don't know exactly what to do for this ticket, I'd like to try this if possible.
