### ISSUE TITLE
add deltaType to the parameters for workqueue CRUD

### ISSUE THREAD

**Issue by zbw0046** [kubernetes/kubernetes#86381]
**What would you like to be added**: 
Add deltaType to the parameters for workqueue CRUD

**Why is this needed**:
We usually use workqueue to collect events from DeltaFIFO and send the key of them to controller for processing. However, when controller pop keys from workqueue it does not know which type of event(add/update/delete) is associated to this key.

One choice is to wrap key and deltaType in the parameter of `workqueue.Add(interface{})`. But, because of the implementation of `dirty` and `processing` set in workqueue, under this choice we will lose the correctness guarantee of the workqueue when requeue happens. In this case events with same key but different delta type are not seen as the same in dirty and processing set, so operations sequence such as `update then delete` will be put in `dirty` and `processing` as two different items, and then dirty/processing will not be able to protect the workqueue from incorrectness.

**Comment by zbw0046** [comment]
/sig cli

@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
The key in the work queue just indicates which object should be synchronized. It is not intended to convey the type of the event. Typical implementations dequeue the key and look up the object from a local store. If the object is present, they handle the object that is present. If the object is absent, they handle any cleanup required on a delete.

**Comment by liggitt** [comment]
If you want to handle raw event types, I'm not sure workqueue is the best fit for you… it almost seems like to want to consume a deltafifo's output directly

**Comment by mikedanese** [comment]
This is the first point of Kubernetes control logic principles. 

> Functionality must be level-based, meaning the system must operate correctly given the desired state and the current/observed state, regardless of how many intermediate state updates may have been missed. Edge-triggered behavior must be just an optimization.

https://github.com/kubernetes/community/blob/3f8bf88a06a114b3984417d6867bb16506c9c71e/contributors/design-proposals/architecture/principles.md#control-logic

The API and usage of workqueue is intended to lead users to write controllers that align with this principal.

**Comment by zbw0046** [comment]
It seems like that i misunderstand the usage of the `workqueue`. thanks.
