### ISSUE TITLE
Pod pending waiting for pvc due to fsck -a /dev/rbd error

### ISSUE THREAD

**Issue by zhxqgithub** [kubernetes/kubernetes#86406]
**What happened**:
The pod always pending because it waiting for mount pvc,however, error occur when fsck -a /dev/rbd.

![image](https://user-images.githubusercontent.com/8119309/71139823-4b089780-224a-11ea-9262-42244d7d20ed.png)

**What you expected to happen**:
in  pkg/util/mount/mount_linux.go#433,we can see fsck use -a parameter to check and repair disk. however, fsck -a can not work well when fix disk, fsck -y can resolve problem.can we use -y parameter in the code ?
```
if !readOnly {
		// Run fsck on the disk to fix repairable issues, only do this for volumes requested as rw.
		klog.V(4).Infof("Checking for issues with fsck on disk: %s", source)
		args := []string{"-a", source}
		out, err := mounter.Exec.Run("fsck", args...)
		if err != nil {
			ee, isExitError := err.(utilexec.ExitError)
			switch {
			case err == utilexec.ErrExecutableNotFound:
				klog.Warningf("'fsck' not found on system; continuing mount without running 'fsck'.")
			case isExitError && ee.ExitStatus() == fsckErrorsCorrected:
				klog.Infof("Device %s has errors which were corrected by fsck.", source)
			case isExitError && ee.ExitStatus() == fsckErrorsUncorrected:
				return fmt.Errorf("'fsck' found errors on device %s but could not correct them: %s.", source, string(out))
			case isExitError && ee.ExitStatus() > fsckErrorsUncorrected:
				klog.Infof("`fsck` error %s", string(out))
			}
		}
	}

```

it can be fixed  by 'fsck -a' command or use 'fsck -y'
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.9
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
centos
- Kernel (e.g. `uname -a`):
4.9.2
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vsxen** [comment]
accessmode ReadonltMany?
use fsck.ext4  to fix file system?

**Comment by zhxqgithub** [comment]
@vsxen yes ,we use ReadOnlyMany accessMode. 'fsck -y ' can fix file system by manual  . however , hope the code can auto repair file system.

**Comment by lyyao09** [comment]
Same issue for me. @zhxqgithub, Is there any solution?

After the host was powered off abnormally, the pod using the iscsi device failed to start because the file system was damaged. We can use `fsck -y` command to repair successful.  Is it feasible that kubelet use `fsck -y` to repair instead of `fsck -a`?
