### ISSUE TITLE
kube-apiserver container log file seems to have no size limit

### ISSUE THREAD

**Issue by brentpearson** [kubernetes/kubernetes#86403]
I noticed this file 
/var/lib/docker/containers/aa0faf7c7e4cfe30cb33768a1f3462a225267fbdee00c70b23c7d47903bd38d2/aa0faf7c7e4cfe30cb33768a1f3462a225267fbdee00c70b23c7d47903bd38d2-json.log
is 2.3 GB. 
It's the kubeapi-server log.

How can I limit this size? From what I've read, the default log size is only 10 MB, but that doesn't seem to be getting enforced here.

**Comment by mikedanese** [comment]
From the path, I'm inferring that you are using the docker json-file driver. You have a few options:

https://docs.docker.com/config/containers/logging/json-file/#options
https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver
https://github.com/kubernetes/kubernetes/blob/8cd87842894464bdf7bc25378fc4824ba1cb37bb/cmd/kubelet/app/options/options.go#L536-L537

**Comment by brentpearson** [comment]
I keep seeing these things about configuring Docker logging, but I haven't done anything to change Docker from it's default (version 19.03.1, build 74b1e89) state, other than modifying 
/usr/lib/systemd/system/docker.service
to add "native.cgroupdriver=systemd" to the end of the "ExecStart" line.

There is no /etc/docker/daemon.json file. Should I just create it with
`{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3" 
  }
}`
and then restart the Docker service and it'll pick up these settings?

I'm using K8s 1.15.3 on CentOS 7.5, btw.

**Comment by mikedanese** [comment]
Yes, I would expect that to work.

**Comment by brentpearson** [comment]
Nice, looks like it worked.
