### ISSUE TITLE
All CI kubemark tests are failing

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#86423]
See https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100

E.g. failure, the error seems to be:
```
W1219 07:34:39.336] error: error parsing /go/src/k8s.io/kubernetes/kubernetes/test/kubemark/resources/addons/heapster.json: json: line 14: invalid character ':' after object key:value pair

```

/assign @jkaniuk

**Comment by jkaniuk** [comment]
Problem started right after #85879 was merged.

Log:
```
I1218 16:59:25.442] Waiting for all hollow-nodes to become Running...
I1218 16:59:25.443] Timeout waiting for all hollow-nodes to become Running. 
I1218 16:59:25.784] Found only 1 ready hollow-nodes while waiting for 100.
I1218 16:59:26.394] 100 hollow-nodes are reported as 'Running'
I1218 16:59:26.398] 0 hollow-nodes are reported as NOT 'Running'
```

Interestingly - same happened in presubmit, but was not reported as an error:
pull-kubernetes-kubemark-e2e-gce-big Job succeeded. [Details](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85879/pull-kubernetes-kubemark-e2e-gce-big/1207282581612007424/)
I will open separate bug for that.
