### ISSUE TITLE
[Failing Test] node-containerd-throughput failing

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#86429]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-node-containerd-throughput

**Which test(s) are failing**:
Setting up the cluster

**Since when has it been failing**:
long time

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-node#node-containerd-throughput

**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-node-containerd-throughput/1207611460683829266
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-node-containerd-throughput/1207611460683829266/artifacts/e2e-9bf3bf1745-5888a-master/kube-master-installation.log
`Dec 19 10:45:11.211155 e2e-9bf3bf1745-5888a-master configure.sh[852]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Anything else we need to know**:

/sig node
/sig scalability

**Comment by jkaniuk** [comment]
Partial fix: https://github.com/kubernetes/test-infra/pull/15713

Test runs now, but fail:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-node-containerd-throughput/1211925160513245187
```
testing/node-throughput/config.yaml 
[measurement call WaitForControlledPodsRunning - WaitForRunningLatencyRCs error:
100 objects timed out: ReplicationControllers: 
test-55rfp1-6/latency-pod-rc-0, test-55rfp1-26/latency-pod-rc-0, ...]

```

**Comment by jkaniuk** [comment]
controller-manager.log
`E1231 08:28:58.430760       1 replica_set.go:534] sync "test-55rfp1-4/latency-pod-rc-0" failed with pods "latency-pod-rc-0-" is forbidden: unable to validate against any pod security policy: []`

**Comment by jkaniuk** [comment]
different set of addmission controllers

additional test flag:
` - --env=ENABLE_POD_SECURITY_POLICY=true`

failing test:
> I1231 08:26:52.498304       1 flags.go:33] FLAG: --enable-admission-plugins="[NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,PodPreset,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,Priority,StorageObjectInUseProtection,PersistentVolumeClaimResize,RuntimeClass,**PodSecurityPolicy**,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota]"

passing node-throughput test:
> I1231 09:15:39.137989       1 flags.go:33] FLAG: --enable-admission-plugins="[NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,PodPreset,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,Priority,StorageObjectInUseProtection,PersistentVolumeClaimResize,RuntimeClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota]"

**Comment by jkaniuk** [comment]
Original (not throughput) test have similar problems:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-containerd/1182316556764319745/

`E1010 15:36:28.251929       1 stateful_set.go:393] Error syncing StatefulSet provisioning-7675/csi-hostpath-provisioner, requeuing: pods "csi-hostpath-provisioner-0" is forbidden: unable to validate against any pod security policy: []`

**Comment by wojtek-t** [comment]
Let's remove the enable pod security policy then.

Though, I think that's only part of the problem - replication-controller is getting 403 when creating pods. And my hunch is that it's something different. But we may try one by one.

**Comment by jkaniuk** [comment]
Example passing test with pod security enabled: ci-cri-containerd-e2e-gci-gce
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml#L553
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce/1211943279172521984/

additional presets:
```
    preset-e2e-containerd: "true"
    preset-e2e-containerd-image-load: "true"
```

mainly:
`  - name: KUBE_MASTER_EXTRA_METADATA
    value: user-data=/workspace/github.com/containerd/cri/test/e2e/master.yaml,containerd-configure-sh=/workspace/github.com/containerd/cri/cluster/gce/configure.sh,containerd-env=/workspace/test-infra/jobs/e2e_node/containerd/cri-master/env`
`  - name: KUBE_NODE_EXTRA_METADATA
    value: user-data=/workspace/github.com/containerd/cri/test/e2e/node.yaml,containerd-configure-sh=/workspace/github.com/containerd/cri/cluster/gce/configure.sh,containerd-env=/workspace/test-infra/jobs/e2e_node/containerd/cri-master/env`

We could add those presets and see if that helps. WDYT?

**Comment by wojtek-t** [comment]
It was there before I removed it in the morning:
https://github.com/kubernetes/test-infra/pull/15714

It wasn't even starting back then...

**Comment by jkaniuk** [comment]
Right, just wanted to write the same.
OK, I'll try with removing security policy.

**Comment by wojtek-t** [comment]
Seems to work now:
https://testgrid.k8s.io/sig-scalability-node#node-containerd-throughput

Closing.
