### ISSUE TITLE
Presubmit failed but did not stop the merge

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#86426]
**What happened**:
One of presubmits failed in https://github.com/kubernetes/kubernetes/issues/85879 job, but PR was still merged, which caused all kubemark tests to start failing #86423

Last status:

**14 of 15 checks passed**
**tide** Not mergeable. Retesting: pull-kubernetes-kubemark-e2e-gce-big [Details](https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fkubernetes+author%3Agongguan+head%3Acri-kubemark)
**pull-kubernetes-kubemark-e2e-gce-big** Job succeeded. [Details](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85879/pull-kubernetes-kubemark-e2e-gce-big/1207282581612007424/)

**What you expected to happen**:
It should stop PR from merging.

**Environment**:
- Kubernetes version (use `kubectl version`): master

/sig testing

**Comment by liggitt** [comment]
resolved in https://github.com/kubernetes/test-infra/pull/15657?

**Comment by mm4tt** [comment]
Yes, we can close this one.
/close

**Comment by jkaniuk** [comment]
Similar situation but in different test:
https://github.com/kubernetes/kubernetes/pull/83654

> @feiskyer feiskyer added cherry-pick-approved and removed do-not-merge/cherry-pick-not-approved labels on 9 Oct
@k8s-ci-robot k8s-ci-robot merged commit a8b5220 into kubernetes:release-1.13 on 9 Oct
**9 of 11 checks passed**
**pull-kubernetes-e2e-gce-device-plugin-gpu** Job triggered. [Details](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83654/pull-kubernetes-e2e-gce-device-plugin-gpu/1181860254355296256/)
**tide** Not mergeable. Should not have do-not-merge/cherry-pick-not-approved label. Details

/reopen

**Comment by mm4tt** [comment]
The test from the PR you mentioned (`pull-kubernetes-e2e-gce-device-plugin-gpu`) is an [optional test](https://github.com/kubernetes/test-infra/blob/fc58d32f2d96b844079c1619135cb9e45b419f62/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gcp-gpu-presubmits.yaml#L19). If it fails it won't block merging a PR.

/close
