### ISSUE TITLE
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/prometheus is this link gone?

### ISSUE THREAD

**Issue by a1198457636** [kubernetes/kubernetes#86424]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/prometheus is this link gone?

**Comment by liggitt** [comment]
yes, see https://github.com/kubernetes/kubernetes/pull/83442#issuecomment-545367910

/close

**Comment by a1198457636** [comment]
> yes, see [#83442 (comment)](https://github.com/kubernetes/kubernetes/pull/83442#issuecomment-545367910)
> 
> /close
thanks
