### ISSUE TITLE
Set containerd oom score adj to -999

### ISSUE THREAD

**Issue by vitality411** [kubernetes/kubernetes#86420]
**What would you like to be added**:
In https://github.com/kubernetes/kubernetes/blob/661a08daf6acb99374401b68639d82e8b3509f04/pkg/kubelet/qos/policy.go#L34 Kubernetes sets OOM score adjustment for Docker but not for containerd. 
Set containerd oom score adj to -999.

**Why is this needed**:
In an OOM situation containerd migth be killed, stop docker and kubelet due to systemd dependency and won't auto-restart (restart is fixed in containerd/containerd#3297). 

```
Dec 13 13:29:35 k8s-dev-569d8766d4-2ms9z kernel: Out of memory: Kill process 994 (containerd) score 4 or sacrifice child
Dec 13 13:29:35 k8s-dev-569d8766d4-2ms9z kernel: Killed process 994 (containerd) total-vm:907784kB, anon-rss:18912kB, file-rss:0kB, shmem-rss:0kB
...
Dec 13 13:29:34 k8s-dev-569d8766d4-2ms9z systemd[1]: containerd.service: Main process exited, code=killed, status=9/KILL
Dec 13 13:29:34 k8s-dev-569d8766d4-2ms9z systemd[1]: containerd.service: Failed with result 'signal'.
...
Dec 13 13:29:34 k8s-dev-569d8766d4-2ms9z systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Dec 13 13:30:43 k8s-dev-569d8766d4-2ms9z systemd[1]: Stopping Docker Application Container Engine...
Dec 13 13:30:43 k8s-dev-569d8766d4-2ms9z systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 13 13:30:44 k8s-dev-569d8766d4-2ms9z systemd[1]: Stopped Docker Application Container Engine.
Dec 13 13:30:44 k8s-dev-569d8766d4-2ms9z systemd[1]: Closed Docker Socket for the API.
```

I opened containerd/containerd#3901 to address setting oom score adj to -999 for containerd per default.

IMHO Kubernetes should set oom score adj for containerd as required by Kubernetes just like it already does for Docker (also see #78314).

**Comment by mattjmcnaughton** [comment]
@neolit123 @dims curious for your thoughts here?

In my mind, its actually a bit of an anti-pattern that kubelet is setting the `OomAdj` for docker - and reflects the undesired coupling between Docker and the kubelet. So I'm a bit hesitant to extent this coupling to containerd.

In particular, using containerd as the container runtime requires the cluster administrator to be running containerd outside of the Kubelet (unlike docker, which the Kubelet will start and manage), so containerd has an additional hook for the cluster administrator to set OomAdj.

Curious to hear from others :)

**Comment by dims** [comment]
@mattjmcnaughton i'd leave this OomAdj for docker as-is, until we just drop dockershim totally. We should document somewhere though that folks using `remote` should ensure this in their environments to reduce surprise. 

example here's how did set this in image-builder : https://github.com/kubernetes-sigs/image-builder/pull/113/files#diff-8fce943161a0c079a7b0836e8e8a0b03R8

**Comment by neolit123** [comment]
^ +1
