### ISSUE TITLE
Move SelectorSpread priority logic to its Score plugin [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#86435]
/sig scheduling
/priority important-soon

SelectorSpread priority is now called from a plugin named DefaultPodTopologySpread. We need to move the logic to run in the plugin and remove SelectorSpread priority completely.

See #86399 as an example.

Part of #85822

This needs PostFilter Plugin to store the pod selector.

/assign @hprateek43

**Comment by hprateek43** [comment]
Started working on this. Will be opening a PR shortly.

**Comment by hprateek43** [comment]
I have started working on the code but the `selector_spreading.go` uses a lot of internal functions and types from the package `priorities` which we cannot access in `frameworks`. Am I missing something or we have a different strategy around that?

**Comment by ahg-g** [comment]
Which exact functions are you referring to? Anything that it depends on in the priorities package should ideally move with it. Are there functions that it depends on that is shared with other priorities?
