### ISSUE TITLE
Move resource-based priority functions to their Score plugins [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#86445]
/sig scheduling
/priority important-soon

See #86399 as an example.

There are two parts to this:

PR 1: move  RequestedToCapacityRatio plugins/requestedtocapacityratio/requested_to_capacity_ratio.go to plugins/noderesources/requested_to_capacity_ratio.go

PR 2: move resource_allocation.go to plugins/noderesources/ and move the logic in  Least/Most/Balanced and RequestedToCapacityRatio logic to their Score plugins. This needs to be done in a single PR.

Part of #85822

/assign @notpad

**Comment by ahg-g** [comment]
Hi @notpad , are you still working on this?

**Comment by notpad** [comment]
yes, I am working on this
