### ISSUE TITLE
CSI drivers need some way to get service account tokens

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#86448]
CSI drivers need some way to get service account tokens for the pods they are provisioning volumes for. These tokens may be used to authenticate to the Kubernetes API (e.g. the [Certificates API](https://github.com/jetstack/cert-manager-csi), or to authenticate to external services like [vault](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault)). Right now the state of the art is to give the CSI driver acccess to the filesystem. This is suboptimal because:
* It's not straightforward but security critical. Every driver has to re-implement this.
* It violates least privilege. CSI drivers should not be able to read secrets of pods that don't use them.
* The token is not guaranteed to be available (e.g. it won't be if automountServiceAccountToken=false).

The kubelet VolumeHost is wired up to fetch new-style service account tokens:

https://github.com/kubernetes/kubernetes/blob/9fad2e320104cc44d5631203c0a7085dedbaf35c/pkg/volume/plugins.go#L433

We can pretty easily wire up the CSI plugin to pass audience bound tokens to CSI drivers. If we like this approach, then we need an API design for:
* CSI configuration. How do I configure a driver that (1)  needs a service account token and (2) needs the token to have a specific audience?
  * Some options are configuration on the global CSIDriver object or at the pod level.
* CSI runtime: How does the kubelet pass the token to the driver?
  * This will probably look something like the other [attributes](https://github.com/kubernetes/kubernetes/blob/9f841bf42396daf1ed4b7ab47c1e1708bfb028b3/pkg/volume/csi/csi_mounter.go#L220-L228) we pass.

/sig storage
/sig auth

@kubernetes/sig-auth-feature-requests @kubernetes/sig-storage-feature-requests 
@seh @kfox1111 @munnerz

**Comment by seh** [comment]
As an intermediate hack, following a suggestion posed by @tallclair, my CSI driver uses the _TokenRequest_ API to fetch a service account token for the pod into which it's mounting a volume. However, as discussed in the SIG Auth meeting on 11 December 2019, doing so is only really safe if we also use an admission plugin that verifies that the token request both comes from the CSI driver's service account and that the pertinent pod is indeed mounting a volume provided by that CSI driver.

It works, but it's messy.

**Comment by kfox1111** [comment]
should such a check be added to the node admission plugin?

**Comment by seh** [comment]
It would need to know which service accounts are associated with which CSI drivers, which isn't obvious from the _CSIDriver_ object. You can get from a pod's volume mounts to _CSIDriver_ objects, but you don't know which pods are implementing which drivers.

**Comment by enj** [comment]
Folks from SIG Auth seemed to generally be happy with this proposal.  I think we need feedback from SIG Storage folks on if this makes sense and how to configure it.

**Comment by kfox1111** [comment]
Hmm... yeah, there is no real link between a csidriver and a service account...

This somewhat is not specific to csidrivers as well. Say you have a daemonset that loads a nonstorage driver onto the node. It wants to modify the nodeobject on which it is running on. Today either you need to use the node's credential, or you need to give the daemonset service account access to change all nodes (not very secure). Could the same solution be used for both issues? Just thinking out loud here.

**Comment by kfox1111** [comment]
It almost feels like an rbac kind of policy thing. Pod P1 with service account S can do X with resource Y but only if P1 is on the same host as another pod P2 referencing Y?

kind of like: the serviceaccount for the csidriver has permissions to impersonate user service account only if it has a running pod instance on the same node as a pod on the same node. or the service account or a problem detector can edit the node object only if it has a pod running on the same node as the node object.

Maybe these are still too different to put into rbac... The use case keeps coming up though.

**Comment by kfox1111** [comment]
More thinking out loud here.... There's a third general service account restriction I'd really like to see.
Operators typically ask for access to all secrets in the cluster so they can do their work. but that is kind of horrible...

There needs to be a way to restrict secret access by namespaces only to those operators service accounts that have an instance of their CR inside that same namespace.

**Comment by mikedanese** [comment]
I don't see this requiring any admission or changes in authorization. In either of the options for the Kubernetes API, permission to update the CSIDriver or PodSpec to specify an audience should be sufficient. There's no object references or secrets here at play here.

**Comment by kfox1111** [comment]
for just the csi use case, I agree, it could be solved with a csidriver/podspec audience field addition and admission checks.

Just wondering out loud a little bit if there is a greater problem that can be solved with the same machinery. The other two use cases are just as scary to me on my own clusters. All fall into the category of "software provided by others are asking/getting way more permissions to the entire cluster then necessary to do their job because lack of feature restricting access"

**Comment by seh** [comment]
Something I forgot to mention, @mikedanese: Since these service account tokens likely have a short lifetime before they expire, a CSI driver may need to acquire fresh tokens every so often. It would be easy enough to push a valid token down to the driver through the "volume context" in the `NodePublishVolume` call, but after that, the driver would have no way to receive subsequent tokens. I don't think it's valid to call `NodePublishVolume` on a driver repeatedly if an earlier call completed successfully.

**Comment by sftim** [comment]
I'm wondering what determines the audience for the token the CSI driver gets to see. Maybe there's a confused deputy attack there, I'm assuming there couldn't be but I thought I'd mention it in case I'm wrong.

**Comment by seh** [comment]
In my CSI driver, I take the audiences as a command-line flag set by the cluster operator who deploys the driver. That's the person who probably also configured whichever other system needs to accept those tokens.

With Vault's Kubernetes auth method, for example, the cluster operator who deploys the CSI driver would have to tell the Vault role authors [which audience to expect](https://www.vaultproject.io/api/auth/kubernetes/index.html#audience) coming out of the CSI driver.

**Comment by zshihang** [comment]
@seh, 
> a CSI driver may need to acquire fresh tokens every so often

how would the csi driver reuse the token? looking at the current usage of the token in vault provider, it is only used in for login when `NodePublishVolume`?

**Comment by seh** [comment]
> how would the csi driver reuse the token? looking at the current usage of the token in vault provider, it is only used in for login when `NodePublishVolume`?

Vault secrets can convey an advisory TTL. If those secrets expire, the CSI driver should fetch fresh values and rewrite the published files. In order to authenticate with Vault again, the driver may need a new service account token if the previous token expired already.

That's how my driver works, optionally, if enabled for a particular Vault secret. It means that the consuming container has to be ready to reread the files, as opposed to reading them only once when it starts.

**Comment by zshihang** [comment]
we can remount the volume every period < TTL in this case where `NodePublishVolume` will be called again.
