### ISSUE TITLE
Error creating load balancer in AWS

### ISSUE THREAD

**Issue by AlexShemeshWix** [kubernetes/kubernetes#86441]
kube version: Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
nginx-ingress controller version: 0.22.0

**What happened**:
We have kops managed kube clusters in 6 DCs in AWS.
in one of them kube fails to create load balancer that suppose to serve nginx-ingress instances.
I can see following error in events in kube-public namespace.

```
Error creating load balancer listener: "TooManyTargets: The maximum number of targets per load balancer '2000' has been reached on load balancer 'arn:aws:elasticloadbalancing:eu-west-1:11111111111:loadbalancer/net/a00750083f5d246adb186f4de33ea231/258d33324f0cb6d7'\n\tstatus code: 400, request id: 5f9ffd25-3ae7-4b6b-a562-6b9613fbc60f"
```
Cluster has ~350 nodes total. Load balancer suppose to forward traffic to port 80 and port 443. 
**What you expected to happen**:
So usually one load balancer created with 2 target groups in listeners each contains all 350 nodes.

**How to reproduce it (as minimally and precisely as possible)**:
generate kube cluster with kops with 350 nodes.
install nginx-ingress using helm
you will see error in events stream in kube-public.

**Anything else we need to know?**:
We had these errors before but we created load balancers long time ago and it successfully registered once so when this error happens its usually easy to fix by manually edidting tarteht groups to add missing instances to target group. At this case it wont help since load balancer never fully configued, after this failed attempt it remains with single listening target group for port 80.
**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian"
- Kernel (e.g. `uname -a`): Linux ip-10-85-99-109 4.19.37-wix #1 SMP Tue Jun 18 12:13:42 UTC 2019 x86_64 GNU/Linux
- Install tools: kops Version 1.15.0 (git-9992b4055)
- Others: nginx-ingress deployed from stable chart version 1.2.3 https://github.com/helm/charts/tree/master/stable/nginx-ingress

**Comment by AlexShemeshWix** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by AlexShemeshWix** [comment]
Ive found the solution.
Ive reconfigured nginx-ingress-controller to create classic elb instead of nlb.
Ive removed following annotation from nginx-ingress-controller service object
```
service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

**Comment by shyamjvs** [comment]
@AlexShemeshWix In the description you mentioned only exposing 2 ports (80, 443) per node, with 350 nodes. That should be 700 backends for target group. Wondering how it's complaining with 2000:

```
Error creating load balancer listener: "TooManyTargets: The maximum number of targets per load balancer '2000' has been reached on load balancer 'arn:aws:elasticloadbalancing:eu-west-1:11111111111:loadbalancer/net/a00750083f5d246adb186f4de33ea231/258d33324f0cb6d7'\n\tstatus code: 400, request id: 5f9ffd25-3ae7-4b6b-a562-6b9613fbc60f"
```

**Comment by lsowen** [comment]
I am running into the same issue, however my cluster currently only has 4 nodes with two ports exposed (80, 443)

**Comment by nckturner** [comment]
I'm going to close this issue as the original poster seems to have resolved it.  @lsowen yours sounds a bit different, if you are still experiencing it can you open a new issue?

/close

**Comment by mimmus** [comment]
@AlexShemeshWix 
> In the description you mentioned only exposing 2 ports (80, 443) per node, with 350 nodes. That should be 700 backends for target group. Wondering how it's complaining with 2000:
> 
> ```
> Error creating load balancer listener: "TooManyTargets: The maximum number of targets per load balancer '2000' has been reached 

We are wondering same question: perhaps is  it counting target x 3 times, one for every Availability Zone?
