### ISSUE TITLE
GCE startup: clusters in different zones have name collisions

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#8645]
1. Started a cluster in us-central1-f.
2. (accidentally) switched config to us-central1-b.
3. repeated kube-down.sh/kube-up.sh cycles cannot recover from this; you have to switch back to the original zone, kube-down.sh, then you can get it working again.

**Comment by roberthbailey** [comment]
Please re-open if this is still something that we need to address.
