### ISSUE TITLE
my kubernetes version is 1.16.2 I cannot use ephemeralcontainers

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#86461]
}[root@master01 ephemeralContainers]# curl http://localhost:8081/api/v1/namespaces/default/pods/nginx/ephemeralcontainers
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    
  },
  "code": 404
}

[root@master01 ephemeralContainers]# kubectl -n default replace --raw /api/v1/namespaces/default/pods/nginx/ephemeralcontainers -f ./ephemeral.json 
Error from server (NotFound): the server could not find the requested resource
[root@master01 ephemeralContainers]# 

my kubernetes version is 1.16.2

> 

>

**Comment by liggitt** [comment]
The feature is still alpha level and is not enabled by default. You can enable it with the --feature-gates flag to the apiserver and to kubelets, but be aware that upgrade compatibility for alpha features is not guaranteed.
