### ISSUE TITLE
apply can't work, but delete/apply work

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes/kubernetes#86463]
**What happened**:

when apply a replicaset change, and change the label and apply again, it reports error, I have to delete this replicaset and apply again, all fine. 

Furtherly, if the first deployment with wrong yaml, and apply with correct one, it only starts one pod. 

**What you expected to happen**:

should be fine to switch the label and start the nominated count of replica pods. 

**How to reproduce it (as minimally and precisely as possible)**:

```
master $ cat replicaset-definition-1.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx

master $ kubectl apply -f replicaset-definition-1.yaml
replicaset.apps/replicaset-1 created

master $ kubectl get all
NAME                     READY   STATUS    RESTARTS   AGE
pod/replicaset-1-g97dd   1/1     Running   0          2m7s
pod/replicaset-1-q5b85   1/1     Running   0          2m7s

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   25m

NAME                           DESIRED   CURRENT   READY   AGE
replicaset.apps/replicaset-1   2         2         2       2m7s
master $

# So I change the label from `frontend` to `nginx` and apply the change, get error
master $ vi replicaset-definition-1.yaml
master $ cat replicaset-definition-1.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
master $ kubectl apply -f replicaset-definition-1.yaml
The ReplicaSet "replicaset-1" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"tier":"nginx"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
master $
```

sometime, if previous yaml file is not correct and I apply a proper yml later, I can see the replicaset is created, but only run with one pod. which I need 2 replica pods.

**Anything else we need to know?**:

**Environment**: linux
- Kubernetes version (use `kubectl version`): 

```
master $ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

```
master $ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
master $
```

- Kernel (e.g. `uname -a`):

master $ uname -a
Linux master 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ozbillwang** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
The selector on an apps/v1 replicaset is immutable after creation. 

/remove-sig cli
/sig apps

**Comment by zhouya0** [comment]
As it said ` field is immutable`, so you can use `kubectl apply --force` which will delete and then create.

**Comment by tedyu** [comment]
See #66602

**Comment by ozbillwang** [comment]
Thanks a lot @zhouya0  & @tedyu 

so `kubectl apply --force` fixed both issue.

* I can switch label whatever I like to, the command will be always successful
* I can guarantee to get proper number of replica pods.
