### ISSUE TITLE
I want to use readinessGates ，how can i create a condition

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#86465]
I want to use readinessGates ，how can i create a condition

**Comment by php-coder** [comment]
> how can i create a condition

Could you elaborate more on this? What do you mean by "create a condition"?

Based on the [docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate):
> Since the kubectl patch command still doesn’t support patching object status, the new Pod conditions have to be injected through the PATCH action using one of the KubeClient libraries.

my understanding is that you have to interact with kubernetes API from your own code.
