### ISSUE TITLE
Scheduler： len(failedPredicates) always 0

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#86475]
failedPredicates declared, but would not have failedPredict add to it.

https://github.com/kubernetes/kubernetes/blob/9fa1e00be9f4816e18d463f8125a7f20c0d4aee1/pkg/scheduler/core/generic_scheduler.go#L642
https://github.com/kubernetes/kubernetes/blob/9fa1e00be9f4816e18d463f8125a7f20c0d4aee1/pkg/scheduler/core/generic_scheduler.go#L652

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment]
I suppose it's the master code, right? We're in the mid of migrating legacy predicate/priorities to pure plugins, so some messy code is expected. We're aware of them and get them cleanup very soon :)

**Comment by cwdsuzhou** [comment]
thanks for your clarification @Huang-Wei

**Comment by ahg-g** [comment]
can you clarify why is this a bug?

**Comment by cwdsuzhou** [comment]
seem it has been fixed in master branch as @Huang-Wei said

/close
