### ISSUE TITLE
Validation error during deployment using YAML config file

### ISSUE THREAD

**Issue by saf-itpro** [kubernetes/kubernetes#86486]
**Environment**: Windows Containers on Windows 10, Azure Kubernetes Services Cluster, Azure Cli, Azure Cloud Shell

I'm following [this][1] Microsoft Tutorial to create a Windows Server container on an Azure Kubernetes Service (AKS) cluster using Azure Cli. In the [Run the Application][3] section of this turorial, I get the following error when running the following command to deploy the application using `YAML` config file:

    kubectl apply -f sample.yaml

>>error: error validating "sample.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false

**Question**: As shown in the following `sample.yaml` file, the `apiVersion` is already set. So what this error is about and how can we fix the issue?

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      replicas: 1
      template:
        metadata:
          name: sample
          labels:
            app: sample
        spec:
          nodeSelector:
            "beta.kubernetes.io/os": windows
          containers:
          - name: sample
            image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
            resources:
              limits:
                cpu: 1
                memory: 800M
              requests:
                cpu: .1
                memory: 300M
            ports:
              - containerPort: 80
      selector:
        matchLabels:
          app: sample
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: sample
    spec:
      type: LoadBalancer
      ports:
      - protocol: TCP
        port: 80
      selector:
        app: sample

  [1]: https://docs.microsoft.com/en-us/azure/aks/windows-container-cli
  [2]: https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest
  [3]: https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#run-the-application

**Comment by liggitt** [comment]
I'm unable to reproduce this. what version of kubectl are you using? can you attach the exact yaml file you are using to rule out any copy/paste whitespace issues?

**Comment by saf-itpro** [comment]
@liggitt I'm using [Azure Cloud Shell](https://azure.microsoft.com/en-us/features/cloud-shell/) that  -according to the second checkmark on the above link - is updated and maintained by Microsoft. However, I did run `kubectl version` in Azure Cloud Shell, and got the following output. Does this output tell what version I'm using. If it's an older version, do you happened to know how I can upgrade to the latest version?

**Output of kubectl version command in Azure Cloud Shell**:

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by saf-itpro** [comment]
@liggitt Following is the attached yaml file you request. I'm using the Azure Cloud Shell and downloaded this file using command `download sample.yaml`. After download, I had to changed the file extension to `.txt` since GitHub was not allowing me to attach the file with some other extensions such as `yaml` .
[sample.txt](https://github.com/kubernetes/kubernetes/files/3989527/sample.txt)

**Comment by liggitt** [comment]
it looks like you have a typo in the file:

```
piVersion: apps/v1
kind: Deployment
metadata:
...
```

**Comment by saf-itpro** [comment]
@liggitt The file content is taking from [this ](https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#run-the-application) section of Microsoft tutorial by just clicking `Copy` button at the top right corner of their file content there and then pasting it to their Azure Cloud Shell by first creating the file using `vi` editor. Is there something we can suggest there to correct their typo? Microsoft is always open to the edits (via GitHub) in their online documents (subject to an approval by their team).

**Comment by liggitt** [comment]
The file on that site is correct. I suspect you opened vi in read mode, then by pasting, the first `a` put you in edit mode.

**Comment by saf-itpro** [comment]
@liggitt  Good catch. You are the best. Thank you for coming to my rescue. It's working now.
