### ISSUE TITLE
why I cannt access pod with headless service

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#86516]
[root@master01 service]# curl nginx-02.nginx-clusterip-svc-headless.default.svc.cluster.local:80
curl: (6) Could not resolve host: nginx-02.nginx-clusterip-svc-headless.default.svc.cluster.local; Unknown error
[root@master01 service]# curl nginx-clusterip-svc-headless.default.svc.cluster.local:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

[root@master01 service]# kubectl get svc
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes                     ClusterIP   10.68.0.1       <none>        443/TCP          8d
nginx-clusterip-svc            ClusterIP   10.68.200.126   <none>        8000/TCP         39m
nginx-clusterip-svc-headless   ClusterIP   None            <none>        8000/TCP         27m
nginx-clusterip-svc-with-ip    ClusterIP   10.68.100.100   <none>        8000/TCP         34m
nginx-nodeport-svc             NodePort    10.68.162.103   <none>        8000:38819/TCP   31m
[root@master01 service]# 

ME                READY   STATUS    RESTARTS   AGE
debug-agent-5b9xb   1/1     Running   1          22h
debug-agent-b5m9h   1/1     Running   1          22h
debug-agent-htqc6   1/1     Running   1          22h
debug-agent-pw52v   1/1     Running   1          22h
nginx-01            1/1     Running   0          39m
nginx-02            1/1     Running   0          39m
nginx-03            1/1     Running   0          39m
[root@master01 service]#

**Comment by aojea** [comment]
@13567436138 the headless service creates a DNS record per pod, and per your description it's working correctly

> [root@master01 service]# curl nginx-clusterip-svc-headless.default.svc.cluster.local:80
> 
> <title>Welcome to nginx!</title> <style> body { width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif; } </style>
> 

I think that you are looking for DNS records for pods, and this is explained here
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods
