### ISSUE TITLE
Document kubectl diff command as GA

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#86525]
**What would you like to be added**:

Currently, we primarily have documentation for `kubectl diff` in the helptext itself.

`kubectl diff` is being promoted from beta to GA in v1.18.

For `kubectl diff`, we need more documentation on kubernetes.io.

Documentation includes:

- [x] https://kubernetes.io/docs/reference/kubectl/cheatsheet/ https://github.com/kubernetes/kubernetes/issues/86525
- [x] `kubectl diff` requires write access
- [x] `kubectl diff` exit code https://github.com/kubernetes/kubernetes/issues/87343 https://github.com/kubernetes/kubernetes/pull/87805
- [x] https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/
- [x] https://kubernetes.io/docs/reference/kubectl/overview/#examples-common-operations  https://github.com/kubernetes/website/pull/18665 
- [x] https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ https://github.com/kubernetes/website/pull/19586
- [x] kubectl book https://kubectl.docs.kubernetes.io/ 
  - [x] https://kubectl.docs.kubernetes.io/pages/app_composition_and_deployment/diffing_local_and_remote_resources.html

**Why is this needed**:

`kubectl diff` is graduating to GA, so we need to properly document usage and examples for users.

https://github.com/kubernetes/kubernetes/issues/68526

cc @apelisse 
/sig cli
/sig api-machinery
/priority important-soon

**Comment by apelisse** [comment]
> kubectl diff requires write access

That's such a great point, thank you!

**Comment by zhouya0** [comment]
I think can try to help to write documentation, because i know `kubctl diff` a lot , but i never did that before. So should submit PR directly into `https://github.com/kubernetes/website`?

**Comment by apelisse** [comment]
Yes, that's really appreciated @zhouya0. Feel free to ask more question on slack (#wg-apply), and I'd love to know what you're doing with diff!

**Comment by julianvmodesto** [comment]
From the release team:

> * Docs PRs must be ready for review on Mon March 9
> * Docs must be complete, all PRs reviewed and ready to merge by Mon March 16

Thanks for your help @zhouya0! I think we're all good here now! I'll do one more pass.

/assign @zhouya0 

The only things left are maybe documenting `kubectl diff` in a `kustomize` workflow in the kustomize docs, and also if there is a `feature-state` Hugo Shortcode we should use, but all of the important docs seem covered.

**Comment by zhouya0** [comment]
Sorry I see this message just now, "Docs PRs must be ready for review on Mon March 9". Is that means it's already late for the PRs?

**Comment by apelisse** [comment]
It means we've got to hurry up, but there's not a crazy amount of work either.

**Comment by zhouya0** [comment]
I send a PR to `k/website`:https://github.com/kubernetes/website/pull/19586

**Comment by julianvmodesto** [comment]
> if there is a feature-state Hugo Shortcode we should use to indicate v1.18 stable

I'm actually retracting this task – I couldn't find any commands that publish their feature state

**Comment by julianvmodesto** [comment]
This is done now, thank you @zhouya0!
