### ISSUE TITLE
Kubernetes service redirect failed

### ISSUE THREAD

**Issue by bengong2015** [kubernetes/kubernetes#8652]
I estabished a master (202.120.11.50) and a minion (202.120.11.52) and build a pod called 'wildfly' through replicationController (carry an attri 'selector': "name=wildfly"). The pod has been assigned to 202.120.11.52:8182 by setting 'hostPort':8182 (arg 'containerPort':8087) and the internel address on minion (202.120.11.52) is 172.17.0.1:8087 (searched by ps -ef|grep docker). Then I created a kubernetes service exposing port 8182:
{
       "kind":"Service".
       "apiVersion":"v1beta3",
       ...
       "spec":{
             "ports":[
                    {
                          "port":8182,
                          "targetPort":8087,
                          "protocol":"TCP"
                     }
              ],
              "selector":{ "name": "wildfly" }
         }
}
It automatically created an endpoints:
Name                           ENDPOINTS
wildfly-service              172.17.0.1:8087

The connections test:
(externel connection)  http://202.120.11.52:8182      Correct
(externel connection)  http://172.17.0.1:8087            Connection Time Out
(internel connection on minion (202.120.11.52) ) http://172.17.0.1:8087       Correct
(externel connection)  http://202.120.11.50:8182       Connection Refused

Then I tried to build a service without 'selector' and assigned an endpoints manually to 202.120.11.52:8182:
Name                           ENDPOINTS
wildfly-service              202.120.11.52:8182

It was still failed if I tried to connect 202.120.11.50:8182.
I've read the guestbook of kubernetes service, it said the kubernetes can random select a pod when customer connect to a public ip+port. How can I do that? For example, I want the kubernetes automatically redirect to a pod on minions (like 202.120.11.52:8182) when I try to connect 202.120.11.50:8182.

PS: The iptables on master and minion ACCEPT all route (INPUT,OUTPUT,FORWARD)..

**Comment by thockin** [comment]
On Thu, May 21, 2015 at 7:17 PM, bengong2015 <notifications@github.com> wrote:
>
> I estabished a master (202.120.11.50) and a minion (202.120.11.52) and build a pod called 'wildfly' through replicationController (carry a attri 'selector': "name=wildfly"). The pod has been assigned to 202.120.11.52:8182 by setting 'hostPort' (arg 'containerPort':8182) and the internel address on minion (202.120.11.52) is 172.17.0.1:8087. Then I created a kubernetes service exposing port 8182:

You should not need a host port, almost ever.  The existence of a 172
network suggests that you did not set up networking properly.  Did you
install flannel or some other SDN, or can you ensure your pods can all
ping each other across nodes?  Read docs/networking.md

**Comment by bengong2015** [comment]
The OS is CentOS7 with libvirt, the lbvirt is opened with NAT model (ip: 192.168.122.1). Shall I close the virbr0 or install another SDN (like OpenVSwitch)?

**Comment by thockin** [comment]
You have to configure docker's bridge so that it can communicate across
nodes.  By default docker uses 172 as a machine-private range, which
necessitates the abomination that is host ports.

**Comment by bengong2015** [comment]
Can I change the container's network mode from 'Bridge(default)' to 'host' so that the container can can be reached by external connection? And can I set the containers' network mode in replicationController's json file?

**Comment by thockin** [comment]
You can use host networking, but that's really an anti-pattern for
kubernetes - it forces you to coordinate port usage across containers.  If
you want to use kubernetes, you should invest in getting the network model
working properly.  Flannel is very easy to set up.

**Comment by bengong2015** [comment]
Thanks for ur help. I gonna try Flannel.

**Comment by bengong2015** [comment]
I set a 'publicIPs' and the service work. Now I can connect to pods (running wildfly environment) by a single ip+port (202.120.11.51) through browser. However, the connection was really slowy, spend apporx. 20s. And when I tried to connect to the service through EJB client, the connection failed. What's the problem of this?

**Comment by thockin** [comment]
It's practically impossible to know what's going on.  Is this after you you
got flannel running?  Is it slow if you do in-cluster access (for example
from a node to the service?)  Can you ping all of the backend pods?

**Comment by bengong2015** [comment]
I can ping a backend pod on its host machine. For example, their is a container running on minion 202.120.11.54, the backend ip (--bip=172.17.0.129/25) is 172.17.0.129. I can ping this ip on minion 54, but the accessing from other way failed. It seem that the flannel doesn't work. However, the endpoints of kubenetes has been automatically created with arg '172.17.0.129:8087'.

**Comment by bengong2015** [comment]
I manually set the setting of docker0 on minions and the connection from client pass. Now there is a new problem:
I tried to connect to database in starting the container, the starting process expose 'no route to host' exception (failed to connect to database). However, when I start the container by docker directly and set host port for it, the problem gone. If I start it by using kubernetes replicationController, the logs of container shows the 'no route to host' exception. I guess it might be caused by the internal network built by flannel cannot get access to the external database. How can I fix it?

**Comment by thockin** [comment]
It sounds like flannel is not running correctly.  Before you can really do
ANYTHING else you need to ensure that pods on node A can ping pods on node
B, and vice-versa.  if that doesn't work then all sorts of stuff will not
work.

**Comment by bengong2015** [comment]
Thanks, I already solved the problem by manually setting the ip&route of docker bridge(docker0) and assigned key value of etcd. (e.x. docker0 on 202.120.11.51: 172.17.41.1 and key of etcd: 172.17.41.0-24 '{"publicIP":"202.120.11.51"}') It seems the flannel sometimes cannot automatically syno. the setting of docker0 and etcd keys if I manually change one of them.
There are other problems:
1. The kubernetes cannot monitor the status of process runnning inside containers so that the connection might be failed if kubernetes assign the request to a container which is failed to correctly start the software environment (e.x. JBoss) inside. (The pod's status is running without any error sign) Whether the kuberbetes can monitor the status mentioned above and refuse to add the IPs of error pods into endpoint of service unless the problem gone?
2. The kubernetes allocates pods to minions averagely based on resources usage, but the different minions spend different time on starting the software environment inside of container which may cause confusion. For instance, a minion with E8400 CPU used average 600s+ to start 10 replicas when a minion with I5 CPU only used 33s. Therefore, sometimes the connection will pass or failed based on the connection has been allocated to which minion.
3. It seems that the command 'delete pod <pod id>' only do 'docker stop <container Id>' on docker client. Then the rc will create a new container which cause the minions has a large number of exited containers. Currently I solve this by using a java client including kubernetesApi and dockerJavaApi. Whether Kubernetes can remove the useless container when the rc auto, create a new one?

**Comment by dove-young** [comment]
I hit to similar problem. 

I am using hyperkube image, and it sets portal-net to 10.0.0.1/24 by default.  And all the services will be registered to this network. 

```
"Args": [
        "apiserver",
        "--portal-net=10.0.0.1/24",
        "--address=0.0.0.0",
        "--etcd_servers=http://127.0.0.1:4001",
        "--cluster_name=kubernetes",
        "--v=2"
    ],

```

I configured  flannel handles docker networks

```
etcdctl --no-sync  -C ${MASTER_IP}:4001 get /coreos.com/network/config
{ "Network": "10.1.0.0/24" }

# etcdctl --no-sync  -C ${MASTER_IP}:4001 ls /coreos.com/network/subnets
/coreos.com/network/subnets/10.1.7.0-24
/coreos.com/network/subnets/10.1.30.0-24
/coreos.com/network/subnets/10.1.11.0-24

```

Then I also hit problems that application cannot connect to database if application pod is not located in the same host as database pod. 

when I try to access to the database service from application container via nc, it just give no response. 

```
# docker exec 55c790384670 sh -c 'nc 10.0.0.215 3306'
#
```

when I access to the database service from application container which located in the same host as database, it response ordinarily

```
# docker exec eece sh -c 'nc 10.0.0.215 3306'
R
5.5.41-MariaDBLs"K4`f_ÿ -]n4S*q"NCEpmysql_native_password
```

**Comment by bgrant0607** [comment]
Obsolete
