### ISSUE TITLE
init-container restarted after docker prune image

### ISSUE THREAD

**Issue by zhaoguangqiang** [kubernetes/kubernetes#86531]
**What happened**:

My init-container completed in the first day.
In the second day, i have a crontab to prune image by docker.
After clean, my init-container will be restarted.

**What you expected to happen**:

I want the init-container not be restarted

**How to reproduce it (as minimally and precisely as possible)**:

Run a pod with init-container.
After init-container success complete.
Then run "docker container prune -f" on your node.
Wait for a minute. The init-container will be restarted.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux ni-k8s-1 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pbertera** [comment]
The command `docker container prune` removes the stopped containers, not the images.
Removing the terminated init container will cause a restart of the init container, see #67261

**Comment by howardjohn** [comment]
the linked issue was closed as resolved but I'm not sure how (or if) it has been resolved.

I get the restarting failed containers, but starting an init container after the application container seems like a clear violation of the lifecycle

**Comment by pbertera** [comment]
@howardjohn: I can agree with you, looks like a weak design of the init container life cycle, the Kubelet relies on the terminated init container presence to define if the init container has been started.
You can even trigger the init container re-execution via the Kubernetes Garbage collector, see also #78328

**Comment by anapsix** [comment]
this is still an issue, when initContainer is removed by `docker container prune`, or `docker rm`, it respawns, but main Pod's container(s) continue to run..

Depending on initContainer action, it might not be able to complete successfully, while main container is running, causing `Init:CrashLoopBackOff`.

In some cases, initContainer's actions are not compatible with running main container(s), causing other failures.
For example: init container moves application code into tmpfs, (or PV), while main container's `entrypoint.sh` updates config values from external source, causing application config to reset to defaults, breaking application (since main container did not restart, and `entrypoint.sh` was not executed)

**Comment by tcz001** [comment]
any idea to add a execution rule for init container, once it's complete k8s should ignore the deletion of container

**Comment by Boran** [comment]
Hmm, how to keep this open then, it is still a real problem and biting people...

**Comment by anapsix** [comment]
still an issue in `1.19.4`
one of the long running pods died, got rescheduled, ended up being mutated to include an init container, but init container did not run
```
Error from server (BadRequest): previous terminated container "copy-vault-env" in pod "xxxxx" not found
```
