### ISSUE TITLE
`kubectl convert` was not removed in v1.17

### ISSUE THREAD

**Issue by superbrothers** [kubernetes/kubernetes#86536]
**What happened**:

In v1.16 release note, `kubectl convert` will be removed in v1.17. However it still exists. Is this forgetting to remove it?

> `kubectl convert`, deprecated since v1.14, will be removed in v1.17.

- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Thanks for the issue, but a bug is not required to track this. @seans3 is working on moving the functionality to a standalone command to unblock kubectl extraction while keeping the function available.

**Comment by Mowzey123** [comment]
Am tasked with setting up MongoDB on Kubernetes, What is the new way to convert from apps/v1beta to apps/v1

**Comment by liggitt** [comment]
`kubectl convert` is still present and functional

**Comment by Mowzey123** [comment]
My kubeadmn git version is 1.17 but when I try to convert mongodb StatefulSet deployment from apps/v1beta to apps/v1. It throws a warning that kubetcl convert is deprecated and stops at that.
