### ISSUE TITLE
No Device Plugin Callback for Releasing devices against Allocate

### ISSUE THREAD

**Issue by fujitatomoya** [kubernetes/kubernetes#86539]
**What would you like to be added**:

Device Plugin Callback to release(dis-allocation) the hardware or devices at the finalization of pods.

**Why is this needed**:

Currently the following simple API are ready for Device Plugin,
https://github.com/kubernetes/kubernetes/blob/92e0de32698864f4dce876d79e80386261e3e18c/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.proto#L48-L67

but device and hardware, platform acceleration getting complicated including edge A.I and pre-process for sensing data. in generally, if allocation is required to bind the hardware to pods, there could also be release(dis-allocation) callback which will take care of device specific finalization when pods exit.

**Note**:

I am not so sure where I could start this discussion(or already discussion is in progress or done), if this is not the place, tell me where I could tag this issue. thanks in advance and appreciated.

**Comment by ipuustin** [comment]
@fujitatomoya: have you seen this issue: https://github.com/kubernetes/kubernetes/issues/59110 ?

**Comment by fujitatomoya** [comment]
@ipuustin 

appreciate for pointing that out, i've been though the https://github.com/kubernetes/kubernetes/issues/59110.

it seems that there was an important discussion on slack based on  https://github.com/kubernetes/kubernetes/issues/59110#issuecomment-379273420 or maybe not, it is 1.5 years ago, so i am not sure how it ended up. it looks to me that it just phased away.

how do we need to proceed, open discussion on slack or any online sig wg available?

**Comment by ipuustin** [comment]
@bart0sh might have a pointer to the last time this subject was last brought up, and he also could have some ideas about how to deal with the current state of affairs.

There are currently ongoing proposals for improving the device plugin state (see https://docs.google.com/document/d/1Tc0Kc4GDWx1gFvGQbBUizudSuND6Kq8GiH7KVm_X5eg/edit and https://docs.google.com/document/d/1wPlJL8DsVpHnbVbTaad35ILB-jqoMLkGFLnQpWWNduc/edit). Please see if the new use cases in the documents already include your device use scenario, because it might be easier to contribute on current proposals rather than create your own.

**Comment by fujitatomoya** [comment]
@ipuustin 

i do not have access the following, already request the access permission though.
https://docs.google.com/document/d/1Tc0Kc4GDWx1gFvGQbBUizudSuND6Kq8GiH7KVm_X5eg/edit

> Please see if the new use cases in the documents already include your device use scenario, because it might be easier to contribute on current proposals rather than create your own.

totally agreed, will do that.

**Comment by fujitatomoya** [comment]
@ipuustin 

i have been through the documents, i see it is well considered and defined, appreciate it.

since we are with Sony, we have edge devices / robotics use cases, so that maybe it is better to sync up what we are trying to do once in a while. if any online discussion is there, i would like to participate in that.

**Comment by fujitatomoya** [comment]
@ipuustin 

i see the you've participated in kubrenetes organization, congrats.

how do you want us to proceed? is there anything/anywhere we should have discussion online? we are not sure how we can go further to catch up with Container Device Interfaces.

**Comment by fujitatomoya** [comment]
@prydonius thanks 👍

**Comment by fujitatomoya** [comment]
related to:

- https://github.com/kubernetes/enhancements/issues/1948
- https://github.com/kubernetes/enhancements/pull/1949

**Comment by fujitatomoya** [comment]
close this issue, see https://github.com/kubernetes/enhancements/pull/3080#issuecomment-989734876
