### ISSUE TITLE
It's impossible to restart master in private clusters created via kube-up (provider GCE)

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#86547]
If you create a private cluster via kube-up using provider GCE, you won't be able to restart your master nodes.
If you restart you master, the nodes won't be able to connect to your master.

This is due to this line - https://github.com/kubernetes/kubernetes/blob/127c47caf49bec4a59a0500f99b1b1d4cdbf340e/cluster/gce/util.sh#L2922
It gets executed on master on cluster-up, but it won't be re-executed on master restart.

We should fix that, especially if we're to implement https://github.com/kubernetes/kubernetes/issues/86484

/sig scalability
/priority important-soon

**Comment by mm4tt** [comment]
/remove-lifecycle stale
/good-first-issue

I'll ask whether someone in SIG Scalability public meeting would like to take on this one

**Comment by bartekzurawski** [comment]
Hello,

Can I start work on this one as my first issue? :)

**Comment by oxddr** [comment]
@bartekzurawski I don't see anyone else claiming it, so your contributions are welcome :)

**Comment by mm4tt** [comment]
@bartekzurawski, let me know if you need any explanations here

**Comment by bartekzurawski** [comment]
@mm4tt Thank you :) I've made some changes and assign you can you tell me is this will be good approach?

**Comment by mm4tt** [comment]
Thanks, @bartekzurawski!

I replied in the PR
