### ISSUE TITLE
Delete data safely from emptyDir volume in multi-tenancy environment

### ISSUE THREAD

**Issue by yy8848** [kubernetes/kubernetes#86546]
Local directories of emptyDir volumes are removed from disk during teardown.

```go
func (ed *emptyDir) teardownTmpfsOrHugetlbfs(dir string) error {
	if ed.mounter == nil {
		return fmt.Errorf("memory storage requested, but mounter is nil")
	}
	if err := ed.mounter.Unmount(dir); err != nil {
		return err
	}
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	return nil
}
```

In cloud multi-tenancy environment, safe data deletion is required especially for data like secrets.

Is it possible to add support for safe deletion?

**Comment by liggitt** [comment]
FYI, secret volumes are stored in tmpfs memory backed mounts, not disk

**Comment by yy8848** [comment]
Content of deleted files is just accessible from containers under rare conditions (access to raw disk for example). So the concern seems to be a little paranoid.
