### ISSUE TITLE
Disable route-mesh for LB liveness probes when destination-preserve=true annotation is set

### ISSUE THREAD

**Issue by gowthamboddapati** [kubernetes/kubernetes#86544]
**What happened**:
When preserve-destination annotation is set to true the routing mesh is getting disabled for actual traffic flow but the  route mesh isn’t getting disabled for LB liveness probes. As a result the VM's which doesn't have active pods are looking healthy from the point of view of LB and getting active customer traffic. The VM's are dropping the traffic since the routing mesh is disabled.  

**What you expected to happen**:
When preserve-destination annotation is set routing mesh should be disabled for LB liveness probes as well as end user traffic. 

**How to reproduce it (as minimally and precisely as possible)**:
Enable preserve-destination=true annotation in Azure k8s service and deploy an app that is registered with the service.  

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.1 
- Cloud provider or hardware configuration: Azure (ACS)
- OS (e.g: `cat /etc/os-release`): Windows 1903
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ksubrmnn** [comment]
Fixed by 85611

**Comment by ksubrmnn** [comment]
@yujuhong  Hey Yu-Ju this missed the 1.17 deadline and it’s a bug fix for the Windows preserve-destination feature. Can we back port this?
