### ISSUE TITLE
when computer container cpu usage through the metrics/cadvisor, the value larger than limited value and `top` command's value

### ISSUE THREAD

**Issue by zhangxingdeppon** [kubernetes/kubernetes#86540]
**What happened**:
hi, buddies, I met a problem, when computer container cpu usage through the metrics/cadvisor, the value larger than `top` command's value, I need a exactly value like `top` command,  can you give me some ideas? thanks

here is a example to show you, for example  deployment  `hux7rjho76zj3l2s-notebook`.
this is example deployment yaml:
<pre><code>
[root@ecs-5274-0318501 ~]# kubectl get deploy hux7rjho76zj3l2s-notebook -n aipaas-notebook -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-23T05:51:18Z"
  generation: 1
  labels:
    app: hux7rjho76zj3l2s-notebook
  name: hux7rjho76zj3l2s-notebook
  namespace: aipaas-notebook
  resourceVersion: "44842674"
  selfLink: /apis/extensions/v1beta1/namespaces/aipaas-notebook/deployments/hux7rjho76zj3l2s-notebook
  uid: 3d2c0dc0-2548-11ea-a14a-fa163ebce782
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: hux7rjho76zj3l2s-notebook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hux7rjho76zj3l2s-notebook
    spec:
      containers:
      - env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: none
        image: 172.16.1.222:10004/notebook/deeplearning_jupyter_limit_token:v1.3
        imagePullPolicy: Always
        name: hux7rjho76zj3l2s-notebook
        ports:
        - containerPort: 8888
          name: jupyter
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: "8589934592"
          requests:
            cpu: 500m
            memory: "2147483648"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /src/notebooks/
          name: hux7rjho76zj3l2s-notebook
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsUser: 999
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hux7rjho76zj3l2s-notebook
        persistentVolumeClaim:
          claimName: hux7rjho76zj3l2s-pvc
</code></pre>
cpu `limited:2, request:0.5`

 Firstly, use the metric/cadvisor computer the value, the promQL is `rate(container_cpu_usage_seconds_total{container_name=~"hux7rjho76zj3l2s-notebook.*"}[1m])`
 I have tried to decrease or increase the time, like `5m`/`30s`, but the value is also not exact.
 
through a period of time, you will find below cpu monitor grafana:

![image](https://user-images.githubusercontent.com/16789841/71348315-3fe59c80-25a7-11ea-920f-e9540707d2ef.png)

you will find sometime the cpu value larger than 2 a lot, the peak is `2.3`, but the value is exact returned by `top` command:

![image](https://user-images.githubusercontent.com/16789841/71348461-8e933680-25a7-11ea-8b99-cc99ccf6b56e.png)

**What you expected to happen**:
I need a exact value about container cpu usage, thanks.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
<pre><code>
[root@ecs-5274-0318501 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
</code><pre>
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhangxingdeppon** [comment]
@kubernetes/sig-apps-bugs

**Comment by zhangxingdeppon** [comment]
@zq-david-wang Hi, buddy,  Do you have any ideas about this problem? thanks very much.

**Comment by zq-david-wang** [comment]
@zhangxingdeppon  Mostly the accuracy depends on the frequency of sampling,  `top` may fetch a sample every 1s, yielding a much accurate measurement, but for the container metrics collected by prometheus via cadvisor endpoints, there are two sampling processing involved, cadvisor and prometheus both has its own sampling configuration and it is hard to sync the sampling processes.
It could be helpful for cadvisor to yield metrics with a timestamp indicating when the metrics is sampled, but somehow adding a timestamp to a metrics value is not recommended.

Roughly speaking, if prometheus fetch a sample from cadvisor very n seconds, cadvisor make a sample  from kernel very m seconds, then n seconds delta value dy  observed by prometheus could be x seconds delta value reported by cadvisor where x could be (n/m+/-1)*m ~= n+/-m , hence you would observe a higher/lower  rate reported by prometheus 


I am just speculating, the reasoning make sense to me :)  (My prometheus servers would  sometimes send an alert reporting some container is consuming more than 100% of its cpu limit which puzzled me a lot.)

Hope this would help.
There may be better explanations, but I think  this is definitely not a kubernetes issue.

**Comment by zhangxingdeppon** [comment]
@zq-david-wang yes, I got it, you are right,  perfectly answered my question, thanks very much; 
I think if we want to reslove this issue, maybe `metric/cadvisor` can explicitly calculate the percentage value,  and add it in metrics  like `container_cpu_usage_percentage  50%` , but not `container_cpu_usage_seconds_total`, In addition, add a metric in `kubelet metrics`,  this is also okay.
anyway, thank you very much.
