### ISSUE TITLE
Sending server-side-apply patch as protobuf

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/kubernetes#86559]
Original report: http://groups.google.com/group/kubernetes-wg-apply/t/61d80fedada07e33?utm_source=digest&utm_medium=email
> Hello!
>  
> I'm excited about the server-side-apply feature and want to use it. GKE
> just released Kubernetes 1.16 which includes this feature. I cannot use
> client-go, because of the number of dependencies, so I use the more minimal
> client that Eric Chiang built. I'm trying to add server-side-apply support
> to this client (see #1). However, this client doesn't support
> marshal/unmarshal of json in the way that Kubernetes does, because that
> would require depending on kubernetes/api (see #2) which has a large number
> of dependencies like client-go does. I'm including this context to make
> sure people are aware of the existence of this client and why people would
> choose to use it instead of client-go.
>  
> Anyways, my question is about sending the object (the HTTP request body) as
> a protobuf instead of as json. Is this possible? I looked at the
> implementation of kubectl (see #3) and it is sending the patch as json.
>  
> Thanks!
>  
> 1. https://github.com/ericchiang/k8s/issues/123
> 2. https://github.com/kubernetes/api
> 3. https://github.com/kubernetes/kubectl/blob/1528d4eea6dd954c652321beeb462b55cb181f7b/pkg/cmd/apply/apply.go#L417
> 

/kind bug
/sig api-machinery
/wg apply
/cc @apelisse @jennybuckley @tedyu

**Comment by liggitt** [comment]
Protobuf can only be used with data for which a schema is already known. It also is not straightforward to distinguish "present but null" values from "unspecified" values, which is necessary for patch requests. 

Adding support for protobuf-based patches would be a feature, not a bug fix, and it's unclear how feasible it is.

**Comment by kwiesmueller** [comment]
As far as I remember, apply uses the openapispec which is different for some things than the respective proto.

A more detailed error message for the patch sent in the issue linked above:
```
 --- FAIL: TestValidationBug (4.32s)
     apply_test.go:1375: Failed to create object using Apply patch: failed to create typed patch object: errors:
           .spec.template.spec.containers[name="hello"].livenessProbe.handler: field not declared in schema
           .spec.template.spec.containers[name="hello"].ports: element 0: associative list with keys has an element that omits key field "protocol"
           .spec.template.spec.containers[name="hello"].readinessProbe.handler: field not declared in schema
           .spec.template.spec.containers[name="hello"].resources.limits.cpu: expected string, got {string="1000m"}
           .spec.template.spec.containers[name="hello"].resources.limits.memory: expected string, got {string="100Mi"}
           .spec.template.spec.containers[name="hello"].resources.requests.cpu: expected string, got {string="10m"}
           .spec.template.spec.containers[name="hello"].resources.requests.memory: expected string, got {string="10Mi"}
```

**Comment by liggitt** [comment]
The linked issue is generating incorrect json. A proto-to-json translator will not work correctly, given some of the json serializations of our API types.

**Comment by liggitt** [comment]
Added comments to the linked issue, can discuss there
