### ISSUE TITLE
/apis/admission.certmanager.k8s.io/v1beta1?timeout=32s 503 Service Unavailable

### ISSUE THREAD

**Issue by bojanpog** [kubernetes/kubernetes#86594]
Hello!

After successfully upgrading kubernetel  from version 1.17 to v.1.17 all commands like "kubectl get pods" has some delay displaying data. After executing "kubectl get pods -v=6" I get this result:

_I1224 19:54:51.511686   27758 loader.go:375] Config loaded from file:  /root/.kube/config
I1224 19:54:51.529036   27758 round_trippers.go:443] GET https://k8s.cluster:6443/api?timeout=32s 200 OK in 15 milliseconds
I1224 19:54:51.533896   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis?timeout=32s 200 OK in 1 milliseconds
I1224 19:54:51.543628   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/project.cattle.io/v3?timeout=32s 200 OK in 4 milliseconds
I1224 19:54:51.543685   27758 round_trippers.go:443] GET https://k8s.cluster:6443/api/v1?timeout=32s 200 OK in 4 milliseconds
I1224 19:54:51.545104   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/apiregistration.k8s.io/v1beta1?timeout=32s 200 OK in 4 milliseconds
I1224 19:54:51.545263   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/extensions/v1beta1?timeout=32s 200 OK in 4 milliseconds
I1224 19:54:51.546171   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/apiregistration.k8s.io/v1?timeout=32s 200 OK in 6 milliseconds
I1224 19:54:51.547068   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/storage.k8s.io/v1?timeout=32s 200 OK in 5 milliseconds
I1224 19:54:51.548174   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s 200 OK in 6 milliseconds
I1224 19:54:51.549800   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/apps/v1?timeout=32s 200 OK in 9 milliseconds
I1224 19:54:51.549946   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/apiextensions.k8s.io/v1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.550383   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/autoscaling/v1?timeout=32s 200 OK in 7 milliseconds
I1224 19:54:51.550402   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/autoscaling/v2beta1?timeout=32s 200 OK in 7 milliseconds
I1224 19:54:51.550728   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/node.k8s.io/v1beta1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.550854   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/events.k8s.io/v1beta1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.551213   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/autoscaling/v2beta2?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.551382   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/rbac.authorization.k8s.io/v1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.551452   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/discovery.k8s.io/v1beta1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.551862   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/batch/v1?timeout=32s 200 OK in 9 milliseconds
I1224 19:54:51.551880   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/admissionregistration.k8s.io/v1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.552445   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/storage.k8s.io/v1beta1?timeout=32s 200 OK in 8 milliseconds
I1224 19:54:51.552476   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/monitoring.coreos.com/v1?timeout=32s 200 OK in 9 milliseconds
I1224 19:54:51.552725   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/batch/v1beta1?timeout=32s 200 OK in 9 milliseconds
I1224 19:54:51.552750   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s 200 OK in 9 milliseconds
I1224 19:54:51.553052   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/certmanager.k8s.io/v1alpha1?timeout=32s 200 OK in 10 milliseconds
I1224 19:54:51.553142   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/apiextensions.k8s.io/v1beta1?timeout=32s 200 OK in 11 milliseconds
I1224 19:54:51.553454   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/certificates.k8s.io/v1beta1?timeout=32s 200 OK in 10 milliseconds
I1224 19:54:51.553661   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/authentication.k8s.io/v1?timeout=32s 200 OK in 11 milliseconds
I1224 19:54:51.553954   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/scheduling.k8s.io/v1?timeout=32s 200 OK in 11 milliseconds
I1224 19:54:51.554456   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/authentication.k8s.io/v1beta1?timeout=32s 200 OK in 12 milliseconds
I1224 19:54:51.554854   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/scheduling.k8s.io/v1beta1?timeout=32s 200 OK in 12 milliseconds
I1224 19:54:51.554873   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/networking.k8s.io/v1?timeout=32s 200 OK in 11 milliseconds
I1224 19:54:51.555359   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/authorization.k8s.io/v1?timeout=32s 200 OK in 13 milliseconds
I1224 19:54:51.555381   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/management.cattle.io/v3?timeout=32s 200 OK in 12 milliseconds
I1224 19:54:51.555864   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/coordination.k8s.io/v1?timeout=32s 200 OK in 13 milliseconds
I1224 19:54:51.555884   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/networking.k8s.io/v1beta1?timeout=32s 200 OK in 12 milliseconds
I1224 19:54:51.556302   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/policy/v1beta1?timeout=32s 200 OK in 13 milliseconds
I1224 19:54:51.556328   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/authorization.k8s.io/v1beta1?timeout=32s 200 OK in 13 milliseconds
I1224 19:54:51.557114   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/coordination.k8s.io/v1beta1?timeout=32s 200 OK in 14 milliseconds
I1224 19:54:56.554926   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/admission.certmanager.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 5011 milliseconds
I1224 19:54:56.558414   27758 request.go:1220] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'Error trying to reach service: 'dial tcp 10.98.247.147:443: i/o timeout''
I1224 19:54:56.558452   27758 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I1224 19:54:56.560645   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/admission.certmanager.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 0 milliseconds
I1224 19:54:56.560740   27758 request.go:1220] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'Error trying to reach service: 'dial tcp 10.98.247.147:443: i/o timeout''
I1224 19:54:56.560752   27758 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I1224 19:54:56.561232   27758 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
I1224 19:54:56.562919   27758 round_trippers.go:443] GET https://k8s.cluster:6443/apis/admission.certmanager.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 0 milliseconds
I1224 19:54:56.563004   27758 request.go:1220] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'Error trying to reach service: 'dial tcp 10.98.247.147:443: i/o timeout''
I1224 19:54:56.563016   27758 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I1224 19:54:56.573046   27758 round_trippers.go:443] GET https://k8s.cluster:6443/api/v1/nodes?limit=500 200 OK in 5 milliseconds
NAME                  STATUS   ROLES    AGE   VERSION
master1.k8s.cluster   Ready    master   49d   v1.17.0
master2.k8s.cluster   Ready    master   49d   v1.17.0
master3.k8s.cluster   Ready    master   49d   v1.17.0
worker1.k8s.cluster   Ready    <none>   49d   v1.17.0
worker2.k8s.cluster   Ready    <none>   49d   v1.17.0
worker3.k8s.cluster   Ready    <none>   49d   v1.17.0_

k8s.cluster is address of haproxy load balancer.

Did I miss something at upgrading or is it a bug?

**Environment:**

Kubernetes version (use kubectl version):

**Client Version**: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**OS** (e.g: cat /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Kernel** (e.g. uname -a):
Linux master1.k8s.cluster 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tedyu** [comment]
```
from version 1.17 to v.1.17
```
Same version appeared twice. Which version did you run before the upgrade ?

Is there anything noticeable in apiserver / controller-manager logs ?

Thanks

**Comment by bojanpog** [comment]
Hello!

Sorry about the version .. before was v1.16
Logs from controller-manager:

I1224 13:26:08.384914       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
I1224 13:26:08.384978       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/kube-controller-manager...
I1224 13:26:08.385007       1 tlsconfig.go:219] Starting DynamicServingCertificateController
E1224 13:27:01.420164       1 leaderelection.go:331] error retrieving resource lock kube-system/kube-controller-manager: etcdserver: request timed out
I1224 13:26:34.370110       1 serving.go:312] Generated self-signed cert in-memory
I1224 13:26:34.703821       1 controllermanager.go:161] Version: v1.17.0
I1224 13:26:34.704485       1 secure_serving.go:178] Serving securely on 127.0.0.1:10257
I1224 13:26:34.704648       1 tlsconfig.go:219] Starting DynamicServingCertificateController
I1224 13:26:34.704702       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
I1224 13:26:34.704708       1 dynamic_cafile_content.go:166] Starting request-header::/etc/kubernetes/pki/front-proxy-ca.crt
I1224 13:26:34.704744       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/kube-controller-manager...
I1224 13:26:34.704746       1 dynamic_cafile_content.go:166] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
W1224 20:47:02.499978       1 garbagecollector.go:639] failed to discover some groups: map[admission.certmanager.k8s.io/v1beta1:the server is currently unable to handle the request]
E1224 20:47:19.618236       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
W1224 20:47:43.303880       1 garbagecollector.go:639] failed to discover some groups: map[admission.certmanager.k8s.io/v1beta1:the server is currently unable to handle the request]
E1224 20:47:55.070227       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
W1224 20:48:24.208028       1 garbagecollector.go:639] failed to discover some groups: map[admission.certmanager.k8s.io/v1beta1:the server is currently unable to handle the request]
E1224 20:48:30.522707       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
W1224 20:49:05.011956       1 garbagecollector.go:639] failed to discover some groups: map[admission.certmanager.k8s.io/v1beta1:the server is currently unable to handle the request]
E1224 20:49:05.977195       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
E1224 20:49:41.429431       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
W1224 20:49:45.374187       1 garbagecollector.go:639] failed to discover some groups: map[admission.certmanager.k8s.io/v1beta1:the server is currently unable to handle the request]
E1224 20:50:16.881446       1 resource_quota_controller.go:407] unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
W1224 20:50:26.278398       1 garbagecollector.go:639] failed to discover some groups: map[admission.certmanager.k8s.io/v1beta1:the server is currently unable to handle the request]

**Comment by bojanpog** [comment]
maybe some additional help - I am using helm and it was installed on version 1.16..

**Comment by neolit123** [comment]
/triage support

> https://k8s.cluster:6443/apis/admission.certmanager.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 5011 milliseconds

>  'Error trying to reach service: 'dial tcp 10.98.247.147:443: i/o timeout''

hi, this is a helm / certmanager issue.

related:
https://github.com/jetstack/cert-manager/issues/2273
https://github.com/helm/charts/issues/10869

you should look for an existing bug in those repositories or open a new one.

thanks.
/close

**Comment by bojanpog** [comment]
updating cert-manager solved my problem. Thank you for your help!
