### ISSUE TITLE
 Could not connect to apt.kubernetes.io:80 (35.201.71.162). - connect (113: No route

### ISSUE THREAD

**Issue by samkrish123** [kubernetes/kubernetes#86608]
I am trying to install kubernetes in my ubutu 18.04, I even tried package.cloud.google.com as well. I guess there is some issue with my server. I disabled windows norton as well.  Did anyone face this issue before. 

sudo apt-add-repository " deb https://packages.cloud.google.com/apt/ kubernetes-xenial main"

 > apt-get update

Error: Unable to connect apt.kubernetes.io.80

root@k8s:/u01/k8s# sudo apt-get update
Hit:1 http://in.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://packages.cloud.google.com/apt kubernetes-xenial InRelease
Hit:5 http://in.archive.ubuntu.com/ubuntu bionic-security InRelease
Err:6 http://apt.kubernetes.io kubernetes-xenial InRelease
  Could not connect to apt.kubernetes.io:80 (35.201.71.162). - connect (113: No route to host)
Reading package lists... Done
W: Failed to fetch http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Could not connect to apt.kubernetes.io:80 (35.201.71.162). - connect (113: No route to host)
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@k8s:/u01/k8s# ssh -i LFS458.pem student@35.226.100.87
Warning: Identity file LFS458.pem not accessible: No such file or directory.
ssh: connect to host 35.226.100.87 port 22: No route to host
root@k8s:/u01/k8s# ssh -i LFS458.pem student@35.201.71.162
Warning: Identity file LFS458.pem not accessible: No such file or directory.
ssh: connect to host 35.201.71.162 port 22: No route to host

**Comment by neolit123** [comment]
/remove-kind failing-test
/triage support

> Error: Unable to connect apt.kubernetes.io.80

hi, this seems like a networking issue and not a k8s bug or feature request.
try searching/posting on stackoverflow or in the k8s slack.

thanks.

/close
