### ISSUE TITLE
'-f' flag in kubectl apply is not working 

### ISSUE THREAD

**Issue by ranjit552** [kubernetes/kubernetes#86617]
**What happened**: I am trying to use kubectl apply in Python the following manner
n = '--namespace mynamespace'
['kubectl', 'create', 'secret', 'generic',mysecret,'--dry-run','-o','yaml',n,'|','kubectl','apply','-f','-',n]
I get an error saying : unknown shorhand f in -f

**Environment**: docker desktop for mac, GKE
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by liggitt** [comment]
Piping (kubectl create ... | kubectl apply ...) depends on interpretation by a shell, and will not work from within a single python invocation like that.

See https://stackoverflow.com/questions/19318859/execute-shell-script-from-python-with-multiple-pipes for an example of using the output of one command as the input to other from Python.

/close
