### ISSUE TITLE
Support passing pod annotations as default options for flexvolumes

### ISSUE THREAD

**Issue by skilxn-go** [kubernetes/kubernetes#86610]
**What would you like to be added**:
**Passing pod annotations to flexvolume plugin as default options**

**Why is this needed**:
For example, we have two disks, each is 100Gi, which are controlled by one single flexvolume driver. And we advertised these two disk info to this node.

When user use this flexvolume, we use a scheduler framework plugin to assign one of the disks to pods ( find a node with enough space, and assign one disk to the pod by updating it's annotation).

But at flexvolume driver side, we can't get the information of which disk has been assigned to this pod for mounting.

So if two pods each cost 20Gi is already on this node, then a pod with 100Gi request comes, we don't know if we can bind this pod to this node for the two disks' usage may be (20Gi, 20Gi which means there is no 100Gi space) or (40Gi, 0Gi which means a total empty disk is available)

Of course, we can use two flex volume drivers, but this forces user to clearly specify one driver, if there is two nodes, one has disk1 empty and the other has disk2 empty, we can't figure this in one pod template event if this pod only needs one disk without caring about the host path.

Currently, only pod.Name and pod.Namespace is passed to the flex volume. We can use this info to query api-server and get the pod spec. However, we have thousands of nodes and tens of thousands of pods in a cluster, it's a huge pressure to api-server for this query. But when the kubelet try to mount a disk using flex volume, it already got the pods' info.

So may be it's a good idea to pass pods annotations to flex volume as default options? Currently, there is no path for passing information from scheduler to kubelet plugins, no matter we use flexvolume or device plugin. Howabout using a key like "kubernetes.io/pod.annotations" and value is the serialized json to plugin, which will not cause compatible problems？

**Comment by liggitt** [comment]
> Currently, only pod.Name and pod.Namespace is passed to the flex volume.

the flex volume options are passed to the driver, right? why wouldn't the required data be specified there, not in pod annotations?

**Comment by skilxn-go** [comment]
@liggitt Thanks for your reply, as I replied in slack, we need some dynamic info to be passed from scheduler plugin to flex volume plugin. Let me declare the  example more clearly. There is one node with two disks, and this two disks is controlled(mount/unmount) by one flex volume driver. Like this fig:
![image](https://user-images.githubusercontent.com/8231208/71494865-5d578680-2885-11ea-95a4-44d5819c6774.png)
If we have already scheduled two pods on this node, there is 3 situations :
![image](https://user-images.githubusercontent.com/8231208/71494879-7829fb00-2885-11ea-9fc0-747d8099ae32.png)
![image](https://user-images.githubusercontent.com/8231208/71494889-80823600-2885-11ea-9c8e-d8d7a640c0a5.png)
![image](https://user-images.githubusercontent.com/8231208/71494893-8aa43480-2885-11ea-8300-99d486eba5a7.png)
It caused by the fact that we can only bind one pod to a node, but we can't pass any information from scheduler to flex driver. So when this two pods are in scheduling, the scheduler can only bind them to this node but have no control for which pod use which node, it's totally controlled by flex volume now.

Then , one pod comes, it claims 80G flex volume storage, the scheduler plugin now can't decide if this pod can be bind to this node. For situation 1, 3 it works, but for situation 2, it can't satisfy the pod's requirement.

**Comment by skilxn-go** [comment]
It can't be done with flex volume options is because that pods's spec can't be updated when scheduling.(except some fields like container images, etc)

**Comment by liggitt** [comment]
It's unclear to me what information you would put in pod annotations that would help the volume driver that couldn't be put in flex volume options. Maybe a concrete example would help understanding. 

I don't anticipate exposing the pod annotation information to volume drivers, but there may be an alternate approach that would make more sense if we understood the use case and desired information better.

**Comment by skilxn-go** [comment]
Thanks, let me say:
We have a big cluster with different types of nodes. Some has 1 ssd, some has 2 or more.
Now we want to use these ssds as a resource, but we don't want to make them as a big network filesystem for best performance.
Meanwhile, we can't use Local PV for the reason that local pv is static, we want to use them dynamically. One pod need 50G ssd while another pod need 50G can be bind to a node with one 100G ssd.
As the pre-declared situations above, our solution is like this:
1. Run a daemon set for expose ssd count and sizes to node label.
2. Use a scheduler plugin to match pods' requirement and nodes' ssd resource.
3. When there multi ssds with enough space in one node, we want to specify which one to use for each pod, otherwise the situation in https://github.com/kubernetes/kubernetes/issues/86610#issuecomment-569157675 will occurs due to scheduler can't control which ssd to use.

now 3 is not achieve-able due to we can't pass info from scheduler to flex volume driver.
And we can't make the decision for which ssd to use in pods' flex volume driver options. Two pods in the same deployment may use different ssd in different nodes, it can't be statically specified. 

Thanks again, and is there any other better solutions for my problem?

**Comment by skilxn-go** [comment]
As I described, I want to put the information of which ssd bind to a scheduled pod in scheduler. And use this information in flex volume driver.

**Comment by liggitt** [comment]
how is the scheduler understanding there are two disks, and the capacities of the two disks, in order to understand how it should pack pods? is that built into your scheduler plugin opaquely, or communicated via resource requests in the pods and custom resource capacities on the node objects?

**Comment by skilxn-go** [comment]
We have some choices to achieve this:

1. Patch resources to nodes api spec
2. Add some unstructured  to node's label/Annotations

So I think it's not a problem. :D

**Comment by skilxn-go** [comment]
@liggitt what do you think about add something like env from source to flex volume options? Which allow users to specify what field to expose flexibility.

**Comment by skilxn-go** [comment]
As I searched a lot of documents/issues about how to pass something from scheduler to flex volume, I fount that the device plugin may have the same requirement in some user cases:
https://github.com/kubernetes/kubernetes/issues/59109

**Comment by gnufied** [comment]
What is being put in annotation that we need to pass to flexvolume driver?

**Comment by riking** [comment]
I think that a KEP for adding scratch SSD support is the right direction here, instead of jumping straight into code.

Another way to think about this is "hardware-backed emptyDir with a resource request", correct? One of the big design points of emptyDir is the assumption that the data you're writing will probably fit in RAM and can be charged against your memory allocation.

**Comment by skilxn-go** [comment]
> What is being put in annotation that we need to pass to flexvolume driver?

@gnufied when there aremulti disks on a node. I want to pass which one should be used by this scheduled pod. It will be write to annotation in scheduler and pass to flexvolume

**Comment by skilxn-go** [comment]
> I think that a KEP for adding scratch SSD support is the right direction here, instead of jumping straight into code.
> 
> Another way to think about this is "hardware-backed emptyDir with a resource request", correct? One of the big design points of emptyDir is the assumption that the data you're writing will probably fit in RAM and can be charged against your memory allocation.

@riking Thanks, I would consider a KEP, and IMO it's not just about the emptydir. The core problem is now we cant bind a local disk to a volume claim (I am not saying pvc) dynamicly, which can only be decided by scheduler.
