### ISSUE TITLE
Scheduler: use the power of two random choices to select nodes

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#86630]
**What would you like to be added**:

[The power of two random choices](https://www.eecs.harvard.edu/~michaelm/postscripts/handbook2001.pdf) has been used in many systems, e.g. [Sparrow: Distributed, Low Latency Scheduling](https://cs.stanford.edu/~matei/papers/2013/sosp_sparrow.pdf), [Nomad](https://www.nomadproject.io/docs/schedulers.html#batch). Kube-schedule could also use it to to limit the number of nodes that are ranked in order to reduce the time for running score plugins significantly.

The main idea is that scheduler chooses two nodes randomly from those nodes filered by filter plugins, then run socre plugins only for the two nodes.

We can implement it as a post-filter plugins with some modification(e.g. `postfilterStatus := g.framework.RunPostFilterPlugins(ctx, state, pod, filteredNodes, filteredNodesStatuses)` => `posfilteredNodes, postfilterStatus := g.framework.RunPostFilterPlugins(ctx, state, pod, filteredNodes, filteredNodesStatuses)`)

**Why is this needed**:

It is very usefully for the batch workload since they are short lived and not so sensitive to that whether it is really the best choice node, by using it kube-scheduler could be used as a batch workload scheduler with higher throughput. And it is also useful for the service workload if they are not so senstive to best choice node.

/sig scheduling
/assign

**Comment by ahg-g** [comment]
-1 to changing PostFilter semantics. PostFilter is not supposed to be a second filtering phase.

We have [PercentageOfNodesToScore](https://github.com/kubernetes/kube-scheduler/blob/master/config/v1alpha1/types.go#L80) flag to control the number of nodes to score, I think it is reasonable to add another one to set an absolute limit (e.g., MaxNodesToScore), and we can validate that one of them is set .

**Comment by hex108** [comment]
> We have PercentageOfNodesToScore flag to control the number of nodes to score, I think it is reasonable to add another one to set an absolute limit (e.g., MaxNodesToScore), and we can validate that one of PercentageOfNodesToScore and MaxNodesToScore is set in ComponentConfig.

I think they have different effects and purposes.
* Suppose that there are 1000 nodes in the cluster, `PercentageOfNodesToScore` is 10, it means that we could stop searching nodes once we found 100 nodes(1000 * 10%) feasible for running a pod. 
* Suppose that `MaxNodesToScore` is 10, if scheduler finds 100 nodes feasible for running a pod, scheduler only need to score 10 nodes of them, and choose the best node whose score is highest. Howerver, how to choose these 10 nodes, by order or randomly?
    
     * If chosing the 10 nodes by order, then it will be same as setting `PercentageOfNodesToScore` to `1`, and scheduler only need to search 10 nodes feasible for running the pod, then score them. But the scheduling effetct will be worse than choosing 100 nodes. 
     * If chosing the 10 nodes randomly from the 100 nodes, the [paper(The Power of Two Random Choices:)](https://www.eecs.harvard.edu/~michaelm/postscripts/handbook2001.pdf) says that it might be enough to choose 2 nodes randomly. And the scheduling effetct is a little worse than scoring 100 nodes, but better than just scoring 10 nodes(in the case that sets `PercentageOfNodesToScore` to `1`).

> -1 to changing PostFilter semantics. PostFilter is not supposed to be a second filtering phase.

Yes, it seems not a good idea. We could disucss it more once we reach a consensus about the above idea.

**Comment by ahg-g** [comment]
> > We have PercentageOfNodesToScore flag to control the number of nodes to score, I think it is reasonable to add another one to set an absolute limit (e.g., MaxNodesToScore), and we can validate that one of PercentageOfNodesToScore and MaxNodesToScore is set in ComponentConfig.
> 
> I think they have different effects and purposes.
> 
> * Suppose that there are 1000 nodes in the cluster, `PercentageOfNodesToScore` is 10, it means that we could stop searching nodes once we found 100 nodes(1000 * 10%) feasible for running a pod.
> * Suppose that `MaxNodesToScore` is 10, if scheduler finds 100 nodes feasible for running a pod, scheduler only need to score 10 nodes of them, and choose the best node whose score is highest. Howerver, how to choose these 10 nodes, by order or randomly?
>   
>   * If chosing the 10 nodes by order, then it will be same as setting `PercentageOfNodesToScore` to `1`, and scheduler only need to search 10 nodes feasible for running the pod, then score them. But the scheduling effetct will be worse than choosing 100 nodes.

Sure, it is the same as setting the percentage of 1%, but that assumes you know how many nodes you have in the cluster when starting up the scheduler, which is not the case in most realistic deployments, and so having an absolute value is difference from setting a percentage.

>   * If chosing the 10 nodes randomly from the 100 nodes, the [paper(The Power of Two Random Choices:)](https://www.eecs.harvard.edu/~michaelm/postscripts/handbook2001.pdf) says that it might be enough to choose 2 nodes randomly. And the scheduling effetct is a little worse than scoring 100 nodes, but better than just scoring 10 nodes(in the case that sets `PercentageOfNodesToScore` to `1`).

I didn't look at the paper you linked to, but suppose that we are filtering the nodes randomly (which is not the case now, but we can look into it), and stop after finding only 2 nodes (set by the new ```MaxNodesToScore``` flag), isn't that the same as identifying some or all feasible nodes first and then choosing two randomly? 

> 
> > -1 to changing PostFilter semantics. PostFilter is not supposed to be a second filtering phase.
> 
> Yes, it seems not a good idea. We could disucss it more once we reach a consensus about the above idea.

Do you mean the idea of scoring just two nodes? If yes, then this is not something new to the scheduler, we already support scoring a limited number of nodes, so nothing new to agree on.

**Comment by hex108** [comment]
> Sure, it is the same as setting the percentage of 1%, but that assumes you know how many nodes you have in the cluster when starting up the scheduler, which is not the case in most realistic deployments, and so having an absolute value is difference from setting a percentage.

Agree with it, an absolute limit is different with percentage, and we could add it.

> I didn't look at the paper you linked to, but suppose that we are filtering the nodes randomly (which is not the case now, but we can look into it), and stop after finding only 2 nodes (set by the new MaxNodesToScore flag), isn't that the same as identifying some or all feasible nodes first and then choosing two randomly?

I think it is same(I need to look into it). Then we need to figure out how to filter the nodes randomly, it might not be easy to adopt it to the scheduler framework. At the same time, it seems easier to add a plugin that choose 2 nodes randomly from the filtered nodes.

>  Do you mean the idea of scoring just two nodes? 

Yes, but these two nodes need to be choosed randomly.

> If yes, then this is not something new to the scheduler, we already support scoring a limited number of nodes, so nothing new to agree on.

Is it limited by `PercentageOfNodesToScore` or other options?

**Comment by ahg-g** [comment]
>At the same time, it seems easier to add a plugin that choose 2 nodes randomly from the filtered nodes.

Yes, you can do that with a Filter, but you need to make sure it is the last Filter to be executed.

**Comment by ahg-g** [comment]
> Is it limited by PercentageOfNodesToScore or other options?

We can have other options, isn't this what we are trying to discuss already? 

There are two issues here:
1) Limiting the number of nodes to score as a concept (whether limiting it to two or or more)
2) How to choose the nodes 

The sentence **" We could disucss it more once we reach a consensus about the above idea."** was  confusing because you seem to suggest that we should defer discussing issue 2 to later until we agree on issue 1, and what I wanted to say is that issue 1 is something we already agree on because it is already supported in some form in the scheduler, so what is left is discussing how to choose the nodes in a more generic way (or perhaps more than one way).

**Comment by hex108** [comment]
> so what is left is discussing how to choose the nodes in a more generic way (or perhaps more than one way).

Get your point now, agree with it!

> 1. Limiting the number of nodes to score as a concept (whether limiting it to two or or more)
> 2. How to choose the nodes

As disscussed above, I think we could do both of them, because they are different and both are useful.

* Add an absolute limit `MaxNodesToScore`, and filter nodes in the same way as now.

* Choose two nodes randomly from filtered node, and only score the two nodes. It is more appropriate for short live jobs.

**Comment by ahg-g** [comment]
> * Add an absolute limit `MaxNodesToScore`, and filter nodes in the same way as now.
> * Choose two nodes randomly from filtered node, and only score the two nodes. It is more appropriate for short live jobs.

Why do you need the second one if the first is able to give you (assume randomly) two nodes to score from the get go?

**Comment by hex108** [comment]
Yes, we do not need the second one if the first one choose node randomly.

**Comment by ahg-g** [comment]
/cc @alculquicondor 

Aldo has another use case for changing the post filter extension point to act as a second filtering phase, perhaps it is worth doing. We could preserve the current semantics of PostFilter and rename it  to PreScore, and add a new PostFilter with the semantics suggested here (or something similar).

**Comment by alculquicondor** [comment]
My thoughts on the algorithmic implications (not implementation details).

I can see 2 benefits of introducing random choices:

- Increased performance of scoring.
- Reduced over-fitting, which we do by scoring a big number of nodes and only selecting the absolute maximum.

Now, if we aim for even better performance, a random shuffle **before filtering** might be an interesting thing to explore. FTR, our current heuristic is a window on a fixed order of nodes. Naturally, we would still run through all the nodes in some scenarios.

Now, just to challenge the applicability of the paper to k8s scheduler. Section 1.1.3 talks specifically about maintaining (1) a low load on each cluster and (2) considering all the items weigh the same. I must admit that I didn't read the whole survey thoroughly, but we have different requirements: (1) other scores, (2) pods weigh different from each other. Do we know if the survey (or some other work) also talks about more general weights?

**Comment by hex108** [comment]
/remove-lifecycle rotten

I'll do it in following days.

**Comment by yuanchen8911** [comment]
With the scheduling framework and plugin, we can introduce another scheduling parameter  _numFeasibleNodesToFind_ for each scheduler profile, which specifies how many feasible nodes Filter plugins should return (stop after it find so many nodes). We can set the number as 2 and implement the better of 2 random choices scheduling algorithm. 
#93270

**Comment by alculquicondor** [comment]
If we go with that and set numFeasibleNodesToFind=2, there is no need for any extra logic. Best of 2 is what the scoring plugins would do.

**Comment by alculquicondor** [comment]
Oh, I forgot about the "random" part. That wouldn't be possible with the current framework.

**Comment by Huang-Wei** [comment]
> Oh, I forgot about the "random" part. That wouldn't be possible with the current framework.

Currently, it's a bit "random" already - node is popped from a "topology tree list" maintained in the internal cache. But we can argue that it's not "random" enough.

Apart from the "random" part, the idea of "MaxNodesToScore" (or "numFeasibleNodesToFind") should be easy to accommodate, isn't it? (let me know if i miss anything) - just tweak the `numNodesToFind` abtain logic to:

`numNodesToFind := min(g.numFeasibleNodesToFind(), prof.MaxNodesToScore`:

https://github.com/kubernetes/kubernetes/blob/02cf58102a61b6d1e021e256381ff750573ce55d/pkg/scheduler/core/generic_scheduler.go#L299

---

Another thought is: do we need **two** arguments - `PercentageOfNodesToScore` **and** `MaxNodesToScore`?  is it an AND or OR relation? If it's the latter, in Kubernetes, we can use an internal `IntOrString` to represent its semantics - i.e., we can clearly tell from the given value it's a percentage or absolute number ("10%" or "10").

**Comment by xq2005** [comment]
> Another thought is: do we need **two** arguments - `PercentageOfNodesToScore` **and** `MaxNodesToScore`? is it an AND or OR relation? If it's the latter, in Kubernetes, we can use an internal `IntOrString` to represent its semantics - i.e., we can clearly tell from the given value it's a percentage or absolute number ("10%" or "10").

How about moving `MaxNodesToScore` into internal using and adding another profile-level parameter `RandomShuffling` that can enable/disable the random shuffle before filtering. When `RandomShuffling` is enable, `MaxNodesToScore` is set to 2. If not `MaxNodesToScore` will equal to `PercentageOfNodesToScore` * `Number of Nodes.`

**Comment by alculquicondor** [comment]
I don't think you would want to forcibly link RandomShuffling to MaxNodesToScore=2. As I said before, the mentioned paper only refers to load balancing. But several other scores in kube-scheduler.

**Comment by hex108** [comment]
> we can use an internal IntOrString to represent its semantics

+1 for the idea! And yes, it is easy to accommodate :)

> Currently, it's a bit "random" already - node is popped from a "topology tree list" maintained in the internal cache. But we can argue that it's not "random" enough.

Yes, it's a bit "random" now. If we could implement the random part, it would be better.

> As I said before, the mentioned paper only refers to load balancing. But several other scores in kube-scheduler.

We could calculate scores for the two nodes chosen by random algorithm. The Sparrow paper does not metion it, howerver Nomad(https://www.nomadproject.io/docs/schedulers.html#batch) implements it in this way.

**Comment by alculquicondor** [comment]
That's probably not too bad if you are not using node affinity or pod spreading. On the other hand, some users rather want tight bin packing, which is rather the opposite from load balancing.

What I'm saying is that you might be ok with having it set to 2 for your use case, but it's probably not enough for all users.

**Comment by Huang-Wei** [comment]
> That's probably not too bad if you are not using node affinity or pod spreading.

It's bit of ok even if they use node affinity or pod spreading. But users should be aware of that the "heavy" work is done in the PreFitler phase, so they **may** not see their expected performance boost.

> On the other hand, some users rather want tight bin packing, which is rather the opposite from load balancing.

Agree, so if we go with this, this should be a profile-level argument, not global.
