### ISSUE TITLE
TestCommonKindsRegistered failing on release-1.17 as flowcontrol is not registered

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/kubernetes#86644]
**What happened**:
`TestCommonKindsRegistered ` is failiing on [release-1.17](https://github.com/kubernetes/kubernetes/tree/7d04da8a4a80f22b1a165edb36a02aa9e01514cf).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Run command `make test` on release-1.17.

**Anything else we need to know?**:
Master is ok, and this test has been removed by https://github.com/kubernetes/kubernetes/pull/86256.

Should we cherry-pick #86256 to release-1.17?

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux ecs-d8b6 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by RainbowMango** [comment]
cc @yue9944882  Any comments? :)

**Comment by neolit123** [comment]
/sig api-machinery
/remove-kind bug
/kind failing-test

> TestCommonKindsRegistered is failiing on release-1.17.

i can confirm that it fails with `make test`:
but i couldn't get it to fail with:
`go test ./pkg/api/testing/... -count=1`

> Should we cherry-pick #86256 to release-1.17?

you can try asking in #sig-api-machinery, but people are on holidays right now.

**Comment by liggitt** [comment]
> Should we cherry-pick #86256 to release-1.17?

that is larger than I would expect in a cherry-pick. https://github.com/kubernetes/kubernetes/pull/86252 is a more minimal fix we could pick to release-1.17

**Comment by RainbowMango** [comment]
Great!  I will have a try.

I have a question, #86252 has been closed and the branch has been deleted too, so, how can I get the commit? Is there a guide for this?  

I also not sure if the cherry_pick_pull.sh could handle this case.

**Comment by neolit123** [comment]
> I have a question, #86252 has been closed and the branch has been deleted too, so, how can I get the commit? Is there a guide for this?

```
wget https://github.com/kubernetes/kubernetes/pull/86252.patch
git am 86252.patch
# to see the commit
git log -1 
```

> I also not sure if the cherry_pick_pull.sh could handle this case

it can.

**Comment by RainbowMango** [comment]
I tested #86252 and it works.  See #86649.

Thanks @neolit123 @liggitt. 

> but i couldn't get it to fail with:
go test ./pkg/api/testing/... -count=1

By the way, if run the test with `go test` it won't fail. I have no clue. I guess this due to some env set by `hack/make-rules/test.sh`.

**Comment by fedebongio** [comment]
The fix was already cherrypicked, closing.
/close
