### ISSUE TITLE
Is there any plan for secret/configmap status?

### ISSUE THREAD

**Issue by yttan** [kubernetes/kubernetes#86642]
There is no way to find out if a secret/configmap is used by a pod or not for now. 
Is there any plan for adding a status like PVC's Bound/Available? 
Or can you tell me why you decide not to have a status for  secret/configmap?

A user case example:

I have a test secret.
```
NAME                  TYPE                                  DATA   AGE
test-secret           Opaque                                1      18m
```
And I have a deployment using this secret.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: yuting
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: docker-user.cambricon.com:30080/cambricon/test-ubuntu-apache-nettools:v0.0.4
        imagePullPolicy: Always
        name: a
        volumeMounts:
        - name: foo
          mountPath: "/home"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: test-secret
```
 The deployment has a runing pod.
```
NAME                    READY   STATUS    RESTARTS   AGE
test-847658dfdf-2rmg2   1/1     Running   0          8m16s
```

While the pod is still running, I delete the secret. It was deleted successfully. The pod is still running. And then I delete the pod. Because it's a deployment, the replication controller gives a new pod. The new one got stuck in ContainerCreating becauser of failed mount.
```
NAME                    READY   STATUS              RESTARTS   AGE
test-847658dfdf-krfcv   0/1     ContainerCreating   0          4m38s
```
```
Events:
  Type     Reason       Age                   From                Message
  ----     ------       ----                  ----                -------
  Normal   Scheduled    4m48s                 default-scheduler   Successfully assigned yuting/test-847658dfdf-krfcv to machine33
  Warning  FailedMount  43s (x10 over 4m53s)  kubelet, machine33  MountVolume.SetUp failed for volume "foo" : secret "test-secret" not found
  Warning  FailedMount  34s (x2 over 2m50s)   kubelet, machine33  Unable to mount volumes for pod "test-847658dfdf-krfcv_yuting(17a20af9-27dd-11ea-8c09-ac1f6ba56e8a)": timeout expired waiting for volumes to attach or mount for pod "yuting"/"test-847658dfdf-krfcv". list of unmounted volumes=[foo]. list of unattached volumes=[foo default-token-2mm44]
```

I think in this example Kubernetes should at least prevent the user from deleting the secret as it is being used by a deployment. If there is a status showing a secret/configmap is used or not, it would be easier to manage a large number of  secrets/configmaps in a large scale cluster

**Comment by liggitt** [comment]
there is no plan to add status to these objects. since these are 1:many, status does not make as much sense as PV/PVC, which are 1:1

/close
