### ISSUE TITLE
Error message from updating pod should be better

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#8668]
Tried to update a pod's environment and got a terrible error message.  For the "invalid change to updated pod" we need to not print out Go formatted log, but instead something much more specific if possible.  The client almost always has their own object available.

```
Error: Pod "database-2-kmnfk" is invalid: spec: invalid value {Volumes:<nil> Containers:[{Name:ruby-helloworld-database Image:openshift/mysql-55-centos7:latest Command:<nil> Args:<nil> WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:3306 Protocol:TCP HostIP:}] Env:[{Name:MYSQL_USER Value:userBFY ValueFrom:<nil>} {Name:MYSQL_PASSWORD Value:TJlaMIml ValueFrom:<nil>} {Name:MYSQL_DATABASE Value:root ValueFrom:<nil>} {Name:A Value:C ValueFrom:<nil>}] Resources:{Limits:<nil> Requests:<nil>} VolumeMounts:<nil> LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:<*>(0xc20af1bd40){Capabilities:<*>(0xc21093a8a0){Add:<nil> Drop:<nil>} Privileged:<*>(0xc20c10bc7a)false SELinuxOptions:<nil> RunAsUser:<nil>}}] RestartPolicy:Always TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccount: Host:openshiftdev.local HostNetwork:false}
```

**Comment by caesarxuchao** [comment]
@smarterclayton, could you elaborate on how to reproduce this error message? I don's see why your []Env is wrong.
And what error message do you expect? Something that tells you why the []Env is invalid?

FWIW, #9803 should remove the long spec if we append a more specific error.

**Comment by smarterclayton** [comment]
I was changing the env of an existing, scheduled pod.

**Comment by caesarxuchao** [comment]
Hi @smarterclayton, I tried on HEAD, it seems the problem has been fixed. Here's what I did:
I created a pod, then modified one of it's env var, and use `kubectl update` to update it, and I got this response:

```
Replace failed: may not update fields other than container.image
```
which seems to be a clear error message to me. What do you think?

**Comment by smarterclayton** [comment]
Sounds good, as long as the API is returning that (not the client side).

On Jul 6, 2015, at 1:16 PM, Chao Xu <notifications@github.com> wrote:

Hi @smarterclayton <https://github.com/smarterclayton>, I tried on HEAD, it
seems the problem has been fixed. Here's what I did:
I created a pod, then modified one of it's env var, and use kubectl update
to update it, and I got this response:

Replace failed: may not update fields other than container.image

which seems to be a clear error message to me. What do you think?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/8668#issuecomment-118928488>
.

**Comment by caesarxuchao** [comment]
Unfortunately, #9803 is a client side trick that extracts this neat error message from a messy response. The response from the apiserver includes a full spec of the object and this error message appended at the end.

**Comment by smarterclayton** [comment]
Doesn't seem very useful.  The server doesn't (and shouldn't) print the
object the user sends back - would prefer we shorten that so all API
clients have something to show to a user:

On Jul 6, 2015, at 7:40 PM, Chao Xu <notifications@github.com> wrote:

Unfortunately, #9803
<https://github.com/GoogleCloudPlatform/kubernetes/pull/9803> is a client
side trick that extracts this neat error message from a messy response. The
response from the apiserver includes a full spec of the object and this
error message appended at the end.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/8668#issuecomment-119028212>
.

**Comment by bgrant0607** [comment]
See also #14102

**Comment by smarterclayton** [comment]
It's better, but still ugly.  But not terrible.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (172/150 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:36310 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dGU8E-000QPw-6k
	for dev@imwiz.com; Thu, 01 Jun 2017 11:43:34 -0600
Date: Thu, 01 Jun 2017 10:35:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1496338500;
	bh=hk8BOkk3Sb+Qmb2qigxzFLjxRmMa6lBmrf6UHAIw3lU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=16Z66jqUKeNrhjRfUOyhZfODZOYjbOLNFtO00hS8nH6X3jYqK2ZkWk5GvL4g6drvm
	 FQqXrkG4YfKTCKvcQKvwIU1yFnrcFv1dlGl1lLuWyY50xEXkfwbRMgPWHFYt+Y13PI
	 jOhD7EpLr5fNVqeQjUeIjU80El79kLNrJYBKKB2Q=
