### ISSUE TITLE
[Win10] kubectl port-forward background fails

### ISSUE THREAD

**Issue by ALINRUISU** [kubernetes/kubernetes#86697]
**What happened**: I tired to port-forward my elastic search pods to 9200 and run it on the background using &, however, it seems like it does not work for window hosts

**What you expected to happen**: port-forward works and is exposes 9200 on the background.  

**How to reproduce it (as minimally and precisely as possible)**: Please see sample copy & pasta 

```
PS C:\Users\psyduck\charts\elastic> kubectl port-forward service/elasticsearch-master 9200 -n ame
Forwarding from 127.0.0.1:9200 -> 9200
Forwarding from [::1]:9200 -> 9200
PS C:\Users\psyduck\charts\elastic> kubectl port-forward service/elasticsearch-master 9200 -n ame &
At line:1 char:63
+ kubectl port-forward service/elasticsearch-master 9200 -n ame &
+                                                               ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\Users\psyduck\charts\elastic> kubectl port-forward service/elasticsearch-master 9200 -n ame "&"
error: Service 'elasticsearch-master' does not have a named port '&'
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.17
- Cloud provider or hardware configuration: Minikube
- OS (e.g: `cat /etc/os-release`):Windows
- Kernel (e.g. `uname -a`):
- Install tools:Kubectl install from chocolatey
- Network plugin and version (if this is a network-related bug):n/a
- Others:n/a

**Comment by gab-satchi** [comment]
Hey @ALINRUISU, the ampersand doesn't work on PowerShell to background a process. You can try the solutions listed here: https://stackoverflow.com/questions/185575/powershell-equivalent-of-bash-ampersand-for-forking-running-background-proce

`Start-Process` is a good alternative as it will also print to stdout.
