### ISSUE TITLE
Sanitize certificate input during import or before comparison

### ISSUE THREAD

**Issue by coboluxx** [kubernetes/kubernetes#86695]
**What happened**:
CA validation code fails for a valid input file while trying to initialize a new cluster with an external CA by running kubeadm init.

**What you expected to happen**:
No error.

**How to reproduce it (as minimally and precisely as possible)**:
Prepare an external CA for a new cluster (https://kubernetes.io/docs/setup/best-practices/certificates/).

Create the admin certificate. Place a newline in front of the pem encoded text of your ca file (/etc/kubernetes/pki/ca.crt).  Generate admin.conf:

```
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config set-cluster defaul-cluster --server=https://myip:6443 --certificate-authority /etc/kubernetes/pki/ca.crt --embed-certs
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config set-credentials default-admin --client-key admin-certificate.key --client-certificate admin-certificate.crt --embed-certs
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config set-context default-system --cluster default-cluster --user default-admin
KUBECONFIG=/etc/kubernetes/admin.conf kubectl config use-context default-system
```

Try `kubeadm init`

You will see a message like "admin.conf does not exist or is invalid". Running

`kubeadm init phase certs ca`

will give you more details:

> W1229 01:50:57.406710     684 validation.go:28] Cannot validate kube-proxy config - no validator is available
> W1229 01:50:57.406775     684 validation.go:28] Cannot validate kubelet config - no validator is available
> the admin.conf file does not exists or it is not valid: a kubeconfig file "/etc/kubernetes/admin.conf" exists already but has got the wrong CA cert

The errors is thrown in kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go line 236 (1.17).

Removing the newline fixes the problem. The responsible code should parse the certificate and compare the certificates properties or at least compare a sanitized string version.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7.7.1908
- Kernel (e.g. `uname -a`): 3.10.0-1062.el7.x86_64
- Install tools: -
- Network plugin and version (if this is a network-related bug): -
- Others: -

**Comment by neolit123** [comment]
please open this issue in the kubernetes/kubeadm repository where the kubeadm issue tracker resides.

thank you.
/area kubeadm
/close
