### ISSUE TITLE
Break Filter plugins dependency on PredicateFailureReason [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#86711]
/sig scheduling
/assign

This is apart from the Predicates that we can't move now because Kubelet and DaemonSet controller currently depends on.

Part of #85822

**Comment by haosdent** [comment]
For PredicateFailureReason, I think we could move the `pkg/scheduler/algorithm/predicates/error.go` to `pkg/scheduler/framework/plugins/helper`.

**Comment by haosdent** [comment]
Is it OK for you? @ahg-g

**Comment by ahg-g** [comment]
No, we should keep plugins/helper as light as possible, and there is no need to put all failure reasons in one place, see comment here: https://github.com/kubernetes/kubernetes/issues/86712#issuecomment-570214164

**Comment by haosdent** [comment]
got it, thx @ahg-g

**Comment by haosdent** [comment]
Hi, @ahg-g Now the rest filter plugins depends on `predicates` package are

```
pkg/scheduler/framework/plugins/nodeaffinity
pkg/scheduler/framework/plugins/nodename
pkg/scheduler/framework/plugins/nodeports
pkg/scheduler/framework/plugins/noderesources
```

They could not move methods from `predicates` package to their own filter packages due to

```
# ./pkg/scheduler/algorithm/predicates/predicates.go
func GeneralPredicates(pod *v1.Pod, meta Metadata, nodeInfo *schedulernodeinfo.NodeInfo) (bool, []PredicateFailureReason, error) {
	var predicateFails []PredicateFailureReason
	for _, predicate := range []FitPredicate{PodFitsResources, PodFitsHost, PodFitsHostPorts, PodMatchNodeSelector} {
```

Do you have any suggestions to move this forward? Thank you in advance.
