### ISSUE TITLE
remove TODO in test/e2e/framework/auth/helpers

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kubernetes#86721]
**What happened**:

There are some TODO in  test/e2e/framework/auth/helpers

```
// logf logs INFO lines to the GinkgoWriter.
// TODO: Log functions like these should be put into their own package,
// see: https://github.com/kubernetes/kubernetes/issues/76728
func logf(format string, args ...interface{}) {
	log("INFO", format, args...)
}

// log prints formatted log messages to the global GinkgoWriter.
// TODO: Log functions like these should be put into their own package,
// see: https://github.com/kubernetes/kubernetes/issues/76728
func log(level string, format string, args ...interface{}) {
	fmt.Fprintf(ginkgo.GinkgoWriter, nowStamp()+": "+level+": "+format+"\n", args...)
}

// nowStamp returns the current time formatted for placement in the logs (time.StampMilli).
// TODO: If only used for logging, this should be put into a logging package,
// see: https://github.com/kubernetes/kubernetes/issues/76728
func nowStamp() string {
	return time.Now().Format(time.StampMilli)
}

```

**What you expected to happen**:

solve it

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tanjunchen** [comment]
area/e2e-test-framework

**Comment by neolit123** [comment]
the `helpers.go` file should import `"k8s.io/kubernetes/test/e2e/framework"`
and use this function instead:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/log.go#L41
