### ISSUE TITLE
marshal ObjectMeta always prints `proto: tag has too few fields: "-"` error

### ISSUE THREAD

**Issue by elfinhe** [kubernetes/kubernetes#86739]
**What happened**:
By [marshaling](https://github.com/gogo/protobuf/blob/master/jsonpb/jsonpb.go#L142) time.Time with gogo/protobuf, our istioctl CLI always prints the this message into stderr:
```
proto: tag has too few fields: "-"
```
My guess - there might be some typo here in the tag of time.Time:
https://github.com/kubernetes/apimachinery/blame/master/pkg/apis/meta/v1/time.go#L34
where the gogo/protobuf will validate it (`protobuf:"-"`). Please help double check if the tag is correct.

More context: https://github.com/istio/istio/issues/19735

**What you expected to happen**: 
gogo/protobuf parsing tag error message is not shown.  

**How to reproduce it (as minimally and precisely as possible)**:
marshal an ObjectMeta with gogo/protobuf's  MarshalToString.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jennybuckley** [comment]
Adding proto tags to metav1.Time probably wouldn't fix this, snice metav1.Time has a custom protobuf marshaller function: 
https://github.com/kubernetes/kubernetes/blob/4f1daf0cf30dbb119f670ace1c2e1b4eabbc030d/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto.go#L78-L84

**Comment by howardjohn** [comment]
We are operating on arbitrary proto messages, so we cannot just call `.Marshal()` is my understanding. I would think that jsonpb would call the custom marshal method though, but perhaps I am understanding how everything works together.

**Comment by jennybuckley** [comment]
From the linked bug, it looks like it's calling MarshalToString like [this](https://github.com/istio/operator/blob/f623b65d63f2b3fa68efcea9e89090b4b3fb65b3/cmd/mesh/manifest-migrate.go#L105-L108):
```
isCP := &v1alpha2.IstioControlPlane{Spec: translatedICPS, Kind: "IstioControlPlane", ApiVersion: "install.istio.io/v1alpha2"}

ms := jsonpb.Marshaler{}
gotString, err := ms.MarshalToString(isCP)
```

in order to convert isCP to serialized JSON. I was wondering why we can't just call json.Marshal() on isCP instead

**Comment by esnible** [comment]
I took a look at this.  The problem can be reproduced with this code:

```
import (
	"github.com/gogo/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
...
	_ = proto.GetProperties(reflect.TypeOf(metav1.Time{}))
```

Is `protobuf:"-"` a valid tag?  If so, fix https://github.com/gogo/protobuf/blob/master/proto/properties.go#L368 so that it ignores `"-"` the same way it ignores `""`.   If not, replace `"-"` with something valid.
