### ISSUE TITLE
GCE load-balancer should have a node health-check

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8673]
That way it will not balance to nodes that are in trouble.  A simple internal healthz should suffice.

**Comment by roberthbailey** [comment]
Should we health check the kubelet or the kube-proxy (or both)?

**Comment by thockin** [comment]
Honestly I think kube-proxy is more valuable, but simply "anything on the
host" would be a good first cut. :)

**Comment by thockin** [comment]
Dup #14661
