### ISSUE TITLE
1.17: calico-kube-controllers CrashLoopBackoff

### ISSUE THREAD

**Issue by AndreyMaltsev** [kubernetes/kubernetes#86735]
When I run command kubectl get pods --all-namespaces,  there is ERROR  -> kube-system   calico-kube-controllers-648f4868b8-dbkbx    0/1   has STATUS  CrashLoopBackOff.
I installed the next v.  Using Kubernetes version: v1.17.0. OS - CentOS 8.0

I am a new in Kubernetes\Docker - have no idea what is wrong here and where should I check the issie.
Regards, Andre

**Comment by neolit123** [comment]
hi,
what deployer are you using to create this cluster?

if using kubeadm please read this guide for Calico:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

did you apply Calico with this command:
> kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml

this should pull the latest 3.8 (which is 3.8.5 ATM).
3.8* works fine with k8s 1.17.

if you are having troubles with Calico, please tear down the cluster and apply a different CNI plugin like WeaveNet.

**Comment by AndreyMaltsev** [comment]
Thanks so much neolit123. I will apply your solution and post here the results

**Comment by hochan222** [comment]
Hi!
Have you ever checked the calico version?
Google top link & kubernetes sites link the old version, check it out.

Here is latest version site!
> https://docs.projectcalico.org/v3.11/getting-started/kubernetes/installation/calico
