### ISSUE TITLE
can‘t download any binary release package 

### ISSUE THREAD

**Issue by John402-cloud** [kubernetes/kubernetes#86741]

**Comment by John402-cloud** [comment]
I need kubernetes package to practise，but i find any binary kubernetes package can not be downloaded.

**Comment by neolit123** [comment]
the binaries are in the changelog:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#downloads-for-v1170

you can also install some of them as Debian / RPM packages:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

/close
