### ISSUE TITLE
Build kubernetes for mips64le

### ISSUE THREAD

**Issue by huchengze** [kubernetes/kubernetes#86749]
**What would you like to be added**:
Support for mips64le.

When I tried to build kubernetes for  mips64le, I found that for these components:

```
cmd/kubelet
cmd/hyperkube
cmd/genkubedocs
cmd/genman
test/e2e/e2e.test
cmd/kubemark
test/e2e_node/e2e_node.test
```

This error is reported when the make command is executed：

```
# k8s.io/kubernetes/vendor/github.com/google/cadvisor/fs
vendor/github.com/google/cadvisor/fs/fs.go:513:20: cannot use buf.Dev (type uint32) as type uint64 in argument to major
vendor/github.com/google/cadvisor/fs/fs.go:514:20: cannot use buf.Dev (type uint32) as type uint64 in argument to minor
vendor/github.com/google/cadvisor/fs/fs.go:755:65: cannot use buf.Dev (type uint32) as type uint64 in argument to major
vendor/github.com/google/cadvisor/fs/fs.go:755:86: cannot use buf.Dev (type uint32) as type uint64 in argument to minor
vendor/github.com/google/cadvisor/fs/fs.go:756:66: cannot use buf.Rdev (type uint32) as type uint64 in argument to major
vendor/github.com/google/cadvisor/fs/fs.go:756:88: cannot use buf.Rdev (type uint32) as type uint64 in argument to minor
vendor/github.com/google/cadvisor/fs/fs.go:758:23: cannot use buf.Dev (type uint32) as type uint64 in argument to major
vendor/github.com/google/cadvisor/fs/fs.go:758:44: cannot use buf.Dev (type uint32) as type uint64 in argument to minor
```

The reason I found that there would be such an error is:

https://github.com/golang/go/issues/16500#issuecomment-235288559

Then I edited the file（vendor/github.com/google/cadvisor/fs/fs.go） like this：

```diff
-     buf.Dev
+     uint64(buf.Dev)
-     buf.Rdev
+     uint64(buf.Rdev)
```

And the build can be implemented after this modification.

Do I need to submit changes under the [cadvisor](https://github.com/google/cadvisor)?Or I just submit changes in kubernetes.

And if I submit changes under the [cadvisor](https://github.com/google/cadvisor), when will kubernetes synchronize cadvisor changes to vendor?

**Comment by dims** [comment]
yes, please submit to cadvisor. we periodically re-sync the vendor directory

**Comment by neolit123** [comment]
/remove-wg component-standard
/remove feature
/kind bug
/priority backlog

cc @kubernetes/dep-approvers

**Comment by huchengze** [comment]
@dims Thank you and I just creat this [pr](https://github.com/google/cadvisor/pull/2368).

**Comment by huchengze** [comment]
> yes, please submit to cadvisor. we periodically re-sync the vendor directory

This PR was merged. What are the specific periodic rules for vendor re-sync? I'm going to submit another PR based on this.

**Comment by BenTheElder** [comment]
aside: IMHO the title of this issue is a feature but the problem mentioned with mismatched uint sizes in cadvisor is a bug 🙃
