### ISSUE TITLE
Endpoints Controller should not include pods that are not ready or not healthy

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8674]
Ideally that includes when a node is not reachable but not yet timed out.

**Comment by bgrant0607** [comment]
Not-ready pods are removed, but pods on unreachable nodes are not.

This affects replication controller, too. A solution that updated the pod status would work for both. Probably the node controller should do that.

**Comment by lavalamp** [comment]
Please no solution that requires endpoints controller to watch nodes...

**Comment by thockin** [comment]
My thought was simply to look at Pod conditions in EP controller.

**Comment by bgrant0607** [comment]
EP controller already looks at pod conditions.

**Comment by mikedanese** [comment]
I think this can be closed.
