### ISSUE TITLE
Code-generator does not work outside of $GOPATH

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#86753]
**What happened**:
`k8s.io/code-generator` is not able to generate code for projects using Go modules (cloned outside $GOPATH).

**What you expected to happen**:
`k8s.io/code-generator` to be able to generate code for projects using Go modules (cloned outside $GOPATH).

**How to reproduce it (as minimally and precisely as possible)**:
#### 1. k8s.io/sample-apiserver located in $GOPATH

1. Setup `k8s.io/sample-apiserver` in $GOPATH
```
$ mkdir -p $GOPATH/src/k8s.io/
$ cd $GOPATH/src/k8s.io/
$ git clone git@github.com:kubernetes/sample-apiserver.git
$ cd sample-apiserver
$ go mod vendor
```

2. Remove the generated code
```
$ rm -rf pkg/generated/
$ git diff --shortstat
 38 files changed, 5407 deletions(-)
```

3.  And generate it once again
```
$ ./hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for wardle:v1alpha1,v1beta1 at k8s.io/sample-apiserver/pkg/generated/clientset
Generating listers for wardle:v1alpha1,v1beta1 at k8s.io/sample-apiserver/pkg/generated/listers
Generating informers for wardle:v1alpha1,v1beta1 at k8s.io/sample-apiserver/pkg/generated/informers
go: directory ../code-generator/cmd/defaulter-gen outside available modules
go: directory ../code-generator/cmd/conversion-gen outside available modules
go: directory ../code-generator/cmd/client-gen outside available modules
go: directory ../code-generator/cmd/lister-gen outside available modules
go: directory ../code-generator/cmd/informer-gen outside available modules
go: directory ../code-generator/cmd/deepcopy-gen outside available modules
go: directory ../code-generator/cmd/openapi-gen outside available modules
```

4. Ensure that the generation works
```
$ git diff --shortstat
 1 file changed, 6 insertions(+)
```

#### 2. k8s.io/sample-apiserver located outside $GOPATH

1. Setup `k8s.io/sample-apiserver` outside $GOPATH
```
$ cd $HOME/git/
$ git clone git@github.com:kubernetes/sample-apiserver.git
$ cd sample-apiserver
$ go mod vendor
```

2. Remove the generated code
```
$ rm -rf pkg/generated/
$ git diff --shortstat
 38 files changed, 5407 deletions(-)
```

3.  And generate it once again
```
$ ./hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for wardle:v1alpha1,v1beta1 at k8s.io/sample-apiserver/pkg/generated/clientset
Generating listers for wardle:v1alpha1,v1beta1 at k8s.io/sample-apiserver/pkg/generated/listers
Generating informers for wardle:v1alpha1,v1beta1 at k8s.io/sample-apiserver/pkg/generated/informers
go: directory ../code-generator/cmd/defaulter-gen outside available modules
go: directory ../code-generator/cmd/conversion-gen outside available modules
go: directory ../code-generator/cmd/client-gen outside available modules
go: directory ../code-generator/cmd/lister-gen outside available modules
go: directory ../code-generator/cmd/informer-gen outside available modules
go: directory ../code-generator/cmd/deepcopy-gen outside available modules
go: directory ../code-generator/cmd/openapi-gen outside available modules
```

4. Ensure that the generation generated nothing
```
$ git diff --shortstat
 39 files changed, 1 insertion(+), 5407 deletions(-)
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ialidzhikov** [comment]
/area code-generation
/sig api-machinery

cc @nikhita

**Comment by liggitt** [comment]
Potential fix in https://github.com/kubernetes/kubernetes/pull/85559

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/82531#issuecomment-781806805 cc @liggitt

**Comment by palnabarun** [comment]
/assign

I will take a look at it.

**Comment by zwpaper** [comment]
how about rewriting this even further to use go 1.18 generics?

**Comment by liggitt** [comment]
resolved by https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/4402-go-workspaces
