### ISSUE TITLE
"container init exited prematurely" after OOMKilled

### ISSUE THREAD

**Issue by devopsgoat** [kubernetes/kubernetes#86776]
**What happened**:

After a container in a pod has been OOMKilled it fails to restart. The message is "oci runtime error: container_linux.go:247: starting container process caused "container init exited prematurely"

Deleting the pod will create a new pod which will start with no issues.

**What you expected to happen**:

The container should restart with no issues.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The pod consists of a main container and 3 sidecar containers which share emptydir volumes with the main container. There is a ConfigMap which has keys mounted as 5 separate volumeMounts in the main container.

I have enabled docker debug on the node with the failing container. This shows no further info on the error. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
aws
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`):
Linux ip-10-20-100-180.eu-west-1.compute.internal 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sftim** [comment]
@devopsgoat would you be able to add sample manifests that someone can apply to try to reproduce the issue?

**Comment by devopsgoat** [comment]
Hi. This is a sample manifest with some values sanitized:

`---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapp1
  namespace: live
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        myapp1/some-port: "8765"
      labels:
        app: myapp1
        service: myapp
      name: myapp1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - oneserve
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: myapp-image
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 30
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health.html
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
        name: myapp
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /health.html
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1.5
            memory: 4.7Gi
          requests:
            cpu: 0.2
            memory: 4Gi
        volumeMounts:
        - mountPath: /configdir/properties
          name: config-volume
          subPath: properties
        - mountPath: /configdir/log4j.properties
          name: config-volume
          subPath: log4j.properties
      - args:
        - -c
        - tail -n+1 -f /logs/myapp1.log -F
        command:
        - /bin/sh
        image: alpine
        name: sitelog
        volumeMounts:
        - mountPath: /logs
          name: logs
      initContainers:
      - args:
        - -c
        - nc -v database 9999
        command:
        - /bin/sh
        image: busybox
        name: db-check
        resources:
          limits:
            memory: 200Mi
      volumes:
      - configMap:
          name: myapp1-configmap
        name: config-volume`

**Comment by devopsgoat** [comment]
When the pod goes into the problematic state the sidecar containers continue to run. The ConfigMaps appear to be mounted in the OS under` /var/lib/kubelet/pods/[pod Id]/volumes/kubernetes.io~configmap/config-volume/`

**Comment by devopsgoat** [comment]
We have recently lengthened the value passed to `sleep` in the preStop hook to 30 seconds. Could this be factor?

**Comment by devopsgoat** [comment]
...also on every cycle of the container restart is the message:

```
level=warning msg="10cc098f603cb93a6e1ca7cdb141574ff2a6cf5629b47b787a24a34879bcb309 cleanup: failed to unmount secrets: invalid argument"
```

I assume this is because the secret never gets mounted as the container has failed to start.

**Comment by neolit123** [comment]
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6",

is the problem reproducible with 1.15 at minimum? 1.14 is out of support since the release of 1.17.

**Comment by devopsgoat** [comment]
OK. I can look to see if this is still an issue at 1.15.

Are there any tools recommended to troubelshoot this at the docker level as this looks like where the error is coming from? So far I have used docker with debug enabled and strace against the docker process.

This only seems to have become a problem recently but there have been no changes to the platform (OS + packages, K8S version) nor the K8S manifests

**Comment by neolit123** [comment]
> Are there any tools recommended to troubelshoot this at the docker level as this looks like where the error is coming from? So far I have used docker with debug enabled and strace against the docker process.

i'm not aware of any tools for that, but you can try asking in the #sig-node channel on k8s slack.

if you provide some minimal (but detailed) reproduction steps someone else might be able to help too.

**Comment by devopsgoat** [comment]
Hi. This issue can be closed - the issue was found with an erroneous ConfigMap change. The ConfigMap had a key used by the container (in a mount). This could be seen from within the container when running "df":

> df: /mountpath.txt\040(deleted): No such file or directory

Simply deleting the pods fixes this issue. 

It would be nice to have some tooling that could identify this issue. Docker debug and strace did not help identify the source of the problem. Thanks for your help.

**Comment by ganadara135** [comment]
this is related to option problem in my case.
I remove -v ... option 
after that, the error message was gone.
docker run -p 80:80 **-v $(pwd)/default.conf:/etc/nginx/conf.d/default.conf** -d --name abbweb ganadara135/abbweb:latest
