### ISSUE TITLE
Provide richer output for "kubelet --version"

### ISSUE THREAD

**Issue by gprossliner** [kubernetes/kubernetes#86779]
**What would you like to be added**:
The `kubeadm version` and `kubelet version` output can be controlled by the `-o` argument. This is very nice for automation scripts, which need to read this information. It also contains rich information like buildDate, gitTreeState and others.

It would be nice, if we could get this information also from `kubelet --version`, with json or yaml output.

Question: I assume that is it `kubelet --version` and not `kubelet version` because kubelet is no cli. It this correct?

**Why is this needed**:
I'm implementing (yet another) automated provisioning of kubeadm clusters. To implement the update workflow, I need to get the version of kubeadm, kubectl and kubelet. And kubelet needs to be handled in a special way.

**Comment by neolit123** [comment]
> the kubeadm version and kubelet version output can be controlled by the -o argument.

i think you meant kubeadm and kubectl.

> Question: I assume that is it kubelet --version and not kubelet version because kubelet is no cli. It this correct?

a CLI means command line interface and the kubelet does have one. yet it does not have sub-commands (such as "version"), only flags. so the possibility here is to either add a "version" sub command or add an extra "-o" flag that controls the version output. the later seems better for the time being.

/retitle Provide richer output for "kubelet --version"
/remove-sig cli
/sig node
/priority backlog

**Comment by gprossliner** [comment]
Thank you neolit123 for the instant feedback on this Issue.

> i think you meant kubeadm and kubectl.

Of cause, sorry for this.

> a CLI means command line interface and the kubelet does have one. yet it does not have sub-> commands (such as "version"), only flags. 

This was what I was meant.

> so the possibility here is to either add a "version" sub command or add an extra "-o" flag that > controls the version output. the later seems better for the time being.

I also think that introducing sub commands to a program which is no CLI is a good idea.
But implementing the -o (long flag --output) flag to control the output would be reasonable.

I checked the documented [kubelet Options](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/), and only --help seems to have the same "CLI like" behavior too, which is print something and exit. Because I don't think that anyone expects --help to honor the output format, the -o flag could be implemented only for the --version flag.

I suggest implementing the same formats like `kubeadm version`, "yaml ", "json" and "short", while "short" is the current output, and the default value.

Example (for 1.16.3 release):
```
[root@lnxclp1 ~]# kubelet --version
Kubernetes v1.16.3

[root@lnxclp1 ~]# kubelet --version -o short
Kubernetes v1.16.3

[root@lnxclp1 ~]# kubelet --version -o yaml
clientVersion:
  buildDate: "2019-11-13T11:20:25Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64

[root@lnxclp1 ~]# kubelet --version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "16",
    "gitVersion": "v1.16.3",
    "gitCommit": "b3cbbae08ec52a7fc73d334838e18d17e8512749",
    "gitTreeState": "clean",
    "buildDate": "2019-11-13T11:20:25Z",
    "goVersion": "go1.12.12",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**Comment by neolit123** [comment]
> I also think that introducing sub commands to a program which is no CLI is a good idea

but the kubelet does have a [CLI](https://en.wikipedia.org/wiki/Command-line_interface) even if it does not have sub-commands.

> I suggest implementing the same formats like kubeadm version, "yaml ", "json" and "short", while "short" is the current output, and the default value.

this is a valid proposal and it is fairly easy to understand and implement.

here is a mini guide for the `help-wanted` label, so that someone can pick this up and work on it:
- investigate how kubectl does the version formatting.
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/version/version.go
- implement the same for kubelet but using `--version -o <fmt>` instead of subcommand `version`.
https://github.com/kubernetes/kubernetes/blob/67d928acdc351d3d4f9e20a92cee4452a26ed0c4/staging/src/k8s.io/component-base/version/verflag/verflag.go#L75-L92
or suggest a better flag option e.g. `--version-output`.

/help

**Comment by bharaththiruveedula** [comment]
@neolit123 @gprossliner can I work on this please?

**Comment by neolit123** [comment]
Sure, but please note these ideas are not yet approved by the kubelet
maintainers.

**Comment by gprossliner** [comment]
@neolit123, I really appreciate your participation on this topic. Please let me know, if there is anything I can assist with.

**Comment by neolit123** [comment]
@gprossliner 
have a look at the ongoing discussion at the k-dev mailing list about the available flag options: https://groups.google.com/forum/#!topic/kubernetes-dev/Nmqug4xwS8c

**Comment by gprossliner** [comment]
Thanks @bharaththiruveedula, let me know if there is anything I can do.

**Comment by bharaththiruveedula** [comment]
@gprossliner , I am currently getting confirmation about the flags to use from kubelet maintainers. The current options we have are --version=json and --version-json. Once it is confirmed, I  can start implementing it immediately

**Comment by soltysh** [comment]
I don't think SIG-CLI has anything to say wrt kubelet flags, I'll leave it entirely to kubelet maintainers.
