### ISSUE TITLE
[Failing Test] gce-windows-containerd-master (ci-kubernetes-e2e-windows-containerd-gce)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#86788]
**Which jobs are failing**:
`gce-windows-containerd-master (ci-kubernetes-e2e-windows-containerd-gce)`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-containerd-master

**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-containerd-gce/1212723448694968324

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/milestone v1.18
/sig cluster-lifecycle
/sig windows

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle
/sig node
this job is owned by sig-windows and sig-node.

**Comment by pjh** [comment]
The first failure that I see in the linked build log:

```
Jan  2 14:00:19.092: FAIL: failed to validate endpoints for service endpoint-test2 in namespace: services-2709
Unexpected error:
    <*errors.errorString | 0xc002c7cf70>: {
        s: "Timed out waiting for service endpoint-test2 in namespace services-2709 to expose endpoints map[pod1:[80]] (3m0s elapsed)",
    }
    Timed out waiting for service endpoint-test2 in namespace services-2709 to expose endpoints map[pod1:[80]] (3m0s elapsed)
occurred
```

I skimmed through other failures below that and they all seem to be timeouts. I think increased latency is expected with containerd on Windows right now, not sure if we should increase the test timeouts or just live with this while containerd work progresses.

**Comment by droslean** [comment]
@Random-Liu Any news?

**Comment by Random-Liu** [comment]
@droslean Hey! That test is still WIP. :)

I'll work on a fix soon.

**Comment by droslean** [comment]
@Random-Liu  Any news?

**Comment by yliaog** [comment]
@Random-Liu is this release blocking?

**Comment by Random-Liu** [comment]
Nope. It only affects GCE. And we still have Azure coverage for the windows test.

**Comment by yliaog** [comment]
in that case, @droslean, could you remove this test from release blocking list. thanks

**Comment by hasheddan** [comment]
@yliaog PR already open to remove it :) https://github.com/kubernetes/test-infra/pull/16549

**Comment by yliaog** [comment]
sounds good, thanks. any other release blocking issue related to 'windows'?

**Comment by droslean** [comment]
the job has been removed. Closing
/close
