### ISSUE TITLE
Define a scheduler algorithm provider for kubelet

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#86803]
**What would you like to be added**:

Define algorithm providers in terms of plugins instead of predicates for kubelet.

Ref https://github.com/kubernetes/kubernetes/issues/86162

**Why is this needed**:

Predicates will be deprecated.

/sig scheduling
/assign

**Comment by ahg-g** [comment]
Sounds good, thanks.

**Comment by ahg-g** [comment]
/retitle Define a scheduler algorithm provider for kubelet

**Comment by wgliang** [comment]
According to my actual experience, in addition to the default provider for kubelet, a custom algorithm is also necessary. 

The scenario is: the user needs to shield some of the factors that trigger the eviction of the kubelet, thereby reducing the risk of the application.

**Comment by hex108** [comment]
I have done most of the work for this issue. Howerver there is a problem I have not solved.

When [`predicates.GeneralPredicates`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/predicate.go#L92) fails because of insufficient resources, kubelet will try to recover from it.

https://github.com/kubernetes/kubernetes/blob/36e40fb850293076b415ae3d376f5f81dc897105/pkg/kubelet/lifecycle/predicate.go#L103

It will retry to evict pods to saitisfy the insufficient amount.
https://github.com/kubernetes/kubernetes/blob/36e40fb850293076b415ae3d376f5f81dc897105/pkg/kubelet/preemption/preemption.go#L68-L86

Howerver, there is no such information in `framework.Status`: when we convert predicate messages, we do not put `InsufficientAmount` to the reasons.
https://github.com/kubernetes/kubernetes/blob/36e40fb850293076b415ae3d376f5f81dc897105/pkg/scheduler/framework/v1alpha1/interface.go#L100-L103

How about adding an field `extraInfo` in `Status` to contain these similar messages?  Then we could parse `InsufficientAmount` from them. Any suggestion for it? @ahg-g
