### ISSUE TITLE
The base image's tag of debian-hyperkube-base haven't changed

### ISSUE THREAD

**Issue by huchengze** [kubernetes/kubernetes#86808]
**What happened**:

The base image'tag of debian-hyperkube-base haven't changed.

In this [commit](https://github.com/kubernetes/kubernetes/commit/861cdd82b50d2aca3115b5e031a9f509b9eb5e3e#diff-cbc4ed8875862b227463fb138e295d7e), the base image's tags  of debian-base, debian-iptables and debian-hyperkube-base have changed together.

But in this [commit](https://github.com/kubernetes/kubernetes/commit/573a99ea51b0e7924260306a11a567de89e5bd67#diff-c75f0e607309c48d530a65a2943fc3a0), only the base image's tags of debian-base and debian-iptables have changed.

And the base image's tag of debian-hyperkube-base is still 0.4.1.

Is this all right or just forgeted to change it?

**Comment by aojea** [comment]
I think this should be related to this https://github.com/kubernetes/kubernetes/issues/81760

**Comment by huchengze** [comment]
@aojea This  [issue](https://github.com/kubernetes/kubernetes/issues/81760) just changed the way how to create a hyperkube image, but didn't say why not change the tag.
I find that when the hyperkube's base image use tag 0.4.1 and before, it is 
```
ifeq ($(ARCH),amd64)
	BASEIMAGE?=debian:stretch
endif
ifeq ($(ARCH),arm)
	BASEIMAGE?=arm32v7/debian:stretch
	QEMUARCH=arm
endif
ifeq ($(ARCH),arm64)
	BASEIMAGE?=arm64v8/debian:stretch
	QEMUARCH=aarch64
endif
ifeq ($(ARCH),ppc64le)
	BASEIMAGE?=ppc64le/debian:stretch
	QEMUARCH=ppc64le
endif
ifeq ($(ARCH),s390x)
	BASEIMAGE?=s390x/debian:stretch
	QEMUARCH=s390x
endif
```
and when it use tag v1.0.0 and after, it is
```
ifeq ($(ARCH),amd64)
	BASEIMAGE?=debian:buster-slim
endif
ifeq ($(ARCH),arm)
	BASEIMAGE?=arm32v7/debian:buster-slim
	QEMUARCH=arm
endif
ifeq ($(ARCH),arm64)
	BASEIMAGE?=arm64v8/debian:buster-slim
	QEMUARCH=aarch64
endif
ifeq ($(ARCH),ppc64le)
	BASEIMAGE?=ppc64le/debian:buster-slim
	QEMUARCH=ppc64le
endif
ifeq ($(ARCH),s390x)
	BASEIMAGE?=s390x/debian:buster-slim
	QEMUARCH=s390x
endif
``` 
Is this why hyperkube haven't changed its base image's tag?

**Comment by huchengze** [comment]
/remove-kind bug
/kind feature
@kubernetes/release-engineering
