### ISSUE TITLE
Allow description in metadata of CRD structural schema

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#86800]
**What would you like to be added**:

CRD structural schema requires that `if metadata is specified, then only restrictions on metadata.name and metadata.generateName are allowed.`

Can `metadata.description` field be also allowed?

**Why is this needed**:

I am using kubebuilder to generate CRD yamls. If I add comments to `metadata` field in Go struct, kubebuilder sets that as `metadata.description` in the generated CRd yaml. This generated yaml is considered invalid as structural schema.

Example:
- https://github.com/appscode/voyager/commit/5f8a169dae4eb73738ec965575328177026bf4b9#diff-621dd318cc94d163f872e0712dc053a8L47-L48
- https://github.com/appscode/voyager/commit/5f8a169dae4eb73738ec965575328177026bf4b9#diff-c793f5d116450276c7d0a4cb7e90b538L49

**Comment by tamalsaha** [comment]
cc: @sttts

**Comment by sttts** [comment]
We cannot change this easily, i.e. weakening validation. This would lead to CRDs which are compatible with e.g. 1.18, but incompatible with 1.17.

**Comment by liggitt** [comment]
Given the description would not actually be used in the generated openapi schema, it seems misleading to allow it to be specified

**Comment by liggitt** [comment]
That, in addition to the compatibility concerns @sttts mentioned, makes me think we should not do this.
