### ISSUE TITLE
Initialize map for singleton cache

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#86814]
**What would you like to be added**:
For singleton cache, the map should be created outside lock.

**Why is this needed**:
For singleton cache, it is inefficient to check map against nil under lock.
Code from staging/src/k8s.io/apimachinery/third_party/forked/golang/json/fields.go :
```
var fieldCache struct {
	sync.RWMutex
	m map[reflect.Type][]field
...
	fieldCache.Lock()
	if fieldCache.m == nil {
		fieldCache.m = map[reflect.Type][]field{}
```

**Comment by liggitt** [comment]
Discussion of this change can be contained to the PR, we don't need a separate issue to track it
