### ISSUE TITLE
Support pod binding in batch

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#86839]
**What would you like to be added**:

Bind Pods in batch/array.

**Why is this needed**:

[Volcano](http://github.com/volcano-sh/volcano) supports gang-scheduling which will bind several pods together when there're enough resources. The performance downgraded extraordinarily as the `minMember` of `PodGroup` increaseing. The atomic binding is **un-necessary** as the volcano will help to handle the exception.

/wg machine-learning
/sig api-machinery

**Comment by liggitt** [comment]
Since this is targeted at api-machinery, it's unclear what capability this is requesting. Is this asking for atomic multi-resource write transactions?

**Comment by k82cn** [comment]
> Since this is targeted at api-machinery, it's unclear what capability this is requesting. Is this asking for atomic multi-resource write transactions?

oh, I'd like to have the ability to bind several pods to serveral nodes in **one** request, for example, we'd like to pod_1 to node_1, pod_2 to node_2 ..., and send those binding in **one** request. We don-t need atomic binding, as the scheduler will retry it in next scheduling cycle and abort the whole 'job' if it cann-t get more resources :)

**Comment by liggitt** [comment]
> I'd like to have the ability to bind several pods to serveral nodes in one request, for example, we'd like bind pod_1 to node_1, pod_2 to node_2 ..., and send those binding in one request; the apiserver give the feedback on which one was bound successfully :)

A multi-resource write operation is a net new concept… given the lack of atomicity you describe, the only benefit seems to be a single request over multiple requests. It's not clear to me that benefit warrants the added complexity. 

sig-node / sig-scheduling would be the primary drivers of the API, though api-machinery / architecture could give guidance on potential mechanisms. 

/priority awaiting-more-evidence
/sig node architecture

**Comment by k82cn** [comment]
> the only benefit seems to be a single request over multiple requests.

The benefit is performance improvement when we enable gang-scheduling; we'll send several bind requests to apiserver in a `for` loop when we get enough resources :)

**Comment by liggitt** [comment]
That seems similar to the approach for instantiating multiple pods for a replicaset during a scale up operation (simple create requests in a loop). That can be parallelized to complete faster, but it's not clear a bulk API is warranted.

**Comment by k82cn** [comment]
hm... it's blocked by qps of kube-apiserver, so a parallelized binder did not make it faster; and we can not increase qps only for binding request. For example, it'll take 20s to create pods, 1s to do the scheduling, and 20s to bind to the host: if enable gang-scheduling, it'll take 41s (20s + 1s + 20s) to do that; if disable gang-scheduling, it'll take ~20s to do that as the pod can be dispatched one by one (controller and scheduler is a kind of pipeline).

**Comment by k82cn** [comment]
btw, is it possible to make that extendable?

**Comment by liggitt** [comment]
> is it possible to make that extendable?

I'm not sure what you're referring to

**Comment by k82cn** [comment]
> > is it possible to make that extendable?
> 
> I'm not sure what you're referring to

Customized api to modify default kinds (e.g. Pod).

**Comment by lavalamp** [comment]
> it's blocked by qps of kube-apiserver, so a parallelized binder did not make it faster

In that case, I wouldn't expect that moving the loop inside apiserver would make a difference (apiserver would just be calling itself N times).

Moving the loop doesn't change the amount of work that needs to be done.

Why can you not increase your scheduler's QPS?

If the problem is the knock-on writes from starting the pods (status updates, event writes) then making apiserver do things in a batch is definitely not going to help.
