### ISSUE TITLE
close the kubernetes/kubernetes GitHub project called "kubeadm"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#86834]
close the kubernetes/kuberentes project called "kubeadm"

https://github.com/kubernetes/kubernetes/projects/7

it was last updated in 2017, contains merged and closed tickets and is currently unused.
the kubeadm project uses the k/kubeadm repository for tracking work.

/sig cluster-lifecycle
/assign @timothysc @nikhita @cblecker 
or someone else with access please help with that. thanks.

**Comment by nikhita** [comment]
> close the kubernetes/kuberentes project called "kubeadm"

Done!
/close
