### ISSUE TITLE
Kubelet should store the config of a static pod as an annotation in the mirror pod

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#8683]
See #8642 for more context.

Currently, kubelet compares the spec of a mirror pod (created via apiserver) with that of a static pod (config stored as a file) to decide whether the two are considered identical. If they differ, kubelet would delete the mirror pod and re-create it with the correct spec. Due to the fact that apiserver may set default values for some fields in the spec of the mirror pod, the specs could deviate undesirably. To avoid problems like this, we can store the config of a static pod as an annotation in the mirror pod, and compare the static pod with the annotation.

**Comment by vmarmol** [comment]
Would a hash of the config be sufficient if we're only going to compare? The whole spec would generally be more useful, but I wonder if that is too much data to put in an annotation.

**Comment by davidopp** [comment]
This seems totally reasonable to me, but I'm still desperately curious why you can't just bypass defaulting when you generate mirror pod from static pod? (i.e. just use the static pod's configuration verbatim)

**Comment by yujuhong** [comment]
> This seems totally reasonable to me, but I'm still desperately curious why you can't just bypass defaulting when you generate mirror pod from static pod? (i.e. just use the static pod's configuration verbatim)

It's not kubelet who applies the default values here. The admission plugin was only run at the apiserver, and to bypass that, you have to ask apiserver to treat mirror pods different and potentially at multiple places.

**Comment by davido2** [comment]
On May 22, 2015 10:38 AM, "Yu-Ju Hong" <notifications@github.com> wrote:
>>
>  The admission plugin was only run at the apiserver, and to bypass that,
you have to ask apiserver to treat mirror pods different and potentially at
multiple places.

Understood, but is it really multiple places? If so then I agree it's a bad
idea. Otherwise it might be worth considering as an alternative.

**Comment by bgrant0607** [comment]
@davidopp It's untenable for Kubelet to assume to know/circumvent all fields that will be set by other entities: admission control, defaulting, late initialization, auto-something, whatever. It needs to obey the same rules as other clients.

**Comment by davidopp** [comment]
I don't understand why you would ever want to apply any of the things you mentioned to static pods. Static pods should be copied verbatim into the mirror pods, right? That's what I'm proposing.

**Comment by bgrant0607** [comment]
What if the master is updated before the kubelet, and the master adds a new API field with a default value?

**Comment by bgrant0607** [comment]
That case should be discussed in #4855

**Comment by yujuhong** [comment]
> I don't understand why you would ever want to apply any of the things you mentioned to static pods. Static pods should be copied verbatim into the mirror pods, right? That's what I'm proposing.

@davidopp, I agree that mirror pod should reflect the true status of the static pod running on the node, and no default values should be set in this case. However, I think it'd be harder to implement this way since, as stated above, that there are many things to circumvent in the apiserver itself. It could also be harder to keep this special case from being broken by a yet another new feature/plugin. Keeping the hash of the config in the annotation seems like a good compromise even though it may not reflect the true status 100% accurately. I think this is acceptable. What do you think?

**Comment by davidopp** [comment]
Sure, if you think the annotation approach is easier, I would go with that.

I guess in the case Brian mentoined (master adds a new API field with a default value), you would not update the mirror pod, because the static pod definition has not changed?

**Comment by bgrant0607** [comment]
@vmarmol Yes, a hash would be sufficient.

**Comment by bgrant0607** [comment]
@davidopp It shouldn't be necessary to update the mirror pod in the case that a new default field was updated, because that field should be populated automatically by the apiserver on decode from etcd.

**Comment by bgrant0607** [comment]
We should fix this so we don't have this problem again in 1.2.
