### ISSUE TITLE
Patch status of volumeAttachment(StorageV1) does not work   

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#86835]
**What happened**:

When we upgrade volumeAttchment api version from v1beta1 to v1 in external-attcher, we found we can patch volumeattachment would return error, but the volumeAttachment .

See https://github.com/kubernetes-csi/external-attacher/pull/200

Patch status of volumeAttachment(StorageV1) does not work   

**What you expected to happen**:

Successfully path volumeAttachment successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Patch an already existing volumeAttachment with V1 api, patch would not work but it does not return error

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cwdsuzhou** [comment]
/assign


I have found reason, I will send a PR to fix it

**Comment by cwdsuzhou** [comment]
@liggitt @msau42 

I am not sure if  we should change this func.
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/storage/volumeattachment/strategy.go#L103

Because I see the comment of the initial PR
https://github.com/kubernetes/kubernetes/pull/69929#discussion_r232444074

**Comment by liggitt** [comment]
Volume attachment status must be patched via the /status subresource in v1. The ability to change those fields via the main resource in v1beta1 was an unintentional oversight. 

/close

**Comment by cwdsuzhou** [comment]
> Volume attachment status must be patched via the /status subresource in v1. The ability to change those fields via the main resource in v1beta1 was an unintentional oversight.
> 
> /close

Thanks
