### ISSUE TITLE
Skip sorting Requirement slice in variant of SelectorFromValidatedSet

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#86851]
**What would you like to be added**:
The sorting step in SelectorFromValidatedSet can be skipped.

**Why is this needed**:
Looking at the references to SelectorFromValidatedSet(), the return value is used for calling api-server where sorted key is not required.

With sorting:
```
BenchmarkSelectorFromValidatedSet-12             5000000               257 ns/op             208 B/op          5 allocs/op
```
Without sorting:
```
BenchmarkSelectorFromValidatedSet-12            10000000               202 ns/op             176 B/op          4 allocs/op
```

**Comment by liggitt** [comment]
We probably don't need issues tracking things like this. My one question is whether the sorting is required so that comparison (equality checks) and serialization is normalized

**Comment by tedyu** [comment]
e2e test results are good.

There is some unit test assertions to be adjusted.
e.g.
```
--- FAIL: TestNodeSelectorRequirementsAsSelector (0.00s)
    helpers_test.go:242: [2]expected:
                foo in (bar,baz)
        but got:
                foo in (bar,baz)
```
I cannot see difference from the above output or, in IDE.

**Comment by apelisse** [comment]
Yeah, agreed, we don't need issues for small changes.
