### ISSUE TITLE
Best practices for packaging cluster components

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#8686]
We have a mix of styles in our current cluster creation pushing code. We should fix this soon after 1.0.
## Current state
- apiserver - put into container, tar’d, uploaded to gcs, and curl’d into to cluster at kube-up time.
- scheduler - put into container, tar’d, uploaded to gcs, and curl’d into to cluster at kube-up time.
- controller-manager - put into container, tar’d, uploaded to gcs, and curl’d into to cluster at kube-up time.
- kubelet, kube-proxy - n/a (run as binaries)
- Addons: kube2sky (dns), heapster, network-tester, etc - occasionally built, and pushed to gcr.io, with an ad-hoc version that doesn’t reliably correlate with any revision in git.
## Problems
1. Difficult or impossible to get a consistent cluster (including addons) from source.
2. Addons leave lingering dependencies (accidental push could break all cluster turnups).
3. Also not possible to start a cluster using config + a set of containers already in gcr.io
## Desired state

Build and version a complete set of containers, including addons.
1. For official releases, push to official registry and throw away the keys (or do the closest moral equivalent). This lets you start most of a cluster just with config files referencing the official containers for that version.
2. For unofficial releases, a choice:
   1. Push to cluster via gsutil/curl, like now.
      1. cons: doesn’t work well for addons, which might need to run on any node.
   2. Push to a (potentially private) registry, under the user’s name, so that my dev containers can’t collide in name with yours (filed #8517).
      1. pros: code reuse with the official release method.
   3. Run a private registry in the cluster by default, and push to that. (bootstrapping problem to solve!)
      1. additional pro: no need for user to set up a private repo before using.
3. The build process then makes a set of config that references these containers.

**Comment by bgrant0607** [comment]
cc @thockin @vishh @brendandburns

**Comment by brendandburns** [comment]
We should also split our image stores into:
```gcr.io/google_containers/...``` - Production images, limited write ACLs
```gcr.io/google_containers_dev/...``` - Staging images, ACLs like the existing ```google_containers``` that will help prevent mistakes as well.

**Comment by bgrant0607** [comment]
Another addon: the UI

**Comment by davidopp** [comment]
What are unofficial releases? Does that mean releases the user creates, as opposed to the ones released by the Kubernetes project itself?

One other question: I wasn't clear how your proposal addresses the "Addons leave lingering dependencies" issue (probably because I don't understand that issue).

**Comment by pmorie** [comment]
@lavalamp the kubelet can run in a container under docker 1.6 -- the mount
propagation mide used fir bind mounts changed in 1.7 in a way that breaks
it, though. We at RH are trying to get this fixed.

**Comment by lavalamp** [comment]
@davidopp yes, that covers random builds by individual devs.

By "lingering dependencies" I mean that if you build from head and re-push e.g. kube2sky:v1, you accidentally break an unknown number of running clusters that used to work.

**Comment by mikedanese** [comment]
I discussed this with @brendandburns @roberthbailey and we decided that the easiest path forward for ci builds is to depend on an external registry (so 2) ii) ):

> Push to a (potentially private) registry, under the user’s name, so that my dev containers can’t collide in name with yours (filed #8517).

The registry prefix (everything but the image name and tag) would be configurable by an env variable set it cluster/env.sh which we already source in kube-up and gitignore.

We can move to iii later on if we decide we don't like this dependency but ii is good intermediate step. Any oposition to taking this depenency? cc @pmorie @kubernetes/rh-cluster-infra

**Comment by pmorie** [comment]
@mikedanese That SGTM

**Comment by ihmccreery** [comment]
FYI @fgrzadkowski

**Comment by davidopp** [comment]
@mikedanese This is tagged as 1.2 milestone -- AIUI the full vision for this is definitely not going to be in 1.2, so should we bounce it to next-candidate? If so, please change the milestone.

**Comment by mikedanese** [comment]
we can now use kube-push to deploy clusters using an external docker registry which is what I wanted to get done for 1.2. that is sufficient to allow the self hosting cluster configuration without having to unpack everything everywhere

**Comment by ixdy** [comment]
The "current state" of May 22, 2015 looks a lot like the "current state" of February 13, 2017.

How happy are we with this? How much of the "desired state" still makes sense to try to attempt?

x-ref #15639 which seems somewhat related

**Comment by roberthbailey** [comment]
@ixdy - I agree that the current state hasn't change much, but that just means we have been able to skate by, not that we have redefined the desired state. 

We have started pushing hyperkube images to gcr.io as part of building releases; why not push the other master components (and kube-proxy, which is also now side-loaded onto nodes) as well? That would at least move us in the right direction. And you could still side-load the containers from a tar file if you wanted to warm the docker cache on the machine and skip the pull from the registry. 

Is this something that the release sig could help drive?

**Comment by roberthbailey** [comment]
FWIW, @dchen1107 also filed https://github.com/kubernetes/kubernetes/issues/24123 in April 2016 which is along the same lines (we should stop side-loading and be pulling from gcr.io).

**Comment by ixdy** [comment]
I'm pretty sure we do push all of the core cluster images to gcr.io/google-containers for releases, but for G{C,K}E we still side-load, and I'm not sure if the reasons for doing the side-loading are still valid.

If we wanted to use a registry instead of side-loading, we'd still need to figure out the developer and CI use-cases. We currently don't push any of the CI builds to gcr.io, but that's something we've considered doing for a while (https://github.com/kubernetes/test-infra/issues/1400).

#44981 is a bit of prework to help with the dev/CI cases - the images we build locally now always use the (slightly munged) semantic version as the tag, rather than an md5sum. We still discard the images after builds except in the release workflow, however.

**Comment by roberthbailey** [comment]
> I'm not sure if the reasons for doing the side-loading are still valid.

One of the main reasons that we side-load is to run tests against HEAD. For instance, @luxas posted [this gist](https://gist.github.com/luxas/7515d1e1fb94cff1327b83ae4affd7a4) to show how we could add side-loading to run kubeadm tests against HEAD. If the CI builds could pull from gcr.io, then we could leverage that for kubeadm tests **and** remove the side-loading from the GCE/GKE setup scripts. 

I need to think through the dev case a bit more, since right now (at least on GCE) it revolves around having everything packaged into the tarball.

**Comment by luxas** [comment]
Agree that if https://github.com/kubernetes/test-infra/issues/1400 was fixed, this should/might be solved as a consequence
