### ISSUE TITLE
sharedProcessor::resyncCheckPeriodChanged looks unnecessary

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#86862]
**What happened**:
I studied https://github.com/kubernetes/kubernetes/blob/0f61791bc7330c8402e6b9fe93a86ad064607f77/staging/src/k8s.io/client-go/tools/cache/shared_informer.go (that's from the commit to which `master` currently points) and noticed what appears to be unnecessary code complexity.  Notice that the `resyncCheckPeriod` of a sharedIndexInformer only shrinks, and never changes after `started` becomes true.  In every call to sharedIndexInformer::AddEventHandlerWithResyncPeriod, `resyncPeriod==0 || s.resyncCheckPeriod==0 || resyncPeriod > s.resyncCheckPeriod` at line 427, which means that in this call to `determineResyncPeriod` the test on line 389 will never be true and thus lines 390 and 391 will never be reached.  Line 427 will construct a listener with a resync period that is as good as it will ever get; no future call to resyncCheckPeriodChanged will improve it.  Thus, the function resyncCheckPeriodChanged does not need to exist or be called.

**What you expected to happen**:
I expected to find no unnecessary complexity.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@ncdc

**Comment by MikeSpreitzer** [comment]
Also, the use of `wait.ExponentialBackoff` on line 652 looks unnecessary, because the ConditionFunc always returns `true, nil`.

**Comment by MikeSpreitzer** [comment]
See also #86774

**Comment by tedyu** [comment]
@MikeSpreitzer 
Do you want to submit PR with removal of resyncCheckPeriodChanged ?

**Comment by MikeSpreitzer** [comment]
@tedyu : I decided to start with a PR that extends the testing to prove my observations.  See #86883 .
