### ISSUE TITLE
AWS NLB: support multiple TLS certificates

### ISSUE THREAD

**Issue by iusergii** [kubernetes/kubernetes#86881]
**What would you like to be added**:
Elastic Load Balancing now support [multiple TLS certificates](https://aws.amazon.com/about-aws/whats-new/2019/09/elastic-load-balancing-network-load-balancers-now-supports-multiple-tls-certificates-using-server-name-indication/).  Respective support for configuring list of certificates ARNs for Service type Load-Balancer.

**Why is this needed**:
We have requirement to use certificate managed by AWS (ACM) for our external connection.  Since we have  a bunch of hosted zones we have to create dedicated Ingress Controller per domain.  This feature would eliminate this overhead.

**Comment by justinsb** [comment]
We discussed this in the k8s-AWS bi-weekly meeting; we classified this as a feature request and would certainly welcome anyone to work on it!

We think ALB supports specifying multiple ARNs in a comma-separated form, and so it likely makes sense to support the same thing here.

**Comment by pschulten** [comment]
Please unfreeze

**Comment by iusergii** [comment]
@justinsb could you please re-open this.

**Comment by PeiyuanQi** [comment]
is there a new request for tracking this feature or not?

**Comment by ccampo133** [comment]
Wold love to see this implemented. It allows us to use a single load balancer for many TLS hosts, instead of one LB per host. This is more cost and resource effective.

For now, manually adding the additional certificates to the LB in the AWS console or with the AWS CLI seems to work.

**Comment by Dohbedoh** [comment]
There seems to be WIP https://github.com/kubernetes/kubernetes/pull/95208

**Comment by kireledan** [comment]
Just nudging to let you know I haven't abandoned the PR. I've just been really caught up in work 😅  
Planning to wrap up this weekend since I'll have a lot of time.

**Comment by iusergii** [comment]
@justinsb, @kireledan is there any progress on this, and can we re-open this?

**Comment by kireledan** [comment]
I left a comment on the original issue a bit ago https://github.com/kubernetes/cloud-provider-aws/issues/80#issuecomment-864320888. I don't have any time to work on it unfortunately , but the code is there and just needs feedback implemented from the comments. https://github.com/kubernetes/kubernetes/pull/95208

**Comment by kcheemz** [comment]
Please re-open :)

**Comment by SpootyMcSpoot** [comment]
Any update here?

**Comment by ccampo133** [comment]
I'm working on a PR for this using the work already done. Should be able to
get to it next week.
/cc

**Comment by loliveira-itp** [comment]
I'm interested in this as well!

**Comment by david-wirelab** [comment]
Bump - any news on this please?

**Comment by iamhritik** [comment]
Hi, is there any way to add multiple TLS Certificate in NLB nginx ingress controller through annotations.
