### ISSUE TITLE
create an OWNERS file in /test/e2e/apimachinery

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#86888]
the apimachinery package here:
https://github.com/kubernetes/kubernetes/tree/master/test/e2e/apimachinery

lacks an OWNERS file, thus often times the SIG might not see changes in this package.
review and approval is delegated to top-level `/test` OWNERS which is not ideal.

**request for the SIG**: create an OWNERS file in the package and pick the maintainers

for reference https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/OWNERS

/area test
/priority important-longterm
/kind feature
/sig api-machinery

**Comment by fedebongio** [comment]
Looks like someone was faster than me and this was fixed as part of: #86854
