### ISSUE TITLE
v1.18.0 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by evillgenius75** [kubernetes/kubernetes#86882]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.18 Release Notes. If you know of issues or API changes that are going out in 1.18, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @kubernetes/release-team 

/sig release
/milestone v1.18

**Comment by reylejano-rxm** [comment]
Please add appropriate verbiage about the xfs filesystem bug that will be under the 1.18 Release Notes "Known Issues" section.
/cc @alejandrox1 @gnufied @saad-ali

**Comment by evillgenius75** [comment]
Ref #89440 
PR#126 added an extra step to run xfs_repair before mounting a XFS file system. However instead of helping to automatically correct FS issues due to prior unclean shutdowns, it actually prevented auto recovery from happening, which led to complete unavailability of the corresponding volume and subsequently required manual human intervention

**Comment by gnufied** [comment]
Wait - aren't we holding 1.18.0 release so as we can merge https://github.com/kubernetes/kubernetes/pull/89444 and cherry-pick? Do we still need to capture this in "Known Issues"?

**Comment by xing-yang** [comment]
Yeah, once #89444 is merged and the cherry-pick #89449 is merged, we should not need to have this as "Known Issues".

**Comment by xing-yang** [comment]
> Proposed Verbiage for Known Issue:
> Ref #89440
> Kubernetes/utils PR#126 added an extra step to run xfs_repair before mounting a XFS file system. 

Also the referenced issue 89440 is a different one, not related to the xfs_repair issue.

**Comment by evillgenius75** [comment]
No longer a known Issue with regression provided by #89444 and cherry pick #89449

**Comment by saschagrunert** [comment]
I think this can be closed. 
/close
