### ISSUE TITLE
Custom controllers should be able to use k/k defaulting logic

### ISSUE THREAD

**Issue by vllry** [kubernetes/kubernetes#86887]
**What would you like to be added**:
Add an API to access defaulting for k/k resources. The API should accept an object, and return the defaulted result.

**Why is this needed**:
Suppose I am writing a custom controller that manages pods, or some resource that contains a PodSpec.

Some PodSpec fields/subfields, such as `dnsPolicy` are set to defaults by the Kubernetes API. My controller submits an undefaulted object, unaware of this. When my controller goes to reconcile, it does not find a matching spec (due to the mutating default), and falsely believes it always needs to reconcile due to the lack of a match.

This is awkward to implement by importing defaulting logic for a given version.

**Workarounds I've Used**
* [Storing original PodSpec in an annotation, and comparing against the annotation rather than real PodSpec](https://github.com/zeitgeistlabs/kubernetes-rollout/blob/5021ee9c15a66100061d448985a6a8d9dbd672a9/controllers/pinneddeployment_controller.go#L326)
* [Writing a custom comparison to compare select fields](https://github.com/zeitgeistlabs/kubernetes-rollout/blob/5021ee9c15a66100061d448985a6a8d9dbd672a9/controllers/pinneddeployment_controller.go#L317)

**Comment by smarterclayton** [comment]
I'm not sure even an API is sufficient for your case - during a rolling upgrade there are two valid defaulting strategies in place, and depending on which one you get you'll get different values.

Matching specs is generally considered "a hard problem" even within an identical server and version (deployments have continually struggled with it), and even with defaulting it is not foolproof.  Usually the recommendation is to more strongly define "reconcile" in terms of your operation (these are the fields I change, etc).

**Comment by liggitt** [comment]
I agree with what Clayton said, but if you really want to see the result of a creation, dry run would let you see the result without actually committing the result.

**Comment by liggitt** [comment]
(https://kubernetes.io/docs/reference/using-api/api-concepts/#dry-run)

**Comment by vllry** [comment]
> I'm not sure even an API is sufficient for your case - during a rolling upgrade there are two valid defaulting strategies in place, and depending on which one you get you'll get different values.
> 
> Matching specs is generally considered "a hard problem" even within an identical server and version (deployments have continually struggled with it), and even with defaulting it is not foolproof. Usually the recommendation is to more strongly define "reconcile" in terms of your operation (these are the fields I change, etc).

That's a good point, the closer I look, the less sense a DeepEquals check makes in all scenarios.

/close
