### ISSUE TITLE
run_crd_tests flaking

### ISSUE THREAD

**Issue by vllry** [kubernetes/kubernetes#86897]
**Which jobs are flaking**:
pull-kubernetes-integration

**Which test(s) are flaking**:
run_crd_tests

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82462/pull-kubernetes-integration/1214414030366576641

**Reason for failure**:
```/home/prow/go/src/k8s.io/kubernetes/hack/lib/test.sh: line 270: 67937 Killed                  while [ ${tries} -lt 10 ]; do
    tries=$((tries+1)); kubectl "${kube_flags[@]}" patch bars/test -p "{\"patched\":\"${tries}\"}" --type=merge; sleep 1;
done
/home/prow/go/src/k8s.io/kubernetes/test/cmd/../../test/cmd/crd.sh: line 294: 67936 Killed                  kubectl "${kube_flags[@]}" get bars --request-timeout=1m --watch-only -o name
!!! [0107 05:24:43] Call tree:
!!! [0107 05:24:43]  1: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../test/cmd/crd.sh:442 kube::test::get_object_assert(...)
!!! [0107 05:24:43]  2: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../test/cmd/crd.sh:133 run_non_native_resource_tests(...)
!!! [0107 05:24:43]  3: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:47 run_crd_tests(...)
!!! [0107 05:24:43]  4: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0107 05:24:43]  5: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:131 juLog(...)
!!! [0107 05:24:43]  6: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:572 record_command(...)
!!! [0107 05:24:43]  7: hack/make-rules/test-cmd.sh:142 runTests(...)```
```
I am unfamiliar with this test, but the log suggests that the test did not properly wait for required resources to be available.

**Comment by roycaihw** [comment]
`kubectl apply` [prunes](https://github.com/kubernetes/kubernetes/blob/96dfa3f6051766d7ebb3a74dbc0c0c58d5aa120b/test/cmd/crd.sh#L440) the foo CR "test" with a Foreground delete, and [expects](https://github.com/kubernetes/kubernetes/blob/96dfa3f6051766d7ebb3a74dbc0c0c58d5aa120b/test/cmd/crd.sh#L442) it to be gone. 
```
$ kubectl apply --prune -l pruneGroup=true -f hack/testdata/CRD/bar.yaml --prune-whitelist=company.com/v1/Foo --prune-whitelist=company.com/v1/Bar -v=9
I0219 17:20:17.646218  164184 request.go:1035] Request Body: {"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Foreground"}
I0219 17:20:17.646245  164184 round_trippers.go:423] curl -k -v -XDELETE  -H "Accept: application/json" -H "User-Agent: kubectl/v1.19.0 (linux/amd64) kubernetes/da9f47e" 'https://localhost:6443/apis/company.com/v1/namespaces/default/foos/test'
I0219 17:20:17.649337  164184 round_trippers.go:443] DELETE https://localhost:6443/apis/company.com/v1/namespaces/default/foos/test 200 OK in 3 milliseconds
...
foo.company.com/test pruned
```
However in those [failures](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1229950714411749377) the foo CR "test" was still visible. 
```
foo.company.com/test pruned
Waiting for Get foos {{range.items}}{{.metadata.name}}:{{end}} : expected: , got: test:
[1m[31m
crd.sh:442: FAIL!
```
I think this is caused by test running fast, and the garbage collector hasn't removed the object from REST API yet. I will send a fix to let the test to retry

**Comment by roycaihw** [comment]
Created #88353. For the record the test failed 13 time since 2/14: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&sort-by-flakiness=&exclude-non-failed-tests=

**Comment by roycaihw** [comment]
/reopen

I will verify the test results in the next few days.

**Comment by roycaihw** [comment]
The test is green.

/close
