### ISSUE TITLE
Support mandatory plugins in the scheduling framework

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#86909]
**What would you like to be added**:

Add mandatory plugins that can't be removed from the default plugins.

**Why is this needed**:

We have mandatory predicates that should be configured all the time, and we still need them when migrates to scheduling plugins.

```go
		// MandatoryPredicates the set of keys for predicates that the scheduler will
		// be configured with all the time.
		MandatoryPredicates: sets.NewString(
			predicates.PodToleratesNodeTaintsPred,
			predicates.CheckNodeUnschedulablePred,
		),
```

/sig scheduling
/priority important-soon

**Comment by ahg-g** [comment]
Sounds good, thanks!

**Comment by Huang-Wei** [comment]
We should revisit this. My 2 cents: https://github.com/kubernetes/kubernetes/pull/87134#issuecomment-575408639

**Comment by draveness** [comment]
> @alculquicondor I think this has been debated already while the KEP for the framework was presented. We should respect that decision.

I revisited the comments on https://github.com/kubernetes/community/pull/3082 and didn't find the debate on the disable of the scheduling plugin, and maybe it is a lazy consensus, or I missed some vital info?

**Comment by draveness** [comment]
I agree with what @Huang-Wei mentioned in https://github.com/kubernetes/kubernetes/pull/87134#issuecomment-575408639

> + don't define new plugin by just simply combining existing plugins
> + don't define any plugin as mandatory
> + with validation logic, also be cautious - validate whatever really needs to be validated

This could make things much easier.

**Comment by ahg-g** [comment]
Ok, so we agree we shouldn't do anything for plugins, but still add those two predicates for Policy-based configurations to maintain backward compatibility

**Comment by alculquicondor** [comment]
> I revisited the comments on [kubernetes/community#3082](https://github.com/kubernetes/community/pull/3082) and didn't find the debate on the disable of the scheduling plugin, and maybe it is a lazy consensus, or I missed some vital info?

It was actually not in the KEP, but the config PR https://github.com/kubernetes/kubernetes/pull/77501#discussion_r282078897
although the conversation is difficult to follow. But it seems that the main rationale is that it should be easy to override one or a few default plugins without having to copy the default list (which would be more error prone)

**Comment by draveness** [comment]
> > I revisited the comments on [kubernetes/community#3082](https://github.com/kubernetes/community/pull/3082) and didn't find the debate on the disable of the scheduling plugin, and maybe it is a lazy consensus, or I missed some vital info?
> 
> It was actually not in the KEP, but the config PR [#77501 (comment)](https://github.com/kubernetes/kubernetes/pull/77501#discussion_r282078897)
> although the conversation is difficult to follow. But it seems that the main rationale is that it should be easy to override one or a few default plugins without having to copy the default list (which would be more error prone)

And we could close this issue since we reached a consensus on this.

/close
