### ISSUE TITLE
Ungraceful pod deletion (w/o SIGTERM) for testing purposes

### ISSUE THREAD

**Issue by fischerman** [kubernetes/kubernetes#86914]
**What would you like to be added**:

An option to delete a pod without sending a `SIGTERM` to the pods containers, similar to a `docker rm -f ...` and/or an enhanced documentation stating that the kubelet (I guess) always sends a `SIGTERM` to the containers.

**Why is this needed**:

For example, to test a failover between Pods in a StatefulSet without having to interact with the container runtime. I did expect that the options `--now` and `--grace-period=1` would achieve this because they are documented as "immediate deletion" which I interpreted as "no clean-up time". To my surprise the containers still received a `SIGTERM`.

**Comment by fengzixu** [comment]
Before we talk about the "force to delete the pod", we need to confirm what is the real deletion of Pod. The deletion of pod includes two parts I think:

1. kubelet deletes all related containers of this pod
2.kubelet sends the deletion request to kube-apiserver. Then the record of this pod will be removed

Before the kubelet deletes containers, containers will receive SIGTERM. That is the graceful mechanism to delete the pod and there is a timeout called the graceful period.

Actually, I don't think supporting ungraceful pod deletion is making sense. Because the kubelet should not perform some dangerous behaviors.

For testing, especially in failover or self-healing, maybe we need to implement the individual component to make some troubles.

**Comment by fischerman** [comment]
I've opened this issue mostly due the confusion about the flags `--now`, `--force` and `--grace-period` and to start the discussion. I've asked around a bit and most people seem to be unsure of how they treat containers.

I think the biggest confusion is the grace period and what it relates to. Is this only relevant for the containers and denotes the time between `SIGTERM` and `SIGKILL`? Or are the apiserver or other components (bypassing webhooks?) interested in the grace-period as well? 
As far as I can read from the documentation a `--grace-period` of 0 or 1 have special meanings:
- `--grace-period=0`: Required for `--force`. The value 0 (for me at least) indicates ungraceful deletion. However the docs also state `until the node detects the deletion [of the pod on the apiserver] and completes graceful deletion.` which IMHO contradicts a grace period of 0.
- `--grace-period=1`: Is documented as `Set to 1 for immediate shutdown.` Does immediate shutdown mean something or is it a short time of 1 second (approximately ofc) between `SIGTERM` and `SIGKILL`?

I'm happy to open a PR and enhance the documentation in this direction as soon as I understand the matter fully.

> Because the kubelet should not perform some dangerous behaviors.

I think killing a process (i.e. container) is well understood. It should not happen under normal circumstances but an option for testing would be useful.

> maybe we need to implement the individual component to make some troubles.

What do you mean by individual component?

**Comment by fischerman** [comment]
/remove-lifecycle stale

@fengzixu Still hoping to enhance the documentation and any input is appreciated.

**Comment by barosl** [comment]
While trying to simulate the failure of a pod, I also realized the necessity of this feature. Have you found any other workarounds to send `SIGKILL` to the processes inside a container?

**Comment by jwolfe-ns** [comment]
We have a test case for this also that we haven't been able to implement, so we are interested in this also.

- `docker rm -f` causes the container to just be restarted within the pod
- `--force --grace-period=0` still sends a SIGTERM, it just seems to follow up quickly with a SIGKILL
- `--force --grace-period=1` ignores `--force`, as it requires `--grace-period=0`

**Comment by MartinEmrich** [comment]
/reopen
/remove-lifecycle rotten

This seem still valid with 1.21. @jwolfe-ns 's recommendation does not work here (`--grace-period=0` does not send a SIGKILL here, but has in fact no effect). So I have to wait untill my process is finished, or the (intentionally long) terminationGracePeriod is over.

AFAIR `--force` only removes all records of the Pod from the control plane, but the process might still linger on the node.

I see no clean way to immediately kill a pod via kubectl. (even getting a shell with `kubectl exec` is useless, as PID 1 ignores my `kill -KILL 1` somehow. And there might be even slimmer images without a kill command...
