### ISSUE TITLE
CPU Manager Test fails when enabling cpu manager in kubelet without deleting stale file

### ISSUE THREAD

**Issue by vpickard** [kubernetes/kubernetes#86925]
**Which jobs are failing**:
E2E CPU Manager

https://testgrid.k8s.io/wg-resource-management#kubelet-serial-gce-e2e-cpu-manager

**Which test(s) are failing**:

enable cpu manager in kubelet without delete state file

**Since when has it been failing**:

For a very long time. I stopped looking at CI logs that went back to October 2019.

**Testgrid link**:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager/1214553455293632513/build-log.txt

**Reason for failure**:
It appears that CPU Manager is in some sort of initialization loop, and failing to start properly.

Here are some relevant logs. The "initializing new in-memory state store..." log repeats for 2 minutes, and the test times out.

I0107 14:44:34.570] [1mSTEP[0m: enable cpu manager in kubelet without delete state file
I0107 14:44:34.597] I0107 14:42:24.904975    1355 server.go:182] Initial health check passed for service "kubelet"
I0107 14:44:34.597] I0107 14:42:27.594697    1355 util.go:228] new configuration has taken effect
I0107 14:44:34.597] [1mSTEP[0m: wait for the deleted pod to be cleaned up from the state file
I0107 14:44:34.597] I0107 14:42:27.597050    1355 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0107 14:44:34.598] I0107 14:42:27.597261    1355 state_mem.go:88] [cpumanager] updated default cpuset: "0-1,3"
I0107 14:44:34.598] I0107 14:42:27.597282    1355 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[0bb91704-469c-4f02-a831-0aba63392b9b:map[gu-container-testremove:2]]"
I0107 14:44:34.598] I0107 14:42:27.597301    1355 state_checkpoint.go:140] [cpumanager] state checkpoint: restored state from checkpoint
I0107 14:44:34.598] I0107 14:42:27.597310    1355 state_checkpoint.go:141] [cpumanager] state checkpoint: defaultCPUSet: 0-1,3
I0107 14:44:34.598] I0107 14:42:28.597515    1355 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0107 14:44:34.598] I0107 14:42:28.597719    1355 state_mem.go:88] [cpumanager] updated default cpuset: "0-1,3"
I0107 14:44:34.599] I0107 14:42:28.597742    1355 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[0bb91704-469c-4f02-a831-0aba63392b9b:map[gu-container-testremove:2]]"
I0107 14:44:34.599] I0107 14:42:28.597759    1355 state_checkpoint.go:140] [cpumanager] state checkpoint: restored state from checkpoint
I0107 14:44:34.599] I0107 14:42:28.597768    1355 state_checkpoint.go:141] [cpumanager] state checkpoint: defaultCPUSet: 0-1,3
I0107 14:44:34.599] I0107 14:42:29.598002    1355 state_mem.go:36] [cpumanager] initializing new in-memory state store

<snip>

I0107 14:44:34.720] I0107 14:44:26.655996    1355 state_mem.go:36] [cpumanager] initializing new in-memory state store

**Anything else we need to know**:

**Comment by neolit123** [comment]
/priority important-longterm

@klueska do you happen to know who maintains these tests on the side of sig-node?

**Comment by klueska** [comment]
@neolit123 These tests have gone stale, unfortunately, and no one is really maintaining them anymore. I am currently working with Viktor to restore them to a working state and add more of them, at which point Viktor and I will be the maintainers.

**Comment by vpickard** [comment]
Kevin pushed these PRs to address this issue:

https://github.com/kubernetes/kubernetes/pull/87397 
https://github.com/kubernetes/kubernetes/pull/87255 
https://github.com/kubernetes/kubernetes/pull/84300 

Ran the CPUManager test on GCE on 1/23/2020 with updated master. All tests pass! Thanks Kevin for the above PRs. 

The test is still failing on the upstream CI. I believe it is because of preflight verification, due to old docker image. 

When this PR to update the image is merged, test should pass: 

https://github.com/kubernetes/test-infra/pull/15609

**Comment by vpickard** [comment]
Snippet of successful test run on GCE:

<<snip>>

make test-e2e-node PARALLELISM=1 FOCUS="Feature:CPUManager" SKIP="" REMOTE=true


JUnit report was created: /tmp/node-e2e-20200123T095143/results/junit_test-cos-beta-80-12739-37-0_01.xml

Ran 1 of 316 Specs in 538.705 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 315 Skipped
PASS

Ginkgo ran 1 suite in 8m59.485218177s
Test Suite Passed

Success Finished Test Suite on Host test-cos-beta-80-12739-37-0
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<                              FINISH TEST                               <
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by vpickard** [comment]
With the above PR's, and the PR to update the test image from [15609](https://github.com/kubernetes/test-infra/pull/15609), these are now passing.

**Comment by vpickard** [comment]
https://testgrid.k8s.io/wg-resource-management#kubelet-serial-gce-e2e-cpu-manager
