### ISSUE TITLE
[Scheduler] Node snapshot data structures sometimes go out of sync

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#86920]
/sig scheduling

**What happened**:

#86919 is removing a check for snapshot's NodeInfoMap and NodeInfoList go out of sync. According to code comments this is expected when node removal events arrive before their corresponding node removal events.

https://github.com/kubernetes/kubernetes/blob/11a31590e432ba9c723b951e1691d5a97c09dba7/pkg/scheduler/internal/cache/cache.go#L631-L634

**What you expected to happen**:

Given that the plugins should only use NodeInfoList as source of truth for the existing nodes, there should be no need to keep a node in NodeInfoMap until all of its pods are removed.

However, before doing the changes, we should ensure that no code is relying on NodeInfoMap as source of truth. We could consider unexporting NodeInfoMap to avoid any iteration on its keys.

**How to reproduce it (as minimally and precisely as possible)**:

The issue is triggered by quickly downscaling a cluster, even doing it forcefully by stopping a set of nodes without draining.

**Environment**:
- Kubernetes version: 1.18 (head)

/cc @ahg-g

**Comment by ahg-g** [comment]
Can we list all places where NodeInfoMap is used outside the snapshot?

**Comment by alculquicondor** [comment]
After #86930 gets merged, the only remaining uses are:

- `genericScheduler.findNodesThatFit`, passing it to `extender.Filter` to check that pods coming from the extender are part of the snapshot. Although this seems wrong: **we should be checking that the nodes are within the input nodeList instead**.
- `genericScheduler.Preempt`, passing it to `podEligibleToPreemptOthers`, where we do checks on the pods in the nominated node. We should be using the `snapshot.NodeInfos` interface here instead.
- `genericScheduler.processPreemptionWithExtenders`, ultimately used in `convertToNodeVictims`, where we should use the NodeInfos interface as well.

**Comment by alculquicondor** [comment]
Oh, the rest of the usages are in plugins tests, also candidates to use the interface.

**Comment by ahg-g** [comment]
Can we try to make the map and list private and only accessible via the listers?

**Comment by alculquicondor** [comment]
The problem is that `cache` needs access to build the snapshot.
But we could move `snapshot.Snapshot` to the `internal/cache` package. This is an internal package, but we should have no issues because we have the `scheduler/listers` which has an interface for it.
WDYT?

**Comment by ahg-g** [comment]
yeah, that is what I was thinking, move the implementation to internal/cache. Now that we cut most direct dependencies on the scheduler code (DS controller and soon Kubelet) I think we will not have indirect dependency issues.
