### ISSUE TITLE
Generate inter pod affinity error

### ISSUE THREAD

**Issue by wybzju** [kubernetes/kubernetes#86938]
**What happened**:
https://github.com/kubernetes/kubernetes/blob/6099a739d8cb1762cdadf956fae484833b937c5d/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L86
Maybe it should be 
```
affinity.PodAffinity != nil
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bharaththiruveedula** [comment]
I feel it is a valid error. But need confirmation from sig-scheduling maintainers.  @wybzju ... is it okay if I work on this?

**Comment by wybzju** [comment]
@bharaththiruveedula  ok

**Comment by ahg-g** [comment]
Yeah, this is a bug in preemption
