### ISSUE TITLE
Running benchmarks in pre-submits

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#86935]
I wish benchmarks (`go test -bench=.`) would run as pre-submits, and ideally I would have a few other requirements, some of which makes it non-trivial:
1. We should be able to retrieve the base commits benchmark to compare them
2. We should run with `-test.count=5` or maybe 10
3. We should use [`benchstat`](https://godoc.org/golang.org/x/perf/cmd/benchstat)
4. We should sort the output by magnitude of change
5. We should be able to configure a failure-threshold: changes more than X% negative should fail the pre-submit
6. This should be easily re-usable in other generic repositories

**Comment by apelisse** [comment]
@tedyu @BenTheElder @wojtek-t

**Comment by wojtek-t** [comment]
Blocked on https://github.com/kubernetes/kubernetes/issues/79464 - we need to fix that one first.

Also, I'm not 100% sure about its value - I think it should be possible to trigger an optional presubmit for benchmarks, but I'm not sure I see a ton of value of making that requires and blocking one (especially in the current form, where this is more informative than really checking anything).

**Comment by apelisse** [comment]
I don't think the blocker is a super big blocker, we could ignore this test somehow.

Also I don't know if it needs to be blocking or not (might depend on each individual repository). It would really be helpful for server-side apply [repo](github.com/kubernetes-sigs/structured-merge-diff) since we have A LOT of important benchmarks there, and we're also have a few benchmarks here in Kubernetes, including in integration test where they can provide preliminary marker for things that are going wrong. That'd have a lot of value for us to identify regression early.

**Comment by BenTheElder** [comment]
1\.  is a bit involved but could be done by looking up artifacts from a periodic in GCS, there is not a mapping from commit to results though AFAIK... cc @Katharine
2-4. 🤷‍♂
5. This seems mainly blocked on 1.
6. The implementation probably needs to be in another repo then.

**Comment by wojtek-t** [comment]
> I don't think the blocker is a super big blocker, we could ignore this test somehow.

It's not that easy - because the problem is that it's not a test that is failing, but the fact that it doesn't built. Which seems to be more tricky to exclude.
I don't have time to look into it, but if someone can pick it up, it would be great.

**Comment by apelisse** [comment]
> I don't have time to look into it, but if someone can pick it up, it would be great.

Yeah, let's try to fix it!

> 6. The implementation probably needs to be in another repo then.

Any suggestion?

**Comment by BenTheElder** [comment]
... unclear. repo-infra? test-infra?

**Comment by apelisse** [comment]
Yeah, I don't want to over-worry about that, code can always move ...

**Comment by julianvmodesto** [comment]
For (1):

> >  1. We should be able to retrieve the base commits benchmark to compare them

> 1. is a bit involved but could be done by looking up artifacts from a periodic in GCS, there is not a mapping from commit to results though AFAIK... 

Maybe we could add another git checkout ref to `.extra_refs` that has a `.base_ref = master` so we have both the PR + master checked out, then run tests on master in the same job for the `benchstat` comparison.

**Comment by apelisse** [comment]
Let's forget about that for now? If we could see a graph of the benchmarks like the example that you showed me before, that'd probably be a massive step forward already, thanks Julian!

**Comment by julianvmodesto** [comment]
This is now working as a periodic + presubmit for smd:
https://testgrid.k8s.io/sig-api-machinery-structured-merge-diff#ci-benchmark&graph-metrics=allocs%2Fop&graph-metrics=op%20count&graph-metrics=alloced%20B%2Fop&width=20

https://testgrid.k8s.io/sig-api-machinery-structured-merge-diff#pr-benchmark&graph-metrics=allocs%2Fop&graph-metrics=op%20count&graph-metrics=alloced%20B%2Fop&width=90

Still need to fix the job under sig-scalability.

**Comment by apelisse** [comment]
That's awesome Julian, thank you!

**Comment by apelisse** [comment]
Looking at these two benchmarks, it's actually pretty hard to see how a pull-request (pr-benchmark) is diverging from the master branch (ci-benchmark). I'd be really nice if we could just compare the pull-requests results with the latest ci results.

**Comment by BenTheElder** [comment]
The prowjob pod should probably set guaranteed CPU if we're comparing
results btw...

**Comment by apelisse** [comment]
Yeah, I think that's solved!
