### ISSUE TITLE
Pod-to-NodePort: Pod to send http post to NodePort

### ISSUE THREAD

**Issue by raizik** [kubernetes/kubernetes#86934]
pretty new in Kubernetes, sorry in advance for possible mistakes)

I'm using kind (kind) for my two-node cluster and I have a node.js that simulates an HTTP server that gets HTTP GET requests.

I want to implement a new load balancing algorithm that's based on the pods sending http POST to the load balancer service (in my case - NodePort since it's a local cluster) when they finish a job sent from some external python program. Currently getting this error from pods logs`Error: connect ECONNREFUSED 172.17.0.3:8081`

For this purpose, I'm trying to set pod-to-nodePort connection for sending an HTTP POST with an idle massage whenever the pod is idle (after handling the clients' HTTP GET).

So far, I've tried using golang's ListenAndServe function (which if I understand correctly creates an http server) with the control plane node address (the master node in kind infrastructure), and some port (say 8081) though not sure where's the best placement for calling this function in the code. It's currently being called in NextEndpoint function in roundrobin.go.

I'm aware that there's an option to add a port pair to the ports map of the service via the yaml, but I'm not sure in this case how exactly am I meant to route incoming pod HTTP POST requests in the control plane node to my specific handle function.

What could be the best way to do this?

Code excerpts:

In roundrobin.go:

```
type idleHandler struct{
    lb LoadBalancer
    svcPort proxy.ServicePortName
}

func (ih *idleHandler) handler(w http.ResponseWriter, r *http.Request) {
    //something something
}
```
In function NextEndpoint:

    
```
handlerStruct := &idleHandler{lb: lb, svcPort: svcPort}
    http.HandleFunc("/", handlerStruct.handler)

    if err := http.ListenAndServe("172.17.0.3:8081", nil); err != nil {
    log.Fatal("ListenAndServe: ", err)
    }
```

In server.js:

```
const http = require('http');
const fs = require('fs');
const url = require('url');

//HTTP POST
var postData = JSON.stringify({msg: 'IDLE'})

var options = {
  hostname: '172.17.0.3',   //control plane node
  port: 8081,              //NodePort
  path: '/',
  method: 'POST',
  headers: {
       'Content-Type': 'application/json',
       'Content-Length': postData.length
     }
};

function handleRequest(request, response) {

      //HTTP GET response here...

      //HTTP POST
      var req = http.request(options, (res) => {
  console.log('statusCode:', res.statusCode);
  console.log('headers:', res.headers);

  res.on('data', (d) => {
    process.stdout.write(d);
  });
});

req.on('error', (e) => {
  console.error(e);
});
    //post IDLE
req.end(postData);
}
```
/sig Node
/sig kind/feature 
/sig kind/design
/sig kind/bug

**Comment by aojea** [comment]
/close
answered in the KIND project
https://github.com/kubernetes-sigs/kind/issues/1234
