### ISSUE TITLE
Pod failed to be scheduled due to request resources satisfied in multiple nodes

### ISSUE THREAD

**Issue by zhiyxu** [kubernetes/kubernetes#86943]
**What would you like to be added**:

Let's say I have a 3 nodes cluster, node01 has some special resource "device/gpu".

Now I want to create a pod request some CPU and "device/gpu", but node01 lack of CPU while the other node02 and node03 lack of "device/gpu", then this pod would be in "Pending" state until some CPU on node02 released.

**Why is this needed**:

In fact, all those pods could run in the cluster if properly arranged, so I'm wondering if there are any related function, or any suggestion and solutions to handle this issue properly.

**Comment by zhiyxu** [comment]
sig/scheduling

**Comment by liggitt** [comment]
the scheduler will not evict/rearrange running pods to make it possible to run additional pods of the same priority level
/cc @ahg-g

**Comment by zhiyxu** [comment]
> the scheduler will not evict/rearrange running pods to make it possible to run additional pods of the same priority level
> /cc @ahg-g

Is there any ideas to solve this sort of issue? Priority and preemption could be a solution, but it's a little bit hard to set priorities in advance.

**Comment by alculquicondor** [comment]
What do you mean by "properly arranged cluster"?

If you want pods that don't require GPU to avoid running on nodes that have GPU, you can set node labels and add node affinity

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity
