### ISSUE TITLE
kubectl diff on Service returns error

### ISSUE THREAD

**Issue by aristosvo** [kubernetes/kubernetes#86957]
**What happened**:
`kubectl diff -f service.yml` returns `The Service "xx-service" is invalid: spec.clusterIP: Invalid value: "": field is immutable`.
```xx-service.yml
apiVersion: v1
kind: Service
metadata:
  name: xx-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: tomcat-port
      protocol: TCP
    - name: https-port
      port: 443
      targetPort: tomcat-ssl-port
      protocol: TCP
  selector:
    app: xx-application
```
However, `kubectl apply --dry-run -f service.yml` works well.

**What you expected to happen**:

Both commands should throw the same errors

**How to reproduce it (as minimally and precisely as possible)**:
- `kubectl apply -f xx-service.yml`
- `kubectl diff -f service.yml`

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
  - AKS
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`):
Linux DESKTOP-M2A2CB5 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Can you show the previous service yaml which was used to create the service ?

Thanks

**Comment by apelisse** [comment]
I agree that this must be a bug. `kubectl diff` is supposed to do the same thing that `kubectl apply` would do but with dry-run. Unfortunately, I can't easily reproduce with what you posted, so it'd be really nice if you could show us ... maybe the last-applied-annotations? so that we know what you applied before that? Thanks

**Comment by apelisse** [comment]
cc @julianvmodesto

**Comment by aristosvo** [comment]
Sorry for my delayed response. I expected that the last `kubect apply -f` command was the exact same as the file I diffed against, but these are different. I don't know the reason, but my collegue included clusterIP already in it.

I suspect this doesn't mean the bug isn't there, but at least it is more reproducable:)

kubectl.kubernetes.io/last-applied-configuration:
```
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {},
        "name": "xx-service",
        "namespace": "default"
    },
    "spec": {
        "clusterIP": "10.0.112.36",
        "ports": [
            {
                "name": "http-port",
                "port": 80,
                "protocol": "TCP",
                "targetPort": "tomcat-port"
            },
            {
                "name": "https-port",
                "port": 443,
                "protocol": "TCP",
                "targetPort": "tomcat-ssl-port"
            }
        ],
        "selector": {
            "app": "xx"
        }
    }
}
```

**Comment by tedyu** [comment]
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", 
```
I noticed that server version lags client version.

I wonder if this is reproducible if server runs 1.16+ version.

**Comment by julianvmodesto** [comment]
Oh so because `.spec.ClusterIP` was applied by your colleague (as show in last applied), `kubectl diff` is showing this conflict. If you actually `kubectl apply --server-dry-run` or `kubectl apply`, you'll see this same conflict message. Since you don't want to put `.spec.ClusterIP` in your service yaml, you can `kubectl apply -f service.yaml --force` to remove ownership of `.spec.ClusterIP`. It is immutable, so this would not remove the cluster IP.

**Comment by aristosvo** [comment]
Thanks a lot, I understand and will close the issue.

To summarize my misunderstanding:
I thought the `kubectl diff` should be the same as `kubectl apply --dry-run`, but it is the same as `kubectl apply --server-dry-run`.

**Comment by julianvmodesto** [comment]
You can reproduce this by:

```
kubectl apply -f service.yaml
kubectl get -f service.yaml > service.yaml # export the service.yaml with .spec.ClusterIP
kubectl apply -f service.yaml # now we have ownership of .spec.ClusterIP
sed -i '/ClusterIP/d' ./service.yaml # remove the .spec.ClusterIP

# now the below will show the same conflict
kubectl diff -f service.yaml
kubectl apply -f service.yaml --server-dry-run
kubectl apply -f service.yaml 
```

**Comment by apelisse** [comment]
> I thought the kubectl diff should be the same as kubectl apply --dry-run, but it is the same as kubectl apply --server-dry-run.

Even I got confused for a minute ...
/shrug

Glad this is not a bug!

Thank you guys!
