### ISSUE TITLE
The validity period of the certificate generated by kubeadm should be configurable

### ISSUE THREAD

**Issue by QianChenglong** [kubernetes/kubernetes#86951]
**What would you like to be added**:
The validity period of the certificate generated by kubeadm should be configurable
**Why is this needed**:
At present, the root certificate is valid for 10 years, and the ordinary certificate is 1 year. Deployment in the actual production environment will increase maintenance costs.

![image](https://user-images.githubusercontent.com/1881126/71964248-2cd5fc00-3238-11ea-990c-a6785f569cb8.png)
![image](https://user-images.githubusercontent.com/1881126/71964262-32cbdd00-3238-11ea-8884-82233405dafa.png)
![image](https://user-images.githubusercontent.com/1881126/71964264-35c6cd80-3238-11ea-8a0a-804b3b98f0c8.png)

**Comment by neolit123** [comment]
hi, it's not configurable by design.
having a certificate valid for more than 1 year or a CA for more than 10 years is far from secure.

we decided against enabling this configuration option.
kubeadm still allows you to sign your own certificates and use them instead of generating ones.
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode

/close

**Comment by QianChenglong** [comment]
This function should not be rejected because of security issues. In the private cloud scenario, a large number of customers or businesses need to be deployed, and the services are all accessed in the private network. Users know the consequences of opening here and can afford to use them. Without this feature, you often need to pay attention to which cluster's certificate is about to expire. If you replace it, you need to stop the service. It takes a lot of manpower to deal with these damn expires. Just like iptables, rules should let the user specify when he can clearly understand his needs and consequences. Why must we use security as a reason to reject other possibilities?

**Comment by neolit123** [comment]
> This function should not be rejected because of security issues. In the private cloud scenario, a large number of customers or businesses need to be deployed, and the services are all accessed in the private network. Users know the consequences of opening here and can afford to use them. 

1 year for these certificates is the sane industry default.
if you wish to rotate certificates more often you are free to do so. if you wish to extend the certificate expiration you are not following security practices even for private clouds.

kubeadm has no plans to support customizable certificate expiration from it's API.

you have two options:
- provide external certificates (which kubeadm already supports!)
- fork kubeadm and make your changes

> Without this feature, you often need to pay attention to which cluster's certificate is about to expire. If you replace it, you need to stop the service. It takes a lot of manpower to deal with these damn expires. Just like iptables, rules should let the user specify when he can clearly understand his needs and consequences. Why must we use security as a reason to reject other possibilities?

newer versions of kubeadm gives you some tools to make this easier:

to monitor cert expiration:
`kubeadm alpha certs check-expiration`

to renew certificates:
`kubeadm alpha certs renew`

**Comment by QianChenglong** [comment]
For a large number of clusters, we need to design a special component to periodically check or automatically update the certificate, which is too cumbersome.
