### ISSUE TITLE
Integrate new scheduler benchmark tests with perf dash

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/kubernetes#86972]
**What would you like to be added**:
We have been woking on a new framework to run scheduler benchmark tests. #86160 makes tests configurable via a YAML file and #85685 collects metrics and saves them to a JSON file. Now we need to make sure the perf dash can read the new test artifacts (JSON file).

/sig scheduling

**Comment by liu-cong** [comment]
@ingvagabund, do you want to take this one?

**Comment by ingvagabund** [comment]
Sure :)
/assign

**Comment by ingvagabund** [comment]
In order to complete this task, https://github.com/kubernetes/kubernetes/pull/85861 needs to be merged and the jenkins job responsible for running the perf tests needs to be run a couple of times to produces artifacts the perf dashboard can consume.

**Comment by ingvagabund** [comment]
PR got merged!!!

We need https://github.com/kubernetes/kubernetes/pull/88162 to get merged as well to have the metrics stored under artifacts directory. Then, we can start collecting the metrics as well.

**Comment by ingvagabund** [comment]
Will wait for a day or two to collect more artifacts in https://k8s-testgrid.appspot.com/sig-scalability-benchmarks#scheduler-perf so the plots looks more shiny with more data.
