### ISSUE TITLE
pod scheduler to node, but  kubelet admit failed, pod was outOfmemory

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/kubernetes#86986]
**What happened**:
cluster info:   3 master, 1000 nodes

create pod,  scheduler pod to node,  pod was outofmemory, kubelet log:
Predicate failed on Pod: xihh-b1be980fcf582028y0kkvd1ffxd5jc8_default(c8cff343-2abf-11ea-815b-246e9683be48), for reason: Node didn't have enough resource: memory, requested: 2147483648, used: 128849018880, capacity: 130405863424

use kubectl describe node , we can see node have use 108Gi memory, Allocatable is 127349476Ki.
maybe kubelet cache and kube-api cache are inconsistent,  if restart kubelet , can solve this promlem.
kubelet logs:
![image](https://user-images.githubusercontent.com/8597823/72032747-4d9b6180-32cb-11ea-9592-525fda912ef1.png)

kubectl describe nodes:
![image](https://user-images.githubusercontent.com/8597823/72033090-3610a880-32cc-11ea-98a3-5683aab6eccd.png)

**What you expected to happen**:
pod can be schedulerd and running

**How to reproduce it (as minimally and precisely as possible)**:
 it is difficult to reproduce it
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.8.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos6.2
- Kernel (e.g. `uname -a`):3.10.107 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by snowplayfire** [comment]
https://github.com/kubernetes/kubernetes/pull/73845  may the pr can solve your problem.

**Comment by hongli-my** [comment]
ref to #73845 kube-scheduler's cache are wrong if some event miss, 
but,   nodes's pod info by `docker ps` are Consistent with `kubectl describe nodes`.
kubelet logs: 
```
Predicate failed on Pod: xihh-b1be980fcf582028y0kkvd1ffxd5jc8_default(c8cff343-2abf-11ea-815b-246e9683be48), for reason: Node didn't have enough resource: memory, requested: 2147483648, used: 128849018880, capacity: 130405863424
```
`used: 128849018880` are different with  `kubectl describe nodes`,    kubelet miss some event? 
but  pod's status report by kubelet

**Comment by snowplayfire** [comment]
It's my understanding:

`nodes's pod info by docker ps are consistent with kubectl describe nodes` means datas in etcd are correct,  `kubelet logs are different` means kubelet's cache isn't consistent with etcd. `The problem can be solved after restart kubelet` means the kubelet re-lists all from etcd and re-establish a correct cache.

**Comment by snowplayfire** [comment]
I meet a similar problem:  pod has been scheduled into a new node, but the old node also has the corresponding container. If I try to delete the container on the old node,  the container is recreated on the old container.   If I restart the old node's kubelet, the problem can be solved.
