### ISSUE TITLE
Add pointer to config-default.sh in "Cannot start cluster using os distro" error message

### ISSUE THREAD

**Issue by juliaferraioli** [kubernetes/kubernetes#8699]

**Comment by alex-mohr** [comment]
@juliaferraioli I'm not sure what the actionable item here is.  Can you give an example of the error message you saw and a revised version you'd like to have seen?

**Comment by juliaferraioli** [comment]
Not my error message, but here's the text from the friction log:

$ cluster/kube-down.sh 
Cannot start cluster using os distro: windows
Bringing down cluster using provider: gce

The user had changed their settings which resulted in the mismatch. They then had to dig around to find where the correct config file was located. Instead, the error message could point them to that path:

*Cannot start cluster using os distro: windows*
*Bringing down cluster using provider: gce*
*Please check the distro specified in cluster/$PROVIDER/config-default.sh*

It's a little addition that would save the user a lot of pain.

**Comment by alex-mohr** [comment]
Agreed that getting k8s scripts to work on a new distro is painful.  I think we're going to work on moving away from bash rather than harden all the corner cases.

**Comment by juliaferraioli** [comment]
This was an issue that someone experienced with relatively little usage with k8s, so I don't think that it falls under the corner case category. It will be a pretty common scenario to have people trying out different OS's, especially in the decision-making phase of development. This is "one of the paper cuts" when it comes to developer experience.

I'm reopening this, because DevRel agrees that it's useful information to have in the interim before you finish the work to move away from bash. A DevReller will put in a post-v1 PR fixing this (unless someone else gets to it first).

**Comment by roberthbailey** [comment]
@juliaferraioli - no one has had a chance to fix this; do you think anyone from DevRel will have cycles in the near future?

**Comment by roberthbailey** [comment]
Closing as obsolete due to lack of updates in almost two years.
