### ISSUE TITLE
Remove scheduler/algorithm/priorities/util package [Migration Phase 2]

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#86993]
The logic should move to the plugins using the util logic, or to plugins/helper package if it is shared with multiple plugins.

/assign @Huang-Wei 
/sig scheduling
/priority important-soon
Part of #85822

**Comment by haosdent** [comment]
@Huang-Wei @ahg-g I think I could help in this clean up, could I assign it to me? Or you have started?
