### ISSUE TITLE
test/e2e/framework/volume : the same function generateWriteBlockCmd  and generateWriteFileCmd

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/kubernetes#86992]
I found two differently named functions with the same function in 
see
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/volume/fixtures.go#L548-L568

the git log , see

https://github.com/kubernetes/kubernetes/commit/5fc9e23b507e5ca0d77aeedf0a9dc45075ba22b5#diff-2ff410ea588732f4fe497de3d8dbb7deR625

origin pr , see
https://github.com/kubernetes/kubernetes/pull/79730/files

the function is used by https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/volume/fixtures.go#L518

I don’t know the background at that time, but I’m just confused, so I open an issue to record it.

/sig testing

**Comment by neolit123** [comment]
@tanjunchen 
the functions look the same.
please remove `generateWriteBlockCmd` and use `generateWriteFileCmd` everywhere.
this pairs the function with `generateReadFileCmd`.

if there is demand for unique logic when writing to a block device, the function ` generateWriteBlockCmd` can be reintroduced.
