### ISSUE TITLE
`preStop`-hook doesn't get triggered when a pod is about to be terminated

### ISSUE THREAD

**Issue by ChillyVanilly77** [kubernetes/kubernetes#87016]
Dear Kubernetes-team,

**What happened**:
Recently I was trying to trigger the `preStop`-hook by running for example `kubectl drain` or `kubectl delete pod <pod_name>` which was supposed to run a simple `kill -s SIGINT 1`-command on the master-procces (PID 1) of Postgres, thus trying to achieve a graceful shutdown of Postgres through overriding the standard SIGTERM -> grace-period -> SIGKILL -behaviour.

**What you expected to happen**:
When following the logs of Postgres, I expected to find `LOG:  received fast shutdown request` after what was supposed to be the triggering of the `preStop`-hook. But this was never the case.
I expected the `preStop`-hook to be rather reliable or even guaranteed to execute before a **termination of any sort**, but according to a few members of [this discussion](https://github.com/kubernetes/kubernetes/issues/55807) from a previous issue, this is apparently a bug, while others stated that it is by design yet might not be documented as precisely.

But be it by design or not - this is in my opinion a bit of an issue, since there seems to be no other clean or configurable options such as the [stop_signal](https://docs.docker.com/compose/compose-file/compose-file-v2/#stop_signal) in Docker-compose to customise termination behaviour or anything similar that requires **guaranteed** execution of some script for example before the container in a pod is about to get started/stopped.

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS:
`Ubuntu 18.04.3`

**Comment by tedyu** [comment]
/cc @mgdevstack 
What do you think ?

**Comment by lllamnyp** [comment]
This is, apparently, to be expected. `kill -s SIGINT 1` executes quickly and postgres begins its graceful shutdown. However, the graceful shutdown happens in the background. From the kubelet's point of view, the preStop hook has ran to completion, so kubelet immediately sends a SIGTERM to postgres. What you are looking for, is a handler for SIGTERM in the entrypoint of your container.
