### ISSUE TITLE
BoundServiceAccountTokenVolumes: Pod rejected when solely relying on projected token volumes

### ISSUE THREAD

**Issue by linki** [kubernetes/kubernetes#87028]
**What happened**:

We enabled the `BoundServiceAccountTokenVolume` feature gate on `v1.15.6` to start switching from non-expiring to expiring ServiceAccount tokens as [introduced here](https://github.com/kubernetes/kubernetes/issues/70679). It works well.

We then wanted to completely get rid of the "legacy" non-expiring ServiceAccount token Secrets. To do that we configured `controller-manager` with `--controllers=*,-serviceaccount-token` (so it wouldn't auto-create the Secrets), removed the existing Secrets and removed the reference from the respective ServiceAccount to the Secret. This works as expected: No non-expiring token Secrets are generated.

However, when creating a Pod we now see:
```
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  5s (x2 over 14s)  replicaset-controller  Error creating: No API token found for service account "chaoskube", retry after the token is automatically created and added to the service account
```

This happens because the [AdmissionPlugin](https://github.com/kubernetes/kubernetes/blob/v1.15.7/plugin/pkg/admission/serviceaccount/admission.go#L433) rejects the Pod because it cannot find a ServiceAccount token Secret (because it doesn't exist anymore as intended).

**What you expected to happen**:

When using the `BoundServiceAccountTokenVolume` feature the legacy ServiceAccount token Secrets aren't used anymore, so a Pod should not be rejected if the Secret doesn't exist. The Pod doesn't even use the Secret at all.

**How to reproduce it (as minimally and precisely as possible)**:

* Enable `BoundServiceAccountTokenVolume=true` feature gate
* Start `controller-manager` with `--controllers=*,-serviceaccount-token`
* Create a new ServiceAccount
* Deploy a dummy app using that ServiceAccount
* Observe no Pod being created with `kubectl get pods`
* Describe the corresponding ReplicaSet to see the above Error event.

**Anything else we need to know?**:

Looking at the [relevant code section](https://github.com/kubernetes/kubernetes/blob/v1.15.7/plugin/pkg/admission/serviceaccount/admission.go#L428-L437) it seems that at least one legacy Secret must exist in order for the Pod to get admitted. This is enforced even when `BoundServiceAccountTokenVolume=true` and we're relying on projected token volumes.

Following the code path when `BoundServiceAccountTokenVolume` is enabled reveals that the token [fetched here](https://github.com/kubernetes/kubernetes/blob/v1.15.7/plugin/pkg/admission/serviceaccount/admission.go#L428) is never going to be used later on as there's no SecretVolume to be mounted in [here](https://github.com/kubernetes/kubernetes/blob/v1.15.7/plugin/pkg/admission/serviceaccount/admission.go#L511).

In other words: [`len(serviceAccountToken) == 0`](https://github.com/kubernetes/kubernetes/blob/v1.15.7/plugin/pkg/admission/serviceaccount/admission.go#L428) is just fine when `BoundServiceAccountTokenVolume=true`.

During the transition period it's fine to have the legacy Secrets lying around but ultimately it's desirable to get rid of them because as far as I can tell they are still happily accepted by the API server.

**Environment**:
- Kubernetes version: tested on `v1.15.6` but code seems the same in `v1.16.x` and `v1.17.x`
- Cloud provider or hardware configuration: [AWS](https://github.com/zalando-incubator/kubernetes-on-aws)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 4.15.0-1054-aws
- Install tools: https://github.com/zalando-incubator/kubernetes-on-aws

/kind bug
/sig auth

@kubernetes/sig-auth-bugs

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/87029

**Comment by linki** [comment]
@liggitt Thank you!
