### ISSUE TITLE
[Scheduler] Move snapshot.Snapshot to cache.Snapshot

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87033]
See #86920 for motivation

Snapshot's data structures (map and lists of nodes)  shouldn't be accessed directly by any users, other than its builder (cache.Cache).

We have migrated most of the old usages of these fields to the listers' interfaces. There might be some usages left in tests. But once that's finalized, there is no point in having Snapshot in its own package. It should just be part of the internal cache package.

/sig scheduling
/assign
/kind cleanup

**Comment by alculquicondor** [comment]
Having a second thought, the only blocker is autoscaler.

As of today the requirements are:
- cache needs read/write access to snapshot's data structures.
- autoscaler basically just needs to create listers.

This is one idea I have in mind if those above are the only requirements:
We add an unexported snapshot holder in `internal/cache`. Then `nodeinfo/snapshot.Snapshot` is just something that implement the listers. It could just receive the prepared lists or just the map of nodes (what autoscaler does today).

However, maybe autoscaler will need to update their snapshot at some point without having to recreate it. In that case, we might need to introduce an interface between cache and snapshot that would allow efficient updates.

Before proceeding, I would like to hear from autoscaler team.
/cc @losipiuk

**Comment by losipiuk** [comment]
> However, maybe autoscaler will need to update their snapshot at some point without having to recreate it. In that case, we might need to introduce an interface between cache and snapshot that would allow efficient updates.

As part of migration to scheduler framework we (I) are kinda implementing exactly that. So at the end of the road we will only depend on the interface of `scheduler.listers.SharedLister`. I am not exactly sure that sharing the implementation will give us much benefit. Possibly some duplicate work now could be avoided - but at the cost of stepping each other toes more in the future. And the CA requirements do not necessarily match those of scheduler. E.g. we want to have an efficient mechanism to apply a set of changes on top of snapshot (add some pods, schedule some nodes), and then rollback all of those changes to start scheduling simulation for other node group.

FWIW we are currently thinking of following interface of "snapshot-building-thingy"

```go
type ClusterSnapshot interface {
	// adds node to snapshot
	AddNode(node *apiv1.Node) error
	// removes nodes (and pods scheduled to it) from snapshot
	RemoveNode(nodeName string)
	// adds pod and schedules it to given node
	AddPod(pod *apiv1.Pod, nodeName string) error
	// removes pod 
	RemovePod(namespace string, podName string)

	// branches snapshot state. All modifications can later be reverted to moment of branching via Revert()
	Branch()
	// reverts snapshot state to moment of branching.
	Revert()
	// commits changes done after branching to base cluster state
	Commit()

	// exposes snapshot state as scheduler's SharedLister
	GetSchedulerLister() scheduler_listers.SharedLister
}
```

We create `Framework` with our `DelegatingSchedulerSharedLister` which just holds a mutable reference to `SharedLister` which should be used by `Framework` at given point in time. We change the reference from one `SharedLister` to the other depending on what is the simulated cluster state.

So IMO you can proceed with changes around `Snapshot` implementation and it should not hit us in any way.

**Comment by alculquicondor** [comment]
Sounds good @losipiuk!
Thanks for the detailed explanation of your plans. It looks pretty good.

**Comment by alculquicondor** [comment]
I agree that given the different requirements, sharing the implementation might just hurt us in the long run.

**Comment by ahg-g** [comment]
Thanks @losipiuk, will your implementation be ready in 1.18? can we proceed with Aldo's plans now?

**Comment by losipiuk** [comment]
That is the plan. Go with a change. 

At worst we can alway copy implementation of `SharedLister` from scheduler codebase and still only depend on the interaface.

**Comment by ahg-g** [comment]
sounds good, thanks.
