### ISSUE TITLE
Mark CustomResourceDefinitionStatus fields +optional

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#87040]
**What would you like to be added**:

Currently, the `Status` field on `CustomResourceDefinitions` must be explicitly set to their zero-values due to the fact that they are not tagged `omitempty`.

Ref:

https://github.com/kubernetes-sigs/controller-tools/blob/0dd9d80ad4b98900d6066141dd4233354b25e3f3/pkg/crd/spec.go#L154

**Why is this needed**:

If using a system that automatically compares the provided configuration to the current, it will produce a diff on the updated status after creation. In addition, making sure to explicitly set to zero-values is not the best user experience.

I am happy to provide the fix if this change is approved!

/cc @DirectXMan12 

/sig api-machinery
/area custom-resources

**Comment by liggitt** [comment]
marking them as `// +optional` seems ok, so that client-side validation doesn't complain if they are absent when submitting manifests, but they shouldn't need to be set to omitempty (and at this point, we likely wouldn't change the serialization)

> If using a system that automatically compares the provided configuration to the current, it will produce a diff on the updated status after creation.

Those fields are changed by controllers after creation, so expecting the live API object to exactly match the status is not going to go well anyway.

**Comment by hasheddan** [comment]
> marking them as // +optional seems ok, so that client-side validation doesn't complain if they are absent when submitting manifests, but they shouldn't need to be set to omitempty (and at this point, we likely wouldn't change the serialization)

Good point! I’ll open a fix for this.

> Those fields are changed by controllers after creation, so expecting the live API object to exactly match the status is not going to go well anyway.

Yep! The specific system in question ignores fields that are not set at creation time by default when doing comparison, so if status fields are not included then it will not report a diff.

**Comment by hasheddan** [comment]
@fedebongio I opened a fix for this but CC'ed both you and @jpbetz. Let me know if any additional effort is required. Thanks!
