### ISSUE TITLE
Pod sandbox changed, it will be killed and re-created

### ISSUE THREAD

**Issue by CC1404068613** [kubernetes/kubernetes#87049]
**What happened**:
Pod sandbox changed, it will be killed and re-created
![image](https://user-images.githubusercontent.com/44268973/72118761-2a38eb00-338d-11ea-9ea1-2196aadebb03.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
If possible, can you paste the text from the image ?

Which version are you using ?

Thanks

**Comment by CC1404068613** [comment]
> If possible, can you paste the text from the image ?
> 
> Which version are you using ?
> 
> Thanks



> If possible, can you paste the text from the image ?
> 
> Which version are you using ?
> 
> Thanks
I have found this isssu due to not install network pod so that coredns is not ok ,thank.
