### ISSUE TITLE
Kubernetes support for mips64le

### ISSUE THREAD

**Issue by huchengze** [kubernetes/kubernetes#87056]
I have completed the release of kubernetes for mips64le.
https://travis-ci.com/huchengze/kubernetes/builds/143502702
I wiill make a list about how to do it.

- [ ] **1. Modify [fs.go](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/google/cadvisor/fs/fs.go).**
I have mention it in this [issue](https://github.com/kubernetes/kubernetes/issues/86749), and I create this [PR](https://github.com/google/cadvisor/pull/2368) for cadvisor which is already merged. 
Now we just wait kubernetes to update it.

- [x] 2. **Add CNI support for mips64le.**
CNI plugins has supported mips64le since this [PR](https://github.com/containernetworking/plugins/pull/433). And now we can visit this [URL](https://github.com/containernetworking/plugins/releases/download/v0.8.4/cni-plugins-linux-mips64le-v0.8.4.tgz) to download it.

- [ ] 3. **Build mips64le [kube-cross](https://github.com/kubernetes/kubernetes/tree/master/build/build-image/cross) and [debian-base](https://github.com/kubernetes/kubernetes/tree/master/build/debian-base) images.**
Because of  this [issue](https://github.com/kubernetes/kubernetes/issues/86808), we should build v1.0.0 and v2.0.0 two different versions of debian-base images.
Build kube-cross and v2.0.0 debian-base images : https://github.com/kubernetes/kubernetes/pull/87058.
Build v1.0.0 debian-base image : https://github.com/kubernetes/kubernetes/pull/87066

- [ ] 4. **Build mips64le [debian-hyperkube-base]() and [debian-iptables](https://github.com/kubernetes/kubernetes/tree/master/build/debian-iptables) images.**
Build debian-iptables image : https://github.com/kubernetes/kubernetes/pull/87063
_We can't build mips64le debian-hyperkube-base image now. Because to achieve this [Makefile](https://github.com/kubernetes/kubernetes/blob/release-1.16/build/debian-hyperkube-base/Makefile), we should add mips64le CNI plugins to mips64le debian-hyperkube-base image, but these plugins haven't pushed to https:// storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-mips64le-v0.8.4.tgz._
https://github.com/containernetworking/plugins/issues/436
https://github.com/kubernetes/kubernetes/blob/e3f90df767aefdd6a8031281bf1d9207ddf55a14/build/debian-hyperkube-base/Makefile#L61

- [ ] 5. **Modify the scripts related to this [Makefile](https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile).**
I will create a PR for this when the mips64le debian-hyperkube-base image can be built.

- [ ] 6. **make release.**

**Comment by huchengze** [comment]
@kubernetes/release-engineering
/sig release

**Comment by ydcool** [comment]
CC  @BenTheElder @dankohn  @dims @liggitt

**Comment by justaugustus** [comment]
/sig network
/area release-eng
cc: @kubernetes/release-engineering

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/87058#issuecomment-614491243

**Comment by tpepper** [comment]
adding
/sig architecture
for discussion of entry gating quality requirements (eg: same bucket discussion imo as arm64/linux and illumos(arch?))

**Comment by dims** [comment]
@huchengze please see https://github.com/kubernetes/community/pull/5014
