### ISSUE TITLE
Jenkins GCE e2e: server version sometimes mismatches client version

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#8705]
We seem to have an occasional consistency issue between the client and server versions on our Jenkins GCE e2e project.

Build 6295 failed this morning because the client version was *newer* than the server version:
```
2015/05/22 11:42:29 Running: 'kubectl version --match-server-version=false'
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-666-ge0092a1c230f6c-dirty", GitCommit:"e0092a1c230f6c2f01886823791eef24fbbd6023", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-629-gd9d12fd3f7036c-dirty", GitCommit:"d9d12fd3f7036c92606fc3ba9046b365212fcd70", GitTreeState:"dirty"}
```

The server version matches the build was was immediately running in 6294, which was aborted early. I wonder if (somehow) the cleanup didn't work properly? (Which is a bit worrying if so.)

Here's the version from 6294:
```
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-629-gd9d12fd3f7036c-dirty", GitCommit:"d9d12fd3f7036c92606fc3ba9046b365212fcd70", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-629-gd9d12fd3f7036c-dirty", GitCommit:"d9d12fd3f7036c92606fc3ba9046b365212fcd70", GitTreeState:"dirty"}
```

A short while later, build 6297 failed, this time with the client version *older* than the server version:
```
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-678-g17ac4b1dfc83f1-dirty", GitCommit:"17ac4b1dfc83f197a77cbc7370c7305ef93b719a", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-680-ga823f6d1d50ccb-dirty", GitCommit:"a823f6d1d50ccb1491f4c80db68cfa63ce7a7786", GitTreeState:"dirty"}
```

This one makes a little bit more sense: there was a new build published between downloading the client/test tarballs and setting up the cluster. I'm guessing that somewhere in the cluster setup scripts the latest CI release file was read again, rather than using the version read for the client/test tarballs. (I haven't yet worked out where exactly it's read, but it should be an easier fix.)

cc @quinton-hoole @zmerlynn

**Comment by ixdy** [comment]
A side issue: we should probably figure out why the build git client is being marked dirty. Since we're checking out the head version from GitHub, it should ideally be a clean client.

**Comment by ixdy** [comment]
The -dirty bit is now fixed by #15199.

**Comment by ihmccreery** [comment]
This is caused by different Jenkins jobs uploading to the same GCS bucket and clobbering each other.  In http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4134/ we see:

```
11:55:03 Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.357+61096f49984a17", GitCommit:"61096f49984a1784d32e5c2e4e1de40d1d3e01db", GitTreeState:"clean"}
...
11:55:03 ... calling kube-up
11:55:03 Project: kubernetes-jenkins
11:55:03 Zone: us-central1-f
11:55:05 +++ Staging server tars to Google Storage: gs://kubernetes-staging-a978d0a66e/devel
...
11:55:14 Starting master and configuring firewalls
...
12:01:34 Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.357+61096f49984a17", GitCommit:"61096f49984a1784d32e5c2e4e1de40d1d3e01db", GitTreeState:"clean"}
12:01:34 Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.359+bc55b1a58b8e98", GitCommit:"bc55b1a58b8e98fc30b5e72fe32bf68c1e871d67", GitTreeState:"clean"}
```

Over in http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel/14762/consoleFull:

```
11:55:05 Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.359+bc55b1a58b8e98", GitCommit:"bc55b1a58b8e98fc30b5e72fe32bf68c1e871d67", GitTreeState:"clean"}
...
11:55:05 ... calling kube-up
11:55:05 Project: kubernetes-jenkins
11:55:05 Zone: us-central1-f
11:55:07 +++ Staging server tars to Google Storage: gs://kubernetes-staging-a978d0a66e/devel
```

**Comment by ihmccreery** [comment]
This also explains the issues seen in https://github.com/kubernetes/kubernetes/issues/19189#issuecomment-173781926; the `gce-reboot` job is also running in the same project.

**Comment by ixdy** [comment]
Ah, good sleuthing. We avoided this issue in the PR builds by setting `KUBE_GCS_STAGING_PATH_SUFFIX` (used [here](https://github.com/kubernetes/kubernetes/blob/eaa61a72b05278309010866f10e2e1ab1e36607e/cluster/gce/util.sh#L204)), but maybe we should always be setting `KUBE_GCS_STAGING_PATH_SUFFIX` to include the Jenkins job name (and optionally executor/node number).

**Comment by quinton-hoole** [comment]
@ixdy @ihmccreery The original idea was to run every e2e job in it's own project, to avoid these sorts of name clashes.  But we seem to have regressed and now have many jobs sharing the same projects.   Is project-per-job not a better approach?  It also helps with resource leaks and the likes. Just a thought.

**Comment by ihmccreery** [comment]
@quinton-hoole I'd argue this is actually uncovering a (dev) deployment bug; I should be able to deploy different versions of Kubernetes to the same project.  I know you and I disagree (and probably always will) on the strategy here. :smile:

**Comment by alex-mohr** [comment]
@ihmccreery fwiw I think I agree with @quinton-hoole that if project-per-job avoids this issue and helps identify resource leaks, it's a pragmatic near-term improvement in the state of the world that would result in more benefit than the cost of changing all the everythings to support multi-job-in-project.

Re: devs deploying different versions of k8s to the same project, P3 feature request?

**Comment by ihmccreery** [comment]
@alex-mohr I was just about to suggest the same thing.  I will file a separate issue, and fix this in the short term an easier way.  #18119 is out to make it easier to isolate a run to a project.

**Comment by ihmccreery** [comment]
Also @alex-mohr @quinton-hoole it seems like a reasonable thing (higher than P2) to want to deploy multiple clusters to the same project safely in prod, not just dev.  Disagree?

**Comment by alex-mohr** [comment]
@ihmccreery Multiple clusters in prod using well-defined build versions such as v1.1.4 = P0.  Multiple clusters in prod using our cooked-up test-building system = non-goal?

**Comment by ihmccreery** [comment]
@alex-mohr SGTM; this is prod code, though, not test code; it's used every time we call `kube-up`, regardless of whether it's a CI build or released version.

**Comment by dchen1107** [comment]
FYI: kubernetes-e2e-gce-reboot/10974 has one reboot test failed due to kube-proxy image change. But that build doesn't include pr #20036 yet.

**Comment by ixdy** [comment]
@dchen1107 looks like it. That run used version `v1.2.0-alpha.6.507+c2eb90cc4df191`, but the first build with #20036 was `v1.2.0-alpha.6.511+93168c1edef521`.
