### ISSUE TITLE
HPA support temporary disable function

### ISSUE THREAD

**Issue by mmpei** [kubernetes/kubernetes#87070]
**What would you like to be added**:
there should be a way to disable HPA temporarily. like an annotation `xxxxx/disable: true`. and enable it after this annotation removed or set the value to `false`.
**Why is this needed**:
we want to disable HPA when we are doing upgrading. especially in our scenario, we implement canary strategy using two k8s deployment, HPA mechanism makes the upgrading process unstable, so we want to disable HPA and resume it after upgrading, but not delete it and recreate it after upgrading.

**Comment by hprateek43** [comment]
You would need to add the annotation manually at the start of the upgrade and remove it at the end of your upgrade. A better solution would be to patch the autoscaler min and max value during this. Also, similar issues can be observed during a rolling update. Refer https://github.com/kubernetes/kubernetes/issues/25238

**Comment by mmpei** [comment]
thank you. but our scenarios are different. we use multiple deployment when upgrading using canary strategy, and our process like,
1. scale down the primary deployment and scale up the canary deployment.
2. do testing.
3. adjust the rest of the replicas after all of the tests pass
it will make the metrics highly unstable, and the replicas of deployment changes multi-times. so the best way is to disable HPA.  @hprateek43

**Comment by mmpei** [comment]
i read the issue you mentioned and agree the point `HPA is incompatible with any action to replicas`. so it is better to eliminate HPA but not try to reduce the affect of HPA when you want to adjust replicas. @hprateek43

**Comment by carlpett** [comment]
Just to leave another potential usecase, we've seen some times when there are errors (in the application, or metrics that control the scaling) that cause uncontrolled scaling. As an operational measure, it would be good to be able to temporarily disable the scaling. Right now, I believe the only option is to delete the hpa manually, which isn't a great workflow.
