### ISSUE TITLE
Add ca-certificates install to debian-base image

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#87087]
**What would you like to be added**:

Add `ca-certificates` install to [debian-base image](https://github.com/kubernetes/kubernetes/tree/master/build/debian-base). Or provide a build parameter for installing additional packages.

**Why is this needed**:

[Kubernetes v1.17](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md) deprecated the [debian-hyperkube-base image](https://github.com/kubernetes/kubernetes/tree/master/build/debian-hyperkube-base).  This image installed `ca-certificates` along with many other packages.  Unlike the other packages, `ca-certificates` is often critical to running Kubernetes API server and possibly other components.  Therefore, it would be ideal to install `ca-certificates` by default or at least provide a build parameter for installing additional packages.

**Comment by neolit123** [comment]
> Unlike the other packages, ca-certificates is often critical to running Kubernetes API server and possibly other components. Therefore, it would be ideal to install ca-certificates by default or at least provide a build parameter for installing additional packages.

kubernetes started moving its images to distroless:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md

the plan is for the control-plane images to no longer be distro based in the future, they will not contain a shell or any installed packages, ideally only the binary of the component.

running a control-plane image as a container, the operator must mount `ca-certificates` related host paths (as read-only). if the component is run directly on the host it must has access to the these paths.

/priority awaiting-more-evidence

**Comment by rtheis** [comment]
@neolit123 The static distroless image installs `ca-certificates` per https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md.  We could mount `ca-certificates` via a read-only host path, but that requires us to patch all hosts when `ca-certificates` are updated rather than simply updating the container ... doable but an operational pain.

**Comment by neolit123** [comment]
i did not know that distroless has `ca-certificates`.

one problem with that is that if the component image includes outdated ca-certificates how would one update them? they either have to force a component image upgrade or mount a newer ca-certificates from the host.

in general this is a space that sig-release are responsible for, so leaving the discussion to them.
you can also get feedback on the slack in #sig-release or in this tracking issue: https://github.com/kubernetes/kubernetes/issues/70249

**Comment by rtheis** [comment]
Outdated `ca-certificates` is always a potential problem and either option (container update or host update with mount) could be used to resolve.

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering 
/area release-eng

**Comment by rtheis** [comment]
With the move to static distroless images in 1.19, we can close this issue.
