### ISSUE TITLE
[Failing Test] ci-kubernetes-e2e-gke-gci-serial-sig-cli is failing

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#87092]
**Which jobs are failing**:
ci-kubernetes-e2e-gke-gci-serial-sig-cli

**Which test(s) are failing**:
The `Up` stage has been constantly failing.

**Since when has it been failing**:
This job has been failing since at least 12-26.

**Testgrid link**:
https://testgrid.k8s.io/sig-cli-master#gke-serial&width=20

**Reason for failure**:
Looking at triage https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=ci-kubernetes-e2e-gke-gci-serial-sig-cli
It seems to be that this job is always failing around some variant of the command
```
error creating cluster: error during gcloud container clusters create --quiet --project=k8s-jkns-gke-ubuntu-reboot --zone=us-west1-b --machine-type=n1-standard-2 --image-type=gci --num-nodes=3 --network=bootstrap-e2e --cluster-version=1.18.0-alpha.1.177+40320be679e9bc bootstrap-e2e: exit status 1
```

It seems that the job can easily be fixed by using a different zone (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-serial-sig-cli/1215512182830141458#1:build-log.txt%3A456)
```
W0110 05:57:25.347] ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Failure in zone us-west1-b due to tight resource constraints. You can either try again later or create another node pool in another zone and migrate workloads. (See https://cloud.google.com/kubernetes-engine/docs/tutorials/migrating-node-pool) Recommended alternative zone: us-west1-c).
```

/priority critical-urgent
/milestone v1.18
/cc @kubernetes/sig-cli-test-failures

**Comment by alejandrox1** [comment]
The issue at hand was related to https://github.com/kubernetes/test-infra/issues/16202
Along with that, https://github.com/kubernetes/test-infra/pull/15867 seemed to cause the following issue:
```
W0222 16:51:54.204] ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Location "us-west1-c" does not exist
```

**Comment by alejandrox1** [comment]
I don't think this issue is fixable, xref: https://github.com/kubernetes/kubernetes/issues/88971
there seems to be an issue in the assumptions that the gke-provisioning logic in kubetest (it looks for latest releases that don't exist).
I think at this point we should look into whether this e2e job adds useful information. If it does then we can convert it into a GCE-based job. Else, we should delete it.

**Comment by hasheddan** [comment]
@alejandrox1 any update on this test? Looks like the situation has not improved, are you in favor of removing?

**Comment by alejandrox1** [comment]
Excuse the delayed answer but huge update happened https://github.com/kubernetes/kubernetes/issues/88971
and a ton of GKE-based jobs got removed.
