### ISSUE TITLE
[Flaky Test] gce-cos-master-serial (ci-kubernetes-e2e-gci-gce-serial)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#87104]
**Which jobs are failing**:
`gce-cos-master-serial (ci-kubernetes-e2e-gci-gce-serial)`

**Which test(s) are failing**:
```
[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand Verify if offline PVC expansion works
```

**Since when has it been failing**:
`10th Jan 22:58 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

**Reason for failure**:
```console
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:161
Jan 11 09:06:15.441: while recreating pod for resizing
Unexpected error:
    <*errors.errorString | 0xc0030b10b0>: {
        s: "pod \"security-context-fe81ad46-cccd-48ac-aed0-a7c9a9a4e46d\" is not Running: timed out waiting for the condition",
    }
    pod "security-context-fe81ad46-cccd-48ac-aed0-a7c9a9a4e46d" is not Running: timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:209
```

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.18
/sig storage

**Comment by fengzixu** [comment]
@droslean I would like to handle this failing test.

**Comment by droslean** [comment]
@fengzixu All help is welcome.

**Comment by davidz627** [comment]
+1 I've been seeing this flake a lot recently on `pull-kubernetes-e2e-gce` as well. Happens on various tests

**Comment by droslean** [comment]
since the job is keeps failing because of #87387 it's really hard to track the flakiness of the job. I am closing this issue, and once the job will be fixed, we will track it for any flakiness.
