### ISSUE TITLE
PLEG relist latency metrics are not updated if runtime remote call does not response

### ISSUE THREAD

**Issue by bysnupy** [kubernetes/kubernetes#87108]
It's difficult to detect relist latency increasing or real latency, because `pleg_relist_duration_seconds` or `pleg_relist_latency_microseconds ` does not be updated if runtime remote call does not response due to issues such like "PLEG is not healthy" or runtime down.

**What happened**:

When "PLEG is not healthy" happened, the following "kubelet_pleg_relist_latency_microseconds" is shown not detect real latency. Even though "PLEG is not healthy: pleg was last seen active 3m35.027736415s ago; threshold is 3m0s" start to print out at that time.
i.e.> Metrics format is "`relist latency microseconds` `@epoch a metric is recorded`".
~~~
73240120 @1574745815.321
---> We can guess the relist is stuck at this time as calculating latency duration time included in "pleg was last seen active 3m35.027736415s".

---> Watch out "77793968" latency does not be updated until the node recovered from "PLEG is not healthy".
   It's too difficult to catch out relist latency issue for end users.
77793968 @1574745875.321 
77793968 @1574745905.321
77793968 @1574745935.321
77793968 @1574745965.321
77793968 @1574745995.321

---> @1574745022: NodeNotReady happened at this time.
77793968 @1574746025.321
77793968 @1574746055.321

---> @1574746057: "PLEG is not healthy: pleg was last seen active 3m35.027736415s ago; threshold is 3m0s" starts to print out

---> @1574745069: Recovered as Node Ready
88584176 @1574745145.321: Start to record the pleg latency metrics at this time.
~~~

**What you expected to happen**:

We should detect the relist latency trend during real delay using relist latency metrics.

**How to reproduce it (as minimally and precisely as possible)**:

You can always see the same metrics trend I provided above when any pleg latency happens.

**Anything else we need to know?**:

relist time can be updated after get all the pods using remote runtime call, so if the remote call is stuck with any issue, relist time cannot be updated.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go#L198-L211
```go
	timestamp := g.clock.Now()
	defer func() {
		metrics.PLEGRelistDuration.Observe(metrics.SinceInSeconds(timestamp))
		metrics.DeprecatedPLEGRelistLatency.Observe(metrics.SinceInMicroseconds(timestamp))
	}()

	// Get all the pods.
	podList, err := g.runtime.GetPods(true)
	if err != nil {
		klog.Errorf("GenericPLEG: Unable to retrieve pods: %v", err)
		return
	}

	g.updateRelistTime(timestamp)
```

**Comment by skilxn-go** [comment]
How can you say the latency when this runtime remote call is not finished? Accroding the code piece you show, the PLEGRelistDuration will be update after this runtime remote call finished or timeout

**Comment by bysnupy** [comment]
> How can you say the latency when this runtime remote call is not finished? Accroding the code piece you show, the PLEGRelistDuration will be updated after this runtime remote call finished or timeout

@skilxn-go  You mean, how can we check the latency while the runtime remote call is not finished ?
This issue is, PLEGRelistDuration depends on runtime remote call response. So we check the relist latency using other goroutine, such as Heathy check which is called from syncLoop() additionally.

My thought is as follows.
e.g.>
relist latency is updated two path.
1. every relist process
2. Healthy check through syncLoop() every 10 sec.
If "1." cannot be updated by some issues,  "2." can keep updating the latency regardless of "1." updates.

What about add logic to update metrics here ? : https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go#L136-L148
```go
// Healthy check if PLEG work properly.
// relistThreshold is the maximum interval between two relist.
func (g *GenericPLEG) Healthy() (bool, error) {
	relistTime := g.getRelistTime()
	if relistTime.IsZero() {
		return false, fmt.Errorf("pleg has yet to be successful")
	}
	// Expose as metric so you can alert on `time()-pleg_last_seen_seconds > nn`
	metrics.PLEGLastSeen.Set(float64(relistTime.Unix()))
	elapsed := g.clock.Since(relistTime)

        // MY SUGGESTION is to add PLEGRelistDuration here as follows.
        metrics.PLEGRelistDuration.Observe(metrics.SinceInSeconds(relistTime))
        metrics.DeprecatedPLEGRelistLatency.Observe(metrics.SinceInMicroseconds(relistTime))

	if elapsed > relistThreshold {
		return false, fmt.Errorf("pleg was last seen active %v ago; threshold is %v", elapsed, relistThreshold)
	}
	return true, nil
}
```

**Comment by skilxn-go** [comment]
I think latency is a request-level value. If it's designed like what you want, when people say latency=100ms, how can we figure out whether it means the last request finished in 100ms, or it's just a real time value when request is pending?
Instead of adding this confusing update of latency, why don't you use metrics.PLEGLastSeen to caculate 'how long does this request lasts for' ?

**Comment by bysnupy** [comment]
Thank you for your update @skilxn-go , and it makes more sense. I've also checked the PLEGLastSeen metrics is added recently, and the metrics can be auxiliary metrics whether the relist has latency or not. 
You can close this issue. Thank you again for your review :)
