### ISSUE TITLE
Update hyperkube/master.json and hyperkube/master-multi.json to no longer pass --machines

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#8711]
This flag is deprecated and no longer has any effect.

**Comment by roberthbailey** [comment]
--sync_nodes should also be removed, since it no longer has any effect either.

**Comment by luxas** [comment]
Hasn't this been fixed now? Maybe it could get closed.

**Comment by roberthbailey** [comment]
Yep. I'm not sure when it was fixed but sometime between when I filed it and now it's been resolved.
