### ISSUE TITLE
configmap Key should not follow `[-._a-zA-Z0-9]+`

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#87119]
**What happened**:

**What you expected to happen**:
Configmap as a basic key-value storage, it should contain any thing which is string type.
Now it does not support to use "/"

**How to reproduce it (as minimally and precisely as possible)**:
use 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: taintWhiteNamelist
  namespace: kube-system
data:
  "hello.io/is-host": "true"
```

the console replied: 
```shell
 a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
``` 

**Anything else we need to know?**:
``` go
// IsConfigMapKey tests for a string that is a valid key for a ConfigMap or Secret
func IsConfigMapKey(value string) []string {
	var errs []string
	if len(value) > DNS1123SubdomainMaxLength {
		errs = append(errs, MaxLenError(DNS1123SubdomainMaxLength))
	}
	if !configMapKeyRegexp.MatchString(value) {
		errs = append(errs, RegexError(configMapKeyErrMsg, configMapKeyFmt, "key.name", "KEY_NAME", "key-name"))
	}
	errs = append(errs, hasChDirPrefix(value)...)
	return errs
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhangxiaoyu-zidif** [comment]
I suggest to remove this validation:
```go
	if !configMapKeyRegexp.MatchString(value) {
		errs = append(errs, RegexError(configMapKeyErrMsg, configMapKeyFmt, "key.name", "KEY_NAME", "key-name"))
	}
```

**Comment by zhangxiaoyu-zidif** [comment]
ping @msau42

**Comment by neolit123** [comment]
/remove-sig storage
/sig api-machinery

related to:
https://github.com/kubernetes/kubernetes/issues/83290

changes to the key names were not approved:
https://kubernetes.slack.com/archives/C0EG7JC6T/p1576651152067200

/close
