### ISSUE TITLE
HostPath in FileOrCreate mode does not work properly when the directory where the file is located does not exist

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/kubernetes#87112]
**What happened**:

Using hostpath, when the type is `FileOrCreate` , if the directory of the mounted file does not exist, the mount fails and the pod cannot start normally

**What you expected to happen**:

When the directory where the mounted file does not exist, it can automatically create a directory and complete the mounting

**How to reproduce it (as minimally and precisely as possible)**:

Use FileOrCreate mode hostpath to mount a file that does not exist in the parent directory

**Anything else we need to know?**:
the sample yaml (This directory does not exist `/demo2/demo2/demo1`)
![image](https://user-images.githubusercontent.com/7907809/72219112-4dc28800-357d-11ea-877b-f6bc910de2d8.png)

Error after deployment

![image](https://user-images.githubusercontent.com/7907809/72219129-8bbfac00-357d-11ea-92b3-e8c74b49a991.png)

/sig storage

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wawa0210** [comment]
I will fix this

**Comment by neolit123** [comment]
/remove-kind bug
/kind feature

this is not a bug, but rather a feature-request / change in behavior:

https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

FileOrCreate | If nothing exists at the given path, an empty file will be created there as needed with permission set to 0644, having the same group and ownership with Kubelet.
-- | --

`FileOrCreate` does not give you the guarantee that it will create the path to the file.
if the [PR](https://github.com/kubernetes/kubernetes/pull/87113) is merged or not, the documentation has to be updated to give more clarity on this.

**Comment by wawa0210** [comment]
Thank you for your reply

Based on two aspects, I think when the mode is set to `FileOrCreate` , the directory should be available 

+ Most applications may be stateless and will be scheduled to multiple nodes in the cluster (including later added nodes). When we mount a single file, if we need to manually create the parent directory in the node, it is very difficult and not operable
+ Use hostpath with the mode `DirectoryOrCreate`. This mode will create the file directory successfully, even if the root directory of the mount directory does not exist. I think `FileOrCreate` should also be consistent

<table>
<tr>
<td>DirectoryOrCreate</td>
<td> If nothing exists at the given path, an empty directory will be created there as needed with permission set to 0755, having the same group and ownership with Kubelet. </td>
</tr>
<tr>
<td> FileOrCreate </td>
<td> If nothing exists at the given path, an empty file will be created there as needed with permission set to 0644, having the same group and ownership with Kubelet. </td>
</tr>
</table>
