### ISSUE TITLE
Azure - PIP dns label will be default deleted when there is no service dns annotation

### ISSUE THREAD

**Issue by fseldow** [kubernetes/kubernetes#87127]
**What happened**:
After issue https://github.com/kubernetes/kubernetes/issues/67813 is fixed. Cloud provider will automatically reconcile the Azure Public Ip DNS record same as the service annotation. 
As a result, user finds their DNS record will be deleted if the annotation `service.beta.kubernetes.io/azure-dns-label-name` is not set.
Such a change is a block to users who have set the DNS record on their public IP without using this annotation when they upgrade the cluster. Besides, if the public ip is a user's own public ip, it is also not reasonable to delete the DNS record.

**What you expected to happen**:
We may need to change the reconcile logic. Maybe only delete the DNS record, when the annotation exists but empty value

**How to reproduce it (as minimally and precisely as possible)**:
Manually add the DNS label to Azure Public IP resource via Portal

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.7
- Cloud provider or hardware configuration: Azure

**Comment by porrascarlos802018** [comment]
The fix
helm install helm-nginx-ingress stable/nginx-ingress \
    --namespace ingress-nginx-ns \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set controller.service.annotations."service\.beta\.kubernetes\.io\/azure-dns-label-name"=MY-AZURE-DNS \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
