### ISSUE TITLE
[Failing Test] integration-master (ci-kubernetes-integration-master)

### ISSUE THREAD

**Issue by prksu** [kubernetes/kubernetes#87131]
**Which jobs are flaking**:

```
ci-kubernetes-integration-master
```

**Which test(s) are flaking**:

```
k8s.io/kubernetes/test/integration/client.TestDynamicClient
```

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Reason for failure**:

```shell
--- FAIL: TestDynamicClient (6.68s)
    testserver.go:181: runtime-config=map[api/all:true]
    testserver.go:182: Starting kube-apiserver on port 37255...
    testserver.go:198: Waiting for /healthz to be ok...
    dynamic_client_test.go:88: unexpected pod in list.  ....
```

**Anything else we need to know**:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=dynamic_client_test.go%3A88%3A%20unexpected%20pod%20in%20list.&job=ci-kubernetes-integration-master&test=k8s.io%2Fkubernetes%2Ftest%2Fintegration%2Fclient.TestDynamicClient
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1216620112996470785

/cc @kubernetes/ci-signal 
/sig api-machinery
/priority critical-urgent

**Comment by droslean** [comment]
This flake started to appear after #87044 
@jennybuckley Is this related?

**Comment by jennybuckley** [comment]
I think it probably started flaking because of #87044, but the real issue seems to be that the test is using reflect.DeepEqual instead of semantic.DeepEqual, since when I marshal the actual and expected objects in a failure case, they are identical. I'll make a PR to fix it now

**Comment by oomichi** [comment]
According to https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestDynamicClient this seems to start since 01/11/2020

/cc @oomichi

**Comment by prksu** [comment]
this job become failing today

/remove-kind flake
/kind failing-test
fyi @droslean 
@jennybuckley any idea about this?

**Comment by liggitt** [comment]
yes, being fixed in https://github.com/kubernetes-sigs/structured-merge-diff/pull/145

@jennybuckley, can we rollback the enablement of managed field persistence until this is resolved?

**Comment by liggitt** [comment]
opened revert in https://github.com/kubernetes/kubernetes/pull/87196 to clean up CI signal. Can reintroduce once the serialization issue is resolved
