### ISSUE TITLE
What is ListKind's usefulness in CRD?

### ISSUE THREAD

**Issue by xieyanker** [kubernetes/kubernetes#87133]
Hello, I would like to know what is ListKind's usefulness in CRD?

```shell
# kubectl explain crd.spec.names
...

   listKind	<string>
     ListKind is the serialized kind of the list for this resource. Defaults to
     <kind>List.

...
```

I found this parameter in CRD.spec.names. However, I didn't find any other info about it, anyone can help me?

**Comment by liggitt** [comment]
it controls the Kind returned by the API server for a list request, e.g.
```
apiVersion: acme.com/v1
kind: WidgetList
items:
- apiVersion: acme.com/v1
  kind: Widget
  ...
```

/close
