### ISSUE TITLE
Single prober not discovered via Prometheus cause scalability tests failures

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#87143]
**Which jobs are failing**:
`gce-master-scale-performance (ci-kubernetes-e2e-gce-scale-performance)`

**Since when has it been failing**:
`12th Jan 09:02 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

**Reason for failure**:
```console
:0
[measurement call DnsLookupLatency - DnsLookupLatency error: timed out waiting for the condition
measurement call InClusterNetworkLatency - InClusterNetworkLatency error: timed out waiting for the condition
measurement call DnsLookupLatency - DnsLookupLatency error: measurement DnsLookupLatency has not been started
measurement call InClusterNetworkLatency - InClusterNetworkLatency error: measurement InClusterNetworkLatency has not been started]
:0
```

**Anything else we need to know**:
/sig scalability
/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.18

**Comment by oxddr** [comment]
What happened: two probers pods were started correctly (according to kubelet logs), but were not visible via Prometheus (we use it to detect whether probes have started correctly). 

Two things:
1. Shall we wait for all pods to start? At 5k we could allow some small number or percentage of probes' pod to not start. 
2. If there are any errors from a measurement at start phase they should fail the test fast - we shouldn't wait up until the end of the test.

**Comment by oxddr** [comment]
/priority important-soon

This doesn't seem critical.

**Comment by oxddr** [comment]
The same problem has occurred in gce100 test on 1.16 https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1216872794164301829

**Comment by oxddr** [comment]
/retitle Single prober not discovered via Prometheus cause scalability tests failures

**Comment by droslean** [comment]
Thanks @oxddr

**Comment by droslean** [comment]
thanks @oxddr 

/close
