### ISSUE TITLE
[Failing Test] gce-windows-master (ci-kubernetes-e2e-windows-gce)

### ISSUE THREAD

**Issue by jpreese** [kubernetes/kubernetes#87154]
**Which jobs are failing**:
gce-windows-master (ci-kubernetes-e2e-windows-gce)

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-master

**Reason for failure**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/1216713982044278786

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/milestone v1.18
/sig windows

**Comment by droslean** [comment]
We track this problem in #80534 
Closing...

/close
