### ISSUE TITLE
Move the current pod binding logic into a default Bind plugin [Migration Phase 2] 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#87157]
The current bind logic is currently placed in generic_scheduler.go, it should move to run as Bind plugin that gets configured to execute by default.

Part of #85822
/sig scheduling
/assign @alculquicondor

**Comment by alculquicondor** [comment]
Should we name it `DefaultBinding` or just `Binding`?

**Comment by ahg-g** [comment]
Prefixing with ```Default``` is reasonable in this case I think.
