### ISSUE TITLE
[Scheduler] Make extenders processing a plugin on its own

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87159]
Part of #85822
This plugin would implement the following extension points:

- *PostFilter*: Needs a change of semantics to be able to return a new filtered list (as it's being discussed in #86630).
- *Score*
- *Bind*
- *Preempt*. This needs progress kubernetes/enhancements#1398

/hold

/sig scheduling

/kind cleanup

**Comment by haosdent** [comment]
+1

**Comment by skilxn-go** [comment]
Hi, sorry I didn't see this issue before, and create a same one  #87364.
So, I'm free recently, and I can help with this issue if you need. 😃

**Comment by alculquicondor** [comment]
Well, as you can see, we have 2 blockers for this around the framework interfaces.
So we would need to work on the changes to the KEP first. We can always leave Preemption (see open PR) for later, but there is not much point on only moving `Score` and `Bind`.

**Comment by skilxn-go** [comment]
Yep, but I think filter, bind, and score can be implemented with scheduler plugin now. And the preempt KEP seems will not be implemented in short term.
As discussed in #87364 , I think maybe implement them first will be a good start.

**Comment by skilxn-go** [comment]
Our implementation will not change alot even with the possible change of postFilter interface.

**Comment by alculquicondor** [comment]
There are 2 problems with using the Filter endpoint:

- it doesn't match the format of the extenders (they accept a list of nodes)
- we can't guarantee that extenders would run after all the other filters, which is the current behavior we should preserve.

**Comment by skilxn-go** [comment]
We can use postfilter point, not filter.

**Comment by skilxn-go** [comment]
As I say in my issue:
extender.Filter -> scheduler framework.PostFilter
extender.Bind -> scheduler framework.Bind
extender.Priority -> scheduler framework.Score

**Comment by skilxn-go** [comment]
I can send a pr which implement extender.Filter with framework.PostFilter, if you are not doing the same work. 🌵

**Comment by alculquicondor** [comment]
PostFilter doesn't return a list of Nodes, which wouldn't allow to implement extenders' filters.

**Comment by skilxn-go** [comment]
Why do you care about the return value of PostFilter?
We can wrap extender.Filter verb into a PostFilter, and use the extender.Filter's return value to modify the `filteredNodesStatuses` that used in PostFilter.
Please let me know if I'm making some mistakes.

**Comment by alculquicondor** [comment]
That would be a hack and undocumented behavior (https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#post-filter). Also, we only use the statues for reporting, not to proceed with scheduling.

We should, in fact, be creating a copy of that map before passing it to the plugins, which we haven't done.

**Comment by skilxn-go** [comment]
Yep, you are right. I just think the doc is out-dated and the interface support not only reporting, but also filtering works before.
I agree that modify the `filteredNodesStatuses` is somehow hack. A more clear interface or a new filter point will make it semantically clear.

**Comment by fengzixu** [comment]
@skilxn-go Are you still working on this issue? If you don't mind, I want to handle it. 

/cc @alculquicondor

**Comment by skilxn-go** [comment]
@fengzixu Nope, this feature is finally denied since it's hard to implement extender `filter` in framework.

**Comment by fengzixu** [comment]
Sure. Maybe we can close it. @alculquicondor

**Comment by alculquicondor** [comment]
/close

Yeah, for now better keep Extenders as a separate feature. We might reconsider this in the future.
