### ISSUE TITLE
No restrictions for verbs when creating Role 

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#87180]
**What would you like to be added**:
Add restrictions for verbs with Role creating. Like error reporting or something else.
**Why is this needed**:
When creating a role like:
```
kind: Role
metadata:
  name: test-Role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - error
```
The verb `error` is obviously a bad verb but this Role can correctly been created. And you will find the verb through `selfsubjectaccessreview`(`kubectl auth can-i`):
```
Resources                                       Non-Resource URLs   Resource Names           Verbs
configmaps                                      []             []                      [get  error]
```
Meanwhile, when `resourceName` is set in Role. Actually verbs like `create`, `list` are not useful but there is no checking for this.

This is really getting troubles when getting `Role` and `AccessReview` info, they give wrong messages.

**Comment by skilxn-go** [comment]
I think verb checker  may be useful.
But why do you think 
> when resourceName is set in Role. Actually verbs like create, list are not useful 
?

**Comment by zhouya0** [comment]
@skilxn-go  Thanks for you apply.  See this Issue: https://github.com/kubernetes/kubectl/issues/779

**Comment by skilxn-go** [comment]
Got it~

**Comment by liggitt** [comment]
Verbs other than API verbs are allowed in authorization policy, and are honored when evaluating SubjectAccessReview checks. For example, [verbs like "bind", "use", and "escalate" are used by various aspects of the Kubernetes server](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb), and custom verbs can be used by other consumers of the authorization system.

/close
