### ISSUE TITLE
SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run - possibly invalid test

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#87191]
**What happened**:

I am questioning validity of the test. Comments under `test/e2e/scheduling/predicates.go` of `validates resource limits of pods that are allowed to run` say:
```
// This test verifies we don't allow scheduling of pods in a way that sum of
// limits of pods is greater than machines capacity.
// It assumes that cluster add-on pods stay stable and cannot be run in parallel
// with any other test that touches Nodes or Pods.
// It is so because we need to have precise control on what's running in the cluster.
// Test scenario:
// 1. Find the amount CPU resources on each node.
// 2. Create one pod with affinity to each node that uses 70% of the node CPU.
// 3. Wait for the pods to be scheduled.
// 4. Create another pod with no affinity to any node that need 50% of the largest node CPU.
// 5. Make sure this additional pod is not scheduled.
/*
	Release : v1.9
	Testname: Scheduler, resource limits
	Description: Scheduling Pods MUST fail if the resource limits exceed Machine capacity.
*/
```

The test scenario described as it is sounds reasonable. The only nitpick I have is the very first sentence saying "`This test verifies we don't allow scheduling of pods in a way that sum of limits of pods is greater than machines capacity`". Pod's resource limits are ignored in predicates. They take effect in the scoring phase when priorities are computed. Also, priorities are computed only when there are at least two candidate nodes. So after revisiting the step number 5 it's impossible to make sure the additional pod does or does not get scheduled when setting the resource limits. There are either no candidate nodes or one. In which case the limits are ignored and the test passes in the first case and fails in the second. In case there are at least two candidate nodes, one of them will always get picked. In which case the additional pod gets scheduled (no matter what the resource limits field says).

In the framework:
- resource limits are accessed through `ResourceLimits.PostFilter` method [1]
- `ResourceLimits.PostFilter` is used to perform pre-scoring [2]
- in the scoring phase score is computed through `ResourceLimits.Score` method [3]

The test is alternating between passing and failing state. It passes when predicates give empty list of candidate nodes and failing when the list of candidate nodes is non-empty. Thus, making the pod resource limits ineffective.

[1] https://github.com/kubernetes/kubernetes/blob/be26fbc638ff5ed952ccae70e68baa712b3c60c8/pkg/scheduler/framework/plugins/noderesources/resource_limits.go#L141-L153
[2] https://kubernetes.io/docs/concepts/configuration/scheduling-framework/#post-filter
[3] https://github.com/kubernetes/kubernetes/blob/be26fbc638ff5ed952ccae70e68baa712b3c60c8/pkg/scheduler/framework/plugins/noderesources/resource_limits.go#L106-L125

**What you expected to happen**:

Have another node schedule the additional pod validating that all saturated nodes (with `filler-pods-*` scheduled) have lower score (0 in case of `ResourceLimits` plugin). Or, invalidate the test by removing it.

Can anyone check the test validity and confirm/disprove my statement about ineffectiveness of the resource limits?

**How to reproduce it (as minimally and precisely as possible)**:
Make sure there is at least one node with non-zero free cpu resource before running the step 5.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master HEAD
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by ingvagabund** [comment]
cc @kubernetes/sig-scheduling-test-failures

**Comment by ingvagabund** [comment]
@bsalamat I have noticed you refactored the test in https://github.com/kubernetes/kubernetes/pull/53169. Can you still recall the original intent of the test? I can't grasp how the limits are actually taken into account.

**Comment by ahg-g** [comment]
I agree, I think the test is wrong, the scheduler doesn't make fit decisions on resource limits. In the test, [the pod that gets created at the end](https://github.com/kubernetes/kubernetes/blob/be26fbc638ff5ed952ccae70e68baa712b3c60c8/test/e2e/scheduling/predicates.go#L297) should have ```Requests``` set.

do you mind fixing the test and the update the comment please?

**Comment by ingvagabund** [comment]
> do you mind fixing the test and update the test comment please?

On it
/assign
