### ISSUE TITLE
Kubernetes securityContext sysctl settings not applied in pod

### ISSUE THREAD

**Issue by jeffdesc** [kubernetes/kubernetes#87198]
**What happened**:
When configuring all components to use sysctl override configuration, the pod is not being configured properly. The settings are configured per deployment (even tried a single pod) but the specific '/proc' is still not what I was needed. **This is a rootless pod, we're running a custom user in this container.**

The configured deployment, Pod Security Policy and Kubelet config is attached here: https://gist.github.com/jeffdesc/d0a727a118d2e526a210b45253851a8c

When the following sysctl is configured...:
```
sysctls:
  - name: net.ipv4.ip_forward
    value: "1"
```

... then the setting is not propagated properly:
```
custom-user@test-sysctl-1-7c58dff94c-c9s2d:/$ cat /proc/sys/net/ipv4/ip_forward
0
custom-user@test-sysctl-1-7c58dff94c-c9s2d:/$ sysctl -a | grep -i ipv4.ip_forward
net.ipv4.ip_forward = 0
```

**What you expected to happen**:
When the following sysctl is configured...:
```
sysctls:
  - name: net.ipv4.ip_forward
    value: "1"
```

... then the setting is not propagated properly:
```
custom-user@test-sysctl-1-7c58dff94c-c9s2d:/$ cat /proc/sys/net/ipv4/ip_forward
1
custom-user@test-sysctl-1-7c58dff94c-c9s2d:/$ sysctl -a | grep -i ipv4.ip_forward
net.ipv4.ip_forward = 1
```

**How to reproduce it (as minimally and precisely as possible)**:
Configure deployment, Pod Security Policy and Kubelet like this: https://gist.github.com/jeffdesc/d0a727a118d2e526a210b45253851a8c

Then spin up the deployment and verify if the setting is configured with: `cat /proc/sys/net/ipv4/ip_forward`.

**Anything else we need to know?**:
- The container is **configured rootless** using a custom user (uid 10000)
- A Pod Security Policy is applied and not allowing any privileged containers (which has to remain)

The flag is set in Docker, but when it's spin-up in Kubernetes the flag is being rewritten. Example:
```
$ docker run --rm -it test-local-user:1.10.3.27 /bin/bash
user-agent@ebbc6cd9b52b:/$ cat /proc/sys/net/ipv4/ip_forward
1
user-agent@ebbc6cd9b52b:/$ exit

$ kex test-sysctl-1-7c58dff94c-c9s2d /bin/bash
user-agent@test-sysctl-1-7c58dff94c-c9s2d:/$ cat /proc/sys/net/ipv4/ip_forward
0
```

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.16.3`
- Cloud provider or hardware configuration: Virtual machines on VMware
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2303.3.0
VERSION_ID=2303.3.0
BUILD_ID=2019-12-02-2049
PRETTY_NAME="Container Linux by CoreOS 2303.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):
```
Linux <FQDN> 4.19.86-coreos #1 SMP Mon Dec 2 20:13:38 -00 2019 x86_64 Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz GenuineIntel GNU/Linux
```

- Install tools: Kubespray
- Network plugin and version (if this is a network-related bug): Calico (v3.7.3)
- Others: none

**Comment by ikogan** [comment]
I just happened to run into this issue as well, also a deployment, same sysctl:

```
# docker inspect kubelet
...
        "Config": {
            ...
            "Image": "rancher/hyperkube:v1.14.1-rancher1",
            ...
            "Entrypoint": [
                "/opt/rke-tools/entrypoint.sh",
                "kubelet",
                "--fail-swap-on=false",
               ...
                "--allowed-unsafe-sysctls=net.ipv4.ip_forward"
            ],
...
```

```
# kubectl describe podsecuritypolicy elevated-psp
Name:  elevated-psp

Settings:
  Allow Privileged:                       true
  Allow Privilege Escalation:             true
  Default Add Capabilities:               <none>
  Required Drop Capabilities:             <none>
  Allowed Capabilities:                   *
  Allowed Volume Types:                   *
  Allowed Unsafe Sysctls:                 net.ipv4.ip_forward
  Allow Host Network:                     true
  Allow Host Ports:                       0-65535
  Allow Host PID:                         true
  Allow Host IPC:                         true
  Read Only Root Filesystem:              false
  SELinux Context Strategy: RunAsAny      
    User:                                 <none>
    Role:                                 <none>
    Type:                                 <none>
    Level:                                <none>
  Run As User Strategy: RunAsAny          
    Ranges:                               <none>
  FSGroup Strategy: RunAsAny              
    Ranges:                               <none>
  Supplemental Groups Strategy: RunAsAny  
    Ranges:                               <none>
```

```
# kustomize build kubernetes/gateway-only
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      containers:
      - name: gateway
        ...
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
         ...
      securityContext:
        sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
      ...
```

Environment:

- Install tools: Rancher deployed, Rancher 2.2.4
- Cloud provider or hardware configuration: CentOS VMs on Proxmox
- Network plugin and version: Calico 3.4.0

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
# uname -a
Linux kubernetes-one.public.org 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tuananh170489** [comment]
Same issue with @jeffdesc

**Comment by marquiz** [comment]
I was unable to reproduce this issue (tried with Kubernetes v1.17 and v1.14 on CentOS and Ubuntu). Is the podsecuritypolicy somehow involved with the issue? Does everything work as expected if you disable the PodSecurityPolicy admission controller?

**Comment by harutyundermenjyan** [comment]
Hello,
I have the same issue as well, the cluster deployed by the rancher, checked for PodSecurityPolicy, it disabled by default.

**Comment by dims** [comment]
same problem as https://github.com/kubernetes/kubernetes/issues/92266 ?

**Comment by EmilyM1** [comment]
Alot of good info here. Sifting through it I think this is notable:
`$ docker run --rm -it test-local-user:1.10.3.27 /bin/bash
user-agent@ebbc6cd9b52b:/$ cat /proc/sys/net/ipv4/ip_forward
1
user-agent@ebbc6cd9b52b:/$ exit

$ kex test-sysctl-1-7c58dff94c-c9s2d /bin/bash
user-agent@test-sysctl-1-7c58dff94c-c9s2d:/$ cat /proc/sys/net/ipv4/ip_forward
0`

At core this seems to be due to an overwrite between k8/Docker/PodSecurityPolicy on some not all clusters.

**Comment by mogaika** [comment]
Calico overwriting `net.ipv4.ip_forward`
Check: https://github.com/projectcalico/cni-plugin/blob/b9f0ee57c2cffe429eb84c82e922c2fcd0dd9eb8/pkg/dataplane/linux/dataplane_linux.go#L414
As I understand you can add `"allow_ip_forwarding": true` to cni config

**Comment by xilu0** [comment]
I have the same issue as well, the cluster deployed by the kubeadm.

**Comment by mogaika** [comment]
@xilu0 Network plugin?

**Comment by xilu0** [comment]
@mogaika Thank you for responding to my message, I use calico and I find the reason that needs to set allow_ip_forwarding in calico-config.
![image](https://user-images.githubusercontent.com/23609955/92373330-c12e9080-f130-11ea-8df4-1c00281ffc8c.png)

**Comment by mogaika** [comment]
@xilu0 can you confirm that ```"allow_ip_forwarding": true``` worked for you? Or issue still persists?

**Comment by xilu0** [comment]
It works for me. thanks
