### ISSUE TITLE
ci-kubernetes-kubemark-500-gce failing on 1.14 & 1.15

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#87200]
**Which jobs are failing**:
ci-kubernetes-kubemark-500-gce-stable2
ci-kubernetes-kubemark-500-gce-stable3

**Which test(s) are failing**:
setting up the tests

**Since when has it been failing**:
since change to using per release perf-tests repository branches

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-1.15-500
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-1.14-500

**Reason for failure**:
```
W0114 15:32:11.714] I0114 15:32:11.714357   25155 util.go:71] 8/9 targets are ready
W0114 15:32:11.764] F0114 15:32:11.751347   25155 clusterloader.go:236] Error while setting up prometheus stack: timed out waiting for the condition
```

**Anything else we need to know**:

**Comment by jkaniuk** [comment]
Fixed
/close

**Comment by justaugustus** [comment]
@jkaniuk -- There is no information whatsoever on how this was fixed. I'd expect that for a failing test issue.

/reopen

**Comment by justaugustus** [comment]
cc: @kubernetes/ci-signal

**Comment by jkaniuk** [comment]
Older perf-tests branches (1.14, 1.15) have some problems with setting up Prometheus stack in kubemark tests.
Kubemark periodic tests were changed to use release-1.16 perf-tests branch - PR was linked above.

This solution takes less time than debugging all issues on those branches but in the same time it does not invalidate the promise/reason for creation of perf-tests branches - so that changes on perf-tests master would not break presubmits/release breaking tests on old releases.

In general, perf-tests branches should match kubernetes branches, however value of keeping purity of such assignments on old branches is probably not worth time spent on debugging all issues on them.
This assignment should be eventually consistent, as new releases would have 1 to 1 mapping to perf-tests, and old branches will be gradually phased out.

**Comment by jkaniuk** [comment]
Tests are green for last few days
/close
