### ISSUE TITLE
Failing test: ci-kubernetes-integration-master

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/kubernetes#87216]
**Which jobs are failing**:
ci-kubernetes-integration-master

**Which test(s) are failing**:
Overall stage is failing

**Since when has it been failing**:
01/12

**Testgrid link**:
https://testgrid.k8s.io/sig-cli-master#integration-cmd&width=20

**Reason for failure**:

**Anything else we need to know**:
link to error: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1217157432359260162#1:build-log.txt%3A8706

**Comment by liggitt** [comment]
resolved by https://github.com/kubernetes/kubernetes/pull/87196

/close
