### ISSUE TITLE
How to push CNI plugins to https://storage.googleapis.com/kubernetes-release/network-plugins?

### ISSUE THREAD

**Issue by huchengze** [kubernetes/kubernetes#87228]
To fix the step 4 of this [issue](https://github.com/kubernetes/kubernetes/issues/87056), I need to push the mips64le CNI plugins to 
https:// storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-mips64le-v0.8.4.tgz.

I see that the mips64le CNI plugins are already released in
https://github.com/containernetworking/plugins/releases/download/v0.8.4/cni-plugins-linux-mips64le-v0.8.4.tgz

Will these plugins regularly pushed to _https:// storage.googleapis.com/kubernetes-release/network-plugins_?

**Comment by dims** [comment]
/sig network

@dcbw @thockin who has access to https:// storage.googleapis.com/kubernetes-release/network-plugins ?

**Comment by justaugustus** [comment]
@dims -- I've opened https://github.com/kubernetes/kubernetes/pull/87562 to pull CNI downloads from GitHub releases instead of this GCS bucket with unclear ownership.

**Comment by justaugustus** [comment]
@huchengze @ydcool -- With the merge of https://github.com/kubernetes/kubernetes/pull/78819, CNI plugins will now be retrieved from `https://storage.googleapis.com/k8s-artifacts-cni/release/`, which is a GCS bucket with shared control between CNI plugin maintainers and the Kubernetes Release Engineering subproject.

When CNI plugins creates a new release, we'll ensure that we're updating that bucket.
You can track that work here: https://github.com/kubernetes/sig-release/issues/245

**Comment by ydcool** [comment]
Got it, thank you!


 
---Original---
