### ISSUE TITLE
Services need fine-grained permissions

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#8723]
We may want to let users create services, but not let them use all the possible options.
- often we might not want a user to be allowed to pick ServiceType = NodePort because this consumes global resources.
- possibly we might not want a user to be allowed to pick ServiceType = LoadBalancer, since this exposes services outside the cluster.
- Possibly user-specified PortalIP is needs restriction too?

For Pods we have a proposal to make a SecurityConstraint that controls some security sensitive fields which are grouped into a SecurityContext.    Does this pattern apply to service as well in some way?

 Sometimes we want to let a principal create pods, but not allow them to use all the possible options on pods.  One way we are looking at doing this is to group some sensitive options

**Comment by erictune** [comment]
#8655 is about NodePort, which is one of the sensitive values.

**Comment by erictune** [comment]
#7893 is about SecurityContextConstraints.

**Comment by justinsb** [comment]
Another reason for an ACL mechanism for LoadBalancer: it typically costs money (~ $20 for 5 rules on GCE, $15 each LB on AWS), and you typically can't create very many per cloud account (on AWS, the default limit is 20 per region).

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
We can quota usage of both load balancers and node ports in a namespace to
ensure that a namespace cannot consume any.  I will get an example quota
soon.

**Comment by derekwaynecarr** [comment]
@erictune - an example doing this with quota:

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    services.nodeports: "2"
    services.loadbalancers: "2"
```

You can set either to 0 to prevent consumption of either.

This is new to kube 1.3 - thanks to @sdminonne

**Comment by sdminonne** [comment]
yep, @derekwaynecarr not sure if I've to do something for release notes on  #24247 and #22154

**Comment by derekwaynecarr** [comment]
You should be fine.  Both are labeled release note.

**Comment by sdminonne** [comment]
thanks

**Comment by erictune** [comment]
Quota seems good for nodePort.

For LoadBalancer, I was hoping we could express this via RBAC.  Some roles can expose things to the internets, and some can't.

**Comment by smarterclayton** [comment]
For now quota handles this pretty effectively.

**Comment by liggitt** [comment]
quota and admission webhooks cover this for now
