### ISSUE TITLE
Unable to switch to VM LIST because of dataDisk.createOption issues

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#87232]
**What happened**:

PR #86817 switched to list vm instead of get when getting virtual machine, which would help to mitigate the throttling issues when there're a lot of VMs in the cluster.

However, it introduced some weird issues when running pull-kubernetes-e2e-azure-disk tests (refer https://github.com/kubernetes/kubernetes/pull/87122#issuecomment-573921532 for more details). The error message is :

```
 "message": "The property 'dataDisk.createOption' cannot have the value 'Empty' when property 'dataDisk.managedDisk.id' is set."
```

Hence, #87210 reverted the commit.

We should recheck why LIST VM would introduce the above issue and reenable the LIST after it gets fixed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/area provider/azure
/cc @andyzhangx @chewong

**Comment by zqingqing1** [comment]
assign @zqingqing1

**Comment by nilo19** [comment]
a quick test in https://github.com/kubernetes/kubernetes/pull/97105, the azure disk tests still fail, with a similar error message:
```
Dec  8 06:16:47.434: INFO: At 2020-12-08 06:02:43 +0000 UTC - event for azuredisk-volume-tester-lvchm: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "pvc-c0325832-01b6-48ba-8f0a-a81f0bee3829" : Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {
  "error": {
    "code": "PropertyChangeNotAllowed",
    "message": "Changing property 'dataDisk.managedDisk.id' is not allowed.",
    "target": "dataDisk.managedDisk.id"
  }
}
```

**Comment by andyzhangx** [comment]
correct, there is issue with the above PR.

**Comment by nilo19** [comment]
one possible walkaround: use GET for azure disk only and LIST for the rest
