### ISSUE TITLE
Ability to specify internal interface and external interface in Kubeadm

### ISSUE THREAD

**Issue by yp28** [kubernetes/kubernetes#87244]
It seems like by default kubeadm tries to figure out the internal-ip by looking at what the hostname resolves to in `/etc/hosts`. However, this is not ideal since it resolves to the public ip on some cloud providers.

**What would you like to be added**:
I'd like the ability in kubeadm/KubeletConfiguration to specify what it should use as the internal-ip and what it should use as the external-ip.

**Why is this needed**:
To have a proper overview in `kubectl get nodes`, as well as making sure that all internal comms use the internal ip address.

Related: kubernetes/kubeadm#1987

**Comment by stgleb** [comment]
When you do `kubeadm join` in JoinConfig you can configure nodeRegistration

```
nodeRegistration:
  kubeletExtraArgs:
    node-ip: {{ .InternalIP }}
```

Does it help in your case?

**Comment by yp28** [comment]
Although that does help for the representation of the internal-ip, the external-ip then gets lost in the overview of nodes using the Kubernetes API. On top of that, it'd mean that you'd have to have a different JoinConfiguration for every node in the cluster, whereas with defining an interface there's generally only a single configuration file.

**Comment by stgleb** [comment]
Okay, but I am not sure how would you differentiate between internal/external ip throught kubeadm configuration. I agree that is inconvenient from user prospective.

**Comment by neolit123** [comment]
@yp28 

> Although that does help for the representation of the internal-ip, the external-ip then gets lost in the overview of nodes using the Kubernetes API

external IPs in kubernetes are managed by cloud provider integration and this is something that kubeadm does not handle. internal-ip has a slightly misleading meaning in k8s - it's the IP of the node, no matter if picked from external or internal interface.

> On top of that, it'd mean that you'd have to have a different JoinConfiguration for every node in the cluster, whereas with defining an interface there's generally only a single configuration file.

it's unlikely that kubeadm will allow passing interface by name from `InitConfiguration` to be able to determine where to pick an IP for joining nodes. what if the joining nodes are not replicas and have completely different network setups?

i think this preference to not use external IPs requires manual steps with the current defaults of the kubelet.

@stgleb 

> When you do kubeadm join in JoinConfig you can configure nodeRegistration

this is indeed the only workaround. the kubelet picks an external IP by default, unless one passes `--node-ip`. if you don't want to use the kubeadm config you can alternatively pass `--node-ip` using `/etc/default/kubelet`:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

**Comment by yp28** [comment]
Misleading indeed. 
> what if the joining nodes are not replicas and have completely different network setups?
Then they're probably deployed using different configuration anyway, so they'll need a different JoinConfiguration anyway.

My use-case is this: I deploy machines using Terraform, and only having the node-ip option forces me to generate a new configfile for each and every node, bloating the output of Terraform plans. Having to specify an interface will allow me to only generate a single configfile that can be used for all machines. When using a different configuration in terms on NICs will have a different entry in Terraform anyway, so I'll need to generate a new configfile anyway. 

If there's an entry for external-ip and internal-ip in the output of `kubectl get nodes -o wide`, then why not use it? Or at least make it less confusing.

**Comment by neolit123** [comment]
> If there's an entry for external-ip and internal-ip in the output of kubectl get nodes -o wide, then why not use it? Or at least make it less confusing.

i have no historic context of why this separation of external-ip vs internal-ip exists, but as i explained above external-ip is set by cloud provider integration with the kubelet. to get more feedback on this topic you must ask the owners of the kubelet - sig-node, `#sig-node` on the k8s slack.
