### ISSUE TITLE
 The connection to the server <$ MASTER>: 6443 was refused-did you specify the right host or?

### ISSUE THREAD

**Issue by wybaron** [kubernetes/kubernetes#87268]
I encountered the following problems during the kubernetes single node test. I tried to solve the problem in a general way. Looking forward to getting everyone's help.
cause:
    Perform a forced shutdown test of the kubernetes host (single node) without shutting down kubernetes related services.
Current situation:
    After starting the server, I cannot access the kubernetes dashboard, use the command:
    # kubectl get pod
Shows: The connection to the server <$ MASTER>: 6443 was refused-did you specify the right host or?
Thanks everyone for your help！

**Comment by liggitt** [comment]
That message means the kubernetes API server is not running. Ensure you have configured it to start on machine startup, or manually restart the API server.
