### ISSUE TITLE
Container stuck in Waiting even for permanent errors (e.g. image not found) and restartPolicy=Never

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/kubernetes#87278]
**What happened**:
Container **stuck** in Waiting even for **permanent** errors (e.g. image not found) and **restartPolicy=Never**

Event:
`      "message": "Failed to pull image \"nginx:notag132\": rpc error: code = Unknown desc = Error response from daemon: manifest for nginx:notag132 not found",
`

Pod Status:
```
    "containerStatuses": [
      {
        "name": "nginx",
        "state": {
          "waiting": {
            "reason": "ImagePullBackOff",
            "message": "Back-off pulling image \"nginx:notag132\""
          }
        },
        "lastState": {},
        "ready": false,
        "restartCount": 0,
        "image": "nginx:notag132",
        "imageID": ""
      }
```

**What you expected to happen**:
If we can make sure that the container meet **permanent** errors (such as above image/tag not found), we would better just fail the container, instead of keep retrying it (i.e. stuck in container waiting).

In this way, we can get below benefits:
1. Save cluster avaliable resource since the Pod may be already bound to a node and with resource allocated (such as above image/tag not found). So even if the Pod cannot be ran, its resource still cannot be used by other Pods in a guaranteed way.
2. Save platform (dockerd, kubelet, container registry, etc) workload for these useless retries
3. Save user's time and effort to determine the failure and correct his podspec/podtemplatespec. 
Currently, they have to infer the root cause based on Pod `events `(not stable) and `reasons `(hard to infer, since above `ImagePullBackOff `cannot tell it is a permanent error)
4. (Think controller as above user) Controller generally will take actions based on the Failed Pod, such as fail the Job, rollback the Deployment/StatefulSet revision, etc. But they can hardly take actions based on the Pending Pod (caused by Waiting Container), i.e. based on the `events `and `reasons`. I saw Deployment progressDeadlineSeconds, but it is not reliable, as the real error may not be permanent.
5. etc

Given above benefits, seems it is reasonable to **at least provide an option** in PodSpec, to let user to specify if he want to fail the container on permanent errors. (And maybe we can reuse the restartPolicy field, i,e, if restartPolicy=Never, we will not retry on permanent errors)
And the default value for this option could keep current behaiour unchanged.

**How to reproduce it (as minimally and precisely as possible)**:
Create Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: imagetest
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:notag132
```

**Anything else we need to know?**:
This kind of issue have been reported again and again.
AFAIK, it helps to fix below issues:
https://github.com/kubernetes/kubernetes/issues/85992
https://github.com/kubernetes/kubernetes/issues/18568
https://github.com/kubernetes/kubernetes/issues/14519
https://github.com/kubernetes/kubernetes/issues/67250

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yqwang-ms** [comment]
/sig node
/sig apps
@dims @bgrant0607 @nikhiljindal  @smarterclayton PTAL

**Comment by JamesMurkin** [comment]
Hi,

Just to add another example to this that I hope is relevant.
If you make an pod with an invalid image name. For example as simple as having a capital letter in the image name. The pod will forever be stuck in Pending with InvalidImageName.

This will never recover, the image is invalid. So I think it should fail the pod/container.

An example of this:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: invalid-image-test
spec:
  restartPolicy: Never
  containers:
  - name: invalid-image
    image: Alpine:3.10
```

**Comment by liggitt** [comment]
ImageNotFound is not necessarily a permanent error. Deployment pipelines can start a deployment at the same time the required image is being pushed, and the pod startup waits for the image to become available.

**Comment by yqwang-ms** [comment]
@liggitt So, why if other Pod dependent missing are treated as permanent error, such as we will receives forbidden (404) if the Pod's PriorityClass cannot be found. 

Another example is:
kubelet will just fail Pod if the resource predicate check failed, such as InsufficientResourceError: OutOfcpu, etc
https://github.com/kubernetes/kubernetes/blob/b82a1d46003bf38f13cab864c0be09feefd27c4f/pkg/kubelet/lifecycle/predicate.go#L133-L136

So we treat InsufficientResourceError as permanent error, however, the error may be disappeared in future if other resources on the node is released later. So it is also not necessarily a permanent error, and kubelet should periordically try to check the predicate again and again?

And what I mean here is that, we **should not bet on future to classify errors**, for example, if we can change all things (cluster setup, k8s code, k8s objects, user's code/data, etc) in future, there should be no permanent error anymore, because the "all things" I just mentioned can include the fix for the permanent error.


Anyway, if we still think it is not necessarily a permanent error in some cases, like Deployment. 
But for other cases, like Job, the more common case is that user specified a wrong image tag/name, we would better **provide an option** to let user consider it as permanent error.

**Comment by yqwang-ms** [comment]
From another aspect, for long running service (replicaset, statefulset, etc), we can consider all/most errors can be fixed on the fly later (by human or machine), so there is no permanent error. This is the common case for service.

However, for batch job, usually user will not try to fix the bad job on the fly, they just want fail the bad job, release resource, get failure notification, revise the job, then retry with the revised job. So, permanent error is very useful at least for the batch job scenario.

**Comment by yqwang-ms** [comment]
And even if for the Deployment case, ImageNotFound cause the Pod failed, then the Pod is still controlled by the restartPolicy=Always, so it will be still retried.  

Furthermore, now user have choice to configure it, by restartPolicy, and it is desired support more user scenario as I mentioned above.

**Comment by yqwang-ms** [comment]
And at least we should **refine the container waiting reason** when ImageNotFound. 
Such as change existing:
```
        "state": {
          "waiting": {
            "reason": "ImagePullBackOff",
            "message": "Back-off pulling image \"nginx:notag132\""
          }
        }
```
To be:
```
        "state": {
          "waiting": {
            "reason": "ImageNotFound",
            "message": "Back-off pulling image \"nginx:notag132\""
          }
        }
```

So that controller or user of the pod can take actions based on the more specific reason.

**Comment by yqwang-ms** [comment]
@liggitt As I mentioned above, is it reasonable to **just provide an option** to fail fast ImageNotFound? PTAL Thanks

**Comment by yqwang-ms** [comment]
@liggitt could you pls take a time to reconsider this issue and below comment?
https://github.com/kubernetes/kubernetes/issues/88193#issuecomment-659858179
