### ISSUE TITLE
kubelet can't unregister csiplugin after csiplugin pod is deleted from node

### ISSUE THREAD

**Issue by k2huang** [kubernetes/kubernetes#87282]
**What happened**:
```
Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: context deadline exceeded"
```

Before deleting csiplugin pod, we will firstly remove register unix domain socket </var/lib/kubelet/plugins_registry/xxx-reg.sock>, which will trigger kubelet unregister csiplugin.
After we update our k8s cluster from v1.14.3 to v1.16.3, I noticed that above error logs, meanwhile `kubectl get csinode node-xxx`, I can see old plugin in spec.drivers list but it should not(The error does not happen in v1.14.3).

**What you expected to happen**:
csiplugin can be unregistered by kubelet exactly，and there are no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csinode daemonset as describing at [here](https://github.com/kubernetes-csi/node-driver-registrar#example)

**Anything else we need to know?**:
maybe this issue was imported by the [commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)
And after reading code implementation, I find kubelet will dial unix domain socket <var/lib/kubelet/plugins_registry/xxx-reg.sock> when it's trigger by removing xxx-reg.sock, which is confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Maybe we can establish a map from socketPath to (handler, infoResp.Name) so that within unregisterPluginFunc, we don't need to call dial().

I can send out a PR if the above is adopted.

**Comment by tedyu** [comment]
I think the following change should handle the absence of unix domain socket :
```
diff --git a/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go b/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go
index a16546601df..932c01163a1 100644
--- a/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go
+++ b/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go
@@ -24,6 +24,7 @@ import (
        "context"
        "fmt"
        "net"
+       "os"
        "time"

        "k8s.io/klog"
@@ -138,11 +139,15 @@ func (og *operationGenerator) GenerateUnregisterPluginFunc(
        actualStateOfWorldUpdater ActualStateOfWorldUpdater) func() error {

        unregisterPluginFunc := func() error {
-               client, conn, err := dial(socketPath, dialTimeoutDuration)
-               if err != nil {
-                       return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+               var client registerapi.RegistrationClient
+               var conn *grpc.ClientConn
+               if _, err := os.Stat(socketPath); !os.IsNotExist(err) {
+                       client, conn, err = dial(socketPath, dialTimeoutDuration)
+                       if err != nil {
+                               return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+                       }
+                       defer conn.Close()
                }
-               defer conn.Close()

                ctx, cancel := context.WithTimeout(context.Background(), time.Second)
                defer cancel()
```
This way, the unregistration should be able to proceed.

@k2huang @taragu 
What do you think ?

**Comment by tedyu** [comment]
I have a patch which implements what I described above.

**Comment by davidz627** [comment]
@tedyu can you link the patch here, I can't seem to see it

**Comment by tedyu** [comment]
@davidz627 
See #88006
