### ISSUE TITLE
join master fails with: error decoding certificate key: encoding/hex: invalid byte: U+006D 'm'

### ISSUE THREAD

**Issue by x3nb63** [kubernetes/kubernetes#87280]
**What happened**:

joining a master to the cluster fails.

**What you expected to happen**:

it to succeed or tell me an error I can understand.

**How to reproduce it (as minimally and precisely as possible)**:

```
[root@ktestmaster ~]# kubeadm join kmaster.host.domain:6443 --token ur8g2u.jmhyt6j0hq6XXXXX --discovery-token-ca-cert-ha[4/1845]
6:d54087774006d5d9bb14479f170ce4c8e6d3739270b1710216baee78a0aYYYYY --control-plane --certificate-key masterjoin --ignore-preflight-errors=all                                                                                                                 
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks before initializing the new control plane instance
        [WARNING NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[download-certs] Downloading the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace error execution phase control-plane-prepare/download-certs: error downloading certs: error decoding certificate key: encoding/hex: invalid byte: U+006D 'm'
To see the stack trace of this error execute with --v=5 or higher
[root@ktestmaster ~]#
```
Tell me if you need that stack trace.

**Anything else we need to know?**:

this `encoding/hex: invalid byte: U+006D 'm'` part of the error looks as its coming from the X509 parser of OpenSSL.

I have no clue what its trying to tell me. My other master looks functional:

```
[kubectl@kmaster ~]$ kubectl get nodes
NAME                 STATUS   ROLES    AGE   VERSION
kmaster.host.domain   Ready    master   23h   v1.17.0
[kubectl@kmaster ~]$
```

**Environment**:
- Kubernetes version (use `kubectl version`):

 `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: own hardware
- OS (e.g: `cat /etc/os-release`): `CentOS Linux release 8.0.1905 (Core)`
- Kernel (e.g. `uname -a`): `Linux ktestmaster.host.domain 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: 
 - `dnf` using https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
 - `dnf` installing `docker-ce` using https://download.docker.com/linux/centos/7/source/nightly  (they have no CentOS 8 repo yet)

**Comment by neolit123** [comment]
/area kubeadm
/sig cluster-lifecycle
/triage support

> --certificate-key masterjoin 

your certificate key is not valid - it should be a 64 character long HEX string.
when you create a "init" node with the `--upload-certs` extra flags it should give you this key.

you can execute the upload on demand, using:
`kubeadm init phase upload-certs --upload-certs`
this will give you a new key.

please reopen if you have further questions.

/close

**Comment by neolit123** [comment]
> could this get added to the documentation... The token value is well documented, this is not.

the command "kubeadm init phase upload-certs --upload-certs" and what a "certificateKey" is are documented in the HA docs:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#stacked-control-plane-and-etcd-nodes

**Comment by davhdavh** [comment]
I don't see anywhere it is documented it needs to be a string of `[a-f0-9]+`, not sure what the length requirements is, 32 or 64 both work

**Comment by neolit123** [comment]
> I don't see anywhere it is documented it needs to be a string of `[a-f0-9]+`, not sure what the length requirements is, 32 or 64 both work

that is true.
please watch this ticket. or even better...help us by sending the PRs:
https://github.com/kubernetes/kubeadm/issues/2928
