### ISSUE TITLE
Informer invokes XXXFunc multiple times when adding/updating/deleting CRD

### ISSUE THREAD

**Issue by life1347** [kubernetes/kubernetes#87284]
**What happened**:

I used the informer code generated by `code-generator` and notice that informer invokes XXXFunc multiple times when adding/updating/deleting CRD.

```go
c := versioned.New(client.V1().RESTClient())
factory := externalversions.NewSharedInformerFactoryWithOptions(c, 30*time.Second)
ir := iio.New(factory, metav1.NamespaceDefault, nil).V1()

envInformer := ir.Environments().Informer()
envInformer.AddEventHandler(k8sCache.ResourceEventHandlerFuncs{
    AddFunc: func(obj interface{}) {
        logger.Info("add", zap.Any("obj", obj))
    },
    UpdateFunc: func(oldObj, newObj interface{}) {
        logger.Info("update", zap.Any("oldobj", oldObj), zap.Any("newobj", newObj))
    },
    DeleteFunc: func(obj interface{}) {
        logger.Info("delete", zap.Any("obj", obj))
    },
})

envInformer2 := ir.Environments().Informer()
envInformer2.AddEventHandler(k8sCache.ResourceEventHandlerFuncs{
    AddFunc: func(obj interface{}) {
        logger.Info("add 2", zap.Any("obj", obj))
    },
    UpdateFunc: func(oldObj, newObj interface{}) {
        logger.Info("update 2", zap.Any("oldobj", oldObj), zap.Any("newobj", newObj))
    },
    DeleteFunc: func(obj interface{}) {
        logger.Info("delete 2", zap.Any("obj", obj))
    },
})
```

If `N` informers are created and get started like

```go
go envInformer.Run(make(chan struct{}))
go envInformer2.Run(make(chan struct{}))
```

If a CRD is added/updated/deleted, each informer invokes it's own XXXFunc `N` times.
For example, if a CRD is updated, then each informer will call UpdateFunc `N` times.

There are two workarounds

1. use factory to start informers

```go
factory.Start(make(chan struct{}))
```

2. use the same informer to add event handlers. 

**What you expected to happen**:

I expect the informer only invokes XXXFunc one time.

**Question**

1. Is it a bug?
2. If it's not a bug, are we always expected to start all informers with `factory.Start(make(chan struct{}))`? Or, could we start an informer like `informer.Run(make(chan struct{}))`

**Environment**:
- Code-generator SHA: 0826954c61ed88ac5d75e771ade6aae646ca5268

**Comment by tedyu** [comment]
bq. use the same informer to add event handlers

+1

**Comment by liggitt** [comment]
> 2\. are we always expected to start all informers with `factory.Start(make(chan struct{}))`

I believe that is the case. @deads2k, can you confirm?
