### ISSUE TITLE
Apiserver<->etcd watches broken for infrequently changing types

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#87292]
As promised on sig-scale sync today, I'm filing an issue regarding the problem I recently saw on one of our production clusters. Summary:

- we triggered a rolling upgrade of our etcd cluster
- as soon as the first etcd instance was replaced, the master instance which was holding watches with that instance had to to re-establish those watches
- around the time when it tried doing so, I saw multiple watches were terminated from the apiserver to clients:

```
...
W1223 21:31:33.728228       1 cacher.go:125] Terminating all watchers from cacher *storage.StorageClass
W1223 21:31:33.728456       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.728499       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.728568       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.728595       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.728969       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.729048       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.729111       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.732458       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.732770       1 cacher.go:125] Terminating all watchers from cacher *unstructured.Unstructured
W1223 21:31:33.732825       1 cacher.go:125] Terminating all watchers from cacher *rbac.Role
...
```
- The reason why that happened iiuc is because apiserver could no longer continue watches (corresponding to those object types) with etcd because of revision history (for those object types) falling out of etcd's window. See these logs:
```
E1223 21:31:32.728577       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
E1223 21:31:32.728579       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W1223 21:31:32.728596       1 reflector.go:256] storage/cacher.go:/config.istio.io/opas: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
E1223 21:31:32.728602       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
E1223 21:31:32.728606       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W1223 21:31:32.728611       1 reflector.go:256] storage/cacher.go:/config.istio.io/signalfxs: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
W1223 21:31:32.728624       1 reflector.go:256] storage/cacher.go:/config.istio.io/httpapispecs: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
W1223 21:31:32.728630       1 reflector.go:256] storage/cacher.go:/config.istio.io/circonuses: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
...
E1223 21:31:32.798621       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
W1223 21:31:32.798640       1 reflector.go:256] storage/cacher.go:/authentication.istio.io/policies: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
```
- All those `*unstructured.Unstructured` type watches correspond to CRDs and I checked that the cluster has tens of CRD types (a bit typical of istio). The objects in those types were hardly ever changing. And for commonly changing types (like pods, deployments), I wasn't seeing watches breaking

Regarding why the apiserver watches with etcd closed, the following is my theory:
- Apiserver keeps watches with etcd for each resource type. And the RV for that watch gets updated to newer number each time a watch event is delivered for that resource type
- So if there were no changes to any object of a given type, no watch event gets delivered for a long time (and hence that watch stays at the same RV value)
- And since etcd is made to truncate old revision history every few mins (compaction), the RV for the watch trying to re-establish is "too old" now (because objects of that resource type change infrequently and etcd compacted that old RV by now), so watch can't be continued

Couple questions I have here:
- Is the above reasoning correct?
- Would etcd progress notify feature help avoid such watch terminations?

cc @wojtek-t @jpbetz @mm4tt @kubernetes/sig-scalability-bugs

**Comment by liggitt** [comment]
/remove-kind bug

A watch terminating on a rarely changed resource is expected, and is not a bug. Clients are expected to relist and obtain a fresh resourceVersion when they encounter this scenario. See https://github.com/kubernetes/website/blob/master/content/en/docs/reference/using-api/api-concepts.md#efficient-detection-of-changes:

> When the requested watch operations fail because the historical version of that resource is not available, clients must handle the case by recognizing the status code 410 Gone, clearing their local cache, performing a list operation, and starting the watch from the resourceVersion returned by that new list operation.

The question about whether etcd progress would make this happen less often is a good one.

**Comment by mm4tt** [comment]
I think the progress notify may help here, IIUC it could be configured so etcd would send progress notifications on a regular interval even if no changes for a given resource type happened. That should help avoid the case you described where apiserver falls out of the etcd revision history

Leaving for @jpbetz to confirm :)

**Comment by wojtek-t** [comment]
Yes - progress notify was design exactly to solve this case.

We're looking into the progress notify a bit deeper and try to use it solve more problems than this one - you may want to follow this KEP if you're interested:
https://github.com/kubernetes/enhancements/pull/1404

So yes - I agree with Jordan - this is not a bug. At the same time, we're looking into it.
