### ISSUE TITLE
v1.15.8 hyperkube docker image reports v1.15.9-beta0 version

### ISSUE THREAD

**Issue by dlisin** [kubernetes/kubernetes#87294]
**What happened**:
`hyperkube kubelet --version` executed inside `k8s.gcr.io/hyperkube-amd64:v1.15.8` container reports version `v1.15.9-beta.0`

**What you expected to happen**:
Version `v1.15.8` should be reported

**How to reproduce it (as minimally and precisely as possible)**:
Execute:
```
> docker run --rm k8s.gcr.io/hyperkube-amd64:v1.15.8 /hyperkube kubelet --version                                                                                              
```

**Comment by neolit123** [comment]
related to https://github.com/kubernetes/release/issues/1020

actually let's consolidate these.
please add a comment to the above issue that hyperkube is also affected.

thanks
/close
