### ISSUE TITLE
kubectl taint --help example doesn't work

### ISSUE THREAD

**Issue by multi-io** [kubernetes/kubernetes#87296]
**What happened**:

`kubectl taint --help` says:

```
...
Examples:
   ...
  # Add to node 'foo' a taint with key 'bar' and no value
  kubectl taint nodes foo bar:NoSchedule
```

That doesn't work:

```
$ kubectl taint nodes foo bar:NoSchedule
error: at least one taint update is required
```

It doesn't matter whether there is a node "foo" or not. It doesn't seem to contact the API at all.

**What you expected to happen**:

Examples form the help texts should work.

**Anything else we need to know?**:

Looking at https://github.com/kubernetes/kubernetes/blob/7d15d41eb87f8e6977a8947efe3edf7a75c1d01d/pkg/kubectl/cmd/taint/taint.go#L121-L156, it seems to want either a `=` or `-` in the argument. Indeed, `kubectl taint nodes foo bar=:NoSchedule` does work and does the right thing, i.e. set a taint with key `bar` and no value.

**Environment**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
$
```

**Comment by neolit123** [comment]
> bar=:NoSchedule does work and does the right thing, i.e. set a taint with key bar and no value.

i believe there were updates about this at some point.
a PR is welcome

/remove-kind bug
/kind documentation
/sig cli

side note:
> client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

always make sure the client MINOR version is equal or +1, or -1 of the server MINOR version. in this case it's +2, which is unsupported.

**Comment by zhouya0** [comment]
@bharaththiruveedula Do you mind if I submmit a PR on this because I met this issue before?

**Comment by bharaththiruveedula** [comment]
@zhouya0 I assigned the issue today itself and already started working on it. I will send the PR by end of today. But thanks for showing the interest.

**Comment by multi-io** [comment]
Are we updating the documentation or the code now? Right now `kubectl taint nodes foo bar:NoSchedule` fails but `kubectl taint nodes foo bar:NoSchedule-` works (because of the "-"), which isn't very consistent at all, so I'd suggest to actually fix kubectl itself do do what the help page says.
