### ISSUE TITLE
New pods expanded using hpa cannot be allocated traffic

### ISSUE THREAD

**Issue by mengjinmm** [kubernetes/kubernetes#87304]
What happened:

The deployment is probably like this: 
One svc deploys NGINX, then one svc deploys fpm, and then NGINX proxyes to fpm through svcname, so that the PHP project is accessed using nginx. The problem is: I use hpa to expand the fpm pod Half, but found that the request did not come to this new pod, why is this? If it is a ready pod, traffic can be distributed normally.
I used the ab tool for stress testing. When using a GET request, the traffic can be normally distributed to the newly expanded pod, but my POST request using the json file cannot be properly distributed. The expanded pod has no traffic, and the CPU usage shows 0m.

Question
Is it a bug?

Environment:
Kubernetes version 1.15
Network plugin calico

hpa.yaml
`apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-test
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hpa-test
  maxReplicas: 8
  minReplicas: 1
  metrics:
    type: Resource
    resource:
      name: cpu
      targetAverageValue: 0.1`

**Comment by neolit123** [comment]
> Kubernetes version 1.11.10

this version is long out of support. 1.15 will be out of support with the release of 1.18 in March.

**Comment by mengjinmm** [comment]
> > Kubernetes version 1.11.10
> 
> this version is long out of support. 1.15 will be out of support with the release of 1.18 in March.

Same problem with Kubernetes version 1.1.5

**Comment by mengjinmm** [comment]
The stress test command using ab is
`ab -n 5000 -c 10 -p "test.json" -T "application/json; charset=UTF-8" -k -r -v4 "http://…"`

The returned value is
`LOG: header received:
HTTP/1.1 200 OK
Date: Fri, 17 Jan 2020 06:01:59 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 202
Connection: keep-alive
App-Code: 0
Orig-Content-Length: 202
Orig-Content-Type: application/json
Orig-Date: Fri, 17 Jan 2020 06:01:58 GMT
Modelid: fd1f8c2b-747c-49a8-b05a-6005a8a87580
Route: me/ip
Orig-Server: TornadoServer/5.0.2
Status: HTTP/1.1 200 OK

{"code": 0, "data": {"result": [{"value": "no", "status": 0, "detail": "", "msg": null, "probDict": "", "prob": 0.9}]}, "metaInfo": {"route": "me/ip", "modelId": "fd1f8c2b-747c-49a8-b05a-6005a8a87580"}}
LOG: Response code = 200`

But the cpu index of the pod is 0
`kubectl describe hpa -n kube-system`
`
Name:                    hpa-test
Namespace:               kube-system
Labels:                  <none>
Annotations:             kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"hpa-test","namespac...
CreationTimestamp:       Fri, 17 Jan 2020 10:53:26 +0800
Reference:               Deployment/hpa-test
Metrics:                 ( current / target )
  resource cpu on pods:  990m / 100m
Min replicas:            1
Max replicas:            8
Deployment pods:         4 current / 4 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     False   BackoffBoth       the time since the previous scale is still within both the downscale and upscale forbidden windows
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource
  ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  SuccessfulRescale  43s   horizontal-pod-autoscaler  New size: 4; reason: cpu resource above target`

`kubectl top pods -n kube-system`
`
NAME                                                  CPU(cores)   MEMORY(bytes)
hpa-test-4b66n                                         997m         198Mi
hpa-test-62wrr                                             0m           133Mi
hpa-test-jpns5                                              0m           133Mi
hpa-test-trns7                                               0m           133Mi`
