### ISSUE TITLE
Support for cookie based session affinity

### ISSUE THREAD

**Issue by tanmaybinaykiya** [kubernetes/kubernetes#8731]
Creating a new issue as https://github.com/GoogleCloudPlatform/kubernetes/issues/2867  is closed. 
To add support for sticky sessions based on Cookies. If no one is working on this, I'd like to pick it up. Will need some help with the design for the same. If you have any thoughts please comment here. 

An approach I have thought is to set a randomised string in a cookie for every new request (new = requests without the set cookie), create a map from this string to the service pod IP and the next time you see this cookie, you serve it with the mapped pod IP.

**Comment by erictune** [comment]
The current load balancer works at layer 3.  Cookies are at layer 7.  Layer 7 load balancing is a significant project which I don't think we will be taking on prior to our v1.

**Comment by pmorie** [comment]
@pweil-

**Comment by pesho** [comment]
> An approach I have thought is to set a randomised string in a cookie for every new request (new = requests without the set cookie), create a map from this string to the service pod IP and the next time you see this cookie, you serve it with the mapped pod IP.

This is a bad idea, as the map would have to be synchronized/shared between all proxies in the cluster. Otherwise a new request with a cookie can hit a different proxy, which won't recognize the randomized id.

The right approach is to just set the pod id in the cookie.

**Comment by pweil-** [comment]
> The right approach is to just set the pod id in the cookie

I agree with this.  Synchronization across proxies is not unheard of (ie. HAProxy peers with stick-tables) but using a consistent hash in the proxy based on the source to select a destination would avoid synchronization altogether.

**Comment by mikedanese** [comment]
This would be a feature of ingress. cc @bprashanth

**Comment by ofyaniv** [comment]
Is this implemented now?

**Comment by wstrange** [comment]
The nginx ingress implements cookie-based sticky load balancing

**Comment by ofyaniv** [comment]
Great. 
Cookie based sticky load balancing for Tomcat8 is invaluable for our implementation on AWS.

Does this have a doc?
How would ingress setup for sticky load balancing look like?

**Comment by wstrange** [comment]
See
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md

**Comment by danielbonatto** [comment]
Updating reference:

https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md

**Comment by brthor** [comment]
Other links 404

https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/affinity/cookie/README.md

**Comment by Hamdan-Atypon** [comment]
it is 2019 and we still need some filtering on services level (cookies, http header and other stuff) without using Nginx Ingress ..
