### ISSUE TITLE
[Failing Test] gce-master-scale-performance: single CoreDNS pod doesn't pass readiness check

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#87324]
**Which jobs are failing**:
gce-master-scale-performance

**Which test(s) are failing**:
ClusterLoaderV2

**Since when has it been failing**:
01/16

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-performance

**Reason for failure**:
Single coredns doesn't pass readiness probe. Prometheus times out waiting for all coredns pods to be up and running.

**Anything else we need to know**:
n/a

/sig scalability
/priority critical-urgent
/assign

**Comment by oxddr** [comment]
We don't collect logs from CoreDNS so I am not able to tell, why exactly it failed readiness probe. There were at least tens of them scheduled in the cluster, so if there is a bug in CoreDNS it's not deterministic. I had a look at there no 5** returned to any API call from CoreDNS.

**Comment by chrisohaver** [comment]
If it failed to respond to a readiness probe, then its a problem with CoreDNS starting up.
If it returned a not ready response to the readiness probe, then it's probably due to coredns being unable to establish a connection to the API.

**Comment by oxddr** [comment]
CoreDNS failed to respond to readiness probe (503 code was returned), so I
assume this it the former.
