### ISSUE TITLE
Cleanup scheduler test to instantiate plugins dynamically

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#87328]
In our scheduler tests, we rely on a hard-coded instantiation of empty `pluginSet` for necessary `extensionPoint`. It'd be good to handle the instantiation dynamically, so every time we add a test, the author doesn't need to worry about whether the `pluginSet` for an extension point has been instantiated or not.

Here are some occurrences, but it would be good to search thoroughly:

```
⇒  ag "TODO: instantiate the plugins dynamically."
pkg/scheduler/scheduler_test.go
675:	// TODO: instantiate the plugins dynamically.
733:	// TODO: instantiate the plugins dynamically.

pkg/scheduler/core/generic_scheduler_test.go
788:			// TODO: instantiate the plugins dynamically.
840:	// TODO: instantiate the plugins dynamically.
1121:			// TODO: instantiate the plugins dynamically.
1585:			// TODO: instantiate the plugins dynamically.
1885:			// TODO: instantiate the plugins dynamically.
2386:			// TODO: instantiate the plugins dynamically.
```

/sig scheduling
/kind cleanup

/assign @fengzixu
(according to https://github.com/kubernetes/kubernetes/pull/87261#discussion_r367749950)

**Comment by Huang-Wei** [comment]
Can't assign to @fengzixu, but you're free to take it if you're still interested.

/good-first-issue

**Comment by fengzixu** [comment]
@Huang-Wei I am not sure if I misunderstand the `instantiate plugins dynamically`.

First of all, after I searched the comments `TODO: instantiate the plugins dynamically` in the code base, I found different tests required different default and empty plugins.

Do you mean instantiating all the plugins? Use global variables and then share them across all tests.

**Comment by Huang-Wei** [comment]
> Do you mean instantiating all the plugins?

Nope. We should prevent using global variables.

I meant that "plugins" doesn't need to be instantiated and then passed to function `RegisterPluginFunc`; instead, it can be an empty point object, and then inside `RegisterXYZPlugin` function, in particular in `getPluginSetByExtension()`, it then instantiates the proper `PluginSet` if it's not instantiated.

**Comment by fengzixu** [comment]
I think this issue has been resolved by another person. 
https://github.com/kubernetes/kubernetes/commit/4a5ab84dccc2d6b899a5c1d49b2478ec355071c9#diff-718c5036402a4013245b26f23dc1d824L786
https://github.com/kubernetes/kubernetes/pull/87261#discussion_r368742257

**Comment by Huang-Wei** [comment]
@fengzixu exactly.

We can close it.
