### ISSUE TITLE
k8s.gcr.io/pause:3.1 non-amd64 images claim to be for amd64

### ISSUE THREAD

**Issue by vrothberg** [kubernetes/kubernetes#87325]
**What happened**:

Non-amd64 images of k8s.gcr.io/pause:3.1 claim to be for amd64. Obviously, those images are executing just fine but the image configs claim to be for the amd64 architecture. We just started noticing the issue as the github.com/containers/image library has some more rigorous checks now.

**What you expected to happen**:

Each image config should contain the correct architecture.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ podman pull --override-arch=arm  k8s.gcr.io/pause:3.1
Trying to pull k8s.gcr.io/pause:3.1...
  Image architecture mismatch: image uses "amd64", expecting "arm"
Error: error pulling image "k8s.gcr.io/pause:3.1": unable to pull k8s.gcr.io/pause:3.1: unable to pull image: Image architecture mismatch: image uses "amd64", expecting "arm"
```

A more detailed analysis can be found here: https://github.com/containers/libpod/issues/4877#issuecomment-575637147

**Anything else we need to know?**:

I suggest to update the 3.1 images. Although most runtimes/container engines are happily eating the image, the configs still claim to be for a different architecture. We haven't noticed the issue since the os/arch validity checks are fairly new in the containers/image library.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rphillips** [comment]
cc @ixdy  @kubernetes/release-engineering

**Comment by dims** [comment]
cc @mkumatag

**Comment by mkumatag** [comment]
I think this is happening because we cross-build these docker images x86 architecture and inspect shows am64 for that particular image it is trying to pull:

```
[root@flexmk3 pause]# docker inspect gcr.io/google-containers/pause-arm:3.1
[
    {
        "Id": "sha256:e11a8cbeda8688fdc3a68dc246d6c945aa272b29f8dd94d0ea370d30c2674042",
        "RepoTags": [
            "gcr.io/google-containers/pause-arm:3.1"
        ],
        "RepoDigests": [
            "gcr.io/google-containers/pause-arm@sha256:c84b0a3a07b628bc4d62e5047d0f8dff80f7c00979e1e28a821a033ecda8fe53"
        ],

.....
......
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 374116,
        "VirtualSize": 374116,
        "GraphDriver": {
....
.....
```

**Comment by mkumatag** [comment]
Will have to figure out a way to tag the appropriate architecture while building docker image, I see an experimental flag `--platform` flag been introduced which can be used to fix this issue but unfortunately it is not working properly when we build it `FROM scratch` image

**Comment by saschagrunert** [comment]
> Will have to figure out a way to tag the appropriate architecture while building docker image, I see an experimental flag `--platform` flag been introduced which can be used to fix this issue but unfortunately it is not working properly when we build it `FROM scratch` image

Hey @mkumatag :wave:, I'm currently working on setting the arch/OS for a container image during image build (see https://github.com/containers/buildah/pull/2097). We could think about building our images with buildah/podman if the feature gets accepted and fits our needs. WDYT?

**Comment by mkumatag** [comment]
> > Will have to figure out a way to tag the appropriate architecture while building docker image, I see an experimental flag `--platform` flag been introduced which can be used to fix this issue but unfortunately it is not working properly when we build it `FROM scratch` image
> 
> Hey @mkumatag 👋, I'm currently working on setting the arch/OS for a container image during image build (see [containers/buildah#2097](https://github.com/containers/buildah/pull/2097)). We could think about building our images with buildah/podman if the feature gets accepted and fits our needs. WDYT?

Most of the build scripts are now using docker client but I'm open for using other tools if they are serving the purpose! wdys @dims

**Comment by dims** [comment]
@saschagrunert @mkumatag as long as someone signs up to do the work and handle follow ups (AND cover all the scenarios that we do currently - like windows!) 

cc @claudiubelu

**Comment by mkumatag** [comment]
> @saschagrunert @mkumatag as long as someone signs up to do the work and handle follow ups (AND cover all the scenarios that we do currently - like windows!)
> 
> cc @claudiubelu

ah! windows will be challenging I feel at the moment with buildah, will find a workaround for that!

**Comment by BenTheElder** [comment]
Is buildah available on Mac or runnable in a docker container?

**Comment by claudiubelu** [comment]
> 
> 
> @saschagrunert @mkumatag as long as someone signs up to do the work and handle follow ups (AND cover all the scenarios that we do currently - like windows!)
> 
> cc @claudiubelu

Ye, will look into it. But I think someone was already doing work on this, will have to check how it looks. And we can probably add the Image Promoter to this, including the Windows bits in a similar way we're doing with the test images.

**Comment by saschagrunert** [comment]
> Is buildah available on Mac or runnable in a docker container?

It runs inside docker containers. Can we create a list of requirements that I could prepare a demo container? What is the whole set of platforms which we have to support?

**Comment by claudiubelu** [comment]
So, there used to be a PR that was adding support for Windows for this image: https://github.com/kubernetes/kubernetes/pull/75618

But a few things have changed since then, so things should be a bit different:

- we'll need multiple Windows OS version support: for 1809, 1903, 1909.
- we'll have to include wincat: https://github.com/kubernetes-sigs/sig-windows-tools/tree/master/cmd/wincat - it is needed for a few kube-proxy usecases, if I remember correctly.

As for building, we could probably do it using the Image Promoter? I currently have a few PRs that are adding the Windows bits to the k/k e2e test images, including the part in which the Image Promoter is using a few Windows Server build nodes to build the Windows container images (https://github.com/kubernetes/kubernetes/pull/76838), so I could add the same bits to the pause image, if people want it. If so, I'll have to know first: is the Image Promoter in place for this image, or do I have to do it from scratch? :smile:

**Comment by mkumatag** [comment]
> So, there used to be a PR that was adding support for Windows for this image: #75618
> 
> But a few things have changed since then, so things should be a bit different:
> 
> * we'll need multiple Windows OS version support: for 1809, 1903, 1909.
> * we'll have to include wincat: https://github.com/kubernetes-sigs/sig-windows-tools/tree/master/cmd/wincat - it is needed for a few kube-proxy usecases, if I remember correctly.
> 
> As for building, we could probably do it using the Image Promoter? I currently have a few PRs that are adding the Windows bits to the k/k e2e test images, including the part in which the Image Promoter is using a few Windows Server build nodes to build the Windows container images (#76838), so I could add the same bits to the pause image, if people want it. If so, I'll have to know first: is the Image Promoter in place for this image, or do I have to do it from scratch? 😄

The problem is not just with windows images, most of the time the problem will be with cross-building images for non-amd64 archs like arm64, ppc64le, s390x platform using qemu.

**Comment by claudiubelu** [comment]
> 
> 
> > So, there used to be a PR that was adding support for Windows for this image: #75618
> > But a few things have changed since then, so things should be a bit different:
> > 
> > * we'll need multiple Windows OS version support: for 1809, 1903, 1909.
> > * we'll have to include wincat: https://github.com/kubernetes-sigs/sig-windows-tools/tree/master/cmd/wincat - it is needed for a few kube-proxy usecases, if I remember correctly.
> > 
> > As for building, we could probably do it using the Image Promoter? I currently have a few PRs that are adding the Windows bits to the k/k e2e test images, including the part in which the Image Promoter is using a few Windows Server build nodes to build the Windows container images (#76838), so I could add the same bits to the pause image, if people want it. If so, I'll have to know first: is the Image Promoter in place for this image, or do I have to do it from scratch? smile
> 
> The problem is not just with windows images, most of the time the problem will be with cross-building images for non-amd64 archs like arm64, ppc64le, s390x platform using qemu.

Sorry, this is a bit unclear for me. the problem is that we're using qemu to cross-build the images for non-amd64 archs and we shouldn't?

**Comment by everflux** [comment]
I just upgraded to latest crio and it refuses to download/use the pause image for me since then.

```
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Image architecture mismatch: image uses "amd64", expecting "arm64" 
```

I assume this is from a change in container/libpod implementing more strict checks. In my point of view this is impossible to fix for all images, but at least the base cluster images (pause, static pods for kubernetes like apiserver, etcd) should be fixed.

For reference here is the according crio issue I opened: https://github.com/cri-o/cri-o/issues/3233

**Comment by mkumatag** [comment]
> Sorry, this is a bit unclear for me. the problem is that we're using qemu to cross-build the images for non-amd64 archs and we shouldn't?

when we cross-build the images on the amd64, the image will contain the target architecture bits but the image will be signed with host arch(amd64) and this is what is creating issue while pulling the image by crio where they have a strict check of the image architecture and expects to match the host architecture(arm64 or ppc64le). The solution here is to build all these images natively on the target  architecture or feed the proper platform while cross-building(the above buildah PR is to achieve this)

**Comment by BenTheElder** [comment]
`--platform` works as expected with `buildx`. I will prepare a trivial PR to fix this, but then we will need to decide how to roll out the new image...

**Comment by mkumatag** [comment]
> `--platform` works as expected with `buildx`. I will prepare a trivial PR to fix this, but then we will need to decide how to roll out the new image...

sounds good to me,

**Comment by justaugustus** [comment]
Should be fixed in https://github.com/kubernetes/kubernetes/pull/87954.

**Comment by vrothberg** [comment]
Thanks a lot to all involved!

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/88129
https://github.com/kubernetes/kubernetes/pull/88137 (whoops :|)

building the images now, then we'll start updating references to it.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/88139 -> the image is now pushed to staging after sorting out the manifest .. will file a promotion to prod now

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/88173 actually updates to the new image, which should now be live at `k8s.gcr.io/pause:3.2`
