### ISSUE TITLE
[Flaky Test] skew-cluster-latest-kubectl-beta-gce (ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew-beta)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#87321]
**Which jobs are flaking**:
`sig-release-1.17-blocking/skew-cluster-latest-kubectl-beta-gce`

**Which test(s) are flaking**:
`listResources After`
`listResources Before`
`diffResources`

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-1.17-blocking#skew-cluster-latest-kubectl-beta-gce

**Reason for failure**:
```
subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--check-version-skew=false', '--extract=ci/k8s-stable1', '--extract=ci/latest', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--ginkgo-parallel=25', '--skew', '--test_args=--ginkgo.focus=Kubectl --ginkgo.skip=\\[Serial\\] --minStartupPods=8', '--timeout=120m')' returned non-zero exit status 1
```

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Invalid%20value%20for%20field%20%27zone%27%3A%20%27asia-northeast3-a%27.%20Unknown%20zone.

/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.18
/sig cloud-provider
/area provider/gcp

**Comment by droslean** [comment]
/close

The job stopped flaking after https://github.com/kubernetes/kubernetes/compare/2cb90fc65...c1b696d67

Closing...
