### ISSUE TITLE
go-to-protobuf: type FooSpec has both field and method named Size

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#87336]
**What happened**:
go-to-protobuf generates `Size()` func which breaks the compilation when the type has `Size` field.

**What you expected to happen**:
go-to-protobuf generation to do not break the compilation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Assume that your type has a field named `Size`. I simple add this type to the `k8s.io/sample-apiserver` types.go.
```go
type FooSpec struct {
	Size string `json:"size" protobuf:"bytes,1,opt,name=size"`
}
```

2. Run go-to-protobuf
```
$ go-to-protobuf \
  --output-base="${GOPATH}/src" \
  --apimachinery-packages='-k8s.io/apimachinery/pkg/util/intstr,-k8s.io/apimachinery/pkg/api/resource,-k8s.io/apimachinery/pkg/runtime/schema,-k8s.io/apimachinery/pkg/runtime,-k8s.io/apimachinery/pkg/apis/meta/v1,-k8s.io/apimachinery/pkg/apis/meta/v1beta1,-k8s.io/api/core/v1,-k8s.io/api/rbac/v1' \
  --go-header-file=./hack/custom-boilerplate.go.txt \
  --proto-import=./third_party/protobuf \
  --proto-import=./vendor \
  --packages="k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1"
```

3. Check generated.pb.go and ensure it contains

```go
// ...

func (m *FooSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Size_)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

// ...
```

4. Ensure that the compilation fails

```
$ GOOS=linux go build .
# k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1
pkg/apis/wardle/v1alpha1/generated.pb.go:563:12: m.Size_ undefined (type *FooSpec has no field or method Size_)
pkg/apis/wardle/v1alpha1/generated.pb.go:564:18: m.Size_ undefined (type *FooSpec has no field or method Size_)
pkg/apis/wardle/v1alpha1/generated.pb.go:565:49: m.Size_ undefined (type *FooSpec has no field or method Size_)
pkg/apis/wardle/v1alpha1/generated.pb.go:672:6: type FooSpec has both field and method named Size
pkg/apis/wardle/v1alpha1/generated.pb.go:678:11: m.Size_ undefined (type *FooSpec has no field or method Size_)
pkg/apis/wardle/v1alpha1/generated.pb.go:769:36: this.Size_ undefined (type *FooSpec has no field or method Size_)
pkg/apis/wardle/v1alpha1/generated.pb.go:1522:5: m.Size_ undefined (type *FooSpec has no field or method Size_)
```

and note the root cause
```
pkg/apis/wardle/v1alpha1/generated.pb.go:672:6: type FooSpec has both field and method named Size
```

**Anything else we need to know?**:
k8s.io/code-generator version - v1.16.0

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Given that's part of the protobuf serializer interface, it's unclear what could be done to work around this. Type aliasing seems super invasive.

**Comment by ialidzhikov** [comment]
@liggitt , see https://github.com/gogo/protobuf/pull/140.
From what I see, there is an option `protosizer_all`  and when enabled, it will generate `ProtoSize()` func, not `Size()`.
I would like to specify this option to go-to-protobuf.

I think it currently has hard-coded `"option (gogoproto.sizer_all) = true;",` - https://github.com/kubernetes/code-generator/blob/ff19ea5b1bbd993e2a16b8b3be4595923687477b/cmd/go-to-protobuf/protobuf/generator.go#L56

Can you confirm that `protosizer_all` option would generate `ProtoSize()` func?

**Comment by ialidzhikov** [comment]
With some hacks, I made code-generator to use `"option (gogoproto.protosizer_all) = true;"` and it generated `ProtoSize()` funcs. The issue is that the generated code now also tries to invoke `ProtoSize()` for the kubernetes types such as `metav1.LabelSelector`, `metav1.ListMeta`, `metav1.ObjectMeta` and etc. where the used extension is `gogoproto.sizer_all` but the already generated funcs are `Size()` ones.

```
$ GOOS=darwin go build .
# k8s.io/sample-apiserver/pkg/apis/wardle/v1beta1
pkg/apis/wardle/v1beta1/generated.pb.go:383:18: m.ObjectMeta.ProtoSize undefined (type v1.ObjectMeta has no field or method ProtoSize)
pkg/apis/wardle/v1beta1/generated.pb.go:398:16: m.ListMeta.ProtoSize undefined (type v1.ListMeta has no field or method ProtoSize)
# k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1
pkg/apis/wardle/v1alpha1/generated.pb.go:588:18: m.ObjectMeta.ProtoSize undefined (type v1.ObjectMeta has no field or method ProtoSize)
pkg/apis/wardle/v1alpha1/generated.pb.go:605:16: m.ListMeta.ProtoSize undefined (type v1.ListMeta has no field or method ProtoSize)
pkg/apis/wardle/v1alpha1/generated.pb.go:622:18: m.ObjectMeta.ProtoSize undefined (type v1.ObjectMeta has no field or method ProtoSize)
pkg/apis/wardle/v1alpha1/generated.pb.go:637:16: m.ListMeta.ProtoSize undefined (type v1.ListMeta has no field or method ProtoSize)
```

**Comment by ialidzhikov** [comment]
What is your proposal for workaround?

The only option I see is to get a new version of the API group where these `Size` fields are renamed to something else. Even in this case the new API group (for example  `wardle.example.com/v1beta2`) will support protobufs, but the old API group (for example `wardle.example.com/v1beta1`) - it won't.

**Comment by liggitt** [comment]
cc @smarterclayton for feedback on generated proto methods

**Comment by ialidzhikov** [comment]
@liggitt , does it makes sense to update https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions with this limitation that it is not possible to have a field named `Size` and to have proto definition for it.

Currently if you have API, you have to first deprecate this field and introduce equivalent, then introduce a new API version where this `Size` field is removed and then finally you can have proto definitions. Which is a lot of pain...
