### ISSUE TITLE
Failing test - ci-kubernetes-e2e-gci-gce-scalability

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/kubernetes#87346]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-scalability

**Which test(s) are failing**:
Stages: Overall
              listResources After
              listResources Before

**Since when has it been failing**:
1/16 

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

**Reason for failure**:
Multiple occurrences of the following error messages,
W0118 00:01:50.100]  - Invalid value for field 'zone': 'asia-northeast3-a'. Unknown zone.
W0118 00:01:50.100]  - Invalid value for field 'zone': 'asia-northeast3-b'. Unknown zone.
W0118 00:01:50.101]  - Invalid value for field 'zone': 'asia-northeast3-c'. Unknown zone.

**Anything else we need to know**:
Similar error was seen in the test failure mentioned in https://github.com/kubernetes/kubernetes/issues/87345 

/priority critical-urgent
/sig scalability

**Comment by droslean** [comment]
/close

The job is green now. The infrastructure problems seemed to be resolved.
