### ISSUE TITLE
zfs cannot handled properly: mistifyio/go-zfs not up to date

### ISSUE THREAD

**Issue by kazimsarikaya** [kubernetes/kubernetes#87341]
**What happened**:
kubelet cannot handle zfs properly because of old mistifyio/go-zfs 

```
E0117 22:43:26.591904    5419 watcher.go:103] encountered error getting children of zfs filesystem: zp_data/docker: exit status 1: "/usr/sbin/zfs zfs get -t all -Hp all -r zp_data/docker" => cannot open '-r': dataset does not exist
E0117 22:43:26.592001    5419 watcher.go:63] encountered error refreshing zfs watcher: exit status 1: "/usr/sbin/zfs zfs get -t all -Hp all -r zp_data/docker" => cannot open '-r': dataset does not exist
```
**What you expected to happen**:
zfs works as expected at kubelet.

**How to reproduce it (as minimally and precisely as possible)**:
using folders kubelet, containerd  and docker folders under /var/lib as zfs dataset

**Anything else we need to know?**:
I delete content at vendor/github.com/mistifyio/go-zfs/ and update with the https://github.com/mistifyio/go-zfs/archive/master.zip then the issue is solved.

**Environment**:
- Kubernetes version (use `kubectl version`):
Our production server:
`Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`
Test server i fixed:
```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1-dirty", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"dirty", BuildDate:"2020-01-17T19:57:51Z", GoVersion:"devel +316fd8cc4a Fri Jan 17 17:38:40 2020 +0000", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T20:56:50Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
virtualbox
- OS (e.g: `cat /etc/os-release`):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
- Kernel (e.g. `uname -a`):
4.19.80-0-vanilla
- Install tools:
manual install
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dims** [comment]
@kazimsarikaya in PR 86975, we are doing a bump to go-zfs. Could you check if that is enough for you?

https://github.com/kubernetes/kubernetes/pull/86975/files#diff-37aff102a57d3d7b797f152915a6dc16R410

**Comment by kazimsarikaya** [comment]
i reviewed. yes it is enough.

**Comment by flaviamissi** [comment]
Hey @kazimsarikaya !

Don't mean to barge in here, but if the problem is solved shouldn't this issue be closed?
