### ISSUE TITLE
`kubectl diff` fails with unclear error when binary is not in PATH

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#87343]
Reported by someone here:
https://stackoverflow.com/questions/58390269/kubectl-diff-on-windows-returns-an-error-executable-file-not-found-in-path

Three things that are problematic with this:
1. The error is super unclear, and doesn't tell you what binary it's failing to find,
2. if you're using `KUBECTL_EXTERNAL_DIFF`, the problem happens too, and again it's not telling you what binary it's looking for
3. We should document more clearly that this is using the diff binary (and maybe warn Windows users) as well as the fact that the error code from diff is propagated back to the user, see https://github.com/kubernetes/kubernetes/issues/6284#issuecomment-444163502

**Comment by apelisse** [comment]
The error is addressed by #87344, we have to fix the documentation.

**Comment by zhouya0** [comment]
For my understanding, wo should add info in doc about `kubectl diff` is using `diff` binary by default? 
Where to put? https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#diff as this already have.

**Comment by apelisse** [comment]
I think it'd make more sense to document here: https://kubectl.docs.kubernetes.io/pages/app_composition_and_deployment/diffing_local_and_remote_resources.html

Which you can change by looking at this:
https://github.com/kubernetes/kubectl/blob/master/docs/book/CONTRIBUTING.md

Would you mind taking care of this @zhouya0 ?

**Comment by zhouya0** [comment]
Ok. No problem,  I'll try to do it :)

**Comment by julianvmodesto** [comment]
This is done! https://github.com/kubernetes/kubernetes/pull/87805 https://github.com/kubernetes/kubernetes/pull/87344 

/close
