### ISSUE TITLE
kubectl cannot get flowschemas

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#87349]
**What happened**:
I am testing API Priority and Fairness.  I launched it like this:
```
RUNTIME_CONFIG=flowcontrol.apiserver.k8s.io/v1alpha1=true FEATURE_GATES=APIPriorityAndFairness=true LOG_LEVEL=7 hack/local-up-cluster.sh
```

After the logging said the cluster is running and told me how to set KUBECONFIG, I did so in another shell and went looking for FlowSchema objects.  But kubectl erroneously told me there is no such thing.

```
$ kubectl get Pod -A
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   kube-dns-74b889989-jh8zn   3/3     Running   0          49s

$ kubectl get flowschemas
error: the server doesn't have a resource type "flowschemas"

$ kubectl get flowschemas.flowcontrol.apiserver.k8s.io
error: the server doesn't have a resource type "flowschemas"

$ kubectl get flowschemas.v1alpha1.flowcontrol.apiserver.k8s.io
error: the server doesn't have a resource type "flowschemas"
```

However, looking in the kube-apiserver log shows flowschemas and prioritylevelconfigurations being read and written; for example:
```
I0118 06:00:08.222289   75066 httplog.go:90] verb="GET" URI="/apis/flowcontrol.apiserver.k8s.io/v1alpha1/flowschemas/catch-all" latency=954.726µs resp=200 UserAgent="kube-apiserver/v1.18.0 (linux/amd64) kubernetes/916edd9" srcIP="[::1]:48830": 
```

Also, I am able to read them with `curl` against the insecure port.

Interestingly, the kube-apiserver log also includes this complaint:
```
I0118 05:58:05.655870   75066 aggregator.go:182] Skipping APIService creation for flowcontrol.apiserver.k8s.io/v1alpha1
```

I will attach the kube-apiserver log.

**What you expected to happen**:
I expected `kubectl get flowschemas` to list them.

**How to reproduce it (as minimally and precisely as possible)**:
I think the report above is pretty minimal.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): this is the `master` branch, git commit 916edd922e528f2f27542d3ca5967ca11fe153f8

- Cloud provider or hardware configuration: bare metal, intel, 16 "CPUs", 64 GB of memory
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux mjs-dev-1 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hack/local-up-cluster.sh
- Network plugin and version (if this is a network-related bug):
- Others:
Docker version 18.09.7
go version go1.13.4 linux/amd64
[kube-apiserver.log](https://github.com/kubernetes/kubernetes/files/4080061/kube-apiserver.log)

**Comment by liggitt** [comment]
the flowservice API group is not included in the list of known groups to register at startup:
https://github.com/kubernetes/kubernetes/blob/37d9c22abe5921da1d9c61bc92d054eebfb01515/cmd/kube-apiserver/app/aggregator.go#L248-L294

That means they will not appear in discovery, and clients like kubectl will not know how to find them.

**Comment by liggitt** [comment]
You can see all resources visible via discovery by running `kubectl api-resources`

**Comment by yue9944882** [comment]
just as @liggitt said, for now we have to manually create an apiservice into the cluster to get kubectl work. i dont think we're adding this to the list until the beta stage, can we make an exception for the case? @kubernetes/sig-api-machinery-misc 

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1alpha1.flowcontrol.apiserver.k8s.io
spec:
  group: flowcontrol.apiserver.k8s.io
  groupPriorityMinimum: 16000
  service: null
  version: v1alpha1
  versionPriority: 1
```

**Comment by liggitt** [comment]
It is fine to add alpha things to the list I linked. They only get registered if the relevant runtime-config is enabled.

**Comment by sfxworks** [comment]
Interrupts control plane upgrade in lazy scenario where it's assumed dns name isn't changed properly to active node or or single node control plane 

```
[root@k8s-control-1 bin]# ./kubeadm upgrade apply v1.29.6
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
W0620 19:24:10.219810  939204 configset.go:78] Warning: No kubeproxy.config.k8s.io/v1alpha1 config is loaded. Continuing without it: configmaps "kube-proxy" not found
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade/version] You have chosen to change the cluster version to "v1.29.6"
[upgrade/versions] Cluster version: v1.28.3
[upgrade/versions] kubeadm version: v1.29.6
[upgrade] Are you sure you want to proceed? [y/N]: y
[upgrade/prepull] Pulling images required for setting up a Kubernetes cluster
[upgrade/prepull] This might take a minute or two, depending on the speed of your internet connection
[upgrade/prepull] You can also perform this action in beforehand using 'kubeadm config images pull'
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.29.6" (timeout: 5m0s)...
[upgrade/staticpods] Writing new Static Pod manifests to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests2147223571"
[upgrade/staticpods] Preparing for "kube-apiserver" upgrade
[upgrade/staticpods] Renewing apiserver certificate
[upgrade/staticpods] Renewing apiserver-kubelet-client certificate
[upgrade/staticpods] Renewing front-proxy-client certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-apiserver.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2024-06-20-19-24-45/kube-apiserver.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
[upgrade/apply] FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: failed to obtain static Pod hash for component kube-apiserver on Node k8s-control-1: Get "https://office-cluster.mcserverhosting.net:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-k8s-control-1?timeout=10s": dial tcp 192.168.67.28:6443: connect: connection refused
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by sfxworks** [comment]
oh cool actually it succeeds on the second main node but the kube apiserver pod doesnt start

[root@k8s-control-2 ~]# crictl ps
CONTAINER           IMAGE                                                              CREATED             STATE               NAME                      ATTEMPT             POD ID              POD
cdde940a69e7c       f1759791c7fd7bbd76b0a925b6ee895e6c7705adecdace4fbdf0de03e8b3795d   14 minutes ago      Running             cilium-operator           6                   8ced199faabb8       cilium-operator-68bff6bdf-dnbtk
1b10a060bf285       49d9b8328a8fda6ebca6b3226c6d722d92ec7adffff18668511a88058444cf15   22 minutes ago      Running             kube-scheduler            0                   e3f2e2a8b9048       kube-scheduler-k8s-control-2
2ce6f607e11ce       083b81fc09e858d3e0d4b42f567a9d44a2232b60bac396a94cbdd7ce1098235e   22 minutes ago      Running             kube-controller-manager   0                   08e23d2ca9a9e       kube-controller-manager-k8s-control-2
35e44f062a3e5       ead0a4a53df89fd173874b46093b6e62d8c72967bbf606d672c9e8c9b601a4fc   5 months ago        Running             coredns                   2                   1cab274be3a56       coredns-5dd5756b68-fj78d
5736ca1c2e25b       1d8f313eedac95688b371b093bc66830f521a7b522ada3776cbb15749e809e75   5 months ago        Running             cilium-agent              2                   e4cdd8266cb68       cilium-57nk8
[root@k8s-control-2 ~]# kubeadm k^C
[root@k8s-control-2 ~]# kubectl ^C
[root@k8s-control-2 ~]# crictl ^C
[root@k8s-control-2 ~]# cat /var/log/containers/kube-apiserver-k8s-control-2_kube-system_kube-apiserver-09a5b9e2e3ebce5bdcd48bbcee2821a9fc150ad1d0c4cf5f9255d794145c42aa.log 
2024-06-20T19:42:34.641439208+00:00 stderr F W0620 19:42:34.641275       1 feature_gate.go:241] Setting GA feature gate APIPriorityAndFairness=true. It will be removed in a future release.
2024-06-20T19:42:34.641641669+00:00 stderr F I0620 19:42:34.641607       1 options.go:222] external host was not specified, using 192.168.67.28
2024-06-20T19:42:34.642847962+00:00 stderr F I0620 19:42:34.642795       1 server.go:148] Version: v1.29.6
2024-06-20T19:42:34.642871638+00:00 stderr F I0620 19:42:34.642844       1 server.go:150] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
2024-06-20T19:42:34.967787306+00:00 stderr F E0620 19:42:34.967724       1 run.go:74] "command failed" err="group version flowcontrol.apiserver.k8s.io/v1alpha1 that has not been registered"
[root@k8s-control-2 ~]#

**Comment by sfxworks** [comment]
the hacky way being to adjust that api creation based on this?

The flowcontrol.apiserver.k8s.io/v1beta3 FlowSchema and PriorityLevelConfiguration APIs has been promoted to flowcontrol.apiserver.k8s.io/v1, with the following changes:

PriorityLevelConfiguration: the .spec.limited.nominalConcurrencyShares field defaults to 30 only if the field is omitted (v1beta3 also defaulted an explicit 0 value to 30). Specifying an explicit 0 value is not allowed in the v1 version in v1.29 to ensure compatibility with v1.28 API servers. In v1.30, explicit 0 values will be allowed in this field in the v1 API. The flowcontrol.apiserver.k8s.io/v1beta3 APIs are deprecated and will no longer be served in v1.32. All existing objects are available via the v1 APIs. Transition clients and manifests to use the v1 APIs before upgrading to v1.32. (https://github.com/kubernetes/kubernetes/pull/121089, [@tkashem](https://github.com/tkashem))

**Comment by sfxworks** [comment]
And I removed the flags too

```
Error from server (AlreadyExists): error when creating "api-service.yaml": apiservices.apiregistration.k8s.io "v1beta3.flowcontrol.apiserver.k8s.io" already exists
```

**Comment by sfxworks** [comment]
```
[root@k8s-control-1 ~]# kubectl logs -f -n kube-system kube-apiserver-k8s-control-2
I0620 20:07:37.705087       1 options.go:222] external host was not specified, using 192.168.67.27
I0620 20:07:37.706361       1 server.go:148] Version: v1.29.6
I0620 20:07:37.706423       1 server.go:150] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
E0620 20:07:38.356654       1 run.go:74] "command failed" err="group version flowcontrol.apiserver.k8s.io/v1alpha1 that has not been registered"
[root@k8s-control-1 ~]# kubectl create -f api-service.yaml 
Error from server (AlreadyExists): error when creating "api-service.yaml": apiservices.apiregistration.k8s.io "v1alpha1.flowcontrol.apiserver.k8s.io" already exists
```

**Comment by sfxworks** [comment]
Wait what is this?

```
--runtime-config=flowcontrol.apiserver.k8s.io/v1alpha1=true
```

This was added to my api manifest during kubeadm upgrade?
