### ISSUE TITLE
Is Unstructured.ToList() correct?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#87367]
**What happened**:
https://github.com/kubernetes/apimachinery/blob/b615468efe0478fcdf43e7ce5ae63d76d205ef50/pkg/apis/meta/v1/unstructured/unstructured.go#L62-L66

```
func (obj *Unstructured) ToList() (*UnstructuredList, error) {
	if !obj.IsList() {
		// return an empty list back
		return &UnstructuredList{Object: obj.Object}, nil
	}

```

Does this look correct? If the unstructured object is not a List(), shouldn't ToList() return a list with the original object as an item?

I am trying to read objects from a YAML file. I was using the api like below:

```
var u unstructured.Unstructured
err = reader.Decode(&u)
if err == io.EOF {
	break
} else if err != nil {
	panic(err)
}
list, err := u.ToList()
if err != nil {
	panic(err)
}
err = list.EachListItem(func(obj runtime.Object) error {
	resources = append(resources, obj.(*unstructured.Unstructured))
	return nil
})
if err != nil {
	panic(err)
}
```

It does not work, because it drops individual objects.

/sig api-machinery

**Comment by tamalsaha** [comment]
cc: @deads2k

**Comment by jpbetz** [comment]
Please include a YAML file demonstrating the issue and more details about the actual and expected results
