### ISSUE TITLE
kubecetl client-go exec credentials plugin should use new valid token as soon as stored rather than old expired

### ISSUE THREAD

**Issue by anderseknert** [kubernetes/kubernetes#87369]
**What happened**:

With the exec credentials plugin configured in my kubeconf, *and* a stale/expired token present in the same file issuing e.g. `kubectl get pod` triggers the authentication flow as handled by the plugin - once the flow is returned to kubectl (by printing the ExecCredential object) the new token is stored to the kubeconfig *but* not immediately used to resolve the `kubectl get pod` request, leading to:

`error: You must be logged in to the server (Unauthorized)`

Immediately issuing `kubectl get pod` again works as kubectl now seem to use the credentials (token) stored following the first request.

**What you expected to happen**:

That kubectl would read the new token as fetched by the exec credential plugin and use it already for the first command issued. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure the kubernetes API server with the OIDC authenticator enabled.
2. Configure kubectl to use an exec credential plugin printing the token received out of band.
3. Verify that the token was indeed written to the kubeconf file.
4. See that the first kubectl command failed.
5. See that the next identical command succeeds.

**Anything else we need to know?**:

This works as expected when there is *no* token previously stored in the kubeconf - the behavior is only triggered when there is a token stored but it expired, or for whatever other reason not accepted by the API server.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14, also tried with 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Mac OS for kubectl client
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by enj** [comment]
@anderseknert could you provide more details around how `kubectl` is configured.  For example, it is unclear to me if you are using the built in oidc plugin or a custom exec plugin.

I _think_ you are using a custom exec plugin but its also trying to write tokens to the `KUBECONFIG` file (which it should not do)?

/triage needs-information

**Comment by anderseknert** [comment]
Thanks for looking into it @enj . You are indeed correct in your assumption that I'm using a [custom exec plugin](https://github.com/Bisnode/kubectl-login) which stores the token in the `KUBECONFIG` after retrieval. I'd love to learn why this should not be done, but the problem remains also without persisting the token after retrieval. Basically the steps to reproduce could be reduced to these:

1. A `KUBECONFIG` containing an expired token.
2. The same `KUBECONFIG` configuring an exec plugin which retrieves a valid token out of band and echoes it.

Expected behavior: The valid token retrieved is used for the subsequent authentication.
Possibly expected behavior: The exec plugin flow not started (or exited with a warning) due to an expired token being present in the `KUBECONFIG`.

Current behavior seems to acknowledge the invalid token and hence tries to retrieve a new, valid one - which it then discards as soon as it arrives.

**Comment by anderseknert** [comment]
Seems we can reduce it even further by removing the token altogether from the `KUBECONFIG` file and instead provide it directly. So the only step needed to reproduce is essentially this:

1. A `KUBECONFIG` configuring an exec plugin which retrieves a valid token out of band and echoes it as part of an [ExecCredential object](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats).

Now any `kubectl --token=<expired_token> <command>` will trigger the exec plugin to retrieve a valid token, but will still not use it for subsequent authentication.

**Comment by mikedanese** [comment]
> Now any `kubectl --token=<expired_token> <command>` will trigger the exec plugin to retrieve a valid token, but will still not use it for subsequent authentication.

This one is caused by config merging with clientcmd overrides:

https://github.com/kubernetes/kubernetes/blob/0f13c5c3d1cdbb983c3e3d7a1b2a1ef803d24fcb/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go#L425-L434

and exec.Auth not being added in this switch:

https://github.com/kubernetes/kubernetes/blob/0f13c5c3d1cdbb983c3e3d7a1b2a1ef803d24fcb/staging/src/k8s.io/client-go/transport/round_trippers.go#L44

**Comment by anderseknert** [comment]
Interesting, thanks @mikedanese. Will add it to the switch along with some tests and if everything works out well I'll submit a PR next week.

**Comment by anderseknert** [comment]
Having spent some time on this in the debugger, it seems somewhat more intricate than I first thought. Turns out the exec plugin is executed whether the `--token` presented is invalid _or valid_ - the exec action is actually called before the first call is even dispatched. This due to the exec credential plugin possibly being needed to setup the client certificate requested for the transport. Once the exec plugin's `UpdateTransportConfig` is called it assign the authenticators `cert` function to `c.TLS.GetCert`:

https://github.com/kubernetes/kubernetes/blob/fb6f5d739b08e049b188806d6e33099f85fad2fe/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L188

..which is then called when setting up the transport, thus triggering the exec plugin regardless of a token being present or not:

https://github.com/kubernetes/kubernetes/blob/fb6f5d739b08e049b188806d6e33099f85fad2fe/staging/src/k8s.io/client-go/transport/transport.go#L94-L102

Since the exec plugin has no way of knowing whether a token or a client certificate will be returned by the exec action, this kind of makes sense. It however defeats letting any `--token` present to override the exec plugin, which clearly seems to be the intent:

https://github.com/kubernetes/kubernetes/blob/fb6f5d739b08e049b188806d6e33099f85fad2fe/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L216-L221

Possible options here that I can think of:
1. Keep (and fix) behavior of letting `--token` override the exec plugin. This looks doable by adding a check for token auth early in the exec.go's `UpdateTransportConfig` method body:
```
if c.HasTokenAuth() {
    return nil
}
```
But might be there are consequences to this I'm not aware of.

2. Remove the behavior of letting `--token` override the exec plugin being called.

3. A third, more complex option, would be to keep the token override but dispatch to the exec credential plugin should the response from the first call with the token come back with a 401. This was what I originally believed was the intent as my first tests always included an invalid token. While this behavior seems nice I'm more and more thinking it may violate the principle of least surprise. Either you present a token and use that for auth or you let the exec plugin fetch the credentials for you.

What do you guys think?

**Comment by anderseknert** [comment]
As a colleague just made me aware of, certain tools like kubetail seem to have kubectl call the exec plugin so many times that eventually the `onRotateListWarningLength` threshold of 1000 is reached and warn logs (exec:201) start spewing - even though no certificate (and hence no rotation) should be involved. This has me more convinced that the first option is the right one, skipping the client TLS ceremonies should a token be present for authentication.
