### ISSUE TITLE
Merge extender to scheduler framework

### ISSUE THREAD

**Issue by skilxn-go** [kubernetes/kubernetes#87364]
**What would you like to be added**:
Merge scheduler extender to plugins in shceduler framework.

**Why is this needed**:
Now, most scheduler policy has been implemented with scheduler framework, but extender is still out of it.

As post-filter plugin can be used to do filter work now, we are available to merge extender to scheduler framwork as bellow:
extender.Filter -> scheduler framework.PostFilter
extender.Bind -> scheduler framework.Bind
extender.Priority -> scheduler framework.Score

However we still need a preempt plugin point, and I don't know the progress of this KEP?
https://github.com/kubernetes/enhancements/pull/1398

So can we merge Filter、Bind、and Priority first to scheduler framework, and after preempt plugin is implemented, we can make the whole extender run in some scheduler plugins.

**Comment by ahg-g** [comment]
/cc @alculquicondor 

Aldo also suggested that the binding call to the extenders should move to a plugin. The whole approach of moving the extenders calls to plugins sounds good to me. We can do the Filter and Bind now and wait for preemption to be resolved later.

**Comment by alculquicondor** [comment]
I had already opened an issue for this #87159
