### ISSUE TITLE
A volume doesn't add in volumesAttached while the volume is attached to the node.

### ISSUE THREAD

**Issue by celiawa** [kubernetes/kubernetes#87374]
Hi Experts:

We're doing cinder volume attach/detach performance test with the in-tree cloud provider.
The volumes attach/detach to a node in every 10 minutes.  After dozens of success, one one the volume failed with mount.

A pod stuck in ContainerCreating status with:

  Warning  FailedMount  3m15s (x2143 over 3d8h)  kubelet, a2113-wrkr-03  Unable to mount volumes for pod "alpine-c-4_default(cc61968f-d5f9-4d97-bd89-10b82f9b68ac)": timeout expired waiting for volumes to attach or mount for pod "default"/"alpine-c-4". list of unmounted volumes=[alpine-test-persistent-storage-cinder]. list of unattached volumes=[alpine-test-persistent-storage-cinder default-token-hhxmz]

The volume failed to mount is:
[root@a2113-edge-00 ~]# kubectl get pv |grep alpine-c-4
pvc-6fab930e-904d-4ca1-950b-80d7d59a9eaf   50Gi       RWO            Delete           Bound    default/alpine-test-persistent-storage-cinder-alpine-c-4     cinder-az-nova                                2d

From kube-controller-manager log can see the PV is successfully attached to the worker node. And check from openstack, the volume is attached to a2113-wrkr-03 as /dev/vdp .
I0116 19:37:25.015649       1 actual_state_of_world.go:479] Report volume "kubernetes.io/cinder/c5071480-b313-4034-a784-bf22c4c6bf3d" as attached to node "a2113-wrkr-03"
I0116 19:37:25.015699       1 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"alpine-c-4", UID:"cc61968f-d5f9-4d97-bd89-10b82f9b68ac", APIVersion:"v1", ResourceVersion:"42157166", FieldPath:""}): type: 'Normal' reason: 'SuccessfulAttachVolume' AttachVolume.Attach succeeded for volume "pvc-6fab930e-904d-4ca1-950b-80d7d59a9eaf" 

Also below log in the kube-controller log:
I0116 19:37:28.663167       1 actual_state_of_world.go:365] SetVolumeMountedByNode volume kubernetes.io/cinder/c5071480-b313-4034-a784-bf22c4c6bf3d to the node "a2113-wrkr-03" mounted true
From this log and the code, does that mean the volume is added into volumeInUse and attached to the node. 
func (adc *attachDetachController) processVolumesInUse(
	nodeName types.NodeName, volumesInUse []v1.UniqueVolumeName) {
	klog.V(4).Infof("processVolumesInUse for node %q", nodeName)
	for _, attachedVolume := range adc.actualStateOfWorld.GetAttachedVolumesForNode(nodeName) {
		mounted := false
		for _, volumeInUse := range volumesInUse {
			if attachedVolume.VolumeName == volumeInUse {
				mounted = true
				break
			}
		}
		err := adc.actualStateOfWorld.SetVolumeMountedByNode(attachedVolume.VolumeName, nodeName, mounted)
		if err != nil {
			klog.Warningf(
				"SetVolumeMountedByNode(%q, %q, %v) returned an error: %v",
				attachedVolume.VolumeName, nodeName, mounted, err)
		}
	}
}

From kubelet log in a2113-wrkr-03, the volume failed to mount with "Volume not attached according to node status for volume".
Jan 16 19:37:43 a2113-wrkr-03 kubelet[13766]: I0116 19:37:43.005468   13766 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-6fab930e-904d-4ca1-950b-80d7d59a9eaf" (UniqueName: "kubernetes.io/cinder/c5071480-b313-4034-a784-bf22c4c6bf3d") pod "alpine-c-4" (UID: "cc61968f-d5f9-4d97-bd89-10b82f9b68ac")
Jan 16 19:37:43 a2113-wrkr-03 kubelet[13766]: E0116 19:37:43.010779   13766 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/cinder/c5071480-b313-4034-a784-bf22c4c6bf3d\"" failed. No retries permitted until 2020-01-16 19:37:59.010731671 +0200 EET m=+301815.968062399 (durationBeforeRetry 16s). Error: "Volume not attached according to node status for volume \"pvc-6fab930e-904d-4ca1-950b-80d7d59a9eaf\" (UniqueName: \"kubernetes.io/cinder/c5071480-b313-4034-a784-bf22c4c6bf3d\") pod \"alpine-c-4\" (UID: \"cc61968f-d5f9-4d97-bd89-10b82f9b68ac\") "

In a2113-wrkr-03 can see the device path for the volume(bold in below /dev/vdu) is attached.
[root@a2113-wrkr-03 by-id]# ll
total 0
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 ata-QEMU_DVD-ROM_QM00001 -> ../../sr0
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-2c3268c4-8f40-4de2-8 -> ../../vdg
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-49358e2a-3a35-4734-8 -> ../../vdt
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-502b2eb1-c4e7-462d-b -> ../../vdq
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-54d7928e-c1b6-4b73-8 -> ../../vde
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-6669f138-c66e-4001-a -> ../../vdn
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-7227d7bd-bfcb-4114-a -> ../../vdm
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-76b10773-95f1-4aab-b -> ../../vdd
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-a85a3ca1-3614-491b-a -> ../../vdo
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-b0ba2acf-d6cf-478b-b -> ../../vdr
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-b348cd89-9730-4b38-a -> ../../vdc
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-c11ccab8-79b0-4c8f-b -> ../../vdi
**lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-c5071480-b313-4034-a -> ../../vdu**
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-d136ffdc-a42c-4926-b -> ../../vdk
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-e5f94072-7734-43d4-9 -> ../../vdb
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-f13eac59-2978-436d-a -> ../../vdf
lrwxrwxrwx. 1 root root 9 Jan 16 19:37 virtio-f3339173-cc8d-413d-a -> ../../vdh

The volume is added to the volumesInUse, but not added to volumesAttached.
volumesAttached:
  - devicePath: /dev/vdi
    name: kubernetes.io/cinder/c11ccab8-79b0-4c8f-b67d-19fa55c99745
  - devicePath: /dev/vdc
    name: kubernetes.io/cinder/b348cd89-9730-4b38-ac50-2008202118fa
  - devicePath: /dev/vdl
    name: kubernetes.io/cinder/6669f138-c66e-4001-afb6-a9e9f60066f5
  - devicePath: /dev/vdo
    name: kubernetes.io/cinder/49358e2a-3a35-4734-81af-5b8a357fbf6e
  - devicePath: /dev/vdq
    name: kubernetes.io/cinder/502b2eb1-c4e7-462d-b3ce-dd0932eb9e73
  - devicePath: /dev/vdj
    name: kubernetes.io/cinder/d136ffdc-a42c-4926-b900-4af9fb348357
  - devicePath: /dev/vdh
    name: kubernetes.io/cinder/f3339173-cc8d-413d-a3ae-9b8052e46b53
  - devicePath: /dev/vdk
    name: kubernetes.io/cinder/7227d7bd-bfcb-4114-a236-7881a740f085
  - devicePath: /dev/vdm
    name: kubernetes.io/cinder/a85a3ca1-3614-491b-ae03-3f6a6510b79b
  - devicePath: /dev/vdn
    name: kubernetes.io/cinder/b0ba2acf-d6cf-478b-b5df-6bf8bebf9668
  - devicePath: /dev/vde
    name: kubernetes.io/cinder/54d7928e-c1b6-4b73-89a1-c870c9b247b3
  - devicePath: /dev/vdg
    name: kubernetes.io/cinder/2c3268c4-8f40-4de2-8a14-c42b32582c99
  - devicePath: /dev/vdd
    name: kubernetes.io/cinder/76b10773-95f1-4aab-b1e0-f6cb219b4faa
  - devicePath: /dev/vdf
    name: kubernetes.io/cinder/f13eac59-2978-436d-a216-3140a708d747
  volumesInUse:
  - kubernetes.io/cinder/2c3268c4-8f40-4de2-8a14-c42b32582c99
  - kubernetes.io/cinder/49358e2a-3a35-4734-81af-5b8a357fbf6e
  - kubernetes.io/cinder/502b2eb1-c4e7-462d-b3ce-dd0932eb9e73
  - kubernetes.io/cinder/54d7928e-c1b6-4b73-89a1-c870c9b247b3
  - kubernetes.io/cinder/6669f138-c66e-4001-afb6-a9e9f60066f5
  - kubernetes.io/cinder/7227d7bd-bfcb-4114-a236-7881a740f085
  - kubernetes.io/cinder/76b10773-95f1-4aab-b1e0-f6cb219b4faa
  - kubernetes.io/cinder/a85a3ca1-3614-491b-ae03-3f6a6510b79b
  - kubernetes.io/cinder/b0ba2acf-d6cf-478b-b5df-6bf8bebf9668
  - kubernetes.io/cinder/b348cd89-9730-4b38-ac50-2008202118fa
  - kubernetes.io/cinder/c11ccab8-79b0-4c8f-b67d-19fa55c99745
  **- kubernetes.io/cinder/c5071480-b313-4034-a784-bf22c4c6bf3d**
  - kubernetes.io/cinder/d136ffdc-a42c-4926-b900-4af9fb348357
  - kubernetes.io/cinder/f13eac59-2978-436d-a216-3140a708d747
  - kubernetes.io/cinder/f3339173-cc8d-413d-a3ae-9b8052e46b53

**What happened**:
One volume is not added to volumeAttached and failed to mount.

**What you expected to happen**:
The volume shall be added to the volumeAttached and pod is running.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.4

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

- Kernel (e.g. `uname -a`):
Linux a2113-wrkr-03 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Sun Sep 15 11:24:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by b8kings0ga** [comment]
facing the similar issue here with kubernetes version of 1.16.9. I'm using the custom CSI out tree plugin, but turns out kubelet is not recelve the pv-node relationship really soon and it takes about 20 mins to find out.
