### ISSUE TITLE
Kubectl Expose --type ExternalName 

### ISSUE THREAD

**Issue by DeanPH** [kubernetes/kubernetes#87398]
**What happened**:
Running `kubectl expose pod mypod --port 80 --type ExternalName` returns the error:
> The Service "mypod" is invalid: spec.externalName: Required value

Running `kubectl expose pod mypod --port 80 --type ExternalName="xxx"` returns the error:
> The Service "mypod" is invalid: spec.type: Unsupported value: "ExternalName=xxx": supported values: "ClusterIP", "ExternalName", "LoadBalancer", "NodePort"

Running `kubectl expose --help` returns:
> --type='': Type for this service: ClusterIP, NodePort, LoadBalancer, or ExternalName. Default is 'ClusterIP'.

**What you expected to happen**:
There is no support for --ExternalName when using kubectl expose so it should not appear in the help page for --expose or in the error messages:

**How to reproduce it (as minimally and precisely as possible)**:
```
Create a single pod then run the following commands:
kubectl expose pod mypod --port 80 --type ExternalName
kubectl expose pod mypod --port 80 --type ExternalName="xxx"
kubectl expose --help
```

**Anything else we need to know?**:
Ignore the fact that I specified a port 👍 

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T20:56:50Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: Virtualbox Lab

- OS (e.g: `cat /etc/os-release`): `NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`

- Kernel (e.g. `uname -a`): `Linux kmaster 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by zhouya0** [comment]
I think it's better to just delete the `ExternalName` from  the help info. I tried to add support for `ExternalName` in  `kubectl expose`. But I realized that `kubectl expose ` actually will create the `service` with `lable selector` with the lables in your given object. But `ExternalName` doesn't need `lable selector` and should not rely on any given object.

**Comment by zhouya0** [comment]
If you really want's to create `ExternalName` service, you'd better to write a yaml file or something else.
