### ISSUE TITLE
Move scheduler's SchedulerExtender interface to core/extenders.go

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#87396]
```scheduler/algorithm``` is deprecated, and ```SchedulerExtender``` must move somewhere else, and the best place is in ```core/extenders.go```.

/sig scheduling
/help
/good-first-issue

**Comment by haosdent** [comment]
@zouyee seems you have submitted the pull request, let me transfer the ticket to you. I go through your pull request and it looks awesome, thanks your contribution!

**Comment by haosdent** [comment]
BTW, I think we could remove `scheduler/algorithm` totally once https://github.com/kubernetes/kubernetes/pull/87342/files is merged. OK for you? @ahg-g @zouyee
