### ISSUE TITLE
Latest k8s.io/utils/mount breaks pkg/volume/rbd tests

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#87408]
**Which jobs are failing**:
bazel-test

**Which test(s) are failing**:
```--- FAIL: TestPlugin (0.00s)
    rbd_test.go:286: rbd: failed to mount device /dev/rbd1 at /tmp/rbd_test419475751/plugins/kubernetes.io/rbd/mounts/pool1-image-image1 (fstype: ext4), error cannot mount unformatted disk /dev/rbd1 as we are manipulating it in read-only mode
FAIL
FAIL    k8s.io/kubernetes/pkg/volume/rbd        0.016s
FAIL
```

**Since when has it been failing**:
Test fails when updating to latest k8s.io/utils version. Tested in https://github.com/kubernetes/kubernetes/pull/85617. 

**Anything else we need to know**:
I think the commit causing the breaking test is https://github.com/kubernetes/utils/pull/127

**Comment by andrewsykim** [comment]
/sig storage
/assign @jingxu97 @jsafrane 
cc @mvisonneau

**Comment by andrewsykim** [comment]
cc @codenrhoden @msau42

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by mvisonneau** [comment]
I assume this is due to the fact that before my change, a device configured in read-only mode which would not be formatted would then be formatted 🤔

**Comment by andrewsykim** [comment]
Would it be possible to get a fix in soon? It's blocking other updates to k8s.io/utils

**Comment by msau42** [comment]
@mvisonneau are you saying that the rbd test is not correct because it was trying to format a read-only volume?

**Comment by mvisonneau** [comment]
Indeed, one solution could be to pre-format it before attempting to mount it in read-only mode.

**Comment by mvisonneau** [comment]
The easiest one seems to be removing the _ReadOnly_ attribute (which would set it to false) on the the first **TestPlugin** case. I have submitted a PR that does it: https://github.com/kubernetes/kubernetes/pull/87609 ☝️

**Comment by mvisonneau** [comment]
This behaviour seems to be older than my recent changes though 🤔 https://github.com/kubernetes/utils/pull/127/files#diff-532e7b8579a9b13f176219cc79712ee3L303-L306

**Comment by mvisonneau** [comment]
I believe you can retry @andrewsykim, the test fix has now been merged!

**Comment by andrewsykim** [comment]
/close

thanks!
