### ISSUE TITLE
[Failing Test] kubemark-{master, 1.1.6, 1.17) fail to start 

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#87416]
**Which jobs are failing**:
kubemark-1.16-500
kubemark-1.17-500
kubemark-100

**Which test(s) are failing**:
Kubemark Up

**Since when has it been failing**:

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-1.16-500
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-1.17-500
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100

**Reason for failure**:

**Anything else we need to know**:

/sig scalability
/assign @jkaniuk

**Comment by jkaniuk** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce-stable1/1219545266021994499
```
I0121 09:13:22.321] docker push gcr.io/k8s-periodic-scale-2/kubemark:dcr2be
I0121 09:13:23.125] The push refers to repository [gcr.io/k8s-periodic-scale-2/kubemark]
I0121 09:13:23.143] c894301c3e30: Preparing
I0121 09:13:23.143] f47163e8de57: Preparing
I0121 09:13:23.143] 0d1435bd79e4: Preparing
I0121 09:13:23.338] denied: Token exchange failed for project 'k8s-periodic-scale-2'. Please enable Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=k8s-periodic-scale-2 before performing this operation.
```

Few projects were added to boskos pool recently:
https://github.com/kubernetes/test-infra/pull/15927
seems that not all needed permissions were set on them

**Comment by jkaniuk** [comment]
I have enabled Google Container Registry API in new projects:
- k8s-periodic-scale-1
- k8s-periodic-scale-2
- k8s-periodic-scale-3
- k8s-periodic-scale-4
- k8s-periodic-scale-5
- k8s-presubmit-scale-31
- k8s-presubmit-scale-32
- k8s-presubmit-scale-33
- k8s-presubmit-scale-34
- k8s-presubmit-scale-35

Waiting for next runs results to verify.

**Comment by jkaniuk** [comment]
New runs works fine:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce-beta/1219817144749920259
*20/20 Tests Passed!*

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce-stable1/1219907740399308800

```
I0122 09:18:46.989] The push refers to repository [gcr.io/k8s-periodic-scale-1/kubemark]
I0122 09:18:47.017] 2388690327b1: Preparing
I0122 09:18:47.018] f47163e8de57: Preparing
I0122 09:18:47.018] 0d1435bd79e4: Preparing
I0122 09:18:49.239] 0d1435bd79e4: Mounted from distroless/base
I0122 09:18:49.435] f47163e8de57: Mounted from distroless/base
I0122 09:19:02.331] 2388690327b1: Pushed
```
