### ISSUE TITLE
[TaintBasedEvictions] Update docs to reflect GA status

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#87429]
As part of promoting TaintBasedEvictions to GA (https://github.com/kubernetes/kubernetes/issues/87161), the docs around it will need to be updated to reflect the new status.

/kind cleanup
/sig scheduling

**Comment by damemi** [comment]
@haosdent are you still planning to work on updating these docs?

**Comment by haosdent** [comment]
sry, @damemi . assign by mistake. let me unassign.

**Comment by ingvagabund** [comment]
What's the ETA? Till Friday?
/assign

**Comment by sethmccombs** [comment]
Hi Team - Seth on the 1.18 Docs team here, we have until 2/28 to get placeholder PRs in for docs for this release, please let me know if I can help!

**Comment by damemi** [comment]
Hi @sethmccombs, Jan just opened a PR here to reflect this change in the docs: https://github.com/kubernetes/website/pull/19302 could you please provide review to make sure we've properly listed this as GA?
