### ISSUE TITLE
Expose gRPC client API

### ISSUE THREAD

**Issue by johanbrandhorst** [kubernetes/kubernetes#87421]
**What would you like to be added**:

I would like to be able to use a gRPC client to talk to the Kubernetes API.

**Why is this needed**:

The OpenAPI definition is great, and the existing language clients help, but JSON/HTTP is not perfect, and there are better alternatives. gRPC is becoming more popular every day, and it would make sense to expose a gRPC API. In the short term, there are well known performance wins when using gRPC over JSON/HTTP, and in the long term, it could mean doing away with per-language clients altogether and just expose the proto files directly.

Apologies if this has been discussed and discarded already, I couldn't find an issue for this.

**Comment by fedebongio** [comment]
/assign @lavalamp @deads2k 
hoping one of you can comment on the feasibility of this one

**Comment by caesarxuchao** [comment]
This was indeed discussed in the past: https://docs.google.com/document/d/13yn2Xgg5EBA3ytvs7b4x2fNE3iBxlFzYLpz-g1nENuI/edit#

**Comment by lavalamp** [comment]
You can use the proto content type to get the performance wins [*]. There's no way to make an unmodified gRPC client work against an unmodified kube-apiserver, and we've currently no plans to make a proxy or anything like that.

[*] doesn't work on CRDs yet.

**Comment by johanbrandhorst** [comment]
> This was indeed discussed in the past: https://docs.google.com/document/d/13yn2Xgg5EBA3ytvs7b4x2fNE3iBxlFzYLpz-g1nENuI/edit#

FYI this link is not public.

Thanks for the explanation. Is the possibility of using the proto content type documented somewhere? I didn't know about it until today.

**Comment by lavalamp** [comment]
It's viewable to members of the kubernetes-announce, kubernetes-dev, and kubernetes-sig-api-machinery mailing lists, sorry, my employer makes it impossible to make docs world-readable.

Search for "application/vnd.kubernetes.protobuf"...

**Comment by lavalamp** [comment]
E.g.: https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources

**Comment by johanbrandhorst** [comment]
Thank you!
