### ISSUE TITLE
[TaintBasedEvictions] Clean up featuregate logic

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#87428]
As part of moving TaintBasedEvictions to GA in 1.18 (https://github.com/kubernetes/kubernetes/issues/87161), we need to clean up the logic around featuregating for this feature. Since it will be GA, it should not require a featuregate anymore.

/kind cleanup
/sig scheduling

**Comment by skilxn-go** [comment]
Does this issue need help? I can do this, if help is needed, please just assign it to me. THX~

**Comment by damemi** [comment]
Sure, thank you for offering to help

/assign @skilxn-go

**Comment by skilxn-go** [comment]
Hi @damemi , I have a little question about it.
What's the expectation of this feature gate? Do we just move this feature gate to GA, or totally remove this feature gate?

**Comment by skilxn-go** [comment]
And if we just move this feature to GA, do we need to Lock it to true?

**Comment by skilxn-go** [comment]
So I send a pr with minimum modify. If there is anything wrong, please let me know, and I will fix it ASAP.
