### ISSUE TITLE
hcsshim has recursive dependency on kubernetes

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#87420]
Please see:
- https://github.com/microsoft/hcsshim/blob/master/go.mod#L42
- https://github.com/kubernetes/kubernetes/blob/master/go.mod#L190

Leads to weird stuff:
- https://github.com/microsoft/hcsshim/pull/700
- https://github.com/microsoft/hcsshim/issues/642

Please break the loop. We can't have it both ways!

/sig windows
/assign @PatrickLang

**Comment by dims** [comment]
please see https://github.com/microsoft/hcsshim/issues/760

**Comment by yujuhong** [comment]
hcsshim should import the the [cri-api](https://github.com/kubernetes/cri-api) instead

**Comment by liggitt** [comment]
That's easy to do (see https://github.com/liggitt/hcsshim/commits/bump-k8s), but means we could not then update our vendored copy of hcsshim in kube (we do not allow k8s.io/kubernetes -> vendor -> staging dependencies because it can gridlock the repo). The only real solutions I see are 1) for the cri-api component to graduate to a stand-alone component or 2) for kube to stop vendoring hcsshim.

**Comment by dims** [comment]
/area code-organization

option #1 looks like this
- https://github.com/kubernetes/kubernetes/pull/87493
- https://github.com/kubernetes/cri-api/pull/3

**Comment by jterry75** [comment]
@liggitt - For *2.* we actually only use cri-api for test code. This is to produce a binary under */test* that can be run against cri containerd. We have no part of hcsshim that requires kube

**Comment by liggitt** [comment]
Ah, that's helpful to know. Unfortunately, all dependencies (test or otherwise) are included in the dependency graph when go modules choose required versions.

**Comment by PatrickLang** [comment]
We can't remove the dependency on hcsshim - it would break the `/stats` endpoint. In fact we need to increase dependency on it to resolve https://github.com/kubernetes/kubernetes/issues/74991 because of latency issues in Docker codepath. cc @marosset 

So I think that leaves us with option 1

**Comment by PatrickLang** [comment]
ok @liggitt and @dims  - if we remove the hcsshim -> k/k dependency, then we still need to ensure that k/k and containerd both vendor the same version of hcsshim right?

**Comment by PatrickLang** [comment]
@jterry75 has a PR https://github.com/microsoft/hcsshim/pull/764

**Comment by PatrickLang** [comment]
re: tagging - I talked to @jterry75 and we want to propose adding different release tags for the containerd train, as the older 0.8.x ones were vendored into Docker and not tested with ContainerD or K8s.

This would give us 1 tag that we could vendor into both containerd and kubernete/kubernetes off a commitID, run tests, then add the tag. They would need to stay in sync, but at least we can tag what was tested before the vendoring change is merged.

**Comment by dcantah** [comment]
As all we use the k8s import for is the cri-api, for now we went ahead and used this repo for the tests instead https://github.com/kubernetes/cri-api/. Here is the pr https://github.com/microsoft/hcsshim/pull/783

**Comment by dcantah** [comment]
The pr (linked above) to use https://github.com/kubernetes/cri-api/ for our test code has been merged. Please let me know of anything on our end we still need to do! @dims @liggitt

**Comment by dims** [comment]
Thanks @dcantah when 1.19 opens, i'll propose a PR to move cri-api from staging/

**Comment by dcantah** [comment]
@dims Awesome. Keep me updated

**Comment by dims** [comment]
@dcantah i've raised a PR that effectively removes cri-api from the hcsshim root go.mod by adding a separate go.mod for the test directory, please take a look:
https://github.com/microsoft/hcsshim/pull/789

**Comment by dcantah** [comment]
@dims @liggitt https://github.com/microsoft/hcsshim/pull/789 has been merged

**Comment by dims** [comment]
@dcantah @liggitt this turned out nicely, please see https://github.com/kubernetes/kubernetes/pull/89710 

@dcantah can you please cut a release/tag that we can use to vendor the dependency back into kubernetes.

**Comment by dcantah** [comment]
I'll consult with the team tomorrow :)

**Comment by dims** [comment]
@dcantah Any update? thanks!

**Comment by dcantah** [comment]
@dims My apologies. We're waiting on a bug fix that has a pr out right now and hopefully should be merged soon if not tomorrow.

**Comment by dims** [comment]
@dcantah not an issue at all. thanks for the heads up.

**Comment by dcantah** [comment]
@dims last bug fix went in today so drafted the release and will have it reviewed by team on Monday!

**Comment by dims** [comment]
very cool! thanks for the heads up @dcantah

**Comment by daschott** [comment]
@dcantah any updates? thank you so much! :)

**Comment by dcantah** [comment]
@daschott @dims Release is finally out. I'm sorry for the delay we had more fixes on our end that needed to happen. Let me know if there's any problems or other things we need to do on our side. https://github.com/microsoft/hcsshim/releases/tag/v0.8.8

**Comment by dcantah** [comment]
@dims If possible can we hold off on vendoring the above? There's a commit that another team has been trying to get vendored in that slipped my mind. I'll see if I can re-upload the release with this in by today as I'm not able to delete it myself. My apologies

**Comment by dims** [comment]
@dcantah sounds good!

**Comment by dcantah** [comment]
Just ended up making a new release with this changes. https://github.com/microsoft/hcsshim/releases/tag/v0.8.9 @dims @daschott Hopefully this is finally resolved! 😁
