### ISSUE TITLE
[TaintBasedEvictions] Ensure test coverage is complete and up-to-date

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#87427]
As part of promoting TaintBasedEvictions to GA in 1.18 (https://github.com/kubernetes/kubernetes/issues/87161), we need to make sure that the test coverage is sufficient. There are some tests mentioned in the KEP, and as mentioned in https://github.com/kubernetes/enhancements/pull/1450#discussion_r366899543, those that are still under scheduling should be moved to the appropriate SIGs (sig-node or sig-cloud-provider)

/kind cleanup

**Comment by damemi** [comment]
@fengzixu would you like to take this? It should mostly only be moving the tests from scheduling to an appropriate sig

**Comment by fengzixu** [comment]
/assign @fengzixu 

Of course. Thank you @damemi

**Comment by fengzixu** [comment]
After I detected related tests, I want to ask 

1. Where I need to move for integration test `TestTaintBasedEvictions ` ?  It seems like related to sig-node. But I didn't find the `node` directory under integration director.https://github.com/kubernetes/kubernetes/blob/47d5c3ef8df2b1b26da739aec0ada15d41f20cf3/test/integration/scheduler/taint_test.go#L580

@damemi @Huang-Wei

**Comment by Huang-Wei** [comment]
> I want to move it into the eviction directory.

It makes sense to me.

@ahg-g Have we got an agreement with sig-node? Technically speaking, it's more belong to sig-apps as the primary code exists under `pkg/controller/nodelifecycle`.

**Comment by skilxn-go** [comment]
Kindly ping @fengzixu what's the progress of this issue? Need any help?

**Comment by fengzixu** [comment]
@skilxn-go Let me submit the PR by Wednesday.

**Comment by skilxn-go** [comment]
Thanks, just checking. 👍

**Comment by fengzixu** [comment]
Should I move the integration Test `TestTaintBasedEvictions` into the `app` directory of e2e test?
According to this comment: https://github.com/kubernetes/enhancements/pull/1510#issuecomment-579329753

@skilxn-go

**Comment by skilxn-go** [comment]
Actually, I'm not quite sure about it. But I guess `TaintBasedEviction` is better to be put under sig-node. @Huang-Wei Do we have an agreement about where to put those tests?

**Comment by fengzixu** [comment]
@Huang-Wei I decide to move the TestTaintBasedEvictions into the evictions directory. WDYT?

**Comment by Huang-Wei** [comment]
@skilxn-go As the code mostly is located under `pkg/controller/nodelifecycle`, it's more reasonable to be owned by sig-apps. @damemi what's the latest status on this?

**Comment by k82cn** [comment]
sig-node takes the responsibility to nodelifecycle and nodeipm, please ping the approver in its OWNERS file; I can help on PR review if necessary.

Regarding integration test directory, `node/controller` or `node/lifecycle` is better as we may also add integration test for nodeipm.

**Comment by fengzixu** [comment]
According to the suggestion from @k82cn and @Huang-Wei . I plan to move the `TaintBasedEviction` into the node directory under `test/integration/`. It means I need to create a new directory.

**Comment by damemi** [comment]
@Huang-Wei spoke to @soltysh and @tnozicka from sig-apps, they also feel it is more appropriate under sig-node

**Comment by damemi** [comment]
@fengzixu are you still working on a PR for this? If so please link it to this issue so we can track it

**Comment by fengzixu** [comment]
@damemi Yep. Actually I have moved it into the eviction directory. I am revising it according to `move to sig-node` suggestion. Submit PR by tomorrow.

**Comment by damemi** [comment]
/reopen
#88685 was just part of this issue
