### ISSUE TITLE
Expiration field for role bindings

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#87433]
**What would you like to be added**:

An optional expiration date for role bindings

**Why is this needed**:

To help administrators manage temporary work situations in a more automated, reliant fashion.

**Comment by liggitt** [comment]
Something similar was proposed in https://github.com/kubernetes/kubernetes/issues/2204. As noted there, this could be accomplished out of tree with a binding-removing controller. 

/priority awaiting-more-evidence

**Comment by liggitt** [comment]
This was discussed in today's sig-auth meeting, and the same conclusion in https://github.com/kubernetes/kubernetes/issues/2204 was reached. This can be implemented as a layer on top of the existing API, and there is no plan to build this into the core.

/close
