### ISSUE TITLE
REQUEST: New membership for YuikoTakada

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes/kubernetes#87445]
## GitHub Username

@YuikoTakada 

## Organization you are requesting membership in

@kubernetes

## Requirements

- [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x]  I am actively contributing to 1 or more Kubernetes subprojects
- [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application 

## Sponsors

- @SataQiu 
- @oomichi 

### PRs reviewed / authored

- [kubernetes/community#87317](https://github.com/kubernetes/kubernetes/pull/87317)
- [kubernetes/community#87270](https://github.com/kubernetes/kubernetes/pull/87270)
- [kubernetes/community#87221](https://github.com/kubernetes/kubernetes/pull/87221)
- [kubernetes/community#87175](https://github.com/kubernetes/kubernetes/pull/87175)
- [kubernetes/community#87173](https://github.com/kubernetes/kubernetes/pull/87173)
- [kubernetes/community#87062](https://github.com/kubernetes/kubernetes/pull/87062)
- [kubernetes/community#86652](https://github.com/kubernetes/kubernetes/pull/86652)
- [kubernetes/community#86570](https://github.com/kubernetes/kubernetes/pull/86570)
- [kubernetes/community#86568](https://github.com/kubernetes/kubernetes/pull/86568)
- [kubernetes/community#85522](https://github.com/kubernetes/kubernetes/pull/85522)
- [kubernetes/community#85119](https://github.com/kubernetes/kubernetes/pull/85119)
- [kubernetes/community#84897](https://github.com/kubernetes/kubernetes/pull/84897)
- [kubernetes/community#84892](https://github.com/kubernetes/kubernetes/pull/84892)
- [kubernetes/community#84499](https://github.com/kubernetes/kubernetes/pull/84499)
- [kubernetes/community#84427](https://github.com/kubernetes/kubernetes/pull/84427)
- [kubernetes/community#83148](https://github.com/kubernetes/kubernetes/pull/83148)

### Issues responded to

- [kubernetes/kubernetes#81245](https://github.com/kubernetes/kubernetes/issues/81245)
- [kubernetes/kubernetes#81657](https://github.com/kubernetes/kubernetes/issues/81657)
- [kubernetes/kubernetes#86651](https://github.com/kubernetes/kubernetes/issues/86651)
- [kubernetes/kubernetes#84380](https://github.com/kubernetes/kubernetes/issues/84380)
- [kubernetes/kubernetes#84380](https://github.com/kubernetes/kubernetes/issues/84380)
- [kubernetes/kubernetes#81427](https://github.com/kubernetes/kubernetes/issues/81427)

### SIG projects I am involved with

[sig-testing](https://github.com/kubernetes/community/tree/master/sig-testing)

**Comment by haosdent** [comment]
May need to raise this at https://github.com/kubernetes/org

**Comment by YuikoTakada** [comment]
thanks. I'll close this PR.
