### ISSUE TITLE
[Flaky Test] Stage

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#87441]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce
pull-kubernetes-e2e-gce-rbe

**Which test(s) are flaking**:
Stage

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-rbe&include-filter-by-regex=Overall%7CBuild%7CStage
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=Overall%7CBuild%7CStage

**Reason for failure**:
This isn't technically a test that's failing, it's part of the build->stage->up->test cycle used by our e2e jobs.

There are two main clusters of failures that I can tell.  One is timeouts.

The other looks like:
```
- Hashing and copying public release artifacts to
gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.18.0-alpha.2.14+1b7738cc4ebdbe:
$TEST_TMPDIR defined: output root default is '/bazel-scratch/.cache/bazel' and max_idle_secs default is '15'.
Server terminated abruptly (error code: 14, error message: '', log file: '/bazel-scratch/.cache/bazel/_bazel_prow/cae228f2a89ef5ee47c2085e441a3561/server/jvm.out')
Signal ERR caught!
Traceback (line function script):
208 main /home/prow/go/src/k8s.io/release/push-build.sh
Exiting...
```
Example -gce jobs:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85861/pull-kubernetes-e2e-gce/1219647945268269056 (#85861)
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85846/pull-kubernetes-e2e-gce/1219646811342376960 (#85846)
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87422/pull-kubernetes-e2e-gce/1219612336432615426 (#87422)
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87372/pull-kubernetes-e2e-gce/1219266675761745921 (#87372)

Example -gce-rbe jobs:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87435/pull-kubernetes-e2e-gce-rbe/1219718868767870977
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87266/pull-kubernetes-e2e-gce-rbe/1219655997224652803
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86408/pull-kubernetes-e2e-gce-rbe/1219620136827228160

(source gist https://gist.github.com/spiffxp/ed54d006e630b8fd8126ddfe67d9dc1e)

**Anything else we need to know**:
- Triage link for the job that actually reports to PRs: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=gce%24&test=Stage
- [The line where the crash is happening]( https://github.com/kubernetes/release/blob/f59f6ba61ac5f225cde91ff0fc179a0a6f762841/lib/releaselib.sh#L1148) ends up running `bazel run //:push-build $gcs_stage $gcs_destination`
- Some googling for "bazel error code 14" leads me to believe that bazel (or its jvm) is getting killed due to OOM.  [This job requests 6Gi of memory](https://github.com/kubernetes/test-infra/blob/b2471685eed6a7d063d7e1e19032282bb33679db/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L59-L61) which is a value that's been cargo culted around as far as I can tell.  I was unable to find the decision that led to this value.  I'm wondering if a bump to 8Gi of memory would help reduce occurrences of this flake.
- I'm referencing the -rbe jobs to point out that this happens even if we use RBE, but they're not blocking

**Comment by spiffxp** [comment]
/sig testing
Top flake according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by spiffxp** [comment]
With https://github.com/kubernetes/test-infra/pull/15980 merged we'll wait and see if the Stage flakes on pull-kubernetes-e2e-gce go down.  If they do, there are other presubmit jobs that could benefit from that.  If they don't, we should revert.

**Comment by spiffxp** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=gce%24&test=Stage

Still seeing flakes, so I don't think just bumping memory request helped.

---

@BenTheElder 

ref: https://github.com/kubernetes/test-infra/pull/15980#issuecomment-576932189
>my theory is that making this non-privileged broke our ability to free memory

This happened via https://github.com/kubernetes/test-infra/pull/12140 around 2019-04-11
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-04-15&pr=1&job=gce%24&test=Stage - flakes were still occurring prior to this merge 
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-04-15&pr=1&job=gce%24&test=Stage - but not prior to 2019-04-01
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2019-03-15&pr=1&job=gce%24&test=Stage - and very infrequently prior 2019-03-15

It could be that bazel's memory usage grew when we bumped it to 0.23.2 on 2019-03-29 https://github.com/kubernetes/test-infra/pull/12004 (or maybe https://github.com/kubernetes/test-infra/pull/12028 on 2019-04-02 is what actually deployed the change)

---

Either way, I agree it looks like bazel is eating more memory than the container is allowed. Two ideas:
- Instead of allowing the bazel server to exist as a long lived process, have kubetest call `bazel shutdown` in between the Build and Stage steps, in addition to trying to flush memory
- Constrain bazel's host JVM to a hardcoded memory limit via `startup --host_jvm_args=-Xms1234m -Xmx1234m` in bazelrc

**Comment by BenTheElder** [comment]
Idea 3: switch build modes and see how expensive / flaky that is. Including:
- use RBE
- use the dockerized build instead

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/pull/16004 to try and constrain the JVM's memory.  Jobs that use RBE behave the same way, so try doing the same to them for comparison's sake.

**Comment by pascalstindt** [comment]
#87588

**Comment by liggitt** [comment]
this is still being seen extremely frequently (seen multiple times in a row on the same PR at https://github.com/kubernetes/kubernetes/pull/87664)

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/pull/16071 for the last idea I have for working around bazel's behavior, beyond this I am out of my depth on how to replace bazel for the release/push-build.sh script

**Comment by spiffxp** [comment]
... but I'm willing to try with a canary job and see what happens https://github.com/kubernetes/test-infra/pull/16073

**Comment by liggitt** [comment]
bumping priority, this looks like 99/122 flakes according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json
/priority critical-urgent

**Comment by tedyu** [comment]
Another occurrence:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87818/pull-kubernetes-e2e-gce-csi-serial/1225252821763362826/

**Comment by liggitt** [comment]
I'd like to see if we can root cause what changed around 1/27-1/29 that greatly increased this

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-02-08&ci=0&pr=1&text=push-build&job=e2e-gce%24

**Comment by liggitt** [comment]
kubernetes/kubernetes changes:
* 1/26, ~6am UTC: e2b823fa7dd1ef61debc524e0e07f74db8ba4d91
* 1/28: ~6pm UTC: 53376cdf12b31c3c2405758c97e2ebca442ea7ea
* https://github.com/kubernetes/kubernetes/compare/e2b823fa7dd1ef61debc524e0e07f74db8ba4d91..53376cdf12b31c3c2405758c97e2ebca442ea7ea

test-infra changes:
* 1/25, ~3pm UTC: 2dfd2d812e2f294eb66e7438c0acc1281df5c5dc
* 1/28: ~8pm UTC: 15e661e6a2798eb50538e86ffa81caedf2db4903
* https://github.com/kubernetes/test-infra/compare/2dfd2d812e2f294eb66e7438c0acc1281df5c5dc..15e661e6a2798eb50538e86ffa81caedf2db4903

in that delta kubekins changed from v20200123-0a8437a to v20200127-8d34d6e
* https://github.com/kubernetes/test-infra/compare/0a8437a..8d34d6e

nothing jumps out at me in those diffs, but wanted to link to them in case it helped anyone else see something

**Comment by BenTheElder** [comment]
It doesn't have to be one, the CI is run overcommitted with no limits,
something else could be upping memory pressure..?

**Comment by liggitt** [comment]
ok... after sweeping k/k and test-infra for that time period, nothing clear emerged, and the bazel bandaids seem to be holding for now. unsatisfying :-/

/close
