### ISSUE TITLE
Wrong API documentation references: 1.16 shows 1.17

### ISSUE THREAD

**Issue by walterdolce** [kubernetes/kubernetes#87454]
**What happened**:
Went to check API docs for 1.16, but saw it was for 1.17

**What you expected to happen**:
Read API docs for 1.16

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/

**Anything else we need to know?**:
Please screenshot:
<img width="1303" alt="Screenshot_2020-01-22_at_09_50_56" src="https://user-images.githubusercontent.com/6195629/72884211-acb29a80-3cfd-11ea-810c-0ab6d3b9abec.png">

**Environment**:
N/A

**Comment by liggitt** [comment]
Thanks for the issue. This probably belongs in https://github.com/kubernetes/website/issues

**Comment by walterdolce** [comment]
Someone already spotted it. Thanks for the redirection @liggitt
