### ISSUE TITLE
Bump structured merge diff dependency to v3.0.0

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/kubernetes#87466]
This issue is to make sure we bump the structured merge diff dependency to non pre-release version of v3.0.0 prior to release of 1.18, as a follow up to https://github.com/kubernetes/kubernetes/pull/87442

/wg apply
/sig api-machinery
/milestone 1.18
/assign
/cc @liggitt @apelisse

**Comment by gianarb** [comment]
Hello @jennybuckley    !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by apelisse** [comment]
I think this is obsolete? Joe did bump smd through another PR, am I correct @jennybuckley ?

**Comment by gianarb** [comment]
Hello @jennybuckley @kubernetes/sig-api-machinery-bugs !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by apelisse** [comment]
Maybe it shouldn't have been closed 3 days ago, but now I think it's fine to close it, since we tagged smd with `v3.0.0`: https://github.com/kubernetes-sigs/structured-merge-diff/tree/v3.0.0
