### ISSUE TITLE
PluginConfig for InterPodAffinity not respected

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87474]
/sig scheduling
/kind feature

Now that framework migration phase 2 is done and Plugins are first class citizens of kube-scheduler, I think we should honor PluginConfig for the default plugins (today just InterPodAffinity).

We have most of the machinery to do so, but since we have `KubeSchedulerConfiguration.HardPodAffinitySymmetricWeight`, we use this value to override whatever is set in `PluginConfig`, even if the user doesn't specify anything in their Component Config file.

I think we should honor PluginConfig, unless `HardPodAffinitySymmetricWeight` is set.

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei

**Comment by ahg-g** [comment]
Since we are bumping the ComponentConfig API version, I suggest we just remove the CC parameter.

**Comment by alculquicondor** [comment]
Actually, we will remove it from `v1alpha2` as detailed in the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20200114-multi-scheduling-profiles.md)

However, I assume we still need to keep `v1alpha1`, parse it and configure the scheduler with it? Although, if we simply convert it to the `v1alpha2`, then we would create a PluginConfig for this parameter. However, if we find args for that plugin already, we need to decide which one we override.

**Comment by ahg-g** [comment]
Yeah, we need to convert it to the [internal type](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/types.go#L46), which will not have that field. 

A v1alpha1 config can be validated such that setting the field in both places is rejected.

**Comment by Huang-Wei** [comment]
> However, I assume we still need to keep v1alpha1, parse it and configure the scheduler with it?

I see some cases that promote an alpha version while eliminating the preceding one - e.g., just keep v1lapha2 in the codebase.

> I suggest we just remove the CC parameter.

+1 on this as that field doesn't make sense to apply globally to CC. We should enforce the customized symmetric weight to be provided in podaffinity pluginConfig. Otherwise, just use the default symmetric weight.

**Comment by alculquicondor** [comment]
/close

#88002 should be enough
