### ISSUE TITLE
Fake client watch + informer dropping events

### ISSUE THREAD

**Issue by vtereso** [kubernetes/kubernetes#87472]
I have been running into testing inconsistencies when using informers. With a high enough test count, the informer is presumably not called since the channel hangs to receive forever. To reproduce, try running the code below with `go test -v --count=1000000 <pkg>`:
```go
package tester

import (
	"testing"

	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sinformers "k8s.io/client-go/informers"
	fakek8sclientset "k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/tools/cache"
)

func TestInformer(t *testing.T) {
	k8sClient := fakek8sclientset.NewSimpleClientset()
	sharedK8sInformerFactory := k8sinformers.NewSharedInformerFactory(k8sClient, time.Duration(time.Hour))
	serviceInformer := sharedK8sInformerFactory.Core().V1().Services().Informer()

	informerChan := make(chan struct{})

	serviceInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(_ interface{}) {
			informerChan <- struct{}{}
		},
	})
	sharedK8sInformerFactory.Start(make(chan struct{}))

	ns := "test-namespace"
	_, err := k8sClient.CoreV1().Namespaces().Create(&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: ns}})
	if err != nil {
		t.FailNow()
	}
	svc := &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name: "s",
		},
	}
	// Create extension service and await corresponding event
	_, err = k8sClient.CoreV1().Services(ns).Create(svc)
	if err != nil {
		t.Fatalf("Error creating service: %v\n", err)
	}
	<-informerChan
}
```
I have tried to set different values for the resync period (`time.Duration(0)`, `time.Second`, etc.), but the same hanging occurs. Should this not be used for tests or with the fake client? Has it been patched? Any insight is appreciated.

From my Gopkg.toml
---
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

**Comment by liggitt** [comment]
fake client tries to simulate watches with reasonable fidelity, but the implementation is completely different than the real apiserver watch implementation, it would not surprise me if there are bugs or race conditions present in the fake client mock. are you only seeing this in informers used in combination with the fake client?

**Comment by vtereso** [comment]
I am experiencing this in unit tests with the fake client, which is giving us test flakes. I couldn't say for sure whether this is happening with the regular client.

**Comment by damoye** [comment]
@vtereso 
Adding a factory.WaitForCacheSync after factory.Start and before create resources helps me.
Maybe there is a race between List and Create of fake client.
