### ISSUE TITLE
E2E: [sig-api-machinery] Garbage collector should support cascading deletion of custom resources

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#87473]
This is near the top of the flakiness list: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&sort-by-flakiness=

I looked at the most recent flake, it looks like the GC legit just did not delete the expected thing at all. 60 seconds seems plenty generous.

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1219764546487455746

One idea is to switch to foreground deletion, so at least you could tell when the GC thinks it is done.

/kind flake
/sig api-machinery

**Comment by caesarxuchao** [comment]
The GC processed the dependent 12 times, e.g., 

```
I0122 00:26:12.267173       1 garbagecollector.go:404] processing item [mygroup.example.com/v1beta1/foo8hxrka, namespace: , name: dependentzr55z, uid: bab11ce0-9f8d-4f39-be4e-05f82e8e6025]
```
The last attempt was at 00:32:25.183915.

I don't know why the GC didn't delete the dependent.

In the apiserver log, the GC got the 404 when GET the owner:
```
I0122 00:26:12.098285       1 httplog.go:90] verb="GET" URI="/apis/mygroup.example.com/v1beta1/foo8hxrkas/ownerg6bb4" latency=479.159817ms resp=404 UserAgent="kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/b43ea3e/system:serviceaccount:kube-system:generic-garbage-collector" srcIP="[::1]:48724": 
```
So even if the GC hasn't observed the delete event of the owner, it should know the owner was gone by now.

As a side note, the GC observed the deletion of the owner:
```
I0122 00:26:11.408661       1 garbagecollector.go:404] processing item [mygroup.example.com/v1beta1/foo8hxrka, namespace: , name: ownerg6bb4, uid: e0e62e14-55c7-4634-986d-64526429f105]
```
IIRC that means the owner was added as a virtual node.

**Comment by lavalamp** [comment]
Yeah, that's what I saw, too. So it sounds like this might be an actual system bug?

/kind bug
/priority important-soon

**Comment by caesarxuchao** [comment]
Yes, this can be an actual bug.

After printing the "processing xxx" log, GC will GET the object from the apiserver, unless the object has a non-nil deletion timestamp ([code](https://github.com/kubernetes/kubernetes/blob/f409793eb6574f1ab92afd910dbbf0ed90e6bcbb/pkg/controller/garbagecollector/garbagecollector.go#L406-L413)). The apiserver log showed that the GC never tried to GET the dependent, so it means that the GC thought the object had a non-nil deletion timestamp. On the other hand, the apiserver log did not contain and DELETE of the dependent.

I'll send a PR to print out the last state of the dependent. I'll figure out the next step based on if the dependent actually has a deletionTimestamp.

**Comment by lavalamp** [comment]
> the GC never tried to GET the dependent, so it means that the GC thought the object had a non-nil deletion timestamp

Maybe a deletecollection request caused this? Due to the test framework deleting the namespace after the test failed?

**Comment by tedyu** [comment]
```
	go garbageCollector.Sync(gcClientset.Discovery(), 30*time.Second, ctx.Stop)
```
If owner was deleted around 00:26:11.408661, there didn't seem to be enough time till the next GC run (00:26:41 which was after 00:26:19 when the test failed)

**Comment by caesarxuchao** [comment]
@tedyu I checked the timeline, GC had ~7 seconds to delete the dependent.

**apiserver log**

I0122 00:25:17.212776       1 httplog.go:90] verb="DELETE" URI="/apis/mygroup.example.com/v1beta1/foo8hxrkas/ownerg6bb4" latency=298.740317ms resp=200 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-api-machinery] Garbage collector should support cascading deletion of custom resources" srcIP="34.66.138.240:54168": 

first "GET" of the dependent by the e2e.test:
I0122 00:25:27.729204       1 httplog.go:90] verb="GET" URI="/apis/mygroup.example.com/v1beta1/foo8hxrkas/dependentzr55z" latency=182.420722ms resp=200 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-api-machinery] Garbage collector should support cascading deletion of custom resources" srcIP="34.66.138.240:54168": 

GC "GET" the owner, got 404 back
I0122 00:26:12.098285       1 httplog.go:90] verb="GET" URI="/apis/mygroup.example.com/v1beta1/foo8hxrkas/ownerg6bb4" latency=479.159817ms resp=404 UserAgent="kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/b43ea3e/system:serviceaccount:kube-system:generic-garbage-collector" srcIP="[::1]:48724":

last "GET" of the dependent by the e2e.test:
I0122 00:26:18.893609       1 httplog.go:90] verb="GET" URI="/apis/mygroup.example.com/v1beta1/foo8hxrkas/dependentzr55z" latency=512.46691ms resp=200 UserAgent="e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-api-machinery] Garbage collector should support cascading deletion of custom resources" srcIP="34.66.138.240:54168": 

**controller manager log**
I0122 00:26:12.267173       1 garbagecollector.go:404] processing item [mygroup.example.com/v1beta1/foo8hxrka, namespace: , name: dependentzr55z, uid: bab11ce0-9f8d-4f39-be4e-05f82e8e6025]

GC should have sent a DELETE for the dependent shortly after 00:26:12, before the last "GET" of the dependent by the e2e.test at 00:26:18.

**Comment by tedyu** [comment]
Logs which would give us clue are at level 5.

I have run gce-e2e a few times but this test passed in those runs.

**Comment by hasheddan** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/78819

@caesarxuchao any updates here?

**Comment by liggitt** [comment]
this got much worse around 1/24:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-e2e-gce%24#e13ce6a3eff5d487df1c

I don't see anything related to GC merging around then, but I do see two PRs that might bear investigation:
* server-side apply enabled for 50% of requests: https://github.com/kubernetes/kubernetes/pull/87500 (could push things sitting on the edge of timeouts over the edge)
* https://github.com/kubernetes/kubernetes/pull/87393 modified shared informers... I think it was supposed to be a no-op, but might be good to look closely to make sure it didn't introduce a bug

**Comment by liggitt** [comment]
looking at recent failures, at least some of them are simply caused by the test not waiting long enough

from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84051/pull-kubernetes-e2e-gce/1222516022213349380:

The test failed (from the e2e logs):
* `Jan 29 14:29:10.727: failed waiting for dependent resource "dependentvlnzl" to be deleted`

And the GC delete occurred a few seconds later (from the controller manager logs):
* `I0129 14:29:13.011587       1 garbagecollector.go:517] delete object [mygroup.example.com/v1beta1/foo6m8k8a, namespace: , name: dependentvlnzl, uid: 9a14796b-b2b2-4df9-881f-aa0e104f8114] with propagation policy Background`

and was verified not to exist:
* `E0129 14:29:13.358221       1 garbagecollector.go:309] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"mygroup.example.com/v1beta1", Kind:"foo6m8k8a", Name:"dependentvlnzl", UID:"9a14796b-b2b2-4df9-881f-aa0e104f8114", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:""}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, deletingDependents:false, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:false, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"mygroup.example.com/v1beta1", Kind:"foo6m8k8a", Name:"owner8rbs8", UID:"6fc4ebd4-047a-43f6-8a34-d36b72aee93c", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}}: foo6m8k8as.mygroup.example.com "dependentvlnzl" not found`

**Comment by liggitt** [comment]
timeline:

e2e test created resource:
* `Jan 29 14:28:08.134: INFO: created dependent resource "dependentvlnzl"`

GC synced with new CRD type:
```
I0129 14:28:40.049974       1 garbagecollector.go:200] syncing garbage collector with updated resources from discovery (attempt 1): added: [mygroup.example.com/v1beta1, Resource=foo6m8k8as wardle.example.com/v1alpha1, Resource=fischers wardle.example.com/v1alpha1, Resource=flunders], removed: []
I0129 14:28:40.050009       1 garbagecollector.go:206] reset restmapper
E0129 14:28:51.449692       1 garbagecollector.go:218] failed to sync resource monitors (attempt 1): [couldn't look up resource "wardle.example.com/v1alpha1, Resource=flunders": no matches for wardle.example.com/v1alpha1, Resource=flunders, couldn't look up resource "wardle.example.com/v1alpha1, Resource=fischers": no matches for wardle.example.com/v1alpha1, Resource=fischers]
I0129 14:28:55.944199       1 garbagecollector.go:200] syncing garbage collector with updated resources from discovery (attempt 2): added: [mygroup.example.com/v1beta1, Resource=foo6m8k8as], removed: []
I0129 14:28:55.944233       1 garbagecollector.go:206] reset restmapper
I0129 14:28:55.944365       1 garbagecollector.go:221] resynced monitors
I0129 14:28:55.944373       1 shared_informer.go:205] Waiting for caches to sync for garbage collector
I0129 14:28:55.944412       1 graph_builder.go:272] garbage controller monitor not yet synced: mygroup.example.com/v1beta1, Resource=foo6m8k8as
I0129 14:28:56.045553       1 graph_builder.go:272] garbage controller monitor not yet synced: mygroup.example.com/v1beta1, Resource=foo6m8k8as
I0129 14:28:56.246887       1 shared_informer.go:212] Caches are synced for garbage collector 
I0129 14:28:56.246901       1 garbagecollector.go:241] synced garbage collector
```

GC observed new parent:
```
I0129 14:28:56.246924       1 garbagecollector.go:404] processing item [mygroup.example.com/v1beta1/foo6m8k8a, namespace: , name: owner8rbs8, uid: 6fc4ebd4-047a-43f6-8a34-d36b72aee93c]
```

GC observed dependent:
```
I0129 14:29:12.394115       1 garbagecollector.go:404] processing item [mygroup.example.com/v1beta1/foo6m8k8a, namespace: , name: dependentvlnzl, uid: 9a14796b-b2b2-4df9-881f-aa0e104f8114]
```

GC deleted dependent:
```
I0129 14:29:13.011587       1 garbagecollector.go:517] delete object [mygroup.example.com/v1beta1/foo6m8k8a, namespace: , name: dependentvlnzl, uid: 9a14796b-b2b2-4df9-881f-aa0e104f8114] with propagation policy Background
```

GC observed dependent being gone:
```
E0129 14:29:13.358221       1 garbagecollector.go:309] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"mygroup.example.com/v1beta1", Kind:"foo6m8k8a", Name:"dependentvlnzl", UID:"9a14796b-b2b2-4df9-881f-aa0e104f8114", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:""}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, deletingDependents:false, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:false, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"mygroup.example.com/v1beta1", Kind:"foo6m8k8a", Name:"owner8rbs8", UID:"6fc4ebd4-047a-43f6-8a34-d36b72aee93c", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}}: foo6m8k8as.mygroup.example.com "dependentvlnzl" not found
```

**Comment by lavalamp** [comment]
> One idea is to switch to foreground deletion, so at least you could tell when the GC thinks it is done.

I think this sounds like a pretty reasonable change. We can make the time limit longer at the same time. I don't like the idea of just increasing the time limit when we've got two unknowns (time to GC observing, time to deletion after that).

**Comment by liggitt** [comment]
I like the idea of using a foreground delete to infer GC awareness of the new custom type, but I would do that with a new instance, just prior to waiting for the dependent to be deleted, to avoid changing the code path exercised by the existing test. Opened https://github.com/kubernetes/kubernetes/pull/87665 to do that

**Comment by droslean** [comment]
I wasn't able to find any flake with a reason described in the issue. Closing...
/close
