### ISSUE TITLE
Kubectl not working on GCE master

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#87481]
**What happened**:
Used kube-up.sh to bring up a GCE cluster and then logged on to the master.
Run kubectl on the master, is hangs for a while (30 seconds) and then returns an error.

$ kubectl get nodes
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding

**What you expected to happen**:
I expected to get the node list.
If I use one of the system account's kubeconfig files it works.

$ sudo kubectl --kubeconfig=/mnt/disks/master-pd/srv/kubernetes/kube-bootstrap/kubeconfig get nodes
NAME                           STATUS                     ROLES    AGE   VERSION
kubernetes-master              Ready,SchedulingDisabled   <none>   26m   v1.18.0-alpha.2.55+e41bb325c2453f-dirty
kubernetes-minion-group-jfk6   Ready                      <none>   26m   v1.18.0-alpha.2.55+e41bb325c2453f-dirty
kubernetes-minion-group-mqnp   Ready                      <none>   26m   v1.18.0-alpha.2.55+e41bb325c2453f-dirty
kubernetes-minion-group-x540   Ready                      <none>   26m   v1.18.0-alpha.2.55+e41bb325c2453f-dirty

**How to reproduce it (as minimally and precisely as possible)**:
Bring up a GCE cluster from head, ssh to master and run "kubectl get nodes"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.2.55+e41bb325c2453f-dirty", GitCommit:"e41bb325c2453fc373826f5cd2b8d9b106038d2f", GitTreeState:"dirty", BuildDate:"2020-01-23T00:38:39Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.2.55+e41bb325c2453f-dirty", GitCommit:"e41bb325c2453fc373826f5cd2b8d9b106038d2f", GitTreeState:"dirty", BuildDate:"2020-01-23T00:36:29Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GCE
- OS (e.g: `cat /etc/os-release`): COS m_77
- Kernel (e.g. `uname -a`): 4.19.76
- Install tools: cluster/kube-up.sh
- Network plugin and version (if this is a network-related bug):
- Others:

I believe this used to work based on talking to KAS on the insecure port using no authentication.
The insecure port is now turned off and we require authentication materials.
We should probably setup an admin account specifically for the master.

**Comment by liggitt** [comment]
I also would not have expected a hang, but an immediate error

**Comment by cheftako** [comment]
I believe the internal error is due to it defaulting to port 8080. Nothing is listening on that port.
This used to work but I would guess it stopped working when we stopped listening on the insecure port.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/75368#issuecomment-577953647 changed behavior of client-go on connection refused errors, which changed a short wait and an "invalid host/port" error into a long retry wait and a confusing "internal server" error

/assign @deads2k @mfojtik

**Comment by liggitt** [comment]
@cheftako if kubectl is intended to work automatically against the local API server, then a kubeconfig file should be set up, but the 30 second delay and incorrect error are a bug that should be fixed in client-go

/sig api-machinery

**Comment by liggitt** [comment]
/remove-sig api-machinery
/unassign @deads2k @mfojtik 

actually, moved the client-go issue to https://github.com/kubernetes/kubernetes/issues/87510

will keep this one for the GCE $KUBECONFIG resolution

**Comment by cheftako** [comment]
> Walter Fender if kubectl is intended to work automatically against the local API server, then a kubeconfig file should be set up

I agree that seems like the right fix.

**Comment by liggitt** [comment]
I'm not sure this belong to sig-cli... looks like https://github.com/kubernetes/kubernetes/pull/76792 made this change
/sig cluster-lifecycle
/cc @dekkagaijin

**Comment by dekkagaijin** [comment]
@cheftako Re: set up a kubeconfig
That's what we do for GKE: create an authenticated kubeconfig and set the `KUBECONFIG` env var. 
E.g. if you have an authenticated kubeconfig at `/mnt/disks/master-pd/srv/kubernetes/kube-bootstrap/kubeconfig`:
```shell
echo "export KUBECONFIG=/mnt/disks/master-pd/srv/kubernetes/kube-bootstrap/kubeconfig" > /etc/profile.d/kubeconfig.sh
```

**Comment by cheftako** [comment]
Yes, GKE sets up an admin system account for the master(s) as part of the internal-configure-helper. 
I believe we should do the same thing for GCE.
