### ISSUE TITLE
[Flaky Test] kubeadm-kinder-master (ci-kubernetes-e2e-kubeadm-kinder-master)

### ISSUE THREAD

**Issue by prksu** [kubernetes/kubernetes#87496]
**Which jobs are flaking**:

`kubeadm-kinder-master (ci-kubernetes-e2e-kubeadm-kinder-master)`

**Which test(s) are flaking**:

`task-02-create-cluster`

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master

**Reason for failure**:

```
Error: failed to create cluster: failed to write /kinder/node-settings.yaml: exit status 1
time="04:28:36" level=error msg="failed to write /kinder/node-settings.yaml: exit status 1"
 exit status 1
```

**Anything else we need to know**:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-kubeadm-kinder-master
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1220199959664529410

/cc @kubernetes/ci-signal 
/priority critical-urgent
/sig testing

**Comment by droslean** [comment]
It seems that it failed only once with the specific error. I don't consider this job as a flaky one. Let's try to observe it in the next days.

**Comment by ahmadnurus** [comment]
@droslean after digging this issue, seems this flaky already opened in kubernetes/kubeadm#1918. should we close this one?

**Comment by prksu** [comment]
@droslean after digging this issue seems this flaky already opened in https://github.com/kubernetes/kubeadm/issues/1918. should we close this one?

**Comment by neolit123** [comment]
> @droslean after digging this issue seems this flaky already opened in kubernetes/kubeadm#1918. should we close this one?

we don't know how to solve https://github.com/kubernetes/kubeadm/issues/1918
i'm suspecting a `docker cp` bug.

i suggest you close this issue and watch https://github.com/kubernetes/kubeadm/issues/1918

**Comment by neolit123** [comment]
i will include the node-settings in there too.

**Comment by neolit123** [comment]
given this is not failing consistently i'm dropping the priority
/remove-priority critical-urgent
/priority important-longterm
/sig cluster-lifecycle

but you might as well:
> i suggest you close this issue and watch kubernetes/kubeadm#1918

**Comment by prksu** [comment]
thanks, @neolit123 
will put eyes on https://github.com/kubernetes/kubeadm/issues/1918 and closing this one

/close
