### ISSUE TITLE
[Stale Job] kind-ipv6-master-parallel (ci-kubernetes-kind-ipv6-e2e-parallel)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#87497]
Job kind-ipv6-master-parallel (ci-kubernetes-kind-ipv6-e2e-parallel) stuck in progress since the 6th of Jan 2020.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel

**Prow link**:
https://prow.k8s.io/?job=ci-kubernetes-kind-ipv6-e2e-parallel

**Anything else we need to know**:
/sig testing
/cc @BenTheElder 
/cc @kubernetes/ci-signal 
/milestone v1.18
/priority critical-urgent

**Comment by BenTheElder** [comment]
deleted the stuck prowjob, new job triggered with current config.

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1220423385759092739/
/close
