### ISSUE TITLE
node Event missing apiVersion in the involvedObject

### ISSUE THREAD

**Issue by travisghansen** [kubernetes/kubernetes#87506]
**What happened**:

I'm attempting to use an `Events` watcher to better re-act to cluster modifications. I've received the below event:

```
{ 
   "metadata":{ 
      "name":"172.26.64.24.15ec9789b5157656",
      "namespace":"default",
      "selfLink":"/api/v1/namespaces/default/events/172.26.64.24.15ec9789b5157656",
      "uid":"28bf0748-3a6e-4590-8c4e-1f262ebb7519",
      "resourceVersion":"107982651",
      "creationTimestamp":"2020-01-23T18:29:49Z"
   },
   "involvedObject":{ 
      "kind":"Node",
      "name":"172.26.64.24",
      "uid":"bb6bd832-895d-11e8-bd5a-001d0917d583"
   },
   "reason":"RegisteredNode",
   "message":"Node 172.26.64.24 event: Registered Node 172.26.64.24 in Controller",
   "source":{ 
      "component":"node-controller"
   },
   "firstTimestamp":"2020-01-23T18:29:47Z",
   "lastTimestamp":"2020-01-23T18:29:47Z",
   "count":1,
   "type":"Normal",
   "eventTime":null,
   "reportingComponent":"",
   "reportingInstance":""
}
```

**What you expected to happen**:

I would expect the `involvedObject` to include `apiVersion` attribute. Not sure if it's all node events or just this particular one.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: bare metal, rancher's rke
- OS (e.g: `cat /etc/os-release`): centos host nodes
- Kernel (e.g. `uname -a`): 3.18, 4.4
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by travisghansen** [comment]
Just got another from kubelet..

```
{
  "type": "MODIFIED",
  "object": {
    ...
    "involvedObject": {
      "kind": "Node",
      "name": "redacted",
      "uid": "redacted"
    },
    "reason": "NodeNotReady",
    "message": "Node  status is now: NodeNotReady",
    "source": {
      "component": "kubelet",
      "host": ""
    },
    "firstTimestamp": "2020-01-16T23:27:09Z",
    "lastTimestamp": "2020-01-24T00:42:09Z",
    "count": 2529,
    "type": "Normal",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
  }
}
```

**Comment by liggitt** [comment]
recording code is here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/util/node/controller_utils.go#L159-L183
