### ISSUE TITLE
connection refused errors retry slowly and ultimately return incorrect error

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#87510]
/kind bug

https://github.com/kubernetes/kubernetes/pull/75368#issuecomment-577953647 changed behavior of client-go on connection refused errors, which changed a short wait and an "invalid host/port" error into a long retry wait and a confusing "internal server" error

/assign @deads2k @mfojtik

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/87481#issuecomment-577953730_

**Comment by deads2k** [comment]
I linked @mfojtik

**Comment by markyjackson-taulia** [comment]
@deads2k @mfojtik 
Hello, bug-triage here. Just want to make sure we are still staffed and on-track for v1.18 code freeze

**Comment by mfojtik** [comment]
@markyjackson-taulia thanks, I will get to this tomorrow.

**Comment by markyjackson-taulia** [comment]
@mfojtik gentle ping

![](https://apptimize.com/wp-content/uploads/2015/11/Code-Freeze.png)
