### ISSUE TITLE
Add logging to scheduler's event handlers

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#87524]
This helps debugging scheduler's behavior, currently we don't have logs that indicate when the scheduler first saw a pod or a node. The log level should be v=3.

/sig scheduling
/cc @Huang-Wei @alculquicondor

**Comment by skilxn-go** [comment]
Do you mean add logging for callbacks in 
`pkg/scheduler/eventhandlers.go`?

**Comment by ahg-g** [comment]
yes, at least for add and delete events

**Comment by skilxn-go** [comment]
Sure, I can also give this pr, before tomorrow

**Comment by alculquicondor** [comment]
3 would be the most appropriate level.

**Comment by alculquicondor** [comment]
We actually have one v=2 log line for a Node being added to the cache's tree:

https://github.com/kubernetes/kubernetes/blob/63d7733e988776355306e21947c43cb2f4fb8896/pkg/scheduler/internal/cache/node_tree.go#L86

But it's probably good to keep this one.
