### ISSUE TITLE
Deprecate AlgorithmSource from scheduler ComponentConfig

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#87526]
AlgorithmSource was meant to be a bridge to allow specifying a Policy file in ComponentConfig. Now that all Policy configuration is available through ComponentConfig directly, AlgorithmSource is not needed. This is the first step towards deprecating scheduler Policy file.

/assign @alculquicondor 
/cc @ravisantoshgudimetla @Huang-Wei @damemi 

/sig scheduling

**Comment by alculquicondor** [comment]
If agreed, we can do this as part of https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20200114-multi-scheduling-profiles.md, which is adding v1alpha2

Ref #85737

**Comment by Huang-Wei** [comment]
+1 on adding this as part of v1alpha2.

And in the KEP, we should point out that if a deprecated option (--algorithm-provider) is provided, how we'd honor the precedence. This is needed as the deprecated option is documented in the [official doc].(https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/)

**Comment by alculquicondor** [comment]
Our current behavior is that when using component config, command line flags are ignored, except for `--address` and `--port`

**Comment by alculquicondor** [comment]
We can proceed with the 2nd part of this after #89298 lands

**Comment by alculquicondor** [comment]
Actually, we still need to support the command line flag, don't we?

**Comment by damemi** [comment]
Bumping this, do we want to go forward with deprecating AlgorithmSource? Policy config is gone in v1alpha2 (and v1alpha1 is gone now too, right?) So the only thing AlgorithmSource still configures is the provider (which is only default or autoscaler https://github.com/kubernetes/kubernetes/blob/eb3405877799b770c72848c11aef967bda887eac/pkg/scheduler/algorithmprovider/registry.go#L60-L62)

So we could still support the `--algorithm-provider` flag if we need to but cut out everything else. What's the deprecation policy for this?

**Comment by alculquicondor** [comment]
I assume you meant removing it from `pkg/scheduler/apis/config/types.go`.

I'm fine with removing it as long as we can still support the flags in a reasonable way. But that code would go away once we graduate component config to GA in 2 releases. So I'm not sure if it's worth the refactoring effort.

**Comment by damemi** [comment]
> But that code would go away once we graduate component config to GA in 2 releases.

I'm fine waiting for this then, just wanted to check in on this issue since it hasn't had activity in some time to clarify where we are

**Comment by ahg-g** [comment]
/remove-lifecycle stale

AlgorithmSource was removed from component config external API, but still exist in the internal type to support the legacy policy API.

**Comment by ahg-g** [comment]
I think we can close this, removing the internal field will be part of policy API deprecation.
