### ISSUE TITLE
Scheduler Framework: Rename `PostFilter` to `PreScore`

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87523]
Our current plugins use the `PostFilter` score to do pre-processing for `Score`. It makes more sense for the endpoint to be renamed to `PreScore`. We can do so as we move to `v1alpha2` for the Component Config API (#85737). `PreScore` would no longer need to accept `NodeToStatusMap`.

This opens the possibility of more easily adding a *new* `PostFilter` endpoint which would accept and return a list of nodes, as it has been discussed in #87159 and #86630. ~~But we don't have to decide this now.~~ Follow this discussion in kubernetes/enhancements#1511

Progress:

- [ ] Rename postfilter to prescore, but keep the interface unchanged.
- [ ] Then remove filteredNodesStatuses NodeToStatusMap from prescore's interface.

/sig scheduling

/cc @ahg-g @Huang-Wei

**Comment by skilxn-go** [comment]
As I discussed with @Huang-Wei in slack before. If PostFilter is going to keep as an reporting point, can we add a new point like batch-filter? Which accept a list of nodes and returns a list of filtered nodes.
It's useful when we want to do some rpc-calls in filter plugin because we can send all nodes to a remote components in one HTTP request instead of one-by-one using filter-plugin, which is exactly the behavior of extender's filter.

**Comment by Huang-Wei** [comment]
How about:

- Define `PreScore` extension point, and move current in-tree `PostFilter` plugins as `PreScore` ones. It's fine to adjust the signature like removing `NodeToStatusMap`.
- On the other hand, as @skilxn-go mentioned, I'm leaning towards keeping current `PostFilter` extension point and its signature. IMO we might not want to close the door for consumers to hack (sometimes it can be innovational!) as long as it's complying with the ground design rationale of scheduler framework.

**Comment by alculquicondor** [comment]
The current signature for `PostFilter` doesn't allow to implement either of #87159 and #86630. We need to add `filteredNodes` to the return values.

**Comment by Huang-Wei** [comment]
> We need to add filteredNodes to the return values.

That sounds good. In that case, we don't need to "hack" to modify the object in place, right?

**Comment by alculquicondor** [comment]
> That sounds good. In that case, we don't need to "hack" to modify the object in place, right?
Exactly

So, both changes (new `PreScore`, and new return value in `PreFilter`) for 1.18?

**Comment by ahg-g** [comment]
renaming the current ```PostFilter``` extension point to ```PreScore``` sounds good to me, and that should be part of updating CC to v1alpha2.

**Comment by alculquicondor** [comment]
It looks like we have agreement on `PreScore` for 1.18.

I don't see any reason to hold on adding the changes for `PostFilter`. @ahg-g ?

**Comment by ahg-g** [comment]
Yeah, we can add that as well, PreScore is more critical to do in this cycle because we are doing a v1alpha2 anyway. PostFilter is only critical if we want to use it in this cycle (e.g., plan to move extenders to run as a PostFilter).

**Comment by Huang-Wei** [comment]
> I don't see any reason to hold on adding the changes for PostFilter

We can do either way - adjust the signature if we want to get #87159 done, otherwise, leave its signature as-is.

**Comment by ahg-g** [comment]
I think a safe way is to first rename, and make sure we properly convert v1alpha1 PostFilter plugin to a v1alpha2 PreScore plugin. And then we adding PostFilter back.

**Comment by alculquicondor** [comment]
> I think a safe way is to first rename PostFilter To PreScore, and make sure we properly convert v1alpha1 PostFilter plugin to a v1alpha2 PreScore plugin. And then we add PostFilter back.

I agree, but these are implementation details.

The most urgent thing is updating the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md). @skilxn-go can you take it?

**Comment by skilxn-go** [comment]
@alculquicondor Yes, I'm glad to take it, just assign it to me. I will send pr of details to the framework KEP.

**Comment by ahg-g** [comment]
/assign @skilxn-go 

Please send the kep update ASAP because the enhancement deadline is mid next week

**Comment by skilxn-go** [comment]
Got it, thianks!

**Comment by skilxn-go** [comment]
I'm now working on updating this KEP, but for this figure:
![image](https://user-images.githubusercontent.com/8231208/73118279-e947f580-3f8c-11ea-9c8a-b6d78e2280d6.png)
I don't have the original file of it. So, can I just draw a new one to replace this figure, and replace the post-filter endpoint with pre-score?

**Comment by alculquicondor** [comment]
@misterikkit, could you provide some help?

However, I would say just send the PR as is for now.

**Comment by alculquicondor** [comment]
Also, feel free to redo the picture too. It shouldn't be that hard with Inkscape or something like that :)

**Comment by skilxn-go** [comment]
Thanks, I have redo this picture using powerpoint. 😃

**Comment by skilxn-go** [comment]
@alculquicondor The kep is already merged, btw, is there any issue tracking the progress of v1alpha2? I didn't find things about it.

**Comment by skilxn-go** [comment]
And do I need to add the new definitation of post-filter to this KEP?
Now I just rename post-filter to pre-score in the KEP.

For clearify:
- In v1alpha1:
The post-filter should keep current behavior and it's name is not changed.

- In v1alpha2:
    - A pre-score plugin will do things that is done in **v1apha1.postfilter**
    - The post-filter plugin will return a filtered node list. And it's semantic is changed from a reporting plugin to a plugin that do actually filter works.

Is this right?

**Comment by alculquicondor** [comment]
Yes, please work on the KEP for adding PostFilter. Note that this needs to be merged by tomorrow EOD. But better have it today.

I'll create a tracking bug for all the `v1alpha2` efforts.

**Comment by skilxn-go** [comment]
Sure, working on it now

**Comment by alculquicondor** [comment]
Tracking #87617

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/enhancements/pull/1511#issuecomment-579820681

> And anyway, we need to remove NodeToStatusMap from pre-score interface.
Here is a problem with how to convert a v1alpha1.PostFilter to v1alpha2.PreScore plugin if we remove NodeToStatusMap? My suggest is passing an empty map to previous post-filter interface.
Can we reach this agreement?

This shouldn't be a problem, as no in-tree plugin uses that map.

**Comment by skilxn-go** [comment]
As we discussed, here is some base opinion for pre-score:
## interface
```go
PreScore(ctx context.Context, state *CycleState, pod *v1.Pod, nodes []*v1.Node) *Status
```
## some details
As we removed `filteredNodesStatuses NodeToStatusMap` from the interface, and v1alpha1.postfilter need it, when converting v1alpha1.postfilter to prescore, we will pass an empty `NodeToStatusMap` to it.

**Comment by skilxn-go** [comment]
> This shouldn't be a problem, as no in-tree plugin uses that map.
Yes, just searched, so it's safe for internal-plugins, and for user-custom plugins, it will cause some compatible problems.
I think we should notice that at release node?

**Comment by alculquicondor** [comment]
Yes, we should add the change to the release notes.

**Comment by skilxn-go** [comment]
Sure, I will start working on it after #87628 merged 😆

**Comment by skilxn-go** [comment]
This issue will be separated into two commits:

- [ ] Rename `postfilter` to `prescore`, and keep the interface unchanged.
- [ ] Remove `filteredNodesStatuses NodeToStatusMap` from `prescore`'s interface.

**Comment by skilxn-go** [comment]
@alculquicondor Hi, as we have reached an agreement, would you please close this issue, and I will create a clean one for tracking the progress, thanks.

**Comment by alculquicondor** [comment]
Why create a new one? In general, it's best to keep the full context.

**Comment by skilxn-go** [comment]
Sure, I just think maybe I should open a new clean issue for tracking progress. I will close them.

**Comment by skilxn-go** [comment]
This issue will be separated into two commits:
- [ ] Rename `postfilter` to `prescore`, but keep the interface unchanged.
- [ ] Then remove `filteredNodesStatuses NodeToStatusMap` from `prescore`'s interface.

**Comment by skilxn-go** [comment]
As I have sent one pr above to rename `postfilter` to `prescore`, I wonder if I should rename `pkg/scheduler/framework/v1alpha1` dir to `pkg/scheduler/framework/v1alpha2` in this pr?
@ahg-g @alculquicondor WDYT?

**Comment by alculquicondor** [comment]
Hello @skilxn-go, thanks a lot for your first PR.

Just checking if you can still work on the 2nd PR (remove the argument from the interface).

**Comment by skilxn-go** [comment]
Yep, just send my pr.
