### ISSUE TITLE
Skip default spreading scoring plugin for pods that define TopologySpreadConstraints

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#87521]
Currently the scheduler by default spreads the pods of a deployment based on a hard-coded [criteria](https://github.com/kubernetes/kubernetes/blob/90da466221c14e76b4509ddc310e7a7bd4e0039c/pkg/scheduler/framework/plugins/defaultpodtopologyspread/default_pod_topology_spread.go#L73). 

We recently added a pod object api (pod.Spec.TopologySpreadConstraints) that allows specifying spread behavior at the workload level. For pods that specify topology spread constraints, the default spreading behavior should not apply.

/sig scheduling
/cc @Huang-Wei @alculquicondor

**Comment by skilxn-go** [comment]
I can fix this behavior, can you assign it to me?

**Comment by ahg-g** [comment]
/assign @skilxn-go 

sure, lets wait for feedback first.

**Comment by skilxn-go** [comment]
sure

**Comment by alculquicondor** [comment]
I agree. Having the default spreading run would just water down the score given by the constraints.

Other than that, this would just be a temporary fix until #80639 is finalized
