### ISSUE TITLE
Update Azure auth module in kubectl to obtain proper audience claim in AAD token

### ISSUE THREAD

**Issue by weinong** [kubernetes/kubernetes#87541]
**What would you like to be added**:
add a flag in Azure auth module in kubectl to get AAD token with audience claim in proper (most commonly accepted) format.

**Why is this needed**:
The original issue is explained very well in #86410. In sort, the current `azure` auth module will get a token whose `audience` claim has `spn:` prefix. This prefix is not documented in most Azure AD documentation which causes confusion and blocks some scenario.

There was an attempt to update existing `azure` auth module in #86412 which resulted in a breaking behavior to existing k8s clusters using Azure AD OIDC. The issue is documented well in #87464. Hence, the #86412 PR is reverted in #87507.

As discussed in [here](https://github.com/kubernetes/kubernetes/issues/87464#issuecomment-577894188), a proper migration path to achieve #86410 with zero impact to existing clusters should be:
1. (client side change) add a flag in azure auth module in kubectl to allow new behavior
2. (server side change) update api server to support multiple `--oidc-client-id`
3. customers can opt in to update `--oidc-client-id=spn:<guid>;<guid>` so that kubectl in old and new can still authenticate with api-server
4. migrate kubectl/kubeconfig to use new flag
5. update `--oidc-client-id=<guid>`

This issue is to implement the first task: **(client side change) add a flag in azure auth module in kubectl to allow new behavior**

**Comment by weinong** [comment]
it seems a better approach to add a flag in cfg so that the auth modules dont become bloated

**Comment by tallclair** [comment]
Not owned by sig-auth
/remove-sig auth
/assign @feiskyer
