### ISSUE TITLE
The AddEventHandlerWithResyncPeriod of SharedInformer has an error condition but can not report it

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#87552]
**What happened**:
While studying the implementation, I noticed that a SharedInformer constructed with a defaultEventHandlerResyncPeriod of zero logs warnings (from the determineResyncPeriod func) after AddEventHandlerWithResyncPeriod is called with a non-zero resyncPeriod --- and the informer does no resyncs.  In short: such an informer does not honor the contract of such a call to its AddEventHandlerWithResyncPeriod method --- and the fact that it will not is immediately obvious in the implementation.  But this method can not return an error to its caller.

**What you expected to happen**:
I expected a way to tell the caller that its request will not be fully honored.

**How to reproduce it (as minimally and precisely as possible)**:
Read the API.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `master` branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
It seems resyncCheckPeriod value of 0 disables the resync.
I assume this is by design.

**Comment by MikeSpreitzer** [comment]
Yes, I would say that is clearly by design.  IMO, an informer that does not do resyncs should not be accepting a call that specifies resyncs.

**Comment by MikeSpreitzer** [comment]
In a similar vein: The constructors for shared informers take a default resync period but will not necessarily honor it and these constructors can not return an `error`.  This one is a little less serious --- it is a matter of quantity not quality.
