### ISSUE TITLE
[client-go] Can't override config values

### ISSUE THREAD

**Issue by vvelikodny** [kubernetes/kubernetes#87554]
original issue kubernetes/client-go#735

**What happened**:

I am loading my local kubeconfig which contains multiple clusters and contexts. The default context is "prod" and one of the config values I want to override is the `CurrentContext`

```golang
clientConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: "/Users/me/.kube/config"},
		&clientcmd.ConfigOverrides{
			CurrentContext: "stage",
		})

	rawConfig, _ := clientConfig.RawConfig()
	log.Printf(rawConfig.CurrentContext) // outputs "prod" instead of "stage"
```

**What you expected to happen**:
CurrentContext="stage"
```golang
	log.Printf(rawConfig.CurrentContext) // stage
```
**How to reproduce it (as minimally and precisely as possible)**:
use code above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2
- Cloud provider or hardware configuration: localhost
- OS (e.g: `cat /etc/os-release`): macOS
- Kernel (e.g. `uname -a`): Darwin ....local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
With the following change, the example passes:
```
diff --git a/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go b/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
index 44115130d99..51b37a4fb0c 100644
--- a/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
+++ b/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
@@ -91,6 +91,9 @@ func NewDefaultClientConfig(config clientcmdapi.Config, overrides *ConfigOverrid

 // NewNonInteractiveClientConfig creates a DirectClientConfig using the passed context name and does not have a fallback reader for auth information
 func NewNonInteractiveClientConfig(config clientcmdapi.Config, contextName string, overrides *ConfigOverrides, configAccess ConfigAccess) ClientConfig {
+       if len(overrides.CurrentContext) != 0 {
+               config.CurrentContext = overrides.CurrentContext
+       }
        return &DirectClientConfig{config, contextName, overrides, nil, configAccess, promptedCredentials{}}
 }
```
I am open to suggestion for better fix.

**Comment by vvelikodny** [comment]
@tedyu thanks for the answer, look at the my patch please, if it good
https://github.com/vvelikodny/kubernetes-client-go/commit/8c99132f9960bc61d3fceb0bd20ad3e5964f8203

**Comment by fedebongio** [comment]
/cc @deads2k 
who is already looking at the PR

**Comment by vvelikodny** [comment]
@fedebongio thanks

**Comment by harveyxia** [comment]
Is this PR still active?
