### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by hoizo** [kubernetes/kubernetes#87573]
Hello
they commissioned me to do this test:
1)installing docker-desktop and enabling kubernetes
2)Deployment of a minimal nginx in the kubernetes environment created
3)deployment of prometheus-graphana-node-exporter in the kube environment created
4) Access to graphana and create a simple dashboard that monitors the CPU used by the nginx pod
I installed docker-desktop and enabled kubernetes , then I started an application with docker but I can not start it with kubectl and then do not understand how to get the graphana data from prometheus.
Would anyone be able to help me?
Thank you.

**Comment by 928234269** [comment]
You can give more useful information like #87600.
