### ISSUE TITLE
[Azure] UseManagedIdentityExtension is broken for Auth with Azure container registry

### ISSUE THREAD

**Issue by shahzzzam** [kubernetes/kubernetes#87579]
**What happened**:
Using the Managed Identity feature from `az` cli, I created a cluster. I see that the Managed Identity credentials were baked into the agent like so:

```json
azureuser@aks-nodepool1-41751273-vmss000000:~$ sudo cat /etc/kubernetes/azure.json
{
    "cloud":"AzurePublicCloud",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
    "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
    "aadClientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
    "aadClientSecret": "<redacted>",
    "resourceGroup": "MC_aks-msi_myaks_westus",
    "location": "westus",
    "vmType": "vmss",
    "subnetName": "aks-subnet",
    "securityGroupName": "aks-agentpool-41751273-nsg",
    "vnetName": "aks-vnet-41751273",
    "vnetResourceGroup": "",
    "routeTableName": "aks-agentpool-41751273-routetable",
    "primaryAvailabilitySetName": "",
    "primaryScaleSetName": "aks-nodepool1-41751273-vmss",
    "cloudProviderBackoffMode": "v2",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderRatelimit": true,
    "cloudProviderRateLimitQPS": 10,
    "cloudProviderRateLimitBucket": 100,
    "cloudProviderRatelimitQPSWrite": 10,
    "cloudProviderRatelimitBucketWrite": 100,
    "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Standard",
    "disableOutboundSNAT": false,
    "excludeMasterFromStandardLB": true,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}
```

I grabbed the Identity, and assigned it an `AcrPull` role for a registry. 

```sh
cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: aks-demo
spec:
  containers:
    - name: private-reg-container
      image: myregistry.azurecr.io/hello-world:simple
EOF
pod/aks-demo created
samashah@shahzzzam-dev:~$ kubectl logs pod/aks-demo
Error from server (BadRequest): container "private-reg-container" in pod "aks-demo" is waiting to start: image can't be pulled
```

Kubernetes version on the cluster:
v1.14.8

There are no Level 4 logs from this method:

https://github.com/kubernetes/kubernetes/blob/fa6b8e8cac34dba78f374ca9c0940aac1b4b495b/pkg/credentialprovider/azure/azure_credentials.go#L221-L249

**What you expected to happen**:
Expecting it to Authenticate with ACR using token exchange: https://github.com/Azure/acr/blob/master/docs/Token-BasicAuth.md

We see that the requests coming in to ACR does not have any authentication headers (Basic or Bearer).

**How to reproduce it (as minimally and precisely as possible)**:
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.8
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by shahzzzam** [comment]
cc: @andyzhangx

**Comment by andyzhangx** [comment]
hi @shahzzzam, I have checked, this issue should be fixed by https://github.com/kubernetes/kubernetes/pull/77245 from k8s v1.15.0, and also verified that on AKS 1.15.7, MSI auth on ACR works well. And also share the MSI auth logs in 1.15.7 kubelet logs:
```
azure_credentials.go:189] try to provide secret for image andyacr2.azurecr.io/nginx-server
azure_credentials.go:233] discovering auth redirects for: andyacr2.azurecr.io
azure_credentials.go:240] exchanging an acr refresh_token
azure_credentials.go:248] adding ACR docker config entry for: andyacr2.azurecr.io
azure_credentials.go:189] try to provide secret for image docker.io/library/alpine
azure_credentials.go:194] image(docker.io/library/alpine) is not from ACR, skip MSI authentication
```

**Comment by shahzzzam** [comment]
@andyzhangx Does the current `az aks` use 1.15? how do I upgrade that? 
What steps should I take to make this work?

**Comment by andyzhangx** [comment]
You could specify aks version in az aks create
```
az aks create -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --node-count 1 --generate-ssh-keys --kubernetes-version 1.15.7 
```

and also could specify version in upgrade:
```
az aks upgrade -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --kubernetes-version 1.15.7 
```

I will close this issue, let me know if you have any question.
