### ISSUE TITLE
Replace "success/failure" nouns with the actual pod adjective phases (succeeded or failed). 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#87574]
**What would you like to be added**:

The E2E tests evaluate Pod Phases  adjectives, describing the state of a pod, i.e. Succeeded, Failed, and so on.   But, they log nouns (success or failure). 

```
Waiting up to 5m0s for pod "client-can-connect-80-5x9dw" in namespace "network-policy-8096" to be "success or failure"
```

**Why is this needed**:

Right now when reading tests, it takes a tiny leap of faith to correlate "success or failure" with the pod phase "failure", and one wonders wether 'failed' literally means the pod phase is Failed.  Making the condition match the exact semantics of this pod phase makes test logs  consistent from a readability perspective.

**Comment by LucianaMarques** [comment]
Hi there!

I want to help with this issue, I'll come back when I have a PR open :)

Is it ok if you assign this to me? 

Thanks!

**Comment by LucianaMarques** [comment]
@sureshpalemoni I was already working on it, do you want to share any ideas?

**Comment by sureshpalemoni** [comment]
@LucianaMarques I didn't see your comment. Kindly review my PR if it has similar ideas or comment to make any additional changes. Thank you.

**Comment by alejandrox1** [comment]
This looks like something that could go in this release
/milestone v1.18

**Comment by LucianaMarques** [comment]
@sureshpalemoni that's ok, but please be more careful, I was a little bit frustrated :(

**Comment by jayunit100** [comment]
oh   i already did this :) https://github.com/kubernetes/kubernetes/pull/87576

**Comment by markyjackson-taulia** [comment]
@jayunit100 @sureshpalemoni 
Hello, bug-triage here. Just want to make sure we are still staffed and on-track for v1.18 code freeze

**Comment by sureshpalemoni** [comment]
> @jayunit100 @sureshpalemoni
> Hello, bug-triage here. Just want to make sure we are still staffed and on-track for v1.18 code freeze

PR has already been merged. This issue can be closed actually.

**Comment by markyjackson-taulia** [comment]
@jayunit100 gentle ping

![](https://apptimize.com/wp-content/uploads/2015/11/Code-Freeze.png)
