### ISSUE TITLE
Invalid listTypes in FlowSchema cause errors in apiserver logs

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/kubernetes#87594]
In the kind `flowcontrol.apiserver.k8s.io/v1alpha1.FlowSchema`, the fields [`.spec.rules`](https://github.com/kubernetes/kubernetes/blob/ec5321c6a9f23e5ad26cf88a41fda9dba0c5ce89/staging/src/k8s.io/api/flowcontrol/v1alpha1/types.go#L110), [`.spec.rules[].subjects`](https://github.com/kubernetes/kubernetes/blob/ec5321c6a9f23e5ad26cf88a41fda9dba0c5ce89/staging/src/k8s.io/api/flowcontrol/v1alpha1/types.go#L155), [`.spec.rules[].resourceRules`](https://github.com/kubernetes/kubernetes/blob/ec5321c6a9f23e5ad26cf88a41fda9dba0c5ce89/staging/src/k8s.io/api/flowcontrol/v1alpha1/types.go#L161), and [`.spec.rules[].nonResourceRules`](https://github.com/kubernetes/kubernetes/blob/ec5321c6a9f23e5ad26cf88a41fda9dba0c5ce89/staging/src/k8s.io/api/flowcontrol/v1alpha1/types.go#L166) are all tagged with `+listType=set`, but their elements are non-scalar, which is not currently supported. This causes errors messages like:

```
[SHOULD NOT HAPPEN] failed to create typed new object: .spec.rules: element 0: associative list without keys has an element that's a map type
```

to appear in apiserver logs when the feature is enabled, and also prevents server side apply from working with this type. Changing these tags to `+listType=atomic` should fix the issue.

/cc @lavalamp @apelisse

**Comment by lavalamp** [comment]
@MikeSpreitzer @yue9944882 @jktomer for P&F types

@jennybuckley, @apelisse: is it possible to have e.g. an integration test that fails in this condition, to surface it earlier?

Also, this is an alpha feature and thus off by default, are the types still somehow getting registered?

**Comment by liggitt** [comment]
> Also, this is an alpha feature and thus off by default, are the types still somehow getting registered?

based on the description, it sounds like this is only happening when the feature is explicitly enabled

**Comment by apelisse** [comment]
> @jennybuckley, @apelisse: is it possible to have e.g. an integration test that fails in this condition, to surface it earlier?

We probably shouldn't be able to generate the openapi for these types. I think that's where we should detect it. That code can be challenging to update to do exactly this, but we need to look, it might be worth it.

**Comment by MikeSpreitzer** [comment]
Odd, I thought I did some testing and did not get that error message.  I concluded that on the other occasions when I _did_ see that error, it was about some other type.  Would it be possible to make that error message name the type it is complaining about?

**Comment by MikeSpreitzer** [comment]
Also, where are the available choices for listType documented?

**Comment by fedebongio** [comment]
Who would like to be assigned on this one? 
@MikeSpreitzer @lavalamp

**Comment by apelisse** [comment]
We have a lot of things going on for this, some are complete, some are not, this list is not exhaustive:
On-going, feel free to comment: https://github.com/kubernetes/community/pull/4218
Done, but feel free to comment too: https://github.com/kubernetes/kube-openapi/blob/master/pkg/idl/doc.go

**Comment by apelisse** [comment]
> Odd, I thought I did some testing and did not get that error message.

Yeah, this is not easy to "trigger", we'll on work on making this more obvious, that's great feedback.

**Comment by MikeSpreitzer** [comment]
Also, here is another problem with that error message: the phrase "associative list without keys" is awkward to the point of being confusing.  How about something like "set-typed list", "set-structured list", or simply "set"?

**Comment by lavalamp** [comment]
Yeah, "associative" is the old word for map-typed.

**Comment by MikeSpreitzer** [comment]
There is also this pointer that I got from Slack: https://github.com/kubernetes/kube-openapi/blob/master/pkg/idl/doc.go#L21-L63

**Comment by MikeSpreitzer** [comment]
Also, while I am revisiting this, I wonder: should there be a `listType` annotation on the Items field of FlowSchemaList and PriorityLevelConfigurationList?

**Comment by lavalamp** [comment]
The FlowSchemaList and similar types don't matter, since they are not
something a client can write, they're only used for serving read requests.
If we set these annotations on them, they'd be map typed (with namespace
and name the keys). But let's not start doing that now.

**Comment by MikeSpreitzer** [comment]
Also, I see that `listType=granular` is a possibility.  Now I have to figure out which to use where.

For the config object specs: these may well be big long-lived things, edited over time by various admins.  Does that mean I want `granular` rather than `atomic`?

**Comment by lavalamp** [comment]
oh, I remember talking about making that change but I don't remember what was settled on. I thought it was "map"; @apelisse is there a canonical location for this?

**Comment by MikeSpreitzer** [comment]
Oh, sorry, I misread.  `granular` is indeed for maps not lists.

**Comment by apelisse** [comment]
We've settled on `granular` and @mariantalla has been working on fixing all these inconsistencies throughout the docs. This is typically a good starting point indeed: https://github.com/kubernetes/kube-openapi/blob/master/pkg/idl/doc.go

**Comment by MikeSpreitzer** [comment]
@lavalamp: sorry, I do not seem to have the option to omit `listType` for the top-level lists:
```
mspreitz@mjs-dev-1:~/go/src/k8s.io/kubernetes$ make update
+++ [0129 21:45:22] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [0129 21:45:31] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [0129 21:45:38] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [0129 21:45:51] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
259,260d258
< API rule violation: list_type_missing,k8s.io/api/flowcontrol/v1alpha1,FlowSchemaList,Items
< API rule violation: list_type_missing,k8s.io/api/flowcontrol/v1alpha1,PriorityLevelConfigurationList,Items
```

**Comment by lavalamp** [comment]
oh, we need to fix that right away. @apelisse... We should make an exception for the *List types, don't you think?

**Comment by apelisse** [comment]
> We should make an exception for the *List types, don't you think?

That seems like a broad brush. They should definitely be atomic for now.

**Comment by lavalamp** [comment]
I think we should leave it unset on those types, since they're not targets for apply, put, or patch.

Also "granular" is for maps, not lists :)

**Comment by apelisse** [comment]
> I think we should leave it unset on those types, since they're not targets for apply, put, or patch.

Yeah, and it's also fine to add it as an exception for now.

**Comment by lavalamp** [comment]
I filed https://github.com/kubernetes/kube-openapi/issues/185

Until we get this fixed, I guess mark them as atomic to avoid the spurious warning.
