### ISSUE TITLE
e2e tests are order-dependent

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8759]
Maybe we should have two e2e test runs in Jenkins, one that always runs in the same order, and one that runs in a random order.  That way we can differentiate always-regressions (on the same-order test) from probably-regressions (random-order test).

**Comment by quinton-hoole** [comment]
+1

**Comment by quinton-hoole** [comment]
This is pretty trivial to do, and will provide a better signal of regressions.

**Comment by fejta** [comment]
https://onsi.github.io/ginkgo/#spec-permutation `--randomizeSuites` and `--randomizeAllSpecs`

And pass these args into a new suite here: https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L68

**Comment by quinton-hoole** [comment]
cc @lavalamp FYI.  This will probably substantially improve the fidelity of the regression signal.  I'd suggest running the per-PR e2e tests in a predictable sequence, and the submit-queue-blocking tests in a random order.  Make sense?

**Comment by quinton-hoole** [comment]
Tentatively added v1.4 milestone, on the basis of the above.  Feel free to shout if you disagree.

**Comment by lavalamp** [comment]
Sounds like a fine plan.

**Comment by goltermann** [comment]
@fejta @rmmh @spxtr is this in the plan for 1.4?  Or should we punt this bug out to 1.5?

**Comment by spiffxp** [comment]
/close
At this point in time, I suspect we're not going to be implementing this.  Our e2e tests have become stringly typed into `[Slow]` or `[Disruptive]` to separate out the ones that don't play well with others in parallel.  Please /reopen if you'd like to tackle it.
