### ISSUE TITLE
`kubectl diff --server-side` fails

### ISSUE THREAD

**Issue by hatotaka** [kubernetes/kubernetes#87600]
**What happened**:

`kubectl diff --server-side` fails.

```
$ kubectl diff --server-side -f file.yaml
The PatchOptions "" is invalid: fieldManager: Required value: is required for apply patch
```

**What you expected to happen**:

I would expect the PatchOptions to not include FieldManager. 

The following fix will eliminate the problem.

```diff
diff --git a/pkg/cmd/diff/diff.go b/pkg/cmd/diff/diff.go
index ac762a71..08c98896 100644
--- a/pkg/cmd/diff/diff.go
+++ b/pkg/cmd/diff/diff.go
@@ -73,6 +73,7 @@ type DiffOptions struct {
 
 	ServerSideApply bool
 	ForceConflicts  bool
+	FieldManager    string
 
 	OpenAPISchema    openapi.Resources
 	DiscoveryClient  discovery.DiscoveryInterface
@@ -261,6 +262,7 @@ type InfoObject struct {
 	Force           bool
 	ServerSideApply bool
 	ForceConflicts  bool
+	FieldManager    string
 	genericclioptions.IOStreams
 }
 
@@ -282,6 +284,7 @@ func (obj InfoObject) Merged() (runtime.Object, error) {
 		options := metav1.PatchOptions{
 			Force:        &obj.ForceConflicts,
 			DryRun:       []string{metav1.DryRunAll},
+			FieldManager: obj.FieldManager,
 		}
 		return resource.NewHelper(obj.Info.Client, obj.Info.Mapping).Patch(
 			obj.Info.Namespace,
@@ -406,6 +409,7 @@ func (o *DiffOptions) Complete(f cmdutil.Factory, cmd *cobra.Command) error {
 
 	o.ServerSideApply = cmdutil.GetServerSideApplyFlag(cmd)
 	o.ForceConflicts = cmdutil.GetForceConflictsFlag(cmd)
+	o.FieldManager = cmdutil.GetFieldManagerFlag(cmd)
 	if o.ForceConflicts && !o.ServerSideApply {
 		return fmt.Errorf("--force-conflicts only works with --server-side")
 	}
@@ -494,6 +498,7 @@ func (o *DiffOptions) Run() error {
 				Force:           force,
 				ServerSideApply: o.ServerSideApply,
 				ForceConflicts:  o.ForceConflicts,
+				FieldManager:    o.FieldManager,
 				IOStreams:       o.Diff.IOStreams,
 			}

```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16 and 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by julianvmodesto** [comment]
cc @apelisse

**Comment by julianvmodesto** [comment]
cc @kwiesmueller

**Comment by apelisse** [comment]
I agree, we clearly missed that. Would you mind sending the fix in the form of a PR? Also please include a test, because that shouldn't have happened if I had tested my code properly :-(

**Comment by apelisse** [comment]
Clearly we should also cherry-pick that into 1.17. @hatoka, I'll send the PR on Monday if you prefer! Thanks.

**Comment by hatotaka** [comment]
Ok, I will send a PR. However, I can't include a test immediately because I don't understand how the test works.

**Comment by apelisse** [comment]
Thanks, I’ll try to show you how to get started!

**Comment by apelisse** [comment]
Any update @hatotaka, we clearly need this promptly since code-freeze is coming! Thanks.

**Comment by apelisse** [comment]
@hatotaka I'll send a PR on Monday if you haven't! Thanks.

**Comment by hatotaka** [comment]
Sorry, I haven't started working on this test. Thanks.
