### ISSUE TITLE
kubelet 0.17.1 silently ignores malformed auth-path JSON

### ISSUE THREAD

**Issue by farcaller** [kubernetes/kubernetes#8761]
Based on the `/var/lib/kubelet/kubernetes_auth`:
```
{
  "CertFile": "/etc/kubernetes/kubelet.crt",
  "KeyFile": "/etc/kubernetes/kubelet.key"
  "CAFile": "/usr/local/share/ca-certificates/hackndev-root.crt"
}
```

kubelet starts successfully and then fails to authenticate to apiserver as there's no cert and key configured (notice the missing comma in the `KeyFile` line). Failing to parse JSON here should be a hard fail.

**Comment by roberthbailey** [comment]
The auth-path flag to the kubelet is [deprecated](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kubelet/app/server.go#L208-L209) and will likely be removed before we hit the 1.0 release.

**Comment by bgrant0607** [comment]
Obsolete
