### ISSUE TITLE
Update etcd server + client libraries to latest etcd 3.4 release.  

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#87613]
**What would you like to be added**:
From looking at our gomod deps we seem to have drifted out of date again and we should update - https://github.com/etcd-io/etcd/releases/tag/v3.4.3 

**Why is this needed**:
Bug fixes, feature adds, validation.  

/cc @jpbetz @kubernetes/sig-api-machinery-misc @dlipovetsky

**Comment by timothysc** [comment]
Also cc: @wojtek-t @kubernetes/sig-release @dims

**Comment by liggitt** [comment]
we currently use `go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738` which is the same as `v3.4.3`

go does not allow referring to a module using a v2+ semver tag unless the module name ends with `/v<N>`

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/87614 to add an explanatory comment in our go.mod file, which is the best we can do until etcd renames its module to follow semantic import versioning, which requires changing every package import reference

**Comment by timothysc** [comment]
what about github.com/coreos/etcd => github.com/coreos/etcd v3.3.10+incompatible  

+ the other older etcd deps?

**Comment by liggitt** [comment]
not vendored/linked/used (can verify no code from that dependency is even present in [vendor](https://github.com/kubernetes/kubernetes/tree/master/vendor/github.com/coreos)), just in our graph, so included in replace / go.sum directives

```
$ go mod graph | grep github.com/coreos/etcd
github.com/spf13/viper@v1.3.2 github.com/coreos/etcd@v3.3.10+incompatible
github.com/spf13/viper@v1.0.2 github.com/coreos/etcd@v3.3.10+incompatible
```

**Comment by timothysc** [comment]
uhhh that's weird, we need to dump viper for component config, but no one wanted todo that work.
