### ISSUE TITLE
Unexpected scheduling of replacement Pod upon Pod deletion

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#87621]
## Background

As you may have known, internally, the Kubernetes scheduler handles "unassignedPod" (nil `.spec.nodeName`) and "assignedPod" (non-nil `.spec.nodeName`) simultaneously.

- one to be handled in the internal cache:
    https://github.com/kubernetes/kubernetes/blob/15c3f1b119ff4b4073c86df05c819a9672b80d68/pkg/scheduler/eventhandlers.go#L348-L349

- while the other to be dealt with in internal queue(s):
    https://github.com/kubernetes/kubernetes/blob/15c3f1b119ff4b4073c86df05c819a9672b80d68/pkg/scheduler/eventhandlers.go#L373-L374

It works most of the time except for the case that **the scheduling decision of added Pod strictly depends on a previously deleted Pod**. For example, if you delete a Pod from a Deployment, (1) the Pod will be deleted, and then (2) a backfilling Pod will be created. Looking at the timeline, (1) happens prior to (2), however, in scheduler, (2) may be processed when (1) is still happening. In that case, the decision for the backing Pod is based on the presence of the terminating Pod, which is not the desired result.

Using pod topology spread constraints or pod anti-affinity can easily reproduce this scenario. #86037 is one DP.

## Is it an Issue?

Before jumping to possible solutions, we should brainstorm to conclude whether it's an issue or not.

- We should firstly verify, in the client-go/API's perspective, whether the informers will **_always_** get the new Pod event **after** the deleted Pod event. If it's uncertain, we don't need to continue the discussion.
- In the scheduler's point of view, can we simply say: it's not an issue as we handle Pod events individually, instead of handling one event to waiting for a preceding event to be finished. (no need to say, it's hard to figure out the implicit Pod dependency)
- From the user's perspective, it's an issue as the scheduling decision for the replacement Pod doesn't make sense.

## Workaround

As mentioned in https://github.com/kubernetes/kubernetes/issues/86037#issuecomment-563095248, we can use `kubectl delete pod <pod name> --force=true --grace-period=0` to alleviate the issue.

## Possible Solutions

(This part will be updated now and then...)

- Hold the scheduling cycle (using proper lock) if a dependent terminated Pod is being processed in the caching goroutine.
- Using a workqueue to enqueue both assignedPod and unassignedPod, then process each item to in either caching or schedulingQ. But this may slow down the throughput.

/sig scheduling
/priority important-longterm
/assign

**Comment by Huang-Wei** [comment]
/cc @ahg-g @alculquicondor 

FYI @eranreshef

**Comment by alculquicondor** [comment]
My thinking is that this not about a "Delete" event arriving after the "Add" event for the pods.
This is about the scheduler not accounting for "terminating" pods.

For example, if I delete a pod and this takes a while, the pod spec will have `.metadata.deletionTimestamp` set and `.status.Phase = "Running"`. And deployments react to terminating pods, rather that *terminated*

For example, if I set a deployment with 1 replica and delete the pod, I get this:

```
$kubectl get pods
NAME                              READY   STATUS        RESTARTS   AGE
foo-deployment-6dc95ddcf6-2sqmm   1/1     Running       0          2s
foo-deployment-6dc95ddcf6-hmcs8   1/1     Terminating   0          22s
```

If this is the case, I would say kube-scheduler taking the right decision. Those resources are not free yet.
But we should clarify the expectations with sig-apps

/sig apps

**Comment by Huang-Wei** [comment]
@alculquicondor It's true that at the same point, there are 2 Pods existing - one Running and one Terminating. So when it comes to scheduler, should we schedule the new one excluding the terminating one or not? This is the point of this issue.

BTW: the context we should discuss is the Pods belong to the same controllerRef.

**Comment by alculquicondor** [comment]
I think there are points that can be made for excluding or counting terminating pods. Then the decision might come to each (filter) plugin to decide what's best for them.

But even then, I think there might always be some use case that goes against our decision. At least in #86037, I would say the user should use pod antiaffinity to enforce the distribution they want.

My stance then is to keep current behavior and enhance our documentation to clarify expectations.

**Comment by ahg-g** [comment]
I agree with https://github.com/kubernetes/kubernetes/issues/86037#issuecomment-563096452, I think excluding terminating pods for pod spread (and perhaps affinity) makes sense, and it should be done inside the filter. A terminating pod will eventually be deleted, and so the system will be back to a good state eventually. 

I don't agree with solutions that block the scheduling of a pod to force specific order of events.

**Comment by haosdent** [comment]
> Hold the scheduling cycle (using proper lock) if a dependent terminated Pod is being processed in the caching goroutine.

We could continue to process other pods if it doesn't have dependencies? And for the pod has hard depdencies, we just check if the requirements match, if not match, we skip it and would check at next scheduling cycle?

**Comment by skilxn-go** [comment]
I think it seems to be a tradeoff between consistency and availability. And it's different for pod spread and pod affinity.
- For pod anti-affinity, I think we may not exclude terminating pods, it may cause some consistency problems as we don't know the status of the terminating process.
- For pod spread and pod affinity, I think it's ok to exclude terminating pods, which guarantee us an eventually consistency

**Comment by Huang-Wei** [comment]
I did some further debugging, and found that the "delete" event we were talking about comes everytime before the "add" event. But one thing worth noting is that the "delete" event is more an "update" event which sets the Pod's `.spec.deletionTimestamp` to a non-nil value.

For example, I have a Deployment with 2 Pods running, using topology spread containts to ensure they're running in 2 nodes:

```
root@wei-dev:~/manifests# k get po -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP                NODE    NOMINATED NODE   READINESS GATES
pause-f5dcb658d-sfd4s   1/1     Running   0          12s   192.168.192.168   node2   <none>           <none>
pause-f5dcb658d-vw89z   1/1     Running   0          12s   192.168.192.168   node1   <none>           <none>
```

And if I taint node2, and delete the pod on node2, it shows the replacement Pod gets scheduled onto node1, which as unexpected as #86037 reported:

```
root@wei-dev:~/manifests# k taint node node2 foo=bar:NoSchedule
node/node2 tainted
root@wei-dev:~/manifests# k delete po pause-f5dcb658d-sfd4s
pod "pause-f5dcb658d-sfd4s" deleted
root@wei-dev:~/manifests# k get po -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP                NODE    NOMINATED NODE   READINESS GATES
pause-f5dcb658d-6n2mz   1/1     Running   0          9s    192.168.192.168   node1   <none>           <none>
pause-f5dcb658d-vw89z   1/1     Running   0          36s   192.168.192.168   node1   <none>           <none>
```

In the debugging log, it shows the "update" event comes before "add" event, and then the _real_ "delete" event comes:

- Line 01~03 indicates the old pod is being deleted as its `DeletionTimestamp` gets set
- Line 07 shows the replacement pod gets added to schedulingQ
- Line 08~09 shows the replacement pods get popped, and it takes a snapshot on the cache at that very moment
- Line 11 shows until 2 seconds after the "add" event, the "delete" event comes, which indicates the old pod has deleted physically (from etcd)

```
01 I0128 20:26:49.275170   19841 eventhandlers.go:244] [DEBUG] updatePodInCache(): pause-f5dcb658d-sfd4s -> pause-f5dcb658d-sfd4s
02 I0128 20:26:49.275213   19841 eventhandlers.go:245] [DEBUG] updatePodInCache(): oldPod.DeletionTimestamp = <nil>
03 I0128 20:26:49.275253   19841 eventhandlers.go:246] [DEBUG] updatePodInCache(): newPod.DeletionTimestamp = 2020-01-28 20:27:19 -0800 PST
04 I0128 20:26:49.275276   19841 cache.go:514] [DEBUG] cache.UpdatePod(): pause-f5dcb658d-sfd4s
05 I0128 20:26:49.275287   19841 cache.go:434] [DEBUG] cache.updatePod starts
06 I0128 20:26:49.275305   19841 cache.go:439] [DEBUG] cache.updatePod completed
07 I0128 20:26:49.282965   19841 eventhandlers.go:172] [DEBUG] addPodToSchedulingQueue(): pause-f5dcb658d-6n2mz
08 I0128 20:26:49.283128   19841 cache.go:207] [DEBUG] snapshoting starts
09 I0128 20:26:49.283152   19841 cache.go:278] [DEBUG] snapshoting ends
10 I0128 20:26:49.301605   19841 eventhandlers.go:205] [DEBUG] deletePodFromSchedulingQueue(): pause-f5dcb658d-6n2mz
......
11 I0128 20:26:51.261373   19841 eventhandlers.go:276] [DEBUG] deletePodFromCache(): pause-f5dcb658d-sfd4s
```

So, why the replacement Pod gets scheduled to node1 (instead of pending) is because in:

https://github.com/kubernetes/kubernetes/blob/1590c7b31cb40259397ccef602b6d6dc2a9f9d72/pkg/scheduler/internal/cache/cache.go#L430-L436

It removes the old pod, and readd the old pod (with non-nil deletionTimestamp) again! So when new pod tries to schedule, the snapshot still includes the old pod.

**Comment by skilxn-go** [comment]
yes, after the pod terminated, it will be actually deleted by kubelet, in my memory.

**Comment by Huang-Wei** [comment]
@haosdent it seems I complicated the case - the "update" event happens ahead to "add" event everytime.

@ahg-g @alculquicondor @skilxn-go Can we verify the "update" case at:

https://github.com/kubernetes/kubernetes/blob/1590c7b31cb40259397ccef602b6d6dc2a9f9d72/pkg/scheduler/internal/cache/cache.go#L430-L436

to check if newPod has non-nil deletionTimestamp, if yes, remove it from cache rather than adding back.

In this case, we make it generic and don't bother with each filter plugin implementation as I don't see much value of keeping a terminating Pod in our cache. In other words, the cache.updatePod() is buggy in my eyes.
WDYT?

**Comment by skilxn-go** [comment]
In most cases, I think this works well. But just for pod anti-affinity, I think users who use it will expect a more strong consistency when scheduling pods.
We can't make sure if a pod has terminated before the delete event received.

**Comment by skilxn-go** [comment]
But as @ahg-g said:
> A terminating pod will eventually be deleted, and so the system will be back to a good state eventually.

So, I'm not sure if eventual consistency is acceptable for pod anti-affinity.

**Comment by skilxn-go** [comment]
I think there may be a case like this:
Say there is a deployment:
1. Pods in the deployment use host-path volume.
2. A user wants to keep on host-path can only be used by one pod, so he uses pod anti-affinity to achieve this.
3. The pod's terminating behavior is clean up the host-path.
4. Once a pod is stuck at terminating (for any reason). We may schedule a new pod to this node as we exclude the terminating one.
5. The new pod start running, and write something to the host-path.
6. The previous pod successfully terminated, and clean up what the new pod has written.
7. Finally, things messed up.

**Comment by skilxn-go** [comment]
There may be some same cases when we use pod spread. (use the hostname as topo-key,  and maxskew = 1)

**Comment by alculquicondor** [comment]
> In this case, we make it generic and don't bother with each filter plugin implementation as I don't see much value of keeping a terminating Pod in our cache. In other words, the cache.updatePod() is buggy in my eyes.

I disagree in general terms. We don't know how long deletion is going to take and there could be several pods terminating at the same time. While it might be beneficial for pod spreading filter to not consider terminating pods, for filters that involve resource usage, it's incorrect to not consider them. They are still using resources and, again, we don't know for how much longer.

For simplicity, I would prefer to keep the current behavior. The use case https://github.com/kubernetes/kubernetes/issues/87621#issuecomment-579613755 can be solved with pod antiaffinity or simply using a daemonset. In other words, I think spreading shouldn't be used to ensure uniqueness. However, I'm not entirely against disregarding terminating pods, but this should be done per-plugin.

**Comment by skilxn-go** [comment]
Agreed with @alculquicondor , the resource limit is another important issue.

**Comment by ahg-g** [comment]
> In this case, we make it generic and don't bother with each filter plugin implementation as I don't see much value of keeping a terminating Pod in our cache. In other words, the cache.updatePod() is buggy in my eyes.

Agreed with the previous two comments, we can't make a blanket decision to exclude terminating pods because resources assigned to those pods may have not be reclaimed yet. I think it makes sense to exclude them for spreading.

**Comment by Huang-Wei** [comment]
Thanks for the brainstorming. The points are fair to me. We should exclude the terminating Pods, when necessary, on a plugin basis.

I'd make pod topology spread as a pilot if nobody objects.

**Comment by ahg-g** [comment]
Sounds good, I think we should just do it for spreading since it is not GA yet. Changing the semantics for affinity may come as a surprise to some.

**Comment by Huang-Wei** [comment]
> Sounds good, I think we should just do it for spreading since it is not GA yet. Changing the semantics for affinity may come as a surprise to some.

SGTM.

/close 
this issue as we have got a conclusion. I will send a PR addressing  #86037.

**Comment by kerthcet** [comment]
> I think there may be a case like this: Say there is a deployment:
> 
> 1. Pods in the deployment use host-path volume.
> 2. A user wants to guarantee that one host-path in a node can only be used by one pod, so he uses pod anti-affinity to achieve this.
> 3. The pod's terminating behavior is cleaning up the host-path.
> 4. Once a pod is stuck at terminating (for any reason). We may schedule a new pod to this node as we exclude the terminating one.
> 5. The new pod start running, and write something to the host-path.
> 6. The previous pod successfully terminated, and clean up what the new pod has written.
> 7. Finally, things messed up.

Revisit the discussion, I'm not completely convinced by this case. `guarantee that one host-path in a node can only be used by one pod` this should be guaranteed by a pod-node constraint, like https://github.com/kubernetes/kubernetes/issues/105287. Pod anti-affinity used to express the relationships between different pods, So I think `interPodAffinity` should also exclude terminating pods.

**Comment by alculquicondor** [comment]
If anything, it needs to be a new API field that decides whether or not to include terminating pods. Another alternative would be something similar to https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades

**Comment by kerthcet** [comment]
> If anything, it needs to be a new API field that decides whether or not to include terminating pods. Another alternative would be something similar to https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades

If we introduce a new api field, it will mostly like a feature than. But I treat it as a bug fix, need more advices.

**Comment by alculquicondor** [comment]
It can't be treated as a bugfix, because the semantics are well defined: we evaluate the (anti)affinity while the pod is still running, even if terminating.

**Comment by kerthcet** [comment]
> It can't be treated as a bugfix, because the semantics are well defined: we evaluate the (anti)affinity while the pod is still running, even if terminating.

Then maybe it worths a KEP, let's make it a configuration for end users.

**Comment by ahg-g** [comment]
But is there a need for that now? did we get a request for it?

**Comment by kerthcet** [comment]
> But is there a need for that now? did we get a request for it?

Here's a recent issue related https://github.com/kubernetes/kubernetes/issues/111793, I think it make the users confusing.
