### ISSUE TITLE
v1.17 Can you customize the version information?

### ISSUE THREAD

**Issue by yxzking** [kubernetes/kubernetes#87649]
I have a k8s cluster. I want to add some custom names after this VERSION. What do I need to do?

```
[root@yxzking-91101 ~]# kubectl get nodes -o wide
NAME            STATUS   ROLES    AGE   VERSION                      INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNE
192.168.0.172   Ready    <none>   14m   v1.13.10   192.168.0.172   <none>        CentOS Linux 7 (Core)   3.10
```
For example **VERSION** display:
v1.13.10-aliyuncloud

**Comment by liggitt** [comment]
the version can be customized at build time by passing ldflags to the go build to customize the values of the k8s.io/component-base/version and k8s.io/client-go/pkg/version variables

see https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L147-L182 for the way these are populated in OSS kubernetes builds

/close

**Comment by yxzking** [comment]
@liggitt Thanks i succeeded！
