### ISSUE TITLE
Rename "taint" to something less vulgar

### ISSUE THREAD

**Issue by enragedginger** [kubernetes/kubernetes#87655]
**What would you like to be added**:
Rename "taint" to something less vulgar.

**Why is this needed**:
In common English, a taint is an area in the nether regions of the human body. This makes discussing Kubernetes "taints" very difficult in a professional or public setting, especially if anyone who doesn't already know of Kubernetes "taints" is present.

We should rename "taint" to be either "perineum", the official name for the taint, or something more fitting like "restriction" or "stigma."

**Comment by neolit123** [comment]
it might be too late for this one, without breaking thousands of users.

/sig architecture node

**Comment by enragedginger** [comment]
I don't agree with that rationale. I think we can all agree that we should avoid using vulgarities in our code, documentation, and general professional communication. Regardless of whether or not the word was once accepted in computation, it is now a common vulgarity. Therefore, we should move away from it. Doing so will only increase the appeal of Kubernetes by making it appear more mature and forward thinking.

**Comment by smarterclayton** [comment]
Thanks for the feedback.  Since these issues historically attract a lot of unhelpful arguments and attacks in the threads, I'm going to lock this issue for now and when we add this to sig-architecture agenda I'll update with details for discussion there.

**Comment by smarterclayton** [comment]
I'll bring this up at the sig-arch meeting today, however as neolit noted 

* our API guarantees prevent these sorts of renames on short time scales (we might introduce a new name, but the old name would be preserved effectively for the rest of the v1 lifetime)
* the term is well established in both having common descriptive usage (outside of the less-common vulgar usage)

so I think it's unlikely we would change this.  Will update after the meeting.

**Comment by timothysc** [comment]
I'm opposed to the change at this stage due to the overall impact it would have, there is plenty of history and literature that does not pertain to the urban-dictionary definition.

**Comment by liggitt** [comment]
Agreed. A rename at this point is not practical due to API compatibility guarantees, and the term as used corresponds to the legitimate and inoffensive definition of the word.

**Comment by timothysc** [comment]
We discussed this issue on the SIG-arch call of 20200130, and have unanimously agreed that we will keep the current naming for the aforementioned reasons.
