### ISSUE TITLE
kubectl port-forward does not close the local connection when the server closes the connection

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#8766]
I am trying out `kubectl port-forward` and I think it does not close the client-side connection properly when the server closes the connection.

I realize this example is probably deeply unhelpful unless you have a zookeeper image lying around, but here's what I observed...

When I ssh in to the minion and target the pod IP, I send the "status" message (ruok) and the server sends the reply (imok) and closes the connection.

```
justinsb@kubernetes-minion-nyy1:~$ echo ruok | nc 10.244.1.5 2181
imok
justinsb@kubernetes-minion-nyy1:~$
```

But when I try to do this on the client:

```
 kubectl port-forward -p zookeeper-rplo3 2181 
```
and then

```
echo ruok | nc 127.0.0.1 2181
imok
<hangs>
```

I hope to publish this zookeeper image early this week, if you can't find another test-image where the server closes the connection.

**Comment by smarterclayton** [comment]
@ncdc

**Comment by ncdc** [comment]
We haven't had issues using curl with port-forward to retrieve web pages from e.g. nginx. Is there something different about how Zookeeper and/or nc handle closing connections?

**Comment by ncdc** [comment]
Ok, I've been able to reproduce. I'm working on a fix now.

**Comment by ncdc** [comment]
@liggitt
