### ISSUE TITLE
Fix non-ascii characters which are written accidentally

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes/kubernetes#87679]
**What happened**:
There are some files which contain non-ascii charactor accidentally.

**What you expected to happen**:
Fix non-ascii characters written by mistake(it means, we don't get rid of non-ascii characters which are written intentionally).

**How to reproduce it (as minimally and precisely as possible)**:
ex)a file which contains non-ascii characters
```
$ file test/e2e/common/runtime.go
test/e2e/common/runtime.go: UTF-8 Unicode text, with very long lines
```
ex)a file which **DOESN'T** contain non-ascii characters
```
$ file test/e2e/common/docker_containers.go
test/e2e/common/docker_containers.go: ASCII text
```

**Anything else we need to know?**:
We can fix file code to ascii by below;
```
$ iconv -c -f UTF-8 -t ASCII test/e2e/common/runtime.go > testfile.go
$ diff test/e2e/common/runtime.go testfile.go
```
then modify diffs of `test/e2e/common/runtime.go` .

**Comment by liggitt** [comment]
thanks for the PR, we can just track the change there... no need for a separate issue

/close
