### ISSUE TITLE
'cannot convert int64 to float64' with runtime.DefaultUnstructuredConverter.FromUnstructured on CustomResourceDefinitions with integer minimum, maximum, and/or multipleOf values

### ISSUE THREAD

**Issue by nrb** [kubernetes/kubernetes#87675]
**What happened**:

When converting JSON representations of v1beta1 CustomResourceDefintions with `Spec.Validation.OpenAPIV3Schema.Properties.(Minimum|Maximum|multipleOf)` fields set to a whole number, the `runtime.DefaultUnstructuredConverter.FromUnstructured` function returns 'cannot convert int64 to float64'.

Making the field decimal numbers converts as expected.

**What you expected to happen**:
OpenAPI schema should convert from unstructured.Unstructured whether whole or decimal representation.

**How to reproduce it (as minimally and precisely as possible)**:

A Go test with a minimal CRD & failing test is at https://github.com/nrb/unstructured-conversion-bug/blob/master/main_test.go. The repo includes a go.sum with pinned versions of dependencies. Use `go test` to run it and get a failure.

**Anything else we need to know?**:
This was identified by someone reviewing a [Velero pull request](https://github.com/vmware-tanzu/velero/pull/1937#pullrequestreview-344047216) that waited on CRDs to be 'ready' before restoring CRDs from their serialized JSON representations. The reproduced case is based on his sample CRD.

There's also a Helm 2 issue referencing this, with an included fix. https://github.com/helm/helm/issues/5806.

I believe https://github.com/kubernetes/kubernetes/issues/77665 may be related, but I'm not 100% sure.

**Environment**:
- Kubernetes version (use `kubectl version`): apimachinery 0.17.2

**Comment by liggitt** [comment]
I don't think number type conversion is intended to be performed by that helper. It's primary purpose is to round-trip between a typed and unstructured object without requiring json serialization/deserialization. 

If you have JSON you want to unmarshal, you can do so directly into the CRD go type without first unmarshaling into an Unstructured object.

**Comment by nrb** [comment]
@liggitt Apologies for the delayed response.

In [the original problem](https://github.com/vmware-tanzu/velero/pull/1937#pullrequestreview-344047216) this was actually with information returned by the Kubernetes API server, which I then tried to change into the CRD Go type. The original goal was for Velero (a backup/restore tool) to check a CRD in the cluster for readiness before restoring any CRs. In Velero's case, because we deal with more or less any object that could be in the API server, we're using a Dynamic client as we can't import every possible Go type, though well-known ones like CRDs are different.

The example I have is the simplest possible reproduction case I could come up with, without involving a full Kubernetes API server.

Given we're constrained to using Unstructured types from the Kubernetes API server, is there an alternative method we could use for translating them into the CRD Go types?

**Comment by liggitt** [comment]
> Given we're constrained to using Unstructured types from the Kubernetes API server, is there an alternative method we could use for translating them into the CRD Go types?

I'm not sure I understand. If you're working with go types, you can unmarshal into the typed structs, correct?

**Comment by nrb** [comment]
Not always, because in some instances, we hit this error.  We got another report of this today (https://github.com/vmware-tanzu/velero/issues/2319), which I traced back to my code at https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/remap_crd_version_action.go#L65, the `runtime.DefaultUnstructuredConverter.FromUnstructured` call to take the Unstructured data to the Go type.

**Comment by nrb** [comment]
/remove-lifecycle-stale

This is still affecting Velero, though we've worked around it by not using `FromUnstructured` on CRDs returned directly from the Kube API server as Unstructured via a dynamic client. We instead marshal to JSON and back for now.

I  think I may have not explained my case clearly - is there anything I can do or provide to help resolve this?

**Comment by liggitt** [comment]
apologies for the delay, I dug into this and opened https://github.com/kubernetes/kubernetes/pull/93250 as a fix

**Comment by nrb** [comment]
@liggitt Thanks a ton!
