### ISSUE TITLE
FlowSchemaStatus is ambiguous

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#87684]
**What happened**:
Thinking about how I might utilize the "dangling" condition in testing, I noticed a lack of synchronization.  Clients can update the Spec of a FlowSchema at any time --- even after conditions have been set in the Status.  A client has no way to know whether a given condition in the Status was derived from current Spec or a previous Spec.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `master`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@lavalamp 
@yue9944882 
@jktomer 
@deads2k 
@mars1024

**Comment by lavalamp** [comment]
The condition type probably universally needs an "ObservedGeneration". Our case may also need a field for "Observer" since there'll be multiple apiservers independently making judgments.

I think this can be addressed for beta, GA, or later--it's OK to suffer in the meantime.

**Comment by jktomer** [comment]
Note that the dangling status can be out-of-date in two ways: either the flow schema's spec or the priority level it references can have changed between the last time the condition was updated and when the reader sees it. I'm not sure if we have a standard way to deal with this kind of cross-object consistency issue in k8s, or if people are just accustomed to dealing with such artifacts of eventual consistency.

**Comment by MikeSpreitzer** [comment]
There certainly is not a way to provide general multi-object consistency, because the available ACID transactions are so limited.  There are more complicated and specific things that can be done, such as https://www.ibm.com/cloud/blog/new-builders/preserve-kubernetes-api-objects-while-they-are-in-use .  But the original observation here is that we do not even have some obvious intra-object consistency.  IMO we should at least do that.

**Comment by yue9944882** [comment]
we're already bumping the `.metadata.generation` on every spec update, it's low-hanging-fruit to add `observedGeneration` to the FS/PL's status. it can be a follow-up of #87413.

https://github.com/kubernetes/kubernetes/blob/1bb68a2cde08e39875f8e4f53bf429e14438835e/pkg/registry/flowcontrol/flowschema/strategy.go#L58-L60
