### ISSUE TITLE
API Docs for corev1.LimitRangeItem show type as +optional and omitempty

### ISSUE THREAD

**Issue by whiskeyjimbo** [kubernetes/kubernetes#87683]
**What happened**:
updating controller and using API docs shows corev1.LimitRangeItem as not requiring `Type`, this is not the case.

**What you expected to happen**:
API Docs should show that Type is required

**How to reproduce it (as minimally and precisely as possible)**:
Per API Docs https://github.com/kubernetes/kubernetes/blob/ae95a4bfcac12bf6b19e2d5acf6404359b1a8c3b/staging/src/k8s.io/api/core/v1/types.go#L5211 Type is optional and omitempty
this should work...
```
	return &corev1.LimitRange{
		ObjectMeta: metadata,
		Spec: corev1.LimitRangeSpec{
			Limits: []corev1.LimitRangeItem{
				{
					Max: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("4")},
					Default: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("2.5")},
					DefaultRequest: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("1")},
				},
			},
		},
	}
```

This is the required format with Type:
```
	return &corev1.LimitRange{
		ObjectMeta: metadata,
		Spec: corev1.LimitRangeSpec{
			Limits: []corev1.LimitRangeItem{
				{
                                        Type: "Container",
					Max: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("2.5")},
					Default: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("2.5")},
					DefaultRequest: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("2.5")},
				},
			},
		},
	}
```

**Anything else we need to know?**:
Nope.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.9
- Cloud provider or hardware configuration: aws EKS
- Others:

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.14.9

1.14 is out of support. does the same happen with 1.15+?
1.15 will come out of support too with the release of 1.18 in late March.

/sig node
/kind documentation

**Comment by bismitaguha** [comment]
@neolit123 The documentation can be changed and `omitempty` variable should be removed from the `Type` field.
Can I work on this issue?

**Comment by neolit123** [comment]
@bismitaguha 
giving this is suggesting a change in a core v1 API you should ideally ask in the #api-review or #sig-api-machinery channels on slack, before sending the PR.

**Comment by munnerz** [comment]
Looking through the codebase, I cannot see any place where the `Type` field is defaulted, and the LimitRange admission plugin seems to gate on this field being set to one of the recognised values.

Digging back through `git blame`, it appears that this field did *NOT* originally have `// +optional` as the object was first introduced pre-1.0 when we didn't have OpenAPI schema tags in the same way.

This PR added the `// +optional` tag as the field had `omitempty` set: https://github.com/kubernetes/kubernetes/pull/34860

This change added the `omitempty` tag, and looking through the corresponding PR (https://github.com/kubernetes/kubernetes/pull/3751) I don't see any justification for adding `omitempty` nor any discussion around it. Given this was in the pre-1.0 days, I suspect it may have been a bit of a cargo-cult given there were not clear guidelines around usage of `omitempty`, although I may be wrong. @derekwaynecarr may have some additional insight as you originally wrote this, albeit a *very very very* long time ago!

I see as well that prior to the PR merging, this field was named `Kind` and *didn't* have the omitempty tag (although *did* have a variety of others): https://github.com/derekwaynecarr/kubernetes/blame/31a1145abdc4f8672cd1ffc6ada9ebb47acdc62b/pkg/api/types.go#L1145

---

So I'd *guess* that the field is essentially required and it being marked optional was an accident.

All that said... if we switch this field from optional to required now, it does represent a net-breaking behavioural change in the apiserver. Previously if a user submitted a LimitRange without a `type` field set, the apiserver would accept that LimitRange but not enforce it/provide any information to the user.

After #88029, the apiserver will begin rejecting the request. This _is_ more intuitive behaviour, but I'm conscious that there tends to be a commitment towards not breaking this sort of thing... I would defer to @deads2k or @liggitt to weigh in on whether it's acceptable to introduce a breaking change 😄

**Comment by bismitaguha** [comment]
@munnerz Since this is a change in the `core`, also aligning to what the docs say I removed the `omitempty` behaviour, but if the requirement is of not enforcing any information on the user, I would push a commit to modify it.
It's my first contribution, so I would like to have your suggestions on the PR.

**Comment by liggitt** [comment]
> After #88029, the apiserver will begin rejecting the request.

The API server already rejects requests with empty Type fields:

```sh
echo 'apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
spec:
  limits:
  - max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 200m
      memory: 6Mi
  - default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 3Mi' | kubectl create -f -

The LimitRange "mylimits" is invalid: 
* spec.limits[0].type: Invalid value: "": name part must be non-empty
* spec.limits[0].type: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
* spec.limits[1].type: Invalid value: "": name part must be non-empty
* spec.limits[1].type: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
* spec.limits[1].type: Duplicate value: ""
```

Since the field is actually required (and is not defaulted), it should not be marked omitempty or optional.

**Comment by munnerz** [comment]
> The API server already rejects requests with empty Type fields:

Digging back into the validation package I can see that now 👀 not sure how I missed it in the first place!
