### ISSUE TITLE
some scheduler metrics(pending_pods, schedule_attempts_total) was not recorded.

### ISSUE THREAD

**Issue by everpeace** [kubernetes/kubernetes#87690]
**What happened**:

two scheduler metrics, `pending_pods` and `schedule_attempts_total`, was not recorded in `v1.17.0`.

scheduler has some code for this already.  It seems to be a bug.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L58-L63
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L149-L155

**What you expected to happen**:

`pending_pods` and `schedule_attempts_total` was recorded

**How to reproduce it (as minimally and precisely as possible)**:

```shell
#
# Create the cluster locally
#
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
...
kubectl cluster-info --context kind-kind

#
# Create a pod being scheduled
#
$ kubectl run --restart=Never --image=busybox test echo hello
pod/test created

$ kubectl get pod
NAME   READY   STATUS      RESTARTS   AGE
test   0/1     Completed   0          15s

# portforward to scheduler
$ kubectl -n kube-system port-forward kube-scheduler-kind-control-plane 10251:10251
Forwarding from 127.0.0.1:10251 -> 10251
Forwarding from [::1]:10251 -> 10251

#
# In another terminal
#

# Confirm some scheduler metrics was recorded
$ curl -s http://localhost:10251/metrics
...
# HELP scheduler_binding_duration_seconds [ALPHA] Binding latency in seconds
# TYPE scheduler_binding_duration_seconds histogram
scheduler_binding_duration_seconds_bucket{le="0.001"} 0
...

# BUT, `pending_pods` and `schedule_attempts_total` was not recorded....
$ curl http://localhost:10251/metrics | grep pending_pods
______NO_OUTPUT!!__SOME_METRICS_SHOULD_BE_HERE_______
$ curl http://localhost:10251/metrics | grep schedule_attempts_total
______NO_OUTPUT!!__SOME_METRICS_SHOULD_BE_HERE_______
```

---
/king bug
/sig scheduling

**Comment by skilxn-go** [comment]
Pending pods sounds good. And what do you expect for `schedule_attempts_total`?

**Comment by everpeace** [comment]
@skilxn-go actually, scheduler has some codes already for recording these metrics.  

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L58-L63
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L273-L286

But I found a bug in these code.  I will post my PR to fix this issue soon.
