### ISSUE TITLE
Unit test that plugin args are being set correctly from policy

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87703]
/kind cleanup
/sig scheduling

Tests in `pkg/scheduler/factory_test.go` only check that no errors are produced. But we are not testing that the produced plugin config is correct.

/help-wanted
/good-first-issue

**Comment by alculquicondor** [comment]
The tests should look more like this:

```
	wantConfig := []schedulerapi.PluginConfig{
		{
			Name: noderesources.FitName,
			Args: runtime.Unknown{Raw: []byte(`null`)},
		},
		{
			Name: interpodaffinity.Name,
			Args: runtime.Unknown{Raw: []byte(`{"hardPodAffinityWeight":1}`)},
		},
	}
	if diff := cmp.Diff(wantConfig, factory.pluginConfig); diff != "" {
		t.Errorf("wrong plugin config (-want, +got): %s", diff)
	}
```

And perhaps validate that raw args decode correctly to the specific Arg type of each plugin.

**Comment by alculquicondor** [comment]
Hello @haosdent, are you on track with this?

**Comment by haosdent** [comment]
Hi, @alculquicondor I saw @pancernik assign to him before, so I remove help. If he didn't work in this, I would like to help to fix this issue.

**Comment by haosdent** [comment]
Looks he didn't work in this. Let me create pull request. @alculquicondor

**Comment by alculquicondor** [comment]
Sorry I got messed up with the previous messages. Could you guys coordinate so that the one who already has made progress takes it?

**Comment by alculquicondor** [comment]
You might want to wait for the 2nd part of #88027 to be solved first

**Comment by alculquicondor** [comment]
#88027 is done

**Comment by alculquicondor** [comment]
@fengzixu can you still work on this?

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/kubernetes/blob/dbbf868014039cfdf1e5e98a8efa532141a9fcc5/pkg/scheduler/factory_test.go#L176

**Comment by fengzixu** [comment]
Ok. It seems like the #88027 was finished. Let me do it

**Comment by alculquicondor** [comment]
Actually, it might be possible to override the plugin registry and capture there. Although, we might need a new interface.

Something similar to what I'm doing in #90657 in `framework_test.go`

**Comment by alculquicondor** [comment]
Not entirely sure how to expose the registry, but it's worth giving it a thought.

**Comment by alculquicondor** [comment]
Could you look into using https://github.com/kubernetes/kubernetes/blob/dc98ed96f65a795749ad62fa79373bec5899e303/pkg/scheduler/scheduler.go#L159 ?

There are some existing tests that use it.
