### ISSUE TITLE
Hyperkube: cAdvisor is unsupported in this build

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#8772]
Whenever I launch `kubelet` using Hyperkube (using the `gcr.io/google_containers/hyperkube:v0.17.0` container), I get the following repeated log statement:

```
kubelet.go:643] failed to record system OOMs - cAdvisor is unsupported in this build
```

Seems cAdvisor is not (yet) bundled in this Docker image?

**Comment by vishh** [comment]
The log messages have been suppressed on HEAD. v0.18.x will contain the fix.

**Comment by JeanMertz** [comment]
:+1: thank you for the response.

I assume the fix is not yet available in a PR somewhere (so I can optionally backport it to our current build)?

**Comment by vishh** [comment]
#8430.

**Comment by JeanMertz** [comment]
@vishh my understanding of your earlier reply was that there was a PR to silence the logging (which I've seen before), but that a fix will be built for a future `v0.18.x` release.

It was the fix (ie. getting cAdvisor to work inside the Docker container) I was referring to, when asking if such a fix was already built somewhere.

**Comment by vishh** [comment]
@JeanMertz: It looks like hyperkube is being statically compiled, which is the reason for this issue. I will dig a bit deeper and get back to you.

**Comment by nkwangleiGIT** [comment]
I met with the same issue here, seems hyperkube don't have cAdvisor embedded now.
Do you have any workaround? so we can update some k8s build script to make it work, thanks!

**Comment by nickethier** [comment]
Ran into this as well. It also affects the ability to run heapster with k8s source.

**Comment by vishh** [comment]
I believe this issue can be avoided by not statically linking hyperkube binaries. This can be done by removing [this line](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/golang.sh#L96).
@nkwangleiGIT: Let me know if that works.

**Comment by nkwangleiGIT** [comment]
Hi vishh, it really works, thanks a lot for your help!

**Comment by nlamirault** [comment]
Same error using the  ``gcr.io/google_containers/hyperkube:v0.18.2`` and  ``gcr.io/google_containers/hyperkube:v0.19.3`` container

**Comment by dalanlan** [comment]
I am sorry but still meet the same pb with v1.0.0 rc2. @vishh 
Do u mean [this line](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/golang.sh#L122) for now since the code was changed?

**Comment by vishh** [comment]
@dalanlan: Hyperkube should not be a static binary and it should run in a docker container with a busybox base image.

**Comment by dalanlan** [comment]
Agreed. Thx :)
Since you are aware of that, why not fix it? Also #7415 argues that it's a static one, which acted as the trouble maker.

**Comment by thockin** [comment]
To build non-static we need a reliable golang base container that has appropriate libs and isn't 450 MB.  do we have this?

**Comment by nlamirault** [comment]
Same error using the `gcr.io/google_containers/hyperkube:v1.0.6` and `1.07`.

**Comment by vishh** [comment]
@nlamirault: This is expected. The build fix wasn't included in the v1.0 releases. Can you try the latest v1.1 beta release? Sorry for the trouble!

**Comment by vishh** [comment]
@thockin: Why do we need golang base container? As of hyperkube containers are packaged with a debian baseimage and a on-static binary built using the regular build pipeline.

**Comment by vishh** [comment]
I'm closing this issue since things work as expected.
