### ISSUE TITLE
framework.Handle should allow to move pods to the active queue

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes/kubernetes#87738]
**What would you like to be added**:
Framework plugin can currently decide that pod is unschedulable (by returning Unschedulable and UnschedulableAndUnresolvable codes) during the scheduling attempt. However plugin has no control over what resource events are considered by the scheduler when making decision on whether pod should be moved between active, backoff and unschedulable queues. It should be possible to signal to the scheduler that pod is schedulable after observing an event relevant to the plugin. This is important feature to allow gang scheduling and working with custom resources  (see below).

**Why is this needed**:
Goal of the new scheduling framework is to allow more flexibility how pods are being scheduled.

One of the use cases mentioned in the scheduling framework proposal is to allow coscheduling / gang scheduling (see https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#coscheduling).

In the gang scheduling, whether pod can be scheduled depends on a state of other gang pods.
For example, gang pod might end up in the unschedulable or backoff queue, because other gang pods did not exist at the time that pod was attempted, thus gang requirement was not satisfied and pod scheduling attempt failed. However once all gang pods are created, the scheduler should attempt to schedule all of them.

As far as I understand currently there is no good solution to handle such scenario - some gang pods might be in the unschedulable or backoff queues and might stay there for a long time because pod is not moved to the active queue when other pods change. I suspect that for gang scheduling to work unassigned pods of the same gang should all be in the active queue when gang is being scheduled.

Currently, one hacky solution is to issue artificial updates to all gang pods from the plugin to force scheduler to move them into the active queue. However this might result in a burst of thousands of pod updates to the apiserver each time scheduler attempts to schedule a gang.

**Proposal**:

One solution would be to allow a plugin to signal to the scheduler that pods are now schedulable when observed state of the world has changed.

For example following method could move provided pods to the active queue internally:

```
// SignalSchedulable signals to the scheduler that state of the specified 
// pods has changed and these pods might be schedulable.
SignalSchedulable(pods []types.UID)
``` 

This method could be also called from the existing event handlers in the scheduler.

Please let me know if this make sense. I am happy to help implementing missing functionality.

Mentioned in more general #77746.

/sig scheduling

**Comment by draveness** [comment]
Currently, we could handle the gang scheduling by permit plugin, the pods could wait in permit plugin until the desired state, e.g. a minimum number of pods and etc. You could find an example here. https://github.com/hex108/coscheduling-plugin

You could also read the co-scheduling design document by @hex108 https://docs.google.com/document/d/1-igzuDyiN24yvcc0I4qGnN_w6tYRd9IZpEOgxrC7j_U/edit

**Comment by mateuszlitwin** [comment]
Permit plugin is not sufficient if pods are stuck in the unschedulable queue. To implement performant gang scheduling we need mechanism to ensure gang pods will go to the scheduling cycle roughly the same time.

Note that when you are scheduling a particular gang, then gang pods of other gangs should not be reserved/assumed, because no gang might end up scheduled. As the result you end up blocking all pods from being scheduled for at least a minute (until unschedulable queue is flushed plus back off time) and all gang pods go through scheduling cycle.

**Comment by draveness** [comment]
> Permit plugin is not sufficient if pods are stuck in the unschedulable queue. To implement performant gang scheduling we need mechanism to ensure gang pods will go to the scheduling cycle roughly the same time - otherwise pods might have to wait long time in the permit extension point for other gang pods and block all unassigned pods from scheduling.

You can't ensure the pods go to the scheduling cycle roughly the same time since the scheduling cycle runs in serial. 

> Currently, one hacky solution is to issue artificial updates to all gang pods from the plugin to force scheduler to move them into the active queue. However this might result in a burst of thousands of pod updates to the apiserver each time scheduler attempts to schedule a gang.

The scenario you mentioned here truly exists, the pod group has to wait for the last pod to be scheduled. But do you have numbers on the percentile of the stucking unschedulable pod, which blocks the whole pod group? IMO after we have real clusters running the co-scheduling plugin, we could come up with a better idea.

BTW: we could merge this discussion into https://github.com/kubernetes/kubernetes/issues/80611 issue.

**Comment by alculquicondor** [comment]
We shouldn't add more endpoints to the scheduler framework because we think it will allow gang scheduling. I'd rather see the complete design of gang scheduling first (like Jun's), which is already being discussed.

Do you have any other concrete use case?

**Comment by alculquicondor** [comment]
I shared this proposal earlier, but I can't work on it at the moment https://docs.google.com/document/d/1Dw1qPi4eryllSv0F419sKVbGXiPvSv6N_mJd6AVSg74/edit#heading=h.7ni9venvudmm
