### ISSUE TITLE
Secrets applied with stringData show configured even when no changes made

### ISSUE THREAD

**Issue by NickSchleicher** [kubernetes/kubernetes#87736]
**What happened**:
Applied a secret with `stringData`. After applying the same secret a second time (no changes made), kubectl outputs `secret/user configured`

**What you expected to happen**:
No changes were made on the second apply, so the output should be `secret/user unchanged`

**How to reproduce it (as minimally and precisely as possible)**:
secret_stringdata.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: default
type: Opaque
stringData:
  username: admin
  password: password
```
`kubectl apply -f secret_stringdata.yaml`
`kubectl apply -f secret_stringdata.yaml`

output:
```
secret/user configured
secret/user configured
```

expected output:
```
secret/user configured
secret/user unchanged
```

**Anything else we need to know?**:
If you do the above reproduction steps, but replace `stringData` with `data` and base64 encode the values, you'll get the expected output.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `minikube`

**Comment by mcristina422** [comment]
Is this just a side effect of how `stringData` is a write only field of the API? 

If so this should be documented. Maybe in
https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually

ref: https://github.com/kubernetes/kubernetes/pull/28263

@smarterclayton @liggitt 

/remove-lifecycle rotten
