### ISSUE TITLE
OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown"

### ISSUE THREAD

**Issue by robertchen** [kubernetes/kubernetes#87735]
**What happened**: using a POD for building docker images, sometimes got this error:
"OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown"

**What you expected to happen**:  should be no issue

**How to reproduce it (as minimally and precisely as possible)**:  build nginx r19 in kubelet

**Anything else we need to know?**:
when the issue happened,  the kubelet logs on that node which the pod was running on:
Jan 31 14:15:52 ip-10-0-2-157.ec2.internal kubelet[28227]: W0131 14:15:52.872076   28227 helpers.go:189] readString: Failed to read "/sys/fs/cgroup/memory/kubepods/burstable/podaac87eaa-b8b4

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.17.2
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): centos 7.7 
- Kernel (e.g. `uname -a`):  
Linux ip-10-0-2-212.ec2.internal 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Network plugin and version (if this is a network-related bug): weavenet
- others:
Tried to increase this on the node:
sysctl -w user.max_user_namespaces=30000
it helped a little(not happen so often) and the issue is still happening.

**Comment by babafakruddin476** [comment]
im facing the same.. in rancher kubernetes during pod initialization.....

Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "pxc-wsouserdb-pxc-1": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown

**Comment by cenfei** [comment]
how  fix  it?

**Comment by ndubbala** [comment]
Have you tried below steps ?

https://success.docker.com/article/user-namespace-runtime-error

**Comment by VictorLee0321** [comment]
systemctl restart docker.service fixed this issue.
look at this:
https://github.com/microsoft/vscode-docker/issues/1963
