### ISSUE TITLE
Automatic PV(C) support

### ISSUE THREAD

**Issue by gireeshpunathil** [kubernetes/kubernetes#87744]
**What would you like to be added**:
 - automatic provision of a pvc, one per POD
 - configurable at the project level, with default being disabled.
 - applied for every deployments under the project
 - size of the volume as a function of the size of the container that runs the app / service
 - retain last `n` volumes, with automatic cleanup of the rest, with `n` defaults to 1 and is configurable

**Why is this needed**:

By default, POD crashes lead to recycle without leaving a trace. This design works well for high availability philosophy, but acts against serviceability principles. Traditional (e.g:- con-containerized) deployments did not suffer from this issue.

Production deployments always need to have a way to persist some data - traces, dumps, logs etc. for some period of time that is mostly more than the life time of the container; so the day 2 operators always configure a PV for every deployment. If the platform supports a way to achieve this through standard semantics, that will improve the diagnostic story greatly.

**Comment by hprateek43** [comment]
@gireeshpunathil Wouldn't adding a PVC to every pod be counter-intuitive ? The PVC construct depends on an underlying PV. The usual recommendation is to add some logging or tracing solution on top of the Kubernetes infrastructure like the ELK stack or Jaeger.

Could you explain your use case?

**Comment by gireeshpunathil** [comment]
@hprateek43 - thanks for the response!

my use cases are:

 - dumps - (system dumps, snap dumps, heap dumps): they aid diagnostics, and need to persist across restarts
 - traces and logs - according to discretion, an architect want to design the runtime / middleware / application specific tracing and logging to be written to disk.

while this is possible through configuration on a per deployment level, both these requirements are scoped wide, at the project level on a minimum.

And hence it makes sense for a project user to be able to configure a PV and a PVC that applies across the board?

**Comment by gireeshpunathil** [comment]
no acknowledgement for 3 months. sad!

/remove-lifecycle stale
