### ISSUE TITLE
kubectl apply --prune namespace interaction

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#87756]
Not sure if this is a bug, feature requests, or a documentation issue.

**What happened**:
I am trying to apply some configs with --prune, and was surprised by the behavior. I have a config file with objects in multiple namespaces, and apply with `kubectl apply --prune` (note: no `--namespace` flag). By kube context was set to a namespace that was not in the manifests.

Here is what I found:
* If my context is set to a random namespace, nothing is pruned
* If its set to namespace X, only objects in namespace X are applied
* If I pass a `--namespace` flag I can control which namespace gets pruned, but that will break the apply because the file has multiple namespaces in it

**What you expected to happen**:
I expect some way to be able to apply a config file with objects in multiple namespace and having pruning across all namespaces.

Seems there are a few options:

1. Find all namespaces referenced in the file, prune these
2. Prune across all namespaces
3. Explicitly warn about why we are not pruning due to namespace mismatch

**How to reproduce it (as minimally and precisely as possible)**:
[repro.txt](https://github.com/kubernetes/kubernetes/files/4145190/repro.txt)

Run the script from namespace default, a, and b. You will see different behavior on each run.

Related? https://github.com/kubernetes/kubernetes/pull/83084

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.0
- Others:

/sig cli

**Comment by tatsuhiro-t** [comment]
I encountered this issue.  I think #83084 has the bug that o.namespace gets "default" if no namespace is given.  Then only a single namespace is visited with or without namespace.
If my observation is correct, it changes the bahaviour drastically.  In my work, pruning just stops working.
