### ISSUE TITLE
kubectl now showing api-server after enabling psp

### ISSUE THREAD

**Issue by simonstumpf** [kubernetes/kubernetes#87769]
I have a cluster running on kubernetes v1.17.2 with one master and an node.

**What happened**:
After I enabled PodSecurityPolicy in the kube-apiserver.yaml file
`- --enable-admission-plugins=NodeRestriction,ResourceQuota,PodSecurityPolicy`, the api server cant be viewed by `kubectl get pods -n kube-system`
Output of the command:
```
[root@master01 7_Security]# kubectl get pods -n kube-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-5b644bc49c-hw54h   1/1     Running   0          60m
calico-node-m7xrr                          1/1     Running   0          51m
calico-node-mzftg                          1/1     Running   0          60m
calico-node-sg7lh                          1/1     Running   0          52m
coredns-6955765f44-4z45p                   1/1     Running   0          62m
coredns-6955765f44-8fl8h                   1/1     Running   0          62m
etcd-master01                              1/1     Running   0          62m
kube-controller-manager-master01           1/1     Running   3          62m
kube-proxy-7z44x                           1/1     Running   0          62m
kube-proxy-q7fzs                           1/1     Running   0          51m
kube-proxy-smpvr                           1/1     Running   0          52m
kube-scheduler-master01                    1/1     Running   3          62m
metrics-server-694db48df9-gcq8r            1/1     Running   0          44m
traefik-ingress-controller-h8z49           1/1     Running   0          50m
traefik-ingress-controller-l7nwn           1/1     Running   0          50m
```

However i can see the api server with docker ps (kubectl works too)
```
[root@master01 7_Security]# docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
63671daa562d        f52d4c527ef2              "kube-scheduler --au…"   32 minutes ago      Up 32 minutes                           k8s_kube-scheduler_kube-scheduler-master01_kube-system_9c994ea62a2d8d6f1bb7498f10aa6fcf_3
8311aeadf93d        da5fd66c4068              "kube-controller-man…"   32 minutes ago      Up 32 minutes                           k8s_kube-controller-manager_kube-controller-manager-master01_kube-system_c9e50acf3a6fd2e4d143a4068ee60601_3
4692db8a6753        41ef50a5f06a              "kube-apiserver --ad…"   33 minutes ago      Up 33 minutes                           k8s_kube-apiserver_kube-apiserver-master01_kube-system_b30265390a7e97f531f9ed17c2d2da08_0
```

**What you expected to happen**:
The kube-apiserver should be seen with the command `kubectl get pods -n kube-system`
**How to reproduce it (as minimally and precisely as possible)**:
Add `PodSecurityPolicy` to the '--enable-admission-plugins' line. 

**Environment**:
- Kubernetes version (use `kubectl version`):
v.1.17.2
- Cloud provider or hardware configuration:
2vCPU and 4GB RAM
- OS (e.g: `cat /etc/os-release`):
CentOS 7
- Kernel (e.g. `uname -a`):
3.10.0-1062.9.1.el7.x86_64
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
traefik
- Others:

**Comment by liggitt** [comment]
Enabling PodSecurityPolicy requires constructing policies and granting access to all pod-creating actors. This means you have not defined a pod security policy and granted access to the kubelet to allow it to create the api-server pod. Check the kubelet logs and you will see the relevant forbidden errors.

/close

**Comment by simonstumpf** [comment]
> Enabling PodSecurityPolicy requires constructing policies and granting access to all pod-creating actors. This means you have not defined a pod security policy and granted access to the kubelet to allow it to create the api-server pod. Check the kubelet logs and you will see the relevant forbidden errors.
> 
> /close

Well I already had a psp before I edited the kubernetes-apisverver manifest. And the kubectl works perfectly with the enabled psp but I just can't see the apiserver. 

```[root@master01 ~]# kubectl describe clusterrolebindings.rbac.authorization.k8s.io  KubeSystemClusterRoleBinding 
Name:         KubeSystemClusterRoleBinding
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  PrivilegedClusterRole
Subjects:
  Kind   Name                    Namespace
  ----   ----                    ---------
  Group  system:serviceaccounts  kube-system 

 [root@master01 ~]# kubectl describe psp privilegedpolicy 
Name:         privilegedpolicy
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  policy/v1beta1
Kind:         PodSecurityPolicy
Metadata:
  Creation Timestamp:  2020-02-03T12:16:45Z
  Resource Version:    7608
  Self Link:           /apis/policy/v1beta1/podsecuritypolicies/privilegedpolicy
  UID:                 bf118579-d605-4c9a-aebd-1fc5bd9d8166
Spec:
  Allow Privilege Escalation:  true
  Allowed Capabilities:
    *
  Fs Group:
    Rule:        RunAsAny
  Host IPC:      true
  Host Network:  true
  Host PID:      true
  Host Ports:
    Max:       65535
    Min:       0
  Privileged:  true
  Run As User:
    Rule:  RunAsAny
  Se Linux:
    Rule:  RunAsAny
  Supplemental Groups:
    Rule:  RunAsAny
  Volumes:
    *
Events:  <none>

**Comment by liggitt** [comment]
> Well I already had a psp before I edited the kubernetes-apisverver manifest. And the kubectl works perfectly with the enabled psp but I just can't see the apiserver.

Did you grant the ability to use that PSP to the kubelet? See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies

**Comment by simonstumpf** [comment]
> > Well I already had a psp before I edited the kubernetes-apisverver manifest. And the kubectl works perfectly with the enabled psp but I just can't see the apiserver.
> 
> Did you grant the ability to use that PSP to the kubelet? See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies

Well I'm not quite sure. 
`Granting the controller access to the policy would grant access for all pods created by that controller, so the preferred method for authorizing policies is to grant access to the pod’s service account`
The docs say that the preferred method is to authorise the service account of a pod. Otherwise it would effect all pods created by that controller. So do I really need to authorise the kubelet controller?

**Comment by liggitt** [comment]
> So do I really need to authorise the kubelet controller?

The pods created by the kubelet to reflect the static pod manifests it is running do not have a service account specified, so yes, you do.

As an example, see the privileged PSP policy, role, and rolebinding used in the cluster addon:
* [policy](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/privileged.yaml)
* [role](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/privileged-role.yaml)
* [rolebinding](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/node-binding.yaml)

**Comment by simonstumpf** [comment]
> > So do I really need to authorise the kubelet controller?
> 
> The pods created by the kubelet to reflect the static pod manifests it is running do not have a service account specified, so yes, you do.
> 
> As an example, see the privileged PSP policy, role, and rolebinding used in the cluster addon:
> 
> * [policy](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/privileged.yaml)
> * [role](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/privileged-role.yaml)
> * [rolebinding](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/node-binding.yaml)

Thank you very mutch for your help :) 
It works now
