### ISSUE TITLE
Does metrics server support multiple replicas?

### ISSUE THREAD

**Issue by dudicoco** [kubernetes/kubernetes#87768]
Hi,

I could not find this in the documentation so perhaps it should be clarified there.
Can the metrics server be deployed with multiple replicas, or can it only run with 1 replica similar to controllers?

Thanks

**Comment by neolit123** [comment]
/sig instrumentation
/close

hi, you can ask in the #sig-instrumentation channel on k8s slack or here:
https://github.com/kubernetes-sigs/metrics-server/issues
