### ISSUE TITLE
Dynamic reloading of certs in kube-aggregator

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/kubernetes#87766]
**What would you like to be added**:
1.17 made almost all certs in api-machinery world dynamically loaded from disk (example #84200) but the same was not done for certs in kube-aggregator. 

**Why is this needed**:
Allows e.g. cert rotation

/sig api-machinery
/milestone v1.18

**Comment by deads2k** [comment]
This makes sense to fix.  It's the last gap that I know of.

**Comment by smourapina** [comment]
Hello @alenkacz!
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March, which is a few weeks from now. Is this issue still intended for milestone 1.18? Thanks in advance!

**Comment by alenkacz** [comment]
@smourapina yes :)

**Comment by smourapina** [comment]
Hello @alenkacz,
Just checking in once more with a friendly ping to remind you that code freeze is in about 1 week (5 March)!

**Comment by bai** [comment]
👋 Hello from Bug Triage team! Wanted to follow up on this issue with a friendly reminder that the code freeze for 1.19 is starting June 25th (about 4 weeks from now).

As this issue is tagged for 1.19, is it still planned for this release?
