### ISSUE TITLE
Exposure of pod in Job fails: AlreadyExists; service did not exist and is created anyway

### ISSUE THREAD

**Issue by LaumiH** [kubernetes/kubernetes#87771]
**What happened**: I have a pod inside a Job with label `app=mitmproxy`. I want to expose it with a ClusterIP service. The `expose` command works, but the AlreadyExists error is thrown anyway. Let me be clear: There was no service before, and then a service is successfully created, but the server tells me there is already a service.
As I run the commands in an ansible script, the output is 
`"stderr_lines": ["Error from server (AlreadyExists): services \"mitmproxy-svc-fvxwgydjh3\" already exists"], "stdout": "service/mitmproxy-svc-fvxwgydjh3 exposed", "stdout_lines": ["service/mitmproxy-svc-fvxwgydjh3 exposed"]`, which sais that the service already exists and is exposed at the same time ...

**What you expected to happen**: The pod is exposed via the mitmproxy-svc without any error.

**How to reproduce it (as minimally and precisely as possible)**:
1. `kubectl get services` shows no mitmproxy-svc.

2. as I run the commands in an ansible script, I do: 
- `POD=$(kubectl get pod -l app=mitmproxy -o name)` to get the pod name, and 
- `kubectl expose $POD --protocol=TCP --target-port=8080 --port=8080 --name=mitmproxy-svc --type=ClusterIP` to expose the pod.

3. The AlreadyExists error pops up, but the service is created anyway. So `kubectl get services` shows the mitmproxy-svc.

**Anything else we need to know?**: It sometimes works, and sometimes doesn't. I haven't found a reason, and therefore suppose it has somehow to do with timing. The ansible script always fails, but when I run it on my command line locally it only sometimes fails. I just don't get it.

**Environment**:
- Kubernetes version: v1.17.2
- Cloud provider or hardware configuration: minikube v1.6.2
- Host: 5.4.15-2-MANJARO

**Comment by liggitt** [comment]
/remove-sig api-machinery
/sig cli

I would recommend starting with the expose command implementation

**Comment by LaumiH** [comment]
Thanks for choosing the right SIG, it is my first bug and I did not know where to put it correctly.

**Comment by MikeSchlosser16** [comment]
I also see similar output using `client-go`. There is no secret, the client makes a call to create secret, the call fails with `AlreadyExists` but the secret gets created as expected. 

Like noted, it seems very racy. Sometimes it works fine, sometimes it fails. Hard to see a pattern from what I've noticed so far but there definitely appears to be a timing issue.
