### ISSUE TITLE
api/openapi-spec/swagger.json lacks version information

### ISSUE THREAD

**Issue by sh0rez** [kubernetes/kubernetes#87787]
**What happened**: `swagger.json` files in this repo for branches newer than `release-1.14` lack the version number in the `info` object, it contains `unversioned`, which seems incorrect.

**What you expected to happen**:
https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.15/api/openapi-spec/swagger.json, `.info.version` to include `1.15.x`, instead of `unversioned`.

**How to reproduce it (as minimally and precisely as possible)**:

##### Works (1.14):
```bash
$ curl -s https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.14/api/openapi-spec/swagger.json | jq .info
{
  "title": "Kubernetes",
  "version": "v1.14.11"
}

```

##### Works not (1.15 and above):
```bash
$ curl -s https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.15/api/openapi-spec/swagger.json | jq .info 
{
  "title": "Kubernetes",
  "version": "unversioned"
}
```

**Comment by liggitt** [comment]
Thanks for the report. This is working as intended. See https://github.com/kubernetes/kubernetes/pull/84654

/cc @justaugustus
