### ISSUE TITLE
Cleanup "slow-path" logic in scheduler Filters

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#87783]
by "slow-paths"  we mean logic that allows executing Filters in the absence of PreFilter state. 

In the scheduler, it is not possible that a Filter will be invoked without invoking its PreFilter first, but we still have logic in Filters to allow this because historically ClusterAutoscaler didn't consistently call "MetadataProducer", neither kubelet and daemonset controller.

Now that both Kubelet and DaemonSet controller dependencies have been removed, and according to  https://github.com/kubernetes/kubernetes/pull/87702#issuecomment-581298101, CA is consistently calling PreFilter, this special logic can be removed.

[ ] https://github.com/kubernetes/kubernetes/blob/845b23232125caeb67eb30659ff482404a3d3735/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L574

[ ] https://github.com/kubernetes/kubernetes/blob/845b23232125caeb67eb30659ff482404a3d3735/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L411

[ ] https://github.com/kubernetes/kubernetes/blob/845b23232125caeb67eb30659ff482404a3d3735/pkg/scheduler/framework/plugins/nodeports/node_ports.go#L111

[ ] https://github.com/kubernetes/kubernetes/blob/845b23232125caeb67eb30659ff482404a3d3735/pkg/scheduler/framework/plugins/noderesources/fit.go#L158

/sig scheduling
/help
/cc @losipiuk @MaciekPytel @Huang-Wei

**Comment by losipiuk** [comment]
ahg-g@ Just one note here; which I rose in the past. There is a possibility that we will need to add some optimization for features like pod inter-(anti)affinity. For which prefiltering is costly to compute; and yet often not needed. If we never reach the filter which checks pod-inter-affinity, because pod does not fit on node because of lack of resources, whole pre-filtering computation is a waste of time. 

We still need to do scalability testing with pod inter-(anti)affinity to see how big a problem is (if at all).

So with that in mind maybe it is worth to postpone pursuing with this effort a bit.

cc: @MaciekPytel

**Comment by ahg-g** [comment]
@losipiuk one solution is for CA to split the execution of filters into two phases: light and heavy filters. You can create two instances of the framework for each phase:

```
cheapFwk, err := framework.NewFramework(
	plugins.NewInTreeRegistry(),
	cheapPlugins,
	cheapPluginConfigs,
        ...        
)

expensiveFwk, err := framework.NewFramework(
	plugins.NewInTreeRegistry(),
	expensivePlugins,
	expensivePluginConfigs,
        ...        
)

cheapFwk.RunPreFilter()
s := cheapFwk.RunFilter(node)

if s == Success {
  expensiveFwk.RunPreFilter()
  s = expensiveFwk.RunFilter(node)
}


```

**Comment by losipiuk** [comment]
Yeah - I guess that would work. The only problem I see with that is that we need to be aware of the list of plugins. And not just depend on what is in default registry. But I guess we can live with that. Let's see what tests show. And implement that only if needed.

**Comment by ahg-g** [comment]
We could have those two sets as two separate providers in the scheduler, and the default one is always the combination of the two.

**Comment by notpad** [comment]
@ahg-g shoud we return an error if the state is nil, or just remove the else branch?

**Comment by losipiuk** [comment]
> We could have those two sets as two separate providers in the scheduler, and the default one is always the combination of the two.

This seems kinda CA specific. But if you are fine to maintain such two sets it would be great. Then source of truth, what is the set of plugins, would live in single repo.

**Comment by notpad** [comment]
There is a similar logic in https://github.com/kubernetes/kubernetes/blob/d0f582c9bf83d67b41020600f293e11a7f322d01/pkg/scheduler/framework/plugins/serviceaffinity/service_affinity.go#L250

Do we need to clean this one?

**Comment by ahg-g** [comment]
> > We could have those two sets as two separate providers in the scheduler, and the default one is always the combination of the two.
> 
> This seems kinda CA specific. But if you are fine to maintain such two sets it would be great. Then source of truth, what is the set of plugins, would live in single repo.

we already have them ordered, splitting the default provider into two is fine lists is fine.

**Comment by ahg-g** [comment]
> There is a similar logic in
> 
> https://github.com/kubernetes/kubernetes/blob/d0f582c9bf83d67b41020600f293e11a7f322d01/pkg/scheduler/framework/plugins/serviceaffinity/service_affinity.go#L250
> 
> Do we need to clean this one?

yes, we need to clean this up as well.

**Comment by ahg-g** [comment]
> @ahg-g shoud we return an error if the state is nil, or just remove the else branch?

For each filter that expects prefilter state, we should return an error if it didn't exist in CycleState.

**Comment by losipiuk** [comment]
> > > We could have those two sets as two separate providers in the scheduler, and the default one is always the combination of the two.
> > 
> > 
> > This seems kinda CA specific. But if you are fine to maintain such two sets it would be great. Then source of truth, what is the set of plugins, would live in single repo.
> 
> we already have them ordered, splitting the default provider into two lists is fine.

Great. I created https://github.com/kubernetes/kubernetes/issues/87822 to track this. And assigned to @aleksandra-malinowska to verify if we need it.
