### ISSUE TITLE
Define in-tree PluginConfig Args as component config types

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#87784]
/kind cleanup
/sig scheduling

As we move from parameters in the root of the component config to using args in PluginConfig (#87617), we are losing visibility of available parameters (in the API definition) and their early validation. Arguably, we might also lose versioning.

Since the configuration of in-tree plugins is part of the API, one alternative is to move the args definition to the `pkg/scheduler/apis/config` package and their versioned counterparts.

Extracted from https://github.com/kubernetes/kubernetes/pull/87725#issuecomment-581519825

/cc @ahg-g @Huang-Wei

**Comment by ahg-g** [comment]
+1 to having all plugin configuration definitions of in-tree plugins to the apis/config package. They are practically part of the API, and so we should make sure they are properly versioned.

**Comment by Huang-Wei** [comment]
+1 to hold plugin specific parameters in their own pluginConfig. Some parameter (e.g., `HardPodAffinitySymmetricWeight`) doesn't really make sense to be held at the root level.

**Comment by alculquicondor** [comment]
Since there is no consensus, I'll add this as a discussion item for next SIG meeting.

**Comment by alculquicondor** [comment]
Actually, let me add some clarification:
This question is not referring to keeping `hardPodAffinitySymmetricWeight` in the root of `KubeSchedulerConfig`. We already decided to just use PluginConfig for that.
The proposal here is to move `interpodaffinity.Args` to `pkg/scheduler/apis/config` and its versioned counterparts. The appeal is that of versioning and perhaps early validation.

**Comment by ahg-g** [comment]
PluginConfigs of the various in-tree plugins are part of the scheduler's config api, so ```pkg/scheduler/apis/config``` seems the natural place for it.

**Comment by Huang-Wei** [comment]
> The proposal here is to move the definition of the struct interpodaffinity.Args to pkg/scheduler/apis/config (probably as something like InterPodAffinityArgs) and to its versioned counterparts.

I suppose the `runtime.Unknown` type of `PluginConfig.Args` remains unchanged, right? i.e., it still accepts arbitrary bytes data, and decoded into particular Args type in runtime. It's just the particular Args are going to be held in a versioned manner.

**Comment by ahg-g** [comment]
Yes, we are not changing the current API. We are just declaring that whatever we parse from ```runtime.Unknown``` for a specific plugin is versioned and is part of the api.

**Comment by alculquicondor** [comment]
Update from SIG meeting: we are onboard with this change.

I'll work on it (or open for contributors) once multi scheduler profiles land.

**Comment by alculquicondor** [comment]
I'm trying to wrap my head around conversion and defaults once we move this types.

In particular, I'm thinking of building an scheme in `pkg/scheduler/framework/v1alpha1` that has all the in-tree plugin args registered. My hope is that with this scheme we can make [`DecodeInto`](https://github.com/kubernetes/kubernetes/blob/fe9073b8c14bbf6bbe42a2259f01d3d3a853a6a3/pkg/scheduler/framework/v1alpha1/registry.go#L31) use the scheme for in-tree plugins and resort to Unmarshal for out-of-tree plugins.

However, arg types don't have `metav1.TypeMeta`. They shouldn't need it, as they are supposed to only be specified in a `kubescheduler.config.k8s.io` file, and evolve with it.
So, I wonder if we can make it work, given that we would be providing a typed struct to `DecodeInto`. My fear is that the scheme wouldn't be able to do the conversion from v1alpha2, where we would define the json annotations and defaults.

@liggitt, could you shed some light?

**Comment by alculquicondor** [comment]
I'm trying to wrap my head around conversion and defaults once we move this types.

In particular, I'm thinking of building an scheme in `pkg/scheduler/framework/v1alpha1` that has all the in-tree plugin args registered. My hope is that with this scheme we can make [`DecodeInto`](https://github.com/kubernetes/kubernetes/blob/fe9073b8c14bbf6bbe42a2259f01d3d3a853a6a3/pkg/scheduler/framework/v1alpha1/registry.go#L31) use the scheme for in-tree plugins and resort to Unmarshal for out-of-tree plugins.

However, arg types don't have `metav1.TypeMeta`. They shouldn't need it, as they are supposed to only be specified in a `kubescheduler.config.k8s.io` file, and evolve with it.
So, I wonder if we can make it work, given that we would be providing a typed struct to `DecodeInto`. My fear is that the scheme wouldn't be able to do the conversion from v1alpha2, where we would define the json annotations and defaults.

@liggitt, could you shed some light?

**Comment by alculquicondor** [comment]
@Huang-Wei and I were brainstorming a couple of ideas offline:

1. We store the GVK of the component config in the scheduler and it's frameworks. Then we use that GVK for building a decoder and getting parsing into the internal types during plugin instantiation.
1. in `pkg/scheduler/apis/config/{version}/conversion.go` we parse the in-tree PluginConfig, convert them to the internal types and marshal them back into the `runtime.Unknown`. Then during plugin instantiation we can just use the internal types.
  1. Alternatively, we change `pkg/scheduler/apis/config.PluginConfig.Args` (internal type) from `runtime.Unknown` to `interface{}`. Then as we convert from the versions, we parse and set the pointer to the appropriate type. We still use `runtime.Unknown` if it is out-of-tree plugin. Not sure if there are precedents to this, but it seems reasonable to me given that these are internal types.

@liggitt, WDYT?

**Comment by ahg-g** [comment]
I don't like option 1, seems strange to pass around version and kind around in the scheduler. When I proposed moving plugin Args to ```apis/config``` my initial thought was that we will do something like option 2.

I like option 2.i as well since we will do the conversion once, and we will do it in the proper place, however we need to understand better how we plan to handle out-of-tree plugins.

>  We still use runtime.Unknown if it is out-of-tree plugin.

How will the conversion function know that a given plugin args is one for an out-of-tree plugin? if decoding fails? and where do you propose we store those? in a separate plugin args slice? I feel that will complicate things.

**Comment by alculquicondor** [comment]
> How will the conversion function know that a given plugin args is one for an out-of-tree plugin?

We would already have the structs in`types.go`, so I don't see any harm on having a private map (or event a `switch` statement) that is keyed by the plugin name to the type. Or we can have this slice in `pkg/scheduler/framework/plugins/registry.go`, except that we build the registry at init time.

**Comment by alculquicondor** [comment]
Any further questions? I would like to get this fixed early in the development cycle of 1.19.

**Comment by liggitt** [comment]
Is the expectation that all plugins and their args will be compiled-in?

**Comment by alculquicondor** [comment]
Yes. But only in-tree plugins would have their types versioned in `k8s.io/kube-scheduler`

**Comment by alculquicondor** [comment]
We came up with the following solution in an offline discussion with @liggitt:

1. Move the Arg types to the versioned and internal component config types #88585
1. Migrate from `runtime.Unknown` to `runtime.RawExtension` for the `PluginConfig.Args` type. This is backwards compatible. This new type allow us to pass an object along with the raw bytes. #89904
1. Implement `DecodeNestedObjects(d runtime.Decoder) error` for `v1alpha2.KubeSchedulerConfiguration` to decode the raw bytes into the known arg types.
1. Move defaulting of plugin args into the versioned packages.

**Comment by Huang-Wei** [comment]
Thanks Aldo for the wrap-up!

**Comment by alculquicondor** [comment]
/reopen

We still have pending work here :)
