### ISSUE TITLE
Windows 1909 failing test: E2E: [k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]

### ISSUE THREAD

**Issue by pjh** [kubernetes/kubernetes#87785]
"[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]" is failing consistently for Windows 1909 on GCE, but it's passing for 2019. Likely one of the containers it depends on hasn't been rebuilt as multi-arch?

https://testgrid.k8s.io/sig-windows#gce-windows-1909-master&width=20

Failure message from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1224386533100883969/build-log.txt:
```
[91m[1m• Failure [932.789 seconds][0m
[k8s.io] Container Runtime
[90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:697[0m
  blackbox test
  [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:38[0m
    when running a container with a new image
    [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:263[0m
      [91m[1mshould be able to pull from private registry with secret [NodeConformance] [It][0m
      [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:385[0m

      [91mFeb  3 18:44:35.174: All 3 attempts failed: expected container state: Running, got: "Terminated"[0m

      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/runtime.go:364
[90m------------------------------[0m
{"msg":"FAILED [k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]","total":-1,"completed":13,"skipped":194,"failed":1,"failures":["[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]"]}
```

**Comment by pjh** [comment]
/sig windows
cc @claudiubelu

**Comment by pjh** [comment]
More useful output from build-log.txt: https://gist.github.com/pjh/8d4da1cc3e4b272d82df26353c0109ac

```
Feb  3 18:44:35.253: INFO: At 2020-02-03 18:39:36 +0000 UTC - event for image-pull-testc6c4691b-5852-4724-87e5-b02f40db712f: {kubelet e2e-044834034c-d872a-windows-node-group-zmxf} Pulling: Pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
Feb  3 18:44:35.253: INFO: At 2020-02-03 18:39:37 +0000 UTC - event for image-pull-testc6c4691b-5852-4724-87e5-b02f40db712f: {kubelet e2e-044834034c-d872a-windows-node-group-zmxf} Pulled: Successfully pulled image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
Feb  3 18:44:35.253: INFO: At 2020-02-03 18:39:37 +0000 UTC - event for image-pull-testc6c4691b-5852-4724-87e5-b02f40db712f: {kubelet e2e-044834034c-d872a-windows-node-group-zmxf} Created: Created container image-pull-test
Feb  3 18:44:35.253: INFO: At 2020-02-03 18:39:37 +0000 UTC - event for image-pull-testc6c4691b-5852-4724-87e5-b02f40db712f: {kubelet e2e-044834034c-d872a-windows-node-group-zmxf} Failed: Error: failed to start container "image-pull-test": Error response from daemon: CreateComputeSystem image-pull-test: The container operating system does not match the host operating system.
```

Seems the gcr.io/authenticated-image-pulling/windows-nanoserver:v1 container doesn't work on 1909.

cc @yliaog

**Comment by pjh** [comment]
This test is also failing on https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-1903-master&width=20 for Windows 1903.

**Comment by yliaog** [comment]
see https://github.com/kubernetes-sigs/windows-testing/issues/117#issuecomment-561342481

**Comment by pjh** [comment]
Ah, thanks, I searched k/k for an existing issue but didn't think to search windows-testing. I posted a follow-up there.

**Comment by claudiubelu** [comment]
Hi. It is a known issue, I've also reported it a while back: https://github.com/kubernetes/kubernetes/issues/84609

**Comment by claudiubelu** [comment]
@listx , do you have push right to the ``gcr.io/authenticated-image-pulling`` registry? If so, could you recreate the ``windows-nanoserver:v1`` manifest list to include the newer Windows OS versions. Basically, the commands are:

    docker manifest create gcr.io/authenticated-image-pulling/windows-nanoserver:v1 mcr.microsoft.com/windows/nanoserver:1909-amd64 mcr.microsoft.com/windows/nanoserver:1903-amd64 mcr.microsoft.com/windows/nanoserver:1809
    docker manifest push --purge gcr.io/authenticated-image-pulling/windows-nanoserver:v1

**Comment by listx** [comment]
> @listx , do you have push right to the `gcr.io/authenticated-image-pulling` registry? If so, could you recreate the `windows-nanoserver:v1` manifest list to include the newer Windows OS versions. Basically, the commands are:
> 
> ```
> docker manifest create gcr.io/authenticated-image-pulling/windows-nanoserver:v1 mcr.microsoft.com/windows/nanoserver:1909-amd64 mcr.microsoft.com/windows/nanoserver:1903-amd64 mcr.microsoft.com/windows/nanoserver:1809
> docker manifest push --purge gcr.io/authenticated-image-pulling/windows-nanoserver:v1
> ```

I tried running this but got:

```
 $ docker manifest create gcr.io/authenticated-image-pulling/windows-nanoserver:v1 mcr.microsoft.com/windows/nanoserver:1909-amd64 mcr.microsoft.com/windows/nanoserver:1903-amd64 mcr.microsoft.com/windows/nanoserver:1809
docker manifest push --purge gcr.io/authenticated-image-pulling/windows-nanoserver:v1
mcr.microsoft.com/windows/nanoserver:1809 is a manifest list
cannot use source images from a different registry than the target image: mcr.microsoft.com != gcr.io
```

I looked into the `authenticated-image-pulling` project and noticed @ixdy and @Random-Liu as owners. Are you able to assist?

**Comment by yliaog** [comment]
docker manifest push  gcr.io/authenticated-image-pulling/windows-nanoserver:v1
Pushed ref gcr.io/authenticated-image-pulling/windows-nanoserver@sha256:ec76696da5a660a02bbfd304549d6e09d8c9fe48f2d4efe642f26cb1e46a6bde with digest: sha256:ec76696da5a660a02bbfd304549d6e09d8c9fe48f2d4efe642f26cb1e46a6bde
Pushed ref gcr.io/authenticated-image-pulling/windows-nanoserver@sha256:7c4ee446a647fdf8988672ae5e685cb66d53d4581e057b02e3a2bad728177f48 with digest: sha256:7c4ee446a647fdf8988672ae5e685cb66d53d4581e057b02e3a2bad728177f48
Pushed ref gcr.io/authenticated-image-pulling/windows-nanoserver@sha256:297cce9134ddaa2c09d91dea7ab7af0e58e06e59858c0311a0770143d144ddf1 with digest: sha256:297cce9134ddaa2c09d91dea7ab7af0e58e06e59858c0311a0770143d144ddf1
sha256:fb9b25770487567c02bf90dd3edea7917323556d1b7ba81ec042ffd5f9effeae

**Comment by yliaog** [comment]
this is fixed. the image manifest is available in gcr.io/authenticated-image-pulling/windows-nanoserver:v1
