### ISSUE TITLE
Moving Kubernetes master to new server issue

### ISSUE THREAD

**Issue by ZrytyADHD** [kubernetes/kubernetes#87803]
Hi,
I have a question. I create openshift  OKD cluster with:
1 master colocated with ETCD
1 infra node
2 app nodes
I try to move my master to new server but i can't do this properly. I add new master move everything to new server and it shoud be working but not. 
When old server is on everything is ok but when i shutdown it my cluster stop working. 
I try to figure out why and I discover something. After entering command : `kubectl cluster-info`
on old master i got : `Kubernetes master is running at https://server address:443` andI think this is a problem. Can anyone tell me how to move it to new master ? Trying to upgrade OKD cluster with upgrade playbook etc without success.

**Comment by neolit123** [comment]
> openshift OKD cluster

hi, i think it's best if you ask on a forum or slack channel that is OKD specific:
this issue tracker is for issues in core kubernetes.

thanks
/close
