### ISSUE TITLE
Extend Kubelet REST API (/spec) with System Info similar to Kube APIs (/nodes)

### ISSUE THREAD

**Issue by ganga1980** [kubernetes/kubernetes#87824]
**What would you like to be added**:
Currently, there is no Kubelet REST API to determine what is the underlying container run-time engine configured.

**Why is this needed**:
Having the information about the container run time engine configured on the kubelet would be super helpful to make decision about the run time specific scenarios. Currently, we use the docker HTTP APIs to get the information what containers running on the node  and docker Fluentbit parser to parse the container logs.  Other container run time engines like CRI-O and containerd have different logging and different set of APIs so having the information about the container runtime engine configured on the kubelet would help to make decisions what APIs/logging parser we need to call in based on the underlying container run time. 

Though there are REST APIs on the Kubelet to get the list of pods (using http://localhost:10255/pods) and perf counters (http://localhost:10255/stats/summary) , spec  (http://localhost:10255/spec) etc.. but there is no information about the container run time in any of these APIs so request to extend the existing API for example /spec with container runtime info.

Ihttps://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/

**Comment by ganga1980** [comment]
Hi, @neolit123, any update on addressing this issue?

**Comment by neolit123** [comment]
looks like nobody saw your ticket.
you could join a SIG node Zoom meeting and present your idea:
https://github.com/kubernetes/community/tree/master/sig-node

and/or also mention it in the #sig-node channel on k8s slack.

/remove-lifecycle rotten

**Comment by ganga1980** [comment]
> looks like nobody saw your ticket.
> you could join a SIG node Zoom meeting and present your idea:
> https://github.com/kubernetes/community/tree/master/sig-node
> 
> and/or also mention it in the #sig-node channel on k8s slack.
> 
> /remove-lifecycle rotten

> Sure, @neolit123 , I will join this Tuesday call and present the requirement to enable this functionality.
