### ISSUE TITLE
[Failing Test] gce-master-scale-correctness: [sig-cli] Kubectl client Simple pod should return command exit codes 

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#87851]
**Which jobs are failing**:
gce-master-scale-correctness

**Which test(s) are failing**:
[sig-cli] Kubectl client Simple pod should return command exit codes 

**Since when has it been failing**:
02/05

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
Feb  5 12:32:40.354: Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.243.250.2 --kubeconfig=/workspace/.kube/config --namespace=kubectl-3790 run -i --image=docker.io/library/busybox:1.29 --restart=Never failure-4 --leave-stdin-open -- /bin/sh -c exit 42:\nCommand stdout:\n\nstderr:\nError from server (NotFound): pods \"failure-4\" not found\n\nerror:\nexit status 1",
        },
        Code: 1,
    }
    error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.243.250.2 --kubeconfig=/workspace/.kube/config --namespace=kubectl-3790 run -i --image=docker.io/library/busybox:1.29 --restart=Never failure-4 --leave-stdin-open -- /bin/sh -c exit 42:
    Command stdout:
    
    stderr:
    Error from server (NotFound): pods "failure-4" not found
    
    error:
    exit status 1
```

**Anything else we need to know**:

/sig cli

**Comment by mm4tt** [comment]
The test seems to be flaking quite a lot recently 
![yLH4sEMtOQd](https://user-images.githubusercontent.com/2604887/77311161-e4d75900-6cff-11ea-9d80-0356adf87439.png)

Friendly ping, sig-cli, could you take a look?

**Comment by mm4tt** [comment]
FTR, these are really blocking tests and it's getting more urgent given the forthcoming 1.18 release

**Comment by mm4tt** [comment]
Full log of the failure:
```
I0322 12:39:08.504] [It] should return command exit codes
I0322 12:39:08.504]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:466
I0322 12:39:08.504] STEP: execing into a container with a successful command
I0322 12:39:08.505] Mar 22 12:39:03.524: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.196.135.251 --kubeconfig=/workspace/.kube/config --namespace=kubectl-1043 exec httpd -- /bin/sh -c exit 0'
I0322 12:39:08.505] Mar 22 12:39:04.012: INFO: stderr: ""
I0322 12:39:08.505] Mar 22 12:39:04.012: INFO: stdout: ""
I0322 12:39:08.505] STEP: execing into a container with a failing command
I0322 12:39:08.505] Mar 22 12:39:04.012: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.196.135.251 --kubeconfig=/workspace/.kube/config --namespace=kubectl-1043 exec httpd -- /bin/sh -c exit 42'
I0322 12:39:08.505] Mar 22 12:39:04.500: INFO: rc: 42
I0322 12:39:08.505] STEP: running a successful command
I0322 12:39:08.505] Mar 22 12:39:04.500: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.196.135.251 --kubeconfig=/workspace/.kube/config --namespace=kubectl-1043 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0'
I0322 12:39:08.506] Mar 22 12:39:04.933: INFO: rc: 1
I0322 12:39:08.506] Mar 22 12:39:04.933: FAIL: Unexpected error:
I0322 12:39:08.506]     <exec.CodeExitError>: {
I0322 12:39:08.506]         Err: {
I0322 12:39:08.506]             s: "error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.196.135.251 --kubeconfig=/workspace/.kube/config --namespace=kubectl-1043 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0:\nCommand stdout:\n\nstderr:\nError from server (NotFound): pods \"success\" not found\n\nerror:\nexit status 1",
I0322 12:39:08.506]         },
I0322 12:39:08.506]         Code: 1,
I0322 12:39:08.506]     }
I0322 12:39:08.507]     error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.196.135.251 --kubeconfig=/workspace/.kube/config --namespace=kubectl-1043 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0:
I0322 12:39:08.507]     Command stdout:
I0322 12:39:08.507]     
I0322 12:39:08.507]     stderr:
I0322 12:39:08.507]     Error from server (NotFound): pods "success" not found
I0322 12:39:08.507]     
I0322 12:39:08.507]     error:
I0322 12:39:08.507]     exit status 1
I0322 12:39:08.507] occurred
I0322 12:39:08.507] 
I0322 12:39:08.507] Full Stack Trace
I0322 12:39:08.507] k8s.io/kubernetes/test/e2e/kubectl.glob..func1.8.7()
I0322 12:39:08.507]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:481 +0x498
I0322 12:39:08.508] k8s.io/kubernetes/test/e2e.RunE2ETests(0xc0027b2100)
I0322 12:39:08.508]     _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:125 +0x324
I0322 12:39:08.508] k8s.io/kubernetes/test/e2e.TestE2E(0xc0027b2100)
I0322 12:39:08.508]     _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:119 +0x2b
I0322 12:39:08.508] testing.tRunner(0xc0027b2100, 0x4aea068)
I0322 12:39:08.508]     /usr/local/go/src/testing/testing.go:909 +0xc9
I0322 12:39:08.508] created by testing.(*T).Run
I0322 12:39:08.508]     /usr/local/go/src/testing/testing.go:960 +0x350
I0322 12:39:08.508] [AfterEach] Simple pod
I0322 12:39:08.508]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:354
I0322 12:39:08.509] STEP: using delete to clean up resources
```

It looks like the `kubectl run` finishes with `pod not found` error. Strange, I thought `kubectl run` is supposed to create a pod. 
Would really appreciate if someone from sig-cli could take a look

**Comment by jkaniuk** [comment]
4 out of last 8 runs failed:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

/sig scalability

**Comment by jkaniuk** [comment]
Another flaky, related test: https://github.com/kubernetes/kubernetes/issues/89811

**Comment by justaugustus** [comment]
SIG CLI Leads -- any update on this?
This is affecting scalability signal.

/assign @pwittrock @soltysh

**Comment by justaugustus** [comment]
@hasheddan @kubernetes/ci-signal -- Please keep tabs on this one.

**Comment by hasheddan** [comment]
@justaugustus yep, monitoring 👍

**Comment by soltysh** [comment]
It looks like there's a race between when the pod gets created and when we try to connect to it, thus we're seeing `Error from server (NotFound): pods "success" not found` but further down in the logs the pod is `success  gce-scale-cluster-minion-group-4-rk9k  Pending`, I'll be looking more into ti.

**Comment by mm4tt** [comment]
Thanks, @soltysh 

Any update on this?

**Comment by soltysh** [comment]
> Any update on this?

Sorry I got sidetracked yesterday and I'm back investigating this just now...

**Comment by soltysh** [comment]
Probable fix in https://github.com/kubernetes/kubernetes/pull/90364

**Comment by hasheddan** [comment]
Will continue to monitor here and reopen if needed :+1:

**Comment by wojtek-t** [comment]
Unfortunately - it seems that the problem still exists - the test failed today (an hour ago):
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1253293067511795714  :(

@soltysh @mm4tt ^^

**Comment by soltysh** [comment]
I'll check it, thx Wojtek for pointing that out.

**Comment by wojtek-t** [comment]
@soltysh - I'm not familiar with kubectl code, but I took a quick look and what I found is that this waitForPod() thing is happening only for pods with RestartPolicyNever:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L385

I must be missing something here, but for the case that failed it's not really the case, which means we don't wait for it?

**Comment by soltysh** [comment]
This particular one is using `RestartPolicyNever`, see the actual invocation that failed:
```
kubectl --server=https://35.243.250.2 --kubeconfig=/workspace/.kube/config --namespace=kubectl-3790 run -i --image=docker.io/library/busybox:1.29 --restart=Never failure-4 --leave-stdin-open -- /bin/sh -c exit 42
```

That's why I started with this approach.

**Comment by wojtek-t** [comment]
Sorry - the one for which the bug was originally opened.
But the today`s failure is actually slightly different (the same test, different case - sorry):
```
error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.196.154.90 --kubeconfig=/workspace/.kube/config --namespace=kubectl-1912 run -i --image=docker.io/library/busybox:1.29 --restart=OnFailure failure-2 -- /bin/sh -c cat && exit 42:\nCommand stdout:\n\nstderr:\nError from server (NotFound): pods \"failure-2\" not found\n\nerror:\nexit status 1",
```

The restart policy for this one is `OnFailure`

**Comment by soltysh** [comment]
Gotcha, so it looks like we progressed, I'll check the possible paths for this one, something tells me we're missing another timeout somewhere :wink:

**Comment by wojtek-t** [comment]
OK - I think I know what is going on here.
Here is what is happening (for the test case from two comments above):
- the test is setting "-i", so interactive mode is switched on
- that option triggers that Attach option defaults to true: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L187
- over the Run() command, we get to the handleAttachPod: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L378
- handleAttachPod is calling waitForPod

And waitForPod is broken.
The problem is the preconditionFunc: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L460
which is below passed to the UntilWithSync function

UntilWithSync underneath is creating an informer and calling that function against its state:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/watch/until.go#L143

But the informer is initialized from apiserver watchcache, so it may be lagging.
In large clusters we are observing lags in the order of small hundreds of milliseconds and that seem to be enough.

What is happening is that:
- informer is initialized (but the pod creation is not yet reflected in it)
- the preconditionFunc is called
- the state doesn't contain that pod (yet)
- the whole thing fails with that error

I actually believe, that just removing the preconditionFunc should actually solve the problem. I opened https://github.com/kubernetes/kubernetes/pull/90417 for that.

**Comment by wojtek-t** [comment]
@soltysh ^^ - please take a look at the PR that I assigned to you (it's literally one-liner as of now - if you want to add tests or anything like that, feel free to pick it up).

**Comment by wojtek-t** [comment]
Actually I went ahead, and fixed couple other commands too - so it's no longer one-liner. But still short one :)
