### ISSUE TITLE
client-go: Use log levels that match logging conventions

### ISSUE THREAD

**Issue by jodavis-suse** [kubernetes/kubernetes#87867]
/kind cleanup
/sig instrumentation

**What happened**:
SIG Instrumentation has published logging conventions for use in Kubernetes.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
The existing code has calls in the range 0 to 10 and still remains to be normalized to match the conventions.

**What you expected to happen**:
All klog.V() calls use values in the 0-5 range. So when a user specifies a verbosity of 5 they will receive the highest level of detail.
All uses of klog.V() (not just those over 5) should be reviewed for alignment with the logging conventions and adjusted as makes sense.

List of files to review (instances where log level > 5):
vendor/k8s.io/client-go/discovery/cached/disk/cached_discovery.go
vendor/k8s.io/client-go/rest/request.go
vendor/k8s.io/client-go/tools/clientcmd/loader.go
vendor/k8s.io/client-go/tools/remotecommand/v1.go
vendor/k8s.io/client-go/transport/round_trippers.go

**How to reproduce it (as minimally and precisely as possible)**:
Run with a log level of 5, and again with a log level of 10 and compare the resulting logs.
Note that many messages above 5 may only appear under certain error conditions.

**Anything else we need to know?**:
This is not a critical bug and most users will not notice any change.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17 and older
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by RyanRod** [comment]
/assign
I'd like to work on this one

**Comment by jodavis-suse** [comment]
@RyanRod Should be pretty straight forward.  The key is to review all the log messages for sanity in the range from the convention.

**Comment by jodavis-suse** [comment]
Note: similar patch in apimachinery - https://github.com/kubernetes/kubernetes/pull/87864

**Comment by RyanRod** [comment]
@jodavis-suse Thanks. Got a first draft PR open with some obvious adjustments. A few log messages could fit into debug or trace categories, let me know if anything seems incorrect.

**Comment by liggitt** [comment]
The trace-level request logging is intentionally at much higher levels. Mixing request-level trace logs with logic-level trace logs ("did x", "did y", etc) would make the logic-level trace logs almost impossible to consume. Before making changes to flatten the verbosities, we need to ensure the resulting logs are 1) useful, 2) do not break existing clusters by increasing logging rates for existing verbosity levels by multiple orders of magnitude.

**Comment by liggitt** [comment]
Also, given https://github.com/kubernetes/community/pull/3162#issuecomment-458532311, I would recommend waiting for some of the current discussions around logging (e.g. https://github.com/kubernetes/enhancements/pull/1367) to resolve before sweeping the codebase to make it conform to a set of conventions that does not account for all the types of trace logging we do.

**Comment by liggitt** [comment]
For those who wondered this logging guide's history:
* https://github.com/kubernetes/community/commits/master/contributors/devel/logging.md
* https://github.com/kubernetes/kubernetes/commits/master/docs/devel/logging.md
* https://github.com/kubernetes/kubernetes/commits/master/docs/logging.md

The initial levels were added in https://github.com/kubernetes/kubernetes/commit/4e56dafecc9d609f45bb4577a2c30c173d17964e#diff-6fede6782d33a3306a99cb1a47ea5f6b by @smarterclayton

The V(5) level was added in https://github.com/kubernetes/community/pull/2887#issuecomment-435275578, but noted that we don't have consistency with that guide.

Before sweeping to make consistent with the guide, we should consider whether the guide is correct. Making HTTP requests and error codes be logged at V(2), for example, does not produce reasonable logs at default verbosity.

/assign @smarterclayton @thockin

**Comment by deads2k** [comment]
> Making HTTP requests and error codes be logged at V(2), for example, does not produce reasonable logs at default verbosity.

I found that note in the guidelines and also consider the advice to be highly suspect.  

The v(0) advice about programmer errors seems incorrect too.  Panic guidance is out of date.  I think we decided that events come out at V2, which conflicts with the advice about v(1) and repeating errors.


I think I'd go with something more like error showing me something broke across multiple namespaces, info showing me cross namespace level state changes, v2 showing edges in namespaces, and v4 showing me why the edges were made.

**Comment by jodavis-suse** [comment]
Thanks for the history links, @liggitt 
So I'm still new to Kubernetes and may be missing something.  Are you saying that the logging conventions were not properly reviewed before they were merged, so a change should be made to the conventions to mark them as invalid?
I will agree that the guidelines in the document need to be interpreted depending on the purpose of the code they are applied to.

**Comment by liggitt** [comment]
> Are you saying that the logging conventions were not properly reviewed before they were merged, so a change should be made to the conventions to mark them as invalid?

The two main issues are:
1. The current state of our log levels is wildly out of step with the guidelines
2. If we followed the guidelines as written, our log volume would increase to problematic levels at current scale and would not be usable

**Comment by jodavis-suse** [comment]
I was hoping this and the change in apimachinery would be a good step toward addressing 1.
I am a bit confused by 2.  Are you saying the guidelines are recommending putting log messages for common operations (live http requests) at too low of a log level, or that you are already using a high level of logging (5 or more?) in production that can't take any more messages?  I hope that doesn't sound like I'm trying to argue, just trying to better understand behavior, as my expectation is that these changes would not effect a system running in production.

I am assuming the guidelines are treated as guidelines and combined with some experience on the part of the coder, so that not _every_ http request is logged at a 2 but rather critical instructions and changes are tracked.  It feels like there is an issue between different kinds of trace level logging that would be better addressed by restricting logging to different modules rather than relying on serial log levels.

If the consensus in SIG-instrumentation is that we aren't ready for this change, I'm ok with that.  Is there a proper way to continue this discussion or decide on a different plan?

**Comment by smarterclayton** [comment]
The rules in that doc apply to server code, not client libraries, library packages, or cli code

**Comment by jodavis-suse** [comment]
Ah, that makes some sense.  Can we make a clarification to that in the logging convention?  The guideline doesn't have any stated restrictions.  It would be simple to add a line stating "The guideline is for server code to use log levels up to V(5), though client libraries, library packages, and CLI code may find levels up to V(10) are needed for tracing."
