### ISSUE TITLE
config kubeadm kubelet client&server certificate auto rotation configuration did not succeed

### ISSUE THREAD

**Issue by zhangxingdeppon** [kubernetes/kubernetes#87878]
**What happened**:
hi, buddy, I met a problem, when I operated kubeadm's kubelet client &server certificate rotation configuration,  but it did not succeed, can you give me some ideas? it is very important to me, thanks very much.
for details, see below:
here is  the current kubelet's certificate :
<pre><code>
[root@k8s-master ~]# cd /var/lib/kubelet/pki/
[root@k8s-master pki]# ls -trl
total 16
-rw-r--r-- 1 root root 2177 Dec  9 17:47 kubelet.crt
-rw------- 1 root root 1679 Dec  9 17:47 kubelet.key
-rw------- 1 root root 2761 Dec  9 17:47 kubelet-client-2019-12-09-17-47-58.pem
lrwxrwxrwx 1 root root   59 Dec  9 17:48 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2019-12-09-17-48-29.pem
-rw------- 1 root root 1118 Dec  9 17:48 kubelet-client-2019-12-09-17-48-29.pem
</code></pre>
I have created the `rbac` object before.
<pre><code>
[root@k8s-master ssl]# vim ca-update.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:certificates.k8s.io:certificatesigningrequests:selfnodeserver
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/selfnodeserver
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeadm:node-autoapprove-certificate-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:certificates.k8s.io:certificatesigningrequests:selfnodeserver
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes

kubectl create –f ca-update.yaml
[root@k8s-master ssl]# kubectl apply -f ca-update.yaml 
clusterrole.rbac.authorization.k8s.io/system:certificates.k8s.io:certificatesigningrequests:selfnodeserver created
clusterrolebinding.rbac.authorization.k8s.io/kubeadm:node-autoapprove-certificate-server created
</code></pre>

firstly, I add the parameters to  the controler-manager, after that the static pod will be auto restart.
<pre><code>
- --experimental-cluster-signing-duration=87600h0m0s
- --feature-gates=RotateKubeletServerCertificate=true
</code></pre>

the whole controler-manager yaml：
<pre><code>
[root@k8s-master ~]# cat /etc/kubernetes/manifests/kube-controller-manager.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --address=127.0.0.1
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true
    - --experimental-cluster-signing-duration=87600h0m0s
    - --feature-gates=RotateKubeletServerCertificate=true
    image: registry.aliyuncs.com/google_containers/kube-controller-manager:v1.13.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
</code></pre>

secondly, I add the parameters to  the node kubelet.
<pre><code>
--feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true  --rotate-certificates
</code></pre>
<pre><code>
[root@k8s-master ~]# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=cgroupfs --feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true  --rotate-certificates --network-plugin=cni --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.1
</code></pre>

after that, restart the kubelet process, but the configration don't generate new certificate 
<pre><code>
systemctl  restart kubelet 
</code></pre>
<pre><code>
[root@k8s-master ~]# cd /var/lib/kubelet/pki/
[root@k8s-master pki]# ls -trl
total 16
-rw-r--r-- 1 root root 2177 Dec  9 17:47 kubelet.crt
-rw------- 1 root root 1679 Dec  9 17:47 kubelet.key
-rw------- 1 root root 2761 Dec  9 17:47 kubelet-client-2019-12-09-17-47-58.pem
lrwxrwxrwx 1 root root   59 Dec  9 17:48 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2019-12-09-17-48-29.pem
-rw------- 1 root root 1118 Dec  9 17:48 kubelet-client-2019-12-09-17-48-29.pem
</code></pre>
 I  check the kubelet log, show that the kubelet's paremeter has been deprecated
see below details:
<pre><code>
Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.456773   14326 server.go:407] Version: v1.13.1
Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.457022   14326 plugins.go:103] No cloud provider specified.
Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.463148   14326 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.521080   14326 server.go:666] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.522432   14326 container_manager_linux.go:248] container manager verified user specified cgroup-root exists: []
</code></pre>

 according to the information `pecified by the Kubelet's --config flag`,  I added these parameters to  `/var/lib/kubelet/config.yaml`.
<pre><code>
rotateCertificates: true
featureGates:
  RotateKubeletClientCertificate: true
  RotateKubeletServerCertificate: true
</code></pre>

 the whole config yaml:
<pre><code>
[root@k8s-master ~]# cat /var/lib/kubelet/config.yaml
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
cgroupsPerQOS: true
clusterDNS:
- 10.1.0.10
clusterDomain: cluster.local
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable:
- pods
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kind: KubeletConfiguration
kubeAPIBurst: 10
kubeAPIQPS: 5
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 110
nodeLeaseDurationSeconds: 40
nodeStatusReportFrequency: 1m0s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
registryBurst: 10
registryPullQPS: 5
resolvConf: /etc/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 1m0s
rotateCertificates: true
featureGates:
  RotateKubeletClientCertificate: true
  RotateKubeletServerCertificate: true
</code></pre>

 and restart the kubelet, but it  also don't gernarate the expected certification.
the kubelet's logs :
<pre><code>
Feb 06 12:41:49 k8s-master systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Feb 06 12:41:49 k8s-master systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Feb 06 12:41:49 k8s-master systemd[1]: Started kubelet: The Kubernetes Node Agent.
Feb 06 12:41:49 k8s-master kubelet[17276]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 12:41:49 k8s-master kubelet[17276]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 12:41:49 k8s-master kubelet[17276]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 12:41:49 k8s-master kubelet[17276]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 12:41:49 k8s-master kubelet[17276]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 12:41:49 k8s-master kubelet[17276]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 06 12:41:49 k8s-master kubelet[17276]: I0206 12:41:49.690306   17276 server.go:407] Version: v1.13.1
Feb 06 12:41:49 k8s-master kubelet[17276]: I0206 12:41:49.690627   17276 plugins.go:103] No cloud provider specified.
Feb 06 12:41:49 k8s-master kubelet[17276]: I0206 12:41:49.697744   17276 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Feb 06 12:41:49 k8s-master kubelet[17276]: I0206 12:41:49.764076   17276 server.go:666] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Feb 06 12:41:49 k8s-master kubelet[17276]: I0206 12:41:49.766594   17276 container_manager_linux.go:248] container manager verified user specified cgroup-root exists: []
Feb 06 12:41:49 k8s-master kubelet[17276]: I0206 12:41:49.766624   17276 container_manager_linux.go:253] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms}
</code></pre>
The full log file is below：
[kubelet-all.log](https://github.com/kubernetes/kubernetes/files/4163239/kubelet-all.log)
Is there a problem with which of my steps? Please tell me if need more information, I'm  pleasure to provide it, thank you very much.

**What you expected to happen**:
config the kubeadm kubelet auto client&server certificate rotation configuration can be success.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
<pre><code>
[root@k8s-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
</code></pre>
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
<pre><code>
[root@k8s-master ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
</code></pre>
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhangxingdeppon** [comment]
@kubernetes/sig-apps-bugs

**Comment by tedyu** [comment]
I found the following in CHANGELOG-1.11.md :

The kubelet `--rotate-certificates` flag is now deprecated, and will be removed in a future release. The kubelet certificate rotation feature can now be enabled via the `.RotateCertificates` field in the kubelet's config file.  ([#63912](https://github.com/kubernetes/kubernetes/pull/63912), [@luxas](https://github.com/luxas))

FYI

**Comment by zhangxingdeppon** [comment]
> after that, restart the kubelet process, but the configration don't generate new certificate
> 
> ```
> 
> systemctl  restart kubelet 
> ```
> 
> ```
> 
> [root@k8s-master ~]# cd /var/lib/kubelet/pki/
> [root@k8s-master pki]# ls -trl
> total 16
> -rw-r--r-- 1 root root 2177 Dec  9 17:47 kubelet.crt
> -rw------- 1 root root 1679 Dec  9 17:47 kubelet.key
> -rw------- 1 root root 2761 Dec  9 17:47 kubelet-client-2019-12-09-17-47-58.pem
> lrwxrwxrwx 1 root root   59 Dec  9 17:48 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2019-12-09-17-48-29.pem
> -rw------- 1 root root 1118 Dec  9 17:48 kubelet-client-2019-12-09-17-48-29.pem
> ```
> 
> I check the kubelet log, show that the kubelet's paremeter has been deprecated
> see below details:
> 
> ```
> 
> Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Feb 06 11:08:16 k8s-master kubelet[14326]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.456773   14326 server.go:407] Version: v1.13.1
> Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.457022   14326 plugins.go:103] No cloud provider specified.
> Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.463148   14326 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
> Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.521080   14326 server.go:666] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
> Feb 06 11:08:16 k8s-master kubelet[14326]: I0206 11:08:16.522432   14326 container_manager_linux.go:248] container manager verified user specified cgroup-root exists: []
> ```
> 
> according to the information `pecified by the Kubelet's --config flag`, I added these parameters to `/var/lib/kubelet/config.yaml`.
> 
> ```
> 
> rotateCertificates: true
> featureGates:
>   RotateKubeletClientCertificate: true
>   RotateKubeletServerCertificate: true
> ```
> 


yes, you can see above details, I have set `rotateCertificates: true` & `featureGates` in the kubelet's config file, but it didn't work.

**Comment by eladm26** [comment]
new contributor, would love to take this one
/assign

**Comment by zhangxingdeppon** [comment]
@eladm26 wow, great, thanks, could you give me some ideas?

**Comment by zhangxingdeppon** [comment]
@tedyu I found the official has no specific implementation steps in this section,do you have any other mothed？thanks very much.

**Comment by neolit123** [comment]
i responded to the similar issue in k/kubeadm here:
https://github.com/kubernetes/kubeadm/issues/2024

/close
