### ISSUE TITLE
Java Controller Example with reconciler - not working as expected

### ISSUE THREAD

**Issue by meenalpandey** [kubernetes/kubernetes#87889]
I am trying to execute the Controller Example (using listNamespacedPodCall) in Java -
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
However, I am not getting the triggers or the logs whenever the POD is added/updated/deleted.

Ideally the log "triggered reconciling", should be printed with the POD details.

It can be reproduced simply by replacing the call to "listNodeCall" API with "listNamespacedPodCall". Using kubectl apply to apply the yaml file. Just changing the "replicas" configured in the yaml and applying the yaml again. Excepted to get the log "triggered reconciling".

I am running kubernetes using docker desktop.
Also, in the above-mentioned example link uses "listNodeCall . However, in my sample, I am using "listNamespacedPodCall" API to get the POD details.
The namespace is "default" and deployment is "nginx".
Attaching the sample yaml and code snippet files.
<img width="1146" alt="ControllerCodeSnippet_1" src="https://user-images.githubusercontent.com/42957286/73936922-ded11880-4909-11ea-887b-20ab94d81047.png">

<img width="1132" alt="ControllerCodeSnippet_2" src="https://user-images.githubusercontent.com/42957286/73936927-e1337280-4909-11ea-9588-370453cb77cc.png">

<img width="591" alt="DeploymentYaml" src="https://user-images.githubusercontent.com/42957286/73936930-e2fd3600-4909-11ea-80ec-3b83f91e2976.png">

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.5
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): MacOs
- Kernel (e.g. `uname -a`): Darwin PU-02276.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- Install tools: Docker-desktop, v2.1.5.0

**Comment by roycaihw** [comment]
This sounds like a client issue. Could you file an issue in the Java client repo?
