### ISSUE TITLE
Kubeadm on ContainerLinux - flexvolume-dir points to read-only directory and fails

### ISSUE THREAD

**Issue by gmateusz09** [kubernetes/kubernetes#87883]
**What happened**:
Kubeadm v1.17.2 fails to deploy a cluster or kube-controller-manager to be precise.

**Kubelet logs**
`Feb 06 11:08:28 hsr00036 kubelet[27225]: E0206 11:08:28.184776   27225 kubelet.go:1680] Unable to attach or mount volumes for pod "kube-controller-manager-hsr00036_kube-system(ea3e4a11f67f52fe745c1d60c2319245)": unmounted volumes=[flexvolume-dir], unattached volumes=[ca-certs flexvolume-dir k8s-certs kubeconfig usr-share-ca-certificates]: timed out waiting for the condition; skipping pod
Feb 06 11:08:28 hsr00036 kubelet[27225]: E0206 11:08:28.184833   27225 pod_workers.go:191] Error syncing pod ea3e4a11f67f52fe745c1d60c2319245 ("kube-controller-manager-hsr00036_kube-system(ea3e4a11f67f52fe745c1d60c2319245)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[ca-certs flexvolume-dir k8s-certs kubeconfig usr-share-ca-certificates]: timed out waiting for the condition
`
**Reason why it fails**
kube-controller-manager.yaml
...
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    **- mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec**
      **name: flexvolume-dir**
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      **type: DirectoryOrCreate**
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates

**/usr is mounted as Read-Only in Container Linux (CoreOS)**

**How to reproduce it (as minimally and precisely as possible)**:
- Run ContainerLinux in VM
- install kubeadm (follow https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)

**Environment**:
- Kubernetes version 1.17.2
- Cloud provider or hardware configuration: Bare metal
- OS (e.g: `cat /etc/os-release`): Container Linux by CoreOS 2191.5.0 (Rhyolite)
- Kernel (e.g. `uname -a`): Linux hsr00036 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 Intel(R) Xeon(R) CPU X5675 @ 3.07GHz GenuineIntel GNU/Linux
- Install tools: Kubeadm

**Comment by gmateusz09** [comment]
When I replace K8s manifest files (kube-apiserver.yaml  kube-controller-manager.yaml  kube-scheduler.yaml) and edit kube-controller-manager.yaml:
...
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates

Then I am able to deploy a working cluster with:
kubeadm init --apiserver-advertise-address=172.16.242.36 --control-plane-endpoint \
$loadbalancer:6443 --upload-certs --v=2  --pod-network-cidr=10.244.0.0/16 **--skip-phases=control-plane --ignore-preflight-errors=all**

**Comment by neolit123** [comment]
what happens if you modify the static Pod YAML to mount a non-read-only path and pass this path as --flexvolume-dir?

**Comment by gmateusz09** [comment]
When I use the following YAML:
...
    **- mountPath: /etc/kubernetes/flexvolume-dir
      name: flexvolume-dir
      readOnly: false**
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
  **- hostPath:
      path: /etc/kubernetes/flexvolume-dir
      type: DirectoryOrCreate
    name: flexvolume-dir**
status: {}

Everything works fine and I don't see any errors in the Kubelet log:
`Feb 08 11:56:44 hsr00036 kubelet[29995]: I0208 11:56:44.433801   29995 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "flexvolume-dir" (UniqueName: "kubernetes.io/host-path/dd6c28b9bba87463d07190acaf88fbee-flexvolume-dir") pod "kube-controller-manager-hsr00036" (UID: "dd6c28b9bba87463d07190acaf88fbee")`

**Comment by neolit123** [comment]
if you are not able to apply custom settings using the kubedam config, you can also try the `--kustomize..` feature of `kubeadm init`. it allows you to patch the control-plane Pod manifests files.

/close
