### ISSUE TITLE
[Flaky Test] [sig-storage] Subpath tests are flaky

### ISSUE THREAD

**Issue by ramineni** [kubernetes/kubernetes#87882]
**Which jobs are flaking**:
Summarizing 2 Failures:
[Fail] [sig-storage] In-tree Volumes [Driver: cinder] [Testpattern: Dynamic PV (default fs)] subPath [It] should support restarting containers using file as subpath [Slow][LinuxOnly] 
/workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:180
[Fail] [sig-storage] In-tree Volumes [Driver: cinder] [Testpattern: Dynamic PV (default fs)] subPath [It] should support existing directories when readOnly specified in the volumeSource 
/workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:180
**Which test(s) are flaking**:

**Testgrid link**:
https://logs.openlabtesting.org/logs/06/906/757599c68c3b880adb29e6fb57b3045e7c8d56f5/cloud-provider-openstack-multinode-csi-migration-test/cloud-provider-openstack-multinode-csi-migration-test/66dc68f/logs/kubernetes/e2e.log
**Reason for failure**:
Failing in cleanup phase mostly.
**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by chrigl** [comment]
/close

I was able to track it down to a race condition in `cinder-csi-plugin`. See https://github.com/kubernetes/cloud-provider-openstack/pull/925
