### ISSUE TITLE
kube-apiserver hang on startup if etcd down

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#8790]
If you start the kube-apiserver while etcd is down or unavailable the apiserver will hang.  There is nothing in the logs to tell you the problem. So if you typo the --etcd_servers= argument you just get a hang and no feedback.  The hang is actually in `pkg/registry/service/ipallocator/controller/repair.go` `func (c *Repair) RunOnce() error` somewhere in `c.alloc.Get()`.  Once I debugged the hang to there, I realized it was etcd that was the problem.

It would be nice if we got some sort of error/log/info about why the apiserver is hanging...

**Comment by bgrant0607** [comment]
@xiang90 Is this still an issue?

**Comment by xiang90** [comment]
not sure. will take a look this week.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
