### ISSUE TITLE
Setting HPA on CPU Utilization on Deployment with Multi Container Pod computes desired replicas incorrectly

### ISSUE THREAD

**Issue by samof76** [kubernetes/kubernetes#87917]
**What happened**:

I am using EKS cluster k8s version 1.14.8, now I am trying to i tried create the hpa...

```
$ kubectl autoscale deployment http-app --cpu-percent=50 --min=15 --max=18 -n example
horizontalpodautoscaler.autoscaling/http-app autoscaled
$ kubectl describe horizontalpodautoscaler.autoscaling/http-app -n example
Name:                                                  http-app
Namespace:                                             example
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Thu, 06 Feb 2020 15:02:30 +0000
Reference:                                             Deployment/http-app
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  31% (259m) / 50%
Min replicas:                                          15
Max replicas:                                          18
Deployment pods:                                       18 current / 18 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  SuccessfulRescale  25s   horizontal-pod-autoscaler  New size: 18; reason: cpu resource utilization (percentage of request) above target
```

Please notice that I have 15 pod already running at an average utilization of 31% and target is 50%, but i see that it immediately scales my app to 18 which is my max replicas. I am not sure is there an issue with the HPA or my understanding is amiss?

FYI, my pod is multi container pod, running 7 containers.

**What you expected to happen**:

The expect is that the desired replicas to stay at the minReplicas in this case.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I tried setting the HPA on the replicaset created by the Deployment. And it seems to work as as desired, that it does not immediately shoot the desired count to the 18, but waits for the Utilization to grow over the Target, add bring up more pods, but it seems to endup with a conflict with Deployments desired replicas. The pods keep getting terminated.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
EKS (1.14.9)
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):

```
Linux ip-172-16-136-88.ec2.internal 4.14.154-128.181.amzn2.x86_64 #1 SMP Sat Nov 16 21:49:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by EwanValentine** [comment]
We're seeing the same thing, same version of Kubernetes as well, on EKS. Auto-scaling kicks in and maxes out our HPA, but the cpu usage is like 0%.

**Comment by samof76** [comment]
I apologize, but any updates on this?

**Comment by samof76** [comment]
Also notice similar behaviour on EKS 1.15 cluster as well. Experimenting on the KOPS to get more insights.

**Comment by ratulbasak** [comment]
I am having same issue in k8s 1.15 eks cluster. any update on that?

**Comment by Jeffwan** [comment]
Sorry I don't have enough capacity to help on this issue. Anyone who is interested in it please help on it.
