### ISSUE TITLE
make clean ; make WHAT=test/e2e/e2e.test" fails

### ISSUE THREAD

**Issue by childsb** [kubernetes/kubernetes#8792]
when building e2e_test.go using 'make WHAT=test/e2e/e2e' fails with:

(20:51:55)[bc-macpro]:[~/dev/git/t/kubernetes/]# make clean ; make WHAT=test/e2e/e2e.test
build/make-clean.sh
+++ [0525 20:52:03] Verifying Prerequisites....
+++ [0525 20:52:03] Cleaning out local _output directory
rm -rf _output
rm -rf Godeps/_workspace/pkg
hack/build-go.sh test/e2e/e2e.test
+++ [0525 20:52:04] Building go targets for darwin/amd64:
    test/e2e/e2e.test
/Users/bc/dev/git/t/kubernetes/hack/lib/golang.sh: line 367: pushd: /Users/bc/dev/git/t/kubernetes/_output/local/go/bin: No such file or directory
!!! Error in /Users/bc/dev/git/t/kubernetes/hack/lib/golang.sh:361
  'pushd "$(dirname ${outfile})" > /dev/null' exited with status 1
Call stack:
  1: /Users/bc/dev/git/t/kubernetes/hack/lib/golang.sh:361 kube::golang::build_binaries_for_platform(...)
  2: /Users/bc/dev/git/t/kubernetes/hack/lib/golang.sh:488 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
make: *** [all] Error 1

However 'make all; make (20:51:55)[bc-macpro]:[~/dev/git/t/kubernetes/]# make clean ; make WHAT=test/e2e/e2e.test' works

**Comment by bgrant0607** [comment]
Obsolete
