### ISSUE TITLE
HPA being evaulated incorrectly - Can't grab CPU metrics from metrics.k8s.io api

### ISSUE THREAD

**Issue by DerrickMartinez** [kubernetes/kubernetes#87935]
**What happened**:

Had a production issue today with an HPA not scaling. Turned out an HPA was unable to evaluate a cpu field. (i.e. prod-api-blue-7f66b8f7f5-sp47w) which was running for hours could not get results because there was missing CPU data. 

```
  Type     Reason                   Age                     From                       Message
  ----     ------                   ----                    ----                       -------
  Warning  FailedGetResourceMetric  30s (x17584 over 3d3h)  horizontal-pod-autoscaler  missing request for cpu
```

Well, there was another pod  (prod-api-blue-test-connection) which was completed from a helm test. Turns out it was trying to use the latter to determine cpu, which of course it can't. Resolved by removing the test-connection pod

**What you expected to happen**:

Should show data from metrics.k8s.io. (metrics-server) etc. However the metrics.k8s.io API was not receiving a request and immediately failing. 

**How to reproduce it (as minimally and precisely as possible)**:

Create Deployment & HPA (CPU based), and then create a completed pod. i.e.
`prod-api-blue-7f66b8f7f5-sp47w`
and `prod-api-blue-test` and see if HPA is able to get data

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.4

- Cloud provider or hardware configuration: AWS on kops 1.16

- OS (e.g: `cat /etc/os-release`): 

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux ip-10-189-24-201 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Dogstarsuper** [comment]
same issue.
Environment:
centos 7.4 / Kubernetes  1.14.1 /metrics-server  0.3.4
Kubernetes  installed with kubeadm
metrics-server installed with yaml from github.
kubectl top nodes  &  kubectl top pods   work fine.
metrics-server command:  
`  /metrics-server 
            - --kubelet-preferred-address-types=InternalIP
            - --kubelet-insecure-tls`
test pod running with
`resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
`

**Comment by jackfarzan** [comment]
Having the same issue on EKS Kubernetes v1.15. HPA is `autoscaling/v2beta1`. Metrics server is running as expected, but HPA cannot get CPU usage.
