### ISSUE TITLE
[Flaky tests] "command terminated with exit code 1" errors in pull-kubernetes-e2e-kind

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#87953]
**Which jobs are flaking**:
pull-kubernetes-e2e-kind
pull-kubernetes-e2e-kind-ipv6

**Which test(s) are flaking**:
* [sig-storage] PersistentVolumes-local ...
* [sig-storage] EmptyDir volumes pod should support shared volumes between containers
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] ...

**Reason for failure**:
Sample output from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87759/pull-kubernetes-e2e-kind/1226150446263963649:
```
Feb  8 14:47:47.932: INFO: Could not find CSI Name for in-tree plugin kubernetes.io/local-volume
ï¿½[1mSTEPï¿½[0m: Creating block device on node "kind-worker" using path "/tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc"
Feb  8 14:47:59.969: INFO: ExecWithOptions {Command:[nsenter --mount=/rootfs/proc/1/ns/mnt -- sh -c mkdir -p /tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc && dd if=/dev/zero of=/tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc/file bs=4096 count=5120 && losetup -f /tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc/file] Namespace:volumemode-193 PodName:hostexec-kind-worker-ztr6n ContainerName:agnhost Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
Feb  8 14:47:59.969: INFO: >>> kubeConfig: /root/.kube/kind-test-config
Feb  8 14:48:01.217: INFO: exec kind-worker: command:   mkdir -p /tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc && dd if=/dev/zero of=/tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc/file bs=4096 count=5120 && losetup -f /tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc/file
Feb  8 14:48:01.217: INFO: exec kind-worker: stdout:    ""
Feb  8 14:48:01.217: INFO: exec kind-worker: stderr:    "5120+0 records in\n5120+0 records out\n20971520 bytes (21 MB, 20 MiB) copied, 0.266407 s, 78.7 MB/s\nlosetup: /tmp/local-driver-fcf02f2d-41af-415f-9b2c-3cf478fda9fc/file: failed to set up loop device: No such file or directory\n"
Feb  8 14:48:01.217: INFO: exec kind-worker: exit code: 0
Feb  8 14:48:01.217: FAIL: Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "command terminated with exit code 1",
        },
        Code: 1,
    }
    command terminated with exit code 1
occurred
```

**Anything else we need to know**:
Started ~1/7:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-01-15&ci=0&pr=1&text=command%20terminated%20with%20exit%20code%201%22&job=-e2e-

Continues to today:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=command%20terminated%20with%20exit%20code%201%22&job=-e2e-

/cc @BenTheElder 
/sig storage

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1248 cc @pohly @msau42

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1248#issuecomment-585939103 :crossed_fingers:

**Comment by BenTheElder** [comment]
looks green after https://github.com/kubernetes/test-infra/pull/16278

we'll want to tweak that setup slightly but I think it should hold now. we're also looking at https://github.com/kubernetes-sigs/kind/issues/1333 for follow up

**Comment by BenTheElder** [comment]
tentatively closing https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&width=5
/close
