### ISSUE TITLE
kubectl auth can-i --list does not show non-namespaced resources

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kubernetes#87955]
I have a use case with service account called "steve" running in the default namespace with a role binding to a cluster role allowing read access to nodes and /metrics.

As far as I know, nodes and /metrics are not namespaced.
Therefore I would expect to see them in the output for kubectl auth can-i --list when applied for any namespaces.  This is not the case.  

Case 1)
I see nodes and /metrics when listing actions the steve service account can perform in the default namespace. So far so good!
![image](https://user-images.githubusercontent.com/20993422/74091962-e7515c80-4a8b-11ea-9565-2f1bd3ebce67.png)

Case 2) I don’t see nodes and /metrics when listing actions the steve service account can perform in the kube-system namespace. Did I miss something?
![image](https://user-images.githubusercontent.com/20993422/74091972-17006480-4a8c-11ea-8ffe-2ed9a0bb3034.png)

**Comment by stevebail** [comment]
/sig api-machinery
@liggitt

**Comment by liggitt** [comment]
That means you have a role which grants those resources and non-resource urls within the default namespace, and not within the kube-system namespace. The authorization layer doesn't have knowledge of whether a particular resource is namespaced or not, the resource names are opaque strings as far as it is concerned.
