### ISSUE TITLE
 pull-kubernetes-e2e-gce has begun to care about "us-west3"

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kubernetes#87962]
I've started to notice some strange errors today while reviewing results from various `pull-kubernetes-e2e-gce` tests in spyglass.
They look something like below and don't seem to be the result of a janky PR because I'm seeing them consistently across PRs (and repos).

```
ERROR: (gcloud.compute.instances.list) Some requests did not succeed:
W0209 15:29:45.112]  - Invalid value for field 'zone': 'us-west3-a'. Unknown zone.
W0209 15:29:45.112]  - Invalid value for field 'zone': 'us-west3-b'. Unknown zone.
W0209 15:29:45.112]  - Invalid value for field 'zone': 'us-west3-c'. Unknown zone.
W0209 15:29:45.112] 
W0209 15:29:50.546] ERROR: (gcloud.compute.instances.list) Some requests did not succeed:
W0209 15:29:50.546]  - Invalid value for field 'zone': 'us-west3-a'. Unknown zone.
W0209 15:29:50.546]  - Invalid value for field 'zone': 'us-west3-b'. Unknown zone.
W0209 15:29:50.546]  - Invalid value for field 'zone': 'us-west3-c'. Unknown zone.
W0209 15:29:50.546] 
I0209 15:30:08.945] Deleting firewall rules remaining in network e2e-62db3709f4-674b9: 
```
The snippet is from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87949/pull-kubernetes-e2e-gce/1226526557565095936/
but I also saw this here https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86799/pull-kubernetes-e2e-gce/1226568085956202498/ .

**Comment by liggitt** [comment]
This is now resolved

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/test-infra/issues/16202
