### ISSUE TITLE
CSINodeInfo registration timeout can kill kubelet before API server is available

### ISSUE THREAD

**Issue by SerialVelocity** [kubernetes/kubernetes#87964]
**What happened**:
Upgraded from 1.16.6 to 1.17.2 and `kubelet` will no longer start on control-plane hosts.

It fails with:
```
F0209 21:12:03.029910    4631 csi_plugin.go:281] Failed to initialize CSINodeInfo after retrying
```

**What you expected to happen**:
`kubelet` to start, static pods to launch, `kubelet` to connect to `kube-apiserver` in the static pod

**How to reproduce it (as minimally and precisely as possible)**:
Have the `kube-apiserver`, `kube-controller-manager`, `kube-proxy`, etc in the static pod manifest folder. Try to start the `kubelet` with the container images not preloaded on the host.

Just in case it is needed:
 - `containerd` is used as the backend
 - `kubelet` is run using `podman`

**Anything else we need to know?**:
This looks to be two things interacting poorly:
1- It takes a long time for static pods to be created for the first time when the `kubelet` can't talk to `kube-apiserver` yet.
2- The new CSI migration code force terminates `kubelet` causing these log lines to appear in `containerd`:
```
time="2020-02-09T21:08:33.519966472Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:43a8fe7d2382002ffbd9e249f8f83eb9fb8d656907c83fcf4c35c1b1068ad4ae: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount755552492: context canceled: unknown" key="extract-346448313-0TU_ sha256:e8bb55ebf09d64b814cddc95b32a3beea13ce15b488996e7d8a072fcd50aa864"
time="2020-02-09T21:08:33.664729729Z" level=error msg="PullImage "gcr.io/google-containers/hyperkube-amd64:v1.17.2" failed" error="failed to pull and unpack image "gcr.io/google-containers/hyperkube-amd64:v1.17.2": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:43a8fe7d2382002ffbd9e249f8f83eb9fb8d656907c83fcf4c35c1b1068ad4ae: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount755552492: context canceled: unknown"
```

@davidz627 @liggitt It looks like https://github.com/kubernetes/kubernetes/pull/74835 introduced this new fatal error.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.2
- Cloud provider or hardware configuration: Bare-metal
- OS (e.g: `cat /etc/os-release`): Fedora 31.20191127.1 (CoreOS preview)"
- Kernel (e.g. `uname -a`): 5.3.12-300.fc31.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by SerialVelocity** [comment]
Actually, probably:
/sig node

**Comment by liggitt** [comment]
The referenced PR was added in 1.14, so that interaction is not new. What is likely new is the size increase of hyperkube in 1.17 (xref https://github.com/kubernetes/kubernetes/pull/84662). When not pre-pulled, this can increase the time it takes to start hyperkube for the first time.

Does the image pull make progress as the kubelet restarts/retries?

**Comment by liggitt** [comment]
It might make sense for the initializeCSINode() method to:
* first wait to successfully talk to the kube apiserver *at all*, perhaps indefinitely
* after successfully talking to the kube apiserver, *then* try to register the CSINode object with backoff, and fail if it cannot do that successfully

**Comment by SerialVelocity** [comment]
> Does the image pull make progress as the kubelet restarts/retries?

It doesn't seem to. Once the connection to containerd is closed, it cancels the context. Otherwise I would expect this to succeed eventually if the pull happened in the background.

> It might make sense for the initializeCSINode() method to
> ...

That sounds reasonable to me assuming it isn't blocking the static pod creation code. Do you happen to know why it takes a very long time for the static pod creation code to be called? I would expect the pods to be created very soon after the kubelet is started.

**Comment by liggitt** [comment]
> Do you happen to know why it takes a very long time for the static pod creation code to be called? I would expect the pods to be created very soon after the kubelet is started.

Pulling the image and starting the processes for those pods happens immediately (from the containerd logs, you can see the image pull happening... it just doesn't complete in time before the independent kubelet logic to register the CSI node info times out).

**Comment by SerialVelocity** [comment]
Ah, yes. I just upgraded a couple of days ago so I didn't check whether I still saw the 2 minute delay in creating the "pod sandboxes" (this is before the pull even happens). It now is only a 23 second delay:

containerd:
```
time="2020-02-10T00:07:39.211822304Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:kube-apiserver...
```

kubelet:
```
I0210 00:07:16.599593    1465 server.go:416] Version: v1.17.2
...
I0210 00:07:38.387785    1465 kuberuntime_manager.go:211] Container runtime containerd initialized, version: v1.2.8, apiVersion: v1alpha2
```

**Comment by davidz627** [comment]
ack, I like the idea

> first wait to successfully talk to the kube apiserver at all, perhaps indefinitely
> after successfully talking to the kube apiserver, then try to register the CSINode object with backoff, and fail if it cannot do that successfully

Will work on a fix today and cherry-pick it as necessary
