### ISSUE TITLE
[Failing Test] gce-ubuntu-master-containerd (ci-kubernetes-e2e-ubuntu-gce-containerd)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#87989]
**Which jobs are failing**:
`gce-ubuntu-master-containerd (ci-kubernetes-e2e-ubuntu-gce-containerd)`

**Which test(s) are failing**:
```
[sig-auth] PodSecurityPolicy should allow pods under the privileged policy.PodSecurityPolicy
```
```
[sig-node] RuntimeClass should run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler]
```

**Since when has it been failing**:
`2nd Feb 05:22 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-containerd

**Reason for failure**:
see https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1226919914875392001

**Anything else we need to know**:
/milestone v1.18
/cc @kubernetes/ci-signal 
/sig auth
/sig node
/priority critical-urgent

**Comment by liggitt** [comment]
For `PodSecurityPolicy should allow pods under the privileged policy`:

> Running a privileged pod
> Running a HostPath pod
> Running a HostNetwork pod
> Running a HostPID pod
> Running a HostIPC pod
> Running a custom AppArmor profile pod
> Feb 10 17:44:07.267: FAIL: Unexpected error:
>     <*errors.errorString | 0xc0000d9fa0>: {
>         s: "timed out waiting for the condition",
>     }
>     timed out waiting for the condition

https://github.com/kubernetes/kubernetes/blob/bb3cddc24f5c7d02b81573453f934826fc731401/test/e2e/auth/pod_security_policy.go#L171-L178

https://github.com/kubernetes/kubernetes/blob/bb3cddc24f5c7d02b81573453f934826fc731401/test/e2e/auth/pod_security_policy.go#L376-L379

https://github.com/kubernetes/kubernetes/blob/bb3cddc24f5c7d02b81573453f934826fc731401/test/e2e/framework/skipper/skipper.go#L179-L180

**Comment by dims** [comment]
/priority important-soon

this is a new job :) it's in informing, not blocking

**Comment by dims** [comment]
a new presubmit in https://github.com/kubernetes/test-infra/pull/16213 will help with coming up with a fix for this issue

**Comment by dims** [comment]
Apparent fix in `kind` was https://github.com/kubernetes-sigs/kind/pull/914

**Comment by dims** [comment]
fyi, the fix for the 2 failures are across the following PR(s):
- https://github.com/kubernetes/test-infra/pull/16221
- https://github.com/kubernetes/kubernetes/pull/88033
- https://github.com/kubernetes/kubernetes/pull/88010

**Comment by droslean** [comment]
job is green. Closing... 
/close

**Comment by dims** [comment]
thanks @droslean !

**Comment by harshanarayana** [comment]
Noticed this issue again on a [new job](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90690/pull-kubernetes-e2e-kind-ipv6/1256668931205107712)

```bash
May  2 19:55:03.373: FAIL: Error creating Pod
Unexpected error:
    <*errors.StatusError | 0xc001a17c20>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
skipped 261 lines unfold_more
Latency metrics for node kind-worker2
May  2 19:55:12.400: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "runtimeclass-3870" for this suite.
• Failure [9.246 seconds]
[sig-node] RuntimeClass
test/e2e/common/runtimeclass.go:39
  should run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler] [It]
  test/e2e/common/runtimeclass.go:55
skipped 41067 lines unfold_more
[Fail] [sig-node] RuntimeClass [It] should run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler] 
test/e2e/framework/pods.go:95
Ran 594 of 5094 Specs in 1140.902 seconds
FAIL! -- 593 Passed | 1 Failed | 0 Pending | 4500 Skipped

```
