### ISSUE TITLE
Node performance tests are continuously failing

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#87988]
**Which jobs are failing**:
ci-kubernetes-node-kubelet-flaky

**Which test(s) are failing**:
```
[sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads NAS parallel benchmark (NPB) suite - Embarrassingly Parallel (EP) workload
[sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads NAS parallel benchmark (NPB) suite - Integer Sort (IS) workload
[sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads TensorFlow workload
```

**Since when has it been failing**:
A long time ago: https://github.com/kubernetes/kubernetes/pull/76799, https://github.com/kubernetes/kubernetes/pull/78548

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-flaky

**Reason for failure**:
These tests create workloads that each requires 16 CPU, but the nodes only have 1 CPU. In sys log you can find errors like `Message:Pod Node didn't have enough resource: cpu, requested: 15000, used: 0, capacity: 800 Reason:OutOfcpu`. 

[Job config](https://github.com/kubernetes/test-infra/blob/5847890219321e49274e9193d99847d71dc873ac/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L178)
[Node config](https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config.yaml) (default machine type is n1-standard-1)

/sig node
/sig testing

**Comment by boddumanohar** [comment]
I dont think theres a way to make this test pass on testgrid.

**Comment by roycaihw** [comment]
I had some in progress work to bump the machine side to n1-standard-16 in test-infra, which should fit the workload. Are you suggesting that it won't help, or people won't allow tests using such a big machine? I think the latter is more likely to be true for cost reason. 

On the other hand, if we couldn't make these tests pass, IMO we should stop running them in testgrid to save some cost.

**Comment by alejandrox1** [comment]
I accidentally started looking into this issue as well on https://github.com/kubernetes/kubernetes/issues/91263
I see that this one is a bit stale so hope you dont mind if i close as duplicate
/close
