### ISSUE TITLE
Dump list of test containers on Windows test nodes

### ISSUE THREAD

**Issue by pjh** [kubernetes/kubernetes#88011]
When a test run completes it would be useful to have a list of all the test containers that were pulled onto the node - see https://github.com/kubernetes-sigs/windows-testing/pull/126#discussion_r377413135 for the motivation. Let's add a call to `docker image list` at https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L249 - just after `export-windows-docker-event-log` seems like it should work fine. We can dump the output to a file and gather it from each node just like we do for docker.log.

**Comment by pjh** [comment]
/assign @YangLu1031 

Yang, we should also consider adding `docker image list` to the log gathering that the GCE diagnostics tool does :)

**Comment by pjh** [comment]
/reopen

@YangLu1031 in the [most recent passing run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1241893161664516097) of our [tests](https://testgrid.k8s.io/google-windows#gce-windows-2019-master&width=20) on 03-22 I don't see `docker_images.log` in the artifacts for the Windows node. Can you check on this? Did we miss a step or is something failing?

**Comment by YangLu1031** [comment]
Oh, missed to add the new log file to collector list.

**Comment by YangLu1031** [comment]
Added the fix: https://github.com/kubernetes/kubernetes/pull/89634
