### ISSUE TITLE
Measure our 1.0 scaling goals under different cluster configurations

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#8801]
Our 1.0 scaling goals as described in #3952, #4521, and #3954 are for 100 nodes with 30 pods/node.

It would be interesting to see what happens when we use more nodes and fewer pods/node, since I suspect few people will need 30 pods/node while some may want more than 100 nodes. For example, I would suggest trying
* 200 nodes and 10 pods/node
* 200 nodes and 15 pods/node
* 250 nodes and 10 pods/node
* 300 nodes and 10 pods/node

BTW we should make it clear when we talk about N pods/node whether we are or are not including cluster add-on pods (like the ones used for logging and monitoring).  

We aren't changing the 1.0 performance goal, but it would be good to understand the space of configuations a little better, if we have time.

@wojtek-t @fgrzadkowski (feel free to reassign, and this is not critical for 1.0, just a "nice to have" so we can possibly give more than one data point in our announcement for 1.0)

**Comment by davidopp** [comment]
Also, we could provide additional datapoints on what happens if you use a larger master (e.g. n1-standard-8 instead of n1-standard-4).

**Comment by davidopp** [comment]
This is definitely post-1.0; nobody should spend time on it before that.

When we do look into it, we need to look into the scaling characteristics of the various cloud providers (and flannel) as well. It's not just API server and etcd scalability that are likely to be issues.

**Comment by bprashanth** [comment]
So i noticed our scalability tests on jenkins are using an n1-standard-8. Did I miss the notification of an upgrade, I thought we settled on a standard-4 in https://github.com/GoogleCloudPlatform/kubernetes/issues/6454?

**Comment by davidopp** [comment]
Thanks for noticing this! I was under the same impression as you. @fgrzadkowski

**Comment by davidopp** [comment]
@fgrzadkowski is going to switch the scalability Jenkins back to n1-standard-4. 

I forgot that he and I had briefly discussed this; the argument was that it's reasonable to ask people with large clusters to run beefier masters, which seemed reasonable to me. But I think it would be good to see how n1-standard-4 compares. He also pointed out that when he reported the latest stats, he mentioned that it was on 8-core master (which I overlooked):
https://github.com/GoogleCloudPlatform/kubernetes/issues/4521#issuecomment-110439025

**Comment by fgrzadkowski** [comment]
Please see https://github.com/GoogleCloudPlatform/kubernetes/issues/4521#issuecomment-111423515 with the results for 4 core master.

**Comment by erictune** [comment]
@wojtek-t can this be closed now that v1.0 has been released?
