### ISSUE TITLE
Kube-apiserver token authentication is case-sensitive for IPv6

### ISSUE THREAD

**Issue by JerrySunWRS** [kubernetes/kubernetes#88026]
**What happened**: 
Set up Kubernetes cluster with OIDC parameters on the kube-apiserver. 
Deploy Dex for authentication and obtain a token for kube-apiserver
create a kubernetes context and user for authentication with Dex
run "kubectl get pods", authentication fails
the following is seen in the logs:
2020-02-10T20:19:54.523842199Z stderr F E0210 20:19:54.523584 1 oidc.go:232] oidc authenticator: initializing plugin: oidc: issuer did not match the issuer returned by provider, expected "https://[2620:10A:A001:A103::1085]:30556/dex" got "https://[2620:10a:a001:a103::1085]:30556/dex"

**What you expected to happen**:
"kubectl get pods" should finish without errors, since IPv6 addresses are not case sensitive.

**How to reproduce it (as minimally and precisely as possible)**:
Set up Kubernetes cluster with OIDC parameters on the kube-apiserver, specifying the IPv6 address in upper case for "oidc-issuer-url"
Deploy Dex for authentication and obtain a token for kube-apiserver, this time specifying the issuer url in lower case.
create a kubernetes context and user for authentication with Dex
run "kubectl get pods", authentication fails

**Anything else we need to know?**:
Deployment in IPv6 environment

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2020-02-01T09:48:34Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): Linux controller-0 3.10.0-1062.1.2.el7.1.tis.x86_64 #1 SMP PREEMPT Sat Feb 1 05:47:06 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico v3.6.2
- Others:

**Comment by liggitt** [comment]
The [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#Terminology) explicitly says the issuer is case-sensitive:

> Issuer Identifier
> Verifiable Identifier for an Issuer. An Issuer Identifier is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.

> The following Claims are used within the ID Token for all OAuth 2.0 flows used by OpenID Connect:
> iss
> REQUIRED. Issuer Identifier for the Issuer of the response. The iss value is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.

**Comment by liggitt** [comment]
Are you encountering a scenario where normalization makes it impossible to configure the issuer to match, or was it just unexpected that the value would be case-sensitive?

**Comment by JerrySunWRS** [comment]
It was just unexpected that the value would be case-sensitive given that IPv6 addresses are not. I will close this bug.
