### ISSUE TITLE
Scheduler: Add tests for server.go for close-to-full E2E setup

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#88028]
We are lacking tests that exercise a full scheduler setup, all the way from config files and command line flags to what plugins end up instantiated.

The best candidate for this is `cmd/kube-scheduler/app/server.go`, but this needs tweaking. Basically, we need to split `runCommand` in two functions: `setupCommand` and the already existing  `Run` (which already has a test). Maybe we can have the test in `cmd/kube-scheduler/app/testing` as well.

Configuration can be written to files just like we do in `cmd/kube-scheduler/app/options/options_test.go` and args can be passed as parameters.

/sig scheduling
/help
/kind cleanup

**Comment by skilxn-go** [comment]
/assign
I'm interested in e2e test. I can take it, too.

**Comment by alculquicondor** [comment]
Just to avoid too much burden on you, let's leave this open to other contributors. WDYT?

**Comment by skilxn-go** [comment]
Sure, I will unassign it.

**Comment by notpad** [comment]
@alculquicondor I have a question about what shoud be checked for the instantiated plugins, the name and weight or the args of the plugins?

**Comment by alculquicondor** [comment]
Just names and weights to start. But args could be tested once #88027 is fixed

**Comment by alculquicondor** [comment]
/reopen

Could you add some tests for `--algorithm-provider`, `--policy-config-file` and related?

**Comment by notpad** [comment]
@alculquicondor Sure

**Comment by alculquicondor** [comment]
/reopen

#88027 was finalized, so we can add one test to exercise plugin config

**Comment by notpad** [comment]
Does that mean we can use `scheduler.WithBuildFrameworkCapturer` to get the Plugin config? But we don't have direct acess to the scheduler.new unless we add this argument to `Setup`

**Comment by alculquicondor** [comment]
that's a good point. Maybe we can add an unexported package variable to do so.

**Comment by alculquicondor** [comment]
@notpad can you do that?
