### ISSUE TITLE
Scheduler: Add compatibility tests for framework configuration

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#88027]
`pkg/scheduler/apis/config/testing` has compatibility tests for Policy v1.

We are lacking similar tests for other options of `scheduler.New`, such as:

- [x] `WithFrameworkPlugins`: This can be added right away to test that default plugins can be disabled, changed order, etc.
- [ ] `WithFrameworkPluginConfig`: This one is trickier, as it requires a new method in `Framework` to expose all configurations and a new method in `Plugin` so that they can say which args they used.

/sig scheduling
/help
/kind cleanup

**Comment by alculquicondor** [comment]
@skilxn-go, you can work on the first one.

I'll have a PR soon that should clarify how the second one should be done.

**Comment by skilxn-go** [comment]
@alculquicondor I have sent a pr for the first one.
And I'm working on the second one, I think it's better to keep 2 pr for this issue? If so, PTAL at the first one, thanks.

**Comment by alculquicondor** [comment]
Yes, 2 PRs is ideal. I'll review later today.

**Comment by skilxn-go** [comment]
I have one small question that do I need to mock some fake plugins for testing `WithFrameworkPluginConfig`, or just testing the default plugins?

**Comment by alculquicondor** [comment]
You should use the existing plugins, because these are compatibility tests.

**Comment by skilxn-go** [comment]
Okay 😃

**Comment by skilxn-go** [comment]
Actually, I think adding a new method such as `BuildArgs` to `Plugin` interface is a little redundant. In fact, most plugins don't need any arg for building them, so we are talking about adding a 
new method that needs to be implemented by all of the existing and coming plugins. And users who write out-of-tree plugins also hardly have the need for using this method.
IMO, it would be more meaningful to move [getExtensionPoints](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/framework.go#L101) up to the `FrameWork` interface.
Then by this method, we can simply implement `BuildArgs` for default plugins who actually need args.
WDYT?

**Comment by alculquicondor** [comment]
`getExtensionPoints` should remain unexported because it provides pointers. However, I agree that `BuildArgs` might be too much to ask for all plugins. Instead, we can add a new interface and then plugins can opt-int. Not sure if we should follow this extension pattern https://github.com/kubernetes/kubernetes/blob/9c1543263bac9cb12272b271d2e2f93e45f07e53/pkg/scheduler/framework/v1alpha1/interface.go#L256

Any thoughts @ahg-g?

**Comment by alculquicondor** [comment]
On the other hand, simply returning `nil` doesn't seem like much.

**Comment by skilxn-go** [comment]
Sure, then I will add `BuildArgs` like what we want before(add this method to `Plugin` interface), and if there is any better idea later, please let me know.

**Comment by ahg-g** [comment]
I think we should just add it to the plugins that actually have args, this will require custom code in the test, but I think it is better than having all plugins implement a function means something to only 1% of them.

**Comment by skilxn-go** [comment]
@ahg-g Thanks, but now there is a problem that we can't get the registered plugins with current API.
So, I'm not sure if we can just implement the `ListPluginArgs` method in `FrameWork` with some reflect code for checking if one plugin has implement `BuildArgs` method? This could help us with keeping the `Plugin` interface clean.
cc @alculquicondor

**Comment by ahg-g** [comment]
you don't need to check if it implements BuildArgs, since this is for testing, we can hardcode which plugins should have their args verified.

**Comment by ahg-g** [comment]
The test will not be pretty, but I think it is worth the tradeoff.

**Comment by skilxn-go** [comment]
Do you mean that we don't test the default plugins, but define some custom plugins in the test file?
And we don't need the ListPluginArgs method anymore, am I right?

**Comment by alculquicondor** [comment]
@ahg-g and I discussed this offline and arrived to this conclusion:

- For the compatiblity test, we can mock `Configurator.buildFramework` (added in #88285) to capture the arguments the configuration that is being passed. This can also be used by with #88028
- We want another test for `framework/v1alpha1/framework_test.go` that checks the build args for the in-tree plugins accessing the internal pointers.

These 2 tests should cover the whole stack. Sorry for the back-and-forth. Sometimes it's useful to see a full PR to realize that the initial idea wasn't good enough. Thanks a lot for it.

**Comment by skilxn-go** [comment]
Sure, that sounds much more clear, thanks. :D

**Comment by skilxn-go** [comment]
@alculquicondor One more question, the `Configurator.buildFramework` is under package `scheduler`, and the compatibility test is under package `testing`. So for mocking `Configurator.buildFramework`, we need to change `Configurator.buildFramework` to a function variable in `Configurator`, and add a `NewConfigurator` method for it, right？
It will look like:

```go
type buildFrameworkFunc func (schedulerapi.KubeSchedulerProfile) (framework.Framework, error) 
type Configurator struct {
    frameworkBuilder buildFrameworkFunc
    // other fields.
}

func NewConfigurator(f buildFrameworkFunc) {
    if f == nil {
      // use the default one.
    } else {
      // user the mocked one.
    }
}
```

Maybe we can add something like `WithFrameworkBuilder` to `NewConfigurator`, but that's the implementation details. I want to make sure if the design above is proper.

**Comment by alculquicondor** [comment]
Or rather, you could add something like: `WithFrameworkBuilderCapturer`, so that you don't have to mock the whole thing.

**Comment by skilxn-go** [comment]
Got your message in slack, let me reply here. 😄  
`WithFrameworkBuilderCapturer ` sounds good, and do I need to revert the change in #88030? I think `BuildArgs` is not necessary now.

**Comment by alculquicondor** [comment]
I think they will still be useful for the other test:

> We want another test for framework/v1alpha1/framework_test.go that checks the build args for the in-tree plugins accessing the internal pointers.

**Comment by alculquicondor** [comment]
Hello @skilxn-go are you still working on this?

**Comment by skilxn-go** [comment]
@alculquicondor Ah, I'm so sorry that I'm so busy in the last few weeks, but I will send prs fot this issue in this weekend. Sorry for my delay again.
