### ISSUE TITLE
[Flaky test] [sig-storage] Mounted volume expand Should verify mounted devices can be resized

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#88037]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce

**Which test(s) are flaking**:
* `[sig-storage] Mounted volume expand Should verify mounted devices can be resized`

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:
Appears to have started flaking around 1/16
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-01-22&pr=1&job=e2e-gce%24&test=Mounted%20volume%20expand
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=e2e-gce%24&test=Mounted%20volume%20expand

/sig storage
/cc @msau42

**Comment by gnufied** [comment]
I am reopening this to track this down.

/reopen
