### ISSUE TITLE
Update conformance.txt testdata generate command

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/kubernetes#88039]
# Issue
The currently provided command for generating `test/conformance/testdata/conformance.txt` requires bazel, the command should be updated to one which does not require bazel

Currently:
```
bazel build //test/conformance:list_conformance_tests
cp bazel-genfiles/test/conformance/conformance.txt test/conformance/testdata
```

Suggested:
```
go run ./test/conformance/walk.go test/e2e > test/conformance/testdata/conformance.txt
```

/sig testing
/sig architecture
/area conformance

**Comment by BenTheElder** [comment]
We're going to need to update this to verify under `make verify` as well instead of under the bazel "unit tests", ref: https://github.com/kubernetes/enhancements/issues/2420#issuecomment-785663043

I'll work on this.

**Comment by BenTheElder** [comment]
done in https://github.com/kubernetes/kubernetes/pull/99549

**Comment by BobyMCbobs** [comment]
> done in #99549

This is wonderful to see. Thank you @BenTheElder!
