### ISSUE TITLE
managedFields updates for no-op writes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#88031]
**What happened**:

On a resource with managedFields populated, a no-op patch modified the serialization order of managedFields.

**What you expected to happen**:

No-op patches do not result in a write to etcd.

**How to reproduce it (as minimally and precisely as possible)**:

```
# capture watch events
kubectl get deployment -o yaml -w --output-watch-events > watch.txt &

# create deployment
kubectl create deployment foo --image=foo

# record pre-patch state
kubectl get deployment/foo -o yaml > 1.txt

# no-op patch deployment updated resourceVersion, reordered kubectl and kube-controller-manager fields
kubectl patch deployments/foo -n default --type=merge -p '{}'
# record post-patch state
kubectl get deployment/foo -o yaml > 2.txt

# second no-op patch is an actual no-op
kubectl patch deployments/foo -n default --type=merge -p '{}'
# record result
kubectl get deployment/foo -o yaml > 3.txt
```

watch.txt contains:
* the initial ADDED event from kubectl
* MODIFIED events from kube-controller-manager
* one MODIFIED event corresponding to the kubectl patch (from resourceVersion 1704 in 1.txt to resourceVersion 1718 in 2.txt)

`diff 1.txt 2.txt` shows the kubectl and kube-controller-manager managed field sets swapped order:
```diff
--- 1.txt	2020-02-11 19:00:23.447671479 +0000
+++ 2.txt	2020-02-11 19:00:33.832626867 +0000
@@ -12,6 +12,39 @@
     fieldsType: FieldsV1
     fieldsV1:
       f:metadata:
+        f:annotations:
+          .: {}
+          f:deployment.kubernetes.io/revision: {}
+      f:status:
+        f:conditions:
+          .: {}
+          k:{"type":"Available"}:
+            .: {}
+            f:lastTransitionTime: {}
+            f:lastUpdateTime: {}
+            f:message: {}
+            f:reason: {}
+            f:status: {}
+            f:type: {}
+          k:{"type":"Progressing"}:
+            .: {}
+            f:lastTransitionTime: {}
+            f:lastUpdateTime: {}
+            f:message: {}
+            f:reason: {}
+            f:status: {}
+            f:type: {}
+        f:observedGeneration: {}
+        f:replicas: {}
+        f:unavailableReplicas: {}
+        f:updatedReplicas: {}
+    manager: kube-controller-manager
+    operation: Update
+    time: "2020-02-11T19:00:20Z"
+  - apiVersion: apps/v1
+    fieldsType: FieldsV1
+    fieldsV1:
+      f:metadata:
         f:labels:
           .: {}
           f:app: {}
@@ -52,42 +85,9 @@
     manager: kubectl
     operation: Update
     time: "2020-02-11T19:00:20Z"
-  - apiVersion: apps/v1
-    fieldsType: FieldsV1
-    fieldsV1:
-      f:metadata:
-        f:annotations:
-          .: {}
-          f:deployment.kubernetes.io/revision: {}
-      f:status:
-        f:conditions:
-          .: {}
-          k:{"type":"Available"}:
-            .: {}
-            f:lastTransitionTime: {}
-            f:lastUpdateTime: {}
-            f:message: {}
-            f:reason: {}
-            f:status: {}
-            f:type: {}
-          k:{"type":"Progressing"}:
-            .: {}
-            f:lastTransitionTime: {}
-            f:lastUpdateTime: {}
-            f:message: {}
-            f:reason: {}
-            f:status: {}
-            f:type: {}
-        f:observedGeneration: {}
-        f:replicas: {}
-        f:unavailableReplicas: {}
-        f:updatedReplicas: {}
-    manager: kube-controller-manager
-    operation: Update
-    time: "2020-02-11T19:00:20Z"
   name: foo
   namespace: default
-  resourceVersion: "1704"
+  resourceVersion: "1718"
   selfLink: /apis/apps/v1/namespaces/default/deployments/foo
   uid: 677473f7-b132-44d9-9f63-711f3015f326
 spec:
```

second patch was a no-op (`diff 2.txt 3.txt` is empty)

**Anything else we need to know?**:
This was easiest to reproduce with server-side apply enabled at 100%

/assign @apelisse @jennybuckley

**Comment by apelisse** [comment]
> diff 1.yaml 2.yaml shows the kubectl and kube-controller-manager managed field sets swapped order

Can you print the before after fieldmanager? I can't quite figure out what the actual values are.
The code that sorts that is located [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go#L189-L215)

**Comment by liggitt** [comment]
updated to unified diff and attached:
* [1.txt](https://github.com/kubernetes/kubernetes/files/4187573/1.txt)
* [2.txt](https://github.com/kubernetes/kubernetes/files/4187569/2.txt)
* [watch.txt](https://github.com/kubernetes/kubernetes/files/4187572/watch.txt)

**Comment by lavalamp** [comment]
If you explicitly set the field manager to something unique, does it happen every time?

**Comment by lavalamp** [comment]
hm, no, it's definitely an ordering swap

**Comment by apelisse** [comment]
1.txt is not sorted properly, since `kube-controller-manager` should come before `kubectl`.

**Comment by lavalamp** [comment]
We seem to also sort it in a second place: https://github.com/kubernetes/kubernetes/blob/574acbe31025bd7a298eae5dc72b0256a7a9b11a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/capmanagers.go#L80-L91

**Comment by lavalamp** [comment]
Theory: the first time it goes through, the time is accurate to the nanosecond; the second time, it's accurate to the second

**Comment by lavalamp** [comment]
Yeah OK I'm pretty sure that's it, both times are the same second. Serialization drops the fractional part.
