### ISSUE TITLE
Auditing dynamic backend prevents buffered audit backend starting

### ISSUE THREAD

**Issue by EdwinRobbins** [kubernetes/kubernetes#88044]
**What happened**:
If using both runtime specified audit webhook with dynamic backend enabled the buffered backend for the runtime audit-webhook will not be started

**What you expected to happen**:
Both backends should start

**How to reproduce it (as minimally and precisely as possible)**:
- Enable feature gates and api for dynamic auditing
- Supply a runtime config for audit-webhook
- Observe apiserver logs show error that the backend is not started 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.704
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 18.04.3 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):Linux ip-10-0-2-56 4.15.0-1058-aws #60-Ubuntu SMP Wed Jan 15 22:35:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fedebongio** [comment]
/assign @caesarxuchao 
could you please take a look?
