### ISSUE TITLE
Kubelet restart unexpectedly

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#88063]
**What happened**:
my kubelet restart unexpectedly,i find log info has more "Failed to list" info and has fatal error: go of nil func value,and then kubelet restart

Feb 02 17:46:25 mgt15 kubelet[6914]: E0202 17:46:25.752271    6914 reflector.go:126] object-"logging"/"elasticsearch-token-99wc2": Failed to list *v1.Secret: Get https://vip-apiserver.inspur.com:8443/api/v1/nam
Feb 02 17:46:25 mgt15 kubelet[6914]: E0202 17:46:25.760543    6914 controller.go:154] failed 5 attempts to update node lease, will retry after 10s
Feb 02 17:46:25 mgt15 kubelet[6914]: E0202 17:46:25.761608    6914 reflector.go:126] object-"logging"/"default-token-6wh7n": Failed to list *v1.Secret: Get https://vip-apiserver.inspur.com:8443/api/v1/namespace
Feb 02 17:46:25 mgt15 kubelet[6914]: E0202 17:46:25.763387    6914 reflector.go:126] object-"monitoring"/"prometheus-rules": Failed to list *v1.ConfigMap: Get https://vip-apiserver.inspur.com:8443/api/v1/namesp
Feb 02 17:46:25 mgt15 kubelet[6914]: E0202 17:46:25.784045    6914 reflector.go:126] object-"logging"/"service-registry": Failed to list *v1.Secret: Get https://vip-apiserver.inspur.com:8443/api/v1/namespaces/l
Feb 02 17:46:25 mgt15 kubelet[6914]: E0202 17:46:25.841605    6914 reflector.go:126] object-"monitoring"/"prometheus-center": Failed to list *v1.ConfigMap: Get https://vip-apiserver.inspur.com:8443/api/v1/names
Feb 02 17:46:30 mgt15 kubelet[6914]: E0202 17:46:30.935788    6914 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://vip-apiserver.inspur.com:8443/ap
Feb 02 17:46:31 mgt15 kubelet[6914]: E0202 17:46:30.965713    6914 reflector.go:126] object-"logging"/"telegraf-elasticsearch": Failed to list *v1.ConfigMap: Get https://vip-apiserver.inspur.com:8443/api/v1/nam
Feb 02 17:46:31 mgt15 kubelet[6914]: E0202 17:46:30.977697    6914 reflector.go:126] object-"monitoring"/"prometheus-center": Failed to list *v1.ConfigMap: Get https://vip-apiserver.inspur.com:8443/api/v1/names

Feb 02 17:46:32 mgt15 kubelet[6914]: fatal error: go of nil func value
Feb 02 17:46:32 mgt15 kubelet[6914]: goroutine 357 [running]:
Feb 02 17:46:32 mgt15 kubelet[6914]: k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation.(*closableConn).Close(0x4002193f00, 0x0, 0x0)
Feb 02 17:46:32 mgt15 kubelet[6914]:         /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation/connrot
Feb 02 17:46:32 mgt15 kubelet[6914]: k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation.(*Dialer).CloseAll(0x4000bbaea0)
Feb 02 17:46:32 mgt15 kubelet[6914]:         /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation/connrot
Feb 02 17:46:32 mgt15 kubelet[6914]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateNodeStatus(0x40010ce000, 0x54d0978, 0x40010ce648)
Feb 02 17:46:32 mgt15 kubelet[6914]:         /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:383 +0xf0
Feb 02 17:46:32 mgt15 kubelet[6914]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncNodeStatus(0x40010ce000)
Feb 02 17:46:32 mgt15 kubelet[6914]:         /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status

**What you expected to happen**:
kubelet do not restart 

**How to reproduce it (as minimally and precisely as possible)**:
when have more info of "Failed to list"

**Environment**:
- Kubernetes version (use `kubectl version`):v1.14.3
- OS (e.g: `cat /etc/os-release`):Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`):4.15.0-55-generic
- Network plugin and version (if this is a network-related bug):calico3.8.2

**Comment by liggitt** [comment]
fix is in #88079

**Comment by timyinshi** [comment]
@liggitt  thanks，what version is this bug been fixed?

**Comment by liggitt** [comment]
The fix is not yet merged, but I plan to backport the fix to 1.15.x, 1.16.x, 1.17.x (the exact patch versions depend on when the backports are merged)
