### ISSUE TITLE
Ability to have Pod not be removed from endpoints list for service when "preStop" is executing - set to NotReady instead

### ISSUE THREAD

**Issue by ottoyiu** [kubernetes/kubernetes#88085]
**What would you like to be added**: Pod is immediately removed from endpoints list for service after user sends command to delete Pod, even if it has a 'preStop' hook defined. This causes the loadbalancer to remove the endpoint which causes existing connections to immediately close without having a chance to be drained by the application.

See:
https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
"Termination of Pods"

(simultaneous with 3) When the Kubelet sees that a Pod has been marked as terminating because the time in 2 has been set, it begins the pod shutdown process.
If the pod has defined a preStop hook, it is invoked inside of the pod. If the preStop hook is still running after the grace period expires, step 2 is then invoked with a small (2 second) extended grace period.
The processes in the Pod are sent the TERM signal.
(simultaneous with 3) Pod is removed from endpoints list for service, and are no longer considered part of the set of running pods for replication controllers. Pods that shutdown slowly cannot continue to serve traffic as load balancers (like the service proxy) remove them from their rotations.

The chance of behaviour from immediate removal of the endpoint, to changing the endpoint to be under 'notReadyAddresses' instead during the duration of the preStop hook execution would allow for existing connections to continue to function, while new connections to not be directed to the Pod.

**Why is this needed**:
Applications that require the preStop hook to signal to the clients for its imminent death cannot do so, if the client is connected through a Loadbalancer VIP. This seems like a common use-case for preStop hooks and without it, seriously impacts the usefulness of the feature.

Related:
https://github.com/kubernetes/kubernetes/issues/67592

/sig node

**Comment by tedyu** [comment]
```
duration of the preStop hook execution would allow for existing connections to continue to function
```
What's the expected period of time 'notReadyAddresses' is supposed to be effective ?
What if the preStop hook takes long time to finish ?

Thanks

**Comment by ottoyiu** [comment]
@tedyu It would be in the notReady set of addresses until completion, regardless of how long it takes.

AFAIK, this problem was dealt with and was implemented in the form of 'Graceful Termination' within the IPVS proxier. The proxier would put the RealServer into a graceful termination bucket - which marks the IPVS destination to a weight of 0, and waits until all TCP connections have expired before truly deleting the IPVS destination.
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/graceful_termination.go#L166-L179

Unfortunately, by dealing with the problem at that layer, other implementations of loadbalancers would also have to implement something similar.

Perhaps a better idea is that there can be an API change to endpoints, to add a 'terminating' set of addresses instead of overriding the 'notReady' set?

**Comment by huangyanhong** [comment]
but  I meet the same problem，the IPVS destination to a weight of 0 when I delete the pod,but the service request be sent to the  endpoint of a weight of 0  , I don't know why the   weight of 0 'd pod
 still be loaded  in the service 
[root@-k8s-~]# ipvsadm -Ln --stats |grep 9376
  -> 10.233.102.89:9376                112     3762     2508   248919   224466
  -> 10.233.124.47:9376                  0        0        0        0        0
  -> 10.233.124.51:9376                  9      138       89     9118     7762
  -> 10.233.125.84:9376                 28     1386      924    91707    82698
[root@-k8s- ~]# ipvsadm -ln |grep 9376
  -> 10.233.102.89:9376           Masq    1      0          8         
  -> 10.233.124.47:9376           Masq    1      0          8         
  -> 10.233.124.51:9376           Masq    0      0          0         
  -> 10.233.125.84:9376           Masq    1      0          8
