### ISSUE TITLE
Garbage collector deleted wrong resources 

### ISSUE THREAD

**Issue by luisdavim** [kubernetes/kubernetes#88097]
**What happened**:
Today I ran into a problem that seems to be a race condition in the way kube-controller-manager primes the cache before starting the garbage collection. We have a cluster with hundreds of namespaces and thousands of custom resources that have parent child relationships and during a cluster upgrade, whilst replacing the control plane nodes the garbage collector deleted some resources that was not supposed to, they had proper owner references and the owners where live and well.

Looking at the audit logs I can see a spike in the number of objects being deleted by the garbage collector during the upgrade. 

My theory is that the garbage collector started looking at the child resources before their parents were cached, would this be possible?

**What you expected to happen**:
The healthy non orphan resources should not have been deleted 

**How to reproduce it (as minimally and precisely as possible)**:
Not really sure but this seems to be a race condition I think that killing the leader kube-controller-manager in a cluster with a large amount of custom resources that have a parent child relationship is the way to reproduce, I was able to reproduce it 3 times but not constantly. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Azure VMs/Scale sets
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"                                           VERSION="18.04.3 LTS (Bionic Beaver)"                   ID=ubuntu                                               ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"                        VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"                      SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"                             VERSION_CODENAME=bionic                                 UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux cpscu0c52000000 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by liggitt** [comment]
this is likely the same issue as https://github.com/kubernetes/kubernetes/issues/65200

are your owner resources namespaced or cluster-scoped?
are your child resources namespaced or cluster-scoped?
if both are namespaced, are the child resources in the same namespace as the parent?

**Comment by luisdavim** [comment]
Hi, yes, the resources are all namespaced and the parents and children are in the same namespace.

**Comment by luisdavim** [comment]
The description in the issue you linked seems like the opposite of what I'm describing. In my case the children had valid owner references pointing to valid parents that were not marked for deletion. 

The garbage collector deleted resources that should have not been deleted.

**Comment by anyasabo** [comment]
I believe we are also running into this issue in 1.15.3. We have (namespace-scoped) CRs that have a lot of child objects in the same namespace. During k8s cluster maintenace, we see in the API server audit logs that the GC deletes a lot of the children objects, even though the parent CR has not been deleted. We are trying to reproduce it but have been unsuccessful so far, but wanted to chime in on this issue.

**Comment by LittleFox94** [comment]
/remove-lifecycle rotten

Have the same problem with 1.19.0 and rook resources getting deleted, namely the mon deployments and services, the mgr deployments, the osd deployments and, most annoyingly, the mon endpoint configmap and dashboard password secret - making rook create new cluster from scratch and creating a lot of manual work for me to recover the cluster

tell me if you need more information

**Comment by Kyle-Cooley** [comment]
I'm noticing that the garbage collection code has an `absentOwnerCache` that does not appear to be namespace scoped. I was running into this same issue, and had a couple of owners references on cluster scoped resources that were invalid (pointed at a namespace scoped resources). I observed the namespace scoped resources with valid owners references were also being deleted even though the owner still existed.

Shouldn't this cache be namespace scoped? This seems like a potential security vulnerability, though the risk is fairly low. If a user happens to know the uid used as an owners reference in another namespace, then they could add invalid owners references with that same uid on many resources in the namespace they have access to (increasing the chance that they will get the uid in the absent owner cache when the kube controller manager restarts).

Another option would be to validate owners references when they are added and drop/reject invalid references.

**Comment by liggitt** [comment]
> Shouldn't this cache be namespace scoped? 

That fix is in progress in https://github.com/kubernetes/kubernetes/pull/92743

**Comment by reith** [comment]
@luisdavim 

Something similar happened for us a week ago but unfortunately garbage collector requests is filtered from our audit log, so I cannot say it's for sure same phenomenon but I see some DELETE actions on resources that got deleted exactly when incident occurred. Those requests count are zero before and after incident and that spike matches deletionTimestamp on deleted resources (actually they are kept because they have a finalizer set). Whole thing had happened after one of master nodes failed twice and controller-managers on all nodes got restarted.

I see owner resources still existing and there is not deletionTimestamp on them and owner reference is correct indeed. Did owner resources exist after incident for your case?

**Comment by reith** [comment]
For our case server version is `1.16.4` and removed resources have some characteristics:

1) they were being owned (and still owned) by another resource which has `foregroundDeletion` finalizer.
2) some resources are owned like 1) but are additionally owned by another resource, those resources are not deleted.
3) all resources, owner or owned, are namespaced but problem didn't occur for some namespaces. but namespaces it did, all resources owned by an owner got deleted expect the case 2).

**Comment by reith** [comment]
For our case, while deleted resources had proper (in the same subnet) owner, some owned resources in another namespace were incorrectly pointing to another namespace. Is it a possible case that #92743 covers?

**Comment by liggitt** [comment]
> some owned resources in another namespace were incorrectly pointing to resources in another namespace which were owners of deleted resources. Is it a possible case that #92743 covers?

Yes, that is one of the primary issues addressed by that PR

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/92743 was released in 1.20

**Comment by raz3k** [comment]
Will this PR be backported to 1.19 ?

Thanks.

**Comment by liggitt** [comment]
#92743 was a significant modification to the garbage collector, and also changed behavior to consistently clean up children with invalid cross-namespace ownerReferences, so it is unlikely it will be backported.

As part of that work, the https://github.com/kubernetes-sigs/kubectl-check-ownerreferences tool was created to allow identifying invalid ownerReferences, and that tool can be run against older clusters.

**Comment by YYashwanth** [comment]
I had this issue today on AWS EKS 1.16. All the pods in the kube-system namespace were deleted. This is what I see in the controller manager logs

![image](https://user-images.githubusercontent.com/24538941/131518690-a3babecf-3092-4287-88d2-187d82464c05.png)

> I0831 03:01:39.893175       1 garbagecollector.go:518] delete object [apps/v1/ControllerRevision, namespace: kube-system, name: aws-node-6dd8fd9c88, uid: 15f67826-9662-497a-b5f3-aa598523f254] with propagation policy Background

This is the same event for every pod in the kube-system namespace.

Any idea why this happens?
