### ISSUE TITLE
Provide server-side apply capability in client-go

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#88091]
**What would you like to be added**:
Provide an interface to run `Apply` in client-go.

**Why is this needed**:

Currently, `kubectl apply` is the canonical example of how to call server-side apply in a client.

https://github.com/kubernetes/kubernetes/blob/1e12d92a5179dbfeb455c79dbf9120c8536e5f9c/staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go#L388-L433

However, we need to package this into client-go (and clients for other languages...), and document this accordingly.

Related issues:
* First pass https://github.com/kubernetes/kubernetes/pull/86222
* Umbrella issue for server-side apply https://github.com/kubernetes/kubernetes/issues/73723

References:
* Doc on our high-level clients https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/client-package-structure.md
* Doc on our generated clientset https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md

/wg apply
/sig api-machinery

cc @joshmsamuels @kwiesmueller @mariantalla @apelisse @sttts @lavalamp @deads2k

**Comment by julianvmodesto** [comment]
Some suggestions from @lavalamp from the sig-apimachinery meeting:
- Structured objects won't work since server-side apply accepts `yaml` as the format. Pointers for fields to capture `nil` in our generated resource structs is not great for usability.
- Thus, an interface could take `yaml` as a format
- A DynamicClient Apply interface that accepts a map or resource with setters and getters, and converts to `yaml` could work

**Comment by julianvmodesto** [comment]
@jennybuckley mentioned a related issue: patchType only has a content-type for yaml, but we need a content-type for json, too. cc @mariantalla 

So some interface(s) ideally supports yaml + json formats.

**Comment by julianvmodesto** [comment]
@apelisse mentioned we need some strategy to support clients that use structured objects and CRDs. Related: https://github.com/kubernetes-sigs/controller-runtime/issues/347

**Comment by lavalamp** [comment]
@deads2k is interested in this.

**Comment by lavalamp** [comment]
> So some interface(s) ideally supports yaml + json formats.

YAML is a superset of JSON, so we don't need both.

**Comment by lavalamp** [comment]
/assign

Taking an AI to at least write up some options for this.

**Comment by lavalamp** [comment]
Here's the options as I see them: https://docs.google.com/document/d/1_Oo9YTjjV6SQYtCP1k3gTqzwRkaKY1phGULz-G49cIk/edit (shared with the sig & working group lists).

**Comment by gavinshark** [comment]
Hi @julianvmodesto ,

Glad to see the server-side apply capability in client-go. This is just what our team is looking for right now.
Could you tell me if the feature has been added in current version(v0.19.0)?
If not, is there any ETA?

Thank you!

Best Regards,
Gavin

**Comment by kwiesmueller** [comment]
Hey @gavinshark 
we are still investigating the best approach to build a typed client.
If you want to look at the options we're considering, you can take a look at this document: https://docs.google.com/document/d/1K5rdbS-4tPgQezIy-M8ATo0yl_QXnYEWbHDfsI_QkKI/edit#heading=h.45j5nkz9or5v

Feel free to leave feedback on it or stop by on [our Slack Channel](https://kubernetes.slack.com/archives/C0123CNN8F3).
Currently there is no specific (typed) client for apply in v1.19, but you can still use SSA by sending YAML and JSON through client-go by specifying the ApplyPatch type.

Like:
```go
client.Patch(ctx, name, types.ApplyPatchType, yourJsonOrYaml, metav1.PatchOptions{
        FieldManager: "your-fieldmanager",
})
```
I'll lookup a concrete example if you like.

**Comment by gavinshark** [comment]
Hi @kwiesmueller 

Thank you for your quick reply.
Kind to see a unstructured types' example in your convenience.

(We want a simple way to upgrade from agent-v1 version to agent-v2 version. 
We have namespace-v1.yaml, cluster-role-v1.yaml, deployment-A-v1.yaml and configuremap-v1.yaml now.
And we **may** have namespace-v2.yaml, cluster-role-v2.yaml, deploymet-A-v2.yaml, configuremap-v2.yaml and deployment**-B**-v2.yaml in the future.
Our plan is to apply all v2 yaml files to upgrade from v1. And even version-N yaml files to upgrade from version-M in the future.)

Thank you very much

**Comment by julianvmodesto** [comment]
Oops, this is a duplicate, tracked here https://github.com/kubernetes/kubernetes/issues/9598

**Comment by cbandy** [comment]
#95989
