### ISSUE TITLE
Validate Plugin and PluginConfig for KubeSchedulerConfiguration

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#88093]
Today, we are doing validation of the framework configuration (plugins and plugin config) during the framework instantiation (`framework.NewFramework`) which happens during scheduler instantiation (`scheduler.New`).

This was a a good first step during the Framework migration. However, as we prepare to move component config to beta (aiming for 1.19), we should start replicating some of the validation in `pkg/scheduler/apis/config/validation`.

For this, we probably need to move the framework registry instantiation earlier in the setup for `cmd/kube-scheduler/app`.

/kind cleanup
/sig scheduling

**Comment by alculquicondor** [comment]
We could further validate specific plugin configs if we decide to do #87784

**Comment by ahg-g** [comment]
We can do some validation for Plugin and PluginConfig of KubeSchedulerConfiguration, but I don't think we should remove the one done at Framework instantiation for two reasons: 1) external components like CA create a Framework instance directly, 2) the logic that creates the final set of plugins (i.e., after disabled plugins are removed and the special * symbol is processed) is done at a later stage.

**Comment by alculquicondor** [comment]
That is true. I updated the issue description. That said, I don't plan to work on this until profiles land.

**Comment by alculquicondor** [comment]
I'll defer this to the next release

**Comment by alculquicondor** [comment]
I'll tackle this next, after #90657, but just focusing in PluginArgs.
I plan to call the validation functions that will live in `pkg/scheduler/apis/config/validation` from the relevant places in the framework.

**Comment by alculquicondor** [comment]
/unassign
/assign @pancernik 

/close
fixed in #91241

**Comment by alculquicondor** [comment]
/reopen

Actually, we moved the validation logic, but we are not using it in `ValidateKubeSchedulerConfiguration` yet.

**Comment by alculquicondor** [comment]
/help

This is not necessarily suitable for a new contributor, but I'm willing to guide. cc @pancernik just in case you still want to take it.

**Comment by pancernik** [comment]
I'm still on it.

/assign @pancernik 
/remove-help

**Comment by chendave** [comment]
@alculquicondor 

> we moved the validation logic, but we are not using it in ValidateKubeSchedulerConfiguration yet.

What do mean the validation logic here?  I saw  only the QueueSort plugin config is validate separately here, 
https://github.com/kubernetes/kubernetes/blob/6e0e64c992439c66ec63a02e6d517928acc580d5/pkg/scheduler/profile/profile.go#L89

Other than that, is there anything we need to do for this issue?

**Comment by alculquicondor** [comment]
API validation is missing a lot of checks, including the validation for pluginConfigs.

https://github.com/kubernetes/kubernetes/blob/6e0e64c992439c66ec63a02e6d517928acc580d5/pkg/scheduler/apis/config/validation/validation.go#L83

It's useful to have all validations in a single canonical place.

**Comment by chendave** [comment]
/unassign @pancernik
as we haven't heard back for quite a long time.

/assign
I agree this is an area we can improve.

**Comment by chendave** [comment]
We have couple of things to do before closing this issue, 

* [ ] Move noderesource plugin args validation to apis/config/validation, currently, the validation logic is kept in the pkg/scheduler/framework/plugins instead.
* [ ] Consolidate all the validation logic if possible into one place, for example `QueueSort` plugin config could be done in the `validation` package instead. 
* [ ] Drop unnecessary calling of validation, as an example, during the process of  `Setup`, `ValidateKubeSchedulerConfiguration` is firstly called to validate the CC, following by the same validation logic is called the second time if there scheduler config file is loaded. 
* [ ] There are some `TODO` left for various reason, some cleanup is needed to remove those `TODO` items.

**Comment by chendave** [comment]
> Drop unnecessary calling of validation

For this item, my opinion is that, we only need one validation when everything is finalized,  unless early exit is really needed before moving forward.

**Comment by alculquicondor** [comment]
We just need to make sure of 2 things:
- Validation messages contain the most amount of information for debugging. For example, a full path (in the KubeSchedulerConfiguration) to the failed fields.
- We validate for different usages:
  - kube-scheduler users (like in production clusters)
  - scheduler.New (like integration and e2e tests)
  - framework.New (like cluster-autoscaler) Although, if we validate for this case, we are also probably covering scheduler.New with the same level of debuggability.

Can you expand what are the TODOs about? IIRC, some of them where things we missed in the first release and unfortunately we cannot change them for backwards-compatibility reasons. Those should become simple comments instead of TODOs, unless it's something we can fix in the next component config version.

**Comment by chendave** [comment]
> Can you expand what are the TODOs about?

I checked it again, only one is related with issue,  while others are `KubeSchedulerConfiguration` related which should not belong to validation scope.

> TODO(#88093): Validate that all plugin configs for the queue sort extension match.

**Comment by chendave** [comment]
I guess we can close this now? @alculquicondor

**Comment by alculquicondor** [comment]
Yes, thanks

/close
