### ISSUE TITLE
How to disable the support for TLS v1.0 and v1.1?

### ISSUE THREAD

**Issue by jannomeister** [kubernetes/kubernetes#88106]
Right now I'm using a ConfigMap and added **ssl-protocols** set to `TLSv1.2`. When when I tested it using https://ssllabs.com/ssltest/analyze.html, I can see It still supports TLS v1.0 and TLS v1.1. What is the configMap settings to disable the support for these two TLS version permanently?

**Comment by liggitt** [comment]
What component is this issue referring to?

**Comment by jannomeister** [comment]
im possibly referring to `ConfigMap` and `Ingress`

**Comment by liggitt** [comment]
ah, looks like https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/

issues for that component are managed in https://github.com/kubernetes/ingress-nginx/issues, I would suggest asking your question there
