### ISSUE TITLE
Kubernetes should warn when referenced imagePullSecret does not exist

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kubernetes#88142]
**What would you like to be added**:
A warning (or even error) should be emitted, when a scheduled workload references a non-existing imagePullSecret.
**Why is this needed**:
An imagePullSecret is necessary for running images from private registry. They are often referenced in the Pod, parent object (e.g. deployment) or ServiceAccount. They might not need to exist yet, when the parent object or serviceaccount gets created, but they need to when the Pod gets scheduled in order to pull the image. It is a bad user experience if the imagePullSecret that is referenced has a typo in the referenced secret's name or the referenced secret does not exist. As far as I can see there are no warnings emitted for this case.

**Comment by marquiz** [comment]
Perhaps a warning event should be created? I'm not sure if an error would be the right thing to do as the image pull might succeed without the secret in question.
