### ISSUE TITLE
use ControllerRevisionControllerRefManager in StatefulSet like DaemonSet

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#88150]
**What would you like to be added**:

update StatefulSet to use `ControllerRevisionControllerRefManager`, xref: https://github.com/kubernetes/kubernetes/pull/84984/files#r344144617

**Why is this needed**:

this can simplify the code in StatefulSet

**Comment by gavinfish** [comment]
I want to have a try for this.

Besides using `ControllerRevisionControllerRefManager`, I think the logic change here is that adopting orphan revisions is not enough for `sync(key string)`? More actions need to be done like
- Release owned revisions if the selector no longer matches
- Cleanup old stateful set revisions

/assgin

**Comment by cofyc** [comment]
/remove-lifecycle stale

hi, @gavinfish just want to know if you are still seeing this issue?

**Comment by gavinfish** [comment]
> I want to have a try for this.
> 
> Besides using `ControllerRevisionControllerRefManager`, I think the logic change here is that adopting orphan revisions is not enough for `sync(key string)`? More actions need to be done like
> 
> * Release owned revisions if the selector no longer matches
> * Cleanup old stateful set revisions
> 

@cofyc yes. And any comments on my understanding of this issue?

**Comment by cofyc** [comment]
As for this issue, I think we should not change the logic.

**Comment by cofyc** [comment]
/reopen
/help
It's worth finish it.

**Comment by GreyBalloonYU** [comment]
I would like to solve this problem.
I'm a new contributor of k8s, so it will take some time for me to read the source code.
