### ISSUE TITLE
kubelet should rectify corrupt pod status

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#8818]
Forked from #8335

Currently, kubelet sends pod status update whenever it discovers that the newly-generated status differs from the copy in its internal cache. However, it does not check the pod status received from the apiserver at all. What this implies is that if a user or another component changes the pod status via apiserver, kubelet will not correct the status until there is an actual update. We should make kubelet detect corrupt pod status and rectify it.

There are a couple of things that need to be ironed out for this:
 1. Kubelet, as of now, filters out pod status update by default, i.e., it will trigger an update only if the pod spec is changed. Kubelet will not be able to view the status it updates in a short-period of time.
 2. When kubelet generates the pod status, it sets `StartTimestamp` for the pod before storing it into status manager (the internal cache). The timestamp needs to be at the second-level precision to match with the status received from the apiserver (after json marshalling).

**Comment by bgrant0607** [comment]
What about the case where the pod is in Succeeded or Failed?

**Comment by derekwaynecarr** [comment]
Architecturally, is there a ever a future where a field could be defined on Pod.Status whose source of truth is not the Kubelet?

**Comment by bgrant0607** [comment]
@derekwaynecarr Yes. 
1. We're planning to make the node controller have joint (backup) responsibility for the Ready condition: https://github.com/GoogleCloudPlatform/kubernetes/issues/8335#issuecomment-109051619
2. We could create a subresource that would enable another controller to set a specific part of the status and/or an annotation. For instance, /binding currently sets spec.nodeName and annotations, but I'd like to be able to update status also, as mentioned in https://github.com/GoogleCloudPlatform/kubernetes/pull/9032#discussion_r31473139

**Comment by yujuhong** [comment]
> What about the case where the pod is in Succeeded or Failed?

Kubelet ignores pods in the terminated states, so it will not update their status. This behavior can be changed, but I don't see any reason to do that (terminated pods cannot be revived)>

> but I'd like to be able to update status also, as mentioned in #9032 (comment)

For this specific case, the pod is not scheduled anywhere, so it is safe for the scheduler to update the pod status.

**Comment by derekwaynecarr** [comment]
I think the resource version of a pod that is terminated should be stable as it used to do screwy things to our client watches when the Kubelet updated their status.

**Comment by yujuhong** [comment]
Repurposing the old issue for a new use case. @freehan is working on transitioning the pod status to not ready if kubelet hasn't updated the node status after 40 seconds. This fits the "a user or another component changes the pod status via apiserver" condition in the original post. If kubelet restarts, it'd by default updating statuses for all the pods. However, if kubelet was disconnected from the apisever due to, e.g., a network partition, once it recovers from that, it wouldn't update the status since its internal cache is always up-to-date.

Off the top of my head, we have two options.
 1. Rectifying the pod status as the original title suggests. This relies on the fact that status is a subresource of pod, and through watching the pods, kubelet can receive the latest status. If this ever changes, kubelet may need to explicitly watch pod status as well.
 2. Instruct kubelet to detect whether apiserver is reachable (e.g., failed to update node status for the past minute, etc). Once kubelet notices that, it'd lock the internal status cache, and reset the version in the cache to forcibly trigger updates (cc @timstclair). The problem with this is that it's less universal and it may race with the node controller to change pod status. This could be mitigated by setting a more conservative threshold, but I am not sure the race could be completely avoided.

/cc @kubernetes/goog-node

**Comment by yujuhong** [comment]
Update: I discussed with @timstclair and the conclusion is that we'll go with option (1), and clear the apiStatusVersion if the status from the apiserver differs from what kubelet cached internally.
 1. Add a new [pod operation](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/pod_update.go#L33), and sends an update if only status differs so that kubelet [can receive the new update] (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2295).
 2. Upon receiving the new update, kubelet will send the status to [StatusManager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/manager.go) to compare against the current status in the cache. If the statuses differ, the apiStatusVersion entry is cleared to trigger an update. 

It should be noted that this approach
 - may cause some extra status updates due to watch delay when there are multiple in flight updates 
 - would slightly the kubelet's workload (e.g., checking the statuses). The lock contention in status manager will be higher too.

We may want to test kubelet's performance and resource usage during batch creation of pods.

**Comment by Random-Liu** [comment]
Close this issue because #18410 has been merged. Feel free to reopen it if any related error happens again.

**Comment by Random-Liu** [comment]
Close this issue because #18410 has been merged. Feel free to reopen it if any related error happens again.
