### ISSUE TITLE
apiserver: Don't log stack traces on context cancellation?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#88180]
If you look at apiserver logs for any recent e2e test run, you'll see stack traces resulting from "context cancellation" which return 500 status code. Often seemingly from Dynamic PV tests.

I think we shouldn't return a 500 and enormous stack trace on this?

/sig api-machinery
/help-wanted

**Comment by SomtochiAma** [comment]
What should be returned instead?

**Comment by riking** [comment]
If the request (the context) is cancelled, there's no need to log anything. You can check with [`errors.Is`](https://golang.org/pkg/errors/#Is)`(err, `[`context.Canceled`](https://godoc.org/context#pkg-variables)`)`

**Comment by tedyu** [comment]
diff --git a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go
index 5a845435033..d7d3a187ad7 100644
--- a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go
+++ b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go
@@ -17,6 +17,8 @@ limitations under the License.
 package responsewriters

 import (
+       "context"
+       "errors"
        "fmt"
        "net/http"

@@ -68,7 +70,9 @@ func ErrorToAPIStatus(err error) *metav1.Status {
                // by REST storage - these typically indicate programmer
                // error by not using pkg/api/errors, or unexpected failure
                // cases.
-               runtime.HandleError(fmt.Errorf("apiserver received an error that is not an metav1.Status: %#+v", err))
+               if !errors.Is(err, context.Canceled) {
+                       runtime.HandleError(fmt.Errorf("apiserver received an error that is not an metav1.Status: %#+v", err))
+               }
                return &metav1.Status{
                        TypeMeta: metav1.TypeMeta{
                                Kind:       "Status",

**Comment by lavalamp** [comment]
Please note the implied requests in an issue like this, which I didn't
explicitly state:

* is this a bug? Why is the context getting cancelled?
* If not a bug, then 500 is probably not the right return code

To adequately address this, we should understand who/what is cancelling the
context and why.

**Comment by tedyu** [comment]
Here was the last occurrence of 'an error that is not an metav1.Status' in kube-apiserver.log:
```
E0216 03:10:22.940366       1 status.go:71] apiserver received an error that is not an metav1.Status: context.deadlineExceededError{}
```
This was the first line in e2e-gce output:
```
W0216 03:31:46.467] **************************************************************************
```
Note that the error was prior to test run.

Trying to figure out what activity the context cancellation corresponded to.

**Comment by tedyu** [comment]
Checked the build-log.txt for e2e-gce-device-plugin-gpu and e2e-gce-100-performance 

They started around 03:31:50 which was after 03:10:22 
I wonder if 'an error that is not an metav1.Status' was from other test run.
