### ISSUE TITLE
wait pkg functions from apimachinery behave weirdly when stopCh is nil

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#88184]
**What happened**:
Prints "hello" in an infinite loop.

**What you expected to happen**:
Nothing or error?

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L89

```
func main() {
        wait.Until(func() {
                fmt.Println("hello")
        }, 5*time.Second, nil)
}
```

Is this the expected behavior of this code?

**Comment by tedyu** [comment]
I wonder why nil is passed for stop channel.
What's the use case ?

**Comment by neolit123** [comment]
> Is this the expected behavior of this code?

yes, you must pass a channel to the function, as the channel controls when the function should return.

Context#Done() can be used for that:
https://golang.org/pkg/context/#Context

/close
