### ISSUE TITLE
Transitive imports of client-go fail dependency check due to OpenAPIv2 capitalization

### ISSUE THREAD

**Issue by timfallmk** [kubernetes/kubernetes#88183]
**What happened**:
When building a package that contains a dependency on `k8s.io/client-go`, downloading imported dependencies will fail due to a change of package name on `github.com/googleapis/gnostic/OpenAPIv2`

For example, when building [ksync](https://github.com/ksync/ksync) :
```shell
/go/ksync/cmd/ksync# go build -v .
build github.com/ksync/ksync/cmd/ksync: cannot load github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```
This appears to be due to a renaming of the noted package to `openapiv2` to follow the (proper) style guide recommendations (`openapiv3` is similarly changed). https://github.com/googleapis/gnostic/commit/896953e6749863beec38e27029c804e88c3144b8

Explanation of pathing in `go` tools: https://github.com/golang/go/blob/c54bc3448390d4ae4495d6d2c03c9dd4111b08f1/src/cmd/go/internal/module/module.go#L359-L417

**Note**: _This only seems to affect *nix builds_
Due to the way the `go` tools handle (or do not handle) strings in module paths, only builds on `*nix` systems seem to be affected. MacOS builds work just fine.

**Change**:
Change references to `"github.com/googleapis/gnostic/OpenAPIv2"` to be lowercase (despite aliasing them to lowercase anyway)
Making this change would cause all platforms to behave similarly.

**What you expected to happen**:
Successfully dependency download and build.

**How to reproduce it (as minimally and precisely as possible)**:
Example given above:
```shell
git clone https://github.com/ksync/ksync -b dep-update && cd ksync/cmd/ksync && go build -v .
```
(must be run on linux, or a system that handles paths similarly)

**Anything else we need to know?**:

**Environment**: Ubuntu 18.04, golang 1.13.6
- Kubernetes version (use `kubectl version`): NA
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.x

**Comment by timfallmk** [comment]
I'm not entirely convinced this is the right place to file this, so let me know if it isn't.

**Comment by liggitt** [comment]
See resolution in https://github.com/kubernetes/client-go/issues/741#issuecomment-580957445

Using a specific version of client go will correctly fetch compatible versions of dependencies

**Comment by timfallmk** [comment]
@liggitt Appreciate the quick response. `INSTALL.md` has the same instructions for pinning releases, but doesn't explain _why_ a pinned version would navigate transitive dependencies differently than `HEAD`. Could you shed some light on this?

**Comment by timfallmk** [comment]
I'm not sure this solves the issue. Same result when pinning `client-go` to `v0.17.3`.

**Comment by liggitt** [comment]
> Same result when pinning `client-go` to `v0.17.3`.

You simultaneously are requiring the new incompatible version of the gnostic library at https://github.com/ksync/ksync/commit/fdefc3b1b497ea5c869329f3fa7bb4d86ca79426#diff-37aff102a57d3d7b797f152915a6dc16L28

**Comment by timfallmk** [comment]
That's correct, the issue was to fix using current versions of the gnostic library. If you're saying the  solution is to downgrade to an older version (which is what I get when I run dependency checks after pinning, from scratch `github.com/googleapis/gnostic v0.0.0-20170729233727-0c5108395e2d`) then shouldn't the upstream fix here be the easier solution? Or are there other outstanding reasons not to use the most recent `gnostic` release?

Just trying to understand the thought process.

**Comment by timfallmk** [comment]
I see this is an ongoing issue that has no resolution, but is being closed out. https://github.com/DataDog/dd-trace-go/pull/585

I will send a PR with the proposed fixes for review.

**Comment by timfallmk** [comment]
Blog post for new proto tools release related to fix https://blog.golang.org/a-new-go-api-for-protocol-buffers

**Comment by thavlik** [comment]
> See resolution in [kubernetes/client-go#741 (comment)](https://github.com/kubernetes/client-go/issues/741#issuecomment-580957445)
> 
> Using a specific version of client go with a version of go that makes use of version information for dependencies provided in go.mod will correctly fetch compatible versions

I was able to "fix" go.mod on my side with https://github.com/kubernetes/client-go/issues/741#issuecomment-603440039 (`go get -u k8s.io/client-go@v0.17.2 github.com/googleapis/gnostic@v0.3.1 ./...`)

Hopefully this is fixed soon in upstream.

Thanks

**Comment by liggitt** [comment]
this dependency is updated in kubernetes/kubernetes#89704 and kubernetes/kube-openapi#189, targeting Kubernetes 1.19

**Comment by damemi** [comment]
Tangential note to anyone that has this as a transitive dependency: make sure your git is aware of the case-sensitive change if you have any kind of verify-vendor scripts that do a simple diff to make sure `vendor` is up-to-date

Sorry to revive a closed issue, but I just spent a while debugging why our `verify-vendor` script (basically [hack/verify-vendor](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-vendor.sh)) was failing in the descheduler (bumping to 1.19) before I realized that I needed to manually commit the directory's new lowercase filename as git wasn't picking up the change. This showed up as a "new file" in the `diff` call, but nothing in git which had me pretty confused.

Hope this helps if anyone hits a similar problem

**Comment by gophobic** [comment]
go mod is such a fest of retardation. But it's thought out according to the core team and you can do nothing about that.

**Comment by lboix** [comment]
Here is a workaround that could help, especially if you are using Kubernetes 1.14 : https://github.com/kubernetes/client-go/issues/741#issuecomment-807368949
