### ISSUE TITLE
hack/update-bazel.sh fails with incompatible RULES_GO_VERSION

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#88190]
**What happened**:

When run hack/update-bazel.sh from the latest master branch (commit 3e3a3599ca41ed98240170cd59018a743b97b6e7), it reported:
gazelle: Found RULES_GO_VERSION 0.17.2. Minimum compatible version is 0.19.0.
Gazelle may not be compatible with this version of rules_go.
Update io_bazel_rules_go to a newer version in your WORKSPACE file.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
go version is 1.13.6

**Comment by liggitt** [comment]
Do you see that if you `make clean`? Do you have a stale bazel/gazelle binary?

**Comment by caesarxuchao** [comment]
Yeah, I tried "make clean". I also manually removed the `_output` directory.

And in my environment, "which bazel", "which gazelle" both return empty. Also, the hack/update-bazel.sh [installs](https://github.com/kubernetes/kubernetes/blob/3b22fcc7bdcf5cb6eac2e4bb10f3b943ba94e2f2/hack/update-bazel.sh#L29-L31) gazzelle, so I think the problem is not caused by the gazelle version.

**Comment by liggitt** [comment]
Strange, it works well for me and in CI

**Comment by BenTheElder** [comment]
@caesarxuchao are you still seeing this?
