### ISSUE TITLE
Switch scheduler performance integration tests to new metrics-based suite

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#88195]
Scheduler integration tests under `test/integration/scheduler_perf` for performance measurement of kube-scheduler component has recently underwent code refactoring and major improvements in what is measured and collected. Right now, there are two test suites running on top of Golang benchmark framework:
- tests prefixed with `BenchmarkScheduling` (10 in total)
- tests prefixed with `BenchmarkPerfScheduling` (10 configurable tests ran as 1)

The latter group/suite is a copy of the first. Additionally, it allows to:
- make the list of tests configurable through a yaml file (see https://github.com/kubernetes/kubernetes/pull/86160), thus allowing easy addition of another tests without changing the code itself
- collect metrics registered within kube-scheduler (see https://github.com/kubernetes/kubernetes/pull/87923)

The former test suite is run within a jenkins job. Test results are displayed in the [performance dashboard](http://perf-dash.k8s.io/#/?jobname=scheduler-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults&benchmark=BenchmarkSchedulingInTreePVs%2F5000Nodes%2F5000Pods-8&metricName=time).

Parent issue: https://github.com/kubernetes/kubernetes/issues/81719

**What would you like to be added**:
- replace the former test suite (turn it into a legacy suite) with the new one which provides compatible performance measurements (replacing overall running time with evaluation time of individual steps in a scheduling cycle); performance dashboard will need to be altered to accept new metrics artifact (trivial change just by changing input data parser for `scheduler-benchmark` jobname)
- remove golang benchmark artifact which will no longer be consumed: https://github.com/kubernetes/kubernetes/blob/1c60045db0bd6efbb2827063e39f515b95c2bfa4/hack/jenkins/benchmark-dockerized.sh#L63-L66

**Why is this needed**:
To measure kube-scheduler performance in terms of metrics, not the overall running time. Individual metrics allows to give us better picture of performance of individual steps during a scheduling cycle.

**Comment by ahg-g** [comment]
I suggest we keep the old one for now:
1) rename the file ```scheduler_perf_legacy_test.go```
2) rename the test suite ```BenchmarkSchedulingLegacy```
3) rename the new test suite ```BenchmarkScheduling```
4) use the new test suite in the per dashboard


The reason I want to keep the old one for now is that we can still use it to compare performance against older releases. We can remove it after a couple of releases.

**Comment by liu-cong** [comment]
Can we run both the old and new tests for a while so that we can compare the results and get more confidence on the new metrics? Meanwhile we can have some time to get feedbacks.

**Comment by ingvagabund** [comment]
> rename the old test suite BenchmarkScheduling to BenchmarkSchedulingLegacy

As we discussed on the Slack we need other than `BenchmarkScheduling` prefix if we want to keep the jenkins jobs running the suite unchanged: 
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L376-L377

as @ahg-g suggested we can go with LegacyBenchmarkScheduling

**Comment by ingvagabund** [comment]
> Can we run both the old and new tests for a while so that we can compare the results and get more confidence on the new metrics? Meanwhile we can have some time to get feedbacks.

I am not against, the last time I checked it should be easy to add the new job into the perf dashboard.

**Comment by ingvagabund** [comment]
The new suite already deployed: 
http://perf-dash.k8s.io/#/?jobname=scheduler-perf-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkPerfResults&Metric=scheduler_scheduling_algorithm_predicate_evaluation_seconds&Name=BenchmarkPerfScheduling%2FSchedulingBasic%2F500Nodes%2F500InitPods%2F1000PodsToSchedule
