### ISSUE TITLE
when use leaderelection failed to release lock

### ISSUE THREAD

**Issue by silenceper** [kubernetes/kubernetes#88194]
**What happened**:
when use leaderelection failed to release lock  
```
E0215 20:05:38.726163   48791 leaderelection.go:307] Failed to release lock: Lease.coordination.k8s.io "example" is invalid: spec.leaseDurationSeconds: Invalid value: 0: must be greater than 0

```
**What you expected to happen**:
release lock success
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
lock type is lease 
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by fedebongio** [comment]
/assign @silenceper 
Thank you for creating the issue and the PR! Assigning to you so you can close when the PR merges!
