### ISSUE TITLE
Pod is stuck in "ContainerCreating" when "RestartPolicy: Never" and "FailedMount"

### ISSUE THREAD

**Issue by SerialVelocity** [kubernetes/kubernetes#88193]
**What happened**:
I started a pod with `RestartPolicy: Never` set and it couldn't mount a volume (I had a bad iptables rule).

It got stuck in "ContainerCreating" and never retried mounting the volume.

**What you expected to happen**:
Retry mounting the volume until the pod is created.

**How to reproduce it (as minimally and precisely as possible)**:
Start a pod with `RestartPolicy: Never` where it is not possible to mount a volume.

**Anything else we need to know?**:
It looks similar to these tickets but to do with failed mounts instead of a failed CNI:
https://github.com/kubernetes/kubernetes/issues/79398
https://github.com/kubernetes/kubernetes/pull/79451

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: bare-metal
- OS (e.g: `cat /etc/os-release`): Fedora CoreOS 31.20200127.3.0"
- Kernel (e.g. `uname -a`): 5.4.13-201.fc31.x86_64

/sig node

**Comment by tedyu** [comment]
```
had a bad iptables rule
```
Was the bad rule removed and the expectation is that the retry would get mount to succeed ?

**Comment by SerialVelocity** [comment]
> Was the bad rule removed and the expectation is that the retry would get mount to succeed ?

Correct. I would expect the mount to be retried as the failure is part of pod creation, not the pod failing while running/starting up.

**Comment by SergeyKanzhelev** [comment]
It sounds like opposite to what is asked here: https://github.com/kubernetes/kubernetes/issues/87278 ?

**Comment by SerialVelocity** [comment]
It seems like that is asking if there is a way to fail for permanent errors? It's also for different behaviour to what the docs say:

> https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
> `restartPolicy` only refers to restarts of the Containers by the kubelet

`ImageNotFound` and `FailedMount` are before the container has even started therefore I would expect them to be retried. It sounds like #87278 is asking for an extra flag for failing.

Also, `FailedMount` here occurred due to a network timeout which is most definitely transient in nearly every case.

**Comment by yqwang-ms** [comment]
@SerialVelocity
The restartPolicy is a field of **PodSpec**, instead of a field of **ContainerSpec**.
So, it should also responsible to control the whole retry behavior for the pod.

Anyway, if you insist **PodSpec**.restartPolicy can only control **container** restartPolicy, the leftover restartPolicys for the pod are hardcoded, such as ImageNotFound/FailedMount are always retry. We would better also expose the flexibility to let **PodSpec** can also control these leftover restartPolicys, and make up the Pod restartPolicy missing part. (So you can still specify always retry for your FailedMount, and I can also specify never retry for my ImageNotFound )

**Comment by SerialVelocity** [comment]
@yqwang-ms 

I'm just quoting the docs there :)

I don't consider the pod started until the container manages to start. I consider it in the "starting" state and should only fail on permanent errors.

**-- Below here everything is related to the other issue --**

I agree with @liggitt that reasons like `ImageNotFound` are transient as I have seen in practice systems waiting for an image to exist.

I think your issue should be asking for another restart policy which includes transient errors. My issue here is that `FailedMount` is transient in the case of network errors so should be retried even when restart policy is never.

**Comment by yqwang-ms** [comment]
I am asking the restart policy would better to be configurable as ImageNotFound/FailedMount/etc may need to be treated differently in different scenarios, such as for batch jobs, user easliy to specify a wrong image name/mount pathm etc,

**Comment by fromanirh** [comment]
is this still relevant? the original reports says kubernetes 1.17.3, does it still reproduce?
/triage needs-information

**Comment by yqwang-ms** [comment]
It should still reproduce, as restart policy for ImageNotFound/FailedMount/etc is still not configurable
