### ISSUE TITLE
Insufficient permissions for RBAC role system:kube-controller-manager for clusterroles resource

### ISSUE THREAD

**Issue by qhh0205** [kubernetes/kubernetes#88203]
**What happened**:
I startup kube-controler-manager with binary, the CA cert user is system:kube-controller-manager, but that report the RBAC permission related issues as following:
```
Feb 16 05:10:48 ansible kube-controller-manager[4046]: E0216 05:10:48.502394    4046 clusterroleaggregation_controller.go:180] edit failed with : clusterroles.rbac.authorization.k8s.io "edit" is forbidden: User "system:kube-controller-manager" cannot update resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
Feb 16 05:27:28 ansible kube-controller-manager[4046]: E0216 05:27:28.501957    4046 clusterroleaggregation_controller.go:180] view failed with : clusterroles.rbac.authorization.k8s.io "view" is forbidden: User "system:kube-controller-manager" cannot update resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
Feb 16 05:27:28 ansible kube-controller-manager[4046]: E0216 05:27:28.503529    4046 clusterroleaggregation_controller.go:180] admin failed with : clusterroles.rbac.authorization.k8s.io "admin" is forbidden: User "system:kube-controller-manager" cannot update resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
```
 _**I have read related issues, but still not work for me: #48208**_ 
**What you expected to happen**:
No such error logs!
**How to reproduce it (as minimally and precisely as possible)**:
Start the kube-controller-manager binary with following options:
```
ExecStart=/usr/local/bin/kube-controller-manager \
  --controllers=*,-horizontalpodautoscaling \
  --kubeconfig=/var/lib/kube-controller-manager/kube-controller-manager.kubeconfig \
  --leader-elect=true \
  --log-dir=/home/data/logs \
  --logtostderr=false \
  --pod-eviction-timeout=1m0s \
  --root-ca-file=/var/lib/kubernetes/ca-k8s-apiserver.pem \
  --service-account-private-key-file=/var/lib/kubernetes/cert-k8s-controller-manager-sa-key.pem \
  --terminated-pod-gc-threshold=20 \
  --use-service-account-credentials=true \
  --v=2
```
**Anything else we need to know?**:
The default clusterrole of system:kube-controller-manager:
```
root@ansible:/vagrant# kubectl describe clusterrole system:kube-controller-manager
Name:         system:kube-controller-manager
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
PolicyRule:
  Resources                                  Non-Resource URLs  Resource Names  Verbs
  ---------                                  -----------------  --------------  -----
  secrets                                    []                 []              [create delete get update]
  endpoints                                  []                 []              [create get update]
  serviceaccounts                            []                 []              [create get update]
  events                                     []                 []              [create patch update]
  events.events.k8s.io                       []                 []              [create patch update]
  serviceaccounts/token                      []                 []              [create]
  tokenreviews.authentication.k8s.io         []                 []              [create]
  subjectaccessreviews.authorization.k8s.io  []                 []              [create]
  configmaps                                 []                 []              [get]
  namespaces                                 []                 []              [get]
  *.*                                        []                 []              [list watch]
```
**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.3
- Cloud provider or hardware configuration: hardware
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux ansible 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): Not install net plugin now.
- Others:

**Comment by liggitt** [comment]
How are you starting your kube apiserver? Are you enabling RBAC authorization?

**Comment by liggitt** [comment]
Check the actual process of kube-controller-manager to make sure it matches your systemd invocation. You appear to have trailing white space after some of the line continuation backslashes. 

That could have the effect of dropping several of the final flags, especially the use-service-account-credentials flag. The log messages indicate that is not being passed.

**Comment by qhh0205** [comment]
> Check the actual process of kube-controller-manager to make sure it matches your systemd invocation. You appear to have trailing white space after some of the line continuation backslashes.
> 
> That could have the effect of dropping several of the final flags, especially the use-service-account-credentials flag. The log messages indicate that is not being passed (because that controller is trying to update using the controller manager user, not the cluster role reconciliation service account)

Yes, you are right! Thank you very much! The process of kube-controller-manager does not mache systemd invocation, the `use-service-account-credentials` flag not load by process.

**Comment by I-ANY** [comment]
Excuse me, I have error the same problem as you. How do you resolve it? Looking forward to your reply, Thank you! 
My kubernetes's version is 1.23. And this is my configure:
kube-apiserver:
KUBE_APISERVER_OPTS="--logtostderr=false \\
--v=2 \\
--log-dir=/opt/kubernetes/logs \\
--etcd-servers=https://192.168.9.20:2379,https://192.168.9.21:2379,https://192.168.9.22:2379 \\
--bind-address=192.168.9.20 \\
--secure-port=6443 \\
--advertise-address=192.168.9.20 \\
--allow-privileged=true \\
--service-cluster-ip-range=10.0.0.0/24 \\
--enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \\
--authorization-mode=RBAC,Node \\
--enable-bootstrap-token-auth=true \\
--token-auth-file=/opt/kubernetes/cfg/token.csv \\
--service-node-port-range=30000-32767 \\
--kubelet-client-certificate=/opt/kubernetes/ssl/apiserver.pem \\
--kubelet-client-key=/opt/kubernetes/ssl/apiserver-key.pem \\
--tls-cert-file=/opt/kubernetes/ssl/apiserver.pem  \\
--tls-private-key-file=/opt/kubernetes/ssl/apiserver-key.pem \\
--client-ca-file=/opt/kubernetes/ssl/ca.pem \\
--service-account-key-file=/opt/kubernetes/ssl/ca-key.pem \\
--service-account-issuer=https://kubernetes.default.svc.cluster.local \\
--service-account-signing-key-file=/opt/kubernetes/ssl/apiserver-key.pem \\
--etcd-cafile=/opt/etcd/ssl/ca.pem \\
--etcd-certfile=/opt/etcd/ssl/server.pem \\
--etcd-keyfile=/opt/etcd/ssl/server-key.pem \\
--requestheader-client-ca-file=/opt/kubernetes/ssl/ca.pem \\
--proxy-client-cert-file=/opt/kubernetes/ssl/apiserver.pem \\
--proxy-client-key-file=/opt/kubernetes/ssl/apiserver-key.pem \\
--requestheader-allowed-names=kubernetes \\
--requestheader-extra-headers-prefix=X-Remote-Extra- \\
--requestheader-group-headers=X-Remote-Group \\
--requestheader-username-headers=X-Remote-User \\
--enable-aggregator-routing=true \\
--audit-log-maxage=30 \\
--audit-log-maxbackup=3 \\
--audit-log-maxsize=100 \\
--audit-log-path=/opt/kubernetes/logs/k8s-audit.log"

kube-controller-magager:
ExecStart=/opt/kubernetes/bin/kube-controller-manager \\
--v=2 \\
--log-dir=/opt/kubernetes/logs \\
--leader-elect=true \\
--kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig \\
--bind-address=127.0.0.1 \\
--allocate-node-cidrs=true \\
--cluster-cidr=10.244.0.0/16 \\
--service-cluster-ip-range=10.0.0.0/24 \\
--cluster-signing-cert-file=/opt/kubernetes/ssl/ca.pem \\
--cluster-signing-key-file=/opt/kubernetes/ssl/ca-key.pem  \\
--root-ca-file=/opt/kubernetes/ssl/ca.pem \\
--service-account-private-key-file=/opt/kubernetes/ssl/ca-key.pem \\
--cluster-signing-duration=87600h0m0s
Restart=on-failure
