### ISSUE TITLE
GPLv3 dependency?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#88208]
While this project uses Apache v2 license, this depends on `https://github.com/libopenstorage/openstorage` (Apache v2), which depends on   `gopkg.in/jmcvetta/napping.v3` package which uses GPL v3 license.

https://github.com/libopenstorage/openstorage/blob/d1e3fd845368e7a0550a2b597015eb3d865dbd0b/volume/drivers/coprhd/coprhd.go#L9

This seems problematic. I filed an issue at upstream https://github.com/libopenstorage/openstorage/issues/1433. 

I wanted to bring this your attention and potentially address this.

/sig storage

**Comment by dims** [comment]
@tamalsaha per https://github.com/kubernetes/kubernetes/issues/80029 we will hopefully *never* touch this dependency again (we are at v1.0.0). 

cc @lpabon 

/close

**Comment by tamalsaha** [comment]
@dims, this does not resolve the underlying issue that there is a transitive dependency on a GPL v3 library from an Apache v2 licensed project. 

/open

**Comment by dims** [comment]
@tamalsaha you are chasing that in libopenstorage/openstorage#1433 so that's sufficient for now.

**Comment by lpabon** [comment]
Hi guys, thank you for pointing this out. We are fixing that now. https://github.com/libopenstorage/openstorage/pull/1445 . Do we need to update Kubernetes in any way to resolve this?

**Comment by tamalsaha** [comment]
@lpabon , I suppose you can cut a new release for openstorage repo and update k/k's gomod?

**Comment by dims** [comment]
@tamalsaha we are using a really old 1.0.0 of the openstorage repo, i see no need to touch that. please cross check.
