### ISSUE TITLE
After reboot Centos7 server , when run kubectl get pod get error: the connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by stevenruizhang** [kubernetes/kubernetes#88205]
**What happened**:
when i reboot the centos7 server, and run get pod see below error
The connection to the server localhost:8080 was refused - did you specify the right host or port?
**What you expected to happen**:
before i reboot the system, the kubernetes have three nodes, and pods/service/,.. all working file
**How to reproduce it (as minimally and precisely as possible)**:
1) reboot the server
2) kubectl get pod
**Anything else we need to know?**:
1) i even sudo kubeadm reset and init again still issue

[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /var/lib/dockershim /var/run/kubernetes /var/lib/cni]
The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d
The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.
If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.
The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
2) sudo kubeadm init --pod-network-cidr 172.100.0.0/16 --apiserver-advertise-address 10.128.0.5 --apiserver-cert-extra-sans 35.239.61.35

Unfortunately, an error has occurred:
        timed out waiting for the condition
This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'
Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:
"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
- Cloud provider or hardware configuration:
the instance running in cloud
n1-standard-2 (2 vCPUs, 7.5 GB memory)
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
uname -a
Linux k8s-master-9828 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/remove-kind bug
/triage support
/sig cluster-lifecycle

hi, what do you see in the kubelet logs; why isn't it running after reboot?

**Comment by stevenruizhang** [comment]
1) after reboot , run kubectl version and get nodes will always throw below error
The connection to the server localhost:8080 was refused - did you specify the right host or port?
2) if u want to need more kubelet log, give me the command i can paste, thanks

**Comment by neolit123** [comment]
kubeadm gives you the command when it fails:

> - 'journalctl -xeu kubelet'

try running this right after a failure.

**Comment by stevenruizhang** [comment]
@neolit123
[steven_rui_zhang@k8s-master-9828 ~]$ kubectl get pod
The connection to the server localhost:8080 was refused - did you specify the right host or port?
steven_rui_zhang@k8s-master-9828 ~]$ journalctl -xeu kubelet
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.178387   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.278665   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.378903   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.455079   12380 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://10.128.0.5:6443
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.479126   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.579347   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.655000   12380 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://10.128.0.5:6
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.679606   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.779817   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.880022   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:29 k8s-master-9828 kubelet[12380]: E0217 12:56:29.980235   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.055034   12380 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://10.128.0
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.080419   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.180629   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.255028   12380 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://10.128.0
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.280845   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.381123   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.455006   12380 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://10.12
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.481240   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.581442   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.655035   12380 csi_plugin.go:267] Failed to initialize CSINodeInfo: error updating CSINode annotation: timed out waiting for the co
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.681664   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.781905   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.855094   12380 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://10.128.0.5:6443
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.882096   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:30 k8s-master-9828 kubelet[12380]: E0217 12:56:30.982327   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:31 k8s-master-9828 kubelet[12380]: E0217 12:56:31.055059   12380 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://10.128.0.5:6
Feb 17 12:56:31 k8s-master-9828 kubelet[12380]: E0217 12:56:31.082565   12380 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 12:56:31 k8s-master-9828 kubelet[12380]: E0217 12:56:31.104107   12380 event.go:272] Unable to write event: 'Post https://10.128.0.5:6443/api/v1/namespaces/default/events: dial tcp 10.128

**Comment by neolit123** [comment]
wondering if that last line:
> Unable to write event: 'Post https://10.128.0.5:6443/api/v1/namespaces/default/events: dial tcp 10.128

suggests connectivity issues.
did the network setup of the node changed after reboot for some reason?

**Comment by neolit123** [comment]
also check if the kubelet is running?
```
systemctl status kubelet
```

and post a full log from `journalctl -xeu kubelet` after doing a:
```
systemctl restart kubelet
```

**Comment by stevenruizhang** [comment]
@neolit123 
1) the instance running in GCP, i think the network not changed after reboot, it in the same subnetwork and the Primary internal IP and external IP not changed also
2) steven_rui_zhang@k8s-master-9828 ~]$ systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Mon 2020-02-17 13:09:39 UTC; 6s ago
     Docs: https://kubernetes.io/docs/
 Main PID: 23200 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─23200 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driv...
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: W0217 13:09:44.443137   23200 status_manager.go:530] Failed to get status for pod "kube-apiserver-k8s-master-9828_kube-system(efda344ebcb658fc3...
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.534702   23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.634957   23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.642914   23200 kubelet_node_status.go:92] Unable to register node "k8s-master-9828" with API server: Post https://10...tion refused
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.735199   23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.835435   23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.842939   23200 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://...tion refused
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.935723   23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:45 k8s-master-9828 kubelet[23200]: E0217 13:09:45.035999   23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:45 k8s-master-9828 kubelet[23200]: E0217 13:09:45.136243   23200 kubelet.go:2263] node "k8s-master-9828" not found
Hint: Some lines were ellipsized, use -l to show in full.
3) [steven_rui_zhang@k8s-master-9828 ~]$ sudo systemctl restart kubelet
[steven_rui_zhang@k8s-master-9828 ~]$ journalctl -xeu kubelet
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.321731   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.421943   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.438261   24367 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://10.128.0
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.522199   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.575207   24367 eviction_manager.go:246] eviction manager: failed to get summary stats: failed to get node info: node "k8s-master-98
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.622478   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.638319   24367 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://10.12
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.722645   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.822933   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:10:59 k8s-master-9828 kubelet[24367]: E0217 13:10:59.923124   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.023370   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: W0217 13:11:00.038267   24367 status_manager.go:530] Failed to get status for pod "kube-controller-manager-k8s-master-9828_kube-system(c8cf50ad532
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.123638   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.223836   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.238271   24367 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://10.128.0.5:6
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.324179   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.424366   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.438243   24367 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://10.128.0
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.524545   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.624805   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: W0217 13:11:00.638347   24367 status_manager.go:530] Failed to get status for pod "kube-apiserver-k8s-master-9828_kube-system(efda344ebcb658fc3320
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.725040   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.825264   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.838352   24367 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://10.128.0.5:6443
Feb 17 13:11:00 k8s-master-9828 kubelet[24367]: E0217 13:11:00.925495   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.025693   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.038243   24367 csi_plugin.go:267] Failed to initialize CSINodeInfo: error updating CSINode annotation: timed out waiting for the co
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.125879   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.226137   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.238353   24367 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://10.128.0
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.326361   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.426601   24367 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:11:01 k8s-master-9828 kubelet[24367]: E0217 13:11:01.438221   24367 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://10.12
lines 998-1030/1030 (END)

**Comment by neolit123** [comment]
> [steven_rui_zhang@k8s-master-9828 ~]$ sudo systemctl restart kubelet
[steven_rui_zhang@k8s-master-9828 ~]$ journalctl -xeu kubelet

this does not show the beginning of the logs - "staring kubelet..."

> systemctl status kubelet

does it say that it's running?

**Comment by stevenruizhang** [comment]
@neolit123  systemctl status kubelet result show the kubelet status is active 
steven_rui_zhang@k8s-master-9828 ~]$ systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
Drop-In: /usr/lib/systemd/system/kubelet.service.d
└─10-kubeadm.conf
Active: active (running) since Mon 2020-02-17 13:09:39 UTC; 6s ago
Docs: https://kubernetes.io/docs/
Main PID: 23200 (kubelet)
CGroup: /system.slice/kubelet.service
└─23200 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driv...
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: W0217 13:09:44.443137 23200 status_manager.go:530] Failed to get status for pod "kube-apiserver-k8s-master-9828_kube-system(efda344ebcb658fc3...
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.534702 23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.634957 23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.642914 23200 kubelet_node_status.go:92] Unable to register node "k8s-master-9828" with API server: Post https://10...tion refused
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.735199 23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.835435 23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.842939 23200 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://...tion refused
Feb 17 13:09:44 k8s-master-9828 kubelet[23200]: E0217 13:09:44.935723 23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:45 k8s-master-9828 kubelet[23200]: E0217 13:09:45.035999 23200 kubelet.go:2263] node "k8s-master-9828" not found
Feb 17 13:09:45 k8s-master-9828 kubelet[23200]: E0217 13:09:45.136243 23200 kubelet.go:2263] node "k8s-master-9828" not found
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by stevenruizhang** [comment]
let me know what u need more action from my side

**Comment by neolit123** [comment]
> kubelet_node_status.go:92] Unable to register node "k8s-master-9828" with API server: Post https://10...tion refused

this line suggests that the API server pod is not running.
make sure the static pod yaml files are present under:
`/etc/kubernetes/manifests`

other than that, it's not clear to me what may be causing this.

**Comment by stevenruizhang** [comment]
@neolit123 
1) let me know if missing some files in this folder: /etc/kubernetes/manifests
[steven_rui_zhang@k8s-master-9828 ~]$ ls -l /etc/kubernetes/manifests/
total 16
-rw-------. 1 root root 1757 Feb 16 07:17 etcd.yaml
-rw-------. 1 root root 2600 Feb 16 07:17 kube-apiserver.yaml
-rw-------. 1 root root 2534 Feb 16 07:17 kube-controller-manager.yaml
-rw-------. 1 root root 1120 Feb 16 07:17 kube-scheduler.yaml
2) check the docker container, seems like the first threes are exited
[steven_rui_zhang@k8s-master-9828 ~]$ sudo docker ps -a                                                                                                                                           
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                      PORTS               NAMES
af9d9505d3b3        90d27391b780           "kube-apiserver --..."   17 seconds ago      Exited (1) 16 seconds ago                       k8s_kube-apiserver_kube-apiserver-k8s-master-9828_kube-system_efda344ebcb658fc33203cb2984024a3_6520
9dda601aade2        b0f1517c1f4b           "kube-controller-m..."   18 seconds ago      Exited (1) 16 seconds ago                       k8s_kube-controller-manager_kube-controller-manager-k8s-master-9828_kube-system_c8cf50ad532c7df062b8c6e9e2913e1b_6207
4fdd4e31346d        303ce5db0e90           "etcd --advertise-..."   20 seconds ago      Exited (1) 19 seconds ago                       k8s_etcd_etcd-k8s-master-9828_kube-system_1e119859996e1f2e703fc2cb8633af5d_6572
c6ea98768fec        d109c0821a2b           "kube-scheduler --..."   41 hours ago        Up 41 hours                                     k8s_kube-scheduler_kube-scheduler-k8s-master-9828_kube-system_e3025acd90e7465e66fa19c71b916366_0
bc366b58cbb8        k8s.gcr.io/pause:3.1   "/pause"                 41 hours ago        Up 41 hours                                     k8s_POD_kube-scheduler-k8s-master-9828_kube-system_e3025acd90e7465e66fa19c71b916366_0
5bc6c59e906b        k8s.gcr.io/pause:3.1   "/pause"                 41 hours ago        Up 41 hours                                     k8s_POD_kube-controller-manager-k8s-master-9828_kube-system_c8cf50ad532c7df062b8c6e9e2913e1b_0
78acc783f1a5        k8s.gcr.io/pause:3.1   "/pause"                 41 hours ago        Up 41 hours                                     k8s_POD_kube-apiserver-k8s-master-9828_kube-system_efda344ebcb658fc33203cb2984024a3_0
d20aa45be9ac        k8s.gcr.io/pause:3.1   "/pause"                 41 hours ago        Up 41 hours                                     k8s_POD_etcd-k8s-master-9828_kube-system_1e119859996e1f2e703fc2cb8633af5d_0

3) i can not find the first container log, because it was exited
[steven_rui_zhang@k8s-master-9828 ~]$ sudo docker logs af9d9505d3b3
Error: No such container: af9d9505d3b3

4) i encountered the same issue in minikube, i use minikube stop, start then the issue resolved, any the command can stop, start the kubernetes or reset the kubernetes 

5) let me know what u need more action from my side

**Comment by neolit123** [comment]
you need to find out why the containers have exited.

try moving the contents of the folder `/etc/kubernetes/manifests/*.yaml` to a temporary location, wait 1 minute, the bring the `*.yaml` back in `/etc/kubernetes/manifests/`

after you have done this watch the docker containers again using `docker ps`

**Comment by stevenruizhang** [comment]
@neolit123 try moving the yaml to  a temporary location, wait 1 minute, the bring the *.yaml back in /etc/kubernetes/manifests/, running docker ps -a, still have exited container,
1) [steven_rui_zhang@k8s-master-9828 ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                              PORTS               NAMES
5ae3977442f4        90d27391b780           "kube-apiserver --..."   2 seconds ago       Exited (1) 1 second ago                                 k8s_kube-apiserver_kube-apiserver-k8s-master-9828_kube-system_efda344ebcb658fc33203cb2984024a3_10341
0d5d3424a06b        b0f1517c1f4b           "kube-controller-m..."   2 seconds ago       Exited (1) Less than a second ago                       k8s_kube-controller-manager_kube-controller-manager-k8s-master-9828_kube-system_c8cf50ad532c7df062b8c6e9e2913e1b_9829
bdc665a89566        303ce5db0e90           "etcd --advertise-..."   2 seconds ago       Exited (1) 1 second ago                                 k8s_etcd_etcd-k8s-master-9828_kube-system_1e119859996e1f2e703fc2cb8633af5d_10406
89f3c0f9fe9e        b0f1517c1f4b           "kube-controller-m..."   31 seconds ago      Exited (1) 29 seconds ago                               k8s_kube-controller-manager_kube-controller-manager-k8s-master-9828_kube-system_c8cf50ad532c7df062b8c6e9e2913e1b_9828
c6ea98768fec        d109c0821a2b           "kube-scheduler --..."   2 days ago          Up 2 days                                               k8s_kube-scheduler_kube-scheduler-k8s-master-9828_kube-system_e3025acd90e7465e66fa19c71b916366_0
bc366b58cbb8        k8s.gcr.io/pause:3.1   "/pause"                 2 days ago          Up 2 days                                               k8s_POD_kube-scheduler-k8s-master-9828_kube-system_e3025acd90e7465e66fa19c71b916366_0
5bc6c59e906b        k8s.gcr.io/pause:3.1   "/pause"                 2 days ago          Up 2 days                                               k8s_POD_kube-controller-manager-k8s-master-9828_kube-system_c8cf50ad532c7df062b8c6e9e2913e1b_0
78acc783f1a5        k8s.gcr.io/pause:3.1   "/pause"                 2 days ago          Up 2 days                                               k8s_POD_kube-apiserver-k8s-master-9828_kube-system_efda344ebcb658fc33203cb2984024a3_0
d20aa45be9ac        k8s.gcr.io/pause:3.1   "/pause"                 2 days ago          Up 2 days                                               k8s_POD_etcd-k8s-master-9828_kube-system_1e119859996e1f2e703fc2cb8633af5d_0
2) what's the purpose of moving action, i can not see any file changed?
3) i encountered the same issue in minikube, i use minikube stop, start then the issue resolved, any the command can stop, start the kubernetes or reset the kubernetes

**Comment by neolit123** [comment]
> what's the purpose of moving action, i can not see any file changed?

moving the YAML files away will notify the kubelet to remove the control-plane static pods.
bringing them back will tell the kubelet to re-create the static pods.

> encountered the same issue in minikube, i use minikube stop, start then the issue resolved, any the command can stop, start the kubernetes or reset the kubernetes

minikube creates your cluster in a virtual-machine. so minikube stop/start i assume restarts the VM.
the kubeadm equivalent is to restart the host, yet you are seeing an issue after doing that.

> [steven_rui_zhang@k8s-master-9828 ~]$ sudo docker ps -a

try finding out why the containers exit.

**Comment by stevenruizhang** [comment]
@neolit123  i have no idea how to find out why the containers exit. I already done the above steps, issue still not resolved, do u have any other way such as reset the kubernetes?

**Comment by neolit123** [comment]
hi, try asking for help on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if this is confirmed as a bug, please reopen the ticket.
/close
