### ISSUE TITLE
cluster unjoin node failed 

### ISSUE THREAD

**Issue by skycastlelily2** [kubernetes/kubernetes#88207]
**What happened**:
cluster unjoin node  nodename failed 

[root@dell-pem905-01 lnie]# cluster unjoin node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Can't open unjoin
Can't open node
Can't open dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
always
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 
I follow this link https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ to create a cluster and then kubeadm join  on another machine 
[root@dell-pem905-01 lnie]# kubectl get nodes
NAME                                            STATUS     ROLES    AGE   VERSION
amd-ethanol-01.ml3.eng.bos.redhat.com           NotReady   <none>   20h   v1.17.3
dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com   Ready      <none>   92m   v1.17.3
dell-pem905-01.dell2.lab.eng.bos.redhat.com     Ready      master   25h   v1.17.3
dell-per6415-04.lab2.eng.bos.redhat.com         Ready      <none>   23h   v1.17.3

- OS (e.g: `cat /etc/os-release`):
[root@dell-pem905-01 lnie]# cat /etc/os-release
NAME=Fedora
VERSION="30 (Thirty)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Thirty)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
[root@dell-pe-fm120-1b cri-o]# cat /etc/os-release
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

- Kernel (e.g. `uname -a`):
[root@dell-pem905-01 lnie]# uname -r
5.4.18-100.fc30.x86_64
[root@dell-pe-fm120-1b cri-o]# uname -r 
5.4.17-200.fc31.x86_64
- Install tools:kubeadm init
- Network plugin and version (if this is a network-related bug):cni/flannel
- Others:
[root@dell-pem905-01 lnie]# kubectl describe node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Name:               dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
                    kubernetes.io/os=linux
                    type=testEndNode1
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"b6:fe:b0:ee:a6:ef"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.16.218.23
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 16 Feb 2020 02:31:50 -0500
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
  AcquireTime:     <unset>
  RenewTime:       Sun, 16 Feb 2020 03:54:27 -0500
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Sun, 16 Feb 2020 03:49:57 -0500   Sun, 16 Feb 2020 02:31:50 -0500   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Sun, 16 Feb 2020 03:49:57 -0500   Sun, 16 Feb 2020 02:31:50 -0500   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Sun, 16 Feb 2020 03:49:57 -0500   Sun, 16 Feb 2020 02:31:50 -0500   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Sun, 16 Feb 2020 03:49:57 -0500   Sun, 16 Feb 2020 03:29:56 -0500   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  10.16.218.23
  Hostname:    dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Capacity:
  cpu:                4
  ephemeral-storage:  452490Mi
  hugepages-2Mi:      0
  memory:             16348180Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  427023138109
  hugepages-2Mi:      0
  memory:             16245780Ki
  pods:               110
System Info:
  Machine ID:                 e7c66c46d4564da49192c0df36b2f43b
  System UUID:                4c4c4544-0143-5310-8051-b4c04f433432
  Boot ID:                    a9a4eaa7-03a7-4ff2-9e2d-e1ed88b81bb8
  Kernel Version:             5.4.17-200.fc31.x86_64
  OS Image:                   Fedora 31 (Thirty One)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://18.9.8
  Kubelet Version:            v1.17.3
  Kube-Proxy Version:         v1.17.3
PodCIDR:                      10.244.3.0/24
PodCIDRs:                     10.244.3.0/24
Non-terminated Pods:          (3 in total)
  Namespace                   Name                           CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                           ------------  ----------  ---------------  -------------  ---
  kube-system                 kube-flannel-ds-amd64-lfl7l    100m (2%)     100m (2%)   50Mi (0%)        50Mi (0%)      82m
  kube-system                 kube-proxy-pp8cn               0 (0%)        0 (0%)      0 (0%)           0 (0%)         82m
  mem-example                 memory-demot2                  0 (0%)        0 (0%)      100Mi (0%)       200Mi (1%)     5m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                100m (2%)   100m (2%)
  memory             150Mi (0%)  250Mi (1%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:
  Type    Reason                   Age   From                                                    Message
  ----    ------                   ----  ----                                                    -------
  Normal  NodeReady                25m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com status is now: NodeReady
  Normal  Starting                 24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Starting kubelet.
  Normal  NodeHasSufficientMemory  24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com status is now: NodeHasSufficientPID
  Normal  NodeNotReady             24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com status is now: NodeNotReady
  Normal  NodeAllocatableEnforced  24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Updated Node Allocatable limit across pods
  Normal  NodeReady                24m   kubelet, dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com  Node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com status is now: NodeReady

**Comment by neolit123** [comment]
i don't know where this command is coming from:
```
[root@dell-pem905-01 lnie]# cluster unjoin node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Can't open unjoin
Can't open node
Can't open dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
```

but i don't think this `cluster unjoin` is a tool maintained by the k8s project.

as far as kubeadm managed clusters goes do remove nodes you can do:
```
kubeadm reset # on the problem node
kubectl delete no <node-name> # on a host that has the admin.conf
```

/close
