### ISSUE TITLE
k8s failed to select a node use node name 

### ISSUE THREAD

**Issue by skycastlelily2** [kubernetes/kubernetes#88219]
**What happened**:
I create a cluster on fedora 30,and add another node,I try to create a pod with kubectl -f yaml 
but k8s failed to slelect the node use node name,then I change the yaml to select that  node with 
label,pod is created successfully on that node
```
[root@dell-pem905-01 lnie]# kubectl describe pod memory-demot --namespace=mem-example
Name:         memory-demot
Namespace:    mem-example
Priority:     0
Node:         <none>
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  memory-demo-ctr:
    Image:      polinux/stress
    Port:       <none>
    Host Port:  <none>
    Command:
      stress
    Args:
      --vm
      1
      --vm-bytes
      150M
      --vm-hang
      1
    Limits:
      memory:  200Mi
    Requests:
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cwj9v (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-cwj9v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cwj9v
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  name=dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  46s (x739 over 17h)  default-scheduler  0/4 nodes are available: 4 node(s) didn't match node selector.
``` 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:kubeadm init
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
What labels do you have on your node?

**Comment by skycastlelily2** [comment]
I  try to select the node with name but failed,then I set the node label with 
kubectl label nodes dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com type=testEndNode1
and select the node with label,succeed

**Comment by liggitt** [comment]
node selectors don't operate on the node name, only on the node labels. If you want to directly assign a pod to a node you can do so with the spec.nodeName field. Note that if you also specify a spec.nodeSelector on the pod it must match the node's labels even if you directly assign a spec.nodeName

**Comment by skycastlelily2** [comment]
I try to select the node with nodeName but still failed.This is the yaml I use.
apiVersion: v1
kind: Pod
metadata:
  name: memory-demot6
  namespace: mem-example
spec:
  nodeSelector:
    nodeName: dell-per6415-04.lab2.eng.bos.redhat.com
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]

[root@dell-pem905-01 lnie]# kubectl get nodes
NAME                                          STATUS     ROLES    AGE   VERSION
dell-pem905-01.dell2.lab.eng.bos.redhat.com   Ready      master   42h   v1.17.3
dell-per6415-04.lab2.eng.bos.redhat.com       Ready      <none>   40h   v1.17.3

**Comment by liggitt** [comment]
Not nodeSelector of nodeName,
```
spec:
  nodeName: …
```

**Comment by skycastlelily2** [comment]
It works,thanks for your help and patience
