### ISSUE TITLE
k18s doesn't work with cgroupv2?

### ISSUE THREAD

**Issue by skycastlelily2** [kubernetes/kubernetes#88211]
**What happened**:
I create a cluster with kubeadm init on fedora 30 with docker runtime
the join the cluster on another fedora31 system with cgroupv1 reverted and docker runtime,
then I change runtime to crio,it seems work.
then I change back to cgroupv2 and have crio as the runtime, this time kubelet fails to start
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
[root@dell-pem905-01 lnie]# kubectl describe node dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Name:               dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
                    kubernetes.io/os=linux
                    type=testEndNode1
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"02:18:f9:28:c2:9f"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.16.218.23
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 16 Feb 2020 02:31:50 -0500
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
  AcquireTime:     <unset>
  RenewTime:       Sun, 16 Feb 2020 08:12:15 -0500
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----             ------    -----------------                 ------------------                ------              -------
  MemoryPressure   Unknown   Sun, 16 Feb 2020 07:45:35 -0500   Sun, 16 Feb 2020 07:47:49 -0500   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure     Unknown   Sun, 16 Feb 2020 07:45:35 -0500   Sun, 16 Feb 2020 07:47:49 -0500   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure      Unknown   Sun, 16 Feb 2020 07:45:35 -0500   Sun, 16 Feb 2020 07:47:49 -0500   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready            Unknown   Sun, 16 Feb 2020 07:45:35 -0500   Sun, 16 Feb 2020 07:47:49 -0500   NodeStatusUnknown   Kubelet stopped posting node status.
Addresses:
  InternalIP:  10.16.218.23
  Hostname:    dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com
Capacity:
  cpu:                4
  ephemeral-storage:  452490Mi
  hugepages-2Mi:      0
  memory:             16348180Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  452490Mi
  hugepages-2Mi:      0
  memory:             16245780Ki
  pods:               110
System Info:
  Machine ID:                 e7c66c46d4564da49192c0df36b2f43b
  System UUID:                4c4c4544-0143-5310-8051-b4c04f433432
  Boot ID:                    e7477f84-1467-4295-a809-b02f166d81f9
  Kernel Version:             5.4.17-200.fc31.x86_64
  OS Image:                   Fedora 31 (Thirty One)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  cri-o://1.17.0
  Kubelet Version:            v1.17.3
  Kube-Proxy Version:         v1.17.3
PodCIDR:                      10.244.3.0/24
PodCIDRs:                     10.244.3.0/24
Non-terminated Pods:          (3 in total)
  Namespace                   Name                           CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                           ------------  ----------  ---------------  -------------  ---
  kube-system                 kube-flannel-ds-amd64-lfl7l    100m (2%)     100m (2%)   50Mi (0%)        50Mi (0%)      5h40m
  kube-system                 kube-proxy-pp8cn               0 (0%)        0 (0%)      0 (0%)           0 (0%)         5h40m
  mem-example                 memory-demot5                  0 (0%)        0 (0%)      100Mi (0%)       200Mi (1%)     94m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                100m (2%)   100m (2%)
  memory             150Mi (0%)  250Mi (1%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:

journalctl -xe:
-- The unit run-r912a3c50d2444a1c9de0843ac423e91c.scope has successfully entered the 'dead' state.
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.910558    4634 certificate_store.go:129] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet>
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: W0216 08:08:19.912766    4634 server.go:610] failed to get the kubelet's cgroup: mountpoint for cpu not found.  >
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.919884    4634 server.go:641] --cgroups-per-qos enabled, but --cgroup-root was not specified.  de>
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.920386    4634 container_manager_linux.go:265] container manager verified user specified cgroup-r>
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.920421    4634 container_manager_linux.go:270] Creating Container Manager object based on Node Co>
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.920686    4634 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.920715    4634 container_manager_linux.go:305] Creating device plugin manager: true
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.920771    4634 fake_topology_manager.go:39] [fake topologymanager] AddHintProvider HintProvider: >
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.920840    4634 state_mem.go:36] [cpumanager] initializing new in-memory state store
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.921060    4634 state_mem.go:84] [cpumanager] updated default cpuset: ""
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.921081    4634 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.921104    4634 fake_topology_manager.go:39] [fake topologymanager] AddHintProvider HintProvider: >
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.921290    4634 kubelet.go:286] Adding pod path: /etc/kubernetes/manifests
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.921375    4634 kubelet.go:311] Watching apiserver
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.923982    4634 remote_runtime.go:59] parsed scheme: ""
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924042    4634 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924108    4634 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.>
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924130    4634 clientconn.go:577] ClientConn switching balancer to "pick_first"
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924188    4634 remote_image.go:50] parsed scheme: ""
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924209    4634 remote_image.go:50] scheme "" not registered, fallback to default scheme
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924235    4634 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.>
Feb 16 08:08:19 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:19.924255    4634 clientconn.go:577] ClientConn switching balancer to "pick_first"
Feb 16 08:08:28 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com restraintd[1147]: *** Current Time: Sun Feb 16 08:08:28 2020  Localwatchdog at:  * Disabled! *
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: E0216 08:08:40.214018    4634 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no val>
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.215542    4634 kuberuntime_manager.go:211] Container runtime cri-o initialized, version: 1.17.0, >
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.216292    4634 server.go:1113] Started kubelet
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: E0216 08:08:40.216819    4634 kubelet.go:1302] Image garbage collection failed once. Stats initialization may no>
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.217361    4634 server.go:144] Starting to listen on 0.0.0.0:10250
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.218689    4634 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.219825    4634 volume_manager.go:265] Starting Kubelet Volume Manager
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.220685    4634 desired_state_of_world_populator.go:138] Desired state populator starts to run
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com crio[2270]: time="2020-02-16 08:08:40.220759384-05:00" level=warning msg="imageStatus: can't find k8s.gcr.io/pause:3.1" id=09ee>
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.222231    4634 server.go:384] Adding debug handlers to kubelet server.
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.259892    4634 status_manager.go:157] Starting to sync pod status with apiserver
Feb 16 08:08:40 dell-pe-fm120-1b.dell2.lab.eng.bos.redhat.com kubelet[4634]: I0216 08:08:40.260225    4634 kubelet.go:1820] Starting kubelet main sync loop.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
bare mental
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:kubeadm init
- Network plugin and version (if this is a network-related bug):flannel
- Others:

**Comment by aojea** [comment]
AFAIK cgroups v2 is a WIP
https://github.com/kubernetes/enhancements/pull/1370

**Comment by neolit123** [comment]
yes, cgroups v2 is not supported.
in terms of kubeadm checking if the node has v2 the PR to add that is on hold, until k8s actually supports v2:
https://github.com/kubernetes/system-validators/pull/12

/sig node
/remove-kind bug
/triage support
/close
