### ISSUE TITLE
addon-manager fails to elect leader if running on master instances that have `_` (underscore character) in the hostname

### ISSUE THREAD

**Issue by olegch** [kubernetes/kubernetes#88214]
**What happened**:

When kubernetes addon manager runs on a master instance that has an `_` (underscore character) in the hostname, it fails to elect a leader and never applies addon manifests.

Even though `_` is not an allowed character in the hostnames (RFC 952, RFC 1123) it still can happen due to error or standard misinterpretations (https://en.wikipedia.org/wiki/Hostname). Not all linux distributions enforce this requirement, so for example CentOS instances can be configured with a hostname containing underscore characters.

**What you expected to happen**:

Addon manager to be able to elec a leader and apply addon manifests.

**How to reproduce it (as minimally and precisely as possible)**:

Run addon manager with leader election enabled on a master with and underscore in the hostname.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: any
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Install tools: any using addon-manager
- Network plugin and version (if this is a network-related bug):  n/a
- Others: n/a

**Comment by olegch** [comment]
PR with a suggested fix for the issue: https://github.com/kubernetes/kubernetes/pull/88215

**Comment by neolit123** [comment]
FYI, the addon manager is deprecated and should not be used in production clusters.

**Comment by olegch** [comment]
Yes, I agree, considering that addon-manager is deprecated, and that hostnames with underscore is a non-standard situation breaking RFC, it is not clear if this issue even needs to be fixed.
Just putting it here for documentation purposes and for the community to decide.
