### ISSUE TITLE
failed to join the cluster with /usr/libexec/kubernetes: read-only file system

### ISSUE THREAD

**Issue by skycastlelily2** [kubernetes/kubernetes#88210]
**What happened**:
I have create a cluster on fedora coreos with kubeadm,
but failed to join in the cluster，
systemctl status kubelet shows:mkdir /usr/libexec/kubernetes: read-only file system
I then tried to add KUBELET_VOLUME_PLUGIN="--volume-plugin-dir=/var/lib/kubelet/volumeplugins" to /var/lib/kubelet/kubeadm-flags.env,but still failed the same.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
always
**Anything else we need to know?**:
[root@localhost bin]# kubectl get nodes
NAME        STATUS   ROLES    AGE     VERSION
localhost   Ready    master   3h57m   v1.17.3
[root@localhost bin]# kubectl describe nodes localhost
Name:               localhost
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=localhost
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 16 Feb 2020 08:21:52 +0000
Taints:             node-role.kubernetes.io/master:NoSchedule
                    node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  localhost
  AcquireTime:     <unset>
  RenewTime:       Sun, 16 Feb 2020 12:19:12 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Sun, 16 Feb 2020 12:15:13 +0000   Sun, 16 Feb 2020 08:21:48 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Sun, 16 Feb 2020 12:15:13 +0000   Sun, 16 Feb 2020 08:21:48 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Sun, 16 Feb 2020 12:15:13 +0000   Sun, 16 Feb 2020 08:21:48 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Sun, 16 Feb 2020 12:15:13 +0000   Sun, 16 Feb 2020 08:22:16 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.122.118
  Hostname:    localhost
Capacity:
  cpu:                2
  ephemeral-storage:  15193068Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             2029164Ki
  pods:               110
Allocatable:
  cpu:                2
  ephemeral-storage:  14001931446
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             1926764Ki
  pods:               110
System Info:
  Machine ID:                 a4c8736868564d22ae726990c239b27d
  System UUID:                a4c87368-6856-4d22-ae72-6990c239b27d
  Boot ID:                    15c78d5d-9f25-45c8-8d64-7b23722bd7a1
  Kernel Version:             5.4.13-201.fc31.x86_64
  OS Image:                   Fedora CoreOS 31.20200127.3.0
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://18.9.8
  Kubelet Version:            v1.17.3
  Kube-Proxy Version:         v1.17.3
Non-terminated Pods:          (4 in total)
  Namespace                   Name                                 CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                 ------------  ----------  ---------------  -------------  ---
  kube-system                 etcd-localhost                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         3h57m
  kube-system                 kube-apiserver-localhost             250m (12%)    0 (0%)      0 (0%)           0 (0%)         3h57m
  kube-system                 kube-controller-manager-localhost    200m (10%)    0 (0%)      0 (0%)           0 (0%)         3h57m
  kube-system                 kube-scheduler-localhost             100m (5%)     0 (0%)      0 (0%)           0 (0%)         3h57m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                550m (27%)  0 (0%)
  memory             0 (0%)      0 (0%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:              <none>

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
virtual machine 
- OS (e.g: `cat /etc/os-release`):
[root@localhost bin]# cat /etc/os-release
NAME=Fedora
VERSION="31.20200127.3.0 (CoreOS)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora CoreOS 31.20200127.3.0"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='31.20200127.3.0'
- Kernel (e.g. `uname -a`):
5.4.13-201.fc31.x86_64
- Install tools:kubeadm init
- Network plugin and version (if this is a network-related bug):flannel
- Others:
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Sun 2020-02-16 10:24:45 UTC; 1h 58min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 66419 (kubelet)
    Tasks: 16 (limit: 2297)
   Memory: 32.3M
   CGroup: /system.slice/kubelet.service
           └─66419 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1

Feb 16 12:18:10 localhost kubelet[66419]: E0216 12:18:10.938430   66419 pod_workers.go:191] Error syncing pod 2ec8c951d5bec8c6f385c0a277bf90b1 ("kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[k8s-certs kubeconfig ca-certs etc-pki flexvolume-dir]: timed out waiting for the condition
Feb 16 12:19:06 localhost kubelet[66419]: E0216 12:19:06.873082   66419 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir\" (\"2ec8c951d5bec8c6f385c0a277bf90b1\")" failed. No retries permitted until 2020-02-16 12:21:08.87300065 +0000 UTC m=+6983.437108662 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir\") pod \"kube-controller-manager-localhost\" (UID: \"2ec8c951d5bec8c6f385c0a277bf90b1\") : mkdir /usr/libexec/kubernetes: read-only file system"
Feb 16 12:20:06 localhost kubelet[66419]: E0216 12:20:06.041189   66419 container_manager_linux.go:466] cpu and memory cgroup hierarchy not unified.  cpu: /system.slice, memory: /system.slice/docker.service
Feb 16 12:20:06 localhost kubelet[66419]: E0216 12:20:06.041352   66419 container_manager_linux.go:511] failed to find cgroups of kubelet - cpu and memory cgroup hierarchy not unified.  cpu: /system.slice, memory: /system.slice/kubelet.service
Feb 16 12:20:26 localhost kubelet[66419]: E0216 12:20:26.935662   66419 kubelet.go:1680] Unable to attach or mount volumes for pod "kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)": unmounted volumes=[flexvolume-dir], unattached volumes=[etc-pki flexvolume-dir k8s-certs kubeconfig ca-certs]: timed out waiting for the condition; skipping pod
Feb 16 12:20:26 localhost kubelet[66419]: E0216 12:20:26.937434   66419 pod_workers.go:191] Error syncing pod 2ec8c951d5bec8c6f385c0a277bf90b1 ("kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[etc-pki flexvolume-dir k8s-certs kubeconfig ca-certs]: timed out waiting for the condition
Feb 16 12:21:08 localhost kubelet[66419]: E0216 12:21:08.880187   66419 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir\" (\"2ec8c951d5bec8c6f385c0a277bf90b1\")" failed. No retries permitted until 2020-02-16 12:23:10.880040391 +0000 UTC m=+7105.444148405 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir\") pod \"kube-controller-manager-localhost\" (UID: \"2ec8c951d5bec8c6f385c0a277bf90b1\") : mkdir /usr/libexec/kubernetes: read-only file system"
Feb 16 12:22:43 localhost kubelet[66419]: E0216 12:22:43.935055   66419 kubelet.go:1680] Unable to attach or mount volumes for pod "kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)": unmounted volumes=[flexvolume-dir], unattached volumes=[kubeconfig ca-certs etc-pki flexvolume-dir k8s-certs]: timed out waiting for the condition; skipping pod
Feb 16 12:22:43 localhost kubelet[66419]: E0216 12:22:43.935210   66419 pod_workers.go:191] Error syncing pod 2ec8c951d5bec8c6f385c0a277bf90b1 ("kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[kubeconfig ca-certs etc-pki flexvolume-dir k8s-certs]: timed out waiting for the condition

**Comment by neolit123** [comment]
closing in favor of:
https://github.com/kubernetes/kubeadm/issues/2031

the KCM default for flex-volumes points to a path that is R/O:
`--flex-volume-plugin-dir string     Default: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"`
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
