### ISSUE TITLE
No details given on PVC when WaitForFirstConsumer binding fails

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#88229]
**What happened**:
With a StorageClass with `volumeBindingMode= WaitForFirstConsumer`, it's not clear why a PVC is not bound when there is no available PV.

On Pod, there is a  clear event what's wrong:
```
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```

On the PVC side we get only this event:
```
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  WaitForFirstConsumer  2s (x26 over 6m4s)  persistentvolume-controller  waiting for first consumer to be created before binding
```

Note that the message says "waiting for first consumer'. But the pod already exists. The reason why it's not bound yet is that the StorageClass has no dynamic provisioning configured (`provisioner: kubernetes.io/no-provisioner`) and there are no free PVs to satisfy the claim.

**What you expected to happen**:
An event "1 node(s) didn't find available persistent volumes to bind" on the PVC.

**Comment by jsafrane** [comment]
I tried to fix this in VolumeBinding predicate, https://github.com/kubernetes/kubernetes/pull/88163. The predicate is called for each pod - node combination, so it would generate event for each node. Which is too much and it's even wrong when there is a node that has an available PV.

We need to evaluate all nodes and then, if the pod is still unschedulable, distribute events to all unbound PVCs of that pod. Scheduler does not offer any way how to track unbound PVCs at that stage - whole volume logic is hidden in VolumeBinding predicate.

One option would be to extend [`v1alpha1.Status`](https://github.com/kubernetes/kubernetes/blob/f5b7e3cca355ab5aef06d5def2aa1f71bd4b9b92/pkg/scheduler/framework/v1alpha1/interface.go#L100-L103
) struct to contain also list of related objects:

```patch
type Status struct {
	code    Code
	reasons []string
+	relatedObjects map[types.UID]runtime.Object
}
```

* Scheduler would then send all failed scheduling events it sends to a pod to all the `relatedObjects`, without any interpretation.
* `map[types.UID]` is used to manage duplicates easily - each object (its UID) can be in the map only once. Simple array is a working option.
* `runtime.Object` is extensible to allow any object types. `VolumeBinding` predicate would put all unbound PVCs there.
* `VolumeBinding` does not need any special handling of each PVC. In case a pod uses multiple PVCs, each of them might be bind-able on different nodes (node A may satisfy PVC1, but not PVC2, while node B may satisfy PVC2 only). Message "2 node(s) didn't find available persistent volumes to bind" sounds just right.

**Comment by jsafrane** [comment]
I tried to fix this in VolumeBinding predicate, https://github.com/kubernetes/kubernetes/pull/88163. The predicate is called for each pod - node combination, so it would generate event for each node. Which is too much and it's even wrong when there is a node that has an available PV.

We need to evaluate all nodes and then, if the pod is still unschedulable, distribute events to all unbound PVCs of that pod. Scheduler does not offer any way how to track unbound PVCs at that stage - whole volume logic is hidden in VolumeBinding predicate.

One option would be to extend [`v1alpha1.Status`](https://github.com/kubernetes/kubernetes/blob/f5b7e3cca355ab5aef06d5def2aa1f71bd4b9b92/pkg/scheduler/framework/v1alpha1/interface.go#L100-L103
) struct to contain also list of objects where to send events (except the pod itself):

```patch
type Status struct {
	code    Code
	reasons []string
+	notifyObjects map[types.UID]runtime.Object
}
```

* Scheduler would then send all failed scheduling events it sends to a pod to all the `notifyObjects`, without any interpretation.
* `map[types.UID]` is used to manage duplicates easily - each object (its UID) can be in the map only once. Simple array would work too, but then it needs extra work in [PluginToStatus.Merge](https://github.com/kubernetes/kubernetes/blob/f5b7e3cca355ab5aef06d5def2aa1f71bd4b9b92/pkg/scheduler/framework/v1alpha1/interface.go#L165) removing duplicates. Not sure how easy it is to detect duplicate `runtime.Object` instances.
* `runtime.Object` is extensible to allow any object type. `VolumeBinding` predicate would put all unbound PVCs there.
* `VolumeBinding` does not need any special handling of each PVC. Message "2 node(s) didn't find available persistent volumes to bind" sounds just right in case a pod uses multiple PVCs, each of them might be bind-able on different nodes (node A may satisfy PVC1, but not PVC2, while node B may satisfy PVC2 only).

@bsalamat @msau42, what do you think about such design?

**Comment by Huang-Wei** [comment]
We used to have `PostFilter()` extension point, which I believe is the right moment for recording the event for unbounds PVCs. But recently it's been refactored so doesn't fit.

@alculquicondor @ahg-g Do you think this case can be a good example of using `PostFilter()` as an informational extension point?

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

@cofyc wdyt?

**Comment by cofyc** [comment]
I have some other concerns. What if the pod is deleted? Should the scheduler send events that PVC is not in volume binding?

The PV controller must be updated to stop emit `waiting for first consumer to be created before binding` event in this scenario. It might be simpler to solve on the PV controller side.

https://github.com/kubernetes/kubernetes/blob/ba2855eaa5c0e4f6b0bb32047f9f832ab1ee14f2/pkg/controller/volume/persistentvolume/pv_controller.go#L321-L323

In this function, we can check if the PVC is being used by a pod. If it is, we can send event like `binding with the pod "foo/bar"`, then people can go to check the progress of pod "foo/bar".

If the pod "foo/bar" is deleted, the PV controller can emit "waiting for first consumer ..." event again.

What do you think? cc @jsafrane @msau42

**Comment by jsafrane** [comment]
Sounds better than it's now. My only issue may be performance - PV controller has to check if a pod exists, i.e. list all pods in the same namespace as PVC being reconciled. I am probably too worried.

**Comment by cofyc** [comment]
current attach detach controller has a custom indexer to index pods by PVC keys to avoid iterating all pods every time to find pods which reference given PVC. 
https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/attachdetach/attach_detach_controller.go#L199-L203

And there are other places we need to check if a PVC is used by a pod or not from pod informer, e.g. 

- pvc_protection_controller [askInformer](https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L231-L247)
- pv_controller [isVolumeUsed](https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/persistentvolume/pv_controller.go#L1298-L1321)

we can try to share this custom indexer among these volume controllers in the future. This will improve the overall performance of the `kube-controller-manager` IMO. What do you think？

**Comment by jsafrane** [comment]
Yes, using the indexer looks like a good idea.

**Comment by alculquicondor** [comment]
/remove-sig scheduling

I also agree that solving in PVC side seems like a better idea.

**Comment by cofyc** [comment]
/assign

unbound claims are reconciled in the PV controller every 15 seconds, we may have bad worst-case performance. we can add an indexer in the PV controller locally to solve this issue first (also optimize [isVolumeUsed](https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/persistentvolume/pv_controller.go#L1298-L1321), then find a way to share the indexer between controllers in manager to improve the overall performance.
