### ISSUE TITLE
Scheduler not attempting to schedule CoreDNS pods

### ISSUE THREAD

**Issue by shalev123d** [kubernetes/kubernetes#88225]
Hey everyone!

**What happened**:
After an unexpected reboot event, we started noticing some weird behavior in our cluster, when we tried to troubleshoot everything we noticed that the CoreDNS deployment was 0/2 from the desired state. When initiating kubectl get pods -n kube-system, we don't see any CoreDNS pods in any state, not failing, not running, just nothing.

We tried to 'redeploy' by "kubectl patch" and adding labels/changing the number of replicas, but still, no pods are spawning.

**What you expected to happen**:

See the CoreDNS pods (kubectl get pods -n kube-system), even if in failed state.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure, probably sudden reboot.

**Anything else we need to know?**:

Much thanks!

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17
- Cloud provider or hardware configuration: On-Prem
- OS (e.g: `cat /etc/os-release`): RHEL 7.7
- Kernel (e.g. `uname -a`): 3.10.0-1062.4.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Callico
- Others:

**Comment by neolit123** [comment]
@shalev123d 

any logs that might help debug this?

> Kubernetes version (use kubectl version): v1.17

if you are on 1.17.0 not that there are critical bugs.
you should upgrade to the latest PATCH version.

**Comment by shalev123d** [comment]
Apologies, We're on 1.17.2.
I'm not sure what logs to provide here since I don't have access to the pods, but I tried to upgrade to 17.1.3 now, and the kubeadm upgrade surprisingly hangs here:

[addons]: Migrating CoreDNS Corefile
[addons] Applied essential addon: CoreDNS

 Could you please guide me regarding what logs would be useful?

Thanks!

**Comment by neolit123** [comment]
please provide the output from `kubectl get po -n kube-system`.

if there are coredns pods in the list that are not running call this on one of them:
`kubectl describe po -n kube-system <pod-name>`
and provide the output.
