### ISSUE TITLE
Redeply pods depending on load of nodes

### ISSUE THREAD

**Issue by hase1128** [kubernetes/kubernetes#88232]
**What would you like to be added**:
I want the new kubectl command for redeploy pods between kubernetes nodes depending on load of nodes.
e.g. kubectl balance pod

**Why is this needed**:
when one nodes is down due to some trouble, the pod running on the node is evicted to another nodes.
Even if we solve the trouble and succeed to recover the node, existing pods don't run on the node unless some event occurs such as new pod creation.
In this case, load imbalance occurs between Kubernetes nodes, and we should pod deletion and re-creation manually if we address the load imbalance situation.
so, I want to the command which redeploy the pods for keeping load balance between the nodes.

**Comment by ahg-g** [comment]
did you try rolling restart: https://v1-16.docs.kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-restart-em-

**Comment by ahg-g** [comment]
Here is the list of resources that restart is implemented for: https://github.com/kubernetes/kubernetes/blob/1e12d92a5179dbfeb455c79dbf9120c8536e5f9c/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go#L32

it includes: ```Deployment```, ```DaemonSet``` and ```StatefulSet```

**Comment by hase1128** [comment]
@ahg-g 
thanks for the information!
`kubectl rollout restart` is very similar what I want.
but this command increase revision of resource.

if user is associating their application's feature and revision numbers, it may occur unexpected trouble.
Is there a way to keep revision number?

**Comment by ahg-g** [comment]
Not using the restart command because it is effectively a deployment update.

Your other option is using something like the descheduler: https://github.com/kubernetes-sigs/descheduler, although it doesn't have a rebalancing strategy yet.

**Comment by hase1128** [comment]
Understood.
In the current k/k community, is it possible to consider developing such a feature?

**Comment by hase1128** [comment]
I close this FR. I ask this in descheduler.
