### ISSUE TITLE
Issue with Command kubectl delete clusterrolebinding --all

### ISSUE THREAD

**Issue by isildurmac** [kubernetes/kubernetes#88250]
Hi all.
I has a kubernetes cluster in 3 VM with Ubuntu 18.04. One master and 2 worker.
By my mistake I ran this command: kubectl delete clusterrolebinding --all
After that issue I ran with several issues:
root@k8master:~# kubectl get pods --all-namespaces
NAMESPACE              NAME                                         READY   STATUS      RESTARTS   AGE
default                mysql-c85f7f79c-f4ph6                        0/1     Pending     0          18h
default                nginx-86c57db685-9dk74                       1/1     Running     0          42h
**kube-system            coredns-6955765f44-prchn                     0/1     Completed   0          3d23h
kube-system            coredns-6955765f44-s9nmw                     0/1     Completed   0          3d23h**
kube-system            etcd-k8master                                1/1     Running     2          3d23h
kube-system            kube-apiserver-k8master                      1/1     Running     3          3d23h
kube-system            kube-controller-manager-k8master             1/1     Running     5          3d23h
kube-system            kube-flannel-ds-amd64-9ntgr                  1/1     Running     0          3d1h
**kube-system            kube-flannel-ds-amd64-pt8ld              0/1     CrashLoopBackOff   192        3d2h**
kube-system            kube-flannel-ds-amd64-tplc4                  1/1     Running     0          3d1h
kube-system            kube-proxy-5hct6                             1/1     Running     0          3d1h
kube-system            kube-proxy-67p4s                             1/1     Running     0          3d1h
kube-system            kube-proxy-n7rs5                             1/1     Running     2          3d23h
kube-system            kube-scheduler-k8master                      1/1     Running     5          3d23h
kubernetes-dashboard   dashboard-metrics-scraper-7b8b58dc8b-dhdjr   1/1     Running     0          18h
kubernetes-dashboard   kubernetes-dashboard-866f987876-5c2zp        1/1     Running     0          18h

Flannel log:
E0217 18:38:38.368727       1 main.go:241] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-amd64-pt8ld': Get https://10.96.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-amd64-pt8ld: dial tcp 10.96.0.1:443: i/o timeout

CoreDNS log:
pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpoints" in API group "" at the cluster scope

It´s possible to recover that cluster or I need to create another cluster :-D?

Regards.

**Comment by liggitt** [comment]
Restarting the apiserver will recreate the default bindings required for the control plane (controller manager, scheduler) and kube-proxy to function. You'll need to recreate any other bindings that are required for your additional addons or applications to run.
