### ISSUE TITLE
CRD validation error for x-kubernetes-preserve-unknown-fields: true

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#88252]
**What happened**:
I have CRD with a spec field of type `runtime.RawExtension` and annotation `x-kubernetes-preserve-unknown-fields: true`. I want to store json data in this field which is actually a Grafana Dashboard json.

When I try to create a CR of this type, I am getting validation error from json bytes. `error validating data: unknown object type "nil" in Dashboard.spec.model.gnetId;` . In the json data `.spec.model.gnetId: null`.

**What you expected to happen**:

I expected no error since I set `x-kubernetes-preserve-unknown-fields: true`

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kind create cluster

$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.17.0

# create CRD
$ kubectl create -f https://github.com/searchlight/grafana-operator/raw/f1dc2cce10f9849405d1f45c4fb33fb0221d5e9d/api/crds/grafana.searchlight.dev_dashboards.yaml


# validation error
$ kubectl create -f https://github.com/searchlight/grafana-operator/raw/f1dc2cce10f9849405d1f45c4fb33fb0221d5e9d/hack/examples/dashboard2.yaml

error: error validating "https://github.com/searchlight/grafana-operator/raw/f1dc2cce10f9849405d1f45c4fb33fb0221d5e9d/hack/examples/dashboard2.yaml": error validating data: unknown object type "nil" in Dashboard.spec.model.gnetId; if you choose to ignore these errors, turn validation off with --validate=false


# works, as removed the `.spec.model.gnetId` field
$ kubectl create -f https://github.com/searchlight/grafana-operator/raw/83f8a0fa7da470e79151220ab2b85cae75a38a9c/hack/examples/dashboard2-valid.yaml

dashboard.grafana.searchlight.dev/dashboard2-valid created
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.0
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery
/area custom-resources

**Comment by tamalsaha** [comment]
cc: @sttts

**Comment by tedyu** [comment]
```
$ kubectl create -f https://github.com/searchlight/grafana-operator/raw/f1dc2cce10f9849405d1f45c4fb33fb0221d5e9d/api/crds/grafana.searchlight.dev_dashboards.yaml
customresourcedefinition.apiextensions.k8s.io/dashboards.grafana.searchlight.dev created

$ kubectl version --short
Client Version: v1.17.2
Server Version: v1.16.2
```

**Comment by tamalsaha** [comment]
@tedyu , you are able to create the CRD, which is also working for me.

Are you able to create the CR for this CRD? Does the following command work for you?

```
kubectl create -f https://github.com/searchlight/grafana-operator/raw/f1dc2cce10f9849405d1f45c4fb33fb0221d5e9d/hack/examples/dashboard2.yaml
```

**Comment by tedyu** [comment]
I used your first command (against 1.16 server) which passed (without validation error).

This might be regression in 1.17

**Comment by tamalsaha** [comment]
I think you have not read the issue clearly. The CRD creation is working fine. I am getting validation error when trying to create CR for this CRD.

**Comment by tedyu** [comment]
I edited the previous comment with result for second command.

**Comment by tamalsaha** [comment]
Thanks @tedyu ! This is the issue I see. I expected no error since I set `x-kubernetes-preserve-unknown-fields: true`.

**Comment by liggitt** [comment]
If you pass --validate=false, does it create successfully?

**Comment by tamalsaha** [comment]
Yes, if I pass --validate=false, it creates successfully.

**Comment by liggitt** [comment]
Then the issue is in client-side kubectl validation

**Comment by liggitt** [comment]
/cc @apelisse 
for openapi validation

**Comment by apelisse** [comment]
Yeah, we should probably make anything that has the `x-kubernetes-preserve-unknown-fields: true` accept anything. I thought we already did so for types that are `runtime.RawExtension`. Maybe this never landed actually, I could look it up.

**Comment by apelisse** [comment]
That's probably not super hard to solve if someone wants to try.

**Comment by apelisse** [comment]
A good way to start would be to solve all the TODOs in https://github.com/kubernetes/kube-openapi/blob/master/pkg/util/proto/document.go.

Or possibly, to address this bug specifically:
This is the function that validates the "kind" (i.e. structures): https://github.com/kubernetes/kube-openapi/blob/master/pkg/util/proto/validation/types.go#L103-L128

When I initially wrote this code, we assumed that these type would never have additionalProperties.

We probably need to change this condition since it's not really valid:
https://github.com/kubernetes/kube-openapi/blob/master/pkg/util/proto/document.go#L243-L256 and this one: https://github.com/kubernetes/kube-openapi/blob/master/pkg/util/proto/document.go#L261-L265

We create the kind here:
https://github.com/kubernetes/kube-openapi/blob/master/pkg/util/proto/document.go#L197-L225. That function would have to be changed to save the "additionalProperties" type (if given) or the ability to have additionalProperties.

**Comment by apelisse** [comment]
Actually, the problem also is that it doesn't know how to handle null. This one is a little tricky.

**Comment by sttts** [comment]
I think the publishing of the "object" type must be supressed for `x-kubernetes-preserve-unknown-fields: true` fields. We have similar cases already.

Touching kubectl is not very effective, or at least it takes multiple releases to makes its way through the ecosystem.
