### ISSUE TITLE
Declarative rolling-update

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#8827]
I was trying to apply a rolling update and was surprised by this message:

```
Error: app.rc.json cannot have the same name as the existing ReplicationController app
```

I am using a `version` label to differentiate between versions, but we're using images pointing to `latest`, so I can't use `--image`. Why am I still forced to rename the RC every time I want to do an upgrade?

It would be nice if Kubernetes internally handled name conflicts during upgrades (and possibly use a hash of the RC json to see if any changes where made)

**Comment by aronchick** [comment]
There's an additional bug here around name conflicts on rolling updates, that I'm not sure if you'd like to split out.

```
$ cluster/kubectl.sh create -f demos/purple-rc.yml
Starting cluster using os distro: debian
current-context: "green-snowflake-95422_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../platforms/darwin/amd64/kubectl create -f demos/blue-rc.yml
replicationcontrollers/purple

$ cluster/kubectl.sh create -f demos/blue-rc.yml
Starting cluster using os distro: debian
current-context: "green-snowflake-95422_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../platforms/darwin/amd64/kubectl create -f demos/blue-rc.yml
replicationcontrollers/blue

$ cluster/kubectl.sh rolling-update purple --update-period=3s -f demos/blue-rc.yml
Starting cluster using os distro: debian
current-context: "green-snowflake-95422_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../platforms/darwin/amd64/kubectl rolling-update purple --update-period=3s -f demos/blue-rc.yml
Continuing update with existing controller blue.
Error: Missing/unexpected annotations for controller blue: map[]
```

Expected: Notification that there was a name conflict.

**Comment by bgrant0607** [comment]
@JeanMertz So what are you updating if not the image name? We could add another option similar to --image.

Is the problem that the new RC has a different name, or just that you need to specify the new name?

You could also potentially use GenerateName to auto-generate a new RC name, though we might need to fix checks in kubectl to allow it.

It's explicitly called out in the documentation, which we should fix:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl_rolling-update.md

The eventual solution to this is the Deployment API: #1743. 

@aronchick The clue was that it thought you were trying to resume an update, which is valid and supported, not a name conflict. I agree that we shouldn't just dump an internal implementation error message.

**Comment by bgrant0607** [comment]
More generally, my interpretation of this is that it would be useful to be able to declaratively update an existing pod template (e.g., via an edit command #8263) and kick off a rolling update. I agree with that. However, the Right Way to do that would be via configuration reconciliation (#1702) with a runtime object that managed the rollout (i.e., Deployment #1743).

**Comment by bgrant0607** [comment]
@aronchick Please file a separate issue for the obscure error message.

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by lavalamp** [comment]
> we're using images pointing to latest

@JeanMertz I'd recommend not doing that, as it defeats the purpose of the rolling update. If you re-use "latest" when pushing a new container, you can no longer effectively roll back.

If you do want to always use latest, the way to do a rolling update would be to just slowly kill each pod, and let the RC make a new one. But that's not that convenient.

Is there still an issue here?

**Comment by JeanMertz** [comment]
@lavalamp good point.

Given that, this workflow should work as expected, right?

* initial deploy using `kubectl create -f rc.json`, pointing to `my/app:latest`, which is a pointer to `my/app:v1.0.0`
* rolling update using `kubectl rolling-update frontend --image=my/app:v1.1.0`
* after terrible infra-crash new "initial deploy" using `kubectl create -f rc.json`, pointing to `my/app:latest` (which now is a pointer to `my/app:v1.1.0`)
* rolling update using `kubectl rolling-update frontend --image=my/app:v1.2.0`

This will support rolling-restarts as well as rollbacks, and allows us to not update the `rc.json` file for every new release, but still have it point to the latest stable release whenever we have to re-run the json.

**Comment by lavalamp** [comment]
@JeanMertz Yeah I think that will work. But it sounds a bit dangerous to me, because if you don't check what version is currently deployed before you do a rolling update, you won't know what to roll back to should it have a problem?

Perhaps this is style difference, but I think if it were me, I would always use literal version numbers in the config file and track which is the latest stable one elsewhere. This works especially well if you keep your config in source control, and use a workflow where you commit a change, then push to your cluster.

**Comment by JeanMertz** [comment]
@lavalamp yeah, but we have a continuous deploy cycle where each commit on master - when the CI is green - is auto deployed.

Transitioning to Kubernetes, we're looking how this workflow fits with the Kubernetes release process.

Unfortunately, I just got this error:

> Image update is not supported for multi-container pods

So I guess my above workflow won't work after all. Back to the drawing board.

**Comment by lavalamp** [comment]
@JeanMertz ah-- in that case, I suggest using the git hash for the version. Has the nice property that you can easily find the exact code that's running.

**Comment by JeanMertz** [comment]
@lavalamp you are right, and in fact that is what we're doing already. Each git commit gets a tagged image in the gcr.io image repository.

However, that does not help me, because we'd still have to update the json file for each commit to master, which gets cumbersome. Automated updates/commits of the json file could be a possibility, but polutes the Git history.

Other than waiting for the multi-container `--image` support, I can't seem to find a way to make our workflow work with the current options.

**Comment by lavalamp** [comment]
@JeanMertz Sounds like you need to parameterize your config file. e.g. have {VERSION} in the .json file and pipe it through sed or something on the way to kubectl.

I was just chatting with @bgrant0607 about this; parameterization of config files is on our radar, but we don't have a good canned solution yet.

**Comment by lavalamp** [comment]
You could potentially also have the script that tags your image also spit out the command line or the config to do the rolling update.

**Comment by bgrant0607** [comment]
It sounds like want you want to do is resolve latest to a specific version at deployment time: #1697

**Comment by bgrant0607** [comment]
FWIW, committing a new version of the config file when deploying a new image version is exactly what we do inside Google.

Though the support isn't built-in, it wouldn't be hard to templatize the image field. You could substitute the tag with a one-line shell script.

I also believe Openshift does what you want, if you want to check that out.

**Comment by JeanMertz** [comment]
@bgrant0607 and @lavalamp thanks for that input.

I guess it's a difference in philosophy, in our strategy:

* every commit in `master` is treated as a release
* the CI is repsonsible for building the (Docker) image after all tests pass, and then triggers a deploy
* Git tags aren't used, instead we rely on Git refs
* each new image gets the current Git ref as its tag
* each new release also updates the `latest` tag to point to the latest release
* rollback consists of getting the parent of the current commit, and deploying the image with that ref as its tag

Given this, the `--image` based `rolling-update` certainly fits our update-strategy best. In that regard, I'm really looking forward to multi-container pods being able to use `--image` as well.

The only reason I'd suggest setting the *initial* version to the `latest` is to recover from a disaster scenario where a application's rc is gone, and has to be created again, in this case, simply using the existing rc json file results in the correct situation, as the latest image version will be re-deployed. Other than this situation, `latest` is never used.

**Comment by bgrant0607** [comment]
Closing in favor on ongoing work on Deployment and #1697:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deployment.md

cc @nikhiljindal @ironcladlou
