### ISSUE TITLE
Support passing Context and Options for client-go non-generated Scale client

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#88274]
**What would you like to be added**:
It would be great if Context and Options could be passed for the Scale subresource client in client-go.

https://github.com/kubernetes/client-go/blob/0ff5a65499e672956d25228b15354d4083973fe7/scale/interfaces.go#L32-L44

**Why is this needed**:
Similar to the change https://github.com/kubernetes/kubernetes/pull/87952.

Options would allow passing dry-run or fieldManager, and Context would allow propagating timeouts, cancellations, and tracing.

Not sure if there are other subresources to track yet

Related issues:
- https://github.com/kubernetes/client-go/issues/635
- https://github.com/kubernetes/enhancements/pull/1503

/sig api-machinery
cc @mikedanese

**Comment by julianvmodesto** [comment]
Actually would be nice to have for Evict too, which seems to be an extension for Pods.

**Comment by julianvmodesto** [comment]
Okay after looking at this, the change I referenced was for generated clientsets. However, there are non-generated clients in client-go, including the scale client.

Other clients include the dynamic client, metadata client, and event client.

The dynamic client interface is probably the next most interesting one.

**Comment by julianvmodesto** [comment]
cc @liggitt

**Comment by liggitt** [comment]
dynamic client update in https://github.com/kubernetes/kubernetes/pull/88906

**Comment by mikedanese** [comment]
Does this one need the milestone as well? What are your plans?

**Comment by liggitt** [comment]
Added milestone to https://github.com/kubernetes/kubernetes/pull/88599 and held. Running tests on the metadata client update now, then will submit an exception request for those three PRs to round out the feature.

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/88599
