### ISSUE TITLE
Ability to define pod affinity on namespace level

### ISSUE THREAD

**Issue by ameir** [kubernetes/kubernetes#88272]
**What would you like to be added**:
Pod affinity/anti-affinity rules provide a lot of power in scheduling pods, but must be defined per-pod.  In our case, we have a dedicated namespace (e.g. `kube-addons`) where we run utility-type services like ExternalDNS, the ALB ingress controller, the Kubernetes dashboard, etc.  We would like to have these services prefer a specific set of nodes, where available.  We would likely also do the same for the `kube-system` namespace so that other nodes, by default, would only be running application pods, with the exception of daemonsets, of course.

Instead of updating each manifest for each service to define affinity, it would be much easier to define this on the namespace level, and pods would automatically be attracted to matching nodes during scheduling.

**Why is this needed**:
This would greatly ease the configuration of pod affinity within this use case, especially in instances where templates are installed via Helm, and direct control of the applied manifest is not straightforward.

Note: this is similar to, but closer to the inverse of, https://github.com/kubernetes/kubernetes/issues/68827.

**Comment by wgliang** [comment]
@ameir It looks like this issue can start with KEP.

**Comment by ameir** [comment]
Thanks, @wgliang. Should I file the issue in https://github.com/kubernetes/enhancements or is it okay to stay here?

**Comment by tehmoon** [comment]
Hi!
Any update/advise on this? I'm trying to find a way to bulk select everything that would deploy a pod (job/st/deployment/daemon...) to set a node affinity on them.
So far I only had luck with patching all the kind of resources with kustomize. It's a lot of code duplication.

Thank you for your time.

**Comment by asoltesz** [comment]
This is an important feature because it allows a cleaner separation of concerns between operations teams and development teams.

Namespace attributes could be managed by operations who know what affinities are needed. 

As it is, development teams need to make affinities configurable and very often, these get hard-coded into descriptors.
