### ISSUE TITLE
BootstrapArguments only allows = sign in --register-with-taints option.

### ISSUE THREAD

**Issue by tretos53** [kubernetes/kubernetes#88271]
**What happened**: `BootstrapArguments` only allows `=` (equal) sign when used with `--register-with-taints`. 

`--register-with-taints=\"node.kubernetes.io=unschedulable:NoSchedule\"` is allowed.
`--register-with-taints=\"node.kubernetes.io/unschedulable:NoSchedule\"` is not allowed.

**What you expected to happen**: BootstrapArguments to allow `--register-with-taints=\"node.kubernetes.io/unschedulable:NoSchedule\"`

**How to reproduce it (as minimally and precisely as possible)**: Create a new Cloud Formation template that build EKS node and add to the cluster. Configure BootstrapArguments with --register-with-taints option.

**Anything else we need to know?**: When adding BootstrapArguments to cloud formation, the only format allowed is:
`--kubelet-extra-args '--node-labels=\"label1=key1,label2=key2,label3=key3\" --register-with-taints=\"node.kubernetes.io=unschedulable:NoSchedule\"' --enable-docker-bridge true`

Above is not an equivalent of `kubectl drain node <node>` or `kubectl taint nodes <node> node.kubernetes.io/unschedulable:NoSchedule` and DeamonSets that are not in kube-system namespace don't get scheduled.

When changed to either of:
`--kubelet-extra-args '--node-labels=\"label1=key1,label2=key2,label3=key3\" --register-with-taints=\"node.kubernetes.io/unschedulable:NoSchedule\"'`

`--kubelet-extra-args '--node-labels=\"label1=key1,label2=key2,label3=key3\" --register-with-taints=\"node.kubernetes.io\/unschedulable:NoSchedule\"'`

kubelet gives below error:
`kubelet[xxxx]: --register-with-taints []api.Taint                                                                          Register the node with the given list of taints (comma separated "<key>=<value>:<effect>"). No-op if register-node is false.`
`kubelet[xxxx]: xxxxx xx:xx.xx.xxxxxx xxxx server.go:148] invalid argument "node.kubernetes.io/unschedulable:NoSchedule" for "--register-with-taints" flag: invalid taint spec: node.kubernetes.io/unschedulable:NoSchedule`

**Environment**:
- Kubernetes version (use `kubectl version`):
  Client Version: 1.15.1
  Server Version: 1.12.10
- Cloud provider or hardware configuration: AWS EKS

Story behind this issue is that I'm trying to make one node Unscheduled to be used only by a specific pod. When I make a node Tainted the normal way, none of the DeamonSet are being scheduled to that node. I would like to achieve this without adding taints to my DeamonSets.

**Comment by marquiz** [comment]
Hmm, as described by the error you should use `<key>=<value>:<effect>` format. In this case it should be something like `--register-with-taints "node.kubernetes.io/unschedulable=:NoSchedule"`. Does that work as expected?

**Comment by tretos53** [comment]
I tested this again.

The taint format expected by kubelet is: `<key>=<value>:<effect>`

`--register-with-taints node.kubernetes.io/unschedulable=:NoSchedule` Node is attached to the cluster but no taint is set. `Kubectl get node` shows node as Ready.

`--register-with-taints node.kubernetes.io/unschedulable:NoSchedule` Node is not attached to the cluster and kubelet shows error: invalid argument for "--register-with-taints" flag: invalid taint spec: (comma separated "<key>=<value>:<effect>"). `Kubectl get node` is not showing the node.

The taint format expected by kubelet is: `<key>=<value>:<effect>` so it seems there is no way to taint the node with the built in Taints, for example: node.kubernetes.io/unschedulable:NoSchedule.
The only way to make the node unschedulable is by using `kubectl drain node`.

Below command doesn't work either:
```
kubectl taint node <node> node.kubernetes.io/unschedulable:NoSchedule
error: at least one taint update is required
```

Below command taints the node but as this is a normal taint no DeamonSet pods are allowed
```
kubectl taint node <node> node.kubernetes.io=unschedulable:NoSchedule
node/<node> tainted
```

I understand why below taints shouldn't be set by a user but at lease the first one should:

> node.kubernetes.io/unschedulable
> node.kubernetes.io/not-ready
> node.kubernetes.io/unreachable
> node.kubernetes.io/out-of-disk
> node.kubernetes.io/memory-pressure
> node.kubernetes.io/disk-pressure
> node.kubernetes.io/network-unavailable
> node.cloudprovider.kubernetes.io/uninitialized

**Comment by neolit123** [comment]
i don't think it is a good idea to try apply the built-in taints managed by the DS controller.

> Story behind this issue is that I'm trying to make one node Unscheduled to be used only by a specific pod. When I make a node Tainted the normal way, none of the DeamonSet are being scheduled to that node. I would like to achieve this without adding taints to my DeamonSets.

someone reported the same use case some time ago, but i cannot find the ticket. not sure if maintainers replied there. my reply there was that you have to make your DS YAML aware of custom taint that you apply to nodes.

you can also play with anti-affinity and the `NotIn` operator, see example here:
https://stackoverflow.com/a/59013378
some more details:
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled

this can act like a reverse-nodeSelector, where if a Node has a label a DS Pod will not schedule on it.

> Client Version: 1.15.1
> Server Version: 1.12.10

side note, this is unusupported skew between client and server:
https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl

**Comment by marquiz** [comment]
> The taint format expected by kubelet is: `<key>=<value>:<effect>` so it seems there is no way to taint the node with the built in Taints, for example: node.kubernetes.io/unschedulable:NoSchedule.

It's not about the format. With the built-in taints the value is just empty. E.g. this should work:
```
kubectl taint node node2 node.kubernetes.io/my-unschedulable=:NoSchedule
```

It's just that you have no control over these reserved built-in taints. I don't know exactly how it works but I expect that the master (node controller?) immediately/automatically writes over any value you're trying to set.

**Comment by marquiz** [comment]
> you have to make your DS YAML aware of custom taint that you apply to nodes.

Yup

I'd suggest to close this issue as `--register-with-taints` seems to work as expected. Giving the user full control over the built-in taints is a completely different story, I think (and I don't know it's a good idea)

**Comment by neolit123** [comment]
thanks for the comments and report.
/close
