### ISSUE TITLE
The COS versions at image-config.yaml are really old

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#88284]
_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/88281_

/kind cleanup

**Comment by cheftako** [comment]
Confirmed the relevant images do exist and are still accessible. (gcloud compute images list --project cos-cloud --no-standard-images --show-deprecated)
Its not clear however if this is the relevant file, https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/image-config.yaml is the relevant file or if these files are no longer used at all.

**Comment by bsdnet** [comment]
Are those files still relevant, and I saw test-infra has the same files.
git grep cos |grep stable
CHANGELOG/CHANGELOG-1.10.md:3109:* GCE: bump COS image version to cos-stable-63-10032-71-0 ([#57204](https://github.com/kubernetes/kubernetes/pull/57204), [@yujuhong](https://github.com/yujuhong))
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:51:  cosstable2-resource1:
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:52:    image: cos-stable-59-9460-64-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:58:  cosstable2-resource2:
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:59:    image: cos-stable-59-9460-64-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:65:  cosstable2-resource3:
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:66:    image: cos-stable-59-9460-64-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:72:  cosstable1-resource1:
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:73:    image: cos-stable-60-9592-76-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:79:  cosstable1-resource2:
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:80:    image: cos-stable-60-9592-76-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:86:  cosstable1-resource3:
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:87:    image: cos-stable-60-9592-76-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:115:    image: cos-stable-60-9592-76-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:116:    image_description: cos-stable-60-9592-76-0 with docker 1.12.6
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:123:    image: cos-stable-60-9592-76-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:124:    image_description: cos-stable-60-9592-76-0 with docker 1.12.6
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:131:    image: cos-stable-60-9592-76-0
test/e2e_node/jenkins/benchmark/benchmark-config.yaml:132:    image_description: cos-stable-60-9592-76-0 with docker 1.12.6
test/e2e_node/jenkins/image-config-serial.yaml:15:  cos-stable2:
test/e2e_node/jenkins/image-config-serial.yaml:16:    image_regex: cos-stable-59-9460-64-0 # docker 1.11.2
test/e2e_node/jenkins/image-config-serial.yaml:23:  cos-stable1:
test/e2e_node/jenkins/image-config-serial.yaml:24:    image_regex: cos-stable-60-9592-84-0 # docker 1.13.1
test/e2e_node/jenkins/image-config.yaml:15:  cos-stable2:
test/e2e_node/jenkins/image-config.yaml:16:    image_regex: cos-stable-59-9460-64-0 # docker 1.11.2
test/e2e_node/jenkins/image-config.yaml:19:  cos-stable1:
test/e2e_node/jenkins/image-config.yaml:20:    image_regex: cos-stable-60-9592-84-0 # docker 1.13.1

**Comment by MHBauer** [comment]
The yaml don't seem to be referenced anywhere else, so I made https://github.com/kubernetes/kubernetes/pull/91471

I'm wondering how much of the rest of that directory is also unused and has been already moved to test-infra.

**Comment by bsdnet** [comment]
There are same name files in kubernetes/test-infra, where they are updated.
We need to know what tests to run when remove those files
