### ISSUE TITLE
--shutdown-delay-duration causes kube-apiserver to shut down shortly after startup if set to 20s or more

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#88293]
**What happened**:

After upgrading to 1.16.6, my team started to experiment with the `--shutdown-delay-duration` flag. We found that if it was set to 20s or higher, there was a chance (which increased as duration increased) that our kube-apiserver would shut down shortly after starting, usually within 30 seconds of systemd receiving the startup signal from the apiserver process (i.e. when it enters a `active (running)` state.) And this would happen ad infinitum as systemd would restart the stopped process.

We run kube-apiserver on a cluster of separate Nodes from our main worker Nodes, on the host directly with systemd rather than as a static pod. `systemctl status` reports this status when that happens:

```
Active: deactivating (stop-sigterm) since Tue 2020-02-18 20:57:55 UTC; 966ms ago
```

There are no logs from the server itself about a crash or anything like that. The standard server bootup messages are there, then sometimes some `healthz check failed` logs, sometimes none, and then sometimes some regular logs, then suddenly the journal just shows the systemd shutdown message.

Any server for which this begins to happen will not eventually become healthy. The only solution is to changing the setting to a lower value. However, some servers would not have a problem with a value of 20s or more. I could find nothing that stood out about these servers to differentiate them. We use an immutable infrastructure at my workplace so these servers are all cattle and not unique in the slightest.

Here is a gist from later in the thread where I tested with 30s: https://gist.github.com/2rs2ts/57837d2932341a9133516386af5f69c5

**What you expected to happen**:

We expect that any value should be fine. Looking at the code, too, the change that introduced this flag should only apply on shutdown. And if that wasn't the case we would not expect ~20 seconds to be a magic number where the problems start.

**How to reproduce it (as minimally and precisely as possible)**:

While I'd like to say that anyone with a systemd-based setup could just test this argument and see what they get, I can't rule out that it's not caused by something else in our system. The 20 second threshold might be an emergent property of some things going on in our cluster, like load or number of custom apiservices.

I would encourage someone reproducing this to try a wider range of values. For me, the lowest I went was 10 seconds, and the highest was 30 seconds. At 30 seconds, I could reproduce this behavior almost all of the time. At 20 seconds it happened around 1/3 of the time.

**Anything else we need to know?**:

Our systemd `ExecStartTimeout` is the default, which I believe is 90 seconds. I don't believe this is happening due to a systemd timeout, I believe a timeout would show a different error message.

Our master nodes run kubelet as well, so they are full-fledged Nodes.

For external clients we use an AWS ELB that fronts the kube-apiservers, and its healthcheck is configured to hit `/readyz` on a 10 second interval. (Our ASG uses an EC2 health check, so the ELB health checks failing are not causing instance termination.) We also have a monit server and datadog agent each running on the node, checking `/healthz`. I think monit runs every 30 seconds and datadog runs every 10 or 15 seconds. Not sure if these probes have anything to do with the errors but since the `--shutdown-delay-duration` flag is designed to affect the behavior of probes I thought I'd mention it.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.6
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`):  `Debian GNU/Linux 9 (stretch)`
- Kernel (e.g. `uname -a`): `Linux ip-10-42-18-58 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux`
- Install tools: N/A (manual install)
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
/assign @sttts 
as original author in https://github.com/kubernetes/kubernetes/pull/74416

**Comment by tedyu** [comment]
I wonder why delayedStopCh is passed to NonBlockingRun.

It seems stopCh should be passed instead.
```
diff --git a/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go b/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
index 07bad3d8c01..e26b9f769f7 100644
--- a/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
+++ b/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
@@ -324,7 +324,7 @@ func (s preparedGenericAPIServer) Run(stopCh <-chan struct{}) error {
        }()

        // close socket after delayed stopCh
-       err := s.NonBlockingRun(delayedStopCh)
+       err := s.NonBlockingRun(stopCh)
        if err != nil {
                return err
        }
```

**Comment by sttts** [comment]
> I wonder why delayedStopCh is passed to NonBlockingRun.

`delayedStopCh` is correct because the API server keep working and serving during the delayed shutdown time. That's the main sense of the delayed shutdown time in the first place.

**Comment by sttts** [comment]
The issue description is not enough. We need complete logs of the apiserver up to termination. We also need a complete systemd unit file.

**Comment by tedyu** [comment]
Thanks for clarification, @sttts

**Comment by 2rs2ts** [comment]
@sttts Here's a gist with the journal from a couple iterations of the stop/start loop, as well as the `systemctl show` output for the service, from a node I tested this morning (with the value set to 30s because it reproduces very easily at that value): https://gist.github.com/2rs2ts/57837d2932341a9133516386af5f69c5

I should say, this log pattern here is not always the same for every time I test this, so if you want I can go do this collection for more instances with more values for `--shutdown-delay-duration`, but it takes me a few hours to do it because I have to redact the output and get it cleared with security at my company, so I hope this is good enough.

**Comment by tedyu** [comment]
Looking at #74416 (we don't know whether that was really related to the shutdown), there is not much log around the delayedStopCh.

Maybe we can add more logs so that there is more information in the next round of test run.

**Comment by sttts** [comment]
I see 
```
Feb 19 20:10:38 ip-10-47-18-234 kube-apiserver[24354]: [-]poststarthook/rbac/bootstrap-roles failed: reason withheld
```

for extended amount of time. This is not healthy.

Have you tried on a recent release? This code path was reworked a couple of times.

**Comment by 2rs2ts** [comment]
@sttts we can give this a shot on 1.19, the current version we are using at my company–if you think that would be productive.

**Comment by sttts** [comment]
Was thinking more about 1.22 beta. There lots of things in this area have changed.

**Comment by 2rs2ts** [comment]
@sttts gotcha. Well, I will at least make a point to test this setting every time we upgrade, and hopefully when we get to 1.22, it'll just be solved. Getting a 1.22 beta cluster spun up right now would probably take me a few days at least, so I hope you'll forgive me for not doing it right now.

**Comment by 2rs2ts** [comment]
My team upgraded to 1.20 two weeks ago and we decided to use this new flag. So far we have not seen any of the instability from this issue, so I suppose this is resolved!
