### ISSUE TITLE
have a question,tell the path not exist,but i am sure  the path is exist.

### ISSUE THREAD

**Issue by k332772194** [kubernetes/kubernetes#88305]
Events:
  Type     Reason       Age                            From                    Message
  ----     ------       ----                           ----                    -------
  Normal   Scheduled    2m39s                          default-scheduler       Successfully assigned public-service/es-0 to 192.168.2.134
  Warning  FailedMount  <invalid> (x8 over <invalid>)  kubelet, 192.168.2.134  MountVolume.SetUp failed for volume "elasticsearch-config" : configmap "es-config" not found
  Warning  FailedMount  <invalid>                      kubelet, 192.168.2.134  Unable to mount volumes for pod "es-0_public-service(169c6dbb-bf4e-4cbc-b301-bc89856d59e2)": timeout expired waiting for volumes to attach or mount for pod "public-service"/"es-0". list of unmounted volumes=[es-data elasticsearch-config]. list of unattached volumes=[es-data elasticsearch-config default-token-zs4z4]
  Warning  FailedMount  <invalid> (x9 over <invalid>)  kubelet, 192.168.2.134  MountVolume.NewMounter initialization failed for volume "k8s-pv-es1" : path "/mnt/es/vol1" does not exist

**Comment by neolit123** [comment]
hi, please use the support channels for this:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
