### ISSUE TITLE
document for container linux need to update 

### ISSUE THREAD

**Issue by skycastlelily2** [kubernetes/kubernetes#88322]
**What would you like to be added**:

Hi, I have followed this document to setup a cluster successfully on fedora coreos (container linux)
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

The following steps are also needed 
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

Note:
    Setting SELinux in permissive mode by running setenforce 0 and sed ... effectively disables it. This is required to allow containers to access the host filesystem, which is needed by pod networks for example. You have to do this until SELinux support is improved in the kubelet.

    Some users on RHEL/CentOS 7 have reported issues with traffic being routed incorrectly due to iptables being bypassed. You should ensure net.bridge.bridge-nf-call-iptables is set to 1 in your sysctl config, e.g.

    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sysctl --system

    Make sure that the br_netfilter module is loaded before this step. This can be done by running lsmod | grep br_netfilter. To load it explicitly call modprobe br_netfilter.

**Why is this needed**:
 kubeadm init will fail without the above steps

**Comment by neolit123** [comment]
/remove-kind feature
/kind documentation
/sig cluster-lifecycle node

@skycastlelily2 hi, users are already using SELinux labels and running a kubeadm cluster with SELinux enabled.

this is possible by configuring a security context:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#assign-selinux-labels-to-a-container

> You have to do this until SELinux support is improved in the kubelet.

i wonder what work remains there and if this sentence is still valid.

in any case i'm going to close this ticket because there is ongoing discussion to remove the recommended steps to disable SELinux in the kubeadm installation guide for RedHat distros:
https://github.com/kubernetes/website/issues/14457

please follow that discussion if interested.

thanks
/close

**Comment by skycastlelily2** [comment]
Hi,

Thanks for your information,the following is needed

cat <<EOF > /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

Make sure that the br_netfilter module is loaded before this step.
This can be done by running lsmod | grep br_netfilter. To load it
explicitly call modprobe br_netfilter.

*Why is this needed*:

**Comment by neolit123** [comment]
the `br_netfilter` requirement is documented here. it is required by _some_ CNI plugins:
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements

> The plugin may also need specific support for kube-proxy. The iptables proxy obviously depends on iptables, and the plugin may need to ensure that container traffic is made available to iptables.

this step seems more valid not for the Node/OS installation part, but rather for the CNI installation part:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

if you check under "WeaveNet" there the step is already documented:
> Set /proc/sys/net/bridge/bridge-nf-call-iptables to 1 by running sysctl net.bridge.bridge-nf-call-iptables=1 to pass bridged IPv4 traffic to iptables’ chains. This is a requirement for some CNI plugins to work, for more information please see Network Plugin Requirements.

**Comment by skycastlelily2** [comment]
kubeadm init --config init.yaml will fail with  [ERROR
FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]:
/proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
 without modprobe br_netfilter,you will get:
 [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]:
/proc/sys/net/bridge/bridge-nf-call-iptables does not exist
 Besides, the document for other distros put them there.Maybe we should
also add them  for container linux ?

**Comment by neolit123** [comment]
this is technically a requirement for most Linux distros, to be able to pass bridged iptables traffic.

a potential improvements for the docs can be done here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#ensure-iptables-tooling-does-not-use-the-nftables-backend

a new section bellow "Check network adapters" can be added:
```
## Letting iptables see bridged traffic

As a requirement for your Linux Node's iptables to correctly see bridged traffic, you should ensure net.bridge.bridge-nf-call-iptables is set to 1 in your sysctl config, e.g.

cat <<EOF > /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

Make sure that the br_netfilter module is loaded before this step. This can be done by running lsmod | grep br_netfilter. To load it explicitly call modprobe br_netfilter.

For more details please see the [Network Plugin Requirements](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements) page.
```
and then remove the similar notes from here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

i will create an issue in kubernetes/website
if you want, please feel free to send a PR to fix that.

**Comment by neolit123** [comment]
see https://github.com/kubernetes/website/issues/19222

**Comment by skycastlelily2** [comment]
Hi,Thanks for your  response and help.
