### ISSUE TITLE
k8s 1.14.8 error: unable to retrieve the complete list of server APIs: admissionregistration.k8s.io/v1alpha1: the server could not find the requested resource

### ISSUE THREAD

**Issue by steve19922** [kubernetes/kubernetes#88326]
**What happened**:
error: unable to retrieve the complete list of server APIs: admissionregistration.k8s.io/v1alpha1: the server could not find the requested resource

**What you expected to happen**:
list all api resources
**How to reproduce it (as minimally and precisely as possible)**:
kubectl api-resources --verbs=list

This also happens when trying to install helm release, it fails with:  failed update prepare step: a release named xxxx is in use, cannot re-use a name that is still in use error

In the tiller deploy logs a more detailed error is logged:
Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server API's: admissionregistration.k8s.io/v1alpha1: the server could not find the requested resource
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AKS (Azure kubernetes cluster)
- OS (e.g: `cat /etc/os-release`):
Linux (ubuntu 16.04)
- Kernel (e.g. `uname -a`):
n/a
- Install tools:
terraform
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Do you have alpha APIs enabled in your cluster? Are there multiple API servers in your cluster? Are they at the same version with the same APIs enabled?

**Comment by steve19922** [comment]
Hi, thanks for replying, yes the issue is happening with this particular API, which is ALPHA, as per the api servers, AKS is taking care of that.

**Comment by liggitt** [comment]
what does `kubectl get apiservice/v1alpha1.admissionregistration.k8s.io -o yaml` return?

**Comment by steve19922** [comment]
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2020-02-11T18:22:11Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1alpha1.admissionregistration.k8s.io
  resourceVersion: "91332005"
  selfLink: /apis/apiregistration.k8s.io/v1/apiservices/v1alpha1.admissionregistration.k8s.io
  uid: 6bf0d842-4cfb-11ea-a95d-4e1a1dae46f2
spec:
  group: admissionregistration.k8s.io
  groupPriorityMinimum: 16700
  service: null
  version: v1alpha1
  versionPriority: 9
status:
  conditions:
  - lastTransitionTime: "2020-02-11T18:22:11Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available

**Comment by liggitt** [comment]
That alpha API version no longer exists in 1.14, and is removed by a 1.14 API server on start. It's presence means a 1.13 (or earlier) API server was run in this cluster after the current 1.14 API server started.

You can manually remove it with `kubectl delete apiservices/v1alpha1.admissionregistration.k8s.io` or restart your 1.14 API server to resolve the issue.

/close
