### ISSUE TITLE
Intermittent problem with pipeline

### ISSUE THREAD

**Issue by olefemmy** [kubernetes/kubernetes#88330]
**What happened**: Pipeline occasionally fails. It fails about 1 in 3 builds (there are 3 publishImage in my pipeline)

**What you expected to happen**: Previous version of k8s/rancher always works 1 out of 1

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: Error message is `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Environment**: Rancher 2.3.3
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration: AWS, 5 worker nodes with t3.large
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Docker Version: 19.3.5

**Comment by marquiz** [comment]
Hmm, maybe you should file this report against rancher?

**Comment by olefemmy** [comment]
I have taken it up with Rancher team and they seem to suggest that it might
be an issue with k8s and docker version, which is why I am raising it here.
I have looked at the bug fixes on docker and k8s and none seem to mention
this intermittent problem.

**Comment by olefemmy** [comment]
The issue is due to the fact that the latest rancher release broke the parallel release.
