### ISSUE TITLE
move pkg/controller/volume/scheduling to scheduler

### ISSUE THREAD

**Issue by gongguan** [kubernetes/kubernetes#88357]
**What happened**:
package `pkg/controller/volume/scheduling` are only used by scheduler rather than controller-manager, I think it reasonable to move it to `pkg/scheduling/framework/plugins/volumebinding`.

By the way, we can merge [nodevolumelimits.InTreeToCSITranslator](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L41) into [scheduling.InTreeToCSITranslator](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/scheduling/scheduler_binder.go#L50) after moving.

WDYT @msau42 @ahg-g ?

**Comment by ahg-g** [comment]
It is more about ownership of the code, I think this should stay where it is.

/close

**Comment by gongguan** [comment]
> It is more about ownership of the code

Agree, pkg/volume/scheduling maybe better.

**Comment by gongguan** [comment]
> Agree, pkg/volume/scheduling maybe better.

Seems it makes little sense.
