### ISSUE TITLE
scheduler framework need more values for additional user-defined plugin

### ISSUE THREAD

**Issue by nalan2012** [kubernetes/kubernetes#88365]
**What would you like to be added**:
In the priority part of schedule framework, we want to add pod info besides node scores as the input values for additional user-defined plugin.
**Why is this needed**:
we want to leverage the scores info to acheive other tasks after filtering the pod.

**Comment by alculquicondor** [comment]
Could you specify which interface you are referring to and what is the proposed change?

In general, it's preferred to keep the interfaces as limited as possible to avoid side effects and maintenance burden. So it's helpful if you can describe the use case too.

**Comment by nalan2012** [comment]
Thanks for your comment. 
I wanna to extend functions in the normalize scoring part in the scheduler framework.
Actually,  we want to create new resources based on the scores of the alternative nodes and  
distinguish the pod through the annotation info. Our use case could described as follows:
 func NormalizeScores(pod, scores map[string]int) {
   annotations := pod.GetAnnotations()
   if annotations[flag] == true {
      // functions to do sth. 
   }
}

**Comment by alculquicondor** [comment]
but `NodeScoreList` already has the names of the nodes. Is that not enough?

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/interface.go#L322

**Comment by hprateek43** [comment]
Any use case that you feel will benefit from adding the pods in addtion to the nodes for user defined plugins ? Given that you get the node, you can always find the pods running on that node ?

**Comment by alculquicondor** [comment]
Also, in your example, I believe you are talking about the pod being scheduled. That pod is already passed in. Unless we are misunderstanding your example. Please provide more details.

**Comment by alculquicondor** [comment]
/close
we can reopen if more information is provided.
