### ISSUE TITLE
Manage the order of Pod booting

### ISSUE THREAD

**Issue by hase1128** [kubernetes/kubernetes#88362]
**What would you like to be added**:
I want to add the feature which can manages the order of Pod booting.

e.g. 
I would like to guarantee that Pod2 starts boot after Pod1 becomes "ready" status.

in case of multiple pods are contained in one yaml file and user apply this file by kubectl, these pods are booting in parallel.

we can use pod-priority, but this can't manage order strictly.
https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#

There is Initcontainer feature, but this does not affect among Pods.(this affects to containers inside of Pod).

I think Helm can manage order of boot, but Helm doesn't guarantee the status of Pod.(e.g. Pod2 starts boot before Pod1 has not been "Ready" status yet).

**Why is this needed**:
Pod1: DB
Pod2: Application

If Pod2 starts boot before Pod1 become "Ready", Pod2 fails to connect DB.
Pod2 tries to reconnect, but user should wait long time if this retry interval is long even if Pod1 become "Ready".

We can't use InitContainer if we want to separate another Pod due to several reason(maintenancy/microservice/scaling level/etc).

We can also manage the booting order manually by self script, but it is useful if k8s has such feature.

**Comment by skilxn-go** [comment]
It's a little strange IMO.
As we know, pods belong to workloads.
So your DB and Application pods should belong to some workloads such as deployments or statefulsets.
If there are multi pods in those workloads, say 90/100 pods are ready for the DB, what's the expecting behavior of the Application pods(maybe 50 App pods to be created).

**Comment by hase1128** [comment]
- DB(one primary DB and multiple replica DBs) 
- App(multiple Pods and connect to `primary` DB).

In this case, several App Pods will be created but rest of them wait for their reconnect interval.
In this situation, service is run normally, but it does not have enough resource of App Pods.
I would like to avoid such situation. (If we are unlucky, all Apps wait longer than expected)

**Comment by fengzixu** [comment]
Actually, I agree with @skilxn-go. The DB and application should be deployed separately. But I have some ideas based on your requirement.

If you insist on deploying your application pods in the specific order,  maybe you can write a script or little programme, let it run in the initContainer of application pod, this script/programme will check if the DB works fine. If the state of DB is ok, your application pod can start.

Here is a premise: deploy your DB and application separately.

**Comment by hase1128** [comment]
@fengzixu 
Thanks your ideas (use initContainer). It looks good for me.
So, I close this feature request. If I come up other requirement, I will reopen the issue. thanks.
