### ISSUE TITLE
csi driver is not enabled in kube-apiserver

### ISSUE THREAD

**Issue by liu4480** [kubernetes/kubernetes#88361]
I ran k8s 1.13.7
with options:
apiserver
KUBE_APISERVER_OPTS="--logtostderr=true \
--v=2 \
--etcd-servers=https://X.X.X.X:2379 \
--bind-address=0.0.0.0 \
--secure-port=6443 \
--advertise-address=X.X.X.X \
--allow-privileged=true \
--service-cluster-ip-range=X.X.X.X/24 \
--enable-admission-plugins=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
--enable-bootstrap-token-auth \
--token-auth-file=XXXXXX \
--service-node-port-range=30000-50000 \
--allow-privileged=true \
--feature-gates=BlockVolume=true,CSIBlockVolume=true,CSIPersistentVolume=true,VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true \
--tls-cert-file=XXXXX  \
--tls-private-key-file=XXXX \
--client-ca-file=XXXX \
--service-account-key-file=XXXX \
--etcd-cafile=XXXX \
--etcd-certfile=XXXX \
--etcd-keyfile=XXXX

controller-manager
KUBE_CONTROLLER_MANAGER_OPTS="--logtostderr=true \
--v=4 \
--master=127.0.0.1:8080 \
--leader-elect=true \
--address=127.0.0.1 \
--service-cluster-ip-range=X.X.X.X/24 \
--cluster-name=kubernetes \
--cluster-signing-cert-file=XXXXX \
--cluster-signing-key-file=XXXXX  \
--root-ca-file=XXXXX \
--service-account-private-key-file=XXXXX \
--feature-gates=TaintBasedEvictions=false,TaintNodesByCondition=false,BlockVolume=true,CSIBlockVolume=true \
--node-monitor-grace-period=60s \
--pod-eviction-timeout=70s "

kubelet:
KUBELET_OPTS="--logtostderr=true \
--v=2 \
--hostname-override=X.X.X.X \
--kubeconfig=XXXXXXX \
--bootstrap-kubeconfig=XXXXXX \
--config=XXXXXX \
--cert-dir=XXXXXX \
--pod-infra-container-image=wcloud-registry.58corp.com/rhel7/pod-infrastructure:latest \
--eviction-hard=memory.available<5Gi,imagefs.available<3% \
--cgroup-driver=cgroupfs \
--allow-privileged=true \
--feature-gates=BlockVolume=true,CSIBlockVolume=true,CSIPersistentVolume=true,VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true "

but kubelet encountered the issue:
[ reflector.go:125] k8s.io/csi-api/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.CSIDriver: the server could not find the requested resource (get csidrivers.csi.storage.k8s.io)

it seems that the reousrce csidrivers.csi.storage.k8s.io does not exist, does anyone know the reason, and how can I fix the issue

**Comment by liu4480** [comment]
What I mean is how can I enable csidrivers.csi.storage.k8s.io in k8s 1.13?

**Comment by liggitt** [comment]
The CSIDriver API types were added in 1.14. Prior to that, they were developed as alpha-level custom resources.

/sig storage
/remove-sig usability
/close

**Comment by liu4480** [comment]
thanks， I tried the solution, it works as expected
