### ISSUE TITLE
Errors encountered when decoding json/yaml files should be descriptive

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes#8838]
For example, I tried `kubectl create -f password.yaml` and got `Error: unable to load "./password.yaml": illegal base64 data at input byte 8` I didn't know that it was the secret `data.password:` field that was triggering the illegal base64 error.

When doing decoding like this, it would be good to print at least the label name from the file where the error happened.

**Comment by smarterclayton** [comment]
We improved this a while back I think.  Re-open if still an issue.
