### ISSUE TITLE
kubelet fails to delete static pods after updating its configuration to apiserver and restart.

### ISSUE THREAD

**Issue by yttan** [kubernetes/kubernetes#88402]
**What happened**:

Firstly, the secure port of apiserver is changed from 6443 to 6444. Some modifications are done on master nodes, everything looks fine.

Then on normal nodes, change the the `server` field in kubelet configuration from ` https://localhost:6443` to ` https://localhost:6444`. And restart kubelet 
```
systemctl restart kubelet
```
It's localhost because the traffic is redirected by an nginx-proxy static pod managed by kubelet.
So requests go from local port 6444 to the static pod, then from the nginx pod to the remote server.

Of course since the nginx configuration is not updated yet, kubelet can not connect to remote apiservers successfully by now. So I changed the nginx configuration file, and removed the static pod yaml out of /etc/kubernetes/manifests in order to restart the nginx pod.

Then I found the nginx is not deleted by kubelet. It should be deleted by kubelet since kubelet is running.

```
tcp        0      0 127.0.0.1:6443          0.0.0.0:*               LISTEN      20653/nginx: master
```

Then I tried to move the static pod yaml to /etc/kubernetes/manifests again. The nginx configuration is updated and should serve on 6444. But no, it still serves on 6443.

I have to kill the previous nginx process manually to have kubelet running a new nginx pod which serves on 6444.

```
kill 20653
```

```
tcp        0      0 127.0.0.1:6444          0.0.0.0:*               LISTEN      18842/nginx: master
```

**What you expected to happen**:

After removing the nginx yaml out of /etc/kubernetes/manifests, the nginx pod should disappear.

I know kubelet can not connect to the remote apiserver in this process.
But managing the nginx static pod has nothing to do with apiserver. It's local.

**How to reproduce it (as minimally and precisely as possible)**:

1. change server port in node kubelet config.
2. restart kubelet (at this point kubelet can not connect to apiserver)
3. remove static pod yaml out of static pod file path

**Anything else we need to know?**:

I traced kubelet code. The problem might because of

```go
func (kl *Kubelet) deletePod(pod *v1.Pod) error {
	if pod == nil {
		return fmt.Errorf("deletePod does not allow nil pod")
	}
	if !kl.sourcesReady.AllReady() {
		// If the sources aren't ready, skip deletion, as we may accidentally delete pods
		// for sources that haven't reported yet.
		return fmt.Errorf("skipping delete because sources aren't ready yet")
	}
```

It checks all the sources to be ready before deleting a pod. 

So kubelet can not manage local static pods when it is restarted and can not connect to apiserver

My point here is kubelet does not need to know apiserver is ready or not to manage local static pods.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"archive", BuildDate:"2019-06-12T09:20:58Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
@yttan 
Do you see the following in kubelet log ?

"skipping delete because sources aren't ready yet"

Thanks

**Comment by yttan** [comment]
@tedyu 
Yes, sorry that I forgot to paste the log 

```
I0218 12:20:53.311162   10750 kubelet.go:1895] SyncLoop (REMOVE, "file"): "nginx-proxy-mockvm-deploy8_kube-system(794f814d9c3e79f67ce0eb35470e4048)"
I0218 12:20:53.311188   10750 kubelet.go:2098] Failed to delete pod "nginx-proxy-mockvm-deploy8_kube-system(794f814d9c3e79f67ce0eb35470e4048)", err: skipping delete because sources aren't ready yet
```

**Comment by yttan** [comment]
/ assign

**Comment by derekwaynecarr** [comment]
I agree kubelet should not need access to api-server to manage static pods.
