### ISSUE TITLE
Image pull policy default is inconsistant

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes#8841]
See: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/defaults.go#L57

The default pull policy is only 'always' if your container image ends with ':latest'. If you leave latest off, which implies latest, the pull policy is 'if not present'. Some people might expect the default to be 'always' even if they use a versioned tag, or any tag like ':mylatest'.

Also see: https://cloud.google.com/container-engine/docs/pods/operations#manifest

**Comment by tmandry** [comment]
+1, I expected this and was very confused why my images weren't updating while using tags like `:prod` and `:staging`. I thought it was a bug somewhere.

**Comment by resouer** [comment]
@tmandry So the expected way is when tag is `:latest` or `null` then policy is always?

**Comment by tmandry** [comment]
@resouer I guess I expected it to be always for any tag.

As a new user, I didn't know there was such a thing as an image pull policy. I was using versioned tags along with `rolling-update` and it wasn't working, and I didn't know why. None of the docs I was using seemed to mention it, so maybe that's the problem.

**Comment by resouer** [comment]
@tmandry you can set `imagePullPolicy: Always` in your container spec. Not related to this issue, I think.
