### ISSUE TITLE
Add impersonation flags to ExecCredential status field

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#88422]
**What would you like to be added**:
Add impersonation flags to ExecCredential status field.

**Why is this needed**:
This would be great to be able to allow the plugin to pass other parameters such as impersonate user, group or extra fields to the Kubernetes API server, which currently requires changing the KUBECONFIG file directly.

**Comment by enj** [comment]
What is the use case exactly?  It would make more sense for the plugin to return a token/cert for the actual user you want to be.  Since the plugin has no input information, how would it know what user to impersonate?

/priority awaiting-more-evidence
/triage needs-information

**Comment by adammw** [comment]
We're currently implementing OIDC authentication for users via a 'helper script' which authenticates via a browser in exchange for providing a token to kubectl.

The use case here is to provide a mechanism by which users can 'request' extra permissions out-of-band, and have the plugin implement it by impersonating other groups. For example, by default the user themselves may not have write access, but by impersonating an admin with a particular group, other RBAC rules can apply to allow that access. 

Additionally, because the impersonation allows for 'extra' user fields that can be logged in the audit log, they can record information such as references to _why_ they needed those extra permissions (e.g. a reference to a ticket).

**Comment by enj** [comment]
> The use case here is to provide a mechanism by which users can 'request' extra permissions out-of-band, and have the plugin implement it by impersonating other groups. For example, by default the user themselves may not have write access, but by impersonating an admin with a particular group, other RBAC rules can apply to allow that access.

If the plugin is automatically impersonating the group (via the script), then why not just give the user that group membership directly?  You can remove group membership just as easily as you can remove the impersonation access.
 
> Additionally, because the impersonation allows for 'extra' user fields that can be logged in the audit log, they can record information such as references to _why_ they needed those extra permissions (e.g. a reference to a ticket).

Having the client be responsible for inserting data into the audit stream is not an approach I would encourage.

---

From the details I understand, I would implement this flow with a custom token webhook and flags to your exec plugin (the flags to the exec plugin are only required if you want the user to opt-into some permissions).  Your tokens can then include the group membership and extra fields as you desire (without user involvement).  This does assume your token issuer is smart enough to perform any authorization checks needed to mint the correct token based on the user (you could reuse Kube RBAC for this by creating some custom permissions).
