### ISSUE TITLE
kubernetes version of release

### ISSUE THREAD

**Issue by mc468** [kubernetes/kubernetes#88430]
Hey guys,
I hvae a simple question, just wannna know which one is stable version(the branch release-1.17 or the tags v1.17.3 in github), in other words, if I wanna build kubernetes using source code, which branch is better
Appreciate it!

**Comment by hprateek43** [comment]
Use a release tag if you want to build a specific release. Use `make build`  to get a local build. If you are developing kubernetes or want to see the latest changes in your build, go with the master branch.

**Comment by liggitt** [comment]
Release tags are cut from the release-1.x branch periodically (roughly monthly). Use the tags if you want a particular release

**Comment by mc468** [comment]
> Use a release tag if you want to build a specific release. Use `make build` to get a local build. If you are developing kubernetes or want to see the latest changes in your build, go with the master branch.

Thank you for your response, so is that means the release-1.x branch is the latest version of the kubernetes 1.x?

**Comment by liggitt** [comment]
1.17.3 is the latest stable release. 1.18 is in development currently
