### ISSUE TITLE
Scheduler framework: Perfilter did not return a FitError

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#88445]
**What happened**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L186 

When return an error not FitError, so we will not go to preemption when preFilter return not success. Is this intentional?

**What you expected to happen**:

IMO, we may still need preempt when failed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ahg-g** [comment]
This is by design, preFilter is not a "Filter", the only expected valid status ```Success```

**Comment by Huang-Wei** [comment]
I'd say we adopted this requirement in #92797 :)
