### ISSUE TITLE
Propagate imagePullSecrets from ServiceAccount to Pod

### ISSUE THREAD

**Issue by kaoet** [kubernetes/kubernetes#88456]
**What would you like to be added**:
When an imagePullSecret is added to a ServiceAccount, this secret is automatically added to all the Pods using this SA.

In the [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account), it says

> Now, any **NEW** pods created in the current namespace will have this added to their spec:

We want that to be all Pods, not only new ones.

**Why is this needed**:

We're implementing an auto secret injector to watch for new SAs, and automatically set `imagePullSecrets` field in it. With this injector, users don't have to maunally specify imagePullSecrets in their YAMLs.

However, there is a race condition. Imagine a user create the SA and a Deployment at the same time (e.g. using `kubectl apply -f` with a YAML containing both). Our injector finds the new SA, but it's too late, since the Pod is already created. So the Pod will never get the injected secret, and users have to restart the Pod to have `imagePullSecrets` field filled.

By having new `imagePullSecret` auto-propagate to old Pods, Kubernetes maintains its declarative way of managing resources.

**Comment by boddumanohar** [comment]
Is there a way to update/replace service account token of a running pod?

**Comment by karthikeayan** [comment]
@kaoet Its been a long time, how did you handle this scenario?

**Comment by kaoet** [comment]
I no longer work on Kubernetes projects.
