### ISSUE TITLE
usb passthrough to VMs spun up using kubevirt

### ISSUE THREAD

**Issue by skolnickm** [kubernetes/kubernetes#88468]
**What would you like to be added**:
The ability to pass usb devices to a VM started by Kubevirt. That way the VM can be interfaced by USB devices hooked up directly to the node that is running the VM.

**Why is this needed**:
When a GPU is passed through to a VM and the VM now has direct access to a physical monitor there is no way to interface with it besides using a VNC session of some sort.

**Comment by dims** [comment]
is there a kubevirt feature request? https://github.com/kubevirt/kubevirt/issues/ please start there and let the kubevirt folks open any KEP (enchancement proposals here in kubernetes)

/close
