### ISSUE TITLE
client-go fake seems to be dropping writes

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#88508]
**What happened**:

I am seeing some weird issues where writes are seemingly being dropped with the fake client. I am not sure if I am doing something wrong here or if this is unexpected. Basically doing `write(x); read(x)` and the read fails. 

**What you expected to happen**:

I can read some item after I have written it

**How to reproduce it (as minimally and precisely as possible)**:

```go

func TestHowardjohn(t *testing.T) {
	node := &coreV1.Node{
		ObjectMeta: metaV1.ObjectMeta{
			Name: "node",
		},
	}
	client := fake.NewSimpleClientset()

	sharedInformers := informers.NewSharedInformerFactoryWithOptions(client, 0, informers.WithNamespace(""))
	nodes := sharedInformers.Core().V1().Nodes().Informer()
	stop := make(chan struct{})
	go nodes.Run(stop)
	cache.WaitForCacheSync(stop, nodes.HasSynced)
	if _, err := client.CoreV1().Nodes().Create(node); err != nil {
		t.Fatalf("Cannot create node %s (error: %v)", node.Name, err)
	}
	err := retry.UntilSuccess(func() error {
		_, exists, err := nodes.GetStore().GetByKey("node")
		if !exists || err != nil {
			return fmt.Errorf("not found")
		}
		return nil
	}, retry.Timeout(time.Second*10))
	if err != nil {
		if _, err := client.CoreV1().Nodes().Create(node); err != nil {
			t.Fatalf("Cannot create node %s (error: %v)", node.Name, err)
		}
	}
}
```

I run this test with https://godoc.org/golang.org/x/tools/cmd/stress and I see that 1/5000 runs fail with error
```
--- FAIL: TestHowardjohn (10.00s)
    controller_test.go:337: Cannot create node node (error: nodes "node" already exists)
FAIL
```

So it seems the read shows that the node is not there, but then if I try to create it, suddenly it already exists.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `k8s.io/client-go v0.17.2`

**Comment by howardjohn** [comment]
Seems like if I replace the create with 

```
		if _, err := client.CoreV1().Nodes().Get(node.Name, metaV1.GetOptions{}); err != nil {
			t.Fatalf("Cannot get node %s (error: %v)", node.Name, err)
		}
```

this runs fine, so its more about the informer missing an update than the write not persisting?

**Comment by fedebongio** [comment]
/cc @deads2k 
(we discussed this one during our Bug Triage)

**Comment by deads2k** [comment]
To my knowledge, the usage of fake clients to drive informers has never worked and has been a consistent limitation of the fake client. We don't consider it a bug, because the mock is a limited view into the interface.  If you find the problem and fixed it, I'd be happy to review an addition to the mock that supports this if it is reasonably sized, but I don't see this being prioritized by the usual suspects.

**Comment by howardjohn** [comment]
I am a bit confused that you say it "doesn't work", as the test pass 99.99% of the time, which gives an impression it's supposed to work. Is there an alternative for testing code with informers?

**Comment by howardjohn** [comment]
I am a bit surprised as well that there is an official example showing almost identical to my example: https://github.com/kubernetes/client-go/blob/master/examples/fake-client/main_test.go#L42

**Comment by howardjohn** [comment]
Can this be reopened? I am working on a fix for this

**Comment by howardjohn** [comment]
I think there is a race in the real `ListAndWatch` between HasSynced returning true and the watch being initiated. I think the fact its a fake client is just because its faster, it might impact real clients as well

**Comment by howardjohn** [comment]
I think the real client avoids this because it uses the resourceVersion in the Watch call, so it gets the Create that happens between the initial List and Watch, while the fake client doesn't

**Comment by howardjohn** [comment]
Specifically, There is a race between

https://github.com/kubernetes/client-go/blob/866e6a7e3cf35d16a6d3d5175e36d05dfe4b0797/tools/cache/reflector.go#L302 and https://github.com/kubernetes/client-go/blob/866e6a7e3cf35d16a6d3d5175e36d05dfe4b0797/tools/cache/reflector.go#L414.

Any creates/updates between those two are dropped.

**Comment by howardjohn** [comment]
The official example, https://github.com/kubernetes/kubernetes/blob/25651408aeadf38c3df7ea8c760e7519fd37d625/staging/src/k8s.io/client-go/examples/fake-client/main_test.go#L33, also has this flake issue
