### ISSUE TITLE
[FR] Rate limited logging util

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/kubernetes#88546]
It would be very useful to have a library or util function that can cap the number of times per second a log message is printed. Something like [this](https://github.com/kubernetes/kubernetes/blob/b5e95fc73dafc92b8e94f5f5a53e5fea7b15ee6f/staging/src/k8s.io/client-go/rest/request.go#L565-L590) but more general.

/sig instrumentation
/priority backlog
/assign @logicalhan

**Comment by serathius** [comment]
Hey, 

Is rate limited logs something commonly used in k8s code? or more pattern that we want to adapt?
Can you specify examples of use cases for it?

**Comment by serathius** [comment]
@mm4tt from Scalability team was also interested in it

**Comment by mm4tt** [comment]
Yeah, having something like this would be great. What I originally had in mind was to have a [flogger](https://github.com/google/flogger) like api, e.g.
```
klog.V(level).AtMostEvery(5, time.Second).Infof(...)
```
But I'm open to other propositions as long as we can achieve the rate-limited logging.

I believe it would be very beneficial both for our internal tooling (e.g. clusterloader2) and for k8s base components. Rate-limiting logging gives you ability to log more without worrying about polluting / spamming the logs. E.g. you can have a situation like this:

```
func onPodUpdate(pod *Pod) {
  err := doSomethingNonCritical(pod)
  if err != nil {
    //  We cannot use non rate-limited logging, as in high churn clusters, in certain scenarios, it would totally spam the log
    klog.Infof("Something non critical, but worth to know when debugging, happened)
    // But we could totally do
    klog.atMostEvery(10, time.Second).Infof(...)
   // it wouldn't spam the log and we'd have the important info for debugging
  }
}

```

Other use-case is to log progress of some operations. E.g. in clusterloader2 we create thousands deployments and we'd like to monitor progress. Currently it results either in spamming the log or in making us to implement some hacks to enable logging conditionally, e.g. https://github.com/kubernetes/perf-tests/blob/ca851b1e218bcd873bac4022beba1aac1cc9042d/clusterloader2/pkg/measurement/util/wait_for_pods.go#L91

Such feature should be part of the logging api, users shouldn't have to do it on their own.

**Comment by serathius** [comment]
It would be definitely a great utility function that would work as a wrapper for logging library. 

I don't think we should add as klog function, but as a function in k8s.io/component-base/logging. Long term as klog is replaced with [logr](https://github.com/go-logr/logr) we could add a wrapper for logr inteface. 
  
@thockin @DirectXMan12  WDYT?
I image that logr, will want to stay as simple interface. Feature requests like this one should be implemented as k8s utils functions for logging.

**Comment by serathius** [comment]
Stumbled on this 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/logreduction/logreduction.go#L26

**Comment by DirectXMan12** [comment]
it's pretty trivial, IIRC, to do stuff like this with Zap -- Zap supports sampling of frequent messages ootb, FYI.  It's one of the nicer logr backends, IMO.

**Comment by serathius** [comment]
Ok, but logr doesn't have methods to control it, meaning this can be set globally during setup. 
Are we ok with enabling this mechanism globally? e.g. would it impact HTTP access logs if they are 2 identical repeated requests?

**Comment by DirectXMan12** [comment]
hmm... zap's built-in sampler samples of message & level, so yeah, that could happen.  A more complex sampler could do other things.  It think it makes sense to live in the utility library, but my gut also says that it doesn't really make particular sense for individual packages to configure sampling -- I'd imaging folks would want it to be up to the user, like `--v` or `--vmodule`.

If I were an end user, there's certainly situations where I'd want to say "no, really, show me all logs" and also situations where I want to say "it turns out this log line is unexpectedly spammy, turn on sampling for that logger name/module/whatever".
