### ISSUE TITLE
ReplicaSet controller incorrectly claim a plain Pod as its orphans

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#88550]
**What happened**:

In one recent e2e [flake](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1231581843564793859), it turns out a plain Pod was updated to set its `ownerReference` to a ReplicaSet, whose labelSelector happens to match the Pod's labels. Afterwards, plain Pod gets garbage collected b/c it's actually not owned by the ReplicaSet.

Here is the slack discussion [link](https://kubernetes.slack.com/archives/C0EG7JC6T/p1582668036017400). And below are the apiserver audit logs proving that it's the replicaset controller that updates the Pod:

- event1: https://gist.github.com/Huang-Wei/0366797df2cad34f7cd8f7e1d7104180
- event2: https://gist.github.com/Huang-Wei/9b600882cba26587781a4fc99009e793

**What you expected to happen**:

A plain Pod shouldn't be claimed as an orphan of the matching ReplicaSet.

**How to reproduce it (as minimally and precisely as possible)**:

- In an e2e test, create a ReplicaSet with labelSelector "foo:bar".
- Create a plain Pod with labels "foo:bar".
- Observe if the Pod gets deleted or not.

**Anything else we need to know?**:

This issue was only reproduced in an e2e test env (i.e., reproduced programmatically). I failed to reproduce it using `kubectl`.

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: e2e-test
- Network plugin and version (if this is a network-related bug):
- Others:

/sig apps
cc/ @janetkuo @soltysh @liggitt @ahg-g 
/priority critical-urgent

**Comment by liggitt** [comment]
> a plain Pod was updated to set its ownerReference to a ReplicaSet, whose labelSelector happens to match the Pod's labels
> ...
> A plain Pod shouldn't be claimed as an orphan of the matching ReplicaSet.

isn't this exactly [controller adoption](https://kubernetes.io/docs/concepts/workloads/controllers/#pod-template)? e2e tests creating pods whose labels place them within a controller selector seems like a test bug

**Comment by Huang-Wei** [comment]
> e2e tests creating pods whose labels place them within a controller selector seems like a test bug

It seems to be the case. I rechecked the manifest I created using kubeclt, it doesn't have `metadata.labels`. Let me close this issue.
