### ISSUE TITLE
Add e2e tests for Windows Device Manager

### ISSUE THREAD

**Issue by ddebroy** [kubernetes/kubernetes#88554]
**What happened**:
This to track there is a followup PR to https://github.com/kubernetes/kubernetes/pull/80917 to introduce e2e tests for Windows.

**What you expected to happen**:
e2e tests get written (fine if it exercises a fake plugin).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`): NA
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by thomacos** [comment]
@aarnaud @ddebroy Idea:
Instead of writing a new dummy plugin, would it be an option to use the existing DirectX device plugin https://github.com/aarnaud/k8s-directx-device-plugin as test?

**Comment by thomacos** [comment]
Does someone know a good sample to be used as blueprint for such an automated e2e test?
As raised by @aarnaud in https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-587931089.

**Comment by thomacos** [comment]
@michmike Do you know good e2e sample code to be used as blueprint for writing a test for https://github.com/kubernetes/kubernetes/pull/93285 as part of https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging?

As suggested in https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-587590447 asked for in https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-587931089.

Alternatively, who would be the right person to ask this?

**Comment by thomacos** [comment]
@aarnaud Does the following make sense?

A test like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/service.go, but with the following differences:

1. No nodeport needed. 
2. But create and get a device plugin pod similar to the function `getSampleDevicePluginPod` in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/device_plugin_test.go#L82-L99.

The device plugin may be https://github.com/aarnaud/k8s-directx-device-plugin (or a hollow version of that).

**Comment by michmike** [comment]
> @michmike Do you know good e2e sample code to be used as blueprint for writing a test for #93285 as part of https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging?
> 
> As suggested in [#80917 (comment)](https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-587590447) asked for in [#80917 (comment)](https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-587931089).
> 
> Alternatively, who would be the right person to ask this?

please connect with @claudiubelu and @adelina-t for some blueprints on tests for windows

**Comment by ddebroy** [comment]
@thomacos @aarnaud you can take a look at the e2e tests in  https://github.com/kubernetes/kubernetes/tree/master/test/e2e/windows for reference/examples/blueprint to follow.

**Comment by thomacos** [comment]
@michmike @ddebroy Thanks!
@claudiubelu @adelina-t  if you could help this would be great!

**Comment by thomacos** [comment]
@claudiubelu @adelina-t 
From your perspective, does the following make sense to you?
1. Prepare a device plugin test pod image containing https://github.com/aarnaud/k8s-directx-device-plugin.
2. Create a yaml file similar to https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests/sample-device-plugin.yaml.
2. Use the test https://github.com/kubernetes/kubernetes/tree/master/test/e2e/windows/service.go as starting point.
2. Remove the nodeport-related code.
3. Add code to launch the device plugin test pod, using code similar to the code in function getSampleDevicePluginPod in https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node/device_plugin_test.go#L82-L99.

**Comment by adelina-t** [comment]
@thomacos It makes sense, with maybe the exception of 2. Create yaml file. I think we can create the pod spec directly in test code, something like this: https://github.com/kubernetes/kubernetes/blob/a097243cbae780f5e2dadc4630f4204fc6500f97/test/e2e/apps/daemon_set.go#L183-L184

I find it's much cleaner to have everything we need contained in the test code.

**Comment by thomacos** [comment]
Thanks, @adelina-t!

We created a fork for the Windows device plugin e2e tests at https://github.com/Kerstin08/kubernetes_device_plugin_e2e_test.

May I ask you the following?

We don't understand https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/device_plugin_test.go#L89-L96.
It seems to create a daemon set, but returns a specific pod. Does this code automatically return the (first?) pod created implicitly by the daemon set?
And how would this code look like when not using a yaml file, but when creating it directly as you recommended?

Other question:
What is the procedure for creating a pod image for testing?

**Comment by adelina-t** [comment]
Hm, I don't think it creates a daemon set at all. It just uses reads the daemonSet spec from the file and uses that to fill in the create the pod spec it returns. In turn, you can see it creates that pod here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/device_plugin_test.go#L133 . It specifically creates a pod, no mention of a daemonSet creation. But this is just at first glance.

For the test image, all test images code is here: https://github.com/kubernetes/kubernetes/tree/897dc66b0e017426d8f2182c4ddcb61dd7ddd93f/test/images

You can add a Dockerfile for a new image here, or you can use one of the existing images if that would work. For example, the agnhost image ( here: https://github.com/kubernetes/kubernetes/tree/897dc66b0e017426d8f2182c4ddcb61dd7ddd93f/test/images/agnhost ), which is supported by both linux & windows is where we add all sorts of functionality that we need in testing. It's basically the swiss army knife for e2e, it does everything from generating logs to being a simple webserver. You can easily add something else here. 

As for the building process, it's done by hand for the moment for Windows. In general building is done by an image promoter job, @claudiubelu  is adding support for Windows in said image promoter.

**Comment by thomacos** [comment]
Since, from our understanding, a daemonSet is the normal way of creating device plugins, why is this test not using a daemonSet?
What approach should be use for our e2e test?
Our assumption was to create a daemonSet (as we are doing for our real use-cases).
Or would you suggest to use the approach of directly creating a device plugin pod without using a daemonSet as done in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/device_plugin_test.go?

**Comment by adelina-t** [comment]
I don't really understand why they designed the test the way they did. I suspect it's because it's just simpler to use a pod. However, a test should be an automation of a real world, so if usage in real use-cases says DaemonSet, you can do that.

**Comment by thomacos** [comment]
Do you by chance have sample code around for creating a DaemonSet?

**Comment by thomacos** [comment]
Yes, indeed, we should have found that by ourselves. 
Thanks!

**Comment by thomacos** [comment]
Thanks a lot for the help!

May I ask another question?
When having created a busybox test pod as in 
https://github.com/kubernetes/kubernetes/blob/a5b89b8e3c533923cdcb7d85abe53dc601ebed7e/test/e2e/windows/device_plugin.go#L64-L65
is it easily possible to run a command inside the pod which writes a file and then verify the content of that file?

In our case we want to run
```
dxdiag /t dxdiag_output.txt

```
inside the pod and verify that the generated file `dxdiag_output.txt` contains the line
```
          DirectX Version: DirectX 12
```

**Comment by adelina-t** [comment]
You can do something like this: https://github.com/kubernetes/kubernetes/blob/edbbb6a89f9583f18051218b1adef1def1b777ae/test/e2e/node/kubelet.go#L110

**Comment by thomacos** [comment]
@adelina-t 

My colleague @Kerstin08 created a first implementation of the e2e test:
https://github.com/Kerstin08/kubernetes_device_plugin_e2e_test
It is not tested yet, because we don't know how to setup the e2e testing environment.
Any feedback so far?

It is possible to run that new test directly in the Kubernetes GitHub test infrastructure by this test robot via "/test something"?
If yes, what is necessary for doing this?

**Comment by jsturtevant** [comment]
There is some documentation on running with kubetest in relation to windows: https://github.com/kubernetes-sigs/windows-testing#running-an-e2e-test-pass.  If you have questions and possible improvements for that document for new folks that would be helpful.

We can add a test for this in this area: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/windows

**Comment by thomacos** [comment]
> There is some documentation on running with kubetest in relation to windows: https://github.com/kubernetes-sigs/windows-testing#running-an-e2e-test-pass. If you have questions and possible improvements for that document for new folks that would be helpful.

Thanks!

> We can add a test for this in this area: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/windows

Yes, this is where we already put it, see https://github.com/Kerstin08/kubernetes_device_plugin_e2e_test.

**Comment by thomacos** [comment]
/close
Merged https://github.com/kubernetes/kubernetes/pull/93285/commits/dc86fb93901f089bb1a72cba8691f7ce93c035eb as part of https://github.com/kubernetes/kubernetes/pull/93285.
