### ISSUE TITLE
kubectl silently fails parsing annotations when passing numeric value

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes/kubernetes#88564]
**What happened**:
Kubectl/Kubernetes API server silently fails parsing numeric annotation values. If one field value is invalid, all annotations are skipped.

For example, given the following my-pod.yaml, `invalid: 123` is an invalid field (or causes the problem, at least)
```
$ cat my-pod.yaml 
kind: Pod
apiVersion: v1
metadata:
  name: my-pod
  annotations:
    valid: foo
    invalid: 123
spec:
  containers:
    - name: my-pod
      image: busybox
      command: [ "sleep", "1000000" ]
```

When this yaml is applied, the pod starts, but with missing annotations:
```
$ kubectl describe pod my-pod
Name:         my-pod
Namespace:    default
Priority:     0
Node:         grant-k8s-node1/192.168.30.91
Start Time:   Tue, 25 Feb 2020 22:07:26 -0800
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"my-pod","namespace":"default"},"spec":{"containers":[{"command":["sle...
Status:       Running
```

To compare, I changed the "invalid" field value to "bar", and both annotations now show up:
```
$ kubectl describe pod my-pod-2
Name:         my-pod-2
Namespace:    default
Priority:     0
Node:         grant-k8s-node2/192.168.30.92
Start Time:   Tue, 25 Feb 2020 22:06:34 -0800
Labels:       <none>
Annotations:  invalid: bar
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"invalid":"bar","valid":"foo"},"name":"my-pod-2","namespace":"default"},"spec":...
              valid: foo
Status:       Running
```

**What you expected to happen**:
I would expect either the invalid field to be ignored, or kubectl to fail client-side in this case.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ (cat <<EOF
kind: Pod
apiVersion: v1
metadata:
  name: my-pod
  annotations:
    valid: foo
    invalid: 123
spec:
  containers:
    - name: my-pod
      image: busybox
      command: [ "sleep", "1000000" ]
EOF
) | kubectl apply -f -
```

**Anything else we need to know?**:
This is not specific to pods - I first discovered this when creating a PVC, but used this pod as a simple example.

Happy to document this if it is expected behavior, but I did not see it on the follow doc page:
https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
3 nodes/1 master vagrant setup
- OS (e.g: `cat /etc/os-release`):
CentOS Linux 7
- Kernel (e.g. `uname -a`):
Linux PDC4-SM26-N8 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Vagrant
- Network plugin and version (if this is a network-related bug):
n/a
- Others:
n/a

**Comment by liggitt** [comment]
This is resolved in 1.17 in https://github.com/kubernetes/kubernetes/pull/83552
