### ISSUE TITLE
If detaching failed while deleting statefulset, we re-create the statefulset and the pods are schedulerd on the same node, pod will be "ContainerCreating" because of attach failed

### ISSUE THREAD

**Issue by ivan-cai** [kubernetes/kubernetes#88565]
**What happened**:
I have the same problem as issue [#72181](https://github.com/kubernetes/kubernetes/issues/72181).
When I use 1 node cluster. I create a statefulset with some pvcs，then delete the sts, and fail to detach volume because of some reasons，then we re-create the sts in ExponentialBackoff duration, the pods will be "ContainerCreating".

Then, I try the pr [#72914](https://github.com/kubernetes/kubernetes/pull/72914) , I found 15 times requesets of patching node per second per volume. this is also a serious problem.

**What you expected to happen**:
when i re-create sts in 1 node cluster, the pods can be "Running".

**How to reproduce it (as minimally and precisely as possible)**:
1、delete sts，the first time entering (ad controller)reconcile(), execute the `volumeDetacher.Detach` in `GenerateDetachVolumeFunc` and return error. the volume will be add back to asw.nodesToUpdateStatusFor (remove by `RemoveVolumeFromReportAsAttached` before detaching), then will be patch to node by `nodeStatusUpdater.UpdateNodeStatuses()`. if failed to detach, the volume will not be remove from `asw.attachedVolumes`.
2、the period of reconciliationLoopFunc is 100ms，and the second time entering reconcile()，when executing `oe.pendingOperations.Run()`，the operation has exist，and then excuting `previousOp.expBackoff.SafeToRetry`, because of the initialDurationBeforeRetry is 500ms，`SafeToRetry` will return `exponentialBackoffError`，and will not add the volume back to asw.nodesToUpdateStatusFor . Then patching to node by `nodeStatusUpdater.UpdateNodeStatuses()`, the volume will miss in node.status.VolumesAttached
3、in this backoff duration, we re-create the sts，and the pod is scheduled to the same node. the `podInformer` in attach/detach controller will add the pod to `dsw.nodesManaged`
4、next time entering reconcile()，`desiredStateOfWorld.VolumeExists` will find the detaching volume is existed in dws，will skip the detach logic. 
5.  because of not adding the volume back to node.status.VolumesAttached，volume manager will think the volume is not attached, and kubelet `WaitForAttachAndMount` timeout

**Anything else we need to know?**:
describe pod:
![image](https://user-images.githubusercontent.com/49785578/75320309-64147100-58a9-11ea-8dc6-18a258919435.png)

kubelet logs:
![image](https://user-images.githubusercontent.com/49785578/75320473-b81f5580-58a9-11ea-8abb-c0f2378b24e0.png)

node yaml:
volumesAttached:
  - devicePath: /dev/disk/by-id/virtio-disk-6w87j3wv
    name: kubernetes.io/qcloud-cbs/disk-6w87j3wv
  volumesInUse:
  - kubernetes.io/qcloud-cbs/disk-6w87j3wv
  - kubernetes.io/qcloud-cbs/disk-7bfqsft5

**Environment**:
Kubernetes version (use kubectl version):
1.10.5/1.12.4/1.14.3
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Linux VM-0-10-ubuntu 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Install tools:
Others:

**Comment by xiaoxiadazhi** [comment]
@kubernetes/sig-storage-bugs

**Comment by Anjingkegui** [comment]
I have met the same issue in our environment. (v1.15.7)

What we got (timeline-based):
1. we have pod A attached volume A on a node.
2. when the job in pod A is completed, pod A entered Succeed/Completed status, which would trigger the detach happen.
3. but something wrong happened in the backend to make the detach process failed.
4. pod B was created and scheduled to the same node, and also use volume A as its volume.
5. pod B would trigger attach process.

The problem here is the failed detach for pod A would never have tr-try and the attach process of pod A would proceed and get unexpected result from the node.

**Comment by ivan-cai** [comment]
> I have met the same issue in our environment. (v1.15.7)
> 
> What we got (timeline-based):
> 
> 1. we have pod A attached volume A on a node.
> 2. when the job in pod A is completed, pod A entered Succeed/Completed status, which would trigger the detach happen.
> 3. but something wrong happened in the backend to make the detach process failed.
> 4. pod B was created and scheduled to the same node, and also use volume A as its volume.
> 5. pod B would trigger attach process.
> 
> The problem here is the failed detach for pod A would never have tr-try and the attach process of pod A would proceed and get unexpected result from the node.

@Anjingkegui I have committed a pr, it may help you.: https://github.com/kubernetes/kubernetes/pull/88572

**Comment by ivan-cai** [comment]
@saad-ali @jingxu97

**Comment by ivan-cai** [comment]
https://github.com/kubernetes/kubernetes/issues/88565#issuecomment-634012975

**Comment by ivan-cai** [comment]
> I have met the same issue in our environment. (v1.15.7)
> 
> What we got (timeline-based):
> 
> 1. we have pod A attached volume A on a node.
> 2. when the job in pod A is completed, pod A entered Succeed/Completed status, which would trigger the detach happen.
> 3. but something wrong happened in the backend to make the detach process failed.
> 4. pod B was created and scheduled to the same node, and also use volume A as its volume.
> 5. pod B would trigger attach process.
> 
> The problem here is the failed detach for pod A would never have tr-try and the attach process of pod A would proceed and get unexpected result from the node.

@saad-ali @jingxu97
