### ISSUE TITLE
Applying a daemonset to thousands of controllers

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#88583]
Request for info:

**Goal:** To manage 50K to 100K nodes using kubernetes for applying daemonsets

A possibility:
- To manage this scale, we need around 5K to 10K of controllers/masters.

- Nodes can add labels that describe self as static & dynamic data
  Static data: e.g. clustername, platform, HWSKU, ...
  Dynamic Data: e.g. Status, ...

- Apply daemonset with appropriate node-selectors at a central place - May be a cloud file storage

-  The master nodes, are configured with cloud storage path & credentials required to access daemonset manifests

- Master nodes watch storage for updates, apply updated manifests locally.

**Questions:**

1. Is the above feasible today ?
2. Is there a better way to handle this ?

**Related questions**:
a. When a master nodes encounter failure in applying a manifest, does it provide any hook for registering a custom script ?
   For example, the custom script can take some action, like log a message, raise an alert, ...

b. When managing thousands of controllers & nodes, is there any inherent support or suggestion for a dash-board feasibility to reflect the current status of nodes w.r.t deployments/daemonsets/...

Thank you!

**Comment by renukamanavalan** [comment]
I require #sig-scalability. Not sure, how to add this.

**Comment by oxddr** [comment]
At the moment Kubernetes supports [5000 nodes in cluster](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md). 50-100k is way above this.
