### ISSUE TITLE
Implementation of merge in `scheduler/framework/v1alpha1/interface` should be more concise？

### ISSUE THREAD

**Issue by shikanon** [kubernetes/kubernetes#88581]
I find method `Merge` in `pkg/scheduler/framework/v1alpha1/interface.go` implementation has a problem that the variable `finalStatus.code`  is assigned repeatedly. Why to design it in this way? Can we remove duplicate?

```
func (p PluginToStatus) Merge() *Status {
	if len(p) == 0 {
		return nil
	}

	finalStatus := NewStatus(Success)
	var hasError, hasUnschedulableAndUnresolvable, hasUnschedulable bool
	for _, s := range p {
		if s.Code() == Error {
			hasError = true
		} else if s.Code() == UnschedulableAndUnresolvable {
			hasUnschedulableAndUnresolvable = true
		} else if s.Code() == Unschedulable {
			hasUnschedulable = true
		}
                // First assigned
		finalStatus.code = s.Code()
		for _, r := range s.reasons {
			finalStatus.AppendReason(r)
		}
	}
 
       // Second assigned
	if hasError {
		finalStatus.code = Error
	} else if hasUnschedulableAndUnresolvable {
		finalStatus.code = UnschedulableAndUnresolvable
	} else if hasUnschedulable {
		finalStatus.code = Unschedulable
	}
	return finalStatus
}
```

finalStatus.code was assigned two times.

**Comment by gavinfish** [comment]
@shikanon The second assign is only triggered by special cases. Normally it should only use the first assign.

**Comment by shikanon** [comment]
> The second assign is only triggered by special cases. Normally it should only use the first assign.

Okay, how to remove it?

**Comment by gavinfish** [comment]
@shikanon I do not think we need to remove anything here.

**Comment by shikanon** [comment]
> @shikanon I do not think we need to remove anything here.

look at the code, I think the first assign is always equals the second assign. 

when `s.Code() == Error`, then `finalStatus.code = Error`,

when `s.Code() == UnschedulableAndUnresolvable`, then `finalStatus.code = UnschedulableAndUnresolvable`,

when `s.Code() == Unschedulable`, then `finalStatus.code = Unschedulable`,

second assigned why not to be delete?

**Comment by gavinfish** [comment]
There are more types for `s.Code()`, so the if/else won't always be triggered.

https://github.com/kubernetes/kubernetes/blob/364c66ed9c7125e55ced73b35f00a9a73fd79e96/pkg/scheduler/framework/v1alpha1/interface.go#L54-L77

**Comment by shikanon** [comment]
> triggered

Okay, you mean that error messages assign finalStatus with priority when it rise.

**Comment by shikanon** [comment]
> There are more types for `s.Code()`, so the if/else won't always be triggered.
> 
> https://github.com/kubernetes/kubernetes/blob/364c66ed9c7125e55ced73b35f00a9a73fd79e96/pkg/scheduler/framework/v1alpha1/interface.go#L54-L77

Okay, you mean that error messages assign finalStatus with priority when it rise.

**Comment by shikanon** [comment]
> There are more types for `s.Code()`, so the if/else won't always be triggered.

Okay, you mean that error messages assign finalStatus with priority when it rise.
