### ISSUE TITLE
Preemption: set "Status.Reason" for victim pod

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes/kubernetes#88614]
**What would you like to be added**:
Set the `Status.Reason` as `Preempted ` or whatever

**Why is this needed**:
When a `Pod` is preempted by a Preemptor, the `Pod` will be delete directly, the `PodPhase` is `Failed` but the `Reason` is nil.

A controller which create `pod` will hit issue.
Sometimes it found the `pod` is disappear, that's ok, it will create another `pod`
sometimes it found the `pod` `failed`, actually that's not a really `pod` failed, so the scenario will make some confuse.

So I think if we can use the `Status.Reason`, that will resolve such issue.

**Comment by tedyu** [comment]
```
a Pod is prompted by a Preemptor
```
I think you meant preempted.
Accordingly the Status.Reason should be set 'Preempted'

**Comment by vincent-pli** [comment]
@tedyu 
Thanks, corrected.

**Comment by Huang-Wei** [comment]
@vincent-pli It seems `status.reason` is now only used by kubelet:

https://github.com/kubernetes/kubernetes/blob/af9e0be163a89a4cca8f602ed7ff60353ef866bb/pkg/kubelet/eviction/eviction_manager.go#L573-L577

And I seldom see non-kubelet components set `status.reason` or `status.conditions[*].reason` as kubelet is the only component know exactly the status of the Pod. If other components decide to delete a Pod, its `Delete` request goes to APIServer and tweaked to updated the Pod's `spec.deletionTimestamp` to a non-nil value, which is used in scheduler when it preempts victims Pods upon preemption.

If I understand correctly, `spec.deletionTimestamp` is only allowed to be mutated by apiserver internally, so it's impossible to achieve (1) set `status.reason` to `preempted` and (2) set `spec.deletionTimestamp` in one request. And I doubt we want to achieve this by 2 API requests.

> Sometimes it found the pod is disappear, that's ok, it will create another pod
> sometimes it found the pod failed, actually that's not a really pod failed, so the scenario will make some confuse.

As aforementioned, a preempted Pod will firstly be updated and then deleted. So I don't quite follow what you mean by "disppear".
And what do you mean by "failed" Pod? Are you talking about a preempted Pod by scheduler, or an evicted Pod by kubelet?

**Comment by vincent-pli** [comment]
@Huang-Wei 
Thanks for your comments.
I talk about preempted Pod by scheduler not evicted.
I agree with you that should be 2 request.
The solution of `eviction_manager` is what exactly I expect to:
Update `Reason` `Message` then do the delete(deletionTimestamp)
oppose to this:
https://github.com/kubernetes/kubernetes/blob/af9e0be163a89a4cca8f602ed7ff60353ef866bb/pkg/scheduler/scheduler.go#L434
and this:
https://github.com/kubernetes/kubernetes/blob/af9e0be163a89a4cca8f602ed7ff60353ef866bb/pkg/scheduler/scheduler.go#L769-L771

As the code said, no status update delete directly, there is no chance for a `controller` to distinguish a real pod `faild` or `preempted` case.

**Comment by Huang-Wei** [comment]
@vincent-pli May I know your motivations on distinguishing a Preempted deletion and a regular deletion? on controller side. Are you trying to achieve something based on the deletion reason?

**Comment by vincent-pli** [comment]
@Huang-Wei 
Not Preempted deletion and regular deletion, what I want to distinguishing is Pod failed caused by Preempted deletion and real Pod failed.
There are difference handle behavior for these two cases.
For failed caused by Preempted deletion, we will create new Pod
For real failed, we just mark Pod's owner CR as failed.

**Comment by Huang-Wei** [comment]
Got it. In the next release (1.19), we will start to extract preemption related logic into extension points, and each extension point will have their own default plugin. This issue will be taken into consideration. Thanks for the feedback.

**Comment by alculquicondor** [comment]
What if we add an event to the Pod? But that also requires a second API request :(

**Comment by Huang-Wei** [comment]
> But that also requires a second API request :(

True, end-user should be aware of this when implementing their own plugin.
The default deletion logic will remain unchanged.

**Comment by alculquicondor** [comment]
@vincent-pli do you run your own control plane?

**Comment by alculquicondor** [comment]
An alternative I can think of is that we add a new DeleteOption that allows to include a reason for deletion or the controller that is triggering it. But that's an API change that we would need to discuss with API reviewers.

**Comment by vincent-pli** [comment]
@alculquicondor 
I think that's useful with `Reason` or `trigger controller`.  and I run my controller, thanks

**Comment by alculquicondor** [comment]
@vincent-pli to clarify my question: do you (or are you able to) run your own scheduler?

**Comment by vincent-pli** [comment]
@alculquicondor 
I do have my own scheduler(based on Scheduler Framework) but only for gang-schedule not preemption.

**Comment by alculquicondor** [comment]
@vincent-pli do you still need this?

**Comment by Huang-Wei** [comment]
@vincent-pli Once the PostFilter extension point is out, users can choose to implement their victims deletion logic - either deleting them directly or update and then delete.

**Comment by vincent-pli** [comment]
@alculquicondor @Huang-Wei 
Thanks, I still need the feature, does the `PostFilter extension` you mean the `scheduler framework`: https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/?

**Comment by Huang-Wei** [comment]
Yes. In 1.19, we proposed the PostFilter extension point, and the defaultpreemption plugin is being developed. Basically this plugin is an in-tree implementation, but you can implement your own as the alternative.

**Comment by vincent-pli** [comment]
@Huang-Wei 
Glad to hear that, thanks.
