### ISSUE TITLE
kubectl cp chokes on files with square brackets

### ISSUE THREAD

**Issue by graham-web** [kubernetes/kubernetes#88630]
**What happened**:

Attempting to `kubectl cp` a directory of files from local machine to remote pod. One of the files inside the directory contains square brackets in the name (e.g. `broken[.txt`)

**What you expected to happen**:

File should appear in remote pod at `/tmp/test/broken[.txt`

**How to reproduce it (as minimally and precisely as possible)**:
```
mkdir test
touch 'test/broken[.txt'
kubectl cp test podname:/tmp/
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Digitalocean managed kubernetes
- OS (e.g: `cat /etc/os-release`):
macOS mojave 10.14.6
- Kernel (e.g. `uname -a`):
Darwin Graham-Macbook 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

**Comment by starbassma** [comment]
Hello,
I'm working on it..

**Comment by starbassma** [comment]
Hello,
Actually there is a pending PR about this issue (check #https://github.com/kubernetes/kubernetes/pull/78928)
Regards,

**Comment by kfox1111** [comment]
We've seen this.

/reopen
/remove-lifecycle rotten
