### ISSUE TITLE
admin.conf compromise, how to generate a new admin.conf to replace the old admin.conf

### ISSUE THREAD

**Issue by zhujintao** [kubernetes/kubernetes#88688]

**Comment by neolit123** [comment]
if this is using kubeadm try `kubeadm alpha kubeconfig user --help`.
but if your `/etc/kubernetes/pki/ca.*` files are compromised too, i'd say it's better to recreate this cluster.

/area kubeadm
/close

**Comment by zhujintao** [comment]
> if this is using kubeadm try `kubeadm alpha kubeconfig user --help`.
> but if your `/etc/kubernetes/pki/ca.*` files are compromised too, i'd say it's better to recreate this cluster.
> 
> /area kubeadm
> /close

tks! how to disable old versions, or reject old version

**Comment by neolit123** [comment]
> tks! how to disable old versions, or reject old version

i don't think there is a way to do that.
the old admin.conf is for a user that is part of a valid group and has valid client certificates.

you can still try asking in #kubernetes-users or #sig-auth of k8s slack.
