### ISSUE TITLE
1.17.0: Pod sometime intermittently not connect to the external reachable system

### ISSUE THREAD

**Issue by SaravanakumarSivasankaran** [kubernetes/kubernetes#88696]
**What happened**:

> Pods sometime intermittently not connect to the external reachable system.

**What you expected to happen**:

> The application pod should always able to reachable to external reachable system.

**How to reproduce it (as minimally and precisely as possible)**:

> Install kubernetes version v1.17.0 and launch some pods with the images mentioned below section

**Anything else we need to know?**:

**Environment**:

> - Kubernetes version (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

> NAME="CentOS Linux"
> VERSION="7 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7"
> HOME_URL="https://www.centos.org/"

> BUG_REPORT_URL="https://bugs.centos.org/"

> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

> Linux dir-worker1.company.com 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

# rpm -qa | grep kube

> kubelet-1.17.0-0.x86_64
> kubectl-1.17.0-0.x86_64
> kubeadm-1.17.0-0.x86_64
> kubernetes-cni-0.7.5-0.x86_64

- Network plugin and version (if this is a network-related bug):
- Others:

Kubernetes Images:

> k8s.gcr.io/kube-controller-manager                               v1.15.7             d2f090f2479f        7 weeks ago         159 MB
> k8s.gcr.io/kube-apiserver                                        v1.15.7             c500a024ff84        7 weeks ago         207 MB
> k8s.gcr.io/kube-proxy                                            v1.15.7             ae3d9889423e        7 weeks ago         82.4 MB
> k8s.gcr.io/kube-scheduler                                        v1.15.7             78b4180ab00d        7 weeks ago         81.1 MB
> k8s.gcr.io/kube-proxy                                            v1.17.0             7d54289267dc        8 weeks ago         116 MB
> k8s.gcr.io/kube-controller-manager                               v1.17.0             5eb3b7486872        8 weeks ago         161 MB
> k8s.gcr.io/kube-apiserver                                        v1.17.0             0cae8d5cc64c        8 weeks ago         171 MB
> k8s.gcr.io/kube-scheduler                                        v1.17.0             78c190f736b1        8 weeks ago         94.4 MB
> k8s.gcr.io/coredns                                               1.3.1               eb516548c180        12 months ago       40.3 MB
> k8s.gcr.io/etcd                                                  3.3.10              2c4adeb21b4f        14 months ago       258 MB
> k8s.gcr.io/pause                                                 3.1                 da86e6ba6ca1        2 years ago         742 kB
> k8s.gcr.io/echoserver                                            1.4                 a90209bb39e3        3 years ago         140 MB

Is any issue related to kube-dns version "k8s.gcr.io/coredns:1.3.1" ?

**Comment by tedyu** [comment]
Have you looked at kueblet log during the period without connectivity ?

Thanks

**Comment by neolit123** [comment]
/triage support
/remove-kind bug

please try the latest 1.17.3.

**Comment by SaravanakumarSivasankaran** [comment]
Tedyu: I could not found logs /var/log directory. You mean "journalctl -u kubelet" logs. I could found the following in errors in journalctl, can exactly the issue seen.

>  watcher.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/run
>  pod_workers.go:191] Error syncing pod b745ca30-c9be-4ed6-a2cd-165699777df9 ("mypod.

Neolit123: Seems not able to install 1.17.3 rpms

> yum install -y kubelet-1.17.3 kubeadm-1.17.3 kubectl-1.17.3
> ......
> No package kubelet-1.17.3 available.
> No package kubeadm-1.17.3 available.
> No package kubectl-1.17.3 available.

Able to install "yum install -y kubelet-1.17.0 kubeadm-1.17.0 kubectl-1.17.0" but not 1.17.3 even though the rpm showing in repo
"https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/primary.xml"
