### ISSUE TITLE
Pod subresource storage (Exec, PortForward, Proxy, Log) should return appropriate object on New

### ISSUE THREAD

**Issue by csrwng** [kubernetes/kubernetes#8869]
The following resources need to be returned:

Exec -> PodExec
PortForward -> PodPortForward
Proxy -> PodProxy
Log -> PodLog

**Comment by csrwng** [comment]
Related to https://github.com/GoogleCloudPlatform/kubernetes/issues/8868

**Comment by smarterclayton** [comment]
Closing due to age and general lack of need.
