### ISSUE TITLE
Missing validation for HPA annotation

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#88738]
Recently, I tried to create an HPA object with an empty value for the `autoscaling.alpha.kubernetes.io/conditions` annotation and even though the response from apiserver is a 500, the object itself still got created (I verified this by querying for the key from the etcd). And since then `kubectl get/list hpa` calls are failing because apiserver seems to be unable to parse that particular object. Even worse, I wasn't even able to delete that object through the k8s api (had to delete the key directly from etcd).

This was on a v1.14.9 cluster.

Here's a minimal hpa object to reproduce the issue (both `v2beta1` and `v2beta2` seem to have it):
```
{
    "kind": "HorizontalPodAutoscaler",
    "apiVersion": "autoscaling/v2beta1",
    "metadata": {
        "name": "bad-hpa-object",
        "annotations": {
            "autoscaling.alpha.kubernetes.io/conditions": ""
        }
    },
    "spec": {
        "scaleTargetRef": {
            "kind": "Deployment",
            "name": "test",
            "apiVersion": "apps/v1"
        },
        "maxReplicas": 1
    }
}
```

Failing "create hpa" request:
```
$ kubectl create -f bad-hpa-object.json --v=8
...
I0302 18:45:37.912801   25603 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unexpected end of JSON input","code":500}
I0302 18:45:37.913015   25603 helpers.go:196] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"hpa.json\": unexpected end of JSON input",
  "code": 500
}]
```

Kubectl call failing after above request:
```
$ kubectl get hpa
Error from server: unexpected end of JSON input
```

But object itself is present in etcd and I manually deleted it:
```
$ ETCDCTL_API=3 etcdctl get --keys-only --prefix "/registry/horizontalpodautoscalers/"
/registry/horizontalpodautoscalers/default/bad-hpa-object
$
$ etcdctl del /registry/horizontalpodautoscalers/default/bad-hpa-object
1
```

Which fixed the issue:
```
$ kubectl get hpa
No resources found.
```

cc @kubernetes/sig-api-machinery-bugs (I'm tagging apimachinery here because even though this could be a missing validation for a particular API owned by @kubernetes/sig-autoscaling-bugs , I'm wondering why apiserver created the object even though it returned a 500 to the client)

**Comment by liggitt** [comment]
/remove-sig api-machinery

This is a bug in the autoscaling conversion. There are several annotations that are used to round-trip v2beta1 and v2beta2 data into v1 types, but those are not cleared/verified when persisting versions other than v1

**Comment by liggitt** [comment]
cc @kubernetes/sig-autoscaling-bugs

**Comment by liggitt** [comment]
> I'm wondering why apiserver created the object even though it returned a 500 to the client

The server converted the object the user sent to the internal version, then to v1, then persisted the object to etcd, which succeeded. It then tried to convert that v1 object back to internal and back to v1beta2 to return to the user. That conversion step failed because the conversions are not symmetric.

**Comment by shyamjvs** [comment]
@liggitt Thanks for the above explanation. But if we could successfully persist the object in etcd as `v1`, I'm not sure why we would fail even when trying to get that object using the `v1` api:

```
$ curl localhost:8080/apis/autoscaling/v1/horizontalpodautoscalers
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "unexpected end of JSON input",
  "code": 500
}
```

**Comment by liggitt** [comment]
It's a bug in the conversion. The conversion from internal -> v1 (for persistence) completes without error. The conversion from v1 -> internal (part of serving the objects) fails.

**Comment by shyamjvs** [comment]
Then keeping the sig-autoscaling part of the bug aside, why is it not an apimachinery issue too? Because iiuc we're essentially allowing to persist an object that we're sure to fail converting back to internal.

**Comment by liggitt** [comment]
manually written conversions are owned by the sig that owns those APIs, in this case sig-autoscaling

**Comment by shyamjvs** [comment]
Thanks.

In more general sense, isn't expecting that conversions are written properly by author of an API more like a "good will" rather than enforcement currently? (Sorry for any ignorance in asking this question..) I'm wondering if we can have apiserver itself check for (v1 -> internal) conversion before persisting an object? Or you think it's too expensive for it to do that?

**Comment by liggitt** [comment]
That's a very expensive check to run on all conversions of all objects to guard against a programming error.

**Comment by shyamjvs** [comment]
Now I have my answer, thanks! :)

**Comment by shyamjvs** [comment]
fyi - @MaciekPytel :)

**Comment by shyamjvs** [comment]
Per @liggitt's advice, I was looking into the conversion code today along with Harish Kuna. The bug seems to be coming from ([ref](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v1/conversion.go#L404-L408)):

```
if currentConditionsEnc, hasCurrentConditions := out.Annotations[autoscaling.HorizontalPodAutoscalerConditionsAnnotation]; hasCurrentConditions {
	var currentConditions []autoscalingv1.HorizontalPodAutoscalerCondition
	if err := json.Unmarshal([]byte(currentConditionsEnc), &currentConditions); err != nil {
		return err
	}
```

part of `Convert_v1_HorizontalPodAutoscaler_To_autoscaling_HorizontalPodAutoscaler` function. And the problem is that the annotation value being passed is an empty string and `json.Unmarshal` throws ["unexpected end of JSON input"](https://play.golang.org/p/AVDyEVYCX0D) in such case.

So similar to what we do elsewhere, we should add an extra check in the if condition that `currentConditionsEnc != ""`.

Btw - when I set the value of the annotation to empty array `"[]"` in the object, it gets created fine. So it's almost certainly the bug above.

**Comment by liggitt** [comment]
It's not just "", but any error unmarshaling the JSON from the annotation that must be tolerated (for all the annotations we round trip JSON through in these objects)

**Comment by liggitt** [comment]
Fixes open for review:

* master - #89963
* 1.18.x - #89965
* 1.17.x - #89967
* 1.16.x - #89968
* 1.15.x - #89969
