### ISSUE TITLE
Add --dry-run=server|client to kubectl scale

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#88740]
**What would you like to be added**:
Support `kubectl scale --dry-run=server|client`.

**Why is this needed**:
Dry-running a `kubectl scale` command is helpful for validating that a scale request will succeed or fail.

The values `--dry-run` and `--dry-run=true|false` have been deprecated and replaced by `--dry-run=client`, and `--dry-run=server` is now possible. This issue is a follow up to https://github.com/kubernetes/kubernetes/issues/85652, where we added `--dry-run=server|client` to other kubectl commands.

This would also help us test dry-run on the `/scale` subresource: https://github.com/kubernetes/kubernetes/issues/76971

Blocked by https://github.com/kubernetes/kubernetes/issues/88274.

Related, but not-blocking: https://github.com/kubernetes/kubernetes/issues/68514

**Comment by julianvmodesto** [comment]
@apelisse looks like we'll get https://github.com/kubernetes/kubernetes/issues/88274 in for v1.18.

This `kubectl scale --dry-run=client|server` seems small and acceptable risk, so we could get it in for v1.18 too?

**Comment by apelisse** [comment]
That seems fine, it's not the end of the world if we can't. Let me see.
