### ISSUE TITLE
kubectl get events does not show how long events are kept

### ISSUE THREAD

**Issue by schollii** [kubernetes/kubernetes#88748]
**What happened**:
`kubectl get events --all-namespaces` showed no events whatsoever, without indicating the period this covers... an hour, a day, a week? 

**What you expected to happen**:

I expected to see a line saying "In the last PERIOD, these are the events that were logged:", where PERIOD would reflect the value used for event TTL (`kube-apiserver --event-ttl PERIOD` or default if that arg not given). Or some equivalent output or a way to get that info from the cluster. 

**How to reproduce it (as minimally and precisely as possible)**:

Run that same command

**Anything else we need to know?**:

Not likely

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13

**Comment by liggitt** [comment]
This isn't really a CLI issue. The events API does not provide the information you are wanting
