### ISSUE TITLE
Resource consumer controller does not respect configured dns domain

### ISSUE THREAD

**Issue by vryzhenkin** [kubernetes/kubernetes#88752]
**What happened**:
During execution of HPA e2e part on kubespray deployment environment with non-default domain 7 of 8 HPA tests failed. One passed by accident due it require only downscale.

**What you expected to happen**:
All 8 tests passed

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a Kubernetes cluster using any desired tool with any domain setting that differs from cluster.local
2. Execute e2e tests with regex [Feature:HPA]

**Anything else we need to know?**:
Discovered using metrics server 0.3.6.
Domain set to different than default

During normal execution was observed that creating of consume requests doing nothing.
```
Mar  3 01:27:04.782: INFO: RC test-deployment: sending request to consume 325 millicores
Mar  3 01:27:04.782: INFO: ConsumeCPU URL: {https   172.19.116.45:443 /api/v1/namespaces/horizontal-pod-autoscaling-470/services/test-deployment-ctrl/proxy/ConsumeCPU  false durationSec=30&millicores=325&requestSizeMillicores=100 }
Mar  3 01:27:09.542: INFO: waiting for 3 replicas (current: 1)
Mar  3 01:27:29.543: INFO: waiting for 3 replicas (current: 1)
Mar  3 01:27:29.774: INFO: RC test-deployment: sending request to consume 0 MB
Mar  3 01:27:29.774: INFO: ConsumeMem URL: {https   172.19.116.45:443 /api/v1/namespaces/horizontal-pod-autoscaling-470/services/test-deployment-ctrl/proxy/ConsumeMem  false durationSec=30&megabytes=0&requestSizeMegabytes=100 }
Mar  3 01:27:30.052: INFO: RC test-deployment: sending request to consume 0 of custom metric QPS
Mar  3 01:27:30.052: INFO: ConsumeCustomMetric URL: {https   172.19.116.45:443 /api/v1/namespaces/horizontal-pod-autoscaling-470/services/test-deployment-ctrl/proxy/BumpMetric  false delta=0&durationSec=30&metric=QPS&requestSizeMetrics=10 }
```
By idea such requests goes through controller and then - controller sending it to consumers. But consumers continue consume 1Mi MEM and 0 CPU even in case I saw a request from e2e to controller.
```
freerunner@pegassie:[~/metrics-server] (master)$ kubectl top pod -n horizontal-pod-autoscaling-470
NAME                               CPU(cores)   MEMORY(bytes)
test-deployment-5948f49fb8-c97p7   0m           1Mi
```

Metrics-server works fine because logging in to container and execute some primitive operations did its job and normal metrics was caught. 

Then I tried to execute curl command manually to make consume request.
`curl --data "millicores=300&durationSec=600" http://10.233.97.21:8080/ConsumeCPU`
And it worked as expected. (HPA also)
```
root@kaas-node-b3de5b83-1f27-439d-85d5-909a86509de0:~# kubectl top po -n horizontal-pod-autoscaling-470
NAME                               CPU(cores)   MEMORY(bytes)
test-deployment-5948f49fb8-c97p7   300m         6Mi
test-deployment-5948f49fb8-hgrbj   0m           1Mi
```

Then, in tries to find root cause I found that:
https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/resource-consumer-controller/controller.go#L216

So, controller construct an URL to reach consumers that for sure will not work with domains that not 'cluster.local`.
Moreover - controller does not write any logs that may help to debug issues with that.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.7/v1.17.3/v1.18.0-beta/master
- Cloud provider or hardware configuration: Openstack VMs
- OS (e.g: `cat /etc/os-release`): 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`): Linux kaas-node-b3de5b83-1f27-439d-85d5-909a86509de0 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Kubespray

**Comment by BenTheElder** [comment]
/remove-sig testing
SIG testing owns the frameworks, CI, etc. SIG autoscaling is responsible for their tests.

**Comment by vponomaryov** [comment]
This bug has been fixed by following PR: https://github.com/kubernetes/kubernetes/pull/92964
