### ISSUE TITLE
Kublet calls to du can hang indefinitely

### ISSUE THREAD

**Issue by briankmatheson** [kubernetes/kubernetes#88767]
**What happened**:

kubelet pod grew in size as it spawned an ever-increasing number of du child procs.

**What you expected to happen**:

This check should maybe timeout after a while.  Preferably before we spawn another du.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not quite sure unfortunately, I haven't seen this behavior first-hand.  I did get a report from a 3rd party about an end-user who experienced the behavior, and so I took a look at the code, and the behavior I would expect from du on a network filesystem that's not responding is that it would block indefinitely.

**Anything else we need to know?**:
I am new to the codebase but this looks like the culprit to me:
https://github.com/kubernetes/kubernetes/blob/23eb2180c65472f5c25fdec551b594f0b2db427d/pkg/volume/util/fs/fs.go#L71
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by briankmatheson** [comment]
I came across potentially related PR https://github.com/kubernetes/kubernetes/pull/74675

/sig node

**Comment by briankmatheson** [comment]
That's certainly a way to get around du proc proliferation.  I'm afraid that stat call might block indefinitely leaving us with the same ultimate problem though.  IMO using `du` is convenient for a bunch of reasons.  Would it be acceptable to just invoke du under timeout?  Is there a good way to set that timeout dynamically (i.e. is there some time interval constant that we can base our timeout value off of?)

**Comment by gongguan** [comment]
> Is there a good way to set that timeout dynamically (i.e. is there some time interval constant that we can base our timeout value off of?)

@dims WDYT?

**Comment by gongguan** [comment]
hi, could you please upload kubelet log?
