### ISSUE TITLE
Make kube-apiserver use SO_REUSEPORT to enable graceful bootstrapping and upgrades of self-hosted kube-apiserver

### ISSUE THREAD

**Issue by invidian** [kubernetes/kubernetes#88785]
**What would you like to be added**:
Add `SO_REUSEPORT` Linux socket option, when binding ports in `kube-apiserver`.

**Why is this needed**:
That will allow to run multiple instances of `kube-apiserver` on a single host, which makes bootstrapping and upgrading self-hosted `kube-apiserver` much more graceful, as it allows to wait until new self-hosted pod is up and running before shutting down old process. This applies for both pivoting from temporary `kube-apiserver` to Pod as well as rolling upgrades via e.g. `Deployment` with `hostNetwork: true`.

At the moment, when running single-controller-node cluster using [bootkube](https://github.com/kubernetes-sigs/bootkube), upgrade process for `kube-apiserver` relies on [pod checkpointer](https://github.com/kubernetes-sigs/bootkube/tree/master/cmd/checkpoint), which restores `kube-apiserver` as static Pod during the outage of self-hosted `kube-apiserver`, which causes some short downtime and is rather error prone, as it's hard to distinguish if the upgrade succeeded, as crashing `kube-apiserver` is part of the process, as it tries to bind already occupied port.

The alternative to that is to make `kube-apiserver` listen on some random IP address and put a proxy program on the front, which will be listening on the right port and using `SO_REUSEPORT`. For example HAProxy. This is what [kube-apiserver-helm-chart](https://github.com/flexkube/kube-apiserver-helm-chart/blob/master/templates/deployment.yaml#L124) is doing. While this work, it adds additional complexity to the process and requires additional resources. It may also have some side-effects caused by the proxy configuration.

Some possible downsides:
- When scraping metrics from single `kube-apiserver` port, it will return different metrics on each call, depending which instance you hit. This can be tested with following command: `kubectl get --raw /metrics | grep rest_client_requests_total | grep GET | grep 'code="200"'`. On the other hand, running multiple instances on a single host is rather undesired and should be only temporary during upgrades, so I don't see this as a major disadvantage.
- The solution might need to be multi-platform. If that's the case, then the patch I posted is not sufficient. Perhaps some library like https://github.com/kavu/go_reuseport or https://github.com/libp2p/go-reuseport could be used.

From my testing, following simple patch is enough to enable it:
```patch
diff --git a/staging/src/k8s.io/apiserver/pkg/server/options/serving.go b/staging/src/k8s.io/apiserver/pkg/server/options/serving.go
index 06edf361e91..0cf05935834 100644
--- a/staging/src/k8s.io/apiserver/pkg/server/options/serving.go
+++ b/staging/src/k8s.io/apiserver/pkg/server/options/serving.go
@@ -17,13 +17,16 @@ limitations under the License.
 package options
 
 import (
+       "context"
        "fmt"
        "net"
        "path"
        "strconv"
        "strings"
+       "syscall"
 
        "github.com/spf13/pflag"
+       "golang.org/x/sys/unix"
        "k8s.io/klog"
 
        utilnet "k8s.io/apimachinery/pkg/util/net"
@@ -316,11 +319,18 @@ func (s *SecureServingOptions) MaybeDefaultWithSelfSignedCerts(publicAddress str
        return nil
 }
 
+func reusePort(network, address string, conn syscall.RawConn) error {
+       return conn.Control(func(descriptor uintptr) {
+               syscall.SetsockoptInt(int(descriptor), syscall.SOL_SOCKET, unix.SO_REUSEPORT, 1)
+       })
+}
+
 func CreateListener(network, addr string) (net.Listener, int, error) {
        if len(network) == 0 {
                network = "tcp"
        }
-       ln, err := net.Listen(network, addr)
+       config := &net.ListenConfig{Control: reusePort}
+       ln, err := config.Listen(context.Background(), network, addr)
        if err != nil {
                return nil, 0, fmt.Errorf("failed to listen on %v: %v", addr, err)
        }
```

`kube-apiserver` with following patch is available with this `hyperkube` image (based on `v1.17.3` tag): `invidian/hyperkube-amd64:v1.17.3-api-so-reuseaddr-4`.

Please let me know what you think and if I should open a PR with given patch.

**Comment by fedebongio** [comment]
/assign @lavalamp @deads2k 
Could you please take a look to this request? thanks!

**Comment by invidian** [comment]
Thanks for positive feedback @lavalamp.

>How do you prevent a malicious process from also opening up the port? 

From socket manpage:
>To prevent port hijacking, all of the pro‐
              cesses binding to the same address must have the same effec‐
              tive UID.

>I wasn't a fan at first, but the patch is pretty small. This would need to be tested somehow.

As I said, if multiple operating systems must be supported, then patch will be slightly bigger or we should use the library, which will take care of that. Does `kube-apiserver` must be compatible with Windows, BSD, or Darvin?

Regarding the tests, I'm happy to implement them too. I know how to write unit test for it, but help with writing some integration test would be appreciated :)

**Comment by invidian** [comment]
>As I said, if multiple operating systems must be supported, then patch will be slightly bigger or we should use the library, which will take care of that. Does kube-apiserver must be compatible with Windows, BSD, or Darvin?

As far as I see in https://kubernetes.io/docs/setup/release/notes/#server-binaries, only Linux binaries are provided, so I assume just Linux support is fine for now. That's good news. I will go ahead and open a PR about it with unit test at least.

**Comment by invidian** [comment]
Created https://github.com/kubernetes/kubernetes/pull/88893.

**Comment by invidian** [comment]
Hm, now that I think about it, it would be nice to have the same change applied also for `kube-controller-manager` and `kube-scheduler`, as if they run with `--bind-address`, upgrading won't be possible either... @lavalamp would it be possible to have the same implementation for them as well?

**Comment by aojea** [comment]
I understand the big benefit for the upgrade but what happens if, for whatever reason (upgrade failed to remove the old apiserver, ...) , 2 or more apiservers with different versions are bound to the socket?

My understanding is that SO_REUSEPORT will distributes connections evenly across all of the processes, and some clients will be served by different versions

**Comment by invidian** [comment]
>I understand the big benefit for the upgrade but what happens if, for whatever reason (upgrade failed to remove the old apiserver, ...) , 2 or more apiservers with different versions are bound to the socket?

> My understanding is that SO_REUSEPORT will distributes connections evenly across all of the processes, and some clients will be served by different versions

That's correct. But according to [Kubernetes version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/), it should be fine to run 2 different versions of API server during the upgrade. If one have HA controlplane, this will be happening anyway.

In theory, this problem may occur, if more than one upgrade fails to remove old API server instance, so skew policy will be violated.

**Comment by lavalamp** [comment]
Yes, that is correct, HA systems already run in that split-version configuration. (I personally consider it undertested and therefore a state to be minimized, but this is how it is supposed to work.)

**Comment by lavalamp** [comment]
As far as what platforms we expect apiserver to run on-- I think the windows clusters still run the control plane on linux machines? I'd expect linux variants (both x86 and arm) to work. I think it's OK if the feature just isn't offered on all platforms, as long as it's documented and apiserver still *builds*.

**Comment by invidian** [comment]
>As far as what platforms we expect apiserver to run on-- I think the windows clusters still run the control plane on linux machines? I'd expect linux variants (both x86 and arm) to work. I think it's OK if the feature just isn't offered on all platforms, as long as it's documented and apiserver still builds.

I have little idea how to implement that, but I'll have a look.

**Comment by invidian** [comment]
>I have little idea how to implement that, but I'll have a look.

Okay, I think I figured it out. Triggering tests on #88893 would be appreciated :)
