### ISSUE TITLE
Kubelet should not restart RestartPolicyNever pods when machine reboots

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#8878]
(Discussed in person today.)

@dchen1107

**Comment by yujuhong** [comment]
I believe we check the pod status from the apiserver to avoid this. However, if kubelet fails to update the pod status before the reboot and the dead containers were deleted, kubelet may still restart the pod. We'll need a checkpoint to recover the information.

**Comment by yujuhong** [comment]
No one is working on this. Lower the priority to reflect the status.
