### ISSUE TITLE
How to get the command of interaction between user and pod after kubectl Exec

### ISSUE THREAD

**Issue by felix0080** [kubernetes/kubernetes#88791]
How to get the command of interaction between user and pod after kubectl Exec？We want to monitor the interaction instructions between users and pod to prevent users from entering unsafe instructions, which will have a bad impact on the host. Is there any way to do this? Thank you for your help.

**Comment by jpjeery6** [comment]
Is there any way to do that?

**Comment by felix0080** [comment]
The way I can think of is to intercept from webshell

**Comment by soltysh** [comment]
For the record, current [audit mechanism](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) only looks at the requests and responses between client and server and has no way to look into what's going on in the pod after `kubectl exec` or similar. One possible alternative is to force a base image with a central auditing mechanism, such that all commands executed in a pod get logged to a central place.
