### ISSUE TITLE
Makefile:1: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by HtcOrange** [kubernetes/kubernetes#88808]
I want to use kubemark to test the cluster. But when I wanna to install it by source code, in the step of compiling, the error occured as follows:
```bash
archlab@GG-135:~/gocode/src/k8s.io/kubernetes$ KUBE_BUILD_PLATFORMS=linux/amd64  make kubemark GOFLAGS=-v GOGCFLAGS="-N -l"
Makefile:1: *** missing separator.  Stop.
```
And the Makefile is only one line:
```bash
build/root/Makefile
# There is no "tab" or "space" in front of the line above
```
Could someone tell me what is the problem? I am so eager to know what was wrong with me? Thank you very much!!!

**Comment by SupermanCj** [comment]
Hello, I also encountered the same problem. have you solved the problem?

**Comment by oxddr** [comment]
I wasn't able to reproduce it at HEAD. `KUBE_BUILD_PLATFORMS=linux/amd64  make kubemark GOFLAGS=-v GOGCFLAGS="-N -l"` worked just fine.

**Comment by tlereste** [comment]
I had the same problem.

Here is a workaround : 

Remove the Makefile and Makefile.generated_files files : 
`rm Makefile Makefile.generated_files`

Create the symlinks : 
`ln -s build/root/Makefile Makefile`
`ln -s build/root/Makefile.generated_files Makefile.generated_files`


This solution worked for me !

**Comment by samaiyayashraj** [comment]
Hi,
I'm having the same issue on my windows machine. Is there any workaround for this.?

**Comment by wwj-2017-1117** [comment]
I'm having the same issue on arm + cenos. Is there any workaround for this.?

**Comment by t-katsumura** [comment]
Just a workaround worked for me.
Add `include` to the line in kubernetes/Makefile like this

```Makefile
include build/root/Makefile
```
