### ISSUE TITLE
[Failing Test] ci-release-anago-stage (ci-release-anago-stage)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#88804]
**Which jobs are failing**:
`ci-release-anago-stage (ci-release-anago-stage)`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-releng-informing#ci-release-anago-stage

**Reason for failure**:
```console
 gcbmgr: BEGIN main on 61c75765-5e0e-11ea-8376-ea577b796c7a Wed Mar  4 11:52:17 UTC 2020
Checking required system packages: OK
fatal: no path specified; see 'git help pull' for valid url syntax
Checking /home/prow/go/src/k8s.io/release state: FAILED
/home/prow/go/src/k8s.io/release is not up to date.
$ git pull
Exiting... 
```

**Anything else we need to know**:
/priority important-soon
/milestone v1.18
/assign @justaugustus 
/sig release
/cc @kubernetes/ci-signal

**Comment by justaugustus** [comment]
Will be closed via https://github.com/kubernetes/test-infra/pull/16224.
