### ISSUE TITLE
Missing etcd_helper_* metrics >=1.16

### ISSUE THREAD

**Issue by angelbarrera92** [kubernetes/kubernetes#88803]
**What happened**:

kube-apiserver is not exposing etcd_helper_* metrics since Kubernetes version 1.16. 

**What you expected to happen**:

Two options:
1. Annotate the metric deprecation in the right CHANGELOG.md file.
2. Get working these metrics again.

**How to reproduce it (as minimally and precisely as possible)**:

Create a kind/kubeadm cluster 1.15 and 1.16, then query kube api-server static pod at `/metrics` endpoint.
Finally, grep for `etcd_helper_`. You should see results in 1.15, none in 1.16.

**Anything else we need to know?**:

It breaks some dashboard graphs in the kube-prometheus project:

Partial: https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/grafana-dashboardDefinitions.yaml
```
                          "targets": [
                              {
                                  "expr": "etcd_helper_cache_entry_total{job=\"apiserver\", instance=~\"$instance\", cluster=\"$cluster\"}",
                                  "format": "time_series",
                                  "intervalFactor": 2,
                                  "legendFormat": "{{instance}}",
                                  "refId": "A"
                              }
                          ],
```

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15 and 1.16
- Cloud provider or hardware configuration:
kind/kubeadm locally

**Comment by liggitt** [comment]
cc @logicalhan

**Comment by Jeffwan** [comment]
em. This should be included in release notes. It takes time to figure it out.
