### ISSUE TITLE
ensure server-side apply doesn't write to etcd if there are no changes

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#88816]
**What happened**:
On server-side apply, we should make sure not to write to etcd if there are no changes.

For example, in this change https://github.com/kubernetes/kubernetes/pull/88739, even though the applied object did not change, the timestamp for the field manager changed.

**What you expected to happen**:
We shouldn't update `.metadata.managedFields` if there is no change in any fields.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f deployment.yaml --server-side
sleep 1
kubectl apply -f deployment.yaml --server-side

# the second kubectl apply will update the field manager's timestamp and
# write to etcd even though the object didn't change
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17

/wg apply
/sig api-machinery
cc @apelisse @jennybuckley @kwiesmueller 

/assign @apelisse

**Comment by julianvmodesto** [comment]
One of the original integration tests for this: https://github.com/kubernetes/kubernetes/pull/81673

**Comment by EronWright** [comment]
Thanks for filing this issue, it appears to be the fix I need for the following issue.  My controller uses server-side apply against an object that it is watching, and it gets into an infinite loop because it doesn't calculate whether the patch would be non-trivial.

**Comment by apelisse** [comment]
Yes, that sounds like a side-effect of that bug. We might want to cherry-pick the fix to older release possibly. I'm not completely sure I understand why you would want to update the object anytime it changes though?

**Comment by EronWright** [comment]
The controller is simply trying to control certain fields of a certain owned object, and so it issues a patch to that object whenever the reconciliation loop runs.   The alternative is to use pre-SSA style logic involving a 3-way merge, which I'd hoped to avoid (as per [Using Server-Side Apply in a controller](https://kubernetes.io/docs/reference/using-api/api-concepts/#using-server-side-apply-in-a-controller)).

**Comment by apelisse** [comment]
Thanks for your answer, I agree that you shouldn't have to use a three-way merge. Would you mind giving more details about what fields you're trying based on what changes? It's hard to reason without an example.

**Comment by EronWright** [comment]
I don't mean to over-complicate, this is an ordinary situation involving an operator, a CRD, and a `Deployment`.   I simply wish to control the spec of the deployment.  If some other manager were to write an annotation onto that `Deployment`, I'd rather not overwrite it (as an `Update` would).

**Comment by EronWright** [comment]
@apelisse are you able to take steps to backport this fix?   Honestly I don't know how to use SSA in a controller without it.

**Comment by apelisse** [comment]
I'm planning on working on that, but I have a few other things on fire right now (so close to the 1.18 release). 

I still don't understand why a change to the object would require another change to the same object.

Also, I'm not sure I understand that: 
> If some other manager were to write an annotation onto that Deployment, I'd rather not overwrite it (as an Update would).

**Comment by EronWright** [comment]
@apelisse maybe there's a misunderstanding.   Imagine that I have a controller which manages a resource of type `Foo`, and implements it using a resource of type `Deployment`.   The controller has a watch established for `Foo` and for `Deployment`.  Whenever the reconciliation loop runs, the controller patches the deployment using SSA to enforce a certain spec (based on information from `Foo`).   An infinite loop occurs because the patch request on the deployment causes the watch to fire, which causes the controller to patch the deployment, which causes the watch to fire, and so on.   The workaround is to use some conditional logic to avoid issuing a trivial patch, but the logic needed to do that negates the value of SSA.

**Comment by apelisse** [comment]
Thanks, I think that's helpful. Let me see how I can cherry-pick this in previous versions.

**Comment by apelisse** [comment]
I've tried to cherry-pick this in 1.17, but it's not that easy. There are many changes that we would have to pull along with this. I don't think I'm going to cherry-pick this.

**Comment by EronWright** [comment]
Thanks @apelisse for the effort.
