### ISSUE TITLE
Does Kubernet's existing storage CSI plug-in meet my needs?

### ISSUE THREAD

**Issue by heidawei** [kubernetes/kubernetes#88836]
this is our needs for k8s.
1. Many of our applications want  volumes to have independent namespaces
2. In some cases, each pod wants to share a storage volume
3. There are also cases where each pod uses an exclusive volume to store logs
4. Some acquisition terminals have thousands of pods, hoping to use a more lightweight s3 interface to store data instead of mounting pvc. Then, we hope to mount the collected data to the analysis terminal for computing
5. Performance must be superior
6. Hope the storage plugin supports random write and sequential write
7. We need to store hundreds of millions of small files, each of which is a few KB

thanks!!!

/sig Storage

**Comment by mervinkid** [comment]
Hi @heidawei ,

JD.com which operates millions of container-scale K8s clusters is using [ChubaoFS](https://github.com/chubaofs/chubaofs) as the storage solution for its K8s clusters.

ChubaoFS is a distributed file system hosted by the [Cloud Native Computing Foundation](https://cncf.io) (CNCF) as a [sandbox](https://www.cncf.io/sandbox-projects/) project.
It is a fusion storage provides CSI plugin that you need and expose posix-compatible file system interface and amazon s3-compatible object storage interface at same time.
It makes possible for users to enjoy the benefits of Amazon FSx in them own Kubernetes cluster.
