### ISSUE TITLE
Create restricted podsecuritypolicy and use it with a service account in statefulset in specified ns 

### ISSUE THREAD

**Issue by Mishra-Akash** [kubernetes/kubernetes#88843]
**What happened**:

we want to start a pod with restricted permissions on the root filesystem, and to disable privilege pode. I am creating one state-ful set for my application and want to restrict that pod should not be started in privileged mode,  and root as read only.  I have created one service account and one role & role-binding with that sa in that namespace. (Not a cluster role)
Now when I am deploying state-ful set in privileged mode, its allowing me to deploy a pod.

**What you expected to happen**:
Since I am mapping SA to create state-ful set against a psp that doesn't allow to create a privileged pod , so if in stateful set ,pod should not de deployed if someone set privileged pod.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
PSP::
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-usr
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: roleaccess
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods","secrets"]
  verbs: ["get", "patch"]
- apiGroups:
  - policy
  resourceNames:
  - psp-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: testrolebinding
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: sa-usr
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: roleaccess
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-test
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: sname
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      serviceAccountName: sa-usr
      containers:
      - name: pod1
        image:  {{ .Values.image.pullPath }}
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        imagePullPolicy: {{ .Values.image.pullPolicy }}

...........
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
HP DL360
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"

- Kernel (e.g. `uname -a`):
Linux dl360x4669 4.12.14-23-default #1 SMP Tue May 29 21:04:44 UTC 2018 (cd0437b) x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
1. what PSP is the pod being admitted with? (`kubectl get pod/$name -o yaml` will show the effective $PSP_NAME as an annotation)

2. what permissions does the statefulset controller have?

```
kubectl auth can-i use podsecuritypolicies --all-namespaces --as=system:serviceaccount:kube-system:statefulset-controller

kubectl auth can-i use podsecuritypolicies/$PSP_NAME --all-namespaces --as=system:serviceaccount:kube-system:statefulset-controller
```

3. do you have your kube-controller-manager invocation handy? is it running against the TLS port? is it running with the `--use-service-account-credentials` flag set?

**Comment by Mishra-Akash** [comment]
Hi liggitt , pls find my reply- 

1- No PSP is showing in $PSP_NAME as an annotation in POD>

2- I am creating one service account that i will be using for my name space.
 
kubectl auth can-i use podsecuritypolicies --all-namespaces --as=system:serviceaccount:kube-system:statefulset-controller
no

kubectl auth can-i use podsecuritypolicies -n akash --as=system:serviceaccount:wrapping-w-usr
no

kubectl auth can-i use podsecuritypolicies/psp-restricted  --all-namespaces  --as=system:serviceaccount:kube-system:statefulset-controller
no

 kubectl auth can-i use podsecuritypolicies/psp-restricted -n akash --as=system:serviceaccount:wrapping-w-usr
no

3- Yes,  kube-controller-manager.yaml:    - --use-service-account-credentials=true

**Comment by liggitt** [comment]
> No PSP is showing in $PSP_NAME as an annotation in POD

do you have the PodSecurityPolicy admission plugin enabled? (`--enable-admission-plugins=PodSecurityPolicy,...` arg to kube-apiserver)

**Comment by Mishra-Akash** [comment]
yes. I have enabled that.

**Comment by liggitt** [comment]
If pods fetched from the API server do not have a `kubernetes.io/psp` annotation, then the admission plugin is not enabled

**Comment by Mishra-Akash** [comment]
I have updated /etc/kubernetes/manifests/kube-apiserver.yaml file with --enable-admission-plugins=PodSecurityPolicy. so this should work.

**Comment by Mishra-Akash** [comment]
Is there anything that I can check to verify the same?

**Comment by liggitt** [comment]
do you have the apiserver manifest handy? if the PodSecurityPolicy admission plugin is enabled, pods fetched from the API server will have a `kubernetes.io/psp` annotation
