### ISSUE TITLE
kubectl log does not support pods/foo format

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#8884]
kubectl create prints out the names of the created resources with the resource type as a prefix, like:
```
$ kubectl create -f myconfig.yaml
pods/mypod
pods/myotherpod
```

You can pass this prefixed name as an argument to `kubectl describe` but not to `kubectl log` (and presumably not to `kubectl exec`, though the latter not tested).

This would be nice for copy/paste with a default selection regex that includes slash as part of a word, and for scripts that chain the output of create to other commands.

**Comment by erictune** [comment]
Specifically, `kubectl log pods/mypod` does not work and I think it should.

**Comment by bgrant0607** [comment]
Related: #8448

**Comment by bgrant0607** [comment]
Related: https://github.com/openshift/origin/issues/5685

**Comment by bgrant0607** [comment]
cc @soltysh

**Comment by soltysh** [comment]
Sign me up, I'll try to find some time and fix it.

**Comment by kargakis** [comment]
kubectl log pods/mypod should work now

**Comment by soltysh** [comment]
Confirmed, @erictune you can close.

**Comment by erictune** [comment]
Thanks!
