### ISSUE TITLE
Make CSI test suite timeouts configurable

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#88848]
**What would you like to be added**:
[Current external CSI tests](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external) expect that pods can start in 5 minutes. This startup includes dynamic provisioning (if `WaitForFirstConsumer` is enabled), scheduling, volume attach and mount.  

The timeout is extended to 10 minutes for snapshot restore and cloning tests.
 
Both timeouts (and maybe others) are hardcoded in the code base now. They should be configurable.

**Why is this needed**:

This suite is to be used by 3rd party driver vendors to test their CSI drivers. Different storage drivers can be slower, especially when dynamically provisioning a volume.

cc @pohly @msau42 
/sig storage

**Comment by jsafrane** [comment]
As a simple solution, driver's manifest could have a field to specify timeout multiplier.

The hard part is to 1) find all the timeouts used by the suite and 2) pass any new timeout setting  through all the test layers up to the place where the timeout is needed, e.g. `WaitForPodRunningInNamespace`.

**Comment by wongma7** [comment]
yes, e.g. aws fsx takes 5 mins alone to provision a volume and ClaimProvisionTimeout https://github.com/kubernetes/kubernetes/blob/6b6336e5c094c60c35f2b7e6beb17abe9adbb4bd/test/e2e/framework/util.go#L135 is 5 minutes. 

Simple solution would be to put all the timeouts in a timeout package, change them from const to var, and let consumers set them before executing test.

**Comment by ZhiFeng1993** [comment]
@jsafrane  `SnapshotCreateTimeout` is 5 minutes. Am I wrong? You said it's 10 minutes. 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L134

**Comment by jsafrane** [comment]
Snapshot restore and Cloning test use `TestVolumeClientSlow`, which allows 15 minutes.

https://github.com/kubernetes/kubernetes/blob/0cdd5365a1d0c8ccad93bf5d12fbf54ec69deb0e/test/e2e/storage/testsuites/provisioning.go#L260

https://github.com/kubernetes/kubernetes/blob/b748c702d995dc4c26dfc1a12fb4beb5d8de91ae/test/e2e/framework/pod/wait.go#L64

**Comment by bertinatto** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/96042.
/close
