### ISSUE TITLE
CSI Volumes marked "Alpha", but utilized in beta features

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/kubernetes#88852]
**What happened**:

The godoc for `VolumeSource` in `core/v1` marks the `CSI` source type as alpha, but is utilized in beta features like CSI ephemeral volumes [1].

**What you expected to happen**:

Features that are marked beta should utilize APIs that are marked beta or GA.

**How to reproduce it (as minimally and precisely as possible)**:

Always - this is in the API reference [2].

**Anything else we need to know?**:

[1] https://kubernetes.io/docs/concepts/storage/volumes/#csi-ephemeral-volumes
[2] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#volume-v1-core

**Environment**:

N/A

**Comment by joshimoo** [comment]
This still seems to be the case, is it safe to assume that CSIVolumeSource should be marked as beta?

**Comment by liggitt** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#volume-v1-core shows the field as beta
