### ISSUE TITLE
[Flaky test] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#88861]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce

**Which test(s) are flaking**:
`[sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container`

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=Pod%20Container%20Status%20should%20never%20report%20success%20for%20a%20pending%20container

**Reason for failure**:

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=container%20unexpected%20exit%20code%20128

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88857/pull-kubernetes-e2e-gce/1235601663465623554/

Triage board shows flakes here spiked dramatically on 3/4

/sig node
/priority critical-urgent
/milestone v1.18

**Comment by derekwaynecarr** [comment]
@vpickard are you able to assist if this is related to recent topology work?

**Comment by vpickard** [comment]
@derekwaynecarr sure, I'll take a look

**Comment by liggitt** [comment]
@smarterclayton is this the test you just added in #88440?

**Comment by vpickard** [comment]
@derekwaynecarr As @liggitt mentioned above, this is a new test that was just added, and the test sometimes fails. I don't see that any of the recent topology manager changes would cause these failures. I'll be happy to help out and dig more if @liggitt or others think otherwise.

**Comment by smarterclayton** [comment]
This is me, the bugs are untriaged containerd / Kubelet failures with low occurrence rates that this test now exposes.

Investigating.

**Comment by liggitt** [comment]
still flaking in non-dockershim environments:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88906/pull-kubernetes-e2e-kind/1235957684612632581

> test/e2e/node/pods.go:213
> Mar  6 16:17:01.428: 1 errors:
pod pod-submit-status-0-14 on node kind-worker2 container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2020-03-06 16:16:54 +0000 UTC reason=StartError message=failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/1a82055a-819e-4840-8369-52eaf42e5c98/volumes/kubernetes.io~secret/default-token-nc5ln\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/f3204e1bbb06f378283a8971f201b22c3536b44f77c046200c2ef845f4e40b9b/rootfs\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/1a82055a-819e-4840-8369-52eaf42e5c98/volumes/kubernetes.io~secret/default-token-nc5ln: no such file or directory\\\"\"": unknown
test/e2e/node/pods.go:425

**Comment by smarterclayton** [comment]
Different reason this time.  Will continue to enumerate failure modes.
