### ISSUE TITLE
No pod restart after updating initContainer image

### ISSUE THREAD

**Issue by willise** [kubernetes/kubernetes#88886]
**What would you like to be added**:
Update docs about initContainer or fix kubelet to run as docs says.

**Why is this needed**:
As this(https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons) says:
```
A user updates the Pod specification, causing the init container image to change. Any changes to the init container image restarts the Pod. App container image changes only restart the app container.
```
If initContainer's image is updated, the pod will be restart. However, code shows that there is no logic to do this:
https://github.com/kubernetes/kubernetes/blob/edf460bc0f50822e3cb123457445aa63ae87cf10/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L477

So I want to know if it is a bug or just a doc error.

**Comment by liggitt** [comment]
cc @derekwaynecarr @smarterclayton for container lifecycle issues

**Comment by andylibrian** [comment]
I'm interested to look at this.

That statement has been in the documentation for a long time (2017):
https://github.com/kubernetes/website/commit/446606a43a18e963374d5309c9c4b23f7de3fe2c

```
A user updates the PodSpec causing the Init Container image to change. App Container image changes only restart the app Container.
```

and when I quickly look into `kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go` history, it seems that it has never been implemented.

Can I work on this once there is a direction whether we should fix the docs or implement it in the code?

**Comment by vnktram** [comment]
@willise Is this a doc update or a code-fix? Please clarify. I'm willing to take this up.

**Comment by Nit123** [comment]
\assign

**Comment by pacoxu** [comment]
After #96572 (1.20)， the behavior should be :

-  no pod restart after the init container was GCed
-  no pod restart after the init container image changed.

The reason is that kubelet will check `status of the main containers` before restarting init container.
/cc sjenning 
/sig node
