### ISSUE TITLE
add another arg for NodeResourcesFit plugin

### ISSUE THREAD

**Issue by angao** [kubernetes/kubernetes#88887]
**What would you like to be added**:
We want to add another arg for `NodeResourcesFit` plugin that is `ignoredResourcePrefixes`.

**Why is this needed**:
We know that Kubernetes support [custom extended resource](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#extended-resources) in container resources,  it is checked in the `NodeResourcesFit` plugin when the container is scheduled, and the custom extended resources can be set to ignore through `NodeResourcesFit` plugin arg `ignoredResources`, and that can be handled by custom scheduler framework plugin.
But in our scenario, the extended resource name is dynamic generation, such as `example.com/rc1`, `example.com/rc2`, where `rc1` and `rc2` are dynamic, we cannot use `ignoredResources` arg to ignore the resource since we don't know the next generate extended resource name, but they have the same prefix `example.com`. So we want to extend the `NodeResourcesFit` plugin arg by adding `ignoredResourcePrefixes`, it can be set a list of extended resource prefixes that `NodeResourcesFit` plugin should ignore.

related pr: https://github.com/kubernetes/kubernetes/pull/88842

**Comment by Huang-Wei** [comment]
Instead of providing existing args such as `ignoredResources`, or(and) as you suggested,  `ignoredResourcePrefixes `, maybe we can provide a field `resourceSelector` so as to be resilient to adapt to more general cases:

```go
type Fit struct {
    resourceSelector <define a new type here>
}
```

`resourceSelector` can describe sth. like "resName IN [...]", "resName NOT IN [...]", etc.

**Comment by angao** [comment]
It sounds good.

**Comment by angao** [comment]
maybe I can write a KEP for this

**Comment by Huang-Wei** [comment]
@angao A KEP may be overkill. We can just use this issue for brainstorming, get to a consensus, and get it implemented.

**Comment by angao** [comment]
A piece of my mind, the `Fit` is designed as follows: 

```go
type Fit struct {
	ResourceSelector ResourceSelector
}

type ResourceSelector struct {
	MatchExpressions []ResourceSelectorRequirement
}

type ResourceSelectorRequirement struct {
	Key      string
	Operator ResourceSelectorOperator
	Values   []string
}

type ResourceSelectorOperator string
const (
	ResourceSelectorOpIn           ResourceSelectorOperator = "In"
	ResourceSelectorOpNotIn        ResourceSelectorOperator = "NotIn"
)
```

`ResourceSelectorOpIn` describes the `Key` is a subset of one of `Values`, example: `Values` is `[]string{"example.com"}`, the `Key` could be either `example.com/rc` or `sub.example.com/rc`.

**Comment by alculquicondor** [comment]
Before we move into the new API details, I think we need to understand why this CAN NOT be accomplished with the existing API. Or if this is the right API that needs to be extended.

> But in our scenario, the extended resource name is dynamic generation

Why does it have to be dynamic? How are you scheduling against those requests instead?

Without knowing many details, an alternative I can think of is that the [device plugin APIs](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) or the [extended resources API](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/) could be changed instead.

**Comment by angao** [comment]
Yes, we know that the current device plugin API exposes less information, only deviceid, and the device is scheduled by Kubelet. 

Referring to [this proposal](https://github.com/vikaschoudhary16/community/blob/3cd8f87115b7a32dc8c2c5eeea09847657f73c50/keps/sig-node/00014-resource-api.md), we designed the device to be scheduled by the Scheduler. 

We use the `ExtendedResource` CRD to expose more device information, and the `ResourceClass` CRD to describe what kind of device the pod container requires, which is created by the user on demand. The usage of `ResourceClass` is as described in issue, such as `example.com/rc`, where `rc` is the name of the `ResourceClass`, and the scheduler selects the appropriate `ExtendedResource` (device) based on the `ResourceClass`. so we have the requirement that the `NodeResourcesFit` plugin can ignore such dynamic resources. 

In our design scenario, we modified the Kubelet and added a custom scheduler framework filter plugin, but the modification of the Kubelet was not friendly, and the scheduler was a small change that we hoped would be accepted upstream, or we could disable the `NodeResourcesFit` plugin and implement the change through a custom `NodeResourcesFit` plugin.

If you are interested, we can talk about it in detail on slack, and we also hope to contribute our solution to more people.

**Comment by angao** [comment]
@alculquicondor Yes, we know that the current device plugin API exposes less information, only deviceid, and the device is scheduled by Kubelet. 

Referring to [this proposal](https://github.com/vikaschoudhary16/community/blob/3cd8f87115b7a32dc8c2c5eeea09847657f73c50/keps/sig-node/00014-resource-api.md), we designed the device to be scheduled by the Scheduler. 

We use the `ExtendedResource` CRD to expose more device information, and the `ResourceClass` CRD to describe what kind of device the pod container requires, which is created by the user on demand. The usage of `ResourceClass` is as described in issue, such as `example.com/rc`, where `rc` is the name of the `ResourceClass`, and the scheduler selects the appropriate `ExtendedResource` (device) based on the `ResourceClass`. so we have the requirement that the `NodeResourcesFit` plugin can ignore such dynamic resources. 

In our design scenario, we modified the Kubelet and added a custom scheduler framework filter plugin, but the modification of the Kubelet was not friendly, and the scheduler was a small change that we hoped would be accepted upstream, or we could disable the `NodeResourcesFit` plugin and implement the change through a custom `NodeResourcesFit` plugin.

If you are interested, we can talk about it in detail on slack, and we also hope to contribute our solution to more people.

**Comment by alculquicondor** [comment]
cc @ahg-g

**Comment by Huang-Wei** [comment]
> or we could disable the NodeResourcesFit plugin and implement the change through a custom NodeResourcesFit plugin.

My 2 cents: in terms of a new req, basically we have 2 ways to hanlde it: (1) incorporate it in the upstream if it's a common requirement, easy to be implemented, not breaking existing semantics. Otherwise, (2) treat it as a special customer req, and hence as @angao mentioned, leave it for end-user to implement in their own plugin.

For this requirement, I'm slightly inclined to categorize it in the former case. Reasons as below:

- An extensive FitArgs API semantics fulfilling more cases, without breaking backward compatibility. It should be not that difficult to implement.
- If user chooses to implement a customized scheduler plugin, they don't need to disable the default nodesources plugin and duplicate the basic res fitting logic in their own plugin, and based on that, implement the customized fitting logic; instead, just implement the pure customized plugin, as it can co-exist with upstream noderesource plugin.
- If user chooses to implement the logic as a scheduler extender, the new FitArgs API is also backward compatible - mapping string set to res selector is fine. Or, we can optionally change [ExtenderManagedResource](https://github.com/kubernetes/kubernetes/blob/c649666b4addcb9cbef3ca5ca1d6d572e252f551/staging/src/k8s.io/kube-scheduler/config/v1/types.go#L226) to let it totally coherent with new FitArgs, and hence enjoy the extra benefits.

BTW: in terms of the API, we can tease apart `ResourceName` (the whole example.com/abc string) and `ResourceGroup` (the prefix of the qualified name, i.e., example.com).

**Comment by alculquicondor** [comment]
I'm still trying to understand why are devices being used in such a dynamic way. Users (aka Pod authors) creating devices doesn't seem correct. Maybe this use case can be re-thought as CRDs and controllers. But, maybe I'm must missing context.

However, adding support for "resource group" might not be a bad idea, considering that it would allow a vendor to implement a single plugin for all the devices they offer and make it easy to exclude them from the default resources plugin.

**Comment by ahg-g** [comment]
I think having a prefix or a "ResourceGroup" to exclude in the Fit plugin is reasonable ask. You could have a cluster where new nodes are joining with new GPU model, and you don't want to restart the scheduler to exclude those new models every time this happens.

**Comment by alculquicondor** [comment]
In that sense, I don't think we need something like https://github.com/kubernetes/kubernetes/issues/88887#issuecomment-595668889.
Something closer to the initial proposal was enough, but perhaps `IgnoredResourceGroups`.

**Comment by angao** [comment]
> You could have a cluster where new nodes are joining with new GPU model, and you don't want to restart the scheduler to exclude those new models every time this happens.

Yes,  it's also necessary to configure when the user create a new `ResourceClass`  as mentioned above not only the new GPU model is joined.

I think `IgnoredResourceGroups ` is a good idea, I will change the field `IgnoreResourcePrefixes` to `IgnoredResourceGroups` which describes a group of vendor devices.
