### ISSUE TITLE
StatefulSet does not update the Pod image

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#88896]
**What happened**:
StatefulSet does not reflect image change to the Pod.

**What you expected to happen**:
StatefulSet to reflect image change to the Pod.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply a StatefulSet with a wrong image - `.spec.template.spec.containers[0].image`.
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:foo
        ports:
        - containerPort: 80
          name: web
```

2. Ensure that the Pod fails to pull the image
```
$ k get po
NAME                             READY   STATUS             RESTARTS   AGE
web-0                            0/1     ImagePullBackOff   0          1m
```

3. Update the StatefulSet `.spec.template.spec.containers[0].image` to a valid image - `k8s.gcr.io/nginx-slim:0.8`

4. Ensure that the StatefulSet does not update the Pod and the Pod still tries to pull the old image
```
$ k get po
NAME                             READY   STATUS             RESTARTS   AGE
web-0                            0/1     ImagePullBackOff   0          19m

$ k get po web-0 -o jsonpath='{.spec.containers[0].image}'
k8s.gcr.io/nginx-slim:foo

$ k get sts web -o jsonpath='{.spec.template.spec.containers[0].image}'
k8s.gcr.io/nginx-slim:0.8
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by silenceper** [comment]
same issue

**Comment by janetkuo** [comment]
This behavior is documented here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback:

> When using Rolling Updates with the default Pod Management Policy (`OrderedReady`), it's possible to get into a broken state that requires manual intervention to repair.
> ... you must also delete any Pods that StatefulSet had already attempted to run with the bad configuration. StatefulSet will then begin to recreate the Pods using the reverted template.

**Comment by ialidzhikov** [comment]
> This behavior is documented here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback:
> 
> > When using Rolling Updates with the default Pod Management Policy (`OrderedReady`), it's possible to get into a broken state that requires manual intervention to repair.
> > ... you must also delete any Pods that StatefulSet had already attempted to run with the bad configuration. StatefulSet will then begin to recreate the Pods using the reverted template.

Ah, I now see https://github.com/kubernetes/kubernetes/issues/67250. Closing this issue as duplicate of https://github.com/kubernetes/kubernetes/issues/67250.
