### ISSUE TITLE
package unstructured does not provide GetGroupVersionResource()

### ISSUE THREAD

**Issue by Avni-Sharma** [kubernetes/kubernetes#88908]
On going through https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured I found at that there is no support for GetGroupVersionResource.

It would be good if we have something like 

```			GroupVersionResource: v1.GroupVersionResource{
				Group:         obj.GroupVersionResource().Group,
				Version:       obj.GroupVersionResource().Version,
				Resource:    obj.GroupVersionGetResource().Resource,
			},
```
where obj is unstructured.Unstructured

**Comment by liggitt** [comment]
An individual API object contains its own apiVersion and kind. That is accessible from an unstructured object via `GroupVersionKind()`.

To determine a group/version/resource from a group/version/kind, you also need discovery information from the server.

```go
gvk := unstructuredObject.GroupVersionKind()
discoveryClient := clientset.Discovery()
mapper := restmapper.NewDeferredDiscoveryRESTMapper(discoveryClient)
mapping, err := mapper.RESTMapping(gvk.GroupKind(), gvk.Version)
if err != nil {
  // handle not being able to determine a resource
}
// group/version/resource is available as mapping.Resource
// scope (namespaced or cluster-scoped) is available as mapping.Scope (Name() will either be RESTScopeNameNamespace or RESTScopeNameRoot)
```

Note that the code above will re-fetch discovery info every time you run it. You can wrap the discovery client in a NewMemCacheClient or NewCachedDiscoveryClientForConfig to cache results in memory or on disk.
