### ISSUE TITLE
Visitors of Configmaps and Secrets should specify which containers to visit

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#88909]
Fully described in https://github.com/kubernetes/kubernetes/pull/87865#discussion_r384736714, `VisitPodSecretNames` and `VisitPodConfigmapNames` will visit these fields for all containers, regardless of whether they're hidden behind a feature gate (e.g. `EphemeralContainers`).

This is usually correct, these methods are often used to drop fields and in this case should visit all containers that are persisted regardless of whether they're disabled, but the callers of these methods should signal that explicitly rather than relying on the implicit behavior.

/cc @liggitt, @tedyu 
/priority important-longterm
/kind bug
/sig node

**Comment by verb** [comment]
@tedyu are you interested in taking this one, too?

**Comment by tedyu** [comment]
VisitPodSecretNames and VisitPodConfigmapNames already specify AllContainers for VisitContainers

Can you let me know what else needs to be done?

**Comment by verb** [comment]
@tedyu Callers should specify whether they want to visit all containers or not. There are valid reasons for each, so we shouldn't assume the desired behavior, even if 100% of the current users want to visit all containers.  Jordan's original comment in https://github.com/kubernetes/kubernetes/pull/87865#discussion_r384736714 has some examples of current uses.

I don't think this needs to be as configurable as `VisitContainers`, so my naive first attempt to implement this would probably just be a new `allContainers bool` added to `VisitPodSecretNames` and `VisitPodConfigmapNames`
