### ISSUE TITLE
About Startup Probes

### ISSUE THREAD

**Issue by surekhakallam** [kubernetes/kubernetes#88912]
we are using kubernetes 1.17  and implemented Startup Probes ... And reduced the failure Threshold of readiness and liveness probes ...  after that the pods are going to crashed state ... is it the expected behaviour?

we saw that the startup probe is useful during the slow start of the containers..
we thought that the startup probe will takeover first and then the liveness probe and readiness probe will take over but in our case we see that after the time given in the readiness probe gets over but the container have not come up then the pod is restarting again ... due to which we came to the conclusion that readiness probe is running first .. is this expected or any other step to be added..

**Comment by Jukka-A** [comment]
I'm also seeing this with 1.17 version. I have set feature-gates to kube-apiserver and kubelet in order to enable startup probe.

This command shows that startup probe is there.
`kubectl get pod podname -o yaml`

Seems like startup probe does nothing...

**Comment by Waitfish** [comment]
yes,the startupProbe not for me too.

my kubelet version is:
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chenkaiyue** [comment]
@Waitfish have you opened StartupProbe feature-gates?

**Comment by chenkaiyue** [comment]
@surekhakallam you mean  readiness probe ran before liveness probe or just Startup probe doesn't work?

**Comment by Waitfish** [comment]
> @Waitfish have you opened StartupProbe feature-gates?
Thanks!
I find this url now.
https://kubernetes.io/zh/docs/reference/command-line-tools-reference/feature-gates/
 
So it need to open StartupProbe feature-gates if use StartupProbe

**Comment by surekhakallam** [comment]
> @surekhakallam you mean readiness probe ran before liveness probe or just Startup probe doesn't work first? and
> 
> > after the time given in the readiness probe
> 
> what this time is ? InitialDelaySeconds?

yes readiness probe  ran in the first place its 10
sorry for late reply

**Comment by surekhakallam** [comment]
> @Waitfish have you opened StartupProbe feature-gates?

yes its done

**Comment by surekhakallam** [comment]
> @surekhakallam you mean readiness probe ran before liveness probe or just Startup probe doesn't work first? and
> 
> > after the time given in the readiness probe
> 
> what this time is ? InitialDelaySeconds?

**Comment by stevengibbszions** [comment]
I also have this issue on k8s v1.17.  Feature gate is enabled, but startup probe does not appear in the yaml and does not execute.  Do we need to do anything else besides open the feature gate?

**Comment by dhananjaya-senanayake** [comment]
I also have this issue on k8s v1.16 (AKS).  Startup probe does not appear in the yaml.

**Comment by stevengibbszions** [comment]
> I also have this issue on k8s v1.17. Feature gate is enabled, but startup probe does not appear in the yaml and does not execute. Do we need to do anything else besides open the feature gate?

I was able to get Startup Probes working on Rancher K8s v1.17.2 by adding the feature gate args to BOTH the kubelet AND the kube-api.

**Comment by chirangaalwis** [comment]
> I also have this issue on k8s v1.16 (AKS). Startup probe does not appear in the yaml.
> [Update]
> AKS only supports GA features. The startup probe feature is still in alpha stage for Kubernetes v1.16. We can find detailed information at: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe.

@dhananjaya-senanayake seems like this is not enabled by default in AKS clusters of Kubernetes server version `1.17.x` as it is a Kubernetes alpha feature in the particular version range. Please refer to https://github.com/Azure/AKS/issues/1550.
