### ISSUE TITLE
Add swagger docs for kube-scheduler APIs

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#88919]
/sig scheduling
/sig docs
/wg component-standard
/kind feature

kube-scheduler has 2 APIs that can be used to configure it at start up:

- [kubescheduler.config.k8s.io/v1.Policy](https://github.com/kubernetes/kubernetes/blob/c649666b4addcb9cbef3ca5ca1d6d572e252f551/staging/src/k8s.io/kube-scheduler/config/v1/register.go#L39)
- [kubescheduler.config.k8s.io/v1alpha2.KubeSchedulerConfiguration](https://github.com/kubernetes/kubernetes/blob/11c4bcd9dd5658b8befe5eaf807b22f5f5ec7ac2/staging/src/k8s.io/kube-scheduler/config/v1alpha2/register.go#L40)

These APIs don't have generated swagger docs in the [kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/). However, this kind of makes sense because the above APIs are not meant to be sent to the api server.

Can we start generating the necessary files? Where should they live? Can we still do it in 1.18?

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei @zacharysarah @mtaufen

**Comment by alculquicondor** [comment]
I did an experiment to generate some docs in #88927. But I'm not sure if that's all its needed.

**Comment by alculquicondor** [comment]
cc @tengqm @kbhawkey

**Comment by kbhawkey** [comment]
Hello @alculquicondor,
Can the `kube-scheduler` generate an Open API spec?

Have you looked at the API server and how the spec is generated?

If you don't have a spec, have you thought about using a tool such as,
https://github.com/ahmetb/gen-crd-api-reference-docs?
The docs generated are quite readable and this may be a quick way of producing a first reference.

**Comment by alculquicondor** [comment]
I haven't checked this yet, but it sounds like we would need quite some work. I'll leave it for 1.19.

**Comment by alculquicondor** [comment]
https://github.com/ahmetb/gen-crd-api-reference-docs worked. However, I need to feed a proper template to the tool. Any suggestions?

**Comment by alculquicondor** [comment]
cc @SataQiu @gavinfish since you seemed interested in #89701

**Comment by alculquicondor** [comment]
The pending process is described in https://github.com/kubernetes-sigs/reference-docs/issues/138#issuecomment-605467979
and there is sample code in kubernetes-sigs/reference-docs#143

**Comment by alculquicondor** [comment]
@angao I see you sent kubernetes-sigs/reference-docs#156

We need the script, not just the instructions. But we need the consensus of sig docs as described here https://github.com/kubernetes-sigs/reference-docs/issues/138#issuecomment-605467979

Did you do that?

**Comment by alculquicondor** [comment]
/help

We should handle this in 1.20
