### ISSUE TITLE
Pods not starting on Windows nodes

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#88913]
**What happened**:

Pods will not start on Windows nodes, even though nodes are ready and pods are scheduled to nodes.

Kubelet logs are filled with this:

```
E0306 18:20:36.813221    3564 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 206 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x38ac960, 0x6b90c30)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xaa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x38ac960, 0x6b90c30)
	/usr/local/go/src/runtime/panic.go:679 +0x1c0
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).canAdmitPod(0xc000640a80, 0x0, 0x0, 0x0, 0xc00102d400, 0x0, 0x0, 0x6a62da3, 0xa, 0x774)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1794 +0x15d
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc000640a80, 0xc000d5e1a8, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2071 +0x312
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000640a80, 0xc000680ae0, 0x48cc5c0, 0xc000640a80, 0xc000816ea0, 0xc000816f00, 0xc0009f1800, 0xc0002f0601)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1913 +0x561
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000640a80, 0xc000680ae0, 0x48cc5c0, 0xc000640a80)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1856 +0x378
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000640a80, 0xc000680ae0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1452 +0x26e
k8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1133 +0x43
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000b352a0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x65
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000b352a0, 0x4824e60, 0xc000b39cb0, 0xc0000bf601, 0xc0000800c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xaa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b352a0, 0x0, 0x0, 0x1, 0xc0000800c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe9
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000b352a0, 0x0, 0xc0000800c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x54
created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Build K8s from master, create any pod on Windows node.

**Anything else we need to know?**:

I strongly believe this commit is responsible: https://github.com/kubernetes/kubernetes/commit/ac32644d6e712af0747f39a945c8df29d6a9cfc4 

What happened is that now, with the commit mentioned above, a nil podAdmitHandler is registered, that when called will result in a panic.

More specifically here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L871

For Windows, `GetAllocateResourcesPodAdmitHandler` returns `nil`:

https://github.com/kubernetes/kubernetes/blob/1afb554222605d4d67a911c9bbb0fa5b1049c2dc/pkg/kubelet/cm/container_manager_windows.go#L181

**Environment**:

All K8s built from master. This affects all sig-windows master tests.

**Comment by droslean** [comment]
/reopen 

Is this resolved? The jobs still failing because of this. ref https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master

@adelina-t Can you check?

**Comment by adelina-t** [comment]
@droslean The issue is fixed, you can look here: https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging . I don't know what's happening with gce tests, but all other windows tests ( based on aks ) are working. 

PS: Maybe I should add aks job to master release informing as well :)

**Comment by adelina-t** [comment]
Since this affected the Kubelet starting, I think we can safely close this issue based on just aks test results.

**Comment by droslean** [comment]
Thanks, @adelina-t
/close

**Comment by marosset** [comment]
Thanks @adelina-t!

**Comment by marosset** [comment]
@yliaog can you take a look at the Windows GCE test passes?

It looks like they are still unhealthy and there are a few issues being tracked by the release team
#88974 and #88659

**Comment by yliaog** [comment]
https://github.com/kubernetes-sigs/windows-testing/pull/145#issuecomment-599642648
