### ISSUE TITLE
jsonpath wildcard and filter support is not working with objects

### ISSUE THREAD

**Issue by skaegi** [kubernetes/kubernetes#88928]
JSONPath wildcard and filter support works correctly for arrays but does not work for objects.

When I use an expression like ...
```
kubectl get pod my-pod -o=jsonpath={.metadata.labels[*]}
```
I get the error ...
```
Error executing template: map[string]interface {} is not array or slice.
```

Similarly when I use a filter expression like...
```
kubectl get pod my-pod -o=jsonpath={.metadata.labels[?(@='tekton')]}
```
I get something like...
```
Error executing template: map[app.kubernetes.io/managed-by:tekton-pipelines tekton.dev/pipeline:output-pipeline tekton.dev/pipelineRun:output-pipeline-run tekton.dev/pipelineTask:then-check tekton.dev/task:check-stuff-file-exists tekton.dev/taskRun:output-pipeline-run-then-check-kn44p] is not array or slice and cannot be filtered.
```

---

These are both legal jsonpath expressions where the "*" wild-card should be treated like matching all key fields of the map, and the filter expression should be run against each map value. For a bit more info see https://goessner.net/articles/JsonPath/index.html#e2  wildcard description.

**Comment by tedyu** [comment]
The 'filter expression' command is the same as the first one.

Can you show the actual command ?

**Comment by skaegi** [comment]
whoops ... copy and paste error ... updated with an actual filter expression

**Comment by brianpursley** [comment]
@skaegi I was taking a look at the code for this a little today and have some questions.

---

First, can you show what you expect `kubectl get pod my-pod -o=jsonpath={.metadata.labels[*]}` to return?

I have a pod with label `run=nginx` and `foo=bar` and this works for me:
```
$ kubectl get pod nginx -o=jsonpath={.metadata.labels.*}
bar nginx
```

---

Second, I looked at [the link you posted](https://goessner.net/articles/JsonPath/index.html#e2) and it seems like the `?(@<expr>)` filter only applies to filtering items in an array, so it would be some different sort of capability to make that work for filtering keys/values in an object.  It seems like what you are saying in your second example is you want to find all labels that have a value of "tekton".  Is that correct?

I wonder if you might be better off using something a little more powerful like [go templates](https://golang.org/pkg/text/template/) for this.

I realize it is more complex, but you could do something like this to get only the labels matching a certain value:
(I have the same pod above with labels `run=nginx` and `foo=bar`)
```
kubectl get pod nginx -o=template='{{range $k, $v := .metadata.labels}}{{with eq $v "bar"}}{{printf "%s: %s\n" $k $v}}{{end}}{{end}}'
```
Output:
```
foo: bar
```

**Comment by Harkishen-Singh** [comment]
@brianpursley I think the output should be similar to what a normal jsonpath should behave.

Like:

```
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2020-04-09T10:55:29Z",
        "name": "termination-demo",
        "namespace": "default",
        "resourceVersion": "335080",
        "selfLink": "/api/v1/namespaces/default/pods/termination-demo",
        "uid": "1f879342-95c7-4631-b119-7d5fc9866e19"
    }
}

```

will have `{$.metadata[*]}` as 
```
[
   "2020-04-09T10:55:29Z",
   "termination-demo",
   "default",
   "335080",
   "/api/v1/namespaces/default/pods/termination-demo",
   "1f879342-95c7-4631-b119-7d5fc9866e19"
]
```

**I am looking into this issue since a couple of days and will love to fix it.**

**Comment by mmiklavc** [comment]
Not sure if this is shell dependent or not, but in zsh and bash I had to do the following escaping:
```
-o=jsonpath="{.data['*']}"
-o=jsonpath="{.data['some_rules\.yml']}"
```

**Data was:**
```
{
    "apiVersion": "v1",
    "data": {
        "some_rules.yml": "groups:\n- long nested yaml"
        "more_rules.yml": "groups:\n- long nested yaml"
    },
...
    "metadata": {
        "creationTimestamp": "...",
        "labels": {
            "app": "someapp",
            "chart": "some-chart-1.2.3",
            "component": "server",
            "heritage": "Tiller",
            "release": "myrelease"
        },
...
}
```

**Types:**
```
map[some_rules.yml:groups:
more_rules.yml:groups:
]
```

Any wildcard match without the single quotes gave me the same error as in the OP.
