### ISSUE TITLE
Getting Pod Name

### ISSUE THREAD

**Issue by pranay123111** [kubernetes/kubernetes#88922]
**What would you like to be added**:
How can i get the pod name (in my code) where my service is running

**Why is this needed**:
In our current project we are running 100 pods i just want to have a monitor on logs, if we know which pod it is running. i can create a dashboard which gives information total requests it ran on each pod
/sig Apps

**Comment by sudaxl** [comment]
Not sure if I understand your requirement fully. I think you can use some kubectl log commands and filter the pods that you are interested in using labels, names, deployment name etc..

**Comment by onesolpark** [comment]
If you follow the `kubectl logs deployment/name` logic
1. Get deployment and get selector
2. Select pods using selector label (i.e app=nginx)
3. Get logs from pods selected from step 2.

If you know the label I think you can go straight to step 2 and 3
