### ISSUE TITLE
certificatesigningrequest.certificates.k8s.io wrong output upon certificate deny

### ISSUE THREAD

**Issue by deepakcpakhale06** [kubernetes/kubernetes#88937]
**What happened**:
Denied a CSR using `kubectl certificate deny`. Got the wrong/misleading output

**What you expected to happen**:
Expected api to return correct output.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create `CertificateSigningRequest` object.

```
cat <<EOF | kubectl apply -f -
> apiVersion: certificates.k8s.io/v1beta1
> kind: CertificateSigningRequest
> metadata:
>   name: test
> spec:
>   request: $(cat test.csr | base64 | tr -d '\n')
>   usages:
>   - digital signature
>   - key encipherment
>   - server auth
> EOF

```
2. Deny the request

```
kubectl certificate deny test
```
You will get following output 

```
certificatesigningrequest.certificates.k8s.io/test approved
```
**Anything else we need to know?**:

**Environment**: Test
- Kubernetes version (use `kubectl version`):

```
kubectl version --short
Client Version: v1.16.0
Server Version: v1.16.0

```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by deepakcpakhale06** [comment]
sig usability

**Comment by liggitt** [comment]
This was resolved in https://github.com/kubernetes/kubernetes/pull/84400/files
