### ISSUE TITLE
kubectl get nodes command giving The connection to the server <ip>:6443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by kuldeepsingh99** [kubernetes/kubernetes#88938]
I have deployed kubernetes cluster on AWS EC2 Ubuntu Nodes, one master node and one worker node. Its a free tier t2.micro machine with 1 CPU.

I installed and configured everything and on day 1 everything works fine. kubectl get nodes command was responding without any delay and i was able to create MYSQL deployment.

Next day when i tried kubectl get nodes i was getting **The connection to the server :6443 was refused - did you specify the right host or port?** and even sometimes i am getting **Unable to connect to the server: net/http: TLS handshake timeout**

I checked the following things to verify whether kubernetes is working or not ```sudo systemctl status kubelet``` it was in active status

Even its surprising that sometime``` kubectl get nodes``` works perfectly and sometime it return **The connection to the server :6443 was refused - did you specify the right host or port?**

I am using kubeadm to create cluster

running the ```journalctl -xeu kubelet```

> Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:56.877636   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://172.31.46.140:6443/api/v1/services?limit=500&resourceV
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:56.878004   14821 reflector.go:153] object-"kube-system"/"coredns": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fieldS
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:56.878875   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://172.31.46.140:6443/api/v1/nodes?fieldSelector=metadata.na
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:56.879884   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-token-xm2vf": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespace
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:56.959021   14821 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://172.31.46.140:6443/apis/storage.k8s.io/v1beta1/csi
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:56.959202   14821 reflector.go:153] object-"kube-system"/"calico-kube-controllers-token-xf5dq": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:57.530172   14821 reflector.go:153] object-"kube-system"/"kube-proxy-token-86f8d": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secre
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:57.530995   14821 reflector.go:153] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fie
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:57.533867   14821 event.go:272] Unable to write event: 'Patch https://172.31.46.140:6443/api/v1/namespaces/default/events/ip-172-31-46-140.15f9ece1a5ee7c89: write tcp 172.31.46
Mar 07 05:03:57 ip-172-31-46-140 kubelet[14821]: E0307 05:03:57.616329   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-certs": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.027403   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://172.31.46.140:6443/api/v1/pods?fieldSelector=spec.
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.434287   14821 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "ip-172-31-46-140": Get https://172.31.46.140:6443/api/v1/nodes/ip-172-
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.637944   14821 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "ip-172-31-46-140": Get https://172.31.46.140:6443/api/v1/nodes/ip-172-
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.638565   14821 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "ip-172-31-46-140": Get https://172.31.46.140:6443/api/v1/nodes/ip-172-
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.638832   14821 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "ip-172-31-46-140": Get https://172.31.46.140:6443/api/v1/nodes/ip-172-
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.639078   14821 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "ip-172-31-46-140": Get https://172.31.46.140:6443/api/v1/nodes/ip-172-
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.639303   14821 kubelet_node_status.go:389] Unable to update node status: update node status exceeds retry count
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.719128   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://172.31.46.140:6443/api/v1/nodes?fieldSelector=metadata.na
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.719316   14821 reflector.go:153] object-"kube-system"/"coredns-token-kxp6r": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secrets?
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.719420   14821 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://172.31.46.140:6443/apis/node.k8s.io/v1beta1/run
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.719540   14821 reflector.go:153] object-"kube-system"/"calico-config": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?
Mar 07 05:03:58 ip-172-31-46-140 kubelet[14821]: E0307 05:03:58.720515   14821 reflector.go:153] object-"kube-system"/"calico-node-token-chq4r": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secr
Mar 07 05:03:59 ip-172-31-46-140 kubelet[14821]: E0307 05:03:59.007662   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://172.31.46.140:6443/api/v1/services?limit=500&resourceV
Mar 07 05:03:59 ip-172-31-46-140 kubelet[14821]: W0307 05:03:59.336457   14821 status_manager.go:530] Failed to get status for pod "coredns-6955765f44-7s5mp_kube-system(53025fd9-be3f-4990-bfb8-9854a0054f52)": Get https://172.31.46.140:64
Mar 07 05:03:59 ip-172-31-46-140 kubelet[14821]: E0307 05:03:59.337703   14821 reflector.go:153] object-"kube-system"/"coredns": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fieldS
Mar 07 05:03:59 ip-172-31-46-140 kubelet[14821]: W0307 05:03:59.417871   14821 status_manager.go:530] Failed to get status for pod "dashboard-metrics-scraper-76585494d8-fbrrp_kubernetes-dashboard(7a568368-f6bc-4c41-b384-d9a6d57f89a7)": G
Mar 07 05:03:59 ip-172-31-46-140 kubelet[14821]: E0307 05:03:59.786693   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-token-xm2vf": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespace
Mar 07 05:03:59 ip-172-31-46-140 kubelet[14821]: W0307 05:03:59.867347   14821 status_manager.go:530] Failed to get status for pod "kube-apiserver-ip-172-31-46-140_kube-system(9cf756fe9ee0f87c9d8c8477701b0f92)": Get https://172.31.46.140
Mar 07 05:04:00 ip-172-31-46-140 kubelet[14821]: E0307 05:04:00.115393   14821 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://172.31.46.140:6443/apis/storage.k8s.io/v1beta1/csi
Mar 07 05:04:00 ip-172-31-46-140 kubelet[14821]: E0307 05:04:00.277208   14821 reflector.go:153] object-"kube-system"/"calico-kube-controllers-token-xf5dq": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube
Mar 07 05:04:00 ip-172-31-46-140 kubelet[14821]: E0307 05:04:00.605092   14821 reflector.go:153] object-"kube-system"/"kube-proxy-token-86f8d": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secre
Mar 07 05:04:00 ip-172-31-46-140 kubelet[14821]: E0307 05:04:00.686180   14821 reflector.go:153] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fie
Mar 07 05:04:00 ip-172-31-46-140 kubelet[14821]: W0307 05:04:00.848212   14821 status_manager.go:530] Failed to get status for pod "kube-controller-manager-ip-172-31-46-140_kube-system(7a1889f29b3b0e6aaa446cb6ed6e7fb9)": Get https://172.
Mar 07 05:04:01 ip-172-31-46-140 kubelet[14821]: E0307 05:04:01.014728   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-certs": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube
Mar 07 05:04:01 ip-172-31-46-140 kubelet[14821]: E0307 05:04:01.545804   14821 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://172.31.46.140:6443/apis/node.k8s.io/v1beta1/run
Mar 07 05:04:01 ip-172-31-46-140 kubelet[14821]: E0307 05:04:01.712139   14821 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: Get https://172.31.46.140:6443/apis/coordination.k8s.io/v1/namespaces/kube-nod
Mar 07 05:04:01 ip-172-31-46-140 kubelet[14821]: E0307 05:04:01.712231   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://172.31.46.140:6443/api/v1/pods?fieldSelector=spec.
Mar 07 05:04:01 ip-172-31-46-140 kubelet[14821]: E0307 05:04:01.713020   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://172.31.46.140:6443/api/v1/nodes?fieldSelector=metadata.na
Mar 07 05:04:01 ip-172-31-46-140 kubelet[14821]: E0307 05:04:01.874423   14821 reflector.go:153] object-"kube-system"/"coredns-token-kxp6r": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secrets?
Mar 07 05:04:02 ip-172-31-46-140 kubelet[14821]: E0307 05:04:02.118776   14821 reflector.go:153] object-"kube-system"/"calico-config": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?
Mar 07 05:04:02 ip-172-31-46-140 kubelet[14821]: E0307 05:04:02.243460   14821 reflector.go:153] object-"kube-system"/"calico-node-token-chq4r": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secr
Mar 07 05:04:02 ip-172-31-46-140 kubelet[14821]: E0307 05:04:02.408560   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://172.31.46.140:6443/api/v1/services?limit=500&resourceV
Mar 07 05:04:02 ip-172-31-46-140 kubelet[14821]: E0307 05:04:02.612028   14821 reflector.go:153] object-"kube-system"/"coredns": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fieldS
Mar 07 05:04:02 ip-172-31-46-140 kubelet[14821]: W0307 05:04:02.814516   14821 status_manager.go:530] Failed to get status for pod "kube-proxy-plz27_kube-system(8fd48d90-fbd6-402b-ac01-ee9786c43316)": Get https://172.31.46.140:6443/api/v
Mar 07 05:04:03 ip-172-31-46-140 kubelet[14821]: E0307 05:04:03.062535   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-token-xm2vf": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespace
Mar 07 05:04:03 ip-172-31-46-140 kubelet[14821]: E0307 05:04:03.224606   14821 reflector.go:153] object-"kube-system"/"calico-kube-controllers-token-xf5dq": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube
Mar 07 05:04:03 ip-172-31-46-140 kubelet[14821]: E0307 05:04:03.426514   14821 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://172.31.46.140:6443/apis/storage.k8s.io/v1beta1/csi
Mar 07 05:04:03 ip-172-31-46-140 kubelet[14821]: E0307 05:04:03.633332   14821 reflector.go:153] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fie
Mar 07 05:04:03 ip-172-31-46-140 kubelet[14821]: E0307 05:04:03.840351   14821 reflector.go:153] object-"kube-system"/"kube-proxy-token-86f8d": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secre
Mar 07 05:04:04 ip-172-31-46-140 kubelet[14821]: E0307 05:04:04.043128   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-certs": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube
Mar 07 05:04:04 ip-172-31-46-140 kubelet[14821]: E0307 05:04:04.208620   14821 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://172.31.46.140:6443/apis/node.k8s.io/v1beta1/run
Mar 07 05:04:04 ip-172-31-46-140 kubelet[14821]: W0307 05:04:04.411819   14821 status_manager.go:530] Failed to get status for pod "coredns-6955765f44-9q75k_kube-system(ad2289c2-327f-4c0f-8b5c-187e3574ad01)": Get https://172.31.46.140:64
Mar 07 05:04:04 ip-172-31-46-140 kubelet[14821]: E0307 05:04:04.614515   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://172.31.46.140:6443/api/v1/pods?fieldSelector=spec.
Mar 07 05:04:04 ip-172-31-46-140 kubelet[14821]: W0307 05:04:04.780807   14821 iptables.go:520] Could not check for iptables canary mangle/KUBE-KUBELET-CANARY: exit status 4
Mar 07 05:04:04 ip-172-31-46-140 kubelet[14821]: E0307 05:04:04.821342   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://172.31.46.140:6443/api/v1/nodes?fieldSelector=metadata.na
Mar 07 05:04:05 ip-172-31-46-140 kubelet[14821]: E0307 05:04:05.065933   14821 reflector.go:153] object-"kube-system"/"coredns-token-kxp6r": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secrets?
Mar 07 05:04:05 ip-172-31-46-140 kubelet[14821]: E0307 05:04:05.231528   14821 reflector.go:153] object-"kube-system"/"calico-config": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?
Mar 07 05:04:05 ip-172-31-46-140 kubelet[14821]: E0307 05:04:05.435764   14821 reflector.go:153] object-"kube-system"/"calico-node-token-chq4r": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/secr
Mar 07 05:04:05 ip-172-31-46-140 kubelet[14821]: E0307 05:04:05.723822   14821 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get https://172.31.46.140:6443/api/v1/services?limit=500&resourceV
Mar 07 05:04:05 ip-172-31-46-140 kubelet[14821]: E0307 05:04:05.843097   14821 reflector.go:153] object-"kube-system"/"coredns": Failed to list *v1.ConfigMap: Get https://172.31.46.140:6443/api/v1/namespaces/kube-system/configmaps?fieldS
Mar 07 05:04:06 ip-172-31-46-140 kubelet[14821]: E0307 05:04:06.009712   14821 reflector.go:153] object-"kubernetes-dashboard"/"kubernetes-dashboard-token-xm2vf": Failed to list *v1.Secret: Get https://172.31.46.140:6443/api/v1/namespace

/sig api-machinery

/area apiserver

**Comment by liggitt** [comment]
That indicates the API server is not running successfully. What is in the apiserver log file?

**Comment by lavalamp** [comment]
/assign @liggitt 

(6443 is probably not the port to use off-system?)

**Comment by liggitt** [comment]
Closing due to lack of information. If you are able to get the API server log output, that would help understanding why the server is sometimes unavailable
