### ISSUE TITLE
k8s 1.15.5 cpumanager/kubelet changed the cpu_sets of containers in Guaranteed Qos Pods

### ISSUE THREAD

**Issue by saurabhanetskope** [kubernetes/kubernetes#88939]
**What happened**:
CpuManager, Kubelet changed the cpu_sets, core_ids of the containers running in Pods with Guaranteed Qos Class. These containers are using integer number of cpus. 'kubectl describe pod' does show that pod is in Guaranteed Qos Class.

**What you expected to happen**:
cpu_sets or the core-ids to remain the same throughout the lifetime of the container. Is it expected to is it just a bug? We didn't see it k8s 1.13 but only in k8s 1.15.5

**How to reproduce it (as minimally and precisely as possible)**:
Run multiple pods with multiple containers on the same worker node which ask for integer cpu requests.

**Anything else we need to know?**:
Is it expected to is it just a bug? We didn't see it k8s 1.13 but only in k8s 1.15.5
**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.5
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by saurabhanetskope** [comment]
i don't see the above issue on k8s 1.17.0 version either. Can somebody confirm that some issue like this existed and got fixed in 1.17.0 release. I do see a lot of changes that went in reconcileState() inside CpuManager in release 1.17.0

**Comment by saurabhanetskope** [comment]
I checked and saw container has not restarted. cpu_sets for the guaranteed container-id changed after initial assignment. I have the kubelet logs to show that is indeed the case. I am attaching the log file. Please look for this container id 82b9c23702a30bcbe946379d0ae256954a42bccfec43cbe27dbf5e7a94aa334d

[kubelet_cpu_sets.log](https://github.com/kubernetes/kubernetes/files/4307718/kubelet_cpu_sets.log)

**Comment by Maxpain177** [comment]
The same problem
