### ISSUE TITLE
CRD: Free-Form Object (openAPIV3Schema)

### ISSUE THREAD

**Issue by angelbarrera92** [kubernetes/kubernetes#88944]
**What happened**:

My CRD definition with a [`Free-Form Object`](https://swagger.io/docs/specification/data-models/data-types/) attribute does not work as expected.

Having the following CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
            spec:
              type: object
              required: [email]
              properties:
                email:
                  description: User's email to access Grafana
                  type: string
  names:
    kind: User
    plural: users
    singular: user
    shortNames:
      - users
      - user
```

With a CR:
```yaml
apiVersion: grafana.k8spin.cloud/v1
kind: User
metadata:
  name: tenant-1
  namespace: grafana
spec:
  email: user@tenant-1.com
```

My controller can do the business, but when it tries to patch the `status` field:

```
[2020-03-07 19:42:55,345] kopf.objects         [DEBUG   ] [grafana/tenant-1] Patching with: {'status': {'create_user': {'id': 11, 'message': 'User created'}}, 'metadata': {'annotations': {'kopf.zalando.org/last-handled-configuration': '{"spec": {"email": "user@tenant-1.com"}}'}}}
```

It just create an empty json:

```bash
$ kubectl get user -o yaml tenant-1
apiVersion: grafana.k8spin.cloud/v1
kind: User
metadata:
  annotations:
    kopf.zalando.org/last-handled-configuration: '{"spec": {"email": "user@tenant-1.com"}}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"grafana.k8spin.cloud/v1","kind":"User","metadata":{"annotations":{},"name":"tenant-1","namespace":"grafana"},"spec":{"email":"user@tenant-1.com"}}
  creationTimestamp: "2020-03-07T19:41:33Z"
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  generation: 2
  name: tenant-1
  namespace: grafana
  resourceVersion: "12577"
  selfLink: /apis/grafana.k8spin.cloud/v1/namespaces/grafana/users/tenant-1
  uid: 9af897a6-b3d6-4d7c-a626-c08a251d1c01
spec:
  email: user@tenant-1.com
status: {}
```

**What you expected to happen**:

As the output says the `status` attribute should contains:

> {'status': {'create_user': {'id': 11, 'message': 'User created'}}

```yaml
status:
  create_user:
    id: 11
    message: User created
```

Actual behavior:

```yaml
status: {}
```

**How to reproduce it (as minimally and precisely as possible)**:

Create a CRD with an attribute type `object` (which means *Free-Form Object* in OpenApi Docs) and implement a simple controller/operator that adds "random" object on it.

**Anything else we need to know?**:

**Environment**: Kind local
- Kubernetes version (use `kubectl version`): 1.16.4
- Cloud provider or hardware configuration: None

**Comment by angelbarrera92** [comment]
Do i need to add: `x-kubernetes-preserve-unknown-fields: true` in the status field?

**Comment by liggitt** [comment]
Yes. By default, only defined attributes are preserved in CRD v1 schemas.

**Comment by liggitt** [comment]
See https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields for details
