### ISSUE TITLE
unable to fetch pod metrics for pod default/mypod: no metrics known for pod

### ISSUE THREAD

**Issue by Adhders** [kubernetes/kubernetes#88957]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/remove kind-bug
/triage needs-information

please feel the issue template from the `.github` folder correctly.

**Comment by catchups** [comment]
Please fill out the correct template for your question.
