### ISSUE TITLE
Server Side Apply patch type only mentions yaml

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/kubernetes#88975]
Currently the content type for using ssa is `application/apply-patch+yaml`, while ssa explicitly accepts both yaml and json.
This can be confusing for users.

Our current plan to approach is this is:

- [x]  Clarify the documentation (@kwiesmueller)
- [x] ~~Add a new content type that is clearer~~

/sig api-machinery
/wg apply
/cc @apelisse 
/assign @jennybuckley

**Comment by apelisse** [comment]
New content-type is probably not needed for 1.18, while the documentation improvement probably is.

Also, I don't think we need to frame it as "ssa explicitly accepts both yaml and json." since that's not accurate. YAML is a superset of Json so sending json to the yaml endpoint is fine.

**Comment by liggitt** [comment]
I agree we should not fragment versions by adding a new content-type only supported by some servers. More clearly documenting what the current content-type allows is a good idea.

**Comment by lavalamp** [comment]
I vote for fixing this with documentation?

**Comment by apelisse** [comment]
> I vote for fixing this with documentation?

I think we all agree here. I've already read that fix somewhere

**Comment by kwiesmueller** [comment]
Closed by https://github.com/kubernetes/website/pull/19286
/close
