### ISSUE TITLE
Server-side Apply: Ownership not tracked for sub-resources

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/kubernetes#88981]
This issue tracking the sub-resource tracking issue in server-side apply, reported in:

- https://github.com/kubernetes/kubernetes/issues/88901
- https://github.com/kubernetes/kubernetes/issues/82046

/sig api-machinery
/wg apply
/assign @apelisse

**Comment by cmhokej** [comment]
Ok

**Comment by pacoxu** [comment]
- #89232 fixed #88901 in 1.19
- #98377 fixed #82046 in 1.22

It seems that we can close this issue now.
@apelisse @kwiesmueller

**Comment by kwiesmueller** [comment]
I agree, thanks for reminding :-)
/close
