### ISSUE TITLE
kube-proxy logs show errors， however  the stautus of pod is RUNNING

### ISSUE THREAD

**Issue by Adhders** [kubernetes/kubernetes#88999]
Here is the error message of kube-proxy :

E0303 07:46:14.241529       1 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Service: Get https://192.168.205.60:6443/api/v1/services?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=1850691&timeout=5m14s&timeoutSeconds=314&watch=true: dial tcp 192.168.205.60:6443: connect: connection refused
E0303 07:46:15.241361       1 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Endpoints: Get https://192.168.205.60:6443/api/v1/endpoints?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=1868413&timeout=9m50s&timeoutSeconds=590&watch=true: dial tcp 192.168.205.60:6443: connect: connection refused
E0303 07:46:15.242170       1 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Service: Get https://192.168.205.60:6443/api/v1/services?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=1850691&timeout=9m13s&timeoutSeconds=553&watch=true: dial tcp 192.168.205.60:6443: connect: connection refused
E0303 07:46:20.358047       1 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Service: unknown (get services)
E0303 07:46:20.358536       1 reflector.go:307] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Endpoints: unknown (get endpoints)

Here is the description of pod ：

Name:                 kube-proxy-vsdt2
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 tensorflow-ts700-e8-rs8-v2/192.168.205.60
Start Time:           Sat, 22 Feb 2020 18:10:14 +0800
Labels:               controller-revision-hash=76fd4f5cc8
                      k8s-app=kube-proxy
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   192.168.205.60
IPs:
  IP:           192.168.205.60
Controlled By:  DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  docker://d4ca342c76a8b932f472b634921c3f1eabdb20227e5d4dc50a2477f8833da1a7
    Image:         registry.aliyuncs.com/google_containers/kube-proxy:v1.17.3
    Image ID:      docker-pullable://registry.aliyuncs.com/google_containers/kube-proxy@sha256:8dfd672298f8fbcd37731e0f2e45be87199cee6ee1f482ffec766693dcec0ec4
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    State:          Running
      Started:      Sun, 01 Mar 2020 19:33:24 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sun, 01 Mar 2020 10:51:14 +0800
      Finished:     Sun, 01 Mar 2020 19:33:05 +0800
    Ready:          True
    Restart Count:  7
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-proxy-token-rmqb9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  kube-proxy-token-rmqb9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-proxy-token-rmqb9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>

**Comment by matias-devoto** [comment]
Im having the same problem what was it?

**Comment by hugohyliang** [comment]
I used Kubeadm to install a Kubernetes 1.81 cluster and I encountered the same problem

**Comment by matias-devoto** [comment]
i tried changing the cidr of the pods on my init because it was colapsing with other net
