### ISSUE TITLE
kube-controller-manager creates continuously pods in OutOfcpu state

### ISSUE THREAD

**Issue by Ottovsky** [kubernetes/kubernetes#89007]
**What happened**:
When user creates a deployment (or replicaset) with nodeName specified in the PodTemplateSpec and resources limit for cpu higher than the node cpu count, the kube controller manager keeps on creating pods in OutOfcpu state.

**What you expected to happen**:
Create a single pod in  `OutOfcpu` status

**How to reproduce it (as minimally and precisely as possible)**:
1.    Ensure namespace does not have ResourceQuota, or its cpu value is set to the value higher than the maximum number of cpus in the node.
1.    Apply deployment resource with pod template spec which contains nodeName with node from the cluster and cpu resource limit set to value higher than cpu count on that node
1.    Observe as kube-controller-manager keeps on creating more and more pods in OutOfcpu state.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVers
ion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVers
ion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`minikube v1.7.3 on Fedora 31`
- OS (e.g: `cat /etc/os-release`):
```
NAME=Buildroot
VERSION=2019.02.9
ID=buildroot
VERSION_ID=2019.02.9
PRETTY_NAME="Buildroot 2019.02.9"
```
- Kernel (e.g. `uname -a`):
`Linux minikube 4.19.94 #1 SMP Thu Feb 20 00:37:50 PST 2020 x86_64 GNU/Linux`
- Install tools:
`minikube start`
- Network plugin and version (if this is a network-related bug):
- Others:
Example of yaml to cause the mentioned behaviour in the minikube:
[busybox-dos-minikube.txt](https://github.com/kubernetes/kubernetes/files/4313525/busybox-dos-minikube.txt)

**Comment by smarterclayton** [comment]
related to #89068

**Comment by chenqiangzhishen** [comment]
same as OutOfMemory case which will continuously create pods if specified nodeName in Deployment with the specified node doesn't have more memory provided.

**Comment by Ottovsky** [comment]
Seems to be related to https://github.com/kubernetes/kubernetes/issues/72593

**Comment by marcinma** [comment]
same happens on v1.25.5

**Comment by liggitt** [comment]
The pod is not out of cpu when created, but are marked as out of cpu by the node, right? By directly assigning the nodeName in the pod spec, this is skipping all scheduling / back-pressure mechanisms that would keep pods pending until there was capacity for them.

**Comment by liggitt** [comment]
/remove-kind bug

Instead of using `nodeName`, use a node selector or node affinity rule to target the desired node, but route pod assignment through the scheduler, which will consider whether the targeted node has sufficient resources to run the pod. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/ for more details on node selector and node affinity.

/close

**Comment by marcinma** [comment]
> The pod is not out of cpu when created, but are marked as out of cpu by the node, right? By directly assigning the nodeName in the pod spec, this is skipping all scheduling / back-pressure mechanisms that would keep pods pending until there was capacity for them.

The bug isn't about back-pressure mechanisms but rather infinite number of pods being created in such scenario. When nodeName is provided only one pod should be pending in OutOfCpu state. Also the pod may be out of cpu when created right away by providing cpu requests bigger than resoruces on node. I don't get why you are closing this bug, it should be either fixed or some other way of informing that nodeName may cause infinite number of pods creation should be provided (which impacts getting information about pods at all)

**Comment by asafdl** [comment]
happened to me now, was very confused until I found this post, would love to understand why and how k8s just implodes with pod creations on a single deployment

**Comment by Ottovsky** [comment]
@asafdl I did a talk on this bug some time ago at Warsaw Kubernetes Meetup: [here](https://www.youtube.com/watch?v=eNei0dzLtk4&t=307s&ab_channel=CloudNativeWarsaw) , where I deep dive into root cause and present practical mititgations. 

I agree the closure of the issue seems to be premature, since the real issue is the continuous creation of the pods, which under certain condition may bring down the control plane. This behavior can be triggered in a multiple ways, vide: https://github.com/kubernetes/kubernetes/issues/72593
