### ISSUE TITLE
Documentation about empty affinity topologyKey

### ISSUE THREAD

**Issue by dmage** [kubernetes/kubernetes#89000]
Documentations for topologyKey at [kubernetes.io/docs/.../assign-pod-node/](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity) says:

> For `preferredDuringSchedulingIgnoredDuringExecution` pod anti-affinity, empty `topologyKey` is interpreted as “all topologies”

The [API documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podaffinityterm-v1-core) says:

> topologyKey string | ... Empty topologyKey is not allowed.

One of these documents needs to be updated.

**Comment by zhouya0** [comment]
The doc in https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity is not right. 

I send a PR to `k/website`. https://github.com/kubernetes/website/pull/19587
