### ISSUE TITLE
kubectl cordon returns wrong error code if you don't have permissions

### ISSUE THREAD

**Issue by baens** [kubernetes/kubernetes#89008]
**What happened**:
An error code equal to 0 is returned when `kubectl cordon` is run with a user that doesn't have permissions

```
$ kubectl cordon gke-base-main-pool-4381f9fb-722d                                                                                                    
error: unable to cordon node "gke-base-main-pool-4381f9fb-722d": nodes "gke-base-main-pool-4381f9fb-722d" is forbidden: User "elindblom" cannot patch resource "nodes" in API group "" at the cluster scope: Required "container.nodes.update" permission.
$ echo $?
0
```

**What you expected to happen**:
The return code should not equal 0 when an error is produced

**How to reproduce it (as minimally and precisely as possible)**:
* Create a GKE cluster
* Only grant your user viewer permissions
* Run cordon

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE

**Comment by baens** [comment]
I _think_ this would fix the issue, but not quite sure if this is the right approach to this: https://github.com/kubernetes/kubernetes/compare/master...baens:tickets/GH-89008/return-error-of-cordon

**Comment by ChiefyG-Admin** [comment]
Please review fejta bots ability to stay current in the past and future.. the bot has become abusive with repeat after repeat within seconds.... thanks tho fejta the human...

**Comment by ChiefyG-Admin** [comment]
I like your solution.  Another thought is to adjust the code to replace any value other than "0" with "0"  while retaining a list that will be omitted from the replacement case.  List is for obvious reasons as instances will occur where access should be denied.  Maybe opens up security risk though now that I think it through..  is there some permission sequences that could be of use here? Or permeation of my thoughts?

**Comment by ChiefyG-Admin** [comment]
Remove-lifecycle stale

**Comment by baens** [comment]
I love the idea that you could go through early on and check if you even have permissions. That would makes sense instead of trying and just letting the error let you know what went wrong. However, I don't know the API well enough to even know if that is possible.... Any pointers on where to look?
