### ISSUE TITLE
NewDocumentDecoder fails with bufio.Scanner: token too long

### ISSUE THREAD

**Issue by kensipe** [kubernetes/kubernetes#89016]
**What happened**:

When calling `NewDocumentDecoder` the token size for the buffer is the default which is NOT changable. Larger documents (which is likely when using a yaml separator) causes a `bufio.Scanner: token too long`

This was uncovered using kudo... the issue is https://github.com/kudobuilder/kudo/issues/1397

**What you expected to happen**:

1. size limitation should be documented if they exist
2. token size should be calling code managed

**How to reproduce it (as minimally and precisely as possible)**:

Call `NewDocumentDecoder` with a doc larger than token size

**Anything else we need to know?**:

The fixing PR https://github.com/kudobuilder/kudo/pull/1400 provides more detail if needed.

Code concern is: https://github.com/kubernetes/apimachinery/blob/release-1.6/pkg/util/yaml/decoder.go#L94

duplicate of https://github.com/kubernetes/apimachinery/issues/89 which I will now close

**Environment**:
- Kubernetes version (use `kubectl version`):  1.17
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lavalamp** [comment]
OK so the request here is that we call `.Buffer()` on the scanner to permit larger documents?

I think 5MB is a good max size? (Since YAML is more verbose than proto, where the (IIRC) 1.5MB limit is enforced.)

**Comment by lavalamp** [comment]
Adding labels-- this is a good one for new contributors.

**Comment by bitscuit** [comment]
Could I pick this up as a first issue?

**Comment by praseodym** [comment]
/assign 0xMH
because of open PR
