### ISSUE TITLE
Kubernetes Authentication At Application Level

### ISSUE THREAD

**Issue by chandra210893** [kubernetes/kubernetes#89028]
Is there a way to implement kubernetes authentication at application level. I would like to know is there a way to implement something like Google-Login in kubernetes which should be able to authenticate application users via kubernetes plugins or api calls. I am aware of ABAC, RBAC and Node level authentication, but they doesn't seems to be serving our purpose. Can anyone suggest me a way to achieve this is kubernetes. Thank you !!

**Comment by liggitt** [comment]
Thanks for reaching out, but an issue is not the best approach for a general question like this. For this topic, I would recommend asking sig-auth [via the mailing list or slack](https://github.com/kubernetes/community/tree/master/sig-auth#contact).

/close

**Comment by CzarMich** [comment]
Hey, I am having the same question. The possibility of implementing ABAC for Different users with different permissions  determined at application layer. In this case, different users on different Pods which have different applications with users who have different roles and tasks. E.g Having different sections of a view. .

Could there be a general discussion on this?
