### ISSUE TITLE
Process remained in container after Kubectl exec being killed

### ISSUE THREAD

**Issue by samsam2310** [kubernetes/kubernetes#89031]
**What happened**:
I executed a bash by this command:
```
kubectl exec -it POD_NAME bash
```
After killing the kubectl process, bash is remained in the container.

**What you expected to happen**:
After killing the kubectl process, bash should also terminated

**How to reproduce it (as minimally and precisely as possible)**:
1. Created a pod.
2. Executed a bash by kubectl exec.
3. Kill kubectl.
4. Execute `top` in container, the previous bash is in S state.

**Anything else we need to know?**:
I also checked if this is a tty problem.
I ssh into a server and executed `kubectl exec`, killed ssh (close the ssh connection). The same problem occured (bash is remained in the container).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): Linux 3.10.0-1062.9.1.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ChanderG** [comment]
This tripped me up yesterday. This is the same "feature" as in docker - https://github.com/moby/moby/issues/9098.

If we are not going to fix this, can we at least have a clear warning in the help string? I am personally willing to open a PR if it will be accepted.
