### ISSUE TITLE
RESTMapper Pluralization Logic Is Too Limited

### ISSUE THREAD

**Issue by irishshagua** [kubernetes/kubernetes#89034]
**What happened**:
Pluralization logic in the client generator in api/machinery is too simplistic. For an example CRD `FabricGateway` the pluralised generated client is `FabricGatewaies` whereas the actual is `FabricGateways`.

**What you expected to happen**:
To be able to specify the plural name for the client generation if guessed pluralisation is throwing a wobbly.

**Anything else we need to know?**:
Problem seems to be [here](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/restmapper.go#L141)

This was duplicated from this issue:
https://github.com/kubernetes/apimachinery/issues/77

**Comment by liggitt** [comment]
does the --plural-exceptions option to client/informer/lister generation do what you want?
