### ISSUE TITLE
Env variables are shared between pods on the same namespace

### ISSUE THREAD

**Issue by bloudman** [kubernetes/kubernetes#89033]
**What happened**:
When I use `env` command inside a container of a certain namespace I get all env variables concerning IP address and services of all containers in this namespace.
**What you expected to happen**:
`env` command should return only variables of my pod.
**How to reproduce it (as minimally and precisely as possible)**:
Run two pods inside a same namespace with both differents env variables, use `env` command on a container of the first pod you will see env variables of the other
**Anything else we need to know?**:
If it is not a bug I did not find anything in the documentation about this behaviour so maybe it is a lack of documenation. 
**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): GKE 
- Kernel (e.g. `uname -a`): GKE
- Install tools: Helm with tiller
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
This is working as designed. See https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service for details:

> When a Pod runs on a Node, the kubelet adds a set of environment variables for each active Service.

It also indicates how to opt out of this behavior if you don't want it:

> Note: If the service environment variables are not desired (because possible clashing with expected program ones, too many variables to process, only using DNS, etc) you can disable this mode by setting the enableServiceLinks flag to false on the pod spec.
