### ISSUE TITLE
Adding an already deleted node port to service shows already acquired error

### ISSUE THREAD

**Issue by hudannag** [kubernetes/kubernetes#89042]
**THIS IS THE THIRD TIME FOR CREATING THIS ISSUE!
The two previous ones:
https://github.com/kubernetes/kubernetes/issues/73140
https://github.com/kubernetes/kubernetes/issues/32987**

**What happened**:
I created a service for my microservice in helm. It is a NodePort type. I specified the nodePort, but after I deleted the whole app, including the service itself and re-deployed it, this particular service failed to start becuase the reason: _kubectl failed exit status 1: The Service "rabbitmq-amqp-service" is invalid: spec.ports[0].nodePort: Invalid value: 30672: provided port is already allocated_

**What you expected to happen**:
In the earlier issues it's mentioned that it only costs some time before the service can re-claim the required port. But it causes DOWNTIME. It's unacceptable in HA environments.
Please fix this issue, so that the port becomes free **inmediately** after the service is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service and specify the nodePort too. Delete the service with kubectl and then re-create it.

**Anything else we need to know?**:
I think there's a high demand for a solution or **at least an official workaround.**

**Environment**:
- Kubernetes version: v1.15.10
- Cloud provider or hardware configuration: On premise
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): Linux <server_name> 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liggitt** [comment]
I think this is a duplicate of #85894

**Comment by liggitt** [comment]
Thanks for the detailed report. Closing as a duplicate in favor of https://github.com/kubernetes/kubernetes/issues/85894
