### ISSUE TITLE
failed to create containerd task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo 

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#89064]
**Which jobs are flaking**:
* pull-kubernetes-e2e-kind
* pull-kubernetes-e2e-kind-ipv6

**Which test(s) are flaking**:

* [sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support non-existent path
* [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (default fs)] subPath should support non-existent path

**Testgrid link**:

* https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=subPath&width=5&sort-by-failures=
* https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind-ipv6&include-filter-by-regex=subPath&width=5&sort-by-failures=

**Reason for failure**:

> failed to create containerd task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo "/run/containerd/io.containerd.grpc.v1.cri/containers/286e8796a52f39a425ecf241d7602600bedc4893a6af6ed7d0c90143b604aef1/io/248318440/286e8796a52f39a425ecf241d7602600bedc4893a6af6ed7d0c90143b604aef1-stdout" failed: context deadline exceeded

> expected pod "pod-subpath-test-inlinevolume-l55j" success: pod "pod-subpath-test-inlinevolume-l55j" failed with status: {Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-28 21:39:26 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-28 21:39:17 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [test-container-subpath-inlinevolume-l55j test-container-volume-inlinevolume-l55j]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-28 21:39:17 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [test-container-subpath-inlinevolume-l55j test-container-volume-inlinevolume-l55j]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-28 21:39:17 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:fc00:db8:1::242:ac11:4 PodIP:fd00:10:244:0:1::33 PodIPs:[{IP:fd00:10:244:0:1::33}] StartTime:2020-02-28 21:39:17 +0000 UTC InitContainerStatuses:[{Name:test-init-subpath-inlinevolume-l55j State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2020-02-28 21:39:24 +0000 UTC,FinishedAt:2020-02-28 21:39:24 +0000 UTC,ContainerID:containerd://a8efd3fa9eb2b51ecf5ba678419bee9361fedc767c4015f0db8024b8d5f5834d,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:gcr.io/kubernetes-e2e-test-images/mounttest:1.0 ImageID:gcr.io/kubernetes-e2e-test-images/mounttest@sha256:c0bd6f0755f42af09a68c9a47fb993136588a76b3200ec305796b60d629d85d2 ContainerID:containerd://a8efd3fa9eb2b51ecf5ba678419bee9361fedc767c4015f0db8024b8d5f5834d Started:<nil>}] ContainerStatuses:[{Name:test-container-subpath-inlinevolume-l55j State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2020-02-28 21:39:27 +0000 UTC,FinishedAt:2020-02-28 21:39:27 +0000 UTC,ContainerID:containerd://52caac15eeb9daf11e8d3850c2b123fe79de510e8c1630f99f81d287bf358148,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:gcr.io/kubernetes-e2e-test-images/mounttest:1.0 ImageID:gcr.io/kubernetes-e2e-test-images/mounttest@sha256:c0bd6f0755f42af09a68c9a47fb993136588a76b3200ec305796b60d629d85d2 ContainerID:containerd://52caac15eeb9daf11e8d3850c2b123fe79de510e8c1630f99f81d287bf358148 Started:0xc0007c2ce9} {Name:test-container-volume-inlinevolume-l55j State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:StartError,Message:failed to create containerd task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo "/run/containerd/io.containerd.grpc.v1.cri/containers/286e8796a52f39a425ecf241d7602600bedc4893a6af6ed7d0c90143b604aef1/io/248318440/286e8796a52f39a425ecf241d7602600bedc4893a6af6ed7d0c90143b604aef1-stdout" failed: context deadline exceeded,StartedAt:1970-01-01 00:00:00 +0000 UTC,FinishedAt:2020-02-28 21:40:02 +0000 UTC,ContainerID:containerd://286e8796a52f39a425ecf241d7602600bedc4893a6af6ed7d0c90143b604aef1,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:gcr.io/kubernetes-e2e-test-images/mounttest:1.0 ImageID:gcr.io/kubernetes-e2e-test-images/mounttest@sha256:c0bd6f0755f42af09a68c9a47fb993136588a76b3200ec305796b60d629d85d2 ContainerID:containerd://286e8796a52f39a425ecf241d7602600bedc4893a6af6ed7d0c90143b604aef1 Started:0xc0007c2cea}] QOSClass:BestEffort EphemeralContainerStatuses:[]}

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=unable%20to%20copy%20pipes

This seems likely to be an actual containerd bug that is just exposed in these tests in the kind jobs. Tracked in https://github.com/containerd/containerd/issues/4068

Note that this existed [prior to the runc-rc10 bump as well](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-01-25&ci=0&pr=1&text=unable%20to%20copy%20pipes)

/sig node
/kind bug

**Comment by BenTheElder** [comment]
cc

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91617/pull-kubernetes-e2e-kind/1267635291242369029

**Comment by BenTheElder** [comment]
happens sometimes on GCE / containerd too https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=failed%20to%20create%20containerd%20task#a845b734d2e03c6333ce
