### ISSUE TITLE
IntStr GetValueFromIntOrPercent assumes all strings are percentages

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes/kubernetes#89082]
**What happened**:

Using [GetValueFromIntOrPercent](https://github.com/kubernetes/apimachinery/blob/c76d55892ea23f279bd999f01f951e78434b6095/pkg/util/intstr/intstr.go#L154-L170) from the `intstr` package in `k8s.io/apimachinery/pkg/util/intstr`, I found there's a difference in behaviour between `{"foo": 1}` and `{"foo": "1"}`, but there is no difference in behaviour between `{"foo": "1"}` and `{"foo": "1%"}`

When unmarshalling from JSON, {"foo": "1"} results in the intstr being of type String, this causes the [getIntOrPercentValue](https://github.com/kubernetes/apimachinery/blob/c76d55892ea23f279bd999f01f951e78434b6095/pkg/util/intstr/intstr.go#L176-L183) method to assume that it is a percentage when it is not. So a value of `"1"` becomes identical in behaviour to a value of `"1%"`.

**What you expected to happen**:

A value of `1` and `"1"` should cause the same behaviour.
The code should check for the existence of a `%` in the string before determining it is a percentage

**How to reproduce it (as minimally and precisely as possible)**:

```
package main

import (
	"fmt"
	"k8s.io/apimachinery/pkg/util/intstr"
)

func main() {
	oneString := intstr.FromString("1")
	val, err := intstr.GetValueFromIntOrPercent(&oneString, 10, false)
	if err != nil {
		panic(err)
	}
	fmt.Printf("(String) Expecting %d to equal 1\n", val)
	
	oneInt := intstr.FromInt(1)
	val, err = intstr.GetValueFromIntOrPercent(&oneInt, 10, false)
	if err != nil {
		panic(err)
	}
	fmt.Printf("(Int) Expecting %d to equal 1\n", val)
}
```

Outputs:

```
(String) Expecting 0 to equal 1
(Int) Expecting 1 to equal 1
```

https://play.golang.org/p/MR3M4UdWYph

**Anything else we need to know?**:

This was raised in [slack](https://kubernetes.slack.com/archives/C0EG7JC6T/p1583949884224600), @liggitt responded and noted that at first glance, where this is used in tree, the types have [validation](https://github.com/kubernetes/kubernetes/blob/c369cf187ea765c0a2387f2b39abe6ed18c8e6a8/pkg/apis/apps/validation/validation.go#L384-L399) to check string values are valid percents before being accepted and that if we want to fix this, a proper sweep of current in-tree uses should be checked to make sure that updating the behaviour wouldn't break any current uses

@liggitt Also suggested it might be worth checking out of tree uses as well to be good citizens and linked to https://grep.app/search?q=.GetValueFromIntOrPercent%28 for helping with this

/assign

**Comment by renatoviana12** [comment]
Can I pick this up?

**Comment by JoelSpeed** [comment]
If you have the time, yes please!

**Comment by renatoviana12** [comment]
Deleted the comment by accident, would love to tackle it :)

**Comment by renatoviana12** [comment]
Hey @JoelSpeed should I put you as a reviewer?

**Comment by JoelSpeed** [comment]
CC me and I'll take a look

**Comment by jrroman** [comment]
@JoelSpeed I have submitted a PR at #90573 to address this issue. PTAL, thank you!

**Comment by JoelSpeed** [comment]
@jrroman Apologies, this is already being tackled in #89482 which is currently under review and @renatoviana12 has been actively responding to, I think it's close to getting LGTM now

**Comment by jrroman** [comment]
@JoelSpeed Sorry about that I didnt realize, I have closed my PR accordingly. Thank you!

**Comment by JoelSpeed** [comment]
Still a problem
/remove-lifecycle rotten
