### ISSUE TITLE
CPUManager feature: processes inside the containers should get the exact list of CPUs allocated

### ISSUE THREAD

**Issue by kvp-cs** [kubernetes/kubernetes#89087]
**With CPU Manager feature enabled, if a POD/Container is launched, there should be a to identify which CPU IDs have been assigned to that container so that processes inside the container can use pthread_setaffinity() calls**:

**pthreads of my app (running inside the container) to be able to call pthread_setaffinity() system call.**:

**Comment by kvp-cs** [comment]
To explain with an example, 
With CPUManager feature enabled, launch a single-container-POD, my container got CPUIds {4,5,6,7} assigned to it. I found this from "cat /var/lib/kubelet/cpu_manager_state" on the respective node in the cluster. But how can I get this information from inside the container - I want the pthreads of my app (running inside the container) to be able to call pthread_setaffinity() system call.

**Comment by vpickard** [comment]
You should be able to look at the cpuset as shown below to figure out the CPUs allocated.

[root@nfvsdn-20 ~]# kubectl exec testpod1 -- cat /sys/fs/cgroup/cpuset/cpuset.cpus
2,4,6,8,10,14,16,18,20,22

**Comment by kvp-cs** [comment]
Thank You Victor, this information would help me know the Allowed-CPUSet before starting the application threads and hence I can pin the threads to specific CPU (from this set). 

However it would be great if some command like kubectl get pods/node/cluster-info could show the same info - some centralized place where I can see which CPUs of a node are busy and which are free. 

> You should be able to look at the cpuset as shown below to figure out the CPUs allocated.
> 
> [root@nfvsdn-20 ~]# kubectl exec testpod1 -- cat /sys/fs/cgroup/cpuset/cpuset.cpus
> 2,4,6,8,10,14,16,18,20,22
