### ISSUE TITLE
Massive managedFields in yaml file

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#89080]
After upgrating to k8s 1.18.0. 
The feature `Server-side-apply` is enabled by default, as this PR brings:https://github.com/kubernetes/kubernetes/pull/72947
The yaml file from `kubectl get -o yaml` has massive strange `managedFields` which is really strange:
```
managedFields:
- apiVersion: v1
  fieldsType: FieldsV1
  fieldsV1:
    f:status:
      f:conditions:
        k:{"type":"ContainersReady"}:
          f:lastTransitionTime: {}
          f:status: {}
        k:{"type":"Ready"}:
          f:lastTransitionTime: {}
          f:status: {}
      f:containerStatuses: {}
      f:podIP: {}
      f:podIPs:
        .: {}
        k:{"ip":"172.155.130.108"}:
          .: {}
          f:ip: {}
  manager: kubelet
  operation: Update
  time: "2020-03-12T02:36:21Z"
```
Some bigger object has even more `managedFields`.
I have two questions for this:
1. Is there a doc to describe the meaning and usage of `managedFields` and `Server side apply`? 
2. Is this possible to ignore these fields even `Server side apply` is enabled?
/cc @apelisse

**Comment by apelisse** [comment]
> Is there a doc to describe the meaning and usage of managedFields and Server side apply?

Most of the doc is here: https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply, let me know find a gap, I'll also make a pass.

> Is this possible to ignore these fields even Server side apply is enabled?

No, we have thought about that and decided that we didn't want to alter the object. We can revisit this decision but I don't think it would change without new compelling arguments. Do you have suggestions?

Also, overall, what is the problem you're trying to solve?

**Comment by lavalamp** [comment]
We think it's useful. That tells you kubelet wrote those fields (and not e.g. the node controller).

We didn't want to remove it from JSON/YAML output because it might cause problems for workflows that e.g. automatically read/modify/write the object.

I agree it's a little weird. We had started an effort to compress it, but that would have made it look even weirder, and it turned out not to be needed for our efficiency goals.

We're wide open to suggestions for improving the presentation!

**Comment by zhouya0** [comment]
Really thanks for your reply! Just I the first time I saw these fields make me think there's a bug in my cluster, I believe there could other users think like me if they didn't know this change.

**Comment by LiamMorrow** [comment]
I wonder if it's possible to output it so that it is on the bottom of the output.  It's pretty annoying to have to scroll through all this irrelevant metadata when doing a kubectl edit, or even just viewing the current yaml.

**Comment by lavalamp** [comment]
Yeah, it's part of metadata, so it'd be at the top either way.

I feel like there should be a jsonpath expression that prints everything except for a given field. But I haven't figured one out with a few minutes of trying.

**Comment by apelisse** [comment]
Can we build an option to hide it? I think we talked about that before, and that'd still work if someone uses the output to do a read-modify-write?

**Comment by mcristina422** [comment]
As someone who frequently uses a YAML view, the first time I used a cluster with this enabled was quite jarring. I now frequently have to scroll through pages of properties when viewing resources like `kubectl get po foo -o yaml`. Or having to jump down 100s of lines to edit an image version during `kubectl edit dp bar` 

The `managedFields` block is extremely annoying and a huge change to my workflow. I think during certain workflows it should always be dropped

**Comment by lavalamp** [comment]
Thanks for the feedback.

**Comment by OriHoch** [comment]
Yes, it's quite annoying

You can use [yq](https://mikefarah.gitbook.io/yq/) or [jq](https://stedolan.github.io/jq/) to do it

```
kubectl_yaml() {
  kubectl -o yaml "$@" \
    | yq d - 'items[*].metadata.managedFields' \
    | yq d - '.metadata.managedFields' \
    | yq d - 'items[*].metadata.ownerReferences' \
    | yq d - 'metadata.ownerReferences' \
    | yq d - 'items[*].status' \
    | yq d - 'status'
}

kubectl_json() {
  kubectl -o json "$@" \
    | jq 'del(.items[]?.metadata.managedFields)' \
    | jq 'del(.metadata.managedFields)' \
    | jq 'del(.items[]?.metadata.ownerReferences)' \
    | jq 'del(.metadata.ownerReferences)' \
    | jq 'del(.items[]?.status)' \
    | jq 'del(.status)'
}

kubectl_yaml get pods
kubectl_json get service my-service
```

**Comment by itaysk** [comment]
If anyone came here looking for a way to get rid of `managedFields`, check out [kubectl-neat](https://github.com/itaysk/kubectl-neat). It removes not only this, but also other commonly unwanted fields, and hides fields that are set to their default values. It was created some time ago with the goal to make kubernetes yamls more readable, but since the 1.18 release it has gotten more popular thanks to `managedFields`.
https://github.com/itaysk/kubectl-neat

**Comment by apelisse** [comment]
Discussion is going-on in #90066
