### ISSUE TITLE
Initcontainer-exit on error

### ISSUE THREAD

**Issue by selvapal** [kubernetes/kubernetes#89099]
Container in a Deployment exits on error

apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  containers:
  - name: application-container
    image: alpine
    command: ['sh', '-c', 'if [ -f /work/sharedfile.txt ]; then sleep 99999; else exit; fi']
    volumeMounts:
    - name: workdir-volume
      mountPath: /work
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ['sh', '-c', 'mkdr /work; echo>/work/sharedfile.txt']
    volumeMounts:
    - name: workdir-volume
      mountPath: /work
  volumes:
  - name: workdir-volume
    emptyDir: {}

**Comment by neolit123** [comment]
please try the support channels, where you can get a faster response:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
