### ISSUE TITLE
Deleting a namespace doesn't delete related ClusterRoleBinding

### ISSUE THREAD

**Issue by johnlinp** [kubernetes/kubernetes#89098]
**What happened**:

After deleting a namespace, the related ClusterRoleBinding didn't get deleted as well.

**What you expected to happen**:

I expected that related ClusterRoleBinding should be deleted after deleting a namespace.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Namespace `foo-ns`.
2. Create a ServiceAccount `foo-account` in `foo-ns`.
3. Create a ClusterRole `bar-role`.
4. Use `kubectl edit clusterrolebinding bar-role` to add a new ClusterRoleBinding:
```
- kind: ServiceAccount
  name: foo-account
  namespace: foo-ns
```
5. Delete the Namespace `foo-ns`.
6. Type `kubectl edit clusterrolebinding bar-role` again to see the current ClusterRoleBinding.
7. Found that the ClusterRoleBinding for `foo-account` in `foo-ns` was not deleted.

**Anything else we need to know?**:

None.

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
The cluster role binding exists outside the namespace, and its lifecycle is not tied to the namespace. Deletion of a namespace only removes resources contained within the namespace. One possible approach if you want the clusterrolebinding to be automatically deleted along with the namespace is to set an ownerReference on the clusterrolebinding object pointing at the namespace. Then the garbage collection controller will remove the clusterrolebinding object for you when the namespace is deleted.

**Comment by johnlinp** [comment]
@liggitt Thank you so much! I'll take a look at ownerReference.
