### ISSUE TITLE
Migrate API conventions to https://k8s.io/docs/reference/

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#89094]
**What would you like to be added**:
Migrate the content currently at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources to a new URL inside https://k8s.io/docs/reference/

Store a placeholder README at the old location, to:
- signpost readers there
- ensure existing bookmarks continue to work, at least somewhat
- draw a measure of PageRank (etc) from existing inbound hyperlinks

**Why is this needed**:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md is not localized and there is not an obvious route to localize it
- Most reference documentation lives inside https://k8s.io/docs/reference/
- The website search does not include the page at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
- There are multiple ways of linking to the API conventions including broken links to https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
  - that means that there are already some grounds for changing the URL, at least for those affected pages

/sig docs
/sig architecture
/kind documentation

**Comment by liggitt** [comment]
cc @kubernetes/api-reviewers 

We just talked about a restructure in sig-arch today.

**Comment by sftim** [comment]
Oh, this is still useful.

/reopen
/remove-lifecycle rotten

**Comment by sftim** [comment]
@kubernetes/api-reviewers would anyone like to pick this up, or to mentor someone else to make that change?
