### ISSUE TITLE
Init container resource usage not properly prioritized in scheduler

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#89092]
The scheduler does not properly calculate pod requests for a resource as `max(max(initContainers),sum(containers))` - it ignores init containers completely in `ResourceAllocationPriority`.  This would allow a workload to get "free" scheduling above the limit of containers (mitigated by quota, which calculates this properly) and so the scheduler would make non-optimal fits.  Both kubelet and scheduler enforce the `PodFitsPredicate`, so you can't actually schedule, but you sometimes get steered to the wrong node if you have more init container resource usage than containers.

`calculateResourceAllocatableRequest` in `ResourceAllocationPriority` should use `GetResourceRequest` and the similar helpers instead of writing its own method to calculate the request for resources.

/sig scheduling

**Comment by fengzixu** [comment]
Let me follow this issue.

/assign

**Comment by soltysh** [comment]
@damemi @ingvagabund fyi

**Comment by fengzixu** [comment]
After I checked the implementation of `GetResourceRequest` function, I think we just need to use it to instead of the function in the scheduler.

@Huang-Wei

**Comment by superbrothers** [comment]
Is the pod phase not considered? When the pod phase is running, the requested resource is actually considered as `sum(podSpec.scontainers)`. This change seems to reduce the resource utilization of the node.

**Comment by fengzixu** [comment]
@superbrothers Actually, I don't think we need to consider the pod.Phase. The resource request & limit are mainly used in the scheduling process. The scenario you said is not belong to the responsibility of kube-scheduler

**Comment by alculquicondor** [comment]
Correct. Setting appropriate requests/limits that maintain good node usage is users responsibility.

Considering the max(initContainers, sum(containers)) is the documented behavior.

**Comment by superbrothers** [comment]
I understand. Thank you for your comments!
