### ISSUE TITLE
Pods not updating after deployment. Kubectl rollout status not showing any status

### ISSUE THREAD

**Issue by chintanrp** [kubernetes/kubernetes#89102]
I'm applying yaml for pods deployment. And after that applying "kubectl rollout status" to monitor rollout but somehow it's not showing ay status and finishing the deployment script.

Previously it's used to work.
So, because of the above reason, my pods are not getting updated with the latest changes.

**What you expected to happen**: It should show the status of each pod deployment in each nodes

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.8
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):Ubuntu 16.04.6
- Kernel (e.g. `uname -a`):4.15.0-1050-azure
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/remove-kind bug
/triage support

> Kubernetes version (use kubectl version):1.12.8

this version is out of support, please upgrade to 1.16 as the minimum.
re-open this issue if you can reproduce it with the newer version and share the YAML your deployment.

thanks
/close

**Comment by chintanrp** [comment]
upgraded to 1.16.4 but issue still remains
