### ISSUE TITLE
[kubeadm upgrade] Misleading component version warning

### ISSUE THREAD

**Issue by jayaddison** [kubernetes/kubernetes#89108]
**What happened**:
During a cluster upgrade from `v1.17.2` to `v1.17.4`, the following misleading non-fatal warning was emitted:

`[upgrade/etcd] Non fatal issue encountered during upgrade: the desired etcd version for this Kubernetes version "v1.17.4" is "3.4.3-0", but the current etcd version is "3.4.3". Won't downgrade etcd, instead just continue`

**What you expected to happen**:
Versions `3.4.3-0` and `3.4.3` appear equal.  (refs: [supported etcd version in kubeadm source](https://github.com/kubernetes/kubernetes/commit/706cde51c512d8d07e35fc815af4439108a587f9#diff-c0a37094ae1c8cb6223a3822eb66f9f0R428), [upstream etcd github tags](https://github.com/etcd-io/etcd/tags))

If the versions are equal, then either no upgrade of `etcd` should have been attempted, or the emitted message should indicate (in an informational, non-warning level) that the current version is already satisfied.

The ambiguity may be caused by the `image-revision` (the `-0` suffix in `3.4.3-0`) as per the [`etcd` image versioning docs](https://github.com/kubernetes/kubernetes/blob/dc4d92e1544749a755f1ead1f8111b7279e4105e/cluster/images/etcd/README.md#versioning).  If so, the  `kubeadm upgrade` component may need to become more aware of this version format.

**How to reproduce it (as minimally and precisely as possible)**:
Pending repro details.

**Anything else we need to know?**:

Here's the cluster version state pre-upgrade:

```
COMPONENT            CURRENT   AVAILABLE
API Server           v1.17.2   v1.17.4
Controller Manager   v1.17.2   v1.17.4
Scheduler            v1.17.2   v1.17.4
Kube Proxy           v1.17.2   v1.17.4
CoreDNS              1.6.5     1.6.5
Etcd                 3.4.3     3.4.3-0
```

**Environment**:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"

$ sudo kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jayaddison** [comment]
/sig cluster-lifecycle

(assignment determined from `cluster-lifecycle`'s [charter](https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/charter.md#scope) re: owning cluster version upgrades, and also recent history of commits to kubeadm [GetAvailableUpgrades](https://github.com/kubernetes/kubernetes/blob/20e32882773ea6717636cfaf08e19fbcc26c85d4/cmd/kubeadm/app/phases/upgrade/compute.go#L78) which may be a relevant area of code)

**Comment by neolit123** [comment]
> The ambiguity may be caused by the image-revision (the -0 suffix in 3.4.3-0) as per the etcd image versioning docs. If so, the kubeadm upgrade component may need to become more aware of this version format.

yes, this is a known issue (but non-fatal) issue and we are tracking it here:
https://github.com/kubernetes/kubeadm/issues/2058

thanks
/close

**Comment by jayaddison** [comment]
Great to hear this is already known & tracked, thanks @neolit123 !
