### ISSUE TITLE
imagePullPolicy not work,always try pull from repository

### ISSUE THREAD

**Issue by lerit** [kubernetes/kubernetes#89100]
without internet 
image:xxx:latest
local machine has this image with tag latest.
now:
set  imagePullPolicy:IfNotPresent or Never in rancher
redeploy it

**What happened**:
error message:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "docker.io/rancher/pause:3.1": Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
![pullstragy-not-work](https://user-images.githubusercontent.com/4743467/76589297-8d2d3680-6524-11ea-8f31-976c66038e8a.png)

**What you expected to happen**:
redeploy my image without pull from internet repository
**How to reproduce it (as minimally and precisely as possible)**:
with a workload that work fine;
set  imagePullPolicy:Never
redeploy it
**Anything else we need to know?**:
from error message:is it mean rancher try to download 'docker.io/rancher/pause:3.1' from repository cause this error?
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0+k3s.1", GitCommit:"0f644650f5d8e9f091629f860b342f221c46f6d7", GitTreeState:"clean", BuildDate:"2020-01-06T23:22:38Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0+k3s.1", GitCommit:"0f644650f5d8e9f091629f860b342f221c46f6d7", GitTreeState:"clean", BuildDate:"2020-01-06T23:22:38Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
ubuntu 18.04
- Kernel (e.g. `uname -a`):
Linux liyy 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
docker+rancher+k3s
- Network plugin and version (if this is a network-related bug):
- Others:
import k3s cluster

**Comment by onesolpark** [comment]
`docker.io/rancher/pause:3.1` is a sandbox image which is needed for every pod.

Even if you set imagePullPolicy:IfNotPresent or Never kubelet will try to pull the pause image.

You can change `--pod-infra-container-image` args in kubelet to set it to a repo that you can reach

**Comment by lerit** [comment]
@onesolpark  thank you! resolve by setting --pod-infra-container-image :)

**Comment by rnwhitehead** [comment]
It appears to me that if you create a pod with containers with the imagePullPolicy "always", this seems to stick: setting it to IfNotPresent has no effect, even if you delete and recreate the pod.
