### ISSUE TITLE
Pods not updating after deployment. Kubectl rollout status not showing any status

### ISSUE THREAD

**Issue by chintanrp** [kubernetes/kubernetes#89101]
I'm applying yaml for pods deployment. And after that applying "kubectl rollout status" to monitor rollout but somehow it's not showing ay status and finishing the deployment script.

Previously it's used to work.
So, because of the above reason, my pods are not getting updated with the latest changes.

**Comment by tedyu** [comment]
Which release are you using now ?
```
Previously it's used to work.
```
Which release did this work ?

thanks

**Comment by chintanrp** [comment]
Previous and current are both 1.12.8

**Comment by dims** [comment]
/close

not enough information to help in any way
