### ISSUE TITLE
Add support for live volume mount/unmount in kubernetes

### ISSUE THREAD

**Issue by cosminilie** [kubernetes/kubernetes#8910]
Based on the discussion on the mailing list [https://groups.google.com/forum/#!topic/google-containers/j0QR971KtJc] i'm opening a feature request.

We have the following scenario in our application. On each container we run a multi-tennat java app. For each tenant we're using using 2 NFS volumes . One is used to store the tenant's files (inputs for processing,reports and other data we can't loose) and another one is to store temp data used for short lived temporary stuff. The reason why we're using NFS is that we need that to grow dynamically so here NFS/Gluster us handy as based on the space usage alert we can increase it automatically up to some predefined limit, again without restarting the container. The ability to grow the data volume is also a requirement.

Our tenants also move from one container to another when being upgraded. We move the tenant to another container because that runs a newer version of the app, however since moving them means a service interruption we can't always move all the tenants to a new version so we need to do it selectively without affecting the existing ones . When moving them we also need to unmount the volumes associated with the tenant and mount them on the new container.

**Comment by pmorie** [comment]
@cosminilie Can I clarify, in your use-case, the containers you move tenants between live longer than the work required for a tenant?  Do the containers serve more than one tenant at a time?  I don't think it should make a difference in the implementation required, I just want to be sure I understand the use-case.

@rootfs @markturansky

**Comment by cosminilie** [comment]
@pmorie your are right,the tenant live longer than the container.  As for your second question, yes the containers serve more than one tenant at a time. 

Sorry for taking so long to respond.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-feature-requests
