### ISSUE TITLE
[Feature] [kubectl] create or replace configmap

### ISSUE THREAD

**Issue by matanshukry** [kubernetes/kubernetes#89129]
**What would you like to be added**:
Create or replace if exist, for a configmap.
To preserve backward compatibility, a new flag can be added (with default being same behavior as now)

**Why is this needed**:
Seems basic, but I need it so I can use it in a script.
Currently my script uses replace, but every time when I change cluster (for example a new local cluster), I need to create the config map manually and only then the script will work.

There's an old issue about it but it was closed due to inactivity and I can't reopen it - but it's definitely still an issue ( #65066 )

/sig cli

**Comment by liggitt** [comment]
`kubectl apply` does this create-or-update behavior

**Comment by matanshukry** [comment]
@liggitt you're right, while the syntax I used is not as straightforward to me (and probably other users), it now allow to use apply and it works. For people who're looking for this

```
 kubectl --context=my-context create configmap social-config --from-env-file=data/deploy/config-1-dev.properties -o yaml --dry-run | kubectl --context=my-context apply -f -
```

**Comment by virtualdxs** [comment]
@liggitt Is there a way to use kubectl apply with --from-file and similar without a pipe as @matanshukry demonstrated above?
