### ISSUE TITLE
Kubernetes thinks that a file is not a file

### ISSUE THREAD

**Issue by theAkito** [kubernetes/kubernetes#89127]
**What happened**:

```
  MountVolume.SetUp failed for volume "customer" : hostPath  type check failed:  /hostPath/to/customerProfile.json is not a file
```
but
```
/hostPath/to/customerProfile.json: UTF-8 Unicode text
```
and using `cat` onto the file works flawlessly, displaying the contents.

**What you expected to happen**:
I expected Kubernetes to mount a file and use a file instead of complaining, that a file is not really a file.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a File on the host.
2. Provide the volume that contains the file as a `hostPath`. No SubPath.
3. Add this volume to `volumeMounts`.
4. Wonder why a file does not recognized as a file, when looking at the logs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Custom Cloud
- OS (e.g: `cat /etc/os-release`):
`Debian GNU/Linux bullseye`
- Kernel (e.g. `uname -a`):
`Linux 5.4.0-2-amd64 #1 SMP Debian 5.4.8-1 (2020-01-05) x86_64 GNU/Linux`

**Comment by wawa0210** [comment]
You can check if this file `/ hostPath / to / customerProfile.json` is a file of type` link`

**Comment by theAkito** [comment]
@wawa0210 

Thanks for your response.

Do you mean, check if it is a hard|symbolic link? It's not a generic link.
Or are you referring to a different type of `link`?

**Comment by wawa0210** [comment]
Is a symbolic link?
