### ISSUE TITLE
IPVS dont work in EKS 1.14

### ISSUE THREAD

**Issue by b0nete** [kubernetes/kubernetes#89126]
**What happened**:
IPVS dont work in EKS 1.14

**What you expected to happen**:
I've deployed kube-proxy with --proxy-mode=ipvs flag, but kube-proxy keeps running with iptables.

Here the snippet of kube-proxy daemonset yaml, i use kube-proxy:v1.12.6 image

>  containers:
      - command:
        - /bin/sh
        - -c
        - kube-proxy --v=2 --config=/var/lib/kube-proxy-config/config --proxy-mode=ipvs

Here logs when kube-proxy is executed.

> kubectl logs -f kube-proxy-429sm
I0314 21:04:09.511460       6 flags.go:33] FLAG: --alsologtostderr="false"
I0314 21:04:09.511508       6 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0314 21:04:09.511516       6 flags.go:33] FLAG: --cleanup="false"
I0314 21:04:09.511523       6 flags.go:33] FLAG: --cleanup-iptables="false"
I0314 21:04:09.511537       6 flags.go:33] FLAG: --cleanup-ipvs="true"
I0314 21:04:09.511542       6 flags.go:33] FLAG: --cluster-cidr=""
I0314 21:04:09.511548       6 flags.go:33] FLAG: --config="/var/lib/kube-proxy-config/config"
I0314 21:04:09.511554       6 flags.go:33] FLAG: --config-sync-period="15m0s"
I0314 21:04:09.511561       6 flags.go:33] FLAG: --conntrack-max="0"
I0314 21:04:09.511567       6 flags.go:33] FLAG: --conntrack-max-per-core="32768"
I0314 21:04:09.511573       6 flags.go:33] FLAG: --conntrack-min="131072"
I0314 21:04:09.511579       6 flags.go:33] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
I0314 21:04:09.511588       6 flags.go:33] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
I0314 21:04:09.511600       6 flags.go:33] FLAG: --feature-gates=""
I0314 21:04:09.511620       6 flags.go:33] FLAG: --healthz-bind-address="0.0.0.0:10256"
I0314 21:04:09.511627       6 flags.go:33] FLAG: --healthz-port="10256"
I0314 21:04:09.511632       6 flags.go:33] FLAG: --help="false"
I0314 21:04:09.511637       6 flags.go:33] FLAG: --hostname-override=""
I0314 21:04:09.511642       6 flags.go:33] FLAG: --iptables-masquerade-bit="14"
I0314 21:04:09.511647       6 flags.go:33] FLAG: --iptables-min-sync-period="0s"
I0314 21:04:09.511652       6 flags.go:33] FLAG: --iptables-sync-period="30s"
I0314 21:04:09.511657       6 flags.go:33] FLAG: --ipvs-exclude-cidrs="[]"
I0314 21:04:09.511675       6 flags.go:33] FLAG: --ipvs-min-sync-period="0s"
I0314 21:04:09.511680       6 flags.go:33] FLAG: --ipvs-scheduler=""
I0314 21:04:09.511685       6 flags.go:33] FLAG: --ipvs-sync-period="30s"
I0314 21:04:09.511690       6 flags.go:33] FLAG: --kube-api-burst="10"
I0314 21:04:09.511695       6 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0314 21:04:09.511700       6 flags.go:33] FLAG: --kube-api-qps="5"
I0314 21:04:09.511718       6 flags.go:33] FLAG: --kubeconfig=""
I0314 21:04:09.511728       6 flags.go:33] FLAG: --log-backtrace-at=":0"
I0314 21:04:09.511740       6 flags.go:33] FLAG: --log-dir=""
I0314 21:04:09.511758       6 flags.go:33] FLAG: --log-flush-frequency="5s"
I0314 21:04:09.511767       6 flags.go:33] FLAG: --logtostderr="true"
I0314 21:04:09.511775       6 flags.go:33] FLAG: --masquerade-all="false"
I0314 21:04:09.511783       6 flags.go:33] FLAG: --master=""
I0314 21:04:09.511792       6 flags.go:33] FLAG: --metrics-bind-address="127.0.0.1:10249"
I0314 21:04:09.511809       6 flags.go:33] FLAG: --metrics-port="10249"
I0314 21:04:09.511818       6 flags.go:33] FLAG: --nodeport-addresses="[]"
I0314 21:04:09.511831       6 flags.go:33] FLAG: --oom-score-adj="-999"
I0314 21:04:09.511840       6 flags.go:33] FLAG: --profiling="false"
**I0314 21:04:09.511849       6 flags.go:33] FLAG: --proxy-mode="ipvs"**
I0314 21:04:09.511859       6 flags.go:33] FLAG: --proxy-port-range=""
I0314 21:04:09.511870       6 flags.go:33] FLAG: --resource-container="/kube-proxy"
I0314 21:04:09.511879       6 flags.go:33] FLAG: --stderrthreshold="2"
I0314 21:04:09.511888       6 flags.go:33] FLAG: --udp-timeout="250ms"
I0314 21:04:09.511898       6 flags.go:33] FLAG: --v="2"
I0314 21:04:09.511915       6 flags.go:33] FLAG: --version="false"
I0314 21:04:09.511924       6 flags.go:33] FLAG: --vmodule=""
I0314 21:04:09.511929       6 flags.go:33] FLAG: --write-config-to=""
I0314 21:04:09.512774       6 feature_gate.go:206] feature gates: &{map[]}
**I0314 21:04:09.537829       6 server_others.go:148] Using iptables Proxier.**
W0314 21:04:09.537984       6 proxier.go:304] missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended
W0314 21:04:09.538009       6 proxier.go:317] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0314 21:04:09.538146       6 server_others.go:178] Tearing down inactive rules.
I0314 21:04:12.195730       6 iptables.go:200] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
I0314 21:04:12.195794       6 server.go:466] Version: v1.12.6
I0314 21:04:12.202708       6 server.go:492] Running in resource-only container "/kube-proxy"
I0314 21:04:12.203732       6 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 262144
I0314 21:04:12.203896       6 conntrack.go:52] Setting nf_conntrack_max to 262144
I0314 21:04:12.204006       6 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0314 21:04:12.204153       6 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0314 21:04:12.204353       6 config.go:102] Starting endpoints config controller
I0314 21:04:12.204372       6 controller_utils.go:1027] Waiting for caches to sync for endpoints config controller
I0314 21:04:12.204396       6 config.go:202] Starting service config controller
I0314 21:04:12.204423       6 controller_utils.go:1027] Waiting for caches to sync for service config controller
I0314 21:04:12.304577       6 controller_utils.go:1034] Caches are synced for endpoints config controller
I0314 21:04:12.304653       6 controller_utils.go:1034] Caches are synced for service config controller
I0314 21:04:12.304665       6 proxier.go:643] Not syncing iptables until Services and Endpoints have been received from master
I0314 21:04:12.304761       6 service.go:309] Adding new service port "qa1/frontend:main" at 172.20.117.204:3000/TCP

**How to reproduce it (as minimally and precisely as possible)**:
I follow the next guide for enable IPVS.
https://medium.com/@jeremy.i.cowan/the-problem-with-kube-proxy-enabling-ipvs-on-eks-169ac22e237e

I edited the user-data of my ASG adding the follow lines for enable ipvs and set env in each new node.

This is my user-data script.

> #!/bin/bash 
set -ex 
modprobe -- ip_vs
modprobe -- ip_vs_rr
modprobe -- ip_vs_wrr
modprobe -- ip_vs_sh
modprobe -- nf_conntrack_ipv4
lsmod | grep -e ip_vs -e nf_conntrack_ipv4 >> /home/ec2-user/testUG
echo "========================" >> /home/ec2-user/testUG
cut -f1 -d " "  /proc/modules | grep -e ip_vs -e nf_conntrack_ipv4 >> /home/ec2-user/testUG
export KUBE_PROXY_MODE=ipvs
B64_CLUSTER_CA=XXXXXXXXXXXXXXX
API_SERVER_URL=https://XXXXXX.eks.amazonaws.com 
/etc/eks/bootstrap.sh XXXX --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=nodegroup-XXXXXXX,eks.amazonaws.com/nodegroup-image=ami-087a82f6b78a07557' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL

Logging me in node with ssh i check the installed modules in file testUG generate previusly.

> cat /home/ec2-user/testUG
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  0
ip_vs                 172032  6 ip_vs_rr,ip_vs_sh,ip_vs_wrr
nf_defrag_ipv6         20480  1 ip_vs
nf_conntrack_ipv4      16384  1
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
nf_conntrack          155648  5 xt_conntrack,nf_conntrack_ipv4,nf_nat,nf_nat_ipv4,ip_vs
libcrc32c              16384  4 nf_conntrack,nf_nat,xfs,ip_vs
ipv6                  524288  40 bridge,ip_vs
========================
ip_vs_sh
ip_vs_wrr
ip_vs_rr
ip_vs
nf_conntrack_ipv4

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-29T16:37:45Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
AWS - EKS v1.14
- OS (e.g: `cat /etc/os-release`):
ec2-user]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
- Kernel (e.g. `uname -a`):
ec2-user]# **uname -a**
Linux ip-10-11-235-133.ec2.internal 4.14.154-128.181.amzn2.x86_64 #1 SMP Sat Nov 16 21:49:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Nothing.

- Network plugin and version (if this is a network-related bug):

- Others:

**Comment by b0nete** [comment]
> @b0nete: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
>     * `/sig <group-name>`
> 
>     * `/wg <group-name>`
> 
>     * `/committee <group-name>`
> 
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

/sig network

**Comment by dims** [comment]
please contact AWS/EKS support

/close
