### ISSUE TITLE
Create Security Bulletins page

### ISSUE THREAD

**Issue by oke-py** [kubernetes/kubernetes#89130]
**What would you like to be added**:
I'd like the team to publish a security bulletin when a vulnerability is found.
I need information such as below.
- CVSS v3 score or Severity <= This is what I want most.
- Affected versions
- Patched versions
- CVE identifier
- (how to detect)
- (how to mitigate)

ref:
- [Istio Security Bulletins](https://istio.io/news/security/)
- [Envoy Security Advisory](https://github.com/envoyproxy/envoy/security/advisories)

This page can be used.
https://github.com/kubernetes/kubernetes/security/advisories

**Why is this needed**:
Security Bulletins enable us to quickly make sure our cluster has no vulnerabilities.
What's more, CVSS score helps us decide when our cluster should be upgraded when new vulnerabilities are found.

---

I opened an issue https://github.com/kubernetes/website/issues/19627 but I noticed it might not be up tp sig-docs. Then, I recreated this issue.

/area security
/sig release

**Comment by justaugustus** [comment]
cc: @kubernetes/product-security-committee @kubernetes/release-engineering 
/committee product-security
/area release-eng

**Comment by oke-py** [comment]
I'm satisfied with [today's Security Advisory](https://groups.google.com/forum/m/#!msg/kubernetes-announce/jPiyJ1KL_FI/1bMtMyS7BQAJ) as a prompt report. Thanks!

It'll be perfect for me if there is a list of vulnerabilities.

**Comment by liggitt** [comment]
http://kubernetes.io/cve links to an issue query listing all disclosed vulnerabilities. We are investigating using the github advisories capability as well in the future, and if we switch to that, will update http://kubernetes.io/cve to redirect there.
