### ISSUE TITLE
Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="

### ISSUE THREAD

**Issue by lwx294821** [kubernetes/kubernetes#89132]
when  installed k8s v1.16.7,I checked pods and the result is as follow:
 **kubectl logs kube-controller-manager-node1 -n kube-system**
 I0315 09:28:28.488397       1 shared_informer.go:197] Waiting for caches to sync for garbage collector
I0315 09:28:28.570006       1 shared_informer.go:204] Caches are synced for certificate
W0315 09:28:28.572658       **1 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="node1" does not exist
W0315 09:28:28.577527       1 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="node2" does not exist
W0315 09:28:28.577752       1 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="node3" does not exist**

**Comment by tedyu** [comment]
Did all the nodes from your cluster encounter the error of actual_state_of_world.go line 506 ?

If not, can you observe difference between the nodes ?

For node1, did it recover sometime later ?
Examining / attaching kubelet log from node1 may also provide more clue.

**Comment by neolit123** [comment]
/triage needs-information
also please properly fill the issue template:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
