### ISSUE TITLE
Pods stuck in ContainerCreating state after network outage

### ISSUE THREAD

**Issue by MelissaOS** [kubernetes/kubernetes#89143]
After a short network outage that occurred 3 days ago, some Pods are stuck in "ContainerCreating" or "Init" state and will probably never come up again without manual intervention. This network outage was outside of PKS/NSX-T, more related to generic connectivity.

 The context is an outage on the customer side network, in particular DNS affected but NSX-T kept working theoretically fine during that time, just with no external connection. Pods relying on DNS outside of Kubernetes couldn’t reach it as any traffic was cut.  

deleting the affected Pods manually fixes the issue, as new ones will be properly scheduled.

But could you please have a look at this issue and provide a solution that would prevent such cases to occur in the future (e.g. timeout for container creation after a certain time they are deleted themselves and recreated)?

**Comment by tedyu** [comment]
Can you attach control plane logs and kubelet log for analysis ?

Thanks

**Comment by MelissaOS** [comment]
Is there a timed event where kubernetes handles these containers when they are seen to be unresponsive. what is the time gap for this? Is there a way to modify this time gap?

**Comment by MelissaOS** [comment]
@kubernetes/sig-scheduling-misc

**Comment by ahg-g** [comment]
@MelissaOS this is a node related issue not a scheduling issue.

**Comment by MelissaOS** [comment]
Hi there, Just wondering does anyone have more information on SIG-nodes?

**Comment by tedyu** [comment]
@MelissaOS 
See #89155
