### ISSUE TITLE
Build cmd/kubectl-ns.go getting undefined errors.Is  in api machinery module

### ISSUE THREAD

**Issue by Aamir-raza-1** [kubernetes/kubernetes#89148]
**What happened**:
../k8s.io/apimachinery@v0.0.0-20200307122051-2b7fa1cb5395/pkg/util/errors/errors.go:99:10: undefined: errors.Is

**What you expected to happen**:
Executable in configured bin  folder

**How to reproduce it (as minimally and precisely as possible)**:
git clone git@github.com:kubernetes/sample-cli-plugin.git
cd sample-cli-plugin
GO111MODULE="on" go build cmd/kubectl-ns.go

**Anything else we need to know?**:

**Environment**:
- Go version (use `go version`):
go version go1.12.5 darwin/amd64
- Go env
OARCH="amd64"
GOBIN=""
GOCACHE="/Users/aamirraza/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/aamirraza/go:/Users/aamirraza/code"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/aamirraza/dev/kubectl-plugin/sample-cli-plugin/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z2/xpwd22297yz16t146gdbfpq00000gn/T/go-build059653031=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by robutil** [comment]
Hi, I had the same issue; but upgrading to go v1.14 solved it for me.
