### ISSUE TITLE
Strategic Merge Patch has different results in two ways of deleting a map

### ISSUE THREAD

**Issue by superbrothers** [kubernetes/kubernetes#89140]
**What happened**:
[The document of Strategic Merge Patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#maps) says `$patch: delete` and `null` are equivalent ways to delete a map as follows:

> One way to delete a map is using delete directive. Applying this patch will delete the rollingUpdate map.
> 
> ```yaml
> rollingUpdate:
>   $patch: delete
> ```
> An equivalent way to delete this map is
> 
> ```yaml
> rollingUpdate: null
> ```

However, I got different results in each way. Is this a bug of strategic marge patch, or mistake in that document?

**What you expected to happen**:

That two ways to delete a map have the same result.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl create configmap env-config --from-literal=log_level=INFO
configmap/env-config created

$ cat <<EOL | kubectl create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: log_level
EOL

$ kubectl patch deploy nginx --patch "$(cat <<'EOL'
{
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "name": "nginx",
            "env": [
              {
                "name": "LOG_LEVEL",
                "value": "INFO",
                "valueFrom": {
                    "$patch": "delete"
                }
              }
            ]
          }
        ]
      }
    }
  }
}
EOL
)"
The Deployment "nginx" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`

$ kubectl patch deploy nginx --patch "$(cat <<'EOL'
{
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "name": "nginx",
            "env": [
              {
                "name": "LOG_LEVEL",
                "value": "INFO",
                "valueFrom": null
              }
            ]
          }
        ]
      }
    }
  }
}
EOL
)"
deployment.apps/nginx patched

$ kubectl get deploy nginx -o jsonpath='{.spec.template.spec.containers[*].env}'
[map[name:LOG_LEVEL value:INFO]]
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
    - `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}`
    - `Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yue9944882** [comment]
we used to fix this by https://github.com/kubernetes/kubernetes/pull/67586 but now we are addressing all the drawbacks from "strategic-merge-patch" in another feature named "server-side-apply". plz migrate to the latter approach.

**Comment by superbrothers** [comment]
This bug also affects Kustomize, which probably won't be resolved in the Server-side apply.
