### ISSUE TITLE
Mutation restriction on informer clients is not well documented

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#89157]
**What happened**:
I discovered colleagues writing informer clients that modify objects delivered by informers.  I went looking for where it says they should not do that, and I could not find it.

**What you expected to happen**:
I expected this critical restriction to be prominently documented.

**How to reproduce it (as minimally and precisely as possible)**:
Try to find where it says that a client of an informer must not modify an object delivered by the informer.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by enj** [comment]
Documentation aside, I would suggest adding `export KUBE_CACHE_MUTATION_DETECTOR=true` to your CI infra to make it harder for people to make this mistake.

**Comment by fedebongio** [comment]
/assign @MikeSpreitzer 
Thank you for fixing docs!
