### ISSUE TITLE
apimachinery: RFC3339Micro format seems to be incorrect

### ISSUE THREAD

**Issue by technosophos** [kubernetes/kubernetes#89156]
**What happened**:
The Go time.RFC3339Nano format is 2006-01-02T15:04:05.999999999Z07:00, while the meta/v1 apimachinery package has the RFC3339Micro format set to 2006-01-02T15:04:05.000000Z07:00 (Note the zeros instead of nines).

https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/micro_time.go#L26

A parse error results when a client sends a date that does not use placeholder zeros to right-pad the microseconds. E.g. the timestamp 2006-01-02T15:04:05.1234Z07:00 will cause a parse error because the microtime is not right-padded.

This particularly breaks API usage when timestamps like the above (which are RFC3339 compatible) cannot be parsed by APIMachinery.

**What you expected to happen**:

Since (a) this is inconsistent with Go's interpretation of RFC3339, and (b) a parser ought to opt for leniency when strictness does not improve the fidelity or integrity of the data, it seems that the date format used in micro_time.go might best be changed to use 9 instead of 0.

**How to reproduce it (as minimally and precisely as possible)**:

Parse `2006-01-02T15:04:05.1234Z07:00` using ` RFC3339Micro` as the parse format.

**Anything else we need to know?**:

**Environment**:
This is present in the current version of apimachinery, confirmed with Kubernetes 1.15 and 1.17.

**Comment by yliaog** [comment]
i think it is intentional such that the date is always right-pad the microseconds to the fixed length. it is stricter than what golang RFC3339Nano requires.

does this cause any problem for your use case?

**Comment by technosophos** [comment]
Yes. As I noted in the issue, any platform that uses the API but does NOT right-pad dates will fail with a parse error. RFC3339 does not require padding dates (and, in fact, remains silent on the matter). Thus, Kubernetes is placing a requirement over and above the RFC, and one that does not match other implementations of the RFC.

**Comment by Nuru** [comment]
I believe the best solution is to use a fixed-width format for output and a variable width format for input. See the code in #91186 for how I propose modifying kubelet to do this for logs. The same kind of thing can be done here for RFC3339Micro, namely create RFC3339MicroFixed and RFC3339MicroLenient and use Fixed for output and Lenient for input. Or, frankly, use RFC3339NanoLenient for input, as that accepts 0 to 9 digits after the decimal point.

**Comment by Nuru** [comment]
/remove-lifecycle stale

As I said above, this can and should be fixed with lenient parsing of input while keeping strict formatting of output. This exact change was made for handling container log timestamps in https://github.com/kubernetes/kubernetes/pull/91207 which has been accepted for Kubernetes 1.19 and backported to 1.16, 1.17, and 1.18.

**Comment by asmeikal** [comment]
This issue is breaking requests from the JavaScript client: `Date` fields are [formatted](https://github.com/kubernetes-client/javascript/blob/master/src/gen/model/models.ts#L1976) to ISO 8601 with millisecond precision, but if the field is a `MicroTime` the request fails due to a parsing error.

```
unmarshalerDecoder: parsing time "2020-12-09T23:44:10.443Z" as "2006-01-02T15:04:05.000000Z07:00": cannot parse ".443Z" as ".000000"
```

**Comment by yliaog** [comment]
i agree with the proposal given in comment https://github.com/kubernetes/kubernetes/issues/89156#issuecomment-629884397

**Comment by asmeikal** [comment]
@yliaog should I assign the issue to myself to submit a fix?

**Comment by yliaog** [comment]
@asmeikal sounds good to me
