### ISSUE TITLE
The Multi-AZ spreading test makes an incorrect assumption about which zones are candidates

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#89178]
Tests in k8s.io/kubernetes/test/e2e/scheduling/ubernetes_lite.go assume that the set of zones that pods are spread over is "all node zones".  That is not true for two reasons:

1. User workloads may be scheduled by default to a subset of nodes
2. The set of nodes users can schedule to may be further subdivided by rules

The test fails in the following config (3 masters, 2 nodes for user workloads) because the test draws from all zones.

We need to fix the tests so that the user invoking e2e specifies an optional selector for which nodes should be tested (i.e. machines that are not tainted with master, or machines that have the node-role label selector worker, or a list of nodes).  Then the test should be updated to calculate zone names from that subset.

**Comment by damemi** [comment]
Is this still being seen as a flake?

**Comment by hakman** [comment]
@damemi @johngmyers seems that it got better lately:
https://testgrid.k8s.io/kops-misc#kops-aws-ha-euwest1
