### ISSUE TITLE
Pod startup failed when CSI driver changes from attachable to non-attachable

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#89173]
**What happened**:
When a CSI driver changes from attachable (`CSIDriver.spec.attachRequired`: true) to non-attachable (`attachRequired: false`) in the middle of attaching a volume, A/D controller still wants to attach the volume.

**What you expected to happen**:
A/D controller skips attach.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install CSI mock driver:
    - With `--disable-attach=true`, so the mock driver does not require `ControllerPublish`)
    - Without the external-attacher sidecar, so we can simulate slow attach.
    - Without any CSIDriver instance, so A/D controller requires attach.
2. Create a PVC and start a pod.
3. Wait for time outs when attaching the provisioned volume, because the external-attacher is not running.
4. Create CSIDriver with `attachRequired: false`.

The pod never starts. The volume is already in A/D controller desired state of world and nothing removes it from there.

Pod events:
```
Successfully assigned default/testpod to ip-10-0-160-231.us-east-2.compute.internal
AttachVolume.Attach failed for volume "pvc-1da1900a-7514-4a4a-9a65-bb54f5c42308" : attachdetachment timeout for volume 5
AttachVolume.FindAttachablePluginBySpec failed for volume "pvc-1da1900a-7514-4a4a-9a65-bb54f5c42308"
Unable to attach or mount volumes: unmounted volumes=[vol], unattached volumes=[vol default-token-2mwq6]: timed out waiting for the condition
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.1

/sig storage
cc @gnufied @jingxu97 @msau42

**Comment by ensonic** [comment]
If there are ordering constraints in pvc, pv and pod -w hat are they? This should definitely be fixed, but at least I could work around it in the tooling. I don't manage to get anything reliable to schedule using pvc + pv on a kubeadm cluster.

**Comment by msau42** [comment]
The main constraint right now is that the CSIDriver object needs to be created before the workload tries to use it. We're looking to fix that.

**Comment by Jiawei0227** [comment]
Hi Saad, I am willing to take this bug and try to fix it!

**Comment by ioanc** [comment]
hello; 
we have seen similar behavior after upgrading K8s from 1.18.15 to 1.19.8.
But the pods are starting and able to use the storage with success.
When describing the pod, we see the specific warning event

Type: Warning
Reason: FailedAttachVolume
From: attachdetach-controller
Message:  AttachVolume.FindAttachablePluginBySpec failed for volume "pvc-xxx"

Restarting the pod makes the warning to go away

csidriver details:

Name: csi.nutanix.com
ATTACHREQUIRED : false
PODINFOONMOUNT : true
MODES: Persistent
