### ISSUE TITLE
Service account token secret can be made invalid

### ISSUE THREAD

**Issue by edwardstudy** [kubernetes/kubernetes#89174]
**What happened**:

The secret of sa token can be tampered with.

**What you expected to happen**:
- tokens controller can regenerate the token

**How to reproduce it (as minimally and precisely as possible)**:

Modify the `.data.token` of the token secret:
```
stringData:
  token: invalid
```
The token has became `invalid`:
```
$ kubectl get secret sa-test-token-*** -o jsonpath='{.data.token}' | base64 -D
invalid%
```

**Anything else we need to know?**:
Does that make sense to not verify the jwt token and then regenerate token if the `.data.token` is changed?
If it needs to change, I'm glad to handle this.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
the stringData or data fields of a Secret are not immutable, which means that anybody with permissions can modify it. this can be prevented with the right RBAC.

see this related KEP:
https://github.com/kubernetes/enhancements/issues/1412

> tokens controller can regenerate the token

this seems like a feature request.

/kind feature
/sig auth

**Comment by enj** [comment]
@liggitt any reason we do not do a `bytes.Equal` for `needsToken` similar to the `needsCA` calculation?

https://github.com/kubernetes/kubernetes/blob/76f85943787a5901a34a314a935712177edd2db0/pkg/controller/serviceaccount/tokens_controller.go#L502-L508

**Comment by liggitt** [comment]
yeah, jwt validation on every relist is expensive for the controller...

**Comment by liggitt** [comment]
clarified title to be less alarming

**Comment by liggitt** [comment]
I don't anticipate making these secrets immutable, since it would break some existing workflows. Removing the token key from the secret is one way to request it be regenerated/repopulated in key rotation cases.

Since most of our efforts are focused on the non-secret-based service account tokens, addressing a scenario where someone with secret write access invalidates a secret-based token doesn't seem like a high priority.

/priority awaiting-more-evidence

**Comment by edwardstudy** [comment]
@liggitt Got it. Did `non-secret-based service account tokens` mean `BoundServiceAccountTokenVolume`? I did this examination because I want to use `BoundServiceAccountTokenVolume` and wanted to remove this default non-expiring service account token for security. So when `BoundServiceAccountTokenVolume` is GA, do we still have the service account token secret in this scenario?

**Comment by liggitt** [comment]
> Did `non-secret-based service account tokens` mean `BoundServiceAccountTokenVolume`?

Yes, pods using that feature do not make use of secret-based tokens, and are not affected by this.

> So when BoundServiceAccountTokenVolume is GA, do we still have the service account token secret in this scenario?

Once we switch the tokens that are auto-injected into pods away from secret-based tokens, we will likely transition to stop auto-generating those.

We will likely continue supporting populating secret-based tokens that [explicitly request them](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token).
