### ISSUE TITLE
e2e framework should support non-default configuration of NodePort range

### ISSUE THREAD

**Issue by vryzhenkin** [kubernetes/kubernetes#89175]
**What would you like to be added**:
On configurations with non-default `--service-node-port-range` some tests from [Conformance] subset may fail, due hardcoded port range here https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/service/jig.go#L55
It'll be good if someone can decide to unhardcode this parameter and add it into test context instead have it hardcoded.

**Why is this needed**:
It's needed to correctly cover NodePort functionality since it's possible to configure it on control plane.

**Comment by BenTheElder** [comment]
@alejandrox1 @aojea 
/sig network

**Comment by aojea** [comment]
this is a tricky thing, in my opinion. Some installers use the defaults for configuring the cluster an the host system, then run sunobouy or e2e tests directly, using non-defaults may break things in the ecosystem. Also, this is a conformance test, we should have buy-in from the conformance group.

For coverage, I think that this feature is well covered, it has unit tests for the non-defaults and I personally don't remember any recent issue about this, and is a heavily used feature. 100% coverage is great but my personal opinion is that is not worth in this case, just my 2 cents
