### ISSUE TITLE
[Flaky Test] release-test (pull-release-test)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#89197]
**Which jobs are failing**:
`release-test (pull-release-test)`

**Which test(s) are failing**:
`//external/io_k8s_repo_infra/hack:verify-golangci-lint`

**Since when has it been failing**:
`03-17-20 1647 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-misc#release-test

**Reason for failure**:
```
FAIL: @io_k8s_repo_infra//hack:verify-golangci-lint (see /root/.cache/bazel/_bazel_root/92c657af61c81ec6a823dc4627a93ca5/execroot/io_k8s_release/bazel-out/k8-fastbuild/testlogs/external/io_k8s_repo_infra/hack/verify-golangci-lint/test.log)
INFO: From Testing @io_k8s_repo_infra//hack:verify-golangci-lint:
==================== Test output for @io_k8s_repo_infra//hack:verify-golangci-lint:
Verifying golangci-lint...
level=warning msg="[runner/nolint] Found unknown linters in //nolint directives: deprecated"
../../../../../../../../../../../../../../../../../../home/prow/go/src/k8s.io/release/cmd/krel/cmd/release_notes.go:465: unnecessary leading newline (whitespace)
	for scanner.Scan() {
../../../../../../../../../../../../../../../../../../home/prow/go/src/k8s.io/release/cmd/krel/cmd/release_notes.go:712:19: SA1019: doc.RenderMarkdown is deprecated: Prefer using the golang template instead of markdown. Will be removed in #1019  (staticcheck)
	markdown, err := doc.RenderMarkdown(
	                 ^
ERROR: golangci-lint failed
```
**Anything else we need to know**:
/cc @kubernetes/ci-signal
/sig release
/priority important-soon
/milestone v1.18

**Comment by hasheddan** [comment]
I am looking into this

/assign @hasheddan

**Comment by hasheddan** [comment]
Looks true reason for flake is this:

```
time="2020-03-18T02:36:54Z" level=info msg="Using release branch release-1.16"
time="2020-03-18T02:36:54Z" level=info msg="Using local repository path /tmp/k8s-test/test-1584498973"
time="2020-03-18T02:36:54Z" level=info msg="We're currently on branch: master"
time="2020-03-18T02:36:54Z" level=info msg="Found latest origin/release-1.16 commit 5116ee4b159565b69a040a62f8a824adbb110ffa"
--- FAIL: TestNewRCRelease (44.71s)
    changelog_test.go:202: 
        	Error Trace:	changelog_test.go:202
        	Error:      	Expected nil, but got: no latest tag available for branch release-1.16
        	Test:       	TestNewRCRelease
Cloning into '/tmp/k8s-test/base-1584499018'...
```

**Comment by droslean** [comment]
This is a presubmit and it was failing because of https://github.com/kubernetes/release/pull/1185 https://github.com/kubernetes/release/pull/1180 https://github.com/kubernetes/release/pull/1187

@saschagrunert @puerco @j0n3lson  Did you notice any flakes on your PRs?

**Comment by saschagrunert** [comment]
> Looks true reason for flake is this:
> 
> ```
> time="2020-03-18T02:36:54Z" level=info msg="Using release branch release-1.16"
> time="2020-03-18T02:36:54Z" level=info msg="Using local repository path /tmp/k8s-test/test-1584498973"
> time="2020-03-18T02:36:54Z" level=info msg="We're currently on branch: master"
> time="2020-03-18T02:36:54Z" level=info msg="Found latest origin/release-1.16 commit 5116ee4b159565b69a040a62f8a824adbb110ffa"
> --- FAIL: TestNewRCRelease (44.71s)
>     changelog_test.go:202: 
>         	Error Trace:	changelog_test.go:202
>         	Error:      	Expected nil, but got: no latest tag available for branch release-1.16
>         	Test:       	TestNewRCRelease
> Cloning into '/tmp/k8s-test/base-1584499018'...
> ```

This should be fixed with https://github.com/kubernetes/release/pull/1187

**Comment by hasheddan** [comment]
Opened https://github.com/kubernetes/release/pull/1192 to address

**Comment by hasheddan** [comment]
I have not observed a flake here since the dashboard was moved to https://testgrid.k8s.io/sig-release-releng-presubmits#release-test

Going to go ahead and close this out until we encounter new flakes.

/close
