### ISSUE TITLE
Implement  `--logging-format` flag in k8s.io/component-base

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#89190]
**What would you like to be added**:
As part of [Structured Logging KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20191115-structured-logging.md) k8s.io/component-base should add logging configuration allowing to change logging implementation.

Things to implement:
* --logging-format - flag to pick between available implementations. Defaults to "text" using unchanged klog.
* LoggingConfig - structure storing component configuration for logging 
* LogFormatRegistry - Used for registration of additional log formats. New formats should be registered by providing unique name and implementation of https://github.com/go-logr/logr interface

LoggingConfig.Complete method should configure klog by passing logr interface implementation into klog.SetLogger method

**Why is this needed**:
Subtask of https://github.com/kubernetes/enhancements/issues/1602

/help
/wg component-standard

**Comment by yuzhiquan** [comment]
/assign
have a try

**Comment by yuzhiquan** [comment]
@serathius  The klog 1.0.0 version  looks like no SetLogger method, should update klog version in vendor?

**Comment by serathius** [comment]
@yuzhiquan yes, forgot about that. I remember @44past4 saying that it will require some changes, but shouldn't be to hard. I will help with it if needed.

**Comment by serathius** [comment]
Klog was upgraded to v2.
