### ISSUE TITLE
Failed to execute rolling update if resource quota is full.

### ISSUE THREAD

**Issue by zhangdb-git** [kubernetes/kubernetes#89209]
**What happened**:
Resourcequota limits deployments to upgrade.

**How to reproduce it**:
1. Create a new namespace.
2. Create a resourcequota in the namespace, allow only one pod.
3. Create a deployment with one replica in the namespace, and set upgrade-method to be "RollingUpdate".
4. Edit the image value of the deployment.
5. Watch the result of update. A new replicaset was created with errors as follows and new pod can not be created:
```
Error creating: pods "test-c5d48877d-z2x6r" is forbidden: exceeded quota: rqtest, requested: pods=1, used: pods=1, limited: pods=1
```

**Environment**:
- Kubernetes version: v1.14.6

**Comment by fengzixu** [comment]
Actually, I don't think the behavior you mentioned is a kind of bug of kube-scheduler. RollingUpdate strategy means it will create a new pod and start to terminate the old at the same time.

I'm not sure why you want to set the resource quota for only one pod. If it is your testing behavior,  I think you need to consider the upgrade function.

**Comment by zhangdb-git** [comment]
@fengzixu, hello, as I know, it will not start to terminate the old pod before the new one is ready.

**Comment by ahg-g** [comment]
/remove-sig scheduling 

the scheduler doesn't enforce quotas.
