### ISSUE TITLE
test/e2e/framework depends on scheduler framework

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#89229]
/kind cleanup
/sig scheduling

In `test/e2e/framework/.import-restrictions` we allow `pkg/scheduler/framework/v1alpha1` along with some plugins.
The dependency on `pkg/scheduler/framework/v1alpha1` is particularly odd and it implies that any dependency (possibly internal) we add to this package will have to be added to the restrictions file (See #89070 for example).

I've managed to clean up some dependencies. However, the hardest to clean up comes through `test/e2e/framework/providers/kubemark`. This has to instantiate a full kubelet, which in turn requires scheduler plugins to check for some conditions in the node.

The questions then are:

1. Should kubelet depend on plugins code? If not, we can move the necessary code out of the plugins folder into a more general package.
1. Should kubelet depend on the framework implementation? If not, we can split the framework implementation in 2 packages: one that provides support for plugins (like the framework handle and the framework types) and one that provides the framework runtime (functions such as `RunPreFilterPlugins`).

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei

**Comment by Huang-Wei** [comment]
> However, the hardest to clean up comes through test/e2e/framework/providers/kubemark. This has to instantiate a full kubelet

This sounds odd to me as kubemark was created to simulate a kubelet without any concrete logic inside. It's also known as "hollow node".

**Comment by alculquicondor** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
> This sounds odd to me as kubemark was created to simulate a kubelet without any concrete logic inside. It's also known as "hollow node".

This isn't true - we're using the real kubelet logic. We're trying to fake as little as possible (in particular we're faking the container runtime underneath and volume manager). We're trying to repliace this logic. And this by-design, as thanks to it we simulate the load to apiserver much more accurate.

**Comment by alculquicondor** [comment]
In that case, the kubemark->kubelet->scheduler dependency should remain there, as it is used to verify resource usage, tolerations and other node-specific constraints.

**Comment by ahg-g** [comment]
> Should kubelet depend on the framework implementation? If not, we can split the framework implementation in 2 packages: one that provides support for plugins (like the framework handle and the framework types) and one that provides the framework runtime (functions such as RunPreFilterPlugins).

But that doesn't improve things too much, the package that "provides support for plugins" will still need to be included in the import-restrictions file of kubemark, right?

**Comment by alculquicondor** [comment]
Yes, but that's a more limited package with less dependencies, as opposed to the framework "runtime".

That said, that might not be as important as long as test owners don't push back on imports we keep adding.

**Comment by Huang-Wei** [comment]
My 2 cents is to move out the shared functions in individual plugin (pkg/scheduler/framework/plugins) where that plugin itself depends on pkg/scheduler/framework/v1alpha1.

Take the kubemark for example, the full dependency chain is:

```
/test/e2e/framework/providers/kubemark
/pkg/kubemark
/pkg/kubelet/cm
/pkg/kubelet/lifecycle
/pkg/scheduler/framework/plugins/noderesources
/pkg/scheduler/framework/v1alpha1
```

So we can move `pkg/scheduler/framework/plugins/noderesources/fit.go#Fits()` to some common place to eliminate the indirect dependency from /test/e2e/framework/providers/kubemark to /pkg/scheduler/framework/v1alpha1.

**Comment by alculquicondor** [comment]
Yeah, that was my idea (from question 1).

More generally, I think those calculations could even be outside of both the scheduler and kubelet code. But living somewhere outside of `pkg/scheduler/framework/plugins` should be a good enough solution for now.

**Comment by alculquicondor** [comment]
On the other hand, you could say that kubelet should (instead) instantiate a framework and run the plugins it needs from there. Then we can't really solve this problem until we decide to move the framework to staging.
