### ISSUE TITLE
TestNominatedNodeCleanUp is flaky

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#89259]
**Which jobs are flaking**:

pull-kubernetes-integration

**Which test(s) are flaking**:

TestNominatedNodeCleanUp

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89162/pull-kubernetes-integration/1240643459644133376

**Reason for failure**:

```
preemption_test.go:933: The nominated node name of the medium priority pod was not cleared: timed out waiting for the condition
```

/sig scheduling

**Comment by ahg-g** [comment]
@fengzixu any progress on this one?

**Comment by fengzixu** [comment]
> @fengzixu any progress on this one?

@ahg-g  I was working on it and tried to find the root cause. I will give my solution within this week

**Comment by alculquicondor** [comment]
Another one https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89070/pull-kubernetes-integration/1242466748452573184

**Comment by alculquicondor** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90475/pull-kubernetes-integration/1255139243836051457

Still happening

cc @pancernik

**Comment by alculquicondor** [comment]
/close
dupe #90627
