### ISSUE TITLE
SSA: `kubectl apply --server-side` should not client-side validate

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#89266]
Since some of the objects applied may not be fully valid, we should disable validate by default.

**Comment by apelisse** [comment]
/assign @julianvmodesto 

I think that's a one-liner.

**Comment by apelisse** [comment]
On the other hand, server-side apply doesn't fix the thing that `--validate` was intending to fix (which is mostly to detect misspelled key fields), so I'm not sure why we would disable it. Also, I can't remember why I opened this issue in the first place, is that a real-life example? Let's wait to see more proof of that.

**Comment by julianvmodesto** [comment]
Seems related to https://github.com/kubernetes/kubernetes/issues/39434

**Comment by julianvmodesto** [comment]
Oh yeah this is related to moving validation server-side. I'm not sure if we get to this yet and how much of this we do now

**Comment by apelisse** [comment]
I'd like to see evidence that we need this. People, feel free to re-open!
