### ISSUE TITLE
kube-proxy should treat failure to bind to a port as fatal

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#89265]
**What would you like to be added**:

If kube-proxy fails to bind to MetricsBindAddress or HealthzBindAddress, it either retries forever in the background or never tries again (respectively).

Both of these should probably be considered fatal, but that would turn a "soft" fail into a "hard" fail, and very likely there are people out there living with the soft fail, so we can't break them.

We can probably add a new config to turn those into hard-fails, and make that opt-in.

Healthz should probably retry, too, when it's not a hard fail.

**Comment by eddiezane** [comment]
Newbie here. I'd love to take a stab at this one.

@thockin I didn't test manually but looking at (what I believe is) the code it seems that both Metrics and Healthz have the same retry logic with `wait.Until` ... `wait.NeverStop`.

Thoughts?

https://github.com/kubernetes/kubernetes/blob/2c8ef3b19d5b3c1fda0123912e6cd2d1feac7427/cmd/kube-proxy/app/server.go#L618-L623

https://github.com/kubernetes/kubernetes/blob/2c8ef3b19d5b3c1fda0123912e6cd2d1feac7427/pkg/proxy/healthcheck/proxier_health.go#L101-L119

**Comment by vllry** [comment]
Linked PR appears to address this, closing.

/close
