### ISSUE TITLE
Remove kubescheduler.config.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#89260]
/sig scheduling
/kind cleanup

As we get ready to move to beta, we should first get rid of the v1alpha1 API to reduce maintenance cost.

In particular, this would free us from having to maintain Algorithm Source.

Before I open this for contributors, I would like to know if there are any concerns.

**Comment by Huang-Wei** [comment]
+1. It's a common practice to only keep one alpha release to reduce maintenance efforts, such as kubeadm componentconfig API.

**Comment by neolit123** [comment]
SGTM.

removing v1alpha1, before the beta is out agrees with the table under:
https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api
see:
> v1alpha1 is removed, "action required" relnote

for kubeadm's component config we kept them for a while longer and did not following this guide exactly:

alpha1,2,3 existed at the same time:
https://github.com/kubernetes/kubernetes/tree/release-1.12/cmd/kubeadm/app/apis/kubeadm

alpha1,2 were both removed with the release of beta1; alpha3 was kept:
https://github.com/kubernetes/kubernetes/tree/release-1.13/cmd/kubeadm/app/apis/kubeadm

**Comment by gavinfish** [comment]
Hi all, I want to have a try to get familiar with kubernetes api. Is there anything (documents or general commands) I should know before I start the work.

I think this should be similar with #69055

/assign

**Comment by gongguan** [comment]
> Is there anything (documents or general commands) I should know before I start the work.

Ref [87628](https://github.com/kubernetes/kubernetes/pull/87628) which add v1alpha2, you can remove v1alpha1 conversely.
