### ISSUE TITLE
serverside apply: delete dropped fields

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#89273]
I used `args` for my container in a Deployment (via SSA). Then I discovered that I'd screwed up the entrypoint in my container, and switched to use `command`. SSA retained the `args`, which is NOT what I expected to happen.

A counter example where the existing behavior is correct: if I delete spec.replicas, I expect that field to retain its value (probably HPA will start setting it or something).

I believe the distinction is "gets a default". Fields that can't not have a value (i.e., are required and/or defaulted) should be retained; fields that are truly optional should be deleted completely. List & map items behave like the latter.

/sig api-machinery
/wg apply

**Comment by lavalamp** [comment]
In the bug triage meeting we flagged this as worth a bigger discussion. Maybe to be hosted by WG Apply?

- a collection of cases for evaluating how well various rules (like the one I suggested) capture human intuition would be very helpful
- hopefully we don't need to make the API author declare the behavior, but maybe?
- @deads2k brought up the case of controllers that want to hand-off fields between each other, without risking intermediate deletion; making the order matter (new claims first, then old relinquishes) might be unfortunate.

**Comment by apelisse** [comment]
I'm happy to be wrong with the following, it's up for debate. It's describing how I've considered things so far, not how I'll consider them for the rest of time :-)

> List & map items behave like the latter.

My understanding is that these are different because the set of possible "key" is not properly defined, which is different from other fields (including args, which you know exist by looking at the openapi).

The reality of your example above is that you *WANT* args to be empty, so you probably should specify it as empty in your config. In my opinion, the problem you have is that it's hard to detect that the field you just removed is still impacting your objet.

> capture human intuition

That sounds complicated ;-)

**Comment by lavalamp** [comment]
> The reality of your example above is that you WANT args to be empty, so you probably should specify it as empty in your config

Interesting take, but since the default is to have nothing there, it makes the live object depend on history-- should I also explicitly specify all the other features I don't want to use?

**Comment by apelisse** [comment]
It does depend on history, I think we should fix that problem by making it obvious to people.

> should I also explicitly specify all the other features I don't want to use?

I want to say yes, but I see how it's neither doable nor desirable. 

There's probably a spectrum "I don't care about this value", "I expect the default to do the right thing" "if something/someone changes this, I'm probably fine" and "if this field changes, my app is completely broken".

Some examples of these would be:
- You probably don't care about most environment variables,
- I'm almost certain that you expect your DeploymentStrategy to be roll-out, not recreate
- quotas for CPU and memory are not great, and they can certainly be changed

I'm not sure you have a super super strong opinion about any of these, if they change, things will probably still work to varying degrees.

**Comment by lavalamp** [comment]
Quotas specifically I expect the system to magically figure out for me (eventually).

If I remove an env var, I definitely expect it to go away--that could break my app otherwise. If someone else adds one, though, that's fine (e.g. HTTPS_PROXY)

**Comment by apelisse** [comment]
Should be fixed by #92661

**Comment by jpbetz** [comment]
Yes, this is fixed by #92661 and the docs changes in https://github.com/kubernetes/website/pull/22412
