### ISSUE TITLE
Windows volume mounts failing in 1.18.0-rc.1

### ISSUE THREAD

**Issue by mboersma** [kubernetes/kubernetes#89276]
**What happened**:
#88684 changed to the `MountSensitive` call but may not have made enough changes. We identified a problem in AKS Engine testing where a Windows volume is never mounted succesfully.

**What you expected to happen**:
Volume is mounted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Mount a volume from a pod on a Windows node. As we read the new code, this should fail consistently (and it does in our tests).

**Anything else we need to know?**:
We have a potential fix that changes five references to `options` to `sensitiveOptions` that appears to fix this behavior. PR incoming.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.0-rc.1
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

cc: @kkmsft @marosset @jackfrancis @andyzhangx

**Comment by andyzhangx** [comment]
I verified that code change only on Linux, I think one problem is that we don't have windows disk e2e test now,
@chewong is working on this:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/320#issuecomment-601479600
Once we have windows e2e test, we should not have such regression issue.

**Comment by andyzhangx** [comment]
And @mboersma could you share the fix? I could take a look, thanks.

**Comment by mboersma** [comment]
@andyzhangx kubernetes/utils#148 seems to fix it. The unit tests in kubernetes/utils passed before and after the change, so I think we need coverage at that level too.

**Comment by alejandrox1** [comment]
>  I think one problem is that we don't have windows disk e2e test now,

Hi all, is there an existing issue to track the creation/addition of said tests?

**Comment by marosset** [comment]
@alejandrox1 I just created a new issue for this.

**Comment by justaugustus** [comment]
> @alejandrox1 I just created a new issue for this.

xref: https://github.com/kubernetes/kubernetes/issues/89307

**Comment by andyzhangx** [comment]
Need to point out that azure disk and azure file drivers are the only two **in-tree** drivers supports disk and smb mount on windows, we need to add windows e2e tests for these two drivers now.
This will also benefit other CSI drivers which would support disk and smb mount on windows soon.
cc @jingxu97

**Comment by alejandrox1** [comment]
Hi all, first off, thank you to everyone for working on this!

Figure I drop a quick comment for openness and transparency.
The planned release date for Kubernetes 1.18 is next Tuesday (March 24).
This issue is critical to the use of windows in 1.18 and we [the release team] are considering this work release blocking and will keep on syncing with you all to ensure this gets into 1.18.0.

Right now it seems that the way to help make sure that happens is to push back the release a day or two but I guess right now let's wait and see how things go. Will have a better plan by Monday.
Again, thank you everyone for all the work you do!

**Comment by andyzhangx** [comment]
@alejandrox1 here is the fix we need to get into v1.18.0:
https://github.com/kubernetes/kubernetes/pull/89319
cc @saad-ali
