### ISSUE TITLE
Wake a node on Lan

### ISSUE THREAD

**Issue by Jarnek** [kubernetes/kubernetes#89271]
Hey guys,
I would like to use kubernetes on my home server to run applications like nextcloud or teamspeak.
My current setup is a raspberry pi as master and a hp server as worker. The issue is the amount of power the hp consumes. Is it possible to set the whole worker node asleep or even shut it down while there are no requests and wake it up again via WOL if needed?

**Comment by neolit123** [comment]
i do not believe this has been requested before, but it's interesting.
possibly some managed solutions already do that to preserve resources.

/kind feature

**Comment by praseodym** [comment]
This could probably be implemented by writing a custom [Cluster Autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) provider, where scaling up is done by Wake-on-LAN and scaling down by putting a node to sleep.

**Comment by vanakema** [comment]
I'd LOVE this as a feature.

**Comment by MayeulC** [comment]
Has anyone attempted this yet? It would be interesting to have a low-power server, and a high-power backup sitting in S3, available at <1s notice.

The cluster-autoscale approach sounds interesting.

**Comment by rektide** [comment]
/reopen

awesome idea terrible bot

**Comment by johnlettman** [comment]
This is an excellent idea for those working to limit their resource consumption at different scales. Please consider reopening it.
