### ISSUE TITLE
It is dangerous to call os.RemoveAll() when saveVolumeData() fails is csi NewMounter()

### ISSUE THREAD

**Issue by fankangbest** [kubernetes/kubernetes#89281]
**What happened**:
When saveVolumeData() fails，dataDir is removed, and all data is gone.
``` go
	if err := saveVolumeData(dataDir, volDataFileName, volData); err != nil {
		if removeErr := os.RemoveAll(dataDir); removeErr != nil {
			klog.Error(log("failed to remove dir after error [%s]: %v", dataDir, removeErr))
		}
		return nil, errors.New(log("failed to save volume info data: %v", err))
	}

	klog.V(4).Info(log("mounter created successfully"))
```
This bug will happen when saveVolumeData() fails(in our environment, the disk is readonly). And the code is introduced in 2018. So most of the k8s environments are in the threaten of this bug.

**What you expected to happen**:
The data in mount point shouldn't be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
What problem did you encounter w.r.t. the code cited above ?

thanks

**Comment by jim3ma** [comment]
@tedyu 
When encounter error, all files in `mount` directory will be deleted.

Step 1, csi mount ok
Step 2, kubelet restart, and call those code
Step 3, encounter error(disk quota exceed or disk readonly and so on), clean all data in csi mount.

**Comment by fankangbest** [comment]
@vladimirvivien Do you known the reason why to call os.RemoveAll() when saveVolumeData() fails?

**Comment by k2huang** [comment]
From my point of view, I suggest to directly return error if `saveVolumeData` failed, because it seems calling os.RemoveAll or os.Remove is meaningless. And more, in fact we don't really need save volume data file every time if there is no changed contents.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
cc @gnufied
