### ISSUE TITLE
(Dual Stack Env) Kube Proxy in IPVS Mode not removing scale down pods entries from ipvsdm list for ipv6 address.

### ISSUE THREAD

**Issue by Abhishek1121-tech** [kubernetes/kubernetes#89294]
Kernel Version:             3.10.0-957.el7.x86_64
  OS Image:                   Red Hat Enterprise Linux Server 7.6 (Maipo)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.6
  Kubelet Version:            v1.17.2
  Kube-Proxy Version:         v1.17.2
  Networking calico             v3.11.2
[
\
![Screenshot from 2020-03-20 16-36-22](https://user-images.githubusercontent.com/62426428/77158494-6f824300-6ac9-11ea-98eb-9b0fd951223c.png)
![Screenshot from 2020-03-20 16-37-54](https://user-images.githubusercontent.com/62426428/77158495-701ad980-6ac9-11ea-8df0-cc0038f533ea.png)
![Screenshot from 2020-03-20 16-39-23](https://user-images.githubusercontent.com/62426428/77158496-714c0680-6ac9-11ea-9f59-30753f949513.png)

In the attachments, the ipv6 entries are not removed after scaling down the pods and for ipv4 address everything looks fine.
Please help on this.
](url)

**Comment by uablrek** [comment]
This is a bug. It is fixed in v1.18. I will post a ref to the issue when I find it.

/kind bug

**Comment by uablrek** [comment]
Fixed by this PR https://github.com/kubernetes/kubernetes/pull/87695.

Since ipv6-only and dual-stack are in alpha this will not be back-ported to v1.17, please see comments in the PR above.

I try to close this issue
/close

**Comment by uablrek** [comment]
I tested on 'v1.18.0-rc.1' btw.

**Comment by Abhishek1121-tech** [comment]
So, officially available on which version.

**Comment by uablrek** [comment]
It will be in v1.18 when it is released. I think it's soon since rc.1 is out;
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md
