### ISSUE TITLE
Enable disk/mount e2e tests on Windows

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#89307]
**What would you like to be added**:
Increase e2e test coverage for mounting disks on Windows nodes.

**Why is this needed**:
Currently e2e disk tests only test Linux.
We need this coverage to catch regressions like https://github.com/kubernetes/kubernetes/issues/89276

cc @kkmsft @jackfrancis @andyzhangx @chewong 
/sig windows
/kind test

**Comment by andyzhangx** [comment]
related PR to fix this issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/320

**Comment by andyzhangx** [comment]
/assign @chewong
cc @ritazh @craiglpeters

**Comment by chewong** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/16877.
/close

**Comment by marosset** [comment]
Thanks @chewong!
