### ISSUE TITLE
Incorrect command suggestion in kubectl exec deprecation message

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#89301]
**What happened**:

```
% kubectl exec iso -it -c nginx echo foobar
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
foobar

% kubectl kubectl exec iso -it -c nginx -- echo foobar
Error: unknown command "kubectl" for "kubectl"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.0.960+ede025af1b54ee", GitCommit:"ede025af1b54ee20c0abbce553a5b15ef31225f8", GitTreeState:"clean", BuildDate:"2020-03-20T12:56:36Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by maxcanna** [comment]
Fixed in #89919
