### ISSUE TITLE
Azure VMSS is not added to internal SLB backend address pool

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#89336]
**What happened**:

When using Internal Standard LoadBalancer on Azure, although VMSS instances have been added to LB backend address pools, the VMSS itself is not added. Hence, if customer upgrades these VMSS instances to latest model, the backend address pool would be lost and hence the LoadBalancer services would be broken.

**What you expected to happen**:

Azure VMSS is also added to internal SLB backend address pool automatically.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cloud-provider
/kind bug
/priority critical-urgent
/area provider-azure

**Comment by porrascarlos802018** [comment]
Can you share some insights when this could be get fixed?
