### ISSUE TITLE
Kubelet refers to old device path and does not mount the volume from new device path

### ISSUE THREAD

**Issue by princerachit** [kubernetes/kubernetes#89330]
**What happened**:
1. I created an EBS volume
1. I created a job which uses this ebs volume as `awsElasticBlockStore`
1. Job's pod ran to completion.
1. I created another deployment with above EBS volume reference (Utilizing PV/PVC this time and NOT awsElasticBlockStore ). This was done using a script therefore there was virtually no delay b/w the steps
1. The pod of the deployment does not transition from `ContainerCreating` state as it could not mount the volume
```
  Normal   SuccessfulAttachVolume  12m (x2 over 12m)   attachdetach-controller                             AttachVolume.Attach succeeded for volume "test-persistentvolume-a2a3d028"
  Warning  FailedMount             2m40s               kubelet, ip-172-20-60-8.us-east-2.compute.internal  MountVolume.WaitForAttach failed for volume "test-persistentvolume-a2a3d028" : could not find attached AWS Volume "aws://us-east-2a/vol-033642b25e8512c14". Timeout waiting for mount paths to be created
```
**What you expected to happen**:
Volume to be mounted to pod successfully within few seconds.

**How to reproduce it (as minimally and precisely as possible)**:
Refer to *What Happened* section

**Anything else we need to know?**:
The EBS vol was attached to the instance at device path `/dev/xvdcx` when the job requested to use it. It was unmounted and detached successfully after the job completed. It was reattached at path `/dev/xvdcs` the second time, i.e. when the deployment was created. However, 2 strange things happened:- 
1. kubelet was still referring to old device path
2. The device was not mounted by kubelet.

I was able to mount the volume successfully manually.

Note: *The logs might seem off as I have masked some text in an unconsistent manner.*
**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-172-20-37-140 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```
- Install tools: `kops`
- Network plugin and version (if this is a network-related bug):
- Others:
[debug-dmesg.log](https://github.com/kubernetes/kubernetes/files/4363075/debug-dmesg.log)
[debug-fdisk.log](https://github.com/kubernetes/kubernetes/files/4363076/debug-fdisk.log)
[debug-kubelet.log](https://github.com/kubernetes/kubernetes/files/4363077/debug-kubelet.log)
[debug-pod-describe.log](https://github.com/kubernetes/kubernetes/files/4363078/debug-pod-describe.log)

**Comment by gnufied** [comment]
This looks like similar to https://github.com/kubernetes/kubernetes/issues/77949 which we fixed. Unfortunately the fix is not available in 1.14. Can you try with 1.15 and let us know?

**Comment by princerachit** [comment]
closing this issue as I was not able to reproduce it in the newer release. Thanks for your help @gnufied

**Comment by princerachit** [comment]
I have hit this issue again, this time with kubernetes 1.16
```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gnufied** [comment]
@princerachit can you post controller-manager and kubelet logs from 1.16?

**Comment by princerachit** [comment]
@gnufied it will take me sometime to get the kube controller manager logs, and then mask the  confidential data.

Here is the masked log of kubelet:

[prince-debug-kubelet.log](https://github.com/kubernetes/kubernetes/files/5085307/prince-debug-kubelet.log)

**Comment by princerachit** [comment]
I don't see anything useful in kube-controller-manager logs other than this getting repeated with other node dns 
```
I0815 05:03:56.690515       1 route_controller.go:295] set node ip-172-20-11-192.us-west-2.compute.internal with NodeNetworkUnavailable=false was canceled because it is already set
```
