### ISSUE TITLE
Get CRD resource in Plugin of Scheduler Framework

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes/kubernetes#89344]
I'm checking the [Scheduler Framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md) and try to implement based on that.

I wonder to know what should I do if I try to get CRD resource in a plugin. what's the best practice?
BTW, I notice this feature is still on alpha phase, what's the next plan?
and I think we need more example, document to make it easy to adopt, thanks.

**Comment by angao** [comment]
You can create a CRD clientset and use the follows method to register plugin:
```
clientset := createClient(...)
app.NewSchedulerCommand(
    app.WithPlugin(sample.Name, func(_ *runtime.Unknown, _ framework.FrameworkHandle) (framework.Plugin, error) {
        return sample.New(clientset), nil
    }),
)
```

**Comment by vincent-pli** [comment]
@angao 
Thanks, I saw your example for `Scheduler Framework` on github, very useful.
What do you think about `Scheduler Framework`, is that ready for adopt now?  any plan for supply more guide line?

**Comment by angao** [comment]
v1.18 is coming soon, maybe that is a chance. The document is being planed.

**Comment by alculquicondor** [comment]
It seems that the question was answered.

/close

**Comment by alculquicondor** [comment]
Btw, this repository is meant to have samples and common plugins, but it's still in construction
https://github.com/kubernetes-sigs/scheduler-plugins
