### ISSUE TITLE
Updating imageRepository and kubeadm config upgrade does not update registry for etcd

### ISSUE THREAD

**Issue by jeanluclariviere** [kubernetes/kubernetes#89366]
**What happened**:
I'm switching a kubeadm initialized cluster to use a private repo via the imageRepository key in the kubeadm-config.

**What you expected to happen**:
I expect all control plane images to use the new repo and for those pods to be re-created and pull down the images via the private repo.

After modifying the kubeadm-config.yaml file i've created, i run the command: `kubeadm upgrade apply --config kubeadm-config.yaml -f` and the cluster performs the change.

Afterwards, if i run the command `kubectl describe pods -n kube-system | grep Image:`, i see the following:

<pre>
λ kubectl describe pods -n kube-system | grep Image:
    ...
    Image:         my.repo.com:9999/coredns:1.6.2
    Image:         my.repo.com:9999/coredns:1.6.2
    <b>Image:         k8s.gcr.io/etcd:3.3.15-0</b>
    Image:         my.repo.com:9999/kube-apiserver:v1.16.4
    Image:         my.repo.com:9999/kube-controller-manager:v1.16.4
    Image:         my.repo.com:9999/kube-proxy:v1.16.4
    Image:         my.repo.com:9999/kube-proxy:v1.16.4
    Image:         my.repo.com:9999/kube-proxy:v1.16.4
    Image:         my.repo.com:9999/kube-scheduler:v1.16.4
</pre>

**How to reproduce it (as minimally and precisely as possible)**:
1. sudo kubeadm config view > kubeadm-config.yaml
2. edit kubeadm-config.yaml and replace k8s.gcr.io with your repo
3. sudo kubeadm upgrade apply --config kubeadm-config.yaml

**Anything else we need to know?**:
I'm lead to believe this is a bug because if I perform the following command: `kubeadm config images list --image-repository my.repo.com:9999` we can see that etcd is listed with the new repo name - and if i were to perform a pull it would pull down etcd from the private repo as well.

<pre>
$ kubeadm config images list --image-repository my.repo.com:9999
I0323 08:38:13.452370   30381 version.go:251] remote version is much newer: v1.17.4; falling back to: stable-1.16
my.repo.com:9999/kube-apiserver:v1.16.8
my.repo.com:9999/kube-controller-manager:v1.16.8
my.repo.com:9999/kube-scheduler:v1.16.8
my.repo.com:9999/kube-proxy:v1.16.8
my.repo.com:9999/pause:3.1
<b>my.repo.com:9999/etcd:3.3.15-0</b>
my.repo.com:9999/coredns:1.6.2
</pre>

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15.5
- Cloud provider or hardware configuration:
on-prem, virtualized
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
- Kernel (e.g. `uname -a`):
3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
canal
- Others:

**Comment by neolit123** [comment]
/area kubeadm
/triage needs-information

please show the contents of:
- `kubectl get cm -n kube-system kubeadm-config -o yaml`
and also:
- kubeadm-config.yaml

note that adding `--config` to the `kubeadm upgrade *` commands is going to be deprecated in the future. you should let kubeadm upgrade without reconfiguring the cluster.

**Comment by jeanluclariviere** [comment]
> kubectl get cm -n kube-system kubeadm-config -o yaml

```
$ kubectl get cm -n kube-system kubeadm-config -o yaml
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager: {}
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: my.repo.com:9999
    kind: ClusterConfiguration
    kubernetesVersion: v1.16.4
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    scheduler: {}
  ClusterStatus: |
    apiEndpoints:
      vtorcordv01:
        advertiseAddress: x.x.x.x
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-08T21:35:15Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "9001918"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
  uid: c7b86ba7-b3a3-4659-9d02-651b41b9b6fd
```

> kubeadm-config.yaml

```
$ kubeadm config view
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: my.repo.com:9999
kind: ClusterConfiguration
kubernetesVersion: v1.16.4
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
```

**Comment by jeanluclariviere** [comment]
> note that adding --config to the kubeadm upgrade * commands is going to be deprecated in the future. you should let kubeadm upgrade without reconfiguring the cluster.

What would be the recommended approach for updating the kubeadm config post initialization in this case?

**Comment by neolit123** [comment]
your configuration looks fine.

if you have to customize the image / repository under the `etcd:` field in the CLusterConfiguration, then kubeadm will pick the `imageRepository: my.repo.com:9999` instead.

questions:
- have you previously upgraded this cluster from older versions e.g. 1.14->15->16?
- what happens if you don't pass `--config` to `upgrade plan`?

> What would be the recommended approach for updating the kubeadm config post initialization in this case?

manually editing the `kubeadm-config` ConfigMap in the cluster.

**Comment by jeanluclariviere** [comment]
I'll also add that if i look in the `/etc/kubernetes/manifest` directory, all of the files have been updated except etcd:

<pre>
$ sudo cat kube-*.yaml etcd.yaml | grep image:
    image: my.repo.com:9999/kube-apiserver:v1.16.4
    image: my.repo.com:9999/kube-controller-manager:v1.16.4
    image: my.repo.com:9999/kube-scheduler:v1.16.4
    <b>image: k8s.gcr.io/etcd:3.3.15-0</b>
</pre>

**Comment by neolit123** [comment]
```
kubectl describe pods -n kube-system | grep Image:
    ...
    Image:         my.repo.com:9999/coredns:1.6.2
    Image:         my.repo.com:9999/coredns:1.6.2
    Image:         k8s.gcr.io/etcd:3.3.15-0
```

do you recall why the etcd image has a different registry in the existing Pod?

**Comment by jeanluclariviere** [comment]
to answer your questions:

> have you previously upgraded this cluster from older versions e.g. 1.14->15->16? 
That is correct

> what happens if you don't pass --config to upgrade apply?
I'll try this now and update the new post - thanks for your assistance.
