### ISSUE TITLE
`localtime`, `rsyncd.password` and `rsyncd.sh` don't exist when building Kubernetes

### ISSUE THREAD

**Issue by zzxwill** [kubernetes/kubernetes#89362]
**What happened**:
Following instruction [Building Kubernetes](https://github.com/kubernetes/kubernetes/blob/0641e0c6d809fa6bdb23d6f76c86ab4b31009d94/build/README.md#basic-flow) to build docker image, it said `localtime`, `rsyncd.password` and `rsyncd.sh` don't exist.
```
[root@iZj6car9k56yp0slyk2788Z build-image]# pwd
/go/src/k8s.io/kubernetes/build/build-image

[root@iZj6car9k56yp0slyk2788Z build-image]# docker build -t kube-build .
Sending build context to Docker daemon 17.41 kB
Step 1/14 : FROM us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.13.9-2
 ---> 5240c28f18e5
Step 2/14 : RUN touch /kube-build-image
 ---> Using cache
 ---> a36ebc654f6e
Step 3/14 : RUN chmod -R a+rwx /usr/local/go/pkg
 ---> Using cache
 ---> bdeacb9d6d73
Step 4/14 : RUN mkdir /var/run/kubernetes && chmod a+rwx /var/run/kubernetes
 ---> Using cache
 ---> 095742d61e31
Step 5/14 : ENV HOME /go/src/k8s.io/kubernetes
 ---> Using cache
 ---> 0dcfd6cc400e
Step 6/14 : WORKDIR ${HOME}
 ---> Using cache
 ---> 6ee139045385
Step 7/14 : ENV KUBE_OUTPUT_SUBPATH _output/dockerized
 ---> Using cache
 ---> 331b8e1540dd
Step 8/14 : ENV KUBE_GIT_VERSION_FILE ${HOME}/.dockerized-kube-version-defs
 ---> Using cache
 ---> 196adacb7006
Step 9/14 : RUN git config --system user.email "nobody@k8s.io"   && git config --system user.name "kube-build-image"
 ---> Using cache
 ---> ef6c1bd454d2
Step 10/14 : RUN chmod -R a+rwx $GOPATH
 ---> Using cache
 ---> 550282d104fa
Step 11/14 : ADD rsyncd.password /
lstat rsyncd.password: no such file or directory
```

**What you expected to happen**:
Successfully build an image which can use to build Kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:
- `git clone https://github.com/kubernetes/kubernetes.git`
- `cd cd kubernetes/build/build-image/`
- `docker build -t kube-build .`

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`): In Kubernetes build stage, no version could be provided.
- Cloud provider or hardware configuration: Linux VM
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`): `Linux iZj6car9k56yp0slyk2788Z 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: NA
- Network plugin and version (if this is a network-related bug): NA
- Others: NA

**Comment by afrouzMashaykhi** [comment]
based on documentation you will run `build/run.sh` which build docker image in 
https://github.com/kubernetes/kubernetes/blob/0641e0c6d809fa6bdb23d6f76c86ab4b31009d94/build/run.sh#L26
line you will find another script which has build-image function
https://github.com/kubernetes/kubernetes/blob/0641e0c6d809fa6bdb23d6f76c86ab4b31009d94/build/common.sh#L417
in this function it will set localtime, rsyncd.sh and rsyncd.paasword
