### ISSUE TITLE
[Docs] Improve documentation for CRD/Structured merge diff integration

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes/kubernetes#89374]
This is possible for the wrong place to open this issue. If so please direct me where to put it. 

**Background** 

Kubernetes API server supports apply-patch https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/0006-apply.md  feature where under the hood CRD spec is parsed, appropriate `proto.Models` interface is created, and in combination with https://github.com/kubernetes-sigs/structured-merge-diff appropriate strategic merge patch is applied.

**Issue** 

What I'm currently trying to achieve is to use the strategic-merge-patch without the API server for arbitrary CRDs. Without CRD specific type information is easy, just using something like (minus the error handling):

```go
                var a, patch *unstructured.Unstructured
               ...
		a, err := typed.DeducedParseableType.FromUnstructured(a.Object)
		patch, err  := typed.DeducedParseableType.FromUnstructured(patch.Object)
                a.Merge(patch)
```

The hard thing is getting the right `TypedValue` from the https://github.com/kubernetes-sigs/structured-merge-diff package for the arbitrary CRD type knowing the openAPIv3 schema defined in the CRD. By looking through the API server code the following files/functions look promising, though a lot is going on:
 
* https://github.com/kubernetes/kubernetes/blob/0641e0c6d809fa6bdb23d6f76c86ab4b31009d94/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder.go#L89

builds the swagger definitions

* https://github.com/kubernetes/kubernetes/blob/0641e0c6d809fa6bdb23d6f76c86ab4b31009d94/staging/src/k8s.io/apiserver/pkg/util/openapi/proto.go#L31

it's involved in converting the openAPISpec to the proto.Models which other helper functions later convert to the right helper function converting `unstructured.Unstructured` to `*TypedValue`

* https://github.com/kubernetes/kubernetes/blob/0641e0c6d809fa6bdb23d6f76c86ab4b31009d94/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/typeconverter.go#L75  
is equally promising in getting from `proto.Models` to something I can use to convert `*unstructured.Unstructured` to `*typed.TypedValue`   (this function is unfortunately internal)

Thus have I understood the code correctly and I should do something like this instead?:

```go
                var a, patch *unstructured.Unstructured
                ...
		swag, err := builder.BuildSwagger(crd "v1alpha1", builder.Options{V2: false, StripDefaults: true, StripValueValidation: true, StripNullable: true, AllowNonStructural: true})
		models, err := openapi.ToProtoModels(swag)
		converter, err := (internal)NewTypeConverter(models, true)
		a, err := converter.ObjectToTyped(a)
		patch, err  := converter.ObjectToTyped(patch)
                a.Merge(patch)
```

**Comment by apelisse** [comment]
@jennybuckley is also working on a change to make things simpler, since it will convert schemas directly from structural to SMD: https://github.com/kubernetes/kubernetes/pull/87872.

**Comment by nmiculinic** [comment]
btw, what does SMD stands for?

**Comment by kwiesmueller** [comment]
Structured Merge Diff :-)

**Comment by apelisse** [comment]
We've actually made changes for that very recently: https://github.com/kubernetes/kubernetes/pull/97172

Could you take a look and see if it solves your problem?

**Comment by apelisse** [comment]
It's unclear what problem we're trying to solve here? Can you clarify?
