### ISSUE TITLE
v1.Extender.HTTPTimeout is a time.Duration

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#89396]
https://github.com/kubernetes/kubernetes/blob/2ab6357df0a513593b425f8abde6578687d44034/staging/src/k8s.io/kube-scheduler/config/v1/types.go#L210-L212

This requires specification as int64 nanoseconds so a one second timeout would need to be specified as 1000000000. It should be a metav1.Duration like other durations in the API but it's been like this since 1.2. Is anyone actually using this field?

**Comment by angao** [comment]
@alculquicondor WDYT? I can do this update if it is accepted.

**Comment by alculquicondor** [comment]
Any updates in here requires a new API version.
@mikedanese wasn't there a related issues already opened for this?
Can anybody work on a KEP?

**Comment by angao** [comment]
@alculquicondor  I can write a KEP for this.

**Comment by mikedanese** [comment]
@alculquicondor, not sure if there is a releated issue. I noticed it working on openapi stuff.

**Comment by alculquicondor** [comment]
Sorry, I confused you with @damemi who had done some work in 1.18 to make our API compliant.

**Comment by damemi** [comment]
@mikedanese should it be a `metav1.Duration`? Or an integer value? I've noticed in the API conventions that using `Duration` in the API isn't advised in order to keep compatibility with non-go clients (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#units)

**Comment by damemi** [comment]
(cross-ref to the open issue to improve the extender API: https://github.com/kubernetes/kubernetes/issues/88634)

**Comment by liggitt** [comment]
As a config API, this isn't served anywhere, so the only consumer is the go scheduler binary. Other config APIs use metav1.Duration or a plain integer with `seconds` in the field name to clarify the units.

**Comment by damemi** [comment]
Thanks @liggitt, I've been confused on what the distinction was

**Comment by alculquicondor** [comment]
We just fixed this for KubeSchedulerConfiguration (going for v1beta1 in 1.19) #91625

Once this is GA, the Policy API (which uses this Extender type) will be removed #92143
