### ISSUE TITLE
Chart requires kubernetesVersion: >=1.11.1 which is incompatible with Kubernetes v1.15.9-gke.9

### ISSUE THREAD

**Issue by arvera** [kubernetes/kubernetes#89404]
Error: Chart requires kubernetesVersion: >=1.11.1 which is incompatible with Kubernetes v1.15.9-gke.9

```
$ helm version
Client: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
**What happened**:
As I was trying to use helm 3.1.2 or 2.16.4, I get the error on the subject line

**What you expected to happen**:
I am not expecting to have a problem, as the version v1.15.9-gke.9 is > than 1.11.1

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): *see above*
- Cloud provider or hardware configuration: *gke*
- OS (e.g: `cat /etc/os-release`):  MACos Mojave 10.14.6

**Comment by lanycrost** [comment]
Hi @arvera

Your issue not relate to kubernetes it's helm issue.

Please review links:

https://github.com/helm/helm/issues/6190
https://github.com/helm/helm/issues/3810

**Comment by liggitt** [comment]
agree this is either a helm or a gke issue, not a kubernetes issue

/close
