### ISSUE TITLE
TestUnreservePlugin is flaky

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#89434]
**Which jobs are flaking**:
pull-kubernetes-integration

**Which test(s) are flaking**:
TestUnreservePlugin

Example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89270/pull-kubernetes-integration/1242471529611005952

/sig scheduling 
/help

**Comment by notpad** [comment]
I can't reproduce this failure in local env. And does this only happen for release-1.16 branch?

**Comment by ahg-g** [comment]
may be you are right, will close for now and monitor if this happens on master.

/close
