### ISSUE TITLE
Graduate PodTopologySpread to GA

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#89433]
Graduate PodTopologySpread to GA, the feature is currently in Beta, it was first introduced in 1.16 and since then no major changes happened to the feature.

/sig scheduling
/assign @Huang-Wei 
/milestone v1.19

**Comment by Huang-Wei** [comment]
## Items

- [ ] Optimize PodTopologySpread Filter #89665
- [x] Optimize preferred spreading for hostname topology #89487

**Comment by sftim** [comment]
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/895-pod-topology-spread#readme / https://github.com/kubernetes/enhancements/issues/895

**Comment by ahg-g** [comment]
/milestone v1.19

This is already done.

**Comment by liggitt** [comment]
all listed items are complete
