### ISSUE TITLE
Defining container resources limit implies resource requests

### ISSUE THREAD

**Issue by alemonmk** [kubernetes/kubernetes#89469]
**What happened**:
Basically what happens here: https://github.com/piraeusdatastore/piraeus/issues/19
Their deployment yaml has `resources.limits` defined, `resources.requests` not defined in *Sets, but `resources.requests` is defined in the created pods and they request same amount of resources as the limits.

**What you expected to happen**:
Limiting the resources usage should not reserve any resource.

**How to reproduce it (as minimally and precisely as possible)**:
Just defined a resource limit in any of your *Set.spec.template.spec.containers then see it pops up in your pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:
"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:
"linux/amd64"}
```
- Cloud provider or hardware configuration: Self-hosted vSphere
- OS (e.g: `cat /etc/os-release`): 
```
NAME=Fedora
VERSION="31.20200223.3.0 (CoreOS)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora CoreOS 31.20200223.3.0"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='31.20200223.3.0'
```
- Kernel (e.g. `uname -a`): `Linux RMNMVLABCNTAPS03 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Rancher RKE
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wawa0210** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

**Comment by alemonmk** [comment]
I'm new to k8s but is that mean there's nothing like "I don't keep a certain amount of resources for you and you can't get over certain limit", to do what I need is just specify a "minimal but more than zero" request?
