### ISSUE TITLE
Snapshots taken while a pod is using a PVC may result in inconsistent snapshot

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#89483]
I was reading snapshot documentation and it is missing the caveat that currently if user takes a snapshot of PVC that is being used in a Pod, it could result in inconsistent snapshot. 

/sig storage
cc @kubernetes/sig-storage-bugs

**Comment by Jainbrt** [comment]
Hi @gnufied, Could you please explain more of technical reason or any reference for detailed information on this problem statement?
