### ISSUE TITLE
Run RotateLogs function when there is disk pressure

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#89481]
**What would you like to be added**:
For ContainerLogManager, we can expose RotateLogs function and call it when there is disk pressure.

**Why is this needed**:
rotateLog() cleans up unused logs and removes excess logs.
This would free up disk space.

**Comment by tedyu** [comment]
Addresses:
```
	// TODO(random-liu): Add RotateLogs function and call it under disk pressure.
```

**Comment by karan** [comment]
Seems like the TODO is just stale?

https://github.com/kubernetes/kubernetes/blob/eb3405877799b770c72848c11aef967bda887eac/pkg/kubelet/logs/container_log_manager.go#L173

**Comment by tedyu** [comment]
The code you referenced is periodic.

This issue is about applying RotateLogs function when there is disk pressure.
