### ISSUE TITLE
go-to-protobuf: cannot use &v (type *int64) as type *int in assignment

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#89492]
**What happened**:
go-to-protobuf cannot handle int/*int fields.

**What you expected to happen**:
I would expect go-to-protobuf to do not generate something that does not build.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup the following example

- go.mod
```
module github.com/ialidzhikov/test-apiserver

go 1.13

require (
	github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
	golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7 // indirect
	k8s.io/api v0.17.4 // indirect
	k8s.io/code-generator v0.17.4
	k8s.io/kube-openapi v0.0.0-20200204173128-addea2498afe // indirect
)
```
- hack/tools.go
```golang
// +build tools

package tools

import (
	_ "k8s.io/code-generator"
	_ "k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo"
)
```

- pkg/apis/core/v1alpha1
```golang
package v1alpha1

type FooSpec struct {
	Count *int `json:"count,omitempty" protobuf:"varint,1,opt,name=count"`
}
```

```
$ go mod vendor; go mod tidy
```

2. Run `go-to-protobuf`
```
$ protoc --version
libprotoc 3.11.4

$ GOFLAGS="" go build -o ${GOPATH}/bin ./vendor/k8s.io/code-generator/cmd/go-to-protobuf
$ GOFLAGS="" go build -o ${GOPATH}/bin ./vendor/k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo

$ go-to-protobuf \
  --packages="github.com/ialidzhikov/test-apiserver/pkg/apis/core/v1alpha1" \
  --proto-import=./vendor
```

3. Ensure go build fails
```
$ go build ./...
# github.com/ialidzhikov/test-apiserver/pkg/apis/core/v1alpha1
pkg/apis/core/v1alpha1/generated.pb.go:223:12: cannot use &v (type *int64) as type *int in assignment
```

The generated proto message is with int64
```proto
message FooSpec {
  optional int64 count = 1;
}
```

and generated.pb.go tries to assign *int64 to *int which is a build error.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jpbetz** [comment]
`int` is not supported, so the bug is that we don't report that clearly in the generator. `*int32` or `*int64` can be used.

**Comment by ialidzhikov** [comment]
@jpbetz , can you add `lifecycle/frozen` label to this issue to prevent close from fejta-bot?

**Comment by aojea** [comment]
@ialidzhikov what is your expectation if `int` is not supported?

https://github.com/kubernetes/kubernetes/issues/89492#issuecomment-604687369

**Comment by ialidzhikov** [comment]
As written in the comment the generator can fail early and properly state that `int` is not supported instead of generating a code that does not build. This can be also documented in API conventions guideline (if not already documented) so people don't use `int` in their types.

**Comment by aojea** [comment]
> As written in the comment the generator can fail early and properly state that `int` is not supported instead of generating a code that does not build. 

Is not likely some maintainer is going to pick this checking the amount of times the bot commented, let's see if there are volunteers for this 

/help wanted

> This can be also documented in API conventions guideline (if not already documented) so people don't use `int` in their types.

this is already documented 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types

> All public integer fields MUST use the Go (u)int32 or Go (u)int64 types, not (u)int (which is ambiguous depending on target platform). Internal types may use (u)int.
