### ISSUE TITLE
DNS labels should handle more than 63 chars

### ISSUE THREAD

**Issue by tibers** [kubernetes/kubernetes#89495]
**What would you like to be added**:
Allow DNS label entries to contain up to 255 chars.

Per [RFC1123](https://tools.ietf.org/html/rfc1123#page-13) on Page 13:

> Host software MUST handle host names of up to 63 characters and
> SHOULD handle host names of up to 255 characters.

[K8s documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) states:

> Some resource types require their names to follow the DNS label standard as defined in RFC 1123. This means the name must:
> contain at most 63 characters

**Why is this needed**:
For private registries - I typically have `<FQDN>/<project>/<containername>:<tag>` and the FQDN eats about half my character allocation. I could get into games with A records and `search` in resolv.conf assuming I have some fully featured host environment, or CNAMEs, or all sorts of other DNS management tricks, or we could just decide to use 255 chars like "SHOULD" be permitted in the RFC.  I'm sure there's other k8s resources too which could benefit from what "SHOULD" be supported. :)

**Comment by liggitt** [comment]
The linked RFC defines DNS labels (individual segments of a hostname) to be limited to 63 characters:

> The DNS defines domain name syntax very generally -- a string of labels each containing up to 63 8-bit octets, separated by dots, and with a maximum total of 255 octets.

Since some resource names (especially services and namespaces) are used as individual segments in constructed DNS names, the 63 character limit is applicable.

**Comment by tibers** [comment]
It's a bit of throwing the baby out with the bathwater, don't you think? If I have a _single_ resource which I am working with, I expect that resource to be able to use the entire 255 chars I am used to. 

I completely agree with you that generated strings far down the line also need to be aware of this limitation, but then I would say the correct thing to do is surface them to the user to allow them to decide what's the appropriate course of action to take. 

Or, look at it the other way - the 63 char limit is harming the user experience. What could we do about it? Wouldn't it be better to simply be more permissive and throw an appropriate error when things get too long to cover the majority of the use cases?

**Comment by thockin** [comment]
I didn't see this before - which 63 character limit are you concerned with?  Resource names?  Which resources specifically?  Some (e.g. services) simply CAN'T allow more without tons of downstream changes, and practically probably changing anything to allow it is more work than it is worth.

**Comment by tibers** [comment]
Hey there. My reading of the spec is that 63 chars is the minimum so if anything, supporting the _should_ part would be quite helpful.

The specific scenario was something like `image: ip-12-34-56-78.us-east-1.compute.internal/myproject/container:v1.23.4` which is 67 chars. The problem is that folks using a private registry, with SSL, have to use an FQDN (or turn off cert validation) and so that eats up ~40 chars. Given that we're in love with pipelines like everyone else and so our developers tend to tag containers or name them with `date`, which is another 10 chars, and things get quite thin quite quickly. I think it would be good practice in general to support the "should" part of the spec but my specific problem is in referencing the docker containers in a private registry.

**Comment by thockin** [comment]
63 chars is a "label".

You're citing rules for "host names".

1123 builds on 1035, which says (among other things) "Labels must be 63
characters or less."

I'm still not clear what field(s) you want changed?  The pod.spec.image?
As far as I can see, we do not validate that at all.

**Comment by tibers** [comment]
Maybe I'm reporting a bug instead of a feature request. It's not that kubernetes throws an error, it's that if the field exceeds 63 chars for the spec.pod.image, K8s will look like it's working but the pod will never pull.

**Comment by thockin** [comment]
That is a very very different issue than this title would suggest.

Kubelet logs?

Does it work with plain old docker?

are there events generated for your Pod?

**Comment by thockin** [comment]
Can you post a minimal repro to public registry?  E.g. I just tested with `gcr.io/thockin-dev/012356789/0123456789/0123456789/0123456789/long_name:a-very-log-tag-name-0123456789` and it deployed into my cluster without fail.
