### ISSUE TITLE
a Node with name and status "Ready" already exists in the cluster.

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#89512]
**What happened**:

After upgrading to v1.18.0 not possible to join existing node into cluster:

```bash
# /usr/bin/kubeadm join 10.28.36.157:8443 --token <redacted> --discovery-token-ca-cert-hash 
...
I0326 11:57:39.638919   12149 kubelet.go:145] [kubelet-start] Checking for an existing Node in the cluster with name "m1c4" and status "Ready"
a Node with name "m1c4" and status "Ready" already exists in the cluster. You must delete the existing Node or change the name of this new joining Node
```

<details>
<summary>Full log</summary>

<pre>
W0326 11:57:39.322862   12149 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
I0326 11:57:39.322941   12149 join.go:371] [preflight] found NodeName empty; using OS hostname as NodeName
I0326 11:57:39.322968   12149 initconfiguration.go:103] detected and using CRI socket: /var/run/dockershim.sock
[preflight] Running pre-flight checks
I0326 11:57:39.323001   12149 preflight.go:90] [preflight] Running general checks
I0326 11:57:39.323031   12149 checks.go:249] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0326 11:57:39.323070   12149 checks.go:286] validating the existence of file /etc/kubernetes/kubelet.conf
I0326 11:57:39.323077   12149 checks.go:286] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0326 11:57:39.323086   12149 checks.go:102] validating the container runtime
I0326 11:57:39.407093   12149 checks.go:128] validating if the service is enabled and active
I0326 11:57:39.487777   12149 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0326 11:57:39.487834   12149 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0326 11:57:39.487861   12149 checks.go:649] validating whether swap is enabled or not
I0326 11:57:39.487890   12149 checks.go:376] validating the presence of executable conntrack
I0326 11:57:39.487922   12149 checks.go:376] validating the presence of executable ip
I0326 11:57:39.487954   12149 checks.go:376] validating the presence of executable iptables
I0326 11:57:39.487982   12149 checks.go:376] validating the presence of executable mount
I0326 11:57:39.488009   12149 checks.go:376] validating the presence of executable nsenter
I0326 11:57:39.488030   12149 checks.go:376] validating the presence of executable ebtables
I0326 11:57:39.488054   12149 checks.go:376] validating the presence of executable ethtool
I0326 11:57:39.488076   12149 checks.go:376] validating the presence of executable socat
I0326 11:57:39.488096   12149 checks.go:376] validating the presence of executable tc
I0326 11:57:39.488118   12149 checks.go:376] validating the presence of executable touch
I0326 11:57:39.488146   12149 checks.go:520] running all checks
I0326 11:57:39.560686   12149 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0326 11:57:39.560800   12149 checks.go:618] validating kubelet version
I0326 11:57:39.598654   12149 checks.go:128] validating if the service is enabled and active
I0326 11:57:39.609631   12149 checks.go:201] validating availability of port 10250
I0326 11:57:39.609728   12149 checks.go:286] validating the existence of file /etc/kubernetes/pki/ca.crt
I0326 11:57:39.609743   12149 checks.go:432] validating if the connectivity type is via proxy or direct
I0326 11:57:39.609764   12149 join.go:441] [preflight] Discovering cluster-info
I0326 11:57:39.609782   12149 token.go:78] [discovery] Created cluster-info discovery client, requesting info from "10.28.36.157:8443"
I0326 11:57:39.616900   12149 token.go:116] [discovery] Requesting info from "10.28.36.157:8443" again to validate TLS against the pinned public key
I0326 11:57:39.622631   12149 token.go:133] [discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "10.28.36.157:8443"
I0326 11:57:39.622650   12149 discovery.go:51] [discovery] Using provided TLSBootstrapToken as authentication credentials for the join process
I0326 11:57:39.622659   12149 join.go:455] [preflight] Fetching init configuration
I0326 11:57:39.622667   12149 join.go:493] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
I0326 11:57:39.635104   12149 interface.go:400] Looking for default routes with IPv4 addresses
I0326 11:57:39.635123   12149 interface.go:405] Default route transits interface "vmbr0"
I0326 11:57:39.635884   12149 interface.go:208] Interface vmbr0 is up
I0326 11:57:39.636606   12149 interface.go:256] Interface "vmbr0" has 3 addresses :[10.28.36.164/16 2a02:2b88:1:2:9657:a5ff:fed3:b6f2/64 fe80::9657:a5ff:fed3:b6f2/64].
I0326 11:57:39.636663   12149 interface.go:223] Checking addr  10.28.36.164/16.
I0326 11:57:39.636681   12149 interface.go:230] IP found 10.28.36.164
I0326 11:57:39.636696   12149 interface.go:262] Found valid IPv4 address 10.28.36.164 for interface "vmbr0".
I0326 11:57:39.636710   12149 interface.go:411] Found active IP 10.28.36.164 
I0326 11:57:39.636959   12149 preflight.go:101] [preflight] Running configuration dependant checks
I0326 11:57:39.636986   12149 controlplaneprepare.go:211] [download-certs] Skipping certs download
I0326 11:57:39.637019   12149 kubelet.go:111] [kubelet-start] writing bootstrap kubelet config file at /etc/kubernetes/bootstrap-kubelet.conf
I0326 11:57:39.638010   12149 kubelet.go:119] [kubelet-start] writing CA certificate at /etc/kubernetes/pki/ca.crt
I0326 11:57:39.638919   12149 kubelet.go:145] [kubelet-start] Checking for an existing Node in the cluster with name "m1c4" and status "Ready"
a Node with name "m1c4" and status "Ready" already exists in the cluster. You must delete the existing Node or change the name of this new joining Node
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runKubeletStartJoinPhase
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/kubelet.go:152
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:170
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
error execution phase kubelet-start
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:170
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
</pre>
</details>

The problem is that the check introduced in https://github.com/kubernetes/kubernetes/commit/b117a928a6c3f650931bdac02a41fca6680548c4 violates the existing diskless node approach.

Eg. we are having cluster of hundreds servers which are booding over PXE and have no any local storage.
After the boot they just running `kubeadm join` command to connect to the cluster, they can be rebooted ay any time, and after reboot they will run join procedure again.

Thus node object in cluster may already have some settings, labels and annotation for this node. After the joining the node just reuses them, this is working as a charm.

**What you expected to happen**:

Existing node successful joined

**How to reproduce it (as minimally and precisely as possible)**:

```
kubeadm join
kubeadm reset
kubeadm join
```

**Anything else we need to know?**:

Currently if you try to join the node you will face with https://github.com/kubernetes/kubernetes/issues/89501, but I created cluster role to check this chage.

**Environment**:
- Kubernetes version: `v1.18.0`
- Cloud provider or hardware configuration: Bare Metal
- OS: `Ubuntu 18.04.3 LTS`
- Kernel: `4.15.18-24-pve`
- Install tools: `kubeadm`
- Network plugin and version `kube-router v0.4.0`
- Others:

**Comment by neolit123** [comment]
> The problem is that the check introduced in b117a92 violates the existing diskless node approach.
> Eg. we are having cluster of hundreds servers which are booding over PXE and have no any local storage.
> After the boot they just running kubeadm join command to connect to the cluster, they can be rebooted ay any time, and after reboot they will run join procedure again.

we have to be clear that this approach was never officially supported by kubeadm.
simply restarting a node machine would make the kubelet and the CR bring that node back up.
but resetting the node and then re-joining without deleting the node object is problematic.

> Thus node object in cluster may already have some settings, labels and annotation for this node. After the joining the node just reuses them, this is working as a charm.

by preventing a node with the same name from joining the cluster we are solving a security issue, as otherwise an attacker knowing a bootstrap token would be able to bring your control-plane down.

ideally, your steps should now be:
```
kubeadm join
# store the Node labels / annotations
kubeadm reset
kubectl delete no <node-name> # which needs privileged kubeconfig
kubeadm join
# apply the stored labels and annotations
```

/priority awaiting-more-evidence

**Comment by kvaps** [comment]
> we have to be clear that this approach was never officially supported by kubeadm.

OK, but this opportunity is supported by kubelet and api-server itself, it is working fine and I don't see the reason to stop using it.
We are using this approach since v1.9 and never faced with the problems described in #79779, every rejoin old node is just reuse old name and parameters with no any problems.

> by preventing a node with the same name from joining the cluster we are solving a security issue, as otherwise an attacker knowing a bootstrap token would be able to bring your control-plane down.

This is not fully truth, because:

* He can just use modified kubeadm binary, or other deployment tool.
* Bootstrap token could be generated automatically for each new boot
* This precaution is useless for spheres where you use Kubernetes in closed perimeter just for convenient utilizing a compute power of your servers and you don't expect some hacking attempts.

**Comment by neolit123** [comment]
> OK, but this opportunity is supported by kubelet and api-server itself, it is working fine and I don't see the reason to stop using it.
We are using this approach since v1.9 and never faced with the problems described in #79779, every rejoin operation of old node is just reuse name and parameters of existing resource with no any problems.

i've seen #79779 in the wild a number of times and users are shooting them self in the foot causing outage of the control-plane creating tickets for us.

> He can just use modified kubeadm binary, or other deployment tool. And now he can also list all the nodes in cluster to make a choose which one he want to hack slightly_smiling_face

this is absolutely true
i should have said "partially" as it needs a server side fix as well.
it only eliminates the issue for users that do not recompile the source code or users that do it by accident.

> Bootstrap token could be generated automatically every hour and for each new boot

but the malicious bootstrap can only succeed if the user knows a token.

> This precaution is useless for spheres where Kubernetes is used in closed perimeter just for convenient utilizing a compute power of physical servers, eg scientific where you need just convenient tool to perform calculating and no security.

they can still shoot themself in the foot by having two nodes with the same name. so i think it has some value. using kubernetes without security is not possible - e.g. disabling certificates completely.

**Comment by kvaps** [comment]
OK, but I still do not understand how is it possible to create two nodes with the same name, is there any steps to reproduce? I was trying but Kuberentes API is not allowing that:

```bash
# kubectl create -f - <<EOT
apiVersion: v1
kind: Node
metadata:
  name: test
EOT
node/test created

# kubectl create -f - <<EOT
apiVersion: v1
kind: Node
metadata:
  name: test
EOT
Error from server (AlreadyExists): error when creating "STDIN": nodes "test" already exists
```

**Comment by neolit123** [comment]
creating the Node object directly will not work. the TLS bootstrap in the kubelet for matching node names (hostnames) can still trigger the race condition in etcd.

**Comment by kvaps** [comment]
@neolit123, if we will not allow rejoining only new nodes, say, whose age is 1 minute, would it solve the problem with the race condition in etcd?

**Comment by kvaps** [comment]
Or even better idea, to not restrict the join if node having `Unknown` status.

**Comment by neolit123** [comment]
> @neolit123, if we will restrict rejoining only for new nodes, say, whose age is 1 minute, would it solve the problem with the race condition in etcd?

not sure i understand. if you join a node named "foo" to a cluster that already has "foo", the new "foo" will remain NotReady but the existing "foo" will also become NotReady due to the crash loop of control-plane components. not sure how age matters here.

> Or even better: to not restrict the join if node having Unknown status.

are you suggesting the Node having status NodeReady but with condition Unknown:
https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4556-L4592

what would put it in this condition?

my understanding is that you are trying to rejoin nodes while their status is still "Ready", so this line breaks this for you:
https://github.com/kubernetes/kubernetes/commit/b117a928a6c3f650931bdac02a41fca6680548c4#diff-3c566a0c1e3b213a34b39503abf4fc11R150

would changing `--node-monitor-grace-period` and possibly adjusting `--node-monitor-period` to lower values and waiting for the nodes to become NotReady before joining solve the issue for you?

**Comment by kvaps** [comment]
Unfortunately intentionally or accidentally, but this check does not work:

```bash
# kubectl get node m1c12
NAME    STATUS     ROLES    AGE   VERSION
m1c12   NotReady   <none>   29h   v1.17.4

# kubectl get node m1c12 -o json | jq .status.conditions
[
  {
    "lastHeartbeatTime": "2020-03-27T22:42:29Z",
    "lastTransitionTime": "2020-03-27T22:43:12Z",
    "message": "Kubelet stopped posting node status.",
    "reason": "NodeStatusUnknown",
    "status": "Unknown",
    "type": "MemoryPressure"
  },
  {
    "lastHeartbeatTime": "2020-03-27T22:42:29Z",
    "lastTransitionTime": "2020-03-27T22:43:12Z",
    "message": "Kubelet stopped posting node status.",
    "reason": "NodeStatusUnknown",
    "status": "Unknown",
    "type": "DiskPressure"
  },
  {
    "lastHeartbeatTime": "2020-03-27T22:42:29Z",
    "lastTransitionTime": "2020-03-27T22:43:12Z",
    "message": "Kubelet stopped posting node status.",
    "reason": "NodeStatusUnknown",
    "status": "Unknown",
    "type": "PIDPressure"
  },
  {
    "lastHeartbeatTime": "2020-03-27T22:42:29Z",
    "lastTransitionTime": "2020-03-27T22:43:12Z",
    "message": "Kubelet stopped posting node status.",
    "reason": "NodeStatusUnknown",
    "status": "Unknown",
    "type": "Ready"
  }
]

# kubeadm join 10.28.36.157:8443 --token w1omzr.yjt7s52f2wvf6pdn     --discovery-token-ca-cert-hash sha256:8a614c8c9f40c18e7a48754ddfcf8e616aea64fd3ab93cbbc45623108797f9ef 
W0327 23:43:43.201658   30737 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase kubelet-start: a Node with name "m1c12" and status "Ready" already exists in the cluster. You must delete the existing Node or change the name of this new joining Node
To see the stack trace of this error execute with --v=5 or higher
```

In b117a92#diff-3c566a0c1e3b213a34b39503abf4fc11R150, you're checking just existence of condition with `type == Ready` but you also have to check the `status` of this condition

**Comment by kvaps** [comment]
This variant is working fine:
https://github.com/kubernetes/kubernetes/pull/89602/files

**Comment by neolit123** [comment]
it did work in my tests.
i guess, it would not work for the case where the condition is still present but not True, so your PR makes sense.

**Comment by neolit123** [comment]
but that does not help you with your use case, right?

**Comment by kvaps** [comment]
This change is fine for me, because I need to rejoin nodes only after reboot. Usually it takes more than 30 seconds (it's a time when node is coming from `Ready` to `Unknown` state.)

**Comment by neolit123** [comment]
so by the time you reboot the NodeReady condition now has a `Unknown` status instead of `Ready`?
does `--node-monitor-grace-period` affect this? it's default is 40s?

**Comment by neolit123** [comment]
you might want to lower that value.

also see my comment about "release note" on the PR.

**Comment by kvaps** [comment]
You're right it is 40 seconds:
```
  {
    "lastHeartbeatTime": "2020-03-27T23:11:23Z",
    "lastTransitionTime": "2020-03-27T23:10:53Z",
    "message": "kubelet is posting ready status. AppArmor enabled",
    "reason": "KubeletReady",
    "status": "True",
    "type": "Ready"
  }
  {
    "lastHeartbeatTime": "2020-03-27T23:11:23Z",
    "lastTransitionTime": "2020-03-27T23:12:33Z",
    "message": "Kubelet stopped posting node status.",
    "reason": "NodeStatusUnknown",
    "status": "Unknown",
    "type": "Ready"
  }
```

**Comment by neolit123** [comment]
ok, i will send a cherry pick for the PR to 1.18
