### ISSUE TITLE
pvc will lost when statefulset create volume but pvc is deleting

### ISSUE THREAD

**Issue by smileusd** [kubernetes/kubernetes#89513]
Is this a bug?
/kind bug

**What happened**:
If pod and pvc deleted, new pod will be created when controller sync statefulset. But pvc is deleting with finalizer. Then statefulset controller will skip create pvc and only create pod. If pod recreate the pvc might be deleted.
**What you expected to happen**:
Statefulset controller will skip create this pod utill the pvc is deleted.
**How to reproduce it (as minimally and precisely as possible)**:
1. create statefulset with pvc. 
2. add finalizer to pvc. 
3. delete pod. 
4. remove pvc
**Anything else we need to know?**:
None
**Environment**:
- Kubernetes version (use `kubectl version`):
latest master (at least 1.18)
- Cloud provider or hardware configuration:
None
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
None

**Comment by msau42** [comment]
Sounds like https://github.com/kubernetes/kubernetes/issues/74374

**Comment by smileusd** [comment]
Thanks. And I try to fix this issues https://github.com/kubernetes/kubernetes/pull/89643.

**Comment by smileusd** [comment]
duplicated with #74374
