### ISSUE TITLE
Update perf-dash to use new scheduler metrics

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#89521]
The scheduler latency metrics for predicate and priority evaluation used in [perf-dash](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Scheduler&metricname=SchedulingLatency&Operation=priority_evaluation) are deprecated. We need to migrate to use the [new extension point-based metric](https://github.com/kubernetes/kubernetes/blob/f8e62e33c920ccc86f8ca9ffb9b58a30634feeba/pkg/scheduler/metrics/metrics.go#L186).

This can be done in two steps:
1) add latency metrics for each of the extensions point to perf-dash
2) once we verify that the predicate and priority evaluation metrics are properly represented by the (PreFilter + Filter) and (PreScore + Score) metrics, then we completely remove those metrics 

/sig scheduling
/assign @ingvagabund

**Comment by ingvagabund** [comment]
1. will be resolved through: https://github.com/kubernetes/perf-tests/pull/1081

**Comment by ahg-g** [comment]
new metrics look ok, we can now remove the deprecated ones:
binding, predicate_evaluation, priority_evaluation and preemption_evaluation

**Comment by ingvagabund** [comment]
2. resolved through https://github.com/kubernetes/perf-tests/pull/1172

**Comment by ingvagabund** [comment]
/close
done
