### ISSUE TITLE
Pod to Pod Bandwidth Reservation 

### ISSUE THREAD

**Issue by mudverma** [kubernetes/kubernetes#89532]
Proposal/Question: 

For Bandwidth sensitive telco and or video/audio streaming applications we need to block bandwidth between pods. This is specially needed in service chaining scenarios. 

Currently CNIs support local traffic shaping (bandwidth reservation) per pod. What we want is bandwidth reservation between pods. 

Can this be achieved with current implementation? If not, we are considering adding such a feature. 

<img width="1055" alt="Screenshot 2020-03-16 at 3 50 07 PM" src="https://media.github.ibm.com/user/38380/files/e05dee00-679d-11ea-9cdd-74f8d3ca5d7e">

We want to take community opinion on this.

**Comment by uablrek** [comment]
K8s itself is not involved in traffic forwarding, this is an issue for the CNI-plugin.

> Currently CNIs support local traffic shaping (bandwidth reservation) per pod.

I have actually not seen any CNI-plugin with this function. Which CNI-plugin are you using?

"traffic shaping" often means "bandwith limitation" rather that "bandwidth reservation" which is actually very hard. I would like to check this in more detail (I am working with telco).

**Comment by mudverma** [comment]
@uablrek Yes, no CNI for now provides pod to pod guarantees (if we can call that a reservation).  However Calico provide traffic shaping (limitation) that too locally and not between a pair of pods. 

Yes Bandwidth reservation is actually hard. But there are clear use-cases if such a thing would exist. Even best-effort guarantees if not absolute.  

If there is a possibility to connect offline, we can discuss in detail.

**Comment by thockin** [comment]
The short answer is that k8s does not have such support right now, nor any open proposals to add it.

The longer answer is that I am not sure this is something Kubernetes itself should tackle, at lest not in "core".  If some implementations (CNI vendors or clouds or ...) want to get together and work on a proposed API and behavioral spec that could be implemented in their own ways, nobody would object to that, and it could MAYBE even find a home under the SIG (the API, not the impls).

I'm going to close this issue - the right path (assuming you want to walk it) is to first write a doc and socialize with sig-network, then turn that into a KEP.
