### ISSUE TITLE
MutatingAdmissionWebhook cannot modify the apiVersion

### ISSUE THREAD

**Issue by helios741** [kubernetes/kubernetes#89558]
i want to use MutatingAdmissionWebhook to modify the **apiVersion** of resource and find it is not feasible, but modify the content of **spec/metadata**.

my test code is as follows:
```golang
func updateApiVersion()([]byte, error)  {
    var patch []patchOperation
    patch = append(patch, patchOperation{
        Op: "replace",
        Path: "/group",
        Value: "apps",
    })
    patch = append(patch, patchOperation{
        Op: "replace",
        Path: "/version",
        Value: "v1",
    })
    patch = append(patch, patchOperation{
        Op: "replace",
        Path: "/metadata/name",
        Value: "helios",

    })
    patch = append(patch, patchOperation{
        Op: "replace",
        Path: "/spec/replicas",
        Value: 2,
    })
    return json.Marshal(patch)
}

...

    patchBytes, err := updateApiVersion()
    glog.Infof("patchBytes is :", string(patchBytes))
    if err != nil {
        return &v1beta1.AdmissionResponse{
            Result: &metav1.Status{
                Message: err.Error(),
            },
        }
    }

    glog.Infof("AdmissionResponse: patch=%v\n", string(patchBytes))
    return &v1beta1.AdmissionResponse{
        Allowed: true,
        Patch:   patchBytes,
        Result: &metav1.Status{
            TypeMeta: metav1.TypeMeta{
                APIVersion: "apps/v1",
            },
        },
        PatchType: func() *v1beta1.PatchType {
            pt := v1beta1.PatchTypeJSONPatch
            return &pt
        }(),
    }
```
when submitting a resource, the output is:

```shell
I0326 11:29:07.229993       1 webhook.go:319] patchBytes is :%!(EXTRA string=[{"op":"replace","path":"/group","value":"apps"},{"op":"replace","path":"/version","value":"v1"},{"op":"replace","path":"/metadata/name","value":"helios"},{"op":"replace","path":"/spec/replicas","value":2}])
I0326 11:29:07.230023       1 webhook.go:328] AdmissionResponse: patch=[{"op":"replace","path":"/group","value":"apps"},{"op":"replace","path":"/version","value":"v1"},{"op":"replace","path":"/metadata/name","value":"helios"},{"op":"replace","path":"/spec/replicas","value":2}]
I0326 11:29:07.230050       1 webhook.go:398] Ready to write reponse ...%!(EXTRA string={"response":{"uid":"01422e64-6f55-11ea-97b3-5254008356fe","allowed":true,"status":{"apiVersion":"apps/v1","metadata":{}},"patch":"W3sib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii9ncm91cCIsInZhbHVlIjoiYXBwcyJ9LHsib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii92ZXJzaW9uIiwidmFsdWUiOiJ2MSJ9LHsib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii9tZXRhZGF0YS9uYW1lIiwidmFsdWUiOiJoZWxpb3MifSx7Im9wIjoicmVwbGFjZSIsInBhdGgiOiIvc3BlYy9yZXBsaWNhcyIsInZhbHVlIjoyfV0=","patchType":"JSONPatch"}})

# echo -n "W3sib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii9ncm91cCIsInZhbHVlIjoiYXBwcyJ9LHsib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii92ZXJzaW9uIiwidmFsdWUiOiJ2MSJ9LHsib3AiOiJyZXBsYWNlIiwicGF0aCI6Ii9tZXRhZGF0YS9uYW1lIiwidmFsdWUiOiJoZWxpb3MifSx7Im9wIjoicmVwbGFjZSIsInBhdGgiOiIvc3BlYy9yZXBsaWNhcyIsInZhbHVlIjoyfV0=" | base64 --decode
[{"op":"replace","path":"/group","value":"apps"},{"op":"replace","path":"/version","value":"v1"},{"op":"replace","path":"/metadata/name","value":"helios"},{"op":"replace","path":"/spec/replicas","value":2}]

```

MutatingWebhookConfiguration as follow:
```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: mutating-example.banzaicloud.com
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", "extensions", ""]
        apiVersions: ["v1", "v1beta1"]
        resources: ["deployments","services"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled
```

i also looked at some source code because it is here but not sure：

is it because [NewVersionedAttributes](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go#L121)和[ConvertVersionedAttributes](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go#L126) are converted to the Kind type of the request here? 

had some question：
- [addPatchAnnotation](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go#L368)  call [AddAnnotationWithLevel](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/attributes.go#L141) and finds that there is no specific storage data.
- when does kube-apiserver store the webhook patch data in etcd? i did not find the corresponding code~

thanks~~

**Comment by helios741** [comment]
sig/api-machinery
area/apiserver

**Comment by liggitt** [comment]
An admission plugin may not modify the following attributes of objects being admitted: name, namespace, uid, kind, apiVersion

The patch returned by the admission webhook is applied to the incoming object, the incoming object is then converted to the internal version, validated, then serialized and stored in etcd.

**Comment by helios741** [comment]
@liggitt

**Comment by helios741** [comment]
@liggitt 
is there any reason why  apiVersion cannot be modified?

Is there any way to modify the ApiVersion of the deployment? is [Webhook conversion](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#webhook-conversion) feasible?

**Comment by liggitt** [comment]
Admission does not convert object types (change apiVersion/kind) or modify object identity (name/namespace/uid). Can you describe why you want to modify the apiVersion of a request being made to the API server and what you are hoping to accomplish?

Webhook conversion applies only to custom resources. The API server knows how to convert all built-in API types already.

**Comment by helios741** [comment]
@liggitt 
We are about to upgrade the version of k8s to 1.16.8, we use the deprecated apiVersion and not want every developer to modify it.So i want to dynamically modify apiVersion when submitting resources.
is this method feasible？(i know i can specify *--runtime-config*  to avoid this problem, but it will still be encountered in version 1.18)

**Comment by liggitt** [comment]
> So i want to dynamically modify apiVersion when submitting resources. is this method feasible?

No, the API callers must change the API version submitted.

**Comment by helios741** [comment]
@liggitt 
why is this happening?
is there anything wrong with me doing this?

**Comment by liggitt** [comment]
The apiVersion determines the endpoint the client submits the request to. For example:
* An extensions/v1beta1 Deployment gets submitted to `/apis/extensions/v1beta1/namespaces/$namespace/deployments`
* An apps/v1 Deployment gets submitted to `/apis/apps/v1/namespaces/$namespace/deployments`

In 1.16, by default, the extensions/v1beta1 endpoint no longer exists. Clients that attempt to submit things to that endpoint will receive a 404 error.

Also, admission happens after an incoming request has been deserialized into typed structs. Trying to do conversion to a different apiVersion after that has happened is too late.

**Comment by helios741** [comment]
@liggitt 
ok, thanks.
Do you think my demand is reasonable?

**Comment by liggitt** [comment]
No, changing the apiVersion of a request in admission will not work.

**Comment by helios741** [comment]
@liggitt 
Thank you very much for your patience, i have a few more question.
1. why can not apiVersion be modified after request has been deserialized into typed structs?
2. why is the admission designed after request has been deserialized into typed structs. Does not admission before request has been deserialized into typed structs provide better scalability?

**Comment by liggitt** [comment]
> why can not apiVersion be modified after request has been deserialized into typed structs?

Conversion between versions does not just change the apiVersion string... the structure and fields of two different versions can vary dramatically, renaming fields, relocating them, restructuring the object, etc. An example of what conversion can do is found at https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v1/conversion.go#L258-L333

Unmarshaling an incoming request to a typed struct only works if the request's apiVersion matches the typed struct's version.

> Why is the admission designed after request has been deserialized into typed structs. Does not admission before request has been deserialized into typed structs provide better scalability?

The purpose of admission is to inspect/modify particular fields on objects and enforce policy on them. Admission plugins originated in-process in the API server, and operate on the in-memory deserialized object. Doing admission before deserializing would require passing data to each admission plugin as a `[]byte`, and for each admission plugin to decode/encode, which would decrease scalability.

**Comment by helios741** [comment]
@liggitt 
I see, thank you😊
