### ISSUE TITLE
Conformance v1.17.2 failure

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#89564]
**What happened**:
Conformance v1.17.2 fails，because of known bug
Summarizing 1 Failure:

[Fail] [sig-cli] Kubectl client Guestbook application [It] should create and stop a working application  [Conformance]
/workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2335

Ran 280 of 4843 Specs in 6342.641 seconds
FAIL! -- 279 Passed | 1 Failed | 0 Pending | 4563 Skipped

e2e test have been resolved in v1.18
https://github.com/kubernetes/kubernetes/pull/85642

**What you expected to happen**:
i want to pass the comformance v1.17.2，what should i do?

**How to reproduce it (as minimally and precisely as possible)**:
set up v1.17.2 k8s cluster，and run the conformance test

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mysunshine92** [comment]
ping @claudiubelu ,what should i do? if i want to pass theconformance
but now the test is failed on [sig-cli] Kubectl client Guestbook application [It] should create and stop a working application

**Comment by claudiubelu** [comment]
Is this a Windows environment?

**Comment by mysunshine92** [comment]
> Is this a Windows environment?

linux environment，centos

**Comment by claudiubelu** [comment]
Then your environment might have an issue. That test is a Conformance test, which means that any change couldn't have merged if it would have broken it. Looking in testgrid, it looks like solid green: https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%201.17

You'll have to include more information in this issue report, including test logs. Pod logs are also very useful to track what the pods are doing.

**Comment by mark-au** [comment]
Reproduced when performing different distributions v1.17.4 conformance test on Oracle Linux. 

Attached are two tests performed on the same cluster, one using 1.17 tests and the latter with 1.18 tests.

[202004080355_sonobuoy_0a625910-cef3-44ad-9fcd-3193e7987619-clean.tar.gz](https://github.com/kubernetes/kubernetes/files/4448816/202004080355_sonobuoy_0a625910-cef3-44ad-9fcd-3193e7987619-clean.tar.gz)
[202004080529_sonobuoy_2c5be1c5-9708-464d-a0af-d38b0be77387-clean.tar.gz](https://github.com/kubernetes/kubernetes/files/4448817/202004080529_sonobuoy_2c5be1c5-9708-464d-a0af-d38b0be77387-clean.tar.gz)

We're still investigating but naturally the changes changes made for #85642 are interesting

```
export SONOBUOY_VERSION="0.18.0"
export SONOBUOY_FILENAME="sonobuoy_${SONOBUOY_VERSION}_linux_amd64.tar.gz"
curl -LO https://github.com/vmware-tanzu/sonobuoy/releases/download/v${SONOBUOY_VERSION}/${SONOBUOY_FILENAME}
tar zxf ${SONOBUOY_FILENAME}

[vagrant@master1 ~]$ kubectl get nodes -o wide
NAME                 STATUS   ROLES    AGE     VERSION             INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                   CONTAINER-RUNTIME
master1.vagrant.vm   Ready    master   7m37s   v1.17.4+1.0.1.el7   192.168.99.101   <none>        Oracle Linux Server 7.6   4.14.35-1844.4.5.el7uek.x86_64   cri-o://1.17.0
worker1.vagrant.vm   Ready    <none>   6m25s   v1.17.4+1.0.1.el7   192.168.99.111   <none>        Oracle Linux Server 7.6   4.14.35-1844.4.5.el7uek.x86_64   cri-o://1.17.0
worker2.vagrant.vm   Ready    <none>   6m50s   v1.17.4+1.0.1.el7   192.168.99.112   <none>        Oracle Linux Server 7.6   4.14.35-1844.4.5.el7uek.x86_64   cri-o://1.17.0

[vagrant@master1 ~]$ ./sonobuoy version --kubeconfig ~/.kube/config
Sonobuoy Version: v0.18.0
MinimumKubeVersion: 1.16.0
MaximumKubeVersion: 1.18.99
GitSHA: 7d97bdec5801a6853fa454edf59081156983f430
API Version:  v1.17.4+1.0.1.el7

[vagrant@master1 ~]$ ./sonobuoy run --mode=certified-conformance --wait
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=sonobuoy resource=services
[vagrant@master1 ~]$ ./sonobuoy retrieve --log_file v1.17.tar.gz
202004080355_sonobuoy_0a625910-cef3-44ad-9fcd-3193e7987619.tar.gz
[vagrant@master1 ~]$ ./sonobuoy delete --wait
INFO[0000] deleted                                       kind=namespace namespace=sonobuoy
INFO[0000] deleted                                       kind=clusterrolebindings
INFO[0000] deleted                                       kind=clusterroles

[vagrant@master1 ~]$ ./sonobuoy run --mode=certified-conformance --kube-conformance-image-version=v1.18 --wait
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=sonobuoy resource=services
[vagrant@master1 ~]$ ./sonobuoy retrieve --log_file v1.18.tar.gz
202004080529_sonobuoy_2c5be1c5-9708-464d-a0af-d38b0be77387.tar.gz

[vagrant@master1 ~]$ ./sonobuoy e2e 202004080355_sonobuoy_0a625910-cef3-44ad-9fcd-3193e7987619.tar.gz --show=failed
failed tests: 1
[sig-cli] Kubectl client Guestbook application should create and stop a working application  [Conformance]

[vagrant@master1 ~]$./sonobuoy e2e 202004080529_sonobuoy_2c5be1c5-9708-464d-a0af-d38b0be77387.tar.gz --show=failed
failed tests: 0
```
Note I have modified the tarballs before uploading but _only_ to edit the name of the image registry

**Comment by mark-au** [comment]
I've confirmed that `--kube-conformance-image-version=v1.16` also passes without error so it's specific to the v1.17 image/tests.

**Comment by cocoztho000** [comment]
@ivinpolosony and I also hit this issue on Oracle Linux (we work with @mark-au). Our root cause turned out to be a firewall masquerade was hiding the source IP of the packets causing this test to fail. Further digging revealed the test is valid since the [Kubernetes network model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model) states "pods in the host network of a node can communicate with all pods on all nodes without NAT".

### Our Workaround 

1. If you set the masquerade rule on all hosts you should remove it
```
firewall-cmd --remove-masquerade 
firewall-cmd --remove-masquerade --permanent
```

2. Set the firewall rule on all hosts to trust the pod traffic. Our fix is to accept all connections to the cni0 interface from the host. This interface is used as the bridge for our containers.
```
firewall-cmd --zone=trusted --add-interface=cni0
firewall-cmd --zone=trusted --add-interface=cni0 --permanent
```

Thank you @mysunshine92 for opening this issue so we knew we were not the only ones failing the 1.17 conformance on a similar OS. Since this messing with firewall please refer your security team for the best solution. Let us know if this fixes your problem 🙂

**Comment by mysunshine92** [comment]
@cocoztho000 we have fix this problem.from the pr #85642 ,we know that the agnhost image is wrong，so i pull 1.18  agnhost image，then use docker tag as 1.17  agnhost image，then this e2e test is paased.

**Comment by cocoztho000** [comment]
It's good to hear you found a solution
