### ISSUE TITLE
Restore HA multi control-planes once the external etcd cluster is restored from backup snapshots

### ISSUE THREAD

**Issue by kcao3** [kubernetes/kubernetes#89595]
Hello,

I currently have a HA cluster with 3 masters/control-planes nodes and 2 worker nodes. The cluster is using an external 3-node etcd cluster. 

I currently testing how to backup and restore the control-planes from a disaster. I was able to backup my etcd cluser by using ETCDCTL_API=3 etcdctl --endpoints $ENDPOINT snapshot save snapshot.db on each etcd member host and able to restore the etcd cluster by using cmd: ETCDCTL_API=3 etcdctl snapshot restore.. on each etcd member host. The restored etcd cluster
is healthy.

However, I have had no luck so far getting the k8s components including the kube-controller-manager and the kube-scheduler running correctly after the etcd cluster has been successfully restored from snapshots. Specifically, since etcd cluster is restored from snapshots, there has been an issue with both the controller-manager and scheduler. For some unknown reason, these two components are having the same type of issue involving acquiring/electing a leader.

For example, first I see some messages from a kube-controller-manager once it starts:

leaderelection.go:246] failed to aquire lease kube-system/kube-controller-manager
leaderelection.go:350] lock is held by HOST_NAME_UUID and has not yet expired
leaderelection.go:246] failed to aquire lease kube-system/kube-controller-manager

I then managed to free up the lock/lease by deleting the endpoint kube-controller-manager
kubectl -n kube-system delete ep kube-controller-manager

As soon as the endpoint kube-controller-manager is deleted, I notice a new one is successfully created; and the new controller-manager pod is able acquire the lease:

I leaderelection.go: 251] successfully acquired lease kube-system/kube-controller-manager
I event.go: 274] Event(v1.ObjectReference{Kind: "Endpoints", Namespace: "kube-system", "Name: "kube-controller-manager", UID:"<ID>",
  APIVersion:"v1", ResourceVersion: "607084", FieldPath:""}) type: 'Normal' reason: 'LeaderElection' <HOST_NAME>_<ID> became leader

I controllermanager.go:217] using legacy client builder
E leaderelection.go:365] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-control-manager": the object has been modified; please apply your changes to the latest version and try again

Some other INFO-level logs ...

E leaderelection.go:365] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-control-manager": the object has been modified; please apply your changes to the latest version and try again

E leaderelection.go:365] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-control-manager": the object has been modified; please apply your changes to the latest version and try again

E leaderelection.go:365] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-control-manager": the object has been modified; please apply your changes to the latest version and try again

E leaderelection.go:365] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-control-manager": the object has been modified; please apply your changes to the latest version and try again

I leaderelection.go: 287] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition.
I event.go:274] Event(v1.ObjectReference{Kind: "Endpoints", Namespace: "", "Name: "", UID:"",
  APIVersion:"v1", ResourceVersion: "", FieldPath:""}) type: 'Normal' reason: 'LeaderElection' <SAME_HOST_NAME_AS_ABOVE>_ID stopped leading
F controllermanager.go:279] leaderelection lost
I tokens_controller.go:181] Shutting down

While inspect the kube-control-manager endpoint, I see the SON object like the following:

kubectl describe ep -n kube-system kube-controller-manager

{
  "holderIdentity": "<hostname>_<ID>",
  "leaseDurationSeconds": 15,
  "acquireTime": "**2020-03-27T17:24:56Z**",
  "renewTime": "**2020-03-27T17:24:56Z**",
  "leaderTransitions": 0
}

I notice the aquireTime and renewTime are almost the same in this case. 

Does anyone know why the kube-controller-manager is not able to renew its lease in this case?  Is there something still wrong with my etcd cluster after it is successfully restoreed from a snapshot backups?  The reason I wonder is because I notice if I back up my etcd cluster by simply copy ALL files on each etcd host under/var/lib/etcd to a backup location then restore the etcd cluster by moving the files back to /var/lib/etcd on each etcd member host from the backup location; after my etcd cluster was restored successfully, the controller-manager and scheduler did NOT run into this issue.

I believe backup/restore k8s control-plane components for a HA multi-control-plane cluster is an extremely important feature of kubernetes.

I hope that someone has done it and is willing to share his/her experience with the community.

I really appreciate your time and thank you for your support.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3; 
- Cloud provider or hardware configuration: Bare-metal
- OS (e.g: `cat /etc/os-release`): Centos 7.7
- Kernel (e.g. `uname -a`): 5.5.2-1.el7.elrepo 
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others: etcd version v3.3.5

**Comment by neolit123** [comment]
/triage support
/remove-kind bug

hi, heave your read?
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md
https://docs.openshift.com/container-platform/3.11/admin_guide/assembly_restoring-cluster.html#restoring-etcd-data
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster

**Comment by kcao3** [comment]
@neolit123 thank you for your quick response. Yes. as I mentioned, I believe my restored etcd cluster is HEALTHY.  It's the k8s components (controller-manager and scheduler) that are having the problem.

**Comment by kcao3** [comment]
It turned out the root cause of the issue is because the etcd cluster was recovered INCORRECTLY from multiple snapshots  - each snapshot was created independently from each etcd member. 
In other words,  To restore/recover an etcd cluster, ONLY ONE single snapshot of the keyspace from ANY etcd member in a healthy cluster MUST be used.

**Comment by neolit123** [comment]
> ONLY ONE single snapshot of the keyspace from ANY etcd member in a healthy cluster MUST be used.

this is stated in the etcd docs that i linked above:

> all members should restore using the same snapshot

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster

**Comment by kcao3** [comment]
Based on my painful experience, it's a 'MUST' rather a 'should'. Anyway, thank you for your kind support.

**Comment by neolit123** [comment]
agreed. you can PR the change in their docs.

**Comment by nulldoot2k** [comment]
> It turned out the root cause of the issue is because the etcd cluster was recovered INCORRECTLY from multiple snapshots - each snapshot was created independently from each etcd member. In other words, To restore/recover an etcd cluster, ONLY ONE single snapshot of the keyspace from ANY etcd member in a healthy cluster MUST be used.

I can not bro, 
etcd external with 3 node is, etcd1, etcd2, etcd3
cluster include 3 master and 2 worker
LB: VIP
i create snapshot from 1 of 3 node etcd via LB
```
ETCDCTL_API=3 etcdctl \
  --endpoints=https://loadbalancer:2379 \
  --cacert=/etc/kubernetes/pki/etcd/ca.pem \
  --cert=/etc/kubernetes/pki/etcd/etcd.pem \
  --key=/etc/kubernetes/pki/etcd/etcd-key.pem \
  snapshot save mybackup.db
  ```
  and sync to all node etcd
  i restore all etcd with mybackup.db
  ```
  ETCDCTL_API=3 /usr/local/bin/etcdctl \
  --endpoints=https://<IP>:2379 \
  --cacert=/etc/kubernetes/pki/etcd/ca.pem \
  --cert=/etc/kubernetes/pki/etcd/etcd.pem \
  --key=/etc/kubernetes/pki/etcd/etcd-key.pem \
  --data-dir="/var/lib/etcd" \
  --initial-cluster="etcd1=https://<IP>:2380,etcd2=https://<IP>:2380,etcd3=https://<IP>:2380" \
  --name="etcd(n)" \
  --initial-advertise-peer-urls="https://<IP>:2380" \
  snapshot restore mybackup.db
  ```
  now i check pods in cluster then i see CNI fail: Failed to initialize datastore error=Get "https://10.244.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default" 
  because api-server active wrong after etcd recovery
  
  i did stop api-server,schedule... etcd before restore etcd
  but still error..
  
  You can share step by step you finish them?
