### ISSUE TITLE
kubectl describe secrets skips annotations by default

### ISSUE THREAD

**Issue by jtigger** [kubernetes/kubernetes#89600]
**What would you like to be added**:
Adjust the behavior of `kubectl describe secrets` such that _all_ annotations are omitted from the output, by default.

Users who wish to view annotations, include a flag (e.g. `--show-annotations`).  Or are directed to use the `kubectl get secret -o yaml` command.

**Why is this needed**:
For the same reason that `kubectl describe secrets` skips the `lastAppliedConfig` annotation (that is, https://github.com/kubernetes/kubernetes/pull/34664#issuecomment-276543823): to address https://github.com/kubernetes/kubernetes/issues/23564.

The technique of storing the object state in an annotation is useful in general — colocating a snapshot of the object's state in metadata is an effective way of supporting operations relying on detecting changes.

Unfortunately, employing this technique means that the raw contents of the secret are displayed, including sensitive data (detailed discussion contained in https://github.com/kubernetes/kubernetes/issues/23564 and https://github.com/kubernetes/kubernetes/pull/34664).

`kubectl` is the defacto standard tool for managing Kubernetes resources.  That said, other tools are useful for certain use-cases.

For example, k14s' [kapp](https://get-kapp.io/) tool improves the resource upgrade experience by detecting when previously-deployed resources have changed.  To accomplish this, the tool stores the object's state in an annotation when it first applies the object, and uses that data later to detect if a change has occurred.

By omitting all annotations, as a default behavior, we make it less likely the user will display potentially sensitive data in plaintext, accidentally.

----
p.s. The desired goal, here, is an approach by which `kubectl describe secret` is able to maintain its apparent design goal of providing a sanitized-by-default view of the object.

The approach outlined above is merely a concrete proposal to achieve this actual goal, designed to be as simple as possible.

p.p.s. It is understood that "metadata is not treated as less confidential than main object content by encryption at rest or authorization" (https://github.com/kubernetes/kubernetes/issues/23564#issuecomment-517937457).  This feature is about not accidentally displaying sensitive data in console output.

**Comment by jtigger** [comment]
> I think this make sense.

I'm delighted!

> Do you want to submit a PR on this?

I do.  I will.

**Comment by pwittrock** [comment]
Thanks for filing this.

@soltysh @seans3 this will break backwards compatibility on describe, but I think we have said in the past that the describe output is not stable.

How much does this just apply to secrets versus all resources -- e.g. other tools could store sensitive data in annotation for other resources.  The last-applied annotation is a special case since kubectl owns it.

Perhaps we should make this more generic by having the resource itself describe which annotations should / should not be displayed?

**Comment by liggitt** [comment]
what is the threat model being addressed here, that the output of describing a secret would be logged?

**Comment by jtigger** [comment]
> what is the threat model being addressed here, that the output of describing a secret would be logged?

If we found that omitting the `last-applied-configuration` annotation was addressing a valid threat, I thought it would follow that the same threat applies to _all_ annotations on a Secret since _any_ could contain sensitive data.

I've found myself conditioned to think of `kubectl describe secret` as "safe."  For example, when recording a demo, I wouldn't put it past myself to do this when verifying that the secret I just added is, in fact, present.

**Comment by soltysh** [comment]
This was discussed earlier today during SIG-CLI and the overall sentiment is that this won't be solved. We advised towards either improved server-side describe which at some point will allow further dynamic printing (maybe in the future), but overall the suggestion was that original author should check out server-side apply to start with.

I'm going to close this for now, feel free to re-open if this gets back.
/close
