### ISSUE TITLE
Kubernetes API-server certificate expired client

### ISSUE THREAD

**Issue by qw1mb0** [kubernetes/kubernetes#89611]
**What would you like to be added**:
Add a label or metric with the Common Name of the certificate and the IP-address where the request is made to the kubernetes api-server. 

**Why is this needed**:
Kubernetes api-server has the metrics apiserver_client_certificate_expiration_seconds_bucket: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go#L34-L66.

Which tells you that there are clients in the kubernetes cluster that are accessing the api-server with a certificate. Based on this metric, there are a few alerts on the Internet:
https://github.com/coreos/prometheus-operator/issues/1843.
https://medium.com/@DazWilkin/kubernetes-metrics-ba69d439fac4

However, it is impossible to understand from this metric who accesses the api-server with the certificate, which will soon end. And the only way to find such clients is to wait for the certificate to expire and to find clients who receive 403 response code by api-server logos with high verbose.

Is there any way to find these clients before their certificate expires? Usually these are kubectl or kubelet configs and sometimes you have to guess where you forgot to update your client certificate. Is there a metric for that?

**Cluster information**:
Kubernetes version: 1.16.6
Cloud being used: bare-metal
Installation method: kubeadm
Host OS: ubuntu 18.04
CNI and version: Flannel 0.11.0
CRI and version: docker://18.9.7

**Comment by liggitt** [comment]
Adding an unbounded value as a metric label causes problems with metric cardinality

cc @logicalhan

**Comment by qw1mb0** [comment]
Yes, I understand the problem.

Maybe we should add some metric or label for apiserver_request_*.

**Comment by enj** [comment]
I think #89305 is a better approach for including metadata from authenticators that is not bounded by the cardinality requirements of metrics.

/priority important-longterm

**Comment by zjj2wry** [comment]
It seems that the metrics are meaningless. If the client cannot be distinguished from kubernetes component {kubelet, controller-manager} and others. 

@enj If I understand correctly, we want add an audit when the client cert expires?

**Comment by qw1mb0** [comment]
Now we have a workaround for resolve this issue via patch apiserver:

```
--- staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go	(revision e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529)
+++ staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go	(date 1589130892814)
@@ -20,6 +20,7 @@
 	"crypto/x509"
 	"crypto/x509/pkix"
 	"fmt"
+	"k8s.io/klog"
 	"net/http"
 	"time"
 
@@ -102,6 +103,13 @@
 
 	remaining := req.TLS.PeerCertificates[0].NotAfter.Sub(time.Now())
 	clientCertificateExpirationHistogram.Observe(remaining.Seconds())
+
+	if remaining < (7 * 24 * time.Hour) {
+		klog.Warningf("%s %s: [%s %s]: certificate expires in one week. Issuer: %s, Subject: %s, NotBefore: %s, NotAfter: %s",
+			req.Method, req.RequestURI, req.UserAgent(), req.RemoteAddr,
+			req.TLS.PeerCertificates[0].Issuer, req.TLS.PeerCertificates[0].Subject, req.TLS.PeerCertificates[0].NotBefore, req.TLS.PeerCertificates[0].NotAfter)
+	}
+

```
