### ISSUE TITLE
Unify the calculating resource request/limit into one place

### ISSUE THREAD

**Issue by fengzixu** [kubernetes/kubernetes#89627]
**What would you like to be added**:

I want to unify all methods of "Calculating Resource" into one place.

**Why is this needed**:

When I worked on this PR(https://github.com/kubernetes/kubernetes/pull/89222) of sig-scheduling,  we found we should use the unified function to calculating the resource request.

So we find there are two methods in https://github.com/kubernetes/kubernetes/blob/5713c22eecff4610026643fbd3d37c33a43c168d/pkg/api/v1/resource/helpers.go file.

The first is  `PodRequestsAndLimits`

```
func PodRequestsAndLimits(pod *v1.Pod) (reqs, limits v1.ResourceList) {
	reqs, limits = v1.ResourceList{}, v1.ResourceList{}
	for _, container := range pod.Spec.Containers {
		addResourceList(reqs, container.Resources.Requests)
		addResourceList(limits, container.Resources.Limits)
	}
	// init containers define the minimum of any resource
	for _, container := range pod.Spec.InitContainers {
		maxResourceList(reqs, container.Resources.Requests)
		maxResourceList(limits, container.Resources.Limits)
	}

	// if PodOverhead feature is supported, add overhead for running a pod
	// to the sum of reqeuests and to non-zero limits:
	if pod.Spec.Overhead != nil && utilfeature.DefaultFeatureGate.Enabled(features.PodOverhead) {
		addResourceList(reqs, pod.Spec.Overhead)

		for name, quantity := range pod.Spec.Overhead {
			if value, ok := limits[name]; ok && !value.IsZero() {
				value.Add(quantity)
				limits[name] = value
			}
		}
	}

	return
}
``` 

It used the addResourceList to calculate the resource request. But it only covers cpu and memory calculation. 

The second function is `GetResourceRequest`, it can calculate the request for a specific resource. It looks like better than PodRequestsAndLimits.

I think the PodRequestsAndLimits is more like a kind of batch operation. The GetResourceRequest is like a single operation for a specific resource. Maybe we need to make the approach of calculating resource reqeust/limit the same whatever in the batch or single method. 

In my opinion,  a good and unified method of calculating resource request/limit should include points as below

- Can get the resource/limit for any specific resource
- Can get the resource/limit for any specific pod. It should consider all containers, eventually, init container.
- Can get resource/limit for all supported resources in current version.

**Comment by fengzixu** [comment]
So i think we may need to refactor the function of calculating resource request/limit.

1. GetResourceRequest
2. GetResourceLimit
3. PodRequest
3. PodLimit

Those methods include single and batch operation, they are more flexible for users.

**Comment by fengzixu** [comment]
@liggitt What do you think?
/cc @ahg-g @Huang-Wei

**Comment by fengzixu** [comment]
@apelisse PTAL. If the issue was validated, I will do it.

**Comment by apelisse** [comment]
I have no knowledge about this issue, I would rather ask @yliaog again.
