### ISSUE TITLE
e2e Reboot test failure

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#8962]
Built mostly from head. One node did not come up healthy, kubelet is not sending heartbeats.

I see this in the offending kubelet's logs every 7 seconds or so:
```
E0528 22:33:30.578956    2551 gce.go:459] Failed to retrieve TargetInstance resource for instance: e2e-test-dbsmith-minion-vwwn
E0528 22:33:30.579004    2551 kubelet.go:729] Unable to construct api.Node object for kubelet: failed to get instance ID from cloud provider: Get https://www.googleapis.com/compute/v1/projects/crested-analogy
-671/zones/us-central1-b/instances/e2e-test-dbsmith-minion-vwwn?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE
```

**Comment by rjnagal** [comment]
@lavalamp Looks like the node didn't come up healthy enough to contact metadata server. Kubelet keeps retrying to get to metadata server. Do we need a different behavior here, or more node validation?

**Comment by lavalamp** [comment]
I'm not sure what happened, and unfortunately I already tore down the cluster. Rebooting it a second time did not fix the problem, though.

**Comment by roberthbailey** [comment]
Closing since this issue is a few months old and it isn't possible to debug any longer.
