### ISSUE TITLE
kubeadm can't join existing cluster if conntrack is not installed on Coreos

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/kubernetes#89628]
**What happened**:
failed to join node using kubeadm because conntrack is not found on ContainerLinux distributions.

**What you expected to happen**:
kubeadm should work without any error. 

**How to reproduce it (as minimally and precisely as possible)**:
execute 
`kubeadm init phase preflight`
on ContainerLinux
```
ip-172-16-65-137 ~ # kubeadm init phase preflight
W0329 10:17:52.672484    8589 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileExisting-conntrack]: conntrack not found in system path
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
ip-172-16-65-137 ~ # cat /etc/*release
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=2191.5.0
DISTRIB_CODENAME="Rhyolite"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 2191.5.0 (Rhyolite)"
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2191.5.0
VERSION_ID=2191.5.0
BUILD_ID=2019-09-04-0357
PRETTY_NAME="Container Linux by CoreOS 2191.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
ip-172-16-65-137 ~ # lsmod |grep con
xt_conntrack           16384  0
nf_conntrack_ipv4      16384  0
nf_conntrack_netlink    45056  0
nfnetlink              16384  2 nf_conntrack_netlink,ip_set
nf_conntrack          139264  6 xt_conntrack,nf_conntrack_ipv4,nf_nat,nf_nat_ipv4,nf_conntrack_netlink,ip_vs
nf_defrag_ipv6         20480  2 nf_conntrack,ip_vs
nf_defrag_ipv4         16384  1 nf_conntrack
libcrc32c              16384  3 nf_conntrack,nf_nat,ip_vs
ip-172-16-65-137 ~ # kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:56:30Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
ip-172-16-65-137 ~ #
```

**Anything else we need to know?**:

related issue: 

https://github.com/kubernetes/kops/issues/5671
https://github.com/coreos/fedora-coreos-config/issues/325

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.0
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): coreos 2191.5.0
- Kernel (e.g. `uname -a`): 4.19.68-coreos
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): not appliable
- Others:

**Comment by aojea** [comment]
@MartinForReal you can ignore the error in kubeadm if you want,  as explained in the error message, using the flag `--ignore-preflight-errors=`

> [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Comment by MartinForReal** [comment]
@aojea I think we need to add some comments for coreos installations. So that the user will not get confused. 

related issue: #59286

**Comment by neolit123** [comment]
conntrack is already a kubelet dependency in the RPM spec:
https://github.com/kubernetes/release/blob/master/cmd/kubepkg/templates/latest/rpm/kubelet/kubelet.spec#L19

in terms of container linux you can send a PR for this area of the k8s.io website:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

listing some of the required binaries and mentioning that theuser can skip some of them with `--ignore-preflight-errors=...` (on their own risk).

/remove-kind bug
/kind documentation
/remove-sig node

**Comment by nealey** [comment]
The instructions on this page work brilliantly for Fedora CoreOS, thanks so much to whomever created them, I have been trying for *months* to get k8s going on my FCOS machines.

Except for the conntrack issue. This command did complete successfully:

    sudo kubeadm init --ignore-preflight-errors=FileExisting-conntrack

Given that the current instructions are as simple as "copy/paste these 5 blobs into a shell", I personally would have appreciated at the very least a blurb about what the conntrack binary does, how to ignore it being missing, and what risk I'm taking by ignoring it (I still have no idea). Even better would be some pointers about how I can get this binary installed, so I don't have to take the risk.

**Comment by neolit123** [comment]
conntrack is required by the kubelet for clearing connections (same for kube-proxy).
https://github.com/kubernetes/kubernetes/pull/85857

we don't have an explanation in the k8s.io documentation, but since some of these binary dependencies are hardcoded in the kubelet then it seems appropriate for this to be documented in kubelet documentation (not kubeadm) and then the kubeadm documentation can link to that page.

if you would like you can log a ticket for that in k/website. also PRs are welcome.

> sudo kubeadm init --ignore-preflight-errors=FileExisting-conntrack

the kubeadm CLI already prints that you can skip errors using `--ignore-preflight-errors`, where `FileExisting` is the prefix and `-conntrack` is the filename. there are no guarantees the cluster will work properly after skipping some of these.

/close
