### ISSUE TITLE
Pod cannot be deleted from cluster because its volume directory can't been removed by kubelet

### ISSUE THREAD

**Issue by k2huang** [kubernetes/kubernetes#89635]
**What happened**:
Pod keeps terminating state forever after trigger deleting pod via `kubectl delete` command. And the following kubelet error logs was found:

`
I0306 00:36:16.988704   11502 util.go:189] "/var/lib/kubelet/pods/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a/volumes/kubernetes.io~nfs/bach-hadflow" is unmounted, deleting the directory
E0306 00:36:16.988816   11502 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/nfs/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a-bach-hadflow\" (\"6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a\")" failed. No retries permitted until 2020-03-06 00:36:17.488766591 +0800 CST m=+5133187.004659487 (durationBeforeRetry 500ms). Error: "UnmountVolume.TearDown failed for volume \"hadflow-pvc\" (UniqueName: \"kubernetes.io/nfs/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a-bach-hadflow\") pod \"6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a\" (UID: \"6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a\") : remove /var/lib/kubelet/pods/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a/volumes/kubernetes.io~nfs/bach-hadflow: directory not empty"
`

**What you expected to happen**:
Pod can be deleted from k8s cluster after deleting pod via kubectl

**How to reproduce it (as minimally and precisely as possible)**:
1.kubectl create pod, pod spec includes [subpath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath)
2.kubectl delete pod during pod is pulling container image, and then the pod maybe in terminating state forever.

**Anything else we need to know?**:
After analyzing kubelet logs, I think there exists workflow conflict between sync pod loop goroutine and volume manager goroutine in kubelet process. My find is as following:
1.user executes `kubectl create pod` (pod spec including [subpath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath))
2.kubelet volume manager goroutine mounts pod volumes after pod scheduled
3.kubelet sync pod loop goroutine creates & starts pod sandbox
4.kubelet sync pod loop goroutine creates & starts containers
5.user executes `kubelet delete pod` during the first container is pulling docker image
6.kubelet volume manager goroutine unmounts pod volumes when finding pod is deleting（pod.deletionTimestamp != nil ）and no container is running
7.kubelet sync pod loop goroutine makes subpath for container into volume mountpoint after docker image is pulled but in fact volume has been unmounted at step6, so those subpathes are built in local host path but not in volume mountpoint
8.kubelet volume manager goroutine removes pod volumes directory in host but find it's not empty and can't be removed.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Can you post more of the kubelet log regarding 6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a ?

Thanks

**Comment by k2huang** [comment]
> Can you post more of the kubelet log regarding 6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a ?
> 
> Thanks

Sorry, I don't save it. Could you please check my analysis?

**Comment by tedyu** [comment]
Looking at recent e2e test log, I saw:
```
I0328 17:47:32.980605    1386 subpath_linux.go:213] Cleaning up subpath mounts for /var/lib/kubelet/pods/46f98e08-20ef-40ea-ae48-7be681443847/volume-subpaths/local-pvptjkn
```
It seems the subpath in your example was slightly different from e2e test run.

The code has moved quite a bit between 1.16 and 1.19
When you have time, see if the problem can be reproduced using 1.19
```
user executes kubelet delete pod during the first container is pulling docker image
```
It seems the window of exposing this problem is kind of short.

Thanks

**Comment by k2huang** [comment]
> Looking at recent e2e test log, I saw:
> 
> ```
> I0328 17:47:32.980605    1386 subpath_linux.go:213] Cleaning up subpath mounts for /var/lib/kubelet/pods/46f98e08-20ef-40ea-ae48-7be681443847/volume-subpaths/local-pvptjkn
> ```
> 
> It seems the subpath in your example was slightly different from e2e test run.
> 
> The code has moved quite a bit between 1.16 and 1.19
> When you have time, see if the problem can be reproduced using 1.19
> 
> ```
> user executes kubelet delete pod during the first container is pulling docker image
> ```
> 
> It seems the window of exposing this problem is kind of short.
> 
> Thanks

The prefix `/var/lib/kubelet` can be specified by kubelet option <--root-dir>, which is not this issue key point. 
I have check master brach code, and I think this issue is still existing. Please focus on the user case: 
The first container of Pod is pulling a big image by kubelet, user trigger `kubectl delete pod`, then kubelet volume manager goroutine will trigger to unmount volume (because `IsPodTerminated` return true) , but sync pod loop can't stop immediately and continue to create the first container, and the subpath(sush as /xxx/yyy) is made based on volume path(/var/lib/kubelet/pods/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a/volumes/kubernetes.io~nfs/bach-hadflow) before creating container,  but this subpath （/var/lib/kubelet/pods/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a/volumes/kubernetes.io~nfs/bach-hadflow/xxx/yyy）will lead to kubelet volume manager can't remove volume path(/var/lib/kubelet/pods/6e3bdbf0-5eff-11ea-991c-7cd30ac0ac2a/volumes/kubernetes.io~nfs/bach-hadflow) via `os.Remove`.

Please help me confirm if it will happen in the latest code from your point of view. Thanks in advance.

**Comment by tedyu** [comment]
thanks for the reply.
```
because IsPodTerminated return true
```
Looking at Kubelet#podAndContainersAreTerminal (in master branch), it seems we should take PodPending phase (where image is being pulled) into account.

**Comment by fun-sudeep** [comment]
SWCTL-6414: Sometimes, "cleanup" failed complaining "rmtree failed: [Errno 16] Device or resource busy".
