### ISSUE TITLE
Job Controller: job.Status.Failed is incorrect in some cases

### ISSUE THREAD

**Issue by yangxikun** [kubernetes/kubernetes#89630]
**What happened**:

The job yaml:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-failed-onfailure
  namespace: test-job-cronjob
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    spec:
      hostNetwork: true
      containers:
      - name: hello
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; echo I am down; exit 1
      restartPolicy: OnFailure
```

The job is finished and has one failed pod, but job.Status.Failed = 0.

```
Name:           job-failed-onfailure
Namespace:      test-job-cronjob
Selector:       controller-uid=4c9f272a-8cb9-4798-ab64-d194480ef642
Labels:         controller-uid=4c9f272a-8cb9-4798-ab64-d194480ef642
                job-name=job-failed-onfailure
Annotations:    kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"job-failed-onfailure","namespace":"test-job-cronjob"},"spec":{"...
Parallelism:    1
Completions:    1
Start Time:     Sun, 29 Mar 2020 00:12:36 +0800
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=4c9f272a-8cb9-4798-ab64-d194480ef642
           job-name=job-failed-onfailure
  Containers:
   hello:
    Image:      dockerhub.nie.netease.com/wings/busybox
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/sh
      -c
      date; echo I am down; exit 1
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason                Age                    From            Message
  ----     ------                ----                   ----            -------
  Normal   SuccessfulCreate      5m51s                  job-controller  Created pod: job-failed-onfailure-9g7dt
  Normal   SuccessfulDelete      5m35s                  job-controller  Deleted pod: job-failed-onfailure-9g7dt
  Warning  BackoffLimitExceeded  5m35s (x2 over 5m35s)  job-controller  Job has reached the specified backoff limit
```

**What you expected to happen**:

job.Status.Failed = 1

**How to reproduce it (as minimally and precisely as possible)**:

Just apply the yaml above, and sometimes can reproduce.

**Anything else we need to know?**:

In job_controller.go:syncJob:

* active: means the number of pods that satisfy `v1.PodSucceeded != p.Status.Phase && v1.PodFailed != p.Status.Phase && p.DeletionTimestamp == nil`
* failed: means the number of pods that it's phase equal v1.PodFailed

```go
	activePods := controller.FilterActivePods(pods)
	active := int32(len(activePods))
	succeeded, failed := getStatus(pods)
```

Then, if the JobController detect the job is failed, JobController cumulative "active" as "failed".

When the pod.Status.Phase is not Succeeded or Failed, and pod.DeletionTimestamp != nil, then this pod will not be count as "active" or "failed".

```go
        ........
	if jobFailed {
		errCh := make(chan error, active)
		jm.deleteJobPods(&job, activePods, errCh)
		select {
		case manageJobErr = <-errCh:
			if manageJobErr != nil {
				break
			}
		default:
		}

		// update status values accordingly
		failed += active
		active = 0
		job.Status.Conditions = append(job.Status.Conditions, newCondition(batch.JobFailed, failureReason, failureMessage))
		jm.recorder.Event(&job, v1.EventTypeWarning, failureReason, failureMessage)
		klog.V(4).Infof("jobFailed = true, failed = %d", failed)
	} else {
        ........
```

In my case, because the pod.spec.restartPolicy = OnFailure, so the pod.Status.Phase always be Running, and the `jm.deleteJobPods` will make the pod enter "pod.DeletionTimestamp != nil" state.

So, in one sync loop, JobController observe the job status is `active=1, succeeded=0, failed=0`, and the job enter jobFailed, then update job.status = `active=0, succeeded=0, failed=1`.

In the next sync loop, JobController observe the job status is `active=0, succeeded=0, failed=0`, and the job enter jobFailed, then update job.status = `active=0, succeeded=0, failed=0`.
> Because in the last sync loop, job.status update event didn't received by JobInformer, so JobController continue the sync logic.

My suggestion bugfix, in `succeeded, failed := getStatus(pods)` count `v1.PodSucceeded != p.Status.Phase && v1.PodFailed != p.Status.Phase && p.DeletionTimestamp != nil` as failed.

```go
// getStatus returns no of succeeded and failed pods running a job
func getStatus(pods []*v1.Pod) (succeeded, failed int32) {
	for _, p := range pods {
		if v1.PodSucceeded == p.Status.Phase {
			succeeded++
			continue
		}
		if v1.PodFailed == p.Status.Phase || p.DeletionTimestamp != nil {
			failed++
		}
	}
	return
}
```

I notice there is another issue #28486 about reimplement the job status update. but it doesn't seem to be progressing.

**Environment**:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tedyu** [comment]
The suggested fix should take pod.spec.restartPolicy into account.

**Comment by yangxikun** [comment]
I had test pod.spec.restartPolicy = Never, the problem also exists.

And I found another problem, if pod.spec.restartPolicy = Never, the BackoffLimit implement is not be accurate enough(It depends on the number of requeue).

In one sync, JobController detect the job enter jobFailed: `exceedsBackoffLimit = true, len(pods) = 7, active = 2, succeeded = 0, failed = 5`, then delete pods and update job.status.condition = BackoffLimitExceeded.

In the next sync, JobController detect the job doesn't enter jobFailed(Because jobHaveNewFailure=false): `exceedsBackoffLimit = false, len(pods) = 7, active = 0, succeeded = 0, failed = 5`, 2 pods(status=Running) are in deletion progress, then it create new pods and update  job.status.condition = [].

Finally the job will enter jobFailed more than 1 times, and some pods are "miss" statistics(because this pods are delete by first jobFailed and not observe in next sync).

Should JobController stop sync job after job first enter jobFailed? This may require to introduce cache to mark job that is failed.

**Comment by soltysh** [comment]
There are two different approaches to how we can handle this situation. As described here https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy pods are treated differently based on the restart policy and job controller needs to react accordingly. For the restart policy Never it's simple, we count the failed pods - if we're at backofflimit we're done. It can happen as @yangxikun noted that this is not perfect and sometimes you might get additional pod run, but this is best effort and not guaranteed behavior. For the OnFailure restart policy the situation is slightly more complicated, since in this case it's kubelet responsibility to drive the restarts, in this case job controller verifies the pod restarts count. Which in case of the original problem is two which can be seen from the event:
```
Warning  BackoffLimitExceeded  5m35s (x2 over 5m35s)  job-controller  Job has reached the specified backoff limit
```
or if you check the pod output, you'll notice that its restart count matches the backofflimit. You can check the PR which added this capability here: https://github.com/kubernetes/kubernetes/pull/58972 and the original issue here: https://github.com/kubernetes/kubernetes/issues/54870

I'm closing this as this is not a bug.
/close

**Comment by sstaley-hioscar** [comment]
Why was this closed?
