### ISSUE TITLE
Cannot make WMI call to server from pod

### ISSUE THREAD

**Issue by lalwk** [kubernetes/kubernetes#89650]
**What happened**: 
Get-WmiObject return into an error when calling to a remote server with fqdn.
Get-WmiObject : The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

**What you expected to happen**: 
Get a list of WMI objects on the targeted server.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a windowscontainer with a GMSA attached . 

**Anything else we need to know?**:
GMSA is in the local administrator group of the targeted server.
A container spinned up by docker using the same image and gmsa-account is doing the call without errors.
I can access the server from the pod

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.0
- Cloud provider or hardware configuration: master: CentOS7 - worker: Windows Server 2019 Datacenter
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug): Flannel
- Others:

**Comment by SathishMSFT** [comment]
I am hitting this issue. Is there any workaround available to try?

**Comment by craiglpeters** [comment]
@immuzz @marosset do you have any ideas here?

**Comment by michmike** [comment]
you likely have to first configure GMSA and execute the WMI call from a network service or local system account inside the pod

**Comment by marosset** [comment]
Also make sure your networking routes are configured to allow your pod to establish WMI connects to the host.
