### ISSUE TITLE
--replicas has been deprecated

### ISSUE THREAD

**Issue by 1194570458** [kubernetes/kubernetes#89651]
kubectl run nginx --image=nginx --replicas=5

Flag --replicas has been deprecated, has no effect and will be removed in the future.

- Kubernetes version (use `kubectl version`): 1.18.0
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04

**Comment by tanjunchen** [comment]
/assign
@neolit123  
could you give more any information or documents about this?Thanks

**Comment by neolit123** [comment]
hi, try asking in the #sig-apps or #sig-cli channels on k8s slack.

**Comment by q843922994** [comment]
> hi, try asking in the #sig-apps or #sig-cli channels on k8s slack.

Flag --replicas has been deprecated, has no effect and will be removed in the future.
pod/nginx created

> /assign
> @neolit123
> could you give more any information or documents about this?Thanks

root@kubernetes-master:~# kubectl run nginx --image=nginx --replicas=2 --port=80
Flag --replicas has been deprecated, has no effect and will be removed in the future.
pod/nginx created

**Comment by neolit123** [comment]
see:
https://github.com/kubernetes/kubernetes/pull/87077

> Remove all the generators from kubectl run. It will now only create pods. Additionally, deprecates all the flags that are not relevant anymore.

this is part of 118:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#deprecation-4

/close

**Comment by chrisroat** [comment]
Should the asciicinema on the getting started page be updated?  It shows installing 1.12, and it basically stops working half-way through because a deployment is not created.  (A bit jarring for someone new to the project.)

**Comment by alexellis** [comment]
The new alternative command `kubectl create deployment` doesn't seem to provide the same functionality - it can't take many of the requisite flags. What would you suggest to users trying to migrate?

**Comment by q843922994** [comment]
> 新的替代命令`kubectl create deployment`似乎没有提供相同的功能-它不能使用许多必需的标志。您对尝试迁移的用户有何建议？
https://kubernetes.io/zh/docs/tasks/run-application/run-stateless-application-deployment/
