### ISSUE TITLE
Kubelet service installation on container Linux - fails for v1.18

### ISSUE THREAD

**Issue by chorus12** [kubernetes/kubernetes#89658]
**What happened**: Installation documentation is incorrect

**What you expected to happen**:
When installed for **container linux** according to the link - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
the kubelet service does not work. 

The problem is in the code below:
`curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
mkdir -p /etc/systemd/system/kubelet.service.d
curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf`

the location https://raw.githubusercontent.com/kubernetes/kubernetes/v1.18.0/buld/debs/kubelet.service
https://raw.githubusercontent.com/kubernetes/kubernetes/v1.18.0/build/debs/10-kubeadm.conf
does not contain the file and if files are taken, let's say from v1.16.4 release - that does not work and the service fails to start.

**Comment by neolit123** [comment]
> When installed for container linux according to the link - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

the location of the files changed.
you can download them from here:
https://github.com/kubernetes/release/tree/master/cmd/kubepkg/templates/latest

xref
https://github.com/kubernetes/kubernetes/issues/88832

/remove-sig docs
/sig cluster-lifecycle
/remove-kind bug
/kind documentation

logged this k/kubeadm issue:
https://github.com/kubernetes/kubeadm/issues/2097

/close
