### ISSUE TITLE
go-bindata/... matched no packages

### ISSUE THREAD

**Issue by smijolovic** [kubernetes/kubernetes#89675]
kubernetes 1.18.0
go 1.13.9 and 1.14.1

make what=cmd/kubeadm
+++ [0331 03:30:37] Building go targets for linux/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
go: warning: "k8s.io/kubernetes/vendor/github.com/go-bindata/go-bindata/..." matched no packages
+++ [0331 03:30:39] Building go targets for linux/amd64:
    cmd/kubeadm
go: warning: "k8s.io/kubernetes/vendor/github.com/go-bindata/go-bindata/..." matched no packages

make what=cmd/kubectl
go: warning: "k8s.io/kubernetes/vendor/github.com/go-bindata/go-bindata/..." matched no packages

**Comment by neolit123** [comment]
/triage support

try:

```
make clean
make all WHAT=./cmd/kubeadm
```

**Comment by smijolovic** [comment]
Same results:

make clean
make all WHAT=./cmd/kubeadm

+++ [0402 18:21:31] Verifying Prerequisites....
+++ [0402 18:21:51] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [0402 18:22:02] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [0402 18:22:09] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [0402 18:22:24] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [0402 18:22:35] Building go targets for linux/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
warning: ignoring symlink /home/rpmbuild/nimbus8/kube-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
go: warning: "k8s.io/kubernetes/vendor/github.com/go-bindata/go-bindata/..." matched no packages
+++ [0402 18:22:36] Building go targets for linux/amd64:
    ./cmd/kubeadm

**Comment by neolit123** [comment]
i reproduced the warning locally, but i do not know where it's coming from.
possibly something in `build/root/Makefile.generated_files`

the warning itself seems harmless.

/help
requesting help to debug why this warning is showing up.
the reproduction steps are in the comment above.

thanks.

/remove-triage support

**Comment by neolit123** [comment]
removing area/kubeadm as this also happens for `make all WHAT=./cmd/kubelet`

/remove-area kubeadm

**Comment by agadelshin** [comment]
/assign

I want to help here if you don't mind.

**Comment by agadelshin** [comment]
It's already fixed in master - https://github.com/kubernetes/kubernetes/commit/fe0f38839a79eb372593e87e095988e2dbbc8018

**Comment by neolit123** [comment]
ok, if this is fixed in master already we can close this issue.
this fix cannot be backported to 1.18 as it's not critical.

thanks for investigating @agadelshin 
/close
