### ISSUE TITLE
kube-apiserver and kube-scheduler doesn't expose kubernetes_build_info on /metrics

### ISSUE THREAD

**Issue by yrwal** [kubernetes/kubernetes#89685]
**What happened**:
After I updated from version 1.16.8 to 1.18.0, the kube-apiserver and kube-scheduler doesn't expose kubernetes_build_info on /metrics any more.

**What you expected to happen**:
The kube-apiserver and kube-scheduler should expose this metric.

**How to reproduce it (as minimally and precisely as possible)**:
kube-apiserver
$ curl -s -k --cert ./client.crt --key ./client.key https://127.0.0.1:6443/metrics | grep '^kubernetes_build_info'

kube-scheduler
$ curl -s http://127.0.0.1:10251/metrics | grep '^kubernetes_build_info'

**Anything else we need to know?**:
In version 1.18.0, only the kube-controller-manager will expose this metric.
$ curl -s http://127.0.0.1:10252/metrics | grep '^kubernetes_build_info'
kubernetes_build_info{buildDate="2020-03-25T14:50:46Z",compiler="gc",gitCommit="9e991415386e4cf155a24b1da15becaa390438d8",gitTreeState="clean",gitVersion="v1.18.0",goVersion="go1.13.8",major="1",minor="18",platform="linux/amd64"} 1

In version 1.16.8, the kube-apiserver, kube-scheduler and kube-controller-manager will all expose this metric.
$ curl -s -k --cert ./client.crt --key ./client.key https://127.0.0.1:6443/metrics | grep '^kubernetes_build_info'
kubernetes_build_info{buildDate="2020-03-12T20:52:22Z",compiler="gc",gitCommit="ec6eb119b81be488b030e849b9e64fda4caaf33c",gitTreeState="clean",gitVersion="v1.16.8",goVersion="go1.13.8",major="1",minor="16",platform="linux/amd64"} 1

$ curl -s http://127.0.0.1:10251/metrics | grep '^kubernetes_build_info'
kubernetes_build_info{buildDate="2020-03-12T20:52:22Z",compiler="gc",gitCommit="ec6eb119b81be488b030e849b9e64fda4caaf33c",gitTreeState="clean",gitVersion="v1.16.8",goVersion="go1.13.8",major="1",minor="16",platform="linux/amd64"} 1

$ curl -s http://127.0.0.1:10252/metrics | grep '^kubernetes_build_info'
kubernetes_build_info{buildDate="2020-03-12T20:52:22Z",compiler="gc",gitCommit="ec6eb119b81be488b030e849b9e64fda4caaf33c",gitTreeState="clean",gitVersion="v1.16.8",goVersion="go1.13.8",major="1",minor="16",platform="linux/amd64"} 1

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.7.1908 (Core)
- Kernel (e.g. `uname -a`): Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: curl
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhouya0** [comment]
@yrwal I submit this PR to fix this https://github.com/kubernetes/kubernetes/pull/89724, but I think it's not easy to get merged.
