### ISSUE TITLE
kubectl get events LAST SEEN is <unknown>

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubernetes#89689]
**What happened**:

When use `kubectl get events` show events, some events `LAST SEEN` is `<unknown>`,  i use `kubectl get events -o json` found these events `firstTimestamp` is null. I want to know why?

I compared to v1.11.6, events have no this problem.

**What you expected to happen**:

I want to know why some events firstTimestamp is null.

**How to reproduce it (as minimally and precisely as possible)**:

1. create a pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`v1.17.2`

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> create a pod.

@pytimer please try providing reproduction steps and example event YAML.
also more details about your setup should help.

/sig instrumentation

**Comment by pytimer** [comment]
@neolit123 I add example YAML and `kubectl get events` results.

I find only the event that source is  `default-scheduler` have this problem. 

I use `kubectl get events -n kube-system -ojson` to get the event detail information, I found v1.17.2 scheduler events object different from v1.11.6. I see the kubectl code, i found kubectl get `firstTimestamp` as `LAST SEEN` value, but this field is null in v1.17.2, so i'm a little confused.

These are events information:

#### v1.17.2 scheduler event:

```json
{
    "action": "Binding",
    "apiVersion": "v1",
    "eventTime": "2020-04-02T00:00:03.727592Z",
    "firstTimestamp": null,
    "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "etcd-backup-1585785600-hcxdt",
        "namespace": "kube-system",
        "resourceVersion": "1300145",
        "uid": "e7f2e826-4359-4017-9468-abdf23e0c95f"
    },
    "kind": "Event",
    "lastTimestamp": null,
    "message": "Successfully assigned kube-system/etcd-backup-1585785600-hcxdt to k8s-234",
    "metadata": {
        "creationTimestamp": "2020-04-02T00:00:03Z",
        "name": "etcd-backup-1585785600-hcxdt.1601d79ad01d5f8d",
        "namespace": "kube-system",
        "resourceVersion": "1300149",
        "selfLink": "/api/v1/namespaces/kube-system/events/etcd-backup-1585785600-hcxdt.1601d79ad01d5f8d",
        "uid": "bade7835-c09d-49c8-bac1-6e2a32ed7b9c"
    },
    "reason": "Scheduled",
    "reportingComponent": "default-scheduler",
    "reportingInstance": "default-scheduler-k8s-234",
    "source": {
        "component": "default-scheduler"
    },
    "type": "Normal"
}
```

#### v1.11.6 scheduler event:

```json
{
    "apiVersion": "v1",
    "count": 1,
    "eventTime": null,
    "firstTimestamp": "2020-03-31T12:00:18Z",
    "involvedObject": {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "etcd-backup-1585656000-x85zs",
        "namespace": "kube-system",
        "resourceVersion": "15158300",
        "uid": "3058d5a8-7347-11ea-baf7-fa163e2d0ef9"
    },
    "kind": "Event",
    "lastTimestamp": "2020-03-31T12:00:18Z",
    "message": "Successfully assigned kube-system/etcd-backup-1585656000-x85zs to master2",
    "metadata": {
        "creationTimestamp": "2020-03-31T12:00:18Z",
        "name": "etcd-backup-1585656000-x85zs.160161bf5326de78",
        "namespace": "kube-system",
        "resourceVersion": "15158304",
        "selfLink": "/api/v1/namespaces/kube-system/events/etcd-backup-1585656000-x85zs.160161bf5326de78",
        "uid": "307f67fe-7347-11ea-baf7-fa163e2d0ef9"
    },
    "reason": "Scheduled",
    "reportingComponent": "",
    "reportingInstance": "",
    "source": {
        "component": "default-scheduler"
    },
    "type": "Normal"
}
```

**Comment by neolit123** [comment]
thanks for adding the examples.
#instrumentation on slack might know more about this.

**Comment by afrouzMashaykhi** [comment]
> I find only the event that source is `default-scheduler` have this problem.

@pytimer can you reproduce the issue with another pod ?

**Comment by pytimer** [comment]
No, only `default-scheduler` . I think maybe scheduler use new event API, but kubectl use old event API.
