### ISSUE TITLE
Unexplained DNS request timeouts from all pods

### ISSUE THREAD

**Issue by fyatzeck** [kubernetes/kubernetes#89686]
**What happened**:

Kubernetes DNS queries suddenly began timing out across an entire cluster.  This includes both remote hosts and internal service DNS lookups.  Checking logs, many pods were reporting EAI_AGAIN error apparently indicating Kubernetes DNS server failed or timed out while fulfilling the request.  There are similar issues raised but no real root cause stated.

Example of one pod application logs:

`2020-03-23 23:27:48 - 'INFO' - Router called>>>/auth/Outlook
2020-03-23 23:28:30 - 'INFO' - Router called>>>/auth/callback/Outlook
2020-03-23 23:28:46 - 'ERROR' - err var on app.js -->Error: getaddrinfo EAI_AGAIN outlook.office.com`

However, checking the kube-dns pods themselves, they appeared to be running fine, and logs showed no errors.

Also checking the pod nameserver found in /etc/resolv.conf, the UDP port was responding fine:
nc -uv 100.64.0.10 53
`Connection to 100.64.0.10 53 port [udp/*] succeeded!`

Whether this could be Weave Net related or any other leads would be appreciated.

**What you expected to happen**:
No failure in DNS lookups

**How to reproduce it (as minimally and precisely as possible)**:

Cluster created in AWS using KOPS with 3 masters running across 2 availability zones
Cluster installed with the Weave Net CNI plugin.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:

AWS

- OS (e.g: `cat /etc/os-release`):

1. Debian GNU/Linux 9 (stretch)
2. Alpine Linux v3.7

- Kernel (e.g. `uname -a`):

Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by thockin** [comment]
It might help to walk through this doc:  https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

Unfortunately, there isn't much to go on in this report.  Hopefully that doc helps pinpoint where things are disconnecting.

Another approach might be to tcpdump the traffic from the node (root netns) and see what's happening there.

This does not seem to be a bug, per se, so I am going to close it for now.  If you can come back with more data that suggests kubernetes is going awry PLEASE reopen it
