### ISSUE TITLE
kubeadm 1.17 uses wrong SupportedEtcdVersion for 1.16

### ISSUE THREAD

**Issue by lewandom** [kubernetes/kubernetes#89680]
**What happened**:

When upgrading from 1.16 to 1.17 using kubeadm, occassionally a wrong etcd image version (3.3.17-0) is being used. Looks like this happens due to a bug in kubeadm code, introduced in https://github.com/kubernetes/kubernetes/commit/706cde51c512d8d07e35fc815af4439108a587f9.

**What you expected to happen**:

kubeadm consequently uses etcd image version 3.3.15-0. 

**How to reproduce it (as minimally and precisely as possible)**:

I was not able to track down the exact circumstances. However, it should not be necessary to reproduce, since the typo in the code is rather obvious.

**Anything else we need to know?**:

Nothing else to add.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.8 => 1.17.4
- Cloud provider or hardware configuration: VMware ESX
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by neolit123** [comment]
> When upgrading from 1.16 to 1.17 using kubeadm, occassionally a wrong etcd image version (3.3.17-0) is being used. Looks like this happens due to a bug in kubeadm code, introduced in 706cde5.

can you show the error message? are you sure it's not this warning:
https://github.com/kubernetes/kubeadm/issues/2065

this commit updated the versions for 1.16, 17 and added a version for 18:
https://github.com/kubernetes/kubernetes/commit/706cde51c512d8d07e35fc815af4439108a587f9#diff-c0a37094ae1c8cb6223a3822eb66f9f0R427-R429

/area kubeadm
/triage needs-information

**Comment by lewandom** [comment]
@neolit123 we're customizing the cluster's `imageRegistry` to a local one, e.g.:

```
[root@myhost ~]# kubectl get cm -n kube-system kubeadm-config -oyaml
apiVersion: v1
data:
  ClusterConfiguration: |
    ...
    imageRepository: myhost.acme.com:5000
    kind: ClusterConfiguration
    ...
kind: ConfigMap
metadata:
  ...
```

We're copying only a minimum required subset of images required to upgrade from version to version - currently, our upgrade chain is 1.13.0 => 1.14.10 => 1.15.11 => 1.16.8 => 1.17.4.

If you take kubeadm 1.16.8, the correct etcd version is 3.3.15, not 3.3.15.

```
$ wget https://storage.googleapis.com/kubernetes-release/release/v1.16.8/bin/linux/amd64/kubeadm -O kubeadm_1.16.8
--2020-04-02 18:30:45--  https://storage.googleapis.com/kubernetes-release/release/v1.16.8/bin/linux/amd64/kubeadm
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:818::2010, 172.217.21.208
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:818::2010|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40480768 (39M) [application/octet-stream]
Saving to: ‘kubeadm_1.16.8’

kubeadm_1.16.8                                       100%[=====================================================================================================================>]  38.61M  16.8MB/s    in 2.3s    

2020-04-02 18:30:48 (16.8 MB/s) - ‘kubeadm_1.16.8’ saved [40480768/40480768]

$ chmod a+x kubeadm_1.16.8 
$ ./kubeadm_1.16.8 config images list
I0402 18:31:17.994547   20685 version.go:251] remote version is much newer: v1.18.0; falling back to: stable-1.16
k8s.gcr.io/kube-apiserver:v1.16.8
k8s.gcr.io/kube-controller-manager:v1.16.8
k8s.gcr.io/kube-scheduler:v1.16.8
k8s.gcr.io/kube-proxy:v1.16.8
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd:3.3.15-0
k8s.gcr.io/coredns:1.6.2
```

Same thing if we look at line 427 in `release-1.16` branch: https://github.com/kubernetes/kubernetes/blob/release-1.16/cmd/kubeadm/app/constants/constants.go#L427 - etcd 3.3.15.

Historically, etcd 3.3.17 has been upgraded to in 1.17 alpha2, it was never part of 1.16:  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v1170-alpha2. The faulty commit https://github.com/kubernetes/kubernetes/commit/706cde51c512d8d07e35fc815af4439108a587f9 wrongly assumed 3.3.17 comes from a previous release, 1.16. That's what I referred to as "typo".

**Comment by neolit123** [comment]
> The faulty commit 706cde5 wrongly assumed 3.3.17 comes from a previous release, 1.16. That's what I referred to as "typo".

this is not a faulty commit because it bumped both etcd for 1.17 (to be released at the time) to `v3.4.3` and the 1.16 version to `v3.3.17-0` (which included critical etcd fixes).

> If you take kubeadm 1.16.8, the correct etcd version is 3.3.15, not 3.3.17.

that is true for kubeadm 1.16, but not for kubeadm 1.17.
note that kubeadm can deploy kubernetes version 1.X and 1.X-1, and there could be cases where we have to bump the etcd version for 1.X-1 too. there are cases where we might also have to backport this etcd bump to kubeadm 1.16.

> $ ./kubeadm_1.16.8 config images list

you might want to always specific `--kubernetes-version=v1.x.x` for `kubeadm config images`.
this will give you better control - i.e. the mapping for the etcd version for this kubernetes version based on the kubeadm binary.

your process should be the following [1]:
- pull the kubeadm binary version v1.16.x
- check the version of etcd using `kubeadm config images list --kubernetes-version=v1.16.x`
- pull that image
- pull the kubeadm binary version v1.17.x
- check the version of etcd using `kubeadm config images list --kubernetes-version=v1.17.x`
- pull that image

wouldn't this process work for you?

**Comment by lewandom** [comment]
@neolit123 to make me get that right, is the below correct?
- when using kubeadm 1.16.8 to install kubernetes 1.16.8, etcd 3.3.15 will be deployed,
- when using kubeadm 1.17.4 to install kubernetes 1.16.8, etcd 3.3.17 will be deployed.

Is that a correct behavior?

**Comment by neolit123** [comment]
i would say, yes it is correct.
ideally the 3.3.17 etcd bump should have also been backport to kubeadm 1.16 as it includes security patches.

**Comment by lewandom** [comment]
Understood, in such case I'm closing this as working as designed.
