### ISSUE TITLE
[Flaky test] TestSubresourcePatch resource version changes on no-op status patch of custom resource

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#89712]
**Which jobs are flaking**:
pull-kubernetes-integration

**Which test(s) are flaking**:
TestSubresourcePatch

**Testgrid link**:
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&sort-by-failures=&include-filter-by-regex=TestSubresourcePatch&width=5

**Reason for failure**:
Unknown. A diff with the original object would be helpful.

```
--- FAIL: TestSubresourcePatch (1.66s)
I0401 02:17:03.007163  119106 apiapproval_controller.go:198] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
    testserver.go:142: runtime-config=map[api/all:true]
    testserver.go:143: Starting apiextensions-apiserver on port 34145...
    testserver.go:161: Waiting for /healthz to be ok...
    subresources_test.go:755: Creating foo
    subresources_test.go:766: Patching .status.num to 999
    subresources_test.go:795: Patching .status.num again to 999
    subresources_test.go:806: Applying empty patch
    subresources_test.go:817: Patching .spec.replicas to 7
    subresources_test.go:858: Patching .spec.replicas again to 7
    subresources_test.go:869: Applying empty patch
    subresources_test.go:755: Creating foo
    subresources_test.go:766: Patching .status.num to 999
    subresources_test.go:795: Patching .status.num again to 999
    basic_test.go:1046: wanted "61203" at .metadata.resourceVersion, got "61204"
```

**Anything else we need to know**:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89710/pull-kubernetes-integration/1245166622725902337

/sig api-machinery

**Comment by apelisse** [comment]
OK Trying to reproduce, see what's going on.

**Comment by apelisse** [comment]
Clearly this is because SSA is updating the tracked entry's time. It happens when the two request don't happen in the same second. Having a `time.Sleep(time.Second)` between the two requests makes this into a definitive error.

**Comment by apelisse** [comment]
This seems to be because of ["status-wiping"](https://github.com/kubernetes/kubernetes/issues/75564).

A repeated patch like `{status:{num:999}, spec:{num:999}}` will always trigger a new managedFields entry to be created, since it's always going to change the object (status or spec will be wiped depending on the endpoint), so the patch will always cause the object to change, which will always cause the entry to be created.

**Comment by spiffxp** [comment]
Still seeing this, bumped into it over in https://github.com/kubernetes/kubernetes/pull/93943

**Comment by liggitt** [comment]
deflake in #94055 while the underlying issue is being worked on in https://github.com/kubernetes/kubernetes/issues/75564
