### ISSUE TITLE
node is NotReady

### ISSUE THREAD

**Issue by canerbis** [kubernetes/kubernetes#89714]
Dear anyone.
I am experiencing the problem like this.
I have installed many times for multi master of k8s.
I think both master2 and master3 has the previous configurations.
Could you know how to remove configurations related to k8s ?
I had removed yum remove kubectl,kubeadm and kubelet.
But It seems to remain files related to k8s. 

1.kubectl get node

[root@k8s-master1 ~]# kubectl get node
NAME          STATUS     ROLES    AGE   VERSION
k8s-master1   Ready      master   28m   v1.15.9
k8s-master2   NotReady   master   9h    v1.15.9
k8s-master3   NotReady   master   9h    v1.15.9
[root@k8s-master1 ~]# 

2. k8s-master2 /var/log/messages

[root@k8s-master2 ~]# systemctl status kubelet -l
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2020-04-01 20:28:08 KST; 7min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 3131 (kubelet)
    Tasks: 20
   Memory: 36.2M
   CGroup: /system.slice/kubelet.service
           └─3131 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=gcr.io/google_containers/pause:3.1

Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.533165    3131 kubelet.go:2252] node "k8s-master2" not found
Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.633344    3131 kubelet.go:2252] node "k8s-master2" not found
Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.718758    3131 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Unauthorized
Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.733558    3131 kubelet.go:2252] node "k8s-master2" not found
Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.833808    3131 kubelet.go:2252] node "k8s-master2" not found
Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.920088    3131 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Unauthorized
Apr 01 20:35:19 k8s-master2 kubelet[3131]: E0401 20:35:19.933969    3131 kubelet.go:2252] node "k8s-master2" not found
Apr 01 20:35:20 k8s-master2 kubelet[3131]: E0401 20:35:20.034125    3131 kubelet.go:2252] node "k8s-master2" not found
Apr 01 20:35:20 k8s-master2 kubelet[3131]: E0401 20:35:20.121328    3131 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Unauthorized
Apr 01 20:35:20 k8s-master2 kubelet[3131]: E0401 20:35:20.134345    3131 kubelet.go:2252] node "k8s-master2" not found
[root@k8s-master2 ~]# 

3. /etc/hosts
[root@k8s-master2 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.100.196 k8s-master1
192.168.100.197 k8s-master2
192.168.100.198 k8s-master3
[root@k8s-master2 ~]#

**Comment by MartinForReal** [comment]
have you tried executing `kubeadm reset `?

**Comment by neolit123** [comment]
> k8s-master2 NotReady master 9h v1.15.9

not that 1.15 is no longer supported. please upgrade to 1.16.

> I think both master2 and master3 has the previous runtime configurations.

`kubeadm reset...` should suffice to clear configuration.

> I had removed yum remove kubectl,kubeadm and kubelet.

this will uninstall the binaries and their deployed configuration such as systemd files.


> systemctl status kubelet -l

i don't see any relevant errors in the kubelet log.

to get more help on your "node is notReady" problem try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/triage support
/close
