### ISSUE TITLE
cephfs down lead kubernetes crush

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#89711]
cephfs down --> docker inspect hang -->pleg unhealth -->all kubelet not ready -->k8s cluster down

**Comment by tedyu** [comment]
Can you give some detail on cephfs going down ?

Thanks

**Comment by timchenxiaoyu** [comment]
mount pod to cephfs 

 /var/lib/kubelet/pods/8775eb17-73f5-11ea-837f-fad2d3138100/volumes/kubernetes.io~cephfs/dev-dev type ceph (rw,relatime,name=xxx,secret=<>,acl,wsize=16777216)

then  shutdown ceph  mds and  osd

**Comment by neolit123** [comment]
re-open this ticket once you modify the description to follow the issue template correctly:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

/remove-sig cluster-lifecycle
/close
