### ISSUE TITLE
Backward support for old KVM virtio-scsi driver

### ISSUE THREAD

**Issue by prometherion** [kubernetes/kubernetes#89723]
**What happened**:

After upgrading the hypervisor's QEMU version from 2.11 to 4.0 Pods were unable attach an already node mounted volume.
The root cause is that newer versions of QEMU apparently changed the way how the disks ID format being handled in `/dev/disk/by-id`: with this change, volumes attached on an OpenStack cluster using newer KVM driver doesn't work.
To address it, we had to create a _udev rule_ as has been suggested by this [comment](https://github.com/kubernetes/kubernetes/issues/34698#issuecomment-282129378).

**What was expected to happen**:

Although using deprecated OpenStack Cloud Provider, still being able to handle volumes regardless of the underlying driver.

**Steps to reproduce (as basic and precise as possible)**:

1. Deploy a Kubernetes cluster using OpenStack and QEMU 2.11
2. Upgrade hypervisor's QEMU to 4.0
3. Notice how disks ID format changes
**Anything else needs to be known?**:

**Environment**:
- Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: OpenStack Cloud Provider (deprecated one)
- OS (e.g: `cat /etc/os-release`): `Container Linux by CoreOS 2191.5.0 (Rhyolite)`
- Kernel (e.g. `uname -a`): `4.19.68`
- Install tools: `kubeadm` via `kubespray`
- Network plugin and version (if this is a network-related bug): N.R.
- Others: N.R.

**Comment by mandre** [comment]
The same issue was reported in https://github.com/kubernetes/kubernetes/issues/96672 with a fix at https://github.com/kubernetes/kubernetes/pull/96673.
