### ISSUE TITLE
Allow ConfigMap injection into any field

### ISSUE THREAD

**Issue by JohnGalt1717** [kubernetes/kubernetes#89738]
**What would you like to be added**:
All yaml files and any field should allow the injection of a value from a config map something like this: $(config-map-name/key)  When this syntax was used you could inject it anywhere into anything including in the middle of other strings.

somefield: some-($config-map-name/key)-value

or
somefield: (config-map-name/key)

**Why is this needed**:
This would allow vastly simpler configuration for environments. A single configmap file could be created in almost all cases that would allow you to inject values.

Kustomization is way too complex for most cases when you could just template and have kubectl do the injection.

**Comment by liggitt** [comment]
Building in templating was discussed at length early on in the project (e.g. https://github.com/kubernetes/kubernetes/issues/11492, 
https://github.com/kubernetes/kubernetes/issues/13241#issuecomment-233731291, https://github.com/kubernetes/kubernetes/issues/23896). There are [many templating tools available](https://github.com/kubernetes/kubernetes/issues/23896#issuecomment-313544857), but templating was deemed out of scope for kubectl.

**Comment by JohnGalt1717** [comment]
This isn't templating persay. It's injection anywhere of ConfigMaps so that it isn't on the Kind to have programmed it to use ConfigMaps.  Right now it's basically impossible without using a 3rd party tool to actually create environment configurations. Even using Kconfiguration you still end up with settings in multiple files that you have to update instead of one shared file as would be the case with this.
