### ISSUE TITLE
apiserver panic'd on GET /api/v1/events

### ISSUE THREAD

**Issue by Lincoln-dac** [kubernetes/kubernetes#89734]
**What happened**:
api-server logs error logs 
Apr 01 22:43:44 dcn-kube06 kube-apiserver[69454]: E0401 22:43:44.164834   69454 wrap.go:32] apiserver panic'd on GET /api/v1/namespaces/default/pods
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: E0401 22:48:48.135963   69454 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request ti
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: goroutine 1582505649 [running]:
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a40060, 0xc0001d5620)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachine
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc0030f7c60, 0x1, 0x1)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachine
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: panic(0x3a40060, 0xc0001d5620)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc01b832a40, 0xc019d406e0)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc001911080, 0x73a47a0, 0xc010ccac40, 0xc00bfbb3
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x73a47a0, 0xc010ccac40, 0xc00bfbb200)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: net/http.HandlerFunc.ServeHTTP(0xc00678fa70, 0x73a47a0, 0xc010ccac40, 0xc00bfbb200)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/net/http/server.go:1995 +0x44
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x73a47a0, 0xc010ccac40, 0xc02155d800)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: net/http.HandlerFunc.ServeHTTP(0xc00678faa0, 0x73a47a0, 0xc010ccac40, 0xc02155d800)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/net/http/server.go:1995 +0x44
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x73a47a0, 0xc010ccac40, 0xc02155d800)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: net/http.HandlerFunc.ServeHTTP(0xc0019110a0, 0x73a5d20, 0xc005374fc0, 0xc02155d800)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/net/http/server.go:1995 +0x44
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00678fad0, 0x73a5d20, 0xc005374fc0, 0xc02155d800)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: net/http.serverHandler.ServeHTTP(0xc005b22820, 0x73a5d20, 0xc005374fc0, 0xc02155d800)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/net/http/server.go:2774 +0xa8
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: net/http.(*conn).serve(0xc01f878e60, 0x73af660, 0xc0124c96c0)
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/net/http/server.go:1878 +0x851
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: created by net/http.(*Server).Serve
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: /usr/local/go/src/net/http/server.go:2884 +0x2f4
Apr 01 22:48:48 dcn-kube06 kube-apiserver[69454]: E0401 22:48:48.136105   69454 wrap.go:32] apiserver panic'd on GET /api/v1/events

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
kubernetes version 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
linux ernel   "4.14.15-1.el7.elrepo.x86_64"
- Install tools:
- Network plugin and version (if this is a network-related bug):
cni  flanneld 0.10
- Others:

**Comment by neolit123** [comment]
> kubernetes version 1.15

1.15 is out of support. is this reproducible with > 1.16?

/sig api-machinery

**Comment by neolit123** [comment]
> ...-v1.15.0-rc.1

this is also an RC version and not a final release of k8s.

**Comment by liggitt** [comment]
Timeouts are handled as panics, that looks like what happened: "killing connection/stream because serving request timed out"

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L245-L257

/close
