### ISSUE TITLE
Like Checkpointing, save Container Memory and Writable Layer to Persistent Storage after it is live and ready so that new containers can be created instantaneously from this memory image

### ISSUE THREAD

**Issue by sagarvelankar** [kubernetes/kubernetes#89742]
**What would you like to be added**:

After a container is live and ready as per the liveness and readiness probes, its memory and container writable layer should be saved to persistent storage using some solution like Checkpoint/Restore In Userspace (CRIU) so that new containers can be spawned using this image in addition to the docker image for faster boot time.

**Why is this needed**:

When we start Containers running Spring Boot Applications, they initialize many Bean Objects in memory along with many other objects. Due to this, they take time to be live and ready. So, if their memory and container writable layer can also be loaded from this memory image like their root filesystem is created quickly by the docker image, then they can be live and ready instantaneously.

**Comment by tedyu** [comment]
```
they take time to be live and ready.
```
After the container is ready, it would take traffic. Do you want the initial traffic to be persisted as well ?

**Comment by sagarvelankar** [comment]
> ```
> they take time to be live and ready.
> ```
> 
> After the container is ready, it would take traffic. Do you want the initial traffic to be persisted as well ?

Thanks for the reply. We do not want to persist initial traffic. The Container Memory and Writable Layer Image should be taken before the container's pod IP is added to the service endpoint object so that it does not contain any initial traffic data.
