### ISSUE TITLE
[Flaky Test] [sig-apps] ReplicationController should test the lifecycle of a ReplicationController

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#89740]
**Which jobs are flaking**:
- pull-kubernetes-e2e-gce
- pull-kubernetes-e2e-kind

**Which test(s) are flaking**:
- [sig-apps] ReplicationController should test the lifecycle of a ReplicationController

**Testgrid link**:
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=ReplicationController%20should%20test&width=10
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=ReplicationController%20should%20test&width=10

**Reason for failure**:
```
test/e2e/apps/rc.go:100
Apr  1 00:19:30.365: Failed to patch ReplicationControllerScale
Unexpected error:
    <*errors.StatusError | 0xc001505180>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Operation cannot be fulfilled on replicationcontrollers \"rc-test\": the object has been modified; please apply your changes to the latest version and try again",
            Reason: "Conflict",
            Details: {
                Name: "rc-test",
                Group: "",
                Kind: "replicationcontrollers",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    Operation cannot be fulfilled on replicationcontrollers "rc-test": the object has been modified; please apply your changes to the latest version and try again
occurred
test/e2e/apps/rc.go:195
```

**Anything else we need to know**:
- test was introduced via https://github.com/kubernetes/kubernetes/pull/88588
- links to specific failures
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88036/pull-kubernetes-e2e-kind/1245137431854845954
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89715/pull-kubernetes-e2e-gce/1245372983606775809/

- ref: https://github.com/kubernetes/kubernetes/pull/88588#issuecomment-607366847
>Choices are:
>
>- patch something the controller isn't messing with regularly (not sure what that would be)
>- properly handle optimistic concurrency by retrying in these cases, AND by not necessarily expecting the value we write to be there later

/assign @hh @BobyMCbobs 
/sig architecture
/area conformance
/sig apps
/priority important-soon
It's flaking, but not so bad as to show up in triage and flakes-latest.json. If it gets there I'll bump priority.

**Comment by BobyMCbobs** [comment]
https://github.com/kubernetes/kubernetes/pull/89746 attempts to resolve this issue

**Comment by spiffxp** [comment]
Turns out triage was running off of stale data
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=ReplicationController%20should%20test

**Comment by BobyMCbobs** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89753/pull-kubernetes-e2e-gce/1246969347528724484/

**Comment by yangkev** [comment]
Ran into this issue too. Logs: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89669/pull-kubernetes-e2e-gce/1250425205034061825/

From: #89669

**Comment by ScrapCodes** [comment]
Ran into this issue too. Logs: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce/1250673516785700865

From: https://github.com/kubernetes/kubernetes/pull/90165

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority critical-urgent
http://storage.googleapis.com/k8s-metrics/flakes-latest.json this is now the top flake affecting pull-kubernetes-e2e-gce

**Comment by aojea** [comment]
analyzing one occurrence seems that this is the error in the apiserver :

```
I0416 07:11:14.380344       1 store.go:366] GuaranteedUpdate of /registry/controllers/replication-controller-585/rc-test failed because of a conflict, going to retry
I0416 07:11:14.380640       1 httplog.go:90] verb="PATCH" URI="/api/v1/namespaces/replication-controller-585/replicationcontrollers/rc-test/scale" latency=272.933935ms resp=409 UserAgent="e2e.test/v1.19.0 (linux/amd64) kubernetes/046200c -- [sig-apps] ReplicationController should test the lifecycle of a ReplicationController" srcIP="34.70.33.26:51590": 
```

@liggitt is the problem that it should retry per the message, but it never does it?

**Comment by liggitt** [comment]
Yes, this is a real bug.

The application of the patch sent to scale subresources should be done inside the guaranteedupdate loop. Reproducer test and fix in progress at https://github.com/kubernetes/kubernetes/pull/90342

**Comment by BobyMCbobs** [comment]
Made a PR to mark this test as flaky in the meanwhile:
https://github.com/kubernetes/kubernetes/pull/90354
