### ISSUE TITLE
etcd backup and restore questtion

### ISSUE THREAD

**Issue by liaotx** [kubernetes/kubernetes#89758]
in my env ,i had try to backup my data via etcd ，when i restore my data ,my node doesn't restore . my node is in a not ready status .

i want to know this  etcd  will not restore  node while that  status is not-ready ?

this is a common question about etcd but not associate my env.

thanks!

**Comment by sirsikar-lalit** [comment]
etcd backup and restore is context aware of machines - needs to be performed on same set of machines with similar ip-address and hostname.

Ref: https://elastisys.com/2018/12/10/backup-kubernetes-how-and-why/

I tested backup from one cluster and restore to another cluster, etcd captures exact nodes, pods, svc etc. information alongwith cluster ip-address, node-port ip address - exact replica over to another cluster.

Sounds like backup and restore to same cluster is entirely possible, but not to a new cluster with different ip-address and hostnames.

**Comment by liaotx** [comment]
> etcd backup and restore is context aware of machines - needs to be performed on same set of machines with similar ip-address and hostname.
> 
> Ref: https://elastisys.com/2018/12/10/backup-kubernetes-how-and-why/
> 
> I tested backup from one cluster and restore to another cluster, etcd captures exact nodes, pods, svc etc. information alongwith cluster ip-address, node-port ip address - exact replica over to another cluster.
> 
> Sounds like backup and restore to same cluster is entirely possible, but not to a new cluster with different ip-address and hostnames.

thanks , there is in a same env ,but my node is a fake node what use a yaml to add.
so i want to know that in a same env ,etcd will restore my fake node when my node status is not-ready?
