### ISSUE TITLE
watch does not work for GET of an individual object

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#89755]
**What happened**:
I fetched the `master` branch of k/k and used `hack/local-up-cluster.sh`  to create a simple cluster for testing.  In another shell I tried to watch one individual object, but I did not get a stream of notifications (only the initial object).  Following is a typescript; note the immediate completion (there was no ^C).
```
mspreitz@mjs-dev-1:~$ curl 'http://localhost:8080/api/v1/namespaces/kube-system/configmaps/kube-dns?watch=1&resourceVersion=100'
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "kube-dns",
    "namespace": "kube-system",
    "selfLink": "/api/v1/namespaces/kube-system/configmaps/kube-dns",
    "uid": "5cbec4ed-6bdc-4306-bbed-4f95e8f6daf0",
    "resourceVersion": "159",
    "creationTimestamp": "2020-04-02T04:11:32Z",
    "labels": {
      "addonmanager.kubernetes.io/mode": "EnsureExists"
    },
    "managedFields": [
      {
        "manager": "kubectl",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2020-04-02T04:11:32Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:metadata":{"f:labels":{".":{},"f:addonmanager.kubernetes.io/mode":{}}}}
      }
    ]
  }
}mspreitz@mjs-dev-1:~$ 
```

**What you expected to happen**:
I expected behavior like I get from `curl 'http://localhost:8080/api/v1/namespaces/kube-system/configmaps?watch=1&resourceVersion=100'` --- that is, an object is returned immediately and the stream is left open for further notifications.

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): commit 96109680a4a311eb1278edd64ce3b4c8ad8cdd7d
- Cloud provider or hardware configuration: none
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux mjs-dev-1 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hack/local-up-cluster.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
`curl 'http://localhost:8080/api/v1/nodes/127.0.0.1?watch=1&resourceVersion=100'` also returns one object and immediately completes.

**Comment by liggitt** [comment]
watch only operates on lists. To watch a single object, watch with a fieldSelector of metadata.name=$name
