### ISSUE TITLE
As of v1.18.0 release kubelet.service and 10-kubeadm.conf not provided as documented

### ISSUE THREAD

**Issue by Xenwar** [kubernetes/kubernetes#89757]
**What happened**:
Starting v1.18.0 release kubelet.service and 10-kubeadm.conf downloads not provided

**What you expected to happen**:
As describe in [Documentation](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl), under 'Container Linux', I tried to download the two files with curl, but got 404. Previous releases still work though. 

As was the case in previous releases, adding the files solves the problem. If location has been changed or are no longer downloadable, please do update the documentation accordingly. 

**How to reproduce it (as minimally and precisely as possible)**:
For comparison, please run the following.

```
for RELEASE in v1.15.0 v1.16.0 v1.17.0 v1.18.0;do
  echo "===========${RELEASE}=============="
  curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/kubelet.service";echo "" 
  curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/${RELEASE}/build/debs/10-kubeadm.conf";echo ""
done
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.0
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): NA
- Kernel (e.g. `uname -a`): NA
- Install tools: NA
- Network plugin and version (if this is a network-related bug): NA
- Others:

**Comment by neolit123** [comment]
the fix is up but not approved yet.

please watch:
https://github.com/kubernetes/website/pull/20021

/close
