### ISSUE TITLE
Improve or document behaviour of YAML decoder

### ISSUE THREAD

**Issue by glyn** [kubernetes/kubernetes#89764]
**What would you like to be added**:

Remove, or at least document, what appear to be restrictions in the way YAML is handled by the API machinery YAML utility.

**Why is this needed**:

I tried using the API machinery YAML utility to split a stream of YAML documents into individual documents. It doesn’t seem to cope with certain cases and I am wondering if that was intentional, a restriction, or what.

In particular, directives don't appear to be grouped with the document they apply to. For example:
```
%YAML 1.2
---
a: b
...
%YAML 1.2
---
c: d
```

splits into three documents instead of two:
```
%YAML 1.2
```
```
a: b
...
%YAML 1.2
```
```
c: d
```

See the code here which reproduces the above: https://play.golang.org/p/fgqRm_16LJV.

There are also small issues around when newlines are preserved.

Ideally, `NewDocumentDecoder` should satisfy these properties:
* each document produced should be a valid YAML document consisting of a substring of the input string
* when the documents produced are concatenated together, the resultant string should be equal to the input string

Here is some code and a test which pins down the unexpected behaviour a bit better: [split.go.txt](https://github.com/kubernetes/apimachinery/files/4419616/split.go.txt),[split_test.go.txt](https://github.com/kubernetes/apimachinery/files/4419617/split_test.go.txt). (I added the `.txt` to the filenames since I couldn't attach `.go` files.)

## Related issues

* Thanks @dims for pointing this out: https://github.com/kubernetes/kubernetes/issues/34146
* I unwittingly raised the above issue here first: https://github.com/kubernetes/apimachinery/issues/91

**Comment by fedebongio** [comment]
/help-wanted 
We need to evaluate if is an easy fix, or at least document it if it's not
