### ISSUE TITLE
Capture spew.Sprintf() with all our favorite config into a util func

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8976]
util.PrettyPrintObject() or something.  Then find all the places that printf %#v on an object and use this instead.

**Comment by thockin** [comment]
@mhrgoog another relatively inconsequential cleanup that will let you explore some aspects of the project

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by thockin** [comment]
Another that might be worth considering is https://github.com/sanity-io/litter - I like that emits Go-style literals.  Unclear if that can be compacted into 1 line, if it handles map keys and things as well as spew does.

**Comment by thockin** [comment]
I like litter - give it a shot

**Comment by nikhita** [comment]
I'm going to label this a good-first-issue because the changes are relatively easier and there is already a PR (which was closed due to age) that can be used as a reference: https://github.com/kubernetes/kubernetes/pull/55383

/good-first-issue

**Comment by gokultp** [comment]
I would like to take this up.
/assign

**Comment by gokultp** [comment]
I compared the performances of both spew and litter packages. attaching the benchmarks below.
```
goos: linux
goarch: amd64
pkg: github.com/gokultp/bookmark_pretty_printers
BenchmarkLitter-4   	  300000	      4679 ns/op	    1824 B/op	      79 allocs/op
BenchmarkSpew-4   	  500000	      2668 ns/op	     656 B/op	      26 allocs/op
PASS
```

clearly spew is performing better than litter, so I am using spew for writing the util function.

**Comment by thockin** [comment]
This is good insight, but raw perf should not be the only metric.  We
should evaluate output for human readability.

**Comment by thockin** [comment]
Also there's https://github.com/kr/pretty

Also we should file a bug againstlitter to see if they can do better (I
like their output better than spew)

**Comment by gokultp** [comment]
Actually  https://github.com/kr/pretty is working well.  here is the benchmarks
```
BenchmarkPretty-4   	  500000	      2653 ns/op	     360 B/op	      14 allocs/op
BenchmarkLitter-4   	  300000	      4717 ns/op	    1824 B/op	      79 allocs/op
BenchmarkSpew-4   	  500000	      2639 ns/op	     656 B/op	      26 allocs/op
```

also attaching the formatted outputs

1. spew:
```
{{foo false 12344} 1234.123 [foo bar]}
```
2. linter:
```
main.TestType{
          Field1: main.SubType{
            Field2: "foo",
            Field3: false,
            Field4: 12344,
          },
          Field5: 1234.123,
          Field6: []string{
            "foo",
            "bar",
          },
        }
```
3. pretty : 
```
main.TestType{Field1:main.SubType{Field2:"foo", Field3:false, Field4:12344}, Field5:1234.123, Field6:[]string{"foo", "bar"}}
```


so I'll be changing the util function to use https://github.com/kr/pretty,  as it is giving  better performance and almost the same output.

**Comment by gauravwalecha101** [comment]
It seems like fanzhangio has already resolved the aim of this ticket. What all things are left in this to work ?

**Comment by akki** [comment]
Hi
Can this ticket be marked as closed or is there anything left? I would like to help, if required.

**Comment by pmadhvi** [comment]
Hi,
Is this ticket closed or still open. 
I wanted to take this .

**Comment by haoruan** [comment]
Based on https://github.com/kubernetes/utils/pull/226#issuecomment-1279600221, we decided to work on k/k first, then move to kubernetes/utils @thockin
