### ISSUE TITLE
Describe how resource namespace and name are determined for get/list/watch requests, in authorization and API Priority and Fairness

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#89772]
**What happened**:
I have a client that needs to watch just one object, and I want to write RBAC that grants it only the privilege to watch one object.  But I can not do that because a watch only operates on lists.
#89755 

**What you expected to happen**:
I expected to be able to write a client that watches only one object and grant it only the privilege to do that.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
watching a single item (e.g. namespaces) with `fieldSelector=metadata.name=mynamespace` can be authorized with the following role:

```yaml
- verbs: ["watch"]
  resources: ["namespaces"]
  resourceNames: ["mynamespace"]
```

**Comment by liggitt** [comment]
Added in https://github.com/kubernetes/kubernetes/pull/63469, available since 1.11

**Comment by MikeSpreitzer** [comment]
@liggitt : where is that documented?

**Comment by liggitt** [comment]
It's scattered around a few places:

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resource-operations-read

> List: List will retrieve all resource objects of a specific type within a namespace, and the results can be restricted to resources matching a selector query.
> ...
> Watch: Watch will stream results for an object(s) as it is updated. Similar to a callback, watch is used to respond to resource changes.

[Filtering to a single item with a `metadata.name` field selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields):

> All resource types support the metadata.name and metadata.namespace fields.

[RBAC authorization rules for a single item](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources):

> You can also refer to resources by name for certain requests through the resourceNames list. When specified, requests can be restricted to individual instances of a resource.

(the two CRUD request types it doesn't work for, `create` and `deletecollection`, are called out)

**Comment by MikeSpreitzer** [comment]
@liggitt : the surprise is that field selectors on metadata.namespace and metadata.name contribute to the authorization decision.  For example, https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources "RBAC refers to resources using exactly the same name that appears in the URL for the relevant API endpoint" and continues with an example showing a URL for an individual, not a list restricted by metadata.name.  Reviewing that and the general doc on authorization, I see that nothing specifically focuses the URL's path as opposed to its query parameters.  But since I am surprised, I think it is worth explicitly calling this out in the general authorization documentation.

**Comment by liggitt** [comment]
Agree adding details about how resource name is determined to https://kubernetes.io/docs/reference/access-authn-authz/authorization/#review-your-request-attributes and https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources would make sense.

**Comment by liggitt** [comment]
reopened as doc issue

**Comment by MikeSpreitzer** [comment]
@liggitt : BTW, using Kind=namespace is confusingly degenerate.  I had a colleague test with Kind=ConfigMap, specifying both namespace and name in field selectors NOT the URL's path.  He found that the SubjectAccessReview created for his Authorization webhook contained the name but not the namespace!  This was in release 1.14.

**Comment by MikeSpreitzer** [comment]
While the target object name specified in either the URL's path or the URL's query will be considered in authorization and in APF, a target object namespace specified in the URL's query will be ignored by authorization and APF.

**Comment by liggitt** [comment]
limiting a watch to a single namespace was already possible via the URL path, so the fieldSelector inspection method for extracting request attributes was not extended to namespace

**Comment by lavalamp** [comment]
It's VERY confusing to having namespace selection possible in both the URL path, and via field selection, and have them checked differently.

That said, it isn't a security bug since the power to list over all namespaces (e.g., omit namespace in the path) is a superset of the power to list particular namespaces.

Why do we permit field selection of metadata.namespace at all?

**Comment by liggitt** [comment]
> Why do we permit field selection of metadata.namespace at all?

My guess is the same code was used for field extraction for downward API and fieldSelector matching long long ago

**Comment by lavalamp** [comment]
We should either deprecate and remove that ability, or make it checked the same either way.

And document this in the mean time.

Does anyone even use this? It might not be hard to remove?

**Comment by lavalamp** [comment]
> Why do we permit field selection of metadata.namespace at all?

(I don't actually want to know the answer, it was probably me, but in my defense, it would have been written before RBAC was a thing.)

**Comment by MikeSpreitzer** [comment]
> Does anyone even use this [specify namespace via field selector]? It might not be hard to remove?

Yes, I found code from colleagues doing that.  Apparently the authors were unaware that there was any important difference between the two ways of specifying the namespace.  [In fact there is: putting the namespace in the URL path makes the client work with fewer privileges.]  Given the lack of documentation, this is not inexcusable.

**Comment by MikeSpreitzer** [comment]
Since _this_ PR is in k/k, let's use it for fixing the comments in the code.  I made a PR in the doc PR (https://github.com/kubernetes/website/issues/20071) for the user-facing doc work.
