### ISSUE TITLE
Restarting kubelet while fsGroup is applied results in pod getting started with mixed group ownership

### ISSUE THREAD

**Issue by JensErat** [kubernetes/kubernetes#89776]
**What happened**:

Volumes with a large number of files take quite some time when getting mounted if `fsGroup` enforces the group ID. If kubelet gets restarted for whatever reason during this time, the disk is already mounted but the `chgrp`-operation has not finished, permissions have only partially been applied.

**What you expected to happen**:

All files have `fsGroup` group ownership.

**How to reproduce it (as minimally and precisely as possible)**:

- create a volume with lots of files
- mount in pod with another `fsGroup`
- kubelet now applies new group ownership
- restart kubelet while this operation is still going on
- check file ownership, which is now mixed

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.6, v1.17.3
- Cloud provider or hardware configuration: custom/kubeadm
- OS (e.g: `cat /etc/os-release`): Ubuntu 19.10
- Kernel (e.g. `uname -a`): 5.3.0-29-generic
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
/remove-lifecycle stale
