### ISSUE TITLE
Workload updates do not honor PodDisruptionBudget

### ISSUE THREAD

**Issue by codesome** [kubernetes/kubernetes#89820]
**What happened**:

I have 2 StatefulSets with 1 pod in each StatefulSet with a common label lets say `name: mycode`.

I have set up a `PodDisruptionBudget` on `name: mycode` with `minAvailable: 1`.

I applied a change using `kubectl apply` to both StatefulSets at the same time.

Both the pods terminated at the same time without honoring the `PodDisruptionBudget`.

**What you expected to happen**:

`kubectl apply` to follow the `PodDisruptionBudget` specification and rollout 1 pod at a time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have 2 StatefulSets with 1 pod each, with a common label.
2. Set a `PodDisruptionBudget` on the common label.
3. Try applying a change to both StatefulSet at the same time.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Google Cloud

- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
PodDisruptionBudget only limits pod evictions, which I think are only used when draining nodes.

When applying a new statefulset, the statefulset controller makes decisions about how to roll out the new pods based on the update strategy. Kubectl doesn't modify the pods directly (that is true for all workload API objects... the controller managing the object controls rollout of the new child objects).

/sig apps

**Comment by liggitt** [comment]
This is likely a documentation issue around what PodDisruptionBudget's intended use is, rather than a bug

**Comment by alvaroaleman** [comment]
@liggitt shouldn't the statefulset controller (and all other workload controllers for that matter) evict pods rather than deleting them? PDBs are pretty useless if the only thing that respects them is node draining

**Comment by liggitt** [comment]
I'll let sig-apps answer in more detail, but my understanding is that the disruption budgets are intended to cover cross workload eviction of pods for reasons unrelated to a requested rollout of a new version, like node drains.

Most workload API objects have rollout strategy options that describe the options available for controlling rollout of new versions.
