### ISSUE TITLE
[Failing Job] pull-kubernetes-node-e2e-containerd is timing out

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#89847]
**Which jobs are failing**:
pull-kubernetes-node-e2e-containerd

**Which test(s) are failing**:
Timeout

**Since when has it been failing**:
- Last good run (2020-04-03 11:00:09 +0000 UTC): https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e-containerd/1246029654804926464
- First bad run (2020-04-03 12:37:42 +0000 UTC): https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e-containerd/1246054193446260736
- Latest bad run (2020-04-04 01:19:40 +0000 UTC): https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e-containerd/1246245958304403456

**Testgrid link**:
https://testgrid.k8s.io/sig-node-containerd#pull-node-e2e

**Reason for failure**:
```kubetest --timeout triggered```

**Anything else we need to know**:
- triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-node-e2e-containerd

This isn't a merge-blocking test but it is reporting on all PRs

/sig node
/sig release
/priority important-soon

**Comment by Random-Liu** [comment]
All containerd tests are failing, not just the presubmit.

I found this error on the master instance:
```
Apr 06 18:45:55.975305 bootstrap-e2e-master configure-helper.sh[1012]: [90B blob data]
Apr 06 18:45:55.975759 bootstrap-e2e-master configure-helper.sh[1012]: Creating filesystem with 5242880 4k blocks and 1310720 inodes
Apr 06 18:45:55.975869 bootstrap-e2e-master configure-helper.sh[1012]: Filesystem UUID: a8e337f7-0a55-44cf-a8ed-ef8d6f9384c8
Apr 06 18:45:55.975916 bootstrap-e2e-master configure-helper.sh[1012]: Superblock backups stored on blocks:
Apr 06 18:45:55.976163 bootstrap-e2e-master configure-helper.sh[1012]:         32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
Apr 06 18:45:55.976209 bootstrap-e2e-master configure-helper.sh[1012]:         4096000
Apr 06 18:45:55.976512 bootstrap-e2e-master configure-helper.sh[1012]: [57B blob data]
Apr 06 18:45:55.978262 bootstrap-e2e-master configure-helper.sh[1012]: [54B blob data]
Apr 06 18:45:56.832972 bootstrap-e2e-master configure-helper.sh[1012]: Creating journal (32768 blocks): done
Apr 06 18:45:57.155328 bootstrap-e2e-master configure-helper.sh[1012]: [91B blob data]
Apr 06 18:45:57.156760 bootstrap-e2e-master configure-helper.sh[1012]: Mounting '/dev/disk/by-id/google-master-pd' at '/mnt/disks/master-pd'
Apr 06 18:45:57.205111 bootstrap-e2e-master configure-helper.sh[1012]: Mounted master-pd '/dev/disk/by-id/google-master-pd' at '/mnt/disks/master-pd'
Apr 06 18:45:57.229862 bootstrap-e2e-master configure-helper.sh[1012]: chown: invalid user: ‘etcd’
```

**Comment by Random-Liu** [comment]
I think this is the issue https://github.com/kubernetes/kubernetes/commit/c7abf44a197867234c5f3732267354ce41dc2783

**Comment by cheftako** [comment]
I agree that https://github.com/containerd/cri/pull/1429 seems to be the fix. https://github.com/kubernetes/kubernetes/pull/88856 merged 10 days ago and the failures started 3 days ago. While they are clearly related, there seems to be a piece missing to the story.

**Comment by Random-Liu** [comment]
> I agree that containerd/cri#1429 seems to be the fix. #88856 merged 10 days ago and the failures started 3 days ago. While they are clearly related, there seems to be a piece missing to the story.

The cluster e2e test started failing 10 days ago. containerd/cri#1429 should fix it.

However, the node e2e seems to be failing because of a different issue.

**Comment by Random-Liu** [comment]
I believe the node e2e tests failure (including regular node e2e tests failure) are caused by no network access to the GCE project.

Google shutdown the network access to those GCE projects for some security reason...

**Comment by Random-Liu** [comment]
We need to update COS and ubuntu images used by all node e2e tests to fix this.

**Comment by spiffxp** [comment]
I suggest we have this job stop reporting to all PRs if this is going to take a while to fix.

I know it's not merge-blocking because its context doesn't have "required" next to it, but I think a lot of people just see the bot commenting about a failure and instinctively /retest.

**Comment by hasheddan** [comment]
@Random-Liu do you think the GCE network access is causing the failures in #89892 and #89893?

**Comment by saschagrunert** [comment]
/assign @spiffxp 

Can you please add the latest information and close this one out? (Just discussed it in the release engineering meeting right now)

**Comment by saschagrunert** [comment]
@derekwaynecarr will request a new GCP project in k8s wg infra to add the SIG node jobs

**Comment by spiffxp** [comment]
Getting this to run over in wg-k8s-infra is going to take some time.  Expect something in the next two weeks. (ref: https://github.com/kubernetes/k8s.io/issues/752#issuecomment-621371086)

As these aren't release blocking or merge blocking tests I haven't spent time dissecting whether there is something unique about this project that requires it be used for containerd tests.  Someone is welcome to try assigning one of these to the node-e2e-project pool and see what happens.

**Comment by hasheddan** [comment]
@spiffxp I will try moving it over today 👍 

/assign

**Comment by hasheddan** [comment]
`containerd-node-conformance` is green since #17452 https://testgrid.k8s.io/sig-node-containerd#containerd-node-conformance

**Comment by MHBauer** [comment]
n00b here looking at `
pull-kubernetes-node-e2e-containerd` for sig-node test analysis project. 

I see this quota exceeded message in a lot of the failing test groups in sig-node-containerd. I think this is a known issue. 

How can I help? 

```
I0519 17:09:50.773] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0519 17:09:50.773] >                              START TEST                                >
I0519 17:09:50.773] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0519 17:09:50.773] Start Test Suite on Host 
I0519 17:09:50.773] 
I0519 17:09:50.773] Failure Finished Test Suite on Host 
I0519 17:09:50.774] unable to create gce instance with running docker daemon for image cos-77-12371-251-0.  could not create instance tmp-node-e2e-fc88dbbe-cos-77-12371-251-0: [&{Code:QUOTA_EXCEEDED Location: Message:Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 69.0 in region us-west1. ForceSendFields:[] NullFields:[]}]
I0519 17:09:50.774] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0519 17:09:50.774] <                              FINISH TEST                               <
I0519 17:09:50.774] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0519 17:09:50.774] 
I0519 17:09:50.872] 
I0519 17:09:50.872] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0519 17:09:50.872] >                              START TEST                                >
I0519 17:09:50.872] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0519 17:09:50.872] Start Test Suite on Host 
I0519 17:09:50.872] 
I0519 17:09:50.873] Failure Finished Test Suite on Host 
I0519 17:09:50.873] unable to create gce instance with running docker daemon for image ubuntu-gke-1804-1-15-v20200519.  could not create instance tmp-node-e2e-fc88dbbe-ubuntu-gke-1804-1-15-v20200519: [&{Code:QUOTA_EXCEEDED Location: Message:Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 69.0 in region us-west1. ForceSendFields:[] NullFields:[]}]
I0519 17:09:50.873] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0519 17:09:50.873] <                              FINISH TEST                               <
I0519 17:09:50.873] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
```

**Comment by liggitt** [comment]
Disabling the optional silent job in https://github.com/kubernetes/test-infra/pull/18356 until this is resolved, since our CI resources are constrained

**Comment by dims** [comment]
/close

this is fixed.
