### ISSUE TITLE
Kubernetes Deletes Pods Periodically

### ISSUE THREAD

**Issue by saraAlizadeh** [kubernetes/kubernetes#89860]
/sig storage
/priority critical-urgent
Hi everyone,
I'm experiencing something really weird in my cluster.
All my pods that have a pvc, are terminated periodically every 1 minute (approximately).

they are recreated again, terminated again and so on.

this has caused sooo many problems, like many many orphaned pod. work load is not deniable.

I see lots of error logs in my monitoring stack. which is kube-promethes. but I know they are not the roou cause.
my storage is rook-ceph.its health-status is OK!
my kubernetes version is 1.16.

can any body, please, share some helpful ideas? I'm desperate.

**Comment by liggitt** [comment]
can you provide some additional information to help identify the root cause:
* pod definitions (`kubectl get pod $name -o yaml`)
* events from the pods' namespace (`kubectl get events -n $pod_namespace`)
* logs from the kube-controller-manager and kubelet for a few minutes around when you observe a pod deletion

**Comment by saraAlizadeh** [comment]
**1.** my pods are MySQL and WordPress. there is one of each in every namespaces.
here is the log of watching a sample namespace:
`
kubectl get pod --watch
NAME                               READY   STATUS    RESTARTS   AGE
wordpress-559f878449-7p5vb         1/1     Running   0          40s
wordpress-mysql-689b44677b-qwdkw   1/1     Running   0          6d16h
wordpress-559f878449-7p5vb         1/1     Terminating   0          53s
wordpress-559f878449-7p5vb         0/1     Terminating   0          55s
wordpress-559f878449-7p5vb         0/1     Terminating   0          56s
wordpress-559f878449-7p5vb         0/1     Terminating   0          56s
wordpress-9cdc54996-r46r5          0/1     Pending       0          0s
wordpress-9cdc54996-r46r5          0/1     Pending       0          0s
wordpress-9cdc54996-r46r5          0/1     ContainerCreating   0          0s
wordpress-9cdc54996-r46r5          0/1     Terminating         0          0s
wordpress-9cdc54996-r46r5          0/1     Terminating         0          0s
wordpress-9cdc54996-r46r5          0/1     Terminating         0          10s
wordpress-9cdc54996-r46r5          0/1     Terminating         0          10s
wordpress-6b76b69f75-jjprv         0/1     Pending             0          0s
wordpress-6b76b69f75-jjprv         0/1     Pending             0          0s
wordpress-6b76b69f75-jjprv         0/1     ContainerCreating   0          0s
wordpress-6b76b69f75-jjprv         0/1     ContainerCreating   0          7s
wordpress-6b76b69f75-jjprv         0/1     Terminating         0          47s
wordpress-6b76b69f75-jjprv         0/1     Terminating         0          47s
wordpress-6b76b69f75-jjprv         0/1     Terminating         0          60s
wordpress-6b76b69f75-jjprv         0/1     Terminating         0          60s
wordpress-78dc577d95-7mkzm         0/1     Pending             0          0s
wordpress-78dc577d95-7mkzm         0/1     Pending             0          0s
wordpress-78dc577d95-7mkzm         0/1     ContainerCreating   0          0s
wordpress-78dc577d95-7mkzm         0/1     ContainerCreating   0          2s
wordpress-78dc577d95-7mkzm         1/1     Running             0          3s
`

here is the pod deployment:
`
kubectl get deployment wordpress -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7066"
  creationTimestamp: "2020-03-29T11:12:09Z"
  generation: 45572
  labels:
    app: wordpress
  name: wordpress
  namespace: "00165401412932020154218"
  resourceVersion: "52123256"
  selfLink: /apis/apps/v1/namespaces/00165401412932020154218/deployments/wordpress
  uid: 5964e7af-d667-4482-bafa-f7271b84b53d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        dummy: du_1586258427180
      creationTimestamp: null
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        image: 192.168.xx.xx:8083/wordpress/twentyfifteen
        imagePullPolicy: IfNotPresent
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
`

and we have the pvc:
`kubectl get pvc wordpress-pvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  creationTimestamp: "2020-03-29T11:12:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: wordpress-pvc
  namespace: "00165401412932020154218"
  resourceVersion: "44282913"
  selfLink: /api/v1/namespaces/00165401412932020154218/persistentvolumeclaims/wordpress-pvc
  uid: ad5c1c06-0aa0-4b5b-a562-0e8a1a2468d4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-ad5c1c06-0aa0-4b5b-a562-0e8a1a2468d4
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound`
**2.** 
` kubectl get events  -n
2m29s       Normal    Scheduled                pod/wordpress-ff994d69d-c8b9g     Successfully assigned 00165401412932020154218/wordpress-ff994d69d-c8b9g to worker2.mix.ir
2m29s       Normal    SuccessfulAttachVolume   pod/wordpress-ff994d69d-c8b9g     AttachVolume.Attach succeeded for volume "pvc-ad5c1c06-0aa0-4b5b-a562-0e8a1a2468d4"
2m26s       Normal    Pulled                   pod/wordpress-ff994d69d-c8b9g     Container image "wordpress/twentyfifteen" already present on machine
2m26s       Normal    Created                  pod/wordpress-ff994d69d-c8b9g     Created container wordpress
2m26s       Normal    Started                  pod/wordpress-ff994d69d-c8b9g     Started container wordpress
102s        Normal    Killing                  pod/wordpress-ff994d69d-c8b9g     Stopping container wordpress
2m29s       Normal    SuccessfulCreate         replicaset/wordpress-ff994d69d    Created pod: wordpress-ff994d69d-c8b9g
102s        Normal    SuccessfulDelete         replicaset/wordpress-ff994d69d    Deleted pod: wordpress-ff994d69d-c8b9g
99s         Normal    ScalingReplicaSet        deployment/wordpress              (combined from similar events): Scaled up replica set wordpress-fd695c95c to 1
11m         Normal    ScalingReplicaSet        deployment/wordpress              Scaled up replica set wordpress-5996c7799b to 1
10m         Normal    ScalingReplicaSet        deployment/wordpress              Scaled down replica set wordpress-5996c7799b to 0
10m         Normal    ScalingReplicaSet        deployment/wordpress              Scaled up replica set wordpress-7b747b955c to 1
8m42s       Normal    ScalingReplicaSet        deployment/wordpress              Scaled down replica set wordpress-7b747b955c to 0
8m39s       Normal    ScalingReplicaSet        deployment/wordpress              Scaled up replica set wordpress-5bd9dfd9bd to 1
6m39s       Normal    ScalingReplicaSet        deployment/wordpress              Scaled up replica set wordpress-9cdc54996 to 1`

**3.**logs from the kube-controller-manager and kubelet

`
ssh worker2 journalctl -exu kubelet
Apr 07 15:58:20 worker2.mix.ir kubelet[2217]: E0407 15:58:20.306323    2217 kubelet_volumes.go:154] orphaned pod "0f027ffb-61be-                             4a2a-81cd-dc68bd503769" found, but volume paths are still present on disk : There were a total of 23 errors similar to this. Turn up verbosity to see them.
Apr 07 15:58:22 worker2.mix.ir kubelet[2217]: E0407 15:58:22.331915    2217 kubelet_volumes.go:154] orphaned pod "0f027ffb-61be-                             4a2a-81cd-dc68bd503769" found, but volume paths are still present on disk : There were a total of 23 errors similar to this. Turn up verbosity to see them.
`
`
kubectl logs kube-controller-manager-master1.mix.ir -n kube-system --tail=10
I0407 11:31:30.403431       1 reconciler.go:288] attacherDetacher.AttachVolume started for volume "pvc-xx" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-27433f2a-6c60-11ea-a2ae-6ac7d7183376") from node "worker2.mix.ir"
I0407 11:31:30.414376       1 operation_generator.go:390] AttachVolume.Attach succeeded for volume "pvc-xx" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-27433f2a-6c60-11ea-a2ae-6ac7d7183376") from node "worker2.mix.ir"
I0407 11:31:30.414443       1 event.go:274] Event(v1.ObjectReference{Kind:"Pod", Namespace:"x", Name:"wordpress-mysql-85fd4c55b4-w8ggd", UID:"fd88d8f3-b4c2-4b83-95d6-e1295ac9a79a", APIVersion:"v1", ResourceVersion:"52128943", FieldPath:""}): type: 'Normal' reason: 'SuccessfulAttachVolume' AttachVolume.Attach succeeded for volume "pvc-xx"
I0407 11:31:36.110516       1 event.go:274] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"x", Name:"wordpress", UID:"3cff0a2e-535d-4180-998c-eb37ed3f66e8", APIVersion:"apps/v1", ResourceVersion:"52128876", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set wordpress-655765f777 to 1
I0407 11:31:36.121071       1 event.go:274] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"x", Name:"wordpress-655765f777", UID:"148b904d-2417-401a-902c-e87c2a95f903", APIVersion:"apps/v1", ResourceVersion:"52128988", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: wordpress-655765f777-5ph6b
I0407 11:31:36.231683       1 reconciler.go:288] attacherDetacher.AttachVolume started for volume "pvc-xx" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-65721ef8-71b3-11ea-8913-c6694bca9815") from node "worker3.mix.ir"
I0407 11:31:36.243467       1 operation_generator.go:390] AttachVolume.Attach succeeded for volume "pvc-xx" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-65721ef8-71b3-11ea-8913-c6694bca9815") from node "worker3.mix.ir"
I0407 11:31:36.243669       1 event.go:274] Event(v1.ObjectReference{Kind:"Pod", Namespace:"x", Name:"wordpress-655765f777-5ph6b", UID:"6c437817-0f0d-4de4-892d-63635397d65d", APIVersion:"v1", ResourceVersion:"52128994", FieldPath:""}): type: 'Normal' reason: 'SuccessfulAttachVolume' AttachVolume.Attach succeeded for volume "pvc-yy"
I0407 11:32:23.350388       1 event.go:274] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"x", Name:"wordpress", UID:"3cff0a2e-535d-4180-998c-eb37ed3f66e8", APIVersion:"apps/v1", ResourceVersion:"52129275", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set wordpress-655765f777 to 0
I0407 11:32:23.364679       1 event.go:274] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"x", Name:"wordpress-655765f777", UID:"148b904d-2417-401a-902c-e87c2a95f903", APIVersion:"apps/v1", ResourceVersion:"52129276", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: wordpress-655765f777-5ph6b
`

**Comment by ydcool** [comment]
Hi @saraAlizadeh 
Just a little advise, the logs will be more readable if you paste the logs with code block like this:
<pre>
```
kubectl get pod --watch
NAME READY STATUS RESTARTS AGE 
wordpress-559f878449-7p5vb 1/1 Running 0 40s 
wordpress-mysql-689b44677b-qwdkw 1/1 Running 0 6d16h 
wordpress-559f878449-7p5vb 1/1 Terminating 0 53s

kubectl get events -n
2m29s Normal Scheduled pod/wordpress-ff994d69d-c8b9g Successfully assigned 00165401412932020154218/wordpress-ff994d69d-c8b9g to worker2.mix.ir 
2m29s Normal SuccessfulAttachVolume pod/wordpress-ff994d69d-c8b9g AttachVolume.Attach succeeded for volume "pvc-ad5c1c06-0aa0-4b5b-a562-0e8a1a2468d4" 
2m26s Normal Pulled pod/wordpress-ff994d69d-c8b9g Container image "wordpress/twentyfifteen" already present on machine 
```
</pre>

**Comment by ydcool** [comment]
@saraAlizadeh Looks something wrong with the `orphaned pod` on the worker2 node, coud you try to umount and clean up those pods by hand? It's a little bit like this issue  #60987

**Comment by saraAlizadeh** [comment]
> 
> 
> @saraAlizadeh Looks something wrong with the `orphaned pod` on the worker2 node, coud you try to umount and clean up those pods by hand? It's a little bit like this issue #60987

yes, I've tried it. I can delete them but they keep populating. coz my pod are deleted and their dependencies are left orphaned. actually I believe orphaned pods are a side effect to my real issue. WHY ARE THE PODS DELETED IN THE FIRST PLACE?

**Comment by saraAlizadeh** [comment]
I upgraded my Kubernetes from 1.16.4 to 1.17.5. also upgraded ceph-rook to latest. (rook v1.3)
everything was ok at first but then again, my pods started terminating and recreating.
could this have a relation with the number of pods or the number of PVs?
I don't know what is causing this...any ideas?
