### ISSUE TITLE
Liveness probe failed: OCI runtime exec failed

### ISSUE THREAD

**Issue by lrouquette** [kubernetes/kubernetes#89862]
**What happened**:
Command-based liveness probes are randomly failing with the below error:
> Liveness probe failed: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 21603 to cgroups caused \"failed to write 21603 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod9b0b86e7-71dc-4101-90ea-fd06f7c8c25a/42a7fe88c0cda2e9c1018665ca9460fb5452d6627da424c7711e8731849019bc/cgroup.procs: invalid argument\"": unknown

This is a major problem for probes configured with `failureThreshold: 1` as the container is restarted, potentially causing outages.

**What you expected to happen**:
No failures, ideally. 
More importantly, since it is the k8s component executing the command that failed, before the command itself is executed, I wouldn't expect the container to be restarted (or the "failureCount" to be incremented); this is a lot different than the command failing.

**How to reproduce it (as minimally and precisely as possible)**:
Hard to forcefully reproduce; perhaps run a bunch of pods with command-based probes for a few hours.

**Anything else we need to know?**:
We have various pods/commands that are failing, and that includes the cilium ones from a [vanilla](https://github.com/cilium/cilium/blob/v1.6.8/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml#L48-L53) daemonset. There doesn't seem to be a pattern though.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.16.7`
- Cloud provider or hardware configuration: AWS, Azure, metal clusters alike
- OS (e.g: `cat /etc/os-release`): `Container Linux by CoreOS 2247.7.0 (Rhyolite)`
- Kernel (e.g. `uname -a`): `Linux ip-10-10-11-239 4.19.84-coreos #1 SMP Tue Nov 19 20:51:06 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz GenuineIntel GNU/Linux`
- Install tools: in-house
- Network plugin and version (if this is a network-related bug): Cilium
- Others:

**Comment by tedyu** [comment]
Have you taken a look at https://github.com/opencontainers/runc/issues/1884 ?
