### ISSUE TITLE
Facing issue while adding a windos server 2019 worker node to K8 master

### ISSUE THREAD

**Issue by sarbajitpattanaik** [kubernetes/kubernetes#89865]
Hi All, having this issue, if you can help:

kubeadm join 10.96.164.243:6443 --token v0rzbf.d8xwioz762gx957z --discovery-token-ca-cert-hash sha256:2f855d5997c18d54a677bef407b0954b2cde979503b0c313152276c40d5b9b4f --v=5
W0404 18:43:17.974224    2676 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
I0404 18:43:17.976219    2676 join.go:371] [preflight] found NodeName empty; using OS hostname as NodeName
I0404 18:43:17.978219    2676 initconfiguration.go:103] detected and using CRI socket: npipe:////./pipe/docker_engine
[preflight] Running pre-flight checks
I0404 18:43:17.979228    2676 preflight.go:90] [preflight] Running general checks
I0404 18:43:17.986226    2676 checks.go:249] validating the existence and emptiness of directory \etc\kubernetes\manifests
I0404 18:43:17.988224    2676 checks.go:286] validating the existence of file \etc\kubernetes\kubelet.conf
I0404 18:43:17.988224    2676 checks.go:286] validating the existence of file \etc\kubernetes\bootstrap-kubelet.conf
I0404 18:43:17.989229    2676 checks.go:102] validating the container runtime
I0404 18:43:18.925120    2676 checks.go:128] validating if the service is enabled and active
I0404 18:43:18.927122    2676 checks.go:520] running all checks
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.5. Latest validated version: 19.03
I0404 18:43:20.278943    2676 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0404 18:43:20.289950    2676 checks.go:618] validating kubelet version
I0404 18:43:20.423654    2676 checks.go:128] validating if the service is enabled and active
I0404 18:43:20.424653    2676 checks.go:201] validating availability of port 10250
I0404 18:43:20.425650    2676 checks.go:286] validating the existence of file C:/etc/kubernetes/pki/ca.crt
I0404 18:43:20.425650    2676 checks.go:432] validating if the connectivity type is via proxy or direct
        [WARNING HTTPProxy]: Connection to "https://10.96.164.243" uses proxy "http://58.162.139.110:3128". If that is not intended, adjust your proxy settings
I0404 18:43:20.426654    2676 join.go:441] [preflight] Discovering cluster-info
I0404 18:43:20.427680    2676 token.go:78] [discovery] Created cluster-info discovery client, requesting info from "10.96.164.243:6443"
I0404 18:43:20.431920    2676 token.go:215] [discovery] Failed to request cluster-info, will try again: Get https://10.96.164.243:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: Forbidden
I0404 18:43:20.434151    2676 token.go:215] [discovery] Failed to request cluster-info, will try again: Get https://10.96.164.243:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: Forbidden
I0404 18:43:26.854308    2676 token.go:215] [discovery] Failed to request cluster-info, will try again: Get https://10.96.164.243:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: Forbidden
I0404 18:43:32.856036    2676 token.go:215] [discovery] Failed to request cluster-info, will try again: Get https://10.96.164.243:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: Forbidden
I0404 18:43:38.526113    2676 token.go:215] [discovery] Failed to request cluster-info, will try again: Get https://10.96.164.243:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: Forbidden

**Comment by neolit123** [comment]
please open the same issue in https://github.com/kubernetes-sigs/sig-windows-tools
thanks
/close
