### ISSUE TITLE
Need better debug logging for patch operations

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#89874]
**What would you like to be added**:
I would like debug logging to show the heart of the processing of a patch request.  For example, showing the inputs and outputs of https://github.com/kubernetes/apiserver/blob/fa3c8ad6d7aff4ba13bf7296583ed2815db1be44/pkg/endpoints/handlers/patch.go#L620 .

**Why is this needed**:
It is way too easy to botch a PATCH request.  Due to the way JSON decoding happily and silently discards unexpected contents, it is very easy to accidentally write buggy code that provokes no error.  There is no existing debug logging to help a developer see the error in their ways.
I spent a lot of time chasing a bug that was immediately evident when I put in debug logging about the line mentioned above.

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by MikeSpreitzer** [comment]
This mah be particularly helpful to someone struggling with #89875

**Comment by MikeSpreitzer** [comment]
FYI, for a comparison of similar debug logging you can try setting `-v=5` and seeing what gets logged.  You can also try some higher settings.  You will see request bodies logged at the site where the call goes out.  I did not see request bodies logged on the receiving side.

**Comment by MikeSpreitzer** [comment]
FYI, here is the debug logging statement that I used:
```
	klog.V(8).Infof("Applied %#+v to %#+v to produce %#+v, err=%#+v", patchMap, originalMap, patchedObjMap, err)
```

That was right after the call to `strategicpatch.StrategicMergeMapPatch`.

**Comment by MikeSpreitzer** [comment]
It would be appropriate to do the same for the case of JSON Patch and JSON Merge Patch as well as the stategic merge patch.

**Comment by liggitt** [comment]
> I did not see request bodies logged on the receiving side.

That's somewhat intentional. Logging of API server request bodies without regard to whether the resource is a confidential one (e.g. secrets) would expose confidential content. If we add debug output of Request bodies to the API server log, we'll need to do so in a way that is not considered a vulnerability.

**Comment by MikeSpreitzer** [comment]
Good point.  So would it suffice to carve out an exception for objects of the core Secret kind?

**Comment by liggitt** [comment]
> So would it suffice to carve out an exception for objects of the core Secret kind?

The audit logging and storage encryption mechanisms do not special-case secret resources, I would not expect this to.

**Comment by twisted-sres** [comment]
Can I take this up as my first issue? Any pointers would be helpful.

**Comment by MikeSpreitzer** [comment]
@twisted-sres : yes.
@liggitt : your last remark looks like a complete rejection of this issue.  Is there something you think can be done here?

**Comment by liggitt** [comment]
> your last remark looks like a complete rejection of this issue. Is there something you think can be done here?

In general, I don't want to increase the number of ways confidential data can leak into server logs. Are there other ways we could ease testing patches (like simpler use of patching functions in a library/unit test) or surface potential problems (like returning warnings, similar to the mechanism proposed in https://github.com/kubernetes/kubernetes/pull/73032)?

**Comment by MikeSpreitzer** [comment]
The particularly difficult thing about patching is that it is very easy for a client developer to make a mistake that produces an unexpected result and NO error NOR warning message on the server.  Just goof up a field name or a bit of structure, and the patch has little or no effect on the target object.

I suppose it should be possible --- for JSON merge and for strategic merge patches --- to add a check on the server side, comparing the patch with the patched object to see if the patch contains material that does not appear in the patched object.  It should be possible to also do a similar check for a JSON patch, looking for patch material that had no effect.  Would there be a way to plumb a warning from these out to a reply header?

**Comment by liggitt** [comment]
> Would there be a way to plumb a warning from these out to a reply header?

I actually just started a proposal for server -> client warnings (https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1693-warnings) which could surface something like that in the future, though getting the "field X in patch didn't exist so was ignored" plumbed out of the patch/json stack without erroring would be non-trivial as well.

**Comment by lavalamp** [comment]
Note that users can and should use dry run to verify their change will have the desired effect.

**Comment by TARIKPHON85** [comment]
Thanks

**Comment by tranbaominh** [comment]
#89874

**Comment by leilajal** [comment]
@MikeSpreitzer what is the status of this issue? can we close this one if we follow up with the client warnings instead of generating new logs?
