### ISSUE TITLE
Code cleanup: better document pointers

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#8991]
I feel like there is a lot of code that is written in ugly ways because we are not clear about pointer ownership and mutability.  Deep down in the guts of the code you get a *api.Pod - can you assume it is not nil?  Can you change fields in it?

This is a tedious things to retrofit, but I think it would make a lot of code more obvious (e.g. I suspect a lot of our "need" for deep copy comes from this)

**Comment by smarterclayton** [comment]
Closing due to age and general lack of interest, reopen if passionate.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (186/150 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:45644 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dGU9N-000RBY-Am
	for dev@imwiz.com; Thu, 01 Jun 2017 11:44:45 -0600
Date: Thu, 01 Jun 2017 10:37:37 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1496338657;
	bh=C7ipu35hddNugc/VwJUyzaobwTkrDUdemNMndVgLtDc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TTJUxpFnVsB10scHtj1TGOxWSxlNaIUqWvNG+7HN5xJhFkT3MvrSbChHkkRBUfN7w
	 q238YiScTP+Lo/PSmBwX0zuoKlZi00p7bhpuVRJCTOlWypiWvwO21m+pdw17QCQnKT
	 YkHZgIcpHPe9xkA5ec6RCioeenjzfzMP4VPjFPrE=
