### ISSUE TITLE
kubectl apply sets data to an empty string if you remove corresponding values from stringData

### ISSUE THREAD

**Issue by dobesv** [kubernetes/kubernetes#89938]
I used `kubectl apply` to update a secret, and I specified values in plaintext using `stringData`.  Each time I updated a different key using this method, the previous keys set using the same method were reset to a blank value.

After some head-scratching I found that the `last-applied-configuration` annotation stored the `stringData` values previously applied, and when `apply` sees that the value is no longer present in a new `stringData` it supplies an empty value for that entry in `stringData`.

**What you expected to happen**:

The transformation from `stringData` to `data` would happen prior to calculating the `last-applied-configuration` so that a future apply does not undo the prior one.

**How to reproduce it (as minimally and precisely as possible)**:

Use `kubectl apply` on a secret and use `stringData` to set the values in plaintext instead of base64.

**Suggested Workaround/Solution**

Do not use `kubectl apply` to edit secrets, use `kubectl edit` or `kubectl replace`.

**Comment by liggitt** [comment]
The transformation happens serverside, and the last applied annotation is computed client-side. That's not likely to interact well...

**Comment by dobesv** [comment]
I'm a bit puzzled that the values were blanked out, I think the main issue here is that the values were set to an empty string rather than (1) deleted completely from the secret or (2) ignored.

Since I had removed those values compared to the last apply, I thought it would have omitted them when it sent them to the server, or perhaps sent some kind of `null` or `$delete` marker to say the value should be removed.

It seems odd that the server took the `null` or `$delete` value to mean it should apply an empty string.  I don't think I'd get an empty string if I had removed the value directly from `data`.

So maybe this can be solved server-side by changing how the null / delete value is converted to base64, perhaps it could ignore it?  Even if it propagated the deletion to the matching key in `data` I would have been less confused, although that wouldn't be my preferred behavior.

**Comment by liggitt** [comment]
> Since I had removed those values compared to the last apply, I thought it would have omitted them when it sent them to the server

The client-side apply diffs what you apply with the last-applied annotation and anything removed it sends explicit nulls for.

You are expected to apply the full object you want each time, not piecemill fields. I may be misunderstanding what you're doing… a reproducer might be helpful.

**Comment by dobesv** [comment]
```
$ kubectl create secret generic temp --from-literal=FOO=bar
secret/temp created
$ kubectl get secret temp -o yaml >temp.yaml
$ echo "stringData:" >>temp.yaml
$ echo "  FOOFOO: bar" >>temp.yaml
$ kubectl apply -f temp.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
secret/temp configured
$ kubectl get secret temp -o yaml >temp.yaml
$ echo "stringData:" >>temp.yaml
$ echo "  FOOFOOFOO: bar" >>temp.yaml
$ kubectl apply -f temp.yaml
secret/temp configured
$ kubectl get secret temp -o yaml
apiVersion: v1
data:
  FOO: YmFy
  FOOFOO: ""
  FOOFOOFOO: YmFy
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"FOO":"YmFy","FOOFOO":"YmFy"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2020-04-08T05:57:52Z","name":"temp","namespace":"default","resourceVersion":"159582252","selfLink":"/api/v1/namespaces/default/secrets/temp","uid":"001f2087-d424-452b-a234-fc3028ff0b31"},"stringData":{"FOOFOOFOO":"bar"},"type":"Opaque"}
  creationTimestamp: "2020-04-08T05:57:52Z"
  name: temp
  namespace: default
  resourceVersion: "159582375"
  selfLink: /api/v1/namespaces/default/secrets/temp
  uid: 001f2087-d424-452b-a234-fc3028ff0b31
type: Opaque
```

If you don't want to support this use case, then if a value is removed from `stringData` it should probably be removed from `data` as well, rather than treated as an empty string.

It would be nice if it would just ignore it, though.

It also seems like using `apply` with `stringData` results in the values being placed into the annotation without base64 encoding, which is also a bit questionable or troubling.

I've actually changed my script to use `patch` for now, and that's probably the right way to do it.  But I found this behavior confusing for a while so I thought I'd report it in case someone wants to fix it, or someone runs into it themselves and wonders what the status of it is.

**Comment by liggitt** [comment]
it looks like the thing sent in the apply patch to indicate removal (a `null` value in a `stringData` item) gets coerced to `""` by the JSON decoder, so by the time conversion merges/moves the `stringData` into `data`, it can't tell the difference between removal and addition of an empty string item :-/

**Comment by lavalamp** [comment]
cc @apelisse

**Comment by apelisse** [comment]
@seans3

**Comment by seans3** [comment]
@dobesv Can you run `kubectl version` and paste the output here? Thanks

**Comment by apelisse** [comment]
For those who aren't aware of this feature, it is based on this proposal: https://github.com/kubernetes/kubernetes/issues/19575

**Comment by dobesv** [comment]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by apelisse** [comment]
From https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/merge/update.go#L34, a good prediction from Brian ;-):
> I definitely would not want to do this anywhere else, since it would break kubectl apply and probably other things. However, users shouldn't use kubectl apply on secrets, so that reason isn't relevant in this case.

I still have no idea how to fix that.

**Comment by thesuperzapper** [comment]
Just wanted to say, this behaviour causes problems for helm, see https://github.com/helm/helm/issues/10010.

_NOTE: Helm charts often template Secret YAML to add/remove/change keys depending on the chart's values._

---

This `stringData` behaviour is a timebomb, as it violates the core principle of Kubernetes that __the YAML is declarative__. If I apply some YAML to the cluster, I don't expect the in-cluster resource to be different than what I applied.

**Comment by apelisse** [comment]
I strongly believe that this feature is broken by design. We can keep the issue open, but I don't think we'll ever fix this to be honest (I wish someone can prove me wrong :-).

**Comment by zerkms** [comment]
@apelisse indeed, I'm just keeping a number of reports that affect me (or affected me long ago :-D ) so that it was closed with some official "works as designed" or a real fix, both are fine.

**Comment by apelisse** [comment]
As you mentioned earlier, I'm going to close this as "broken by design". I'll even throw a quote from @liggitt [1]:
> StringData is a weird feature that takes data in string format and converts it to []byte when converting to the internal type. Knowing what we know now, we wouldn't do this again

[1]: https://github.com/kubernetes/kubernetes/issues/107442#issuecomment-1008926682
