### ISSUE TITLE
docker images getting deleted when enabling k8s on windows

### ISSUE THREAD

**Issue by vipinponnarath** [kubernetes/kubernetes#89932]
**What happened**:
I am using docker desktop for windows for running some of my local images. I enabled Kubernetes option from the docker settings UI and what I observe from time to time is a lot of my important images are getting removed. I have no proof to say that it is k8s who is deleting these, but i confirm that it happens whenever I enable the kubernetes option from the UI. I read about the image garbage collection policy of k8s and I suspect, k8s is getting confused while evaluating the diskpressure on the MobyLinux VM. I tried to raise an issue first with docker/for-win repository and there I received a comment that it might be an issue with k8s itself and not docker-desktop. Here is the link to that issue  https://github.com/docker/for-win/issues/6216

**What you expected to happen**:
Kubernetes should not remove images if there is no disk pressure on the node

**How to reproduce it (as minimally and precisely as possible)**:
please see here - 
https://github.com/docker/for-win/issues/6216

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
docker-desktop on windows single node
- OS (e.g: `cat /etc/os-release`): MobyLinux VM on Windows 10
- Kernel (e.g. `uname -a`): dont know
- Install tools: docker-desktop installer for windows 10
- Network plugin and version (if this is a network-related bug): NA
- Others:

**Comment by wawa0210** [comment]
Is the node disk pressure normal?

**Comment by vipinponnarath** [comment]
Yes, it is normal.
