### ISSUE TITLE
IKS | Node host name is not equal between kubernetes API and node's os

### ISSUE THREAD

**Issue by yoavAqua** [kubernetes/kubernetes#89948]
I'm trying to identify a shared node between 2 different components.
One component is accessing the node via the Kubernetes API, and the other is running on the node itself and has access to its operating system.

In order to identify the node, I'm combining the node's machine-id with its hostname (since the machine-id and hostname are not unique by themselves).

In most of the environments, this method works fine, but, when running in IKS (IBM Cloud
Kubernetes Service) I get different hostnames for the same node:

The KubeAPI returns a hostname equal to the node's name, while when running the "hostname" command on the node itself, there's a different result.

Note: the machine-id is the same.

/sig api-machinery

**Comment by yoavAqua** [comment]
./sig api-machinery

**Comment by lavalamp** [comment]
cc @deads2k 

> The KubeAPI returns a hostname equal to the node's name, while when running the "hostname" command on the node itself, there's a different result.

The node name of the kubernetes node object is up to the cloud provider, and is chosen when they create the node object. Whether this name is supposed to match the hostname, a network name, or the name of the e.g. VM resource has never been super well defined.

**Comment by lavalamp** [comment]
/sig node
/sig architecture

/remove-sig api-machinery

(we don't own the contents of the API)

**Comment by yoavAqua** [comment]
Hi @lavalamp thanks for your answer, just to be clear:
Getting a node's hostname using the API returns a different **hostname** than the one returned by running "hostname" on the node's os.

**Comment by lavalamp** [comment]
That sounds like a configuration problem. I guess you need to take it up with IKS. If you can see your `kubelet`s, there's some chance you might be able to find the configuration problem in their command line arguments, config files, or environment...

**Comment by deads2k** [comment]
Suggestion from @derekwaynecarr 

/assign @mhbauer

**Comment by yoavAqua** [comment]
@lavalamp Thanks Daniel, can you think about a different method to identify a node in Kubernetes from 2 ways? one from API and one on the node.

**Comment by lavalamp** [comment]
The kubelet must somehow know its kubernetes node object. I'd look at how it's configured in this environment.
