### ISSUE TITLE
kubernetes api-server memory is increasing

### ISSUE THREAD

**Issue by zhaoguangqiang** [kubernetes/kubernetes#89958]
**What happened**:
When i using kubernetes, my api-server memory is increasing to 8G: but i only have 2 nodes and 3 masters

**What you expected to happen**:
I need a api-server with normal memory usage:

**How to reproduce it (as minimally and precisely as possible)**:
It a little difficult, it always grows unconsciously.But i found memory always grow after run helm3 install promethues and grafana or other software:

**Anything else we need to know?**:
kubectl top node
NAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ni-k8s-1       311m         15%    7165Mi          96%       
ni-k8s-2       199m         9%     2035Mi          27%       
ni-k8s-3       310m         15%    5698Mi          76%

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.3
- Cloud provider or hardware configuration: hardware
- OS (e.g: `cat /etc/os-release`):ubuntu18.04
- Kernel (e.g. `uname -a`):Linux ni-k8s-1 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubeadm
- Network plugin and version (if this is a network-related bug):flannel
- Others:

**Comment by liggitt** [comment]
* is the the kube-apiserver process that is growing in memory use, or some other process on the master node?
* is something creating ever-increasing numbers of API objects?
* do you have API server logs showing request rate/type?

**Comment by zhaoguangqiang** [comment]
Thanks your reply!!!

> * is the the kube-apiserver process that is growing in memory use, or some other process on the master node?

 kubectl top pod -n kube-system
kube-apiserver-ni-k8s-1            122m         5484Mi          
kube-apiserver-ni-k8s-2            73m          798Mi           
kube-apiserver-ni-k8s-3            178m         4356Mi 

> kubectl top node
NAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ni-k8s-1       332m         16%    6820Mi          91%       
ni-k8s-2       224m         11%    2265Mi          30%       
ni-k8s-3       308m         15%    5825Mi          78%       

The kube-apiserver process that is growing in memory use.

> * is something creating ever-increasing numbers of API objects?
What's the meaning of API ojbects? Is kube-apiserver threads?
Whatever how much the kube-apiserver memory usage in 3 masters,  i found the kube-apiserver always have ten kube-apiserver threads.

> * do you have API server logs showing request rate/type?
Sorry, i cannot found it in kube-apiserver logs. by the way, the "request rate/type" have some keyword in my log that let me search.

**Comment by aojea** [comment]
> Sorry, i cannot found it in kube-apiserver logs. by the way, the "request rate/type" have some keyword in my log that let me search.

if you are using kubeadm the kube-apiserver should be a pod, you can find it with:

```sh
kubectl get pods -n kube-system | grep apiser
kube-apiserver-kind-control-plane            1/1     Running   0          6d9h
```

and get the logs with:

```sh
kubectl -n kube-system logs kube-apiserver-kind-control-plane | less
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0402 22:05:08.244009       1 server.go:596] external host was not specified, using 172.17.0.4
I0402 22:05:08.244208       1 server.go:150] Version: v1.17.2
I0402 22:05:08.936895       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I0402 22:05:08.936913       1 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I0402 22:05:08.937784       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I0402 22:05:08.937797       1 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
```

**Comment by zhaoguangqiang** [comment]
> ```shell
> kubectl get pods -n kube-system | grep apiser
> ```

I only have these kube-apiserver, cannot find a pod like kube-apiserver-kind-control-plane
My kubeadm version is 1.16.3. Your version is 1.17.2. 
Version 1.16+ may be not have this pod ?

> kubectl get pods -n kube-system | grep apiser
kube-apiserver-ni-k8s-1            1/1     Running     2          21h
kube-apiserver-ni-k8s-2            1/1     Running     3          21h
kube-apiserver-ni-k8s-3            1/1     Running     2          21h

**Comment by lavalamp** [comment]
> But i found memory always grow after run helm3 install promethues and grafana or other software

apiserver's resource footprint is very dependent on what is using it.

**Comment by zhaoguangqiang** [comment]
> > But i found memory always grow after run helm3 install promethues and grafana or other software
> 
> apiserver's resource footprint is very dependent on what is using it.

But how can i find a clear reason immediately and fix up it?
