### ISSUE TITLE
before-first-apply manager prevents resource updates

### ISSUE THREAD

**Issue by dulltz** [kubernetes/kubernetes#89954]
**What happened**:

This problem is occurred when trying to do server-side apply without force option.
I cannot apply new patch to the resource which was created by client-side apply.
It is because `before-first-apply` manager prevents resource updates by other manager's server-side apply.

What is `before-first-apply` field manager?
Of course it can be patched if the force-conflicts option is added to the request, however is this the intended behavior of kube-apiserver?

**What you expected to happen**:

It is enable to do server-side apply without force option to the resource which was created by client-side apply.

**How to reproduce it (as minimally and precisely as possible)**:

1. Prepare pod manifest. 
```console
$ cat pause.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pause
  namespace: sandbox
spec:
  containers:
  - image: k8s.gcr.io/pause:latest
    name: pause
```
2. Apply it by client-side-apply
```console
$ kubectl apply -f pause.yaml
pod/pause created
```
3. Apply the same manifest by server-side apply
```console
$ kubectl apply -f pause.yaml --server-side
pod/pause serverside-applied
```
4. Prepare the tweaked pod manifest.
```console
$ sed s/pause:latest/pause:3.1/g pause.yaml > pause-3-1.yaml
```
5. Apply the tweaked manifest by server-side apply without `--force-conflicts` option.
```console
$ kubectl apply -f pause-3-1.yaml --server-side
error: Apply failed with 1 conflict: conflict with "before-first-apply" using v1: .spec.containers[name="pause"].image

Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).

See http://k8s.io/docs/reference/using-api/api-concepts/#conflicts
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"archive", BuildDate:"2020-03-13T04:17:19Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on-premiss
- OS (e.g: `cat /etc/os-release`):
```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```console
$ uname -a
Linux stage0-boot-0 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: [in-house tool](https://landscape.cncf.io/format=card-mode&grouping=category&organization=cybozu&selected=cybozu-kubernetes-engine)
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lavalamp** [comment]
cc @apelisse @kwiesmueller 

I think we're working on making this smoother for 1.19?

**Comment by apelisse** [comment]
Yes, we're planning on converting resources applied with client-side to server-side without conflicts. @julianvmodesto

**Comment by apelisse** [comment]
Actually, that's a slightly different use-case, but we could probably address it.

**Comment by julianvmodesto** [comment]
Oh we can do something about this now that scalability isn’t an issue? https://github.com/kubernetes/kubernetes/pull/87044#issuecomment-573127883

We’ll want to fix managed fields with this manager (remove or replace this manager) and also turn this field manager off (turn probability to 0).

It seems that we can either replace the manager with a kubectl CSA manager or remove it entirely.

**Comment by apelisse** [comment]
I don't know yet if we want to solve that or if this is Working As Intended.

On one hand, we want users to know that there're about to clobber some fields as they apply for the first time. On the other hand, some of these are not really legitimate conflicts. I suspect the definition of a legitimate conflict is the same definition we've used for updating from client-side apply to server-side apply.

IOW, we should probably ignore errors if:
1. The object has been client-side applied before (there is a last-applied annotation)
2. The fields that conflict were specified in the last-applied annotation
3. These fields haven't changed since the file was client-side applied

That would exactly solve the problem described by OP.

Does it make sense @julianvmodesto ?

**Comment by julianvmodesto** [comment]
Ahhh yes that makes sense, this should just work now since the resource will have the last-applied annotation and avoid conflicts.

**Comment by apelisse** [comment]
@julianvmodesto I think that's solved, right?

**Comment by julianvmodesto** [comment]
Yes this is solved! 

/close
