### ISSUE TITLE
Human readable duration formats exact year inconsistently

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#89960]
**What happened**:
When the duration is **exactly** 2 years or 3 years, human readable duration is returned as `2y0d` or `3y0d`.  But when the duration is exactly 4 years, 5 years, etc, the human readable duration is returned as `4y`, `5y`, etc.

**What you expected to happen**:
The format of an exact year should be consistent.  Remove `0d` when duration is an exact year:
* `2y0d` should be `2y`
* `3y0d` should be `3y`
* Check other years... 4, 5, 6, 7... not sure if they also have the problem.

**How to reproduce it (as minimally and precisely as possible)**:
Because this is time-dependent, it can be difficult to reproduce via the CLI, but you can see the problem illustrated in [this unit test](https://github.com/kubernetes/kubernetes/blob/15bb54c2d2c515ad155b90c2c2ca59eaa1cd3f65/staging/src/k8s.io/apimachinery/pkg/util/duration/duration_test.go#L77) which shows the current behavior:
```
		{d: 2 * 365 * 24 * time.Hour, want: "2y0d"},
		{d: 2*365*24*time.Hour + 23*time.Hour, want: "2y0d"},
		{d: 3 * 365 * 24 * time.Hour, want: "3y0d"},
		{d: 8*365*24*time.Hour - time.Millisecond, want: "7y364d"},
		{d: 8 * 365 * 24 * time.Hour, want: "8y"},
		{d: 8*365*24*time.Hour + 364*24*time.Hour, want: "8y"},
		{d: 9 * 365 * 24 * time.Hour, want: "9y"},
```

The `2y0d` and `3y0d` test cases should be changed to want `2y` and `3y`, and the code should be changed to make that pass.

**Anything else we need to know?**:
Note, this is not a problem when the duration is exactly 1 year because the human readable duration is still shown in days.  So nothing needs to change to handle the case of exactly 1 year.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.18
- Cloud provider or hardware configuration:  n/a
- OS (e.g: `cat /etc/os-release`):  n/a
- Kernel (e.g. `uname -a`):  n/a
- Install tools:  n/a
- Network plugin and version (if this is a network-related bug):  n/a
- Others:  n/a

**Comment by bitscuit** [comment]
Could I pick this up as my first issue?

**Comment by brianpursley** [comment]
Absolutely.  Just use `/assign <your-github-username>` to assign it to yourself.

**Comment by brianpursley** [comment]
Also I just updated the issue description.  Check the other exact years 4, 5, 6, 7 because they might also have the problem, I can't remember.

I know 8 and beyond don't have the problem because it just stops showing days after 8 years.

**Comment by lavalamp** [comment]
@deads2k might recall a related PR?

**Comment by lavalamp** [comment]
(also, I have to leave the pedantic note: a year isn't always 365 days, so it's surprising to me to see the abbreviation exists at all)

**Comment by deads2k** [comment]
I can't find it.  Maybe I was remembering https://github.com/kubernetes/kubernetes/pull/88270

**Comment by brianpursley** [comment]
> I can't find it. Maybe I was remembering #88270

Yeah it was probably that one.

At first I had the tests and the fix. But it sat for a while.  I changed it to just the tests of existing behavior so it could be approved more easily.

Then I made this issue for the fix but decided it would probably be a good first time issue for someone instead of me doing it.

**Comment by bitscuit** [comment]
> 
> 
> (also, I have to leave the pedantic note: a year isn't always 365 days, so it's surprising to me to see the abbreviation exists at all)

so should leap years be considered by the code?

**Comment by lavalamp** [comment]
There's no way to know how long a year is without knowing the date, so it's
not a good unit--in the abstract, there's no way to know if it's a leap
year or not. The go language deliberately omits it IIRC.

**Comment by bitscuit** [comment]
What's the intention of HumanDuration? From what I've seen, it is just an approximation of a timestamp solely for humans to understand, so assuming 365 days per year sounds about right to me. This issue is about consistency though, so it could be solved the other way. Instead of abbreviating when it's an exact year (2y, 3y, etc.), exact years could just all have 0d (2y0d, 3y0d, etc.)

**Comment by brianpursley** [comment]
I think it is just used for a ballpark duration.  It loses accuracy as the duration increases anyway because it changes the units.  I guess my intention for opening the issue was to make it consistent with itself.  For example it doesn't say 2d0h or 2h0m, so it should not say 2y0d.

**Comment by lavalamp** [comment]
(FTR I agree that Xy0d looks worse than Xy.)

**Comment by vikkyomkar** [comment]
Hi @bitscuit I have made the required changes. Shall I raise the PR if you haven't started working in it ?

**Comment by brianpursley** [comment]
@vikkyomkar @bitscuit already assigned it, so I think it would be good to let him submit the PR, unless he unassigns or does not submit a PR in a reasonable amount of time.

**Comment by bitscuit** [comment]
Thanks @brianpursley, I was planning on submitting the PR over the weekend

**Comment by iwita** [comment]
Hello, I am a first timer in open source contribution community.
I think I made the required changes for that issue.
However, I don't know how assignment rules work. Should I submit a pull request or wait for a feedback?
