### ISSUE TITLE
Static control plane pods do not have priority set

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#89966]
**What happened**:
https://github.com/kubernetes/kubernetes/pull/80491 changed all static pods to be considered critical. If two pods are both critical, the relative numeric priority determines which one preempts the other. However, the static control plane pods in the `cluster` dir do not have numeric priorities assigned to them.

**What you expected to happen**:
Control plane pods are not preemptible by other static pods.

/sig cluster-lifecycle
/sig node
/assign

**Comment by liggitt** [comment]
It also looks as though they try to set priority class, but have a typo in the field name ("priorityClass" instead of "priorityClassName")

**Comment by neolit123** [comment]
for kubeadm's static control-plane pods, we use "system-cluster-critical". might have been more accurate to use the higher priority of "system-node-critical".

**Comment by liggitt** [comment]
IIUC, system-cluster-critical means "it's ok for this pod to be evicted from *this* node by a system-node-critical pod, but it should have priority over all user pods"

for control-plane static pods, I would not expect it would be ok for the pods to be evicted from their nodes

**Comment by neolit123** [comment]
i can send a PR to update this for 1.19, but not backport, mostly because we haven't seen user complains (yet).
