### ISSUE TITLE
Upgrade to klogv2

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#89961]
As part of Structured Logging effort we will be upgrading klog to version 2. This issue will propose plan for upgrading all dependencies and be used to maintain progress.

Part of https://github.com/kubernetes/enhancements/issues/1602

Plan:
* [x] Cut klog release 2.0.0 (@dims)
* [x] Send PRs to k/k dependencies upgrading klog (taken from https://github.com/kubernetes/kubernetes/pull/89717#issuecomment-608091112)
  * [x] k8s.io/gengo (@dims, https://github.com/kubernetes/gengo/pull/173)
  * [x] k8s.io/utils (@dims, https://github.com/kubernetes/utils/pull/152)
  * [x] k8s.io/kube-openapi (@tanjunchen, https://github.com/kubernetes/kube-openapi/pull/192)
  * [x] github.com/google/cadvisor (@dims, https://github.com/google/cadvisor/pull/2478)
  * [x] github.com/GoogleCloudPlatform/k8s-cloud-provider (@tanjunchen. https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/37, https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/38)
  * [x] sigs.k8s.io/apiserver-network-proxy (@tanjunchen, https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/100)
  * [x] k8s.io/repo-infra (@dims, https://github.com/kubernetes/repo-infra/pull/185)
* [x] [Optional] Run scalability tests on draft PR to check for performance regressions
* [ ] Get approval from root owners & schedule upgrade
* [ ] Send announcement kubernetes-dev@
* [ ] Execute the upgrade

/cc @dims @liggitt @smarterclayton @wojtek-t
/milestone v1.19

**Comment by dims** [comment]
@serathius please add me to utils repo as well.

**Comment by dims** [comment]
@serathius please mark klog release as DONE ( https://github.com/kubernetes/klog/releases/tag/v2.0.0 )

**Comment by serathius** [comment]
@mm4tt We are ready to run scalability tests on https://github.com/kubernetes/kubernetes/pull/89955

**Comment by dims** [comment]
@serathius please mark k8s.io/utils and k8s.io/klog as done.

**Comment by dims** [comment]
@serathius filed https://github.com/kubernetes/gengo/pull/173 for gengo

**Comment by dims** [comment]
@serathius file https://github.com/kubernetes/repo-infra/pull/185 for repo-infra

**Comment by dims** [comment]
@tanjunchen can you please file the PRs that you picked up and throw us a link?

**Comment by tanjunchen** [comment]
@dims i have open these prs. As seen above.

**Comment by serathius** [comment]
Linked all PRs to issue description. 

I was planning to find some time and pick one repo on weekend, but you beat me up to it. Thanks for all the help!

**Comment by dims** [comment]
@serathius https://github.com/kubernetes/gengo/pull/173 has merged.

**Comment by tanjunchen** [comment]
https://github.com/kubernetes/kube-openapi/pull/192 has been merged .  @serathius

**Comment by serathius** [comment]
Talked with @mm4tt, he proposed to run 5k release blocking performance tests and do A/B performance analysis. 
I will try to find someone from SIG-scalability to help but it might take time due Holidays.

**Comment by mm4tt** [comment]
SIG Scalability will run the tests by the end of the next week. Will have a more precise estimate today.

**Comment by mm4tt** [comment]
@tosi3k from SIG Scalability will run the tests

**Comment by tosi3k** [comment]
Follow-up: I will run the tests tomorrow.

**Comment by dims** [comment]
@tosi3k @mm4tt @serathius Let's please use https://github.com/kubernetes/kubernetes/pull/90183 for the tests.

**Comment by dims** [comment]
@tosi3k @mm4tt @serathius did the scalability CI jobs get started? i have updated https://github.com/kubernetes/kubernetes/pull/90183 and i haven't heard from y'all

**Comment by tosi3k** [comment]
@dims sorry for the late update. The 5k CI job based on commit 2f0e334 of #90183 is currently running and will take a few more hours. I will give you more update on Monday.

**Comment by tosi3k** [comment]
@dims the test succeeded but I'm concerned about the actual commit I run the test on top of. It was the freshest one when I left work on Friday but I saw one with description `
switch over k/k to use klog v2` being pushed afterwards, hence I believe the test I started on Friday didn't really make sense :(. Shall I rerun the tests on top of the most recent change (which is cd1edd0 I believe but correct me if I'm wrong)?

**Comment by serathius** [comment]
@tosi3k Thanks for running it. 
Could you provide link to dashboard with results?

I think intention was to do A/B tests. So run tests twice, one before the update and one after update. @mm4tt can you confirm?

**Comment by mm4tt** [comment]
@serathius, you're right, but we don't need to run the test twice manually. We can use a daily 5k CI/CD run as a baseline.
That being said, before we spin up the dashboards, I'd like to get answer to @tosi3k's question, i.e. whether the manual run he did actually had klogv2 enabled.

**Comment by dims** [comment]
@serathius my bad, i had not pushed everything needed before i added that note :(

**Comment by mm4tt** [comment]
No worries, @tosi3k can confirm, but I think he reserved a slot for re-running the tests tomorrow. 

@dims, could you please double check and give us an explicit green light confirming that the PR is ready to be tested?

**Comment by dims** [comment]
@mm4tt yes, what is in https://github.com/kubernetes/kubernetes/pull/90183 is good. specifically cd1edd0c0e06af7c4dd02838d55ccc84586c89fe is the last commit

For next time best way to cross check is ensuring that "k8s.io/klog" is removed from root go.mod/sum and "k8s.io/klog/v2" is added there instead.

```
-	k8s.io/klog v1.0.0
+	k8s.io/klog/v2 v2.0.0
```

**Comment by tosi3k** [comment]
Okay, I will run the test using cd1edd0 commit tomorrow and compare the results with our daily 5k CI/CD test run the day after tomorrow then.

**Comment by tosi3k** [comment]
I ran a test job with the experiment and the test passed. Looking at the dashboards I noticed a few changes:
* Clusterloader
LIST calls for pods in the namespace scope take more time on average than before change (1.63s vs. 3.59s),
* etcd
number of bytes sent to gRPC clients rose quite considerably (3.16 MB vs. 13.3 MB on average)
apart from that everything looks pretty much the same
* kube-apiserver
slightly higher variance of memory allocation for kube-apiserver (but the memory usage stays the same on average),

Overall, the results look good (at least from my novice perspective).

Dashboard with metrics before the change: [link](http://35.226.146.156:3000/d/uzJNy03Wk/master-dashboard?orgId=1) (source: `grafana-prom`).
Dashboard with metrics after the change: [link](http://35.226.146.156:3000/d/uzJNy03Wk/master-dashboard?orgId=1&var-source=klogv2-experiment&var-etcd_type=All&var-etcd_operation=All&var-verb=All&var-resource=All) (source: `klogv2-experiment`).

**Comment by serathius** [comment]
@mm4tt does this look ok for you?

**Comment by mm4tt** [comment]
Thanks, @tosi3k!

The latency of the pod lists seems suspicious, but my intuition says it's a red herring, most likely coming from the different setup of the test runs. The CI/CD test uses configuration than the manual test. For manual test, we used our scalability prow instance, it's likely that the cl2 was run in different region than the cluster, which could affect the pod list (IIRC, cl2 is the main issuer of these calls).

So yes, to summarize it looks ok. We don't see any obvious scalability blockers for klogv2.

**Comment by serathius** [comment]
Thanks @dims for all great work!
