### ISSUE TITLE
Update of a non-existent object returns 409 instead of 404

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#89985]
**What happened**:
```
mspreitz@mjs-dev-1:~$ curl -X PUT -H "Content-type: application/json" -d @z http://localhost:8080/api/v1/namespaces/default/pods/xyzzy/status
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Operation cannot be fulfilled on pods \"xyzzy\": StorageError: invalid object, Code: 4, Key: /registry/pods/default/xyzzy, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 1234, UID in object meta: ",
  "reason": "Conflict",
  "details": {
    "name": "xyzzy",
    "kind": "pods"
  },
  "code": 409
}

mspreitz@mjs-dev-1:~$ curl -X PUT -H "Content-type: application/json" -d @z http://localhost:800/api/v1/namespaces/default/pods/xyzzy
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Operation cannot be fulfilled on pods \"xyzzy\": StorageError: invalid object, Code: 4, Key: /registry/pods/default/xyzzy, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 1234, UID in object meta: ",
  "reason": "Conflict",
  "details": {
    "name": "xyzzy",
    "kind": "pods"
  },
  "code": 409
}
```
The contents of `z` are:
```
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "xyzzy",
        "uid": "1234"
    }
}
```

I get similar results with configmaps.

**What you expected to happen**:
I expected to get a 404 Not Found

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): current `master` branch, commit 0393b5994a0e02f0a0f3fb50311b3aa191f926ce

- Cloud provider or hardware configuration: Intel Xen VM with 16 virtual CPUs and 64 GB of memory

- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux mjs-dev-1 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hack/local-up-cluster.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@matte21 
@liggitt

**Comment by liggitt** [comment]
When the incoming object has a precondition (uid or resourceVersion), a conflict error is an allowed response. I think the error message should be made clearer, but we should think carefully before changing the return status code.

**Comment by MikeSpreitzer** [comment]
Fair enough.

**Comment by liggitt** [comment]
(Discussion/context at https://kubernetes.slack.com/archives/C0EG7JC6T/p1586381612318200)

**Comment by MikeSpreitzer** [comment]
On further reflection: the primary conflict is between the expectation that the object exists and the fact that it does not.  I think "Not found" is the best response.

I stumbled upon this not because my controller couldn't handle the Conflict response, but because I went trolling through telemetry looking for system misbehavior.  It is honestly surprising to a developer of clients (controllers) to get a Conflict response to an Update[Status] request for an object that no longer exists.

**Comment by liggitt** [comment]
In the abstract, I would have expected a NotFound as well. The question is whether changing from a Conflict error to a NotFound error could be a breaking change.

**Comment by matte21** [comment]
I agree that the most natural response is NotFound. Besides: when attempting to update a resource that has been deleted the sensible behavior is to stop after the 1st request failure, but a Conflict error might be handled by a client with a retry, which would be useless.

**Comment by liggitt** [comment]
> a Conflict error might be handled by a client with a retry, which would be useless.

correct handling of a conflict would get the current item to refresh the uid or resourceVersion precondition, at which point the NotFound error would be encountered, right?

**Comment by matte21** [comment]
I know very little about the code dealing with preconditions, so I wouldn't know :( .

But on further reflection, the most sensible behavior for a controller's worker that receives a Conflict error is to halt processing w/o re-enqueuing the object's namespace name, knowing that a create/update notification that carries the most recent version of the object will be received by the informer and trigger re-processing of the object. The key point is that the client practically handles the error like it should when seeing a NotFound.

I still think that human operators can be confused by a precondition Conflict message.

> The question is whether changing from a Conflict error to a NotFound error could be a breaking change.

But a client that handles a Conflict error should also be prepared to handle a NotFound error, right?

**Comment by MikeSpreitzer** [comment]
@liggitt : how shall we evaluate whether switching from Conflict to NotFound in this situation is a breaking change?

I can think of three approaches.  One is testing, another is thinking about coding patterns, and a third is surveying the code.  The normal PR processing does some testing, including a sample of the E2E tests.  A submitter could do all the E2E tests, right?  How long would that take?

The discussion above mentions the two most plausible responses to errors: (1) requeue for retry, and (2) simply workqueue.Done and .Finish on the grounds that another notification arrives after processing started and so the object reference gets requeued and reprocessed.  Both of these handle both Conflict and NotFound correctly, right?

Code survey looks like a lot of work and is necessarily incomplete (client code is scattered throughout the world).  Of course, testing is also necessarily incomplete, and reasoning is of limited confidence.

**Comment by liggitt** [comment]
I would lean toward improving the way the existing conflict error is presented to make it clearer what is going on, and leave it at that. Changing the fundamental error that is returned in this case has non-zero risk, and in my opinion little benefit over simply clarifying the message.

**Comment by lavalamp** [comment]
I think NotFound would have been the correct response, but changing it now carries more risk than benefit. :( In particular none of the three mechanisms mentioned ("...testing, another is thinking about coding patterns, and a third is surveying the code...") are sufficient to mitigate the risk, since the affected clients could be running anywhere and may not even be open source for us to examine.

I recommend documentation changes, or possibly changing the message / reason.

**Comment by matte21** [comment]
Oddly, I can reproduce only with a UID precondition.
If I specify a resourceVersion precondition I get a 404 status code.
