### ISSUE TITLE
kube-controller-manager: "Unexpected EOF during watch stream event decoding"

### ISSUE THREAD

**Issue by wzxmt** [kubernetes/kubernetes#89994]
**What happened**:
I encountered some problems in the binary deployment of k8s 1.18, the controller-manager has some error messages "Unexpected EOF during watch stream event decoding: unexpected EOF"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Log level: v2
Apr 09 13:49:22 m1 kube-controller-manager[2156]: I0409 13:49:22.700867    2156 streamwatcher.go:114] Unexpected EOF 
**Anything else we need to know?**:
Log level: v4
lock is held by m1_28d34456-a33b-42b9-bb6b-69c2a39ceb83 and has not yet expired
failed to acquire lease kube-system/kube-controller-manager
**Environment**:
centos 7.5
- Kubernetes version (use `kubectl version`):
1.18.1
- Cloud provider or hardware configuration:
VMware
- OS (e.g: `cat /etc/os-release`):
4.4.218-1.el7.elrepo.x86_64
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wzxmt** [comment]
Sorry, I do n’t quite understand, what should I do?

**Comment by neolit123** [comment]
/retitle kube-controller-manager: "Unexpected EOF during watch stream event decoding"
/sig api-machinery

hi, i think the folks helping issue triage will request more details logs from you.

**Comment by liggitt** [comment]
Agreed, more logs are needed. The logs a few seconds before and after the EOF messages would be helpful. Are there any other error messages logged? Is the API server restarting around the time theee messages are seen?
