### ISSUE TITLE
Unexpected startupProbe behavior. 

### ISSUE THREAD

**Issue by heckad** [kubernetes/kubernetes#89995]
If I have `startupProbe` probe and `readinessProbe` then all good. Previous version of the pod is terminated after startup probe success, but if  `readinessProbe` wasn't specified the pod becomes ready immediately. It would be nice to add new state (for example starting) which would have pods until a `startupProbe` is successful. Also, it would mean that container not ready for connection.

Thank you for attention!

**Comment by heckad** [comment]
@neolit123?

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle
/sig apps

try asking in #kubernetes-users on k8s slack.

**Comment by heckad** [comment]
How to do this if I don't have slack workspace or company or somebody else?

**Comment by heckad** [comment]
@neolit123, they are silent in the chat. Who is involved in the development of startup probe?

**Comment by neolit123** [comment]
i think this topic better fits SIG Node.

try asking in their channel on slack `#sig-node`, but beg patient ;)
/sig node
/remove-sig apps

**Comment by thockin** [comment]
I think this is a feature request, not support, so I changed labels.  On its face it SEEMS reasonable, but I am not close enough to the details to say.  This is definitely sig-node.

**Comment by riking** [comment]
Adding a new pod lifecycle state has been determined to be intractable in the past.

Do you mean keeping the pod in !Ready until the first success from `startupProbe`?

**Comment by heckad** [comment]
> Is the proposed change keeping the pod in !Ready until the first success from `startupProbe`?

Yes, I want that pod considered not ready until `startupProbe` will not be successful. If readiness probe doesn't present then a pod can become ready.

**Comment by heckad** [comment]
@riking?

**Comment by heckad** [comment]
@riking how long wait?

**Comment by thockin** [comment]
Looking at this issue, I can confirm it, at least superficially - a pod with a perma-failing `startupProbe` is "ready" if there is no readinessGate defined and "not ready" if it is defined.

The question I have is whether we think that is "correct" or not?  Initially I thought it was correct, but the more I think about it the less convinced I am.  

If I have defined a startupProbe and it is not passing, my app should not be ready.

Does anyone disagree?

**Comment by heckad** [comment]
Also, the app should not be ready in `terminating` status.

**Comment by thockin** [comment]
Whether a pod is ready while terminating is an entirely different question, IMO.  Apps that server network traffic probably need to "drain" and to do that they need to stay "ready" for a while as upstream LBs de-program.

Let's not conflate issues, please.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/92196

The fix seems simple - lets see what CI says.

**Comment by matthyx** [comment]
> @neolit123, they are silent in the chat. Who is involved in the development of startup probe?

Sorry, I don't spend much time on slack... you could have checked the release notes in 1.18 ;-)
Tim's fix seems good, thanks!

**Comment by matthyx** [comment]
/reopen
Until we merge all related PRs...

**Comment by matthyx** [comment]
All merged.
/close
