### ISSUE TITLE
How to extend the auto-exit time of POD entry?

### ISSUE THREAD

**Issue by ygqygq2** [kubernetes/kubernetes#89997]
env
k8s: v1.14.3
kubectl: v1.14.3

After 3 seconds, pod auto exit when use kubectl enter pod.

```
time kubectl exec -it curl-79854fc947-2cwv8 /bin/bash
bash-5.0# 
real    0m3.166s
user    0m0.063s
sys     0m0.047s
```

**Comment by neolit123** [comment]
hi, please try on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
