### ISSUE TITLE
Server-Dry-Run with Force flag hangs forever if applied to an Immutable object

### ISSUE THREAD

**Issue by nicksc423** [kubernetes/kubernetes#90017]
/kind bug

**What happened**:  We use the Server-Dry-Run to lint our kubernetes yaml files (make sure they pass our OPA/Gatekeeper restrictions etc).  When trying this with a Job CRD we recieved an immutable object error, if you add the --force flag this will hang forever (or until timeout).

**What you expected to happen**:
Server-Dry-Run with the Force flag should know that it will delete any existing CRDs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create/Apply a Job (https://kubernetes.io/examples/controllers/job.yaml) 
2. Make some change to the Job (Change to print bpi(1999)
3. Apply the job with --server-dry-run and --force flags

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
AKS

**Comment by nicksc423** [comment]
Currently just using sed to change the name of the job to add a uuid as a work around so not the largest problem in the world

**Comment by brianpursley** [comment]
@julianvmodesto Sorry I didn't see you /assigned.  I just did a small PR to add a validation check.  I just closed it, but feel free to use whatever you want from that, or not.

**Comment by julianvmodesto** [comment]
Oh wait please go ahead with your change! I haven’t started working on this

**Comment by brianpursley** [comment]
Ok, I reopened the PR.  Feel free to review and comment.

**Comment by julianvmodesto** [comment]
cc @apelisse 

/wg api-expression
/sig cli

**Comment by julianvmodesto** [comment]
Fixed by @brianpursley!

/close
