### ISSUE TITLE
Do not record managedFields for specific requests/object/types

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#90012]
As an example (but there are probably other scenarios we need to investigate), events are recording the managedFields even though it's mostly irrelevant. As a consequence, events are much bigger and since they can be quite frequent, this can cause some problems.

A control to decide what is tracked or not can be considered at different levels:
- Per request: one can disable tracking fields for a specific request,
- Per object: we could disable tracking for an object,
- Per gvk: Objects of a specific types won't ever be tracked

We could possibly:
- track the fields and everything,
- only track the manager/date,
- not track anything (pre-ssa state)

cc @lavalamp @kwiesmueller @smarterclayton

**Comment by lavalamp** [comment]
I don't agree we need to disable recording managed fields. I think marking something root-level in the object as atomic is sufficient.

**Comment by apelisse** [comment]
> I don't agree we need to disable recording managed fields. I think marking something root-level in the object as atomic is sufficient.

I'm fine settling on this for now.
