### ISSUE TITLE
Stress testing the rc manager

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#9002]
More of a question here, is there any stress testing of the rc manager (I am mostly interested in replication controller bulk deleting) currently happening in the Kubernetes test suites?

cc: @smarterclayton @mfojtik

**Comment by kargakis** [comment]
The issue we have observed is that `delete` *randomly* times out when trying to remove 6 replication controllers (probably related to the [number](https://github.com/GoogleCloudPlatform/kubernetes/blob/17f6f86be688a415b50b0ae627f1695032a06969/cmd/kubernetes/kubernetes.go#L138) of workers?).

**Comment by smarterclayton** [comment]
@tstclair

**Comment by bprashanth** [comment]
We have https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/load.go (which I just ran). We also run e2e tests on a cluster that has 5 rcs and tear it down ~hourly, and a scale test that stops very large rcs. It would be nice to have a shorter test that targest just stopping multiple rcs.

Can you give me the exact rc manifests you're using, and more detailed repro steps if possible? (how you're deleting the rcs, number of replicas, what else is running on your cluster, what state the pods were in etc). The number of workers should only affect the speed of deletion.

**Comment by kargakis** [comment]
@bprashanth the test that hangs is [this](https://github.com/openshift/origin/blob/master/hack/test-cmd.sh#L576-L581) ([JSON/YAML files](https://github.com/openshift/origin/tree/master/test/fixtures/app-scenarios) - nevermind `osc status`). 

I cannot reproduce the timeout locally but I can see it hanging for some time while waiting to update the replica status of a random rc: http://pastebin.com/cuHgVUQf

*osc delete [all](https://github.com/openshift/origin/blob/2e53c1fe514ebecdeb7b9eda526c747c9dcbb54e/pkg/api/latest/latest.go#L94) --all* tears down deploymentConfigs (when a dc gets deleted, our reaper will first delete the latest replication controller associated with it) and then rcs. At start I thought maybe that was a possible source of the problem but then I reverted the sequence of the `all` alias[1] so that `delete all` would first delete rcs and then dcs but the problem has persisted.

Re benchmarking, yes, I am interested in doing some on this.

[1]
` "deploymentConfigs", "replicationControllers",` 
to  
`"replicationControllers", "deploymentConfigs",`

**Comment by bprashanth** [comment]
> I cannot reproduce the timeout locally but I can see it hanging for some time while waiting to update the replica status of a random rc: http://pastebin.com/cuHgVUQf

Ok, lets get your kubectl pr in, that should help clear out some of the confusion. After that we can add some rc stop benchmarks.
