### ISSUE TITLE
gcp cloud-controller-manager cannot initialize a new Node

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#90056]
**What happened**:
https://github.com/kubernetes/kubernetes/pull/85735 introduces a regression that `getNodeAddressesByProviderIDOrName` func is invoked on a Node obj without `.spec.providerID`, hence it can fail fetching the node addresses when the `.spec.providerID` is not set. 

**What you expected to happen**:
I would expect cloud-controller-manager to be able to initialize new Node.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start the gcp legacy-cloud-controller v1.18.1 (`--cloud-provider="gce"`)

2. Ensure that the node-controller cannot initialize a new Node. Logs of the cloud-controller-manager repeated multiple times:
```
I0410 15:48:51.287480       1 node_controller.go:325] Initializing node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 with cloud provider
E0410 15:48:51.295679       1 gce_instances.go:575] Failed to fetch instanceID via Metadata: metadata: GCE metadata "instance/hostname" not defined
E0410 15:48:51.541680       1 node_controller.go:370] failed to initialize node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 at cloudprovider: error fetching node by provider ID: error splitting providerID, and error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
I0410 15:48:51.541710       1 node_controller.go:325] Initializing node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 with cloud provider
E0410 15:48:51.547318       1 gce_instances.go:575] Failed to fetch instanceID via Metadata: metadata: GCE metadata "instance/hostname" not defined
E0410 15:48:51.762648       1 node_controller.go:370] failed to initialize node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 at cloudprovider: error fetching node by provider ID: error splitting providerID, and error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
```

Ensure that the Node is with the `node.cloudprovider.kubernetes.io/uninitialized:NoSchedule` taint. Ensure that the `.spec.providerID` of the Node is not set.

The cloud-controller-manager is not running on the host machine and that's why it cannot call the gce matadata. But it was never a hard requirement for cloud-controller-manager to run on the host machine.

**Anything else we need to know?**:
The legacy cloud-controller-manager v1.17.x is working perfectly fine.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.18.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by andrewsykim** [comment]
@ialidzhikov @cheftako can we open a new issue re: https://github.com/kubernetes/kubernetes/pull/90057#discussion_r408929994?
