### ISSUE TITLE
--all-namespaces should parse anywhere -n parses

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#90055]
Currently, -n can go adjacent to kubectl, but --all-namespaces can only go at the end of the subcommand

**Comment by tlereste** [comment]
Hi @mcandre , I don't reproduce this issue.

I create a pod : 
`kubectl run nginx --image=nginx --restart=Never`

I can get it with adjacent `-n` : 
`kubectl get po -n my-namepsace -l run=nginx`

And I can also get it with adjacent `--all-namespaces` : 
`kubectl  get po --all-namespaces -l run=nginx`

Do you have steps to reproduce this issue ?

**Comment by tylerauerbeck** [comment]
@tlereste I think the problem that's being described here is:

`kubectl -n my-namespace get pods -l run=nginx` = works as expected

however

`kubectl --all-namespaces get pods -l run=nginx` breaks with:

```
Error: unknown command "pods" for "kubectl"

Did you mean this?
	logs

Run 'kubectl --help' for usage.
```

**Comment by liggitt** [comment]
`-n` / `--namespace` is a "global flag" (any kubectl command can take this option). Global flags appear in `kubectl options` help.

`--all-namespaces` is not a global flag (only specific commands can take this option). Only global flags can appear before the command name (in this case, `kubectl get`)

**Comment by liggitt** [comment]
This seems more like a feature request for https://github.com/spf13/cobra (the CLI library kubectl uses) than a bug
