### ISSUE TITLE
Clarify scope of --etcd-servers-overrides option

### ISSUE THREAD

**Issue by mdrocco** [kubernetes/kubernetes#90053]
**What would you like to be added**:
Comment on the scope of --etcd-servers-overrides option in the generated documentation

**Why is this needed**:
The documentation does not say if the --etcd-servers-overrides option for kube-apiserver does support CRDs.

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options

**Comment by hickeng** [comment]
The doc could be clarified, but the following suggest the answer is no support for CRs unless added recently:

https://github.com/kubernetes/kubernetes/pull/84467

https://github.com/kubernetes/kubernetes/issues/81508

**Comment by droccom** [comment]
Yes, indeed I think it should be at least clarified in the docs.
