### ISSUE TITLE
Timeout expired waiting for volumes to attach or mount for pod

### ISSUE THREAD

**Issue by sowhatim** [kubernetes/kubernetes#90079]
/sig storage

**What happened**:
I had es-data-1 pod as part of statefulset es-data. This pod was assigned to a nodegroup which I decided to scale down from 2 to 1 and then later scaled up back to 2. I did this as part of learning and testing the node autoscaling scenario. After this it is stuck in Init:0/1 state. When I describe the the pod, it shows the following error under events - 

 ` Warning  FailedMount             54s (x7 over 14m)  kubelet, ip-172-24-2-128.ap-southeast-1.compute.internal  Unable to mount volumes for pod "es-data-1_elasticsearch(c4eaaa80-7beb-11ea-99e2-027104ad84aa)": timeout expired waiting for volumes to attach or mount for pod "elasticsearch"/"es-data-1". list of unmounted volumes=[storage]. list of unattached volumes=[storage default-token-87r66]`

PVC and PV everything looks fine.

PVC - 
```
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
storage-es-data-0   Bound    pvc-aa0bfc1a-7b3a-11ea-99e2-027104ad84aa   10Gi       RWO            gp2            21h
storage-es-data-1   Bound    pvc-b26762de-7b3a-11ea-99e2-027104ad84aa   10Gi       RWO            gp2            21h
storage-es-data-2   Bound    pvc-c292e70f-7b3a-11ea-99e2-027104ad84aa   10Gi       RWO            gp2            21h
```

PV - 
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                             STORAGECLASS   REASON   AGE
pvc-aa0bfc1a-7b3a-11ea-99e2-027104ad84aa   10Gi       RWO            Delete           Bound    elasticsearch/storage-es-data-0   gp2                     21h
pvc-b26762de-7b3a-11ea-99e2-027104ad84aa   10Gi       RWO            Delete           Bound    elasticsearch/storage-es-data-1   gp2                     21h
pvc-c292e70f-7b3a-11ea-99e2-027104ad84aa   10Gi       RWO            Delete           Bound    elasticsearch/storage-es-data-2   gp2                     21h
```

But if you note that the pod under question - es-data-1 actually had claim on a different pvc than the one scheduler is trying to mount for it. In the pod description, it shows 
_c4eaaa80-7beb-11ea-99e2-027104ad84aa_
while as per pvc it is _b26762de-7b3a-11ea-99e2-027104ad84aa_. 

I checked the events for the pod and found this - 

```
LAST SEEN   TYPE      REASON                   OBJECT          MESSAGE

53m         Normal    Scheduled                pod/es-data-1   Successfully assigned elasticsearch/es-data-1 to ip-172-24-2-174.ap-southeast-1.compute.internal
53m         Normal    SuccessfulAttachVolume   pod/es-data-1   AttachVolume.Attach succeeded for volume "pvc-b26762de-7b3a-11ea-99e2-027104ad84aa"
53m         Normal    Pulling                  pod/es-data-1   Pulling image "busybox:1.27.2"
53m         Normal    Pulled                   pod/es-data-1   Successfully pulled image "busybox:1.27.2"
53m         Normal    Created                  pod/es-data-1   Created container init-sysctl
53m         Normal    Started                  pod/es-data-1   Started container init-sysctl
53m         Normal    Pulling                  pod/es-data-1   Pulling image "quay.io/pires/docker-elasticsearch-kubernetes:6.2.4"
53m         Normal    Pulled                   pod/es-data-1   Successfully pulled image "quay.io/pires/docker-elasticsearch-kubernetes:6.2.4"
53m         Normal    Created                  pod/es-data-1   Created container es-data
53m         Normal    Started                  pod/es-data-1   Started container es-data
39m         Warning   FailedAttachVolume       pod/es-data-1   AttachVolume.Attach failed for volume "pvc-b26762de-7b3a-11ea-99e2-027104ad84aa" : error finding instance ip-172-24-2-174.ap-southeast-1.compute.internal: "instance not found"
38m         Normal    Scheduled                pod/es-data-1   Successfully assigned elasticsearch/es-data-1 to ip-172-24-2-128.ap-southeast-1.compute.internal
38m         Normal    SuccessfulAttachVolume   pod/es-data-1   AttachVolume.Attach succeeded for volume "pvc-b26762de-7b3a-11ea-99e2-027104ad84aa"
39s         Warning   FailedMount              pod/es-data-1   Unable to mount volumes for pod "es-data-1_elasticsearch(c4eaaa80-7beb-11ea-99e2-027104ad84aa)": timeout expired waiting for volumes to attach or mount for pod "elasticsearch"/"es-data-1". list of unmounted volumes=[storage]. list of unattached volumes=[storage default-token-87r66]
```

**What you expected to happen**:
I expected pod to go into state where it can't find the capacity to be scheduled and later when I scaled up the nodegroup , it should have seamlessly got scheduled to the new node.
**How to reproduce it (as minimally and precisely as possible)**:
Tough to say if this is reproducible but I will try to recreate the whole scenario and update if any luck on it. 
**Anything else we need to know?**:
These are all the pods running in that namespace right now -

```
NAME                         READY   STATUS     RESTARTS   AGE
es-client-d6657c44b-b9bts    1/1     Running    0          115m
es-client-d6657c44b-x58gr    1/1     Running    0          115m
es-data-0                    1/1     Running    0          113m
es-data-1                    0/1     Init:0/1   0          46m
es-master-859bdf8987-bc8pt   1/1     Running    0          115m
es-master-859bdf8987-ckb7z   1/1     Running    0          115m
es-master-859bdf8987-kc9zt   1/1     Running    0          115m
```

And I haven't installed any cluster autoscaler. 
Using AWS EKSCTL managed cluster. 
Though it's not related but while I was scaling down and up this nodegroup, I was also scaling the other nodegroup back and forth as well. 

This nodegroup is in ap-southeast-1b region. 
All the pvc have claim on volumes under the same ap-southeast-1b region. (earlier had three es-data pods but had them scaled back to 1 and then to 2)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.4
- Cloud provider or hardware configuration: nodegroup is t3.medium ec2. AWS. ap-southeast-1b.
- OS (e.g: `cat /etc/os-release`): Host OS is Amazon Linux. 
- Kernel (e.g. `uname -a`): Linux ip-172-24-2-128.ap-southeast-1.compute.internal 4.14.171-136.231.amzn2.x86_64 #1 SMP Thu Feb 27 20:22:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: metrics server and dashboard additionally installed
- Network plugin and version (if this is a network-related bug): not sure
- Others:

**Comment by balusarakesh** [comment]
I'm also seeing the same issue, but in my case after 30-40 minutes the node was able to attach, not really sure what the issue was and how it got resolved itself. This started happening when we switched from kops to EKS.

**Comment by OpsPita** [comment]
@sowhatim i feel your pain but in GCP , 
I got this problem also with Google filestore And GKE cluster

I have 2 Clusters , 1 prod - 1 dev

Prod sits on eu-west-2a
Dev sits on eu-west-3a

Google Filestore sits on eu-west-2a.

Meaning Prod cluster is ok and he can mount the volumes to all pods (ReadWriteMany).

But Dev cluster struggle to mount the volumes we reach  timeout .


```
Mounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs <NFS IP>:/<PATH> /var/lib/kubelet/pods/f10b9de9-f159-4a67-ae4d-0f31e6b3d7a1/volumes/kubernetes.io~nfs/website-fs-files]
Output: mount.nfs: Connection timed out

  Warning  FailedMount  24s (x2 over 4m57s)  kubelet, gke-platform-dev-system-pool-46318f24-ww70  Unable to attach or mount volumes: unmounted volumes=[website-files], unattached volumes=[website-files default-token-fcc59]: timed out waiting for the condition

```

**Comment by sowhatim** [comment]
I see, yes. This was randomly stuck for me but worked later on a new cluster. I haven't seen this issue since . Also maybe because I am using bigger instances now . 

Will close out the issue as I haven't got the time to reproduce .
