### ISSUE TITLE
Remove PodShareProcessNamespace feature gate

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#90096]
**What would you like to be added**:
PodShareProcessNamespace is in GA.
The feature gate can be removed.

**Why is this needed**:
```
	PodShareProcessNamespace:       {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.19
```

**Comment by tanjunchen** [comment]
@tedyu 
it is merged.
/close
