### ISSUE TITLE
Kubernetes not terminating pods after the respective deployment has been deleted

### ISSUE THREAD

**Issue by oaicstef** [kubernetes/kubernetes#90106]
**What happened**:
Every time I delete a deployment from console using kubectl the related pods are not deleted. 
Console command executed is:
kubectl delete deploy deploymentname -n namespacename

**What you expected to happen**:
I expect that the pods and replicasets associated to the deployment are terminated.

**How to reproduce it (as minimally and precisely as possible)**:
I reproduce it only on my dev cluster in fact if I execute same pattern on our production cluster it works properly. 
Console command executed is:
kubectl delete deploy deploymentname -n namespacename

**Anything else we need to know?**:
Please, let me know if I can check some configuration or what details you need.

**Environment**: Development
- Kubernetes version (use `kubectl version`): Client version 1.17.0 Server version 1.15.10
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cloud-provider
/sig apps
/sig scheduling

**Comment by ahg-g** [comment]
/remove-sig scheduling

Scheduling isn't involved in deleting pods.

**Comment by tedyu** [comment]
@oaicstef 
Can you attach controller manager log and kubelet.log (the portion that covered the deletion of deployment) ?

Thanks
