### ISSUE TITLE
dependencies.yaml : please add patch version for docker

### ISSUE THREAD

**Issue by larham** [kubernetes/kubernetes#90119]
**What would you like to be added**:

https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L28 

shows only the docker minor version, omitting the patch version.  e.g. `19.03`

Please add the patch version, e.g. `19.03.5`

**Why is this needed**:

All other dependencies are listed with patch version.  Docker releases are not available for download without a patch version. We'd like to know what version (or range) is used in the testing matrix, and ship that also.

**Comment by saschagrunert** [comment]
@Verolop are you still considering to work on this? We could also think about asking for volunteers again in SIG Release. :blush:

**Comment by pacoxu** [comment]
Since docker-shim is deprecated, should we close this?
