### ISSUE TITLE
CRD validation message confused users.

### ISSUE THREAD

**Issue by supermqB** [kubernetes/kubernetes#90128]
**What happened**:
I have a custom resource definition, there is a property with minimum=20 validation in it. When we set a a value(eg: 10) which is smaller than 20. I got an error likes below:
```
[root@node1 crds]# kubectl apply -f cr.yaml
The ****** "example-******" is invalid:
* spec.***.sysResource.cpuUsage: Invalid value: 20: spec.***.sysResource.cpuUsage in body should be greater than or equal to 20
```
**What you expected to happen**:
We expect the message like this, the invalid value should be the one what user specified.
```
* spec.***.sysResource.cpuUsage: Invalid value: 10: spec.***.sysResource.cpuUsage in body should be greater than or equal to 20
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2

After going through the source code, I found the problem is in line 82-88 of 
https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apiserver/validation/validation.go
```golang

			default:
				value := interface{}("")
				if err.Value != nil {
					value = err.Value
				}
				allErrs = append(allErrs, field.Invalid(errPath, value, err.Error()))
```

it created an error with the value in the result from func ExceedsMinimumInt in https://github.com/go-openapi/errors/blob/master/schema.go

```golang
return &Validation{
		code:    MinFailCode,
		Name:    name,
		In:      in,
		Value:   min,
		message: message,
	}
```

func ExceedsMinimumInt put the minimum value as the result value. it causes the final error message shows target value as input value. that makes user confused.

The problem can be fixed in go-openapi or in kubernetes/apiextensions-apiserver side.

**Comment by fedebongio** [comment]
/assign @sttts 
@supermqB since you already found the potential place to fix, would you like to send a PR linked to this issue? Thanks!

**Comment by raiaan12** [comment]
Would it be possible for you to share your cr.yaml file?

**Comment by liggitt** [comment]
Another openapi validation value issue reported at https://github.com/kubernetes/kubernetes/issues/91114, would be good to consider how both of these can be fixed at the same time

**Comment by gautierdelorme** [comment]
I reported the other related issue linked by @liggitt. How do we want to fix that? Should we make a code change in go-openapi? I shared a diff to resolve it in the other issue.

**Comment by gautierdelorme** [comment]
@supermqB are you working on a fix or should someone else take a stab at it?

**Comment by gautierdelorme** [comment]
@liggitt @sttts @fedebongio Looking at this issue and https://github.com/kubernetes/kubernetes/issues/91114 do you agree the fix should be in **github.com/go-openapi/errors** and **github.com/go-openapi/validate**?

**Comment by liggitt** [comment]
since that's where the error originates, that would seem to be the place that a fix/addition would need to start

**Comment by gautierdelorme** [comment]
Update: https://github.com/go-openapi/errors/pull/21 and https://github.com/go-openapi/validate/pull/126 are both merged. I'll now update K8s deps and tests.

**Comment by gautierdelorme** [comment]
/remove-lifecycle stale

The issue is still present. Fix have been made in upstream repos see (https://github.com/kubernetes/kubernetes/issues/90128#issuecomment-643941680) but the PR (https://github.com/kubernetes/kubernetes/pull/92146) is stuck on feedback due other dependencies changes.

**Comment by gautierdelorme** [comment]
As discussed in https://kubernetes.slack.com/archives/C0EG7JC6T/p1592287631273100 we moved from `go-openapi` to `kube-openapi` and we fixed the bug there (see https://github.com/kubernetes/kube-openapi/pull/213). The fix will be picked up by https://github.com/kubernetes/kubernetes/pull/95954.
