### ISSUE TITLE
Problem with dynamic CSI provisioning when fsgroup is set for access type RWO

### ISSUE THREAD

**Issue by rbo54** [kubernetes/kubernetes#90123]
**What happened**:
This defect is related to the solution chosen for a previous defect: https://github.com/kubernetes/kubernetes/issues/66323.
It appears the solution did not consider a use case our customer has which is described here.

The user wants to provision an NFS mount off of one of our arrays that supports NFS as a native protocol.
(We verified this on Kubernetes v1.14 and v1.16.)

The PVC definition is manually created before the deployment, resulting in a dynamically created volume that is available when the pod is deployed:
```json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xxx-pvc
  labels:
    app: xxx
spec:
  storageClassName: yyy
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
```

The user creates a Deployment where the container spec has the following securityContext, and the pod is deployed:
```json
    securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
```

The volume definition is:
```json
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: xxx-pvc
```

In the initial deployment, the NFS volume is dynamically created, and works correctly.
During the pod’s execution, the user code changes the modes of all the directories in the NFS mount to 0700, meaning only user 1000 has access.
Additionally, one should note that root squash is enabled on the array, meaning the array will not allow root access to such directories.
The pod finishes execution and terminates. The existing PVC and PV are retained.

Later the user again instantiates the deployment, using the same spec and security context, to the same volume.
This time the volume exists, and is published correctly, the CSI driver’s publish request and reply are:

time="2020-04-08T22:45:08Z" level=debug msg="/csi.v1.Node/NodePublishVolume: REQ 0283: VolumeId=twa-31b81e3979=_=_=39645=_=_=System, StagingTargetPath=/var/lib/kubelet/plugins/kubernetes.io/csi/pv/twa-31b81e3979/globalmount, TargetPath=/var/lib/kubelet/pods/721c5e66-79ea-11ea-a026-005056809fcd/volumes/kubernetes.io~csi/twa-31b81e3979/mount, VolumeCapability=mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > , Readonly=false], XXX_NoUnkeyedLiteral={}, XXX_sizecache=0"
time="2020-04-08T22:45:09Z" level=debug msg="/csi.v1.Node/NodePublishVolume: REP 0283: XXX_NoUnkeyedLiteral={}, XXX_sizecache=0"

Immediately after the completion of the publish request though, we see the following errors in the kubelet log:
Apr  8 18:45:09 k1143-10-247-102-215 kubelet: E0408 18:45:09.118620   27734 volume_linux.go:73] Chown failed on /var/lib/kubelet/pods/721c5e66-79ea-11ea-a026-005056809fcd/volumes/kubernetes.io~csi/twa-31b81e3979/mount: chown /var/lib/kubelet/pods/721c5e66-79ea-11ea-a026-005056809fcd/volumes/kubernetes.io~csi/twa-31b81e3979/mount: operation not permitted
Apr  8 18:45:09 k1143-10-247-102-215 kubelet: E0408 18:45:09.140409   27734 volume_linux.go:88] Chmod failed on /var/lib/kubelet/pods/721c5e66-79ea-11ea-a026-005056809fcd/volumes/kubernetes.io~csi/twa-31b81e3979/mount: chmod /var/lib/kubelet/pods/721c5e66-79ea-11ea-a026-005056809fcd/volumes/kubernetes.io~csi/twa-31b81e3979/mount: operation not permitted
Apr  8 18:45:09 k1143-10-247-102-215 kubelet: E0408 18:45:09.332586   27734 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/csi/csi-xxx.com^twa-31b81e3979=_=_=39645=_=_=System\"" failed. No retries permitted until 2020-04-08 18:45:17.332533963 -0400 EDT m=+10516.947250119 (durationBeforeRetry 8s). Error: "MountVolume.SetUp failed for volume \"twa-31b81e3979\" (UniqueName: \"kubernetes.io/csi/csi-xxx.com^twa-31b81e3979=_=_=39645=_=_=System\") pod \"xxx-5c4d84c767-xt69v\" (UID: \"721c5e66-79ea-11ea-a026-005056809fcd\") : applyFSGroup failed for vol twa-31b81e3979=_=_=39645=_=_=System: open /var/lib/kubelet/pods/721c5e66-79ea-11ea-a026-005056809fcd/volumes/kubernetes.io~csi/twa-31b81e3979/mount/xxx: permission denied"

The driver then receives an immediate NodeUnpublish request, which completes successfully, a new NodeStage, and then a new NodePublish, which has the same result as the one above, and we are in an unresolvable Kubernetes retry loop.

Please, note that, if directories created on mount are of mode 740 or similar, pod gets created without error but the directory’s owner UID and mode changes. 
Before
drwxr-----    2 1000 1000 22 Apr 1 11:36 test
After
drwxrws---    2 4294967294 1000 22 Apr 1 11:36 test

Looking at the Kubernetes code involved (this is tag v1.14.3 which matches exactly our deployment), 
https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/volume/csi/csi_mounter.go#L243
we see just after the call to NodePublish in csi_mounter.go line 243, if that was successful there is a call to applyFSGroup on line 271, and should that fail there is “attempt to rollback mount”, calling NodeUnpublish, and then we’re in the loop described above.

Looking one level down, at applyFSGroup csi_mounter.go line 378, it is a nop if either fsType is nil, or the accessModes are not ReadWriteOnce, or if the mount is readOnly. Otherwise it calls SetVolumeOwnership in this case.

https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/volume/volume_linux.go#L39
Looking at SetVolumeOwnership in volume_linux.go line 39, which is called in this case, if fsGroup is not null, it will call SetVolumeOwnership which calls internally filepath.Walk on a function to set the owner (which failed in the logs above), and change the mode (which failed in the logs above).

The CSI driver is not setting FsType in it’s storageclass; indeed the ControllerPublish call got “ext4” for the StorageClass which is completely ignored by the driver.
We tried setting FsType=”” but still got ext4 as the default, and even tried manually editing the PV to set fsType, but it is not allowed that we can set fsType to nil once PV has been created.

We tried the generic Kubernetes NFS CSI driver https://github.com/kubernetes-csi/csi-driver-nfs and discovered it works correctly with this same file and storage system and the same use case. We noted however that the generic driver only supports static provisioning, and in the example here the https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/examples/kubernetes/nginx.yaml the csi section fsType variable was not set, which causes the code discussed above to be avoided. Trying further we modified use of this driver to include fsType: nfs in the PersistentVolume and then it failed in the same way as our driver.

We then tried a similar static provisioning with our driver, avoiding the specification of the fsType variable in the PersistentVolume. Our driver then also worked, so our driver is behaving the same as the generic driver.

So in summary, to reproduce the bug, five things must happen:
-	fsType must be set (which is mandatory as far as we can tell with dynamic provisioning)
-	Volume access mode is set to RWO
-	Fsgroup parameter is used
-	Volume permissions changed by the container so root can no longer traverse the directory tree
-	Container is restarted after the permissions were changed in a previous deployment, that’s when it fails

So perhaps we’re missing something that isn’t obvious about how the driver should be interacting with Kubernetes in this situation. Right now though we don’t see any plausible actions the driver can take to ameliorate the problem other than a) using static provisioning, or b) relaxing the restrictions the user deliberately put on permissions when the volume is unpublished or unstaged, or something similar, which seems like an undesirable security risk.
The discussion in https://github.com/kubernetes/kubernetes/issues/6632 about the driver can supply a nil FsType does not seem possible when dynamic provisioning is used.

**What you expected to happen**:
We expected to be able to dynamically provision an NFS volume in this scenario without encountering the kubelet errors above

**How to reproduce it (as minimally and precisely as possible)**:
The steps to reproduce are described in detail above in the "What Happened" section.

**Anything else we need to know?**:
Not that we know of.

**Environment**:
- Kubernetes version (use `kubectl version`): 
1.14.3
- Cloud provider or hardware configuration: 
Virtual Machine, k8s installed via kubespray
- OS (e.g: `cat /etc/os-release`): 
[root@k1143-10-247-102-211 scale]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"

- Kernel (e.g. `uname -a`):
Linux k1143 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubespray
- Network plugin and version (if this is a network-related bug):
flannel
- Others:

/sig storage

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
There's a problem in the external-provisioner where a default fstype is set. We are looking to change this behavior in the next release, so that the fstype will become "". https://github.com/kubernetes-csi/external-provisioner/issues/328

In the meantime, I would suggest that the user uses RWX access mode or don't set fsgroup in their Pod

**Comment by msau42** [comment]
/assign @gnufied 
who is also looking at getting rid of our RWO heuristic to call ChangeVolumeOwnership, and make it an explicit option by the driver.

**Comment by rbo54** [comment]
Thanks msau42- we had suggested RWX as an option to our customer. An explicit option to allow ChangeVolumeOwnership would probably be preferential; as I don't see how it would work generally if the pod has every run before and configured root to have no access.

**Comment by msau42** [comment]
Adding an explicit option is an API change and will require going through alpha->beta->GA cycles, so will take some time to be available. Even then, I'm not sure if this would work as you intend?

Basically, the option would allow a driver to say "I don't support fsgroup". So in that case, the volume is always mounted with the default permissions when it was provisioned, and if the user wants to change those permissions, either the driver needs to support it as a CreateVolume option, or the user needs to manually update the permissions outside of Kubernetes. Is that going to work for your use case?

**Comment by rbo54** [comment]
I'm thinking to be useful, the option to run the fsgroup code may have to be dynamic. That is we want to do it on the first execution of the pod, but have a way to inhibit it if the volume is reused and the permissions have been restricted (and presumably it was already run the first time). I admit though that is complicated.

**Comment by msau42** [comment]
There is the fsgroupchangepolicy that is alpha in 1.18 that allows you to only set fsgroup the 1st time. But I'm not sure that's going to solve the problem of kubelet losing access to the nfs share. Fsgroup was not designed to handle nfs. @gnufied please correct me, but I believe nfs permission handling needs to be done in a different way.

**Comment by msau42** [comment]
> How would an API change be different than not supplying the fsGroup option in the first place?

The main difference is this API change would be something that drivers can specify, instead of relying on users to do the right thing in their Pod

**Comment by gnufied** [comment]
Yeah I think we have problem in heuristics we use for performing `SetVolumeOwnership` change for CSI volumes but fsGroup mechanism was not designed to be used for NFS volumes.

@rbo54 why do you need `fsGroup` mechanism at all because it sounds like you are giving `700` permission to the NFS volume and hence removing `fsGroup` line from pod's security context should retain the permission. Not having `fsGroup` field in pod will also skip call to ` SetVolumeOwnership` function.

The other thing is - if group of NFS volume is known, I would recommend adding that group as a supplemental group to the pod. https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups this would require no recursive permission change and as long volume has same group as what is specified in supplemental group, it will work.

**Comment by rbo54** [comment]
Hi Hemant, These sound like good suggestions. I don't know why the customer "needs" fsGroup as I agree with you once they are changing permissions it not necessary. I will point them to your comment and inquire. Thank you! Tom

**Comment by rbo54** [comment]
I don't think we need any additional assistance from the k8s team, so I'm going to close this for now. Thank you for your assistance and confirming our findings. Tom
