### ISSUE TITLE
bad error message for deeply malformed input

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9012]
If, for example, I leave 'Spec' out entirely, I get an error about a field of spec, but not about spec itself.  I think that would be a better error.

```
$ k create -f /tmp/y
Error from server: Pod "kube-dns-v1-kbs64" is invalid: spec.containers: required value
```

**Comment by bgrant0607** [comment]
It's because spec is technically optional, since we use the same schema for /status and for patches.

**Comment by spzala** [comment]
@thockin hi, I could recreate it with v1.6.4 and I was wondering if there are two issues here - bad message and also wrong message? 
`spec.selector:` is not required. The only required section is `spec.template`. 
I got this output:
```
$ kubectl create -f ngingx-deployment.yaml
The Deployment "nginx-deployment" is invalid:
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`
* spec.template.spec.containers: Required value
```
