### ISSUE TITLE
Watch interface docs ambiguous

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#90134]
The docs for the Watch interface are a little ambiguous: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/watch/watch.go#L34-L37

"If an error occurs or Stop() is called, this channel will be closed, in which case the watch should be completely cleaned up."

That can be read two ways:
* When the channel is closed, the watch is already completely cleaned up
* When the channel is closed, the caller must call Stop() to clean up resources.

If it's the first, can I suggest we rephrase to "If an error occurs or Stop() is called, this channel will be closed.  It is not required to call Stop() to free resources when the channel has been closed."

If it's the second, can I suggest we rephrase to "If an error occurs or Stop() is called, this channel will be closed.  On observing the closed channel, the caller must call Stop() to free resources."

/sig apimachinery

**Comment by fedebongio** [comment]
/assign @MikeSpreitzer 
Mike would you be interested in taking a look?

**Comment by MikeSpreitzer** [comment]
OK, I will take a look.
