### ISSUE TITLE
downgrade from client-side apply to server-side apply should fail with a conflict

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#90146]
**What would you like to be added**:

After server-side apply with `kubectl apply --server-side` is used on an object, then client-side apply with `kubectl apply` should conflict.

**Why is this needed**:

Once a resource is being managed by SSA, then we should prevent CSA from attempting to manage the object.

CSA should not be trusted to manage an object after SSA because SSA doesn't update the CSA annotation, so CSA will not be safe to use.

We can detect this condition if:
1) the field manager for SSA exists in managed fields
2) the object is sent with the CSA annotation

[This change is described in the upgrade pathway doc.](https://docs.google.com/document/d/1_YKsMttYZmIw2cSg-jH5PExHjA7FUyALAgHuXDDBcFY/edit)

This conflict detection would have prevented this issue https://github.com/kubernetes/kubernetes/issues/80916.

Note that this is a breaking change to the beta v2 for SSA to make SSA safer.

We would want to respect the force conflicts parameter and add it to CSA with `kubectl apply --force-conflicts` if for some reason a user wants to manage the object with CSA again, but it's unclear what the behavior would or should be. A user could use `diff` to test this behavior. Alternatives to this are:
- expect the user to delete and recreate the object
- clear or update managed fields directly so CSA doesn't conflict with SSA

cc @apelisse @jennybuckley @kwiesmueller @lavalamp

**Comment by lavalamp** [comment]
Note that today we have objects with managed fields set (because we set them all the time now) AND the client-side apply annotation. We shouldn't give conflicts to client-side apply on such objects until the user runs server-side apply.

Other than that I agree with everything.

**Comment by lavalamp** [comment]
An interesting way of making this all work might be doing the following in the server:

* Detect client-side apply requests (create or update with a different CSA annotation set)
* Get the user intent out of the annotation
* Ignore everything else about the request
* Call the SSA handler

I'm not sure if this is the best way of doing things (or even a good way), but I don't think we discussed it yet? It would make CSA and SSA behave very similarly.

**Comment by apelisse** [comment]
That would literally change all kubectl versions to "default" to SSA. I don't hate the idea, though it's a little surprising for users. Also, how would they break-glass if they want to use CSA again or exclusively?

**Comment by kwiesmueller** [comment]
I think CSA currently tells you to recreate an object if it was not applied before. At least i think to remember a warning like this in the past.
People might actually be used to it?

I would prefer a solution we can implement on the server, so it doesn't matter how old the client is.
Though, i'm not sure if it's okay to add csa annotation detection on the server, as it didn't care about it before. But we could detect it and issue a normal ssa conflict or another conflict error.

There already is the --force flag, if we can use this instead of a second --force-conflicts one, we could probably implement this without having to touch kubectl/making it compatible with all kubectl versions.

Also:
/sig api-machinery
/wg api-expression

**Comment by julianvmodesto** [comment]
Oh for the upgrade: instead of calling the SSA handler completely on CSA, we could update managed fields on CSA so that they match for both the CSA manager and the SSA manager.

Also for the downgrade (mentioning discussion for posterity), as an alternative to failing a downgrade from CSA to SSA with a conflict, @apelisse suggested we keep the last-applied annotation up-to-date with managed fields: https://github.com/kubernetes/kubernetes/pull/90187.

We could keep both managed fields and the last-applied annotation up to date to support the upgrade and the downgrade.

**Comment by julianvmodesto** [comment]
Closing this one. We've addressed this differently by keeping the last-applied annotation up-to-date so CSA and SSA don't conflict.

See the KEP section in https://github.com/kubernetes/enhancements/pull/1382.
