### ISSUE TITLE
kubernetes-el7-x86_64/Packages are missing

### ISSUE THREAD

**Issue by 13217amasia** [kubernetes/kubernetes#90158]
Packages are missing! 4/14/2020 10:17 PM US Central Time
**What happened**:
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/Packages directory is empty???
**What you expected to happen**:
To see packages in there.
**How to reproduce it (as minimally and precisely as possible)**:
Open url https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/Packages in browser
**Anything else we need to know?**:
Lockdown at home!  :-(
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by 13217amasia** [comment]
Looks like there are *no* packages under https://packages.cloud.google.com/yum/repos/

**Comment by 13217amasia** [comment]
Update 4/16/2020 4:05 US Central Time:
Packages appeared at https://packages.cloud.google.com/yum/repos/ 
Still nothing listed at https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/Packages

**Comment by neolit123** [comment]
/sig release
/priority backlog

i think the /packages folder was always empty (maybe the files are just hidden).
you can ask in the #sig-release channel on slack.

**Comment by neolit123** [comment]
/priority critical-urgent
/milestone v1.19

as indicated by @redcricket in https://github.com/kubernetes/website/issues/21071
the kubelet, kubeadm, kubectl packages are indeed missing.

full reproduction steps:
```
$ docker pull fedora:33
$ docker run -it fedora:33 bash

# inside the container
# instead of \$basearch one can also try `x86_64`
$ cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# this would fail
$ yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes

# only the cni/cri-tools packages are found
cri-tools.x86_64                                                                         1.13.0-0                                                         kubernetes           
kubernetes-cni.x86_64                                                                    0.7.5-0                                                          kubernetes

# installing one of them results in an error
$ yum install kubernetes-cni --skip-broken
Problem: package kubernetes-cni-0.7.5-0.x86_64 requires kubelet, but none of the providers can be installed
```

**Comment by neolit123** [comment]
so this is actually a completely different issue here...
see https://github.com/kubernetes/website/issues/21040

the `–` is not a `--` so the flag is ignored and fails.

```
yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes
```

if you try 
```
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
```
it works fine.

i'm going to send a fix for 
https://github.com/kubernetes/website/issues/21040

/close
/milestone clear

**Comment by redcricket** [comment]
I remove this line ...

exclude=kubelet kubeadm kubectl


... from the yum repo file.

**Comment by neolit123** [comment]
instead of removing the line just pass `--disableexcludes=kubernetes`
if you remove the line this means that when you upgrade with `yum` you will upgrade your k8s cluster components which is not desired in most cases.

**Comment by Joseph94m** [comment]
@neolit123 Hi. Pretty sure I should re-open this issue instead of creating a new one (let me know if this needs a new issue with more details). As per [documentation](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/), installing kubeadm, kubelet and kubectl on rhel releases (el7) using the following configuration where K8S_VERSION=1.19.15

```
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# Set SELinux in permissive mode (effectively disabling it)
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

sudo yum install -y kubelet-$K8S_VERSION kubeadm-$K8S_VERSION kubectl-$K8S_VERSION --disableexcludes=kubernetes

sudo systemctl enable --now kubelet
```

Results in the following:

```
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.plusserver.com
 * epel: mirror.23m.com
 * extras: mirror.plusserver.com
 * updates: mirror.plusserver.com
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x7AA99B80:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)"
 Fingerprint: e89b faec 34d3 1829 362f 7f7b 5668 44f3 7aa9 9b80
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.


 One of the configured repositories failed (Kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kubernetes ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes
        or
            subscription-manager repos --disable=kubernetes

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
```


I haven't tried other versions of kubernetes

-----

On an (maybe) unrelated note, we also experienced an issue that you should be aware of: when we tried upgrading an existing el7 cluster from 1.18.20 to 1.19.16, the 1.19.16 packages were found only for the server side of the api server, so instead yum/Kubernetes decided to install 1.23.3 for the client side... I kept it like that for a while and then upgraded everything to 1.23.3 but the devs weren't too happy because of all the API, chart, helm, CRDs incompatibilities that it caused.

Let me know if I should open separate issues for these reports.

**Comment by neolit123** [comment]
> using the following configuration where K8S_VERSION=1.19.15

I did not try such an old version though. Make sure the issue is reproducible with 1.21+
