### ISSUE TITLE
Loadbalancer service sometimes cannot be deleted with annotation "azure-shared-securityrule" in Azure

### ISSUE THREAD

**Issue by kunmin-db** [kubernetes/kubernetes#90150]
**What happened**:

We notice when we create LoadBalancer service with the annotation `service.beta.kubernetes.io/azure-shared-securityrule: true`, it could fail to delete the service because of controller manager logic in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L205-L236

I believe what happens is:
1. Service deletion is triggered. The `reconcileSecurityGroup` is called and the service IP is removed from the shared security group.
2. `reconcileLoadBalancer` is called but some cloud provider error happened, so it returns an error and the the deletion is aborted.
3. After some time `EnsureLoadBalancerDeleted` is triggered again, and `reconcileSecurityGroup` is called again. But it fails to do that because it fails to check the IP in the destination because it's already removed. https://github.com/kubernetes/kubernetes/blob/aed3f054953ef28174930ce9c540f5c2b003ae78/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L1240 in step 1. It aborts and fall into dead loop for deleting this service.

**What you expected to happen**:

I will expect it can still delete the service regardless of any intermittent cloud provider error in step 2. 
I believe the problem is the `reconcileSecurityGroup` is not idempotent with this annotation enabled. 

**How to reproduce it (as minimally and precisely as possible)**:

We don't have a reliable way to reproduce it as it relies on cloud provider to return certain error in the loadbalancer step. But we observe two different error message from Azure:
1. 
```
E0411 03:45:21.868143       1 service_controller.go:255] error processing service $service_name (will retry): failed to delete load balancer: Code="PreconditionFailed" Message="Precondition failed." Details=[{"code":"PreconditionFailedEtagMismatch","message":"Etag provided in if-match header W/\"1ecc662b-5420-46eb-ae68-e8a91009xxxx\" does not match etag W/\"93ea9d6e-ff6c-411a-b0e0-4e28f9adxxxx\" of resource $RESOURCE_ID in NRP data store."}]
```
I am also curious why the Etag could be mismatch. From the Azure activity log, all activity comes from this Kubernetes cluster. So I would expect controller manager can always keep the Etag in sync.
2. 
```
I0413 03:38:54.294237       1 azure_loadbalancer.go:956] reconcileLoadBalancer: reconcileLoadBalancer for service($service_name): lb(kubernetes) - updating
E0413 03:39:05.981812       1 azure_backoff.go:749] processHTTPRetryResponse: backoff failure, will retry, err=Code="RetryableError" Message="A retryable error occurred." Details=[{"code":"RetryableErrorDueToAnotherOperation","message":"Operation AllocateTenantNetworkResourcesOperation (0e073647-1e5f-4f36-9418-5b109ebxxxx) is updating resource $SUBSCRIPTION_ID. The call can be retried in 12 seconds."}]
```
This error is probably not related to Kubernetes.

**Anything else we need to know?**:
We only have one replica of controller manager running.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.6
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): CentOS
- Kernel (e.g. `uname -a`): `3.10.0-1062.4.1.el7.x86_64`
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by jmos5156** [comment]
Can we re-open this as we have hit this same issue twice now on two different clusters. Although we have not been able to repeat the issue at will, we have experienced the same issue described above. We have found that using the same shared rule annotation, can sometimes lead to errors like this 
```
log_s | I0226 18:03:30.888266       1 event.go:291] "Event occurred" object="do/sftpserver" kind="Service" apiVersion="v1" type="Warning" reason="DeleteLoadBalancerFailed" message="Error deleting load balancer: Expected to find destination address 52.155.230.99 in shared rule shared-TCP-22-Internet for service sftpserver being deleted, but did not"
-- | --
```
In an attempt to fix and reverse back we have deleted the Helm release and for the service + endpoint object that was left behind, we have had to use a `kubectl patch ` command to add null to the finalizers and force K8 to remove the object from its listings.

Subsequent redeploys of the release do not work and result in the exact same failure.

Attempting to manually add the IP to the NSG only compounds the issue as we then hit duplicate resource issues. We've dug ourselves so deep that our only option has been to recreate the cluster.
