### ISSUE TITLE
Add the option to log not-skipped events only to EventBroadcaster

### ISSUE THREAD

**Issue by towca** [kubernetes/kubernetes#90168]
**What would you like to be added**:
EventBroadcaster should allow to log only those events which aren't skipped by the correlator and are actually passed to sinks.

**Why is this needed**:
`NewBroadcasterWithCorrelatorOptions()` allows creating a broadcaster with rate-limiting options. However, those options only get applied when recording to sink via `StartRecordingToSink()` and not when logging via `StartLogging()`. If a user produces a lot of events, it's likely that they'd want to only log information about those that actually passed rate-limiting, to avoid filling up the log. With the current implementation, they'd have to either replicate the rate-limiting logic on the caller side, or implement a wrapper around a sink which does the logging.

We encountered this problem in Cluster Autoscaler and we'll solve it with the wrapper for now, but I think it'd beneficial to add the option directly to EventBroadcaster.

**Comment by bartekzurawski** [comment]
Hello! Can I take this one and try work on it?

**Comment by fedebongio** [comment]
/assign @bartekzurawski bartekzurawski
Yes, thank you!
/triage accepted
