### ISSUE TITLE
Scheduler not always taking into account init containers

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#90177]
According to documentation https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources

> The Pod’s effective request/limit for a resource is the higher of:
> - the sum of all app containers request/limit for a resource
> - the effective init request/limit for a resource

We are respecting this in the NodeResourcesFit plugin: https://github.com/kubernetes/kubernetes/blob/495b0ddfaaec93fce726ffee7acabfb55d56327b/pkg/scheduler/framework/plugins/noderesources/fit.go#L104

But we are not respecting that in the cached node size https://github.com/kubernetes/kubernetes/blob/495b0ddfaaec93fce726ffee7acabfb55d56327b/pkg/scheduler/framework/v1alpha1/types.go#L454

/sig scheduling

**Comment by Huang-Wei** [comment]
@alculquicondor #89222 is already working on this.

**Comment by alculquicondor** [comment]
/close
duplicate of #89092
