### ISSUE TITLE
gce Instances::NodeAddresses assumes it is run from the relevant instance.

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#90185]
**What would you like to be added**:
Please see https://github.com/kubernetes/kubernetes/pull/90057#discussion_r408929994
Implement Instances::NodeAddresses so it doesn't ignore the node input.

**Why is this needed**:
The current implementation assumes it will be *only* run on the Kubelet.
That is no longer a valid assumption and in fact it the nearish future it will no longer be run on the Kubelet.

**Comment by kaishah** [comment]
@cheftako Is this issue solved by #90181 or does the NodeAddresses function still need to change? I can work on the change if needed

**Comment by cheftako** [comment]
This issue is about the GCE implementation found at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/gce/gce_instances.go#L86. This problem cannot be fixed in the cloud node controller.

**Comment by jiahuif** [comment]
According to https://github.com/kubernetes/kubernetes/blob/v1.19.0-alpha.2/staging/src/k8s.io/cloud-provider/cloud.go#L158-L169

`NodeAddresses` is indeed only used for the address of the calling instance. Maybe we should use `NodeAddressesByProviderID` instead?

**Comment by jiahuif** [comment]
Or, we should definitely remove the `TODO` if its TODO item is no longer true.

**Comment by cheftako** [comment]
I believe the TODO is no longer true as there is also a call in https://github.com/kubernetes/kubernetes/blob/e8d6d3768e1131d6c3cd9ab5b7144a3a00c916f8/pkg/controller/cloud/node_controller.go#L543
