### ISSUE TITLE
Start a stopped pod/container manually on local dev environment

### ISSUE THREAD

**Issue by winkee01** [kubernetes/kubernetes#90202]
**What would you like to be added**:
The semantics and operation on starting a stopped pod/container.

**Why is this needed**:
restartPolicy includes 3 strategies Never, OnFailure and Always. 

Although most of time it's recommended to let the kube to restart the pods for us, but since there is a **Never** semantics, which means kube won't do restart of the pod for us, but then how do we start it manually if we need? Is this semantics missed? (In my case, I ran a single pod and fix some time zone error, but when I killed my container to restart it, I found there is no way I can do it, `kube restart pod` just doesn't exist). So basically, kube provides **Never** semantics but provides no start semantic? What if a container can not just be restarted before some bugs fixed? On my local dev environment, can there be a way I can do something to my containers in pods, stop them and restart them again?

Should there be a way to complement the 'Never' semantics and provide some flexibility so that I can restart my pod instead of let the kube take all over it?  Sorry I have consult with many k8s guys they all tell me this is not restart concept in k8s. 

Is there some philosophy I missed? As a novice, I tested and played kubernetes in my local development environment and had much fun, would be much appreciate it if my confusion be cleared, thanks a lot!

Environment:

Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}

Cloud provider or hardware configuration:
OS MacOS 10.14.6 Mojave

**Comment by liggitt** [comment]
In that case, deleting and recreating the pod is what would be expected.

/close

**Comment by winkee01** [comment]
> In that case, deleting and recreating the pod is what would be expected.
> 
> /close

for a single pod( I am in test environment), if I delete it all state is gone, why don't allow me to make some changes to the container and start it up again?
I encounter this problem when I try to fix a NTP time issue and it ask me to restart the container.

well, why would it be ok for kube to restart the pod but not me?  for single pod, it's reasonable for me to manually start the pod, with the semantics support of restartPolicy. It make sense for a user to start the pod with regard to the 'Never' option. In my opinion, never means kube won't do it, and leave it to the user. otherwise, kube can just delete it, right?
