### ISSUE TITLE
kube-apiserver rolls back from 1.16 to 1.8 with `Error from server: no kind "Deployment" is registered for version "apps/v1"`

### ISSUE THREAD

**Issue by helios741** [kubernetes/kubernetes#90205]
I know that upgrading from 1.8 to 1.16 is very risky.

Because the `extensions/v1beta1` apiVersion  we used was deprecated in 1.16, We reused the deprecated API by specifying the --runtime-config parameter of the API server, as follows

```shell
--runtime-config=extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,apps/v1beta2=true,apps/v1beta1=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true \
```

I upgraded an environment from 1.8 to 1.16 without problems,but I want to roll back the 1.16 environment back to 1.8, the following problem appears:
```shell
# k get deploy -n helios
Error from server: no kind "Deployment" is registered for version "apps/v1"
```
RS and DS are ths same output, it should be the change of apiserver that caused this problem, why is this?

I want to save the pre-upgrade ETCD data first, and then use the pre-upgrade data if the above problem occurs. Although the data will be lost for a period of time, it is guaranteed to be available. Is this OK?

sig/api-machinery
area/apiserver

**Comment by liggitt** [comment]
Rollback of more than 1 minor release is not supported. 1.16 persists data in etcd in formats that are only guaranteed to be readable by 1.15+ API servers.

Restoring from an etcd backup will lose any changes made to that data, including records of things that correspond to items that live outside the cluster, like persistentvolumes.

/close

**Comment by helios741** [comment]
@liggitt 
Is there any way to convert the data (the format supported by 1.16 is converted to the one supported by 1.8)?
