### ISSUE TITLE
GCE Windows e2e tests: artifacts are not being collected from Windows nodes

### ISSUE THREAD

**Issue by pjh** [kubernetes/kubernetes#90224]
Example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1250897317888790529 has artifacts from the master and the two Linux worker nodes, but not the three Windows worker nodes. The artifacts should include log files and other critical information for debugging failures.

This has been broken for at least [one month](https://github.com/kubernetes/kubernetes/issues/88974#issuecomment-600205597).

**Comment by pjh** [comment]
/assign

cc @YangLu1031

**Comment by pjh** [comment]
Oh, this is only happening for our 1909 test jobs, and not every run. Here's [one run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1250866865962487812) from today that has the expected artifacts. Here's a [run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1250897317888790529) where the only artifacts for the Windows nodes are the serial port logs, and here's a [run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1250836338651959298) where partial artifacts were collected, but only from two nodes strangely (what happened to the third node??).

Notably, the two runs with incomplete artifacts completed after 2h0m, whereas the run with full artifacts completed after only 1h52m. It looks like our two-hour test timeout can interrupt the artifact gathering that happens at the end of a test run, which is unfortunate.

**Comment by jingxu97** [comment]
now most of tests do not have kubelet logs uploaded due to permission issue.
