### ISSUE TITLE
Official website docs error

### ISSUE THREAD

**Issue by jihaojie** [kubernetes/kubernetes#90245]
**What happened**:
Official website docs  date error
URL：
https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#%E6%9C%80%E5%A4%A7%E5%A2%9E%E9%87%8F

**What you expected to happen**:

例如，当此值设置为 30 时，启动滚动更新后，会立即展开新的 ReplicaSet ，以便新旧 Pod 的总数不超过所需的 130%。一旦旧 Pods 被杀死，新的 ReplicaSet 可以进一步扩展，确保更新期间任何时间运行的 Pods 总数最多为所需 Pods 总数的130%。

30 should be 30%

**Comment by wawa0210** [comment]
Thank you very much for pointing out the problem, I will fix the Chinese document

**Comment by wawa0210** [comment]
/close 

The issue has been fixed.

**Comment by wawa0210** [comment]
/close

The issue has been fixed.
