### ISSUE TITLE
kubelet_container_log_filesystem_used_bytes not accurate

### ISSUE THREAD

**Issue by hykych** [kubernetes/kubernetes#90272]
**What happened**:
I use the metrics, but I found there is one time this data is not accurate, the logs for the pod is 50KB, but there is one time the data surge to 800+MB.  I took a look at the source code, It seems like the data of **kubelet_container_log_filesystem_used_bytes** is not only the logs size.

**What you expected to happen**:
**kubelet_container_log_filesystem_used_bytes** should be same as the log size.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Version: V1.13.12

**Comment by neolit123** [comment]
> Version: V1.13.12

please note that if this is the k8s version, it's out of support.
you should upgrade to 1.16 at minimum.

**Comment by jlohiya** [comment]
I do see similar issue on v1.17

kubelet_container_log_filesystem_used_bytes metrics shows more bytes than its actually on disk. This metric never goes down. We have rotating logs capped at 50MB and still we see this metrics goes to 100-200MB.

Can someone help me how is that possible?

EX: 
I have mount path /var/local/jlohiya
where my container created files of 50MB
then it got consumed/deleted
then again files got created..

this process goes on, at a time only 50MB can be there at mount path but I see that "kubelet_container_log_filesystem_used_bytes " shows 100MB 200MB values.

Can someone help me in understanding that, whats happening here?

**Comment by jlohiya** [comment]
@hykych Can you share the code piece where you noticed its not for just logs?

**Comment by Dentrax** [comment]
Any updates here? @hykych Did you figure it out yet?
