### ISSUE TITLE
Incorrect job completed state

### ISSUE THREAD

**Issue by wikusbrinkNearmap** [kubernetes/kubernetes#90290]
**What happened**:
When running many Kubernetes jobs (hundreds to thousands) on our cluster we've had several cases of jobs completing successfully according to Kubernetes, without actually having completed.

In other words `kubectl describe job` returns `Pods Statuses:  0 Running / 1 Succeeded / 0 Failed`, but the data that the job was tasked to generate does not exist (any execution error will appear in our logs and will cause the pod to fail).

When we rerun the jobs they complete as expected.

This happens seemingly at random, and we've been unable to find any reason for this.
We've observed this behaviour using kubectl and Kubeflow.

**Environment**:
- Environment: EC2 cluster, Kubernetes cluster managed by kops Version 1.15.2
- Kubernetes version:
-- Client Version: version.Info{Major:“1”, Minor:“16", GitVersion:“v1.16.2”, GitCommit:“c97fe5036ef3df2967d086711e6c0c405941e14b”, GitTreeState:“clean”, BuildDate:“2019-10-15T19:18:23Z”, GoVersion:“go1.12.10”, Compiler:“gc”, Platform:“darwin/amd64”}
-- Server Version: version.Info{Major:“1", Minor:“15”, GitVersion:“v1.15.1", GitCommit:“4485c6f18cee9a5d3c3b4e523bd27972b1b53892”, GitTreeState:“clean”, BuildDate:“2019-07-18T09:09:21Z”, GoVersion:“go1.12.5", Compiler:“gc”, Platform:“linux/amd64"}
- Cloud provider or hardware configuration: EC2 r5.4xlarge (spot)
- OS (e.g: `cat /etc/os-release`):
-- PRETTY_NAME=“Debian GNU/Linux 9 (stretch)”
-- NAME=“Debian GNU/Linux”
-- VERSION_ID=“9”
-- VERSION=“9 (stretch)”
-- ID=debian
-- HOME_URL=“https://www.debian.org/”
-- SUPPORT_URL=“https://www.debian.org/support”
-- BUG_REPORT_URL=“https://bugs.debian.org/”
- Kernel (e.g. `uname -a`): Linux amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux

**Comment by tedyu** [comment]
Can you attach snippet of controller manager log where the job for 'Pods Statuses: 0 Running / 1 Succeeded / 0 Failed' showed up ?

If related log points to certain node, please collect kubelet.log from that node as well.

Thanks

**Comment by konradlykowski** [comment]
Hey @tedyu , thanks for the help. Unfortunately we don't have those logs any more. 
Although we might see those cases again in the near future - let us go back with more logs within a few days/weeks. Thanks!

**Comment by soltysh** [comment]
This is known issue being discussed in https://github.com/kubernetes/kubernetes/issues/28486. Please move all discussion over there. Closing this as a duplicate.
/close
