### ISSUE TITLE
kubelet warnings W0420 flooding systemd logs (kubernetes 1.18.2)

### ISSUE THREAD

**Issue by msschl** [kubernetes/kubernetes#90293]
**What happened**:
there are many kubelet warnings in the systemd logs

```
Apr 20 11:03:37 lxkubenode01 kubelet[9103]: W0420 11:03:37.275020    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/63c4a49f-bf23-4b87-989e-102f5fcdb315/volumes/kubernetes.io~secret/seq-token-whpfk and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:46 lxkubenode01 kubelet[9103]: W0420 11:03:46.198559    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/cdb79fa0-4942-4211-9261-a4928f872bd6/volumes/kubernetes.io~secret/prometheus-operator-prometheus-node-exporter-token-snbtf and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:47 lxkubenode01 kubelet[9103]: W0420 11:03:47.201212    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/8cafe45f-2d14-4eb1-8c38-71a54b34f83c/volumes/kubernetes.io~secret/default-token-9hq84 and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:50 lxkubenode01 kubelet[9103]: W0420 11:03:50.209770    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/174c1204-11e5-4297-b71f-1ebd2c961b95/volumes/kubernetes.io~secret/default-token-cwdzw and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:50 lxkubenode01 kubelet[9103]: W0420 11:03:50.209791    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/174c1204-11e5-4297-b71f-1ebd2c961b95/volumes/kubernetes.io~configmap/config-volume and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:53 lxkubenode01 kubelet[9103]: W0420 11:03:53.217655    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/655e1952-1200-4653-bdd6-e4029cb75d2b/volumes/kubernetes.io~configmap/config-volume and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:53 lxkubenode01 kubelet[9103]: W0420 11:03:53.217671    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/2f69fc08-f4c9-447b-8cb2-bf737a2d9136/volumes/kubernetes.io~configmap/app-config and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:53 lxkubenode01 kubelet[9103]: W0420 11:03:53.217738    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/655e1952-1200-4653-bdd6-e4029cb75d2b/volumes/kubernetes.io~secret/default-token-cwdzw and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:53 lxkubenode01 kubelet[9103]: W0420 11:03:53.217769    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/2f69fc08-f4c9-447b-8cb2-bf737a2d9136/volumes/kubernetes.io~secret/geocoding-aspnetcore-token-xrg72 and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Apr 20 11:03:53 lxkubenode01 kubelet[9103]: W0420 11:03:53.217805    9103 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/2f69fc08-f4c9-447b-8cb2-bf737a2d9136/volumes/kubernetes.io~secret/dataprotection-certs and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
```

I initialized the cluster with kubeadm init (no modifications)

**What you expected to happen**:

Not to have that many kubelet warnings in the system logs

**Anything else we need to know?**:

Environment:

- Kubernetes version (use kubectl version):
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `kubeadm on Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64) amd64`

- OS (e.g: cat /etc/os-release):
```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. uname -a): `Linux lxkubemaster01 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools: `kubeadm`

**Comment by DesistDaydream** [comment]
I have the same issue

**Comment by zhangguanzhang** [comment]
should add a option or an annotationo to resolve this 
/sig node
/area kubelet

**Comment by notariuss** [comment]
Same issue
kops, kubernetes 1.18.2
`Jun 08 08:31:22 ip-172-20-82-162 kubelet[2708]: W0608 08:31:22.792168    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/3c0e6aea-a4b7-453e-8ee9-e910a0016a8f/volumes/kubernetes.io~configmap/config and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:22 ip-172-20-82-162 kubelet[2708]: W0608 08:31:22.792522    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/3c0e6aea-a4b7-453e-8ee9-e910a0016a8f/volumes/kubernetes.io~secret/mysql-token-hdqtk and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:36 ip-172-20-82-162 kubelet[2708]: W0608 08:31:36.832610    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/666ffcac-6305-4144-921a-b0830926e31c/volumes/kubernetes.io~configmap/config and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:36 ip-172-20-82-162 kubelet[2708]: W0608 08:31:36.832659    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/666ffcac-6305-4144-921a-b0830926e31c/volumes/kubernetes.io~configmap/health and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:36 ip-172-20-82-162 kubelet[2708]: W0608 08:31:36.833220    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/666ffcac-6305-4144-921a-b0830926e31c/volumes/kubernetes.io~secret/default-token-x7wgj and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:40 ip-172-20-82-162 kubelet[2708]: W0608 08:31:40.861713    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/7f9e0c5f-3c6d-4400-ad40-2e6c8a53d67d/volumes/kubernetes.io~configmap/config and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:40 ip-172-20-82-162 kubelet[2708]: W0608 08:31:40.861727    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/7f9e0c5f-3c6d-4400-ad40-2e6c8a53d67d/volumes/kubernetes.io~secret/default-token-x7wgj and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 08 08:31:40 ip-172-20-82-162 kubelet[2708]: W0608 08:31:40.862554    2708 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/7f9e0c5f-3c6d-4400-ad40-2e6c8a53d67d/volumes/kubernetes.io~configmap/health and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699`

**Comment by presidenten** [comment]
Same issue on v1.17.4

**Comment by oldthreefeng** [comment]
Same issue on v1.18.0   ~

**Comment by yerzhant** [comment]
Same issue on 1.17.6
```
Jun 13 15:32:17 worker-2 kubelet[4066]: W0613 15:32:17.240330    4066 volume_linux.go:45] Setting volume ownership for /var/lib/kubelet/pods/d9a36c2c-c87f-4f3f-8323-3434915dcd84/volumes/kubernetes.io~secret/auth and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 13 15:32:17 worker-2 kubelet[4066]: W0613 15:32:17.240675    4066 volume_linux.go:45] Setting volume ownership for /var/lib/kubelet/pods/d9a36c2c-c87f-4f3f-8323-3434915dcd84/volumes/kubernetes.io~secret/default-token-kq9fq and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
Jun 13 15:32:17 worker-2 kubelet[4066]: W0613 15:32:17.241329    4066 volume_linux.go:45] Setting volume ownership for /var/lib/kubelet/pods/d9a36c2c-c87f-4f3f-8323-3434915dcd84/volumes/kubernetes.io~configmap/docker-reg-docker-registry-config and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699
```

**Comment by eplightning** [comment]
Happens on v1.18.3 as well. 

This issue only occurs when container has some fsGroup set in its securityContext AND volume being mounted is either secret or a configmap. I guess they are being re-mounted every 70s or so.

It's okay when the volume being mounted is a standard PV - log only appears once and doesn't get repeated.

**Comment by jvanz** [comment]
I'm seeing the same issue. I'm willing to fix it.

**Comment by jvanz** [comment]
I've digged into this a little bit further. I believe this is just a annoying warning message. AFAICS, it does not show any issue... 

I was reading the kubelet, its volume manager and the volume plugins source files. It seems that's the expected behavior. The desiredStateOfWorldPopulator sync loop always call the [MarkRemountRequired](https://github.com/kubernetes/kubernetes/blob/v1.17.4/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L361). 
The [function](https://github.com/kubernetes/kubernetes/blob/v1.17.4/pkg/kubelet/volumemanager/cache/actual_state_of_world.go#L490) finds the volume plugin and check if the plugin requires mount. Secret plugin, witch is the plugin in discussion, always returns [true](https://github.com/kubernetes/kubernetes/blob/v1.17.4/pkg/volume/secret/secret.go#L84). Thus, the [reconciler code](https://github.com/kubernetes/kubernetes/blob/v1.17.4/pkg/kubelet/volumemanager/reconciler/reconciler.go#L233) of the volume manager  remounts the volume all every time.

I think the problem is in the [statement](https://github.com/kubernetes/kubernetes/blob/v1.17.4/pkg/volume/volume_linux.go#L45) which prints the warning message. It's more [recent](https://github.com/kubernetes/kubernetes/commit/223ef76db5a4a537ab670a2f66a830ee97c89105) and I believe it does not take these plugins into account. The secret plugin is as it is now since [2016](https://github.com/kubernetes/kubernetes/commit/542f2dc70802e47564c5d68b88228211f65aa91b).

Is that make sense to you?
