### ISSUE TITLE
v1.19.0 Release Notes: "Known Issues" 

### ISSUE THREAD

**Issue by puerco** [kubernetes/kubernetes#90304]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.19 Release Notes. If you know of issues or API changes that are going out in 1.19, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @kubernetes/release-team

/sig release
/milestone v1.19

**Comment by pohly** [comment]
The new storage capacity tracking alpha feature is known to be affected by a limitation of the `WaitForFirstConsumer` volume binding mode: https://github.com/kubernetes/kubernetes/issues/94217

This is mentioned in the documentation of the feature (https://github.com/kubernetes/website/pull/21634#discussion_r454631648), but it may be worth calling out also as a known issue in the release notes.

**Comment by puerco** [comment]
@pohly as noted on your issue, we added a Known Issue to the final v1.19 release notes. Thanks for your feedback!

**Comment by puerco** [comment]
All known Issues are now merged in the final Release Notes for Kubernetes v1.19:
https://github.com/kubernetes/sig-release/pull/1193

Closing 
/close
