### ISSUE TITLE
Use maxSkew in TopologySpreadingContraint to affect scoring weight

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#90308]
Spin-off from #88174

**What would you like to be added**:

Use maxSkew in TopologySpreadingContraint to affect relative weight of the constraint.
Exact formula to be discussed.

Some ideas:
1. `baseScore / maxSkew`, intuitive but too coarse-grained at low numbers. Goes: 100%, 50%, 33%, 25%, 20%
1. `baseScore * (k+1) / (k + maxSkew)` some linearity. For `k=1`, goes: 100%, 66%, 50%, 40%, 33%
1. `baseScore * (k+1) / (k + maxSkew)`. For `k=2`, goes: 100%, 75%, 60%, 50%, 42%
1. `baseScore / sqrt(maxSkew)`. Goes: 100%, 70%, 57%, 50%, 44%

**Why is this needed**:

- When using `defaultConstraints` for `PodTopologySpreading`, it will be useful for operators to control how strong the constraints should be compared to explicit user requests.
- Pods would be able to control the weight of constraints per-topology.

**Comment by Huang-Wei** [comment]
1 maybe the most compatible option with the current zone:node ratio (2:1):

https://github.com/kubernetes/kubernetes/blob/b35fdbc0370c11db06ee30be579f83aff62932fb/pkg/scheduler/framework/plugins/defaultpodtopologyspread/default_pod_topology_spread.go#L46

**Comment by alculquicondor** [comment]
Not quite. The ratio is correct, but the weight is different.

original: `1/3 * node_score + 2/3 * zone_score`
prop 1: `1/4 * node_score + 1/2 * zone_score`

**Comment by alculquicondor** [comment]
I realized that using `maxSkew` as weight is quite counterintuitive. Instead, I propose that we use `maxSkew` to water down the counts per topology.

`newCount := max(count - maxSkew + 1, 0)`

This way, the behavior still doesn't change for `maxSkew = 1`. But as `maxSkew` increases, counts become more similar. For example, given the counts `5 3 2 7` and `maxSkew=3`, we get the new counts: `2 0 0 4`. Then we proceed with the counts normalization as usual.

Note that when the minimum count is zero in a topology, this procedure has the effect of giving the max score (100) for nodes (or zones) that would satisfy the `maxSkew` condition.
That won't be true when the minimum count is not zero, but enforcing it would be quite costly. This proposal still gets us closer to that and reduce score differentiation among nodes within the skew.

When using constraints against multiple topologies, another side effect is that topologies with bigger `maxSkew` would have a reduced effect in the overall score.

**Comment by ahg-g** [comment]
That sounds better than the original proposal which seemed to deviate from the original semantics of the API.

**Comment by alculquicondor** [comment]
WDYT @Huang-Wei ?

**Comment by Huang-Wei** [comment]
@alculquicondor Sounds good to me.

Per constraint on large-scope topology (e.g., zone), I assume it will still be credited with the matching number on its sub topologies (e.g., node), right? (It's just we're using the newCount formula - by taking the maxSkew specified on its constraint into consideration.)

**Comment by ahg-g** [comment]
Note that this doesn't replace increasing the weight as described in the parent issue. I think the issue title needs updating.

**Comment by Huang-Wei** [comment]
@ahg-g Understood. Default weight is tracked in another issue. This one talks about Scoring.

**Comment by ahg-g** [comment]
Right, just wanted to explicitly mention that to avoid confusion since this issue started in the context of increasing the default weight :)

**Comment by alculquicondor** [comment]
@ahg-g Could you rename that one and clarify that it depends on this issue being resolved first?

**Comment by ahg-g** [comment]
@alculquicondor can you clarify what that issue is dependent on this one? aren't we going to increase the weight regardless?

**Comment by alculquicondor** [comment]
I was referring to #88174.
But you are right, it doesn't depend on this. kubernetes/enhancements#1258 does
