### ISSUE TITLE
Container cpuset lost, apparently due to race between PostStopContainer() and new container creation

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#90303]
**What happened**:
A container which had exclusive CPUs assigned to it (and an entry in /var/lib/kubelet/cpu_manager_state specifying those CPUs) was killed.  When it came back, it was using the default cpuset, and its entry in /var/lib/kubelet/cpu_manager_state was gone.

**What you expected to happen**:
It should have been given exclusive CPUs.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod/container with "guaranteed" QoS.  Determine the exclusive CPUs allocated to the container.  From the host, kill pid1 within the container.  ("kill -9" works.)  The container will restart within the existing pod, but it will be allocated cpus from the default cpuset (which will now include the CPUs that had been exclusively allocated to the container earlier).

**Anything else we need to know?**:

I added some instrumentation to kubelet.  What seems to be happening is this:

1) The container is killed (or dies).  Kubelet then immediately creates a new container and calls PolicyStatic.Allocate() to allocate exclusive CPUs for it.  This updates the entry in /var/lib/kubelet/cpu_manager_state (and the in-memory cache) which is mapped by podUID and container name, such that it contains the cpuset for the new container.

2) The InternalContainerLifecycle.PostStopContainer() code runs, which calls i.cpuManager.RemoveContainer(containerID).  This uses the containerID of the exited container to look up the podUID/container-name tuple, then deletes the cpuset entry from  /var/lib/kubelet/cpu_manager_state (and the in-memory cache).  But the entry that was deleted was actually the one for the *new* container.

3) Kubelet calls the CPU manager's AddContainer() function, which calls m.state.GetCPUSetOrDefault(string(p.UID), c.Name) to get the cpuset based on the podUID and container name of the new container.  The cpuset entry was erroneously deleted, so this returns the default cpuset, and the container which *should* have gotten exclusive CPUs ends up running on the default cpuset.

An solution suggested by @klueska is to delay calling cpuManager.RemoveContainer() until the whole pod is deleted.  This would preserve the CPU allocations.

An alternate solution also suggested by @klueska is to avoid calling cpuManager.RemoveContainer() from the container lifecycle code, but instead call removeStaleState() in the CpuManager.Allocate() function.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.1
- Cloud provider or hardware configuration:   x86, SMP
- OS (e.g: `cat /etc/os-release`):  CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1062.1.2.rt56.1025.el7

**Comment by tedyu** [comment]
I wonder if the RemoveContainer() in PostStopContainer can be dropped:
```
 func (i *internalContainerLifecycleImpl) PostStopContainer(containerID string) error {
        if i.cpuManager != nil {
-               err := i.cpuManager.RemoveContainer(containerID)
```
since RemoveContainer() is also called in PreStopContainer

**Comment by tedyu** [comment]
Considering the following change based on discussion over Slack with @klueska 
```
diff --git a/pkg/kubelet/cm/cpumanager/cpu_manager.go b/pkg/kubelet/cm/cpumanager/cpu_manager.go
index 9d52a09b9e1..75013b932ab 100644
--- a/pkg/kubelet/cm/cpumanager/cpu_manager.go
+++ b/pkg/kubelet/cm/cpumanager/cpu_manager.go
@@ -216,6 +216,7 @@ func (m *manager) Allocate(p *v1.Pod, c *v1.Container) error {
        defer m.Unlock()

        // Call down into the policy to assign this container CPUs if required.
+       m.removeStaleState()
        err := m.policy.Allocate(m.state, p, c)
        if err != nil {
                klog.Errorf("[cpumanager] Allocate error: %v", err)
diff --git a/pkg/kubelet/cm/internal_container_lifecycle.go b/pkg/kubelet/cm/internal_container_lifecycle.go
index 9e243430269..690718e4e68 100644
--- a/pkg/kubelet/cm/internal_container_lifecycle.go
+++ b/pkg/kubelet/cm/internal_container_lifecycle.go
@@ -54,19 +54,10 @@ func (i *internalContainerLifecycleImpl) PreStartContainer(pod *v1.Pod, containe
 }

 func (i *internalContainerLifecycleImpl) PreStopContainer(containerID string) error {
-       if i.cpuManager != nil {
-               return i.cpuManager.RemoveContainer(containerID)
-       }
        return nil
 }

 func (i *internalContainerLifecycleImpl) PostStopContainer(containerID string) error {
-       if i.cpuManager != nil {
-               err := i.cpuManager.RemoveContainer(containerID)
-               if err != nil {
-                       return err
-               }
-       }
        if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.TopologyManager) {
                err := i.topologyManager.RemoveContainer(containerID)
                if err != nil {
```

**Comment by harper1011** [comment]
@cbf123 
Sorry that bother you via this close issue, but I was tracing back to this issue via the PR.
As per your statement above, if I understand correctly, this problem only happened when the container inside Pod got killed.
but an simple Pod restarted (e.g. delete/re-create via kubectl delete pod command) should not trigger the problem, right?
Or any container(inside Pod) or Pod restart with guaranteed Qos will trigger this issue?
