### ISSUE TITLE
Build position independent executables

### ISSUE THREAD

**Issue by johanfleury** [kubernetes/kubernetes#90311]
## What would you like to be added:

Currently `kubelet` is dynamically linked but is not built as a position independent executable. It would be great if it could be built with Go’s `-buildmode=pie` flag to enable ASLR.

## Why is this needed:

I’m not a security expert, and I’m not familiar with those concepts, but it seems that ASLR is a pretty common (and recommended) security mechanism.

If I understand correctly, statically linked binaries (e.g. all the Kubernetes binaries except `kubelet`) do not require/support PIE so this would only apply to `kubelet`.

## Related issues/PR:

There was an attempt at using Go’s `-buildmode=pie` in #57225 but it seems that it was abandoned due to an incompatibility issue with Windows.

**Comment by saschagrunert** [comment]
cc @dims

**Comment by RobertKielty** [comment]
ASLR stands for Address Space Layout Randomization 
ref: https://en.wikipedia.org/wiki/Address_space_layout_randomization

**Comment by neolit123** [comment]
> There was an attempt at using Go’s -buildmode=pie in #57225 but it seems that it was abandoned due to an incompatibility issue with Windows.

conditionally building only Linux binaries in PIE for ASLR seems acceptable.
the problem is k8s is using a bash library for building which is not very flexible.

**Comment by saschagrunert** [comment]
I know at least some distributions which build go binaries per default with `buildmode=pie`. @neolit123  do you see any reason to not turn it on for Linux per default?

**Comment by neolit123** [comment]
> @neolit123 do you see any reason to not turn it on for Linux per default?

i think it should be turned on. my comment was that our build infra is a bit entangled at places.

/priority backlog
the `help-wanted` label seems appropriate.

**Comment by abhay-krishna** [comment]
I will work on this issue.

**Comment by BenTheElder** [comment]
there are outstanding questions about this https://github.com/kubernetes/kubernetes/pull/94448#issuecomment-721100759
@kubernetes/sig-security PTAL, I can lend some pointers to the build but I'd like more input on if this is desirable / worthwhile.

Some notes:
- https://groups.google.com/g/golang-nuts/c/Jd9tlNc6jUE
- buildmode=pie does not seem to be supported for all platforms even on linux, which seems problematic given that we compile for many platforms.

Custom builds can of course set this without the Kubernetes project choosing to do so, see `GOFLAGS`.

**Comment by tabbysable** [comment]
IMO, there's value in building as PIE on the platforms where that is possible, but this is a low priority / nice-to-have. [A recently released paper](https://arxiv.org/pdf/2003.05503.pdf) shows one way that building a PIE to enable ASLR can make attacks harder even though Go is memory-safe. It could also be a mitigation against a hypothetical memory-unsafety bug in the Go runtime.

**Comment by rficcaglia** [comment]
not sure if it moves the discussion forward but ASLR is one mechanism to address NIST 800-53 control requirements for memory integrity/protection (ie SI-16). CIS mapped this in one of their [docs](https://www.cisecurity.org/wp-content/uploads/2019/12/CIS-Controls-and-Sub-Controls-Mapping-to-NIST-Special-Publication-800-53-Rev-4-Low-Final-v1.1.xlsx). Note that is an older mapping and rev 5 is coming soon which keep this in as a requirement.

**Comment by altenx** [comment]
ROP mitigation is probably the most valuable aspect of this since Kubelet is always running in memory.  Its binary may be a rich source of gadgets, of which their offsets in the binary need to be well known to an attacker.

**Comment by xmudrii** [comment]
cc @saschagrunert to take a look

**Comment by saschagrunert** [comment]
Started to follow-up on this in https://github.com/kubernetes/kubernetes/pull/102323
