### ISSUE TITLE
K8s initialisation pulls 2 different pause container

### ISSUE THREAD

**Issue by nqdrizzt** [kubernetes/kubernetes#90326]
**What happened**:
After installing k8s v1.18.2 in combination with containerd and initializing the environment, the local container registry contains 2 pause container in different versions

**What you expected to happen**:
There is just the latest pause container in the local registry

**How to reproduce it (as minimally and precisely as possible)**:
user@host:~$ sudo crictl images
IMAGE               TAG                 IMAGE ID            SIZE

user@host:~$ sudo kubeadm config images pull
W0420 12:51:30.043172   10467 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[config/images] Pulled k8s.gcr.io/kube-apiserver:v1.18.2
[config/images] Pulled k8s.gcr.io/kube-controller-manager:v1.18.2
[config/images] Pulled k8s.gcr.io/kube-scheduler:v1.18.2
[config/images] Pulled k8s.gcr.io/kube-proxy:v1.18.2
[config/images] Pulled k8s.gcr.io/pause:3.2
[config/images] Pulled k8s.gcr.io/etcd:3.4.3-0
[config/images] Pulled k8s.gcr.io/coredns:1.6.7

user@host:~$ sudo kubeadm init --pod-network-cidr="$DETOX_K8S_POD_NETWORK" --kubernetes-version=1.18.2
...
...
...
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

user@host:~$ sudo crictl images
IMAGE                                TAG                 IMAGE ID            SIZE
k8s.gcr.io/coredns                   1.6.7               67da37a9a360e       13.6MB
k8s.gcr.io/etcd                      3.4.3-0             303ce5db0e90d       101MB
k8s.gcr.io/kube-apiserver            v1.18.2             6ed75ad404bdd       51.1MB
k8s.gcr.io/kube-controller-manager   v1.18.2             ace0a8c17ba90       49.1MB
k8s.gcr.io/kube-proxy                v1.18.2             0d40868643c69       48.8MB
k8s.gcr.io/kube-scheduler            v1.18.2             a3099161e1375       34.1MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca19       317kB
k8s.gcr.io/pause                     3.2                 80d28bedfe5de       300kB

user@host:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-42jjz             1/1     Running   0          4m
kube-system   coredns-66bff467f8-dl2bc             1/1     Running   0          4m
kube-system   etcd-detox01-dm                      1/1     Running   0          4m9s
kube-system   kube-apiserver-detox01-dm            1/1     Running   0          4m8s
kube-system   kube-controller-manager-detox01-dm   1/1     Running   0          4m9s
kube-system   kube-proxy-82f6x                     1/1     Running   0          4m
kube-system   kube-scheduler-detox01-dm            1/1     Running   0          4m9s

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2-dirty", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"dirty", BuildDate:"2020-04-20T06:47:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: amd64

- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`): Linux  4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by neolit123** [comment]
> [config/images] Pulled k8s.gcr.io/pause:3.2

looks like kubeadm is pulling 3.2.
3.2 is now the default version for the 1.18 kubeadm and kubelet.

> After installing k8s v1.18.2 in combination with containerd and initializing the environment, the local container registry contains 2 pause container in different versions

are you passing 3.1 in the containerd config?

**Comment by BenTheElder** [comment]
if they're using containerd many versions have pause 3.1
with newer containerd pause 3.2 is the default

cri-o is probably similar.

**Comment by nqdrizzt** [comment]
there is no sign of a pause:3.1 container configured anywhere:

detox@detox01-dm:~$ sudo systemctl status containerd
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-04-23 12:21:22 UTC; 3 days ago
     Docs: https://containerd.io
 Main PID: 439 (containerd)
    Tasks: 211
   Memory: 1.5G
   CGroup: /system.slice/containerd.service
           ├─ 439 /usr/local/bin/containerd
           ├─8309 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 9bfedd765d03268be5d9b68fc8be27419d0cf2c1e349a78d3a902ccb8f27595f -address /run/containerd/containerd.sock
           ├─8310 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 61a98f9ab87082e779de37a9387fc2d7b8c0be8e90f9254b2f6278016caa4e28 -address /run/containerd/containerd.sock
           ├─8311 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 099edd5bbfea23cb5a737d4775bd3cb907f90d2693fc0cb14a8ccc5b80f25d38 -address /run/containerd/containerd.sock
           ├─8312 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 2e8e98843d55de4a747bd4caca7e97cc05609038a9733fdb232538e2a401ff78 -address /run/containerd/containerd.sock
           ├─8382 /pause
           ├─8389 /pause
           ├─8390 /pause
           ├─8400 /pause
           ├─8448 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 4f2678713fde6d9a14b9e8c210f87b7739bb0064251bb48196fe9f20ce7520f8 -address /run/containerd/containerd.sock
           ├─8468 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id a0a64c8c0d17be8e691e9409895088f06c0c34b633be4302d448ad838d1783c4 -address /run/containerd/containerd.sock
           ├─8470 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 64f2719e8128804b6168fdde5585e9d3848e43ff8f2356784135a16ab1665013 -address /run/containerd/containerd.sock
           ├─8528 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 655609257a927716daf5558e19e5e3a8ce1600c904f5d5c2eff93c9a8e778181 -address /run/containerd/containerd.sock
           ├─8548 kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/et
           ├─8554 kube-scheduler --authentication-kubeconfig=/etc/kubernetes/scheduler.conf --authorization-kubeconfig=/etc/kubernetes/scheduler.conf --bind-address=127.0.0.1 --kubeconfig=/etc/kubernetes/scheduler.conf --leader-elect=true
           ├─8560 etcd --advertise-client-urls=https://192.168.222.202:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://192.168.222.202:2380 --initial-cluster
           ├─8566 kube-apiserver --advertise-address=192.168.222.202 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --e
           ├─8801 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 6837f2fdf296d9717f82e2cf79a5ca6d27b0bedcfebc68bc69d3a37560a82861 -address /run/containerd/containerd.sock
           ├─8823 /pause
           ├─8842 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 2a0c9718d439d5f8016b4fc01111fe30b01d2286a5e8d7cf3c5f0ccef2e13252 -address /run/containerd/containerd.sock
           ├─8864 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=detox01-dm
           ├─9002 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 344f0e2b3ee7300a924f20d7a1a5a279ff41839689f042160b854e88ff1214c7 -address /run/containerd/containerd.sock
           ├─9023 /pause
           ├─9110 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id ad708565e7721039fd8f11bdbe787e5e4a050ce182ec9394939bf6d5cb659dec -address /run/containerd/containerd.sock
           ├─9132 /opt/bin/flanneld --ip-masq --kube-subnet-mgr
           ├─9438 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id e3c40af33434fac71288dc3ce6c00f02f0b63a47aa46dadd65433e927a43ccb3 -address /run/containerd/containerd.sock
           ├─9440 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id 6f4c82ebb67e5044333242d1464d623ef84216928acec6a1d2547b153fa40b7a -address /run/containerd/containerd.sock
           ├─9478 /pause
           ├─9484 /pause
           ├─9526 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id c8318f6d231bc565057dddf3c058e06b7ccc0f37a96b643cccf4f1b9d8b92427 -address /run/containerd/containerd.sock
           ├─9552 /usr/local/bin/containerd-shim-runc-v1 -namespace k8s.io -id f4a676b575383e47b3431a2e7e283f1d269e7bc97d36a39f426454514a22976c -address /run/containerd/containerd.sock
           ├─9573 /coredns -conf /etc/coredns/Corefile
           └─9579 /coredns -conf /etc/coredns/Corefile


detox@detox01-dm:~$ cat /etc/containerd/config.toml
version = 2

[debug]
  level = "warn"



The "kubeadmin init" command somehow pulls that container.
If i execute "kubeadm config images pull" before initialize the cluster,  only the pause:3.2 container gets pulled

**Comment by BenTheElder** [comment]
those pause processes are probably 3.1

what containerd version? until recently containerd used 3.1 as the pod sandbox image.

kubeadm OTOH assumes 3.2 for kubernetes 1.18+ and dockershim will use this.

you can either avoid the kubeadm pull step (sadly currently requires skipping preflight checks) or configure containerd to use the 3.2 image

```toml
[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "k8s.gcr.io/pause:3.2"
```

**Comment by nqdrizzt** [comment]
detox@detox01-dm:~$ apt list containerd
Listing... Done
containerd/stable,now 1.3.3 all [installed]

Actually the current installation works a bit different for me: As I am locaten in a separated on premise network with no internet access available, we are delivering a tarball which contains all the basic container. This tarball gets import into the local repository before initializing k8s itself, so that there is no need to pull anything from upstream.
In my opinion the kube admin init command executes the "config images pull" image pull, which looks for pause 3.2 in the local repository. then the preflight checks run and somehow the 3.1 pause container is also necessary. 
I give the containerd config a try and specify the sandbox image there before initializing k8s. lets see if this results in only one pause container.

**Comment by BenTheElder** [comment]
This is more or less how sigs.k8s.io/kind works, we ran into the same issue. https://github.com/kubernetes-sigs/kind/issues/1471

**Comment by BenTheElder** [comment]
contained 1.3.3 uses pause:3.1 by default. 1.3.4 uses 3.2

**Comment by nqdrizzt** [comment]
after pinning containerd v1.3.3 to use pause version v3.2 it looks like the local repository only hast the pause:3.2 container stored:

detox@detox01-dm:~$ cat /etc/containerd/config.toml
version = 2

[debug]
  level = "warn"

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = "k8s.gcr.io/pause:3.2"

detox@detox01-dm:~$ sudo crictl images
IMAGE                                TAG                 IMAGE ID            SIZE
k8s.gcr.io/coredns                   1.6.7               7ef3db5de0159       14.8MB
k8s.gcr.io/etcd                      3.4.3-0             1168581beb1ac       103MB
k8s.gcr.io/kube-apiserver            v1.18.2             aab33e1fae6b0       74.2MB
k8s.gcr.io/kube-controller-manager   v1.18.2             384ae2880c928       71.3MB
k8s.gcr.io/kube-proxy                v1.18.2             b2f726161785e       57.9MB
k8s.gcr.io/kube-scheduler            v1.18.2             d403de1833d43       44.3MB
k8s.gcr.io/pause                     3.2                 80d28bedfe5de       300kB
quay.io/coreos/flannel               v0.11.0-amd64       abc11f4465332       42.7MB

**Comment by neolit123** [comment]
thank you for confirming.
if you wish to improve the kubeadm documentation regarding matching the kubeadm / containerd "pause" please log a ticket in k/kubeadm, but other than documentation there isn't much else we can do on the kubeadm side for the time being.

/close

**Comment by nqdrizzt** [comment]
/reopen

Sadly this issue is not resolved. I did further testings withe containerd v1.3.4
Even with containerd using the latest version it tries to pull the pause:3.1 container, if the sandbox image is not specified explicitly in the containerd.conf

detox@detox01-dm:~$ sudo journalctl -xeu kubelet
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.970976    1334 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971079    1334 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kube-apiserver-detox01-dm_kube-system(10161a66a697de753304685256272214)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971124    1334 kuberuntime_manager.go:727] createPodSandbox for pod "kube-apiserver-detox01-dm_kube-system(10161a66a697de753304685256272214)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971241    1334 pod_workers.go:191] Error syncing pod 10161a66a697de753304685256272214 ("kube-apiserver-detox01-dm_kube-system(10161a66a697de753304685256272214)"), skipping: failed to "CreatePodSandbox" for "kube-apiserver-detox01-dm_kube-system(10161a66a697de753304685256272214)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-apiserver-detox01-dm_kube-system(10161a66a697de753304685256272214)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address"
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971451    1334 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971552    1334 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "etcd-detox01-dm_kube-system(8be3e1cec19c49249b06a7e31f0a1d8a)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971610    1334 kuberuntime_manager.go:727] createPodSandbox for pod "etcd-detox01-dm_kube-system(8be3e1cec19c49249b06a7e31f0a1d8a)" failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address
Apr 28 06:10:56 detox01-dm kubelet[1334]: E0428 06:10:56.971778    1334 pod_workers.go:191] Error syncing pod 8be3e1cec19c49249b06a7e31f0a1d8a ("etcd-detox01-dm_kube-system(8be3e1cec19c49249b06a7e31f0a1d8a)"), skipping: failed to "CreatePodSandbox" for "etcd-detox01-dm_kube-system(8be3e1cec19c49249b06a7e31f0a1d8a)" with CreatePodSandboxError: "CreatePodSandbox for pod \"etcd-detox01-dm_kube-system(8be3e1cec19c49249b06a7e31f0a1d8a)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": dial tcp: lookup k8s.gcr.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address"

**Comment by BenTheElder** [comment]
@nqdrizzt this was closed because it should be tracked in github.com/kubernetes/kubeadm's issue tracker (translating https://github.com/kubernetes/kubernetes/issues/90326#issuecomment-620065079)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubeadm/issues/2020

**Comment by BenTheElder** [comment]
implementation of the podsandbox is up to the container runtime, except when you use "dockershim" mode (which is in tree for now), either kubeadm (https://github.com/kubernetes/kubeadm/issues/2020) or containerd (the sandbox_image config) will need to be configured to match the other.

containerd already supports this, and kubeadm has this issue tracking being able to specify the pause image https://github.com/kubernetes/kubeadm/issues/2020

**Comment by BenTheElder** [comment]
your options are:
- discuss in / help implement https://github.com/kubernetes/kubeadm/issues/2020
- configure containerd pod_sandbox to match `kubeadm config images list | grep pause`
- `kubeadm init --skip-phases=preflight` (skip the preflight checks, which includes image pulling, unfortunately this cannot currently be done more granularly, see also https://github.com/kubernetes/kubeadm/issues/524)


If you'd like kubeadm to change behavior, please see https://github.com/kubernetes/kubeadm/issues/2020 or file a new issue against kubeadm https://github.com/kubernetes/kubeadm/issues/new
/close

**Comment by nqdrizzt** [comment]
Thanks for clarifying

**Comment by BenTheElder** [comment]
FWIW I think this behavior is clearly suboptimal, discussing in the kubeadm repo.

**Comment by nqdrizzt** [comment]
What's a bis disturbing me is the case, that although I am using containerd 1.3.4 now (which should use pause 3.2 by default ) something still tries to pull 3.1 and I'm not sure if it is kubeadm, because they are already pulling the 3.2 image
> 
> 
> contained 1.3.3 uses pause:3.1 by default. 1.3.4 uses 3.2

**Comment by BenTheElder** [comment]
these values are off the top of my head, you can confirm the default from
`containerd config dump` IIRC

**Comment by nqdrizzt** [comment]
ok thx, well it seems even v1.3.4 is still using pause:3.1 as default

`  [plugins."io.containerd.grpc.v1.cri"]
...
    sandbox_image = "k8s.gcr.io/pause:3.1"`

**Comment by BenTheElder** [comment]
https://github.com/containerd/cri/pull/1399 is merged, i'm not sure which
versions it landed in, that repo gets pulled into containerd. I could've
sworn 1.3.4 pulled in that change.
