### ISSUE TITLE
Windows: subpath mount changes on a container restart if the environment variable changes

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#90336]
**What happened**:

The test ``[k8s.io] Variable Expansion should not change the subpath mount on a container restart if the environment variable changes [sig-storage][Slow] [Conformance]`` fails on Windows. On container restart, the subpath mount changes.

The test does the following:

- spawns a Pod with an EmptyDir volume mounted in 2 locations: ``/volume_mount`` and ``subpath_mount`` (the 2nd one has a subpath expr set, taken from ``metadata.annotations['mysubpath']``)
- the pod has a liveness probe that checks for the file ``/subpath_mount/test.log``
- the test updates ``metadata.annotations['mysubpath']`` to a different value.
- the test then deletes the file ``/subpath_mount/test.log`` and then waits for the container restart because of the liveness probe.
- the test recreates the ``/subpath_mount/test.log``
- the test asserts that ``/volume_mount/foo/test.log`` exists, and that ``/volume_mount/newsubpath/test.log`` does not.

The test fails on the assertions on Windows.

**What you expected to happen**:

The container volume subpath should not change on container restart.

**How to reproduce it (as minimally and precisely as possible)**:

    kubectl create -f liveness.yaml

    # check that test.log exists.
    kubectl exec -n subpath-test-ns subpath-test -- ls /subpath_mount

    # create /volume_mount/bar/test.log and /volume_mount/bar/tender
    kubectl exec -n subpath-test-ns subpath-test -- /bin/bash -c "mkdir -p /volume_mount/bar && touch /volume_mount/bar/test.log && touch /volume_mount/bar/tender"

    # update the pod volume subpath.
    kubectl patch pod -n subpath-test-ns subpath-test -p '{"metadata":{"annotations":{"mysubpath":"bar"}}}'

    # trigger the restart by deleting the file checked by the liveness probe.
    kubectl exec -n subpath-test-ns subpath-test -- rm /subpath_mount/test.log

    # check the /subpath_mount contents. It shouldn't contain test.log or tender.
    kubectl exec -n subpath-test-ns subpath-test -- ls /subpath_mount

liveness.yaml:

    apiVersion: v1
    items:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: subpath-test-ns
    - apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          kubernetes.io/psp: e2e-test-privileged-psp
          mysubpath: foo
        name: subpath-test
        namespace: subpath-test-ns
      spec:
        containers:
        - command:
          - /bin/sh
          - -ec
          - 'sleep 100000'
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['mysubpath']
          image: claudiubelu/busybox:1.29
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - 'cat /subpath_mount/test.log'
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          name: dapi-container
          volumeMounts:
          - mountPath: /subpath_mount
            name: workdir1
            subPathExpr: $(POD_NAME)
          - mountPath: /volume_mount
            name: workdir1
        initContainers:
        - command:
          - sh
          - -c
          - mkdir -p /volume_mount/foo; touch /volume_mount/foo/test.log
          image: claudiubelu/busybox:1.29
          imagePullPolicy: Always
          name: init-volume-50ab29f4
          volumeMounts:
          - mountPath: /subpath_mount
            name: workdir1
          - mountPath: /volume_mount
            name: workdir1
        volumes:
        - emptyDir: {}
          name: workdir1
    kind: List

**Anything else we need to know?**:

/sig windows

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by craiglpeters** [comment]
Due to the discussion in https://github.com/kubernetes/kubernetes/pull/89629 this is no longer a priority
