### ISSUE TITLE
getPodContainerStatuses should handle exited container

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#90346]
**What happened**:

For the following container:
```
Apr 17 03:45:04.403114 ip-10-0-167-215 hyperkube[1541]: E0417 03:45:04.402994    1541 kuberuntime_manager.go:935] getPodContainerStatuses for pod "8a34d0bf-805c-11ea-b463-0a58ac102063_ci(e70c5840-538d-4509-afdb-36140fee0066)" failed: rpc error: code = Unknown desc = container with ID starting with e6615f8ceb59833d91012e6f16816cdb2ee69b7f5dd7dcf1f46a3e07eb86fb43 not found: ID does not exist
```
The corresponding container state was Terminated :
```
Apr 17 03:45:09.635953 ip-10-0-167-215 hyperkube[1541]: +                 InitContainerStatuses: []v1.ContainerStatus{
Apr 17 03:45:09.635953 ip-10-0-167-215 hyperkube[1541]: +                         {
Apr 17 03:45:09.635953 ip-10-0-167-215 hyperkube[1541]: +                                 Name: "initupload",
Apr 17 03:45:09.635953 ip-10-0-167-215 hyperkube[1541]: +                                 State: v1.ContainerState{
Apr 17 03:45:09.635953 ip-10-0-167-215 hyperkube[1541]: +                                         Terminated: s"&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2020-04-17 03:44:58 +0000 UTC,FinishedAt:2020-04-17 03:44:59 +0000 UTC,ContainerID:cri-o://e6615f8ceb59833d91012e6f16816cdb2ee69b7f5dd7dcf1f46a3e07eb86fb43,}",
Apr 17 03:45:09.635953 ip-10-0-167-215 hyperkube[1541]: +                                 },
```
Inside kubeGenericRuntimeManager#getPodContainerStatuses, there was no check on the c.State (container state) when we receive the result of runtimeService.ListContainers().
When runtimeService.ContainerStatus() returns container not found error, the loop over containers exits.

**What you expected to happen**:
We can fill in ContainerStatus for containers in ContainerState_CONTAINER_EXITED state.

Examining the callers, we can notice that only Kubelet#getFailedContainers pays attention to the exit code of the containers. Filling in ContainerStatus can be done for other callers of getPodContainerStatuses()

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
[get-container-status.txt](https://github.com/kubernetes/kubernetes/files/4518082/get-container-status.txt)

**Comment by rphillips** [comment]
This patch will fix the attempt number if the runtime returns an error to the kubelet. I believe we need Mrunal's [KEP](https://github.com/kubernetes/enhancements/pull/1654) adding more granular errors, so the Kubelet can select on the type of error to inject the container status.

**Comment by tedyu** [comment]
Pending granular errors to be added.
