### ISSUE TITLE
I set a static pod to critical mode by priority, why its oom_score_adj is still 1000

### ISSUE THREAD

**Issue by liruishan** [kubernetes/kubernetes#90393]
I set a static pod to critical mode by priority, why its oom_score_adj is still 1000, I checked through the code should be -998, the code is as follows:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/qos/policy.go
func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapacity int64) int {
	if types.IsCriticalPod(pod) {
		// Critical pods should be the last to get killed.
		return guaranteedOOMScoreAdj
	}

**Comment by liggitt** [comment]
what version are you running? how did you set the priority?

**Comment by liruishan** [comment]
> what version are you running? how did you set the priority?
version:1.15.6
pod priority config is as follows:
spec.containers.priorityClassName:system-cluster-cirtical

I tried version 1.16 and the test results were as expected, but I don’t understand why version 1.15 is wrong
