### ISSUE TITLE
Make the "GetResourceRequest" logic in scheduler pkg more clean

### ISSUE THREAD

**Issue by fengzixu** [kubernetes/kubernetes#90402]
**> This issue is for tracking some problems I found and I plan to fix.**

**Why is this needed**:
During I fixed the bug [**bugfix: initcontainer is also taken into account when calculating resource requests**](https://github.com/kubernetes/kubernetes/pull/89222), I found some issues of calculating resource request logic existed in scheduler package.  

1. **Duplication**: Actually, in Kubernetes code base, only kube-scheduler gives the default resource request to every container for calculating score purpose. So we have our own logic. But there is a [unified function](https://github.com/kubernetes/kubernetes/blob/5713c22eecff4610026643fbd3d37c33a43c168d/pkg/api/v1/resource/helpers.go#L133) which also can be used to get the resource request of pod  in `/pkg/api/v1/resource` package. 

2. **Default resource request value**: In the [current implementation](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/noderesources/resource_allocation.go#L118), we check every container of one pod if it specifies the explicit resource request. If there is no explicit value, we will give a default resource request value to the **container**. Actually, we can change the default value of per container to per pod. It likes 
```go
resourceRequest := max(sum(pod.Spec.Containers), max(pod.Spec.InitContainers))
if  resourceRequest== 0 {
              resourceRequest = defaultResourceRequestValue
}
```
3. **Explicit zero resource request**:  In this [unit test](https://github.com/kubernetes/kubernetes/blob/3538320d74f98fc0972206d20cd3d76186d88aa9/pkg/scheduler/framework/plugins/noderesources/least_allocated_test.go#L100), it specifies the explicit zero resource request. It looks like this test doesn't want to get the default resource request. It should be considered carefully ****If we should give the default resource request value** for the pod which specifies the explicit zero value**. [Context](https://github.com/kubernetes/kubernetes/pull/89222#discussion_r411617331)

4. **IsScalarResourceName**: In our [current of calculating non zero resource request logic](https://github.com/kubernetes/kubernetes/blob/b850b5ce2e7d282abae01a26be4d14d56d71bfad/pkg/scheduler/util/non_zero.go#L76), we consider if the resource belongs to the **scalar resource**. Not sure if it is valuable to remain. Because the [GetResourceRequest](https://github.com/kubernetes/kubernetes/blob/5713c22eecff4610026643fbd3d37c33a43c168d/pkg/api/v1/resource/helpers.go#L133) of `/pkg/api/v1/resource` package doesn't consider it.

5. **Lack of correct test cases**: When I fixing the bug I mentioned, I found it is hard to add the test logic about initContainer in [TestNodeInfoRemovePod](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/types_test.go#L814). Because it uses the [MakeBasePod](https://github.com/kubernetes/kubernetes/blob/3e2ae631b4caef5f823a5e121f860c653da32ff5/pkg/scheduler/framework/v1alpha1/types_test.go#L247) to construct the pod test cases. The current logic of  [MakeBasePod](https://github.com/kubernetes/kubernetes/blob/3e2ae631b4caef5f823a5e121f860c653da32ff5/pkg/scheduler/framework/v1alpha1/types_test.go#L247) is not good for me. We should refactor it and make the test for "GetResourceRequest" logic more complete.

In my [bugfix PR](https://github.com/kubernetes/kubernetes/pull/89222), for easier to cherry-pick to the older version, I just focus on fixing the bug based on the current implementation.  So I think we need to do the improvement in following PRs.

**Comment by fengzixu** [comment]
@Huang-Wei @ahg-g @alculquicondor We can discuss the next work on this issue.

**Comment by alculquicondor** [comment]
The overall idea sounds good to me and I think we can discuss some details in a PR.

Non-zero values are used to calculate scores (not to perform filters). A couple of thoughts:

1. We have some slack in changing those calculations and I'm ok with making the values per-pod. The effect will be that some nodes that used to get a zero score now get a small value.
1. Since the code is not used anywhere else, we can have this code in the noderesources  (instead of utils package), with an appropriate comment mentioning the difference from the shared calculations.

The calculations without non-zero defaults can and should be shared across k8s code.

> IsScalarResourceName: In our current of calculating non zero resource request logic, we consider if the resource belongs to the scalar resource. Not sure if it is valuable to remain. Because the GetResourceRequest of /pkg/api/v1/resource package doesn't consider it.

This question requires discussion with sig-node folks and dig in the history of the implementation of IsScalarResourceName to understand the initial motivation for it.

**Comment by alculquicondor** [comment]
We could start unifying just the scheduler code in `pkg/scheduler/utils` or `pkg/scheduler/framework/plugins/helper` to initiate sig-scheduling discussions.

And we could leave the changes that affect kubelet for a followup PR.

**Comment by ahg-g** [comment]
How about we have the code in frameworkv1alpha1/types.go instead of noderesources since it will be used by nodeinfo?

Perhaps we can have a single function in types.go that calculates the total pod resources, and the function accepts a ```WithNonZero()```:

```GetPodResources(pod *v1.Pod, options ...PodResourcesOption) (requests *v1.ResourceList, limits *v1.ResourceList)```

The limits will be used by ```ResourceLimits``` plugin.

**Comment by alculquicondor** [comment]
> How about we have the code in frameworkv1alpha1/types.go instead of noderesources since it will be used by nodeinfo?

Then that code wouldn't be shared with kubelet.

**Comment by ahg-g** [comment]
How would nodeinfo be able to calculate pod resources if the function is placed in noderesources?

> Then that code wouldn't be shared with kubelet.
Why not? They do have a dependency on nodeinfo I think, and so the dependency on the framework isn't new.

**Comment by alculquicondor** [comment]
> How would nodeinfo be able to calculate pod resources if the function is placed in noderesources?

That suggestion was limited to calculations that include non-zero

>> Then that code wouldn't be shared with kubelet.

> Why not? They do have a dependency on nodeinfo I think, and so the dependency on the framework isn't new.

True

**Comment by ahg-g** [comment]
> That suggestion was limited to calculations that include non-zero

ok, I think we can do better by unifying all uses under a single function with an option for non-zero.

**Comment by fengzixu** [comment]
After I looked comments above, I think I can confirm some points as below

#### Confirmed

1. Unify all calculating resource request logic of the scheduler package to the single place. We prefer to put this logic in `frameworkv1alpha1/types.go` file for better sharing
2. Change the "assign default resource request logic" from per container to per pod
3. Use the "Variadic Argrument" mechanism in Golang to refactor the `GetResourceRequest` function, so convenient to support all using cases in scheduler package, such as zero and non-zero resource request
4. Remain the `IsScalarResourceName` logic first, need to discuss with sig-node .

Before I start to implement, I think there still is one point we need to confirm

#### Need to Confirm

1. **Explicit zero resource request**: In this unit test, it specifies the explicit zero resource request. It looks like this test doesn't want to get the default resource request. It should be considered carefully If we should give the default resource request value for the pod which specifies the explicit zero value. Context

@Huang-Wei @alculquicondor @ahg-g

**Comment by alculquicondor** [comment]
> Explicit zero resource reques
My take is that it should be respected and considered 0.

I think you can start a PR with the points you have. And a follow up would be to make kubelet use the code in framework so that we can remove `pkg/api/v1/resource`

**Comment by fengzixu** [comment]
> > Explicit zero resource reques
> > My take is that it should be respected and considered 0.
> 
> I think you can start a PR with the points you have. And a follow up would be to make kubelet use the code in framework so that we can remove `pkg/api/v1/resource`

Got your point. Let me submit my PR first.

**Comment by fengzixu** [comment]
Start to implement. Sorry about leave this issue for a long time.

**Comment by alculquicondor** [comment]
@fengzixu do you still want to take this?

We should move the logic to the staging repository #92507

**Comment by alculquicondor** [comment]
@fengzixu can you still work on this?
In particular, we should unify the logic in plugins/noderesources/fit.go and framework/types.go

**Comment by fengzixu** [comment]
> @fengzixu can you still work on this?
> In particular, we should unify the logic in plugins/noderesources/fit.go and framework/types.go

@alculquicondor Hi. Sorry for reply too late. Actually, I have did some work for this issue, but not submit it yet.

**Comment by alculquicondor** [comment]
Might be worth moving the helpers to https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-helpers/scheduling/corev1

cc @smarterclayton

**Comment by pravarag** [comment]
@alculquicondor can I work on this issue ?

**Comment by alculquicondor** [comment]
yes

**Comment by pravarag** [comment]
Hi @alculquicondor, while going through the comments mentioned above I've understand few things:
1. As part of this change we want to collect all the `calculating resource request logic` of scheduler package in one place. And as per this comment: https://github.com/kubernetes/kubernetes/issues/90402#issuecomment-619042451 it's to be collected within `frameworkv1alpha1/types.go` .
2. We want to change the `assign default resource request logic` from per container to pod.
3. Using `Variadic Argument` mechanism of Go lang to refactor `GetResourceRequest` function which will support use cases like zero or non-zero resource requests.
4. Implementation of `IsScalarResourceName` logic - it's mentioned as a separate discussion is required with `sig/node` in comment: https://github.com/kubernetes/kubernetes/issues/90402#issuecomment-619042451
5. And, finally `Explicit zero resource request` which is mentioned to be respected and considered as 0.

Kindly confirm above points and are there any points from above which may required further discussions? Also, is there any specific order of priority for the implementation of above changes, kindly let me know.

**Comment by alculquicondor** [comment]
Re 1: Since that comment was posted, a better location could be https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-helpers/scheduling/corev1, but this is open to deliberation. It's better that you start exploring both possibilities and access the impact in the code.

Re 2, 3: Let's start just with the functions that don't have a non-zero default, as those are the ones that are shared across components.

Re 4: leave it

Re 5: We can discuss that in a code review

**Comment by pravarag** [comment]
@alculquicondor I've created a draft PR with in-progress items and further discussions. I'll continue to collect more `resourceRequest` logic (currently I've added only two) and will seek your guidance as well for the same.

**Comment by pravarag** [comment]
@alculquicondor apologies for any delays in finishing the above draft PR as I'm currently recovering from Covid-19. I'll get back to it once things settle on my end.

**Comment by pravarag** [comment]
I've started working on this issue again, hopefully will finish it soon :)

**Comment by pravarag** [comment]
@alculquicondor @Huang-Wei I've some doubts w.r.t the changes as mentioned under review here: https://github.com/kubernetes/kubernetes/pull/101193/files#r614823080,
Is there a way I can remove the dependency of component helpers `kubernetes/pkg/scheduler` ?

**Comment by alculquicondor** [comment]
Perhaps the shared logic should be moved to component-helpers.

**Comment by alculquicondor** [comment]
/close
in favor of #106769
