### ISSUE TITLE
Azure credential provider does not authenticate to ACR in all clouds

### ISSUE THREAD

**Issue by DavidParks8** [kubernetes/kubernetes#90412]
**What happened**:
An aks-engine cluster with a user assigned managed service cluster identity fails to authenticate to azure container registries in private clouds when the proper (acrpull) azure role assignments are in place and when there are no image pull secrets.

**What you expected to happen**:
The cluster should be able to authenticate and pull from an ACR hosted in the same azure cloud without needing additional pull secrets when the cluster identity has the proper acrpull azure role assignment, no matter which azure cloud it is operating in.

**How to reproduce it (as minimally and precisely as possible)**:
Assume you have a private azure cloud where every url ends with "my.cloud". That would mean the ACR suffix would be `.azurecr.my.cloud`. Let's pretend you have an ACR at `test.azurecr.my.cloud` and you try to deploy a pod in your cluster referencing the image `test.azurecr.my.cloud/helloworld:latest`. This will fail to pull when you have no image pull secrets.

**Anything else we need to know?**:
The problem stems from the following lines where expected ACR suffix domains are hardcoded:
https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/azure/azure_credentials.go#L49-L50

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- Cloud provider or hardware configuration: Azure private
- OS: ubuntu 16.0.4
- Network plugin and version: Azure CNI

**Comment by DavidParks8** [comment]
It looks like we may be able to obtain the acr suffix from the azure environment:
https://github.com/Azure/go-autorest/blob/f29a2eccaa178b367df0405778cd85e0af7b4225/autorest/azure/environments.go#L71

**Comment by andyzhangx** [comment]
there is a security issue here:
if we support self defined ACR domain, e.g. `test.azurecr.my.cloud`, then service principal secret could be sent to that remote server. 
The reason why we use hardcoded domains is that we could always make sure the following 4 domains are owned by Azure:
https://github.com/kubernetes/kubernetes/blob/0c0984abdb17246b472e65f0fefee82637dd83e6/pkg/credentialprovider/azure/azure_credentials.go#L49-L50
