### ISSUE TITLE
spec.finalizers cannot be modified via a patch or update to a namespace resource

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubernetes/kubernetes#90438]
**What happened**:

I am trying to patch a namespace but i am unable to do so. On dry run it shows the correct output that is :

```
$ kubectl patch ns test -p '{"spec":{"finalizers": []}}' --type=merge --dry-run -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c24,c19
    openshift.io/sa.scc.supplemental-groups: 1000590000/10000
    openshift.io/sa.scc.uid-range: 1000590000/10000
  creationTimestamp: "2020-04-24T08:10:06Z"
  name: test
  resourceVersion: "17681080"
  selfLink: /api/v1/namespaces/test
  uid: 194b4b48-ce44-46ec-b8f4-f51989ea9b6b
spec:
  finalizers: []
status:
  phase: Active
```

But when i apply the patch:

```
$ kubectl patch ns test -p '{"spec":{"finalizers": []}}' --type=merge
namespace/test patched (no change)
```

Is patching somehow restricted on namespaces ?

**What you expected to happen**:

For the namespace to be patched

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl create ns test
kubectl patch ns test -p '{"spec":{"finalizers": []}}' --type=merge --dry-run -o yaml
kubectl patch ns test -p '{"spec":{"finalizers": []}}' --type=merge
kubectl get ns test  -o yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2

**Comment by liggitt** [comment]
`spec.finalizers` is only mutable via the `/finalizers` subresource

this is described obliquely in the [namespace design](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/namespaces.md#finalizers), but should be called out explicitly in the field documentation

**Comment by ahmedwaleedmalik** [comment]
Makes sense @liggitt  (y)

**Comment by RichardoC** [comment]
So, how can we mutate that field without using patch?

**Comment by hielfx** [comment]
@RichardoC I was able to remove the challenges with the `patch` command. E.g.:
```bash
kubeclt patch --namespace=my-namespace challenge challenge-name --patch='{"metadata":{"finalizers":null}}' --type=merge
```
In case you wanted to remove all challenges, you can do it like this:
```bash
kubeclt patch --namespace=my-namespace challenge $(kubectl get challenges --namespace=my-namespace | awk '{if (NR>1) {print $1}}') --patch='{"metadata":{"finalizers":null}}' --type=merge
```

Hope it helps.

**Comment by RichardoC** [comment]
> @RichardoC I was able to remove the challenges with the `patch` command. E.g.:
> 
> ```shell
> kubeclt patch --namespace=my-namespace challenge challenge-name --patch='{"metadata":{"finalizers":null}}' --type=merge
> ```
> 
> In case you wanted to remove all challenges, you can do it like this:
> 
> ```shell
> kubeclt patch --namespace=my-namespace challenge $(kubectl get challenges --namespace=my-namespace | awk '{if (NR>1) {print $1}}') --patch='{"metadata":{"finalizers":null}}' --type=merge
> ```
> 
> Hope it helps.

Which version are you using? I can't find a reference to "challenges" in the [v1.23 API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/) or kubectl
`$ kubectl api-resources | grep challenge
$`

Thanks!

**Comment by dan-tw** [comment]
> Which version are you using? I can't find a reference to "challenges" in the [v1.23 API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/) or kubectl `$ kubectl api-resources | grep challenge $`

`challenge` and `challenge-name` in the solution provided by @hielfx are just the resource and resource name.

E.g. 
```
kubectl patch ingress my-ingress -p '{"metadata":{"finalizers":null}}' -n my-namespace --type=merge
```
