### ISSUE TITLE
In-place rolling updates

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#9043]
Our current rolling update scheme requires deleting a pod and creating a replacement. We should also have rolling "in-place" update, of both containers and pods. There are two kinds of in-place update
1) [only applies to container update] pod stays in place, but container doesn't - for example, change container image without killing pod
2) [applies to pod or container update] pod stays in place, and container stays in place - for example, resource limit updates (IIRC we don't implement this yet, or at least don't implement it in-place)

The motivation is that there's no reason to kill the pod if you don't need to. The user may have local data stored in it that they don't want blown away due to update.

**Comment by bgrant0607** [comment]
I agree we'll eventually want this, but...

There are very few in-place, non-disruptive updates that we can actually do right now. For instance, Docker doesn't support resource changes, so we'll need to work around that using cgroup_parent. Resource changes will also complicate admission control in kubelet.

Decoupling lifetime of local storage from the pod is discussed in #7562 and #598, which would reduce the number of circumstances where in-place updates would be required.

**Comment by soundofjw** [comment]
This would be wildly valuable - specifically for kubernetes + elastic-search, where data nodes really shouldn't be losing data.

**Comment by bgrant0607** [comment]
Data needs a lifetime independent of pods. See, for example, #598 and #7562.

**Comment by hurf** [comment]
It seems #6099 is also talking about this.

**Comment by bgrant0607** [comment]
@hurf #6099 is not related to this. That's nodes, this is pods.

**Comment by chengyli** [comment]
What's the difference between this proposal and "kubectl replace/patch"?

**Comment by alfred-huangjian** [comment]
@kubernetes/huawei

**Comment by davidopp** [comment]
https://blog.docker.com/2016/02/docker-1-10/
(Docker 1.10 announcement)

*Live update container resource constraints: When setting limits on what resources containers can use (e.g. memory usage), you had to restart the container to change them. You can now update these resource constraints on the fly with the new docker update command.*

**Comment by davidopp** [comment]
/inplaceupdate subresource on pod might be a good way to express pod updates (resource as well as container image)

**Comment by dts** [comment]
Mentioned in https://github.com/kubernetes/kubernetes/issues/13488 is an important use case for me: updating secrets.  Specifically if we have a load balancer referencing certificates in a Secret and we want to refresh those certificates in a rolling fashion to all pods in the deployment/etc.

**Comment by mqliang** [comment]
@davidopp May I ask what the benefit we can get from in-place rolling update? Is it about scheduling? IIRC, if we update pod.spec, kubelet will kill the pod and recreate, so we still "kill" the pod.

**Comment by davidopp** [comment]
I can't remember for sure, but I think the reason I suggested /inplaceupdate subresource was so that an update request could be rejected if there aren't enough free resources on the node to do the update successfully (if the update is increasing resource request, for example).

Example: 4G machine, running a (request) 1G container a (request) 3G container, then you update the 1G container to 2G. What is supposed to happen? Some component should detect and reject this. It would be better if the master can do it before committing the new request value to etcd, vs. having it not be detected until the kubelet sees it (because then what would the kubelet do? write the old request value back? kill the container?)

BTW I'm not actually sure what happens today if you update the request of a running pod to some value that makes sum of requests > capacity on a node. Probably nothing, is my guess.

Since the scheduler operates asynchronously from the API server, the only way to structure this would be something like an admission controller that synchronously calls to the scheduler, to make processing the /inplaceupdate operation synchronous (so you can reject it when necessary). This is pretty ugly and requires more thought.

**Comment by kargakis** [comment]
cc: @derekwaynecarr

**Comment by davidopp** [comment]
I just realized that if you do this check in an admission controller like I described in the last paragraph above, you don't need a subresource (you would just have the admission controller intercept update to Pod). I guess if you used a subresource maybe you could have the API server delegate the handling of that subresource to the scheduler or something, instead of using an admission controller, but that sounds needlessly complicated.

**Comment by magicwang-cn** [comment]
what's the entrance of the in-place rolling update?
just patch pod directly?  if i create a replicaset includes 3 pods, i can't just patch pod directly, because
when the patched pod failed, the replicaset controller will create a pod with old spec.

so we should use deployment?

**Comment by rcoup** [comment]
Current workaround: patch a deployment with an updated environment variable

```
kubectl patch deployment mydeployment \
-p'{"spec":{"template":{"spec":{"containers":[{"name":"mycontainer","env":[{"name":"RESTART_","value":"$(date)"}]}]}}}}'
```

**Comment by magicwang-cn** [comment]
@rcoup just replace update, not in-place update, right?

**Comment by ddysher** [comment]
As mentioned from @magicwang-cn , updating pod is not enough since if one fails, we'll end up with old spec.  But that's orthogonal to inplace update of pod i think: it's a matter of whether we want to persist new spec.  If we want to persist the new spec, then it seems a new DeploymentStrategy is needed. This stills require we have an approach to update pod though.

**Comment by rcoup** [comment]
> @rcoup just replace update, not in-place update, right?

Correct. For us it solves the use-case of "change configmap or secrets and get deployment to pick them up". 

I'm not sure _any_ docker-based solution really supports some sort of in-place update --  eg. you can't change a running Unix process' environment variables externally without kernel/debugger hackery

**Comment by quinton-hoole** [comment]
cc @quinton-hoole . Federation customers have requested this too.

**Comment by davidopp** [comment]
@quinton-hoole can you say what properties they want to update specifically?

**Comment by quinton-hoole** [comment]
@davidopp Nothing specific.  The request was actually only for a rolling in-place restart.

**Comment by dts** [comment]
@quinton-hoole - is there a reason that setting a RESTART environment variable to the current date/time is insufficient or incorrect?

**Comment by quinton-hoole** [comment]
@dts It's not clear to me what you're proposing.  What would read the RESTART variable and act on it?  The pod? Kubelet?  Something else?

**Comment by quinton-hoole** [comment]
@dts Oh, I see, you're referring to @rcoup 's workaround suggestion above. That does not cause an in-place restart, as far as I understand. The rolling update controller portion of deployment will create replacements for all pods, probably on different nodes (and certainly in different kernel namespaces, cgroups etc) than the originals.

**Comment by dts** [comment]
Ah, I understand.  In-Place restart would preserve emptyDir volumes, but not re-mount secrets, etc, correct?

**Comment by MarkRx** [comment]
Would something like this work for updating labels on the RC / pods?

**Comment by kargakis** [comment]
> Would something like this work for updating labels on the RC / pods?

See https://github.com/kubernetes/kubernetes/issues/36897#issuecomment-263275370, if all you need is to relabel old pods then https://github.com/kubernetes/kubernetes/issues/36897 should be enough for your case.

**Comment by resouer** [comment]
Got a feature request from #39060, which is mainly inspired by `docker update`.

**Comment by bgrant0607** [comment]
Pod resource updates is #5774

**Comment by bgrant0607** [comment]
Example: change to affinity: #57181

**Comment by fabiand** [comment]
Considering the original 2nd case from the initial description - aka changing resources of a pod.

Assuming that we do not want to change the pod (and scheduler) behavior, I wonder if this could be modeled with some kind of `PodResourceAttachment`.

A resource attachment could contain additional memory, or cpu shares, eventually volmes (not sure how the api would look like for this), but if such a "attachment" is created on the cluster, then it can be applied to existing pods based on labels and selectors. The scheduler can check the constratins and either attach such an attachment to a pod or not, effectively granting additional resource to the pod.

In such a fashion the pod itself does not have to be changed, but it could be helpful for i.e. StatefulSet pods, which are running for some longer time.

**Comment by bgrant0607** [comment]
cc @kow3ns @janetkuo

**Comment by bgrant0607** [comment]
@vinaykul Please use email for questions rather than posting to misc. github issues. For your questions, I suggest reaching out to the autoscaling, apps, and node SIGs.

**Comment by xiaods** [comment]
so any update on this feature request?

**Comment by vinaykul** [comment]
> so any update on this feature request?

@xiaods we have started a new merged design [KEP](https://github.com/kubernetes/enhancements/pull/686) and i'm working on it. this has taken me longer than i had initially hoped due to some other tasks taking priority. i'll be updating the new KEP document with my suggested flow control mechanism in that discussion and pushing it out for review in a day or two.

**Comment by xiaods** [comment]
@vinaykul yes, this is very complicated concerns for how-to implement in-place task. i will look for this review docs. thanks a lot.

**Comment by michelgokan** [comment]
@vinaykul  Is there any quick "hack" available to resize a particular container without any restart? Something like disabling scheduler for a short while and perform "docker update". Or anything that I can use for a short while. I need something like this for a specific resource tuning project.

**Comment by vinaykul** [comment]
> @vinaykul Is there any quick "hack" to resize a particular container without killing it? Something like disabling scheduler for a short while and perform "docker update", do whatever I want to do (in my case some benchmarks), and then turn on scheduler again (I don't care if scheduler kills it after I finished my task). I need something like this for a specific resource tuning project.

We have an [implementation](https://github.com/huawei-cloudnative/kubernetes/tree/vertical-scaling) for v1.11 based on our [original design](https://docs.google.com/document/d/18K-bl1EVsmJ04xeRq9o_vfY2GDgek6B6wmLjXw-kos4/). You may have to port it to the version you're interested in, and may need bug fixes - we are not maintaining it anymore as the current design being considered for upstream is significantly different. Hope this helps.

**Comment by michelgokan** [comment]
@vinaykul Very nice. Just 2 more questions: Is this In-Place resizing works together with different [QoS types](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) (guaranteed, burstable,best-effort)? Also, does it support [static CPU manager policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/)?

**Comment by vinaykul** [comment]
> @vinaykul Very nice. Just 2 more questions: Is this In-Place resizing holds the [QoS types](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) (guaranteed, burstable,best-effort)? Also, is it compatible with the [static CPU manager policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/)?

Resizing applies to Guaranteed and burstable QoS classes, and changing QoS class of a running Pod is not allowed. That code does not check for CPU manager policy - so it would incorrectly update non-integral requests for static policy nodes.

**Comment by krmayankk** [comment]
@bgrant0607 @davidopp  @kow3ns is this still in the plans ?

**Comment by vinaykul** [comment]
> @bgrant0607 @davidopp @kow3ns is this still in the plans ?

Yes. @thockin reviewed and approved the KEP, and I'm working on resolving a couple of changes requested from KubeCon API review session, and fleshing out the test plans and GA criteria sections in order to get the KEP into implementable stage before Jan 28 date for 1.18 release.

**Comment by andyxning** [comment]
@vinaykul What is the status for In-Place Pod resource change? We have similar requirements like yours. Hope you can give us some info.

**Comment by vinaykul** [comment]
> @vinaykul What is the status for In-Place Pod resource change? We have similar requirements like yours. Hope you can give us some info.

We are revisiting the API changes that we previously thought were good. For details, please see https://github.com/kubernetes/enhancements/pull/1883 

I hope to find some time in the coming weeks to refactor PR https://github.com/kubernetes/kubernetes/pull/92127 as per the above discussion and check the implementation for robustness (I'm about half-way done, but I have some higher priority work)

**Comment by yarncraft** [comment]
**OpenKruise** (https://openkruise.io/en-us/index.html) offers a _well documented_ solution through the use of **CustomResourceDefinitions**. It would be valuable to include these controllers in vanilla Kubernetes since they seem to resolve the challenges mentioned above.

**Comment by liupeng0518** [comment]
> 1. [only applies to container update] pod stays in place, but container doesn't - for example, change container image without killing pod

Is there any quick "hack" to replace image without killing it?

**Comment by yangjunsss** [comment]
> **OpenKruise** (https://openkruise.io/en-us/index.html) offers a _well documented_ solution through the use of **CustomResourceDefinitions**. It would be valuable to include these controllers in vanilla Kubernetes since they seem to resolve the challenges mentioned above.

It seems *Kruise* resolve the update container in-place, but not the request & limit of container.

**Comment by FillZpp** [comment]
> It seems Kruise resolve the update container in-place, but not the request & limit of container.

Yeah, OpenKruise v1.0 now supports update images and env/command/args (via Downward API) in-place (https://openkruise.io/docs/core-concepts/inplace-update), but it can not modify request & limit which will break the logic of scheduler and kubelet.

**Comment by jonyhy96** [comment]
FYI https://github.com/kubernetes/kubernetes/pull/102884 this pr try to implement In-place Pod Vertical Scaling which may change pod's request & limit

**Comment by surarchita-matam** [comment]
Is there any hack we can use to read the updated config map values without restarting a pod?

**Comment by shinebayar-g** [comment]
> Is there any hack we can use to read the updated config map values without restarting a pod?

Doesn't configmap already do that? (if not using subPath)

**Comment by surarchita-matam** [comment]
> Doesn't configmap already do that? (if not using subPath)
No its not working.

**Comment by furykerry** [comment]
since openkruise 1.8, cloneset and advance statefulset now support inplace resource resizing
https://github.com/openkruise/kruise/pull/1353
