### ISSUE TITLE
batch v1beta1 will be deprecated in 1.22

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#90473]
per https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/1635-prevent-permabeta/README.md.   https://github.com/kubernetes/kubernetes/pull/90472 added the tags, but the release note should be in 1.22.

**Comment by wangyysde** [comment]
As if batch v1beta1 has be marked deprecated in #99423. Should we close this issue?
