### ISSUE TITLE
Fix entries in root go.mod for staging repositories just before tagging a release

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#90474]
Looking at a released go.mod file:
https://github.com/kubernetes/kubernetes/blob/v1.18.2/go.mod#L141-L152

Please see the for all the staging repos, we have `v0.0.0` in the root go.mod. If there was a way for the release tooling to update this go.mod file just before we cut alpha/beta/rc/final etc. that would help some folks.

Yes, this gets into the discussion that folks should not use k/k directly etc. So leaving this suggestion here to see what sig-release and other folks think!

/sig release
/cc @justaugustus @tpepper @liggitt

**Comment by dims** [comment]
oh in the example above the suggestion would be for the `v0.0.0` to be `v1.18.2`. Yes i know when we cut the release publishing bot has not yet run that publishes code to the repos that get populated from staging repos.

**Comment by liggitt** [comment]
I am not in favor of making our release tagging workflow more complicated, to add commits referencing dependency versions that don't yet exist, to enable uses we explicitly don't support.

**Comment by nikhita** [comment]
Looks like this can be closed?

Fwiw there is discussion to fix this on go's side to not require `v0.0.0` in the require directive for local replacements. Ref: https://github.com/golang/go/issues/33370. This issue should get fixed once Go fixes it.

**Comment by nikhita** [comment]
Also as a side note from a technical perspective, even if we did this, the go.sum file won't be generated correctly and `go mod tidy` will create a diff on release tags. This is true even for published staging repos today, but it doesn't matter for them because they are supposed to be imported directly and used as libraries. We might not want this behavior for k/k.

**Comment by justaugustus** [comment]
From what I remember of brief discussion w/ Dims and Jordan, we essentially opened this issue to document that this is something that we _don't_ want to do.

/close
