### ISSUE TITLE
kubectl get events returns null on some events timestamp fields

### ISSUE THREAD

**Issue by inoam** [kubernetes/kubernetes#90482]
**What happened**:
Ran `kubectl get events -o yaml`
got list of events but some of the timestamp fields are missing
for example here - no first and last:
```
- action: Binding
  apiVersion: v1
  eventTime: "2020-04-24T13:38:26.252501Z"
  firstTimestamp: null
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: alertmanager-monit-alertmanager-0
    namespace: magellan
    resourceVersion: "17555"
    uid: a2340cb4-e308-4b08-b3e2-d8bea043e0e3
  kind: Event
  lastTimestamp: null
  message: Successfully assigned magellan/alertmanager-monit-alertmanager-0 to ip-172-31-108-34.eu-west-1.compute.internal
  metadata:
    creationTimestamp: "2020-04-24T13:38:26Z"
    name: alertmanager-monit-alertmanager-0.1608c507df74c9ad
    namespace: magellan
    resourceVersion: "17560"
    selfLink: /api/v1/namespaces/magellan/events/alertmanager-monit-alertmanager-0.1608c507df74c9ad
    uid: 48d60a45-d1d7-44e4-98a4-8b777c1e1981
  reason: Scheduled
  reportingComponent: default-scheduler
  reportingInstance: default-scheduler-ip-172-31-181-132.eu-west-1.compute.internal
  source:
    component: default-scheduler
  type: Normal
```

While here no eventTime:
```
- apiVersion: v1
  count: 1
  eventTime: null
  firstTimestamp: "2020-04-24T13:30:27Z"
  involvedObject:
    apiVersion: apps/v1
    kind: StatefulSet
    name: etcd
    namespace: magellan
    resourceVersion: "13231"
    uid: 08bb433c-113a-4eb0-b239-cec4f405ba83
  kind: Event
  lastTimestamp: "2020-04-24T13:30:27Z"
  message: create Pod etcd-0 in StatefulSet etcd successful
  metadata:
    creationTimestamp: "2020-04-24T13:30:27Z"
    name: etcd.1608c49853129748
    namespace: magellan
    resourceVersion: "13234"
    selfLink: /api/v1/namespaces/magellan/events/etcd.1608c49853129748
    uid: 4aba9d4d-0e3b-42b4-87eb-f7856c2f848f
  reason: SuccessfulCreate
  reportingComponent: ""
  reportingInstance: ""
  source:
    component: statefulset-controller
  type: Normal
```

**What you expected to happen**:
get list of events in yaml format, with all following fields not null:
`firstTimestamp`
`lastTimestamp`
`eventTime`
`metadata.creationTimestamp`

such that I'll be able to sort events by timestamp (mainly buy lastTimestamp but not necessarily)

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubectl get events -o yaml`

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: aws

**Comment by liggitt** [comment]
This is the responsibility of the component creating the event, not the CLI. I'd suggest opening specific issues for the problematic reporting components.

**Comment by inoam** [comment]
@liggitt as always thanks for reply!
Just to be sure - in the first case for example talks about  assigning pod to a node, component is default scheduler, so I should open bug for the specific event and tag sig scheduling ? (I will find my way for the other examples)

**Comment by liggitt** [comment]
Actually, it looks like firstTimestamp/lastTimestamp is deprecated in favor of eventTime reported in newer versions of the events helpers and API. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1661-new-event-api-ga-graduation#comparison-between-old-and-new-apis

The scheduler reports events using the newer version when available, so the eventTime field is populated.

The statefulset controller reports events using the older API and helpers, so eventTime is not yet populated and firstTimestamp/lastTimestamp are.

**Comment by liggitt** [comment]
The firstTimestamp/lastTimestamp and eventTime fields are optional, so clients must tolerate events without those timestamps set.

**Comment by liggitt** [comment]
there are issues tracking migrating components to the newer events helpers and API: https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+%22use+v1beta1+events%22+is%3Aissue+
