### ISSUE TITLE
[Flaky Test]: gce-master-scale-correctness (ci-kubernetes-e2e-gce-scale-correctness)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90506]
**Which jobs are failing**:
gce-master-scale-correctness (ci-kubernetes-e2e-gce-scale-correctness)

**Which test(s) are failing**:
[sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD with validation schema [Conformance] 

**Since when has it been failing**:
04-26 05:02 PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
Apr 26 12:28:01.219: FAIL: failed to explain ksvc.spec: error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://35.185.126.243 --kubeconfig=/workspace/.kube/config explain ksvc.spec:
Command stdout:

stderr:
the server doesn't have a resource type "ksvc"

error:
exit status 1

Full Stack Trace
k8s.io/kubernetes/test/e2e/apimachinery.glob..func4.1()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go:131 +0x1545
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc002ca6100)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x324
k8s.io/kubernetes/test/e2e.TestE2E(0xc002ca6100)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:141 +0x2b
testing.tRunner(0xc002ca6100, 0x4b8d060)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
[AfterEach] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:175
ï¿½[1mSTEPï¿½[0m: Collecting events from namespace "crd-publish-openapi-4377".
ï¿½[1mSTEPï¿½[0m: Found 0 events.
Apr 26 12:28:01.314: INFO: POD  NODE  PHASE  GRACE  CONDITIONS
Apr 26 12:28:01.314: INFO: 
Apr 26 12:28:02.899: INFO: skipping dumping cluster info - cluster too large
Apr 26 12:28:02.899: INFO: Waiting up to 3m0s for all (but 50) nodes to be ready
ï¿½[1mSTEPï¿½[0m: Destroying namespace "crd-publish-openapi-4377" for this suite.

**Anything else we need to know**:

/cc @kubernetes/ci-signal 
/cc @kubernetes/sig-api-machinery-bugs 
/milestone v1.19
/priority critical-urgent

**Comment by hasheddan** [comment]
/milestone v1.19

Thanks for opening this! I'll get you on milestone maintainers soon @hkamel :)

Also, was taking a look at this as well and noticed this test was recently added: https://github.com/kubernetes/kubernetes/pull/89505

**Comment by liggitt** [comment]
As noted in https://github.com/kubernetes/kubernetes/pull/89505/files#r415473166, this modified an existing conformance test and made it flaky. Please move the new test out of the conformance test and mark it as flaky until this issue has been resolved.

**Comment by liggitt** [comment]
Cc @knight42 @soltysh for flake introduced in https://github.com/kubernetes/kubernetes/pull/89505

**Comment by knight42** [comment]
It is a bit weird that I cannot reproduce this problem on my local kind cluster by running 
```
go test ./test/e2e -v -args -ginkgo.focus='works for CRD with validation schema' -kubeconfig ~/.kube/config
```
even after 20 times 😕

I suspect this is a cache issue since I once created a crd without short name `ksvc` and forgot to delete it in the test.

**Comment by hasheddan** [comment]
/retitle [Flaky Test]: gce-master-scale-correctness (ci-kubernetes-e2e-gce-scale-correctness)
/kind flake
/remove-kind failing-test

**Comment by knight42** [comment]
I can reproduce this problem by the following steps now

<pre>
$ cat ksvc.yaml
<summary>
<details>
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.crd-publish-openapi-test-service.example.com
spec:
  conversion:
    strategy: None
  group: crd-publish-openapi-test-service.example.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
    shortNames: ["ksvc"]
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Specification of CustomService
            properties:
              dummy:
                description: Dummy property.
                type: string
            type: object
        type: object
    served: true
    storage: true
</details>
</summary>
$ kubectl get crd
No resources found in default namespace.

$ rm -r ~/.kube/cache

$ kubectl explain ksvc.spec
the server doesn't have a resource type "ksvc"

$ kubectl create -f ksvc.yaml
customresourcedefinition.apiextensions.k8s.io/services.crd-publish-openapi-test-service.example.com created

$ kubectl explain ksvc.spec
the server doesn't have a resource type "ksvc"

$ kubectl explain ksvc.spec
<summary>
<details>
KIND:     Service
VERSION:  crd-publish-openapi-test-service.example.com/v1alpha1

RESOURCE: spec <Object>

DESCRIPTION:
     Specification of CustomService

FIELDS:
   dummy        <string>
     Dummy property.
</details>
</summary>
</pre>

it looks like that this problem has something to do with discovery cache.

**Comment by liggitt** [comment]
looks like https://github.com/kubernetes/kubernetes/issues/65517
