### ISSUE TITLE
Unable to request "attachable-volumes-aws-ebs" resource

### ISSUE THREAD

**Issue by mgaurav** [kubernetes/kubernetes#90505]
**What happened**:
I am running a EKS cluster and to respect volume attachment constraints which EC2 instances have, I want to use "attachable-volumes-aws-ebs" resource type in my request. 

kubectl describe node shows "attachable-volumes-aws-ebs" resource is specified on the nodes. However, when I request it in my pod spec, I get an error.
```
$ kubectl describe node
...
Capacity:
 attachable-volumes-aws-ebs:  25
 cpu:                         4
 ephemeral-storage:           524275692Ki
 hugepages-1Gi:               0
 hugepages-2Mi:               0
 memory:                      15950512Ki
 pods:                        58
Allocatable:
 attachable-volumes-aws-ebs:  25
 cpu:                         4
 ephemeral-storage:           483172476948
 hugepages-1Gi:               0
 hugepages-2Mi:               0
 memory:                      15848112Ki
 pods:                        58
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests      Limits
  --------                    --------      ------
  cpu                         560m (14%)    600m (15%)
  memory                      2690Mi (17%)  2890Mi (18%)
  ephemeral-storage           0 (0%)        0 (0%)
  attachable-volumes-aws-ebs  0             0
```

```
$ cat ~/eks/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume-resource 
  namespace: default 
spec:
  containers:
    - name: container 
      image: nginx 
      resources:
        requests:
          attachable-volumes-aws-ebs: 3

$ kubectl create -f ~/eks/pod.yaml 
The Pod "pod-with-volume-resource" is invalid: 
* spec.containers[0].resources.requests[attachable-volumes-aws-ebs]: Invalid value: "attachable-volumes-aws-ebs": must be a standard resource type or fully qualified
* spec.containers[0].resources.requests[attachable-volumes-aws-ebs]: Invalid value: "attachable-volumes-aws-ebs": must be a standard resource for containers
```

**What you expected to happen**:
I expected pod to be launched and available volume capacity on the node to be reduced by 3.

**How to reproduce it (as minimally and precisely as possible)**:
Launch an EKS cluster, and create a pod using above specification.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-879c36", GitCommit:"879c3621692a32b5d77a951ca0e61ee55aefc80f", GitTreeState:"clean", BuildDate:"2020-02-21T18:09:01Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux gauravm-precision-5530 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jsafrane** [comment]
Volume attachment resources work differently. The Kubernetes scheduler counts what kind of volumes a pod uses and calculates necessary `attachable-volumes-<xyz>` automatically. The pod should not explicitly request any `attachable-volumes` resource, because pod author may not know what storage backend the pod is going to use in the end.

See https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodevolumelimits/non_csi.go

If you create pods that use AWS EBS PV/PVCs, will Kuberentes respect limits of the nodes? At some point new pods should not get scheduled and you should see "X node(s) exceed max volume count" event on these pods. If not, it is a bug in the scheduler.

**Comment by mgaurav** [comment]
Thanks @jsafrane. You are correct, kubernetes scheduler is handling volume counts.

```
  Warning  FailedScheduling        113s (x2 over 113s)  default-scheduler                                     0/1 nodes are available: 1 node(s) exceed max volume count.
  Normal   TriggeredScaleUp        110s                 cluster-autoscaler                                    pod triggered scale-up: [{Rubrik-Exocompute-AutoScalingGroup-GGKAPD 1->2 (max: 10)}]
 ```

The reason I thought I would need to request `attachable-volumes` explicitly is because node's allocatable counts for `attachable-volumes` is always reported as zero:
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests     Limits
  --------                    --------     ------
  cpu                         160m (4%)    250m (6%)
  memory                      1250Mi (8%)  1250Mi (8%)
  ephemeral-storage           0 (0%)       0 (0%)
  attachable-volumes-aws-ebs  0            0
```

This issue is invalid, so I will close it. Thanks for your help.

**Comment by pnorth1** [comment]
I understand not being able to request this resource explicitly in the pod definition. But, what about the fact that it is not reported correctly at the node level? I would expect describing the node to still show how many volumes are requested, and the limits of the node?
