### ISSUE TITLE
Allow editing labels/selector in pod template spec in StatefulSets

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kubernetes#90519]
**What would you like to be added**:
The ability to modify the labels and selector clauses in StatefulSets after they are deployed

**Why is this needed**:
Currently if a STS is deployed and you need to modify the pod labels and, by inference, the selector labels you cannot do so, because Kubernetes will reject the update with:

`Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

You can force the update by deleting the STS and redeploying it (or by using `--force` in Helm), but this causes downtime of the service in between when the last pod is deleted and the new one is ready, which is not ideal, especially if you are in production.

Allowing the label updates (even if you disallow updates to the other parts of the pod template spec), is fine.

**Comment by liggitt** [comment]
This restriction was added in apps/v1 because changes to labels/selectors had not worked well historically.

**Comment by huang-jy** [comment]
Thanks, @liggitt, is there any easier (and less destructive) way I would update something like the labels and selector clauses without having to nuke the entire STS?

**Comment by liggitt** [comment]
I thought labels could be updated as long as they still matched the selector. The changing selector was the problematic field which was why it was made immutable.

**Comment by huang-jy** [comment]
In my case I'm making the update to both together -- the label (spec.template.metadata.labels) and the selector (spec.selector.matchLabels)

If I only change the label section, the update will fail saying the labels don't match the selector.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/50808 was the issue tracking selector immutability and described some of the problems caused by allowing selectors to change.

**Comment by huang-jy** [comment]
https://github.com/kubernetes/kubernetes/issues/50808#issuecomment-324746374

You mentioned my exact situation here :)

**Comment by huang-jy** [comment]
Still valid

**Comment by huang-jy** [comment]
This ticket has been given the "stale" and "waiting for info" labels. 

Are you waiting for more details from me, and if so, what additional info do you need?

**Comment by liggitt** [comment]
This is waiting for evidence that the benefit of changing labels/selectors outweighs the risks of allowing them to change, that the issues previously seen with this can be corrected, and that it is deemed sufficiently important to staff

**Comment by huang-jy** [comment]
Thanks, wasn't sure if that label was meant for me or not.

**Comment by huang-jy** [comment]
Still active

**Comment by cornfeedhobo** [comment]
> This restriction was added in apps/v1 because changes to labels/selectors had not worked well historically.

Are there any cases to point to? It seems odd to make a stateful resource *more brittle* - generally that is better handled by ephemeral workloads.

> I thought labels could be updated as long as they still matched the selector. The changing selector was the problematic field which was why it was made immutable.

This would be great, but it seems like they're immutable period, regardless of the selector still matching.

**Comment by blowfishpro** [comment]
You definitely have to be careful updating the selector - if the pods don't already have those labels the controller won't associate them with the statefulset and will try to create pods that already exist.  If you add the new labels first though it seems to work fine.

**Comment by babinos87** [comment]
There is a valid use case when someone has a label called `app.kubernetes.io/version`, which is used by Istio, for example. When a new version of the app is created, someone would need to change this label. Is there a workaround for this, if we can't update the label of a StatefulSet (apart from deleting and recreating it)?

**Comment by jdemeyer** [comment]
And what about the labels of the StatefulSet itself, i.e. `metadata.labels`? I get why you can't change the pod and selector labels (it's also like that for a Deployment). But for a StatefulSet, even the top-level labels are immutable and that's a difference with a Deployment. For example, the linked issue https://github.com/helm/helm/issues/13051 is about those labels.

**Comment by liggitt** [comment]
> And what about the labels of the StatefulSet itself, i.e. metadata.labels? I get why you can't change the pod and selector labels (it's also like that for a Deployment). But for a StatefulSet, even the top-level labels are immutable and that's a difference with a Deployment.

I don't think that's accurate... I see the statefulset labels able to be updated:

ss1.yaml:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test1
  labels:
    sslabel: value
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: test
        image: test
```

```sh
$ kubectl create -f ss1.yaml

statefulset.apps/test1 created

$ kubectl get statefulsets --show-labels

NAME    READY   AGE   LABELS
test1   0/1     0s    sslabel=value

$ kubectl label -f ss1.yaml newlabel=newvalue

statefulset.apps/test1 labeled

$ kubectl get statefulsets --show-labels

NAME    READY   AGE   LABELS
test1   0/1     0s    newlabel=newvalue,sslabel=value
```
