### ISSUE TITLE
Kubelet cannot detect CPU Cache for ARM CPUs

### ISSUE THREAD

**Issue by sharkymcdongles** [kubernetes/kubernetes#90511]
**What happened**: On both k8s 1.16.1 and 1.18.2 Ubuntu 18.04 aarch64 and Rasbpian Buster ARM7l kubelet logs say cannot detect CPU cache and I see this:

`Apr 26 13:55:24 pi0 kubelet[1509]: E0426 13:55:24.900279 1509 machine.go:331] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory`

**What you expected to happen**: I expect CPU cache to be detected. I think problem is that aarch64 writes cache information in a different way or something.

**How to reproduce it (as minimally and precisely as possible)**: Install k8s aarch64 on Ubuntu or Raspbian.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 and Rasbpian Buster
- Kernel (e.g. `uname -a`): Linux pi1 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
- Install tools: kubeadm

It seems cache is improperly detected / monitored on arm cpus. :'(

**Comment by sharkymcdongles** [comment]
Still a problem even if stale.

**Comment by dims** [comment]
cc @lubinsz

**Comment by eamonryan** [comment]
/remove-lifecycle-stale

Also seeing this on aarch64 Raspbian Lite myself, it's actually a k3s install but the error is the same:
`Linux pi02 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux`

`Aug 20 17:44:55 pi02 k3s[13031]: E0820 17:44:55.333152   13031 machine.go:331] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory`
