### ISSUE TITLE
Dynamically changing CPU requests / limits

### ISSUE THREAD

**Issue by dinogun** [kubernetes/kubernetes#90518]
**What would you like to be added**:
Sorry if this has been asked before, is it possible to change the CPU requests and limits during the course of the lifetime of a pod ?

**Why is this needed**:
Java applications typically need more CPU during initialization and subsequently settle down. Putting the pod into the shared pool (Burstable QoS) means that the extra CPU needed at Init time is not guaranteed and may result in taking a performance hit. Is it possible to have a concept of a INIT time CPU request that is different from the rest of the run ? This is a very common scenario in FaaS environments where a delay during INIT can cause delays in the time it takes to handle the first request and so needs the guaranteed higher CPU, but subsequently needs very less CPU.

**Comment by liggitt** [comment]
It is not currently possible. There is a proposal to allow it at https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20181106-in-place-update-of-pod-resources.md, but is quite involved.

**Comment by matthyx** [comment]
new location of the KEP:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/
