### ISSUE TITLE
[Failing Test] verify-master (ci-kubernetes-verify-master)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#90538]
**Which jobs are failing**:

`verify-master (ci-kubernetes-verify-master)`

**Which test(s) are failing**:

`Overall`

**Since when has it been failing**:

`04-27-20 05:47 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

**Reason for failure**:

```
I0427 13:19:08.353332    2197 parse.go:444] type checker: /usr/local/go/src/runtime/panic.go:292:34: cannot use (_defer literal) (value of type _defer) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
I0427 13:19:08.353837    2197 parse.go:444] type checker: /usr/local/go/src/runtime/panic.go:292:20: unsafe.Sizeof((_defer literal)) (value of type uintptr) is not constant
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority important-soon

**Comment by liggitt** [comment]
I think that's a false positive and not the actual cause of the failure. Note those messages are logged at info level.

**Comment by liggitt** [comment]
It's a timeout error. 

https://testgrid.k8s.io/google-unit#verify-master&graph-metrics=test-duration-minutes&width=20

**Comment by hasheddan** [comment]
@liggitt the variance that you noted makes me think the solution is likely not just bumping the timeout limit here. Any ideas why this would be taking much longer on some runs than others?

**Comment by liggitt** [comment]
Not sure. My first guess would be CPU or disk contention

**Comment by hasheddan** [comment]
@liggitt I am going to close this in favor of https://github.com/kubernetes/kubernetes/issues/87807, which has historical info about this flake

/close
