### ISSUE TITLE
ORing label selectors for different keys

### ISSUE THREAD

**Issue by lolin9** [kubernetes/kubernetes#90549]
Is it possible to have a logical OR operation for different keys when selecting objects? Something like 
```key1=value1 || key2=value2```
I am more interested in the programmatic approach via the go-client case not the YAML config.

**Comment by liggitt** [comment]
That is not currently possible. Disjoint selectors were intentionally avoided in the selector design to allow for efficient indexing in the future (e.g. https://github.com/kubernetes/kubernetes/issues/4817) and to avoid complexity of nested boolean AND/OR expressions.

**Comment by lolin9** [comment]
@liggitt thank you for the quick response. I can get around this by using regex for a single key (e.g. `key=*val*`), is this possible, maybe in set-based selections?

**Comment by liggitt** [comment]
No, label selectors only match literal values, presence, or absence of a key. Regex/prefix matching is not a supported label selector feature.

**Comment by lolin9** [comment]
Thank you! It seems that I wish for more advanced filtering via labels than I should. Have you ever been asked by any big opensource project devs (e.g. istio, rook, etc..) about something similar? Maybe I can just read some code and learn how things are done (even if it's some dirty solution). Maybe these projects need advancing filtering for their CRDs.

**Comment by liggitt** [comment]
The suggestion we've made in the past is to actively watch/compute/persist more complex decisions as a dedicated label

**Comment by lolin9** [comment]
@liggitt Probably for my case, I will just use `List` repetitively with each label and then combine the unique objects into one list. It isn't clean but it isn't that expensive too.

**Comment by nehatomar12** [comment]
@liggitt @lolin9 did you get any resolution? to filter key1=value1 || key2=value2?
