### ISSUE TITLE
[Failing Test] build-master-fast (ci-kubernetes-build-fast)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90568]
**Which jobs are failing**:
Overall

**Which test(s) are failing**:
ci-kubernetes-build-fast

**Since when has it been failing**:
04-28 12:59 PDT

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#build-master-fast

**Reason for failure**:
W0428 20:30:04.496]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 32, in check
W0428 20:30:04.497]     subprocess.check_call(cmd)
W0428 20:30:04.498]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0428 20:30:04.498]     raise CalledProcessError(retcode, cmd)
W0428 20:30:04.498] subprocess.CalledProcessError: Command '('make', 'quick-release')' returned non-zero exit status 2
E0428 20:30:04.528] Command failed
I0428 20:30:04.528] process 506 exited with code 1 after 0.2m
E0428 20:30:04.528] FAIL: ci-kubernetes-build-fast
I0428 20:30:04.529] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0428 20:30:06.052] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
I0428 20:30:06.276] process 930 exited with code 0 after 0.0m
I0428 20:30:06.276] Call:  gcloud config get-value account
I0428 20:30:07.897] process 944 exited with code 0 after 0.0m

**Anything else we need to know**:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W0428 20:46:55.687] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W0428 20:46:55.888] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W0428 20:46:56.082] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W0428 20:46:56.280] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W0428 20:46:57.019] Run: ('make', 'quick-release')
I0428 20:46:57.187] +++ [0428 20:46:57] Verifying Prerequisites....
W0428 20:46:57.522] Can't connect to 'docker' daemon. 

/cc @kubernetes/ci-signal
/cc @kubernetes/sig-testing
/priority critical-urgent
/milestone v1.19

**Comment by BenTheElder** [comment]
PRing fixes

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17423
needs 2x followup. on it.

**Comment by dims** [comment]
pull-kubernetes-cross failed as well https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-cross

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17425 => bump kubekins next.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17427

**Comment by BenTheElder** [comment]
fairly confident this will bounce back once https://github.com/kubernetes/test-infra/pull/17427 merges. it's lgtm just waiting on tests / tide

**Comment by BenTheElder** [comment]
green https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1255265195530391552

**Comment by BenTheElder** [comment]
/close
this has been green since the 15:39 PDT run

**Comment by BenTheElder** [comment]
last follow up FTR https://github.com/kubernetes/test-infra/pull/17428

**Comment by hasheddan** [comment]
Thanks so much @BenTheElder!
