### ISSUE TITLE
Check podSandboxChanged with wrong sandboxStatus 

### ISSUE THREAD

**Issue by weili10** [kubernetes/kubernetes#90588]
https://github.com/kubernetes/kubernetes/blob/0c3c2cd6ac8c9ffefc38f9746034e546331b9cd6/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L434

The comment said 'Needs to create a new sandbox when readySandboxCount > 1 or the ready sandbox is not "the latest one".'

but the sandboxStatus got here is the first one.

**Comment by tedyu** [comment]
Take a look at the two if statements starting with the one on line 435:
```
	if readySandboxCount > 1 {
```

**Comment by weili10** [comment]
The first if statement only check the 'ready' sandbox count > 1.
I encountered a situation that there were 2 sandbox status in the list, the first is not ready and the second is ready. In this situation it would said there is no ready sanbox found and kill the pod.

**Comment by weili10** [comment]
> Take a look at the two if statements starting with the one on line 435:
> 
> ```
> 	if readySandboxCount > 1 {
> ```
The first if statement only check the 'ready' sandbox count > 1.
I encountered a situation that there were 2 sandbox status in the list, the first is not ready and the second is ready. In this situation it would said there is no ready sanbox found and kill the pod.

**Comment by tedyu** [comment]
```
		if s.State == runtimeapi.PodSandboxState_SANDBOX_READY {
			readySandboxCount++
```
Please look at the code on line 428.
In the scenario you described, readySandboxCount should be 1.

Can you attach relevant part of kubelet.log so that we can understand the situation ?

Thanks

**Comment by weili10** [comment]
I add a log statement 
`klog.V(2).Infof("SandBoxStatus: %+v", podStatus.SandboxStatuses)`
at line 434 to print the sandbox statuses, and substitute the massive pod info with xxx in the log.

What I have done is that deploy a pod and then reboot the system, and then try to re-deploy the pod by SyncPod() funciton. 



`I0211 16:29:50.617009    3737 kuberuntime_manager.go:480] Syncing Pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)": &Pod{xxx}
I0211 16:29:50.618168    3737 kuberuntime_manager.go:434] SandBoxStatus: [&PodSandboxStatus{Id:637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35,Metadata:&PodSandboxMetadata{Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Uid:01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Namespace:websocket,Attempt:0,},State:SANDBOX_NOTREADY,CreatedAt:1588267528126901235,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},},},Labels:map[string]string{io.kubernetes.pod.name: web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,io.kubernetes.pod.namespace: websocket,io.kubernetes.pod.uid: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8,},Annotations:map[string]string{},RuntimeHandler:,} &PodSandboxStatus{Id:b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f,Metadata:&PodSandboxMetadata{Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Uid:01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Namespace:websocket,Attempt:1,},State:SANDBOX_READY,CreatedAt:1455208104948964730,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},},},Labels:map[string]string{io.kubernetes.pod.name: web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,io.kubernetes.pod.namespace: websocket,io.kubernetes.pod.uid: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8,},Annotations:map[string]string{},RuntimeHandler:,}]
I0211 16:29:50.618365    3737 kuberuntime_manager.go:442] No ready sandbox for pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)" can be found. Need to start a new one
I0211 16:29:50.618426    3737 kuberuntime_manager.go:652] computePodActions got {KillPod:true CreateSandbox:true SandboxID:637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35 Attempt:1 NextInitContainerToStart:nil ContainersToStart:[0] ContainersToKill:map[] EphemeralContainersToStart:[]} for pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)"
I0211 16:29:50.618522    3737 record.go:24] Normal SandboxChanged Pod sandbox changed, it will be killed and re-created.
I0211 16:29:50.618564    3737 kuberuntime_manager.go:668] Stopping PodSandbox for "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)", will start new one
I0211 16:29:50.618776    3737 record.go:19] Normal Killing Stopping container container-0
I0211 16:29:50.618827    3737 kuberuntime_container.go:600] Killing container "docker://a9280be54c46eeaee6a38087b11e082a4bc9e77341942179e0fd49a1cb99c0f1" with 30 second grace period`

**Comment by tedyu** [comment]
How about the following change ?
```
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_manager.go b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
index bf40fd51eb7..ab58d4e84c5 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_manager.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
@@ -424,9 +424,12 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
        }

        readySandboxCount := 0
+       unreadySandboxCount := 0
        for _, s := range podStatus.SandboxStatuses {
                if s.State == runtimeapi.PodSandboxState_SANDBOX_READY {
                        readySandboxCount++
+               } else {
+                       unreadySandboxCount++
                }
        }

@@ -436,7 +439,7 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
                klog.V(2).Infof("Multiple sandboxes are ready for Pod %q. Need to reconcile them", format.Pod(pod))
                return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
        }
-       if sandboxStatus.State != runtimeapi.PodSandboxState_SANDBOX_READY {
+       if unreadySandboxCount > 0 && readySandboxCount == 0 {
                klog.V(2).Infof("No ready sandbox for pod %q can be found. Need to start a new one", format.Pod(pod))
                return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
        }
```

**Comment by tedyu** [comment]
@weili10 
Can you give us more information about your deployment ?

* version of k8s
* version of CRI

**Comment by tedyu** [comment]
By injecting pod sandbox in TestSyncPodWithInitContainers, I was able to exercise the mentioned condition.
```
  0 = {*k8s.io/kubernetes/pkg/kubelet/container.SyncResult | 0xc0003e1fc0}
   Action = {k8s.io/kubernetes/pkg/kubelet/container.SyncAction} "KillContainer"
  1 = {*k8s.io/kubernetes/pkg/kubelet/container.SyncResult | 0xc0003f8000}
   Action = {k8s.io/kubernetes/pkg/kubelet/container.SyncAction} "KillPodSandbox"
  2 = {*k8s.io/kubernetes/pkg/kubelet/container.SyncResult | 0xc0003f8080}
   Action = {k8s.io/kubernetes/pkg/kubelet/container.SyncAction} "CreatePodSandbox"
  3 = {*k8s.io/kubernetes/pkg/kubelet/container.SyncResult | 0xc0003f8100}
   Action = {k8s.io/kubernetes/pkg/kubelet/container.SyncAction} "ConfigPodSandbox"
  4 = {*k8s.io/kubernetes/pkg/kubelet/container.SyncResult | 0xc0003f8180}
   Action = {k8s.io/kubernetes/pkg/kubelet/container.SyncAction} "StartContainer"
```
with the following proposed change, there would be one SyncResult instead of 5.
```
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_manager.go b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
index bf40fd51eb7..ab58d4e84c5 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_manager.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
@@ -424,9 +424,12 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
        }

        readySandboxCount := 0
+       unreadySandboxCount := 0
        for _, s := range podStatus.SandboxStatuses {
                if s.State == runtimeapi.PodSandboxState_SANDBOX_READY {
                        readySandboxCount++
+               } else {
+                       unreadySandboxCount++
                }
        }

@@ -436,7 +439,7 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
                klog.V(2).Infof("Multiple sandboxes are ready for Pod %q. Need to reconcile them", format.Pod(pod))
                return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
        }
-       if sandboxStatus.State != runtimeapi.PodSandboxState_SANDBOX_READY {
+       if unreadySandboxCount > 0 && readySandboxCount == 0 {
                klog.V(2).Infof("No ready sandbox for pod %q can be found. Need to start a new one", format.Pod(pod))
                return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
        }
```

**Comment by tedyu** [comment]
@feiskyer 
Since you were the author of the underlying code, can you chime in ?

**Comment by tedyu** [comment]
@weili10 
Does my proposed fix in https://github.com/kubernetes/kubernetes/issues/90588#issuecomment-621973387 make sense ?

**Comment by feiskyer** [comment]
There're already two conditions are checked: `readySandboxCount > 1` and `sandboxStatus.State != runtimeapi.PodSandboxState_SANDBOX_READY`. And this two checks are matched with the above comment `Needs to create a new sandbox when readySandboxCount > 1 or the ready sandbox is not the latest one`.

I don't think we should check `unreadySandboxCount` because regardless of unreadySandboxCount, if the latest sandbox is not ready, a new sandbox needs to be created.

**Comment by tedyu** [comment]
@feiskyer 
I was modifying the condition when you made the above comment.
What do you think of the following where if the sandbox with highest attempt is unready, we create new sandbox ?
```
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_manager.go b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
index bf40fd51eb7..e5bf048f4ed 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_manager.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
@@ -424,9 +424,20 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
        }

        readySandboxCount := 0
+       // highest attempt number for ready sandbox
+       readyAttempt := -1
+       // highest attempt number for unready sandbox
+       unreadyAttempt := -1
        for _, s := range podStatus.SandboxStatuses {
                if s.State == runtimeapi.PodSandboxState_SANDBOX_READY {
                        readySandboxCount++
+                       if readyAttempt < 0 || uint32(readyAttempt) < s.Metadata.Attempt {
+                               readyAttempt = int(s.Metadata.Attempt)
+                       }
+               } else {
+                       if unreadyAttempt < 0 || uint32(unreadyAttempt) < s.Metadata.Attempt {
+                               unreadyAttempt = int(s.Metadata.Attempt)
+                       }
                }
        }

@@ -436,7 +447,7 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
                klog.V(2).Infof("Multiple sandboxes are ready for Pod %q. Need to reconcile them", format.Pod(pod))
                return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
        }
-       if sandboxStatus.State != runtimeapi.PodSandboxState_SANDBOX_READY {
+       if unreadyAttempt >= readyAttempt {
                klog.V(2).Infof("No ready sandbox for pod %q can be found. Need to start a new one", format.Pod(pod))
                return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
        }
```

**Comment by feiskyer** [comment]
I think it should always check the latest one. whenever there're new sandbox created, all older ones should be killed if they're still running.

**Comment by tedyu** [comment]
Can you clarify the condition for identifying latest one ?
In the above snippet, I check by highest attempt number. This should serve as the indicator for latest sandbox.

**Comment by feiskyer** [comment]
I mean creation time. See the codes here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L272.

**Comment by tedyu** [comment]
@weili10 
Can you provide more of the kubelet.log so that we can get idea how the two sandboxes statuses were formed ?

**Comment by tedyu** [comment]
@feiskyer 
In getSandboxIDByPodUID(), Attempt number is not considered.
Do you know why Attempt number is excluded in sorting criteria ?

From the code in kubeGenericRuntimeManager) podSandboxChanged, it seems Metadata.Attempt is more important.
```
		klog.V(2).Infof("No ready sandbox for pod %q can be found. Need to start a new one", format.Pod(pod))
		return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
```

**Comment by tedyu** [comment]
@weili10 
How long has your cluster been running ?

I was curious about the CreatedAt value of the second sandbox in your posting which seemed quite old.

**Comment by weili10** [comment]
> @weili10
> How long has your cluster been running ?
> 
> I was curious about the CreatedAt value of the second sandbox in your posting which seemed quite old.

The device I used doesn't have a real-time clock. So the time on that device would be reset after reboot.

**Comment by tedyu** [comment]
Since the CreatedAt value is used to order sandboxes, it is expected that this constraint is maintained across reboots.

Is there reason why the device doesn't use real-time clock ?
Please tell us more about your cluster and your use case(s).

**Comment by weili10** [comment]
> @weili10
> Can you provide more of the kubelet.log so that we can get idea how the two sandboxes statuses were formed ?

I find some logs relate to the two sandbox status before the former logs I provide.

`I0211 16:28:25.833205    3737 kuberuntime_manager.go:933] getSandboxIDByPodUID got sandbox IDs ["637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35" "b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f"] for pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)"

I0211 16:28:25.845681    3737 generic.go:397] PLEG: Write status for web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8/websocket: &{ID:01bdf80e-4c5a-4ed8-ac94-41560f6137e8 Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8 Namespace:websocket IPs:[] ContainerStatuses:[0x40006ba540] SandboxStatuses:[&PodSandboxStatus{Id:637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35,Metadata:&PodSandboxMetadata{Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Uid:01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Namespace:websocket,Attempt:0,},State:SANDBOX_NOTREADY,CreatedAt:1588267528126901235,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},},},Labels:map[string]string{io.kubernetes.pod.name: web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,io.kubernetes.pod.namespace: websocket,io.kubernetes.pod.uid: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8,},Annotations:map[string]string{},RuntimeHandler:,} &PodSandboxStatus{Id:b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f,Metadata:&PodSandboxMetadata{Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Uid:01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Namespace:websocket,Attempt:1,},State:SANDBOX_READY,CreatedAt:1455208104948964730,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},},},Labels:map[string]string{io.kubernetes.pod.name: web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,io.kubernetes.pod.namespace: websocket,io.kubernetes.pod.uid: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8,},Annotations:map[string]string{},RuntimeHandler:,}]} (err: <nil>)

I0211 16:28:25.849935    3737 kuberuntime_manager.go:933] getSandboxIDByPodUID got sandbox IDs ["637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35" "b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f"] for pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)"

I0211 16:28:25.864534    3737 status_manager.go:423] Status Manager: adding pod: "01bdf80e-4c5a-4ed8-ac94-41560f6137e8", with status: (1, {Running [{Initialized True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC ContainersNotReady containers with unready status: [container-0]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }]    192.168.0.23 192.168.0.23 [] 2016-02-11 16:28:25 +0000 UTC [] [{container-0 {nil nil &ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2020-04-30 17:25:28 +0000 UTC,FinishedAt:2020-04-30 17:28:13 +0000 UTC,ContainerID:docker://ed58fff46f3c97856d72d1f1a5798c56317a0f9f9a79a4b4e8975db48be39846,}} {nil nil &ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2020-04-30 17:25:28 +0000 UTC,FinishedAt:2020-04-30 17:28:13 +0000 UTC,ContainerID:docker://ed58fff46f3c97856d72d1f1a5798c56317a0f9f9a79a4b4e8975db48be39846,}} false 0 example.com/library/web1:1.0.0 docker-pullable://example.com/library/web1@sha256:71938ea47e48b0eb90191e723f1cd208f087bccace1df56c080bbaba7b406895 docker://ed58fff46f3c97856d72d1f1a5798c56317a0f9f9a79a4b4e8975db48be39846 0x4000bba2cd}] Burstable []}) to podStatusChannel


I0211 16:28:26.145554    3737 cpu_manager.go:211] [cpumanager] update container resources is skipped due to cpu set is empty

I0211 16:28:26.145666    3737 record.go:19] Normal Created Created container container-0

I0211 16:28:26.336739    3737 record.go:19] Normal Started Started container container-0

E0211 16:28:26.336900    3737 kuberuntime_container.go:172] Failed to create legacy symbolic link "/var/log/containers/web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket_container-0-a9280be54c46eeaee6a38087b11e082a4bc9e77341942179e0fd49a1cb99c0f1.log" to container "a9280be54c46eeaee6a38087b11e082a4bc9e77341942179e0fd49a1cb99c0f1" log "/var/log/pods/websocket_web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_01bdf80e-4c5a-4ed8-ac94-41560f6137e8/container-0/1.log": symlink /var/log/pods/websocket_web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_01bdf80e-4c5a-4ed8-ac94-41560f6137e8/container-0/1.log /var/log/containers/web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket_container-0-a9280be54c46eeaee6a38087b11e082a4bc9e77341942179e0fd49a1cb99c0f1.log: no such file or directory

I0211 16:28:26.846210    3737 generic.go:189] GenericPLEG: Relisting

I0211 16:28:26.853495    3737 generic.go:153] GenericPLEG: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8/a9280be54c46eeaee6a38087b11e082a4bc9e77341942179e0fd49a1cb99c0f1: non-existent -> running

I0211 16:28:26.856917    3737 kuberuntime_manager.go:933] getSandboxIDByPodUID got sandbox IDs ["637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35" "b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f"] for pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)"

I0211 16:28:26.877013    3737 generic.go:397] PLEG: Write status for web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8/websocket: &{ID:01bdf80e-4c5a-4ed8-ac94-41560f6137e8 Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8 Namespace:websocket IPs:[] ContainerStatuses:[0x40006b2fc0 0x40006b30a0] SandboxStatuses:[&PodSandboxStatus{Id:637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35,Metadata:&PodSandboxMetadata{Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Uid:01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Namespace:websocket,Attempt:0,},State:SANDBOX_NOTREADY,CreatedAt:1588267528126901235,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},},},Labels:map[string]string{io.kubernetes.pod.name: web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,io.kubernetes.pod.namespace: websocket,io.kubernetes.pod.uid: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8,},Annotations:map[string]string{},RuntimeHandler:,} &PodSandboxStatus{Id:b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f,Metadata:&PodSandboxMetadata{Name:web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Uid:01bdf80e-4c5a-4ed8-ac94-41560f6137e8,Namespace:websocket,Attempt:1,},State:SANDBOX_READY,CreatedAt:1455208104948964730,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},},},Labels:map[string]string{io.kubernetes.pod.name: web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8,io.kubernetes.pod.namespace: websocket,io.kubernetes.pod.uid: 01bdf80e-4c5a-4ed8-ac94-41560f6137e8,},Annotations:map[string]string{},RuntimeHandler:,}]} (err: <nil>)


I0211 16:28:26.881474    3737 kuberuntime_manager.go:933] getSandboxIDByPodUID got sandbox IDs ["637ff5c305dd6b95791ac417cf0c128ad8dd82427ca56e2247d3a3a122f94e35" "b9ef30fb7d26d26c60710e2428630fe584781c7823e0c93eb25a40e1cff8a25f"] for pod "web-always-01bdf80e-4c5a-4ed8-ac94-41560f6137e8_websocket(01bdf80e-4c5a-4ed8-ac94-41560f6137e8)"`

**Comment by weili10** [comment]
> Since the CreatedAt value is used to order sandboxes, it is expected that this constraint is maintained across reboots.
> 
> Is there reason why the device doesn't use real-time clock ?
> Please tell us more about your cluster and your use case(s).

It's just an demo board used for educational purpose. So the problem would be fixed if we use RTC or NTP service?
