### ISSUE TITLE
StatefulSet continues to try to create pods with old spec even after spec updated

### ISSUE THREAD

**Issue by roy-work** [kubernetes/kubernetes#90607]
**What happened**: We attempted to remove a `serviceAccount` from a `StatefulSet` by removing the `serviceAccount` from the `spec.template` of the `StatefulSet`, and by removing the `ServiceAccount` itself.

However, due to the unfixed https://github.com/kubernetes/kubernetes/issues/72519, while the removal of the `ServiceAccount` itself succeeded, the removal of the reference to it on the `StatefulSet` was ignored by `kubectl apply`.

While I think that #72519 is a bug & should be fixed, it should have been fine enough, as we thought we knew how to work around it: manually specify `serviceAccount: null` in the manifest, & `kubectl apply` that.

After attempting that fix, the `serviceAccount[Name]` was successfully removed from the `StatefulSet` manifest. However, the `StatefulSet` continues to emit,

```
  Warning  FailedCreate  9m33s (x34 over 3h32m)  statefulset-controller  create Pod <STS name>-1 in StatefulSet <STS name> failed error: pods "<STS name>-1" is forbidden:
 error looking up service account <namespace>/<old service acct name>: serviceaccount "<old service acct name>" not found
```

Yet, we can confirm that no service account is being requested:

```
» kubectl get sts -n test <STS name> -o json | jq .spec | grep serviceAccount
» # no output, indicating it was not present.
```

**What you expected to happen**: The `StatefulSet` should stop attempting to create the pod with a `serviceAccount` that does not match the template it has been given.

**How to reproduce it (as minimally and precisely as possible)**: the above is the most minimal test case I have at this time.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.10
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`): <unknown, Azure>
- Kernel (e.g. `uname -a`): <unknown, Azure>
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by kow3ns** [comment]
I can not reproduce this either
