### ISSUE TITLE
Updates with client-go dropping ManagedFieldsEntry.FieldsType breaks

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#90610]
https://github.com/kubedb/issues/issues/739

[`ManagedFieldsEntry. FieldsType`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1123) is not defaulted and can be dropped by pre 1.15 versions of client-go (since the field didn't exist at that time). Unfortunately, sending an update will then result in a validation failure since the field is required.

We should figure out what to do when we receive a `ManagedFieldsEntry` whose `FieldsType` is not set.

/sig api-machinery
/priority important-soon

**Comment by apelisse** [comment]
The bug is probably present since 1.16, but we haven't detected it before 1.18 because it's more likely to happen (now that most objects have managed fields, rather than before when barely any had it).

**Comment by apelisse** [comment]
A much simpler solution is to use a post-1.16 client-go? I don't think upgrading to 1.18 is necessary.

**Comment by apelisse** [comment]
A rather radical method would be to just drop the whole ManagedFields thing when it misses the field. I think in general we drop ManagedFields when it's invalid anyways.

**Comment by apelisse** [comment]
Alternately, we could also try to load the ManagedFields using the only type we have right now.

**Comment by liggitt** [comment]
> Alternately, we could also try to load the ManagedFields using the only type we have right now.

not sure what you mean by this

> A rather radical method would be to just drop the whole ManagedFields thing when it misses the field. I think in general we drop ManagedFields when it's invalid anyways.

I would expect a managedFields without fieldsType set to be more likely to be a pre-1.16 client-go client than a client that is trying to manipulate the managedFields structure and doesn't know to set that field properly. Treating that scenario the same way we treat a request that omits managedFields entirely seems reasonable to me.

**Comment by apelisse** [comment]
> I would expect a managedFields without fieldsType set to be more likely to be a pre-1.16 client-go client than a client that is trying to manipulate the managedFields structure and doesn't know to set that field properly. Treating that scenario the same way we treat a request that omits managedFields entirely seems reasonable to me.

To be honest, we do the same thing in both cases.

> Alternately, we could also try to load the ManagedFields using the only type we have right now.

Well, the `FieldsType` has only one value today, so if it's missing, we still really know what it should be doing anyway ...

**Comment by liggitt** [comment]
> Well, the `FieldsType` has only one possible value today, so if it's missing, we still really know what it's supposed to be anyway ...

if we add a second possible value, we would still need to tolerate a client that worked prior to 1.16 dropping the fieldsType field

**Comment by apelisse** [comment]
Yes, I think that sort of goes back to what I was trying to say here:

> Alternately, we could also try to load the ManagedFields using the only type we have right now.

We can try to load it with the one deserializer we have and see if it works. When we have two, we could possibly try both deserializers.

**Comment by liggitt** [comment]
is falling back to the old object's managedFields simpler/safer?

**Comment by apelisse** [comment]
It's probably simpler yes.

**Comment by apelisse** [comment]
We have to make the `FieldsType` not required, and it's probably an if-statement somewhere.

**Comment by liggitt** [comment]
bumping priority since this impacts API compatibility and we would expect to pick a fix back to 1.16-1.18
