### ISSUE TITLE
Unnecessary scheduling attempt

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#90616]
When there is not any node fits for an incoming Pod, scheduler firstly tries to [put it to internal unschedulableQ or backoffQ](https://github.com/kubernetes/kubernetes/blob/429aefa2e6e1d41cab892703733cf6fdd9919561/pkg/scheduler/factory.go#L504). And right after that, scheduler [updates the Pod's status as unschedulable](https://github.com/kubernetes/kubernetes/blob/429aefa2e6e1d41cab892703733cf6fdd9919561/pkg/scheduler/scheduler.go#L391-L396) via API server:

But unfortunately, the preceding step is running as a [goroutine](https://github.com/kubernetes/kubernetes/blob/429aefa2e6e1d41cab892703733cf6fdd9919561/pkg/scheduler/factory.go#L487), which in practice can happen after the latter step. Or even worse, the preceding step may occur after the PodUpdate event comes in. In this case, the logic that scheduler intentionally bypasses the updated Pod doesn't work (L439~L446 below won't be reached):

https://github.com/kubernetes/kubernetes/blob/429aefa2e6e1d41cab892703733cf6fdd9919561/pkg/scheduler/internal/queue/scheduling_queue.go#L436-L452

Then the Pod gets added to activeQ (L452 above) and will soon be retried - which in most cases is a waste as it was just tried earlier.

**Reproduce steps:**

See https://github.com/kubernetes/kubernetes/issues/90616#issuecomment-621520874.

**Solutions:**

- Aggressive option. Change the [goroutine](https://github.com/kubernetes/kubernetes/blob/429aefa2e6e1d41cab892703733cf6fdd9919561/pkg/scheduler/factory.go#L487) to be synchronous call.
- Safe option.  Update `PriorityQueue#Update()` to guard the case: even if a Pod is not in unschedulingQ, it may also be unnecessary to be added into activeQ.

/sig scheduling
/priority important-longterm

**Comment by Huang-Wei** [comment]
We can use an integration test to reproduce this:

```diff
diff --git a/test/integration/scheduler/framework_test.go b/test/integration/scheduler/framework_test.go
index cf54a938e87..48798044520 100644
--- a/test/integration/scheduler/framework_test.go
+++ b/test/integration/scheduler/framework_test.go
@@ -1397,7 +1397,7 @@ func TestFilterPlugin(t *testing.T) {
 		scheduler.WithFrameworkOutOfTreeRegistry(registry))
 	defer testutils.CleanupTest(t, testCtx)
 
-	for _, fail := range []bool{false, true} {
+	for _, fail := range []bool{true} {
 		filterPlugin.failFilter = fail
 		// Create a best effort pod.
 		pod, err := createPausePod(testCtx.ClientSet,
@@ -1416,6 +1416,8 @@ func TestFilterPlugin(t *testing.T) {
 			}
 		}
 
+		t.Logf("[DEBUG] filterPlugin.numFilterCalled = %v", filterPlugin.numFilterCalled)
+
 		if filterPlugin.numFilterCalled == 0 {
 			t.Errorf("Expected the filter plugin to be called.")
 		}
```

And then run the "TestFilterPlugin" test for 10 times, on my local dev machines, it shows like:

```script
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 4
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 4
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 4
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
    framework_test.go:1419: [DEBUG] filterPlugin.numFilterCalled = 2
```

The number shows Filter() function being called, as the test setups 2 node, so only 2 calls are expected, but you can see that 30% of the results shows 4 calls, and also there is error msa when adding the Pod to unschedubleQ:

```
E0429 16:14:44.771547   92995 factory.go:505] pod: filter-plugin929b921d-45bc-4472-810c-1622dfbe9331/test-pod is already present in the active queue
``` 

It also proves the racing symptom.

**Comment by alculquicondor** [comment]
I think I prefer option 1.
It looks like the only reason why it's a goroutine instead of a synchronous call is the API request to get an updated pod.

But I think we shouldn't need it. If an update comes in while we were doing a scheduling cycle (with more changes than just status), the pod should go in the active queue, and then we don't need to add it to the unschedulable queue (and that shouldn't be an error). If otherwise we didn't get any updates, we just add the pod to the unschedulable queue.

This would save us not just the unnecessary scheduling attempt but an API call :)

**Comment by Huang-Wei** [comment]
> I think I prefer option 1.

I checked the asynchronous call's history, it was introduced 6 years ago... And the comment also assumed it was for temporary use. I think we should enough reasons to optimize it, just need to be cautious for regression. I will craft a PR.

> But I think we shouldn't need it.

I feel the same.
