### ISSUE TITLE
Add support for using parameters and ENV variables to PostStart/PreStop handler

### ISSUE THREAD

**Issue by ZhiFeng1993** [kubernetes/kubernetes#90624]
**What would you like to be added**:
Currently, PostStart and PreStop hook are not supporting taking arguments and ENV variables like a container does. I'd like to add this functionality into them. 

**Why is this needed**:
This feature could extend flexibility in container lifecycle hooks.

**Comment by tedyu** [comment]
Can you describe your use case in more detail ?

/sig node

**Comment by ZhiFeng1993** [comment]
@tedyu  sure. 

So our use case is to use a K8s Deployment to do health-check for a long-running job running in another cluster. We also hope by cleaning up the health-check Pod, the long-running job it monitors will be cleaned up too by a PreStop hook. That requires taking parameters(like job name) in the PreStop hook that K8s doesn't support in the meantime. 

An example yaml file is like:
`apiVersion: v1
kind: Pod
metadata:
  name: foo-test
spec:
  containers:
    - name: foo-start
      image: <docker-registry>:dev
      env:
         - name: JOB_NAME
            value: $JOB_NAME
         - name: EMR_CLUSTER
            value: $EMR_CLUSTER      
      imagePullPolicy: Always
      command: ["/bin/sh","-c"]
      args: ["bash foo_healthcheck.sh" $(JOB_NAME) $(EMR_CLUSTER)]
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","kill_job.sh"]`

As you might notice in the above example, regular container spec supports taking parameters(like JOB_NAME and EMR_CLUSTER), while preStop doesn't. I'd like to add this feature.

**Comment by tedyu** [comment]
Thanks for the example.
I wonder why the termination of long-running job is contingent on the monitoring job.
The monitoring job may not function normally but long-running job should still run (assuming it is important).

**Comment by ZhiFeng1993** [comment]
Yes this is a valid point. Associating the healthcheck job with a long-running job is not a best practice, also because of preStop hook is lacking this feature, we had to give up this option eventually. But there are some other cases where we'd like to bind the healthcheck task with(like another healthcheck task). Or we'd like to use the deletion of a Pod as a trigger to some other tasks. 

My point here is: the capability of taking parameters of a postStart/preStop hook is necessary. Does this make sense to you?

**Comment by tedyu** [comment]
Conceptually I agree with you.

**Comment by vsxen** [comment]
Get start & stop msg from event API ？

**Comment by ZhiFeng1993** [comment]
@vsxen I don't get it. Mind elaborating?
