### ISSUE TITLE
Admission that tries to add an annotation fails when annotations is nil

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#90623]
a modifying admission webhook that produces this patch:
```
	{
		"op":    "add",
		"path":  "/metadata/annotations/foo"
		"value": "bar",
	}
```
fails when using `kubectl run`
```
kubectl run --generator=run-pod/v1  --attach test-deploy --image=busybox --labels="team=sre,project=datadog" ls
Error from server (InternalError): Internal error occurred: jsonpatch replace operation does not apply: doc is missing path: /metadata/annotations/foo
```

it even fails when try to initialize annotations before setting:

```
{"op":"add","path":"/metadata/annotations","value":"{}"}
```

this is on 1.17

**Comment by liggitt** [comment]
do you have the full patch your webhook is returning to initialize and set the annotations?

**Comment by grosser** [comment]
```
[
{"op":"add","path":"/metadata/annotations","value":"{}"},
{"op":    "add","path":  "/metadata/annotations/foo","value": "bar"}
]
```

**Comment by grosser** [comment]
... if that payload worked it would still:
- leave a race-condition open where multiple webhooks could try to reset annotations
- still be a trap for anyone building admission webhooks

... so ideally it would work without the reset to `{}`

**Comment by liggitt** [comment]
> If that payload worked it would still leave a race-condition open where multiple webhooks could try to reset annotations

mutating webhooks are run sequentially, so there's no race

> ideally it would work without the reset to {}

Unfortunately, jsonpatch doesn't give a single-operation way to optionally initialize a map and set a child while leaving other members intact if the map already exists.

If the existing object has no annotations, either of these would do what you want (note there are no quotes around the `{}` value):

option 1 - init then set:
```
[
  {"op":"add","path":"/metadata/annotations","value":{}},
  {"op":"add","path":"/metadata/annotations/foo","value": "bar"}
]
```
option 2 - set the entire annotations map:
```
[{"op":"add","path":"/metadata/annotations","value":{"foo":"bar"}]
```

If the existing object has annotations, then the following works:
```
[{"op":"add","path":"/metadata/annotations/foo","value":"bar"]
```

**Comment by grosser** [comment]
thx, I'll try that ... yeh I think the `"{}"` is what got me 🤦
