### ISSUE TITLE
Incomplete list of operations for admission webhook

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#90632]
**What happened**:
Working on other doc bugs, I went looking for what calls admission plugins.  I found four call sites for validating plugins, documented in https://github.com/kubernetes/website/issues/20673 .  They correspond to the verbs CONNECT, CREATE, DELETE, and UPDATE.  But only two of those verbs are documented at https://github.com/kubernetes/kubernetes/blob/863ce9726e0aa617f03332f42ff3cebb7abe8fc0/staging/src/k8s.io/api/admissionregistration/v1/types.go#L465

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Looks like docs are correct in https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-rules and https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#request and

**Comment by liggitt** [comment]
The API doc can be updated to call out all four operations and clarify that "all" means "all four admission operations"
