### ISSUE TITLE
Very few PRs have merged in the past few days

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#90647]
https://monitoring.prow.k8s.io/d/d69a91f76d8110d3e72885ee5ce8038e/tide-dashboard?orgId=1&from=now-30d&to=now

https://prow.k8s.io/tide-history?repo=kubernetes%2Fkubernetes&branch=master

Tide is continually retesting PR's but unable to merge them due to flakes or failures.  Batches are more likely to encounter them, and so are basically never merging.  This kills the merge velocity of this repo.

@dims is acting on the belief that pull-kubernetes-cross and pull-kubernetes-verify are timing out (ref: https://kubernetes.slack.com/archives/C09QZ4DQB/p1588244968367900)

Verify timing out may be the same as https://github.com/kubernetes/kubernetes/issues/87807 but on a larger scale since it's a pr job instead of ci job

In https://github.com/kubernetes/kubernetes/pull/90639#issuecomment-621810350 @liggitt proposed splitting up the verify job

/assign @dims @spiffxp 
/sig testing
/priority critical-urgent
/kind flake

**Comment by spiffxp** [comment]
FYI @kubernetes/ci-signal

**Comment by dims** [comment]
![image](https://user-images.githubusercontent.com/23304/80736826-aabc5c80-8ae0-11ea-8b72-7eb17632bca2.png)

**Comment by dims** [comment]
Another instructive link is https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=batch&state=failure

**Comment by justaugustus** [comment]
FYI @kubernetes/release-team @kubernetes/release-engineering

**Comment by spiffxp** [comment]
Now that https://github.com/kubernetes/test-infra/pull/17454 has merged I think we're waiting to see if verify takes less time

**Comment by spiffxp** [comment]
We had a batch of 4 merge, I suspect many of the others may no longer qualify as eligible since they don't have the new pull-kubernetes-remake-files test

**Comment by spiffxp** [comment]
A 15 PR batch merged in around 12:45am PT today

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
Downgrading priority as we seem to be back at an expected pace.  Leaving open for the weekend in case there is remaining cleanup to be done

**Comment by dims** [comment]
we are out of the woods.

/close
