### ISSUE TITLE
Reduce the number of calls to GCE API (for clusters on GCE) coming from cloud node-controller

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#90652]
For external cloud provider - Kubelet setting the TaintExternalCloudProvider taint: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L266

The results in calling `initializeNode` function in cloud node-controller:
https://github.com/kubernetes/kubernetes/blob/5c276a451d64d161b21d70042d93f4c4b8e3201d/pkg/controller/cloud/node_controller.go#L323

This (in a healthy case) sends 4 GCE API calls to:
1. get node addresses: https://github.com/kubernetes/kubernetes/blob/5c276a451d64d161b21d70042d93f4c4b8e3201d/pkg/controller/cloud/node_controller.go#L439 (as part of getNodeModifier call)
2. get instance type:
https://github.com/kubernetes/kubernetes/blob/5c276a451d64d161b21d70042d93f4c4b8e3201d/pkg/controller/cloud/node_controller.go#L452 (as part of getNodeModifiers call)
3. get instance:
https://github.com/kubernetes/kubernetes/blob/5c276a451d64d161b21d70042d93f4c4b8e3201d/pkg/controller/cloud/node_controller.go#L233 (as part of updateNodeAddresses call)
4. get node addresses (again):
https://github.com/kubernetes/kubernetes/blob/5c276a451d64d161b21d70042d93f4c4b8e3201d/pkg/controller/cloud/node_controller.go#L242 (as part of updateNodeAddresses call)

All those requests are read requests and could be replaced by a single call.
We could do that by introducing a simple struct like:
```
type InstanceMetadata struct {
  ProviderID ...
  Type ...
  NodeAddresses ...
}
```
and adding a method (or rather replacing the existing InstanceTypeByProviderID which is used only for this purpose) to Instances cloud-provider interface;
```
func InstanceMetadataByProviderID(...) (*InstanceMetadata, error)
```

With that change, we would be able to replace all that 4 calls with just a single API call.

This would be useful especially for creating large clusters (like 5k nodes), which may saturate the quota for API calls for quite some time.

This is quite significant size of refactoring, though it should be relatively mechanical task to do.

/sig cloud-provider
/sig scalability
/priority important-longterm

/help-wanted

@mborsz @mm4tt - FYI

**Comment by tedyu** [comment]
The InstanceMetadataByProviderID would be added to every cloud provider, such as aws, azure, etc.
right ?

**Comment by gongguan** [comment]
/assign
Hi @tedyu , if you're interested in it, I can work with you.

**Comment by wojtek-t** [comment]
> The InstanceMetadataByProviderID would be added to every cloud provider, such as aws, azure, etc. right ?

Yes - we need to do that (which is why I wrote it's quite significant refectoring). It also makes reviews harder, because we will need to ask maintainers of all cloud-providers.
So it would be good to separate changes to different cloud providers into separate commits.

**Comment by gongguan** [comment]
I have one question:
`getNodeAddressesByProviderIDOrName` and `getInstanceTypeByProviderIDOrName` first query by providerID, if failed then query by nodeName. While the logic in `ensureNodeExistsByProviderID` is conversely(if providerID is nil, get providerID by nodeName, then ensure its existence by providerID).
If we merge these three method into `InstanceMetadataByProviderID`, how to deal with the query sequence of nodeName and providerID?

**Comment by wojtek-t** [comment]
I bet it's a consequence of different people adding different code paths.
Those conceptually seem to be the same to me. Unifying this will be additional benefit from this change imho.
So I would say that choose whatever is easier to implement.

**Comment by andrewsykim** [comment]
I think https://github.com/kubernetes/kubernetes/pull/93569 will be the last PR required for this. 

One other optimization that can be made is to cache the instance metadata but I think that's a provider specific implementation

**Comment by wojtek-t** [comment]
Plus enabling it for GCE if we decide to remove it from the first PR. But yeah, in general I agree.

**Comment by wojtek-t** [comment]
@gongguan - can you please address https://github.com/kubernetes/kubernetes/pull/94846#discussion_r490974724 ?

**Comment by gongguan** [comment]
I think this issue has been resolved, feel free to reopen it.

/close
