### ISSUE TITLE
staging: test.Fatal() can only be used in test goroutine instead of its child

### ISSUE THREAD

**Issue by BurtonQin** [kubernetes/kubernetes#90651]
**What happened**:
`testing.Fatal()/FailNow()/SkipNow()/...` can only be used in test goroutine.
`t.Fatal()/Fatalf()/FailNow()` "[must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test.](https://golang.org/pkg/testing/#T.FailNow)"

There are four cases related to this kind of bug:
- [ ] staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go:623
https://github.com/kubernetes/kubernetes/blob/c71a25e91209714463664474428ab10dfc1ad6e3/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go#L613-L623
- [ ] staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go:691
https://github.com/kubernetes/kubernetes/blob/c71a25e91209714463664474428ab10dfc1ad6e3/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go#L681-L691
- [ ] staging/src/k8s.io/apiserver/pkg/storage/cacher/caching_object_test.go:152
https://github.com/kubernetes/kubernetes/blob/c71a25e91209714463664474428ab10dfc1ad6e3/staging/src/k8s.io/apiserver/pkg/storage/cacher/caching_object_test.go#L137-L152
- [ ] staging/src/k8s.io/apiserver/pkg/storage/tests/cacher_test.go:930
https://github.com/kubernetes/kubernetes/blob/c71a25e91209714463664474428ab10dfc1ad6e3/staging/src/k8s.io/apiserver/pkg/storage/tests/cacher_test.go#L921-L930

**What you expected to happen**:
--
**How to reproduce it (as minimally and precisely as possible)**:
--
**Anything else we need to know?**:
--
**Environment**:
master branch, commit c71a25e91209714463664474428ab10dfc1ad6e3

**Comment by BenTheElder** [comment]
/sig apimachinery
/remove-sig testing
SIG testing owns the CI, frameworks, guidance etc. SIG apimachinery owns their tests.

**Comment by BenTheElder** [comment]
@kubernetes/sig-api-machinery-bugs
