### ISSUE TITLE
[Failing Test] gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90668]
**Which jobs are failing**:

> gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)

**Which test(s) are failing**:

> Overall
> Up

**Since when has it been failing**:

> 04-30 10:00 PDT

**Testgrid link**:

> https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:

> W0501 09:18:42.774] scp: /var/log/kube-addon-manager.log*: No such file or directory
> W0501 09:18:42.774] scp: /var/log/konnectivity-server.log*: No such file or directory
> W0501 09:18:42.775] scp: /var/log/fluentd.log*: No such file or directory
> W0501 09:18:42.775] scp: /var/log/kubelet.cov*: No such file or directory
> W0501 09:18:42.775] scp: /var/log/startupscript.log*: No such file or directory
> W0501 09:18:42.780] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing

**Comment by hasheddan** [comment]
I am seeing the same error listed above on successful runs as well so I think the issue might be elsewhere
