### ISSUE TITLE
Which component guarantees that the modification of the configmap conforms to the configmap format?

### ISSUE THREAD

**Issue by leexiaominghub** [kubernetes/kubernetes#90661]
ie, when I add "- --v=4" to kube-proxy as flag after "--config" flag, it report an error and forbid this modification, however,  it is ok when put it just after kubeproxy.  It makes me confused. 

does apiserver do this? and which port of apiserver do this ?thanks

**What would you like to be added**:

**Why is this needed**:

**Comment by neolit123** [comment]
> ie, when I add "- --v=4" to kube-proxy as flag after "--config" flag, it report an error and forbid this modification, however, it is ok when put it just after kubeproxy. It makes me confused.

can you show the full examples?

> does apiserver do this? and which port of apiserver do this ?thanks

`--config` errors for kube-proxy are managed by kube-proxy.

/sig network
/remove-kind feature
/kind bug
/priority awaiting-more-evidence

**Comment by neolit123** [comment]
> can you show the full examples?

full examples, as in the full command lines and what errors are you seeing.

**Comment by rikatz** [comment]
/assign

@leexiaominghub as asked previously, needs more information.

Can you also provide further information as how your cluster was installed, what's kubernetes version, which OS, etc

/remove-kind bug
/triage needs-information
/remove-priority awaiting-more-evidence

**Comment by rikatz** [comment]
@leexiaominghub due to lack of information I'm closing this issue. Please feel free to reopen and mark me if you have any further problem or evidence on this!

Thank you!!

/close
