### ISSUE TITLE
Kubelet sending thousands of request and CPU usage 100% 

### ISSUE THREAD

**Issue by gaetansnl** [kubernetes/kubernetes#90666]
**What happened**:
Kubelet CPU usage on one host becoming crazy. The other node is fine.
**What you expected to happen**:
Nothing, the server wasn't used.
**How to reproduce it (as minimally and precisely as possible)**:
Here is a screenshot of the buggy node
![QYFZ5LNXc8f8RaU83ioiqYJ0B](https://user-images.githubusercontent.com/8348807/80791695-b6685b80-8b92-11ea-9e47-117f5530af54.png)

In kubelet logs, it's simply sending thousands of requests to every endpoint on the cluster. All of them with response `use of closed connection`.
Rebooting solved the problem

![7rldH5ppI0jjn7uWty82GnUnM](https://user-images.githubusercontent.com/8348807/80791908-5b833400-8b93-11ea-9d74-aacb12573e1f.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
2 nodes, 12 cores, 20GB RAM
- OS (e.g: `cat /etc/os-release`):
```
NAME="RancherOS"
VERSION=v1.4.2
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.2
PRETTY_NAME="RancherOS v1.4.2"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```
- Kernel (e.g. `uname -a`): `Linux dev-node 4.14.73-rancher #1 SMP Thu Oct 4 00:19:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Rancher

**Comment by tedyu** [comment]
Can you give snippet of the log showing 'use of closed connection' ?

Next time this occurs, please get profile of the kubelet process.

What version of Calico are you using ? (I assume all other nodes have calico as well)

Thanks

**Comment by gaetansnl** [comment]
![ciDadPipirILsbf52GVjnmLlb](https://user-images.githubusercontent.com/8348807/80824129-1afcd800-8bde-11ea-9d09-5add6483ade5.png)

And I use `rancher/calico-node:v3.13.0`

**Comment by tedyu** [comment]
Have you seen #87615 ?

In the future, please paste text instead of image - text is easier to search.

**Comment by gaetansnl** [comment]
It happened again, but I can't take a profile or get logs because the server is becoming too slow. It took long time just to connect to SSH.
