### ISSUE TITLE
AWS: Error creating security policy on load balancer when using custom SSL negotiation policy.

### ISSUE THREAD

**Issue by TonyLovesDevOps** [kubernetes/kubernetes#90677]
**What happened**: I received the error `failed to ensure load balancer: error creating security policy on load balancer: "ValidationError: Invalid Reference Security Policy: k8s-SSLNegotiationPolicy-test` when using the `service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy` annotation to reference a custom policy, as part of following [the instructions in this comment](https://github.com/kubernetes/kubernetes/pull/54507#issuecomment-339329158).

**What you expected to happen**:
I expected the SSL negotiation policy specified in `service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy` to be applied to the ELB.

**How to reproduce it (as minimally and precisely as possible)**:

Here's the manifest I'm using:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.10
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<redacted>"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
```

1. Save above snippet as `echoservice.yml`
2. Run `kubectl apply -f echoservice.yml` to have k8s create the ELB.
3. Query the initial ELB policy configuration (everything is fine at this point):
```bash
$ ELB_NAME=$(kubectl get service echoserver -o json | jq -r '.status.loadBalancer.ingress[0].hostname' | cut -d '-' -f1)
$ aws elb describe-load-balancers \
    --load-balancer-name $ELB_NAME \
    --output json \
    --query 'LoadBalancerDescriptions[0].{Name:LoadBalancerName,ListenerDescriptions:ListenerDescriptions,Policies:Policies}'
{
    "Name": "a3855b4f6966d440894169015d47596d",
    "ListenerDescriptions": [
        {
            "Listener": {
                "Protocol": "HTTPS",
                "LoadBalancerPort": 443,
                "InstanceProtocol": "HTTP",
                "InstancePort": 30884,
                "SSLCertificateId": "<redacted>"
            },
            "PolicyNames": [
                "ELBSecurityPolicy-2016-08"
            ]
        }
    ],
    "Policies": {
        "AppCookieStickinessPolicies": [],
        "LBCookieStickinessPolicies": [],
        "OtherPolicies": [
            "ELBSecurityPolicy-2016-08"
        ]
    }
}
```
4. Create a custom security policy on the ELB following [the instructions in this comment](https://github.com/kubernetes/kubernetes/pull/54507#issuecomment-339329158):
```bash
$ ELB_NAME=$(kubectl get svc echoserver -o json | jq -r '.status.loadBalancer.ingress[0].hostname' | cut -d '-' -f1)
$ aws elb create-load-balancer-policy \
    --load-balancer-name $ELB_NAME \
    --policy-name k8s-SSLNegotiationPolicy-test \
    --policy-type-name SSLNegotiationPolicyType \
    --policy-attributes  AttributeName=Protocol-TLSv1.2,AttributeValue=true AttributeName=DHE-RSA-AES256-SHA256,AttributeValue=true AttributeName=Server-Defined-Cipher-Order,AttributeValue=true
```
5. Apply the `service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy` annotation to the service in order to use the new negotiation policy:
```bash
$ kubectl patch service echoserver --patch '{"metadata": {"annotations": {"service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy": "k8s-SSLNegotiationPolicy-test"}}}'
```
6. Query the updated ELB policy configuration:
```bash
$ ELB_NAME=$(kubectl get service echoserver -o json | jq -r '.status.loadBalancer.ingress[0].hostname' | cut -d '-' -f1)
$ aws elb describe-load-balancers \
    --load-balancer-name $ELB_NAME \
    --output json \
    --query 'LoadBalancerDescriptions[0].{Name:LoadBalancerName,ListenerDescriptions:ListenerDescriptions,Policies:Policies}'
{
    "Name": "a3855b4f6966d440894169015d47596d",
    "ListenerDescriptions": [
        {
            "Listener": {
                "Protocol": "HTTPS",
                "LoadBalancerPort": 443,
                "InstanceProtocol": "HTTP",
                "InstancePort": 30884,
                "SSLCertificateId": "<redacted>"
            },
            "PolicyNames": [
                "ELBSecurityPolicy-2016-08"
            ]
        }
    ],
    "Policies": {
        "AppCookieStickinessPolicies": [],
        "LBCookieStickinessPolicies": [],
        "OtherPolicies": [
            "k8s-SSLNegotiationPolicy-test",
            "ELBSecurityPolicy-2016-08"
        ]
    }
}
```
Note that `ELBSecurityPolicy-2016-08` is still active for `PolicyNames`, which is incorrect - it should be `k8s-SSLNegotiationPolicy-test`.

7. Look at events:
```bash
$ kubectl -n default get events --sort-by=.metadata.creationTimestamp
39s         Warning   SyncLoadBalancerFailed   service/echoserver   Error syncing load balancer: failed to ensure load balancer: error creating security policy on load balancer: "ValidationError: Invalid Reference Security Policy: k8s-SSLNegotiationPolicy-test. Use DescribeLoadBalancerPolicies API to list valid security policies.\n\tstatus code: 400
```
8. Logs from the controller manager:
```
I0501 15:45:42.514945       1 aws_loadbalancer.go:1427] Creating SSL negotiation policy 'k8s-SSLNegotiationPolicy-k8s-SSLNegotiationPolicy-test' on load balancer
E0501 15:45:42.552599       1 service_controller.go:255] error processing service default/echoserver (will retry): failed to ensure load balancer: error creating security policy on load balancer: "ValidationError: Invalid Reference Security Policy: k8s-SSLNegotiationPolicy-test. Use DescribeLoadBalancerPolicies API to list valid security policies.\n\tstatus code: 400, request id: 7ac02fbe-39b0-4042-9ed7-53c8274c567c"
```

**Anything else we need to know?**:

1. I believe the root issue is that kubernetes tries to [create its own custom policy named k8s-SSLNegotiationPolicy-<reference-policy-name> to apply to the ELB](https://github.com/kubernetes/kubernetes/blob/v1.16.8/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L1429-L1436), using the value of the service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy annotation. However, _custom load balancer policies cannot be used as a reference security policy_. Only AWS’s predefined list of security policies can be used as reference policies.

Attempting the same API call using the AWS CLI fails with the same error:
```bash
$ aws elb create-load-balancer-policy --load-balancer-name $ELB_NAME --policy-name foo --policy-type-name SSLNegotiationPolicyType --policy-attributes AttributeName=Reference-Security-Policy,AttributeValue=k8s-SSLNegotiationPolicy-test

An error occurred (ValidationError) when calling the CreateLoadBalancerPolicy operation: Invalid Reference Security Policy: k8s-SSLNegotiationPolicy-test. Use DescribeLoadBalancerPolicies API to list valid security policies.
```

One possible fix would be to change the code to _not_ create an SSL negotiation policy for the ELB if `service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy` is specified, but instead to just apply that policy to the ELB.

2. I like turtles (but only sea turtles.)

**Environment**: AWS EKS 1.16
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS EKS 1.16
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by TonyLovesDevOps** [comment]
/sig cloud-provider

@k8s-ci-robot I have no idea what I'm doing but I trust that you have this in hand.

**Comment by Redm0nd** [comment]
Just from looking at the comment [here](https://github.com/kubernetes/kubernetes/pull/54507#issuecomment-339329158)

Have you attempted to annotate with just:
`kubectl patch service echoserver --patch '{"metadata": {"annotations": {"service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy": "test"}}}'` instead of `k8s-SSLNegotiationPolicy-test`?

Curious as the AWS CLI command uses k8s-SSLNegotiationPolicy-test, however the comment says to only annotate with the "<my-policy-name>"
