### ISSUE TITLE
[Flaky Test] capg-conformance-v1alpha3-k8s-master (ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90686]
**Which jobs are failing**:
> capg-conformance-v1alpha3-k8s-master (ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts) 

**Which test(s) are failing**:
> Overall

**Since when has it been failing**:
> 05-01 18:11 PDT

**Testgrid link**:
> https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1alpha3-k8s-master

**Reason for failure**:
> cluster.cluster.x-k8s.io "test1" deleted
> Error from server (NotFound): clusters.cluster.x-k8s.io "test1" not found
> kind delete cluster --name=clusterapi || true
Deleting cluster "clusterapi" ...
> ERROR: (gcloud.compute.forwarding-rules.delete) Could not fetch resource:
 > - The resource 'projects/kube-gce-upg-1-4-1-5-upg-mas/global/forwardingRules/test1-> apiserver' was not found
> ERROR: (gcloud.compute.target-tcp-proxies.delete) Some requests did not succeed:
>  - The resource 'projects/kube-gce-upg-1-4-1-5-upg-mas/global/targetTcpProxies/test1-apiserver' was not found
> ERROR: (gcloud.compute.backend-services.delete) Some requests did not succeed:
>  - The resource 'projects/kube-gce-upg-1-4-1-5-upg-mas/global/backendServices/test1-apiserver' was not found
> ERROR: (gcloud.compute.health-checks.delete) Could not fetch resource:
> - The resource 'projects/kube-gce-upg-1-4-1-5-upg-mas/global/healthChecks/test1-apiserver' was not found

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing
/project 11 To do

**Comment by hkamel** [comment]
Successful since last two runs, update it from Failing to Flaky

/retitle [Flaky Test] capg-conformance-v1alpha3-k8s-master (ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts)

/remove-kind failing-test
/kind flake

**Comment by ncdc** [comment]
I looked into some failing vs passing runs from the past couple of days.

For the failing runs, the control plane node fails to register with the apiserver. From the kubelet logs:

```
May 15 15:11:11 test1-control-plane-bsd82 kubelet[5732]: E0515 15:11:11.357899    5732 kubelet_node_status.go:91] Unable to register node "test1-control-plane-bsd82.c.k8s-gce-gci-mstr-1-6-ctl-skew.internal" with API server: Node "test1-control-plane-bsd82.c.k8s-gce-gci-mstr-1-6-ctl-skew.internal" is invalid: metadata.labels: Invalid value: "test1-control-plane-bsd82.c.k8s-gce-gci-mstr-1-6-ctl-skew.internal": must be no more than 63 characters
```

For a passing run, I see something like this:

```
Attempting to register node test1-control-plane-k6xtk.c.gce-up-c1-4-glat-up-clu-n.internal
```

The invalid value from above is 67 characters. The passing node name is 63 characters.

I'm not sure what label key is being set that matches the node name, though? I'm also curious why the nodes have names containing things like `k8s-gce-gci-mstr-1-6-ctl-skew` and `gce-up-c1-4-glat-up-clu-n` given this is a test scenario that stands up a brand new cluster and runs conformance tests against it?

cc @dims @vincepri

**Comment by ncdc** [comment]
I [chatted](https://kubernetes.slack.com/archives/C09QZ4DQB/p1589569142175900) with @BenTheElder and I think the conclusion is that CAPG Prow jobs may end up running in one of several different GCP projects, whose names are of varying lengths. We use the `local-hostname` value from instance metadata when registering the node, and that is of the format `<instance name>.c.<project name>.internal`.

If the combination of the length's of instance name and project name is more than 63 characters, we can't register a node for that instance (today, at least).

**Comment by ncdc** [comment]
cc @detiber

**Comment by justinsb** [comment]
I reopened an old k8s issue that pointed out that it's inconsistent to have an official label `kubernetes.io/hostname` yet have that limited to 63 characters.

I'm not entirely sure what we should do here TBH.  The right answer is probably to deprecate the label and replace it with an annotation (which is 64KB), or we could simply stop setting the label.  I don't know if anyone actually uses the hostname label.

For this particular problem, I'd say our best answer is to stay under 64 characters until node/apimachinery figure it out.

I imagine users are going to hit this as well, so I suspect we should just change the hostname to be just the first component (i.e. just the machine name).

**Comment by ncdc** [comment]
>  I suspect we should just change the hostname to be just the first component (i.e. just the machine name)

How do we do that? And will that break the GCP cloud provider for Kubernetes (does it expect the hostname to be the current format)?

**Comment by justinsb** [comment]
There wasn't a lot of documentation on what the label was actually used for, if anything, so I don't know!  I don't think anything will break, and I'll do the same thing in kops if we're not doing so already (misery loves company, right :-) ? )

I'm not entirely sure how to do so in cloud-init;  I'm going to send a PR that I think does it with cloud-init jinja...

**Comment by justinsb** [comment]
You've got company: https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/nodeup/command.go#L502-L506 :-)

**Comment by hkamel** [comment]
/sig scheduling

observing time out 

`Jun 10 05:42:34.202: INFO: found a healthy node: test1-md-0-4qcf5
[It] runs ReplicaSets to verify preemption running path [Conformance]
  test/e2e/framework/framework.go:597
Jun 10 05:42:42.675: INFO: pods created so far: [1 1 1]
Jun 10 05:42:42.675: INFO: length of pods created so far: 3
Jun 10 05:44:42.765: FAIL: pod sched-preemption-path-3834/pod4 failed to preempt other pods
Unexpected error:
    <*errors.errorString | 0xc00011bdd0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
`

**Comment by BenTheElder** [comment]
/remove-sig testing
SIG testing doesn't own cluster API or the scheduling tests.

**Comment by detiber** [comment]
I believe this has already been resolved thanks to the work of @justinsb 
/close
