### ISSUE TITLE
'pause' base image updates & building on K8s Infra

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#90698]
**What would you like to be added**:

Our core/base images should be built and housed on Kubernetes Community Infra.

- `pause`

**Why is this needed**:

We currently depend an extremely small set of Googlers to push these images.
There's minimal public documentation or visibility into this process and it creates a bottleneck when trying to do updates. This is especially detrimental from a security standpoint.

### Image building

- [x] (https://github.com/kubernetes/kubernetes/pull/90558, https://github.com/kubernetes/test-infra/pull/17424) Initial image building job
- [x] (https://github.com/kubernetes/test-infra/pull/17475, https://github.com/kubernetes/test-infra/pull/17476, https://github.com/kubernetes/test-infra/pull/17485) Updated image building jobs
- [x] (https://github.com/kubernetes/test-infra/pull/17496) Fix args for `debian-{base,iptables}` and pause image builds
- [ ] Consider pulling in content from @hoegaarden's original PR: https://github.com/kubernetes/kubernetes/pull/80909

### `pause`

- [x] (https://github.com/kubernetes/kubernetes/pull/90665) bump the `pause` tag
- [x] (https://github.com/kubernetes/k8s.io/pull/832) promote the `pause` image
- [ ] (https://github.com/kubernetes/kubernetes/pull/90700) update dependents to use the new `pause` image

### Cherry picks

- [ ] `pause`
  - [ ] 1.18:
  - [ ] 1.17:
  - [ ] 1.16:

/assign
cc(build-image OWNERS): @dims @BenTheElder @cblecker @listx 
cc: @kubernetes/release-engineering @kubernetes/product-security-committee 
/sig release
/area release-eng dependency security
/priority important-soon
/milestone v1.19

**Comment by justaugustus** [comment]
cc: @tallclair (so you get updates here)

**Comment by justaugustus** [comment]
Moved the debian base image items to a previously-opened issue: https://github.com/kubernetes/kubernetes/issues/58012

**Comment by jtslear** [comment]
Due to reaching the code freeze deadline, I'm going to bump this to the next release.

/milestone v1.20

**Comment by droslean** [comment]
@justaugustus Shall we keep this in 1.20 or move it to 1.21? The code freeze is near.

**Comment by justaugustus** [comment]
We're roughly done here, but I have to backfill docs.
/milestone v1.21
