### ISSUE TITLE
go util.Forever(func() {}, 0) is dangerous

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#907]
In repeated panic situations this causes the server to hot loop, and if go routines are launched as children you can quite easily bring down the goruntime with too many goroutines.

Things lavalamp and I tossed around:
- Treat `0` as `10 * time.Milliseconds`
- Detect multiple panics in a row and give up at some point
- Gradually increase timeout on successive panics up to a larger time window

Is there a reason why code would need 0?  I can't think of a good one (any code that needs to hot loop like that should be doing that hot loop inside the util.Forever).

**Comment by bgrant0607** [comment]
There are still instances of this in the scheduler, kubelet, and util/config/config.go.

**Comment by bgrant0607** [comment]
@smarterclayton @lavalamp Is this still relevant?

**Comment by smarterclayton** [comment]
It's still dangerous.  We shouldn't be hotlooping in until for the simplest reason that it allocates an object every time it loops which is bad for a very small loop.  Until should be reserved for long running operations, not very short ones.
