### ISSUE TITLE
Scheduling Framework: Merge Reserve and Unreserve

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#90724]
/kind cleanup

It doesn't make much sense for Reserve plugins to not have an Unreserve counterpart. Having them separate adds configuration toil.
I propose we merge them in a single interface and a single PluginSet in the configuration. However, we can only do the later in a new version of component config.

/sig scheduling

Related #83557 #83726  kubernetes-sigs/scheduler-plugins#4

**Comment by alculquicondor** [comment]
cc @mrkm4ntr @ahg-g @Huang-Wei @mrkm4ntr

**Comment by Huang-Wei** [comment]
SGTM.

**Comment by alculquicondor** [comment]
cc @cofyc

**Comment by ahg-g** [comment]
sounds good, we have precedence when we moved Normalize from being a standalone plugin into an extension of Score. For this one we can move unreserve to the reserve plugin and make implementing the function mandatory.

>  However, we can only do the later in a new version of component config.

we can do that in beta in this cycle, right?

**Comment by alculquicondor** [comment]
Yes, I can include the planned modifications in the KEP. Good thing is that we don't have in-tree (Un)Reserver plugins.

**Comment by cofyc** [comment]
SGTM

**Comment by alculquicondor** [comment]
@adtac is interested in helping out here

**Comment by adtac** [comment]
One potential issue that occurred to me while implementing this is the loss of the ability to do custom ordering when unreserving things if we merge the two into a single plugin. For example, a workload with three reserve plugins A, B, C (in that order) may require the Unreserve method to be called in the reverse order. That is, C may be required to be unreserved before B is unreserved.

This is trivially possible in the current implementation -- a user can explicitly define the order in which plugins should be run. However, a single plugin will no longer allow them to do this.

One potential real use case for something like this is nested mountpoints. If B mounts a directory inside a directory mounted by A, then B must usually be unmounted before A is unmounted.

I'm not sure if scheduler plugins are required to be independent of each other, but if we make this a requirement, we will no longer have this problem (also has potential side-benefits such as running multiple plugins concurrently).

Another solution would be execute Unreserve operations in the reverse order of Reserve operations. However, I feel that this inconsistency would be confusing to most users.

Any thoughts?

**Comment by alculquicondor** [comment]
The intention is for Reserve/UnReserve to act as "assume" and "cancel-assume", so they are informational [1]. Doing the actual binding of resources should happen in PreBind, just like our VolumeBinding plugin does [2]

The other thing is that plugins should be independent of each other, so order shouldn't matter. However, one thing we should expect from Unreserve calls is for them to be idempotent.

@mrkm4ntr @cofyc Do you forsee any problems with ordering of UnReserve calls?

[1](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#reserve)
[2](https://github.com/kubernetes/kubernetes/blob/13f1d956ea2741be4c11e90340ed1c4e0b515a8c/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L189)

**Comment by ahg-g** [comment]
I think calling in reverse order makes sense with proper documentation it should be fine.

**Comment by mrkm4ntr** [comment]
I don't foresee any problems.  Reverse order seems to be fine.

**Comment by cofyc** [comment]
Reverse order SGTM

**Comment by alculquicondor** [comment]
Thanks guys! Let's proceed with that.
