### ISSUE TITLE
A way to obtain the API server IP address from the network plugin.

### ISSUE THREAD

**Issue by shettyg** [kubernetes/kubernetes#9072]
After a pod's network container gets created, a call is made to the network plugin (documented here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/network/exec/exec.go). 

One way for the network plugin to get context information about a pod is to contact the api server to get information about the pod. To do that, the network plugin needs to know the IP address and port information of the api server.

Currently there is no nice way to do this. One current option is to look at '/proc/`pidof kubelet`/cmdline' to know the IP address of the api server. But it is likely not future proof because the command lines can change.

**Comment by thockin** [comment]
Thanks for filing this.  It's a good point.  We could pass the apiserver URL as part of the commandline, but that won't provide a token to actually access the API server.  Will have to think about it.

@jainvipin
@rajatchopra
@mrunalp

**Comment by rajatchopra** [comment]
My take is that this is an admin thing. The cluster admin starts the kubelet and other system components like kube-proxy, container runtimes (docker/rocket..) and thus it falls upon as the admin's duty to configure the network plugin too (with the appropriate args required to reach apiserver).

Couple of options exist nevertheless.
 - If there are config components over and above kubelet, then one can always create a wrapper that includes both a networking daemon and the kubelet (as a package). The networking plugin then inherits the config passed to the wrapped kubelet.
e.g. https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/start_node.go#L249-L254
 - The networking plugin can have a master of its own that is configured with the apiserver, thus relaying the info that is needed. The network plugin will have to be configured to reach its own master then, though.

That said, kubelet does have quite a bit of info about the pod (and it does serve them via REST too). Is there a specific thing that one needs about the pod that the kubelet does not have? Then it may be probably wiser to include that as part of what the kubelet stores. Alternatively, we can make the kubelet relay some of the info from apiserver too.

**Comment by thockin** [comment]
Kubelet should act as a local mirror of the apiserver for pod info, but I
don't think it does yet.

**Comment by shettyg** [comment]
@rajatchopra
>>That said, kubelet does have quite a bit of info about the pod (and it does serve them via REST too). Is there a specific thing that one needs about the pod that the kubelet does not have? 

Apart from thockin's response above,
I did not know something like this can be done. How does one get pod level information from kubelet in a minion? I tried to get lucky by copying kubectl to a minion and ran: 
```
./kubectl --server="0.0.0.0:10250" get pods
```
That did not help as I got a 
```
"Error: Get http://0.0.0.0:10250/api/v1beta1/pods?namespace=default: malformed HTTP response "\x15\x03\x01\x00\x02\x02""
```

Is there a tool to specifically query information from kubelet?

**Comment by rajatchopra** [comment]
Depends on how your cluster is setup. I have to check the latest on if admission control is applied to kubelet server. I did this on the master machine where a kubelet is running:
curl https://localhost:10250/pods | python -mjson.tool

Here is the massive output of the system pods that were running:
http://ur1.ca/mpnmy

**Comment by jainvipin** [comment]
For the situation @shettyg brought up, I am accessing by configuring the plugin with the apiserver’s URL with netmaster - option 2 that @rajatchopra mentioned above. So it is one time cluster startup configuration to the netmaster, which is cluster’s network intent realizer e.g. https://github.com/contiv/netplugin/tree/master/netmaster

@thockin mentioned:
> Thanks for filing this. It's a good point. We could pass the apiserver URL as part of the commandline, but that won't provide a token to actually access the API server. Will have to think about it.

Going this way would also mean that we’ll have to keep the cmd-args backwards compatible and future extensible.

**Comment by thockin** [comment]
> Going this way would also mean that we’ll have to keep the cmd-args
backwards compatible and future extensible.

We're going to have to cross that bridge eventually.

**Comment by shettyg** [comment]
@jainvipin 
Thanks for the insight. A little off-topic: What is the general consensus on where to define networking? Is it added as part of pod json as annotations or kept separate?

**Comment by jainvipin** [comment]
@shettyg - In my view `defining networking` is a much bigger task than associating annotations/labels to the pods. Clearly, the later one is needed for the former to work. Defining networking involves specifying the overall policy using which the operator wants to define/manage inter-connectivity within clusters, and perhaps traffic leaving the cluster. There are many examples that constitute cluster level inter-connectivity and perhaps you are familiar with many yourself, so I'll omit citing examples right now, but if you prefer I can.

Let's call the entity that consumes the `networking intent` is the place where networking is defined. In order, to realize the intent there needs to be a mechanism to translate and distribute the translated intent to minions and network-plugins that can realize the intent. This translated parameters is perhaps what you are referring to as whether it is best kept within pod json as annotations or outside. Adding annotations within pod, or putting labels and associate the labels to the translated intent outside - both works from some networking implementations on Kubernetes I am aware of.
