### ISSUE TITLE
TestCmdCompletion unit test fails when run locally

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#90732]
**What happened**:
TestCmdCompletion unit test fails on freshly cloned repository

**What you expected to happen**:
Unit test should pass when running locally without requiring any manual configuration of the system beforehand.

**How to reproduce it (as minimally and precisely as possible)**:
(Don't have `KUBEADM_PATH` environment variable set)
```
git clone git@github.com:kubernetes/kubernetes.git
cd kubernetes
go test ./cmd/kubeadm/test/cmd
```
Output:
```
--- FAIL: TestCmdCompletion (0.00s)
panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path [recovered]
	panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path

goroutine 8 [running]:
testing.tRunner.func1(0xc0000e2400)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x11ae540, 0x14f4790)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/cmd/kubeadm/test/cmd.getKubeadmPath(...)
	/home/bpursley/go/src/k8s.io/kubernetes/cmd/kubeadm/test/cmd/util.go:89
k8s.io/kubernetes/cmd/kubeadm/test/cmd.TestCmdCompletion(0xc0000e2400)
	/home/bpursley/go/src/k8s.io/kubernetes/cmd/kubeadm/test/cmd/completion_test.go:22 +0x1f8
testing.tRunner(0xc0000e2400, 0x1407e40)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	k8s.io/kubernetes/cmd/kubeadm/test/cmd	0.011s
FAIL
```

**Anything else we need to know?**:
I don't  have `KUBEADM_PATH` environment variable set.  I'm not making changes to kubeadm, I just want to see all the unit tests pass locally before making a PR for something else unrelated.

**Environment**:
- Kubernetes version (use `kubectl version`): **Master branch (v1.19.0-alpha)**
- Cloud provider or hardware configuration: **n/a**
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`): 
```
Linux cinlogic-xps13 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: **n/a**
- Network plugin and version (if this is a network-related bug): **n/a**
- Others: **n/a**

**Comment by brianpursley** [comment]
OK, I see what it is doing.  It needs to have a fully-compiled `kubeadm` (path set in `KUBEADM_PATH` environment variable) in order to test this because it exec's it.  

Am I doing something wrong?  I'm trying to run all unit tests locally before pushing a change, but maybe I should not be running this one, and if so, how can i exclude it?

Or maybe this test can be re-written to remove the compiled binary dependency...

**Comment by BenTheElder** [comment]
`go test` doesn't work so well, e.g. kubernetes sets build tags and stuff, you want `make test` and for a particular package you can set `WHAT=./pkg/foo`

**Comment by neolit123** [comment]
@brianpursley 

as you found out, those tests under cmd/kubeadm/tests are _command line integration tests_ that require a kubeadm binary prebuilt and passed via an environment variable.

to run them type:
```
make test-cmd WHAT=kubeadm
```

however if you want to run the kubeadm _unit tests_:
```
go test ./cmd/kubeadm/app/...
```
should work fine.

> EDIT 3: I wonder if these tests belong better in test/integration

kubeadm is going to be extracted into it's own repository at some point, so we should not move them under /test/integration.

does this provide a sufficient explanation?
it's already documented here:
https://github.com/kubernetes/kubeadm/blob/c4674ed58e9116933e7a6d9a613c7a3d3ba4da8e/CONTRIBUTING.md#running-unit-tests

/remove-kind failing-test
/triage support

**Comment by brianpursley** [comment]
@neolit123 yeah, that is fine. I guess I was expecting it to be a unit test, but I think even though I saw somewhere I can do `go test ./...` I should not do that because it will try to run tests like this, which are not meant to be run like that.

Thanks for the help and explanation.

/close
