### ISSUE TITLE
Unexpected MCS levels on containers

### ISSUE THREAD

**Issue by jean-edouard** [kubernetes/kubernetes#90759]
**What happened**:
On an SELinux-enabled setup, when I set an SELinux type (or user or role) in a `PodSecurityContext`, each container inside that pod gets its own SELinux level.
That in turn prevents inter-container communication within the pod.

**What you expected to happen**:
The SELinux level should be the same on all the containers of a given pod, as it is when no SELinux option is set on the pod.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ cat > pod.yaml << EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  securityContext:
    seLinuxOptions:
      type: container_t
  containers:
    - name: c1
      image: fedora
      command: [ "/bin/sleep", "10d" ]
    - name: c2
      image: fedora
      command: [ "/bin/sleep", "10d" ]
EOF
$ kubectl create -f pod.yaml
pod/pod created
$ kubectl exec -it pod -c c1 /bin/bash
[root@pod /]# ls -lZd /
drwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c605,c788 17 May  5 11:50 /
[root@pod /]# exit
$ kubectl exec -it pod -c c2 /bin/bash
[root@pod /]# ls -lZd /
drwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c61,c904 17 May  5 11:50 /
```

**Anything else we need to know?**:
- Setting `user` or `role` instead of `type` also triggers the issue.
- If no `seLinuxOptions` is set, all the containers do get the same SELinux level.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Bare-metal Fedora 31
- OS (e.g: `cat /etc/os-release`):
```
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
- Kernel (e.g. `uname -a`): Linux xxx 5.6.8-200.fc31.x86_64 #1 SMP Wed Apr 29 19:10:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vladikr** [comment]
@rhatdan Could you please advise on this?
Thanks!

**Comment by rhatdan** [comment]
If the containers in a pod share PID and/or IPC Namespaces, they need to share the same SELinux MCS Label.  If they share storage in multiple containers, the storage needs to be labeled with a non private label or the levels need to be the same or the label of the storage has to be container_file_t:s0, so all containers can write to it.

**Comment by jean-edouard** [comment]
@rhatdan thanks, that makes sense.
Do you also agree that there is a bug here that needs to be fixed?
i.e. auto-SELinux-level should behave the same regardless of other SELinux pod settings?

**Comment by rhatdan** [comment]
Yes containers joined to the same pod should be getting the same labels.  This works correctly with CRI-O.

**Comment by jean-edouard** [comment]
@rhatdan very interesting, could you please give me more details on your setup?
Having an environment that doesn't reproduce the issue might help debug it... So far I have seen it on every k8s environment I tried.
Thank you!

**Comment by rhatdan** [comment]
My setup is just a standard CRI-O configured setup.  CRI-O understands that containers that share IPC and/or PID Namespaces need to share the same SELinux label.  I believe as long as the kubernetes yaml file does not override the SELinux label, it should just work out of the box.  Thousands of OpenShift users are getting this without setting anything up.
