### ISSUE TITLE
Remove or clarify recommendation about using go test to run unit tests

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#90763]
**What would you like to be added**:
Remove `go test ./...` example from [testing guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing.md).

**Why is this needed**:
While trying to get all unit tests to run locally, I tried using this and it doesn't work, at least not from the Kubernetes root.

The reason it doesn't work is that it is not equivalent to `make test`, because `make test` [specifically excludes](https://github.com/kubernetes/kubernetes/blob/b48f5af2602bf097c11c6a252bc7f82a7c096206/hack/make-rules/test.sh#L34-L60) some directories when it runs unit tests.

On a side note, I think it is actually a little confusing presenting both `make test` and `go test` alternatives intermixed within the testing guide. I wonder if the `go test` examples would be better off consolidated in their own section toward the end of the guide.

**Comment by Yagora** [comment]
I can do this for my first contribution, maybe it's better if I specify in the Run all test paragraph : It's better to use make test because it excludes some directories when it runs unit tests.

Do you thinks it's enough ?

**Comment by brianpursley** [comment]
I will defer to someone from the sig testing team to answer that question.

`go test ./...` definitely won't work, so that should be removed from the docs altogether, IMO.

The other `go test` examples, I'm not sure if there is a reason to keep them in the docs or not.  They can work sometimes, depending on what you are testing, but they don't work universally... for example, if I try to `go test` something under `/cmd/kubeadm/test` it will likely fail because at least some of those tests have some external dependencies and are not true "unit tests".

**Comment by neolit123** [comment]
> go test ./... definitely won't work, so that should be removed from the docs altogether, IMO.

+1 (not a sig-testing member though)

**Comment by MushuEE** [comment]
@brianpursley do you mind elaborating on 

> I tried using this and it doesn't work, at least not from the Kubernetes root.?

I just ran it from root and seems like most of the tests run for me, just due to GOPATH being unset I get a lot of `[no test files]` If there were instructions on setting the GOPATH and we moved the go testing bit to it's own area of the guide, would that work?

**Comment by brianpursley** [comment]
@MushuEE sure. I probably should have provided more specific examples.

The main problem is the cmd/kubeadm/test directory.

It seems the tests in that folder are not really **unit** tests because they require a KUBEADM_PATH variable to be set in order to run and will actually call the kubeadm executable.

```
--- FAIL: TestCmdCompletion (0.00s)
panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path [recovered]
	panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path

goroutine 21 [running]:
testing.tRunner.func1(0xc0000f2400)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x1231680, 0x15a2570)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/cmd/kubeadm/test/cmd.getKubeadmPath(...)
	/home/bpursley/go/src/k8s.io/kubernetes/cmd/kubeadm/test/cmd/util.go:89
k8s.io/kubernetes/cmd/kubeadm/test/cmd.TestCmdCompletion(0xc0000f2400)
	/home/bpursley/go/src/k8s.io/kubernetes/cmd/kubeadm/test/cmd/completion_test.go:22 +0x1f8
testing.tRunner(0xc0000f2400, 0x14a5370)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	k8s.io/kubernetes/cmd/kubeadm/test/cmd	0.012s
?   	k8s.io/kubernetes/cmd/kubeadm/test/kubeconfig	[no test files]
?   	k8s.io/kubernetes/cmd/kubeadm/test/resources	[no test files]
FAIL
```

If you just to `go test ./...` from the project root, it will try to run these tests and fail.

On the other hand, if you use `make test` you don't have a problem because it specifically excludes certain folders where the tests are not really unit tests.

While `go test` may be fine to use within some subdirectories, I don't think it can be used at the project root.

**Comment by liggitt** [comment]
I'd recommend opening a bug against those tests in particular

**Comment by brianpursley** [comment]
OK, I can do that.  Makes sense to move them to integration probably, or remove the dependencies that cause them to fail.

**Comment by brianpursley** [comment]
Closing this issue in favor of fixing the problem in the tests.
New issue is https://github.com/kubernetes/kubernetes/issues/91740
