### ISSUE TITLE
Inconsistent use of service-accounts, .kubeconfig, and kube-addons secrets.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9076]
Making a serviceAccount causes automatic creation of a secret with an apiserver authn token.  But it does not generate a kubeconfig file holding the token.

kube-addons.sh makes secrets with tokens AND kubeconfigs.  But it does not make a ServiceAccount.  It also does not run on non-GCE platforms.

Our addons (logging, monitoring, dns) rely on secrets with secrets from the second category. 

We should stop manually generating secrets in kube-addons.  Instead, we should POST service accounts and let the automation make the secrets.  There should not be specific logic in kube-addons to make the service-accounts.  That should be part of the yaml for each addon.

This means we need to automatically generate kubeconfig in the TokenController, or change the client code for (dns, monitoring, logging) to understand how to read the bare token from its default location.

@lavalamp @liggitt

**Comment by liggitt** [comment]
adding in a kubeconfig that wraps up the token (along with CA, etc) is on my list, but not at the top of it

**Comment by lavalamp** [comment]
Yeah, addons should all use service accounts and we should stop using the special tokens.

**Comment by thockin** [comment]
Is there more to do here or is it done?

**Comment by erictune** [comment]
This can be closed.
