### ISSUE TITLE
DNS: If nodes use 3 nameservers or > 3 search records -- trouble

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9079]
Linux's libc is impossibly stuck ([see this bug from 2005](https://bugzilla.redhat.com/show_bug.cgi?id=168253)) with limits of just 3 DNS `nameserver` records and 6 DNS `search` records.  Kubernetes needs to consume 1 `nameserver` record and 3 `search` records.  This means that if a local installation already uses 3 `nameserver`s or uses more than 3 `search`es, some of those settings will be lost.  As a partial workaround, the node can run `dnsmasq` which will provide more `nameserver` entries, but not more `search` entries.

**Comment by erictune** [comment]
#9230 surfaces to the user if system is hitting this problem.

**Comment by cmluciano** [comment]
/close
kube-dns is now using dnsmasq
