### ISSUE TITLE
Pods in Node are deleted even if the NoExecute taint that triggered deletion is removed

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#90794]
**What happened**:

A Pod was scheduled for deletion because a taint w/ effect `NoExecute` was observed in the Node the Pod was assigned to, and after the taint is removed from the Node, the Pod scheduled deletion isn't canceled.

After scheduling pod deletion, the *`NoExecuteTaintManager` only cancels pod deletion if all `NoExecute` taints are removed from the node*, including any taints that the user relies on for their use-cases (example below).

**What you expected to happen**:

After the taint that triggered scheduling pod deletion is removed, `NoExecuteTaintManager` cancels the scheduled pod deletion.

**How to reproduce it (as minimally and precisely as possible)**:

- A node `MyNode` is tainted w/ `OnlyForMyUsage:NoExecute`, so any workloads already assigned to it which don't tolerate this taint are evicted.
- A pod `MyPod` is created w/ tolerations: `OnlyForMyUsage:NoExecute` w/ unspecified `tolerationSeconds` and `NotReady:NoExecute` w/ `tolerationSeconds: 300`.
- `MyPod` is assigned to `MyNode`.
- At some point in time after the previous steps took place, `MyNode` is tainted as `NotReady:NoExecute`.
- `NoExecuteTaintManager` gets an update event for `MyNode` and observes two `NoExecute` taints. It proceeds to calculate the minimum time (in seconds) that `MyPod` tolerates for the two taints which at this point is 300 seconds, and marks `MyPod` for deletion in ~300 seconds - this happens in-memory, in a timed-queue.
- At some point in time after the previous steps took place, and before the 300 seconds trigger happen, `NotReady:NoExecute` taint is removed from `MyNode`.
-  `NoExecuteTaintManager` gets an update event for `MyNode` and observes only one `NoExecute` taint, `OnlyForMyUsage:NoExecute`. It proceeds to calculate the minimum time (in seconds) that `MyPod` tolerates for the this taint which is _infinity_, and returns, not canceling the previous deletion. It *completely ignores the fact that the taint that triggered `MyPod` deletion is no longer observed*.

**Anything else we need to know?**:

- Worked w/ @bobveznat to figure this out after all pods in a node got evicted without apparent reason.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.3 (but looking at the code seems to affect all of 1.17.x and 1.18.x and master.
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): 5.x
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

cc @gmarek @bowei @k82cn (owners of this code)

**Comment by pires** [comment]
There seems to be at least [one other similar report in the wild](https://stackoverflow.com/questions/58560739/noexecutetaintmanager-falsely-deleting-pod).

**Comment by bobveznat** [comment]
You can sort of get a feel for what's going on here by looking at these two code snippets:

This is what happens in [the fast path](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L458) when the node does not have any NoExecute taints:
```	// Short circuit, to make this controller a bit faster.
	if len(taints) == 0 {
		klog.V(4).Infof("All taints were removed from the Node %v. Cancelling all evictions...", node.Name)
		for i := range pods {
			tc.cancelWorkWithEvent(types.NamespacedName{Namespace: pods[i].Namespace, Name: pods[i].Name})
		}
		return
	}
```
If you have any NoExecute taints on the node processPodOnNode gets called and this routine is really, really eager to evict pods. So [this code path is followed](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L359):

```	// getMinTolerationTime returns negative value to denote infinite toleration.
	if minTolerationTime < 0 {
		klog.V(4).Infof("New tolerations for %v tolerate forever. Scheduled deletion won't be cancelled if already scheduled.", podNamespacedName.String())
		return
	}
```

We are currently working around this issue by changing over our NoExecute taints to NoSchedule.

**Comment by ahg-g** [comment]
/remove-sig scheduling

scheduler isn't involved in this case.

**Comment by pires** [comment]
Which SIG owns the controller-manager or is the node lifecycle manager (and its NoExecuteTaintManager) owned by sig-node alone?

**Comment by liggitt** [comment]
I think node lifecycle is jointly owned by sig-node and sig-cloud-provider

**Comment by liggitt** [comment]
API machinery owns the mechanics of the controller manager (controller loop setup and management), but the individual controllers are SIG-specific

**Comment by bobveznat** [comment]
Looks like we lost some momentum here and I'd like to avoid this falling into the abyss of bugs that never get fixed. When this bug is triggered the outcome is pretty terrible and once it does happen it is very difficult to dig into and understand what actually happened. Did we ever get this routed to the right owner?

**Comment by liggitt** [comment]
adding sig-node leads for triage/routing. this seems like a clearly reproducible bug with significant correctness issues.

/assign @derekwaynecarr @dchen1107

**Comment by derekwaynecarr** [comment]
@bobveznat @pires thanks for the detailed report and reproducer.  to help accelerate this, do you have a form of your reproducer we could add in the e2e suite (even if its failing initially)?

**Comment by liggitt** [comment]
> do you have a form of your reproducer we could add in the e2e suite

custom taints are considered disruptive, so it couldn't run in the main suite

**Comment by pires** [comment]
It's been a while since I wrote tests for the e2e suite but if you are available over slack in case guidance is needed, I'm willing to put the effort.

**Comment by pires** [comment]
> custom taints are considered disruptive, so it couldn't run in the main suite

Do all suites need to pass for a fix to be merged? I'd assume it is the case, otherwise how would a regression be prevented after the fix lands?

**Comment by derekwaynecarr** [comment]
@pires i was more inquiring if there was a test that could automate the reproduction, so even just a linked commit may be helpful for someone that wants to pick this up.

**Comment by liggitt** [comment]
looks like a unit test could reproduce the issue, opened a WIP fix in https://github.com/kubernetes/kubernetes/pull/93722

**Comment by pires** [comment]
@derekwaynecarr our code is not publicly accessible, I'm sorry. PR linked by @liggitt seems to cover both the fix and the test that proves it.

**Comment by liggitt** [comment]
frozen keeps the bot from auto-closing

**Comment by pires** [comment]
Ah, sorry then.
