### ISSUE TITLE
Weird HPA behaviour

### ISSUE THREAD

**Issue by jrubenc** [kubernetes/kubernetes#90808]
**What happened**:

A deployment gets way too many pods launched by HPA. But individual pods CPU usage is really low.

foo-deployment      Deployment/foo-deployment    89%/90%   14        30        29         205d

But, for those 29 pods the CPU usage is:

112m 64m 91m 99m 133m 75m 115m 86m 76m 128m 98m 102m 134m 94m 64m 92m 107m 141m 77m 150m 128m 148m 103m 115m 74m 104m 110m 81m 121m

The deployment's limit is 400, so it's way under its limit.

**What you expected to happen**:

Pods CPU usage should be higher and HPA wouldn't have to trigger so many pods.

**How to reproduce it (as minimally and precisely as possible)**:

No idea. This deployment runs under JS. We have other deployments under JS too, and this doesn't happen.

**Environment**:
- Kubernetes version 1.15
- Cloud provider or hardware configuration: EKS
- OS Amazon Linux 2
- Kernel 4.14.173-137.229.amzn2.x86_64

**Comment by zuquan-song** [comment]
Hi, did the pods eventually dropped to normal number? The HPA would get the highest recommendation within the `--horizontal-pod-autoscaler-downscale-stabilization` period. Or if you custom a behavior, the scale up rule and the scale down rule will affect the time to drop the desired replica numbers
