### ISSUE TITLE
kubernetes ppc64le client v1.18 binary is mixed up with arm64 client

### ISSUE THREAD

**Issue by runlevel5** [kubernetes/kubernetes#90807]
**What happened**:

I downloaded the official ppc64le client binary from the https://kubernetes.io/docs/setup/release/notes/#client-binaries.

When I run `./bin/kubectl`, I get following error:

`cannot execute binary file: Exec format error`

**What you expected to happen**:

The app should work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Find a computer running Linux ppc64le
2. `wget https://dl.k8s.io/v1.18.0/kubernetes-client-linux-ppc64le.tar.gz`
3. `tar xzvf kubernetes-client-linux-ppc64le.tar.gz`
4. run `./kubernetes/client/bin/kubectl`

**Anything else we need to know?**:

It turns out the binary in the tarball is actually the one compiled for ARM64

```
$ file bin/kubectl 
bin/kubectl: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=EoUOyIgEnU1RN6SJdd9p/KGKe0cdy40WB7YV2Mt39/XQ38HiJQu_8HhOJAxd_0/3lIgDpOxKW1-bZfIwZEu, stripped
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: Raptor Computing Systems Blackbird (C1P9S01) motherboard with IBM POWER9 V2 8-core 3.8Ghz 32-threads (Sforza) (02CY649)
- OS (e.g: `cat /etc/os-release`): Fedora 32 ppc64le
- Kernel (e.g. `uname -a`): Linux orion.dev 5.6.8-300.fc32.ppc64le #1 SMP Wed Apr 29 17:40:17 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
@kubernetes/release-engineering 
@kubernetes/release-managers

**Comment by justaugustus** [comment]
Will investigate next week.
/assign
/area release-eng

**Comment by runlevel5** [comment]
Thanks for fixing the issue.
