### ISSUE TITLE
Clarify behavior of `imagePullPolicy: Always`

### ISSUE THREAD

**Issue by nfisher** [kubernetes/kubernetes#90809]
**What would you like to be added**:

**Updated issue description:**

`imagePullPolicy: Always` resolves the image with the registry, and if it resolves to a sha that is not already pulled to the node, pulls the image content. If the resolved sha is already pulled to the node, it uses the already-pulled content. The documentation does not make this clear.

**Original issue description:**

Currently the options for the container `imagePullyPolicy` is limited to `Always` and `IfNotPresent`. It would be useful to have an additional option of `IfModified` when combined with a tag. If the docker digest for the `arch + os` has changed then pull a newer image. Maybe this needs to happen upstream in docker first?

A sample tag entry from the docker registry v2 API:

```
{
      "creator": 7,
      "id": 2110,
      "image_id": null,
      "images": [
        {
          "architecture": "amd64",
          "features": "",
          "variant": null,
          "digest": "sha256:1ae98b2c895d1ceeba8913ff79f422f005b7f967a311da520a88ac89180b4c39",
          "os": "linux",
          "os_features": "",
          "os_version": null,
          "size": 87342331
        }
      ],
      "last_updated": "2017-04-06T20:16:24.015937Z",
      "last_updater": 2215,
      "last_updater_username": "stackbrew",
      "name": "centos5",
      "repository": 54,
      "full_size": 87342331,
      "v2": true
    }
```

**Why is this needed**:

Would eliminate needless downloads from a registry where the image version has not changed. Acting similar to e-tags/if-modified-since tags in HTTP.

**Comment by liggitt** [comment]
`imagePullPolicy: Always` actually does what you want already... it resolves the image with registry and if it resolves to a sha that is not already pulled to the node, pulls the image. If the resolved sha is already pulled to the node, it uses the already-pulled content.

**Comment by liggitt** [comment]
/remove-kind feature
/kind documentation

the documentation probably needs to make the behavior of "Always" clearer

**Comment by nfisher** [comment]
I assume this is per Node behaviour correct? Rather than level-set during submission of the container spec to the cluster?

**Comment by liggitt** [comment]
yes, all image pull effects are per-node

**Comment by wawa0210** [comment]
I feed these clarification information into the document
