### ISSUE TITLE
[Flaky test] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Slow] [Conformance] - watch closed before UntilWithoutRetry timeout

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#90813]
**Which jobs are flaking**:
* ci-kubernetes-kind-conformance-parallel
* ci-kubernetes-kind-conformance-ga-only-parallel
* ...

**Which test(s) are flaking**:

* `[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy`

**Testgrid link**:

* https://testgrid.k8s.io/sig-testing-kind#pull-kubernetes-conformance-kind-ga-only-parallel&width=5&sort-by-flakiness=&include-filter-by-regex=Scaling%20should%20happen%20in%20predictable%20order%20and%20halt%20if%20any%20stateful%20pod%20is%20unhealthy
* https://testgrid.k8s.io/conformance-all#conformance,%20master%20%28dev%29%20[non-serial]&width=5&include-filter-by-regex=Scaling%20should%20happen%20in%20predictable%20order%20and%20halt%20if%20any%20stateful%20pod%20is%20unhealthy

**Reason for failure**:

```
test/e2e/framework/framework.go:597
May  5 21:31:57.103: Unexpected error:
    <*errors.errorString | 0xc0004c81f0>: {
        s: "watch closed before UntilWithoutRetry timeout",
    }
    watch closed before UntilWithoutRetry timeout
occurred
test/e2e/apps/statefulset.go:659
```

**Anything else we need to know**:

This increased sharply on 5/5:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=watch%20closed%20before%20UntilWithoutRetry%20timeout

**Comment by liggitt** [comment]
#90729 seems a likely cause

/cc @wojtek-t

**Comment by liggitt** [comment]
I *think* the test is actually faulty... e2e tests using watch.UntilWithoutRetry or watch.Until are going to be vulnerable to their resource versions exceeding the watch window

```
egrep -r 'watchtools\.(Until|UntilWithoutRetry)\(' test/e2e
test/e2e/common/init_container.go:		event, err := watchtools.Until(ctx, startedPod.ResourceVersion, w,
test/e2e/common/init_container.go:		event, err := watchtools.Until(ctx, startedPod.ResourceVersion, w, recordEvents(events, conditions.PodRunning))
test/e2e/common/init_container.go:		event, err := watchtools.Until(
test/e2e/common/init_container.go:		event, err := watchtools.Until(
test/e2e/apps/deployment.go:	_, err := watchtools.Until(ctx, d.ResourceVersion, w, condition)
test/e2e/apps/statefulset.go:			_, err = watchtools.Until(ctx, pl.ResourceVersion, w, func(event watch.Event) (bool, error) {
test/e2e/apps/statefulset.go:			_, err = watchtools.Until(ctx, pl.ResourceVersion, w, func(event watch.Event) (bool, error) {
```

**Comment by liggitt** [comment]
/sig apps
for deployment/statefulset tests

/sig testing
for common helper methods

**Comment by wojtek-t** [comment]
Let me take a look - I think my PR shouldn't fundamentally break anything, so it's probable that those tests are faulty as Jordan wrote? I will look into it.

/assign

**Comment by liggitt** [comment]
it looks like at least some of the watchers we start don't indicate they can receive watch bookmarks:

https://github.com/kubernetes/kubernetes/blob/0a6c826d3e92dae8f20d6199d0ac7deeca9eed71/staging/src/k8s.io/client-go/tools/watch/retrywatcher.go#L100-L105

**Comment by liggitt** [comment]
/kind bug

based on the issue discovered in non-test code

**Comment by wojtek-t** [comment]
OK - so I looked into the test and it's actually it's not that surprising - the test takes more than 5 minutes, and we're sending "watch request" with RV from the initial request from the beginning of the test. So it's not unexpected.

I actually looked into tests and should be fairly trivial to migrate them to use, so I will try to do that too.

**Comment by liggitt** [comment]
Let's isolate the RetryWatcher change... I'd consider backporting that

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/90818 should improve the immediate flakiness. Keeping this open with lowered severity to switch the tests to completely-non-flaky watch.Until methods in https://github.com/kubernetes/kubernetes/pull/90815 once signal in https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=watch%20closed%20before%20UntilWithoutRetry%20timeout is demonstrably clear

**Comment by wojtek-t** [comment]
#90815 in the current form has so problems with itself (it may cause flakiness). I need to spend a bit more time to fix it.
That said, I opened #90855 (which is a bit unrelated), but is cleaning up one of the functions we don't really need.

**Comment by liggitt** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=watch%20closed%20before%20UntilWithoutRetry%20timeout signal has not improved, which surprises me... I expected use of watch bookmarks to resolve the issue

**Comment by wojtek-t** [comment]
@liggitt - I understand where it comes from.
Basically what is happening is:
- we first list: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/statefulset.go#L586
- we do a bunch of stuff
- and only after that we start watch from RV got in the initial step:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/statefulset.go#L615

So bookmarks won't help.
https://github.com/kubernetes/kubernetes/pull/90815
changes to that test would fix that problem.

Let me separate some of those to fix it.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/90898 should fix this problem (just the statefulset test).
I'm going to clean up the other PR for other tests independently.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/90818 and https://github.com/kubernetes/kubernetes/pull/90898 resolved the flakiness

**Comment by liggitt** [comment]
closing this, #90815 and #90855 can cleanup the test functions as followups

/close
