### ISSUE TITLE
VSphere Cloud Provider dynamic storage provisioning got very slow after upgrading from v1.14 to v1.15.

### ISSUE THREAD

**Issue by Baykonur** [kubernetes/kubernetes#90814]
**What happened**:
We are using vsphere cloud provider. Dynamic storage provisioning got very slow after upgrading our K8s clusters from v1.14 to v1.15.
**What you expected to happen**:
We expected `pv`s to be created within seconds as it happens on K8s v1.14 cluster. However depending on the number `pvc`s created by the developers on the cluster, the creation of a `pv` took between 2 minutes to 156 minutes after the K8s upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
Provision a v1.14 K8s cluster using VMs running on a single datacenter, no zoning used.
Use the following `vsphere.conf`:
```
[Global]
#TODO: install certs for vcenter https and remove insecure-flag
insecure-flag = 1
secret-name = "vsphere-cloud-provider-secret"
secret-namespace = "kube-system"

[VirtualCenter "<IP_ADDRESS"]
port = <PORT>
datacenters = <DATACENTER>

[Workspace]
server = "<IP_ADDRESS"
datacenter = "<DATACENTER>"
default-datastore = "<YOUR_DEFAULT_DS>"
folder = "vm/Kubernetes"

[Disk]
scsicontrollertype = pvscsi
```

push the following `storageclass`:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vmfs-policydelete
parameters:
  diskformat: zeroedthick
  fstype: ext4
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Create a `pvc` using the `storageclass` above and see that `pv` gets created within 3 seconds.
Above please spot `folder = "vm/Kubernetes"`, on a v1.14 cluster this could be `folder = Kubernetes` and the datastore would be found, with the commits cited down below as **1 and 2**, once we upgraded to v1.15, we were getting [Ambigous datastore name](https://github.com/kubernetes/kubernetes/commit/18922a3c44874bd052f06a2a9daae58da935f797#diff-639eab7105ae6828f3636f9d47143f3bR1326) error when we have `folder = Kubernetes`  in our `vsphere.conf` file. One reason is the fact that unfortunately our VMWARE Team decided to use the same folder name (which is also _Kubernetes_) for the datastores which they created for us. Once we realized that the folder names are same (for VMs and Datastores), we set the folder value to `"vm/Kubernetes"` in `vsphere.conf` and things started to work again but very slowly. Dynamic storage provisioning is taking really long time on our v1.15 cluster and downgrading to v1.14 from v1.15 is not an option for us.

Now upgrade your v1.14 cluster to v1.15 using `kubeadm` and repeat the exercise above. You will see that `pv` creation will take around 2 minutes.

**Anything else we need to know?**:
We do not use any zoning, I suspect this issue arose with the following commits: [1](https://github.com/kubernetes/kubernetes/commit/18922a3c44874bd052f06a2a9daae58da935f797), [2](https://github.com/kubernetes/kubernetes/pull/74295/commits/8ceacd9ed963868d4392b49a45dc68f0adafe70d).
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `vsphere`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2303.3.0
VERSION_ID=2303.3.0
BUILD_ID=2019-12-02-2049
PRETTY_NAME="Container Linux by CoreOS 2303.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux 4.19.86-coreos #1 SMP Mon Dec 2 20:13:38 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz GenuineIntel GNU/Linux
```
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Baykonur** [comment]
Dear @subramanian-neelakantan, this issue requires your attention, I would appreciate if you could flag it with vmware team. 
Also, if you can let me know how I can activate debug logs for govmomi library which is used by the kube-controller-manager, I can provide further information.

**Comment by divyenpatel** [comment]
@Baykonur Kubernetes and VCP are emitting various Prometheus metrics which can help identify what causes overall performance issues.

In VCP we emit metrics for overall volume creation operation as well as an individual API call to vCenter for creating volume.  If you can scrape vSphere metrics from Kubernetes Controller, we can identify where the issue is - VC is responding slow or cluster is taking a long time for processing requests.

Refer this - https://github.com/kubernetes/kubernetes/pull/46462/

You can capture logs following this troubleshooting guide - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/troubleshooting.html

**Comment by Baykonur** [comment]
That is great, I will have a look at the links and come back to you.

**Comment by Baykonur** [comment]
Dear @divyenpatel , we have started to scrape `cloudprovider_vsphere*` metrics from the controller, can you please point me to a possible grafana dahsboard configuration that you might be using for this?

**Comment by Baykonur** [comment]
Dear @divyenpatel , is there anything you can recommend here?
