### ISSUE TITLE
RBD json tags don't match field names

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9083]
There may be others but I saw this today...

```
type RBDVolumeSource struct {
    // Required: CephMonitors is a collection of Ceph monitors
    CephMonitors []string `json:"monitors"`
    // Required: RBDImage is the rados image name
    RBDImage string `json:"image"`
    // Required: Filesystem type to mount.
    // Must be a filesystem type supported by the host operating system.
    // Ex. "ext4", "xfs", "ntfs"
    // TODO: how do we prevent errors in the filesystem from compromising the machine
    FSType string `json:"fsType,omitempty"`
    // Optional: RadosPool is the rados pool name,default is rbd
    RBDPool string `json:"pool"`
    // Optional: RBDUser is the rados user name, default is admin
    RadosUser string `json:"user"`
```

I think that, in general we want field names and JSON tags to match unless there's a good reason for them not to.  I see no good reason here.  Probably field names should change, leaving tags (the API) untouched.

@markturansky @rootfs

**Comment by smarterclayton** [comment]
Moving to @kubernetes/sig-storage-misc

**Comment by humblec** [comment]
afaict, this is fixed for RBDVolumeSource @thockin , if thats the case, cant we close this issue?

**Comment by sftim** [comment]
RBD is deprecated, I recommend closing.

**Comment by thockin** [comment]
Closing - changing this would cause client-go breakage that just isnt' worth the pain.

Alas poor #123391 - we hardly knew you.
