### ISSUE TITLE
[Flaky Test] gce-cos-master-slow (ci-kubernetes-e2e-gci-gce-slow)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90830]
**Which jobs are failing**:
> gce-cos-master-slow (ci-kubernetes-e2e-gci-gce-slow)

**Which test(s) are failing**:
> Overall
>Test
> [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Slow] [Conformance]

**Since when has it been failing**:
> 05-06 09:33 PDT (with one success only in between 15:17 PDT)

**Testgrid link**:
>https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-slow

**Reason for failure**:
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
May  7 04:50:33.637: Unexpected error:
    <*errors.errorString | 0xc000393890>: {
        s: "watch closed before UntilWithoutRetry timeout",
    }
    watch closed before UntilWithoutRetry timeout
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/statefulset.go:659

**Anything else we need to know**:
> timed out

/cc @kubernetes/ci-signal 
/milestone v1.19
/priority critical-urgent
/sig testing
/sig apps

**Comment by hasheddan** [comment]
We are still getting an error in the watch here (ref: https://github.com/kubernetes/kubernetes/blob/90f7ae54acbbab22460fe5fabded02d9b912b834/staging/src/k8s.io/client-go/tools/watch/until.go#L78). It looks like @tnozicka + @spiffxp were attempting to fix this in https://github.com/kubernetes/kubernetes/pull/75111. From what I can see in a failed run, we are successfully scaling down that `StatefulSet` in reverse order, so I believe this is an issue with the watch https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1258681349833756673#1:build-log.txt%3A51830

**Comment by hasheddan** [comment]
`StatefulSet` flake does not appear to be happening frequently anymore, but now seeing `[sig-network] Services should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters] [LinuxOnly]` @kubernetes/sig-network-misc 

/remove-sig apps
/sig network
/retitle [Flaky Test] gce-cos-master-slow (ci-kubernetes-e2e-gci-gce-slow)
/remove-kind failing-test
/kind flake

**Comment by aojea** [comment]
I think we can decrease the priority, right?
now is just flaky, previously it was completely red

**Comment by BenTheElder** [comment]
/remove-sig testing
> [sig-network] Services should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters] [LinuxOnly]

I have no idea what ESIPP is :O

**Comment by aojea** [comment]
@MrHohn should we remove the ESSIP tests?

https://github.com/kubernetes/kubernetes/issues/64124

> `StatefulSet` flake does not appear to be happening frequently anymore, but now seeing `[sig-network] Services should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters] [LinuxOnly]`

**Comment by MrHohn** [comment]
> @MrHohn should we remove the ESSIP tests?

The name is confusing :) ESIPP (External Source IP Preservation) is now a GA Service API field -> ExternalTrafficPolicy.

Took a quick glance at the test result - it looks like there are some blips on the load balancer traffic that are affecting the test result. I believe it is more of a test setup issue other than a real bug.

Consider that it's been flaky for a long long while and nobody has given enough attention to it, and that we have a separate test case that exercises the session affinity feature (without transition), I guess it might be okay to disable this one for now until we can get it back to a healthy state.

Or if there is any jailing concept for e2e test in general I'd like to opt this test in that as well.

**Comment by BenTheElder** [comment]
what sort of "test setup" issue?
the cluster? the test readiness logic?

Tests can be ~jailed with a `[Flaky]` tag

**Comment by MrHohn** [comment]
>what sort of "test setup" issue?
the cluster? the test readiness logic?

Sorry for no being clear, I observed some I/O timeouts on the load balancer traffic and that seems to trigger the session affinity being unhold. I was thinking that the test logic is not entirely correct that it tries to verify the behavior while the load balancer is still being stabilized. I guess "test setup" is a wrong word, but the way the test is written makes it flaky.

> Tests can be ~jailed with a `[Flaky]` tag

Good to know, we can definitely make this as flaky.

**Comment by hasheddan** [comment]
I have not seen a flake on the test mentioned in this issue recently

/close
