### ISSUE TITLE
Move scheduler Plugin args validation to apis/config/validation

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#90859]
Follow up to #87784

The validation is currently done in each plugin, which makes sense to keep some independence of the plugins.
However, since the types are API types, it also makes sense to have them in the validation package (and call the functions from the plugins)

Note that validation is only imported in `cmd/kube-scheduler/app/options` today

Thoughts?

/sig scheduling
/kind cleanup

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei @liggitt

**Comment by liggitt** [comment]
Things that depend on internal API types can reasonably make use of validation functions on those internal types as well. Moving the static validation to `pkg/scheduler/apis/config/validation` so we can call them from ValidateKubeSchedulerConfiguration makes sense to me.

**Comment by ahg-g** [comment]
Sounds good to me as well. We should keeping calling the validation logic from the plugins because the framework is currently being instantiated directly by CA.

**Comment by alculquicondor** [comment]
Sound good.
Opening for contributors

/help

**Comment by angao** [comment]
I can help do this change.

**Comment by alculquicondor** [comment]
Thanks @angao, but @pancernik already has experience in this particular stack. I have other tasks that need attention. You can ping me in slack.

**Comment by pancernik** [comment]
This is divided into:
- [x]  moving validation of all plugin args but Node Resources ones  https://github.com/kubernetes/kubernetes/pull/91241 
- [ ] moving validation of Node Resources plugin args
- [ ] using moved validation in `ValidateKubeSchedulerConfiguration`,
       and improving code and error message consistency

**Comment by alculquicondor** [comment]
I think you will also be missing a couple of validations for plugin args that are getting merged now.

**Comment by alculquicondor** [comment]
/close

this work was completed for 1.19
