### ISSUE TITLE
UnmountVolume.TearDown failed for volume of type hugetlbfs, error getting page size from 'pagesize=2Mi' mount option: unable to parse quantity's suffix". Resulting pod status in terminated forever.

### ISSUE THREAD

**Issue by kapil-rn** [kubernetes/kubernetes#90851]
**What happened**:
Pods get stuck in terminating state, as kubelet failed to unmount volume:
nodev on /var/lib/kubelet/pods/b3220985-120c-45c4-aeac-9f49adb29d17/volumes/kubernetes.io~empty-dir/hugepage type hugetlbfs (rw,relatime,pagesize=**2Mi**)

`Error: "UnmountVolume.TearDown failed for volume \"hugepage\" (UniqueName: \"kubernetes.io/empty-dir/b3220985-120c-45c4-aeac-9f49adb29d17-hugepage\") pod \"b3220985-120c-45c4-aeac-9f49adb29d17\" (UID: \"b3220985-120c-45c4-aeac-9f49adb29d17\") : error getting page size from 'pagesize=2Mi' mount option: unable to parse quantity's suffix"`
 
**What you expected to happen**: Pod to get deleted and volumes to be cleaned up.

**How to reproduce it (as minimally and precisely as possible)**: kvm based virtual machines on ubuntu 16.04.  create a pod with hugepage volumes (https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/)
Delete the pod.

**Anything else we need to know?**:

Changes are related to mentioned commit id: https://github.com/kubernetes/kubernetes/commit/03ecc20b19972ecb4825ecf4ce6868bc2a45f3c0

In this file : **pkg/volume/emptydir/empty_dir_linux.go , line no 72**  : 
`pageSize, err := resource.ParseQuantity(strings.TrimPrefix(opt, prefix) + "i")
`
The mount already has a pagesize 2Mi in my case as shown here : (rw,relatime,pagesize=**2Mi**)
But the code here suffix/appends **"i"**  assuming pagesize can be only of type 2M or 1024M
resulting in failure to clean up this volume.

Documentation from code:
`/ NOTE: Adding suffix 'i' as result should be comparable with a medium size.
			// pagesize mount option is specified without a suffix,
			// e.g. pagesize=2M or pagesize=1024M for x86 CPUs
			pageSize, err := resource.ParseQuantity(strings.TrimPrefix(opt, prefix) + "i")
			if err != nil {
				return nil, fmt.Errorf("error getting page size from '%s' mount option: %v", opt, err)
			}`

when the pod is deployed, kubelet creates the mount and we can see from logs that it already has **pagesize=2Mi** for my environment.

```
12898 empty_dir.go:319] pod b3220985-120c-45c4-aeac-9f49adb29d17: mounting hugepages for volume hugepage
May 07 13:37:56 worker-1 kubelet[12898]: I0507 13:37:56.890909   12898 mount_linux.go:146] Mounting cmd (systemd-run) with arguments (--description=Kubernetes transient mount for /var/lib/kubelet/pods/b3220985-120c-45c4-aeac-9f49adb29d17/volumes/kubernetes.io~empty-dir/hugepage --scope -- mount -t hugetlbfs -o **pagesize=2Mi** nodev 

```

**Environment**:
- Kubernetes version: 
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Kvm hypervisor based virual machine setup 

- OS (e.g: `cat /etc/os-release`): 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`): Linux master 4.4.0-169-generic #198-Ubuntu SMP Tue Nov 12 10:38:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
What about this change ?
```
diff --git a/pkg/volume/emptydir/empty_dir_linux.go b/pkg/volume/emptydir/empty_dir_linux.go
index 63a25dc4ed0..e468fa09f7d 100644
--- a/pkg/volume/emptydir/empty_dir_linux.go
+++ b/pkg/volume/emptydir/empty_dir_linux.go
@@ -69,7 +69,11 @@ func getPageSize(path string, mounter mount.Interface) (*resource.Quantity, erro
                        // NOTE: Adding suffix 'i' as result should be comparable with a medium size.
                        // pagesize mount option is specified without a suffix,
                        // e.g. pagesize=2M or pagesize=1024M for x86 CPUs
-                       pageSize, err := resource.ParseQuantity(strings.TrimPrefix(opt, prefix) + "i")
+                       trimmedOpt := strings.TrimPrefix(opt, prefix)
+                       if !strings.HasSuffix(trimmedOpt, "i") {
+                               trimmedOpt = trimmedOpt + "i"
+                       }
+                       pageSize, err := resource.ParseQuantity(trimmedOpt)
                        if err != nil {
                                return nil, fmt.Errorf("error getting page size from '%s' mount option: %v", opt, err)
                        }
```

**Comment by bart0sh** [comment]
@tedyu The change looks good to me. Would you be willing to submit a PR?

**Comment by kapil-rn** [comment]
@tedyu & @bart0sh : Thanks for the quick turnaround.

**Comment by svallala** [comment]
We are seeing this issue in 1.18.6 version, can you please push the fix to this branch as well.

**Comment by harper1011** [comment]
Could we know when the problem was introduced?
As I suppose we don't have the same issue with K8S 1.17.x release?

**Comment by yueseW** [comment]
Hi same issue found in 1.18.2

**Comment by svallala** [comment]
It is not yet ported into v1.18.6 as well.

**Comment by bart0sh** [comment]
@tedyu Can you submit your PR for release-1.18 branch?

**Comment by tedyu** [comment]
I tried to run cherry pick script.
However hub was blocked by MacOS.
