### ISSUE TITLE
Improve readiness times for clusters that use envelope encryption and create large numbers of secrets.

### ISSUE THREAD

**Issue by immutableT** [kubernetes/kubernetes#90856]
**What would you like to be added**:
Remove the need to call remote KMS for every new Secret.

**Why is this needed**:
Due to the serial processing of List requests, the initialization of informers may take significant time due to the large number of consecutive trips to KMS. For example, assuming a 40 milliseconds round-trip to a KMS and two thousand secrets, the initialization of an informer may take 80 seconds.

Relevant PRs:
Reduce the number of trips to KMS by caching DEKs. #87438
Transform from storage concurrently during List operation. #88633

**Comment by mikedanese** [comment]
Breaking the problem up a bit, we can reduce the number of calls across tow boundaries:

1. kube-apiserver -> kms plugin
2. kms plugin -> non-local kms

Most ideas are around DEK reuse. Writing down notes from the brainstorm:

### Boundary 1

We've discussed a lot of options. I like the idea of keeping the DEKs one to one with objects, but reusing DEKs to encrypt the same object. If we use a counter to generate nonces (vs generating nonces randomly), we don't have to worry about the birthday problem and can switch to AES-GCM for data encryption without concern.

### Boundary 2

Plugins can reduce calls to remote KMS services by implementing a multi level KEK hierarchy. I.e. a plugin keeps local KEKs that it reuses across DEKs for some number of operations.

With ad hoc symbolic notation for operations:

```
| = concatenate
kid(key) -> key identifier
enc(key, data) -> cipher text
dec(key, cipher text) -> data
```

For an example key hierarchy:

![Key Hierarchy](https://user-images.githubusercontent.com/1787169/81361125-66a5fa80-9092-11ea-8df8-24e2f00ca9d9.png)

object_0_0_1 is stored as:

```
kid(kek_0) | enc(kek_0, kek_0_0) \
| kid(kek_0_0) | enc(kek_0_0, dek_0_0_1) \
| kid(dek_0_0_1) | enc(dek_0_0_1, object_0_0_1)
```

**Comment by mikedanese** [comment]
@enj @kubernetes/sig-auth-bugs

**Comment by immutableT** [comment]
I am adding some background on GCM to help us navigate the decision on approach - caching DEK vs.  hierarchical key structure (as suggested by @mikedanese). 
 
From [NIST 800-38D](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf) (emphasis and omissions are mine):
### Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and GMAC.
- The total number of invocations of the authenticated encryption function shall not exceed
**2^32** ... with the given key. 

**My interpretation of the above (in the context of envelope encryption feature):**
Given the upper limit of 2^32 invocations, it is safe cache DEKs when:

1. TTL is in the range of minutes (very conservative)
2. IV is produced via /dev/urandom (or via a counter as suggested by @mikedanese). 

Note that setting the cache TTL in the range of several minutes will dramatically reduce the number of trips to KMS since requests for Secrets creation are typically batched (ex. cluster creation or service deployment). The drawback of caching DEKs is that uses would need to wait for the duration of the cache TTL before performing storage migration.

**Comment by immutableT** [comment]
I am adding PCI DSS requirements relevant to the protection of secrets at rest:

**3.5.3 Store secret and private keys used to encrypt/decrypt cardholder data in one (or more) of the following forms at all times**:

- Encrypted with a key-encrypting key that is at least as strong as the data encrypting key, and that is stored separately from the data-encrypting key

- Within a secure cryptographic device (such as a hardware (host) security module (HSM) or PTS approved point-of-interaction device)

- As at least two full-length key components or key shares, in accordance with an industry accepted method  

**3.6.4 Cryptographic key changes for keys that have reached the end of their crypto period** (for example, after a defined period of time has passed and/or after a certain amount of cipher-text has been produced by a given key), **as defined by the associated application vendor or key owner**, and based on industry best practices and guidelines (for example, NIST Special Publication 800-57). 

**3.6.5 Retirement or replacement (for example, archiving, destruction, and/or revocation) of keys as deemed necessary when the integrity of the key has been weakened** (for example, departure of an employee with knowledge of a clear-text key component), or keys are suspected of being compromised.

**Comment by enj** [comment]
So I tried reading the hierarchical key structure but I will admit I am unable to parse what the image is trying to say ...

---

@immutableT would it be valuable to perform this experiment:

1. Create a cluster with KMS configured (to some cloud KMS) and create a large number of encrypted at rest secrets (100k?)
1. Set KMS `cachesize` cache size to > 100k
1. Restart cluster
1. Measure start up time
1. Calculate mean and standard deviation of gRPC calls.  This will give us the overhead of `kube-apiserver -> kms plugin` + `kms plugin -> non-local kms` calls.

Perform the same experiment but change the KMS to https://github.com/enj/citadel with a static KEK (i.e. `echo $secret_key`).  This will give us a good idea of what the overhead of the `kube-apiserver -> kms plugin` calls.

We can then determine `kube-apiserver -> kms plugin` vs. `kms plugin -> non-local kms` overhead.  In particular, it would tell us if a KMS plugin proxy that caches a KEK temporarily is viable or if we need to make changes directly to the API server.

**Comment by immutableT** [comment]
Yes it would be. Furthermore, I think it would be a useful metric to have (see #91119).

While I am working on this experiment, I can provide some rough numbers based on my environment.
Since we measure the latency at both points: kube-apiserver and kms-plugin, by subtracting the median latency at kube-aipserver from that of kms-plugin, I estimated the overhead of over the Unix Domain Socket communications to be 6 ms for encrypt requests.

**Comment by cenkalti** [comment]
@mikedanese @immutableT Do you remember what was the reason behind creating a DEK per secret object? It could be a single DEK for all secrets.
