### ISSUE TITLE
pod fails to pull image from private docker registry

### ISSUE THREAD

**Issue by imchand** [kubernetes/kubernetes#90858]
I am trying to create a pod in the Kubernetes cluster using the image present in the private registry. i was able to successfully push images to the registry.  But when I am trying to create a pod it fails with the below error. 

 Type     Reason     Age                From                 Message
  ----     ------     ----               ----                 -------
  Normal   Scheduled  <unknown>          default-scheduler    Successfully assigned default/private-reg to kubeworker
  Normal   Pulling    47s (x3 over 89s)  kubelet, kubeworker  Pulling image "localhost:5000/my-ubuntu"
  Warning  Failed     47s (x3 over 89s)  kubelet, kubeworker  Failed to pull image "localhost:5000/my-ubuntu": rpc error: code = Unknown desc = Error response from daemon: Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused
  Warning  Failed     47s (x3 over 89s)  kubelet, kubeworker  Error: ErrImagePull
  Normal   BackOff    10s (x6 over 89s)  kubelet, kubeworker  Back-off pulling image "localhost:5000/my-ubuntu"
  Warning  Failed     10s (x6 over 89s)  kubelet, kubeworker  Error: ImagePullBackOff

**Followed these below steps to push image to registry:**

Pull the ubuntu:16.04 image from Docker Hub.

$ docker pull ubuntu:16.04
Tag the image as localhost:5000/my-ubuntu. This creates an additional tag for the existing image. When the first part of the tag is a hostname and port, Docker interprets this as the location of a registry, when pushing.

$ docker tag ubuntu:16.04 localhost:5000/my-ubuntu
Push the image to the local registry running at localhost:5000:

$ docker push localhost:5000/my-ubuntu
Remove the locally-cached ubuntu:16.04 and localhost:5000/my-ubuntu images, so that you can test pulling the image from your registry. This does not remove the localhost:5000/my-ubuntu image from your registry.

$ docker image remove ubuntu:16.04
$ docker image remove localhost:5000/my-ubuntu
Pull the localhost:5000/my-ubuntu image from your local registry.

$ docker pull localhost:5000/my-ubuntu

kubectl create secret docker-registry regcred --docker-server=localhost:5000 --docker-username='<username>' --docker-password='<password>'  --docker-email=email@email.com

**Added below in /etc/default/docker**

DOCKER_OPTS='--insecure-registry localhost:5000'

**pod_spec :**

apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: localhost:5000/my-ubuntu
  imagePullSecrets:
  - name: regcred

**What you expected to happen**:
pod should come with local registry image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
The message "Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused" indicates that from the perspective of the kubelet there is no image registry running at localhost:5000

You must specify an image spec to a registry that the nodes have network visibility to

**Comment by imchand** [comment]
I am able to pull images from the private registry on the machine where Kubernetes is running. And able to list also. if that is the case, I should not be able to download from the machine right?

root@ubuntu:/# docker pull localhost:5000/my-ubuntu
Using default tag: latest
latest: Pulling from my-ubuntu
Digest: sha256:a4fc0c40360ff2224db3a483e5d80e9164fe3fdce2a8439d2686270643974632
Status: Downloaded newer image for localhost:5000/my-ubuntu:latest
localhost:5000/my-ubuntu:latest

**list images from catalog**
root@ubuntu:/# curl localhost:5000/v2/_catalog
{"repositories":["my-ubuntu"]}
root@ubuntu:/#
