### ISSUE TITLE
Need a new label "do-not-merge:required-jobs-failed"

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#90899]
Can we please add a label when we update the status(es) from prow jobs that are required have failed?

Reviewers can look for things to be lgtm-ed can use say : `label:approved -label:do-not-merge:required-jobs-failed"`
Approvers can rely on reviewers lgtm use say : `label:lgtm -label:do-not-merge:required-jobs-failed"`

Essentially, I feel this will help us write better queries to find things that are ready to merge given the limited bandwidth of reviewers and approvers.

**Comment by dims** [comment]
@nikhita @cblecker WDYT?

**Comment by LappleApple** [comment]
+1. This comes out of @dims and I trying to perform a targeted query for ready-to-merge PRs on behalf of a SIG with a heavy workload. Having this label would definitely help going forward.

**Comment by cblecker** [comment]
We can use `-status:failure` for this already in search queries. A new label isn't necessary :)

/close
