### ISSUE TITLE
Add a metric for apiserver self-requests

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#90908]
Currently we don't have an easy way of determining what number of requests are apiserver self-requests. This has historically bitten us, since we used to have a 50(?) QPS limit on apiserver self-requests (which thus has been removed). Even so, it would be a good idea to know this generally, since this may be helpful in pinpointing performance regressions for apiserver.

/sig api-machinery instrumentation

**Comment by ConcurrencyPractitioner** [comment]
@logicalhan Can this issue be considered a newbie one?  I'm hunting for issues which might be a good first PR.

**Comment by fedebongio** [comment]
In the triage meeting was mentioned that would be good to have similar issues to track other well known actors like controller-manager and kubelet. But let's keep this one for api-server calling itself to have it done.
/cc @cheftako @deads2k
