### ISSUE TITLE
User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by wonleing** [kubernetes/kubernetes#90924]
newly kubeadm init, and found following error in `kubectl cluster-info dump`

k8s.io/client-go/informers/factory.go:132: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope

What's reason? How to fix it?

**Comment by liggitt** [comment]
Is the message persistent or did the scheduler continue after that? Did the time correspond with the API server startup? Requests while the API server is starting can be rejected while the authorization cache is being initialized.

**Comment by wonleing** [comment]
The time (E0511 10:17:44.750080) does not match my current local time. Is there a method to flush the old message of dump?
