### ISSUE TITLE
kubectl deprecate message has typo

### ISSUE THREAD

**Issue by faintdream** [kubernetes/kubernetes#90935]
**What happened**: when i run `kubectl exec <somepod> date` , it shows a deprecate message which has a typo

example
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
[vagrant@localhost pod_manifests]$ kubectl exec kuard date
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Sat May  9 18:02:35 UTC 2020
[vagrant@localhost pod_manifests]$ kubectl exec kuard -- date
Sat May  9 18:02:40 UTC 2020

```
**What you expected to happen**: expected deprecate message without typo of having word kubectl once

**How to reproduce it (as minimally and precisely as possible)**:
run  `kubectl exec <somepod> date`
**Anything else we need to know?**:
no
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: running on vagrant box under minikube
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:minikube
- Network plugin and version (if this is a network-related bug): NA
- Others: NA
/sig ui

**Comment by oke-py** [comment]
#89919 fixed this issue. It may be available in the next release.

**Comment by faintdream** [comment]
Thanks for your reply and effort 👍

**Comment by neolit123** [comment]
/sig cli

> #89919 fixed this issue. It may be available in the next release.

/close
