### ISSUE TITLE
kubectl get -o yaml | json should not show managedFields by default

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#90933]
**What would you like to be added**:
With the introduction of `managedFields` in object meta `-o yaml` output is harder to read. I would like to propose that command `-o yaml | json` commands by default hide the `managedFields` from output and show it if user passes a flag like `--show-managed-fields`.

**Why is this needed**:
I miss the readable outputs of `-o yaml` command.

/sig cli

**Comment by liggitt** [comment]
Thanks for the request, https://github.com/kubernetes/kubernetes/issues/90066 is already open to discuss this
