### ISSUE TITLE
Kubernetes - Building - IPv4/IPv6 dual stack cluster

### ISSUE THREAD

**Issue by svangeepuram** [kubernetes/kubernetes#90930]
Hello!

I am not able to find proper documentation to build IPv4/IPv6 dual stack cluster.  Please provide specific references/instructions to build dual stack Cluster.

Regards,
Chary

**Comment by aojea** [comment]
It's documented here 
https://kubernetes.io/docs/concepts/services-networking/dual-stack/

**Comment by liggitt** [comment]
Thanks for the link @aojea 

/close
