### ISSUE TITLE
`kubectl apply --server-side` doesn't honor `--force` flag

### ISSUE THREAD

**Issue by ndrpnt** [kubernetes/kubernetes#90931]
**What happened**:

A resource is not replaced (deleted and recreated) when passing the `--force`
flag to `kubectl apply --server-side` and the change cannot be applied.

**What you expected to happen**:

I expected the service to be replaced.

**How to reproduce it (as minimally and precisely as possible)**:

``` console
$ cat >svc.yaml <<EOF
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  clusterIP: 10.97.219.180
  ports:
  - name: "9876"
    port: 9876
    protocol: TCP
    targetPort: 9876
  type: ClusterIP
EOF

$ kubectl apply -f svc.yaml --server-side
service/foo serverside-applied

$ cat >svc.yaml <<EOF
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  clusterIP: 10.97.219.181 # Updated
  ports:
  - name: "9876"
    port: 9876
    protocol: TCP
    targetPort: 9876
  type: ClusterIP
EOF

$ kubectl apply -f svc.yaml --server-side --force
The Service "foo" is invalid: spec.clusterIP: Invalid value: "10.97.219.181": field is immutable
```

**Anything else we need to know?**:

**Environment**:

`kind`

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by apelisse** [comment]
Good to know, that's certainly worthy of a fix.

**Comment by kwiesmueller** [comment]
This is slightly related: https://github.com/kubernetes/kubernetes/issues/90968
If we want to support `--force` we could try and make the behavior clearer.

**Comment by lavalamp** [comment]
@kubernetes/sig-cli-maintainers Can you weigh in on how important this is?

We feel that `--force` is super, super dangerous in general. It's also very easy to confuse it with `--force-conflicts` for server side apply, so it's extra dangerous.

Do we need to implement this field for this command? Can we give an error, like "use one of: --force-conflicts or --delete-then-create"?

Can SIG CLI do something about this flag in general?

**Comment by apelisse** [comment]
@lavalamp Noted, I'll make sure this is in the agenda for the next sig-cli meeting.

**Comment by brianpursley** [comment]
This PR was merged recently that I think will prevent this:
https://github.com/kubernetes/kubernetes/pull/90225

**Comment by apelisse** [comment]
I don't think the two are related. `--force` is now error-ing when used with `--dry-run=server`, but it'll still fail with server-side apply.

**Comment by brianpursley** [comment]
You're right... my recall was bad.  I deleted my comment where I thought https://github.com/kubernetes/kubernetes/pull/90225 was this, but it is not.  Sorry about that

**Comment by ykakarap** [comment]
@apelisse Looks like in the SIG-CLI meeting it was decided to not enable the user to use the `--server-side` and `--force` flag together. kubectl should fail immediately with a warning that `--force` should not be used with server side apply.

Do you mind if I start working on this issue? I will reach out to you and other members of the SIG to get more details needed.

I am a new contributor to k8s and would like to work on this issue.

**Comment by apelisse** [comment]
@ykakarap Thanks for summarizing the discussion! I'd love to see you submit a PR for that, that's awesome!
