### ISSUE TITLE
[Failing Test] gce-device-plugin-gpu-master (ci-kubernetes-e2e-gce-device-plugin-gpu)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#90947]
**Which jobs are failing**:
> gce-device-plugin-gpu-master (ci-kubernetes-e2e-gce-device-plugin-gpu)

**Which test(s) are failing**:
>BeforeSuite
>Overall
>Test

**Since when has it been failing**:
> 05-09 00:30 PDT

**Testgrid link**:
> https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

**Reason for failure**:
> I0510 05:48:20.315] May 10 05:48:20.244: INFO: At 2020-05-10 05:36:47 +0000 UTC - event for coredns-78ff568f7c-wt5xr: {kubelet bootstrap-e2e-minion-group-dxkj} FailedMount: MountVolume.SetUp failed for volume "coredns-token-qjvl4" : failed to sync secret cache: timed out waiting for the condition

> I0510 05:48:26.112] panic: Get https://10.0.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.0.0.1:443: i/o timeout

> I0510 05:48:26.269] ERROR: logging before flag.Parse: E0510 05:48:11.697725       1 nanny_lib.go:87] Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing

**Comment by alejandrox1** [comment]
Looking at 1 of the runs, these pods failed to reach a "Running" state after 10 minutes
```
I0509 07:49:03.739] May  9 07:49:03.736: INFO: coredns-78ff568f7c-tp5qs                    bootstrap-e2e-minion-group-gwgw  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:51 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:51 +0000 UTC ContainersNotReady containers with unready status: [coredns]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:51 +0000 UTC ContainersNotReady containers with unready status: [coredns]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:51 +0000 UTC  }]
I0509 07:49:03.748] May  9 07:49:03.736: INFO: kube-proxy-bootstrap-e2e-minion-group-8xj3  bootstrap-e2e-minion-group-8xj3  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:32 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:32 +0000 UTC ContainersNotReady containers with unready status: [kube-proxy]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:32 +0000 UTC ContainersNotReady containers with unready status: [kube-proxy]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:32 +0000 UTC  }]
I0509 07:49:03.749] May  9 07:49:03.736: INFO: kube-proxy-bootstrap-e2e-minion-group-gwgw  bootstrap-e2e-minion-group-gwgw  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:37 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:37 +0000 UTC ContainersNotReady containers with unready status: [kube-proxy]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:37 +0000 UTC ContainersNotReady containers with unready status: [kube-proxy]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:37 +0000 UTC  }]
I0509 07:49:03.750] May  9 07:49:03.736: INFO: kube-proxy-bootstrap-e2e-minion-group-q8bx  bootstrap-e2e-minion-group-q8bx  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:33 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:33 +0000 UTC ContainersNotReady containers with unready status: [kube-proxy]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:33 +0000 UTC ContainersNotReady containers with unready status: [kube-proxy]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:33 +0000 UTC  }]
I0509 07:49:03.751] May  9 07:49:03.736: INFO: kubernetes-dashboard-864d864f44-qkx5s       bootstrap-e2e-minion-group-q8bx  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:50 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:47:22 +0000 UTC ContainersNotReady containers with unready status: [kubernetes-dashboard]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:47:22 +0000 UTC ContainersNotReady containers with unready status: [kubernetes-dashboard]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:50 +0000 UTC  }]
I0509 07:49:03.751] May  9 07:49:03.736: INFO: metrics-server-v0.3.6-5597cd7488-5ttq6      bootstrap-e2e-minion-group-q8bx  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:59 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:47:25 +0000 UTC ContainersNotReady containers with unready status: [metrics-server]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:47:25 +0000 UTC ContainersNotReady containers with unready status: [metrics-server]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-05-09 07:37:56 +0000 UTC  }]
```

Then, while dumping events from the kube-system namespace these couple look interesting
```
I0509 07:49:03.831] May  9 07:49:03.806: INFO: At 2020-05-09 07:37:34 +0000 UTC - event for fluentd-gcp-scaler-54b85fcc78-5l5kh: {default-scheduler } FailedScheduling: 0/3 nodes are available: 1 node(s) had taint {node.kubernetes.io/network-unavailable: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 1 node(s) were unschedulable.
```
```
I0509 07:49:03.832] May  9 07:49:03.806: INFO: At 2020-05-09 07:37:34 +0000 UTC - event for kube-proxy-bootstrap-e2e-minion-group-8xj3: {kubelet bootstrap-e2e-minion-group-8xj3} Failed: Error: ImagePullBackOff
I0509 07:49:03.832] May  9 07:49:03.806: INFO: At 2020-05-09 07:37:34 +0000 UTC - event for kube-proxy-bootstrap-e2e-minion-group-8xj3: {kubelet bootstrap-e2e-minion-group-8xj3} BackOff: Back-off pulling image "k8s.gcr.io/kube-proxy:v1.19.0-alpha.3.91_7d53ecee37ceba"
```

That kube proxy image seems to not exist (?), I tried pulling it from another machine and got this
```
$ docker pull k8s.gcr.io/kube-proxy:v1.19.0-alpha.3.91_7d53ecee37ceba
Error response from daemon: manifest for k8s.gcr.io/kube-proxy:v1.19.0-alpha.3.91_7d53ecee37ceba not found: manifest unknown: Failed to fetch "v1.19.0-alpha.3.91_7d53ecee37ceba" from request "/v2/kube-proxy/manifests/v1.19.0-alpha.3.91_7d53ecee37ceba".
```

The commit that is part of the kube proxy tag, 7d53ecee37ceba , does coincide with the k/k commit that went in right as this test broke https://github.com/kubernetes/kubernetes/compare/a3cf6fc0a...7d53ecee3 and that commit range only introduces this PR https://github.com/kubernetes/kubernetes/pull/90575
The following CI tests are listed fro that specific commit (when looking at the commit history of k/k)
* ci-kubernetes-bazel-build  https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-build/1259001233771859968/
* ci-kubernetes-bazel-test https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-test/1259001233776054272
* post-kubernetes-bazel-build https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kubernetes-bazel-build/1259001233771859969
* post-kubernetes-bazel-test  https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kubernetes-bazel-test/1259001233767665664

**Comment by hasheddan** [comment]
@alejandrox1 looks like `push-build` failed in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-build/1259001233771859968/

```
I0509 06:12:48.978] Call:  gsutil ls gs://kubernetes-jenkins/logs/ci-kubernetes-bazel-build/1259001233771859968/artifacts
W0509 06:12:50.622] CommandException: One or more URLs matched no objects.
E0509 06:12:50.849] Command failed
I0509 06:12:50.850] process 6256 exited with code 1 after 0.0m
```

/cc @justaugustus

**Comment by alejandrox1** [comment]
I think it there may be an outdated manifests used for this job.
The kube proxy images are being built.
If you look for `kube-proxy-bootstrap-e2e-minion-group` in the logs of other ci jobs, i.e., https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1259808048835203074 you will see that an alpha 3 with a k/k commit is being used.
For example, 
```
k8s.gcr.io/kube-proxy-amd64:v1.19.0-alpha.3.138_2b2cf8df303aff
```

The thing is that, I think, there should be a mention of the ARCH in the container image, e.g., amd64 in the above example, where as teh GPU job doesnt have any arch.

**Comment by alejandrox1** [comment]
Mmm  though im not 100 sold on the image name being the problem. Checking out both kube-proxy and kube-proxy-amd64 both exist and both seem to be updated frequently
https://console.cloud.google.com/gcr/images/k8s-artifacts-prod-bak/US

**Comment by aojea** [comment]
/assign 
I had similar issues trying to use the debian-iptables image, let me check if I'm able to solve it here too


/cc @justaugustus @dims @BenTheElder 
FYI

**Comment by hasheddan** [comment]
@aojea this may help:

```
W0501 20:03:19.761] INFO: Call stack for the definition of repository 'debian-iptables-amd64' which is a container_pull (rule definition at /bazel-scratch/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/io_bazel_rules_docker/container/pull.bzl:173:18):
W0501 20:03:19.761]  - <builtin>
W0501 20:03:19.762]  - /workspace/k8s.io/kubernetes/build/workspace.bzl:110:9
W0501 20:03:19.762]  - /workspace/k8s.io/kubernetes/build/workspace.bzl:53:5
W0501 20:03:19.762]  - /workspace/k8s.io/kubernetes/WORKSPACE:81:1
W0501 20:03:19.765] ERROR: An error occurred during the fetch of repository 'debian-iptables-amd64':
W0501 20:03:19.766]    Traceback (most recent call last):
W0501 20:03:19.766] 	File "/bazel-scratch/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/io_bazel_rules_docker/container/pull.bzl", line 128
W0501 20:03:19.766] 		fail(<1 more arguments>)
W0501 20:03:19.766] 	File "/bazel-scratch/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/io_bazel_rules_docker/container/pull.bzl", line 128, in fail
W0501 20:03:19.766] 		" ".join(args)
W0501 20:03:19.766] expected string for sequence element 0, got 'path'
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-build/1259001233771859968/

**Comment by aojea** [comment]
Seems the job is failing to install the nodes with an error related to the LICENSES folder 

```
May 09 07:37:12.865188 bootstrap-e2e-minion-group-8xj3 configure.sh[794]: mv: cannot overwrite non-directory '/home/kubernetes/LICENSES' with directory '/home/kubernetes/kubernetes/LICENSES'
May 09 07:37:12.865606 bootstrap-e2e-minion-group-8xj3 systemd[1]: kube-node-installation.service: Main process exited, code=exited, status=1/FAILURE
May 09 07:37:12.866701 bootstrap-e2e-minion-group-8xj3 systemd[1]: Failed to start Download and install k8s binaries and configurations.
May 09 07:37:12.866744 bootstrap-e2e-minion-group-8xj3 systemd[1]: kube-node-installation.service: Unit entered failed state.
May 09 07:37:12.866786 bootstrap-e2e-minion-group-8xj3 systemd[1]: kube-node-installation.service: Failed with result 'exit-code'.
```

Seems LICENSES has a recent history of changes:
https://github.com/kubernetes/kubernetes/pull/85220
https://github.com/kubernetes/kubernetes/pull/90575

I'm not able to correlate between the changes and job failures, @thockin @dims @liggitt you have better insights in the LICENSES folder, what's the best way to proceed here?

**Comment by liggitt** [comment]
I think https://github.com/kubernetes/kubernetes/pull/90575 changed LICENSES in the root of the built artifacts from a file to a folder

/assign @thockin

**Comment by thockin** [comment]
FTR, I am looking at this, please don't revert my revert revert yet

**Comment by thockin** [comment]
Failed to repro, but I also get:

```
Ran 0 of 5095 Specs in 6.856 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 5095 Skipped
```

**Comment by aojea** [comment]
> Failed to repro, but I also get:
> 
> ```
> Ran 0 of 5095 Specs in 6.856 seconds
> SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 5095 Skipped
> ```

@thockin seems that this is only affecting the *-plugin-gpu-* jobs

**Comment by thockin** [comment]
Yeah, I think I messed up the `kubetest` invocation.  It should have run tests.

**Comment by thockin** [comment]
OK, I got it to run a test but it doesn't fail this way.  I have another umask fix, let me back that out.

**Comment by thockin** [comment]
I can't get it to fail like this.

On my run I see 27/27 pods running, but this run seems stuck with:
`24 / 30 pods in namespace 'kube-system' are running and ready`
...where that varies from 24 - 26.

My personal kubetest invocation:

```
kubetest '--dump=/tmp/workspace/_artifacts' --build --up --test --down '--provider=gce' '--cluster=bootstrap-e2e' '--gcp-network=bootstrap-e2e' '--check-leaked-resources' '--gcp-node-image=gci' '--gcp-project-type=gpu-project' '--gcp-zone=us-west1-b' '--test_args=--ginkgo.focus='Feature:GPUDevicePlugin' --minStartupPods=8' '--timeout=180m' --gcp-project=thockin-dev-2
```

And my run failed, but with:

```
• Failure [62.008 seconds]
[sig-scheduling] [Feature:GPUDevicePlugin]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:40
  run Nvidia GPU Device Plugin tests [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/nvidia-gpus.go:218

  May 11 13:18:57.007: failed to get pods controlled by the nvidia-driver-installer daemonset
  Unexpected error:
      <*errors.errorString | 0xc0034082b0>: {
          s: "Timeout while waiting for pods with label k8s-app=nvidia-driver-installer",
      }
      Timeout while waiting for pods with label k8s-app=nvidia-driver-installer
  occurred
```

**Comment by thockin** [comment]
Further more, I can't think of ANY way the old non-directory LICENSES file would be present unless there's some cache that is not invalidated when it needs to be and is leaking across tests

**Comment by justaugustus** [comment]
> Further more, I can't think of ANY way the old non-directory LICENSES file would be present unless there's some cache that is not invalidated when it needs to be and is leaking across tests

@spiffxp @fejta -- is this greenhouse/bazel?

**Comment by spiffxp** [comment]
I sincerely doubt greenhouse.  I don't understand enough about the bazel build in this repo to say one way or the other.

Why it would be consistently affecting this and no other job that runs in the same cluster, e.g.
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default
- https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress

**Comment by aojea** [comment]
> Why would it be consistently affecting this and no other job that runs in the same cluster, e.g.
> 
> * https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default
> * https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress

and why started to fail this morning, if the patch was merged a few days ago?

**Comment by thockin** [comment]
Jordan figured it out.  This node image has /home/kubernetes baked in.

**Comment by thockin** [comment]
2nd time I get to use this today:  

https://66.media.tumblr.com/8bda4db3eec8e4af5a623730db5f3404/tumblr_pozpf78qTa1xz4q4mo1_500.gifv
