### ISSUE TITLE
Watch event test verification tooling

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#90957]
* [Ticket status](#sec-1)
* [Current problem](#sec-2)
* [Proposed solution](#sec-3)

This Issue replace #90574

# Ticket status
* [ ]  [K8s watch events test tooling #323](https://github.com/cncf/apisnoop/pull/323)
* [ ]  [Watch event test verification tooling #90574](https://github.com/kubernetes/kubernetes/issues/90574)
* [X] [PR #91416 ](https://github.com/kubernetes/kubernetes/pull/91416)
# Current problem
Watch events may be missed and the test may still pass. We need to ensure that all expected watch events are seen.

Watch events are not collected and checked at the end of the test.

# Proposed solution
In order to solve the problem, we must collect all watch events as they come in and perform a check at the end of the test to ensure that the order is correct and they contain no errors.

```go
package main

import (
  "fmt"
)

func main() {
  expectedWatchEventsAll := [][]string{
    {
      "ADDED",
      "ADDED",
      "DELETED",
    },
    {
      "ADDED",
      "MODIFIED",
      "MODIFIED",
      "DELETED",
    },
    {
      "ADDED",
      "MODIFIED",
      "DELETED",
    },
  }
  for expectedExampleInt, expectedWatchEvents := range expectedWatchEventsAll {
	  fmt.Println("Running example", expectedExampleInt)
    allowedAttempts := 3
    failure := VerifyWatchEventOrder(allowedAttempts, expectedWatchEvents, func() []string {
      var myWatchEvent string
      var watchEvent []string
      fmt.Println("An event takes place (1/3)")
      myWatchEvent = "ADDED"
      watchEvent = append(watchEvent, myWatchEvent)

      fmt.Println("An event takes place (2/3)")
      myWatchEvent = "MODIFIED"
      watchEvent = append(watchEvent, myWatchEvent)

      fmt.Println("An event takes place (3/3)")
      myWatchEvent = "DELETED"
      watchEvent = append(watchEvent, myWatchEvent)

      return watchEvent
    })
    if failure != "" {
      fmt.Println(failure, "watch events occured in the wrong or incorrect order")
    }
    fmt.Println("Check complete")
  }
}

func VerifyWatchEventOrder(retries int, expectedWatchEvents []string, scenario func() []string) (failure string) {
  var attemptContainsFailure bool
attempts:
  for try := 1; try <= retries; try++ {
    if try == retries {
      return failure
    }
    actualWatchEvents := scenario()
    if len(expectedWatchEvents) != len(actualWatchEvents) {
      failure = "expected watch events count does not match the count of actual watch events"
      attemptContainsFailure = true
      continue
    }
    for watchEventInt, watchEvent := range actualWatchEvents {
      if expectedWatchEvents[watchEventInt] != watchEvent {
        failure = fmt.Sprintf("(index %v) %v not found, found %v instead. %v/%v attempts", watchEventInt, expectedWatchEvents[watchEventInt], watchEvent, try, retries)
        attemptContainsFailure = true
      }
    }
    if attemptContainsFailure == false {
      failure = ""
      break attempts
    }
  }
  return failure
}
```

```
Running example 0
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
(index 1) ADDED not found, found MODIFIED instead. 2/3 attempts watch events occured in the wrong or incorrect order
Check complete
Running example 1
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
expected watch events count does not match the count of actual watch events watch events occured in the wrong or incorrect order
Check complete
Running example 2
An event takes place (1/3)
An event takes place (2/3)
An event takes place (3/3)
Check complete
```

**Comment by Riaankl** [comment]
This Issue replace #90574

**Comment by BobyMCbobs** [comment]
AI: Must allow for other events to occur through the expected watch events stream

# Example
expected watch events:
1. Added
2. Modified
3. Deleted

must allow the following to be valid:
1. Added
2. Modified
3. Modified
4. Deleted

**Comment by BobyMCbobs** [comment]
# Tooling goals
- [ ] Set up a watch for resource through a static label to the resource with DynamicClient
- [ ] Manage the watch if it dies
- [ ] Feed the watch to the function
- [ ] Read all the watch events from the `resourceWatch.ResultChan()` at the end of the test, ensuring that the events occur
  - question: What does doing this mean to tests which check `watchEvent.Object` data? (e.g: https://github.com/kubernetes/kubernetes/pull/90942/files#diff-0f856ff011970dca55a2cd916b9ddcf0R893 - waits for values, sourced from watch)
- [ ] Retry the test, upon failure
- [ ] Manage the resources on retry (delete)

**Comment by johnbelamaric** [comment]
More or less, yes. If we need to read results mid-test, I think that will be OK, rather than waiting for the end. The main point is to wrap the watch such that it gets restarted if it fails. That wrapper will need to sit between the raw watch channel and the test:

raw watch -> channel -> wrapper (restarts watch if closes/fails prematurely) -> channel consumed in test

I'm a little surprised there isn't already a sort of "buffered watch" object that does this already @smarterclayton ?

You'll also need a stop channel for the go routine started by the wrapper, so that at the end of the test you can stop that go routine and watch.

**Comment by johnbelamaric** [comment]
Also, if we have the "protected watch" wrapper, not sure we need to retry the test on failure. AFAIU, the only reason we wouldn't see the watch events we expected would be because of etcd compaction, which would not be expected to happen in e2e clusters, and even if it did it would not happen to event histories that are brand new (i.e., it only compacts old history). Again would like @smarterclayton to confirm.

**Comment by hh** [comment]
/reopen

While we did push through this first iteration, this ticket is for ongoing discussion of watch tooling and refactoring of the approach.

**Comment by Riaankl** [comment]
/reopen

While we did push through this first iteration, this ticket is for ongoing discussion of watch tooling and refactoring of the approach.
