### ISSUE TITLE
VolumeBinding improvements track issue

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#90962]
Once volume binding logic is implemented as a VolumeBinding scheduler plugin (#83726), the following improvements can be done:

- [x] Revert assumed volume cache in `Unreserve` extension point (https://github.com/kubernetes/kubernetes/pull/82934#issuecomment-538269188) (https://github.com/kubernetes/kubernetes/issues/91654)
- [x] Share pod volume binding cache via `framework.CycleState` (see [design](https://github.com/kubernetes/kubernetes/issues/56180#issuecomment-457046118)) (https://github.com/kubernetes/kubernetes/issues/92186)
- [x] update comments in `volumescheduling` pkg to reflect latest change (https://github.com/kubernetes/kubernetes/pull/91296)
- ~~[ ] remove fake volume binder, use fake kubernetes client with real VolumeBinder~~ https://github.com/kubernetes/kubernetes/issues/92142
- [ ] more benchmark tests for VolumeBinding

https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/

**Comment by cofyc** [comment]
/assign
/sig scheduling
/sig storage
cc @msau42 @ahg-g

**Comment by alculquicondor** [comment]
Can you add `Remove .bindTimeoutSeconds once we have a volume binding plugin` to your list?

**Comment by cofyc** [comment]
Removing `KubeSchedulerConfiguration.BindTimeoutSeconds` is tracked in #90958, you can add #90958 in your umbrella issue #89701.

**Comment by alculquicondor** [comment]
Done, thanks

**Comment by alculquicondor** [comment]
Hi @cofyc is there any progress on this?

**Comment by alculquicondor** [comment]
@cofyc was there any remaining work here?

**Comment by cofyc** [comment]
no

I was planning to add some benchmarks. It's not urgent and can be tracked in a separate issue.
