### ISSUE TITLE
Generate API documentation for Kubernetes using Swagger

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#9097]
I'm in the process of generating AsciiDoc / Markdown from swagger specs.  General goals:
1. Generate documentation files suitable for inclusion into formal docs (OpenShift uses AsciiDoc -> DocBook)
2. Generate tables and examples for all objects that correctly represent the action
3. Have richer descriptions for each object and operation than we currently include, so that users understand what the object does (not just its fields).

Primary angle of attack is https://github.com/RobWin/swagger2markup
### Issues encountered
- [swagger-parser](https://github.com/swagger-api/swagger-parser) doesn't handle the "TRACE" verb - going to open a pull to fix that
- PATCH documents don't properly document their body parameter model type (no schema) - should be "any" which we can probably make happen with `map[string]interface{}`.  Also, the return type should be versionedObject
- We don't have descriptions on our path parameters for individual types, so any descriptions have to be external (swagger2markup supports external descriptions but this should come from the type).
- Our top level API objects don't have title or description (description really needs to be a long description - it's the description of the API)
- Our model objects don't have descriptions
- Our operations don't have descriptions
- go-restful ApiDeclaration doesn't have "Info" which contains title and description, used by the generator to frame the document
- Our paths should have descriptions like "Use this path to operate on lists of Pods", "Use this path to operate on individual Pods", "Use this path to control the status of a Pod"
- Our operation descriptions should be capitalized - those are used as headers and TOC lines in doc
- Our dates and times are missing format "date-time"
- runtime.RawExtension should be documented more like "any" - RawJSON is not actually exposed.  May need to set JSON struct tags on it.
- Swagger model order is random because ApiDeclarations.Models is a map[string]Object.  We need to convert it to a `[]...` in the swagger serialization format.

**Comment by smarterclayton** [comment]
We don't set `util.Time` to `date-time`... intentional?

**Comment by smarterclayton** [comment]
Swagger 1.2 and 2.0 don't support TRACE - https://github.com/swagger-api/swagger-spec/issues/325

**Comment by bgrant0607** [comment]
This would be awesome.

cc @RichieEscarez @nikhiljindal 

date-time: Not intentional: #2968

Other known issues:
* #6842
* #6167
* #4700
* #2971
* #3059
* #7100
* #5331
* #8116

**Comment by smarterclayton** [comment]
Will have an example of the output shortly so you can see what it looks like.

**Comment by RichieEscarez** [comment]
Yes this would be great (@MikeJeffrey and I recently discussed the need for this)!

**Comment by smarterclayton** [comment]
Examples http://docs.openshift.org/latest/rest_api/openshift_v1.html and http://docs.openshift.org/latest/rest_api/kubernetes_v1.html

**Comment by smarterclayton** [comment]
swagger2markup can also inline descriptions - that was used to get http://docs.openshift.org/latest/rest_api/kubernetes_v1.html#v1-persistentvolumeclaim

**Comment by bgrant0607** [comment]
Cool. Inlined from where?

**Comment by smarterclayton** [comment]
Directory structure - the generator looks for a file in a directory that corresponds to the name of the object or the name of the topic. It slurps in the asciidoc file and then generates the rest of the structure.

**Comment by RichieEscarez** [comment]
@smarterclayton does Markdown get automatically generated too (along with the AsciiDoc you use)? Im working on moving our user doc into GitHub pages and would like a copy of the API in Markdown.

**Comment by smarterclayton** [comment]
swagger2markup can output to Markdown.  Asciidoc is the default.

----- Original Message -----

**Comment by bgrant0607** [comment]
Any progress on this?

**Comment by smarterclayton** [comment]
Will open a pull next week when I get back from PTO

**Comment by bgrant0607** [comment]
@andronat pointed out [Slate](https://github.com/tripit/slate) on #11253

**Comment by bgrant0607** [comment]
We're doing this now.

@caesarxuchao @nikhiljindal @RichieEscarez Anything we should fork off this issue before closing?

**Comment by caesarxuchao** [comment]
I don't have more issues.

**Comment by RichieEscarez** [comment]
I think the inconsistency between the GitHub repo and the Kubernetes.io versions of the API should be resolved.

Issue:
Today, out on Kubernetes.io, we override all the embedded CSS that is included with the current versions of these [html formatted API files](http://kubernetes.io/v1.0/docs/api-reference/operations.html) in order for it to display with the same color and font as our other docs. 

From in the Github repo, the [raw versions of these API files](https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/v1.0.2/docs/api-reference/operations.html) get inconsistently displayed in a different color.

Aside from the color and font differences between our two sources, the header in both files is also different (path vs. operations).

Possible solutions:
 * output to markdown instead (convert it to HTML for the kubernetes site like all other docs)
 * output html files with Kubernetes specific CSS (same color and font as our site)

**Comment by caesarxuchao** [comment]
> I think the inconsistency between the GitHub repo and the Kubernetes.io versions of the API should be resolved.

I don't know if this is necessary, they are two different websites, people won't expect the format to be the same.

> Aside from the color and font differences between our two sources, the header in both files is also different (path vs. operations).
Good catch, this could be fixed by adding a line in https://github.com/kubernetes/kubernetes/blob/master/hack/gen-swagger-doc/gen-swagger-docs.sh and update the container image. Sorry I don't have time to do that this week.

**Comment by bgrant0607** [comment]
@nikhiljindal We should fork another issue to track all of the swagger problems.

**Comment by RichieEscarez** [comment]
Re:
*... the header in both files is also different (path vs. operations).*

Chao fixed the page title mismatch in #15040

**Comment by RichieEscarez** [comment]
There is also: #15343

**Comment by bgrant0607** [comment]
What's left to do here?

**Comment by caesarxuchao** [comment]
There are no big problems, but several enhancements nice to have. The left issues from smarterclayton's first comment
- [ ] Swagger model order is random because ApiDeclarations.Models is a map[string]Object. We need to convert it to a []... in the swagger serialization format.
- [ ] Our operation descriptions should be capitalized - those are used as headers and TOC lines in doc
- [ ] Our paths should have descriptions like "Use this path to operate on lists of Pods", "Use this path to operate on individual Pods", "Use this path to control the status of a Pod"
- [ ] PATCH documents don't properly document their body parameter model type (no schema) - should be "any" which we can probably make happen with map[string]interface{}. (see if http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html#_unversioned_patch is good enough?)

**Comment by smarterclayton** [comment]
This was done by many people.
