### ISSUE TITLE
Azure disk detach/attach failure - due to deleted node (vmss)

### ISSUE THREAD

**Issue by stackempty** [kubernetes/kubernetes#90986]
**What happened**:

Same symtoms as https://github.com/kubernetes/kubernetes/pull/82640

The detach is not successful until controller-manager is restarted

controller-manager logs:
```
I0508 07:02:24.420727       1 reconciler.go:229] attacherDetacher.DetachVolume started for volume "pvc-<pvc-id>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>") on node "workeb81800007f"
I0508 07:02:24.424524       1 operation_generator.go:1489] Verified volume is safe to detach for volume "pvc-<pvc-id>" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>") on node "workeb81800007f"
E0508 07:02:27.760753       1 azure_controller_vmss.go:162] azureDisk - detach disk(, /subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>) on rg(rg-<resource-group>) vm(workeb81800007f) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 267 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
E0508 07:02:31.050723       1 azure_controller_vmss.go:162] azureDisk - detach disk(, /subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>) on rg(rg-<resource-group>) vm(workeb81800007f) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 267 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
E0508 07:02:45.383423       1 azure_controller_vmss.go:162] azureDisk - detach disk(, /subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>) on rg(rg-<resource-group>) vm(workeb81800007f) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 267 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
E0508 07:02:56.469513       1 azure_controller_vmss.go:162] azureDisk - detach disk(, /subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>) on rg(rg-<resource-group>) vm(workeb81800007f) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 267 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
E0508 07:03:19.303335       1 azure_controller_vmss.go:162] azureDisk - detach disk(, /subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>) on rg(rg-<resource-group>) vm(workeb81800007f) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 267 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
W0508 07:13:39.172799       1 azure_controller_common.go:273] azureDisk - Cannot find node "workeb81800007f", DisksAreAttached will assume disks [kubernetes-dynamic-pvc-<pvc-id-02> kubernetes-dynamic-pvc-<pvc-id>] are not attached to it.
```

**What you expected to happen**:
The detach operation should know that a node is not active or its been deleted and should assume the disk is detached.

**How to reproduce it (as minimally and precisely as possible)**:

This seems quite hard to reproduce, but we do run into it quite a few times where the pod is stuck in `ContainerCreating`, because the controller-manager is unable to detach disks from deleted nodes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.11
- Cloud provider or hardware configuration: azure (self-managed)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 5.0.0-1027-azure
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cloud-provider
/area provider/azure

paging @andyzhangx @feiskyer

**Comment by stackempty** [comment]
paging @andyzhangx @feiskyer

**Comment by andyzhangx** [comment]
hi @stackempty have you done sth manually on the node? if node is deleted finally, the disk would be in unattached state finally, then disk attach to another node would succeed finally.

**Comment by andyzhangx** [comment]
as discussed offline, the issue is probably due to vmss instance compute name change(`workeb81800007f`), user should **not** change vmss instance compute name, otherwise it would break disk attach/detach, since compute name is used in vmss node name passing, code is here: https://github.com/kubernetes/kubernetes/blob/v1.15.11/staging/src/k8s.io/legacy-cloud-providers/azure/azure_instances.go#L267-L272

**Comment by stackempty** [comment]
Hi @andyzhangx 

We don't change the instance compute name and i see the right format in the azure metadata service for the instances - What you're referring to seems to be the computer name, and we do use the defaults as provided by azure. See https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids#scale-set-vm-computer-name

The attach/detach operations works fairly well most of the time, and I think we're running into some edge case here.

One thing i might have missed out is the fact that there seems to have been an issue with the VM at the time. So the VM was present, but azure platform would return 400 bad request for a detach operation which probably led to this ..

```
E0508 07:03:19.303335       1 azure_controller_vmss.go:162] azureDisk - detach disk(, /subscriptions/<sub-id>/resourceGroups/rg-<resource-group>/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-<pvc-id>) on rg(rg-<resource-group>) vm(workeb81800007f) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 267 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
```

```
node_lifecycle_controller.go:154] error checking if node workeb81800007f is shutdown: failed to get power status for node "workeb81800007f"
```

But when the VM was eventually deleted by the autoscaler, the re-attach was never attempted by the reconciler it would seem. and the last message about that disk was 

```
 azure_controller_common.go:273] azureDisk - Cannot find node "workeb81800007f", DisksAreAttached will assume disks [kubernetes-dynamic-pvc-<disk-id-1> kubernetes-dynamic-pvc-<disk-id-2>] are not attached to it.
```

**Comment by andyzhangx** [comment]
@feiskyer `workeb81800007f` should be a valid compute name according to https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids#scale-set-vm-computer-name, do you know why we define the format like this?
https://github.com/kubernetes/kubernetes/blob/d94a81c724ea8e1ccc9002d89b7fe81d58f89ede/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache_test.go#L37-L57

**Comment by feiskyer** [comment]
@andyzhangx The function `extractVmssVMName()` is used to get the name from IMDS, and its format is `<scalesetname>_<vmId>`.

**Comment by feiskyer** [comment]
From the above `compute.VirtualMachineScaleSetVMsClient#Update` errors, seems the request has been sent to VMSS but failed because it's not active. @stackempty Do you know the VM state during that time?

**Comment by stackempty** [comment]
I am not sure of the state at the time, but i believe the VM was in some kind of failed state. The VM has since been deleted, but we had errors on the scaleset at the time.

The events on the VMSS look like this.

```
Your virtual machine scale set is degraded because 1 out of 22 virtual machines are unavailable. Use Azure resource health and the troubleshoot tool to address the issues with the unavailable virtual machines
```

The VM was eventually deleted by the autoscaler, but the disk was never re-attached to a different node, and the pod remained in `ContainerCreating` for about 2 days until controller-manager was restarted.

**Comment by bergerx** [comment]
Apparently we hit this issue today as a result of replacing the nodepool. We added 2 new nodepools and deleted the old one, and now we have 718 of 1672 pods stuck with this error in one of our clusters. The volumes are failing to be attached to new pods, the VMSS for old nodepool is removed. In AKS portal disks are still reported to be attached to VM instances in the VMSS that was deleted. hundreds of pods are stuck in Init state won't likely go forward.

**Comment by andyzhangx** [comment]
> Apparently we hit this issue today as a result of replacing the nodepool. We added 2 new nodepools and deleted the old one, and now we have 718 of 1672 pods stuck with this error in one of our clusters. The volumes are failing to be attached to new pods, the VMSS for old nodepool is removed. In AKS portal disks are still reported to be attached to VM instances in the VMSS that was deleted. hundreds of pods are stuck in Init state won't likely go forward.
> 
> /remove-lifecycle rotten

@bergerx I have seen similar issue when handling one customer's case, it's probably caused by broken vmss cluster, pls file a ticket to VMSS team to fix the issue.

**Comment by andyzhangx** [comment]
I happened to find this issue in one customer case, this issue is caused by obsolete cache in kube-controller-manager, should skip attach/detach retry when it's 400, below are the details, following two instances were deleted 3min ago before kube-controller-manager trying to attach/detach:
```
E0929 06:15:58.829232       1 azure_controller_common.go:201] azureDisk - detach disk(, /subscriptions/xxx/resourceGroups/mc_rg-corvette_corvette_northeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-313789cd-82a4-4a16-be0e-11a75b6cc7af) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 1177 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"

E0929 06:15:43.823113       1 azure_controller_vmss.go:165] azureDisk - detach disk(, /subscriptions/xxx/resourceGroups/mc_rg-corvette_corvette_northeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-ce73f28d-3ad7-47ce-a1e3-07ff4dcce4c2) on rg(mc_rg-corvette_corvette_northeurope) vm(aks-platform-34667809-vmss0000w0) failed, err: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The provided instanceId 1152 is not an active Virtual Machine Scale Set VM instanceId." Target="instanceIds"
```

 - workaround
restart kube-controller-manager should work
