### ISSUE TITLE
Golang errors in Dockershim don't stop Kube Proxy from building

### ISSUE THREAD

**Issue by ksubrmnn** [kubernetes/kubernetes#90991]
**What happened**:
When making changes to dockersshim, a syntax error occured that did not prevent Kube Proxy from being built locally. It did however result in some failing tests.

**What you expected to happen**:
Kube proxy would not compile with errors in dockersshim
**How to reproduce it (as minimally and precisely as possible)**:
In pkg/kubelet/dockershim/network/cni/cni_windows.go, there was a PR with the following code 

```
var  list = []net.IP {result020.IP4.IP.IP};
```

This did not result in any errors when building Windows Kube Proxy with the following command:

`KUBE_BUILD_PLATFORMS=windows/amd64 make WHAT=cmd/kube-proxy`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Developing for 1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Building Windows components on Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ksubrmnn** [comment]
@kumarvin123 hopefully this captures what you saw

**Comment by ksubrmnn** [comment]
@mrbobbytables Is this considered contributor experience? Do you know if there's a SIG that focuses on building, etc or is this handled on a SIG by SIG basis?

**Comment by liggitt** [comment]
dockershim is not used by kube-proxy, is it?

**Comment by liggitt** [comment]
Dockershim is used by the kubelet, not by kube-proxy, so a syntax error in it would not prevent kube-proxy from building, it would prevent the kubelet binary from building.
