### ISSUE TITLE
Mirror pod deletion should respect grace period

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#90999]
**What happened**:
Currently when the mirror pod is deleted, it is deleted without grace period.

When static pod yaml was removed from the manifests directory, @sjenning observed
```
Jul 29 20:54:44 master-2 hyperkube[1526]: I0729 20:54:44.122924    1526 kubelet.go:1904] SyncLoop (REMOVE, "file"): "kube-apiserver-master-2_openshift-kube-apiserver(60d66dd8b81c2a4756d2e2f69ec1e3fc)"
Jul 29 20:54:44 master-2 hyperkube[1526]: I0729 20:54:44.401404    1526 mirror_client.go:93] Deleting a mirror pod "kube-apiserver-master-2_openshift-kube-apiserver" (uid (*types.UID)(nil))
Jul 29 20:54:44 master-2 hyperkube[1526]: I0729 20:54:44.435138    1526 kubelet_pods.go:1695] Orphaned pod "60d66dd8b81c2a4756d2e2f69ec1e3fc" found, but volumes not yet removed.  Reducing cpu to minimum
Jul 29 20:54:44 master-2 hyperkube[1526]: I0729 20:54:44.435544    1526 kubelet.go:1910] SyncLoop (DELETE, "api"): "kube-apiserver-master-2_openshift-kube-apiserver(08b81ce8-b243-11e9-a38f-fa163e8871d1)"
Jul 29 20:54:44 master-2 hyperkube[1526]: I0729 20:54:44.441528    1526 kubelet.go:1904] SyncLoop (REMOVE, "api"): "kube-apiserver-master-2_openshift-kube-apiserver(08b81ce8-b243-11e9-a38f-fa163e8871d1)"
```

The cause has two aspects:
* DeleteOrphanedMirrorPods doesn't consider grace period from pod spec
* cleanupOrphanedPodCgroups prematurely cleans up the underlying cgroup

**What you expected to happen**:
The desired behavior is that the kubelet honors the pod.spec.terminationGracePeriodSeconds in the yaml file when turning down the container, and only deletes the pod from the APIServer after the container is down.

This would allow the logs to be accessible via the apiserver during pod termination.

**How to reproduce it (as minimally and precisely as possible)**:
* remove static pod of kube-apiserver from /etc/kubernetes/manifests
* monitor the mirror pod in the API and how it goes away immediately
* monitor `crictl ps` and how the container disappears immediately.

Please see the 'Test Strategy' subsection of the description of #91453 for the failure case of e2e test where grace period is not respected.

Without the fix, the new e2e test would fail with the following assertion:
```
[k8s.io] MirrorPodWithGracePeriod when create a mirror pod mirror pod termination should satisfy grace period when static pod is deleted [NodeConformance] expand_less  4s
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_grace_test.go:54
Unexpected error:
    <*errors.StatusError | 0xc0003b35e0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"static-pod-9ba82792-0187-43a7-be3d-ffb5db011631-tmp-node-e2e-59ba742a-cos-stable-81-12871-103-0\" not found",
            Reason: "NotFound",
            Details: {
                Name: "static-pod-9ba82792-0187-43a7-be3d-ffb5db011631-tmp-node-e2e-59ba742a-cos-stable-81-12871-103-0",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    pods "static-pod-9ba82792-0187-43a7-be3d-ffb5db011631-tmp-node-e2e-59ba742a-cos-stable-81-12871-103-0" not found
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_grace_test.go:72
```
Here is the assertion which expects to be able to retrieve the mirror pod within grace period:
```
				pod, err := f.ClientSet.CoreV1().Pods(ns).Get(context.TODO(), mirrorPodName, metav1.GetOptions{})
				framework.ExpectNoError(err)
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Thanks to @sttts and @sjenning for investigation into this matter.

**Comment by tedyu** [comment]
In basicMirrorClient#DeleteMirrorPod, there is place holder for grace period:
```
	var GracePeriodSeconds int64
	if err := mc.apiserverClient.CoreV1().Pods(namespace).Delete(context.TODO(), name, metav1.DeleteOptions{GracePeriodSeconds: &GracePeriodSeconds, Preconditions: &metav1.Preconditions{UID: uid}}); err != nil {
```
One option is to give non-zero period, such as 60 seconds.

**Comment by tedyu** [comment]
@liggitt 
What do you think ?

**Comment by liggitt** [comment]
without digging too deeply, if we set a grace period, I'd expect it to match the pod.spec.terminationGracePeriodSeconds on the pod

I don't know whether the path the kubelet uses to deal with static pod deletion honors options set in the pod coming from the API server (for static pods, the file on disk is supposed to be authoritative).

If we start adding an API deletion grace period, what happens if a static pod manifest is removed (triggering a delete-with-grace-period) then readded (triggering a create attempt which fails because the old pod API object still exists with a deletion timestamp)?

**Comment by tedyu** [comment]
For orphaned mirror pod, we have the following code in basicManager#getOrphanedMirrorPodNames :
```
		if _, ok := pm.podByFullName[podFullName]; !ok {
			podFullNames = append(podFullNames, podFullName)
```
At this point, there is no reference to the Pod.

I will think about implication for readding pod manifest.

**Comment by tedyu** [comment]
[mirror-pod-del-grace.txt](https://github.com/kubernetes/kubernetes/files/4658923/mirror-pod-del-grace.txt)

**Comment by tallclair** [comment]
I'm a bit confused by this. The issue as described sounds like you want to move the trigger for the mirrorpod api deletion from the pod manifest being removed to the pod actually terminating. What does the grace period have to do with it?

**Comment by tedyu** [comment]
From my observation, pod manifest being removed from /etc/kubernetes/manifests and the destroy of containers (indicated by 'crictl ps') are very close.

So the grace period (30s) should be applied for destroying container and for removal from apiserver.
```
May 20 22:23:49 ip-10-0-131-183 hyperkube[865359]: I0520 22:23:49.509925  865359 manager.go:1007] Destroyed container: "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod29fc1ab0aad2dd8ecb94453749da5814.slice/crio-aea8c223fd4103a333c40355612c4f1058384bbf9e9af902cb11078074d96b0b.scope"
```

**Comment by tedyu** [comment]
Reading Kubelet#syncLoopIteration, it seems kubetypes.REMOVE is not concerned with graceful deletion while kubetypes.DELETE is.

I noted the following from kubelet.log
```
May 21 02:04:51 tmp-node-e2e-a167bc70-cos-stable-81-12871-103-0 kubelet[1917]: I0521 02:04:51.057192    1917 kubelet.go:1855] SyncLoop (DELETE mirror, "api"): "static-pod-5a513605-b539-4642-bdfc-081128f2f7b5-tmp-node-e2e-a167bc70-cos-stable-81-12871-103-0_mirror-pod-828(62288531-4764-4dc6-9db6-4a891adec1fb)"

May 21 02:04:51 tmp-node-e2e-a167bc70-cos-stable-81-12871-103-0 kubelet[1917]: I0521 02:04:51.059531    1917 kubelet.go:1845] SyncLoop (REMOVE mirror, "api"): "static-pod-5a513605-b539-4642-bdfc-081128f2f7b5-tmp-node-e2e-a167bc70-cos-stable-81-12871-103-0_mirror-pod-828(62288531-4764-4dc6-9db6-4a891adec1fb)"
```

**Comment by tedyu** [comment]
/cc @caesarxuchao 
since you worked on related code.

**Comment by caesarxuchao** [comment]
Just to clarify, in #1, you said "monitor crictl ps and how the container disappears immediately" and "the static pod is gracefully terminated on the node", which one is true?

**Comment by tedyu** [comment]
I modified the description to make it clear.

via the output of 'crictl ps', currently the container disappears immediately

**Comment by caesarxuchao** [comment]
I think I missed something, what do you mean by "the static pod is gracefully terminated on the node" if "the container disappears immediately"?

**Comment by tedyu** [comment]
I dropped that sentence since it is redundant with the first sentence of 'What you expected to happen'.
Currently given:
```
c9a5476b643d1       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         About a minute ago   Running             kube-scheduler-cert-syncer                    0                   86d093ce96d51
95b07e71a9a61       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         About a minute ago   Running             kube-scheduler                                0                   86d093ce96d51
```
Once 'mv /etc/kubernetes/manifests/kube-scheduler-pod.yaml /tmp/' is executed, the two containers would be destroyed immediately.

The desired behavior is for the containers to have 30s grace period.

**Comment by caesarxuchao** [comment]
Thanks for the clarification. So currently the container is deleted immediately, and the pod is removed from the APIServer immediately as well. The desired behavior is that the kubelet honors the `pod.spec.terminationGracePeriodSeconds` in the yaml file when turning down the container, and only deletes the pod from the APIServer after the container is down.

**Comment by tedyu** [comment]
[mirror-pod-del-grace-killing.txt](https://github.com/kubernetes/kubernetes/files/4665020/mirror-pod-del-grace-killing.txt)

Here is tentative patch
I verified on patched 1.18 master node :
```
[root@ip-10-0-150-184 kube-scheduler]# crictl ps | grep sched
c9a5476b643d1       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         About a minute ago   Running             kube-scheduler-cert-syncer                    0                   86d093ce96d51
95b07e71a9a61       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         About a minute ago   Running             kube-scheduler                                0                   86d093ce96d51
[root@ip-10-0-150-184 kube-scheduler]# date
Thu May 21 20:54:53 UTC 2020
[root@ip-10-0-150-184 kube-scheduler]# mv /etc/kubernetes/manifests/kube-scheduler-pod.yaml /tmp/
[root@ip-10-0-150-184 kube-scheduler]# crictl ps | grep sched
c9a5476b643d1       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         About a minute ago   Running             kube-scheduler-cert-syncer                    0                   86d093ce96d51
95b07e71a9a61       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         About a minute ago   Running             kube-scheduler                                0                   86d093ce96d51
[root@ip-10-0-150-184 kube-scheduler]# crictl ps | grep sched
c9a5476b643d1       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         About a minute ago   Running             kube-scheduler-cert-syncer                    0                   86d093ce96d51
95b07e71a9a61       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         About a minute ago   Running             kube-scheduler                                0                   86d093ce96d51
[root@ip-10-0-150-184 kube-scheduler]# crictl ps | grep sched
c9a5476b643d1       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         2 minutes ago       Running             kube-scheduler-cert-syncer                    0                   86d093ce96d51
95b07e71a9a61       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         2 minutes ago       Running             kube-scheduler                                0                   86d093ce96d51
```

**Comment by tedyu** [comment]
@timstclair @caesarxuchao 
Please take a look at the patch in above comment.

**Comment by tedyu** [comment]
Currently static pod deletion doesn't respect grace period.
What we ultimately need is cancellable grace period where if, the static pod is recreated shortly after pod deletion, the remaining grace period should be cancelled.

It seems putting call to apiserver for pod deletion and the call to Kubelet#killPod() in the same place would make implementation of cancellable grace period more intuitive.

**Comment by tedyu** [comment]
I tested updated patch on 1.18 master node.
Please note the containers were not immediately destroyed after kube-scheduler-pod.yaml was moved.
When kube-scheduler-pod.yaml was moved back, the containers were immediately destroyed and new containers created:
```
[root@ip-10-0-131-125 manifests]# mv kube-scheduler-pod.yaml /tmp/
[root@ip-10-0-131-125 manifests]# crictl ps | grep sched
74a34862981f2       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         8 minutes ago       Running             kube-scheduler                                1                   59c2527151e75
c7e3d30aeb1be       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         17 minutes ago      Running             kube-scheduler-cert-syncer                    0                   59c2527151e75
[root@ip-10-0-131-125 manifests]# crictl ps | grep sched
74a34862981f2       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         8 minutes ago        Running             kube-scheduler                                1                   59c2527151e75
c7e3d30aeb1be       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         17 minutes ago       Running             kube-scheduler-cert-syncer                    0                   59c2527151e75
[root@ip-10-0-131-125 manifests]# cp /tmp/kube-scheduler-pod.yaml .
[root@ip-10-0-131-125 manifests]# crictl ps | grep sched
[root@ip-10-0-131-125 manifests]# crictl ps | grep sched
5da0aa80f590a       a5092311477007882b8468716d31638fc0d8d47ab358d0029846f7d2b1a15461                                                         1 second ago         Running             kube-scheduler-cert-syncer                    1                   8dcdf8c9412d2
e5fdbeb5d6d9f       5aed8ada242173389ab0c94132b9b49a4f68a8a278723a691349f2e728a4936a                                                         2 seconds ago        Running             kube-scheduler                                2                   8dcdf8c9412d2
```
Here was snippet from kubelet.log - note that the actual wait was 16.8 seconds (< 30 second grace period):
```
May 22 19:09:33 ip-10-0-131-125 hyperkube[71416]: I0522 19:09:33.838701   71416 kubelet_pods.go:1130] pod openshift-kube-scheduler-ip-10-0-131-125.ec2.internal_openshift-kube-scheduler is being added, skip waiting
May 22 19:09:33 ip-10-0-131-125 hyperkube[71416]: I0522 19:09:33.838736   71416 kubelet_pods.go:1136] killing pod openshift-kube-scheduler-ip-10-0-131-125.ec2.internal after having waited 16.826519469 seconds
May 22 19:09:33 ip-10-0-131-125 hyperkube[71416]: I0522 19:09:33.838761   71416 kubelet_pods.go:1139] deleting mirror pod openshift-kube-scheduler-ip-10-0-131-125.ec2.internal
May 22 19:09:33 ip-10-0-131-125 hyperkube[71416]: I0522 19:09:33.838777   71416 mirror_client.go:125] Deleting a mirror pod "openshift-kube-scheduler-ip-10-0-131-125.ec2.internal_openshift-kube-scheduler" (uid (*types.UID)(nil)) with grace 0
```

**Comment by tedyu** [comment]
[mirror-pod-del-grace-cancel-2.txt](https://github.com/kubernetes/kubernetes/files/4669979/mirror-pod-del-grace-cancel-2.txt)

**Comment by tedyu** [comment]
[cri-ctl-test.txt](https://github.com/kubernetes/kubernetes/files/4674705/cri-ctl-test.txt)

Attempted to write e2e test.
However, there was no host where the scheduler container could be found:
```
I0524 23:44:11.462] ^[[1mSTEP^[[0m: SSH'ing to node "34.83.82.247:22" to run "sudo crictl ps | grep schedul"
I0524 23:44:11.462] May 24 23:44:05.374: INFO: For host "34.83.82.247:22":  . and stderr:
I0524 23:44:11.462] May 24 23:44:05.375: FAIL: Didn't find any host for scheduler
```

**Comment by tedyu** [comment]
If I understand the investigation by @sttts and @sjenning correctly , we have the following considerations:

1. it would be desirable to have container logs from the time static pod begins to shut down till the removal of the containers.
2. it is hard to determine how long a container would take to react to SIGTERM after the container receives the signal. For a container which has been running for quite a while, it would take more time to gracefully shutdown (compared to a container which just starts up).

If we choose to modify DeleteOrphanedMirrorPods() for verifying that container resources are reclaimed on the node before calling DeleteMirrorPod(), the following from description would still behave as today:
```
monitor crictl ps and how the container disappears immediately.
```
I am afraid that this is not desirable - if I read the initial report (https://bugzilla.redhat.com/show_bug.cgi?id=1700279) correctly

Side note for judging whether container resource has been reclaimed:

First plan is to resort to the following Runtime API for checking container status:
```
GetPodStatus(uid types.UID, name, namespace string) (*PodStatus, error)
```
Note that for some reason, error may be returned. Then we would face the question of whether the container status can be reliably retrieved.

**Comment by sttts** [comment]
> For a container which has been running for quite a while, it would take more time to gracefully shutdown (compared to a container which just starts up).

Why does this matter? We have a graceful termination time specified in the pod spec. That's the upper bound. It can take that long.

**Comment by derekwaynecarr** [comment]
@tedyu  per discussion on your proposed PR, we should increase node e2e test coverage around static pods, and then ideally reproduce the reported issue in that test coverage so that we can ensure node resources are reclaimed.

**Comment by tedyu** [comment]
New test has been added.
Without fix, it fails:
https://github.com/kubernetes/kubernetes/pull/91453#issuecomment-636267692
