### ISSUE TITLE
can I use dlv with k8s in linux unit file

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#91017]
···
[Service]
ExecStart=/root/kubernetes_go/bin/dlv --listen=192.168.198.154:39999 --headless=true --api-version=2 exec  /opt/kube/bin/kube-apiserver \
  --advertise-address=192.168.198.154 \
  --allow-privileged=true \
  --anonymous-auth=false \
  --authorization-mode=Node,RBAC \
  --bind-address=192.168.198.154 \
  --client-ca-file=/etc/kubernetes/ssl/ca.pem \
  --endpoint-reconciler-type=lease \
  --etcd-cafile=/etc/kubernetes/ssl/ca.pem \
  --etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem \
  --etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem \
  --etcd-servers=https://192.168.198.154:2379,https://192.168.198.155:2379,https://192.168.198.156:2379 \
  --insecure-bind-address=127.0.0.1 \
  --kubelet-https=true \
  --kubelet-client-certificate=/etc/kubernetes/ssl/admin.pem \
  --kubelet-client-key=/etc/kubernetes/ssl/admin-key.pem \
  --service-account-key-file=/etc/kubernetes/ssl/ca-key.pem \
  --service-cluster-ip-range=10.68.0.0/16 \
  --service-node-port-range=20000-40000 \
  --tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
  --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem \
  --requestheader-allowed-names= \
  --requestheader-extra-headers-prefix=X-Remote-Extra- \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --proxy-client-cert-file=/etc/kubernetes/ssl/aggregator-proxy.pem \
  --proxy-client-key-file=/etc/kubernetes/ssl/aggregator-proxy-key.pem \
  --enable-aggregator-routing=true \
···

···
[root@master01 ~]# systemctl status kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) since Tue 2020-05-12 18:14:08 CST; 60ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 23608 ExecStart=/root/kubernetes_go/bin/dlv --listen=192.168.198.154:39999 --headless=true --api-version=2 exec /opt/kube/bin/kube-apiserver --advertise-address=192.168.198.154 --allow-privileged=true --anonymous-auth=false --authorization-mode=Node,RBAC --bind-address=192.168.198.154 --client-ca-file=/etc/kubernetes/ssl/ca.pem --endpoint-reconciler-type=lease --etcd-cafile=/etc/kubernetes/ssl/ca.pem --etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem --etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem --etcd-servers=https://192.168.198.154:2379,https://192.168.198.155:2379,https://192.168.198.156:2379 --insecure-bind-address=127.0.0.1 --kubelet-https=true --kubelet-client-certificate=/etc/kubernetes/ssl/admin.pem --kubelet-client-key=/etc/kubernetes/ssl/admin-key.pem --service-account-key-file=/etc/kubernetes/ssl/ca-key.pem --service-cluster-ip-range=10.68.0.0/16 --service-node-port-range=20000-40000 --tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem --tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem --requestheader-allowed-names= --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --proxy-client-cert-file=/etc/kubernetes/ssl/aggregator-proxy.pem --proxy-client-key-file=/etc/kubernetes/ssl/aggregator-proxy-key.pem --enable-aggregator-routing=true --v=2 (code=exited, status=0/SUCCESS)
 Main PID: 23608 (code=exited, status=0/SUCCESS)

May 12 18:14:08 master01 dlv[23608]: --check-go-version     Checks that the version of Go in use is compatible with Delve. (...t true)
May 12 18:14:08 master01 dlv[23608]: --headless             Run debug server only, in headless mode.
May 12 18:14:08 master01 dlv[23608]: --init string          Init file, executed by the terminal client.
May 12 18:14:08 master01 dlv[23608]: -l, --listen string        Debugging server listen address. (default "127.0.0.1:0")
May 12 18:14:08 master01 dlv[23608]: --log                  Enable debugging server logging.
May 12 18:14:08 master01 dlv[23608]: --log-dest string      Writes logs to the specified file or file descriptor (see 'dlv help log').
May 12 18:14:08 master01 dlv[23608]: --log-output string    Comma separated list of components that should produce debug out...p log')
May 12 18:14:08 master01 dlv[23608]: --only-same-user       Only connections from the same user that started this instance o...t true)
May 12 18:14:08 master01 dlv[23608]: --wd string            Working directory for running the program. (default ".")
May 12 18:14:08 master01 systemd[1]: Started Kubernetes API Server.
···
kubeapi server can not start

**Comment by jtslear** [comment]
Finding a home:

/sig @kubernetes/sig-api-machinery-misc 

If this is incorrect, please assist in re-assessing and reassigning.

**Comment by jtslear** [comment]
Sorry for the wide ping, I used the assignment command incorrectly, this was not intentional.

**Comment by lavalamp** [comment]
I don't think we can help you debug delve or systemd here, sorry! It looks like it is printing help text which makes me think something is wrong with the arguments it's seeing. I'd make sure it runs as expected without being in the systemd unit. And then I'd check whether the args need to be quoted or something. Hopefully one of those actions should at least provide a clue, but I don't know.

Good luck!
