### ISSUE TITLE
Split scheduler framework implementation into a separate pkg

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#91029]
Split the scheduler framework into an interface pkg and an implementation pkg. 

We can keep the interface files (interface.go, types.go, listers.go and cyclestate.go) under ```scheduler/framework/v1alpha1``` and move the implementation to ```scheduler/framework/runtime```. 

Ideally plugins should only depend on the interface pkg. 

/cc @Huang-Wei @alculquicondor 
/sig scheduling

**Comment by Huang-Wei** [comment]
And we can use this chance to remove the "v1alpha1" literal from `scheduler/framework/v1alpha1` as there is only one version of framework interface.

**Comment by alculquicondor** [comment]
+1

**Comment by farah** [comment]
Hi @ahg-g, 

I was hoping that maybe I can pick this up as I'm looking for my first PR :)

I'll get started on this anyway anyway will and attempt to break the package up . Will report in a few days. 

Any tips are most welcome :) @Huang-Wei  @alculquicondor

**Comment by farah** [comment]
Hi @ahg-g,

I was hoping that maybe I can pick this up as I'm looking for my first PR :)

I'll get started on this anyway will and attempt to break the package up . Will report in a few days.

Any tips are most welcome :) @Huang-Wei @alculquicondor

**Comment by ahg-g** [comment]
Thanks @farah, feel free to send a PR my way. For now, let's just move the implementation to `scheduler/framework/runtime`

/assign @farah

**Comment by ahg-g** [comment]
I suggest we move the interface out of `pkg/scheduler/framework/v1alpha1` to `pkg/scheduler/framework` or `pkg/scheduler/framework/interface` and close the enhancement issue https://github.com/kubernetes/enhancements/issues/624

@Huang-Wei @alculquicondor what do you think?

**Comment by alculquicondor** [comment]
I vote for `pkg/scheduler/framework`

**Comment by Huang-Wei** [comment]
`pkg/scheduler/framework` looks good.

**Comment by ahg-g** [comment]
do you also agree that we should just graduate kubernetes/enhancements#624 and considered implemented?

**Comment by Huang-Wei** [comment]
> do you also agree that we should just graduate [kubernetes/enhancements#624](https://github.com/kubernetes/enhancements/issues/624) and consider it implemented?

Agree. As (1) we're not maintaining a multi-versioned scheduler framework, (2) the in-tree scheduler has totally migrated to plugin-based execution path since 1.18, and (3) scheduler-plugins has provided a number of data points proving the maturity and the scheduler framework design.

**Comment by farah** [comment]
There's 11 files remaining to finish this off (mostly in the kubelet directory)

```
kubernetes$ find ./ -type f -name '*.go' | xargs grep 'framework/v1alpha1'
./pkg/kubelet/kubelet_test.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/container_manager_windows.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/container_manager_stub.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/container_manager.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/devicemanager/manager_test.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/devicemanager/manager_stub.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/devicemanager/manager.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/devicemanager/types.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/cm/container_manager_linux.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/lifecycle/predicate_test.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"
./pkg/kubelet/lifecycle/predicate.go:	schedulerframework "k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1"

```

I'll change those after the #95069 is merged, and delete the v1alpha1/ folder in the same pr.
