### ISSUE TITLE
Dashboard logs forcibly open in new tab

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#91027]
The Web browsing user has no control over whether log hyperlink opens in the current tab vs. a new tab.

**Comment by mcandre** [comment]
Same issue with exec.

**Comment by liggitt** [comment]
thanks for the report... this probably belong under https://github.com/kubernetes/dashboard

**Comment by neolit123** [comment]
> this probably belong under https://github.com/kubernetes/dashboard

+1
please log the issue in k/dashboard.

/sig ui
/close
