### ISSUE TITLE
Awkward navigation from logs <-> exec

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#91028]
**What would you like to be added**:

Please offer more links for quickly jumping back and forth between logs for a pod, and exec to a pod.

**Why is this needed**:

The user currently has to find the pod all over again in the main pod list. It really slows you down when troubleshooting.

Also, extra page loads in between logs and exec is wasteful at layer 3.

**Comment by neolit123** [comment]
again please log dashboard issues in k/dashboard and provide details about the version.
thanks.

/sig ui
/close
