### ISSUE TITLE
Bump spf13/cobra dependency to 1.0.0 version

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#91021]
Cobra 1.0.0 release was released a month ago:
https://github.com/spf13/cobra/releases/tag/v1.0.0

We should bump our vendor to use that (instead of 0.5 version we currently use).

As a bonus - in 0.6 version, support for "Context" was added, which would help me with cleaning up UnitWithoutRetry - see https://github.com/kubernetes/kubernetes/pull/90815

/help wanted
/kind cleanup

**Comment by wojtek-t** [comment]
@gongguan - in case you're interested in helping with this one too

**Comment by gongguan** [comment]
Sure, I'll look into it.
/assign
