### ISSUE TITLE
Add debug for kubeadm

### ISSUE THREAD

**Issue by Seb0042** [kubernetes/kubernetes#91022]
**What would you like to be added**:
More debug information for kubeadm when doing "kubeadm upgrade plan" and get this message:
invalid configuration: kind and apiVersion is mandatory information that needs to be specified

**Why is this needed**:
because even in --v=5 or higher the cause is difficult to find.
I suggest changing code from:
 
       if err != nil {
                        return err
                }
to:

      if err != nil {
                        klog.Warningf("WARNING: config group misses something: %v", handler.GroupVersion.Group)
                        return err
                }

        
file: cmd/kubeadm/app/componentconfigs/configset.go
function: FetchFromCluster

At least we will have the information off which one of the config having troubles.

**Comment by neolit123** [comment]
/close
/remove-sig apps
/sig cluster-lifecycle
/area kubeadm


hi, please open this ticket in the kubernetes/kubeadm repository.
thank you.
