### ISSUE TITLE
create svc externalname --tcp has no effect

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#91043]
**What happened**:
···
[root@master01 f]# kubectl create svc externalname test12 --external-name=www.baidu.com2 --tcp=8800:80 -n test -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-13T05:50:25Z"
  labels:
    app: test12
  name: test12
  namespace: test
  resourceVersion: "1608488"
  selfLink: /api/v1/namespaces/test/services/test12
  uid: a116509b-31e1-4bfe-b6e9-624496aaa704
spec:
  externalName: www.baidu.com2
  selector:
    app: test12
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
···

···
generator = &generateversioned.ServiceCommonGeneratorV1{
			Name:         name,
			Type:         v1.ServiceTypeExternalName,
			ExternalName: cmdutil.GetFlagString(cmd, "external-name"),
			ClusterIP:    "",
		}
···
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
···
[root@master01 f]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
···
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by johscheuer** [comment]
I took a look and the `--tcp` argument is never used which makes sense since a service of the type `ExternalName` will create a `CNAME` and the `CNAME` won't return any information about the port.

The funny part is that you can create an service with type `ExternalName` and a port specification (this should probably documented):

```bash
$ cat test.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test1
  name: test1
spec:
  externalName: www.baidu.com2
  ports:
  - port: 80
    targetPort: 8080
  type: ExternalName
```

results in:

```bash
kubectl get svc -o wide
NAME         TYPE           CLUSTER-IP   EXTERNAL-IP      PORT(S)   AGE   SELECTOR
test1        ExternalName   <none>       www.baidu.com2   80/TCP    4s    <none>
```

What Use-case did you want to solve with the port and the service of `ExternalName`?

**Comment by 13567436138** [comment]
If externalName doesn't need ports，you should delete the tcp options

**Comment by johscheuer** [comment]
I already opened a PR (see above).
