### ISSUE TITLE
Add test coverage for SelfSubjectRulesReview and node authorizer

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#91042]
An integration test should be added to confirm that the node authorizer interacts correctly with the `SelfSubjectRulesReview` API.

Test the 4 permutations of node authorizer=on/off with identity isNode=true/false.

xref: #90975 #91030

**Comment by ZhiFeng1993** [comment]
@enj Just to confirm, is the integration test for `SubjectRulesReview` supposed to be similar with https://github.com/kubernetes/kubernetes/blob/master/test/integration/auth/accessreview_test.go?(test for `SubjectAccessReview`)

I had some trouble finding out how to construct an authorizer with `isNode` toggled. Not sure where `RulesFor` gets called.

**Comment by ZhiFeng1993** [comment]
@alam0rt  I'm working on this one. Mind working on another one? Thanks

**Comment by alam0rt** [comment]
sure!
