### ISSUE TITLE
kubetest  --ginkgo.focus=Service timed out waiting for the condition

### ISSUE THREAD

**Issue by chenpfeisoo** [kubernetes/kubernetes#91047]
**What happened**:

When I execute the command to run the service case, the console always prints the timeout, and the pod is not running

`network-perf-1259   iperf-e2e-pod-0                       0/1     Completed   0          3h41m
 network-perf-1259   iperf-e2e-pod-1                       0/1     Completed   0          3h41m`
`May 13 16:14:36.533: FAIL: Unexpected error:
    <*errors.errorString | 0xc000099090>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition`
`kubetest --provider=skeleton --test --test_args="--host=**** --ginkgo.focus=Service" --check-version-skew=false --dump result`

**What you expected to happen**:
     1.pod running   or  End of current case

    
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
    1.16.3
    go ： 1.12.7

**Comment by chenpfeisoo** [comment]
pod status

**Comment by chenpfeisoo** [comment]
pod  status

`network-perf-1259   iperf-e2e-pod-0                       0/1     Completed   0          3h41m
network-perf-1259   iperf-e2e-pod-1                       0/1     Completed   0          3h41m`

Shouldn't pod running  or recreate   when there is a case? Although it's a job

**Comment by gianarb** [comment]
/sig testing

sig-release is in the effort of assigning issues to sigs when missed if you feel this issue does not belong to you because of assign to somebody else.
