### ISSUE TITLE
Some docs do not reflect the changes to kubectl run command since 1.18

### ISSUE THREAD

**Issue by puja108** [kubernetes/kubernetes#91064]
**What happened**:

Since Kubernetes 1.18 the `kubectl run` command is not creating deployments anymore, but pods. Furthermore, some flags (e.g. [--replicas](https://github.com/kubernetes/kubernetes/issues/89651)) have also been deprecated.

I stumbled upon a few places where the docs do not reflect that:
- https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#setup uses deprecated flag and expect a deployment to be created to follow the walkthrough
- https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/#docker-run mentions and expects a deployment to be created
- https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run still mentions deprecated flags

I did not run a full search through the docs, so there might be other places.

**What you expected to happen**:

In most cases, the expected behavior should be possible to achieve with the `kubectl create deployment` command. However, as [mentioned by others](https://github.com/kubernetes/kubernetes/issues/89651#issuecomment-627245763) it might not offer all the flags that are needed. Not sure if the flag limitation affects the usage in the docs mentioned above.

**How to reproduce it (as minimally and precisely as possible)**:

Try to run the commands from the docs.

**Anything else we need to know?**:

As the change is on the client-side users with newer kubectl but older Kubernetes version might also be affected.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18+

**Comment by Cweiping** [comment]
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run , maybe need sig/cli（i guess） regenerated to update. And [kubectl run](https://github.com/kubernetes/kubernetes/issues/89651) become created pod， those who use it need to be checked

**Comment by ryan-chase** [comment]
In addition to any deprecated flags mentioned in https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run, there is incorrect information provided for the `--restart` flag.  The page says: 
The restart policy for this Pod. Legal values [Always, OnFailure, Never]. If set to 'Always' a deployment is created, if set to 'OnFailure' a job is created, if set to 'Never', a regular pod is created. For the latter two --replicas must be 1. Default 'Always', for CronJobs Never. 

...however, running each of the following commands returns `kind: Pod` :
- `kubectl run nginx --image=nginx --**restart=Never** --dry-run=client - o yaml | grep kind`
- `kubectl run nginx --image=nginx --**restart=Always** --dry-run=client - o yaml | grep kind`
- `kubectl run nginx --image=nginx --**restart=OnFailure** --dry-run=client - o yaml | grep kind`
