### ISSUE TITLE
Creating External Loadbalancer should present some "progress status"

### ISSUE THREAD

**Issue by jdk-google** [kubernetes/kubernetes#9106]
Creating an external loadbalancer takes minutes.

At the same time, the user doesn't know waht is happening, and whether it failed, is in progress, or just the user made a typo in the "externalLoadBalancer" 

What we could do for example is:
in the "kubectl get services", if there is external Load Balancer configured, in the place of "external IP" show "status of the load balancer creation".

**Comment by bgrant0607** [comment]
See also #8992

cc @thockin @justinsb @a-robinson

**Comment by cmluciano** [comment]
Possible dupe of https://github.com/kubernetes/kubernetes/issues/52670

**Comment by sftim** [comment]
See https://github.com/kubernetes/kubernetes/issues/70159#issuecomment-773457794 

We'd ideally have someone willing to start of a KEP for the Networking SIG.

**Comment by thockin** [comment]
I think events are the API for progress-reports (we do report some already).  It could probably be more but it's worth noting that there is a difference between "cloud LB created" and "cloud LB is accepting traffic".  The former is sync, the latter is usually async.

I think this is a cloud-provider implementation detail feature-request, which should be handled in the out-of-tree cloud-providers as a convention, not requirement.
