### ISSUE TITLE
Service account key rotation is not well documented

### ISSUE THREAD

**Issue by Matty9191** [kubernetes/kubernetes#91070]
**What happened**:

After rotating the SA public and private keys, the API server is unable to validate tokens minted off the old private key.

**What you expected to happen**:

Based on the documentation and the notes in [34029](https://github.com/kubernetes/kubernetes/pull/34029) and [20165](https://github.com/kubernetes/kubernetes/issues/20165), I would have expected the API server to accept the token that was created by the previous private key.

**Environment**:

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

$ kind version
kind v0.8.1 go1.14.2 linux/amd64

$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux kube 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce**

I was experimenting with certificate and service account key rotation. To test the SA key rotation process, I fired up a Kind cluster with the following configuration:

$ kind create cluster --name test --config kind

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
```
Once the cluster was up, I copied the existing SA public key to saold.pub:

$ docker exec -it test-control-plane sh
$ cd /etc/kubernetes/pki
$ cp sa.pub saold.pub
$ mkdir bak && mv sa.* bak

And minted new sa keys with kubeadm:

$ kubeadm init phase certs sa

Then I added "- --service-account-key-file=/etc/kubernetes/pki/saold.pub" to /etc/kubernetes/manifests/kube-apiserver.yaml. Next I restarted the API server and controller manager to pick up the changes:

```
root      3617 31.0  3.8 446240 310908 ?       Ssl  01:37   0:09 kube-apiserver --advertise-address=172.18.0.4 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-account-key-file=/etc/kubernetes/pki/saold.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key

root      3499  6.2  0.4 159676 34784 ?        Ssl  01:37   0:02 kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=10.244.0.0/16 --cluster-name=test --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --enable-hostpath-provisioner=true --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --node-cidr-mask-size=24 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.96.0.0/12 --use-service-account-credentials=true
```

Now that the API server was configured to use the old as well as the new public keys, I deleted the coredns SA token to see if everything continued to work:

$ kubectl delete secret coredns-token-lpx72 -n kube-system
secret "coredns-token-lpx72" deleted

After a few queries were issued, I was a bit confused when I saw the following log entries:

```
CoreDNS logs:
  coredns-66bff467f8-plr9h coredns E0509 01:46:30.772785       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Endpoints: Unauthorized

API server logs:
  kube-apiserver-test-control-plane kube-apiserver E0509 01:48:34.113219       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
```
Next I deleted the coredns pods, and the Unauthorized messages went away. Based on @liggitt's comment in issue [22351](https://github.com/kubernetes/kubernetes/issues/22351):

_"if you have changed the service account token signing key, existing tokens in etcd will no longer validate"_

This would explain the Unauthorized messages. But issue [34029](https://github.com/kubernetes/kubernetes/pull/34029) appears to add support for multiple keys, and @ericchiang's comment in [20165](https://github.com/kubernetes/kubernetes/issues/20165) leads me to believe things should continue working when the private key is rotated:

_"API servers can already be given multiple public keys to validate service account JWTs (#34029). This lets you introduce a new key pair over time for validation before changing it in the controller manager as the active signing key."_

I have looked everywhere for an answer to this, but my searching hasn't turned up much. Could someone clarify what *should* happen if the SA keys are rotated, a token is signed with the new key, and the API server is configured to use the old and new public keys? I'll be glad to submit a documentation PR to clarify this for others.

**Comment by liggitt** [comment]
> Now that the API server was configured to use the old as well as the new public keys, I deleted the coredns SA token to see if everything continued to work

That is why you are getting unauthorized errors. To be valid, a secret-based service account token must 1) have a valid signature and 2) still exist in a backing secret. Specifying both public keys took care of 1, but when you deleted the secret, you revoked the old token.

**Comment by liggitt** [comment]
To trigger creation of new token secrets while leaving the old ones valid, reset the 'secrets' field of the serviceaccount. A rough sketch of what this could look like is:

```
# 1. record the starting date/time
start=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo $start
sleep 1

# 2. gather all existing service accounts
kubectl get sa --all-namespaces -o=jsonpath='{range .items[*]}--namespace={.metadata.namespace} serviceaccount/{.metadata.name}{"\n"}{end}' > accounts.txt

# 3. clear recorded secrets to trigger new token secret generation
cat accounts.txt | xargs -L 1 kubectl patch --type=merge -p '{"secrets":[]}'

# 4. wait for all uses of old secrets to stop
...

# 5. find service account token secrets created before start
kubectl get secrets --field-selector=type=kubernetes.io/service-account-token --all-namespaces -o json |
jq -r ".items[] | select(.metadata.creationTimestamp <= \"${start}\") | \"--namespace=\(.metadata.namespace) secret/\(.metadata.name)\"" > oldsecrets.txt

# 6. delete old service account token secrets
cat oldsecrets.txt | xargs -L 1 kubectl delete
```

Obviously, step 4 is the least well-defined, since it means triggering a recreation of every pod in the system and redistributing updated tokens to anything that captured them for out-of-cluster use.

**Comment by liggitt** [comment]
Something like https://github.com/kubernetes/kubernetes/issues/91070#issuecomment-628709708 should be added to the service account admin documentation page, with lots of caveats around step 4.

Long-term time-bound service account tokens will make it much more reasonable to rotate keys automatically, since all minted tokens have a finite lifetime

**Comment by Matty9191** [comment]
Thanks @liggitt for the explanation. That makes perfect sense, and it looks like your comment in 22351 was spot on. Hopefully this thread will others who are checking into this!
