### ISSUE TITLE
TestMaxResourceSize integration test being flaky

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#91075]
**Which jobs are flaking**:

test/integration is flaking.  For example - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90907/pull-kubernetes-integration/1260640250275827716

**Which test(s) are flaking**:

     --- FAIL: TestMaxResourceSize/StrategicMergePatchType_should_handle_a_patch_just_under_the_max_limit (32.01s)
        max_request_body_bytes_test.go:125: expected success or bad request err, got Patch https://127.0.0.1:39661/api/v1/namespaces/default/secrets/test?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

    === FAIL: test/integration/apiserver TestMaxResourceSize (94.37s) 

**Testgrid link**:

https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestMaxResourceSize

This is also evident from testgrid that this test is flaking a lot.

**Comment by liggitt** [comment]
This test submits a large request. The CI machines have no resource guarantees, and tend to be overcommitted. This seems likely to simply be resource starvation on the test machines.

**Comment by liggitt** [comment]
/sig testing

what is the recommendation here?

**Comment by liggitt** [comment]
The same test in post-submit:

https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master&width=5&sort-by-failures=&include-filter-by-regex=TestMaxResourceSize

**Comment by BenTheElder** [comment]
Integration tests are also expected to run on developer machines...
This test sounds overly expensive?

**Comment by liggitt** [comment]
> Integration tests are also expected to run on developer machines...

on my laptop:

```
--- PASS: TestMaxResourceSize (10.00s)
    --- PASS: TestMaxResourceSize/Create_should_limit_the_request_body_size (0.02s)
    --- PASS: TestMaxResourceSize/Update_should_limit_the_request_body_size (0.11s)
    --- PASS: TestMaxResourceSize/Patch_should_limit_the_request_body_size (0.11s)
    --- PASS: TestMaxResourceSize/JSONPatchType_should_handle_a_patch_just_under_the_max_limit (1.76s)
    --- PASS: TestMaxResourceSize/JSONPatchType_should_handle_a_valid_patch_just_under_the_max_limit (0.08s)
    --- PASS: TestMaxResourceSize/MergePatchType_should_handle_a_patch_just_under_the_max_limit (1.41s)
    --- PASS: TestMaxResourceSize/MergePatchType_should_handle_a_valid_patch_just_under_the_max_limit (0.06s)
    --- PASS: TestMaxResourceSize/StrategicMergePatchType_should_handle_a_patch_just_under_the_max_limit (1.62s)
    --- PASS: TestMaxResourceSize/StrategicMergePatchType_should_handle_a_valid_patch_just_under_the_max_limit (0.04s)
    --- PASS: TestMaxResourceSize/ApplyPatchType_should_handle_a_patch_just_under_the_max_limit (0.01s)
    --- PASS: TestMaxResourceSize/ApplyPatchType_should_handle_a_valid_patch_just_under_the_max_limit (0.03s)
    --- PASS: TestMaxResourceSize/Delete_should_limit_the_request_body_size (0.01s)
    --- PASS: TestMaxResourceSize/create_should_limit_yaml_parsing (0.00s)
    --- PASS: TestMaxResourceSize/create_should_handle_a_yaml_document_just_under_the_maximum_size_with_correct_nesting (0.01s)
    --- PASS: TestMaxResourceSize/create_should_handle_a_yaml_document_just_under_the_maximum_size_with_unbalanced_nesting (0.12s)
    --- PASS: TestMaxResourceSize/create_should_limit_json_parsing (0.11s)
    --- PASS: TestMaxResourceSize/create_should_handle_a_json_document_just_under_the_maximum_size_with_correct_nesting (0.07s)
    --- PASS: TestMaxResourceSize/create_should_handle_a_json_document_just_under_the_maximum_size_with_unbalanced_nesting (0.15s)
```

that doesn't seem awful to me

**Comment by BenTheElder** [comment]
it doesn't look like this fails often currently.
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestMaxResourceSize

**Comment by liggitt** [comment]
stopped running these in presubmit in https://github.com/kubernetes/kubernetes/pull/92879

/close
