### ISSUE TITLE
Another duplicate of  fieldSelector syntax and usage not documented #15128 

### ISSUE THREAD

**Issue by romanseidl** [kubernetes/kubernetes#91101]
**What would you like to be added**:
Documentation that has been missing for years.

**Why is this needed**:
Either just drop the feature or document it. Else it is simply useless.

I am looking forward to this Issue being removed for the duplication. But it seems to be intentional. There is already many duplicates of the first issue because this keeps getting ignored.

**Comment by liggitt** [comment]
is https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/ what you are referring to?
