### ISSUE TITLE
Add integration tests for pods becoming schedulable

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#91111]
Pods can become schedulable due to different reasons. Some of them span across different objects (like nodes added, pods being scheduled, etc).

The logic goes all the way from getting the events to moving pods in the scheduling queues and finally doing the scheduling attempt.

More coverage would be useful.

**Comment by nodo** [comment]
Hey @alculquicondor - I would be happy to help out with this if you want. However, I am a new contributor, would you be able to give some pointers? At which level were you thinking to add more coverage exactly?

**Comment by alculquicondor** [comment]
Take a look at #91071 for reference.

**Comment by nodo** [comment]
Thanks, sounds good. Do you already an idea of what the next test could be? I can start working on it using the structure of your PR.

**Comment by alculquicondor** [comment]
The basic idea is to increase the coverage of this file https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go

It is possible that we cover some of it in https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/predicates_test.go but, at quick glance, it doesn't seem like it.

**Comment by nodo** [comment]
cool, I will give it a go in the next days.

/assign

**Comment by alculquicondor** [comment]
Thanks

/remove-help

**Comment by nodo** [comment]
What is the status of https://github.com/kubernetes/kubernetes/pull/91071 ? Can I assume the structure of the test will be the same?

Also, to double check that I am on the right track, I have added a test to check a pod becoming schedulable after a taint is removed from a node. Does it make sense to you? If you have any particular tests in mind I am happy to work on those, otherwise, I can just pick some other events.

**Comment by alculquicondor** [comment]
Yes, that is a good one. I didn't have enough time to go through the whole list. But one test per event should be enough.

An event would be "node created", "node updated", "other pod created", "other pod finished", etc.

**Comment by alculquicondor** [comment]
I just pinged the reviewer for #91071 so that we get it merged soon.

**Comment by alculquicondor** [comment]
@nodo, could you list which other test cases you would like to cover, if any?

**Comment by nodo** [comment]
I was thinking to cover these:
- A scheduled pod gets updated (e.g. it requires less resources)
- A new pod get scheduled (e.g. using inter-pod affinity)

I can see there are more events related to pv, pvc, storage class and services, which I am happy to cover but it's not obvious how to test.

What do you think?

**Comment by alculquicondor** [comment]
I'd only do the 2nd. And you can call it a day there.

**Comment by nodo** [comment]
@alculquicondor for some reason the issue wasn't closed automatically and I don't have the permissions to do that : -)

**Comment by alculquicondor** [comment]
You should have done `Fixes #91111` in your PR description, instead of `Fixes of #` 😅 

Thanks for working on this! But please do the clean up follow up.

/close

**Comment by nodo** [comment]
My bad sorry for the typo :-) 

> Thanks for working on this! But please do the clean up follow up.

No worries and I will definitely follow up with the clean up. Thanks for the reviews!
