### ISSUE TITLE
How to create master & node with full setup in yaml 

### ISSUE THREAD

**Issue by Manjunath34** [kubernetes/kubernetes#91115]
How to create master & node with full setup(etcd controller api scheduler docker) through yaml

**Comment by bai** [comment]
Hey! GitHub issues is used primarily for Kubernetes bug report or feature request. Please use one of the other channels for such questions, e.g. Slack, Discuss, or StackOverflow.

**Comment by gianarb** [comment]
You can also have a look at cluster-api for that. Please feel free to reach out on Slack for this kind of questions.

https://cluster-api.sigs.k8s.io/

I am gonna close this issue for now

/close
