### ISSUE TITLE
[Flakey Test] pull-kubernetes-e2e-kind high failure rate

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/kubernetes#91128]
**Which jobs are flaking**: pull-kubernetes-e2e-kind

**Which test(s) are flaking**: Various

**Testgrid link**: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind

**Reason for failure**: Unknown

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by liggitt** [comment]
I know @BenTheElder is already aware, but I didn't see another tracking issue. In general, our CI nodes seem more resource constrained recently (xref https://github.com/kubernetes/kubernetes/issues/91075)

**Comment by BenTheElder** [comment]
In addition to the resource constraints we may be hitting in the CI there've been multiple seemingly unrelated issues hitting us
- iptables userspace lock being held too long (hopefully improved in CNI plugins 0.8.6 which we've rolled out)
- this particular test case has started flaking excessively: https://github.com/kubernetes/kubernetes/issues/73099
- kubelet bug with auto-selected node IP not matching the expected IP family, fix is out for review in https://github.com/kubernetes/kubernetes/pull/91125
- ...  tbd

**Comment by BenTheElder** [comment]
better flake hunting data:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-e2e-kind

**Comment by BenTheElder** [comment]
Worth noting that pull-kubernetes-e2e-gce is failing badly as well:
> Success rate over time: 3h: 57%, 12h: 62%, 48h: 59%
https://prow.k8s.io/?job=pull-kubernetes-e2e-gce

> Success rate over time: 3h: 43%, 12h: 44%, 48h: 41%
https://prow.k8s.io/?job=pull-kubernetes-e2e-kind

kind runs faster and people push broken PRs so sometimes it has a higher failure rate due to just running more times on broken PRs

Looks to me like our e2e are generally poor right now.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/91045

**Comment by BenTheElder** [comment]
there's a broken batch right now (haven't figured out what PR is offending) causing the build to fail so the stats including that batch are off. selecting type=presubmit in the dashboard avoids that. (instead of including type=batch too)

**Comment by BenTheElder** [comment]
So last night before I clunked 💤 I found that some of the CI nodes on which this we run prow (on which the pods in which we run this job and others run) ... a few of them seem to have very high CPU usage from system components (namely the host kubelet), I'm looking into it. Smells like a bug in k8s 1.14.

This would explain why we've generally seen reliability in the CI jobs go down. FYI @neolit123

**Comment by liggitt** [comment]
I'd be very interested in a CPU profile… hot loop in kubelet?

**Comment by BenTheElder** [comment]
Discussed elsewhere, was not able to get a profile (debugging not enabled?), but dumped and passed along the logs at least.

Rolling forward to the latest GKE 1.14.X-gke.Y in the build cluster to at least get us a tad more up to date and get fresh node VMs.

**Comment by tedyu** [comment]
From an e2e-kind run on master branch today, I saw a lot of (212, to be exact) log lines in the following form :
```
May 16 17:43:17 kind-worker kubelet[767]: E0516 17:43:17.585838     767 kubelet_volumes.go:154] orphaned pod "888e1e61-0ffa-4ee2-99f0-776f0ef1b84d" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
```

**Comment by BenTheElder** [comment]
graph pretty much speaks for itself, rolling the nodes cleared things up for now:
<img width="1529" alt="Screen Shot 2020-05-16 at 5 30 45 PM" src="https://user-images.githubusercontent.com/917931/82133016-503b2580-979b-11ea-8289-466737555caf.png">

**Comment by BenTheElder** [comment]
(note that those very short failures along the bottom of the graph are nearly always due to code that doesn't compile)

**Comment by dims** [comment]
@BenTheElder thanks!

**Comment by BenTheElder** [comment]
At least currently, kind is passing much more often than GCE again, and they're both passing at rates I'd have expected until very recently...

> Success rate over time: 3h: 100%, 12h: 82%, 48h: 44%

vs

> Success rate over time: 3h: 100%, 12h: 71%, 48h: 59%

I'd like to leave this open to see how we do through Monday though, the weekends are often very different.
