### ISSUE TITLE
GOAWAY may cause client error when client request server in high concurrency

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#91131]
**What happened**:

We enabled [GOAWAY](https://github.com/kubernetes/kubernetes/pull/88567) feature in our large-scale cluster, and we found client(Kubelet) may got error(500 http code response) like `request declared a Content-Length of N but only wrote 0 bytes` after received GOAWAY frame. 

I had already re-produce this bug and open an [issue](https://github.com/golang/go/issues/39086) in golang repo. So far I think this bug only occur with a small probability when client request server in high concurrency use a same httpclient instance, and it's a golang sdk bug in http client.

**Before I solved this issue, I suggest do NOT enable GOAWAY(`--goaway-chance=0`) feature. As it's a golang sdk bug(currently I known and doubt) in http client, revert GOAWAY feature(codes) is not necessary.**

**Comment by answer1991** [comment]
cc @lavalamp @liggitt @deads2k @wojtek-t

**Comment by lavalamp** [comment]
Thanks for the report.

**Comment by deads2k** [comment]
> Before I solved this issue, I suggest do NOT enable GOAWAY(`--goaway-chance=0`) feature. As it's a golang sdk bug(currently I known and doubt) in http client, revert GOAWAY feature(codes) is not necessary.

Based on https://github.com/kubernetes/kubernetes/blob/v1.19.0-beta.0/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go#L59 not setting the field, I think it defaults that way, so that's good.

We will leave the option and filter so that when golang updates its client, we will have a simple way to turn it on and execute it.

**Comment by answer1991** [comment]
Sure.

I am trying to fix the golang http client issue and will update progress at [golang issue](https://github.com/golang/go/issues/32441). After golang http client issue fixed, I will add more concurrent test cases to see if there are any other bugs may occur by GOAWAY feature.

BTW, we still enable GOAWAY feature in our production cluster, because there is no any evidence told us this error will influence SLO, as all most components(kubelet, controller-manager, scheduler) is controller work mode and will re-try after got error.

/assign

**Comment by answer1991** [comment]
Golang version 1.13.13 or 1.14.5 required, which will release at 07/01/2020.

**Comment by answer1991** [comment]
Kubernetes v1.19(or master branch) now is using golang 1.15, and golang 1.15 has fixed the issue. And [Kubernetes v1.18 backport golang 1.15](https://github.com/kubernetes/kubernetes/pull/94037) is on going.

Let me add more test cases to ensure the error will not happen again.

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by answer1991** [comment]
I think we should re-open this issue because of https://github.com/golang/go/issues/41234 .

/re-open

**Comment by LiuNingqian** [comment]
Hi, I find the same error for Kubernetes server version v1.13.3 and Golang version 1.12.17.
I want to know if upgrading the Kubernetes version is only way to solve the problem?
