### ISSUE TITLE
Document the size of "terminationMessage"

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes/kubernetes#91133]
In out case, we use `terminationMessagePath` to point to certain file, use it to pass information between `Pod/Container` to our `Controller`,  seems the file has size limitation to `4096`
https://github.com/kubernetes/kubernetes/blob/96e13de777a9eb57f87889072b68ac40467209ac/pkg/kubelet/kuberuntime/kuberuntime_container.go#L420

So do we document the limitation somewhere, thanks

**Comment by wawa0210** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core

openapi detailed description about terminationMessagePath

**Comment by vincent-pli** [comment]
@wawa0210 
Thanks
