### ISSUE TITLE
--dry-run & --validate not picking up errors in deployment template

### ISSUE THREAD

**Issue by Gerrit-K** [kubernetes/kubernetes#91144]
**What happened**:
This is a re-open of #38748. 

If a deployment manifest contains environment variables with non-string values, it cannot be applied to the cluster, but a `apply --dry-run --validate` will not report any errors.

**What you expected to happen**:
`--dry-run --validate` should detect and report the invalid environment variable.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ kubectl create deployment dp --image=img --dry-run -o yaml | awk '/name: img/{print "        env:\n        - name: FOO\n          value: true"}1' > test.yaml

$ kubectl apply -f test.yaml --dry-run --validate
deployment.apps/dp created (dry run)

$ kubectl apply -f test.yaml
Error from server (BadRequest): error when creating "test.yaml": Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|ec":{"containers":[{"env":[{"name":"FOO","value":true}],"image":"img","name":"img","resources":{}}]}|...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"169db3bff4b5fb7722e967c5b6356713f05f15ed", GitTreeState:"clean", BuildDate:"2020-04-03T16:14:09Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure Kubernetes Service (AKS)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhouya0** [comment]
https://github.com/kubernetes/kubernetes/issues/64830 Try using `--dry-run=server`

**Comment by Gerrit-K** [comment]
@zhouya0 it didn't work on my version, but you pointed me to the right direction.

In kubectl 1.18 the parameters changed from `--dry-run` and `--server-dry-run` to `--dry-run=client` and `--dry-run=server`. Thus, on my kubectl (1.16/1.15) I still have to use `--server-dry-run`, but in the end that worked for me and detected the error above.

More on that can be read [here](https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/).
