### ISSUE TITLE
Kubectl create with --all-namespaces or set of namespaces. Or Sharing resources with namespaces

### ISSUE THREAD

**Issue by sureshpalemoni** [kubernetes/kubernetes#91147]
**What would you like to be added**:
Is there any way I can create resources in multiple namespaces at the same time? Or Can we share the resources like configmaps, secrets with other namespaces?

**Why is this needed**:
I had to create the same secret in multiple namespaces and had to run the command several times. (Not sure how to make a secret shareable to other namespaces -  This would be also good to implement, if resources can be shared with other namespaces - If there is any existing solution please let me know.

**Comment by dineshba** [comment]
@sureshpalemoni  May be useful for you https://github.com/EmberStack/kubernetes-reflector

**Comment by michaelgugino** [comment]
I don't think the API server will accept multiple namespace, so the best the cli can do is loop over the namespaces and perform the same operation with each namespace.

You can get the same functionality with a bash for loop:

```sh
for i in ns1 ns2 ns3 ns4; do kubectl apply -f file.yaml --namespace $i; done
```

This may be obvious to some, just leaving it here in case someone stumbles upon this issue in the future :)
