### ISSUE TITLE
inflightUsageMetricUpdatePeriod in maxinflight.go is too short

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#91173]
**What happened**:
While preparing for an enhancement, I studied the existing concurrency metrics produced by the maxinflight filter.  The two numbers of currently executing requests (mutating and readonly) are very bouncy, and the existing code reports windowed high-water-marks instead of the very bouncy numbers.  This makes sense, because Prometheus metrics are scraped at a much lower rate than the rate at which the raw numbers change.  However, the window currently used --- one second (see https://github.com/kubernetes/apiserver/blob/ff4c7be184fe264c4aa58f99e084f7a6ce748382/pkg/server/filters/maxinflight.go#L42) --- is much shorter than the typical interval between Prometheus scrapes.  The default scrape interval in the Prometheus server is 10 seconds.  I do not know what is typical practice for scraping kube-apiservers, but I expect it is well over 1 second.

**What you expected to happen**:
I expected the windows to be wide enough for typical Prometheus configurations to observe each window.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): I found this in master today
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@lavalamp 
@deads2k 
@yue9944882

**Comment by yue9944882** [comment]
@MikeSpreitzer this issue is resolved, is it?
