### ISSUE TITLE
scheduler: `ImageLocality` score plugin improvement

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#91204]
**What would you like to be added**:
redefine the formula, the score should be capped per images instead of pod.

**Why is this needed**:
For the pod that going to be scheduled, `ImageLocality` calculate the score based on the below steps, 
-  Scaled score base on the image size and it's spread over the cluster, 
***image[i].nodes***:  number of nodes that already have image 

![image](https://user-images.githubusercontent.com/6007417/82198995-ae007680-992f-11ea-8578-035b6d0c4089.png)

-  Capped score based on the assumption 90% image size on dockerhub falls into the range [23M ~ 1000M]

***lowerbound***: 23M
***upperbound***:1000M

![image](https://user-images.githubusercontent.com/6007417/82199705-a42b4300-9930-11ea-9fb9-dcd2f7f68990.png)

- Final scores returned for scheduling, 
***maxscore***: 100
![image](https://user-images.githubusercontent.com/6007417/82199952-f704fa80-9930-11ea-901d-b06c25f9e96e.png)

The second step is not well guarded, the assumption is based on the image size while the pod may hold multiple images, it is not surprise to see that total image size of the pods is larger than 1000M, while each of might be only around 300M. 

In this below case, following the above formula, NODE1 and NODE2 willl get the same scores(100), since both of them are capped by the max score (100), the ideal result is score of NODE2 should be larger than NODE1 (all requested images are ready on NODE2) and is preferred, the larger the **sample1** here the more scores should be expected for NODE2.

![image](https://user-images.githubusercontent.com/6007417/82204735-fe7bd200-9937-11ea-8de4-14607a87efcc.png)

**Comment by chendave** [comment]
cc @alculquicondor @damemi  @Huang-Wei @ahg-g

**Comment by alculquicondor** [comment]
Thanks a lot for summarizing the problem. I agree that the formula needs improvement.

I think doing the capping for each image solves the original problem and what @damemi said in https://github.com/kubernetes/kubernetes/pull/91138#discussion_r425995455

**Comment by chendave** [comment]
Here is my thoughts,

step1:  calculate image level priority, for each image (should be same as exsting func `scaledImageScore`)
            `image.score = image.size * (imageState.NumNodes / total nodes)`

step2: cap the each image's score with thresholds, minThreshold and maxThreshold. (should be same as existing func `calculatePriority` except that it's per image instead of pod)
           `100 * (image.score - minThresholds) / (maxThresholds - minThresholds)`

step3: calculate pod level priority, and return the final score, range (0~100)
           `final_score = sum(image.score) / len(images)`

step1 and step2 primarily update the exiting code to make it is image level priorities instead of pod level.

Based on the above steps,  consider the below two cases, a pod with four images, 

- case1: All images are ready on  node2
node1 (0, 80, 90, 60)   - final score is:  (80+90+60) / 4 = 57
node2 (90, 80, 90, 60)  - final score is:  (90+80+90+60) / 4 = 80    √  

- case2: each node has three images ready but image1 is larger than image2.
node1 (0, 80, 70, 60)   - final score is:  (80+70+60) / 4 = 52
node2 (90, 0, 70, 60)  - final score is:  (90 +70+60) / 4 = 55    √  



thoughts? 
cc @alculquicondor @damemi @Huang-Wei @ahg-g

**Comment by ahg-g** [comment]
Thanks chendave@, can you update the the examples with the score that we would have gotten with the current function?

**Comment by alculquicondor** [comment]
For reference, see this analysis for a different plugin #90475

**Comment by alculquicondor** [comment]
Also it's worth to see the difference with just capping per pod, instead of per container.

**Comment by ahg-g** [comment]
can you also describe the image sizes you used? the example in the original post assumed three images, while your analysis is assuming four.

**Comment by damemi** [comment]
agree with @ahg-g and @alculquicondor, the explanation in https://github.com/kubernetes/kubernetes/issues/91204#issuecomment-631246361 looks good but just to be sure it would be nice to see the math worked out with image sizes, and compared to the current formula

**Comment by chendave** [comment]
Sorry for the confusion, let me switch back to the original three images, update the image size a little bit to make it easier to understand, and also fit to the case of `minThreshold` and `maxThreshold`.

Here is the pod, 
![image](https://user-images.githubusercontent.com/6007417/82537616-e3e66a80-9b7c-11ea-8cfd-7a06f32318ea.png)



and two nodes in the cluster, 
![image](https://user-images.githubusercontent.com/6007417/82537646-f2348680-9b7c-11ea-8521-3a2a05bb4161.png)


Let's see the difference between two approaches, 

 **- capping per pod,**

 **step1:** 
![image](https://user-images.githubusercontent.com/6007417/82535183-1726fa80-9b79-11ea-8262-67249871166f.png)

NODE1: 
scores =  30 * 2/3 + 1500 * 2/3 = 1020

NODE2: 
scores = 30 * 2/3 + 600 * 2/3 + 1500 * 2/3 = 1420

**step2:**
![image](https://user-images.githubusercontent.com/6007417/82536240-bef0f800-9b7a-11ea-86e1-70213c2a66ec.png)

NODE1: 
1020 >  1000 (maxThreshold),  capped_score = 1000

NODE2:
1420 > 1000 (maxThreshold),  capped_score = 1000


**step3:**
![image](https://user-images.githubusercontent.com/6007417/82536326-ddef8a00-9b7a-11ea-95e1-35dd2854c895.png)

*upperbound = 100*  / *lowerbound = 23* /   *maxscore = 100*

NOTE1:
score = 100 * (1000 - 23) / (1000 - 23) = 100

NODE2: 
score = 100 * (1000 - 23) / (1000 - 23) = 100

**potentially, *NODE1* will be chose for scheduling.**

**- capping per images,**

step1: calculate image level priority, 
`image.score = image.size * (imageState.NumNodes / total nodes)`

NODE1:
image1: score = 30 * 2/3 = 20
image2: score = 0
image3: score = 1500 * 2/3 = 1000

NODE2:
image1: score = 30 * 2/3 = 20
image2: score = 600 * 2/3 = 400
image3: score = 1500 * 2/3 = 1000


step2/3: cap the each image's score with thresholds and calculate the image score, 

![image](https://user-images.githubusercontent.com/6007417/82538925-12fddb80-9b7f-11ea-82b2-a0f51234842a.png)

`100 * (capped_image_score - minThresholds) / (maxThresholds - minThresholds)`

NODE1:
image1: score = 100 * (23 - 23) / ( 1000 - 23) = 0
image2: score = 0
image3: score = 100 * (1000 - 23) / (1000 - 23) = 100

NODE2:
image1:  score = 100 * (23 - 23) / ( 1000 - 23) = 0
image2: score = 100 * (400 - 23) / (1000 - 23) = 35
image3: score = 100 * (1000 - 23) / (1000 - 23) = 100

step4: final score
`final_score = sum(image.score) / len(images)`

NODE1: final_score = 100 / 3 = 33
NODE2: final_score = 135 / 3 = 45

**NODE2 will be chosen for scheduling.**

**Comment by ahg-g** [comment]
Computing the score per image and normalizing by the number of images make sense to me at first glance, but I would like to see more examples.

It would be much easier to digest the analysis if it was summarized in tabular form comparing three scoring functions: (1) current one, (2) one in https://github.com/kubernetes/kubernetes/pull/91138 and (3) https://github.com/kubernetes/kubernetes/issues/91204#issuecomment-631246361

multiple big images, multiple small images (total less than the threshold) and a mix. Also, compare cases where the spread is high vs low.

**Comment by alculquicondor** [comment]
Yes, we don't need to see the individual steps, but a good set of scenarios with final scores.

> Also it's worth to see the difference with just capping per pod, instead of per container.

I didn't mean just the old function. We know it's very ineffective. What I meant is capping per pod using the strategy you used in #91138

**Comment by chendave** [comment]
Did some comparison here, 
```
         pods              |               nodes                    | cap per pod (current) |  cap per image only （#91138）|   cap and normalize per image 
-----------------------------------------------------------------------------------------------------------------------------------------------------------	
[10, 20, 30]  & small      | (20, 30) (10, 20, 30) (20, 200)        |  [1, 2, 0]            |  [0,0,0]                      |   [0,0,0]
[800, 1200, 1500] &  big   | (1500)  (1200, 1500) (800, 1200, 1500) |  [100, 100, 100]      |  [48, 76, 85]                 |   [33, 59, 67]	
[30, 600, 1500]  & mix     | (30, 1500)  (30, 600, 1500) (200)      |  [100, 100, 0]        |  [32, 39, 0]                  |   [33, 45, 0]
```

**Comment by ahg-g** [comment]
Normalizing by the number of images gives each image the same "weight". Another option is to try and multiply each image score with its size divided by the total size of all images, can you add that as another option?

**Comment by alculquicondor** [comment]
> Another option is to try and multiply each image score with its size divided by the total size of all images

I don't understand that suggestion. The score of an image is already proportional to its size.

I would say the difference between the two suggestions is:

- Capping per pod cares about total downloaded size
- Capping per image gives roughly the same importance to each image.

I think capping per pod makes more sense. However, there is some information we are losing in both suggestions, as seen in the first case. Even if a lot of small images need to be downloaded, we are giving a 0 score to all nodes.
I think a cap from `[minThreshold, images*maxThreshold]` makes more sense, as @damemi suggested in the initial PR.

**Comment by ahg-g** [comment]
> I don't understand that suggestion. The score of an image is already proportional to its size.

It helps giving more importance to larger images.

**Comment by ahg-g** [comment]
If the statistics are accurate with regards to image size distribution, then having many small images all scoring zero isn't common. For the more common cases (sizes between 32-1000), it seems that both approaches will likely give similar results, so I am fine with both approaches.

**Comment by alculquicondor** [comment]
> It helps giving more importance to larger images.

That would make the score proportional to the square of the size.

Just to play safe (ie, not make the score too strong in a way that could affect spreading or resource allocation) I suggest we go with capping per pod. And then we can re-evaluate next release.

**Comment by alculquicondor** [comment]
> If the statistics are accurate with regards to image size distribution

Speaking of statistics. They might have changed since this plugin was first developed. Is there a reliable source?

**Comment by ahg-g** [comment]
> That would make the score proportional to the square of the size.

True for uncapped images, but everything we are doing is just heuristics, and the suggestion is just for the sake of exploring options, not advocating a specific one.

Playing it safe sounds good to me.

**Comment by chendave** [comment]
> > Another option is to try and multiply each image score with its size divided by the total size of all images
> 
> I don't understand that suggestion. The score of an image is already proportional to its size.
> 
+1,  image size has been counted for scoring, dive by the number of images make it looks like those images has the same weight but they hold different score.

> I would say the difference between the two suggestions is:
> 
> * Capping per pod cares about total downloaded size
> * Capping per image gives roughly the same importance to each image.
> 
> I think capping per pod makes more sense. However, there is some information we are losing in both suggestions, as seen in the first case. Even if a lot of small images need to be downloaded, we are giving a 0 score to all nodes.
> I think a cap from `[minThreshold, images*maxThreshold]` makes more sense, as @damemi suggested in the initial PR.

this approach needs the smallest change and the minimum impact I think.

**Comment by chendave** [comment]
> If the statistics are accurate with regards to image size distribution, then having many small images all scoring zero isn't common. For the more common cases (sizes between 32-1000), it seems that both approaches will likely give similar results, so I am fine with both approaches.

+1,  this is not common case we can see that a pod with lots of small images (all < 23M), but a corner case that might be improved. 

No perfect solution so far, but either one is better than the original one IMHO.

**Comment by chendave** [comment]
btw, https://github.com/kubernetes/kubernetes/pull/91138 has been updated to the second approach (capping and normalization per image).

**Comment by ahg-g** [comment]
> I think a cap from [minThreshold, images*maxThreshold] makes more sense, as @damemi suggested in the initial PR.

I would go with this approach as well, it preserves the behavior for multiple small images, and improve it for multiple big ones.

**Comment by damemi** [comment]
`[minThreshold, images*maxThreshold]` seems like a simple enough compromise for now, and running through some of the examples with that formula it does get more of the specificity you're looking for with large images without normalizing all smaller images right to 0 (so we keep some of the detail there too).

I would like to see some updated statistics on the thresholds, and while 90% of the images might fall between them I'm wondering if that's a totally normal distribution. @ahg-g's suggestion in https://github.com/kubernetes/kubernetes/issues/91204#issuecomment-633589763 got me (tangentially) thinking if we could use thresholds that are more relevant to the pod in question, rather than all of Dockerhub. 

Because as it is now hypothetical pods (and clusters) which have all small images don't get much benefit from ImageLocality. But I recognize that could be intentional since download resources for small images is ultimately negligible.

**Comment by chendave** [comment]
> `[minThreshold, images*maxThreshold]` seems like a simple enough compromise for now, and running through some of the examples with that formula it does get more of the specificity you're looking for with large images without normalizing all smaller images right to 0 (so we keep some of the detail there too).
> 
> I would like to see some updated statistics on the thresholds, and while 90% of the images might fall between them I'm wondering if that's a totally normal distribution. @ahg-g's suggestion in [#91204 (comment)](https://github.com/kubernetes/kubernetes/issues/91204#issuecomment-633589763) got me (tangentially) thinking if we could use thresholds that are more relevant to the pod in question, rather than all of Dockerhub.
> 
Good point! This is definitely something we can explore in the future,  let's go with @alculquicondor  suggestion for the sake of "play safe" and revisit this later.
> Because as it is now hypothetical pods (and clusters) which have all small images don't get much benefit from ImageLocality. But I recognize that could be intentional since download resources for small images is ultimately negligible.

I also believe that scoring of small images by zero is intentional,  but seems like making lots of small images in pod accountable for the scheduling is slightly better.

**Comment by alculquicondor** [comment]
It looks like we have consensus. Can you update the PR?

**Comment by chendave** [comment]
PR updated, pls kindly let me know if I miss something.
