### ISSUE TITLE
Flaky test: TestUpgradeResponse

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9121]
A test is flaky.

https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/64951456

--- FAIL: TestUpgradeResponse (0.17s)
	upgrade_test.go:82: 3: unexpected non-nil err from client.Do: Get http://127.0.0.1:52842: net/http: transport closed before response was received

This is with go1.4, though I suspect it is not version-related.
This is during race testing, but there is not a specific message about a race being detected. Probably things are happening in a different order, causing a test expectation to fail.
This is also during coverage measurement, which might also affect timing.

Please try running this test many times to see if it fails again, and then fix it. Run with race detection and coverage if needed to repro.

@ncdc I think you wrote this test.

**Comment by brendandburns** [comment]
@erictune is this still flaky?

**Comment by mvdan** [comment]
Built a race test executable and ran it 10,000 times as follows:

    stress -p 200 ./test -test.run '^TestUpgradeResponse$'

I'm positive that the flake is now gone, most probably solved by c83786979c6fa.

**Comment by goltermann** [comment]
It looks like we have no reason to think there's still a flake here.  Should we close?

**Comment by mvdan** [comment]
@goltermann that's exactly what I implied :)

Ping @erictune @brendandburns

**Comment by wojtek-t** [comment]
Closing - I also didn't see that since a long time.
