### ISSUE TITLE
Move pkg/kubelet/cm/cpuset to staging

### ISSUE THREAD

**Issue by eMGabriel** [kubernetes/kubernetes#91220]
**What would you like to be added**:
I would like to request moving `pkg/kubelet/cm/cpuset` to `staging`.

**Why is this needed**:
We depend on `cpuset` in our projects:
[nokia/danm](https://github.com/nokia/danm/search?q=cm%2Fcpuset&type=Code)
[nokia/CPU-Pooler](https://github.com/nokia/CPU-Pooler/search?q=cm%2Fcpuset&type=Code)
Go modules cannot properly handle `k8s.io/kubernetes` as dependency. Similar issues: #82437, #87965
Also Kubernetes user guide states that projects should not `import k8s.io/kubernetes` mono-repo, instead use individual komponent projects provided.
Moving cpuset to staging would eliminate `k8s.io/kubernetes` import from our projects.

**Comment by eMGabriel** [comment]
@kubernetes/sig-node-bugs

**Comment by jackfrancis** [comment]
@SergeyKanzhelev I'm happy to take on this housekeeping issue. Can you point me to an example of where this might land (I assume in `staging/src/k8s.io` somewhere)
