### ISSUE TITLE
Job will never succeed because pod GC deletes the success pod 

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#91235]
**What happened**:
Job controller will create pod in a loop, b/c pod gc controller delete the succeed pod since the number of succeed and failed pod exceed the `--terminated-pod-gc-threshold`
**What you expected to happen**:
Job can finished 
**How to reproduce it (as minimally and precisely as possible)**:
1. set `--terminated-pod-gc-threshold` to a lower no. eg 1
2. create a job with `completions` to a higher no. eg 6
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig apps
/kind bug

**Comment by Pingan2017** [comment]
ping @kubernetes/sig-apps-bugs

**Comment by soltysh** [comment]
This is mentioned in https://github.com/kubernetes/kubernetes/issues/28486, please move the discussion over there. It is a known limitation :sweat: 
/close
