### ISSUE TITLE
Override the CSI test images

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#91247]
**What would you like to be added**:
 RightNow CSI tests hardcoded the images in the manifests here: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests/storage-csi, need to figure out how to override the images runtime.

**Why is this needed**:
This is required to use the custom images built and override them while running the e2e tests.

**Comment by BenTheElder** [comment]
@dims is basically also handling this while fixing https://github.com/kubernetes/kubernetes/issues/91242

**Comment by mkumatag** [comment]
> @dims is basically also handling this while fixing #91242

@BenTheElder I don't see any relevant changes in that PR which overrides the actual images in the manifest, when I tried on my test setup - it didn't override the CSI images in the manifest when I override the QuayK8sCSI registry. I will add more information to this issue
