### ISSUE TITLE
[Failing Test] Storage tests are failing due to quay.io being down

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#91242]
**Which jobs are failing**:

`skew-cluster-latest-kubectl-stable1-gce`
`gce-cos-master-default`
`gce-cos-master-alpha-features`
`gci-gce-ingress`
`gce-cos-master-reboot`
`gce-cos-master-scalability-100`
`Conformance - GCE - Master`
`integration-master`
`kind-master-parallel`
`kind-ipv6-master-parallel`

**Which test(s) are failing**:

All relying on volume snapshot controller.

**Since when has it been failing**:

`5/18/20 12:38 AM PT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking

**Reason for failure**:

https://quay.io/ is experiencing downtime, causing failure to pull image in volume snapshot controller deployment: https://github.com/kubernetes/kubernetes/blob/6a0e01880ad7ea4c110040c3be417516c0bf6bca/cluster/addons/volumesnapshots/volume-snapshot-controller/volume-snapshot-controller-deployment.yaml#L26

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing
/sig storage

**Comment by hasheddan** [comment]
@xing-yang is there an issue open for moving this quay.io image to community infra?

**Comment by xing-yang** [comment]
@hasheddan we haven't talked about it.  Let me open an issue about it.

**Comment by hasheddan** [comment]
Potential fix here: https://github.com/kubernetes-csi/node-driver-registrar/pull/82

**Comment by BenTheElder** [comment]
/assign @dims 
dupes: https://github.com/kubernetes/kubernetes/issues/91253 https://github.com/kubernetes/kubernetes/issues/91255

**Comment by BenTheElder** [comment]
short term work around https://github.com/kubernetes/kubernetes/pull/91257

**Comment by BenTheElder** [comment]
https://prow.k8s.io/?job=pull-kubernetes-e2e-kind lots of green bouncing back
thanks @dims!
