### ISSUE TITLE
Kubernetes auth plugin for Amazon EKS

### ISSUE THREAD

**Issue by dany74q** [kubernetes/kubernetes#91251]
**What would you like to be added**:
An authentication plugin for communicating with an EKS cluster.

**Why is this needed**:
Currently, the kubernetes go client comes bundled with several authentication plugins - however, EKS is missing.

I believe that it would ease users to have such a plugin, as EKS being one of the major three managed Kubernetes platforms out there (EKS, AKS, GKE); if not only for reference as to how one authenticates to EKS programatically.

**Comment by enj** [comment]
See comment at https://github.com/kubernetes/kubernetes/pull/91254#issuecomment-630963728

/close
