### ISSUE TITLE
imagePullSecrets in ServiceAccount should have "x-kubernetes-patch-strategy": "merge"

### ISSUE THREAD

**Issue by Jamstah** [kubernetes/kubernetes#91250]
**What would you like to be added**:
imagePullSecrets in the pod spec use a merge strategy, but they don't in the ServiceAccount.

**Why is this needed**:
Consistency, and it makes sense.

**Comment by apelisse** [comment]
Thanks for reporting this bug, I'll look into it!

/wg api-expression

**Comment by Jamstah** [comment]
@apelisse i have a PR here but am waiting on my CCLA: https://github.com/kubernetes/kubernetes/pull/91256

New to contributing to k8s, I'm not sure if the PR needs an API review, so any advice appreciated!
