### ISSUE TITLE
ci-kubernetes-node-kubelet-flaky has been constantly failing

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#91263]
**Which jobs are failing**:
ci-kubernetes-node-kubelet-flaky 

**Which test(s) are failing**:
* [sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads NAS parallel benchmark (NPB) suite - Embarrassingly Parallel (EP) workload
* [sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads TensorFlow workload 
* [sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads NAS parallel benchmark (NPB) suite - Integer Sort (IS) workload 

**Since when has it been failing**:
This has been failing since before 5/4 (a while).

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-flaky

**Reason for failure**:
```
[sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads NAS parallel benchmark (NPB) suite - Embarrassingly Parallel (EP) workload 
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:118
 Unexpected error:
     <*errors.errorString \| 0xc00057e800>: {
         s: "pod ran to completion",
     }
     pod ran to completion
 occurred /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:103
```

```
[sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads TensorFlow workload 

_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:127
 Unexpected error:
     <*errors.errorString \| 0xc00057e800>: {
         s: "pod ran to completion",
     }
     pod ran to completion
 occurred
 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:103
```

```

[sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads NAS parallel benchmark (NPB) suite - Integer Sort (IS) workload

_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:109
 Unexpected error:
     <*errors.errorString \| 0xc00057e800>: {
         s: "pod ran to completion",
     }
     pod ran to completion
 occurred
 /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:103
```

**Anything else we need to know**:

The code for the tests is in
https://github.com/kubernetes/kubernetes/blob/6c9aab2b098d92adfeba76a4f542cac900393dd1/test/e2e_node/node_perf_test.go#L118

https://github.com/kubernetes/kubernetes/blob/6c9aab2b098d92adfeba76a4f542cac900393dd1/test/e2e_node/node_perf_test.go#L127 

and
https://github.com/kubernetes/kubernetes/blob/6c9aab2b098d92adfeba76a4f542cac900393dd1/test/e2e_node/node_perf_test.go#L109
respectively

/sig node
/priority important-longterm
/kind failing test
/assign

**Comment by alejandrox1** [comment]
Documenting some node knowledge about this test...
Looking at the prow configuration, https://prow.k8s.io/prowjob?prowjob=56e44b3a-99e4-11ea-aa9b-c69591b579a5 , this e2e job only tests
```
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml
      - --node-test-args= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1 --focus="\[Flaky\]"
```

Which turns out to be only 3 e2e tests
```
I0519 15:32:53.579] Ran 3 of 321 Specs in 169.908 seconds
I0519 15:32:53.579] FAIL! -- 0 Passed | 3 Failed | 0 Pending | 318 Skipped
I0519 15:32:53.579] --- FAIL: TestE2eNode (169.94s)
I0519 15:32:53.579] FAIL
```
ref: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/1262765282464632837#1:build-log.txt%3A648

**Comment by alejandrox1** [comment]
Into the tests themselves...
There is a set of workloads predefined in e2e_nodes/oerf/workloads
https://github.com/kubernetes/kubernetes/blob/6c9aab2b098d92adfeba76a4f542cac900393dd1/test/e2e_node/perf/workloads/workloads.go#L52-L53

* The `npbISWorkload` is defined here https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/perf/workloads/npb_is.go
* The `npbEPWorkload` workload is defined here https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/perf/workloads/npb_ep.go
* and the  `tfWideDeepWorkload` is defined here https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/perf/workloads/tf_wide_deep.go

**Comment by MHBauer** [comment]
looks similar to a lot of other failures I'm seeing in sig-node-containerd test groups related to resource exhaustion, It shows up here as 
```

**Comment by alejandrox1** [comment]
Step through the code and the helper functions that run the workloads definitely need some rewriting to make things more debug-gable but 
```
UnexpectedAdmissionError: Allocate failed due to not enough cpus available to satisfy request, which is unexpected
```
seems to be the main thing happening here
xref: https://github.com/kubernetes/kubernetes/issues/79159

**Comment by alejandrox1** [comment]
Coming back to this...
Each one of the workloads requires a good chunk of resources

https://github.com/kubernetes/kubernetes/blob/6c9aab2b098d92adfeba76a4f542cac900393dd1/test/e2e_node/perf/workloads/tf_wide_deep.go#L46-L54

https://github.com/kubernetes/kubernetes/blob/ada13bd33016c0b72430d00f436d4345b04858bf/test/e2e_node/perf/workloads/npb_ep.go#L46-L54

and

https://github.com/kubernetes/kubernetes/blob/ada13bd33016c0b72430d00f436d4345b04858bf/test/e2e_node/perf/workloads/npb_is.go#L44-L52

And looking at the test artifacts - on spyglass (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/1262765282464632837#1:build-log.txt%3A648) click on "artifacts", then on "artifacts/",  then on "tmp-node-e2e-bccd7779-ubuntu-gke-1804-1-16-v20200330/", and finally on "kubelet.log"

```
May 19 15:31:43 tmp-node-e2e-bccd7779-ubuntu-gke-1804-1-16-v20200330 kubelet[3664]: I0519 15:31:43.959754    3664 manager.go:202] 
Machine: {Timestamp:2020-05-19 15:31:43.949491834 +0000 UTC m=+0.738760555 

NumCores:1 NumPhysicalCores:1 NumSockets:1 CpuFrequency:2200000 
MemoryCapacity:3862577152 

MemoryByType:map[] NVMInfo:{MemoryModeCapacity:0 
AppDirectModeCapacity:0 AvgPowerBudget:0} HugePages:[{PageSize:1048576 NumPages:0} 
{PageSize:2048 NumPages:0}] MachineID:90ffb4f39336812aea8a65d55c4f1057 
SystemUUID:90ffb4f3-9336-812a-ea8a-65d55c4f1057 BootID:e0b92590-99c4-4c6c-bec5-
bef02d3b066d Filesystems:[{Device:/dev/shm DeviceMajor:0 DeviceMinor:25 Capacity:1931288576 
Type:vfs Inodes:471506 HasInodes:true} {Device:/run/lock DeviceMajor:0 DeviceMinor:26 
Capacity:5242880 Type:vfs Inodes:471506 HasInodes:true} {Device:/sys/fs/cgroup DeviceMajor:0 
DeviceMinor:27 Capacity:1931288576 Type:vfs Inodes:471506 HasInodes:true} 
{Device:/run/user/1001 DeviceMajor:0 DeviceMinor:52 Capacity:386256896 Type:vfs 
Inodes:471506 HasInodes:true} {Device:tmpfs DeviceMajor:0 DeviceMinor:52 Capacity:386256896 
Type:vfs Inodes:471506 HasInodes:true} {Device:/run DeviceMajor:0 DeviceMinor:24 
Capacity:386260992 Type:vfs Inodes:471506 HasInodes:true} {Device:/dev/sda1 DeviceMajor:8 
DeviceMinor:1 Capacity:20629221376 Type:vfs Inodes:2580480 HasInodes:true}] 
DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:21474836480 Scheduler:mq-deadline}] 
NetworkDevices:[{Name:eth0 MacAddress:42:01:0a:8a:00:33 Speed:-1 Mtu:1460}] Topology:[{Id:0 
Memory:3862577152 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 
NumPages:0}] Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 
Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:57671680 
Type:Unified Level:3}]}] 

CloudProvider:GCE InstanceType:n1-standard-1 InstanceID:3309468759821796580}
```

We can see that we are running on an n1-standard-1 machine that has 1 vCPU and 3.75 GB of memory.
Which is not enough.

Right now im checking in with people at #testing-ops to see how we can specify a machine type for e2e tests because an n1-standard-1 won't do it for these tests.

**Comment by alejandrox1** [comment]
So it appears that the way to solve this is to change the machine instance type in the node config, such as in

https://github.com/kubernetes/test-infra/blob/0952907d173f7bebbf11662f4c3ef5f412bbd756/jobs/e2e_node/benchmark-config.yaml#L6

Overall, the question now is whether to 1.) move the tests to run on bigger machines, 2.) tweak the tests in some other way, 3.) remove them ?
xref: https://github.com/kubernetes/test-infra/pull/17669#issuecomment-632179553

**Comment by alejandrox1** [comment]
Tests were originally created on https://github.com/kubernetes/kubernetes/pull/65250
Which explicitly states that these benchmarks were tested n n1-standard-1 machines even though the smallest pod requires 16 cpus and 16 GiB and these resource specifications have never changed.

So i guess time to at least test the benchmarks with less resources and see what happens.

**Comment by MHBauer** [comment]
I https://github.com/kubernetes/kubernetes/pull/65250 saying `n1-standard-16`

I wonder how much these tests are superseeded by all of https://github.com/kubernetes/perf-tests

https://www.nas.nasa.gov/publications/npb_problem_sizes.html

npb IS Integer-Sort Class-D is sorting 2^31 values, so 8g to 16g memory for values alone if all in memory.

npb EP is generating 2^36 pairs of values and operating on them 10 at a time, so it shouldn't require much memory at all, just lots of cores to throw at the problem.

Maybe we can add comments to the tests?

**Comment by MHBauer** [comment]
Ran the npb tests on an 8 core 64g memory virtual instance:
 - npb IS Integer-Sort Class-D requires 32GB of memory to complete, and runs for ~6minutes
 - npb EP requires ~10MB to complete, but takes around 10minutes

**Comment by alejandrox1** [comment]
> I wonder how much these tests are superseeded by all of https://github.com/kubernetes/perf-tests

We should definitely sync with sig scalability (the perf tests are owned by them).
I don't know if those tests supersede node performance tests and I also don't know if there is a sub-group within sig node that focuses on node performance so this may be an area to improve.
Using that comment as a Segway to the next comment

> Maybe we can add comments to the tests?

YES!

---

For sake of simplicity I've been looking at the n1 machines.
an n1-standard-16 has enough vCPU and memory to fit the workloads as is.
I ran the tests in an n1-standard-8 but some non-trivial amount of work needs to be done to make the tests run in anything smaller.

**Comment by alejandrox1** [comment]
For future reference, the tests running in this job were labeled as flaky here https://github.com/kubernetes/kubernetes/pull/78548

**Comment by MHBauer** [comment]
With #17687 in, it looks like they're running somewhat, but testgrid isn't parsing it right.

**Comment by alejandrox1** [comment]
yeah...
as per the issue, the problem code is https://github.com/kubernetes/kubernetes/blob/3918393e04324f709832c52ef86cab3ea8e76cd1/test/e2e_node/util.go#L176

but no great insight as to why it is failing.
I was running the tests myself and it worked but now replicating manually seems to fail in the same manner...

**Comment by alejandrox1** [comment]
Found some interesting looking logs in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/1270863727700217856/artifacts/n1-standard-16-cos-81-12871-119-0-6ef435af-system.log
```
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: I0611 00:04:20.208941    9134 cpu_manager.go:184] [cpumanager] starting with none policy
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: I0611 00:04:20.208952    9134 cpu_manager.go:185] [cpumanager] reconciling every 10s
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: I0611 00:04:20.208967    9134 state_mem.go:36] [cpumanager] initializing new in-memory state store
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: E0611 00:04:20.209168    9134 cpu_manager.go:194] [cpumanager] could not initialize checkpoint manager: could not restore state from checkpoint: configured policy "none" differs from state checkpoint policy "static", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet, please drain node and remove policy state file
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: F0611 00:04:20.209186    9134 kubelet.go:1313] Failed to start ContainerManager start cpu manager error: could not restore state from checkpoint: configured policy "none" differs from state checkpoint policy "static", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: goroutine 455 [running]:
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc0008b62c0, 0x15b, 0x28f)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb8
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x7504f40, 0xc000000003, 0x0, 0x0, 0xc0002b69a0, 0x7385988, 0xa, 0x521, 0x0)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x19d
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x7504f40, 0x3, 0x0, 0x0, 0x46b45f8, 0x23, 0xc000675c20, 0x1, 0x1)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1448
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc000ac0000)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1313 +0x3e4
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: sync.(*Once).doSlow(0xc000ac07f0, 0xc000c93dc0)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/usr/local/go/src/sync/once.go:66 +0xe3
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: sync.(*Once).Do(...)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/usr/local/go/src/sync/once.go:57
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0xc000ac0000)
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2133 +0x5b1
Jun 11 00:04:20 n1-standard-16-cos-81-12871-119-0-6ef435af kubelet[9134]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00101bc10)
```

**Comment by alejandrox1** [comment]
Checking up on this again, wanted to give the job more time to run at at least now it is flaky.
The thing that is going on is definitely related to the cpu manager
```
Jun 15 22:58:40 n1-standard-16-cos-81-12871-119-0-7eca5f16 kubelet[6223]: F0615 22:58:40.444218    6223 kubelet.go:1315] Failed to start ContainerManager start cpu manager error: could not restore state from checkpoint: configured policy "none" differs from state checkpoint policy "static", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet
```

That bit has been continuously showing up in all the system logs.
The cool thing is that the workloads being tested do delete the checkpoint file.
see
* https://github.com/kubernetes/kubernetes/blob/3918393e04324f709832c52ef86cab3ea8e76cd1/test/e2e_node/perf/workloads/npb_ep.go#L104
* https://github.com/kubernetes/kubernetes/blob/a8e43038a430aad2878cdfff17a5702dbcec1b73/test/e2e_node/perf/workloads/tf_wide_deep.go#L96

so right after the workload completes, the `PostExec` function is executed and then the kubelet config is reset and it seems that in beteen those 2 steps the checkpoint file maybe regenerated?
Gonna check up on that next.

**Comment by alejandrox1** [comment]
Also, for future reference: been debugging these test with this command
```
time make test-e2e-node FOCUS="\[Flaky\]" SKIP="" PARALLELISM=1 REMOTE=true DELETE_INSTANCES=true IMAGE_CONFIG_FILE=perf-image-config.yaml TEST_ARGS='--feature-gates=DynamicKubeletConfig=true --server-start-timeout=160s'
```

**Comment by alejandrox1** [comment]
Think I found something.
there clearly is an error with the checkpoint file for the cpu manager state.
While browsing through the logs i noticed these bits...

```
Jun 16 13:58:55.193: INFO: Pod "npb-ep-pod": Phase="Running", Reason="", readiness=true. Elapsed: 5m22.401832366s
Jun 16 13:58:57.195: INFO: Pod "npb-ep-pod": Phase="Succeeded", Reason="", readiness=false. Elapsed: 5m24.403896069s
Jun 16 13:58:57.195: INFO: Pod "npb-ep-pod" satisfied condition "Succeeded or Failed"
Jun 16 13:58:57.211: INFO: Time to complete workload npb-ep: 5m23.1s
Jun 16 13:58:57.215: INFO: Waiting for pod npb-ep-pod to disappear
Jun 16 13:58:57.216: INFO: Pod npb-ep-pod no longer exists
STEP: running the post test exec from the workload
STEP: postexec ran
```
I added some extra "STEP"s but essentially npb ep runs, pod is deleted (as per the e2e test), then the checkpoint file is removed in a postexec hook.
Notice the timestamp: 13:58:57

Then I was looking for any interesting CPU manager logs in the kubelet logs and saw this
```
Jun 16 13:58:59 n1-standard-16-cos-81-12871-119-0-ed26d118 kubelet[7462]: E0616 13:58:59.497161    7462 cpu_manager.go:342] [cpumanager] removeStaleState: removing (pod e7441b8f-7f3f-44c6-a854-          d46e2ed246df, container: npb-ep-ctn)
Jun 16 13:58:59 n1-standard-16-cos-81-12871-119-0-ed26d118 kubelet[7462]: I0616 13:58:59.497203    7462 policy_static.go:248] [cpumanager] static policy: RemoveContainer (pod: e7441b8f-7f3f-44c6-a854-   d46e2ed246df, container: npb-ep-ctn)
Jun 16 13:58:59 n1-standard-16-cos-81-12871-119-0-ed26d118 kubelet[7462]: I0616 13:58:59.497220    7462 state_mem.go:107] [cpumanager] deleted cpuset assignment (pod: e7441b8f-7f3f-44c6-a854-            d46e2ed246df, container: npb-ep-ctn)
Jun 16 13:58:59 n1-standard-16-cos-81-12871-119-0-ed26d118 kubelet[7462]: I0616 13:58:59.501243    7462 state_mem.go:88] [cpumanager] updated default cpuset: "0-15"
```

From the CPU manager perspective, the npb-ep pod is delete at around 13:58:59 (barely 1 or 2 seconds after the test).
And the logs indicate that the checkpoint file might have been updated (updated default cpuset: "0-15").

**Comment by alejandrox1** [comment]
Added some extra logging during the test and the checkpoint file is indeed being updated with the following
```
{"policyName":"static","defaultCpuSet":"0-15","checksum":4220024897}
```

**Comment by alejandrox1** [comment]
Well, we are improving little by little https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-flaky
Since #92234 merged we have had more green runs.
Sometimes the e2e tests here fail on the ubuntu image but the tests have been consistently passing on COS.

**Comment by alejandrox1** [comment]
New kind of flake has been showing up, e.g., https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/1273938706700439557
```
I0619 11:42:03.715] [sig-node] Node Performance Testing [Serial] [Slow] [Flaky] Run node performance testing with pre-defined workloads 
I0619 11:42:03.716]   NAS parallel benchmark (NPB) suite - Integer Sort (IS) workload
I0619 11:42:03.716]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:118
I0619 11:42:03.716] [BeforeEach] [sig-node] Node Performance Testing [Serial] [Slow] [Flaky]
I0619 11:42:03.716]   /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:174
I0619 11:42:03.717] STEP: Creating a kubernetes client
I0619 11:42:03.717] STEP: Building a namespace api object, basename node-performance-testing
I0619 11:42:03.717] Jun 19 11:40:51.597: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
I0619 11:42:03.717] Jun 19 11:40:51.597: INFO: Skipping waiting for service account
I0619 11:42:03.717] [BeforeEach] Run node performance testing with pre-defined workloads
I0619 11:42:03.718]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:115
I0619 11:42:03.718] [JustBeforeEach] [sig-node] Node Performance Testing [Serial] [Slow] [Flaky]
I0619 11:42:03.718]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:68
I0619 11:42:03.718] I0619 11:40:51.617838    3590 util.go:223] new configuration has taken effect
I0619 11:42:03.718] [It] NAS parallel benchmark (NPB) suite - Integer Sort (IS) workload
I0619 11:42:03.718]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:118
I0619 11:42:03.719] STEP: running the workload and waiting for success
I0619 11:42:03.719] Jun 19 11:40:53.637: FAIL: Failed to delete pod "npb-is-pod": Delete http://127.0.0.1:8080/api/v1/namespaces/node-performance-testing-7142/pods/npb-is-pod: dial tcp 127.0.0.1:8080: connect: connection refused
I0619 11:42:03.719] 
I0619 11:42:03.719] Full Stack Trace
I0619 11:42:03.720] k8s.io/kubernetes/test/e2e/framework.(*PodClient).DeleteSync(0xc000902260, 0xc000f06d30, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc0008d8310, 0x0, 0x0, ...)
I0619 11:42:03.720] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:155 +0x415
I0619 11:42:03.720] k8s.io/kubernetes/test/e2e_node.glob..func33.2()
I0619 11:42:03.720] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:83 +0x11c
I0619 11:42:03.720] panic(0x45ef260, 0x5f7b510)
I0619 11:42:03.720] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
I0619 11:42:03.721] k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc000a58080, 0x60c47c0, 0x8f28278, 0x0, 0x0, 0x0, 0x0, 0xc000a58080)
I0619 11:42:03.721] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:75 +0x1f0
I0619 11:42:03.721] k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).NotTo(0xc000a58080, 0x60c47c0, 0x8f28278, 0x0, 0x0, 0x0, 0xc000f08000)
I0619 11:42:03.722] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:48 +0xc7
I0619 11:42:03.722] k8s.io/kubernetes/test/e2e/framework.ExpectNoErrorWithOffset(0x1, 0x6051aa0, 0xc000f08000, 0x0, 0x0, 0x0)
I0619 11:42:03.722] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/expect.go:46 +0xf5
I0619 11:42:03.722] k8s.io/kubernetes/test/e2e/framework.ExpectNoError(...)
I0619 11:42:03.722] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/expect.go:40
I0619 11:42:03.723] k8s.io/kubernetes/test/e2e/framework.(*PodClient).CreateSync(0xc00064d500, 0xc0012f7c00, 0xc0012f7c00)
I0619 11:42:03.723] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:103 +0xfe
I0619 11:42:03.723] k8s.io/kubernetes/test/e2e_node.glob..func33.3()
I0619 11:42:03.723] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:104 +0xe6
I0619 11:42:03.723] k8s.io/kubernetes/test/e2e_node.glob..func33.4.2()
I0619 11:42:03.724] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_perf_test.go:120 +0x53
I0619 11:42:03.724] k8s.io/kubernetes/test/e2e_node.TestE2eNode(0xc000bec000)
I0619 11:42:03.724] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:170 +0x4c5
I0619 11:42:03.724] testing.tRunner(0xc000bec000, 0x54d1458)
I0619 11:42:03.724] 	/usr/local/go/src/testing/testing.go:909 +0xc9
I0619 11:42:03.725] created by testing.(*T).Run
I0619 11:42:03.725] 	/usr/local/go/src/testing/testing.go:960 +0x350
I0619 11:42:03.725] [AfterEach] [sig-node] Node Performance Testing [Serial] [Slow] [Flaky]
I0619 11:42:03.725]   /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:175
```

**Comment by alejandrox1** [comment]
Closing this. The job is now being executed properly and in descent shape.
It is still flaky but will open up another issue to work on that.
/close
