### ISSUE TITLE
Error while creating 2 containers in a single pod.

### ISSUE THREAD

**Issue by 7tabish** [kubernetes/kubernetes#91279]
I am trying to create a multi container pod but every time when i create pod the first container go in running state and second container always give me error. I am using simple nodejs docker image which return a message from get endpoint.
**Dockerfile**
FROM node:alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "node", "app.js" ]

**Pod.yaml**
apiVersion: v1
kind: Pod
metadata:
  name: node-demo2
  labels:
    app: web
spec:
  containers:
    - name: mycontainer2
      image: tabishmanzoor/nodejs-sample1:1.0
      ports:
        - containerPort: 4100
    - name: mycontainer3
      image: tabishmanzoor/nodejs-sample1:1.0
      ports:
        - containerPort: 4000

**Comment by liggitt** [comment]
Containers in a pod share a network address. If both containers are binding to the same address/port, only one of them will succeed. You need to provide a way to adjust the port the container binds to, then configure unique ports in the container args or env in the pod spec.
