### ISSUE TITLE
pause rolling update of the deployment after user specified pod updated

### ISSUE THREAD

**Issue by xiegang1** [kubernetes/kubernetes#91276]
**What would you like to be added**:
When rolling update the deployment, we want pause the deployment after specified number of pods are updated, then we could check those pods. and then continue some other and check again. This requires deployment support the pause and resume according to the number specified by user. 

**Why is this needed**:
current pause mechanism could not pause rolling update pods specified by user.  Think about the usual case, we have 50 pods, when usually update 1 or 2 at first before rolling update. Current strategy doesn't support this. Using 2 deployments to do the canary is another story, we just want to use the deployment simply.

**Comment by zjj2wry** [comment]
Now deployment does not support this feature, maybe you can refer to this document to achieve the purpose.

https://github.com/ContainerSolutions/k8s-deployment-strategies/tree/master/canary/native
