### ISSUE TITLE
Make DNS required?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9127]
I think we should just make DNS a required component and upgrade it as part of all the standard upgrade processes (e.g. kube-push).

@erictune @satnam6502 @vishh 

We might be able to push this beyond 1.0 but it's going to start hurting more and more.

**Comment by vishh** [comment]
+100. I would prefer integrating kube-dns as part of kubernetes release
bundle for 1.0.

**Comment by zmerlynn** [comment]
+1000. We have next to 0 testing with it off.

The upgrade work is in flight and isn't unique to DNS, though. #8107

**Comment by satnam6502** [comment]
+1e6 esp. for integrating kube-dns as part of kubernetes release bundle for
1.0

**Comment by bgrant0607** [comment]
See also discussion in #5284

**Comment by fgrzadkowski** [comment]
FYI There is a PR in-flight that implements first simple version of add-on upgrades - https://github.com/GoogleCloudPlatform/kubernetes/pull/9128

@marekbiskup

**Comment by zmerlynn** [comment]
I think this is a dupe of #9107.
