### ISSUE TITLE
scheduler/extender: extend the current `ExtenderFilterResult` struct to include node status

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#91281]
Updated on 13/06/2020:

- ~~[ ] update extender design proposal~~ (not possible, see https://github.com/kubernetes/community/pull/4816)
- [x] migrate it to k/enhancements https://github.com/kubernetes/enhancements/pull/1840
- [x] submit a API change PR https://github.com/kubernetes/enhancements/pull/1850
- [ ] implement it https://github.com/kubernetes/kubernetes/pull/92866

**What would you like to be added**:

I'd like to extend the current `ExtenderFilterResult` struct to include node status of the failed pod.

https://github.com/kubernetes/kubernetes/blob/9e991415386e4cf155a24b1da15becaa390438d8/staging/src/k8s.io/kube-scheduler/extender/v1/types.go#L86-L97

e.g. 

- add a new map `FailedUnresolvableNodes` to include `UnschedulableAndUnresolvable` nodes 
- or use an extensive struct to include both status and message in the node map (which supersedes current `FailedNodes` map)

**Why is this needed**:

`FailedNodes` is a map of string to string which includes failed message only.

https://github.com/kubernetes/kubernetes/blob/9e991415386e4cf155a24b1da15becaa390438d8/staging/src/k8s.io/kube-scheduler/extender/v1/types.go#L82-L83

The status of the failed node is hardcoded to `Unscheduable` here.

https://github.com/kubernetes/kubernetes/blob/9e991415386e4cf155a24b1da15becaa390438d8/pkg/scheduler/core/generic_scheduler.go#L520-L526

The extender filter can't report that failed nodes are unresolvable like built-in filters.

https://github.com/kubernetes/kubernetes/blob/7ba332a839c844ef4ba0191ddca2ce3601d283af/pkg/scheduler/core/generic_scheduler.go#L1034-L1047

**Comment by cofyc** [comment]
/sig scheduling 
What do you think?

**Comment by cofyc** [comment]
cc @resouer @Huang-Wei

**Comment by Huang-Wei** [comment]
@cofyc extenders.Filter() can set the status of failed node as `UnschedulableAndUnresolvable`, then we should be fix the logic:

https://github.com/kubernetes/kubernetes/blob/b339ed0e75c5815d49c5c4d118d4b9858b4babc4/pkg/scheduler/core/generic_scheduler.go#L509-L515

to respect the `UnschedulableAndUnresolvable` status returned by extenders.Filter().

**Comment by cofyc** [comment]
yes, when `extenders.Filter()` can return the status of the node, we must update this logic to respect the status returned by the extender.

**Comment by cofyc** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by Huang-Wei** [comment]
One thing I’m thinking about is: if we can keep current failedNodeMap struct, say still use string as the value, but set an implicit contract with extenders, and then parse the returned error string to a particular type.

If we introduce Status as the the value, extender has to depends on k/k, that sort of violates the intention to move out extender API.

**Comment by cofyc** [comment]
Add an implicit contract with extenders may change the meaning of the failed msg. How about adding a new field?

The new field can be a map to supersede `FailedNodes`. I agree we should not depend on internal status constants in the framework, we can use string as the status value, e.g. `Unschedulable`, `UnschedulableAndUnresolvable`.

Or the new field can be a map which includes `UnschedulableAndUnresolvable` nodes only, e.g.

```
type ExtenderFilterResult struct { 
    // ...
 	// Filtered out nodes where the pod can't be scheduled and the failure messages 
 	FailedNodes FailedNodesMap 
 	// Filtered out nodes where the pod can't be scheduled and the failure messages. Failed nodes put in this map are unresolvable and will be skipped in preemption phase.
 	FailedAndUnresolvableNodes FailedNodesMap 
 } 
```

**Comment by Huang-Wei** [comment]
To sum up, there are several options:

- **Option 1:** keep `FailedNodesMap map[string]string` as is. In the scheduler core, add additional logic to check whether the return error reason contains (or starts with, well it's an implicit contract) keyword "UnschedulableAndUnresolvable", if so, set the status to `UnschedulableAndUnresolvable`; otherwise, set it to `Unschedulable` as before. In this way, we don't need to update the extender v1 API, and also user's extenders won't be impacted.
- **Option 2:** replace `FailedNodesMap map[string]string` with `FailedNodesMap map[string]framework.Status`. This adds an extra deps to k/k, which may violate our intention of moving extender API to staging. To make the API backwards compatible, we may need extra decoding logic to ensure both plain string (old version) and framework.Status get decoded properly.
- **Option 3:** adds `FailedAndUnresolvableNodes map[string]string`. As this adds a new field, so it's API backwards compatible naturally.

On the other hand, the staging extender v1 isn't really a standard k8s version - it's just a JSON format contract negotiated with the users. We can only support one version due to missing of GVK, unless there are multiple endpoints served (which is almost impossible).

**Comment by cofyc** [comment]
I guess 2) is not possible because it adds an extra deps to `k/k` as you said. I'm ok with option 1) and 3).

@resouer @ahg-g @alculquicondor what do you think?

If you agree, I can send a PR to implement it. This gives extender the ability to mark nodes unscheduable and unresolvable then nodes can be skipped in the preempt phase.

**Comment by Huang-Wei** [comment]
> If you agree, I can send a PR to implement it.

Thanks @cofyc. Just a reminder, for option 3, we may need to update (or migrate) existing extender KEP as it involves API changes.

**Comment by ahg-g** [comment]
I think option 3 is the one we should go with. Option 1 in my opinion shouldn't be considered at all, while option 2 breaks backward compatibility.

**Comment by cofyc** [comment]
Thanks!

Current extender [design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md) doesn't document `preempt` verb (maybe documented in another place?). I'll update it first, then submit an API change proposal. 

We can migrate the doc to `k/enhancements` after it's done.

**Comment by alculquicondor** [comment]
beware of #88634

I think we should adhere to API versioning (and release v2) before adding more fields. Unless this is urgent.

**Comment by ahg-g** [comment]
> I think we should adhere to API versioning (and release v2) before adding more fields. Unless this is urgent.

Certainly addressing  #88634 is important, but I think they can move in parallel as long as we treat it as a versioned API.
