### ISSUE TITLE
[Flaky Test] node-kubelet-master (ci-kubernetes-node-kubelet)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#91292]
**Which jobs are failing**:
> node-kubelet-master (ci-kubernetes-node-kubelet)

**Which test(s) are failing**:
> Node Tests
> Overall

**Since when has it been failing**:
> 05-20 23:08 PDT

**Testgrid link**:
> https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master

**Reason for failure**:

>Timed out after 60.000s.
Expected
    <string>: Summary
to match fields: {
[.Pods:
	missing expected element summary-test-2812::stats-busybox-0, .Pods:
	missing expected element summary-test-2812::stats-busybox-1]
}
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:337

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by hasheddan** [comment]
This was merged around the same time failures started: https://github.com/kubernetes/kubernetes/pull/89667

@kmala any idea of if this could be affecting the test here?

**Comment by hasheddan** [comment]
@MHBauer made the astute observation that there are two new `[k8s.io] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api` tests present here. Looks like related to changes in `test-infra`

**Comment by MHBauer** [comment]
last build before failure was https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1262973166725107714
first build with failure was https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1262988516996943872

went from one node on a ubuntu-gke-1804 image
to 3 nodes, ubuntu-gke-1804, cos-73, cos-77

329 tests -> 971 tests

doesn't seem to consistently fail on one specific image type.

**Comment by MHBauer** [comment]
So it looks like it's supposed to be running on 3 nodes

job config
https://github.com/kubernetes/test-infra/blob/8547d0b27801b1d6032721faa3d1e3a4bfe723c6/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L27
to
https://github.com/kubernetes/test-infra/blame/master/jobs/e2e_node/image-config.yaml
with the last change, yes, being the swap out of images, https://github.com/kubernetes/test-infra/commit/44ffc6959370a2da61aee0d9d65336cce6783344

so, was it **_silently failing_** until the images were swapped? Is there some other config that was changed I'm not seeing?

Would rolling forward the cos images fix it? 

My biggest concern is the silent non-failure.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/17617 is the PR that changed node image config and yes it landed last night right before node-e2e started failing

>so, was it **silently failing** until the images were swapped?

Yeah that concerns me too, and unfortunately I think you're right.  I'm trying to determine if this means we've had no COS coverage for a while.

I can see my PR to roll ubuntu forward (https://github.com/kubernetes/test-infra/pull/17255) had an effect when it landed on 2020-04-24
```
gs://kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1253770450945708033/artifacts/tmp-node-e2e-957c620f-ubuntu-gke-1804-d1703-0-v20181113/
gs://kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1253785801825718274/artifacts/tmp-node-e2e-9808547f-ubuntu-gke-1804-1-16-v20200330/
```

I'm checking to see if my attempt to roll COS forward (https://github.com/kubernetes/test-infra/pull/17245) had any effect (at least on this silent failure problem) when it landed 2020-04-16

**Comment by spiffxp** [comment]
OK, this is the first run after the long window of failures we experienced in April: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1250899833967874050
```
gs://kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1250899833967874050/artifacts/tmp-node-e2e-8f855484-cos-stable-60-9592-84-0/
gs://kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1250899833967874050/artifacts/tmp-node-e2e-8f855484-cos-stable-63-10032-71-0/
gs://kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1250899833967874050/artifacts/tmp-node-e2e-8f855484-ubuntu-gke-1804-d1703-0-v20181113/
```

This proceeds for a few runs

The last of these is at `2020-04-17 00:35:32 +0000 UTC`: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1250945887434182657

https://github.com/kubernetes/test-infra/pull/17245 landed at roughly 2020-04-17 01:19

The next run at `2020-04-17 01:36:39 +0000 UTC` only has ubuntu artifacts: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1250961239010447361

Hooray, our lack of COS coverage from 2020-04-16 to 2020-05-19 was my fault

**Comment by MHBauer** [comment]
Seems to only fail in the cos-73 image, so rotating the images forward is the solution.

**Comment by MHBauer** [comment]
It'd be good to get a run with FOCUS="should report resource usage through the stats api" to get rid of all the logs that aren't relevant.

**Comment by Huang-Wei** [comment]
It's still failing https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90415/pull-kubernetes-node-e2e/1263189845191168000/

**Comment by vpickard** [comment]
I did a run on my gcp, and I see these additional details....

   Timed out after 60.002s.
    Expected                                                                                                                                                                         
        <string>: Summary                                                                                                                                                            
    to match fields: {                                                                                                                                                               
    .Node.Runtime:                                                                                                                                                                   
        Expected                                                                                                                                                                     
            <string>: RuntimeStats                                                                                                                                                   
        to match fields: {                                                                                                                                                           
        .ImageFs:                                                                                                                                                                    
                Expected                                                                                                                                                             
                    <string>: FsStats                                                                                                                                                
                to match fields: {                                                                                                                                                   
                .AvailableBytes:                                                                                                                                                     
                        Expected                                                                                                                                                     
                            <uint64>: 0                                                                                                                                              
                        to be >=                                                                                                                                                     
                            <int64>: 100000000                                                                                                                                       
                .CapacityBytes:                                                                                                                                                      
                        Expected                                                                                                                                                     
                            <uint64>: 0                                                                                                                                              
                        to be >=                                                                                                                                                     
                            <int64>: 100000000                                                                                                                                       
                .InodesFree:                                                                                                                                                         
                        Expected                                                                                                                                                     
                            <*uint64 | 0x0>: nil                                                                                                                                     
                        not to be <nil>                                                                                                                                              
                .Inodes:                                                                                                                                                             
                        Expected                                                                                                                                                     
                            <*uint64 | 0x0>: nil                                                                                                                                     
                        not to be <nil>                                                                                                                                              
                .InodesUsed:                                                                                                                                                         
                        Expected                                                                                                                                                     
                            <*uint64 | 0x0>: nil                                                                                                                                     
                        not to be <nil>                                                                                                                                              
                }                                                                                                                                                                    
                                                                                                                                                                                     
        }                                                                                                                                                                            
                                                                                                                                                                                     
    [.Pods[summary-test-500::stats-busybox-1].Containers[busybox-container].Rootfs:                                                                                                  
        Expected                                                                                                                                                                     
            <string>: FsStats                                                                                                                                                        
        to match fields: {                                                                                                                                                           
        .AvailableBytes:                                                                                                                                                             
                Expected                                                                                                                                                             
                    <uint64>: 0                                                                                                                                                      
                to be >=                                                                                                                                                             
                    <int64>: 100000000                                                                                                                                               
        .CapacityBytes:                                                                                                                                                              
                Expected                                                                                                                                                             
                    <uint64>: 0                                                                                                                                                      
                to be >=                                                                                                                                                             
                    <int64>: 100000000                                                                                                                                               
        .InodesFree:                                                                                                                                                                 
                Expected                                                                                                                                                             
                    <*uint64 | 0x0>: nil                                                                                                                                             
                not to be <nil>                                                                                                                                                      
        .Inodes:                                                                                                                                                                     
                Expected                                                                                                                                                             
                    <*uint64 | 0x0>: nil                                                                                                                                             
                not to be <nil>                                                                                                                                                      
        }                                                                                                                                                                            
        , .Pods[summary-test-500::stats-busybox-0].Containers[busybox-container].Rootfs:                                                                                             
        Expected                                                                                                                                                                     
            <string>: FsStats                                                                                                                                                        
        to match fields: {                                                                                                                                                           
        .AvailableBytes:                                                                                                                                                             
                Expected                                                                                                                                                             
                    <uint64>: 0                                                                                                                                                      
                to be >=                                                                                                                                                             
                    <int64>: 100000000                                                                                                                                               
        .CapacityBytes:                                                                                                                                                              
                Expected                                                                                                                                                             
                    <uint64>: 0                                                                                                                                                      
                to be >=                                                                                                                                                             
                    <int64>: 100000000                                                                                                                                               
        .InodesFree:                                                                                                                                                                 
                Expected                                                                                                                                                             
                    <*uint64 | 0x0>: nil                                                                                                                                             
                not to be <nil>                                                                                                                                                      
        .Inodes:                                                                                                                                                                     
                Expected                                                                                                                                                             
                    <*uint64 | 0x0>: nil                                                                                                                                             
                not to be <nil>                                                                                                                                                      
        }                                                                                                                                                                            
        ]                                                                                                                                                                            
    }

**Comment by spiffxp** [comment]
I just realized we're cause the node e2e presubmit to fail as well, which is blocking all merges https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e

I've opened https://github.com/kubernetes/test-infra/pull/17660 to revert https://github.com/kubernetes/test-infra/pull/17617

This gets us back to green, but also to the place where only ubuntu images are running.

**Comment by MHBauer** [comment]
As an FYI, here is a link to the test code:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/summary_test.go#L337

**Comment by dims** [comment]
Just caught up here. Nice work you all :)

**Comment by MHBauer** [comment]
root cause-ish seems to be that the config https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config.yaml uses `image_regex:` which silently skips here.

This was as far back as I could find, and I'm not sure why it was used.
https://github.com/kubernetes/test-infra/pull/4338/files#diff-cd0cab798784c2641e09aaf30a024a93R4-R22

When https://github.com/kubernetes/test-infra/pull/17617 was made to fix ci-kubernetes-node-kubelet-conformance,  that’s https://github.com/kubernetes/test-infra/blob/3ff387b699fc0405bcd455099ddb414ad10b7fa5/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L115 which uses https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/benchmark-config.yaml which is all `image:` strict matching, which surfaced as an explicit failure.

**Comment by MHBauer** [comment]
And comparing uses of `image:` to `image_regex:` 
```
➜  test-infra git:(master) rg 'image_regex:' -t yaml | wc -l
      10
➜  test-infra git:(master) rg 'image:' -t yaml | wc -l
    1658
```
This seems to be a footgun.

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e presubmits are up and running again, I'm fine with whatever fix-forward PR folks would like to move with

**Comment by MHBauer** [comment]
https://kubernetes.slack.com/archives/C0BP8PW9G/p1589987979392300 some triage notes.

**Comment by bsdnet** [comment]
> And comparing uses of `image:` to `image_regex:`
> 
> ```
> ➜  test-infra git:(master) rg 'image_regex:' -t yaml | wc -l
>       10
> ➜  test-infra git:(master) rg 'image:' -t yaml | wc -l
>     1658
> ```
> 
> This seems to be a footgun.

Looks all the places are image name, instead of regex. image_regex is introduced by 2f6514bd63f2590f37cc3a456a5dd78d228c296f, but rarely be used,

**Comment by hasheddan** [comment]
/retitle [Flaky Test] node-kubelet-master (ci-kubernetes-node-kubelet)

/remove-kind failing-test
/kind flake

**Comment by hasheddan** [comment]
@MHBauer @vpickard Seeing some pretty regular timeout here now, any insight?
