### ISSUE TITLE
Possible performance regression landed within the last 24 hours

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#91316]
**What happened**:
It's most visible in the test `[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container`

<img width="323" alt="Screen Shot 2020-05-20 at 6 09 10 PM" src="https://user-images.githubusercontent.com/49258/82512466-0f0d8300-9ac5-11ea-8396-94ce8cf25a61.png">

It shows up in kind, kube-up.sh and kops jobs
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=10&graph-metrics=test-duration-minutes&include-filter-by-regex=Pod%20Container%20Status%20should%20never%20report%20success
- https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel&width=10&graph-metrics=test-duration-minutes&include-filter-by-regex=Pod%20Container%20Status%20should%20never%20report%20success
- https://testgrid.k8s.io/google-aws#kops-aws-k8s-latest&graph-metrics=test-duration-minutes&width=5

The regression was introduced somewhere within https://github.com/kubernetes/kubernetes/compare/cf13f8d99...7ba332a83, possible culprits are:
- https://github.com/kubernetes/kubernetes/pull/89667 (FYI @dashpole @kmala)
- https://github.com/kubernetes/kubernetes/pull/90825 (FYI @dopelsunce @caesarxuchao)
- https://github.com/kubernetes/kubernetes/pull/91258  (FYI @ahg-g @alculquicondor)

There are more tests affected, just not as prominently (visually inspecting https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=10&graph-metrics=test-duration-minutes)
- [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications with PVCs
- [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]
- [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Inline-volume (default fs)] volumes should store data
- [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Pre-provisioned PV (default fs)] volumes should store data

I wasn't sure whether to tag this as kind/regression or not, I'll leave that up to @liggitt or someone

/sig node
/sig api-machimery
/sig scheduling

**Comment by kmala** [comment]
#89667 will increase the time for deletion of pod and it should be expected because currently pod is deleted from apiserver before removing the sandbox container but after this fix pod will be deleted from the apiserver only after deleting the sandbox container.

**Comment by alculquicondor** [comment]
/remove-sig scheduling

#91258 doesn't affect scheduling running time at all.

**Comment by dashpole** [comment]
Yeah, #89667 is almost definitely the culprit.  Last time we changed that code path, it also caused a regression.  The degradation in performance is expected, but a 5x slowdown is definitely larger than it should be.

**Comment by liggitt** [comment]
do we know if that's because the status used by the `syncPod -> canBeDeleted` path is stale, or if removing sandboxes is actually that slow?

**Comment by liggitt** [comment]
if there's not a quick fix, should we revert https://github.com/kubernetes/kubernetes/pull/89667 and bring it back in once the root issue is understood?

**Comment by dashpole** [comment]
I think a revert is appropriate in this case.

**Comment by liggitt** [comment]
ok, I'll open it

**Comment by liggitt** [comment]
open at https://github.com/kubernetes/kubernetes/pull/91337

**Comment by kmala** [comment]
I agree with @dashpole that 5x is something which shouldn't happen and i can take a look on why thats happening and that might require changing the way how the sandbox is currently deleted which is on during GC.
