### ISSUE TITLE
Add unit test coverage for `pkg/kubelet/types/pod_update.go`

### ISSUE THREAD

**Issue by mattjmcnaughton** [kubernetes/kubernetes#91313]
**What would you like to be added**:
Currently, in `pkg/kubelet/types/pod_update.go` the following public methods do not have unit test coverage:
- `IsMirrorPod`
- `IsStaticPod`
- `IsCriticalPod`
- `Preemptable`

These methods are great candidates for adding unit test coverage.

**Why is this needed**:
Adding unit test coverage will both ensure they are working correctly and (more importantly), encode their expected behavior in the test suite. Additionally, if we want to change their behavior in the future, it'll be helpful to already have the test suites.

**Extra note**
I think this could be a great candidate for someone who is new to contributing to sig-node/k8s. I'm happy to mentor any first time contributors :) Please respond saying you'd like to work on this issue and I'll assign it to you. Please reach out to me on k8s slack (where I'm also @mattjmcnaughton) if I can be of any assistance.

**Comment by knabben** [comment]
Hi, @mattjmcnaughton I would like to work in one of these.

**Comment by mattjmcnaughton** [comment]
/assign @knabben 

Awesome!

**Comment by abhi1604** [comment]
Hi, I am a first time contributor and would be happy to contribute to one of these. @mattjmcnaughton

**Comment by benzispawn** [comment]
Hi, I want to help if still need it.
