### ISSUE TITLE
Hide IaaS-specific DNS search paths

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9132]
On a GCE VM (created by GKE):

```
$ cat resolve.conf
domain c.some-project-123.internal.
search c.some-project-123.internal. 987654321.google.internal. google.internal.
nameserver 169.254.169.254
nameserver 10.240.0.1
```

Kubernetes will append:
`$NAMESPACE.svc.$CLUSTER_SUFFIX svc.$CLUSTER_SUFFIX $CLUSTER_SUFFIX`
to the search line where `$CLUSTER_SUFFIX` defaults to `cluster.local`, but cluster admins can redefine.

Pods which depend on resolving these special dns names will not be portable to other cloud providers, or potentially even across projects/clusters/zones within the same cloud provider.  We should strive to avoid things which reduce portability of pods.   
- Exposing the project name and other details about the underlying node goes against the kubernetes philosophy of abstracting the hardware from the application. 
- Encourages addressing nodes directly (e.g. foo.c.some-project-123.google.internal) rather than using pods and services, which undermines kubernetes networking abstractions.
- It limits the flexibility of the cluster admin to chose which nodes comprise a cluster.
- Enterprises may want to ensure that they keep their pods portable for various reasons.  Hiding nonportable APIs like this is one way to do that.  

Suggest that
- kubelet has a flag that causes it to pass a certain resolve.conf to docker when creating a pod..
- kubelet setup has per-cloud-provider algorithm for filtering non-essential info from the node's resolve.conf.
- If anyone asks for it, provide an escape hatch, e.g. `hostResolveConf` option on Pod Spec, default false.  Not clear this is needed.  Pods that want to talk to the metadata server can just skip DNS and use its IP address.

Suggest filtering as follows on GCE:
- remove `domain` since it mentions project (and does nothing when search is specified)
- remove `c.some-project-123.internal. 987654321.google.internal. google.internal` from the search path.  
- remove `nameserver 169.254.169.254`, which is just used for GCE metadata requests.

Related:
- conserve limited search and nameserver entries (#9079)
- hide metadata from pods, which contains secret information (#8867)

**Comment by erictune** [comment]
@thockin @roberthbailey

**Comment by erictune** [comment]
@bgrant0607

**Comment by erictune** [comment]
Probably not practical for v1, but try to do soon after if possible.

**Comment by erictune** [comment]
@smarterclayton what of the resolve.conf do you expose in openshift?

**Comment by smarterclayton** [comment]
Right now our installation docs are going to say to add our master (which has SkyDNS integrated, vs running in a pod) to the nodes' resolv.conf, then pass that in.  So the node and container would have the same resolv.conf by default today which I believe is the Docker default value.  I think we'd want to hide the same sorts of things on GCE and AWS that you describe above.  @ncdc fyi

**Comment by bgrant0607** [comment]
I agree we should block things like http://metadata #8867. Not resolving VM hostnames seems reasonable, also.

**Comment by thockin** [comment]
This really means going all-in on things like external services.  Any
non-kubernetes IP endpoint must be "imported" into kubernetes' scope to
give it a name.  I guess I can live with that, but it is a bit tedious.

Are there any other ramifications of locking down in this way?

I just ran some tests and it seems that SkyDNS is perhaps automatically
forwarding lookups, so things like metadata.google.internal resolve, even
if I take the GCE DNS out of the container.

**Comment by bgrant0607** [comment]
I think we should allow access to external services, such as storage APIs.

**Comment by thockin** [comment]
I think it's either

a) inherit everything
b) inherit nothing
c) inherit nothing, provide sufficient flags for admin to do what they want

I'm not keen on trying to enumerate things we block and things we don't

**Comment by smarterclayton** [comment]
> On Jun 3, 2015, at 12:24 AM, Tim Hockin <notifications@github.com> wrote:
> 
> This really means going all-in on things like external services. Any
> non-kubernetes IP endpoint must be "imported" into kubernetes' scope to
> give it a name. I guess I can live with that, but it is a bit tedious.
> 
> Are there any other ramifications of locking down in this way?
> 
> I just ran some tests and it seems that SkyDNS is perhaps automatically
> forwarding lookups, so things like metadata.google.internal resolve, even
> if I take the GCE DNS out of the container.

Open forwarders are problematic - we've been asked repeatedly to disable it in customer environments, so we just started disabling forwarding in skydns and using SERVFAIL sent by skydns to fall to the next nameserver.

**Comment by erictune** [comment]
@thockin
I didn't think that accessing storage APIs, such as GCS, requires use of `.internal` names, right?  So I don't think @bgrant0607 are in disagreement?

**Comment by thockin** [comment]
If we disable forwarding entirely then we MUST pass a "real" nameserver to
all containers, which means yet another flag for cluster admins to get
right.

**Comment by bgrant0607** [comment]
@erictune I believe we are in agreement. We just need to solve the "real nameserver" problem to retain access to external services.

**Comment by porridge** [comment]
https://github.com/kubernetes/kubernetes/issues/16307 seems to be in a conflict with this one. What's the plan for near term? (I don't know whether a removal of milestone v1.0-post means it's going to happen in 1.0 or at unspecified time?)

**Comment by roberthbailey** [comment]
It means an unspecified time.

/cc @matchstick @girishkalele

**Comment by freehan** [comment]
reopened if needed
