### ISSUE TITLE
ClusterIP UDP Port Not available on CentOS8

### ISSUE THREAD

**Issue by wk60807430** [kubernetes/kubernetes#91331]
**What happened**:
ClusterIP UDP Port Not available on CentOS8, It was available by test when use ENDPOINTS IP
For Example:

CoreDNS serveice,use UDP 53 ，DNS client available on ENDPOINTS IP:10.244.1.100,but it was not available on ClusterIP 10.0.0.2;Other UDP service test result is like this too. ClusterIP NOT OK, ENDPOINTS IP ok.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: CentOS Linux release 8.1.1911 (Core)
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Aliyun
- OS (e.g: `cat /etc/os-release`):

NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"

- Kernel (e.g. `uname -a`):  Linux talcloud-web-002 4.18.0-147.8.1.el8_1.x86_64
- Install tools: binPKG
- Network plugin and version (if this is a network-related bug): ipvs flannel:v0.11.0-amd64
- Others:
iptables v1.8.2 (nf_tables)

lsmod | grep -e ip_vs -e nf_conntrack_ipv4

nf_conntrack_ipv4      16384  10
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  40
ip_vs                 172032  46 ip_vs_rr,ip_vs_sh,ip_vs_wrr
nf_defrag_ipv6         20480  1 ip_vs
nf_conntrack          155648  8 xt_conntrack,nf_conntrack_ipv4,nf_nat,ipt_MASQUERADE,nf_nat_ipv4,xt_nat,nf_conntrack_netlink,ip_vs
libcrc32c              16384  4 nf_conntrack,nf_nat,xfs,ip_vs

**Comment by wk60807430** [comment]
/sig/network

**Comment by rikatz** [comment]
@wk60807430 You've missed the right command ;)

/sig network

**Comment by rikatz** [comment]
/triage unresolved

We will triage this later

**Comment by rikatz** [comment]
@wk60807430 can you provide further informations please, steps to reproduce what is happening? I couldn't figure out what's actually happening and how to reproduce.

Thank you

**Comment by system51** [comment]
We encountered the same problem. I used calico instead of flannel

**Comment by system51** [comment]
@rikatz I want to be the same as I encountered the problem  https://github.com/kubernetes/kubernetes/issues/91346#issue-622881454

**Comment by wk60807430** [comment]
> @wk60807430 can you provide further informations please, steps to reproduce what is happening? I couldn't figure out what's actually happening and how to reproduce.
> 
> Thank you

1 Enviroment:
![image](https://user-images.githubusercontent.com/40818413/82746724-a0327180-9dc5-11ea-99e1-72d76ec72593.png)
 uname -a
Linux talcloud-web-002 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@talcloud-web-002 ~]# cat /etc/redhat-release
CentOS Linux release 8.1.1911 (Core)

2 Run a pod with UDP service and kube-proxy service use Cluster IP:
kubectl get svc -A:
talcloud        tal-admin                   ClusterIP   10.0.0.243   <none>        8080/TCP,39999/TCP,1234/UDP
3 Emulating a udp service：
 nc -lu 1234
4 Testing on centos 7 node and centos 8 node on the same k8s cluster：
Centos7：
Testing result：UDP service passed
![image](https://user-images.githubusercontent.com/40818413/82746830-abd26800-9dc6-11ea-97b5-7fd64a3ad35f.png)
Centos8：
Testing result：UDP service connected fail
![image](https://user-images.githubusercontent.com/40818413/82746861-f81da800-9dc6-11ea-8330-5dee544370af.png)

5 Result：
When k8s cluster's node with OS CentOS8 , k8s pod UDP service is not available by useing Cluster IP, TCP service didn't have this problem

@rikatz I didn't know this message is  clear enough for you or not , pleasa leave me a message if  have any questions about this.
Thank you

**Comment by wk60807430** [comment]
> We encountered the same problem. I used calico instead of flannel

Yes,calico I used it to test this problem, it's have the same problem, i think problem may be in IPVS,bu i'm not sure about that.

**Comment by rikatz** [comment]
@wk60807430 thank you, I'll create a full CentOS 8 cluster with Calico here and kube-proxy in IPVS mode and check if I can reproduce here

**Comment by rikatz** [comment]
> > We encountered the same problem. I used calico instead of flannel
> 
> Yes,calico I used it to test this problem, it's have the same problem, i think problem may be in IPVS,bu i'm not sure about that.

Just a question, are you running Calico with VXLAN or in the default mode? Thank you

**Comment by rikatz** [comment]
@wk60807430 Need some further information:

* Is kube-proxy and flannel running as a container or as a binary inside your cluster?
* Can you please provide the output of a ``iptables -L -n -v``? Let's check if you got the same rules as me here.
* Also, ``ipvsadm -L -n`` in the source node and the destination node to check if the ipvs rules are created correctly

From my first test, when using kube-proxy and flannel as a Daemonset inside a container it seems there's an incompability, as flannel still uses the legacy iptables API while Red Hat / CentOS uses the newer iptables API (NFT).

There has been some discussion about this [here](https://github.com/kubernetes/kubernetes/issues/71305) and also some folks mentioning the lack of nft support from flannel [here](https://github.com/rancher/rancher/issues/23045#issuecomment-602794617)

So the FORWARD rules from flannel seems not to be inserted. The difference here between the behavior that you've checked and mine is that the Pod IP isn't accessible as well. 

Just as a test, can you please run a ``iptables -P FORWARD ACCEPT`` in the node running the workload and run the test again so we can isolate and check if this is the real problem? 

I'll not be able right now to test this with Calico (as you've said that Calico presents the same behavior) but the tests bellow with your environment would be appreciated to check if this is the case.

Thank you

**Comment by rikatz** [comment]
> We encountered the same problem. I used calico instead of flannel

@system51 did calico worked for you? If don't, can you please change the Daemonset from Calico to force it to use NFT?

https://discuss.kubernetes.io/t/connection-issues-with-pods-on-centos-8-nodes/8650/19

**Comment by rikatz** [comment]
Hi folks.

This is a kindly reminder that if this issue got no attention in the next 14 days it will be closed.

Please take a look at **https://github.com/kubernetes/kubernetes/issues/91331#issuecomment-638472197** for the necessary information.

Thank you

**Comment by rikatz** [comment]
@wk60807430 @system51 issue will be closed tomorrow if no further information can be provided :)

About Calico, changing the backend worked? About flannel, is that clear about the NFT and have you tried to change the policy of FORWARD to ACCEPT just to confirm the case? It seems there's a PR opened into Flannel to solve this: https://github.com/coreos/flannel/pull/1318/files

Thank you!

**Comment by wk60807430** [comment]
> @wk60807430 Need some further information:
> 
> * Is kube-proxy and flannel running as a container or as a binary inside your cluster?
> * Can you please provide the output of a `iptables -L -n -v`? Let's check if you got the same rules as me here.
> * Also, `ipvsadm -L -n` in the source node and the destination node to check if the ipvs rules are created correctly
> 
> From my first test, when using kube-proxy and flannel as a Daemonset inside a container it seems there's an incompability, as flannel still uses the legacy iptables API while Red Hat / CentOS uses the newer iptables API (NFT).
> 
> There has been some discussion about this [here](https://github.com/kubernetes/kubernetes/issues/71305) and also some folks mentioning the lack of nft support from flannel [here](https://github.com/rancher/rancher/issues/23045#issuecomment-602794617)
> 
> So the FORWARD rules from flannel seems not to be inserted. The difference here between the behavior that you've checked and mine is that the Pod IP isn't accessible as well.
> 
> Just as a test, can you please run a `iptables -P FORWARD ACCEPT` in the node running the workload and run the test again so we can isolate and check if this is the real problem?
> 
> I'll not be able right now to test this with Calico (as you've said that Calico presents the same behavior) but the tests bellow with your environment would be appreciated to check if this is the case.
> 
> Thank you

1 kube-proxy and flannel running as a binary inside my  cluster.
2 
![image](https://user-images.githubusercontent.com/40818413/86245936-d345fd00-bbdc-11ea-91b5-dd10918ebcea.png)
3 
![image](https://user-images.githubusercontent.com/40818413/86246011-e9ec5400-bbdc-11ea-9170-80379769c75b.png)

4  when i run a iptables -P FORWARD ACCEPT probloem still there. I can't get DNS or other UDP service  by coreDNS cluster IP

**Comment by rikatz** [comment]
/remove-triage needs-information

OK, will take some further look

**Comment by rikatz** [comment]
@wk60807430 ok, I've created the lab here running flannel as a binary and no big deal with calling the DNS from a different node. Everything running in CentOS 8, kube-proxy in IPVS mode.

A point that I've seen here is that you're using v1.16.0, right? Is that possible to update to 1.16.12 so we can check if there's some minor bug in the middle that might be the reason?

I'll try to see if I can hit this scenario with other configurations.

Tks

**Comment by rikatz** [comment]
@wk60807430 are you sure you're not running flannel as a DaemonSet / container inside your environment?

Per the output that you've sent, there's no flannel configured in your current iptables:

```
    4   265 ACCEPT     all  --  *      *       10.244.0.0/16        0.0.0.0/0           
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.244.0.0/16   
```

And the message in the bottom indicates that you're using something changing the legacy iptables:
 `# Warning: iptables-legacy tables present, use iptables-legacy to see them`

This happens because the iptables package inside the flannel container uses iptables-legacy and not iptables-nft, and CentOS 8 uses only the nft. 

Please take a look at: https://github.com/coreos/flannel/pull/1318 which is a PR that corrects this behavior in flannel.

Is that possible that you fork this PR and use the generated container with iptables-nft to check if this goes fine?

Thank you

**Comment by wk60807430** [comment]
> coreos/flannel#1318
https://github.com/kubernetes-sigs/iptables-wrappers/blob/master/iptables-wrapper-installer.sh
I add this script to my custom flannel container,and i find  it  works on the container which run on my centos8 node 
![image](https://user-images.githubusercontent.com/40818413/86516202-2fb15280-be51-11ea-9607-237cdf411973.png)

![image](https://user-images.githubusercontent.com/40818413/86516003-c8df6980-be4f-11ea-8c5e-18b0ec4339f6.png)
but,soooo sad , test was faild too ,UPD service still not ok on Cluster-ip (⊙︿⊙)
Even after I rebuild my coreDNS deployment，it dose"t work  either 😞
In my node's iptables ruls,I can't find any rule about DNS service(53)
![image](https://user-images.githubusercontent.com/40818413/86516229-7141fd80-be51-11ea-9a49-188b967d5466.png)

Any thing wrong I did ? or other reason ,i don't kown.

**Comment by rikatz** [comment]
@wk60807430 if kube-proxy is running as a DaemonSet (or maybe flannel), can you please post in a pastebin or here (but not being an image, please!) the output of the following commands:

```
iptables-nft -L -n -v
iptables-nft -t nat -L -n -v
iptables-legacy -L -n -v
iptables-legacy -t nat -L -n -v
```

Thank you!

**Comment by rikatz** [comment]
@wk60807430 friendly ping

**Comment by rikatz** [comment]
@wk60807430 any evolution on this? Need the iptables dump from kube-proxy to take a look.

/triage needs-information

**Comment by rikatz** [comment]
@wk60807430 ping

**Comment by rikatz** [comment]
/close

Closing due to lack of response, please feel free to reopen if you have any further information
