### ISSUE TITLE
No way configure timeout for conversion webhooks

### ISSUE THREAD

**Issue by vagababov** [kubernetes/kubernetes#91338]
Regular validation/mutation webhooks have `timeoutSeconds` field which permits configuring the timeout for the webhook to use.
Conversion webhooks on the other wise, use the default timeout of 30s.
It would be beneficial to actually permit this to be configurable for conversion webhooks as well.

**Comment by vagababov** [comment]
/sig api-machinery
I guess...

**Comment by jpbetz** [comment]
This is complicated by a couple things:

- conversion webhook takes a list of objects to convert (admission webhooks take a single object). So it is not as obvious how to pick a timeout limit that works for all requests.
- conversion webhooks are blocking. If the conversion does not happen, there is no other option besides failing the request (for comparison admission webhooks can have failurepolicy: ignore).

**Comment by vagababov** [comment]
This is still the problem with default 30s (either of problems).

**Comment by jpbetz** [comment]
> This is still the problem with default 30s (either of problems).

I agree. But it is also easy to imagine developer shooting themselves in the foot by setting the timeout to a lower value because they don't understand how it is applied. My point is this is not 1-to-1 with the timeout that already exists on admission webhooks.

**Comment by liggitt** [comment]
Is the context of the request triggering the timeout plumbed to the conversion webhook call?
