### ISSUE TITLE
[Failing Test] conformance-ga-master (ci-kubernetes-conformance-kind-ga-only)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#91341]
**Which jobs are failing**:

`conformance-ga-master (ci-kubernetes-conformance-kind-ga-only)`

**Which test(s) are failing**:

`Overall`

**Since when has it been failing**:

`5-20-20 04:19 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only

**Reason for failure**:

```
{"component":"entrypoint","file":"prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","time":"2020-05-20T13:20:01Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:245","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","time":"2020-05-20T13:20:16Z"}
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19
/sig testing

**Comment by hasheddan** [comment]
This may resolve with being moved to new infra: https://github.com/kubernetes/test-infra/pull/17674

**Comment by BenTheElder** [comment]
it's not the infra, this is #91316

**Comment by BenTheElder** [comment]
it should be resolved by the next run, liggitt reverted the regression

**Comment by hasheddan** [comment]
@BenTheElder gotcha, thanks!

**Comment by liggitt** [comment]
Green again

**Comment by hasheddan** [comment]
Thank you @liggitt!
