### ISSUE TITLE
kubernetes Udp is not available

### ISSUE THREAD

**Issue by system51** [kubernetes/kubernetes#91346]
**What happened**:   Unable to resolve using coredns

**What you expected to happen**: Resolve the SVC address

**How to reproduce it (as minimally and precisely as possible)**:

1、Start a coredns pod on a node
![image](https://user-images.githubusercontent.com/26198108/82619925-cad7cb00-9c09-11ea-8d13-59a4391355f7.png)

2、Try to use coredns svc address resolution

![image](https://user-images.githubusercontent.com/26198108/82620091-3d48ab00-9c0a-11ea-88b9-e80e8d5e5c13.png)

note:Only the node where the coredns pod is located can be resolved using the coredns svc address

![image](https://user-images.githubusercontent.com/26198108/82620263-96184380-9c0a-11ea-9582-cf139760184e.png)

![image](https://user-images.githubusercontent.com/26198108/82620297-afb98b00-9c0a-11ea-8343-1b4fd461600a.png)
note:But we can use coredns pod address for resolution

Or use coredns tcp protocol
![image](https://user-images.githubusercontent.com/26198108/82620419-fc9d6180-9c0a-11ea-8df4-5a948343c224.png)

**Anything else we need to know?**:  
1、kube-proxy no error log
2、Use calico ip-in-ip mode is normal
3、Failed to use calico vxlan mode

**Environment**:
- Kubernetes version (use `kubectl version`):   
```
[root@devops010015001003 overlord]#   kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
```
[root@devops010015001003 overlord]# hostnamectl 
   Static hostname: devops010015001003
         Icon name: computer-vm
           Chassis: vm
        Machine ID: e86057833cb746548a07ed6a2ffa4d9a
           Boot ID: 12f7760751cf4671b5b01ca7abb33416
    Virtualization: vmware
  Operating System: CentOS Linux 8 (Core)
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 5.6.14-1.el8.elrepo.x86_64
      Architecture: x86-64
```

- OS (e.g: `cat /etc/os-release`):
```
[root@devops010015001003 overlord]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
- Kernel (e.g. `uname -a`):
```
[root@devops010015001003 overlord]# uname -a
Linux devops010015001003 5.6.14-1.el8.elrepo.x86_64 #1 SMP Tue May 19 12:21:08 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
```
images: flannel:v0.12.0-amd64  

rpm package: kubernetes-cni-0.7.5-0.x86_64
```

- Others:

/sig Network

**Comment by neolit123** [comment]
/sig network

> images: flannel:v0.12.0-amd64  

i think i've seen similar reports from flannel users.

**Comment by neolit123** [comment]
try logging an issue in the flannel repo or try a CNI plugin that works best for you and your setup.
if this is a coredns issue, log a ticket in the coredns issue tracker.

if the maintainers of those projects confirm this is core k8s bug, please reopen this ticket.

thank you.
/close
