### ISSUE TITLE
FailedScheduling doesn't report all reasons for nodes failing

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#91340]
**What happened**:
With a pod that is failing to schedule, seeing the following error:
```
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  95s (x225 over 5h26m)  default-scheduler  0/9 nodes are available: 8 node(s) didn't have free ports for the requested pod ports.
```

This gives the information that 8 nodes failed the node ports filter, but not why the 9th node has failed. In this case, I am running a daemonset so it makes sense that there should be an existing pod on each node consuming the desired port, but my 9th pod is failing to schedule. Therefore, the information that 8 nodes don't have free ports is obvious and doesn't help debug the scheduling error at all.

**What you expected to happen**:
The number of reasons given for scheduling failures should equal the number of nodes. Is it possible that some filters are not always reporting errors when they fail?

This does not have to be an event in the pod status, but could be done through improving the scheduler's logging to make this information more accessible.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling

**Comment by Huang-Wei** [comment]
@damemi which k8s version are you running on? https://github.com/kubernetes/kubernetes/pull/86022 seems to have resolved your problem (available since 1.18).

**Comment by damemi** [comment]
@Huang-Wei this is on a 1.18.2 cluster:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2", GitCommit:"d543523", GitTreeState:"clean", BuildDate:"2020-05-21T06:49:03Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

This was a weird report, because like you said I know it usually does report all of the errors now. But clearly, for some reason, at least one is being omitted

**Comment by Huang-Wei** [comment]
Sounds like a bug. Are you able to reproduce it?

**Comment by zhouya0** [comment]
@Huang-Wei Can I try to fix this bug?

**Comment by Huang-Wei** [comment]
@zhouya0 Sure. But it’s better to check with @damemi first in case he has started working on it.

**Comment by zhouya0** [comment]
The number of scheduling failures is the number of reasons so it's possible for scheduling failures more than the number of nodes, for example node resource filter can have two reasons:
```
 0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory.
```
But seems not possible for scheduling failures less than nodes in your case:
```
0/9 nodes are available: 8 node(s) didn't have free ports for the requested pod ports.
``` 
So I think this is really a bug.

**Comment by damemi** [comment]
Hi, unfortunately I'm not sure how I could reproduce it (which is part of the problem, lol). This just occurred on a cluster, and we were unable to diagnose what the issue was with the 9th node from looking at the pod and node info. Eventually, the scheduler restarted and the pod went through fine.

The only other information I have is that the pod did have a required affinity for that particular node, and that node did not have any other pods from the daemonset running on it yet (so this, we're assuming, was the 9th node to correspond to this 9th pod). From that I am guessing that some other filter failed for this node without reporting its error.

@zhouya0 I haven't started working on this so if you would like to please feel free. I apologize that it's such an open-ended problem though and wish there was more information I could give you to start with.

**Comment by zhouya0** [comment]
@damemi Great, indeed I can't reproduce this bug in my env. Waiting for more evidence for this.

**Comment by damemi** [comment]
Similar issue reported in https://github.com/kubernetes/kubernetes/issues/91601

**Comment by alculquicondor** [comment]
/assign
I'll look at this tmr

**Comment by damemi** [comment]
In both cases, it sounds like restarting the scheduler fixes the problem. Possibly something we're missing in cache management then?

**Comment by alculquicondor** [comment]
In you case, what was newer: the daemonset or the node?

**Comment by alculquicondor** [comment]
also, did you use the default profile?

**Comment by alculquicondor** [comment]
Do you have extenders?

**Comment by damemi** [comment]
@alculquicondor unfortunately I don't have all of that information, I saw this on a cluster that someone else asked me to debug and didn't think to look at those. I'll follow up with that reporter and update

**Comment by alculquicondor** [comment]
Please do. According to my initial investigation, a possible culprit could be a plugin missing to report a "reason". But looking through the codebase didn't reveal any in-tree problems.

**Comment by alculquicondor** [comment]
plugin or extender

**Comment by dennis-benzinger-hybris** [comment]
We've seen such messages when the "missing" nodes have taints. For example the master nodes.

**Comment by alculquicondor** [comment]
Do the pods have tolerations for them, or fails for both present and absent?

/close

Please answer in #91601, so we dedup
