### ISSUE TITLE
Log symlinks are garbage collected even if containers are not

### ISSUE THREAD

**Issue by sjmiller609** [kubernetes/kubernetes#91345]
**What happened**:

I am hoping it is possible to configure kubelet such that a logging agent such as fluentd is capable to collect the logs of short-lived pods.

The deprecated flag --minimum-container-ttl-duration is still working to keep containers around in the "stopped" state after pods are terminated, only getting "removed" after the minimum TTL has passed. This is evident by container remaining "stopped" (viewed with 'docker ps -a') on the node up until at least the configured value.

However, the logging symlinks in /var/log/pods are removed shortly after the pod is gone. I can see on EKS, which uses Docker engine, that the container log exists in /var/lib/docker/containers/\*/*.log while the corresponding symlink is gone from /var/log/pods and /var/log/containers.

I think this function is where it happens, but I do not fully understand it: https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L400

This is the body of that function:
```
	// Remove evictable containers
	if err := cgc.evictContainers(gcPolicy, allSourcesReady, evictTerminatedPods); err != nil {
		errors = append(errors, err)
	}

	// Remove sandboxes with zero containers
	if err := cgc.evictSandboxes(evictTerminatedPods); err != nil {
		errors = append(errors, err)
	}

	// Remove pod sandbox log directory
	if err := cgc.evictPodLogsDirectories(allSourcesReady); err != nil {
		errors = append(errors, err)
	}
	return utilerrors.NewAggregate(errors)
```

I think maybe this part: "evictContainers" is conditional to remove the container based on the TTL, and the this part: ".evictPodLogsDirectories" is only conditional on if the pod is gone (pod is gone, but container within TTL)

**What you expected to happen**:

I expect it to be possible to configure a log-collecting daemonset and / or kubelet in order to collect logs for short-lived pods.

**How to reproduce it (as minimally and precisely as possible)**:

you can set --minimum-container-ttl-duration and see that the symlinks in /var/log/pods disappear before the TTL.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Have you looked at #89160 ?

**Comment by tedyu** [comment]
This can be closed as dup.

**Comment by sjmiller609** [comment]
@tedyu I inspected the PR, can you help me understand?
this line:
```
				} else if status.State != runtimeapi.ContainerState_CONTAINER_EXITED {
```
I want the symlink only removed if in docker the container is removed, rather that only if it's stopped. Do you know if your change will prevent removal of the symlink in the event the container is stopped but not removed by container GC? This is like when you have containers that show up with 'docker ps -a' but not 'docker ps'

**Comment by tedyu** [comment]
I need to do some homework w.r.t. docker container being in stopped versus removed state.

Looking at k8s code, we only have ContainerState_CONTAINER_EXITED
