### ISSUE TITLE
wrong comment for preparedAPIAggregator struct

### ISSUE THREAD

**Issue by Xindahuang** [kubernetes/kubernetes#91359]
**What happened**:
https://github.com/kubernetes/kubernetes/blob/1a8561464e33a63869ef9606dcda50895a0101f4/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L99

wrong struct name in its comment 

**What you expected to happen**:
change to `preparedAPIAggregator`
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
nothing
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Thanks for the attention to detail, an issue isn't really needed to track this, a PR to fix it can be opened directly
