### ISSUE TITLE
#sig-multicluster ..kube/config file wont update locally.

### ISSUE THREAD

**Issue by himanshusharma-git** [kubernetes/kubernetes#91361]
**What happened**:
i was using my cluster locally by copying .kube/config file in my local system , i created a name space and started working in it and meanwhile i was also looking at my cluster not locally but where it was actually running . I created a name space and switched on it on from both of my machine , locally as well as original bare-metal one , after completing my work i can see all changes i made to from my local machine are upto mark with my bare-metal machine , i delete the namespace and switched back to default one but it wont happened to bare-metal , i can still see at the .kube.config file that it was still same to the name space i created.
**What you expected to happen**:
I was expecting all things to be in sync, like if locally i made some changes it should me made to bare-metal too but no i have to switch back to default namespace manually again from my bare-metal machine too.
Everything change we made to our cluster from local system by accessing .kube/config file is a success but then why it does not make this possible to . when the name space is already delete it should automatically switch to default namespace coz from remote machine i have already delete the namespace as well as have switched back to it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by himanshusharma-git** [comment]
sig-multicluster

**Comment by himanshusharma-git** [comment]
> @himanshusharma-git: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

/sig multicluster

**Comment by liggitt** [comment]
The current namespace is optionally specified in the kubeconfig file, not as a server-side setting. If you copy the kubeconfig file elsewhere, changes made to the original file will not be replicated. You can set the current namespace used by the client with this command:

```
kubectl config set-context --current --namespace=<desired_namespace>
```
