### ISSUE TITLE
[Failing Test] kind-master-parallel / kind-ipv6-master-parallel (ci-kubernetes-kind-e2e-parallel / ci-kubernetes-kind-ipv6-e2e-parallel)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#91367]
**Which jobs are failing**:
`kind-master-parallel (ci-kubernetes-kind-e2e-parallel)`
`kind-ipv6-master-parallel (ci-kubernetes-kind-ipv6-e2e-parallel)`

**Which test(s) are failing**:

`[sig-api-machinery] client-go should negotiate watch and report errors with accept "application/json"`
`[sig-api-machinery] client-go should negotiate watch and report errors with accept "application/json,application/vnd.kubernetes.protobuf`

**Since when has it been failing**:
`5/22/20 8:52 PT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel
https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel

**Reason for failure**:

```
May 22 19:23:58.731: FAIL: Expected
    <bool>: false
to be true
Full Stack Trace
k8s.io/kubernetes/test/e2e/apimachinery.glob..func13.1()
	test/e2e/apimachinery/protocol.go:62 +0x51e
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc00046f400)
	test/e2e/e2e.go:130 +0x360
k8s.io/kubernetes/test/e2e.TestE2E(0xc00046f400)
	test/e2e/e2e_test.go:141 +0x2b
testing.tRunner(0xc00046f400, 0x4e304f8)
	GOROOT/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:960 +0x350
[AfterEach] [sig-api-machinery] client-go should negotiate
  test/e2e/framework/framework.go:175
May 22 19:23:58.732: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
• Failure [2333.797 seconds]
[sig-api-machinery] client-go should negotiate
test/e2e/apimachinery/framework.go:23
  watch and report errors with accept "application/json,application/vnd.kubernetes.protobuf" [It]
  test/e2e/apimachinery/protocol.go:46
  May 22 19:23:58.731: Expected
      
      <bool>: false
  to be true
  test/e2e/apimachinery/protocol.go:62
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by hasheddan** [comment]
Suspect it has to do with https://github.com/kubernetes/kubernetes/pull/91260
cc @wojtek-t 

/assign @VineethReddy02 
(for CI signal ownership)

**Comment by liggitt** [comment]
Seems unlikely since multiple kind e2e tests passed on the PR itself

**Comment by hasheddan** [comment]
@liggitt I was thinking that as well, but I don't see any other relevant changes

**Comment by liggitt** [comment]
Actually, I take that back. Looks like the same failure was encountered as a flake on some of the PR runs. 

Looking at the test, it appears to assume the resource version of the kubernetes service will always be in the watch window, which is a bad assumption. 

I'd expect us to fix that assumption in the test, but also make sure we didn't unintentionally shrink the watch window for resources.

**Comment by hasheddan** [comment]
Note: this also appears to be breaking `gce-cos-master-default`

**Comment by gongguan** [comment]
I'm willing to take a look, but how could I get the apiserver log which can't be seen in artifacts.

**Comment by liggitt** [comment]
Failure seems to be timeout related as well

https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel&graph-metrics=test-duration-minutes&width=20 shows the runtime ~tripled after 99dff90d613e2014873dc2fae0a00acaf95c3bd2 merged

**Comment by liggitt** [comment]
revert open in https://github.com/kubernetes/kubernetes/pull/91380

can investigate test failure and timeouts and bring the change back in

**Comment by liggitt** [comment]
> Looking at the test, it appears to assume the resource version of the kubernetes service will always be in the watch window, which is a bad assumption.
> 
> I'd expect us to fix that assumption in the test, but also make sure we didn't unintentionally shrink the watch window for resources.

I take it back, the test tolerates an expired error explicitly.

**Comment by liggitt** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel&graph-metrics=test-duration-minutes showed 17 of the 22 runs since 1700acb035ce24b760ff6e2c3fb6ee6246528ab1 merged took ~1 hour.

The first run after the revert at c37837e5eaf92c440913f7e16c9007428350a461 returned to less than 30 minutes for the run. Will keep an eye on that to see if subsequent runs match.

**Comment by wojtek-t** [comment]
@liggitt - thanks a lot for looking into it.
I don't think my PR changed anything that anyone should rely on. I will take a deeper look into it and try to fix that (hopefully later this week).

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/issues/91415 contains the explanation and describes the bug (in fact this bug still exists in the codebase, that PR was only increasing the probability of this particular test hitting it)
