### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by dsx** [kubernetes/kubernetes#91368]
**What happened**:
kube-router process crashed:

`kube-router I0522 21:36:22.204132       1 kube-router.go:216] Running /usr/local/bin/kube-router version v1.0.0-rc4, built on 2020-05-20T19:03:51+0000, go1.10.8             
 kube-router I0522 21:36:24.157143       1 network_policy_controller.go:142] Starting network policy controller                                                               
 kube-router I0522 21:36:24.157170       1 network_policy_controller.go:147] Starting network policy controller full sync goroutine                                           
 kube-router I0522 21:36:24.166910       1 network_routes_controller.go:981] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen 
  on node IP: 192.0.2.1 address.                                                                                                                                            
 kube-router I0522 21:36:24.236453       1 network_services_controller.go:287] Starting network services controller                                                           
 kube-router I0522 21:36:24.323871       1 network_routes_controller.go:225] Starting network route controller                                                                
 kube-router I0522 21:36:24.331495       1 network_routes_controller.go:752] Could not find BGP peer info for the node in the node annotations so skipping configuring peer.  
 kube-router E0522 21:36:24.437219       1 service_endpoints_sync.go:201] Failed to create ipvs service for node port due to: file exists                                     
 kube-router panic: runtime error: invalid memory address or nil pointer dereference                                                                                          
 kube-router [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=2020-05-22T17:36:24.44213865-04:00 0xf82aa7]                                                       
 kube-router goroutine 156 [running]:                                                                                                                                         
 kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.ipvsServiceString(0x0, 0xc420cff2c0, 2020-05-22T17:36:24.442205419-04:00 0x1c)                      
 kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:1447 +0x37                                               
 kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*linuxNetworking).ipvsAddServer(0xc42000d150, 0x0, 0xc420c73500, 0x15, 0xc4204637a0)               
 kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:17172020-05-22T17:36:24.442238663-04:00  +0x303          
 kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).setupNodePortServices(0xc421005180, 0xc4209d99b0, 0xc4209d99e0, 0xc420 
 a0ba28, 0x0, 0x0)                                                                                                                                                            
 kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/service_endpoints_sync.go:230 +0x7dd                                                    
 kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).syncIpvsServices(0xc421005180, 0xc4209d99b0, 0xc4209d99e0, 0x0, 0x0)   
 kube-router     2020-05-22T17:36:24.442274981-04:00 /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/service_endpoints_sync.go:43 +0x16f                 
 kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).doSync(0xc421005180, 0x0, 0x0)                                         
 kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:439 +0x143                                               
 kube-router github.com/cloudnativelabs/kube-router/pkg/controllers/proxy.(*NetworkServicesController).Run(0xc421005180, 0xc4201ad020, 0xc42008e840, 0xc4203cc900)            
 kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/controllers/proxy/network_services_controller.go:3572020-05-22T17:36:24.442308226-04:00  +2020-05-22T17:3 
 6:24.442839024-04:00 0x401                                                                                                                                                   
 kube-router created by github.com/cloudnativelabs/kube-router/pkg/cmd.(*KubeRouter).Run                                                                                      
 kube-router     /go/src/github.com/cloudnativelabs/kube-router/pkg/cmd/kube-router.go:179 +0xa8c                                                                             
`

**What you expected to happen**:
Kube router process doesn't crash

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
Looks like kube-router doesn't handle well stale ipvs entries

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.2
- Cloud provider or hardware configuration: off the shelf bare metal
- OS (e.g: `cat /etc/os-release`): NixOS 20.03 (Markhor)
- Kernel (e.g. `uname -a`): 5.4.35
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by dsx** [comment]
Sorry for the mess, I honestly don't know how to fix it.

**Comment by tedyu** [comment]
I searched for network_services_controller.go in k8s codebase but don't seem to find it.

Should this be logged in kube-router repo ?

**Comment by dsx** [comment]
> I searched for network_services_controller.go in k8s codebase but don't seem to find it.
> 
> Should this be logged in kube-router repo ?

It totally should! Too many browser tabs…
