### ISSUE TITLE
Allow restricting scope of (Cluster)RoleBinding a user can create with RBAC

### ISSUE THREAD

**Issue by RyuunoAelia** [kubernetes/kubernetes#91376]
**What would you like to be added**:
I think at least white/blacklisting the (Cluster)Roles that can are referenced by (Cluster)RoleBindings would be a good start for security minded clusters.

Also maybe restricting the ApiGroups/Resources/Verbs of (Cluster)Role would help too (just throwing an idea here).

**Why is this needed**:
With the increase of Controllers (Operators) trying to mangle with RBAC, from a security perspective, I think it should be great to be able to limit what they can to while mangling the RBACs.

**Comment by RyuunoAelia** [comment]
The rationale is simple here (and most obvious for ClusterRoleBindings), if you allow a service account to manipulate (create or modify) ClusterRoleBindings without restrictions, then it can basically privilege escalate  to any right it wants.

**Comment by liggitt** [comment]
Take a look at https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping

When modifying a (cluster)role or (cluster)rolebinding, by default, the writer can only set permissions in a role (or create/modify a binding to a role with permissions) which they already hold.

**Comment by RyuunoAelia** [comment]
Oh yes... sorry for the noise I overlooked this part of the doc...
