### ISSUE TITLE
Default value not allowed for in x-kubernetes-list-map-keys

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#91395]
**What happened**:
I have a CRD which was working fine in 1.17. But it fails with in 1.18.

CRD YAML:
https://github.com/kubedb/apimachinery/blob/ok117/api/crds/kubedb.com_memcacheds.yaml

In 1.18, I get the following error:

```
Error: CustomResourceDefinition.apiextensions.k8s.io "memcacheds.kubedb.com" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[podTemplate].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

Then I tried to add a `default` value for the `protocol` field. But now, I am getting this error in 1.18 .

```
The CustomResourceDefinition "memcacheds.kubedb.com" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[podTemplate].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Forbidden: must not be set
```

I am generating the CRD YAMLs using kubebuilder controller-tools v0.3.0 from this Go source file:

https://github.com/kubedb/apimachinery/blob/f118/apis/kubedb/v1alpha1/memcached_types.go

**What you expected to happen**:
I expected the CRD yaml to work in 1.18 like it did in 1.17 .

**How to reproduce it (as minimally and precisely as possible)**:
Just create a cluster using kind and do `kubectl create -f`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/sig api-machinery
/area custom-resources

**Comment by tamalsaha** [comment]
cc: @sttts 

Can you please help me understand the default value is not acceptable here?

Also, this is using the PodTemplate and Go types from the core/v1 .

**Comment by tamalsaha** [comment]
Just so you now the example CronJob yaml is controller-tools project also does not work in 1.18 

https://github.com/kubernetes-sigs/controller-tools/blob/v0.3.0/pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml

```
$ kubectl version --short
Client Version: v1.18.3
Server Version: v1.18.2

$ kubectl create -f https://github.com/kubernetes-sigs/controller-tools/raw/v0.3.0/pkg/crd/testdata/testdata.kubebuilder.io_cronjobs.yaml
The CustomResourceDefinition "cronjobs.testdata.kubebuilder.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[embeddedResource].properties: Required value: must not be empty if x-kubernetes-embedded-resource is true without x-kubernetes-preserve-unknown-fields

```

**Comment by liggitt** [comment]
properties defined as list map keys must either be required or have a default value. Otherwise merge behavior on items that do not specify is undefined. 

You can specify default attributes using the v1 CRD API

**Comment by tamalsaha** [comment]
Thanks @liggitt ! What is the best way to keep up with this type of breaking changes for CRDs?

**Comment by sttts** [comment]
> Thanks @liggitt ! What is the best way to keep up with this type of breaking changes for CRDs?

This was part of the release notes: https://github.com/kubernetes/kubernetes/pull/88076

The whole change was unfortunate: `x-kubernetes-list-map-keys´ had been introduced to CRDs earlier, but nobody added the necessary validations for CRDs and CRs. https://github.com/kubernetes/kubernetes/pull/88076 fixed that. On that road we noticed that we need stricter requirements on the map keys to make the mechanism sound.

**Comment by tamalsaha** [comment]
Thanks, @sttts ! For me the confusing part was that somewhere kubebuilder controller-tools started auto generating `x-kubernetes-list-map-keys` because once I switched from controller-toold v0.2.x to v0.3.0 it started showing up. Should there be an explicit annotation needed for controller-tools to auto generate `x-kubernetes-list-map-keys` ?

On a separate note, should k/api add these default annotations so that CRD authors can use their types? I know this discussion happened with ObjectMeta but here we are talking about any types from k/api.

**Comment by liggitt** [comment]
> For me the confusing part was that somewhere kubebuilder controller-tools started auto generating x-kubernetes-list-map-keys because once I switched from controller-toold v0.2.x to v0.3.0 it started showing up. 

I'd find that surprising as well. 

> Should there be an explicit annotation needed for controller-tools to auto generate x-kubernetes-list-map-keys

I would expect so… list map keys are an explicit decision about the shape of the API… I'm not sure how controller-tools would automatically infer this.

**Comment by liggitt** [comment]
> On a separate note, should k/api add these default annotations so that CRD authors can use their types?

Indicating default values declaratively makes sense to me, though I wouldn't expect kubebuilder-specific annotations

**Comment by tamalsaha** [comment]
It seems that the listType annotations were added sometime ago (Oct, 2018) but only recent version of kubebuilder (Dec 2019) started using those when generating CRD YAML.

- https://github.com/kubernetes/api/commit/47160d10e38963082e8d35a474e274debc7cb016
- https://github.com/kubernetes-sigs/controller-tools/pull/347

So, the only missing piece is that core types lack any way to indicate default values. I can see why kubebuilder annotations won't make sense here. So, should I file a new feature request for adding an annotation for default values and annotating core types with that?

**Comment by liggitt** [comment]
> So, the only missing piece is that core types lack any way to indicate default values. I can see why kubebuilder annotations won't make sense here. So, should I file a new feature request for adding an annotation for default values and annotating core types with that?

Indicating defaults in struct annotations has been on the backlog for a while (xref https://github.com/kubernetes/kubernetes/issues/25460). Note that not all of our defaults can be expressed declaratively (some defaults vary depending on values of other fields, for example), but as far as I'm aware the ones used as keys in list-map items are constant. A KEP proposing a specific approach would be welcome.

**Comment by cscetbon** [comment]
@tamalsaha hey did you make some progress on that issue. I got the same with operator-sdk

**Comment by jieya-ms** [comment]
A work around in #https://github.com/kedacore/keda/pull/926

**Comment by ymmt2005** [comment]
Another workaround by editing generated CRD with sed:
https://github.com/cybozu-go/coil/blob/6afd89c1cd9261429a9a8ed408a33f144176e57f/v2/Makefile#L30-L33

**Comment by sagarvelankar** [comment]
Pull Request https://github.com/kubernetes/kubernetes/pull/70100 added following comment markers to Ports Field of type slice of ContainerPort Struct inside Container struct in core/v1/types.go

	// +listType=map
	// +listMapKey=containerPort
	// +listMapKey=protocol

kubernetes-sigs/controller-tools converts these comment markers to x-kubernetes-list-type and x-kubernetes-list-map-keys as per https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy for Server Side Apply.

Please advice the purpose of adding listType and listMapKey comment markers to Ports Field of type slice of ContainerPort Struct inside Container struct in core/v1/types.go.

I worked around this issue by removing below comment markers from Ports Field of type slice of ContainerPort Struct inside Container struct in $GOPATH/pkg/mod/k8s.io/api@v0.18.6/core/v1/types.go

	// +listType=map
	// +listMapKey=containerPort
	// +listMapKey=protocol

Then controller-gen did not add x-kubernetes-list-type and x-kubernetes-list-map-keys to CRD
