### ISSUE TITLE
kubernetes.io/maxRetriesForOnFailurePolicy does not set the MaxRetryCount in Docker

### ISSUE THREAD

**Issue by yaminisridaran** [kubernetes/kubernetes#91396]
**What happened**:
I am trying to set maxRetriesForOnFailurePolicy so that docker MaxRetryCount will be set via deployment

**What you expected to happen**:
```
annotations:
  kubernetes.io/maxRetriesForOnFailurePolicy: "5" 
```
the above line should set docker MaxRetryCount to 5

/sig/api-machinery

**Comment by yaminisridaran** [comment]
sig/api-machinery

**Comment by liggitt** [comment]
This was suggested as a pull request in https://github.com/kubernetes/kubernetes/pull/79334, but was not accepted yet, so it's not expected that this annotation would have any effect.
