### ISSUE TITLE
kubectl set selector  --resource-version has no effect

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#91391]
**What happened**:

--resource-version
······
[root@master01 ~]# kubectl set selector svc nginjx-svc app=nginx2 --resource-version=1 -n test -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-24T03:33:34Z"
  labels:
    app: nginjx-svc
  name: nginjx-svc
  namespace: test
  resourceVersion: "1838182"
  selfLink: /api/v1/namespaces/test/services/nginjx-svc
  uid: c1b52ecc-e72d-4449-bad0-deb64fcdd62d
spec:
  clusterIP: 10.68.45.166
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
····
even resource version is wrong ，the update is success
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
·····
[root@master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
·····
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by robinpercy** [comment]
/sig cli

Confirmed that `--resource-version` seems to be ignored in kubectl 1.16.x. However, it does work as expected in 1.17.0 and beyond.

**Comment by yasongxu** [comment]
1.19.0 branch ：

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/set/set_selector.go#L197

1.16 branch ：
https://github.com/kubernetes/kubernetes/blob/release-1.16/staging/src/k8s.io/kubectl/pkg/cmd/set/set_selector.go#L114

I guess this code is missing

`if len(o.resourceVersion) != 0 {
				accessor, err := meta.Accessor(info.Object)
				if err != nil {
					return nil, err
				}
				accessor.SetResourceVersion(o.resourceVersion)
			}`

How to fix this problem in the old version 1.16 ?
