### ISSUE TITLE
[ERROR ImagePull]: failed to pull image k8s.gcr.io

### ISSUE THREAD

**Issue by Chartreux0** [kubernetes/kubernetes#91402]
When I run kubeadm init, I get the following error.

**[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.7: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher**

Please tell me the cause of the error and the solution.

Execution environment
OS：CentOS7
Firewall(OS)：OFF
Country：Japan

**Comment by prasadkatti** [comment]
/sig node
I think this is sig node as the issue is with image pull

**Comment by johscheuer** [comment]
Do you get the same error when you run `docker pull k8s.gcr.io/kube-apiserver:v1.18.3` (assuming you use docker). Could you ensure that the machine can talk to the internet or at least to `k8s.gcr.io/`?

The error message just tells you that `k8s.gcr.io/` is not reachable.

**Comment by tanjunchen** [comment]
@Chartreux0 
could you make sure that `k8s.gcr.io/` is  reachable?

kubeadm init --image-repository registry.aliyuncs.com/google_containers
I guess that  it is good for you.

**Comment by neolit123** [comment]
as already mentioned ensure k8s.gcr.io is reachable.
or prepull the images using `kubeadm config images list --kubernetes-version=...`

seems like a support ticket.
/triage support
/close

**Comment by Chartreux0** [comment]
Thank you for your reply.
The following message was output when executing kubeadm init.

**W0526 08:59:07.348949   29230 version.go:102] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: read tcp 10.12.42.26:39840->34.107.204.206:443: read: connection reset by peer**

Is it because of not being able to communicate with 34.107.204.206?

**Comment by Chartreux0** [comment]
OSのプロキシを設定しなおしたところ、以下のようにエラーが変わりました。

W0527 10:06:26.075331   14809 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.3
[preflight] Running pre-flight checks
	[WARNING HTTPProxy]: Connection to "https://10.12.42.26" uses proxy "http://ProxyServer". If that is not intended, adjust your proxy settings
	[WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://ProxyServer". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.18.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.7: output: Error response from daemon: Get https://k8s.gcr.io/v2/: EOF
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by jiawei666** [comment]
> @Chartreux0 could you make sure that `k8s.gcr.io/` is reachable?
> 
> kubeadm init --image-repository registry.aliyuncs.com/google_containers I guess that it is good for you.

![image](https://user-images.githubusercontent.com/24775116/141481900-6247346a-c95a-401b-b5d8-f80f381e1ad3.png)
is there my kubeadm version wrong?

**Comment by liuyue-niann** [comment]
me to error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.10: output: E0606 13:28:53.327481    7021 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-apiserver/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.10"
time="2024-06-06T13:28:53+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-apiserver/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.28.10: output: E0606 13:29:09.326695    7057 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-controller-manager/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.28.10"
time="2024-06-06T13:29:09+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-controller-manager/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.10: output: E0606 13:29:25.412274    7094 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-scheduler/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.10"
time="2024-06-06T13:29:25+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-scheduler/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.28.10: output: E0606 13:29:41.081820    7131 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-proxy/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.28.10"
time="2024-06-06T13:29:41+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.28.10\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.28.10\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kube-proxy/manifests/v1.28.10\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9: output: E0606 13:29:57.541858    7174 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/pause/manifests/3.9\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9"
time="2024-06-06T13:29:57+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/pause/manifests/3.9\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.12-0: output: E0606 13:30:13.436089    7210 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.12-0\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.12-0\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/etcd/manifests/3.5.12-0\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.12-0"
time="2024-06-06T13:30:13+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.12-0\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.12-0\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/etcd/manifests/3.5.12-0\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1: output: E0606 13:30:29.027339    7247 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/coredns/manifests/v1.10.1\": dial tcp 120.55.105.209:443: connect: no route to host" image="registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1"
time="2024-06-06T13:30:29+08:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1\": failed to resolve reference \"registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1\": failed to do request: Head \"https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/coredns/manifests/v1.10.1\": dial tcp 120.55.105.209:443: connect: no route to host"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
