### ISSUE TITLE
WatchCache may accept watches that it should not

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#91415]
Opening as an follow up analysis from https://github.com/kubernetes/kubernetes/issues/91367

Merging #91260 unexpectedly resulted in a huge flakiness of at least one of the apimachinery tests: https://github.com/kubernetes/kubernetes/issues/91367 
That is definitely unexpected, because that PR only changes the size of watchcache, which no e2e tests should rely on.

So I started digging deeper into it and indeed that PR also uncovered the bug that was introduced earlier.

Here is what is happening:
- https://github.com/kubernetes/kubernetes/pull/90091 made the watch cache size dynamic
- however, there was a place in watch cache that relied on the following invariant:
 "when watchache becomes full, it is full until the next relist"
 that place is this one:
https://github.com/kubernetes/kubernetes/blob/6249f287e1d3d9fb63b60961c8625a82d7db360e/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L537-L544

- with the change that made watchcache size dynamic, it may no longer be true, i.e.:
 (a) watch cache was full
 (b) we are increasing its size
 (c) it is no longer full, but we no longer can't serve (at least not always) everything since listResourceVersion

This is exactly what was happening in the failed tests:
- the service was updated well back in the past
- the watchcache initially rotated couple times (no need to increase it) [which pulled our change out of it]
- the its size was increased
- that resulted in cache becoming not full
- so the incoming watch should have returned "too old", but was accepting it (due to the listResourceVersion > 0 condition being true), but in fact wasn't able to serve it

Bonus point: in "kind" tests we were observing tests taking 30+ minutes - this seem to be a bug in kube-apiserver configuration, because the watch in the test doesn't set TimeoutSeconds, and:
(a) in GCE it is default in kube-apiserver to sth random from [5m, 30m]: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L248-L250
(b) in kind apparently it isn't...

/kind bug
/sig apimachinery

/assign @gongguan @wojtek-t 

@liggitt @hasheddan @jpbetz - FYI

**Comment by wojtek-t** [comment]
Working on the fix right now

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/91417 for now contains a test reproducing the issue
Fix coming soon.

**Comment by wojtek-t** [comment]
#91417 is ready for review

**Comment by aojea** [comment]
> Bonus point: in "kind" tests we were observing tests taking 30+ minutes - this seem to be a bug in kube-apiserver configuration, because the watch in the test doesn't set TimeoutSeconds, and:
> (a) in GCE it is default in kube-apiserver to sth random from [5m, 30m]: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L248-L250
> (b) in kind apparently it isn't...

it seems TimeoutSeconds is configured explicitely on GCE tests  to 300 sec
https://github.com/kubernetes/kubernetes/blob/aed3f054953ef28174930ce9c540f5c2b003ae78/cluster/gce/config-test.sh#L54

KIND is using Kubeadm under the hood and I could not find any place where those flags are configured, but then I think it should be taken the default values for TimeoutSeconds, no?

https://github.com/kubernetes/kubernetes/blob/c5aa1eddcc6f6d5a3fe30532888f632f5ebff647/staging/src/k8s.io/apiserver/pkg/server/config.go#L303-L304

**Comment by BenTheElder** [comment]
I would want to speak to the kubeadm team first, we avoid deviating from their defaults as much as possible so we can test them. cc @neolit123

**Comment by neolit123** [comment]
i see the tests under "client-go should negotiate" are not conformance yet, which makes them less likely to be run outside of k8s testing.

> it seems we should set this apiserver option to a lower value, should we do it in KIND itself?

i personally don't think our tools used for e2e (GCE/kube-up included) should be configuring these kube-apiserver flags. the tests should behave well with any deployer-X that relies on the apiserver sane defaults.
