### ISSUE TITLE
improve Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply

### ISSUE THREAD

**Issue by GeminiAgaloos** [kubernetes/kubernetes#91425]
**What would you like to be added**:

- show a clearer message that better informs the user of a potential conflict between changes done declaratively vs imperatively on the same object,  inform whether the changes have been applied, what may have been overwritten

based on closed issue #82154
1. A resource that has been directly modified imperatively (for example via a kubectl edit command)
 
2. You try to update it again declaratively (for example by kubectl apply -f yamlfile)
The following confusing info message appears:

"Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply... "

**Why is this needed**:
the error message is confusing. is it really an error message or just an informative message?
Did the command successfully execute the changes being asked?
Were the changes applied successfully?
Was there anything overwritten?
If changes were successfully applied, what is the reason for this message to show?

**Comment by 007g3m1n1** [comment]
background references:
#36620 and #36672
https://github.com/kubernetes/kubernetes/pull/36672#issuecomment-266161716

**Comment by booleanbetrayal** [comment]
Agree that this is a confusing message. Could probably use some love. First-round search indexing brought me here.
