### ISSUE TITLE
APIServer proxy to pod with muliple port and schema

### ISSUE THREAD

**Issue by Incarnation-p-lee** [kubernetes/kubernetes#91438]
As we know, kubernetes apiserver proxy allow you to access Node/Pod/Service out of cluster with credentials. The format should following this [doc](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls) For example, services.

https://dns-xxxxxxx.io:443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

But how can I access pod with muliple port which support both http and https ?

**Comment by Jefftree** [comment]
You can specify ports with `https:<service-name>:<port-name>` / `http:<service-name>:<port-name>`. Depending on your use case, ideally you should set up [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)

**Comment by Incarnation-p-lee** [comment]
make sense, you mean it is not recommanded to access pod directly when apiserver proxy ?
