### ISSUE TITLE
share custom indexer among controllers to improve the overall performance

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#91436]
**What would you like to be added**:

share custom indexer among controllers to improve the overall performance

**Why is this needed**:

xref: https://github.com/kubernetes/kubernetes/issues/88229#issuecomment-633341770

current attach detach controller has a custom indexer to index pods by PVC keys to avoid iterating all pods every time to find pods which reference given PVC. 
https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/attachdetach/attach_detach_controller.go#L199-L203

And there are other places we need to check if a PVC is used by a pod or not from pod informer, e.g. 

- pvc_protection_controller [askInformer](https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L231-L247)
- pv_controller [isVolumeUsed](https://github.com/kubernetes/kubernetes/blob/4e8b56e6671893757d40e2001a3c615acebc13a2/pkg/controller/volume/persistentvolume/pv_controller.go#L1298-L1321)

we can share this custom indexer among these volume controllers.

/kind cleanup
/sig storage

**Comment by RaunakShah** [comment]
@cofyc If this is not taken up already, i can do so.

**Comment by cofyc** [comment]
This is a proposal, not decided yet. details must be discussed first.

**Comment by RaunakShah** [comment]
Yes i agree that a discussion is needed. 
I was actually looking at the first suggestion from https://github.com/kubernetes/kubernetes/issues/88229#issuecomment-633781359:

> we can add an indexer in the PV controller locally to solve this issue first (also optimize isVolumeUsed)

**Comment by cofyc** [comment]
> Yes i agree that a discussion is needed.
> I was actually looking at the first suggestion from [#88229 (comment)](https://github.com/kubernetes/kubernetes/issues/88229#issuecomment-633781359):
> 
> > we can add an indexer in the PV controller locally to solve this issue first (also optimize isVolumeUsed)

oh, I've already opened a PR to fix that issue https://github.com/kubernetes/kubernetes/pull/91455.

If you're interested in this issue too, you can take it. Basically, there are two things we should discuss first:

- how to share the indexer between controllers. I'm not sure if it violates the design of the controller manager. currently, each controller is independent
- different controllers care different pods
  - I guess the shared indexer must index all pods and each controller can run a post-filter on returned pods from the indexer

**Comment by cofyc** [comment]
@jsafrane @msau42 what do you think about this idea?

in addition to builtin indexers in SharedIndexInformer, if we can register this PVC to pods indexer in the shared pod informer, multiple volume controllers can benefit from it.

**Comment by jsafrane** [comment]
Sharing a common indexer among controllers would be awesome.

**Comment by msau42** [comment]
sgtm, are you thinking of something specific for volume controllers, or something in the sharedinformer interface? If the latter, we'll have to run this by sig-apimachinery

**Comment by cofyc** [comment]
> sgtm, are you thinking of something specific for volume controllers, or something in the sharedinformer interface? If the latter, we'll have to run this by sig-apimachinery

I'm thinking of the former, as this indexer is controller-specific. Here is pseudocode:

``` go
const (
     // PodPVCIndex is the lookup name for the index function, which is to index by pod pvcs.
     PodPVCIndex = "pod-pvc-index" 
)

// PodPVCIndexFunc returns PVC keys for given pod
func PodPVCIndexFunc(obj interface{}) ([]string, error) {
    pod, ok := obj.(*v1.Pod)
    if !ok {
        return []string{}, nil 
    }    
    keys := []string{}
    for _, podVolume := range pod.Spec.Volumes {
        if pvcSource := podVolume.VolumeSource.PersistentVolumeClaim; pvcSource != nil {
            keys = append(keys, fmt.Sprintf("%s/%s", pod.Namespace, pvcSource.ClaimName))
        }   
    }   
    return keys, nil
}

func AddIndexerIfNotPresent(indexer cache.Indexer, indexName string, indexFunc cache.IndexFunc) error {
     indexers := indexer.GetIndexers()
     if _, ok := indexers[indexName]; ok {
         return nil
     }
     return indexer.Add(cache.Indexers{indexName: indexFunc})
}
```

In each controller, we use the following code to initialize pod indexer:

```go
controller.podIndexer = p.PodInformer.Informer().GetIndexer()
if err := AddPodPVCIndex(controller.podIndexer, PodPVCIndex, PodPVCIndexFunc); err != nil {
     return err
}

// now, this controller can use `PodPVCIndex` lookup name to access this shared indexer.
```

- the controller initialization order does not matter
- and controllers can be enabled/disabled independently
