### ISSUE TITLE
An ability to find installed storage provisioners

### ISSUE THREAD

**Issue by 0xMH** [kubernetes/kubernetes#91464]
**What would you like to be added**:
With Kubernetes one can define storage classes with provisioners. How does one find which provisioners are installed and available in the cluster? I didn't find away to get this info.

**Why is this needed**:
When you specify in a storage class a provisioner that does not exist, and then try to create a persistent volume claim with this class you get something like the following error: "no volume plugin matched". So it isn't unreasonable to be able to query K8S or this info.

**Comment by RaunakShah** [comment]
```
kubectl get csidrivers
```

lists the csi driver(s) installed on your cluster. You can use a csi driver in the provisioner field for a storage class. 

I'm not sure if there's a similar mechanism for in-tree provisioners.
