### ISSUE TITLE
Kubelet should handle node shutdown 

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#91472]
**What would you like to be added**:

Kubelet currently does not handle machine shutdown. Kubelet should be able to detect machine shutdown and gracefully terminate pods with attempt to respect pod's requested grace period.

**Why is this needed**:

Currently, when a machine is shutdown, Kubelet does not have any special handling to gracefully terminate pods. Machine shutdown can be a simple as `sudo shutdown now` or pressing the power key.

Some items to consider:

* Constrained machine shutdown time
    * In some cases, machines may or may not have a constrained time to shutdown. As a result, it's not always possible to respect a pod's requested grace period. 
       *  Certain cloud providers offer preemptive style VM's (e.g. [GCE Preemptible VM](https://cloud.google.com/compute/docs/instances/preemptible) or [AWS EC2 Spot instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html) that run at lower prices but can be terminated at any time with a fixed termination period (e.g. GCP PVMs offer 30 secs timeout, EC2 offers two-minutes). 
       * Some type of cloud provider integration of detecting preemption and specifying node termination period may be useful here 
       * Improving node shutdown would help experience of using preemptive style VMs with Kubernetes.

* Machine shutdown interference  (e.g. systemd)
    * In cases where kubelet is managed by systemd, systemd shutdown may interfere with kubelet. For example, during machine shutdown, systemd sends SIGTERM's to all processes on the VM (including all containers). This can potentially interfere with expected pod lifecycle (e.g. `preStopHooks` should be run before SIGTERM) [1]. There needs to be a way to ensure kubelet can mange lifecycle of pods during shutdown without systemd interference.   

[1] https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods

Related to #66393, #30051

**Comment by mrunalp** [comment]
We can look into using a custom script in `/usr/lib/systemd/system-shutdown` that signals the kubelet before systemd initiates node shutdown. More details here - https://www.freedesktop.org/software/systemd/man/systemd-halt.service.html

**Comment by bobbypage** [comment]
Thanks Mrunal, we should try that out. 

However, still need to figure out if it's possible to somehow block systemd from sending SIGTERMs to kubelet and processes managed by kubelet (i.e. all the pods/containers). Based on what I saw currently, systemd will just send SIGTERMs to all processes on the node during shutdown. However, if kubelet will manage the lifecycle of the pods during shutdown we need to ensure systemd won't interfere and also send it's own SIGTERMs during shutdown to the pods.

**Comment by mrunalp** [comment]
@bobbypage If the systemd custom shutdown scripts work as we think they do, then it can send a signal to kubelet and wait for some time or from a signal from the kubelet (could be something as simple as a file written somewhere) to clean up the pods and then return back control to systemd. systemd should not be sending any SIGTERMs during that period. That way kubelet can be responsible for pod shutdown while systemd can then proceed with system service and the node shutdown.

**Comment by justinsb** [comment]
(tagging with cloudprovider for processing the cloud-provider-specific hooks, processing shutdown signals is likely still a node topic)
