### ISSUE TITLE
scheduler extender pods can not be scheduled because sheduler extender is unavailable

### ISSUE THREAD

**Issue by RyanAoh** [kubernetes/kubernetes#91489]
**What would you like to be added**:
maybe we can add a field `podSelector` for extender to decide whether this pod is needed to be handled. Or, some way to tell it the pod is itself ?

**Why is this needed**:
scheduler extender pods can not be scheduled because sheduler extender isunavailable
```shell
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  Post http://scheduler-extender.kube-system:8000/scheduler/filter: dial tcp 10.107.151.182:8000: connect: connection refused
  Warning  FailedScheduling  <unknown>  default-scheduler  Post http://scheduler-extender.kube-system:8000/scheduler/filter: dial tcp 10.107.151.182:8000: connect: connection refused
```
The pod is Pending. BTW, the param `extender.IsIgnorable` can not be set to `True` for my case

**Comment by RyanAoh** [comment]
sig/scheduling

**Comment by cofyc** [comment]
I guess you want to apply your custom scheduling policies to a subset of your pods and don't want 
 them to be ignored.
Which scheduler to use is determined on pod side.  You can deploy another instance of `kube-scheduler` and name it to a custom name. Your workloads can choose it by setting this custom scheduler name in `pod.spec.schedulerName`.

**Comment by cofyc** [comment]
The current scheduler supports multiple profiles, but extenders are shared globally. Maybe in the future, the extender can be configured in the scheduler profile.

**Comment by cofyc** [comment]
> The current scheduler [supports multiple profiles](https://github.com/kubernetes/kubernetes/blob/c1707541d8430716477f2dfa163ef9f9cdcbe9ba/pkg/scheduler/apis/config/types.go#L110-L114), but [extenders are shared globally](https://github.com/kubernetes/kubernetes/blob/c1707541d8430716477f2dfa163ef9f9cdcbe9ba/pkg/scheduler/apis/config/types.go#L116-L118) by all profiles. Maybe in the future, the extender can be configured in the scheduler profile.

@Huang-Wei @alculquicondor What do you think about this? As an extension mechanism, it's better if it can be supported in the current scheduler profile.

**Comment by ahg-g** [comment]
> > The current scheduler [supports multiple profiles](https://github.com/kubernetes/kubernetes/blob/c1707541d8430716477f2dfa163ef9f9cdcbe9ba/pkg/scheduler/apis/config/types.go#L110-L114), but [extenders are shared globally](https://github.com/kubernetes/kubernetes/blob/c1707541d8430716477f2dfa163ef9f9cdcbe9ba/pkg/scheduler/apis/config/types.go#L116-L118) by all profiles. Maybe in the future, the extender can be configured in the scheduler profile.
> 
> @Huang-Wei @alculquicondor What do you think about this? As an extension mechanism, it's better if it can be supported in the current scheduler profile.

We discussed this before. The conclusion if I recall correctly is that we could add ```Extenders``` to the profiles in the future. The semantics for the list defined outside will be a default configuration for profiles that don't define one.

**Comment by alculquicondor** [comment]
Actually, the conclusion was that extenders already had a way to exclude pods, but making them per-profile was not discarded for the future.

https://github.com/kubernetes/kubernetes/issues/88529#issuecomment-590950777

> The pod is Pending. BTW, the param extender.IsIgnorable can not be set to True for my case

Could you use this?

https://github.com/kubernetes/kubernetes/blob/87473a5d27e52f8eb86575898cd6e6d8b8e881be/staging/src/k8s.io/kube-scheduler/config/v1/types.go#L153-L159

**Comment by RyanAoh** [comment]
@alculquicondor I  saw this (`ExtenderManagedResource`) way excludes pods according to the extended resource. But I have no such resource in the case.

**Comment by alculquicondor** [comment]
You could add a phantom one. That's kind of the point of the extenders, to manage external resources.
Have you considered using a scheduler plugin instead?

**Comment by alculquicondor** [comment]
@RyanAoh did any of the suggested solutions work for you?

**Comment by RyanAoh** [comment]
@alculquicondor em..I‘ve learned about the scheduling framework, perhaps using a scheduler plugin is a better way in the long term.  Currently, I deployed extenders as static pods.
