### ISSUE TITLE
host network pods do not show IPv6 address in 'kubectl describe'

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#91494]
**What happened**:

kubectl describe of host network pods only appears to show the IPv4 address. 

**What you expected to happen**:

The IPv6 addresses(es) should be shown too (possibly even the local one). 

The IP addresses are visible from within the pods using `ip addr`

**How to reproduce it (as minimally and precisely as possible)**:

With a dual stack system in place run `kubectl describe` on a pod running with 'hostNetwork: true'. 

I used the apiserver and the cloud controller
**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-beta.0", GitCommit:"6a0e01880ad7ea4c110040c3be417516c0bf6bca", GitTreeState:"clean", BuildDate:"2020-05-19T12:54:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-beta.0", GitCommit:"6a0e01880ad7ea4c110040c3be417516c0bf6bca", GitTreeState:"clean", BuildDate:"2020-05-19T12:46:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Brightbox
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`):
Linux srv-5oo9z 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Kubeadm
- Network plugin and version (if this is a network-related bug):
Calico 3.14 

- Others:

**Comment by aojea** [comment]
this is a known limitation in current dual-stack status and hopefully it will be fixed by
https://github.com/kubernetes/enhancements/pull/1665

**Comment by danwinship** [comment]
Yeah, this isn't a kubectl bug; the pod actually only has one podIP, and kubectl is showing that correctly.
#91940 tracks the dual-stack hostNetwork pod IP bug
/close
