### ISSUE TITLE
Remove the apiserver insecure port

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#91506]
The API server's "insecure-port" has been [deprecated since 1.10](https://github.com/kubernetes/kubernetes/commit/2f175bc43279a1a4552610a42af0a006f4c6fba2), but never had a deadline for removal. Previous efforts to remove the port have been blocked by requirements for http healthz checks (https://github.com/kubernetes/kubernetes/issues/43784).

I propose publishing a deadline to remove the feature in v1.20. This means that in v1.19 we:
1. Update the deprecation notice to indicate that removal will happen in v1.20 (rather than a "future release")
2. Add an [action required] release note to highlight the removal
3. Figure out a path forward to meeting healthz or other requriments

For item 3, there are already out-of-tree solutions available today, such as a healthz-only proxy which can serve the same API on the same port, and authenticates as a user that only has access to healthz.

/cc @justinsb @micahhausler @deads2k @liggitt 
/sig auth api-machinery
/milestone v1.20
/kind cleanup
/priority important-longterm

**Comment by BenTheElder** [comment]
cc @neolit123

**Comment by liggitt** [comment]
I would also consider changing the default in 1.19 to be off (`0`), rather than on (`8080`)

**Comment by liggitt** [comment]
Also, I would recommend leaving the inert flag in place for a few releases even after the insecure serving code is removed. I want to avoid accidents where people stop setting `--insecure-port=0` too early in response to warnings about the flag being removed, and accidentally opt back into the default behavior of enabling the insecure port.

**Comment by neolit123** [comment]
> I would also consider changing the default in 1.19 to be off (0), rather than on (8080).

+1, not enabling the insecure port by default is very reasonable.

**Comment by knight42** [comment]
Currently this is being blocked by #94658, and the fix is ongoing at #94723 .

**Comment by knight42** [comment]
Now #95856 has been merged and apiserver no longer listen on insecure port 🎉 .

I am going to disable the insecure port in controller-manager and scheduler, but found that apiserver would access their insecure ports for health checks: https://github.com/kubernetes/kubernetes/blob/8b59fe9612ac36e0de8603aa6ca7a9b47eb122a5/pkg/registry/core/rest/storage_core.go#L344-L347 and it looks like we still grab metrics from the insecure ports in tests, e.g. https://github.com/kubernetes/kubernetes/blob/8b59fe9612ac36e0de8603aa6ca7a9b47eb122a5/test/e2e/framework/metrics/metrics_grabber.go#L199

I am not sure how to deal with these cases, any suggestion?

**Comment by liggitt** [comment]
for the health checks, see comment on https://github.com/kubernetes/kubernetes/pull/95522#issuecomment-708633054

**Comment by knight42** [comment]
@liggitt Thanks! looks like we could migrate the health checks first.

**Comment by knight42** [comment]
Now the remaining problem is how should we fetch metrics from controller-manager and scheduler. I have two options in mind for the time being:

1. make the insecure port a read-only port, and only expose basic read-only services on this port like what kubelet does.
2. completely disable the insecure port and only listen on the secure port.

Which one is more desired? Or do we have better alternative?

**Comment by liggitt** [comment]
> completely disable the insecure port and only listen on the secure port.

That was my expectation. What are the issues with this approach?

**Comment by knight42** [comment]
> That was my expectation. What are the issues with this approach?

I am OK with this approach, I could start with it. but I am afraid this would break some tests that I don't know, and actually I have broken several tests after disabling the insecure port of apiserver: #95877 #95955. Do we need broader discussion first?

**Comment by MHBauer** [comment]
We can try to run more of the CI tests ahead of time, but I think it's forward progress to break things in the effort.

**Comment by sayanchowdhury** [comment]
Hi 👋🏽 , Bug Triage here. We're pretty late into code freeze for 1.20, going to bump this to 1.21. Thanks!

/milestone 1.21

**Comment by jqmichael** [comment]
For /healthz or /readyz of kube-apiserver, is below still the recommended approach?

> For item 3, there are already out-of-tree solutions available today, such as a healthz-only proxy which can serve the same API on the same port, and authenticates as a user that only has access to healthz.

**Comment by liggitt** [comment]
#95856 dropped API server support for the insecure port in 1.20, and only allows apiserver invocations that set the flag to set it to `0`

/close

> For /healthz or /readyz of kube-apiserver, is below still the recommended approach?
> 
> > For item 3, there are already out-of-tree solutions available today, such as a healthz-only proxy which can serve the same API on the same port, and authenticates as a user that only has access to healthz.

The recommended approach is to allow anonymous requests to /healthz or /readyz.
