### ISSUE TITLE
Moving apiserver_request metrics to stable status

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#91536]
apiserver_request (total, latency histogram) metrics are likely the two most important metrics emitted by the kube-apiserver, aggregator, and aggregated-apiserver binaries. https://github.com/kubernetes/kubernetes/issues/76302 has been open for a year regarding some of the issues that have been ongoing problems. I want to open up a discussion on:

(1) cleaning this metric up so that it can be used reliably and consistently for many versions addressing as many of the cardinality concerns as possible
(2) explicitly defining a set of prescriptions for adding new metrics which may require joins to this very centrally important metric

These metrics are critically important because people use them for SLIs/SLOs. In fact we define SLOs for them here (https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md). Yet, due to the fact that people can inject arbitrary webhooks into the request flow process, we can never actually guarantee that the apiserver response time actually meets our stated objectives. 

Which brings us to the other dimension in which these metrics are flawed. They do not account for apiserver request processing time, exclusive of webhook processing time. As long as we do not break out internal request processing time, it is possible that arbitrary clusters will never be able to meet our internally stated service level objectives given the one metrics we provide.

**Comment by metalmatze** [comment]
The cardinality issues hit us here pretty badly, just one example for this, I suppose:
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/411

Soo :100: % agree.

**Comment by mkorbi** [comment]
Heyho @logicalhan  I wanted to check how it is going?
The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each relevant issue has a chance to be considered.

As the issue is tagged for 1.20, is it still planned for this release?

**Comment by logicalhan** [comment]
> Heyho @logicalhan I wanted to check how it is going?
> The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each relevant issue has a chance to be considered.
> 
> As the issue is tagged for 1.20, is it still planned for this release?

Ah, this is going to be slated for 1.21.

/milestone v1.21

**Comment by ams0** [comment]
Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (about 1 week from now).

As the Issue is tagged for 1.21, and the PRs linked are merged and marked for 1.21, can we close this one?

**Comment by logicalhan** [comment]
Yes! :)
