### ISSUE TITLE
Table-driven scheduler integration tests

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#91551]
There are some tests under folder `test/integration/scheduler` that don't quite follow the [Golang table-driven](https://github.com/golang/go/wiki/TableDrivenTests) test style. Here are some symptoms:

- no `t.Run()` under `for _, test := range tests` loop ([good example](https://github.com/kubernetes/kubernetes/blob/0891f69f5ec27cdbcb6336ce3cfe6efdcc1d1e05/test/integration/scheduler/predicates_test.go#L1005-L1006), [bad example](https://github.com/kubernetes/kubernetes/blob/0891f69f5ec27cdbcb6336ce3cfe6efdcc1d1e05/test/integration/scheduler/predicates_test.go#L821-L822))
- unnecessary `t.Logf("===Running test")` - with t.Run() as a sub-test, Golang already dumps test.name to the test output. ([bad example](https://github.com/kubernetes/kubernetes/blob/0891f69f5ec27cdbcb6336ce3cfe6efdcc1d1e05/test/integration/scheduler/preemption_test.go#L594))

/sig scheduling
/kind cleanup
/good-first-issue

**Comment by knabben** [comment]
Hi, can I help in this refactoring?

**Comment by Huang-Wei** [comment]
Thanks @knabben .

/remove-good-first-issue

**Comment by knabben** [comment]
@Huang-Wei can this be closed, the PRs were already merged.

**Comment by Huang-Wei** [comment]
Thanks @knabben .
