### ISSUE TITLE
Add new types for the Events

### ISSUE THREAD

**Issue by painhardcore** [kubernetes/kubernetes#91552]
**What would you like to be added**:
more levels for instrument events flow like:

Info, Critical, Error
**Why is this needed**:
Wanted to reuse https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/staging/src/k8s.io/client-go/tools/record/event.go#L88
But it's matched by the constants
https://github.com/kubernetes/client-go/blob/f099a72e140ab46a70ceb9337c75802c3a2be045/tools/record/util/util.go#L29

**Comment by painhardcore** [comment]
Is there a way to make validation optional?

**Comment by painhardcore** [comment]
@caesarxuchao 🙂

**Comment by painhardcore** [comment]
@caesarxuchao any comments about this issue?

**Comment by painhardcore** [comment]
@fedebongio maybe you can assign another member of the responsible team?

**Comment by painhardcore** [comment]
@fedebongio @caesarxuchao

**Comment by painhardcore** [comment]
2yo mark is achieved 🥇

**Comment by deads2k** [comment]
Validation for events only allows two levels: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/events.go#L56

The matching client-side code prevents unnecessary API validation failures.  Given breadth of impact, changing the set of allowed warnings is unlikely to progress as an issue, though https://github.com/kubernetes/enhancements could provide a venue to pitch for increasing the allows values.

/close
