### ISSUE TITLE
kubectl sometimes get a <invalid> string in output CreationTimestamp column

### ISSUE THREAD

**Issue by xjtustt** [kubernetes/kubernetes#91565]
**What happened**:
I used [apiserver-builder](https://github.com/kubernetes-sigs/apiserver-builder-alpha) v1.17 to extend a rest resource for apiserver. In the Get()/List() method I added the `CreationTimestamp` like this:
`<resourceInstanceName>.ObjectMeta.CreationTimestamp = metav1.Now()`.
In kubernetes 1.14 and 1.16 the output is as I expected like:
```
NAME             AGE
<resourceName>       0s
<resourceName>   0s
```
But in kubernetes 1.17, **sometimes** the out will show a `invalid` string like
```
NAME             AGE
<resourceName>       <invalid>
<resourceName>   <invalid>
```

**What you expected to happen**:
kubernetes 1.17 should always show same output with kubernetes 1.14 and 1.16

**How to reproduce it (as minimally and precisely as possible)**:
This issue only appears intermittently.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
- Kernel (e.g. `uname -a`):
Linux ocp44x-inf 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yue9944882** [comment]
can you reproduce w/ flag `-v8` and paste your output to us? can't find any related code printing  `<invalid>` in the codebase..

**Comment by xjtustt** [comment]
@yue9944882 
```
[root@ocp44x-inf ~]# k get meteringreport -v=8
I0601 08:57:45.870728   13936 loader.go:375] Config loaded from file:  /root/auth/kubeconfig
I0601 08:57:45.880228   13936 round_trippers.go:420] GET https://api.ocp44x.cp.fyre.ibm.com:6443/apis/metering.ibm.com/v1/namespaces/ibm-common-services/meteringreports?limit=500
I0601 08:57:45.880260   13936 round_trippers.go:427] Request Headers:
I0601 08:57:45.880265   13936 round_trippers.go:431]     Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json
I0601 08:57:45.880270   13936 round_trippers.go:431]     User-Agent: kubectl/openshift (linux/amd64) kubernetes/2576e48
I0601 08:57:45.892142   13936 round_trippers.go:446] Response Status: 200 OK in 11 milliseconds
I0601 08:57:45.892165   13936 round_trippers.go:449] Response Headers:
I0601 08:57:45.892169   13936 round_trippers.go:452]     Audit-Id: 230ee20a-5316-443a-a0f6-754525315b0f
I0601 08:57:45.892173   13936 round_trippers.go:452]     Content-Type: application/json
I0601 08:57:45.892176   13936 round_trippers.go:452]     Date: Mon, 01 Jun 2020 15:57:52 GMT
I0601 08:57:45.892179   13936 round_trippers.go:452]     Content-Length: 774
I0601 08:57:45.892210   13936 request.go:1017] Response Body: {"kind":"MeteringReportList","apiVersion":"metering.ibm.com/v1","metadata":{"selfLink":"/apis/metering.ibm.com/v1/namespaces/ibm-common-services/meteringreports"},"items":[{"metadata":{"name":"fullreport","selfLink":"/apis/metering.ibm.com/v1/namespaces/ibm-common-services/meteringreports/fullreport","creationTimestamp":"2020-06-01T15:57:52Z"},"spec":{"name":"fullreport","description":"use -n meteringreport-allns to get all namespaces report data"},"status":{}},{"metadata":{"name":"workloadreport","selfLink":"/apis/metering.ibm.com/v1/namespaces/ibm-common-services/meteringreports/workloadreport","creationTimestamp":"2020-06-01T15:57:52Z"},"spec":{"name":"workloadreport","description":"use -n meteringreport-allns to get all namespaces report data"},"status":{}}]}
I0601 08:57:45.892813   13936 table_printer.go:44] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table
I0601 08:57:45.892898   13936 table_printer.go:44] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table
NAME             AGE
fullreport       <invalid>
workloadreport   <invalid>
```

**Comment by knight42** [comment]
@xjtustt this seems to be a clock drift issue. 
you receive the response at `08:57:45.892210`, but the creationTimestamp shows that your report items was created at `2020-06-01T15:57:52Z` which I guess is `08:57:52` in your local time.  Therefore the duration turns out to be negative and kubectl display it as `<invalid>`.

**Comment by yue9944882** [comment]
> Date: Mon, 01 Jun 2020 15:57:52 GMT

@xjtustt can you check if the time zone is properly configured for your apiserver (or its deployed machine)? note that the `creationTimestamp` always uses utc timestamp.

**Comment by xjtustt** [comment]
@yue9944882 @knight42 
Yes, I found that the apiserver machine use PDT time,
```
[root@ocp44x-inf ~]# date
Mon Jun  1 22:51:43 PDT 2020
```
And the `creationTimestamp` use GMT time so the duration turns to a negative value.
The strange thing is that why this can be worked on kubernetes 1.16 and 1.14?
