### ISSUE TITLE
[failing test] "Pod Container Status should never report success for a pending container" hangs and times out KIND jobs

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#91579]
I've checked some jobs that timed out and something is odd with the test

```
[k8s.io] [sig-node] Pods Extended
^[[90mtest/e2e/framework/framework.go:592^[[0m
  [k8s.io] Pod Container Status
  ^[[90mtest/e2e/framework/framework.go:592^[[0m
    should never report success for a pending container
```

Check the durations in

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88196/pull-kubernetes-e2e-kind/1266095722265055235/build-log.txt
```
[32m• [SLOW TEST:3484.128 seconds][0m
[k8s.io] [sig-node] Pods Extended
[90mtest/e2e/framework/framework.go:592[0m
  [k8s.io] Pod Container Status
  [90mtest/e2e/framework/framework.go:592[0m
    should never report success for a pending container
    [90mtest/e2e/node/pods.go:219[0m
```
```
May 28 21:05:05.238: INFO: Pod pod-submit-status-0-7 on node kind-worker2 timings total=56m0.34898024s t=1.832s run=0s execute=0s
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91535/pull-kubernetes-e2e-kind/1266050429549023233/build-log.txt
```
[32m• [SLOW TEST:3376.269 seconds][0m
[k8s.io] [sig-node] Pods Extended
[90mtest/e2e/framework/framework.go:592[0m
  [k8s.io] Pod Container Status
  [90mtest/e2e/framework/framework.go:592[0m
    should never report success for a pending container
    [90mtest/e2e/node/pods.go:219[0m
```

```
May 28 18:08:32.338: INFO: Pod pod-submit-status-0-13 on node kind-worker2 timings total=54m38.072272958s t=1.751s run=0s execute=0s
```

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/pull/91491#issuecomment-635651958_

**Comment by aojea** [comment]
/cc @BenTheElder @wojtek-t @liggitt 

@smarterclayton you have added this test, do you see any reason why this test is never finishing on KIND (Kubernetes in Docker)

i.e this is a recent occurence
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88196/pull-kubernetes-e2e-kind/1266264458729099265

The test never finish and the job times out

```
[32m• [SLOW TEST:3293.106 seconds][0m
```

it seems that one of the pods is stuck

> May 29 08:14:32.416: INFO: Pod pod-submit-status-2-12 on node kind-worker timings total=52m19.427066405s t=875ms run=0s execute=0s

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/91585 with debug info and a bound on how long we'll wait for pod events

**Comment by tedyu** [comment]
Looking at a timed out test, I noticed the 35 minute gap toward the end of the build log:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89155/pull-kubernetes-e2e-kind/1266582655445504000
```
May 30 04:50:20.707: INFO: Pod pod-submit-status-1-14 on node kind-worker2 timings total=10.019519452s t=1.196s run=0s execute=0s
May 30 05:25:17.491: INFO: Pod pod-submit-status-2-4 on node kind-worker2 timings total=36m25.229431893s t=1.812s run=0s execute=0s
```
For passing builds, there was no such gap in similar logs.
Also, similar log appeared at the early part of build log in the passing build.

**Comment by tedyu** [comment]
I was looking at a recent failure:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/91453/pull-kubernetes-e2e-kind/1266858347173253121/artifacts
```
-rw-r--r--@ 1 zyu  staff  69649091 May 30 18:48 k2-kubelet.log
```
The size of kubelet log from worker node 2 was at least 10 times the size of kubelet.log for passing test.

There were 1573 occurrences of log lines in the following form:
```
May 30 23:10:00 kind-worker2 kubelet[673]: E0530 23:10:00.780763     673 remote_runtime.go:140] StopPodSandbox "719efe5645245b614ce69780ebdff7be982390d5551ad594ce39c84ff8450694" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
May 30 23:10:00 kind-worker2 kubelet[673]: E0530 23:10:00.780886     673 kuberuntime_manager.go:892] Failed to stop sandbox {"containerd" "719efe5645245b614ce69780ebdff7be982390d5551ad594ce39c84ff8450694"}
May 30 23:10:00 kind-worker2 kubelet[673]: E0530 23:10:00.780951     673 kubelet_pods.go:1183] Failed killing the pod "pod-submit-status-0-9": failed to "KillPodSandbox" for "57b7c2cf-1523-4d5e-ab86-2ba27b45a008" with KillPodSandboxError: "rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```
1554 occurrences for kubelet.log on worker node 1.
```
-rw-r--r--@ 1 zyu  staff  5099478 May 30 18:59 pass-k2-kubelet.log
```
There were only 233 occurrences for the above kubelet.log from a passing e2e-kind test run.

**Comment by BenTheElder** [comment]
probably not related but we did just change containerd versions quite a bit
due to an unrelated issue
https://github.com/kubernetes-sigs/kind/commit/ca0dde47d9597ade08db2cce5e2dd08f60f318cd

this kinda looks like the CI hosts being resource starved. might try
bumping the CPU req in the kind jobs (currently generally 2CPU), also
considering using memory backed emptydir for the docker storage in those
jobs (and hence most of what kind is doing) for some I/O isolation vs other
jobs ..

**Comment by tedyu** [comment]
In the corresponding containerd log:
```
May 30 23:10:19 kind-worker2 containerd[124]: time="2020-05-30T23:10:19.019821211Z" level=error msg="Failed to handle backOff event &TaskExit{ContainerID:719efe5645245b614ce69780ebdff7be982390d5551ad594ce39c84ff8450694,ID:719efe5645245b614ce69780ebdff7be982390d5551ad594ce39c84ff8450694,Pid:184815,ExitStatus:137,ExitedAt:2020-05-30 23:05:56.903075821 +0000 UTC,XXX_unrecognized:[],} for 719efe5645245b614ce69780ebdff7be982390d5551ad594ce39c84ff8450694" error="failed to handle sandbox TaskExit event: failed to stop sandbox: unknown error after kill: runc did not terminate sucessfully: lstat /sys/fs/cgroup/devices/kubepods/burstable/pod57b7c2cf-1523-4d5e-ab86-2ba27b45a008/719efe5645245b614ce69780ebdff7be982390d5551ad594ce39c84ff8450694: no such file or directory\n: unknown"
```
There was similar log line from journal.log
A brief search within the containerd log didn't reveal who deleted the file.

**Comment by tedyu** [comment]
From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91453/pull-kubernetes-e2e-kind/1266858347173253121/build-log.txt 
```
^[[90mtest/e2e/storage/utils/framework.go:23^[[0m
  [Driver: local][LocalVolumeType: dir]
  ^[[90mtest/e2e/storage/in_tree_volumes.go:56^[[0m
    [Testpattern: Pre-provisioned PV (default fs)] subPath
    ^[[90mtest/e2e/storage/testsuites/base.go:115^[[0m
      ^[[91m^[[1mshould support non-existent path [It]^[[0m
      ^[[90mtest/e2e/storage/testsuites/subpath.go:191^[[0m

      ^[[91mMay 30 23:09:31.282: Unexpected error:
          <*errors.errorString | 0xc00013ddd0>: {
              s: "timed out waiting for the condition",
          }
          timed out waiting for the condition
      occurred^[[0m

      test/e2e/storage/utils/host_exec.go:110
^[[90m------------------------------^[[0m
{"msg":"FAILED [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (default fs)] subPath should support non-existent path","total":-1,"completed":29,"skipped":186,"failed":2,"failures":["[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (filesystem volmode)] volumeMode should not mount / map unused volumes in a pod","[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (default fs)] subPath should support non-existent path"]}
```

**Comment by liggitt** [comment]
With the added debugging, seeing *lots* of failures for this:

* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1267635544741908481
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1267615032988930051
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1267609244828438528

**Comment by liggitt** [comment]
Digging into https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind/1267615032988930051

The pod pod-submit-status-0-4 was never deleted:
```
01:00:34.847: timed out waiting for watch events for pod-submit-status-0-4
```

Events:
* `Jun  2 01:00:54.440: INFO: At 2020-06-02 00:55:33 +0000 UTC - event for pod-submit-status-0-4: {default-scheduler } Scheduled: Successfully assigned pods-7342/pod-submit-status-0-4 to kind-worker2`
* `Jun  2 01:00:54.440: INFO: At 2020-06-02 00:55:35 +0000 UTC - event for pod-submit-status-0-4: {kubelet kind-worker2} Created: Created container busybox`
* `Jun  2 01:00:54.440: INFO: At 2020-06-02 00:55:35 +0000 UTC - event for pod-submit-status-0-4: {kubelet kind-worker2} Pulled: Container image "docker.io/library/busybox:1.29" already present on machine`
* `Jun  2 01:00:54.440: INFO: At 2020-06-02 00:55:36 +0000 UTC - event for pod-submit-status-0-4: {kubelet kind-worker2} Started: Started container busybox`

Searching the [kubelet log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91651/pull-kubernetes-e2e-kind/1267615032988930051/artifacts/logs/kind-worker2/kubelet.log) for "pod-submit-status-0-4" shows repeated errors:

* `Jun 02 00:56:13 kind-worker2 kubelet[677]: E0602 00:56:13.036013     677 remote_runtime.go:563] ReopenContainerLog "583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592" from runtime service failed: rpc error: code = Unknown desc = failed to create and open log file: open /var/log/pods/pods-7342_pod-submit-status-0-4_553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/busybox/0.log: no such file or directory`
* `Jun 02 00:56:13 kind-worker2 kubelet[677]: E0602 00:56:13.036055     677 container_log_manager.go:210] Container "583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592" log "/var/log/pods/pods-7342_pod-submit-status-0-4_553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/busybox/0.log" doesn't exist, reopen container log failed: rpc error: code = Unknown desc = failed to create and open log file: open /var/log/pods/pods-7342_pod-submit-status-0-4_553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/busybox/0.log: no such file or directory`
* `Jun 02 00:56:15 kind-worker2 kubelet[677]: E0602 00:56:15.717463     677 cri_stats_provider.go:591] Unable to fetch container log stats for path /var/log/pods/pods-7342_pod-submit-status-0-4_553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/busybox: failed command 'du' ($ nice -n 19 du -x -s -B 1) on path /var/log/pods/pods-7342_pod-submit-status-0-4_553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/busybox with error exit status 1`

These repeat until the end of the log. None of the other test pods from the test log these errors.

**Comment by liggitt** [comment]
looking in the [containerd log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91651/pull-kubernetes-e2e-kind/1267615032988930051/artifacts/logs/kind-worker2/containerd.log):

* `Jun 02 00:55:34 kind-worker2 containerd[128]: time="2020-06-02T00:55:34.029936308Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:pod-submit-status-0-4,Uid:553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c,Namespace:pods-7342,Attempt:0,}"
`
* `Jun 02 00:55:35 kind-worker2 containerd[128]: time="2020-06-02T00:55:35.093627544Z" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:pod-submit-status-0-4,Uid:553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c,Namespace:pods-7342,Attempt:0,} returns sandbox id \"a0bdea1f1a9ee6c2859f30cbcef3820fe0271ef8767e5a029b3a33fb8cc4d72c\""
`
* `Jun 02 00:55:36 kind-worker2 containerd[128]: time="2020-06-02T00:55:36.149486402Z" level=error msg="add cg to OOM monitor" error="open /sys/fs/cgroup/memory/kubepods/burstable/pod553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592/memory.oom_control: no such file or directory"
`
* `Jun 02 00:55:36 kind-worker2 containerd[128]: time="2020-06-02T00:55:36.249578751Z" level=error msg="Failed to handle exit event &TaskExit{ContainerID:583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592,ID:583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592,Pid:195311,ExitStatus:137,ExitedAt:2020-06-02 00:55:36.131145685 +0000 UTC,XXX_unrecognized:[],} for 583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592" error="failed to handle container TaskExit event: failed to stop container: unknown error after kill: runc did not terminate sucessfully: lstat /sys/fs/cgroup/devices/kubepods/burstable/pod553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592: no such file or directory\n: unknown"
`
* ... this repeats for a while ...
* `Jun 02 00:56:43 kind-worker2 containerd[128]: time="2020-06-02T00:56:43.981571000Z" level=error msg="Failed to handle backOff event &TaskExit{ContainerID:a0bdea1f1a9ee6c2859f30cbcef3820fe0271ef8767e5a029b3a33fb8cc4d72c,ID:a0bdea1f1a9ee6c2859f30cbcef3820fe0271ef8767e5a029b3a33fb8cc4d72c,Pid:194950,ExitStatus:137,ExitedAt:2020-06-02 00:55:36.182322799 +0000 UTC,XXX_unrecognized:[],} for a0bdea1f1a9ee6c2859f30cbcef3820fe0271ef8767e5a029b3a33fb8cc4d72c" error="failed to handle sandbox TaskExit event: failed to stop sandbox: unknown error after kill: runc did not terminate sucessfully: lstat /sys/fs/cgroup/devices/kubepods/burstable/pod553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/a0bdea1f1a9ee6c2859f30cbcef3820fe0271ef8767e5a029b3a33fb8cc4d72c: no such file or directory\n: unknown"
`
* ...
* `Jun 02 00:59:58 kind-worker2 containerd[128]: time="2020-06-02T00:59:58.004849896Z" level=error msg="Failed to handle backOff event &TaskExit{ContainerID:583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592,ID:583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592,Pid:195311,ExitStatus:137,ExitedAt:2020-06-02 00:55:36.131145685 +0000 UTC,XXX_unrecognized:[],} for 583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592" error="failed to handle container TaskExit event: failed to stop container: unknown error after kill: runc did not terminate sucessfully: lstat /sys/fs/cgroup/devices/kubepods/burstable/pod553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592: no such file or directory\n: unknown"`

**Comment by wojtek-t** [comment]
I looked into the other failure, and there one of the pods never started. But again - it seems to be related to the containerd (or some Kubelet-containerd interactions):
```
...
Jun  2 02:36:31.217: INFO: At 2020-06-02 02:31:32 +0000 UTC - event for pod-submit-status-0-5: {kubelet kind-worker} Pulled: Container image "docker.io/library/busybox:1.29" already present on machine
Jun  2 02:36:31.217: INFO: At 2020-06-02 02:31:33 +0000 UTC - event for pod-submit-status-0-5: {kubelet kind-worker} Failed: Error: failed to start containerd task "busybox": OCI runtime start failed: container process is already dead: unknown
```

For now - I don't see anything that suggests problems with delivering watch events.

**Comment by smarterclayton** [comment]
Yeah this test fails usually due to failures in CRI.  We found 2-3 bugs in docker while rolling it out, 1-2 containerd / crio bugs.

**Comment by liggitt** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=kind&xtext=timed%20out%20waiting%20for%20the%20condition%7Cstdin%20closed%7Ckubectl%7CGave%20up%20after%20waiting%7Cerror%20waiting%20for%20deployment&xtest=Volume%7Cnegotiate%20watch%7CNodeConformance shows how common the test failure is. It was occurring before 6/1, it just wasn't attributed correctly

**Comment by liggitt** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=kind#b05025d9cb729f714b09 is interesting... the containerd logs show the same error:

> May 27 03:28:05 kind-worker2 containerd[125]: time="2020-05-27T03:28:05.678487798Z" level=error msg="Failed to handle exit event &TaskExit{ContainerID:95794ab7e562c322e36a86ad7105469be95514ffde22b303b24214c5743fb13d,ID:95794ab7e562c322e36a86ad7105469be95514ffde22b303b24214c5743fb13d,Pid:20149,ExitStatus:137,ExitedAt:2020-05-27 03:28:05.270358036 +0000 UTC,XXX_unrecognized:[],} for 95794ab7e562c322e36a86ad7105469be95514ffde22b303b24214c5743fb13d" error="failed to handle container TaskExit event: failed to stop container: unknown error after kill: runc did not terminate successfully: lstat /sys/fs/cgroup/devices/kubepods/besteffort/podf16a275a-abf1-4533-8c2e-8cfc94f4780d/95794ab7e562c322e36a86ad7105469be95514ffde22b303b24214c5743fb13d: no such file or directory\n: unknown"

And appears to have started right at 5/27

**Comment by liggitt** [comment]
the CNI bump to 0.8.6 also merged the evening of 5/26... does that impact kind?

**Comment by liggitt** [comment]
oh... kind upgraded containerd the evening of 5/26... that seems very likely to be related - https://github.com/kubernetes-sigs/kind/pull/1599

**Comment by aojea** [comment]
> the CNI bump to 0.8.6 also merged the evening of 5/26 in [f91c1ef](https://github.com/kubernetes/kubernetes/commit/f91c1ef60e808ed4070619e0f7c53849757cf26c)... does that impact kind?

kind consumes it directly we upgraded it earlier

> oh... kind upgraded containerd the evening of 5/26... that seems very likely to be related - kubernetes-sigs/kind#1599

it was rolled back some days later https://github.com/kubernetes-sigs/kind/pull/1635

**Comment by liggitt** [comment]
> it was rolled back some days later [kubernetes-sigs/kind#1635](https://github.com/kubernetes-sigs/kind/pull/1635)

but to v1.3.4-12-g1e902b2d, not the original version (v1.3.3-14-g449e9269)

looking at that delta now

**Comment by liggitt** [comment]
containerd commits in that range that stood out:

* https://github.com/containerd/containerd/commit/c95854caca1432862a8379a7dfd261de29b99a9a
* https://github.com/containerd/containerd/commit/d70d0f1a993af68aa1f7a066f4dc040a32580adb
* https://github.com/containerd/containerd/commit/910dfcd727371578550edd2d5356f82c6c174228
* https://github.com/containerd/containerd/commit/e655edce10c97b691e32e59d9360b955bf79eca2

**Comment by BenTheElder** [comment]
Minor note: the rollback wasn't a direct rollback because it was done due to an issue known to be in 1.4 and not in 1.3 that does not affect CI at all (and honestly the host OS [gLinux] is at fault for that one).

**Comment by liggitt** [comment]
kind reverted to v1.3.3-14-g449e9269 in https://github.com/kubernetes-sigs/kind/pull/1649 around 2am

will watch https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=kind&test=Pod%20Container%20Status%20should%20never%20report%20success%20for%20a%20pending%20container to see if signal clears up

**Comment by liggitt** [comment]
https://prow.k8s.io/?job=pull-kubernetes-e2e-kind looks greener already:

`Success rate over time: 3h: 75%, 12h: 53%, 48h: 36%`

![image](https://user-images.githubusercontent.com/980082/83653057-5269f600-a589-11ea-9697-4aa29647a105.png)

**Comment by liggitt** [comment]
This can probably be closed out, but should spawn an issue for containerd.

**Comment by aojea** [comment]
/close

> This can probably be closed out, but should spawn an issue for containerd that we'll need to drive

This was a tough one :smile:

**Comment by fuweid** [comment]
I guess that the root cause is about oomkiller.

Based on the log from [containerd log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91651/pull-kubernetes-e2e-kind/1267615032988930051/artifacts/logs/kind-worker2/containerd.log)

When that `/bin/false` pod start, but it has been killed.

```
02 00:55:36 kind-worker2 containerd[128]: time="2020-06-02T00:55:36.149486402Z" level=error msg="add cg to OOM monitor" error="open /sys/fs/cgroup/memory/kubepods/burstable/pod553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592/memory.oom_control: no such file or directory"

Jun 02 00:55:36 kind-worker2 containerd[128]: time="2020-06-02T00:55:36.157731626Z" level=info msg="StartContainer for \"583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592\" returns successfully"

Jun 02 00:55:36 kind-worker2 containerd[128]: time="2020-06-02T00:55:36.158443064Z" level=info msg="TaskExit event &TaskExit{ContainerID:583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592,ID:583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592,Pid:195311,ExitStatus:137,ExitedAt:2020-06-02 00:55:36.131145685 +0000 UTC,XXX_unrecognized:[],}"
```

The log is interesting because that `StartContainer` does successfully but we received the exit event with exit status 137. If I understand correctly, `/bin/false` return exit status 1 and 137 is like oom killer.

And the tricky part  is first log line above. `/sys/fs/cgroup/memory/kubepods/burstable/pod553b0f48-8dbd-4ff6-8e4c-289a0a9b7f5c/583c17764ed521bc6e30482e10faff6f0cda6d5351cfdb9b942b905df0eec592/memory.oom_control` is not found.

The containerd `v1.4.0-beta-6312b52d` is using `1.0.0~rc10` runC. runC might destroy the cgroup path during initialization at two places
* https://github.com/opencontainers/runc/blob/v1.0.0-rc10/libcontainer/process_linux.go#L304-L310
* https://github.com/opencontainers/runc/blob/v1.0.0-rc10/libcontainer/process_linux.go#L353-L358

When cgroup path has been deleted, the `runc kill --all` will buggy us because it doesn't check the status.

```go
// https://github.com/opencontainers/runc/blob/v1.0.0-rc10/libcontainer//container_linux.go#L381

func (c *linuxContainer) Signal(s os.Signal, all bool) error {
        if all {
                return signalAllProcesses(c.cgroupManager, s). <----- no check status 
        }
        status, err := c.currentStatus()
        if err != nil {
                return err
        }
        // to avoid a PID reuse attack
        if status == Running || status == Created || status == Paused {
                if err := c.initProcess.signal(s); err != nil {
                        return newSystemErrorWithCause(err, "signaling init process")
                }
                return nil
        }
        return newGenericError(fmt.Errorf("container not running"), ContainerNotRunning)
}

// https://github.com/opencontainers/runc/blob/v1.0.0-rc10/libcontainer/init_linux.go#L470

// signalAllProcesses freezes then iterates over all the processes inside the
// manager's cgroups sending the signal s to them.
// If s is SIGKILL then it will wait for each process to exit.
// For all other signals it will check if the process is ready to report its
// exit status and only if it is will a wait be performed.
func signalAllProcesses(m cgroups.Manager, s os.Signal) error {
        var procs []*os.Process
        if err := m.Freeze(configs.Frozen); err != nil {
                logrus.Warn(err).  <------------ just warning
        }
        pids, err := m.GetAllPids(). <----- check devices path and oops
        if err != nil {
                m.Freeze(configs.Thawed)
                return err
        }
        for _, pid := range pids {
                p, err := os.FindProcess(pid)
                if err != nil {
                        logrus.Warn(err)
                        continue
                }
                procs = append(procs, p)
                if err := p.Signal(s); err != nil {
                        logrus.Warn(err)
                }
        }
```

I didn't know why runC destroys the cgroupPath. No clue yet.
But I think runC should cover the cgrouppath-404 case.
Hope it can help

cc @dims @liggitt @AkihiroSuda

**Comment by AkihiroSuda** [comment]
https://github.com/opencontainers/runc/pull/2338 might fix the issue, though the PR is originally intended for cgroup2+systemd.
