### ISSUE TITLE
Disable unused filesystems in Kubernetes

### ISSUE THREAD

**Issue by Mishra-Akash** [kubernetes/kubernetes#91609]
Is there any way where we can disable mounting of FAT/squashfs/cramfs/hfsplus/jffs2 inside a container in Kubernetes. 

This is a security requirement to comply with.

**Comment by Mishra-Akash** [comment]
Security Audit

**Comment by tedyu** [comment]
Can you give a bit more detail on the security requirement ?

**Comment by Mishra-Akash** [comment]
I have to ensure disabling of the unused filesystems as reported in System CIS-CAT report inside my container by anymean.  
Refer https://secscan.acron.pl/centos7/1/1/1.
