### ISSUE TITLE
The node was low on resource: ephemeral-storage, and pods were evicted

### ISSUE THREAD

**Issue by windayski** [kubernetes/kubernetes#91600]
In my cluster, some of the pods were evicted, and the description shows it's due to lack of ephemeral-storage.
I checked the disk space of worker nodes. There is still plenty of disk space. But the kubelet logs showed the kubelet is still trying to evict pods. It's quite strange. Why?

```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Created         18m (x2 over 18m)  kubelet, mgt04     Created container calico-node
  Normal   Started         18m (x2 over 18m)  kubelet, mgt04     Started container calico-node
  Normal   Killing         18m (x2 over 18m)  kubelet, mgt04     Stopping container calico-node
  Warning  Evicted         18m                kubelet, mgt04     The node was low on resource: ephemeral-storage. Container calico-node was using 92Ki, which exceeds its request of 0.
```
`kubectl describe node mgt04`

```
Capacity:
 cpu:                16
 ephemeral-storage:  41218252Ki
 hugepages-2Mi:      0
 memory:             49450604Ki
 pods:               60
Allocatable:
 cpu:                15400m
 ephemeral-storage:  30732492Ki
 hugepages-2Mi:      0
 memory:             48426316Ki
 pods:               60
System Info:
 Machine ID:                 a87d37f9c4d74e9eb672b97b5dd0c818
 System UUID:                d7c5f9f9-c017-42ee-9aa3-0e9d79ac4b3e
 Boot ID:                    1fc3d156-d529-4b28-8695-da0a048a4bc5
 Kernel Version:             5.0.0-29-generic
 OS Image:                   Ubuntu 18.04.2 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.8
 Kubelet Version:            v1.14.3
 Kube-Proxy Version:         v1.14.3
Non-terminated Pods:         (1 in total)
  Namespace                  Name                CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                ------------  ----------  ---------------  -------------  ---
  kube-system                kube-proxy-mgt04    150m (0%)     500m (3%)   64M (0%)         2G (4%)        67d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                150m (0%)  500m (3%)
  memory             64M (0%)   2G (4%)
  ephemeral-storage  0 (0%)     0 (0%)
Events:
  Type     Reason                Age                    From            Message
  ----     ------                ----                   ----            -------
  Warning  EvictionThresholdMet  2m5s (x8411 over 23h)  kubelet, mgt04  Attempting to reclaim ephemeral-storage
```

Check disk space. There is still plenty of disk space.
```
root@mgt04:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             24G  4.0K   24G   1% /dev
tmpfs           4.8G  1.6M  4.8G   1% /run
/dev/vda1        40G  9.0G   29G  24% /
tmpfs            24G   12K   24G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            24G     0   24G   0% /sys/fs/cgroup
/dev/vdb         79G   20G   55G  27% /data
overlay          79G   20G   55G  27% /data/docker/overlay2/6ddd762cfc0bcc76acd5e8b014ee253aa3f5e2bfaa723f8983a58b8040941136/merged
shm              64M     0   64M   0% /data/docker/containers/b1ba326ac4627fb844ca2a4db8e4f7a7642a6fa4b97a2b0f33e50ea0df9b4146/mounts/shm
overlay          79G   20G   55G  27% /data/docker/overlay2/3c8d943ab61033fc23c52093f04917d2ea12d9c0935ba2a3976ccdba440df4f3/merged
shm              64M     0   64M   0% /data/docker/containers/7dde45b9d3364c5db49db7b255205e9a5b8dd90fd2cc7e21dc26b8e8cce756e2/mounts/shm
overlay          79G   20G   55G  27% /data/docker/overlay2/a18f902afd77bddeaf06aff4e7ad68afa45b8b5ce9eab051c7d82e4e21a5993b/merged
tmpfs           4.8G     0  4.8G   0% /run/user/0
```

Kubelet logs:
```
May 14 15:25:59 mgt06 kubelet[2974181]: I0514 15:25:59.448341 2974181 setters.go:73] Using node IP: "172.30.30.136"
May 14 15:26:01 mgt06 kubelet[2974181]: W0514 15:26:01.437227 2974181 eviction_manager.go:333] eviction manager: attempting to reclaim ephemeral-storage
May 14 15:26:01 mgt06 kubelet[2974181]: I0514 15:26:01.437326 2974181 eviction_manager.go:344] eviction manager: must evict pod(s) to reclaim ephemeral-storage
May 14 15:26:01 mgt06 kubelet[2974181]: I0514 15:26:01.437360 2974181 eviction_manager.go:362] eviction manager: pods ranked for eviction: kube-proxy-mgt06_kube-system(bd86a2d0d2a9741d930c9e069eb1792f)
May 14 15:26:01 mgt06 kubelet[2974181]: E0514 15:26:01.437421 2974181 eviction_manager.go:557] eviction manager: cannot evict a critical static pod kube-proxy-mgt06_kube-system(bd86a2d0d2a9741d930c9e069eb1792f)
May 14 15:26:01 mgt06 kubelet[2974181]: I0514 15:26:01.437436 2974181 eviction_manager.go:385] eviction manager: unable to evict any pods from the node
May 14 15:26:09 mgt06 kubelet[2974181]: I0514 15:26:09.463459 2974181 setters.go:73] Using node IP: "172.30.30.136"
May 14 15:26:11 mgt06 kubelet[2974181]: W0514 15:26:11.555406 2974181 eviction_manager.go:333] eviction manager: attempting to reclaim ephemeral-storage
May 14 15:26:11 mgt06 kubelet[2974181]: I0514 15:26:11.555490 2974181 eviction_manager.go:344] eviction manager: must evict pod(s) to reclaim ephemeral-storage
May 14 15:26:11 mgt06 kubelet[2974181]: I0514 15:26:11.555522 2974181 eviction_manager.go:362] eviction manager: pods ranked for eviction: kube-proxy-mgt06_kube-system(bd86a2d0d2a9741d930c9e069eb1792f)
May 14 15:26:11 mgt06 kubelet[2974181]: E0514 15:26:11.555585 2974181 eviction_manager.go:557] eviction manager: cannot evict a critical static pod kube-proxy-mgt06_kube-system(bd86a2d0d2a9741d930c9e069eb1792f)
May 14 15:26:11 mgt06 kubelet[2974181]: I0514 15:26:11.555606 2974181 eviction_manager.go:385] eviction manager: unable to evict any pods from the node
```

**Comment by tedyu** [comment]
1.14.3 is quite old.
Are you able to reproduce this using 1.18 ?

Thanks

**Comment by jofia** [comment]
I also encountered the same problem, the disk space is also very sufficient, please help us to see
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: ephemeral-storage. Container ebaogi-bff-app was using 34260Ki, which exceeds its request of 0. 
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/ebaogi-bff-app-955968dbb


Name:           ebaogi-report-app-5dbc89ff58-zqsn2
Namespace:      ebaogi
Priority:       0
Node:           xen15-142/
Start Time:     Thu, 09 Jul 2020 10:20:16 +0800
Labels:         app=ebaogi-report-app
                deploytime=2020-07-09-10-18-59-1594261139
                pod-template-hash=5dbc89ff58
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: ephemeral-storage. Container ebaogi-report-app was using 108488Ki, which exceeds its request of 0.

**Comment by ledroide** [comment]
Same issue here, using Kubernetes 1.19.3.
Happens even with pods that do not use EmptyDir volumes.
@windayski : why did you close the issue ? Could you solve it ?

**Comment by windayski** [comment]
@ledroide： Check your kubelet args `--eviction-minimum-reclaim `.  Maybe it's too large, so the kubelet would still reclaim the resource even if the resource is sufficient on this node.

**Comment by devopsteachpractice** [comment]
I see allocated resource for ephemeral storage limit is 0, hence if your pod try to accumulated any logs in the area it would get evicted. 

ephemeral-storage  0 (0%)     0 (0%)

**Comment by huylv** [comment]
@windayski, @devopsteachpractice: I'm still looking for answer to this issue. How do I troubleshoot and solve this?

**Comment by mac-chaffee** [comment]
That error can be confusing if your pod just so happened to be running on the same node as another pod which filled up the disk and was killed. Without any ephemeral-storage requests/limits, ALL pods can be considered for eviction even when only one pod is the main disk hogger.

If pod A fills up the disk (outside of a PV) and pod B is running on the same node and has written any data to disk outside of a PV, both pods could be killed. Kubelet inmediately reclaims the storage from killed pods, so when you go to check disk usage, it looks fine.

One solution is to enforce cluster-wide default limits for ephemeral-storage using a LimitRange. That way, if one pod exceeds its limit, it won't use up the whole disk and only that pod will be killed: https://kubernetes.io/docs/concepts/policy/limit-range/

Or if you are just a tenant of a larger kubernetes cluster and don't have that permission, just specifying requests/limits for ephemeral-storage for your own pods will greatly reduce your risk of being evicted for this reason.

**Comment by huylv** [comment]
Thank you very much, @mac-chaffee. I have added requests and limits for ephemeral-storage to the deployment and it has been stable for 2 weeks so far.

```
spec:
    containers:
        - ...
          resources:
            requests:
              ephemeral-storage: 2Gi
            limits:
              ephemeral-storage: 4Gi
```

One question is: how is it not evicted now when the limits are set to 4GB, but in the past it was evicted for requesting up to 200+GB of ephemeral-storage? It could have been evicted because of another pod on the same node, but at least that was the error message.

**Comment by chaoscreater** [comment]
> That error can be confusing if your pod just so happened to be running on the same node as another pod which filled up the disk and was killed. Without any ephemeral-storage requests/limits, ALL pods can be considered for eviction even when only one pod is the main disk hogger.
> 
> If pod A fills up the disk (outside of a PV) and pod B is running on the same node and has written any data to disk outside of a PV, both pods could be killed. Kubelet inmediately reclaims the storage from killed pods, so when you go to check disk usage, it looks fine.
> 
> One solution is to enforce cluster-wide default limits for ephemeral-storage using a LimitRange. That way, if one pod exceeds its limit, it won't use up the whole disk and only that pod will be killed: [kubernetes.io/docs/concepts/policy/limit-range](https://kubernetes.io/docs/concepts/policy/limit-range/)
> 
> Or if you are just a tenant of a larger kubernetes cluster and don't have that permission, just specifying requests/limits for ephemeral-storage for your own pods will greatly reduce your risk of being evicted for this reason.

Probably a dumb question, but if you define a LimitRange, it's namespace specific. If you evict the pods within that namespace and let it re-create, it will apply the new LimitRange. But the LimitRange applies to just that one namespace. So to enforce "cluster-wide" limits, wouldn't this mean you'd have to create LImitRange per namespace?
