### ISSUE TITLE
@kubernetes daemonsets

### ISSUE THREAD

**Issue by Ankur7890** [kubernetes/kubernetes#91605]
Hi Guys,

Is there a way to label kubernetes daemonsets? Do not want daemonset to run on specific node.

**Comment by liggitt** [comment]
See https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes for details on specifying a node selector to constrain which nodes a daemonset runs on

**Comment by Ankur7890** [comment]
> See https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes for details on specifying a node selector to constrain which nodes a daemonset runs on

Gone through the link, it seems that for newer version taint/toleration might help but about lower versions.

k8s version 1.4 or 1.5 something.

**Comment by liggitt** [comment]
node selectors are supported on all daemonset versions
