### ISSUE TITLE
JSON patch with kubectl has exponential time complexity for nesting depth of manifest

### ISSUE THREAD

**Issue by tapih** [kubernetes/kubernetes#91615]
**What happened**:

When updating a deeply nested CRD in a local k8s cluster with `kubectl apply`,
the command finishes after more than 5 minutes.
The CRD has a field like [`corev1.PodSpec`](https://godoc.org/k8s.io/api/core/v1#PodSpec).

I did a brief experiment for how the nesting depth of manifests affects computation time,
and found that JSON patch creation with `kubectl apply` has exponential time complexity for the depth.

**What you expected to happen**:

Finish updating deeply nested CRDs with `kubectl apply` in some seconds, at most 5s.

**How to reproduce it (as minimally and precisely as possible)**:

Please execute `kubectl apply -f https://gist.githubusercontent.com/tapih/f339a2d558cf49b0cd6320b7b2f1821b/raw/2fa11c4935f1976059c6517caef647115e1dcbda/crd.yaml` twice.
The second one will take too long to finish.

This is the detail of my experiment.

1. Create a `Foo` CRD project of which API version is `apiextensions.k8s.io/v1` with [kubebuilder](https://book.kubebuilder.io/quick-start.html).
2. Change the type definition of the CRD to have deeply nested slices.

```go
type FooSpec struct {
	// +optional
	T1 []T1 `json:"t1,omitempty"`
}

type T9 struct {
	// +optional
	T8 []T8 `json:"t8,omitempty"`
}

type T8 struct {
	// +optional
	T7 []T7 `json:"t7,omitempty"`
}

type T7 struct {
	// +optional
	T6 []T6 `json:"t6,omitempty"`
}

:

type T1 struct {
	// +optional
	Field string `json:"field"`
}
```

3. Run `make manifests` and create the CRD manifest.
4. Create a CRD object with `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml`.
5. Update the CRD object with `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml`.
6. Repeat this with incrementing the nesting depth of `FooSpec` like T1, T2, T3...T8.

The wall-clock time to finish the second `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml` was as follow:

```
...
T4 => 0.1s
T5 => 1.2s
T6 => 8.7s
T7 => 68s
T8 => 544s
```

**Anything else we need to know?**:

https://github.com/evanphx/json-patch/pull/87 has already resolved this issue.
However, [kubernetes/kubernetes/go.mod](https://github.com/kubernetes/kubernetes/blob/413bc1a1d238efb7c4ba9e3aac2c381c93295aec/go.mod#L239) at master `HEAD` does not take this fix.

https://github.com/kubernetes/kubectl/issues/698 is about the same problem.
However, it was closed without fixing this problem.

**Environment**:
- Kubernetes version:  
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Hardware: VM on Hyper-V
- OS: Ubuntu 18.04
- Kernel: 4.15.0-66-generic
- Install tools: kind v0.8.1

**Comment by vincepri** [comment]
@liggitt Should this issue be reopened given that the patch was reverted / never merged for older versions?

**Comment by liggitt** [comment]
yes, we can keep this open until the release branches are patched. json-patch just cut a v4.8.0 release we can use for those, opening PRs now.

**Comment by vincepri** [comment]
I noticed we're using `v0.0.0-20200808040245-162e5629780b` instead of the actual git tag `v4.8.0`. 

When I tried using the tag I got the error 
```
/Users/vince/go/src/sigs.k8s.io/cluster-api/go.mod:12: require github.com/evanphx/json-patch: reading https://proxy.golang.org/github.com/evanphx/json-patch/@v/v4.8.0.info: 410 Gone
        server response: not found: github.com/evanphx/json-patch@v4.8.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```

Unfortunately, even if we have a replace directive in controller-runtime, this won't be enough because controller-runtime doesn't generate any binary, all the projects using it (through kubebuilder and whatnot) will have to have the replace directive. To make things more complicated, CR also imports `gomodules.xyz/jsonpatch/v2 v2.1.0`, which requires `json-patch v4.5.0`.

I'll have to find some other way to get around this issue, or document it in a release for all users. Do you folks have any other idea?

**Comment by liggitt** [comment]
See https://github.com/evanphx/json-patch/pull/113
