### ISSUE TITLE
Support for metadata information in JWT token created by ServiceAccountToken controller

### ISSUE THREAD

**Issue by rnsv** [kubernetes/kubernetes#91610]
/sig auth
/sig api-machinery

**What would you like to be added**:
I would like the JWT token created by ServiceAccountToken controller to include optional labels from metadata

**Why is this needed**:
The JWT token created by ServiceAccountToken has namespace, pod name and sa name.  Adding metadata info like labels from the pod would help the relying party to get additional context information of the pod  
```
  ...
  "kubernetes.io": {
    "namespace": "test",
    "pod": {
      "name": "nginx-1237f43324-p4cdw",
      "uid": "6f0432ee4-bdda-4234-86a3-1b12346dabb9"
    },
    "serviceaccount": {
      "name": "nginx-sa",
      "uid": "d712369b-1271-45bd-224c-36babcde9fd2"
    }
  },
```

**Comment by liggitt** [comment]
name and uid are immutable and can be used to look up pod info if needed. it's not clear that copying mutable pod attributes into authentication token claims is desirable

**Comment by rnsv** [comment]
I understand your concern.  What I am looking for is some context around the jwt token presented by the pod.  For example, the cluster-id and the environment in which the Kubernetes is running.  
One possibility is to provide a static list of key-value as an option in the api server.  
e.g --service-account-additional-claims mapStringString

**Comment by liggitt** [comment]
is the issuer insufficient to identify the environment? custom claims configured per-environment aren't really what I would expect in a "standard" kubernetes service account credential

**Comment by rnsv** [comment]
In most traditional enterprises, the urls need to follow certain format, which makes it difficult to use the issuer url as way to identify cluster specific information
