### ISSUE TITLE
generic-garbage-collector can't cleanup clusterroles with managedFields set

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#91621]
**What happened**:
I have a custom resource which is a controller for a ClusterRole that uses a PSP. When I delete the CR in foreground mode, I see the following error in kube-controller-manager logs.

`E0601 04:41:02.733015       1 garbagecollector.go:314] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"rbac.authorization.k8s.io/v1", Kind:"Role", Name:"memcached-tzy37l", UID:"dbfa1c0a-7a09-4870-9d0e-e8793daa87b9", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:"memcached-sl5p3q"}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, deletingDependents:true, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:true, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"kubedb.com/v1alpha1", Kind:"Memcached", Name:"memcached-tzy37l", UID:"19c73d78-b0c8-404e-8548-00439fb2cc44", Controller:(*bool)(0xc001fddd19), BlockOwnerDeletion:(*bool)(0xc001fddd1a)}}}: roles.rbac.authorization.k8s.io "memcached-tzy37l" is forbidden: user "system:serviceaccount:kube-system:generic-garbage-collector" (groups=["system:serviceaccounts" "system:serviceaccounts:kube-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["policy"], Resources:["podsecuritypolicies"], ResourceNames:["memcached-db"], Verbs:["use"]}`

We fixed the issue by adding permission to delete the PSPs to `system:serviceaccount:kube-system:generic-garbage-collector` .

**What you expected to happen**:

I expected `generic-garbage-collector` s/a to be able to gc the role.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

If this behavior is by design, it will be nice to have a `aggregate-to-gc` so we cloud just create the cluster role.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools: kind
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery
/sig auth

**Comment by liggitt** [comment]
Fixed in master in https://github.com/kubernetes/kubernetes/pull/90534 but needs cherry picking to existing releases. 

/assign @apelisse

**Comment by apelisse** [comment]
Thanks, I archived that task a little too fast.

**Comment by liggitt** [comment]
This is resolved in 1.16.11+, 1.17.7+, 1.18.4+
