### ISSUE TITLE
Let kube-apiserver select an HTTP or an HTTPS connection based on kubelet's configuration

### ISSUE THREAD

**Issue by kadisi** [kubernetes/kubernetes#91620]
**What would you like to be added**:

Currently `kube-apiserver` use the configuration of itself `--kubelet-https` to determine the use of https for kubelet connections.

If `--kubelet-https =true`, when apiserver initiates a connection to all kubelet, it USES the HTTPS connection. But this is the full configuration.

In some scenarios, a node node will be under an Intranet VPN and will only allow apiserver to get metric data, so there is no need to connect via HTTPS. 

This limits the flexible configuration of `kube-apiserver` and `kubelet` connections.

**Why is this needed**:

**Comment by liggitt** [comment]
The ability to disable TLS communication from the API server to the kubelet is deprecated. I would not anticipate enabling per-kubelet insecure settings as proposed.

**Comment by kadisi** [comment]
> The ability to disable TLS communication from the API server to the kubelet is deprecated. I would not anticipate enabling per-kubelet insecure settings as proposed.

@liggitt You mean the kube-apiserver will be canceled the `--kubelet-https` configuration in the future ?  and the kube-apiserver must initiate a connection to kubelet using TLS ?

**Comment by liggitt** [comment]
> You mean the kube-apiserver will be canceled the `--kubelet-https` configuration in the future ? and the kube-apiserver must initiate a connection to kubelet using TLS ?

Yes. That has been required since before 1.0. Not removing the obsolete `--kubelet-https` flag was an oversight.

**Comment by neolit123** [comment]
> In some scenarios, a node node will be under an Intranet VPN and will only allow apiserver to get metric data, so there is no need to connect via HTTPS.

from what i've seen, most serious customers and their security teams would demand TLS from your setup regardless of VPN.

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/91630 to clean up the apiserver flag

**Comment by kadisi** [comment]
@liggitt @neolit123 thanks
