### ISSUE TITLE
Connection to the server local host:8080 was refused - did you specify right host or port

### ISSUE THREAD

**Issue by AnwarArifa** [kubernetes/kubernetes#91631]
@Rahulwagh after restart my laptop unable to cluster using vagrant getting the below error

Connection to the server local host:8080 was refused - did you specify right host or port
_

Please advise

**Comment by rikatz** [comment]
@AnwarArifa is this still a thing?

**Comment by rikatz** [comment]
/triage needs-information
/close

I'm closing this due to lack of information, please feel free to reopen as soon as you got some further information about this.

Thanks
