### ISSUE TITLE
Volumes subPathExpr not being expanded.

### ISSUE THREAD

**Issue by dick-twocows** [kubernetes/kubernetes#91644]
**What happened**:
Running https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath-with-expanded-environment-variables, specifically the subPathExpr section fails with "POD_NAME: command not found"

I have other cases where this is not working but this is a documentation example so I logged it aginst this one.

``` 
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: busybox
    command: [ "sh", "-c", "while [ true ]; do echo 'Hello'; sleep 10; done | tee -a /logs/hello.txt" ]
    volumeMounts:
    - name: workdir1
      mountPath: /logs
      subPathExpr: $(POD_NAME)
  restartPolicy: Never
  volumes:
  - name: workdir1
    hostPath:
      path: /var/log/pods
``` 
**What you expected to happen**:
The pod to be created and the ENV POD_NAME expanded for workdir1 volumeMounts.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the above YAML.

**Anything else we need to know?**:

Output as below...

``` 
 k apply -f - <<EOF
> apiVersion: v1
> kind: Pod
> metadata:
>   name: pod1
> spec:
>   containers:
>   - name: container1
>     env:
>     - name: POD_NAME
>       valueFrom:
>         fieldRef:
>           apiVersion: v1
>           fieldPath: metadata.name
>     image: busybox
>     command: [ "sh", "-c", "while [ true ]; do echo 'Hello'; sleep 10; done | tee -a /logs/hello.txt" ]
>     volumeMounts:
>     - name: workdir1
>       mountPath: /logs
>       subPathExpr: $(POD_NAME)
>   restartPolicy: Never
>   volumes:
>   - name: workdir1
>     hostPath:
>       path: /var/log/pods
> EOF
POD_NAME: command not found
pod/pod1 created

/data 
❯ k describe pod pod1
Name:         pod1
Namespace:    default
Priority:     0
Node:         dick-5491/192.168.1.111
Start Time:   Mon, 01 Jun 2020 20:06:23 +0100
Labels:       <none>
Annotations:  Status:  Running
IP:           10.1.44.29
IPs:
  IP:  10.1.44.29
Containers:
  container1:
    Container ID:  containerd://a9d60b2d13a7242d3bc0f6763cac5df98c9ff8c73f4606e592d4579f25717392
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:836945da1f3afe2cfff376d379852bbb82e0237cb2925d53a13f53d6e8a8c48c
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      while [ true ]; do echo 'Hello'; sleep 10; done | tee -a /logs/hello.txt
    State:          Running
      Started:      Mon, 01 Jun 2020 20:06:24 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAME:  pod1 (v1:metadata.name)
    Mounts:
      /logs from workdir1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-drzsd (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  workdir1:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/pods
    HostPathType:  
  default-token-drzsd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-drzsd
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age    From                Message
  ----    ------     ----   ----                -------
  Normal  Scheduled  2m41s  default-scheduler   Successfully assigned default/pod1 to dick-5491
  Normal  Pulling    2m40s  kubelet, dick-5491  Pulling image "busybox"
  Normal  Pulled     2m39s  kubelet, dick-5491  Successfully pulled image "busybox"
  Normal  Created    2m39s  kubelet, dick-5491  Created container container1
  Normal  Started    2m39s  kubelet, dick-5491  Started container container1
``` 
/data 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
Linux dick-5491 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
is the problem that you are using an unescaped `$` character in a shell invocation?

placing the value in a file and applying with ` -f /path/to/file` or escaping the $ character in the shell invocation would work better

**Comment by dick-twocows** [comment]
Thank you! I had completely overlooked that :-(
