### ISSUE TITLE
authentication error when delete secret in etcd

### ISSUE THREAD

**Issue by pretendhigh** [kubernetes/kubernetes#91653]
There is a secret that I can not delete it use "kubectl delete secret ceph-retain-bucket -n default". So I delete it in the  etcd.
```
etcdctl --endpoints="https://10.2.20.159:2379" del --from-key /registry/secrets/default/ceph-retain-bucket
```
Command "kubectl get secret -n default“ nolonger show the secret again. But the api-server show a error  log like:
```
E0601 23:05:28.062127       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
```
I don not konw how to fix it.

**Environment**:
- Kubernetes version :kubernet 1.15.3
- etcd: 3.2.9
- OS : centos7.6

**Comment by pacoxu** [comment]
I have met this issue once when I mistakely delete all my secrets for backup.

```
all_namespaces=$(kubectl get namespaces -A --no-headers=true | awk '{print $1}')
for namespace in $all_namespaces; do echo "backup sa secret on $namespace"; all_secrets=$(kubectl get secret -n $namespace | grep 'kubernetes.io/service-account-token' | awk '{print $1}'); for secret in $all_secrets; do kubectl get secret -n $namespace $secret -o yaml > $secret.yaml; done;   echo "delete sa secret on $namespace"; kubectl delete secret -n $namespace $(kubectl get secret -n $namespace | grep 'kubernetes.io/service-account-token' | awk '{print $1}');   done
```

As I backuped those secrets, I restore these secrets and apiserver works now.
```
E0603 03:56:28.467220       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:28.470421       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:29.001728       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:29.001859       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:30.006374       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:30.007437       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:31.010458       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:31.011424       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:32.014321       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
E0603 03:56:32.015053       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
```

Please check if there are something missing in your cluster

**Comment by enj** [comment]
I believe you have deleted all data that is "greater than or equal to" `/registry/secrets/default/ceph-retain-bucket`.  The `Token has been invalidated` error message refers to SA tokens that are no longer valid because the underlying secret or pod has been deleted.

```
      --from-key[=false]	delete keys that are greater than or equal to the given key using byte compare
```

**Comment by pretendhigh** [comment]
> I have met this issue once when I mistakely delete all my secrets for backup.
> 
> ```
> all_namespaces=$(kubectl get namespaces -A --no-headers=true | awk '{print $1}')
> for namespace in $all_namespaces; do echo "backup sa secret on $namespace"; all_secrets=$(kubectl get secret -n $namespace | grep 'kubernetes.io/service-account-token' | awk '{print $1}'); for secret in $all_secrets; do kubectl get secret -n $namespace $secret -o yaml > $secret.yaml; done;   echo "delete sa secret on $namespace"; kubectl delete secret -n $namespace $(kubectl get secret -n $namespace | grep 'kubernetes.io/service-account-token' | awk '{print $1}');   done
> ```
> 
> As I backuped those secrets, I restore these secrets and apiserver works now.
> 
> ```
> E0603 03:56:28.467220       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:28.470421       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:29.001728       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:29.001859       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:30.006374       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:30.007437       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:31.010458       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:31.011424       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:32.014321       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> E0603 03:56:32.015053       1 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, Token has been invalidated]
> ```
> 
> Please check if there are something missing in your cluster

A configmap disappered on the same time just when I deleted /registry/secrets/default/ceph-retain-bucket in the etcd. Then I restarted etcd, kube-apiserver, controller-manager,scheduler-manager, authentication error happened in controller-manager and scheduler-manager too. And pods controlled by deployment could not restart when I deleted them. I tried to recreate ca.pem, admin.pem, etcd.pem, kubernetes.pem,  kube-proxy.pem, token.csv, bootstrap.kubeconifg, kube-proxy.kubecnfig. But it wouldn't help when I restarted the k8s cluster.  Finally, I destroied the k8s-cluster. Maybe it is a bad idea to delete resources in the etcd. But I still feel confused when I delete a secret or configmap and it just get stucked. I think it would be a good way for k8s telling me why I couldn't destroy it.

**Comment by pretendhigh** [comment]
> I believe you have deleted all data that is "greater than or equal to" `/registry/secrets/default/ceph-retain-bucket`. The `Token has been invalidated` error message refers to SA tokens that are no longer valid because the underlying secret or pod has been deleted.
> 
> ```
>       --from-key[=false]	delete keys that are greater than or equal to the given key using byte compare
> ```
I tried to delete a configmaps and a secret but it got stucked. So I deleted /registry/secrets/default/ceph-retain-bucket in the etcd. Then the configmap disappeared too and the authentication error appeared.  I tried to recreate ca.pem, admin.pem, etcd.pem, kubernetes.pem, kube-proxy.pem, token.csv, bootstrap.kubeconifg, kube-proxy.kubecnfig. But it wouldn't help when I restarted the k8s cluster. Finally, I destroied the k8s-cluster.

**Comment by liggitt** [comment]
Deleting data directly from etcd this way is not recommended, since it bypasses apiserver protections. The example authentication errors would have been from any service account in any namespace alphabetically after "default". 

Restoring from an etcd backup or recreating the cluster is likely your best option after that.
