### ISSUE TITLE
Enhance the test/tooling coverage for `dockerless` Kubelet

### ISSUE THREAD

**Issue by mattjmcnaughton** [kubernetes/kubernetes#91657]
**What would you like to be added**:
I'm creating this issue as a tracking issue for improving the test and tooling coverage for our `dockerless` Kubelet. See the [KEP](https://github.com/kubernetes/enhancements/pull/1546) and [PR](https://github.com/kubernetes/kubernetes/pull/87746) for more background information - at a high level, the cool is supporting building a Kubelet that does not have any dependency on `docker/docker`.

With [PR](https://github.com/kubernetes/kubernetes/pull/87746), we've merged the changes which allow folks to build a Kubelet without a dependency on `docker/docker`. However, we want to add additional test/tooling coverage in CI so that we can remain confident that `dockerless` will continue to work going forward.

To start, we'd like to see the following:
- [ ] Add the static tests mentioned [in this comment](https://github.com/kubernetes/kubernetes/pull/87746#issuecomment-617488763) as part of CI. Alternatively, we could try and use `.import-restrictions` to replace the check that only certain files import `github.com/docker/docker`, although I'm not sure if that will work yet... I think there still may be external `docker/docker` dependencies that we're waiting to remove.
- [ ] Add a test to CI that verifies Kubelet builds when the `dockerless` tag is enabled. Note, [this verify script](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-typecheck-dockerless.sh) may already do this. Confirm its running via CI and tests the build.
- [ ] Add a e2e_node test using a Kubelet compiled w/ the `dockerless` flag.
- cc @dims @derekwaynecarr anything you'd like to see added?

**Why is this needed**:
Adding this testing will help us ensure the Kubelet successfully builds w/ the `dockerless` tag and that uses of `docker/docker` stay constrained to `pkg/kubelet/dockershim`.

**Extra Note**
I think participating in this workstream could be a great candidate for someone who is new to
contributing to sig-node/k8s or someone who has tackled a couple small issues and is looking to tackle a bigger one. With that in mind, **I'd prefer to please give first dibs for picking up all/some of this work to any folks who are currently underrepresented in the k8s community.** Myself and @dims (who is much more knowledgeable than myself :) ) are completely open to mentoring and assisting. Please reach out to @mattjmcnaughton on k8s Slack (or post directly in #sig-node and tag me) if you're interested, and we can go from there.

**Comment by BenTheElder** [comment]
I'm mildly interested in having the kind presubmits do this.
we'd either have to get the tag working under bazel or migrate off of bazel and implement caching for that.

**Comment by MHBauer** [comment]
I am interested in getting this all the way through to completion.

I've been mainly looking at the tests for the sig-node testing push, so I might start a bit on my own with making an e2e_node test, but I want to get fully into the depth of the rest of the work as well.

I think I have e2e_node tests running locally with containerd and without docker. I'll look into the PR and see if there is a way for me to verify that it was built with the correct build tags.

**Comment by MHBauer** [comment]
I've managed to get it compiled and running e2e_node tests with

`GOFLAGS='-v -tags=dockerless' make test-e2e-node PARALLELISM=1 TEST_ARGS='--kubelet-flags=--fail-swap-on=false' FOCUS="Legacy:Docker" SKIP=""`

There's a nice error message in the PR, but it isn't surfaced, so I'm making a PR for that.

**Comment by MHBauer** [comment]
Do the containerd tests use docker at all? 
Is it as simple as adding 
```
      env:
      - name: GOFLAGS
        value: -tags=dockerless
```
to some of the existing configuration?

**Comment by yash97** [comment]
I can start with adding the static checks with CI

**Comment by mattjmcnaughton** [comment]
Cool - I just updated that part of the issue w/ some additional info - please lmk if you have qs :)

**Comment by yash97** [comment]
sure so can i dm you on slack?

**Comment by mattjmcnaughton** [comment]
Yup!

**Comment by MHBauer** [comment]
I've gotten some remote runs in targeting specifically the docker tests

1. This succeeds
```
GOFLAGS='-v' make test-e2e-node TEST_ARGS='--kubelet-flags=--fail-swap-on=false' FOCUS="Legacy:Docker" SKIP="" RUNTIME=docker REMOTE=true DELETE_INSTANCES=true
```

2. This fails as I would expect it to
```
GOFLAGS='-v -tags=dockerless' make test-e2e-node TEST_ARGS='--kubelet-flags=--fail-swap-on=false' FOCUS="Legacy:Docker" SKIP="" RUNTIME=docker REMOTE=true DELETE_INSTANCES=true
```

Should we now by default to `tags=dockerless` and then make sure to not use that tag for the docker specific test suite?

**Comment by mattjmcnaughton** [comment]
Oh that's awesome news :) @dims and @derekwaynecarr, curious to know what you envisioned as the most effective long term setting for the tests. Should we default to dockerless, with some tests using the dockershim, or default to using the dockershim, with only certain tests specifying `dockerless`?

I can see arguments for both :)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1932 (note: most of upstream CI testing kubernetes with kind is using bazel builds which do not have this)
