### ISSUE TITLE
Add unit test coverage using throttledImageService

### ISSUE THREAD

**Issue by mattjmcnaughton** [kubernetes/kubernetes#91655]
**What would you like to see added?**

Currently, executing the unit tests in `pkg/kubelet/images/...` does not
actually execute the `throttledImageService` as defined in
`pkg/kubelet/images/helpers.go`. For all unit tests, `qps` is set to 0, so we
essentially use a non-throttled image service. Examining the code coverage shows
that all code components "unique" to the throttled image service (i.e. the
actual throttling) are not actually tested.

**Why this is needed?**

We'd like unit test coverage for the business logic that makes the throttling
actually throttle. Furthermore, by default, the image service does use
throttling, so adding this test coverage will help us mirror what happens in
production.

**Extra note**

I think this ticket could be a great candidate for someone who is new to
contributing to sig-node/k8s. **I'd prefer to please give first dibs for picking
this up to any folks who are currently underrepresented in the k8s community**.
Please reach out to @mattjmcnaughton on k8s Slack (or post directly in #sig-node and tag me) if you're interested, and I'll assign you the issue. I'm happy to mentor and be helpful in whatever way I can :)

**Comment by iamchuckss** [comment]
Hi @mattjmcnaughton, can I work on this issue?

**Comment by mattjmcnaughton** [comment]
Sure @iamchuckss !

/assign @iamchuckss 

Please let me know if you have any questions :)

**Comment by mattjmcnaughton** [comment]
:wave: @iamchuckss when you submit a pr for this, can you tag me and @farah as a reviewer? @farah has also given this ticket some thought, so I'm looking forward to getting their insights :)

**Comment by iamchuckss** [comment]
@mattjmcnaughton yeah definitely!
