### ISSUE TITLE
Should Replicaset controller cleanup the failed pods

### ISSUE THREAD

**Issue by xiaoanyunfei** [kubernetes/kubernetes#91672]
**What happened**:
I found a deployment with one running pod and serveral failed pods
But the expect pod num of deployment is 1
The failed pods cloud never be deleted unless someone do it.

Should replicaset controller cleanup the failed pods when the pod number reach expectations？

pod list
> 
cloud-731790-10907-1948-41-deploy-5769778f7f-bdkfq                1/1     Running   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-kx5ng                0/1     Evicted   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-mh6h8                0/1     Evicted   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-r8vl2                0/1     Evicted   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-scjd4                0/1     Evicted   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-tbkcq                0/1     Evicted   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-xc94j                0/1     Evicted   0          22h
cloud-731790-10907-1948-41-deploy-5769778f7f-zdjzb                0/1     Evicted   0          22h

failed pod status
>
status:
  message: 'Pod The node had condition: [DiskPressure]. '
  phase: Failed
  reason: Evicted

replicaset
> 
NAME                                           DESIRED   CURRENT   READY   AGE
cloud-731790-10907-1948-41-deploy-5769778f7f   1         1         1       22h

replicaset status
>
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1

**What you expected to happen**:

Replicaset controller should cleanup the failed pods  automatically

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure, maybe:

- Create a deployment
- Evict the pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.17.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/sig apps
/assign

**Comment by yan234280533** [comment]
we have the same requirements.

**Comment by tnozicka** [comment]
> Replicaset controller should cleanup the failed pods automatically

The pod objects are intentionally left there as thumb stones so user can discover them and find out the reason for eviction (by kubelet). They are not accounted into the RS state. If the count gets too high PodGC would clean them up. This isn't a bug. 

/remove-kind bug
/kind feature

Eviction API just deletes the pods so this isn't the case there.

That said the thumb stones could be eventually cleaned by a controller e.g. if they are older then a week or so. But such feature would require an RFE. Feel free to file one if you'd like pursue it.

**Comment by tnozicka** [comment]
We talked about it at today's Sig-Apps call. The consensus was that it would be useful but not a high priority. Needs a KEP and syncing there with apimachinery for being a pod GC (it was pointed out that they claimed the ownership for the similar count based pod GC).
