### ISSUE TITLE
StreamWatcher memory leak

### ISSUE THREAD

**Issue by vikramk7** [kubernetes/kubernetes#91686]
I am porting https://github.com/kubernetes/apimachinery/issues/70 to k/k per the [comment](https://github.com/kubernetes/apimachinery/issues/70#issuecomment-597302625)

We are using the StreamWatcher and seeing extremely high memory allocations. Attached is a memory profile:

[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.033.pb.gz](https://github.com/kubernetes/kubernetes/files/4718401/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.033.pb.gz)

From this we have 9.6 GB of memory allocated by the StreamWatcher.

To get to this state I had a deployment with 200 replicas, and every 30 seconds I redeployed all of the pods (kubectl rollout restart). I left this running overnight and saw this memory usage.

**Comment by vikramk7** [comment]
Copying @howardjohn,  he was the original reporter of the bug in apimachinery.

**Comment by liggitt** [comment]
Thanks for the report. @howardjohn, some additional quesitons:

* what client version are you using?
* what does your handler do with the objects it receives from the streamwatcher? does it retain any portion of those objects out of band?
* do you have metrics indicating the handler is not blocked

**Comment by fedebongio** [comment]
Thank you Jordan for taking a look!

**Comment by nirvanagit** [comment]
Hi, we are facing the same issue, when using Istio. Pilot's heapdump showed the exact behavior as reported by @howardjohn.

**Comment by howardjohn** [comment]
I am about 90% sure this is an Istio bug and not a k8s bug. We had various reports about the handler being blocked in Istio which would explain this. I figured this was a k8s issue initially as it was at the root of the flame graph, but I think that was just my own misunderstanding

**Comment by howardjohn** [comment]
We have proven this is an Istio issue, see https://github.com/istio/istio/issues/25112 for details. tl;dr don't block the handler for the informer

/close

**Comment by liggitt** [comment]
Thanks for the follow up

**Comment by evanlixin** [comment]
Hi, I am also facing the same issue, when using cache.NewListWatchFromClient to watch pod resource. I find StreamWatcher and see extremely high memory allocations.  pprof memory profile like this @vikramk7 described
