### ISSUE TITLE
k8s with cri-o as runtime does not support calico as cni plugin

### ISSUE THREAD

**Issue by kubealex** [kubernetes/kubernetes#91695]
**What happened**:
Followed the guide to install cri-o as container runtime and calico as cni-plugin for CentOS7

**What you expected to happen**:

Working configuration

**How to reproduce it (as minimally and precisely as possible)**:

Just follow the guide for installing HA Cluster.
Set up cri-o with prerequisites
Init master node with kubeadm specifying custom --pod-network-cidr
Install cni-plugin with kubectl apply -f kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

In crio daemon, default bridge is used for network, completely ignoring calico network definition in /etc/cni/net.d/ due to default plugin dir not containing calico executable.

So every pod from now on will start on the default cri-o network 10.85.0.0/16 ON ALL NODES, so pods will have the same IP in the cluster, making everything not working.

**Anything else we need to know?**:

I think this setup should not be marked as supported, since it doesn't work at the moment, manual intervention is needed updating /etc/crio/crio.conf file with the correct location of plugin executable 

# Paths to directories where CNI plugin binaries are located.
plugin_dirs = [
        "/usr/libexec/cni",
        "/opt/cni/bin/",
]

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: VMS
- OS (e.g: `cat /etc/os-release`): CentOS7
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico 3.14
- Others:

**Comment by neolit123** [comment]
hello, this doesn't feel like a core k8s problem. it is hard for k8s to guarantee support for all container runtime / CNI combinations.

please log the issue in the Calico issue tracker and ask for feedback there first.

thanks
/close
