### ISSUE TITLE
Group info is missing in subject access review request for webhook authz mode

### ISSUE THREAD

**Issue by krdhruva** [kubernetes/kubernetes#91698]
**What happened**:
I configured webhook authz mode like below to authorize client request 

```Console
--runtime-config=authentication.k8s.io/v1=true
--runtime-config=authorization.k8s.io/v1=true
--authentication-token-webhook-config-file=/etc/kubernetes/manifests/guard-webhook.yaml
--authorization-mode=Node,Webhook,RBAC
--authorization-webhook-config-file=/etc/kubernetes/manifests/guard-webhook-authz.yaml 
--authorization-webhook-cache-authorized-ttl=5m0s
--authorization-webhook-cache-unauthorized-ttl=1m0s
```

On successful authentication, I observed that authentication webhook is returning groups details to api server  as below

```Console
{
  "kind": "TokenReview",
  "apiVersion": "authentication.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    
  },
  "status": {
    "authenticated": true,
    "user": {
      "username": "**redacted**",
      "groups": [
        "7e6a53d8-eac4-4a9c-bd35-ed0148c793f0",
        "0af90af7-4d7f-468a-986b-8901f7280ab3"
      ],
      "extra": {
        "oid": [
  "40d92b25-50d6-4d61-8370-d88a183140f5"
]
      }
    }
  }
}
```

However subject access review request has group info as empty
```Console
{
    "kind": "SubjectAccessReview",
    "apiVersion": "authorization.k8s.io/v1beta1",
    "metadata": {
        "creationTimestamp": null
    },
    "spec": {
        "resourceAttributes": {
            "namespace": "deployment-test",
            "verb": "get",
            "group": "extensions",
            "version": "v1beta1",
            "resource": "deployments",
            "name": "nginx-deployment"
        },
        "user": "**redacted**",
        "extra": {
            "oid": [
    "40d92b25-50d6-4d61-8370-d88a183140f5"
]
        }
    },
    "status": {
        "allowed": false
    }
}
```

- Printing subject access review request with members shows Groups:[]
- Even though I have registered runtime version v1, subject access review request apiVersion is v1beta1

Alternatively, I verified this scenario with below configuration but observed same behavior.
```Console
--runtime-config=authentication.k8s.io/v1beta1=true
--runtime-config=authorization.k8s.io/v1beta1=true
```
**What you expected to happen**:
Subject access review should contain group information retrieved in token review request.

**How to reproduce it (as minimally and precisely as possible)**:
I am able to repro this by configuring webhook authn and authz with AAD. Working on generic repro.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AKS-Engine
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
- Kernel (e.g. `uname -a`): 
Linux k8s-master-10794928-0 4.15.0-1082-azure #92~16.04.1-Ubuntu SMP Tue Apr 14 22:28:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
> However subject access review request has group info as empty

How did you capture the JSON in the description? Did you grab that directly from the incoming request to the webhook, or did you decode it to a typed struct?

https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook_v1beta1_test.go#L490-L522 and https://github.com/kubernetes/kubernetes/blob/release-1.18/staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook_v1_test.go#L490-L511 verify the webhook is sending the correct data...

Note that v1beta1 SubjectAccessReviews had a typo in the serialized groups field and named it `group`: https://github.com/kubernetes/api/blob/master/authorization/v1beta1/types.go#L149

v1 SubjectAccessReviews fixed the typo and now serializes as `groups`: https://github.com/kubernetes/api/blob/master/authorization/v1/types.go#L138-L140

**Comment by krdhruva** [comment]
Thanks @liggitt to look into the issue.

I decoded request to subject access review structure of k8s.io/api/authorization/v1 package. Decoding it to structure of k8s.io/api/authorization/v1beta1 fails with error EOF.

**Comment by liggitt** [comment]
> However subject access review request has group info as empty

Decoding an incoming v1beta1 request to the v1 struct is not valid. You need to decode the incoming request to the proper version.
