### ISSUE TITLE
Wrong comments and code in DeltaFIFO wrt items vs queue consistency

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#91709]
**What happened**:
In reviewing another PR, I noticed incorrect commentary and code.  The primary offense is at https://github.com/kubernetes/kubernetes/blob/eda662b2fd1beb31f6117d20a2c850f4e216bd77/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L390-L395 , where a comment asserts (incorrectly) that a key can be present in `queue` but not `items` and the code removes a key from `items` without ensuring it is absent from `queue`.  The only saving grace is that this code is actually unreachable (as also noted in the comment).  I think it would be better to fix the comment and `panic` in this unreachable situation, than to violate an invariant that is critical to other code in this file.

https://github.com/kubernetes/kubernetes/blob/eda662b2fd1beb31f6117d20a2c850f4e216bd77/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L496-L499 also contemplates the possibility that a key can be in `queue` and absent from `items`.

**What you expected to happen**:
I expected there to be no comments or code that contemplate violations of the invariant at https://github.com/kubernetes/kubernetes/blob/eda662b2fd1beb31f6117d20a2c850f4e216bd77/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L166-L167

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): current `master` branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@jqmichael

**Comment by MikeSpreitzer** [comment]
Sorry, I should have noticed this in my earlier pass over this code.

**Comment by jqmichael** [comment]
Agreed. 

Was discussing this with @lavalamp at
https://github.com/kubernetes/kubernetes/pull/91435#discussion_r433000161

**Comment by fedebongio** [comment]
We discussed this one, Mike will send PR, Daniel will review.
