### ISSUE TITLE
rollout history change cause not right

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#91714]
**What happened**:
1run  kubectl set image deploy mysql-deploy mysql=mysql：5.7 --record
2run kubectl rollout history deploy mysql-deployment
3run  kubectl set image deploy mysql-deploy mysql=mysql：5.6
4run kubectl rollout history deploy mysql-deployment
```
[root@master01 ~]# kubectl rollout history deploy mysql-deployment
deployment.apps/mysql-deployment 
REVISION  CHANGE-CAUSE
10        kubectl set image deploy mysql-deployment mysql=mysql:5.7 --record=true
11        kubectl set image deploy mysql-deployment mysql=mysql:5.7 --record=true
```
11 is wrong，not 5.7，and the command doesnot has --record
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
···
[root@master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
···
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mattthias** [comment]
I can reproduce the behavior @13567436138 described on Kubernetes  v1.18.4 (on premise installation installed using kubeadm). As the rollout history is part of  `/apis/apps/v1/deployment`  i added the sig/apps as label.

**Comment by janetkuo** [comment]
> **What happened:**
> 1run kubectl set image deploy mysql-deploy mysql=mysql：5.7 --record
> 2run kubectl rollout history deploy mysql-deployment
> 3run kubectl set image deploy mysql-deploy mysql=mysql：5.6
Would you try again with `kubectl set image deploy mysql-deploy mysql=mysql：5.6 --record`? Without specifying `--record`, the command won't be recorded in the resource annotations and therefore the previous recorded command will be used. 
> 4run kubectl rollout history deploy mysql-deployment

**Comment by janetkuo** [comment]
Closing as this works as designed. Please feel free to reopen if there are still issues to be resolved.
