### ISSUE TITLE
kubernetes supporting multiple VRF:s

### ISSUE THREAD

**Issue by nysan** [kubernetes/kubernetes#91728]
**What would you like to be added**:
In my setup, I'm using metalLB+calico.

The netdev topology on the metal OS is:
```
eth0.2  eth0.3    eth1.23  eth1.24
     \          |          /            /
                 bond0      
          /              \
   eth0                 eth1
```
eth0.2, eth0.3, eth1.23 and eth1.24 are different L3 domains, and do not share a default route towards external clients. i.e. traffic responses need to be routed back to the interface where it came in.

To support above, the below items have been modified.

* For ingress traffic via LB*
0. a separate named metaLB pool of VIPs for each L3 network domain.
1. ip rule from <eth0.2_LB_VIP_CIDR> table 101. (To have mutiple default routes, selecting on SRC VIP CIDR).

* For egress traffic *
0. VRF specific FWMARK applied on egress for Pods marked with network domain.
1. 1. ip rule fwmark <FWMARK> table 101.

An alternative approach, and perhaps a nicer one, would be to fix support for VRFs in the container provider. i.e. support exposing a service(via LB) to a single host VRF.
I think https://github.com/docker/for-linux/issues/698 is related.

If there is another, more proper approach to this problem, please let me know.

**Why is this needed**:
With above modification, a single k8s instance would be able to serve clients on multiple isolated L3 domains at the same time.

**Comment by vivekskrishna** [comment]
Hi @nysan , can you please let me know why you closed this issue? any outcome for this feature request?
