### ISSUE TITLE
[Failing Test] Conformance - OpenStack (ci-cloud-provider-openstack-acceptance-test-e2e-conformance)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#91739]
**Which jobs are failing**:

`Conformance - OpenStack (ci-cloud-provider-openstack-acceptance-test-e2e-conformance)`

**Which test(s) are failing**:

`[sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Conformance]`

**Since when has it been failing**:

`06-03-20 07:08 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack

**Reason for failure**:

```
Jun  3 15:32:47.275: FAIL: We need at least two pods to be created butall nodes are already heavily utilized, so preemption tests cannot be run
```

**Anything else we need to know**:

Looks like this is a new test that was just promoted here: https://github.com/kubernetes/kubernetes/pull/80545

/cc @spiffxp 

/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19
/sig testing
/assign @hkamel

**Comment by hasheddan** [comment]
@spiffxp I see that in another test we skip if we hit this case: https://github.com/kubernetes/kubernetes/blob/bb11561ace51b205e89c33813225142643b2fffc/test/e2e/scheduling/preemption.go#L244

Could this be done instead of fail in the test we are seeing here: https://github.com/kubernetes/kubernetes/blob/bb11561ace51b205e89c33813225142643b2fffc/test/e2e/scheduling/preemption.go#L159

**Comment by hasheddan** [comment]
@Huang-Wei this looks like the same test failure we were seeing with https://github.com/kubernetes/kubernetes/issues/91911, any thoughts?

**Comment by Huang-Wei** [comment]
@hasheddan Could you let me know which k/k commit https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack is using? I cannot find the commit # on the page so cannot confirm if my fix gets picked up or not.

**Comment by Huang-Wei** [comment]
Ah, it seems the test suite has only one available node?

```
Jun 11 14:52:00.117: We need at least two pods to be created but all nodes are already heavily utilized, so preemption tests cannot be run
```

In #91955, we have to change `e2e.skipf` to `e2e.fatalf`.

**Comment by Huang-Wei** [comment]
@hasheddan not sure we can check the test setup, basically it needs more than 2 nodes for the conformance tests to pass through.

**Comment by hasheddan** [comment]
@Huang-Wei thanks! I'll see what I can do :+1:

**Comment by hkamel** [comment]
/sig scheduling

**FAIL: We need at least two pods to be created butall nodes are already heavily utilized, so preemption tests cannot be run**
` Jun 12 15:14:45.415: FAIL: We need at least two pods to be created butall nodes are already heavily utilized, so preemption tests cannot be run
Full Stack Trace
k8s.io/kubernetes/test/e2e/scheduling.glob..func5.4()
	/home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:250 +0x103e
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc002888700)
skipped 28 lines unfold_more
Jun 12 15:14:45.477: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "sched-preemption-6003" for this suite.
[AfterEach] [sig-scheduling] SchedulerPreemption [Serial]
  /home/zuul/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:77`

**Comment by BenTheElder** [comment]
Conformance tests may never skip. That would defeat the purpose.

**Comment by BenTheElder** [comment]
This is maybe 
/sig cloud-provider
The tests are WAI, this cluster is not passing.
/remove-sig testing
/remove-sig scheduling

**Comment by hasheddan** [comment]
@BenTheElder Openstack team is discussing in Slack :) Their job config is outside of Kubernetes org, but I'll make sure to xref any PR's here.

**Comment by hasheddan** [comment]
This is really hard for us to track as the CI system it runs in is entirely opaque to us. Any thoughts on what to do about this? @liggitt @onlydole

**Comment by onlydole** [comment]
It would be fantastic if we had a bit more visibility over the long-term so we could have signal without needing to reach out to any teams. Do you know if we have any ability to offer log aggregation for tests like this, @liggitt or @spiffxp? 

Note that is VERY likely a "to be solved later" solution :smile:

**Comment by liggitt** [comment]
s/liggitt/bentheelder/ for test aggregation discussions

**Comment by liggitt** [comment]
cc @BenTheElder

**Comment by BenTheElder** [comment]
can you elaborate on what you mean by log aggregation?

third party CI can upload any files they want, but the intention is
primarily that testgrid can display structured JUnit xml results.
testgrid / prow also have some JSON files with timestamps and pass/fail
essentially.

**Comment by onlydole** [comment]
Ah! Got it, @BenTheElder - my thought was if we might be able to view build logs/errors...that might help in solving any issues on that front. 

I agree with you that JUnit XML would be the most ideal (really anything with to provide more data/signal would be excellent).

**Comment by BenTheElder** [comment]
they're available in prow.k8s.io's viewer if the bucket is public, and
testgrid config controls what log viewer is used on click through (it's
templated IIRC)

**Comment by hasheddan** [comment]
Given that this is not release blocking and we have limited insight into the testing environment, I am going to bump this to v1.20

/milestone v1.20

**Comment by hasheddan** [comment]
Looks like this is running again! (albeit with a failure on `DumpClusterLogs`).. will investigate

**Comment by RobertKielty** [comment]
So there is an in progress thread in Slack looking at the this now. 

I am tempted to create a new issue for the DumpClusterLogs issue / timing out but will leave open for today ...

This is being investigated now by @ramineni and they are investigating on the following thread on Slack

https://kubernetes.slack.com/archives/CN0K3TE2C/p1605284969233600

**Comment by RobertKielty** [comment]
@ramineni has let me know on the thread above there is a PR opened on OpenLab that might fix this issue
