### ISSUE TITLE
Kubeadm tests fail when run using go test ./...

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#91740]
**What happened**:
When I do `go test ./...` from the kubernetes root, it fails because the tests in [cmd/kubeadm/test](https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/test) have external dependencies.  KUBEADM_PATH is required for example.
```
...
--- FAIL: TestCmdCompletion (0.00s)
panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path [recovered]
	panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path

goroutine 21 [running]:
testing.tRunner.func1(0xc0000f2400)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x1231680, 0x15a2570)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/cmd/kubeadm/test/cmd.getKubeadmPath(...)
	/home/bpursley/go/src/k8s.io/kubernetes/cmd/kubeadm/test/cmd/util.go:89
k8s.io/kubernetes/cmd/kubeadm/test/cmd.TestCmdCompletion(0xc0000f2400)
	/home/bpursley/go/src/k8s.io/kubernetes/cmd/kubeadm/test/cmd/completion_test.go:22 +0x1f8
testing.tRunner(0xc0000f2400, 0x14a5370)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	k8s.io/kubernetes/cmd/kubeadm/test/cmd	0.012s
?   	k8s.io/kubernetes/cmd/kubeadm/test/kubeconfig	[no test files]
?   	k8s.io/kubernetes/cmd/kubeadm/test/resources	[no test files]
FAIL
```

**What you expected to happen**:
The [Kubernetes Testing Guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing.md#run-all-unit-tests) says I should be able to run all unit tests using `go test ./...`

**How to reproduce it (as minimally and precisely as possible)**:
Clone the repository and run `go test ./...` from the project root.

Or, you can more quickly see the problem if you rjust un that from the cmd/kubeadm subfolder like this:
```
cd cmd/kubeadm
go test ./...
```

**Anything else we need to know?**:
`make test` [specifically excludes cmd/kubeadm/test](https://github.com/kubernetes/kubernetes/blob/b48f5af2602bf097c11c6a252bc7f82a7c096206/hack/make-rules/test.sh#L43) so that the problem does not occur if you use make test.

When this issue is fixed, we should probably remove this exclusion as well.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19 (master branch)
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```
Linux cinlogic-xps13 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
go version go1.13.4 linux/amd64
```

**Comment by neolit123** [comment]
hello, i'm having deja-vu on this topic but i may have discussed it with someone else and not you @brianpursley ?

this will not work.
```
cd cmd/kubeadm
go test ./...
```

you have to do:
```
cd cmd/kubeadm/app
go test ./...
```

as you may have figured out, `cmd/kubeadm/test` contains integration tests that should not be run run without the required env vars.

> panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path
> [recovered]
>	panic: the environment variable KUBEADM_PATH must point to the kubeadm binary path

this should not be fixed, as the integration test needs a binary.
also we should not move the kubeadm integration tests to another location.

i don't think we should take any action here. also kubeadm is moving out of k/k at some point in the (near) future.

/priority awaiting-more-evidence

**Comment by liggitt** [comment]
I would expect go tests outside the test/integration and test/e2e packages to be unit tests, and to be able to run `go test ./cmd/...`

**Comment by brianpursley** [comment]
@neolit123 I think we did probably discuss in slack.

I opened an issue to remove that from the docs, but the question was raised why don't we just fix the problem since it just seems to be this one subdirectory that is the problem.

Can these tests be moved to the integration folder and if so would that fix the issue?

**Comment by neolit123** [comment]
this has been the case for while now (possibly 10+ releases) at least, but if sig-testing and others are fine with this we can extract the `./cmd/kubeadm/test` to somewhere in `/test/integration/`.

PRs welcome too, please.

**Comment by liggitt** [comment]
I would also accept skipping the tests if KUBEADM_PATH is unset rather than panicing

**Comment by brianpursley** [comment]
> PRs welcome too, please.

I'll take it and see what I can come up with...

/assign

**Comment by brianpursley** [comment]
@neolit123 @liggitt Here is a PR to move the kubeadm integration tests to the test/integration/kubeadm directory: https://github.com/kubernetes/kubernetes/pull/91826

I think it is a good change because it eliminates some of the special-case handling of kubeadm tests and extracts some of the integration test util functions that got inter-mixed with unit test util functions.

... But...
it wasn't everything I hoped it would be because it still does not allow `go test ./...` to work from the kubernetes root.

`go test ./...` from the root tries to run things in the /test directory.  I just don't think that is a feasible way to run tests, at least not from the root. From a subdirectory it will probably work though.

**Comment by neolit123** [comment]
i've added a couple of comments on the PR. thank you for taking on this.
unclear whether splitting kubeadm source code in two locations is a good idea for the sake of better supporting `go test ...` calls.

> it wasn't everything I hoped it would be because it still does not allow go test ./... to work from the kubernetes root.

i don't think `go test ./...` is an achievable goal or something we should push for.
claiming support for `go test ./cmd/...` makes more sense.

**Comment by brianpursley** [comment]
Yeah, I'm starting to think @liggit's suggestion of just checking KUBEADM_PATH and skipping might be the best next move with least impact...

**Comment by brianpursley** [comment]
Or just leaving it how it is too, and maybe just update the docs like the original idea.

**Comment by neolit123** [comment]
> Yeah, I'm starting to think liggitt 's suggestion of just checking KUBEADM_PATH and skipping might be the best next move with least impact...

i think it used to be like that but i may have broken it with a recent cleanup.

skipping tests in cmd/kubeadm/test if KUBEADM_PATH is not defined messy, but arguably better than moving cmd/kubeadm/test to another location.

**Comment by brianpursley** [comment]
I'm thinking just update the docs to say don't use `go test ./...` from the repository root. 
Besides, there are a number of reasons that won't work, and kubeadm is just one of them.

Also, the more I think about it, I don't really like the idea of conditionally skipping the tests because it could result in the tests being mistakenly skipped when they are supposed to be run... for example, if someday in the future, the integration tests are modified and accidentally unset KUBEADM_PATH, the tests would just stop running (instead of failing) and we wouldn't really know about it unless someone looked closely and noticed they were being skipped.

I'll go ahead and close this issue.  Thanks for talking it through with me and reviewing the PR. I don't mean to waste your time, but it has been valuable to me from a learning standpoint at least.

**Comment by neolit123** [comment]
Ack. Thank you for taking the time to look at this.
