### ISSUE TITLE
"unbound immediate PersistentVolumeClaims" should be UnschedulableAndUnresolvable error 

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#91755]
when a pod has unbound immediate PersistentVolumeClaims, it's unscheduable and unresolvable as the pod must wait for the PV controller to bind these PVCs. ~~In VolumeBinding plugin, we can return an `UnschedulableAndUnresolvable` error to eliminate unnecessary retries~~ (not right, they have the same effect, but `UnschedulableAndUnresolvable` is more meaningful). Once the PVC(s) are bound, pods will be [moved to the active or backoff queue again](https://github.com/kubernetes/kubernetes/blob/1bc526aa6c310b915e7ad57b4442deec7328aad2/pkg/scheduler/eventhandlers.go#L55-L61).

ref: https://github.com/kubernetes/kubernetes/pull/91679#discussion_r434554404

**Comment by cofyc** [comment]
cc @msau42

**Comment by cofyc** [comment]
/priority awaiting-more-evidence

hi, @ahg-g IIUC, both internal error and unscheduable error will mark the pod unscheduable and put it into the unscheduable queue and will not be retried until it's moved to active/backoff queues again?

https://github.com/kubernetes/kubernetes/blob/5dbe3e308af1598536cda3b785fb05b30505990f/pkg/scheduler/factory.go#L479-L516

The reason we report it ("pod has unbound immediate PVCs") as an internal error because it fails fast (will not retry other nodes as it's not necessary). cc @msau42 Am I right?

I think it's more meaningful to report it as an `UnscheduableAndUnresolvable` error. It's a normal case, some PVCs are not bound by PV controller yet.

Now we have `PreFilter` extension point, I guess we should pre-check pod's PVCs in `PreFilter` phase and fail with an `UnscheduableAndUnresolvable` error if the pod must wait for PV controller to bind its immediate PVCs.

What do you think?

**Comment by ahg-g** [comment]
> hi, @ahg-g IIUC, both internal error and unscheduable error will mark the pod unscheduable and put it into the unscheduable queue and will not be retried until it's moved to active/backoff queues again?

Yes, an internal error will not cause preemption logic to execute, which is similar to UnschedulableAndUnresolvable.

 > Now we have PreFilter extension point, I guess we should pre-check pod's PVCs in PreFilter phase and fail with an UnscheduableAndUnresolvable error if the pod must wait for PV controller to bind its immediate PVCs.

A non ```Success``` PreFilter gets converted to Error: https://github.com/kubernetes/kubernetes/blob/5dbe3e308af1598536cda3b785fb05b30505990f/pkg/scheduler/core/generic_scheduler.go#L398

we should change that and support proper rejection of the pod at PreFilter, but for now, lets change the error to ```UnscheduableAndUnresolvable```

**Comment by cofyc** [comment]
created a PR for this: https://github.com/kubernetes/kubernetes/pull/91775 

I found that the overall performance can be improved if we pre-check pod PVCs in the PreFilter phase. In the old scheduler, `podUsePVCs` and `SchedulerBinder.getPodVolumes` are called for every node in the predicate phase, which is unnecessary.
