### ISSUE TITLE
Timeout does not take effect in the Watch method

### ISSUE THREAD

**Issue by kadisi** [kubernetes/kubernetes#91753]
**What would you like to be added**:

Client-go /client has a way to set a context deadline based on a timeout.
Such as LIST and DELETE COLLECTION Method.

However, I find that timeout is not useful in context deadline honored by the transport for the `Watch` method

So for the `Watch` method, do we need to set the context deadline in the future or is it not necessary？

for example：
For `List` method, https://github.com/kubernetes/kubernetes/blob/00a1388dbb56f8bf8c44e2d58f69569ab9836d81/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/deployment.go#L85

it will call `Request.request` method, and set context timeout:
https://github.com/kubernetes/kubernetes/blob/1bc526aa6c310b915e7ad57b4442deec7328aad2/staging/src/k8s.io/client-go/rest/request.go#L843

but for `Watch` method,
https://github.com/kubernetes/kubernetes/blob/00a1388dbb56f8bf8c44e2d58f69569ab9836d81/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/deployment.go#L112

it does not set context timeout.  but the `Timeout` method is still called 

**Why is this needed**:

Therefore, can we cancel the call of `Timeout `method or  set watch's context timeout?

**Comment by kadisi** [comment]
If it needs to be modified, i can work a patch.

**Comment by kadisi** [comment]
cc @deads2k @liggitt

**Comment by fedebongio** [comment]
Hi @kadisi we discussed this one on the triage meeting. 

There are multiple ways of setting timeouts, context is one of them. Can you describe a little bit more how you would expect it to work? 

If you are open to send a PR with a proposed fix we can also take a look. 

Thanks!

**Comment by fisherxu** [comment]
@fedebongio @kadisi   Now for the watch method, `timeout` is not used in the client side, and it will be passed to apiserver in the URL.

So do we need the `timeout` parameter in client for the `watch`?

**Comment by kadisi** [comment]
@fisherxu  @fedebongio i don't think that we need the `timeout` parameter in client for the `watch`
