### ISSUE TITLE
Provide option to disable logrotate on /var/log/pods directory

### ISSUE THREAD

**Issue by loburm** [kubernetes/kubernetes#91767]
**What would you like to be added**:
Environment variable to disable logrotate configuration: https://github.com/kubernetes/kubernetes/blob/f01d848c4808bdaaa1378511c343a63a650f8cf1/cluster/gce/gci/configure-helper.sh#L388

**Why is this needed**:
Starting from 1.11 CRIContainerLogRotation feature is enabled by default. Second one by default performs more often checks then logrotate, so it doesn't makes sense to have both enabled in the same time.

**Comment by wojtek-t** [comment]
@loburm  - Has this been fixed by: https://github.com/kubernetes/kubernetes/pull/93781 ?

/remove-lifecycle stale

**Comment by loburm** [comment]
Yes, it was.
