### ISSUE TITLE
Stop the blocked Get() in workqueue, and without shuttingdown the workqueue

### ISSUE THREAD

**Issue by fisherxu** [kubernetes/kubernetes#91800]
**What would you like to be added**:
Now we have a usage scenario, we need to stop getting items from the workqueue, but without shuttingdown the queue, and the **Add** func can continue to add items to the queue. So at this time, I need a method to stop the blocked Get and to exit the gorouting.

**Why is this needed**:
Add a func like `StopGet` to stop the blocked Get and without shuttingdown the workqueue.

**Comment by fisherxu** [comment]
cc @lavalamp @liggitt @deads2k

**Comment by liggitt** [comment]
can you clarify the use case? blocking a single goroutine on the queue doesn't seem very heavyweight

**Comment by hzxuzhonghu** [comment]
We have met a similar issue in istio .  We need to notify the go routine blocking on queue to exit when it lost the leader.

 FYI https://github.com/istio/istio/pull/24427/files.

**Comment by hzxuzhonghu** [comment]
Now we added a very hack signal here https://github.com/istio/istio/pull/24427/files#diff-daa5c20e27f7d0cedf85f2b3343b8f86R138

**Comment by hzxuzhonghu** [comment]
IMO, this should be a simple feature, without causing compatibility issue.

**Comment by liggitt** [comment]
> we need to stop getting items from the workqueue, but without shuttingdown the queue, and the Add func can continue to add items to the queue

persisting in this state is effectively a memory leak scenario, right? it really seems like the queue should be shut down if there is nothing draining it

**Comment by fisherxu** [comment]
> persisting in this state is effectively a memory leak scenario, right? it really seems like the queue should be shut down if there is nothing draining it

The queue will be reused in other goroutings, so shouldn't be shut down, just stop it here and without affecting other gorouting.

We used workqueue in a server's send queue, when the connection is disconnected, we need to stop Get here and exit this gorouting and and let the new connection corresponding gorouting to do the get.

**Comment by lavalamp** [comment]
You have multiple different *kinds* of worker goroutines draining a queue, and you want to shut down only some of the goroutines? I don't understand how that can be correct, neither kind of goroutine will see all queue entries.

I think you should make separate queues for each kind of worker.

**Comment by lavalamp** [comment]
Closing this -- we can reopen if there's more info.

**Comment by hzxuzhonghu** [comment]
@lavalamp Let me clarify my use case: I need to startup a controller when acquires leadership, and stop the controller when it loses it.

The `controller `, you can just think it similar as k8s cm. So there is no way to notify the sync handler to quit, except sending a very tricky and special  message

**Comment by liggitt** [comment]
> I need to startup a controller when acquires leadership, and stop the controller when it loses it

It still sounds like the appropriate action would be to stop to workqueue

**Comment by hzxuzhonghu** [comment]
Iiuc, if the queue closed, when we want to use it again, need to recreate a new one

**Comment by liggitt** [comment]
That's correct. Since a stopped queue with no controller loop actively draining it is effectively a memory leak, that is recommended.

**Comment by lavalamp** [comment]
Right, you should stop the queue in this situation, tear everything down. If you get the election later, just start everything again.

**Comment by liggitt** [comment]
closing this with the recommended approach of stopping the queue and creating a new one if needed

/close
