### ISSUE TITLE
How to use PodDisruptionBudgets to do a controlled rollout across multiple StatefulSet (e.g., for a multi-zone Elasticsearch cluster)

### ISSUE THREAD

**Issue by jgoeres** [kubernetes/kubernetes#91808]
I have the following scenario: I want to set up an Elasticsearch cluster spread across multiple zones, and for that I use multiple statefulsets 

Note that is almost the same scenario as described in https://github.com/kubernetes/kubernetes/issues/58146 (not for different node types, though, but for different availability zones). Since that issue has been closed for a while, I decided to create a new one

When I do , e.g., a "helm upgrade" to change the ES config or rollout a new image, I want the total number of not running pods to be limited across ALL those statefulsets to avoid a cluster outage. For example, if I have three zones and 1 ES instance per zone, only one of the pods should be restarted at any given time. Alas, out of the box this doesn't work. Since the statefulsets are independent of each other, the single pod in each is stopped and restarted, taking down the entire ES cluster.

The documentation actually mentions how to use PDBs for "non-standard" controllers:
https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors

So I tried specifying a PDB that would match the pods of all my statefulsets - alas, this didn't make a difference. Any way this can be accomplished? Target platform is EKS, so I am stuck with Kubernetes 1.15.

**Comment by jgoeres** [comment]
The obvious wokraround that comes to my mind is patching the STSes one after the other:

Workaround is to patch each STS individually, like this:

Create a patch file patch-es-version.yaml with this content:

—

spec:
  template:
    spec:
      containers:
      - name: elasticsearch
        image: <ECR-REGISTRY>.dkr.ecr.eu-central-1.amazonaws.com/xyz/elasticsearch:<NEWVERSION>
—


and apply it to each of the STSs one by one, waiting for the patch to be completed rolled out on one STS and shards being re-allocated properly (=cluster green again) before doing the patch on the next STS:

kubectl patch sts elasticsearch-eu-central-1a --patch "$(cat patch-es-version.yaml)"

kubectl patch sts elasticsearch-eu-central-1b --patch "$(cat patch-es-version.yaml)"

kubectl patch sts elasticsearch-eu-central-1c --patch "$(cat patch-es-version.yaml)"

I think even if we were able to solve the "at most one pod down across multiple statefulsets" with a PDB, this of course would only consider the pod readiness, but not wait for the ES cluster to be in green state again.

**Comment by b2cbre** [comment]
K8s is by far one of the best infrastructure tools I have ever used or seen in my career.

Surely there's a solution beyond individually patching each set.  Such a rollout method contradicts the design pattern of tools like CNCF's Helm and Flux's Helm Controller.

Perhaps the unspoken & desired design of the Kube Scheduler includes PDBs limited to a single resource instance--e.g. a single statefulset?  If so, maybe the docs need to be updated to reflect this.

I believe many smart people out there have figured out how to do this using a tool (k8s operator perhaps?) but it is not yet well known.  Might even be a knowledge gap on how to use Helm.  I and my team would enjoy a solution not requiring us to break from the Helm upgrade feature set--e.g. individual patches.  We'll keep chipping at this problem, but please do share if anyone viewing this thread knows. :)

**Comment by b2cbre** [comment]
It is interesting that service resources can target any pod that matches its selector. I've encountered bugs in our deployment manifests whereby our selectors were not tight enough and traffic was routed to instances that should not have been servicing requests.

This is not an attempt at sarcasm.  I'm genuinely curious.

Why then are the selectors on PDBs different in behavior?

**Comment by michaelgugino** [comment]
/sig apps
This is already supported in many recent releases.  I think we can close this.

**Comment by PSjoe** [comment]
I've run into this as well, running 1.21.2 (AWS hosted).  I have a PodDisruptionBudget  that selects pods from multiple statefulesets by pod label.  I can see that they PDB does, indeed, cover all the pods I expect it to when I look at it.  I have 5 pods from three different StatefulSetSets.  The PDB looks like this:  
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
 <lines omitted for brevity>
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      algod_flavour: api
      app: algorand-algod
      ledger: betanet
status:
  conditions:
  - lastTransitionTime: "2021-07-23T19:27:39Z"
    message: ""
    observedGeneration: 1
    reason: SufficientPods
    status: "True"
    type: DisruptionAllowed
  currentHealthy: 5
  desiredHealthy: 4
  disruptionsAllowed: 1
  expectedPods: 5
  observedGeneration: 1
```

When I apply an update to two of the StatefulSets at the same time, I can see where kubernetes is updating both StatefulSets at once, taking 2 pods off line, even though I have a max PDB of 1.

```
betanet1-algod-algorand-api-0                            0/2     PodInitializing   0          33s
betanet2-algod-algorand-api-0                            2/2     Running           0          12m
betanet2-algod-algorand-api-1                            2/2     Running           0          10m
betanet2-algod-algorand-api-2                            0/2     PodInitializing   0          33s
```

When I do something like a `node drain`, the PDB is respected.

**Comment by joswiatek** [comment]
For anyone who was surprised by this PDB behavior and ended up on this issue via google, I found [this section](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#:~:text=Pods%20which%20are,specific%20workload%20resource.) of kubernetes documentation useful. It details why this occurs, excerpt included below

> Pods which are deleted or unavailable due to a rolling upgrade to an application do count against the disruption budget, but workload resources (such as Deployment and StatefulSet) are not limited by PDBs when doing rolling upgrades. Instead, the handling of failures during application updates is configured in the spec for the specific workload resource.

AFAIK, the method described above of applying helm updates sequentially instead of in parallel is the best solution to this problem.

**Comment by dabest1** [comment]
[PodUnavailableBudget](https://openkruise.io/docs/user-manuals/podunavailablebudget) from OpenKruise might be useful in solving your issue.
