### ISSUE TITLE
Networking: K8s pods unkown host exception to call api outside world

### ISSUE THREAD

**Issue by Khamphai** [kubernetes/kubernetes#91809]
My application spring boot to develop and use docker image openjdk:11-jdk to build image
previously I use alpine version of the image and ran into problem which sometimes the pod is not able to connect to k8s dns
after changing back to base openjdk:11-jdk version, the dns discovery is resolved, yet sometimes, every 10-20, it takes so long about 14-16 seconds to reach destination (other service within the cluster)

**Comment by rikatz** [comment]
@Khamphai can you please check if this is the case: https://github.com/kubernetes/kubernetes/issues/88986?

Flannel, VXLan, disabling tx offload works, etc?

Thanks!

**Comment by rikatz** [comment]
@Khamphai was the previous related issue your case. If so can this issue be closed?

Thank you

/sig network
/remove-kind feature
/triage support

**Comment by rikatz** [comment]
@Khamphai friendly ping :)

I'll close this issue in 7 days if there's no answer, as this is going to became stale due to lack of answer :)

Thank you!

/triage needs-information
