### ISSUE TITLE
Deprecate ResourceLimitsPriorityFunction feature in the scheduler

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#91817]
[ResourceLimitsPriorityFunction](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L200:2) has bee in alpha since 1.9. Since then, no requests were made to graduate the feature, which indicates lack of usage. Based on that I propose we deprecate this scoring function.

/cc @aveshagarwal
/sig scheduling

**Comment by aveshagarwal** [comment]
no objection from my side.

**Comment by SataQiu** [comment]
If you don't object, I can help to file a PR for this. @ahg-g @aveshagarwal

**Comment by ahg-g** [comment]
Sounds good

/assign @SataQiu

**Comment by Huang-Wei** [comment]
@ahg-g we need a doc PR working on this.
