### ISSUE TITLE
Unable to use v1 version of SubjectAccessReview request even after setting --runtime-config=authorization.k8s.io/v1=true webhook authz mode

### ISSUE THREAD

**Issue by Anumita** [kubernetes/kubernetes#91821]
**What happened**:
I am using a webhook to do authorization checks for users. While setting the kube-apiserver flags to use the webhook, i have set the "runtime-config" parameter to "authorization.k8s.io/v1". Even after setting this parameter the SubjectAccessReview request calls that my webhook is receiving are from "authorization.k8s.io/v1beta1". 

Webhook mode flags set in ApiServer

--runtime-config=authentication.k8s.io/v1beta1=true
--runtime-config=authorization.k8s.io/v1=true
--authentication-token-webhook-config-file=/etc/kubernetes/manifests/guard-webhook.yaml
--authorization-mode=Node,Webhook,RBAC
--authorization-webhook-config-file=/etc/kubernetes/manifests/guard-webhook-authz.yaml 
--authorization-webhook-cache-authorized-ttl=5m0s
--authorization-webhook-cache-unauthorized-ttl=1m0s

SAR request that comes to my webhook:

{"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"verb":"list","version":"v1","resource":"nodes","name":"some-name"},"user":"some-user","group":["system:nodes","system:authenticated"]},"status":{"allowed":false}}

Are there any other parameters that i need to set so that my webhook receives v1 version requests of SAR?
 
**What you expected to happen**:
Webhook should receive SAR requests of v1 version

**How to reproduce it (as minimally and precisely as possible)**:
I am able to repro this by configuring webhook authn and authz with AAD. Working on generic repro.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AKS-Engine
- OS (e.g: `cat /etc/os-release`):
  NAME="Ubuntu"
  VERSION="16.04.6 LTS (Xenial Xerus)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 16.04.6 LTS"
  VERSION_ID="16.04"
- Kernel (e.g. `uname -a`):
  Linux anshenoVM 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
`--runtime-config` does not control the version sent to the authorization webhook. 

Use `--authorization-webhook-version=v1` to configure the version sent to the authorization webhook.

**Comment by Anumita** [comment]
Hey,

I am getting the following error in apiserver {"log":"Error: unknown flag: --authorization-webhook-version\n","stream":"stderr","time":"2020-06-05T14:55:49.639032467Z"}

Is it only after a specific version of K8s?

**Comment by liggitt** [comment]
Yes. Added in https://github.com/kubernetes/kubernetes/pull/85441 in 1.17
