### ISSUE TITLE
RuntimeClass quota

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#91845]
**What would you like to be added**:
A way to specify pods/requests/limits per RuntimeClass the same way you can set limits on individual StorageClasses

**Why is this needed**:
Your cluster may be split in such a way that you need to limit a project to a particular RuntimeClass or set the proportion of resource they can consume in each RuntimeClass.

**Comment by ingvagabund** [comment]
Hello @kfox1111 

> A way to specify pods/requests/limits per RuntimeClass the same way you can set limits on individual StorageClasses

Checking https://kubernetes.io/docs/concepts/storage/storage-classes/ I don't see any mention of limits for storage classes. Can you more elaborate on what you want to be added? E.g. with an example?

> Your cluster may be split in such a way that you need to limit a project to a particular RuntimeClass 

Setting pod defaults is handled by admission plugins. By project here do you mean a namespace with a set of objects?

> or set the proportion of resource they can consume in each RuntimeClass.

By resource proportion do you mean a percentage or setting a fixed amount?

In general, for request like this it's recommended to write a KEP or provide more information in description so the community have a better picture of what you need and can help to point you to the right SIG or component owners at least.

I also don't see any mention of runtime class in the scheduler code. Documentation at https://kubernetes.io/docs/concepts/containers/runtime-class/#usage mentions the use of `runtimeClassName` field (`RuntimeClassName *string` in `PodSpec`). The docs also says:
```
This will instruct the Kubelet to use the named RuntimeClass to run this pod.
If the named RuntimeClass does not exist, or the CRI cannot run the corresponding
handler, the pod will enter the Failed terminal phase.
```
Which indicates the scheduler is not aware of the runtime class. Which might be related to the fact the Node object does not share which runtime classes are available (though I might be wrong). 

Given you want to limit pods to a runtime class, you will need to introduce a new Filter plugin at least so the collaboration with SIG-scheduling will be required. Though, based on [kubernetes-v1.12-introducing-runtimeclass](https://kubernetes.io/blog/2018/10/10/kubernetes-v1.12-introducing-runtimeclass) from 2018, runtime classes are owned by sig-node. Which I think is the right starting point for now.

/sig node

**Comment by kfox1111** [comment]
> Hello @kfox1111
Hi @ingvagabund 

> > A way to specify pods/requests/limits per RuntimeClass the same way you can set limits on individual StorageClasses
> 
> Checking https://kubernetes.io/docs/concepts/storage/storage-classes/ I don't see any mention of limits for storage classes. Can you more elaborate on what you want to be added? E.g. with an example?

In the quota object (https://kubernetes.io/docs/concepts/policy/resource-quotas/), you can add to the spec things like:
  <storageclassname>.storageclass.storage.k8s.io/requests.storage: 20Gi
  <storageclassname>.storageclass.storage.k8s.io/persistentvolumeclaims: 8

This allows the admins to limit how many volumes can be created and how much capacity is granted, per storage class. This really helps when you have say a big pool of spinny disk and a small pool of low latency ssd and want to ensure users get their fair share.

I think we just need something similar for runtimeClass.

> Setting pod defaults is handled by admission plugins. By project here do you mean a namespace with a set of objects?

Yes, sorry. I'd like to limit the amount of each runtime class can be allocated per namespace.

> > or set the proportion of resource they can consume in each RuntimeClass.
> 
> By resource proportion do you mean a percentage or setting a fixed amount?

Fixed amount, similar to it works now with regular quota. Just per resourceClass.

> In general, for request like this it's recommended to write a KEP or provide more information in description so the community have a better picture of what you need and can help to point you to the right SIG or component owners at least.

Ok, yeah. A KEP is probably the next step.

> I also don't see any mention of runtime class in the scheduler code. Documentation at https://kubernetes.io/docs/concepts/containers/runtime-class/#usage mentions the use of `runtimeClassName` field (`RuntimeClassName *string` in `PodSpec`). The docs also says:
> 
> ```
> This will instruct the Kubelet to use the named RuntimeClass to run this pod.
> If the named RuntimeClass does not exist, or the CRI cannot run the corresponding
> handler, the pod will enter the Failed terminal phase.
> ```
> 
> Which indicates the scheduler is not aware of the runtime classes. Which might be related to the fact the Node object does not share which runtime classes are available (though I might be wrong).

Yes/No. Starting in 1.18 there is a beta for runtimeClasses to add nodeSelectors/tolerations. They are automatically injected into the pod by runtimeClassName reference. This gives the scheduler enough information to schedule the workload to the appropriate node. It completely reuses existing pluming so doesn't show up in the scheduler directly. That part works great already though. We just need a way to limit the amount of pods of a particular runtimeClass can be consumed. Quota I think is the right place to do that.

> Given you want to limit pods to a runtime class, you will need to introduce a new Filter plugin at least so the collaboration with SIG-scheduling will be required. Though, based on [kubernetes-v1.12-introducing-runtimeclass](https://kubernetes.io/blog/2018/10/10/kubernetes-v1.12-introducing-runtimeclass) from 2018, runtime classes are owned by sig-node. Which I think is the right starting point for now.

I think the existing admission controller that implements Quota today already has all the hooks nessisary. It just needs finer grained nobs then just pods count/limits/resources but also taking into account optionally, values per runtimeClass.

> /sig node

Thanks!
Kevin

**Comment by kfox1111** [comment]
/remove-lifecycle stale

still relevant.

**Comment by kfox1111** [comment]
/remove-lifecycle stale

still relevant.

**Comment by SergeyKanzhelev** [comment]
@kfox1111 can you please explain how you use RuntimeClass. It is intended to use to "balance of performance versus security" when running pods. In other words, use a different ways to virtualize. Let's say you can run pods in ultra-secure 
environment using RuntimeClass. What would be the reason to limit the number of resources these secure pods can consume? Would namespaces work better for your use case?

**Comment by kfox1111** [comment]
Multiple reasons. security isolation is one. but yeah, you could probably use namespace isolation too with that.

Another:
Say you have 2 pools of nodes with different hardware specs. Some are good at thing A, and some are good at thing B.

You label/taint the sets of nodes, and make a runtime class so the user can easily select between the two. If the size of A is significantly bigger then B, then a generic quota wouldn't help. A generic quota that covers reasonable usage of A may allow the complete over allocation of the B pool. This could be for things like long running services, vs hpc like jobs. Each may get different hardware.

A more concrete example:
Say you have some workloads that are not 100% cloud native yet (will use a not great but understandable example). Say single pod instances of mysql that you cant cluster for whatever reason. Deletion of these pods are disruptive to the rest of the services. But this does fly in the face of upgrading the nodes as frequently as possible. So, you split your cluster into two sets of nodes. A regular pool where 100% cloud native workloads run and the nodes are possibly automatically upgraded, and a enhancedavailability node pool where they are less frequently updated (monthly say) to provide greater workload availability. This makes the best of the situation. But if you don't quota things, folks may be inclined to just push everything to the enhancedavailability node pool, since its "easier", giving an incentive not to try and make as much cloud native as possible. You still want the choice of which pool to use to be per namespace but quotas need to be different to avoid abuse.

**Comment by haircommander** [comment]
@kfox1111 thanks for opening the issue. Do you have any interest in opening a KEP and driving this work?

**Comment by egernst** [comment]
Hey @kfox1111 - I was thinking through this, and alternative options if I had to handle.  My thoughts below; curious if you can clarify and provide feedback. 

It seems in general, you're trying to limit the # of pods (not necessarily pod specific geometries?) that use a particular runtimeclass.

In your scenario, do you have only a subset of nodes already which will allow running runtimeclass foo? And, are they tainted so only workloads that specific runtimeClassName foo schedule there? If you can, or do, this would be a way to limit the # of pods which use the runtimeClass directly, right (ie size of pool * Max pods per node)?

Are you generally trying to limit access to a particular runtimeclass? Ie, you can introduce a validation policy to ensure only ns on allow list may specify the runtimeClass in the pod spec? Now instead of trying to push things at runtime, you can manage namespaces for who you think can and should and should not have access?

It almost sounds like you are using the same handle for each runtimeclass, but trying to leverage the runtimeclass admission controller which'll set a runtimeclass specific toleration/nodeSelector?

If you're doing this, it seems like just enforcing quota per namespace and applying an appropriate nodeSelector per namespace would also work (or, again, validate which ns has access to the runtimeclass)?

**Comment by kfox1111** [comment]
Say I have 2 pools of nodes, with runtime classes set for each, each pointing at runc. Foo runtimeclass, has nodeselectors/tolerations for nodes labeled pool=foo, and Bar runtimeclass, has nodeselctors/tolerations for nodes labeled pool=bar
There are 10 nodes labeled pool=foo and 3 labeled pool=bar

Say I would like to quota a namespace so it can't consume more then 1/3rd of those pools. I can't do that with the existing quota structure, because I could set it at 3/3 ~= 1 nodes worth of resource, but that doesn't allow enough of pool foo to be used. Or if I set it to 10/3 ~= 3.33 they would be able to completely consume all of pool bar.

Its not the number of pods that is a problem. Its the sum total of resources given to the pods of a particular runtime class that needs limiting.

Avoiding the issue by limiting a namespace to only one pool of hardware works in some cases, but not all. More of a workaround.
