### ISSUE TITLE
etcd server overrides is in generic interface but kubeapiserver implementation

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#91848]
**What happened**:
I tried using the `--etcd-servers-overrides` flag on an aggregated apiserver built like the sample-apiserver.  The flag was ignored.

**What you expected to happen**:
I expected the flag to be respected.  It affects the `Etcd` section of a `RecommendedOptions` defined in https://github.com/kubernetes/apiserver/blob/master/pkg/server/options/recommended.go .  https://github.com/kubernetes/sample-apiserver/blob/master/pkg/cmd/server/start.go uses that as its options data structure.

But the interpretation of the data from that flag is in `completedStorageFactoryConfig::New` in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/default_storage_factory_builder.go .  This is invoked by `buildGenericConfig` in https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go .  The kube-apiserver has
```
type Config struct {
	GenericConfig *genericapiserver.Config
	ExtraConfig   ExtraConfig
}
```
in https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go , and that `ExtraConfig` includes `StorageFactory serverstorage.StorageFactory`; the code path that creates the Config from the options invokes `completedStorageFactoryConfig::New`.

The sample-apiserver's Config and ExtraConfig are defined in https://github.com/kubernetes/sample-apiserver/blob/master/pkg/apiserver/apiserver.go ; the ExtraConfig struct is empty.  This server uses `RecommendedOptions::ApplyTo` in https://github.com/kubernetes/apiserver/blob/master/pkg/server/options/recommended.go and this calls `o.Etcd.ApplyTo(&config.Config)` instead of `s.Etcd.ApplyWithStorageFactoryTo(storageFactory, genericConfig)` as the kubeapiserver does.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): this is in master and has been this way for a _long_ time
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@droccom

**Comment by fedebongio** [comment]
/cc @deads2k 
(we thought you would find this approach interesting and may have an opinion)
