### ISSUE TITLE
add a CRD resource with kind only a single chart while cause kube-apiserver crash

### ISSUE THREAD

**Issue by lidajia** [kubernetes/kubernetes#91857]
**What happened**:
add a CRD resource with kind only a single chart while cause kube-apiserver crash（slice bounds out of range）
**What you expected to happen**:
add validation to limit CRD kind definition or fix the bug of slice out of bounds。
**How to reproduce it (as minimally and precisely as possible)**:
`
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rs.crd.test.org
spec:
  group: crd.test.org
  version: v1
  names:
    kind: R
    plural: rs
    singular: r
  scope: Cluster
`

**Anything else we need to know?**:
apiserverlogs:
`16606 10:05:32.237058	6 panic.go:679] Shutting down OpenAPI controller
E6606 10:05:32.237233	6 runtime.go:78] Observed a panic: runtime.boundsError{x:-1, y:1, signed:true, code:0x3> (runtime error: slice bounds out of range [-1:])
goroutine 1670 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41458a0, Gxc00ed66d40)
/workspace/anago-v1.17.G-rc.2.1G+7G132bGf130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/workspace/anago-v1.17.G-rc.2.1G+7G132bGf130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82 panic(0x41458a0, Oxc0Oed66d40)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.GetArticleForNoun(0x7493232, 0x1, 0x447d778, 0x1, 0x130, 0xc00ed13680)
/workspace/anago-v1.17.0-rc.2.1G+7G132bGf130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1056 +0x2b8 k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.("builder).descriptionFor(€xc007b351f0, 0x0, 0x0, 0x4481982, 0x6, Gxc00ed06d00, 0x18)
/workspace/anago-v1.17.0-rc.2.1G+7G132bGf130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder.go:243 +0x3c6 k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.("builder).buildRoute(GxcGG7b351fG, 0xc00ed66d00, 0x18, 0x0, 0x0, 0x447f0F3, 0x4, 0x447f71b, 0x4, 0x4481982, ...)
/workspace/anago-v1.17.0-rc.2.1G+7G132bGf130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder .go :281 +0x197 k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.BuildSwagger(0xc66b7bcfd0, 0xc005d24a3c, 0x2, 0x101, 0x1, 0x2, Gxc60b76aec8)
/workspace/anago-v1.17.0-rc .2.10+70132b0F130acc/src/k8s .io/kubernetes/_output/dockerized/go/src/k8s .io/kubernetes/vendor/k8s .io/apiextensions-apiserver/pkg/controller/openapi/builder/builder .go :146 +0x49d k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi.buildUersionSpecs(0xc66b7bcfd0, 0x0, Oxb, Gx447f1db, 0x4, 0x1)
/workspace/anago-v1.17.0-rc.2.10+70132b0F130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go:204 +0x1a8 k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi.("Controller).Run(0xc0012c8050, Gxc0G1d61200, 0xc007a6d1e0, 0xc069cced80)
/workspace/anago-v1.17.0-rc.2.10+70132b0F130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go:105 +0x2da created by k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.conpletedConfig.New.func2
/workspace/anago-v1.17.0-rc.2.10+70132b0F130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver .go :236 +0x244 panic: runtime error: slice bounds out of range [-1:] [recovered] panic: runtime error: slice bounds out of range [-1:]`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lidajia** [comment]
> @lidajia: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

/sig apps

**Comment by tedyu** [comment]
```
only a single chart
```
There is a typo in the subject.
