### ISSUE TITLE
Reconfiguring a kubelet does not work on EKS

### ISSUE THREAD

**Issue by scardena** [kubernetes/kubernetes#91865]
**What happened**:
I was trying to reconfigure a kubelet in EKS following this: https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/
I got no error whatsoever while following the steps, but the config is not being recognized by the kubelet.

**What you expected to happen**:
The config to the kubelet in this specific node should be updated.

**How to reproduce it (as minimally and precisely as possible)**:
Assuming you have access to a working EKS cluster.
```
kubectl proxy --port=8001 &

# get the current kubelet config for this node.
curl  -sSL http://localhost:8001/api/v1/nodes/some-node-name/proxy/configz | jq '.kubeletconfig|.kind="KubeletConfiguration"|.apiVersion="kubelet.config.k8s.io/v1beta1"' > old-kubelet-config.yaml

#Do the changes you want to old-kubelet-config.yaml. In my case, im setting anonymous enabled = true for testing purposes

# Create a config map with the new configs for the kubelet
kubectl -n kube-system create configmap node-config --from-file=kubelet=old-kubelet-config.yaml  --append-hash -o yaml

# Edit the node configs so the kubelet overrides the configs set either on launch or from a config file, so it uses the configmap instead. This node name should be the same as in step 2
kubectl edit node some-node-name
```

this is how my node config looks after editing:

```
spec:
  configSource:
    configMap:
      kubeletConfigKey: kubelet
      name: node-config-ckb9t8mk7c
      namespace: kube-system
  providerID: aws:///us-west-2b/i-xxxxxxxx
```
I even went into the node, and restarted the kubelet. The change does not apply either way.

**Anything else we need to know?**:
There is one step I am not sure if i need to follow or not:
> Note: You need to manually add the kind and apiVersion to the downloaded object, because those fields are not reported by the configz endpoint. 

I am not sure if this outdated or not, but I can see the output of configz does return the json, and at the very end:
```
  "kind": "KubeletConfiguration",
  "apiVersion": "kubelet.config.k8s.io/v1beta1"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

- Cloud provider or hardware configuration:
AWS EKS 1.16
- OS (e.g: `cat /etc/os-release`):
macos Catalina
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Does EKS enable dynamic Kubelet config?

**Comment by scardena** [comment]
@liggitt that might be the reason, seems like managed node groups doesn't support dynamic kubelet by default, and there is no easy way to make them support it. There is a work in progress that will allow this in the future: https://github.com/aws/containers-roadmap/issues/596
Thanks!
