### ISSUE TITLE
CRD  creation failed due to spec.validation.openAPIV3Schema.properties[spec].properties[license].properties[accept].default: Forbidden: must not be set

### ISSUE THREAD

**Issue by PurnimaChawla** [kubernetes/kubernetes#91872]
I am have property added and a default value is given to it.
I am getting Forbidden error: must not be set.
Is it a version specific issue??

**Comment by SataQiu** [comment]
Did you enable `CustomResourceDefaulting` feature gate? 
Ref: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features  https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation

**Comment by liggitt** [comment]
default attributes are only allowed in v1 CRDs

**Comment by PurnimaChawla** [comment]
I am using v1beta1 CRD version.

**Comment by liggitt** [comment]
To create a CRD that uses the defaulting feature, you will need to use the v1 CRD API.

**Comment by PurnimaChawla** [comment]
so you mean in v1beta1 version, it will not support? 
it should be just v1

**Comment by liggitt** [comment]
correct, `apiextensions.k8s.io/v1` CRDs support specifying the `default` attribute for properties

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/91928 to clarify the reason in the returned message

**Comment by PurnimaChawla** [comment]
but if for version v1beta1 I want to enable the defaulting through feature gate, it that possible? 
will it support? I am using  ocp 4.3 which has Kubernetes version 1.16

**Comment by liggitt** [comment]
no, using the v1 API is required to add default values to a CRD
