### ISSUE TITLE
[Failing Test] conformance-ga-only (ci-kubernetes-conformance-kind-ga-only)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#91878]
**Which jobs are failing**:
> ci-kubernetes-conformance-kind-ga-only`

**Which test(s) are failing**:
> Overall

**Since when has it been failing**:
> 06-06 16:48 PDT

**Testgrid link**:
>https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only

**Reason for failure**:
> azelle: /bazel-scratch/.cache/bazel/_bazel_root/cae228f2a89ef5ee47c2085e441a3561/external/org_golang_x_tools/go/packages/packagestest/testdata/groups/two/modules/example.com/what@v1.1.0/main.go: error reading go file: /bazel-scratch/.cache/bazel/_bazel_root/cae228f2a89ef5ee47c2085e441a3561/external/org_golang_x_tools/go/packages/packagestest/testdata/groups/two/modules/example.com/what@v1.1.0/main.go:1:16: expected ';', found '.'
gazelle: finding module path for import domain.name/importdecl: exit status 1: can't load package: package domain.name/importdecl: cannot find module providing package domain.name/importdecl
gazelle: finding module path for import old.com/one: exit status 1: can't load package: package old.com/one: cannot find module providing package old.com/one
gazelle: finding module path for import titanic.biz/bar: exit status 1: can't load package: package titanic.biz/bar: cannot find module providing package titanic.biz/bar
gazelle: finding module path for import titanic.biz/foo: exit status 1: can't load package: package titanic.biz/foo: cannot find module providing package titanic.biz/foo
gazelle: finding module path for import fruit.io/pear: exit status 1: can't load package: package fruit.io/pear: cannot find module providing package fruit.io/pear
gazelle: finding module path for import fruit.io/banana: exit status 1: can't load package: package fruit.io/banana: cannot find module providing package fruit.io/banana
gazelle: finding module path for import lib: exit status 1: can't load package: package lib: malformed module path "lib": missing dot in first path element
gazelle: finding module path for import nosuchpkg: exit status 1: can't load package: package nosuchpkg: malformed module path "nosuchpkg": missing dot in first path element
gazelle: finding module path for import lib: exit status 1: can't load package: package lib: malformed module path "lib": missing dot in first path element
gazelle: finding module path for import nosuchpkg: exit status 1: can't load package: package nosuchpkg: malformed module path "nosuchpkg": missing dot in first path element
gazelle: finding module path for import lib: exit status 1: can't load 

**Anything else we need to know**:

/sig testing
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by liggitt** [comment]
That error doesn't seem specific to this job

**Comment by hkamel** [comment]
I see the following

> Jun  8 01:10:12.466: INFO: Running '/home/prow/go/src/k8s.io/kubernetes/bazel-bin/cmd/kubectl/linux_amd64_pure_stripped/kubectl --server=https://127.0.0.1:35577 --kubeconfig=/root/.kube/kind-test-config exec --namespace=statefulset-3918 ss-2 -- /bin/sh -x -c mv -v /tmp/index.html /usr/local/apache2/htdocs/ || true'
Jun  8 01:10:13.888: INFO: rc: 1
Jun  8 01:10:13.888: INFO: Waiting 10s to retry failed RunHostCmd: error running /home/prow/go/src/k8s.io/kubernetes/bazel-bin/cmd/kubectl/linux_amd64_pure_stripped/kubectl --server=https://127.0.0.1:35577 --kubeconfig=/root/.kube/kind-test-config exec --namespace=statefulset-3918 ss-2 -- /bin/sh -x -c mv -v /tmp/index.html /usr/local/apache2/htdocs/ || true:
Command stdout:

> stderr:
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "f53a43d5c472b8828f85327115508ae2609db1a7b008d83eab3b8f326fd918fe": OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown

> error:
exit status 1
Jun  8 01:10:23.890: INFO: Running '/home/prow/go/src/k8s.io/kubernetes/bazel-bin/cmd/kubectl/linux_amd64_pure_stripped/kubectl --server=https://127.0.0.1:35577 --kubeconfig=/root/.kube/kind-test-config exec --namespace=statefulset-3918 ss-2 -- /bin/sh -x -c mv -v /tmp/index.html /usr/local/apache2/htdocs/ || true'
Jun  8 01:10:24.755: INFO: rc: 1
Jun  8 01:10:24.755: INFO: Waiting 10s to retry failed RunHostCmd: error running /home/prow/go/src/k8s.io/kubernetes/bazel-bin/cmd/kubectl/linux_amd64_pure_stripped/kubectl --server=https://127.0.0.1:35577 --kubeconfig=/root/.kube/kind-test-config exec --namespace=statefulset-3918 ss-2 -- /bin/sh -x -c mv -v /tmp/index.html /usr/local/apache2/htdocs/ || true:
Command stdout:

> stderr:
error: unable to upgrade connection: container not found ("webserver")

**Comment by liggitt** [comment]
I don't see actual test failures, this appears to be a timeout at 2 hours. Successful runs typically range between 95 and 110 minutes (I saw one that took [117 minutes](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/1266694769862512640)), so a slight build or test run delay would hit the timeout.

I know of two conformance tests that were just added last week, but there have been two successful runs since they were added, and they are very fast (9 and 2 seconds, respectively).

I don't enough history on the test job to know if build or test performance regressed or if we've just added new conformance tests and crept up to our timeout. In general, I'd expect more headroom than 5-10% on timeouts over normal run times.

**Comment by liggitt** [comment]
@BenTheElder, any idea why these two kind conformance jobs would look different, runtime-wise?

* https://testgrid.k8s.io/conformance-kind#conformance,%20master%20(dev)&width=20&graph-metrics=test-duration-minutes
* https://testgrid.k8s.io/conformance-kind#conformance-ga-only&width=20&graph-metrics=test-duration-minutes

**Comment by liggitt** [comment]
looks like https://github.com/kubernetes/kubernetes/pull/80545 just got merged which added ~3 minutes of tests

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/4badfd9f3777ed2ceb9eab83832bbab4bfa9bf19/config/jobs/kubernetes/sig-testing/conformance-e2e.yaml#L189
https://github.com/kubernetes/test-infra/blob/2eab27db6e653d809cd48ad06a35462f1aa3cf0e/config/jobs/kubernetes-sigs/kind/kind.yaml#L30
I don't see anything interesting config wise
- same image
- both decorated jobs
- same timeout I think, but one is explicit
- one sets GINKGO_TOLERATE_FLAKES but that's set in the bash now I think
- one sets GA_ONLY
- one still mounts the prow GCP service account but it's unused

**Comment by liggitt** [comment]
if anything, I would have expected the GA_ONLY job to be slightly faster since discovery calls have to traipse through fewer API groups

**Comment by BenTheElder** [comment]
Ah wait -- I think only the GA only one is on the new WG k8s prow cluster
... Cluster may be overloaded still? cc @spiffxp

**Comment by liggitt** [comment]
looks like APIListChunking and APIResponseCompression features are still beta... those being off could hurt performance a bit, though I'd only expect them to matter in large clusters

**Comment by hkamel** [comment]
/sig scheduling

observing time out 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
Jun 10 09:55:49.851: failed pod observation expectations: rs1 had more than 2 pods created: 3
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:655
```

```
I0610 09:29:31.689] nc: connect to affinity-clusterip port 80 (tcp) timed out: Operation in progress
I0610 09:29:31.689] command terminated with exit code 1
I0610 09:29:31.689] 
I0610 09:29:31.689] error:
I0610 09:29:31.689] exit status 1
I0610 09:29:31.689] Retrying...
skipped 3432 lines unfold_more
I0610 09:55:03.389]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
I0610 09:55:11.772] Jun 10 09:55:11.772: INFO: pods created so far: [1 1 1]
I0610 09:55:11.772] Jun 10 09:55:11.772: INFO: length of pods created so far: 3
I0610 09:55:47.851] Jun 10 09:55:47.851: INFO: pods created so far: [3 4 1]
I0610 09:55:49.851] Jun 10 09:55:49.851: INFO: pods created so far: [3 4 1]
I0610 09:55:49.852] Jun 10 09:55:49.851: FAIL: failed pod observation expectations: rs1 had more than 2 pods created: 3
```

**Comment by hkamel** [comment]
Thanks @Huang-Wei the job is successful since 06-08 04:59 PDT
