### ISSUE TITLE
Upgrade grpc dependency

### ISSUE THREAD

**Issue by tedyu** [kubernetes/kubernetes#91881]
**What happened**:
Currently we use grpc v1.26.0
There is a bug where temporary failure of DNS resolution will bring client down until it is restarted. See grpc/grpc-go#3353

**What you expected to happen**:
We should upgrade to grpc release which has the fix.
Compatibility should be evaluated carefully between the components involved: etcd, api server, controllers, etc

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
blocked on https://github.com/kubernetes/kubernetes/issues/91266

**Comment by tedyu** [comment]
One remaining item: #92078 for image building

**Comment by tedyu** [comment]
#92078 has been merged.

**Comment by nikhita** [comment]
Related - https://github.com/kubernetes/kubernetes/issues/93320

/sig architecture
/area code-organization
