### ISSUE TITLE
Kubelet sometimes slow to delete pods

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#9188]
Spinoff from a conversation on https://github.com/GoogleCloudPlatform/kubernetes/pull/9165, I haven't had the time to dig into this yet. Tl;dr version is that graceful deletion is sometimes sluggish with simple ubuntu echo pods on a lightly loaded system. https://github.com/GoogleCloudPlatform/kubernetes/pull/9165#issuecomment-108186294 indicates a possible race. Also discussed on https://github.com/GoogleCloudPlatform/kubernetes/issues/6764.

**Comment by yujuhong** [comment]
The potential cause of the slow pod deletion has been identified in #9165, and it is not related to race conditions. Once the PR is fixed and verified, we can close this issue.

**Comment by resouer** [comment]
Should this be closed now?

**Comment by yujuhong** [comment]
Sure.
