### ISSUE TITLE
Where is the new Hyperkube repo now?

### ISSUE THREAD

**Issue by JohnJAS** [kubernetes/kubernetes#91897]
It looks like Hyperkube is not available in kubernetes  repo since 1.17, but there is nowhere mentioned about where it is now.

Reference in 1.17:
Hyperkube will now be available in a new Github repository and will not be included in the kubernetes release from 1.17 onwards (#83454, @dims)

**Comment by dims** [comment]
1.18 still has hyperkube image:
https://github.com/kubernetes/kubernetes/tree/release-1.18/cluster/images/hyperkube

1.19 will entirely drop the hyperkube image:
https://github.com/kubernetes/kubernetes/pull/88676

/close
