### ISSUE TITLE
Ping timeout to CoreDNS Pod from another pod, yet ping works from Node Host

### ISSUE THREAD

**Issue by xinwen0328** [kubernetes/kubernetes#91895]
## My CoreDNS Pods and Services:

NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE    IP              
kube-system   coredns-66bff467f8-d9622                   1/1     Running   0          3d1h   10.217.99.129   
kube-system   coredns-66bff467f8-t92zn                   1/1     Running   0          3d1h   10.217.99.130   

NAMESPACE     NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
kube-system   service/kube-dns     ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP,9153/TCP   3d1h

## My Ngnix Pods and Services:
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE    IP              
default       pod/nginx-deployment-6b474476c4-dqsbh          1/1     Running   0          3d1h   10.217.61.195   
default       pod/nginx-deployment-6b474476c4-qzl9w          1/1     Running   0          3d1h   10.217.61.194   
default       pod/nginx-deployment-6b474476c4-x8k5z          1/1     Running   0          3d1h   10.217.61.193   

NAMESPACE     NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE    SELECTOR
default       service/svc-ngnix    ClusterIP   10.111.8.124   <none>        80/TCP                   3d1h   app=nginx

## My Jump Pod:
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE    IP              
default       pod/dnsutils                                   1/1     Running   1          114m   10.217.61.199   
default       pod/jumpod                                     1/1     Running   26         3d     10.217.61.196
## curl works to my ngnix pods and service by using IP
$kubectl exec -it jumpod -- curl 10.217.61.195
This is a test
$ kubectl exec -it jumpod -- curl 10.111.8.124
This is a test

## curl time out to my ngix pods or service by using DNS name
$ kubectl exec -it dnsutils  -- nslookup svc-ngnix
;; connection timed out; no servers could be reached

command terminated with exit code 1

## Ping to my Ngnix Pods works while Ping to CoreDNS doesn't
$ kubectl exec -it jumpod -- ping 10.217.61.195
PING 10.217.61.195 (10.217.61.195) 56(84) bytes of data.
64 bytes from 10.217.61.195: icmp_seq=1 ttl=63 time=0.067 ms

$ kubectl exec -it jumpod -- ping 10.217.99.129
PING 10.217.99.129 (10.217.99.129) 56(84) bytes of data.
^C<<<<<<< No output, so cancelled it 
--- 10.217.99.129 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5110ms

## ping and nslookup works from Cluster Node 
myhost:~$ ping 10.217.99.129
PING 10.217.99.129 (10.217.99.129) 56(84) bytes of data.
64 bytes from 10.217.99.129: icmp_seq=1 ttl=64 time=0.039 ms

3 packets transmitted, 3 received, 0% packet loss, time 2034ms
rtt min/avg/max/mdev = 0.039/0.053/0.062/0.010 ms
myhost:~$ nslookup
> server 10.217.99.129
Default server: 10.217.99.129
Address: 10.217.99.129#53
> www.google.com
Server:		10.217.99.129
Address:	10.217.99.129#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.9.196
Name:	www.google.com
Address: 2607:f8b0:4004:806::2004
> exit

myhost:~$ nslookup
> server 10.96.0.10
Default server: 10.96.0.10
Address: 10.96.0.10#53
> www.google.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	www.google.com
Address: 172.217.2.100
Name:	www.google.com
Address: 2607:f8b0:4004:80a::2004
>

I used calico as my CNI , and  initial my cluster by "kubeadm init --pod-network-cidr=10.217.0.0/16" .  the DNS policy is 'default'.  the cluster is built on two AWS EC2 instance.  anyone can let me know if this normal behavior or not?  appreciate it .

**Comment by neolit123** [comment]
please use the support channels for support questions
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks

/sig cluster-lifecycle
/triage support
/close
