### ISSUE TITLE
Early filtering at PreFilter extension point

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#91904]
Update the semantics of ```PreFilter``` extension point to allow it to act as an early filtering stage. PreFilter can be used to reject pods before evaluating each node at the Filter extension point. This is useful to quickly reject unschedulable pods in cases that don't depend on the particular node (e.g., pod requesting unbound immediate PersistentVolumeClaims).

A non ```Success``` PreFilter gets converted to Error: https://github.com/kubernetes/kubernetes/blob/5dbe3e308af1598536cda3b785fb05b30505990f/pkg/scheduler/core/generic_scheduler.go#L398

We should change that and support proper rejection of the pod at PreFilter. The only acceptable unschedulable status for now should be  ```UnschedulableAndUnresolvable```.

/sig scheduling

**Comment by ahg-g** [comment]
Example: https://github.com/kubernetes/kubernetes/issues/91755

**Comment by ahg-g** [comment]
Hi, any progress on this one @yuzhiquan , I know that you just picked it up, but we need to get this done before the code freeze next week.

**Comment by yuzhiquan** [comment]
> Hi, any progress on this one @yuzhiquan , I know that you just picked it up, but we need to get this done before the code freeze next week.

Working on this, and would finish it on friday.

**Comment by yuzhiquan** [comment]
> > Hi, any progress on this one @yuzhiquan , I know that you just picked it up, but we need to get this done before the code freeze next week.
> 
> Working on this, and would finish it on friday.

Sorry for late pr, but  i misunderstood the issue detail.Still confuse about this `Update the semantics of PreFilter extension point to allow it to act as an early filtering stage`,shoud this issue to update prefilter extention point define?
