### ISSUE TITLE
[Failing Test] Conformance - GCE - master (ci-kubernetes-gce-conformance-latest)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#91911]
**Which jobs are failing**:

`Conformance - GCE - master (ci-kubernetes-gce-conformance-latest)`

**Which test(s) are failing**:

`[sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Conformance]`

**Since when has it been failing**:

`06-08-20 07:22 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
Jun  8 15:43:46.663: Unexpected error:
    <*errors.StatusError | 0xc001b8c000>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Operation cannot be fulfilled on nodes \"bootstrap-e2e-minion-group-9n19\": the object has been modified; please apply your changes to the latest version and try again",
            Reason: "Conflict",
            Details: {
                Name: "bootstrap-e2e-minion-group-9n19",
                Group: "",
                Kind: "nodes",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    Operation cannot be fulfilled on nodes "bootstrap-e2e-minion-group-9n19": the object has been modified; please apply your changes to the latest version and try again
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:124
```

**Anything else we need to know**:

/sig scheduling
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

Looks like changes were introduced here: https://github.com/kubernetes/kubernetes/pull/91243
/cc @cynepco3hahue

**Comment by Huang-Wei** [comment]
@ahg-g the error happened on updating a node:

```go
node, err := cs.CoreV1().Nodes().UpdateStatus(context.TODO(), &node, metav1.UpdateOptions{})
```

So it's less likely related with #91750. I think we should be either using patching instead of updateStatus, or retry to reduce the chances of conflicts.

I will work on a PR.

**Comment by Huang-Wei** [comment]
Basically I think the flake is due to other tests are updating node.status(.capacity) (such as #91243) along with the preemption tests. #91955 tries to use "patch" to replace "updateStatus".

**Comment by BenTheElder** [comment]
> + ./hack/ginkgo-e2e.sh --provider=skeleton --num-nodes=2 --ginkgo.focus=\[Conformance\] --ginkgo.skip= --report-dir=/logs/artifacts --disable-log-dump=true

???

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance/1270374504111017984

**Comment by BenTheElder** [comment]
er, there should just be one ginkgo node in these runs AFAICT
