### ISSUE TITLE
Provide an official kubectl docker image

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#91919]
**What would you like to be added**:
We would like to see an official multi-arch `kubctl` docker image

**Why is this needed**:
We find ourselves needing to use `kubectl` as a pod various time. So, we maintain our own amd64 variant of the kubectl docker image. We see that other vendors also maintain their own kubectl image, example, https://github.com/rancher/kubectl . I don't speak for Rancher. But it seems that upstream can easily provide a multi-arch kubectl docker image.

**Comment by tamalsaha** [comment]
/sig cli

cc: @BenTheElder

**Comment by dims** [comment]
@tamalsaha Sorry, we really really don't want to add more images that we have to care for in upstream. we are trying really hard to move things to distroless and trying hard to remove images we maintain. Looking for outside it seems "too easy", in the long term, it's expensive in terms of time/effort.

**Comment by mindw** [comment]
@dims won't this have the opposite effect?
For one people will be forced to maintain their own flavour of a kubectl image - which will grow stale for example:
* https://github.com/bitnami/bitnami-docker-kubectl
* https://github.com/rancher/kubectl
Causing all sorts of compatibility and security problems?
Second, won't the risk of someone publishing a malicious kubectl image increases as people will pick up random images for kubectl usage in cluster?

Perhaps we an err on the side of pragmatism in this case?

**Comment by BenTheElder** [comment]
> @dims won't this have the opposite effect?

Dims is talking about the time spent maintaining the build / images in this repo.
This repo is currently working towards having fewer images, and images that are unlikely to have external security issues (i.e. distroless) to keep up with.

> For one people will be forced to maintain their own flavour of a kubectl image - which will grow stale for example:

That doesn't cost the maintainers of this repo anything ... If the other images are stale, there must not be sufficient interest in maintaining them, which is actually a pretty strong endorsement that we shouldn't create the same problem here. The upstream images are already expensive to maintain and few work on this.

> Causing all sorts of compatibility and security problems?

It shouldn't ...

compatibility: Kubernetes has well defined compatibility for clients. kubectl in a docker image isn't special here.

security: built properly from upstream, kubelet is a single static go binary with no dependencies ... and we already provide those binaries in the existing releases

**Comment by mindw** [comment]
@BenTheElder thank you for your answering on @dims behalf.

It seems we disagree that running kubectl in-cluster is a valid and common use case. We also disagree that the effort for maintaining a kubelet image is a ginormous effort (it isn't).

I'll stop here - the time is better used to maintain the above mentioned image myself.

**Comment by tamalsaha** [comment]
@mindw , we are maintaining our multi-arch kubectl docker image here. https://github.com/appscodelabs/kubectl-docker . Please feel free to open pr if you see any issues.

**Comment by BenTheElder** [comment]
> It seems we disagree that running kubectl in-cluster is a valid and common use case.

I don't think anyone said that?

> We also disagree that the effort for maintaining a kubelet image is a ginormous effort (it isn't).

Maintaining anything in the upstream build & release is more work than you might think. 
Nothing is free and there's already too much to fix there. We could use help.

**Comment by dims** [comment]
@tamalsaha that's helpful. thanks!

**Comment by mindw** [comment]
Thanks @dims @tamalsaha @dims and @bendrucker , your time and efforts are much appreciated!
