### ISSUE TITLE
ValidatingWebhook for Namespace called 2 times for 1 request

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#91917]
**What happened**:
I have a `ValidatingWebhookConfiguration` with a rule for namespace deletion. When a namespace is deleted, the webhook is called 2 times.

**What you expected to happen**:
I would expect to have 1 call for 1 request.

**How to reproduce it (as minimally and precisely as possible)**:
I created a dedicated repository with sample manifests and steps to reproduce inside - https://github.com/ialidzhikov/admission-webhook-example. Checkout the [README.md](https://github.com/ialidzhikov/admission-webhook-example/blob/master/README.md).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ k version

Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: minikube
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
This is working as expected. 

The first delete call sets deletionTimestamp. Then the namespace controller cleans up resources contained in the namespace, removes the finalizer, and issues a second delete request to remove the namespace API object. 

I'm newer versions, the removal of the finalizer cleans up the API object as part of processing the update and no second delete request is required.
