### ISSUE TITLE
PowerRegisterSuspendResumeNotification error running kubectl on Azure App Services

### ISSUE THREAD

**Issue by AlexEyler** [kubernetes/kubernetes#91924]
**What happened**:
When running `kubectl get nodes --output=json` in a Function App running on Azure App Services, we get the following error:
```
kubectl command execution failed: kubectl get nodes  --output=json. Error: runtime: PowerRegisterSuspendResumeNotification failed with errno= 5
fatal error: runtime: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0x1baeb8c, 0x37)
	/usr/local/go/src/runtime/panic.go:774 +0x79 fp=0x30afdd8 sp=0x30afda8 pc=0x432e89
runtime.monitorSuspendResume()
	/usr/local/go/src/runtime/os_windows.go:312 +0x220 fp=0x30afe80 sp=0x30afdd8 pc=0x42eff0
runtime.goenvs()
	/usr/local/go/src/runtime/os_windows.go:549 +0x1ba fp=0x30afed8 sp=0x30afe80 pc=0x42f96a
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:554 +0xa9 fp=0x30aff30 sp=0x30afed8 pc=0x435889
runtime.rt0_go(0x30aff60, 0x7ffcb6e084d4, 0x30aff60, 0x0, 0x7ffcb6e084d4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x30aff38 sp=0x30aff30 pc=0x45d69d
```

**What you expected to happen**:
kubectl returns the nodes for the cluster as a json string

**How to reproduce it (as minimally and precisely as possible)**:
* Create a function app (v2)
* Deploy a function that includes a reference to kubectl.exe (latest version)
* Run the function app

**Anything else we need to know?**:
This looks like it's fixed in golang 13.10: https://github.com/golang/go/issues/37230

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.2
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`): Windows Server 2019
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by AlexEyler** [comment]
I think kubernetes upgraded to 1.13.9 of golang in v1.18.1, so hopefully upgrading one golang revision isn't too troublesome.

**Comment by lixiaobing1** [comment]
yeah，agree @AlexEyler, golang updated to 1.13.9 since k8s v1.18.0：

Changelog since v1.18.0
Changes by Kind
Feature
deps: Update to Golang 1.13.9
build: Remove kube-cross image building (#89398, @justaugustus) [SIG Release and Testing]

**Comment by justaugustus** [comment]
Our next Golang update will be to go1.13.12.
You can track the work here: https://github.com/kubernetes/release/issues/1257

cc: @Verolop @markyjackson-taulia

**Comment by AlexEyler** [comment]
Thanks! I'll follow that item then
