### ISSUE TITLE
api-server does not come up when using ./hack/local-cluster-up.sh

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#91920]
This may be new but it looks like api-server is refusing to come up when started via `./hack/local-cluster-up.sh`. It fails with:

```
Error: error in registering group versions: unable to get openapi models: cannot find model definition for k8s.io/api/certificates/v1.CertificateSigningRequest. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again

```

Could this be introduced by https://github.com/kubernetes/kubernetes/pull/91685 ? 

cc @liggitt 

/sig api-machinery

**Comment by gnufied** [comment]
A random commit before this merged - https://github.com/kubernetes/kubernetes/commit/019d3ee4380959d28da07a7b14fc7583833ca433 works

**Comment by liggitt** [comment]
if you make clean and rerun, does it come up correctly?

**Comment by gnufied** [comment]
Looks like `make clean` did fix it. sorry about the noise.
