### ISSUE TITLE
e2e framework: Remove/replace the "kube-proxy-mode-detector" mechanism 

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#91938]
**What would you like to be added**:

Remove/replace the "kube-proxy-mode-detector" mechanism used in the e2e test.

https://github.com/kubernetes/kubernetes/blob/a017253ace9017bb8716b2d46b57467b2c73af29/test/e2e/network/service.go#L3679

**Why is this needed**:

This is being used by some tests to detect the kube-proxy mode

https://github.com/kubernetes/kubernetes/blob/a017253ace9017bb8716b2d46b57467b2c73af29/test/e2e/network/service.go#L976

https://github.com/kubernetes/kubernetes/blob/a017253ace9017bb8716b2d46b57467b2c73af29/test/e2e/network/service.go#L3404

It basically creates a pod and exec a curl in a node to the `http://localhost:10249/proxyMode`

Taken this job log as example 

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91748/pull-kubernetes-e2e-gce/1270263772719616001/build-log.txt

```
0609 08:31:38.940] [It] should preserve source pod IP for traffic thru service cluster IP [LinuxOnly]
I0609 08:31:38.940]   test/e2e/network/service.go:976
I0609 08:31:38.940] Jun  9 08:30:58.952: INFO: Running '/go/src/k8s.io/kubernetes/kubernetes/platforms/linux/amd64/kubectl --server=https://34.105.100.87 --kubeconfig=/workspace/.kube/config exec --namespace=services-5059 kube-proxy-mode-detector -- /bin/sh -x -c curl -q -s --connect-timeout 1 http://localhost:10249/proxyMode'
I0609 08:31:38.941] Jun  9 08:31:02.417: INFO: stderr: "+ curl -q -s --connect-timeout 1 http://localhost:10249/proxyMode\n"
I0609 08:31:38.941] Jun  9 08:31:02.417: INFO: stdout: "iptables"
I0609 08:31:38.941] Jun  9 08:31:02.417: INFO: proxyMode: iptables
I0609 08:31:38.941] Jun  9 08:31:03.094: INFO: Waiting for pod kube-proxy-mode-detector to disappear
I0609 08:31:38.941] Jun  9 08:31:03.440: INFO: Pod kube-proxy-mode-detector still exists
I0609 08:31:38.941] Jun  9 08:31:05.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear
I0609 08:31:38.942] Jun  9 08:31:06.156: INFO: Pod kube-proxy-mode-detector still exists
I0609 08:31:38.942] Jun  9 08:31:07.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear
I0609 08:31:38.942] Jun  9 08:31:07.706: INFO: Pod kube-proxy-mode-detector still exists
I0609 08:31:38.942] Jun  9 08:31:09.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear
I0609 08:31:38.942] Jun  9 08:31:09.856: INFO: Pod kube-proxy-mode-detector still exists
I0609 08:31:38.943] Jun  9 08:31:11.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear
I0609 08:31:38.943] Jun  9 08:31:11.934: INFO: Pod kube-proxy-mode-detector still exists
I0609 08:31:38.943] Jun  9 08:31:13.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear
I0609 08:31:38.943] Jun  9 08:31:13.509: INFO: Pod kube-proxy-mode-detector no longer exists
I0609 08:31:38.943] [1mSTEP[0m: creating a TCP service sourceip-test with type=ClusterIP in namespace services-5059
```

It takes about 15 seconds and it runs 3 times, so we can save some time ~45 secs

**Comment by neolit123** [comment]
> maybe a help-wanted/good first-issue?

seems fine as long as the issue description explains how exactly it should be improved.

**Comment by aojea** [comment]
> seems fine as long as the issue description explains how exactly it should be improved.

:thinking: the kube-proxy configmap is only used by kubeadm?

**Comment by neolit123** [comment]
i don't think so:
https://github.com/helm/charts/tree/master/stable/prometheus-operator#kubeproxy

**Comment by BenTheElder** [comment]
> It takes about 15 seconds and it runs 3 times, so we can save some time ~45 secs

sync.Once ?

**Comment by pururaj1908** [comment]
@aojea I am interested in taking up this issue. But as this will be my first time contributing in the project, I will need some elaborate explanation to understand what exactly needs to be done. Thanks.

**Comment by aojea** [comment]
@pururaj1908 I do not have clear that this is an easy change or if it is worth the effort, after considering the answers and checking the code again
If you don't mind I'll close this to avoid more confusion, if I come back to it or I find another good first issues I'll let you know
Thanks for stepping up :smile: 
/close

**Comment by pururaj1908** [comment]
@aojea Alright. Thanks for the info. I will also look for any other open issues in the meantime.
