### ISSUE TITLE
leader-elect-resource-lock should be leases

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#91951]
**What happened**:

Documentation states `kube-scheduler` and `kube-controller-manager` have a flag `--leader-elect-resource-lock` which can be set to `endpoints` (default) or `configmaps`. This is way outdated. Possible values seem to be `configmapleases`, `endpointleases` and, more importantly `leases`. The latter should be the default by now given the multi-lock implementations were there for migration purposes, unless the concern is introducing a breaking change.

**What you expected to happen**:

The documentation should state clearly all the options and, hopefully, the cost of going w/ each.

**How to reproduce it (as minimally and precisely as possible)**:

- https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
- https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

**Anything else we need to know?**:

I don't think so.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.5

/sig sig-docs

**Comment by ialidzhikov** [comment]
The `--leader-elect-resource-lock` docs are fixed in the master branch with https://github.com/kubernetes/kubernetes/pull/90173.

**Comment by pires** [comment]
Thank you, @ialidzhikov.

Do you happen to know if there's a plan to default to `leases`?

**Comment by ialidzhikov** [comment]
> Do you happen to know if there's a plan to default to leases?

I don't have details. Probably someone from apimachinery can point a KEP link, issue or PR that explains whether there is a plan to default to leases and if yes - how and when.

/cc @liggitt @lavalamp

**Comment by lavalamp** [comment]
I think @cheftako or maybe @andrewsykim might know the exact current plan?

We can't just switch the default, that will probably cause a disaster for someone doing a rolling upgrade of a multiple-controller-manager cluster.

**Comment by pires** [comment]
So, I checked the CLI reference documentation and up until 1.16, inclusive, [it clearly states default is `endpoints`](https://v1-16.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/).
Docs related to newer versions state the default is now `endpointleases`:

```
--leader-elect-resource-lock string     Default: "endpointsleases"
  The  type of resource object that is used for locking during leader  election. Supported options are 'endpoints', 'configmaps', 'leases',  'endpointsleases' and 'configmapsleases'.
```

Digging a little deeper into the 1.17 changelog, there's a reference to the change that supposedly sets `endpointleases` as the new default for, at least, `kube-scheduler` and `kube-controller-manager` (#84084). This reference in the changelog is not part of breaking changes, so either it wasn't a breaking change because there was a migration path - and this is my understanding at the time of opening the issue - or I'm missing something.

Anyways, #84084 only changes the file-based configuration, not the CLI flags. And this is where it gets hairy for me because looking at the codebase, only in 1.19 did both binaries started using `k8s.io/component-base` instead of `pkg/client/leaderelectionconfig` (#90649) and up until then the default was `endpoints` as can be found in [1.17](https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/client/leaderelectionconfig/config.go#L43-L45) and [1.18](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/client/leaderelectionconfig/config.go#L43-L45). Am I right that CLI default was `endpoints` until 1.18, inclusive, but `endpointleases` has been the default for far longer when relying on file-based configuration?

**Comment by pires** [comment]
OK I think this is just a problem between what actually shows up in the CLI flag description vs the implementation. Check this out:

```
root@d4653f48fed2:/kubernetes/server/bin# ./kube-controller-manager --version
Kubernetes v1.18.8

root@d4653f48fed2:/kubernetes/server/bin# ./kube-controller-manager -h |grep leader-elect-resource-lock
      --leader-elect-resource-lock endpoints     The type of resource object that is used for locking during leader election. Supported options are endpoints (default) and `configmaps`. (default "endpointsleases")
```

Clearly, the implementation states the default is `endpointsleases` but the description states the default is `endpoints`.

**Comment by pires** [comment]
Same for `kube-scheduler`

```
root@d4653f48fed2:/kubernetes/server/bin# ./kube-controller-manager --version
Kubernetes v1.18.8
```

**Comment by pires** [comment]
I think the issue can be closed but will leave it open for the owners of this piece of code to decide whether they want to cut a bugfix release for 1.17 and 1.18 that fixes the CLI flag description. Thank you for your time!

**Comment by pires** [comment]
Was backported to 1.18 https://github.com/kubernetes/kubernetes/pull/94511
