### ISSUE TITLE
Kubelet tries to connect to API server via closed connection

### ISSUE THREAD

**Issue by zhan849** [kubernetes/kubernetes#91963]
**What happened**:
We've seen kubelet trying to talk to API server via closed connection. Here is one example but the error exists in the underlying kube client:

```
Jun 9 17:48:07 xxxxxx kubelet[6515]: E0609 17:48:07.530047 6515 desired_state_of_world_populator.go:312] Error processing volume "efs" for pod "xxxxxx": error processing PVC jupyter/efs: failed to fetch PVC from API server: Get https://api-server/api/v1/namespaces/xxxxxx: write tcp 10.12.46.168:39998->10.12.43.105:443: use of closed network connection 
```

Couple of things to notice:
- such failure can last for hours without re-establishing connection.
- Node will appear to be not ready so control plane behaves as expected
- Kubelet will report "ok" in healthz endpoint so it's hard to detect on node level
- Restart kubelet will help

**What you expected to happen**:
once connection is closed, kubelet shall re-establish connection to api server

**How to reproduce it (as minimally and precisely as possible)**:
cut off connection from api server perhaps? We haven't found a way to reproduce it yet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.8
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery

**Comment by MikeSpreitzer** [comment]
I have been seeing a similar symptom but with a slightly different error message.  In the kubelet it starts after the initial certificate rotation, and the error message complains about not being able to write to the connection.  I have also seen kube-proxy get stuck in this state.  `strace` and `tcpdump` and `lsof` show no network activity by the troubled processes.  Oddly, the problem strikes only a few processes in my cluster.  And different ones in different trials, although there is a tendency towards consistency.

**Comment by tedyu** [comment]
Kubelet.kubeClient is used for communicating with API server (see call to volumemanager.NewVolumeManager()).

It seems kubeClient needs to be reconstructed when 'use of closed network connection' surfaces.

**Comment by caesarxuchao** [comment]
This seems to be a dupe of #87615 

https://go-review.googlesource.com/c/net/+/198040 has been merged in Golang. That should fix the issue once Kuberentes can use the feature.

**Comment by BenTheElder** [comment]
@caesarxuchao what remains here?
