### ISSUE TITLE
ReadOnly mount /var/lib/kubelet/pods/<podID>/etc-hosts

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/kubernetes#91981]
**What happened**:
https://github.com/kubernetes/kubernetes/blob/b6bdd64b1070781d5a63ab02d533d3b3c88ed2b8/pkg/kubelet/kubelet_pods.go#L298-L304 we have this `etc-hosts` mount in container with `ReadOnly: false`. 

So users can exec into container and modify this file, but this file is shared with all containers in the same pod, I don't think it's good to change this file.

I think to solve is simple, just change this file to mount as `ReadOnly: true`, and actually if we really want to customize our `/etc/hosts` we can simply uses `hostAlias` in Pod spec.

**What you expected to happen**:
User can't modify this file.

**How to reproduce it (as minimally and precisely as possible)**:
Write things into the container `/etc/hosts`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos
- Kernel (e.g. `uname -a`): Linux master 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mikebrow** [comment]
A container writing to `/etc/hosts` is not recommended because "Modification not using HostAliases is not suggested because the file is managed by Kubelet and can be overwritten on during Pod creation/restart" and also because "If you make manual changes to the hosts file, those changes are lost when the container exits."

However, there exist instances where kubernetes users write to /etc/hosts from inside the container in spite of these warnings. This proposal would cause those writes to abend. It would be fair to provide a switch to make the mount readonly, but IMO the default should remain as is.

**Comment by mrunalp** [comment]
Changing this to read-only will break legacy workloads that depend upon being able to write to this file. @joelsmith was looking into this and one idea was making this file managed by the container runtime.

**Comment by szuecs** [comment]
As far as I understand the problem starts when podX modifying the file and podY will get this unexpected change.
We could let it writeable, but the bind mount that shares host‘s /etc/hosts file with pods can be changed like: copy hosts file and bind mount the copy. This can be done for each pod, so it’s not shared anymore.
Does it make sense?

**Comment by mikebrow** [comment]
> As far as I understand the problem starts when podX modifying the file and podY will get this unexpected change.
> We could let it writeable, but the bind mount that shares host‘s /etc/hosts file with pods can be changed like: copy hosts file and bind mount the copy. This can be done for each pod, so it’s not shared anymore.
> Does it make sense?

He only mentioned one pod in the description of the problem. Yes, your suggested resolution makes sense for the problem you described,.. and each pod already has it's own hosts file see example in the title of the issue.
