### ISSUE TITLE
Support Preemptible instances on GKE

### ISSUE THREAD

**Issue by wstrange** [kubernetes/kubernetes#9199]
It would be nice if GKE supported [https://cloud.google.com/compute/docs/instances/preemptible]

See https://groups.google.com/forum/#!topic/google-containers/RwZV0x56yho for more background

The use case would be for casual testing and development.

**Comment by bgrant0607** [comment]
cc @erickhan

**Comment by roberthbailey** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/12384
