### ISSUE TITLE
Renaming DefaultPodTopologySpread plugin

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#91994]
As suggested in https://github.com/kubernetes/kubernetes/pull/91793#issuecomment-642138709
This is necessary to avoid confusion between the plugin name and the feature gate that controls #80639

The name change should be fine as the plugin names were alpha, along with the component config API. And now that we are graduating to beta its the perfect time to change it.

One idea would be to call it `LegacyDefaultPodTopologySpread`, but since the replacement is only alpha, I don't think it's a good fit. I would suggest `DefaultPodSpread` instead (ie, remove Topology from it).

**Comment by ahg-g** [comment]
I think the feature name and the plugin named the same will cause more confustion, what about we name the plugin ```SelectorSpread```, the old priority name. We don't need to mention default at all.

**Comment by alculquicondor** [comment]
I don't see a problem with "Default", but Selector is fine too. Although the selector aspect of it is more of an implementation detail. Another alternative would be "WorkloadSpread"

**Comment by Huang-Wei** [comment]
`SelectorSpread` looks good to me, which is similar to the old priority name SelectorPriority.

**Comment by alculquicondor** [comment]
`SelectorSpread` it is

/good-first-issue
/help

**Comment by rakeshreddybandi** [comment]
@alculquicondor I am interested on helping this issue. Can I work on this?

**Comment by alculquicondor** [comment]
Absolutely. Please assign it to yourself with `/assign`

Keep in mind that code freeze is in June 25th.

**Comment by mayankshah1607** [comment]
@rakeshreddybandi Are you still working on this one?

**Comment by rakeshreddybandi** [comment]
Hi @mayankshah1607 I am working on it and I will be creating a PR soon

**Comment by alculquicondor** [comment]
@rakeshreddybandi is the PR ready? Even though Code Freeze is July 9th, keep in mind that some reviewers might be out next week for holidays in north america.

**Comment by rakeshreddybandi** [comment]
HI @alculquicondor Sorry for delay.. Created a PR
