### ISSUE TITLE
lots of "Failed" PV found after deleting namespace

### ISSUE THREAD

**Issue by fduyangchao** [kubernetes/kubernetes#92023]
**What happened**:
lots of "Failed" PV found after deleting namespace

**What you expected to happen**:
there should not be so many "Failed" PV

**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl delete namespace <nsName>, 
2. restart kubelet during deleting namespace

**Anything else we need to know?**:
kubelet volume manager reconciles the asw/dsw and do unmountVolume() and unmountDevice():
(1) in the first reconcile() loop, volume manager do unmountVolume(), which will delete volume dir in /var/lib/kubelet/pods/xxx/volumes/xxx
(2) restart kubelet (caused by node power cycle)
(3) After kubelet is running, it reads /var/lib/kubelet/pods/xxx/ to recover asw. Since volume subdir in /var/lib/kubelet/pods/xxx/ is already removed, so it won't be globally unmounted.
(4) pv controller invokes deleteVolume(), but found the volume is not globally unmounted, then set it as "Failed"

Is there any solution to cover this case? 

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by domgoer** [comment]
this seems to be related to [#60987](https://github.com/kubernetes/kubernetes/issues/60987)
