### ISSUE TITLE
UpdateStatus func would also update label and annotations

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#92022]
**What happened**:

When we use UpdateStatus to update pod, we found pod label also updated. Is that by design?

**What you expected to happen**:

only update pod status

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L163-168

we do not ignore label and annotations

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
The original approach to subresources was only concerned with preventing changes to spec and status via the respective endpoints. Changes to metadata were allowed via either endpoint. That is the case for most of the types defined early on in Kubernetes. 

Changes to metadata via status subresources were restricted in some later types, notably custom resource types.

**Comment by Danny-Wei** [comment]
> The original approach to subresources was only concerned with preventing changes to spec and status via the respective endpoints. Changes to metadata were allowed via either endpoint. That is the case for most of the types defined early on in Kubernetes.
> 
> Changes to metadata via status subresources were restricted in some later types, notably custom resource types.

Hi @liggitt, I would like to ask if there are any plans to adjust the metadata modification permission rules for core resources such as Pods and Nodes in the future?

A common scenario is that many DaemonSet components need to modify the annotations or labels of Pods or Nodes. Under the earlier rules, we only needed to grant permissions for `nodes/status` or `pods/status` to enable these operations, which effectively narrowed the scope of sensitive permissions and minimized their spread.

However, if metadata modifications for core resources like Pods and Nodes are also restricted (following the later rule applied to custom resources), it will become inevitable to expand the permission scopes, undermining the goal of limiting the diffusion of sensitive permissions.

**Comment by liggitt** [comment]
There are no plans to modify the behavior of older resources like pods and nodes here
