### ISSUE TITLE
i can`t install dashboard

### ISSUE THREAD

**Issue by lypee** [kubernetes/kubernetes#92021]
forgive my bad Engilish
i want to install dashboard ， and i follow the tutorial :https://github.com/kubernetes/dashboard/blob/master/docs/user/installation.md
I use command in that page : kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.1/aio/deploy/head.yaml
but terminal display these info : The connection to the server raw.githubusercontent.com was refused - did you specify the right host or port? ,

**Comment by BenTheElder** [comment]
please file an issue at https://github.com/kubernetes/dashboard/issues
the dashboard maintainers are much more likely to see bugs in their own repo, and this isn't a kubernetes bug

FWIW though: this sounds like an issue with your local environment being able to reach github, the connection to githubusercontent comes from your local machine, not kubernetes.

/close
