### ISSUE TITLE
EFK Not working as expected

### ISSUE THREAD

**Issue by shanmukha511** [kubernetes/kubernetes#92036]
**What happened**:
We have deployed efk from marketplace and finding some  issues.

1. After some days of deploying on GCP UI it shows **"Some components Pending"**
Don't know the reason why it show pending after some days of deploying.

2. Initially we can see fluentd pods logs getting generated  but after some time we see fluentd logs itself not rotating it will get stopped.

3. Have deployed in our env and see some pods logs wont reach to kibana while some other pod logs to reach kibana.We just try to find logs of fluentd but it logs got stucked and its not rotating.
wn we search elastic search logs and kibana we don't find any error logs.
 tried to change thread count chunk limit and some other parameters of fluent but i dont see any progress. 

**What you expected to happen**:
1.It should not show that some components pending.
2.the fluentd pod logs should be rotated for 5 sec (i.e flush interval)
3. All pods logs has to reach kibana and it should reflected there

**How to reproduce it (as minimally and precisely as possible)**:

Deploy from Google market place and after some days like may be 10 or 20 days You can observer these issues.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by kow3ns** [comment]
This doesn't fall within the scope of code that sig-apps owns. I'm not sure where to direct you that you might find help. You might reach out to elastic or GCP.
