### ISSUE TITLE
pull-kubernetes-e2e-gce-storage-slow job timing out

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#92045]
**Which jobs are failing**:
 pull-kubernetes-e2e-gce-storage-slow

**Which test(s) are failing**:
job timesout

**Since when has it been failing**:
6/9/20

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-storage-slow

**Reason for failure**:
It appears that build + cluster creation is taking around 30 minutes, and the job times out after running about 50m worth of tests
```
I0611 12:48:32.189] Args: --job=pull-kubernetes-e2e-gce-storage-slow --service-account=/etc/service-account/service-account.json --upload=gs://kubernetes-jenkins/logs --root=/go/src --repo=k8s.io/kubernetes=master:2930723a2518a65c44fd190fd3d45b3f795d8eda,91577:0ed41c3f1036785c6c86dd35d20412c8387cf382 --repo=k8s.io/release --upload=gs://kubernetes-jenkins/pr-logs --timeout=125 --scenario=kubernetes_e2e -- --build=bazel --cluster= --extract=local --gcp-node-image=gci --gcp-zone=us-west1-b --ginkgo-parallel=30 --provider=gce --runtime-config=batch/v2alpha1=true --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-storage-slow '--test_args=--ginkgo.focus=\[sig-storage\].*\[Slow\] --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8' --timeout=80m

I0611 13:22:38.351] Running Suite: Kubernetes e2e suite

W0611 14:10:40.882] 2020/06/11 14:10:40 process.go:199: Interrupt after 1h20m0s timeout during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[sig-storage\].*\[Slow\] --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true. Will terminate in another 15m
```
**Anything else we need to know**:

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
In a run that doesn't timeout, the 267 test cases took 13 minutes to run.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91687/pull-kubernetes-e2e-gce-storage-slow/1269946677666516993/build-log.txt

I0608 11:30:05.866] [1m[32mRan 267 of 5102 Specs in 776.539 seconds[0m

**Comment by msau42** [comment]
But in a run that did timeout, the same 267 test cases took more than double the time.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-storage-slow/1271103557549953026

```
I0611 16:57:43.624] Ran 267 of 5104 Specs in 1892.674 seconds
```

**Comment by msau42** [comment]
Looking at the test duration graphs:
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-storage-slow&graph-metrics=test-duration-minutes

`Test` duration has increased from 20 mins to 50-60 mins, but I could not spot any obvious increases in individual test case durations, and there are no new test cases added.

**Comment by msau42** [comment]
This seems to be a problem in CI job too, not just pull, with a clear start around 6/9 afternoon.
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-slow&graph-metrics=test-duration-minutes

**Comment by msau42** [comment]
Looking at the CI runs, the run that passed used commit 717b9b769ed7afa1f97f10f1d221e81e53571d84. The following run failed and used commit 6ac3ca4b1793d0eaaaa7d605e5b9b8057000e1ce

Looking between those commits, https://github.com/kubernetes/kubernetes/pull/91684 looks most suspicious.

**Comment by BenTheElder** [comment]
full diff https://github.com/kubernetes/kubernetes/compare/717b9b769ed7afa1f97f10f1d221e81e53571d84..6ac3ca4b1793d0eaaaa7d605e5b9b8057000e1ce

**Comment by msau42** [comment]
I confirmed in https://github.com/kubernetes/kubernetes/pull/92056 that it's the change to containerd that caused it

**Comment by msau42** [comment]
Temporarily switched the slow job back to docker in https://github.com/kubernetes/test-infra/pull/17924, and jobs are looking good now. Root cause is being investigated in #92057.

/close
