### ISSUE TITLE
[Flaky test] gci-gce-basic-sctp should create a Pod with SCTP HostPort

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#92041]
**Which jobs are failing**:

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-basic-sctp

**Which test(s) are failing**:

sig-network] SCTP [Feature:SCTP] [LinuxOnly] should create a Pod with SCTP HostPort

**Since when has it been failing**:

Test [sig-network] SCTP [Feature:SCTP] [LinuxOnly] should create a Pod with SCTP HostPort has failed 3 times since it last passed at commit/d49d045a3. It started failing between commit/d49d045a3 (Tue Jun 09 13:25 PDT) and commit/d62762f09 (Wed Jun 10 01:26 PDT): https://github.com/kubernetes/kubernetes/compare/d49d045a3...d62762f09?.

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-basic-sctp&show-stale-tests=

**Reason for failure**:

**Anything else we need to know**:

I'm not sure if we already did it but there was a proposal to change from dockershim to containerd for the GCE jobs

**Comment by danwinship** [comment]
> I'm not sure if we already did it but there was a proposal to change from dockershim to containerd for the GCE jobs

yes, that would break us... the test checks "are we using kubenet", but it didn't occur to me that we would need to deal with kubenet with CRI instead of kubenet with dockershim. It should be easy to make it check for both the dockershim rule and the CNI portmap rule though...

**Comment by janosi** [comment]
yes, according to the "Changes" link on the dashboard, containerd replaced docker in GCE right before the failures.

**Comment by janosi** [comment]
> It should be easy to make it check for both the dockershim rule and the CNI portmap rule though...
Let's see if I can make it :)

**Comment by danwinship** [comment]
So actually the test is pretty generic (it just looks for `-p sctp` and `--dport 5060`) and it seems like it ought to pass correctly with CNI portmap too. I'm not sure what's failing. You may need to add some debugging...

**Comment by janosi** [comment]
OK, so as I can see, containerd's CRI implementation just ignores all HostPort definitions that do not have TCP or UDP Protocol value.

https://github.com/containerd/containerd/blob/834665d9db028c8733479b5063e4fd477e549364/vendor/github.com/containerd/cri/pkg/server/sandbox_run.go#L417

I.e. containerd will not send HostPort mapping definitions to the CNI if the protocol is not TCP or UDP.

**Comment by aojea** [comment]
seems that is enough reverting this

https://github.com/containerd/cri/pull/911

**Comment by janosi** [comment]
Yes, exactly. Introduced right after SCTP support was merged in k8s.

**Comment by aojea** [comment]
> Yes, exactly. Introduced right after SCTP support was merged in k8s.
> Just found this in the `framework/skipper` package: `func RunIfContainerRuntimeIs(runtimes ...string)` Though not sure it "knows" the right runtime at runtime, because there is no user of it in `test` :)

just curious, why do we skip in containerd and allow it with dockershim?

**Comment by janosi** [comment]
Hmm, do you mean why do not we skip in case of containerd? The reason is that I did not remember that containerd PR about the SCTP support.
Let's see if I can skip it.

**Comment by janosi** [comment]
> Though not sure it "knows" the right runtime at runtime, because there is no user of it in test :)

Hm, that is not true. My search engine was wrong. After a restart I found usage of that in e2e_node

**Comment by BenTheElder** [comment]
Has a bug been filed upstream in containerd?
Just skipping the tests seems like the wrong approach here.

**Comment by aojea** [comment]
> Hmm, do you mean why do not we skip in case of containerd? The reason is that I did not remember that containerd PR about the SCTP support.
> Let's see if I can skip it.

sorry, I meant why we are not allowing it in containerd, 

@janosi does this feature should work in all container runtimes? CRIO, docker and containerd?

if affirmative, we can submit a PR to containerd/cri to allow SCTP, 
I can do it if you don't have time

**Comment by janosi** [comment]
@aojea Yep, why not. I mean, it could work in all container runtimes. As I understand the containerd implementation is based on a misunderstanding: that the host port mapping loads the SCTP kernel module and that would be bad for those apps that want to use user space SCTP. But as long as there is no SCTP socket created on a node the SCTP kernel module is not loaded.

**Comment by janosi** [comment]
I can initiate a discussion with containerd about this.

**Comment by BenTheElder** [comment]
https://github.com/containerd/containerd/issues/4321#issuecomment-643711175

seems this dates back to the original SCTP KEP, seems like it should be a pretty simple fix (?)

thanks for filing the bug and for the details there!

**Comment by janosi** [comment]
@aojea @BenTheElder CRI-O seems to have the same issue: https://github.com/cri-o/cri-o/blob/61d79c8266498fc59e868a9e32bd66750b2a5f93/server/sandbox_run.go#L77

**Comment by mikebrow** [comment]
Just confirming you want this filter to be gone now. Or do you need the filter to be manageable in some way.. filtered by a config switch?

**Comment by danwinship** [comment]
For TCP and UDP HostPorts, the runtime is expected to do two things:
1. open a listening socket on that port so the kernel will think it's in use and not allocate it to anyone else
2. create iptables rules (or whatever) to route traffic from the host port to the container port

For _SCTP_ HostPorts, the runtime _should_ do the second part (iptables rules), but _should not_ do the first part (listening socket), for two reasons:
- Some users want to use "userspace SCTP", in which case they will be referring to SCTP at the Kubernetes level but need to keep the `sctp.ko` kernel module from ever being loaded. (This is discussed more [in the KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0015-20180614-SCTP-support.md#the-solution-in-the-kubernetes-sctp-support-implementation).)
- If `sctp.ko` is not loaded when Kubernetes starts, we want to avoid having Kubernetes itself cause it to be auto-loaded, for security reasons. (More discussion of this [on the sig mailing list](https://groups.google.com/forum/#!msg/kubernetes-sig-network/KSi0DI-Gw80/fNpWFnAdCAAJ).)

So, runtimes should be filtering out SCTP for the opening-listening-sockets part, but not for the making-iptables-rules part. (Some implementations, notably CNI `portmap`, don't actually do the opening-listening-sockets part, so they wouldn't be filtering at all.)

**Comment by janosi** [comment]
Exactly. 
The current state in the runtimes:
- Docker (dockershim, actually): OK. The logic was been implemented together with the basic SCTP feature, so listening on the host port is filtered for SCTP, but the iptables rules are created
- Containerd (CRI, actually): the patch which was applied 2 years ago filters out every SCTP host port handling, because it filters SCTP ports from the list of port mappings that are passed to CNI (portmap) later. Actually, containerd (CRI) does not perform the "listen" part at all, so the patch is not needed at all
- CRI-O: the patch applied 2 years ago filters out everything. CRI-O imports the host port manager implementation from kubelet/dockershim. For this reason it has the logic that can filter out SCTP ports from the "listen" part, but still applies the iptables rules. I.e. the patch is not needed in CRI-O either.

**Comment by aojea** [comment]
/remove-lifecycle stale

The test is flaky now :thinking: 
https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-basic-sctp&width=5

**Comment by janosi** [comment]
I guess it is a timing issue? Do you think some extra polling rounds would help?

**Comment by aojea** [comment]
I've submitted a PR to fix it and another one to test the sctp connectivity, please review them, I've pinged you there :smile:
