### ISSUE TITLE
pvc.Spec.Resources is marked as optional in api-docs but is required via validation

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#92044]
The doc comments for the field read:

```golang
type PersistentVolumeClaimSpec struct {
	// Resources represents the minimum resources required
	// +optional
	Resources ResourceRequirements
}
```

But looking at validation code, I do not think it is possible to create a PVC without `Resources` field:

```golang
	storageValue, ok := spec.Resources.Requests[core.ResourceStorage]
	if !ok {
		allErrs = append(allErrs, field.Required(fldPath.Child("resources").Key(string(core.ResourceStorage)), ""))
	} else if errs := ValidatePositiveQuantityValue(storageValue, fldPath.Child("resources").Key(string(core.ResourceStorage))); len(errs) > 0 {
		allErrs = append(allErrs, errs...)
	} else {
		allErrs = append(allErrs, ValidateResourceQuantityValue(string(core.ResourceStorage), storageValue, fldPath.Child("resources").Key(string(core.ResourceStorage)))...)
	}
```

looks like an oversight (unless I missed something). 

/sig storage

**Comment by farah** [comment]
@gnufied nice catch. 

Can I send a fix for it or are you already on it?

**Comment by gnufied** [comment]
@farah no, I am not working on a fix. feel free to open one.

**Comment by farah** [comment]
thanks @gnufied!

/assign

**Comment by jingxu97** [comment]
@Jiawei0227 do you want to take it?

**Comment by Jiawei0227** [comment]
Sure. So I am wondering we do want this to be a required field? Or loose the validation?

**Comment by jingxu97** [comment]
I don't think we want to lose validation. Create a volume without specifying a request size does not work. Pls note only request is needed, I am also wondering whether it is ok to change from optional to requirement in API. You can make a PR and see what comments from reviewers.

From what I understand, just remove //+optional line to make it as required..?

**Comment by gnufied** [comment]
Yes I think we should just remove optional line and see what api-reviewers say.

**Comment by Jiawei0227** [comment]
okay sounds good. I will take this

**Comment by farah** [comment]
sry for the delay guys was off on vacation.

@Jiawei0227 all good i got this. thanks
