### ISSUE TITLE
HostPathType Socket e2e tests hang on containerd

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#92057]
**What happened**:
Once we switched over the default runtime to containerd, the slow ci and pull jobs started timing out. The tests, which used to take 13 minutes, jumped to 30 minutes. https://github.com/kubernetes/kubernetes/issues/92045

This increase in test time is only observed in the slow job, so I suspect the slow job is exercising some functionality that may not be exercised as frequently in the other jobs.

**What you expected to happen**:
No performance regression

**How to reproduce it (as minimally and precisely as possible)**:
Run the tests in the slow job with containerd

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by msau42** [comment]
@kubernetes/sig-node-bugs @kubernetes/sig-storage-bugs

**Comment by BenTheElder** [comment]
do we know what tests were regressing?

**Comment by msau42** [comment]
I did some analysis in https://github.com/kubernetes/kubernetes/issues/92045, but basically, no single test stood out in terms of increasing the time took. I suspect that all the test cases started taking a few seconds longer, and the sum of all of contributed to the increase in job time.

**Comment by msau42** [comment]
I was mainly eyeballing the graphs, but we probably should get the raw data and do some more detailed analysis on it

**Comment by msau42** [comment]
@kubernetes/sig-scalability-bugs do we have scale runs with the [slow] tests?

**Comment by msau42** [comment]
As an experiment, I changed the runtime back to docker in https://github.com/kubernetes/kubernetes/pull/92056, and the slow job tests went back down to 13 minutes.

**Comment by msau42** [comment]
@mikebrow pointed out that https://github.com/kubernetes-sigs/cri-tools/pull/627 may be relevant

**Comment by msau42** [comment]
@Random-Liu pointed out that cri-tools is not used in the kubelet path, so that particular issue may not be the cause. But maybe we can investigate image pulling as a first start.

FWIW, there are at least 100+ test cases running in this job that create the same container on the same node multiple times: hostpathtype, multivolume, container restart

**Comment by msau42** [comment]
I think I found it. All the HostPath Socket tests are consistently never completing.

**Comment by jingxu97** [comment]
https://github.com/containerd/containerd/issues/4320
something might related

**Comment by msau42** [comment]
The test logs don't seem to show up in the artifacts. Running it manually, I see it hung on the exec during BeforeEach():

```
STEP: Create a socket for further testing
Jun 12 14:58:53.432: INFO: ExecWithOptions {Command:[/bin/sh -c nc -lU /mnt/test/asocket &] Namespace:host-path-type-socket-9510 PodName:test-hostpath-type-7rh6v ContainerName:host-path-testing Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
Jun 12 14:58:53.432: INFO: >>> kubeConfig: /usr/local/google/home/msau/.kube/config
```

However when I do this manually using "kubectl exec" it is fine.

**Comment by dims** [comment]
found a work around

```
diff --git test/e2e/storage/host_path_type.go test/e2e/storage/host_path_type.go
index 231f6ae2e21f..8c1a304e28c1 100644
--- test/e2e/storage/host_path_type.go
+++ test/e2e/storage/host_path_type.go
@@ -197,7 +197,7 @@ var _ = utils.SIGDescribe("HostPathType Socket [Slow]", func() {
                ginkgo.By(fmt.Sprintf("running on node %s", basePod.Spec.NodeName))
                targetSocket = path.Join(hostBaseDir, "asocket")
                ginkgo.By("Create a socket for further testing")
-               _, err := utils.PodExec(f, basePod, fmt.Sprintf("nc -lU %s &", path.Join(mountBaseDir, "asocket")))
+               _, err := utils.PodExec(f, basePod, fmt.Sprintf("nc -lU %s >/dev/null 2>&1 &", path.Join(mountBaseDir, "asocket")))
                framework.ExpectNoError(err)
        })

```

**Comment by dims** [comment]
i can easily recreate the problem locally using kubetest + local-up-cluster.sh running against containerd.

```
kubetest --build=none --ginkgo-parallel=1 --deployment=local --provider=local  --test --test_args='--ginkgo.focus=HostPathType\sSocket'
```

**Comment by dims** [comment]
There are some notes on differences between how dockershim and other CRI impls handle this situation:
https://github.com/containerd/cri/blob/master/pkg/server/container_execsync.go#L184-L195

@mikebrow have you run into this before?

**Comment by mikebrow** [comment]
> There are some notes on differences between how dockershim and other CRI impls handle this situation:
> https://github.com/containerd/cri/blob/master/pkg/server/container_execsync.go#L184-L195
> 
> @mikebrow have you run into this before?

Came up here:
https://github.com/containerd/cri/pull/1256

**Comment by mikebrow** [comment]
I think what I said in that PR still applies.. I would expect kubectl -it to have a -d detach mode if background operation is the desired mode see docker exec -d option.

**Comment by Random-Liu** [comment]
https://github.com/kubernetes/kubernetes/issues/92057#issuecomment-644485839

This seems to be a known issue. If an exec:
1) Spawns a long running background process;
2) Leaves the IO of the background process open after exits;
3) Containerd will wait until that IO to be closed before finishing the exec.

It is arguable a bug in containerd, and the behavior of background process spawned by exec was never clearly defined. We've seen several production issues caused by this.

Maybe we should:
1) Clearly define and document the behavior, and fix the test;
2) Pass timeout for probe. `ExecSync` timeout is supported by many runtimes, but kubelet doesn't pass a proper value right now.
Set timeout for `ExecSync` 
One option is to clearly document the behavior, and fix the test. https://github.com/kubernetes/kubernetes/blob/v1.19.0-beta.2/pkg/kubelet/lifecycle/handlers.go#L63

**Comment by tedyu** [comment]
Among the callers of HandlerRunner#Run is the following from  kubeGenericRuntimeManager#startContainer :
```
		msg, handlerErr := m.runner.Run(kubeContainerID, pod, container, container.Lifecycle.PostStart)
```
We should find a proper value for the timeout.

**Comment by mrunalp** [comment]
We have a similar issue with CRI-O. I agree with @Random-Liu that we should define this clearly and meanwhile setting a timeout makes sense.

**Comment by mrunalp** [comment]
I have opened https://github.com/kubernetes/kubernetes/pull/92205 to fix the tests.
