### ISSUE TITLE
kubelet default cgroup driver is not cgroupfs on CentOS7

### ISSUE THREAD

**Issue by kubealex** [kubernetes/kubernetes#92066]
From the documentation:

`Please mind, that you only have to do that if the cgroup driver of your CRI is not cgroupfs, because that is the default value in the kubelet already.`

From /etc/sysconfig/kubelet:

[...]KUBELET_EXTRA_ARGS=--cgroup-driver=systemd[...]

It sounds like the usage of the sysconfig file was deprecated, but in this situation:

- file is actually read
- kubelet spins up with systemd

Moreover, the default cgroup driver is not actually cgroupfs.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- OS (e.g: `cat /etc/os-release`): centos7
- Install tools: kubeadm

**Comment by neolit123** [comment]
depends on the container runtime.
for docker kubeadm will detect your cgroup driver and setup the kubelet accordingly, but of other runtimes you have to do it manually.

setuping your CR with a cgroupdriver of systemd is recommended!

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node

/sig-remove architecture
/triage support
/close

**Comment by kubealex** [comment]
no way, this is not true:

Please mind, that you only have to do that if the cgroup driver of your CRI is not cgroupfs, because that is the default value in the kubelet already.

This means that cgroupfs is the default for kubelet, but I just proved that it is not the default value that is assigned when CR != Docker.

**Comment by neolit123** [comment]
I don't think there is logic in the kubelet for that. It always defauls to
cgroupfs unless something changes it to systemd.
