### ISSUE TITLE
Failed to Fit pod errors are not useful

### ISSUE THREAD

**Issue by uluyol** [kubernetes/kubernetes#9207]
When pods cannot be scheduled due to insufficient resources, kubectl describe should give useful output. Currently we have

```
$ cluster/kubectl.sh describe pod mysql

W0603 11:50:59.541717   99656 request.go:291] field selector: v1beta3 - events - involvedObject.name - mysql: need to check if this is versioned correctly.
W0603 11:50:59.541822   99656 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0603 11:50:59.541838   99656 request.go:291] field selector: v1beta3 - events - involvedObject.uid - 4b433a7b-0a20-11e5-afa1-42010af0f412: need to check if this is versioned correctly.
Name:               mysql
Image(s):           mysql
Node:               /
Labels:             name=mysql
Status:             Pending
Replication Controllers:    <none>
Containers:
Events:
  FirstSeen             LastSeen            Count   From        SubobjectPath   Reason          Message
  Wed, 03 Jun 2015 11:43:32 -0700   Wed, 03 Jun 2015 11:46:35 -0700 6   {scheduler }            failedScheduling    Error scheduling: failed to find fit for pod, Node kubernetes-minion-6vim: PodFitsResourcesNode kubernetes-minion-kprc: PodFitsResourcesNode kubernetes-minion-imqn: PodFitsResourcesNode kubernetes-minion-k6im: PodFitsResources
  Wed, 03 Jun 2015 11:42:32 -0700   Wed, 03 Jun 2015 11:48:32 -0700 4   {scheduler }            failedScheduling    Error scheduling: failed to find fit for pod, Node kubernetes-minion-kprc: PodFitsResourcesNode kubernetes-minion-imqn: PodFitsResourcesNode kubernetes-minion-k6im: PodFitsResourcesNode kubernetes-minion-6vim: PodFitsResources
  Wed, 03 Jun 2015 11:44:32 -0700   Wed, 03 Jun 2015 11:48:35 -0700 3   {scheduler }            failedScheduling    Error scheduling: failed to find fit for pod, Node kubernetes-minion-k6im: PodFitsResourcesNode kubernetes-minion-6vim: PodFitsResourcesNode kubernetes-minion-kprc: PodFitsResourcesNode kubernetes-minion-imqn: PodFitsResources
  Wed, 03 Jun 2015 11:42:35 -0700   Wed, 03 Jun 2015 11:50:35 -0700 5   {scheduler }            failedScheduling    Error scheduling: failed to find fit for pod, Node kubernetes-minion-imqn: PodFitsResourcesNode kubernetes-minion-k6im: PodFitsResourcesNode kubernetes-minion-6vim: PodFitsResourcesNode kubernetes-minion-kprc: PodFitsResources
```

which is cryptic and also lists every attempted node.

**Comment by davidopp** [comment]
#9341 which was merged today addresses half of your issue ("and also lists every attempted node.")

The other half (that we use the predicate name directly, which is cryptic) is a valid complaint but I'm not sure we have time to fix it for 1.0. The solution would be to have a translation table in the predicates package from predicate rule name to "human-friendly" name (presumably we'd do the same for priority rule names), and use that table when generating events that mention these rules (as in the line in #9341). Feel free to send a PR, which will substantially increase the likelihood that this will make it into 1.0.

**Comment by davidopp** [comment]
Another improvement would be to say specifically which resource(s) didn't fit. (There are analogous improvements for some of the other predicates too.)

**Comment by davidopp** [comment]
@etune says "Failed to Fit pod errors are not useful"

Scheduler event:
```
Events:
  FirstSeen  ... Reason                    Message
  ...              ...  failedScheduling	Error scheduling: For each of these fitness predicates, pod frontend failed on at least one node: PodFitsResources.
```

Problems with this event message:
1. It says `Error`, but having pods fail to schedule is a common event in a system, and "Error" is too alarming a term.
1. It says `scheduling`, but the event makes it clear that this is about scheduling in both the `From` and `Reason` fields.
1. it says `For each of these fitness predicates .. failed on at least one node:` but there is only one predicate in this case.  Lets be concise and to the point where possible.  Maybe when only one predicate failed, say: `No node satisfied rule PodFitsResources`.
1. the message contains the string `pod frontend`, but that information is already present in the event object.  Save space by removing this.  Also, it reduces the cardinality of the set of distinct message strings, which facilitates grouping of events.

An improved output looks something like this:
```
Events:
  FirstSeen  ... Reason                    Message
  ...              ...  failedScheduling	No node found where PodFitsResources.
```

**Comment by davidopp** [comment]
@erictune I will implement what you described except this one: "It says `For each of these fitness predicates .. failed on at least one node:` but there is only one predicate in this case. Lets be concise and to the point where possible. Maybe when only one predicate failed, say: `No node satisfied rule PodFitsResources`."

The message you saw does *not* mean "No node satisfied rule PodFitsResources." Instead it means "At least one node satisfied rule PodsFitsResources." So the correct rewriting in the spirit you are suggesting is, when there is only one failure reason, to say ".. failed on at least one node for reason .." We've iterated a couple of times on this issue and I'm not sure we've figured out the best wording yet, but the simplification you suggested for the case where there's only one failure reason is totally reasonable.

**Comment by davidopp** [comment]
I had a rather important typo in my previous comment, so please read on the web for the update.

**Comment by davidopp** [comment]
Now that @erictune's comments have been addressed, I'm moving this back out of 1.0.

**Comment by davidopp** [comment]
(addressed by my PR)

**Comment by bgrant0607** [comment]
@davidopp Is this issue still relevant?

**Comment by scottstensland** [comment]
I am using latest kubernetes 1.4.0 and still this fatal error condition message is not helpful at all 

```
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason                                                                          Message
  ---------	--------	-----	----			-------------	--------	------                                                                          -------
  51m		37m		50	{default-scheduler }			Warning		FailedScheduling                                                                        pod (loudmail-deployment-1671311517-s1nb9) failed to fit in any node
```

**Comment by ensalty** [comment]
I also get the same problem not sure if any workaround to solve this
```
[root@cloud kubernetes]# kubectl get events --namespace=kube-system
LASTSEEN   FIRSTSEEN   COUNT     NAME                        KIND      SUBOBJECT   TYPE      REASON       SOURCE            MESSAGE
1s         16h         26052     kube-dns-2247936740-j6pq1   Pod                   Warning   FailedSync   {kubelet cloud}   Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-2247936740-j6pq1_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-2247936740-j6pq1_kube-system(472b334c-9dd4-11e6-bb85-002219c0946b)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

2s        16h       3302      kubernetes-dashboard-1655269645-km0gq   Pod                 Warning   FailedScheduling   {default-scheduler }   pod (kubernetes-dashboard-1655269645-km0gq) failed to fit in any node
fit failure on node (cloud): PodToleratesNodeTaints


```

**Comment by tartavull** [comment]
Same exact errors as @ensalty  and @scottstensland.
Where I have nodes without pods running on it, with more free resources than required by the pod.

**Comment by davidopp** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by jayunit100** [comment]
cluster/kubectl.sh get pod redis-master-223378846-1k1d8 -o=json | grep -A 10 status                 Will show a more useful roll up ofnpredicate -> count
so code think this is closed now

**Comment by timothysc** [comment]
@tartavull what version are you running?  1.6 should have a more concise rollup.

**Comment by tartavull** [comment]
I'll try 1.6, I was running 1.5.3

**Comment by ravisantoshgudimetla** [comment]
@tartavull -  Are you still having this issue in 1.6?
