### ISSUE TITLE
Reset default container runtime to docker for windows node

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#92081]
With PR https://github.com/kubernetes/kubernetes/pull/91684, the default container runtime is set to containerd. However, containerd is not ready for windows yet. There are a number of issues being worked on including https://github.com/containerd/containerd/issues/4320 and https://github.com/kubernetes/kubernetes/issues/92057

For windows node, we need to set default value back to docker now. And then change it to containerd when it is ready.

**Comment by jingxu97** [comment]
cc @pjh

**Comment by marosset** [comment]
@jingxu97 - the containerd PR to supported named pipe mounts for Windows has merged.
I have not had a chance to validate csi-proxy works with containerd on Windows but hope to do so soon.
