### ISSUE TITLE
Security contacts for cluster-bootstrap not specified or out of date

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#92090]
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/cluster-bootstrap/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cluster-bootstrap/SECURITY_CONTACTS) file for the cluster-bootstrap repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig cluster-lifecycle

**Comment by neolit123** [comment]
/help-wanted
/good-first-issue

mini guide:
- send a PR for https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cluster-bootstrap/SECURITY_CONTACTS
- change the list in the file with the following people (SIG cluster lifecycle leads):
```
justinsb
neolit123
timothysc
fabriziopandini
```
https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#chairs

**Comment by gleichda** [comment]
@neolit123 following the discussions of #93357 I think this issue can be closed also?

**Comment by neolit123** [comment]
once a solution is found https://github.com/kubernetes/security/issues/56#issuecomment-758518519
all related issues can be closed:
https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+label%3Aarea%2Fsecurity+security+contacts

**Comment by Saty248** [comment]
hey @neolit123 is this issue still open?

**Comment by neolit123** [comment]
Hello. The parent issue is still not resolved:
https://github.com/kubernetes/committee-security-response/issues/56

But am ok with closing this particular issue given we are changing the mechanism and that cluster bootstrap is a low noise repository. 

/close
