### ISSUE TITLE
Security contacts for component-base not specified or out of date

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#92092]
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/component-base/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/SECURITY_CONTACTS) file for the component-base repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery
/sig cluster-lifecycle

**Comment by neolit123** [comment]
/good-first-issue
/help-wanted

mini guide:
- send a PR for:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/SECURITY_CONTACTS
- replace the list with these contributors:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/OWNERS#L4-L8
(approvers, take from the owners file)

**Comment by rudy2steiner** [comment]
only need update SECURITY_CONTACTS with approvers from the owner file, is right?

**Comment by neolit123** [comment]
> only need update SECURITY_CONTACTS with approvers from the owner file, is right?

it's slightly more complicated as the contacts that are added should agree individually, see:
https://github.com/kubernetes/kubernetes/pull/93357#issuecomment-662703612

but you could send the PR and later update it with only the people that agreed.

**Comment by rudy2steiner** [comment]
Ok

**Comment by BLasan** [comment]
@neolit123 @joelsmith Still opened?

**Comment by rajdevworks** [comment]
@joelsmith @neolit123 is there any pending work that I can contribute on?

**Comment by neolit123** [comment]
/close
To not confuse contributors.
These file will be removed eventually.

**Comment by neolit123** [comment]
@rajdevworks not sure. you can check more help wanted issues.
