### ISSUE TITLE
Geometrically increasing wait times

### ISSUE THREAD

**Issue by pvwebb** [kubernetes/kubernetes#92115]
What would be friendlier to users and more secure from hackers is a geometrically increasing delay from entering wrong passwords.  For example, for the first three wrong passwords have a delay of 1 min.  If three wrong passwords in a row within the next five minutes, delay 5 min. before accepting the password.  If three wrong passwords in a row within the next 15 min., delay 15 min., and continue to increase the wait time.  Thus, instead of it taking 6 months to have a 50% change of software finding the password, it might take 10 years with a system with geometrically increasing delay.

**Comment by liggitt** [comment]
Which component are you referring to which accepts a password?

**Comment by pvwebb** [comment]
The delay when a person enters the wrong password for the account to access the OS.  At the corporate level this is usually an account on the domain server.    The most common setting is when a person enters the wrong password three times.  Right now the delay is always the same amount each time.

**Comment by BenTheElder** [comment]
Kubernetes doesn't ship an OS, which part of Kubernetes are you referring
to?
This sounds like some third party distro OS, not part of Kubernetes.

**Comment by pvwebb** [comment]
My understanding is most OS's (Windows and Linux for example) use Kubernetes for their security.

**Comment by BenTheElder** [comment]
> My understanding is most OS's (Windows and Linux for example) use Kubernetes for their security. 


I don't think your understanding is correct with regards to this.

From [the readme](https://github.com/kubernetes/kubernetes#kubernetes):

> Kubernetes is an open source system for managing containerized applications across multiple hosts. It provides basic mechanisms for deployment, maintenance, and scaling of applications.
>
> Kubernetes builds upon a decade and a half of experience at Google running production workloads at scale using a system called Borg, combined with best-of-breed ideas and practices from the community.

In other words, Kubernetes is used for managing clusters of machines running [containers](https://www.docker.com/resources/what-container).

>Are you saying that Kubernetes doesn't control those login characteristics of those OS's, domain accounts in particular?

No, it doesn't. Login characteristics of Windows and Linux are not part of this project.

/close

**Comment by pvwebb** [comment]
Thank you
