### ISSUE TITLE
Suspected bug in HPA

### ISSUE THREAD

**Issue by zuquan-song** [kubernetes/kubernetes#92111]
**What happened**:
While I was reading the autoscaling source code, I found the method calculateScaleUpLimitWithScalingRules in kube-controller-manager/app/autoscaling.go has a bug if we set SelectPolicy MinPolicySelect. Since the default variable result is 0, the final result would be 0 because the min selectPolicyFn. I'm not sure if it is the expected result, but from my perspective, the result value should be the minimal value among all the proposed value and the initial result value should not be counted.

If it is a bug, I'm interested to fix it ^_^

**What you expected to happen**:
If the the currentReplica = 5, replicasAddedInCurrentPeriod =0, policy.Value is 1. the expected result variable value should be 6, however, it is 0

**How to reproduce it (as minimally and precisely as possible)**:
Just as the `What you expected to happen` says
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by JoshuaAndrew** [comment]
@zuquan-song  any progress ?

**Comment by zuquan-song** [comment]
@JoshuaAndrew hi, I'm not sure whether it is a bug and waiting for someone to confirm this problem

**Comment by JoshuaAndrew** [comment]
@zuquan-song  It's certain that this is bug
