### ISSUE TITLE
Designate or reserve a specific label to indicate "node group"

### ISSUE THREAD

**Issue by max-rocket-internet** [kubernetes/kubernetes#92137]
**What would you like to be added**

To designate or reserve a specific label to be used to show what "node group" a node belongs to. Currently GKE uses `cloud.google.com/gke-nodepool` and EKS uses `eks.amazonaws.com/nodegroup`.

I know node groups don't really exist in the k8s API but they exist on every cloud platform in one form or another.

Maybe `node.kubernetes.io/group`?

**Why is this needed**

It would be convenient to have a standard common label to used for scheduling (e.g. `nodeSelector`) and in monitoring tools where labels are used heavily (e.g. Prometheus).

**Comment by sftim** [comment]
Cluster API also has MachineSets which overlap with this concept quite a bit (not yet officially documented AIUI - see https://github.com/kubernetes-sigs/cluster-api/issues/788)

**Comment by neolit123** [comment]
> Maybe node.kubernetes.io/group?

delayed response, but you could send this as a topic to the SIG Architecture mailing list:
https://github.com/kubernetes/community/tree/master/sig-architecture#contact

/sig architecture

**Comment by max-rocket-internet** [comment]
@neolit123 is there a way to proceed? Should I sign up to the mailing list in order to post this?

**Comment by neolit123** [comment]
> Should I sign up to the mailing list in order to post this?

you can join the SIG Arch mailing list and post the topic there:
https://github.com/kubernetes/community/tree/master/sig-architecture#contact

**Comment by max-rocket-internet** [comment]
OK done: https://groups.google.com/g/kubernetes-sig-architecture/c/nDbhknjYtts
