### ISSUE TITLE
[Failing Test] gce-master-scale-correctness (ci-kubernetes-e2e-gce-scale-correctness)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#92149]
**Which jobs are failing**:

`gce-master-scale-correctness (ci-kubernetes-e2e-gce-scale-correctness)`

**Which test(s) are failing**:

`Timeout`

**Since when has it been failing**:

`06-10-20 05:01 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&graph-metrics=test-duration-minutes

**Reason for failure**:

Timeout

**Anything else we need to know**:

/cc @kubernetes/ci-signal

/sig scalability
/priority critical-urgent
/milestone v1.19

**Comment by jprzychodzen** [comment]
/assign @knight42
An attempt to fix this was done in #92134

**Comment by knight42** [comment]
@jprzychodzen #92134 just reverts the changes, actually I have opened anthoer PR #92163 to fix this problem, but haven't got a `/ok-to-test` yet.

**Comment by hasheddan** [comment]
This job has been green for lat 10+ runs.

/close
