### ISSUE TITLE
Volume not detached if leader election happens before detach is executed

### ISSUE THREAD

**Issue by breunigs** [kubernetes/kubernetes#92145]
**What happened**:

Detaching a volume fails when a kube-controller-manager leader election/change happens before the operation is executed or its error is processed. The new leader starts up thinking the volume has been detached already, while it still remains attached from the view of the storage (vsphere in our case). This becomes problematic once a pod wants to re-attach said volume on a different node, which fails due to the storage not supporting multi-attach.

**What you expected to happen**:

Volume detach gets retried/finished.

**How to reproduce it (as minimally and precisely as possible)**:

Since the kube-controller-manager needs to stop at the exact right moment, it's not easy to provide straight forward steps. Roughly:
1. setup a pod with a volume
2. delete the pod
3. ensure `volumeDetacher.Detach` (https://github.com/kubernetes/kubernetes/blob/9b53b9306e50ffdb1b1b5c930fb4b4ce1f404105/pkg/volume/util/operationexecutor/operation_generator.go#L463) is a no-op or fails. Additionally, the currently running kube-controller-manager should not execute any code after above statement, because it will prevent the bug from triggering. An option might be to insert a `os.Sleep` here to allow for easy manual killing.
4. restart kube-controller-manager
5. observe the detach is not retried

**Anything else we need to know?**:

I don't think the issue is vsphere specific. The following links are for v1.15.11.

As far as I followed the code, it seems that the [reconciler.go:206ff](https://github.com/kubernetes/kubernetes/blob/v1.15.11/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L206-L215) removes volume from the list of attached volumes on that node. This is also visible in the audit logs and kube-controller-manager logs shortly after that it tries to unmount the volume (`attacherDetacher.DetachVolume started for volume …`).

There's no other audit log entry for that leader/volume/node combination before the leader election. 

The new leader populates its `actualStateOfWorld` by iterating over the list of attached volumes per node ([attach_detach_controller.go:371](https://github.com/kubernetes/kubernetes/blob/v1.15.11/pkg/controller/volume/attachdetach/attach_detach_controller.go#L371-L397)). Since the volume in question was removed from that list just before the election, the new leader has no knowledge about the not-fully-detached volume. This is corroborated by the logs of the bulk checker ([vsphere.go:1101](https://github.com/kubernetes/kubernetes/blob/v1.15.11/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L1101)) which doesn't list the volume anymore.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.11
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64

/kind bug
/sig storage

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
cc @gnufied @yuga711 @jingxu97 
/remove-lifecycle stale

This may be related to the dangling attach race but on the detach path?

**Comment by yuga711** [comment]
The issue here seems same as https://github.com/kubernetes/kubernetes/issues/94912
The dangling attachment could occur when KCM crashes while the attach/detach in progress (irrespective of leader election or not). The dangling attach is possible, if the KCM crashes in this window: 
- During attach, after the volume is attached but before the node->status is updated (but the pod is also deleted in the window) 
- During detach, after the volume is removed from node->status, but before the volume is detached.

The patch https://github.com/kubernetes/kubernetes/pull/96617 implements solution for recovering CSI volumes from such dangling attachments.

**Comment by breunigs** [comment]
Indeed, the linked issue describes the same scenario. While #96617 won't work for us right now, since we're not using the vsphere-csi-driver, it seems a given our setup will eventually have a CSI one. Therefore I'm fine closing this ticket, considering a solution is available.

Thanks for letting me know.
