### ISSUE TITLE
scheduler: use http test server to mock external extenders in testing

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#92141]
With [FakeExtender](https://github.com/kubernetes/kubernetes/blob/1fa20301a0173eb7945ea8b80ac60997adceaffa/pkg/scheduler/core/extender_test.go#L160-L269), the real `Extender` implementation is not tested actually. I would suggest mocking external extenders in our testing code.
/sig scheduling
/kind cleanup

**Comment by cofyc** [comment]
In the development of https://github.com/kubernetes/kubernetes/issues/91281, I found it's tricky to add new test cases.
/assign

**Comment by cofyc** [comment]
@Huang-Wei what do you think? the real extender interface implementation [`HTTPExtender`](https://github.com/kubernetes/kubernetes/blob/8b9c9eade3447a9c2d0ac089bd960dc71996cb84/pkg/scheduler/core/extender.go#L41-L53) is not tested in unit tests actually. We can reimplement the current FakeExtender with the real `HTTPExtender` with a mock extender server.

**Comment by Huang-Wei** [comment]
Sure, that makes sense to me. BTW: that may also help catching potential marshal/unmarshal issues.

However, I'd expect the mock extender server to used only in pure Extender testings, i.e., the other tests which wrap extenders can still use FakeExtender as testing extender is not their primary purpose.

**Comment by cofyc** [comment]
SG

We can have a fake `Extender` interface implementation (current `FakeExtender`) and a fake extender server implementation (can be used by `HTTPExtender`).
