### ISSUE TITLE
Machine consistent casing

### ISSUE THREAD

**Issue by adamhjk** [kubernetes/kubernetes#92159]
**What would you like to be added**:

I would like to see a version of the kubernetes object spec's that uses machine consistent casing. The current mechanism is a variant of camelCase, where acronyms that are part of the word are in upper case. Some examples are `hostIP`, `hostIPC`, `hostPID`. 

**Why is this needed**:

The kubernetes object API is intended as both a platform for people to write, and for machines to build on top of. As it currently stands, the API cannot be machine generated from one format to another without custom serialization code. For example: if you have a system where the correct internal representation is snakeCase, you would have `host_ip`. To convert this to the correct case for the k8s API requires custom code - you have to know that `ip` is an acronym, and should therefore become `hostIP`.  

For systems that generate the kubernetes objects via templating, this isn't such a big deal - you either take the inputs offered by the user verbatim and transform them, or you store it directly. But for systems that try and generate objects programmatically, it means quite a bit of custom code.

I think this could be introduced in at least two backwards compatible ways:

1) The API could look for the camelCase version of keys on a lookup miss, so that both the go style `hostIP` and the camelCase `hostIp` are valid. In this case, the current version (which I think is likely better for humans - at least humans who come from writing a lot of Go) could remain the primary interface, while the machine consistent version is there for compatibility.

2) The API could normalize the data before processing it. If you wanted the behavior to be maximally accepting, this would be one way to achieve it - you could normalize all the keys, all the time internally. Anything that can be converted to camelCase would match - or you could go further, and simply lowercase the entire key, and accept `HoStIp`. 

Of course, it could be introduced as a breaking change - but I think that would be difficult to accept, due to the sheer volume of existing kubernetes object files in the wild.

**Comment by adamhjk** [comment]
FWIW, if this is a thing that's worth having, I'm happy to invest in seeing how to send a patch.

**Comment by thepudds** [comment]
Hi @adamhjk, on mobile, so just a quick note, and sorry if this is off-base.

Regarding:

> No machine could possibly know that hostIP should be hostIP, but cheeseIt should be cheezIt should not be cheezIT

And:

> I was helpfully shown https://github.com/golang/go/wiki/CodeReviewComments#initialisms in my question about why hostIP and other fields don't follow any kind of regular case convention. 

I just wanted to point you to golint, including:

https://github.com/golang/lint/blob/master/lint.go#L770

Many (but not all) Go codebases follow the initialisms defined by golint. That might help you get to an 80% solution in terms of programmatically knowing the right casing?

That said, I realize that is not actually what you asked for here.

**Comment by adamhjk** [comment]
@thepudds thank you! Yeah, that was helpfully pointed out to me, and it will help us to get the behavior right - although it remains unfortunate that it has to be that way. For example, we're writing things in Rust and using Serde - so we'll have to have custom field annotations for anything that needs to serialize into a k8s object, which is unfortunate. We can, of course, deal with it - and I super appreciate you pointing it out.

The deeper question to me is one of API intent - is it primarily for humans? If so, the lints make sense. Is it for machines? If so, the lints don't make a whole lot of sense as the public API surface. I obviously have a bias about what the answer should be, but - first time caller, big fan, you know? :)

**Comment by willthames** [comment]
One approach I've taken in the past to this to get reversible camel to snake conversion was to convert `hostIP` to `host_i_p`, but it really depends on how much control you have over the conversion to snake case.

**Comment by adamhjk** [comment]
That’s a nice hack! I still think we should fix it in the object model, though :)

**Comment by liggitt** [comment]
Accepting/normalizing incorrect data introduces ambiguities into the system and requires all consumers of API manifests to do similar normalization (reading data out of manifest files is a reasonable thing to do currently, but would be less reasonable if the manifest files could contain any variety of non-normalized fields)

The openapi schema is published with exact field names used in the API… I would expect generated clients to use that to determine the required serialization.

**Comment by adamhjk** [comment]
@liggitt thanks! Generating from the OpenAPI specification can work. It often requires intervention to be idiomatic - check out this repo as an [for a rust binding as an example]( https://github.com/Arnavion/k8s-openapi), and the list of [fixes here]( https://github.com/Arnavion/k8s-openapi/blob/master/k8s-openapi-codegen/src/fixups/upstream_bugs.rs). That crate (which is excellent) has lots of examples of the hand-rolled serialization code I'm talking about. 

All of this is work-around-able, and I'm going to do that either way. Thank you so much for the pointer.

I agree that consumers of the API should really only have to deal with one format. Ideally, that format is one that is machine generatable across multiple languages idiomatically, and the current code isn't. That's okay - the k8s API is big, and that's life. But I think it's actually a pretty common paper cut kind of issue - you discover it, it hurts you, you fix it, and you move on until you find a case you didn't know or understand, it hurts you, you fix it, and you move on. Over time you stabilize on having gotten through the majority/all of your use case, and then forget about it. 

If it's not possible to fix (because of the impact being too large for users, rather than API consumers), that's okay by me, and completely understandable as a position. If it is something worth investing in fixing, I would be happy to work on a path to doing that. Either way is OK by me. :)

**Comment by fedebongio** [comment]
/assign @liggitt 
thank you for your reply

**Comment by liggitt** [comment]
> check out this repo as an [for a rust binding as an example](https://github.com/Arnavion/k8s-openapi), and the list of [fixes here](https://github.com/Arnavion/k8s-openapi/blob/master/k8s-openapi-codegen/src/fixups/upstream_bugs.rs). That crate (which is excellent) has lots of examples of the hand-rolled serialization code I'm talking about.

The fixups I see in the linked example seem to be mostly around types and optionality, not about specific field name casing. Issues for bugs in the openapi spec are certainly welcome (incorrect return types, incorrectly indicated optionality, etc), but I don't anticipate changing the way field names are handled.

/close

**Comment by adamhjk** [comment]
@liggitt thank you so much for the consideration, thoughtful feedback, and your time.
