### ISSUE TITLE
aws credentials provider causes ~10s-20s hangup on kubelet's initializing docker runtime

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#92162]
Following commit in 1.15 on aws credentials provider  causes ~10s-20s delay(kubelet main goroutine hangup) on kubelet's initializing docker runtime for nodes of K8s clusters not running on AWS:

[Refactors and fixes bugs in AWS credentialprovider - 11efc013288a](https://github.com/kubernetes/kubernetes/commit/11efc013288a15322a6abc0852a4859f7b0785dc)

We observed **20s delay** on our 1.16 production nodes, while on local clusters, the delay is about **9s to 14s**

This commit failed to check whether the node is running on AWS or not before calling AWS APIs. 

Please add this check like other providers, such as GCP,Azure. Thanks.

GCP: https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/gcp/metadata.go#L146
Azure: https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/azure/azure_credentials.go#L157

# Test results
## add trace to pkg/credentialprovider/aws/aws_credentials.go
```
func (p *ecrProvider) Enabled() bool {
	klog.Info("aws_credential:1")
	sess, err := session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
	})
	klog.Info("aws_credential:2")
	if err != nil {
		klog.Errorf("while validating AWS credentials %v", err)
		return false
	}
	klog.Info("aws_credential:3")
	if _, err := sess.Config.Credentials.Get(); err != nil {
		klog.Info("aws_credential:4")
		klog.Errorf("while getting AWS credentials %v", err)
		return false
	}
	klog.Info("aws_credential:5")
	return true
}
```
## our 1.16 production node - 20s delay
```
Jun 16 10:34:59 VM-32-46-ubuntu kubelet[2749059]: I0616 10:34:59.602839 2749059 aws_credentials.go:69] aws_credential:1
Jun 16 10:34:59 VM-32-46-ubuntu kubelet[2749059]: I0616 10:34:59.602926 2749059 aws_credentials.go:73] aws_credential:2
Jun 16 10:34:59 VM-32-46-ubuntu kubelet[2749059]: I0616 10:34:59.602931 2749059 aws_credentials.go:78] aws_credential:3
Jun 16 10:35:19 VM-32-46-ubuntu kubelet[2749059]: I0616 10:35:19.972128 2749059 aws_credentials.go:80] aws_credential:4
Jun 16 10:35:19 VM-32-46-ubuntu kubelet[2749059]: E0616 10:35:19.972153 2749059 aws_credentials.go:81] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
```
### master - 14s
```
I0616 09:50:28.031310  193270 aws_credentials.go:69] aws_credential:1
I0616 09:50:28.031401  193270 aws_credentials.go:73] aws_credential:2
I0616 09:50:28.031408  193270 aws_credentials.go:78] aws_credential:3
I0616 09:50:42.004205  193270 aws_credentials.go:80] aws_credential:4
E0616 09:50:42.004229  193270 aws_credentials.go:81] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
```
### 1.18 - 11s
```
I0616 10:05:18.584844  270482 aws_credentials.go:69] aws_credential:1
I0616 10:05:18.584996  270482 aws_credentials.go:73] aws_credential:2
I0616 10:05:18.585003  270482 aws_credentials.go:78] aws_credential:3
I0616 10:05:29.799597  270482 aws_credentials.go:80] aws_credential:4
E0616 10:05:29.799613  270482 aws_credentials.go:81] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
```
### 1.16 - ~9s
```
I0616 10:15:01.767194   49200 aws_credentials.go:69] aws_credential:1
I0616 10:15:01.767269   49200 aws_credentials.go:73] aws_credential:2
I0616 10:15:01.767273   49200 aws_credentials.go:78] aws_credential:3
I0616 10:15:10.436312   49200 aws_credentials.go:80] aws_credential:4
E0616 10:15:10.436331   49200 aws_credentials.go:81] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
```

**Comment by justinsb** [comment]
@nckturner what do you think about just having `Enabled()` always return true in the ecrProvider?

It looks like the `Provide(image)` function will then only be called, but will immediately short-circuit when it sees that this isn't an ecr image, based on the regex https://github.com/kubernetes/kubernetes/blob/ec36ff40016e1ea612ae364b3b550cd31dd04651/pkg/credentialprovider/aws/aws_credentials.go#L41

That should mean that users can still use ECR from outside of AWS, as long as their AWS credentials are available (e.g. env variables).

**Comment by nckturner** [comment]
@justinsb That seems reasonable.  I'll put together a quick PR and give it a test.

**Comment by therc** [comment]
> @nckturner what do you think about just having `Enabled()` always return true in the ecrProvider?

Hey, I think that was already the case in my original code years ago. I seem to remember trying to avoid (and testing) the scenario in this issue. Not sure why it was changed last year, I wasn't included on the review. Anyway, I'm not sure what else has changed in the meantime in the credential providers, but that sounds like a plan to me.

**Comment by nckturner** [comment]
I'll update https://github.com/kubernetes/kubernetes/pull/93260 today or tomorrow.
