### ISSUE TITLE
Validate mounting volumes by type

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#9218]
Some volumes can be mounted once in a cluster.   Others can be mounted many times, but in different modes.

Gather requirements around each volume, understand their rules, and implement runtime validation to prevent the wrong thing from getting mounted the wrong way on the wrong host.

This is similar to and a complement of scheduling constraints based on volume type: https://github.com/GoogleCloudPlatform/kubernetes/issues/7835

@smarterclayton

**Comment by smarterclayton** [comment]
A PV that is mounted onto a node for pod 1 should not be able to be added to pod 2 on that same node if the PV is not readwritemany.

**Comment by pmorie** [comment]
Example: you shoulnd't be able to mount a secret volume, unless the `VolumeMount` is read-only.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc
