### ISSUE TITLE
kubelet_running_pod_count includes Completed pods

### ISSUE THREAD

**Issue by paulfantom** [kubernetes/kubernetes#92180]
**What happened**:
`kubelet_running_pod_count` metric reported too high values due to including terminated pods created as a result of a CronJob (pod status `Completed`).

**What you expected to happen**:
`kubelet_running_pod_count` includes only data about currently running metrics

**How to reproduce it (as minimally and precisely as possible)**:
1. Check value of `kubelet_running_pod_count`
2. Run any CronJob and wait for it to finish
3. Check again value of `kubelet_running_pod_count`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```
Linux node03 5.4.0-1012-raspi #12-Ubuntu SMP Wed May 27 04:08:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
- Install tools: k3s
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhouya0** [comment]
Should we have `false` here? https://github.com/kubernetes/kubernetes/blob/0a1e58913c5f9cbfe0fe46d11d48e6968b7ce11d/pkg/kubelet/pleg/generic.go#L203

**Comment by paulfantom** [comment]
I would say yes. The metric name suggests value is only about running containers, so IMHO exited containers shouldn't be included.

Created a PR with this fix in #92187

**Comment by fernandocarletti** [comment]
For those looking for a workaround while this is not fixed, I'm getting the running pods count using kube-state-metrics:

```
sum(kube_pod_status_phase{phase="Running"} * on(pod) group_left(node) kube_pod_info) by (node)
```

**Comment by paulfantom** [comment]
Closing as this is fixed in https://github.com/kubernetes/kubernetes/pull/85983
