### ISSUE TITLE
fake client-go panics after deployment scale

### ISSUE THREAD

**Issue by avorima** [kubernetes/kubernetes#92195]
**What happened**:

Scaling and then reading the scaled deployment panics when using a fake client.

**What you expected to happen**:

Reading a recently scaled deployment works when using a fake client.

**How to reproduce it (as minimally and precisely as possible)**:

```go
func TestDeploymentScale(t *testing.T) {
	deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "foo",
			Namespace: metav1.NamespaceDefault,
			Labels:    map[string]string{"app": "foo"},
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: pointer.Int32Ptr(3),
			Selector: &metav1.LabelSelector{MatchLabels: map[string]string{"app": "foo"}},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: map[string]string{"app": "foo"}},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{{Image: "nginx", Name: "nginx"}},
				},
			},
		},
	}
	client := fake.NewSimpleClientset(deployment)

	ns := metav1.NamespaceDefault
	scale := &autoscalingv1.Scale{
		ObjectMeta: metav1.ObjectMeta{Name: "foo", Namespace: ns},
		Spec:       autoscalingv1.ScaleSpec{Replicas: 5},
	}
	_, err := client.AppsV1().Deployments(ns).UpdateScale(context.TODO(), "foo", scale, metav1.UpdateOptions{})
	if err != nil {
		t.Fatal(err)
	}

	client.AppsV1().Deployments(ns).Get(context.TODO(), "foo", metav1.GetOptions{})
}
```

Running this test results in

```
--- FAIL: TestDeploymentScale (0.00s)
panic: interface conversion: runtime.Object is *v1.Scale, not *v1.Deployment [recovered]
        panic: interface conversion: runtime.Object is *v1.Scale, not *v1.Deployment
```

The panic comes from this this type assertion: https://github.com/kubernetes/kubernetes/blob/v1.18.3/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/fake/fake_deployment.go#L52.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  `k8s.io/client-go v0.18.3`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by knight42** [comment]
this issue is almost impossible to fix due to the limitation of the current framework.

/unassign

**Comment by jshen28** [comment]
any update on this issue?

**Comment by innovia** [comment]
a workaround for me was to not use `UpdateScale` but use `Update` I think that the name for the autoscaling block meta is whats being picked up by the getter of the fake

so not using it works for me with `update`
