### ISSUE TITLE
Scheduling framework: test more failure points that trigger Unreserve

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#92229]
See https://github.com/kubernetes/kubernetes/blob/1b93ae57746e0d7a2a553baa9fc53da399c0bd72/test/integration/scheduler/framework_test.go#L963 - currently there's just one test that triggers Unreserve through a pre-bind failure.

**Comment by KofClubs** [comment]
/assign
I shall work on it.

**Comment by kerthcet** [comment]
i saw @Abdullah Gharaibeh commented the only test code, do you have any idea why this going on? @adtac

**Comment by kerthcet** [comment]
> i saw @AbdullahGharaibeh commented the only test code, do you have any idea why this going on? @adtac

well, I found some functions missing, maybe because of the code refactor.
