### ISSUE TITLE
Default PodSpec.enableServiceLinks to false

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#92226]
**What would you like to be added**:
I would like the default for `enableServiceLinks` to be changed from `true` to `false` 

**Why is this needed**:

I think the default behaviour is unexpected for new users. Having this be an opt-in feature may be more predictable. 

References:
https://github.com/kubernetes/kubernetes/issues/60099
https://github.com/elastic/cloud-on-k8s/issues/2030
https://github.com/knative/serving/issues/6074
https://stackoverflow.com/questions/45323958/is-it-possible-to-disable-service-discovery-with-environment-variables-in-kubern
https://twitter.com/fredbrancz/status/1201937181230686208

**Comment by dprotaso** [comment]
Dunno where PodSpec falls - best guess is

/sig api-machinery

**Comment by liggitt** [comment]
/remove-sig api-machinery
/sig node

Thanks for the request, but changing defaults in an existing API is not backwards compatible, and changing this particular default would break many existing users. Our compatibility guarantees are intended to keep existing API versions operating in backwards compatible ways.

**Comment by dprotaso** [comment]
Is there an umbrella PodSpec v2 issue that's tracking potential future changes?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/8190 is the closest thing I know of

**Comment by dprotaso** [comment]
@liggitt Can we re-open this issue - it seems like service links will degrade pod start time even when there's a modest # of services in a namespace.


Context: https://github.com/knative/serving/issues/8498#issuecomment-650614371

**Comment by mattmoor** [comment]
It's actually worse than that.  Above a certain number of services new pods will fail to start altogether.

**Comment by liggitt** [comment]
> @liggitt Can we re-open this issue - it seems like service links will degrade pod start time even when there's a modest # of services in a namespace.

A distinct issue tracking performance problems or startup issues would be fine, but changing the default for core/v1 isn't really an option... it would break far more current users.

**Comment by dprotaso** [comment]
Sounds good
