### ISSUE TITLE
Node e2e remote runner is broken

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92241]
**What happened**:
Not completely sure what happen but the node e2e test runner is not working and it seems to be due to https://github.com/kubernetes/kubernetes/commit/4c8e5c5a50ba72dcec3fdea06b5d6dd4897dd303#diff-cf414d98f9d30ef4489021c4415e797e
Checked commits before that one (the one right before it is https://github.com/kubernetes/kubernetes/commit/019d3ee4380959d28da07a7b14fc7583833ca433#diff-cf414d98f9d30ef4489021c4415e797e ) and it seems to work right until https://github.com/kubernetes/kubernetes/pull/91543 merged.
See the full git history here https://github.com/kubernetes/kubernetes/commits/master/test/e2e_node

**How to reproduce it (as minimally and precisely as possible)**:

The way i'm testing it with 
```
make test-e2e-node FOCUS="\[Flaky\]" SKIP="" PARALLELISM=1 REMOTE=true DELETE_INSTANCES=true IMAGE_CONFIG_FILE=perf-test.yaml TEST_ARGS='--server-start-timeout=120s'
```
The contents of `perf-test.yaml` are
```yaml
images:
  ubuntu:
    image: ubuntu-gke-1804-1-17-v20200605 # docker 19.03.2 / containerd 1.2.10
    project: ubuntu-os-gke-cloud
    machine: n1-standard-16
    tests:
      - 'Node Performance Testing'
```

That would normally work but since the PR mentioned above it fails to get a kubelet for testing properly setup:
```
I0617 22:19:08.640321    3500 server.go:102] Starting server "services" with command "/tmp/node-e2e-20200617T181700/e2e_node.test --run-services-mode --test.timeout=24h0m0s --ginkgo.seed=1592432279 --ginkgo.focus=Node Performance Testing --ginkgo.slowSpecThreshold=5.00000 --system-spec-name= --system-spec-file= --extra-envs= --logtostderr --v 4 --node-name=n1-standard-16-ubuntu-gke-1804-1-17-v20200605-f5e8361c --report-dir=/tmp/node-e2e-20200617T181700/results --report-prefix=ubuntu --image-description=ubuntu-gke-1804-1-17-v20200605 --kubelet-flags=--experimental-kernel-memcg-notification=true --server-start-timeout=120s"
I0617 22:19:08.640343    3500 util.go:44] Running readiness check for service "services"
I0617 22:19:08.640414    3500 server.go:130] Output file for server "services": /tmp/node-e2e-20200617T181700/results/services.log
I0617 22:19:08.640730    3500 server.go:160] Waiting for server "services" start command to complete
Failure [160.282 seconds]
[BeforeSuite] BeforeSuite 
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:174

  should be able to start node services.
  Expected success, but got an error:
      <*errors.errorString | 0xc000776df0>: {
          s: "failed to run start command for server \"services\": exit status 255",
      }
      failed to run start command for server "services": exit status 255

  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:196
------------------------------
```

/cc @kubernetes/sig-node-test-failures 
/priority critical-urgent

**Comment by alejandrox1** [comment]
Interesting thing...
This is the output that the make test-e2e-node command above would output before https://github.com/kubernetes/kubernetes/pull/91543 was merged

```
I0617 21:55:46.886869    3484 server.go:102] Starting server "kubelet" with command "/usr/bin/systemd-run -p Delegate=true --unit=kubelet-20200617T175336.service --slice=runtime.slice --remain-after-     exit /tmp/node-e2e-20200617T175336/kubelet --kubeconfig /tmp/node-e2e-20200617T175336/kubeconfig --root-dir /var/lib/kubelet --v 4 --logtostderr --dynamic-config-dir /tmp/node-e2e-20200617T175336/dynamic-kubelet-config --network-plugin=kubenet --cni-bin-dir /tmp/node-e2e-20200617T175336/cni/bin --cni-conf-dir /tmp/node-e2e-20200617T175336/cni/net.d --cni-cache-dir /tmp/node-e2e-20200617T175336/cni/       cache --hostname-override n1-standard-16-ubuntu-gke-1804-1-17-v20200605-c23c52f4 --container-runtime docker --container-runtime-endpoint unix:///var/run/dockershim.sock --config /tmp/node-e2e-            20200617T175336/kubelet-config --experimental-kernel-memcg-notification=true"
```

Which is completely different from what happens now

**Comment by MHBauer** [comment]
Is there more test output? Do you see it choosing the image?

**Comment by MHBauer** [comment]
I can't find the magical args to run remotely, but I do appreciate the command to test this.

**Comment by alejandrox1** [comment]
> Is there more test output? Do you see it choosing the image?

There is but im trying to figure out what are the parts that matter :sweat_smile: 

---

> I can't find the magical args to run remotely, but I do appreciate the command to test this.

This may help make some sense of the runner...
* The entrypoint intho the e2e tests is here https://github.com/kubernetes/kubernetes/blob/7b0d7847ecd915f3d74a14501222e49f07526081/test/e2e_node/runner/remote/run_remote.go#L324

During e2e tests, the runner stands up a kubelet and the part that handles that is defined here
* https://github.com/kubernetes/kubernetes/blob/7b0d7847ecd915f3d74a14501222e49f07526081/test/e2e_node/runner/remote/run_remote.go#L186-L197

**Comment by MHBauer** [comment]
I'm on a mac, and it seems to be building for darwin, and then copying those over to gcloud and blowing up.

I have tried setting `export KUBE_BUILD_PLATFORMS='linux/amd64'` or some combination with darwin/amd64, but then the build just straight up doesn't work with output from `hack/lib/golang.sh` complaining about 
`go install: cannot install cross-compiled binaries when GOBIN is set` and I'm out of ideas.

**Comment by alejandrox1** [comment]
ha linux support strikes again!
i'll continue working on this and putting as much info as i find here.
but you should make an issue about the problem you found! I don't know if it is possible (I recall there being some other issues about building Kubernetes on mac) but i think it may be useful to look into it a bit :thinking:

**Comment by alejandrox1** [comment]
ight, after a looooong time bisecting the commit history of all of k/k, not just for k/k/test/e2e_node - I've been reading and reading #91543 and it looks ok.
I discovered that the test runner works ok in https://github.com/kubernetes/kubernetes/commit/3509b46fc6fe2bb5ee3ab9cdca0c3e4f93025042
but then breaks on the next commit at https://github.com/kubernetes/kubernetes/commit/3f8bb1bf50fb5a13a5823bdbc49bd6c2198752db
.

The latter corresponds to https://github.com/kubernetes/kubernetes/pull/91685 and here is the diff https://github.com/kubernetes/kubernetes/compare/3509b46fc6fe2bb5ee3ab9cdca0c3e4f93025042...3f8bb1bf50fb5a13a5823bdbc49bd6c2198752db

Im reviewing the diff but not real suspects as to why that could have broken the runner...

**Comment by alejandrox1** [comment]
By the way, this is the commit history for the days around which the test runner broke https://github.com/kubernetes/kubernetes/commits/master?after=7b0d7847ecd915f3d74a14501222e49f07526081+244

**Comment by alejandrox1** [comment]
This magically started working after some 50 failures yesterday.
So i'll try and replicate the failure to see why they were happening but otherwise lowering the priority on this
/priority-remove critical-urgent
/priority important backlog

**Comment by bsdnet** [comment]
I am wondering whether we can come out some better bi-sect tool :). I closely monitor sig-node-containered tests those days. I saw sometimes some tests suddenly stopped working. After a couple of runs, it succeeds again.

**Comment by MHBauer** [comment]
@alejandrox1 I think we're done with this issue for now. We've got improved logging and the remote runner will fail loudly if images fail to be used instead of silently succeeding.

/close

I saw this while searching. I want to move the "Node Performance Tests" out of the flaky job now that we've gotten the proper resources to run the tests successfully.
