### ISSUE TITLE
Rewrite typecheck using go/packages to be module friendly 

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#92253]
Ref: https://github.com/kubernetes/kubernetes/pull/92212#issuecomment-645277504
For https://github.com/kubernetes/kubernetes/issues/82531

Today, the [typecheck](https://github.com/kubernetes/kubernetes/tree/master/test/typecheck) tool uses the `go/types` package for type checking. This is a legacy package and doesn't work without GOPATH -- which means it isn't truly compatible with go modules.

The recommendation from the Go team is to use  [`golang.org/x/tools/go/packages`](https://godoc.org/golang.org/x/tools/go/packages) instead of `go/types` going forward.

To make [`verify-typecheck.sh`](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-typecheck.sh) module-friendly, we should update the typecheck tool to use [`golang.org/x/tools/go/packages`](https://godoc.org/golang.org/x/tools/go/packages).

/sig testing
/kind feature

**Comment by nikhita** [comment]
This is being fixed in https://github.com/kubernetes/kubernetes/pull/92212

**Comment by BenTheElder** [comment]
done in https://github.com/kubernetes/kubernetes/pull/92212
/assign @thockin 
/close
