### ISSUE TITLE
Don't collect metrics if csi migration is not being tested

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#92269]
**Which jobs are flaking**:
pull-kubernetes-e2e-gce

**Which test(s) are flaking**:
storage tests

**Testgrid link**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=metrics%3A%20the%20server%20is%20currently%20unable%20to%20handle%20the%20request

**Reason for failure**:
Probably unnecessary load on the metrics endpoints.

```
Jun 18 19:37:35.868: Error getting Kubelet e2e-50bc3b6a92-674b9-minion-group-6d17 metrics: the server is currently unable to handle the request (get nodes e2e-50bc3b6a92-674b9-minion-group-6d17:10250)
Unexpected error:
    <*errors.StatusError | 0xc000e1f220>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server is currently unable to handle the request (get nodes e2e-50bc3b6a92-674b9-minion-group-6d17:10250)",
            Reason: "ServiceUnavailable",
            Details: {
                Name: "e2e-50bc3b6a92-674b9-minion-group-6d17:10250",
                Group: "",
                Kind: "nodes",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "Error trying to reach service: 'dial tcp 10.40.0.3:10250: i/o timeout'",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 503,
        },
    }
    the server is currently unable to handle the request (get nodes e2e-50bc3b6a92-674b9-minion-group-6d17:10250)
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
The logic  [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/base.go#L697) is supposed to ignore the metrics results if the test job is not configured to test csi migration. However, this is checked after trying to collect metrics from all the nodes. We should probably move this check earlier to reduce load on the metrics endpoints.

**Comment by msau42** [comment]
However, once csi migration is enabled by default, this problem will come back. But maybe by that time we could remove the metrics check from the tests altogether since we would have also removed all the in-tree plugin code at the same time.

**Comment by msau42** [comment]
cc @mattcary

**Comment by mattcary** [comment]
Thanks, I'll look at this in the next few days.

**Comment by msau42** [comment]
Interesting observation from the triage link is it appears to fail more in the last week.

**Comment by BenTheElder** [comment]
Thanks everyone.
