### ISSUE TITLE
Feature Request: Deployment Blue/Green Strategy

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#92267]
**What would you like to be added**:
Deployment has a strategy field in the specification that could be enhanced to add a new option, maybe named `Replace` or `BlueGreen` (naming up for debate).

This new strategy could use a new label (naming up for debate) to distinguish between blue and green ReplicaSets, allowing for two different Services to point at the pods, one for blue and one for green. Each new change to the Deployment would still make a new ReplicaSet, and the blue/green label would alternate between revisions.

As with the `RollingUpdate` strategy, this new strategy would keep the existing ReplicaSet after making a new one, but instead of scaling down the old ReplicaSet, it would be kept at full scale while the new ReplicaSet's Pods are coming up.

After the new ReplicaSet (ex: green) is fully scaled and all pods are ready, the old ReplicaSet (ex: blue) would NOT be immediately deleted by the deployment controller. Instead, the Deployment would stay in that state until something is changed (in the spec?) to specify whether to keep the new green ReplicaSet and delete the old blue ReplicaSet OR "rollback" the Deployment change (revert to previous spec?) and keep the old blue ReplicaSet. This gating and rollback could perhaps be managed with enhancements to the kubectl rollout command (ex: `kubectl rollout continue` and `kubectl rollout undo`).

With two Services, one selecting on blue and the other on green, the (human or automated) operator would be able to route traffic (via ingress or other load balancer) to both ReplicaSets simultaneously and independently (ex: different DNS or paths or selection via header).

**Why is this needed**:
Blue/Green Deployment (aka Red/Black) is a common deployment strategy that is generally necessary for uses cases where the old and new instances conflict with each other (ex: reverse incompatible API or database change). In some cases, you may also want to use RollingUpdate for the general case but switch to Blue/Green for special occasions. Rolling is more efficient in terms of resources, but Blue/Green is potentially safer and more consistent for clients when not using sticky sessions. Blue/Green also allows for manual or automated testing on the new ReplicaSet without having to migrate all users to the new version (via load balancing or API gateway reconfiguration).

This enhancement would unblock further enhancements (or third party tools/CRDs) to automate Blue/Green lifecycle management (ex: using Service/Ingress/Gateway, Knative or Spinnaker). Integrated end to end testing/validation (ex: CI/CD integration) would allow Blue/Green rollout and rollback to be fully automated with confidence. 

/sig apps
@kubernetes/sig-apps-feature-requests

**Comment by karlkfi** [comment]
Example of how traffic shifting might work:
1.  User creates Deployment with strategy=RollingUpdate and label app=X & Service A with selector app=X
1.  Controller creates initial ReplicaSet A with labels app=X and color=blue 
1. User adds Service A selector color=blue to pin that DNS/IP/Ingress to route to the current revision. 
1. User changes Deployment strategy=BlueGreen and updates the docker image tag
1. Controller creates new ReplicaSet B with app=X and color=green and replicas set to the same number as ReplicaSet A
1. User creates a new Service B with app=X and color=green for staging/testing. 
1. User validates new functionality
1. User changes Service A selector to color=green
1. Endpoint Controller updates endpoints for Service A
1. Kube Proxy updates iptables to route Service A traffic to ReplicaSet B (and Ingress Controllers like Nginx update backends)
1. User signals to Deployment to scale down ReplicaSet A
1. Deployment controller updates replicas=0 on ReplicaSet A


The second to last step I’m not certain how to specify yet. I’m open to suggestions. 

One way might be to add a new spec field that indicates just a boolean like RetainLastReplicas=true that can be set to false by the user in order to indicate that validation is complete and ReplicaSet A can be set to 0 replicas. One problem with this is that the Boolean needs to be set back to true on every user change, which is undesirable. 

Another way might be to just always retain the replicas on the latest 2 ReplicaSets. This is probably not a desirable default, but theoretically the User could then reduce the replicas on the old ReplicaSet if they wanted. This has the benefit that whatever controller ends up managing the higher level Service/Ingress lifecycle automation could do this automatically, even if the Deployment controller doesn’t handle it. 

I’m sure there are other options too.

**Comment by karlkfi** [comment]
I forgot the obvious default:
The old ReplicaSet should be scaled to zero as soon as all the pods in the new ReplicaSet are Ready. That way the default has no manual gate and automatically completes. 

That would mean that a continuation gate is optional and opt-in. If that’s the case, it seems potentially reasonable to have a Boolean field that needs to be flipped every time you want a change to keep the old ReplicaSet at full scale after the new ReplicaSet pods are ready. 

Maybe KeepLegacyPods=true ?

**Comment by krmayankk** [comment]
i like the simple idea of putting a knob(strategy) that keeps both ReplicaSet around and signal someway the other RS should go away. There is a lot of logic that goes in Deployment controller to manage these ReplicaSets and i would like that not replicated in external controllers if possible. Here is one [example](https://argoproj.github.io/argo-rollouts/)  which actually manages ReplicaSets for purposes of advanced blue/green strategies. [ArgoRollout](https://argoproj.github.io/argo-rollouts/) brings down the new RS based on an AnalysisTemplate which could be many things. So, instead of adding all that logic, i would be in favor of just a boolean type that signals the bringing down of old RS and then finally marks the Deployment as complete and available. The [AnalysisTemplate](https://argoproj.github.io/argo-rollouts/features/analysis/) kind of functionality can then be layered on top of this. This would also require manipulating a lot of the status properties like availableReplicas and see what that means in this context.
     Having said, we should also look at how many people/efforts/community members would this benefit, vs all the efforts that have already propped up on top of core kubernetes to layer complex blue/green . One place to ask that question would be https://discuss.kubernetes.io/ as well as on slack(kubernetes-users to get some feedback. looking forward to others opinions on this

**Comment by karlkfi** [comment]
It’s worth also considering Canary strategy while brainstorming what fields to add for BlueGreen. It might lead to a more elegant API, even if we decide not to implement Canary and leave that for the traffic routing LB layer to handle. 

If you manage Canary at the L7 LB layer, that allows use of headers and session stickiness, which is a requirement for many (but not all) cases to achieve consistent client user experience. One benefit with this approach is that you could use BlueGreen deployment strategy and then optionally canary a small set of users/traffic via LB. One big downside is that a BlueGreen canary may be wasteful and slow with both ReplicaSets at the same full number of replicas, spinning up potentially hundreds of new replicas just to support a small amount of initial traffic. So even if the LB handles percentage routing, it may still be desirable to have a more controllable scale up strategy, regardless of whether the old ReplicaSet is scaling down.

If we manage Canary using replica count, we could make use of the BlueGreen color labels, but then is Canary an optional variation of BlueGreen or a distinct strategy? Canary is sometimes done more like RollingUpdate, where the old ReplicaSet is still scaled down as the new ReplicaSet is scaled up. This wouldn’t necessarily need the BlueGreen labels, but it might still be desirable to have them, to enable smarter LB routing logic. 

We might want to just ALWAYS set color labels on Deployment ReplicaSets for simplicity. 

One way to support all permutations might be to have 4 different strategies: RollingUpdate, RollingCanary, BlueGreen, BlueGreenCanary. But I’m not sure this has much merit. 

Another option might be to add a “canaries=(#or%)” field to both the BlueGreen and RollingUpdate strategies (or outside the strategy?). This may be unintuitive but it could be a way to handle gating. It would be similarl to how Knative does with its Route percentages, only relative to the Deployment’s replica count instead of relative to all traffic, and only supporting 2 concurrent revisions instead of many. 

BlueGreen with canaries=100% would mean “keep both ReplicaSets at full scale”. BlueGreen with canaries=0 would mean “scale down new ReplicaSet to 0 (aka rollback)”. BlueGreen with canaries=10% would mean “old ReplicaSet stays at 100%, new ReplicaSet scales up to 10%, and wait for instructions”.

RollingUpdate with canaries=100% would be the default existing behavior and mean to complete the rollout if canaries was previously not-100%. RollingUpdate with canaries=0 would be “scale down new ReplicaSet to 0 (aka rollback)”. RollingUpdate with canaries=10% would mean “old ReplicaSet scales down to 90%, new ReplicaSet scales up to 10%, and wait for instructions”.

Then we just need an analogous field for the #or% of the old ReplicaSet for BlueGreen. Whatever the opposite of a canary is. Legacy/Legacies? Miner/Miners (from canary in the coal mine analogy)?

P.S. we don’t need to support all 4 strategies up front or even at all. I just wanted to consider them to avoid needing to backpedaling an incompatible API. Don’t throw out the baby with the bath water if you don’t like this part of the suggestion.

**Comment by karlkfi** [comment]
> So, instead of adding all that logic, i would be in favor of just a boolean type that signals the bringing down of old RS and then finally marks the Deployment as complete and available. The AnalysisTemplate kind of functionality can then be layered on top of this.

This is exactly what I was thinking. 

This enhancement wouldn't completely replace existing tools that do blue/green, it would just provide a lower level abstraction that would satisfy basic use cases (blue/green rollout without validation or with manual validation). It would then allow the higher level abstractions to be thinner and focus on what makes them unique, rather than what they all have in common.

[Knative Serving](https://knative.dev/docs/serving/), for example, has the ability to do blue/green and canary rollouts using revision percentages at the routing layer. With this new enhancement, similar behavior could be performed using a Deployment at the replica count layer instead, without having to install Istio & Knative. But this wouldn't make Knative Serving obsolete, because it still has FaaS-like load balancing driven autoscaling and supports N concurrent revisions, not just the latest 2.

[Argo Rollouts](https://argoproj.github.io/argo-rollouts/) and [Spinnaker Canary Analysis](https://www.spinnaker.io/reference/pipeline/stages/#canary-analysis) ([Kayenta](https://github.com/spinnaker/kayenta)) both have advanced validation that can help automate the decision making process of the go/no-go gates. With this new enhancement, the gating would be build-in, but not the decision making process. So you could use blue/green with no gate, blue/green with manual gate, or canary with manual gate, without needing any extra tools on top of Kubernetes. But WITH those tools, you can go the next step into full end to end self-validating automated rollouts.

My hope is that this would allow less duplication of Deployment functionality in 3rd party tools that previously had to replace the Deployment resource and controller in order to provide advanced functionality.

**Comment by karlkfi** [comment]
RFC: https://docs.google.com/document/d/17vmPjg1DoLzwxgbAfAsSdFqdaQ4SsnZcQugDZ1qFN9s/edit

**Comment by hjanuschka** [comment]
issue is closed, the gdoc is not updated and no KEP has been filed, is this going to get worked on?

**Comment by karlkfi** [comment]
I spoke to sig-apps about it and they didn’t seem interested in having an upstream PR unless it was vetted in a fork or custom operator first and had support from other operators/tools that already do blue/green that they would use it. 

I was just trying to contribute what seemed like an important missing feature while in between gigs for a few months, but it seems like getting this upstream will be more effort than I have time for right now.
