### ISSUE TITLE
Annotating Cronjobs

### ISSUE THREAD

**Issue by johnfedoruk** [kubernetes/kubernetes#92280]
**What would you like to be added**:

As of Kubernetes 1.17.4, annotating cronjobs is not supported.

Example:

```bash
$ kubectl annotate cronjob.v1.apps/${CRONJOB_NAME} kubernetes.io/change-cause="Release $(git describe --abbrev=0)" --namespace=${NAMESPACE}
error: the server doesn't have a resource type "cronjob"
```

**Why is this needed**:

Annotated cronjobs could be of value for maintaining a history record of previously deployed versions and supporting rollbacks.

**Comment by knight42** [comment]
@johnfedoruk you have specified the wrong apiVersion. please try `kubectl annotate cronjob.v1beta1.batch ...` or simply `kubectl annotate cronjob ...`

**Comment by nikhita** [comment]
Please see @knight42's comment above https://github.com/kubernetes/kubernetes/issues/92280#issuecomment-646421950 for fixing this. Closing the issue, please reopen if you run into any problems!

/close
