### ISSUE TITLE
Deprecation notice of CRD can be printed in kubectl commands

### ISSUE THREAD

**Issue by muvaf** [kubernetes/kubernetes#92290]
**What would you like to be added**:

When a CRD is deprecated, we are able to put a deprecation notice in its code but this isn't actually visible to the end-user. What I'd like to see is something like:
```
$ kubectl create -f my-cr-instance.yaml
warning: somekind.example.org has been deprecated and will be removed after v1.2, use otherkind.example.org
somekind.example.org/foo created
```

**Why is this needed**: In order to let users know it's not going to be supported in the next releases.

I believe an annotation on CRD or a string field in spec to include the deprecation warning could be feasible.

**Comment by liggitt** [comment]
This is planned/tracked as part of https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1693-warnings (see the custom resource definition section of that design) and will likely being implemented in 1.20
