### ISSUE TITLE
clusterDNS does not dedup entries

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#9229]
In `pkg/kubelet/kubelet,go` in `getClusterDNS(...)`, it appends cluster DNS nameserver and search paths to the ones in the host resolv.conf.

A user reported trying to add skydns nameserver address and kubernetes search paths to the host resolv.conf.  Not what the instructions say to do, but a reasonable thing to do.  Very reasonable if you want to be able to resolve service names while debugging from the root UTS namespace.

This wasn't working for the user.  One thing I think would go wrong here is that if the node has 1 or 2 search paths, and then the user added the 3 for kubernetes, that is 5.  Then when kubelet adds 3 more (duplicate) entries, you get 8, which exceeds the limit of 6.  

Would it be better if the code filtered duplicate search entries?

**Comment by bowei** [comment]
Looks like PR #29270 removes duplicates
