### ISSUE TITLE
Is it possible to handle connection reset by peer exeception in this library?

### ISSUE THREAD

**Issue by buxizhizhoum** [kubernetes/kubernetes#92298]
**Handle the connection reset by peer exeception**:

**I am using KubernetsPodOperator in airflow, which deps on this library, and when there is no log from pod for a long time there is an exeception:
[2020-06-17 15:04:53,084] {connectionpool.py:750} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /api/v1/namespaces/oflow-test/pods/oflow-kuberbetes-test-24972430/log?container=base&follow=True&tailLines=10**:

the test case I used is:
`import datetime
from unittest import TestCase

from airflow import settings
from airflow.kubernetes.volume import Volume
from airflow.kubernetes.volume_mount import VolumeMount
from airflow.operators.kubernetes_pod_operator import KubernetesPodOperator

class TestKubernetesPodOperator(TestCase):
    def setUp(self):
        self.namespace = "airflow-test"
        self.image = "ubuntu:16.04"
        self.name = "test-task"
        self.config_file = "/home/think/.kube/config.yml"
        self.cluster_context = "default"

        self.dag_id = "test_onoff"
        self.task_id = "root_test_onoff"
        self.execution_date = datetime.datetime.now()

        self.context = {"dag_id": self.dag_id,
                        "task_id": self.task_id,
                        "execution_date": self.execution_date}

        self.cmds = ["sleep"]
        self.arguments = ["6000"]  # if there is no output for a long time, there will be connection reset by peer exception

        self.resources = {
            "limits":
                {"memory": "512Mi",
                 "cpu": "500m"},
            "requests": {
                "memory": "512Mi",
                "cpu": "500m"}
        }

        self.security_context = {}

        self.operator = KubernetesPodOperator(
            namespace=self.namespace,
            image=self.image, 
			name=self.name,
            cluster_context=self.cluster_context,
            config_file=self.config_file,
            cmds=self.cmds,
            arguments=self.arguments,
            startup_timeout_seconds=600,
            is_delete_operator_pod=True,
            resources=self.resources,
            security_context=self.security_context,
            # the operator could run successfully but the directory /tmp
            # is not mounted to kubernetes operator
            **self.context)

    def test_execute(self):
        self.operator.execute(self.context)`

**Comment by BenTheElder** [comment]
the python client is here with their own issue tracker https://github.com/kubernetes-client/python
please file an issue with their tracker
/close
