### ISSUE TITLE
Kube proxy is blocking LIST requests intended to be forwarded through `kubectl proxy`

### ISSUE THREAD

**Issue by zystem** [kubernetes/kubernetes#92305]
**What happened**:
I created a very basic Nginx replication controller, and a service that points to that Nginx server.

Then, I use kubectl proxy and do this request:

`curl -X GET http://localhost:8001/api/v1/namespaces/default/services/nginx:80/proxy/`

This works fine. But! When I do this request:

```
curl -X LIST http://localhost:8001/api/v1/namespaces/default/services/nginx:80/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {
    
  },
  "code": 405
}
```

I get that error message.

**What you expected to happen**:

The proxy would successfully forward my request even if it is a LIST.

**How to reproduce it (as minimally and precisely as possible)**:
Install Nginx: helm install nginx

Then kubectl proxy

and run this command: curl -X LIST http://localhost:8001/api/v1/namespaces/default/services/nginx:80/proxy/

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
KOPS on AWS

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"

- Kernel (e.g. `uname -a`):
3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubectl proxy

**Comment by liggitt** [comment]
LIST is not a recognized http method. API list requests are normal http GET requests, made to an endpoint that returns a list response. 

Using GET is the correct approach.
