### ISSUE TITLE
Rename CommonImageWhiteList

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92319]
**What would you like to be added**:
We should come up with a better name for `CommonImageWhiteList`:
https://github.com/kubernetes/kubernetes/blob/403716626d126c850c233a85977de0e6ce60d8ec/test/e2e/common/util.go#L60-L64

**Why is this needed**:
From #90277

> Associating "white" with good/allowed and "black" with bad/disallowed cannot be disentangled from systemic racism. In contrast, allowlist and denylist exactly and merely describe the functions of these fields and variables.

/sig testing
/priority important-soon
/cleanup
/help
/good-first-issue

**Comment by BenTheElder** [comment]
@RobertKielty what happened with https://github.com/kubernetes/kubernetes/pull/92327 ?

**Comment by RobertKielty** [comment]
I redid it here https://github.com/kubernetes/kubernetes/pull/92359
