### ISSUE TITLE
Use PrepullList in e2e framework

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92317]
Similar to https://github.com/kubernetes/kubernetes/issues/90277 we should switch up from "WhiteList" to "AllowList" in the e2e framework.

**What would you like to be added**:
Within the e2e framework, there is a definition of a set of images to be used for a test suite:
https://github.com/kubernetes/kubernetes/blob/403716626d126c850c233a85977de0e6ce60d8ec/test/e2e/framework/pods.go#L60-L63

We should rename this to `AllowList` here and in all other places where it is used:
```
$ grep -nr ImageWhiteList
e2e/framework/pods.go:60:// ImageWhiteList is the images used in the current test suite. It should be initialized in test suite and
e2e/framework/pods.go:63:var ImageWhiteList sets.String
e2e/framework/pods.go:190:		gomega.Expect(ImageWhiteList.Has(c.Image)).To(gomega.BeTrue(), "Image %q is not in the white list, consider adding it to CommonImageWhiteList in test/e2e/common/util.go or NodeImageWhiteList in test/e2e_node/image_list.go", c.Image)
e2e/common/runtime.go:268:			// Images used for ConformanceContainer are not added into NodeImageWhiteList, because this test is
e2e/common/util.go:60:// CommonImageWhiteList is the list of images used in common test. These images should be prepulled
e2e/common/util.go:64:var CommonImageWhiteList = sets.NewString(
e2e_node/runtime_conformance_test.go:51:			// The following images are not added into NodeImageWhiteList, because this test is
e2e_node/image_list.go:46:// NodeImageWhiteList is a list of images used in node e2e test. These images will be prepulled
e2e_node/image_list.go:48:var NodeImageWhiteList = sets.NewString(
e2e_node/image_list.go:64:// updateImageAllowList updates the framework.ImageWhiteList with
e2e_node/image_list.go:69:	// Union NodeImageWhiteList and CommonImageWhiteList into the framework image white list.
e2e_node/image_list.go:70:	framework.ImageWhiteList = NodeImageWhiteList.Union(commontest.CommonImageWhiteList)
e2e_node/image_list.go:72:	framework.ImageWhiteList.Insert(getNodeProblemDetectorImage())
e2e_node/image_list.go:73:	framework.ImageWhiteList.Insert(getSRIOVDevicePluginImage())
e2e_node/image_list.go:152:	images := framework.ImageWhiteList.List()
```

**Why is this needed**:
From https://github.com/kubernetes/kubernetes/issues/90277

> Associating "white" with good/allowed and "black" with bad/disallowed cannot be disentangled from systemic racism. In contrast, allowlist and denylist exactly and merely describe the functions of these fields and variables.

/sig testing
/priority important-soon
/cleanup

**Comment by spiffxp** [comment]
Yes I'm in favor of changing them.  But I'm not sure `allowlist` makes sense here, this isn't necessarily being used as a filter.

It looks like node, common and pods all use something for prepulling / describing images used in test.  Maybe something like 'PrePulledImagesList`?

**Comment by BenTheElder** [comment]
+1

Let's please clean these up.
I will personally prioritize review and approve fixes for this, you can comment `/assign @bentheelder` to assign me on any associated Pull Requests.

/help
/good-first-issue

**Comment by BenTheElder** [comment]
/remove-help
/remove-good-first-issue
oops, it seems @alejandrox1 is already working on this.
+1 to @spiffxp's comment.

**Comment by alejandrox1** [comment]
/retitle Use PrepullList in e2e framework

and thank you @spiffxp @BenTheElder for the comments.
Ima leave these 2 labels for now
/help
/good-first-issue

Just wanted to get an example out there.
Gonna try and find more instances of this kind of thing in /test.

**Comment by alejandrox1** [comment]
on a second thought, https://github.com/kubernetes/kubernetes/pull/92318#discussion_r443010567, let me just do this one and ill search for more "good first issues" since we have some consensus about this.
/remove-help
/remove-good-first-issue
/assign

**Comment by markyjackson-taulia** [comment]
I am +1 for this

**Comment by hasheddan** [comment]
+1 please feel free to tag me for reviews as well

**Comment by SataQiu** [comment]
+1 for this
