### ISSUE TITLE
Default namespace changes when kubectl run from inside pod

### ISSUE THREAD

**Issue by lonnix** [kubernetes/kubernetes#92313]
**What happened**: 
I deployed a pod to my cluster (call it the host pod) and ran `kubectl` commands from inside that pod without specifying a namespace. When I ran `kubectl get pods` I got back a list of all pods in the same namespace as the host pod

**What you expected to happen**:
I expected to get back a list of pods from the `default` namespace because I did not specify a namespace

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy pod with kubectl functionality to a non-default namespace
2. Connect to any cluster with a kubeconfig file & context that does not specify/restrict to a namespace
3. Exec into pod and run `kubectl get pods`
4. Determine if pod list is from `default` namespace or the same one as the host pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client: 1.18.4, Server: 1.15.11-eks-af3caf
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): linux (multiple flavors)

I have done as much investigation as I can and here is what I've found:
1. kubeconfig file does not specify a namespace and the user in kubeconfig has access to all namespaces
2. no environment variables are set 
3. nothing is set via command line (no `--namespace` or `-n` on any commands)
4. this happens with kubectl and helm (v3.0.2)
5. it does not matter which cluster your kubectl commands run against, it will use the host pod namespace. I tested on both the same cluster as the host pod as well as a completely separate cluster
6. if I use the same kubeconfig file on my local laptop it does use the `default` namespace unless I specify one on the command line

I am filing this because I assume it is a bug. I cannot see a reason why the default namespace would change based on where kubectl is run from. If this is the intended behavior that is fine, I would just like to know where that config is coming from. 

I also acknowledge that not all of my versions are up to date, but I can't upgrade my environment to latest right now. If it can't be reproduced on the latest versions I am fine with just assuming it is a bug that has since been fixed.

**Comment by liggitt** [comment]
The default namespace for the in-cluster configuration injected into each pod is the namespace matching the running pod. 

This is described at https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

> the default namespace to be used for namespaced API operations is placed in a file at /var/run/secrets/kubernetes.io/serviceaccount/namespace in each container
