### ISSUE TITLE
Rename NodeImageWhiteList

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92320]
**What would you like to be added**:
We should come up with a better name for `NodeImageWhiteList`:
https://github.com/kubernetes/kubernetes/blob/403716626d126c850c233a85977de0e6ce60d8ec/test/e2e_node/image_list.go#L46-L48

**Why is this needed**:
From #90277

> Associating "white" with good/allowed and "black" with bad/disallowed cannot be disentangled from systemic racism. In contrast, allowlist and denylist exactly and merely describe the functions of these fields and variables.

/sig testing
/priority important-soon
/cleanup
/help
/good-first-issue

**Comment by wfernandes** [comment]
@alejandrox1 I'd like to help out with this. 
/assign

**Comment by wfernandes** [comment]
Whoops...never mind. It seems like you have a PR for it already.
/unassign

**Comment by wfernandes** [comment]
And I misread the changes you made in #92318. I'm back on this one. 
/assign

**Comment by wfernandes** [comment]
I'm going to rename this to `NodeImageAllowList`. Please let me know if there are any objections or if there are things that I should be considering.

**Comment by alejandrox1** [comment]
@wfernandes please feel free to take it.
I'm only changing ImageWhileList withint test/e2e/framework/pods.go.

**Comment by BenTheElder** [comment]
ultimately was changed to NodePrePullImageList because that's what it's actually used for, not for any sort of filtering.
