### ISSUE TITLE
Make the AWS NLB health check configurable

### ISSUE THREAD

**Issue by kishorj** [kubernetes/kubernetes#92321]
/sig aws
/kind feature
**What would you like to be added**:
Additional  annotations for configuring the AWS NLB health checks
**Why is this needed**:
Currently, the health check for AWS NLB uses default values and not configurable. Support additional service annotations to specify the protocol, path, port for the AWS NLB health checks.

**Comment by TBBle** [comment]
Related currently-open issues: #86624, #82595, #81469 and https://github.com/kubernetes/cloud-provider-aws/issues/51.

**Comment by TBBle** [comment]
As noted in https://github.com/kubernetes/cloud-provider-aws/issues/87#issuecomment-648603010, changing most of these options will require a new `TargetGroup`, and so supporting these will fix in-passing #80996, as changing `externalTrafficPolicy` fails when it implicitly changes these values and the `TargetGroup` is modified. `externalTrafficPolicy` should affect the _defaults_ before the overriding annotations are applied, I guess?

**Comment by TBBle** [comment]
Fix #94546 merged for Kubernetes 1.20.
