### ISSUE TITLE
 "kubectl create -f "failed with normal user

### ISSUE THREAD

**Issue by skycastlelily2** [kubernetes/kubernetes#92334]
**What happened**:
[core@localhost bin]$   mkdir -p $HOME/.kube
[core@localhost bin]$   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
cp: overwrite '/var/home/core/.kube/config'? yes
[core@localhost bin]$   sudo chown $(id -u):$(id -g) $HOME/.kube/config

[core@localhost bin]$  kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
error: error loading config file "/etc/kubernetes/admin.conf": open /etc/kubernetes/admin.conf: permission denied
[core@localhost bin]$ sudo kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**What you expected to happen**:

Shouldn't $HOME/.kube/config be used when run kubectl with normal user?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME=Fedora
VERSION="32.20200615.1.0 (CoreOS)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora CoreOS 32.20200615.1.0"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='32.20200615.1.0'

- Kernel (e.g. `uname -a`):
5.6.18-300.fc32.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
Did you set KUBECONFIG env to point to the admin conf?
If the env is set this path is used instead of home.

**Comment by liggitt** [comment]
The KUBECONFIG envvar isn't propagated to the sudo-run command by default, so the existing kubeconfig filepath is not being honored. To propagate that, do `sudo -E KUBECONFIG ...`

**Comment by liggitt** [comment]
Also, the attempt to copy to the home dir is evaluating $HOME in the current user's context. It is likely $HOME has a different value when running as sudo

**Comment by skycastlelily2** [comment]
> Did you set KUBECONFIG env to point to the admin conf?
> If the env is set this path is used instead of home.

I haven't set KUBECONFIG, I just follow the steps listed in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
and then kubeadm init.
But the value is somehow set to /etc/kubernetes/admin.conf,and kubectl create -f works with normal user works after I unset it.

**Comment by skycastlelily2** [comment]
> Also, the attempt to copy to the home dir is evaluating $HOME in the current user's context. It is >likely $HOME has a different value when running as sudo.
The issue is described as follows,though I didn't know why"The connection to the server localhost:8080 was refused" is shown with sudo one
[core@localhost bin]$ kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
error: error loading config file "/etc/kubernetes/admin.conf": open /etc/kubernetes/admin.conf: permission denied

>To propagate that, do sudo -E KUBECONFIG ...
[core@localhost bin]$ sudo -E KUBECONFIG kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.8/install/kubernetes/quick-install.yaml
sudo: KUBECONFIG: command not found
