### ISSUE TITLE
Remove Mutex Thread locking unlocking from Loggin Format

### ISSUE THREAD

**Issue by rahulchheda** [kubernetes/kubernetes#92346]
**What happened**:

According to this comment, there is no need for mutex thread locking and unlocking In Logging Format.
ref: https://github.com/kubernetes/kubernetes/pull/92177#discussion_r442897848

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by fedebongio** [comment]
/assign @lavalamp 
(just for consistency, the PR is approved already)

**Comment by serathius** [comment]
/close
Mutex was removed.
