### ISSUE TITLE
[Flaky Test] integration-master (ci-kubernetes-integration-master)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#92360]
**Which jobs are failing**:
> integration-master (ci-kubernetes-integration-master)

**Which test(s) are failing**:
>Overall

**Since when has it been failing**:
> 06-21 08:57 PDT

**Testgrid link**:
> https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Reason for failure**:
> test timed out after 2m0s

**Anything else we need to know**:
>=== FAIL: cmd/kubeadm/test/cmd TestCmdInitConfig/can_load_current_component_config (121.49s)
panic: test timed out after 2m0s
goroutine 45 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0x11c
created by time.goFunc
skipped 104 lines unfold_more
	/usr/local/go/src/os/exec/exec.go:311 +0x7b
os/exec.(*Cmd).Start.func1(0xc0002e09a0, 0xc000334cc0)
	/usr/local/go/src/os/exec/exec.go:435 +0x35
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:434 +0xa8e
FAIL	k8s.io/kubernetes/cmd/kubeadm/test/cmd	121.486s
DONE 20 tests, 1 failure in 0.028s
+++ [0621 18:51:44] Saved JUnit XML test report to /logs/artifacts/junit_20200621-184653.xml
make[1]: *** [Makefile:185: test] Error 1

/sig testing
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by hkamel** [comment]
/retitle [Flaky Test] integration-master (ci-kubernetes-integration-master)
/remove-kind failing-test
/kind flake

**Comment by hasheddan** [comment]
Seeing `k8s.io/kubernetes/cmd/kubeadm/test/cmd.TestCmdInitConfig/can_load_current_component_config` spiking significantly (https://testgrid.k8s.io/sig-release-master-blocking#integration-master&&graph-metrics=test-duration-minutes)

**Comment by BenTheElder** [comment]
SIG testing does not own kubeadm
SIG testing owns test tooling, frameworks, CI infra, etc.

**Comment by neolit123** [comment]
> Seeing k8s.io/kubernetes/cmd/kubeadm/test/cmd.TestCmdInitConfig/can_load_current_component_config spiking significantly (https://testgrid.k8s.io/sig-release-master-blocking#integration-master&&graph-metrics=test-duration-minutes)

tracked here:
https://github.com/kubernetes/kubeadm/issues/2197

**Comment by neolit123** [comment]
i cannot reproduce the issue:

> === FAIL: cmd/kubeadm/test/cmd TestCmdInitConfig/can_load_current_component_config (121.49s)
panic: test timed out after 2m0s

```
$ KUBEADM_PATH=/usr/local/bin/kubdm go test ./cmd/kubeadm/test/cmd/... -count=1 -v
=== RUN   TestCmdCompletion
=== RUN   TestCmdCompletion/shell_not_expected
=== RUN   TestCmdCompletion/unsupported_shell_type
--- PASS: TestCmdCompletion (0.20s)
    --- PASS: TestCmdCompletion/shell_not_expected (0.11s)
    --- PASS: TestCmdCompletion/unsupported_shell_type (0.09s)
=== RUN   TestCmdInitToken
=== RUN   TestCmdInitToken/invalid_token_size
=== RUN   TestCmdInitToken/invalid_token_non-lowercase
=== RUN   TestCmdInitToken/valid_token_is_accepted
--- PASS: TestCmdInitToken (6.57s)
    --- PASS: TestCmdInitToken/invalid_token_size (0.08s)
    --- PASS: TestCmdInitToken/invalid_token_non-lowercase (0.09s)
    --- PASS: TestCmdInitToken/valid_token_is_accepted (6.40s)
=== RUN   TestCmdInitKubernetesVersion
=== RUN   TestCmdInitKubernetesVersion/invalid_semantic_version_string_is_detected
=== RUN   TestCmdInitKubernetesVersion/valid_version_is_accepted
--- PASS: TestCmdInitKubernetesVersion (5.48s)
    --- PASS: TestCmdInitKubernetesVersion/invalid_semantic_version_string_is_detected (0.24s)
    --- PASS: TestCmdInitKubernetesVersion/valid_version_is_accepted (5.25s)
=== RUN   TestCmdInitConfig
=== RUN   TestCmdInitConfig/fail_on_non_existing_path
=== RUN   TestCmdInitConfig/can't_load_old_v1alpha1_config
=== RUN   TestCmdInitConfig/can't_load_old_v1alpha2_config
=== RUN   TestCmdInitConfig/can't_load_old_v1alpha3_config
=== RUN   TestCmdInitConfig/can_load_v1beta1_config
=== RUN   TestCmdInitConfig/don't_allow_mixed_arguments_v1beta1
=== RUN   TestCmdInitConfig/can_load_v1beta2_config
=== RUN   TestCmdInitConfig/don't_allow_mixed_arguments_v1beta2
=== RUN   TestCmdInitConfig/can_load_current_component_config
=== RUN   TestCmdInitConfig/can't_load_old_component_config
--- PASS: TestCmdInitConfig (18.24s)
    --- PASS: TestCmdInitConfig/fail_on_non_existing_path (0.09s)
    --- PASS: TestCmdInitConfig/can't_load_old_v1alpha1_config (0.09s)
    --- PASS: TestCmdInitConfig/can't_load_old_v1alpha2_config (0.09s)
    --- PASS: TestCmdInitConfig/can't_load_old_v1alpha3_config (0.10s)
    --- PASS: TestCmdInitConfig/can_load_v1beta1_config (5.25s)
    --- PASS: TestCmdInitConfig/don't_allow_mixed_arguments_v1beta1 (0.23s)
    --- PASS: TestCmdInitConfig/can_load_v1beta2_config (5.71s)
    --- PASS: TestCmdInitConfig/don't_allow_mixed_arguments_v1beta2 (0.22s)
    --- PASS: TestCmdInitConfig/can_load_current_component_config (6.36s)
    --- PASS: TestCmdInitConfig/can't_load_old_component_config (0.11s)
=== RUN   TestCmdInitCertPhaseCSR
=== RUN   TestCmdInitCertPhaseCSR/generate_CSR
=== RUN   TestCmdInitCertPhaseCSR/fails_on_CSR
=== RUN   TestCmdInitCertPhaseCSR/fails_on_all
--- PASS: TestCmdInitCertPhaseCSR (1.22s)
    --- PASS: TestCmdInitCertPhaseCSR/generate_CSR (1.03s)
    --- PASS: TestCmdInitCertPhaseCSR/fails_on_CSR (0.09s)
    --- PASS: TestCmdInitCertPhaseCSR/fails_on_all (0.10s)
=== RUN   TestCmdInitAPIPort
=== RUN   TestCmdInitAPIPort/fail_on_non-string_port
=== RUN   TestCmdInitAPIPort/fail_on_too_large_port_number
=== RUN   TestCmdInitAPIPort/fail_on_negative_port_number
=== RUN   TestCmdInitAPIPort/accept_a_valid_port_number
--- PASS: TestCmdInitAPIPort (7.77s)
    --- PASS: TestCmdInitAPIPort/fail_on_non-string_port (0.11s)
    --- PASS: TestCmdInitAPIPort/fail_on_too_large_port_number (0.92s)
    --- PASS: TestCmdInitAPIPort/fail_on_negative_port_number (0.87s)
    --- PASS: TestCmdInitAPIPort/accept_a_valid_port_number (5.88s)
=== RUN   TestCmdInitFeatureGates
=== RUN   TestCmdInitFeatureGates/no_feature_gates_passed
=== RUN   TestCmdInitFeatureGates/feature_gate_IPv6DualStack=true
=== RUN   TestCmdInitFeatureGates/feature_gate_PublicKeysECDSA=true
--- PASS: TestCmdInitFeatureGates (10.35s)
    --- PASS: TestCmdInitFeatureGates/no_feature_gates_passed (0.09s)
    --- PASS: TestCmdInitFeatureGates/feature_gate_IPv6DualStack=true (6.24s)
    --- PASS: TestCmdInitFeatureGates/feature_gate_PublicKeysECDSA=true (4.02s)
=== RUN   TestCmdJoinConfig
=== RUN   TestCmdJoinConfig/config
=== RUN   TestCmdJoinConfig/config_path
--- PASS: TestCmdJoinConfig (0.32s)
    --- PASS: TestCmdJoinConfig/config (0.16s)
    --- PASS: TestCmdJoinConfig/config_path (0.16s)
=== RUN   TestCmdJoinDiscoveryFile
=== RUN   TestCmdJoinDiscoveryFile/valid_discovery_file
=== RUN   TestCmdJoinDiscoveryFile/invalid_discovery_file
--- PASS: TestCmdJoinDiscoveryFile (0.34s)
    --- PASS: TestCmdJoinDiscoveryFile/valid_discovery_file (0.16s)
    --- PASS: TestCmdJoinDiscoveryFile/invalid_discovery_file (0.18s)
=== RUN   TestCmdJoinDiscoveryToken
=== RUN   TestCmdJoinDiscoveryToken/valid_discovery_token
=== RUN   TestCmdJoinDiscoveryToken/valid_discovery_token_url
--- PASS: TestCmdJoinDiscoveryToken (0.32s)
    --- PASS: TestCmdJoinDiscoveryToken/valid_discovery_token (0.18s)
    --- PASS: TestCmdJoinDiscoveryToken/valid_discovery_token_url (0.15s)
=== RUN   TestCmdJoinNodeName
=== RUN   TestCmdJoinNodeName/valid_node_name
--- PASS: TestCmdJoinNodeName (0.16s)
    --- PASS: TestCmdJoinNodeName/valid_node_name (0.16s)
=== RUN   TestCmdJoinTLSBootstrapToken
=== RUN   TestCmdJoinTLSBootstrapToken/valid_bootstrap_token
=== RUN   TestCmdJoinTLSBootstrapToken/valid_bootstrap_token_url
--- PASS: TestCmdJoinTLSBootstrapToken (0.32s)
    --- PASS: TestCmdJoinTLSBootstrapToken/valid_bootstrap_token (0.16s)
    --- PASS: TestCmdJoinTLSBootstrapToken/valid_bootstrap_token_url (0.16s)
=== RUN   TestCmdJoinToken
=== RUN   TestCmdJoinToken/valid_token
=== RUN   TestCmdJoinToken/valid_token_url
--- PASS: TestCmdJoinToken (0.31s)
    --- PASS: TestCmdJoinToken/valid_token (0.15s)
    --- PASS: TestCmdJoinToken/valid_token_url (0.16s)
=== RUN   TestCmdJoinBadArgs
=== RUN   TestCmdJoinBadArgs/discovery-token_and_discovery-file_can't_both_be_set
=== RUN   TestCmdJoinBadArgs/discovery-token_or_discovery-file_must_be_set
--- PASS: TestCmdJoinBadArgs (0.32s)
    --- PASS: TestCmdJoinBadArgs/discovery-token_and_discovery-file_can't_both_be_set (0.16s)
    --- PASS: TestCmdJoinBadArgs/discovery-token_or_discovery-file_must_be_set (0.16s)
=== RUN   TestCmdJoinArgsMixed
=== RUN   TestCmdJoinArgsMixed/discovery-token_and_config
--- PASS: TestCmdJoinArgsMixed (0.18s)
    --- PASS: TestCmdJoinArgsMixed/discovery-token_and_config (0.18s)
=== RUN   TestCmdTokenGenerate
--- PASS: TestCmdTokenGenerate (0.09s)
=== RUN   TestCmdTokenGenerateTypoError
--- PASS: TestCmdTokenGenerateTypoError (0.09s)
=== RUN   TestCmdTokenDelete
=== RUN   TestCmdTokenDelete/no_token_provided
=== RUN   TestCmdTokenDelete/invalid_token
--- PASS: TestCmdTokenDelete (0.32s)
    --- PASS: TestCmdTokenDelete/no_token_provided (0.16s)
    --- PASS: TestCmdTokenDelete/invalid_token (0.16s)
=== RUN   TestCmdVersion
=== RUN   TestCmdVersion/invalid_output_option
=== RUN   TestCmdVersion/short_output
=== RUN   TestCmdVersion/default_output
--- PASS: TestCmdVersion (0.28s)
    --- PASS: TestCmdVersion/invalid_output_option (0.09s)
    --- PASS: TestCmdVersion/short_output (0.10s)
    --- PASS: TestCmdVersion/default_output (0.09s)
=== RUN   TestCmdVersionOutputJsonOrYaml
=== RUN   TestCmdVersionOutputJsonOrYaml/json_output
=== RUN   TestCmdVersionOutputJsonOrYaml/yaml_output
--- PASS: TestCmdVersionOutputJsonOrYaml (0.17s)
    --- PASS: TestCmdVersionOutputJsonOrYaml/json_output (0.09s)
    --- PASS: TestCmdVersionOutputJsonOrYaml/yaml_output (0.08s)
PASS
ok  	k8s.io/kubernetes/cmd/kubeadm/test/cmd	53.100s

```

the above is tested in a fairly low spec-ed Ubuntu VM.
having these integration tests run for about <60 seconds has always been the case, so if they are failing in the prow jobs, my explanation is slow CPU during the runtime of the tests.

**Comment by neolit123** [comment]
to clarify further, there are no recent changes that increase the runtime of these particular tests.

kubeadm cmd tests can set a custom KUBE_TIMEOUT to more than 2 minutes if that is what the maintainers want to avoid the recent observed decrease in performance in the prow cluster (confirmed by others as well). maybe increasing the timeout to 3 or 4 minutes (that is an threshold increase from 2x to 3x or 4x, based on my local results).

https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-cmd.sh#L130-L132
https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test.sh#L62

@BenTheElder ?
cc @liggitt who also reported the issue in https://github.com/kubernetes/kubernetes/pull/91366

**Comment by BenTheElder** [comment]
we did just change go version? I have no other particular insight. 

the prow cluster cannot guarantee performance when all the jobs are free-for-all CPU and changing that is non-trivial.

I've semi-recently set a minimum default CPU request across the board, which should _reduce_ issues with poor performance.

**Comment by BenTheElder** [comment]
we also have unbounded increased usage of prow via more and more project but the node pool is fixed size ...
we should really get the wg-k8s-infra move prioritized :/

**Comment by neolit123** [comment]
> we did just change go version? 

i tested with 1.14.4 locally.

> kubeadm cmd tests can set a custom KUBE_TIMEOUT to more than 2 minute

should this be done still?

**Comment by BenTheElder** [comment]
I see from your output that about 1/2 of the current timeout is achieved locally on a machine that is probably not under any load, so increasing the timeout SGTM

**Comment by neolit123** [comment]
ack, i will send a PR to increase the timeout.

**Comment by neolit123** [comment]
PR is here:
https://github.com/kubernetes/kubernetes

**Comment by RobertKielty** [comment]
@neolit123 @BenTheElder 

[sig-release-master-blocking#integration-master](https://testgrid.k8s.io/sig-release-master-blocking#integration-master&sort-by-flakiness=&embed=) is still flaking, will a reviewed #92490 resolve the flakiness?

**Comment by neolit123** [comment]
> sig-release-master-blocking#integration-master is still flaking, will a reviewed #92490 resolve the flakiness?

it will not. https://github.com/kubernetes/kubernetes/pull/92490 increases the timeout for `k8s.io/kubernetes/cmd/kubeadm/test/cmd*` tests, but looking at testgrid i don't see any recent flakes for these tests, so closiing https://github.com/kubernetes/kubernetes/pull/92490 is an option too.

the flakiest recent ones are for `k8s.io/kubernetes/test/integration/scheduler*` (sig-scheduling) and `k8s.io/kubernetes/vendor/k8s.io/{apiserver}apiextensions-apiserver}` (sig-apimachinery).

**Comment by RobertKielty** [comment]
@neolit123 Thanks so much for the assist both here and on #920490  I was co-presenting part of the CI-Signal update yesterday, hence the queries.

I'll follow up on with SIGs scheduling and apimachinery

**Comment by hasheddan** [comment]
@RobertKielty do you have a status update here?

**Comment by liggitt** [comment]
> cmd/kubeadm/test/cmd TestCmdInitConfig/can_load_current_component_config

this test has not flaked in over a week

opened https://github.com/kubernetes/kubernetes/issues/93485 specifically for the scheduler test flakes
