### ISSUE TITLE
Pod status ready condition is incorrect

### ISSUE THREAD

**Issue by liuxu623** [kubernetes/kubernetes#92378]
**What happened**:
- kubelet pod status cache ready condition is `true` and node system hangs
- controller-manager update pod status ready condition to `false` because node `NotReady`
- node system recovery and kubelet update node status to `Ready`
- but kubelet doesn't update pod status ready condition to `true`, because cache is `true`

**What you expected to happen**:
kubelet update pod status ready condition to `true` after node recovery

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by VigneshSP94** [comment]
I just did a quick test -

#create a pod
```
[root@localhost .kube]# kubectl run nginx --image=nginx
pod/nginx created
```

#stop kubelet
`[root@localhost .kube]# systemctl stop kubelet`

#check the node status
```
[root@localhost .kube]# kubectl get nodes
NAME                    STATUS     ROLES    AGE   VERSION
localhost.localdomain   NotReady   master   18m   v1.18.1
```

#check the pod status after node goes to NotReady state
```
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   True
  PodScheduled      True
```

#start kubelet
[root@localhost .kube]# systemctl start kubelet

#check the node status, wait for it to become ready.
```
[root@localhost .kube]# kubectl get nodes
NAME                    STATUS   ROLES    AGE   VERSION
localhost.localdomain   Ready    master   20m   v1.18.1
```

#now the pod status goes to True again, I am unable to replicate this.
```
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
```

**Comment by liuxu623** [comment]
@VigneshSP94 I think maybe kubelet loss pod update event, I'm tyring reproduce this.

**Comment by liuxu623** [comment]
I think the problem maybe is `podStatuses` map is updated but patch apiserver pod status failed.

**Comment by tedyu** [comment]
Related: #89155
