### ISSUE TITLE
[Flaky Test] conformance-ga-only (ci-kubernetes-conformance-kind-ga-only)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#92386]
**Which jobs are flaking**:

`[Flaky Test] conformance-ga-only (ci-kubernetes-conformance-kind-ga-only)`

**Which test(s) are flaking**:

`[sig-network] DNS should provide DNS for services [Conformance]`
`[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]`
`[sig-apps] Deployment deployment should delete old replica sets [Conformance]`

Looks like `Overall` is bumping up against its timeout.

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only

**Reason for failure**:

```
[sig-network] DNS should provide DNS for services [Conformance] expand_less | 52s
-- | --
test/e2e/framework/framework.go:597 Jun 22 00:50:22.829: Unexpected error:     <*errors.StatusError \| 0xc0018dc320>: {         ErrStatus: {             TypeMeta: {Kind: "", APIVersion: ""},             ListMeta: {                 SelfLink: "",                 ResourceVersion: "",                 Continue: "",                 RemainingItemCount: nil,             },             Status: "Failure",             Message: "etcdserver: request timed out",             Reason: "",             Details: nil,             Code: 500,         },     }     etcdserver: request timed out occurred test/e2e/network/dns_common.go:587
```

**Anything else we need to know**:

/sig testing
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by BenTheElder** [comment]
Is this really priority critical urgent for two flaked runs?
/sig architecture
/remove-sig testing

**Comment by hasheddan** [comment]
@BenTheElder we can likely bump it down in priority. However, it has been flaking somewhat regularly (every ~8 runs or so) and given that it is a `master-blocking` job I would like to address it sooner rather than later.

/priority important-soon

**Comment by BenTheElder** [comment]
1 in 8 runs is a pretty good pass rate for kubernetes :+)

Not-too long ago we bumped the time on this, because it was simply timing out due to conformance tests getting slower / more tests ...

This job doesn't run frequently enough to have many runs since then.https://github.com/kubernetes/test-infra/pull/18010

**Comment by BenTheElder** [comment]
will bump the CPU req for this job, looks like etcd timeouts.
also looking forward to https://github.com/etcd-io/etcd/pull/11946 whenever etcd. has a release with it and kubernetes catches up ...

**Comment by BenTheElder** [comment]
no flakes since the config tweak, but it only runs twice a day. it is running more tests again (new conformance tests)

**Comment by BenTheElder** [comment]
we could run it more often if necessary.

**Comment by BenTheElder** [comment]
currently failing due to issues with the following tests:

[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance

previously more scheduler tests were broken.

**Comment by RobertKielty** [comment]
These SchedulerPredicates jobs are still flaking

[Sorted by flakiness ](https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only&sort-by-flakiness=)

[sig-scheduling] SchedulerPredicates [Serial] 
 - validates resource limits of pods that are allowed to run [Conformance]
 - validates that NodeSelector is respected if not matching [Conformance]
 - validates that NodeSelector is respected if matching [Conformance]
 - validates that there exists conflict between pods with same hostPort and protocol but one using 0.0.0.0 hostIP [Conformance]
 - validates that there is no conflict between pods with same hostPort but different hostIP and protocol [Conformance]
 - PreemptionExecutionPath runs ReplicaSets to verify preemption running path [Conformance]
 - validates basic preemption works [Conformance]
 -  validates lower priority pod preemption by critical pod [Conformance]

**Comment by RobertKielty** [comment]
This job is now classified as non-flaky.

**Comment by BenTheElder** [comment]
It's been green since the scheduler test fix went in
/close

**Comment by hasheddan** [comment]
Thanks @BenTheElder !
