### ISSUE TITLE
Run Scheduler integration benchmarks as kubemark benchmarks

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#92388]
We have a number of benchmarks set up as [integration tests](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/config/performance-config.yaml). Those benchmarks are valuable for development since one can run them locally. 

We also have benchmarks running on full (e.g., gce-5000Nodes) and kubemark (e.g., kubemark-5000Nodes) clusters continuously and the results are tracked on the [perf-dash](http://perf-dash.k8s.io/#/?jobname=kubemark-500Nodes&metriccategoryname=Scheduler&metricname=SchedulingThroughput) dashboard maintained by the scalability sig. Those benchmarks run for various cluster sizes but for the same vanilla workload.

What we want is to have some of the benchmarks we developed in integration tests to run as part of the perf-dash set. Specifically, we can start with the following ones as kubemark benchmarks (full clusters are expensive to setup, so kubemark is less expensive but should be good enough for now):

- SchedulingPodAntiAffinity
- SchedulingPodAffinity
- SchedulingPreferredPodAffinity
- SchedulingPreferredPodAntiAffinity
- SchedulingNodeAffinity
- TopologySpreading
- PreferredTopologySpreading
- MixedSchedulingBasePod

/sig scheduling
/assign @adtac

**Comment by ahg-g** [comment]
the code is in the following repo: https://github.com/kubernetes/perf-tests/

**Comment by Huang-Wei** [comment]
I recalled we used to have those metrics in perf-dash, but maybe it's somehow removed.

**Comment by ahg-g** [comment]
The one you are referring to where the integration tests themselves.

I am suggesting we translate some of the integration test benchmarks to kubemark ones, which is a lot more realistic.

**Comment by Huang-Wei** [comment]
I see the point. Need to check kubemark is using prometheus or golang benchmark metric in the output, and hopefully we can adapt current scheduler perf tests properly without too much burden.

**Comment by hprateek43** [comment]
The goal is to have these benchmarks for the local developer, or we plan to track these benchmarks against the master branch ?

**Comment by adtac** [comment]
>The goal is to have these benchmarks for the local developer, or we plan to track these benchmarks against the master branch ?

I believe the primary focus is on the latter. However, you should be able to run the benchmarks locally as well.

**Comment by ahg-g** [comment]
/remove-lifecycle stale

@adtac I am guessing this is mostly done?

**Comment by adtac** [comment]
6/8 are done. Mixed scheduling and Node affinity aren't.

**Comment by adtac** [comment]
The most relevant benchmarks have all been added -- in the past couple of months, we haven't felt a need for any additional workloads on top of what we have right now. Closing.

/close
