### ISSUE TITLE
imagePullPolicy does not default to Always for :latest images with ephemeral containers

### ISSUE THREAD

**Issue by ecourreges-orange** [kubernetes/kubernetes#92383]
**What happened**:
`kubectl alpha debug` reused my previous `:latest` image that is not pullable anymore.
**What you expected to happen**:
`kubectl alpha debug` to always pull the latest `:latest` image.  
As per documentation [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ephemeralcontainer-v1-core), excerpt:
```
imagePullPolicystring | Image  pull policy. 
One of Always, Never, IfNotPresent. 
Defaults to Always if  :latest tag is specified, or IfNotPresent otherwise. 
Cannot be updated.  
More info:  https://kubernetes.io/docs/concepts/containers/images#updating-images
```
**How to reproduce it (as minimally and precisely as possible)**:
Have a simple Dockerfile with ENTRYPOINT ["/bin/bash"]
```
docker build my_image .
docker push my_image:latest
kubectl alpha debug -ti my_pod --image=my_image:latest --target=my_container
```
And then, change one line in your image,
```
docker build my_image .
docker push my_image:latest
kubectl alpha debug -ti my_pod --image=my_image:latest --target=my_container
kubectl describe pod my_pod
```
You will see that both images have the same sha256 (the first one built) and the Events in will show that it did not pull the image:
`Normal  Pulled   20m   kubelet, node005  Container image "my_image:latest" already present on machine
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

Regards,
Thank you for your time.

**Comment by wawa0210** [comment]
From the code 

https://github.com/kubernetes/kubernetes/blob/8815a1da595ff9d2d381559ef43fe989332d9cf9/staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go#L126

The default value of the image pull is `PullIfNotPresent`. Perhaps it is better to set the image pull strategy according to the properties of the image. I will submit a pr later, try

**Comment by verb** [comment]
@wawa0210 Are you still working on this issue? Do you need any help?

**Comment by wawa0210** [comment]
> @wawa0210 Are you still working on this issue? Do you need any help?

No problem, I will submit a pr tomorrow
