### ISSUE TITLE
storage transformer plugin envelope enable remote KMS plugin

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#92406]
**What would you like to be added**:

For now, storage transformer plugin [envelope](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service.go) can only work with a localhost KMS plugin. 
We want to deploy the KMS plugin as a remote service on several SGX node(s) to ensure the memory safety, then storage transformer plugin envelope should enable invoke remote KMS plugin service.

Is there any reasons that KMS plugin must be as a local service instead of a remote service? If not, I would like to post a PR to enable this feature.

**Why is this needed**:

KMS plugin may be deployed as a remote service on several SGX node(s), SGX node does not meet API Server performance requirement, so that API Server and KMS plugin are independent deployment and run on different nodes. In this scene, storage transformer plugin envelope should enable to use remote gRPC with TLS(or other auth methods) to call remote KMS plugin.

**Comment by answer1991** [comment]
@mikedanese @liggitt 

kindly ping, any comments?

**Comment by gaorong** [comment]
This would be a great helpful feature not only for performance but also for high-availability, https://github.com/kubernetes/kubernetes/issues/90159 also have some discussion related to this issue from high-availability perspective.
