### ISSUE TITLE
fix staticcheck failures

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#92402]
Many of our packages are failing [staticcheck], we should fix all of them. See previously https://github.com/kubernetes/kubernetes/issues/36858 https://github.com/kubernetes/kubernetes/issues/90208 https://github.com/kubernetes/kubernetes/issues/81657

/help

To fix these, take a look at [hack/.staticcheck_failures] for a list of currently failing packages.

You can check a package by removing it from the list and running `make verify WHAT=staticcheck`.
Once the package is no longer failing, please file a PR including the fixes and removing it from the list.

Before filing your PR, you should run `hack/update-gofmt.sh` and `hack/update-bazel.sh` to auto format your code and update the build.

I recommend keeping PRs scoped down in size for review, fix a package or set of closely related packages, or a certain class of failures, to make it easier for your reviewers to handle. 

We don't need to fix all failures in one PR, but please avoid 100s of single character PRs, as it does cost time & resources to get each PR reviewed, tested, merged etc. :upside_down_face: 

I can help review _some_ of these, but many of them will require other reviewers that own the relevant code.

EDIT: I also don't recommend `/assign` ing to this one, many people are going to need to work on it and we want more people to join in.
You can link to this issue in your PR and comment here that you're working on certain packages to help avoid duplication.
EDIT2: Please do NOT put `Fixes #...` in your Pull Request, despite the template. That will close this PR. Instead put something like `Part of #92402`

I think each of these own code that is currently failing:
/sig testing
/sig storage
/sig api-machinery
/sig architecture
/sig cli
/sig instrumentation
/sig autoscaling
/sig cloud-provider

[staticcheck]: https://staticcheck.io/
[hack/.staticcheck_failures]: https://github.com/kubernetes/kubernetes/blob/master/hack/.staticcheck_failures

**Comment by skilxn-go** [comment]
Sorry, didn't notice this before.

> EDIT: I also don't recommend /assign ing to this one, many people are going to need to work on it and we want more people to join in.

**Comment by BenTheElder** [comment]
thanks :-)
yeah, I think people tend to not work on issues that are already assigned, but I don't think anyone one person is going to get PRs in for all of this, there's lots of room for many to work on this :-)

**Comment by BenTheElder** [comment]
/lifecycle active
I opened a simple one for a package I own, https://github.com/kubernetes/kubernetes/pull/92408
In this case we only use the type in a special compilation mode, so we can just ignore the warning. It's not the best example PR, but it does take care of `pkg/util/coverage`.

**Comment by xiaopeng-han** [comment]
good

**Comment by dims** [comment]
updating to golang 1.14 yielded a bunch more of staticcheck issues:
https://github.com/kubernetes/kubernetes/pull/92438/files#diff-a96dcfd21feac9b3c56dab4636566c5bR10-R17

**Comment by lala123912** [comment]
I'm a new contributor, may I have a try?

**Comment by dims** [comment]
@lala123912 please do

**Comment by SaiHarshaK** [comment]
I would like to work on the vendor/k8s.io/kubectl pkg related ones from the list.

**Comment by obeyda** [comment]
Hello, I tried to narrow down the list of packages without active PRs as of now, hope this is useful for anyone who wants to contribute: 
```
test/integration/scheduler_perf
vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation
vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy
vendor/k8s.io/apimachinery/pkg/util/net
vendor/k8s.io/apimachinery/pkg/util/sets/types
vendor/k8s.io/apimachinery/pkg/util/strategicpatch
vendor/k8s.io/apimachinery/pkg/util/wait
vendor/k8s.io/apiserver/pkg/admission/initializer
vendor/k8s.io/apiserver/pkg/authentication/request/x509
vendor/k8s.io/apiserver/pkg/endpoints
vendor/k8s.io/apiserver/pkg/endpoints/handlers
vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager
vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters
vendor/k8s.io/apiserver/pkg/endpoints/request
vendor/k8s.io/apiserver/pkg/registry/generic/registry
vendor/k8s.io/apiserver/pkg/registry/generic/rest
vendor/k8s.io/apiserver/pkg/registry/rest/resttest
vendor/k8s.io/apiserver/pkg/server
vendor/k8s.io/apiserver/pkg/server/dynamiccertificates
vendor/k8s.io/apiserver/pkg/server/filters
vendor/k8s.io/apiserver/pkg/server/httplog
vendor/k8s.io/apiserver/pkg/server/options
vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig
vendor/k8s.io/apiserver/pkg/server/routes
vendor/k8s.io/apiserver/pkg/server/storage
vendor/k8s.io/apiserver/pkg/storage
vendor/k8s.io/apiserver/pkg/storage/cacher
vendor/k8s.io/apiserver/pkg/storage/etcd3
vendor/k8s.io/apiserver/pkg/storage/tests
vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope
vendor/k8s.io/apiserver/pkg/util/webhook
vendor/k8s.io/apiserver/pkg/util/wsstream
vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc
vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook
vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook
vendor/k8s.io/client-go/rest
vendor/k8s.io/client-go/rest/watch
vendor/k8s.io/client-go/transport
```

**Comment by leilajal** [comment]
@obeyda do we have separate issues for above packages or are they all assigned here?

**Comment by obeyda** [comment]
@leilajal Only one issue, but as noted by @BenTheElder: 
> EDIT: I also don't recommend `/assign` ing to this one, many people are going to need to work on it and we want more people to join in.
> You can link to this issue in your PR and comment here that you're working on certain packages to help avoid duplication.
> EDIT2: Please do NOT put `Fixes #...` in your Pull Request, despite the template. That will close this PR. Instead put something like `Part of #92402`

**Comment by obeyda** [comment]
pull request #95683 submitted with fixes for these paths:

- vendor/k8s.io/apiserver/pkg/storage
- vendor/k8s.io/apiserver/pkg/storage/cacher
- vendor/k8s.io/apiserver/pkg/storage/etcd3
- vendor/k8s.io/apiserver/pkg/storage/tests
- vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope
- vendor/k8s.io/apiserver/pkg/util/webhook
- vendor/k8s.io/apiserver/pkg/util/wsstream

**Comment by ramnar** [comment]
@obeyda - Can you list the packages left which needs fix? I can take up some

**Comment by obeyda** [comment]
@ramnar, that would be [this](https://github.com/kubernetes/kubernetes/issues/92402#issuecomment-710667915) minus these packages: `vendor/k8s.io/apiserver/pkg/{storage, util, authenticator, authorizer}`

as mentioned in previous comments, if you're working on a package it's better to mention that in the comments to avoid duplication.

**Comment by almas33** [comment]
Hello I am new here is this  what i should do for eg :-

in
> vendor/k8s.io/client-go/discovery

`groupVersions := metav1.ExtractGroupVersions(apiGroupList)
	if !reflect.DeepEqual(groupVersions, []string{"v1", "extensions/v1beta1"}) {
		t.Errorf("expected: %q, got: %q", []string{"v1", "extensions/v1beta1"}, groupVersions)
	}`

change to:-

`if groupVersions := metav1.ExtractGroupVersions(apiGroupList) ; 
   !reflect.DeepEqual(groupVersions, []string{"v1", "extensions/v1beta1"}) {
		t.Errorf("expected: %q, got: %q", []string{"v1", "extensions/v1beta1"}, groupVersions)
	}`

as groupVersions is only used inside 'if' statement in this function

**Comment by BenTheElder** [comment]
that sounds like a potentially reasonable change.

aside: client-go sources are actually in `staging/` canonically, `vendor/` is a symlink to allow other parts of the repo to import it for :reasons:

**Comment by almas33** [comment]
should I do that in `staging/`

**Comment by almas33** [comment]
Hi @BenTheElder I saw 3 declarations like that and corrected it ,unused variable declarations looks good; what else do I need to check

**Comment by BenTheElder** [comment]
hi @almas33, sorry I didn't see this. please consider joining slack.k8s.io and discussing development in #kubernetes-contributors or similar, this issue is not a very good place to discuss individual changes and people are more available for live help there.

**Comment by lauchokyip** [comment]
If anyone wants to do `vendor/k8s.io/apiserver/pkg/server/httplog ` please go ahead and submit a PR 👍🏼  You can refer to this PR (https://github.com/kubernetes/kubernetes/pull/97867)

**Comment by BenTheElder** [comment]
[lots of PRs going on, unassigning it so people searching for available issues will find this / it's not accurate to assign one person 😅 ]

**Comment by tiloso** [comment]
We're close to resolving this issue - all remaining packages in [hack/.staticcheck_failures](https://github.com/kubernetes/kubernetes/blob/master/hack/.staticcheck_failures) are covered by PRs. :slightly_smiling_face: 
```
vendor/k8s.io/apiserver/pkg/server/dynamiccertificates      99572, 102899
vendor/k8s.io/apiserver/pkg/server/filters                  99572, 102899
vendor/k8s.io/apiserver/pkg/server/routes                   102899
vendor/k8s.io/apiserver/pkg/storage                         100771
vendor/k8s.io/apiserver/pkg/storage/cacher                  103023
vendor/k8s.io/apiserver/pkg/storage/tests                   103023
vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope  103023
vendor/k8s.io/apiserver/pkg/util/wsstream                   102629
vendor/k8s.io/client-go/rest                                99142
vendor/k8s.io/client-go/rest/watch                          103023
```

**Comment by m-Bilal** [comment]
Hi @tiloso @BenTheElder, can I take the remaining part of this up?

**Comment by lauchokyip** [comment]
@m-Bilal Yes! go ahead as @tiloso mentioned, there is still  `vendor/k8s.io/apiserver/pkg/util/wsstream ` needed to be fixed

**Comment by BenTheElder** [comment]
Yes please do!

**Comment by pacoxu** [comment]
After upgrading to staticcheck v0.2.0, there are several more static failures. New contributors may take a look.

**Comment by sanya301** [comment]
Hi! I am new to the community and would like to help out with anything remaining here. Is anyone still working on this?

**Comment by mourya007** [comment]
@BenTheElder Hello ! I would like to help in this, Is there any current failure which is not taken by anyone.?

**Comment by tiloso** [comment]
Hey @sanya301 and @mourya007! At the moment, all remaining failures are covered by PRs.

**Comment by pacoxu** [comment]
Since #106448 was merged, search `//nolint:staticcheck` for stackcheck failures. 

We should close this issue, or update the way to follow this up.
