### ISSUE TITLE
Kube api server timed out for webhook configuration

### ISSUE THREAD

**Issue by ragunathan23** [kubernetes/kubernetes#92411]
**What happened**:
Kube api server timed out when injecting webhook configuration with following error:

dispatcher.go:181] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling webhook "sidecar-injector.istio.io": Post https://istiod.istio-system.svc:443/inject?timeout=30s: context deadline exceeded

**What you expected to happen**:
The kube api server webhook request should succeed and the sidecar should attach to the pod.  

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Kubernetes with 1 master and 2 worker node on Centos 7 vm
2. Install istio 1.5.2 or 1.6.3
3. Create a pod, istio side car will watch for event "CREATE" and trigger the webhook

**Anything else we need to know?**:
1. Tried curl from other pod running in the same cluster and the request goes through. The curl was requested with --insecure flag
 curl -X POST https://istiod.istio-system.svc:443/inject?timeout=30s --insecure

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.1
- Cloud provider or hardware configuration: on-premise, 32GB RAM, 16 core CPU
- OS (e.g: `cat /etc/os-release`): Centos 7 VM
- Kernel (e.g. `uname -a`): 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Manually
- Network plugin and version (if this is a network-related bug): Flannel CNI
- Others: All webhook requests failed not only for Istio 1.5.2 or 1.6.3. Tried other services which contains webhook also failed.

NOTE: There is no firewall is running in the cluster.

**Comment by ragunathan23** [comment]
Any help, much appreciated!

**Comment by cheftako** [comment]
@ragunathan23 Could you provide the output for the following commands?
kubectl get mutatingwebhookconfiguration sidecar-injector.istio.io -o yaml
kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml
kubectl -n istio-system get endpoints istio-sidecar-injector -o yaml

**Comment by ragunathan23** [comment]
@cheftako Please find the output for the respective commands:
1. kubectl get mutatingwebhookconfiguration sidecar-injector.istio.io -o yaml
Error from server (NotFound): mutatingwebhookconfigurations.admissionregistration.k8s.io "sidecar-injector.istio.io" not found

2. kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app":"sidecar-injector","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.3","release":"istio"},"name":"istio-sidecar-injector"},"webhooks":[{"clientConfig":{"caBundle":"","service":{"name":"istiod","namespace":"istio-system","path":"/inject"}},"failurePolicy":"Fail","name":"sidecar-injector.istio.io","namespaceSelector":{"matchLabels":{"istio-injection":"enabled"}},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}],"sideEffects":"None"}]}
  creationTimestamp: "2020-06-23T05:38:44Z"
  generation: 2
  labels:
    app: sidecar-injector
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.3
    release: istio
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:install.operator.istio.io/owning-resource: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
          f:release: {}
      f:webhooks:
        .: {}
        k:{"name":"sidecar-injector.istio.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:path: {}
              f:port: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector:
            .: {}
            f:matchLabels:
              .: {}
              f:istio-injection: {}
          f:objectSelector: {}
          f:reinvocationPolicy: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: istioctl
    operation: Update
    time: "2020-06-23T05:38:44Z"
  - apiVersion: admissionregistration.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:webhooks:
        k:{"name":"sidecar-injector.istio.io"}:
          f:clientConfig:
            f:caBundle: {}
    manager: pilot-discovery
    operation: Update
    time: "2020-06-23T05:38:47Z"
  name: istio-sidecar-injector
  resourceVersion: "2320802"
  selfLink: /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/istio-sidecar-injector
  uid: b0835eef-c83d-44c7-b78c-a97af0676df9
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzVENDQWNXZ0F3SUJBZ0lRR3FsNElCbjJ0TDFjNTZqSlErblVpVEFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJd01EWXlNekExTVRVek9Gb1hEVE13TURZeQpNVEExTVRVek9Gb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKTlB5MUwralhybjhjclFldGNWVU1SdkVEd2REakJnUmZHSC9mZ0cKTGRreUdSTTBNYnlJQVJPN0IrVURLQXdPeDlZeEI1UzE5NzJWZU9oVFJkQkEweldVdU9IcDBkKzVseHRCRC9yYgpQSGQ4eXE3dkszTFc0Wm1KSjdVMklhSjhiN3FLMk1lUGxkTjUzRDJjSUlENkx5dy83RWlKYk9oSDNTU2ZNVlNBCkpBR0lCZ3FFSWcyR0hXUDdhMXNCQ2RqREplRG1Dd3FNTUpVeU5XRzZmamFJK2R3SHo4bkI1aWt2SW5INHdtUkoKWVVhRHVjcHRrTldwS2J3WE10OGpndStSeUpSU2pjK2dKZWswWWJ0TG0vWStZS2JlN2RiYWowNHI0YnhPUFZrSAp1TzBjazNHOHpKMkliamxKaGFXQzl3NVQwdXo1NHhkaU5XRjdHV2t1eU1FaVJ3a0NBd0VBQWFNak1DRXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUg4a3FtMHFiZXA0dDJnRS82ZnQrZmRPRkwvMWVGT09rU05VQXp1SDBVMlBhTTRrQWdyRWk5enpnRUZML3Y2eQo1L1V5dll0K1VwM3B2L01VeWNZYVlqVmV2QjJGU0lyMUM3OEJuYjgyUFp3N1hwYlFKVTFrSU80Ri9PRDVIYVpnCnlPOGhnekx1d0VUcGQ0Nm00MU90bDc0WXkzYU5rWFpKZmhZbjNxK05mNDBLODNGUGxpV0tXRFQ1RkVLQ2s5L0sKM1Q0Y1FNeXVZWlVJSmgxRVZmRjZoMytWUWFOQVNwemlXUHFEeVBxYzFtK2dPeFdWVkZxaklkTlpIOEVUWVdDUApYUVZJUU9kZTJtWm5VZ0Joek92RndDb1dtVFQ2THh0Qm1jTGFHWW96Y2tqb3dDenYzVjF2Sk5HWmp3SktKejRVClUvTEFBRHorSmg3UDFiTlFoNHRxY29JPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30

3. kubectl -n istio-system get endpoints istio-sidecar-injector -o yaml
Error from server (NotFound): endpoints "istio-sidecar-injector" not found

**Comment by ragunathan23** [comment]
@cheftako one more observation. Today I deployed one custom metric for HPA purpose and the metrics were served over HTTPS. Kube API server started throwing the following error which is similar to the above-mentioned problem. 

v1beta1.custom.metrics.k8s.io failed with: failing or missing response from https://10.97.179.122:443/apis/custom.metrics.k8s.io/v1beta1: Get https://10.97.179.122:443/apis/custom.metrics.k8s.io/v1beta1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Interestingly after I added **hostNetwork: true** under the pod spec, the error went away and the Kube API server was able to talk to the service. Why is this? 

I have been stuck with this problem for more than a week and since the Kubernetes been deployed in on-prem with Centos 7 there isn't enough help out there. Kindly requesting your help to figure this out.

**Comment by cheftako** [comment]
Couple quick things. 1) "failurePolicy":"Fail" This means any problem, such as the istio service being unavailable will cause the webhook to refuse the incoming request. 2) rules: operations:["CREATE"],"resources":["pods"] means you will only get requests to create pods. However if that pod is for instance the pods need to serve the webhook or your metric server, then it won't get created. Have to jump on a call. If you want a quick resolution I would delete the webhook and see if that fixes it. Otherwise I will be back later with more debugging suggestions.

**Comment by ragunathan23** [comment]
I am not sure whether we can delete the webhook as they might impact the
functionality of ISTIO. As I mentioned earlier with respect to metric
server which doesn't have any webhook also failing with connect timed out
exception. But after I changed the pod spec of the metric server with
hostNetwork: true, it started working.
Also I mentioned the pod network and kube api server are in different
subnet. Could that be the reason?

**Comment by ragunathan23** [comment]
@cheftako we can get on a call, let me know your availability. I am in the IST timezone.

**Comment by cheftako** [comment]
I'm cheftako on Kubernetes slack. Feel free to reach out and we can arrange some time. I'm Pacific time

**Comment by ragunathan23** [comment]
@cheftako it's a flannel issue. For now able to fix the issue by changing the flannel backend to host-gw from vxlan. Not sure why it didn't work with vxlan. Thanks for @nustiueudinastea (Alex) for debugging the issue.
