### ISSUE TITLE
CpuManagerPolicy static doesn't work with pods that run to completion on k8s 1.18

### ISSUE THREAD

**Issue by robertdavidsmith** [kubernetes/kubernetes#92436]
**What happened**:
I built a small cluster with cpuManagerPolicy static.

I submitted a test k8s job with parallelism 80 (80 is more than there are cores on my cluster). The test job just returns a non-zero exit code.

Some pods ended in state Error as expected but others failed with UnexpectedAdmissionError.
~~~~
kubectl get pods
NAME          READY   STATUS                     RESTARTS   AGE
nginx-6h7dr   0/1     Error                      0          5m14s
nginx-8pjs8   0/1     Error                      0          5m14s
nginx-9lbzz   0/1     Error                      0          5m14s
nginx-9s7jw   0/1     UnexpectedAdmissionError   0          5m1s
nginx-b42g4   0/1     UnexpectedAdmissionError   0          5m14s
nginx-b4bfb   0/1     UnexpectedAdmissionError   0          5m13s
nginx-cp9gq   0/1     UnexpectedAdmissionError   0          5m
nginx-fbv69   0/1     Error                      0          5m14s
~~~~

Describing one pod gives more info:

~~~~
kubectl describe pod nginx-b42g4
Name:           nginx-b42g4
...
Status:         Failed
Reason:         UnexpectedAdmissionError
Message:        Pod Allocate failed due to not enough cpus available to satisfy request, which is unexpected
IP:
IPs:            <none>
Controlled By:  Job/nginx
...
Events:
  Type     Reason                    Age        From                                                Message
  ----     ------                    ----       ----                                                -------
  Warning  FailedScheduling          <unknown>  default-scheduler                                   0/6 nodes are available: 6 Insufficient cpu.
  Warning  FailedScheduling          <unknown>  default-scheduler                                   0/6 nodes are available: 6 Insufficient cpu.
  Normal   Scheduled                 <unknown>  default-scheduler                                   Successfully assigned default/nginx-b42g4 to robertstest-node2.ospr-k8s-d.vgis.c3.zone
  Warning  UnexpectedAdmissionError  18m        kubelet, robertstest-node2.ospr-k8s-d.vgis.c3.zone  Allocate failed due to not enough cpus available to satisfy request, which is unexpected
~~~~

If you modify the pod to return 0 you get a mix of UnexpectedAdmissionError and Completed pod statuses.

**What you expected to happen**:
If the job returns non-zero all pods should end with status Error.
If the job returns zero all pods should end with status Completed.

**How to reproduce it (as minimally and precisely as possible)**:
Build a v1.18.0 cluster including the below in kubelet config
~~~~
cpuManagerPolicy: "static"
reservedSystemCPUs: "0"
~~~~

kubectl apply this file:
~~~~
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx
spec:
  parallelism: 80
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        command: ["/bin/ls",  "/do_not_exist_directory"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "1"
          limits:
            memory: "32Mi"
            cpu: "1"
      restartPolicy: Never
~~~~
(this file was copied from https://github.com/kubernetes/kubernetes/issues/79159)

**Anything else we need to know?**:
This is a variation on issue https://github.com/kubernetes/kubernetes/issues/79159

I have reproduced issue https://github.com/kubernetes/kubernetes/issues/79159 with k8s 1.17.5.

However with 1.18.0 or 1.18.3 the behaviour is different from that described in https://github.com/kubernetes/kubernetes/issues/79159 in two ways
- With 1.18, the problem happens regardless of whether the pods return 0.
- With 1.17.5 you get a PreStartHookError. With 1.18 you get a UnexpectedAdmissionError with the same error message.

**Environment**:
- Kubernetes version (use `kubectl version`):
~~~~
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
~~~~
- Cloud provider or hardware configuration: On prem OpenStack. 3x c2.m4 VMs for masters. 3x c4.m8 VMs for nodes.
- OS (e.g: `cat /etc/os-release`):
~~~~
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2345.3.1
VERSION_ID=2345.3.1
BUILD_ID=2020-03-26-2026
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2345.3.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
~~~~
- Kernel (e.g. `uname -a`): Linux 4.19.107-flatcar #1 SMP Thu Mar 26 19:48:36 -00 2020 x86_64 Intel Xeon Processor (Skylake, IBRS) GenuineIntel GNU/Linux
- Install tools: Custom terraform
- Network plugin and version (if this is a network-related bug):
- Others: Docker version 18.06.3-ce

**Comment by jgiannuzzi** [comment]
This is my understanding of what happens in v1.18.x:
* the job creates as many pods as requested by the parallelism parameter (all of them `Pending`)
* a number of pods will get scheduled based on the allocatable CPUs in the system (they become `ContainerCreating`)
* these pods go through the static CPU manager to get an exclusive CPU allocated to them, eventually making the assignable CPU set shrink to zero
* whenever one of these pods is done (whether it completed successfully or failed), its assigned exclusive CPU does not get released until the CPU manager tries to reconcile the state (this can be exacerbated by setting `cpuManagerReconcilePeriod` to something higher than the 10s default, like 1m)
* the next pod is then scheduled as there are allocatable CPUs in the system, but the static CPU manager will not have any assignable CPU available in the set, which ends up in an `UnexpectedAdmissionError`

Setting a topology manager policy to anything other than `none` (i.e. `best-effort`) will force the CPU manager to remove its stale state when admitting a new pod, which prevents this issue from happening.

Changing the CPU manager's `Allocate` function to call `removeStaleState` before anything else also prevents this issue from happening, but I am not sure if there is any downside to doing that? If not, I am happy to create a PR with that change.

---

In v1.17.x, there is an important difference, which is that `removeStaleState` was so conservative that even calling it before admitting a new pod is not enough to prevent the issue from happening. I guess we shouldn't try to fix it below v1.18.x.

**Comment by jgiannuzzi** [comment]
Update: I just found that this exact solution (calling `removeStaleState` at the start of the CPU manager's `Allocate` function) was implemented in ab5870d808ed, which made it into v1.19.0-alpha.3.

So in summary, this issue can be fixed by either running v1.18.x with a topology manager policy, or by upgrading to v1.19-beta.2.

**Comment by jgiannuzzi** [comment]
(Final) update: this fix also made it into v1.18.4 (#90377). You can thus upgrade to that release without even setting a topology manager policy 🎉

**Comment by jgiannuzzi** [comment]
@robertdavidsmith I think this issue can be closed

**Comment by robertdavidsmith** [comment]
Many thanks Jonathan!
