### ISSUE TITLE
coreos/azure: accessing services from the outside world

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#9244]
As @srakesh28 pointed out (https://github.com/GoogleCloudPlatform/kubernetes/pull/9060#issuecomment-108642690), it's currently not possible to access service [as documented](https://github.com/GoogleCloudPlatform/kubernetes/blob/a161edb3960c01ff6e14813858c2eeb85910009b/docs/getting-started-guides/coreos/azure/README.md#exposing-the-app-to-the-outside-world). I am certain it works a few releases ago, like 0.11 or somewhere there.

**Comment by srakesh28** [comment]
azure login did not work for me, I provided my azure subscription user id and password and below is error I get 
info: Executing command login
warn: Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Password: ***********

Authenticating... error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE info: Error information has been recorded to /home/xxxxxx/.azure/azure.err error: login command failed
so I tried out 
azure account import --> to download publish file go to https://manage.windowsazure.com/publishsettings (Login from browser and it will download it)

azure account set <"name of your subscription"> --> Name can be found in publishsetting files or from Portal
This worked to proceed to next steps.

**Comment by srakesh28** [comment]
I don't see anything running in containers as deamon for example guestbook appln, so Endpoint can't connect to services in backed.

**Comment by errordeveloper** [comment]
If you do `kubectl get services` you will get IP/port for the services there are, which you should be able to test from any of the nodes other then master. That would certainly allow you to verify that the cluster is working, however you would still need some way of making these accessible from the outside world, which I'm not quite sure about at this stage, hopefully someone else will shine a light on it.

**Comment by errordeveloper** [comment]
#11450
