### ISSUE TITLE
Pre-assumed volumes are not checked to see if they are actually bound

### ISSUE THREAD

**Issue by mrkm4ntr** [kubernetes/kubernetes#92458]
I was reading codes around volume binding plugin, I found that pre-assumed volumes are not checked to see if they are actually bound. 

For example,
1. Pod A has PVC A and assumes it will be bound to PV A.
2. Pod B also has PVC A and consider it is bound to PV A because it is pre-assumed by Pod A.
3. Scheduler fails to schedule Pod A and revert assumed PVC A.
4. In scheduling cycle of pod B, there is no check that PVC A is actually bound to PV A. Then pod B is scheduled, but PVC A is not bound actually.

**Comment by mrkm4ntr** [comment]
@cofyc Is my understanding correct? If so, I'd like to fix this using permit extension point.

**Comment by cofyc** [comment]
I guess pod B should not be scheduled as PVC A does not pass this check here until it's fully bound by the PV controller. 

```
https://github.com/kubernetes/kubernetes/blob/b67e7d6e2cacb1af3b4f366531166dfe71c2866a/pkg/controller/volume/scheduling/scheduler_binder.go#L675-L677
```

a binding goroutine will be started for pod B too and fails when "Scheduler fails to schedule Pod A and revert assumed PVC A".

**Comment by mrkm4ntr** [comment]
I think the PVCs passed to `isPVCFullyBound` are cached PVCs or APIPVCs that assumed in this scheduling cycle (matchedBindings and provisionedClaims below).  
https://github.com/kubernetes/kubernetes/blob/b67e7d6e2cacb1af3b4f366531166dfe71c2866a/pkg/controller/volume/scheduling/scheduler_binder.go#L257
So, I think pre-assumed PVCs are not checked.

**Comment by cofyc** [comment]
no

- for static binding, we didn't assume PVC (we pre-bind the PV and wait for the PV controller to bind it with the PVC)
- for dynamic binding, we just set the `selected-node` in the PVC annotation

**Comment by mrkm4ntr** [comment]
Ah, I see. Assumed but not bound PVC has only annotation, but not `Spec.volumeName`. The PV controller set it.  
Thanks!

**Comment by cofyc** [comment]
yes, the scheduler (volume binding) just trigger the binding process

**Comment by mrkm4ntr** [comment]
Thank you! I clearly understood.
