### ISSUE TITLE
[Flaky Test] [sig-cli] Kubectl client Kubectl logs should be able to retrieve and filter logs [Conformance]

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#92468]
**Which jobs are flaking**:

`skew-cluster-latest-kubectl-stable1-gce (ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew)`

**Which test(s) are flaking**:

`[sig-cli] Kubectl client Kubectl logs should be able to retrieve and filter logs [Conformance]`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#skew-cluster-latest-kubectl-stable1-gce

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:721
Jun 24 13:50:35.009: Expected
    <int>: 2
to equal
    <int>: 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1410
```

**Anything else we need to know**:

/sig cli
/cc @kubernetes/ci-signal
/priority important-soon
/milestone v1.19

**Comment by soltysh** [comment]
I haven't noticed this being an issue for over a week now, I'm dropping the 1.19 milestone for it to unblock the release.
/milestone clear

**Comment by hasheddan** [comment]
Noticed this again today (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew/1288434386735206402)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:721
Jul 29 11:30:39.509: expected recent(6) to be less than older(6)
recent lines:
I0729 11:30:34.559283       1 logs_generator.go:76] 86 POST /api/v1/namespaces/kube-system/pods/ppxw 313
I0729 11:30:34.761470       1 logs_generator.go:76] 87 GET /api/v1/namespaces/default/pods/5jl 271
I0729 11:30:34.959287       1 logs_generator.go:76] 88 PUT /api/v1/namespaces/kube-system/pods/tpb7 505
I0729 11:30:35.159277       1 logs_generator.go:76] 89 POST /api/v1/namespaces/default/pods/69g 247
I0729 11:30:35.359274       1 logs_generator.go:76] 90 PUT /api/v1/namespaces/kube-system/pods/tn26 434

older lines:
I0729 11:30:38.286090       1 logs_generator.go:76] 0 PUT /api/v1/namespaces/default/pods/k7c 598
I0729 11:30:38.486277       1 logs_generator.go:76] 1 PUT /api/v1/namespaces/kube-system/pods/8vp 344
I0729 11:30:38.686318       1 logs_generator.go:76] 2 PUT /api/v1/namespaces/ns/pods/r52 580
I0729 11:30:38.886403       1 logs_generator.go:76] 3 PUT /api/v1/namespaces/ns/pods/p8fd 203
I0729 11:30:39.086306       1 logs_generator.go:76] 4 POST /api/v1/namespaces/default/pods/xbs 571


Expected
    <int>: 6
to be <
    <int>: 6
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1428
```

/milestone v1.20

**Comment by hasheddan** [comment]
@soltysh I just observed this flake again. It looks like it has been an issue for some time as #88996 was also tracking. Is there someone from @kubernetes/sig-cli-misc who can look into this?

**Comment by hasheddan** [comment]
@eddiezane @soltysh Looks like there are actually two problems here. The initial failure mentioned in this issue was because tailing one line is returning two [example](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1293148191239180289), but there is also the issue of there not being older logs (mentioned above), which @eddiezane is addressing in #93763

**Comment by hasheddan** [comment]
/retitle [Flaky Test] [sig-cli] Kubectl client Kubectl logs should be able to retrieve and filter logs [Conformance]

**Comment by zhouya0** [comment]
- Tailing one line is returning two
It's because the `--tail` flag will result in finding the start line:
```
	// Search start point based on tail line.
	start, err := tail.FindTailLineStartIndex(f, opts.tail)
```
So when reading the log while writing continuously. The start index will not be the actually `--tail` number.

- Issue of there not being older logs
It's because the pod `agnhos` will be restarted after 20s. If `recent logs` is the old pod and the `older logs` is the new pod. There's no comparability between them.

**Comment by thejoycekung** [comment]
Still flaking as of the 24th: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/1309146359319760896

**Comment by thejoycekung** [comment]
Today's flake from `ci-kubernetes-e2e-gci-gce` ( https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1318479543987605504 )

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Oct 20 09:26:47.072: Expected
    <int>: 2
to equal
    <int>: 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1448
```

**Comment by thejoycekung** [comment]
It looks like this test hasn't flaked recently -- I'm going to go ahead and close this for now.

/close

**Comment by eddiezane** [comment]
This has been failing aggresively since May 7th. Same as https://github.com/kubernetes/kubernetes/issues/98854.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Kubectl%20logs%20should%20be%20able%20to%20retrieve%20and%20filter%20logs

/reopen
