### ISSUE TITLE
Data race when creating isomorphic Events with an "k8s.io/client-go/tools/events".EventRecorder

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/kubernetes#92500]
**What happened**:

I wrote a test creating multiple isomorphic Events with an "k8s.io/client-go/tools/events".[EventRecorder](https://github.com/kubernetes/client-go/blob/master/tools/events/interfaces.go#L26) and stumbled upon a data race.

The data race happens in the [recordToSink](https://github.com/kubernetes/client-go/blob/v0.18.2/tools/events/event_broadcaster.go#L153) function. It seems that the Event Series field can be read and written at the same time by two different goroutines. [Read](https://github.com/kubernetes/client-go/blob/v0.18.2/tools/events/event_broadcaster.go#L178) [Write](https://github.com/kubernetes/client-go/blob/v0.18.2/tools/events/event_broadcaster.go#L168-L171).

This seems to happen in only one scenario:
- (1) a singleton Event is created
- (2) an isomorphic Event is created
- (1) lock addition to cache
- (2) wait for the lock to be released
- (1) unlock
- (2) lock + [create](https://github.com/kubernetes/client-go/blob/v0.18.2/tools/events/event_broadcaster.go#L168-L171) the Series
- (1) [read](https://github.com/kubernetes/client-go/blob/v0.18.2/tools/events/event_broadcaster.go#L209) the freshly created Series
- (1) singleton Event is now considered as a series

That being said, this seems to lead to some data inconsistencies as the singleton Event would be created with an unexpected Series.

<details>
<summary>Data race</summary>
|==================
WARNING: DATA RACE
Write at 0x00c0001237a0 by goroutine 23:
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1.1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:183 +0x536
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:191 +0x84

Previous read at 0x00c0001237a0 by goroutine 24:
  k8s.io/api/events/v1.(*Event).DeepCopyInto()
      /home/damien/go/pkg/mod/k8s.io/api@v0.25.0/events/v1/zz_generated.deepcopy.go:31 +0x64
  k8s.io/api/events/v1.(*Event).DeepCopy()
      /home/damien/go/pkg/mod/k8s.io/api@v0.25.0/events/v1/zz_generated.deepcopy.go:58 +0x56
  k8s.io/api/events/v1.(*Event).DeepCopyObject()
      /home/damien/go/pkg/mod/k8s.io/api@v0.25.0/events/v1/zz_generated.deepcopy.go:64 +0x33
  k8s.io/client-go/testing.CreateActionImpl.DeepCopy()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/testing/actions.go:545 +0xe8
  k8s.io/client-go/testing.(*CreateActionImpl).DeepCopy()
      <autogenerated>:1 +0xb7
  k8s.io/client-go/testing.(*Fake).Invokes()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/testing/fake.go:139 +0x103
  k8s.io/client-go/kubernetes/typed/events/v1/fake.(*FakeEvents).Create()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/kubernetes/typed/events/v1/fake/fake_event.go:89 +0x214
  k8s.io/client-go/tools/events.(*EventSinkImpl).Create()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:86 +0x195
  k8s.io/client-go/tools/events.recordEvent()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:237 +0x32c
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).attemptRecording()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:207 +0xe4
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:193 +0x9d

Goroutine 23 (running) created at:
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:171 +0x159
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).startRecordingEvents.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:339 +0x75
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher.func2()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:326 +0x91

Goroutine 24 (running) created at:
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:171 +0x159
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).startRecordingEvents.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:339 +0x75
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher.func2()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:326 +0x91
|==================
|==================
WARNING: DATA RACE
Read at 0x00c0001236f0 by goroutine 23:
  k8s.io/api/events/v1.(*Event).DeepCopyInto()
      /home/damien/go/pkg/mod/k8s.io/api@v0.25.0/events/v1/zz_generated.deepcopy.go:31 +0x64
  k8s.io/api/events/v1.(*Event).DeepCopy()
      /home/damien/go/pkg/mod/k8s.io/api@v0.25.0/events/v1/zz_generated.deepcopy.go:58 +0x72
  k8s.io/client-go/tools/events.createPatchBytesForSeries()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:267 +0x4d
  k8s.io/client-go/tools/events.recordEvent()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:226 +0x98
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).attemptRecording()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:207 +0xe4
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:193 +0x9d

Previous write at 0x00c0001236f0 by goroutine 24:
  k8s.io/client-go/tools/events.recordEvent()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:236 +0x2e4
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).attemptRecording()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:207 +0xe4
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:193 +0x9d

Goroutine 23 (running) created at:
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:171 +0x159
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).startRecordingEvents.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:339 +0x75
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher.func2()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:326 +0x91

Goroutine 24 (running) created at:
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:171 +0x159
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).startRecordingEvents.func1()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:339 +0x75
  k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher.func2()
      /home/damien/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/events/event_broadcaster.go:326 +0x91
|==================
</details>

**What you expected to happen**:

No data race.

**How to reproduce it (as minimally and precisely as possible)**:

You can run the following code snippet alongside any data race detector. I personally used `go test -race`.
```go
package main

import (
	"testing"

	v1 "k8s.io/api/core/v1"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/tools/events"
	"k8s.io/kubectl/pkg/scheme"
)

func Test(t *testing.T) {
	kubeClient := fake.NewSimpleClientset()

	eventSink := &events.EventSinkImpl{Interface: kubeClient.EventsV1()}
	eventBroadcaster := events.NewBroadcaster(eventSink)

	stopCh := make(chan struct{})
	eventBroadcaster.StartRecordingToSink(stopCh)

	recorder := eventBroadcaster.NewRecorder(scheme.Scheme, "test")

	recorder.Eventf(&v1.ObjectReference{}, nil, v1.EventTypeNormal, "reason", "action", "", "")
	recorder.Eventf(&v1.ObjectReference{}, nil, v1.EventTypeNormal, "reason", "action", "", "")
}
```

**Anything else we need to know?**:

**Environment**:
- k8s.io/client-go v0.25.0

**Comment by fedebongio** [comment]
/assign @jingyih 
Would you mind taking a look to this one? thanks!

**Comment by dgrisonnet** [comment]
We might also want to look into that again for https://github.com/kubernetes/enhancements/issues/383.

/reopen

/assign
/unassign @jingyih

**Comment by dgrisonnet** [comment]
I was able to reproduce this issue with client-go v0.25.0. I updated the reproducer to be compatible with the latest version of the client and attached the data race trace.

**Comment by leilajal** [comment]
@dgrisonnet are you gong to submit a fix for this one? thanks.
/triage accepted

**Comment by dgrisonnet** [comment]
Yes, I am planning to submit a fix for this issue.
