### ISSUE TITLE
[Failing test] Conformance - GCE- master (ci-kubernetes-gce-conformance-latest)

### ISSUE THREAD

**Issue by hkamel** [kubernetes/kubernetes#92502]
**Which jobs are failing**:
> Conformance - CE- master (ci-kubernetes-gce-conformance-latest)

**Which test(s) are failing**:
> - Overall
> - TestChanges[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]
>- [sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching [Conformance]
>- [sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]
>- [sig-scheduling] SchedulerPredicates [Serial] validates that there exists conflict between pods with same hostPort and protocol but one using 0.0.0.0 hostIP [Conformance]
>- [sig-scheduling] SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [Conformance]
>- [sig-scheduling] SchedulerPreemption [Serial] PreemptionExecutionPath runs ReplicaSets to verify preemption running path [Conformance]
>- [sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Conformance]
>- [sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Conformance]

**Since when has it been failing**:
> 06-25 21:37 PDT

**Testgrid link**:
>https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master

**Reason for failure**:
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:89
Test Panicked
/usr/local/go/src/runtime/map_faststr.go:204

> Panic: assignment to entry in nil map

> Full stack:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert(0x0, 0xc001406da8, 0x1, 0x1, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/string.go:51 +0x78
k8s.io/kubernetes/test/e2e/scheduling.glob..func5.2()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:106 +0x4e2
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000e79e60)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x35b
k8s.io/kubernetes/test/e2e.TestE2E(0xc000e79e60)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:141 +0x2b
testing.tRunner(0xc000e79e60, 0x4c616e0)
	/usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x357

**Anything else we need to know**:

/sig scheduling
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by hasheddan** [comment]
/retitle [Failing test] Conformance - GCE- master (ci-kubernetes-gce-conformance-latest)

I am landing a fix for this now

/assign

**Comment by hkamel** [comment]
Thanks @hasheddan !
