### ISSUE TITLE
[Flaky test] TestExpectationsOnRecreate

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#92520]
**Which jobs are flaking**:

* pull-kubernetes-bazel-test

**Which test(s) are flaking**:

```
=== RUN   TestExpectationsOnRecreate
I0625 18:50:35.370026      23 shared_informer.go:240] Waiting for caches to sync for test dsc
I0625 18:50:35.477041      23 shared_informer.go:247] Caches are synced for test dsc 
    TestExpectationsOnRecreate: daemon_controller_test.go:569: There should be no expectations for DaemonSet "default/test" after it was deleted
--- FAIL: TestExpectationsOnRecreate (0.33s)
```

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90454/pull-kubernetes-bazel-test/1276221145426694147
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestExpectationsOnRecreate

/sig apps

**Comment by tnozicka** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/93617
/close
