### ISSUE TITLE
Add Windows 2004 test jobs for GCE

### ISSUE THREAD

**Issue by pjh** [kubernetes/kubernetes#92522]
Windows Server 2004 was released last month, and sig-windows will likely support it for K8s 1.19. We need to add new test jobs that will appear on the [google-windows](https://testgrid.k8s.io/google-windows) / [sig-windows](https://testgrid.k8s.io/sig-windows) testgrids.

Steps to do this:
- Create a suitable VM image for Windows 2004 nodes. Historically for our test jobs we've used GCE's "Windows for containers" images, but GCE will likely not produce such an image for 2004 - we will create and use a GKE Windows 2004 image instead.
- Update the GCE cluster scripts with 2004 support ([1909 example](https://github.com/kubernetes/kubernetes/pull/87629)).
- Add a new test job for master/1.19 in the test-infra config ([1909 example](https://github.com/kubernetes/test-infra/pull/16050)).

**Comment by pjh** [comment]
cc @michmike @marosset @jsturtevant @jeremyje @YangLu1031

**Comment by michmike** [comment]
cc: @adelina-t

**Comment by marosset** [comment]
We should add 2004 jobs for Azure / aks-engine as well @jsturtevant FYI

**Comment by immuzz** [comment]
@adelina-t Do you wanna look at this when you get a chance?

**Comment by pjh** [comment]
/close

We're likely going to skip directly to 20H2 instead.
