### ISSUE TITLE
ResourceQuota calculation

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#92529]
**What happened**:

ResourceQuota usage by a pod seems to be the sum of the requests / limits of all containers within a pod, including initContainers.

**What you expected to happen**:

initContainers only run one at a time, and never when the main containers are running. So to make a pod QoS Guaranteed, those resources must be reserved and will never be used at runtime.

IE, its doing sum(containers) + sum(initContainers)

The quota/node resurvation for the pod's calculation should be:
max(each initContainer individually and the sum(containers))
This meets and reserves the actual amount of resource that will ever be consumed by the pod at any time in its existence.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a guaranteed pod with a few init containers and check its usage against a ResourceQuota

**Comment by liggitt** [comment]
Is that not what https://github.com/kubernetes/kubernetes/pull/29588/files fixed?

**Comment by kfox1111** [comment]
That sure does look like a fix.

I could have sworn I ran into this a little while ago. I'll double check. Maybe something else happened to the namespace when I did it at the same time.

I'll verify.

**Comment by kfox1111** [comment]
Hmm.. I am unable to verify it now on a fresh minikube. I think I ran into some other issue. Sorry for the noise.
