### ISSUE TITLE
certified-conformance : ./sonobuoy run --mode certified-conformance --wait -v 5 failed with timeout error

### ISSUE THREAD

**Issue by RameshJampana** [kubernetes/kubernetes#92539]
certified-conformance : ./sonobuoy run --mode certified-conformance --wait -v 5 failed with below error

 level=error msg="Result processing error (409): result systemd-logs/cluster already received"
level=error msg="Result processing error (409): result systemd-logs/cluster already received"
 level=error msg="Result processing error (409): result systemd-logs/cluster already received"
level=error msg="Result processing error (409): result systemd-logs/cluster already received"
 level=error msg="Timeout waiting for plugin e2e"
 level=error msg="error running plugins: timeout occurred when waiting for plugin results"
 level=error msg="Timeout occurred when running plugins. Inspect logs further for details."

**Comment by dims** [comment]
please ask in https://github.com/vmware-tanzu/sonobuoy 

/close
