### ISSUE TITLE
kubernetes dist file is big; executables in docker images are included twice

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#9253]
kubernetes-server-linux-amd64.tar.gz is 71 MB; that seemed bigger than I remember it being.

Focusing on kube-scheduler...

`tar tzvf kubernetes-server-linux-amd64.tar.gz` shows e.g.
```
-rwxr-xr-x root/root  17781624 2015-06-03 22:27 kubernetes/server/bin/kube-scheduler
-rw-r--r-- root/root  20449792 2015-06-03 22:27 kubernetes/server/bin/kube-scheduler.tar
```

Expanding kube-scheduler.tar, the big layer (for me) is one where the JSON says has 
```Cmd":["/bin/sh","-c","#(nop) ADD file:1921730b6a5704e5144432383579662ef9b1a97e9361f7a3cf276544f4ac349c in /usr/local/bin/kube-scheduler"]```

And untaring layer.tar shows that the only file is `usr/local/bin/kube-scheduler`

Checksum indicates the files are identical.

I think this is repeated for kube-apiserver & kube-controller-manager.

Excluding the repeated files and re-tarring drops the size from 71MB to 54MB.

I believe we aren't using these files other than in the Docker containers (?)

**Comment by zmerlynn** [comment]
We ship these for most of the CoreOS distros. Until they find another way, we need to revert the solution.

**Comment by kelseyhightower** [comment]
@zmerlynn Should everyone on the community side move to docker containers for master components?

**Comment by alex-mohr** [comment]
@kelseyhightower we plan to run master components in containers for GCE and GKE going forward.  Unless that's a hardship for other distros, perhaps we can encourage it?

And if the tarball sizes are a problem, perhaps we could have a size-optimized tarball with just binaries?

**Comment by justinsb** [comment]
Closing in favor of #28435 which has more up to date work
