### ISSUE TITLE
The presence of admission validating webhooks breaks Ephemeral Containers

### ISSUE THREAD

**Issue by johan1252** [kubernetes/kubernetes#92557]
**What happened**:
Adding a validating webhook with resources section of `"pods/*"` or `"*/*"` breaks ability to add Ephemeral Containers as described in https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container

**What you expected to happen**:
```
kubectl alpha debug -it rabbit --image=busybox --target=rabbitmq
```
Debug command should attach to the running pod and allow user to interact with the ephemeral container image. This works when no validating webhook is configured.

**How to reproduce it (as minimally and precisely as possible)**:
Using a K8 cluster with Ephemeral Containers feature gate enabled and v1.18.3
1. Create a validating webhook (contents don't matter except that resources is "pods/*")
<details>
  <summary>whconfig.yaml</summary>

  ```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: test-repro
webhooks:
- name: test-repro.test.k8s.io
  clientConfig:
    url: https://localhost:8675/hook
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["pods/*"]
```
</details>

```
kubectl apply -f whconfig.yaml
```

2. Create a test pod
<details>
  <summary>test_pod.yaml</summary>

  ```
apiVersion: v1
kind: Pod
metadata:
  name: rabbit
  labels:
    role: myrole
spec:
  shareProcessNamespace: true
  containers:
    - name: rabbitmq
      image: rabbitmq
      ports:
        - name: rabbit
          containerPort: 5672
          protocol: TCP
```
</details>

```
kubectl apply -f test_pod.yaml
```

3. Try to add an Ephemeral Container using alpha debug command
```
kubectl alpha debug -it rabbit --image=busybox --target=rabbitmq
```
Error:
```
$ kubectl alpha debug -it rabbit --image=busybox --target=rabbitmq
Defaulting debug container name to debugger-jvc8h.
error: error updating ephemeral containers: Internal error occurred: converting (core.Pod) to (v1.EphemeralContainers): EphemeralContainers not present in src
```

**Anything else we need to know?**:
When using `v=10`, can see that the api server appears to be throwing the error when trying to convert the object for the webhook invocation.
API returning the 500 error: `http://localhost:8080/api/v1/namespaces/default/pods/rabbit/ephemeralcontainers`

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: Minikube
- OS (e.g: `cat /etc/os-release`):  MacOS
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
This looks like an issue with the ephemeral container storage. It is inheriting the New function from the pod storage to return a core.Pod{}, but that doesn't match the type the ephemeral storage actually expects. 

I think the ephemeral storage should probably set up its own New method to return the proper type. 

Enabling the feature gate for the ephemeral container feature in the webhook admission integration test would exercise this with webhooks as well. 

/sig node
/priority important-longterm
/assign @verb

**Comment by verb** [comment]
ack, thanks for the report & triage! I'm digging into it now.

**Comment by verb** [comment]
I thank what matters for proper typing is that `rest.Storage.New()` for `pods/ephemeralcontainers` returns the proper type. This is already implemented for `EphemeralContainersREST` and returns an `EphemeralContainers` API object.

Here's what I think is happening: 

1. `EphemeralContainersREST` gets an update for the `ephemeralcontainers` subresource. This is translated into an update of the pod spec and handed off to the pod store since ephemeral containers do not have separate storage.
2. The update logic triggers admission control for the `Pod` object with the attributes of the `ephemeralcontainers` subresource.
3. The webhook client attempts to convert the stored object (a `Pod`) to the Kind of the ephemeralcontainers attributes (`EphemeralContainers` identified by `EphemeralContainersREST.New()`), but this conversion doesn't exist.

It is actually possible to convert from `Pod` to `EphemeralContainers`, and this fixes the problem except that:
* The conversion is lossy, which would presumably be a problem for a mutating admission controller that returned an `EphemeralContainers` which could not be converted back into a `Pod`
* This would result in the `EphemeralContainers` being sent in the `AdmissionReview` instead of the `Pod`, which is not the behavior we want.

We could instead implement `rest.GroupVersionKindProvider` in `EphemeralContainersREST`, which allows us to override the Kind associated with `ephemeralcontainers`. This results in no conversion and the `Pod` is sent to the admission controller, but this also changes discovery info from:
```
    {
      "name": "pods/ephemeralcontainers",
      "singularName": "",
      "namespaced": true,
      "kind": "EphemeralContainers",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
```

to:
```
    {
      "name": "pods/ephemeralcontainers",
      "singularName": "",
      "namespaced": true,
      "version": "v1",
      "kind": "Pod",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
```

This fixes the problem, but I'm not sure what other side effects to expect. I imagine if we publish `Pod` for this subresource then we should accept `Pod` in addition to `EphemeralContainers`. 

I feel like I might be missing something in the storage configuration, though. @liggitt do you know of any other possible fixes I could investigate?

**Comment by verb** [comment]
For future reference, here's a trace from the validation dispatch that receives the conversion error:

```
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating.(*validatingDispatcher).Dispatch(0xc000c37f20, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, 0x50d7640, 0xc002c704e0, 0xc008622260, 0x1, 0x1, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go:56 +0x37
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/generic.(*Webhook).Dispatch(0xc00009d1d0, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, 0x50d7640, 0xc002c704e0, 0x2, 0x2)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook.go:229 +0x26f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating.(*Plugin).Validate(0xc00059ce70, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, 0x50d7640, 0xc002c704e0, 0x1, 0x1)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/plugin.go:70 +0x145
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/metrics.pluginHandlerWithMetrics.Validate(0x503bf20, 0xc00059ce70, 0xc000c37fe0, 0xc000c37ff0, 0x1, 0x1, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go:111 +0xfc
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.chainAdmissionHandler.Validate(0xc000175600, 0x11, 0x20, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, 0x50d7640, 0xc002c704e0, 0x1, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/chain.go:53 +0x14e
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*reinvoker).Validate(0xc000cc41f0, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, 0x50d7640, 0xc002c704e0, 0x4847d20, 0x6)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/reinvocation.go:56 +0xa4
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/metrics.pluginHandlerWithMetrics.Validate(0x503be60, 0xc000cc41f0, 0xc000cc4200, 0x0, 0x0, 0x0, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go:111 +0xfc
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.auditHandler.Validate(0x503be80, 0xc000cc82a0, 0xc00c6abe00, 0x50a5140, 0xc00fa6ecc0, 0x51042c0, 0xc00954cb40, 0x50d7640, 0xc002c704e0, 0x6, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/audit.go:72 +0x139
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest.AdmissionToValidateObjectUpdateFunc.func2(0x50a5140, 0xc00fa6ecc0, 0x5044440, 0xc00ca80800, 0x5044440, 0xc00ca80c00, 0x5044440, 0xc00c8b9400)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/update.go:279 +0x531
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update.func1(0x5044440, 0xc00c8b9400, 0x0, 0x14e, 0x11c81982bc, 0xbfc7c180d78ea305, 0xc000cb9260, 0xc00c89d000, 0xc005c45e40)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:553 +0x92e
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*store).updateState(0xc000cb9260, 0xc0115b98c0, 0xc00c7ad180, 0x5044440, 0xc00c8b9400, 0x0, 0x0, 0xc00c7adb80)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:845 +0x5b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*store).GuaranteedUpdate(0xc000cb9260, 0x50a5140, 0xc00fa6ecc0, 0xc005c45de0, 0x14, 0x5044440, 0xc00c89d000, 0x1, 0xc008e182c0, 0xc00c7ad180, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go:296 +0x645
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).GuaranteedUpdate(0xc000cbb1e0, 0x50a5140, 0xc00fa6ecc0, 0xc005c45de0, 0x14, 0x5044440, 0xc00c89d000, 0x401, 0xc008e182c0, 0xc00c7ad180, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:740 +0x2fd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*DryRunnableStorage).GuaranteedUpdate(0xc000f907a8, 0x50a5140, 0xc00fa6ecc0, 0xc005c45de0, 0x14, 0x5044440, 0xc00c89d000, 0x1, 0xc008e182c0, 0xc00c7ad180, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/dryrun.go:101 +0x34b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update(0xc000f906c0, 0x50a5140, 0xc00fa6ecc0, 0xc002e51aa0, 0x6, 0x504e380, 0xc00f9d9500, 0xc002ca0af0, 0xc011cf6980, 0x0, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:475 +0x3da
k8s.io/kubernetes/pkg/registry/core/pod/storage.(*EphemeralContainersREST).Update(0xc00000e4f8, 0x50a5140, 0xc00fa6ecc0, 0xc002e51aa0, 0x6, 0x504e380, 0xc00fe647e0, 0xc002ca0af0, 0xc011cf6980, 0xc00c95a800, ...)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/core/pod/storage/storage.go:375 +0x365
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.UpdateResource.func1.3(0x40a65f, 0xc0006a8000, 0x414d020, 0x4483b40)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go:174 +0x9cc
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.UpdateResource.func1.4(0xc008096a20, 0x7f8ed677f438, 0xc009e6fba0, 0xc00c6cd500)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go:192 +0x53
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1(0xc007e30000, 0xc00fe647b0, 0xc007d4ff80, 0xc007d4fe00)
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:241 +0x62
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest
        /home/verb/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:222 +0xd4
```

**Comment by liggitt** [comment]
mutating admission is applied here:

https://github.com/kubernetes/kubernetes/blob/1c548c328a32c5b6819195760d1abba115ab4969/pkg/registry/core/pod/storage/storage.go#L327

validating admission methods (createValidation / updateValidation) is called from inside `r.store.Update` here:

https://github.com/kubernetes/kubernetes/blob/1c548c328a32c5b6819195760d1abba115ab4969/pkg/registry/core/pod/storage/storage.go#L349

You need to wrap the createValidation / updateValidation methods (which expect an EphemeralContainers object) with methods that take a pod (which is what `r.store.Update` will pass in) and translate it to an EphemeralContainers object. See ScaleREST#Update methods for examples of this for the Scale subresource.

> It is actually possible to convert from Pod to EphemeralContainers, and this fixes the problem except that:
>
> 1. The conversion is lossy, which would presumably be a problem for a mutating admission controller that returned an EphemeralContainers which could not be converted back into a Pod

Mutating admission is applied earlier, the only problematic call is validating admission

> 2. This would result in the EphemeralContainers being sent in the AdmissionReview instead of the Pod, which is not the behavior we want.

Isn't it? The user is submitting an `EphemeralContainers` object... so that's what `AdmissionReview` should be sent.

**Comment by verb** [comment]
Thanks @liggitt, that set me straight. I have a working fix for this now, but I'm going to make sure it's covered in the e2e tests before sending it.

re: `AdmissionReview` for `EphemeralContainers`, it was a comment you made long ago that made me think there was a requirement to the contrary, so I must have misunderstood.

**Comment by johan1252** [comment]
@liggitt @verb I had a chance to re-test this flow with `v1.20.0-alpha3` which contains the fix to https://github.com/kubernetes/kubernetes/pull/94685. Although the original issue appears to be fixed, I am hoping to understand what the end goal is for ephemeral containers and their webhook behaviour.

In my test, I enabled my `ValidatingWebhookConfiguration` to forward all resources `*/*`. When running `kubectl alpha debug -it rabbit --image=busybox --target=rabbitmq` to add an ephemeral container to an existing pod, the only webhook that I received was for `Resource=pods,subresource:status,operation:UPDATE`, which did contain the updated pod spec.
However I was hoping that the addition of an ephemeral container would cause a webhook to trigger that wasn't of type `subresource=status`. Maybe of type `resource=ephemeralContainer` or `resource=pod,subresource=ephemeralContainer`? Is there any plans to add a webhook trigger for ephemeral containers specifically?

API server logs after doing `kubectl alpha debug`:
```
I1022 18:20:16.680762       1 trace.go:205] Trace[800289955]: "Call validating webhook" configuration:test-vald-webhook,webhook:test-vald-webhook.default.svc,resource:/v1, Resource=pods,subresource:status,operation:UPDATE,UID:b9b6e119-b2e5-467e-899d-70600c64abeb (22-Oct-2020 18:20:15.931) (total time: 749ms):
Trace[800289955]: ---"Request completed" 749ms (18:20:00.680)
Trace[800289955]: [749.215357ms] [749.215357ms] END
I1022 18:20:16.682511       1 trace.go:205] Trace[1432493664]: "GuaranteedUpdate etcd3" type:*core.Pod (22-Oct-2020 18:20:15.928) (total time: 754ms):
Trace[1432493664]: ---"Transaction prepared" 752ms (18:20:00.681)
Trace[1432493664]: [754.310013ms] [754.310013ms] END
I1022 18:20:16.682653       1 trace.go:205] Trace[803415534]: "Patch" url:/api/v1/namespaces/default/pods/rabbit/status,user-agent:kubelet/v1.20.0 (linux/amd64) kubernetes/6d3ccd8,client:172.19.0.2 (22-Oct-2020 18:20:15.928) (total time: 754ms):
Trace[803415534]: ---"Object stored in database" 751ms (18:20:00.682)
Trace[803415534]: [754.591895ms] [754.591895ms] END
```

**Comment by verb** [comment]
Hi @johan1252,

Your admission controller should receive a review request for resource `pods` subresource `ephemeralcontainers` with a kind `EphemeralContainers`.

When I run a test on `v1.20.0-alpha.2.105+56833a63c902e8` using the `agnhost` test webhook and the config:

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["*"]
    resources:   ["pods/*"]
    scope:       "Namespaced"
  clientConfig:
    url: "https://localhost:9912/always-allow-delay-5s"
    caBundle: "..."
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 10
```

I see this request

```
{
	"kind":"AdmissionReview",
	"apiVersion":"admission.k8s.io/v1",
	"request":{
		"uid":"ec811dc7-05ca-4ad9-ad89-26494baf70d9",
		"kind":{
			"group":"",
			"version":"v1",
			"kind":"EphemeralContainers"
		},
		"resource":{
			"group":"",
			"version":"v1",
			"resource":"pods"
		},
		"subResource":"ephemeralcontainers",
		"requestKind":{
			"group":"",
			"version":"v1",
			"kind":"EphemeralContainers"
		},
		"requestResource":{
			"group":"",
			"version":"v1",
			"resource":"pods"
		},
		"requestSubResource":"ephemeralcontainers",
		"name":"iso",
		"namespace":"default",
		"operation":"UPDATE",
		"userInfo":{
			"username":"system:admin",
			"groups":[
				"system:masters",
				"system:authenticated"
			]
		},
		"object":{
			"kind":"EphemeralContainers",
			"apiVersion":"v1",
			"metadata":{
				"name":"iso",
				"namespace":"default",
				"uid":"f6430e1a-7291-4fa2-a80d-0666931a569d",
				"resourceVersion":"886",
				"creationTimestamp":"2020-10-28T16:49:53Z"
			},
			"ephemeralContainers":[
				{
					"name":"debugger-zvprm",
					"image":"busybox",
					"resources":{
						
					},
					"terminationMessagePath":"/dev/termination-log",
					"terminationMessagePolicy":"File",
					"imagePullPolicy":"Always"
				}
			]
		},
		"oldObject":{
			"kind":"EphemeralContainers",
			"apiVersion":"v1",
			"metadata":{
				"name":"iso",
				"namespace":"default",
				"uid":"f6430e1a-7291-4fa2-a80d-0666931a569d",
				"resourceVersion":"886",
				"creationTimestamp":"2020-10-28T16:49:53Z"
			},
			"ephemeralContainers":[
				
			]
		},
		"dryRun":false,
		"options":{
			"kind":"UpdateOptions",
			"apiVersion":"meta.k8s.io/v1"
		}
	}
}
```

**Comment by johan1252** [comment]
@verb I see it now...must have had a misconfiguration on my previous test. Sorry about that. Thanks for your work on this! Having ephemeral container support is very useful!

**Comment by verb** [comment]
@johan1252 Great! Thanks for trying out the feature while still in alpha and reporting the bug! 😁  👍
