### ISSUE TITLE
configure-helper.sh doesn't assemble-docker-flags for containerd runtimes

### ISSUE THREAD

**Issue by briansneddon** [kubernetes/kubernetes#92552]
https://github.com/kubernetes/kubernetes/blob/e5f55dd9d0969af3a37e7880d9b88c9aef8c654d/cluster/gce/gci/configure-helper.sh#L2739-L2741

When CONTAINER_RUNTIME is docker (or unset) then assemble-docker-flags is called and docker environment flags are generated and written out to /etc/default/docker in order to be loaded in during startup. 

When the CONTAINER_RUNTIME is containerd (e.g. when using a GKE containerd node) assemble-docker-flags is not called and therefore /etc/default/docker is not created. 

For GKE one of the current benefits within assemble-docker-flags is that the Docker bridge ip is set to 169.254.123.1/24 versus the 172.17.0.0/16 default. This link local network range is helpful in avoiding conflicts with other internally routable networks that may conflict with the latter RFC1918 range.

Should assemble-docker-flags as is be called for both docker and containerd runtimes? If not perhaps it could be refactored to support both runtimes and provide to containerd at the very least the configuration of the Docker bridge ip.

**Comment by briansneddon** [comment]
My current understanding is that this issue may now be [obsolete](https://github.com/kubernetes/kubernetes/pull/91684/commits/1731cb30f540d386147f9e89b989e9753aa9daa3) and that the Docker daemon is no longer started in new releases.

**Comment by jayunit100** [comment]
assuming we can close this now.
