### ISSUE TITLE
kubelet: fatal error unexpected signal during runtime execution

### ISSUE THREAD

**Issue by luomoyisheng** [kubernetes/kubernetes#92564]
**What happened**:
```sh
Jun 26 10:07:11 worker1 systemd: kubelet.service holdoff time over, scheduling restart.
Jun 26 10:07:11 worker1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 26 10:07:11 worker1 systemd: Starting kubelet: The Kubernetes Node Agent
```

**What you expected to happen**:

```sh
kubelet.service not restart
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```sh
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVer
sion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVer
sion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:Physical machine
- OS (e.g: `cat /etc/os-release`):centos7.6
- Kernel (e.g. `uname -a`):  3.10.0-957.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
1.13 is quite old.
Do you have a chance to try recent 1.18 release ?

Please provide log prior to Jun 26 10:07:11 so that we can have more context.

thanks

**Comment by luomoyisheng** [comment]
Since the business is already running in this environment, there is no way to update the version, I am looking for other solutions, do you have any suggestions?
