### ISSUE TITLE
{pull,ci}-kubernetes-e2e-gce-ubuntu-containerd are failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#92563]
this is blocking merges.

pretty sure I have the fix here https://github.com/kubernetes/test-infra/pull/18089

/sig testing
/sig node
/priority critical-urgent
FYI @kubernetes/ci-signal

**Comment by BenTheElder** [comment]
up failing
https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd
failing to download in the logs:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1276638936235511808/artifacts/bootstrap-e2e-master/kube-master-installation.log
suspected break: https://github.com/kubernetes/test-infra/pull/18086

**Comment by BenTheElder** [comment]
https://prow.k8s.io/?job=pull-kubernetes-e2e-gce-ubuntu-containerd
<img width="522" alt="Screen Shot 2020-06-26 at 7 28 11 PM" src="https://user-images.githubusercontent.com/917931/85912680-3271cf00-b7e3-11ea-978c-a149b6e64860.png">
The only passing runs are from PRs installing custom versions.

**Comment by BenTheElder** [comment]
successful up https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92212/pull-kubernetes-e2e-gce-ubuntu-containerd/1276703610704498689/

**Comment by BenTheElder** [comment]
Above run passed and the PR merged

**Comment by BenTheElder** [comment]
<img width="1338" alt="Screen Shot 2020-06-26 at 9 25 31 PM" src="https://user-images.githubusercontent.com/917931/85914525-969c8f00-b7f3-11ea-8674-1ab2731b7bf6.png">

cluster up in the CI job now too https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1276730285869764608

**Comment by tedyu** [comment]
Nice job, Ben.
