### ISSUE TITLE
Typo of PercentageOfNodesToScore

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#92561]
There are some typos which put "PercentageOfNodesToScore" (correct) as "PercentageOfNodeToScore" (wrong):

```
⇒  ag -i PercentageOfNodeToScore
staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go
67:	// PercentageOfNodeToScore is the percentage of all nodes that once found feasible

pkg/scheduler/apis/config/types.go
83:	// PercentageOfNodeToScore is the percentage of all nodes that once found feasible
```

/cleanup
/sig scheduling
/good-first-issue

**Comment by Huang-Wei** [comment]
@satishbellapu we usually follow a first-come-first-get rule, so given @rakeshreddybandi has claimed it earlier, would you mind leaving it to him?

**Comment by satishbellapu** [comment]
> @satishbellapu we usually follow a first-come-first-get rule, so given @rakeshreddybandi has claimed it earlier, would you mind leaving it to him?

Sure sorry I didn’t notice that, but not sure how to pull back the commit.
