### ISSUE TITLE
Login to k8 cluster using a new key and csr signed using "certificatesigningrequests" object failing with Error "error: You must be logged in to the server (Unauthorized)"

### ISSUE THREAD

**Issue by skynetrulz** [kubernetes/kubernetes#92574]
**What happened**: kubectl commands to k8 cluster using a new key and csr signed using "certificatesigningrequests" object failing with Error "error: You must be logged in to the server (Unauthorized)"

**What you expected to happen**: Login to be successful

**How to reproduce it (as minimally and precisely as possible)**:  Follow this article

https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

**Anything else we need to know?**: when i impersonate using  --user (kubectl get po --user <newuser> while running as default kubernetes-admin, I am getting the desired output

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.18.4
- Cloud provider or hardware configuration: 3 Node k8 cluster created using kubeadm
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS 
- Kernel (e.g. `uname -a`): Linux master3 5.3.0-1031-azure

kubeconfig file has been generated as per the document.

https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

**Comment by wawa0210** [comment]
Judging from the error message, it may be caused by the permission problem of your kubectl configuration~~ What identity is your kubeconfig configured?

**Comment by skynetrulz** [comment]
> Judging from the error message, it may be caused by the permission problem of your kubectl configuration~~ What identity is your kubeconfig configured?

Sorry, i didn't get your comment. In my kubeconfig file, i have the new key, new crt (signed by api server) and ca cert

**Comment by neolit123** [comment]
you can try asking for help on the support channels or #sig-auth on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by liggitt** [comment]
The `You must be logged in to the server (Unauthorized)` error indicates the credential you are using is not recognized by the server. Verify the issued certificate is a valid client certificate and is signed by an authority included in the kube-apiserver's `--client-ca-file` bundle.

/close
