### ISSUE TITLE
"reservedCpus" ignored when passed in config.yaml ,works when passed as argument "--reserved-cpus" 

### ISSUE THREAD

**Issue by krrypto** [kubernetes/kubernetes#92585]
**What happened**:
Trying to isolate two cores,
cat /var/lib/kubelet/config.yaml|grep -i reservedCpus
reservedCpus: "0,1"

restarted kubelet.
Still kubectl is reporting allocated and Capacity as the same

If i pass --reserved-cpus=0,1 as kubelet start arguments then kubelet is reserving it correctly.

/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --reserved-cpus=0,1 xxxxx

**What you expected to happen**:
reservedCpus: "0,1" in /var/lib/kubelet/config.yaml  should isolate two cores.

**How to reproduce it (as minimally and precisely as possible)**:
edit /var/lib/kubelet/config.yaml add reservedCpus: "0,1" and restart kubelet.Check Allocatable using kubectl command

**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
OS: Ubuntu 18.04.
Kernel:4.15.0-106-generic
Install tool: kubeadm

**Comment by krrypto** [comment]
looks like a configuration issue:

Jun 29 00:32:39 k8worker1 kubelet[4963]: : v1beta1.KubeletConfiguration.ReadObject: found unknown field: reserved-cpus, error found in #10 byte of ...|rved-cpus":0,"rotate|..., bigger context ...|","nodeStatusUpdateFrequency":"0s","reserved-cpus":0,"rotateCertificates":true,"runtimeRequestTimeou|...

Is there a document explaining the right variable to use for reserved-cpus 

tried: 
cat /var/lib/kubelet/config.yaml |grep -i reser
#reservedCpus: "0"
reserved-cpus: 0

**Comment by robinpercy** [comment]
@krrypto looks like you want reservedSystemCPUs: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L733

**Comment by krrypto** [comment]
Thanks @robinpercy
