### ISSUE TITLE
Docs website seems to be broken

### ISSUE THREAD

**Issue by codeaprendiz** [kubernetes/kubernetes#92580]
## Kubernetes Docs Release notes link seems to be broken with overlapping UI

Hi team, 
I am seeing overlapping UI in the website. Attaching a screenshot for the same.

![image](https://user-images.githubusercontent.com/18071639/85941603-f2bafc80-b934-11ea-83cd-109996ff1e0f.png)

[link](https://kubernetes.io/docs/setup/release/notes/)

**Comment by tanjunchen** [comment]
@codeaprendiz 
I think you can open an issue in https://github.com/kubernetes/website , not here.

**Comment by codeaprendiz** [comment]
oh okay, @tanjunchen thanks let me open the issue there.
