### ISSUE TITLE
Unhealthy device cause the scheduler failed to schedule

### ISSUE THREAD

**Issue by draveness** [kubernetes/kubernetes#92592]
**What happened**:

Currently, the device manager calculated the node's allocatable and capacity by healthy and unhealthy devices.

https://github.com/kubernetes/kubernetes/blob/aadaa5d6a917fcb354bce80a0bd1830c95cfbcc3/pkg/kubelet/cm/devicemanager/manager.go#L519-L567

Suppose there are two GPU devices on the node, GPU1 and GPU2. When GPU1 is allocated to a pod and soon become unhealthy, 

+ Kubelet won't evict the pod consuming unhealthy devices https://github.com/kubernetes/kubernetes/issues/60388 and the allocatable of the current node reduced to 1 because of the unhealthy devices.
+ Kubelet would report the allocatable and capacity which is 1 and 2 to the apiserver.

If another pod was applied into the cluster, the scheduler would check the node's allocatable and requested. Although we still have a healthy device on this node - GPU2, it still fails to schedule the pod on it, as it uses the following condition to validate the pod's resources

https://github.com/kubernetes/kubernetes/blob/aadaa5d6a917fcb354bce80a0bd1830c95cfbcc3/pkg/scheduler/framework/plugins/noderesources/fit.go#L247-L264

And we get an insufficient resource error in the pod's events.

**What you expected to happen**:

Kubelet calculates the allocatable resources with healthy devices and unhealthy allocated devices, so the scheduler could do the scheduling.

/sig node
/sig scheduling
/kind bug

**Comment by soulxu** [comment]
Seems like there is no way for the scheduler to figure the allocated resource is the healthy or unhealthy one.

For example, the GPU capacity is 2, allocatable is 2, allocated 1. The allocated one becomes unhealthy. Then GPU capacity is still 2, allocatable is 1, allocated 1. So the scheduler shouldn't count that allocated one anymore. But looks like there is no way to figure out the allocated one is unhealthy.

**Comment by draveness** [comment]
> Seems like there is no way for the scheduler to figure the allocated resource is the healthy or unhealthy one.
> 
> For example, the GPU capacity is 2, allocatable is 2, allocated 1. The allocated one becomes unhealthy. Then GPU capacity is still 2, allocatable is 1, allocated 1. So the scheduler shouldn't count that allocated one anymore. But looks like there is no way to figure out the allocated one is unhealthy.

Yes, that is the problem we met
