### ISSUE TITLE
Support for connecting to glusterfs csi using TLS

### ISSUE THREAD

**Issue by amgads** [kubernetes/kubernetes#92594]
_Originally posted by @fejta-bot in https://github.com/kubernetes/kubernetes/issues/42632

Need k8s glusterfs csi to support connect with tls. Heketi supports tls, but k8s is blocking it.
Refer to the following link for the required changes "NewClientTLS()"

https://github.com/heketi/heketi/issues/1467

**Comment by amgads** [comment]
Any update of the feature or fix?

**Comment by amgads** [comment]
This should stay fresh -- the feature is needed.
Is there anything additional I need to do?

**Comment by amgads** [comment]
This issue change is needed as it blocks using TLS for GlusterFS storage class

**Comment by amgads** [comment]
Is there any update on this issue? -- need some response on target date if in the process!

**Comment by lainosantos** [comment]
Hello, I have been using Glusterfs + Heketi with TLS in Management and I / O Path, everything is ok. The only change was trusting the CA certificate on the kubernete hosts.

**Comment by lainosantos** [comment]
Hello, I have been using Glusterfs + Heketi with TLS in Management and I / O Path, everything is ok. The only change was trusting the CA certificate on the kubernetes hosts.

**Comment by lainosantos** [comment]
Hello, I have been using Glusterfs + Heketi with TLS in Management and I/O Path, everything is ok. The only change was trusting the CA certificate on the kubernete hosts.
