### ISSUE TITLE
Create a tutorial for running Kubernetes on DCOS

### ISSUE THREAD

**Issue by guenter** [kubernetes/kubernetes#9260]
Kubernetes will be available on the Mesosphere DCOS. Add a tutorial that explains how to do this.

**Comment by jmheidly** [comment]
Has anything been done in this regard??

**Comment by jdef** [comment]
xref https://github.com/mesosphere/universe/issues/348

**Comment by justinclayton** [comment]
Would love a semi-official statement of direction in this regard.

**Comment by k82cn** [comment]
hi team, k8sm only focus on Mesos; I'd like to delegate your requirement to DC/OS community :). For the progress, please refer to https://github.com/dcos/dcos-docs/issues/621 .

@jdef , would help to close this issue for now?

**Comment by jdef** [comment]
Regarding direction: running k8sm on dc/os is, at this point, a community-driven effort. Current releases of dc/os do not support k8sm.

**Comment by k82cn** [comment]
IMO, k8sm only provide the doc for pure Mesos, but no doc for DC/OS or other e2e solution.

**Comment by k82cn** [comment]
/close

Please open an issue in [kube-mesos](https://github.com/kubernetes-incubator/kube-mesos-framework) if it's still necessary.
