### ISSUE TITLE
Kubelet will pull only signed when DCT is enabled to docker at node level

### ISSUE THREAD

**Issue by AndreiBamboi** [kubernetes/kubernetes#92602]
**What would you like to be added**:
After following this guide https://docs.docker.com/engine/security/trust/content_trust/ to enable DCT on kubernetes nodes, i expected that the docker engine used by kubelet should make use of this feature but it isn't. I would like that those env variable should be enabled by specifying an additional deployment parameter similar for imagepullsecret. 

ex. of possible parametrizations :

  imagePullTrust:
    - secret-key: myprivatekey
      secret-passphrase: secret_for_passhprase 
      trust-server : my_notary_server.

When above configuration is available, will automatically add the required ENV VARS:
- DOCKER_CONTENT_TRUST=1
- DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="passphrase from secret-passphrase"
 Details on how the automation should work here https://docs.docker.com/engine/security/trust/trust_automation/

**Why is this needed**:
I need to be able to pull only signed images and for this i need to make use of DCT ( Docker Content Trust) and Notary.

**Comment by BenTheElder** [comment]
Kubernetes is moving away from direct usage of docker to the CRI - Container Runtime Interface. 
I don't think new docker specific features are being used. A feature like this would likely need an enhancement proposal to CRI https://github.com/kubernetes/enhancements

**Comment by yuzp1996** [comment]
So if this means we can't use DCT with k8s simply
