### ISSUE TITLE
Ability to configure TCP Load Balancers on GKE

### ISSUE THREAD

**Issue by seeruk** [kubernetes/kubernetes#92623]
**What would you like to be added**:

Many other cloud providers allow their load balancers to be configured via annotations (for example; Alibaba Cloud, AWS, Azure, DigitalOcean, Scaleway - in fact, these are all of the other clouds I've check so far, and _all_ of them support this kind of configuration).

One of the things that's extremely handy with this configuration is being able to do things like configure the health check that's created for a load balancer. Currently with TCP load balancers in GKE most of the configuration is [hard coded](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L77).

It's possible to use the (configurable) GKE ingress controller to make an L7 load balancer, but there are many advantages to using the L4 load balancer; for example, not having for pay for Cloud Armor to protect the load balancer and just being able to rely on firewall rules, and just in general it being a TCP load balancer makes it more flexible.

**Why is this needed**:

At the moment if you want to configure these things you cannot rely on the built-in mechanisms provided by Kubernetes. In a project I'm working on I'm now considering automating the creation of a load balancer with Terraform using the output of a node pools resource (to grab the instance group URLs), then using a NodePort service that will be hit by a backend's health check. The other approach I've considered is building a Kubernetes controller that watches out for services of type NodePort with a specific annotation then creates a load balancer for you using other annotations on the service to configure it.

This feels like something that should be handled within Kubernetes though, as it is for the majority of the other major cloud providers. It's a lot more difficult on GKE. I believe it would be a huge boon to be able to configure TCP load balancers created in GKE via LoadBalancer type services.

**Comment by BenTheElder** [comment]
GKE has https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig for some of these things that would otherwise often be annotations / labels.

In general new features are discouraged from the in-tree cloud providers, as they're actively being moved out of tree.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180530-cloud-controller-manager.md#motivation

https://github.com/kubernetes/cloud-provider-gcp

**Comment by BenTheElder** [comment]
/area provider/gcp
@cheftako how is this being handled now, are we tracking this sort of thing here or cloud-provider-gcp?

**Comment by cheftako** [comment]
I think its fine to track it here for now but we will want to make sure the fix is applied to both until we finalize the cutover.

**Comment by andrefsp** [comment]
Hi there. I belive I've hit a relatable situation. In my case I would like to be able to create a service type load balancer that only forwards traffic to a specific node pool. 

On GKE, when Service `type: LoadBalancer` is created, it will create a load balancer that forwards traffic to all nodes of the cluster. This will work fine if the Serve `externalTrafficPolicy` is set to `Cluster` but if is set to `Local` instead than it will break the load balancer healh checks. 

Idealy, being able to configure the Load Balancer setup via annotations would give another level of control and help to fix this particular issue. In my case I would like to be able to configure the load balancer to only forward traffic to a specific node pool and not to all cluster. 

I did some research on this and couldn't find any way to do it so decided to leave my feedback on this issue.  

Thanks
