### ISSUE TITLE
Node memory and cpu capacity inside limited LXD container detected wrong

### ISSUE THREAD

**Issue by Jetman80** [kubernetes/kubernetes#92638]
**What happened**:
Node memory and cpu capacity inside limited LXD container detected from the host machine. Resources allocation depends on node capacity. If the node runs inside limited LXD container actual resource limits are applied by linux internals (cgroups, LXD etc), but k8s will try to allocate more resources than available to the node container as capacity is detected from the LXD host.

**What you expected to happen**:
Node memory and cpu capacity should be detected correctly inside limited LXD container.

**How to reproduce it (as minimally and precisely as possible)**:
1. Limit LXD container that is used as k8s node:
```
lxc config show --expanded node_container
...
  limits.cpu: "8"
  limits.memory: 36864MB
...
```

2. Check limits inside linux container:
```
free
              total        used        free      shared  buff/cache   available
Mem:       36000000     1973300    31964928        3532     2061772    34026700

cat /sys/fs/cgroup/memory/memory.limit_in_bytes
36864000000

cat /proc/meminfo
MemTotal:       36000000 kB
...

nproc 
8

cat /proc/cpuinfo | grep processor
processor       : 0
processor       : 1
processor       : 2
processor       : 3
processor       : 4
processor       : 5
processor       : 6
processor       : 7
```

3. Check limits with node describe (detected without limits):
```
kubectl describe node node_container
...
Capacity:
  cpu:                24
...
  memory:             132020268Ki
...
```

4. Check kubelet logs (detected without limits):
```
docker logs kubelet 2>&1 | grep -i capacity
I0627 14:53:54.748567   10484 manager.go:193] Machine: {NumCores:24 ... MemoryCapacity:135188754432
```

Kubelet detects 24 cpu cores and 128 gb ram - as on host machine outside container while normal linux utilites show limited resources: 8 cpu and 36 gb ram.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: dedicated server
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): Linux 4.15.0-106-generic
- Install tools: rke

**Comment by BenTheElder** [comment]
The resource detection comes from cAdvisor. https://github.com/google/cadvisor
This same issue happens in a docker container.

Last I spoke to SIG node members, this is not officially supported (running kubelet in a container). It used to be supported to run "containerized" kubelet as in kubelet intentionally managing an underlying host but running / delivered itself via a container, but this was removed and while in use by some is not supported.

**Comment by Jetman80** [comment]
After some additional research I've found it is not a kubelet issue, but docker issue. Docker sees host's /proc fs even in LXD container. There is a workaround: https://github.com/rancher/rancher/issues/21057 .

**Comment by wirwolf** [comment]
@BenTheElder in v1.19.4 this bug already exist. After merge https://github.com/kubernetes/kubernetes/pull/92967 my node display all cpus in host machine
host mashine:
```
grep -c processor /proc/cpuinfo
12
```
lxc container
```
grep -c processor /proc/cpuinfo
4
```
in docker container where run kubelet
```
grep -c processor /proc/cpuinfo
4
```
logs kubelet:
```
I1202 08:50:29.885465 2916759 manager.go:213] Machine: {Timestamp:2020-12-02 08:50:29.885051244 +0000 UTC m=+0.122488081 NumCores:12 NumPhysicalCores:4 NumSockets:1 CpuFrequency:3600000 MemoryCapacity:8192000000
```

kubectl describe node node-worker-1************
```
Capacity:
  cpu:                12
  ephemeral-storage:  48000104Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             8000000Ki
  pods:               110
```

**Comment by wirwolf** [comment]
when i run kubelet in lxc container without docker I see the same logs.
```
I1202 16:27:24.759024 1002003 manager.go:213] Machine: {Timestamp:2020-12-02 16:27:24.758748194 +0000 UTC m=+0.110518340 NumCores:12 NumPhysicalCores:3 NumSockets:1
```
