### ISSUE TITLE
Add cron syntax in the cheatsheet for the certifications or not

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes/kubernetes#92636]
**What would you like to be added**:
Add CronJob full syntax at [https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs) and also in the [CheatSheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet)

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * * <command to execute>

Ex, the line below states that the job must be scheduled every friday as well as the 13th of each month at midnight :

0 0 13 * 5 

Entry | Description | Equivalent to
-- | -- | --
@yearly (or @annually) | Run once a year at midnight of 1 January | 0 0 1 1 *
@monthly | Run once a month at midnight of the first day of the month | 0 0 1 * *
@weekly | Run once a week at midnight on Sunday morning | 0 0 * * 0
@daily (or @midnight) | Run once a day at midnight | 0 0 * * *
@hourly | Run once an hour at the beginning of the hour | 0 * * * *
@reboot | Run at startup | N/A

Required | Allowed values | Allowed special characters | Remarks
-- | -- | -- | --
Minutes | Yes | 0-59 | * , - |  
Hours | Yes | 0-23 | * , - |  
Day of month | Yes | 1-31 | * , - ? L W | ? L W only in some implementations
Month | Yes | 1-12 or JAN-DEC | * , - |  
Day of week | Yes | 0-6 or SUN-SAT | * , - ? L # | ? L # only in some implementations
Year | No | 1970-2099 | * , - | This field is not supported in standard/default implementations

Comma ( , )
Commas are used to separate items of a list. For example, using "MON,WED,FRI" in the 5th field (day of week) means Mondays, Wednesdays and Fridays.

Dash( - )
Dash defines ranges. For example, 2000-2010 indicates every year between 2000 and 2010, inclusive.
Percent ( % )

Percent-signs (%) in the command, unless escaped with backslash (\), are changed into newline characters, and all data after the first % are sent to the command as standard input.[13]

Non-standard characters
The following are non-standard characters and exist only in some cron implementations, such as the Quartz Java scheduler.

L
'L' stands for "last". When used in the day-of-week field, it allows specifying constructs such as "the last Friday" ("5L") of a given month. In the day-of-month field, it specifies the last day of the month.

Slash (/)
In vixie-cron, slashes can be combined with ranges to specify step values.[3] For example, */5 in the minutes field indicates every 5 minutes 

Hash (#)
'#' is allowed for the day-of-week field, and must be followed by a number between one and five. It allows specifying constructs such as "the second Friday" of a given month.[14] For example, entering "5#3" in the day-of-week field corresponds to the third Friday of every month.

**Why is this needed**:
 it would be unfair for anyone clearing the CKAD & CKA exams, to fails some questions just because people do not remeber the syntax.

/sig docs

**Comment by shekhar-rajak** [comment]
Thanks! This is really informative and definitely help to beginners. I would like to add some general examples and use the same format as https://crontab.guru/

Can I work on this?

**Comment by ezYakaEagle442** [comment]
@shekhar-rajak  thanks for your reply, yes please feel free to work on it !

**Comment by StephanDollberg** [comment]
Does k8s actually support those extended features (# offset etc)?

Can't find it in the docs anywhere.

**Comment by prochac** [comment]
@StephanDollberg 
Looks like K8s uses github.com/robfig/cron/v3 for CronJobs
https://github.com/kubernetes/kubernetes/blob/master/go.mod#L63
And it doesn't support the extended cron syntax.
https://go.dev/play/p/U9inCPgTbdI

**Comment by sftim** [comment]
/transfer website

BTW, there is no (permitted) cheatsheet for the Kubernetes certifications. The term “cheat sheet” means a handy lookup and not a guide to answering a specific exam.
