### ISSUE TITLE
Add tips in the cheatsheet for the certifications or not

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes/kubernetes#92635]
**What would you like to be added**:
sometime the copy&paste from [https://github.com/kubernetes](https://github.com/kubernetes) does not work in VI due to indentation issues, the VIM tip below fixes the issue.

```sh

# set ts=2 : ts stands for tabstop. It sets the tab width to 2 spaces.
# sts stands for softtabstop. Insert ou delete 2 spaces with tab or back keys.
# sw stands for shiftwidth. Number of spaces used during indentation > or <
# set et : et stands for expandtab. While in insert mode, it replaces tabs by spaces
vi ~/.vimrc
set ts=2 sw=2
. ~/.vimrc

alias kn='k config set-context --current --namespace '

export gen="--dry-run=client -o yaml"
# ex: k run nginx --image nginx $gen

# Get K8S resources
alias kp="k get pods -o wide"
alias kd="k get deployment -o wide"
alias ks="k get svc -o wide"
alias kno="k get nodes -o wide"

# Describe K8S resources 
alias kdp="k describe pod"
alias kdd="k describe deployment"
alias kds="k describe service"

```

**Why is this needed**:
That can help developers to be more efficient but also anyone clearing the CKAD & CKA exams, it is unfair to waste time during the exam just because people do not know those tips.

**Comment by ezYakaEagle442** [comment]
# if kubelet process ois not running, see kubelet service status
systemctl status kubelet.service 
 #kubelet service did not start, start the service and observe
systemctl start kubelet.service 
 # Start properly, enable service
systemctl enable kubelet.service

**Comment by shekhar-rajak** [comment]
We can surely use these Shortcuts like general shortcuts. so should we add this into the section https://kubernetes.io/docs/reference/kubectl/cheatsheet/ 

I am interested to work on this. Can I assign it to myself ?

**Comment by ezYakaEagle442** [comment]
@shekhar-rajak  thanks for your reply, yes please feel free to work on it !
