### ISSUE TITLE
describe returns results when the name is an incomplete match, inconsistently to `kubectl get`

### ISSUE THREAD

**Issue by robevansuk** [kubernetes/kubernetes#92648]
**What happened**: `kubectl describe secret [partial secret name]` returns the closest match eg. if the full secret name is `default-token`, then using `default` will return successfully

**What you expected to happen**: expected a `Error from server (NotFound): secrets "default" not found` response type as for other types of get/describe

**How to reproduce it (as minimally and precisely as possible)**: create a secret with a name of your choosing (with or without namespace) and then do a describe on the resource using only a part of the full secret name:
eg.

```bash
kubectl get secrets
NAME                  TYPE                                  DATA   AGE
default-token-d5dff   kubernetes.io/service-account-token   3      1d
```

```bash
> kubectl get secret default
Error from server (NotFound): secrets "default" not found

> kubectl get secret default-token-d5dff
NAME                  TYPE                                  DATA   AGE
default-token-d5dff   kubernetes.io/service-account-token   3      1d

> kubectl describe secret default
kubectl describe secret default
Name:         default-token-d5dff
Namespace:    default
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: default
              kubernetes.io/service-account.uid: ... data ...

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     119 bytes
token:      ... data ...
```

**Anything else we need to know?**: no

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", ... , BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"...", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: gcloud
- OS (e.g: `cat /etc/os-release`): mac os Mojave 10.14.6
- Kernel (e.g. `uname -a`): Darwin MBP.home 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

**Comment by zhouya0** [comment]
Actually you can see the logic written in `kubectl describe`:
https://github.com/kubernetes/kubernetes/blob/180af4240c42906f072112e7ac7818f4b3574c5a/staging/src/k8s.io/kubectl/pkg/cmd/describe/describe.go#L240-L253
So it behave as designed to, seems not a bug.
What should be discussed:
1. should `kubectl get` behave the same?
2. using `kubectl describe secrets/default` and `kubectl describe secrets default` will have different result.
