### ISSUE TITLE
After the aggregation api is deleted, the deleted api still exists in the kube-apiserver metrics

### ISSUE THREAD

**Issue by DesistDaydream** [kubernetes/kubernetes#92671]
**What happened**:
After the aggregation api is deleted, the deleted api still exists in the kube-apiserver metrics
```
[root@master-3 ~]# kubectl get apiservices.apiregistration.k8s.io 
NAME                                   SERVICE                         AVAILABLE   AGE
v1.                                    Local                           True        37d
v1.admissionregistration.k8s.io        Local                           True        37d
v1.apiextensions.k8s.io                Local                           True        37d
v1.apps                                Local                           True        37d
v1.authentication.k8s.io               Local                           True        37d
v1.authorization.k8s.io                Local                           True        37d
v1.autoscaling                         Local                           True        37d
v1.batch                               Local                           True        37d
v1.coordination.k8s.io                 Local                           True        37d
v1.monitoring.coreos.com               Local                           True        23h
v1.networking.k8s.io                   Local                           True        37d
v1.rbac.authorization.k8s.io           Local                           True        37d
v1.scheduling.k8s.io                   Local                           True        37d
v1.storage.k8s.io                      Local                           True        37d
v1alpha1.install.istio.io              Local                           True        23h
v1alpha1.rbac.istio.io                 Local                           True        23h
v1alpha2.config.istio.io               Local                           True        12d
v1alpha3.networking.istio.io           Local                           True        23h
v1beta1.admissionregistration.k8s.io   Local                           True        37d
v1beta1.apiextensions.k8s.io           Local                           True        37d
v1beta1.authentication.k8s.io          Local                           True        37d
v1beta1.authorization.k8s.io           Local                           True        37d
v1beta1.batch                          Local                           True        37d
v1beta1.certificates.k8s.io            Local                           True        37d
v1beta1.coordination.k8s.io            Local                           True        37d
v1beta1.custom.metrics.k8s.io          monitoring/prometheus-adapter   True        18h
v1beta1.discovery.k8s.io               Local                           True        37d
v1beta1.events.k8s.io                  Local                           True        37d
v1beta1.extensions                     Local                           True        37d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        34h
v1beta1.networking.istio.io            Local                           True        23h
v1beta1.networking.k8s.io              Local                           True        37d
v1beta1.node.k8s.io                    Local                           True        37d
v1beta1.policy                         Local                           True        37d
v1beta1.rbac.authorization.k8s.io      Local                           True        37d
v1beta1.scheduling.k8s.io              Local                           True        37d
v1beta1.security.istio.io              Local                           True        23h
v1beta1.storage.k8s.io                 Local                           True        37d
v2beta1.autoscaling                    Local                           True        37d
v2beta2.autoscaling                    Local                           True        37d
```
`v1beta1.external.metrics.k8s.io`  This api still exists in metrics
```
[root@master-3 ~]# curl -s --cacert /etc/kubernetes/pki/ca.crt -H "Authorization: Bearer `kubectl get secrets -n monitoring prometheus-k8s-token-rft2s --template={{.data.token}} | base64 -d`" https://10.0.9.203:6443/metrics | grep external
aggregator_openapi_v2_regeneration_count{apiservice="v1beta1.external.metrics.k8s.io",reason="add"} 0
aggregator_openapi_v2_regeneration_count{apiservice="v1beta1.external.metrics.k8s.io",reason="delete"} 0
aggregator_unavailable_apiservice{name="v1beta1.external.metrics.k8s.io"} 1
```

**What you expected to happen**:
I hope that the metrics of apiserver can synchronously clean up the deleted api

**How to reproduce it (as minimally and precisely as possible)**:
Create a new API and then delete it

**Anything else we need to know?**:
I have tried restarting kube-apiserver, this can solve the problem, but restarting kube-apiserver is not a good solution

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):3.10.0-1062.1.1.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
I'm pretty sure that once a given series is created, it cannot be removed. 

cc @logicalhan

**Comment by DesistDaydream** [comment]
Such useless data will generate useless alerts。
I have no choice but to restart kube-apiserver or silences the alart。

**Comment by DesistDaydream** [comment]
Such useless data will generate useless alerts。
I have no choice but to restart kube-apiserver or silences the alerts。

**Comment by yue9944882** [comment]
metrics are resettable by sending `DELETE` requests to the `/metrics` endpoint

**Comment by liggitt** [comment]
> metrics are resettable by sending DELETE requests to the /metrics endpoint

Is it possible for the API server to automatically delete specific series when the API objects driving those series are removed?

**Comment by DesistDaydream** [comment]
> metrics are resettable by sending `DELETE` requests to the `/metrics` endpoint

I tried as follows:
1.delete API
```
[root@master ~]# kubectl delete apiservices.apiregistration.k8s.io v1beta1.custom.metrics.k8s.io
apiservice.apiregistration.k8s.io "v1beta1.custom.metrics.k8s.io" deleted
```
2.reset metrics
```
[root@master ~]# curl -XDELETE --cacert /etc/kubernetes/pki/ca.crt -H "Authorization: Bearer `kubectl get secrets default-token-gxdr8 --template={{.data.token}} | base64 -d`" https://10.10.100.150:6443/metrics
metrics reset
```
3.But the series is still
```
[root@master ~]# curl -s --cacert /etc/kubernetes/pki/ca.crt -H "Authorization: Bearer `kubectl get secrets default-token-gxdr8 --template={{.data.token}} | base64 -d`" https://10.10.100.150:6443/metrics | grep "v1beta1.custom.metrics.k8s.io"
aggregator_openapi_v2_regeneration_count{apiservice="v1beta1.custom.metrics.k8s.io",reason="add"} 0
aggregator_openapi_v2_regeneration_count{apiservice="v1beta1.custom.metrics.k8s.io",reason="delete"} 0
aggregator_unavailable_apiservice{name="v1beta1.custom.metrics.k8s.io"} 0
aggregator_unavailable_apiservice_count{name="v1beta1.custom.metrics.k8s.io",reason="MissingEndpoints"} 27
```

**Comment by logicalhan** [comment]
> I'm pretty sure that once a given series is created, it cannot be removed.

It is possible to remove a series after creation but this isn't something we currently support as an API.

> metrics are resettable by sending `DELETE` requests to the `/metrics` endpoint

There are some **HUGE** caveats to that statement though.

1. Only a subset of metrics are resettable (and even that subset is not consistent).
2. This is a non-standard, undocumented API which means there is no explicit contract that should allow one to believe this is something one can depend on. 
3. This API is only exposed on apiserver metrics endpoint (where it is undocumented).

Historically, this behavior was snuck in with the [enable-profiling feature](https://github.com/kubernetes/kubernetes/blob/v1.18.4/staging/src/k8s.io/apiserver/pkg/server/options/feature.go#L45-L46) (see [also this](https://github.com/kubernetes/kubernetes/blob/v1.18.4/staging/src/k8s.io/apiserver/pkg/server/config.go#L701-L703)), which is "supposed" to just enable pprof. 

I suspect it's likely to have been inserted to make perf/scale testing easier but it should not have been exposed like this. This is an unstable, mostly unpredictable (unless you actually read the code), completely undocumented API which you should definitely not be relying on in a production environment. 

> Such useless data will generate useless alerts。
> I have no choice but to restart kube-apiserver or silences the alerts。

It isn't logically necessary for those to be your only two options. I have not seen your alert configuration but from the information that is present to me at this very moment, it is also possible that this is a poorly written alert.

**Comment by logicalhan** [comment]
What is your alert condition?

**Comment by DesistDaydream** [comment]
> What is your alert condition?

like this: `sum by(name, namespace) (sum_over_time(aggregator_unavailable_apiservice[5m])) > 0`

For example, I created some test API and deleted them after the aggregation failed, but these deleted API will still generate alert

**Comment by logicalhan** [comment]
You want to use `rate` here. If your condition is the change in the metric value between some past point and now, then it will only alert for that window of time (events age out of the window).

**Comment by DesistDaydream** [comment]
Thankful.Chang the rules can prevent useless alerts.

**Comment by logicalhan** [comment]
What makes it not suitable for monitoring availability? I don’t quite understand what you are saying..

**Comment by logicalhan** [comment]
Also when I said ‘rate’, I actually meant ‘delta’.

**Comment by DesistDaydream** [comment]
e.g.`aggregator_unavailable_apiservice{name="v1beta1.metrics.k8s.io"}`  The value of this sample is 1 for 5 minutes. Then a promQL like `rate(aggregator_unavailable_apiservice[5m])` cannot accurately indicate whether the API has been successfully aggregated

**Comment by logicalhan** [comment]
Use delta. This tells you if, in the last X minutes, how much more you have increased in your accumulated unavailability. Also, this metric technically never has to tell you if you’re available, it only count unavailable data points. 

If you use ‘sum’ and compare against the value 0. Then you’ve asked for the situation you are encountering, which is fire once and never reset.

**Comment by DesistDaydream** [comment]
`delta` similar.
e.g.
I modified the configuration at 14:30 to make the API aggregation fail
The sample value of my query at 14:34 is not 0, and an alarm is generated at this time. But when the sample value of my query at 14:40 is 0 again, this alart disappears, but in fact, API aggregation still fails.

**Comment by logicalhan** [comment]
Ah, I misunderstood which metric you are using in your underlying query, I thought you were using the counter but it sounds like you are alerting off of the gauge. The gauge should indeed update to a zero value (I think) when an aggregation apiservice is deleted. I’ll poke around tomorrow to see why it’s broken.

**Comment by dgrisonnet** [comment]
I am also hitting this issue. Upon an aggregated apiservice deletion, the `aggregator_unavailable_apiservice` gauge is not set to 0.

/remove-lifecycle stale

**Comment by dgrisonnet** [comment]
I don't think setting the gauge to 0 is the best option we have here. A zero value would mean that the aggregated apiservice is available, which is wrong since it will not exist anymore. This solution would indeed fix the problem we have with the alert firing, but having incorrect information here might be problematic in the future.

To me, the `aggregator_unavailable_apiservice` metric is like a Prometheus `up` metric and, as such, should follow the same behavior. This means that upon the deletion of its related service, the metric should not exist anymore.

@logicalhan you mentioned that deleting series is not currently supported by the API. To me knowledge, it should be possible via a custom Collector implementation. Instead of having the availability of the aggregated apiservice in a GaugeVec, we could store this information in a map, and then during collection, manually create the series with `NewLazyConstMetric`. With this implementation, upon deletion, we could delete the apiservice from the map, which will result in its availability not being exposed anymore.

**Comment by DesistDaydream** [comment]
> I don't think setting the gauge to 0 is the best option we have here. A zero value would mean that the aggregated apiservice is available, which is wrong since it will not exist anymore. This solution would indeed fix the problem we have with the alert firing, but having incorrect information here might be problematic in the future.
> 
> To me, the `aggregator_unavailable_apiservice` metric is like a Prometheus `up` metric and, as such, should follow the same behavior. This means that upon the deletion of its related service, the metric should not exist anymore.
> 
> @logicalhan you mentioned that deleting series is not currently supported by the API. To me knowledge, it should be possible via a custom Collector implementation. Instead of having the availability of the aggregated apiservice in a GaugeVec, we could store this information in a map, and then during collection, manually create the series with `NewLazyConstMetric`. With this implementation, upon deletion, we could delete the apiservice from the map, which will result in its availability not being exposed anymore.

I agree think that after deleting the specified API,the metric should not exist anymore.It is more elegant to let the API delete the series.

**Comment by wyf010530** [comment]
Nb
