### ISSUE TITLE
Get Kubelet address from kubelet config during node e2e tests

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92672]
There is a todo in the node e2e test suite to obtain the kubelet address from the kubelet config
https://github.com/kubernetes/kubernetes/blob/e4ece47f2ff403b28ffeed44eb5cf97d2aa219a6/test/e2e_node/util.go#L61-L62

The kubelet address is used in https://github.com/kubernetes/kubernetes/blob/e4ece47f2ff403b28ffeed44eb5cf97d2aa219a6/test/e2e_node/util.go#L77

The kubelet flag is itself deprecated, 

> --address 0.0.0.0
> The IP address for the Kubelet to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces) (default 0.0.0.0) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ , so we could get it from the kubelet config.

/help wanted
/good-first-issue

**Comment by knabben** [comment]
@alejandrox1 can I give it a try?
