### ISSUE TITLE
Document node e2e workflow

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92673]
I think it would be useful to explain exactly how node e2e tests are executed.
It isn't the easiest thing in the world to understand the flow of data through the e2e node test binary.
This would also help untangle everything that is done to get the tests running which will simplify the code and make it a bit easier to know what is going on during in the up stage of tests.

The entry point into the e2e node test binary is https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_node_suite_test.go
Everything else is ginkgo magic which we should explain somewhere.

/help wanted
/good-first-issue
/sig node

**Comment by knabben** [comment]
Initial enumeration of tests by context categorization

https://docs.google.com/spreadsheets/d/1KcQPwfg5K2X1ilbAmu1_iPcmXneDte0NX6-O5dF_1yE/

**Comment by knabben** [comment]
@alejandrox1 just bought some initial code walk and diagrams for the suite run:

https://docs.google.com/document/d/10EKyu4kTo3x7mei2TuGuW8AYeld1EuuSj91AvYNVGX4/

After some parsing, there's a list of highlevel Ginkgo context tests from the node_e2e folder here:
https://docs.google.com/spreadsheets/d/1KcQPwfg5K2X1ilbAmu1_iPcmXneDte0NX6-O5dF_1yE/

A curious thing is that for a local run all e2e specs come in place, so it has around 325 tests.

**Comment by alejandrox1** [comment]
@knabben thank you so much for all your work here!!!
The list of tests is great and is going to come in handy to plan work for sig node!
I'm gonna start reviewing the documentation that you put together as well.

**Comment by alejandrox1** [comment]
/remove-help
presented this on the CI node meeting so back on reviewing this

**Comment by alejandrox1** [comment]
@knabben been meaning to ask: how did you compile https://docs.google.com/spreadsheets/d/1KcQPwfg5K2X1ilbAmu1_iPcmXneDte0NX6-O5dF_1yE/edit#gid=0 ?
Did you do it by hand? :eyes:

**Comment by knabben** [comment]
> @knabben been meaning to ask: how did you compile https://docs.google.com/spreadsheets/d/1KcQPwfg5K2X1ilbAmu1_iPcmXneDte0NX6-O5dF_1yE/edit#gid=0 ?
> Did you do it by hand? 👀

I had put a bunch of regex to extract the CSV, here is the code:

https://gist.github.com/knabben/0181a90e8a131d58a55f59c2bee9f494

**Comment by alejandrox1** [comment]
For the sake of iterating, let's call this one as done thanks to https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/test-suite.md

We can add more info into that doc but the big idea is there.
Next let's explore how we can cleanup and do some maintenance on the node test suite itself :heart: 
/close

**Comment by alejandrox1** [comment]
@knabben thank you for your work here!
