### ISSUE TITLE
Cleanup e2e_node/jenkins

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#92674]
There are some leftover test artifacts from the time when e2e tests were executed with Jenkins.
The artifacts can be found here https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node/jenkins

We should look into these files and see
* what do we need to move elsewhere?
* what needs to be updated?
* what can we delete?

/help wanted
/good-first-issue
/sig node

**Comment by mayankshah1607** [comment]
@alejandrox1 I'd like to give this a try!

**Comment by alejandrox1** [comment]
Thank you @mayankshah1607 
Please reach out if you have any questions. I'll also will swing by to see how things are going :smile:

**Comment by alejandrox1** [comment]
Hi @mayankshah1607 , wanted to ping you on this again to check how things are going.
Do you need any help?

**Comment by mayankshah1607** [comment]
Hi @alejandrox1 
Should we be moving the `gci-init.yaml` and `cos-init-live-restore.yaml` files to `test-infra/jobs/e2e_node`? I see that they're being used for various configs. 
It also seems like we can delete `docker-validation/` (it is being handled in `test-infra/jobs/e2e_node/benchmark_config.yaml`) and `conformance/`

**Comment by leilajal** [comment]
@mayankshah1607 Hi I'm interested to know the status of this

**Comment by piyushsingariya** [comment]
@mayankshah1607 Any updates over this? I'm interested in working on this??

**Comment by mayankshah1607** [comment]
@piyushsingariya Please feel free to take this up! :)

**Comment by Aut0R3V** [comment]
Hey this looks intresting, I can take this up if no one's working on it

**Comment by Kappie37** [comment]
Right now, I speak for a group of students from Delft University of Technology. As part of a course, we want to contribute to Kubernetes. This issue seemed like a good start. Is there any more information we can use to fix this issue?

**Comment by Kappie37** [comment]
Dear @alejandrox1 @krzyzacy,

We were looking at this issue and observed that in test-infra (https://github.com/kubernetes/test-infra/tree/master/jenkins) Jenkins is dead. Why can we not delete these remaining test artifacts from the time when e2e tests were executed with Jenkins? If it is not possible/wise to delete, how can we figure out what needs to be preserved?

Do you need us to rewrite the Jenkins tests into the Prow CI/CD system?

**Comment by SergeyKanzhelev** [comment]
/assign @Kappie37 

(since you sent the PR)

**Comment by pacoxu** [comment]
> @alejandrox1 is someone working on it...can i help in some way?

@SaNsK11 #99606 is the PR to fix this issue.

**Comment by SergeyKanzhelev** [comment]
/close

in favor of https://github.com/kubernetes/kubernetes/issues/106119 which @endocrimes self-assigned.
