### ISSUE TITLE
Kubeadm upgrade from 1.18.4-00 to 1.18.5-00 fails on Ubuntu 20.04 due to unmet dependencies and package conflicts

### ISSUE THREAD

**Issue by HubbeKing** [kubernetes/kubernetes#92698]
**What happened**:
When attempting to upgrade the control-plane nodes of kubeadm cluster running on Ubuntu 20.04 from kubeadm 1.18.4-00 to 1.18.5-00, the upgrade fails because of an unmet dependency on kubernetes-cni >= 0.8.6, which is not possible to install because of a conflict with kubelet 1.18.4-00. 
I suspect the only way to resolve this would be to upgrade both kubeadm and kubelet at the same time, but this would likely break the cluster. 

```
root@acerslab:~# apt-mark unhold kubeadm && apt-get update && apt-get install -y kubeadm=1.18.5-00 && apt-mark hold kubeadm
Canceled hold on kubeadm.
Hit:1 http://fi.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://fi.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://fi.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://fi.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (>= 0.8.6)
E: Unable to correct problems, you have held broken packages.
```
```
root@acerslab:~# apt-mark unhold kubeadm && apt-get update && apt-get install -y kubeadm=1.18.5-00 kubernetes-cni=0.8.6-00 && apt-mark hold kubeadm
Canceled hold on kubeadm.
Hit:1 http://fi.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://fi.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://fi.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://fi.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubelet : Conflicts: kubernetes-cni
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**What you expected to happen**:
A clean upgrade, according to the procedure laid out in https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**How to reproduce it (as minimally and precisely as possible)**:
- Set up a kubeadm cluster on Ubuntu 20.04 using the 1.18.4-00 packages following https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
- Ensure `kubeadm`, `kubelet`, and `kubectl` packages are set on hold (`apt-mark hold kubeadm kubelet kubectl`)
- Attempt to upgrade to 1.18.5-00 using the official upgrade guide https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Anything else we need to know?**:
The same issue occurs when trying to upgrade from 1.18.4-00 to 1.18.4-01, if one follows the official kubeadm upgrade guide.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
root@acerslab:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: 
Bare metal cluster: 1 control-plane node (x86_64) + 2 worker nodes (x86_64) all running Ubuntu 20.04 LTS
```
root@acerslab:~# kubectl get nodes -o wide
NAME        STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
acerslab    Ready    master   41d   v1.18.4   192.168.1.224   <none>        Ubuntu 20.04 LTS   5.4.0-37-generic   docker://19.3.8
galactica   Ready    worker   41d   v1.18.4   192.168.1.213   <none>        Ubuntu 20.04 LTS   5.4.0-37-generic   docker://19.3.8
valkyrie    Ready    worker   27d   v1.18.4   192.168.1.237   <none>        Ubuntu 20.04 LTS   5.4.0-37-generic   docker://19.3.8
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`): 
`Linux acerslab 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
`apt` and `kubeadm`
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mksmsrgnk** [comment]
I have similar issue on Debian GNU/Linux 10 (buster)

**Comment by HubbeKing** [comment]
I'm assuming one could sidestep this by draining a node, forcing an upgrade to 1.18.4-01 for `kubeadm`, `kubelet` and `kubectl` for that node, and then rebooting the node or restarting its kubelet before uncordoning and continuing with the remaining nodes. 

Since 1.18.4-01 is still a 1.18.4 version, no changes should need to be made to the cluster configuration. I have no idea what kind of effect this might have on a production cluster, though.

**Comment by jasongol** [comment]
I can confirm that the same issue exists on Ubuntu 18.04.

**Comment by justaugustus** [comment]
/assign @saschagrunert 

Sascha -- can you take a look or assign to someone on @kubernetes/release-engineering to investigate?

The following issues are similar classes of issues for apt/yum:
- https://github.com/kubernetes/kubernetes/issues/92698
- https://github.com/kubernetes/kubernetes/issues/92587
- https://github.com/kubernetes/kubernetes/issues/92586
- https://github.com/kubernetes/kubernetes/issues/92463

**Comment by saschagrunert** [comment]
@HubbeKing @jasongol do you have a simple reproducer within a container?
I tested both package upgrade paths which were successful:
- kubeadm (1.18.5-00) over (1.18.4-01)
- kubeadm (1.18.5-00) over (1.18.4-00)
Even the downgrades work for me. Do I miss anything?

**Comment by HubbeKing** [comment]
@saschagrunert 
I can still trigger the same issue in an ubuntu-based docker container - see below snippet for Dockerfile

```
FROM ubuntu:focal-20200606

RUN apt-get update && apt-get install -y apt-transport-https curl gnupg software-properties-common
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-add-repository 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
RUN apt-get update
RUN apt-get install -y kubelet=1.18.4-00 kubeadm=1.18.4-00 kubectl=1.18.4-00
RUN apt-mark hold kubelet kubeadm kubectl

RUN apt-get install -y --allow-change-held-packages kubeadm=1.18.5-00
```

**Comment by jasongol** [comment]
@saschagrunert, thank you for following up.  To be honest, I think my issue may be a different one.  I was using the Ansible [apt](https://docs.ansible.com/ansible/latest/modules/apt_module.html) module, which provides no access to the `--allow-change-held-packages` apt-get flag.  Instead I was trying to use the dpkg option `--force-hold` and that was not successful.

**Comment by jasongol** [comment]
Arg... I spoke too soon.  I tried it again today and can confirm the issue is real.

`FROM ubuntu:bionic

RUN apt-get update && apt-get install -y apt-transport-https curl gnupg software-properties-common
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-add-repository 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
RUN apt-get update
RUN apt-get install -y kubelet=1.18.4-00 kubeadm=1.18.4-00 kubectl=1.18.4-00
RUN apt-mark hold kubelet kubeadm kubectl

RUN apt-get install -y --allow-change-held-packages kubeadm=1.18.5-00`
