### ISSUE TITLE
daemonset controller cannot create pod

### ISSUE THREAD

**Issue by knightXun** [kubernetes/kubernetes#92699]
**What happened**:
Controller cannot create pod, It always report events: `Warning  FailedCreate  12m (x21 over 46m)  daemonset-controller  Error creating: Timeout: request did not complete within requested timeout
`

**Environment**:
linux 
- Kubernetes version (use `kubectl version`):
1.16
- Cloud provider or hardware configuration:
aws
- OS (e.g: `cat /etc/os-release`):
linux

**Comment by liggitt** [comment]
A timeout error often means the api server is unavailable or overloaded. Is your API server available and healthy when you are observing this? If not, ca. You provide relevant API server logs?

**Comment by knightXun** [comment]
nope, the kubernetes is managed by aws. I cannot see anything from apiserver.. aws tells me they change few of kubernetes

**Comment by liggitt** [comment]
Without more information about the state of the API server, this issue will be difficult to investigate.

**Comment by knightXun** [comment]
It's my webhook problem. @liggitt thanks
