### ISSUE TITLE
Potential license conflict

### ISSUE THREAD

**Issue by cjellick** [kubernetes/kubernetes#92704]
I ran an OSS license scan of a codebase that has this project as a dependency and came across an interesting hit.

This go-vhd dependency specified here:
https://github.com/kubernetes/legacy-cloud-providers/blob/1bd57a2af8f3a65a82398a87ce5a99f855e277f1/go.mod#L22
has a snippet of code from StackOverflow which is license under creative commons sharealike. Here's the code in question:
https://github.com/rubiojr/go-vhd/blob/0bfd3b39853cdde5762efda92289f14b0ac0491b/vhd/util.go#L59-L73

I'm not a license expert, so I don't know if there are any real issues/conflicts here or not, but wanted to share to see what you all think. 

Here's SO's license info for reference:
https://creativecommons.org/licenses/by-sa/4.0/

My understanding is that the potential issue would be with this clause:
> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

which could potentially require go-vhd and projects that depend on it to use the Creative Commons license as well.

**Comment by michaelkolber** [comment]
Not a huge difference, but this is likely actually licensed under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/), not 4.0. See https://stackoverflow.com/help/licensing.

**Comment by andyzhangx** [comment]
the k/k code actually does not reference [utf16BytesToString](https://github.com/rubiojr/go-vhd/blob/0bfd3b39853cdde5762efda92289f14b0ac0491b/vhd/util.go#L59-L73), since that function is in https://github.com/rubiojr/go-vhd, do you mean we should remove `rubiojr/go-vhd` from k/k totally?

**Comment by nikhita** [comment]
> the k/k code actually does not reference utf16BytesToString, since that function is in https://github.com/rubiojr/go-vhd, do you mean we should remove rubiojr/go-vhd from k/k totally?

@andyzhangx Yes, we would either need to remove `rubiojr/go-vhd` from k/k _or_ ask the maintainers of  `rubiojr/go-vhd` to update `utf16BytesToString`.

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

This means that `rubiojr/go-vhd` (and k/k if we end up using it) should be licensed until CC-BY-SA.

**Comment by cjellick** [comment]
Would this ultimately be backported to older versions of k8s or would you just do it in 1.19?

**Comment by andyzhangx** [comment]
thanks, Let me remove the `rubiojr/go-vhd` code in v1.19, actually that part of functionality is deprecated in Azure cloud provider already. My initial thought is only do this in v1.19

**Comment by nikhita** [comment]
Since it isn't trivial to remove `github.com/rubiojr/go-vhd` as a dependency entirely, I've created https://github.com/rubiojr/go-vhd/issues/3 upstream to track updating the code there.
