### ISSUE TITLE
Azure provider uses VMSS API instead of metadata service when computer name prefix differs from VMSS name

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes/kubernetes#92733]
**What happened**:
If computer name prefix does not match VMSS name, then Azure cloud provider will use VMSS API instead of using metadata service data. This leads to throttling, because every affected kubelet is making API requests.

**What you expected to happen**:
Azure cloud provider should use metadata service data instead of calling VMSS API when instance is current.

**How to reproduce it (as minimally and precisely as possible)**:
Set computer name prefix of the VMSS to something different than default. You should observe Azure provider making requests to the VMSS API rather than using metadata service, which leads to throttling if you have multiple kubelets with this bug.

**Anything else we need to know?**:
This is bug was introduced by #89138 - `isCurrentInstance` returns false even if instance is current, because it expects
node name to match VMSS name + instance id, however node name is derived from the computer-name-prefix which can be different than VMSS name. Node name should be matched against `{computer-name-prefix}{base-36-instance-id}`, not against `{vmss-name}{base-36-instance-id}`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.x and higher
- Cloud provider or hardware configuration: azure

/sig cloud-provider

**Comment by mateuszlitwin** [comment]
CC @feiskyer

**Comment by neolit123** [comment]
/remove-sig cloud-provider
/sig cloud-provider

(trying to remove the `needs-sig` label)

**Comment by feiskyer** [comment]
@mateuszlitwin Thanks for the reporting. Unfortunately, computer name prefix is not included in IMDS, so it can't be used without VMSS API for constructing the NodeName. Would check what could we do to workaround the issue.

**Comment by mateuszlitwin** [comment]
Can you memorize the computer name prefix in the first request to the Azure API and then use it for the isCurrentInstance check if vmss?

**Comment by feiskyer** [comment]
@mateuszlitwin opened #92793 to fix the issue. Would you like to have a look?

**Comment by mateuszlitwin** [comment]
@feiskyer I can confirm that your change should address the problem I had. Do you know if your fix will be added to 1.18.x?

**Comment by feiskyer** [comment]
@mateuszlitwin  #92814 is working on the cherry pick

**Comment by mateuszlitwin** [comment]
Thank you for quick fix!
