### ISSUE TITLE
Write audit logs when failing open a validating admission webhook request

### ISSUE THREAD

**Issue by cnphil** [kubernetes/kubernetes#92738]
**What would you like to be added**:
The validating admission webhook, when the failing policy is set to Ignore, will fail open a webhook request. Consider write an audit log when a request is allowed by failing open.

**Why is this needed**:
Fail open events SHOULD be audit logged for integrity. For us specifically, we are currently using the image policy webhook which exports an audit log when failed open, and as we'd like to move to validating admission webhook, we'd want the same feature parity.

**Comment by roycaihw** [comment]
I'm not against adding audit log to track fail-open webhook calls, but I wonder if you have tried using the [metrics](https://github.com/kubernetes/kubernetes/blob/82baa26905c94398a0d19e1b1ecf54eb8acb6029/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L142-L150) to detect fail-open events. A fail-open event is equivalent to a "calling_webhook_error" rejection record in the metrics for a webhook with `Ignore` failure policy.

**Comment by cnphil** [comment]
Thanks for the pointer!  Yes, we (GCP Binauthz) will be using the metrics you've pointed there but mostly for our internal monitoring.  However, to our customers, one of the core security benefits of GCP Binauthz is the audit logging and we want to (and have been) expose this to customers.

**Comment by roycaihw** [comment]
Thanks. Having the audit log sounds good to me

**Comment by cnphil** [comment]
/remove-lifecycle stale

Will expedite and merge the PR associated to this issue.
