### ISSUE TITLE
Some scheduled e2e jobs always fail with "e2e-up.sh: exit status 2"

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#92730]
**Which jobs are failing**:

From the [triage dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html#10593569f958de2147a5):

The following jobs failed 100% of the time (as of when this issue was created):

- [ci-containerd-e2e-gci-gce](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce) - hourly
- [ci-containerd-e2e-ubuntu-gce](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce) - hourly
- [ci-cri-containerd-e2e-gce-device-plugin-gpu](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gce-device-plugin-gpu) - every 3 hours
- [ci-cri-containerd-e2e-gce-multizone](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gce-multizone) - every 2 hours
- [ci-cri-containerd-e2e-gce-stackdriver](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gce-stackdriver) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce) - hourly
- [ci-cri-containerd-e2e-gci-gce-alpha-features](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-alpha-features) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-es-logging](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-es-logging) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-flaky](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-flaky) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-ip-alias](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-ip-alias) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-proto](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-proto) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-reboot](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-reboot) - hourly
- [ci-cri-containerd-e2e-gci-gce-sd-logging](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-sd-logging) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-serial](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-serial) - hourly
- [ci-cri-containerd-e2e-gci-gce-slow](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-slow) - hourly
- [ci-cri-containerd-e2e-ubuntu-gce](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-ubuntu-gce) - hourly
- [ci-kubernetes-e2e-containerd-gce-netd](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-containerd-gce-netd) - every 2 hours
- [ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster) - every 2 hours
- [ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster-parallel](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster-parallel) - every 2 hours
- [ci-kubernetes-e2e-gci-gce-netd](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-netd) - every 2 hours
- [ci-kubernetes-e2e-gce-gpu-beta-stable1-cluster-downgrade](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gpu-beta-stable1-cluster-downgrade) - every 12 hours
- [ci-kubernetes-e2e-ubuntu-gce-netd](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-netd) - every 2 hours

The following jobs failed 99% of the time* (as of when this issue was created):

- [ci-cri-containerd-e2e-gci-gce-ingress](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-ingress) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-sd-logging-k8s-resources](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-sd-logging-k8s-resources) - every 2 hours
- [ci-cri-containerd-e2e-gci-gce-statefulset](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-statefulset) - every 2 hours

The following job failed 97% of the time* (as of when this issue was created):
- [ci-kubernetes-e2e-gce-gpu-master-stable1-cluster-downgrade](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gpu-master-stable1-cluster-downgrade) - every 12 hours

*99% and 97% is what triage dashboard reported, but I could not find where they succeeded the 1% or 3% of the time.

**Which test(s) are failing**:
`Up`

**Since when has it been failing**:
Unknown
I went back through the available job history and could not find when they last succeeded.

**Testgrid link**:
See above

**Reason for failure**:
```
error during ./hack/e2e-internal/e2e-up.sh: exit status 2
```

**Anything else we need to know**:

/sig testing

**Comment by brianpursley** [comment]
Not sure on the sig for this. Please reassign if this belongs to a sig other than testing.

**Comment by BenTheElder** [comment]
This means cluster bringup is failing.
SIG testing doesn't own that unless it's KIND.
Why is cluster up failing? Some of the additional artifacts should have details.

**Comment by brianpursley** [comment]
Hmm, I was just about to investigate further when I noticed the jobs have started passing again as of several hours ago...
![image](https://user-images.githubusercontent.com/4977542/86395630-8e6aa680-bc6e-11ea-8303-39c45d8bfb50.png)

I'd still like to find out why, so I'll do a little more investigation and then probably end up closing this I suppose...

**Comment by brianpursley** [comment]
Looks like this PR that was merged about 12 hours ago fixed it:
https://github.com/kubernetes/kubernetes/pull/92562

I'll go ahead and close this since it seems to be fixed now.

**Comment by bsdnet** [comment]
Good to know :)
