### ISSUE TITLE
Duplicate altnames in certs which generated by kubeadm

### ISSUE THREAD

**Issue by QianChenglong** [kubernetes/kubernetes#92751]
**What happened**:

Duplicate altnames in certs which generated by kubeadm
![image](https://user-images.githubusercontent.com/1881126/86348671-8d4b7080-bc92-11ea-8572-8139f09bd609.png)

**What you expected to happen**:

No Duplicate altnames in certs which generated by kubeadm

**How to reproduce it (as minimally and precisely as possible)**:

Anytime

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/1881126/86349875-64c47600-bc94-11ea-8bc6-3767ce0b5d09.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wawa0210** [comment]
Can you describe your detailed usage scenarios and reproduction steps, and explain the kubernetes version so that we can quickly locate

**Comment by QianChenglong** [comment]
> Can you describe your detailed usage scenarios and reproduction steps, and explain the kubernetes version so that we can quickly locate

Thank for you response! 
I have found why and will fix it soon.

**Comment by neolit123** [comment]
i have commented on the PR.

/priority awaiting-more-evidence
