### ISSUE TITLE
[Flaky Test] verify-1.18 (ci-kubernetes-verify-beta)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#92756]
**Which jobs are failing**:

`verify-1.18 (ci-kubernetes-verify-beta)`

**Which test(s) are failing**:

`Overall`

**Since when has it been failing**:

`07-01-20 23:50 PDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-1.18-blocking#verify-1.18

**Reason for failure**:

`Timeout`

Seeing a sudden spike in test-duration across the board.

**Anything else we need to know**:

/cc @kubernetes/ci-signal 
/milestone v1.19
/sig testing
/sig release
/priority critical-urgent

**Comment by hasheddan** [comment]
/retitle [Flaky Test] verify-1.18 (ci-kubernetes-verify-beta)

/remove-kind failing-test
/kind flake
/priority important-soon

**Comment by liggitt** [comment]
verify-1.18 probably doesn't belong in 1.19?

/milestone v1.18

**Comment by liggitt** [comment]
looks like verify-files-remake is taking up to 40 minutes of the 2 hour timeout: https://testgrid.k8s.io/sig-release-1.18-blocking#verify-1.18&graph-metrics=test-duration-minutes&width=20
