### ISSUE TITLE
Automatically re-register node when node is removed from API server

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#92769]
**What would you like to be added**:
Option to automatically re-register node when node is removed from API server without requiring a manual kubelet restart.

**Why is this needed**:
We recently experienced an issue where our etcd database went into read only mode, therefore none of the heartbeats were persisted to the database. When the database restored connectivity, the controllers marked all nodes in our cluster as missing due to timeout of the heartbeats, and removed them from the kubernetes API server. Consequently, kubelet on each node failed to sync the node status as it first attempts to GET the node before updating it, and did not re-register itself with the API until the kubelet process was manually restarted, at which point it rejoined the cluster successfully.

**Comment by liggitt** [comment]
Previously discussed in https://github.com/kubernetes/kubernetes/issues/71398

**Comment by adammw** [comment]
Is this something that should be discussed on this issue or that previous issue reopened? There didn't seem to be a agreed resolution. Exiting the kubelet process with an error code would be sufficient for our use case, as we run under systemd service which can restart the process if this occurs.
