### ISSUE TITLE
informer hang on WaitForCacheSync

### ISSUE THREAD

**Issue by FengXingYuXin** [kubernetes/kubernetes#92777]
process hang on WaitForCacheSync while list node infos accidentally。
code as following：
![image](https://user-images.githubusercontent.com/9688486/86457682-a0c00f80-bd56-11ea-8556-b40c06f148a7.png)

**Comment by liggitt** [comment]
I think the listers/informers must be accessed and set up prior to starting the shared informers

**Comment by FengXingYuXin** [comment]
really thankful. i adjust the shared informers' starting place and resolve it.

**Comment by immunochomik** [comment]
So basically you have to **call nodeSharedInformer.Start() after** setting up all the listeners and stuff (sorry but this was not obvious to me form @liggitt answer).
