### ISSUE TITLE
Enable "--ulimit" option to be passed to "docker run" via k8s pods

### ISSUE THREAD

**Issue by mukuntharajaa** [kubernetes/kubernetes#92778]
**What would you like to be added**:

kubernetes should provide a way to pass "--ulimit" option to "docker run" command. Just like how, memory and cpu resource limits are passed on to docker run command as mentioned [here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run) .

**Why is this needed**:

On bare-metal hardwares, it is generally a good practice to set RLIMIT_AS, RLIMIT_NOFILE, RLIMIT_CORE etc at system-wide. In systemd based distros, this can be done using systemd environment files. Under such situation, if the system wide setting is either too big or not adequate for particular container/pod, then there should be a way to override this.

If it were simple docker container ( without k8s ), one could overwrite systemd`s setting via docker run, 

`docker run --ulimit nofile=1024:52458 --ulimit core=123456 --memory="750m" <image>`

As on date, only 3 resources ( memory, cpu, hugepage) is able to be overridden via kubernetes. Because of this limitation, one has to compromise on good practices on bare-metal hardware where resources are fixed.

**Comment by dims** [comment]
@mukuntharajaa please see https://github.com/kubernetes/kubernetes/issues/3595

/close
