### ISSUE TITLE
Plugins should access listers during instantiation

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#92781]
SelectorSpread plugin currently accesses listers directly from SharedInformer: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/selectorspread/selector_spread.go#L182-L185

The issue is that if we don't access the lister before the informer is started, the lister will never be populated. The informer is started right after scheduler initialization, and so we have to access the listers in the instantiation function New of the plugin.

This should be checkerrypicked to 1.18 as well.

/sig scheduling
/priority important-soon
/assign @adtac

**Comment by liggitt** [comment]
Does this mean we don't have tests demonstrating this functioning?

**Comment by ahg-g** [comment]
> Does this mean we don't have tests demonstrating this functioning?

We do have a multi-zone e2e test that failed this: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/ubernetes_lite.go#L68

We run those in GKE, and that is how we caught this issue, but it seems that we don't run them in OSS?

**Comment by Huang-Wei** [comment]
@adtac similar initialization logic FYI:

https://github.com/kubernetes/kubernetes/blob/a472138c1ffca452ba04ceb5020cc0972c47407a/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L65-L66

And even for regular Informers (e.g., PodInformer), @ahg-g and I are [discussing](https://github.com/kubernetes/kubernetes/pull/92682#discussion_r449327663) that it _may_ be favorable to explicitly initialize it as the internal shared storage is a singleton, so that won't be harmful.

**Comment by ahg-g** [comment]
Wei, I think that looks a little odd. We should just assign it to a member variable of the plugin.

**Comment by Huang-Wei** [comment]
If the lister gets initialized properly (in plugin's New() function), later it can be fetched from the informerFactory. So why keep a redundant member variable in this plugin?

**Comment by liggitt** [comment]
> If the lister gets initialized properly (in plugin's New() function), later it can be fetched from the informerFactory. So why keep a redundant member variable in this plugin?

Keeping a reference to the informer factory beyond initialization leads to accidents like this where an uninitialized lister is accessed. Limiting the informerfactory to initialization time ensures that all used listers are accessed at initialization time.

**Comment by Huang-Wei** [comment]
> Keeping a reference to the informer factory beyond initialization leads to accidents like this where an uninitialized lister is accessed. Limiting the informerfactory to initialization time ensures that all used listers are accessed at initialization time.

In the point of explicity over implicity, I agree, although with a cost of adding duplicate member fields. @ahg-g I think we need to do a thorough check, to ensure this pattern is followed well.
In addition to this issue(`SelectorSpread`), I can refactor `DefaultPreemption`.

**Comment by ahg-g** [comment]
I took a quick a look at all plugins, those are the only two places where this pattern is not followed.

**Comment by adtac** [comment]
@Huang-Wei I can fix this in defaultpreemption too, if that's okay with you.

**Comment by Huang-Wei** [comment]
@adtac that's being worked in #92682, thanks anyway.

**Comment by liggitt** [comment]
are all the changes merged to master for 1.19?

**Comment by Huang-Wei** [comment]
@liggitt Yes, #92840 and #92876 both got merged.

/close

**Comment by ahg-g** [comment]
we are still trying to get his in 1.18 #93026
