### ISSUE TITLE
AWS CloudProvider fails to configure routes when instance has multiple ENIs

### ISSUE THREAD

**Issue by MQasimSarfraz** [kubernetes/kubernetes#92783]
**What happened**:
I tried to create a cluster in AWS with multiple ENIs. I have enabled `configure-cloud-routes`. But `controller-manager` fails to create routes with:
```
I0703 16:20:07.647786       1 event.go:281] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-100-85-137.eu-west-1.compute.internal", UID:"ip-192-168-85-137.eu-west-1.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedToCreateRoute' Could not create route 28075aa1-16b7-45fb-9002-1b200ee9e626 10.234.64.0/24 for node ip-192-168-85-137.eu-west-1.compute.internal after 176.081033ms: error configuring source-dest-check on instance i-0611f469eb822e885: "InvalidInstanceID: There are multiple interfaces attached to instance 'i-0611f469eb822e885'. Please specify an interface ID for the operation instead.\n\tstatus code: 400, request id: db27d9fa-f146-40b4-bca4-5967089d7da9"

```
**What you expected to happen**:
I expected service CIDR routes to be added to AWS route table.
**How to reproduce it (as minimally and precisely as possible)**:
- Deploy K8s in AWS with provider enabled.
- Enable the `configure-cloud-routes`

**Environment**:
- Kubernetes version (use `kubectl version`):
`v.1.17.6`
- Cloud provider or hardware configuration:
`aws`
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```
- Kernel (e.g. `uname -a`):
`5.7.2-1.el8.elrepo.x86_64`

**Comment by knight42** [comment]
I would like to take this.

/assign

**Comment by knight42** [comment]
I have filed PR #92800 to fix this problem.

**Comment by knight42** [comment]
/reopen
/remove-lifecycle rotten

@andrewsykim I think this still needs to be addressed.
