### ISSUE TITLE
[Failing test] kubeadm-kinder-master (ci-kubernetes-e2e-kubeadm-kinder-master)

### ISSUE THREAD

**Issue by sayanchowdhury** [kubernetes/kubernetes#92795]
**Which jobs are failing**:
kubeadm-kinder-master (ci-kubernetes-e2e-kubeadm-kinder-master)

**Which test(s) are failing**:
`[sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]`

**Since when has it been failing**:
`07-03 07:04 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master

**Reason for failure**:
```
 Jul  4 12:37:29.246: FAIL: Unexpected error:
    <*errors.errorString | 0xc0002ec210>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
Full Stack Trace
k8s.io/kubernetes/test/e2e/node.glob..func3.1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/node/events.go:97 +0xa07
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000e3dc20)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x337
k8s.io/kubernetes/test/e2e.TestE2E(0xc000e3dc20)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:145 +0x2b
testing.tRunner(0xc000e3dc20, 0x4cb0590)
	/usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x357 

```

**Anything else we need to know**:
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19
/sig testing

**Comment by sayanchowdhury** [comment]
After digging it seems that the issue might be on the infrastructure side of things. @BenTheElder @RobertKielty Can you have look at it?

**Comment by BenTheElder** [comment]
/remove-sig testing
/sig cluster-lifecycle
SCL owns kinder. I am ~out until Monday.

**Comment by BenTheElder** [comment]
This test went from passing consistently to failing consistently while the rest of the suite is typically green.

That doesn't fit for an infrastructure issue. There's a bug in kubernetes most likely.

**Comment by hasheddan** [comment]
Looks like failure started after this was merged: https://github.com/kubernetes/kubernetes/pull/92750

Don't see how that would be affecting the test that is failing, but the duration spiked dramatically on the subsequent run: https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master&graph-metrics=test-duration-minutes

**Comment by hasheddan** [comment]
Hmm, just saw a successful run this morning :thinking:

**Comment by neolit123** [comment]
> [k8s.io] [sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]

^ the failure seems to be happening in a SIG Node test. it doesn't feel related to the kubeadm / kinder infrastructure itself.

/sig node

**Comment by neolit123** [comment]
it's happening here:
https://github.com/kubernetes/kubernetes/blob/a26f50a52eaf3acae5f7b9ee628f77729dfdf2df/test/e2e/node/events.go#L97-L113
it tries to list scheduler events but fails.

> Hmm, just saw a successful run this morning

yes, there is a green run from today, which is odd.

**Comment by sayanchowdhury** [comment]
I'm seeing flakes in the test for `kubeadm-kinder-upgrade-1-18-master` as well.
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-1-18-master

**Comment by neolit123** [comment]
wondering if this diff is actually what caused it instead (first run is green https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-master):
https://github.com/kubernetes/kubernetes/compare/d7e364ad0...af29f81af

we have 5 commits that make unrelated kubeadm changes.

these commits make event system related changes:

@chelseychen @wojtek-t 
ade2422 Switch event recorder to use events.k8s.io/v1
e54ad20 Remove DeprecatedSource assignment to avoid validation failure

@soulxu @Huang-Wei 
b3741f3 The Pod is eligible to preempt when previous nominanted node is Unsch… …

**Comment by Huang-Wei** [comment]
@neolit123 b3741f3 seems irrelevant as that commit is effective only when a pod has preempted other pods and is being retried.

**Comment by chelseychen** [comment]
Hi @neolit123, The two commits about events were from #92662, which simply replaced all usage of events/v1beta1 in to events/v1, there's nothing about kubeadm, so it should be irrelevant.

**Comment by neolit123** [comment]
@Huang-Wei 
thanks, i can see this not being related.

@chelseychen the failing test seem related to missing scheduler events and not to the kubeadm setup in general.
are we sure that events/v1 and https://github.com/kubernetes/kubernetes/pull/92662 did not introduce mechanical changes that could make the e2e here to fail https://github.com/kubernetes/kubernetes/blob/a26f50a52eaf3acae5f7b9ee628f77729dfdf2df/test/e2e/node/events.go#L97-L113?

**Comment by liggitt** [comment]
the `[k8s.io] [sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]` test passed on https://github.com/kubernetes/kubernetes/pull/92662 in presubmit... 

In the first failure (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1280209832661487616), the e2e test logs this pod:

> Jul  6 19:09:21.511: INFO: &Pod{ObjectMeta:{send-events-79f41286-0e08-4f21-9e08-e808798e21f2  events-9503 /api/v1/namespaces/events-9503/pods/send-events-79f41286-0e08-4f21-9e08-e808798e21f2 fff5d05e-8647-4b87-a99e-a3021d48aa5a 17763 0 2020-07-06 19:09:19 +0000 UTC <nil> <nil> map[name:foo time:469900737] map[cni.projectcalico.org/podIP:192.168.227.94/32] [] []  [{e2e.test Update v1 2020-07-06 19:09:19 +0000 UTC FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:name":{},"f:time":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"p\"}":{".":{},"f:args":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":80,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}} {calico Update v1 2020-07-06 19:09:20 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:cni.projectcalico.org/podIP":{}}}}} {kubelet Update v1 2020-07-06 19:09:21 +0000 UTC FieldsV1 {"f:status":{"f:conditions":{"k:{\"type\":\"ContainersReady\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Initialized\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Ready\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:phase":{},"f:podIP":{},"f:podIPs":{".":{},"k:{\"ip\":\"192.168.227.94\"}":{".":{},"f:ip":{}}},"f:startTime":{}}}}]},Spec:PodSpec{Volumes:[]Volume{Volume{Name:default-token-9vqmb,VolumeSource:VolumeSource{HostPath:nil,EmptyDir:nil,GCEPersistentDisk:nil,AWSElasticBlockStore:nil,GitRepo:nil,Secret:&SecretVolumeSource{SecretName:default-token-9vqmb,Items:[]KeyToPath{},DefaultMode:*420,Optional:nil,},NFS:nil,ISCSI:nil,Glusterfs:nil,PersistentVolumeClaim:nil,RBD:nil,FlexVolume:nil,Cinder:nil,CephFS:nil,Flocker:nil,DownwardAPI:nil,FC:nil,AzureFile:nil,ConfigMap:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Projected:nil,StorageOS:nil,CSI:nil,},},},Containers:[]Container{Container{Name:p,Image:us.gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost:2.20,Command:[],Args:[serve-hostname],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:,HostPort:0,ContainerPort:80,Protocol:TCP,HostIP:,},},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-9vqmb,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,},},RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{},ServiceAccountName:default,DeprecatedServiceAccount:default,NodeName:kinder-regular-worker-1,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,FSGroupChangePolicy:nil,SeccompProfile:nil,},ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{Toleration{Key:node.kubernetes.io/not-ready,Operator:Exists,Value:,Effect:NoExecute,TolerationSeconds:*300,},Toleration{Key:node.kubernetes.io/unreachable,Operator:Exists,Value:,Effect:NoExecute,TolerationSeconds:*300,},},HostAliases:[]HostAlias{},PriorityClassName:,Priority:*0,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:*true,PreemptionPolicy:*PreemptLowerPriority,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},SetHostnameAsFQDN:nil,},Status:PodStatus{Phase:Running,Conditions:[]PodCondition{PodCondition{Type:Initialized,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2020-07-06 19:09:19 +0000 UTC,Reason:,Message:,},PodCondition{Type:Ready,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2020-07-06 19:09:21 +0000 UTC,Reason:,Message:,},PodCondition{Type:ContainersReady,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2020-07-06 19:09:21 +0000 UTC,Reason:,Message:,},PodCondition{Type:PodScheduled,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2020-07-06 19:09:19 +0000 UTC,Reason:,Message:,},},Message:,Reason:,HostIP:172.17.0.2,PodIP:192.168.227.94,StartTime:2020-07-06 19:09:19 +0000 UTC,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:p,State:ContainerState{Waiting:nil,Running:&ContainerStateRunning{StartedAt:2020-07-06 19:09:21 +0000 UTC,},Terminated:nil,},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:true,RestartCount:0,Image:us.gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost:2.20,ImageID:us.gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost@sha256:17e61a0b9e498b6c73ed97670906be3d5a3ae394739c1bd5b619e1a004885cf0,ContainerID:containerd://702c09ea96989ef03db6e991e09c301d85b5d04e4d4e77a9cd251d16e6ee35b3,Started:*true,},},QOSClass:BestEffort,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:192.168.227.94,},},EphemeralContainerStatuses:[]ContainerStatus{},},}

but I don't see any API requests logged to the namespace `namespaces/events-9503` at all (including the pod create request) in any of the API server logs.

**Comment by liggitt** [comment]
When events are recorded via events/v1, they omit the source field, which means the selector used by that test will not match.

We need to do the following:
1. convert the reportingController/reportingInstance fields in events/v1 to source.component/source.host fields in core/v1
2. define field selectors for events/v1beta1 and events/v1 APIs
3. figure out why this test behaves differently in presubmit (does that imply kube-scheduler is still reporting events via core/v1 in that test?)
