### ISSUE TITLE
Request to add informers.WithCustomListOptions to SharedInformerFactory

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#92792]
The k8s scheduler needs to watch a number of API objects such as Pods, Nodes, Services, ReplicaSet, PDBs, etc. So SharedInformerFactory is a perfect fit to watch/list objects among its codebase.

One problem we're facing is that we want to keep the ListOption as default for all objects except for Pods - for Pods, we want to exclude Pods whose `.status.phase` equals to Failed or Succeded. However, in current api-machinery code, there is only `informers.WithTweakListOptions`, which unfortunately applied the custom option to all listers. So does it make sense to add a `informers.WithCustomListOptions` to SharedInformerFactory? so that it's possible to apply a custom ListOptions for **PodInformer only**.
(BTW: an alternative is to add a "informers.WithCustomInformer" so caller is able to modify the sharedXYZInformer in place)

Ref: https://github.com/kubernetes/kubernetes/pull/92682#issuecomment-653734850

/kind feature
/sig api-machinery
/sig scheduling

**Comment by knight42** [comment]
looks reasonable to me

/assign

**Comment by Huang-Wei** [comment]
I rethink a bit and guess `informers.WithCustomListOptions` may not work for my case - because `.status.phase` is not a general option in `ListOption`. If that's the case, `informers.WithCustomInformer` would be more promising.

**Comment by knight42** [comment]
yeah I think `WithCustomListOptions` would not work as  `.status.phase` cannot be used as a field selector.

Since `client-go/informers` is generated by `informer-gen`, I filed PR #92801 to update `informer-gen` first, if that is accepted then we could update client-go.

**Comment by Huang-Wei** [comment]
Thanks @knight42 , let’s see how it goes.

**Comment by fedebongio** [comment]
/cc @roycaihw 
(since we assigned the PR to Haowei)

**Comment by knight42** [comment]
@Huang-Wei it turns out that we could already modify the sharedInformer regardless of my patch, e.g.
```
sharedInformer.InformerFor(&corev1.Pod{}, func(cli kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
  // create and return custom informer
})
sharedInformer.Start(stopCh)
```

**Comment by Huang-Wei** [comment]
@knight42 Thanks. I think that perfectly fits my requirement.
