### ISSUE TITLE
nodeport service udp packets lost with calico

### ISSUE THREAD

**Issue by hamzakilic** [kubernetes/kubernetes#92798]
**What happened**:
a rsyslog service with nodeport, externalpolicy:Cluster configuration in kubernetes,
udp packets loss,
I am sending 1000 syslog packets from my computer to kubernetes cluster for testing
Kubernetes cluster is working on my machine with virtual box( 1 master,2 worker node),
only sending 1000 udp syslog packets
with bash command like
for i in {1..1000}; do logger "test100" -n node1 -P 30515 -d ;done
this, some of packets loss
![kubernetes (1)](https://user-images.githubusercontent.com/11096936/86516037-22cb3980-be26-11ea-8c6b-dccad77ba158.png)

**What you expected to happen**:
no packet loss
**How to reproduce it (as minimally and precisely as possible)**:
create 3 machines, install kubernetes 1.18 and centos 7, one of them will kubernetes master, others will worker node
install calico 3.14 or 3.15
create a docker rsyslog image with this docker file or other from internet
[dockerfile](https://github.com/hamzakilic/kubernetesudpproblem/blob/master/rsyslog.dockerfile)
docker build -t mysyslog -f rsyslog.dockerfile .
4. deploy rsyslog images to kubernetes like this configuration
[rsyslog.yaml](https://github.com/hamzakilic/kubernetesudpproblem/blob/master/rsyslog.yaml)
5. deploy at least 4 replicas of rsyslog image
6. at worker node1 follow packets
**tcpdump -i any -nn port 30515 --number
tcpdump -i any -nn port 514 --number**
7. from your machine
**for i in {1..1000}; do logger "test100" -n node1 -P 30515 -d ;done**
8. at worker node1 you will see at tcpdump 30515 command screen 1000 packets, but at tcpdump 514 you will not see 1000 packets,
packets arrive to node1 to port 30515 with out loss,but sum of the packets that route to node1 port 514 and node2 port 514 are not 1000
you can check with **iptables -vL |grep DROP**, you will see dropped packets

**Anything else we need to know?**:
I tried with Debian10, kubernetes 1.18, calico 3.15, no fix,
I tried with Debian 10, kubernetes 1.18, with cillium CNI, it worked,
than I created a issue at [project calico](https://github.com/projectcalico/calico/issues/3748),
also there is an issue about this problem [here](https://github.com/kubernetes/kubernetes/issues/72511). but no solution,
**Environment**:
- Kubernetes version (use `kubectl version`):1.18.5 (kube-oroxy mode must be iptables)
- Cloud provider or hardware configuration: on premises
- OS (e.g: `cat /etc/os-release`):centos 7
- Kernel (e.g. `uname -a`):Linux cmaster 3.10.0-1127.13.1.el7.x86_67
- Install tools:
- Network plugin and version (if this is a network-related bug):calico 3.14
- Others:
/sig network
/wg network
/committee code-of-conduct

**Comment by hamzakilic** [comment]
I have fixed this problem by changing kube-proxy working mode iptables to ipvs

**Comment by rikatz** [comment]
@hamzakilic is this still a thing? Do you think it's a bug in kube-proxy iptables?

**Comment by hamzakilic** [comment]
> @hamzakilic is this still a thing? Do you think it's a bug in kube-proxy iptables?

We have switched to kube-proxy iptables. and now there is no problem. I think it is bug about one of the calico created interfaces. Packets dropped on one of  the calico interface. . I made the same test with flannel or kube-router, they worked without any problem.
flannel or kube-router does not apply some many iptables rules .

**Comment by sxyandapp** [comment]
我在使用calico网络时，也遇到了同样的问题，udp包无法被正确的转发。当我使用` iptables --policy FORWARD ACCEPT` 命令开启转发时，问题似乎消失了。经过测试，如果使用flannel网络，同样需要执行此命令来开启转发，否则所有的跨主机通信都无法正常运行。
经过测试，机器默认情况下此开关是打开的，但是当启动docker后，此开关被docker关闭，此时只能手动打开此开关已保证calico或flannel能正常运行
