### ISSUE TITLE
Kubernetes 1.16 hpa not working, cpu utilization unknown error

### ISSUE THREAD

**Issue by rjshree** [kubernetes/kubernetes#92808]
I'm new to kubernetes auto scaling and I'm trying to autoscale deployments. I had deployed metrics-server from https://github.com/kubernetes-sigs/metrics-server/releases/

**Logs of deployment:**
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader unchanged
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator unchanged
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader unchanged
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io unchanged
serviceaccount/metrics-server unchanged
deployment.apps/eai-lf-metrics-server configured
service/eai-lf-metrics-server unchanged
clusterrole.rbac.authorization.k8s.io/system:metrics-server unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server unchanged

**Logs from metric server pod:** 
 I0705 16:33:43.852809       1 log.go:172] http: TLS handshake error from 10.233.120.17:40032: EOF
I0705 16:34:43.852923       1 log.go:172] http: TLS handshake error from 10.233.120.17:40684: EOF
E0705 16:35:13.686540       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:k8s-minion-0: unable to get CPU for container "ees-recovery-service-cronjob" in pod example-system/ees-recovery-service-cronjob-1593966900-pb2ch on node "k8s-minion-0", discarding data: missing cpu usage metric 

Where as I'm trying to autoscale the sample php-apache application as exactly as provided in https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**kubectl autoscale command error message:**
 message: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)

**>kubectl version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: **version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}**

I have gone through stackoverflow and added below arguments to metric server deployment, even then the error persists.
args:
          - /metrics-server
          - --kubelet-insecure-tls
          - --cert-dir=/tmp
          - --secure-port=4443

Could anyone help me with cpu unknown utilization issue.
Thanks in Advance!

**Comment by rjshree** [comment]
Should my kube-controller-manager include below commands to make hpa working?
--horizontal-pod-autoscaler-sync-period
--horizontal-pod-autoscaler-sync-period
--horizontal-pod-autoscaler-cpu-initialization-period

**My kube controller commands:**
kube-controller-manager
--allocate-node-cidrs=true
--authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
--authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
--bind-address=0.0.0.0
--client-ca-file=/etc/kubernetes/ssl/ca.crt
--cloud-config=/etc/kubernetes/cloud_config
--cloud-provider=openstack
--cluster-cidr=10.233.64.0/18
--cluster-signing-cert-file=/etc/kubernetes/ssl/ca.crt
--cluster-signing-key-file=/etc/kubernetes/ssl/ca.key
--configure-cloud-routes=false
--controllers=*,bootstrapsigner,tokencleaner
--kubeconfig=/etc/kubernetes/controller-manager.conf
--leader-elect=true
--node-cidr-mask-size=24
--node-monitor-grace-period=40s
--node-monitor-period=5s
--pod-eviction-timeout=5m0s
--profiling=False
--requestheader-client-ca-file=/etc/kubernetes/ssl/front-proxy-ca.crt
--root-ca-file=/etc/kubernetes/ssl/ca.crt
--service-account-private-key-file=/etc/kubernetes/ssl/sa.key
--service-cluster-ip-range=10.233.0.0/18
--terminated-pod-gc-threshold=12500
--use-service-account-credentials=true

Thanks in Advance!

**Comment by justaugustus** [comment]
/sig autoscaling
@kubernetes/sig-autoscaling-bugs

**Comment by bskiba** [comment]
AFAIU, this issue is with installing metrics server in the cluster and being able to fetch metrics from the metrics API. Maybe sig-instrumentation can help here?
/sig instrumentation
@kubernetes/sig-instrumentation-bugs

**Comment by ehashman** [comment]
@rjshree your logs indicate a TLS handshake error, have you correctly configured TLS in order to be able to scrape metrics?
