### ISSUE TITLE
ImagpullPolicy - add an option to pull based on hash and not on name

### ISSUE THREAD

**Issue by kaplandani** [kubernetes/kubernetes#92810]
I would like to add another ImagpullPolicy that will only pull an image if the name is new or the hash is different. 

**Why is this needed**:
Some repositories use to tag the latest stable version with :latest tag. 
If I don't want to rewrite the deployment data and update the version as the repo advance I should be able to use latest
then the kublet will check - if the name exists - compair the hash value - if the hash in the repo is the same - use local image, if not - pull the new image.

**Comment by liggitt** [comment]
> the kublet will check - if the name exists - compair the hash value - if the hash in the repo is the same - use local image, if not - pull the new image

That is exactly what the `Always` policy does. It resolves the image name to a sha and pulls that sha if it does not already exist locally.
