### ISSUE TITLE
Container `hostname -f` should include namespace

### ISSUE THREAD

**Issue by jfoy** [kubernetes/kubernetes#9283]
Right now, both `hostname` and `hostname -f` return the bare pod name. As we move our existing services into Kubernetes, many of our JVM applications are still reporting to our existing metrics (Graphite) and logging (Flume) pipelines. Both of these use host FQDN as a canonical app instance ID, which includes an environment name in the DNS domain. 

Docker already does the right thing with FQDNs; when we pass `--hostname=x.y.z`, it sets the hostname to `x` and the domain to `y.z`, so `hostname -f` returns `x.y.z`. (The 63-character limit applies to each token in the FQDN, not the entire string.)

I suggest that kubelet should pass `--hostname=podname.namespace.cluster.local` (or whatever value is set for cluster_domain instead of cluster.local). That way, `hostname` still returns `podname`, and `hostname -f` returns a result that's useful to users of legacy instrumentation.

**Comment by quinton-hoole** [comment]
cc @vishh

**Comment by jfoy** [comment]
On further examination `--hostname` doesn't behave as advertised; when I set `--hostname=x.y` then `hostname` returns `x.y`.

**Comment by thockin** [comment]
AFAIK the POSIX spec on hostname is unclear, and therefore different OSes implement it differently.  putting an FQDN into hostname is not unheard of.  Docker does appear to do the right thing wrt /etc/hosts, though.

In general we are wary of making DNS associations with pods, but hostname seems like it should be useful.

@bgrant0607 @smarterclayton

**Comment by bgrant0607** [comment]
Hostname shouldn't even be the pod name. https://github.com/GoogleCloudPlatform/kubernetes/issues/4825#issuecomment-77759846

Please use the downward API:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/downward_api.md

**Comment by jfoy** [comment]
@bgrant0607 We'll adjust our applications to use the downward API where we control the mechanism of name discovery. 

Our problem is with legacy JVM programs that expect meaningful results from `InetAddress.getLocalHost.getCanonicalHostName` and `InetAddress.getLocalHost.getHostName`, and more generally, for components expecting `getaddrinfo()` to behave predictably. 

Does Kubernetes make a statement about what `getaddrinfo()` should return within a container?

**Comment by thockin** [comment]
See #4825 for discussion on this.  I'm going to close this as dup for now.
