### ISSUE TITLE
Error "name is required"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9284]
We accept name or generateName, but if you spec neither the error says name is required.

**Comment by manansaraf** [comment]
I can start working on this if no one has started!

**Comment by bgrant0607** [comment]
I'm not sure we should actually fix this. We don't expect generateName to be a commonly used feature, except as a mechanism used by ReplicationController. Also, the message is not wrong -- a name is required. It just might be generated by the server. :-) This can be explained in more detail by the swagger descriptions.

Both in the swagger description and in Status we don't have a good way of expressing "OneOf".

**Comment by bgrant0607** [comment]
I believe this is fixed.
