### ISSUE TITLE
Secret volume update is not really atomic

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#92851]
I think it's kind of relevant to https://github.com/kubernetes/kubernetes/issues/18372 at least to the Tim Hockin's https://github.com/kubernetes/kubernetes/issues/18372#issuecomment-163519777

**What happened**:

Today on kubernetes v1.17.5 I have experienced the following weird `Secret` behaviour:

1. My application has a mounted `Secret` `/app-secret`, so its keys are files in the filesystem.
2. I updated the secret
3. The application during the secret update did not have those files existing at all, for several milliseconds.

So the timeline looked like this:

a. At point in time A `/app-secret/key` is available and readable fine, with the old contents
b. At some point later there is no such file whatsoever, this lasted a few milliseconds
c. Then the file path is back and now the contents is new.

**What you expected to happen**:

As Tim mentioned - I expect the changes to happen atomically: at any point in time the file contents should either be old, or new, but it should never be absent.

**How to reproduce it (as minimally and precisely as possible)**:

Mount a secret as a directory and create a tiny application that reads from the secret file, then update the secret.

**Anything else we need to know?**:

At the moment I cannot upgrade kubernetes, and it only happened once. So I'm not sure if it was a regression in 1.17.5 or if it's even easy to reproduce.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.5
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.3.0-1028-aws
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lavalamp** [comment]
/sig node
/remove-sig api-machinery

A delay here could be a) watch delay between apiserver and kubelet, b) kubelet doing something wrong mounting the file, or c) user error: instead of an update, delete the secret and then later create another one of the same name.

a) shouldn't be able to cause this effect, kubelet just sees an update message on a watch, there's only one message.
b) is of course kubelet not being as atomic as expected, and must be a sig node problem.
c) is just going to have this behavior and I don't think we can do anything about it? Note that using the `--force` CLI option will do a delete and recreate. If this is what happened then it's a sig CLI issue and I think they're already aware that it's unexpected.

**Comment by zerkms** [comment]
> c) user error: instead of an update, delete the secret and then later create another one of the same name.

At least in my report it's not the case: only `kubectl apply` was used.

**Comment by cynepco3hahue** [comment]
@zerkms Can you please verify that it still happens for the HEAD version?
/triage needs-information

**Comment by zerkms** [comment]
I don't have a playground to deterministically reproduce it.
I also don't have a playground to run arbitrary versions of kubernetes (unfortunately).

I think the easiest reproduction would be a scripted language (eg a python) that reads the file in a busy loop and then the secret is changed in another busy loop. For somebody with a proper k8s development setup creating this repro would take may be 10 seconds.

**Comment by ehashman** [comment]
Please don't remove the stale label unless we've provided additional information here. This bug is not in a state that a contributor can fix it.

**Comment by zerkms** [comment]
> Please don't remove the stale label unless we've provided additional information here.

Is it missing anything?

> This bug is not in a state that a contributor can fix it.

what else does it need?

**Comment by ehashman** [comment]
We need to verify that it affects a current, supported version of Kubernetes. 1.17 is not supported.

Additionally, we would need significantly more information if someone was going to be able to assist in fixing the bug. We will need, at minimum, v=4 or higher verbosity logs from a kubelet on an affected system.

**Comment by zerkms** [comment]
Given this bug is unlikely to ever be fixed even if I spend couple days collecting all those crazy amount of details (one may see how reproducing a race condition is not an easy job), I'd rather just close this issue.

Thanks!
