### ISSUE TITLE
label-selector flag  why not support  '||'  condition 

### ISSUE THREAD

**Issue by Cweiping** [kubernetes/kubernetes#92859]
**What happened**:
```shell
kubectl get po -h
```
```
...
-l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
...
```

**What you expected to happen**:
Support operations similar to the following,Support `or` or or `||`:

```shell
kubectl get po -l 'key1= || key2='
```
or 

```shell
kubectl get po -l 'key1= or key2='
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Why is [it](url) the wrong expression?
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/labels/selector_test.go#L43
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T06:42:04Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T04:33:27Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/sig api-machinery
/kind bug

**Comment by fedebongio** [comment]
Under discussion / revision - there is multiple ways of implementing and /or workaround

**Comment by roycaihw** [comment]
I think this is a duplicate of https://github.com/kubernetes/kubernetes/issues/90549

**Comment by liggitt** [comment]
per https://github.com/kubernetes/kubernetes/issues/90549#issuecomment-620625847

> That is not currently possible. Disjoint selectors were intentionally avoided in the selector design to allow for efficient indexing in the future (e.g. #4817) and to avoid complexity of nested boolean AND/OR expressions.

/close
