### ISSUE TITLE
[Failing Test] verify-master (ci-kubernetes-verify-master)

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/kubernetes#92868]
**Which jobs are failing**:

[sig-release-master-blocking#verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)

**Which test(s) are failing**:
**Overall** 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1280458722404995075
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1280458722404995075#1:build-log.txt%3A853

**Since when has it been failing**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1280364350372057090#1:build-log.txt%3A853 Time Monday Jul 6th 21:57 PDT 
1280364350372057090

**Testgrid link**:
[sig-release-master-blocking#verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)

**Reason for failure**:
Multiple occurrences of "Process did not exit before" at different times in the job 
> {"component":"entrypoint","file":"prow/entrypoint/run.go:245","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2020-07-07T06:57:44Z"}

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1280458722404995075
**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=verify-master

**Comment by hasheddan** [comment]
@RobertKielty can this be tracked on https://github.com/kubernetes/kubernetes/issues/87807 or do you think it requires a new issue? It looks like we are having bunches of flakes that cause the job to report failing, then it recovers.

/retitle [Failing Test] verify-master (ci-kubernetes-verify-master)
/sig testing

**Comment by RobertKielty** [comment]
@kubernetes/test-infra-maintainers can you please take a look at these timeouts when you get a chance? Many thanks.

**Comment by RobertKielty** [comment]
> @RobertKielty can this be tracked on #87807 or do you think it requires a new issue? It looks like we are having bunches of flakes that cause the job to report failing, then it recovers.
> 
> /retitle [Failing Test] verify-master (ci-kubernetes-verify-master)
> /sig testing

It _seems_ to me that all of the work carried out for #87807 has been merged, might be best to keep this open until test infra call this out as a dupe of that issue.

**Comment by BenTheElder** [comment]
Not exiting before the grace period means we hit the timeout configured on the job and then it didn't exit after being signaled before the grace period (which is too short by default, unrelated to this we should change that)

Verify is taking too long. We can either make it faster or kick the can down the road and increase the time limit.

**Comment by hasheddan** [comment]
@BenTheElder I think I would vote for kicking the can down the road while investigating making it faster

**Comment by hasheddan** [comment]
This does not appear to be failing anymore

/close
