### ISSUE TITLE
Failing e2e test: ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#92877]
I mentioned this one on #sig-testing in slack but wanted to make sure it is captured in the issue list.

https://storage.googleapis.com/k8s-gubernator/triage/index.html#09fc8a7ce004b711c724

Looks like the problem is that the [e2e test code](https://github.com/kubernetes/kubernetes/blob/f975b4b0dff48c6a580593f3bc05220c70afa367/test/e2e/storage/utils/create.go#L49-L78) does not deal with beta versions of resources coming from yaml (it assumes v1 even if you specify v1beta1 in this case).

This would be OK for most things, but in gcp-compute-persistent-disk-csi-driver 0.5.0, [sc-standard.yaml](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/release-0.5/test/k8s-integration/config/sc-standard.yaml) it attempts to use `apiVersion: storage.k8s.io/v1beta1` which will fail because e2e assumes it is v1 and does not attempt to convert.

gcp-compute-persistent-disk-csi-driver [0.6.0 and beyond use `apiVersion: storage.k8s.io/v1`](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/release-0.6/test/k8s-integration/config/sc-standard.yaml) so if the version is bumped in [gcp-compute-persistent-disk-csi-driver-postsubmits.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/gcp-compute-persistent-disk-csi-driver-postsubmits.yaml) it will probably fix this test.

In case you are wondering (as I did at first) this is NOT an API machinery problem, it is a limitation of e2e test utils, but I think it can be fixed by bumping to the latest storageclass version in the yaml.

##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go:254
Jun 23 00:59:21.307: load storage class from /go/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/test/k8s-integration/config/sc-standard.yaml
Unexpected error:
    <*errors.withStack | 0xc0037c1b60>: {
        error: {
            cause: {
                error: {
                    cause: {
                        s: "converting (v1beta1.StorageClass) to (v1.StorageClass): unknown conversion",
                    },
                    msg: "decode {Kind:StorageClass}",
                },
                stack: [0x1d66b08, 0x1d54de7, 0x1d54b79, 0x3bd77aa, 0x3aecc40, 0x3aeeed3, 0x7d9fb8, 0x7d9c0f, 0x7d90b4, 0x7e0015, 0x7df871, 0x7e573f, 0x7e5260, 0x7e4aa7, 0x7e708b, 0x7e9be7, 0x7e992d, 0x3bee470, 0x3bf486b, 0x517279, 0x462e41],
            },
            msg: "/go/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/test/k8s-integration/config/sc-standard.yaml",
        },
        stack: [0x1d54e35, 0x1d54b79, 0x3bd77aa, 0x3aecc40, 0x3aeeed3, 0x7d9fb8, 0x7d9c0f, 0x7d90b4, 0x7e0015, 0x7df871, 0x7e573f, 0x7e5260, 0x7e4aa7, 0x7e708b, 0x7e9be7, 0x7e992d, 0x3bee470, 0x3bf486b, 0x517279, 0x462e41],
    }
    /go/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/test/k8s-integration/config/sc-standard.yaml: decode {Kind:StorageClass}: converting (v1beta1.StorageClass) to (v1.StorageClass): unknown conversion
occurred
/go/src/k8s.io/kubernetes/_output/doc
```
#### Recent failures:
[7/7/2020, 1:56:11 AM ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration/1280379953266823170)
[7/6/2020, 9:55:02 PM ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration/1280319303714869249)
[7/6/2020, 5:54:12 PM ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration/1280258653919645696)
[7/6/2020, 9:53:14 AM ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration/1280137541957193728)
[7/6/2020, 5:51:50 AM ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-release-0-5-k8s-master-integration/1280076892296187905)

**Comment by msau42** [comment]
@mattcary @saikat-royc could one of you look into updating our job config to test the latest released version of the driver against k8s master?

https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Release%200.5

We should probably also clean up and remove the 1.13 job as well

**Comment by saikat-royc** [comment]
PR for review : https://github.com/kubernetes/test-infra/pull/18198

**Comment by saikat-royc** [comment]
0.7 driver test grid: https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Release%200.7

**Comment by msau42** [comment]
/close
0.5 release is not supported anymore and the job has been removed.
