### ISSUE TITLE
EventAggregatorByReasonFunc doesn't consider reportingController, only source

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#92882]
**What happened**:

Events reported with an empty source.component/source.host and with distinct reportingController/reportingInstance values are considered identical by EventAggregatorByReasonFunc

events.k8s.io/v1 events will not set source fields.

/assign @wojtek-t

**Comment by liggitt** [comment]
cc @chelseychen

**Comment by wojtek-t** [comment]
Thanks for finding and fixing the issue!
