### ISSUE TITLE
Labels propagation from resource (deployment)  to derived set of resources (replica set, pods)

### ISSUE THREAD

**Issue by akshaybhatt14495** [kubernetes/kubernetes#92896]
**What would you like to be added**:
On adding Labels to resource like Deployment which is responsible for replica set and pods accordingly, Labels do not cascades to it's replica set and pods.

Let say I'm creating a Deployment D, corresponds to Replica set R and pods P1, P2, P3
Using this command to attach label to deployment 
```kubectl label  --overwrite  --namespace <namespace> <resource-list> <label-key>=<label-value>```

On describing Deployment D, can see label <label-key>=<label-value>

Current Behaviour: Same Labels are not attached to Replica set R and pods P1, P2, P3

Expected Behaviour: Same Labels should be attached to Replica set R and pods P1, P2, P3

**Why is this needed**:

On adding same set of labels to all resources, it will be helpful to search all type of resources corresponding to required Label. Let say I'am deploying my service with config map, deployment and service for my corresponding service

Requirement:  Discover all kubernetes resources using Some common label like "app-name" : "<app-name>

If this feature already exist in some other form please let me know.

**Comment by liggitt** [comment]
Labels for the replicaset can be defined in the template inside the deployment spec. Automatically propagating all labels from the deployment itself to the created replicasets is not desired in all cases.
