### ISSUE TITLE
Inaccurate declaration of what conversion generator does

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#92895]
**What happened**:
While reviewing work that adds a field to a custom resource defined by code rather than a CRD, I was alerted to a bug in the comment describing what the conversion generator does.  https://github.com/kubernetes/kubernetes/blob/7de3f938c82a7c0538bdfac5bb9b3cad50c30eae/staging/src/k8s.io/code-generator/cmd/conversion-gen/main.go#L34-L38 states that the Convert_... function is generated if it is not present in a non-generated file --- without regard to whether there are any problems in the autoConvert_... function.  But we see at https://github.com/kubernetes/kubernetes/blob/7de3f938c82a7c0538bdfac5bb9b3cad50c30eae/staging/src/k8s.io/code-generator/cmd/conversion-gen/generators/conversion.go#L753 that there is an additional condition that is relevant.

**What you expected to happen**:
I expected the conversion generator to do what it is documented to do.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): This buggy doc was introduced in #71821
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by fedebongio** [comment]
/cc @sttts 
(we took the freedom of assigning the PR to sttts for revision, thanks!)
