### ISSUE TITLE
We should vendor skyDNS

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9289]
We build skyDNS and push a container and use that container but we have not vendored skyDNS code.

**Comment by kelseyhightower** [comment]
I left a response in #9290 regarding this question and etcd. I think it might make sense to "clone" skyDNS under the GoogleCloudPlatform namespace and doing builds from there. Sync with upstream along the way.

**Comment by thockin** [comment]
Yeah, it just sucks because we have all this tooling with Godeps which will
break.  I can't stick binaries under the Godeps dir because Godeps will
purge it.  If I put it outside the Godeps dir then Godeps will try to
vendor in all of the libs that it uses - including its own libs!
