### ISSUE TITLE
kubectl expose does not check type validity when --dry-run=client flag is present

### ISSUE THREAD

**Issue by abhi1604** [kubernetes/kubernetes#92901]
**What happened**:

`kubectl expose  RESOURCE RESOURCE_NAME --type=x --port=NUM --dry-run=client -o yaml` 
The above command populates the yaml with `spec.type=x`

**What you expected to happen**:

The type gets validated before the yaml is populated

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl run temp --image=nginx 

kubectl expose pod temp --type=x --port=80 --dry-run=client -o yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux master 4.15.0-101-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by eddiezane** [comment]
Copying my comment from [here](https://github.com/kubernetes/kubernetes/pull/93439#issuecomment-673664593).

>I synced with liggitt on this one and his recommendation is to not implement this to avoid tightly coupling the client to the server. It's better to keep the client simple and let the server validate the wrong field. Let's say a new valid service type is added -- users would be required to download a new version kubectl to create a service with the new type.

/close
