### ISSUE TITLE
Should we vendor etcd?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9290]
We build our own container for it, we should probably make that reproducible.

**Comment by bprashanth** [comment]
That would make testing changes to the etcd server easier

**Comment by thockin** [comment]
Apparently it's hard/impossible to make Godep vendor a whoile binary - it
only handles libraries.  Or, at least as far as I can see..

**Comment by kelseyhightower** [comment]
@thockin The only real solution I can think of is "cloning" the etcd project under the GoogleCloudPlatform namespace and doing builds from there; syncing up with upstream along the way.

Any reason to avoid relying on the upstream etcd tags and releases? Is there something CoreOS can improve on regarding how etcd tags and releases are cut?

**Comment by thockin** [comment]
Better safe than sorry? Nothing you guys in particular have done, but we
have been bitten by other upstreams rewriting history and obliterating the
git hash we had pinned to.

**Comment by bprashanth** [comment]
> @thockin The only real solution I can think of is "cloning" the etcd project under the GoogleCloudPlatform namespace and doing builds from there; syncing up with upstream along the way.

that's what i had in mind. With every release we need to change something anyway (unless there's an etcd:latest we aren't using), what difference hash or release tag?

**Comment by thockin** [comment]
I found out how to vendor a binary and all its deps.  Awesome.  Now, about
HEAD...

I can use gopkg.in to pull etcd version tags.  Awesome.
gopkg.in/coreos/etcd.v2 -> latest v2.x.y tag.

Here's where it breaks down - `go get` follows imports.  etcd code is not
expecting to find itself named gopkg.in/coreos/etcd.v2 - every import (and
vendored code) refers to github.com.

Unfortunate.  I can manually arrange for godep to getthe right hash, I think

Perhaps every project that uses version tags should be bouncing through a
redirector like gopkg.in?  If etcd referenced everything as gopkg.in this
would be a valid way for people to 'go get' it. (alternately running the
equivalent of gopkg on code.coreos.com or something).

Just contemplating the sad SAD state of dep management...

**Comment by ArtfulCoder** [comment]
https://vividcortex.com/blog/2013/09/10/100-reproducible-builds-in-go/

the link talks about solving the versioning problem and has open sourced the tooling for it.

**Comment by davidopp** [comment]
@lavalamp What do you think about this--is it needed for 1.0? With Brian and Tim out, I'm nominating you to make the call. :-) (I'm a bit doubtful there's anyone to do it, in any event.)

**Comment by lavalamp** [comment]
When @ArtfulCoder and I were chatting about this previously, we talked about including the source code in the container.

Ultimately, this is a problem we need to solve for *all* of our default cluster containers. They *all* need to be reproducible, and one should be able to reproduce them knowing only the container's version tag.

@thockin 
> Here's where it breaks down - `go get` follows imports. 

You need to construct a GOPATH (and separate-from-k8s Godeps!) solely for the etcd build; then this won't be a problem.

As far as etcd goes specificially. IMO, building etcd from HEAD and shipping it is nuts. We should take official releases that have passed whatever testing the etcd team does (presumably they do some testing before cutting a release?). Ideally, we could get etcd team to make statically linked binaries as part of their release process, or even a prepackaged docker container which we can re-tag & mirror.

In the short term, I think we should just include in our etcd container the source code used to build it (*the entire GOPATH*, not just etcd!). If that makes the container too large, then I suggest we .tar.gz the GOPATH, put it somewhere public in GCS, and include a link in the container. This would be a short-term solution until we get in place a reproducible build system for all of our containers.

If I were a sysadmin, I would not be very happy about running a container with unknown source code. Perhaps @smarterclayton or someone else from Red Hat can say if this will actually keep people from running k8s? I think that's the thing that determines whether or not this is in 1.0.

(although like I said above, long term, I question why we're building etcd ourselves, that seems wrong.)

**Comment by smarterclayton** [comment]
----- Original Message -----
> When @ArtfulCoder and I were chatting about this previously, we talked about
> including the source code in the container.
> 
> Ultimately, this is a problem we need to solve for *all* of our default
> cluster containers. They *all* need to be reproducible, and one should be
> able to reproduce them knowing only the container's version tag.
> 
> @thockin
> > Here's where it breaks down - `go get` follows imports.
> 
> You need to construct a GOPATH (and separate-from-k8s Godeps!) solely for the
> etcd build; then this won't be a problem.
> 
> As far as etcd goes specificially. IMO, building etcd from HEAD and shipping
> it is nuts. We should take official releases that have passed whatever
> testing the etcd team does (presumably they do some testing before cutting a
> release?). Ideally, we could get etcd team to make statically linked
> binaries as part of their release process, or even a prepackaged docker
> container which we can re-tag & mirror.
> 
> In the short term, I think we should just include in our etcd container the
> source code used to build it (*the entire GOPATH*, not just etcd!). If that
> makes the container too large, then I suggest we .tar.gz the GOPATH, put it
> somewhere public in GCS, and include a link in the container. This would be
> a short-term solution until we get in place a reproducible build system for
> all of our containers.
> 
> If I were a sysadmin, I would not be very happy about running a container
> with unknown source code. Perhaps @smarterclayton or someone else from Red
> Hat can say if this will actually keep people from running k8s? I think
> that's the thing that determines whether or not this is in 1.0.

Doubt it.

We vendor etcd already (because we run it in our integrated binary) so don't worry about that.

**Comment by lavalamp** [comment]
Cool. In that case: *not* 1.0.

**Comment by sghosh151** [comment]
In the long run, it would be better to not have a vendored copy inside k8s.
Leveraging etcd for other use cases without having to run two copies would
be preferable.  Specially when you add up the ha/resiliency req I
requirements.

Subhendu

**Comment by lavalamp** [comment]
> ... Leveraging etcd for other use cases without having to run two copies ...

Actually I don't agree with this one; k8s's etcd should just be used by k8s. There's currently too many performance & security concerns to use the same etcd instance for both k8s and other components.

**Comment by thockin** [comment]
I still think we should do it, but I agree that we should have a general
policy for EVERYTHING that we build as semi-required containers.

Option 1) Vendor etcd (resolve deps conflicts by hand for now) into
kubernetes, build container images from there.  Repeat for skyDNS.  What
about InfluxDB, grafana, fluentd, heapster, kibana, etc etc?

Option 2) Fork all of those repos, but keep them as distinct repos, not
under kubernetes.  Build images from there.

Option 3) DON'T fork or vendor upstream code into our repos, but do
automate and document the process and snapshot the code into the container
images we build

We might get away with not doing this for 1.0, but we're wobbling pretty
hard and I am afraid this thing will fall over with a gentle push before
too long.

**Comment by sghosh151** [comment]
Option 2 is preferable to option 1. Option 3 is ideal.

One major issue in vendored code is managing security updates at the linux
distribution level. We have to worry about 2 or more communities instead of
one.

Regards
Subhendu

**Comment by thockin** [comment]
@david-mcmahon I think this is a release-process issue.  We have a gcr.io image of etcd.  I don't know who builds it or under what conditions.  I sort of feel like we should vendor it here and build locally, or at least have our own fork of it that rebase on our schedule.

**Comment by hongchaodeng** [comment]
I would like to take care of it.
Either forking it or maintaining the build script, we can take care of syncing and building etcd image.

**Comment by thockin** [comment]
We need to decide WHAT to do first :)

**Comment by timothysc** [comment]
So across several releases we have a workflow that works for publishing updates, it definitely needs refinement, but it works none-the-less.  I'm going to close out this issue and if we have specific issues on our update mechanics we can handle that separately.
