### ISSUE TITLE
lscpu inside Pod return host cpu info

### ISSUE THREAD

**Issue by rushi47** [kubernetes/kubernetes#92904]
Hello,
**What happened**:
When i run `lscpu` inside pod, it return the host node cpu info.
**What you expected to happen**:
Ideally i think it should return resources allocated to pod.
**How to reproduce it (as minimally and precisely as possible)**:
Its as simple as running lscpu.

Is there any way, i can get the cpu and memory allocated to pod, from inside pod ?
Passing the resources in env variables, confs is one way but is there any elegant way like lscpu or free -g to get cpu & memory limits of pod ?

The same bug was reported before, Here : https://github.com/kubernetes/kubernetes/issues/53706#issue-264486420
But it doesnt seem to have any answers yet.

**Comment by takakawa** [comment]
`free -h` also returns host mem info

**Comment by endocrimes** [comment]
@rushi47 As it was stated in the issue you referenced, this is part of the design of containers. The containers share a kernel with the host, cgroups and namespaces are basic constructs to isolate the process, but unless the process itself is written in a way that will introspect its cgroups/namespaces, it will fall back to querying the host information.

There isn't really anything we can practically change here. It can cause issues with runtimes that aren't cgroup aware though.

The easiest way would be to use the [downstream api](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-container-fields-as-values-for-environment-variables), and pull the values from the environment. Alternatively you can pull this information from sysfs, but that I wouldn't really recommend doing that by hand.

**Comment by rushi47** [comment]
@endocrimes  Thanks a lot for the clarification, appreciate the reply :)
