### ISSUE TITLE
kubelet v1.18.5 still have flag --cgroup-driver in pkgs which will cause kubelet set up fail

### ISSUE THREAD

**Issue by dagn0** [kubernetes/kubernetes#92912]
Jul  8 22:28:04 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../0-conntrack_1%3a1.4.5-2_armhf.deb ...#015
Jul  8 22:28:04 rpi-kube-master-01 kubernetes-bootstrap: Unpacking conntrack (1:1.4.5-2) ...#015
Jul  8 22:28:04 rpi-kube-master-01 kubernetes-bootstrap: Selecting previously unselected package cri-tools.#015
Jul  8 22:28:04 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../1-cri-tools_1.13.0-01_armhf.deb ...#015
Jul  8 22:28:04 rpi-kube-master-01 kubernetes-bootstrap: Unpacking cri-tools (1.13.0-01) ...#015
Jul  8 22:28:06 rpi-kube-master-01 kubernetes-bootstrap: Selecting previously unselected package kubernetes-cni.#015
Jul  8 22:28:06 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../2-kubernetes-cni_0.8.6-00_armhf.deb ...#015
Jul  8 22:28:06 rpi-kube-master-01 kubernetes-bootstrap: Unpacking kubernetes-cni (0.8.6-00) ...#015
Jul  8 22:28:10 rpi-kube-master-01 kubernetes-bootstrap: Selecting previously unselected package socat.#015
Jul  8 22:28:10 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../3-socat_1.7.3.2-2_armhf.deb ...#015
Jul  8 22:28:10 rpi-kube-master-01 kubernetes-bootstrap: Unpacking socat (1.7.3.2-2) ...#015
Jul  8 22:28:10 rpi-kube-master-01 kubernetes-bootstrap: Selecting previously unselected package kubelet.#015
Jul  8 22:28:10 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../4-kubelet_1.18.5-00_armhf.deb ...#015
Jul  8 22:28:10 rpi-kube-master-01 kubernetes-bootstrap: Unpacking kubelet (1.18.5-00) ...#015
Jul  8 22:28:16 rpi-kube-master-01 kubernetes-bootstrap: Selecting previously unselected package kubectl.#015
Jul  8 22:28:16 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../5-kubectl_1.18.5-00_armhf.deb ...#015
Jul  8 22:28:16 rpi-kube-master-01 kubernetes-bootstrap: Unpacking kubectl (1.18.5-00) ...#015
Jul  8 22:28:19 rpi-kube-master-01 kubernetes-bootstrap: Selecting previously unselected package kubeadm.#015
Jul  8 22:28:19 rpi-kube-master-01 kubernetes-bootstrap: Preparing to unpack .../6-kubeadm_1.18.5-00_armhf.deb ...#015
Jul  8 22:28:19 rpi-kube-master-01 kubernetes-bootstrap: Unpacking kubeadm (1.18.5-00) ...#015
Jul  8 22:28:22 rpi-kube-master-01 kubernetes-bootstrap: Setting up conntrack (1:1.4.5-2) ...#015
Jul  8 22:28:22 rpi-kube-master-01 kubernetes-bootstrap: Setting up kubectl (1.18.5-00) ...#015
Jul  8 22:28:22 rpi-kube-master-01 kubernetes-bootstrap: Setting up socat (1.7.3.2-2) ...#015
Jul  8 22:28:22 rpi-kube-master-01 kubernetes-bootstrap: Setting up cri-tools (1.13.0-01) ...#015
Jul  8 22:28:22 rpi-kube-master-01 kubernetes-bootstrap: Setting up kubernetes-cni (0.8.6-00) ...#015
Jul  8 22:28:22 rpi-kube-master-01 kubernetes-bootstrap: Setting up kubelet (1.18.5-00) ...#015
Jul  8 22:28:23 rpi-kube-master-01 systemd[1]: **Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible.** This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jul  8 22:28:23 rpi-kube-master-01 systemd[1]: Reloading.
Jul  8 22:28:23 rpi-kube-master-01 kubernetes-bootstrap: Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /lib/systemd/system/kubelet.service.#015
Jul  8 22:28:23 rpi-kube-master-01 systemd[1]: Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jul  8 22:28:23 rpi-kube-master-01 systemd[1]: Reloading.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jul  8 22:28:24 rpi-kube-master-01 kubernetes-bootstrap: Setting up kubeadm (1.18.5-00) ...#015
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Reloading.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: **Configuration file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf is marked world-inaccessible.** This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: kubelet.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: kubelet.service: Main process exited, code=killed, status=15/TERM
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: kubelet.service: Succeeded.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jul  8 22:28:24 rpi-kube-master-01 kubernetes-bootstrap: Processing triggers for man-db (2.8.5-2) ...#015
**Jul  8 22:28:24 rpi-kube-master-01 kubelet[7434]: F0708 22:28:24.984318    7434 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory**
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Jul  8 22:28:24 rpi-kube-master-01 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jul  8 22:28:25 rpi-kube-master-01 kubernetes-bootstrap: kubelet set on hold.
Jul  8 22:28:25 rpi-kube-master-01 kubernetes-bootstrap: kubeadm set on hold.
Jul  8 22:28:25 rpi-kube-master-01 kubernetes-bootstrap: kubectl set on hold.
Jul  8 22:28:25 rpi-kube-master-01 kubernetes-bootstrap: Pulling down all kubeadm images...
Jul  8 22:28:34 rpi-kube-master-01 kubernetes-bootstrap: v1.18.5: Pulling from mirrorgcrio/kube-apiserver
Jul  8 22:28:34 rpi-kube-master-01 kubernetes-bootstrap: 83b4483280e5: Pulling fs layer
Jul  8 22:28:34 rpi-kube-master-01 kubernetes-bootstrap: e01219981e6b: Pulling fs layer
Jul  8 22:28:35 rpi-kube-master-01 systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
Jul  8 22:28:35 rpi-kube-master-01 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
Jul  8 22:28:35 rpi-kube-master-01 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jul  8 22:28:35 rpi-kube-master-01 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jul  8 22:28:35 rpi-kube-master-01 kubelet[7555]: F0708 22:28:35.313808    7555 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jul  8 22:28:35 rpi-kube-master-01 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Jul  8 22:28:35 rpi-kube-master-01 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jul  8 22:28:45 rpi-kube-master-01 systemd[1]: kubelet.service: Service RestartSec=10s expired, scheduling restart.
Jul  8 22:28:45 rpi-kube-master-01 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2.
Jul  8 22:28:45 rpi-kube-master-01 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jul  8 22:28:45 rpi-kube-master-01 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jul  8 22:28:45 rpi-kube-master-01 kubelet[7565]: F0708 22:28:45.564528    7565 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jul  8 22:28:45 rpi-kube-master-01 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Jul  8 22:28:45 rpi-kube-master-01 systemd[1]: kubelet.service: Failed with result 'exit-code'.

**What happened**: 
Kubelet failed to set-up with 3 possible issues:
   1. kubelet.service file privilege is 640, which is marked world-inaccessible.
   2. file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf with privilege 640, which is marked world-inaccessible.
   3. config file /var/lib/kubelet/config.yaml was not auto created, it should be auto generated by kubeadm.

**What you expected to happen**: 
According to official guide, /var/lib/kubelet/config.yaml should be auto created by kubeadm when using docker, but it did not happen, kubelet set up failed.

**How to reproduce it (as minimally and precisely as possible)**:
raspberry pi 4b cluster + raspbian lite os(buster) + raspbian official repo + docker-ce 5.19.03.12 + kubernetes v1.18.5 to set up a k8s master node.

**Environment**:
- Kubernetes version:  v1.18.5-100 kubernetes-xenial/main armhf 
$ dpkg -l | grep kube
hi  kubeadm                        1.18.5-00                           armhf        Kubernetes Cluster Bootstrapping Tool
hi  kubectl                        1.18.5-00                           armhf        Kubernetes Command Line Tool
hi  kubelet                        1.18.5-00                           armhf        Kubernetes Node Agent
ii  kubernetes-cni                 0.8.6-00                            armhf        Kubernetes CNI

$ dpkg -l | grep docker
ii  docker-ce                      5:19.03.12~3-0~debian-buster        armhf        Docker: the open-source application container engine
ii  docker-ce-cli                  5:19.03.12~3-0~debian-buster        armhf        Docker CLI: the open-source application container engine

$ dpkg -l | grep containerd.io
ii  containerd.io                  1.2.13-2                            armhf        An open and reliable container runtime

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
- Cloud provider or hardware configuration: 
Raspberry pi 4B, 4G/8G cluster at home
- OS (e.g: `cat /etc/os-release`):
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
- Kernel (e.g. `uname -a`):  
$ uname -a
Linux rpi-kube-master-01 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
- Install tools:
bash script with official guide

**Comment by dagn0** [comment]
Just check another reported issue -> [issue 83936](https://github.com/kubernetes/kubernetes/issues/83936) ,  it looks like a designed loop. file kubelet/config.yaml will be auto created after command kubelet init.

Now two service related file was reported as  world-inaccessible, not sure if these are issues or not.

Closed it.

**Comment by dagn0** [comment]
Found out the solution at last, due to flag --cgroup-driver exist in /var/lib/kubelet/kubeadm-flags.env, kubeadm could not create config file /var/lib/kubelet/config.yaml, and kubelet can not be set up successfully.

Solution:
sudo sed -i "s/--cgroup-driver=systemd //g" /var/lib/kubelet/kubeadm-flags.env
sudo systemctl daemon-reload
sudo systemctl restart kubelet

Reference:
[Configure cgroup driver used by kubelet on control-plane node](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node)
Note: Since --cgroup-driver flag has been deprecated by kubelet, if you have that in /var/lib/kubelet/kubeadm-flags.env or /etc/default/kubelet(/etc/sysconfig/kubelet for RPMs), please remove it and use the KubeletConfiguration instead (stored in /var/lib/kubelet/config.yaml by default).

**Comment by dagn0** [comment]
The problem here is that the new kubernetes(v1.18.5-00) packages still have deprecated flag --cgroup-driver in file /var/lib/kubelet/kubeadm-flags.env, and the kubelet set up will fail.

Kubernetes version: v1.18.5-100 kubernetes-xenial/main armhf
$ dpkg -l | grep kube
hi kubeadm 1.18.5-00 armhf Kubernetes Cluster Bootstrapping Tool
hi kubectl 1.18.5-00 armhf Kubernetes Command Line Tool
hi kubelet 1.18.5-00 armhf Kubernetes Node Agent
ii kubernetes-cni 0.8.6-00 armhf Kubernetes CNI

**Comment by neolit123** [comment]
- you seem to be using kubeadm which means the /var/lib/kubelet/config.yaml will be created once you run either kubeadm init or kubeadm join
- kubeadm 1.19 no longer sets the --cgroup-driver flag (deprecated) and instead writes the setting in the above config.yaml file. this change cannot be backported to older releases.
https://github.com/kubernetes/kubernetes/commit/afb1ea44b96626b008ef649209030313e7319a6b

/area kubeadm
/remove-kind bug
/triage support
/close

**Comment by dagn0** [comment]
> * you seem to be using kubeadm which means the /var/lib/kubelet/config.yaml will be created once you run either kubeadm init or kubeadm join
> * kubeadm 1.19 no longer sets the --cgroup-driver flag (deprecated) and instead writes the setting in the above config.yaml file. this change cannot be backported to older releases.
>   [afb1ea4](https://github.com/kubernetes/kubernetes/commit/afb1ea44b96626b008ef649209030313e7319a6b)
> 
> /area kubeadm
> /remove-kind bug
> /triage support
> /close

But what is the standard way to config --cgroup-driver with kubeadm v1.18.5? it has --cgroup-driver configed in /var/lib/kubelet/kubeadm-flags.env, but complained about no file /var/lib/kubelet/config.yaml found.

Shall I use kubeadm 1.19 to configure kubelets 1.18.5?

**Comment by neolit123** [comment]
> But what is the standard way to config --cgroup-driver with kubeadm v1.18.5? it has --cgroup-driver configed in /var/lib/kubelet/kubeadm-flags.env, but complained about no file /var/lib/kubelet/config.yaml found.

for older versions you can continue using --cgroup-driver as the flag will not be removed.

> Shall I use kubeadm 1.19 to configure kubelets 1.18.5?

once you upgrade to 1.19 you can remove the flag from flags.env.
