### ISSUE TITLE
image bug in kubernetes

### ISSUE THREAD

**Issue by BZM708** [kubernetes/kubernetes#92943]
On a separate machine I created a number of visual studio applications (asp.net core - web app) and exposed them with the following commands in the terminal:

      kubectl expose deployment websa-node --name=websa-node --type=LoadBalancer --port=80

      kubectl expose deployment weba1-node --name=weba-1node --type=LoadBalancer --type=NodePort --port=7070

After I started the service for both of these applications I found an error on minikube dashboard:
-For websa-node it is:

        Failed to pull image "websa": rpc error: code = Unknown desc = Error response from daemon: pull access denied for websa, 
        repository does not exist or may require 'docker login'
        MountVolume.SetUp failed for volume "default-token-fqptv" : failed to sync secret cache: timed out waiting for the condition

For weba1-node it is:

       Error: ImagePullBackOff
      MountVolume.SetUp failed for volume "default-token-fqptv" : failed to sync secret cache: timed out waiting for the condition

Also the url for both of these applications when I start them are:

websa-node:

      http://192.168.99.100:30235/

weba1-node:

      http://192.168.99.100:32478/

Both of these url does not include the port I used to expose the applications.

What can I do to fix these problems?

### Environment
kubernetes version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

OS version:
ubuntu 18.04

/sig apps

**Comment by kow3ns** [comment]
This isn't a bug. This is a support request. Please ask this question in stackoverflow or community slack, and a community member will assist you. Thanks.
