### ISSUE TITLE
sandbox bug in kubernetes

### ISSUE THREAD

**Issue by BZM708** [kubernetes/kubernetes#92942]
I created a visual studio code application and it works with docker in ubuntu. 

I started the process of exposing my application on kubernetes with the following commands in the terminal:

       minikube start --memory=16384 --cpus=4 --kubernetes-version=v1.18.2 --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock]

       kubectl create deployment webt1-node **--image=webt1**

       kubectl expose deployment webt1-node --name=webt1-node --type=LoadBalancer --port=80

As soon as I exposed my application I had the following error in the terminal:

        [0622/134831.833081:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
         Most likely you need to configure your SUID sandbox correctly

How can I fix this error?

### Environment
Kubernetes version: 
      Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", 
      GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", 
      GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
       Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", 
        GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", 
       GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

OS: 
ubuntu 18.04 # #

/wg apps
/sig apps

**Comment by neolit123** [comment]
/remove kind-bug
/triage support

this doesn't look like a k8s bug.

googling about this error reveals a number of results and it seems the code is in chromium:
https://chromium.googlesource.com/chromium/chromium/+/3c63f9de10d3b4abd9767cd1f4b85323f1064527/chrome/nacl/nacl_helper_linux.cc#236

it hints that your application is not "sandboxed"
https://chromium.googlesource.com/chromium/chromium/+/3c63f9de10d3b4abd9767cd1f4b85323f1064527/chrome/nacl/nacl_helper_linux.cc#181

you could try asking on Stackoverflow, by also providing more details on what application your are working on and what are its dependencies.

/close
