### ISSUE TITLE
what is CSINode resource

### ISSUE THREAD

**Issue by gouki777** [kubernetes/kubernetes#92962]
version:  k8s 1.14.10 update 1.17.7  

When my k8s 1.14.10 update 1.17.7. I find kube-scheduler error log. 
But i can't find The *v1 CSINode resource.
How to Fix the problem. Please give me a hint.thank you~

kube-scheduler log  
<pre>
I0710 18:06:13.515200       1 reflector.go:185] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
E0710 18:06:13.518262       1 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource
I0710 18:06:14.518572       1 reflector.go:185] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
E0710 18:06:14.522617       1 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource
I0710 18:06:15.522846       1 reflector.go:185] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:135
E0710 18:06:15.525841       1 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: the server could not find the requested resource
</pre>

```
# kubectl api-versions
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
ceph.rook.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
crd.projectcalico.org/v1
discovery.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
metrics.k8s.io/v1beta1
monitoring.coreos.com/v1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
rook.io/v1alpha2
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
snapshot.storage.k8s.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

```

**Comment by BenTheElder** [comment]
This is the object.
https://kubernetes-csi.github.io/docs/csi-node-object.html

IMHO it's pretty annoying that we log errors when the cluster isn't even leveraging CSI.

**Comment by msau42** [comment]
v1.CSINode is available starting 1.17 under storage/v1 api group so something seems odd that the apiserver can't find it?

Can you confirm the api server is on 1.17 too?

CSINode is a core storage object along with StorageClass. They are expected to be enabled on all clusters.

**Comment by BenTheElder** [comment]
Perhaps not related to this issue at all, but glancing at a recent kind
presubmit run, I think perhaps kubeadm's kube-scheduler role does not have
permission to list this ...
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92183/pull-kubernetes-e2e-kind/1281727803829522434
(expand
the build log and search for CSINode)

**Comment by msau42** [comment]
I think if the rbacs weren't right, then you should see a "permission denied" or "not authorized" message. In this case "could not find the resource" appears to me that it's not registered in apiserver

**Comment by BenTheElder** [comment]
In the kind e2e log
> Failed to watch *v1.CSINode: failed to list *v1.CSINode: csinodes.storage.k8s.io is forbidden: User \"system:kube-scheduler\" cannot list resource \"csinodes\" in API group \"storage.k8s.io\" at the cluster scope\nE0710 23:25:40.564872

**Comment by BenTheElder** [comment]
this issue is 1.17 though, the log i dug up is 1.19 devel

**Comment by BenTheElder** [comment]
cc @neolit123

**Comment by msau42** [comment]
Our CSI tests (which run on kind) are working fine at least up to 1.18. Our canary-on-master job also appears to be running fine as well. https://k8s-testgrid.appspot.com/sig-storage-csi-ci#1.18-on-1.18

**Comment by msau42** [comment]
Default kube scheduler rbac rule for csinode is here: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L542

**Comment by neolit123** [comment]
@gouki777 

what output are you getting from `kubectl get clusterrole system:kube-scheduler -o yaml` on that 1.17 cluster?
it should contain:
```
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
```

**Comment by neolit123** [comment]
> I think if the rbacs weren't right, then you should see a "permission denied" or "not authorized" message. In this case "could not find the resource" appears to me that it's not registered in apiserver

that is true.


@gouki777 

> k8s 1.14.10 update 1.17.7

- what does that mean? are you upgrading from 1.14 all the way to 1.17.7
- are all of your component versions matching - e.g.  kubelet and apiserver?

**Comment by gouki777** [comment]
@neolit123 
I found the problem.
I upgraded directly to 1.17.7 with 1.14.10
I have 3 master nodes,i only upgraded one master node and found the error log.. so i didn't do the next step and i did a rollback.
Today I upgraded all the nodes.The error log returns to normal. So the problem is version mismatch.

My RBAC is correct
```
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - watch
```

Thanks for your help.
