### ISSUE TITLE
Coredns is not running after kubeadm init

### ISSUE THREAD

**Issue by kavin-kk** [kubernetes/kubernetes#92993]
**What happened**:

Coredns is not running after kubeadm init

Event:
  Type     Reason     Age                From                  Message
  ----     ------     ----               ----                  -------
  Normal   Scheduled  48s                default-scheduler     Successfully assigned kube-system/coredns-684fd95dd-ncsj4 to kube-master
  Warning  Unhealthy  44s                kubelet, kube-master  Readiness probe failed: Get http://10.244.0.7:8181/ready: dial tcp 10.244.0.7:8181: connect: connection refused
  Normal   Pulled     26s (x3 over 46s)  kubelet, kube-master  Container image "k8s.gcr.io/coredns:1.6.7" already present on machine
  Normal   Created    25s (x3 over 46s)  kubelet, kube-master  Created container coredns
  Normal   Started    25s (x3 over 45s)  kubelet, kube-master  Started container coredns
  Warning  BackOff    6s (x5 over 41s)   kubelet, kube-master  Back-off restarting failed container

**What you expected to happen**:

coredns should be up and running after CNI plugin install

**How to reproduce it (as minimally and precisely as possible)**:

`kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.2`

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`

`kubectl get pods --all-namespaces`

`root@kube-master:/etc# kubectl get pods --all-namespaces
NAMESPACE     NAME                                  READY   STATUS             RESTARTS   AGE
kube-system   coredns-684fd95dd-ncsj4               0/1     CrashLoopBackOff   17         64m
kube-system   coredns-684fd95dd-x782j               0/1     CrashLoopBackOff   17         64m
kube-system   coredns-d54f9c4f7-nfkgj               0/1     CrashLoopBackOff   17         65m
kube-system   etcd-kube-master                      1/1     Running            0          3h46m
kube-system   kube-apiserver-kube-master            1/1     Running            0          3h46m
kube-system   kube-controller-manager-kube-master   1/1     Running            0          3h46m
kube-system   kube-flannel-ds-amd64-m5dwl           1/1     Running            0          3h34m
kube-system   kube-proxy-nztt9                      1/1     Running            0          3h46m
kube-system   kube-scheduler-kube-master            1/1     Running            0          3h46m`

**Anything else we need to know?**:
I have tried to edit the coredns yaml using below command and added 8181 port to ready

`kubectl -n kube-system edit cm coredns -o yaml`

`apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready :8181
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-11T12:43:48Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: kubeadm
    operation: Update
    time: "2020-07-11T12:43:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:Corefile: {}
    manager: kubectl
    operation: Update
    time: "2020-07-11T12:55:34Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "1896"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: b15b0990-5ddc-46ad-8959-168330eba484`

**Environment**: Linux
- Kubernetes version (use `kubectl version`):
`root@kube-master:/etc# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: Virtualbox VM - 2 CPU - 2048 RAM
- OS (e.g: `cat /etc/os-release`):
`
root@kube-master:/etc# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
`
- Kernel (e.g. `uname -a`):
`Linux kube-master 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm kubelet kubectl docker
- Network plugin and version (if this is a network-related bug): Flannel - 0.12.0
- Others:

**Comment by neolit123** [comment]
hello, for support tickets our support channels:

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
also #kubeadm on k8s slack.

> https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

flannel had a number of issues, so encourage you to try another CNI like WeaveNet or Calico.

/remove-sig apps
/sig cluster-lifecycle

/close
