### ISSUE TITLE
Kubernetes configuration file

### ISSUE THREAD

**Issue by TomMorant** [kubernetes/kubernetes#93004]
### Who can tell me, please? Thank you

**Comment by neolit123** [comment]
it was deleted:
https://github.com/kubernetes/kubernetes/pull/76711

the /cluster directory is deprecated and only used for internal testing in k8s.
please move to using a different method for creating clusters.

/close

**Comment by TomMorant** [comment]
Hello, what I want to ask is, where can I find the latest version of the cluster configuration file now? The official standard configuration file. . .

**Comment by neolit123** [comment]
> where can I find the latest version of the cluster configuration file now

the last file that resembled that was deleted in https://github.com/kubernetes/kubernetes/pull/76711

kubernetes has no concept of a "cluster configuration file", different tools that create a k8s cluster for you like kubeadm, kops, cluster api have different configuration formats.

**Comment by TomMorant** [comment]
This makes people's learning costs still higher. Then, for example, if I want to add configuration parameters of a certain component in the future, how can I find it???

**Comment by TomMorant** [comment]
> > where can I find the latest version of the cluster configuration file now
> 
> the last file that resembled that was deleted in #76711
> 
> kubernetes has no concept of a "cluster configuration file", different tools that create a k8s cluster for you like kubeadm, kops, cluster api have different configuration formats.

This makes people's learning costs still higher. Then, for example, if I want to add configuration parameters of a certain component in the future, how can I find it???

**Comment by neolit123** [comment]
the core k8s component flags are documented under this reference documentation:
https://kubernetes.io/docs/reference/command-line-tools-reference/

all components with the exceptions of kube-apiserver support a configuration file format that is passed via --config:
https://godoc.org/k8s.io/kube-proxy/config/v1alpha1
https://godoc.org/k8s.io/kube-scheduler/config/v1
https://godoc.org/k8s.io/kubelet/config/v1beta1
...

**Comment by TomMorant** [comment]
> the core k8s component flags are documented under this reference documentation:
> https://kubernetes.io/docs/reference/command-line-tools-reference/
> 
> also, all components with the exceptions of kube-apiserver support a configuration file format that is passed via --config:
> https://godoc.org/k8s.io/kube-proxy/config/v1alpha1
> https://godoc.org/k8s.io/kube-scheduler/config/v1
> https://godoc.org/k8s.io/kube-controller-manager/config/v1alpha1
> https://godoc.org/k8s.io/kubelet/config/v1beta1
> ...

Thank you, and give the community an opinion: I hope the community can include the configuration files of each component (kube-apiserver, kube-scheduler, kube-controller-manager, kubelet, kube-proxy, etc.) in the binary package. I want to do this The future development of the community is also better
