### ISSUE TITLE
Goroutine leak when prometheus pull metrics from cadvisor

### ISSUE THREAD

**Issue by zoroyouxi** [kubernetes/kubernetes#93007]
**What happened**: We find a node in our k8s cluster has memory leak in kubelet. And further，we find there is goroutine leak when prometheus pull metrics from cadvisor.

**Show the go profile from pprof**:
goroutine profile: total 1327
281 @ 0x42ef5a 0x42f04e 0x405d58 0x405b1d 0x9576c1 0x460031
        0x9576c0        k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.computeApproximateRequestSize+0x150        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/http.go:187

281 @ 0x42ef5a 0x42f04e 0x406a4f 0x406755 0x95bfe1 0x95b97b 0x6e84fd 0x96504b 0x6d1204 0xb69bfa 0xb5eb35 0x549bd1 0xb5eb08 0xb69f97 0x6d1204 0x6d26ff 0xb5cf4d 0x549a4e 0x6d310d 0x6cfa87 0x460031
        0x95bfe0        k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*registry).writePB+0x320                        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:425

281 @ 0x42ef5a 0x42f04e 0x43f1cd 0x43ee60 0x4d3207 0x96547d 0x460031
       0x43ee5f        sync.runtime_Semacquire+0x2f                                                                                /usr/local/go/src/runtime/sema.go:47
        0x4d3206        sync.(*WaitGroup).Wait+0x96                                                                                /usr/local/go/src/sync/waitgroup.go:131
        0x96547c        k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*registry).writePB.func1+0x2c        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:407

280 @ 0x42ef5a 0x42f04e 0x43f1cd 0x43ee60 0x4d1d00 0x8dfdbe 0x11c6a9d 0x965503 0x460031
        0x43ee5f        sync.runtime_Semacquire+0x2f                                                                                /usr/local/go/src/runtime/sema.go:47
        0x4d1cff        sync.(*Mutex).Lock+0xcf                                                                                        /usr/local/go/src/sync/mutex.go:85
       0x8dfdbd        k8s.io/kubernetes/pkg/kubelet/container.(*runtimeCache).GetPods+0x5d                                        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/container/runtime_cache.go:62
        0x11c6a9c        k8s.io/kubernetes/pkg/kubelet/metrics.(*podAndContainerCollector).Collect+0x3c                                /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go:235
        0x965502        k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*registry).writePB.func2+0x62        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:413

**Anything else we need to know?**: We also find some error in kernel and kubelet,
2020-06-20T22:11:31.929314+08:00 pjdispaasapp2p1 kernel: [42603491.825561] unregister_netdevice: waiting for veth223eb58 to become free. Usage count = 1
2020-06-20T22:13:21.451468+08:00 pjdispaasapp2p1 kubelet[18836]: E0620 22:13:21.451076   18836 docker_manager.go:1493] Failed to delete container c9e977e571c9a47f61418b6e36bbd421b161d768dbf4b67493372e9a7fa0e951: operation timeout: context deadline exceeded; Skipping pod "1ae5e2c9-ad8b-11ea-8bc6-fa163e4ef05c"
2020-06-20T22:13:21.681180+08:00 pjdispaasapp2p1 kubelet[18836]: E0620 22:13:21.681043   18836 generic.go:197] GenericPLEG: Unable to retrieve pods: operation timeout: context deadline exceeded
2020-06-20T22:13:21.982844+08:00 pjdispaasapp2p1 kubelet[18836]: E0620 22:13:21.982696   18836 kubelet_pods.go:710] Error listing containers: dockertools.operationTimeout{err:context.deadlineExceededError{}}
2020-06-20T22:13:21.983200+08:00 pjdispaasapp2p1 kubelet[18836]: E0620 22:13:21.982778   18836 kubelet.go:1860] Failed cleaning pods: operation timeout: context deadline exceeded

We find the kernel crash may related to [https://github.com/moby/moby/issues/5618]，and kubelet failed to connect docker daemon in this time.
What we wonder is there any relationship between kernel crash and goroutine leak? And does the goroutine leak by cadvisor fixed in new version of kubernetes? 
Thanks.

**Environment**:
- Kubernetes version:  v1.5.6
- OS : SUSE Linux Enterprise Server 12 SP3
- Kernel : 4.4.103-6.38-default
- Network: Only bridge

**Comment by zoroyouxi** [comment]
@kubernetes/sig-node-bugs

**Comment by BenTheElder** [comment]
Is v1.5.6 the correct kubernetes version?
1.5.6 is very old, the project currently supports 1.16.x+
