### ISSUE TITLE
Retrieve original apiVersion

### ISSUE THREAD

**Issue by karolinepauls** [kubernetes/kubernetes#93018]
**What would you like to be added**:

Ability to query Kubernetes cluster resources by their original apiVersions.

**Why is this needed**:

When upgrading the cluster, it may be error-prone to verify that no resources use deprecated API versions. Since by design `kubectl get deployments.v1beta1.apps` and `kubectl get deployments.v1beta1.extensions` return the same deployments (with apiVersions the user asked for), it doesn't satisfy that need. 

`kubectl get deployments.v1beta1.extensions --strict-version` would only return results which applied API version exactly matches the version specified when applying.

Current solutions I can find are all based on repository scanning. This can be a problem e.g. if you have multiple tools that manage resources.

**Comment by roycaihw** [comment]
> When upgrading the cluster, it may be error-prone to verify that no resources use deprecated API versions

The [storage migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator) aims to solve this problem. Currently it works for non-HA clusters with [storage version hash](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/35-storage-version-hash.md). Support for HA clusters is [WIP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md). 

Does the storage migrator solves your need?

**Comment by karolinepauls** [comment]
That's for self-hosted clusters by the looks of it.
