### ISSUE TITLE
Honor "NominatedNodeName" during the new scheduling cycle

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#93013]
**What would you like to be added**:
A option of scheduler used to check the feasibility of `NominatedNodeName` directly instead of loop all the nodes in the cluster after pod preemption is done previously.

**Why is this needed**:
When the preemption is happened a best candidate is chosen from current nodes in the cluster, i.e. the feasibility and prioritization has been thoroughly considered. 

The best candidate is patched to be the pod's field of `NominatedNodeName`, after the new scheduling cycle is started, the "NominatedNodeName" **mostly** like is still the best candidate for the preemptor pod, but in the new scheduling cycle, all nodes are added to check the feasibility again.

Given in the a large cluster with lots of nodes, how it does like this make the efforts unnecessary heaven, we could add a new option so that we can validate the `NominatedNodeName` directly instead of looping all the nodes, and fall back to check other nodes if the `NominatedNodeName` can not pass all the filters again.

pros:
Save scheduling from running all the filter plugins for all the nodes twice.

cons:
There might be other nodes are more suitable for scheduling the pod than the `NominatedNodeName` node, if the are some big changes happened to that **nodes** after the new scheduling cycle but before the `NominatedNodeName` is re-examined.

**Comment by chendave** [comment]
cc @Huang-Wei  @alculquicondor  @ahg-g  what do you think?

**Comment by alculquicondor** [comment]
I like the idea. But I don't think it should be an option, but rather the default behavior.

However, it's important to note that there selecting the nominated node would be guaranteed. There could be an scenario where pods didn't finish to be preempted in the nominated node and, in the meanwhile, some other node freed enough resources. In this case, the pod should go to this other node.

So, we could add the feature, but:
- There should be no guarantees around it.
- We should build a benchmark to prove that we are reducing the running time in the common case. I'm not sure if an integration test would be enough. Perhaps it should be part of some new set of E2E benchmarks that include preemption.

**Comment by ahg-g** [comment]
Sounds good to me. It might be simple to evaluate this node right before we iterate over all the nodes, somewhere [here](https://github.com/kubernetes/kubernetes/blob/19f0a54d6b656f719d5ac446c6a2400e261acd5b/pkg/scheduler/core/generic_scheduler.go#L313). A benchmark would be nice as well.

**Comment by Huang-Wei** [comment]
Generally, I'm ok with this option. And in terms of making it default or not, it depends on (1) how frequent the decision gets **non-optimal** in the new scheduling cycle, and (2) whether users are ok with the behavior that a preemptor can be placed onto a **non-optimal** node. To start with, we can evaluate the result of (1), and then use this result to request user feedback for (2).

---

Another comment:

> When the preemption is happened a best candidate is chosen from current nodes in the cluster, i.e. the feasibility and prioritization has been thoroughly considered.

Keep in mind that the may _not_ be the "best" candidate in the very first place. For example, when several pods on nodeA are presumed to be victims, current logic only check whether nodeA is a candidate or not. However, it's possible that nodeX can be a better candidate (in the case of PodAntiAffity or PodTopologySpread).

**Comment by alculquicondor** [comment]
> Keep in mind that the may not be the "best" candidate in the very first place. For example, when several pods on nodeA are presumed to be victims, current logic only check whether nodeA is a candidate or not. However, it's possible that nodeX can be a better candidate (in the case of PodAntiAffity or PodTopologySpread).

If nothing else changes in the cluster, other than the preempted pods being removed, the nominated node would be the only candidate, thus the best.

**Comment by Huang-Wei** [comment]
@alculquicondor I meant the **initial** "nominatedNodeName" may not be the best (in the case of PodAntiAffity or PodTopologySpread).

**Comment by chendave** [comment]
> Keep in mind that the may _not_ be the "best" candidate in the very first place. For example, when several pods on nodeA are presumed to be victims, current logic only check whether nodeA is a candidate or not. However, it's possible that nodeX can be a better candidate (in the case of PodAntiAffity or PodTopologySpread).

Okay, looks like the preemption doesn't run score plugins before the final candidate is selected, how the candidate is selected `pickOneNodeForPreemption` is totally irrelevant with `prioritizeNodes`.

How about prioritize those candidates for the preemption as well?

**Comment by chendave** [comment]
> However, it's important to note that there selecting the nominated node would be guaranteed. There could be an scenario where pods didn't finish to be preempted in the nominated node and, in the meanwhile, some other node freed enough resources. In this case, the pod should go to this other node.

yep, there are other corner case which make the node is not the best candidate but the bottom line is the node should be one of the candidate that could be able to run the pod, this is why I propose it as a option.

**Comment by ahg-g** [comment]
> @alculquicondor I meant the **initial** "nominatedNodeName" may not be the best (in the case of PodAntiAffity or PodTopologySpread).

There is a very high chance that the nominated node will be the only one feasible for the pod (that is why the pod had to go through preemption in the first place), and so scoring has no impact unless another node become available, which I think is worth ignoring to optimize for the more common case. 

> How about prioritize those candidates for the preemption as well?

This is not going to be trivial, and I don't believe it is necessary.

**Comment by alculquicondor** [comment]
> How about prioritize those candidates for the preemption as well?

It would also make preemption slower, which defies the purpose of the proposal :)

**Comment by chendave** [comment]
@ahg-g  @alculquicondor  thanks for correcting me, cannot agree more! Let's focus on the common case.
