### ISSUE TITLE
Docker version selection issues

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [kubernetes/kubernetes#93010]
Where can I find the relevant information of kubernetes for each version of Docker? Let's say, which version of Docker does Kubernetes 1.18 correspond to? Where can I see it

**Comment by BenTheElder** [comment]
Kubernetes the project declares no relation to any container runtime.

kubeadm does have some environment validation including versions they've vetted.

**Comment by yuexiao-wang** [comment]
Agree with @BenTheElder 
@ITBOX-ITBOY You can get the list of validated docker versions from CHANGELOG-1.16.md and CHANGELOG-1.17.md.
The current list is 1.13.1, 17.03, 17.06, 17.09, 18.06, 18.09. 19.03.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md

**Comment by ITBOX-ITBOY** [comment]
> 同意@BenTheElder
> @ ITBOX-ITBOY您可以从CHANGELOG-1.16.md和CHANGELOG-1.17.md获取经过验证的Docker版本的列表。
> 当前列表是1.13.1、17.03、17.06、17.09、18.06、18.09。19.03。
> 
> [https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md ](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md)
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md

Could you please provide the specific location? I did not find relevant information in the two versions you provided

**Comment by yuexiao-wang** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md
![image](https://user-images.githubusercontent.com/20082558/87639636-1d4fe680-c778-11ea-8e5e-ad48489e3724.png)
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md
![image](https://user-images.githubusercontent.com/20082558/87639745-48d2d100-c778-11ea-9dce-a65262d7cd32.png)

**Comment by ITBOX-ITBOY** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md
> ![image](https://user-images.githubusercontent.com/20082558/87639636-1d4fe680-c778-11ea-8e5e-ad48489e3724.png)
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md
> ![image](https://user-images.githubusercontent.com/20082558/87639745-48d2d100-c778-11ea-9dce-a65262d7cd32.png)

Thank you for your help

**Comment by BenTheElder** [comment]
:+1: 
/close
