### ISSUE TITLE
initial delay when starting Pods with Azure File volumes

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#93025]
**What happened**:

When starting pods with AFS volumes, there is an initial delay of five seconds until the pod is transitioning from the "Scheduled" state. The reason for this is that currently the volume mounting happens inside a wait.Poll which will initially wait a specified interval (currently 5 seconds) before execution.

Event log for comparison with and without AFS volume attached (seconds since event):

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/assign 
/priority important-soon
/sig cloud-provider
/area provider/azure

**Comment by chriserik** [comment]
see #91967
