### ISSUE TITLE
Failing test: Windows 2004 SAC release tests - authenticated-image-pulling

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#93048]
**Which jobs are failing**:
ci-kubernetes-e2e-aks-engine-azure-master-windows-2004

**Which test(s) are failing**:
[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]

**Since when has it been failing**:
since enabling the Windows 2004 SAC release tests

**Testgrid link**:
https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-2004-master

**Reason for failure**:
The manifest for `gcr.io/authenticated-image-pulling/windows-nanoserver:v1` is missing the new windows server version 2004.

```
Jul 13 00:58:43.657: INFO: At 2020-07-13 00:43:45 +0000 UTC - event for image-pull-test4407fbc5-8b6c-44f0-8c1b-ffa1c70ec7ef: {kubelet 1923k8s001} Pulled: Successfully pulled image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1" in 713.2718ms
Jul 13 00:58:43.657: INFO: At 2020-07-13 00:43:45 +0000 UTC - event for image-pull-test4407fbc5-8b6c-44f0-8c1b-ffa1c70ec7ef: {kubelet 1923k8s001} Created: Created container image-pull-test
Jul 13 00:58:43.657: INFO: At 2020-07-13 00:43:45 +0000 UTC - event for image-pull-test4407fbc5-8b6c-44f0-8c1b-ffa1c70ec7ef: {kubelet 1923k8s001} Pulling: Pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
Jul 13 00:58:43.657: INFO: At 2020-07-13 00:43:46 +0000 UTC - event for image-pull-test4407fbc5-8b6c-44f0-8c1b-ffa1c70ec7ef: {kubelet 1923k8s001} Failed: Error: failed to start container "image-pull-test": Error response from daemon: hcsshim::CreateComputeSystem image-pull-test: The container operating system does not match the host operating system.
```

This has occurred before:

- https://github.com/kubernetes-sigs/windows-testing/issues/117
- https://github.com/kubernetes/kubernetes/issues/87785

I looks like we need someone with appropriate permissions to update the manifests once the images are ready.

**Anything else we need to know**:
There was some work done in https://github.com/kubernetes/kubernetes/pull/76838 to automate some of this. Is there something missing?

There are a few other tests that are failing in this job but should be covered by updating https://github.com/kubernetes/kubernetes/pull/89425

/cc @claudiubelu 
/sig windows

**Comment by claudiubelu** [comment]
The test passed 2x consecutively. We can close this now.

https://testgrid.k8s.io/sig-windows-sac#aks-engine-azure-windows-2004-master

/close
