### ISSUE TITLE
Readonlyfilesystem container security policy

### ISSUE THREAD

**Issue by dewanymca** [kubernetes/kubernetes#93058]
Hi Team

We have been read only file system attribute in container security policy with .net Core app. .Net core stream input request to disk if size is greater than 30kb. And for those request we get read only file system. We understand it’s because of readonlyfilesystem attribute, but does this attribute make full file system including user space. Is there an option to make root file system readonly and user one as writable.

Please help.

Thanks
Deepak Sanghi

**Comment by raesene** [comment]
Generally, if you need a writeable area when you have the container set to have a readonlyfilesystem, it is possible to use a volume mount to provide a directory (or directories) where it is possible to write to the container filesystem. 

For temporary files, one option would be to use an [emptyDir volume](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).
