### ISSUE TITLE
[Incorrect test] HPA TestScaleDownIncludeUnreadyPods

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#93056]
This bug is regarding hpa [TestScaleDownIncludeUnreadyPods](https://github.com/kubernetes/kubernetes/blob/b618411f1edb98afe807866fb3a607356d72ba24/pkg/controller/podautoscaler/horizontal_test.go#L1592) test. 

**What happened**:
The test assumes that unready pods are included in the calculations. However the expected replica count is 2, which only a correct result when unready pods are excluded.

**What you expected to happen**:
The test should expect 3 replicas as a correct result.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The problem is in test. It doesn't set any timestamps.
According to [groupPods](https://github.com/kubernetes/kubernetes/blob/b618411f1edb98afe807866fb3a607356d72ba24/pkg/controller/podautoscaler/replica_calculator.go#L369) pod without any timestamps are excluded.

**Environment**:

**Comment by Cweiping** [comment]
I don't seem to have a problem. When HPA calculates the number of **reduced copies**, the not ready pod does not participate in the calculation, and no requests are sent to the not ready pod.

**Comment by krzysied** [comment]
Then it means that the test name is very misleading. If the whole idea was to **ignore** pods maybe we should rename test to TestScaleDownIgnoresUnreadyPods?
Based on https://github.com/kubernetes/kubernetes/blob/b618411f1edb98afe807866fb3a607356d72ba24/pkg/controller/podautoscaler/replica_calculator.go#L400 there is a possible execution when unready pods are taken into account.
