### ISSUE TITLE
Stateful POD created but not scheduled

### ISSUE THREAD

**Issue by rdxilano** [kubernetes/kubernetes#93062]
I have two statefulsets with one replica for each: `data-teleporter-t10-rs1` and `md-teleporter-105-dv16-sv15-ss1`.
I rebooted the node running those pods.
While the node was going down, I deleted those pods with `--force --grace-period=0`.

**What happened**:
 `data-teleporter-t10-rs1-0` pod was immediately deleted from the rebooted node and scheduled to another running node (as it should).
`md-teleporter-105-dv16-sv15-ss1` pod was deleted, the pod was recreated but was not scheduled to another node. Later it was recreated again and scheduled to the rebooted node, once it came up.

**What you expected to happen**:
`md-teleporter-105-dv16-sv15-ss1` pod was expected to behave much like  `data-teleporter-t10-rs1-0` pod

**How to reproduce it (as minimally and precisely as possible)**:
This issue is not easily reproducible. We perform plenty of reboots and statefulset pods deletions with `--force --grace-period=0` and it usually works fine.

**Anything else we need to know?**:
Looking at the kube-controller-manager logs we can see for `data-teleporter-t10-rs1-0` pod:
```
10:58:12.640053 event.go:255] Event(v1.ObjectReference{Kind:"Pod",         ... type: 'Normal' reason: 'TaintManagerEviction' Cancelling deletion of Pod magellan/data-teleporter-t10-rs1-0
10:58:12.662983 event.go:255] Event(v1.ObjectReference{Kind:"StatefulSet", ... type: 'Normal' reason: 'SuccessfulCreate' create Pod data-teleporter-t10-rs1-0 in StatefulSet data-teleporter-t10-rs1 successful
10:58:12.685637 event.go:255] Event(v1.ObjectReference{Kind:"StatefulSet", ... type: 'Warning' reason: 'FailedCreate' create Pod data-teleporter-t10-rs1-0 in StatefulSet data-teleporter-t10-rs1 failed error: The POST operation against Pod could not be completed at this time, please try again.
```
The pod was deleted at 10:58:12 and then created.

In the same log, for `md-teleporter-105-dv16-sv15-ss1` pod we see:
```
10:58:13.636126 event.go:255] Event(v1.ObjectReference{Kind:"Pod",         ... type: 'Normal' reason: 'TaintManagerEviction' Cancelling deletion of Pod magellan/md-teleporter-105-dv16-sv15-ss1-0
10:58:13.998559 event.go:255] Event(v1.ObjectReference{Kind:"StatefulSet"  ... type: 'Normal' reason: 'SuccessfulCreate' create Pod md-teleporter-105-dv16-sv15-ss1-0 in StatefulSet md-teleporter-105-dv16-sv15-ss1 successful
11:06:03.188762 event.go:255] Event(v1.ObjectReference{Kind:"StatefulSet"  ... type: 'Normal' reason: 'SuccessfulCreate' create Pod md-teleporter-105-dv16-sv15-ss1-0 in StatefulSet md-teleporter-105-dv16-sv15-ss1 successful
```
The pod was deleted at 10:58:13 and then created, however, it was not schuled to any node. On 11:06:03 we see that the pod is created again.

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`):
`NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
`
- Kernel (e.g. `uname -a`):
`Linux ip-172-31-255-13.eu-west-1.compute.internal 5.4.2-reduxio #1 SMP Sun Dec 8 11:47:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by ahg-g** [comment]
>  Later it was recreated again and scheduled to the rebooted node, once it came up.

are you saying that the pod wasn't recreated immediately or it was recreated but wasn't scheduled?

**Comment by rdxilano** [comment]
It was create created not scheduled. As seen in the log:
```
10:58:13.998559 event.go:255] Event(v1.ObjectReference{Kind:"StatefulSet"  ... type: 'Normal' reason: 'SuccessfulCreate' create Pod md-teleporter-105-dv16-sv15-ss1-0 in StatefulSet md-teleporter-105-dv16-sv15-ss1 successful
11:06:03.188762 event.go:255] Event(v1.ObjectReference{Kind:"StatefulSet"  ... type: 'Normal' reason: 'SuccessfulCreate' create Pod md-teleporter-105-dv16-sv15-ss1-0 in StatefulSet md-teleporter-105-dv16-sv15-ss1 successful
```
it seems like it was created on 10:58:13 and later on 11:06:03, however, it started to run only after 11:06:03 and I didn't see in any log a deletion between these two creations.

**Comment by ahg-g** [comment]
so there are two pod create events after it was deleted the first time, right?

**Comment by rdxilano** [comment]
That's correct. Eventually I saw the scheduled pod only after the second creation, on the node that was originally rebooted and ran this pod pre force deleting it. I was expecting to see the pod scheduled on another node, while the original node was during (a long) reboot process.

**Comment by ahg-g** [comment]
It is likely that the pod got deleted in between those two create events and the scheduler noticed the pod on the second create only, I think you need to check with sig-apps why was the pod created twice.

/sig-apps

**Comment by rdxilano** [comment]
Thanks. Is there any log that I can see this pod deletion?

**Comment by ahg-g** [comment]
api server logs perhaps.
