### ISSUE TITLE
Kubelet cannot start any pod on Windows: no-new-privileges not supported by docker on Windows.

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#93061]
**What happened**:

The changes introduced by this ( https://github.com/kubernetes/kubernetes/pull/90948 ) PR will not work with Windows as Docker for Windows does not support: no-new-privileges security flag. 

**How to reproduce it (as minimally and precisely as possible)**:

Run any pod with kubelet built from master.

/sig windows

**Comment by wawa0210** [comment]
Is anyone following this pr ?, can I try to fix it

**Comment by elweb9858** [comment]
This issue is causing pull-kubernetes-e2e-azure-disk-windows test to fail in this PR https://github.com/kubernetes/kubernetes/pull/93080, which is blocking merging. Is there a work around for this?

**Comment by wawa0210** [comment]
https://github.com/kubernetes/kubernetes/pull/93263

The issue has been fixed 

/close
