### ISSUE TITLE
kubeRuntimeManager.podSandboxChanged() expects SandboxStatuses to be ordered by Attempts

### ISSUE THREAD

**Issue by rhafer** [kubernetes/kubernetes#93064]
**What happened**:

On a test system kubelet was unable re-create a PodSandbox, picking an already used "Attempt Number" when there were multiple PodSandboxes in "NotReady"  State.

**What you expected to happen**:

kubelet setting the "Attempt" number to the next available "Attempts"

**How to reproduce it (as minimally and precisely as possible)**:

 When there are multiple "NotReady" Pods kubelet will pick the "Attempt" for the new Sandbox to create based the number of the first pod returned from "ListPodSandbox()" and increase that. So it seems to assume that the runtime returns them ordered from the latest attempt to the oldest. I think that assumption is not always correct wrong (and I can't find anything in the specs that says so. I'd assume the order is undefined).
crio doesn't always return them in a specific order. That way kubelet might pick and Attempt number that is already used and will create a naming conflict in crio.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-10T12:00:00Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
```
# cat /etc/os-release 
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
# crio version
Version:       1.18.2
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     2020-07-07T14:57:07Z
GoVersion:     go1.13.11
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Comment by saschagrunert** [comment]
/sig node 
/cc @haircommander @mrunalp 

We saw that issue in conjunction with CRI-O, but I’m now wondering if other runtimes so something different. 🤔

**Comment by haircommander** [comment]
did we get the `name is reserved` error?

**Comment by saschagrunert** [comment]
> did we get a `name is reserved` error?

Exactly.
