### ISSUE TITLE
Change headless services to be a service Type rather than magic "None"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#9307]

**Comment by smarterclayton** [comment]
Agreed

**Comment by smarterclayton** [comment]
Also opened #9983 to track the fact that you don't get env for headless, which is irritating and surprising to users.

**Comment by caseydavenport** [comment]
I'm going to close this as a duplicate of https://github.com/kubernetes/kubernetes/issues/30918 even though this one is older since:
- They're both from Tim.
- The other issue has a lot more detail.

/assign
