### ISSUE TITLE
prestop container hook, stuck in terminating state, rpc error: code = Unknown desc = operation timeout: context deadline exceeded

### ISSUE THREAD

**Issue by zhb127** [kubernetes/kubernetes#93097]
**What happened**:

![image](https://user-images.githubusercontent.com/5210208/87514367-b74a5d00-c6ac-11ea-9ab5-c0b78f5eeb05.png)

![image](https://user-images.githubusercontent.com/5210208/87514336-ab5e9b00-c6ac-11ea-9ed0-5c13f39512da.png)

pod stuck in state: terminating

**What you expected to happen**:

pod ends normally。

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/5210208/87514561-00021600-c6ad-11ea-981b-aef28be99b08.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
![image](https://user-images.githubusercontent.com/5210208/87514608-16a86d00-c6ad-11ea-99e1-b19aaf1e52a0.png)

- Cloud provider or hardware configuration:
Alicloud

- OS (e.g: `cat /etc/os-release`):
![image](https://user-images.githubusercontent.com/5210208/87514818-68e98e00-c6ad-11ea-9d12-f785d2c63c91.png)

- Kernel (e.g. `uname -a`):
![image](https://user-images.githubusercontent.com/5210208/87514837-7272f600-c6ad-11ea-9d03-c620a849851e.png)

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zhb127** [comment]
/sig/autoscaling

**Comment by zhb127** [comment]
> Your `docker-entrypoint.sh` may exec timeout ?

![image](https://user-images.githubusercontent.com/5210208/87785577-fc1bf280-c86a-11ea-8299-64ca535361f1.png)

Stuck all the time, Not forcibly terminated.

**Comment by Cweiping** [comment]
@zhb127  Whether it can be reproduced stably？try to improve the log level > 3 of kubelet to get the runtime information

**Comment by zhb127** [comment]
> @zhb127 Whether it can be reproduced stably？try to improve the log level > 3 of kubelet to get the runtime information

![image](https://user-images.githubusercontent.com/5210208/88896385-57db7800-d27c-11ea-8481-36bba8b5ec8c.png)
