### ISSUE TITLE
scheduler: support arbitrary workloads in integration benchmarks

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93117]
Currently the Kubernetes scheduler integration benchmarks support workloads of a particular kind -- simulated nodes are created and then an initial set of pods are scheduled. Once this setup is complete, a second and final set of pods are scheduled and various metrics are measured. I propose improving this to support arbitrary workloads that can support benchmarking heterogeneous mixture of pods, complex scheduling patterns, synchronisation primitives and cluster autoscaling.

Please see this doc for details: https://docs.google.com/document/d/1IxBgOUBTBSMSsX381ASdKuTiZE508YNXa5eVFRMzABk/edit?usp=sharing

/sig scheduling
/kind feature
/cc @alculquicondor @ahg-g @Huang-Wei @ingvagabund

**Comment by ingvagabund** [comment]
@adtac scheduler perf generates various percentiles which we can see and observe their changes over time. In case any of the percentiles unexpectedly rises or falls down multiple times in a row, it can be seen as something wrong/good happening in the code. With the improvements you suggest, can you ensure the percentiles will still be around the same values no matter how many times you run the new suites over the same commit? Too much randomness might turn the percentiles too much unstable.

**Comment by alculquicondor** [comment]
That would be about making the cases deterministic, which they should be, according to the proposed API. Don't you think?

**Comment by adtac** [comment]
Two things:

1. One of the soft goals I have when working on this is to also submit a diff of the benchmark percentiles reports (old vs new) to show that the percentiles haven't changed much. Functionally, the old tests should be no different from the new ones, but I can't guarantee that the percentiles would be close enough to the old values until I run the benchmarks. From the first few workloads that I've ported over, the new percentiles seem to be pretty close to the old ones.

2. Stability in the new benchmarks over multiple runs is definitely something I hope to have, agreed. At the very least, 50th percentile values should remain stable. And yes, the tests are deterministic, so test environment fluctuations notwithstanding, medians *should* look similar. 95th and 99th percentiles may have some noise, however. I haven't tested the benchmarks over multiple runs yet.

/assign

**Comment by adtac** [comment]
I've updated the doc to make the syntax a bit more concise whilst keeping the same functionality, PTAL. This should reduce config toil a lot. Writing the same workload in the new yaml format will require fewer lines in most cases.

**Comment by alculquicondor** [comment]
lgtm

**Comment by Huang-Wei** [comment]
LGTM as well.

**Comment by ingvagabund** [comment]
@adtac thanks for that, can't wait to see it in work :)
