### ISSUE TITLE
[sig-scheduling] IPAM / Scheduler Performance tests fail on timeout

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93112]
**Which jobs are failing**:

`integration-master (ci-kubernetes-integration-master)`

**Which test(s) are failing**:

`k8s.io/kubernetes/test/integration/ipamperf.TestMain`
`k8s.io/kubernetes/test/integration/scheduler_perf.TestMain`

**Since when has it been failing**:

`07-12-20 00:15 CDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Reason for failure**:

These tests started running after https://github.com/kubernetes/test-infra/pull/18196 caused `integration-master` to run tests that had been marked to skip unless `--short=false`. This change was made to avoid running some other tests when `--short=true` in https://github.com/kubernetes/kubernetes/pull/92879. We need to establish how to adjust timeouts on these tests such that they will be able to run successfully. They will be disabled in the mean time since they were not running previously.

**Anything else we need to know**:

/cc @kubernetes/ci-signal @liggitt @kubernetes/sig-scheduling-misc 
/milestone v1.19
/priority important-soon
/sig scheduling

**Comment by ahg-g** [comment]
Those are non-critical scheduler perf debugging tests, the running time will increase with each test we add, it will also depend on the machine where this is running. 

I think we should just run them on the vanilla workloads, so it is fine to keep it disabled for now and handle this issue in 1.20

**Comment by liggitt** [comment]
sounds good

**Comment by Huang-Wei** [comment]
+1 to what @ahg-g said above. Additionally, this test was firstly built 5 years ago, the internal mechanics (like using a `for..sleep` loop to calculate the metrics) are not that concise, other aspects also need to be ported to latest scheduler architecture.

So this is not a must for 1.19, let's see how to reintroduce it in 1.20.

**Comment by ahg-g** [comment]
/assign @adtac 

the scheduler_perf tests should run on CI, but only few of them (e.g., only the 500node tests).

**Comment by ahg-g** [comment]
can we rename this issue to only focus on the scheduler and track the test related to IPAM in another issue?
