### ISSUE TITLE
Kubernetes Pod PUT Rest API not equivalent to kubectl replace -f testPod.yaml --force

### ISSUE THREAD

**Issue by jayaise** [kubernetes/kubernetes#93135]
**What happened**: Trying to deploy the pod directly. Kubernetes Pod Rest API - PUT (https://kube-url/api/v1/namespaces/default/pods/test-pod)does not do force replace. But kubectl command "kubectl replace -f testPod.yaml --force" works. 

**What you expected to happen**: How to acheive force replace through POD PUT Rest API

**How to reproduce it (as minimally and precisely as possible)**: Use POD PUT Rest API, force will not work, it will consider only changed content - image version

**Anything else we need to know?**: My requirement is I want to do force replace of Pod through Rest Put API. The same can be acheived for DELETE API by passing gracePeriodSecond parameter to REst URL(https://kube-url/api/v1/namespaces/default/pods/test-pod?gracePeriodSeconds=0)

**Environment**:
- Kubernetes version (use `kubectl version`): C:\kubectl>kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig architecture
/sig api-machinery

**Comment by liggitt** [comment]
You can see the API calls kubectl makes by adding --v=6 to the invocation. To change pod spec fields other than the image (and tolerations), a delete/recreate is required
