### ISSUE TITLE
use the k8s 1.16.1  then the nodeSelector can't use the labe name with the '-'

### ISSUE THREAD

**Issue by christming** [kubernetes/kubernetes#93173]
**Which jobs are failing**:

set the deploy  with the nodeSelector configCode
...   
nodeSelector:
    test-node-write: "1"

then kubectl label no test-node-001  test-node-write=1

the events shows:
0/6 nodes are available: 6 node(s) didn't match node selector.

and change the config wite  no “-”

nodeSelector:
    testnodewrite: "1"

then  
kubectl label no test-node-001  testnodewrite=1

it works ！！！

why ？

**Which test(s) are failing**:

**Since when has it been failing**:

**Testgrid link**:

**Reason for failure**:

**Anything else we need to know**:

**Comment by skilxn-go** [comment]
I don't understand what does
> and change the config wite no “-”
mean?

**Comment by hantmac** [comment]
I have a nodeSelector with '-' and deploy success.

**Comment by skilxn-go** [comment]
so, after you changed
```yaml
nodeSelector:
test-node-write: "1"
```
to
```yaml
nodeSelector:
test-node-write: "-"
```

It works?

**Comment by hantmac** [comment]
> so, after you changed
> 
> ```yaml
> nodeSelector:
> test-node-write: "1"
> ```
> 
> to
> 
> ```yaml
> nodeSelector:
> test-node-write: "-"
> ```
> 
> It works?

The next works.
```
nodeSelector:
test-node-write: "xxx-xxx"
```

**Comment by liggitt** [comment]
Do you have the full node and pod as fetched from the API server with `kubectl get pod/$name -o yaml` and `kubectl get node/$name -o yaml`
