### ISSUE TITLE
kube-scheduler and kube-controller-manager fails health checks on insecure port on 1.16.13

### ISSUE THREAD

**Issue by erihanse** [kubernetes/kubernetes#93194]
It seems a backport is needed for #85043 to v1.16.13 as stated in https://github.com/kubernetes/kubernetes/pull/85043#issuecomment-659875085.
**What happened**:
Kube-scheduler and kube-controller-manager fails their health checks after installing 1.16.13.
**What you expected to happen**:
All control plane pods are ready.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.13
- Cloud provider or hardware configuration: on-prem
- Install tools: kubeadm

**Comment by prosnekov** [comment]
Got this behavior on Debian-10, Debian-11, Ubuntu-19.10. In turn on fedora-31, **1.16.13** is working well.

**Comment by neolit123** [comment]
backport / fix is here: https://github.com/kubernetes/kubernetes/pull/93208

**Comment by liggitt** [comment]
fixed in #93208, will be resolved in v1.16.14

**Comment by erihanse** [comment]
I'm not sure how the release process works (or where to find it), does anybody know when release candidates such as this will be released?

**Comment by liggitt** [comment]
see https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#116 for the schedule

v1.16.4 is planned for this week.

**Comment by gruppferi** [comment]
hi @liggitt is it possible to get this patch by today or tommrow? my cluster is in crashing mode because of kube-scheduler and kube-controller-manager, I am currently on kubespray 2.12.9.
is the possible to move to kubespray 2.13.0 and solve this issue?

**Comment by liggitt** [comment]
1.16.14 was released with this fix yesterday
