### ISSUE TITLE
After applying kuboard.yaml at master node, no resources found in kube-system namespace.

### ISSUE THREAD

**Issue by chenshuyuhhh** [kubernetes/kubernetes#93192]
**What happened**: After applying kuboard.yaml at master node, no resources found in kube-system namespace, the kuboard didn't start successfully.

**What you expected to happen**:  After applying kuboard.yaml at master node, kuboard is running.

**How to reproduce it (as minimally and precisely as possible)**:
1. download file:
wget https://kuboard.cn/install-script/kuboard.yaml
2. apply kuboard.yaml:
kubectl apply -f kuboard.yaml
![image](https://user-images.githubusercontent.com/38785959/87803871-b587c180-c885-11ea-897b-96a62343c451.png)

3. visit the state of kuboard:
kubectl get pods -l k8s.eip.work/name=kuboard -n kube- system

![image](https://user-images.githubusercontent.com/38785959/87803893-bae50c00-c885-11ea-922d-5f820a564075.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
![image](https://user-images.githubusercontent.com/38785959/87803964-ccc6af00-c885-11ea-973e-82279d207947.png)

- Cloud provider or hardware configuration:
master: 2CPU, 4GB memory
node1: 2CPU, 1GB memory
node2: 2CPU, 4GB memory

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux k8s-master 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: calico

- Network plugin and version (if this is a network-related bug):

- Others:

what can I do to fix the problem?

**Comment by rikatz** [comment]
It seems that in your ``kubectl get deploy`` you're not passing the namespace ``kube-system``, and the label you're searching (k8s.eip.work) in Pod search does not exists in the manifest you've attached.

/remove-kind bug
/kind support

**Comment by liggitt** [comment]
you can see the deployment, replicaset, and pods in the kube-system namespace like this:

```
kubectl get deployments,replicasets,pods -n kube-system
```

/close
