### ISSUE TITLE
Gets binary K8S configuration information

### ISSUE THREAD

**Issue by Wujunqi-1996** [kubernetes/kubernetes#93205]
Binary K8S Kube-Apiserver, Kube-Scheduler, Kube-Controller component configuration information is there a quick and easy way to get it, rather than through a configuration file

**Comment by Wujunqi-1996** [comment]
> 二进制K8S Kube-Apiserver，Kube-Scheduler，Kube-Controller组件配置信息是一种快速简便的获取方法，而无需通过配置文件

**Comment by johscheuer** [comment]
I think it's not really documented (at least I'm not aware of) but you can get the binaries here (just change the release version and the binary name e.g. `kube-controller-manager`, `kubelet`, etc.): 

```bash
curl -sLO https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-apiserver
```

**Comment by neolit123** [comment]
i think the question is how to get information on how a running k8s control-plane binary is configured?
if so, this is currently not possible. if you are using flags you could look at the begging of the logs of these components.

if you want to create a feature request for that please log a separate ticket and mark it with `/kind feature`.
for general support questions please use https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
