### ISSUE TITLE
Pod termination documentation should clarify termination signals

### ISSUE THREAD

**Issue by mwaggonerzam** [kubernetes/kubernetes#93209]
**What would you like to be added**:

In the Kubernetes documentation about [Termination of Pods](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) it says:

> When a user requests deletion of a Pod, the system records the intended grace period before the Pod is allowed to be forcefully killed, and a TERM signal is sent to the main process in each Docker container.

Based on [this comment](https://github.com/kubernetes/kubernetes/issues/30051#issuecomment-237689913), if I'm understanding correctly, this is somewhat misleading. It appears that what Kubernetes actually does is issue a `docker stop` command to each container, and it's Docker itself that decides what signal is send to pid 1 in the container. By default (as of 2020 Jul) it sends SIGTERM, but this can be configured during image build with the `STOPSIGNAL` Dockerfile command, or at runtime with `docker run --stop-signal=X`.

The documentation would be altered to read (something like):

> When a user requests deletion of a Pod, the system records the intended grace period before the Pod is allowed to be forcefully killed, and the `docker stop` command is issued to each Docker container. (This normally causes Docker to send a TERM signal to the main process in the container, though the signal can be changed with the `STOPSIGNAL` Dockerfile command.)

It might also be the case that when Kubernetes "forcefully kill[s]" a pod, it uses `docker kill` rather than issuing a SIGKILL itself; if so, the relevant documentation should be updated to describe what Kubernetes actually does.

**Why is this needed**:

It would more accurately describe what happens during the pod termination process.

For background: I spent a couple of hours trying to figure out why my container was receiving SIGQUIT instead of SIGTERM. Because the Kubernetes documentation said "a TERM signal is sent to the main process in each Docker container" and not "Kubernetes runs `docker stop`", it didn't occur to me to look within Docker's documentation for ways in which the signal might be changed. I was unaware of `STOPSIGNAL` until I stumbled across a [blog post](https://ubuntu.com/blog/avoiding-dropped-connections-in-nginx-containers-with-stopsignal-sigquit) which mentioned it. It turned out that the base image I was using had `STOPSIGNAL SIGQUIT` in it.

Thanks!

**Comment by johscheuer** [comment]
I think it would be more precise to

**Comment by dex4er** [comment]
I would like to add this comment only because of my frustration after I spent hours to find out why `kubectl delete pod` doesn't generate `SIGTERM` as it was documented.

Of course it happened because of `STOPSIGNAL` in Dockerfile. Unfortunately it was totally not clear and almost impossible to find. Actually `strace` on custom `command` (`ENTRYPOINT`) made this troubleshooting possible.
