### ISSUE TITLE
when kubelet device manager get preferred allocation, lock and unlock operations maybe are in reverse order

### ISSUE THREAD

**Issue by bingerambo** [kubernetes/kubernetes#93238]
**What happened**:
k8s version: v1.20.0-alpha.0
when kubelet device manager get preferred allocation, lock and unlock operations maybe are in reverse order.
Read the 983 to 1001 lines of code snippet in the pkg/kubelet/cm/devicemanager/manager.go file  

```golang
func (m *ManagerImpl) callGetPreferredAllocationIfAvailable(podUID, contName, resource string, available, mustInclude sets.String, size int) (sets.String, error) {
	eI, ok := m.endpoints[resource]
	if !ok {
		return nil, fmt.Errorf("endpoint not found in cache for a registered resource: %s", resource)
	}

	if eI.opts == nil || !eI.opts.GetPreferredAllocationAvailable {
		klog.V(4).Infof("Plugin options indicate to skip GetPreferredAllocation for resource: %s", resource)
		return nil, nil
	}

	m.mutex.Unlock()
	klog.V(4).Infof("Issuing a GetPreferredAllocation call for container, %s, of pod %s", contName, podUID)
	resp, err := eI.e.getPreferredAllocation(available.UnsortedList(), mustInclude.UnsortedList(), size)
	m.mutex.Lock()
	if err != nil {
		return nil, fmt.Errorf("device plugin GetPreferredAllocation rpc failed with err: %v", err)
	}
	// TODO: Add metrics support for init RPC
	return sets.NewString(resp.ContainerResponses[0].DeviceIDs...), nil
}

```

1. m.mutex.Unlock()
2. resp, err := eI.e.getPreferredAllocation()
3. m.mutex.Lock()

This will trigger panic...

**What you expected to happen**:

should do lock first, then do unlock.

1. m.mutex.Lock()
2. do something...
3. m.mutex.Unlock()

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.0-alpha.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
The release of lock is for making RPC call (after which lock is obtained again).

The logic is correct.

**Comment by bingerambo** [comment]
> The release of lock is for making RPC call (after which lock is obtained again).
> 
> The logic is correct.
