### ISSUE TITLE
Changing kubelet port breaks kubectl logs

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#9325]
Starting the kubelet with --port breaks kubectl logs because the master has a hardcoded assumption of 10250. The easiest way to fix this is to claim it's a user error if the master and any kubelet use mismatched ports, and pipe the one right port into the http client the master creates to talk to all kubelets.

**Comment by davidopp** [comment]
The fix is for kubelet to tell master its port when it registers. For now, we will just add a note for the help text on kubelet --port that says kubelet logs won't work if you override the default.

**Comment by mikedanese** [comment]
cc @gmarek

**Comment by gmarek** [comment]
The changes I make for allowing Kubelet to run on non-standard port will fix this.

**Comment by davidopp** [comment]
@gmarek what is the status of this issue?

**Comment by gmarek** [comment]
It's solved by #12919, but I didn't have time to finish it - I'll do this today.

**Comment by davidopp** [comment]
@gmarek Can we close this? If so, please close.

**Comment by gmarek** [comment]
I need to verify - I'm not sure I have a free cluster time today to do so.
