### ISSUE TITLE
scheduler/metrics.go: add comment warning against changing metric types

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93255]
Changing the type of an existing metric should be considered harmful unless absolutely necessary. Preferably, a new metric would be defined instead of changing the type of the existing metric.

/sig scheduling
/cc @ahg-g

**Comment by ahg-g** [comment]
We should simply adhere to deprecation policy here.

**Comment by adtac** [comment]
Closing as per @ahg-g's comment -- metrics are alpha right now, so this is allowed as per the metrics deprecation policy.

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md#stability-classes
