### ISSUE TITLE
Nested trace panic observed

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93257]
```
=== RUN   TestWebhookAdmissionWithoutWatchCache/node.k8s.io.v1alpha1.runtimeclasses/deletecollection
=== RUN   TestWebhookAdmissionWithoutWatchCache/node.k8s.io.v1alpha1.runtimeclasses/deletecollection
E0720 14:42:14.176652  108028 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 74298 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3e97e80, 0x79aa2c0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc0219e5c98, 0x1, 0x1)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3e97e80, 0x79aa2c0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).durationIsWithinThreshold(0x0, 0xc0219e5400)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:222 +0x26
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).logTrace(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:184 +0x43
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).logTrace(0xc003f55c70)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:208 +0xb0
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).logTrace(0xc003f55a40)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:208 +0xb0
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).Log(0xc003f55a40)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:165 +0x95
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).LogIfLong(0xc003f55a40, 0x6fc23ac00)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:178 +0x64
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithTrace.func1(0x5398b80, 0xc003f559d0, 0xc021c6f900)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/trace.go:62 +0x694
net/http.HandlerFunc.ServeHTTP(0xc00e98ee80, 0x5398b80, 0xc003f559d0, 0xc021c6f900)
	/usr/local/go/src/net/http/server.go:2041 +0x44
```

in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93063/pull-kubernetes-integration/1285215292728807425

which points to this line:

https://github.com/kubernetes/kubernetes/blob/c2378045330669ee5b3e1d1fb08749e3b086995b/vendor/k8s.io/utils/trace/trace.go#L222

/assign @jpbetz

**Comment by liggitt** [comment]
failures seen multiple times: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=durationIsWithinThreshold

this will likely be masked once https://github.com/kubernetes/kubernetes/pull/93253 goes in and stops logging traces unconditionally, but still needs to be root-caused and fixed before 1.19 cuts

**Comment by liggitt** [comment]
Since trace.go:208 is in the stack twice this is related to nested traces

Are all the methods that can be called from the context threadsafe?

**Comment by liggitt** [comment]
at least validatingDispatcher#callHook is called from parallel goroutines, and calls genericapirequest.WithTrace -> which calls Nest(), which mutates t.traceItems

That can definitely cause races ... I'm not sure if it could cause a NPE for something simultaneously iterating over traceItems but it seems likely given the integration test where this is appearing

**Comment by liggitt** [comment]
looks like this was introduced in https://github.com/kubernetes/kubernetes/pull/88936

**Comment by jpbetz** [comment]
> looks like this was introduced in #88936

Yes, that's it. We could revert that and get to a state where we don't do any Nest calls, which avoids the race (no need to change which utils version we use).

**Comment by jpbetz** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/93259 to revert the use of nested traces

**Comment by jpbetz** [comment]
Also opened https://github.com/kubernetes/utils/issues/178 to track the issue in utils.
