### ISSUE TITLE
network glitch can lead to node stuck in "NotReady" state

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#93268]
This issue is primarily to track the inclusion of the fix for https://github.com/golang/go/issues/40213 into Kubernetes.

**What happened**:
After uncleanly rebooting the node running kube-apiserver, a node went into the "NotReady" state and stayed that way even after all nodes were running again.  Once in this mode, restarting kubelet on the "NotReady" node was enough to make it go "Ready" again.

**What you expected to happen**:
Node should return to "Ready" status once kubelet could talk to kube-apiserver again.

**How to reproduce it (as minimally and precisely as possible)**:
Unknown...it appears to be a race condition and I was only able to reliably reproduce in one lab after multiple attempts.

**Anything else we need to know?**:

The problem currently appears to be due to an underlying golang net/http and net/http2 issue, as described at https://github.com/golang/go/issues/40213

I was able to run kubelet under delve, and I could see that "pconn.alt" was of type net/http.RoundTripper(golang.org/x/net/http2.erringRoundTripper) and yet the test for pconn.alt.(http2erringRoundTripper) was failing.

**Environment**:
- Kubernetes version (use `kubectl version`):
controller-0:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"archive", BuildDate:"2020-06-27T23:14:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

controller-0:~$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
controller-0:~$ uname -a
Linux controller-0 3.10.0-1127.el7.2.tis.x86_64 #1 SMP PREEMPT Sat Jun 27 18:46:23 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cbf123** [comment]
@fedebongio Are you sure about removing api-machinery?  Kubelet calls code in kubernetes/vendor/k8s.io/client-go which in turn calls the upstream code referenced in golang/go#40213

**Comment by lavalamp** [comment]
I think we missed that this was just waiting for the mentioned fix to become available.

/sig api-machinery
/remove-sig node
