### ISSUE TITLE
Kueblet fails to start due to device plugin manager on windows

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#93262]
**What happened**:
The pr https://github.com/kubernetes/kubernetes/pull/80917 introduced device manager for windows.   We are seeing test failures since the PR was merged:

The tests have no windows nodes coming online.  From https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1285006290715676672:

```
2020/07/20 00:55:29 e2e.go:474: Cluster nodes:
k8s-master-26157211-0   Ready   master   3m11s   v1.20.0-alpha.0.249+6ceb6c6845348e
```
When looking at the kubelet logs the error is 

```
I0720 19:24:36.710427    4332 manager.go:132] Creating Device Plugin manager at /var/lib/kubelet/device-plugins/kubelet.sock
F0720 19:24:36.710427    4332 server.go:265] failed to run Kubelet: bad socketPath, must be an absolute path: /var/lib/kubelet/device-plugins/kubelet.sock
```

**What you expected to happen**:
The kubelet mounts the device manager via a namedpipe not a unix socket.

**How to reproduce it (as minimally and precisely as possible)**:
use a build from the main branch.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.0-alpha.0.234+a789d56b65d352
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
reverted in Opened https://github.com/kubernetes/kubernetes/pull/93263 with a revert of this since it fails windows kubelet startup

**Comment by aarnaud** [comment]
Ok I see the root cause, In my PR few month ago, I changed the constant path with windows path but reviewer ask me to remove path overwrite.

**Comment by aarnaud** [comment]
maybe it's juste the directory device-plugins to create before start kubelet ?

**Comment by jsturtevant** [comment]
I looked into it a bit, it seems the call to https://github.com/kubernetes/kubernetes/blob/5a529aa3a0dd3a050c5302329681e871ef6c162e/pkg/kubelet/cm/devicemanager/manager.go#L134  

is the issue.  On linux it checks for existence of "/" where as on windows the default that is specified here: https://github.com/kubernetes/kubernetes/blob/8f968c41d29c9fb2a322825b0e2c19ed7e589966/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/constants.go#L30

causes it to not pass the check.

The implementation for filepath on windows is here: https://golang.org/src/path/filepath/path_windows.go

**Comment by thomacos** [comment]
> I looked into it a bit, it seems the call to
> 
> https://github.com/kubernetes/kubernetes/blob/5a529aa3a0dd3a050c5302329681e871ef6c162e/pkg/kubelet/cm/devicemanager/manager.go#L134
> 
> is the issue. On linux it checks for existence of "/" where as on windows the default that is specified here:
> 
> https://github.com/kubernetes/kubernetes/blob/8f968c41d29c9fb2a322825b0e2c19ed7e589966/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/constants.go#L30
> 
> causes it to not pass the check.
> 
> The implementation for filepath on windows is here: https://golang.org/src/path/filepath/path_windows.go

Thanks for the analysis!
See my comment https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-661745052.
