### ISSUE TITLE
scheduler: support scheduling profile-level configuration parameters

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#93270]
**What would you like to be added**:

The current scheduler parameters are set in a scheduler configuration file as global settings. As the scheduling framework and multiple scheduling profiles are introduced, it will be useful to support scheduling profile level parameters, e.g.,  _percentageOfNodeToScore_  and related parameters _minFeasibleNodesToFind_.

Global configuration
```
ApiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
...

profiles
- schedulerName: batch-scheduler 
   plugins:
  ...

- schedulerName: service-scheduler
   plugins:
  ...

percentageOfNodesToScore: 50
```

Per-profile configuration
```
ApiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
...

profiles
- schedulerName: batch-scheduler 
   plugins:
   ...
   percentageOfNodesToScore: 10

- schedulerName: service-scheduler
   plugins:
   ...
   percentageOfNodesToScore: 50

```
**Why is this needed**:

Scheduling profile-level configuration parameters will provide a simple way to customize the scheduling behavior with different scheduling profiles. For example, different thresholds of percentageOfNodesToScore can be used to conduct performance tuning and achieve a better balance of scheduling performance and quality for different workloads. For example, a long running service typically cares more about the scheduling quality and can simply use a profile with a high threshold to achieve a better scheduling quality while a large batch job looks for a quick turnaround and will use a scheduling profile with a lower threshold for a quicker scheduling.

**Comment by Huang-Wei** [comment]
>  For example, a long running service typically cares more about the scheduling quality and can simply use a profile with a high threshold to achieve a better scheduling quality while a large batch job looks for a quick turnaround and will uses a scheduling profile with a lower threshold for a quicker scheduling.

This requirement looks reasonable to me.

/cc @alculquicondor

**Comment by ahg-g** [comment]
Moving `PercentageOfNodesToScore` to inside the profile config make sense.

**Comment by yuanchen8911** [comment]
Thanks, @Huang-Wei  @ahg-g. How should we proceed with it?

**Comment by yuanchen8911** [comment]
> Moving `PercentageOfNodesToScore` to inside the profile config make sense.

should probably include the related parameters such as "minFeasibleNodesToFind".  The current global setting is 100.

**Comment by alculquicondor** [comment]
The problem with "moving" is that it increases maintenance, as we have to support 2 API versions for some time. Should we keep the global as well?

**Comment by alculquicondor** [comment]
> should probably include the related parameters such as "minFeasibleNodesToFind". The current global setting is 100.

Are you sure 100 is too big for your use case? I prefer we don't add parameters if we don't need them.

**Comment by ahg-g** [comment]
the moving in this case shouldn't be difficult (we keep both and the per-profile value takes precedence), and we need to support it for two releases only, right?

**Comment by ahg-g** [comment]
for Beta it will be 9 months or 3 releases, whichever is longer.

**Comment by alculquicondor** [comment]
> the moving in this case shouldn't be difficult (we keep both and the per-profile value takes precedence), and we need to support it for two releases only, right?

If we keep both, we don't need a new API version.

**Comment by ahg-g** [comment]
yeah, we could keep both in Beta, and remove the global one in GA.

**Comment by alculquicondor** [comment]
It is my understanding that the strong preference is that there are no changes between Beta and GA, apart from new fields.

**Comment by ahg-g** [comment]
True, but I think in this case it is fine because we are not removing functionality and not changing the config significantly.

**Comment by yuanchen8911** [comment]
> > should probably include the related parameters such as "minFeasibleNodesToFind". The current global setting is 100.
> 
> 
> 
> Are you sure 100 is too big for your use case? I prefer we don't add parameters if we don't need them.

There are use cases where the number of feasible nodes to find is known as priori. For example, scheduling a Pod on a certain node (like NodeName plugin) or any feasible node. The number of nodes to find is 1. A scalable scheduling algorithm finds two feasible nodes and then chooses the better one (Sparrow https://cs.stanford.edu/~matei/papers/2013/sosp_sparrow.pdf). In this case, the number is 2.

In the above cases, the number of feasible nodes to find has a specific small value. Once the specified number of nodes are found, filtering will be canceled. A (optional) per-profile parameter like numFeasibleNodesToFind would be useful and could be a better profile parameter than minPercentageOfNodeToFind.

**Comment by yuanchen8911** [comment]
> The problem with "moving" is that it increases maintenance, as we have to support 2 API versions for some time. Should we keep the global as well?

Keeping the global one makes sense. Local ones override the global one.

**Comment by yuanchen8911** [comment]
> yeah, we could keep both in Beta, and remove the global one in GA.

I feel keeping the global one would work better. The global one is the default for all profiles and a local one overrides the global one. It makes a lot of sense and the compatibility is maintained.

**Comment by Huang-Wei** [comment]
> In the above cases, the number of feasible nodes to find has a specific small value. Once the specified number of nodes are found, filtering will be canceled.

We can continue the discussion in #86630.

**Comment by alculquicondor** [comment]
> There are use cases where the number of feasible nodes to find is known as priori. For example, scheduling a Pod on a certain node (like NodeName plugin) or any feasible node. The number of nodes to find is 1. A scalable scheduling algorithm finds two feasible nodes and then chooses the better one (Sparrow https://cs.stanford.edu/~matei/papers/2013/sosp_sparrow.pdf). In this case, the number is 2.

I know this is true, but the question is whether it's worth adding such optimization. The current scheduler already can handle 100 pod/s in clusters with 5k nodes. What is your target and how far are we from it?

**Comment by yuanchen8911** [comment]
> > There are use cases where the number of feasible nodes to find is known as priori. For example, scheduling a Pod on a certain node (like NodeName plugin) or any feasible node. The number of nodes to find is 1. A scalable scheduling algorithm finds two feasible nodes and then chooses the better one (Sparrow https://cs.stanford.edu/~matei/papers/2013/sosp_sparrow.pdf). In this case, the number is 2.
> 
> I know this is true, but the question is whether it's worth adding such optimization. The current scheduler already can handle 100 pod/s in clusters with 5k nodes. What is your target and how far are we from it?

As far as scheduling a huge number of small batch jobs/tasks in ultra large clusters, 100 pods/second may not be good enough. Hadoop YARN's throughput is in the high end of hundreds of tasks/sec. We are aware of batch systems that can schedule more than 1000 tasks/per second. The scheduling scalability can become (if not yet) a roadblock to run batch jobs in k8s at scale. If we talk about (sub-second) tiny-tasks as described in the Sparrow paper, even 1000 pods/second might not be adequate. 

Adding an additional parameter like numFeasibleNodes to each profile is straightforward. It would be worthwhile If it can facilitate the development of advanced scheduling like scalable scheduling. What optimization or algorithms should be used would be a separate problem.  

A salient feature of the scheduling framework and plugin is the ability to customize scheduling for specific workloads and use cases.  Flexible mechanisms are hence important to develop various customizations to meet different needs of diverse workloads.

**Comment by yuanchen8911** [comment]
If there's still a concern,  we can just add `percentageOfNodesToFind` as a profile parameter first.

**Comment by alculquicondor** [comment]
I'm not against the change. I'm just trying to make sure all possibilities have been considered. In general, adding more configuration parameters adds to maintenance costs, both for us developers and people trying to configure their schedulers, as now they have to read more documentation.

That's why I would like to know about the specific use case and performance requirements.

**Comment by yuanchen8911** [comment]
> I'm not against the change. I'm just trying to make sure all possibilities have been considered. In general, adding more configuration parameters adds to maintenance costs, both for us developers and people trying to configure their schedulers, as now they have to read more documentation.
> 
> That's why I would like to know about the specific use case and performance requirements.

Understood, I agree we should add parameters with caution. I suggest we keep the global parameters (e.g., percentageOfNodeToScore) as is for simplicity and compatibility, and add and use profile level parameters carefully. The latter will likely be used by advanced users or custom plugins/profiles only. Thanks for the feedback!

**Comment by alculquicondor** [comment]
FYI, we are doing a v1beta2 version in 1.20. So this is the time to move that parameter, if you want to work on it #95446

**Comment by alculquicondor** [comment]
@SataQiu are you no longer working on this?

**Comment by Jerry-Ge** [comment]
> @SataQiu are you no longer working on this?

Is there anyone still working on this issue? I may help.

**Comment by alculquicondor** [comment]
I doesn't look like there is any interest in this anymore

/close

**Comment by yuanchen8911** [comment]
Hi @ahg-g @alculquicondor,  can we reopen this issue?  We discussed the proposed change and everyone agreed with it last year.  An implementation PR was filed by  @SataQiu , but it was incompleted and closed for some reason https://github.com/kubernetes/kubernetes/pull/97263.  

We'd like to submit an PR for it.  A use case is to better support workload-specific scheduling with soft `InterPodAffinity` requirement. With the default `percentageOfNodesToScore`, the feasible nodes for different pods returned by Filter plugins may be disjoint sets. As a result, there's no chance the pods can be co-located  on a same node by the scoring plugins. We want to increase `percentageOfNodeToScore` for these workloads to improve their chance of co-location. In a multi-tenant cluster, we prefer a higher `percentageOfNodesToScore` for certain workloads in a separate scheduling profile only without changing the global value and affecting other workloads.  In this case, per-profile `percentageOfNodeToScore` will be very useful.

/cc @Huang-Wei

**Comment by alculquicondor** [comment]
/reopen

It looks like it was closed by the author because they couldn't continue working on it. I think the agreement was to remove the original percentageOfNodesToScore, but we can no longer do that because the configuration API is a now stable.

In any case, we can still add the new field, but we need to document properly what happens when the field outside of the profile is also set.

**Comment by kerthcet** [comment]
Once https://github.com/kubernetes/kubernetes/pull/112521 is merged, is there any other configurations requested for now?

**Comment by Huang-Wei** [comment]
We can close it now.

/close
