### ISSUE TITLE
[Azure] Node Event doesn't contain the detailed errors when controller manager failed to create routes

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#93277]
**What happened**:

Node Events doesn't contain the detailed errors when controller manager failed to create routes, only time out errors are shown in node events.

**What you expected to happen**:

The detailed errors should be shown in the node events for easier troubleshooting.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/sig cloud-provider
/area provider/azure

**Comment by droslean** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/93466#discussion_r460829331

/close
