### ISSUE TITLE
"instance not found" error is reported for recreated Azure nodes

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#93287]
**What happened**:

When a node is deleted and then recreated in short time, the "instance not found" error  would be reported from Azure cloud provider and hence the node object is deleted by kube-controller-manager.

It is because the deleted VMSS VM would be cached for 15 minutes (this is used to avoid throttling issues when a large number of nodes are deleted):

https://github.com/kubernetes/kubernetes/blob/dd649bb7ef4788bfe65c93ebc974962d64476b39/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go#L182-L188

The cache above is too long and should be reduced to a shorter value, e.g. 3 minutes.

**What you expected to happen**:

The newly created Node should not be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/priority critical-urgent
/area provider/azure
/sig cloud-provider

**Comment by hasheddan** [comment]
@feiskyer is anyone already working on this?

**Comment by feiskyer** [comment]
@hasheddan #93288 is working on a fix for this. Would you like to have a look?

**Comment by hasheddan** [comment]
@feiskyer will do 👍

**Comment by onlydole** [comment]
Thank you for working on this, @feiskyer and @hasheddan!

/assign @feiskyer
