### ISSUE TITLE
Dynamic Provisioning [single-az] should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows]

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93295]
**Which jobs are flaking**:

pull-kubernetes-e2e-azure-disk-windows

**Which test(s) are flaking**:

* Dynamic Provisioning [single-az] should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows]

**Testgrid link**:

https://testgrid.k8s.io/provider-azure-presubmit#pr-k8s-azure-disk-e2e-master-windows&include-filter-by-regex=read%20to%20it%20again%7Cmultiple%20volumes&width=20

**Reason for failure**:

```
Unexpected error:
    <*errors.errorString | 0xc0007530a0>: {
        s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00hello world\r\n\"",
    }
    Failed to find "hello world
    hello world
    ", last result: "�������������hello world
    "
```

That looks like some sort of data corruption or error reading

/sig windows

**Comment by michmike** [comment]
@claudiubelu  and @adelina-t  can you please take a look?

**Comment by michmike** [comment]
cc: @immuzz

**Comment by adelina-t** [comment]
Yep, we're covering this.

**Comment by andyzhangx** [comment]
the flacky e2e test code is here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3b2c6764dd70445d2c6e070abb7d560518b2ed5b/test/e2e/dynamic_provisioning_test.go#L264-L294

I suspect it's related to windows coding: 
```
podCheckCmd = []string{"powershell.exe", "-Command", "Get-Content C:\\mnt\\test-1\\data.txt"}
```
While I have no luck to fix it, it sometimes works, sometimes not.

cc @adelina-t @marosset

**Comment by andyzhangx** [comment]
cc @chewong

**Comment by adelina-t** [comment]
I'm pretty sure it's the Get-Content Command. Just tried, same for me, sometimes works, sometimes not. I'll try to replace it with something else, see if it repros.

**Comment by jsturtevant** [comment]
looks like it might be encoding issue.  Could try being explicit with -encoding for `Get-Content` and the out-put functions that create the content:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3f4eae6d74d187363ea80873540462cc45987f68/test/e2e/suite_test.go#L192

**Comment by liggitt** [comment]
do we have feedback from sig-windows whether this is a regression and/or is release blocking?

**Comment by michmike** [comment]
@jsturtevant , @adelina-t  or @marosset do you have insight to Jordan's last question?
is this a new issue or has always been there?

**Comment by andyzhangx** [comment]
> @jsturtevant , @adelina-t or @marosset do you have insight to Jordan's last question?
> is this a new issue or has always been there?

It's more like a coding issue in the test case, I have already disabled this e2e test on Windows, and there is a tracking issue to fix it: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/381
