### ISSUE TITLE
how to disable exec into a pod

### ISSUE THREAD

**Issue by sunchill06** [kubernetes/kubernetes#93292]
@liggitt 

how to do this?
An admin that wants to remove access to exec or attach should remove all access to pods/exec and pods/attach.

I tried this:
- apiGroups: [""]
  resources: ["pods/exec", "pods/attach"]
  verbs: [""]

But seems like this is not the right way to do it. Could you please suggest how can I make sure that pods/exec and pods/attach are not available to the users.

**Comment by liggitt** [comment]
RBAC permissions are additive, so if a user is granted a role that already contains exec permissions (like the admin or edit roles do), adding another rule related to exec will not do anything.

Your options are:
1. remove the exec permissions from the existing roles (the built-in exec permission added to the `admin` and `edit` clusterroles originates in the `system:aggregate-to-edit` clusterrole). for built-in roles, you will also need to [disable auto-reconciliation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#auto-reconciliation) to prevent the removed permissions from being readded.
2. define your own roles with the subset of permissions you want, and only grant those to your users
3. add a [ValidatingWebhookConfiguration admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) that intercepts requests to pods/exec and forbids them

**Comment by sunchill06** [comment]
@liggitt, thanks for your valuable input. 

Though I have one more query here.

kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: webhook
webhooks:
  - name: webhook.example.com
    rules:
      - operations: ["CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods/exec"]

Will it block exec into the pod or even the commands that I run from outside the pod?

The intention is to just block exec-ing inside the pod, and not executing commands from outside.

**Comment by liggitt** [comment]
One nit, should be `apiGroups: [""]`

> Will it block exec into the pod or even the commands that I run from outside the pod?

That will intercept requests to exec into the pod. I'm not sure what you mean by "commands that I run from outside the pod"

**Comment by sunchill06** [comment]
so what I mean is following:

kubectl exec -it <podname> -n <namespace> -- bash [ I want to block this ]
kubectl exec -it <podname> -n <namespace> -- cat /etc/hosts [ But this should continue working ]

**Comment by liggitt** [comment]
> kubectl exec -it -n -- bash [ I want to block this ]
> kubectl exec -it -n -- cat /etc/hosts [ But this should continue working ]

your webhook would be sent the pod exec options and it could decide whether to allow or reject the request

**Comment by sunchill06** [comment]
@liggitt 

Thanks a lot for your inputs. Is it possible for you to share any sample code/example on how to write a validation webhook specifically for exec as I am not really familiar with go?

Any help would be really great.
