### ISSUE TITLE
node-kubelet-conformance fails with "pod ... was not deleted"

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#93302]
**Which jobs are failing**:

ci-kubernetes-node-kubelet-conformance

**Which test(s) are failing**:

- Variable Expansion should succeed in writing subpaths in container
- Variable Expansion should verify that a failing subpath expansion can be modified during the lifecycle of a container

**Since when has it been failing**:

Since Fri Jul 10 15:41:46 2020 -0700, when [this PR](https://github.com/kubernetes/kubernetes/pull/92784) was merged

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-node-kubelet#node-kubelet-conformance

**Reason for failure**:

Used DeletePropagationForeground option to delete test pod introduced by [this commit](https://github.com/kubernetes/kubernetes/commit/af91e76df80c8c78e2d42ada466a4689398bf887) 

**Anything else we need to know**:

The test pod stuck in Terminating state until 5m timeout of DeletePodWithWait expired.
It happens with empty pod as well. Here is a simplified ginkgo test case that triggers this failure:
```
framework.ConformanceIt("trigger stuck pod deletion", func() {
		pod := newPod([]string{"sh", "-c", "sleep 600"}, nil, nil, nil)
		ginkgo.By("creating the pod")
		var podClient *framework.PodClient = f.PodClient()
		pod = podClient.Create(pod)

		ginkgo.By("waiting for pod running")
		err := e2epod.WaitTimeoutForPodRunningInNamespace(f.ClientSet, pod.Name, pod.Namespace, framework.PodStartShortTimeout)
		framework.ExpectNoError(err, "while waiting for pod to be running")

		ginkgo.By("deleting the pod gracefully")
		err = e2epod.DeletePodWithWait(f.ClientSet, pod)
		framework.ExpectNoError(err, "failed to delete pod")
	})
```

The pod phase is "Failed" and container reason is "Error" for some reason:
```
# kubectl get pod -n var-expansion-1646 var-expansion-f5a6d071-e1c0-40a6-9292-49807b1f862f -o yaml |grep -i -B15 fail
    image: busybox:1.29
    imageID: docker-pullable://busybox@sha256:8ccbac733d19c0dd4d70b4f0c1e12245b5fa3ad24758a11035ee505c629c0796
    lastState: {}
    name: dapi-container
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://7b60220b917510a6819d04774ebf7be660a67cc85ceea5e99174322b26190910
        exitCode: 137
        finishedAt: "2020-07-21T16:35:39Z"
        reason: Error
        startedAt: "2020-07-21T16:35:07Z"
  hostIP: 10.237.72.179
  phase: Failed
```

Reverting above commit or changing delete option to DeletePropagationBackground should fix this.

**Comment by liggitt** [comment]
/sig storage

cc @msau42

**Comment by bart0sh** [comment]
@liggitt I think @pohly's change just triggered the underlying issue. DeletePropagationForeground option doesn't work as expected it seems.

**Comment by liggitt** [comment]
does node-kubelet-conformance run the controller-manager? the kube-controller-manager is responsible for deleting objects with a foreground finalizer on them, but I don't see any kube-controller-manager logs gathered in the artifacts for one of those test failures - https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-conformance/1284533676490625024/

**Comment by bart0sh** [comment]
I could reproduce the issue for commit 6c6cd2deeb03040d458b00824fd6c1a900a81b51 (before 'generic ephemeral inline volumes' PR was merged) + 'use foreground deletion' af91e76df80c8c78e2d42ada466a4689398bf887 commit.

**Comment by msau42** [comment]
@kubernetes/sig-storage-test-failures

**Comment by liggitt** [comment]
> I could reproduce the issue for commit [6c6cd2d](https://github.com/kubernetes/kubernetes/commit/6c6cd2deeb03040d458b00824fd6c1a900a81b51) (before 'generic ephemeral inline volumes' PR was merged) + 'use foreground deletion' [af91e76](https://github.com/kubernetes/kubernetes/commit/af91e76df80c8c78e2d42ada466a4689398bf887) commit.

yeah, I tend to think switching that e2e helper method for all callers was not a good idea

**Comment by bart0sh** [comment]
@liggitt it looks like node e2e runs only etcd, api server and namespace controller: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/services/internal_services.go#L57:L73

I don't think it makes sense to run controller-manager just to fix this failure.
Would modifying test framework to set DeletePropagationBackground  option for e2e node tests be correct solution?

**Comment by msau42** [comment]
For a quick fix, I would suggest just reverting the change for now. Long term, yes, it should be configurable per test.

**Comment by msau42** [comment]
Also do we have plans to make this job a blocking presubmit test so we can find these problems earlier?

**Comment by liggitt** [comment]
> For a quick fix, I would suggest just reverting the test change for now. Long term, yes, it should be configurable per test.

I agree, we should revert https://github.com/kubernetes/kubernetes/commit/af91e76df80c8c78e2d42ada466a4689398bf887

**Comment by bart0sh** [comment]
if we need a PR for that I can prepare it.

**Comment by liggitt** [comment]
> if we need a PR for that I can prepare it.

that would be great, thanks

**Comment by liggitt** [comment]
> Also do we have plans to make this job a blocking presubmit test so we can find these problems earlier?

putting my @BenTheElder hat on, probably not? more hour+ tests that run on every PR are a non-goal

**Comment by BenTheElder** [comment]
The SIG / OWNERs should enable testgrid alerts on failures, if periodic testing is not sufficient you can use a postsubmit to run whenever we merge code.

We're not looking to rely further on presubmit, as is we're running too much there leading to excessive resource usage and inability to merge fixes like this in a timely manner between one thing or the other flaking heavily.
