### ISSUE TITLE
ResourceConfigForPod doesn't consider initContainers when computing cpuLimitsDeclared / memoryLimitsDeclared

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93300]
I noticed ResourceConfigForPod isn't checking `initContainers` here:

https://github.com/kubernetes/kubernetes/blob/b6174e605fd6e23b48131dec9e45043b38372c3c/pkg/kubelet/cm/helpers_linux.go#L144-L150

The methods called by `ResourceConfigForPod` (`PodRequestsAndLimits` and `GetPodQOS`) **do** check `initContainers`, but it looks like `cpuLimitsDeclared` and `memoryLimitsDeclared` can be true for burstable pods even when some of the initContainers do not declare cpu/memory limits.

I'm not sure what the implications of setting these values are if an initContainer has no cpu or memory limit:

https://github.com/kubernetes/kubernetes/blob/b6174e605fd6e23b48131dec9e45043b38372c3c/pkg/kubelet/cm/helpers_linux.go#L178-L184

/sig node
/assign @dashpole

**Comment by pacoxu** [comment]
After reading the code, I prefer that this is a bug according to [the website doc](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed).
> These restrictions apply to init containers and app containers equally.

@dashole  would you confirm?

/assign
I opened #103107.
