### ISSUE TITLE
capg-conformance-v1alpha3-k8s-master (ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts)

### ISSUE THREAD

**Issue by sayanchowdhury** [kubernetes/kubernetes#93309]
**Which jobs are failing**:
`capg-conformance-v1alpha3-k8s-master (ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts)`

**Which test(s) are failing**:
`[sig-instrumentation] Events API should delete a collection of events [Conformance] `
`[sig-instrumentation] Events API should ensure that an event can be fetched, patched, deleted, and listed [Conformance] `

**Since when has it been failing**:
`07-20-20 05:52 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1alpha3-k8s-master

**Reason for failure**:
```
test/e2e/framework/framework.go:597
Jul 20 13:56:42.603: failed to create test event
Unexpected error:
    <*errors.StatusError | 0xc002d83c20>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {Name: "", Group: "", Kind: "", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
    the server could not find the requested resource
occurred
```

**Anything else we need to know**:
/sig cluster-lifecycle
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19

**Comment by liggitt** [comment]
it seems like the cluster being brought up does not have the events.k8s.io/v1 API enabled

**Comment by detiber** [comment]
Digging into this further now

**Comment by detiber** [comment]
So...  The issue boils down to the way we are pulling in the k8s artifacts and the conformance test binary for this test:
- The installed kubernetes version is pulled in through the ci/master.txt version marker, which is currently referencing an older build (from July 1st before the eventsv1 commit was merged).
- The test binary is built from the current state of master

While we could target a different version marker file to get the version, I believe this issue should be resolved without any further intervention with https://github.com/kubernetes/test-infra/pull/18290#issuecomment-658547088 once it is finished and merged.

**Comment by justaugustus** [comment]
This should be fixed in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/308.

**Comment by justaugustus** [comment]
Opened accompanying PRs for other Cluster API variants:
- capz: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/845
- capa: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1845

**Comment by hasheddan** [comment]
Thanks @justaugustus!
