### ISSUE TITLE
How to search specific pod?

### ISSUE THREAD

**Issue by sakaia** [kubernetes/kubernetes#93315]
I am trouble shooting with port-proxy error. following error says pod bbb007990753841253c0e13c66675ec527a45565d6b610ea6e01d0c6b3669660 

But I cannot found it with `kubectl get pods -A -o wide`
How should I use the command?

```bash
E0722 02:20:51.372460   27715 portforward.go:400] an error occurred forwarding 8082 -> 80: error forwarding port 80 to pod bbb007990753841253c0e13c66675ec527a45565d6b610ea6e01d0c6b3669660, uid : failed to execute portforward in network namespace "/var/run/netns/cni-5bdc4ac2-8454-5438-75cb-c7af55de6719": socat command returns error: exit status 1, stderr: "2020/07/22 02:20:51 socat[28914] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused\n"
```

p.s. following command does not helpful for tracking this issue. There is no output.

```bash
kubectl get pod -o custom-columns="name:.metadata.name,UUID:.metadata.uid" -A | grep bbb00
```
I try to execute following command.

```bash
kubectl get pod bbb007990753841253c0e13c66675ec527a45565d6b610ea6e01d0c6b3669660 -A
```
output is follows

```bash
error: a resource cannot be retrieved by name across all namespaces
```

In searching the code. following source says pod name
https://github.com/kubernetes/kubernetes/blob/v1.18.6/pkg/kubelet/server/portforward/httpstream.go#L236-L254

**Comment by liggitt** [comment]
to search for a pod name across all namespaces, you can do:

```
kubectl get pods -A | grep $name
```

if you are looking for a particular pod uid, you can do:
```
kubectl get ns -o jsonpath='{.items[?(@.metadata.uid=="$uid")].metadata.name}{"\n"}'
```

**Comment by sakaia** [comment]
/close

Thank you. This problem is not solved. but the environment is already destroyed.
