### ISSUE TITLE
Claims require redundant namespace specification?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#9331]
Looks like when making claims, you have to specify `--namespace` **EVEN** when the namepsace is specified in the yaml file already.     Why is it that namespace declarations in the YAML file force the user to enter a command line option ?  My guess:  its a bug.   But it could be some kind of sanity feature which prevents users from accidentally creating claims which are in a unintended namespace?

```
# kubectl create -f gluster-pv.yaml 
persistentvolumes/pv0001
[root@f21-1 glusterfs]# kubectl get pv
NAME      LABELS    CAPACITY     ACCESSMODES   STATUS      CLAIM
pv0001    <none>    2147483648   RWX           Available   
[root@f21-1 glusterfs]# cat gluster-claim.yaml 
kind: PersistentVolumeClaim
apiVersion: v1beta3
metadata:
  name: myclaim-1
  namespace: gluster-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
[root@f21-1 glusterfs]# 
[root@f21-1 glusterfs]# 
[root@f21-1 glusterfs]# kubectl create -f gluster-claim.yaml 
the namespace from the provided object "gluster-ns" does not match the namespace "default". You must pass '--namespace=gluster-ns' to perform this operation.
```

**Comment by jayunit100** [comment]
cc @wattsteve @rootfs @bchilds

**Comment by rootfs** [comment]
add @markturansky for claim ns.
glusterfs uses pod namespace

**Comment by markturansky** [comment]
This is not correct.

You should be already within a namespace when creating the claim (or any object in a namespace for that matter).  

You *can* use the --namespace CLI arg, but it is better to be working in the namespace already.

**Comment by jeffvance** [comment]
mark, so does the mean using something like kubectl config context=xx ?

**Comment by markturansky** [comment]
@jeffvance yes, that is correct.  Set the context for the namespace you are working within.

**Comment by jayunit100** [comment]
Okay, so your saying using `--namespace=gluster-ns` is bad style.  But shouldnt it be equivalent, nonetheless, to the results of running a pod with `namespace: gluster-ns` ?

**Comment by thockin** [comment]
Nothing here should be specific to claims.

**Comment by markturansky** [comment]
@jayunit100 can this issue be closed?
