### ISSUE TITLE
[Flaky Test] some tests affected by pod scheduling timeouts

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93334]
**Which jobs are failing**:

`conformance-ga-only (ci-kubernetes-conformance-kind-ga-only)`

**Which test(s) are failing**:

`Overall`

**Since when has it been failing**:

`2020-07-21 20:08 CDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only

**Reason for failure**:

Pod scheduling timeout (see https://prow.k8s.io/prowjob?prowjob=cb203da3-cbb7-11ea-8f9c-6aebfd5be0c2)

**Anything else we need to know**:

/cc @kubernetes/ci-signal @kubernetes/test-infra-maintainers 
/sig testing
/priority critical-urgent

**Comment by liggitt** [comment]
scheduling timeout is not job-specific, can we collapse to a single issue for that?

relevant:
* https://github.com/kubernetes/test-infra/pull/18416
* https://github.com/kubernetes/test-infra/pull/18420

@BenTheElder

**Comment by BenTheElder** [comment]
test-infra-maintainers is probably not a very useful alias here, maybe sig testing something

I think we may have extra confusion here because some of these run in a CNCF build cluster which we don't have auto-deploy manifests to @spiffxp

**Comment by hasheddan** [comment]
@liggitt would you prefer that be tracked here or in k/test-infra?

**Comment by liggitt** [comment]
> @liggitt would you prefer that be tracked here or in k/test-infra?

I'm not aware of anything actionable in this repo that would help fix pod pending timeouts ... seems like test-infra to me, but I'll let ben comment on where he'd like it tracked

**Comment by BenTheElder** [comment]
this is a test-infra bug, but I'd rather focus on getting it closed.

**Comment by BenTheElder** [comment]
I'm not sure what the default CPU request is in that other cluster

**Comment by BenTheElder** [comment]
had to help with some internal issues, see this now:
```
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"LimitRange","metadata":{"annotations":{},"name":"cpu-limit-range","namespace":"test-pods"},"spec":{"limits":[{"defaultRequest":{"cpu":"250m"},"type":"Container"}]}}
  creationTimestamp: "2020-07-21T21:29:36Z"
  name: cpu-limit-range
  namespace: test-pods
  resourceVersion: "1954535288"
  selfLink: /api/v1/namespaces/test-pods/limitranges/cpu-limit-range
  uid: 468d2383-cb99-11ea-be45-42010a800072
spec:
  limits:
  - defaultRequest:
      cpu: 250m
    type: Container
```
the nodes in that cluster have less CPU available to request due to having network policy enabled (for no apparent reason?)
so jobs in that cluster need to request something like 100m less maximum. sending a PR. not sure how this was missed before.

**Comment by BenTheElder** [comment]
it would be great if we could also disable the unused network policy addon in that wg-k8s-infra cluster at some point.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/18431

**Comment by BenTheElder** [comment]
/reopen
we need to ensure this change takes effect successfully, sorry about that

**Comment by onlydole** [comment]
Is it okay if I assign this to you until it's closed, @BenTheElder?

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/1286106121483849728
/assign
/close

**Comment by BenTheElder** [comment]
some pods are still going to hit the issue in the title, but what was mostly discussed here was a specific issue that _reliably_ caused this for one test.

that issue is resolved.

flaky failure to run the tests in prow is not, but it's also probably not going to be easily, and not new.
