### ISSUE TITLE
Clean up sig-storage e2e test utils

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93347]
**What would you like to be added**:

There are a number of places where sig-storage e2e tests make use of shared utilities to perform common operations such as creating or deleting Pods. These helpers are spread throughout files in `test/e2e/storage`. Many of these helpers could be consolidated into `test/e2e/storage/utils` or incorporated into `test/e2e/framework` for use across tests for other SIGs.

**Why is this needed**:

There is currently a fair amount of duplicate code and changes can have unintended side-effects. Consolidating utilities to a single location will make it more clear that they are meant to be depended on my multiple tests / SIGs / etc.

Ref: https://github.com/kubernetes/kubernetes/pull/93332

/sig storage
/kind cleanup
/assign
/priority important-longterm

**Comment by mayankshah1607** [comment]
Hi, @hasheddan !
This one looks interesting to me. Mind if I take it up if no one has already? Thanks :)

**Comment by pacoxu** [comment]
I need to go though all functions in e2e/storage 
- [x] this is mentioned in #93332 comments: StopPodAndDependents: e2e/storage/testsuites/provisioning.go to  test/e2e/storage/utils/pods.go
- [ ] pod create and wait 
- [ ] pvc create and wait
- [ ] node related

Probably, I need read most of the functions.
