### ISSUE TITLE
[Flaky test] [sig-windows] ci-kubernetes-e2e-aks-engine-azure-master-staging-windows

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#93349]
**Which jobs are flaking**:
ci-kubernetes-e2e-aks-engine-azure-master-staging-windows

**Which test(s) are flaking**:
There is a race condition in the one of the tests and they are run in parallel  so if varies, some of the recent ones are:

```
[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset [Conformance]
[sig-node] Downward API should provide host IP as an env var [NodeConformance] [Conformance]
[sig-storage] Secrets should be consumable from pods in volume with mappings [NodeConformance] [Conformance]
```

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-windows-azure#aks-engine-azure-windows-master-staging

**Reason for failure**:
gmsa webhooks is not responding:

```
    Internal error occurred: failed calling webhook "admission-webhook.windows-gmsa.sigs.k8s.io": Post "https://gmsa-webhook.gmsa-full-test-windows-5735-webhook.svc:443/mutate?timeout=30s": dial tcp 10.0.161.18:443: connect: connection refused
```

The gmsa test `GMSA Full [Slow] GMSA support works end to end` creates the webhook and then removes it when the test is complete:

https://github.com/kubernetes/kubernetes/blob/548124828c948d69945cc3ef93a6136228bc3d1e/test/e2e/windows/gmsa_full.go#L108

causing failures for any running tests

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/sig windows
/assign

**Comment by jsturtevant** [comment]
@adelina-t thanks for helping me track this down

**Comment by jsturtevant** [comment]
The current plan is to move the deployment of the webhook out of the individual test and make sure it is installed at cluster provisioning time.

@ddebroy do you see any issues?  

It doesn't look like the gce tests run the `GMSA Full` tests so this should not affect the tests runs there but in the future if added would need to be set up in https://github.com/kubernetes-sigs/windows-testing/tree/master/gce test scripts.  fyi - @pjh

**Comment by ddebroy** [comment]
hey @jsturtevant yes, deploying the webhook at cluster deployment definitely works. It was scoped to the test to reduce blast radius when things weren't super stable.

**Comment by adelina-t** [comment]
@jsturtevant One alternative to creating the webhook at provisioning time ( I still thing this is the cleaner version of the fix ), we can just mark GMSA tests [SERIAL], thus we won't have a problem with this race.

**Comment by jsturtevant** [comment]
I looked into this some more and found we have three options:

- Install the webhook at provisioning time.  This solved the problem above but causes the test `[sig-windows] [Feature:Windows] GMSA Kubelet [Slow] kubelet GMSA support when creating a pod with correct GMSA credential specs passes the credential specs down to the Pod's containers` to fail because the webhook looks for a gmsa CRD and [rejects requests that do not have it set](https://github.com/kubernetes-sigs/windows-gmsa/blob/975f69743c5f49daaa5fc488a41ee21c11e126ed/admission-webhook/webhook.go#L271-L275).  One option is to update the `GMSA Kubelet` test to add a crd in the case the webhook is installed
- Update the gMSA webhook to allow requests that do not have the `GMSACredentialSpecName` name set but do have the `GMSACredentialSpec` set.  This would allow the "GMSA Kubelet" test to pass because it would not be rejected by the webhook. 
- Mark the `GMSA Full` tests as `[Serial]` which would move the test out of the parallel jobs and allow the `GMSA Kubelet` test to still function.  

I am leaning towards the third option as the first option of modifying the "kubelet GMSA" test would be adding extra steps (installing crd and RBAC roles) that have nothing to do with the test.  The second option seems like it could be a fair change to the webhook but I don't know enough about the rest of the webhook logic and design and would be a change in behavior of the webhook.

The third option is simpler but would require changes to the serial tests to enable the domain controller.  The added benefit would be that the tests that run in parallel wouldn't require domains controller to be set up which would speed up provision time and after I ran an experimental  test run indicated that it might bring the test runs under 1hr (currently 1.4hrs).  It would add some additional time to the serial tests which are already pretty slow (3+ hrs).

@adelina-t @ddebroy do you have any thoughts?
