### ISSUE TITLE
componentstatuses doesn't work when Scheduler and Controller Manager are running on secure port

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes/kubernetes#93342]
**What happened**:

We recently upgraded to 1.17.9 using kubeadm and now the controller manager and scheduler are serving on their default secure port and the old insecure port is 0 which disabled it. Now when you run `kubectl get componentstatuses` it shows that these two components are unhealthy even though they are not. Looking at the output the health check is hitting the old port and using http instead of https.

```
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
```

**What you expected to happen**:

I would expect the componentstatuses to use the secure ports that these components are running on and show they are healthy.

**How to reproduce it (as minimally and precisely as possible)**:

Built a control-plane node making sure that the scheduler and controller-manager are running only their default secure port. After it is started up run the `kubectl get componentstatuses` against that control-plan node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.9
- Cloud provider or hardware configuration: on-prem vmware
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 3.10.0-1127.10.1.el7.x86_64
- Install tools: kubeadm

**Comment by liggitt** [comment]
The componentstatus implementation does not work in many topologies... it is a hard-coded implementation in the API server that assumes a particular topology for the scheduler/controller manager.

See discussions in https://github.com/kubernetes/kubernetes/issues/19570 and https://github.com/kubernetes/enhancements/issues/553 about why this approach should be deprecated and removed.

Changing the hard-coded values in the kube-apiserver would be as likely to break existing users that currently configure their components in a way that matches the hard-coded expectations.

/cc @deads2k

**Comment by deads2k** [comment]
> The componentstatus implementation does not work in many topologies... it is a hard-coded implementation in the API server that assumes a particular topology (localhost, unsecured) for the scheduler/controller manager.
> 
> See discussions in #19570 and [kubernetes/enhancements#553](https://github.com/kubernetes/enhancements/issues/553) about why this approach should be marked as deprecated (immediately) and removed (eventually... the deprecation policy is unclear about how to remove a v1 endpoint... but leaving it perpetually available and guaranteed to be broken for some number of clusters doesn't seem right).
> 
> Changing the hard-coded values in the kube-apiserver would be as likely to break existing users that currently configure their components in a way that matches the hard-coded expectations.
> 
> /cc @deads2k

I agree that this should be deprecated and removed and recently commented to similar effect in a PR.  The endpoint has always been unreliable across deployments and to make it differently unreliable doesn't seem like a significant improvement.  It functions for the narrow case it has always handled, but that case has not aged well and neither has the design (as noted in the linked enhancments). 

Interestingly, if we had simply deprecated 2.5 years ago (as desired in the enhancement) I think the outcome here would have been clearer.

**Comment by liggitt** [comment]
behavior of the componentstatus API cannot be changed to suit a particular deployment in a way that will break other consumers of the API for whom it is currently functioning

/close

**Comment by arthurlogilab** [comment]
Got hit by this problem too. This was a "display" problem for our use in rancher. As suggested in https://github.com/rancher/rancher/issues/28802 (see translation : https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fgithub.com%2Francher%2Francher%2Fissues%2F28802 ) removing `--port=0` from the configuration fixed it (for now). Not entirely sure what the security consequences are though.

**Comment by neolit123** [comment]
Hi, the Http ports should be disabled by deafault in the components, but
they are not. The security issue is not severe (for now) but if you did not
specify --address the component can end up listening on a public interface
and e.g the whole internet can see the metrics.

**Comment by avoidik** [comment]
apparently, with removed "--port=0" line you've been enabling insecure ports
