### ISSUE TITLE
Can daemonsets declare dependencies

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#93366]
**What would you like to be added**:
When I have N daemonsets to be deployed on a Node, can I say

DS-N requires "DS-A, DS-B"

Similar to systemd requires/requisite/after ... So DS-N is started only after DS-A & DS-B starts.

**Why is this needed**:
Often these daemonsets are inter-dependent,that when any of the daemons, say daemon-Y depends on goes down, it would be good, if daemon-Y goes down too and comes up only after all its dependencies are back again.

**Is this already feasible?**

**Comment by liggitt** [comment]
No, cross pod (or even cross container) start order is not expressible via the API
