### ISSUE TITLE
`kubectl wait --for=delete` fails on 404

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#93365]
One use-case of `kubectl wait --for=delete` is to wait for a lot of resources that you have just deleted. Unfortunately, this workflow is racy because `kubectl wait --for=delete` will fail when encountering a resource that doesn't exist (yes, it's probably already gone). I suspect we should just consider 404 resources to be already gone and integrate that condition as part of the normal flow.

/sig cli
/kind bug

**Comment by liggitt** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/87747 ?

**Comment by zhouya0** [comment]
@liggitt yes, I tried to add `ignore-not-found` in `kubectl wait` in https://github.com/kubernetes/kubernetes/pull/90969. But that PR seems not complete.

**Comment by apelisse** [comment]
The PR merged, I think we're good now!
