### ISSUE TITLE
Terminal commas in APF debug listings

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#93362]
**What happened**:
I fetched some CSV data from the new /debug endpoints of API Priority and Fairness, and found that the lines all end with a comma.  Since this is intended to be CSV data, that means there is a blank column at the end of every line.  I think we do not want that.

Here is an example:
```
$ kubectl get --raw /debug/api_priority_and_fairness/dump_priority_levels
PriorityLevelName, ActiveQueues, IsIdle, IsQuiescing, WaitingRequests, ExecutingRequests, 
workload-low,      0,            true,   false,       0,               0,                 
global-default,    0,            true,   false,       0,               0,                 
exempt,            <none>,       <none>, <none>,      <none>,          <none>,            
catch-all,         0,            true,   false,       0,               0,                 
system,            0,            true,   false,       0,               0,                 
leader-election,   0,            true,   false,       0,               0,                 
workload-high,     0,            true,   false,       0,               0,                 
```

**What you expected to happen**:
No column full of blanks.

**How to reproduce it (as minimally and precisely as possible)**:
Enable API Priority and Fairness, then
```
kubectl get --raw /debug/api_priority_and_fairness/dump_priority_levels
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  mspreitz@mjs-dev-1:~$ kubectl version
  Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.1.3377+33edf0dc89ba6c", GitCommit:"33edf0dc89ba6ccdc480adb477a31e4feed1e883", GitTreeState:"clean", BuildDate:"2020-07-22T21:01:59Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: x86 VM with 16 "CPUs" and 32 GiB of memory
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux mjs-dev-1 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hack/local-up-cluster.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
/cc @yue9944882 
/cc @lavalamp 
/cc @deads2k 
@rngy

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by fedebongio** [comment]
looks like the right people is in cc :)
