### ISSUE TITLE
Detect "kubectl apply" to resources currently being deleted

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#93363]
Users should be able to know and prevent resources that are being deleted from being applied, since it can be misleading, and racy when they delete and re-apply quickly.

We could offer this through two different user-experience:
1. Create a warning when we detect that the changes are done to a resource that has the `deletionTimestamp` set. The warning could happen on many occasions: when applying, when diffing, doing server dry-run, for both CSA and SSA.
2. Create a new option to fail when applying resources that have the `deletionTimestamp` set: `--fail-if-deleting`. This can be implemented by sending a nil timestamp, which will result in an update failure from the server if it's already set (thanks @lavalamp for the suggestion).

/wg api-expression
/sig cli
/kind feature

**Comment by apelisse** [comment]
Actually I suspect that's a bug. No one has ever wanted to apply to an object that is being deleted.

So I'm suggesting something different:
1. Fail apply on objects that are currently being deleted by using the mechanism describe in the original post
2. Create an option to allow apply on these objects
3. Backport that fix to former versions of kubernetes

**Comment by soltysh** [comment]
Assuming you're entire flow works around apply the fact that something is being removed during one of apply invocation is definitely a bug. That's the whole premise of a proper git-ops management, s I understand it. Thus I agree with Antoine that this is a bug, and it's ok to add a fall-back for those users that occasionally using apply.

**Comment by apelisse** [comment]
@zhouya0 would you be interested in solving that bug next?

**Comment by zhouya0** [comment]
Yes, I'll try to do that. 
/assign

**Comment by apelisse** [comment]
OK, Feel free to ask me any question on slack if you want, thanks @zhouya0!

**Comment by apelisse** [comment]
Yeah, a client-side warning seems good enough for now.

**Comment by apelisse** [comment]
Actually solved by #95544

/close
