### ISSUE TITLE
Outdated code comment for ListWatchUntil

### ISSUE THREAD

**Issue by heyste** [kubernetes/kubernetes#93360]
[wait.Until](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/watch/until.go#L96-L98) has an outdated code comment that refers to the func `ListWatchUntil`. That function was removed in #90855 

```
// Until wraps the watcherClient's watch function with RetryWatcher making sure that watcher gets restarted in case of errors.
// The initialResourceVersion will be given to watch method when first called. It shall not be "" or "0"
// given the underlying WATCH call issues (#74022). If you want the initial list ("", "0") done for you use ListWatchUntil instead.
```
Can this comment be updated what should be used instead. TIA

/kind documentation

**Comment by fedebongio** [comment]
Hi! @heyste thank you for your finding! Would you send us a PR and we will review it? it's the most effective way of fixing it! Thank you in advance!
