### ISSUE TITLE
unexpected results from GET /debug

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#93361]
**What happened**:
I tried fetching prefixes of the new debug endpoints, and got a listing of / instead.

```
$ curl http://localhost:8080/debug
{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/crd-informer-synced",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/priority-and-fairness-config-consumer",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/livez",
    "/livez/etcd",
    "/livez/log",
    "/livez/ping",
    "/livez/poststarthook/crd-informer-synced",
    "/livez/poststarthook/generic-apiserver-start-informers",
    "/livez/poststarthook/priority-and-fairness-config-consumer",
    "/livez/poststarthook/start-apiextensions-controllers",
    "/livez/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/readyz",
    "/readyz/etcd",
    "/readyz/informer-sync",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/crd-informer-synced",
    "/readyz/poststarthook/generic-apiserver-start-informers",
    "/readyz/poststarthook/priority-and-fairness-config-consumer",
    "/readyz/poststarthook/start-apiextensions-controllers",
    "/readyz/poststarthook/start-apiextensions-informers",
    "/readyz/shutdown",
    "/version"
  ]
}$ 
```

```
$ curl http://localhost:8080/debug/api_priority_and_fairness
{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/crd-informer-synced",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/priority-and-fairness-config-consumer",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/livez",
    "/livez/etcd",
    "/livez/log",
    "/livez/ping",
    "/livez/poststarthook/crd-informer-synced",
    "/livez/poststarthook/generic-apiserver-start-informers",
    "/livez/poststarthook/priority-and-fairness-config-consumer",
    "/livez/poststarthook/start-apiextensions-controllers",
    "/livez/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/readyz",
    "/readyz/etcd",
    "/readyz/informer-sync",
    "/readyz/log",
    "/readyz/ping",
    "/readyz/poststarthook/crd-informer-synced",
    "/readyz/poststarthook/generic-apiserver-start-informers",
    "/readyz/poststarthook/priority-and-fairness-config-consumer",
    "/readyz/poststarthook/start-apiextensions-controllers",
    "/readyz/poststarthook/start-apiextensions-informers",
    "/readyz/shutdown",
    "/version"
  ]
}$ 
```

**What you expected to happen**:
I expected to get a listing of the available ways to extend the URL path I fetched.

**How to reproduce it (as minimally and precisely as possible)**:
As shown above, with API Priority and Fairness enabled.  I test it like this:
```
RUNTIME_CONFIG=flowcontrol.apiserver.k8s.io/v1alpha1=true FEATURE_GATES=APIPriorityAndFairness=true LOG_LEVEL=7 hack/local-up-cluster.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  mspreitz@mjs-dev-1:~$ kubectl version
  Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$",   GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.1.3377+33edf0dc89ba6c", GitCommit:"33edf0dc89ba6ccdc480adb477a31e4feed1e883", GitTreeState:"clean", BuildDate:"2020-07-22T21:01:59Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: x86 VM with 16 "CPUs" and 32 GiB of memory
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): Linux mjs-dev-1 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hack/local-up-cluster.sh
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
Yeah our index page is not very smart.

**Comment by caesarxuchao** [comment]
FWIW, the current behavior is defined here: https://github.com/kubernetes/kubernetes/blob/e884b40e73c52227342e591ddf996cef262b3bd4/staging/src/k8s.io/apiserver/pkg/server/config.go#L660-L665

If the path is not handled, the apiserver always returns the index page.

Also note that some debug endpoints explicitly choose to not be included in the index page: https://github.com/kubernetes/kubernetes/blob/e884b40e73c52227342e591ddf996cef262b3bd4/staging/src/k8s.io/apiserver/pkg/server/routes/profiling.go#L31-L35

/unassign

**Comment by yue9944882** [comment]
i think it makes sense to hide the debugging endpoints (pprof and flowcontrol) from users.. IIRC the dumpping endpoint for gc controller in KCM is also invisible. if we're listing them in the index, we should better make sure there're explicit RBAC rules protecting these endpoints..

**Comment by yue9944882** [comment]
> Also note that some debug endpoints explicitly choose to not be included in the index page:

it makes sense to me hiding the debugging endpoints from users in the root index, but what @MikeSpreitzer purposing is to list the existing paths under `/debug` prefix. obviously the users already knows the existence of debugging endpoints when they're looking for `/debug`, so it's probably not a good idea to make the endpoints completely invisible from users..

>   "/livez",
    "/livez/etcd",
    "/livez/log",
    "/livez/ping",
    "/livez/poststarthook/crd-informer-synced",
    "/livez/poststarthook/generic-apiserver-start-informers",
    "/livez/poststarthook/priority-and-fairness-config-consumer",
    "/livez/poststarthook/start-apiextensions-controllers",
    "/livez/poststarthook/start-apiextensions-informers",

btw if we're providing index for subpaths, for a lower verbosity, we should consider to merge the above pathes into:

>  "/livez"
    "/livez/",
