### ISSUE TITLE
Disable failing sd-logging test jobs until fixed

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93375]
it looks like the following test jobs have been solidly failing for a couple weeks:
* https://testgrid.k8s.io/google-gce#gci-gce-sd-logging&width=5
* https://testgrid.k8s.io/sig-node-containerd#e2e-gci-sd-logging-k8s-resources&width=5
* https://testgrid.k8s.io/sig-node-containerd#e2e-gci-sd-logging&width=5
if those are not providing useful signal, we should stop running them. CI capacity is overcommitted at the moment

(these are currently the most frequent failure in the triage board for CI jobs, see https://storage.googleapis.com/k8s-gubernator/triage/index.html)

/assign @dashpole @brancz 
/sig instrumentation

**Comment by liggitt** [comment]
cc @sig-testing for visibility

**Comment by wojtek-t** [comment]
@piosz @serathius @44past4
