### ISSUE TITLE
 plugin/loop: Loop (192.168.0.49:54616 -> 192.168.0.49:53) detected for zone "in-addr.arpa.", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8152613472028609709.5116360551987037255.in-addr.arpa."

### ISSUE THREAD

**Issue by zhaocheng173** [kubernetes/kubernetes#93379]
```
#  k get po  -owide|grep -w dns
         <none>
node-local-dns-cg2nw                           0/1     CrashLoopBackOff   4          4m45s   192.168.0.49     master   <none>           <none>
node-local-dns-lcxkr                           1/1     Running            0          4m45s   192.168.0.4      node1    <none>           <none>
```

**Which jobs are failing**:
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  <unknown>            default-scheduler  0/2 nodes are available: 2 node(s) didn't have free ports for the requested pod ports.
  Warning  FailedScheduling  <unknown>            default-scheduler  0/2 nodes are available: 2 node(s) didn't have free ports for the requested pod ports.
  Normal   Scheduled         <unknown>            default-scheduler  Successfully assigned kube-system/node-local-dns-cg2nw to master
  Normal   Pulling           81s (x4 over 4m17s)  kubelet, master    Pulling image "kubesphere/k8s-dns-node-cache:1.15.12"
  Normal   Pulled            70s (x4 over 2m43s)  kubelet, master    Successfully pulled image "kubesphere/k8s-dns-node-cache:1.15.12"
  Normal   Created           70s (x4 over 2m42s)  kubelet, master    Created container node-cache
  Normal   Started           69s (x4 over 2m41s)  kubelet, master    Started container node-cache
  Warning  BackOff           51s (x9 over 2m19s)  kubelet, master    Back-off restarting failed container
```

**Which test(s) are failing**:
`[FATAL] plugin/loop: Loop (192.168.0.49:54616 -> 192.168.0.49:53) detected for zone "in-addr.arpa.", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8152613472028609709.5116360551987037255.in-addr.arpa."`

**Since when has it been failing**:
Failure to deploy
**Testgrid link**:
no link
**Reason for failure**:
Previously, we deployed a set of POD coredNS, and implemented the capacity expansion of the instance through Autoscaler. Now we find that this performance will cause 5s timeout, so we need to use this one, so we delete the previous one. Now when deploying, Node2 runs successfully, and the first MASTER node fails
**Anything else we need to know**:

**Comment by chrisohaver** [comment]
IIUC, the failing-test label is used for tracking failures in k8s CI tests (i.e. unit tests or e2e tests).

IIUC, you are seeking assistance for resolving an error in a log, not reporting a failing.

Have you read https://coredns.io/plugins/loop#troubleshooting ?

What does your CoreDNS configmap contain?

**Comment by neolit123** [comment]
/close
reopen if needed.
