### ISSUE TITLE
Add coverage for E2Es when SELinux is enforcing

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#9338]
I'm not really sure what to call this PR since it touches so many things.  Suggestion receptacle open if anyone can think of a better name.  I have been thinking about this for a while and want to open discussion while I'm thinking about it.

TL;DR: when there's a multi-platform dashboard for E2E described in #6605, one of the things on that dashboard should be a run of e2e on at least one platform that is done with SELinux enforcing.

We need this for a couple of reasons:

1.  We need to validate that the core-use cases tested by the E2E tests are operationally solvent when SELinux is enforcing
2.  We have SELinux-specific features related to security context that cannot be effectively tested without SELinux enforcing.

I have been running local E2E runs when making changes that can touch SELinux but that isn't sustainable long-term.

@quinton-hoole @zmerlynn @pweil- @eparis @timothysc

**Comment by jayunit100** [comment]
I guess we need a general guide on how we should be running kubernetes, at all, w/ selinux enforcing as a prerequisite to this?

**Comment by timothysc** [comment]
I would like to add a test jig to jenkins to setup a fully-enforcing atomic cluster.

**Comment by pmorie** [comment]
Related: #4871
