### ISSUE TITLE
Pod IP is not in IPv4 format (2 pods on worker node have same IP of fc00:2 ::32)

### ISSUE THREAD

**Issue by imabelli** [kubernetes/kubernetes#93393]
**What happened**:
Multiple pod IPs are labeled as fc00:2 ::32

**What you expected to happen**:
I expected pod IP to be in 10.244.0.0/16 subnet, as specified during kubeadm init because I am using flannel

**How to reproduce it (as minimally and precisely as possible)**:
`kubeadm init --pod-network-cidr=10.244.0.0/16 --skip-phases=addon/kube-proxy`
`kubeadm join` on worker node yields first pod with IP address fc00:2::32 on worker node
Deploying daemonset creates new pod with same IP address fc00:2::32 on worker node

**Anything else we need to know?**:
```
admin@vlab-01:~$ kubectl get pods --all-namespaces -o wide -w
NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE   IP                NODE         NOMINATED NODE   READINESS GATES
default       route-check-ds-lktnq                 1/1     Running   0          63m   fc00:2::32        vlab-01      <none>           <none>
kube-system   coredns-66bff467f8-nsdjp             1/1     Running   0          13h   10.244.0.3        k8s-master   <none>           <none>
kube-system   coredns-66bff467f8-vdjfm             1/1     Running   0          13h   10.244.0.2        k8s-master   <none>           <none>
kube-system   etcd-k8s-master                      1/1     Running   0          13h   192.168.122.184   k8s-master   <none>           <none>
kube-system   kube-apiserver-k8s-master            1/1     Running   0          13h   192.168.122.184   k8s-master   <none>           <none>
kube-system   kube-controller-manager-k8s-master   1/1     Running   0          13h   192.168.122.184   k8s-master   <none>           <none>
kube-system   kube-flannel-ds-amd64-49w5m          1/1     Running   0          13h   192.168.122.184   k8s-master   <none>           <none>
kube-system   kube-flannel-ds-amd64-vv2sd          0/1     Error     164        13h   fc00:2::32        vlab-01      <none>           <none>
kube-system   kube-scheduler-k8s-master            1/1     Running   0          13h   192.168.122.184   k8s-master   <none>           <none>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`): SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): Flannel
- Others:

**Comment by liggitt** [comment]
are those pods hostNetwork pods?

**Comment by aojea** [comment]
it's interesting that the IPv6 pods are the only ones in the node `vlab-01`

> are those pods hostNetwork pods?

can you paste the output of `kubectl get nodes -o wide` ?

**Comment by imabelli** [comment]
hostNetwork is specified for the daemonset manifest that generated `route-check-ds-lktnq` pod. I'm not sure about this pod- `kube-flannel-ds-amd64-vv2sd` that was generated right after I joined vlab-01 to the cluster. Is it safe to use flannel without kube-proxy?

```
isl@k8s-master:~/SONiC-Core-Analyzer/SONiC_manifests$ kubectl get nodes -o wide
NAME         STATUS   ROLES    AGE   VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION      CONTAINER-RUNTIME
k8s-master   Ready    master   16h   v1.18.6   192.168.122.184   <none>        Ubuntu 16.04.6 LTS             4.4.0-186-generic   docker://19.3.11
vlab-01      Ready    <none>   15h   v1.18.6   fc00:2::32        <none>        Debian GNU/Linux 10 (buster)   4.19.0-6-2-amd64    docker://18.9.8
```

I see the IP matches the IP for my vlab-01 machine. Why would that be? Shouldn't flannel assign a pod IP in the 10.244.0.0/16 subnet?

**Comment by imabelli** [comment]
Would skipping kube-proxy be an issue? I aim to save disk space on worker nodes. I am only using k8s master to manage daemonsets running in worker nodes to ensure that each worker node is running one container of the image specified in the daemonset manifest (no self-defined services, no load balancing, no HTTP request processing). But I'm unsure if lack of kube-proxy would affect other system services
```
isl@k8s-master:~/SONiC-Core-Analyzer/SONiC_manifests$ kubectl get svc -A
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  16h
kube-system   kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   16h
```

**Comment by aojea** [comment]
> I see the IP matches the IP for my vlab-01 machine. Why would that be?

your kubelet is reporting the node address as fc00:2::32, you should check how are you configuring that node, specially the kubelet configuration

> Why would that be? Shouldn't flannel assign a pod IP in the 10.244.0.0/16 subnet?

that's a pod with `hostNetwork: true` , it takes the address of the node, not the one assigned by flannel

> Would skipping kube-proxy be an issue? I aim to save disk space on worker nodes. I am only using k8s master to manage daemonsets running in worker nodes to ensure that each worker node is running one container of the image specified in the daemonset manifest (no self-defined services, no load balancing, no HTTP request processing)

that seems unrelated to this issue and more a kind if help/support request, there are better channels for that kind of requests: stackoverflow, slack, discourse, ... Github use to be more "developer focus"

/remove kind-bug
/kind support

**Comment by aojea** [comment]
thanks for updating the issue, but this was already answered here 

https://github.com/kubernetes/kubernetes/issues/93393#issuecomment-663397487

since we didn't have any answer in more than 10 days I'll close it
/close
