### ISSUE TITLE
Inline patch kustomization does not work

### ISSUE THREAD

**Issue by rokej** [kubernetes/kubernetes#93391]
**What happened**:

Using `k8s.io/cli-runtime/pkg/kustomize` to build with kustomization.yaml that contains inline patch (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md) fails with `SliceFromPatches: evalsymlink failure` error.

Here is my simple test code. In the first block, I use the  `k8s.io/cli-runtime/pkg/kustomize` module and it fails. The second block does kustomize build in command line and it works fine.

```
package main

import (
	"bytes"
	"fmt"
	"log"
	"os/exec"

	"k8s.io/cli-runtime/pkg/kustomize"
	"sigs.k8s.io/kustomize/pkg/fs"
)

func main() {

	kustomizeDir := "/tmp/test"

	fSys := fs.MakeRealFS()

	var out bytes.Buffer

	err := kustomize.RunKustomizeBuild(&out, fSys, kustomizeDir)

	if err != nil {
		fmt.Println("Failed, error: ", err.Error())
	}

	fmt.Println("----------------------OUTPUT1--------------------------")
	fmt.Println(out.String())
	fmt.Println("----------------------OUTPUT1--------------------------")

	cmd := exec.Command("kustomize", "build", kustomizeDir)
	var out2 bytes.Buffer
	cmd.Stdout = &out2
	err = cmd.Run()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("----------------------OUTPUT2--------------------------")
	fmt.Println(out2.String())
	fmt.Println("----------------------OUTPUT2--------------------------")

}
```

Here is my go.mod.

```
go 1.14

require (
	k8s.io/cli-runtime v0.18.6
	sigs.k8s.io/kustomize v2.0.3+incompatible
)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
looks like you've already opened the issue here: https://github.com/kubernetes/cli-runtime/issues/15

/close
