### ISSUE TITLE
The build failed for some tests while running make test fo GO version go1.15beta1

### ISSUE THREAD

**Issue by coolshilpi6** [kubernetes/kubernetes#93407]
Test Failures are
```
FAIL    k8s.io/kubernetes/pkg/kubelet [build failed]
FAIL    k8s.io/kubernetes/pkg/kubelet/container [build failed]
FAIL    k8s.io/kubernetes/pkg/kubelet/network/dns [build failed]
FAIL    k8s.io/kubernetes/pkg/scheduler [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/drain [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/gce [build failed]
FAIL
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.300+ff33efc164e78d-dirty", GitCommit:"ff33efc164e78d12c2a250f901b6ec725184fd06", GitTreeState:"dirty", BuildDate:"2020-07-22T10:11:16Z", GoVersion:"go1.15beta1", Compiler:"gc", Platform:"linux/ppc64le"}
- Cloud provider or hardware configuration:
linux/ppc64le
- OS (e.g: `cat /etc/os-release`):
```NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
```
**Full logs of make file**
[make.log](https://github.com/kubernetes/kubernetes/files/4970250/make.log)

**Full Logs of make test**
[make_test.log](https://github.com/kubernetes/kubernetes/files/4970245/make_test.log)

Golang Location: https://dl.google.com/go/go1.15beta1.linux-ppc64le.tar.gz

**Comment by liggitt** [comment]
Thanks for the report. go1.15 is not yet supported. https://github.com/kubernetes/kubernetes/pull/93264 is the PR working on introducing that version

**Comment by liggitt** [comment]
/assign

fix in https://github.com/kubernetes/kubernetes/pull/93425

**Comment by mkumatag** [comment]
> Thanks for the report. go1.15 is not yet supported. #93264 is the PR working on introducing that version

Thanks @liggitt for the quick fix. We just run the builds and test with latest golang version on the ppc64le platform just to ensure we don't hit any golang issues with the platform :)
