### ISSUE TITLE
default PriorityClass by namespace 

### ISSUE THREAD

**Issue by breizh5729** [kubernetes/kubernetes#93416]
**What would you like to be added**:

currently we can create a priorityclass with globalvalue: true for the whole cluster, but an evolution would be interesting to have the possibility of also splitting by namespace.

**Why is this needed**:
actually i can't impose a quotas or limit on my dev team and  i would like to ensure all component in my namespaces system run with a specific priorityclass without modify them.

**Comment by liggitt** [comment]
an admission webhook could be used to set a per-namespace priorityClassName rather than a cluster-wide one

**Comment by breizh5729** [comment]
do you have a example more precise for a namespace  ?

**Comment by breizh5729** [comment]
@liggitt do you have a example more precise for a namespace ?

**Comment by liggitt** [comment]
not sure what you're asking for ... [admission webhooks can intercept and modify pods as they are created](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/). One could be written to set priorityClassName based on the namespace of the incoming pod, rather than a cluster-wide default.

**Comment by breizh5729** [comment]
@liggitt liggitt 
this is exactly what i need but i dont quite understand how to do it, do you have a simple example for that

**Comment by liggitt** [comment]
you could look at the code used to test admission webhooks for an example of writing a webhook that modifies pods as they are created:

https://github.com/kubernetes/kubernetes/blob/2a3a36842f8ab91a3658da38a237225e8988f0df/test/images/agnhost/webhook/main.go#L211-L238

https://github.com/kubernetes/kubernetes/blob/2a3a36842f8ab91a3658da38a237225e8988f0df/test/images/agnhost/webhook/main.go#L91-L161

https://github.com/kubernetes/kubernetes/blob/2a3a36842f8ab91a3658da38a237225e8988f0df/test/images/agnhost/webhook/pods.go#L82-L90

https://github.com/kubernetes/kubernetes/blob/2a3a36842f8ab91a3658da38a237225e8988f0df/test/images/agnhost/webhook/pods.go#L118-L141

@jpbetz, is there an issue tracking factoring out a skeleton admission webhook plugin?

**Comment by jpbetz** [comment]
> @jpbetz, is there an issue tracking factoring out a skeleton admission webhook plugin example?

I don't think we had one. I've created https://github.com/kubernetes/kubernetes/issues/93756 and assigned it to myself.

**Comment by breizh5729** [comment]
thank @jpbetz @liggitt 
I will wait your example for that

**Comment by jpbetz** [comment]
> I will wait your example for that

Just to set expectations, I don't know exactly when I'll be able to start on this. It will be at least a week or two until I start.
