### ISSUE TITLE
Node: Add field to describe most recent request Serving CSR

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/kubernetes#93428]
**What would you like to be added**:

I would like a field that the kubelet can set on it's own node object that indicates the last-requested serving CSR it created.  Since the kubelet creates the CSR object, it already has knowledge of which one it needs approved for continued functionality.  

**Why is this needed**:
Recording this detail on the node object would allow trivial approval of serving CSRs without requiring any knowledge of the content of the CSR itself.

This field would only need to be updated when a kubelet requests a new serving CSR, so there will be minimal impact to API utilization.

Existing KEP for reference of current implementation: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md

**Comment by michaelgugino** [comment]
cc @smarterclayton @liggitt WDYT?  Seems like this is a no-brainer to me.  This would make implementing an approver trivial either in or out of k8s proper.

**Comment by liggitt** [comment]
> Recording this detail on the node object would allow trivial approval of serving CSRs without requiring any knowledge of the content of the CSR itself.

If you trust the kubelet completely, you can already approve all CSRs with `spec.signerName=kubernetes.io/kubelet-serving` and `spec.username=system:node:$name`

I don't really understand what the additional field on the Node API objects gets you.

**Comment by michaelgugino** [comment]
> > Recording this detail on the node object would allow trivial approval of serving CSRs without requiring any knowledge of the content of the CSR itself.
> 
> If you trust the kubelet completely, you can already approve all CSRs with `spec.signerName=kubernetes.io/kubelet-serving` and `spec.username=system:node:$name`
> 
> I don't really understand what the additional field on the Node API object gets you.

Is there an admission controller or other mechanism that enforces the request was indeed made by the kubelet?  If there is, it's not documented.

Is there a mode of operation that allows for a trusted kubelet to not have a trusted serving cert?  In what scenario would that ever be the case?  Having a client certificate grants far more access than the serving cert.

Having the CSR name on the node object attests that the CSR's origin is the kubelet in question.

**Comment by liggitt** [comment]
> Is there an admission controller or other mechanism that enforces the request was indeed made by the kubelet?

The username/groups/extra fields in the spec are populated by the API server based on the authenticated requester and are immutable

See https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/certificates/v1/types.go#L104-L107

> Is there a mode of operation that allows for a trusted kubelet to not have a trusted serving cert? In what scenario would that ever be the case?

A kubelet could request a serving certificate for google.com, but it should probably not be issued. The difficult part of approving kubelet serving certificates is verifying which hostnames/IP addresses the corresponding node should have control over.

> Having the CSR name on the node object attests that the CSR's origin is the kubelet in question.

The spec.username field can be used for that.

**Comment by michaelgugino** [comment]
> The difficult part of approving kubelet serving certificates is verifying which hostnames/IP addresses the corresponding node should have control over.

It seems to me we could optionally approve these CSRs automatically the same way we do with client certs then.  This would be less risky than automatically approving the client certs.  This functionality used to exist in 1.10, but it was based on some IP information on the node object (or something like that) and was removed.  If this was to be opt-in, I don't see a compelling reason to not do it.

In any case, if the spec.username is guaranteed to be set by the API, then I agree the field on the node is redundant.
