### ISSUE TITLE
kubernetes doesnt support ":" colon field in volume mount paths

### ISSUE THREAD

**Issue by pswalia06** [kubernetes/kubernetes#93479]
**What happened**:
I am trying to create a directory which has colon in the path and kubernetes doesn't support that.
/etc/docker/certs.d/reg.example.com:5000

**What you expected to happen**:
Its should create directory "/etc/docker/certs.d/reg.example.com:5000" and put the cert file in it

**How to reproduce it (as minimally and precisely as possible)**:

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-ca
  namespace: kube-system
  labels:
    k8s-app: registry-ca
spec:
  template:
    metadata:
      labels:
        name: registry-ca
    spec:
      containers:
      - name: registry-ca
        image: busybox
        command: [ 'sh' ]
        args: [ '-c', 'cp /home/core/registry-ca /etc/docker/certs.d/reg.example.com:5000/ca.crt && exec tail -f /dev/null' ]
        volumeMounts:
        - name: etc-docker
          mountPath: /etc/docker/certs.d/reg.example.com:5000
        - name: ca-cert
          mountPath: /home/core
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etc-docker
        hostPath:
          path: /etc/docker/certs.d/reg.example.com:5000
      - name: ca-cert
        secret:
          secretName: registry-ca

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pswalia06** [comment]
cncf-cla: yes kind/failing-test priority/important-longterm release-note-none sig/node size/XS

**Comment by liggitt** [comment]
This is likely due to special treatment of colons in filepaths (disallowed in windows paths, treated as a path separator in linux paths). It is unlikely that this validation will be relaxed.

/remove-kind bug
/kind feature
/sig storage

**Comment by Parwinderjit16061986** [comment]
How can I escape those colon ? How can I use the escape characters in kubernetes ?
error: error parsing test2.yaml: error converting YAML to JSON: yaml: line 23: found unknown escape character

**Comment by michmike** [comment]
@ddebroy or @jingxu97, can you PTAL?

**Comment by artificial-aidan** [comment]
For anyone who runs into this issue. Here is the workaround I found.

```
    volumes:
    - name: certs
      secret:
        items:
        - key: ca.crt
          path: my-registry:443/ca.crt
        secretName: registry-ca
    volumeMounts:
    - mountPath: /etc/docker/certs.d
      name: certs
      readOnly: true
```
