### ISSUE TITLE
go1.15.0 / k8s 1.19 tracker

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93484]
Tracking issue to complete go 1.15.0 bump for 1.19

/milestone v1.19

~~Blocking issues for go 1.15.0:
https://github.com/golang/go/issues?q=is%3Aopen+is%3Aissue+milestone%3AGo1.15+label%3Arelease-blocker~~

~~Changes to go 1.15 since go1.15rc2: https://github.com/golang/go/compare/go1.15rc2...release-branch.go1.15~~

Post-release issues found and being considered for go1.15.1: https://github.com/golang/go/issues?q=+milestone%3AGo1.15.1

Remaining Kubernetes tasks: https://github.com/kubernetes/release/issues/1421 tasks

**Comment by liggitt** [comment]
cc @justaugustus

**Comment by justaugustus** [comment]
FYI @kubernetes/sig-release

**Comment by BenTheElder** [comment]
1.15rc2 is out. we're using it in kind and kubetest2

**Comment by liggitt** [comment]
go1.15.0 is tagged - https://github.com/golang/go/releases/tag/go1.15

**Comment by liggitt** [comment]
go1.15.0 is merged in https://github.com/kubernetes/kubernetes/pull/93939
