### ISSUE TITLE
ElasticSearch e2e periodic tests are failing due to missing elasticsearch service.

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#93480]
Looks like this test is never able to succeed because `elasticsearch-logging` service does not exist:
```
I0727 06:43:51.448] Jul 27 06:43:51.447: INFO: Checking the Elasticsearch service exists.
I0727 06:43:51.488] Jul 27 06:43:51.488: INFO: Attempt to check for the existence of the Elasticsearch service failed after 40.466233ms
I0727 06:43:56.530] Jul 27 06:43:56.529: INFO: Attempt to check for the existence of the Elasticsearch service failed after 5.081735546s
I0727 06:44:01.571] Jul 27 06:44:01.570: INFO: Attempt to check for the existence of the Elasticsearch service failed after 10.12297825s
I0727 06:44:06.613] Jul 27 06:44:06.613: INFO: Attempt to check for the existence of the Elasticsearch service failed after 15.165578658s
I0727 06:44:11.656] Jul 27 06:44:11.656: INFO: Attempt to check for the existence of the Elasticsearch service failed after 20.208387047s
I0727 06:44:16.699] Jul 27 06:44:16.699: INFO: Attempt to check for the existence of the Elasticsearch service failed after 25.25152153s
I0727 06:44:21.743] Jul 27 06:44:21.743: INFO: Attempt to check for the existence of the Elasticsearch service failed after 30.295162229s
...
I0727 06:48:28.840] Jul 27 06:48:28.840: INFO: Attempt to check for the existence of the Elasticsearch service failed after 4m37.392168972s
I0727 06:48:33.882] Jul 27 06:48:33.882: INFO: Attempt to check for the existence of the Elasticsearch service failed after 4m42.434454075s
I0727 06:48:38.924] Jul 27 06:48:38.924: INFO: Attempt to check for the existence of the Elasticsearch service failed after 4m47.476311047s
I0727 06:48:43.966] Jul 27 06:48:43.966: INFO: Attempt to check for the existence of the Elasticsearch service failed after 4m52.518390007s
I0727 06:48:49.011] Jul 27 06:48:49.011: INFO: Attempt to check for the existence of the Elasticsearch service failed after 4m57.563234351s
I0727 06:48:54.012] Jul 27 06:48:54.012: FAIL: Failed to init Elasticsearch logs provider
```

##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/elasticsearch/kibana.go:45
Jul 13 02:23:33.912: Unexpected error:
    <*errors.errorString | 0xc0001fa200>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/elasticsearch/kibana.go:72
```
#### Recent failures:
[7/27/2020, 2:35:56 AM ci-cri-containerd-e2e-gci-gce-es-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-es-logging/1287637754586337285)
[7/27/2020, 2:28:57 AM ci-kubernetes-e2e-gci-gce-es-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-es-logging/1287635992882188288)
[7/27/2020, 1:47:51 AM ci-kubernetes-e2e-gci-gce-es-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-es-logging/1287625675137617922)
[7/27/2020, 12:56:18 AM ci-kubernetes-e2e-gci-gce-es-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-es-logging/1287612589823496193)
[7/27/2020, 12:35:02 AM ci-cri-containerd-e2e-gci-gce-es-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce-es-logging/1287607304794935303)

/kind failing-test
/sig instrumentation

**Comment by brianpursley** [comment]
possibly related to https://github.com/kubernetes/kubernetes/issues/92731

**Comment by ehashman** [comment]
@brancz @erain where did we get with this?

**Comment by erain** [comment]
Looks like those tests didn't work for at least half a year and nobody cared... 

Should we delete this e2e test as well? If so I can help with that.

**Comment by ehashman** [comment]
Yes, let's remove them. Would appreciate the help!

/remove-lifecycle rotten

**Comment by ehashman** [comment]
Still failing: https://testgrid.k8s.io/sig-instrumentation-tests#gci-gce-es-logging

/remove-lifecycle stale
