### ISSUE TITLE
[Flaky Test] integration-master scheduler tests (ci-kubernetes-integration-master)

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93485]
**Which jobs are flaking**:

* ci-kubernetes-integration-master
* pull-kubernetes-integration

**Which test(s) are flaking**:

Flaking in pre and post-submit:
* TestPostFilterPlugin
* TestReservePluginUnreserve
* TestFilterPlugin
* TestScorePlugin
* TestNodeAffinity

**Testgrid link**:

* https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5&include-filter-by-regex=test%2Fintegration%2Fscheduler
* https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&width=5&include-filter-by-regex=test%2Fintegration%2Fscheduler

**Reason for failure**:

```
    framework_test.go:671: Expected the filter plugin to be called 2 times, but got 4.
    framework_test.go:674: Expected the postfilter plugin to be called 1 times, but got 2.
```

Triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestPostFilterPlugin%7CTestReservePluginUnreserve%7CTestFilterPlugin%7CTestScorePlugin%7CTestNodeAffinity

/sig scheduling
@kubernetes/sig-scheduling-test-failures

**Comment by liggitt** [comment]
/milestone v1.19

since these are flaking in a post-submit release-blocking job

**Comment by liggitt** [comment]
@kubernetes/ci-signal

**Comment by Huang-Wei** [comment]
I will take a look.

/assign

**Comment by Huang-Wei** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5&include-filter-by-regex=test%2Fintegration%2Fscheduler is all green since the last PR (#93550) gets merged around 4:30 AM PST Jul 30.

I will keep an eye on it for the next couple of days.

**Comment by liggitt** [comment]
Solid green since that merged, thanks
