### ISSUE TITLE
Accessing Dashboard Remotely: ERROR forbidden: User \"system:anonymous\

### ISSUE THREAD

**Issue by EdgeXS** [kubernetes/kubernetes#93494]
I'm fairly new to kubernetes.  Using references to install and get everything up and running. Came across Kubernetes Dashboard to manage the cluster.

Steps to reproduce

1.  i deployed the dashboard following the below link
    https://github.com/kubernetes/dashboard

2. installed dashboard https://github.com/kubernetes/dashboard
ran kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.3/aio/deploy/recommended.yaml

3.  then i tried to access it from another machine using the url
https://<server-IP>:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

but get this error:
https://<server-iP>:6443/ui

**ERROR**

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/ui\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

**Comment by liggitt** [comment]
You can find instructions for accessing the dashboard at https://github.com/kubernetes/dashboard#access

**Comment by EdgeXS** [comment]
Actually I've seen that reference but that doesn't work for remote server.  Since the kubectl is a local proxy.  While i'm trying to access the dashboard remotely.

**Comment by EdgeXS** [comment]
This did not resolve the issue could this thread be reopened.

**Comment by liggitt** [comment]
> Actually I've seen that reference but that doesn't work for remote server. Since the kubectl is a local proxy. While i'm trying to access the dashboard remotely.

The dashboard can be exposed using an ingress like any other web-serving pod (see https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/README.md#ingress), though special care needs to be taken to ensure access is not granted to an unsecured dashboard (see https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md).

If you have further questions, I'd recommend opening an issue in https://github.com/kubernetes/dashboard/issues

**Comment by EdgeXS** [comment]
Thanks for the response.  So from everyone that has responded they have stated opening a node port in production environment is not recommended.

So are you stating that you will have to open up a node port to achieve the remote access is the recommended approach?  I just don't want to open a security can of worms and deploy it by recommended approach. I'm just not getting that official document stating that.

Is there away to reopen this ticket so essentially it's not a duplicate request if not I can resubmit it with the summarized statement as well.

**Comment by liggitt** [comment]
> So are you stating that you will have to open up a node port to achieve the remote access is the recommended approach? I just don't want to open a security can of worms and deploy it by recommended approach. I'm just not getting that official document stating that.

Not a node port, a service+ingress.

> Is there away to reopen this ticket so essentially it's not a duplicate request if not I can resubmit it with the summarized statement as well.

This repo is not the best place for dashboard questions/issues, shifting to the dashboard repo will be more likely to get info from the dashboard maintainers.

**Comment by EdgeXS** [comment]
Must have gotten my postings messed up.  Didn't realize this was the kubernetes / kubernetes repo and not the kubernetes / dashboard repo.

**Comment by EdgeXS** [comment]
Just to conclude this,

By doing the following you are just creating an ingress that needs to be done to achieve access to the dashboard there is no actual other way.  Just assure that it is secured with the token
https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/README.md#nodeport
