### ISSUE TITLE
Move AssumePod Op to ReservePlugins as defaultReserve

### ISSUE THREAD

**Issue by denkensk** [kubernetes/kubernetes#93500]
**What would you like to be added**:
Move AssumePod Op to ReservePlugins as defaultReserve
Move ForgetPod Op to UnReservePlugins as defaultUnreserve

**Why is this needed**:
make all phases of scheduling can be implemented by plugins in Framework

/assign

**Comment by alculquicondor** [comment]
I thought about this before, but since this is tightly associated to the scheduler cache, I'm not sure if it's a good idea.

If you disable the plugin, everything will stop working correctly. That is not the same for other plugins being disabled, such as preemption.

Still, I'm open to discussion.

**Comment by Huang-Wei** [comment]
I'm +1 to see this happen, but Aldo's concern is also legit. @ahg-g would you want to put it into 1.20 items discussion?

**Comment by ahg-g** [comment]
will do, though not sure when 1.20 will start...

**Comment by denkensk** [comment]
> I thought about this before, but since this is tightly associated to the scheduler cache, I'm not sure if it's a good idea.
---
I simulated it. Maybe we can just expose the function of `assumePod` and `forgetPod` in frameworkHandle other than cache itself. In this way, the cache is not seriously affected.

> If you disable the plugin, everything will stop working correctly. That is not the same for other plugins being disabled, such as preemption.
---
This plugin needs to be manually disabled by the user. It is enabled by default.  I feel that this scene may be similar to `defaultBind`. 

@alculquicondor

**Comment by alculquicondor** [comment]
then this plugin will have a single line of code (calling assumePod).

You are right in that this is similar to defaultBind. The advantage there was that there are no internal dependencies. Just API calls.

**Comment by denkensk** [comment]
> then this plugin will have a single line of code (calling assumePod).
----
yes, you are right. In the end, it might be just single line of code in `defaultReserve`(calling assumePod) and `defaultUnReserve`(calling forgetPod). But it makes all phases of scheduling can be implemented by plugins in Framework.
This increases the flexibility of our framework. Meanwhile，it also protects the cache of scheduling. 
@alculquicondor

**Comment by alculquicondor** [comment]
> Why is this needed:
> make all phases of scheduling can be implemented by plugins in Framework

That's not a "why" :)

Could you clarify what is the underlying need? I don't think there is enough justification for a "cleanup".

**Comment by denkensk** [comment]
I am trying to implement `GPU Topology Scheduling For Distribute Training of PodGroup` base on framework.  We need to choose the best topology at once for podGroup and use pod group as a unit to reserve resources at `Reserve`. So I want to implement my own `assumePod` in `Reserve` other than use the `defaultReserve`. @alculquicondor

**Comment by alculquicondor** [comment]
Can't you do that in Reserve plugins? That's what we do for volumes.

**Comment by alculquicondor** [comment]
Is that different from the co-scheduling plugin? Since the scheduler can only schedule one pod at a time in its current architecture, I don't see how you would achieve scheduling multiple pods at the same time without significantly changing the scheduler.

**Comment by denkensk** [comment]
> Since the scheduler can only schedule one pod at a time in its current architecture
---
Yes, This is the biggest problem in the framework scheduling workload of AI/ML. 

> I don't see how you would achieve scheduling multiple pods at the same time without significantly changing the scheduler.
---
Simply, it is to find other pods belonging to the same pod group through one pod. Then scheduling multiple pods as the same time. This may look like Co-scheduling.

**Comment by alculquicondor** [comment]
Wasn't that the intention of the Permit extension point?

Maybe you could update the doc for co-scheduling plugin to present the bigger picture.

**Comment by ahg-g** [comment]
My general preference is to try and completely remove generic_scheduler.go: have most of the logic moved to run as plugins where applicable and the logic outside just executes the extension points of the framework. 

Moving assume/forget to run as plugins I think fits the framework's reserve/unreserve extension points well, not sure we need stronger motivation to actually do that.

**Comment by Huang-Wei** [comment]
@denkensk Probably we can get it completed in 1.22.

**Comment by denkensk** [comment]
@Huang-Wei  Sure I will finish it in 1.22

**Comment by alculquicondor** [comment]
@denkensk do you still need this?

**Comment by denkensk** [comment]
Actually, I have Implemented this in our internal version last year to support our needs. I can list the details first. I hope you can give me some feedback. @Huang-Wei @alculquicondor  If we can reach an agreement, I can submit the pr to upstream.

1.  Add field `schedulerCache` in `framework`
2. Add functions in `FrameworkHandle` to operate the `SchedulerCache` like `AssumePod`,`FinishBinding` and `ForgetPod`
3. Add new plugin called `defaultReserve` to encapsulate the implementation of the original logic  in `scheduleOne`
4. Modify the logic of `RunReservePlugins` like `RunBindPlugins`, it will run the set of configured reserve plugins until one returns a non `Skip` status.

**Comment by alculquicondor** [comment]
My main worry is step 2. That plugin might misuse those functions in inappropriate extension points. For that, I would like to understand why you can't achieve what you want within the existing framework. Can you provide a summary of that here?

**Comment by Huang-Wei** [comment]
I'm also concerned with making the entire `SchedulerCache` manipulatable. This'd over-expose the scheduler internals  IMO.

I'd prefer to build a lightweight "contract" between schedulerCache and plugins. For instance, we can follow #103383 to setup a reserved StateKey to store pods that need to be assumed/forgot. In this way, both in-tree and out-of-tree plugins follow the same pattern: if you want to communicate with internal cache on assume/forget Pods, in the RunReservePluginsReserve()/RunReservePluginsUnreserve(), inject the pod to the state. And the scheduler framework knows how to deal with the state properly.

**Comment by denkensk** [comment]
> why you can't achieve what you want within the existing framework.
1. This can be special. Considering the topology information like gpu topology, We will select a suitable set of resources for a set of pods(like batch jobs). So it's needed to reserve resources for pod in advance. 
2. Another reason is that It's better to completely move the logic of generic_scheduler.go to run as plugins. Moving assume/forget to run as plugins fits the framework's reserve/unreserve extension points.

**Comment by denkensk** [comment]
> I'd prefer to build a lightweight "contract" between schedulerCache and plugins.
I think it's a good idea. This can not only ensure the security of cache, but also provide the way for the plugins to operate internal cache on assume/forget Pods. I can do some research to test this.

**Comment by alculquicondor** [comment]
> So it's needed to reserve resources for pod in advance

So you want to reserve specific GPUs (or GPU cores) within a Node for a Pod? I think the general problem with this is that the scheduler might take a different decision than the node (not sure if kubelet or the device plugin). That is the same problem that this proposal faces https://github.com/kubernetes/enhancements/pull/2787 which I think you are aware of. It would be nice if you can collaborate with @swatisehgal 

Still, why can't you use the `Reserve` extension point that run after assume? That happens within the scheduling cycle (before we start the binding routine). That means that there are no other competing scheduling cycles at that point.

**Comment by kerthcet** [comment]
/remove-lifecycle stale

No progress till today, let me take a research.
/assign

**Comment by kerthcet** [comment]
/remove-lifecycle stale

I hope I have time to implement this, but now, I'm out of bandwidth.
