### ISSUE TITLE
minikube addon kubevirt fails to deploy 

### ISSUE THREAD

**Issue by mazzystr** [kubernetes/kubernetes#93513]
**What happened**:
* Deploy minikube
` minikube start --driver=podman --container-runtime=cri-o`
* Deploy kubevirt addon
`minikube addons enable kubevirt`
* kubevirt addon fails to deploy

**What you expected to happen**:
I expect kubevirt addon to deploy correctly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
$ kubectl exec pod/kubevirt-install-manager -n kube-system -- cat /etc/resolv.conf
search kube-system.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:5
```

It appears `-n kube-system pod/kubevirt-install-manager` uses image docker.io/bitnami/kubectl@sha256:3c19642430bfd6b5f131a4af87bb8669aa595d486b2408b68dbfb19f1b88e6e9 and it has incorrect nameserver hard coded into /etc/resolv.conf.  This causes hostname resolution to fail.  That causes all the curls in /kubevirt-scripts/install.sh to fail and thus kubevirt deployment fails.

I would expect /etc/resolv.conf to be inherited from the host, cni or the network dhcp server itself.

Incidentally `--driver=kvm2` works albeit the same ip is set in /etc/resolv.conf
**Environment**:
```
$ minikube version
minikube version: v1.12.1
commit: 5664228288552de9f3a446ea4f51c6f29bbdd0e0-dirty
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
HP EliteDesk G2 mini (Intel Core i5 / 16 gig memory)
- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/redhat-release
Fedora release 32 (Thirty Two)
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux cube0 5.7.10-201.fc32.x86_64 #1 SMP Thu Jul 23 00:58:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
```
$ rpm -qa | grep container
containers-common-1.1.0-1.fc32.x86_64
systemd-container-245.6-2.fc32.x86_64
containernetworking-plugins-0.8.6-1.fc32.x86_64
container-selinux-2.132.0-1.fc32.noarch
```
- Others:
```
$ podman version
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.14
OS/Arch:            linux/amd64
```

**Comment by liggitt** [comment]
If this is an image with the kubevirt image, should this be opened against https://github.com/kubevirt/kubevirt instead?

**Comment by mazzystr** [comment]
@liggitt I'm happy to create an issue against that repo

**Comment by mazzystr** [comment]
@liggitt  @neolit123 It looks like this isn't an issue with the kubevirt image after all...

`configmap/coredns` ships with a config `forward . /etc/resolv.conf`.  Image k8s.gcr.io/coredns:1.6.7 isn't properly populating it's `/etc/resolv.conf` correctly.  As soon as I set `forward . 192.168.0.1` and rollout restart the correct settings are applied.  dns within the cluster works correctly.  The minikube kubevirt addon deploys correctly.

Perhaps we should reopen this issue?

**Comment by neolit123** [comment]
then should we consider this a coredns issue?
cc @chrisohaver @rajansandeep

**Comment by chrisohaver** [comment]
CoreDNS doesn't populate its `/etc/resolv.conf`,  kubelet does that.

However, if `/etc/resolv.conf` has two or more name servers in it, [this bug](https://github.com/coredns/coredns/issues/3900) affecting 1.6.7 causes only the first server to be used.  It's fixed in 1.7.0.

**Comment by mazzystr** [comment]
dnsmasq on my network does provide two nameservers.... 192.168.0.1 and 1.1.1.1.  I have no idea what lands into coredns /etc/resolv.conf.  user tools like `ls` and `dig` aren't available in the image.

**Comment by chrisohaver** [comment]
CoreDNS uses dns policy "default", so kubelet gives it the `/etc/resolv.conf` of the host node (by default, but kubelet can be configured use a different resolv.conf).

**Comment by cheese** [comment]
I am new to Kubernetes and met the same issue with latest minikube.

```
$ minikube version
minikube version: v1.25.1
commit: 3e64b11ed75e56e4898ea85f96b2e4af0301f43d
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl exec pod/kubevirt-install-manager -n kube-system -- cat /etc/resolv.conf                                
nameserver 10.96.0.10
search kube-system.svc.cluster.local svc.cluster.local cluster.local                                                                
options ndots:5
```
