### ISSUE TITLE
Trace library seem to incorrect print start_time

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#93531]
While debugging scalability tests, I discovered that there seem to be some problem with tracing library.

Taking this as an example run:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1287819459200815104

and grepping for all Trace entires, all seem to have start_time where seconds are always set to 0.
i.e. the start time is always"

`27-Jul-2020 XX:XX:00.XXX`

That makes debugging harder

/kind bug

@jpbetz @dims @liggitt

**Comment by wojtek-t** [comment]
This is the relevant code:
https://github.com/kubernetes/utils/blob/master/trace/trace.go#L200

I don't know what is wrong with it...

**Comment by wojtek-t** [comment]
Woow - I played with it and it seems that you can't set seconds to "00"

https://play.golang.org/p/lvytu4tYb_7

This is so freaking unexpected (given that 000 as milliseconds works fine).

**Comment by dims** [comment]
Crazy!

**Comment by wojtek-t** [comment]
I opened https://github.com/kubernetes/utils/pull/182 in utils repo.

**Comment by liggitt** [comment]
thanks, do you plan to update k8s.io/utils here?

**Comment by wojtek-t** [comment]
Didn't get to it - if someone could pick it up, it would be great.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/93602
