### ISSUE TITLE
CoreDNS does not tolerate node.cloudprovider.kubernetes.io/uninitialized

### ISSUE THREAD

**Issue by nickperry** [kubernetes/kubernetes#93533]
**What happened**:

Clusters built with an external cloud-provider which needs to resolve DNS before it can remove the node.cloudprovider.kubernetes.io/uninitialized taints from nodes, get stuck in a catch-22 state.

CoreDNS cannot start because it does not tolerate node.cloudprovider.kubernetes.io/uninitialized: true...

```
kubectl --kubeconfig /etc/kubernetes/admin.conf describe  pods -n kube-system coredns-84b6ddc6c6-6vlrz|grep FailedScheduling
  Warning  FailedScheduling  <unknown>  default-scheduler  0/10 nodes are available: 2 node(s) had taint {node-role.kubernetes.io/gateway: true}, that the pod didn't tolerate, 8 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.
```

I am using https://github.com/kubernetes/cloud-provider-vsphere as my cloud-provider. This needs to be able to reach a vcenter server before it can remove the node.cloudprovider.kubernetes.io/uninitialized taint from nodes. However it cannot resolve the vcenter DNS entry because CoreDNS cannot start.

```
kubectl --kubeconfig /etc/kubernetes/admin.conf -n kube-system logs -f vsphere-cpi-5kvzj
E0729 13:32:30.313559       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post https://vcenter.local:443/sdk: dial tcp: i/o timeout

[ root@debug-container:/ ]$ nslookup vcenter.local
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'vcenter.local'
```

**What you expected to happen**: I expected to be able to bootstrap a cluster including control plane kubelets using --cloud-provider=external.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster using kubeadm with cloud-provider=external.
Note that coredns cannot get scheduled.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.18.6
- Cloud provider or hardware configuration: https://github.com/kubernetes/cloud-provider-vsphere
- OS (e.g: `cat /etc/os-release`): RHEL7
- Kernel (e.g. `uname -a`): 3.10.0-1062.9.1.el7.x86_6
- Install tools: Kubeadm
- Network plugin and version (if this is a network-related bug): Calico 3.14
- Others:

**Comment by thebsdbox** [comment]
I think @frapposelli may be able to hopefully point you in the right direction around the cloud-provider, if not I'd try asking in `provider-vsphere` on the Kubernetes slack?

**Comment by nickperry** [comment]
The vSphere CPI chart says "FQDN or IP" for the vcenter host, but, tellingly, https://cloud-provider-vsphere.sigs.k8s.io/cloud_config.html only refers to IPs, not FQDNs for addressing vcenter.

**Comment by neolit123** [comment]
the kubeadm coredns deployment tollerations are defined here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L238-L242

@nickperry did you confirm that if you patch the coredns deployment (via kubectl edit / patch) to tollerate `node.cloudprovider.kubernetes.io/uninitialized` the problem is solved?
@rajansandeep @andrewsykim do you think we should be adding this tolleration by default in the kubeadm managed manifest for kubeadm?

**Comment by chrisohaver** [comment]
Will the k8s API be available from a node with the `node.cloudprovider.kubernetes.io/uninitialized` taint.  If not, then even if the CoreDNS deployment tolerates the taint, the pods would remain unready.

**Comment by andrewsykim** [comment]
The cloud provider should be configured to use host network and use the default host resolver for finding vCenter. This is what is recommended in the manifests as well:  https://github.com/kubernetes/cloud-provider-vsphere/blob/master/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml#L58

How is the DNS `vcenter.local` configured in this case?

**Comment by nickperry** [comment]
> @nickperry did you confirm that if you patch the coredns deployment (via kubectl edit / patch) to tollerate `node.cloudprovider.kubernetes.io/uninitialized` the problem is solved?

@neolit123 yes - confirmed by adding the toleration via kubectl edit.

**Comment by nickperry** [comment]
@andrewsykim I've just double checked and my CPI daemonset spec from the official helm chart (chart version 0.1.3) does not have hostNetwork: true in its spec.

**Comment by nickperry** [comment]
I have been told, although I couldn't find it myself, that the Tanzu TGK docs say specify the Vcenter by IP address, which I presume is because of this same issue?

**Comment by nickperry** [comment]
> Will the k8s API be available from a node with the `node.cloudprovider.kubernetes.io/uninitialized` taint? If not, then even if the CoreDNS deployment tolerates the taint, the pods would remain unready.

Yes.

kube-apiserver has
`  tolerations:
  - effect: NoExecute
    operator: Exists
`

Additionally my Calico CNI has also been configured to tolerate node.cloudprovider.kubernetes.io/uninitialized.

**Comment by andrewsykim** [comment]
@nickperry can you try setting `hostNetwork: true` and see if that resolves your issue?

**Comment by andrewsykim** [comment]
> I have been told, although I couldn't find it myself, that the Tanzu TGK docs instruct the user to specify the Vcenter by IP address, which I presume is because of this same issue?

Shouldn't matter IIRC as long as the DNS is resolvable from the host configured resolver.

**Comment by chrisohaver** [comment]
According to the [yaml](https://github.com/kubernetes/cloud-provider-vsphere/raw/master/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml) in the docs, it should be running on hostNetwork ... and, it doesn't specify `ClusterFirstWithHostNet` for dnsPolicy, so it should be going to the host's resolver, not the cluster DNS.

**Comment by andrewsykim** [comment]
@chrisohaver yup -- the issue I think is that the helm charts use different yaml than the one recommending in the cloud-provider-vsphere repo -- we should update the helm charts to set hostNetwork: true as well.

**Comment by neolit123** [comment]
@nickperry any updates? can this ticket be closed?

/remove-kind bug
/triage support

**Comment by dvonthenen** [comment]
/assign

Will take a look at updating the chart

**Comment by nickperry** [comment]
> @nickperry any updates? can this ticket be closed?
> 
> /remove-kind bug
> /triage support

It sounds like the VMware people are happy with hostNetwork: true and it's just an issue at this present time with a discrepancy in their helm chart installation.

So if there's no more general support (i.e. beyond the VMware case) for the principle of having CoreDNS available prior to node.cloudprovider.kubernetes.io/uninitialized taint being removed, sure, go ahead and close. I have workaround for now and look forward to seeing the fix in the CPI chart.

**Comment by neolit123** [comment]
thanks,
i will be watching if we see similar requests from users and reconsider adding the taint.

/close
