### ISSUE TITLE
typecheck uses exorbitant amounts of memory

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93532]
**Background**:

We recently introduced Guaranteed Pod QOS on jobs running in `k8s-infra-prow-build` GCP project (https://github.com/kubernetes/test-infra/pull/18471). Introducing limits on jobs naturally started causing some failures, one of which was `verify-master` ([testgrid](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)). The original memory limit of `46Gi` caused the pod to be unscheduleable, so it was bumped down to `42Gi` (https://github.com/kubernetes/test-infra/pull/18502) at which point the pod became scheduleable and the job ran successfully ([job run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1288169770910224385)). At that point, after observing metrics, I mistakenly concluded that this was much higher than needed and suggested bumping down again (https://github.com/kubernetes/test-infra/pull/18502#issuecomment-665191173). This caused the job to continue to run, but to fail on `verify.typecheck` and sometimes `verify.typecheck-dockerless`.

`test/typecheck` was recently refactored to not depend on GOPATH (https://github.com/kubernetes/kubernetes/pull/92212). This was a fairly significant change so I looked at the metrics before and after the rewrite was merged.

---

`verify-* pre-merge` (June 25th)
![pre-merge](https://user-images.githubusercontent.com/31777345/88804188-2c209b00-d173-11ea-9055-9fa33bf9cb3c.png)

---

`verify-* post-merge` (June 27th)
![post-merge](https://user-images.githubusercontent.com/31777345/88804361-6b4eec00-d173-11ea-9e4d-37170c511139.png)

Memory usage nearly double for `verify-master` post-merge, which appears to be directly related to the rewrite given that `verfiy-*` on other branches remained relatively constant. This can be affirmed further by the fact that `verify-master` and `verify-beta` are failing with the new resource limits, while older release branches are not.

I can see a few options for how we may be able to remedy this issue in the short term:
- Revert the rewrite to get back to lower (yet still very high) memory usage
- Separate `typecheck` into a separate job to not reduce signal on the rest of `verify-master`
- Bump memory limits back up to `~42Gi` to get this running successfully again for now

I plan to look into fixing up `typecheck` but think it would be a good idea to take one of the directions mentioned above if this cannot be remedied quickly.

/priority critical-urgent
/sig testing
/cc @kubernetes/ci-signal @thockin @liggitt @spiffxp @BenTheElder

**Comment by liggitt** [comment]
latest run is green

**Comment by liggitt** [comment]
hmm

```
+++ Running case: verify.typecheck 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-typecheck.sh"
type-checking linux/s390x
type-checking linux/arm
type-checking linux/amd64
type-checking windows/386
type-checking darwin/amd64
type-checking windows/amd64
type-checking linux/386
type-checking linux/arm64
signal: killed
!!! Type Check has failed. This may cause cross platform build failures.
!!! Please see https://git.k8s.io/kubernetes/test/typecheck for more information.
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-typecheck.sh	386s
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1288968550895063040
