### ISSUE TITLE
NodeResourcesLeastAllocatable as score plugin

### ISSUE THREAD

**Issue by patricklundquist** [kubernetes/kubernetes#93547]
**What would you like to be added**:
Scheduling plugin "NodeResourcesLeast**Allocatable**" is a score plugin that favors nodes with fewer allocatable resources. Note that this is not the same as NodeResourcesLeast**Allocated**.

**Why is this needed**:
Our clusters consist of nodes with large differences in allocatable resources, and our services consist of pods with large differences in requested resources. Some large pods may only fit on the large nodes. We prefer to have pods scheduled on the smallest node (least allocatable) that they can fit on. Otherwise, if smaller pods are scheduled on the larger nodes, that could block the larger pods from running. Whereas if all smaller pods are scheduled on smaller nodes, the larger pods are free to run on the large nodes.

**Details**:
We have a private implementation of this in 1.17 which we will be porting to 1.18. Wanted to see if there is interest in making this a default plugin or incubating it in kubernetes-sigs/scheduler-plugins repo first.

/sig scheduling
/cc @Huang-Wei

**Comment by Huang-Wei** [comment]
@patricklundquist Thanks for the idea.

This is a good supplement to existing `NodeResourcesLeastAllocated` and `NodeResourcesMostAllocated` IMO. Here is an example I can think of:

Suppose there are 3 nodes with memory occupied/capacity as `10/2000`, `15/20` and `20/100`, and there comes a Pod requesting 5 units of memory, the preferred node for each Score plugin would be:

- NodeResourcesLeastAllocated: node1
- NodeResourcesMostAllocated: node3
- NodeResourcesLeastAllocatable (your proposal): node2

@ahg-g @alculquicondor @damemi @adtac WDYT?

---

Ideally, it's better to merge the above plugins into 2 categories

- NodeResources**Allocated** - `Least` and `Most` differentiated by PluginArgs
- NodeResources**Allocatable** - `Least` and `Most` differentiated by PluginArgs

This is based on the fact that `Least` and `Most` is totally opposite semantics, so it's only possible to have one enabled in a scheduler profile.

**Comment by alculquicondor** [comment]
Have you tried using NodeResourcesMostAllocated? I feel like it should be enough to cover your usecase.

**Comment by alculquicondor** [comment]
Actually, it might not be, given that NodeResourcesMostAllocated only takes into account percentages. Perhaps we can just have a tuning parameter "absolute/relative" for the existing plugins.

But the problem with this is that we need to know what's the global maximum.

**Comment by patricklundquist** [comment]
@Huang-Wei agreed and thanks for the example. To clarify further, this is not bin packing either. In your example, if there were a 4th node with memory allocated/allocatable of 19/21 and there came a Pod requesting 1 unit of memory, then the preferred nodes for each score plugin in your example would remain the same while the bin packing score plugin (via RequestedToCapacityRatio) would prefer node4. 

@alculquicondor the proposed plugin is looking at NodeResources**Allocatable** which is not related to the allocated resources at all. So NodeResourcesMostAllocated doesn't work here. 

The implementation involved a priority function that assigns node score as inversely proportional to the allocatable resources. To implement the MostAllocatable version, as Huang-Wei suggested doing, would change the priority function to assign node score as directly proportional to allocatable resources.

**Comment by Huang-Wei** [comment]
> given that NodeResourcesMostAllocated only takes into account percentages

True, I missed that. My example wasn't that correct. @patricklundquist could you give a better example to illustrate the difference of existing two plugins?

**Comment by alculquicondor** [comment]
> @alculquicondor  the proposed plugin is looking at NodeResources**Allocatable** which is not related to the allocated resources at all. So NodeResourcesMostAllocated doesn't work here.

My point is that checking for resources left might actually be what you want. If you just want to leave more space for bigger pods, you should be doing bin packing. Otherwise, just checking for the allocatable might be sub-optimal.

**Comment by damemi** [comment]
It sounds like bin packing, but with added preference to fill the smallest (or largest) nodes first. So you might want to run something like `NodeResourcesMostAllocated` (to pack the nodes) *with* `NodeResourcesLeastAllocatable` (to prefer the smallest nodes get packed first), is that reasonable? I think comparing the plugins to each other one-by-one won't show much difference, but what about some examples with the combination of the strategies (and considering multiple incoming pods of widely different requests)?

**Comment by patricklundquist** [comment]
@damemi, yes, sounds like you get it. A problem with only bin packing is that it doesn't prefer smallest or largest nodes, nor does it stop small pods from going to large nodes which are already partially occupied. So you could end up with small pods scheduled on a large node which blocks subsequent large pods from going to that node. 

Here's an example:
Suppose 3 nodes with allocated/allocatable of 0/10, 0/10, 0/200. 
Suppose 5 pods are scheduled in the following order with the following requests: 100, 5, 5, 5, 100

Possible node allocated/allocatable after scheduling for each plugin:

NodeResourcesLeast**Allocatable**: 
5/10, 10/10, 200/200 -- all pods scheduled, or
10/10, 5/10, 200/200 -- all pods scheduled

NodeResourcesMostAllocated: 
0/10, 0/10, 115/200 -- one pod unschedulable

NodeResourcesLeastAllocated: 
5/10, 5/10, 105/200 -- one pod unschedulable, or
5/10, 10/10, 200/200 -- all pods scheduled, or
10/10, 5/10, 200/200 -- all pods scheduled

**Comment by ahg-g** [comment]
I agree with Aldo that finding a node with the "Best Fit" (i.e.,  place the pod in the smallest free space available) is a more general approach than looking node size.

As Wei suggested, this can indeed be combined into a single plugin with with two parameters, each with two possible values: 

- `Mode` which can be either `WorstFit` or `BestFit` 
- `Utilization` which can be the utilization of node
  - `Allocatable` resources, this is the current approach which optimizes for (allocated+requested)/allocatable; or
  - `Remaining` resources, which optimizes for requested/(allocatable-allocated), and is likely to address the OP request when combined with `BestFit` mode.

**Comment by patricklundquist** [comment]
@ahg-g, with your proposed strategy there can be ties between nodes of different sizes. In those cases, there should be a strategy that can break the tie. 

Counter example:

Node 1 -- 10/20 ( 1 pod: size 10)
Node 2 -- 90/100 (2 pods: size 50 and 40)

When a pod of size 10 comes, both nodes appear equal by the proposed strategy for any combination of mode and utilization. The proposed strategy might schedule the pod on Node 2 -- 100/100 (pods 50, 40, 10)

Later, the size 40 pod is terminated, and a size 50 pod comes. But it will be unschedulable. Node 1 still has 10/20 and Node 2 now has 60/100.

This is a typical scenario for us. Preferring the smaller node works out better. As @damemi touched upon, adding a size preference is useful when combined with other plugins. NodeResourcesAllocatable, with a mode param for least or most, provides that size preference.

**Comment by ahg-g** [comment]
Right, in clusters with high churn, this may not be optimal.

The issue with combining different plugins is that they may pull in different directions, not just act as tie breakers: 

Here is an example:
Node 1 -- 30/50 (1 pod: size 10)
Node 2 -- 10/90 (2 pods: size 50 and 40)

The two scoring functions will rank those two nodes differently, and so depending on how each scoring function differentiates between the nodes, the final outcome can differ (we currently sum the scores). 

In the above example, which node do you think should rank higher?

**Comment by alculquicondor** [comment]
Not sure if you missed my proposal: To add an absolute vs relative configuration to NodeResourcesMostAllocated. Relative means to use the percentage of occupation. Absolute would mean to compare the remaining resources to an absolute (configurable) maximum.

Note that, when the cluster is empty, this behaves exactly as the new plugin you are proposing. But later, image a big pod A shows up and it fits in the biggest node (it should be empty, because all other nodes would have been preferred before it). It goes there, and then it has a remaining space. Then comes a small pod B, that fits in that remaining space. Then great, if you place it there, you know that, once pod A finishes, other alike pods would fit in there. Likely smaller pods wouldn't occupy that space, because there will be smaller nodes available.

Of course, there will be scenarios where a pod bigger than A wouldn't fit and then it has to wait. But similar scenarios could happen with the plugin you propose, where you just prefer the smaller node. Ultimately it comes to testing which strategies work best for you.

My proposal has the advantage of requiring minimal changes and avoiding adding more scores that you have to think how to combine. And I think it will be good enough.

But you can always move ahead with the plugin that describes the decision tree strategy that is proposed above, but then assigning scores might be tricky.

**Comment by alculquicondor** [comment]
The current NodeResourcesMostAllocated plugin only considers percentage of use.

For example, if a node has 10/50 occupied resources, it gets a score of 20 (from 20%). So it gets the same score as another node with 20/100.

My proposal is that you would configure the absolute maximum for the plugin (say 200). Then you score higher the node that has the smallest empty space. So the first one gets (200-40)/200*100, the second one gets (200-80)/200*100.

It's not exactly the same formula, but we are still preferring the node with the smallest empty space (except that before it only considered percentages of empty space).

**Comment by ahg-g** [comment]
> For example, if a node has 10/50 occupied resources, it gets a score of 20 (from 20%). So it gets the same score as another node with 20/100.

Not exactly, the score will depend on the incoming pod request, which we add to the occupied resources before normalizing by allocatable.

> My proposal is that you would configure the absolute maximum for the plugin (say 200). Then you score higher the node that has the smallest empty space. So the first one gets (200-40)/200100, the second one gets (200-80)/200100.

This is similar to what was discussed in https://github.com/kubernetes/kubernetes/issues/93547#issuecomment-666043851, which prefers nodes with space that `BestFit` the pod's requested resources based on the formula `100*requested/(allocatable-allocated)`, but doesn't need to define a maximum.

**Comment by patricklundquist** [comment]
https://github.com/kubernetes/kubernetes/issues/93547#issuecomment-666321459
> In the above example, which node do you think should rank higher?

The smaller node (Node 1 -- 30/50), for same reason as the example in https://github.com/kubernetes/kubernetes/issues/93547#issuecomment-666124972. There may be churn, and I'd prefer to keep the larger nodes less occupied by small pods.

IMO a plugin that scores nodes based only on size (allocatable) seems easy to reason about both the expected behavior and interactions with other plugins. A score plugin which depends on allocated, or remaining, may produce ties between nodes of different sizes.

**Comment by Huang-Wei** [comment]
IMO NodeResourcesLeastAllocated and NodeResourcesLeastAllocable would get the same eventual result in @ahg-g 's [example].

[example]: https://github.com/kubernetes/kubernetes/issues/93547#issuecomment-666321459

Let me give another example to explain why NodeResourcesLeast**Allocable** is not _always_ the optimal solution to break the tie.

Suppose we have 2 Nodes:

- Node1: 30/50
- Node2: 70/100

And here comes 3 Pods requesting 10, 20, 20 accordingly:

- NodeResourcesLeast**Allocated** - default in-tree Score plugin
    1. Pod1: tied (80% vs. 80%)
    1. If Pod1 lands on Node1, Pod2 will land to Node2, and Pod3 unschedulable
    1. If Pod1 lands on Node2, Pod2 and Pod3 can be schedulable as Node1/Node2 or Node2/Node1
    1. So there is 50% chance Pod3 become unschedulable

- NodeResourcesLeast**Allocable** - proposed in this issue
    1. Pod1 lands on Node1, and the resource usage becomes 40/50, 70/100
    1. Pod2 can only land on Node2, and so Pod3 has no place to fit
    1. So Pod3 is always unschedulable

- NodeResourcesLeast**Allocated** together with NodeResourcesLeast**Allocable**
    1. Pod1 lands on Node1 since the score tied in NodeResourcesLeast**Allocated** while Node1 gets higher score in NodeResourcesLeast**Allocable**
    1. Same as using NodeResourcesLeast**Allocable**, Pod3 is always unschedulable

**Comment by patricklundquist** [comment]
@Huang-Wei, fair point. In your example a "NodeResourcesMostAllocatable", would have worked well. We now have examples to show that none of the strategies -- NodeResourcesLeast**Allocated**, NodeResourcesLeast**Allocatable**, or the other proposed ones -- are always optimal. Given that, there are cases, such as https://github.com/kubernetes/kubernetes/issues/93547#issuecomment-666124972, where NodeResourcesLeast**Allocatable** does produce a more optimal solution than the others.

So, I would go back to @Huang-Wei's first suggestion to implement a NodeResourcesAllocatable with Least and Most differentiated by PluginArgs. Does that sound reasonable?

**Comment by alculquicondor** [comment]
My question would be: Does it make sense to ever have NodeResourcesLeastAllocated competing with NodeResourcesXAllocatable?

If not, why not parameterize the existing NodeResourcesXAllocated plugin to make relative or global comparisons, given that the behavior is pretty much equivalent to the proposed NodeResourcesXAllocatable.

**Comment by patricklundquist** [comment]
Here's an example where NodeResourcesXAllocated works with NodeResourcesLeastAllocatable.

Initially 4 empty nodes of sizes: 40, 40, 100, 100
Pod sizes sequence: 60, 10, 10, (60 terminated), 50, 50, 50, 50
Let's say the optimal scheduling is: **10/40, 10/40,** (50+50)/100, (50+50)/100

NodeResourcesLeastAllocated alone may leave a 50 pod unschedulable since a 10 pod may be placed on a 100 node. 
Possible sub-optimal scheduling: 0/40, 10/40, (10+50)/100, (50+50)/100

The variant described in https://github.com/kubernetes/kubernetes/issues/93547#issuecomment-666472576 may also leave a 50 pod unschedulable because of ties. 
Possible sub-optimal scheduling: 0/40, 10/40, (10+50)/100, (50+50)/100

NodeResourcesLeastAllocatable alone will schedule all pods, but may leave a 40 node empty. 
Possible scheduling: 0/40, (10+10)/40, (50+50)/100, (50+50)/100

NodeResourcesLeastAllocatable (higher weight) with NodeResourcesLeastAllocated (lower weight) will always end up with the optimal scheduling.

If the optimal scheduling was instead **0/40, (10+10)/40,** (50+50)/100, (50+50)/100, then NodeResourcesLeastAllocatable (higher weight) with NodeResourcesMostAllocated (lower weight) would always achieve it.

**Comment by damemi** [comment]
From a usability point I think just having another plugin to prefer smaller/larger nodes is a lot easier to understand than making the existing plugin configurable with absolute-vs-relative percentages. And still, the node with the smallest empty space isn't always going to be the smallest node.

If you used the relative/absolute percentage, if you have `NodeA` of size `10` and `NodeB` of size `100`
Then get `PodA`-`90`, it will have to go on `NodeB`, leaving `NodeB` with `10`
Then get `PodB`-`10`, with your absolute maximum of `200` Nodes `A` and `B` will be considered equivalent based on their amount of empty space with the global max.

In this case, NodeA is *significantly* smaller and the goal is to treat vastly different nodes (running widely varying pods) differently:

> Our clusters consist of nodes with large differences in allocatable resources, and our services consist of pods with large differences in requested resources.

Which I don't think has been really covered in our examples so far. But I think that really your goal is to make sure that smaller workloads get scheduled onto smaller nodes (since, like in my example, it's possible that your larger workloads will simply not fit onto the smaller nodes)

**Comment by Huang-Wei** [comment]
I also felt the configurable absolute-vs-relative percentage would be hard to tune and hence not easy to use.

So +1 to NodeResourcesLeastAllocatable as a separate plugin, at least in scheduler-plugin repo if not in upstream.

**Comment by alculquicondor** [comment]
Even if it goes in upstream, it shouldn't be a default plugin. So starting in scheduler-plugins seems like the best idea.

However, my concern is that if you introduce new plugins, then users need to think about how to combine them, for which they have to know the competition algorithm (formula) for scores. For that reason, I would prefer a single configurable plugin.

**Comment by Huang-Wei** [comment]
> However, my concern is that if you introduce new plugins, then users need to think about how to combine them, for which they have to know the competition algorithm (formula) for scores. For that reason, I would prefer a single configurable plugin.

True. Indeed I think we're lacking in a tool to quickly identify whether a new plugin can resolve a particular need, while not breaking existing behavior. For example, we may come up with a simulator tool, by giving some workload presets and expected scheduled result, and automatically run the simulator to check if a new plugin can make most of the cases better, or not. Also this should be able to help tune the default weight as well.

**Comment by damemi** [comment]
It's going to create work for the users either way, whether it's considering how a new plugin will interact with the others vs considering how to tweak the configuration and understanding that new formula. I think understanding a simple, new plugin is easier than configuring a complex one that performs differently based on inputs by merging separate plugins.

I do agree that it shouldn't be enabled by default though, and like the idea of scheduler-plugins as an incubating repo.

**Comment by adtac** [comment]
Is it possible to have the same plugin with different plugin args and different weights enabled? If not, that's another point to consider by fitting all use-cases in one configurable plugin.

**Comment by alculquicondor** [comment]
/close

A implementation was done in kubernetes-sigs/scheduler-plugins#36
