### ISSUE TITLE
job fails before the `.spec.backoffLimit`

### ISSUE THREAD

**Issue by georgettica** [kubernetes/kubernetes#93559]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
$oc create job -f job.yaml
$ oc get job jobname -ojson | jq .status
{
  "active": 1,
  "failed": 1,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "active": 1,
  "failed": 2,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "active": 1,
  "failed": 3,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "active": 1,
  "failed": 4,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "conditions": [
    {
      "lastProbeTime": "2020-07-30T06:53:10Z",
      "lastTransitionTime": "2020-07-30T06:53:10Z",
      "message": "Job has reached the specified backoff limit",
      "reason": "BackoffLimitExceeded",
      "status": "True",
      "type": "Failed"
    }
  ],
  "failed": 5,
  "startTime": "2020-07-30T06:45:37Z"
}
$ oc get job jobname -ojson | jq .spec.backoffLimit
6
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: 4.5.3
Server Version: 4.4.13
Kubernetes Version: v1.17.1+b8568b
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux CoreOS"
VERSION_ID="4.4"
OPENSHIFT_VERSION="4.4"
RHEL_VERSION="8.2"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.4"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.4"
OSTREE_VERSION='44.82.202007141430-0'
- Kernel (e.g. `uname -a`):
Linux ip-10-0-192-232 4.18.0-193.13.2.el8_2.x86_64 #1 SMP Mon Jul 13 23:17:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
apiVersion: batch/v1
kind: Job
metadata:
  name: sre-build-test-fail
  namespace: openshift-build-test
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io
                operator: In
                values:
                - infra
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          # ensure we fail if something exits non-zero
          set -o errexit
          set -o nounset
          set -o pipefail
          exit 1

        imagePullPolicy: Always
        name: sre-build-test
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io
        operator: Equal
        value: infra

**Comment by georgettica** [comment]
not sure but that is the best I can think of at this time

**Comment by huangxinxin-szu** [comment]
i have noticed this problem also, and sometimes, it seems to be work normally.

**Comment by huangxinxin-szu** [comment]
i have noticed this problem also, and sometimes, it seems to work normally.

**Comment by georgettica** [comment]
so I found out that in [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L509) the test is `times + 1` so this can cause the issue.. it has been there from the beginning of the codes inception..

WDYT?

**Comment by soltysh** [comment]
Duplicate of #92245.
/close
