### ISSUE TITLE
kube2sky should do smart updates including not deleting-recreating for each update

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#9355]
To do a DNS update, kube2sky currently deletes all records related to a service and then recreates them.

1. For unchanged records: This is not desirable since there is a brief interval where valid records that did not need to be changed, are unavailable (since they are being deleted and re-created)

2. For modified records: instead of deleting and recreating entries, it should be possible to simply overwrite the etcd entries for the modified records since the etcd key strings are stable.

3. For records that are new or being deleted, no work needs to be done. 

@thockin

**Comment by thockin** [comment]
obsoleted by kube-dns rewrite
