### ISSUE TITLE
[SIG Release, SIG Testing] "Extract" phase is failing for multiple jobs using the ci/latest-fast version marker

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#93561]
**Which jobs are failing**:

`master-blocking` jobs:

- ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew-serial
- ci-kubernetes-gce-conformance-latest
- ci-kubernetes-e2e-gci-gce
- ci-kubernetes-e2e-ubuntu-gce-containerd
- ci-kubernetes-e2e-gci-gce-alpha-features
- ci-kubernetes-e2e-gci-gce-reboot
- ci-kubernetes-e2e-gce-device-plugin-gpu
- ci-kubernetes-e2e-gci-gce-ingress
- ci-kubernetes-e2e-gci-gce-scalability

`master-informing` jobs:

- ci-kubernetes-e2e-gce-scale-correctness
- ci-kubernetes-e2e-gce-scale-performance

**Which test(s) are failing**:

`Extract`

**Since when has it been failing**:

~18:05 PDT, 7/29

**Testgrid link**:

Example: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default

**Reason for failure**:

https://github.com/kubernetes/test-infra/pull/18533, https://github.com/kubernetes/sig-release/issues/850

**Anything else we need to know**:

I'll look into this, as it has to do with recent version marker changes.

/assign
/sig release testing
/area release-eng
/priority critical-urgent
cc: @kubernetes/ci-signal @kubernetes/release-engineering @spiffxp

**Comment by justaugustus** [comment]
/assign @hasheddan 
/unassign

Dan is picking this up, since I'm packing.
Knowledge transfer here: https://kubernetes.slack.com/archives/CN0K3TE2C/p1596103219238000

**Comment by hasheddan** [comment]
/reopen

Not sure we are done here yet

**Comment by hasheddan** [comment]
This could definitely be a problem: https://testgrid.k8s.io/sig-release-master-blocking#build-master-fast&graph-metrics=test-duration-minutes

**Comment by justaugustus** [comment]
The timeouts in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/128881586978213478?
Resource starvation maybe?

Can you file a separate issue or maybe roll this into the existing one about QOS?
We are writing to the correct location when the job isn't timing, so it's orthogonal to this issue.

**Comment by hasheddan** [comment]
@justaugustus sure :+1: Also looks like last two runs were now successful. Am I correct that the changes in the PR to match `ci/latest-fast` will not be reflected until kubekins bump happens today?

**Comment by hasheddan** [comment]
Noted on https://github.com/kubernetes/test-infra/issues/18530

**Comment by BenTheElder** [comment]
> @justaugustus sure +1 Also looks like last two runs were now successful. Am I correct that the changes in the PR to match ci/latest-fast will not be reflected until kubekins bump happens today?

why is this dependent on a kubekins bump?

**Comment by hasheddan** [comment]
@BenTheElder we thought it had to do with how `kubetest` was extracting the fast build, and the modifications we made (https://github.com/kubernetes/test-infra/pull/18535) would not be not be seen until jobs were bumped to use new version of `kubekins` image

**Comment by hasheddan** [comment]
Another update, `kubekins` bump for today (https://github.com/kubernetes/test-infra/pull/18544) just happened so we'll see if the added logs help us identify what is going awry here

**Comment by hasheddan** [comment]
Found issue, PR coming
