### ISSUE TITLE
topologySpreadConstraints cannot spread pods evenly when whenUnsatisfiable is set to ScheduleAnyway

### ISSUE THREAD

**Issue by wjun** [kubernetes/kubernetes#93565]
/sig scheduling

**What happened**:
I have 3 nodes: 1 master node(with NoSchedule taints) and 2 worker nodes. All of them can be scheduled to run CoreDNS pods(with NoSchedule and CriticalAddonsOnly tolerations). My nodes have two topology keys: zone and hostname. I set two topologySpreadConstraints on these topology keys for the CorDNS deployment, and set 'whenUnsatifiable: ShcedueAnyway' and 'maxSkew: 1'. These 3 nodes have the same zone name. I set 4 replicas in this CoreDNS deployment. These 4 pods are scheduled and running on two worker nodes(2:2) in this case. But if I set 'whenUnstaifiable:DoNotSchedule', these 4 pods will run on 3 nodes evenly(1:1:2).

**What you expected to happen**:
No matter what value is set to 'whenUnsatifiable', these 4 pods should run on these 3 nodes(1:1:2) evenly.

**How to reproduce it (as minimally and precisely as possible)**:
I can reproduce with the described replicas, nodes and two topology keys with the same zone name but different hostnames.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.18.3
- Cloud provider or hardware configuration: vSphere provider
- OS (e.g: `cat /etc/os-release`): Photon3

**Comment by ahg-g** [comment]
I expect this not to happen in 1.19 because the score function of pod topology spread significantly improved compared to 1.18

/cc @alculquicondor

**Comment by alculquicondor** [comment]
If you have access to the scheduler configuration in your cluster, I suggest you increase the weight of the score to at least 5.

**Comment by wjun** [comment]
@alculquicondor @ahg-g If we switch to 1.19 when it is ready, this issue will be resolved automatically, or depending on the worker nodes loads, there is still possibility that topologySpreadContraints is not satisfied, with the default scheduler weights of scores?

**Comment by alculquicondor** [comment]
there is always going to be that the constraints are not satisfied. That's how scoring works. If other scores are more important, we are going to honor them.

What changes in 1.19 is that topology spreading has more meaningful scores that achieve better spreading.
