### ISSUE TITLE
"Back-off restarting failed container": log which container failed

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#93575]
**What would you like to be added**:

The event `Back-off restarting failed container` should become `Back-off restarting failed container <CONTAINER_NAME>`

**Why is this needed**:

Its hard to tell which container failed, you need to dig through the describe output and find something like

```
    State:          Waiting
      Reason:       CrashLoopBackOff
```

**Comment by SergeyKanzhelev** [comment]
Copying from the PR:

> This increases the back off event writes per pod … the Kubelet throttles event writes and simply omits events over a certain threshold, so increasing the number and variety of events this way could easily drop any events fro other pods

I propose to close it - reasoning seems very sound. @howardjohn do you agree? Or you are still looking for better troubleshooting experience?

**Comment by SergeyKanzhelev** [comment]
closing based on this: https://github.com/kubernetes/kubernetes/pull/93636#pullrequestreview-459673743

Please re-open if the existing experience is not working.

/close
