### ISSUE TITLE
Loosen ConfigMap Max Size Validation

### ISSUE THREAD

**Issue by jaredhancock31** [kubernetes/kubernetes#93576]
**What would you like to be added**:

[Newer versions of etcd expose](https://etcd.io/docs/v3.4.0/dev-guide/limit/) `--max-request-bytes` to bypass the default limit of 1.5MB. Currently apis/core validation rejects anything exceeding 1MB. It would be ideal to loosen validation so that we can take advantage of this.

**Why is this needed**:

ConfigMaps/CRDs may have fields that persist large blobs of text, like a config file. These can be non-trivial to break up for the purposes of bypassing the now-artificial size limit.

**Comment by BenTheElder** [comment]
Kubernetes's homebrew CI https://github.com/kubernetes/test-infra/tree/master/prow places too much text into one configmap.
The solution to this was to add transparent GZIP file reading support to the application and start uploading the contents GZIPed

https://github.com/kubernetes/test-infra/pull/11714/files
https://github.com/kubernetes/test-infra/pull/11745

**Comment by jpbetz** [comment]
Lots of kubernetes clusters are running older versions of etcd. The current limit seems the best for those clusters.

And I suspect if we did raise the limit to 1.5MB it would only be a sort period of time before we got the request to raise it again.

**Comment by jaredhancock31** [comment]
If my understanding is correct, the original reason for adding the validation was due to etcd's constraint. Now that it is configurable, why not follow suit from the k8s layer? While there may be performance considerations, isn't that more of a domain problem than not? I tend to prefer flexibility over hard barriers like this, just my 0.02. 

We're considering going a route similar to the one described in [this issue](https://github.com/kubernetes/kubernetes/issues/88709), but obviously that comes with its own additional overhead. Thanks for the quick responses.

**Comment by liggitt** [comment]
the combination of performance considerations and inconsistency of use (this configmap will only work on "special" clusters) makes me think this is not a great place to add flexibility

**Comment by jaredhancock31** [comment]
Oh well, worth a shot. 

So is there a recommended solution for this scenario then? I've seen a lot of discussions on slack/SO/etc around this, each with their own hacks. None appear particularly compelling, imo. We aren't looking to persist gigs worth of data or anything - just want to be able to handle a few MBs should the config warrant it. 

We can close this issue, but if any of you have proven workarounds that would be fantastic. Thanks again
