### ISSUE TITLE
hack/verify-typecheck-providerless.sh outputs many errors and failure messages but does not fail

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93574]
make verify WHAT=typecheck-providerless

outputs

> `ERROR(linux/arm): failed to verify: /usr/bin/gopackagesdriver: exit status 1: gopkgsdriver: 6.578579496s for GOROOT=/usr/local/google/home/liggitt/.gvm/gos/go1.15beta1 GOPATH=/usr/local/google/home/liggitt/go/src/k8s.io/kubernetes/_output/local/go GO111MODULE=off GOPROXY= PWD=/usr/local/google/home/liggitt/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes go [go list -tags selinux,providerless -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags selinux,providerless -- ./. ... long package listing ... ]: exit status 2: go build k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure: build constraints exclude all Go files in /usr/local/google/home/liggitt/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure
> `go build k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/openstack: build constraints exclude all Go files in /usr/local/google/home/liggitt/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/openstack`
> `# runtime/cgo`
> `gcc: error: unrecognized command line option '-marm'; did you mean '-mabm'?``
> `ERROR(linux/s390x): failed to verify...`
> cc1: error: bad value (‘z196’) for ‘-march=’ switch
> cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
> `ERROR(windows/386): failed to verify: /usr/bin/gopackagesdriver: exit status 1: gopkgsdriver`

but the overall verify command exits with return code 0

/cc @BenTheElder 
/milestone v1.19

**Comment by liggitt** [comment]
see example successful run: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93570/pull-kubernetes-typecheck/1288837133829672961

**Comment by RobertKielty** [comment]
For reference - https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190729-building-without-in-tree-providers.md

**Comment by liggitt** [comment]
fix in #93579

**Comment by BenTheElder** [comment]
_screaming_
