### ISSUE TITLE
Investigate removal of call to generatePodSandboxLinuxConfig for Windows kubelet

### ISSUE THREAD

**Issue by ddebroy** [kubernetes/kubernetes#93580]
**What happened**:
When testing https://github.com/kubernetes/kubernetes/pull/93475, @ravisantoshgudimetla pointed out that invocation of `generatePodSandboxLinuxConfig` is necessary for the Windows pods to come up: https://github.com/kubernetes/kubernetes/pull/93475/files#r463009694 . Skipping the call to `generatePodSandboxLinuxConfig` leads to a CNI error.

**What you expected to happen**:
Windows pods should be able to come up without having to call `generatePodSandboxLinuxConfig`

**How to reproduce it (as minimally and precisely as possible)**:
Remove invocation of `generatePodSandboxLinuxConfig` for Windows paths and test Windows pod bringup.

**Anything else we need to know?**:
Ideally we should be able to accomplish https://github.com/kubernetes/kubernetes/pull/93475/files#r462857857

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jayunit100** [comment]
@ddebroy in principal does https://github.com/kubernetes/kubernetes/pull/96180 look good enough to you as a starting point? if so ill test it and verify it on windows 2019

**Comment by jayunit100** [comment]
bump @ddebroy :)
