### ISSUE TITLE
Add a new function Enqueue to QueueSort Plugin

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#93591]
**What would you like to be added**:

Add a new function `Enqueue` to `QueueSort` plugin. `Enqueue` is the first plugin function in a scheduling cycle and is called before a pod is added to `SchedulingQueue`.

```
type QueueSortPlugin interface {
    Plugin
    Enqueue(*QueuedPodInfo) *Status
    Less(*QueuedPodInfo, *QueuedPodInfo) bool
}
```
It can be a separate Plugin too.

**Why is this needed**:

Advanced scheduling will need to check and construct some data structures when a new pod arrives. The information will be used in `QueueSort` (i.e., `Less` function) or other extension points.  Here are some use cases.

1.  Advanced policies for pod scheduling order. For example, to implement a capacity or fair share scheduler similar to YARN, multiple "virtual queues" with different capacity limits (e.g., min, max) or fair shares can be created.  An `Enqueue` plugin can associate a pod with a "virtual queue" before adding it to the real scheduling queue. `Less` function can then use a Pod's "virtual queue" information to determine its proper scheduling order.  For example,  a pod from a "virtual queue" that overuses its fair share will be placed after a pod from a "virtual queue" that underutilizes its fair share. 

1.  [coscheduling](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling) needs to obtain or create a PodGroup for a new arriving pod. 

Without `Enqueue`, we have to perform initialization in `Less` function, which is not efficient.

1. If the scheduling queue is empty, `Less` function will not be invoked and the information will not be initialized properly. Other plugins have to check and do it again.
2. A pod in the scheduling queue may be passed to `Less` function multiple times, which will lead to duplicate processing.

**Comment by denkensk** [comment]
A pod in the scheduling queue can be passed to Less function multiple times, which will lead to duplicate processing.
-----
The function is invoked when he pod is first added to the scheduler queue or it can be invoked when the unschedule pod requeue？ @yuanchen8911

**Comment by yuanchen8911** [comment]
> > A pod in the scheduling queue can be passed to Less function multiple times, which will lead to duplicate processing.
> 
> -----
> 
> 
> 
> The function is invoked when the pod is first added to the scheduler queue or it can be invoked when the unschedule pod requeue？ @yuanchen8911 

Good question, we will probably have a clean and simple design&implementation if the function is called in both cases (whenever a pod is added to the queue). We just let the plugin distinguish each case.

**Comment by denkensk** [comment]
Thanks. Maybe we can think about it in `Efficient Requeuing of Unschedulable Pods` to cover this case in coscheduling.

**Comment by Huang-Wei** [comment]
@yuanchen8911 I understand it's a good-to-have in the queueSort based coscheduling implementation. But I felt reluctant to add it in QueueSort extension point as it's in the critical path (when enqueuing every single Pod), unless we have another one or two promising use cases.

**Comment by yuanchen8911** [comment]
> @yuanchen8911 I understand it's a good-to-have in the queueSort based coscheduling implementation. But I felt reluctant to add it in QueueSort extension point as it's in the critical path (when enqueuing every single Pod), unless we have another one or two promising use cases.

1. Generally speaking, the feature is critical for developing advanced Pod sorting policies. For example, in order to implement a capacity or fair share scheduler similar to YARN., we can create multiple "virtual queues" with different capacity limits (e.g., min, max) or fair shares.  Enqueue function associates a pod with a "virtual queue" before adding it to the real scheduling queue. Less function can then use the "virtual queue"  information to determine the proper scheduling order.  For example,  a pod from a "virtual queue" that overuses its fair share will be placed behind a pod from a "virtual queue" that underutilizes its fair share. 

2. If no Enqueue is specified in a profile, the overhead is negligible, isn't it?

**Comment by everpeace** [comment]
Thank you for opening the issue! 

> A Less function then determines the proper scheduling order for the pod based on its virtual queue information

Current `Less` function takes two `PodInfo`s and this is assumed to be _pure_ function.  So, every pod update will be informed to scheduling queue and scheduling queue to maintain its rank in the internal heap.  So, if the function is _impure_, for example, `Less(podInfoA, podInfoB)` depends on some __external__ information like fair share or other associated resource statuses, the internal heap in scheduling queue can't keep consistent order for it.

We could have two option to solve it

- introduce some context in `PodInfo` and endpoint in `QueueSort` plugin to notify to update `PodInfo`
- introduce internal heap which calculates max `PodInfo` in every pop 
  - it takes `O(N)` where `N` is the number of `PodInfo`s in the active queue
  - we can't call it _heap_ anymore in this situation thoguh

**Comment by denkensk** [comment]
> introduce some context in PodInfo and endpoint in QueueSort plugin to notify to update PodInfo
---
Can you add more details? I think the PodInfo update operation will need to the resort of heap. How to achieve this？
@everpeace

**Comment by everpeace** [comment]
@denkensk  sorry for the late reply.  

> introduce some context in PodInfo and endpoint in QueueSort plugin to notify to update PodInfo

I thought kind of things below:

```golang
type FrameworkHandle {
  // expose keyfunc for QueueSortPlugin resolving key of Pod in heap
  QueuedPodInfoKeyFunc func(*v1.Pod) (string, error)
}

type QueuedPodInfo {
...
    // This context is allowed to update via QueueSortPlugin
    // and QueueSortPlugin.Less can depend on this field
    context map[string]interface{}
}

type QueueSortPlugin interface {
    Plugin
    Less(*QueuedPodInfo, *QueuedPodInfo) bool
    // as proposed
    Enqueue(*QueuedPodInfo) *Status

    // This method will update QueuedPodInfo.context and 
    // resort heap that will invoke Less O(log N) times.
    // This requires a lock of SchedulingQueue in each Update.
    Update(podKey string, context map[string]interface{})
}
```

**Comment by ahg-g** [comment]
I think what we can do is add `Enqueue`, `Dequeue` and `Update` extension points that gets invoked at `addPodToSchedulingQueue`, `deletePodFromSchedulingQueue` and `updatePodInSchedulingQueue` events respectively.

To determine the exact state of the pod, I think we can add a queueing status to `QueuedPodInfo` that indicates whether it is in `active`, `unschedulable` or `backoff`.

**Comment by everpeace** [comment]
I love ahg-g's idea.

> add `Enqueue`, `Dequeue` and `Update` extension points that gets invoked at `addPodToSchedulingQueue`, `deletePodFromSchedulingQueue` and `updatePodInSchedulingQueue` events respectively.

I think `Dequeue` might be confused with `Pop`.  How about `Add`, `Delete`, `Update` so that it aligns to private methods??

**Comment by Huang-Wei** [comment]
I think the requirement is still valid - the `Less()` function is implicitly called during internal heap sorting, which is not the right place to perform business logic.

Sorting between individual Pods is easy. Today we just sort by their queued timestamp to achieve both prioritization and fairness. However, some business usecases use a CRD to represent a number of pods, and want the CRD (backing by a group of pods) to be efficiently scheduled, which needs to sort between CR Objects, as well as CR Object vs. regular pod. However, as the CR Object is an entity, it's not ideal to use a single pod's queued timestamp (may cause unexpected heap sorting behavior), or the CR Object's creation time to do sorting (which is static); instead, you have to virtually queue the entire CR Object dynamically. Like the discussion mentioned in https://github.com/kubernetes-sigs/scheduler-plugins/issues/110#issuecomment-903994227, this is not easy to achieve without the help of a notification mechanism on when a pod gets enqueued / popped out.

I will dig more into related requirements and come up with a design.

**Comment by everpeace** [comment]
> I will dig more into related requirements and come up with a design.

Thanks for heading up the issue!! Let me share our internal use-case to explain a need for _impure `Less()` functions_ (aka non-referential transparent). 

We have a multi-tenant on-premise kubernetes cluster. Most workloads are machine-learning large batch jobs. Each tenant has some _Credit_  CR that is controlled by multiple policies and maintained by cluster administrators (e.g. pay-as-you-go, idle pod penalty, etc.).  Pods in each tenant should be sorted according to the tenant's _Credit_ CR. The credit value is also used in preemption. Although annotating the credit balance to pods can make `Less(podA, podB)` pure,  it would increase api server's load because credits change dynamically with high-frequency in large cluster (roughly the same rate of pod's start/finish).  

Thus, supporting queue sort by custom _impure functions_ would be very appreciated.

**Comment by Huang-Wei** [comment]
> Thus, supporting queue sort by custom _impure functions_ would be very appreciated.

I suppose by "impure functions", you meant the proposal in https://github.com/kubernetes/kubernetes/issues/93591#issuecomment-671913732. If so, I don't think it's feasible because it'd change the nature property of a heap - as you mentioned, it's no longer a heap.

What I'm thinking is just proper enqueue/popping extension semantics. With that, in your use case, what we can achieve is:

- suppose the first pod from a tenant gets enqueued, in your scheduling plugin, maintain a "snapshotted" credit value for this tenant, also a counter N recording how many pods are being queued. In this case, N is 1.
- let's say another pod from the same tenant gets enqueued, increase its N by 1. Next, check if N is 1:
  - if yes, refresh the "snapshotted" credit value - so you can see here, we introduced the "restricted" dynamics for a tenant's credit usage
  - if no, still use the "snapshotted" (old maintained) credit value for queue sorting
- if a pod from the tenant gets popped out, decrease its counter by 1

**Comment by denkensk** [comment]
How about if we want to use `the used resource / the allocated resource` like utilization rate to affect the order of pod out of the queue, not only the scheduled pods will affect the results, but also the deleted pods will affect the results.

**Comment by Huang-Wei** [comment]
> How about if we want to use `the used resource / the allocated resource of multi-tenant` like utilization rate to affect the order of pod out of the queue

Theoretically, it's doable. But that means you have to sort ALL the pods on each pop() - i.e., with a time complexity O(N•logN) instead of O(logN). I don't think we'd like to go in this direction.

> not only the scheduled pods will affect the results, but also the deleted pods will affect the results.

I don't quite follow, what do you mean by "deleted pods will affect the results".

**Comment by everpeace** [comment]
> But that means you have to sort ALL the pods on each pop() - i.e., with a time complexity O(N•logN) instead of O(logN). I don't think we'd like to go in this direction.

Yeah, rebuilding heap takes O(N•logN).  However, if we could step away from a heap and a user could give the function for pod rank in the queue instead, I think we could just use a hash map for the internal queues.  This can achieve `O(N)` pop (scan the map and select the minimum score) and `O(1)` add/update/delete.  In this case, we should support both data structures (heap and hashmap) for internal queues though.  By the way, when pod rank in the queue was determined externally (i.e. impure case), `O(N)` would be the tight lower bound for pop (choosing the minimum) because we have to see the ranks of all the pods in the queue at the instant of popping out.

**Comment by denkensk** [comment]
> deleted pods will affect the results

Sorry, I mean, if we delete the running pod, the resource usage will be reduced, and the rate of this tenant will be reduced. This may affect the order of queues.

**Comment by Huang-Wei** [comment]
> However, if we could step away from a heap and a user could give the function for pod rank in the queue instead, I think we could just use a hash map for the internal queues.

Even we have built-in support for heap/hashmap, we're unable to open it to users unless we have multi-queue support. But again, I think O(n) for each operation is a bit too much.

**Comment by kerthcet** [comment]
If we're going to add a new extension point enqueue here in https://github.com/kubernetes/enhancements/pull/3522, we can close this issue now.

**Comment by ahg-g** [comment]
Yes, we can close this one.

/close
