### ISSUE TITLE
kubeadm init stuck at "Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s"

### ISSUE THREAD

**Issue by LeonYanghaha** [kubernetes/kubernetes#93595]
/sig area/kubeadm
I installed k8s on a clean ubunut. When I executed the command  ```  kubeadm init   -v=7  ```, I was confused. my port 6443 was not listening. 

![image](https://user-images.githubusercontent.com/23301914/89012241-74db7e00-d344-11ea-9172-f2ce6525ad7b.png)

After doing this many times, tell me ``` The kubelet is not running```,I see  kubelet  running through the command ``` ps aux ```.I saw this [issue](https://github.com/kubernetes/kubernetes/issues/56148), but it didn't solve my problem. who can tell me , why ? thank you .

![image](https://user-images.githubusercontent.com/23301914/89012383-b8ce8300-d344-11ea-8c3e-82d51b0fcba6.png)

OS： Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-70-generic aarch64)
Docker： 19.03.6

**Comment by neolit123** [comment]
hi, please the support channels for such questions or #kubeadm or k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

also see https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-blocks-waiting-for-control-plane-during-installation

at that point kubeadm waits for the kubelet and api-server to start returning "OK" on their health endpoints.
you can use `journactl -xeu kubelet` to look at the kubelet logs or `docker log ...` to check the logs of the api-server container.

we also don't have official e2e tests on ARM64 at the moment, but there are users out there using ARM64.

/close
