### ISSUE TITLE
ListNodes sometimes returns 'null' instead of empty list for .items[].status.images[].names (v1.10)

### ISSUE THREAD

**Issue by lallydd** [kubernetes/kubernetes#93606]
**What happened**:
On a call to ListNodes, the returning JSON had 'null' instead of an empty list in `ContainerImage.names`.  Failing validation in the client.

```json
$ cat ~/error.json | jq '.items[39].status.images[11]'
{
  "names": null,
  "sizeBytes": 226150943
}
```

**What you expected to happen**:
Returned value to contain something like this:
```json
{
  "names": [],
  "sizeBytes": 226150943
}
```

**How to reproduce it (as minimally and precisely as possible)**:
AFAICT, a container image with no name.

**Anything else we need to know?**:
Ref https://github.com/kubernetes-client/haskell/issues/72
Go really likes nulls: https://play.golang.org/p/aZOHv_YShtz (copied from the issue above)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration: AWS (but not EKS)
- OS (e.g: `cat /etc/os-release`): client is macos
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lallydd** [comment]
Note that this is an FYI bug report, I'm going to have to hack around the problem here no matter what.  A "it's fixed in less-ancient versions of k8s" is perfectly cool by me.

**Comment by liggitt** [comment]
/remove-sig api-machinery
/sig node

the field should likely be marked as optional. protobuf serialization does not preserve the distinction between empty and null lists

**Comment by lallydd** [comment]
That'd solve the problem.
