### ISSUE TITLE
Support for --register-with-taints in kubemark hollow-kubelet args

### ISSUE THREAD

**Issue by abansal4032** [kubernetes/kubernetes#93608]
**What would you like to be added**:
The kubemark hollow-kubelet should expose setting --register-with-taints through args for the test.

**Why is this needed**:
1. It would be beneficial to have the nodes come up with taints to avoid scheduling of regular pods on the nodes. The specific workloads can then be scheduled on the hollow-nodes by adding tolerations. This would help for environments where the actual nodes and the kubemark nodes run on the same cluster.
2. Sometimes the hollow nodes are scheduled on other hollow-nodes making them unusable.

**Comment by yujuhong** [comment]
@kubernetes/sig-scalability

**Comment by mm4tt** [comment]
This can be done similarly to the node-labels flag - https://github.com/kubernetes/kubernetes/blob/8d54a84507c622e1552373d5d125c84ee22d1465/cmd/kubemark/hollow-node.go#L90

/good-first-issue
/help-wanted

**Comment by kshitijcode** [comment]
I can try to fix this :)
/assign

**Comment by kshitijcode** [comment]
@mm4tt : Is setting `--register-with-taints` of type map ?

**Comment by ravindrabhargava** [comment]
Hi,
I would like to contribute

**Comment by kshitijcode** [comment]
@ravindrabhargava  : We already have an approved PR for this.
