### ISSUE TITLE
Following instructions to install production environment

### ISSUE THREAD

**Issue by gprakriya** [kubernetes/kubernetes#93616]
**What happened**: Kubelet would not start, brand new installation. (Following instructions ; Bootstrapping clusters with kubeadm

**What you expected to happen**: Expected kubelet to start

**How to reproduce it (as minimally and precisely as possible)**: Per instructions, i was at the end to start the kublelt

**Anything else we need to know?**: Brand new installation

**Environment**: centos 7.6
- Kubernetes version (use `kubectl version`): 1.18.3
- Cloud provider or hardware configuration: HP Hardware
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`): Linux hpwbff223 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: I am following https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- Network plugin and version (if this is a network-related bug): Not network related
- Others: kubelet: F0731 16:39:07.275508   14855 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory

**Comment by neolit123** [comment]
> Expected kubelet to start

kubelet would crashloop until one calls `kubeadm init/join` on the node.

for general support questions try using our support channels and #kubeadm on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/triage support
/sig cluster-lifecycle
/close
