### ISSUE TITLE
PodSecurityPolicy admission plugin selects and uses policy that service account is not authorized to use.

### ISSUE THREAD

**Issue by amdonov** [kubernetes/kubernetes#93615]
**What happened**: 

I created a restrictive PodSecurityPolicy, restricted, that is available to all service accounts and authorized users. I created a permissive PodSecurityPolicy, privileged, that is only authorized for use by service accounts in specific namespaces. It is not available in the psp-example namespace. I confirmed these settings with the following commands.

```
kubectl --as=system:serviceaccount:psp-example:default -n psp-example auth can-i use podsecuritypolicy/privileged
Warning: resource 'podsecuritypolicies' is not namespace scoped in group 'policy'
no
kubectl --as=system:serviceaccount:psp-example:default -n psp-example auth can-i use podsecuritypolicy/restricted
Warning: resource 'podsecuritypolicies' is not namespace scoped in group 'policy'
yes
```

I enabled the PodSecurityPolicy admission plugin.

Pods created directly behave as expected - 
When I create attempt to create a pod that violates the restricted policy in the psp-example namespace it is blocked. Pods that do not violate the restrictive policy succeed and are annotated with "kubernetes.io/psp: restricted" 

Pods created by deployments succeed when they should be blocked -

If I create a deployment in the psp-example namespace that violates the restrictive policy, it selects the privileged PodSecurityPolicy. The pod is annotated with "kubernetes.io/psp: privileged", and the pod starts. This should not happen. Neither the user account that creates the deployment nor the service account used by the deployment has permission to use the privileged PodSecurityPolicy.

**What you expected to happen**:

The admission plugin should not select a PodSecurityPolicy that cannot be used by the service account that runs the pod.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the example https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example.
Create an additional policy that would allow privileged containers but don't allow the psp-example:default service account to use it.
Create a deployment in the psp-example namespace that use privileged containers.
```
kubectl-user create -f- <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
  namespace: psp-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - name:  pause
        image: k8s.gcr.io/pause
        securityContext:
          privileged: true 
status: {}
EOF
```
Confirm that a pod is created (it shouldn't be) and that the psp annotation on the pod is for a psp that the service account can't access

```
kubectl describe pod -n psp-example -l app=test
```

**Anything else we need to know?**:

kube-controller-manager is running with --use-service-account-credentials=true

I poked around the code a bit, but I couldn't debug much because logging is pretty sparse. I think there is a chance that the use of the kubernetes.io/psp annotation bypasses the isAuthorizedForPolicy method. However, I could certainly be misinterpreting things.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

AWS m5.large nodes

- OS (e.g: `cat /etc/os-release`):

NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

- Kernel (e.g. `uname -a`):

Linux #### 3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:54:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Network plugin and version (if this is a network-related bug):

Flannel - not network related

- Others:

**Comment by amdonov** [comment]
/sig/auth

**Comment by liggitt** [comment]
What does the following return?

``` 
kubectl --as=system:serviceaccount:kube-system:replicaset-controller -n psp-example auth can-i use podsecuritypolicy/privileged
```

**Comment by amdonov** [comment]
kubectl --as=system:serviceaccount:kube-system:replicaset-controller -n psp-example auth can-i use podsecuritypolicy/privileged
Warning: resource 'podsecuritypolicies' is not namespace scoped in group 'policy'
yes

I allowed service accounts all existing namespaces to use the privileged policy so I didn't break anything by enabling the PodSecurityPolicy plugin. My plan was to remove that permission for each namespace as I worked to enforce the restricted policy. I was testing with a new namespace. Based upon the documentation, my understanding was that the RBAC bindings of the service-account referenced in the deployment drove the list of potential policies. Is that not correct?

**Comment by liggitt** [comment]
The permissions of the service account of the pod AND the identity creating the pod (in this case, the replicaset controller) are consulted and if either has the ability to use the policy, the pod is allowed. 

See guidance in https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies:

> Granting the controller access to the policy would grant access for all pods created by that controller, so the preferred method for authorizing policies is to grant access to the pod's service account.

**Comment by amdonov** [comment]
Thanks for your help. I did not release that another account was in the mix. I thought --use-service-account-credentials=true caused the controller to use the sa specified in the securityContext.
