### ISSUE TITLE
Document requirements for adding new architectures

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#93620]
Need to follow up on:
- https://github.com/kubernetes/kubernetes/issues/87056#issuecomment-666493661

/sig architecture
/assign

**Comment by BenTheElder** [comment]
This is a perennial issue. We more or less seem to require that someone solve this before a new architecture is added, so eventually someone else will have to do this, or be told they can't add an architecture because this has not been done.

/lifecycle frozen

**Comment by dims** [comment]
i think we have sufficient guidance now https://github.com/kubernetes/sig-release/blob/master/release-engineering/platforms/guide.md

**Comment by BenTheElder** [comment]
Perhaps at somepoint we should revisit applying step 2 and so on to existing platforms https://github.com/kubernetes/sig-release/blob/master/release-engineering/platforms/guide.md#step-2-testing

A number of the existing platforms don't appear to be meeting the guidelines.
