### ISSUE TITLE
fail to deploy pod when setting NodeAffinity in yaml 

### ISSUE THREAD

**Issue by hgliu1985** [kubernetes/kubernetes#93624]
Hello everyone, I want to deploy just one pod on a node, I set the NodeAffinity and PodAntiAffinity for the deployment.
However after the deployment finishes,  there are two pods on the node, one is failed, and another one is running.
This is my yaml file as below, 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: &cluster_name him123
  namespace: mynamespace
  labels:
    application: him
    system-name: him
spec:
  replicas: 1
  selector:
    matchLabels:
      application: him
      system-name: him
  template:
    metadata:
      labels:
        application: him
        system-name: him
    spec:
      serviceAccountName: him
  
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node_him
                operator: In
                values:
                - him
                
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: application
                operator: In
                values:
                - him
            topologyKey: "kubernetes.io/hostname"

      containers:
........

I use the following command to add a label for the node
/opt/kube/bin/kubectl label node $node1_ip node_him=him

After the deployment, I check the pod status and find two pod on my node:
kubectl get pods -n mynamespace|grep him
him-6d6d75b869-d7ncb         0/2     NodeAffinity   0          2d20h
him-6d6d75b869-wvdjz         2/2     Running        0          2d20h

We can see there is a pod whose status is NodeAffinity.  What should I do to only let the running pod existing and let the failed pod disappeared?

**Environment**:
kubectl version
"v1.18.2", 
uname -a 
Linux k8s-master1 5.2.6-1.el7.elrepo.x86_64 #1 SMP Sun Aug 4 10:13:32 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

Thanks a lot!

**Comment by damemi** [comment]
Could you give some more info on the pods (like with `kubectl describe <pod>`?) If you're adding the node label after creating the deployment that would explain the affinity failure but I don't know if that causes a 2nd pod to be created

**Comment by hgliu1985** [comment]
@damemi Thanks a lot for your help.Sorry for my late reply, since the pod was removed at that time.

Now the error reproduced again, and I would provide the info as below:
# kubectl get pods -n haishen|grep him
him-5d6c8df69c-rrfck         2/2     Running        0          23h
him-5d6c8df69c-tch7c         0/2     NodeAffinity   0          23h

# kubectl get nodes --show-labels
NAME           STATUS   ROLES    AGE   VERSION   LABELS
172.2.0.16   Ready    master   23h   v1.18.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=172.2.0.16,kubernetes.io/os=linux,kubernetes.io/role=master,**node_him=him**,node_role=manager
172.2.0.17   Ready    master   23h   v1.18.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=172.2.0.17,kubernetes.io/os=linux,kubernetes.io/role=master,node_role=manager
172.2.0.18   Ready    master   23h   v1.18.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=172.2.0.18,kubernetes.io/os=linux,kubernetes.io/role=master,node_role=manager

# kubectl describe pod him-5d6c8df69c-tch7c -n mynamespace
Name:           him-5d6c8df69c-tch7c
Namespace:      mynamespace
Node:           172.2.0.16/
Start Time:     Thu, 13 Aug 2020 11:01:01 +0800
Labels:         application=him
                pod-template-hash=5d6c8df69c
                system-name=him
Annotations:    <none>
Status:         Failed
Reason:         NodeAffinity
Message:        Pod Predicate NodeAffinity failed
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/him-5d6c8df69c
Containers:
  him-daemon:
    Image:      him-daemon:2.0.0.111
    Port:       9091/TCP
    Host Port:  0/TCP
    Environment:
      MY_POD_NAME:    him-5d6c8df69c-tch7c (v1:metadata.name)
      K3S_NODE_TOKEN:  $K3S_NODE_TOKEN
      HOST_IP:          (v1:status.hostIP)
    Mounts:
      /dev/ from host-dev (rw)
      /etc/localtime from localtime (rw)
  
  him:
    Image:        him:2.0.0.151
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /etc/localtime from localtime (rw)
    
Volumes:
.......................
  localtime:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:  File

    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:          <none>


Thanks a lot for your reply.
