### ISSUE TITLE
Remove support for s390x

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#93621]
We still don't have any CI jobs for this architecture, so we should just remove support for it.

It's been close to 2 years since we opened this issue - https://github.com/kubernetes/kubernetes/issues/67721

**Comment by dims** [comment]
cc @bradtopol @estesp

**Comment by skriesch** [comment]
I want to add CI jobs for s390x. I create that with qemu.

**Comment by BenTheElder** [comment]
Is this SIG Arch (seem to be owning policy?) or SIG Testing / Release? (the latter to enact I suppose?)

What release is this targeted at? 
This should be straightforward to fix and I'd assign for sig-testing, but I'm not sure if we're looking to do that actually.

**Comment by cwsolee** [comment]
@BenTheElder Hi Ben, my team start looking at adding s390x test, you probably saw our PR https://github.com/kubernetes-sigs/kind/pull/1705 which is part of that. Or feel free to let me know if we should help with other task.

**Comment by bradtopol** [comment]
Hi @dims Thanks for the heads up!  I believe @cwsolee and her team will start addressing this. Can you help her to navigate the needed KEPs or architectural reviews to be able to proceed with this work?  Thanks!

**Comment by dims** [comment]
@bradtopol @estesp wrote up a WIP to provide guidance - https://github.com/kubernetes/kubernetes/issues/93620

**Comment by cwsolee** [comment]
@dims Thanks, will certainly take a look at that along with what we've been working on.

**Comment by BenTheElder** [comment]
I want to understand more about the proposed guidance here soon, just need to find the time, particularly WRT https://github.com/kubernetes-sigs/kind/pull/1705, I'm not keen on expanding support to cover this in KIND if we're prepared to remove it upstream.

**Comment by dims** [comment]
@bradtopol @estesp i still don't see any movement on this front!

**Comment by cwsolee** [comment]
@dims We are making good progress on all the 3 tests namely Integration, Conformance and E2E. We are running Integration tests for latest 3 release HEAD's on our local Jenkins setups, we are very close to be done and planning to ask how we can publish the results on GCR bucket soon. Could you guide us on publishing the results on GCR or any pointers are welcome? Regarding conformance and E2E tests, we can run the test cases using our own kind-node image, currently we are resolving some Test Case failures that we are observing. We would like to publish these results too once we are ready.

**Comment by dims** [comment]
please see https://github.com/kubernetes/test-infra/tree/master/testgrid/conformance and https://github.com/kubernetes/test-infra/tree/master/testgrid it should have all the info you need for integrating with testgrid, questions, please hop on slack #sig-testing channel.

**Comment by cwsolee** [comment]
Sounds good, thanks @dims

**Comment by cwsolee** [comment]
I'm please to share this link https://testgrid.k8s.io/conformance-s390x#Periodic%20s390x%20conformance%20test%20on%20local%20cluster s390x has been publishing conformance test result there, we're not done, need to add the same for more branches. We're getting close.

**Comment by dims** [comment]
very cool @cwsolee !

**Comment by cwsolee** [comment]
We added other branches(v1.18 & v1.19) along with master, https://k8s-testgrid.appspot.com/conformance-s390x#Summary, we can claim done with adding conformance test for s390x. We will continue to monitor going forward. Let me know if u've any questions.

**Comment by cwsolee** [comment]
We've been monitoring the s390x test result for quite some time now, pretty stable, I think this issue could be closed but it's not removing support for s390x, more along the line of adding conformance test to make sure s390x is stable for anyone to consume.

**Comment by dims** [comment]
thanks @cwsolee 

cc @saschagrunert @hasheddan 

/close
