### ISSUE TITLE
Failing Test: pull-kubernetes-verify - publishing-bot

### ISSUE THREAD

**Issue by knight42** [kubernetes/kubernetes#93623]
**Which jobs are failing**:
pull-kubernetes-verify

**Which test(s) are failing**:
publishing-bot

**Since when has it been failing**:
07-31 12:23 PDT

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-verify

**Reason for failure**:
missing pyyaml module

**Anything else we need to know**:
Running case: verify.publishing-bot 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes 
+++ command: python "hack/make-rules/../../hack/verify-publishing-bot.py" Please install missing pyyaml module and re-run hack/make-rules/../../hack/verify-publishing-bot.py 
+++ exit code: 1 
+++ error: 1

**Comment by liggitt** [comment]
due to python3 bump in test-infra kubekins; being reverted in https://github.com/kubernetes/test-infra/pull/18603

**Comment by liggitt** [comment]
Resolved by test-infra revert
