### ISSUE TITLE
Using standard kubernetes verbs for subresources

### ISSUE THREAD

**Issue by reith** [kubernetes/kubernetes#93634]
It's not obvious to me whether it's good practice to use interfaces defined in `k8s.io/apiserver/pkg/registry/rest` for subresource implementation or not, but it somewhat works. For example there is `NamedCreater` that helps creating subresource and it is documented so. I Also used `Lister` and `Watcher` in my REST implementations; for listing `client-gen` generated client nicely, for `Watcher` it didn't but it was trivial to make such client in expansion. But it doesn't seem RBAC authorizes such subresources access as it does for actual resources, e.g. for both `List` an `Watch` actions, it simply checks `get` permission.
 
**What would you like to be added**:

code-generator may need some small changes. I'm not sure about RBAC changes.

**Why is this needed**:

What I wanted to achieve is to expose some actual resources as subresource to define more granular authorization for them. Assume I have a CRD named `Dog` and I want define roles to read `corev1.Event`s triggered just by `Dog`s (by defining and matching against `corev1.Event.InvolvedObject`. It may have more use-cases.

**Comment by liggitt** [comment]
Subresources don't distinguish between collection and individual access patterns. They're intended to be scoped to a single resource.

**Comment by reith** [comment]
And is architecturally wrong to be able to consider subresource as lists? There may not be many user-cases but at-least it *can* give us more specific authorization and more fine grained APIs by applying filtering like the use-case i mentioned.

**Comment by liggitt** [comment]
All existing servers parse those URLs into fixed verbs today. I would expect very strong evidence this is required (and that different levels of read access to a subresource are valuable) to justify making different versions of API servers disagree on authorization for a given request.
