### ISSUE TITLE
Pod Getting stuck while starting/terminating with error "context deadline exceeded"

### ISSUE THREAD

**Issue by dhineshbabuelango** [kubernetes/kubernetes#93647]
**What happened**:
Most of the kubernetes pod while deploying gets stuck for 10 mins atleast with error context deadline exceeded and the same happens while terminating as well.

**What you expected to happen**:
Pods should be deployed and terminated without getting stuck

**How to reproduce it (as minimally and precisely as possible)**:
Unkonwn

**Anything else we need to know?**:
We have one pod which is using EFS PVC.

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes v1.15.11-eks-908ff6
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Amazon linux
- Kernel (e.g. `uname -a`): Linux ip-100-72-10-73.us-east-1.compute.internal 4.14.181-142.260.amzn2.x86_64 #1 SMP Wed Jun 24 19:07:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Docker
- Network plugin and version (if this is a network-related bug): AWS CNI
- Others:

Error while stopping the container:

**Jul 28 17:32:53 ip-100-72-10-73.us-east-1.compute.internal  kubelet[4876]: E0728 17:32:53.810050    4876 remote_runtime.go:243] StopContainer "5683295e1a4f9cdf236dc9184060869851aa3010f8e45c6ce3181a287314cea8" from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded**

Error while starting the container:

**Aug 03 10:03:35 i ip-100-72-10-73.us-east-1.compute.internal kubelet[4876]: E0803 10:03:35.397256    4876 pod_workers.go:190] Error syncing pod cb26f0d9-f261-44b9-91f4-4c1e705a2164 ("app-1-85fdc6885b-tt42p_test(cb26f0d9-f261-44b9-91f4-4c1e705a2164)"), skipping: rpc error: code = DeadlineExceeded desc = context deadline exceeded**

**Comment by neolit123** [comment]
hello, this seems like a request for support. please try the #kubernetes-users or the other support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
also you could try getting support from AWS EKS.

please re-open this ticket if there is a confirmed core k8s bug.
thanks
/close
