### ISSUE TITLE
[Flaky Test] run_kubectl_apply_tests (ci-kubernetes-integration-master)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93651]
**Which jobs are flaking**:

`integration master (ci-kubernetes-integration-master)`

**Which test(s) are flaking**:

`test-cmd.run_kubectl_apply_tests `

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Reason for failure**:

```
Error from server (NotFound): resources.mygroup.example.com "myobj" not found
```

**Anything else we need to know**:

/sig cli
/cc @kubernetes/ci-signal @soltysh 
/milestone v1.20
/prority important-soon

**Comment by liggitt** [comment]
after creating the CRD, before applying the CR, kubectl should wait until `kubectl api-resources` includes `resources                                      mygroup.example.com`:

https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/test/cmd/apply.sh#L124-L148

**Comment by knight42** [comment]
/assign

@liggitt is this issue related to #65517?

**Comment by liggitt** [comment]
> @liggitt is this issue related to #65517?

no, this is simply kubectl trying to apply a CR before the server has made the API available

**Comment by knight42** [comment]
Got it! and I have filed #93657 to address this issue.

**Comment by liggitt** [comment]
Still happening:

* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1293758433668894720
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1293681678421594115

**Comment by knight42** [comment]
still happening: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1305183184433975296

looks like the root cause is not related to CRD:
```
[32mapply.sh:173: Successful get pods a -n nsb {{.metadata.name}}: a
(B[mpod/b created
pod/a pruned
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
I0913 16:45:10.097725   57734 request.go:645] Throttling request took 1.044904178s, request: GET:http://127.0.0.1:8080/apis/batch/v1beta1?timeout=32s
I0913 16:45:10.448886   57734 shared_informer.go:240] Waiting for caches to sync for garbage collector
I0913 16:45:10.448941   57734 shared_informer.go:247] Caches are synced for garbage collector 
[32mapply.sh:177: Successful get pods b -n nsb {{.metadata.name}}: b
(B[m!!! [0913 16:45:10] Call tree:
!!! [0913 16:45:10]  1: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:47 run_kubectl_apply_tests(...)
!!! [0913 16:45:10]  2: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0913 16:45:10]  3: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:131 juLog(...)
!!! [0913 16:45:10]  4: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:521 record_command(...)
!!! [0913 16:45:10]  5: hack/make-rules/test-cmd.sh:152 runTests(...)
+++ exit code: 1
+++ error: 1
Error when running run_kubectl_apply_tests
Recording: run_kubectl_server_side_apply_tests
Running command: run_kubectl_server_side_apply_tests
```

I think the message `Error from server (NotFound): resources.mygroup.example.com "myobj" not found
` is expected, as the CR was not actually created: https://github.com/kubernetes/kubernetes/blob/3eb90c19d0cf90b756c3e08e32c6495b91e0aeed/test/cmd/apply.sh#L159-L162

/reopen

**Comment by liggitt** [comment]
> I think the message `Error from server (NotFound): resources.mygroup.example.com "myobj" not found ` is expected, as the CR was not actually created:

yes, the actual error is later:

```
[32mapply.sh:177: Successful get pods b -n nsb {{.metadata.name}}: b
(B[m!!! [0913 16:45:10] Call tree:
!!! [0913 16:45:10]  1: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:47 run_kubectl_apply_tests(...)
!!! [0913 16:45:10]  2: /home/prow/go/src/k8s.io/kubernetes/test/cmd/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0913 16:45:10]  3: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:131 juLog(...)
!!! [0913 16:45:10]  4: /home/prow/go/src/k8s.io/kubernetes/test/cmd/legacy-script.sh:521 record_command(...)
!!! [0913 16:45:10]  5: hack/make-rules/test-cmd.sh:152 runTests(...)
+++ exit code: 1
```

Line 177 succeeds, and the next line fails:

https://github.com/kubernetes/kubernetes/blob/660e1e4969ffd8d5e4b24939e646081233e130a6/test/cmd/apply.sh#L176-L180
