### ISSUE TITLE
Kubeadm creates /var/lib/kubelet with 0700 permissions

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#93652]
**What happened**:

The kubeadm `/var/lib/kubelet` dir does not allow non-root read-access per default:
https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/cmd/kubeadm/app/phases/kubelet/config.go#L181-L184

To be able to rely on rootless directories inside this path, it would be nice if we could create the directory with `0755` for example.

**What you expected to happen**:

When bootstrapping the seccomp-operator, we want to create the subdir  `/var/lib/kubelet/seccomp/operator`, which is not owned by root. This allows us to run the operator without root permissions to increase the security of the deployment. This is right now not possible if the cluster got boostrapped with plain kubeadm.

**How to reproduce it (as minimally and precisely as possible)**:

An easy way to reproduce it is to bootstrap a fresh kind cluster and deploy the operator from:
https://raw.githubusercontent.com/kubernetes-sigs/seccomp-operator/181e329/deploy/operator.yaml

We see that the reconciler is not able to access the directory, because the main kubelet path is not accessible at all.

**Anything else we need to know?**:
None
**Environment**:
Latest kind and the linked deployment should already work to reproduce the issue.

**Comment by BenTheElder** [comment]
Aren't the contents of /var/lib/kubelet sensitive? I don't think they should be world-read / execute.

**Comment by liggitt** [comment]
> Aren't the contents of /var/lib/kubelet sensitive?

yes, they definitely are (they include kubelet credentials in /var/lib/kubelet/pki, etc)

**Comment by liggitt** [comment]
I also would not expect manifests and volumes to be world-readable by default

**Comment by liggitt** [comment]
This is not a bug, it is intentional.

A feature request to set a different owner (but not world-readable) could be reasonable, but the current defaults seem reasonable to me.

/remove-kind bug
/kind feature

**Comment by liggitt** [comment]
> When bootstrapping the seccomp-operator, we want to create the subdir `/var/lib/kubelet/seccomp/operator`, which is not owned by root.

Why does the operator need to place files inside the /var/lib/kubelet dir? I would not expect add-on operators to live inside that directory

**Comment by neolit123** [comment]
given `MkdirAll` is a no-op if the directory exists, you could pre-create the directory with the desired permission bits.
admittedly, 755 is the common permission for sub-folders of /var/lib, with a few exceptions including /kubelet, /etcd.

> To be able to rely on rootless directories inside this path, it would be nice if we could create the directory with 0755 for example.

this is a bit odd, because a 755 would still require root to create the operator sub-directory, which means the operator cannot create its location to store state. using something like `/var/lib/some-operator` would require the same pre-step / installation.

if the operator is run as non-root, maybe `/home/some-user/seccomp-operator` is the right place for this?

**Comment by saschagrunert** [comment]
Thank you all for the insights. The main intention was to run the operator without having a need to reconfigure the kubelets seccomp root. So our first step was to create a subdir in `/var/lib/kubelet/seccomp/operator` and chown it to the desired rootless user from an init container. That way the main execution container does not need to run as root U/GID. Profiles would then be namespaced under that directory.

We cannot really know which users are available on the nodes system, so having an init container which creates the directory with the right set of permissions seems a necessary step to me.

In any case, I agree that purely changing the permissions might be the wrong path here and we have to rethink the issue. 😕

/close

**Comment by saschagrunert** [comment]
@liggitt just saw that we require that path from 1.23: https://github.com/kubernetes/kubernetes/commit/ee3c1aeac662c03e6bdbb2d3d0ea4da3e4d0563d#diff-440efa89fc197eb244da0254f14241aaR408

This makes it basically impossible to run a feature on top of seccomp profiles rootless, without running the kubelet rootless (which is not possible right now).

**Comment by liggitt** [comment]
It seems appropriate to either:
* require the same filesystem permissions as the kubelet to install seccomp profiles, or
* use root permissions to explicitly create and grant a different user/group permission to manage seccomp profiles

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/commit/ee3c1aeac662c03e6bdbb2d3d0ea4da3e4d0563d#diff-440efa89fc197eb244da0254f14241aaR408  -- the PR seems to just be moving the flag to config. You can still configure this.
