### ISSUE TITLE
The GID defined by "USER" in Dockerfile does not work in container of Pod 

### ISSUE THREAD

**Issue by HuangShujun** [kubernetes/kubernetes#93666]
**What happened**:   
Use USER 999:999 in Dockerfile to add default uid and gid,   then start the container in Pod , its UID is 999, but its GID is 0.

In container started by Docker the ID is correct
docker run --entrypoint /bin/bash -it abc:latest
bash-5.0$ id
uid=9999 gid=9999 groups=9999

But start as Pod, the gid is 0

kubectl exec -it test /bin/bash
bash-5.0$ id
uid=9999 gid=0(root) groups=0(root)
bash-5.0$

**What you expected to happen**:   the GID of container in Pod should also 999

**How to reproduce it (as minimally and precisely as possible)**:
Dockerfile add "USER 999:999"
Then start the container in Pod

apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: abc
      imagePullPolicy: Never
      command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g: `cat /etc/os-release`): Fedora release 30 (Thirty)

/help

**Comment by neolit123** [comment]
/remove-help
/remove-bug
/triage support

please read here:
> You will see that gid is 3000 which is same as runAsGroup field. If the runAsGroup was omitted the gid would remain as 0(root) and the process will be able to interact with files that are owned by root(0) group and that have the required group permissions for root(0) group.

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

/close

**Comment by neolit123** [comment]
for general support questions please use the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by HuangShujun** [comment]
Actually I still do not get answer . Because the container images already set UID and GID by USER command

**Comment by antoinetran** [comment]
Hi, just to add my two cents. My observation is that indeed, the GID defined in USER is not used, and even though the doc says

```
If this field is omitted, the primary group ID of the containers will be root(0). 
```

This is not true. I omitted this field and the GID used is the primary group of USER. So instead of adding in Dockerfile
```
USER anyuser:anygroup
```
I changed the primary group
```
RUN sudo usermod -g anygroup anyuser
USER anyuser:anygroup
```
Tested with KIND 0.25.0

**Comment by antoinetran** [comment]
Is this the same conclusion you have @HuangShujun after trying the support?
