### ISSUE TITLE
[Flaky Test] [sig-instrumentation] MetricsGrabber should grab all metrics from a ControllerManager (ci-kubernetes-e2e-ubuntu-gce-containerd)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93688]
**Which jobs are flaking**:

` gce-ubuntu-master-containerd (ci-kubernetes-e2e-ubuntu-gce-containerd)`

**Which test(s) are flaking**:

`[sig-instrumentation] MetricsGrabber should grab all metrics from a ControllerManager`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:84
Aug  4 13:49:25.273: Unexpected error:
    <*errors.errorString | 0xc003007c10>: {
        s: "kube-controller-manager pod is not registered. Skipping ControllerManager's metrics gathering",
    }
    kube-controller-manager pod is not registered. Skipping ControllerManager's metrics gathering
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:101
```

**Anything else we need to know**:

/sig instrumentation
/priority important-soon
/cc @kubernetes/ci-signal 
/milestone v1.19

**Comment by hasheddan** [comment]
@kubernetes/sig-instrumentation-misc

**Comment by ehashman** [comment]
@dashpole has looked into this and says this was just one flake out of many months where the controller failed to come up (and hence there were no metrics available), so we are going to close this.

/close

**Comment by hasheddan** [comment]
@dashpole any status update here? Can we bump this to v1.20 milestone?

**Comment by justaugustus** [comment]
Moving this to v1.20
/milestone v1.20

**Comment by dashpole** [comment]
Hmmm... Not able to reproduce yet.
All tests passed...
Will keep running them until they fail.
This was attempt #217
No, seriously... you can probably stop now.
```

**Comment by dashpole** [comment]
I'm thinking the mirror pod for the kube-scheduler may not be registered yet when the test is run.  This test seems to be one of the first ones run in the suite.

From the kubelet logs on the master node:
```
I0910 00:18:43.454321    1454 kubelet.go:1575] Creating a mirror pod for static pod "kube-scheduler-bootstrap-e2e-master_kube-system(1718d5574bcb24a42a2a04a6c343720d)"
...
I0910 00:18:48.459229    1454 kubelet.go:1575] Creating a mirror pod for static pod "kube-controller-manager-bootstrap-e2e-master_kube-system(8c9393a249f27551b8aeccca9549d317)"
```
The kube-scheduler pod is created 1 second before the test looks for it, but it the kube-controller-manager pod is created 3 seconds after the test looks for it.  The kube-scheduler is close enough that I still suspect it may have been missed by the test.

**Comment by dashpole** [comment]
Oh, actually it looks like the real timestamp was before the mirror pod was created:

```
I0910 00:18:45.158] W0910 00:18:41.207660    9455 metrics_grabber.go:98] Can't find kube-scheduler pod. Grabbing metrics from kube-scheduler is disabled.
```

note the 18:41 vs 18:45 timestamps.  So I think it is a race with mirror pod registration

**Comment by dashpole** [comment]
I think the best solution is just to retry.  Giving it an extra minute should reduce flakes.

**Comment by dashpole** [comment]
No flakes for 4 days.
/close
