### ISSUE TITLE
Performance test in 5k scale failed with because of fatal error: runqsteal: runq overflow error

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#93685]
**Which jobs are flaking**:
ci-kubernetes-e2e-gce-scale-performance

**Which test(s) are flaking**:
testing/load/config.yaml

**Testgrid link**:
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-performance

**Reason for failure**:
Kube-apiserver has panicked during 'Delete SVCs' step with  message `fatal error: runqsteal: runq overflow`.

**Anything else we need to know**:

* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1289607229036564481
* gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1289607229036564481/artifacts/gce-scale-cluster-master/kube-apiserver.log-20200802-1596345911.gz

Possibly this flake is related to go1.15. This flake did not happen before.

/sig release-engineering
/sig scalability
/cc @mm4tt

**Comment by jprzychodzen** [comment]
@kubernetes/release-engineering PTAL

**Comment by BenTheElder** [comment]
https://github.com/golang/go/issues/40457

**Comment by BenTheElder** [comment]
There may(?) be an rc2 https://github.com/golang/go/issues/40544#issuecomment-668107314

**Comment by tpepper** [comment]
/priority critical-urgent
Can @kubernetes/sig-scalability-leads affirm whether this should be considered Kubernetes 1.19 release blocking?  It's currently considered a golang 1.15 release blocker, so implicitly it is a Kubernetes 1.19 release blocker.  But if the golang community were to change its stance, what would we do?

**Comment by liggitt** [comment]
This is already fixed in https://github.com/golang/go/commit/6b4dcf19fa493905689dedc27f2232b74c366057 and will be in go1.15 (master is not yet open for go1.16)

**Comment by wojtek-t** [comment]
> Can @kubernetes/sig-scalability-leads affirm whether this should be considered Kubernetes 1.19 release blocking? 

That sounds like non-negligible problem, so I think it should be release blocking.
But given Jordan`s comment above it probably isn't a big problem - thanks Jordan for tracking this!

**Comment by liggitt** [comment]
will be addressed as part of #93484

**Comment by BenTheElder** [comment]
1.15rc2 is out. we're using it in kind and kubetest2
kubernetes will take a bit longer. it's pretty involved still and depends on the golang docker image

**Comment by liggitt** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/93827#issuecomment-671074415
