### ISSUE TITLE
Atomic Writer creates symlink for configmap files before the files are created

### ISSUE THREAD

**Issue by zepatrik** [kubernetes/kubernetes#93686]
**What happened**:

When writing a kubernetes configmap proof file watcher I noticed that symlinks to files are created before the files themselves exist (step 7 in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/atomic_writer.go). This results in an error when the file watcher tries to read the file on it's corresponding CREATE event.

**What you expected to happen**:

The atomic writer should also create files atomically. From my debugging I think it would be enough to move step 7 of the atomic write algorithm after step 9 (the atomic rename), where old symlinks are removed.

**How to reproduce it (as minimally and precisely as possible)**:

Run this test with a count of 1000 https://github.com/ory/x/blob/fix-panic-in-test/watcherx/file_test.go#L161-L173

**Anything else we need to know?**:

In above test I copied the atomic writer and simplified it for the test to only write one file. The algorithm itself is unchanged.

**Environment**:
- Kubernetes version (use `kubectl version`): algorithm according to master
- Cloud provider or hardware configuration: -
- OS (e.g: `cat /etc/os-release`): Arch Linux
- Kernel (e.g. `uname -a`): 5.7.9-1
- Install tools: go version go1.14.5 linux/amd64
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by zepatrik** [comment]
Gonna close as there seems to be no interest in this.

**Comment by ahmetb** [comment]
@zepatrik I believe your code should be watching "user-visible symlink", which is created last. If your inotify call follows symlinks (default behavior) then you only get IN_DELETE_SELF events when the dereferenced file is deleted (and you need to reestablish inotify again by dereferencing user-visible symlink).
