### ISSUE TITLE
fix for https://github.com/kubernetes/kubernetes/issues/68211 not working on 1.18.1 with containerd

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#93691]
**What happened**:
I patched back https://github.com/kubernetes/kubernetes/pull/89629/commits/6c2562a579b2356c54898d262ec578d5fded1e24 to 1.18.1 and while the code applies cleanly the meaning of the variables doesn't correspond directly.

I used dlv to look at the values of mntInfo.Root and subpath.Path at the point in the code corresponding to line 117 of  pkg/volume/util/subpath/subpath_linux.go (line number as seen in the above patch) and I found that mntInfo.Root was a substring of subpath.Path rather than being identical.
```
(dlv) print mntInfo.Root
"/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volumes/kubernetes.io~configmap/setup-script/..2020_07_28_17_28_48.155435548/metricbeat.yml"
(dlv) print subpath.Path
"/var/lib/kubelet/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volumes/kubernetes.io~configmap/setup-script/..2020_07_28_17_28_48.155435548/metricbeat.yml"
(dlv) print subpath
k8s.io/kubernetes/pkg/volume/util/subpath.Subpath {
        VolumeMountIndex: 2,
        Path: "/var/lib/kubelet/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volumes/kubernetes.io~configmap/setup-script/..2020_07_28_17_28_48.155435548/metricbeat.yml",
        VolumeName: "setup-script",
        VolumePath: "/var/lib/kubelet/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volumes/kubernetes.io~configmap/setup-script",
        PodDir: "/var/lib/kubelet/pods/c08168ae-9579-4c9f-a89d-6217337d666b",
        ContainerName: "c-beat-setup",}
(dlv) print mntInfo
k8s.io/kubernetes/vendor/k8s.io/utils/mount.MountInfo {
        ID: 802,
        ParentID: 50,
        Major: 253,
        Minor: 6,
        Root: "/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volumes/kubernetes.io~configmap/setup-script/..2020_07_28_17_28_48.155435548/metricbeat.yml",
        Source: "/dev/mapper/cgts--vg-kubelet--lv",
        MountPoint: "/var/lib/kubelet/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volume-subpaths/setup-script/c-beat-setup/2",
        OptionalFields: []string len: 1, cap: 1, [
                "shared:33",
        ],
        FsType: "ext4",
        MountOptions: []string len: 2, cap: 2, [
                "rw",
                "relatime",
        ],
        SuperOptions: []string len: 2, cap: 2, [
                "rw",
                "data=ordered",
        ],}
```
The relevent /proc/self/mountinfo entries are these, I think:
```
38 0 8:4 / / rw,relatime shared:1 - ext4 /dev/sda4 rw,data=ordered
50 38 253:6 / /var/lib/kubelet rw,relatime shared:33 - ext4 /dev/mapper/cgts--vg-kubelet--lv rw,data=ordered
801 50 253:6 /pods/c08168ae-9579-4c9f-a89d-6217337d666b/volumes/kubernetes.io~configmap/setup-script/..2020_07_28_17_28_48.155435548/metricbeat.yml /var/lib/kubelet/pods/c08168ae-9579-4c9f-a89d-6217337d666b/volume-subpaths/setup-script/c-beat-setup/2 rw,relatime shared:33 - ext4 /dev/mapper/cgts--vg-kubelet--lv rw,data=ordered



```

**What you expected to happen**:
I was hoping to make the fix work with 1.18.1.  I don't know if the difference is due to the version or the fact that I'm using containerd directly rather than using docker.

**How to reproduce it (as minimally and precisely as possible)**:

Cherry-pick https://github.com/kubernetes/kubernetes/pull/89629/commits/6c2562a579b2356c54898d262ec578d5fded1e24 to 1.18.1, build it with debugging enabled, connect a debugger like dlv to the running kubelet, inject a breakpoint in the prepareSubpathTarget() function where the fix is, and compare mntInfo.Root and subpath.Path.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
controller-0:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"archive", BuildDate:"2020-07-28T01:01:55Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: intel x86, nothing funky
- OS (e.g: `cat /etc/os-release`):  CentOS 7
- Kernel (e.g. `uname -a`):  3.10.0-1127.el7.2.tis.x86_64

**Comment by cbf123** [comment]
As a second data point:
(dlv) print mntInfo
k8s.io/kubernetes/vendor/k8s.io/utils/mount.MountInfo {
        ID: 799,
        ParentID: 50,
        Major: 0,
        Minor: 164,
        Root: "/..2020_07_30_18_30_50.335642872/ext-ca.crt",
        Source: "tmpfs",
        MountPoint: "/var/lib/kubelet/pods/bcc46dfe-9fe5-4188-83f0-54cfd0504bc2/volume-subpaths/ext-cacrt/c-beat-setup/5",
        OptionalFields: []string len: 1, cap: 1, [
                "shared:85",
        ],
        FsType: "tmpfs",
        MountOptions: []string len: 2, cap: 2, [
                "rw",
                "relatime",
        ],
        SuperOptions: []string len: 1, cap: 1, ["rw"],}
(dlv) print subpath
k8s.io/kubernetes/pkg/volume/util/subpath.Subpath {
        VolumeMountIndex: 5,
        Path: "/var/lib/kubelet/pods/bcc46dfe-9fe5-4188-83f0-54cfd0504bc2/volumes/kubernetes.io~secret/ext-cacrt/..2020_07_30_18_30_50.335642872/ext-ca.crt",
        VolumeName: "ext-cacrt",
        VolumePath: "/var/lib/kubelet/pods/bcc46dfe-9fe5-4188-83f0-54cfd0504bc2/volumes/kubernetes.io~secret/ext-cacrt",
        PodDir: "/var/lib/kubelet/pods/bcc46dfe-9fe5-4188-83f0-54cfd0504bc2",
        ContainerName: "c-beat-setup",}

relevent /proc/self/mountinfo:
38 0 8:4 / / rw,relatime shared:1 - ext4 /dev/sda4 rw,data=ordered
50 38 253:6 / /var/lib/kubelet rw,relatime shared:33 - ext4 /dev/mapper/cgts--vg-kubelet--lv rw,data=ordered
578 50 0:164 /..2020_07_30_18_30_50.335642872/ext-ca.crt /var/lib/kubelet/pods/bcc46dfe-9fe5-4188-83f0-54cfd0504bc2/volume-subpaths/ext-cacrt/c-beat-setup/5 rw,relatime shared:85 - tmpfs tmpfs rw

**Comment by liggitt** [comment]
does that mean https://github.com/kubernetes/kubernetes/pull/93272 was a flawed cherry-pick?

**Comment by msau42** [comment]
We don't seem to run containerd tests on older releases. Will revert the changes for now until we can do  more testing.

**Comment by cbf123** [comment]
Is there anything I can investigate to help out?  I don't really know this code very well, so I don't know what it's *supposed* to be doing. :)  But I can reproduce the problem and dig up variable contents.

**Comment by cbf123** [comment]
I'm not sure if it should go here or in another separate issue.  I've made a modified version of the patch for  https://github.com/kubernetes/kubernetes/issues/68211 using !strings.Contains(subpath.Path, mntInfo.Root) for the comparison instead of testing for equality.

Even with that though I'm seeing a scenario where sometimes for some containers that use configmap subpaths they're showing as "Terminated" with a reason of "Unknown".  The pod "Events" show a bunch of logs of this form:

  Warning  FailedMount     26m (x18 over 47m)    kubelet, controller-0  MountVolume.SetUp failed for volume "placement-bin" : stat /var/lib/kubelet/pods/433d8822-2755-45c2-9300-cb4a4bd9d16e/volumes/kubernetes.io~configmap/placement-bin: no such file or directory
  Warning  FailedMount     21m                   kubelet, controller-0  Unable to attach or mount volumes: unmounted volumes=[placement-bin], unattached volumes=[placement-bin placement-etc placement-api-token-vshsc pod-tmp wsgi-placement]: timed out waiting for the condition

Interestingly, unlike https://github.com/kubernetes/kubernetes/issues/68211 there are no " Error: failed to start container" logs.

Should I create a new issue or is this really still part of the same problem?

**Comment by msau42** [comment]
Unsure if they're related. I plan to spend some time next week to investigate this further.

**Comment by cbf123** [comment]
Did you happen to get anywhere with this?

**Comment by cbf123** [comment]
Hi...was going through my backlog and noticed this.  Did you ever get anywhere with this?

**Comment by msau42** [comment]
I unfortunately haven't had a chance to look into why it's failing with containerd on 1.18. Have you tried this workaround with projected volumes? https://github.com/kubernetes/kubernetes/issues/68211#issuecomment-625221313

**Comment by cbf123** [comment]
I have not...unfortunately upstream projects like openstack-helm make extensive use of subpath, and it's not reasonable for us to change all of them.
