### ISSUE TITLE
Probe API HTTPHeader with ValueFrom

### ISSUE THREAD

**Issue by yongruilin** [kubernetes/kubernetes#93708]
**What would you like to be added**:
The HTTPHeader [api](https://github.com/kubernetes/api/blob/4859c947397736b7b452bf4564e7b9b231a5b8f7/core/v1/types.go#L2034) only support plaintext. Maybe we can have something like this 
```
// HTTPHeader describes a custom header to be used in HTTP probes
type HTTPHeader struct {
	// The header field name
	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
	// The header field value
	Value string `json:"value" protobuf:"bytes,2,opt,name=value"`
	// Source for the header variable's value. Cannot be used if value is not empty.
	// +optional
	ValueFrom *HTTPHeaderSource `json:"valueFrom,omitempty" protobuf:"bytes,3,opt,name=valueFrom"`
}

type HTTPHeaderSource struct {
	ConfigMapKeyRef *ConfigMapKeySelector `json:"configMapKeyRef,omitempty" protobuf:"bytes,3,opt,name=configMapKeyRef"`
	// +optional
	SecretKeyRef *SecretKeySelector `json:"secretKeyRef,omitempty" protobuf:"bytes,4,opt,name=secretKeyRef"`
}
```
**Why is this needed**:
We are implementing our own probe controller using the probe API. It would be helpful if have a `valueFrom` field added to HTTPHeader so that the controller can get data from the third source like ConfigMaps or Secrets. There is a[ workaround](https://stackoverflow.com/a/60078088/13478684) for livenessProbe by using the env, but adding a `valueFrom` field seems more elegant here.

**Comment by caesarxuchao** [comment]
/sig node
@kubernetes/api-reviewers 
/remove-sig api-machinery

**Comment by ejose19** [comment]
This is really useful, specially if the base image doesn't include `curl` or similar tools to do it using the `exec` way.
