### ISSUE TITLE
Scheduler should log processed component config

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#93718]
**What would you like to be added**:
When setting a non-default component config (especially custom profiles/plugin configurations), the scheduler should at least log what plugins have been enabled at startup.

**Why is this needed**:
Debugging the scheduler almost always requires knowing what plugins are enabled. Usually, it is safe to assume that the default registry is being used but this is obviously not always the case. Logging the plugin configuration would also match the current behavior which logs custom Policy settings:

```
I0805 14:15:30.692300       1 factory.go:232] Creating scheduler from configuration: {{ } [] [{ImageLocalityPriority 1000 <nil>}] [] 0 false}
```

/sig scheduling

**Comment by alculquicondor** [comment]
I would expand it to print the whole configuration.

We print all command line args, so it makes sense.

**Comment by damemi** [comment]
@alculquicondor good point it should print the whole config

**Comment by ahg-g** [comment]
+1 to printing the whole configuration once initialized.

**Comment by alculquicondor** [comment]
Actually, the hardest part of this task is to print the whole plugins configuration, as the determination of the default plugins happen kind of late in the startup sequence.

Can we make an initial PR that just prints the configuration as produced by API defaulting today?

**Comment by alculquicondor** [comment]
/retitle Scheduler should log processed component config

**Comment by damemi** [comment]
@alculquicondor I can pick this back up now if you'd like. Any specific timeline or blockers for this?

**Comment by alculquicondor** [comment]
The only partial blocker is that we don't generate the `.profiles[*].plugins` or `profiles[*].pluginConfig` values until much later after API defaulting.

But having something is better than nothing, which is what we have today :)

**Comment by damemi** [comment]
PR opened here: https://github.com/kubernetes/kubernetes/pull/96426, sorry for the delay
