### ISSUE TITLE
[Flaky Test] [sig-scalability] there should be no high-latency requests (ci-kubernetes-e2e-gci-gce-scalability)

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93716]
**Which jobs are flaking**:

`gce-cos-master-scalability-100 (ci-kubernetes-e2e-gci-gce-scalability)`

**Which test(s) are flaking**:

`testing/density/config.yaml`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

**Reason for failure**:

```
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:nodes Subresource:status Verb:PATCH Scope:cluster Latency:perc50: 29.891304ms, perc90: 86.029411ms, perc99: 1.595833333s Count:390 SlowCount:25}; expected perc99 <= 1s]]
```

**Anything else we need to know**:

This only happened once: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1290904296279248896

/sig scalability
/cc @kubernetes/ci-signal @kubernetes/sig-scalability @wojtek-t 
/milestone v1.19

**Comment by mm4tt** [comment]
This is a flake (unfortunately, our performance tests are flaky) and should not be considered a release blocker

**Comment by hasheddan** [comment]
@mm4tt thanks! I'll bump milestone and indicate not urgent

/milestone v1.20
/priority important-longterm

**Comment by wojtek-t** [comment]
Yeah - we did a bunch do deflake our tests in previous months, but it was mostly focused on 5k-node tests (and they indeed are quite stable now).
But there is a bunch of work in front of us to deflake the smaller ones too (which aren't super bad, but are not where we would like them to be). We will be further looking into those issues.

**Comment by RobertKielty** [comment]
Hi @wojtek-t Hi @mm4tt 

Will you be in a position to look at this flake for 1.20 

Are there higher priority flakes that you would prefer to track?

**Comment by wojtek-t** [comment]
FTR - it seems that many of the issues in the dashboard you linked above are actually the same as this one.

Going back to your original question - we're are already looking into that as we speak. There is another issue opened for pretty much the same issue:
https://github.com/kubernetes/kubernetes/issues/94098

It's clear that partially the problems are due to resource-starvation on master machine, but we are starting to look into other flakes too. We're also reworking our tests a bit that should also reduce flakiness. So yes - this is something we're actively looking at.

**Comment by wojtek-t** [comment]
Looking into this dashboard:
https://testgrid.k8s.io/sig-scalability-gce#gce-cos-master-scalability-100

There were exactly 3 failed runs over the last 2 weeks - all 3 failed on setting up the cluster.

No single test-related flake in the last 2 weeks. I'm closing this one.
/close
