### ISSUE TITLE
Volume expansion request should not reach to CSI driver, if in-tree plugin is not capable of expanding volume

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubernetes#93727]
**What happened**:
When the CSI migration is enabled, Kubernetes is sending a request to expand the volume to CSI even when the in-tree plugin is not supporting the volume resize.

**What you expected to happen**:
When the migration is enabled, Kubernetes should not send a request to expand the volume to CSI when in-tree plugin is not capable of extending volume.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable vSphere CSI Migration.
2. Create PVC with StorageClass having `AllowVolumeExpansion` set to true using provisioner - `kubernetes.io/vsphere-volume`.
3. Resize PVC.
4. expand volume request is reaching to CSI controller.

**Anything else we need to know?**:
We do not have any interface to check this and fail operation at the translation layer.

We can update the logic in Kubernetes to help verify this and stop volume expansion there - https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/expand/expand_controller.go#L258-L293

**Why do we want this?**
If the in-tree plugin is not capable of expanding volume, but CSI driver is capable to expand volume.

We see a race when CSI driver expands the volume, but before the file system is resized, if user disables the migration and move back to the in-tree plugin, file-system of the volume can never be expanded.

also, migration should not be adding new capabilities on migrated volumes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19 rc
- Cloud provider or hardware configuration: vSphere Cloud Provider

cc: @msau42 @xing-yang @SandeepPissay @misterikkit @chethanv28

**Comment by liggitt** [comment]
> Create PVC with StorageClass having AllowVolumeExpansion set to true using provisioner - kubernetes.io/vsphere-volume.

Isn't that a bug in the storage class specification?

**Comment by divyenpatel** [comment]
@liggitt 
Is there a way we can block patching of storage class with `allowVolumeExpansion` if provisioner is `kubernetes.io/vsphere-volume`? If we can do then it will help.

**Comment by liggitt** [comment]
> Is there a way we can block patching of storage class with `allowVolumeExpansion = true` if provisioner is `kubernetes.io/vsphere-volume`?

Validation like that could be added with an admission webhook, if desired. I would not anticipate special-casing storageclass validation for in-tree -> CSI drivers.

**Comment by gnufied** [comment]
I tend to agree with @liggitt here. A Storageclass explicitly provisions only in-tree volumes and even if migration is enabled, the volumes provisioned by it are not expected to magically gain new capabilities and hence there is no fix needed in k8s IMO.

**Comment by divyenpatel** [comment]
code change made here - https://github.com/kubernetes/kubernetes/pull/93738/files is preventing in-tree volumes to gain expand capability via CSI migration. For in-tree plugins that already support volume resize, functionality-wise this change is not breaking anything.

**Comment by gnufied** [comment]
Even if that were the case - IMO the root cause of the problem is, admin should not have enabled expansion for in-tree Storageclass. 

External-resizer should handle unimplemented error and not retry volume expansion. We can file a bug against external-resizer for that. 

Another problem with https://github.com/kubernetes/kubernetes/pull/93738 is, it is making a very subtle change into expansion controller with little/no testing. I am kinda worried merging it in 1.19 without understanding it fully.

**Comment by liggitt** [comment]
> the root cause of the problem is - storageclass had volume expansion as enabled.

I agree. This is a misconfiguration, and it is the responsibility of the storage class creator to accurately describe the CSI driver's capabilities.

**Comment by divyenpatel** [comment]
closing this issue. 

@gnufied as you mentioned in the slack conversation, if we can stop re-try expansion if the driver returns `Unimplemented`, it will work. I will create a bug for external-resizer.

@liggitt we will also explore the option of adding an admission webhook in the vSphere CSI driver to help protect such accidental unsupported changes on the storage class.
