### ISSUE TITLE
Add ability to specify multiple container images for one container for redundancy

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubernetes#93736]
**What would you like to be added**:

Ability to specify more than one container image (container registry) per container in a pod.

**Why is this needed**:

This has probably come up a few times and there are some solutions that improve the redundancy of container images on the server side, but they may seem heavy handed for some users. For example, [Harbor][https://goharbor.io], [Quay][https://quay.io], and [Trow][https://github.com/ContainerSolutions/trow], but what about from Kubernetes itself? K8s allows to you set the `ImagePullPolicy` for containers but that may not be enough for some users either.

Background:

https://stackoverflow.com/questions/63266765/kubernetes-deployment-specify-multiple-options-for-image-pull-as-a-fallback

**Comment by smarterclayton** [comment]
Both containerd and cri-o supports the concept of fallback of known registries or repositories across clusters.  That would be a good place to start, since registry resilience tends to be cluster wide, not just per pod.

**Comment by liggitt** [comment]
Agree a node-level container registry fallback or configuration is a better place for this than plumbing it all the way from the pod through CRI

**Comment by raravena80** [comment]
Perhaps this can be more of a documentation request. i.e recommendations for redundant registries for K8s nodes using containerd/crio-o. Also, including something like don't use the FQDN or unique_id of the registry if you'd like to have redundancy.

Use:

```
myapp:latest
```

as opposed to:

```
gcr.io/mygcpproject/myapp:latest
```
or
```
aws_account_id.dkr.ecr.region.amazonaws.com/myapp:latest

**Comment by dogzzdogzz** [comment]
We just experienced the outage of quay.io registry, it becomes single point of failure for some of our apps in cluster. we have to update the image of manifest to switch to backup registry and redeploy it. So I think it's kind of important feature for HA.
![image](https://user-images.githubusercontent.com/23068316/100253228-cf47bc80-2f7b-11eb-93fa-11330cc8ca9a.png)

**Comment by thejosephstevens** [comment]
I'm guessing I'm not the only person to get hit by the most recent Quay outage. We're actively recovering (shifting to a backup registry), but would be great to see this supported explicitly at the k8s level (specifically in a way that the managed k8s providers will pick up, we don't have the option to customize our nodes in most cases)

![image](https://user-images.githubusercontent.com/5632093/112083638-a8be1a80-8b44-11eb-860a-ae642c7fd2eb.png)

**Comment by bgjoseluis** [comment]
Hello,

I'm also interested in the proposed feature.

Regards
JLBG

**Comment by nurhun** [comment]
Hello,

Any updates here ?

**Comment by violuke** [comment]
We would also like to see this. Can this be reopened?
