### ISSUE TITLE
Api server should report metrics about etcd requests

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#93734]
I'm trying to add a monitor for "api cannot talk to etcd" and the only thing I found was monitoring the metrics etcd emits, which does not cover any network interruptions. Are there metrics for this ? ... if not, are they easy to add ?

**Comment by liggitt** [comment]
The API server includes the ability to communicate with etcd in its health check. You can specifically monitor this at /healthz/etcd

**Comment by grosser** [comment]
Thx, that could be useful to make a custom monitor.
Ideally something like the metric that kubelet provides about its connection to the api server would be nice.
kubelet_docker_operations_errors_total or rest_client_requests_total

**Comment by liggitt** [comment]
cc @logicalhan

**Comment by logicalhan** [comment]
@grosser what kind of setup do you have for your control-plane? Do you have a control-plane kubelet?

**Comment by grosser** [comment]
yes, api server runs as pods / with a kubelet

**Comment by logicalhan** [comment]
You can monitor the kubelet, it'll effectively tell you the same thing. The kublet exposes a `/metrics/probes` path which will tell you the failure counts or something similar (I don't remember the metric format off the top of my head). 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L86

**Comment by grosser** [comment]
from /metrics/probes I only got 
```
prober_probe_total{container="kube-apiserver",namespace="kube-system",pod="kube-apiserver-ip-172-30-224-112.us-west-2.compute.internal",pod_uid="644aabd1eb818fb460339b8dae69d67f",probe_type="Liveness",result="successful"} 4880
```
so not very helpful ... from the /healthz/etc endpoint I only get `ok` so can graph that over time, but some kinda of count / duration metric would be nice to see trouble brewing before it's down

**Comment by logicalhan** [comment]
Is your etcd not managed by the control plane kubelet? (That would be a necessary condition for this)

**Comment by grosser** [comment]
it's on a different host
either way these checks are only "healthy true/false" which I already
covered, I was interested failure rates and request times from api servers
perspective

**Comment by logicalhan** [comment]
It's a counter, so it would actually let you infer the rates.. it's a moot point though since your control plane kubelet isn't monitoring your etcd instance.

**Comment by grosser** [comment]
ahh ok I'd be able to do result=successful over result=failed
but yeah that would be on a different host so no really correlated
