### ISSUE TITLE
HTTP healtz check entrypoints disappear

### ISSUE THREAD

**Issue by ivanvtimofeev** [kubernetes/kubernetes#93746]
**What happened**: 
HTTP healtz check entrypoints (for kube-scheduler pod http://127.0.0.1:10251/healthz and for kube-controller pod  http://127.0.0.1:10252/healthz ) disappear in 1.16.13 version. This led to kubernetes 1.16.13 containers deployed by kubespray fails due to liveness check.

**What you expected to happen**: 
I expect healtz entrypoints will apper back again, and k8s will not fails due to liveness check

**How to reproduce it (as minimally and precisely as possible)**: 
Deploy k8s using kubespray release-2.12 (https://github.com/kubernetes-sigs/kubespray/tree/release-2.12) with default k8s version.

**Anything else we need to know?**: 
—

**Environment**: 
- Kubernetes version 1.16.13
- Cloud provider or hardware configuration: AWS
- OS `cat /etc/os-release`: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel `uname -a`: 
Linux ip-172-31-15-227.eu-west-1.compute.internal 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
kubespray release-2.12 (https://github.com/kubernetes-sigs/kubespray/tree/release-2.12) 
- Network plugin and version (if this is a network-related bug): 
Tungsten Fabric, Calico
- Others:

**Comment by neolit123** [comment]
please log this ticket in the kubespray repository.
the kubespray maintainers should be already aware that kubeadm (used by kubespray) switched to pass --port=0 to the kube-scheduler and kube-controller-manager, which disabled HTTP serving.

your option is to use health checks the secure ports via HTTPS.

/close
/remove-sig api-machinery
/sig cluster-lifecycle
