### ISSUE TITLE
error converting fieldPath: field label not supported: status.podIPs.

### ISSUE THREAD

**Issue by Telzeng** [kubernetes/kubernetes#93741]
Hi,

To support dual stack. Add one env in the pod.
        - name: POD_IPs
          valueFrom: { fieldRef: { fieldPath: status.podIPs } }

created pod on the cluster with kubernetes API server 1.16. met the following error. another cluster with 1.17 work well.
  Warning  FailedCreate      84s (x19 over 23m)  statefulset-controller  create Pod pg-0 in StatefulSet db-pg failed error: Pod "pg-0" is invalid: spec.containers[0].env[10].valueFrom.fieldRef.fieldPath: Invalid value: "status.podIPs": error converting fieldPath: field label not supported: status.podIPs

k8s version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by aojea** [comment]
This is correct, this was added in 1.17 and since is an alpha feature is not going to be backported to 1.16

xref: https://github.com/kubernetes/kubernetes/pull/83123

/close
