### ISSUE TITLE
Kube-Scheduler metrics misleading error message if not authenticated

### ISSUE THREAD

**Issue by FrediWeber** [kubernetes/kubernetes#93748]
**What happened**:
Kube-Scheduler exposes metrics in a secure manner (TLS and authentication required) on port 10259 by default. If one does not authenticate itself, the error message displayed is:
`: no kind is registered for the type v1.Status in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"`

**What you expected to happen**:
Kube-Scheduler should emit a clear and understandable error message if authentication fails. Kube-Controller-Manager does that the following way:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up a Kubernetes Cluster
2. Try to access the exposed metrics endpoint (https://metrics-server:10259/metrics) without authentication

**Anything else we need to know?**:
xref: https://github.com/kubernetes/kubeadm/issues/2244

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6
- Cloud provider or hardware configuration: Bare metal
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 10 (buster)
- Kernel (e.g. `uname -a`): 4.19.0-9-amd64
- Install tools: Kubeadm (Kube-Scheduler `--bind-address 0.0.0.0`)

**Comment by wawa0210** [comment]
If ok, I can try this fix

/assign
