### ISSUE TITLE
output of kubectl certificate deny command says approved instead of denied

### ISSUE THREAD

**Issue by harsha-s** [kubernetes/kubernetes#93755]
**What happened**:
master $ kubectl certificate deny agent-smith
certificatesigningrequest.certificates.k8s.io/agent-smith approved
master $ kubectl get csr
NAME          AGE     REQUESTOR                 CONDITION
agent-smith   4m16s   agent-x                   Denied
akshay        6m26s   kubernetes-admin          Approved,Issued
csr-2ws5g     23m     system:bootstrap:96771a   Approved,Issued
csr-pkhsf     23m     system:node:master        Approved,Issued
master $ kubectl -version

**What you expected to happen**:
certificatesigningrequest.certificates.k8s.io/agent-smith denied

**How to reproduce it (as minimally and precisely as possible)**:
Run kubectl certificate deny for a pending csr request.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
master $ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
master $ uname -a
Linux master 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by knight42** [comment]
dup with #91876

/close
