### ISSUE TITLE
Add admission webhook example

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#93756]
**What would you like to be added**:

Add a skeleton admission webhook that performs a simple admission operation and that can be used as a starting point for developers that need to build their own admission webhooks.

**Why is this needed**:

It is not obvious how to construct how to construct a skeleton admission webhook. Providing an example that applies best practices would be valuable to the community.

/sig api-machinery
/cc @liggitt 
/assign

**Comment by jpbetz** [comment]
xref https://github.com/kubernetes/kubernetes/issues/93416

**Comment by caesarxuchao** [comment]
Let's take a look at what kubebuilder does, probably there is already a good example.

**Comment by adeniyistephen** [comment]
@jpbetz @liggitt Hi, I would really love to work on this, please kindly provide input and pointers for the documentation. Thanks
