### ISSUE TITLE
scheduler_perf: support multiple node labelling strategies

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93760]
**What would you like to be added**: `scheduling_perf_test.go` only supports one node labelling strategy currently. However, I don't see any reason why multiple node labelling strategies cannot be supported at the same time. Solving overlapping labels from different strategies would be an interesting problem to solve; we could simply catch these at config parse time and fail immediately.

**Why is this needed**: If I want to set a unique hostname using `UniqueNodeLabelStrategy` and also label nodes with three zones using `LabelNodePrepareStrategy`, I can't currently do this.

/sig scheduling
/sig testing
/kind feature
/cc @alculquicondor

**Comment by adtac** [comment]
Perhaps the user could specify an ordered list of node labelling strategies and the testing framework will patch nodes with one strategy after another?

**Comment by alculquicondor** [comment]
sg, but let's defer until the ongoing refactoring is finalized. Also, provided that we already have a testcase we can not write with the current templates.

**Comment by adtac** [comment]
Yeah, agreed, I don't have plans to add features to the in-tree framework anymore; only bug fixes (like the MixedScheduling PR).
