### ISSUE TITLE
Incorrect comment in runtime ObjectKind interface

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#93775]
The statement "returns [...], or nil" cannot be true since the return type is a struct:

https://github.com/kubernetes/kubernetes/blob/97c5f1f7632f2d349303515830be76f6c1084b19/staging/src/k8s.io/apimachinery/pkg/runtime/schema/interfaces.go#L26-L28

https://github.com/kubernetes/kubernetes/blob/97c5f1f7632f2d349303515830be76f6c1084b19/staging/src/k8s.io/apimachinery/pkg/runtime/schema/group_version.go#L142-L146

Suggest it could say ", or an empty struct if ..."

/sig api-machinery

**Comment by SataQiu** [comment]
@bboreham  I can file a PR to fix the incorrect comment if you don't mind :)

**Comment by bboreham** [comment]
Sure, I didn't get round to it yet.
