### ISSUE TITLE
kubelet panic with fatal error: concurrent map writes

### ISSUE THREAD

**Issue by zhiweiv** [kubernetes/kubernetes#93771]
**What happened**:
Windows kubelet panic occasionally on nodes which have high volume of pods run and delete.
```
fatal error: concurrent map writes

goroutine 13660836 [running]:
runtime.throw(0x40932d0, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x79 fp=0xc00274b7c0 sp=0xc00274b790 pc=0x4334a9
runtime.mapassign_faststr(0x3772920, 0xc00084b0b0, 0xc002d2edc0, 0x40, 0xc000da0480)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x41e fp=0xc00274b828 sp=0xc00274b7c0 pc=0x41450e
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).CreateContainer(0xc00091c0b0, 0x4790180, 0xc00263eb70, 0xc00263eba0, 0xc00091c0b0, 0xc00263eb70, 0xc000c2fa80)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_container.go:186 +0xae9 fp=0xc00274ba20 sp=0xc00274b828 pc=0x311e199
```
Full logs:
[kubelet.err.log.zip](https://github.com/kubernetes/kubernetes/files/5040144/kubelet.err.log.zip)

Preliminary investigate result: https://github.com/Azure/AKS/issues/1765#issuecomment-670382606

**How to reproduce it (as minimally and precisely as possible)**:
Run high volume of pods and delete them when they completed in Windows nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.7
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`): 10.0.17763.1282

**Comment by knight42** [comment]
/assign

I would like to give this a shot.

**Comment by knight42** [comment]
/remove-sig windows
I think this is not a window specific problem.

/sig node
/area kubelet

**Comment by knight42** [comment]
@zhiweiv Hi! Thanks for your report, I have filed #93773 to address this issue.

**Comment by zhiweiv** [comment]
@knight42 
This issue is a bit urgent for our situation, it occurs every few days in production clusters. Seems the PR is pending a few days, is it possible to increase the priority to merge it trunk and 1.17/1.18 branch?

Thanks

**Comment by knight42** [comment]
@zhiweiv I understand how urgent this issue is, but I am not privileged to do anything further :(

**Comment by zhiweiv** [comment]
@andyzhangx 
Do you know anyone who can help?

**Comment by andyzhangx** [comment]
> @andyzhangx
> Do you know anyone who can help?

@zhiweiv looks like a simple fix, add a lock for `containerCleanupInfos`, I could help.

**Comment by zhiweiv** [comment]
@andyzhangx 
There is already a fix by @knight42 , the problem is the PR is pending, not sure if you or someone can  increase the priority to merge it trunk and 1.17/1.18 branch

**Comment by zhiweiv** [comment]
Thanks guys.
