### ISSUE TITLE
kubectl drain uses 200% cpu.

### ISSUE THREAD

**Issue by fcantournet** [kubernetes/kubernetes#93784]
Running : 
```
kubectl drain node/XXX --force=true --delete-local-data=true --ignore-daemonsets
```
cpu usage goes to 2 cores @ 100%

**What you expected to happen**:
Way lower cpu usage.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):  Linux felix-Latitude-7490 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rikatz** [comment]
Hey @fcantournet 

I just did not understood, the cpu goes to 200% in the node or in the place where kubectl is running?

Thanks!

**Comment by fcantournet** [comment]
On my laptop running kubectl

**Comment by CostelLupoaie** [comment]
Same issue on mac:
`kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`


`PID    COMMAND          %CPU  TIME     #TH  #WQ #PORTS MEM   PURG CMPRS PGRP  PPID  STATE    BOOSTS %CPU_ME %CPU_OTHRS UID        FAULTS    COW  MSGSENT  MSGRECV  SYSBSD    SYSMACH   CSW       PAGEINS IDLEW   POWER INSTRS      CYCLES     USER           #MREGS RPRVT VPRVT VSIZE KPRVT KSHRD
18701  kubectl          100.5 03:30.41 32/1 0   43     16M   0B   0B    18701 1322  running  *0[1]  0.00000 0.00000    2068790767 11698     274  36       16       56213+    117       229085+   3730    266+    100.5 14465199753 4270601867 costel.lupoaie N/A    N/A   N/A   N/A   N/A   N/A`

I noticed the problem after upgrade from 1.15. Maybe it't not kubectl itself but the way it communicates with external auth provider like IAM in my case.

**Comment by rikatz** [comment]
oh I see. Thanks @CostelLupoaie 

I've no access to cloud providers right now to test, but as you've provisioned in EKS using IAM and @fcantournet is using GKE it MIGHT be a thing.

Will see if someone else have access to cloud providers and can test this :)

**Comment by CostelLupoaie** [comment]
Maybe I am wrong and it's just some busy waiting. In my case I noticed it when draining nodes with many pods that cannot immediately be stopped because it would break the deployments maxUnavailable limits, so kubectl has to wait until it can stop all the pods on the draining node.

**Comment by fcantournet** [comment]
In my case also this was triggered when pods couldn't be evicted immediately because of a violation of pdb.

**Comment by CostelLupoaie** [comment]
`kubectl rollout status deployment` does not lead to high cpu usage in my case, so I suspect it has nothing to do with IAM/GKE auth, but with evictions failing because of pdb (but I am not experienced enough to know kubectl works in the background).

**Comment by adamtulinius** [comment]
I can confirm 100% (not 200%) CPU core usage for each `kubectl drain` process.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ nixos-version
20.03.git.6ec10fc77e5 (Markhor)
```

Currently I'm draining four nodes in parallel (4x `kubectl drain ${host} --delete-local-data`), all four are waiting due to PDB's, and all are at 100% CPU most of the time.

I'll try with a newer kubectl next time.

**Comment by rikatz** [comment]
OK, so it seems to be related to PDB and Drain. I'll try to take a look into it, try to reproduce with the last supported clients.

Thank you for reportint!

/assign

**Comment by adamtulinius** [comment]
> OK, so it seems to be related to PDB and Drain. I'll try to take a look into it, try to reproduce with the last supported clients.
> 
> Thank you for reportint!

Thanks for looking into it!

And my apologies, I forgot to comment on this before:

> I've no access to cloud providers right now to test, but as you've provisioned in EKS using IAM and @fcantournet is using GKE it MIGHT be a thing.

Our cluster is deployed on bare metal on premise, so it's probably not EKS og GKE related.

**Comment by rikatz** [comment]
Is that possible you try draining with "disable-eviction" just to make sure PDB or eviction control is causing this?

Thanks!

**Comment by adamtulinius** [comment]
> Is that possible you try draining with "disable-eviction" just to make sure PDB or eviction control is causing this?

I found a newer kubectl lying around, so it's now v1.18.8 (1.17 didn't include `--disable-eviction` it seems)
```
$ /nix/store/n6iv8l1wfk14drm556nyql8y2qmybank-kubernetes-1.18.8/bin/kubectl version     
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

I couldn't test on the same cluster, but I just drained a host from our staging env with a similar amount of pods to what we run in prod (~85 vs ~100), and _I think you're right_. CPU usage certainly didn't go above 20% at any point on any core, and that's basically background noise on this host.

**Comment by rikatz** [comment]
So my theory here is that kubectl keeps waiting for the node to drain and this is causing a high CPU usage. I'm also creating a cluster here to reproduce the behavior, and see what part of the code is this being caused

**Comment by rikatz** [comment]
Confirmed here  :) Even in last kubectl v1.19.2 the problem happens. It seems also it's putting some pressure in API Server because of the amount of nodes vs PDB.

disable-eviction is a "workaround" not desired if using PDB

/remove-priority awaiting-more-evidence
/priority important-soon

**Comment by rikatz** [comment]
I'm hitting my head in the wall here trying to figure out why the goroutine causes the peak of CPU usage, so anyone with better skills then me in Go, feel free to join :)

https://github.com/kubernetes/kubernetes/blob/v1.19.2/staging/src/k8s.io/kubectl/pkg/drain/drain.go#L244 is the function taking the whole CPU apparently

Will keep digging what part of this function is taking the whole CPU. When removing the [goroutine](https://github.com/kubernetes/kubernetes/blob/v1.19.2/staging/src/k8s.io/kubectl/pkg/drain/drain.go#L256) and making this 'serial' it seems to keep the CPU in low usage but I don't know if this is the desired scenario, as draining a node could take much longer since other Pods may not be using PDB.
