### ISSUE TITLE
[Flaky Test] [sig-scheduling] LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied. [Conformance]

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93782]
**Which jobs are flaking**:

`kind-ipv6-master-parallel (ci-kubernetes-kind-ipv6-e2e-parallel)`

**Which test(s) are flaking**:

`[sig-scheduling] LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied. [Conformance]`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel

**Reason for failure**:

```
Pod "pfpod2" is invalid: [spec.containers[0].resources.requests: Invalid value: "600m": must be less than or equal to cpu limit, spec.containers[0].resources.requests: Invalid value: "600Gi": must be less than or equal to ephemeral-storage limit, spec.containers[0].resources.requests: Invalid value: "600Mi": must be less than or equal to memory limit]
```

**Anything else we need to know**:

/sig scheduling
/priority critical-urgent
/cc @kubernetes/ci-signal @ahg-g @Huang-Wei 
/milestone v1.19

This test waits for the limit range to be deleted before attempting to create the `Pod` so this error is surprising. It appears there are no limit ranges present when they are listed here: https://github.com/kubernetes/kubernetes/blob/97c5f1f7632f2d349303515830be76f6c1084b19/test/e2e/scheduling/limit_range.go#L220

**Comment by Huang-Wei** [comment]
It seems this job failed just once since Jul 23, so I'm wondering is it a must for 1.19?

**Comment by hasheddan** [comment]
@Huang-Wei Given this is a conformance test I would prefer we at least know what is causing the issue

**Comment by BenTheElder** [comment]
This is still flaking with this same issue.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94723/pull-kubernetes-conformance-kind-ga-only-parallel/1304613935629996033

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=LimitRange#6135c3792f44a8ec7317

/reopen

**Comment by s-ito-ts** [comment]
This issue has not occurred recently and seems to have already been fixed.
I think we can close this issue.

**Comment by Huang-Wei** [comment]
Yes, #95807 was expected to get it fixed.

/close

**Comment by BenTheElder** [comment]
this is still flaking in the 1.20 branch : confused : https://github.com/kubernetes/kubernetes/pull/98462 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98462/pull-kubernetes-e2e-kind/1354606943389356032 as of one hour ago
