### ISSUE TITLE
Inability to create pods creates a snowball effect in Kubernetes cronjobs

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kubernetes#93783]
**What happened**:
A misbehaving webhook causes Kubernetes to "snowball" CronJob-related Jobs and pods.

During this time, Kubernetes seemingly **ignores** the HistoryLimit and concurrencyPolicy directives in a CronJob.

**What you expected to happen**:
Kubernetes to respect CronJob settings and values even if there's a misbehaving webhook or some other scheduling problem.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure how easy it would be to reproduce, short of installing the same webhook we did and see this problem occurs for you too.

**Anything else we need to know?**:
Write up, and thoughts: https://blenderfox.com/2020/08/07/the-snowball-effect-in-kubernetes/

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GKE
- OS (e.g: `cat /etc/os-release`):
Linux (Ubuntu)
- Kernel (e.g. `uname -a`):
5.3.0-64
- Install tools:
Helm, Terraform
- Network plugin and version (if this is a network-related bug):
GKE
- Others:

**Comment by liggitt** [comment]
cc @kubernetes/sig-apps-bugs

**Comment by liggitt** [comment]
Based on the description, this is not specific to webhooks but could occur when any admission plugin (like resourcequota) prevents creation of pods for a job

**Comment by huang-jy** [comment]
Possible, but I haven't tested anything using resourcequota. But then again, if resourcequota was rejecting the pod, it should show up on the events entries on the job and/or cronjob object; and the pod creation would be rejected outright, and not delayed.

The snowball effect happens when the pod creation takes longer than normal, and it is this delay that seemingly causes these problems.
