### ISSUE TITLE
test/integration/framework/perf_utils.go: refactor CleanupNodes to only delete nodes created by itself

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93794]
**What would you like to be added**: `CleanupNodes` currently enlists all nodes and deletes *all* of them. This is unintuitive as each node preparer should probably only cleanup the nodes it created.

/sig scheduling
/sig testing
/assign

**Comment by sanposhiho** [comment]
Hi @Jerry-Ge.
Are you still going to work on this issue?

**Comment by Jerry-Ge** [comment]
@sanposhiho Hi~, i am currently working on something else. please go ahead and work on this~ thanks😊

**Comment by sanposhiho** [comment]
Thanks :)  
/assign

**Comment by sanposhiho** [comment]
/remove-lifecycle stale
do it after #101854 merged

**Comment by sanposhiho** [comment]
/reopen
/remove-lifecycle rotten

Still valid
