### ISSUE TITLE
new scheduler_perf framework: add a sleep timer op

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93793]
Note: this issue should be viewed in the context of #93252.

**What would you like to be added**: Currently we support three types of ops: `CreateNodes`, `CreatePods`, `Barrier`. This issue proposes adding a `Sleep` op that would simulate user action by causing the main thread to sleep. Note: I don't have a use-case for this in mind, but one can come up with trivial and contrived examples easily.

**Why is this needed**: Not clear at this time. This is just an open discussion where others can chime in with whether this will be useful.

/sig scheduling
/sig testing

(Not assigning myself until we can figure out if/how we want this.)

**Comment by ahg-g** [comment]
when you get a chance, can you group all enhancements issues relate to the new benchmark framework under one issue with a task list.

**Comment by adtac** [comment]
@ahg-g see https://github.com/kubernetes/kubernetes/issues/94285.

**Comment by sanposhiho** [comment]
I'd like to take this one
/assign

**Comment by oomichi** [comment]
There is still an active pull request for this issue.

/remove-lifecycle rotten
/reopen
