### ISSUE TITLE
new scheduler_perf framework: allow users to specify default pod and node specs

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#93792]
Note: this issue should be viewed in the context of https://github.com/kubernetes/kubernetes/pull/93252.

**What would you like to be added**: Each workload currently requires the user to specify the node/pod specs explicitly. While this is sometimes useful in certain workloads, for around half the workloads, all benchmarks use the same pod and node specs across all `CreateNodes` and `CreatePods` ops. It'd be nice to specify these exactly once at the head of the testCase.

**Why is this needed**: Reduce config toil.

**Comment by sanposhiho** [comment]
Hello, I'd like to take this issue
/assign

**Comment by kapiljain1989** [comment]
I want to understand about this task, what we want to achieve?

**Comment by kapiljain1989** [comment]
@adtac Could you please help me in this, Just little brief what we want to do in this?

**Comment by sanposhiho** [comment]
@kapiljain1989 

This issue will be finished in https://github.com/kubernetes/kubernetes/pull/101799.

**Comment by kapiljain1989** [comment]
@sanposhiho Thank you for the update and also it help me to understood what we wanna achieve in this task :)
