### ISSUE TITLE
Prestop hook are not being triggered when container in the pod gets restarted

### ISSUE THREAD

**Issue by kopal2212** [kubernetes/kubernetes#93818]
**Usecase:** We want a file to be exported to S3 if the container running in pod gets restarted due to OOM error, so we are passing a script in pre stop hook to achieve it, But we are unable to achieve it since pre stop hook is not being triggered.

**What happened**:
_**Scenario 1:**_ when a pod is deleted manually using kubectl delete or using liveness probe, _the pre-stop hook is being triggered_ and file is getting exported to S3.
_**Scenario 2:**_ When making any change in the YAML file of the pod(eg. changing the container image) the container restarts and the _pre-stop hook is being triggered._
**### BUT,**
_**Scenario 3:**_ when a container running in pod gets restarted due to some resource shortage( as in it goes to CrashLoopBackOff state and then restart itself) the pre-stop hooks are not being triggered.

**What you expected to happen**:
We want pre stop hooks to be triggered even when the container in pod restarts due to a shortage of resources(or OOM) or when all processes running in the container are killed, and container restarts.

**Anything else we need to know?**:

****Do let us know if its a bug?**** because in documentation we can't see any clarity.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): linux

-------testfile.yaml-----------------
apiVersion: v1
kind: Pod
metadata:
  name: test-hook
spec:
  containers:
  - image: nginx
    name: test-container
    lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "/bin/pre-stop.sh"]
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory

**Comment by kopal2212** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by Zheaoli** [comment]
Actually I don't think we should support this issue

Here's the detail

**CrashLoopBackOff** means one thing, that container is in an health status. It's not a usual status in Pod's lifecycle, so I think that is right to do not to execute the pre-stop hook during the pod recovery process.

@kopal2212

**Comment by tan31989** [comment]
@Zheaoli how can we still get some mechanism to maybe restart the pod/container on CrashLoopBackOff ?

**Comment by Zheaoli** [comment]
@tan31989 CrashBackOff means one thing that the pod on node got some problems. So if we can find the root cause whether the memory limit , image error or something else, and solve it, the pod will restart/re-pull up - automatically

**Comment by tan31989** [comment]
@Zheaoli Thank you for the update. But while we look for a OOO issue, sometimes to even debug and fix, we may need to take a heap dump on container going down. So, was wondering if this could be highlighted.

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.14

please try to reproduce this with a version of Kubernetes that is 1.17+.
(older versions are out of support and we usually close similar tickets).

/remove-sig cluster-lifecycle
/sig node

**Comment by Chanpreet08** [comment]
K8 gives SIGTERM signal if it wants to terminate the pod, but in case of OOM, it passes SIGKILL to the pod which instantly kills the main process and finally terminates the pod without waiting for the prestop to execute.  So in case of OOM, the prestop won;t execute.

Please follow the raised issue https://github.com/kubernetes/kubernetes/issues/40157
