### ISSUE TITLE
Log streaming disconnects after a while

### ISSUE THREAD

**Issue by thatguyjono94** [kubernetes/kubernetes#93819]
**What happened**:
Running `kubectl --context minikube logs --since=3s -f api-5684fc7b49-49jlt -c api --namespace kludge` to get live logs disconnects unpredictably between 6 - 10 hours usually. 

**What you expected to happen**:
It should never disconnect until instructed. I'm running my cluster in a minikube environment. 
**How to reproduce it (as minimally and precisely as possible)**:
Running live logging command on your pod with at least one container.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
macOS Catalina Version 10.15.5
- Kernel (e.g. `uname -a`):
```
Darwin Jonathans-MBP.hub 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

**Comment by thatguyjono94** [comment]
When I ran this command individually it ran for 10 hrs before disconnecting (no message was given after dc). I still don't know what causes the underlying issue. Based on my research it could be the following:

Apparently log rotation disconnects log streaming (kubernetes/kubernetes#28369). I'm not sure though if it's something that's being done by default in a minikube environment.

There still could be something that skaffold does that interrupts log streaming as I had skaffold running in the background. Maybe it could be a non related rebuild from a mutually exclusive pod that interrupts the log stream.

I have an nginx ingress controller running but based on very different disconnect times I don't think it's a timeout issue coming from this end.

Could just be my operating system, I'm always using 14/16g's of ram, maybe it disconnects long running processes? Although I don't know enough about this to conclude anything.

**Comment by liggitt** [comment]
> It should never disconnect until instructed.

That is not what I would expect. The API server and kubelet have timeouts associated that ensure all connections are eventually closed. Multiple hours is actually longer than I would have expected the connection to remain open (1-2 hours would have been my guess)

**Comment by thatguyjono94** [comment]
@liggitt thanks for the response. A command like `kubectl exec` has a request timeout flag which can be set to never expire. Although `kubectl logs` doesn't. The issue I guess for me is that when I'm developing locally, after a while I don't get my http request logs as the stream closes. And I need to re-establish the connection. Is this expected behavior and is `kubectl logs` with the `follow` flag expected to eventually close? Thank-you.

**Comment by liggitt** [comment]
> A command like kubectl exec has a request timeout flag which can be set to never expire

Regardless of what the client-side timeout is set to, a server side timeout always governs. 

> I need to re-establish the connection. Is this expected behavior and is kubectl logs with the follow flag expected to eventually close?

Yes, clients need to be prepared to reestablish dropped connections.

**Comment by thatguyjono94** [comment]
@liggitt is there a way to set these server timeouts?

**Comment by liggitt** [comment]
no, it looks like that is fixed in the kubelet:

https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/kubelet/server/server.go#L150
