### ISSUE TITLE
merge `NodeUnschedulable` with `TaintToleration` filter plugin together

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#93828]
**What would you like to be added**:
`TaintToleration` is a plugin that checks if a pod tolerates a node's taints
`NodeUnschedulable` is plugin which check if the pod tolerates one specific taint `node.kubernetes.io/unschedulable` and the implied impact for the taint of `node.Spec.Unschedulable`.

`TaintToleration` could cover all the usecases of `NodeUnschedulable` well (some tweak might be needed around `node.Spec.Unschedulable`), there is no need to maintain two plugins for the same purpose.

**Why is this needed**:
Reduce  the filter plugins that need to be maintained by scheduling.

**Comment by draveness** [comment]
`node.Spec.Unschedulable` was supposed to be deprecated, but we can't remove it from the node unless we have a new major API version. https://github.com/kubernetes/kubernetes/issues/69010

I think should keep the `NodeUnschedulable` plugin until the API version bumped to v2 (not in the near future IMO)

**Comment by alculquicondor** [comment]
I agree with @draveness 

Keeping them separate would allow us to remove the unneeded one once the time comes.

**Comment by Huang-Wei** [comment]
@draveness 's point is fair. This can only be done with a v2 node API.

**Comment by chendave** [comment]
thanks all for your feedback!

/close
