### ISSUE TITLE
[Flaky Test] verify.govet passes entire source tree resulting in high memory usage

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#93822]
**Which jobs are flaking**:

`pull-kubernetes-verify`

**Which test(s) are flaking**:

`verify.govet`

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-verify

**Reason for failure**:

Test is passing the entire source tree causing the OOM exceptions due to new limits placed on job in https://github.com/kubernetes/test-infra/pull/18610

```
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
make[1]: *** [Makefile:399: vet] Error 1
```

**Anything else we need to know**:

/priority important-soon
/sig testing
/cc @kubernetes/ci-signal @liggitt

**Comment by liggitt** [comment]
We could experiment with passing one file, one package, or a fixed number of packages at a time to see if there's a good balance between speed and memory consumption

**Comment by liggitt** [comment]
something like `xargs -L 100 go vet ...` could be useful for bounding what we make vet deal with at once

**Comment by hasheddan** [comment]
@liggitt SGTM!

/assign

**Comment by BenTheElder** [comment]
I think @dims is also looking at combining these checks under golangci-lint, something to keep in mind.

**Comment by liggitt** [comment]
yeah, though it's not clear golangci-lint can accomodate all our oddities:
* running subsets of checks (we only run a handful of staticcheck tests)
* exempting some packages from some failures (e.g. our tolerated lint failures)

**Comment by BenTheElder** [comment]
- you can certainly at least exclude subsets of failure codes

- one option is moving the "known failures" toleration to lint ignore
comments in the source ...

**Comment by hasheddan** [comment]
Investigating this further with @liggitt:

This [failed run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93927/pull-kubernetes-verify/1293534074085838848) fails due to `No space left on device`. It looks like the Go cache is using an `emptyDir` volume mount, which should not be constrained except by the disks of the actual node.

```json
{
   "name":"code",
   "emptyDir":{}
}
...
volumeMounts":[
   {
      "name":"logs",
      "mountPath":"/logs"
   },
   {
      "name":"code",
      "mountPath":"/home/prow/go"
   },
   {
      "name":"clonerefs-tmp",
      "mountPath":"/tmp"
   }
],
```

@spiffxp @BenTheElder is it possible that the disks on CI nodes are out of space?

**Comment by BenTheElder** [comment]
It's entirely possible, though I'd expect it to be transient.
