### ISSUE TITLE
Back-off restarting failed container

### ISSUE THREAD

**Issue by manjeetsorout** [kubernetes/kubernetes#93826]
**What happened**:
Back-off restarting failed container
**What you expected to happen**:
message "Back-off restarting failed container" shouldn't in the Events message

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
kubectl describe pods wordpress-5bbd7fd785-p4s9r:

Name: wordpress-5bbd7fd785-p4s9r
Namespace: default
Priority: 0
Node: manjeet-vostro-3558/192.168.43.166
Start Time: Sat, 08 Aug 2020 14:20:27 +0530
Labels: app=wordpress
pod-template-hash=5bbd7fd785
tier=frontend
Annotations: cni.projectcalico.org/podIP: 192.168.62.234/32
Status: Running
IP: 192.168.62.234
IPs:
IP: 192.168.62.234
Controlled By: ReplicaSet/wordpress-5bbd7fd785
Containers:
wordpress:
Container ID: docker://e5554cdd33621c05341ca5b6bd05c526ad9187e3b5afc7253d06d0c305c53aa9
Image: wordpress:4.8-apache
Image ID: docker-pullable://wordpress@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845
Port: 80/TCP
Host Port: 0/TCP
State: Running
Started: Sun, 09 Aug 2020 12:17:29 +0530
Last State: Terminated
Reason: Error
Exit Code: 1
Started: Sun, 09 Aug 2020 12:12:19 +0530
Finished: Sun, 09 Aug 2020 12:16:06 +0530
Ready: True
Restart Count: 19
Environment:
WORDPRESS_DB_HOST: wordpress-mysql
WORDPRESS_DB_PASSWORD: <set to the key 'password' in secret 'mysql-pass-c57bb4t7mf'> Optional: false
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from default-token-b9vtd (ro)
/var/www/html from wordpress-persistent-storage (rw)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady True
PodScheduled True
Volumes:
wordpress-persistent-storage:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: wp-pv-claim
ReadOnly: false
default-token-b9vtd:
Type: Secret (a volume populated by a Secret)
SecretName: default-token-b9vtd
Optional: false
QoS Class: BestEffort
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:
Type Reason Age From Message

Normal Pulled 13h (x8 over 22h) kubelet, manjeet-vostro-3558 Container image "wordpress:4.8-apache" already present on machine
Normal Created 13h (x8 over 22h) kubelet, manjeet-vostro-3558 Created container wordpress
Normal Started 13h (x8 over 22h) kubelet, manjeet-vostro-3558 Started container wordpress
Warning BackOff 15m (x110 over 22h) kubelet, manjeet-vostro-3558 Back-off restarting failed container
**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
This is working as intended, surfacing the fact that the container has restarted many times, and that the kubelet is no longer restarting it as aggressively/quickly. The next recommended action is to view container logs to determine the cause for the restart.
