### ISSUE TITLE
Wrong resourceName of metrics server api object in code-gen fail fake clientset

### ISSUE THREAD

**Issue by secret104278** [kubernetes/kubernetes#93853]
**What happened**:
`+resourceName` of `NodeMetricsList` and `PodMetrics` in `k8s.io/metrics` are set to `nodes` and `pods` respectively in codegen comments. For example, this makes generated fake client to use `nodes` as gvr to query, but the actually gvr should be `nodemetricses`, so `List()`/`Get()`/`Watch()` will always return not found. 

**What you expected to happen**:
`+resourceName` should be `nodemetricses` and `podmetricses`

**How to reproduce it (as minimally and precisely as possible)**:
```go
package main

import (
	"fmt"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metricsv1beta1 "k8s.io/metrics/pkg/apis/metrics/v1beta1"

	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/metrics/pkg/client/clientset/versioned/fake"
)

func main() {
	fakeClient := fake.NewSimpleClientset(&metricsv1beta1.NodeMetrics{
		ObjectMeta: metav1.ObjectMeta{Name: "machine1"},
		Usage: v1.ResourceList{
			v1.ResourceCPU:    resource.MustParse("100m"),
			v1.ResourceMemory: resource.MustParse("1Gi"),
		},
	})
	fmt.Println(fakeClient.MetricsV1beta1().NodeMetricses().List(metav1.ListOptions{})) // &NodeMetricsList{ListMeta:{   <nil>},Items:[]NodeMetrics{},} <nil>
}

```

If you change `$GOPATH/pkg/mod/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/fake_nodemetrics.go`

```diff
- var nodemetricsesResource = schema.GroupVersionResource{Group: "metrics.k8s.io", Version: "v1beta1", Resource: "nodes"}
+ var nodemetricsesResource = schema.GroupVersionResource{Group: "metrics.k8s.io", Version: "v1beta1", Resource: "nodemetricses"}
```

you will get 
```go
fmt.Println(fakeClient.MetricsV1beta1().NodeMetricses().List(metav1.ListOptions{})) // &NodeMetricsList{ListMeta:{   <nil>},Items:[]NodeMetrics{NodeMetrics{ObjectMeta:{machine1      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Timestamp:0001-01-01 00:00:00 +0000 UTC,Window:{0s},Usage:k8s_io_api_core_v1.ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},},},} <nil>
```

**Anything else we need to know?**:

I've created an issue to resolve this issue

**Comment by liggitt** [comment]
I actually think the issue is here:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L325-L330

The object tracker used by the fake client guesses at the resource name, which is incorrect in this case.

**Comment by secret104278** [comment]
> I actually think the issue is here:
> 
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L325-L330
> 
> The object tracker used by the fake client guesses at the resource name, which is incorrect in this case.

You're right, i didn't notice that the gvr of `NodeMetrics` is diff from gvk.
After a little bit dig in, I found this PR https://github.com/kubernetes/kubernetes/pull/71049 kind of resolve this issue.
So if I change the code to this it will work.
```go
package main

import (
	"fmt"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	metricsv1beta1 "k8s.io/metrics/pkg/apis/metrics/v1beta1"

	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/metrics/pkg/client/clientset/versioned/fake"
)

func main() {
	metrics := &metricsv1beta1.NodeMetrics{
		ObjectMeta: metav1.ObjectMeta{Name: "machine1"},
		Usage: v1.ResourceList{
			v1.ResourceCPU:    resource.MustParse("100m"),
			v1.ResourceMemory: resource.MustParse("1Gi"),
		},
	}
	gvr := schema.GroupVersionResource{Group: "metrics.k8s.io", Version: "v1beta1", Resource: "nodes"}

	fakeClient := fake.NewSimpleClientset()
	_ = fakeClient.Tracker().Create(gvr, metrics, "")

	fmt.Println(fakeClient.MetricsV1beta1().NodeMetricses().List(metav1.ListOptions{})) // &NodeMetricsList{ListMeta:{   <nil>},Items:[]NodeMetrics{NodeMetrics{ObjectMeta:{machine1      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Timestamp:0001-01-01 00:00:00 +0000 UTC,Window:{0s},Usage:k8s_io_api_core_v1.ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{1073741824 0} {<nil>} 1Gi BinarySI},},},},} <nil>
}

```

However, I think this issue can be improve by deprecating `tracker.Add` in `NewSimpleClientset` from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/metrics/pkg/client/clientset/versioned/fake/clientset_generated.go#L41 , and use `tracker.Create` with explicite gvr in codegen.
