### ISSUE TITLE
no kind "PodSecurityPolicy" is registered for version "policy/v1beta1" in scheme

### ISSUE THREAD

**Issue by eastlunar** [kubernetes/kubernetes#93851]
```
Aug 10 05:48:34 k8s-master kubelet[56086]: E0810 05:48:34.033076   56086 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/kube-flannel.yaml": /etc/kubernetes/manifests/kube-flannel.yaml: couldn't parse as pod(no kind "PodSecurityPolicy" is registered for version "policy/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"), please check config file
```
I found it using `journalctl -xefu kubelet`. But nodes and pods are both fine.

**Comment by knight42** [comment]
`PodSecurityPolicy` is only supported in k8s 1.18+, perhaps you are trying to create `PodSecurityPolicy` on a cluster whose version is below 1.18. Could you post the output of `kubectl version`?

In addition, if you don't need `PodSecurityPolicy`, perhaps you could try delete it from `/etc/kubernetes/manifests/kube-flannel.yaml`.

/close
As this is not a bug, feel free to reopen if necessary.
