### ISSUE TITLE
Request github to turn on "GitHub Discussions" for kubernetes/kubernetes

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#93879]
We have a *LOT* of issues, quite a few are "support" and not necessarily related to development of k8s itself. I know we have the https://discuss.kubernetes.io/ board, but with "GitHub discussions" we can look forward to converting issue into a discussion to get it off of the dev radar. (We'd have to explore more about what conversions are available, in the pipeline etc). There are plenty of legitimate issues that fall through the cracks and get auto-closed etc. May be worth a try?

WDYT?

**Comment by neolit123** [comment]
i think we should add/extend a bot command that closes a ticket and sends a message to the user with a link to:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

we could have  `/triage close` or `/triage support` do that.

#toomanytools

i have send the same link countless times to users already, followed by a `/close`

**Comment by nikhita** [comment]
Moderating/ensuring discussions don't rot will be hard :(

> i think we should add/extend a bot command that closes a ticket and sends a (well written) message to the user with a link to:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

We could definitely have the bot add a comment with this link whenever someone comments with a `/triage support`. Maybe we could auto-close issues too... :thinking: 

cc @mrbobbytables @castrojo @cblecker
