### ISSUE TITLE
Kubelet use too much cpu (over 100%)

### ISSUE THREAD

**Issue by XiaochenCui** [kubernetes/kubernetes#93874]
k8s version: 1.13.5

My k8s node in overwhelmed by kubelet/kube-apiserver/docker
The cpu usage of kubelet in over 100%.
Here is the flame graph:

![image](https://user-images.githubusercontent.com/9801323/89878850-b1389500-dbf4-11ea-8c68-098e1bf5dbdd.png)

And there is also lots of error logs related to du command failed:
Aug 11 12:47:27 k8s-node2 kubelet[38127]: E0811 12:47:26.947907   38127 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: du command failed on /var/lib/docker/overlay2/270a585152be6486a79e106d4be0dc311ca91f93009b6e1afe905b63171fa023/diff with output stdout: 40        /var/lib/docker/overlay2/270a585152be6486a79e106d4be0dc311ca91f93009b6e1afe905b63171fa023/diff

**Comment by neolit123** [comment]
> k8s version: 1.13.5

hi, this version is no longer in support.
please re-open if you are able to reproduce the problem with 1.16+

thanks
/close
