### ISSUE TITLE
The pod need 30 minutes to be deleted after  rolling-update 

### ISSUE THREAD

**Issue by kengan** [kubernetes/kubernetes#93878]
After rolling-update a pod, the old pod need 30 minutes to be deleted. Can you tell me how to solve this problem. Thank you.

**Comment by kengan** [comment]
My deployment has set the gracetime is 30s
Every pod in my cluster are all need 30m to be removed after  rolling-update 
My kubernetes version is 1.13

**Comment by neolit123** [comment]
> My kubernetes version is 1.13

hello, please reopen this ticket if the problem is reproducible with 1.16+
older versions are no longer in support.

you could also ask for support here:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/remove-sig api-machinery
/sig apps
/close
