### ISSUE TITLE
Add 1 second to ensure freeTime > image.lastUsed，sometimes they are equal

### ISSUE THREAD

**Issue by GreatThan365** [kubernetes/kubernetes#93875]
https://github.com/kubernetes/kubernetes/blob/04362870ad9f9812f487ab8f89a40f6bf2daa588/pkg/kubelet/images/image_gc_manager_test.go#L370

time.Now() ---> time.Now().Add(time.Second)

**Comment by neolit123** [comment]
hello, could you please add more detail about your use case, kubernetes version and follow the issue template:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

/sig node
/priority awaiting-more-evidence
/kind bug
(feature?)
