### ISSUE TITLE
unit test cannot recv sys events on mips64le Loongson3A3000

### ISSUE THREAD

**Issue by duchuanLX** [kubernetes/kubernetes#93882]
**Which jobs are failing**:
go test -v k8s.io/kubernetes/pkg/kubelet/cm/devicemanager

**Which test(s) are failing**:
go test -v k8s.io/kubernetes/pkg/kubelet/cm/devicemanager

**Since when has it been failing**:
nothing

**Testgrid link**:
nothing

**Reason for failure**:
cannot recv vendor/golang.org/x/sys events，such as changefile create、delete events

**Anything else we need to know**:
goroutine 8 [syscall]:
syscall.Syscall6(0x1459, 0x6, 0xc0000efbd8, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/golang1.13.9/src/syscall/asm_linux_mips64x.s:40 +0x10
k8s.io/kubernetes/vendor/golang.org/x/sys/unix.EpollWait(0x6, 0xc0000efbd8, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go:1760 +0x70
k8s.io/kubernetes/vendor/github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000016300, 0x0, 0x0, 0x0)
	/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x7c
k8s.io/kubernetes/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000b8050)

/sig <golang.org/x/sys>
/sig node
/help

tag：v1.18.3
golang1.14.4

**Comment by neolit123** [comment]
so should `k8s.io/kubernetes/pkg/kubelet/cm/devicemanager` skip these tests on mips64le for now?
fixes welcome.

/sig node
/help

**Comment by duchuanLX** [comment]
> so should `k8s.io/kubernetes/pkg/kubelet/cm/devicemanager` skip these tests on mips64le for now?
> fixes welcome.
> 
> /sig node
> /help

sorry,unit error 30+，I must solve all the failures on mips64le，
and i change golang.org/x/sys version 2 golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd，
testcases were PASS。

**Comment by BenTheElder** [comment]
is this at HEAD in the master branch?

> cannot recv vendor/golang.org/x/sys events，such as changefile create、delete events

why is that?

cc @dims ref: Architecture support policy ...

**Comment by duchuanLX** [comment]
> is this at HEAD in the master branch?
> 
> > cannot recv vendor/golang.org/x/sys events，such as changefile create、delete events
> 
> why is that?
> 
> cc @dims ref: Architecture support policy ...

kubernetes tag：v1.18.3

exec 'go test -v k8s.io/kubernetes/pkg/kubelet/cm/devicemanager' was FAIL
Most unit tests have this error, fsnotiy cannot receive system events, such as file creation and file deletion.

**Comment by BenTheElder** [comment]
*most* unit tests shouldn't be using inotify.

Why can't inotify work? What's architecture specific about that? How is this a kubernetes bug?

**Comment by BenTheElder** [comment]
1.18.3 is a bit of an odd choice. It's neither the current development branch, nor even the latest 1.18.X code.

**Comment by duchuanLX** [comment]
> 1.18.3 is a bit of an odd choice. It's neither the current development branch, nor even the latest 1.18.X code.
kubernetes version is v1.18.3

golang.org/x/sys version	               platfrom	        kernelversion	        res
2019						X86			3.10-			PASS
2020						X86			3.10-			PASS
2019						MIPS64LE	3.10-			FAIL(cannot recv any os events)
2020						MIPS64LE	3.10-			PASS
2019						MIPS64LE	4.19			        FAIL(os crush，i trying install new kernel again)

**Comment by duchuanLX** [comment]
> 1.18.3 is a bit of an odd choice. It's neither the current development branch, nor even the latest 1.18.X code.

golang.org/x/sys-version							platfrom	kernelversion	res		appearance
golang.org/x/sys@v0.0.0-20190813064441-fde4db37ae7a	X86			3.10-			PASS	
golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd	X86			3.10-			PASS	
golang.org/x/sys@v0.0.0-20190813064441-fde4db37ae7a	MIPS		3.10-			FAIL	cannot recv any os events about file，such as create file or delete file
golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd	MIPS		3.10-			PASS	
golang.org/x/sys@v0.0.0-20190813064441-fde4db37ae7a	MIPS		4.19-			FAIL	cannot recv any os events about file，such as create file or delete file
golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd	MIPS		4.19-			PASS

**Comment by BenTheElder** [comment]
If we were to change anything it would be against 1.18 development, 1.18.3 is done.

https://github.com/kubernetes/kubernetes/tree/release-1.18

https://github.com/kubernetes/kubernetes/blob/182489b57f6b96f5ae3a988f9034568290cc0549/go.mod#L128

/remove-help

`/help` should be used when there's a clear path forward and we're aiming for a new contributor to help.

A PR to upgrade x/sys would be pretty straightforward, but it's not clear that this change will be accepted in 1.18.X

In 1.19 development we're at:
https://github.com/kubernetes/kubernetes/blob/e97978f924942e32a8c8681331ca24c0ba2b778c/go.mod#L104

**Comment by duchuanLX** [comment]
> https://github.com/kubernetes/kubernetes/tree/release-1.18

thank you,i submit a pr on release-1.18.

https://github.com/kubernetes/kubernetes/pull/93997

**Comment by BenTheElder** [comment]
As I said, I'm not sure if that will be accepted, but we'll see.

We don't do a lot of dependency changes after release, especially not for a
platform we have no CI for.

You should consider trying to get this in a future minor release /
targeting the master branch.

**Comment by SergeyKanzhelev** [comment]
/close

seems like the corresponding PR wasn't accepted and the issue is not present on 1.19+
