### ISSUE TITLE
The updatecache method of relist function in PLEG takes too long time to execute，resulting in PLEG health check timeout

### ISSUE THREAD

**Issue by liruishan** [kubernetes/kubernetes#93886]
**What happened**:
I deployed 360 pods and 765 containers on one node in my cluster.Sometimes, I find "PLEG is not healthy" in my cluster. I add log printing to kubelet and find it takes a long time in the updatecache phase of the relist function, which takes 1m23s, causing the PLEG health check to exceed the 3-minute threshold. I don't know why this happens. Has anyone encountered a similar situation
**What you expected to happen**:
The update cache method can quickly return results
**How to reproduce it (as minimally and precisely as possible)**:
Deploy and delete pods repeatedly
**Anything else we need to know?**:
[root@m1 kubelet]# cat kubelet.INFO | grep "PLEG is not"
I0811 16:05:03.437165 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.32 2579259s ago; threshold is 3m0s
I0811 16:05:03.538856 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.42 4244737s ago; threshold is 3m0s
I0811 16:05:03.739811 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.62 5217759s ago; threshold is 3m0s
I0811 16:05:04.144800 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m1.03 020946s ago; threshold is 3m0s
I0811 16:05:04.945386 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m1.83 0800793s ago; threshold is 3m0s
I0811 16:05:06.546163 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m3.43 1568788s ago; threshold is 3m0s
I0811 16:05:09.746368 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m6.63 1770887s ago; threshold is 3m0s
I0811 16:05:14.747850 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m11.6 33262432s ago; threshold is 3m0s
I0811 16:05:19.037564 3696 setters.go:533] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2020-08-11 16:05:19 .03752471 +0800 CST m=+63306.908382105 LastTransitionTime:2020-08-11 16:05:19.03752471 +0800 CST m=+63306.908382105 Reason:KubeletN otReady Message:PLEG is not healthy: pleg was last seen active 3m15.922979347s ago; threshold is 3m0s}
I0811 16:05:19.750746 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m16.6 36166621s ago; threshold is 3m0s
I0811 16:05:24.751846 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m21.6 37261041s ago; threshold is 3m0s
I0811 16:05:29.752063 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m26.6 37476551s ago; threshold is 3m0s
I0811 16:05:34.753926 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m31.6 39333536s ago; threshold is 3m0s
I0811 16:05:39.755355 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m36.6 40767188s ago; threshold is 3m0s
I0811 16:05:44.760778 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m41.6 46203944s ago; threshold is 3m0s
I0811 16:05:49.967541 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m46.6 67901305s ago; threshold is 3m0s
I0811 16:05:54.967689 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m51.8 53097934s ago; threshold is 3m0s
I0811 16:05:59.969157 3696 kubelet.go:1826] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m56.8 54585336s ago; threshold is 3m0s

The following information is the kubelet log print I added. It shows that the updatecache time is too long:
W0811 16:02:09.491010 3696 generic.go:256] Start UPDATECACHE
W0811 16:03:32.624993 3696 generic.go:271] End UPDATECACHE
W0811 16:03:39.115347 3696 generic.go:256] Start UPDATECACHE
W0811 16:05:24.118042 3696 generic.go:271] End UPDATECACHE
W0811 16:05:24.118065 3696 generic.go:256] Start UPDATECACHE
W0811 16:05:35.365380 3696 generic.go:271] End UPDATECACHE
W0811 16:05:35.365401 3696 generic.go:256] Start UPDATECACHE
W0811 16:05:45.724856 3696 generic.go:271] End UPDATECACHE
**Environment**:
- Kubernetes version (use `kubectl version`):1.15.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`):Linux auto-test 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):calico 3.7.4
- Others:
  docker version：19.03.9

**Comment by neolit123** [comment]
hi,

> Kubernetes version (use kubectl version):1.15.6

is this the kubelet version too?

<1.16 is out of support and 1.16 will go out of support with the release of 1.19.

is the problem reproducible with a newer kubelet?

/sig node
/priority awaiting-more-evidence

**Comment by liruishan** [comment]
> hi,
> 
> > Kubernetes version (use kubectl version):1.15.6
> 
> is this the kubelet version too?
> 
> <1.16 is out of support and 1.16 will go out of support with the release of 1.19.
> 
> is the problem reproducible with a newer kubelet?
> 
> /sig node
> /priority awaiting-more-evidence

YES，kubelet version is also 1.15.6;
I checked the latest code of kubelet and found that the method of updatacache has not been modified. The code has the following comments,there is a todo in this place, but no one has modified it so far:
// updateCache() will inspect the pod and update the cache. If an
// error occurs during the inspection, we want PLEG to retry again
// in the next relist. To achieve this, we do not update the
// associated podRecord of the pod, so that the change will be
// detect again in the next relist.
// TODO: If many pods changed during the same relist period,
// inspecting the pod and getting the PodStatus to update the cache
// serially may take a while. We should be aware of this and
// parallelize if needed.
