### ISSUE TITLE
TestRunInitNodeChecks flake on periodic-kubernetes-bazel-test-master 

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/kubernetes#93883]
**Which jobs are flaking**:
[periodic-kubernetes-bazel-test-master #1293066905715740674](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1293066905715740674)

**Which test(s) are flaking**:
[cmd/kubeadm/app/preflight/checks_test.go#TestRunInitNodeChecks](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks_test.go#L187)
**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master
**Reason for failure**:
```
[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
    checks_test.go:250: failed RunInitNodeChecks:
        	expected: true
        	  actual: false
        	 error: [preflight] Some fatal errors occurred:
        	[ERROR Port-10259]: Port 10259 is in use
```

**Anything else we need to know**:
Test case is not written to the log

**Comment by RobertKielty** [comment]
For now 
/sig testing

**Comment by neolit123** [comment]
so these are the /cmd/kubeadm unit tests called from the periodic-kubernetes-bazel-test-master job.
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master&sort-by-flakiness=

i see one flake on this test today, but none prior to that. perhaps my test grid view is not configured correctly?

>         	[ERROR Port-10259]: Port 10259 is in use

i do not know what may be occupying that port in that single failure, but maybe there are two tests racing to test a kubelet.
in any case, "unit tests" that test availability of system ports should be promoted to integration tests (i.e. we can should remove/refactor tests from https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks_test.go)

/area kubeadm
/sig cluster-lifecycle

**Comment by neolit123** [comment]
/priority awaiting-more-evidence
(since i don't see a consistently flaky test?)

**Comment by neolit123** [comment]
>  we can should remove/refactor tests from

logged: https://github.com/kubernetes/kubeadm/issues/2251

**Comment by RobertKielty** [comment]
@neolit123 No other evidence is required. 

The fact this test has both failed and succeeded on the same commits for both k/k and kubernetes/test-infa is what marks this as a flake.

/remove awaiting-more-evidence

**Comment by RobertKielty** [comment]
@neolit123 for sure, you raise an important point here in relation to terminology. 

When I use the term, "flaky test" I really intend to refer to the _test result_ being _non-deterministic_ for a given set of input conditions. I apologize if that was not clear! I am not referring to the test code itself and as **you rightly point out the test implementation is not flaky.** 

My focus here in logging this issue is that the _single run where we saw an unexpected error_ adds unwanted noise to the test result signal delivered by the tests.

Also from a CI Signal point of view adding the name of the test case that failed should improve the result signal delivered help decrease triage times.

Thanks again fro taking the time to review the issue. I very much appreciate it!

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/93883#issuecomment-671929931 +1 yeah ... unit tests should not require binding to a specific real port (!)

we can actually tag these "integration" under bazel manually in the short term.
