### ISSUE TITLE
[sig-api-machinery] TestWatchHTTPTimeout flake: Leaked watch on timeout

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93891]
**Which test(s) are flaking**:

TestWatchHTTPTimeout

**Reason for failure**:

```
--- FAIL: TestWatchHTTPTimeout (0.01s)
    watch_test.go:848: Leaked watch on timeout
FAIL
```

This test is flaking, but not enough to fail our presubmit CI (which currently retries up to 3 times and passes on a single green run).

Observed in https://github.com/kubernetes/kubernetes/pull/93605#issuecomment-668332578 when trying to disable this flake toleration.

Reproducer steps:

1. Build test binary:
```
go test -race -c k8s.io/apiserver/pkg/endpoints
```

2. Run with [stress](https://godoc.org/golang.org/x/tools/cmd/stress):
```
stress ./endpoints.test -test.run TestWatchHTTPTimeout
```

This is reproducible on release-1.18 as well, though is happening an order of magnitude more frequently on master:
```
1.18:   1145 runs so far, 2 failures (~0.1%)
master: 1311 runs so far, 15 failures (~1.1%)
```

/sig api-machinery

**Comment by knight42** [comment]
/assign

I would like to give it a shot.

**Comment by liggitt** [comment]
thanks for looking
