### ISSUE TITLE
ProjectedVolumeSource transformed incorrectly on write

### ISSUE THREAD

**Issue by cbandy** [kubernetes/kubernetes#93903]
**What happened**:

I created a Pod with a ProjectedVolume with an empty array of `sources`, but Kubernetes transformed that value to `null`. Some clients are happy with either value (e.g. Go) while others are not (e.g. Python).

For example, the following is accepted and stored by Kubernetes, but cannot be read by the Python client:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-projected
spec:
  containers:
  - name: busybox
    image: docker.io/library/busybox
    command: [ sleep, 5m ]
  volumes:
  - name: content
    projected: { sources: [] }
```

```python
client.CoreV1Api().read_namespaced_pod(namespace='default', name='test-projected')
# ValueError: Invalid value for `sources`, must not be `None`
```

The `sources` field has been transformed to `null`:
```
$ kubectl get pod test-projected -o jsonpath='{.spec.volumes[0]}{"\n"}'
map[name:content projected:map[defaultMode:420 sources:<nil>]]
```
```
$ kubectl get pod test-projected -o yaml | grep -A4 '  volumes:'
  volumes:
  - name: content
    projected:
      defaultMode: 420
      sources: null
```

Even a JSON patch has no effect:
```
$ kubectl patch pod test-projected --type=json --patch='[{"op":"add","path":"/spec/volumes/0/projected/sources","value":[]}]'
pod/test-projected patched
```
```
$ kubectl get pod test-projected -o yaml | grep -A4 '  volumes:'
  volumes:
  - name: content
    projected:
      defaultMode: 420
      sources: null
```

**What you expected to happen**:

I expected the required (OpenAPI) field `sources` of core/v1.ProjectedVolumeSource to be returned as the empty array I submitted.

**How to reproduce it (as minimally and precisely as possible)**:

Create the above Pod:
```
$ kubectl create -f pod.yaml
pod/test-projected created
```

See that `sources` has been transformed to `null`:
```
$ kubectl get pod test-projected -o jsonpath='{.spec.volumes[0]}{"\n"}'
map[name:content projected:map[defaultMode:420 sources:<nil>]]
```

See that the officially-supported Python client is unable to deserialize the Pod:
```
$ python3 -m venv env
$ ./env/bin/pip install kubernetes
…
Successfully installed cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 google-auth-1.20.1 idna-2.10 kubernetes-11.0.0 oauthlib-3.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 python-dateutil-2.8.1 pyyaml-5.3.1 requests-2.24.0 requests-oauthlib-1.3.0 rsa-4.6 six-1.15.0 urllib3-1.25.10 websocket-client-0.57.0

$ ./env/bin/python
Python 3.6.8 (default, Apr 16 2020, 01:36:27)

>>> from kubernetes import client, config
>>> config.load_kube_config()
>>> client.CoreV1Api().read_namespaced_pod(namespace='default', name='test-projected')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  …
ValueError: Invalid value for `sources`, must not be `None`
```

**Anything else we need to know?**:

I recognize there's a lot of layers involved in the steps above. The ineffectiveness of the JSON patch is what makes me think the culprit is somewhere in the field spec or API somehow.

/sig api-machinery

**Environment**:
- Kubernetes version (use `kubectl version`):
   ```
   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
   ```

[official-clients]: https://kubernetes.io/docs/reference/using-api/client-libraries/

**Comment by liggitt** [comment]
/remove-sig api-machinery
/sig storage

the issue is in the API definition, which does not indicate the sources field is optional (even though it is)

https://github.com/kubernetes/kubernetes/blob/236b9e7fcda25d9b28afa81305ab23f98e622461/staging/src/k8s.io/api/core/v1/types.go#L1584-L1587
