### ISSUE TITLE
Persistent Volumes in On-Premise HTTP Object Storage Services

### ISSUE THREAD

**Issue by adaptivecorporation** [kubernetes/kubernetes#93915]
**What would you like to be added**: ***Persistent volume support for HTTP/S3 compatible storage systems***

**Why is this needed**:  There is a growing use of on-premise distributed systems used for storing unstructured assets; this would allow larger clusters to take advantage of the scalability of these services.

/sig storage

**Comment by cbandy** [comment]
Sounds very similar to https://github.com/kubernetes/enhancements/pull/1383

**Comment by adaptivecorporation** [comment]
> 
> 
> Sounds very similar to [kubernetes/enhancements#1383](https://github.com/kubernetes/enhancements/pull/1383)

@cbandy you are correct, thank you very much. I will follow this! Closing issue.
