### ISSUE TITLE
Kubelet doesn't start on Linux kernels with CONFIG_SWAP=n

### ISSUE THREAD

**Issue by lyind** [kubernetes/kubernetes#93913]
**What happened**:
Kubelet doesn't start during `kubeadm init`, journalctl shows:
`kubelet[17870]: F0812 02:15:15.717137   17870 server.go:274] failed to run Kubelet: open /proc/swaps: no such file or directory`

**What you expected to happen**:
Kubelet correctly identifies absence of `/proc/swaps` as "no swap present", kubelet service starts and `kubeadm init` can finish.

**How to reproduce it (as minimally and precisely as possible)**:
Build a Linux kernel with `CONFIG_SWAP=y`, install kubeadm, kubelet and try `kubeadm init`.

**Anything else we need to know?**:
No registered swap devices *or* a kernel without swap enabled both means that there is no swap space present. Kubectl successfully checks for the former case but throws an error on the later.
Failure to open `/proc/swaps` means *no swap*.

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Hardware configuration: `on-premises`
- OS: `Debian GNU/Linux bullseye/sid`
- Kernel: `Linux 5.8.0 monolithic kernel with CONFIG_SWAP=n`
- Install tools: `kubeadm`

**Comment by neolit123** [comment]
> Failure to open /proc/swaps means no swap.

this is a potential improvement for the kubelet.

/sig node
/remove-sig cluster-lifecycle

**Comment by lyind** [comment]
The issue can be worked around by adding `--fail-swap-on=false` to `KUBELET_EXTRA_ARGS` (defined in `/etc/default/kubelet` on Debian):

**/etc/default/kubelet**
```
KUBELET_EXTRA_ARGS="--fail-swap-on=false"
```
