### ISSUE TITLE
Pod stuck in Terminating state

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#93925]
**What happened**:

The Calico team is doing a churn test to test Calico but we seem to have run into a kubernetes issue.  Some pods are getting stuck in the Terminating state.  That's bad enough but it seems that

* kubelet is getting far enough that it calls the CNI plugin
* CNI plugin deletes the interface, thus freeing the IP for reuse
* kubelet doesn't remove the IP from the pod spec
* CNI plugin gets called for another pod and allocates the same IP to a new pod
* now we have two pods with the same IP allocated and they're both in states where Calico thinks that they should be networked (we keep networking up when a pod is in Terminating state so that apps that are gracefully shutting down can shut down network connections).

The describe output for the pod says
```
Events:
  Type     Reason     Age                    From                                                   Message
  ----     ------     ----                   ----                                                   -------
  Normal   Killing    21m (x205 over 7h3m)   kubelet, ip-172-16-102-106.us-west-2.compute.internal  Stopping container nginx
  Warning  Unhealthy  76s (x2531 over 7h2m)  kubelet, ip-172-16-102-106.us-west-2.compute.internal  Readiness probe failed: cannot exec in a stopped state: unknown
```

So looks like it's trying to kill the pod.

Examining `docker ps`, I see that the `k8s_POD` container is gone but the workload container is still running:
```
b8e1c8d7a96f        a61ec0c44569                                "nginx -g 'daemon of…"   8 hours ago          Up 8 hours                              k8s_nginx_server2-cali-ns-2-55b5df445f-mc9qm_cali-ns-2_f3dfc21f-605b-4270-9cd7-4cec7f3712a7_0
```

**What you expected to happen**:

kubelet cleans up the pod, including the workload container

**How to reproduce it (as minimally and precisely as possible)**:

This happened after running pod and namespace churn for a few hours.  We scale up and down nginx deployments behind services and clients that connect to them.  Namespaces with clients/servers come and go.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:29:33Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

Running on AWS, cluster created with kubeadm.

- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ip-172-16-102-106.us-west-2.compute.internal 5.4.0-1021-aws #21-Ubuntu SMP Fri Jul 24 09:42:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Calico, pre-release build in BPF mode (this was what we were testing)
- Others:
```
docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Comment by fasaxc** [comment]
Output from 
```
kubectl get po -n cali-ns-2 server2-cali-ns-2-55b5df445f-mc9qm -o yaml
```
[pod.yaml.gz](https://github.com/kubernetes/kubernetes/files/5062729/pod.yaml.gz)

**Comment by fasaxc** [comment]
Tailing the kubelet log, I see a few of these errors go by:
```
Aug 12 12:58:52 ip-172-16-102-106.us-west-2.compute.internal kubelet[5934]: E0812 12:58:52.859567    5934 remote_runtime.go:351] ExecSync dacf689c19913a79a0b44c751faadbab1159db22072dd84c47f0775c71c67001 'curl http://localhost' from runtime service failed: rpc error: code = Unknown desc = container not running (dacf689c19913a79a0b44c751faadbab1159db22072dd84c47f0775c71c67001)
```

And these warnings:
```
pod_container_deletor.go:77] Container "b87ec8b4b18d8356b89938e164b6748bd0d1fb52a53d9b88e4cdea30799ba22f" not found in pod's containers
```
Seems to be different IDs each time

Also see this in the docker journal:
```
Aug 12 13:07:23 ip-172-16-102-106.us-west-2.compute.internal dockerd[5704]: time="2020-08-12T13:07:23.100271582Z" level=info msg="Container b8e1c8d7a96f839c420431dda9c1ac34dd2aeb6833fae4d47cd013a95d4c31f0 failed to exit within 30 seconds of signal 15 - using the force"
```

Looks like docker is failing to kill the container

**Comment by fasaxc** [comment]
Doing `docker rm -f <container ID>` successfully removed the container and kubelet immediately spotted that and the pod was torn down.

**Comment by fasaxc** [comment]
Could kubelet do the equivalent of `docker rm -f` to unwedge itself?

**Comment by brianpursley** [comment]
This function seems a little suspicious to me:

https://github.com/kubernetes/kubernetes/blob/14d9b5d7589841d66a14451bad3bbad11eb88b89/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L879-L897

If `killContainersWithSyncResult` (line 880) fails to kill any of the containers, it doesn't stop and it still kills the sandbox (line 885 onward)

At this point, you have one or more containers still hanging around, but the sandbox is gone, and the call to `killPodWithSyncResult` will be an error, so the pod will still be hanging around too.

Seems like the sandbox should not be deleted UNLESS all containers have been successfully deleted.

I wonder if this should have a return at line 884, something like this:
```
        if result.Error() != nil {
		return result
	}
```

Anyone have any thoughts on this?

**Comment by brianpursley** [comment]
Also this one:
https://github.com/kubernetes/kubernetes/blob/b181c76cbdc9ff2946967a3970280ef0652d8c06/pkg/kubelet/kubelet.go#L1525-L1527


If `syncPod` tries to kill the pod and fails, it looks like nothing is logged. [Other](https://github.com/kubernetes/kubernetes/blob/b181c76cbdc9ff2946967a3970280ef0652d8c06/pkg/kubelet/kubelet.go#L1409-L1414) [places](https://github.com/kubernetes/kubernetes/blob/b181c76cbdc9ff2946967a3970280ef0652d8c06/pkg/kubelet/kubelet.go#L1483-L1487) that call `killPod` log an error, so I wonder if this one should too (and return as well).

**Comment by ehashman** [comment]
@fasaxc can you provide a full kubelet log dump for this, preferably with increased verbosity if it's available? This sounds similar to some other issues around pod/sandbox deletion we are currently investigating. (see e.g. #98142) If this is running on a cluster with docker, I think that the kubelet isn't using the kuberuntime_manager code path, there's a separate one for docker. If it's using containerd via the kuberuntime, that's another matter. Logs would make it clear :)

**Comment by fasaxc** [comment]
Sorry, I can't _easily_ repro this.  To do so requires spinning up a 100+ node cluster and running churn for several hours.

**Comment by ehashman** [comment]
@fasaxc it's okay if the repro isn't easy, we just can't do much to address this without kubelet logs to assist in debugging :( The next time it happens, would appreciate a log dump!

**Comment by ehashman** [comment]
I think there are a number of patches that have gone in that should have helped with this issue. Is it possible to test against 1.21?

**Comment by fasaxc** [comment]
As it happens, we're about to do another round of scale testing; we'll look out for issues.

**Comment by fasaxc** [comment]
First round of scale testing at 100 nodes on Kubernetes **v1.20** (not v1.21, yet).  

* The rig as a whole became somewhat overloaded; not sure if this is due to Calico or Kubernetes issue at this stage.
* Kubelets started to go NotReady with PLEG errors.
* Listing pods, I see some pods stuck in Terminating state, 80m after they were deleted.
* Examining kubelet log, I see errors repeating like this:
```
May 12 10:51:56 lance-bz-33et-kadm-node-1 kubelet[1195]: E0512 10:51:56.710546    1195 kubelet.go:1857] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 8m32.184381525s ago; threshold is 3m0s
May 12 10:51:57 lance-bz-33et-kadm-node-1 kubelet[1195]: E0512 10:51:57.001543    1195 remote_runtime.go:392] ExecSync 633b34598f2bd79cb90d84c5234f36809846034a3f83f1b292b3d62d86a69f84 'curl http://localhost' from runtime service failed: rpc error: code = Unknown desc = container not running (633b34598f2bd79cb90d84c5234f36809846034a3f83f1b292b3d62d86a69f84)
```
* However, examining the state of docker, it's different to v1.18.  Both the k8s_POD and the workload container appear to have been cleaned up as expected.

I've attached a kubelet log; looks like it had wrapped by the time the problem started.
[kubelet.log.gz](https://github.com/kubernetes/kubernetes/files/6465702/kubelet.log.gz)

**Comment by fasaxc** [comment]
Example pod that seems to be stuck: 
```
$ kubectl get po -o yaml -n cali-ns-0                    client21-cali-ns-0-bb6cb6fc6-w8f9w
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: ""
    cni.projectcalico.org/podIPs: ""
    projectcalico.org/iteration: "1"
  creationTimestamp: "2021-05-12T09:23:03Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2021-05-12T09:35:05Z"
  generateName: client21-cali-ns-0-bb6cb6fc6-
  labels:
    app: calico-test-client
    chosenServer: server156-cali-ns-0
    deployment: client21-cali-ns-0
    index: "21"
    pod-template-hash: bb6cb6fc6
    projectcalico.org/app: scale-test
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:projectcalico.org/iteration: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:chosenServer: {}
          f:deployment: {}
          f:index: {}
          f:pod-template-hash: {}
          f:projectcalico.org/app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"105ae3e2-d3b4-4dc2-91fc-c27a92e2ef54"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"ttfp"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"ADDRESS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"CONN_PER_SECOND"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"FAIL_CONN_PER_SECOND"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"NODE_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
              k:{"name":"PORT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"PROM_GATEWAYS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"PROTOCOL"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"TIMEOUT"}:
                .: {}
                f:name: {}
              k:{"name":"UNREACHABLE_ADDRESS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"URL_LENGTH_FACTOR"}:
                .: {}
                f:name: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:nodeSelector:
          .: {}
          f:cloud.google.com/gke-nodepool: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-12T09:23:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2021-05-12T09:23:05Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"192.168.102.46"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-05-12T09:23:08Z"
  name: client21-cali-ns-0-bb6cb6fc6-w8f9w
  namespace: cali-ns-0
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: client21-cali-ns-0-bb6cb6fc6
    uid: 105ae3e2-d3b4-4dc2-91fc-c27a92e2ef54
  resourceVersion: "5235628"
  uid: 8db02595-5f21-4370-baa9-65836a91d212
spec:
  containers:
  - env:
    - name: ADDRESS
      value: 10.100.152.232
    - name: PORT
      value: "80"
    - name: TIMEOUT
    - name: PROTOCOL
      value: tcp
    - name: URL_LENGTH_FACTOR
    - name: CONN_PER_SECOND
      value: "10"
    - name: FAIL_CONN_PER_SECOND
      value: "10"
    - name: PROM_GATEWAYS
      value: '["192.168.111.204:9091","192.168.188.147:9091","192.168.41.160:9091"]'
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: UNREACHABLE_ADDRESS
      value: 10.109.57.147
    image: gcr.io/unique-caldron-775/ttfp:latest
    imagePullPolicy: IfNotPresent
    name: ttfp
    resources:
      requests:
        cpu: 10m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rpkc6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: lance-bz-33et-kadm-node-1
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-rpkc6
    secret:
      defaultMode: 420
      secretName: default-token-rpkc6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-12T09:23:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-12T09:23:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-12T09:23:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-12T09:23:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b4663fdb01580ea2c1dac4a6e7a55abe66399d584a3a0dfe5a008022f4ac2917
    image: gcr.io/unique-caldron-775/ttfp:latest
    imageID: docker-pullable://gcr.io/unique-caldron-775/ttfp@sha256:018d0b4ac1e36f5be48cabd1c1c36bf30fd1e54378e986ee1444581ff541560f
    lastState: {}
    name: ttfp
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-12T09:23:06Z"
  hostIP: 10.128.1.95
  phase: Running
  podIP: 192.168.102.46
  podIPs:
  - ip: 192.168.102.46
  qosClass: Burstable
  startTime: "2021-05-12T09:23:03Z"
```

**Comment by fasaxc** [comment]
We ran a v1.21 test with similar results:
* At some point things got overloaded and PLEGs went unhealthy as above.
* After tearing down the test, kubelets started reporting ready again (eventually, but it took an hour or so).
* We shut down the nodes to save money before the test was fully torn down so we're not sure if there were any left over terminating pods at the end of it all.

**Comment by fasaxc** [comment]
Certainly looks like the bug that was leaving one container up has gone but under overload, looks like kubelet can get stuck unable to finish tear down of long-dead pods.

**Comment by fasaxc** [comment]
OK, we've done another run on v1.21 and this time we certainly have pods stuck in Terminating state even after we've stopped the test and given it an hour to cool down and terminate pods etc.  Listing pods, I see pods stuck in Terminating for a long time.  The nodes that have the stuck pods are all NotReady.

Logging onto a node, I see that the CPU is 80% idle so the overload condition really has stopped.

Kubelet log has various errors in it:
```
May 14 16:38:35 lance-bz-33et-kadm-node-15 kubelet[15990]: E0514 16:38:35.955650   15990 kubelet.go:1877] "Skipping pod synchronization" err="PLEG is not healthy: pleg was last seen active 46m31.770147892s ago; threshold is 3m0s"
```
seems to be the proximate cause of being NotReady but there are lots of other errors (full log attached)

[kubelet.log.gz](https://github.com/kubernetes/kubernetes/files/6480102/kubelet.log.gz)

**Comment by fasaxc** [comment]
Here is a log from a node that recovered on its own.  Not obvious to me what caused it to start to recover.

[kubelet-recovered.log.gz](https://github.com/kubernetes/kubernetes/files/6480150/kubelet-recovered.log.gz)

**Comment by ehashman** [comment]
/remove-priority awaiting-more-evidence
/triage accepted

I haven't had time to debug this recently but I suspect this is a similar root cause to a lot of the pod race conditions I've been working on in OpenShift. I'll try to compile a list of PRs that could potentially address this. We have another PR up now that unifies the deletion path and should be fixing this in 1.22.

**Comment by ehashman** [comment]
Can someone confirm if this can be reproduced in 1.22?

**Comment by ehashman** [comment]
> Logging onto a node, I see that the CPU is 80% idle so the overload condition really has stopped.

20% overall CPU utilization, especially on a large node is not trivial... to me this smells like a performance issue. I haven't had the time to dive into this but the kubelet logs will hopefully be helpful.

/remove-lifecycle stale

**Comment by kimvu3010** [comment]
Hi,
any progress on this issue. I'm still having this on kubelet version 1.21

**Comment by ehashman** [comment]
/remove-triage accepted
/triage needs-information

We need to reproduce this on a more recent version of k8s. We completed a bunch of refactoring in 1.22/1.23 so this may be fixed.
