### ISSUE TITLE
Analytics link not working in main README.md

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#93949]
The analytics link https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/README.md?pixel embedded in [README.md](https://github.com/kubernetes/kubernetes/blob/master/README.md) is not working now.

If you open https://github.com/kubernetes/kubernetes, scroll down to the bottom, you will get:

![image](https://user-images.githubusercontent.com/1425903/90073781-ac381c00-dcae-11ea-92ba-a292b89496dc.png)

/kind documentation

**Comment by habibrosyad** [comment]
Similar issue in https://github.com/kubernetes/website/issues/22819, however they decided to remove it here https://github.com/kubernetes/website/pull/22998

**Comment by nikhita** [comment]
cc @jimangel

**Comment by jimangel** [comment]
Thanks for the ping! Just realized there was a hold on the removal PR. Merging underway now 😅

**Comment by jimangel** [comment]
While this is fixed on the actual Kubernetes website, the issue will still remain on all GitHub markdown files that contain the url.

It seems appropriate for a good first issue. The action would be searching for the url in all Kubernetes org markdown files and removing it.

/good-first-issue

**Comment by Bhard27** [comment]
Is this issue still open? Can anyone guide me about it?

**Comment by avr1254** [comment]
I've submitted the PR above, but it hasn't been merged yet. I don't know why.

**Comment by Bhard27** [comment]
Yeah, that's what I was wondering.
