### ISSUE TITLE
Node IP can't be reached

### ISSUE THREAD

**Issue by manjeetsorout** [kubernetes/kubernetes#93958]
**What happened**:
when i make request in the browser using <nodeIp>:<nodePort>, then i get the following output:
This site can’t be reached192.168.43.166 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**What you expected to happen**:
it should open the wordpress service on this ip.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
containers are running well in the pods:
`kubectl get pods
NAME                               READY   STATUS    RESTARTS   AGE
apache-7c5f5869cc-59fpp            1/1     Running   2          6d22h
ghost-6bbd97db54-pfh8k             1/1     Running   2          6d16h
hello-world-86d6c6f84d-9984s       1/1     Running   2          6d23h
hello-world-86d6c6f84d-pdpmn       1/1     Running   2          6d23h
nginx-f89759699-f4vr8              1/1     Running   2          6d22h
wordpress-5c55876fd4-hx4wh         1/1     Running   1          18h
wordpress-mysql-85ff59475f-t74fs   1/1     Running   1          18h
`
`cat wordpress-deployment.yaml 
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo Done Deploying sv-premier; sleep 3600;done"]
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim`

`kubectl get pvc
NAME             STATUS   VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mysql-pv-claim   Bound    wp-pv-volume      20Gi       RWX            manual         18h
wp-pv-claim      Bound    mysql-pv-volume   20Gi       RWX            manual         18h
`

`kubectl describe svc wordpress
Name:                     wordpress
Namespace:                default
Labels:                   app=wordpress
Annotations:              Selector:  app=wordpress,tier=frontend
Type:                     NodePort
IP:                       10.110.81.202
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30865/TCP
Endpoints:                192.168.62.254:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
`

**Environment**:
- Kubernetes version (use `kubectl version`):
Kubernetes version (use kubectl version):
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by adaptivecorporation** [comment]
@manjeetsorout I don't think this is a bug, how did you configure your CNI? Just wrote same comment a few days ago on another post relating to kube-dns, I have a good feeling it has something to do with your networking. I had been unable to reach pods, or ping hosts from pods. The final fix ended up being rebuilding the master by following the official documentation and using Calico as the CNI overlay. My issues were solved. Just my two cents.

**Comment by neolit123** [comment]
> I don't think this is a bug

i agree. please use the support channels for support questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thank you!

/triage support
/close
