### ISSUE TITLE
Service IP mapping issue

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#9395]
On several occasions now, kube-proxy has ended up in a weird state where it is trying to open up connections to the wrong IP.

I have a service "turnstile":
         
    $ kubectl get endpoints turnstile
    NAME        ENDPOINTS
    turnstile   10.244.20.49:8080,10.244.20.49:10000

And the service definition:

    $ kubectl get service turnstile
    NAME        LABELS                         SELECTOR         IP               PORT(S)
    turnstile   name=turnstile,role=frontend   name=turnstile   10.100.213.187   8080/TCP
                                                                172.31.13.122    443/TCP

The following rules are in iptables:

    REDIRECT   tcp  --  0.0.0.0/0            10.100.242.60        /* production/turnstile:http */ tcp dpt:8080 redir ports 56310
    REDIRECT   tcp  --  0.0.0.0/0            172.31.13.122        /* production/turnstile:http */ tcp dpt:8080 redir ports 56310
    REDIRECT   tcp  --  0.0.0.0/0            10.100.242.60        /* production/turnstile:https */ tcp dpt:443 redir ports 35366
    REDIRECT   tcp  --  0.0.0.0/0            172.31.13.122        /* production/turnstile:https */ tcp dpt:443 redir ports 35366

    DNAT       tcp  --  0.0.0.0/0            10.100.242.60        /* production/turnstile:http */ tcp dpt:8080 to:172.31.13.122:56310
    DNAT       tcp  --  0.0.0.0/0            172.31.13.122        /* production/turnstile:http */ tcp dpt:8080 to:172.31.13.122:56310
    DNAT       tcp  --  0.0.0.0/0            10.100.242.60        /* production/turnstile:https */ tcp dpt:443 to:172.31.13.122:35366
    DNAT       tcp  --  0.0.0.0/0            172.31.13.122        /* production/turnstile:https */ tcp dpt:443 to:172.31.13.122:35366

Performing a `curl http://10.100.213.187:8080` simply hangs (as the iptables mapping seems to be wrong). 

Performing `curl http://172.31.13.122:56310` gives the following in the kube-proxy log:

                    856 proxier.go:116] Accepted TCP connection from 172.31.13.122:38499 to 172.31.13.122:44595
    1:57.381394     856 proxier.go:116] Accepted TCP connection from 172.31.13.122:58990 to   172.31.13.122:56310
    1:58.381677     856 proxier.go:85] Dial failed: dial tcp 10.244.20.45:8080: i/o timeout
    2:00.381935     856 proxier.go:85] Dial failed: dial tcp 10.244.20.45:8080: i/o timeout
    2:00.385905     856 proxier.go:85] Dial failed: dial tcp 10.244.20.45:8080: no route to host

As you can see, something seems screwed up with the service IP mappings. The iptables rules seem out-of-date and kube-proxy is trying to connect to some IP (10.244.20.45) that doesn't match the endpoint (10.244.20.49).

This just happened suddenly after the service had been running fine for many days.

**Comment by erimatnor** [comment]
Some additional info. Deleting the replication controller and service definition (i.e., removing the service completely) left the iptables rules in the kernel. Manually deleting these rules and adding rc and service again didn't help. Mapping was still wrong. Finally, restarting kubelet and kube-proxy seemed to resolve the issue.

**Comment by thockin-cc** [comment]
Did you look at kube-proxy logs?

**Comment by erimatnor** [comment]
I posted a short excerpt from the kube-proxy log above. Or are you looking for something else?

**Comment by brendandburns** [comment]
```kube-proxy``` is responsible for these rules.  It should be synchronizing them.

I see that there is a note in the code:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/proxier.go#L172

That we don't delete old routes.

My guess is that we somehow connection to the API server to get new updates.  The next time this happens, can you post the full ```/var/log/kube-proxy.log``` that would help us figure out what the issue is.  

Looking at the code I can see any obvious problems.

Thanks!
--brendan

**Comment by thockin** [comment]
Yeah, this is a new symptom I've not seen before.  I was looking for something more ... incriminating.  Maybe you can run your kube -proxy with -v=4 soit generates more logs.  It's possible there's some corner case where we don't clean up properly, but even then I would expect the correct rules to show up later in the list...

**Comment by erimatnor** [comment]
Not sure if this helps, but here's a little bit more information. I think this happened mostly when some of my AWS instances became overloaded. I was running quite weak instances with InfluxDB taking up a lot of CPU. At one point, one node became unresponsive and Kubernetes tried to move all pods off of it to another node. This caused a lot of flux and perhaps this in combination with unresponsive instances caused some old state to be left behind.

**Comment by thockin** [comment]
The whole system is supposed to self-heal, so no matter what happened, it
should rectify itself in O(10 seconds).

**Comment by thockin** [comment]
Is this still something to look into?  Or has it disappeared?
