### ISSUE TITLE
kmsv2: consider removing KMS from /livez checks

### ISSUE THREAD

**Issue by MAnyKey** [kubernetes/kubernetes#93968]
**What happened**:
kube-apiserver goes unhealthy and restarts when a kms provider returns PermissionDenied on Encrypt/Decrypt requests. This may happen when the permission to encrypt and decrypt gets revoked.

**What you expected to happen**:
I expected kube-apiserver to stay healthy and return errors on types covered by the kms provider.

**How to reproduce it (as minimally and precisely as possible)**:
Revoke permission to encrypt/decrypt data by a KMS key.

**Anything else we need to know?**:
[Code](https://github.com/kubernetes/kubernetes/blob/ed4c2dbf9211bec3e080488b0fd67a9725759a45/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go#L139) just does classic `err != nil` so I think that checking error code here will resolve the issue.

**Comment by liggitt** [comment]
Is an API server which does not have the permission required to successfully read and write secrets healthy?

**Comment by fedebongio** [comment]
@cheftako says he believes there is a workaround, disabling the KMS check in the manifest file.

**Comment by cheftako** [comment]
I'm assuming here you mean that the KAS start returning a not ok code to the Kubelet which restarts the KAS. 
(Cribbed from the kube-up manifest file) The following section of the manifest file asks that kubelet to send a liveness request which ignores kms providers 0 & 1 status. 

"livenessProbe": {
      "httpGet": {
        "scheme": "HTTPS",
        "host": "127.0.0.1",
        "port": 443,
        "path": "/livez?exclude=kms-provider-0&exclude=kms-provider-1"
      },
      "initialDelaySeconds": 45,
      "timeoutSeconds": 15
    },

**Comment by immutableT** [comment]
I think that it is the desired behavior for kube-apiserver to return !OK when it is unable to encrypt/decrypt secrets.
However, restarting kube-apiserver due to the failure of the livenessProbe (as pointed out by @cheftako) would not help. Hence, excluding kms-providers from the liveness check makes sense.

**Comment by alexanderKhaustov** [comment]
> Is an API server which does not have the permission required to successfully read and write secrets healthy?

This is of course open to interpretation but it seems that since API server works with many objects, not necessarily requiring secrets, it should be considered healthy, no?

**Comment by MAnyKey** [comment]
> I think that it is the desired behavior for kube-apiserver to return !OK when it is unable to encrypt/decrypt secrets.
However, restarting kube-apiserver due to the failure of the livenessProbe (as pointed out by @cheftako) would not help. Hence, excluding kms-providers from the liveness check makes sense.

There is a (not merged) pull request that addresses /livez not being OK because of failures of KMS providers' health checks:     https://github.com/kubernetes/kubernetes/pull/83588. I'm really looking forward to getting the code merged, but I'm not sure whether it is possible to "take over" the pull request. Or should I just create a new one?

**Comment by immutableT** [comment]
I agree with @MAnyKey it would be better to merge #83588 to avoid these type of issues in the future.
@liggitt @cheftako WDYT?

**Comment by liggitt** [comment]
> This is of course open to interpretation but it seems that since API server works with many objects, not necessarily requiring secrets, it should be considered healthy, no?

I think successful access to the configured storage is relevant to server health. Allowing KMS health to be excluded from healthz/livez if desired by the API server operator is fine, but defaulting the API server to reporting healthy when it cannot read/write secrets (including secrets that need to be read internally as part of service account token authentication) seems like a harmful default to me.

**Comment by cheftako** [comment]
> > This is of course open to interpretation but it seems that since API server works with many objects, not necessarily requiring secrets, it should be considered healthy, no?
> 
> I think successful access to the configured storage is relevant to server health. Allowing KMS health to be excluded from healthz/livez if desired by the API server operator is fine, but defaulting the API server to reporting healthy when it cannot read/write secrets (including secrets that need to be read internally as part of service account token authentication) seems like a harmful default to me.

I hate (and am not actually trying) to bring up the dreaded component-status, but I think we may be conflating concepts/mechanism here. To me healthz/livez is a signal to the kubelet that something is wrong. Specifically it indicates a failure which may be fixed by the kubelet restarting the process/container (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command). I do not believe that the KMS failures will in any way be helped by restarting the api-server/container. It seems like we need an alternate signal that the system is unhealthy (intended for some higher level entity than the kubelet).

**Comment by logicalhan** [comment]
I agree with what people are saying above, which I is summarized by the following statement:

`KMS health is not appropriate as a liveness check.`

However, I personally do believe that KMS health checks may be appropriate as a readiness check.

**Comment by logicalhan** [comment]
I also suspect that that is what @liggitt and @cheftako are saying.

**Comment by enj** [comment]
/reopen
/lifecycle frozen
/unassign immutableT 

This may be something we explore further as part of GA for KMS v2 (no specific plans yet)
