### ISSUE TITLE
defaulting to using `v1` apiVersion when getting a resource is unintuitive

### ISSUE THREAD

**Issue by ghostsquad** [kubernetes/kubernetes#93984]
this is a followup ticket after finding #71556 

It's not possible to have multiple resources of the same name with different apiVersions, so it shouldn't matter what apiVersion the client requested, it only matters the apiVersion of the object itself.

**What happened**:

I find it very unintuitive, and so far as a chicken-egg problem, that in order to run

```
kubectl get hpa.v2beta2.autoscaling foo
```

I must first know that the `foo` hpa is of the apiVersion `v2beta2`. However, just running `kubectl get hpa foo` will return `autoscaling/v1`

**What you expected to happen**:

running `kubectl get hpa` returns the representation (apiVersion) of the actual object.

**How to reproduce it (as minimally and precisely as possible)**:

deploy a resource such as an HPA using `autoscaling/v2beta2`, and then `kubectl get` that resource

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`): `Darwin A001643.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin`

**Comment by liggitt** [comment]
> running kubectl get hpa returns the representation (apiVersion) of the actual object.

An object can be returned in all of the versions served by the API server. For resources which have multiple versions available, the version stored in etcd has no connection to the version last used to create or update the object via the API. 

The server lists versions in preferred order in discovery (`/apis`) and when you use `kubectl get` with an ambiguous request (just a resource without specifying a specific version), kubectl prefers the first version listed in discovery which contains a resource with that name. 

Stable API versions (v1) are preferred over alpha and beta versions. 

> in order to run `kubectl get hpa.v2beta2.autoscaling foo`
I must first know that the foo hpa is of the apiVersion v2beta2

That's not accurate, you can request a v2beta2 representation of HPA foo regardless of what API version was used to create it. This allows API consumers to read in the version they understand, and API writers to write to an API version they understand, and the API server handles converting between those versions.

**Comment by ghostsquad** [comment]
I'm confused how this makes sense when apiVersions differ sometimes significantly?

**Comment by ghostsquad** [comment]
I was working with an HPA recently, and it was deployed as a v2beta2, which has a `metrics` key. When returned as a `v1` there is no metrics listed, and I was really concerned about what was going on.

Is there a way to find out what version of the object exists in `etc` so that you can get the _correct_ representation?

**Comment by liggitt** [comment]
> Is there a way to find out what version of the object exists in etc so that you can get the correct representation?

No, that info is not exposed to API consumers. 

If you have the same manifest you created the object from, you can do `kubectl get -f $file` and the same version that is in the manifest will be requested from the API server. 

If you don't have the manifest, and you care about metrics data if it is specified, you can explicitly request the v2beta2 version.

**Comment by ghostsquad** [comment]
so, you are saying that extra fields are persisted in an annotation in order to somehow do some sort of fuzzy forwards/backwards compatibility?

**Comment by ghostsquad** [comment]
This is interesting for sure, and I can kind of see how this works. I suppose the question then would be that the goal of newer apiVersions is such that behavior of an older version can be represented in the newer version, but not vice versa, but you still need the data not to be lost, hence the annotation?

**Comment by liggitt** [comment]
structural changes, field renames, stricter validation, or removal of deprecated allowed values for new objects are all things that can be done on API version boundaries
