### ISSUE TITLE
The CPU.Time is always set to Container StartTime in pod metrics

### ISSUE THREAD

**Issue by AbelHu** [kubernetes/kubernetes#93988]
**What happened**:
https://github.com/kubernetes/kubernetes/blob/55412b6af1764f8bc3d9dfa8f3bd29f1a65f4590/pkg/kubelet/stats/cri_stats_provider.go#L467-L479
CPU.Time is set to cs.StartTime but ps.Memory.Time is set to timestamp when collecting the memoryusage.

**What you expected to happen**:
CPU.Time is set to cs.CPU.Time

**How to reproduce it (as minimally and precisely as possible)**:
Check the code

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
master branch when creating this issue.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by qiutongs** [comment]
I am happy to take over this. 

/assign
