### ISSUE TITLE
Allow to configure cluster name in the kubeconfig generated using kubeadm command

### ISSUE THREAD

**Issue by prabhu43** [kubernetes/kubernetes#93991]
**What would you like to be added**:

Creation of kubeconfig using `kubeadm alpha kubeconfig user` command generated a kubeconfig. But it always has `kubernetes` as cluster name. But the cluster name of my cluster is different, configured via kubeadm config `ClusterConfiguration`. 
Hence, make the cluster name configurable from `kubeadm alpha kubeconfig user` command 

**Why is this needed**:

When we use this command to generate kubeconfig for multiple clusters with different cluster names, this kubeconfig has same cluster name `kubernetes`. This causes the confusion when merging all those kubeconfig files together.

**Comment by neolit123** [comment]
@prabhu43 
please open this same ticket in k/kubeadm where we track kubeadm feature requests/bugs.

thank you
/close
/area kubeadm

**Comment by prabhu43** [comment]
@neolit123 assigning this issue to area/kubeadm should be enough, right? 
what is the reason for closing this issue and creating new issue with same content?
