### ISSUE TITLE
Provide more explanation of new concepts and instructions

### ISSUE THREAD

**Issue by evasnee** [kubernetes/kubernetes#9399]
When a new concept is introduced, it should also be explained. Here are a few examples from the recent K8s Hackathon from new users:
         \* “First reference to createExternalLoadBalancer is confusing, this concept hasn't been introduced.  This section should be organized like: IF you are running locally: Do nothing, IF you are running on GCE and want your app to be externally visible, do X.  ELSE, etc..”
         \* “There are several terms that are not clear to new users: kubelets, minions, etc.”

Explain objects or commands that may be new or unknown to users so they can better understand how to do the task later on their own.
"’docker logs 26af6bd5ac12’  WTF is that random string?  Where do I run this from?” 

![image](https://cloud.githubusercontent.com/assets/11644912/8040306/32a408b8-0dc4-11e5-9887-d464ea49aa9b.png)
(https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook)

**Comment by brendandburns** [comment]
Here is the start of the PR:

https://github.com/GoogleCloudPlatform/kubernetes/pull/9653

But it needs to be adapted to use a Markdown parser.

**Comment by bgrant0607** [comment]
I think we should just do this manually for now. It requires a human to know where the most appropriate content is.

See also #11311.

cc @JanetKuo @caesarxuchao @krousey

**Comment by bgrant0607** [comment]
cc @RichieEscarez

**Comment by bgrant0607** [comment]
Docs have improved a lot
