### ISSUE TITLE
Readiness prob not restarting pod when it getting 503 http status

### ISSUE THREAD

**Issue by a2z-ice** [kubernetes/kubernetes#93994]
**What happened**:
My pod getting 503 http status but it is not being restart automatically.
**What you expected to happen**:
Since I have configured readyness prob with health check url. So I'm expecting when the status check failed it should restart the pod. My pod event shows me that it getting 503 http status but I do not know why the pod is not being restart.
**How to reproduce it (as minimally and precisely as possible)**:
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: survey-cport
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1

Do not configure any liveness porb
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
NAME                    STATUS   ROLES    AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
master.kubernetes.com   Ready    master   103d   v1.18.2   xxx.xxx.xxx.xxx   <none>        CentOS Linux 7 (Core)   3.10.0-1127.el7.x86_64   docker://19.3.8
node01.kubernetes.com   Ready    <none>   103d   v1.18.2    xxx.xxx.xxx.xxx   <none>        CentOS Linux 7 (Core)   3.10.0-1127.el7.x86_64   docker://19.3.8
node02.kubernetes.com   Ready    <none>   103d   v1.18.2    xxx.xxx.xxx.xxx   <none>        CentOS Linux 7 (Core)   3.10.0-1127.el7.x86_64   docker://19.3.8
```

- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
flannel
- Others:

**Comment by knight42** [comment]
@a2z-ice If you want to restart the pod when it returns 503, you should configure the livenessProbe https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request.

/remove-kind bug
/close

Feel free to reopen this issue if necessary.
