### ISSUE TITLE
unable to load a given KubeOneCluster object

### ISSUE THREAD

**Issue by manjeetsorout** [kubernetes/kubernetes#94001]
**What happened**:
i'm following this tutorial for the kubeone: https://dzone.com/articles/running-ha-kubernetes-clusters-on-aws-using-kubeon
but when i got this error when i ran the following command:
kubeone install config.yaml -t .
Error: failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: unable to read the given cluster configuration file: open ./kubeone.yaml: no such file or directory
failed to initialize State: failed to build state: failed to load cluster: unable to load a given KubeOneCluster object: unable to read the given cluster configuration file: open ./kubeone.yaml: no such file or directory
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
kubeone is not part of the kubernetes project.

please file a bug against them instaed https://github.com/kubermatic/kubeone
/close
