### ISSUE TITLE
Need REST API in scheduler to configure extender Instead of doing through manifest.yaml

### ISSUE THREAD

**Issue by mailhari** [kubernetes/kubernetes#94003]
Rephrasing my question:
I have written an extender and updated the /manifests/kube-scheduler.yaml. This works fine. 

(1)
What I am looking is : instead of updating the manifest, I am looking for a REST API that is running in scheduler through which I can register my extender?

(2)
Can this also be done on GKE?

-----my old description----
_To configure extender, I have to always modify manifest.yaml. I see there are some API. But I dont see any documentation on example particularly to what URL. I tried various URL but all resulted in 404. Since this is urgent, creating a issue. Put down the question in slack and haven't got any response. I know I will get, but cant wait any more.

1174  curl -v --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key  /etc/kubernetes/pki/apiserver-kubelet-client.key --cacert /etc/kubernetes/pki/ca.crt 'https://127.0.0.1:10259/apis/config/extender' -k | more
 1175  curl -v --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key  /etc/kubernetes/pki/apiserver-kubelet-client.key --cacert /etc/kubernetes/pki/ca.crt 'https://127.0.0.1:10259/apis/config/v1/extender' -k | more
 1176  curl -v --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key  /etc/kubernetes/pki/apiserver-kubelet-client.key --cacert /etc/kubernetes/pki/ca.crt 'https://127.0.0.1:10259/apis/config/v1alpha1/extender' -k | more
 1177  curl -v --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key  /etc/kubernetes/pki/apiserver-kubelet-client.key --cacert /etc/kubernetes/pki/ca.crt 'https://127.0.0.1:10259/apis/config/v1alpha2/extender' -k | more_

**Comment by mailhari** [comment]
/sig/scheduling

**Comment by Huang-Wei** [comment]
@mailhari the URL should start with the value configured in `extenders[*].urlPrefix`, and followed by `xyzVerb` specified in `extenders[*].xyzVerb`. The full supported fields are here:

https://github.com/kubernetes/kubernetes/blob/3b5aedcef43fa01538518ecbc7de369b27ecd191/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go#L265

So the full URL should be `${urlPrefix}/${xyzVerb}`.

**Comment by mailhari** [comment]
@Huang-Wei -
Updated my question. If you can share the sample that would be helpful.

**Comment by Huang-Wei** [comment]
> (1)
> What I am looking is : instead of updating the manifest, I am looking for a REST API that is running in scheduler through which I can register my extender?

So you want the extender can be dynamically discovered by scheduler? If so, vanilla Kubernetes doesn't support that.

> (2)
> Can this also be done on GKE?

cc/ @ahg-g @alculquicondor

**Comment by mailhari** [comment]
> So you want the extender can be dynamically discovered by scheduler? If so, vanilla Kubernetes doesn't support that.
Yes, exactly.

**Comment by alculquicondor** [comment]
We don't have any plans to support this at the moment.

Could you clarify your use case?

**Comment by mailhari** [comment]
GKE is the main usecase where we dont have a visibility of scheduler at all since GKE manages the control plane.

**Comment by alculquicondor** [comment]
Please clarify the underlying use case. What is it that you want to achieve?

**Comment by mailhari** [comment]
We wanted to register our extender with the scheduler which is running as part of GKE control plane. We dont have access to this control plane. So there is not way to configure the extender in GKE.

**Comment by alculquicondor** [comment]
Sorry @mailhari, I think you are misunderstanding my question. I want to know what is it that your extender is doing that you can't do through other mechanisms. Perhaps it's worth to include what you want as a core feature.

In general, extenders have reliability and performance concerns. You can also reach out to GKE support.

**Comment by mailhari** [comment]
@alculquicondor we are filtering the node items (predicate) and returning it back to the scheduler. Sure, I will reach out to GKE support as well.

Also - this v1alpha2 configuration is REST API or the args to kube-scheduler startup?
https://groups.google.com/g/kubernetes-announce/c/q1dnSDtRqQI/m/4iS7pyy5CgAJ
"Scheduler Extenders can now be configured in the v1alpha2 component config (#88768, @damemi) [SIG Release, Scheduling and Testing]"
