### ISSUE TITLE
Deprecate NodeLabel, ServiceAffinityand NodePreferAvoidPods from scheduler's CC api

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#94008]
NodeLabel and ServiceAffinity are what used to be called customer predicates and priorities. Since we have GA alternatives to those (NodeAffintiy and inter-pod affinity), I believe we should deprecate them from the plugin's API in CC before it gets to GA.

This is important because if CC makes it to GA, we can deprecate those plugins only by going to v2. 

Basically we should:
1) Deprecate their args from CC (requires going to v1Beta2)
2) Keep the logic, and allow configuring them only through the policy api
3) Remove the logic once the policy api is deprecated

/sig scheduling
/cc @mikedanese @Huang-Wei @alculquicondor

**Comment by hprateek43** [comment]
@ahg-g Can work on this. Let me know if we have finalized an approach around this.

**Comment by ahg-g** [comment]
@hprateek43 are you still interested in doing this one? for this release we need to 

- PR1: introduce v1beta2 
  - copy `https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-scheduler/config/v1beta1` to `https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-scheduler/config/v1beta2` and modify the package name to v1beta2 and update the [SchemeGroupVersion](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-scheduler/config/v1beta1/register.go#L28)
  - similarly copy `https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/apis/config/v1beta1` to `https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/apis/config/v1beta2` and make the necessary adjustments.
 - update https://github.com/kubernetes/kubernetes/blob/c87dd9c5121edc26f654f569002d69daee1e1fc4/pkg/scheduler/framework/runtime/framework.go#L330 to v1beta2
- PR2: remove `NodeLabelArgs` and `ServiceAffinityArgs` arguments from the new v1beta2 api

@alculquicondor I am assuming the above is good enough to block using those plugins in v1beta2 because conversion will fail if someone tries to use those plugins because the arg types don't exist and [defaulting](https://github.com/kubernetes/kubernetes/blob/c87dd9c5121edc26f654f569002d69daee1e1fc4/pkg/scheduler/framework/runtime/framework.go#L331) will return an error. Not the best experience may be, so let me know if there is a more explicit way.

**Comment by ahg-g** [comment]
actually you can do the two steps above in one PR.

**Comment by hprateek43** [comment]
I can pick this up

**Comment by ahg-g** [comment]
Sg, let's do it in separate PRs so that the second one include the deprecation notice in the release notes.

**Comment by alculquicondor** [comment]
This is what will happen if someone using v1beta2 tries to use one of the removed plugins, with the plan above.

1. During conversion, there are 2 possibilities:
  1. if there's a PluginConfig for it, it will be treated as out-of-tree and converted into runtime.Unknown.
  1. if there's no PluginConfig for it, `getPluginArgsOrDefault` returns nil.
1. The plugin instantiation would fail here: https://github.com/kubernetes/kubernetes/blob/c87dd9c5121edc26f654f569002d69daee1e1fc4/pkg/scheduler/framework/plugins/nodelabel/node_label.go#L59


I think we should put a `log.Warning` in the plugin instantiation, additionally to the plan above. If we want to be more extreme, we could produce an error here https://github.com/kubernetes/kubernetes/blob/c87dd9c5121edc26f654f569002d69daee1e1fc4/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go#L225, but I'm not sure if it's a good practice. I assume there wouldn't be out-of-tree plugins with the same name.

OTH, I wonder if this is the pattern of deprecation we want to go with all the time. Would it be possible to just fire a deprecation notice for a couple of versions and then remove it?

**Comment by alculquicondor** [comment]
Should we take this opportunity to deprecate "NodePreferAvoidPods"? Taints should cover this too.

**Comment by ahg-g** [comment]
yeah, lets deprecate `NodePreferAvoidPods` as well

**Comment by alculquicondor** [comment]
FYI @damemi, who asked about this in https://github.com/kubernetes/kubernetes/pull/92507#discussion_r500607005

**Comment by alculquicondor** [comment]
/retitle Deprecate NodeLabel, ServiceAffinityand NodePreferAvoidPods from scheduler's CC api

**Comment by alculquicondor** [comment]
Update to https://github.com/kubernetes/kubernetes/issues/94008#issuecomment-703680713

It actually won't work properly. Either v1beta1 plugins get broken or v1beta2 configurations don't get prevented from instantiating old plugins. I believe having `getPluginArgsOrDefault` do validation is a bad idea. We should be doing that during actual API validation (or conversion? although I'm not sure if api-approvers would agree with that).

@pancernik do you have any thoughts? I know pluginconfig validation is WIP, but we haven't really discussed plugin names validation.
