### ISSUE TITLE
Docker Hub's new policy for limiting image pulls

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#94018]
I see a discussion about the docker new policy https://github.com/cncf/foundation/issues/106 and this may affect Kubernetes e2e as well because we do run pull few images from docker hub [here](https://github.com/kubernetes/kubernetes/search?q=DockerLibraryRegistry+DockerGluster&unscoped_q=DockerLibraryRegistry+DockerGluster) in our tests.

This issue is for discussing how to tackle the new policy defined

Pricing link - https://hub.docker.com/pricing

**Comment by BretFisher** [comment]
more info on technicals of pull limits, with more blog/faq coming next week https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by sayanchowdhury** [comment]
👋🏽 Hello @mkumatag ! I'm from the Bug Triage Team! The code freeze for 1.20 release is starting November 12th which is about 3 weeks from now. As the issue is tagged for 1.20, is it still planned for this release?

**Comment by mkumatag** [comment]
> 👋🏽 Hello @mkumatag ! I'm from the Bug Triage Team! The code freeze for 1.20 release is starting November 12th which is about 3 weeks from now. As the issue is tagged for 1.20, is it still planned for this release?

I see a PR here for using the mirror instead of docker hub, hope that will fix the issue.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/19477

**Comment by erismaster** [comment]
Hi @mkumatag, Bug Triage here. I see that https://github.com/openshift/release/pull/13460 was merged. Should this issue be closed/resolved? If not, I can bump it to milestone 1.21. Please let me know, thanks!

**Comment by BenTheElder** [comment]
openshift project mitigtations don't apply here.

**Comment by erismaster** [comment]
@BenTheElder thanks, didn't catch that the PR was in openshift, not Kubernetes. Going to bump to 1.21. Thanks!

/milestone v1.21

**Comment by spiffxp** [comment]
/close
Closing this in favor of https://github.com/kubernetes/kubernetes/issues/97027
