### ISSUE TITLE
Pod scheduled event is unknown

### ISSUE THREAD

**Issue by gzlj** [kubernetes/kubernetes#94019]
**What happened**:
I deployed a deployment workload, and then I ran `kubectl describe pod` and I found Schedule event's timestamp is unknown:

Events:
  Type    Reason     Age        From               Message
  ----    ------         ----       ----               -------
  Normal  Scheduled      <unknown>  default-scheduler  Successfully assigned default/canary-6758c6b466-5qnnp to master03
  Normal  Pulled              3m14s      kubelet, master03  Container image "registry.aliyuncs.com/google_containers/echoserver:1.10" already present on machine
  Normal  Created         3m14s      kubelet, master03  Created container canary
  Normal  Started           3m14s      kubelet, master03  Started container canary

**What you expected to happen**:
Timestamp of pod scheduled event was supposed to be 3m14s.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Time in my host was Sat Aug 15 13:42:54 CST 2020 ( run date command )
Time in my kube-scheduler pod  was Sat Aug 15 05:42:54 UTC 2020  ( run date command )
 
**Environment**:
- Kubernetes version: v1.18.5
- Cloud provider or hardware configuration:  hardware configuration
- OS (e.g: `cat /etc/os-release`): centos 7.6
- Kernel (e.g. `uname -a`):  3.10.0-1062.18.1.el7.x86_64
- Others:
This kuberntes cluster is set up by kubeadm.

**Comment by gzlj** [comment]
Type    Reason             Age        From               Message

Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/canary-6758c6b466-5qnnp to master03
Normal  Pulled          3m14s      kubelet, master03  Container image "registry.aliyuncs.com/google_containers/echoserver:1.10" already present on machine
Normal  Created    3m14s      kubelet, master03  Created container canary
Normal  Started    3m14s      kubelet, master03  Started container canary

**Comment by liggitt** [comment]
@wojtek-t is this an artifact of the new events API? Do we need to update event describe?

**Comment by wojtek-t** [comment]
FTR - this doesn't seem to be a new bug - it's there since we migrated scheduler to new events, which was 1.17 IIRC

**Comment by wojtek-t** [comment]
@farah - will you be able to prepare a PR fixing this?

**Comment by farah** [comment]
Yes @wojtek-t , I'll have a submission this week if that's ok.

**Comment by yastij** [comment]
@wojtek-t - do we want to close #93663 and wait for the PR to fix the printers ?

**Comment by wojtek-t** [comment]
Yes - we probably should

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L4569

It has LastEventTimestamp.

Basically - what you need to do, is to:
- if series is non-nil, print series timestamp
- otherwise, if lastTimestamp is non-zero, print lastTimestamp
- otherwise print EventTime

**Comment by ingvagabund** [comment]
It's not just about internal printers. Also, when e.g. a pod is described, you get the following:
```
Name:         annotation-second-scheduler
Namespace:    zhouyt2
Events:
  Type    Reason          Age        From                                                 Message
  ----    ------          ----       ----                                                 -------
  Normal  Scheduled       <unknown>                                                       Successfully assigned zhouyt2/annotation-second-scheduler to ip-xxx
```

`k8s.io/kubectl/pkg/describe` has `DescribeEvents` functions that takes `corev1.EventList` which does not go through the internal printer. So, the fix needs to be duplicated in `DescribeEvents` as well.

**Comment by ingvagabund** [comment]
Fixed in 1.19 through https://github.com/kubernetes/kubernetes/pull/90227

**Comment by ingvagabund** [comment]
Fixes for the internal printer are already merged in master:
- lastTimestamp: https://github.com/kubernetes/kubernetes/pull/86557
- firstTimestamp: https://github.com/kubernetes/kubernetes/pull/89999

`firstTimestamp` is backport to 1.19 but not to 1.18
`lastTimestamp` is backported to both 1.19 and 1.18

**Comment by wojtek-t** [comment]
Thanks for opening https://github.com/kubernetes/kubernetes/pull/94226 - this will address this issue.

**Comment by ialidzhikov** [comment]
> Thanks for opening #94226 - this will address this issue.

Should we consider closing this issue as the referenced PR is merged?

**Comment by gzlj** [comment]
It's OK. Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes/kubernetes"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 上午6:23
收件人:&nbsp;"kubernetes/kubernetes"<kubernetes@noreply.github.com&gt;;
抄送:&nbsp;"纳尼"<1747441374@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kubernetes/kubernetes] Pod scheduled event is unknown (#94019)





  
Thanks for opening #94226 - this will address this issue.
  
Should we consider closing this issue as the referenced PR is merged?

**Comment by ialidzhikov** [comment]
I also created cherry-pick for `release-1.17` - ref https://github.com/kubernetes/kubernetes/pull/94923.

**Comment by ialidzhikov** [comment]
All related PRs are merged. Can we now close this issue?

**Comment by gzlj** [comment]
yes,thank you.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Ismail&amp;nbsp;Alidzhikov&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月14日(星期三) 凌晨5:11
收件人:&nbsp;&quot;kubernetes/kubernetes&quot;<kubernetes@noreply.github.com&gt;;
抄送:&nbsp;&quot;gzlj&quot;<1747441374@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kubernetes/kubernetes] Pod scheduled event is unknown (#94019)

**Comment by ialidzhikov** [comment]
@gzlj , can you then comment `/close` to close this issue?
