### ISSUE TITLE
Scheduler: Make number of threads configurable

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#94011]
**What would you like to be added**:

A field in kube-scheduler configuration API to set the number of threads. Currently, it's a constant with value 16.

https://github.com/kubernetes/kubernetes/blob/3b5aedcef43fa01538518ecbc7de369b27ecd191/pkg/scheduler/internal/parallelize/parallelism.go#L26

**Why is this needed**:

Some clusters might have master nodes with more CPUs available.

/sig scheduling
/good-first-issue

**Comment by alculquicondor** [comment]
/remove-good-first-issue

Let's get consensus first :)

**Comment by ahg-g** [comment]
I think it makes sense to parameterize this to allow using bigger masters and perhaps be more efficient on smaller ones.

**Comment by Huang-Wei** [comment]
I recalled we had a PR trying to change it dynamically according to the number of CPU cores, but unfortunately, resulted in performance downgrade, and we had to revert that.

Generally, it'd be good to be configurable, but it's necessary to raise a caveat that tunning this parameter may not be that simply by just specifying the number of CPU cores.

**Comment by alculquicondor** [comment]
That's interesting. Perhaps the automatic detection failed in some architectures?

Or was it really that matching number of CPUs is not the best? It could have been due to lock contention, but we have improved on that in 1.19. Also recall #89070

**Comment by adtac** [comment]
In the Makefile world, it's generally good practice to set parallelism to (number of cores - 1) so that the remaining free core could do other work. Could be worth giving that a shot to see if performance improves.

**Comment by Huang-Wei** [comment]
> I recalled we had a PR trying to change it dynamically according to the number of CPU cores, but unfortunately, resulted in performance downgrade, and we had to revert that.

Here is the one: #74907

**Comment by alculquicondor** [comment]
That's a good data point, thanks.

However, by making it configurable, vendors can choose what is best for their specific environments.

**Comment by ahg-g** [comment]
Yes, lets make it configurable and start testing given the improvements we made in reducing lock contention.

**Comment by vikkyomkar** [comment]
I would like to contribute to this issue. Pls let me know if its available to pick ?

**Comment by hprateek43** [comment]
@alculquicondor Can pick this up as have some bandwidth in the coming weeks. Let me know

**Comment by alculquicondor** [comment]
Feel free to pick this up, but note that master is still under freeze.

**Comment by Michaelborsellino** [comment]
Hi! I see that some users have been considering picking this issue up. Is anyone actively working on it? If not, I would love to take a look!

**Comment by alculquicondor** [comment]
Now that master is not in freeze, this can be taken. But please leave some time for contributors that volunteered earlier to respond.
