### ISSUE TITLE
Is there a viewer to lookup data inside etcd snapshot?

### ISSUE THREAD

**Issue by sridhav** [kubernetes/kubernetes#94014]
As etcd3 uses boltdb internally, is it possible if we can use boltdb browsers/any viewer to lookup the data inside the snapshot?

**Comment by neolit123** [comment]
hi,
see this: https://github.com/etcd-io/etcd/issues/7723
for more questions you can use #etcd on k8s slack for log a ticket in the etcd repository.

thanks
/close
