### ISSUE TITLE
compact failed: etcdserver: mvcc: database space exceeded

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#94029]
**What happened**:

After running the e2e network suite with the test `Should answer DNS query for maximum number of services per cluster` creating and deleting 100K service, the etcd database exceeds the data quota, and all the apiserver operations fails because of that.

> 2020-08-15T19:53:24.101951921Z stderr F I0815 19:53:24.101375       1 httplog.go:89] "HTTP" verb="PATCH" URI="/api/v1/nodes/kind-worker2/status?timeout=10s" latency="6.037477ms" userAgent="kubelet/v1.20.0 (linux/amd64) kubernetes/529c134" srcIP="172.18.0.3:54310" resp=500 statusStack="\ngoroutine 690276 [running]:\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc011c5c3f0, 0x1f4)\n\tstaging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:237 +0xcf\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc011c5c3f0, 0x1f4)\n\tstaging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:216 +0x35\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc01612a960, 0x1f4)\n\tstaging/src/k8s.io/apiserver/pkg/server/filters/timeout.go:228 +0xb2\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc012bea480, 0x1f4)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:503 +0x45\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc0020c2af0, 0xc001fdcf00, 0x59, 0x60, 0x7f534a58d7a0, 0xc00d899d60, 0x41)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:202 +0x1f7\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf.(*Serializer).doEncode(0xc000524140, 0x53257a0, 0xc00d899d60, 0x5314760, 0xc0020c2af0, 0x0, 0x4a0d23f)\n\tstaging/src/k8s.io/apimachinery/pkg/runtime/serializer/protobuf/protobuf.go:210 +0x5e5\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf.(*Serializer).Encode(0xc000524140, 0x53257a0, 0xc00d899d60, 0x5314760, 0xc0020c2af0, 0x3b88579, 0x6)\n\tstaging/src/k8s.io/apimachinery/pkg/runtime/serializer/protobuf/protobuf.go:167 +0x147\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc00d899e00, 0x53257a0, 0xc00d899d60, 0x5314760, 0xc0020c2af0, 0x0, 0x0)\n\tstaging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:228 +0x396\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc00d899e00, 0x53257a0, 0xc00d899d60, 0x5314760, 0xc0020c2af0, 0xc000524140, 0x532e060)\n\tstaging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x170\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x4a85389, 0x23, 0x7f534b0beda0, 0xc00d899e00, 0x5377b20, 0xc012ab4c88, 0xc01611bc00, 0x1f4, 0x53257a0, 0xc00d899d60)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:96 +0x12c\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x537aee0, 0xc000316480, 0x537b220, 0x74e7988, 0x0, 0x0, 0x4a0d23f, 0x2, 0x5377b20, 0xc012ab4c88, ...)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x572\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x5317900, 0xc01621b5e0, 0x537aee0, 0xc000316480, 0x0, 0x0, 0x4a0d23f, 0x2, 0x5377b20, 0xc012ab4c88, ...)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:270 +0x16f\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:89\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.PatchResource.func1(0x5377b20, 0xc012ab4c88, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:225 +0x1fff\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulPatchResource.func1(0xc012bea3f0, 0xc011c5c4d0)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/installer.go:1193 +0x99\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc012bea3f0, 0xc011c5c4d0)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:384 +0x282\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0015a0090, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tvendor/github.com/emicklei/go-restful/container.go:288 +0xa84\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)\n\tvendor/github.com/emicklei/go-restful/container.go:199\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4a24690, 0xe, 0xc0015a0090, 0xc000bf8000, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/server/handler.go:146 +0x539\nk8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc00156f630, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:121 +0x183\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc00a9161c0, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3db\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc002db2e70, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8c\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4a27b63, 0xf, 0xc004b3a630, 0xc002db2e70, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/server/handler.go:154 +0x74d\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x563\nnet/http.HandlerFunc.ServeHTTP(0xc00515abc0, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go:175 +0x4cf\nnet/http.HandlerFunc.ServeHTTP(0xc0071dc5a0, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x203d\nnet/http.HandlerFunc.ServeHTTP(0xc00515ac00, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bc00)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f534b492a80, 0xc012ab4c78, 0xc01611bb00)\n\tstaging/src/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x672\nnet/http.HandlerFunc.ServeHTTP(0xc007619720, 0x7f534b492a80, 0xc012ab4c78, 0xc01611bb00)\n\tGOROOT/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc013207080, 0xc0072d8620, 0x537e3e0, 0xc012ab4c78, 0xc01611bb00)\n\tstaging/src/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xb8\ncreated by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\n\tstaging/src/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cc\n" addedInfo="\nlogging error output: \"k8s\\x00\\n\\f\\n\\x02v1\\x12\\x06Status\\x12A\\n\\x06\\n\\x00\\x12\\x00\\x1a\\x00\\x12\\aFailure\\x1a)etcdserver: mvcc: database space exceeded\\\"\\x000\\xf4\\x03\\x1a\\x00\\\"\\x00\"\n"

when the apiserver tries to run the periodic compaction of etcd to free space, it fails, so it's not able to recover the situtation:

> compact.go:124] etcd: endpoint ([https://127.0.0.1:2379]) compact failed: etcdserver: mvcc: database space exceeded

etcd keeps restarting

> 2020-08-15T19:51:55.915839764Z stderr F 2020-08-15 19:51:55.915605 W | etcdserver/api/etcdhttp: /health error due to an alarm memberID:5989846029734297070 alarm:NOSPACE 
> 2020-08-15T19:52:33.618778603Z stderr F 2020-08-15 19:52:33.618609 N | pkg/osutil: received terminated signal, shutting down...

I think that is because of the healthcheck

> Aug 15 19:41:47 kind-control-plane kubelet[709]: E0815 19:41:47.852175     709 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-kind-control-plane.162b887017b19a8c", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-kind-control-plane", UID:"6758eea9919bd7866a6380c7b846e972", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Unhealthy", Message:"Liveness probe failed: HTTP probe failed with statuscode: 503", Source:v1.EventSource{Component:"kubelet", Host:"kind-control-plane"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc62c7ef28e8c8c, ext:1693775391433, loc:(*time.Location)(0x6c94ae0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc62c7ef28e8c8c, ext:1693775391433, loc:(*time.Location)(0x6c94ae0)}}, Count:1, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'etcdserver: mvcc: database space exceeded' (will not retry!)
> Aug 15 19:41:50 kind-control-plane kubelet[709]: E0815 19:41:50.485083     709 controller.go:178] failed to update node lease, error: etcdserver: mvcc: database space exceeded
> Aug 15 19:41:50 kind-control-plane kubelet[709]: E0815 19:41:50.488343     709 controller.go:178] failed to update node lease, error: etcdserver: mvcc: database space exceeded
> Aug 15 19:41:50 kind-control-plane kubelet[709]: E0815 19:41:50.505142     709 controller.go:178] failed to update node lease, error: etcdserver: mvcc: database space exceeded

**What you expected to happen**:

The cluster should be able to recover, compact etcd and free the space necessary (if possible)

**How to reproduce it (as minimally and precisely as possible)**:

It's happening in most of the jobs here https://k8s-testgrid.appspot.com/sig-network-kind#sig-network-kind,%20master

The logs snippets in the description are from this occurrence
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network/1294711996654030849

[apiserver logs](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network/1294711996654030849/artifacts/logs/kind-control-plane/pods/kube-system_kube-apiserver-kind-control-plane_24e9e0aaf1f895f6a3129f76c37beb1a/)
[etcd logs](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network/1294711996654030849/artifacts/logs/kind-control-plane/pods/kube-system_etcd-kind-control-plane_6758eea9919bd7866a6380c7b846e972/)
[kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-network/1294711996654030849/artifacts/logs/kind-control-plane/kubelet.log)

**Anything else we need to know?**:

After compacting etcd manually you are able to restore the situation.

There are several things here:

1. Is it possible that the health check don't act on the alarm `alarm:NOSPACE `, restarting etcd?  Restarting etcd makes the situation worse and it may miss a peridoc apiserver compaction.
2. Can the apiserver process the error  `etcdserver: mvcc: database space exceeded` and try a compaction, not waiting for the periodic compaction?
3. How the compact operations that should solve the problem fails with an error `database space exceeded` ?

**Comment by aojea** [comment]
/sig api
/sig scalability
/cc @neolit123 @wojtek-t @liggitt 
ccing people for each of the questions 1, 2 and 3

**Comment by liggitt** [comment]
cc @jingyih @jpbetz

**Comment by jingyih** [comment]
The compactor in the apiserver needs to persist key `compact_rev_key` before requesting compaction [1]. That explains why it fails to compact etcd when etcd already reaches its backend quota limit.

When etcd server raises no space alarm, usually we need to perform:
1. compact the key space
2. defrag etcd backend
3. disarm the alarm

IIUC, the compactor in the apiserver is not designed to perform all these steps. So manual intervention or some other automated script is needed.

cc @wojtek-t 

ref:
[1] https://github.com/kubernetes/kubernetes/blob/8f9f2fb2d64f81f1bd8aeb4056c4d01a21d2e910/staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go#L134

**Comment by liggitt** [comment]
> IIUC, the compactor in the apiserver is not designed to perform all these steps. So manual intervention or some other automated script is needed.

Is that automation set up in the kube-up and kubeadm configurations?

**Comment by wojtek-t** [comment]
> Is that automation set up in the kube-up and kubeadm configurations?

It is NOT in kube-up (I don't know about kubeadm).

That said - what quota to you set in kubeadm? We're bumping that in kube-up:
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L1668

**Comment by neolit123** [comment]
Kubeadm does not set this flag and uses defauls. For such a corner case the flag can be passed additionally.

**Comment by aojea** [comment]
> Kubeadm does not set this flag and uses defauls. For such a corner case the flag can be passed additionally.

my point is that kubeadm uses a healthcheck for etcd that makes restart the pod if the database space is exceeded, making the situation worse, don't know if you want to tackle this problem from the kubeadm side.

> Is that automation set up in the kube-up and kubeadm configurations?

It seems that apiserver runs the compactor every 5 minutes by default
https://github.com/kubernetes/kubernetes/blob/ebbbc57540f8467cc5b409bddbdad7dd5d4e435e/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go#L31

> That said - what quota to you set in kubeadm? We're bumping that in kube-up:

the quota is the default, that is 2G, i can bump it, but I don't know if kubernetes should handle this scenario. I'm fine with the 

``` the compactor in the apiserver is not designed to perform all these steps. So manual intervention or some other automated script is needed.``` solution, but is not clear to me if the compactor should work in this case

https://github.com/kubernetes/kubernetes/blob/8f9f2fb2d64f81f1bd8aeb4056c4d01a21d2e910/staging/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go#L67-L72

**Comment by neolit123** [comment]
On Aug 17, 2020 14:19, "Antonio Ojea" <notifications@github.com> wrote:
>>
>> Kubeadm does not set this flag and uses defauls. For such a corner case
the flag can be passed additionally.
>
> my point is that kubeadm uses a healthcheck for etcd that makes restart
the pod if the database space is exceeded, making the situation worse,
don't know if you want to tackle this problem from the kubeadm side.
>>

The healthcheck is a standard HTTP static Pod liveness probe at etcd's
health endpoint.

**Comment by jingyih** [comment]
>  I'm fine with the the compactor in the apiserver is not designed to perform all these steps. So manual intervention or some other automated script is needed. solution, but is not clear to me if the compactor should work in this case

I think it is better if the compactor can handle this situation. Currently I do not see how. The compactor needs to write a key to etcd (to persist the compact revision) before requesting the compaction. In the case where etcd is already full, the write will fail.

**Comment by neolit123** [comment]
Potentially, space for the key can be reserved. Userdata sz + compator key
sz = full

**Comment by jingyih** [comment]
> Potentially, space for the key can be reserved. Userdata sz + compator key sz = full

Potentially this could a feature request to etcd. Currently any key sent by etcd client (which is embeded in apiserver) is considered user key.

**Comment by neolit123** [comment]
yep, i meant this can be in etcd.

**Comment by wojtek-t** [comment]
Putting aside the discussion about recovering from that state for a moment,
I would like to understand what is happening that we can fill up 2GB DB. IIUC, this is running in small cluster (<10 nodes) - it's not that easy to write that much data. What is happening in this test?

**Comment by aojea** [comment]
The cluster is just 2 nodes (is using KIND) and the test is creating 10000 services to check its dns records
https://github.com/kubernetes/kubernetes/blob/97c5f1f7632f2d349303515830be76f6c1084b19/test/e2e/network/dns_scale_records.go#L54-L55

After defrag it goes down to 370M, that is the size I use to see in KIND clusters

```
ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --cacert=/etc/kubernetes/pki/etcd/ca.crt defrag                                                                                     
Finished defragmenting etcd member[https://127.0.0.1:2379]
root@kind-control-plane:~# du -sh /var/lib/etcd/member/
370M    /var/lib/etcd/member/
```

**Comment by BenTheElder** [comment]
FWIW I actually see 430M for a clean cluster with a single node on 1.8.8
It's still a lot to jump from that to 2GB...

@neolit123 :

> The healthcheck is a standard HTTP static Pod liveness probe at etcd's
> health endpoint.

That may be so, but if it is making the situation worse we should reconsider.

GCE is increasing this quota even in prod (and doesn't appear to have a different setting in test config), I'd be inclined to suggest that the kubeadm default should be raised.
If kubeadm is against doing this, kind at least may do it.

etcd has users other than Kubernetes, it doesn't seem like we should demand etcd's defaults be 100% perfect for Kubernetes.

> I would like to understand what is happening that we can fill up 2GB DB. IIUC, this is running in small cluster (<10 nodes) - it's not that easy to write that much data. What is happening in this test?

+1 ...

2GB - 370MB ~= 1.63GB, even if we assume some overhead and say maybe 1.4GB is from this test, that's 140kb/service, which seems like a lot?

**Comment by jingyih** [comment]
> After defrag it goes down to 370M

If apiserver writes and deletes (deletes are usually due to compaction) frequently in etcd, etcd may have a lot of internal fragmentation.

**Comment by liggitt** [comment]
> If apiserver writes and deletes (deletes are usually due to compaction) frequently

can we get an apiserver request log at v4 for the test run? I'd really like to make sure something like the endpoints or endpointslice controller isn't churning unexpectedly on this scenario

**Comment by BenTheElder** [comment]
logs _should_ be v4 by default in kind runs now, I think you have one here
at
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-network/1295347935625613312/artifacts/logs/kind-control-plane/containers/kube-apiserver-kind-control-plane_kube-system_kube-apiserver-fa7708048512519ca040be371c5000c3185fffb1b1b268d52f4273291af5e5a9.log

(https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20master appears
to run "Should answer DNS query for maximum number of services per cluster")

**Comment by aojea** [comment]
> If apiserver writes and deletes (deletes are usually due to compaction) frequently in etcd, etcd may have a lot of internal fragmentation.

I have one suspect, I think that is caused by the bitmap used to store the cluster ips, under the key `/registry/ranges/serviceips`, related discussion here https://github.com/kubernetes/enhancements/pull/1881#issuecomment-671758404

I don't know how to get the size of the key value, so I did the following

```
root@kind-control-plane:~# ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --cacert=/etc/kubernetes/pki/etcd/ca.crt get /registry/ranges/serviceips > serviceips.bin                                                           
root@kind-control-plane:~# ls -alh serviceips.bin
-rw-r--r-- 1 root root 129K Aug 17 22:28 serviceips.bin
```

the result seems correct, because I have configured a /12 range `10.96.0.0/12` for the service IP that is a 2^20 bitmap.

Each new service will create a new revision of that key to update the bitmap.

IIUC how etcd works, 129k per the 10000 services, if no compaction runs during that time, can be a a lot of space.

When the database space is exceeded, the health check start to restart etcd and the compactor can not persist the key as explained here https://github.com/kubernetes/kubernetes/issues/94029#issuecomment-674494952

If the compactor runs before the database space is exceeded there is no problem, and the cluster works

**Comment by wojtek-t** [comment]
> the result seems correct, because I have configured a /12 range 10.96.0.0/12 for the service IP that is a 2^20 bitmap.

OK - that explains it. Setting /12 for services sounds a lot. I doubt we would be even able to support 2^20 services (we don't test more than O(10k), so roughly two orders of magnitude less.

@aojea - can you please rerun the experiment by setting say /16 or /18 for services cidr and grab the data then just to fully confirm it?

**Comment by aojea** [comment]
> @aojea - can you please rerun the experiment by setting say /16 or /18 for services cidr and grab the data then just to fully confirm it?

it looks much better :smile: 
```
root@kind-control-plane:/# du -sh /var/lib/etcd/member/
344M    /var/lib/etcd/member/
```

**Comment by BenTheElder** [comment]
Worth noting that [kubeadm init] --service-cidr defaults to 10.96.0.0/12

[kubeadm init]: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Comment by knight42** [comment]
@BenTheElder Looks like it is reasonable to change the default value to `10.96.0.0/16`?

**Comment by neolit123** [comment]
Unless dynamic service range configuration is supported, I am pretty sure
it would be a breaking change resulting in out of range services for users
uprading to a new KCM manifest, that did not specify an explicit range at
cluster creation. The change may require special casing around upgrade.

**Comment by BenTheElder** [comment]
So we moved the _kind_ default to `10.96.0.0/16` which should allow us to run these tests, and doesn't have the same considerations for breaking change as kubeadm currently.

The other aspects of this still need work IMHO, it seems like it would be good for the API server to compact earlier than scheduled in this case (watching the growth or triggered on the alarm?), at minimum.

**Comment by jingyih** [comment]
> The other aspects of this still need work IMHO, it seems like it would be good for the API server to compact earlier than scheduled in this case (watching the growth or triggered on the alarm?), at minimum.

While I agree with this, we need to be careful about the triggering condition. The current compactor keeps 5 mins of history by default. If a cluster is legitimately using a lot of space which is reaching the quota limit, triggering compaction repeatedly would cause all watches to fall out of history window and start relisting. What do you think? @wojtek-t

**Comment by wojtek-t** [comment]
> While I agree with this, we need to be careful about the triggering condition. The current compactor keeps 5 mins of history by default. If a cluster is legitimately using a lot of space which is reaching the quota limit, triggering compaction repeatedly would cause all watches to fall out of history window and start relisting. What do you think? @wojtek-t

That is problem if you're watching directly from etcd. In general, we're using watchcache, and compation doesn't compact stuff in watchcache. So it's not as bad as it seems. There are problems on kube-apiserver reboots, but those will get addressed once https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption is implemented (I'm targeting alpha in 1.20).
There are other ways we can try mitigating too (e.g. always try to send bookmarks right before compaction).

I think we have ways to do that in reasonable way without much significant effort.

**Comment by Deepak1100** [comment]
i am also facing the same issue. I didn't see any event in my cluster from multiple days after debugging it's related to etcd mvcc space.
etcd disk usage is only 6%
```
E0225 13:06:59.662372       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0x8, desc:"etcdserver: mvcc: database space exceeded"}
E0225 13:06:59.996952       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0x8, desc:"etcdserver: mvcc: database space exceeded"}
E0225 13:07:00.060330       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0x8, desc:"etcdserver: mvcc: database space exceeded"}
```

**Comment by djsly** [comment]
we were affected by this error twice this week across two different clusters. 

the first occurrence, there were around 140 deployments that received a `kubectl rollout restart` command affecting ~6000 pods, it took ~30mins until we started getting the etcdserver full error

the second occurrence, was a single rollout restart of a deployment with 1800 replicas. same thing ~15/30min in and etcdserver went down. 

Note also, that when we saw this issue, all kubelet almost became into a bad state with watchlist and needed a restart. they were causing pods in terminating state to never finish. 


```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jpbetz** [comment]
> 1. Is it possible that the health check don't act on the alarm `alarm:NOSPACE `, restarting etcd?  Restarting etcd makes the situation worse and it may miss a peridoc apiserver compaction.

I agree that restarting etcd does not help in this case. And I suspect that, in general, it's better to not restart etcd due to health check failures, but I don't have the data to prove that, so I'm hesitant to suggest disabling the liveness probe.  I'd be very interesting in data anyone is able to gather about this.

> 2. Can the apiserver process the error  `etcdserver: mvcc: database space exceeded` and try a compaction, not waiting for the periodic compaction?

This might be best to discuss at etcd.io/etcd and not at kubernetes/kubernetes, but etcd _compaction_ doesn't actually reduce the storage file size, it just frees pages within it for reuse. _defragmentation_ is the etcd operation that reduces the storage file size.  My preference would be we teach etcd to perform defragmentation automatically rather than waiting for an administrator to request it. I thing etcd is much better positioned thant the apiserver to decide when to do defragmentation. 

> 3. How the compact operations that should solve the problem fails with an error `database space exceeded` ?

See above about difference between _compaction_ and _defragmentation_.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

> My preference would be we teach etcd to perform defragmentation automatically rather than waiting for an administrator to request it. I think etcd is much better positioned than the apiserver to decide when to do defragmentation, so I'd rather invest in improving etcd.

Is this tracked anywhere in the etcd repo currently?

**Comment by BenTheElder** [comment]
same question before letting this close https://github.com/kubernetes/kubernetes/issues/94029#issuecomment-892220009
/remove-lifecycle stale

**Comment by jingyih** [comment]
cc @serathius

**Comment by zhangguanzhang** [comment]
I think this problem should be solved by kube-apiserver. After all, when etcd database is full, etcdctl can compress it. K8s' etcd is only used by kube-apiserver, so kube-apiserver should handle this problem.

**Comment by serathius** [comment]
Clarification, I think the issue with K8s getting stuck on `database space exceeded` is not because of etcd, but due to how K8s handles deletes and compaction. On pure etcd are still able to delete, compact to reduce size of database in use, and then defrag and disarm alarm to unlock writes. The improvements to compaction were discussed in https://github.com/kubernetes/kubernetes/issues/80513
