### ISSUE TITLE
Rate limiter in APIServer needs to take into account watch, exec, proxy, and logs

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#9403]
The rate limiter in the apiserver is impacted by #8337 and also by the addition of exec/proxy/logs.  Endpoints which hold long running connections need to be independently rate limited.  We probably need three buckets:
1. watch - required for intraserver components
2. exec/proxy/logs - used by clients and long running
3. everything else

https://github.com/GoogleCloudPlatform/kubernetes/issues/8337#issuecomment-109781954

**Comment by davidopp** [comment]
#8337 is already marked post-1.0 so transitively this is post-1.0.

**Comment by liggitt** [comment]
#9840 is related... API server rate-limiting has no effect currently

**Comment by liggitt** [comment]
LIST (and soon GET) requests have the potential to specify a future resourceVersion and become long-running
