### ISSUE TITLE
Kubernetes cordon own Node (access API from worker nodes)

### ISSUE THREAD

**Issue by erkum** [kubernetes/kubernetes#94033]
Hi,
I know this is the wrong place but I dont know what else to do I already tried on StackOverflow.
My Workernodes are located in an Office. 
When a user logs in, all running pods on this Node should get evicted and the Node cordoned and when he logs out the Node should become schedulable again.
I got the eviction part working so far with a Python script, the Kubernetes Library, a Role in the corresponding Namespace and a Service Account. 

``` python
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint
import os
import sys


def evict(configuration):
    with kubernetes.client.ApiClient(configuration) as api_client:
        # api_instance = kubernetes.client.AdmissionregistrationApi(api_client)
        v1api = kubernetes.client.CoreV1Api(api_client)
        hostname = os.uname()[1]

        try:
            api_response = v1api.list_namespaced_pod("jhub", label_selector="component=singleuser-server")

            for i in api_response.items:
                if i.spec.node_name == hostname:
                    eviction_body = kubernetes.client.models.v1beta1_eviction.V1beta1Eviction(
                        metadata=kubernetes.client.V1ObjectMeta(name=i.metadata.name, namespace=i.metadata.namespace))

                    api_response = v1api.create_namespaced_pod_eviction(name=i.metadata.name,
                                                                        namespace=i.metadata.namespace, body=eviction_body)
            cordon_body = {
                "spec": {
                    "unschedulable": True
                }
            }
            api_response = v1api.patch_node(hostname, body=cordon_body)
            pprint(api_response)
        except ApiException as e:
            print("Exception when calling Api\n%s" % e)


def join(configuration):
    with kubernetes.client.ApiClient(configuration) as api_client:
        v1api = kubernetes.client.CoreV1Api(api_client)
        hostname = os.uname()[1]
        cordon_body = {
            "spec": {
                "unschedulable": False
            }
        }        
        api_response = v1api.patch_node(hostname, body=cordon_body)
        pprint(api_response)

def main(arg):
    configuration = kubernetes.client.Configuration()
    configuration.verify_ssl = False
    configuration.api_key['authorization'] = '<Token>'
    configuration.api_key_prefix['authorization'] = 'Bearer'

    # Defining host is optional and default to http://localhost
    configuration.host = "https://192.168.2.209:6443"

    if arg == "evict":
        evict(configuration)
    elif arg == "join":
        join(configuration)


if __name__ == '__main__':
    if len(sys.argv) == 2:
        if sys.argv[1] in ("evict", "join"):
            main(sys.argv[1])
        else:
            raise ValueError("Unknown Argument: valid arguments are 'join' and 'evict'")
    else:
        raise ValueError("Only one argument accepted")
``` 

But here is my problem I want to grant least privileges. Since this Service Account can only access Pods inside the namespace I cant cordon this node to prevent rescheduling.  

I read about the [roles][1] which would have those permissions.
But it said here that I should use [Node Authorizer][2] and [NodeRestriction admission plugin][3].  
According to the description this is exactly what I am looking for.  
My problem here is that I don't know how to tell Kubernetes that.  
Is this even suitable for this situation? If yes how am I supposed to do this? How am I even supposed to execute kubectl commands from a worker node?

Thanks in advance :)

  [1]: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#core-component-roles
  [2]: https://kubernetes.io/docs/reference/access-authn-authz/node/
  [3]: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction

**Comment by neolit123** [comment]
hi,

> I know this is the wrong place but I dont know what else to do I already tried on StackOverflow.

yep, we try to keep this issue tracker for bugs/features as much as possible.

instead you can try slack #kuberentes-users or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> Since this Service Account can only access Pods inside the namespace I cant cordon this node to prevent rescheduling.

you'd need a service account that can do that.

> But it said here that I should use Node Authorizer and NodeRestriction admission plugin.

this talks about `system:node` being there for compatibility only.
the cluster admin could create custom RBAC cluster roles / role bindings to grant you access to nodes, but not to much else (re: "least privileges").
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

> How am I even supposed to execute kubectl commands from a worker node?

you can execute kubectl from anywhere as long as you are giving it a kubeconfig file that has the right privileges (e.g. admin).
same goes for creating a client programmatically.

e.g. this guide covers some details
http://docs.shippable.com/deploy/tutorial/create-kubeconfig-for-self-hosted-kubernetes-cluster/

**Comment by neolit123** [comment]
> yep, we try to keep this issue tracker for bugs/features as much as possible.

/close
