### ISSUE TITLE
k8s create terminaling type pods in large Numbers

### ISSUE THREAD

**Issue by tangmingming1** [kubernetes/kubernetes#94048]
A K8S cluster is deployed，rocketmq is deployed to a node,When this node dies，k8s create terminaling type pods all the time，at least a few hundred thousand

System logs show too few pod ,and create pods all the time

**Comment by tangmingming1** [comment]
kind/bug

**Comment by tangmingming1** [comment]
sig/cluster-cheduling

**Comment by neolit123** [comment]
please re-open once you provide more details about your setup, k8s version and all the details in the issue template
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

/remove-sig node cluster-lifecycle
/close
