### ISSUE TITLE
ci-cloud-provider-gcp-conformance-latest failing with mismatched test / server version

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#94051]
**Which jobs are failing**:

ci-cloud-provider-gcp-conformance-latest

**Which test(s) are failing**:

Tests of v1.19 APIs (csr, ingress, ingressclass)

* This is the number 2 failure in the sig-auth triage dashboard https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=auth#149b717fc8f74bbfb782

**Since when has it been failing**:

https://testgrid.k8s.io/provider-gcp-periodics#Conformance%20-%20Cloud%20Provider%20GCP%20-%20master&width=5

Since the job was added on 8/8 in https://github.com/kubernetes/test-infra/pull/18714#issuecomment-674904969

**Testgrid link**:

**Reason for failure**:

Looking at the API server log, the server is running `v1.18.0`, but the tests are running 1.19/master code

```
I0817 06:31:38.334252       1 server.go:153] Version: v1.18.0
```

/assign @michaelmdresser @amwat 
/sig cloud-provider
/area gcp

**Comment by liggitt** [comment]
cc @cheftako

**Comment by michaelmdresser** [comment]
I suspect this is because the kubetest2 Ginkgo tester isn't correctly matching the test package version with the version being built. See https://github.com/kubernetes-sigs/kubetest2/blob/master/pkg/testers/ginkgo/package.go#L24. Kubetest2 by default acquires the latest test package published for k/k.

**Comment by BenTheElder** [comment]
we could default to matching the API server version if not specified.
in the meantime we should specify it in this job @amwat

**Comment by amwat** [comment]
yeah +1 to the defaulting behavior. but we probably want to run a cluster with latest binaries in that job instead of downgrading the tests :)

**Comment by amwat** [comment]
also ref: https://github.com/kubernetes/test-infra/issues/18865

**Comment by amwat** [comment]
fixed with: https://github.com/kubernetes/test-infra/pull/18880
https://testgrid.k8s.io/provider-gcp-periodics#Conformance%20-%20Cloud%20Provider%20GCP%20-%20master

/close
