### ISSUE TITLE
Kubectl: rethink handling (and surfacing) of errors in the resource visitor loop

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#9405]
> We probably need to queue an issue to look at side loaded errors in visitor and see if there's an alternative to the way we have to aggressively continue loops even when errors happen (because someone might want to continueOnError). It might be a change to visitor to allow it to accept an error, like Go's path walker.

From @smarterclayton https://github.com/GoogleCloudPlatform/kubernetes/pull/9357#issuecomment-109600305

**Comment by feihujiang** [comment]
@mikedanese Yes, we should continue loops even when errors happen. We could collect errors, put them into errs.ErrorList{}, then aggregate errors, finally show  a user friendly aggregated errors . I wonder if any other has already started working on this? If not, I would like to start on it then!

**Comment by mikedanese** [comment]
@feihujiang No one is currently working on this.

**Comment by feihujiang** [comment]
@mikedanese OK, I 'm currently working on this now.

**Comment by feihujiang** [comment]
Sorry for the delay, I'll finish it as quickly as I can

**Comment by feihujiang** [comment]
@mikedanese #9707 just solves the DirectoryVisitor's continue loops. Now I'm thinking  a change to visitor to allow it to accept an error, like Go's path walker.
