### ISSUE TITLE
I cant do clustering kubernetes [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.

### ISSUE THREAD

**Issue by lokeshjava28** [kubernetes/kubernetes#94067]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  Kubernetes version: v1.18.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`): root
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> I cant do clustering kubernetes [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.

the warning is a bit misleading and can be ignored. i think we removed it in 1.19.

see here:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#JoinConfiguration


if you pass `controlPlane: {}` in your `JoinConfiguration` it will act the same as the `--control-plane` flag on `kubeadm join`.
it's recommended to not mix flags and config, so better use "--config" only.

for more questions use #kubeadm on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
