### ISSUE TITLE
OpenApi-Spec response schema ref is incorrect for deleting a v1 batch job

### ISSUE THREAD

**Issue by gokussx4** [kubernetes/kubernetes#94064]
**What happened**:
Deleting a job returns a job object instead of a v1 status object.

**What you expected to happen**:
I expected a v1 status object to be returned about the delete of the job per the k8s api documentation and spec.

**How to reproduce it (as minimally and precisely as possible)**:
Delete any namespaced job restfully and it will return the job you are attempting to delete instead of a v1 status.

**Anything else we need to know?**:
This impacts the generated clients based on the open-api spec.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.5
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): Windows 10
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yue9944882** [comment]
ref https://github.com/kubernetes/kubernetes/issues/79472 the deletion api returns the deleted object on graceful deletion, however multi-returning is not supported in OAS2 spec.. this should be addressed by providing a dedicated OAS3 publishing endpoint

**Comment by roycaihw** [comment]
Openapi v3 KEP: https://github.com/kubernetes/enhancements/pull/1263

Moving to v3 is the right way to fix the spec. In the meantime we could improve our documentation. Is there any place that we can document this behavior?
