### ISSUE TITLE
Kubernetes API server response timeout

### ISSUE THREAD

**Issue by csandiri11** [kubernetes/kubernetes#94063]
Seeing some of our Workflow jobs are getting failed with connection timeout error. We are using Argo Workflow manager to run jobs. we are observing Argo is losing connectivity to its workflows and our inter dependent workflow schema is getting failed with the below errors. so when I checked Kubernetes API server logs I am seeing these errors. is there any way I can increase any timeout settings for Kubernetes API server non running jobs?

Errors:
1 status.go:71] apiserver received an error that is not an metav1.Status: &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc095d6de90), Addr:(*net.TCPAddr)(0xc095d6dec0), Err:(*os.SyscallError)(0xc0287c4d00)}
E0817 17:14:46.575773       1 status.go:71] apiserver received an error that is not an metav1.Status: &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc07d555530), Addr:(*net.TCPAddr)(0xc07d555560), Err:(*os.SyscallError)(0xc0be7c70e0)}
E0817 17:14:46.576855       1 status.go:71] apiserver received an error that is not an metav1.Status: &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc07c5a03f0), Addr:(*net.TCPAddr)(0xc07c5a0420), Err:(*os.SyscallError)(0xc07c7454e0)}
E0817 17:15:28.402137       1 status.go:71] apiserver received an error that is not an metav1.Status: &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc09013ea20), Addr:(*net.TCPAddr)(0xc09013ea50), Err:(*os.SyscallError)(0xc0cd00f520)}
E0817 17:23:48.779008       1 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)

Version:
```

Client Version: v1.17.2
Server Version: v1.17.2
```

Host OS:
`Centos 7.7`

CNI:
`Weave`

Thanks,
CS

**Comment by yliaog** [comment]
it looks that the apiserver is overloaded, which may be caused by too many Argo workflow CRDs, could you 1) check how many Argo CRs? 2) reduce # of CRs 3) move the apiserver to a more powerful machine, i.e. more RAMs, CPUs

**Comment by csandiri11** [comment]
thanks Yliaog. We observing the load on API server is normal. the only difference we are seeing b/w successful jobs vs failed jobs is the job nature where some jobs takes usually 6-7 Hrs. to complete and during this time Argo is not able to communicate to K8 Api server and pods getting failed. eventually job is ending up failed. Now is there anyway I increase timeout setting on Kubernetes API server.

**Comment by yliaog** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

has flags for timeout setting.

it would be helpful to understand what API requests are timing out, and why, before adjusting the timeout value
