### ISSUE TITLE
configmaps "kubelet-config-1.xx.x" is forbidden

### ISSUE THREAD

**Issue by KubeLouis** [kubernetes/kubernetes#94065]
Hello here is a question on kubernetes installation
I deleted a master first then I'd like to make it master again, but failed
the version of kubelet and kubeadm is 1.13.10(a bit old version that no doc in kubernetes.io)
after I got token then I tried to join the cluster as a master, the following error report is shown

**[preflight] Running pre-flight checks
        [WARNING Hostname]: hostname "m28" could not be reached
        [WARNING Hostname]: hostname "m28": lookup m28 on 183.60.82.98:53: no such host
[discovery] Trying to connect to API Server "172.17.0.24:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://172.17.0.24:6443"
[discovery] Requesting info from "https://172.17.0.24:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "172.17.0.24:6443"
[discovery] Successfully established connection with API Server "172.17.0.24:6443"
[join] Reading configuration from the cluster...
[join] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
unable to fetch the kubeadm-config ConfigMap: failed to get component configs: configmaps "kubelet-config-1.13" is forbidden: User "system:bootstrap:dxa9uk" cannot get resource "configmaps" in API group "" in the namespace "kube-system"**

that is too bad who can help me?
plus: no association with the version because they are all 1.13.10

**Comment by neolit123** [comment]
> unable to fetch the kubeadm-config ConfigMap: failed to get component configs: configmaps "kubelet-config-1.13" is forbidden: User "system:bootstrap:dxa9uk" cannot get resource "configmaps" in API group "" in the namespace "kube-system"

this means that the bootstrap token was not granted access to the kubelet configuration stored in kubelet-config-1.13.
this can happen if someone tempered with the RBAC for the bootstrap token.

try creating a new token, using `kubeadm token ...` and joining again.
also this version is no longer in support by the kubeadm team and you need to upgrade to 1.17 soon with the release of 1.19.

for support questions please use #kubeadm on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Comment by KubeLouis** [comment]
thx very much!
