### ISSUE TITLE
The node was low on resource: ephemeral-storage，I also encountered the same problem, the disk space is also very sufficient, please help us to see

### ISSUE THREAD

**Issue by jofia** [kubernetes/kubernetes#94073]
I also encountered the same problem, the disk space is also very sufficient, please help us to see
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: ephemeral-storage. Container ebaogi-bff-app was using 34260Ki, which exceeds its request of 0. 
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/ebaogi-bff-app-955968dbb

Name:           ebaogi-report-app-5dbc89ff58-zqsn2
Namespace:      ebaogi
Priority:       0
Node:           xen15-142/
Start Time:     Thu, 09 Jul 2020 10:20:16 +0800
Labels:         app=ebaogi-report-app
                deploytime=2020-07-09-10-18-59-1594261139
                pod-template-hash=5dbc89ff58
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: ephemeral-storage. Container ebaogi-report-app was using 108488Ki, which exceeds its request of 0.

_Originally posted by @jofia in https://github.com/kubernetes/kubernetes/issues/91600#issuecomment-675294896_

**Comment by jofia** [comment]
[root@xen16-23 ~]# kk get nodes
NAME                    STATUS   ROLES    AGE    VERSION
xen15-142               Ready    <none>   189d   v1.16.2

**Comment by neolit123** [comment]
hi, for support questions please use the k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

this issue tracker is for feature requests and bugs (if confirmed).

also you should soon upgrade to 1.17 as 1.16 is going out of support, possibly late august with the release of 1.19.

/triage support
/sig storage

**Comment by jofia** [comment]
thanks
