### ISSUE TITLE
exec-type liveness or readiness probes ignore timeout

### ISSUE THREAD

**Issue by jgoeres** [kubernetes/kubernetes#94080]
When defining a liveness or readiness probe of type exec with a timeout, like this

    readinessProbe:
      exec:
        command:
        - "curl"
        - "-f"
        - "localhost:8080/slow?timeInSecs=10"
      initialDelaySeconds: 5
      periodSeconds: 3
      timeoutSeconds: 1

where the response is taking longer than the defined timeoutSeconds, the pod is still considered running (in case of a liveness probe) resp. resp. reaches ready state (in case of a readiness probe).
What I would expect is that the command is aborted after the timeout is reached and that the probe is considered failed.
Instead, what I am observing when I exec into the container is that the readinessProbe command "hangs" for ten seconds, then completes 

    Every 0.2s: ps aux     2020-08-18 11:35:03
    
    PID   USER     TIME  COMMAND
        1 root      0:07 /opt/openjdk-16/bin/java -jar /slow-1.0.0-exec.jar
       50 root      0:00 bash
       62 root      0:00 watch -d -n 0.2 ps aux
     5368 root      0:00 curl -f localhost:8080/slow?timeInSecs=10
     5386 root      0:00 ps aux

and the pod reaches ready state:

    slow-deployment-5bbc7f667d-w2lgr   1/1     Running   0          14m

This was first observed on an EKS cluster (v1.15.11-eks), but I also tried various other Kubernetes versions via minikube, e.g.,  1.16.14, 1.17.11, and 1.18.8, same behavior.

Attached you can find a YAML file (slow-deployment.zip) with a sample deployment, a ZIP with the very simple SpringBoot application (app-src.zip), and a ZIP with a Dockerfile (slow-docker.zip, plus a shell script which runs the same healthcheck).
For convenience, the image is also available on Dockerhub.

Note that the Dockerfile also defines a Docker healthcheck. Running this container on plain Docker gives the expected behavior:

    $ docker ps
    CONTAINER ID        IMAGE        COMMAND                  CREATED         STATUS                   
    e58e15f84fca        slow:1.0.0   "/opt/openjdk-16/bin…"   51 seconds ago  Up 22 seconds (unhealthy)

[app-src.zip](https://github.com/kubernetes/kubernetes/files/5090090/app-src.zip)
[slow-docker.zip](https://github.com/kubernetes/kubernetes/files/5090062/slow-docker.zip)
[slow-deployment.zip](https://github.com/kubernetes/kubernetes/files/5090063/slow-deployment.zip)

**Comment by andrewsykim** [comment]
I tried to reproduce this with containerd  but wasn't able to, the "slow" pod is not ready as expected since it fails the timeout:
```
$ kubectl get po 
NAME                               READY   STATUS    RESTARTS   AGE
slow-deployment-59767df6b6-x8fnk   0/1     Running   0          8m21s
```

I have a feeling this is likely a docker-specific issue. This code [here](https://github.com/kubernetes/kubernetes/blob/2c964aee1593ec0783dc8bc6ed76c1e7178ad31f/pkg/kubelet/lifecycle/handlers.go) and [here](https://github.com/kubernetes/kubernetes/blob/8398bc3b53cb51b341e14ae2a2cea01cedbf7904/pkg/kubelet/kubelet_pods.go#L1779) seems telling -- will dig into it a bit more.

**Comment by andrewsykim** [comment]
I was able to reproduce this on environments that are still using dockershim and I think this is the fix https://github.com/kubernetes/kubernetes/pull/94115

**Comment by jgoeres** [comment]
@andrewsykim Thanks for taking care of this. Can you say to which versions this fix will go in the end?
There is another topic related to this one - actually this new topic is what triggered my look at the behavior of probe timeouts the results I reported here. I have not enough hard evidence to open a dedicated issue for this other, but maybe you have an idea - let me please give you a brief sketch:
On an Azure AKS cluster, we observed that a number of pods had gone to not ready state. We observed that the root cause was apparently a full disk on a share - we assume that this caused request threads to block, including the one responding to the readiness probe's request.
What we also noticed was that inside the unhealthy containers, we had literally hundreds of hanging processes of our readiness probe. It appeared that in this environment, a non-responding probe would not be canceled, but instead a new probe would be invoked. We had tried to reproduce this behavior, but didn't manage to do it.
