### ISSUE TITLE
bazel-test-master - panic: field etcdserverpb.Request.ID has invalid type

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/kubernetes#94099]
**Which jobs are flaking**:
bazel-test-master
**Which test(s) are flaking**:
Showing up as **Overall** on TestGrid

The Test Names on TG are not presented as they are for e2e tests (Could this be because these are unit tests?)

Here are the Tests where the Panic occurs
- TestAllocatedLocallyButReleasedStorage
- TestServiceRegistryIPUpdate
- TestServiceRegistryUpdateExternalService
- TestServiceRegistryDeleteExternal
- TestShortNames
 
**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:
`panic: field etcdserverpb.Request.ID has invalid type: got uint64, want pointer`

**Anything else we need to know**:
The panic has been noted in this (now closed) issue  #92070 This issue ended up bringing in an etcd fix.
So I guess first port of call is to see if we are somehow not picking up this etcd fix here?
 
**Specific failures on Prow's Spyglass**
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1295783299414757376
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1295675944714899459
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1294002990276939777

- links to go.k8s.io/triage appreciated

I had problems finding this error on triage will investigate further

/kind flake
/sig testing
cc @kubernetes/ci-signal

**Comment by knight42** [comment]
xref: https://github.com/etcd-io/etcd/issues/12197

**Comment by liggitt** [comment]
Workaround open at https://github.com/etcd-io/etcd/pull/12238 (master) and https://github.com/etcd-io/etcd/pull/12239 (3.4 pick)

Would be good if we can pick those up in 3.4.11

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/94105
