### ISSUE TITLE
The host with dual NIC can only get the IP of public network through the interface, but I want the IP of intranet. How to configure kubernetes

### ISSUE THREAD

**Issue by Ruilkyu** [kubernetes/kubernetes#94092]

**Comment by neolit123** [comment]
hello, the kubelet allows you to pass --node-ip explicitly which can override the default of picking an address on the public interface. but note that other components might need extra flags too:
https://kubernetes.io/docs/reference/command-line-tools-reference/

we try to use this issue tracker for bugs/feature requests. for questions you can use the support channels and k8s slack.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
