### ISSUE TITLE
pull-kubernetes-e2e-gce-100-performance is flaky due to sporadic APIResponsivenessPrometheus failures

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/kubernetes#94098]
https://storage.googleapis.com/k8s-gubernator/triage-go/index.html?ci=0&pr=1&text=APIResponsivenessPrometheus&job=performance

![85d44262-1feb-4cad-a626-c8673bc85355](https://user-images.githubusercontent.com/2604887/90616979-6b8c5580-e20e-11ea-978f-01a19b0bfe53.png)

@wojtek-t, was analyzing it when looking at scheduler throughput issues. What he found, suggests that master is cpu throttled from time to time, which may be causing api-call-latency spikes. 

### AIs

1. [x] Experimentally and temporarily upsize master VMs in the `pull-kubernetes-e2e-gce-100-performance` test
2. [ ] Wait a week or two
3. [ ] See if it helps

**Comment by wojtek-t** [comment]
Given that we actually stopped running kubemark-500 recently on every PR, this sounds reasonable from cost perspective too.

**Comment by mm4tt** [comment]
Looking at the last two weeks (with 8vCPU masters), it looks better

### 8 vCPU Master
**Num failures:** 6
**Link:** https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=APIResponsivenessPrometheus&job=performance
![58Q6VEhzxhbpr9U](https://user-images.githubusercontent.com/2604887/93088211-eaec3800-f699-11ea-8913-76ea43c7b29f.png)

### 4 vCPU Master

**Comment by wojtek-t** [comment]
Thanks for the data! Indeed it looks better (especially given we got out of code freeze in that time).

It would make sense to look into those 6 failures and see where those are coming from at some point.

**Comment by wojtek-t** [comment]
/assign @mborsz 

As you're looking into this as-we-speak anyway...

**Comment by wojtek-t** [comment]
/assign

After internal discussions and number of experiments we decided to change the function that defined control-plane node sizes.

**Comment by wojtek-t** [comment]
Once #95947 merges, we can clean-up test-infra and close this issue.
