### ISSUE TITLE
build/README.md suggests using outdated docker-machine

### ISSUE THREAD

**Issue by pymander** [kubernetes/kubernetes#94091]
**What would you like to be added**:

The Docker Machine project is currently in maintenance mode (https://github.com/docker/machine/issues/4537) and there are different ways to utilize remote hosts for Docker containers to build Kubernetes. I believe the **build/README.md** documentation should be updated to reflect this.

**Why is this needed**:

Docker Machine is in maintenance mode and on the Docker website, it's listed as superseded. Kubernetes docs should recommend a better method before Docker Machine fades into non-maintenance.

**Comment by kspviswa** [comment]
I would like to begin my K8S contribution journey with this issue if it is still available to be picked up and still valid (after reading comments from @BenTheElder ). Please let me know.

**Comment by Amyth07** [comment]
Hey, Can I take this ?

**Comment by BenTheElder** [comment]
Removing it from the docs shouldn't be too hard to track down and cleanup and would certainly be welcome, you don't need to ask 😅 

Cleaning up the build system to drop everything related to this will be a bit tedious / tricky, but also welcome.

**Comment by adeniyistephen** [comment]
@BenTheElder Hi, I would really love to work on this, please kindly provide input and pointers for the documentation. Thanks

**Comment by BenTheElder** [comment]
Hi, you can find some of the docs in [`./build`](https://github.com/kubernetes/kubernetes/tree/master/build), but I think it might be best to learn about the docs etc. before attempting this issue. [`CONTRIBUTING.md`](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md) links to some helpful guides 😅

**Comment by adeniyistephen** [comment]
> Hi, you can find some of the docs in [`./build`](https://github.com/kubernetes/kubernetes/tree/master/build), but I think it might be best to learn about the docs etc. before attempting this issue. [`CONTRIBUTING.md`](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md) links to some helpful guides 😅

OK thanks, I will work on this. I hope to get help and guidance when I make a PR

**Comment by adeniyistephen** [comment]
@BenTheElder I can only update the `build/readme.md` file tho.

**Comment by jherrera123** [comment]
I'll take a look at updating the build scripts. My understanding is this issue should cover the following:

- Remove docker-machine usage from build scripts
- Remove docker remote usage from build scripts
- Possibly remove or update rsync usage from build scripts
- Update doc

/assign

**Comment by adeniyistephen** [comment]
> I'll take a look at updating the build scripts. My understanding is this issue should cover the following:
> 
> * Remove docker-machine usage from build scripts
> * Remove docker remote usage from build scripts
> * Possibly remove or update rsync usage from build scripts
> * Update doc
> 
> /assign

This does not look like documentation anymore then, it looks like a code. if there's any pointer or inputs, kindly provide. Thanks

**Comment by jherrera123** [comment]
@adeniyistephen yes, two parts, doc and code.

Do you want to send a PR for the doc portion? Go through the build docs, and update them to reflect we're dropping `official support` for building k8s with docker-machine and docker remote. I don't know if there's any more doc besides build/README.md, you should read the doc or grep for keywords in the code base.

I'll work on the build scripts.

**Comment by adeniyistephen** [comment]
> @adeniyistephen yes, two parts, doc and code.
> 
> Do you want to send a PR for the doc portion? Go through the build docs, and update them to reflect we're dropping `official support` for building k8s with docker-machine and docker remote. I don't know if there's any more doc besides build/README.md, you should read the doc or grep for keywords in the code base.
> 
> I'll work on the build scripts.

Yes I do want to send a PR, thanks. I will work on the docs.
But we are looking at modifying the build/README.md docs right, can I do it now? Besides can you send me to a pointer or how do you think it should be modified.
Cause I thing K8t wants to remove the docker machine build right.

**Comment by adeniyistephen** [comment]
> @adeniyistephen yes, two parts, doc and code.
> 
> Do you want to send a PR for the doc portion? Go through the build docs, and update them to reflect we're dropping `official support` for building k8s with docker-machine and docker remote. I don't know if there's any more doc besides build/README.md, you should read the doc or grep for keywords in the code base.
> 
> I'll work on the build scripts.

I would love to update the `build/README.md` file. Thanks

**Comment by adeniyistephen** [comment]
> @adeniyistephen yes, two parts, doc and code.
> 
> Do you want to send a PR for the doc portion? Go through the build docs, and update them to reflect we're dropping `official support` for building k8s with docker-machine and docker remote. I don't know if there's any more doc besides build/README.md, you should read the doc or grep for keywords in the code base.
> 
> I'll work on the build scripts.

Thank you, I will work on the doc. I guess this is the link to the `build/README.md` file https://github.com/kubernetes/kubernetes/blob/master/build/README.md

**Comment by jherrera123** [comment]
@adeniyistephen , docker-machine is not your regular docker installation. Users can still use regular docker locally, bazel or make to build kubernetes.

I took a first pass at the doc. I searched through the doc using the same regex I used for issue 97618. Do you want to take a look at it?

https://github.com/jherrera123/kubernetes/commit/9f4d95d9333df0060e7e84aa454a99c2c5f2230b

**Comment by coderfornow** [comment]
can I take this, is this still open?
@jherrera123 
@BenTheElder
