### ISSUE TITLE
monit is too aggressive in killing docker

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#9412]
When we get into a low-memory situation, docker is slow to respond and monit kills it:

```
[UTC Jun  8 18:19:46] error    : 'docker' failed protocol test [HTTP] at UNIX[/var/run/docker.sock] -- HTTP: Error receiving data -- Resource temporarily unavailable

[UTC Jun  8 18:19:47] info     : 'docker' trying to restart
[UTC Jun  8 18:19:47] info     : 'docker' stop: /etc/init.d/docker
[UTC Jun  8 18:19:48] info     : 'docker' start: /etc/init.d/docker
```

However, if you have a lot of containers, it can take a long time for Docker to restart and get healthy again.  If you're under a lot of pressure, it will still be recovering at the next check-time (5 minutes later).  (At least I think that is what is happening.)

I don't know what we should do here.  We could make kubelet responsible for health-checking & restarting Docker, because it is talking to Docker all the time so it has a much better idea than monit when Docker is healthy or not.  We could turn down the interval with which monit checks (or allow more time after a restart).

I suppose the right answer is that I should stop over-committing machines!

**Comment by dchen1107** [comment]
@justinsb You are absolutely right about this, especially in over-commit situation, docker respond slowly, and restarting docker causes tons of containers recovery, which causes even higher memory usage for docker.  This is why I had been pushing hard on resource-ware scheduling. Unfortunately for v1.0, putting resource limit for pod is not possible (pod-level limit cannot specify at API), and specify container level resource limit is not mandatory too. But there are a couple of efforts I had pushed into our current system to prevent such bad situation at v0.18 release

1) By default, kubernetes cluster on GCE will have a LimitRange object created, which enforce all containers without limit at least have 100m for cpu. Hope this can prevent tons of small pods are scheduled to a small node. Of course if there are only 2 pods without resource limit specified, and each use too much memory, this one doesn't prevent such situation. But we do oom protected our daemons already. In this case, only user container will be oom-killed. 

```$ cluster/kubectl.sh describe limits limits
Name:		limits
Type		Resource	Min	Max	Default
----		--------	---	---	---
Container	cpu		-	-	100m
```

2) all kubernetes daemons are running in their own resource containers. Please note there is no memory limit specified for them, but we oom protected them. 

3) all other daemons running on node but not managed by kubernetes are running in /system resource container. This helps us have a complete resource consumption on a given node. Of course, once GCE container VM image enabled hierarchical memcg accounting, we can put each daemon into their own subcontainer under /system to make monitoring more clear. 

For this particular issue, I agreed with you we should make kubelet responsible for health-checking & restarting Docker, but that is not v1.0 blocker though.

**Comment by dchen1107** [comment]
#9881 too

**Comment by dchen1107** [comment]
The issue should be obsolete now. We replaced monit with supervisord, and changed the interval of checking daemon's healthiness from 2 minutes to 10 seconds; Also we dropped the test of /var/run/docker.sock from healthcheck. I am closing the issue.
