### ISSUE TITLE
psp/privileged requires binding to other serviceaccounts in ns/kube-system next to sa/default

### ISSUE THREAD

**Issue by christian-2** [kubernetes/kubernetes#94129]
**What happened**:

I have activated `PodSecurityPolicy`s by creating the following Kubernetes resources:

* `psp/restricted`: according to [Pod Security Standards][1]
* `psp/privileged`: according to [Pod Security Standards][1]
* `clusterrole/restricted`: permits `use` of `psp/restricted`
* `clusterrole/privileged`: permits `use` of `psp/privileged`
* `clusterrolebinding/restricted`: binds the following subjects to `clusterrole/restricted`:
1. `sa/default` for a certain namespace where I want restrictions to apply
2. a certain group to whom I want restrictions to apply
* `clusterrolebinding/privileged`: binds the following subjects to `clusterrole/privileged`:
1. group `system:nodes`
2. `sa/default` in `ns/kube-system`
3. `sa/default` in certain other namespaces where I do not want restrictions to apply

**What you expected to happen**:

A certain `deployment/lb` in `ns/kube-system` can no longer restart its pod. `kubectl describe rs -n kube-system` for the corresponding `ReplicaSet` reveals  "Error creating: pods ... is forbidden: unable to validate against any pod security policy: []" and `kubectl get rs -o yaml ...` reveals that it apparently employs `sa/lb` (not `sa/default`).

The problem goes away if I add `sa/lb` as another subject to `clusterrolebinding/privileged`. If memory serves, this was not mentioned in the documentation or tutorials (e.g. [here][2]; I would have thought `sa/default` suffices). So I am asking: Is this a feature or a bug?

**How to reproduce it (as minimally and precisely as possible)**:

(see above)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: bare-metal cluster
- OS (e.g: `cat /etc/os-release`): Debian 10
- Kernel (e.g. `uname -a`): `Linux xxx 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug): Weave Net 2.6.4
- Others:

[1]: https://kubernetes.io/docs/concepts/security/pod-security-standards/
[2]: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#run-another-pod
/sig auth

**Comment by liggitt** [comment]
/remove-kind bug

This is working as intended. To allow pods to run, you must grant their service accounts access to a pod security policy that permits the pod. The `default` service account is not treated differently by PodSecurityPolicy.

A pull request to update the documentation to use a non-default service account would be welcome if that would have helped clarify this.

/close
