### ISSUE TITLE
unable to sync kubernetes service: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by JackieWu1219** [kubernetes/kubernetes#94155]
env:k8s(v1.16.12) in centos7.4.
when is deploy the kube-apiserver ,I get the error when i start the apiserver service,I search a lot and I didn't get the answer:
--------------------------------------------------------
E0821 17:04:40.026333   21836 controller.go:154] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/10.***.***.59, ResourceVersion: 0, AdditionalErrorMsg:
E0821 17:04:40.041829   21836 repair.go:300] the cluster IP 169.169.0.1 may have leaked: flagging for later clean up
E0821 17:04:41.602014   21836 controller.go:224] unable to sync kubernetes service: Service "kubernetes" is invalid: spec.clusterIP: Invalid value: "169.169.0.1": provided IP is already allocated
E0821 17:04:52.893554   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"etcdserver: leader changed", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:04:52.917444   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:04:52.921916   21836 controller.go:224] unable to sync kubernetes service: rpc error: code = Unavailable desc = transport is closing
E0821 17:05:06.263207   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"etcdserver: leader changed", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:05:07.831954   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:05:07.833075   21836 controller.go:224] unable to sync kubernetes service: rpc error: code = Unavailable desc = transport is closing
E0821 17:09:21.893791   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"etcdserver: leader changed", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:09:21.929821   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:09:21.932382   21836 controller.go:224] unable to sync kubernetes service: rpc error: code = Unavailable desc = transport is closing
E0821 17:09:34.405021   21836 status.go:71] apiserver received an error that is not an metav1.Status: &status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
E0821 17:09:34.405498   21836 compact.go:124] etcd: endpoint ([https://10.***.***.59:2379 https://10.***.***.126:2379 https://10.***.***.127:2379]) compact failed: rpc error: code = Unavailable desc = transport is closing
E0821 17:09:41.416368   21836 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: request timed out, possibly due to previous leader failure"}

**Comment by neolit123** [comment]
> E0821 17:09:34.405498 21836 compact.go:124] etcd: endpoint ([https://10...59:2379 https://10...126:2379 https://10..*.127:2379]) compact failed: rpc error: code = Unavailable desc = transport is closing

/sig api-machinery

**Comment by neolit123** [comment]
are all etcd members healthy and running?
what is the etcd version?

**Comment by JackieWu1219** [comment]
> are all etcd members healthy and running?
> what is the etcd version?

thanks for your reply.
I deploy 3 nodes etcd, and get the etcd status is healthy.
my etcd version is v3.3.23

**Comment by JackieWu1219** [comment]
> are all etcd members healthy and running?
> what is the etcd version?

now ,I change the version of k8s to v1.18.6 ,and change the version of etcd to v3.4.10
I deploy the k8s cluster  seems  normal. 
Some k8s version is not compatible with  etcd version ??

**Comment by yehaifeng** [comment]
I'm in a similar situation.
kubernertes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-04T02:07:01Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-04T02:07:01Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
etcd version:
```
etcd Version: 3.4.13
Git SHA: ae9734ed2
Go Version: go1.12.17
Go OS/Arch: linux/amd64
```

and the kube-apiserver logs:
```
I0909 14:13:13.244773   29490 client.go:360] parsed scheme: "passthrough"
I0909 14:13:13.244901   29490 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://192.168.81.11:2379  <nil> 0 <nil>}] <nil> <nil>}
I0909 14:13:13.244946   29490 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0909 14:13:13.245530   29490 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc003135050, {CONNECTING <nil>}
I0909 14:13:13.267701   29490 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc003135050, {READY <nil>}
I0909 14:13:13.271866   29490 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0909 14:13:18.524133   29490 client.go:360] parsed scheme: "passthrough"
I0909 14:13:18.524261   29490 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://192.168.81.12:2379  <nil> 0 <nil>}] <nil> <nil>}
I0909 14:13:18.524296   29490 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0909 14:13:18.524566   29490 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00696ce00, {CONNECTING <nil>}
I0909 14:13:18.547043   29490 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00696ce00, {READY <nil>}
I0909 14:13:18.549034   29490 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0909 14:13:23.488290   29490 client.go:360] parsed scheme: "passthrough"
I0909 14:13:23.488429   29490 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://192.168.81.10:2379  <nil> 0 <nil>}] <nil> <nil>}
I0909 14:13:23.488462   29490 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0909 14:13:23.488683   29490 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc007e08600, {CONNECTING <nil>}
I0909 14:13:23.510121   29490 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc007e08600, {READY <nil>}
I0909 14:13:23.512004   29490 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Comment by der-eismann** [comment]
@yehaifeng We have the same problem here with k8s 1.19.2 and etcd 3.3.12. Were you able to fix the problem?
```
I1006 16:24:52.209674       1 client.go:360] parsed scheme: "passthrough"
I1006 16:24:52.209911       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{http://0.etcd.k8s.domain.loc:2379  <nil> 0 <nil>}] <nil> <nil>}
I1006 16:24:52.210052       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I1006 16:24:52.210192       1 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0116d0b50, {CONNECTING <nil>}
I1006 16:24:52.214547       1 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0116d0b50, {READY <nil>}
I1006 16:24:52.216144       1 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

However the cluster itself is healthy:
```
$ etcdctl cluster-health
member c7549a1f541ef0dc is healthy: got healthy result from http://1.etcd.k8s.domain.loc:2379
member e0a9942f6b765c5f is healthy: got healthy result from http://0.etcd.k8s.domain.loc:2379
member f795bfa714149988 is healthy: got healthy result from http://2.etcd.k8s.domain.loc:2379
cluster is healthy
```

**Comment by hemuke** [comment]
@yehaifeng 
We have the same problem here with k8s 1.19.3 and etcd 3.3.14. Were you able to fix the problem?
kube-apiserver: I1023 23:42:48.507405   59567 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
kube-apiserver: I1023 23:42:48.618611   59567 client.go:360] parsed scheme: "passthrough"
kube-apiserver: I1023 23:42:48.618661   59567 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://172.16.94.60:2379  <nil> 0 <nil>}] <nil> <nil>}
kube-apiserver: I1023 23:42:48.618675   59567 clientconn.go:948] ClientConn switching balancer to "pick_first"
kube-apiserver: I1023 23:42:48.618762   59567 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00e1e4e30, {CONNECTING <nil>}
kube-apiserver: I1023 23:42:48.626355   59567 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc00e1e4e30, {READY <nil>}

**Comment by xxlaila** [comment]
I also encountered this problem. The kube version is: v1.19.4
etcd version: 3.3.25

```
Dec  1 12:10:23 VM-24-11-centos kube-apiserver: I1201 12:10:23.264470   16183 clientconn.go:948] ClientConn switching balancer to "pick_first"
Dec  1 12:10:23 VM-24-11-centos kube-apiserver: I1201 12:10:23.264581   16183 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0130faf00, {CONNECTING <nil>}
Dec  1 12:10:23 VM-24-11-centos kube-apiserver: I1201 12:10:23.270712   16183 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0130faf00, {READY <nil>}
Dec  1 12:10:23 VM-24-11-centos kube-apiserver: I1201 12:10:23.271433   16183 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.304052   16183 client.go:360] parsed scheme: "passthrough"
Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.304093   16183 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://172.16.24.16:2379  <nil> 0 <nil>}] <nil> <nil>}
Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.304103   16183 clientconn.go:948] ClientConn switching balancer to "pick_first"
Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.304234   16183 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0044854c0, {CONNECTING <nil>}
Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.310476   16183 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0044854c0, {READY <nil>}
Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.311164   16183 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Comment by aojea** [comment]
How are you deploying etcd and the apisever, as pods, as processes? are they colocated in the same host? ...

These errors use to happen when there is some problem to connect from the apiserver to etcd, it may be the network , it may be the etcd cluster, ... just check first that the cluster is healthy and that the connection between your apisever and etcd is working correctly ... you can obtain the etcd endpoints from the logs, i.e

> Dec  1 12:10:26 VM-24-11-centos kube-apiserver: I1201 12:10:26.304093   16183 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://172.16.24.16:2379  <nil> 0 <nil>}] <nil> <nil>}

**Comment by grosser** [comment]
We are also seeing this with etcd servers that are not co-located but healthy.
Everything works fine, but logs are getting spammed with these messages.

**Comment by ydp** [comment]
@aojea  encounter the same problem:  etcd Version: 3.4.13    kubernetes: v1.19.2.

we are in a scale test process, there are 500+ nodes, etcd and apiserver both deployed as process, and colocated in the same host, I have 3 masters, only 1 master has this error, other 2 master works fine now.

```
I1223 14:13:57.637272       7 client.go:360] parsed scheme: "passthrough"
I1223 14:13:57.637306       7 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://master-1.etcd.cfcr.internal:2379  <nil> 0 <nil>}] <nil> <nil>}
I1223 14:13:57.637315       7 clientconn.go:948] ClientConn switching balancer to "pick_first"
I1223 14:13:57.637457       7 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc266cd8ac0, {CONNECTING <nil>}
I1223 14:13:57.645876       7 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc266cd8ac0, {READY <nil>}
I1223 14:13:57.646669       7 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I1223 14:13:58.734947       7 client.go:360] parsed scheme: "passthrough"
I1223 14:13:58.734981       7 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://master-0.etcd.cfcr.internal:2379  <nil> 0 <nil>}] <nil> <nil>}
I1223 14:13:58.734991       7 clientconn.go:948] ClientConn switching balancer to "pick_first"
I1223 14:13:58.735054       7 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc10ffaa5a0, {CONNECTING <nil>}
I1223 14:13:58.743845       7 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc10ffaa5a0, {READY <nil>}
I1223 14:13:58.744607       7 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

etcdctl show helath:
```
# etcdctl endpoint health
https://master-0.etcd.cfcr.internal:2379 is healthy: successfully committed proposal: took = 16.764464ms
https://master-2.etcd.cfcr.internal:2379 is healthy: successfully committed proposal: took = 16.966777ms
https://master-1.etcd.cfcr.internal:2379 is healthy: successfully committed proposal: took = 18.494579ms
```

raw metrics show health:
```
# etcdctl endpoint health
https://master-0.etcd.cfcr.internal:2379 is healthy: successfully committed proposal: took = 16.764464ms
https://master-2.etcd.cfcr.internal:2379 is healthy: successfully committed proposal: took = 16.966777ms
https://master-1.etcd.cfcr.internal:2379 is healthy: successfully committed proposal: took = 18.494579ms
```

but  8443 port reply with 429 too many requests:
```
# curl -vv  -k https://127.0.0.1:8443/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* found 139 certificates in /etc/ssl/certs/ca-certificates.crt
* found 556 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: pks-st-1.pks.local (does not match '127.0.0.1')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=pks-st-1.pks.local,O=system:masters
* 	 start date: Tue, 15 Dec 2020 06:58:26 GMT
* 	 expire date: Sun, 15 Dec 2024 06:58:26 GMT
* 	 issuer: CN=ca
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: 127.0.0.1:8443
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 429 Too Many Requests
< Audit-Id: d69b52c5-8d3c-467a-9dcd-bee631456d4f
< Cache-Control: no-cache, private
< Content-Type: text/plain; charset=utf-8
< Retry-After: 1
< X-Content-Type-Options: nosniff
< Date: Wed, 23 Dec 2020 14:19:11 GMT
< Content-Length: 43
<
Too many requests, please try again later.
```

**Comment by jingyih** [comment]
@grosser
I am quite surprised that turning off `--etcd-db-metric-poll-interval` would completely solve this. The error message is a generic error returned from etcd. As an example, in the original post, a compaction request from apiserver to etcd would also trigger this message. So you might be experiencing a different issue. It will be great if you could share the server log.
```
E0821 17:09:34.405498 21836 compact.go:124] etcd: endpoint ([https://10...59:2379 https://10...126:2379 https://10..*.127:2379]) compact failed: rpc error: code = Unavailable desc = transport is closing
E0821 17:09:41.416368 21836 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: request timed out, possibly due to previous leader failure"}
```

**Comment by jingyih** [comment]
From the original post, I noticed that the errors started with the following message. (please share more log entries if I am wrong)
```
Unable to remove old endpoints from kubernetes service: StorageError
```
I did a quick search and found #76146, which unfortunately is an unresolved issue since 2019.
