### ISSUE TITLE
kubectl permission issue after old certificates expired (Error from server (Forbidden))

### ISSUE THREAD

**Issue by siadark** [kubernetes/kubernetes#94175]
**What happened:**

we used Kubernetes version 1.15 for almost a year without any issue and recently before certificates got expired we **upgrade the cluster to 1.16.12 to renew certificates** everything seems fine until old certificates expired and the kubectl commands (kubectl get pods) gives us:
 **error: You must be logged in to the server (Unauthorized)**
then we found out in [Certificate Management with kubeadm](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#:~:text=Manual%20certificate%20renewal,%2Fetc%2Fkubernetes%2Fpki%20.) that we ought to update kubelet.conf manually duo to a bug, with these parameters:
**client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
client-key: /var/lib/kubelet/pki/kubelet-client-current.pem**

after restarting kubelet now there is another sort of error about permissions with almost every kubectl commands except get pods.

**Error from server (Forbidden): error when deleting "manager-pod.yaml": pods "manager-505" is forbidden: node "dashboard" can only delete pods with spec.nodeName set to itself**

**from server for: "manager-configMap.yaml": configmaps "manager-505" is forbidden: User "system:node:dashboard" cannot get resource "configmaps" in API group "" in the namespace "mafioso": no relationship found between node "dashboard" and this object**

**Anything else we need to know?:**

our cluster is now live with no problem so far and we really prefer not to have downtime as we have about **100k** daily users.
we have 5 nodes one control plane.
we have only one root user.
here is our /etc/kuberneteskubelet.conf:
`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *****
    server: https://10.0.0.4:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:dashboard
  name: system:node:dashboard@kubernetes
current-context: system:node:dashboard@kubernetes
kind: Config
preferences: {}
users:
- name: system:node:dashboard
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
`

**Environment:**

- Kubernetes version (use kubectl version): 1.16.12
- Cloud provider or hardware configuration: Bare metal
- OS (e.g: cat /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. uname -a): Linux dashboard 3.10.0-957.27.2.el7.x86_64
- Install tools: Kubeadm 

**update:
how to solve the issue:**
make sure all the certificates are renewed correctly with this:
**kubeadm alpha certs check-expiration**
if not just do:
**kubeadm alpha certs renew all**
then this: **_(this is very important )_**

**** **cp /etc/kubernetes/admin.conf $HOME/.kube/config** ****

also make sure this parameters are set in **/etc/kubernetes/kubelet.conf**
**client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
client-key: /var/lib/kubelet/pki/kubelet-client-current.pem**

**Comment by siadark** [comment]
unfortunately, we ended up tear down and reinit our cluster :(( it was a real disaster.

but today I tried to find out what was the problem and I'm pretty sure I found it:
you were right about admin.conf we probably just needed to **cp /etc/kubernetes/admin.conf $HOME/.kube/config** 
to do the trick as it seems that in version 1.16.12 renewing the certificates will change the certificates in admin. conf but it wont copy it to $HOME/.kube/config this was what happened to us resulting in this **error error: You must be logged in to the server (Unauthorized)** and what we did was to set these parameters in /etc/kubernetes/kubelet.conf**client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
client-key: /var/lib/kubelet/pki/kubelet-client-current.pem**
as we tough this was the problem but it didn't solve the issue after that we did this silly thing to copy kubelet.conf to $HOME/.kube/config and this resulted in the second error  **Error from server (Forbidden) ...**.

thank you and I hope this will never happen to anybody else.

**Comment by neolit123** [comment]
The output of kubeadm init does include a message that you can copy the
admin.conf to the home directory.

Thanks for confirming.

/close

**Comment by siadark** [comment]
> The output of kubeadm init does include a message that you can copy the admin.conf to the home directory.
right but we didn't do kubeadm init. we just upgraded the cluster and renewed certificates along the way and we didn't know that we have to recopy admin.conf.
i think its important to mention this in the output whenever certificates rerenewed like in kubeadm alpha certs renew or kubeadm upgrade apply v1.16.x --certificate-renewal=true

thanks

**Comment by neolit123** [comment]
kubeconfig files are credential files that must be kept up to date and distributed to the right users/folders.
if credentials are renewed they obviously need to be redistributed.
