### ISSUE TITLE
Support for specifying Node Maintenance Information

### ISSUE THREAD

**Issue by khatrig** [kubernetes/kubernetes#94181]
**What would you like to be added**: 
Option stop specify node cordon/drain reason
Eg. kubectl cordon BADNODE --comment "Node out for RAM upgrade RAM"

Then the comment can be read by running:
kubectl get BADNODE -o wide

+-----------------------------+--------+--------+------+---------+----------------+-------------+--------------------+--------------------+-------------------+------------------------------+
| **NAME**                        | STATUS | ROLES  | AGE  | VERSION | INTERNAL-IP    | EXTERNAL-IP | OS-IMAGE           | KERNEL-VERSION     | CONTAINER-RUNTIME | **COMMENT**                      |
+-----------------------------+--------+--------+------+---------+----------------+-------------+--------------------+--------------------+-------------------+------------------------------+
| **BADNODE**  | Ready  | master | 2d7h | v1.16.3 | 10.120.123.136 |             | Ubuntu 18.04.4 LTS | 4.15.0-112-generic | docker://19.3.5   | **Node out for RAM Upgrade** |
+-----------------------------+--------+--------+------+---------+----------------+-------------+--------------------+--------------------+-------------------+------------------------------+

**Why is this needed**: In the scenario where there are multiple maintainers for a cluster, there is no simple way to find out why the node is disabled/down. it would be extremely helpful if there was a way to specify the outage/maintenance reason/comment while disabling a node.

**Comment by michaelgugino** [comment]
You might be interested in this KEP: https://github.com/kubernetes/enhancements/pull/1411
