### ISSUE TITLE
kube-scheduler: debug plugin for reporting scheduler insights into logs

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#94192]
**What would you like to be added**:
A new scheduler plugin for reporting scheduler internals such as node cache, current resource utilization, etc. into logs when scheduling.

**Why is this needed**:
When scheduling e2e tests are flaking, there's no way to know if current utilization guessed by an e2e (e.g. `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]`)  is the same as the one in kube-scheduler's node cache. Without knowing that it's hard to see if the test is failing because the resource utilization is incorrectly computed or because scheduler's node cache is corrupted or other reason.

The goal is to provide a plugin (and make it part of the core plugins) which will report useful information about scheduler's internals. The internals will help to shed more light on which information the scheduler has. The plugin will be disabled by default and enabled only for development/debugging purposes. Alternatively, the plugin can be enabled even in production to provide additional information in case pods are not getting effectively scheduled.

**Comment by ahg-g** [comment]
I like that, I guess the plugin could implement multiple extension points to report the status of a pod's scheduling cycle.

**Comment by ingvagabund** [comment]
> the plugin could implement multiple extension points to report the status of a pod's scheduling cycle.

Any specific bits you have in mind?

cc @alculquicondor

**Comment by alculquicondor** [comment]
How do you suggest to expose the information? metrics? logs?

**Comment by ingvagabund** [comment]
logs

**Comment by alculquicondor** [comment]
What would be the benefit compared to using log levels? Since changes require restarts, changing a single number is less error prone.
One more thing, `kill -SIGUSR2 <kube-scheduler-pid>` can be used to dump the scheduler cache at the moment of execution. Which is not ideal, as it wouldn't log every time. But again, log levels.

**Comment by ingvagabund** [comment]
> What would be the benefit compared to using log levels? Since changes require restarts, changing a single number is less error prone.

Plugin related information starts with log level 10 which is unusable given the amount of logs that are generated by other components.

> One more thing, kill -SIGUSR2 <kube-scheduler-pid> can be used to dump the scheduler cache at the moment of execution. Which is not ideal, as it wouldn't log every time. But again, log levels.

Not possible in CI environment where tests are flaking randomly. Again, for the moment it's mainly to debug `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]`. Though, in general, the goal is to obtain content of node info cache during development and testing. Using a plugin will allow to log bits which can't be logged in production otherwise.

**Comment by alculquicondor** [comment]
> Plugin related information starts with log level 10 which is unusable given the amount of logs that are generated by other components.

We could always revisit the log levels that we have and take advantage of structure logging to provide proper filtering.

**Comment by ingvagabund** [comment]
> We could always revisit the log levels that we have and take advantage of structure logging to provide proper filtering.

Which filtering do you have in mind? Is there a special flag to klog v2 saying "log also all the structure log with this label"?

**Comment by alculquicondor** [comment]
Not exactly. You would just increase the log level to (say) 3 or 4 and filter out what you don't need with the logging infrastructure that you might have.. or just grep.

**Comment by alculquicondor** [comment]
Not saying it is ideal, but rather saying that it might be simpler and easier to use/document.

**Comment by ingvagabund** [comment]
This approach was discussed few years back and the reason for not taking this path was the amount of logs generated in huge clusters. With log level 3-4, one will need to set log level 2 to silence the logs. Potentially silencing important logs which might help with debugging.

**Comment by ingvagabund** [comment]
> be simpler and easier to use/document

I am fine with increasing the complexity a bit for sake of getting more information about scheduling decisions

**Comment by ingvagabund** [comment]
Additionally, the plugin could be constrained to certain namespaces or label selectors. E.g. namespaces prefixed or containing `e2e` string.

**Comment by alculquicondor** [comment]
Would you mind starting a design doc or perhaps a KEP?

**Comment by ingvagabund** [comment]
> Would you mind starting a design doc or perhaps a KEP?

Yeah, I will update the issue once I have something to share. Thanks!!!
