### ISSUE TITLE
[e2e] DynamicSnapshot option should not be in default TestPattern

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#94202]
**What happened**:

In 1.19 we added a "dynamic snapshot" option to the default TestPattern.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testpatterns/testpattern.go#L113

But it is causing tests to skip for the drivers that don't support snapshots. Even though the test is not actually testing snapshot functionality. Like 
`External Storage [Driver: standard-rwo] [Testpattern: Dynamic PV (block volmode)] stress multiple pods should access different volumes repeatedly [Slow] [Serial] [BeforeEach]`

So it seems we should not add snapshots to default options. And instead we should have an explicit snapshots testpattern for snapshot tests.

**How to reproduce it (as minimally and precisely as possible)**:
```
ginkgo -p -focus='External.*Storage.*multiple.pods.should.access.different.volumes.*' \
       ./_output/bin/e2e.test \
       -- \
       -storage.testdriver=/path/to/config/test-driver.yaml
```

/sig storage
/kind bug
/cc @msau42

**Comment by msau42** [comment]
/assign @saikat-royc 
could you help take a look at this?
