### ISSUE TITLE
XSS Vulnerability with cAdvisor UI

### ISSUE THREAD

**Issue by sridhav** [kubernetes/kubernetes#94203]
**What happened**:
Kubelet internally uses cAdvisor to report/expose metrics. cAdvisor UI internally uses jQuery. JQuery < 3.5.0 has an open XSS vulnerability that is reported by various vulnerability assessment engines. 

Example: nessus -> https://www.tenable.com/plugins/nessus/136929

**What you expected to happen**:
UI should not have any open vulnerabilties

**How to reproduce it (as minimally and precisely as possible)**:
Run kubelet with cAdvisor enabled.

**Anything else we need to know?**:
This issue is fixed on cAdvisor end recently and released.
 More info on the fix can be found here -> https://github.com/google/cadvisor/issues/2584, https://github.com/google/cadvisor/issues/2614

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.12 (this is a issue in most of the k8s versions)
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Potential fix:
Build and release kubernetes patched version with recently released cAdvisor.

**Comment by neolit123** [comment]
/sig node

> Kubernetes version (use kubectl version): v1.15.12 (this is a issue in most of the k8s versions)

is this problem present in version 1.16 or newer based on the cadvisor version their include?
1.15 is out of support by the k8s team so if this is already solve in newer versions, this ticket should be closed.
 
/assign @dashpole 
please take a look.

**Comment by liggitt** [comment]
kubernetes does not include the vulnerable files

* 1.16 used [v0.34.0](https://github.com/kubernetes/kubernetes/blob/release-1.16/go.mod#L69)
  * The vulnerable files are in https://github.com/google/cadvisor/tree/v0.34.0/pages
  * Kubernetes does not include the pages package: https://github.com/kubernetes/kubernetes/tree/release-1.16/vendor/github.com/google/cadvisor
* 1.17 used [v0.35.0](https://github.com/kubernetes/kubernetes/blob/release-1.17/go.mod#L66)
  * The vulnerable files are in https://github.com/google/cadvisor/tree/v0.35.0/pages
  * Kubernetes does not include the pages package: https://github.com/kubernetes/kubernetes/tree/release-1.17/vendor/github.com/google/cadvisor
* 1.18 used [v0.35.0](https://github.com/kubernetes/kubernetes/blob/release-1.18/go.mod#L67)
  * The vulnerable files are in https://github.com/google/cadvisor/tree/v0.36.0/pages
  * Kubernetes does not include the pages package: https://github.com/kubernetes/kubernetes/tree/release-1.18/vendor/github.com/google/cadvisor
* 1.19 will use [v0.37.0](https://github.com/kubernetes/kubernetes/blob/release-1.19/go.mod#L56)
  * The vulnerable files are in https://github.com/google/cadvisor/tree/v0.37.0/cmd/internal/pages
  * Kubernetes does not include the cmd package: https://github.com/kubernetes/kubernetes/tree/release-1.19/vendor/github.com/google/cadvisor
