### ISSUE TITLE
How to get gke node reboot/shutdown logs using Systemd service

### ISSUE THREAD

**Issue by shanmukha511** [kubernetes/kubernetes#94212]
**What happened**:

Actually i want to use logs and check whether system got reboot and shutdown and we dont access to gke node so what we doing is we sending journald service systemd units logs to splunk so that can we can check any reboots and shutdown there.
but we are sending some service logs like kubelet,docker etc but we could not see any logs related to reboot.
Is there any way to find what is systemd service that holds reboot logs.

**And we cant use any commands like "journalctl -b -1 -n " because splunk oly support oly systemd service units**

**What you expected to happen**:
whenever reboot/shutdown happens on gke node we should able to see logs in splunk

**How to reproduce it (as minimally and precisely as possible)**:

Create k8 cluster and login to gke node and do sudo reboot and  check the systemd service units for reboot logs

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.12-gke.2
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Container optimized os (COS)
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by shanmukha511** [comment]
sig/node

**Comment by neolit123** [comment]
hi, this seems like a request for help for the GKE platform.
we try to delegate to such requests for managed solutions to their respective help desks - e.g.:
https://cloud.google.com/kubernetes-engine/docs/support

thanks
/close
/triage support
/remove-kind bug
