### ISSUE TITLE
make error - missing separator.  Stop.

### ISSUE THREAD

**Issue by happywzy** [kubernetes/kubernetes#94218]
git the latest project.
```bash
# first step
git clone https://github.com/kubernetes/kubernetes.git
# second step
cd ./kubernetes
# third step
make
# error print
Makefile:1: *** missing separator.  Stop.
```
how to solve? thanks.

**Comment by neolit123** [comment]
i don't see this problem.

what is the output of the follow commands?
```
$ lsb_release -a
$ make -v
```
also what shell are you using and what is its version?

/sig release

**Comment by happywzy** [comment]
> i don't see this problem.
> 
> what is the output of the follow commands?
> 
> ```
> $ lsb_release -a
> $ make -v
> ```
> 
> also what shell are you using and what is its version?
> 
> /sig release

I'm using docker compiler environment with the image `mirrorgooglecontainers/kube-cross:v1.12.10-1`.
```bash
root@48569e4737cd:/go/src/k8s.io/kubernetes# lsb_release -a
bash: lsb_release: command not found
root@48569e4737cd:/go/src/k8s.io/kubernetes# make -v
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by neolit123** [comment]
try a newer version of kube-cross. latest one at GCR is at v1.13.6-1.
also what output do you get from `make -d`?

**Comment by happywzy** [comment]
> try a newer version of kube-cross. latest one at GCR is at v1.13.6-1.
> also what output do you get from `make -d`?

```bash
root@5bc659560d0c:/go/src/k8s.io/kubernetes# make -d
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Makefile:1: *** missing separator.  Stop.
```

I'm trying `v1.13.6-1`

**Comment by happywzy** [comment]
> try a newer version of kube-cross. latest one at GCR is at v1.13.6-1.
> also what output do you get from `make -d`?
`gcrcontainer/kube-cross:v1.13.6-1`, same error, same output.

**Comment by neolit123** [comment]
this error usually comes when a rule is not prefixed with tab characters.
but given you are cloning the repository without modifications, i have no explanation.

**Comment by happywzy** [comment]
> this error usually comes when a makefile rule is not prefixed with tab characters.
> but given you are cloning the repository without modifications, i have no explanation.

thank you

**Comment by wwj-2017-1117** [comment]
Makefile:1: *** missing separator.  Stop.  
How to Solve it.

**Comment by wangweihong** [comment]
> > @wwj-2017-1117
> > Makefile:1: *** missing separator. Stop.
> > How to Solve it.
> 
> 源文件都是一些链接文件，如果挂载到容器中，链接文件就失效了，所以会出现此问题。
> 
> 在宿主机上的源文件：![源文件](https://user-images.githubusercontent.com/30235731/130940875-a1446da5-fdbf-4767-bc10-679faaf7bcbe.png)

save my life

**Comment by WhiteStart** [comment]
> > @wwj-2017-1117
> > Makefile:1: *** missing separator. Stop.
> > How to Solve it.
> 
> 源文件都是一些链接文件，如果挂载到容器中，链接文件就失效了，所以会出现此问题。
> 
> 在宿主机上的源文件：![源文件](https://user-images.githubusercontent.com/30235731/130940875-a1446da5-fdbf-4767-bc10-679faaf7bcbe.png)

在windows下出现这个错误该怎么操作

**Comment by dreams-money** [comment]
Is there a solution for this?

**Comment by t-katsumura** [comment]
Just a workaround worked for me.
Add `include` like this

```Makefile
include build/root/Makefile
```
