### ISSUE TITLE
Use the apiserver as a standalone application server

### ISSUE THREAD

**Issue by calind** [kubernetes/kubernetes#94222]
The kube-apiserver is a very well designed application server. It has a lot of great features already built-in, like authentication, authorization, quotas, multi-tenancy (namespaces), pluggability (webhooks), a way to define resources/subresources (CRD), resource watches, API request limiting and these are only the things from the top of my head.

These are killer features that many applications would benefit from. The "problem" of currently running only the kube-apiserver + etcd and exposing it to the world is that there are a lot of unrelated APIs which get exposed as well (eg. pods, services, deployments and so on).

It would be great to have a way to disables these builtin APIs.

**Comment by fedebongio** [comment]
/assign @lavalamp 
I'm sure you are interested in this topic :)

**Comment by lavalamp** [comment]
> The kube-apiserver is a very well designed application server

Flattery will get you everywhere ;)

More seriously, you can't *just* run the aggregator and the extensions (CRD) apiserver. You definitely need some built ins: Namespaces, maybe secrets, service accounts, RBAC roles... Services and APIServices... Webhook config...

You can turn off individual APIs with the --runtime-config flag. I think things should continue to function if you turn off nodes, pods, and things with pod templates. 

Can you give that a try and let us know how much of the problem that solves?

**Comment by liggitt** [comment]
> You can turn off individual APIs with the --runtime-config flag

I thought that only worked down to the resource level for the extensions/v1beta1 API group, and was limited to the API group/version otherwise

**Comment by lavalamp** [comment]
> I thought that only worked down to the resource level for the extensions/v1beta1 API group, and was limited to the API group/version otherwise

Oh, you're probably right. Sigh, I've gotten this wrong before.

I think I'm amenable to changes that enable turning stuff off. But rather than fixing the flag, which has a horrible format (undiscoverable and super confusing), we should come up with something else.

**Comment by lavalamp** [comment]
Group/version probably is the right level for enabling/disabling. The problem is that the core group has a bunch of different sorts of resources.

**Comment by caiorcferreira** [comment]
Does anyone know if doing this is currently possible? Or whether there is a project that implements these core features for distributed state management without the Kubernetes API?
