### ISSUE TITLE
[Flaky Test] [sig-scheduling] k8s.io/kubernetes/test/integration/scheduler.TestPostFilterPlugin

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#94230]
**Which jobs are flaking**:

`integration-master (ci-kubernetes-integration-master )`

**Which test(s) are flaking**:

`k8s.io/kubernetes/test/integration/scheduler.TestPostFilterPlugin`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Reason for failure**:

```
framework_test.go:666: Expected the filter plugin to be called at least 2 times, but got 0.
    framework_test.go:669: Expected the postfilter plugin to be called at least 1 times, but got 0.
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal @kubernetes/sig-scheduling-bugs @Huang-Wei 
/sig scheduling
/milestone v1.19
/priority critical-urgent

xref: https://github.com/kubernetes/kubernetes/issues/93485

**Comment by Huang-Wei** [comment]
@hasheddan thanks for raising this up. I think this is not a releasing blocking flake, but still a flake that can happen with rare chances.

The logs says:

```
12245 I0825 15:14:39.147789  119315 factory.go:443] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="postfilter2-0e1f1596-ea0      0-448f-807b-035f107417ef/test-pod"
```

This implies the integration test env is not prepared well - the (virtual) nodes are not ready - and then we proceed with the testing logic. A simple fix will be to add logic to ensure all (virtual) nodes to become available, and the logic would be good to be applied as a common pattern to all similar test cases.

**Comment by hasheddan** [comment]
Thanks @Huang-Wei!

/milestone v1.20

**Comment by RobertKielty** [comment]
@Huang-Wei Will you get a chance to look at this for the 1.20 release or would you like get some help with this?

**Comment by Huang-Wei** [comment]
Sure, it's on my radar.

**Comment by Huang-Wei** [comment]
Ready to work on this, got another DP [here](https://github.com/kubernetes/kubernetes/pull/82222#issuecomment-719699190).

**Comment by s-ito-ts** [comment]
I added the code the following and tried to reproduce this problem in my local environment.
```
// Filter is a test function that returns an error or nil, depending on the
// value of "failFilter".
func (fp *FilterPlugin) Filter(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
        fp.numFilterCalled++

        fmt.Printf("Pod=%v Node=%v called=%v\n", pod.Name, (*nodeInfo).Node().Name, fp.numFilterCalled)  <=== *
```
As a result, the following message was output.
So, "fp.numFilterCalled++" is not thread safe and seems to be causing this issue.
```
Pod=test-pod Node=test-node-0 called=1
Pod=test-pod Node=test-node-1 called=2  <=== *
Pod=test-pod Node=test-node-2 called=2  <=== *
```

I think it should be changed to such as atomic.AddInt32, what do you think about it?

**Comment by Huang-Wei** [comment]
@s-ito-ts yes, the latest code has switched to atomic.AddInt32():

https://github.com/kubernetes/kubernetes/blob/6a3fd8f3d71e756f4231b610fb1d404abb100119/test/integration/scheduler/framework_test.go#L232-L233

**Comment by s-ito-ts** [comment]
@Huang-Wei Thank you for your reply.
I seem to have seen the old code.

Please let me ask one more thing.
It seems that there are still some similar codes in the latest code.

https://github.com/kubernetes/kubernetes/blob/6a3fd8f3d71e756f4231b610fb1d404abb100119/test/integration/scheduler/framework_test.go#L252-L253

https://github.com/kubernetes/kubernetes/blob/6a3fd8f3d71e756f4231b610fb1d404abb100119/test/integration/scheduler/framework_test.go#L404-L405

I think these codes should also be switched to atomic.AddInt32().
Will it help you if I change these codes?

**Comment by Huang-Wei** [comment]
@s-ito-ts Reserve and PostFilter plugins are executed sequentially, so it's fine to leave the counter as is.

**Comment by s-ito-ts** [comment]
@Huang-Wei I understand.
Thank you for explaining in detail.
