### ISSUE TITLE
write unit tests for azure_storageaccount.go

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#94240]
**What would you like to be added**:

`getStorageAccounts` and `EnsureStorageAccount` functions need unit tests
https://github.com/kubernetes/kubernetes/blob/8c9d4def18019f3b39305fa83eddedd9f2bc930a/staging/src/k8s.io/legacy-cloud-providers/azure/azure_storageaccount.go#L43

**Why is this needed**:

/kind test
/sig cloud-provider
/area provider/azure

/assign

**Comment by andyzhangx** [comment]
related to https://github.com/kubernetes/kubernetes/pull/94239

**Comment by andyzhangx** [comment]
cc @Sakuralbj

**Comment by brkykan** [comment]
Hi @andyzhangx @dims, I'd like to give this one a go, if no one is currently working on it.

**Comment by andyzhangx** [comment]
> Hi @andyzhangx @dims, I'd like to give this one a go, if no one is currently working on it.

@brkykan  sure, go ahead, thanks

**Comment by antcs** [comment]
@andyzhangx I pushed some first tests for `getStorageAccounts`
