### ISSUE TITLE
many evicted pods produced repeatedly under disk pressure

### ISSUE THREAD

**Issue by nicktming** [kubernetes/kubernetes#94245]
**What happened**:
when a node got disk pressure condition, and a deployment(replicas:1) is deployed to this node using nodename/nodeselector, it will produce many evicted pods until removing this deployment.

**What you expected to happen**:
it should not produce some evicted pods

**How to reproduce it (as minimally and precisely as possible)**:
1. using eviction-hard flag to make a node under disk pressure condition.
2. deploying a deployment with replicas=1 to this node.

**Anything else we need to know?**:
i analysed this problem, since a node is under disk pressure condition, the kubelet will reject this pod with a Failed status, but replicaset controller does not regard this evicted pod as active pods, so replicaset controller will continue to produce pods, which will be rejected by kubelet again. so this will happen repeatedly.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.5
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by gongguan** [comment]
`nodeName` would caused kubelet and controller-manager fight heavily(scheduler won't schedule it), use `nodeAffinity` please, see https://github.com/kubernetes/kubernetes/pull/92966#issuecomment-674809233

**Comment by krmayankk** [comment]
adding /sig scheduling
Another question is does the scheduler take into account disk pressure nodes to avoid those nodes for schedluing. My expecation is that the evicted pod remains pending in this scenario 
@kubernetes/sig-scheduling-bugs  any comments ?

**Comment by gongguan** [comment]
> Another question is does the scheduler take into account disk pressure nodes to avoid those nodes for schedluing. My expecation is that the evicted pod remains pending in this scenario

I don't think it's a sig-scheduling bug. Pod with nodeName will be assigned to certain node directly, that means scheduler won't schedule this pod.

**Comment by nicktming** [comment]
> > Another question is does the scheduler take into account disk pressure nodes to avoid those nodes for schedluing. My expecation is that the evicted pod remains pending in this scenario
> 
> I don't think it's a sig-scheduling bug. Pod with nodeName will be assigned to certain node directly, that means scheduler won't schedule this pod.

agreed

**Comment by MaiSao** [comment]
I have the same problem. How can i help me with this, the deployment (replicaset > 1) loop create evicted Pod ?
