### ISSUE TITLE
Changing server host time after installing k8s cluster can cause problems

### ISSUE THREAD

**Issue by Aaron-23** [kubernetes/kubernetes#94250]
I have a k8s cluster, and the installation time is 1 day faster than the actual time. I want to change the time to the correct time after deploying my business, but the cluster has problems after I am finished. How can I change it correctly? Adjust my server time after installation of k8s cluster？

**Comment by liggitt** [comment]
That seems like your system clock was incorrect when the installation was run. Moving it back in time after the installation is likely to leave you with x509 certificates that are not yet valid. If you used kubeadm to set up, [regenerating certificates](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal) might resolve this issue.

/remove-kind bug
/triage support

**Comment by Aaron-23** [comment]
Thank you, but it is recommended to optimize from a product perspective, because there are many situations like this

**Comment by neolit123** [comment]
> Thank you, but it is recommended to optimize from a product perspective, because there are many situations like this

certificate validity periods are important, so if your node clocks were off, changing them to something outside of the validity would break component connectivity. k8s / kubeadm cannot recover from something like that out of the box without intervention and the procedure is not trivial.

one safer option is to backup your workloads, re-create the cluster, start the workloads again on the new cluster.

alternatively and if you are using kubeadm -  **use this at your own risk**:
- pick a control plane node
- run `kubeadm certs renew all`
- run `kubeadm init phase kubeconfig kubelet`
- run `kubeadm init phase kubelet-finalize`
- run `kubeadm init phase kubelet-start`
- (if you have more than one CP node) run `kubeadm init phase upload-certs --upload-certs` and copy the resulting KEY
- generate a new bootstrap token/join command with `kubeadm token create --print-join-command`
- (if you have more than one CP node) repeat for all other control plane nodes nodes:
  - run `kubeadm reset`
  - rejoin the node using the new join command but also append `--control-plane --certificate-key=KEY`
  - wait for the node to rejoin and workloads to reschedule
- repeat on all worker nodes one at a time
  - `kubeadm reset`
  - rejoin the node using the new join command
  - wait for the node to rejoin and workloads to reschedule

/close
