### ISSUE TITLE
[Flaky Test] pull-kubernetes-e2e-azure-disk-windows: should create a statefulset object, write and read to it, delete the pod and write and read to it again

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubernetes#94269]
**Which jobs are flaking**:
pull-kubernetes-e2e-azure-disk-windows

**Which test(s) are flaking**:
[Fail] Dynamic Provisioning [single-az] [It] should create a statefulset object, write and read to it, delete the pod and write and read to it again
[build-log.txt](https://github.com/kubernetes/kubernetes/files/5133762/build-log.txt)
 [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] 
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/testsuites.go:626

**Testgrid link**:
https://testgrid.k8s.io/provider-azure-presubmit#pr-k8s-azure-disk-e2e-master-windows

**Reason for failure**:
Unknown
**Anything else we need to know**:

    Unexpected error:
        <*errors.errorString | 0xc0007c26a0>: {
            s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00hello world\r\n\"",
        }
        Failed to find "hello world
        hello world
        ", last result: "             hello world
        "
    occurred

**Comment by ZeroMagic** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/93295 
I will try to solve it.

**Comment by MarcPow** [comment]
Ref:[azuredisk-csi-driver/381](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/381)

**Comment by ZeroMagic** [comment]
The PR kubernetes-sigs/azuredisk-csi-driver#515 should fix the error. Let's observe this test case for a period of time. When it is stable, could close the issue.
