### ISSUE TITLE
pull-kubernetes-conformance-kind-ga-only-parallel failing on kind cluster creation due to yaml unmarshal errors

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#94263]
**Which jobs are failing**:

https://testgrid.k8s.io/sig-testing-kind#pull-kubernetes-conformance-kind-ga-only-parallel

**Which test(s) are failing**:

Overall test failure on kind cluster creation

**Since when has it been failing**:

8/26/20 17:08 EDT

**Testgrid link**:

https://testgrid.k8s.io/sig-testing-kind#pull-kubernetes-conformance-kind-ga-only-parallel

**Reason for failure**:

kind cluster creation failure:

```console
 + kind create cluster --image=kindest/node:latest --retain --wait=1m -v=3 --config=/logs/artifacts/kind-config.yaml
ERROR: failed to create cluster: unable to decode config: yaml: unmarshal errors:
  line 11: cannot unmarshal !!str `api/alp...` into map[string]string
Stack Trace: 
sigs.k8s.io/kind/pkg/errors.Wrap
	sigs.k8s.io/kind/pkg/errors/errors.go:39
sigs.k8s.io/kind/pkg/internal/apis/config/encoding.Parse
	sigs.k8s.io/kind/pkg/internal/apis/config/encoding/load.go:73
sigs.k8s.io/kind/pkg/internal/apis/config/encoding.Load
	sigs.k8s.io/kind/pkg/internal/apis/config/encoding/load.go:50
sigs.k8s.io/kind/pkg/cluster.CreateWithConfigFile.func1
	sigs.k8s.io/kind/pkg/cluster/createoption.go:42
sigs.k8s.io/kind/pkg/cluster.createOptionAdapter.apply
	sigs.k8s.io/kind/pkg/cluster/createoption.go:35
sigs.k8s.io/kind/pkg/cluster.(*Provider).Create
	sigs.k8s.io/kind/pkg/cluster/provider.go:139
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.runE
	sigs.k8s.io/kind/pkg/cmd/kind/create/cluster/createcluster.go:80
sigs.k8s.io/kind/pkg/cmd/kind/create/cluster.NewCommand.func1
	sigs.k8s.io/kind/pkg/cmd/kind/create/cluster/createcluster.go:55
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.0.0/command.go:887
sigs.k8s.io/kind/cmd/kind/app.Run
	sigs.k8s.io/kind/cmd/kind/app/main.go:53
sigs.k8s.io/kind/cmd/kind/app.Main
	sigs.k8s.io/kind/cmd/kind/app/main.go:35
main.main
	sigs.k8s.io/kind/main.go:25
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_amd64.s:1374 
```

**Anything else we need to know**:

/sig testing
/assign @BenTheElder 
cc: @kubernetes/ci-signal 
/milestone v1.20
/priority critical-urgent
(as it blocks the 1.20 phased reopen)

**Comment by BenTheElder** [comment]
waiting for https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kind-push-binaries/1298747385475764227 then retesting
/lifecycle active

**Comment by justaugustus** [comment]
Linking fixes: https://github.com/kubernetes-sigs/kind/pull/1819, https://github.com/kubernetes-sigs/kind/pull/1820

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94259/pull-kubernetes-conformance-kind-ga-only-parallel/1298748644094119939 <-- test run

**Comment by BenTheElder** [comment]
cluster is up:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-conformance-kind-ga-only-parallel/1298751537501179905

**Comment by BenTheElder** [comment]
I'm not sure why this took so long to propagate, it seems like somehow some of CI is getting served staler copies ...?
It's a netlify redirect (static redirect to alias the domain so we can swap backing CDN for artifacts) => staging GCS

**Comment by justaugustus** [comment]
"Something, something DNS"?
Thanks for the quick fix, Ben! I've sent the other pending PRs for retest.

/close

**Comment by BenTheElder** [comment]
still failing for a similar reason (no yaml parse error but yaml isn't being plumbed)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1822

**Comment by BenTheElder** [comment]
give it ~4min to upload the new binaries etc.
https://prow.k8s.io/?repo=kubernetes-sigs%2Fkind&type=postsubmit

**Comment by BenTheElder** [comment]
https://prow.k8s.io/?job=pull-kubernetes-conformance-kind-ga-only-parallel very green again
/close
