### ISSUE TITLE
Deamonset rolling update takes longer

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#94270]
**What happened**:
The rolling update strategy still takes in the order of minute, from termination to start of new pod.

The sequence of events upon applying updated manifest:
1) Terminate the current running pod
2) Download the image for new pod
3) Start the new pod

My manifest has:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

Is there a way, make it **_pre-download the new image, before starting the termination_** of current running pod ?

**What you expected to happen**:
To minimize the downtime, it could download the new image and then terminate the old one. Then the downtime would be significantly reduced to mere "pod restart time".

**How to reproduce it (as minimally and precisely as possible)**:
Run the following commands in two different windows/sessions.
kubectl get pods -o wide -w
docker images | grep <the new one>

Now apply updated manifest.

You see the sequence of 
```
snmp-sv2-577ff   1/1     Running   0          47h   10.3.147.253   str-s6000-acs-13   <none>           <none>
snmp-sv2-577ff   1/1     Terminating   0          47h   10.3.147.253   str-s6000-acs-13   <none>           <none>
snmp-sv2-577ff   0/1     Terminating   0          47h   10.3.147.253   str-s6000-acs-13   <none>           <none>
snmp-sv2-577ff   0/1     Terminating   0          47h   10.3.147.253   str-s6000-acs-13   <none>           <none>
snmp-sv2-577ff   0/1     Terminating   0          47h   10.3.147.253   str-s6000-acs-13   <none>           <none>
snmp-sv2-rrkw7   0/1     Pending       0          0s    <none>         <none>             <none>           <none>
snmp-sv2-rrkw7   0/1     Pending       0          0s    <none>         str-s6000-acs-13   <none>           <none>
snmp-sv2-rrkw7   0/1     ContainerCreating   0          0s    10.3.147.253   str-s6000-acs-13   <none>           <none>
snmp-sv2-rrkw7   1/1     Running             0          19s   10.3.147.253   str-s6000-acs-13   <none>           <none>

```
Concurrently, you can see that the download of new image happens, only after the termination is complete.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
 cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux str-s6000-acs-13 4.9.0-11-2-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Thank you in advance!
Renuka

**Comment by renukamanavalan** [comment]
BTW, I double confirmed with tcpdump too. At the time point, when `kubectl get pods -o wide -w` says "creating" is when TCP connection being established with container registry to pull the image down.

Expect: 
1) Pull the image down
2) Stop the current pod
3) Start the new pod

to help minimize down time.

Ref: doc [here](https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/)

**Comment by krmayankk** [comment]
what you really need is some way to maxSurge in DaemonSet so that the downtime is minimized . See [this](https://github.com/kubernetes/enhancements/pull/1590) proposal to add maxSurge to DaemonSet. In this case, a new pod will come up before an old one is brought down

**Comment by renukamanavalan** [comment]
Thank you @krmayankk. I will be looking forward for a code release with this update.

**Comment by tnozicka** [comment]
Thanks for reportin it. We are already tracking it in https://github.com/kubernetes/enhancements/pull/1590 .
/close
