### ISSUE TITLE
error execution phase addon/coredns: unable to match SHA256 digest ID in ""

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#94286]
**What happened**:

during update to v1.19 can not upgrade coredns deployment:

```
# kubeadm init phase addon coredns --config /config/kubeadmcfg.yaml
W0827 17:45:09.167031     251 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH
W0827 17:45:09.167066     251 kubelet.go:213] cannot determine if systemd-resolved is active: no supported init system detected, skipping checking for services
W0827 17:45:09.475045     251 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
error execution phase addon/coredns: unable to match SHA256 digest ID in ""
To see the stack trace of this error execute with --v=5 or higher
```

**What you expected to happen**:

cordns succefully upgraded

**How to reproduce it (as minimally and precisely as possible)**

try to apply my manifests: [coredns.txt](https://github.com/kubernetes/kubernetes/files/5137973/coredns.txt), and do:
```
kubeadm init phase addon coredns
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8 --> v1.19.0
- Cloud provider or hardware configuration: kubefarm
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04.1
- Kernel (e.g. `uname -a`): 5.4.0-42-generic
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
  - [detailed_log.txt](https://github.com/kubernetes/kubernetes/files/5137998/detailed_log.txt)
  - [coredns-pods.txt](https://github.com/kubernetes/kubernetes/files/5138023/coredns-pods.txt)

**Comment by kvaps** [comment]
If I do:
```
kubectl --kubeconfig /etc/kubernetes/admin.conf  delete -n kube-system deploy coredns
```

I can install coredns:
```
# kubeadm init phase addon coredns 
W0827 18:04:16.791421     594 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH
W0827 18:04:16.791463     594 kubelet.go:213] cannot determine if systemd-resolved is active: no supported init system detected, skipping checking for services
W0827 18:04:17.105128     594 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[addons] Applied essential addon: CoreDNS
```

but second run I see the same error:
```
# kubeadm init phase addon coredns 
W0827 18:04:58.721265     605 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH
W0827 18:04:58.721311     605 kubelet.go:213] cannot determine if systemd-resolved is active: no supported init system detected, skipping checking for services
W0827 18:04:59.095994     605 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
error execution phase addon/coredns: unable to match SHA256 digest ID in ""
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by neolit123** [comment]
the linked PR suggests that this happens because you are executing the phase while the Pod is pending?
https://github.com/kubernetes/kubernetes/pull/94299/files

i will comment on the PR.

**Comment by kvaps** [comment]
Very possible, according the logs one of coredns pod was on exactly on Pedning state.

> * [](https://github.com/kubernetes/kubernetes/files/5137998/detailed_log.txt)
> 
> * [coredns-pods.txt](https://github.com/kubernetes/kubernetes/files/5138023/coredns-pods.txt)

**Comment by kvaps** [comment]
Not sure if this covered by kubernetes/kubeadm#2267, but today I've got another error when both pods were on Pending state
https://github.com/kubernetes/kubernetes/issues/94361

**Comment by rosti** [comment]
@kvaps are those pods sitting in Pending state for long? If so, what CNI plugin do you use and is it possible that it contains some errors in its logs?

**Comment by kvaps** [comment]
Hi @rosti, the reason for that is not broken CNI-plugin, but empty cluster.
I'm playing with containerized Kubernetes control-plane, see [Kubernetes-in-Kubernetes](https://github.com/kvaps/kubernetes-in-kubernetes) project.
When you just install the cluster you have no any nodes yet.

**Comment by neolit123** [comment]
i'm going to close this and merge the report in https://github.com/kubernetes/kubeadm/issues/2267
the problem we are trying to solve is handling missing containers and pending pods for the coredns version check.
/close
