### ISSUE TITLE
kubectl proxy not working for kube contexts with base path

### ISSUE THREAD

**Issue by FabianKramm** [kubernetes/kubernetes#94280]
**What happened**:

Given that you have a kube context that looks like this:

```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://my-url-to-kubernetes.com/any-base-path-to-kubernetes
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    client-certificate-data: ANY
    client-key-data: ANY
```

and you try to run `kubectl proxy`, the request `http://localhost:8081/version` fails, because internally the URL is not correctly rewritten to `https://my-url-to-kubernetes.com/any-base-path-to-kubernetes/version` and instead calls `https://my-url-to-kubernetes.com/version`. The problem is in file (at least what I think) https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L231 , where the path needs to be passed as well (also for upgrade connections at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L273)

You can see the problem via `kubectl proxy --v 10`:

```
I0827 14:18:25.042177   30678 loader.go:375] Config loaded from file:  /Users/fabiankramm/.kube/config
Starting to serve on 127.0.0.1:8001
I0827 14:18:28.414766   30678 proxy_server.go:88] /version matched ^.*
I0827 14:18:28.415391   30678 proxy_server.go:88] 127.0.0.1 matched ^127\.0\.0\.1$
I0827 14:18:28.415610   30678 proxy_server.go:128] Filter accepting GET /version 127.0.0.1
I0827 14:18:28.416002   30678 upgradeaware.go:253] Request was not an upgrade
I0827 14:18:28.416841   30678 round_trippers.go:423] curl -k -v -XGET  -H "Cache-Control: max-age=0" -H "Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7" -H "Sec-Fetch-Mode: navigate" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" -H "Accept-Encoding: gzip, deflate, br" -H "X-Forwarded-For: 127.0.0.1" -H "Sec-Fetch-Site: none" -H "Sec-Fetch-User: ?1" -H "Sec-Fetch-Dest: document" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" -H "Upgrade-Insecure-Requests: 1" 'https://test.localhost/version'
I0827 14:18:28.654599   30678 round_trippers.go:443] GET https://test.localhost/version 404 Not Found in 237 milliseconds
I0827 14:18:28.654637   30678 round_trippers.go:449] Response Headers:
I0827 14:18:28.654644   30678 round_trippers.go:452]     Date: Thu, 27 Aug 2020 12:18:29 GMT
I0827 14:18:28.654649   30678 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I0827 14:18:28.654654   30678 round_trippers.go:452]     Content-Length: 21
I0827 14:18:28.654659   30678 round_trippers.go:452]     Server: nginx/1.19.1
```

As you can see the request is made to 'https://test.localhost/version', even though the kube config has a base path of '/kubernetes':

```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: ANY
    server: https://test.localhost/kubernetes
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    client-certificate-data: ANY
    client-key-data: ANY
```

**What you expected to happen**:

The request `http://localhost:8081/version` works, when using `kubectl proxy`

**How to reproduce it (as minimally and precisely as possible)**:

- Spin up a cluster with api root at a different base path like /kubernetes
- Run `kubectl proxy` 
- Try `http://localhost:8081/version` in the webbrowser

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5-dirty
```

**Comment by neolit123** [comment]
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

not this an unsupported skew:
https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl

**Comment by FabianKramm** [comment]
@neolit123 thanks for pointing out, I updated the issue.

**Comment by fedebongio** [comment]
/assign @lavalamp 
(thank you Daniel!)

**Comment by lavalamp** [comment]
Yeah, kubectl proxy doesn't do any rewriting. Given past experience rewriting proxied stuff, I'm not convinced that's wrong.

The problem is that to do it correctly, you have to munge all returned URL-like things so that, when a client sends them back through the proxy in a subsequent request, it works correctly.

Do you have a use case that makes it really difficult to modify your application requests?

If we did want to change this to add path rewriting, I think it'd need to be optional.

**Comment by FabianKramm** [comment]
@lavalamp thanks for clarifying! 

I see your point and I guess I would be fine to make this optional, but I think it is worth a though of making `kube proxy` just always expose the kubernetes api at '/', regardless of how the underlying kube context looks like. This would be much easier for the end user, because otherwise you would have to look up the current kube context and check if there is a base path attached for `kubectl proxy` to always work correctly. Also the documentation and command description never really mentions that.

Our use case is probably a little special, but we provide some sorts of multi Kubernetes cluster API gateway, where users can specify different kube contexts that can be reached from a single endpoint (something like /kubernetes/cluster/name/api/...). Internally we basically just use the `kubectl proxy` code and then reroute the incoming request to the specific `kubectl proxy` handler. Our current workaround is that we modified the `k8s.io/apimachinery/pkg/util/proxy` package to always expose the api at '/', but I guess we could also add the base path at the incoming request itself.

Regarding the returned URL rewriting, in my opinion this is not always needed, since usually kube contexts that have a base path are some sort of API Gateways (like rancher is doing it for example) that just forward the request to a kubernetes cluster without API path prefix and the selfLinks etc. are usually all correct without a prefix (at least in my experience, I could be wrong though). Furthermore, I think there is also no rewriting for `kubectl proxy --api-prefix`, which is kind of similar?

**Comment by lavalamp** [comment]
Yeah, to be clear, I definitely don't think it should attempt any rewriting of the path.

I think I'd be OK with adding the option. Technically SIG CLI owns kubectl, I don't think they'll care but you may want to get sign off from them.

**Comment by FabianKramm** [comment]
@lavalamp thanks, sounds good! Sorry, I'm new to this process, but how can I get them to sign this off? Who do I have to ping exactly?

**Comment by lavalamp** [comment]
Well, we could wait for them to triage issues, but I'm not sure what SIG CLI does there-- we can also [look them up](https://github.com/kubernetes/community/tree/master/sig-cli) and just ping @seans3, @soltysh, @pwittrock

**Comment by FabianKramm** [comment]
@seans3, @soltysh, @pwittrock any chance you take a look at this?

**Comment by pwittrock** [comment]
@eddiezane can you make sure this is part of the next triage?

**Comment by FabianKramm** [comment]
Another example why this might be useful is [lens](https://github.com/lensapp/lens) which uses `kubectl proxy` internally, but currently doesn't work with contexts that have a base path because of the problem described above. Would be really great if `kubectl proxy` would behave consistently with all kube contexts so that apps that build on `kubectl proxy` don't have to solve this problem themselves.

**Comment by FabianKramm** [comment]
@ykakarap @eddiezane @pwittrock Just wanted to check what the status of this issue is, is there any intend of pursuing this? It seems like other people struggle with this issue as well, especially in combination with rancher.  

I could give this a try and submit a pull request (if thats okay), but would like to have some sort of confirmation that this is wanted.

**Comment by ykakarap** [comment]
@FabianKramm Please feel free to take it up. I am afraid I may not be able to work on this in the next few days.

/unassign

**Comment by FabianKramm** [comment]
@ykakarap Great, I opened a PR for this
/assign @FabianKramm

**Comment by rbq** [comment]
I think `kubectl proxy` (and derived projects) should at least fail with an error if connecting to an endpoint with a path is not possible.

Stripping away the path prefix when using Rancher seems to connect to the management cluster instead. Operator Framework uses `kubectl proxy` code to connect your locally developed Operator to the configured context—or so the devs thought. For me as an end user it was actually quite hard to figure out that it connected to a totally different cluster.
