### ISSUE TITLE
node e2e test tags: dedupe [Node.*Feature:Foo][Feature:Foo] anti-pattern

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#94289]
turning https://github.com/kubernetes/kubernetes/pull/94231#discussion_r478088074 into an issue

ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#kinds-of-tests

The `[NodeFeature:Foo]`, `[NodeSpecialFeature:Foo]`, `[NodeAlphaFeature:Foo]` tags are undocumented, and probably shouldn't exist.  They've led to an anti-pattern of `[NodeAlphaFeature:Foo][Feature:Foo]` in tests because `[Feature:.+]` is part of a commonly used skip-regex used by jobs that want to run "the default" set of e2e tests.

Instead of `[NodeAlphaFeature:Foo][Feature:Foo]`, let's use `[NodeAlphaFeature][Feature:Foo]` (and same for the other tags).  This retains the ability to:
- skip non-default features in most e2e jobs (skip `[Feature:.+]`)
- focus on all node alpha features (focus `[NodeAlphaFeature]`)
- focus/skip a specific node alpha feature (focus/skip `[NodeAlphaFeature][Feature:Foo]`)

https://github.com/kubernetes/test-infra/blob/4c9668b157f83ba4bcad2b9c67c307cbb92feeba/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L234 leads me to believe this is the way things used to be? I'm not clear how or why they've evolved to where they are now

I suggest PR's to kubernetes/test-infra to use the old+new tags first, then PR's to this repo to migrate to new tags, then removal of old tags from kubernetes/test-infra.  It would be preferable if we could do this across all actively supported release branches.

/priority important-soon
/area test
FYI @alejandrox1 (is there a test tag hygiene issue to link to?)

/sig node
FYI @SergeyKanzhelev @vpickard (node ci group)

**Comment by spiffxp** [comment]
/assign @SergeyKanzhelev 
to put it on your radar since you mentioned helping out with this, feel free to /unassign or /assign someone more relevant if you'd prefer

**Comment by JornShen** [comment]
do you need some help? I'm interested in this thing.  May be I can do some jobs for yours.

**Comment by SergeyKanzhelev** [comment]
> do you need some help? I'm interested in this thing. May be I can do some jobs for yours.

I think the very first thing would be to discuss the step-by-step enablement for it. Perhaps add new tags to test jobs in test-infra repo. Then update tags in the k/k repo. And finally remove older tags in test-infra repo.

Also I'd like to discuss whether features that moved to GA and doesn't have any flags should still be marked with the Feature tag or not for classification?

If you are interested, do you want to outline in details mentioned steps to make? Or you would be interested to do it once steps has more details?

**Comment by JornShen** [comment]
> > do you need some help? I'm interested in this thing. May be I can do some jobs for yours.
> 
> I think the very first thing would be to discuss the step-by-step enablement for it. Perhaps add new tags to test jobs in test-infra repo. Then update tags in the k/k repo. And finally remove older tags in test-infra repo.
> 
> Also I'd like to discuss whether features that moved to GA and doesn't have any flags should still be marked with the Feature tag or not for classification?
> 
> If you are interested, do you want to outline in details mentioned steps to make? Or you would be interested to do it once steps has more details?

For the whole methods that you mentioned to reach it , I 'm agree with it.I think I know about the direction to do this in general now. So the more details, maybe I am not very familiar with. I would like to do somethings, when the details is given. Or maybe we can discuss it here.

From my understanding, the thing we can do, is to modify the job regrex in test-infra to make it compatible our newtag+oldtag. then we can modify all relevant test case（change old tags to newtags) in k/k repo.  the last one, modify the regrex  in test-infra to just suit the newtags. Three steps, I think is no probem.  if something wrong of my understanding, please  point out it. :)

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

I'm hesitant to start working on it before we have a published guidance on how to use these tags. We are working on it as part of sig node CI group

**Comment by ehashman** [comment]
/remove-lifecycle stale

Let's discuss this next week.

**Comment by ehashman** [comment]
cc @mmiranda96

**Comment by mmiranda96** [comment]
This issue is still relevant, there's an ongoing discussion about it on https://github.com/kubernetes/kubernetes/pull/103674.
/remove-lifecycle stale
