### ISSUE TITLE
Support incremental updates in kubelet?

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#9428]
We send a snapshot of all pods to the kubelet, everytime we add a pod. This leads to 31 parallel workers listing containers and images from docker simultaneously. The 31st container is the most important since it hasn't started yet, while all the others are just status checking. 

Bad for 2 reasons:
1. syncLoop and SyncPods hogs cpu not allowing the 31st worker to run
2. other pod workers hammer docker with lists

Can we avoid this and only resync existing pods in the resyncInterval?
/ref https://github.com/GoogleCloudPlatform/kubernetes/issues/3954

**Comment by yifan-gu** [comment]
Isn't the runtime cache helping with the 2) ?

It seems `resync existing pods in the resyncInterval` will cause the preference on pod creates to pod updates. Is that what we want?

**Comment by bprashanth** [comment]
Hmm, the runtime cache won't help 2 x generatePodStatus in syncPod. We currently resync the whole world on creates, if there aren't creates, we have whatever problems we have. In principle the resync period is precautionary and with incremental updates nothing will really change. In principle.

**Comment by yujuhong** [comment]
This has been fixed. We switched to incremental update in v1.1.
