### ISSUE TITLE
hack/update-generated-protobuf.sh does not generate .pb.go and .proto files

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#94282]
**What happened**:

While working with a PR that updates the API (https://github.com/kubernetes/kubernetes/pull/92744) the `hack/update-generated-protobuf.sh` script stopped to generate grpc files for the updated structure. This worked fine from start and I am unsure when it stopped working. I can't relate it to some update unfortunately.

**What you expected to happen**:

The `hack/update-generated-protobuf.sh` shall generate files, in my case;
```
        modified:   staging/src/k8s.io/api/core/v1/generated.pb.go
        modified:   staging/src/k8s.io/api/core/v1/generated.proto
```

**How to reproduce it (as minimally and precisely as possible)**:

* Update `staging/src/k8s.io/api/core/v1/types.go` with this patch [diff.txt](https://github.com/kubernetes/kubernetes/files/5137392/diff.txt)
* Run `hack/update-generated-protobuf.sh`.

**Anything else we need to know?**:

I have tried to clean the repo, re-clone to a new location. I finally found a work-around by examining the script;
```
./build/run.sh hack/update-generated-protobuf-dockerized.sh k8s.io/api/core/v1
```
The `hack/update-generated-protobuf.sh` make this call with a long list of packages. I call it with just the one I have altered. This works fine.

I wonder if the long list is truncated someplace. And does it happen in my build environent only. I use a standard Ubuntu 18.04.5 LTS and a locally installed go 1.15. Nothing odd.

**Environment**:
- Kubernetes version (use `kubectl version`): master branch.
- Cloud provider or hardware configuration: -
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-42-generic #46~18.04.1-Ubuntu SMP
- Install tools: -
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery

**Comment by fedebongio** [comment]
/assign @sttts 
Stefan, would you mind taking a look to this one please? Thanks in advance!

**Comment by uablrek** [comment]
This was my fault.

I had a script named "bash" in my path. It called the real bash so it did not show. However is somehow caused this seemingly unrelated problem.

Sorry to waste your time.

**Comment by uablrek** [comment]
FYI The trigger was that the SHELL in the Makefile was changed from "/bin/bash" to "/usr/bin/env bash".
