### ISSUE TITLE
CRD update from v1beta1 to v1

### ISSUE THREAD

**Issue by vivekzhere** [kubernetes/kubernetes#94295]
**What happened**: 
Our [operator ](https://github.com/cloudfoundry-incubator/service-fabrik-broker/tree/master/helm-charts/interoperator) was using a crd.v1beta1.apiextensions.k8s.io and recently updated to crd.v1.apiextensions.k8s.io. In v1beta1 definition `spec.preserveUnknownFields` set as true. In the v1 version some fields have the  `x-kubernetes-preserve-unknown-fields` set as true. When we do a helm upgrade(we use helm3 with crds in the crd folder), the crd version gets updated to `crd.v1.apiextensions.k8s.io` with the `versions` array format, but `spec.preserveUnknownFields` is still set an true and the `x-kubernetes-preserve-unknown-fields` field is not at all present in the definition. Our operator copies the crds to another cluster and this fails with
```
"CustomResourceDefinition.apiextensions.k8s.io \"sfplans.osb.servicefabrik.io\" is invalid: spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead"
```

**What you expected to happen**:
The new crds definitions to be correctly applied.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy [interopertor v0.9.0](https://github.com/cloudfoundry-incubator/service-fabrik-broker/releases/tag/0.9.0) or earlier which uses `crd.v1beta1.apiextensions.k8s.io `. Upgrade to [interopertor v0.9.1](https://github.com/cloudfoundry-incubator/service-fabrik-broker/releases/tag/0.9.1) or newer, which uses `crd.v1.apiextensions.k8s.io` . 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Tested on k8s 1.16.12 and 1.18.5
- Cloud provider or hardware configuration: gcp and aws
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Do you have the v1 CRD manifest that is being applied? What mechanism does helm use to update and create an object?

**Comment by liggitt** [comment]
spec.preserveUnknownFields cannot be set to true when creating v1 CRDs.

To get consistent results when applying an object which was created via a different API version, you may need to explicitly set fields in your manifest like ".spec.preserveUnknownFields: false"

**Comment by vivekzhere** [comment]
@liggitt  CRD based on [apiextensions.k8s.io/v1beta1](https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/0.9.0/helm-charts/interoperator/crds/sfplan.yaml)  does not explicitly set `spec.preseveUnknownFields` at all. Our CRD based on [apiextensions.k8s.io/v1](https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/0.9.1/helm-charts/interoperator/crds/sfplan.yaml) also does not have this field. But it uses `x-kubernetes-preserve-unknown-fields` for some fields

**Comment by liggitt** [comment]
If you do not specify the field in the v1beta1 or v1 manifest, you'll be left with the default value for that field of whatever version the object was created with. The default v1beta1 value of false is not permitted in new v1 CRDs, which is why the operator copying the CRD to a new cluster is not working. 

Explicitly setting `spec.preserveUnknownFields: false` in your v1 CRD manifest would make updates match the behavior of creating the v1 CRD via that manifest.
