### ISSUE TITLE
Support customized gcc and cross compilation of kubernetes on platforms other than amd64

### ISSUE THREAD

**Issue by bnrjee** [kubernetes/kubernetes#94291]
**What would you like to be added**:
There should be a way to override the default gcc compliers mentioned in the [golang.sh](https://github.com/kubernetes/kubernetes/blob/35942f65709d73a8bb8c42904eb6ca3204f0e29a/hack/lib/golang.sh#L397) file with custom gcc compilers for different platforms. Also, cross compilation should be supported on platforms other than amd64.

**Why is this needed**:
Right now, there seems to be no way to override the platform specific cc flags that kubernetes sets. We should be able to override those values.
For example, bottlerocket sets customized CC flags for different platforms using this [patch](https://github.com/bottlerocket-os/bottlerocket/blob/41a72fe21400fa227543fcbed2e59eb0a8b633c1/packages/kubernetes-1.17/0001-always-set-relevant-variables-for-cross-compiling.patch). We should be able to override the default values in kubernetes using environment variables or build time flags and build kubernetes with customized gcc variants that bottlerocket uses. Also, we need an option to set gcc compilers for amd64 platform, so that amd64 targets can be built on different platforms.

**Comment by bnrjee** [comment]
sig/release

**Comment by BenTheElder** [comment]
> Also, cross compilation should be supported on platforms other than amd64.

Sure, that will require cross building the build toolset itself, which nobody has taken up yet.
